### ISSUE TITLE
Variable Substitution

### ISSUE THREAD

**Issue by kduenke** [MicrosoftDocs/vsts-docs#1000]
Is variable substitution supported for Arguments (Optional) Command arguments?  Currently, I've tried $(), documented here...
https://docs.microsoft.com/en-us/vsts/pipelines/release/variables?view=vsts&tabs=batch#using-custom-variables

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fc7eeb7f-4e6b-8fee-1d7f-582cfb018b02
* Version Independent ID: 00fb3082-1069-9060-012c-0b6d75ef120b
* Content: [Package and deploy Helm Charts](https://docs.microsoft.com/en-us/vsts/pipelines/tasks/deploy/helm-deploy?view=vsts#qa)
* Content Source: [docs/pipelines/tasks/deploy/helm-deploy.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/pipelines/tasks/deploy/helm-deploy.md)
* Product: **devops**
* GitHub Login: @erickson-doug
* Microsoft Alias: **dastahel**

**Comment by kduenke** [comment]
False alarm.  This completely works fine.  I just made a simple mistake.  I forgot to save my release definition after linking my variable group.

**Comment by steved0x** [comment]
@kduenke Thanks for letting us know and glad to hear you got it working.
