### ISSUE TITLE
Image Type-O

### ISSUE THREAD

**Issue by SauceTheBoss** [MicrosoftDocs/vsts-docs#1002]
The last image (effective-tfvc-branching-strategies-for-devops-complex.png) has a type-o above the 2nd branch.  It should read "Rel V2.0"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 357101ee-b4ac-33e8-984a-20590ba91360
* Version Independent ID: e0fc3848-cfe7-2bed-3097-1a7acbcb268f
* Content: [Manage branching strategies in TFVC for DevOps](https://docs.microsoft.com/en-us/vsts/articles/effective-tfvc-branching-strategies-for-devops?view=vsts)
* Content Source: [docs/articles/effective-tfvc-branching-strategies-for-devops.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/articles/effective-tfvc-branching-strategies-for-devops.md)
* Product: **devops**
* GitHub Login: @wpschaub
* Microsoft Alias: **willys**

**Comment by steved0x** [comment]
@SauceTheBoss Thanks for letting us know, I'll get this fixed.
