### ISSUE TITLE
How to run cpack

### ISSUE THREAD

**Issue by canmor** [MicrosoftDocs/vsts-docs#1004]
Is it possible to run cpack?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6fa6eec-60ed-0a5c-7f79-a53088cf089e
* Version Independent ID: 8a0a6b23-293e-c8c1-79bd-9409b11a8733
* Content: [CMake build and release task](https://docs.microsoft.com/en-us/vsts/pipelines/tasks/build/cmake?view=vsts)
* Content Source: [docs/pipelines/tasks/build/cmake.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/build/cmake.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by chrisrpatterson** [comment]
Running a command line tool from a script in CI is a pretty standard thing to do.  I am not sure I would say it is not elegant.
