### ISSUE TITLE
Customization

### ISSUE THREAD

**Issue by adammulroy** [MicrosoftDocs/vsts-docs#1005]
Is there any plans in the future to allow these filters to be customizable? For instance, we would like custom fields we create to be filterable. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b3b77a32-4cd0-3c02-12b2-c18f57ab3057
* Version Independent ID: 9c357297-9c80-ab6e-d35f-c2d66288b0f6
* Content: [Filter your Kanban board - VSTS & TFS](https://docs.microsoft.com/en-us/vsts/work/kanban/filter-kanban-board?view=vsts#feedback)
* Content Source: [docs/work/kanban/filter-kanban-board.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/work/kanban/filter-kanban-board.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@adammulroy - Thank you for your inquiry. I recommend that you add your suggestion to our User Voice site - https://visualstudio.uservoice.com/forums/330519-team-services where are Product Managers can reply to your feature request.
