### ISSUE TITLE
Non default branch

### ISSUE THREAD

**Issue by banza** [MicrosoftDocs/vsts-docs#1006]
Hello, this functionallity seemingly doesn't work on non default branch in TFS2018. I have default branch, and I have policy on it and everything work fine. But I've created policy on another branch in the same repo and i can complete PR without external service approval.
I dont now this right place for post this. Sorry.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a9a3fce3-aa8f-c5e5-5b10-da912f6941fc
* Version Independent ID: c36e9af9-cc20-c264-0525-2ca7e7d9ad8e
* Content: [Configure a branch policy for an external service](https://docs.microsoft.com/en-us/vsts/git/how-to/pr-status-policy?view=vsts)
* Content Source: [docs/git/how-to/pr-status-policy.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/git/how-to/pr-status-policy.md)
* Product: **devops**
* GitHub Login: @mmitrik
* Microsoft Alias: **mmitrik**

**Comment by mmitrik** [comment]
@banza Will you open a ticket on the [Developer Community](https://developercommunity.visualstudio.com/spaces/22/index.html)?  Any additional details you can provide, such as screenshots of the policy configuration would be helpful.  Thanks!
