### ISSUE TITLE
Markdown link not converted to HTML

### ISSUE THREAD

**Issue by jawn** [MicrosoftDocs/vsts-docs#1007]
The following markdown is visible multiple times in this web page:
I tried fixing it in the markdown, but don't know why the link is not replaced.
 [Artifact Link Types API](https://docs.microsoft.com/rest/api/vsts/wit/artifact link types/list)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dcb1a9df-f8c9-517d-187c-558cefafd7af
* Version Independent ID: 0db222d4-244e-5b9d-1002-292112381f52
* Content: [Link type element reference - VSTS & TFS](https://docs.microsoft.com/en-us/vsts/work/customize/reference/link-type-element-reference?view=tfs-2018)
* Content Source: [docs/work/customize/reference/link-type-element-reference.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/work/customize/reference/link-type-element-reference.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by steved0x** [comment]
@jawn Thanks for letting us know, my guess would be the spaces in the URL need to be URL encoded, I have assigned this to the author of the article to take a look. Thank you.

**Comment by KathrynEE** [comment]
@jawn - Thank you for the correction. I'm updating the topic and the changes should be live later today.
