### ISSUE TITLE
Cannot upload .msg file to VSTS Pull Request Comment

### ISSUE THREAD

**Issue by ahaleiii** [MicrosoftDocs/vsts-docs#1015]
Trying to attach an Outlook .msg file in a reply to a VSTS Pull Request comment results in an error:

![image](https://user-images.githubusercontent.com/7021001/41190460-cbb03ef2-6bac-11e8-970d-aabfdcbdacd1.png)

[According to the docs:](https://go.microsoft.com/fwlink/?linkid=838045)
> Attachments support the following file formats: ... Documents ... Microsoft Office Message (.msg)

Are there certain limitations to .msg files being uploaded to VSTS? Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 63e81f8a-e33c-afb7-493b-f51f40fafd49
* Version Independent ID: c9495a96-c3e8-00f1-1e53-da6ce584412b
* Content: [Syntax usage for Markdown files, widgets, wikis, and pull requests - VSTS & TFS](https://docs.microsoft.com/en-us/vsts/collaborate/markdown-guidance?view=vsts#attachments)
* Content Source: [docs/collaborate/markdown-guidance.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/collaborate/markdown-guidance.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@ahaleiii - Thank you for your comment. The .msg file format isn't supported in pull requests. I've updated the topic to indicate that.
