### ISSUE TITLE
Show example out puts for versioning Scheme

### ISSUE THREAD

**Issue by StevenTCramer** [MicrosoftDocs/vsts-docs#1018]
#versioningScheme: 'off' # Options: off, byPrereleaseNumber, byEnvVar, byBuildNumber

The documentation does not show examples of what the versions will actually be for the various options. (Would save much time)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0fa37a3f-6551-16ad-e164-a4ac522cdaab
* Version Independent ID: a3fd6935-2b99-92ef-4eb3-3249fca01f8a
* Content: [NuGet restore, pack, and publish](https://docs.microsoft.com/en-us/vsts/pipelines/tasks/package/nuget?view=vsts#feedback)
* Content Source: [docs/pipelines/tasks/package/nuget.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/package/nuget.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by steved0x** [comment]
@StevenTCramer Thanks for letting us know, I am assigning this to the author of the article to get it fixed.

**Comment by elbatk** [comment]
@alexmullans hey, can we throw some examples inline here?

**Comment by alexmullans** [comment]
Sure. 

For byPrereleaseNumber, the version will be set to whatever you choose for major, minor, and patch, plus the date and time in the format yyyymmdd-hhmmss.

For byEnvVar, the version will be set as whatever environment variable e.g. $(MyVersion) you provide, so make sure the environment variable is set to a proper SemVer e.g. 1.2.3 or 1.2.3-beta1.

For byBuildNumber, the version will be set to the build number, so you should ensure that your build number is a proper SemVer e.g. 1.0.$(Rev:r).

**Comment by elbatk** [comment]
Awesome, thanks Alex. I hope this helps, @StevenTCramer , I'm adding this to the documentation as well to help future inquirers :)

**Comment by StevenTCramer** [comment]
Yes will save the next guy some time.  Thanks :)

**Comment by webchetan** [comment]
> Sure.
> 
> For byPrereleaseNumber, the version will be set to whatever you choose for major, minor, and patch, plus the date and time in the format yyyymmdd-hhmmss.
> 
> For byEnvVar, the version will be set as whatever environment variable e.g. $(MyVersion) you provide, so make sure the environment variable is set to a proper SemVer e.g. 1.2.3 or 1.2.3-beta1.
> 
> For byBuildNumber, the version will be set to the build number, so you should ensure that your build number is a proper SemVer e.g. 1.0.$(Rev:r).

Hi Alex - I am able to do a Build pipeline successfully. But I am not able to figure out how I can do a Release pipeline from existing build artifact with automatic versioning. Should I add yaml file something like below to the root of my nuget project and that will overwrite the build pipeline step of dotnet pack?

```
steps:
- task: DotNetCoreCLI@2
  displayName: 'dotnet pack'
  inputs:
    command: pack

    configuration: '\Debug'

    versioningScheme: byPrereleaseNumber

    majorVersion: 5

```

Anyway I can have the release SemVer to pick up values from the git master branch tags? so if I tag master branch with v5.0.1, the build triggers and makes a release with package version as 5.0.1

Any help would be appreciated.

Thank you.
