### ISSUE TITLE
does not work with .net core

### ISSUE THREAD

**Issue by kirakosyan** [MicrosoftDocs/vsts-docs#1020]
more than one year old issue
https://github.com/NuGet/Home/issues/4491

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f2512189-84f9-f997-0255-13b276c233b4
* Version Independent ID: c7ccb0ba-4221-bdac-85e1-111eaf51943b
* Content: [Publish NuGet packages from Team Build to Package Management](https://docs.microsoft.com/en-us/vsts/pipelines/packages/nuget-pack-publish?view=vsts)
* Content Source: [docs/pipelines/packages/nuget-pack-publish.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/packages/nuget-pack-publish.md)
* Product: **devops**
* GitHub Login: @erickson-doug
* Microsoft Alias: **amullans**

**Comment by steved0x** [comment]
@alexhomer1 Is this one in your area? Do you know the answer?

**Comment by alexhomer1** [comment]
Thank you for your feedback. I have passed this on to the product team for advice.

**Comment by alexmullans** [comment]
I chatted with @elbatk about this - we'll make some updates to the NuGet in build docs page to more clearly reflect when you should use the .NET Core task vs the NuGet task. Also, @anangaur and team are working on making the original linked issue better.
