### ISSUE TITLE
Not able to see Download PDF Link ? 

### ISSUE THREAD

**Issue by dotnetstep** [MicrosoftDocs/vsts-docs#1021]
Most of the documentation at https://docs.microsoft.com has Download PDF as link. By using that we can download documentation as PDF which is very useful but over here I can not see such link.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7e5835c5-57ca-e68d-f033-d97ec7bd106f
* Version Independent ID: 20ff829f-93d5-b3b8-8a34-612a9a5dc841
* Content: [DevOps at Microsoft - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/devops-at-microsoft/)
* Content Source: [https://mseng.visualstudio.com/DefaultCollection/TechnicalContent/_git/devops-learn-pr?path=%2fdocs%2fdevops-at-microsoft%2findex.md&version=GBlive&_a=contents](https://mseng.visualstudio.com/DefaultCollection/TechnicalContent/_git/devops-learn-pr?path=%2fdocs%2fdevops-at-microsoft%2findex.md&version=GBlive&_a=contents)
* Product: **devops**
* Git Login: **samgu**
* Microsoft Alias: **samgu**

**Comment by steved0x** [comment]
I'm adding this and it should be live soon.
