### ISSUE TITLE
automatically @mention in script

### ISSUE THREAD

**Issue by dinye** [MicrosoftDocs/vsts-docs#1024]
Is it possible to use "@mention" in python script and automatically @ someone when the script runs? Thx!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 34ae521f-6ae4-4d7f-2cce-f844e5811b66
* Version Independent ID: 18098490-1f34-e966-3135-cb90197bfa6f
* Content: [Use @mentions in work items and pull requests - VSTS and TFS - VSTS & TFS](https://docs.microsoft.com/en-us/vsts/notifications/at-mentions?toc=/vsts/user-guide/toc.json&bc=/vsts/user-guide/breadcrumb/toc.json&view=vsts)
* Content Source: [docs/notifications/at-mentions.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/notifications/at-mentions.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by elbatk** [comment]
@willsmythe pretty straightforward question here, I think. Mind helping me @dinye out?

**Comment by dinye** [comment]
@willsmythe, do you have any updates on this? It would be really useful to my team. Thanks!

**Comment by AUFOOD** [comment]
Aufood

**Comment by elbatk** [comment]
Hey @willsmythe , pinging ya on this older GHI to see if we can get an answer :)

**Comment by dinye** [comment]
Here is an example of my python code: 
bug.add_comment('close as xxxx bug')

and

def add_comment(self, comment):
        self['System.History'] = comment

Is it possible to '@someone'?

**Comment by kiranchand** [comment]
Email address may also be used in @mention as below.

@<nobody@nowhere.com>: Can we follow PIP8 coding standards please?

**Comment by elbatk** [comment]
I'm going to close this as it doesn't look like a docs bug but more of a feature question. Pinging @chcomley to see if she knows who on the product team could potentially come in here and sneak an answer about notifications.

**Comment by TobiasZawada** [comment]
@elbatk @chcomley I am also very interested in script-generated notifications (Elisp generating HTML content). Where is the continuation of this feature request? Thanks in advance for any substantial information.

**Comment by chcomley** [comment]
Hi @dinye, After some searching, I haven't found a feature request and would suggest that you create it, and then link back to it within this issue, so that it can be upvoted. I've added @roferg for any possible feedback here. Thank you.
