### ISSUE TITLE
Markdown visible in analytics views documentation

### ISSUE THREAD

**Issue by jawn** [MicrosoftDocs/vsts-docs#1029]
Screenshot:

![image](https://user-images.githubusercontent.com/1705112/41276562-dd7f37c6-6e24-11e8-828e-c87c8d8c4576.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 508bfe7d-16cf-7b44-53a7-26a9f9563be8
* Version Independent ID: f365dd42-530f-e145-5dd3-28420237bc7b
* Content: [What are Analytics views? - VSTS](https://docs.microsoft.com/en-us/vsts/report/analytics/what-are-analytics-views?view=vsts)
* Content Source: [docs/report/analytics/what-are-analytics-views.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/report/analytics/what-are-analytics-views.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@jawn - Thank you for bringing this to our attention. I saw the same problem yesterday, and updated several topics. So the fixes are in now.
