### ISSUE TITLE
Mistake with JobStatus values?

### ISSUE THREAD

**Issue by stewx** [MicrosoftDocs/vsts-docs#1030]
This page lists a value for Agent.JobStatus "SucceededWithIssues". This other documentation refers to a different value, however: "PartiallySucceeded". If both are valid, that should be mentioned here. Otherwise, only the correct one should be listed.

https://docs.microsoft.com/en-us/vsts/pipelines/process/conditions?view=vsts

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ffebdc8-521c-44b5-cde4-4abdc1bd6f18
* Version Independent ID: dc0effda-6d93-62aa-64c5-4e6f283b0826
* Content: [Build variables](https://docs.microsoft.com/en-us/vsts/pipelines/build/variables?view=vsts&tabs=batch#feedback)
* Content Source: [docs/pipelines/build/variables.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/build/variables.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by andyjlewis** [comment]
We've got a backlog item to update this topic.

**Comment by andyjlewis** [comment]
@stewx thank you for reporting this issue. The fix is now in our internal master and should roll out in next day or so.
