### ISSUE TITLE
Missing Link?

### ISSUE THREAD

**Issue by draevin** [MicrosoftDocs/vsts-docs#1032]
I believe there's a missing link in the last section of the Branching section for the Git column of the table. It appears that "See Use Git branches to switch contexts, suspend work, and isolate risk." should be a link after "See" based on context, as well as its sibling in the TFVC column. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a1dc9a4a-7828-f40f-4cf0-e0b1f5476ff2
* Version Independent ID: 278aed60-558e-3beb-2ed4-c2517c2cd05d
* Content: [Git and TFVC version control](https://docs.microsoft.com/en-us/vsts/tfvc/comparison-git-tfvc?view=vsts#feedback)
* Content Source: [docs/tfvc/comparison-git-tfvc.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/tfvc/comparison-git-tfvc.md)
* Product: **devops**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by thesoftwarejedi** [comment]
Bump. Agreed. 

It looks like a page with that title doesn’t exist. This is a good candidate. https://docs.microsoft.com/en-us/vsts/repos/git/gitquickstart

There’s several others though.
