### ISSUE TITLE
More Broken Hyperlinks

### ISSUE THREAD

**Issue by SamGrantham** [MicrosoftDocs/vsts-docs#1033]
Under SQL Server High Availability features Supported by Team Foundation Server the link:

Use SQL Server 2012 Always On Availability Groups with Team Foundation Server (https://docs.microsoft.com/en-us/install/sql-server/use-always-on-groups) 

is dead... also this is supposed to be about the config of TFS for Always on not about the SQL Config? which I think is this:

https://docs.microsoft.com/en-us/tfs/server/install/sql-server/use-always-on-groups?view=vsts

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 641b37fc-f117-aca0-32f4-8ea9b73e9d71
* Version Independent ID: 211130c6-43b8-f47f-3589-cb4d2a330231
* Content: [Requirements and compatibility](https://docs.microsoft.com/en-us/tfs/server/requirements?view=vsts#sql-server)
* Content Source: [docs/server/requirements.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/server/requirements.md)
* Product: **devops-server**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by steved0x** [comment]
@SamGrantham Thank you for letting us know, we'll get these fixed. I'm assigning this to the author of this article.

**Comment by SamGrantham** [comment]
Thank you much!

**Comment by elbatk** [comment]
Hi @SamGrantham , I plan fixing the dead link to point to the article you've linked to, in your second bit are you saying that article isn't in the context of the link here?

**Comment by elbatk** [comment]
Doing some backlog cleaning and closing this one out as resolved, thanks for the heads up on the broken links!
