### ISSUE TITLE
tfs content links here but repo is missing `docs/server` folder

### ISSUE THREAD

**Issue by nschonni** [MicrosoftDocs/vsts-docs#1034]
If you create an issue from https://docs.microsoft.com/en-us/tfs/server/install/sql-server/use-always-on-groups?view=vsts it point to `https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/server/install/sql-server/use-always-on-groups.md` which doesn't exist here.

Is it just on the private repo for now, or a comment system bug?

**Comment by steved0x** [comment]
@nschonni Let me look into this and see what is happening - some of the TFS docs are in a different place now (note the `/tfs/` part of the URL that replaces the `/vsts/` part that most of the other docs have (except release notes).
