### ISSUE TITLE
Incorrect documentation

### ISSUE THREAD

**Issue by andre-capri-iag** [MicrosoftDocs/vsts-docs#1037]
I went and checked the docs on this page and happily found the variable I was looking for put it in to my release pipeline and much to my dismay it did not work.
Obviously I had made a mistake I thought, was this the wrong docs, was I looking at the TFS maybe? Or maybe even made a mistake in inputing it on the release.
So I went about debugging and found that another artifact variable was indeed working.
Now I'm sure that the user experience is important to the developers of this document so get your stuff together and fix it.
Specifically I tried to use the SourceBranch variable with a git artifact.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 611642f0-881f-10b9-ae94-3c562001d1f0
* Version Independent ID: 41efb94b-4c7a-64a3-b23b-70c8634ae727
* Content: [Variables in Release Management](https://docs.microsoft.com/en-us/vsts/pipelines/release/variables?view=vsts&tabs=batch#feedback)
* Content Source: [docs/pipelines/release/variables.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/release/variables.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment]
Thank you for your feedback. I will pass this on to the product team and update the topic based on their response.

**Comment by shashban** [comment]
The available artifact variables are based on the type of the artifacts. SourceVersion is not available for Git artifact type. This is captured in https://docs.microsoft.com/en-us/azure/devops/pipelines/release/variables?view=vsts&tabs=batch#artifact-variables
