### ISSUE TITLE
Missing variable Build.SyncSources

### ISSUE THREAD

**Issue by cecedxx** [MicrosoftDocs/vsts-docs#1039]
This documentation doesn't contain the variable `Build.SyncSources` as the blog below mentioned:
https://blogs.msdn.microsoft.com/tfssetup/2017/09/25/disabling-get-sources-step-in-vnext-build/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ffebdc8-521c-44b5-cde4-4abdc1bd6f18
* Version Independent ID: dc0effda-6d93-62aa-64c5-4e6f283b0826
* Content: [Build variables](https://docs.microsoft.com/en-us/vsts/pipelines/build/variables?view=vsts&tabs=batch)
* Content Source: [docs/pipelines/build/variables.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/build/variables.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by andyjlewis** [comment]
That's not how you do it today on VSTS. Instead, on the Tasks tab, select Get sources, and then clear the Don't sync sources checkbox.

**Comment by cecedxx** [comment]
It seems this option only exists in `VSTS Git`.
