### ISSUE TITLE
Broken link for creating VSTS organizations

### ISSUE THREAD

**Issue by stewartadam** [MicrosoftDocs/vsts-docs#1042]
Link is broken in this statement from the article:
*You must have an organization created in VSTS. If you haven't created one yet, [do that now](https://docs.microsoft.com/en-us/vsts/accounts/set-up-vs.md).*

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4107b23a-ba0a-5a1b-b689-072717cfe8ec
* Version Independent ID: 1ed09ce9-be9b-6146-9cb8-a2a50e12a3c2
* Content: [Add a custom rule to a work item type to an inherited process - VSTS](https://docs.microsoft.com/en-us/vsts/organizations/settings/work/custom-rules?toc=/vsts/work/customize/toc.json&bc=/vsts/work/customize/breadcrumb/toc.json&view=vsts)
* Content Source: [docs/organizations/settings/work/custom-rules.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/settings/work/custom-rules.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@stewartadam - Thank you for reporting this issue. I'm fixing the content and it should be live later today.
