### ISSUE TITLE
Content is showing markdown, not html content

### ISSUE THREAD

**Issue by BillRaymond** [MicrosoftDocs/vsts-docs#1043]
When viewing this document on the Microsoft site, it is displaying with markdown rather than HTML.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 574443d9-7dc6-8fba-f549-2781def08395
* Version Independent ID: bfa2a8a3-f07a-0859-4282-0becc46e692f
* Content: [Create an Analytics view - VSTS](https://docs.microsoft.com/en-us/vsts/report/analytics/analytics-views-create?view=vsts)
* Content Source: [docs/report/analytics/analytics-views-create.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/report/analytics/analytics-views-create.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@BillRaymond  - Thank you for reporting this issue. I've fixed the content format issues.
