### ISSUE TITLE
gitからvssに変更したい

### ISSUE THREAD

**Issue by cidrugHug8** [MicrosoftDocs/vsts-docs#1046]
1ソリューションに含まれる複数のプロジェクトが1つのフォルダ以下に無い場合にgitで管理できないので、ソース管理をgitからvssに変更したいが、やり方が分からない。

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: beb650b9-47d2-4f04-97c9-22b9b6ddeeb9
* Version Independent ID: 74ac33fd-0fee-1b22-b783-9ed9c83a23be
* Content: [Create a new Git repo](https://docs.microsoft.com/ja-jp/vsts/git/tutorial/creatingrepo?view=vsts&tabs=visual-studio)
* Content Source: [docs/git/tutorial/creatingrepo.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/git/tutorial/creatingrepo.md)
* Product: **devops**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
Translation: `1 If multiple projects included in the solution are not under one folder, you can not manage with git, so I'd like to change source control from git to vss but I do not know how to do it.`

**Comment by mmitrik** [comment]
> from git to vss

@steved0x, can we confirm that this translation is correct?  VSS has not been supported for several years, so this is not a recommended approach.

If I assume the desire is to go **to Git**, and you have multiple projects in a single solution, I would generally recommend that everything that's needed to build the solution should be included in a single Git repo.  It will be much easier to version everything atomically if it's in a single repo.

You _could_ consider placing the projects in separate repos, but then managing changes across repos becomes difficult.  You'll need additional strategies like submodules (which are complex and the tooling is immature) or non-version control based solutions like packages and semantic versioning.  It's hard to make a perfect suggestion here without more knowledge about the specifics.

**Comment by steved0x** [comment]
@cidrugHug8 I'm closing this issue, but please open up a new issue if the information here didn't help. Thank you for your feedback.

**Comment by pmiossec** [comment]
I think by using 'vss', he was thinking about TFVC.
Git is perfectly able to handle multiple projects or solution in a repository.
If the monorepo strategy is not enough, use `git submodules`.
