### ISSUE TITLE
Non-hosted agent pools

### ISSUE THREAD

**Issue by PJBowron** [MicrosoftDocs/vsts-docs#1050]
Is it, or will it be, possible to use yaml configurations with non-hosted agent pools?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 87686bea-7c46-cd47-d1a9-128e16b63a23
* Version Independent ID: ace78317-e562-e35d-781d-23cd7d2dfff2
* Content: [CI Build in code using YAML](https://docs.microsoft.com/en-us/vsts/pipelines/build/yaml?view=vsts#learn-more)
* Content Source: [docs/pipelines/build/yaml.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/build/yaml.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by andyjlewis** [comment]
Yes, you can run YAML builds on private agents.
