### ISSUE TITLE
TFS 2017

### ISSUE THREAD

**Issue by minherz** [MicrosoftDocs/vsts-docs#1051]
Does this feature exist in one of releases of TFS 2017? I have Update 2 RTM (Version 15.117.26714.0) and I do not see this feature in the branch policy.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a9a3fce3-aa8f-c5e5-5b10-da912f6941fc
* Version Independent ID: c36e9af9-cc20-c264-0525-2ca7e7d9ad8e
* Content: [Configure a branch policy for an external service](https://docs.microsoft.com/en-us/vsts/git/how-to/pr-status-policy?view=vsts)
* Content Source: [docs/git/how-to/pr-status-policy.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/git/how-to/pr-status-policy.md)
* Product: **devops**
* GitHub Login: @mmitrik
* Microsoft Alias: **mmitrik**

**Comment by mmitrik** [comment]
Pull request status extensibility is available in TFS 2018 Update 2 (see the [release notes](https://docs.microsoft.com/en-us/visualstudio/releasenotes/tfs2018-update2#pull-request-status-extensibility)).  

@steved0x should we have a note on this page to indicate the TFS version where this is available?

**Comment by steved0x** [comment]
@minherz I have updated the documentation to reflect that PR Status Branch Policy is supported in TFS 2018 Update 2 and it should be live later today or Monday. Thanks for bringing it to our attention.
