### ISSUE TITLE
How to make manuel testing, on master ?

### ISSUE THREAD

**Issue by ardumez** [MicrosoftDocs/vsts-docs#1053]
I have difficulty with my team for manuel testing, if we merge on master and after doing manual testing on master there are possibility of conflict with other new merge, and the QA dont know what deploy. We don't have infrastructure for create env by pull request for doing test befor merge on master

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe168fc3-2ed2-b3e6-ce30-cac721165ceb
* Version Independent ID: 8d63fbd7-12c4-9a94-92f6-969e7eb41037
* Content: [Git branching guidance](https://docs.microsoft.com/en-us/vsts/git/concepts/git-branching-guidance?view=vsts)
* Content Source: [docs/git/concepts/git-branching-guidance.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/git/concepts/git-branching-guidance.md)
* Product: **devops**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
@ardumez Can you give me some more details on your scenario? For example, a step by step list of what you are doing, and then where the missing piece or the problem comes in?

Possibly a [build validation policy](https://docs.microsoft.com/en-us/vsts/git/branch-policies?view=vsts#build-validation) would work for you?

Please let me know more details of your scenario and then I can help further or get the right person to advise.

Thanks, Steve

**Comment by ardumez** [comment]
Hello, 
Thanks for your reply.
I have make an example with Kanban Board and Git Branch Strategy

![image](https://user-images.githubusercontent.com/9568904/41657354-72caa706-7493-11e8-985e-508a9bcfa847.png)

-----
![image](https://user-images.githubusercontent.com/9568904/41657372-804cc1d4-7493-11e8-9dd8-8354f200db37.png)

-----

![image](https://user-images.githubusercontent.com/9568904/41657394-9207ec0a-7493-11e8-8b7c-d7a2074c6654.png)

**Comment by dalee-bis** [comment]
If you can't use feature flags, it seems to me that you have one of either two problems:

1. You are trying to perform QA Validation on part of a release or
2. You are merging features into the master branch before they have been fully approved.

I've never used feature flags but I gather they work best if are having regular releases. If you can't use feature flags or have a slower release cycle, I would recommend [GitFlow](https://nvie.com/posts/a-successful-git-branching-model/?) which allows you to batch features up into a release branch. The release branch then goes through QA and is deployed. While it is in QA, it is in a "feature freeze" meaning there are no new features going into the branch and only bugfixes can be made. This gets around merge conflict and release issues.
