### ISSUE TITLE
Request for naming conventions for Tags in VSTS

### ISSUE THREAD

**Issue by erptechnician** [MicrosoftDocs/vsts-docs#1062]
This article is very useful, and I refer to it often. However, it seems to completely omit any information regarding naming convention of Tags in VSTS.

Would it be possible to add a section in this document specifically for Tags so that new VSTS users and administrators will have some guidance?  It would be useful to know things such as maximum length, disallowed characters, and other rules governing the creation of new Tags.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 82305566-bf0a-20ca-46b0-4a011ea65e0b
* Version Independent ID: 59b2347e-dc58-ee34-0000-c2c8eb309901
* Content: [Naming restrictions and conventions - VSTS & TFS](https://docs.microsoft.com/en-us/vsts/organizations/settings/naming-restrictions?view=vsts)
* Content Source: [docs/organizations/settings/naming-restrictions.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/settings/naming-restrictions.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@erptechnician - Thank you for your feedback. I've reached out to the product team for guidelines which I'll publish once I receive them.
