### ISSUE TITLE
HTTP Error 502.5 - Process Failure

### ISSUE THREAD

**Issue by justlearntutors** [MicrosoftDocs/vsts-docs#1075]
Followed each step. Once the project is released to the windows server, I am checking the public ip address.

Your github project uses ASP.NET core 2, but your .NET Core SDK is 1.

Website: http://104.43.242.117/
DNS: http://justlearntest.centralus.cloudapp.azure.com

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a373b706-b74b-51af-f1e9-b549dae4c747
* Version Independent ID: dd1fc4e5-fcd2-5667-e327-2d3f25261e84
* Content: [Deploy your ASP.NET Core app to a Windows VM](https://docs.microsoft.com/en-us/vsts/pipelines/apps/cd/azure/aspnet-core-to-windows-vm?view=vsts&tabs=vsts#import-code-for-sample-app-into-vsts)
* Content Source: [docs/pipelines/apps/cd/azure/aspnet-core-to-windows-vm.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/apps/cd/azure/aspnet-core-to-windows-vm.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by justlearntutors** [comment]
# Install the .NET Core SDK
Invoke-WebRequest https://go.microsoft.com/fwlink/?linkid=848827 -outfile $env:temp\dotnet-dev-win-x64.1.0.4.exe
Start-Process $env:temp\dotnet-dev-win-x64.1.0.4.exe -ArgumentList '/quiet' -Wait

The .NET Core version is 1.0

**Comment by andyjlewis** [comment]
fixed: https://github.com/MicrosoftDocs/pipelines-dotnet-core
