### ISSUE TITLE
"Inline" 'Powershell Script' task - is that TFS 2017 only?

### ISSUE THREAD

**Issue by queBurro** [MicrosoftDocs/vsts-docs#1076]
I'm having to use a Peter Groenewegen's third party "Run Inline Powershell" tool to achieve the same thing with TFS2015. If this doc is incorrect please can you fix it, if not can you point me at the correct task.  Thanks, 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 611642f0-881f-10b9-ae94-3c562001d1f0
* Version Independent ID: 41efb94b-4c7a-64a3-b23b-70c8634ae727
* Content: [Variables in Release Management](https://docs.microsoft.com/en-us/vsts/pipelines/release/variables?view=vsts&tabs=powershell)
* Content Source: [docs/pipelines/release/variables.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/release/variables.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment]
Thank you for your feedback. I have passed this on to the product team for advice.

**Comment by chasewilson** [comment]
Hey @queBurro Sorry for the really late reply, I've recently taken over some of the Docs effort so I will hopefully answer any, if any questions you still have here :) Does the following doc answer your questions? 
[TFS 2015 PowerShell task](https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/powershell?view=tfs-2015)

**Comment by chasewilson** [comment]
I'll be closing this issue. If my response doesn't answer your question, I hope you'll open a new issue. Thanks for the feedback :)
