### ISSUE TITLE
Who has the full source code?

### ISSUE THREAD

**Issue by wzk64657534** [MicrosoftDocs/vsts-docs#1081]
Who has the full source code?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5515c697-786f-e5d2-60fa-a62192c2e9c1
* Version Independent ID: 1fc22c8f-1b7b-32fa-0ec2-05e0b741103e
* Content: [Use the Grid Control](https://docs.microsoft.com/en-us/vsts/extend/develop/ui-controls/grido?view=vsts)
* Content Source: [docs/extend/develop/ui-controls/grido.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/extend/develop/ui-controls/grido.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by elbatk** [comment]
Hi @wzk64657534 , we do not have the full source for these samples, is there a specific question I can help you with?

**Comment by elbatk** [comment]
Hi @wzk64657534 , sorry for the abnormally long delay, a couple of GHI just fell through the cracks on me. We have SDK docs here: https://docs.microsoft.com/en-us/azure/devops/extend/reference/client/core-sdk?view=azdevops and we are looking into expanding them/making them more complete. I hope this helps!
