### ISSUE TITLE
PowerShell v2 Arguments

### ISSUE THREAD

**Issue by VerdonTrigance** [MicrosoftDocs/vsts-docs#1083]
I see in documentation Arguments there is Arguments parameter, but in version 2 no such parameter. How to pass -Verbose to PowerShell v.2 ?

**Comment by steved0x** [comment]
@VerdonTrigance Thank you for the feedback, can you let me know which article it goes with so I can pass it along to the right author for review? Thank you.

**Comment by VerdonTrigance** [comment]
Yes, of cause. But not now :) I just remember it was from VSTS powershell action tooltip link.

**Comment by steved0x** [comment]
@elbatk Elijah can you help with this one?

**Comment by elbatk** [comment]
Are you trying to do it via a powershell script or from the command line? This may be a better question in the [VSTS tasks GitHub repo ](https://github.com/Microsoft/vsts-tasks). Is this issue related? https://github.com/Microsoft/vsts-tasks/issues/3245

If you could point me to the documentation that you found on this issue we could route it better for ya.

**Comment by VerdonTrigance** [comment]
@elbatk No, I mean documentation https://docs.microsoft.com/en-us/vsts/pipelines/tasks/utility/powershell?view=vsts is talking about "Arguments" argument, but in version 2 there is no such argument actually.
![image](https://user-images.githubusercontent.com/12109173/41736519-6febdc46-7595-11e8-82b2-b4f21f952ec0.png)

**Comment by elbatk** [comment]
Looping in @andyjlewis and @chrisrpatterson

**Comment by vtbassmatt** [comment]
Arguments are only accepted for a file-based script, not an inline script. And this is now correctly documented.
