### ISSUE TITLE
Not supporting tables

### ISSUE THREAD

**Issue by remanation** [MicrosoftDocs/vsts-docs#1085]
We are using TFS 2018 update 1 (16.122.27409.2). I seem that tables are not supported in .md files :-( If I add tables in my readme.md file it is not displayed when viewing the file. The same table snippet works fine for a PR comment.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fa622358-f5bb-1f5c-177a-081a37b6acef
* Version Independent ID: 72f7fd16-a822-66c8-3a34-8905645ce5f2
* Content: [Syntax usage for Markdown files, widgets, wikis, and pull requests - VSTS & TFS](https://docs.microsoft.com/en-us/vsts/project/wiki/markdown-guidance?view=vsts#tables)
* Content Source: [docs/project/wiki/markdown-guidance.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/project/wiki/markdown-guidance.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@remanation - Thank you for your feedback.  I believe that tables should be supported in README.md files for TFS 2018. If you're having problems with this feature, please reach out to https://developercommunity.visualstudio.com/spaces/21/index.html.
