### ISSUE TITLE
Can this be put on the Zendesk marketplace so it is considered a public app?

### ISSUE THREAD

**Issue by tannermlx** [MicrosoftDocs/vsts-docs#1086]
Right now since it is technically a private app you have to upgrade to the next plan with a price difference of $59 vs $25, seems a little ridiculous when it could be resolved by an upload. 

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c1646acb-1bd0-d506-fe70-1b749cccbbc4
* Version Independent ID: 89aa9387-8ce6-9877-8e90-5f7c655b4b77
* Content: [Zendesk with VSTS](https://docs.microsoft.com/en-gb/vsts/service-hooks/services/zendesk?view=vsts#feedback)
* Content Source: [docs/service-hooks/services/zendesk.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/service-hooks/services/zendesk.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by rlesavre** [comment]
We are interested by this too, regards

**Comment by sotiriszegiannis** [comment]
can you try our app which is already on marketplace

https://www.zendesk.com/apps/support/integratecloud-connector-for-vsts/?source=app_directory

**Comment by nschonni** [comment]
@sotiriszegiannis if they're trying to avoid paying to upload the extension, I don't think promoting your other paid product is a useful suggestion

**Comment by tannermlx** [comment]
@sotiriszegiannis I am already paying in excess of $600 dollars for the combined services. I'm not interested in using your product, if I were I would be doing that instead of holding Microsoft accountable for supporting the features in a way that makes them accessible to their smaller customers.  I also think, if I were to be brash, advertising a product in a support ticket is ignominious.

**Comment by sotiriszegiannis** [comment]
Hi guys.Accept my apologies if i offended anyone. This was clearly not the intention.It seems that this post was not the place to advertise our app. Please accept my sincere apologies.
Sotiris

**Comment by nschonni** [comment]
Since this is a product issue rather than a docs one, it probably makes sense to close in favour of https://github.com/Microsoft/vsts-zendesk-app/issues/27

**Comment by elbatk** [comment]
That is correct, @nschonni . @tannermlx , please see the [Publish to Zendesk Marketplace GitHub Issue](https://github.com/Microsoft/vsts-zendesk-app/issues/27). Or also feel free to post a suggestion to the [Azure DevOps Services UserVoice](https://visualstudio.uservoice.com/forums/330519-visual-studio-team-services). Closing this issue here as this is not a docs-related issue.
