### ISSUE TITLE
Broken link in the article

### ISSUE THREAD

**Issue by sistoimenov** [MicrosoftDocs/vsts-docs#1087]
In the article under section "Create a new pull request" - first bullet point has a link to "Create a pull request" which cannot be opened - it returns 403 status code.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a9a3fce3-aa8f-c5e5-5b10-da912f6941fc
* Version Independent ID: c36e9af9-cc20-c264-0525-2ca7e7d9ad8e
* Content: [Configure a branch policy for an external service](https://docs.microsoft.com/en-us/vsts/git/how-to/pr-status-policy?view=vsts)
* Content Source: [docs/git/how-to/pr-status-policy.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/git/how-to/pr-status-policy.md)
* Product: **devops**
* GitHub Login: @mmitrik
* Microsoft Alias: **mmitrik**

**Comment by steved0x** [comment]
@sistoimenov Thanks for catching that, I just fixed it and it should be live in a day or two.
