### ISSUE TITLE
Define "above" :)

### ISSUE THREAD

**Issue by giwleb** [MicrosoftDocs/vsts-docs#1088]
Stop and uninstall the service as explained above. - where is above?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 022dbf46-5ccf-ac17-f47a-7557b98bcbd6
* Version Independent ID: cfd090f9-4428-d4f9-224e-9e42805e08c0
* Content: [Remove and re-configure an agent](https://docs.microsoft.com/en-us/vsts/pipelines/agents/_shared/v2/remove-and-reconfigure-unix?view=vsts)
* Content Source: [docs/pipelines/agents/_shared/v2/remove-and-reconfigure-unix.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/agents/_shared/v2/remove-and-reconfigure-unix.md)
* Product: **devops**
* GitHub Login: @erickson-doug
* Microsoft Alias: **douge**

**Comment by andyjlewis** [comment]
Thank your for the heads up. This piece of content is not meant to be viewed independently. We're working on trying to get it removed from the site. Meanwhile, see either https://docs.microsoft.com/en-us/vsts/pipelines/agents/v2-osx or https://docs.microsoft.com/en-us/vsts/pipelines/agents/v2-linux

**Comment by andyjlewis** [comment]
Just an FYI, we've turned off display of shared snippets like this one. Thanks again for reporting this issue.
