### ISSUE TITLE
Missing image /tfs/server/_img/add-administrator-tfs/people-and-groups.png

### ISSUE THREAD

**Issue by nschonni** [MicrosoftDocs/vsts-docs#1092]
The image with the alt text "Follow instructions for your version of SharePoint" doesn't resolve

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1a6dbc38-c975-8045-8910-d87483e3446e
* Version Independent ID: d9c4ddff-7e03-6fc3-9f20-a2e281a1d6a1
* Content: [Set SharePoint permissions for TFS](https://docs.microsoft.com/en-ca/vsts/organizations/security/set-sharepoint-permissions?view=tfs-2017#feedback)
* Content Source: [docs/organizations/security/set-sharepoint-permissions.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/security/set-sharepoint-permissions.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@nschonni - Thank you for the feedback. I'm correcting this now and the fix should be live later today.
