### ISSUE TITLE
Remove branch-policy

### ISSUE THREAD

**Issue by rogatec** [MicrosoftDocs/vsts-docs#1097]
Unfortunately in this documentation there is no part where we can delete a branch policy which was added by test purpose/accident.
My user account is in the Team Foundation-Administrators group, is in the default project administrator group and also I created the branch-policy.
I don't know how I can remove the protection of this branch. There is a documentation which I've found [Remove Check-In Policies](https://docs.microsoft.com/en-us/vsts/tfvc/remove-check-policies?view=vsts) but I can't find these settings on our tfs server (we don't use VSTS!).

Any hints where I can change this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7cd986e0-608c-1d8c-6faf-ecdb12e10bc6
* Version Independent ID: d60c996e-187e-dd6b-7f3a-dd056a1603f4
* Content: [Protect your Git branches with policies](https://docs.microsoft.com/en-us/vsts/git/branch-policies?view=vsts)
* Content Source: [docs/git/branch-policies.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/git/branch-policies.md)
* Product: **devops**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
@rogatec You should be able to follow the steps in that article for configuring branch policies for your desired branch, and uncheck all the boxes and then save the policy, which should effectively clear it. Which branch policy or policies do you have enabled for that branch that you want to clear?

The link you gave was for TFVC which has its own types of permissions and protections but not the same thing as Git branches and branch policies - just as a quick confirmation, you are talking about Git branches and branch policies? That might be why you can't find those settings, if you are not using TFVC.

**Comment by rogatec** [comment]
Well... I didn't recognize that if I remove all policies then I can remove the policy.

Thanks @steved0x

**Comment by steved0x** [comment]
@rogatec I'll make an update to the documentation to make that more clear. Thanks for the great feedback.

**Comment by didii** [comment]
I know this is an old issue, but clearing all the boxes does not do the same when policies can be inherited.
I've recently found out that this was possible and created a branch policy for the `releases/*` branch. But now all existing branches still have a policy applied that overrides the parent one.
I'd like to remove them all so that they all correctly inherit the policy from `releases/*`.
