### ISSUE TITLE
Microsoft test  mangaer

### ISSUE THREAD

**Issue by Shankarkl** [MicrosoftDocs/vsts-docs#1102]
[Enter feedback here]
Not  able to play back the recorded actions ,overwritting existing actions pop up is not been displayed
It was working fine before but when i updated mtm 2015 to mtm 2017 above issue is occuring

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2cc84c9a-f2a6-5919-f709-17572bc3bad4
* Version Independent ID: 37ad2179-bd90-a98c-cabf-4007224ab549
* Content: [Test configurations, specifying test platforms](https://docs.microsoft.com/en-us/vsts/test/mtm/test-configurations-specifying-test-platforms?view=vsts)
* Content Source: [docs/test/mtm/test-configurations-specifying-test-platforms.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/test/mtm/test-configurations-specifying-test-platforms.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment]
Thank you for your feedback. I have passed this on to the product team for advice.

**Comment by harishkragarwal** [comment]
Hi @Shankarkl, sorry to hear this. Do reach us at devops_tools@microsoft.com and share snapshots/short video in the process so that we can investigate this. 
Once resolved, the resolution can be posted here for everyone else's benefit. Thanks.
