### ISSUE TITLE
Validate identities failed

### ISSUE THREAD

**Issue by ravneetDevops** [MicrosoftDocs/vsts-docs#1107]
I am getting error while TFSMigrator. 
[Info   @16:47:04.299] Validating service identities
[Error  @16:47:05.120] Microsoft.TeamFoundation.Framework.Server.ActionDeniedBySubscriberException: Exception of type 'Microsoft.TeamFoundation.Framework.Server.ActionDeniedBySubscriberException' was thrown.
please help
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a35b397-3fe8-122e-042e-280326f88a38
* Version Independent ID: 3e0f0afc-abeb-01be-d767-813cd6ad78db
* Content: [Migration import from TFS to Visual Studio Team Services (VSTS)](https://docs.microsoft.com/en-us/vsts/articles/migration-import?view=vsts)
* Content Source: [docs/articles/migration-import.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/articles/migration-import.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by steved0x** [comment]
Note, possibly related to https://github.com/MicrosoftDocs/vsts-docs/issues/1108

**Comment by roofers** [comment]
Hi @ravneetDevops - Can you email a copy of your full TfsMigrator.log to vstsdataimport@microsoft.com? We can take a look and help you out there.

**Comment by ravneetDevops** [comment]
Hi roofers, - I was able to resolve the issue by detaching the TFS collection and attaching it before running the TFSMigrator /validate. Thank you

**Comment by elbatk** [comment]
Looks like we got this one sorted out, going to go ahead and close the issue, let us know if you have any other issues @ravneetDevops . Thank you @roofers.

**Comment by 199219921992** [comment]
> Hi roofers, - I was able to resolve the issue by detaching the TFS collection and attaching it before running the TFSMigrator /validate. Thank you



> Hi roofers, - I was able to resolve the issue by detaching the TFS collection and attaching it before running the TFSMigrator /validate. Thank you

How did you attached the collection when it is dettached?
