### ISSUE TITLE
TFS (on prem) Support for Enterprise Github? 

### ISSUE THREAD

**Issue by ianceicys** [MicrosoftDocs/vsts-docs#1110]
Is there any documentation for setting up TFS (on prem) to work with Github enterprise?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 75a10513-2af9-8e16-61a4-25d4b09f6d32
* Version Independent ID: 788acaa2-d5a1-1d0d-18f4-e94a4e2fe2c9
* Content: [Define a CI build process for your GitHub repository](https://docs.microsoft.com/en-us/vsts/pipelines/build/ci-build-github?view=vsts#q--a)
* Content Source: [docs/pipelines/build/ci-build-github.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/build/ci-build-github.md)
* Service: **vsts**
* Product: **devops**
* GitHub Login: @mlearned
* Microsoft Alias: **mlearned**

**Comment by mlearned** [comment]
you can set up the service connection like via this blog https://blogs.msdn.microsoft.com/mihansen/2018/05/05/team-foundation-server-and-github-enterprise-in-azure/  @ianceicys

**Comment by mlearned** [comment]
@ianceicys  we have some new docs around this being published (updates to the existing doc) that will be mentioning TFS as well.
