### ISSUE TITLE
File Transform and Variable substitutions not available for IIS Web App Deploy task

### ISSUE THREAD

**Issue by tlemke11** [MicrosoftDocs/vsts-docs#1112]
The WinRM - IIS Web App Deploy task (https://github.com/Microsoft/vsts-rm-extensions/blob/master/Extensions/IISWebAppDeploy/Src/Tasks/IISWebAppDeploy/README_IISAppDeploy.md)
does not have anywhere where it shows "File Transform and Variable Substitution Options" section. With the same project, the "Azure App Service Deploy task" does show these options.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 315ff823-9992-9f9b-62a1-42ce622ed41c
* Version Independent ID: 72ec3ffc-1dc9-b2dc-e3d4-4f14deae3720
* Content: [File transforms and variable substitution](https://docs.microsoft.com/en-us/vsts/pipelines/tasks/transforms-variable-substitution?view=vsts#feedback)
* Content Source: [docs/pipelines/tasks/transforms-variable-substitution.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/transforms-variable-substitution.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment]
Thank you for your feedback. Some of the extension tasks (as opposed to the built-in tasks) have different sets of parameters due to their specialist nature. However, I have passed your feedback on to the product team for comment.

**Comment by 24mu13** [comment]
Any suggested workaround while you're working on that?

**Comment by tlemke11** [comment]
Im using this https://colinsalmcorner.com/post/end-to-end-walkthrough-deploying-web-applications-using-team-build-and-release-management until I get some feedback. I still cant find the https://docs.microsoft.com/en-us/vsts/pipelines/tasks/deploy/iis-web-app-deployment-on-machine-group?view=vsts task within VSTS.

**Comment by azooinmyluggage** [comment]
The approach used by Colin in the blog post is correct. We are considering making File transforms and variable substitution a separate task instead of adding it to each task which needs similar functionality.

**Comment by thinkriver** [comment]
Hi @azooinmyluggage , do you have any more information about the 'File transforms and variable substitution' task ? We need a task from MS. Do you have any time frame for this one ? Thanks.

**Comment by kolexinfos** [comment]
Any plan to add these to the WinRM - IIS Web App Deployment tasks? It is available in the Deploy Azure App Service deployment tasks, what is the hold up just add it to this too.
