### ISSUE TITLE
Broken include docs/_shared/qa-vsts-sla.md

### ISSUE THREAD

**Issue by nschonni** [MicrosoftDocs/vsts-docs#1114]
Was searching for something and noticed this was broken from the search results.
- Heading is stuck to text
- The link is partially formed

I would have PR'd but even fixing the link to add back the starting text https://www.microsoft.com/en-us/support/legal/sla/visual-studio-team-services/v1_2 is still a dead link

**Comment by steved0x** [comment]
@nschonni The correct location is here:

https://azure.microsoft.com/support/legal/sla/visual-studio-team-services/v1_2/

I fixed it and it should be live today or tomorrow. Thank you!
