### ISSUE TITLE
Deprication information is incorrect.

### ISSUE THREAD

**Issue by SamGrantham** [MicrosoftDocs/vsts-docs#1115]
Hi,
Rather than add another place this must be maintained can you please refer to https://docs.microsoft.com/en-us/vsts/report/powerbi/connect-vso-pbi-vs?view=vsts, this product is fully UNSUPPORTED at this point and any page that says otherwise is a Customer Satisfaction issue waiting to happen.

Thank you,
Sam

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a874f64-4330-f3c5-b75f-24bc474b2c83
* Version Independent ID: 9034e780-4edc-415c-db3a-64243f5775ea
* Content: [Power BI integration overview - VSTS](https://docs.microsoft.com/en-us/vsts/report/powerbi/overview?view=vsts)
* Content Source: [docs/report/powerbi/overview.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/report/powerbi/overview.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@SamGrantham - Thanks for the reminder. I'm removing the files and adding redirects as needed. Updates should be live later today.

**Comment by mclizz** [comment]
v1.0-401f6b28af0ff8606aecd9c2-f36eb74e64b5c00550d257ae8857224c9f80274215f1e9f49e80724b1cbda53926b75fd1b25253aa4cff89040ea6046fbca3055cb9c5022e1561cf78cede81a18bfa5119cef59472
