### ISSUE TITLE
Clarify this is about agent-based extensions and add link to the doc on authoring server-based extensions.

### ISSUE THREAD

**Issue by konrad-jamrozik** [MicrosoftDocs/vsts-docs#1116]
Namely, to this doc:
https://github.com/Microsoft/vsts-tasks/blob/master/docs/authoring/servertaskauthoring.md

I was misled by this documentation. After hours of searching, I ended up asking question on internal MS StackOverflow. The answer pointed me to the doc mentioned above:
https://stackoverflow.microsoft.com/questions/102928/is-vsts-service-bus-endpoint-extension-posting-directly-to-service-bus-deprecate

Thanks!
Konrad

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 44581f4a-93df-7507-3844-eadedf9a6cc4
* Version Independent ID: 33c7bcf0-1512-975f-5ef8-9f2a192a84ad
* Content: [Add a Build or Release Task](https://docs.microsoft.com/en-us/vsts/extend/develop/add-build-task?view=vsts)
* Content Source: [docs/extend/develop/add-build-task.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/extend/develop/add-build-task.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by elbatk** [comment]
Ah, sorry for the time we wasted for ya. Thanks for this contribution suggestion and I've added a blurb saying this article covers agent tasks and agent-based extensions and a link to the server task doc @konrad-jamrozik . It should go live by end of day!
