### ISSUE TITLE
Out of date 

### ISSUE THREAD

**Issue by MeltdownZA** [MicrosoftDocs/vsts-docs#1117]
This is out of date, there is no 'Configure Continuous Delivery' option in Azure when selecting a Web App.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f9e617bc-bf8d-0348-5fd4-7b040e4d2ff3
* Version Independent ID: ded5c7ec-feee-b573-ffbf-c972d25135bb
* Content: [Deploy your app to an Azure web app](https://docs.microsoft.com/en-us/vsts/pipelines/apps/cd/azure/aspnet-core-to-azure-webapp?view=vsts&tabs=vsts)
* Content Source: [docs/pipelines/apps/cd/azure/aspnet-core-to-azure-webapp.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/apps/cd/azure/aspnet-core-to-azure-webapp.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment]
Thank you for your feedback. The previous Continuous Deployment feature was a preview and has now been updated to a new experience called Deployment Center, which offers extended functionality. We are currently working on an updated topic for this.
