### ISSUE TITLE
Available icons

### ISSUE THREAD

**Issue by norman-v** [MicrosoftDocs/vsts-docs#1120]
Where can I get info on available icons? It would be great if it was mentioned here as it is used here a lot.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 766b8f6f-72a2-76a8-40cf-a81affd7250e
* Version Independent ID: abdbb5f7-1fe8-ab84-f275-2d8abf36418c
* Content: [Use the Menubar Control](https://docs.microsoft.com/en-us/vsts/extend/develop/ui-controls/menubaro?view=vsts#javascript_action_menubar)
* Content Source: [docs/extend/develop/ui-controls/menubaro.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/extend/develop/ui-controls/menubaro.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by elbatk** [comment]
Hi @norman-v , sorry for being half a year late on this, some issues have just fallen through the cracks for me somehow. I'm not sure if we have info on the available icons that you can use here, sorry about that.
