### ISSUE TITLE
Pass secret argument

### ISSUE THREAD

**Issue by Doomblaster** [MicrosoftDocs/vsts-docs#1121]
Is it in any way possible to pass a secret from a library to a deploy service fabric application task? From what I read you need to pass secrets as an argument to a task, but I can't really see any way to do this in that task. Currently I'm trying to override ApplicationParameters/Cloud.xml with a secret variable, but only seems to work when the parameter is plain text.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7068e469-201e-c820-4d27-b798ea799b70
* Version Independent ID: d6bb717a-1c44-43a1-c7a5-9616b257c0e0
* Content: [Service Fabric Application Deployment task for use in the phases of all of your build and release definitions in Microsoft VSTS and TFS](https://docs.microsoft.com/en-us/vsts/pipelines/tasks/deploy/service-fabric-deploy?view=vsts)
* Content Source: [docs/pipelines/tasks/deploy/service-fabric-deploy.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/deploy/service-fabric-deploy.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment]
Thank you for your feedback. I have passed this on to the product team for advice.

**Comment by pulkitaggarwl** [comment]
To make sure we are on same page,couple of clarifying questions

- are you using "Override application parameters" check box in Service Fabric Application deployment task ?
- If yes, is the issue that the parameters are getting replaced variables are plain text but  not when we mark them as secret ?


![image](https://user-images.githubusercontent.com/36596168/41718725-74552702-757b-11e8-9f64-47a44bb6a94f.png)

**Comment by Doomblaster** [comment]
That is correct. Only plain text variables seem to be replaced.

**Comment by aljo-microsoft** [comment]
@Doomblaster 
I'm not sure if this issue is still applicable or if @pulkitaggarwl answer solved your problem.

@athinanthny for visibility.

@MicahMcKittrick-MSFT 
Can you please follow up with the user, and #please-close if their issue was solved by answer provided?

**Comment by alexhomer1** [comment]
Thank you for your feedback. If you are still having issues, you may like to post details on the Developer Community website at https://developercommunity.visualstudio.com/spaces/21/index.html, where they are tracked by the product teams. Thank you.
