### ISSUE TITLE
Is it available for on prem tfs 2017?

### ISSUE THREAD

**Issue by syedhassanabbas** [MicrosoftDocs/vsts-docs#1122]
documentation state its applicable for "VSTS | TFS 2018 | TFS 2017 | TFS 2015 | TFS 2013" I have TFS 2017  with Update 3. when I hit my TFS base URL post fixed with _admin/_users or _users is gives 404/Not found. Is it only available for VSTS?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 361c08ef-48be-de59-d223-595cadc65a7b
* Version Independent ID: 4bab93d0-8ee5-5e18-a217-c5f6a3eea441
* Content: [Export access level audit log - VSTS & TFS](https://docs.microsoft.com/en-us/vsts/organizations/security/export-users-audit-log?view=vsts)
* Content Source: [docs/organizations/security/export-users-audit-log.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/security/export-users-audit-log.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@syedhassanabbas - Thank you for your inquiry. Please use the version selector in the upper left corner of the page to see the content that addresses your TFS version. The **Users** tab isn't a supported feature for TFS. 
![image](https://user-images.githubusercontent.com/10856840/41864311-5a7995d0-785e-11e8-9660-49a3374e7346.png)

**Comment by syedhassanabbas** [comment]
Thanks got it, it’s probebly not that intuitive.
