### ISSUE TITLE
Import from VSTS to VSTS

### ISSUE THREAD

**Issue by mferris2421** [MicrosoftDocs/vsts-docs#1125]
The documentation suggests that we can import a VSTS repo. Currently I am trying to import from the same account to a different project.

Is this possible?

Currently i am getting the following error:

**Import request cannot be processed due to one of the following reasons:
Clone URL is incorrect.
 Clone URL requires authorization.
Clone URL points to an empty repository.**

**Comment by steved0x** [comment]
@mferris2421 You should be able to do that - but it requires authorization, and you can put in your username and personal access token that allow you to access the repo to be imported. Are you importing into VSTS or are you using TFS? (Well you say same account but different project so it is all on VSTS?)

As a quick check, can you clone the repo to be imported to a new location using the same credentials that you are using to try and import?

Let me know what you find and then we can figure out the next step. 

Thanks,

Steve

**Comment by mferris2421** [comment]
I'm running it from my work laptop. I can clone the repo. I tried with my credentaisl, and I tried to create a PAT with all permissions and I still received that same error.

Same account, same subscription, different team projects.

I ended up doing it manually with git commands.

**Comment by mferris2421** [comment]
I was shown the error of my ways. It's been a while, but I believe I was using the PAT incorrectly with my username.
