### ISSUE TITLE
click on the pie segment

### ISSUE THREAD

**Issue by Iloer** [MicrosoftDocs/vsts-docs#1126]
Good afternoon!
It would not be bad, after clicking on the segment of the diagram, not to go over the entire query, but apply the filter to the selected segment.

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: dcb11d2d-86bd-ff52-d191-4da86d54b473
* Version Independent ID: 79438e17-b3d3-0331-5040-98107eb840a2
* Content: [Dashboards, charts, & widgets - VSTS & TFS](https://docs.microsoft.com/ru-ru/vsts/report/dashboards/overview?irgwc=1&OCID=AID681541_aff_7593_1243925&tduid=(ir_2lZUWvStDSkG3xmTelWAWVIIUkjT3tW8ty32WE0)(7593)(1243925)(TnL5HPStwNw-NslM6UjlsaLxFr09Fft5hQ)()&irclickid=2lZUWvStDSkG3xmTelWAWVIIUkjT3tW8ty32WE0&view=vsts)
* Content Source: [docs/report/dashboards/overview.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/report/dashboards/overview.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by steved0x** [comment]
@Iloer Thank you for your feedback. The issues in this repo are intended for documentation feedback, and it sounds like your feedback is a product feature request. You can file this feature request at the following link, and it will go directly to the product team.

https://developercommunity.visualstudio.com/spaces/21/index.html

I am assigning this feedback to the author of that article in case they can provide any additional feedback before closing this issue. Thank you again for your feedback.
