### ISSUE TITLE
Don't see the Change link on the account page

### ISSUE THREAD

**Issue by Allann** [MicrosoftDocs/vsts-docs#1128]
The Account Setting page does not appear as shown above in the documentation, and the Account owner field is just a straight textbox with a clear button.  Change owner instructions should be changed to reflect this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5939e96c-d796-e1a7-8440-7c4f932d4eb0
* Version Independent ID: ccd071f0-1419-31b0-409e-eadea10dcbbe
* Content: [Troubleshoot changing account owner for VSTS](https://docs.microsoft.com/en-us/vsts/accounts/faq-change-account-ownership?view=vsts#find-owner-pca)
* Content Source: [docs/accounts/faq-change-account-ownership.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/accounts/faq-change-account-ownership.md)
* Product: **devops**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
@Allann Thanks for letting us know. I've created a work item for this update, thank you.
