### ISSUE TITLE
Run build first and the status policy

### ISSUE THREAD

**Issue by asadabbas88** [MicrosoftDocs/vsts-docs#1129]
Is there a way to run build first completely and then the status check policy .. Currently it runs the status check policy because its faster .. due to which the results are not correct as after build is completed status might be changed in my case ..

So can any one help in it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a9a3fce3-aa8f-c5e5-5b10-da912f6941fc
* Version Independent ID: c36e9af9-cc20-c264-0525-2ca7e7d9ad8e
* Content: [Configure a branch policy for an external service](https://docs.microsoft.com/en-us/vsts/git/how-to/pr-status-policy?view=vsts)
* Content Source: [docs/git/how-to/pr-status-policy.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/git/how-to/pr-status-policy.md)
* Product: **devops**
* GitHub Login: @mmitrik
* Microsoft Alias: **mmitrik**

**Comment by asadabbas88** [comment]
any one here?

**Comment by mmitrik** [comment]
@asadabbas88 What build system are you using?  If you're using VSTS build, you shouldn't need to do status checks at all - there is a built-in build policy you should use instead.  Check out this doc for details: https://docs.microsoft.com/en-us/vsts/git/branch-policies?view=vsts#build-validation

**Comment by asadabbas88** [comment]
@mmitrik thanks for the response .. yes it posts the status but issue is my build succeeds .. sonar doesn't break the build .. It doesn't break the build on quality gate failure

**Comment by asadabbas88** [comment]
@mmitrik did you get my point?

**Comment by asadabbas88** [comment]
not relavant now
