### ISSUE TITLE
Run Phase if Specific Previous Phase Failed

### ISSUE THREAD

**Issue by alpacamybags118** [MicrosoftDocs/vsts-docs#1130]
Is there a way to specific to run a phase only if a *specific* previous phase failed?

For example, I want to trigger an Agentless Phase with a manual intervention only if a specific previous Agent Phase that has my Integration Test job fails, and not if any other phase fails.

I looked around in the documentation and didn't see anything that allowed you to specify a specific phase. Any help would be appreciated!

**Comment by alexhomer1** [comment]
If you are using the UI you can enter a conditional expression (https://docs.microsoft.com/vsts/pipelines/process/conditions?view=vsts) for the "Run this phase" setting of a phase in the "Tasks" tab (select the phase and scroll to the bottom of the properties panel under "Additional options"). If you are using YAML, see https://docs.microsoft.com/vsts/pipelines/process/multiple-phases?view=vsts&tabs=yaml#conditions.

**Comment by alpacamybags118** [comment]
Thanks @alexhomer1 . I did see the custom conditional expression, but I guess what I was getting at was I don't see any conditions that refer to getting the status of a specific phase in a release. The documentation listed there seems to mostly refer to build steps or branches. I might be missing something, though.
