### ISSUE TITLE
Unable to change account owner

### ISSUE THREAD

**Issue by sylvaingirardbe** [MicrosoftDocs/vsts-docs#1131]
I'm unable to change the account owner of my VSTS account. There is no link that says 'Change'. I'm logged in as the current account owner. The UI also doesn't look like the one pictured in the screenshots. I'm most likely looking at a newer version or something.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c0be4f37-8668-e800-18c4-217d0741f6ee
* Version Independent ID: cae0e5c3-64bb-3a88-a5b2-9474b7ab111a
* Content: [Change the VSTS account owner](https://docs.microsoft.com/en-us/vsts/accounts/change-account-ownership-vs?view=vsts)
* Content Source: [docs/accounts/change-account-ownership-vs.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/accounts/change-account-ownership-vs.md)
* Product: **devops**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
@sylvaingirardbe thanks for letting us know. I have created a work item to track this update. If you are still having difficulties, please send me an email with screen shots and I'd be happy to help. chcomley@Microsoft.com
