### ISSUE TITLE
grammatical errors

### ISSUE THREAD

**Issue by JJones-IAI** [MicrosoftDocs/vsts-docs#1132]
Your document contains some grammar errors and typos that should be corrected.  For example, early in the third sentence, the word "is"  should be "as"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4e18eead-7795-0752-93b0-e07f6d088089
* Version Independent ID: f637de69-b13c-eed8-ab05-3515106c9270
* Content: [What is Git? - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/git/what-is-git#feedback)
* Content Source: [https://mseng.visualstudio.com/DefaultCollection/TechnicalContent/_git/devops-learn-pr?path=%2fdocs%2fgit%2fwhat-is-git.md&version=GBlive&_a=contents](https://mseng.visualstudio.com/DefaultCollection/TechnicalContent/_git/devops-learn-pr?path=%2fdocs%2fgit%2fwhat-is-git.md&version=GBlive&_a=contents)
* Product: **devops**
* Git Login: **samgu**
* Microsoft Alias: **kangan**

**Comment by steved0x** [comment]
@JJones-IAI Sorry this one slipped through the cracks and that it took so long to reply. I'll get this reviewed. Thanks for your feedback.
