### ISSUE TITLE
At what point are notifications of code review comments sent?

### ISSUE THREAD

**Issue by jeyoung** [MicrosoftDocs/vsts-docs#1135]
The documentation is not clear about the trigger for notifications to be sent out to the PR creator when reviewers post comments? Is it at the time a comment is added? Or, when an action is chosen for the PR (Approve, Reject, etc.)?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 028e7b61-62e4-a10e-e420-3535f7843f0e
* Version Independent ID: 1a6fdbe7-5ba4-a7f8-1b2e-271289a7b9fd
* Content: [Review and merge code with pull requests](https://docs.microsoft.com/en-us/vsts/git/pull-requests?view=vsts#feedback)
* Content Source: [docs/git/pull-requests.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/git/pull-requests.md)
* Product: **devops**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
@jeyoung There are different notifications for when someone votes on a PR, and when someone comments on a PR. Depending on which subscriptions to notifications you have, you may not get notifications for all events. See [View your subscriptions, op out as needed](https://docs.microsoft.com/en-us/vsts/notifications/unsubscribe-default-notification?view=vsts) to see how to check your subscriptions and see what notifications you should be receiving. See [Default and supported notifications](https://docs.microsoft.com/en-us/vsts/notifications/oob-built-in-notifications?view=vsts) and [Manage your personal notifications](https://docs.microsoft.com/en-us/vsts/notifications/manage-personal-notifications?view=vsts) for more information.

The notifications should go out as soon as the event, such as voting or commenting, occurs.

Does this info help? Thanks, Steve
