### ISSUE TITLE
No partial match search?

### ISSUE THREAD

**Issue by TJH-AIZ** [MicrosoftDocs/vsts-docs#1139]
I deleted a local branch yesterday, and Git-VS deleted the tracked remote branch along with it.  (Not what I intended.)

I deleted the local branch because my codebase got corrupted and I was unable to return the solution to the LKG state.  So I also deleted the local cloned repository so that I could just re-clone the project.  (At this time I was unaware that VS had also deleted the remote branch.)

Now I have no local commit history to work with for the command line tools to help me find and recover the deleted remote branch.

The process on this page doesn't help me because I can't remember the exact name of the branch.  All I know for certain at this point is the work item # of the related work item (I begin my branch names with the work item #.)  But this process doesn't allow me to search on just that part of the deleted branch name.

It was only about 3 days of work that hadn't been pulled up into another branch, but it's frustrating that now I'm going to spend the whole weekend working to get back to where I was early Friday afternoon.  Not cool.  At all.

This searching for deleted branches process should support partial match searching.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b2f7bb6-eca8-ba34-0595-3bf2ec7c0e0f
* Version Independent ID: 28093f80-26b9-b9f8-0d5d-639c1da1f493
* Content: [Restore a deleted branch in your Git repo](https://docs.microsoft.com/en-us/vsts/git/restore-deleted-branch?view=vsts)
* Content Source: [docs/git/restore-deleted-branch.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/git/restore-deleted-branch.md)
* Product: **devops**
* GitHub Login: @kaylangan
* Microsoft Alias: **kangan**

**Comment by steved0x** [comment]
@TJH-AIZ Sorry that you ran into trouble - I'm going to see if I can find any hot tips that will help you restore your work. I will reply back here as soon as I have some more information.

`This searching for deleted branches process should support partial match searching.` - that sounds like a good feature request that would be helpful in your scenario - you can file a product request [here](https://developercommunity.visualstudio.com/spaces/21/index.html) - or you can search to see if someone else has had the same idea, you can upvote it.

**Comment by steved0x** [comment]
@TJH-AIZ I have a couple of things to try:

* You can try `git reflog` locally to see if you can find your commit and restore the branch locally.
* If you have the work item number, and the work item was linked to the branch (you don't say if it was), then you can look at the history for that work item and get it that way. (I personally name my branches after the work item number too, and I usually create them from the work item which sets up the link)

Can you share any more details about what you were doing when the remote branch was deleted? Usually you have to do an explicit push or a sync from VS to send changes like a deleted branch up to the server. If there is another set of steps that can delete a remote branch, we can get that added to the documentation.
