### ISSUE TITLE
take a look at 'Team Explorer navigational shortcuts'

### ISSUE THREAD

**Issue by mostafa8026** [MicrosoftDocs/vsts-docs#1140]
something went wrong in section 'Team Explorer navigational shortcuts'.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c2fe0af-744d-e535-b300-8d1060945db6
* Version Independent ID: 10892c8d-ff0b-3072-46bd-cad31923c240
* Content: [Web portal& Team Explorer keyboard shortcuts - VSTS & TFS](https://docs.microsoft.com/en-us/vsts/project/navigation/keyboard-shortcuts?view=vsts)
* Content Source: [docs/project/navigation/keyboard-shortcuts.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/project/navigation/keyboard-shortcuts.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@mostafa8026 - Thank you for your feedback. I'm working on fixing the format and it should be fixed later today.
