### ISSUE TITLE
Variable group override precedence

### ISSUE THREAD

**Issue by alizahid** [MicrosoftDocs/vsts-docs#1142]
Hey,

Say I have multiple environments and a variable group for each environment. But a lot of the variables are same for most of them. So I create a common group and now each environment has the groups common and their own.

If I were override a value that's defined in the common group in one of the other groups, will it work? What gets the precedence?

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4827aa99-ae62-bd63-6f2f-a87a4065ed27
* Version Independent ID: c9e461ee-7f42-3503-9460-18fa3a807bbb
* Content: [Variable groups for VSTS and TFS](https://docs.microsoft.com/en-us/vsts/pipelines/library/variable-groups?view=vsts#help-and-support)
* Content Source: [docs/pipelines/library/variable-groups.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/library/variable-groups.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment]
Thank you for your feedback. As noted in previous feedback, the order of precedence for variables where names collide is "Release scoped variable group" < "Release scoped process variable" < "Environment scoped variable group" < "Environment scoped process variable" < "Variable updated by one of the previous tasks in the phase"

**Comment by wgv-srsedate** [comment]
Variable override precedence information for builds and releases should be added to the documentation, it helps for strategizing our release train ecosystem.

**Comment by theyetiman** [comment]
So what happens when we have 2 "Release scoped variable groups" with a variable with the same name? Which takes precedence? You haven't answered the question.

**Comment by picolino** [comment]
Upvote for answer
