### ISSUE TITLE
Mstest-v2 - dont make it worse as it is :)

### ISSUE THREAD

**Issue by bl4cky** [MicrosoftDocs/vsts-docs#1143]
I think the following is outdated and should therefore be removed from the page (at least wiht mstest v2 it is possible)

"NOTE: At present you cannot use this procedure to associate MSTest V2 tests or tests written in NUnit and XUnit. Adding this capability is planned for a future release."

Cheers :)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7d8a7e40-73d6-795f-7b8c-77104ef606e8
* Version Independent ID: 8f15995b-bd94-8d9f-1e8b-82f1f364d221
* Content: [Associate an automated test with a test case](https://docs.microsoft.com/en-us/vsts/test/associate-automated-test-with-test-case?view=vsts)
* Content Source: [docs/test/associate-automated-test-with-test-case.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/test/associate-automated-test-with-test-case.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment]
Thank you for your feedback. I will pass this on to the product team for confirmation and update the topic based on their response.
