### ISSUE TITLE
Can we do this for build completed event?

### ISSUE THREAD

**Issue by asadabbas88** [MicrosoftDocs/vsts-docs#1144]
Its a question rather than an issue .. Can we get service hook to post status on build complete event just like it's done for pull request completed? So that after pull request is created .. it should also complete build and once build is completed then its should apply status policy using service hook..

Let me know if there is a better place to ask this

Thanks

**Comment by steved0x** [comment]
@asadabbas88 Thank you for feedback. The issues in this GitHub repo are for documentation feedback - your comments sound like a product request, and you can file that [here](https://developercommunity.visualstudio.com/spaces/21/index.html). You can also search to see if someone else has the same suggestion and you can upvote it, if they have. Thank you for your feedback.
