### ISSUE TITLE
Possibility to create new fields from extension.

### ISSUE THREAD

**Issue by yury-stepanov** [MicrosoftDocs/vsts-docs#1146]
Hello, it would be nice to have possibility to extend work items with custom fields from extension. 
Any plans on bringing this functionality? 
Cheers.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3a26044c-d3bf-05fc-6901-17bd1d6b0b68
* Version Independent ID: 546b2780-9b7d-0b46-1696-6edb8608dc18
* Content: [TFS/Work/RestClient WorkHttpClient2_2 API](https://docs.microsoft.com/en-us/vsts/extend/reference/client/api/tfs/work/restclient/workhttpclient2_2?view=vsts)
* Content Source: [docs/extend/reference/client/api/TFS/Work/RestClient/WorkHttpClient2_2.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/extend/reference/client/api/TFS/Work/RestClient/WorkHttpClient2_2.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by elbatk** [comment]
Hi @yury-stepanov , you can extend the work item form now. Check out this doc: https://docs.microsoft.com/en-us/vsts/extend/develop/add-workitem-extension?view=vsts

Also some of our [samples](https://docs.microsoft.com/en-us/vsts/extend/develop/samples-overview?view=vsts) mess around with the work item form as well. Are these not quite what you're looking for? Let me know!

**Comment by yury-stepanov** [comment]
Thanks! Looks like I was looking for, but would this new field be available for querying? 
Cheers

**Comment by yury-stepanov** [comment]
@elbatk I'am sorry, I was looking more for a way to extend work item type with custom fields to hold data. For example custom text fields. Should be more specific. Thanks in advance.
Cheers.

**Comment by elbatk** [comment]
Hi @yury-stepanov sorry for the huge delay here. I want to forward you to the [Azure DevOps Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html) for product-related questions, as it's monitored by the product team and you'll get better info there on questions like this! Best of luck!
