### ISSUE TITLE
Items supported with TFS 2015

### ISSUE THREAD

**Issue by JayCeeK** [MicrosoftDocs/vsts-docs#1147]
Also the whole way of configuring branch policies is different in TFS 2015. Only some things described here are valid for TFS 2015, I'd suggest a separation of the documentation here or an exact description of applicable versions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7cd986e0-608c-1d8c-6faf-ecdb12e10bc6
* Version Independent ID: d60c996e-187e-dd6b-7f3a-dd056a1603f4
* Content: [Protect your Git branches with policies](https://docs.microsoft.com/en-us/vsts/git/branch-policies?view=vsts#feedback)
* Content Source: [docs/git/branch-policies.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/git/branch-policies.md)
* Product: **devops**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
@JayCeeK I'll get that document updated and reply back here shortly with some more information.

**Comment by justhchung** [comment]
Thank you for your feedback. 
We are closing this issue as there is no action to take on our part to address the issue.  The guidance provided is correct, requested additional information was not provided, or the content referenced is no longer relevant.
