### ISSUE TITLE
please support headless install

### ISSUE THREAD

**Issue by cjmather** [MicrosoftDocs/vsts-docs#1148]
These instructions are for deploying a self-hosted Linux agent.  Microsoft probably would like these agents to run on Azure VM's.  Azure Linux VM's do not support the Linux GUI and must be accessed headless.  But your instructions assume the user is running a browser from the agent VM.  Please support headless install of the agent and add appropriate instructions.  I.e., wget and yum/apt install like everybody else.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 23328b13-f079-ad21-5d7a-6c640f25391c
* Version Independent ID: 4a39889d-fa00-ae2b-aa43-f358631b7b1a
* Content: [Deploy a build and release agent on Linux](https://docs.microsoft.com/en-us/vsts/pipelines/agents/v2-linux?view=vsts#download-and-configure-the-agent)
* Content Source: [docs/pipelines/agents/v2-linux.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/agents/v2-linux.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by chrisrpatterson** [comment]
Here a script that can use headless install https://github.com/Microsoft/vsts-agent-docker/blob/master/ubuntu/start.sh. We can look to add something more specific to the docs.

**Comment by andyjlewis** [comment]
Thanks for this suggestion. I've added it to the backlog.
