### ISSUE TITLE
Provide a YAML example for use of the App Center Test task

### ISSUE THREAD

**Issue by lifesoccult** [MicrosoftDocs/vsts-docs#1149]
It would be great to provide working examples of this YAML inline with its definition.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad0bff55-744d-06c4-d6da-595e6d5d6e94
* Version Independent ID: 4fc5c777-ec33-38fd-0c56-6c6038e9ac40
* Content: [App Center Test](https://docs.microsoft.com/en-us/vsts/pipelines/tasks/test/app-center-test?view=vsts)
* Content Source: [docs/pipelines/tasks/test/app-center-test.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/test/app-center-test.md)
* Product: **devops**
* GitHub Login: @erickson-doug
* Microsoft Alias: **dastahel**

**Comment by Pegolon** [comment]
An example YAML file would still be a good idea.

**Comment by DavidStaheli** [comment]
Keep-alive

**Comment by joshlcoffin** [comment]
Please keep alive!

**Comment by mostafamobiquity** [comment]
Did anyone figured out an example ?!

**Comment by shipitfaster** [comment]
It looks like parameter names are different from descriptions. E.g., 
CredsType vs CredentialOptions

**Comment by MouthOfMadness** [comment]
If the GitHub url is our example, only a select few will ever use this task correctly.

**Comment by victorlopesjg** [comment]
Hi,

My pipeline is like this

`pool:
  agents:
    queue: "Android"
steps:

  - task: CmdLine@2
    inputs:
      script: 'sudo npm install -g appcenter-cli'

  - task: CmdLine@2
    inputs:
      script: 'appcenter login --token {YOUR_TOKEN}'

  - task: Gradle@2
    inputs:
      workingDirectory: ''
      gradleWrapperFile: 'gradlew'
      gradleOptions: '-Xmx3072m'
      publishJUnitResults: false
      testResultsFiles: '**/TEST-*.xml'
      tasks: 'YOUR_TASKS'

  - task: CopyFiles@2
    inputs:
      contents: '**/*.apk'
      targetFolder: '$(build.artifactStagingDirectory)'

  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: '$(build.artifactStagingDirectory)'
      artifactName: 'outputs'
      artifactType: 'container'

  - task: CmdLine@2
    inputs:
      script: 'appcenter test run espresso --app "{PAHT_APP_CENTER}" --devices "{DEVICE}" --app-path {PAHT_APP-BUILD}   --test-series "master" --locale "en_US" --build-dir {PAHT_ESPRESSO} --debug'

  - task: AppCenterDistribute@3
    inputs:
      serverEndpoint: 'AppCenter'
      appSlug: '{PAHT_APP_CENTER}'
      appFile: '{PAHT_APP-BUILD}'
      symbolsOption: 'Android'
      releaseNotesOption: 'input'
      releaseNotesInput: 'Versão nova'
      destinationType: 'groups'`

**Comment by victorlopesjg** [comment]
`
pool:
  agents:
    queue: "Android"
steps:

  - task: CmdLine@2
    inputs:
      script: 'sudo npm install -g appcenter-cli'

  - task: CmdLine@2
    inputs:
      script: 'appcenter login --token {YOUR_TOKEN}'

  - task: Gradle@2
    inputs:
      workingDirectory: ''
      gradleWrapperFile: 'gradlew'
      gradleOptions: '-Xmx3072m'
      publishJUnitResults: false
      testResultsFiles: '**/TEST-*.xml'
      tasks: 'YOUR_TASKS'

  - task: CopyFiles@2
    inputs:
      contents: '**/*.apk'
      targetFolder: '$(build.artifactStagingDirectory)'

  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: '$(build.artifactStagingDirectory)'
      artifactName: 'outputs'
      artifactType: 'container'

  - task: CmdLine@2
    inputs:
      script: 'appcenter test run espresso --app "{PAHT_APP_CENTER}" --devices "{DEVICE}" --app-path {PAHT_APP-BUILD}   --test-series "master" --locale "en_US" --build-dir {PAHT_ESPRESSO} --debug'

  - task: AppCenterDistribute@3
    inputs:
      serverEndpoint: 'AppCenter'
      appSlug: '{PAHT_APP_CENTER}'
      appFile: '{PAHT_APP-BUILD}'
      symbolsOption: 'Android'
      releaseNotesOption: 'input'
      releaseNotesInput: 'Versão nova'
      destinationType: 'groups' `

**Comment by davidstaheli** [comment]
An example has been added to the docs (based on the above sample from @victorlopesjg - thanks!).  The docs should be live within a few days.

**Comment by MouthOfMadness** [comment]
Sorry, but this **is not an example** of the App Center Test task, this is an example of the **deployment** task.

The task should be looking like this; my guess is I'm missing some App Center configuration that's isn't listed as a prerequisite of the task.

- task: AppCenterTest@1
  continueOnError: false  
  inputs:
    appFile: '$(outputDirectory)/*.apk'
    artifactsDirectory: '$(Build.ArtifactStagingDirectory)/AppCenterTest'
    frameworkOption: 'uitest'
    uiTestBuildDirectory: '$(outputDirectory)'
    uitestStorePath: '$(storePath)'
    uiTestStorePassword: '$(keystorePassword)'
    uitestKeyAlias: '$(keyAlias)'
    uiTestKeyPassword: '$(keyPassword)'
    credentialsOption: 'AppCenterUser'
    localeOption: 'en_US'

**Comment by davidstaheli** [comment]
Ug, sorry I mixed those up.  I'll try getting some help from the App Center team too.

**Comment by davidstaheli** [comment]
While I work toward a revamp of these docs, here's an example that works, but it's different than what @MouthOfMadness is facing because it uses Espresso-based tests instead of UI Tests (requiring different inputs).

```yaml
steps:
- task: AppCenterTest@1
  displayName: 'Espresso Test - Synchronous'
  inputs:
    appFile: 'Espresso/espresso-app.apk'
    artifactsDirectory: '$(Build.ArtifactStagingDirectory)/AppCenterTest'
    frameworkOption: espresso
    espressoBuildDirectory: Espresso
    serverEndpoint: 'myAppCenterServiceConnection'
    appSlug: 'xplatbg1/EspressoTests'
    devices: a84c93af
```

**Comment by davidstaheli** [comment]
Improved docs with an example are here:
https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/test/app-center-test?view=azure-devops
Thanks for everyone's patience!
