### ISSUE TITLE
While MVC unit tests work fine, SSDT unit tests do not.

### ISSUE THREAD

**Issue by RubixRevenge** [MicrosoftDocs/vsts-docs#1150]
While unit tests created for SQL Server Database projects work just fine on VS 2017, I have been unable to get them to work on TFS 2018. I've gone through so many tweaks and trial-and-error-and-still-fail that I don't know what I should be doing or what to do next. The official Microsoft documentation is marked as outdated. I'm using VS 2017 and TFS 2018. Are there current and relevant documents I could read that can tell me how to get my SQL Unit Tests to work on TFS 2018. And before you say "why don't you just use tSQLt?" It's a long story, it is a conscious choice on my part.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f69faf41-3074-0ce2-fb3f-3d9cc570e010
* Version Independent ID: 9ce392b3-b1cc-55f7-93e5-e8d2cc9bd788
* Content: [Run unit tests with your builds in VSTS and TFS - test automation tools](https://docs.microsoft.com/en-us/vsts/pipelines/test/getting-started-with-continuous-testing?view=vsts)
* Content Source: [docs/pipelines/test/getting-started-with-continuous-testing.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/test/getting-started-with-continuous-testing.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by RubixRevenge** [comment]
To replicate the symptoms, feel free to create your own hello world scenario.

I'm erring on the side of being too detailed, but here's the best I can do (at present) to help you replicate this, as business policy prevents me from making my project public.

1. Using TFS 2018, create a new project (git version control). Assumption: TFS is _not_ the express version and is set up on a server.
2. Initialize with readme and VisualStudio gitignore
3. Initialize and then clone in Visual Studio
4. From Visual Studio, create a new .NET Framework MVC application (Windows Authentication, add unit tests). I'm using .NET Framework 4.6.1.
5. Your test projects should have the Home, About, and Contact Controller tests. Run them and they should pass.

Interlude -- you should have SQL Server installed on your desktop PC and on a server. Create a simple SQL Server database with a simple scalar function, e.g., `dbo.GetTestValue()` that returns `Test Value`. The purpose is to create something that's easy to make and easy to test. As a sanity test, check it in SSMS. 

6. In Visual Studio create a new SQL Server Database project. Import the database you created in your desktop SQL Server.

7. Expand the project to find the `GetTestValue` function and right-click. Select "Create Unit Tests..."

8. This I learned from hard experience. Instead of using the existing test project, you'll need to allow "Create Unit Tests" to create a new test project. _From what I can infer, the infrastructure necessary to test database functions do not play well with the test project that Visual Studio creates when you create the MVC project._

9. Create a new class, with the same name as the function you want to test.

10. Use the Designer to create a unit test. If you created a simple static function, then one unit test should suffice.

11. Rebuild your project and run your unit tests. They should all pass. At worst, you might get prompted to update one or more Nuget packages. After updating the Nuget packages, you should get all passing tests.

12. Commit the the changes you made to TFS.

13. In TFS, create an "ASP.NET (Preview) Build Definition.

14. The defaults should all be good. The only additional step I added in my scenario is a "Copy Files" step to copy the DACPAC to `$(build.artifactstagingdirectory)`.

15. It's the moment of truth.  Run your build... and watch it fail at the "Visual Studio Test" step. Why? Lots and lots of errors that to date I have not been able to resolve.

**Comment by alexhomer1** [comment]
Thank you for your feedback. I have passed this on to the product team for advice.

**Comment by RubixRevenge** [comment]
Thank you @alexhomer1  and @harishkragarwal. I am eager to hear what, if anything, can be done to resolve this issue.

**Comment by RubixRevenge** [comment]
Just curious whether this issue is actively being investigated or is deprioritized.

Please let me know so that I can act accordingly.  Thank you

**Comment by Matteo-T** [comment]
@RubixRevenge: could you kindly log this as a VS Feedback? This was other folks can see it and it is also going to be more visible for us (since it is not a documentation issue, rather a product issue)? Thanks.

**Comment by RubixRevenge** [comment]
Ok. Will do. Closing this thread.
