### ISSUE TITLE
Labelling sources triggers infinite build loop

### ISSUE THREAD

**Issue by thomasdc** [MicrosoftDocs/vsts-docs#1152]
When VSTS tags sources and pushes that tag, it triggers another build that again pushes another tag etc.
This is intended behavior but worth documenting. You can circumvent this by excluding a trigger on refs/tags/*.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 41d4fcf8-3fd9-27b5-89e5-a026cc4a2b6a
* Version Independent ID: 76481ffb-aec5-50cd-6cdd-9e53c59e2933
* Content: [Build definition source repositories](https://docs.microsoft.com/en-us/vsts/pipelines/build/repository?view=vsts)
* Content Source: [docs/pipelines/build/repository.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/build/repository.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by andyjlewis** [comment]
Thank you for this suggestion. I apologize for the very late response. We've made a lot of improvements in the repos and triggers content, but I'm not sure this tip is in there yet, so I'm adding this issue to our backlog.
