### ISSUE TITLE
Needs updating with details on the new UI

### ISSUE THREAD

**Issue by steveculshaw** [MicrosoftDocs/vsts-docs#1153]
Needs updating with details on the new UI

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c2ed06ca-1352-19fe-23bb-8c29685fd95a
* Version Independent ID: 3e6fd6f3-f602-a011-7c68-047b4aa8cc89
* Content: [Delete a team project from VSTS and TFS](https://docs.microsoft.com/en-gb/vsts/organizations/accounts/delete-team-project?view=vsts)
* Content Source: [docs/organizations/accounts/delete-team-project.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/accounts/delete-team-project.md)
* Product: **devops**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
@steveculshaw Thanks so much for your input - I've created a work item on my backlog for this update.
