### ISSUE TITLE
How not to fail on Standard Error? 

### ISSUE THREAD

**Issue by artkpv** [MicrosoftDocs/vsts-docs#1155]
Thank you for the ability to give feedback and the tools! How can I specify for Azure PowerShell task not to fail a step if someone writes to Error stream? There is no "Advanced" group in UI for my release definition as in a PowerShell task to uncheck the option. We want to run Selenium tests which write to this stream on some failed test and we wish to continue running other tests. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fb215324-b1a0-93b5-5022-4bcc7da93bb7
* Version Independent ID: 9eb2977b-ac34-9d53-670e-04fa027bc8e4
* Content: [Azure PowerShell](https://docs.microsoft.com/en-us/vsts/pipelines/tasks/deploy/azure-powershell?view=vsts)
* Content Source: [docs/pipelines/tasks/deploy/azure-powershell.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/deploy/azure-powershell.md)
* Product: **devops**
* GitHub Login: @erickson-doug
* Microsoft Alias: **dastahel**

**Comment by artkpv** [comment]
Probably setting a variable from the script would help:

    	Write-Host "##vso[task.setvariable variable=failOnStandardError;]false"

See https://github.com/Microsoft/vsts-tasks/blob/master/docs/authoring/commands.md .

**Comment by DavidStaheli** [comment]
+ @vtbassmatt and @ericsciple

**Comment by ericsciple** [comment]
it should be a task setting. open an issue for the specific task in the vsts-tasks repo

**Comment by DavidStaheli** [comment]
@artkpv could you please open an issue for the PowerShell task in that repo, found here?
https://github.com/Microsoft/vsts-tasks

**Comment by ericsciple** [comment]
note, the powershell task already has this input: https://github.com/Microsoft/vsts-tasks/blob/master/Tasks/PowerShellV2/task.json#L95

the issue here is about the azure powershell task

**Comment by ericsciple** [comment]
and as a workaround you can redirect stderr

**Comment by artkpv** [comment]
Thanks for the feedback. Actually it was fixed in 3.* version. Please see the picture. 
![screenclip](https://user-images.githubusercontent.com/3657998/42566572-b18677e0-850f-11e8-847f-88a56c30f84a.png)
