### ISSUE TITLE
Additional resources is missing

### ISSUE THREAD

**Issue by psined1** [MicrosoftDocs/vsts-docs#1157]
It says above "For more information about both of these books, see Additional resources later in this topic."

There is no Additional resources chapter on this page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8b18f4fa-1687-69e9-20ad-82c4b60e9b6c
* Version Independent ID: e662b71c-a02a-cafe-d7a8-d2b7034aa2b9
* Content: [Background to Capability Maturity Model Integration (CMMI) - VSTS & TFS](https://docs.microsoft.com/en-us/vsts/work/work-items/guidance/cmmi/guidance-background-to-cmmi?view=vsts#resources)
* Content Source: [docs/work/work-items/guidance/cmmi/guidance-background-to-cmmi.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/work/work-items/guidance/cmmi/guidance-background-to-cmmi.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@psined1  - Thank you for the feedback. You are correct that there are no longer any additional resources. Over time, they have been removed from the internet. I've updated the topic to reflect these changes.
