### ISSUE TITLE
Error on IIS Web App Deploy

### ISSUE THREAD

**Issue by aminkh17** [MicrosoftDocs/vsts-docs#1163]
After I have tried a few times, repeatedly I got the following error.
Error: No package found with specified pattern

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca1c5394-611b-b119-dbf3-b88404e351d5
* Version Independent ID: fcc23259-21ec-f9fa-4e25-f587e1e0f41b
* Content: [Deploy to an IIS web server on a Windows Virtual Machine](https://docs.microsoft.com/en-us/vsts/pipelines/apps/cd/deploy-webdeploy-iis-deploygroups?view=vsts)
* Content Source: [docs/pipelines/apps/cd/deploy-webdeploy-iis-deploygroups.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/apps/cd/deploy-webdeploy-iis-deploygroups.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment]
Thank you for your feedback. I have passed this on to the product team for advice.

**Comment by RoopeshNair** [comment]
@aminkh17 - can you check if the artifact linked with the release has *zip file in it? also can you share the complete logs rm_customer_queries dot com

**Comment by aminkh17** [comment]
Thank you, I've checked and found drop.zip there, however, nothing downloaded when I clicked Build.SourceLabel
[logs_9.zip](https://github.com/MicrosoftDocs/vsts-docs/files/2143486/logs_9.zip)
[ReleaseLogs_4.zip](https://github.com/MicrosoftDocs/vsts-docs/files/2143487/ReleaseLogs_4.zip)

**Comment by mlearned** [comment]
i had a look at this one, i think we need to tweak our CI piece on pre-reqs to ensure we create the package.  did you guys get through the issue?

**Comment by RoopeshNair** [comment]
From the RMCQ thread, it appears that the issue is resolved and the user is no longer blocked. @SumiranAgg for the comments on the resolution.

**Comment by johnkors** [comment]
Hi, I have the same issue.

My build produces an artifact with the artifactName I've setup in the yml file, but the IIS Web App Deploy step cannot find it.


```
2018-10-05T14:02:15.3970305Z ##[section]Starting: IIS Web App Deploy
2018-10-05T14:02:15.3977417Z ==============================================================================
2018-10-05T14:02:15.3977522Z Task         : IIS Web App Deploy
2018-10-05T14:02:15.3977587Z Description  : Deploy a website or web application using Web Deploy
2018-10-05T14:02:15.3977718Z Version      : 0.0.44
2018-10-05T14:02:15.3977789Z Author       : Microsoft Corporation
2018-10-05T14:02:15.3977850Z Help         : [More information](https://go.microsoft.com/fwlink/?linkid=866789)
2018-10-05T14:02:15.3977912Z ==============================================================================
2018-10-05T14:02:17.1584337Z ##[error]Error: No package found with specified pattern
2018-10-05T14:02:17.1895535Z ##[section]Finishing: IIS Web App Deploy
```

**Comment by johnkors** [comment]
I cannot find anywhere to tweak what the expected package name would be for this step. This error message badly needs an explanation. 

What package? What pattern? Where can I set it? If there is a package, but not matching a pattern - what packages did you find that dit not match this pattern?

**Comment by staneee** [comment]
我不知道是不是我哪里搞错了，也是同样的错误信息

** Error: No package found with specified pattern **

![image](https://user-images.githubusercontent.com/26987099/47713025-3945e880-dc74-11e8-902d-fc1281c6eb40.png)


![image](https://user-images.githubusercontent.com/26987099/47712878-dbb19c00-dc73-11e8-8b40-633b8cd31733.png)

![image](https://user-images.githubusercontent.com/26987099/47712941-013ea580-dc74-11e8-849f-029c8567cc72.png)

**Comment by MrEmanuel** [comment]
I get this error too. It doesn't say anything about what is wrong. What package? If it's the release artifact, zip or whatever the error should say so and also what is missing from the artifact. 

Thanks.

**Comment by staneee** [comment]
> I get this error too. It doesn't say anything about what is wrong. What package? If it's the release artifact, zip or whatever the error should say so and also what is missing from the artifact.
> 
> Thanks.

* 使用内置的环境变量 （ Use built-in environment variables）
    * **$(AGENT.RELEASEDIRECTORY)** and **$(RELEASE.PRIMARYARTIFACTSOURCEALIAS)**

```
$(AGENT.RELEASEDIRECTORY)\\$(RELEASE.PRIMARYARTIFACTSOURCEALIAS)\\drop\\*.zip
```

* 这是配置成功的结果，前提是你的服务器上已经配置好了 AGENT 
（This is the result of successful configuration, as long as the AGENT is already configured on your server）

![image](https://user-images.githubusercontent.com/26987099/55882804-b6886880-5bd7-11e9-8767-4b0f8d660fba.png)

**Comment by staneee** [comment]
> > I get this error too. It doesn't say anything about what is wrong. What package? If it's the release artifact, zip or whatever the error should say so and also what is missing from the artifact.
> > Thanks.
> 
> * 使用内置的环境变量 （ Use built-in environment variables）
>   
>   * **$(AGENT.RELEASEDIRECTORY)** and **$(RELEASE.PRIMARYARTIFACTSOURCEALIAS)**
> 
> ```
> $(AGENT.RELEASEDIRECTORY)\\$(RELEASE.PRIMARYARTIFACTSOURCEALIAS)\\drop\\*.zip
> ```
> * 这是配置成功的结果，前提是你的服务器上已经配置好了 AGENT
>   （This is the result of successful configuration, as long as the AGENT is already configured on your server）
> 
> ![image](https://user-images.githubusercontent.com/26987099/55882804-b6886880-5bd7-11e9-8767-4b0f8d660fba.png)

祝你顺利，如果不行的话可以继续联系我。不过你不会立刻得到我的回复，因为中国比瑞典快6小时，你明白的，存在时差。

Wish you all the best. If not, please contact me.But you won't get an immediate response from me because China is 6 hours faster than Sweden and you know there is a time difference.

**Comment by GearsViraj** [comment]
I get this error too, stuck one this step. There is no zip file . How i fixed this
<img width="950" alt="ErrorAzureDevOps" src="https://user-images.githubusercontent.com/48319914/59275584-38e5e500-8c7a-11e9-8055-e5b6f782d476.PNG">

**Comment by gojanpaolo** [comment]
I'm also getting this error. Any help please?

**Comment by RoopeshNair** [comment]
package is the release artifact / folder to deploy. You can specify it in the task input field ** Package or folder **. In the screenshot below it the last field with the default input value as `$(System.DefaultWorkingDirectory)\**\*.zip`. Ensure that there is a single '*.zip' in the path. If multiple zip files are found it will fail. 

![image](https://user-images.githubusercontent.com/1370480/61430661-4d3b9280-a948-11e9-97c5-e6b7705eeed2.png)

**Comment by gojanpaolo** [comment]
> Ensure that there is a single '*.zip' in the path.  If multiple zip files are found it will fail.

In my case, there was no files at all. As a beginner in using Azure Pipelines, it took me a while to figure out the issue which is editing the `azure-pipelines.yml`.

The generated `azure-pipelines.yml` contains the following steps
```yml
steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
```

That needs to be changed to publish like so:
```yml
steps:

- task: DotNetCoreCLI@2
  inputs:
    command: publish
    publishWebProjects: True
    arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: True

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)' 
    artifactName: 'myWebsiteName'
```

Now everything is working as expected. But then again, this is not included in any of the azure pipelines official tutorials / getting started guides.
