### ISSUE TITLE
Should `enableqna` value be quoted

### ISSUE THREAD

**Issue by nschonni** [MicrosoftDocs/vsts-docs#1166]
It is described as a boolean, but the value is always shown as a quoted boolean value. Should it just be a plain boolean value like:
```json
{
     "CustomerQnASupport": {
        "enableqna": true,
        "url": "http://uservoice.visualstudio.com"
    } 
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d8b703fe-8982-4284-6db0-ef33abac08a4
* Version Independent ID: 0fc84d11-1c32-0a49-04ec-641b68f44886
* Content: [Extension Manifest Reference](https://docs.microsoft.com/en-us/vsts/extend/develop/manifest?view=vsts#installation-targets)
* Content Source: [docs/extend/develop/manifest.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/extend/develop/manifest.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by willsmythe** [comment]
The value should be a regular JSON boolean value (i.e. not quoted). Also, `CustomerQnaSupport` can/should be camel-case to match the convention in the rest of the manifest file. So:

```json
{
     "customerQnaSupport": {
        "enableqna": true,
        "url": "http://uservoice.visualstudio.com"
    } 
}
```
