### ISSUE TITLE
Documentation needs more detail.

### ISSUE THREAD

**Issue by BruceHaley** [MicrosoftDocs/vsts-docs#1167]
Please explain that backslashes ("\\") in search patterns are not supported, and that slashes match backslashes. This needs to be spelled out because standard Windows paths use backslashes.

Please include complex examples using "**" such as: 
\*\*/bin/release/\*\*/\*connector\*.dll
(Possibly the above is not a valid search pattern. Please explain what the syntactical limits are.)

Please explain that line separators may be used, or comma separators may be used, or both.

Thank you.
--Bruce
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8fd54e81-9a0c-c5e5-fb89-9534372805ff
* Version Independent ID: f3d49618-32d7-0abc-1c33-8211eb7dd073
* Content: [File matching patterns reference for VSTS and TFS](https://docs.microsoft.com/en-us/vsts/pipelines/tasks/file-matching-patterns?view=vsts#character_set_examples)
* Content Source: [docs/pipelines/tasks/file-matching-patterns.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/file-matching-patterns.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by nikolay-advolodkin** [comment]
Yea, we need much improved documentation on finding test files please. I spent hours trying to locate test directories to no avail. I have no clue how to locate my test directory to run tests.

It can never find the correct test directory which lives here locally "C:\Source\Github\dot-net-sauce\SauceExamples\SeleniumMsTestDotNetFramework\bin\Debug\SeleniumMsTestDotNetFramework.dll":

Here's all I tried:
**\$(BuildConfiguration)\SeleniumMsTestDotNetFramework.dll
**\bin\$(BuildConfiguration)\SeleniumMsTestDotNetFramework.dll
**\dot-net-sauce\SauceExamples\SeleniumMsTestDotNetFramework\bin\Debug\SeleniumMsTestDotNetFramework.dll
**\SauceExamples\SeleniumMsTestDotNetFramework\bin\Debug\SeleniumMsTestDotNetFramework.dll
!**\obj\**
D:\a\1\s\dot-net-sauce\SauceExamples\SeleniumMsTestDotNetFramework\bin\Debug\SeleniumMsTestDotNetFramework.dll

**Comment by vtbassmatt** [comment]
Fixed, should deploy tomorrow.

**Comment by FrankHeimes** [comment]
Here is a complex example (including interleaved exclude), that does work:
**/@(bin|Release)/**/!(*32*|*64*).pdb
**/@(bin|Release)/**/@(*win32|*x64).pdb

Note, that all groups, like @() or !(), must match an individual folder name.
So '*@(32|64)' won't match 'FooBar32'.

It is VERY tedious to get the pattern right; much worse than regex.
To try it, get https://www.powershellgallery.com/packages/VstsTaskSdk/0.11.0/Content/FindFunctions.ps1,
replace 'Get-DirectoryChildItem' with 'Get-ChildItem *' and remove the 'Trace-*' commands.
At the bottom, add the call:
Find-Match 'YourPath' @('YourPattern1', 'YourPattern2', ...)
and run it in PowerShell ISE.
