### ISSUE TITLE
Dead Link /tfs/server/architecture/extend-vs-for-alm

### ISSUE THREAD

**Issue by nschonni** [MicrosoftDocs/vsts-docs#1170]
Under https://docs.microsoft.com/en-ca/vsts/work/customize/add-modify-field?view=vsts#add-a-custom-control in "Using the object model for tracking work items" but I'm not sure where is should point

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: df8f0fc3-60e9-114d-b2e2-c26cee932a08
* Version Independent ID: 9de0bcaa-8043-fc45-9dd8-c8b51afe79b9
* Content: [Add or modify a work tracking field - VSTS & TFS](https://docs.microsoft.com/en-ca/vsts/work/customize/add-modify-field?view=vsts#add-a-custom-control)
* Content Source: [docs/work/customize/add-modify-field.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/work/customize/add-modify-field.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@v - Thank you for the feedback.  The current link is no longer valid. And the valid links are different depending on the TFS version that is being run. I'm updating the article and the changes should be live today.
