### ISSUE TITLE
Why Tiny Charts?

### ISSUE THREAD

**Issue by bigale** [MicrosoftDocs/vsts-docs#1172]
I'm using the Add a test status or result chart right now.  Charts are a tool for visual understanding and limiting them to the size of a postage stamp is a terrible idea that severely restricts the use case of an otherwise greatly engineered feature.  I don't see any settings to expand them to be useful.  It seems this limitation has been around for some time?  Do we have to vote on everything???  When does common sense creep in to the equation?  What am I missing here?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 379200c5-cd1b-9c69-3cce-ec7dcafbd2f2
* Version Independent ID: 4de1aff6-26f4-6cd7-1178-ce2b106fc52f
* Content: [Add built-in charts to a team dashboard - VSTS & TFS](https://docs.microsoft.com/en-us/vsts/report/dashboards/add-charts-to-dashboard?view=tfs-2018)
* Content Source: [docs/report/dashboards/add-charts-to-dashboard.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/report/dashboards/add-charts-to-dashboard.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@bigale - Thank you for your inquiry. I recommend you add your comment to our [User Voice page](https://visualstudio.uservoice.com/forums/330519-team-services) where the product team can take appropriate action.
