### ISSUE TITLE
Url schema out of date?

### ISSUE THREAD

**Issue by skovsboll** [MicrosoftDocs/vsts-docs#1178]
This page states that for VSTS, urls for workitems follow this pattern: _workitems?id=133&_a=edit
On the subdomains on visualstudio.com that I have access to, the url pattern is: _workitems/edit/133 and the former is not recognized.
This must have changed some time between two versions of VSTS?
Do all subdomains on visualstudio.com run the same version of VSTS and do they have the same url scheme?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2a2fa2c-bdbd-3357-1f4f-ff6504367404
* Version Independent ID: aba4b3e9-7572-e1f1-e618-291fbd5b704f
* Content: [Define the hyperlink for a work item - VSTS & TFS](https://docs.microsoft.com/en-us/vsts/work/work-items/work-item-url-hyperlink?view=vsts)
* Content Source: [docs/work/work-items/work-item-url-hyperlink.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/work/work-items/work-item-url-hyperlink.md)
* Product: **devops**
* GitHub Login: @erickson-doug
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@skovsboll - Thank you for the feedback.  All subdomains on visualstudio.com should run the same version of VSTS and have the same url scheme. I'm updating the article to reflect the URL change for VSTS.
