### ISSUE TITLE
Example URL has project twice

### ISSUE THREAD

**Issue by jallman112** [MicrosoftDocs/vsts-docs#1186]
The example/template URL directly below the heading "Get a list of pull requests in the project" has "project" in it twice.

.../DefaultCollection/{project}/{project}/_apis/...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9d5409d2-2ea5-c5c5-e193-58551d3bf11d
* Version Independent ID: 74dc0d16-70c1-7ab1-56e6-6207e99f6aa4
* Content: [Git Pull Requests](https://docs.microsoft.com/en-us/vsts/integrate/previous-apis/git/pull-requests/pull-requests?view=vsts#get-a-list-of-pull-requests-in-the-project)
* Content Source: [docs/integrate/previous-apis/git/pull-requests/pull-requests.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/integrate/previous-apis/git/pull-requests/pull-requests.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by elbatk** [comment]
ah @jallman112 , that's not gonna get devs very far, I'll get this fixed!

**Comment by elbatk** [comment]
This is fixed and should go live by end of day, thanks again!
