### ISSUE TITLE
Send email if I mention someone on shelveset

### ISSUE THREAD

**Issue by shayki5** [MicrosoftDocs/vsts-docs#1190]
Hi,
We have an option on shelveset to write comments on the code, and we can mention user (with @). 
But if I mentioned someone he didn't get an email.
This is supposed to be? can you change it?
Thank you.

**Comment by steved0x** [comment]
@shayki5 The `@mention` control should work with TFVC changeset comments and shelveset comments, per [Use @mentions to further discussion](https://docs.microsoft.com/en-us/vsts/notifications/at-mentions?view=vsts) - it sounds like you are mentioning a user in a shelveset comment and they are not getting an email? When you leave the @mention does it pop up and let you select their name from the list?

**Comment by steved0x** [comment]
@shayki5 You are the 2nd person to mention this, it sounds like it might be a bug. I checked into it and it looks like it could be a bug. The issues in this repo are for content feedback, and this looks like a bug. For product feedback, including bugs, please file an issue here: https://developercommunity.visualstudio.com/spaces/21/index.html

This will engage the product team directly.

Thank you
