### ISSUE TITLE
Path filter doesn't appear to exist

### ISSUE THREAD

**Issue by sabbour** [MicrosoftDocs/vsts-docs#1192]
You can't filter out the build trigger by a path filter. It exists in screenshots but not in my VSTS build definition trigger page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 521b594c-dbb9-54d5-f56f-00e2f5fa1d92
* Version Independent ID: 509d3e4e-23db-8493-e1a6-acb67ec47e81
* Content: [Building multiple branches](https://docs.microsoft.com/en-us/vsts/pipelines/build/ci-build-git?view=vsts&tabs=designer)
* Content Source: [docs/pipelines/build/ci-build-git.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/build/ci-build-git.md)
* Product: **devops**
* GitHub Login: @mlearned
* Microsoft Alias: **mlearned**

**Comment by andyjlewis** [comment]
@sabbour thank you for the feedback and so sorry about this issue getting lost in the shuffle. I'm pretty sure the essence of the content in topic you originally posted your issue about has been refactored into other topics. One of them is this one: https://docs.microsoft.com/azure/devops/pipelines/repos/github. Please see that and other topics under Repositories and feel free to raise another issue over there if you are not finding what you need.
