### ISSUE TITLE
Syntax highlighting for C# in a code block doesn't work for me.

### ISSUE THREAD

**Issue by nadcraker** [MicrosoftDocs/vsts-docs#1193]
I have TFS 2017 (Version 15.117.27414.0), and I cannot get C# language syntax highlighting to work on a readme.md file for my repo. 

Here is my wiki markdown:
``` csharp
public void Run()
{
  Logger.Get().Append("Run method called! Time to do stuff!", LogVerboseLevel.Normal);
}
```
This produces just a regular code block, not one with color highlighting.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fa622358-f5bb-1f5c-177a-081a37b6acef
* Version Independent ID: 72f7fd16-a822-66c8-3a34-8905645ce5f2
* Content: [Syntax usage for Markdown files, widgets, wikis, and pull requests - VSTS & TFS](https://docs.microsoft.com/en-us/vsts/project/wiki/markdown-guidance?view=vsts)
* Content Source: [docs/project/wiki/markdown-guidance.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/project/wiki/markdown-guidance.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by nadcraker** [comment]
Well it seems to work here.

**Comment by KathrynEE** [comment]
@nadcracker - thank you for your inquiry. If you add the csharp tag to the syntax - it should appear in color. 

``` csharp
public void Run()
{
  Logger.Get().Append("Run method called! Time to do stuff!", LogVerboseLevel.Normal);
}
```

If that doesn't work, then the color highlighting may not be supported on your version of TFS.
