### ISSUE TITLE
Maximum widgets on dashboard

### ISSUE THREAD

**Issue by mkuzminski** [MicrosoftDocs/vsts-docs#1197]
What is the maximum number of widgets that can be added to a dashboard?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dcb11d2d-86bd-ff52-d191-4da86d54b473
* Version Independent ID: 79438e17-b3d3-0331-5040-98107eb840a2
* Content: [Dashboards, charts, & widgets - VSTS & TFS](https://docs.microsoft.com/en-us/vsts/report/dashboards/overview?view=vsts)
* Content Source: [docs/report/dashboards/overview.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/report/dashboards/overview.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by PeterAntal** [comment]
A dashboard can contain a maximum of 200 widgets.

**Comment by KathrynEE** [comment]
@mkuzminski  - Thank you for your inquiry. The product team has confirmed that you can add up to 200 widgets to a dashboard.
