### ISSUE TITLE
Team PR page moved when using new navigation scheme

### ISSUE THREAD

**Issue by mudnug** [MicrosoftDocs/vsts-docs#1200]
The [company-instance].visualstudio.com/_pulls URL now returns "404." Is there a comparable page which lists all PRs which are assigned to you and your teams/groups across repositories under the June/July Navigation updates?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 028e7b61-62e4-a10e-e420-3535f7843f0e
* Version Independent ID: 1a6fdbe7-5ba4-a7f8-1b2e-271289a7b9fd
* Content: [Review and merge code with pull requests](https://docs.microsoft.com/en-us/vsts/git/pull-requests?view=vsts)
* Content Source: [docs/git/pull-requests.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/git/pull-requests.md)
* Product: **devops**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
@mudnug Let me find out for you.

**Comment by mmitrik** [comment]
@mudnug There isn't an exact replacement of the _pulls page at this time.  The best alternative is the My Work experience, which you can access from the checklist icon in the upper right corner:

![image](https://user-images.githubusercontent.com/940508/42240730-3908472e-7ed6-11e8-8c2a-a4604239e459.png)

We are tracking an issue on the Developer Community if you want to follow along for status updates: https://developercommunity.visualstudio.com/content/problem/280894/there-is-no-pulls-page-equivalent-in-the-new-navig.html?childToView=286483#comment-286483

**Comment by mudnug** [comment]
Thanks for tracking down the community link for me. 

Since the My Work experience doesn't show PRs "Assigned to my team(s)" it is not really an alternative but I am finding I can customize the screen under Code -> Pull Requests to include PRs assigned to certain teams 
![image](https://user-images.githubusercontent.com/859143/42241291-44dc3d8a-7ec7-11e8-8b2c-add9b0e6c6b4.png)

**Comment by mmitrik** [comment]
Yep, that's another option with the limitation you called out.

**Comment by steved0x** [comment]
I'll make sure to get this section updated: [Manage your pull requests](https://docs.microsoft.com/en-us/vsts/git/pull-requests?view=vsts#manage-your-pull-requests) with the info from this thread.
