### ISSUE TITLE
What ruby versions are available?

### ISSUE THREAD

**Issue by jmoody** [MicrosoftDocs/vsts-docs#1201]
This page should display or link to a document that shows the available ruby versions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 02568f8b-6928-c8f1-178a-79e4cb0d93e2
* Version Independent ID: 1107622c-4165-dcff-741a-279757b35323
* Content: [Use Ruby Version](https://docs.microsoft.com/en-us/vsts/pipelines/tasks/tool/use-ruby-version?view=vsts#feedback)
* Content Source: [docs/pipelines/tasks/tool/use-ruby-version.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/tool/use-ruby-version.md)
* Product: **devops**
* GitHub Login: @erickson-doug
* Microsoft Alias: **dastahel**

**Comment by DavidStaheli** [comment]
Thanks, @jmoody!  This should be live in the documentation later today.
