### ISSUE TITLE
An example of a "versionSpec" range should be provided

### ISSUE THREAD

**Issue by jmoody** [MicrosoftDocs/vsts-docs#1202]
```
# What is the range format?
"~&gt; 2.4"
"&gt;= 2.3.1", "&lt; 2.4"
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 02568f8b-6928-c8f1-178a-79e4cb0d93e2
* Version Independent ID: 1107622c-4165-dcff-741a-279757b35323
* Content: [Use Ruby Version](https://docs.microsoft.com/en-us/vsts/pipelines/tasks/tool/use-ruby-version?view=vsts#feedback)
* Content Source: [docs/pipelines/tasks/tool/use-ruby-version.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/tool/use-ruby-version.md)
* Product: **devops**
* GitHub Login: @erickson-doug
* Microsoft Alias: **dastahel**

**Comment by DavidStaheli** [comment]
Examples are now provided [here](https://docs.microsoft.com/en-us/azure/devops/pipelines/languages/ruby?view=vsts).  Please reopen this issue if we can provide additional help.
