### ISSUE TITLE
Text duplication

### ISSUE THREAD

**Issue by tsahi** [MicrosoftDocs/vsts-docs#1203]
The second and third paragraphs are almost identical. From the source, it looks like one is for TFS and one is for VSTS, but there is no indication for it in the rendered text.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 973bb49c-7fcb-a953-21ff-82b03f899e73
* Version Independent ID: 507b2d8b-9560-9afb-4628-ae562832c7ce
* Content: [Share content by creating a wiki for your team project - VSTS & TFS](https://docs.microsoft.com/en-us/vsts/project/wiki/wiki-create-repo?view=vsts)
* Content Source: [docs/project/wiki/wiki-create-repo.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/project/wiki/wiki-create-repo.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@tsahi - thank you for the feedback. You are correct that the text was duplicated. I'm correcting it now and the change should be live later today.
