### ISSUE TITLE
Merge wizard showing changesets which are merged from target

### ISSUE THREAD

**Issue by KiruthikaSubramaniam** [MicrosoftDocs/vsts-docs#1204]
I.Source: code1
Target : code2

Source Changeset : c1

step 1: merge Source Changeset(c1) from Source to Target 

Now Target Changeset :c2

************************************************
Source: code2
Target : code1

step 2:Open merge wizard in Target

Click selected changeset
Source branch: code2
Target branch: code1

While trying to merge, it is showing changeset c2 whose changes are actually merge from Target.Please help me in this.

**Comment by steved0x** [comment]
@KiruthikaSubramaniam Thank you for your feedback. This GitHub repo is for filing documentation issues. Please file your question at  https://developercommunity.visualstudio.com/spaces/21/index.html

Thank you,
Steve
