### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by jawn** [MicrosoftDocs/vsts-docs#1205]
The title "Link types" has a &lt; character that should be removed

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77829252-e5e1-9458-1f8b-716ff67c8e22
* Version Independent ID: db144baa-772a-6950-1b34-bd188ca656d7
* Content: [witAdmin:Customize and manage objects for tracking work - TFS](https://docs.microsoft.com/en-us/vsts/work/customize/reference/witadmin/witadmin-customize-and-manage-objects-for-tracking-work?view=tfs-2018)
* Content Source: [docs/work/customize/reference/witadmin/witadmin-customize-and-manage-objects-for-tracking-work.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/work/customize/reference/witadmin/witadmin-customize-and-manage-objects-for-tracking-work.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by steved0x** [comment]
@jawn Thanks for letting us know, I just fixed this and it should be live shortly.
