### ISSUE TITLE
Leaf node behaviour changed

### ISSUE THREAD

**Issue by SteRichardson** [MicrosoftDocs/vsts-docs#1211]
The sections around 'Only leaf nodes appear on x' no longer appear to be accurate, I can see a PBI and a child PBI on the same board and backlog at the moment. (not that I'm complaining, but the docs need updating)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c85fc76f-6cf3-2b74-0d50-cd8500b56679
* Version Independent ID: 84fce3ee-5f76-6529-8e97-1ccf0ab68344
* Content: [Resolve backlog issues](https://docs.microsoft.com/en-us/vsts/work/backlogs/resolve-backlog-reorder-issues?view=vsts#feedback)
* Content Source: [docs/work/backlogs/resolve-backlog-reorder-issues.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/work/backlogs/resolve-backlog-reorder-issues.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@SteRichardson - Thank you for your inquiry. I'm also seeing the same change in behavior on my VSTS account. I've reached out to the product team and they indicated no change was planned. As I get more information from them, I'll update the topic accordingly.
