### ISSUE TITLE
build alias are now prefixed with an underscore in release definitions

### ISSUE THREAD

**Issue by boblechat** [MicrosoftDocs/vsts-docs#1216]
In a release definition, when adding a build artifact, the source alias is prefixed with an underscore.
There is no mention of this new "feature / behavior" in the documentation.

![image](https://user-images.githubusercontent.com/34745154/42275264-05976f22-7f90-11e8-8a2a-89834a6b7f57.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 598465e1-85d4-4961-b8b6-902d6026c5e3
* Version Independent ID: 5ef1308a-3aeb-fcc4-dec7-6f10785612a3
* Content: [Artifacts in Release Management](https://docs.microsoft.com/en-us/vsts/pipelines/release/artifacts?view=vsts)
* Content Source: [docs/pipelines/release/artifacts.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/release/artifacts.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment]
Thank you for your feedback. I will update the topic to include your feedback.
