### ISSUE TITLE
Great article

### ISSUE THREAD

**Issue by belgaard** [MicrosoftDocs/vsts-docs#1217]
... but you should probably rephrase this,
"We also understood there is no place like production. This is the shift-right part of the strategy. This is the shift-right part of the strategy. it’s a set of practices about both safeguarding the production as well as ensuring quality in production."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 23818e5e-5c57-4460-8e9d-1c8379b72a30
* Version Independent ID: 82653819-279e-1418-468d-759085e10498
* Content: [Evolving Test Practices at Microsoft - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/devops-at-microsoft/evolving-test-practices-microsoft)
* Content Source: [https://mseng.visualstudio.com/DefaultCollection/TechnicalContent/_git/devops-learn-pr?path=%2fdocs%2fdevops-at-microsoft%2fevolving-test-practices-microsoft.md&version=GBlive&_a=contents](https://mseng.visualstudio.com/DefaultCollection/TechnicalContent/_git/devops-learn-pr?path=%2fdocs%2fdevops-at-microsoft%2fevolving-test-practices-microsoft.md&version=GBlive&_a=contents)
* Product: **devops**
* Git Login: **samgu**
* Microsoft Alias: **munils**

**Comment by steved0x** [comment]
@belgaard I'll pass this feedback along, thank you. What would you change it to? Is it just removing the duplicate `This is the shift-right part of the strategy` part?

**Comment by belgaard** [comment]
Yes




/Brian







On Thu, Jul 5, 2018 at 4:06 PM +0200, "Steve Danielson" <notifications@github.com> wrote:












@belgaard I'll pass this feedback along, thank you. What would you change it to? Is it just removing the duplicate This is the shift-right part of the strategy part?

**Comment by steved0x** [comment]
I just checked this in and it will be live soon, thanks for the great feedback.

Steve
