### ISSUE TITLE
Rest clients parity with Rest API

### ISSUE THREAD

**Issue by danielstefanescu** [MicrosoftDocs/vsts-docs#1218]
Any plans to include clients for Releases/Dashboards/Widgets?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e827e88c-c4a5-c8ce-3ac2-afc61a27d8c9
* Version Independent ID: 5f2514f2-13dd-229b-4ce0-9880a6687ead
* Content: [REST Clients](https://docs.microsoft.com/en-us/vsts/extend/reference/client/rest-clients?view=vsts)
* Content Source: [docs/extend/reference/client/rest-clients.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/extend/reference/client/rest-clients.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by elbatk** [comment]
Hey people, adding @willsmythe to address this question for ya :)
