### ISSUE TITLE
Page is not fully compatible with dark theme

### ISSUE THREAD

**Issue by MMThornberg** [MicrosoftDocs/vsts-docs#1222]
People, branch and commit names are not readable when using dark theme

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fc4fa671-48df-7fc6-eb39-06da85dc1e39
* Version Independent ID: 4ef522f6-24df-df64-3257-854ae27b2b9f
* Content: [The Race to Push - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/git/race-to-push)
* Content Source: [https://mseng.visualstudio.com/DefaultCollection/TechnicalContent/_git/devops-learn-pr?path=%2fdocs%2fgit%2frace-to-push.md&version=GBlive&_a=contents](https://mseng.visualstudio.com/DefaultCollection/TechnicalContent/_git/devops-learn-pr?path=%2fdocs%2fgit%2frace-to-push.md&version=GBlive&_a=contents)
* Product: **devops**
* Git Login: **samgu**
* Microsoft Alias: **sanoursa**

**Comment by steved0x** [comment]
@MMThornberg I apologize for that - this has been an ongoing issue, but I am going to get it fixed this week. I didn't realize it also applied to the "Git at Scale" articles.

**Comment by steved0x** [comment]
This is fixed and should be live in a day or two, thank you.
