### ISSUE TITLE
Consumer fails on http

### ISSUE THREAD

**Issue by hdesouky** [MicrosoftDocs/vsts-docs#1223]
I followed the instructions in the documentation. However when i install the extension on vsts and try to create a new consumer through my new extension, it fails the test when i use http instead of https in the url.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 758bed7c-374d-996e-ebff-c68528a823ca
* Version Independent ID: 81777b37-38ab-a7df-6eaa-7aa6bcd1058c
* Content: [Create a consumer service for service hooks](https://docs.microsoft.com/en-us/vsts/extend/develop/add-service-hook?view=vsts)
* Content Source: [docs/extend/develop/add-service-hook.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/extend/develop/add-service-hook.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by elbatk** [comment]
Hey @hdesouky , adding @willsmythe to take a look at this :)

**Comment by willsmythe** [comment]
Unfortunately, only HTTPS URLs can be used with contributed service hook consumers.

**Comment by hdesouky** [comment]
@willsmythe I can see this, however how it come the built in generic web hook consumer support HTTP and HTTPS :)
