### ISSUE TITLE
Multiple phases do run in sequence on TFS 2018.2

### ISSUE THREAD

**Issue by biohazard999** [MicrosoftDocs/vsts-docs#1224]
&gt; Multiple phases you add to a build definition run in parallel. Multiple phases you add to a release definition run in sequence. You cannot configure the order of dependencies between phases in this version of TFS.

This is not correct, they run in sequence, or I configured it wrong :(
I want to build on windows, mac and linux in parallel, but can't get it configured correctly. For now I need to use multiple builds.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von Problemen docs.microsoft.com ➟ GitHub erforderlich.*

* ID: a14fc554-e74e-2c76-34d1-37a2e0dd7b2f
* Version Independent ID: e95259f4-61ef-5e99-a492-eb77d7d1e657
* Content: [Workflow using multiple phases in Build and Release Management](https://docs.microsoft.com/de-at/vsts/pipelines/process/multiple-phases?view=tfs-2018&tabs=web)
* Content Source: [docs/pipelines/process/multiple-phases.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/multiple-phases.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment]
Thank you for your feedback. I have passed this on to the product team for advice.

**Comment by RoopeshNair** [comment]
Support for running phases in parallel in release is still few months away (~5-6 months tentatively). On VSTS build supports running phases in parallel, for support in TFS @vijayma

**Comment by vijayma** [comment]
Can you confirm my understanding of your setup?
- You are using TFS 2018.2.
- You have a build definition with three phases.
- There are no dependencies specified between these phases (you can configure the dependencies when you select the phase in the editor).
- You are seeing that the phases run in sequence.

If so, this is not expected, and we would like to follow up with you.

**Comment by oneillci** [comment]
I can confirm this behaviour. 
I have a build definition with 3 phases. I want 2 to run in parallel and the 3rd to wait for previous to succeed.
Phase 1 & Phase 2 have no Dependencies and are set to 'Even if a previous Phase has failed'.
3rd Phase has Phase 1 & 2 as Dependencies and set to 'Only when all previous phases have succeeded'

When I queue a build, they all run in sequence. Phase 1 & 2 do not run in parallel

**Comment by anblanco** [comment]
+1. I also noticed the same behavior in Release using VSTS. It appears the Phases in Build will run in parallel, but Phases in Release will run in sequence, even if I put true in the custom condition

**Comment by vijayma** [comment]
Thanks for pointing this out. We went and checked again in 2018.2, and indeed found that the ability to run phases in parallel did not exist in 2018.2. That feature missed 2018.2 by a very narrow margin. Sorry about the confusion. We are fixing the doc to clarify this.

**Comment by oneillci** [comment]
To clarify, I'm seeing the behaviour of build phases running in sequence and not in parallel on vsts and not tfs.

**Comment by vijayma** [comment]
@oneillci, I was responding to the original question by @biohazard999. Regarding your issue in VSTS, to run both the jobs in parallel, you need a concurrency of 2 jobs. My guess is that you do not. You can check the concurrency limits you have by going to Project settings -> Build and Release -> Concurrency. You can purchase additional concurrency if you desire. Another possibility if that you do not have "Build with multiple queues" preview feature enabled. You can check that in your user profile -> Preview features -> Account features.

**Comment by oneillci** [comment]
@vijayma, if I'm looking at the correct setting, I do have enough concurrent jobs permitted:
![image](https://user-images.githubusercontent.com/641669/43372181-67f0b312-93e1-11e8-8ee6-17db78fe1d02.png)

When running my build, my agent phases are not running in parallel. In this example, phase 1 and 2 do not have any dependencies, but phase 3 depends on both 1 & 2. All phases are set to run on the same agent queue. Do I need to have multiple agents running in that queue or does this look like I'm doing something else wrong?
![image](https://user-images.githubusercontent.com/641669/43372211-b64ae258-93e1-11e8-8232-377886a1d29f.png)

**Comment by oneillci** [comment]
I've tried adding more agents to my pool and now have them running parallel :) Have submitted some content feedback on that page as this was no clear from the existing documentation.

**Comment by SteveSims2** [comment]
I can also verify this.   We are running TFS 2018.3 in production with a new install on the test server.   Even in BUILDS (nevermind the release pipeline), phases not only run serially, the dependencies setting on the phase properties isn't even there.   It is there in Azure DevOps.   Not in an on-premises installation.   There does not seem to be any means of using parallelism usefully in an on-premises installation of TFS 2018.3.....

**Comment by ExcaliburVT** [comment]
Also verified.  Running TFS 2018.3 and cannot find any way to run Phases in parallel.  This is a serious issue for us as it is making our Releases run extraordinarily long.  Please advise when this is going to be resolved for on-prem or a workaround?
