### ISSUE TITLE
"windows machine file copy" "Clean target" copy is slow when a large number of files are present in the target folder

### ISSUE THREAD

**Issue by queBurro** [MicrosoftDocs/vsts-docs#1230]
"windows machine file copy" "Clean target" copy is slow when a large number of files are present in the target folder.

Tested on TFS2015

to reproduce:

1. copy to a remote machine a zip to an empty folder (this is quick)
2. unzip it 
3. repeat - copy is now slow and full of "Extra fir" "Extra file" 

also 

1. copy zip / unzip it/ copy single small file - this too is slow. Should be quick.

Cheers,

**Comment by alexhomer1** [comment]
Thank you for your feedback. I will pass this on to the product team and update the topic based on their response.

**Comment by RoshanKumarMicrosoft** [comment]
@queBurro  Which task version are you using ? Can you please share file size in target and how much this operation is taking to complete ? Please share the debug logs to RM_Customer_Queries@microsoft.com.

**Comment by queBurro** [comment]
I believe what's happening is that the "remove-item" is being run on the agent's host against the remote host. This means that the files are being moved across the nw before being deleted. I've swapped this "delete task" for some in-line powershell that runs the "remove-item" on the target machine and the time taken is as it should be.

**Comment by queBurro** [comment]
I'm using version TFS2015.3. I've not got any logs from 2 months ago.

**Comment by RoshanKumarMicrosoft** [comment]
@queBurro We are taking mirror image with empty folder through robocopy to clean target. We are just cleaning the empty folder in last which is on agent box [Link](https://github.com/Microsoft/vsts-tasks/blob/master/Tasks/WindowsMachineFileCopyV2/RoboCopyJob.ps1#L106). We had already done [fixes](https://github.com/Microsoft/vsts-tasks/commit/f279ef7a4f2df98a6c6ce9001adb68f1a47e8faa#diff-9168ef287e3ce4cc5de01362be814bf0). If you still face any issue please write to RM_Customer_Queries@microsoft.com.

**Comment by steved0x** [comment]
@queBurro I am closing this GitHub issue - if the previous comments don't resolve your issue, please send email to `RM_Customer_Queries@microsoft.com` as described in the previous comment. Thank you.
