### ISSUE TITLE
Cannot Use Code From VSTS

### ISSUE THREAD

**Issue by srsedate** [MicrosoftDocs/vsts-docs#1232]
Since we linked Azure AD to our VSTS instance, users are not able to clone Git repositories from VSTS.  When they try to use any of the VSTS tools in Visual Studio (2015, 2017, etc. (Professional, Enterprise, etc.)), or when we try to use third-party Git tools, or when we select "Clone Using IDE" from VSTS, all authentication fails.  All login forms that show up expect a "Personal" Microsoft account, and do not allow signing in with an Azure AD account.  They also do not allow the use of PAT tokens.  This authentication failure renders the code portion of VSTS unusable when using Azure AD to authenticate.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f1e6ad72-c0da-3849-1b77-e6688ca71d95
* Version Independent ID: cf1a8a38-4726-25dd-ec63-bfb09b561802
* Content: [Connect VSTS account to Azure Active Directory (Azure AD)](https://docs.microsoft.com/en-us/vsts/organizations/accounts/connect-account-to-aad?view=vsts#next-steps)
* Content Source: [docs/organizations/accounts/connect-account-to-aad.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/accounts/connect-account-to-aad.md)
* Product: **devops**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
@srsedate Thank you for letting us know and we're sorry you're experiencing difficulties - this issue has been assigned to one of our PMs, who should be in touch with you soon.

**Comment by AdamCaviness** [comment]
I'm experiencing the same issue as described by @srsedate. Three days ago we connected our VSTS to AAD. In Visual Studio it appears to be connected to my personal account when trying to work with our repos on VSTS. I've removed the VSTS credential in Windows Credential Manager and that has no effect. I'm able to see the repo in Team Explorer and connect to it without difficulty. When I attempt to push I receive the following:

Error: cannot spawn /C/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/Common7/IDE/CommonExtensions/Microsoft/TeamFoundation/Team Explorer/Git/mingw32/libexec/git-core/git-askpass.exe: No such file or directory
Error encountered while pushing branch to the remote repository: Git failed with a fatal error.
could not read Username for 'https://ourdomain.visualstudio.com': terminal prompts disabled
Pushing to https://ourdomain.visualstudio.com/defaultcollection/_git/MyRepo

If I just use the third-party Git Gui and attempt to connect I receive the following:
Logon failed, use ctrl+c to cancel basic credential prompt.
fatal: Authentication failed for 'https://ourdomain.visualstudio.com/defaultcollection/_git/MyRepo/'

**Comment by chcomley** [comment]
@AdamCaviness, thanks for your comment and we're sorry you are also experiencing difficulties. @AdamCaviness and @srsedate, would you both please send me an email listing your VSTS URL and email address of your GitHub identities, so we can investigate? chcomley@microsoft.com
Thanks

**Comment by AdamCaviness** [comment]
@chcomley thanks for checking up on this. It resolved itself without any interaction within 12 hours so I presume the workload was not synchronized fully.

**Comment by wgv-srsedate** [comment]
This issue can be considered resolved.  After removing the credentials from the Credential Manager, and deleting the Git cache file in local app data, the issue resolved itself.

**Comment by chcomley** [comment]
Fantastic, thanks to you both - glad to know it's working for you.
