### ISSUE TITLE
Comments on PR's integration with slack?

### ISSUE THREAD

**Issue by boldwade** [MicrosoftDocs/vsts-docs#1235]
Is it possible to have comments on PR's show up in slack?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7fd5671b-b7b8-9acb-c195-7897fec3538b
* Version Independent ID: ff894c1b-f2f7-581d-94b4-dbc77d80ad6d
* Content: [Slack with VSTS](https://docs.microsoft.com/en-us/vsts/service-hooks/services/slack?toc=%2fvsts%2fnotifications%2ftoc.json&%3bbc=%2fvsts%2fnotifications%2fbreadcrumb%2ftoc.json&view=vsts)
* Content Source: [docs/service-hooks/services/slack.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/service-hooks/services/slack.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by elbatk** [comment]
Hi @boldwade , adding @willsmythe to take a look at this for you!

**Comment by willsmythe** [comment]
Good suggestion. This is currently not supported. You can open this as a suggestion on the VSTS UserVoice forum (or vote/comment if someone else already has) here: https://visualstudio.uservoice.com/forums/330519-team-services
