### ISSUE TITLE
Create Virtual Directory

### ISSUE THREAD

**Issue by Gold14388** [MicrosoftDocs/vsts-docs#1237]
This task template does not show an option to create a virtual directory in IIS but the document says it can. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 244121ae-5de4-14cd-a9c3-d9cda5ad0a3b
* Version Independent ID: 313238b7-d67b-bc60-1188-cbe305179600
* Content: [IIS Web App Manage](https://docs.microsoft.com/en-us/vsts/pipelines/tasks/deploy/iis-web-app-management-on-machine-group?view=vsts)
* Content Source: [docs/pipelines/tasks/deploy/iis-web-app-management-on-machine-group.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/deploy/iis-web-app-management-on-machine-group.md)
* Product: **devops**
* GitHub Login: @erickson-doug
* Microsoft Alias: **dastahel**

**Comment by DavidStaheli** [comment]
@RoopeshNair do you know who owns this doc for IISWebApp**Management**OnMachineGroupV0?

**Comment by RoopeshNair** [comment]
@Gold14388 - you should be able to select configuration type from the IIS manage task. It has following options. Let us know if this isn't working for you
* IIS Website
* IIS Web application
* IIS virtual directory
* IIS application pool
