### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by turibbio** [MicrosoftDocs/vsts-docs#1242]
**Creating productive, customer focused teams** link is broken. I suppose that the correct link should be https://docs.microsoft.com/en-us/azure/devops/agile/productive-teams

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7669a6fa-56a7-d6cb-f6ff-77ab120031a1
* Version Independent ID: c4def84a-8348-cd4d-a2c3-cf5503b0ad87
* Content: [What is Agile Development? - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/agile/what-is-agile-development)
* Content Source: [https://mseng.visualstudio.com/DefaultCollection/TechnicalContent/_git/devops-learn-pr?path=%2fdocs%2fagile%2fwhat-is-agile-development.md&version=GBlive&_a=contents](https://mseng.visualstudio.com/DefaultCollection/TechnicalContent/_git/devops-learn-pr?path=%2fdocs%2fagile%2fwhat-is-agile-development.md&version=GBlive&_a=contents)
* Product: **devops**
* Git Login: **samgu**
* Microsoft Alias: **dahellem**

**Comment by steved0x** [comment]
@turibbio I'll get that link fixed, thanks for letting us know!

**Comment by scottkuhl** [comment]
FYI:  Link is still not fixed.

**Comment by steved0x** [comment]
It is fixed and should be live momentarily.
