### ISSUE TITLE
Breaking changes to VSTS templates?

### ISSUE THREAD

**Issue by dbrtly** [MicrosoftDocs/vsts-docs#1243]
3. Select the .NET Desktop template.

Maybe I'm a dummy but I can't find this template when I search for it. Not sure if it has been renamed or removed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a56478c9-7dfc-43e9-c348-357dc6862d73
* Version Independent ID: dd3cd0a1-dc03-15d3-1298-b76d770e4760
* Content: [Build your SQL server database](https://docs.microsoft.com/en-us/vsts/pipelines/apps/aspnet/build-aspnet-dacpac?view=vsts)
* Content Source: [docs/pipelines/apps/aspnet/build-aspnet-dacpac.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/apps/aspnet/build-aspnet-dacpac.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by dbrtly** [comment]
found it

**Comment by steved0x** [comment]
@dbrtly I'm glad you found it, do we need to update our documentation to make anything more clear? Or was it just a case of that template being hard to find for some reason?
