### ISSUE TITLE
Mention user with "@" not alwayes send an email 

### ISSUE THREAD

**Issue by shayki5** [MicrosoftDocs/vsts-docs#1248]
Hi,

**We use TFS 2017.3 on-prem.**
I encountered strange behavior when I try to mention user with "@" in a comment on changeset or shelveset.
I tried in our few team projects and the results are different. There are team projects that if I mention user on changeset/shelveset (in a comment) he doesn't receive any email, in other TP's the user receive email ONLY in the changeset, and in other TP's the user receive email on changeset and on shelveset.
On changeset it works, but not on shelvesets.

Thank you.

**Comment by steved0x** [comment]
@shayki5 You are the 2nd person to mention this, let me check for you.

**Comment by shayki5** [comment]
**Update:** I tried in other team projects and the results are different. There are team projects that if I mention user on changeset/shelveset (in a comment) he doesn't receive any email, in other TP's the user receive email ONLY in the changeset, and in other TP's the user receive email on changeset and on shelveset.

 I catch an error on the event view immediately after I mention user on shelveset (and email didn't send):
```
- <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name="Microsoft-Team Foundation Server" Guid="{80761876-6844-47D5-8106-F8ED2AA8687B}" /> 
  <EventID>0</EventID> 
  <Version>5</Version> 
  <Level>2</Level> 
  <Task>1</Task> 
  <Opcode>10</Opcode> 
  <Keywords>0x8000000000000001</Keywords> 
  <TimeCreated SystemTime="2018-07-09T10:55:39.204929100Z" /> 
  <EventRecordID>13527146</EventRecordID> 
  <Correlation ActivityID="{261FFC27-973D-471B-B5E5-06A3D0C2AFA5}" /> 
  <Execution ProcessID="6740" ThreadID="5284" /> 
  <Channel>Microsoft-Team Foundation Server/Debug</Channel> 
  <Computer>TLVTFS15APPTST1.nice.com</Computer> 
  <Security UserID="S-1-5-21-593699164-1228343305-1847928074-3167613" /> 
  </System>
- <UserData>
- <Info TraceId="{00000001-0001-0001-0000-000000000000}" xmlns="http://schemas.microsoft.com/TeamFoundation/2010/Framework">
  <Tracepoint>101933</Tracepoint> 
  <ServiceHost>{2931588F-5259-4279-A88F-A25C84338979}</ServiceHost> 
  <ContextId>80252</ContextId> 
  <ProcessName>w3wp</ProcessName> 
  <Username /> 
  <VSID>{000007F5-0000-8888-8000-000000000000}</VSID> 
  <CUID>{00000000-0000-0000-0000-000000000000}</CUID> 
  <TenantId>{00000000-0000-0000-0000-000000000000}</TenantId> 
  <ProviderId>{00000000-0000-0000-0000-000000000000}</ProviderId> 
  <Service /> 
  <Method /> 
  <Area>MentionService</Area> 
  <Layer>Service</Layer> 
  <UserAgent /> 
  <Uri /> 
  <Path /> 
  <UniqueIdentifier>{00000000-0004-0000-0000-00004A3B0FFC}</UniqueIdentifier> 
  <UserDefined /> 
  <ExceptionType /> 
  <Message>The string must have at least one non-white-space character. Parameter name: artifactTitle</Message> 
  <E2EID>{00000000-0000-0000-0000-000000000000}</E2EID> 
  </Info>
  </UserData>
  </Event>
```

**Comment by steved0x** [comment]
@shayki5 I checked into it and it looks like it could be a bug. The issues in this repo are for content feedback, and this looks like a bug. For product feedback, including bugs, please file an issue here: https://developercommunity.visualstudio.com/spaces/21/index.html

This will engage the product team directly.

Thank you,

Thank you.

**Comment by shayki5** [comment]
Ok, thank you!
