### ISSUE TITLE
Pull request validation trigger is missing?

### ISSUE THREAD

**Issue by erewok** [MicrosoftDocs/vsts-docs#1251]
Hello,

I am trying to create a build definition for building Pull Requests. Under triggers, there is no "enable pull request validation". I have seen screenshots in [other issues](https://github.com/Microsoft/vsts-agent/issues/1381) that show this checkbox. Why am I missing it? 

Also: should this ticket go somewhere else?

**Comment by steved0x** [comment]
@madhurig Do you know why @erewok is missing the `enable pull request validation` under triggers? I saw that you had engaged on the linked issue and might know. Thank you!

**Comment by madhurig** [comment]
@erewok: Where is your source code - in VSTS or GitHub or some other location?

Thanks,
Madhuri

**Comment by erewok** [comment]
Hi @madhurig: our source code is in VSTS.

I *was* able to build Pull Requests by enabling "Custom condition using variable expressions" and entering the following "Variable expression" under `Phase 1`:

```
and(succeeded(), eq(variables['Build.Reason'], 'PullRequest'))
```

This is different from what the docs said, though, which is what prompted the issue.

**Comment by madhurig** [comment]
@erewok: Pull Request validation builds for source code in VSTS is setup via branch policies and does not show up on the build definition. Please check out this doc: https://docs.microsoft.com/en-us/vsts/git/branch-policies?view=vsts#build-validation
