### ISSUE TITLE
The plugin link does not work

### ISSUE THREAD

**Issue by SamirFarhat** [MicrosoftDocs/vsts-docs#1253]
You are saying that https://marketplace.eclipse.org/content/team-explorer-everywhere is the good URL. It does not work. The previous link (on the screenshot is the good one)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6d30df51-6527-9482-8a71-782e45080e81
* Version Independent ID: 2810a642-a547-4285-ad82-1365177ac431
* Content: [Clone a VSTS Git repository with Eclipse](https://docs.microsoft.com/en-us/vsts/java/labs/eclipsegit/?view=vsts)
* Content Source: [docs/java/labs/eclipsegit/index.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/java/labs/eclipsegit/index.md)
* Product: **devops**
* GitHub Login: @erickson-doug
* Microsoft Alias: **douge**

**Comment by eriawan** [comment]
This is definitely a bug, because
The marketplace link to Team Explorer Everywhere is not working.

And I can only use the https://dl.microsoft.com/eclipse on Eclipse. Screenshot:

![image](https://user-images.githubusercontent.com/8773147/42508848-261df354-8474-11e8-9922-edc0a4cbebd9.png)

I will create a PR for this tomorrow.

**Comment by steved0x** [comment]
@SamirFarhat @eriawan I will get this fixed. To confirm I understand correctly, to read about the plugin, you can use `https://marketplace.eclipse.org/content/team-explorer-everywhere` but when specifying the location in Eclipse, `https://dl.microsoft.com/eclipse/` is still the correct value?

**Comment by eriawan** [comment]
@steved0x 

Thanks for the reply!
Yes, the `https://dl.microsoft.com/eclipse/` should be used for the location of the update site, not the marketplace link.

**Comment by SamirFarhat** [comment]
Yes, this is more accurate.

**Comment by steved0x** [comment]
@SamirFarhat @eriawan I am fixing this today and it should go live later today or tomorrow, sorry for the trouble and thank you for letting us know!
