### ISSUE TITLE
Adding Windows Service release folder into artifacts folder 

### ISSUE THREAD

**Issue by Gold14388** [MicrosoftDocs/vsts-docs#1254]
I am trying to add windows service release folder into artifacts folder but I want to add under a certain folder like service name folder inside artifacts. Currently, I tried to copy files task but it adds just a bin folder inside artifacts for a service

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 81f02378-b85b-d3a4-d3c8-f07d935367da
* Version Independent ID: fab57f76-35d2-4024-6f7f-1740d7b24743
* Content: [Copy Files](https://docs.microsoft.com/en-us/vsts/pipelines/tasks/utility/copy-files?view=vsts)
* Content Source: [docs/pipelines/tasks/utility/copy-files.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/utility/copy-files.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by aaroncatlin** [comment]
You need to use the Publish Artifacts task, not Copy Files:

https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/publish-build-artifacts?view=azure-devops
