### ISSUE TITLE
The Packages hub is not visible

### ISSUE THREAD

**Issue by SamirFarhat** [MicrosoftDocs/vsts-docs#1255]
You should add the following notice. If you don't see the Packages hub, ask your account owner to install the Package Management extension from the Visual Studio Marketplace (like https://docs.microsoft.com/en-us/vsts/package/feeds/create-feed?view=vsts)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 11f43544-e181-b021-b362-dd7c5c631d7c
* Version Independent ID: 01897be8-0c56-1e83-0e1e-8dea747911ec
* Content: [Configure package management for Maven with VSTS](https://docs.microsoft.com/en-us/vsts/java/labs/mavenpmvsts/?view=vsts)
* Content Source: [docs/java/labs/mavenpmvsts/index.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/java/labs/mavenpmvsts/index.md)
* Product: **devops**
* GitHub Login: @erickson-doug
* Microsoft Alias: **douge**

**Comment by trajano** [comment]
You just need to enable it for your project

![image](https://user-images.githubusercontent.com/110627/45005634-8124f800-afc2-11e8-8bc8-f9279c575b3c.png)

You will then need to give your user access to it afterwards

**Comment by isaiahwilliams** [comment]
The Azure DevOps images referenced in this article are not included in the repository. So, none of the images are rendering as excepted.

**Comment by steved0x** [comment]
I'm adding a clarification and a link to this article at the top to fix this. Thank you for letting us know and sorry for the great delay.
