### ISSUE TITLE
Packer build task with Azure Service Endpoint when using custom template

### ISSUE THREAD

**Issue by riezebosch** [MicrosoftDocs/vsts-docs#1258]
It is currently not possible to use a service endpoint when specifying a custom template. That's sad because I have my own template in the repo but still want to run and deploy it on Azure.

Update: Also opened this issue on the vsts tasks repo: https://github.com/Microsoft/vsts-tasks/issues/7668

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7f2f7a83-5e63-e305-4cc1-d443db82893e
* Version Independent ID: 35b19b29-3f7b-19a3-5bb5-a3af2bbfe4d8
* Content: [Build packer machine image](https://docs.microsoft.com/en-us/vsts/pipelines/tasks/deploy/packer-build?view=vsts)
* Content Source: [docs/pipelines/tasks/deploy/packer-build.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/deploy/packer-build.md)
* Product: **devops**
* GitHub Login: @erickson-doug
* Microsoft Alias: **dastahel**

**Comment by DavidStaheli** [comment]
@RoopeshNair do you know who owns this?

**Comment by RoopeshNair** [comment]
@riezebosch  - can you please elaborate, I didn't get this completely. Thanks

@DavidStaheli - not clear if the question is related to process parameters or service endpoint for tasks or template..

**Comment by riezebosch** [comment]
I want to use the 'packer build' task to build an image using my own packer template. But I also want to use the [Packer Azure Builder](https://www.packer.io/docs/builders/azure.html). But instead of providing the credentials on the arguments (service principal and client secret) I want to use a Service Endpoint. That combination is currently not possible.

This request should probably not be on the docs but on the vsts-tasks repo (where I already logged one). But this was for me the starting point.

**Comment by RoopeshNair** [comment]
@riezebosch - got it thanks. I'm closing this issue, as you have duplicate open in the right repository
