### ISSUE TITLE
Variable scoping...

### ISSUE THREAD

**Issue by dennismi** [MicrosoftDocs/vsts-docs#1263]
Hi

Does phase in the following also refer to environments:
To define or modify a variable from a script, use the task.setvariable logging command. Note that the updated variable value is scoped to the phase being executed and does not flow across phases.

I assume it does, cause I've set the variable in one environment, and the value wasn't available in the next... :(

Am using TFS2017u2 (15.117.26714.0)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 611642f0-881f-10b9-ae94-3c562001d1f0
* Version Independent ID: 41efb94b-4c7a-64a3-b23b-70c8634ae727
* Content: [Variables in Release Management](https://docs.microsoft.com/en-us/vsts/pipelines/release/variables?view=tfs-2017&tabs=powershell)
* Content Source: [docs/pipelines/release/variables.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/release/variables.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment]
Thank you for your feedback. I will pass this on to the product team and update the topic based on their response.
