### ISSUE TITLE
Comments are not enabled in the release posts

### ISSUE THREAD

**Issue by nschonni** [MicrosoftDocs/vsts-docs#1267]
Nothing to comment on this particular post https://docs.microsoft.com/en-ca/vsts/release-notes/2018/jul-10-vsts but the old Brian Harry style allowed for good feedback from users on the releases for quicker user comments on a particular release.
This may have just been a temporary hick-up in the publishing config 😄

**Comment by steved0x** [comment]
@nschonni I'll check and see - I can't recall if feedback was enabled for these before, although I do recall getting feedback and PRs for links and so forth. :)

**Comment by nschonni** [comment]
@steved0x you're right, I was thinking more about these https://blogs.msdn.microsoft.com/bharry/2018/01/30/tfs-2018-update-1-rc-is-available/ but there isn't really an equivalent right now since he's on leave
