### ISSUE TITLE
Wrong command for "Work items" -> "Permanently delete work items"

### ISSUE THREAD

**Issue by TobiasSekan** [MicrosoftDocs/vsts-docs#1268]
The command for "Work items" -&gt; "Permanently delete work items" should be only **destroywi** instead of **witadmin destroywi**

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77829252-e5e1-9458-1f8b-716ff67c8e22
* Version Independent ID: db144baa-772a-6950-1b34-bd188ca656d7
* Content: [witAdmin:Customize and manage objects for tracking work - TFS](https://docs.microsoft.com/en-us/vsts/work/customize/reference/witadmin/witadmin-customize-and-manage-objects-for-tracking-work?view=tfs-2018)
* Content Source: [docs/work/customize/reference/witadmin/witadmin-customize-and-manage-objects-for-tracking-work.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/work/customize/reference/witadmin/witadmin-customize-and-manage-objects-for-tracking-work.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@TobiasSekan  - Thank you for the feedback. I'm correcting the article and changes should appear later today.
