### ISSUE TITLE
Markdown includes not replaced

### ISSUE THREAD

**Issue by jawn** [MicrosoftDocs/vsts-docs#1270]
I see multiple markdown includes in this page, e.g.:

![Schematic showing tasks](_img/2017-user-experience/Process parameters view.png)

Expected: replaced by actual content.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8b96fad0-7bfb-8c02-701a-5960da7fb313
* Version Independent ID: 74847500-c617-31f4-999c-a344e7b4299e
* Content: [New Build Editor](https://docs.microsoft.com/en-gb/vsts/pipelines/archive/preview/2017-user-experience?view=vsts#parameters)
* Content Source: [docs/pipelines/archive/preview/2017-user-experience.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/archive/preview/2017-user-experience.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by steved0x** [comment]
@jawn Thanks for letting us know, we'll take a look and get that fixed.

**Comment by steved0x** [comment]
@jawn I fixed this, I think it selectively didn't like the spaces in some of the image names. It should be live shortly, thanks for letting us know.
