### ISSUE TITLE
Are extension charts supported on TFS?

### ISSUE THREAD

**Issue by labrose** [MicrosoftDocs/vsts-docs#1272]
A partner asked when the client-side "chart" support for extensions would be supported on-prem (because our public docs indicate the feature is only available on hosted: https://docs.microsoft.com/en-us/vsts/extend/develop/add-chart?view=vsts). Apparently the feature is available on TFS (partner indicated he tried on 2017 U3 and it works).

Assuming this capability is supported on-prem, we should update the docs and indicate that it is (and do any other clean-up to the docs since it hasn't been touched since 2016).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4504a134-dfd7-0cc9-3292-6844d49b4fe8
* Version Independent ID: e121af02-6651-65bf-a953-fda719e90e3e
* Content: [Add a chart](https://docs.microsoft.com/en-us/vsts/extend/develop/add-chart?view=vsts)
* Content Source: [docs/extend/develop/add-chart.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/extend/develop/add-chart.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by elbatk** [comment]
Sorry for the long delay here. I find it best to point people with product questions to the [Azure DevOps Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html), which is actively monitored by the product team. Best of luck!
