### ISSUE TITLE
Integrate wit git? 

### ISSUE THREAD

**Issue by cosmoKenney** [MicrosoftDocs/vsts-docs#1275]
Can I reference trello cards in commits and have cards updated when the commit happens?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1402b59d-915f-2457-e198-60898fd66191
* Version Independent ID: af8951ef-3bc1-8748-81a5-03696c6f5e85
* Content: [Trello with VSTS](https://docs.microsoft.com/en-us/vsts/service-hooks/services/trello?view=vsts)
* Content Source: [docs/service-hooks/services/trello.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/service-hooks/services/trello.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by elbatk** [comment]
Hi @cosmoKenney , adding @willsmythe to take a look at this one for ya

**Comment by willsmythe** [comment]
Unfortunately, no. Services like Zapier or Microsoft Flow are likely able to support this. If not, there is always the option of writing custom code that receives the commit events from VSTS (via webhooks), parses the messages for Trello card links, and then calls Trello APIS to update the appropriate cards.
