### ISSUE TITLE
Don't think this was ready to publish

### ISSUE THREAD

**Issue by nschonni** [MicrosoftDocs/vsts-docs#1276]
Looks like this and a few others in https://github.com/MicrosoftDocs/vsts-docs/commit/4995649c62ecf1d4e054b59907e208db0ab75def got pushed out by mistake

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f3579700-2bcc-b38d-4112-c1024fee50fc
* Version Independent ID: d6eb0b15-17a3-ee0a-f264-c86a6db41add
* Content: [Azure DevOps Pipelines New User Guide - Key Concepts](https://docs.microsoft.com/en-ca/vsts/pipelines/basic-pipelines-concepts?view=vsts#feedback)
* Content Source: [docs/pipelines/basic-pipelines-concepts.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/basic-pipelines-concepts.md)
* Product: **devops**
* GitHub Login: @erickson-doug
* Microsoft Alias: **douge**

**Comment by steved0x** [comment]
Ok we just fixed it, thank you!
