### ISSUE TITLE
Ok

### ISSUE THREAD

**Issue by Claudinealexandre30** [MicrosoftDocs/vsts-docs#1278]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca1c5394-611b-b119-dbf3-b88404e351d5
* Version Independent ID: fcc23259-21ec-f9fa-4e25-f587e1e0f41b
* Content: [Deploy to an IIS web server on a Windows Virtual Machine](https://docs.microsoft.com/en-us/vsts/pipelines/apps/cd/deploy-webdeploy-iis-deploygroups?toc=%2fvsts%2fdeploy-azure%2ftoc.json&%3bbc=%2fvsts%2fdeploy-azure%2fbreadcrumb%2ftoc.json&view=vsts)

* Content Source: [docs/pipelines/apps/cd/deploy-webdeploy-iis-deploygroups.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/apps/cd/deploy-webdeploy-iis-deploygroups.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by steved0x** [comment]
@Claudinealexandre30 It looks like your feedback didn't make it into the issue, could you please enter it again as a response to this comment and we'll take a look. Thank you.
