### ISSUE TITLE
Broken link "Packaging solution"

### ISSUE THREAD

**Issue by jawn** [MicrosoftDocs/vsts-docs#1280]
The link "packacking solution" in the text "adopt a packaging solution" returns a 404.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 231de24f-34f2-7845-c90c-415459bdaf89
* Version Independent ID: ad53951a-8762-e636-1220-b39c2c0b165d
* Content: [Migrate from other systems to Git - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/git/migrate-other-systems-to-git)
* Content Source: [https://mseng.visualstudio.com/DefaultCollection/TechnicalContent/_git/devops-learn-pr?path=%2fdocs%2fgit%2fmigrate-other-systems-to-git.md&version=GBlive&_a=contents](https://mseng.visualstudio.com/DefaultCollection/TechnicalContent/_git/devops-learn-pr?path=%2fdocs%2fgit%2fmigrate-other-systems-to-git.md&version=GBlive&_a=contents)
* Product: **devops**
* Git Login: **samgu**
* Microsoft Alias: **routlaw**

**Comment by steved0x** [comment]
@jawn I just merged a fix in our private repo, it should be live shortly. Thank you for letting us know.
