### ISSUE TITLE
Incorrect note ordering on Software Dependencies

### ISSUE THREAD

**Issue by IAmHopp** [MicrosoftDocs/vsts-docs#1282]
There's a comment on the JRE mentioned in Software Dependencies about seeing note 2 in the Notes section that follows.

The only note related to JRE is the third one, probably because the second one as it stands now [about Elasticsearch as it related to Update 2] was added later.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be0bdbf7-3132-9007-6c6a-368c5bcb0f3d
* Version Independent ID: 58118f61-f88f-24b9-b785-d8f9d8a1fefd
* Content: [Code and Work Item Search set up](https://docs.microsoft.com/en-us/vsts/project/search/administration?view=vsts)
* Content Source: [docs/project/search/administration.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/project/search/administration.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment]
Thank you for your feedback. I will update the topic to include your recommendations.
