### ISSUE TITLE
Agent Install Location on Windows

### ISSUE THREAD

**Issue by cbailiss** [MicrosoftDocs/vsts-docs#1284]
Hello, the windows self-hosted agent PowerShell install/registration script provided in the VSTS website for deployment groups installs to the system drive with no option given.  Is it a supported configuration to modify this script to install to a different location?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43799c5d-2f13-cc76-a1c0-a3f850e16d4e
* Version Independent ID: 97a5b73f-faf7-f9c0-9269-fc79984616d6
* Content: [Deploy a build and release agent on Windows](https://docs.microsoft.com/en-us/vsts/pipelines/agents/v2-windows?view=vsts)
* Content Source: [docs/pipelines/agents/v2-windows.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/agents/v2-windows.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by vtbassmatt** [comment]
@andyjlewis I think this GitHub issue got misrouted. I don't see anything in the v2-windows topic that talks about deployment group install scripts. There's a topic [here](https://docs.microsoft.com/en-us/vsts/pipelines/release/deployment-groups/?view=vsts#deploy-agents-to-a-deployment-group) that sounds more relevant. How do we move bugs?

**Comment by andyjlewis** [comment]
I don't know if we can move the issue, but heads up to: @alexhomer1 so he can take a look.

**Comment by alexhomer1** [comment]
Thank you for your feedback. I have passed this on to the product team for advice.

**Comment by alexhomer1** [comment]
The product team advises that you can customize the script; for example, this creates a directory under the system drive and sets up the agent there:

{mkdir $env:SystemDrive\'vstsagent'}; cd $env:SystemDrive\'vstsagent'
