### ISSUE TITLE
Outdated Upgrade Steps

### ISSUE THREAD

**Issue by rkralston** [MicrosoftDocs/vsts-docs#1285]
The Upgrade steps all reference upgrading to 2015. Are these relevant for 2018?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: af46d9cb-1b1e-bfe1-0f19-c15aca283c95
* Version Independent ID: 284bd5a1-5ddf-801f-aaa1-502928037110
* Content: [Welcome to tfs-docs!](https://docs.microsoft.com/en-us/tfs/server/?view=vsts)
* Content Source: [docs/server/index.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/server/index.md)
* Product: **devops-server**
* GitHub Login: @erickson-doug
* Microsoft Alias: **douge**

**Comment by elbatk** [comment]
Sorry for the delay, but these should be up to date. I'm going to close this issue but if you find areas that need updating, please reach out!
