### ISSUE TITLE
Update Board Columns 

### ISSUE THREAD

**Issue by MarcoDeJesus** [MicrosoftDocs/vsts-docs#1286]
This of course might be in a different document but no mentioned here. I struggled finding a way of why my bug didn's show up. It was because I missed to update the Board Columns in the setting section. This won't happen for the Definition of Done default columns but it will for those updated ones. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c85fc76f-6cf3-2b74-0d50-cd8500b56679
* Version Independent ID: 84fce3ee-5f76-6529-8e97-1ccf0ab68344
* Content: [Resolve backlog issues](https://docs.microsoft.com/en-us/vsts/work/backlogs/resolve-backlog-reorder-issues?view=vsts#nested)
* Content Source: [docs/work/backlogs/resolve-backlog-reorder-issues.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/work/backlogs/resolve-backlog-reorder-issues.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by evangeline-liu** [comment]
Hi MarcoDeJesus! Would it help if the documents were more clear about how to get bugs to show up on boards?
