### ISSUE TITLE
params missing in GET uri

### ISSUE THREAD

**Issue by A-AontwSR** [MicrosoftDocs/vsts-docs#1287]
The GET of a list of approvals does not show all request parameters, almost all query params are missing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 664c74de-5612-9eb4-06f8-dc95c304c2fe
* Version Independent ID: ff6be0b3-1619-7813-27c4-58d00094f9e9
* Content: [Release approvals](https://docs.microsoft.com/en-us/vsts/integrate/previous-apis/rm/approvals?view=vsts)
* Content Source: [docs/integrate/previous-apis/rm/approvals.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/integrate/previous-apis/rm/approvals.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by elbatk** [comment]
hey @A-AontwSR , duplicated this issue over in the [vsts-rest-api-specs repo](https://github.com/MicrosoftDocs/vsts-rest-api-specs/issues/65) so that the API team could take a better look!

**Comment by elbatk** [comment]
It looks like the linked item was solved here so marking this as completed, thank you!
