### ISSUE TITLE
Petty Charges

### ISSUE THREAD

**Issue by sscoleman** [MicrosoftDocs/vsts-docs#1288]
Charging customers for running builds on their own hardware is petty.  You over charge for ASE too.  It should be free. I can't understand charging for a service that binds other services together. If ASE was free my company would have double the infra in Azure. So we use AWS instead.  I suggest you take a look at this and realize that AWS has many build and deployment options. They don't have gotcha fees hidden in their services.  You don't need to nickel and dime customers who are probably already spending a lot on Azure.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cb26f633-6068-0e2a-0b8d-e97f8acdbb09
* Version Independent ID: 449ffa66-9707-c87a-6128-57beeb22f0fc
* Content: [CI/CD Concurrent Jobs in Team Services](https://docs.microsoft.com/en-us/vsts/pipelines/licensing/concurrent-jobs-vsts?view=vsts)
* Content Source: [docs/pipelines/licensing/concurrent-jobs-vsts.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/licensing/concurrent-jobs-vsts.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by eriawan** [comment]
@sscoleman 

This issue is not within the scope for documentation feedback. It is more of a feature request, so it should be in VSTS' uservoice: https://visualstudio.uservoice.com/forums/330519-visual-studio-team-services

cc @steved0x

**Comment by steved0x** [comment]
@sscoleman I will pas this directly onto the team, but you can also file it in Developer Communities here:

https://developercommunity.visualstudio.com/spaces/21/index.html

Developer communities is more for filing defects and issues with a product, and UserVoice for feature requests. I can see how `Petty charges` could be considered both a feature request (less petty charges) or a defect (I would say too many petty charges, but any petty charges sounds like a defect), in this case I think Developer Communities would be the better place. Of course it couldn't hurt to put it in both and get maximum visibility, but it will be the same folks looking at both.

I'm sorry that this issue is causing you trouble, and I'm passing this along right now.

@alexhomer1 While Andy is out, could you forward this along to the right CI/CD PM?

**Comment by cellvia** [comment]
could someone provide the reasoning for charging for self-hosted agent job concurrency?  the whole point of self-hosting is to avoid paying someone else.  is this purely a money grab as it seems?

**Comment by alexhomer1** [comment]
Thank you for your feedback. I have passed this on to the product team for consideration.

**Comment by ElvenSpellmaker** [comment]
I'd like to add my two-penn'orth here also.

The new Concurrent Charges have been sneaked in without _any_ communication to us that this was ever going to be a thing.

We have enough VSTS Enterprise Licences (I believe) to not be affected, _except_ we've been capped to one build for no reason, and the link given to us to be able to change this, leads to a blank page with a blue background:
![image](https://user-images.githubusercontent.com/2286713/42971121-1bb810ee-8ba3-11e8-8028-5f1f55ee9476.png)

**Comment by lovakumar** [comment]
@ElvenSpellmaker To debug further about blank page with a blue background screen can you please send browser window console logs/errors that you see when this happens.

**Comment by lovakumar** [comment]
@ElvenSpellmaker thanks for the screenshot. We have reproduced a similar issue and just to confirm what we have reproduced is same as what you were facing, can you please share the following.

Browse to https://<your vsts accountname>.visualstudio.com/_diagnostics
click Script debug mode enabled
Browse to https://<your vsts accountname>.visualstudio.com/_admin
On the bottom toolbar click settings (on the right bottom corner)
Turn off bundling
Browse to https://<your vsts accountname>.visualstudio.com/_admin
Press F12 to capture console logs
Browse to https://<your vsts accountname>.visualstudio.com/_admin/_buildQueue

At this point console will show some 404 urls that are failing to download some scripts. Can you please share those urls.

**Comment by ElvenSpellmaker** [comment]
Hey @lovakumar,

I followed the first step and enabled the 'Script debug mode' which led me to a blank blue page again. Navigating back to `_diagnostics` showed me the page saying it's enabled.

I then browsed to `_admin` but there's no bottom toolbar present (I'm on the new preview theme `New Navigation`, if that helps in any way?)

**Comment by lovakumar** [comment]
@ElvenSpellmaker this error is matching the issue that we have reproduced. We have tried some change in the back end to unblock you. Can you please try browsing to _admin/_buildQueue and let us know if it's working for you.

**Comment by ElvenSpellmaker** [comment]
Hey @lovakumar, I can now see the page, many thanks!

![image](https://user-images.githubusercontent.com/2286713/43196167-02b1f05a-8fff-11e8-9b90-95f506563458.png)

It now also seems we can run concurrent builds again, and so I'm hoping the fix has fixed that too:
![image](https://user-images.githubusercontent.com/2286713/43196555-40706a1a-9000-11e8-878d-a158667642ac.png)

Thanks again!

**Comment by cellvia** [comment]
um, how is this resolved?  this was hijacked by some other issue.  you still havent explained the petty charges.

**Comment by andyjlewis** [comment]
This is where we track problems with the docs. Please raise product suggestions here: https://developercommunity.visualstudio.com/spaces/8/index.html
