### ISSUE TITLE
Delete Account Button Moved

### ISSUE THREAD

**Issue by veebz** [MicrosoftDocs/vsts-docs#1291]
The Delete Account action is now part of the toolbar at the top right of the page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 75b82830-ca76-a981-163f-849cf588543f
* Version Independent ID: 06d3db8e-29cc-119c-c7d6-e45a2b0ee9fc
* Content: [Delete your VSTS account](https://docs.microsoft.com/en-us/vsts/organizations/accounts/delete-your-vsts-account?view=vsts)
* Content Source: [docs/organizations/accounts/delete-your-vsts-account.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/accounts/delete-your-vsts-account.md)
* Product: **devops**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
@veebz thank you for your feedback! I've created a work item for this update.
