### ISSUE TITLE
Bad filename

### ISSUE THREAD

**Issue by syonekura** [MicrosoftDocs/vsts-docs#1292]
"Create a file named vsts-ci.yml in the root of your repository." should be "Create a file named .vsts-ci.yml in the root of your repository." I spent several hours scratching my head while wondering why VSTS didn't recognize my build file -_-

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2ca42420-9324-1988-16bd-501be69e278d
* Version Independent ID: 400c0122-a0cc-bb52-b6cc-8aa93ff2c47a
* Content: [Python](https://docs.microsoft.com/en-us/vsts/pipelines/languages/python?view=vsts&tabs=yaml)
* Content Source: [docs/pipelines/languages/python.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/languages/python.md)
* Product: **devops**
* GitHub Login: @erickson-doug
* Microsoft Alias: **dastahel**

**Comment by steved0x** [comment]
@syonekura Sorry that you ran into trouble, I am fixing this now, thank you for letting us know.
