### ISSUE TITLE
404 links to security REST APIs

### ISSUE THREAD

**Issue by weikanglim** [MicrosoftDocs/vsts-docs#1294]
The navigation links in [security toc.yml](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/security/toc.yml) that point to the broken two security links:

- https://docs.microsoft.com/en-us/rest/api/vsts/organizations/security/permissions
- https://docs.microsoft.com/en-us/rest/api/vsts/organizations/security/

Should they be pointing to https://docs.microsoft.com/en-us/rest/api/vsts/security/?

**Comment by eriawan** [comment]
@weikanglim 
You're right. I'll submit a PR on this.

**Comment by eriawan** [comment]
Ah, never mind. The page of https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/security/toc.yml is no longer available in live branch.

Looks like it has been updated, or it has been moved.

**Comment by steved0x** [comment]
@weikanglim @eriawan Thanks for letting us know. Let me assign this one to the owner of that area as I'm not sure.

**Comment by KathrynEE** [comment]
@weikanglim - Thank you for the correction. I'm updating the broken links now.
