### ISSUE TITLE
How do i generate the import.json if the prepare fails due to import size?

### ISSUE THREAD

**Issue by PonmurughuS** [MicrosoftDocs/vsts-docs#1296]
How do I generate the import.json if the prepare fails due to import size? 
It is been mentioned in the troubleshooting document to delete some customizations to go through the step.
Does it mean the customization removals is to only generate import. Json for Azure SQL VM method and that the delete doesn’t have any significant impact on the migration?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a35b397-3fe8-122e-042e-280326f88a38
* Version Independent ID: 3e0f0afc-abeb-01be-d767-813cd6ad78db
* Content: [Migration import from TFS to Visual Studio Team Services (VSTS)](https://docs.microsoft.com/en-us/vsts/articles/migration-import?utm_source=ms&utm_medium=guide&utm_campaign=vstsdataimportguide&view=vsts)
* Content Source: [docs/articles/migration-import.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/articles/migration-import.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by roofers** [comment]
Hi @PonmurughuS - It's hard to tell what problem you're running into without seeing the TfsMigrator.log file. Can you reach out to vstsdataimport@microsoft.com and attach the latest log file from your prepare run? I'll take a look and help get you back on track.

**Comment by PonmurughuS** [comment]
I am asking for additional documentation to run the Azure SQL VM method of migration.
To be precise when I get the large DB table size issues how do I generate import.json for migration.
Error screen attached.
![start-tfs-migrator-validate-using-command-line](https://user-images.githubusercontent.com/17600131/42721293-130a228a-8756-11e8-818a-380a0a177a36.png)

**Comment by roofers** [comment]
@PonmurughuS - Importing a collection via the SQL IaaS method is detailed [here](https://docs.microsoft.com/en-us/vsts/articles/migration-import?view=vsts#importing-large-collections). How to take a generated import.json and set it up to connect to the VM is covered in the documentation [here](https://docs.microsoft.com/en-us/vsts/articles/migration-import?view=vsts#configure-the-import-specification-file-to-target-the-vm).

It looks like you still have process validation errors that will need to be corrected before you can run prepare. Details on how to fix process validation issues can be found [here](https://docs.microsoft.com/en-us/vsts/articles/migration-processtemplates?view=vsts#dealing-with-process-errors). If you have any questions on how to resolve an error, feel free to reach out to vstsdataimport@microsoft.com.

**Comment by elbatk** [comment]
We haven't heard from you in a while @PonmurughuS , so we're going to close this issue, thank you!
