### ISSUE TITLE
How do you add more?!?  If we have to pay more, we pay more, but seriously there's no clear way to do this!

### ISSUE THREAD

**Issue by jholovacs** [MicrosoftDocs/vsts-docs#1297]
You're holding my development hostage here!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5c2c2355-60a5-d53f-2c72-8f032c1b8cf2
* Version Independent ID: 711bf22d-99c9-51b2-382c-e095bdb2c37f
* Content: [Resource limits & constraints - VSTS](https://docs.microsoft.com/en-us/vsts/integrate/concepts/rate-limits?view=vsts)
* Content Source: [docs/integrate/concepts/rate-limits.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/integrate/concepts/rate-limits.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by shaneholder** [comment]
It would be nice to have a way to address the rate limits.  Currently we're importing projects from on-prem TFS using the vstssyncmigrator and hit rate limits that cause the imports to take much longer than they should.  Is there a way to get at least get a temporary increase in rate limits?

**Comment by danhellem** [comment]
Hello Shane, no sorry, we don't typically increase the rates. Is there a reason you are not using the data import tool to do your migration?

**Comment by craigdUSI** [comment]
We migrated to Azure DevOps over the weekend and are running into usage delays when annotating files which have very long histories.  I would agree the limits should be flexible, even at a cost.

**Comment by jderose9** [comment]
Same as others have said. The official tool is inflexible (I need multiple TFS 2015 projects > single azure devops services project). With the service limits as they are, migrating 30k work items with vstssyncmigrator will take a week.

**Comment by janissimsons** [comment]
This is insane, you [microsoft] clearly recommend to use vsts sync migrator tool, and yet you provide NO WAY to bypass the bandwidth limiter. 
There should be a way to temporarily exempt a user from these limits, so it's possible to migrate as quickly as possible.
Right now, migrating 9k items takes over 20 hours. In reality it should take less than 1 hour without the limit.
