### ISSUE TITLE
HTML anchors don't work with link to other wiki docs

### ISSUE THREAD

**Issue by thisispaulsmith** [MicrosoftDocs/vsts-docs#1298]
Adding into a wiki page
```
<a href="/Otherpage">Other page</a>
```

 doesn't work the same as the mark down equivalent.
```
[Other Page](/OtherPage)
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fa622358-f5bb-1f5c-177a-081a37b6acef
* Version Independent ID: 72f7fd16-a822-66c8-3a34-8905645ce5f2
* Content: [Syntax usage for Markdown files, widgets, wikis, and pull requests - VSTS & TFS](https://docs.microsoft.com/en-us/vsts/project/wiki/markdown-guidance?view=vsts)
* Content Source: [docs/project/wiki/markdown-guidance.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/project/wiki/markdown-guidance.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by StingyJack** [comment]
I think the anchor has to be lowercased, like it does for some of the other link types.
```
 [Other Page](/otherpage) 
```

**Comment by KathrynEE** [comment]
@thisispaulsmith, @StingyJack - Thank you for your query and comments. I believe that StingyJack is correct. Please check the casing of your links.
