### ISSUE TITLE
Build Definition using .vsts-ci.yml file does not have an Options tab. No clear way to Allow scripts to access OAuth token.

### ISSUE THREAD

**Issue by 3choBoomer** [MicrosoftDocs/vsts-docs#1299]
Need information on how to enable the option for a yml based build pipeline to Allow scripts to access OAuth token.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0fa5a83c-70fd-6925-a8c8-256b21c21a2e
* Version Independent ID: 75f4a136-7245-7878-2953-6b68272fe4ec
* Content: [Build pipeline options](https://docs.microsoft.com/en-us/vsts/pipelines/build/options?view=vsts)
* Content Source: [docs/pipelines/build/options.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/build/options.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by vtbassmatt** [comment]
Short term, doc is here: https://github.com/Microsoft/vsts-agent/blob/master/docs/preview/yamlgettingstarted-token.md

Long term, I will get this moved into our official docs.
