### ISSUE TITLE
Permissions documentation is out of date

### ISSUE THREAD

**Issue by VerdonTrigance** [MicrosoftDocs/vsts-docs#13]
https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/build-release/actions/agents/_shared/v2/prepare-permissions.md
There is no "Deployment group (read, manage)" permission in PAT editor page. Please update this page.

**Comment by erickson-doug** [comment]
@VerdonTrigance  we're working on significant updates for the permissions documentation to go live by the end of next week. I'll forward this feedback onto the permissions writer. Thank you, and sorry for the delayed response!
