### ISSUE TITLE
Do that now button has the wrong link

### ISSUE THREAD

**Issue by emarion0** [MicrosoftDocs/vsts-docs#1301]
"do that now" button is not about orgs

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 715eca62-8a31-4163-c27b-f5e71d781982
* Version Independent ID: 06dc711f-1946-29e9-aece-75af903da09b
* Content: [Customize the workflow of an inherited process - VSTS](https://docs.microsoft.com/en-us/vsts/organizations/settings/work/customize-process-workflow?view=vsts#feedback)
* Content Source: [docs/organizations/settings/work/customize-process-workflow.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/settings/work/customize-process-workflow.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@emarion0 - Thank you for the correction. I'm updating the affected articles now.
