### ISSUE TITLE
Creating tag without description from web portal

### ISSUE THREAD

**Issue by Anders-Frey** [MicrosoftDocs/vsts-docs#1310]
The Description field in the create tag dialogue seems to be mandatory. What is the reasoning behind this, and is there any way to create a tag from the web portal without a description?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8eb20e31-fc65-913d-f4a6-61318f079224
* Version Independent ID: 0c4960b1-d639-7452-a2e7-08c59934c3b3
* Content: [Working with Git tags](https://docs.microsoft.com/en-us/vsts/git/how-to/git-tags?tabs=vsts-tfs-web-portal&view=vsts#create-tag)
* Content Source: [docs/git/how-to/git-tags.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/git/how-to/git-tags.md)
* Product: **devops**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
@Anders-Frey I spoke with Sandeep (for some reason he was unable to reply directly here), he said: 

`Lightweight tags are considered temporary tags that developers prefer to create in their IDEs. Mostly the intent is to push annotated tags to remote branch therefore we provide 1st class experience to add annotated tags in VSTS IDE. Users can continue to create lightweight tags using cmd line or IDE and push it remotely.`

I'm going to update this article to make this more clear, and I'm closing this issue. 

If creating lightweight tags in the web portal is something you think VSTS should support, you can file a request here: https://developercommunity.visualstudio.com/spaces/21/index.html and continue the discussion over there.

Thank you for your feedback.

Steve

**Comment by Anders-Frey** [comment]
Hi Steve and thanks for your answers. I appreciate the decision to only use annotated tags in the web portal and that is not a problem for my companys specific scenario. Our problem is that the description field is mandatory.

We've just upgraded from TFS 2017 to TFS 2018 and in the former version, the description field was not mandatory. If you created a tag without a description it was created as an annotated tag which worked fine for our need.

Now we have to fill the description field with non-information which is an (admittedly minor) inconvenience.

Br Anders from mobile

**Comment by jnm2** [comment]
> Now we have to fill the description field with non-information which is an (admittedly minor) inconvenience.

Seconded. Anything I have to say about the tag is already in the tag's name. It would be cool for the description to stay optional but change the accept button to say "Create lightweight tag." Maybe show a warning message beneath explaining that an annotated tag can only be created if the description is filled out?
