### ISSUE TITLE
Not showing option to make public project.

### ISSUE THREAD

**Issue by ravinderjangra** [MicrosoftDocs/vsts-docs#1313]
Now shoring option to select private/project. Also in existing project there is only private security option, not showing public option there.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7ee33161-f67e-b5df-77ba-6005ab19ddda
* Version Independent ID: 695c87c3-067f-175c-38d1-9bd6c777a605
* Content: [Create a public project - VSTS Public Project](https://docs.microsoft.com/en-us/vsts/organizations/public/create-public-project?view=vsts&tabs=vertical)
* Content Source: [docs/organizations/public/create-public-project.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/public/create-public-project.md)
* Product: **devops-alm**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@ravinderjangra - Hi. If you don't see the option to create a Public Project after you set the Anonymous Access policy to ON, please reach out to our [Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html) or our [Support](https://www.visualstudio.com/team-services/support/) page.
