### ISSUE TITLE
Unhelpful help

### ISSUE THREAD

**Issue by brfenske** [MicrosoftDocs/vsts-docs#1314]
"To resolve this issue, ask the subscription administrator to configure an Admin Access role for your identity." is useless if I am the subscription administrator and don't know how to do this.  Why not include a link to a page that explains how to configure admin access for someone?  I'm stuck.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5093b8d4-43df-12c3-591d-43e174e630cd
* Version Independent ID: 4a9bf702-1b28-33ef-9a26-fcf9dadaa7c2
* Content: [Troubleshooting Azure Resource Manager service connections in VSTS and TFS](https://docs.microsoft.com/en-us/vsts/pipelines/release/azure-rm-endpoint?view=vsts#notauthtoadd)
* Content Source: [docs/pipelines/release/azure-rm-endpoint.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/release/azure-rm-endpoint.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment]
Thank you for your feedback. I will update the topic to include your recommendations.
