### ISSUE TITLE
Execute tests in parallel on deployment groups

### ISSUE THREAD

**Issue by MoiMoiDG** [MicrosoftDocs/vsts-docs#1318]
Hi,

there is something which is probably missing in this documentation.
Let us assume that one has an application to be tested and written 1000 functional tests for it.
One may want to distribute the artifacts to several machines to parallelize the test execution. This is supported by the TFS 2018.2 release pipelines only for an agent phase but not for a deployment group phase. The latter does not aggregate the test results. Is it something which will be added or is it not the intended use of a deployment group phase? In any case, I could not find any information about that here. 

Thanks in advance!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28003c9d-f926-bdce-e830-8676b1979175
* Version Independent ID: 33a4dfdb-04cd-1b78-f5f3-f193b2a3fcfe
* Content: [Set up environments to run continuous tests with your builds - test automation tools](https://docs.microsoft.com/en-us/vsts/pipelines/test/set-up-continuous-test-environments-builds?view=vsts)
* Content Source: [docs/pipelines/test/set-up-continuous-test-environments-builds.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/test/set-up-continuous-test-environments-builds.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment]
Thank you for your feedback. I have passed this on to the product team for advice.

**Comment by PBoraMSFT** [comment]
@MoiMoiDG Distributing on deployment groups is not supported currently. We recommend using agent pools for all testing needs. If this is a key requirement for you, please file an enhancement on https://github.com/Microsoft/vsts-tasks/ and info on why agent pools cannot be used.
