### ISSUE TITLE
Video link broken

### ISSUE THREAD

**Issue by dalee-bis** [MicrosoftDocs/vsts-docs#1319]
The video at the bottom of the page has been removed from YouTube by the user.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe168fc3-2ed2-b3e6-ce30-cac721165ceb
* Version Independent ID: 8d63fbd7-12c4-9a94-92f6-969e7eb41037
* Content: [Git branching guidance](https://docs.microsoft.com/en-us/vsts/git/concepts/git-branching-guidance?view=vsts#keep-your-branch-strategy-simple)
* Content Source: [docs/git/concepts/git-branching-guidance.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/git/concepts/git-branching-guidance.md)
* Product: **devops**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
@dalee-bis Thanks for letting us know, I'll get this fixed up.

**Comment by steved0x** [comment]
@dalee-bis I just removed the broken video, and as soon as we have a replacement I'll add it back in. Thanks for letting us know.
