### ISSUE TITLE
Group Rules missing feature

### ISSUE THREAD

**Issue by msdnguy** [MicrosoftDocs/vsts-docs#1321]
Hi, I don't see the option for adding extensions.  Is this only available if you have purchased the extensions?  If so could you document this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba38644a-fe6c-e644-2f35-2cf6fa092650
* Version Independent ID: 7d18b423-923f-d9c4-e451-ab7f8ff27bb1
* Content: [Assign access levels and extensions to users by group membership](https://docs.microsoft.com/en-us/vsts/organizations/accounts/assign-access-levels-and-extensions-by-group-membership?view=vsts)
* Content Source: [docs/organizations/accounts/assign-access-levels-and-extensions-by-group-membership.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/accounts/assign-access-levels-and-extensions-by-group-membership.md)
* Product: **devops**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @msdnguy , thanks for your comment. To assign an extension to a user (and, consequently, a group), an administrator must have first installed the extension on the account. Here's a link to that information, which I'll be adding a link to within this topic. Thanks again. https://docs.microsoft.com/en-us/vsts/marketplace/install-paid-vsts-extension?view=vsts
