### ISSUE TITLE
How to edit label description?

### ISSUE THREAD

**Issue by ahmadyo** [MicrosoftDocs/vsts-docs#1322]
How to edit label description?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c9acb068-8187-9dc7-8ed8-ee6115e36141
* Version Independent ID: 112c018f-4dcc-2268-1f6f-536d22835b0a
* Content: [Label sources](https://docs.microsoft.com/en-us/vsts/pipelines/build/_shared/label-sources?view=vsts)
* Content Source: [docs/pipelines/build/_shared/label-sources.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/build/_shared/label-sources.md)
* Product: **devops**
* GitHub Login: @erickson-doug
* Microsoft Alias: **douge**

**Comment by andyjlewis** [comment]
Thanks for your question. This snippet that you commented on is not meant to be displayed independently, so last week we fixed the issue and it is no longer posted. A couple of resources I hope might address your question:

https://docs.microsoft.com/en-us/vsts/pipelines/build/repository
https://docs.microsoft.com/en-us/vsts/tfvc/use-labels-take-snapshot-your-files
https://docs.microsoft.com/en-us/vsts/git/how-to/git-tags
