### ISSUE TITLE
Control configuration documentation missing or out-of-date

### ISSUE THREAD

**Issue by pabrams** [MicrosoftDocs/vsts-docs#1323]
Edit:  Answered my own question, so changed title due to the missing documentation.  Below is an example, but I think the other controls' docs are similarly lacking. 

See https://stackoverflow.com/questions/51370249/how-do-i-get-vss-sdk-treeview-to-collapse-by-default

**Comment by pabrams** [comment]
I finally figured this out.  There's an undocumented (afaict) property called 'treeLevel' which I can set to 0.  See SO link for code.  Can you please add some documentation, or tell me where it is?  I can't find it.

**Comment by steved0x** [comment]
@pabrams The issues in this GitHub repo are for documentation feedback. Can you let me know what article this feedback goes with, and I'll assign it to the right author for review. It sounds like there is a property we need to document. 

Thank you for your feedback.

**Comment by pabrams** [comment]
Examples are linked from the SO question,  but the problem is much bigger than just one missing property.  I dont think ANY properties are documented fir these controls.  We can see what some of them are by looking at the sample code.  If you try to document that one example, i think you will see what i mean.

**Comment by steved0x** [comment]
@pabrams I have assigned this to the writer for that area, thanks again for the feedback.

**Comment by elbatk** [comment]
Hi @pabrams , I know it's been a while for this one! Thanks for putting in the work you've put in. We are switching to autogenerate the reference for these clients, this will hopefully clear all of this up! Closing this as a docs issue as I think we're making the right approach here, thanks again!
