### ISSUE TITLE
Possible typo

### ISSUE THREAD

**Issue by AndrewEllinor** [MicrosoftDocs/vsts-docs#1324]
In the first paragraph " to automate the creation of infrastructure and deployment of a new. Successive environments"
Should there be a word after new?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 895ed016-6ddc-3458-db9e-ebbedf218982
* Version Independent ID: 36e017f5-b012-fcec-6906-1966f3a97cb4
* Content: [What is Continuous Delivery? - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/what-is-continuous-delivery)
* Content Source: [https://mseng.visualstudio.com/DefaultCollection/TechnicalContent/_git/devops-learn-pr?path=%2fdocs%2fwhat-is-continuous-delivery.md&version=GBlive&_a=contents](https://mseng.visualstudio.com/DefaultCollection/TechnicalContent/_git/devops-learn-pr?path=%2fdocs%2fwhat-is-continuous-delivery.md&version=GBlive&_a=contents)
* Product: **devops**
* Git Login: **samgu**
* Microsoft Alias: **samgu**

**Comment by steved0x** [comment]
@mlearned What is the missing word here and I will get it fixed up.

@AndrewEllinor Thanks for letting us know, it looks like there is a missing word, I'll get that fixed up for you.

**Comment by mlearned** [comment]
I'd say something like "new updates to applications."  however @steved0x  i'll spin up a thread with Sam Gu to see what he wants to do.

**Comment by steved0x** [comment]
@mlearned Thank you

@AndrewEllinor I chatted offline with @mlearned and I have checked in a fix, replacing `a new` with `applications1 and this should be live shortly. Thanks for letting us know about the typo.
