### ISSUE TITLE
Please pop a warning before committing when there are no staged changes

### ISSUE THREAD

**Issue by ericrrichards** [MicrosoftDocs/vsts-docs#1325]
It would be very helpful if there was some way to force the git plugin to make you confirm before committing changes, when you haven't staged files.  I run into situations all the time where I tweak some local config file that should not be committed, and then make some changes to other files, and forget to stage the particular files that I want committed, then hit Commit All.  Then I have to go checkout the previous clean version of the mistakenly committed file, and commit again to revert it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9654b64d-80e5-a28e-30d8-240b02bbe175
* Version Independent ID: c4f3eb8e-e203-7452-ba96-b0990107339a
* Content: [Save your changes with Git commits](https://docs.microsoft.com/en-us/vsts/git/tutorial/commits?view=vsts&tabs=visual-studio)
* Content Source: [docs/git/tutorial/commits.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/git/tutorial/commits.md)
* Product: **devops**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
@ericrrichards Thank you for your feedback. The issues in this repo are for content feedback, and this looks like a product feedback. For product feedback, including feature requests, please file an issue here: https://developercommunity.visualstudio.com/spaces/21/index.html

Thank you.
