### ISSUE TITLE
"Task Tool Installers" don't need to be manually enabled anymore

### ISSUE THREAD

**Issue by samuelbcollie** [MicrosoftDocs/vsts-docs#1327]
I think this page needs to be updated. This feature is now enable for everyone and doesn't need to be enabled as a preview feature according to: https://docs.microsoft.com/en-us/vsts/project/navigation/preview-features?view=vsts

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8098f527-ebdf-60d5-3989-5228b7a207c1
* Version Independent ID: ce27c817-9599-00ef-5af2-3ac1dbad8dc6
* Content: [Build and Release Tasks in VSTS and TFS](https://docs.microsoft.com/en-us/vsts/pipelines/process/tasks?view=vsts#tool-installers)
* Content Source: [docs/pipelines/process/tasks.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/tasks.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by Silic0nS0ldier** [comment]
Can confirm this is out of preview. Doesn't appear in the user nor organisation preview feature lists and I just used the `NuGetToolInstaller` with success.

**Comment by snnn** [comment]
The document should be updated.

**Comment by andyjlewis** [comment]
Thank you for the heads up. Apologies for the very late response to this issue. I've posted it to our backlog.

**Comment by MisinformedDNA** [comment]
It's still marked as preview. Very confusing.
