### ISSUE TITLE
Git command prompt within team explorer

### ISSUE THREAD

**Issue by hiraldesai** [MicrosoftDocs/vsts-docs#1328]
Is there a way to get git command prompt working within team explorer itself? Right now I have to switch apps to do it, it'd be nice to just have a Git shell within VS itself.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be5d8ba0-8663-725f-b9da-34f7b47dbe04
* Version Independent ID: 7e9e5c80-4e3d-ed58-07d6-bd72312b1e3d
* Content: [Navigate within the Visual Studio Team Explorer pane - VSTS & TFS](https://docs.microsoft.com/en-us/vsts/user-guide/work-team-explorer?view=vsts)
* Content Source: [docs/user-guide/work-team-explorer.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/user-guide/work-team-explorer.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by steved0x** [comment]
@hiraldesai Do you mean something like this?

https://jessehouwing.net/use-git-directly-from-visual-studio/

I'm not sure if there is a built-in way but I can find out.

**Comment by hiraldesai** [comment]
OMG - I had no idea you could do that! Thank you for this information!
