### ISSUE TITLE
How to set default columns to show in backlog view

### ISSUE THREAD

**Issue by MikaelUmaN** [MicrosoftDocs/vsts-docs#1333]
This does not show how I can set the default columns to be shown in the backlog view. Right now I see for example "value area" which we do not want to see. I just want to select what we want to see, similar to "queries". No idea why the backlog view isn't just generalized to be a query that you can modify?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f3fd2a68-d9ad-0966-bbc4-c70a23566ff8
* Version Independent ID: f66ea1ca-6c7a-8f6c-9be7-7b386662fa22
* Content: [Add or remove columns, change column width, or sort order - VSTS & TFS](https://docs.microsoft.com/en-us/vsts/work/backlogs/set-column-options?view=vsts)
* Content Source: [docs/work/backlogs/set-column-options.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/work/backlogs/set-column-options.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@MikaelUmaN - Thank you for your inqury. Column settings can be set by each user and the system remembers their settings per backlog. 

If you use an on-premises TFS, you can set the default columns as documented here: [ProcessConfiguration XML Reference](https://docs.microsoft.com/en-us/vsts/work/customize/reference/process-configuration-xml-element?toc=%2Fvsts%2Fwork%2Fcustomize%2Ftoc.json&bc=%2Fvsts%2Fwork%2Fcustomize%2Fbreadcrumb%2Ftoc.json&view=vsts#columns).  This feature isn't supported on VSTS.

As for using a modifiable query for the backlog, you may want to add this idea to our [Uservoice](https://visualstudio.uservoice.com/forums/330519-team-services) page.
