### ISSUE TITLE
MD anchors probably need a note about number of pound signs

### ISSUE THREAD

**Issue by StingyJack** [MicrosoftDocs/vsts-docs#1334]
A markdown heading will always be anchored with a single leading pound sign, not however many pound signs are present in the heading. 

So `### My Heading` will be represented in a link context as `#my-heading`. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fa622358-f5bb-1f5c-177a-081a37b6acef
* Version Independent ID: 72f7fd16-a822-66c8-3a34-8905645ce5f2
* Content: [Syntax usage for Markdown files, widgets, wikis, and pull requests - VSTS & TFS](https://docs.microsoft.com/en-us/vsts/project/wiki/markdown-guidance?view=vsts#links)
* Content Source: [docs/project/wiki/markdown-guidance.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/project/wiki/markdown-guidance.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by steved0x** [comment]
@StingyJack Thank you for the feedback. It looks like that matches what we have in the documentation here:

![image](https://user-images.githubusercontent.com/1580889/42891844-4fca2104-8a7e-11e8-92dd-b9a169927ac3.png)

I'm assigning this to the author for review, can you provide ay additional information about what part we need to update or clarify? To explicitly state that there is only one `#` character before an anchor link?

Thank you.

**Comment by StingyJack** [comment]
> To explicitly state that there is only one # character before an anchor link?

Yes please. I cant be the only one who has copied and pasted a heading in order to make a link or TOC  entry and not realized why it wasn't working after lowercasing and trading spaces for dashes..
