### ISSUE TITLE
Some extensibility points are missing in the new UI preview

### ISSUE THREAD

**Issue by marszall87** [MicrosoftDocs/vsts-docs#1335]
Looks like ms.vss-work-web.sprint-board-pivot-filter-menu and ms.vss-work-web.backlog-board-pivot-filter-menu are no longer working in the new UI. Unless it's a bug, it should be documented somehow.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eab519d8-dc41-91de-437a-4469edefddab
* Version Independent ID: edc98ac8-a89a-a79a-d75c-1435870a00d2
* Content: [Developing extensions for VSTS vertical web navigation](https://docs.microsoft.com/en-us/vsts/extend/develop/web-navigation?view=vsts)
* Content Source: [docs/extend/develop/web-navigation.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/extend/develop/web-navigation.md)
* Product: **devops**
* GitHub Login: @willsmythe
* Microsoft Alias: **wismythe**

**Comment by steved0x** [comment]
@elbatk Can you take a look at this one and reassign if needed? Thank you.

**Comment by elbatk** [comment]
Thanks @marszall87 and @steved0x , assigning to @willsmythe so he can take a look

**Comment by marszall87** [comment]
Actually I got a response from the dev team and it was a regression. It works after a fix, however it behaves somewhat differently - perhaps worth a note in docs.

**Comment by pratyushoak** [comment]
The 'ms.vss-work-web.iteration-backlog-tabs' extension point does not seem to be working with the new UI either. @marszall87  Can you please share the suggested fix? It may work for the iteration backlogs tab too.

**Comment by elbatk** [comment]
Looks like we're all solved here, thanks everyone!
