### ISSUE TITLE
How to view a specific branch

### ISSUE THREAD

**Issue by dkmiller** [MicrosoftDocs/vsts-docs#1337]
The documentation doesn't make clear whether or not it's possible to view the "wiki version" of a specific branch of the underlying repository. A typical wiki URL ends with &wikiVersion=GBwikiMaster, which makes it appear that you can set the branch, but substituting another branch doesn't actually show the contents of that branch.

Is this (viewing a different branch of the underlying repository in wiki form) possible?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 172eecd7-1a6b-30d0-96c0-fa6ae56b521c
* Version Independent ID: adc2c741-a41f-68d9-cdaf-dac696e68b9f
* Content: [Clone and update wiki content offline - VSTS & TFS](https://docs.microsoft.com/en-us/vsts/project/wiki/wiki-update-offline?view=vsts)
* Content Source: [docs/project/wiki/wiki-update-offline.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/project/wiki/wiki-update-offline.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by sandeepchadda** [comment]
You can publish multiple branches of Wiki when you publish markdown files from a code repository. This documentation shares more details on this front!! - https://docs.microsoft.com/en-us/vsts/project/wiki/wiki-select-unpublish-versions?view=vsts

**Comment by KathrynEE** [comment]
@dkmiller - Please see the comment provided by Sandeep above.

**Comment by dkmiller** [comment]
Thanks Kathryn and Sandeep. That answers my question.
