### ISSUE TITLE
Clean Target option for Blob operations

### ISSUE THREAD

**Issue by leshkinski** [MicrosoftDocs/vsts-docs#1339]
Would it be possible to add a feature where the target blob is removed if one already exists in the target container?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 622daa35-c6a1-dac3-17ee-3f9308fc60cd
* Version Independent ID: 2c28a59b-8ef5-d7ab-46a6-58748ec552f5
* Content: [VSTS and Team Foundation Server Build and Deploy - Azure File Copy](https://docs.microsoft.com/en-us/vsts/pipelines/tasks/deploy/azure-file-copy?view=vsts)
* Content Source: [docs/pipelines/tasks/deploy/azure-file-copy.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/deploy/azure-file-copy.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment]
Thank you for your feedback. Product suggestions and feature requests are best posted and upvoted on the UserVoice website at https://visualstudio.uservoice.com/forums/330519-team-services, where they are tracked by the product teams. Please post your suggestion there. Thank you.
