### ISSUE TITLE
Dead link for SQL collation information

### ISSUE THREAD

**Issue by skarai** [MicrosoftDocs/vsts-docs#1340]
Paragraph TFS 2013 additional information. Link for SQL collation settings point to https://docs.microsoft.com/en-us/install/sql-server/collation-requirements.md (404 error). Possible link were https://docs.microsoft.com/en-us/sql/relational-databases/collations/collation-and-unicode-support?view=sql-server-2017

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 641b37fc-f117-aca0-32f4-8ea9b73e9d71
* Version Independent ID: 211130c6-43b8-f47f-3589-cb4d2a330231
* Content: [Requirements and compatibility](https://docs.microsoft.com/en-us/tfs/server/requirements?view=vsts)
* Content Source: [docs/server/requirements.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/server/requirements.md)
* Product: **devops-server**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by elbatk** [comment]
Thanks @skarai ! Updating this and it should be live by end of day :)
