### ISSUE TITLE
Additional Web Deploy arguments

### ISSUE THREAD

**Issue by pkzOR** [MicrosoftDocs/vsts-docs#1341]
You state:
Additional Web Deploy arguments that will be applied when deploying the Azure Web App like,-disableLink:AppPoolExtension -disableLink:ContentExtension

but where is the complete list??

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be413593-c38c-d3bf-8450-627f3c4928b1
* Version Independent ID: 4d4e3115-5146-b715-7940-39a68186c871
* Content: [IIS Web App Deploy](https://docs.microsoft.com/en-us/vsts/pipelines/tasks/deploy/iis-web-app-deployment-on-machine-group?view=vsts)
* Content Source: [docs/pipelines/tasks/deploy/iis-web-app-deployment-on-machine-group.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/deploy/iis-web-app-deployment-on-machine-group.md)
* Product: **devops**
* GitHub Login: @erickson-doug
* Microsoft Alias: **dastahel**

**Comment by RoopeshNair** [comment]
@pkzOR - the task relies on -verb:sync to synchronize the destination with the source. You can use the MSDeploy.exe options that are supported with sync on an application site.  

For example, 
PS C:\Program Files (x86)\IIS\Microsoft Web Deploy V3> .\msdeploy.exe /?
Microsoft (R) Web Deployment Command Line Tool (MSDeploy.exe)
Version 7.1.1992.0
Copyright (c) Microsoft Corporation. All rights reserved.

MSDeploy.exe <-verb:<name>> <-source:<object>> [-dest:<object>] [args ...]

  -verb:<name>                   Action to perform (required).
  -source:<object>               The source object for the operation (required).
  -dest:<object>                 The destination object for the operation.
  -declareParam:<params>         Declares a parameter for synchronization.
  -setParam:<params>             Sets a parameter for synchronization.
  -disableLink:<name>            Disables the specified link extension(s).
  -enableLink:<name>             Enables the specified link extension(s).
  -disableRule:<name>            Disables the specified synchronization rule(s).
  -enableRule:<name>             Enables the specified synchronization rule(s).
...

**Comment by B4st13n** [comment]
Is it possible to disable to deployment of config file and keep the one on the server by using these Additional Web Deploy arguments ?

**Comment by er1k-peterson** [comment]
Is there no documentation for msdeploy?
