### ISSUE TITLE
Use Git with third-party client

### ISSUE THREAD

**Issue by J-Cake** [MicrosoftDocs/vsts-docs#1343]
I like to use Github Desktop, but am having difficulty signing in to my git page, is it possible to use GHD for Git management?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0cc40b8e-8a81-8213-d98e-a2c39d615f14
* Version Independent ID: 6d175def-aa48-ff2a-614f-4e9cf3324537
* Content: [Get started with Git and Visual Studio 2017](https://docs.microsoft.com/en-us/vsts/git/gitquickstart?view=vsts&tabs=visual-studio)
* Content Source: [docs/git/gitquickstart.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/git/gitquickstart.md)
* Product: **devops**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
@KlaussMC Yes you can use GitHub desktop, to clone and interact with your repo you need your account name and a Personal Access Token. To generate a personal access token, see [Authenticate access with personal access tokens for VSTS and TFS](https://docs.microsoft.com/en-us/vsts/organizations/accounts/use-personal-access-tokens-to-authenticate?view=vsts#create-personal-access-tokens-to-authenticate-access). Use your account name and this personal access token as your password in GitHub Desktop to access your repo in VSTS.
