### ISSUE TITLE
Build.SourceVersionMessage is undocumented

### ISSUE THREAD

**Issue by jmezach** [MicrosoftDocs/vsts-docs#1344]
The variable Build.SourceVersionMessage can be used in a build, but is not documented here. Is this an omission in the documentation, or an unsupported variable?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ffebdc8-521c-44b5-cde4-4abdc1bd6f18
* Version Independent ID: dc0effda-6d93-62aa-64c5-4e6f283b0826
* Content: [Build variables](https://docs.microsoft.com/en-us/vsts/pipelines/build/variables?view=vsts&tabs=batch#feedback)
* Content Source: [docs/pipelines/build/variables.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/build/variables.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by deaquino** [comment]
This variable is not the current Build SourceVersionMessage, is the last successful Build SourceVersionMessage.

**Comment by andyjlewis** [comment]
Thank you for reporting this issue. We fixed it around 8/30.
