### ISSUE TITLE
What are the possible types for the inputs?

### ISSUE THREAD

**Issue by andrasferenczi** [MicrosoftDocs/vsts-docs#1345]
I figured out from examples there are boolean, string, filePath and pickList.

But is there any type for list of strings? Or is there a way to add custom types?

A link to some documentation would be greatly appreciated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 44581f4a-93df-7507-3844-eadedf9a6cc4
* Version Independent ID: 33c7bcf0-1512-975f-5ef8-9f2a192a84ad
* Content: [Add a Build or Release Task](https://docs.microsoft.com/en-us/vsts/extend/develop/add-build-task?view=vsts)
* Content Source: [docs/extend/develop/add-build-task.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/extend/develop/add-build-task.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by arefinsami** [comment]
Can you guys provide us a link to the list of input types allowed in VSTS extensions? Thanks. 
This extension has a lot of interesting inputs but its not open source. 
https://marketplace.visualstudio.com/items?itemName=mspremier.CreateWorkItem&targetId=dfd2778a-aca4-4d2a-b72d-6f143b9e9e66#overview

**Comment by alessandrodalmas** [comment]
Hi, here there is a more open list of possible inputs:
https://github.com/Microsoft/azure-pipelines-task-lib/blob/master/tasks.schema.json

```
"boolean",
"filePath",
"multiLine",
"pickList",
"radio",
"secureFile",
"string"
```

**Comment by elbatk** [comment]
Hi everyone, I think that task.schema.json is what you're looking for, so I'm going to close this out! But feel free to reach out if you think a documentation change should happen!
