### ISSUE TITLE
Incorrect IP Addresses

### ISSUE THREAD

**Issue by vhhughes** [MicrosoftDocs/vsts-docs#1352]
I went through the long process of having the IT department get the IP addresses listed here opened for our Azure VM. When I finally ran the import, it errored out saying that two unlisted IP addresses could not reach our VM. Please update your list here! Either that or, if your tool will report the needed source IP addresses, consider changing your instructions to have us run the tool once in order to find out what IP addresses need to be opened.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a35b397-3fe8-122e-042e-280326f88a38
* Version Independent ID: 3e0f0afc-abeb-01be-d767-813cd6ad78db
* Content: [Migration import from TFS to Visual Studio Team Services (VSTS)](https://docs.microsoft.com/en-us/vsts/articles/migration-import?utm_source=ms&utm_medium=guide&utm_campaign=vstsdataimportguide&view=vsts#configure-the-import-specification-file-to-target-the-vm)
* Content Source: [docs/articles/migration-import.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/articles/migration-import.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by elbatk** [comment]
Hi @vhhughes , I know it's been a while, I believe we have updated our URLs since then, so let me know if you're still having issues. I'm going to close this but please reach out if you need help.
