### ISSUE TITLE
New VSTS "User's hub" not found

### ISSUE THREAD

**Issue by kcrossman** [MicrosoftDocs/vsts-docs#1357]
The "User's hub" doesn't exist in the new VSTS layout.

![image](https://user-images.githubusercontent.com/9127996/42984192-93fa8c08-8ba8-11e8-8d15-b730314d2b0b.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 98e224f9-91ef-2776-b1d8-04d79f4acf78
* Version Independent ID: d37dd0a0-bb80-6a59-08c2-a4e64fd6f103
* Content: [Install and license Package Management for VSTS and TFS](https://docs.microsoft.com/en-us/vsts/package/install?view=vsts)
* Content Source: [docs/package/install.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/package/install.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by kcrossman** [comment]
![image](https://user-images.githubusercontent.com/9127996/42984192-93fa8c08-8ba8-11e8-8d15-b730314d2b0b.png)

**Comment by elbatk** [comment]
Hi @kcrossman , could you try `https://<account>.visualstudio.com/_settings/users` for me?

**Comment by elbatk** [comment]
Closing this for now, please reach out if you're still having issues, @kcrossman
