### ISSUE TITLE
Please provide examples and unit tests for the API !

### ISSUE THREAD

**Issue by pradeepgudipati** [MicrosoftDocs/vsts-docs#1358]
We need more code samples for GitPullRequestSearchCriteria

coreClient.getPullRequests(record, Contracts.GitPullRequestSearchCriteria.status.PullRequestStatus.All, projectName, 99999, 0, 999999).then(function(results) {
                        console.log(results);
});

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2e9e5b84-8a0e-1987-a5b6-96460ed3d8ae
* Version Independent ID: 382f2a46-fb81-a201-8da9-351b0610e6ce
* Content: [TFS/VersionControl/Contracts GitPullRequestSearchCriteria API](https://docs.microsoft.com/en-us/vsts/extend/reference/client/api/tfs/versioncontrol/contracts/gitpullrequestsearchcriteria?view=vsts)
* Content Source: [docs/extend/reference/client/api/TFS/VersionControl/Contracts/GitPullRequestSearchCriteria.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/extend/reference/client/api/TFS/VersionControl/Contracts/GitPullRequestSearchCriteria.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by elbatk** [comment]
Hi @pradeepgudipati , adding @willsmythe to this. I'm not sure if we have any plans to add more code samples here but maybe he can point you to some helpful stuff!

**Comment by pradeepgudipati** [comment]
Thanks Elba, 

How about a Postman Collection for all the API's, Is that also available. 

Regarding the above, I got it to work with the below piece of code 

`coreClient.getPullRequests(repo, {"status": "All"}, projectName, 99999, 0, 999999).then(function(pullRequests) {...}`

Thanks
Pradeep Gudipati

**Comment by elbatk** [comment]
Hello! I know it's been a while, but we are in the process of strengthening these docs via auto-generated reference which I think will help a lot. We also are going to do a pass and create work items for samples and such. Stay tuned! :)
