### ISSUE TITLE
How to add in-house hosted feeds

### ISSUE THREAD

**Issue by JeroenHo** [MicrosoftDocs/vsts-docs#1359]
How can I add private nuget package feed on an on premises hosted TFS 2018 environment?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d5f022df-36c3-34b1-cac1-ac33995a7d73
* Version Independent ID: 9634b0c8-7b14-4453-2c04-aedabbf331f1
* Content: [Upstream sources](https://docs.microsoft.com/en-us/vsts/package/concepts/upstream-sources?view=vsts)
* Content Source: [docs/package/concepts/upstream-sources.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/package/concepts/upstream-sources.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by elbatk** [comment]
Hi @JeroenHo , is it a package hosted on NuGet.org, or are you wanting to host a package in TFS?

**Comment by JeroenHo** [comment]
Hi @elbatk 
We have development teams all over the world and they all have there own hosting for packages. Nuget and NPM package alike. Some use TFS, others use Artifactory.
I was wondering if our on premise running TFS could be the man in the middle, so we only need one source for all packages no matter where there from. 
Currently I can only add Nuget for forwarding, but could be I'm missing something.

**Comment by elbatk** [comment]
Hi @JeroenHo , going to add @alexmullans to this so he can give you a better answer as to whether or not this is possible and what the best way to do it is. thanks!

**Comment by alexmullans** [comment]
@JeroenHo that's not possible today, unfortunately. We're just now adding support for more npm upstreams beyond npmjs.com and VSTS npm feeds to VSTS; that work should make it into the next major version of TFS. Not sure if/when we'll take equivalent work for NuGet.

**Comment by elbatk** [comment]
Closing this issue for now, if you have more questions feel free to reach out @JeroenHo
