### ISSUE TITLE
The generated project has old style csproj

### ISSUE THREAD

**Issue by samsil** [MicrosoftDocs/vsts-docs#1360]
HI, I found that if I create a project following the steps described in this article, vs is generating old csproj. Is there any way I can generate the new-style csproj? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6e19f646-d820-7582-0672-e5d3b3fe8966
* Version Independent ID: 37f94f23-23bb-3306-840a-1291ca0e66b5
* Content: [Load test your app before release](https://docs.microsoft.com/en-us/vsts/test/load-test/run-performance-tests-app-before-release?view=vsts)
* Content Source: [docs/test/load-test/run-performance-tests-app-before-release.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/test/load-test/run-performance-tests-app-before-release.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment]
Thank you for your feedback. I have passed this on to the product team for advice.

**Comment by PBoraMSFT** [comment]
@samsil - the steps in the doc are correct. And the project it generates is also the right one for load testing. Can you elaborate on the old csproj and new-style csproj?
Closing this issue for now. Feel free to reactivate with the details on old/new style..
