### ISSUE TITLE
@mentions to groups

### ISSUE THREAD

**Issue by nomoreshoes88** [MicrosoftDocs/vsts-docs#1363]
Good morning,

I am attempting to use @mentions to group members in TFS 2017. However, when I try to type in the name of a group, none of our groups from TFS or Active Directory populate or allow us to search for them.

We are coming from another project management software that DID allow for this, so we have become pretty reliant on this feature. In this article, it seems like the process should be as easy as typing "@groupName" but it's not working.

What steps do I need to take to get this working?

Thank you,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 34ae521f-6ae4-4d7f-2cce-f844e5811b66
* Version Independent ID: 18098490-1f34-e966-3135-cb90197bfa6f
* Content: [Use @mentions in work items and pull requests - VSTS & TFS](https://docs.microsoft.com/en-us/vsts/notifications/at-mentions?view=vsts)
* Content Source: [docs/notifications/at-mentions.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/notifications/at-mentions.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@nomoreshoes88 - Thank you for your inquiry. The group mentions feature was made available on VSTS this [February](https://docs.microsoft.com/en-us/vsts/release-notes/2018/feb-14-vsts), and is planned for availability in TFS 2019 according to the [Features Timeline](https://docs.microsoft.com/en-us/vsts/release-notes/index).  Please note to use the Version Selector to make sure that you view the content defined for TFS 2017. 

![image](https://user-images.githubusercontent.com/10856840/43221451-b96b643c-9001-11e8-8dc4-b5c0fd0a8a74.png)
