### ISSUE TITLE
Would like the build data restored to the warehouse for non-XAML builds

### ISSUE THREAD

**Issue by cubonesmash** [MicrosoftDocs/vsts-docs#1367]
It would be helpful to restore the build data to the warehouse.  We use an on-premises version and produce reports for compliance and traceability using the warehouse.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 126a5a77-d3fe-af1f-12e5-260ed45151d2
* Version Independent ID: c2adedfc-bc7b-a73c-9c5c-43d8a03346d5
* Content: [Build Details tables - TFS](https://docs.microsoft.com/en-us/vsts/report/sql-reports/table-reference-build-details?view=tfs-2017)
* Content Source: [docs/report/sql-reports/table-reference-build-details.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/report/sql-reports/table-reference-build-details.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@cubonesmash - Thank you for your inquiry. I recommend you post your request to our  [Support](https://www.visualstudio.com/team-services/support/) page.
