### ISSUE TITLE
Why do stakeholders not have View access?

### ISSUE THREAD

**Issue by patroza** [MicrosoftDocs/vsts-docs#1373]
What's the rationale behind this choice?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d704a22b-6a65-7a4c-1111-944c9aeff944
* Version Independent ID: 5880f4f1-ce11-3f43-e0dd-d569f5206b4d
* Content: [Review team delivery plans - VSTS & TFS](https://docs.microsoft.com/en-us/vsts/work/scale/review-team-plans?view=vsts)
* Content Source: [docs/work/scale/review-team-plans.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/work/scale/review-team-plans.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by danhellem** [comment]
Hello Patroza,

This was a decision we made when we originally rolled out delivery plans. We did not invest in the work to make things read-only depending on your license type. It's a great suggestion and I will triage this with our team for future consideration.

**Comment by KathrynEE** [comment]
@patroza  - Please see Dan's response above.

**Comment by patroza** [comment]
Thanks all!
