### ISSUE TITLE
hellboy

### ISSUE THREAD

**Issue by timscharfenort** [MicrosoftDocs/vsts-docs#1375]
[Hier Feedback eingeben]

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 4409a9cb-8448-edd6-da0a-243e5601aa3e
* Version Independent ID: ec15f71a-a76d-c3f9-1d31-832f92183ef4
* Content: [Agents, pools, and queues](https://docs.microsoft.com/de-de/vsts/pipelines/agents/pools-queues?view=tfs-2015#security)
* Content Source: [docs/pipelines/agents/pools-queues.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/agents/pools-queues.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by steved0x** [comment]
@timscharfen. Guten tag and thank you for your feedback. It appears as though your feedback was not saved. Could you please repeat it here? thank you.

**Comment by andyjlewis** [comment]
I'm going to close this for now until we've got the feedback.
