### ISSUE TITLE
Can we use intranet TFS on VSTS ?

### ISSUE THREAD

**Issue by asadabbas88** [MicrosoftDocs/vsts-docs#1377]
As I want to use build part .. i.e. use local intranet TFS and build the project 

PS: Apologies if the forum is not correct !!

**Comment by steved0x** [comment]
@asadabbas88 Thank you or your feedback. The issues in this repo are for content feedback, and this looks like a product question. For product feedback, including feature requests and discussion on features, please file an issue at the forums here: https://developercommunity.visualstudio.com/spaces/21/index.html

Thank you.
