### ISSUE TITLE
Argument YAML names are missing

### ISSUE THREAD

**Issue by loicmorvan** [MicrosoftDocs/vsts-docs#1378]
The names of the arguments from the YAML file are not written in the table, so it's hard to understand the corresponding description. Can you add a column `YAML name`?

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 16bd8dd1-7650-8c18-2553-38a8bc54e892
* Version Independent ID: f9fa517a-7adc-e327-d12e-256295a1ed52
* Content: [Visual Studio Test](https://docs.microsoft.com/fr-fr/vsts/pipelines/tasks/test/vstest?view=vsts)
* Content Source: [docs/pipelines/tasks/test/vstest.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/test/vstest.md)
* Product: **devops**
* GitHub Login: @erickson-doug
* Microsoft Alias: **dastahel**

**Comment by steved0x** [comment]
@loicmorvan How about it I add them into the existing argument column like this:

![image](https://user-images.githubusercontent.com/1580889/43606515-915234da-9669-11e8-9e79-dcadaf14057a.png)

**Comment by loicmorvan** [comment]
Sounds perfect to me! Thanks!
