### ISSUE TITLE
Ability to store more than 4096 characters in the library variable values

### ISSUE THREAD

**Issue by cricketplayer** [MicrosoftDocs/vsts-docs#1380]
Currently trying to store a long json key value pair in the library variable values, but hitting the 4096 character limit.

**Comment by steved0x** [comment]
@cricketplayer Thank you for your feedback. The issues in this repo are for content feedback, and this looks like a product feedback. For product feedback, including feature requests, please file an issue here: https://developercommunity.visualstudio.com/spaces/21/index.html

We'll monitor this and if there is a workaround, we will add it to the documentation.

Thank you.
