### ISSUE TITLE
typo in title URL SharePort -> SharePoint

### ISSUE THREAD

**Issue by nschonni** [MicrosoftDocs/vsts-docs#1382]
The content is fine, just the filename is off

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cac794da-cbe0-8e40-528e-6ded82b71de6
* Version Independent ID: 77d407ac-95e0-ea4c-d994-e892095500e3
* Content: [Modify or Remove Access Between a SharePoint Web Application and TFS](https://docs.microsoft.com/en-ca/tfs/server/admin/modify-remove-access-shareport-tfs#feedback)
* Content Source: [docs/server/admin/modify-remove-access-shareport-tfs.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/server/admin/modify-remove-access-shareport-tfs.md)
* Product: **devops-server**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by elbatk** [comment]
Hi @nschonni , this is unfortunate. I'll have to think if renaming and setting up a redirect and losing whatever weight the article has currently would be worth the correction. SharePoint and TFS are no longer a thing so I'm thinking it may stay the way it is for now.
