### ISSUE TITLE
Access token using SDK

### ISSUE THREAD

**Issue by viperfx** [MicrosoftDocs/vsts-docs#1385]
How can I access the token and URL saved through the service? I would like to grab this URL and token using the Javascript SDK. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad945cf7-cd73-49da-90f5-21eb88f485e1
* Version Independent ID: d3032766-fb21-d299-e34f-05fe1010132c
* Content: [Authentication Schemas for Service Endpoints](https://docs.microsoft.com/en-us/vsts/extend/develop/auth-schemes?view=vsts)
* Content Source: [docs/extend/develop/auth-schemes.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/extend/develop/auth-schemes.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by elbatk** [comment]
Hi @viperfx , looks like this is a good question for the product team, check out the developer community here:
https://developercommunity.visualstudio.com/spaces/21/index.html

I'm going to close this issue, but will update the docs if we find this is an area that needs to be covered.
