### ISSUE TITLE
Can multiple agents on one machien share the same binarys?

### ISSUE THREAD

**Issue by LokiMidgard** [MicrosoftDocs/vsts-docs#1386]
I tried to configure multiple agents on the same machine, using the same config script but with different agent names and working folders.  
I tried to share the binarys in bin and externals.

But the agents always complains it is already configured. Do I need to have a copy of all binarys for each agent?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 47625b86-abd5-ee15-6d61-8bcf81861b96
* Version Independent ID: be9a6174-a69b-7aed-d584-5f602fcc5eb4
* Content: [Build and Release Agents](https://docs.microsoft.com/en-us/vsts/pipelines/agents/agents?view=vsts)
* Content Source: [docs/pipelines/agents/agents.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/agents/agents.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by andyjlewis** [comment]
Yes, each agent needs its own installation with its own binaries.
