### ISSUE TITLE
The hightlighting rectangle in the screenshot is on wrong item

### ISSUE THREAD

**Issue by jeremymeng** [MicrosoftDocs/vsts-docs#1390]
I would expect the screenshot highlight "Preview features", instead of "My profile"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b4f95345-6686-8e29-ff3f-cbea4a6eb24d
* Version Independent ID: 695d975e-ea9b-139b-4f98-f9655a751f59
* Content: [Turn preview features on or off - VSTS](https://docs.microsoft.com/en-us/vsts/project/navigation/preview-features?view=vsts&tabs=previous-nav#enable-features-for-your-use)
* Content Source: [docs/project/navigation/preview-features.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/project/navigation/preview-features.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@jeremymeng - Thank you for the correction. Making the updates now.
