### ISSUE TITLE
How to pass environment variables

### ISSUE THREAD

**Issue by stevozilik** [MicrosoftDocs/vsts-docs#1392]
Hi,

Is there any ability to define load tests once and then run those against various hosts? We have a number of environments that need to be load tested, and there does not seem to be any ability to inject variables into URL e.g.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4c5348c1-4b41-0644-ce16-91c6969d8ffb
* Version Independent ID: 51530f61-b72e-c09a-57e7-df5e0501fbf4
* Content: [Get Application Insights performance data with load tests](https://docs.microsoft.com/en-us/vsts/test/load-test/get-performance-data-for-load-tests?view=vsts)
* Content Source: [docs/test/load-test/get-performance-data-for-load-tests.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/test/load-test/get-performance-data-for-load-tests.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment]
Thank you for your feedback. I have passed this on to the product team for advice.

**Comment by PBoraMSFT** [comment]
@stevozilik - context parameters are the glue to passing information and changing values for those parameters as desired.
1. Parameterize URLs in your webtest
2. Add a context parameter in your load test runsettings (right click Active runsettings in load test editor -> add context parameter)

If you are running load tests in the CI/CD pipeline where the URL of the app may change from environment to environment, we recently enhanced the cloud load test task that allows you to override the context parameter value from the task UI and use any environment variables of the pipeline to pass in the desired information.

@alexhomer1 - Can you add this to the documentation, please?

**Comment by alexhomer1** [comment]
Thank you for your feedback. I will update the topic to include your recommendations.

**Comment by stevozilik** [comment]
@PBoraMSFT - thank you, I agree that works, I've discovered all of that in last few days. I assume you mean having the load tests defined in a solution and checked in source control.

Are there any plans to make the VSTS UI richer to be able to define these via the web interface (cut out checking in code/Visual Studio)?

**Comment by PBoraMSFT** [comment]
@stevozlilik - no, enhancing the VSTS UI capabilities is not on the backlog for the foreseeable future.
