### ISSUE TITLE
Version spec syntax

### ISSUE THREAD

**Issue by austindonnelly** [MicrosoftDocs/vsts-docs#1393]
What's the syntax for the "version spec" field?
What can I write there? 
A link to some documentation would be ideal.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e765cfad-8ab9-443a-1171-5af81a31252f
* Version Independent ID: 8ff69d93-0128-dbeb-9d63-45266ed73020
* Content: [Use Python Version](https://docs.microsoft.com/en-us/vsts/pipelines/tasks/tool/use-python-version?view=vsts)
* Content Source: [docs/pipelines/tasks/tool/use-python-version.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/tool/use-python-version.md)
* Product: **devops**
* GitHub Login: @erickson-doug
* Microsoft Alias: **brcrista**

**Comment by steved0x** [comment]
@austindonnelly It uses the same version spec language as the `semver` NPM package. If you hover over the information icon you should get a tooltip with some more information and a link. 

![image](https://user-images.githubusercontent.com/1580889/43529648-c1d370ba-9579-11e8-9a01-6ab576fcda23.png)

For more information, see https://www.npmjs.com/package/semver

Thank you,
Steve
