### ISSUE TITLE
Collection level dashboards?

### ISSUE THREAD

**Issue by kallred1** [MicrosoftDocs/vsts-docs#1396]
I think this documentation is great for learning how to set up project and team dashboards! However, i can't find any info on whether such a thing as a project collection level dashboard exists. it'd be great if that was answered somewhere!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d3d9f6cf-89b6-a0e3-0a37-f23446ede457
* Version Independent ID: 988af21a-7ee0-66b4-0fac-07360b8be17d
* Content: [Add and manage team dashboards](https://docs.microsoft.com/en-us/vsts/report/dashboards/dashboards?view=vsts&tabs=new-nav)
* Content Source: [docs/report/dashboards/dashboards.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/report/dashboards/dashboards.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@kallred1 - Thank you for your comment. I agree that it is something that is currently lacking in our documentation. Currently, we don't support collection-level dashboards. You can get some cross-project reports using the Analytics service.
