### ISSUE TITLE
Replace images of JSON with text version

### ISSUE THREAD

**Issue by nschonni** [MicrosoftDocs/vsts-docs#1398]
There are 7 images of JSON samples on the page. It would be nice to include the actual code instead

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a35b397-3fe8-122e-042e-280326f88a38
* Version Independent ID: 3e0f0afc-abeb-01be-d767-813cd6ad78db
* Content: [Migration import from TFS to Visual Studio Team Services (VSTS)](https://docs.microsoft.com/en-us/vsts/articles/migration-import?utm_source=ms&utm_medium=guide&utm_campaign=vstsdataimportguide&view=vsts#feedback)
* Content Source: [docs/articles/migration-import.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/articles/migration-import.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by elbatk** [comment]
I don't know how this fell through the cracks for me, @nschonni , I know you comment a lot. You can either create a PR for us with code snippets, which would be nice :) or I'm going to add @roofers here to check out the feedback.

**Comment by roofers** [comment]
@nschonni - Thank you for your feedback. I normally agree that having the actual JSON examples as text is better, but in this case that rule doesn't prove out. 

The import.json files are generated by the TfsMigrator tool. They include a checked sum validation data section which can't be modified. In the past we had raw JSON text and too many customers copy-pasted that text into an import.json file and tried to queue an import. This lead to a lot of confusion as customers thought they could skip the validate phase. So, we switched to images and included copyable text for the large import method only.

**Comment by elbatk** [comment]
Ah, makes sense to me, I had no idea. Going to close this now, seems like a good reason to not include it as copy/pastable code. I could see us putting it as code snippets with a warning, but people may not pay attention, ha.
