### ISSUE TITLE
Article needs extensive additional references

### ISSUE THREAD

**Issue by iyerusad** [MicrosoftDocs/vsts-docs#1399]
This article on VSTS needs references to numerous other articles describing limitations within the VSTS platform (e.g. CI/CD limitations: https://docs.microsoft.com/en-us/vsts/pipelines/licensing/concurrent-jobs-vsts?view=vsts). Please add.

I'm having a difficult time locating documentation on published limits within the VSTS platform.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5c2c2355-60a5-d53f-2c72-8f032c1b8cf2
* Version Independent ID: 711bf22d-99c9-51b2-382c-e095bdb2c37f
* Content: [Resource limits & constraints - VSTS](https://docs.microsoft.com/en-us/vsts/integrate/concepts/rate-limits?view=vsts)
* Content Source: [docs/integrate/concepts/rate-limits.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/integrate/concepts/rate-limits.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by danhellem** [comment]
thanks for the feedback. we will take a look and see if it makes sense to add additional resources to the rate limits page
