### ISSUE TITLE
File size limit for VSTS stored artifacts?

### ISSUE THREAD

**Issue by iyerusad** [MicrosoftDocs/vsts-docs#1400]
What are the size limits for VSTS stored artifacts?

This came up when contemplating storing a many GB file (e.g. VHD) artifact on VSTS. I don't see reference to size limit. I probably won't do this (and I'm pretty sure probably already limited) and will instead use storage accounts but it would be helpful to know the ballpark limit working with.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c028a99-45f1-3609-3219-89789dc6b966
* Version Independent ID: f626f40e-1bab-4d8a-cd19-ab3b5da4be0a
* Content: [Artifacts in Team Build](https://docs.microsoft.com/en-us/vsts/pipelines/build/artifacts?view=vsts)
* Content Source: [docs/pipelines/build/artifacts.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/build/artifacts.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by natxete88** [comment]
This information would be good, any update?

**Comment by elbatk** [comment]
Hi @iyerusad and @natxete88 , sorry about the super long delay here, things have been crazy in docs land for (now) Azure DevOps. I'm adding @alexmullans to answer your question here and then I can add something to the docs if we need to!

**Comment by alexmullans** [comment]
NuGet packages are limited to about 250 MB. The new [Universal Packages](https://blogs.msdn.microsoft.com/devops/2018/07/09/universal-packages-bring-large-generic-artifact-management-to-vsts/) (which are a few weeks from public preview) don't have a size limit and are well-suited to handle VHDs. If you'd like, @mitchdenny and I can add you to the public preview for Universal Packages - let us know.

**Comment by natxete88** [comment]
@alexmullans Thanks for the reply. I'm not sure that I'm following your answer with regard to the original question - which I did not post - so I will ask it in my own form: We have a mix  c++/UWP , C# and Win32 apps and as part of our test pipeline we temporarily host our build artifacts on vsts (now AzureDev). Haven't hit a wall yet and realize the retention policies only go out as far as 30 days. the question is: How large is a VSTS Organization's storage allocation for "Upload Build Artifacts" type build tasks ? If we have many builds in a 30-day period and are retaining all artifacts for that time will we hit a wall?

**Comment by chrisrpatterson** [comment]
Currently there is no hard limit set just like there is no hard limit set for repos.

**Comment by iyerusad** [comment]
Appreciate it, closing the issue. 

For our team, we ended up consuming storage accounts, mounted via SMB generally (and blob where appropriate). We were working on building a VHD gallery that would be populated with VHDs built from pipelines, available to devs on the team via [Hyper-V's custom gallery](https://docs.microsoft.com/en-us/virtualization/hyper-v-on-windows/user-guide/custom-gallery). Challenges around converting from VHD to VHDx (dynamically) was where this stemmed from.

**Comment by natxete88** [comment]
@chrisrpatterson thanks for the confirmation
