### ISSUE TITLE
xml transformation for "Azure App Service Deployment 4* preview", breaking changes from july24,2018

### ISSUE THREAD

**Issue by linnia78** [MicrosoftDocs/vsts-docs#1401]
the latest commit is breaking the xml transformations.

Transformations are being applied and reports success but the incorrect package is deployed where transformations did not take place.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 315ff823-9992-9f9b-62a1-42ce622ed41c
* Version Independent ID: 72ec3ffc-1dc9-b2dc-e3d4-4f14deae3720
* Content: [File transforms and variable substitution](https://docs.microsoft.com/en-us/vsts/pipelines/tasks/transforms-variable-substitution?view=vsts#xml-transformation)
* Content Source: [docs/pipelines/tasks/transforms-variable-substitution.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/transforms-variable-substitution.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment]
Thank you for your feedback. I have passed this on to the product team for investigation.

**Comment by alexhomer1** [comment]
The product team advise that the issue has been resolved and the fix is deployed to all accounts. Please redeploy and let us know with a new issue if you are still seeing the incorrect behaviour. Thank you.
