### ISSUE TITLE
.

### ISSUE THREAD

**Issue by tomaszek1989** [MicrosoftDocs/vsts-docs#1402]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c94a78f-77de-a612-1fc8-749518195166
* Version Independent ID: fba4f685-1c59-e1e6-2138-aaa5477e476d
* Content: [Change your email address - VSTS & TFS](https://docs.microsoft.com/en-us/vsts/notifications/change-email-address?view=vsts)
* Content Source: [docs/notifications/change-email-address.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/notifications/change-email-address.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by elbatk** [comment]
Closing this issue for now, feel free to reopen if you can find your feedback @tomaszek1989  :)
