### ISSUE TITLE
No VSTS Organization appears

### ISSUE THREAD

**Issue by jstewart2** [MicrosoftDocs/vsts-docs#1403]
There should be some information about how to proceed when no VSTS organization is listed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1ef5cd1c-b235-3ccd-3069-732a1ca15b6b
* Version Independent ID: f977367f-7cac-817f-74db-912828c3ce5a
* Content: [Start to set up billing for VSTS](https://docs.microsoft.com/en-us/vsts/organizations/billing/set-up-billing-for-your-organization-vs?view=vsts)
* Content Source: [docs/organizations/billing/set-up-billing-for-your-organization-vs.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/billing/set-up-billing-for-your-organization-vs.md)
* Product: **devops**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
@jstewart2 thanks for your comment. You either don't have a VSTS organization or are signed in with the wrong identity, likely. But, we'd like to know more about your scenario, so we can better address it. Would you please contact me at chcomley@microsoft.com? Thanks! I've created a work item to clarify this within the doc.

**Comment by nguyenlamlll** [comment]
I'm seeing the same problem. I'm sure that I'm using the right credentials (I can log in to my_company.visualstudio.com and Azure portal). However, it says "Nothing to display" in Team Services administration.

**Comment by chcomley** [comment]
@nguyenlamlll I'm sorry you are also experiencing difficulty. I have engaged a PM and will reply back to this thread.

**Comment by chcomley** [comment]
@nguyenlamlll, are you a project collection admin or owner on the organization?

**Comment by nguyenlamlll** [comment]
Hey @chcomley, I'm sorry for this late reply... 
I'm just an administrator. I got the Visual Studio Enterprise MPN subscription from the organization.

**Comment by chcomley** [comment]
@nguyenlamlll If you're already a member of the Project Administrators group, or a team administrator for the team you want to update, make sure you're also a member of a project. If you're still having problems, please send me the details in an email and I'll loop in a PM. chcomley@microsoft.com. Thanks.
