### ISSUE TITLE
extension failed to load (hub)

### ISSUE THREAD

**Issue by psdev2** [MicrosoftDocs/vsts-docs#1405]
Hi,

I have a problem with developing extension (hub). I follow step by step these tutorials:
https://docs.microsoft.com/en-us/vsts/extend/develop/add-hub?view=vsts
https://docs.microsoft.com/en-us/vsts/extend/get-started/node?view=vsts

but still i have the same problem: "[extension id] by [publisher] failed to load.Learn More about this extension, including available support options."

![failedtoload](https://user-images.githubusercontent.com/41677007/43258371-db0c92ba-90d2-11e8-8e84-4f133802a280.png)

I tried many ways but still I have no idea what is wrong. Uri, targets and ids are ok, I think. I tried different structures of an extension and different targets like "ms.vss-work-web.work-hub-group" and "ms.vss-code-web.code-hub-group" to see  if something will change but it's the same - "failed to load". Other extensions that I did (work item custom control and work item custom action) works good. Can anyone help mi fix this?

In Google Chrome DevTools I did not find anything that could help me, but I found this:

![failedtoloaddevtoolsgooglechrome](https://user-images.githubusercontent.com/41677007/43258372-db2a4ff8-90d2-11e8-9045-7a45a4b61ea1.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b68bebb-14b6-8f83-b362-03d643d39538
* Version Independent ID: de6d224b-2a80-b093-0330-4f70b5892fe3
* Content: [Add a Hub](https://docs.microsoft.com/en-us/vsts/extend/develop/add-hub?view=vsts)
* Content Source: [docs/extend/develop/add-hub.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/extend/develop/add-hub.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by elbatk** [comment]
hi @psdev2 , this would be a good question for the developer community:
https://developercommunity.visualstudio.com/spaces/21/index.html

Closing this issue as it seems more like a troubleshooting problem that the product team may help with than a docs problem.
