### ISSUE TITLE
Dead link to Visual Studio TFS Branching Guide

### ISSUE THREAD

**Issue by haakoo** [MicrosoftDocs/vsts-docs#1406]
It looks like the link to [Visual Studio TFS Branching Guide] (http://go.microsoft.com/fwlink/?LinkId=191400) =&gt; [@Codeplex](https://archive.codeplex.com/?p=tfsbranchingguideiii) is dead. The same is true for http://www.codeplex.com/TFSBranchingGuideII. This is probably also a problem other places in the docs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d5d657df-3541-bfd2-5a6e-fef75545bd9b
* Version Independent ID: 1f831b18-5d71-10b5-6bed-36adfdf0f711
* Content: [Branch folders and files](https://docs.microsoft.com/en-us/vsts/tfvc/branch-folders-files?view=vsts#feedback)
* Content Source: [docs/tfvc/branch-folders-files.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/tfvc/branch-folders-files.md)
* Product: **devops**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by eriawan** [comment]
@haakoo 

Good catch!
I know where the replacement link.
I will create a PR today to update the link.

**Comment by eriawan** [comment]
PR to fix this stale link has been submitted: #1421 .
