### ISSUE TITLE
For VSTS Agile workflow states,  we need to be able to  configure reason

### ISSUE THREAD

**Issue by Justasvil** [MicrosoftDocs/vsts-docs#1410]
Changing state from new to active does  not mean that "implementation has started".  However, this is what  VSTS adds when using agile workflow state.   Please make this  configurable.  Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c0896813-3b6e-a676-c544-03be185600df
* Version Independent ID: f141c33d-e9b5-3c2a-f047-7f1925d052f9
* Content: [Workflow states and state categories - VSTS & TFS](https://docs.microsoft.com/en-us/vsts/work/customize/workflow-and-state-categories?view=vsts)
* Content Source: [docs/work/customize/workflow-and-state-categories.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/work/customize/workflow-and-state-categories.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@Justasvil  - Thank you for your inquiry. As this is a request to enhance the product, please consider adding this request to our UserVoice page, https://visualstudio.uservoice.com/forums/330519-team-services.
