### ISSUE TITLE
Uninstall for 2017 showing raw markdown instead of image

### ISSUE THREAD

**Issue by nschonni** [MicrosoftDocs/vsts-docs#1411]
Not sure if they're supposed to be in a tab, but currently shows as raw
```
**TFS 2017**

&lt;img alt="Manage extensions" src="../_shared/_img/manage-extensions2-new.png" style="border: 1px solid #CCCCCC" /&gt;
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0ceb772f-1723-9851-a216-13dd05e78771
* Version Independent ID: 1c1ebec0-41cc-8262-43a1-b0888d0521e0
* Content: [Uninstall or disable extensions in Visual Studio Team Foundation Server (TFS)](https://docs.microsoft.com/en-us/vsts/marketplace/how-to/uninstall-disable-extensions-tfs?view=vsts)
* Content Source: [docs/marketplace/how-to/uninstall-disable-extensions-tfs.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/marketplace/how-to/uninstall-disable-extensions-tfs.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by nschonni** [comment]
Looks fine on GH, but not on the published page

**Comment by elbatk** [comment]
Thanks @nschonni , submitted a fix for this :)
