### ISSUE TITLE
location of physical packages storage

### ISSUE THREAD

**Issue by verbaloid** [MicrosoftDocs/vsts-docs#1414]
Where are packages physically stored?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 078a8c96-ec59-c10b-e48e-8c5586c8cb09
* Version Independent ID: 200f5723-2404-298d-e6bb-533592a28ff3
* Content: [Package Management in VSTS and TFS](https://docs.microsoft.com/en-us/vsts/package/overview?view=vsts)
* Content Source: [docs/package/overview.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/package/overview.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by elbatk** [comment]
Adding @alexmullans to answer this for ya, @verbaloid

**Comment by alexmullans** [comment]
@verbaloid in TFS or VSTS? Assuming the former, they're stored in the database along with your other TFS data.

**Comment by elbatk** [comment]
Thanks @alexmullans , closing this issue for now but feel free to reach out if you have more questions @verbaloid .

**Comment by verbaloid** [comment]
thank you
