### ISSUE TITLE
Unfinished sentence under Related articles

### ISSUE THREAD

**Issue by andymerritt** [MicrosoftDocs/vsts-docs#1415]
There is an unfinished sentence starting "So now you've got an idea.... " under the sub heading Related articles. This seems out of place and should probably be removed or moved above sub heading and completed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d704a22b-6a65-7a4c-1111-944c9aeff944
* Version Independent ID: 5880f4f1-ce11-3f43-e0dd-d569f5206b4d
* Content: [Review team delivery plans - VSTS & TFS](https://docs.microsoft.com/en-us/vsts/work/scale/review-team-plans?view=vsts#feedback)
* Content Source: [docs/work/scale/review-team-plans.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/work/scale/review-team-plans.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@andymerritt - Thanks for your feedback. I agree and  am removing the text.
