### ISSUE TITLE
First image shows Feature across multiple sprints however this is not possible

### ISSUE THREAD

**Issue by andymerritt** [MicrosoftDocs/vsts-docs#1416]
The first image is very misleading and there should be some indicator that the Feature is being dragged to a new sprint rather than spanning multiple sprints

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d704a22b-6a65-7a4c-1111-944c9aeff944
* Version Independent ID: 5880f4f1-ce11-3f43-e0dd-d569f5206b4d
* Content: [Review team delivery plans - VSTS & TFS](https://docs.microsoft.com/en-us/vsts/work/scale/review-team-plans?view=vsts#feedback)
* Content Source: [docs/work/scale/review-team-plans.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/work/scale/review-team-plans.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@andymerritt  - Thank you for the feedback. I've updated the topic to make it clear that the work item is being updated by dragging it to a later sprint.
