### ISSUE TITLE
I dont think it actually works this way...

### ISSUE THREAD

**Issue by StingyJack** [MicrosoftDocs/vsts-docs#1418]
&gt; For engineering health, we cap active bugs per engineer. If a team has more than 5 bugs per engineer, they need to prioritize fixing those bugs ahead of new feature development. We also track aging bugs in special categories like security.

You probably define "Active" differently, as there is a whole DevCommunity site and a slew of GitHub projects that are chock full of unresolved reported defects. Its currently at about 11K active items, is that really tying up 2,200 engineers?  If it is, I don't really see the results of this in VS 2017 since its release, with crashes and lockups and lost work happening to myself and everyone I've spoken to that uses it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1acb75f5-3f74-13a0-4053-406efc5389d7
* Version Independent ID: 216cbb0d-3e7b-b24e-b3c1-a9ae7776c14a
* Content: [Shift Left to Make Testing Fast and Reliable - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/devops-at-microsoft/shift-left-make-testing-fast-reliable)
* Content Source: [https://mseng.visualstudio.com/DefaultCollection/TechnicalContent/_git/devops-learn-pr?path=%2fdocs%2fdevops-at-microsoft%2fshift-left-make-testing-fast-reliable.md&version=GBlive&_a=contents](https://mseng.visualstudio.com/DefaultCollection/TechnicalContent/_git/devops-learn-pr?path=%2fdocs%2fdevops-at-microsoft%2fshift-left-make-testing-fast-reliable.md&version=GBlive&_a=contents)
* Product: **devops**
* Git Login: **samgu**
* Microsoft Alias: **munils**

**Comment by steved0x** [comment]
@StingyJack I will pass this along, thank you.
