### ISSUE TITLE
Two-Way integration Zendesk->VSTS not working

### ISSUE THREAD

**Issue by pmosupport** [MicrosoftDocs/vsts-docs#1419]
Hi 

I have installed the VSTS integration toolkit and followed the steps as listed here

But the integration does not work. 

I can create a new work item only via zendesk. The comments update thats suppose to happen either way doesn't work.

Can I get some assistance on this please

**Comment by pmosupport** [comment]
Hi 

Can anyone help me please

**Comment by pmosupport** [comment]
@steved0x  Thanks for the reply 

I set it up based on the below article

https://docs.microsoft.com/en-us/vsts/service-hooks/services/zendesk?view=vsts

but the coments are not being updated at either end

**Comment by pmosupport** [comment]
![image](https://user-images.githubusercontent.com/41772123/43497873-9c64368a-9587-11e8-943c-012d072e2222.png)

Also tried installing the app again and this is the error i get when i upload the file i downloaded from here

**Comment by steved0x** [comment]
@pmosupport Thank you for letting me know, I am assigning this issue to the author of that article.

**Comment by ARenfroe** [comment]
@steved0x @elbatk is this still open?  Any luck?

**Comment by elbatk** [comment]
It's been a while, but I'm going to add @roofers here for awareness. This looks like a product issue more than a docs issue, so I'm going to forward you to the [Azure DevOps Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html) which is actively monitored by the product team. We are in the process of updating the service hooks docs as well. Closing this issue for now.
