### ISSUE TITLE
Formatting on page "All WITD XML elements reference" not well

### ISSUE THREAD

**Issue by Styxxy** [MicrosoftDocs/vsts-docs#142]
On page https://docs.microsoft.com/en-us/vsts/work/customize/reference/all-witd-xml-elements-reference the formatting is not well done in the table.

![tfs](https://user-images.githubusercontent.com/1635825/35698350-10bbe110-078d-11e8-84d0-ae6642a3bcfe.png)

**Comment by steved0x** [comment]
@Styxxy Thank you for your contribution, I have filed a work item to get these fixed, thanks again for letting us know.

**Comment by steved0x** [comment]
@Styxxy These fixes (for this issue and the other one) are made and should be live by tomorrow, thanks again for letting us know.
