### ISSUE TITLE
Minor updates due to UI changes in products

### ISSUE THREAD

**Issue by jmlumpkin** [MicrosoftDocs/vsts-docs#1422]
Some of the screenshots do not match what the azure portal looks like now, slight wording changes and the like. For example, under 'Connect your VSTS organization to your Azure AD' section, it says 'Connect AAD'. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 60e3f1aa-2935-a206-2d2a-fd39f1fdfacb
* Version Independent ID: b0d0a3b8-f5b3-0a9c-42c2-4d185b80564e
* Content: [Connect VSTS organization to Azure Active Directory (Azure AD)](https://docs.microsoft.com/en-us/vsts/organizations/accounts/connect-organization-to-aad?view=vsts)
* Content Source: [docs/organizations/accounts/connect-organization-to-aad.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/accounts/connect-organization-to-aad.md)
* Product: **devops**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Thanks for your comment, @jmlumpkin. I've made some updates and replaced screen shots and the new version of this topic should be live sometime this afternoon. Thanks again!
