### ISSUE TITLE
Needs more definition and examples

### ISSUE THREAD

**Issue by RubixRevenge** [MicrosoftDocs/vsts-docs#1425]
While a good intro, it needs more definition and examples. For example, how do you use each of the fields in the NuGet commands and tasks? E.g., NuGet pack has pack options, advanced properties, etc. Since a web search for "TFS Nuget Pack" leads here, then this is the place where this information should be written and kept.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f2512189-84f9-f997-0255-13b276c233b4
* Version Independent ID: c7ccb0ba-4221-bdac-85e1-111eaf51943b
* Content: [Publishing to NuGet feeds](https://docs.microsoft.com/en-us/vsts/pipelines/targets/nuget?view=tfs-2018&tabs=web)
* Content Source: [docs/pipelines/targets/nuget.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/targets/nuget.md)
* Product: **devops**
* GitHub Login: @erickson-doug
* Microsoft Alias: **amullans**

**Comment by alexmullans** [comment]
@elbatk can you add a link from the targets doc to the [full NuGet task reference doc](https://docs.microsoft.com/en-us/vsts/pipelines/tasks/package/nuget?view=tfs-2018)? That doc has the sorts of examples and properties @RubixRevenge is looking for.

**Comment by RubixRevenge** [comment]
@alexmullans -- I took a look at the full Nuget link you just cited. I may be reading the document incorrectly. Even though i have TFS 2018 selected in the dropdown, the document text mentions a lot of VSTS language in it. My concern is that while there are areas of overlap between TFS 2018 and VSTS, there are also elements that are mutually exclusive between TFS and VSTS.

**Comment by alexmullans** [comment]
Ah, thanks for clarifying. That doc was written before the version moniker support existed. I've prepped a change that takes proper advantage of monikers and removes the VSTS-specific items from the TFS version of the page. Thanks for reporting.

**Comment by RubixRevenge** [comment]
@alexmullans -- Thanks for giving a status update. I checked out "https://docs.microsoft.com/en-us/vsts/pipelines/tasks/package/nuget?view=tfs-2018" right now. I do see useful definition presentations. 

Is it too tall of an order to see usage samples as they are actually used in the TFS interface?  While I eventually figured it out, it would have been more efficient too see a sample like this. (See attached screenshot.)

![example](https://user-images.githubusercontent.com/18014544/44432682-ea832080-a557-11e8-9b1b-c179f3d222a5.png)

**Comment by alexmullans** [comment]
@RubixRevenge fair ask :). We tend to avoid screenshots where they don't add a ton of value as they become outdated very quickly. But, we have some upcoming product and docs improvements that might help here. Will add this to our list of items to consider.
