### ISSUE TITLE
Change code-REST to code-JSON

### ISSUE THREAD

**Issue by nschonni** [MicrosoftDocs/vsts-docs#1426]
For some of the previous-api examples the return results are using `code-REST` although they are just pulling in a JSON file.
This example tagging doesn't appear to be used in any other docs repo.

**Comment by elbatk** [comment]
Hi @nschonni , which docs are you referring to here? Again I'd invite ya to throw in a PR and I'd be happy to review it!

**Comment by nschonni** [comment]
I don't think any of the "previous-api" docs are actually in this repo since I believe they're generated. I'll see if I can find some particular articles, but it might be something in the build setup for the old API docs
