### ISSUE TITLE
Formatting on page "Expand list items and exclude groups from lists" not well

### ISSUE THREAD

**Issue by Styxxy** [MicrosoftDocs/vsts-docs#143]
See on page "Expand list items and exclude groups from lists" : https://docs.microsoft.com/en-us/vsts/work/customize/reference/expand-list-items-and-exclude-groups-from-lists?toc=/vsts/work/customize/toc.json&bc=/vsts/work/customize/breadcrumb/toc.json#example-do-not-expand-lists-or-groups-and-do-not-filter

The "note" field is not correctly rendered.

![note](https://user-images.githubusercontent.com/1635825/35698396-2f4f0788-078d-11e8-9713-455ff54202cd.png)

**Comment by steved0x** [comment]
@Styxxy Thank you for your contribution, I have filed a work item to get these fixed, thanks again for letting us know.
