### ISSUE TITLE
Title/metadata missing "I" from Install

### ISSUE THREAD

**Issue by nschonni** [MicrosoftDocs/vsts-docs#1432]
The current heading is shown as "nstall and configure Team Foundation Server" for the tab title. It is correct in the actual article content

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6939f137-c304-38fb-c19c-9e650cd19cfa
* Version Independent ID: 7b227c4e-6507-5543-16b6-a81956bd3484
* Content: [nstall and configure Team Foundation Server](https://docs.microsoft.com/en-us/tfs/server/admin/backup/tut-single-svr-install-config-tfs#feedback)
* Content Source: [docs/server/admin/backup/tut-single-svr-install-config-tfs.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/server/admin/backup/tut-single-svr-install-config-tfs.md)
* Product: **devops-server**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by elbatk** [comment]
Fixing this now! should be live by end of day, thanks @nschonni
