### ISSUE TITLE
Attachment Visio support is misleading 

### ISSUE THREAD

**Issue by acds** [MicrosoftDocs/vsts-docs#1434]
For Attachments the documentation leads one to believe that it will "render" a Visio diagram on the page; but it just grabs an image and adds that as an attachment. If the Visio diagram has links to other pages it provide an advanced mechanism for navigation. Without either image map or direct Visio rendering this does not work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fa622358-f5bb-1f5c-177a-081a37b6acef
* Version Independent ID: 72f7fd16-a822-66c8-3a34-8905645ce5f2
* Content: [Syntax usage for Markdown files, widgets, wikis, and pull requests - VSTS & TFS](https://docs.microsoft.com/en-us/vsts/project/wiki/markdown-guidance?view=vsts)
* Content Source: [docs/project/wiki/markdown-guidance.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/project/wiki/markdown-guidance.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@acds - Thank you for your feedback. I'm updating the topic to make it more clear that only image files are rendered as images.
