### ISSUE TITLE
typo: "to. Fvisualstudio.microsoft.comonnect to a TFS 2015 instance"

### ISSUE THREAD

**Issue by nschonni** [MicrosoftDocs/vsts-docs#1436]
Couldn't figure out what it was supposed to be to fix it

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6e7bb52a-8625-dffb-a8ba-455d03165123
* Version Independent ID: 381c5db2-b8bb-c5a4-ace5-3c44de405f15
* Content: [Manually add features after an upgrade - TFS](https://docs.microsoft.com/en-ca/vsts/work/customize/add-features-manually?view=tfs-2018#feedback)
* Content Source: [docs/work/customize/add-features-manually.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/work/customize/add-features-manually.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@nschonni - Thank you for the correction. I'm updating this  article and several other articles where a find/replace substitution introduced several errors.
