### ISSUE TITLE
typo: "Grant Advanced access tadd-organization-users-from-user-hub.mdl the features available with portfolio backlogs."

### ISSUE THREAD

**Issue by nschonni** [MicrosoftDocs/vsts-docs#1437]
Maybe a find/replace issue or a merge

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 03b6fdf0-f113-2a11-b87b-7b8a336533c9
* Version Independent ID: 8e068d2e-f4e1-856c-5fc0-ddb41dcd3fdd
* Content: [Add portfolio backlogs - VSTS & TFS](https://docs.microsoft.com/en-ca/vsts/work/customize/add-portfolio-backlogs?view=vsts#feedback)
* Content Source: [docs/work/customize/add-portfolio-backlogs.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/work/customize/add-portfolio-backlogs.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@nschonni - Thank you for the correction. I'm updating the article now for publication later today.
