### ISSUE TITLE
typo: "when you add teamvisualstudio.microsoft.comction."

### ISSUE THREAD

**Issue by nschonni** [MicrosoftDocs/vsts-docs#1438]
Probably a bad merge for find/replace

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f344f9d-0f43-5850-1abc-0a4c076d82cf
* Version Independent ID: 05455f70-0225-0f15-d3b1-c046117acdbd
* Content: [Manage new form roll out - TFS](https://docs.microsoft.com/en-ca/vsts/work/customize/manage-new-form-rollout?view=tfs-2018#feedback)
* Content Source: [docs/work/customize/manage-new-form-rollout.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/work/customize/manage-new-form-rollout.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@nschonni - Thank you for the correction. I'm updating the article now for publication later today.
