### ISSUE TITLE
Remove file name generated `title` attributes on images

### ISSUE THREAD

**Issue by nschonni** [MicrosoftDocs/vsts-docs#1439]
This article is just an example, but you can find others by searching for the regex `\s\"\w*\"\)` (or a better regex maybe 😜).

Example
```markdown
 ![Toolbar for Query Results Web Part](_img/procguid_dashboardworkbook_toolbar.png "ProcGuid_DashboardWorkbook_Toolbar")  
```

Renders to 
```html
<img src="_img/procguid_dashboardworkbook_toolbar.png?view=tfs-2017" alt="Toolbar for Query Results Web Part" title="ProcGuid_DashboardWorkbook_Toolbar" data-linktype="relative-path" class="x-hidden-focus">
```
Note the `ProcGuid_DashboardWorkbook_Toolbar`

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d1117019-baee-839a-3fd2-ad0380361d02
* Version Independent ID: c3287dee-f951-98cf-31e7-2944ce51057b
* Content: [Project portal dashboards](https://docs.microsoft.com/en-ca/vsts/report/sharepoint-dashboards/project-portal-dashboards?view=tfs-2017)
* Content Source: [docs/report/sharepoint-dashboards/project-portal-dashboards.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/report/sharepoint-dashboards/project-portal-dashboards.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@nschonni - Thank you for bringing this to my attention. I'm looking into getting this fixed. It is an artifact of the way content was migrated from the original MSDN topics. It may take a while to get corrected as there are hundreds of instances to fix.
