### ISSUE TITLE
How to send alert to specific person if there is a change in requirement document.

### ISSUE THREAD

**Issue by ampac28** [MicrosoftDocs/vsts-docs#1441]
Our QA needs a notification whenever there is a change or addition of requirements to VSTS. Please suggest.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 48641a87-20db-b3e9-d591-8062aaaad424
* Version Independent ID: e1610bde-e50f-34b5-82c4-b6cd373013bc
* Content: [Set alerts, get notified when changes occur - TFS](https://docs.microsoft.com/en-us/vsts/work/track/alerts-and-notifications?view=tfs-2017)
* Content Source: [docs/work/track/alerts-and-notifications.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/work/track/alerts-and-notifications.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@ampac28 - Thank you for your inquiry. You can set up a notification at the project level for when a work item changes or is created and have it delivered to a specific email address or team group.  The method fo creating project-level notifications is similar to team-level notifications as documented here, https://docs.microsoft.com/en-us/vsts/notifications/manage-team-notifications?view=vsts.  You gain access to the project-level notifications through the Project Settings admin context.
