### ISSUE TITLE
Add Azure Resource Manager Service Connection

### ISSUE THREAD

**Issue by StevenTCramer** [MicrosoftDocs/vsts-docs#1442]
There is no documentation that I can find to explain the `Add Azure Resource Manager Service Connection` dialog.
No references to Service Principle Client ID, Service Principle Key, Tenant ID  etc.
The following blog helps to explain these items and where to find the answers but this should be documented in the VSTS docs.

https://medium.com/@roshanj/how-to-add-azure-resource-manager-service-endpoint-32af4dcadf3b

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72b90dd0-49f9-4ed4-3010-9a64dde6ae5a
* Version Independent ID: 6e679d50-4e94-eee3-8793-af884cc909ca
* Content: [Service connections in VSTS and Team Foundation Server](https://docs.microsoft.com/en-us/vsts/pipelines/library/service-endpoints?view=vsts#feedback)
* Content Source: [docs/pipelines/library/service-endpoints.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/library/service-endpoints.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment]
The topic has a list of connection types: https://docs.microsoft.com/en-us/vsts/pipelines/library/service-endpoints?view=vsts#common-service-connection-types and the link "For more information, see Create an Azure service connection" (https://docs.microsoft.com/en-us/vsts/pipelines/library/connect-to-azure?view=vsts). In addition, most topics that use the ARM connection type contain the same link: https://docs.microsoft.com/en-us/vsts/pipelines/targets/webapp?view=vsts&tabs=designer#azure-service-connection. The connection topic itself has some details about service principals, but also links to this blog post: https://blogs.msdn.microsoft.com/devops/2015/10/04/automating-azure-resource-group-deployment-using-a-service-principal-in-visual-studio-online-buildrelease-management/. I hope this helps to answer your question.

**Comment by StevenTCramer** [comment]
Eventually I got this to work.
https://docs.microsoft.com/en-us/vsts/pipelines/library/connect-to-azure?view=vsts

The Powershell script fails unless you enter a password of certain complexity.

The prompt says "password"  normally one would think is asking me for an existing password.  But it is asking you to create a password for the SPN.  

Getting help out of the ps command is far from intuitive.  You have to read the file to figure it out.

```
    [Parameter(Mandatory=$true, HelpMessage="Provide a password for SPN application that you would create; this becomes the service principal's security key")]
    [securestring] $password,
```
I would argue that the documentation and the User experience could still use some improvement.
11 not so simple to follow steps.
We can do better.
