### ISSUE TITLE
TFS new custom states.

### ISSUE THREAD

**Issue by Szczepanek** [MicrosoftDocs/vsts-docs#1445]
Hi.
I create new statuses in my User Story WIT with transition update.
The problem is that, when i change status e.g. from "Active" to "New Custom Status" TFS will move this US to some kind of limbo. Also, at kanban table, when I add new column and try to map column to Status, there are only the old one :/
How make TFS to detect new statuses?

**Comment by KathrynEE** [comment]
@Szczepanek - Thank you for your inquiry. I recommend you contact the [Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html) or [Support](https://www.visualstudio.com/team-services/support/).
