### ISSUE TITLE
Screenshots look to be pretty old. Does this need an update?

### ISSUE THREAD

**Issue by Tiberriver256** [MicrosoftDocs/vsts-docs#1447]
Screenshots look to be pretty old. Does this need an update?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b7a8d4a-fe62-f360-83ef-6ceb8e952dec
* Version Independent ID: b66cc33d-7f7b-5e3e-eb09-e84aebd7ac80
* Content: [Create your backlog and tasks using Project - VSTS & TFS](https://docs.microsoft.com/en-us/vsts/work/backlogs/office/create-your-backlog-tasks-using-project?view=vsts)
* Content Source: [docs/work/backlogs/office/create-your-backlog-tasks-using-project.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/work/backlogs/office/create-your-backlog-tasks-using-project.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@AStoker - Thank you for your feedback. While the screenshots may be old, the general procedures should work as written.  I've added an item to my backlog to update this article at a later date.

**Comment by Tiberriver256** [comment]
Thank you!
