### ISSUE TITLE
"DevOps Project for Java" link broken

### ISSUE THREAD

**Issue by turibbio** [MicrosoftDocs/vsts-docs#1449]
"DevOps Project for Java" link is broken

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 927483e2-5f90-755b-8009-6713f3a4f63f
* Version Independent ID: 2f4bc010-83bb-f485-c7a7-6cd516be05f1
* Content: [Get started with Java DevOps and VSTS](https://docs.microsoft.com/en-us/vsts/java/get-started?view=vsts)
* Content Source: [docs/java/get-started.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/java/get-started.md)
* Product: **devops**
* GitHub Login: @erickson-doug
* Microsoft Alias: **douge**

**Comment by steved0x** [comment]
@turibbio Here is the right link:

https://docs.microsoft.com/en-us/azure/devops-project/azure-devops-project-java

Somehow the `.md` file extension was added to the link in the TOC, I just fixed it and it should be live later today.

Thank you for letting us know
