### ISSUE TITLE
Managing Azure Secrets on GitHub

### ISSUE THREAD

**Issue by alex--thomas** [MicrosoftDocs/vsts-docs#1450]
There is a plugin that would be useful for doing a verifiable scan of GitHub for Azure secrets as part of the checklist process.
https://azure.microsoft.com/en-au/blog/managing-azure-secrets-on-github-repositories/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2ee135e3-2efc-3e1d-d0e7-58be674ce30f
* Version Independent ID: d0dc7e0c-d189-9491-1b37-b6a22a5adc98
* Content: [Migration checklist - VSTS Public Project](https://docs.microsoft.com/en-us/vsts/organizations/public/migration-checklist?view=vsts)
* Content Source: [docs/organizations/public/migration-checklist.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/public/migration-checklist.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
Added link to the blog post from the article.
