### ISSUE TITLE
No ability to add test case name in test run title when run automated tests from test plans in the Test hub VSTS and TFS

### ISSUE THREAD

**Issue by KiprovIgor** [MicrosoftDocs/vsts-docs#1452]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7b6c92a2-2f5c-e34e-f285-3e1a2a02604b
* Version Independent ID: 6f31f4c2-94ac-20eb-da01-e1d47f041945
* Content: [Run automated tests from test plans in the Test hub VSTS and TFS](https://docs.microsoft.com/en-us/vsts/test/run-automated-tests-from-test-hub?view=vsts)
* Content Source: [docs/test/run-automated-tests-from-test-hub.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/test/run-automated-tests-from-test-hub.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment]
Thank you for your feedback. I have passed this on to the product team for advice.

**Comment by KiprovIgor** [comment]
Thanks.

It would be nice to see the name of test case name (if single test) or test
suite name (if multiple tests) to be run on run title.
Now it looks not informative.



Best regards,
Igor Kiprov
Engineering department
            Kyiv, Ukraine
mob.  +380674670998
         +380950647339
Skype: igor.kiprov

**Comment by harishkragarwal** [comment]
@KiprovIgor kindly reach us at devops_tools@microsoft.com for an involved discussion. We want to understand few things better before we can comment one way or the other. Thanks.
