### ISSUE TITLE
Instructions out of date with new UI

### ISSUE THREAD

**Issue by AStoker** [MicrosoftDocs/vsts-docs#1453]
The new UI changes in VSTS result in this article being out of date. The search bar no longer has a drop down to select where to search.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 219de2f0-b98c-3fcf-dc0c-7518e913c944
* Version Independent ID: a7e93e0a-fece-4848-9f58-42aeac9700b4
* Content: [Search the Wiki - VSTS & TFS](https://docs.microsoft.com/en-us/vsts/project/wiki/search-wiki?view=vsts)
* Content Source: [docs/project/wiki/search-wiki.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/project/wiki/search-wiki.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@AStoker - Thank you for your feedback. I've added an item to my backlog to update this article.
