### ISSUE TITLE
Publish Code Coverage Task not parsing Cobertura file, saying "No code coverage results were found to publish"

### ISSUE THREAD

**Issue by Guitrum** [MicrosoftDocs/vsts-docs#1456]
Regarding the "Publish Code Coverage" task, I have an xml output file from Cobertura that I am trying to pass into this task, but even though the file is valid and the path is correct, it is not able to parse it. Is there something about the xml that is not allowing it to be read?

**Comment by Guitrum** [comment]
I was trying to use $(Build.SourcesDirectory) at the beginning of my path to the xml file. Turns out it will only work if you use $(System.DefaultWorkingDirectory). Closing the issue

**Comment by manishi2V** [comment]
I tried to use $(Build.SourcesDirectory) at the beginning of my path to the xml file. But still issue persist.
