### ISSUE TITLE
Cannot manage provisioned wiki like any git repo

### ISSUE THREAD

**Issue by JamesInDenver** [MicrosoftDocs/vsts-docs#1457]
The "Note" is not correct.  You cannot currently manage a provisioned wiki repo like any other repo (branch policies, PR, etc.).  The wiki repo does not show up under the project's repositories (in settings, code or API) and therefor branch policies cannot be set.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 361efecd-d973-82ed-1dd8-ca01afe12f5d
* Version Independent ID: 629f3af2-8218-e53c-45c3-0e40c03f2273
* Content: [Wiki repository files, structure, & conventions - VSTS & TFS](https://docs.microsoft.com/en-us/vsts/project/wiki/wiki-file-structure?view=vsts#order-file)
* Content Source: [docs/project/wiki/wiki-file-structure.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/project/wiki/wiki-file-structure.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@JamesInDenver - Thank you for the feedback. I will correct the topic.
