### ISSUE TITLE
How to check empty artifacts ?

### ISSUE THREAD

**Issue by DavidNorena** [MicrosoftDocs/vsts-docs#1458]
I have a CI Pipeline that with the use of conditions gives me 2 artifacts or just 1.

I need to publish both to different destinations is there a way to check if an artifact is empty and not to execute the distribution task but continue with subsecuent tasks ??

**Comment by steved0x** [comment]
@DavidNorena Thank you for your feedback. The issues in this repo are for documentation feedback, can you let me know what article this feedback/question goes with so I can assign it to the right author? Thank you.

**Comment by DavidNorena** [comment]
Dont worry thank you so much, I'm using a powershellscript to accomplish that, thank you !
