### ISSUE TITLE
Why VSTS  uses the terminology Features in Scrum 

### ISSUE THREAD

**Issue by MaqSaid** [MicrosoftDocs/vsts-docs#1459]
When using Scrum Methodology, the Epic has user stories then why you have features mapped to Epic. **(see section "Agile, CMMI, and Scrum" of this article)**

**Comment by steved0x** [comment]
@MaqSaid Thank you for the feedback, can you let me know what article you were reading so I can send the feedback to the right athor? Thank you.

**Comment by MaqSaid** [comment]
@steved0x  as requested https://docs.microsoft.com/en-us/vsts/work/work-items/guidance/choose-process?view=vsts. "See section "Agile, CMMI, and Scrum" of this article)"

**Comment by KathrynEE** [comment]
@MaqSaid - I'm not sure I fully understand your comment. Both Features and Epics are designated as portfolio backlogs, and provided to support [organizing your backlog](https://docs.microsoft.com/en-us/azure/devops/boards/backlogs/organize-backlog?view=vsts&tabs=new-nav) into parent-child relationships or groupings. That said, the idea is to map User Stories to Features (parent-child links) and Features to Epics. In general, you wouldn't map a User Story to an Epic.
