### ISSUE TITLE
Add a Xamarin Sample

### ISSUE THREAD

**Issue by dansiegel** [MicrosoftDocs/vsts-docs#1460]
would be fantastic if there was a Xamarin Sample showing a multi-agent configuration to build iOS, Android, UWP

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6cfd9f66-a0f8-8369-f19e-c3446c301bcd
* Version Independent ID: 4f666589-3917-3424-bd3b-83b658e3a56d
* Content: [Build a repository with YAML](https://docs.microsoft.com/en-us/vsts/pipelines/get-started-yaml?view=vsts&tabs=github)
* Content Source: [docs/pipelines/get-started-yaml.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/get-started-yaml.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by DavidStaheli** [comment]
Hi @dansiegel.  Thanks for posting this.  It took some time, but we will have a new [Xamarin language guide](https://docs.microsoft.com/en-us/vsts/pipelines/languages/xamarin?view=vsts) and sample repo available tomorrow, Wednesday, September 5.  We'll add more target platforms to it (like UWP) very soon.
