### ISSUE TITLE
Webhook Discord Support

### ISSUE THREAD

**Issue by KLD** [MicrosoftDocs/vsts-docs#1462]
Please add Discord support. 

I tried to set a discord webhook up as a Slack service, but it only works when I 'test' it. Can't save it since uri doesn't match slack's. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4dc61b61-ed67-8313-99d4-d736e7f48234
* Version Independent ID: 3e0fcf87-9744-cec8-24f8-9f68371959c6
* Content: [Integrate with service hooks](https://docs.microsoft.com/en-us/vsts/service-hooks/overview?view=vsts)
* Content Source: [docs/service-hooks/overview.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/service-hooks/overview.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by elbatk** [comment]
Hi @KLD ! Thanks for your feedback. For suggestions or ideas to the product, please feel free to post them on the VSTS UserVoice, where they're more likely to gain traction from other users and from the product team. Closing this ticket for now. 

P.S. I'd like discord integration too :)
