### ISSUE TITLE
Amazingly

### ISSUE THREAD

**Issue by ashfakm** [MicrosoftDocs/vsts-docs#1464]
This is very helpful, thank you so much.
Better you show screenshot of the last step, how you uncheck the access after right click. Any ways..
Thanks a ton! :) IT work for me

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ab53b3f-feac-34cf-960b-3adaf3a8fcfe
* Version Independent ID: 3a84e493-d7de-1946-2e8e-805d4d666018
* Content: [Git index.lock file](https://docs.microsoft.com/en-us/vsts/repos/git/git-index-lock?view=vsts)
* Content Source: [docs/repos/git/git-index-lock.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/repos/git/git-index-lock.md)
* Product: **devops**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
@ashfakm Thank you for the feedback and I am glad the article was able to help you. Could you share more details on the screenshot that you would like to see?

Thank you!

**Comment by ashfakm** [comment]
Hi Steve, what I mean is during commit when I get lock file error, I went in the .git folder and unlock 'index' file and it worked for me. 
![image](https://user-images.githubusercontent.com/41935167/43726016-e29867ec-9952-11e8-827a-0d56aee386d9.png)

**Comment by steved0x** [comment]
@ashfakm Thank you for the feedback. That is a good idea, and since your issue includes the screenshot, I won't include another copy in the article as people can find it here. Thank you for adding the screenshot and we are glad the article was helpful.
