### ISSUE TITLE
Drag and drop to other sprint from taskboard still possible?

### ISSUE THREAD

**Issue by mahilleb-msft** [MicrosoftDocs/vsts-docs#1465]
I'm struggling to find how to drag and drop from the Taskboard (not the back log) to a different sprint:

```
Dragging an incomplete item to the product backlog or to a future sprint updates the Iteration Path of all uncompleted child tasks to correspond to the product backlog iteration path or future sprint. 
You can drag-and-drop work items onto a sprint from any backlog or board. 
```

Is this still possible in the new UI? Where to find the sprint to drag the item onto?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e338b7ea-8e12-73db-1074-1b58644edfbf
* Version Independent ID: f3f40bdc-1fa7-75be-5c57-22e586b47199
* Content: [Update and monitor your scrum taskboard - VSTS & TFS](https://docs.microsoft.com/en-us/vsts/work/scrum/task-board?view=vsts&tabs=new-nav)
* Content Source: [docs/work/scrum/task-board.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/work/scrum/task-board.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@mahilleb-msft - In the New navigation, the only drag-and-drop to a different sprint is supported only from the product backlog with Planning turned on. See  https://docs.microsoft.com/en-us/vsts/work/scrum/assign-work-sprint?view=vsts&tabs=new-nav#assign-work-from-your-backlog-to-a-sprint.  The text you reference is for the old UI. 

You can quickly update a sprint for a task on the taskboard by adding that field to the cards.

**Comment by mahilleb-msft** [comment]
Thanks @KathrynEE , appreciate your response.
