### ISSUE TITLE
"Test results files" argument needs improved examples for Version 1 vs Version 2

### ISSUE THREAD

**Issue by ChadMcCaffery** [MicrosoftDocs/vsts-docs#1469]
Argument | Description
:-- | :--
Test results files | Use this to specify one or more test results files. - Version 1 of the task: You can use a single-folder wildcard (*) and recursive wildcards (**). For example, **/TEST-*.xml searches for all the XML files whose names start with TEST- in all subdirectories. Multiple paths can be specified, separated by a semicolon. - Version 2 of the task: Uses the minimatch patterns. For example, **/TEST-*.xml searches for all the XML files whose names start with TEST- in all subdirectories.

The examples provided above do not contrast the differences between task "Version 1" (wildcard) and "Version 2" (minimatch). It could be improved if the "Version 2" example showed how minimatch can use exclusion patterns, but not that "Version 1" cannot.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba91e46a-de53-c0c1-f7f7-c02e797d527c
* Version Independent ID: 6f478148-461f-694a-ed82-deb4d731854e
* Content: [VSTS and TFS Build and Test - Publish Test Results task](https://docs.microsoft.com/en-us/vsts/pipelines/tasks/test/publish-test-results?view=vsts)
* Content Source: [docs/pipelines/tasks/test/publish-test-results.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/test/publish-test-results.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment]
Thank you for your feedback. I will update the topic to include your recommendations.
