### ISSUE TITLE
Doesn't work after O365 1807 update.

### ISSUE THREAD

**Issue by L31a0rgana** [MicrosoftDocs/vsts-docs#1470]
Dragging and dropping items from the side panel onto my slide doesn't do anything. Completely broken.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eb85ca92-338c-759e-d562-2c0e6f62f406
* Version Independent ID: ca73aa57-f5a2-8ab1-6524-dfcc5023eec3
* Content: [Storyboard your ideas with PowerPoint - VSTS & TFS](https://docs.microsoft.com/en-us/vsts/work/backlogs/office/storyboard-your-ideas-using-powerpoint?view=vsts#feedback)
* Content Source: [docs/work/backlogs/office/storyboard-your-ideas-using-powerpoint.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/work/backlogs/office/storyboard-your-ideas-using-powerpoint.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@L31a0rgana - thank you for the feedback. Please report this issue here https://developercommunity.visualstudio.com/spaces/21/index.html.
