### ISSUE TITLE
Badge URL has an extra ']' in the Markdown

### ISSUE THREAD

**Issue by ctstone** [MicrosoftDocs/vsts-docs#1471]
Remove trailing ']' in the badge URL sample

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 75a10513-2af9-8e16-61a4-25d4b09f6d32
* Version Independent ID: 788acaa2-d5a1-1d0d-18f4-e94a4e2fe2c9
* Content: [Build your GitHub repository](https://docs.microsoft.com/en-us/vsts/pipelines/build/ci-build-github?view=vsts&tabs=designer)
* Content Source: [docs/pipelines/build/ci-build-github.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/build/ci-build-github.md)
* Service: **vsts**
* Product: **devops**
* GitHub Login: @mlearned
* Microsoft Alias: **mlearned**

**Comment by mlearned** [comment]
@ctstone  @steved0x  ill have a look and be back.
