### ISSUE TITLE
Not all info on this page is available in TFS 2015

### ISSUE THREAD

**Issue by varnk** [MicrosoftDocs/vsts-docs#1475]
The top of the page indicates that the information presented here should be in TFS 2015, but that is not the case.  Some screen content shown on this page is not available in TFS 2015.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94cca257-5f81-190e-b50c-7b7f69217234
* Version Independent ID: 1d84dc61-a8bb-b45a-6c93-5bec211c19a5
* Content: [Review continuous test results after a build VSTS and TFS](https://docs.microsoft.com/en-us/vsts/pipelines/test/review-continuous-test-results-after-build?view=vsts)
* Content Source: [docs/pipelines/test/review-continuous-test-results-after-build.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/test/review-continuous-test-results-after-build.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment]
Thank you for your comment. I will update the topic to include your feedback.
