### ISSUE TITLE
Third party extensions security concerns

### ISSUE THREAD

**Issue by TimTMM** [MicrosoftDocs/vsts-docs#1476]
Can Microsoft vouch for these third party extensions? Have they been properly tested to make sure there are no security concerns when installed in an enterprise environment?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 46849bf5-07ed-62cd-66a5-2ebabe449855
* Version Independent ID: d12ad05e-4348-f13a-ea35-7bb4761c3b0b
* Content: [Install extensions for Visual Studio Team Foundation Server (TFS)](https://docs.microsoft.com/en-us/vsts/marketplace/get-tfs-extensions?view=tfs-2018#feedback)
* Content Source: [docs/marketplace/get-tfs-extensions.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/marketplace/get-tfs-extensions.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by elbatk** [comment]
Hi @TimTMM , this feedback area is for the VSTS documentation. Please use the [VSTS UserVoice](https://visualstudio.uservoice.com/forums/330519-visual-studio-team-services) to submit feature ideas or the [VSTS Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html) to submit product bugs.
