### ISSUE TITLE
Scaled Agile Framework with multiples Azure subscriptions

### ISSUE THREAD

**Issue by luisvaladares** [MicrosoftDocs/vsts-docs#1478]
Hi, 

This article doesn’t describe SAFe with multiples azure accounts. Image that, you're working with multiple clients and need separate bills and use SAFe for streaming all work items in your organization. How could it work?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c1cb521-d930-b7da-6568-4577d2d72487
* Version Independent ID: affd6426-51a1-da62-a008-97c751acd1e7
* Content: [Scaled Agile Framework - VSTS & TFS](https://docs.microsoft.com/en-us/vsts/work/scale/scaled-agile-framework?view=vsts)
* Content Source: [docs/work/scale/scaled-agile-framework.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/work/scale/scaled-agile-framework.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by danhellem** [comment]
Sorry - Azure DevOps does not currently have a good solution to support SAFe across several organizations (accounts)
