### ISSUE TITLE
Not working on Windows

### ISSUE THREAD

**Issue by RonMcgonagall** [MicrosoftDocs/vsts-docs#1479]
Hello !

I don't know what I am doing wrong. I have put this in my CI pipeline and everything work fine for my iOS build. However, when trying to build for Android i get the following error :

Unable to locate executable file: 'bash'. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also verify the file has a valid extension for an executable file.

I have install Git (with Git-bash) on my agent and have set Path=C:\Program Files\Git\git-bash.exe

I have also tried with a shellScript and I have the same issue :

Failed which: Not found bash: null

Bash failed with error: Failed which: Not found bash: null

Any help on this ?

Thanks !

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 450ac349-5c33-6cdf-1ecd-6eb989a00334
* Version Independent ID: a7119c1a-59b2-3081-a241-e93aa0d6b4b9
* Content: [Bash](https://docs.microsoft.com/en-us/vsts/pipelines/tasks/utility/bash?view=vsts)
* Content Source: [docs/pipelines/tasks/utility/bash.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/utility/bash.md)
* Product: **devops**
* GitHub Login: @erickson-doug
* Microsoft Alias: **dastahel**

**Comment by vtbassmatt** [comment]
Hello @RonMcgonagall - can you move this question over to https://github.com/microsoft/azure-pipelines-yaml/issues ? It doesn't look like a doc issue.

When you do, please include the pipeline definition and whether you're using a hosted pool or a private agent. Thanks.

**Comment by timendez** [comment]
@vtbassmatt I believe this _is_ a doc issue. Bash isn't installed on the Windows build machines. Here is a thread that shows that the documentation should be updated to show that you can't execute bash scripts on Windows - https://github.com/microsoft/azure-pipelines-tasks/issues/9094#issuecomment-451364044

**Comment by vtbassmatt** [comment]
@timendez that thread is about the Azure CLI. Bash scripts can absolutely be executed from Azure Pipelines running on Windows; I do it all the time.
