### ISSUE TITLE
Automating the test association

### ISSUE THREAD

**Issue by Malba0** [MicrosoftDocs/vsts-docs#1480]
Is there any way to automate (script) the association of tests with test cases? With PowerShell I was able to create new test cases in TFS but have not yet found a way to make the association between the TFS test cases and Selenium test written for that purpose.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7d8a7e40-73d6-795f-7b8c-77104ef606e8
* Version Independent ID: 8f15995b-bd94-8d9f-1e8b-82f1f364d221
* Content: [Associate an automated test with a test case](https://docs.microsoft.com/en-us/vsts/test/associate-automated-test-with-test-case?view=vsts)
* Content Source: [docs/test/associate-automated-test-with-test-case.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/test/associate-automated-test-with-test-case.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment]
Thank you for your feedback. I have passed this on to the product team for advice.

**Comment by wurzelkuchen** [comment]
Actually you can use the VSTS REST API. Below code works fine for me.

        private void AddTestCaseLinkToVSTSTest(MethodBase methodBase)
        {
            using (HttpClient client = new HttpClient())
            {
                client.DefaultRequestHeaders.Accept.Add(
                    new System.Net.Http.Headers.MediaTypeWithQualityHeaderValue("application/json-patch+json"));

                client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue(
                    "Basic", this.authString);

                var method = new HttpMethod("PATCH");

                string fullMethodName = methodBase.DeclaringType.FullName + "." + methodBase.Name;

                JArray operationsArray = new JArray();
                this.AddAddFieldToOperationsArray(operationsArray, "add", "/fields/Microsoft.VSTS.TCM.AutomatedTestName", fullMethodName);
                this.AddAddFieldToOperationsArray(operationsArray, "add", "/fields/Microsoft.VSTS.TCM.AutomatedTestStorage", System.Reflection.Assembly.GetExecutingAssembly().GetName().Name + ".dll");
                this.AddAddFieldToOperationsArray(operationsArray, "add", "/fields/Microsoft.VSTS.TCM.AutomatedTestId", Guid.NewGuid().ToString());
                this.AddAddFieldToOperationsArray(operationsArray, "add", "/fields/Microsoft.VSTS.TCM.AutomatedTestType", "Unit Test");
                this.AddAddFieldToOperationsArray(operationsArray, "add", "/fields/Microsoft.VSTS.TCM.AutomationStatus", "Automated");

                JavaScriptSerializer serializer = new JavaScriptSerializer();

                string body = operationsArray.ToString();
                string url = VSTSTestExecutor.GetConfigParam(this.options, "vsts.workItemUpdateUrl", "https://XXXXXX.visualstudio.com/DefaultCollection/_apis/wit/workitems/");
                var request = new HttpRequestMessage(method, $"{url}{this.workitemID}?api-version=1.0")
                {
                    Content = new StringContent(body, Encoding.UTF8, "application/json-patch+json")
                };

                HttpResponseMessage response = new HttpResponseMessage();
                response = client.SendAsync(request).Result;

                response.EnsureSuccessStatusCode();
            }
        }

**Comment by cltshivash** [comment]
@wurzelkuchen What you have done would work for MSTest framework. The FQN (fullyqualifiedname) implementation today is specific to a test adapter and framework. It varies between NUnit, xUnit and MSTest. Are you looking to automate the association ? Also there's association is not a pre-requisite to run tests in the pipeline.

**Comment by deborahdcarlo** [comment]
If we can insert parameters to run different scenarios into a test case, shouldn't it be possible to associate more than one test method to a test case?

**Comment by rasimavci** [comment]
I have few questions. 
I use TFS and I can not see same Test Explorer screen when I click Test. 
I want to Associate a coded UI to my test but I can not see that option when I right click to test.
I connected to a project but dont know which branch fetched, how can I know ?
Shoul I code the coded ui test in same project and main branch ?
Is it possible to associate test to a coded ui test that is in my local ?

**Comment by PBoraMSFT** [comment]
@rasimavci - which version of VS are you on? Association is available only through VS, not in the TFS / VSTS web-access.
