### ISSUE TITLE
Issue: Cannot choose nuget.org as Upstream

### ISSUE THREAD

**Issue by glatzert** [MicrosoftDocs/vsts-docs#1481]
This item seems not to apply to TFS 2018.2, since I cannot choose nuget as upstream source

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 504c808f-ddc0-fc0a-e63a-aeebf6924863
* Version Independent ID: 97568baa-5a4f-8741-5d69-47fb65ab105a
* Content: [Use packages from nuget.org](https://docs.microsoft.com/en-us/vsts/package/nuget/upstream-sources?view=vsts)
* Content Source: [docs/package/nuget/upstream-sources.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/package/nuget/upstream-sources.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by elbatk** [comment]
Adding @alexmullans to help out here :)

**Comment by alexmullans** [comment]
Currently, [all feeds created before TFS 2018 Update 2](https://docs.microsoft.com/en-us/vsts/package/reference/feed-upgrade-learn-more?view=vsts) are unable to use the nuget.org upstream source. The ability to upgrade "legacy feeds" to use the nuget.org upstream source will come in the next major release of TFS. In the meantime, you can use it by creating a new feed.

@elbatk can you add a small note to the doc for which @glatzert opened this issue clarifying this and linking to the package I linked above?

**Comment by elbatk** [comment]
Updating it as we speak! Closing this issue for now, I hope this helps @glatzert , feel free to reach back out if you have any more questions.
