### ISSUE TITLE
Errata? where Azure AD groups are added

### ISSUE THREAD

**Issue by SCordesHum** [MicrosoftDocs/vsts-docs#1483]
Should "by adding Azure AD groups to TFS groups" be "by adding Azure AD groups to VSTS groups"?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a830bcfa-4584-922f-f28c-531cb59a454e
* Version Independent ID: 4f288fb1-78b1-0339-6627-316f6fb7686a
* Content: [Understand differences between VSTS and TFS](https://docs.microsoft.com/en-us/vsts/user-guide/about-vsts-tfs?view=vsts)
* Content Source: [docs/user-guide/about-vsts-tfs.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/user-guide/about-vsts-tfs.md)
* Product: **devops**
* GitHub Login: @erickson-doug
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@SCordesHum - Thank you for the correction. I will update the topic accordingly.
