### ISSUE TITLE
remove unnecessary web config after xml transformation

### ISSUE THREAD

**Issue by RomanKernSW** [MicrosoftDocs/vsts-docs#1487]
If i publish the .net framework web application with IIS Web App Deploy, I have to add all web.*.config files as content and let them copy into the bin folder for xml transformation. The problem is, that after the deployment, I do have all web.*.config files on one stage.Is their any option that delete unnecessary web config files?

**Comment by steved0x** [comment]
@RomanKernSW Thank you for your feedback. Can you let me know to which article this feedback applies so I can send it to the right author?

Thank you.

**Comment by RomanKernSW** [comment]
Hello, @steved0x 
[its about the IIS Deploy Tool](https://docs.microsoft.com/en-us/vsts/pipelines/tasks/transforms-variable-substitution?view=vsts)

The transformation itself works, but it would be nice, if the tool can automatically remove all unused web.config files

**Comment by steved0x** [comment]
@RomanKernSW Thank you for the additional information. The issues in this repo are for content feedback, and this is a product feedback. For product feedback, including feature requests, please file an issue here: https://developercommunity.visualstudio.com/spaces/21/index.html

Thank you.
