### ISSUE TITLE
TFS Client library issue

### ISSUE THREAD

**Issue by jjones82** [MicrosoftDocs/vsts-docs#1493]
The TFS Client libraries link takes you to a nuget package for "Microsoft.TeamFoundationServer.Client" version 15.112.1 which requires dependency "Microsoft.Tpl.Dataflow" which is no longer available. (https://www.nuget.org/packages/Microsoft.Tpl.Dataflow/4.5.20 - "The owner has unlisted this package. This could mean that the package is deprecated or shouldn't be used anymore.")

I can install the latest prerelease version by utilizing the prerelease parameter of install-module to work around the issue. Can we get a stable release of Microsoft.TeamFoundationServer.Client since the dependency for the current release is no longer available?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4abeff84-74e7-7fd3-db28-fa92683143c8
* Version Independent ID: 9d289096-4cf9-cb30-0893-e9ae5a72a34d
* Content: [REST API samples for VSTS and Team Foundation Server](https://docs.microsoft.com/en-us/vsts/integrate/get-started/rest/samples?view=vsts)
* Content Source: [docs/integrate/get-started/rest/samples.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/integrate/get-started/rest/samples.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by eriawan** [comment]
@jjones82 

The nuget package of Microsoft.Tpl.DataFlow is still there to get/download, although it is not listed. So you can still install the nuget package safely.

For more information, please refer to this dotnet/corefx#24547

**Comment by elbatk** [comment]
Closing this issue for now, thanks @eriawan
