### ISSUE TITLE
Docker agent

### ISSUE THREAD

**Issue by edwinpjacques** [MicrosoftDocs/vsts-docs#1494]
You should add some content or link to another page that describes how to get a docker agent up.  I found that to be easier than downloading/installing/configuring agents.  Also, if you use docker-compose, you can easily specify how many replicas you want to run on a host.

Create ```vsts-agent.env``` file with the following contents:
```
VSTS_TOKEN=<PersonalAccessToken>
VSTS_ACCOUNT=<Account>
```

Create ```vsts-agent.yml``` file with the following contents:
```
version: '3.7'
services:
  vsts-agent:
    image: microsoft/vsts-agent:latest
    deploy:
      replicas: 4
    env_file:
      - vsts-agent.env
```

The first time will require the following setup:
``` bash
docker swarm init
```

Finally, deploy the stack.  The agents will be started immediately, and automatically started when the system boots.
``` bash
docker stack deploy --compose-file vsts-agent.yml vsts-agent
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 23328b13-f079-ad21-5d7a-6c640f25391c
* Version Independent ID: 4a39889d-fa00-ae2b-aa43-f358631b7b1a
* Content: [Deploy a build and release agent on Linux](https://docs.microsoft.com/en-us/vsts/pipelines/agents/v2-linux?view=vsts&viewFallbackFrom=vsts).)
* Content Source: [docs/pipelines/agents/v2-linux.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/agents/v2-linux.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by vtbassmatt** [comment]
This is a great idea.

**Comment by vtbassmatt** [comment]
This is coming soon. Commenting to remove the stale tag :)

**Comment by vtbassmatt** [comment]
I am the absolute worst at following up. This has been published for weeks now: http://docs.microsoft.com/azure/devops/pipelines/agents/docker

**Comment by edwinpjacques** [comment]
Hey, at least you did!  Thanks, I appreciate it.

--Edwin

--
Edwin Jacques
Solution Consultant Staff
Office: +1 (508) 713-5864

“Our highest priority is to satisfy the customer through early and continuous delivery of valuable solutions.”
– Principles Behind the Agile Manifesto<http://agilemanifesto.org/principles.html> #1
