### ISSUE TITLE
ETIMEDOUT connect ETIMEDOUT failure on microsoft hosted agents while running tests in browserstack.

### ISSUE THREAD

**Issue by ShaifaliKhera** [MicrosoftDocs/vsts-docs#1495]
I have an automation framework in Protractor with Jasmine. And I’m trying to trigger browserstack tests from Microsoft hosted agent (e.g. “Hosted vs2017”) through vsts task within a release definition. But as soon as the spec file has more than few tests, its start getting “ETIMEDOUT connect ETIMEDOUT 207.254.56.15” error and as per my observation, the ip address within the error is that of the hub.browserstack.com server sitting in US. We don’t have any proxy or firewall as the tests fail at random places but everytime.

The test runs fine if I host the same agent from my machine. It seems to be related to Microsoft hosted VMs when spin up automatically in VSTS.

**Comment by steved0x** [comment]
@andyjlewis Can you help route this one?

**Comment by alexhomer1** [comment]
Thank you for your feedback. I have passed this on to the product team for advice.

**Comment by PBoraMSFT** [comment]
@ShaifaliKhera - this repo is for doc issues only. You have already reported this one on the tasks repo as well. https://github.com/Microsoft/vsts-tasks/issues/7880 
Closing this one out.
