### ISSUE TITLE
real life example for creating epic , features and product backlog

### ISSUE THREAD

**Issue by abhiindian** [MicrosoftDocs/vsts-docs#1496]
Request you to kindly provide real life example so that I will be more understandable how to use the scrum process

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f3f7d82-e5db-1cce-9205-757478f6376a
* Version Independent ID: 5635fab0-4e32-e76a-399e-9542a4e8c0b2
* Content: [Scrum process work items types & workflow - VSTS & TFS](https://docs.microsoft.com/en-us/vsts/work/work-items/guidance/scrum-process-workflow?toc=/vsts/work/work-items/toc.json&bc=/vsts/work/breadcrumb/toc.json&view=vsts)
* Content Source: [docs/work/work-items/guidance/scrum-process-workflow.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/work/work-items/guidance/scrum-process-workflow.md)
* Product: **devops**
* GitHub Login: @erickson-doug
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@abhiindian - Thank you for your inquiry and apologies for the delayed response. Some examples of using Epics and Features can be seen in this topic, https://docs.microsoft.com/en-us/azure/devops/boards/plans/scaled-agile-framework.
