### ISSUE TITLE
The "Run Functional Tests" and "Visual Studio Test Agent Deployment" tasks have been deprecated, but the documentation is still active

### ISSUE THREAD

**Issue by samsmithnz** [MicrosoftDocs/vsts-docs#150]
See https://docs.microsoft.com/en-us/vsts/build-release/test/continuous-test-selenium. The documentation should be replaced to use "Visual Studio Test".

**Comment by steved0x** [comment]
@samsmithnz Thank you for letting us know, I have forwarded this to the author of that article and I will report back here once it is fixed. Thank you.

**Comment by alexhomer1** [comment]
Thank you. We are currently updating the documentation overall with regard to the two deprecated tasks. An updated Selenium topic will be created as soon as possible, incorporating the new features of the VS Test task and the updated build and release agent capabilities.
