### ISSUE TITLE
unable to use link https://dl.microsoft.com/eclipse

### ISSUE THREAD

**Issue by brewmanz** [MicrosoftDocs/vsts-docs#1504]
When I select link to https://dl.microsoft.com/eclipse/
I get "You do not have permission to view this directory or page."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9419941b-8945-9d1a-b7b8-828ab950fdb6
* Version Independent ID: 00263573-2be4-aca9-8a51-0a5f15febb0a
* Content: [Get the Eclipse Plug-in for VSTS & TFS support](https://docs.microsoft.com/en-us/vsts/java/download-eclipse-plug-in?view=vsts#_install-the-tee-plugin-for-eclipse)
* Content Source: [docs/java/download-eclipse-plug-in.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/java/download-eclipse-plug-in.md)
* Product: **devops**
* GitHub Login: @erickson-doug
* Microsoft Alias: **douge**

**Comment by steved0x** [comment]
@brewmanz That link is just used inside the IDE for Eclipse when installing the plug-in (more details at step 4 [here](https://docs.microsoft.com/en-us/vsts/java/labs/eclipsegit/index?view=vsts#connect-to-vsts-from-eclipse), to read about the plug-in, you can use: https://marketplace.eclipse.org/content/team-explorer-everywhere. Sorry for the confion, I'll see if I can update this page to clarify. Thank you.

**Comment by dlandonjr** [comment]
you can drop the "s" and use "http" and it works with the above URL:
http://dl.microsoft.com/eclipse/
