### ISSUE TITLE
No documentation on supported input types for task.json

### ISSUE THREAD

**Issue by deadlydog** [MicrosoftDocs/vsts-docs#1506]
I'm developing a VSTS Build/Release extension and am looking for a list of acceptable input types that are allowed in the task.json file. I would've expected to find something about it [here](https://docs.microsoft.com/en-us/vsts/extend/develop/build-task-schema?view=vsts), but there's nothing there, and I can't seem to find this information anywhere else on the documentation site.

The closest thing I have found is [this page](https://docs.microsoft.com/en-us/vsts/extend/develop/add-build-task?view=vsts#createmetadata) that shows a sample task.json file, and how to have inputs of type `string` and `boolean`.

I also found [this stackoverflow post](https://stackoverflow.com/a/48170743/602585) that lists a few more, but it would be nice to have something more "official" on the approved documentation site.

**Comment by deadlydog** [comment]
It looks like this issue may be the same as #1345

**Comment by elbatk** [comment]
Hey @deadlydog , it looks like that task schema that is linked in the similar issue is the best place to find what you're looking for!
