### ISSUE TITLE
TFS multiple custom conditions

### ISSUE THREAD

**Issue by Sentinel3d** [MicrosoftDocs/vsts-docs#1507]
Is there a way to trigger it when it is from the branch 'master' or any branch in the release folder
![image](https://user-images.githubusercontent.com/6570499/43957139-0e4f36b6-9ca7-11e8-8c2b-3181a9d7f151.png)

i'm only getting this far:
`and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))`

Is it also possible to invert this?
so to trigger it when it is not master or an release branch

**Comment by steved0x** [comment]
@elbatk Can you help get this feedback to the right place?

**Comment by steved0x** [comment]
@Sentinel3d Sorry about momentarily closing this issue, I accidentally clicked the wrong button. This issue is still open and we are getting the feedback routed to the right author.

**Comment by eriawan** [comment]
@Sentinel3d 

It is possible to invert your requirement.

From your original:

`and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))`

change that to:

`and(succeeded(), ne(variables['Build.SourceBranch'], 'refs/heads/master'))`

This will evaluate to all sourcebranch not equal to `'refs/heads/master'`. And **ne** means not equal, an opposite of **eq**.
See also: https://docs.microsoft.com/en-us/vsts/pipelines/process/conditions?view=vsts#general-functions

**Comment by Sentinel3d** [comment]
yes i already have that. But i need: "Is there a way to trigger it when it is from the branch 'master' or any branch in the release folder"

**Comment by eriawan** [comment]
@Sentinel3d 
> Is there a way to trigger it when it is from the branch 'master' or any branch in the release folder"

Unfortunately, as far as I know, no.
You need to define branch policies on specific branch one by one for that.

Maybe @elbatk could help?

**Comment by elbatk** [comment]
Uhm, I think I may be a bit out of my expertise here (and also sorry for the huge delay, doing backlog cleaning). If you haven't resolved this issue, please post it to the [Azure DevOps Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html), as it's monitored by the product team!
