### ISSUE TITLE
This doc seems different from the task.

### ISSUE THREAD

**Issue by jgaston5** [MicrosoftDocs/vsts-docs#1508]
Looking at the task source here https://github.com/Microsoft/vsts-tasks/blob/master/Tasks/PublishBuildArtifactsV1/task.json. There does not appear to be a "PublishLocation" input in the JSON and this doc to be missing the "ArtifactType" input that is there in the JSON.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b3f565b-88e4-88d6-a534-48ec21e6e3d8
* Version Independent ID: 9fca89ae-4a6e-a43a-2834-1a91ad44c256
* Content: [Publish Build Artifacts](https://docs.microsoft.com/en-us/vsts/pipelines/tasks/utility/publish-build-artifacts?view=vsts)
* Content Source: [docs/pipelines/tasks/utility/publish-build-artifacts.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/utility/publish-build-artifacts.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by ahaleiii** [comment]
A snippet from https://github.com/Microsoft/vsts-tasks/blob/master/Tasks/PublishBuildArtifactsV1/task.json linked above:

```json

    {
      "name": "ArtifactType",
      "aliases": [ "publishLocation" ],
      "type": "pickList",
      "label": "Artifact publish location",
      "defaultValue": "Container",
      "required": true,
      "helpMarkDown": "Choose whether to store the artifact in Visual Studio Team Services/TFS, or to copy it to a file share that must be accessible from the build agent.",
      "options": {
        "Container": "Visual Studio Team Services/TFS",
        "FilePath": "A file share"
      }
    },
```

It looks like "PublishLocation" is an alias for "ArtifactType". I think they're the same thing. It shows up in VSTS with the label "Artifact publish location":

![image](https://user-images.githubusercontent.com/7021001/45643715-b6811980-ba89-11e8-9876-da392d09430f.png)

**Comment by elbatk** [comment]
I'm going to go ahead and close this, as @ahaleiii has answered the question. publishLocation is the same as "ArtifactType".
