### ISSUE TITLE
Issue with link to doc page on creating Azure container registry

### ISSUE THREAD

**Issue by sandra-walters** [MicrosoftDocs/vsts-docs#1511]
In the initial example given in this document, there's a link within the following text: "make sure that you have pre-created the registry in Azure portal."  This link is broken.  Examining the link address shows that the intended link was pasted inside another link, perhaps.  (Or maybe this link once existed in this format and now is no longer functional?)  In any event, clicking on the link produces a 404 at this point.  

It looks like the intended target was: https://docs.microsoft.com/en-us/azure/container-registry/container-registry-get-started-portal

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e825c07d-2168-c0aa-782a-ef6f9c7ba95e
* Version Independent ID: 5cb6926b-215a-bf89-8e63-b2e1129e41df
* Content: [Docker](https://docs.microsoft.com/en-us/vsts/pipelines/languages/docker?view=vsts&tabs=yaml)
* Content Source: [docs/pipelines/languages/docker.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/languages/docker.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by andyjlewis** [comment]
Thanks for reporting the issue. Checked just now and the link seems to be working.

**Comment by sandra-walters** [comment]
Interesting.  It still produces a 404 for me.
  
To be clear - the broken link in the source document is this: [https://github.com/MicrosoftDocs/vsts-docs/blob/master/azure/container-registry/container-registry-get-started-portal](url)

That location doesn't appear to exist.

**Comment by andyjlewis** [comment]
I see that too. But all instances of the link seem to be working OK in the rendered page: https://docs.microsoft.com/en-us/azure/devops/pipelines/languages/docker
