### ISSUE TITLE
Check if only the previous release task has succeeded

### ISSUE THREAD

**Issue by piepege** [MicrosoftDocs/vsts-docs#1512]
I want to check if the previous task in a release was succesful. So I CAN'T use the option "Only when all previous tasks have succeeded" in Run this task, inside the Control Options. Because this checks ALL the previous tasks. What I actually want is the option "Only when THE previous task has susseeded". Is there a way to accomplish this?

**Comment by vtbassmatt** [comment]
There's no generic way to accomplish this. If the task happens to do something to the environment such as a variable or a file, you could detect that using a script.
