### ISSUE TITLE
Build number badge

### ISSUE THREAD

**Issue by mamoorkhan** [MicrosoftDocs/vsts-docs#1515]
is it possible to have badge which shows the build number or branch name deployed to different environments?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 75a10513-2af9-8e16-61a4-25d4b09f6d32
* Version Independent ID: 788acaa2-d5a1-1d0d-18f4-e94a4e2fe2c9
* Content: [Build your GitHub repository](https://docs.microsoft.com/en-us/vsts/pipelines/build/ci-build-github?view=vsts&tabs=yaml#add-a-build-status-badge)
* Content Source: [docs/pipelines/build/ci-build-github.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/build/ci-build-github.md)
* Service: **vsts**
* Product: **devops**
* GitHub Login: @mlearned
* Microsoft Alias: **mlearned**

**Comment by DavidStaheli** [comment]
FYI @moswald

**Comment by moswald** [comment]
@mamoorkhan you say "deployed", are you talking about for a Release? If so, that's some future work that is planned, but not scheduled.

**Comment by mamoorkhan** [comment]
@moswald Yes, I am talking about release environments, let's say I have 5 environments in a single release, I would like to know from badges, which of the environment currently holds which build from which branch. If that could be possible, it would be awesome.

**Comment by moswald** [comment]
We are going to be adding multi-stage yaml pipelines with Release Management support, at which time you should be able to do this with the current status badge api. I know adding this functionality to the current Release Management offering is on their backlog, but I don't know if it's scheduled.
