### ISSUE TITLE
"Associated Automation" Grayed-Out on VSTS Test Case

### ISSUE THREAD

**Issue by wgv-srsedate** [MicrosoftDocs/vsts-docs#1516]
When I open a test case in VSTS, and go to the "Associated Automation" tab, all the fields and buttons are grayed out.  I am a project collection administrator, and have full privileges.  Why are they grayed out, and how do I manually associate a test case with code from the VSTS hub?  I got to this problem by following your test association documentation steps for people using Visual Studio 2015.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7d8a7e40-73d6-795f-7b8c-77104ef606e8
* Version Independent ID: 8f15995b-bd94-8d9f-1e8b-82f1f364d221
* Content: [Associate an automated test with a test case](https://docs.microsoft.com/en-us/vsts/test/associate-automated-test-with-test-case?view=vsts)
* Content Source: [docs/test/associate-automated-test-with-test-case.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/test/associate-automated-test-with-test-case.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment]
Thank you for your feedback. I have passed this on to the product team for advice.

**Comment by alexhomer1** [comment]
You must associate tests using Visual Studio. This cannot be done from the VSTS Test hub. See https://docs.microsoft.com/en-us/vsts/test/associate-automated-test-with-test-case?view=vsts

**Comment by wgv-srsedate** [comment]
Thanks for the clarification.  However, that seems contradictory to the documentation, specifically under the steps for "If you are using Visual Studio 2015 or earlier, follow these steps to associate your tests."  Those steps instruct you to associate tests from the VSTS Test hub.  If that's not the case, the documentation needs to be updated.

**Comment by alexhomer1** [comment]
Thank you. Yes, we will be updating this topic soon.

**Comment by minuz** [comment]
Hi, I'm not sure if its related or not, but since VSTS changed its name to AzureDevOps, I lost the ability to associate the test cases on my VSTS. 

I'm connected to my project from VS2017 and the associated test case are greyed out for me atm.

**Comment by alexhomer1** [comment]
Thank you for your feedback. I have passed this on to the product team for advice.

**Comment by harishkragarwal** [comment]
@minuz change to Azure DevOps is a branding change. No product functionality should be impacted because of that. Do reach us at devops_tools@microsoft.com with details so we can take a look at your case in specific.
