### ISSUE TITLE
"Where can I learn about batch files?" link is dead

### ISSUE THREAD

**Issue by Xamanthas** [MicrosoftDocs/vsts-docs#1518]
The link to where you can learn about batch files is dead (http://www.microsoft.com/resources/documentation/windows/xp/all/proddocs/en-us/batch.mspx?mfr=true).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 96dafbb6-b4ba-d4ab-7468-55e6df71b5e1
* Version Independent ID: 634b0719-9641-59fd-9f6f-f3a2082f9b39
* Content: [Batch script](https://docs.microsoft.com/en-us/vsts/pipelines/tasks/utility/batch-script?view=vsts)
* Content Source: [docs/pipelines/tasks/utility/batch-script.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/utility/batch-script.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by eriawan** [comment]
@Xamanthas 

good catch! I know the link to the documentation of Windows batch files including the commands.

I'm submitting the update now.

**Comment by eriawan** [comment]
PR submitted: #1519

cc @andyjlewis

**Comment by eriawan** [comment]
Umm... @steved0x 

Please confirm about my PR related to this issue.

It's been sitting there for a week, and no reply/feedback at all, other than confirmation from @Xamanthas that the updated link in the PR is correct.
