### ISSUE TITLE
wrong style for referencing images

### ISSUE THREAD

**Issue by mapfel** [MicrosoftDocs/vsts-docs#1524]
most of the references to embed images start with double round-brackets "((" in the link-part: ![foo]((bar) 
So these images aren't displayed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad73cae9-9b23-078d-2b95-d83cc794df03
* Version Independent ID: 3aa17c7d-adca-6ca6-b1e0-e811f520b325
* Content: [Show bugs on backlogs and boards - VSTS & TFS](https://docs.microsoft.com/en-us/vsts/organizations/settings/show-bugs-on-backlog?view=vsts)
* Content Source: [docs/organizations/settings/show-bugs-on-backlog.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/settings/show-bugs-on-backlog.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@mapfel - Thank you for the feedback. I'm in the process of correcting the topic.
