### ISSUE TITLE
Adjust order of backlog items along order of process type

### ISSUE THREAD

**Issue by mapfel** [MicrosoftDocs/vsts-docs#1525]
current: Depending on the process chosen to create your project—Agile, Scrum, or CMMI— the items in your backlog may be called product backlog items (PBIs), user stories, or requirements.
suggestion for improvement: Depending on the process chosen to create your project—Agile, Scrum, or CMMI— the items in your backlog may be called user stories, product backlog items (PBIs), or requirements.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 58aacca7-05a2-e8dd-6a6f-3025d734ef20
* Version Independent ID: 3eea19c1-8bda-6b60-e77d-8c0e82c3f096
* Content: [Create & manage bugs using Agile tools - VSTS & TFS](https://docs.microsoft.com/en-us/vsts/boards/backlogs/manage-bugs?view=vsts&tabs=new-web-form)
* Content Source: [docs/boards/backlogs/manage-bugs.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/boards/backlogs/manage-bugs.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@mapfel - Thank you for the feedback. I'm updating several articles to correct the order of items.
