### ISSUE TITLE
TFS licensing overbooking

### ISSUE THREAD

**Issue by carloseradap** [MicrosoftDocs/vsts-docs#1528]
How does the TFS assign the licenses if I assign the license to a number of users above the amount of extensions I have?. For instance: I bought 5 licenses for this extension and in the panel I assigned them to 6 users. What happens with the 6th user?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 56960db3-66b7-22e3-a4e1-01a9808b198a
* Version Independent ID: 64fa4d92-8b99-852c-0e11-2c9e87e41c04
* Content: [Assign paid extension access to users for VSTS and TFS](https://docs.microsoft.com/en-us/vsts/marketplace/assign-paid-extensions?view=tfs-2018)
* Content Source: [docs/marketplace/assign-paid-extensions.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/marketplace/assign-paid-extensions.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by elbatk** [comment]
Hi @carloseradap , I know it's been a long time for this and you may have figured it out. (This is my assuming) I would think that if you tried to assign to more than 5 users, you would get an error. @harishkragarwal may know more about that scenario. Harish, this should be straight forward and I can close this issue once you've answered :)

**Comment by pazand** [comment]
Hi @carloseradap,

@elbatk has the right idea. If you want to make sure all 6 users receive their extensions, you should first purchase 6 from the Marketplace. Buy what you need, then assign in the product.  Thanks and sorry about the delay!

**Comment by Ashu6753** [comment]
Hi,

Is there any way to add users and assign extension through Azure CLI or Powershell? Assigning extensions to users manually can be troublesome task. So I am looking for an option to automate this for my organization
