### ISSUE TITLE
Set favorites web page is not available. (404) 

### ISSUE THREAD

**Issue by Powerhelmsman** [MicrosoftDocs/vsts-docs#1530]
This issue was originally created by @BoiarynovQA from https://github.com/MicrosoftDocs/feedback/issues/606
Description
as a user, i can't start using your tutorials ((( set favorites tab is not available
STR:
Go to https://docs.microsoft.com/en-us/vsts/user-guide/?view=vsts and navigate to Step-by-Step Tutorials article
Click on link 'Set favorites'
Expected behavior
web page with content is opened.
Screenshot

Desktop
OS: [Windows]
Browser [chrome]
Version [latest]
stranges:
this web page is opened in ru locale, but i use en-us locale.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9af38f5c-9fac-bd18-4102-3640d7d1c5a4
* Version Independent ID: 46cdad70-76a0-d5b6-6941-492a72fd8181
* Content: [Guide for users new to VSTS](https://docs.microsoft.com/en-us/vsts/user-guide/?view=vsts)
* Content Source: [docs/user-guide/index.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/user-guide/index.md)
* Product: **devops**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
@Powerhelmsman It works for me in both Chrome and IE - https://docs.microsoft.com/en-us/vsts/project/navigation/set-favorites?toc=%2Fvsts%2Fuser-guide%2Ftoc.json&bc=%2Fvsts%2Fuser-guide%2Fbreadcrumb%2Ftoc.json&view=vsts&tabs=new-nav. Perhaps delete your cookies and try again. Thank you.

**Comment by BoiarynovQA** [comment]
@chcomley do you reproduce this issue by reported steps? 
1. Go to https://docs.microsoft.com/en-us/vsts/user-guide/?view=vsts
2. navigate to Step-by-Step Tutorials article
3. Click on link 'Set favorites'
AR: 404 - Page not found 


@chcomley  be note: that link provided by you from the comment above work as well.
but my issue still reproduced 
at Chrome and IE

**Comment by chcomley** [comment]
@Powerhelmsman and @BoiarynovQA, I've created a work item for this fix. We appreciate your input.
