### ISSUE TITLE
Enforce fast-forward only as a merge strategy

### ISSUE THREAD

**Issue by szabgab** [MicrosoftDocs/vsts-docs#1531]
Hi, how could I enforce that the only way a Pull-request can be accepted if it is going to be a fast-forward merge to a specific branch?

I would like to make sure that the only way to add something to "master" is to send a pr from a branch that has all the history of "master" already merged in (or rebased to).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7cd986e0-608c-1d8c-6faf-ecdb12e10bc6
* Version Independent ID: d60c996e-187e-dd6b-7f3a-dd056a1603f4
* Content: [Protect your Git branches with policies](https://docs.microsoft.com/en-us/vsts/repos/git/branch-policies?view=vsts)
* Content Source: [docs/repos/git/branch-policies.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/repos/git/branch-policies.md)
* Product: **devops**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
@szabgab I will find out.

**Comment by mmitrik** [comment]
@szabgab We don't have an ff-only merge strategy, but it's a feature we're tracking closely on UserVoice: https://visualstudio.uservoice.com/forums/330519-visual-studio-team-services/suggestions/18495292-enable-fastforward-merge-from-pullrequest 

I encourage you to upvote the idea there so you can stay in the loop on future progress.
