### ISSUE TITLE
Wrong link from VSO Team configuration settings

### ISSUE THREAD

**Issue by t3hprofit** [MicrosoftDocs/vsts-docs#1532]
https://go.microsoft.com/fwlink/?LinkId=512867 in VSO Team configuration settings goes here: https://docs.microsoft.com/en-us/vsts/organizations/show-bugs-on-backlog?view=vsts

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad73cae9-9b23-078d-2b95-d83cc794df03
* Version Independent ID: 3aa17c7d-adca-6ca6-b1e0-e811f520b325
* Content: [Show bugs on backlogs and boards - VSTS & TFS](https://docs.microsoft.com/en-us/vsts/organizations/settings/show-bugs-on-backlog?view=vsts)
* Content Source: [docs/organizations/settings/show-bugs-on-backlog.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/settings/show-bugs-on-backlog.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by t3hprofit** [comment]
followed the link on https://{orgname}.visualstudio.com/{TeamProject}/_settings/work-team

**Comment by KathrynEE** [comment]
@t3hprofit - Thank you for the correction. I'm working on getting the FWLink updated.
