### ISSUE TITLE
Images from repository

### ISSUE THREAD

**Issue by MarcKarbowiak** [MicrosoftDocs/vsts-docs#1533]
I have been trying to figure out the right path to use to add a png from our source-root to a markdown widget on the dashboard, having spend considerable time googling and reading your "learn markdown" page I give up, adding an image taking longer than a few minutes is horrible (and I have been working with vsts for years and really like it otherwise)... maybe provide a working example in the widget docu!?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b21c46ee-e19c-9dc4-11c2-8749c6576925
* Version Independent ID: 09ad6f7f-5169-f1b5-4f71-410bd85c62df
* Content: [Add markdown content to a team dashboard - VSTS & TFS](https://docs.microsoft.com/en-us/vsts/report/dashboards/add-markdown-to-dashboard?view=vsts&tabs=new-nav)
* Content Source: [docs/report/dashboards/add-markdown-to-dashboard.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/report/dashboards/add-markdown-to-dashboard.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by nickclark1000** [comment]
I'm experiencing the same issue

**Comment by MarcKarbowiak** [comment]
Try right click on the image and copy path, use that as the absolute oath,
worked for me....

**Comment by nickclark1000** [comment]
@MarcKarbowiak that worked, thanks! I had actually just gotten it to work with the 'Embedded Webpage' widget by using the same image url, but the markdown widget is more flexible/has more resizing options :) thanks again

**Comment by KathrynEE** [comment]
@MarcKarbowiak  - Thank you for your inquiry and I'm glad you got this working. I believe the syntax for adding images and files through the markdown widget are in the process of changing. I'll be updating the topic to proivde more tips.
