### ISSUE TITLE
No JaCoCo redbar.gif, greenbar.gif images in Coverage Reports on visualstudio.com

### ISSUE THREAD

**Issue by NormanFoxLee** [MicrosoftDocs/vsts-docs#1535]
Hello,

I am using visualstudio.com.
I added "Publish Code Coverage Results" to the pipeline and chose Jacoco as coverage tool. And when you open build's "Code coverage" tab - there is no redbar.gif, greenbar.gif images.
Also, there are two different links to those images:

.../_build/jacoco-resources/redbar.gif - which returns 404 error
.../Code Coverage Report_1/jacoco-resources/greenbar.gif - which returns an error that image contains errors.
![broken_image](https://user-images.githubusercontent.com/18305842/44175840-2ed07580-a0ad-11e8-9861-43715528199c.PNG)

Is it possible to fix this from my side? I have no idea how it was integrated. Any place where I could start?

Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6ac4ff4-9839-6a6d-8d20-a25084d221ef
* Version Independent ID: bd09f139-8e69-8ea1-6671-b7bba8e17c23
* Content: [Publish Code Coverage Results from a VSTS or TFS build](https://docs.microsoft.com/en-us/vsts/pipelines/tasks/test/publish-code-coverage-results?view=vsts#q--a)
* Content Source: [docs/pipelines/tasks/test/publish-code-coverage-results.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/test/publish-code-coverage-results.md)
* Product: **devops**
* GitHub Login: @erickson-doug
* Microsoft Alias: **dastahel**

**Comment by letmaik** [comment]
I can confirm this issue. The reason is that the image files for some reason get HTML-escaped, e.g. `�PNG&#26;IHDR&#1;&#1;&#1...`.

**Comment by DavidStaheli** [comment]
Apologies for taking so long to reply, @NormanFoxLee.  The code coverage displayed in-product is currently escaped out of concern for the possibliity of running malicious JavaScript.  We're addressing this, but in the meantime, please consider [these extensions](https://marketplace.visualstudio.com/search?term=coverage&target=AzureDevOps&category=All%20categories&sortBy=Relevance).  Please reopen this issue if we can provide additional help.
