### ISSUE TITLE
Use of .Result in example

### ISSUE THREAD

**Issue by dracan** [MicrosoftDocs/vsts-docs#1536]
Hi. I was a bit concerned to see the example showing using `.Result` instead of await. Bear in mind that some devs will copy this code as-is. This is really bad practice, as well as being quite dangerous causing potential deadlocks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e978322f-15ae-3a89-ae89-497cdfa5070a
* Version Independent ID: f8654902-e266-c12b-8e25-a2fa7a2ac626
* Content: [Get work items programmatically from Visual Studio Team Services](https://docs.microsoft.com/en-us/vsts/integrate/quickstarts/work-item-quickstart?view=vsts)
* Content Source: [docs/integrate/quickstarts/work-item-quickstart.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/integrate/quickstarts/work-item-quickstart.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by elbatk** [comment]
Hi @dracan , I know it's been a while but thanks for pointing this out, I'm making the change now! In the future - feel free to shoot us a PR :)

**Comment by flipsake** [comment]
In fixing this you seem to have forgotten that async methods usually must return Task<>
