### ISSUE TITLE
How to resend failed request in service/web hook

### ISSUE THREAD

**Issue by Styxxy** [MicrosoftDocs/vsts-docs#1537]
Hi,
How do we resend a failed web hook request? Eg, we have a service (web) hook that notifies a service when a work item is created. One request failed due to some malconfiguration on our part, but how do we resend this failed request?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 96287641-3e4f-b038-148f-08e8471bd573
* Version Independent ID: b0034cd1-4f29-2e2d-c2bb-49004552dae8
* Content: [Troubleshoot your service hooks integrations](https://docs.microsoft.com/en-us/vsts/service-hooks/troubleshoot?view=vsts)
* Content Source: [docs/service-hooks/troubleshoot.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/service-hooks/troubleshoot.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by Styxxy** [comment]
Current work around:
Use Postman to create the same request (the request that was being send, can be viewed in the history).

It would be nice though to have the option to resend a request (from the history view).

**Comment by Styxxy** [comment]
@steved0x @elbatk Any idea yet how to do a resent of a failed web hook request?

**Comment by elbatk** [comment]
Hi @Styxxy , sorry it's been so long, I'm trying to go through our backlog now. I'm adding @roofers here to see if there's a way to resend it.

**Comment by roofers** [comment]
Hi @Styxxy - There currently isn't a way to resend a failed hook.

**Comment by Styxxy** [comment]
Hi @elbatk and @roofers . Thanks for the feedback.
Is there any place where I can suggest this improvement (certain GitHub repo or ...)?

**Comment by nschonni** [comment]
https://developercommunity.visualstudio.com/spaces/21/visual-studio-team-services.html?type=idea is the replacement feature request portal

**Comment by Styxxy** [comment]
Thanks @nschonni , I logged this on https://developercommunity.visualstudio.com/idea/440334/resend-failed-request-in-serviceweb-hook.html .
