### ISSUE TITLE
"Grooming" is a word with a bad aftertaste

### ISSUE THREAD

**Issue by jessehouwing** [MicrosoftDocs/vsts-docs#1541]
Since "grooming" is also used to describe the act of seducing under age children to perform (sexual) acts in front of a camera, the Scrum Guide has renamed this to "Refinement". You should too.

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: dbdbe4c8-400b-0f3f-2214-4233a05c1752
* Version Independent ID: 4dafb9ad-de23-5d3c-130e-c1baa944ecb4
* Content: [Backlog best practices - VSTS & TFS](https://docs.microsoft.com/nl-nl/vsts/boards/backlogs/best-practices-product-backlog?view=vsts)
* Content Source: [docs/boards/backlogs/best-practices-product-backlog.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/boards/backlogs/best-practices-product-backlog.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@jessehouwing  - Thank you for your feedback. Agreed. Will update the article.
