### ISSUE TITLE
Thanks 😍

### ISSUE THREAD

**Issue by Greg-Neumann** [MicrosoftDocs/vsts-docs#1542]
After 'battling' for a few hours trying to bludgeon my way through connection my (Personal Account created) VSTS to a new (Microsoft Work account created) Azure/Office account, I decided to turn the music off and follow this guide.
 Guess what? All worked the first time. I can now sign in to all my VSTS repos from my (new) Microsoft work account - thanks! 

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 60e3f1aa-2935-a206-2d2a-fd39f1fdfacb
* Version Independent ID: b0d0a3b8-f5b3-0a9c-42c2-4d185b80564e
* Content: [Connect your VSTS organization to Azure Active Directory (Azure AD)](https://docs.microsoft.com/en-gb/vsts/organizations/accounts/connect-organization-to-aad?view=vsts)
* Content Source: [docs/organizations/accounts/connect-organization-to-aad.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/accounts/connect-organization-to-aad.md)
* Product: **devops**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by steved0x** [comment]
@Greg-Neumann Thank you for the feedback! I will pass this along to the author and our team.

**Comment by steved0x** [comment]
@erickson-doug

**Comment by chcomley** [comment]
@Greg-Neumann We appreciate your feedback and are happy our documentation served you well. If you happen to come across anything that could use a little clarity in the future, please let us know.
