### ISSUE TITLE
Duplicate key names in different file cause duplicate variable

### ISSUE THREAD

**Issue by onlyutkarsh** [MicrosoftDocs/vsts-docs#1543]
I am deploying a function app (host.json) and web app (appsettings.json). 

My appsettings.json is web app is like below
```json
{
  "Logging": {
    "LogLevel": {
      "Default": "Warning"
    }
  },
  "AllowedHosts": "*",
  "AppSettings": {
    "KeyName": "lobhealth-dev-kv-pks"
  },
}
```

My host.json in function app
```json
{
  "appSettings": {
    "connectionString": "",
    "keyName": "xyz"
  },
  "CORS": "*",
  "logger": {
    "categoryFilter": {
      "defaultLevel": "Information",
      "categoryLevels": {
        "Host.Results": "Error",
        "Function": "Information",
        "Host.Aggregator": "Trace"
      }
    }
  }
}

```

I would like to replace a keyName which I refer in variables like `AppSettings.KeyName` in `appsettings.json` and `appSettings.keyName` in `host.json`. Its currently not possible to replace variables with the current approach as we cannot create duplicate variables in VSTS.

Any plans to address this?

**Comment by alexhomer1** [comment]
Thank you for your feedback. As this is a product request, may I suggest you post it on https://visualstudio.uservoice.com/forums/330519-team-services, or as product feedback at https://developercommunity.visualstudio.com/spaces/21/index.html.
