### ISSUE TITLE
Out of Date, Broken Links, Inaccurate

### ISSUE THREAD

**Issue by laultman** [MicrosoftDocs/vsts-docs#1544]
Trying to find the PowerPoint Storyboard extension and it appears to be gone. Followed the links that are still working but could not locate. If it is NOT available without an install of Visual Studio then you should make that a statement so that people don't waste time. It would be useful to have for Teams collaboration by stakeholders who are not developers and don't have budget to go buy some other tools (government accounts).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6d264a44-2064-f4f4-53f7-9cdb58855fef
* Version Independent ID: 259e65ee-029a-847e-1857-9cac76d0ccaa
* Content: [Storyboard your ideas with PowerPoint - VSTS & TFS](https://docs.microsoft.com/en-us/vsts/boards/backlogs/office/storyboard-your-ideas-using-powerpoint?view=vsts)
* Content Source: [docs/boards/backlogs/office/storyboard-your-ideas-using-powerpoint.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/boards/backlogs/office/storyboard-your-ideas-using-powerpoint.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@laultman - My apologies for the confusion. You can download the Team Foundation Server Office Integration 2017 tool from this link - https://go.microsoft.com/fwlink/?LinkId=832491&clcid=0x409. You can find this link by scrolling down the page and look under Other tools and frameworks - https://visualstudio.microsoft.com/downloads/.
