### ISSUE TITLE
The documentation should explain what to expect when the opened item is deleted.

### ISSUE THREAD

**Issue by PerthCharern** [MicrosoftDocs/vsts-docs#1545]
The documentation should explain what to expect when the opened item is deleted. How does the caller detect from the returned result that the opened item has been deleted. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a9ea30fa-0a16-40c6-6b94-22361d606e1a
* Version Independent ID: 2a4f5d09-d701-528d-bb28-c4b38c9b902e
* Content: [TFS/WorkItemTracking/Services Work Item Form Navigation Service API](https://docs.microsoft.com/en-us/vsts/extend/reference/client/api/tfs/workitemtracking/services/workitemformnavigationservice?view=vsts)
* Content Source: [docs/extend/reference/client/api/TFS/WorkItemTracking/Services/WorkItemFormNavigationService.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/extend/reference/client/api/TFS/WorkItemTracking/Services/WorkItemFormNavigationService.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by elbatk** [comment]
Hey @PerthCharern , we are in the process of updating these client APIs to be autogenerated from the code and they should be in a good spot after that. I know it's been a while since this issue, but it's on our radar and being worked on!
