### ISSUE TITLE
Integrating Slack with a Service Account?

### ISSUE THREAD

**Issue by mapoitras** [MicrosoftDocs/vsts-docs#1549]
When using the instructions found here
https://docs.microsoft.com/en-us/vsts/service-hooks/services/slack?view=vsts
to setup slack integration, its is tied to the account of the person creating the account.  If the user leaves the corporation and his account is deleted, we get a 

Subscription   55f446e7-6f53-4dc6-8993-1fc8dfd0e5a0 has been disabled
--
Sorry, your subscription 'slack Service Hook for build.complete' has been disabled for the following reason:  Exception 'IdentityInactiveException' - 'A subscription identity is inactive 'Peter Smith' or 'Peter Smith'.'.

Is there a way to setup Slack integration using a Service account so its not tied to a particular user?

**Comment by elbatk** [comment]
Hi @mapoitras , sorry it's been so long since this issue. Adding @roofers to see if he can help here. Rogan, the user is wanting to know if you can set up service hooks (slack specifically) via a service account and not a particular user.
