### ISSUE TITLE
Variable Groups not available in Build Definitions?

### ISSUE THREAD

**Issue by pabrams** [MicrosoftDocs/vsts-docs#1550]
In TFS 2017 Update 3 I don't see the Variable Groups tab in Build Definitions like you show in the screenshot under your "Use a Variable Group" heading.  There are also other weird things about that screenshot, like what is that "Pipeline" tab?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4827aa99-ae62-bd63-6f2f-a87a4065ed27
* Version Independent ID: c9e461ee-7f42-3503-9460-18fa3a807bbb
* Content: [Variable groups for VSTS and TFS](https://docs.microsoft.com/en-us/vsts/pipelines/library/variable-groups?view=vsts#use-a-variable-group)
* Content Source: [docs/pipelines/library/variable-groups.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/library/variable-groups.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by RoopeshNair** [comment]
@vijayma - for variable groups support in build.

**Comment by vijayma** [comment]
Variable groups support in Build was introduced in TFS 2018. We will update the docs to represent this accurately. @andyjlewis

**Comment by andyjlewis** [comment]
@alexhomer1 please follow up.

**Comment by alexhomer1** [comment]
Thank you for your feedback. I will update the topic to include your recommendations.
