### ISSUE TITLE
Build.TriggeredBy.BuildDefinitionName Not Populating

### ISSUE THREAD

**Issue by lifesoccult** [MicrosoftDocs/vsts-docs#1551]
Hello, the predefined variable Build.TriggeredBy.BuildDefinitionName is not being populated in a build definition -- either using the UI to define a task or with a YAML configuration. Please investigate.

Thanks,

Jonathan

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ffebdc8-521c-44b5-cde4-4abdc1bd6f18
* Version Independent ID: dc0effda-6d93-62aa-64c5-4e6f283b0826
* Content: [Predefined Build variables](https://docs.microsoft.com/en-us/vsts/pipelines/build/variables?view=vsts)
* Content Source: [docs/pipelines/build/variables.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/build/variables.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by scottboehmer** [comment]
@lifesoccult this property is only set when a build is triggered by another build using a build completion trigger, and it seems to be working as designed for me. Assuming your build was triggered in that way, could you share more information on both the triggering definition and the triggered one?

Also, are the other Build.TriggeredBy.* variables being set for you?

**Comment by scottboehmer** [comment]
Ok, looks like there is an error in the variable name in the docs. Can you confirm that you get a value for $(Build.TriggeredBy.DefinitionName)?

@andyjlewis are you able to fix the variable name in the docs? It looks like they currently have BuildDefinitionName rather than just DefinitionName for the triggered by variable.

**Comment by justinmetz** [comment]
I can confirm that the variable can be retrieved by using $(Build.TriggeredBy.DefinitionName) instead of what is in the docs.  Thank you so much for pointing this out, it was driving me crazy. :)
