### ISSUE TITLE
unable to ignore .git/ directory

### ISSUE THREAD

**Issue by gforceg** [MicrosoftDocs/vsts-docs#1552]
Hello, I'm using the [Copy Files](https://docs.microsoft.com/en-us/vsts/pipelines/tasks/utility/copy-files?view=vsts) task in TFS. All of the application source is in the same directory that .git/ resides.
I want to copy all files except .git/ and I can't seem to make it work. The easy solution is to put everything in a subfolder and use that as the source folder. But are ignore globs allowed? I've tried the following variations:

```
**
!.git/
```
```
**
!.git\
```

**Comment by vtbassmatt** [comment]
Patterns only match full files, so you would need:
```
**/*
!.git/**/*
```

I'll add this as an example.
