### ISSUE TITLE
Extension point missing for 'ms.vss-work-web.iteration-backlog-tabs' in the new navigation preview

### ISSUE THREAD

**Issue by pratyushoak** [MicrosoftDocs/vsts-docs#1553]
A contribution added to the 'ms.vss-work-web.iteration-backlog-tabs' extension point is not visible in the new UI/Navigation. Is this going away or is it regression maybe?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eab519d8-dc41-91de-437a-4469edefddab
* Version Independent ID: edc98ac8-a89a-a79a-d75c-1435870a00d2
* Content: [Developing extensions for VSTS vertical web navigation](https://docs.microsoft.com/en-us/vsts/extend/develop/web-navigation?view=vsts)
* Content Source: [docs/extend/develop/web-navigation.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/extend/develop/web-navigation.md)
* Product: **devops**
* GitHub Login: @willsmythe
* Microsoft Alias: **wismythe**

**Comment by steved0x** [comment]
@elbatk Can you take a look at this one?

**Comment by pratyushoak** [comment]
Actually, I figured out the issue. In the manifest, I had this - 
`"type": "ms.vss-web.hub",
      "targets": [
        "ms.vss-work-web.iteration-backlog-tabs"
      ],`

changing the type to - 'ms.vss-web.tab' fixed the issue. However, weirdly even with the hub type, the old UI did add the tab under iterations backlog.
