### ISSUE TITLE
Can we support important syntax like which in MicrosoftDocs?

### ISSUE THREAD

**Issue by 0xxd0** [MicrosoftDocs/vsts-docs#1555]
syntax like 

[!IMPORTANT] 
[!NOTE] 

It's very useful.

**Comment by steved0x** [comment]
@0xxd0 Are you talking about supporting these types of calllouts in the markdown that is used in various places in VSTS (like Wikis, PR comments, etc?) I am forwarding this to the author of that article to see if there is a way, and if so we can add it to the article.

**Comment by 0xxd0** [comment]
@steved0x Absolutely yes!

**Comment by KathrynEE** [comment]
@0xxd0 - No, these specific syntax snippets are defined for Microsoft Docs, and are not part of the syntax defined for use in VSTS and TFS for markdown.
