### ISSUE TITLE
IIS Deployment sub tasks no longer supported

### ISSUE THREAD

**Issue by taqabubaker** [MicrosoftDocs/vsts-docs#1556]
Hi,

I followed the [post](https://docs.microsoft.com/en-us/vsts/pipelines/apps/cd/deploy-webdeploy-iis-deploygroups?toc=/vsts/deploy-azure/toc.json&bc=/vsts/deploy-azure/breadcrumb/toc.json&view=vsts) instructions but I noticed that "IIS Deployment" sub tasks "IIS Web App Manage" and "IIS Web App Deploy" are no longer supported!
I got an error on both of them says "This task is no longer installed. Re-install the task or remove it from your pipeline." which prevent me from saving the CD pipeline.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca1c5394-611b-b119-dbf3-b88404e351d5
* Version Independent ID: fcc23259-21ec-f9fa-4e25-f587e1e0f41b
* Content: [Deploy to an IIS web server on a Windows Virtual Machine](https://docs.microsoft.com/en-us/vsts/pipelines/apps/cd/deploy-webdeploy-iis-deploygroups?toc=/vsts/deploy-azure/toc.json&bc=/vsts/deploy-azure/breadcrumb/toc.json&view=vsts)
* Content Source: [docs/pipelines/apps/cd/deploy-webdeploy-iis-deploygroups.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/apps/cd/deploy-webdeploy-iis-deploygroups.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment]
Thank you for your feedback. I have passed this on to the product team for advice.

**Comment by alexhomer1** [comment]
The post that you are referring to calls out IIS tasks in the Deployment Group phase. Can you confirm you are adding tasks in the Deployment Group phase ("Run on deployment group") as shown in step 5 of creating a release definition. The product team suggest you might be adding the deprecated IIS tasks to the Agent phase instead. You also need to use the Marketplace task
https://marketplace.visualstudio.com/items?itemName=ms-vscs-rm.iiswebapp

**Comment by taqabubaker** [comment]
Hi @alexhomer1 
I confirm it was my mistake. I should run it on  ("Run on deployment group"). Sorry for any inconvenience.
Again thank you and the team on your support.
