### ISSUE TITLE
There still have member under project->summary->members after delete this member!

### ISSUE THREAD

**Issue by moyanming** [MicrosoftDocs/vsts-docs#1558]
Why there still have member after delete (remove) this member? This member can be find under "project"->Overview->Summary->Members. How to completely delete the member?
Best regards.

![qq 20180819135616](https://user-images.githubusercontent.com/13234209/44306062-98a49400-a3b9-11e8-975a-39c8739368e0.png)
![qq 20180819134453](https://user-images.githubusercontent.com/13234209/44306061-93474980-a3b9-11e8-9438-27c7e4053cee.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 07738454-4b1a-eff5-6c16-69e963ab2663
* Version Independent ID: a63f1dad-0378-5ce3-97e9-ec66afffb206
* Content: [Add users to a team or project](https://docs.microsoft.com/en-us/vsts/organizations/security/add-users-team-project?toc=%2Fvsts%2Forganizations%2Fsettings%2Fscale%2Ftoc.json&bc=%2Fvsts%2Forganizations%2Fsettings%2Fscale%2Fbreadcrumb%2Ftoc.json&view=vsts&tabs=new-nav#add-users-to-a--project)
* Content Source: [docs/organizations/security/add-users-team-project.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/security/add-users-team-project.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@moyanming - Thank you for your inquiry.  When you remove a user from a team, you don't remove them from a team project. Please review the information provided here - https://review.docs.microsoft.com/en-us/azure/devops/organizations/security/remove-users-prohibit-access?view=vsts&branch=master-rebrand - and if you're using VSTS, https://review.docs.microsoft.com/en-us/vsts/organizations/accounts/manage-users-table-view?view=vsts&branch=master-rebrand&tabs=new-nav#manage-users.

**Comment by nschonni** [comment]
@KathrynEE those `review.docs.microsoft.com` aren't available outside of Microsoft folks. The second one works when removing the `review.`, but the first 404s

**Comment by moyanming** [comment]
Hi @KathrynEE , it seems that the "[Manage users for VSTS](https://docs.microsoft.com/en-us/vsts/organizations/accounts/manage-users-table-view?view=vsts&tabs=new-nav)" should be update. I add a new issues for that #1652 .
