### ISSUE TITLE
Not listed in nav

### ISSUE THREAD

**Issue by Silic0nS0ldier** [MicrosoftDocs/vsts-docs#1559]
Not entirely sure how I even managed to track this down (glad I was able none-the-less) as its not included in the nav at all.

Looking at the source vs. other pages in the same section, I think the issue might be the lack of the `ms.topic` property. Page should also be linked to at https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/index.md

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2d4861e9-3c5e-ccc8-6918-f5a7327de545
* Version Independent ID: 8681cf86-9935-2063-ab5d-7ece1e14a2b1
* Content: [NuGet Tool Installer](https://docs.microsoft.com/en-us/vsts/pipelines/tasks/tool/nuget?view=vsts#feedback)
* Content Source: [docs/pipelines/tasks/tool/nuget.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/tool/nuget.md)
* Product: **devops**
* GitHub Login: @erickson-doug
* Microsoft Alias: **amullans**

**Comment by steved0x** [comment]
@Silic0nS0ldier Thank you for letting us know, I have fixed this and it should be live soon.
