### ISSUE TITLE
The notice at the top is a bit of a "lie"

### ISSUE THREAD

**Issue by Trannosaur** [MicrosoftDocs/vsts-docs#156]
https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/collaborate/collaborate-in-a-team-room.md

Teams does not have an API to access conversations

**Comment by steved0x** [comment]
@Trannosaur Thank you for letting us know, I have forwarded this to the author of the article to see if we can get a clarification. I'll reply shortly once we have made a fix or clarification.

**Comment by steved0x** [comment]
@Trannosaur Thank you for letting us know, we have fixed this and it should be live soon, thank you.
