### ISSUE TITLE
UserContext Member Definition

### ISSUE THREAD

**Issue by Dogbert581** [MicrosoftDocs/vsts-docs#1563]
Besides just the type of the member, it would be good to see an example or some definition of what is stored in these fields. Certainly some are obvious (e.g. email, id, etc...), but what does limitedAccess mean? Limited Access to what? How is this populated? For example, does this mean the user only has read-only access, they are just a stake holder, etc...?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f199a03-2fed-96f5-3b9c-afcb9e5d5ff6
* Version Independent ID: 5696ec2b-fa78-1d8a-d8bd-be0c0efdfb35
* Content: [VSS/References/SDK.Interfaces UserContext API](https://docs.microsoft.com/en-us/vsts/extend/reference/client/api/vss/references/sdk_interfaces/usercontext?view=vsts)
* Content Source: [docs/extend/reference/client/api/VSS/References/SDK_Interfaces/UserContext.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/extend/reference/client/api/VSS/References/SDK_Interfaces/UserContext.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by shanthoshravirala** [comment]
for VSS.getWebContext().user, I am not getting limitedAccess attribute

**Comment by elbatk** [comment]
Hey everyone, we're currently working on updating all of these client APIs! They will be auto-generated and contain more information. It's in the works! For now, if you have product issues I'd suggest reaching out to the [Azure DevOps Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html) to get to the product team!
