### ISSUE TITLE
TFS not listed in connectors

### ISSUE THREAD

**Issue by pcaston2** [MicrosoftDocs/vsts-docs#1565]
I have updated my app, it launched a new version, and TFS is not displaying as an option for the connectors.

Note: I am using the FREE version of MS Teams, not 365.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1cddc0ae-93af-297c-2e71-334143ebee1e
* Version Independent ID: cb76e516-8471-c3e1-45f4-0a20a223f32a
* Content: [Microsoft Teams with VSTS and Team Foundation Server](https://docs.microsoft.com/en-us/vsts/service-hooks/services/teams?view=vsts#q--a)
* Content Source: [docs/service-hooks/services/teams.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/service-hooks/services/teams.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by iAmBipinPaul** [comment]
same issue

**Comment by kdicken** [comment]
I'm seeing this same issue as well. VSTS is missing in teams, and does not click through. Nor is there a connector for the Azure Boards.

**Comment by elbatk** [comment]
Hi everyone, please post issues with the product on the [Azure DevOps Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html) as it is regularly monitored by the product team, thank you!

**Comment by IdiotLeon** [comment]
Same here, while I can find VSTS on Slack pretty quickly.

![image](https://user-images.githubusercontent.com/12004270/47948134-128fe800-dee8-11e8-8def-20e4f87a4b38.png)

**Comment by pcaston2** [comment]
I'm still having this issue, why is it closed?

**Comment by elbatk** [comment]
I've closed this issue in this repository as it's for documentation issues with Azure DevOps Services or Team Foundation Server. Product issues should be posted in the Azure [DevOps Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html). This almost seems like it may be a Microsoft Teams issue as well, I'm going to add @roofers for awareness as he works on Service Hooks.

**Comment by lewcianci** [comment]
Same issue... thanks to @idiotleon I will probably move to slack

**Comment by evamueller** [comment]
Look for "Azure DevOps Server" - TFS got renamed. Works fine for TFS 2017.2 and higher.

**Comment by fugaku** [comment]
I'm also having the same issue. Cannot find any Azure as connector.
Why is this closed ?

**Comment by iAmBipinPaul** [comment]
@fugaku Azure Repo
May be it is now 
https://docs.microsoft.com/en-us/azure/devops/repos/integrations/repos-teams?view=azure-devops
