### ISSUE TITLE
Need Clarification

### ISSUE THREAD

**Issue by SamGrantham** [MicrosoftDocs/vsts-docs#1566]
We call out that the *Servers* must all use the same Collation settings but the Collation is a Database (not server) level setting:

>"All instances of SQL Server in your Team Foundation Server deployment must use the same settings"

THis should probably read:

> "All databases in all instances of SQL Server used by your Team Foundation Server deployment must have the same collation settings"

I think this would be much clearer for customers.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc5e7bed-20b2-b95b-ebb1-27ef37244586
* Version Independent ID: 1c0afce3-80e6-faa3-6dae-942261d85bd0
* Content: [SQL Server Collation Requirements for Team Foundation Server](https://docs.microsoft.com/en-us/tfs/server/install/sql-server/collation-requirements#see-also)
* Content Source: [docs/server/install/sql-server/collation-requirements.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/server/install/sql-server/collation-requirements.md)
* Product: **devops-server**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by elbatk** [comment]
Agreed, @SamGrantham , making this update now :)
