### ISSUE TITLE
How to raise warnings to VSTS?

### ISSUE THREAD

**Issue by jacqueskang** [MicrosoftDocs/vsts-docs#1571]
It seems that warnings raised by "dotnet build" are not displayed in VSTS build summary. 
Could you provide any clue?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 483dcb1c-1a89-2b20-4cf2-abd3ae88d9ed
* Version Independent ID: dc4722ed-5a4b-26ec-e7d5-a149bf6e79a7
* Content: [.NET Core](https://docs.microsoft.com/en-us/vsts/pipelines/languages/dotnet-core?view=vsts&tabs=designer#build-environment)
* Content Source: [docs/pipelines/languages/dotnet-core.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/languages/dotnet-core.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by vijayma** [comment]
Are you using the designer or YAML for your pipeline? Are you using the dotnet task or are you running dotnet build command directly using a script?
