### ISSUE TITLE
Allow Scripts to Access OAuth Token has moved

### ISSUE THREAD

**Issue by bussemac** [MicrosoftDocs/vsts-docs#1576]
Documentation says it's on the Options tab for the build pipeline; it has now moved to the Agent phase configuration.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77731c06-e4fd-8125-0daf-870c9ccedd3f
* Version Independent ID: 0d5c338d-80f9-c64e-b675-bf7b4eb8e32b
* Content: [Use a PowerShell script to customize your build process](https://docs.microsoft.com/en-us/vsts/pipelines/scripts/powershell?view=vsts#oauth)
* Content Source: [docs/pipelines/scripts/powershell.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/scripts/powershell.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by andyjlewis** [comment]
Thanks for the heads up. Yes, for VSTS and newer TFS, but not for older TFS, so this change has to be versioned. Copied to backlog.
