### ISSUE TITLE
Quickstart for Universal Package shouldn't link to private build of VSTS CLI

### ISSUE THREAD

**Issue by nayanshah** [MicrosoftDocs/vsts-docs#1577]
The page mentions the following:
> 1.Download [this private build](https://1drv.ms/u/s!AuzH567rcbHhv5JLiqDK0Csb1LT80g) of the VSTS CLI and install it.

But VSTS CLI 0.1.2 has support for universal packages, so official release should be linked instead.

**Comment by steved0x** [comment]
@nayanshah Thank you for letting us know, there are conflicts in your PR due to changes we made, but I am fixing this on our side and it should be live later today. Thank you!
