### ISSUE TITLE
Deployment Center (Preview) for Web App

### ISSUE THREAD

**Issue by sureshhatgithub** [MicrosoftDocs/vsts-docs#1581]
This documentation is useful however it was created on 01/01/2017 and never updated. Considering continuous changes to Microsoft Azure, we would expect to have latest updates to the documentation so we can follow along new changes. Example: 
Recent changes where "Deployment Center (Preview) " section for WebApp has different options than mentioned in this document.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f04a2d4-2e44-9151-1bba-32f00f3cc04c
* Version Independent ID: 1d8ef142-334b-be0a-95eb-e416d6ebed00
* Content: [Automatically generate a CI/CD pipeline to deploy an ASP.NET app](https://docs.microsoft.com/en-us/vsts/pipelines/archive/apps/aspnet/aspnet-4-ci-cd-azure-automatic?view=vsts#feedback)
* Content Source: [docs/pipelines/archive/apps/aspnet/aspnet-4-ci-cd-azure-automatic.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/archive/apps/aspnet/aspnet-4-ci-cd-azure-automatic.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment]
Thank you for your feedback. This topic is an archived one that is no longer being updated. The current documentation for Deployment Center is at https://docs.microsoft.com/azure/app-service/app-service-continuous-deployment. I'll update this topic to show that link.
