### ISSUE TITLE
Broken URL link "Create a backlog - to develop your product backlog"

### ISSUE THREAD

**Issue by dieselVtwin** [MicrosoftDocs/vsts-docs#1582]
[Enter feedback here]
This URL link, "Create a backlog - to develop your product backlog" in the Related Articles section of the page goes to an error 404 page.

The URL link is:
https://docs.microsoft.com/en-us/vsts/boards/backlogs/create-your-backlog.md

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 00606812-b874-018b-405a-b9f2870d2490
* Version Independent ID: 6d0c2539-4f09-b8b4-e60d-23251f4f8a14
* Content: [Scrum process work items types & workflow - VSTS & TFS](https://docs.microsoft.com/en-us/vsts/boards/work-items/guidance/scrum-process-workflow?view=vsts)
* Content Source: [docs/boards/work-items/guidance/scrum-process-workflow.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/boards/work-items/guidance/scrum-process-workflow.md)
* Product: **devops**
* GitHub Login: @erickson-doug
* Microsoft Alias: **kaelli**

**Comment by steved0x** [comment]
@dieselVtwin Thank you for letting us know, we made a lot of changes recently and this was fixed. Thanks again and sorry it took so long to respond.
