### ISSUE TITLE
Engineering companies

### ISSUE THREAD

**Issue by mjvk** [MicrosoftDocs/vsts-docs#1586]
While I understand that most can be done in TFS, integration with Sharepoint is still nice for those who do not only work with software but also with hardware (machines, steel, hydraulics etc.). This way both worlds can be integrated. I.e. the mechanical/field/etc. engineers around me will not use TFS. They use sharepoint for documents and tasks. I would like to link those two to TFS, so tasks and documents can be linked to work items, and from there to branches and commits. Will something like this be possible in the future, or do I need to look for a different workflow.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eb3e5834-a760-6870-593c-06931d5a115b
* Version Independent ID: 8903e640-8da5-fa30-cd3b-d0e7ae4b082b
* Content: [About SharePoint Integration - TFS](https://docs.microsoft.com/en-us/vsts/report/sharepoint-dashboards/about-sharepoint-integration?view=vsts)
* Content Source: [docs/report/sharepoint-dashboards/about-sharepoint-integration.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/report/sharepoint-dashboards/about-sharepoint-integration.md)
* Product: **devops**
* GitHub Login: @erickson-doug
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@mjvk - Thank you for your inquiry. You can still enter hyperlinks from a work item to a Sharepoint document or task. Other than that, you may want to investigate what is available from the Marketplace in terms of extensions, or if you can use service hooks to support your workflow. Other than that, you may want to submit a feature request to our [UserVoice page](https://visualstudio.uservoice.com/forums/330519-team-services).
