### ISSUE TITLE
Are the sources of the built-in widgets in VSTS available on Github or public ?

### ISSUE THREAD

**Issue by mguirao** [MicrosoftDocs/vsts-docs#1587]
I'm really interested to fork one of the widget "Deployment status" to add some capacities like the ability to filter on mulitple branch. 
I don't want to restart from scratch but i haven't found anything online yet so i'm asking.
Is it ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bbe9c938-dde5-4eba-6e09-6e43ef0e8ee5
* Version Independent ID: 53f9961e-1c31-1080-1699-4ef901939b19
* Content: [Add a dashboard widget](https://docs.microsoft.com/en-us/vsts/extend/develop/add-dashboard-widget?view=vsts)
* Content Source: [docs/extend/develop/add-dashboard-widget.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/extend/develop/add-dashboard-widget.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by mguirao** [comment]
Any chance to have an update on this ?
Am I in the wrong place to ask this question ?

**Comment by elbatk** [comment]
Hi @mguirao , I apologize for the delay, we've been busy over in docs land. Adding @willsmythe to help answer this question for you.

**Comment by elbatk** [comment]
Did you check out these [sample extensions](https://github.com/Microsoft/vsts-extension-samples), @mguirao ? There is a widgets folder with some templates.

**Comment by mguirao** [comment]
I did, but they are really basic and not really related to what i want to do.
What i want to do is just to tweak a bit the one that is already available : https://docs.microsoft.com/en-us/vsts/report/dashboards/widget-catalog?view=vsts#deployment-status-widget
to add wildcard filter in the branches.
Is the source code public for this one ? I know it is for most of the build/release task step, i was expecting the same for widget.

**Comment by mguirao** [comment]
Should I give up having a definitive answer ?

**Comment by dineshspillai** [comment]
I am also looking for customizing the widget.
