### ISSUE TITLE
Command line in point 2 is incorrect for TFS >= 2010

### ISSUE THREAD

**Issue by rottedfrog** [MicrosoftDocs/vsts-docs#1589]
It should be:

tf undo /workspace:OtherUserWorkspace;OtherUser $/TeamProject/MyFile.cs /collection:http://YourTFSServer:8080/tfs/YourCollection

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a380edf-ed74-6dcd-aa03-f07625a05df8
* Version Independent ID: 2a823f36-84f6-fd68-e803-1c496d8feddc
* Content: [Undo Changes in Another User's Workspace](https://docs.microsoft.com/en-us/vsts/repos/tfvc/undo-changes-another-user-workspace?view=vsts)
* Content Source: [docs/repos/tfvc/undo-changes-another-user-workspace.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/repos/tfvc/undo-changes-another-user-workspace.md)
* Product: **devops**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
@rottedfrog Thanks for the info, I am fixing this and it should be live soon.
