### ISSUE TITLE
When is it possible again to associate VSTS test cases with unit tests written in MS Test V2?

### ISSUE THREAD

**Issue by p18e3** [MicrosoftDocs/vsts-docs#1590]
As described [here](https://docs.microsoft.com/en-us/vsts/test/associate-automated-test-with-test-case?view=vsts), it is not anymore officially supported to associate test cases created in VSTS with unit test that are written with the MS Test V2 framework.
Is there any information about when this features will be reactivated?

**Comment by alexhomer1** [comment]
Thank you for your feedback. Product suggestions and feature requests are best posted and upvoted on the UserVoice website at https://visualstudio.uservoice.com/forums/330519-team-services, where they are tracked by the product teams. Please post your suggestion there. Thank you.
