### ISSUE TITLE
Deployment groups - misses doc for "Update targets"

### ISSUE THREAD

**Issue by michha** [MicrosoftDocs/vsts-docs#1591]
The documentation on deployment pools doesn't explain the _Update targets_ function. 
![image](https://user-images.githubusercontent.com/10424767/44535653-c90e6a00-a6fa-11e8-8111-bc11f0eb8ec8.png)
The function should both be mentioned and also given a clear answer about the new version (probably the one delivered with the current TFS version) and the requirements needed for the update to work (probably internet access for the current agent to https://vstsagentpackage.azureedge.net)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3b38c265-be4c-b038-e3a9-783a5e5ce659
* Version Independent ID: 67da69da-3651-a8f4-f06a-c35aa3aa98fc
* Content: [Deployment groups in Release Management](https://docs.microsoft.com/en-us/vsts/pipelines/release/deployment-groups/?view=vsts)
* Content Source: [docs/pipelines/release/deployment-groups/index.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/release/deployment-groups/index.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment]
Thank you for your feedback. I have passed this on to the product team for advice.

**Comment by RoopeshNair** [comment]
Thank you for the feedback, update agent, forces the agent upgrade on the target
We will get the docs updated to include it.

**Comment by phil-harmoniq** [comment]
As far as I can tell, this feature still isn't documented anywhere. Has any progress been made on this?

**Comment by v-nealva** [comment]
Hello team, Is there any progress on this request? I cannot find any doc about this topic
