### ISSUE TITLE
TFS2018 服务器上的电子邮件通知设置出错

### ISSUE THREAD

**Issue by Caizhenyu** [MicrosoftDocs/vsts-docs#1592]
已启用：                        [检索值时出错]
SMTP 服务器：              [检索值时出错]
电子邮件发件人地址：  [检索值时出错]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 89390a5f-1a41-b399-3ab7-e662c60cdb80
* Version Independent ID: a2fde063-dd71-dde0-0432-2ba80f8b13fb
* Content: [Contacting support for notifications - VSTS & TFS](https://docs.microsoft.com/en-us/vsts/notifications/troubleshoot-contact-support?view=vsts)
* Content Source: [docs/notifications/troubleshoot-contact-support.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/notifications/troubleshoot-contact-support.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by Caizhenyu** [comment]
点击 警报设置 ，弹窗显示 未将对象引用设置到对象实例。
点击 发送测试邮件， 并输入接收邮箱 和 邮件内容 后点击 确定，弹窗显示  TF400320：不支持发送电子邮件。请与管理员联系。

**Comment by Caizhenyu** [comment]
日志：

[Error  @01:38:59.297] System.InvalidOperationException:TF400320: 不支持发送电子邮件。请与管理员联系。
   在 Microsoft.TeamFoundation.Framework.Server.TeamFoundationMailService.Send(IVssRequestContext requestContext, IEnumerable`1 messages)
   在 Microsoft.TeamFoundation.Server.WebAccess.Controllers.ApiCommonController.TestMailSettings(String sendTo, String message)
[Error  @01:39:55.815] 
异常消息: 未将对象引用设置到对象的实例。 (类型 NullReferenceException)
异常堆栈跟踪:    在 Microsoft.TeamFoundation.Management.SnapIn.ApplicationTierNode.HandleChangeEmailAlertSettings(ActionClickedEventArgs args)
   在 Microsoft.TeamFoundation.Management.SnapIn.ApplicationTierNode.OnManagementAction(ActionClickedEventArgs args)
   在 Microsoft.TeamFoundation.Management.Controls.ManagementView.OnActionClicked(ActionClickedEventArgs args)
   在 Microsoft.TeamFoundation.Management.Controls.ManagementView.newPanel_ActionClicked(Object source, ActionClickedEventArgs e)

[Error  @01:41:17.241] System.InvalidOperationException:TF400320: 不支持发送电子邮件。请与管理员联系。
   在 Microsoft.TeamFoundation.Framework.Server.TeamFoundationMailService.Send(IVssRequestContext requestContext, IEnumerable`1 messages)
   在 Microsoft.TeamFoundation.Server.WebAccess.Controllers.ApiCommonController.TestMailSettings(String sendTo, String message)

**Comment by steved0x** [comment]
@Caizhenyu Thank you for your feedback. The issues in this repo are for content feedback, can you let me know the URL of the article that goes with this feedback so I can pass it along to the correct author? If this is a product issue (something not working properly, or a feature request), please file an issue here: https://developercommunity.visualstudio.com/spaces/21/index.html

Thank you.


Translation: `
Click Alert Settings to display the pop-up window. Object references are not set to the object instance.
Click Send test email, enter the receiving email address and email content, and click OK. The pop-up window displays TF400320: Email is not supported. Please contact your administrator.`

**Comment by steved0x** [comment]
I'm closing this issue since it is not associated with a topic. To continue the discussion, please open a new issue that is associated with a topic by browsing to the topic on docs.microsoft.com and choosing **Content feedback** at the bottom. Thank you for your feedback.

![image](https://user-images.githubusercontent.com/1580889/42953695-fd174150-8b48-11e8-94de-26924ca79c71.png)
