### ISSUE TITLE
Are service connection credentials stored securely on VSTS?

### ISSUE THREAD

**Issue by itsakettle** [MicrosoftDocs/vsts-docs#1594]
Hi, when you are creating a new service connection you commonly enter credentials e.g. a username and password. How does VSTS store these credentials? Are they encrypted and stored securely?

In the documentation for variable groups this is done well where it says `If you want to encrypt and securely store the value, choose the "lock" icon at the end of the row. When you're finished adding variables, choose Save.` which is great because the docs confirm that the credentials are stored securely. However the storage method of service connection credentials is not confirmed in the documentation for creating a service connections, so I'm wondering if the credentials are stored securely.

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72b90dd0-49f9-4ed4-3010-9a64dde6ae5a
* Version Independent ID: 6e679d50-4e94-eee3-8793-af884cc909ca
* Content: [Service connections in VSTS and Team Foundation Server](https://docs.microsoft.com/en-us/vsts/pipelines/library/service-endpoints?view=vsts#sep-github)
* Content Source: [docs/pipelines/library/service-endpoints.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/library/service-endpoints.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment]
The answer is yes. The secrets are always encrypted when stored.
You might also be interested in VSTS-KeyVault integration. https://docs.microsoft.com/en-us/vsts/pipelines/tasks/deploy/azure-key-vault?view=vsts

**Comment by keggster101020** [comment]
@alexhomer1  Would you be able to comment on what type of encryption the secrets are using and if this is one way or two way encryption? 

Also, do extensions have access to the plain secret or encrypted secret only?

Note that I'm not entirely interested in using KeyVault here because a lot of marketplace extensions require connection strings and not just variables.


Thanks!
