### ISSUE TITLE
Add missing integrations

### ISSUE THREAD

**Issue by jawn** [MicrosoftDocs/vsts-docs#1596]
New integration types are available and should be listed in this page.

Example: Office 365

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 634d1b6c-a9ca-6188-a262-2fd23ea8df8f
* Version Independent ID: ded5ff86-199d-1251-5b51-5c52af444447
* Content: [Integrate VSTS with third party apps using service hooks](https://docs.microsoft.com/en-us/vsts/service-hooks/index?view=vsts)
* Content Source: [docs/service-hooks/index.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/service-hooks/index.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by elbatk** [comment]
Hi @jawn , this definitely needs to be done! taking a work item for it now.

**Comment by elbatk** [comment]
Hey @jawn , we are updating our service hooks docs as a whole right now, I'll make sure to add O365 as an integration type.
