### ISSUE TITLE
Fix spelling

### ISSUE THREAD

**Issue by jawn** [MicrosoftDocs/vsts-docs#1598]
have to test cod -&gt; code

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 59d3d423-7069-b03e-cc30-0facb8ab8a9f
* Version Independent ID: e00f9545-4c96-7e52-915a-b1bd5cdbcfdc
* Content: [Progressive Experimentation with Feature Flags - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/learn/devops-at-microsoft/progressive-experimentation-feature-flags)
* Content Source: [https://mseng.visualstudio.com/DefaultCollection/TechnicalContent/_git/devops-learn-pr?path=%2fdocs%2fdevops-at-microsoft%2fprogressive-experimentation-feature-flags.md&version=GBlive&_a=contents](https://mseng.visualstudio.com/DefaultCollection/TechnicalContent/_git/devops-learn-pr?path=%2fdocs%2fdevops-at-microsoft%2fprogressive-experimentation-feature-flags.md&version=GBlive&_a=contents)
* Product: **devops**
* Git Login: **samgu**
* Microsoft Alias: **buckh**

**Comment by steved0x** [comment]
@jawn Thanks for letting us know, I'm fixing this right now and it should be live soon.
