### ISSUE TITLE
Link limit is actually 1000, not 5000

### ISSUE THREAD

**Issue by japj** [MicrosoftDocs/vsts-docs#16]
https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/work/track/link-work-items-support-traceability.md mentions a maximum of 5000 link limit.

This is apparently incorrect, the actual limit seems to be 1000 as can be seen from:
https://developercommunity.visualstudio.com/content/problem/71010/shared-step-link-limit-of-1000-maximum-error.html
https://visualstudio.uservoice.com/forums/330519-visual-studio-team-services/suggestions/30948445-increase-the-link-limit-for-work-item-types

**Comment by steved0x** [comment]
@japj Thank you for your contribution, we are reviewing it and will get back to you shortly. Please accept our apologies for this initial delay while we work though the initial backlog of contributions.

**Comment by steved0x** [comment]
@japj Thank you again for your contribution, this issue has been fixed (a while back) and I am closing this issue. Thank you!
