### ISSUE TITLE
What version of TFS is required for 'Publish a Git repository to a wiki'?

### ISSUE THREAD

**Issue by pegasy** [MicrosoftDocs/vsts-docs#1601]
We are currently on TFS 2018 (16.122.27102.1) and I can only find / see the wiki for the project but can't find anything about how to publish a git repo as a wiki like this doc suggests and I didn't find any mention of that specific feature for the 2018 update 2 feature list (https://docs.microsoft.com/en-us/visualstudio/releasenotes/tfs2018-update2#wiki) (or update 1 or 3 either). 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8d4fe5c7-0ab6-a0e4-4a6e-f98d0355f49a
* Version Independent ID: ce022fef-054d-cdc2-43e9-a8ee3b8fb592
* Content: [Publish markdown files from a Git repository to a wiki - VSTS](https://docs.microsoft.com/en-us/vsts/project/wiki/publish-repo-to-wiki?view=vsts#publish-a-git-repository-to-a-wiki-1)
* Content Source: [docs/project/wiki/publish-repo-to-wiki.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/project/wiki/publish-repo-to-wiki.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by nschonni** [comment]
https://docs.microsoft.com/en-us/vsts/release-notes/ lists it as 2019. If you change the version in the top left, you'll see
>The requested page is not available for Team Foundation Server 2018. You have been redirected to the newest product version this page is available for.

**Comment by pegasy** [comment]
Ok, thanks a lot, will bookmark that page, quite useful 👍
