### ISSUE TITLE
Stakeholder git wiki access

### ISSUE THREAD

**Issue by twem** [MicrosoftDocs/vsts-docs#1602]
We have a wiki published from a vsts git repo.
We now need our stakeholders to be able to read pages within the wiki, I can not file the correct permission combination to allow this. They are a "Reader" on the git repo.
I know Stakeholder can not see code, they are access it through the wiki tab.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c86f5178-e331-f45e-b60a-f0f3955f7a08
* Version Independent ID: 8a0882a7-8f48-32bb-c741-12976b428c38
* Content: [Manage permissions for READMEs and wiki pages - VSTS & TFS](https://docs.microsoft.com/en-us/vsts/project/wiki/manage-readme-wiki-permissions?view=vsts#stakeholder-wiki-access)
* Content Source: [docs/project/wiki/manage-readme-wiki-permissions.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/project/wiki/manage-readme-wiki-permissions.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@twem - Thank you for your inquiry, and sorry for the delay. I've requested our PM to respond as I'm not sure what the access levels are for Stakeholders with regards to code published as wiki.

**Comment by jorupp** [comment]
Is this the same as https://visualstudio.uservoice.com/forums/330519-visual-studio-team-services/suggestions/33980284-allow-stakeholders-to-view-wikis-published-from-co ?  Ie. this is a wiki published from a repository vs. the default wiki for the project?

**Comment by twem** [comment]
@jorupp yes it is the same issue.

**Comment by adramasu** [comment]
@twem @jorupp We currently don't allow stakeholder view access for code wiki. This being a security risk as the code and the hierarchy will be visible, we have restricted stakeholder view only to project wiki. Please upvote the uservoice mentioned by @jorupp. You will be updated if and when we decide on taking it up. Thank.

**Comment by jorupp** [comment]
@adramasu - doesn't the "code wiki" feature only allow `.md` files from branches published to the wiki to be viewed?  Ie. not code?

Also, it seems odd to security as a reason to decide how to license the product.  I can understand that there was a decision made to require a basic license for that feature, just seems odd to claim it's in the name of security.

**Comment by twem** [comment]
@adramasu we have a dedicated repo for the wiki.
I agree with @jorupp how can you say this is a security feature, it should at least be configurable to allow stakeholders to access the wiki if the admin user determines that it is not a security risk.

**Comment by twem** [comment]
MS Premier support were as much help. REG:118092019053454
We need to up vote the UserVoice issue.

**Comment by MichelZ** [comment]
This is a weird decision...  Please re-evaluate this.

**Comment by bbarman4u** [comment]
This should be up voted too

**Comment by chadschroeder-ctr** [comment]
Awesome - all that work into generating a wiki for stakeholders that they will never see. Yay 'security'!

**Comment by MikeMartin180** [comment]
Yup, would rather use a git based wiki, but it's use is limited, particularly at large companies, if you need a licence to view it.

**Comment by Retik** [comment]
This issue should be reopened. It's unreasonable that the people who need access to the wiki can't be granted access without being a developer. What's the point then? I'm sure it's technically possible to separate the access controls of the wiki from the code repo.

**Comment by KathrynEE** [comment]
@Retik - SInce this is not a document issue, but a product issue - the appropriate place is to request a feature be supported. In fact, there is a feature request here: [Allow Stakeholders to edit Wiki](https://developercommunity.visualstudio.com/idea/365837/allow-stakeholders-to-edit-wiki.html). You can upvote the feature there, which appears it is under review. Best regards.
