### ISSUE TITLE
Rule for changing State on adding a PR?

### ISSUE THREAD

**Issue by Efreeto** [MicrosoftDocs/vsts-docs#1604]
Is it possible to create a rule that will change either the State (e.g. from 'In Progress' to 'Resolved') or the Board Column (e.g. from 'Active' to 'PR') on condition of when a Pull Request was attached to a Work Item?

**Comment by steved0x** [comment]
@Efreeto I don't know a way from the Pull Request side, but I am forwarding this feedback to one of our authors for Azure Boards to see if they know.

**Comment by KathrynEE** [comment]
@Efreeto  - Thank you for your inquiry. This isn't a supported feature at this time. You may want to add it as a request through our user voice page - https://visualstudio.uservoice.com/forums/330519-team-services.

**Comment by WilliamAntonRohm** [comment]
@matteo-fantin -- Matteo, thank you for your follow-up.  Please add it here:
- [Developer Community](https://developercommunity.visualstudio.com/AzureDevOps)
