### ISSUE TITLE
How to fail on std error?

### ISSUE THREAD

**Issue by lukewis** [MicrosoftDocs/vsts-docs#1606]
How can I configure this task to fail on std error?  This would be helpful for npm test as well as npm start (I have some commandline utilities that I run as a scheduled build in vsts).  However, the build still completes successfully, even if these tasks write to std error.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c00d3b8-64c1-9f1b-83f8-62d8cf07817b
* Version Independent ID: 5fcdebed-cfb8-c5a6-d807-1315b2db5e57
* Content: [npm](https://docs.microsoft.com/en-us/vsts/pipelines/tasks/package/npm?view=vsts)
* Content Source: [docs/pipelines/tasks/package/npm.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/package/npm.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by elbatk** [comment]
Bringing @alexmullans in here to help with this one, @lukewis :)

**Comment by alexmullans** [comment]
@keithrob thoughts?

**Comment by lukewis** [comment]
Many thanks guys!  A non-zero exit code did the trick for me.  I was barking up the right tree.  I had a try-catch block and I ran process.exit(-1) from the catch block.  However, the root cause of my issue turned out to be an [unhandled promise rejection](https://github.com/nodejs/node/issues/20392).  I was using ES2015 async/await and I had missed an "await" statement.  Since I was writing typescript, TSLint and the no-floating-promises rule enabled me to find the culprit.  This has tripped me up more than once!  Hopefully NodeJS will eventually make a way to terminate the process with a non-zero exit code when this situation arises!  Thanks again for helping guide me in the right direction!
