### ISSUE TITLE
Links to files in repo instead of public URLs

### ISSUE THREAD

**Issue by gbellmann** [MicrosoftDocs/vsts-docs#1608]
The links for the items in the [**Related articles** section](https://docs.microsoft.com/en-us/vsts/boards/work-items/guidance/agile-process#related-articles) are pointing to the .md files, instead of the URL, which results in a 404 when clicked:

1. **Sign up for VSTS** link returns a 404 even after removing the **.md**, it's missing /vsts/ in the path.
Current: https://docs.microsoft.com/user-guide/sign-up-invite-teammates.md
Correct: https://docs.microsoft.com/en-us/vsts/user-guide/sign-up-invite-teammates
1. **Create a project**
Current: https://docs.microsoft.com/en-us/vsts/organizations/projects/create-project.md
Correct: https://docs.microsoft.com/en-us/vsts/organizations/projects/create-project
1. **Add work items to manage a project**
Current: https://docs.microsoft.com/en-us/vsts/boards/backlogs/add-work-items.md
Correct: https://docs.microsoft.com/en-us/vsts/boards/backlogs/add-work-items
1. **Create a backlog**
Current: https://docs.microsoft.com/en-us/vsts/boards/backlogs/create-your-backlog.md
Correct: https://docs.microsoft.com/en-us/vsts/boards/backlogs/create-your-backlog
1. **Plan a sprint**
Current: https://docs.microsoft.com/en-us/vsts/boards/sprints/assign-work-sprint.md
Correct: https://docs.microsoft.com/en-us/vsts/boards/sprints/assign-work-sprint
1. **Kanban**
Current: https://docs.microsoft.com/en-us/vsts/boards/boards/kanban-basics.md
Correct: https://docs.microsoft.com/en-us/vsts/boards/boards/kanban-basics
1. **Excel**
Current: https://docs.microsoft.com/en-us/vsts/boards/backlogs/office/bulk-add-modify-work-items-excel.md
Correct: https://docs.microsoft.com/en-us/vsts/boards/backlogs/office/bulk-add-modify-work-items-excel
1. **Project**
Current: https://docs.microsoft.com/en-us/vsts/boards/backlogs/office/create-your-backlog-tasks-using-project.md
Correct: https://docs.microsoft.com/en-us/vsts/boards/backlogs/office/create-your-backlog-tasks-using-project

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 705dda6e-d073-7df4-eb99-33e3ef858e09
* Version Independent ID: 8fa9c990-26e8-742b-9446-0946d892307e
* Content: [Agile process template artifacts - VSTS & TFS](https://docs.microsoft.com/en-us/vsts/boards/work-items/guidance/agile-process?view=vsts)
* Content Source: [docs/boards/work-items/guidance/agile-process.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/boards/work-items/guidance/agile-process.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by steved0x** [comment]
@gbellmann Thank you for letting us know, these are fixed as of today. If you see anymore, please let us know. Thank you!
