### ISSUE TITLE
TFS 2015 Update 4 fails on update test result using API in this doc

### ISSUE THREAD

**Issue by trinhpham** [MicrosoftDocs/vsts-docs#1609]
PATCH http://[MyIP]:8080/tfs/DefaultCollection/[Myproject]/_apis/test/runs/16/results
With content:
```
[
  {
    "comment": "My code is looking good",
    "id": 100000,
    "outcome": "Passed",
    "state": "Completed"
  },
  {
    "comment": "My code is looking good",
    "id": 100001,
    "outcome": "Passed",
    "state": "Completed"
  },
  {
    "comment": "My code is looking good",
    "id": 100002,
    "outcome": "Passed",
    "state": "Completed"
  }
]
```

Give the error:
```
{
"$id": "1",
"innerException": null,
"message": "TestResult Id must be specified Parameter name: TestResult",
"typeName": "System.ArgumentException, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089",
"typeKey": "ArgumentException",
"errorCode": 0,
"eventId": 0
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6230c0d7-683f-b97b-bcdf-deef64dd9722
* Version Independent ID: 8ebb6ec5-1251-11fd-a8b6-beba6f71c9c3
* Content: [Test Results](https://docs.microsoft.com/en-us/vsts/integrate/previous-apis/test/results?view=tfs-2015#update-test-results-for-a-test-run)
* Content Source: [docs/integrate/previous-apis/test/results.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/integrate/previous-apis/test/results.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by aluitink** [comment]
Is there any workaround for this issue?

**Comment by elbatk** [comment]
Closing this issue as that workaround seems to be working and these are older APIs.

**Comment by trinhpham** [comment]
Hi @elbatk

I don't think this is a good way to handle the issue.
Old APIs are still APIs and people (like me) are still working on them. You should understand how difficult your unclear document makes to us at the starting point.
IMO, if the API has different signature to the document, you must update the document. Otherwise, the document is useless and shouldn't be standed there.
Anyone agree with me?
