### ISSUE TITLE
How to Copy Files into multiple places?

### ISSUE THREAD

**Issue by zwcloud** [MicrosoftDocs/vsts-docs#1610]
For example, Foo.dll needs to be copied to `Bar1/`, `Bar2/`, `Bar3/` and `Bar4/`. How can I do that in a single *Copy Files* task?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c028a99-45f1-3609-3219-89789dc6b966
* Version Independent ID: f626f40e-1bab-4d8a-cd19-ab3b5da4be0a
* Content: [Artifacts in Team Build](https://docs.microsoft.com/en-us/vsts/pipelines/build/artifacts?view=vsts)
* Content Source: [docs/pipelines/build/artifacts.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/build/artifacts.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by zwcloud** [comment]
In TeamCity, we can use artifact path to achieve that:

SomeWhere/Foo.dll => Bar1/Foo.dll
SomeWhere/Foo.dll => Bar2/Foo.dll
SomeWhere/Foo.dll => Bar3/Foo.dll
SomeWhere/Foo.dll => Bar4/Foo.dll

But it seems impossible in VSTS.

**Comment by vtbassmatt** [comment]
Multiple destinations isn't supported by the Copy Files task. You could use a `bash` step with `xargs` as a workaround:

```yaml
- bash: echo Bar1 Bar2 Bar3 Bar4 | xargs -n 1 cp SomeWhere/Foo.dll
```
