### ISSUE TITLE
Suspected mis-reference: using "organization" when it should be "enterprise".

### ISSUE THREAD

**Issue by skeeler** [MicrosoftDocs/vsts-docs#1611]
Search for the phrase "The organization will be similar to the TFS deployment, and the organization will be similar to the TFS collection." in the document. The first "organization" in this sentence should probably be "enterprise". I.e. "The enterprise will be similar to the TFS deployment, and the organization will be similar to the TFS collection."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a830bcfa-4584-922f-f28c-531cb59a454e
* Version Independent ID: 4f288fb1-78b1-0339-6627-316f6fb7686a
* Content: [Understand differences between VSTS and TFS](https://docs.microsoft.com/en-us/vsts/user-guide/about-vsts-tfs?view=vsts)
* Content Source: [docs/user-guide/about-vsts-tfs.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/user-guide/about-vsts-tfs.md)
* Product: **devops**
* GitHub Login: @erickson-doug
* Microsoft Alias: **kaelli**

**Comment by peternield** [comment]
I think this needs to be addressed in other places in that same section as well. e.g "having your work split across multiple organizations can cause some problems, but we plan to address these when the organization entity is introduced" - it is a little hard to create multiple organizations before the organization entity is introduced.

**Comment by KathrynEE** [comment]
@skeeler - Thank you for the feedback. The topic has been updated and some content removed. We will revisit this in an upcoming update.
