### ISSUE TITLE
[warning]No test assemblies found matching the pattern

### ISSUE THREAD

**Issue by hamed-shirbandi** [MicrosoftDocs/vsts-docs#1613]
I use TFS online to build and release my sample project that contains unit-tests and ui-tests (selenium).
I want to run selenium tests after deploying to staging. but during my Visual Studio Test step, I'm getting the following message :

2018-08-27T21:12:25.6374709Z ##[warning]No test assemblies found matching the pattern: **\bin\Release\netcoreapp2.1\\*.UITests.dll.

search folder value is : $(System.DefaultWorkingDirectory)

and i try following patterns:

 **\\*.UITests.dll

 **\\$(BuildConfiguration)\\*.UITests.dll

but still gives that warning message and my selenium tests in DevOpsProject.UITests.dll not run

what should I do?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 09e51d18-72ec-1ad4-9ae7-8185c8e1dcd6
* Version Independent ID: 9f2f0471-d123-8e95-1606-cd811d1ece9a
* Content: [Selenium testing with continuous integration in VSTS - test automation tools](https://docs.microsoft.com/en-us/vsts/pipelines/test/continuous-test-selenium?view=vsts#)
* Content Source: [docs/pipelines/test/continuous-test-selenium.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/test/continuous-test-selenium.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment]
Thank you for your feedback. I have passed this on to the product team for advice.

**Comment by PBoraMSFT** [comment]
Have you verified that the search folder actually contains the necessary test assemblies?
If you have issues using the VSTest task, please log them on the tasks repo https://github.com/Microsoft/vsts-tasks/

Closing this issue here as it's not about the docs.

**Comment by hamed-shirbandi** [comment]
I solved it.
the problem was that the build definition has been run by Hosted VS2017 agent and the release definition run by own agent.

In release, the DefaultWorkingDirectory is an address on my private server (C:\vstsagent\A4\_work\r3\a) and this address only contains artifact files downloaded from build agent (Hosted VS2017) so tfs cant find any test dll.

to solve this problem you have 2 options:
1- make bulid and release agent as same.
2- add test projects to publish artifact by unchecking Publish Web Projects and Zip Published Projects in publish task.

**Comment by CodeeYogi** [comment]
I am facing the same issue . I confirmed tbat both Build and Release are in the same queue.
But they are in different machines.

And I don't see a check box for Publish Web Projects . Can you send a screen capture.
