### ISSUE TITLE
The link in "Build and Release pipeline by using the Visual Studio Test task." is wrong 

### ISSUE THREAD

**Issue by tronda** [MicrosoftDocs/vsts-docs#1614]
The link in "Build and Release pipeline by using the Visual Studio Test task." is wrong. It points now to https://github.com/Microsoft/vsts-tasks/blob/master/Tasks/VsTest/README.md

but it should point to:
https://github.com/Microsoft/vsts-tasks/blob/master/Tasks/VsTestV2/README.md

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7d8a7e40-73d6-795f-7b8c-77104ef606e8
* Version Independent ID: 8f15995b-bd94-8d9f-1e8b-82f1f364d221
* Content: [Associate an automated test with a test case](https://docs.microsoft.com/en-us/vsts/test/associate-automated-test-with-test-case?view=vsts)
* Content Source: [docs/test/associate-automated-test-with-test-case.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/test/associate-automated-test-with-test-case.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment]
Thank you for your feedback. I will update the topic to include your recommendations.
