### ISSUE TITLE
System.PullRequest variables not populating

### ISSUE THREAD

**Issue by AnirvanK** [MicrosoftDocs/vsts-docs#1615]
Hi,

Referring to the documentation: https://docs.microsoft.com/en-us/vsts/pipelines/build/variables?view=vsts

I'm using a Command Line task in the Build Definition and logging the below variables to check the values. But none of them are populating as a result of a PR.

echo $(System.PullRequest.IsFork)
echo $(System.PullRequest.PullRequestId)
echo $(System.PullRequest.PullRequestNumber)
echo $(System.PullRequest.SourceBranch)
echo $(System.PullRequest.SourceRepositoryURI)
echo $(System.PullRequest.TargetBranch)
[Script Logs.txt](https://github.com/MicrosoftDocs/vsts-docs/files/2328697/Script.Logs.txt)

**Comment by andyjlewis** [comment]
Are you using TFS or Azure DevOps Services? is your repo in GitHub or Azure Repos?

**Comment by C123R** [comment]
I am facing this issue as well, trying to use $(System.PullRequest.PullRequestId) in our release job.

**Comment by bmoore-msft** [comment]
Also, hit the same issue...

**Comment by Joel-INTO** [comment]
Also hit the same issue. Any news?

**Comment by kieseld** [comment]
This is closed but I do not see any solution. These variables are also not working for our releases.

**Comment by Lauchi** [comment]
I guess this is not supposed to work in the release pipeline. But I would love something like that, too, as I would like to deploy based on the PR Number to a different environment. On the docs I only see this variable mentioned for builds, not for releases...

**Comment by vhp1895** [comment]
I'm using GitLab. Cant use $(System.PullRequest.PullRequestId) in either Build or Release

**Comment by Mhart12** [comment]
I'm unable to use $(System.PullRequest.SourceBranch) as well for Bitbucket project

**Comment by mvrmoreira** [comment]
I'm having the same issue trying to use pullrequests variables in azure pipelines for github repo

**Comment by wendallmartin** [comment]
I am unable to use $(System.PullRequest.SourceBranch) as well for Azure Devops project

**Comment by hisuwh** [comment]
Classic microsoft closing an issue without any solution or even reply.
Also facing this

**Comment by mehric** [comment]
One year later, it still doesn't work. Did anybody find any working solution for this?

**Comment by hvaandres** [comment]
I have another example here: [similar issue](https://github.com/MicrosoftDocs/azure-devops-docs/issues/11644)

**Comment by jontreynes** [comment]
I was able to get it to populate in a powershell script using macro syntax as described here
https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch#understand-variable-syntax


```
        - task: PowerShell@2
          inputs:
            targetType: 'inline'
            script: |
              if ( "$(Build.SourceBranchName)" -like "merge") {
                Write-Host "This is a PR. Creating a branch path based on the branch name"

                if ("$(System.PullRequest.SourceBranch)" -like "models"){
                  Write-Host "This is a models branch"
                  $branchFolder = "$(System.PullRequest.SourceBranch)"
                }
                else {
                  Write-Host "This is a non models branch"
                  $branchFolder = "$(Build.SourceBranchName)"
                } 
              }
```

However, for my purposes, I need it at the template level in an if condition like this. It does not populate using a template expression syntax
```
  - template: ./templates/mytemplate.yml
    parameters:
      ${{ if startswith(variables['System.PullRequest.SourceBranch'], 'models/') }}:  #this does not work and is not true when the branch is named something like models/modelA
        environment: "${{parameters.environment}}_models"
```

**Comment by bilby91** [comment]
Same here. I think that the only case I saw this working was when the target branch was a pull request. That would kind of make sense if properly documented.

**Comment by ncook-hxgn** [comment]
moi aussi
