### ISSUE TITLE
Provide json schema on/for schemastore.org

### ISSUE THREAD

**Issue by jacksga** [MicrosoftDocs/vsts-docs#1617]
Though this page being very detailed, users would have it easier to start developing extensions if there was a schema (e.g. on schemastore.org) for this to use in VS / VS Code.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d8b703fe-8982-4284-6db0-ef33abac08a4
* Version Independent ID: 0fc84d11-1c32-0a49-04ec-641b68f44886
* Content: [Extension Manifest Reference](https://docs.microsoft.com/en-us/vsts/extend/develop/manifest?view=vsts)
* Content Source: [docs/extend/develop/manifest.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/extend/develop/manifest.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by elbatk** [comment]
Hi @jacksga , you can provide product team feedback on the [developer community site](https://developercommunity.visualstudio.com/spaces/21/index.html), or posts/vote on requests to functionality in our [UserVoice](https://visualstudio.uservoice.com/forums/330519-visual-studio-team-services). Closing this issue as it does not pertain to the online documentation.
