### ISSUE TITLE
Branch policy change history

### ISSUE THREAD

**Issue by Blackbaud-LoriWeiss** [MicrosoftDocs/vsts-docs#1618]
Is there a way to view the change history for branch policies? We would like to be able to tell who/when/what was last changed in our branch policies.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7cd986e0-608c-1d8c-6faf-ecdb12e10bc6
* Version Independent ID: d60c996e-187e-dd6b-7f3a-dd056a1603f4
* Content: [Protect your Git branches with policies](https://docs.microsoft.com/en-us/vsts/repos/git/branch-policies?view=vsts)
* Content Source: [docs/repos/git/branch-policies.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/repos/git/branch-policies.md)
* Product: **devops**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
@Blackbaud-LoriWeiss See https://github.com/MicrosoftDocs/vsts-docs/issues/341, you can get a list of historical revisions for branch policy using the VSTS code policies API [here:]( https://docs.microsoft.com/en-us/rest/api/vsts/policy/revisions/get?view=vsts-rest-4.1). If you are looking for other functionality in this area, please file a UserVoice request [here](https://developercommunity.visualstudio.com/spaces/21/index.html). Please reactivate this issue if this doesn't answer your question. Thank you!
