### ISSUE TITLE
Don't use a flowchart image; it's misleading

### ISSUE THREAD

**Issue by matchavez** [MicrosoftDocs/vsts-docs#1619]
Please reconsider the use of a flowchart as the image choice for this markdown reference page. Many systems actually support flowcharting within markdown, most often Mermaid.

[Demo page](https://docs.microsoft.com/en-us/vsts/project/wiki/markdown-guidance?view=vsts)
[Mermaid](https://mermaidjs.github.io)

It would be better if you supported it, but in the meantime, the image makes it look like you handle that when you don't.

-Mat

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fa622358-f5bb-1f5c-177a-081a37b6acef
* Version Independent ID: 72f7fd16-a822-66c8-3a34-8905645ce5f2
* Content: [Syntax usage for Markdown files, widgets, wikis, and pull requests - VSTS & TFS](https://docs.microsoft.com/en-us/vsts/project/wiki/markdown-guidance?view=vsts)
* Content Source: [docs/project/wiki/markdown-guidance.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/project/wiki/markdown-guidance.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@matchavez  - Thank you for the feedback. I've updated the image accordingly.

**Comment by matchavez** [comment]
Unfortunately, it has not changed. I gave it a few hours, but it still appears to show a flowchart as an image... I wouldn't consider this closed.

![screen shot 2018-09-11 at 16 15 20](https://user-images.githubusercontent.com/1787040/45338328-a5935c80-b5e0-11e8-93f7-25aac416ae07.png)
