### ISSUE TITLE
missing an angle bracket in the Column and Tab Description

### ISSUE THREAD

**Issue by keenam** [MicrosoftDocs/vsts-docs#1620]
both Column and Tab description are missing an angle bracket (&gt;)
`&lt;Group&gt; . . . &lt;/Group`

Group description has an extra space for xlm element
`&lt;/Group &gt;`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 80238ac1-38f6-b664-c138-c80f1521b0bf
* Version Independent ID: 0e68d9bc-a4c0-5788-3eea-961936ad62a5
* Content: [All FORM XML elements reference - VSTS & TFS](https://docs.microsoft.com/en-us/vsts/reference/xml/all-form-xml-elements-reference?toc=/vsts/reference/toc.json&bc=/vsts/reference/breadcrumb/toc.json&view=vsts)
* Content Source: [docs/reference/xml/all-form-xml-elements-reference.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/reference/xml/all-form-xml-elements-reference.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@keenam  - Thank you for the feedback. I'm updating the topic as needed.
