### ISSUE TITLE
Time to update this Guide, because managed portal no longer available 

### ISSUE THREAD

**Issue by SychevIgor** [MicrosoftDocs/vsts-docs#1623]
Time to update this Guide, because managed portal no longer available 
also VSTS UX was updated few years ago.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 27626fdf-53fb-52f5-9d05-82dc3dbe5048
* Version Independent ID: bf7ad83f-1640-f545-7967-0301fc3e2108
* Content: [Azure Service Bus with VSTS](https://docs.microsoft.com/en-us/vsts/service-hooks/services/azure-service-bus?view=vsts)
* Content Source: [docs/service-hooks/services/azure-service-bus.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/service-hooks/services/azure-service-bus.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by elbatk** [comment]
Hi @SychevIgor , you're right, taking on a work item for updating this.

**Comment by SychevIgor** [comment]
nothing had changed for 3 months
