### ISSUE TITLE
Time to update this Guide, because managed portal no longer available 

### ISSUE THREAD

**Issue by SychevIgor** [MicrosoftDocs/vsts-docs#1624]
Time to update this Guide, because managed portal no longer available 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8cd475cc-3510-5c4b-29e0-698eab618041
* Version Independent ID: bf3fff29-d364-b8ee-78ea-620363067c0e
* Content: [Azure Storage with VSTS](https://docs.microsoft.com/en-us/vsts/service-hooks/services/azure-storage?view=vsts)
* Content Source: [docs/service-hooks/services/azure-storage.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/service-hooks/services/azure-storage.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by elbatk** [comment]
Hi @SychevIgor , you're right, taking on a work item for updating this now.

**Comment by SychevIgor** [comment]
nothing had changed for 3 months
