### ISSUE TITLE
Success criteria: Response code

### ISSUE THREAD

**Issue by svrooij** [MicrosoftDocs/vsts-docs#1625]
I would love to see some documentation about the Success criteria and specialy about how we should check the response code to be 200 for example. So not checking the content of the response (what I once found on some other page), but just the response code.
We have an endpoint that returns 200 when everything is fine and 500 when there is something wrong with the applicatation.

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: 89bc6da4-5a1e-5989-f4f0-27465953b5fd
* Version Independent ID: fd12f976-5d3b-3b1b-3d0a-a0bf2a60c961
* Content: [Invoke HTTP REST API task for Microsoft VSTS and TFS](https://docs.microsoft.com/nl-nl/vsts/pipelines/tasks/utility/http-rest-api?view=vsts)
* Content Source: [docs/pipelines/tasks/utility/http-rest-api.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/utility/http-rest-api.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment]
Thank you for your feedback. I have passed this on to the product team for advice.

**Comment by svrooij** [comment]
With the Github search I found something [here](https://github.com/Microsoft/vsts-tasks/blob/1d75fa8f66aa1cf7a9cb62946939f30f087b2969/Tasks/AzureMonitorV0/task.loc.json).

So I think the following should work:
```js
and(gt(count(root['responses']), 0), eq(count(jsonpath('$.responses[?(@.httpStatusCode != 200)]')), 0))
```

But that would be a great example 😉

**Comment by ParidaPunyasloka** [comment]
How would I store data (in a variable) from a "GET" request? and use it for a "PUT" or "POST" request?

**Comment by shashban** [comment]
Output variables are not supported by the invoke REST API task

**Comment by sunny1704** [comment]
I have a similar scenario as above. I am doing a POST which sends the request ID back after initiating a process. I need to parse that request ID from the response object to call a GET API later. Any thoughts on how to achieve this?

**Comment by shashban** [comment]
You can't achieve this with the task itself. But you can author your own task, use [HttpRequestChain](https://github.com/microsoft/azure-pipelines-tasks/blob/master/docs/authoring/servertaskauthoring.md) to  call updateRelease in the task

**Comment by sunny1704** [comment]
Appreciate the prompt response. So if I understand it right based on the link which you shared, I need to write a server task with action type as httpRequestChain. In this, I build a sequence of my API calls. 

I am assuming I need to use build in YAML format to achieve this as I was using classic editor so far for my build pipeline. Is that correct? 

Also, there needs to be a delay between my POST and GET requests. Will that be feasible with this approach?
