### ISSUE TITLE
Lots of images are showing as markdown instead of the image

### ISSUE THREAD

**Issue by sferg-msft** [MicrosoftDocs/vsts-docs#1626]
Example: [backlog]((../../boards/backlogs/create-your-backlog.md)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad73cae9-9b23-078d-2b95-d83cc794df03
* Version Independent ID: 3aa17c7d-adca-6ca6-b1e0-e811f520b325
* Content: [Show bugs on backlogs and boards - VSTS & TFS](https://docs.microsoft.com/en-us/vsts/organizations/settings/show-bugs-on-backlog?view=vsts)
* Content Source: [docs/organizations/settings/show-bugs-on-backlog.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/settings/show-bugs-on-backlog.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by steved0x** [comment]
@sferg-msft Thank you for letting us know, I think we have got them all fixed up now, if you see any more please let us know. Thank you!
