### ISSUE TITLE
Add on QA as a prereq

### ISSUE THREAD

**Issue by ManuelGalindo** [MicrosoftDocs/vsts-docs#1627]
The user access level needs to be BASIC, this is not explained on any other part of the documentation 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4dc61b61-ed67-8313-99d4-d736e7f48234
* Version Independent ID: 3e0fcf87-9744-cec8-24f8-9f68371959c6
* Content: [Integrate with service hooks](https://docs.microsoft.com/en-us/vsts/service-hooks/overview?view=vsts#q--a)
* Content Source: [docs/service-hooks/overview.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/service-hooks/overview.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by elbatk** [comment]
Hi @ManuelGalindo , could you explain a bit about what you'd like to see changed here?

**Comment by elbatk** [comment]
There hasn't been any action here in a while, going to go ahead and close this one.
