### ISSUE TITLE
Feature Request: Automatically include code reviewers as Alice OR Bob

### ISSUE THREAD

**Issue by justrhysism** [MicrosoftDocs/vsts-docs#1629]
The ability to automatically include code reviewers for specific parts of the code base is fantastic. However it would be nice if this could be applied with an OR as an alternative to the AND.
e.g. Alice and Bob are reviewers: currently both are required to review the code and approve. Internal policy is that only one is required to pass acceptance. So code must be reviewed and accepted by Alice OR Bob.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7cd986e0-608c-1d8c-6faf-ecdb12e10bc6
* Version Independent ID: d60c996e-187e-dd6b-7f3a-dd056a1603f4
* Content: [Protect your Git branches with policies](https://docs.microsoft.com/en-us/vsts/repos/git/branch-policies?view=vsts)
* Content Source: [docs/repos/git/branch-policies.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/repos/git/branch-policies.md)
* Product: **devops**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by svrooij** [comment]
You can create a group of approvers and use that.

Creating groups (for various usages) is under Project Settings -> Security -> create group
Once you created a group you can use that as a required reviewer.

**Comment by justrhysism** [comment]
Brilliant! Works a treat! Is it worth adding that to the docs? Seems like a one liner with the relevant links would probably do it.

**Comment by svrooij** [comment]
You're probably right, but I'm not a microsoft employee that can fix that. 😄

**Comment by justrhysism** [comment]
@axdiamond ah yes, I found it. I guess I was looking for something maybe more explicit or clearer since I obviously missed it the first few times I browsed the docs.
