### ISSUE TITLE
Please update screenshots

### ISSUE THREAD

**Issue by mattfrear** [MicrosoftDocs/vsts-docs#1632]
Now that VSTS looks completely different, with the vertical menu bar, I can't figure out how to Change my default branch. I can't get past the first step "Select the settings icon while you have your project open" as I don't see a settings icon.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c8630b8-08ea-d706-e51c-03863b33d49e
* Version Independent ID: ad8a3b91-7b41-a6af-0d5c-b26355a49c7b
* Content: [Manage branches in your Git repo](https://docs.microsoft.com/en-us/vsts/repos/git/manage-your-branches?view=vsts#change-your-default-branch)
* Content Source: [docs/repos/git/manage-your-branches.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/repos/git/manage-your-branches.md)
* Product: **devops**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by mattfrear** [comment]
Thanks @steved0x

**Comment by steved0x** [comment]
@mattfrear I am checking in the new screenshots today and they should be live tonight or tomorrow. Thanks again for letting us know and sorry for the trouble.
