### ISSUE TITLE
JSON variable substitution docs seems incorrect

### ISSUE THREAD

**Issue by chrissena** [MicrosoftDocs/vsts-docs#1633]
According to the example JSON file DebugMode, DBAccess and FeatureFlags are all nested inside the Data field. However only the Data.DefaultConnection.ConnectionString variable has the 'Data.' prefix. Am I missing something or is this a mistake.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 315ff823-9992-9f9b-62a1-42ce622ed41c
* Version Independent ID: 72ec3ffc-1dc9-b2dc-e3d4-4f14deae3720
* Content: [File transforms and variable substitution](https://docs.microsoft.com/en-us/vsts/pipelines/tasks/transforms-variable-substitution?view=vsts#jsonvarsubs)
* Content Source: [docs/pipelines/tasks/transforms-variable-substitution.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/transforms-variable-substitution.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by Kunjahamed-P** [comment]
![tempsnip](https://user-images.githubusercontent.com/42990066/45298800-33127600-b527-11e8-82ad-987bebc29871.jpg)

can  i change AppSettings_Dev  name to AppSettings

**Comment by RoopeshNair** [comment]
@chrissena - you are right, here is the updated example. Will get this fixed. 

@Kunjahamed-P - No, you can change only the values not the key.

### JSON variable substitution example

As an example, consider the task of overriding values in this JSON file:
 
```json
{
  "Data": {
    "DefaultConnection": {
      "ConnectionString": "Data Source=(LocalDb)\MSDB;AttachDbFilename=aspcore-local.mdf;"
    },
    "DebugMode": "enabled",
    "DBAccess": {
      "Admininstrators": ["Admin-1", "Admin-2"],
      "Users": ["Vendor-1", "vendor-3"]
    },
    "FeatureFlags": {
      "Preview": [
        {
          "newUI": "AllAccounts"
        },
        {
          "NewWelcomeMessage": "Newusers"
        }
      ]
    }
  }
}

```
<p />

Define the required substitution values in release pipeline or stage variables.
 
   | Name | Value | Secure | Scope |
   | ---- | ----- | ------ | ----- |
   | Data.DebugMode | disabled | No | Release |
   | Data.DefaultConnection.ConnectionString | Data Source=(prodDB)\\MSDB;AttachDbFilename=prod.mdf; | No | Release |
   | Data.DBAccess.Users.0 | Admin-3 | Yes | Release |
   | Data.FeatureFlags.Preview.1.NewWelcomeMessage | AllAccounts | No | Release |
