### ISSUE TITLE
Managed Disk Images

### ISSUE THREAD

**Issue by Teodelas** [MicrosoftDocs/vsts-docs#1634]
This doesn't appear to support managed disk images.  Can you verify?  I can't get it to work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 061aa8bc-6c7f-82f6-e4c8-ed9370596daf
* Version Independent ID: 775c82ad-6f92-1b0f-ee84-59e01a33d78d
* Content: [Implement deployment of your app to Azure Virtual Machine Scale Set](https://docs.microsoft.com/en-us/vsts/pipelines/apps/cd/azure/deploy-azure-scaleset?view=vsts)
* Content Source: [docs/pipelines/apps/cd/azure/deploy-azure-scaleset.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/apps/cd/azure/deploy-azure-scaleset.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by bishal-pdMSFT** [comment]
@Teodelas The "Build immutable image" task has been updated to create managed image. You can use 1.* version of the task for this purpose.
