### ISSUE TITLE
yaml release definitions?

### ISSUE THREAD

**Issue by steve-hawkins** [MicrosoftDocs/vsts-docs#1639]
I've been using yaml on build definitions for awhile now and have been looking for ways of using something similar for the release definitions

I find it interesting that in the [Demands](https://docs.microsoft.com/en-us/vsts/pipelines/tasks/utility/manual-intervention?view=vsts#demands) section it states 'Can be used in only an agentless phase of a release pipeline.' and directly below there is a [YAML snippet](https://docs.microsoft.com/en-us/vsts/pipelines/tasks/utility/manual-intervention?view=vsts#yaml-snippet) to me this suggests that there is already some way to use yaml files on the release definitions?

The only other explanation I can think of is using solely build definitions and relying on conditioning around some sort of environment release branching?

Either way if you can point me to any documentation / blog posts or provide an explanation on how to define release definitions in code that would be greatly appreciated

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e1c633b9-c8b2-e05d-de2c-7754894d28fd
* Version Independent ID: df031b76-0fe7-e138-dd36-2736757a97fd
* Content: [Manual intervention task for Microsoft VSTS and TFS](https://docs.microsoft.com/en-us/vsts/pipelines/tasks/utility/manual-intervention?view=vsts)
* Content Source: [docs/pipelines/tasks/utility/manual-intervention.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/utility/manual-intervention.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment]
Thank you for your feedback. I have passed this on to the product team for advice.

**Comment by atrauzzi** [comment]
In addition to this, it would be nice to be able to pass parameters to releases when they are being created by automated processes.  Say, logic apps in Azure, timer triggers, etc...

Right now the only way to alter variables is on creation in the web UI and that obviously is very limiting.

**Comment by scottnasello** [comment]
we also use YAML build definitions and want YAML release definitions.

**Comment by janisBerz** [comment]
Yes, please give us yamal support for Release pipelines!
It's really hard to manage the release pipeliens when you have a lot of microservices to deploy to many environments. Takes ages to update task in all environments.

**Comment by shashban** [comment]
Thanks for the feedback. We are actively working on YAML support for release pipelines, and expect it to be available soon. As of now, YAML support is available for build pipelines only.
We'll also update the documentation of this task to avoid this confusion.

**Comment by timjkelly** [comment]
Any update on this? The link that @taspeotis shared is not a public link. We are very interested in using yaml for release definitions.

**Comment by taspeotis** [comment]
https://dev.azure.com/mseng/AzureDevOpsRoadmap/_workitems/edit/1364226

**Comment by celamb4** [comment]
+1 release pipelines tracked as YAML would be great. @taspeotis do you know if there will be support for templates such as with build pipelines? Ability to define reusable tasks for releases would be great. Not sure if this is part of this feature, an ehancement or a new feature request.

**Comment by taspeotis** [comment]
No idea. I'm not a Microsoft employee, I'm just pasting the "Multi-stage pipelines" link from [here](https://docs.microsoft.com/en-us/azure/devops/release-notes/).

**Comment by twsI** [comment]
+1

**Comment by katlimruiz** [comment]
release pipelines are there as of now, i created a multi-stage from build to prod and it worked. The issue is in my case that I need manual intervention yaml task to be able to deploy to PROD only after we run the manual testing required. Right now there is no way to pause a multistage pipeline. My temp solution is to create several yamls and have several pipelines (one for build, another for staging and another for production), definitely not the best solution as it hinders the visualization of what is pending and is not.

**Comment by MrBeanzy** [comment]
They may be available in multi stage pipelines. But this is no use when you are trying to orchestrate a release that has loads of micro services and 10's of environments. When can we expect YAML support for release? @katlimruiz ?

**Comment by shashban** [comment]
As Microsoft, we are pivoting to a common yaml schema for all CI/CD workflows, making it possible to have a single CI+CD pipeline or separate ones like you have had so far.
The ability to add approvals into the pipeline to pause for manual validations is currently not there in the preview. This is being actively worked on. Stay tuned for updates to the capabilities of yaml pipelines through the sprintly release notes.

**Comment by GeromeRen** [comment]
> release pipelines are there as of now, i created a multi-stage from build to prod and it worked. The issue is in my case that I need manual intervention yaml task to be able to deploy to PROD only after we run the manual testing required. Right now there is no way to pause a multistage pipeline. My temp solution is to create several yamls and have several pipelines (one for build, another for staging and another for production), definitely not the best solution as it hinders the visualization of what is pending and is not.

multi-stage working fine, but lacking of manual intervention. This is sad for predeployment approve for prod deploy and huge impact multi-stage release yml feature

**Comment by taspeotis** [comment]
> multi-stage working fine, but lacking of manual intervention. This is sad for predeployment approve for prod deploy and huge impact multi-stage release yml feature

They added this earlier in the week. You might need to give it a few days to roll out to your instance.

> ### [Approvals in multi-stage YAML pipelines](https://docs.microsoft.com/en-us/azure/devops/release-notes/2019/sprint-155-update#approvals-in-multi-stage-yaml-pipelines)
> 
> We continue to improve multi-stage YAML pipelines, we now let you add manual approvals to these pipelines.
