### ISSUE TITLE
Release Burndown for the Agile Template

### ISSUE THREAD

**Issue by sinaja** [MicrosoftDocs/vsts-docs#1642]
We would like to use the Release Burndown chart for the TFS Agile Template.  This means the report will need to support the roll up of Effort for User Stories.  Is there a way to already do this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b9d91df7-0706-9a0a-9268-2323a04fda90
* Version Independent ID: a0ebcab4-b02e-e307-a58e-3e654c7b155e
* Content: [Release Burndown - TFS](https://docs.microsoft.com/en-us/vsts/report/sql-reports/release-burndown?view=tfs-2018)
* Content Source: [docs/report/sql-reports/release-burndown.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/report/sql-reports/release-burndown.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@sinaja - Thank you for your inquiry. To use this report to use with an Agile template, you'll need to modify it to use the fields that the Agile template uses, or you'll have to have updated the Agile template to use Effort instead of Story Points.
