### ISSUE TITLE
MIssing IP addresses

### ISSUE THREAD

**Issue by automagicallyio** [MicrosoftDocs/vsts-docs#1644]
40.85.224.121 and 13.71.189.199 should be added to the list of IP addresses. Import tool fails when kicking off the import (for region Canada Central) for the first time pointing out that the IP addresses above need to be allowed. Import starts successfully after the IP addresses are allowed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a35b397-3fe8-122e-042e-280326f88a38
* Version Independent ID: 3e0f0afc-abeb-01be-d767-813cd6ad78db
* Content: [Migration import from TFS to Visual Studio Team Services (VSTS)](https://docs.microsoft.com/en-us/vsts/articles/migration-import?view=vsts)
* Content Source: [docs/articles/migration-import.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/articles/migration-import.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by elbatk** [comment]
@roofers is this the case? I can update if so.

**Comment by roofers** [comment]
I've got a PR going that will add these missing IPs. Thanks for reporting.

**Comment by steved0x** [comment]
@automagicallyio We are fixing this so I am closing this issue, thanks again for letting us know.
