### ISSUE TITLE
Cannot find "svc.sh" in the Linux agent download

### ISSUE THREAD

**Issue by natemcmaster** [MicrosoftDocs/vsts-docs#1645]
The documentation includes a section about "Run as a systemd service" which mentions a script named "svc.sh". I cannot find this script in the agent download or in github.com/Microsoft/vsts-agent. Where is this script?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 23328b13-f079-ad21-5d7a-6c640f25391c
* Version Independent ID: 4a39889d-fa00-ae2b-aa43-f358631b7b1a
* Content: [Deploy a build and release agent on Linux](https://docs.microsoft.com/en-us/vsts/pipelines/agents/v2-linux?view=vsts#download-and-configure-the-agent)
* Content Source: [docs/pipelines/agents/v2-linux.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/agents/v2-linux.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by natemcmaster** [comment]
Here is what I see:

![image](https://user-images.githubusercontent.com/2696087/45050679-c71ba380-b036-11e8-841b-709f3f0b937f.png)

**Comment by vtbassmatt** [comment]
Thanks for the feedback. svc.sh gets generated after you configure the agent. I will make this more clear in the docs.

**Comment by bateau84** [comment]
this is pointless when using saltstack or puppet...
