### ISSUE TITLE
Feature Missing: Display published CodeCoverage Results in Timeline of the Build Results Page

### ISSUE THREAD

**Issue by Hupka** [MicrosoftDocs/vsts-docs#1646]
As of yesterday me and my teams are missing the code coverage reports in our build pipelines as well as the dedicated tab on the build results page showing our JUnit html file. I also went back a few days to also find this info is now missing on all earlier builds that had previously shown this results... I couldn't find a better place to comment on that -- currently this build task is not very useful for us.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6ac4ff4-9839-6a6d-8d20-a25084d221ef
* Version Independent ID: bd09f139-8e69-8ea1-6671-b7bba8e17c23
* Content: [Publish Code Coverage Results from a VSTS or TFS build](https://docs.microsoft.com/en-us/vsts/pipelines/tasks/test/publish-code-coverage-results?view=vsts)
* Content Source: [docs/pipelines/tasks/test/publish-code-coverage-results.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/test/publish-code-coverage-results.md)
* Product: **devops**
* GitHub Login: @erickson-doug
* Microsoft Alias: **dastahel**

**Comment by DavidStaheli** [comment]
Apologies for taking so long to reply, @Hupka.  We're working to make this much better, but in the meantime, please consider [these extensions](https://marketplace.visualstudio.com/search?term=coverage&target=AzureDevOps&category=All%20categories&sortBy=Relevance).  Please reopen this issue if we can provide additional help.
