### ISSUE TITLE
Too many libraries is confusing

### ISSUE THREAD

**Issue by rifuller** [MicrosoftDocs/vsts-docs#1647]
It is very confusing that there are so many libraries and that none of them seemingly apply to web apps that don't run interactively.  What is the *one* API package for interacting with the VSTS REST API?  The API itself is equally insane but this lack of guidance doesn't help.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 413163f0-28c3-a2a7-d626-fcb81bcb2257
* Version Independent ID: 57c127da-2b1e-d29e-9abb-a3c258762ccf
* Content: [.NET Client Libraries for VSTS (and TFS)](https://docs.microsoft.com/en-us/vsts/integrate/concepts/dotnet-client-libraries?view=vsts)
* Content Source: [docs/integrate/concepts/dotnet-client-libraries.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/integrate/concepts/dotnet-client-libraries.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by phatcher** [comment]
For example, how do I use the libraries when I have a PAT token

**Comment by elbatk** [comment]
Hi @rifuller and @phatcher , what docs change would you guys like to see come of this? It looks like that sample you've contributed is excellent.

**Comment by rifuller** [comment]
I think my confusion was with the fact that there's many options for libraries but it isn't clear which one I needed.  In the end, I think I needed to install 3 of the 5?  They each had different namespaces but somehow they worked together.

**Comment by elbatk** [comment]
Hi people, I'm going to add @willsmythe for awareness here. We do have the new .NET Client Library ref now: https://docs.microsoft.com/en-us/dotnet/api/index?view=azure-devops-dotnet, but I know you're looking for more conceptual guidance/samples in this area.

**Comment by chcomley** [comment]
Hi @rifuller, I'm just catching up on this issue and am wondering whether the previously shared [.NET Client Library ref ](https://docs.microsoft.com/en-us/dotnet/api/index?view=azure-devops-dotnet) helped. Do you feel there's still some missing information? Thanks! If I don't hear from you this week, I may close this issue. You can always respond and we can create a new one, if need be. Have a great day.

**Comment by rifuller** [comment]
It would be useful to still have a hierarchy of packages, or at least correlate which packages have which APIs in them.  They are listed very briefly (Microsoft.VisualStudio.Services.Client has the "identity" apis) but that could be a lot clearer, perhaps with a diagram or by naming the packages better.

**Microsoft.VisualStudio.Services.Client** and **Microsoft.TeamFoundationServer.Client** are practically named the same thing (VSS == TFS == VSTS == ADO) so you can't distinguish what is actually in them.  

What makes it more confusing is that Microsoft.TeamFoundationServer.Client has a dependency on Microsoft.VisualStudio.Services.Client so the latter is really kind of a base client?  All of this should be clear in the naming of the packages.

**Comment by chcomley** [comment]
Adding @wnjenkin for further guidance. Thanks @rifuller, we'll get the docs updated.

**Comment by chcomley** [comment]
Hi @rifuller, I'm closing this issue and have spun off a new issue. You can track it [here](https://github.com/MicrosoftDocs/vsts-docs/issues/4492). Thank you!
