### ISSUE TITLE
This article seems out-of-date

### ISSUE THREAD

**Issue by JohnTasler** [MicrosoftDocs/vsts-docs#1648]
I don't see "Admin Settings". If I click on "Organization Settings", I don't see "Overview". I cannot find a delete button for the organization.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 04896cea-ee71-4a2f-2fca-b50059a68540
* Version Independent ID: addb77a9-ba73-51c0-57e8-bebc3ab2740d
* Content: [Delete your VSTS organization](https://docs.microsoft.com/en-us/vsts/organizations/accounts/delete-your-vsts-organization?view=vsts&tabs=new-nav)
* Content Source: [docs/organizations/accounts/delete-your-vsts-organization.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/accounts/delete-your-vsts-organization.md)
* Product: **devops**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Thanks for your comment, @JohnTasler. We are currently updating our docs, aiming to publish very soon - sorry for the confusion. To delete an organization, go to **Organization settings**, you land on the Overview page, where you'll see a **Delete** button at the top right of your page. If you do not see this, you may not have organization owner permissions. Please let me know if I can help further.
