### ISSUE TITLE
When file copy for Blob, can I set Cache-Control as an option?

### ISSUE THREAD

**Issue by changeworld** [MicrosoftDocs/vsts-docs#1649]
Would it be possible to add a feature to set Cache-Control when file copy?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 622daa35-c6a1-dac3-17ee-3f9308fc60cd
* Version Independent ID: 2c28a59b-8ef5-d7ab-46a6-58748ec552f5
* Content: [VSTS and Team Foundation Server Build and Deploy - Azure File Copy](https://docs.microsoft.com/en-us/vsts/pipelines/tasks/deploy/azure-file-copy?view=vsts)
* Content Source: [docs/pipelines/tasks/deploy/azure-file-copy.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/deploy/azure-file-copy.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment]
Please post your feature request on our product feedback page: https://feedback.azure.com/forums/169385-web-apps. Thank you!
