### ISSUE TITLE
URL Error

### ISSUE THREAD

**Issue by the-wazz** [MicrosoftDocs/vsts-docs#165]
ref: https://docs.microsoft.com/en-us/vsts/collaborate/wiki-create-repo

"However, you can navigate to it from the URL 
`https://<AccountName>.visualstudio.com/DefaultCollection/_git/<TeamProjectName>.wiki`."

the URL should be
`https://<AccountName>.visualstudio.com/DefaultCollection/<TeamProjectName>/_git/<TeamProjectName>.wiki`.

[or update system so this is not the case...]

**Comment by steved0x** [comment]
@the-wazz Thank you for letting us know, I am forwarding this to the author of that article so we can get it clarified. I'll update this issue once we have it fixed. Thank you.

**Comment by steved0x** [comment]
@the-wazz We have fixed the issue and the updated documentation should be live soon, thank you for your contribution!
