### ISSUE TITLE
Queue demands comparison syntax is incorrect

### ISSUE THREAD

**Issue by PST2** [MicrosoftDocs/vsts-docs#1651]
The example above cites comparing for a specific agent capability as:

- agent.os -eq Darwin  # specific string

This is incorrect; if no agent meets the demands check, the -eq comparison will be omitted from the list of demands that were checked.

(The correct form for such a comparison is shown at https://docs.microsoft.com/en-us/vsts/pipelines/process/phases?view=vsts&tabs=yaml#demands -- - agent.os -equals Darwin )

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7458d5b2-1bb7-7d87-7ce6-2b0c430b0155
* Version Independent ID: edf5bbd3-a3f0-5426-e985-31290f8afd05
* Content: [YAML schema](https://docs.microsoft.com/en-us/vsts/pipelines/yaml-schema?view=vsts#queue)
* Content Source: [docs/pipelines/yaml-schema.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/yaml-schema.md)
* Product: **devops**
* GitHub Login: @erickson-doug
* Microsoft Alias: **macoope**

**Comment by vtbassmatt** [comment]
Good catch, thanks!
