### ISSUE TITLE
This doc should be update!

### ISSUE THREAD

**Issue by moyanming** [MicrosoftDocs/vsts-docs#1652]
There are two problems at least:
1. There is no "Admin settings", but there is a "Organization settings".
2. There is no "Remove form projects" of the context menu.
![qq 20180905125604](https://user-images.githubusercontent.com/13234209/45071999-9eb1a900-b10b-11e8-8ca0-a8fb1a46ded5.jpg)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 75aa416a-b842-77d0-e18a-bee7f7bf7205
* Version Independent ID: 65942145-45ca-48bb-6adc-c16bd662b80a
* Content: [Manage users and access in VSTS](https://docs.microsoft.com/en-us/vsts/organizations/accounts/manage-users-table-view?view=vsts&branch=master-rebrand&tabs=new-nav#manage-users)
* Content Source: [docs/organizations/accounts/manage-users-table-view.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/accounts/manage-users-table-view.md)
* Product: **devops**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Thanks for your comment, @moyanming.  If you're attempting to remove a user from a project, you have to go to your project and then choose Project settings, where Organization settings was on your initial sign in page. We are currently updating this topic and will publish early next week. Thank you.

**Comment by moyanming** [comment]
Hi @chcomley , there only a "Teams" (no "Users") item under "Project settings", I guess the user which deleted from the "Team" will still under the project, because this user only removed from the team but not removed from the project.
![qq 20180906112212](https://user-images.githubusercontent.com/13234209/45133603-b9962300-b1c8-11e8-907f-62d65e031081.jpg)

Under "Overview->Summary", there called "Members":
![qq 20180906112045](https://user-images.githubusercontent.com/13234209/45133650-0a0d8080-b1c9-11e8-900b-da05d8eb26b4.jpg)

But under "Overview->Dashboards", there called "Team Members":
![qq 20180906112034](https://user-images.githubusercontent.com/13234209/45133687-3923f200-b1c9-11e8-8a80-177b2fd56b41.jpg)

Under the "Organization settings", there called "Users":
![qq 20180905125604](https://user-images.githubusercontent.com/13234209/45133840-ff072000-b1c9-11e8-96b9-a0e72de8df64.jpg)


Is there docs about the different between: Teams, Users, Members and Team Members, and how to remove and add them from the Project, Team, Member and Team Members?
Best regards!

**Comment by chcomley** [comment]
I am currently updating this doc, so thank you for this valuable feedback.

The doc is incorrect, as it is missing a step. Select **Organization settings** > **Users** > **ellipses** > **Manage projects**. From the popup page, you can choose from which projects to add or remove the user by checking or unchecking the box next to each project, and you can choose the user's access level for each project from the dropdown menu of VSTS Groups. Then, choose **Save all**.  Hope this helps.

For more information, check out [Add users to a team project or team](https://docs.microsoft.com/en-us/vsts/organizations/security/add-users-team-project?toc=%2Fvsts%2Forganizations%2Fprojects%2Ftoc.json&bc=%2Fvsts%2Forganizations%2Fprojects%2Fbreadcrumb%2Ftoc.json&view=vsts&tabs=new-nav), [Add users to a project or team](https://docs.microsoft.com/en-us/vsts/organizations/security/add-users-team-project?toc=%2Fvsts%2Forganizations%2Fsettings%2Ftoc.json&bc=%2Fvsts%2Forganizations%2Fsettings%2Fbreadcrumb%2Ftoc.json&view=vsts&tabs=new-nav), and [About teams and Agile tools](https://docs.microsoft.com/en-us/vsts/organizations/settings/about-teams-and-settings?toc=/vsts/organizations/projects/toc.json&bc=/vsts/organizations/projects/breadcrumb/toc.json&view=vsts).

**Comment by v-piwijs** [comment]
What are Five users?  Five users to test is enough?  See below.

The following types of users can join your organization for free:

Five users who get Basic features, such as version control and tools for Agile, Java, and build and release management.

**Comment by chcomley** [comment]
Hi @v-piwijs, thank you for reaching out. I agree that it’s a bit confusing, as it’s meant to say “users with Basic features...” (of which, you get 5 for free). I’ll create a user story to address this. Sorry for the confusion. Thanks again!

**Comment by v-piwijs** [comment]
👍  I was worried I missed out on knowing an important term in the industry. Thanks!
