### ISSUE TITLE
Typo in 'Create a Release Pipeline'

### ISSUE THREAD

**Issue by kushagraagarwal19** [MicrosoftDocs/vsts-docs#1654]
Hi,

In step 12 of this (https://docs.microsoft.com/en-us/vsts/pipelines/get-started-designer?view=vsts&tabs=new-nav#create-a-release-pipeline) I believe there is a typo.

Just below the step 16, it says that we have used Release Variables instead of Build Variables but in step 12 for the trigger, it's still referring to the Build's one

-greeter "$(Release.RequestedFor)" -trigger "$(Build.DefinitionName)"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 02b747eb-53c2-dd5f-cd2b-f337c15e0864
* Version Independent ID: 04538505-00cd-33ac-8008-4b85cca089e3
* Content: [Create your first build and release](https://docs.microsoft.com/en-us/vsts/pipelines/get-started-designer?view=vsts&tabs=new-nav#create-a-release-pipeline)
* Content Source: [docs/pipelines/get-started-designer.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/get-started-designer.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by elbatk** [comment]
Hi @kushagraagarwal19 , this doesn't seem to be a typo. The arguments are referencing "Release.RequestedFor" instead of "Build.RequestedFor", but the "Build.DefinitionName" is still relevant. I'm going to close this issue for now but if you think we should reevaluate, feel free to reopen or comment.
