### ISSUE TITLE
Project Increment Planning using TFS

### ISSUE THREAD

**Issue by anveshhungenalli** [MicrosoftDocs/vsts-docs#1657]
Hello 
Apart from planning sprints is there an option where we can identify cross team dependencies , Plan project road maps for the initiatives a team is committing to in a quarter. If so can you please show how we do that. 

Thank you 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ef517e1-f614-a2e5-d968-e32bdaac6183
* Version Independent ID: babf6a50-0147-74bb-0e20-b1939de397af
* Content: [Review team delivery plans - VSTS & TFS](https://docs.microsoft.com/en-us/vsts/boards/plans/review-team-plans?view=vsts&tabs=new-nav)
* Content Source: [docs/boards/plans/review-team-plans.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/boards/plans/review-team-plans.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@anveshhungenalli  - Thank you for your inquiry. Please review the article - [Visibility across teams](https://docs.microsoft.com/en-us/azure/devops/boards/plans/visibility-across-teams?view=vsts). for additional tips on gaining visibility across teams and planning. You may also want to check out the [Feature timeline and Epic Roadmap](https://marketplace.visualstudio.com/items?itemName=ms-devlabs.workitem-feature-timeline-extension) extension.
