### ISSUE TITLE
How to distribute a feed with different cedentials?

### ISSUE THREAD

**Issue by Nalbornoz** [MicrosoftDocs/vsts-docs#1659]
Hi team.

We have two feeds (Gradle) in vsts to distribute and we generate a credentials for a custom consumers but the problem is, with both credencials can access to any feeds.
 
For example with credentials of Feed Client1 we can access to Feed Client 2 and consume it on Android Studio.

And we think that it's not the correct funcionality, because is not secure to another feeds.

How can we establish credentials in a single feed and can not be used with another feed?

**Comment by elbatk** [comment]
Adding @alexmullans to help out :)

**Comment by alexmullans** [comment]
You would need to create two service (non-user) accounts, ensure they have licenses to Package Management, and then add one of them as a Reader of Client1 and one of them as a Reader of Client2. Then, you would provide credentials for User1 to Client1 and credentials for User2 to Client2.
