### ISSUE TITLE
Installing certificate from YAML

### ISSUE THREAD

**Issue by jbehrens94** [MicrosoftDocs/vsts-docs#1661]
Hi,

I'd like to use the YAML configuration for my VSTS-hosted code, to run in AppCenter. However, do I have to upload my certificates and provisioning profile via the web-interface, or is there another way to push those to the Secret Files?

Or do I just copy-paste the certSecureFile variable from the web-interface into the YAML code?

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: 6e4f249c-c229-4a5c-7970-4e566026b560
* Version Independent ID: 7062bdf1-7b38-b42b-e117-c3041e09aae7
* Content: [Install Apple Certificate](https://docs.microsoft.com/nl-nl/vsts/pipelines/tasks/utility/install-apple-certificate?view=vsts)
* Content Source: [docs/pipelines/tasks/utility/install-apple-certificate.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/utility/install-apple-certificate.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by DavidStaheli** [comment]
Hi @jbehrens94.  Apologies for taking so long to reply.  To install the certificate using YAML, first upload your cert and provisioning profile via the web interface.  You could also upload them via the REST API.  Then, use the "Install Apple Certificate" and "Install Apple Provisioning Profile" tasks in your YAML file to make them available during your pipeline.  You can find more details [here](https://docs.microsoft.com/en-us/azure/devops/pipelines/apps/mobile/app-signing?view=vsts&tabs=apple-install-during-build#configure-your-build).  Please reopen this issue if we can provide additional help.
