### ISSUE TITLE
using

### ISSUE THREAD

**Issue by Enjoyop** [MicrosoftDocs/vsts-docs#1662]
fbfbg

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 521b594c-dbb9-54d5-f56f-00e2f5fa1d92
* Version Independent ID: 509d3e4e-23db-8493-e1a6-acb67ec47e81
* Content: [Building multiple branches](https://docs.microsoft.com/en-us/vsts/pipelines/build/ci-build-git?view=vsts&tabs=yaml)
* Content Source: [docs/pipelines/build/ci-build-git.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/build/ci-build-git.md)
* Product: **devops**
* GitHub Login: @mlearned
* Microsoft Alias: **mlearned**

**Comment by steved0x** [comment]
@Enjoyop I'm closing this but please feel free to open a new issue with additional details. Thank you.
