### ISSUE TITLE
Additional hosted agent pools that aren't listed

### ISSUE THREAD

**Issue by cglong** [MicrosoftDocs/vsts-docs#1663]
Hi, I'm creating a new build in VSTS and see a few agent pools listed that don't seem to be mentioned here:

* Hosted Ubuntu 1604
* Hosted Windows Container

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4409a9cb-8448-edd6-da0a-243e5601aa3e
* Version Independent ID: ec15f71a-a76d-c3f9-1d31-832f92183ef4
* Content: [Agents, pools, and queues](https://docs.microsoft.com/en-us/vsts/pipelines/agents/pools-queues?view=vsts)
* Content Source: [docs/pipelines/agents/pools-queues.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/agents/pools-queues.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by vtbassmatt** [comment]
Fixing now.

**Comment by vtbassmatt** [comment]
Sorry, it seems my PR didn't complete. There's not a good way to track - but it's because there's only supposed to be a very short window where the docs are still wrong! I'll push this one through. Thank you for raising it again.

**Comment by janpio** [comment]
I wasn't only referring to this specific change, but more in general: 

It would be nice if there was a connection from the issue to the PR fixing the issued (`closes #123` in the PR description or merge commit should do the job) so one can understand what the fix to a specific issue actually was.

In cases where the change doesn't really clarify the situation, a user can directly comment on the PR or commit to make that clear for example.

**Comment by andyjlewis** [comment]
Thanks for the feedback on the doc process. In some cases I personally try to mention GitHub issues in commits or our internal work items, but it definitely is not systematic at this point. Heads up to @erickson-doug and @steved0x
