### ISSUE TITLE
If my build has artifacts as output, how do I flag them for future steps?

### ISSUE THREAD

**Issue by atrauzzi** [MicrosoftDocs/vsts-docs#1665]
Specifically `.zip` files and docker images.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 87686bea-7c46-cd47-d1a9-128e16b63a23
* Version Independent ID: ace78317-e562-e35d-781d-23cd7d2dfff2
* Content: [CI Build in code using YAML](https://docs.microsoft.com/en-us/vsts/pipelines/build/yaml?view=vsts)
* Content Source: [docs/pipelines/build/yaml.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/build/yaml.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by andyjlewis** [comment]
Hi @atrauzzi. Does https://docs.microsoft.com/en-us/azure/devops/pipelines/targets/nuget?view=vsts&tabs=yaml help?

**Comment by alexmullans** [comment]
Use [Copy Files](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/publish-build-artifacts?view=vsts) to arrange files as desired (`$(Build.ArtifactStagingDirectory)` is a good default location for artifacts you want to publish), then [Publish Build Artifacts](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/publish-build-artifacts?view=vsts) to upload one or more artifacts (each artifact can be a whole folder of files or just a single file).

**Comment by alexmullans** [comment]
You'd need a container registry (e.g. Azure Container Registry) and the Docker task to push images to that registry. [This walkthrough](https://docs.microsoft.com/en-us/azure/devops/pipelines/languages/docker?view=vsts&tabs=yaml) should help.

**Comment by atrauzzi** [comment]
But that doesn't associate them to the build in any meaningful way though. Right?

**Comment by vijayma** [comment]
Before pushing to a Docker registry, you can tag the image with the build number as this [walkthrough]([https://docs.microsoft.com/en-us/azure/devops/pipelines/languages/docker?view=vsts&tabs=yaml]) does. You cannot see the link to the image in the registry from your build. I will add that to our backlog. You can see it in the logs of your build. We have a way for you to write a custom section to your build. You can use that yourself until we get something out of the box. See task.upload command in this [document](https://github.com/Microsoft/vsts-tasks/blob/master/docs/authoring/commands.md).

**Comment by atrauzzi** [comment]
Yeah, I'd love to see the ability to associate built docker images with builds so that I'm not having to manually track that as build-specific instructions between objectives. 😄 

That'd be quite powerful!

**Comment by alexmullans** [comment]
Yep, we agree. As @vijayma mentioned, something we're definitely thinking about.
