### ISSUE TITLE
hacked

### ISSUE THREAD

**Issue by realreaddy** [MicrosoftDocs/vsts-docs#1666]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c0d1a52c-1c9d-0745-8afa-ade8c0d1d110
* Version Independent ID: c7843002-b880-b931-d2e4-6d927bd59223
* Content: [Integrating custom apps and third party services with VSTS and Team Foundation Server](https://docs.microsoft.com/en-us/vsts/integrate/?view=vsts)
* Content Source: [docs/integrate/index.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/integrate/index.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by elbatk** [comment]
Closing this issue due to lack of information.
