### ISSUE TITLE
Is this still recommendend?

### ISSUE THREAD

**Issue by erosinger** [MicrosoftDocs/vsts-docs#1667]
Hi All, together with my colleagues I am currently undergoing a company merger and thus need to move my VSTS to another Azure AD tenant. The recommended action seems to be "Disconnect VSTS from old Azure AD" and afterwards "Connect to new Azure AD. As this sight has not been updated for nearly a year this heavily needs a review. Looking forward to your response. Best, erosiner

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f1dab52c-5d12-3f5e-1dfd-e2950f8837ae
* Version Independent ID: 6af8d687-4ca4-4f16-614f-aa867f10e68e
* Content: [Disconnect your VSTS organization from your Azure AD](https://docs.microsoft.com/en-us/vsts/organizations/accounts/disconnect-organization-from-aad?view=vsts)
* Content Source: [docs/organizations/accounts/disconnect-organization-from-aad.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/accounts/disconnect-organization-from-aad.md)
* Product: **devops**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @erosinger, I've forwarded your request to Justin, who should be in contact with you shortly.  Thank you.

**Comment by justmarks** [comment]
@erosinger please contact me in email (jmarks@microsoft.com) so we can assist you.

**Comment by erosinger** [comment]
@justmarks @chcomley Thank you guys for responding so quickly. I`ll reach out to you jmarks. Best, erosinger
