### ISSUE TITLE
Only linux containers?

### ISSUE THREAD

**Issue by fleed** [MicrosoftDocs/vsts-docs#1669]
It is not explicitely mentioned, but it seems that only linux conainers are suppoted.. aren’t they?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3339a2e0-be29-1363-f588-b231d4472c02
* Version Independent ID: 72dd11a3-704d-d0fd-6dfa-cf49f3352de3
* Content: [Container Jobs in Azure Pipelines and TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/container-phases?view=vsts&tabs=yaml)
* Content Source: [docs/pipelines/process/container-phases.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/container-phases.md)
* Product: **devops**
* GitHub Login: @erickson-doug
* Microsoft Alias: **macoope**

**Comment by AArnott** [comment]
I hope Windows containers are supported. :)

**Comment by gregpakes** [comment]
I would love to know if Windows Containers are supported?

**Comment by vtbassmatt** [comment]
Yup, Windows Containers are supported. It's in the [hosted agent](https://docs.microsoft.com/azure/devops/pipelines/agents/hosted) docs but needs to be here, too. Thanks.

**Comment by calvincestari** [comment]
Are containers supported in macOS environments? If not can that please be explicitly stated in the docs.
