### ISSUE TITLE
Authentication details for mySQL server on Hosted Ubuntu 1604 Agent

### ISSUE THREAD

**Issue by jordanbrock** [MicrosoftDocs/vsts-docs#1673]
My rails test script needs to create a database on the mysql server. What details can I use to authenticate with the mysql server?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 99af681d-41ad-da15-0b72-08b5cd5a11ac
* Version Independent ID: 2fa0df36-a437-8cbb-b019-b49b31b1e116
* Content: [Microsoft-hosted agents for Azure Pipelines](https://docs.microsoft.com/en-gb/azure/devops/pipelines/agents/hosted?view=vsts&tabs=yaml)
* Content Source: [docs/pipelines/agents/hosted.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/agents/hosted.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by chrisrpatterson** [comment]
I expect they are the default credentials still but I am not 100% sure.  I will have someone look into it and respond back.

**Comment by dakale** [comment]
You can use root/root

> `mysql ... -uroot -proot`
