### ISSUE TITLE
Task title missing for NuGet task

### ISSUE THREAD

**Issue by letmaik** [MicrosoftDocs/vsts-docs#1679]
"Finds or downloads and caches the specified version of NuGet and adds it to the PATH"
-&gt; Misses the initial task title.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e7ba5cf3-d229-03d0-ad6a-a30a0379afc0
* Version Independent ID: ccffed3b-ea44-517f-f7a8-a1c4c4147495
* Content: [Catalog of the built-in tasks for build-release and Azure Pipelines & TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/index?view=vsts)
* Content Source: [docs/pipelines/tasks/index.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/index.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by elbatk** [comment]
Hey @letmaik , the link was later in the row as "NuGet", updating it though so it looks like the other entries, thanks!
