### ISSUE TITLE
Typo in the About access levels page

### ISSUE THREAD

**Issue by EricStG** [MicrosoftDocs/vsts-docs#1682]
Under [Stakeholder access to administrative features](https://docs.microsoft.com/en-us/azure/devops/organizations/security/access-levels?view=vsts#stakeholder-access-to-administrative-features), in the Project settings, there's a typo.

>Suppress notifications for owrk item updates

should probably read 

> Suppress notifications for work item updates

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8db47b85-e178-7969-40d3-3fa83aa3fb54
* Version Independent ID: a78e453b-4b8f-c885-42ee-8a9d9979f345
* Content: [What access levels does Azure DevOps & TFS support? - Azure DevOps Services & TFS](https://docs.microsoft.com/en-us/azure/devops/organizations/security/access-levels?view=vsts#stakeholder)
* Content Source: [docs/organizations/security/access-levels.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/security/access-levels.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by steved0x** [comment]
@EricStG Thanks for letting us know, I'm fixing it right now and it should be live soon.
