### ISSUE TITLE
createCustomEnvironment not documented

### ISSUE THREAD

**Issue by letmaik** [MicrosoftDocs/vsts-docs#1683]
What does `createCustomEnvironment` do?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fa498d54-1576-498a-b8b5-189f2859a884
* Version Independent ID: 0642e827-92b5-5f30-e162-c7220de4089f
* Content: [Conda Environment](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/package/conda-environment?view=vsts)
* Content Source: [docs/pipelines/tasks/package/conda-environment.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/package/conda-environment.md)
* Product: **devops**
* GitHub Login: @erickson-doug
* Microsoft Alias: **brcrista**

**Comment by carterbox** [comment]
`conda` is both a package manager and environment manager. `createCustomEnvironment` set to `True` tells this task that you want to [create an environment](https://conda.io/docs/commands/conda-create.html) instead of using the default one.

**Comment by DavidStaheli** [comment]
Docs have been updated to clarify this and other arguments.  Thank you!

**Comment by praneetmsft** [comment]
[create an environment](https://conda.io/en/latest/commands/conda-create.html) link does not exists. Please update the doc with correct link.

**Comment by praneetmsft** [comment]
@DavidStaheli 
In the Azure pipeline conda step, can we specify conda.yaml file path, such that it creates env from the yaml file?

**Comment by DavidStaheli** [comment]
@brcrista can you please advise?

**Comment by brcrista** [comment]
@praneetmsft we've learned that the task can't cover every scenario.  We're in the process of deprecating the task and recommend you just use script for working with Anaconda environments.
We have a new guide just for using Anaconda in Pipelines, you can see it here: https://docs.microsoft.com/azure/devops/pipelines/languages/anaconda#from-yaml 

Thanks for pointing out the broken link, I'll fix that.

**Comment by letmaik** [comment]
@brcrista In principle I'm very much in favour of exposing functionality with CLI tools. I see two problems with the new approach though:
- Activating an environment has to be done for each subsequent task that needs to use it. That is quite cumbersome. Any way to work around that and make it persist?
- Having to change PATH just to use conda is a bit awkward, for one thing because of the syntax `##vso[..` syntax) and also because it's different per operating system. What about a UseConda task that does this automatically?

**Comment by brcrista** [comment]
Agreed on both counts.  The way each step runs in a fresh system environment / process has been feedback we've heard before, especially with conda.  That was a fundamental decision made a long time ago in what it means to be a "step."  The original Conda Environment task was an attempt to address this, but Anaconda environments end up having a lot of customization options that the task just can't cover.  @vtbassmatt and I have kicked around some new ideas on how to address this in a script-first way for the YAML world.

Yeah, putting every tool in PATH does get hard to scale for reasons like this. 
 @vtbassmatt , being able to say `use: conda` and go look for an install location might be a good solution here too.
