### ISSUE TITLE
URL Broken

### ISSUE THREAD

**Issue by JoeMcGrath** [MicrosoftDocs/vsts-docs#1684]
the url here https://docs.microsoft.com/en-us/azure/devops/marketplace/install-vsts-extension?toc=%2Fazure%2Fdevops%2Fuser-guide%2Ftoc.json&bc=%2Fazure%2Fdevops%2Fuser-guide%2Fbreadcrumb%2Ftoc.json&view=vsts#install-the-extension is broken - it points to https://marketplace.visualstudio/ which is invalid

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 10a21253-c7bd-cb54-afdc-ddc6289b39e1
* Version Independent ID: 27c48faa-4fcc-22af-6836-2d60b1ea4762
* Content: [Install free extensions for Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/marketplace/install-vsts-extension?toc=%2Fazure%2Fdevops%2Fuser-guide%2Ftoc.json&bc=%2Fazure%2Fdevops%2Fuser-guide%2Fbreadcrumb%2Ftoc.json&view=vsts#install-the-extension)
* Content Source: [docs/marketplace/install-vsts-extension.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/marketplace/install-vsts-extension.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by steved0x** [comment]
@JoeMcGrath Thanks for letting us know, I am fixing that right now and it should be live later today. The correct link is: https://marketplace.visualstudio.com/azuredevops
