### ISSUE TITLE
Add information on suitability for open source projects

### ISSUE THREAD

**Issue by letmaik** [MicrosoftDocs/vsts-docs#1685]
For example, if someone creates a PR that changes the pipeline yml to dump the contents of a secure file. Will this be possible? I'm assuming for open source projects the build outputs can be viewed publicly. Travis CI for example doesn't expose secure environment variables to PR builds to avoid such issues, but this of course imposes some limitations.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 140dcb9a-2ed0-11d5-064b-068f863ed97f
* Version Independent ID: 672d2aa3-cf0d-9207-c97c-e2eba14506b7
* Content: [Secure files for Azure Pipelines and Team Foundation Server](https://docs.microsoft.com/en-us/azure/devops/pipelines/library/secure-files?view=vsts)
* Content Source: [docs/pipelines/library/secure-files.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/library/secure-files.md)
* Product: **devops**
* GitHub Login: @erickson-doug
* Microsoft Alias: **madhurig**

**Comment by DavidStaheli** [comment]
Hi @letmaik.  Apologies for taking so long to reply.  This has now been documented [here](https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/github?view=vsts#validate-contributions-from-forks).  Thank you for the recommendation!  Please reopen this issue if we can provide additional help.
