### ISSUE TITLE
Add use case

### ISSUE THREAD

**Issue by letmaik** [MicrosoftDocs/vsts-docs#1686]
Details on use cases would be good here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 05e99925-c1f9-5041-311f-39469c124d85
* Version Independent ID: 81b0a6bf-d7cb-7208-3759-3455efc5bf13
* Content: [Delay task for Azure Pipelines and TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/delay?view=vsts)
* Content Source: [docs/pipelines/tasks/utility/delay.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/utility/delay.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment]
Thank you for your feedback. I have passed this on to the product team for advice.

**Comment by RoopeshNair** [comment]
Delay task is used within Release Gates, adding @shashban
