### ISSUE TITLE
A couple of important steps are missing

### ISSUE THREAD

**Issue by alexandair** [MicrosoftDocs/vsts-docs#1689]
There is no "add ." step, so there is nothing to commit.
Authentication part is missing too.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc4e7f5a-08f4-5c12-cb6d-424d6e5dadaa
* Version Independent ID: e317a392-cb78-7fcc-fcf8-2cecaa9e6580
* Content: [Code with Git - Azure DevOps Services & TFS](https://docs.microsoft.com/en-us/azure/devops/user-guide/code-with-git?view=vsts&tabs=new-nav)
* Content Source: [docs/user-guide/code-with-git.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/user-guide/code-with-git.md)
* Product: **devops**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by steved0x** [comment]
@alexandair The `- a` in the `git commit` step does the add, and you are right, the article doesn't talk about authentication at all. I will get it fixed up, thank you for letting us know.

**Comment by alexandair** [comment]
I'd followed all the steps, and this is what I've seen:

```bash
$ git commit -a -m "My first commit"
On branch master

Initial commit

Untracked files:
        ReadMe.md

nothing added to commit but untracked files present
```

**Comment by steved0x** [comment]
@alexandair Are you adding a new ReadMe.md file to your repo? `git commit -a` should pick up the change if it is an edit, but if it is a new file you would need to run `git add .` first, then `git commit` - I agree this isn't that clear, let me get the article updated. Thank you for letting me know and sorry that you ran into trouble.

**Comment by alexandair** [comment]
@steved0x 
Yes, I've created a new ReadMe.md file, because it didn't exist. I think the steps before that section don't include the initial creation of the ReadMe.md file.

**Comment by steved0x** [comment]
@alexandair The updated documentation with `git add .` to replace `-a` in the `git commit` command will go live today or tomorrow. Thanks for letting us know.
