### ISSUE TITLE
Steps are not accurate in the "Create a build pipeline" section

### ISSUE THREAD

**Issue by alexandair** [MicrosoftDocs/vsts-docs#1692]
The described steps are not accurate for someone who is a first-timer. YAML template-based creation of a build pipeline is the default one, and it's not explained how to switch to the visual designer. That is not reflected in this document. For the quickstarts is crucial to explain all needed steps to follow the doc.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 02b747eb-53c2-dd5f-cd2b-f337c15e0864
* Version Independent ID: 04538505-00cd-33ac-8008-4b85cca089e3
* Content: [Use the visual designer to create a CI/CD pipeline - Azure Pipelines & TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/get-started-designer?view=vsts&tabs=new-nav)
* Content Source: [docs/pipelines/get-started-designer.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/get-started-designer.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by elbatk** [comment]
Hey @alexandair, thanks for the feedback. We've updated the doc to explain how to get to the visual designer: "For new Azure DevOps accounts, this will automatically take you to the YAML pipeline creation experience. To get to the visual designer and complete this guide, you must turn off the preview feature for the New YAML pipeline creation experience:"

Screenshots in the [original doc page](https://docs.microsoft.com/en-us/azure/devops/pipelines/get-started-designer?view=vsts&tabs=new-nav#create-a-build-pipeline).
