### ISSUE TITLE
[Loc Test] Please ignore this comment as I am MS internal.

### ISSUE THREAD

**Issue by nokura** [MicrosoftDocs/vsts-docs#1697]
Testing to design localized topic behavior for future release

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 15f1fadb-d2a0-f671-af1e-0707ef6e385d
* Version Independent ID: 64faa90d-7e2a-465a-89dc-06f40ccf612c
* Content: [Moving to Cloud Cadence - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/learn/devops-at-microsoft/moving-cloud-cadence#feedback)
* Content Source: [https://mseng.visualstudio.com/DefaultCollection/TechnicalContent/_git/devops-learn-pr?path=%2fdocs%2fdevops-at-microsoft%2fmoving-cloud-cadence.md&version=GBlive&_a=contents](https://mseng.visualstudio.com/DefaultCollection/TechnicalContent/_git/devops-learn-pr?path=%2fdocs%2fdevops-at-microsoft%2fmoving-cloud-cadence.md&version=GBlive&_a=contents)
* Product: **devops**
* Git Login: **samgu**
* Microsoft Alias: **loril**

**Comment by steved0x** [comment]
@nokura Gotcha, I am closing this issue.
