### ISSUE TITLE
System.CollectionName missing

### ISSUE THREAD

**Issue by khalie** [MicrosoftDocs/vsts-docs#1705]
I really would like to use a Variable System.CollectionName instead of System.CollectionId. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ffebdc8-521c-44b5-cde4-4abdc1bd6f18
* Version Independent ID: dc0effda-6d93-62aa-64c5-4e6f283b0826
* Content: [Predefined build variables - Azure Pipelines & TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=vsts)
* Content Source: [docs/pipelines/build/variables.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/build/variables.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by vtbassmatt** [comment]
I agree, that could be handy. This isn't a documentation issue, it's a feature request. Those go over here: https://visualstudio.uservoice.com/forums/330519-visual-studio-team-services?category_id=145254
