### ISSUE TITLE
Npm package deprecated

### ISSUE THREAD

**Issue by csharpsi** [MicrosoftDocs/vsts-docs#1708]
vso-node-api reports that the azure-devops-node-api should be used instead

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e8f48d8a-33fb-9f6d-1db1-4cccb5b987d9
* Version Independent ID: 3e18fcbf-331d-9de2-62ae-c4e7c888cc48
* Content: [Create a pull request status server with Node.js - Azure Repos](https://docs.microsoft.com/en-gb/azure/devops/repos/git/create-pr-status-server?view=vsts)
* Content Source: [docs/repos/git/create-pr-status-server.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/repos/git/create-pr-status-server.md)
* Product: **devops**
* GitHub Login: @mmitrik
* Microsoft Alias: **mmitrik**

**Comment by steved0x** [comment]
@csharpsi I'll get this article updated - there are a few other scheduled updates on the backlog and I will add this to it. Thanks for letting us know. It should be live later this week.
