### ISSUE TITLE
No mention of `trigger:`

### ISSUE THREAD

**Issue by escalonn** [MicrosoftDocs/vsts-docs#1712]
The `trigger:` node is documented [elsewhere](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/triggers?view=vsts), but a page titled "Reference/YAML schema", which introduces a semi-formal grammar syntax, should be exhaustively complete.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7458d5b2-1bb7-7d87-7ce6-2b0c430b0155
* Version Independent ID: edf5bbd3-a3f0-5426-e985-31290f8afd05
* Content: [YAML schema - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=vsts)
* Content Source: [docs/pipelines/yaml-schema.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/yaml-schema.md)
* Product: **devops**
* GitHub Login: @erickson-doug
* Microsoft Alias: **macoope**

**Comment by vtbassmatt** [comment]
Thank you, good catch. Adding it now.
