### ISSUE TITLE
Title typo

### ISSUE THREAD

**Issue by jcdenaes** [MicrosoftDocs/vsts-docs#1716]
"Syntax guidance ~~for~~ for markdown usage"

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: fa622358-f5bb-1f5c-177a-081a37b6acef
* Version Independent ID: 72f7fd16-a822-66c8-3a34-8905645ce5f2
* Content: [Syntax usage for Markdown files, widgets, wikis, and pull requests - Azure DevOps & TFS](https://docs.microsoft.com/fr-fr/azure/devops/project/wiki/markdown-guidance?view=vsts)
* Content Source: [docs/project/wiki/markdown-guidance.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/project/wiki/markdown-guidance.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by steved0x** [comment]
@jcdenaes Thanks for letting us know - this is fixed and should be live by today.

**Comment by MichaelHarmsen** [comment]
It isn't
