### ISSUE TITLE
maxParallel inconsistently documented

### ISSUE THREAD

**Issue by letmaik** [MicrosoftDocs/vsts-docs#1717]
`strategy: [ parallel | maxParallel | matrix ]` which to me means you can use either one of those, but not together. `maxParallel` is also not documented on this page.

On https://docs.microsoft.com/en-us/azure/devops/pipelines/languages/python?view=vsts#use-multiple-python-versions there is an example where `matrix` and `maxParallel` is used together, and in fact leaving out `maxParallel` makes the matrix jobs run sequentially which is an unexpected default not matching other systems like Travis CI where by default all jobs within a phase are run in parallel.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7458d5b2-1bb7-7d87-7ce6-2b0c430b0155
* Version Independent ID: edf5bbd3-a3f0-5426-e985-31290f8afd05
* Content: [YAML schema - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=vsts)
* Content Source: [docs/pipelines/yaml-schema.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/yaml-schema.md)
* Product: **devops**
* GitHub Login: @erickson-doug
* Microsoft Alias: **macoope**

**Comment by vtbassmatt** [comment]
Thank you, good catch.
