### ISSUE TITLE
What TLS version is used?

### ISSUE THREAD

**Issue by dwhanger** [MicrosoftDocs/vsts-docs#1722]
I would like to know if tls 1.0, 1.1, or 1.2 is being used.

**Comment by brendonthiede** [comment]
Not sure exactly what URI this is in regard to, but you can use https://www.ssllabs.com/ssltest/ to check what protocols a public endpoint responds to.

**Comment by dwhanger** [comment]
Sorry, this has to do with the https communication that the VSTS agent initiates with VSTS or Azure DevOps now....

**Comment by steved0x** [comment]
@dwhanger Let me try and find out for you - if this is something we should add to the documentation, where do you think it should be? That will help me route this question to the right folks (and also get it added)

**Comment by dwhanger** [comment]
One additional sentence would do re: TLS version used for https

**Comment by gholliday** [comment]
The VSTS agent uses TLS 1.2 to initiate outgoing connections.

**Comment by dwhanger** [comment]
Fantastic, that's what I wanted to know!


Sent from Outlook<http://aka.ms/weboutlook>

________________________________
