### ISSUE TITLE
Install SSH Key task link is broken :(

### ISSUE THREAD

**Issue by MarkIannucci** [MicrosoftDocs/vsts-docs#1724]
I'm hoping to find out how VSTS stores key passphrases when you input them in the service settings, and I noticed that the link to Install SSH Key task is broken.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ad03c70-4014-135f-ffd3-245c08b3ce32
* Version Independent ID: 42a84b54-9ab7-89b2-00b1-efcfc6ba6eef
* Content: [SSH deployment task for Azure Pipelines and TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/ssh?view=vsts)
* Content Source: [docs/pipelines/tasks/deploy/ssh.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/deploy/ssh.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment]
Thank you for your feedback. I will update the topic to fix the link.
