### ISSUE TITLE
How to set/read environment variables using YAML?

### ISSUE THREAD

**Issue by nikolay-advolodkin** [MicrosoftDocs/vsts-docs#1726]
How do I set and read user environment variables using YAML? On my local, I'm reading values from user environment variables. But I can't figure out how to do the same thing in VSTS using YAML. Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 483dcb1c-1a89-2b20-4cf2-abd3ae88d9ed
* Version Independent ID: dc4722ed-5a4b-26ec-e7d5-a149bf6e79a7
* Content: [.NET Core](https://docs.microsoft.com/en-us/azure/devops/pipelines/languages/dotnet-core?view=vsts&tabs=yaml)
* Content Source: [docs/pipelines/languages/dotnet-core.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/languages/dotnet-core.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by andyjlewis** [comment]
https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables

**Comment by andyjlewis** [comment]
Did you try the approach described in https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=vsts&tabs=yaml%2Cpowershell#set-in-script ?

**Comment by vtbassmatt** [comment]
Each step of a build is run in a new, fresh process. You have to use the `##vso` command syntax [Andy pointed to](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=vsts&tabs=yaml%2Cpowershell#set-in-script) to persist variables between steps.
