### ISSUE TITLE
correction: word left out

### ISSUE THREAD

**Issue by ikechigriffith** [MicrosoftDocs/vsts-docs#1727]
https://docs.microsoft.com/en-us/azure/devops/learn/what-is-devops#optimize-validated-learning

In the above section,
The more frequently you deploy, the more can experiment, 

should be...

The more frequently you deploy, the more you can experiment, 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0cf98c4b-9185-00d5-a980-e2adb3e291fd
* Version Independent ID: f6005931-c9b5-48d9-e6c3-f835bb9b01b1
* Content: [What is DevOps? - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/learn/what-is-devops)
* Content Source: [https://mseng.visualstudio.com/DefaultCollection/TechnicalContent/_git/devops-learn-pr?path=%2fdocs%2fwhat-is-devops.md&version=GBlive&_a=contents](https://mseng.visualstudio.com/DefaultCollection/TechnicalContent/_git/devops-learn-pr?path=%2fdocs%2fwhat-is-devops.md&version=GBlive&_a=contents)
* Product: **devops**
* Git Login: **samgu**
* Microsoft Alias: **samgu**

**Comment by steved0x** [comment]
@ikechigriffith Thanks for letting us know, I'm fixing this right now and it should be live soon.
