### ISSUE TITLE
Why give Windows instructions in a Linux\Mac section?

### ISSUE THREAD

**Issue by wvrius** [MicrosoftDocs/vsts-docs#1729]
https://docs.microsoft.com/en-us/azure/devops/artifacts/npm/npmrc?view=vsts&tabs=new-nav#linux-or-mac

"Create a token that lasts longer than 90 days" &gt; Point 2.

Why give Windows instructions in a Linux\Mac section? Please replace with something relevant.

For example: base64 &lt;&lt;&lt; "YOUR_PAT_GOES_HERE" for Mac

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cb7c2ab6-4ba1-51d5-96bb-38a9ab6b50c3
* Version Independent ID: 415de875-ba1b-476b-f08b-1a61dc7a2747
* Content: [Set up your client's npmrc](https://docs.microsoft.com/en-us/azure/devops/artifacts/npm/npmrc?view=vsts&tabs=new-nav#linux-or-mac)
* Content Source: [docs/artifacts/npm/npmrc.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/artifacts/npm/npmrc.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by elbatk** [comment]
Fixing this by adding both instructions, thanks! :)
