### ISSUE TITLE
Azure App Service Deploy link is broken

### ISSUE THREAD

**Issue by paulmarshall** [MicrosoftDocs/vsts-docs#1730]
404 on this link "https://github.com/Microsoft/vsts-tasks/tree/master/Tasks/AzureRmWebAppDeployment"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 102bd9d0-0c29-3eb9-b6a1-3d2d41da0643
* Version Independent ID: a96f92b7-dc0b-ae2d-a35d-6e66dba6e4dc
* Content: [Azure Stack deployment in Azure Pipelines and Team Foundation Server](https://docs.microsoft.com/en-us/azure/devops/pipelines/targets/azure-stack?view=vsts)
* Content Source: [docs/pipelines/targets/azure-stack.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/targets/azure-stack.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment]
Thank you for your feedback. I will update the topic to fix the link.
