### ISSUE TITLE
VSBuild error

### ISSUE THREAD

**Issue by LoriolChen** [MicrosoftDocs/vsts-docs#1736]
2 errors content:
1:TheFirstProDemo\TheFirstProDemo\TheFirstProDemo.csproj(160,5): Error : ?????????????? NuGet ??????"NuGet ?????"???????????????,??? http://go.microsoft.com/fwlink/?LinkID=322105??????? ..\..\..\..\Configs\packages\Microsoft.Net.Compilers.2.1.0\build\Microsoft.Net.Compilers.props?

2:Process 'msbuild.exe' exited with code '1'.

how to solve these problems?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 38f7a23b-ebd4-af3e-68a2-275f7e45c33e
* Version Independent ID: f552a18c-ba29-00d4-03b6-254d7556d319
* Content: [Create your first pipeline](https://docs.microsoft.com/en-us/azure/devops/pipelines/get-started-yaml?view=vsts)
* Content Source: [docs/pipelines/get-started-yaml.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/get-started-yaml.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by alexmullans** [comment]
This isn't a docs issue. @elbatk can you close it? @LoriolChen please post the full logs from the failing step of your build on [Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html).

**Comment by elbatk** [comment]
You're right, @alexmullans, closing this here.
