### ISSUE TITLE
missspelling of Administrators

### ISSUE THREAD

**Issue by Ladbon** [MicrosoftDocs/vsts-docs#1737]
Project Administors are granted all of these permissions. Should be "Project Administrators are granted all of these permissions."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 68686c2b-c69a-d9e4-3e21-a46d231b649c
* Version Independent ID: 049659da-1772-3166-f909-4feeb8a97730
* Content: [Permissions and groups reference - Azure DevOps Services & TFS](https://docs.microsoft.com/en-us/azure/devops/organizations/security/permissions?view=vsts#iteration-path-object-level)
* Content Source: [docs/organizations/security/permissions.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/security/permissions.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by steved0x** [comment]
@Ladbon thank for letting us know, I'm going to merge @nschonni PR that fixes this. Thanks to both of you.
