### ISSUE TITLE
Triggered build revision

### ISSUE THREAD

**Issue by cosminstirbu** [MicrosoftDocs/vsts-docs#1739]
Hello,

On our Android project we have a build that creates the .apk for a test environment, and when this one succeeds it triggers a new build that creates the same .apk for the release environment - both building from the master branch.

It is not clear if the triggered build is using the same Git revision as the triggering build.

Is that the case? And if not, can we configure so it builds the same revision?

Thank you,
Cosmin

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5673ec1-c7d1-e0ac-043a-8fc3d5b226a9
* Version Independent ID: b4872831-51c0-6cf8-1c56-de20beb38a80
* Content: [Build pipeline triggers - Azure Pipelines & TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/triggers?view=vsts&tabs=designer)
* Content Source: [docs/pipelines/build/triggers.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/build/triggers.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by andyjlewis** [comment]
Hi cosminstirbu, 

You shouldn't rely on the commit being the same as the triggering build because the branch might have moved forward by the time the triggered build is run. Instead, you should upload artifacts in the triggering build(https://docs.microsoft.com/en-us/azure/devops/pipelines/build/artifacts) and then download them from the triggered build (https://docs.microsoft.com/en-us/azure/devops/pipelines/build/triggers?tabs=designer#download-artifacts-from-the-triggering-build)

**Comment by cosminstirbu** [comment]
Thank you for your answer.

However, I don't need the artifacts from the triggering build in the triggered build.
The only reason I'm chaining the builds is because I don't want to wait for both the release and the test build to finish, because usually we need access to the test build more frequently - and we have a limited number of agents, so we don't want the release build to run before the test build and take on one of our agents.

In the end we'll probably simply use a two-phase build to make sure we build the same revision, but depending on the agent availability, the build might take too long.

However, I think it would be a useful feature to be able to build the same revision as the triggering build.

**Comment by vijayma** [comment]
Thanks for the feedback. Your best bet for now would be to make it all part of the same pipeline using different phases. We have an item on our backlog to support snapping to the same commit in the chained build. Not sure when we will get to it though.
