### ISSUE TITLE
Issues locating my test executables

### ISSUE THREAD

**Issue by nikolay-advolodkin** [MicrosoftDocs/vsts-docs#1740]
Hello,
I'm having tons of issues locating my test executables using this feature - https://screencast.com/t/wLXuBlt9Ncs
It just keeps saying that it didn't find any tests to execute, this is my repo structure - https://screencast.com/t/fQeWmk0BFY
I am using NUnit, not sure if that makes a difference.
Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f69faf41-3074-0ce2-fb3f-3d9cc570e010
* Version Independent ID: 9ce392b3-b1cc-55f7-93e5-e8d2cc9bd788
* Content: [Run unit tests with your builds in Azure Pipelines and TFS - test automation tools](https://docs.microsoft.com/en-us/azure/devops/pipelines/test/getting-started-with-continuous-testing?view=vsts)
* Content Source: [docs/pipelines/test/getting-started-with-continuous-testing.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/test/getting-started-with-continuous-testing.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by andrewkress** [comment]
@nikolay-advolodkin  

are the tests dotnet core?  I had to change my configuration to
`**\$(BuildConfiguration)\netcoreapp2.1\*test*.dll`
for it to find the tests

**Comment by nikolay-advolodkin** [comment]
> @nikolay-advolodkin
> 
> are the tests dotnet core? I had to change my configuration to
> `**\$(BuildConfiguration)\netcoreapp2.1\*test*.dll`
> for it to find the tests

@andrewkress no, .NET Framework tests. Here is everything I tried and none of it works:
**\$(BuildConfiguration)\SeleniumMsTestDotNetFramework.dll
**\bin\$(BuildConfiguration)\SeleniumMsTestDotNetFramework.dll
**\dot-net-sauce\SauceExamples\SeleniumMsTestDotNetFramework\bin\Debug\SeleniumMsTestDotNetFramework.dll
**\SauceExamples\SeleniumMsTestDotNetFramework\bin\Debug\SeleniumMsTestDotNetFramework.dll
!**\obj\**
D:/a/1/s/dot-net-sauce/SauceExamples/SeleniumMsTestDotNetFramework/bin/Release/SeleniumMsTestDotNetFramework.dll
D:/a/1/s/dot-net-sauce/SauceExamples/SeleniumMsTestDotNetFramework/bin/$(BuildConfiguration)/SeleniumMsTestDotNetFramework.dll
