### ISSUE TITLE
Document references VSTS

### ISSUE THREAD

**Issue by jamers99** [MicrosoftDocs/vsts-docs#1741]
In a few places in the document it still references VSTS.  It should reference Azure DevOps

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 44afc4fe-66c8-a745-0037-00748a80beb7
* Version Independent ID: 0ea09401-6a08-d745-ff50-7a7b74c41f32
* Content: [Migrate from TFVC to Git - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/learn/git/migrate-from-tfvc-to-git)
* Content Source: [https://mseng.visualstudio.com/DefaultCollection/TechnicalContent/_git/devops-learn-pr?path=%2fdocs%2fgit%2fmigrate-from-tfvc-to-git.md&version=GBlive&_a=contents](https://mseng.visualstudio.com/DefaultCollection/TechnicalContent/_git/devops-learn-pr?path=%2fdocs%2fgit%2fmigrate-from-tfvc-to-git.md&version=GBlive&_a=contents)
* Product: **devops**
* Git Login: **samgu**
* Microsoft Alias: **routlaw**

**Comment by steved0x** [comment]
@jamers99 Thanks for letting us know, I will get this fixed up today.

**Comment by thomps23** [comment]
@steved0x do we need to update Team Foundation references with Azure DevOps Server released?
