### ISSUE TITLE
Incorrect Paths

### ISSUE THREAD

**Issue by adamreed90** [MicrosoftDocs/vsts-docs#1743]
Path = "/fields/Microsoft.Azure DevOps Services.TCM.ReproSteps",

It looks like when doing the mass update to Azure DevOps whomever broke the documentation, the correct Path would be :    
  Path = "/fields/Microsoft.VSTS.TCM.ReproSteps",

These namespaces have not been changed to reflect Azure DevOps in the actual product. This documentation is incorrect. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 46b4eaef-d1c1-1b01-76e5-6f0bcfcdffd7
* Version Independent ID: 3eeb5243-4e77-8533-bd3b-22769a247fb8
* Content: [Create a bug using .NET client libraries in Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/integrate/quickstarts/create-bug-quickstart?view=vsts)
* Content Source: [docs/integrate/quickstarts/create-bug-quickstart.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/integrate/quickstarts/create-bug-quickstart.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by bencz** [comment]
The sample code does not work..., Im getting the following error:

> TF51535: Cannot find field Microsoft.Azure DevOps Services.Common.Priority.

**Comment by eduprog** [comment]
During debug I analyzed fields and modified the values 
 Path = "/fields/Microsoft.Azure DevOps Services.TCM.ReproSteps
to
 Path = "/fields/Microsoft.VSTS.TCM.ReproSteps"

and,

Path = "/fields/Microsoft.Azure DevOps Services.Common.Priority"
to
Path = "/fields/Microsoft.VSTS.Common.Priority",

Worked perfectly.

Hope this helps!

**Comment by elbatk** [comment]
Hi everyone! Sorry for the delay - it was most definitely a hazardous find+replace, I'm updating the values as @eduprog suggests, thanks everyone!

**Comment by nibeditadan** [comment]
Hello Team, 
I am getting this Error Message: Work item type Bug does not exist in project xxxxxx or you do not have permission to access it. 
I have generated the PAT with read,write and manage accesses.. can anyone please help me where I am going wrong.
