### ISSUE TITLE
Typo in creating a project under Organization settings > Projects

### ISSUE THREAD

**Issue by jcdenaes** [MicrosoftDocs/vsts-docs#1754]
Hello,

It is both a Product feedback and Content feedback

*Product*
Under Organization settings &gt; Projects, screen link says "New team project..." instead of New project...". Still, the functionality is working as expected.

*Content*
It would be nice to have this way of creating projects in this documentation page too.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 993e00a3-b7d1-8095-5960-f6f12e8606a4
* Version Independent ID: e125d539-3678-2ab4-3591-f055e7225cbc
* Content: [Create a project in Azure DevOps Services or Team Foundation Server (TFS)](https://docs.microsoft.com/en-us/azure/devops/organizations/projects/create-project?view=vsts&tabs=new-nav)
* Content Source: [docs/organizations/projects/create-project.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/projects/create-project.md)
* Product: **devops**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
@jcdenaes Thank you for your feedback. I have forwarded the product feedback and need a little more information from you about what's not correct within the article, if possible, with screenshots. I'm not able to reproduce any discrepancies. Please send me an email at chcomley@microsoft.com for further clarification. Thanks again.
