### ISSUE TITLE
Bulk adding Test cases

### ISSUE THREAD

**Issue by BBQMAN80** [MicrosoftDocs/vsts-docs#1755]
I have approx 400 test cases to enter into TFS. I downloaded the integration tool and am able to connect but when I go to publish the steps they don't get added to the test case. 
When i query the test cases they are all returned in HTML format and I have tried using HTML markup to save the steps but it doesn't work. please help.
ex. 

&lt;DIV&gt;&lt;DIV&gt;&lt;P&gt;test step 1&nbsp;&lt;/P&gt;&lt;/DIV&gt;&lt;/DIV&gt;&lt;DIV&gt;&lt;P&gt;result 1&nbsp;&lt;/P&gt;&lt;/DIV&gt;&lt;DIV&gt;&lt;P&gt;step 2&lt;/P&gt;&lt;/DIV&gt;&lt;P&gt;&nbsp;result 2&lt;/P&gt;&lt;DIV&gt;&lt;P&gt;&lt;/P&gt;&lt;/DIV&gt;

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 505849d3-01c8-a2cd-dc6c-271dd1120e2d
* Version Independent ID: 577fc252-60e4-f670-bb92-6bdbcb7d5c69
* Content: [Bulk modify using Excel - Azure Boards and TFS](https://docs.microsoft.com/en-us/azure/devops/boards/backlogs/office/bulk-add-modify-work-items-excel?view=vsts)
* Content Source: [docs/boards/backlogs/office/bulk-add-modify-work-items-excel.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/boards/backlogs/office/bulk-add-modify-work-items-excel.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@BBQMAN80 - Thank you for your question.  To bulk update test cases, you can use the web portal grid view as documented here, https://docs.microsoft.com/en-us/azure/devops/test/reference-qa?view=vsts#q-is-there-a-way-to-quickly-add-multiple-test-cases-at-the-same-time. I will add a link from the Excel topic to that topic.

**Comment by Gocoollnath** [comment]
There is no other way to upload steps ,apart from using Grid option? For 1000's of test cases, adding test steps using grid is a tedious process
