### ISSUE TITLE
testResultsFile should be testResultsFiles

### ISSUE THREAD

**Issue by paulmarshall** [MicrosoftDocs/vsts-docs#1763]
According to the Reference Task, this property should be called testResultsFiles, not testResultsFile.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c99686eb-6c78-0336-1ec3-802a53c9868d
* Version Independent ID: 6eaf1acb-24d4-5bb7-3935-17abe7e59dd9
* Content: [JavaScript and Node.js](https://docs.microsoft.com/en-us/azure/devops/pipelines/languages/javascript?view=vsts&tabs=yaml#run-unit-tests)
* Content Source: [docs/pipelines/languages/javascript.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/languages/javascript.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by vijayma** [comment]
@steved0x This change looks good. Please merge it.

**Comment by andyjlewis** [comment]
merged
