### ISSUE TITLE
The title suggest that you can change the region of the devops services

### ISSUE THREAD

**Issue by fransen** [MicrosoftDocs/vsts-docs#1767]
I was looking how to change the location of the region. This article only describes how to find the location.

I'm still very interrested how I may change it.

--jw

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be194f45-05b2-8421-186f-f12700eea9aa
* Version Independent ID: efffdc56-fd4c-aeba-6cd3-d07aaf776d51
* Content: [Find or change your Azure DevOps organization location (region)](https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/change-organization-location?view=vsts&tabs=new-nav)
* Content Source: [docs/organizations/accounts/change-organization-location.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/accounts/change-organization-location.md)
* Product: **devops**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @fransen, thank you for alerting me. The information is there, but it was not called out, so I've added a header to the topic.  To change your organization region, call Azure DevOps Support(https://azure.microsoft.com/support/devops). The Support staff will coordinate changing the region with the organization owner. Thanks again.

**Comment by cmw2** [comment]
The content on changing the region only shows when selecting "Previous navigation."  It doesn't show with "New navigation."  (At least in published version today.)

**Comment by chcomley** [comment]
Thanks @cmw2 , the updated header (which is present for both tabs) should go live at any time, no later than around 4pm this afternoon.
