### ISSUE TITLE
Can't find the task

### ISSUE THREAD

**Issue by Nohcho** [MicrosoftDocs/vsts-docs#1769]
Hi,
I've created a release pipeline and agentless job, but nonetheless I cant see the Manual Intervention task. Can you help me with that?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e1c633b9-c8b2-e05d-de2c-7754894d28fd
* Version Independent ID: df031b76-0fe7-e138-dd36-2736757a97fd
* Content: [Manual intervention task for Azure Pipelines and TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/manual-intervention?view=vsts)
* Content Source: [docs/pipelines/tasks/utility/manual-intervention.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/utility/manual-intervention.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by Nohcho** [comment]
I added a Delay task instead. Then after a refresh and coming back to the release pipeline I'm suddenly able to see the Manual Intervention task.

**Comment by cmart89** [comment]
This looks like a bug and should be reopened. I had the same issue of not being able to see the "Manual Intervention Task" until I actually clicked the "Refresh" button by "Add Tasks". All other manual refreshes would not show it until this exact refresh button was clicked.

**Comment by alexhomer1** [comment]
Thank you for your feedback. I've tried this several times and cannot reproduce the issue. I don't think that there is a fault in the documentation. I suggest you post it on the Product Feedback site (Developer Community - https://developercommunity.visualstudio.com/spaces/21/index.html) to see if you can get a more specific answer to the issue.

**Comment by willmorgan** [comment]
@alexhomer1 As of now, all I can see is a 404 for the GitHub URL in the docs:

https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks/ManualIntervention

![image](https://user-images.githubusercontent.com/168688/47030353-7b940380-d165-11e8-8c7d-5242e0a7fff5.png)

**Comment by alexhomer1** [comment]
Looks like the GitHub doc has been removed in favor of the topic "Manual intervention task for Azure Pipelines and TFS" (linked above). I'll remove the link to GitHub.
