### ISSUE TITLE
parallel vs. matrix

### ISSUE THREAD

**Issue by janpio** [MicrosoftDocs/vsts-docs#1770]
&gt; Slicing
&gt; When `parallel` is specified and `matrix` is not defined ...

Does this mean `parallel` and `matrix` can also be used at the same time? [Multi-Configuration](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/phases?view=vsts&tabs=yaml#multi-configuration) above this section only uses `matrix` together with `maxParallel`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 54bf6c2f-95c1-943d-26ae-d7099143bccf
* Version Independent ID: 0833bb55-1e54-6953-ee69-de6d191d2ec1
* Content: [Build and release jobs in Azure Pipelines and TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/phases?view=vsts&tabs=yaml#multi-configuration)
* Content Source: [docs/pipelines/process/phases.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/phases.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment]
Thank you for your feedback. I have passed this on to the product team for advice.

**Comment by PBoraMSFT** [comment]
@janpio - no, matrix and parallel cannot be used together. 
For an example of how to use parallel for slicing, see https://docs.microsoft.com/en-us/azure/devops/pipelines/test/parallel-testing-any-test-runner?view=vsts

**Comment by PBoraMSFT** [comment]
@vijayma @andyjlewis - can you help with this?

**Comment by janpio** [comment]
Just stumbled over some documentation that shows all 3 in the same configuration:
> The full syntax to specify an agent job is:
```
...
  strategy:
    parallel: number
    maxParallel: number
    matrix: { string: { string: string } }
```
https://docs.microsoft.com/en-us/azure/devops/pipelines/process/phases?view=vsts&tabs=yaml

I'm pretty sure this is just not fully fleshed out all the way through all the docs. 
I appreciate you reopening this and replying.

**Comment by vtbassmatt** [comment]
Fix in progress. Syntactically, all three are siblings. Semantically:

- You can use `maxParallel` alongside either of the strategies.
- The two strategies `parallel` and `matrix` are mutually exclusive, so you can only use one or the other.

**Comment by chrisrpatterson** [comment]
There was a bug that prevented the matrix from running in parallel by default that has no been fixed.  It should roll out over the next few weeks on the service.

**Comment by ajklotz** [comment]
I have a build pipeline using the matrix strategy, and I'm specifying **maxParallel:** 1 but I'm seeing multiple jobs from the matrix running at the same time. **maxParallel** doesn't seem to be honored.

**Comment by vtbassmatt** [comment]
@ajklotz it seems to be working for me. But feel free to report it over on [Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html).

**Comment by ajklotz** [comment]
Disregard, I had different sets of Jobs and the matrix didn't apply to the other ones. My fault!
