### ISSUE TITLE
Self signed certificate in certificate chain error

### ISSUE THREAD

**Issue by pundj** [MicrosoftDocs/vsts-docs#1772]
Task doesn't run for me, only gives this error: "ERR:self signed certificate in certificate chain" with no explanation of how to work around this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2d4861e9-3c5e-ccc8-6918-f5a7327de545
* Version Independent ID: 8681cf86-9935-2063-ab5d-7ece1e14a2b1
* Content: [NuGet Tool Installer - Azure Pipelines & TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/nuget?view=vsts)
* Content Source: [docs/pipelines/tasks/tool/nuget.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/tool/nuget.md)
* Product: **devops**
* GitHub Login: @erickson-doug
* Microsoft Alias: **amullans**

**Comment by pundj** [comment]
Determined this was caused by the firewall on my network. Still think it would be nice to have a way to ignore this, if chosen, but I'll go ahead and close the issue since it is resolved.

**Comment by shivanaru** [comment]
How did you resolve this? Having similar issue. Thanks!

**Comment by jorymorrison** [comment]
Also wondering what workarounds exist for this issue.

**Comment by DanHK** [comment]
The issue might be closed but unfortunately unresolved...

**Comment by DalpheSDC** [comment]
What is the workaround for this issue. I know that we are behind a proxy, so what todo about this certificate issue?

**Comment by shivanaru** [comment]
@DalpheSDC - copy the cert to the ca-bundle.crt and update git config to read from the updated cert bundle. Like mentioned here - https://stackoverflow.com/a/49515609. That resolved it for us.

**Comment by sheepnerd** [comment]
Node seems to have sha256 hash computation failure on Intel CPU that has no avx feature. 
    Intel Pentium J4205
    Intel Celeron J3455
    Intel Celeron J3355
    Intel Pentium N4200
    Intel Celeron N3350
    Intel Celeron N3450
    Intel Atom x7-E3950
    Intel Atom x5-E3940
    Intel Atom x5-E3930

This couse mess node, openssl and some Intel Celeron processors. Ultimate couses DevOps nuget tool fail too. To work around add environment variable 

OPENSSL_ia32cap=~0x1000000000000000:~0

Under system variables and reboot. Wasted all day to figuring this one out.
