### ISSUE TITLE
Single organization Vs Multiple organization recommendation

### ISSUE THREAD

**Issue by nikoNguyen** [MicrosoftDocs/vsts-docs#1773]
An important point to consider is licencing model for AzureDevops Extension.
it is (for now) by Organization so if you have a multi organization model you will have to pay for more licences

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bc718cc3-3403-86f8-f859-682311511d65
* Version Independent ID: ccc59b39-92c8-1fae-3d8a-ceae66745fa9
* Content: [Define organizations and projects in Azure DevOps - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/user-guide/define-organizations-and-projects?view=vsts)
* Content Source: [docs/user-guide/define-organizations-and-projects.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/user-guide/define-organizations-and-projects.md)
* Product: **devops**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by byatis** [comment]
I totally agree, and this is the main reason we won't use the organization currently at all. Extensions should be by subscription or something like that instead.

**Comment by chcomley** [comment]
Thanks for your feedback, @nikoNguyen and @byatis, I've created a work item to address this.
