### ISSUE TITLE
Variable is "useDefaultContext" not "useDefaultBuildContext"

### ISSUE THREAD

**Issue by LazerFX** [MicrosoftDocs/vsts-docs#1778]
You've a typo in the variable details - it's "useDefaultContext" and not "useDefaultBuildContext".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d9dbf88-7e55-d427-145e-d36b04fb197f
* Version Independent ID: a3f30c00-817c-9c05-7a57-3f2bf618821e
* Content: [Docker](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/docker?view=vsts)
* Content Source: [docs/pipelines/tasks/build/docker.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/build/docker.md)
* Product: **devops**
* GitHub Login: @erickson-doug
* Microsoft Alias: **dastahel**

**Comment by DavidStaheli** [comment]
Confirmed fixed.  Thank you @LazerFX!
