### ISSUE TITLE
Missing python 3.6 (MacOSx Microsoft hosted agent)

### ISSUE THREAD

**Issue by lasote** [MicrosoftDocs/vsts-docs#1784]
The agent is supposed to support 3.6.5 but it doesn't work. If you try x86 it will tell you that there is available a 3.6.5 for x64.

```
##[error]Version spec 3.6 for architecture x64 did not match any version in the tool cache.
Available versions:

```

2.7 is available

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: e765cfad-8ab9-443a-1171-5af81a31252f
* Version Independent ID: 8ff69d93-0128-dbeb-9d63-45266ed73020
* Content: [Use Python Version](https://docs.microsoft.com/es-es/azure/devops/pipelines/tasks/tool/use-python-version?view=vsts)
* Content Source: [docs/pipelines/tasks/tool/use-python-version.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/tool/use-python-version.md)
* Product: **devops**
* GitHub Login: @erickson-doug
* Microsoft Alias: **brcrista**

**Comment by brcrista** [comment]
@lasote is this still happening for you?

**Comment by brcrista** [comment]
3.6 should be available for x64 on hosted macOS.  The x86 versions are only for Windows.

**Comment by lasote** [comment]
I don't know, I didn't try again. If there is evidence it is fixed for me this can be close. Thanks

**Comment by brcrista** [comment]
Hosted macOS should now support the Use Python Version task.  @DavidStaheli , I think we can close this.
