### ISSUE TITLE
Multi stage deployment for azure website should include 

### ISSUE THREAD

**Issue by andreasblueher** [MicrosoftDocs/vsts-docs#1787]
Like I said in the title for me multi stage and deployment slots should be one thing when using azure websites as an expample. Having multiple azure websites when all you want is separation is overhead you should avoid.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d589bb13-a51a-77a5-d2f0-f424e42ede04
* Version Independent ID: 7b250082-a9c0-7dc2-9381-d04fbc5b7624
* Content: [Define a multi-stage CD release pipeline - Azure Pipelines & TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/define-multistage-release-process?view=vsts)
* Content Source: [docs/pipelines/release/define-multistage-release-process.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/release/define-multistage-release-process.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment]
Thank you for your feedback. It's not clear what you feel is misleading in the topic. Can you be more precise please?

**Comment by andreasblueher** [comment]
Hello Alex,

the documentation is about the multi stage release process. Azure websites are being used as the prime example and yet you're not using deployment slots, which (imho) is the better option there.

Reading this article would lead me to the assumption, that I have to have multiple Azure Websites to be able to do multi stage releases, which is not the case. Deployment slots and multistage release should be bound together. I hope this clears my initial request up.

**Comment by adventworks** [comment]
The goal of a multi-stage Azure web app deployment is to deploy to QA followed by production. I have not seen a real scenario where QA and production share slots in a production site, let alone in the same subscription. Having said that, slots can be used within a stage to reduce downtime. If slots are used in production web app, then we would recommend that slots be used in QA stage as well to ensure that the same procedures are followed in every stage of the pipeline. Stages and slots when used in this manner are complementary.
