### ISSUE TITLE
how can i update an policy already executed?

### ISSUE THREAD

**Issue by brianhsb1671** [MicrosoftDocs/vsts-docs#1793]
Hi,

I have a custom branch policy, i need to update the status when some changes happen with pipelines. How can i configure my policy in order to allow update or re-execute policy?

When my policy execute with an error, i cant exeucte my policy again, i need to abandon de PR and create a new one.

Thanks!

**Comment by steved0x** [comment]
@brianhsb1671 Whenever a new push is made to the branch it should reevaluate all of the branch policies. Are you asking how to reevaluate the branch policies based on some event that happens in your pipeline? Can you share more details of your scenario and I can see if we can find a solution for you.
