### ISSUE TITLE
"Multiple schedules as required" not available

### ISSUE THREAD

**Issue by jabteles** [MicrosoftDocs/vsts-docs#1795]
"A predefined schedule. When you select this option, you can select the days of the week and the time of day that Release Management will automatically start a new deployment. You can configure multiple schedules as required. Note that, with scheduled triggers, a new deployment is created even if a newer version of artifact is not available."

Hello, I don't have the option to select multiple deploy schedules  on an environment as mentioned in the documentation, I can only choose one.

Can you please clarify?

Using TFS 2018 Update 2.

Regards,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d9e313c5-9120-9172-bc27-c21d10fcd5ae
* Version Independent ID: 1a837182-591f-3cbc-1632-7b50d857b13c
* Content: [Release triggers for stages, branches, and pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/triggers?view=vsts)
* Content Source: [docs/pipelines/release/triggers.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/release/triggers.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment]
Thank you for your feedback. I will update the topic to fix the issue. Multiple schedules are available only for scheduled release triggers (defined using the schedule icon in the Artifacts section), and not for scheduled stage triggers.
