### ISSUE TITLE
Requestb.in is not available any longer

### ISSUE THREAD

**Issue by Splaxi** [MicrosoftDocs/vsts-docs#1796]
But you can use https://beeceptor.com while learning about the data coming out Azure DevOps

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4806b641-fdb1-c0e9-081c-c007807c7cdb
* Version Independent ID: f59d8501-1285-be79-b084-8371ed8395bb
* Content: [WebHooks with Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/service-hooks/services/webhooks?view=vsts)
* Content Source: [docs/service-hooks/services/webhooks.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/service-hooks/services/webhooks.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by adamwride** [comment]
https://requestbin.fullcontact.com seems to be where it migrated to.

**Comment by elbatk** [comment]
Hi people, we are getting these Service Hooks docs updated, I'll add this to stuff we should change, thank you!
