### ISSUE TITLE
Tiller install

### ISSUE THREAD

**Issue by timwebster9** [MicrosoftDocs/vsts-docs#1799]
It's not clear from reading this if it can be used to install Tiller.

First of all, it says `You can use the task to install/update Tiller`.  OK, but how do you do this?  There is an argument called `install`, but the documentation then doesn't have an entry for that - it only has one for `Install if release not present`, and that sounds like it's for installing charts, not Tiller.

Furthermore, it says `Helm Tool installer task can be used to get the right version of Helm on the agents`.  Does this mean you need to run this task first before using the Helm Deploy task?  Or just if you need a different version?  Does the `Helm Deploy` already have Helm installed?  If so, what happens when you run the Helm Tool installer first task on the agent?

Clear documentation would save a lot of trial and error..

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fc7eeb7f-4e6b-8fee-1d7f-582cfb018b02
* Version Independent ID: 00fb3082-1069-9060-012c-0b6d75ef120b
* Content: [Package and deploy Helm Charts](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/helm-deploy?view=vsts)
* Content Source: [docs/pipelines/tasks/deploy/helm-deploy.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/deploy/helm-deploy.md)
* Product: **devops**
* GitHub Login: @erickson-doug
* Microsoft Alias: **dastahel**

**Comment by timwebster9** [comment]
nevermind - you can install Tiller using 'helm init'.  This can be closed.

**Comment by steved0x** [comment]
@timwebster9 Thanks for letting us know, I am closing this issue and passing this feedback along to the author.
