### ISSUE TITLE
Load test error limitation exception

### ISSUE THREAD

**Issue by cloudmelon** [MicrosoftDocs/vsts-docs#1800]
Load test error limitation exception while got more than 1000 errors ( 500 http error ) and then return 503 server unavailable 

![image](https://user-images.githubusercontent.com/4621560/45747339-d5a4b600-bc05-11e8-8a71-1b23a9b2bd61.png)

Doc URL :  https://docs.microsoft.com/en-us/azure/devops/test/load-test/record-and-replay-cloud-load-tests?view=vsts

**Comment by alexhomer1** [comment]
Thank you for your feedback. I have passed this on to the product team for advice.

**Comment by cloudmelon** [comment]
I can share you my whole code which is ok for this test ( by using the
information from your part )

import java.util.Properties;
import javax.mail.*;
import javax.mail.internet.*;

public class EmailSMTP {
  private static final String SMTP_HOST_NAME = "smtp.sendgrid.net";
  private static final String SMTP_AUTH_USER = "xxxusername";
  private static final String SMTP_AUTH_PWD = "xxxxpwd";

public static void main(String[] args) throws Exception {
new EmailSMTP().SendMail();
}
public void SendMail() throws Exception
{
     Properties properties = new Properties();
        properties.put("mail.transport.protocol", "smtp");
        properties.put("mail.smtp.host", SMTP_HOST_NAME);
        properties.put("mail.smtp.port", 587);
        properties.put("mail.smtp.auth", "true");

     Authenticator auth = new SMTPAuthenticator();
     Session mailSession = Session.getDefaultInstance(properties, auth);
     MimeMessage message = BuildMessage(mailSession);

     Transport transport = mailSession.getTransport();
  // Connect the transport object.
  transport.connect();
  // Send the message.
  transport.sendMessage(message, message.getAllRecipients());
  // Close the connection.
  transport.close();

}

public MimeMessage BuildMessage (Session mailSession) throws Exception
{
MimeMessage message = new MimeMessage(mailSession);
Multipart multipart = new MimeMultipart("alternative");
BodyPart part1 = new MimeBodyPart();
part1.setText("Hello, Your Contoso order has shipped. Thank you, John");
BodyPart part2 = new MimeBodyPart();
part2.setContent(
    "<p>Hello,</p><p>Your Contoso order has <b>shipped</b>.</p><p>Thank
you,<br>John</br></p>",
    "text/html");
multipart.addBodyPart(part1);
multipart.addBodyPart(part2);
message.setFrom(new InternetAddress("john@contoso.com"));
message.addRecipient(Message.RecipientType.TO,
   new InternetAddress("someone@cloudmelon.com"));
message.setSubject("Your recent order");
message.setContent(multipart);
return message;
}
private class SMTPAuthenticator extends javax.mail.Authenticator {
public PasswordAuthentication getPasswordAuthentication() {
   String username = SMTP_AUTH_USER;
   String password = SMTP_AUTH_PWD;
   return new PasswordAuthentication(username, password);
}
}

}

Here is what I have done and it works well.

**Comment by divais** [comment]
+Prachi

Thanks,
Divya Vaishnavi | Program Manager

**Comment by PBoraMSFT** [comment]
@cloudmelon - the screenshot shows that you have had more than 1000 errors of the type 500 Internal Server Error. We impose this limit because if you have so many errors, your test is basically not doing the right thing and the results you get are meaningless. If you fix the root cause of why you get 500 Internal server error, the problem should go away.

As an aside, this repo is for documentation issues. If you have product bugs to report / feature suggestions, please use the developer community channel https://developercommunity.visualstudio.com/spaces/21/index.html
