### ISSUE TITLE
Fabric

### ISSUE THREAD

**Issue by damienix** [MicrosoftDocs/vsts-docs#1803]
The controls here are not very useful. I've just found (after publishing our extension) that you have Fabric UI available for a variety of technologies:
https://dev.office.com/fabric-js (Pure js)
https://developer.microsoft.com/en-us/fabric (React)
https://developer.microsoft.com/en-us/fabric#/angular-js (Angular)
https://github.com/aidewoode/office-ui-fabric-vue (Unofficial Vue wrapper)
and more.

How about mentioning these options for VSTS developers before they start implementing their extensions. Is there a reason not to use one of the above? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e73d5c2c-b77b-d5bc-a0cb-03d948d98f1d
* Version Independent ID: a3f4410b-0ee6-cd88-f68b-2c3ce889c464
* Content: [Configure UI Controls](https://docs.microsoft.com/en-us/azure/devops/extend/develop/ui-controls/configure?view=vsts)
* Content Source: [docs/extend/develop/ui-controls/configure.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/extend/develop/ui-controls/configure.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by elbatk** [comment]
Hey @damienix , sorry about the long delay here. Adding @matthewisabel here for his input. Matthew, should I add those options to the docs?

**Comment by damienix** [comment]
Nice.

**Comment by matthewisabel** [comment]
We're revamping our documentation now and have made all of the core components we've made available. We'll be launching a public documentation site for it shortly and doing a blog post on updates to the extension sdk.

If you want to see some examples, our new samples all use our azure-devops-ui npm package that we recommend using: https://github.com/Microsoft/azure-devops-extension-sample.

There will be more guidance coming soon on how to use our components, but hopefully the samples are a valuable starting place for now.
