### ISSUE TITLE
Using VssBasicCredential + PAT raises VssUnauthorizedException when run from Azure (local workstation + Azure function works)

### ISSUE THREAD

**Issue by ktundwal** [MicrosoftDocs/vsts-docs#1807]
I have a WebAPI that creates VSTS tasks. I created a Personal access token using my own MSFT OrgId and used code (below) to connect to VSTS.

On my local workstation code works. However, when this code runs on Azure, I get following exception

```
Exception=Microsoft.VisualStudio.Services.Common.VssUnauthorizedException:
 VS30063: You are not authorized to access https://dev.azure.com.
```
I tested it in Azure Function, and it worked there too.

Code (uses alt user/pass, it fails for PAT too)

```
VssConnection connection = new VssConnection(new Uri(Uri), new VssBasicCredential(
    ConfigurationManager.AppSettings['VsoUsername'],
    ConfigurationManager.AppSettings['VsoPassword']));

using (var client = connection.GetClient<WorkItemTrackingHttpClient>())
{
    var result = await client.GetWorkItemAsync(vsoId);
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e978322f-15ae-3a89-ae89-497cdfa5070a
* Version Independent ID: f8654902-e266-c12b-8e25-a2fa7a2ac626
* Content: [Get work items programmatically from Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/integrate/quickstarts/work-item-quickstart?view=vsts)
* Content Source: [docs/integrate/quickstarts/work-item-quickstart.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/integrate/quickstarts/work-item-quickstart.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by ktundwal** [comment]
Hi @elbatk - Following made the code work
1. I switched `VssBasicCredential` with `VssAadCredential`.
2. Instead of PAT, I used user/pass. User format = <alias>@<domain>.com

New issue now
1. I created a new user in a customer Active Directory. Say foo@somedir.onmicrosoft.com
2. I added this as a guest user to my org aad (in this case microsoft.onmicrosoft.com)
3. I used user/pass for this user in `VssAadCredential` and i got following in fiddler

```
{
    "$id": "1",
    "innerException": null,
    "message": "TF400813: The user '' is not authorized to access this resource.",
    "typeName": "Microsoft.TeamFoundation.Framework.Server.UnauthorizedRequestException, Microsoft.TeamFoundation.Framework.Server",
    "typeKey": "UnauthorizedRequestException",
    "errorCode": 0,
    "eventId": 3000
}
```

**Comment by elbatk** [comment]
Hey @ktundwal , sorry it's been so long here. I'm adding @willsmythe to take a look when he gets time and see if we can't help. I'd suggest you post any product issues to the [Azure DevOps Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html), as it's monitored by the product team.
