### ISSUE TITLE
Custom Field not allowed in Scrum process as exists in CMMI process?

### ISSUE THREAD

**Issue by cmeyer79** [MicrosoftDocs/vsts-docs#1812]
Since I am newer to the Azure DevOps tool, I was wondering why I could not use a WIT that is in one process but not the process that I'm currently trying to create a custom field in. For instance, I'm trying to create a Root Cause field in Scrum process but getting a duplicate field found error. I would assume it is because it exists in the CMMI template....assuming those the templates are not independent of each other? If this is the case then should it be documented? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 12084832-5567-c723-2e87-aeaac920aa31
* Version Independent ID: 7620ba4b-7bbd-0c1d-882f-374b9278a315
* Content: [Index of default and system work item fields - Azure Boards and TFS](https://docs.microsoft.com/en-us/azure/devops/boards/work-items/guidance/work-item-field?view=vsts)
* Content Source: [docs/boards/work-items/guidance/work-item-field.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/boards/work-items/guidance/work-item-field.md)
* Product: **devops**
* GitHub Login: @erickson-doug
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@cmeyer79 - Thank you for your inquiry. All fields listed in the index are defined for the collection. You can add a field defined for the CMMI process to a Scrum work item type - as an existing field. For Azure DevOps Services, see [Add or modify a field for an inherited process](https://docs.microsoft.com/en-us/azure/devops/organizations/settings/work/customize-process-field).
