### ISSUE TITLE
How do I revoke NPM credentials?

### ISSUE THREAD

**Issue by octogonz** [MicrosoftDocs/vsts-docs#1814]
I clicked the "Generate NPM credentials" button that is listed on this page, which created a token.  How do I later revoke this token?  The documentation does not explain how to do that.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cb7c2ab6-4ba1-51d5-96bb-38a9ab6b50c3
* Version Independent ID: 415de875-ba1b-476b-f08b-1a61dc7a2747
* Content: [Set up your client's npmrc](https://docs.microsoft.com/en-us/azure/devops/artifacts/npm/npmrc?view=vsts&tabs=new-nav#feedback)
* Content Source: [docs/artifacts/npm/npmrc.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/artifacts/npm/npmrc.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by mchelen** [comment]
Maybe each time you generate new NPM credentials it invalidates the old one?

**Comment by elbatk** [comment]
Hi @octogonz , currently there is no way to manage the token that gets created in this method. We've heard this as a pain point and we're currently taking a look at the entire Connect to Feed dialog to get this onboarding flow correct. I'm going to close this as a docs issue as this is something we're tracking on the product side of things, but I would be interested to know your opinion on how you'd like to see this work - more configuration options when creating token? A link to manage the token with the token name after creation? Let us know :)

**Comment by octogonz** [comment]
@elbatk GitHub's **Settings -> Developer settings -> Personal access tokens** is a pretty decent design.

>  currently there is no way to manage the token that gets created in this method

What happens if the token is accidentally leaked?  (For example, what if a person accidentally pushes their npmrc file to Git?)  Is there no way to revoke the token?
