### ISSUE TITLE
"Auto Logon and Lock" link broken

### ISSUE THREAD

**Issue by JacobHenner** [MicrosoftDocs/vsts-docs#1816]
The link to ["Auto Logon and Lock"](http://www.tuaw.com/2011/03/07/terminally-geeky-use-automatic-login-more-securely/) is broken. It redirects to engadget.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c9cb3bd5-5c72-4ad6-8566-3bc4527112ce
* Version Independent ID: 4c0f61d9-0d61-83e6-ece5-4d96ca91e9d1
* Content: [Deploy a build and release agent on macOS](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/v2-osx?view=vsts)
* Content Source: [docs/pipelines/agents/v2-osx.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/agents/v2-osx.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by andyjlewis** [comment]
Hi @JacobHenner, thank you for the heads up. I'm following up.
