### ISSUE TITLE
For a build pipeline, the "pool" Yaml setting, along with child "vmImage" isn't ever articulated.

### ISSUE THREAD

**Issue by cicorias** [MicrosoftDocs/vsts-docs#1818]
What does `pool` and `vmImage` refer to? Nothing explains it. I'm kinda thinking it has something to do with how named in HyperV - bit, that's just not true. I tried "Default" - that didn't work either.  Also, this setting overrides what a user specifies if they queue a new Build and select an Agent Pool
pool:
  vmImage: 'Ubuntu 16.04'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '8.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'npm install and build'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7458d5b2-1bb7-7d87-7ce6-2b0c430b0155
* Version Independent ID: edf5bbd3-a3f0-5426-e985-31290f8afd05
* Content: [YAML schema - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=vsts)
* Content Source: [docs/pipelines/yaml-schema.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/yaml-schema.md)
* Product: **devops**
* GitHub Login: @erickson-doug
* Microsoft Alias: **macoope**

**Comment by vtbassmatt** [comment]
Fix is in PR on the internal repo
