### ISSUE TITLE
"Web app for Containers" is missing from App type

### ISSUE THREAD

**Issue by holotrek** [MicrosoftDocs/vsts-docs#1819]
When I try to select "Web App for Containers" under step 3 when adding a release stage of Deploy Azure App Service, all I get is "Web App" and the containerized web app is missing from the dropdown for "App service name". This is a Free Trial sub, is that limited?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 593c3abc-7b38-6673-62b6-7787d0dda4dd
* Version Independent ID: cbb2b875-b220-596c-7b4d-c2cf6c644335
* Content: [Deploy a Docker container app to an Azure Web App](https://docs.microsoft.com/en-us/azure/devops/pipelines/apps/cd/deploy-docker-webapp?view=vsts)
* Content Source: [docs/pipelines/apps/cd/deploy-docker-webapp.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/apps/cd/deploy-docker-webapp.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment]
Thank you for your feedback. I have passed this on to the product team for advice.

**Comment by seesharprun** [comment]
You need to select the "Preview" version which is 4.0.

The drop-down list where you select the version of the task is at the top of the page when you are editing a task.

**Comment by chazguerrero** [comment]
When will there be the addition of a compose file or k8s deploy file?

**Comment by kkho** [comment]
Tried to deploy with dotnet core Project.  Just a dummy app. Followed the recipe all the steps except step 3 (which does not find web app container that I created in azure portal) and tried to run web app wtih multi containers. Uploaded a docker compose script and got an error saying that the image was not found, also when I tried to deploy a container as a web app from acr. It did not even work, still got the same problem with image not found...

Running locally works and please fix this problem.

**Comment by azooinmyluggage** [comment]
@kkho We have improved the task. Please try the 4.0 version. 
The multi-container support is under development.

Let me know if you have any other feedback for improving container support.

**Comment by ceemafour** [comment]
Any update on multi container support please

**Comment by azooinmyluggage** [comment]
we have added support for Azure Web app - multi-container scenario.
