### ISSUE TITLE
Team Foundation Server Configuration failed

### ISSUE THREAD

**Issue by md-masum** [MicrosoftDocs/vsts-docs#1820]
VS403185: An unknown error has occurred during Search configuration. Retry the operation and if problem persists, please contact Microsoft Customer Support(https://go.microsoft.com/fwlink/?LinkId=808053) for help.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4f03d007-1303-234b-c32c-de06924d8688
* Version Independent ID: c1bc50f6-d0f8-777c-2a83-d1d892841d12
* Content: [Search across all your code and work items](https://docs.microsoft.com/en-us/azure/devops/project/search/overview?view=vsts&tabs=new-nav)
* Content Source: [docs/project/search/overview.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/project/search/overview.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment]
Please contact the Search team at vstssearch@microsoft.com directly. They will be able to help you resolve the issue. Thank you!
