### ISSUE TITLE
Deployment Group Severs

### ISSUE THREAD

**Issue by jzserai** [MicrosoftDocs/vsts-docs#1824]
With a simple environment configuration of just one web server and one database server, why not just use just the web server in the deployment group? The web server already has access to the database server and only one agent has to be installed.
Using the same IIS tasks works for the web application but SQL Server Database Deploy task does not run pre- and post-deployment scripts.
I use a Command Line task instead to run SqlPackage which then runs the scripts automatically.
The drawback is that you either have to hard-code the path to SLPackage.exe or use another task to return the path to the latest version of SqlPackage in a previous step. But it seems easier than trying to add separate steps to run pre- and post-deployment scripts.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4e2663d5-b101-2eca-984a-51a25b972d0b
* Version Independent ID: 6779599b-291e-4324-8dca-992885856e57
* Content: [Use IIS Deployment Groups for rolling deployments and databases](https://docs.microsoft.com/en-us/azure/devops/pipelines/apps/cd/howto-webdeploy-iis-deploygroups?view=vsts#envirconfig)
* Content Source: [docs/pipelines/apps/cd/howto-webdeploy-iis-deploygroups.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/apps/cd/howto-webdeploy-iis-deploygroups.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment]
Thank you for your feedback. I have passed this on to the product team for advice.

**Comment by RoopeshNair** [comment]
Can you please elaborate the text 

> Using the same IIS tasks works for the web application but SQL Server Database Deploy task does not run pre- and post-deployment scripts.

SQL deploy task that runs on deployment groups can accept multiple sql files. And you can run this task on the same machine where the web server is running

![image](https://user-images.githubusercontent.com/1370480/45829988-c6af2800-bd19-11e8-8b08-688de0b22718.png)

**Comment by jzserai** [comment]
What I meant is that my pipeline uses the same IIS deployment tasks as depicted in your documentation. But using a SQL Server Database Deploy task only publishes the schema changes. It does not execute the pre- and post-deployment scripts.

- SQL deploy task that runs on deployment groups can accept multiple sql files. 
I'm not sure what you mean with this. Do you mean adding a separate SQL Deploy task for the pre- and post-deployment scripts and selecting SQL Query File? If so, then the pipeline becomes tightly coupled to the database project at that point in time. If any scripts are added or removed, the pipeline would have to be updated as well.

- And you can run this task on the same machine where the web server is running.
Yes, I know that. But your documentation instructs people to install an agent on the database server for the SQL Deploy task.

My solution is to use the web server alone in the deployment group, and use the same IIS deployment tasks as specified in your documentation. But instead of using the SQL Server Database Deploy task, I use the Command Line task to call SqlPackage.exe directly, passing in the variables for the server, database, user, and password. The password is a secret variable that our database administrator created in our project after creating the same user on the target database server in the dbcreator role. I also had to add the user to the database project (without login) because the task complained about the missing user. But, also, we only deploy only a few types of changes, not including anything security related or database properties, so adding the user in the project did not change what was deployed.

**Comment by Ajay-MS** [comment]
@jzserai 

you can include pre and post-deployment scripts as part of your database solution. Now the build will generate DACPAC which will contain both pre and post-deployment scripts. 

During the deployment of DACPAC file using SQL Server Database Deployment task, pre and post-deployment scripts will be executed automatically. 

I assume there is no need of adding SQL Server Database Deployment task multiple time in the pipeline as follow: 

-  SQL Server Deploy task - Pre-deployment script ( Query File )
-  SQL Server Deploy task - DACPAC deployment   ( DACPAC file)
-  SQL Server Deploy task - Post-deployment script ( Query File ) 

Only a single SQL Server task should achieve it and I think it would be cumbersome to maintain a separate PS script for it. 

Please let me know if missed something in the problem.

**Comment by jzserai** [comment]
I originally made this post to
1. Inform you that the SQL Server Deploy Task in Azure DevOps does not execute pre- and post-deployment scripts, at least when executed from a remote server, and 
2. Show you an alternate method that does execute the pre- and post-deployment scripts when executed from a remote server.

Our configuration is to deploy the agent on the web server and execute deployments to the web server and database server from there. This is different that your documentation that instructs readers to deploy the agent on the database server. Perhaps that is what the SQL Server Deploy Task requires, but I don't know.

_you can include pre and post-deployment scripts as part of your database solution. Now the build will generate DACPAC which will contain both pre and post-deployment scripts._
- Yes I know this. I use pre- and post-deployment scripts in many of my database projects. 

_During the deployment of DACPAC file using SQL Server Database Deployment task, pre and post-deployment scripts will be executed automatically._
- **No, it does not**. In fact, another MS MVP verified this in another blog. I realize that it seems like the task should execute the deployment scripts, but it does not. Perhaps if the task ran on an agent on the database server itself it might then execute the scripts, but that is not our preferred agent configuration.

_I assume there is no need of adding SQL Server Database Deployment task multiple time in the pipeline as follow:
SQL Server Deploy task - Pre-deployment script ( Query File )
SQL Server Deploy task - DACPAC deployment ( DACPAC file)
SQL Server Deploy task - Post-deployment script ( Query File )
Only a single SQL Server task should achieve it and I think it would be cumbersome to maintain a separate PS script for it._
- As I stated, I do not use the SQL Server Deploy Task anymore because it does not execute my pre- and post-deployment scripts. Instead, I use the Command Line Task to call SqlPackage.exe directly, using variables. I also use the secret variables for the credentials to the database. This works very nicely for us. This also gives us some options for gathering output from SqlPackage for the database team to view.

Perhaps if you modify/fix the SQL Server Deploy Task to execute the pre- and post-deployment scripts when executing SqlPackage from a remote server, I may give it another try.

**Comment by RoopeshNair** [comment]
> No, it does not. In fact, another MS MVP verified this in another blog. I realize that it seems like the task should execute the deployment scripts, but it does not. Perhaps if the task ran on an agent on the database server itself it might then execute the scripts, but that is not our preferred agent configuration.

This issue was reported against deployment group task to deploy SQL changes. In Deployment Group model you have to install the agent on the target and it does execute pre/post deployment SQL scripts part of your database projects.
