### ISSUE TITLE
Is the first tip correct

### ISSUE THREAD

**Issue by DavidHBallantyne** [MicrosoftDocs/vsts-docs#1825]
In the first green "Tip" section, I see two tips - one "for users who will manage features at the project level admin context..." and one "for users who will manage features provided at the collection-level admin context"

Despite the difference in levels between the two statements, they both say "...add them to the Project Administrators group."

Is this correct?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ae5c3b5-9751-743f-6e68-d20a2fac6243
* Version Independent ID: 66756817-161b-cadf-f13c-10a216fae08a
* Content: [Set project-level or collection-level permissions - Azure DevOps Services & TFS](https://docs.microsoft.com/en-us/azure/devops/organizations/security/set-project-collection-level-permissions?view=vsts&tabs=new-nav)
* Content Source: [docs/organizations/security/set-project-collection-level-permissions.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/security/set-project-collection-level-permissions.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@DavidHBallantyne - Thank you for your inquiry. The seond sentence should point to the Project Collection Administrators group.  I am updating the article now and the updates should be live later today.
