### ISSUE TITLE
feature request: Having a field for renaming the file

### ISSUE THREAD

**Issue by wood1986** [MicrosoftDocs/vsts-docs#1833]
In Pipelines &gt; Library &gt; Secure files, Currently we are unable to put the description for the file. Because of that, I have to use the filename. But it will be very inconvenient for the group task situation which consumes this filename.

For example, there are two files PROD.key and INT.key in Pipelines &gt; Library &gt;Secure files. I would expect one task consume this file. Because of two different filename, I have to create two tasks or use pre-defined variable.

If there is a place to rename the secure file, then I do not have to create two tasks or specify the pre-defined variable 
 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a5f8376-3654-0ed4-d9f8-d15f28350783
* Version Independent ID: f393daba-6515-6c26-71ac-b557e8c8dad1
* Content: [Download Secure File - Azure Pipelines & TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/download-secure-file?view=vsts)
* Content Source: [docs/pipelines/tasks/utility/download-secure-file.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/utility/download-secure-file.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by DavidStaheli** [comment]
Hi @wood1986.  It's been several months since you suggested this feature, but I want to let you know that it's on our backlog and I'm hopeful we can complete it in early 2019.  Thank you for suggesting it.  I'll close this issue for now, but I've made a note to reply here once the feature becomes available.
