### ISSUE TITLE
How should I use for package version ci build?

### ISSUE THREAD

**Issue by WeihanLi** [MicrosoftDocs/vsts-docs#1834]
I'm using vsts pipeline to build my nuget package, how should I use for package version ci build?
Is there some best practices?

**Comment by alexmullans** [comment]
Some [guidance](https://docs.microsoft.com/en-us/azure/devops/pipelines/targets/nuget?toc=%2Fazure%2Fdevops%2Fartifacts%2Ftoc.json&view=vsts&tabs=yaml#package-versioning) is here.

**Comment by WeihanLi** [comment]
Thanks @alexmullans ,any suggestion for package reference? Is floating version recomended?

**Comment by alexmullans** [comment]
The .NET Core task contains the same automatic versioning described in that doc.
