### ISSUE TITLE
Error when installing App in Zendesk

### ISSUE THREAD

**Issue by KristofferWest** [MicrosoftDocs/vsts-docs#1835]
I get an error when I try to install the App in Zendesk.
I got to the sted where I have zipped the downloaded content from GitHub and find the package.

"Upload Error
Could not find manifest.json in the root of the zip file, but dist/manifest.json was found. Try re-creating the archive from this directory."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c1646acb-1bd0-d506-fe70-1b749cccbbc4
* Version Independent ID: 89aa9387-8ce6-9877-8e90-5f7c655b4b77
* Content: [Zendesk with Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/service-hooks/services/zendesk?view=vsts)
* Content Source: [docs/service-hooks/services/zendesk.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/service-hooks/services/zendesk.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by ARenfroe** [comment]
Any movement on this?  I ran into the same issue earlier.  I moved the manifest.json file and zipped again.  Error persisted.

**Comment by ARenfroe** [comment]
@KristofferWest download from here. https://github.com/Microsoft/vsts-zendesk-app/releases

**Comment by KristofferWest** [comment]
It works :)

**Comment by KristofferWest** [comment]
Thank you

**Comment by elbatk** [comment]
Glad you could get it worked out, @KristofferWest , thanks for the help @ARenfroe . Closing this :)
