### ISSUE TITLE
This page is a mess

### ISSUE THREAD

**Issue by MichaelHarmsen** [MicrosoftDocs/vsts-docs#1836]
The title of this page is still "Syntax guidance for for markdown usage" with an extra "for" as already mentioned a week ago in #1716. 

While the title talks about markdown usage, the page also mentions usage of html and wiki pages. At the top of the page is states that this applies to Azure DevOps Services | TFS 2018 | TFS 2017 | TFS 2015, but wiki pages are not available in TFS 2017 and 2015. 

I've tried some of the guidance in markdown files in a git repository in TFS 2017 but most of it is not supported. Some of it isn't even supported in markdown files in a git repository in TFS 2018 or in the 2018 wiki. Try the :bowtie: emoji which is the first emoji listed on the page you reference: https://www.webpagefx.com/tools/emoji-cheat-sheet/ 

It's a complete guesswork for me trying to figure out what is supported in TFS 2017 and what is supported in TFS 2018. I can't even get the TOC to work in TFS 2018 and that version has a wiki. It does work in VSTS (no, I don't like the new name) though.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fa622358-f5bb-1f5c-177a-081a37b6acef
* Version Independent ID: 72f7fd16-a822-66c8-3a34-8905645ce5f2
* Content: [Syntax usage for Markdown files, widgets, wikis, and pull requests - Azure DevOps & TFS](https://docs.microsoft.com/en-us/azure/devops/project/wiki/markdown-guidance?view=vsts#mathematical-notation-and-characters)
* Content Source: [docs/project/wiki/markdown-guidance.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/project/wiki/markdown-guidance.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@MichaelHarmsen  - thank you for your feedback. I've made several updates to clarify what is supported for the different TFS versions. The TOC feature is only supported for Azure DevOps Services at this time.

**Comment by MichaelHarmsen** [comment]
I appreciate your effort but it's still not correct. TOC is described on this page as working for Wiki pages and not just on VSTS. Anchor links are described as working within Markdown files but that is not correct. It works in TFS 2018 but not in TFS 2017. In TFS 2017 (Update 2) clicking the link just reloads the page. I cannot imagine what works in TFS 2015 and what doesn't. In my opinion this page should be structured differently so it is clear what syntax is supported in which version (VSTS, TFS 2018, 2017, 2015) and where (markdown files, wiki, pull requests etc).
This page opens with the words "Having the right guidance at the right time is critical to success". I agree, but I'm not getting the right guidance here. I'm getting frustrated.
