### ISSUE TITLE
Difficult to find where to put in the icon for the Hub navbar

### ISSUE THREAD

**Issue by PerthCharern** [MicrosoftDocs/vsts-docs#1841]
It is very difficult to find on this page where to put our custom icon for the Hub Navbar.

I clicked on the "contributions" section, and it still doesn't go into enough details on how to add that icon. I can only find such information from a separate page https://docs.microsoft.com/en-us/azure/devops/extend/develop/web-navigation?view=vsts#hub-icon

This seems like a common thing to do for all Hub extensions, so it should be added to the Contributions section.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d8b703fe-8982-4284-6db0-ef33abac08a4
* Version Independent ID: 0fc84d11-1c32-0a49-04ec-641b68f44886
* Content: [Extension Manifest Reference](https://docs.microsoft.com/en-us/azure/devops/extend/develop/manifest?view=vsts#contributions)
* Content Source: [docs/extend/develop/manifest.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/extend/develop/manifest.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by elbatk** [comment]
Hi @PerthCharern , sorry for the abnormally long delay here, I'm adding this as I think you're correct, it would be helpful :)
