### ISSUE TITLE
Correction for item 4. Delete the TFS-PS category from mapped projects

### ISSUE THREAD

**Issue by JeffBarnard** [MicrosoftDocs/vsts-docs#1845]
I believe that step #3 should read
witadmin importcategories .. and not witadmin importglobalworkflow ..

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e88a42e6-8bd6-ac60-48ec-bf5cd7660334
* Version Independent ID: e924ea51-f257-42f5-c2d3-20e768922b3b
* Content: [Remove PS-TFS integration - TFS](https://docs.microsoft.com/en-us/azure/devops/reference/tfs-ps-sync/remove-tfs-ps-integration?view=tfs-2015)
* Content Source: [docs/reference/tfs-ps-sync/remove-tfs-ps-integration.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/reference/tfs-ps-sync/remove-tfs-ps-integration.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by JeffBarnard** [comment]
There is a related mistake in Item 5, the commands are swapped..

**Comment by KathrynEE** [comment]
@JeffBarnard - thank you for the correction. I am updating the topic accordingly.
