### ISSUE TITLE
Consigo criar regra para a coluna DUE DATE?

### ISSUE THREAD

**Issue by wtassi** [MicrosoftDocs/vsts-docs#1846]
Preciso criar uma regra para a coluna "Due Date" para preencher a mesma com a informação de:
"Created Date" + 45 dias úteis.
Alguém sabe me dizer se é possível?
Obrigado.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4107b23a-ba0a-5a1b-b689-072717cfe8ec
* Version Independent ID: 1ed09ce9-be9b-6146-9cb8-a2a50e12a3c2
* Content: [Add a custom rule to a work item type - Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/organizations/settings/work/custom-rules?view=vsts&tabs=new-nav)
* Content Source: [docs/organizations/settings/work/custom-rules.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/settings/work/custom-rules.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@wtassi - Thank you for your inquiry. The ability to create a custom rule - "Created Date" + 45 business days - is not supported. However, you may be able to do something using a REST API. 

Obrigado por sua pergunta. A capacidade de criar uma regra personalizada - "Data de criação" + 45 dias úteis - não é suportada. No entanto, você pode fazer algo usando uma API REST.
