### ISSUE TITLE
"##vso[task.logissue" syntax is not documented except on Powershell task page

### ISSUE THREAD

**Issue by escalonn** [MicrosoftDocs/vsts-docs#1847]
The `##vso` syntax in general is not documented in any one place, and in particular the useful `task.logissue` functionality is not documented except for the Powershell task.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a0e444c2-69c6-4d71-6fd0-94d0f4097d3a
* Version Independent ID: 3a727833-1cc3-c2fb-c5b3-22605eee2721
* Content: [PowerShell - Azure Pipelines & TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/powershell?view=vsts)
* Content Source: [docs/pipelines/tasks/utility/powershell.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/utility/powershell.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by andyjlewis** [comment]
@escalonn great point, and we've got it on the backlog to bolster logging command docs. I'm adding this issue to our user story to make sure we cover this concern. Also thanks for sharing your experience in using the logissue command in the Docker scenario. I'll forward the info to the feature team.
