### ISSUE TITLE
Copyedit issue

### ISSUE THREAD

**Issue by cleemullins** [MicrosoftDocs/vsts-docs#1848]
Your example shows: 
&gt;   When referring to Microsoft products, use full names in place of abbreviations.
&gt;   e.g. Azure DevOps Services vs. Azure DevOps Services.

Note that "Azure DevOps Services" is the same as "Azure DevOps Services". 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3d3bc9b6-7944-5d58-7ec8-156a5ed81cdc
* Version Independent ID: 8f466811-4c19-9d69-68a8-5b715cabb50e
* Content: [Package, publish, & unpublish extensions](https://docs.microsoft.com/en-us/azure/devops/extend/publish/overview?view=vsts)
* Content Source: [docs/extend/publish/overview.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/extend/publish/overview.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by elbatk** [comment]
Ah, the ol' find and replace error. Thanks @cleemullins , fixing now :)
