### ISSUE TITLE
Incorrect input name in PublishTestResults@2 YAML snippet

### ISSUE THREAD

**Issue by GavinOsborn** [MicrosoftDocs/vsts-docs#1849]
The [YAML snippet](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/test/publish-test-results?view=vsts&tabs=yaml#yaml-snippet) section refers to an input called `testResultsFormat` which should actually be `testRunner`.

The correct input name is used throughout the rest of the document.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba91e46a-de53-c0c1-f7f7-c02e797d527c
* Version Independent ID: 6f478148-461f-694a-ed82-deb4d731854e
* Content: [Azure Pipelines and TFS Build and Test - Publish Test Results task](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/test/publish-test-results?view=vsts&tabs=yaml)
* Content Source: [docs/pipelines/tasks/test/publish-test-results.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/test/publish-test-results.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment]
Thank you for your feedback. I have passed this on to the product team for advice.

**Comment by PBoraMSFT** [comment]
@GavinOsborn - testResultsFormat and testRunner are both valid. testResultsFormat is an alias for the input name and we think it's a better name since the results files can be produced by multiple runners and not just a specific runner. For e.g., jUnit results format is supported by many runners and not just junit.

**Comment by GavinOsborn** [comment]
Understood @PBoraMSFT - I'm not sure what happened - I discovered this "problem" trying to create my first build pipeline from the documentation. Either the platform was having a momentary hiccup or more likely my butter fingers made a mistake.

In any case, I wonder if the documentation should be consistent one way or the other?
The YAML snippet is the only reference on the page that refers to the input by its alias - everything else refers to that input by its original name.
