### ISSUE TITLE
VIsual Designer 

### ISSUE THREAD

**Issue by Pachehra** [MicrosoftDocs/vsts-docs#1851]
Please check at the beginning - Add a script to Azure Repos and when i do that its totally different on Azure Devops then i saw the picture below which already have a Smart Hotel 360 and then adding PS file.

Please go step by Step else its total time waste to figure out what is happening for the newbies 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 02b747eb-53c2-dd5f-cd2b-f337c15e0864
* Version Independent ID: 04538505-00cd-33ac-8008-4b85cca089e3
* Content: [Use the visual designer to create a CI/CD pipeline - Azure Pipelines & TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/get-started-designer?view=vsts&tabs=new-nav)
* Content Source: [docs/pipelines/get-started-designer.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/get-started-designer.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by elbatk** [comment]
Hi @Pachehra, which screen are you seeing in this scenario? The initial Azure Repos wizard that gives you a couple of options for cloning your repo, importing one, or initializing one?

**Comment by elbatk** [comment]
Hi @Pachehra, we added a step that includes initializing your repository if you haven't yet, that should help :)
