### ISSUE TITLE
equivalent of TRAVIS_PULL_REQUEST_SHA

### ISSUE THREAD

**Issue by wmhilton** [MicrosoftDocs/vsts-docs#1853]
If you need the commit id for Github's commit status API, you can use the following command:
```bash
TRAVIS_PULL_REQUEST_SHA=$(git log --pretty=%P -n 1 | awk '{print $NF}')
```

Explanation: There does not appear to be an environment variable that exposes the git commit id in the PR branch that triggered a build. (BUILD_SOURCEVERSION corresponds to the _merge_ commit between the PR source branch and PR destination branch.) But since this is a merge commit, we can use git log to get the parents of the merge. The first parent will be the destination branch of the PR so we ignore that and grab the second (or last) parent which should be the source branch of the PR.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ffebdc8-521c-44b5-cde4-4abdc1bd6f18
* Version Independent ID: dc0effda-6d93-62aa-64c5-4e6f283b0826
* Content: [Predefined build variables - Azure Pipelines & TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=vsts)
* Content Source: [docs/pipelines/build/variables.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/build/variables.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by vtbassmatt** [comment]
Maybe I'm missing something - can't you do the same thing here? I was playing around with the `git log` one-liner you offered, and I get my source branch as the second commit as well.
