### ISSUE TITLE
incorrect information ? 

### ISSUE THREAD

**Issue by sqlenders** [MicrosoftDocs/vsts-docs#1854]
Perhaps the screenshots are wrong 
Expected : Microsoft Hosted Job should be increased. 
Actuel : Self-Hosted was increased. 

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: 7734edca-173b-ba47-bf1b-3c19f9bd93e1
* Version Independent ID: d6ea8680-546e-f102-fd55-b35af33a6aa5
* Content: [Buy CI/CD in Azure DevOps Services](https://docs.microsoft.com/nl-nl/azure/devops/organizations/billing/buy-more-build-vs?view=vsts)
* Content Source: [docs/organizations/billing/buy-more-build-vs.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/billing/buy-more-build-vs.md)
* Product: **devops**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @sqlenders thank you for your feedback. I've created a work item to better clarify that the screen shots are showing as an example of Microsoft-hosted. The first step tells you to select between Microsoft-hosted or Self-hosted. Although the process for both is the same, I'll explain that the screenshots only show an example of the Microsoft-hosted workflow. Thanks again.
