### ISSUE TITLE
 Link to "old work item form tag has been deprecated"

### ISSUE THREAD

**Issue by Bazul99** [MicrosoftDocs/vsts-docs#1856]
The link to " old work item form tag has been deprecated"
Here:
https://devblogs.microsoft.com/devops/2017/05/22/announcing-the-deprecation-of-the-old-work-item-form-in-tfs/
Has also apparently been depricated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 86f8d3c8-b8e5-0b66-1d79-5a75c59f5ddb
* Version Independent ID: 683882d0-c1b2-685f-aa20-5ac652c33a64
* Content: [Upgrade your TFS deployment](https://docs.microsoft.com/en-us/tfs/server/upgrade/get-started?view=vsts)
* Content Source: [docs/server/upgrade/get-started.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/server/upgrade/get-started.md)
* Product: **devops-server**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by ClydeDz** [comment]
@Bazul99 @elbatk The new link to the blog article can be found [here](https://blogs.msdn.microsoft.com/devops/2017/05/22/announcing-the-deprecation-of-the-old-work-item-form-in-tfs/).

Interestingly, the edit button is missing on this page, so I'm guessing can be edited by internal staff only?

![image](https://user-images.githubusercontent.com/13506613/46255806-6b8dea00-c4fe-11e8-8cda-21ceb5efef3d.png)

**Comment by msebolt** [comment]
@elbatk This issue was fixed in the latest Azure DevOps update.  You can now close the issue.

**Comment by elbatk** [comment]
Good to hear! Thanks @msebolt
