### ISSUE TITLE
new build pipeline documentation 

### ISSUE THREAD

**Issue by kgreed** [MicrosoftDocs/vsts-docs#1858]
I am not experiencing the same screens when I open new build pipeline. 
Instead I get a wizard "build your code in a few easy steps "  1 Location 2 Repository 3 Template 4 Save and Run

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 02b747eb-53c2-dd5f-cd2b-f337c15e0864
* Version Independent ID: 04538505-00cd-33ac-8008-4b85cca089e3
* Content: [Use the visual designer to create a CI/CD pipeline - Azure Pipelines & TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/get-started-designer?view=vsts&tabs=new-nav)
* Content Source: [docs/pipelines/get-started-designer.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/get-started-designer.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by elbatk** [comment]
This should be fixed, @kgreed . I believe it was taking you to the new YAML pipeline wizard, there is a preview feature that you can turn off to create a pipeline using the visual designer. You can find more about it in the [Create your pipeline section of the get started designer guide](https://docs.microsoft.com/en-us/azure/devops/pipelines/get-started-designer?view=vsts&tabs=new-nav#create-a-build-pipeline).
