### ISSUE TITLE
New Navigation

### ISSUE THREAD

**Issue by GingerBr** [MicrosoftDocs/vsts-docs#1859]
How do you get to the Recycle Bin in the new navigation?  This documentation needs to be updated.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e9f02cb-f094-d6bc-ca7b-973db9de0082
* Version Independent ID: 1af6a7f5-9e99-ec99-081d-c0bf9e7ac5f5
* Content: [Move, change, or delete work items - Azure Boards and TFS](https://docs.microsoft.com/en-gb/azure/devops/boards/backlogs/remove-delete-work-items?toc=%2Fazure%2Fdevops%2Fboards%2Fbacklogs%2Ftoc.json&bc=%2Fazure%2Fdevops%2Fboards%2Fbacklogs%2Fbreadcrumb%2Ftoc.json&view=vsts&tabs=browser#restore-or-permanently-delete-work-items)
* Content Source: [docs/boards/backlogs/remove-delete-work-items.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/boards/backlogs/remove-delete-work-items.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@GingerBr - Thank you for the feedback. You are correct that the article needs updating. 
With New Navigation turned on, you reach the recycle bin from the Work Items page: 

![image](https://user-images.githubusercontent.com/10856840/46111004-47e34080-c19a-11e8-8b58-3f2773c4a11f.png)

I will update the topic.
