### ISSUE TITLE
missing item

### ISSUE THREAD

**Issue by joeruder** [MicrosoftDocs/vsts-docs#1860]
Under 'How many iterations should a team provide' it states "In the following example, Backlog,..."
There is no item 'Backlog' in the provided picture.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b52fb8a5-d949-dbe6-7e3f-56ac61984e8a
* Version Independent ID: 5e1aeb8b-35bd-8c40-769c-fdac56768b0d
* Content: [How are area and iteration paths used? - Azure DevOps & TFS](https://docs.microsoft.com/en-us/azure/devops/organizations/settings/about-areas-iterations?view=vsts)
* Content Source: [docs/organizations/settings/about-areas-iterations.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/settings/about-areas-iterations.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@joeruder - Thank you for the correction. I'll update the topic accordingly.
