### ISSUE TITLE
[[_TOC_]] doesn't seem to work

### ISSUE THREAD

**Issue by Sniipe** [MicrosoftDocs/vsts-docs#1861]
I have a page like the following
[[_TOC_]]
#Chapter 1
blah
#Chapter 2
blah
##Chapter 2.1
blah

I don't get a table of contents instead I get [[_TOC_]] in italics

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fa622358-f5bb-1f5c-177a-081a37b6acef
* Version Independent ID: 72f7fd16-a822-66c8-3a34-8905645ce5f2
* Content: [Markdown syntax for files, widgets, wikis - Azure DevOps & TFS](https://docs.microsoft.com/en-us/azure/devops/project/wiki/markdown-guidance?view=vsts)
* Content Source: [docs/project/wiki/markdown-guidance.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/project/wiki/markdown-guidance.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@Sniipe - Please look at changing the [[TOC]] to [[_TOC_]], and use at least 33 for the headings. 

I found this worked - Azure DevOps Services only for now: 

[[_TOC_]]

## Chapter 1
blah
## Chapter 2
blah
### Chapter 2.1
blah

**Comment by Sniipe** [comment]
I am using TFS 2018, would that not work?  Could that by my issue?

**Comment by CSharkey145** [comment]
This is not working for me as well.

Am I working in: 
Microsoft Visual Studio Team Foundation Server
Version 16.131.27701.1
