### ISSUE TITLE
Powershell gallery as upstream source in package

### ISSUE THREAD

**Issue by gregoirefra** [MicrosoftDocs/vsts-docs#1863]
Do we have an ETA on when it will be possible to add custom upstream source to package or if the powershell gallery will be offered as an upstream source? This is a deal breaker for my team right now as package we develop and work with leverages some from the powershell gallery and makes it much more complicated for us to install the external dependencies instead of having them upstreamed.

**Comment by alexmullans** [comment]
I don't have an ETA to share at the moment. Support for the PowerShell gallery as an upstream will come as part of [this work](https://visualstudio.uservoice.com/forums/330519-azure-devops-formerly-visual-studio-team-services/suggestions/17505808-add-powershellget-support-for-packagemanagement).

**Comment by alexmullans** [comment]
Closing this docs issue. Please feel free to vote on [this Developer Community suggestion](https://developercommunity.visualstudio.com/content/idea/365613/add-powershellget-support-for-packagemanagement.html) for PowerShell support.
