### ISSUE TITLE
Definition Gets Prefixed with Nuget_

### ISSUE THREAD

**Issue by lifesoccult** [MicrosoftDocs/vsts-docs#1864]
Trying to use this task to download a jar from the universal package repo and this task is prefixing the definition with `Nuget_`. I'm guessing this does not support universal packages yet; can this be confirmed please?

Thanks,

Jonathan

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ff8354ee-807f-0c1f-8e5b-9303c4591c60
* Version Independent ID: 1fd42523-8504-76cf-deec-26c5fccd0109
* Content: [Download Package](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/download-package?view=vsts)
* Content Source: [docs/pipelines/tasks/utility/download-package.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/utility/download-package.md)
* Product: **devops**
* GitHub Login: @erickson-doug
* Microsoft Alias: **dastahel**

**Comment by 24mu13** [comment]
Right, but this *Download Package task* is the same used by Release pipeline. So is impossible to bind a release-pipeline to an Universal package!

**Comment by alexmullans** [comment]
That's correct. It's not currently possible to use Universal Packages as Artifacts in a release pipeline. We're adding that support this quarter. @elbatk for now can we add a note to this doc specifying that the task currently only works with NuGet packages.

**Comment by elbatk** [comment]
Thanks @alexmullans , adding the note and closing this issue for now.
