### ISSUE TITLE
invalid link

### ISSUE THREAD

**Issue by jgillette** [MicrosoftDocs/vsts-docs#1865]
The link for GitStatusState above (#9 in this section https://docs.microsoft.com/en-us/azure/devops/repos/git/create-pr-status-server?view=tfs-2018#post-status-to-prs) is no longer valid. 

It should now point to 
https://docs.microsoft.com/en-us/rest/api/vsts/git/pull%20request%20statuses/get?view=vsts-rest-4.1#gitstatusstate

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e8f48d8a-33fb-9f6d-1db1-4cccb5b987d9
* Version Independent ID: 3e18fcbf-331d-9de2-62ae-c4e7c888cc48
* Content: [Create a pull request status server with Node.js - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/create-pr-status-server?view=tfs-2018#post-status-to-prs)
* Content Source: [docs/repos/git/create-pr-status-server.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/repos/git/create-pr-status-server.md)
* Product: **devops**
* GitHub Login: @mmitrik
* Microsoft Alias: **mmitrik**

**Comment by steved0x** [comment]
@jgillette Thanks for letting us know, I have merged the related PR to fix this.
