### ISSUE TITLE
Some endpoint URLs are incorrect

### ISSUE THREAD

**Issue by sobjornstad** [MicrosoftDocs/vsts-docs#1870]
In several places on this page, the base form of the URL is listed as something like the following:

    GET https://{instance}/DefaultCollection/{project}/_apis/repos/git/repositories/{repository}?api-version={version}

But this URL always yields 404. The URLs in the sample requests leave out the `repos` between `_apis` and `git`, and those URLs actually work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 37d86d41-50bf-d9a1-ab53-00a50ec0414b
* Version Independent ID: 5beec633-c108-c9bf-400a-e5fb2ec55c99
* Content: [Git Repositories](https://docs.microsoft.com/en-us/azure/devops/integrate/previous-apis/git/repositories?view=tfs-2018)
* Content Source: [docs/integrate/previous-apis/git/repositories.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/integrate/previous-apis/git/repositories.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by elbatk** [comment]
Hi @sobjornstad , which version of the APIs are you using? These pages are for older APIs (version 1), the newer APIs don't use that `repos` bit. If Version 1 is failing, then we'll need to make a change.

**Comment by sobjornstad** [comment]
I'm pretty sure I specified version 1, but I'll double-check on Monday when I can look at the code again.

**Comment by sobjornstad** [comment]
Confirmed, this is not working on API version 1.0 (against TFS 2018 R3).

```
PS> iwr -Uri 'http://tfs-prod:8080/tfs/myCollection/myProject/_apis/repos/git/repositories?api-version=1.0' -UseDefaultCredentials
iwr : Error
The page you are looking for is currently unavailable.
Page not found.
 More information about this error
Page not found.
Things you can try:
Refresh the current page
Go back to the previous page
Sign in as a different user
Submit feedback to Microsoft about this error
Microsoft Visual Studio Team Foundation Server
© Microsoft Corporation. All rights reserved.
At line:1 char:1
+ iwr -Uri 'http://tfs-prod:8080/tfs/myCollection/myProject ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebExc
   eption
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand
```

```
PS> iwr -Uri 'http://tfs-prod:8080/tfs/myCollection/myProject/_apis/git/repositories?api-version=1.0' -UseDefaultCredentials

StatusCode        : 200
StatusDescription : OK
Content           : {"value":[{"id":"e2e9ef71-fd8d-4af1-84b7-007118090c97","name":"polproc_vb_clientapp_Scheduler","url
                    ":"http://tfs-prod:8080/tfs/myCollection/_apis/git/repositories/e2e9ef71-fd8d-4af1-84b7-0
                    07...
[...]
```

**Comment by chcomley** [comment]
Hi @sobjornstad, since this issue is also crossreferenced in #3091, I'm closing this issue and we'll address it in 3091. Thanks!
