### ISSUE TITLE
Missing documentation for users with different email addresses

### ISSUE THREAD

**Issue by davisnw** [MicrosoftDocs/vsts-docs#1871]
According to https://blogs.msdn.microsoft.com/devops/2018/03/28/deadline-extended-for-connecting-vsts-accounts-to-azuread/, we will no longer be able to create MSA accounts with address domains backed by an AzureAD.  That is in 5 days.

This documentation says "We will update this guidance when we have a solution for scenarios where email addresses must be changed."

I am in this situation, but this documentation gives no path forward.  Either I continue to use MSA and am not able to use our company addresses for new users, or I join to the Azure AD, and half my users no longer have their accounts properly migrated to the organizational accounts.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 031380a0-4f04-4105-199a-81715b42c653
* Version Independent ID: 570b2795-90ad-32b4-7ad0-1fceb186ffa3
* Content: [Connect your Azure DevOps organization to Azure Active Directory (Azure AD)](https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/connect-organization-to-azure-ad?view=vsts&tabs=new-nav)
* Content Source: [docs/organizations/accounts/connect-organization-to-azure-ad.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/accounts/connect-organization-to-azure-ad.md)
* Product: **devops**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Thank you for your comment, @davisnw. We are preparing for said update. In the meantime, for more information and guidance, please contact Justin.Marks@microsoft.com. Thanks again.
