### ISSUE TITLE
Why cannot have Release.Artifacts.{Primary artifact alias}.RequestedForEmail

### ISSUE THREAD

**Issue by wood1986** [MicrosoftDocs/vsts-docs#1873]
As you have `Release.Artifacts.{Primary artifact alias}.RequestedFor`, having `Release.Artifacts.{Primary artifact alias}.RequestedForEmail` should not be a problem.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 611642f0-881f-10b9-ae94-3c562001d1f0
* Version Independent ID: 41efb94b-4c7a-64a3-b23b-70c8634ae727
* Content: [Variables in Release Management](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/variables?view=vsts&tabs=batch)
* Content Source: [docs/pipelines/release/variables.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/release/variables.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by wood1986** [comment]
As you have `Release.Artifacts.{Primary artifact alias}.RequestedFor`, having `Release.Artifacts.{Primary artifact alias}.RequestedForEmail` should not be a problem?

**Comment by alexhomer1** [comment]
Thank you for your feedback. Product suggestions and feature requests are best posted and upvoted on the UserVoice website at https://visualstudio.uservoice.com/forums/330519-team-services, where they are tracked by the product teams. Please post your suggestion there. Thank you.
