### ISSUE TITLE
new REST APIs has a  link which is broken

### ISSUE THREAD

**Issue by ranjan-ranjan** [MicrosoftDocs/vsts-docs#1874]
new REST APIs has a  link which is broken
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 413163f0-28c3-a2a7-d626-fcb81bcb2257
* Version Independent ID: 57c127da-2b1e-d29e-9abb-a3c258762ccf
* Content: [.NET Client Libraries for Azure DevOps Services (and TFS)](https://docs.microsoft.com/en-us/azure/devops/integrate/concepts/dotnet-client-libraries?view=vsts)
* Content Source: [docs/integrate/concepts/dotnet-client-libraries.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/integrate/concepts/dotnet-client-libraries.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by ClydeDz** [comment]
@ranjan-ranjan @elbatk, this is interesting. PR #1283 by @eriawan should have fixed this.

If you [click the .md content source file](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/integrate/concepts/dotnet-client-libraries.md), it shows you the correct link. 
![image](https://user-images.githubusercontent.com/13506613/46256092-84000380-c502-11e8-8b51-5ad3813e010b.png)

But on the live page it still shows the old link, hence this issue.
![image](https://user-images.githubusercontent.com/13506613/46256089-7fd3e600-c502-11e8-892c-616dcc1e74e9.png)

Any thoughts?

**Comment by elbatk** [comment]
It's been a while, but I've fixed this issue! :)

**Comment by chcomley** [comment]
I've just completed a PR, fixing this link, which should go live sometime this morning. Until then, here's the [link](https://docs.microsoft.com/en-us/rest/api/azure/devops/?view=azure-devops-rest-5.0).
