### ISSUE TITLE
New navigation, markup is showing

### ISSUE THREAD

**Issue by jspijkerboer** [MicrosoftDocs/vsts-docs#1875]
On step number 4 of adding the user, it shows [!div class="mx-imgBorder"] left of the image. This shows on the New navigation tab.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b6db4fba-7322-16bc-3431-6b8f933a84bf
* Version Independent ID: a20bd1b0-06d7-8f49-30d2-25c5e188b674
* Content: [Add external users to your organization](https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/add-external-user?view=vsts&tabs=new-nav)
* Content Source: [docs/organizations/accounts/add-external-user.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/accounts/add-external-user.md)
* Product: **devops**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Thanks for the heads up, @jspijkerboer. I've updated the doc, so the fix should be live this afternoon. Thanks again for helping to make our documentation better for everyone.
