### ISSUE TITLE
Disable builds on new tags

### ISSUE THREAD

**Issue by michael-wolfenden** [MicrosoftDocs/vsts-docs#1876]
After a successful release, my workflow creates a new github release tagged with the current release number.  This creates  a tag which triggers a new azure pipeline build.

Is there a way to disable builds on new tags?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5673ec1-c7d1-e0ac-043a-8fc3d5b226a9
* Version Independent ID: b4872831-51c0-6cf8-1c56-de20beb38a80
* Content: [Build pipeline triggers - Azure Pipelines & TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/triggers?view=vsts&tabs=yaml)
* Content Source: [docs/pipelines/build/triggers.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/build/triggers.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by vijayma** [comment]
If you are using YAML, you can use the trigger node and branch inclusion to control that. If you are using designer, you can include or exclude specific branches. Use refs/tags/* as the syntax for the branch name to refer to tags.
