### ISSUE TITLE
Download artifact from PartiallySucceeded builds

### ISSUE THREAD

**Issue by Thilas** [MicrosoftDocs/vsts-docs#1882]
Currently, this task only allows to download artifacts from `Succeeded` builds, it does not consider artifacts of `PartiallySucceeded` builds. It would be nice to have the choice here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c0a16bcf-af6c-e278-f0a6-8ec95012ce4a
* Version Independent ID: ae442106-33b3-786f-2158-34eed3fed6e0
* Content: [Download Build Artifacts](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/download-build-artifacts?view=vsts)
* Content Source: [docs/pipelines/tasks/utility/download-build-artifacts.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/utility/download-build-artifacts.md)
* Product: **devops**
* GitHub Login: @erickson-doug
* Microsoft Alias: **dastahel**

**Comment by omeshp** [comment]
This is a tasks issue please raise it at https://github.com/Microsoft/vsts-tasks/

Also, it should be relatively easy to add this support the code is at https://github.com/Microsoft/vsts-tasks/blob/f8c47dff2d23be002ce9d093fc32ddde6e6520e0/Tasks/DownloadBuildArtifactsV0/main.ts#L173

**Comment by Thilas** [comment]
Ok, will do. Thanks!
