### ISSUE TITLE
Azure DevOps Services Plugin for Android Studio

### ISSUE THREAD

**Issue by SrivatsaMarichi** [MicrosoftDocs/vsts-docs#1883]
There is no plugin by the name **Azure DevOps Services**. So the plugin available to connect to **VSTS/TFS** is **VSTS**. Since the name is misleading, people are confused as to which plugin to be installed. 

### When searched for Azure DevOps Services

![vsts](https://user-images.githubusercontent.com/13433045/46128911-a8ce4f80-c252-11e8-9b3e-707bde87f5af.png)

### When searched for VSTS

![vsts1](https://user-images.githubusercontent.com/13433045/46128958-d3b8a380-c252-11e8-98ae-14b72897b7c7.png)

When I try to download the latest plugin (1.150.0) from [jetbrains](http://plugins.jetbrains.com/plugin/7981-visual-studio-team-services) site, the plugin downloads the version 1.147.0 which is incorrect. Would be great help if the link is fixed too :-)

PFA recorded clip for the same.

[vstspluginerror.zip](https://github.com/MicrosoftDocs/vsts-docs/files/2422913/vstspluginerror.zip)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3378875f-5f9d-8992-a01d-8ea87e019861
* Version Independent ID: b098532e-61ee-0906-8b50-9108e50e2732
* Content: [Get the Android Studio Azure DevOps Services plug-in](https://docs.microsoft.com/en-us/azure/devops/java/download-android-studio-plug-in?view=vsts)
* Content Source: [docs/java/download-android-studio-plug-in.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/java/download-android-studio-plug-in.md)
* Product: **devops**
* GitHub Login: @erickson-doug
* Microsoft Alias: **douge**

**Comment by SrivatsaMarichi** [comment]
No help yet.

**Comment by IbrahimElshafey** [comment]
* Scroll down in this page [https://plugins.jetbrains.com/plugin/7981-visual-studio-team-services]
* Find the download section and download the latest version of the plugin
* In Settings>Plugins Dialog there is a button in the bottom with a text 'Install plugin from disk'
* Click the button > select the .zip file you downloaded > Now you are done :)
