### ISSUE TITLE
Subscriptions REST APIs link is broken

### ISSUE THREAD

**Issue by shaboinkin** [MicrosoftDocs/vsts-docs#1884]
https://visualstudio.microsoft.com/en-us/docs/integrate/api/hooks/subscriptions leads to page not found error. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 571ca92c-4252-2138-6899-8477f4d5dcf3
* Version Independent ID: 6a5fc398-1799-df19-d6c0-987491108fa4
* Content: [Service hooks in Azure DevOps Services REST APIs](https://docs.microsoft.com/en-us/azure/devops/integrate/concepts/service-hooks?view=vsts#feedback)
* Content Source: [docs/integrate/concepts/service-hooks.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/integrate/concepts/service-hooks.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by patrick-ryan1** [comment]
Still broken
