### ISSUE TITLE
How to change the value of State with custom rule?

### ISSUE THREAD

**Issue by ralucapredacegeka** [MicrosoftDocs/vsts-docs#1885]
I want to change the State of a test case when the Automation Status changes to Automated.

**Comment by alexhomer1** [comment]
Thank you for your feedback. I have passed this on to the product team for advice.

**Comment by PBoraMSFT** [comment]
@harishkragarwal - is there anything we can recommend here?

**Comment by harishkragarwal** [comment]
@ralucapredacegeka: what should the State change to in your opinion?

**Comment by ralucapredacegeka** [comment]
We added a new State for the test case: Automated and we want to change to it. The reason we added the Automated state was to make the steps and parameters read only when a test case is automated.

Basically, I just want to add a custom rule where the State of an item changes based on a condition.

**Comment by harishkragarwal** [comment]
Work item customization (as described at https://docs.microsoft.com/en-us/azure/devops/organizations/settings/work/customize-process-workflow?view=vsts&tabs=new-nav and it sibling pages) is what you can possibly consider for this. Apart from that no other suggestion here. 

Thanks. And hoping above helps.
