### ISSUE TITLE
Last sentence reads incorrectly

### ISSUE THREAD

**Issue by kimbleyGriffin** [MicrosoftDocs/vsts-docs#1887]
<b>Easily track results</b>
A key principle of good user acceptance testing practice is to minimize the effort required to determine whether a requirement has been achieved. There are two ways this can be achieved, you can focus on individual test runs and tests to see which failed or use the charts views make it much easy and accessible to all members of Azure DevOps makes this much easier. 

*This last sentence reads incorrectly.  PLEASE CONSIDER CHANGING IT TO...*
There are two ways this can be achieved, you can focus on individual test runs and tests <b>-- to see which failed, or use the charts views -- to make it much easier and accessible to all members of Azure DevOps.</b>

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43dea7da-3f9e-5053-d35c-9c0450b8a2cf
* Version Independent ID: 08ba2e82-fa28-6559-7a57-b582eef9313d
* Content: [User acceptance testing - manual testing in Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/test/user-acceptance-testing?view=vsts)
* Content Source: [docs/test/user-acceptance-testing.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/test/user-acceptance-testing.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment]
Thank you for your feedback. I will update the topic to include your recommendations.

**Comment by kimbleyGriffin** [comment]
Groovy!  De nada.
