### ISSUE TITLE
Details on file locking

### ISSUE THREAD

**Issue by Stevie-DeLaCruz** [MicrosoftDocs/vsts-docs#1889]
Planning on using this task for a big file transfer that we need to execute, couldn't find anything in docs confirming if files are locked during the process.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 81f02378-b85b-d3a4-d3c8-f07d935367da
* Version Independent ID: fab57f76-35d2-4024-6f7f-1740d7b24743
* Content: [Copy Files - Azure Pipelines & TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/copy-files?view=vsts)
* Content Source: [docs/pipelines/tasks/utility/copy-files.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/utility/copy-files.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by vtbassmatt** [comment]
The Copy Files task [calls `tl.cp`](https://github.com/Microsoft/vsts-tasks/blob/f8c47dff2d23be002ce9d093fc32ddde6e6520e0/Tasks/CopyFilesV2/copyfiles.ts#L134) where `tl` is our task library. [That](https://github.com/Microsoft/vsts-task-lib/blob/d61bacb057170af734a8b73eb217b359a9ab8f8b/node/task.ts#L686) in turn calls [shelljs's cp](https://github.com/shelljs/shelljs/blob/master/src/cp.js) method, which doesn't appear to do any locking.
