### ISSUE TITLE
Support for Java 11 in gradle builds.

### ISSUE THREAD

**Issue by ThadHouse** [MicrosoftDocs/vsts-docs#1893]
Now that the default build agents have Java 11 installed on then, jdk version 11 should be available to Gradle builds with the `jdkVersionOption` property.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 00499395-fdc3-b150-3469-aee2f9fb7cbc
* Version Independent ID: 44e630e1-1689-2d2e-212b-3ce2baf8771f
* Content: [Gradle build and release task](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/gradle?view=vsts)
* Content Source: [docs/pipelines/tasks/build/gradle.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/build/gradle.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by DavidStaheli** [comment]
@ThadHouse, thanks a lot for creating this issue.  It has been fixed through [this PR](https://github.com/Microsoft/azure-pipelines-tasks/pull/8716).
