### ISSUE TITLE
"Where can I learn about batch files?" can't be found

### ISSUE THREAD

**Issue by buzzfrog** [MicrosoftDocs/vsts-docs#1894]
The link doesn't go to a page

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 96dafbb6-b4ba-d4ab-7468-55e6df71b5e1
* Version Independent ID: 634b0719-9641-59fd-9f6f-f3a2082f9b39
* Content: [Batch script - Azure Pipelines & TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/batch-script?view=vsts)
* Content Source: [docs/pipelines/tasks/utility/batch-script.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/utility/batch-script.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by andyjlewis** [comment]
Thanks for the heads up. PRs to internal branches are in process and the fix should be published soon.
