### ISSUE TITLE
You can move work items to another project?

### ISSUE THREAD

**Issue by MichaelHarmsen** [MicrosoftDocs/vsts-docs#1897]
Under the headline "Features stakeholders can't access" this page states that stakeholders can't "move work items to another project". To my knowledge nobody can move work items to another project in TFS 2017. If I am correct this line could mislead someone to think that another access level includes this feature.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8db47b85-e178-7969-40d3-3fa83aa3fb54
* Version Independent ID: a78e453b-4b8f-c885-42ee-8a9d9979f345
* Content: [What access levels are supported? - Azure DevOps & TFS](https://docs.microsoft.com/en-us/azure/devops/organizations/security/access-levels?view=tfs-2017)
* Content Source: [docs/organizations/security/access-levels.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/security/access-levels.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@MichaelHarmsen - Thank you for the correction. I'm updating the topic now.
