### ISSUE TITLE
Add resize images support in markdown displayed in dashboards

### ISSUE THREAD

**Issue by pmiossec** [MicrosoftDocs/vsts-docs#1899]
Disclamer: perhaps not the right place to open the issue but finding the good place to report issue and bugs in VSTS is not easy...

You could read from: https://docs.microsoft.com/en-us/azure/devops/project/wiki/markdown-guidance?view=vsts#images

>Note
>The syntax to support image resizing is only supported in pull requests and the Wiki.

Please add support for resize images support in markdown displayed in dashboards displayed in VSTS/Azure Devops.

There is not a lot of places in widget and displaying images features in markdown is useless if we can't resize it.

**Comment by evangeline-liu** [comment]
Hi Philippe! Thanks for your feedback. We are closing this issue as it does not specifically relate to our docs. However, please feel free to suggest the feature here: https://developercommunity.visualstudio.com/content/idea/post.html?space=21.
