### ISSUE TITLE
basic navigation?

### ISSUE THREAD

**Issue by ieain** [MicrosoftDocs/vsts-docs#1900]
Nowhere on this page does it say where to find "Utility: Publish Build Artifacts" in Azure Pipelines.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c028a99-45f1-3609-3219-89789dc6b966
* Version Independent ID: f626f40e-1bab-4d8a-cd19-ab3b5da4be0a
* Content: [Artifacts in Azure Pipelines - Azure Pipelines & TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/artifacts?view=vsts)
* Content Source: [docs/pipelines/build/artifacts.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/build/artifacts.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by ociata** [comment]
Same here, maybe there is a change in the UI.

**Comment by elbatk** [comment]
Hi @ieain and @ociata, I agree this doc really doesn't explain the visual designer tasks and where to find them/configure them very well, I'm working on an update that should answer this question. For now, you can check out the [visual designer quickstart](https://docs.microsoft.com/en-us/azure/devops/pipelines/get-started-designer?view=vsts&tabs=new-nav) to learn more about how to configure pipelines and publishing artifacts with the UI.
