### ISSUE TITLE
First Time Push

### ISSUE THREAD

**Issue by jmclamb** [MicrosoftDocs/vsts-docs#1904]
I am trying to push a first time commit.
I get the message as described above about "current branch does not track....."
I then pressed the PUSH button under Outgoing Commits, but it still fails with the same error.

Any ideas?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6d5ca6b5-523a-21d0-26f3-567846f7c298
* Version Independent ID: c712c338-46d6-a70a-0ba1-0d1ec3cd6ac7
* Content: [Sync your changes to a remote Git repo - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/pushing?view=vsts&tabs=visual-studio)
* Content Source: [docs/repos/git/pushing.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/repos/git/pushing.md)
* Product: **devops**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by Aquastorm** [comment]
Hello jmclamb
You first need to commit your changes to your local repository and then you will be able to push your changes to the remote one.

**Comment by proficad** [comment]
Pushing master
Error: cannot spawn /c/program files (x86)/microsoft visual studio/2017/community/common7/ide/commonextensions/microsoft/teamfoundation/team explorer/Git/mingw32/libexec/git-core/git-askpass.exe: No such file or directory
Error encountered while pushing branch to the remote repository: Git failed with a fatal error.

**Comment by greatjos** [comment]
Hi, when I try to push it tells me to sign in, but when I put my credentials it keeps saying it failed even though the credential is right. This is my first push

**Comment by greatjos** [comment]
nvm, I needed to create a git credential
