### ISSUE TITLE
Pricing

### ISSUE THREAD

**Issue by koengillissen** [MicrosoftDocs/vsts-docs#1906]
Hello, our organization has a basic level Azure DevOps subscription which includes 5 free basic users. We bought 20 extra basic users. At this moment our subscription is not connected to a directory. We do have an Office 365 subscription as well and are considering to restrict access to Azure DevOps with Azure Active Directory. Does this have impact on our current Azure DevOps licenses? Kind regards,
Koen

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 39c81ce4-7085-f5cd-e29a-e434074d449a
* Version Independent ID: e9bbaf41-404e-d1b7-5e39-33b68ffe7ef0
* Content: [Azure DevOps Services access with Azure AD groups](https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/manage-azure-active-directory-groups?view=vsts&tabs=new-nav)
* Content Source: [docs/organizations/accounts/manage-azure-active-directory-groups.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/accounts/manage-azure-active-directory-groups.md)
* Product: **devops**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
@koengillissen thank you for your comment. I am looking into this and will be in touch. Thanks again.

**Comment by chcomley** [comment]
@koengillissen please go here for a live chat option: https://visualstudio.microsoft.com/vs/support/#talktous. Scroll to the bottom of the page and choose **Account, Subscription, and Billing Support**, select your country from the dropdown menu, and then choose **Live chat (English)**. Thank you.
