### ISSUE TITLE
npm version

### ISSUE THREAD

**Issue by trajano** [MicrosoftDocs/vsts-docs#1908]
This needs to expand to indicate how to do the `npm version` with VSTS

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d4cb48a1-d0bf-40b7-4645-910d4006fee9
* Version Independent ID: 9bddd101-2bc2-f65c-6a12-e395b76a2b98
* Content: [Publishing npm packages](https://docs.microsoft.com/en-us/azure/devops/pipelines/targets/npm?view=vsts&tabs=yaml)
* Content Source: [docs/pipelines/targets/npm.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/targets/npm.md)
* Product: **devops**
* GitHub Login: @erickson-doug
* Microsoft Alias: **amullans**

**Comment by alexmullans** [comment]
Unfortunately it's not feasible to use `npm version` in Azure Pipelines, since it relies on updating the version number in your source code. Your Pipeline would need to check in that updated version number at the end of the build, which is generally not recommended.

**Comment by trajano** [comment]
Is there another approach where we only build when there is a "TAG" not just by branch.

**Comment by alexmullans** [comment]
I'm not sure I follow. You might try asking your question on [StackOverflow](https://stackoverflow.com/questions/tagged/azure-devops) using the azure-devops tag - this site is for specific docs issues.

**Comment by StudioSpindle** [comment]
Added a similar question as @trajano on https://stackoverflow.com/questions/52702569/run-a-task-only-if-a-tag-is-present-in-the-commit-message as @alexmullans points out.

**Comment by trajano** [comment]
@StudioSpindle you may want to close your question.... I already asked and answered https://stackoverflow.com/questions/52601259/how-do-we-trigger-a-build-only-for-tags-matching-a-pattern/52611471#52611471

Also closing this for now as I found the workaround.
