### ISSUE TITLE
retain last Shared Steps Query setting

### ISSUE THREAD

**Issue by Abutu** [MicrosoftDocs/vsts-docs#1916]
"INSERT SHARED STEPS" default query is different for some of our users in the same project. Is there a way to reset default queries for individual users? I know if you have MTM installed you'll have a local setting m also not sure where this defaults are cached for web client.  I've also powted the same question on stackoverflow before with screenshots.
https://stackoverflow.com/questions/51106986/mtm-vsts-insert-shared-steps-query-has-different-default-per-user

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eb458d44-bb20-77d2-01cf-3507cb728a1c
* Version Independent ID: 0d66dd50-17c6-b440-9def-d7f8c414688f
* Content: [Share steps between test cases](https://docs.microsoft.com/en-us/azure/devops/test/mtm/share-steps-between-test-cases?view=vsts)
* Content Source: [docs/test/mtm/share-steps-between-test-cases.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/test/mtm/share-steps-between-test-cases.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment]
Thank you for your feedback. I have passed this on to the product team for advice.

**Comment by Abutu** [comment]
@harishkragarwal One of our user is defaulted to the screenshot below everytime 'INSERT SHARED STEPS' is clicked
![image](https://user-images.githubusercontent.com/24704907/46750093-32cfdc80-cc85-11e8-91de-996251af25f5.png)

most users including me have the following default, which I'm assuming you're referring as well.

![image](https://user-images.githubusercontent.com/24704907/46750360-c0133100-cc85-11e8-823a-600dee6c7611.png)

**Comment by Abutu** [comment]
@harishkragarwal is there any updates on this one?

**Comment by Abutu** [comment]
@harishkragarwal  both users are on TFS 2017.3

**Comment by DeborshiSaha1988** [comment]
Hi actually query is only updated when a shared step is added
Please let the user try the following 
1) change the query to contain only one row . 
2) Insert a shared step on any test case. 

The default query should be updated for the user to only contain a single row. 

If the problem still remains please let us know

**Comment by DeborshiSaha1988** [comment]
This is what it should be.
Internally , for each user, when user insert a shared step on a test case, we store the configuration (at that point) in a registry.

Later when user open the inserts shared step dialog, we read the configuration from the registry and display it. 
We would be needing additional data for analyzing this. 

For further  analysis could you please send the traces .Please request the user facing the issue to try out the steps in Chrome browser,
1.	Launch Chrome browser and navigate to any test case
2.	Press F12 to launch the chrome dev tools
3.	Go to the Network tab and make sure that ‘preserve log’ option is checked and that you’ve selected the ‘All’ option as shown below,
![file1](https://user-images.githubusercontent.com/23494184/48821361-f791f480-ed7e-11e8-996a-32dfe381d78a.png)

4.    Open the "insert shared step"  dialog by right clicking in a step.
5.    Change the query to have only one single row as Work Item Type in group Shared Steps ( Remove the other rows )
5.    Run the query and Insert a shared step on a test case.
6.    Open the "insert shared step"  dialog by right clicking in a step again. Expectation is that the query is updated to show the content last used.
6.	Now go to the dev tools window, right click on any of the rows and select ‘Save as HAR with content’ as shown below,
![file2](https://user-images.githubusercontent.com/23494184/48821328-c6192900-ed7e-11e8-8cdd-17150c5bc50a.png)

 7.	Save the file on the machine and send it to debsaha@microsoft.com please. 

Please send it to my mailId.

**Comment by Abutu** [comment]
@DeborshiSaha1988 I've sent you the HAR file sent  to debsaha@microsoft.com yesterday

**Comment by steved0x** [comment]
@Abutu I'm closing this issue since it sounds like you are working directly with @DeborshiSaha1988 - please feel free to reopen this issue if needed. Thank you.
