### ISSUE TITLE
Does the handle sign in/authentication page?

### ISSUE THREAD

**Issue by nadaraj15** [MicrosoftDocs/vsts-docs#1917]
If the url which I provided need authentication, will it load test for that URL? If yes, how is authentication is being handled 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 38f120b6-d7a4-8405-d644-aa716ccbce4b
* Version Independent ID: ea50c669-34a1-0a51-a730-e692ff65f970
* Content: [Test your Azure web app performance under load from the Azure portal](https://docs.microsoft.com/en-us/azure/devops/test/load-test/app-service-web-app-performance-test?view=vsts)
* Content Source: [docs/test/load-test/app-service-web-app-performance-test.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/test/load-test/app-service-web-app-performance-test.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment]
Thank you for your feedback. I have passed this on to the product team for advice.

**Comment by PBoraMSFT** [comment]
@nadaraj15 - if you use the URL based experience in the portal, authentication is not handled. If you use webtest, you can author a richer test with headers or other parameters that contain auth information. 
If you use Visual Studio to write the load test, you can do richer testing - a webtest can be data-driven to simulate multiple users and their auth scenarios.
