### ISSUE TITLE
How do we reference resources in YAML

### ISSUE THREAD

**Issue by trajano** [MicrosoftDocs/vsts-docs#1918]
There's no instructions on how to use or specify these resources in YAML

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee4ec9d0-e0d5-4fb4-7c3e-b84abfa290c2
* Version Independent ID: 3e2b80d9-30e5-0c48-49f0-4fcdfedf5eee
* Content: [Resources - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/resources?view=vsts)
* Content Source: [docs/pipelines/process/resources.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/resources.md)
* Product: **devops**
* GitHub Login: @vtbassmatt
* Microsoft Alias: **alewis**

**Comment by vtbassmatt** [comment]
@andyjlewis this should go on your backlog, I believe.

**Comment by odelljl** [comment]
Does this mean YAML builds cannot be used by Pull Requests?  I can't authorize the temporary branch created by a Pull Request ahead of time.

**Comment by trajano** [comment]
You can, I am just pointing out that it is not documented or at least not well.  What I do as a work around is use the graphical one and convert it to YAML and copy the block that had the resource IDs.

**Comment by TomasHubelbauer** [comment]
I'd also appreciate more instructions around this. I've managed to do this before, but forgot how I did it. I remember it's necessary to use the graphical editor to set up the resource and then copy the result over to YAML, but when I go and Edit the Pipeline now, all I can see is the YAML and checkout tasks with no option of adding a new one graphically. Is it necessary to create a new temporary Pipeline, set the resource up there graphically, copy the ID, then discard the temporary one and use the ID in the YAML one? I don't think it was _this_ contrieved the last time I did it, but maybe things have changed? Is this tracked for improvement somewhere?

**Comment by trajano** [comment]
In my case I needed the connections to a Maven repository so that's not possible without using the secrets.

**Comment by thomps23** [comment]
This topic was refreshed from a YAML perspective recently. Closing this out.

**Comment by calum-hunter** [comment]
Why is this closed? There does not appear to be any documentation on what parameters or how to use them when calling `resources:` in the yaml. Do we just guess? or do we have to dive into the code to try to work it out?

**Comment by thomps23** [comment]
@calum-hunter Thanks for the quick follow-up. We're conducting an audit of open issues against at the moment and I mis-interpreted the full scope of the request.

**Comment by vtbassmatt** [comment]
`resources:` is documented in the [schema](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema#resources), under [templates](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/templates?view=azure-devops#using-other-repositories), and under [container jobs](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/container-phases?view=azure-devops&tabs=yaml#other-settings). That's all they do at the moment, so I'm not sure what more we could document there.

I left this open thinking we could document non-`resources` things like [service connections](https://docs.microsoft.com/en-us/azure/devops/pipelines/library/service-endpoints?view=azure-devops#use-a-service-connection), which I'm doing now.
