### ISSUE TITLE
[[_TOC_]] does not work

### ISSUE THREAD

**Issue by CSharkey145** [MicrosoftDocs/vsts-docs#1921]
You have previously closed someone elses ticket with some info that did not work for me either. I am working in:
Chrome
Microsoft Visual Studio Team Foundation Server Version 16.131.27701.1

This is not working for me and I cannot find a resolution.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fa622358-f5bb-1f5c-177a-081a37b6acef
* Version Independent ID: 72f7fd16-a822-66c8-3a34-8905645ce5f2
* Content: [Markdown syntax for files, widgets, wikis - Azure DevOps & TFS](https://docs.microsoft.com/en-us/azure/devops/project/wiki/markdown-guidance?view=vsts#table-of-contents-toc-for-wiki-pages)
* Content Source: [docs/project/wiki/markdown-guidance.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/project/wiki/markdown-guidance.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@CSharkey145 - Thank you for your inquiry,. The Wiki  TOC feature is currently only valid on Azure DevOps Services. It isn't supported on Team Foundation Server. Please make sure that you use the version selector when viewing a topic, and you should only see content that applies to your platform: https://docs.microsoft.com/en-us/azure/devops/project/wiki/markdown-guidance?view=tfs-2018#table-of-contents-toc-for-wiki-pages

**Comment by ogamespec** [comment]
@KathrynEE - Can you please add TOC support in TFS also?

**Comment by tunebeach61** [comment]
Ditto - please add TOC support in TFS!
