### ISSUE TITLE
Reusing Task Groups

### ISSUE THREAD

**Issue by KbLev** [MicrosoftDocs/vsts-docs#1922]
There's no info on how to reuse the Task Groups in a new pipeline (and also couldn't figure it out myself)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1e6b773c-dfb0-5c58-1463-e9b865d73af6
* Version Independent ID: 83f332ed-719a-5347-acd8-bfe3bdb397b4
* Content: [Task Groups in Azure Pipelines and Team Foundation Server](https://docs.microsoft.com/en-us/azure/devops/pipelines/library/task-groups?view=vsts)
* Content Source: [docs/pipelines/library/task-groups.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/library/task-groups.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment]
Thank you for your feedback. https://docs.microsoft.com/en-us/azure/devops/pipelines/library/task-groups?view=vsts#manage-task-groups says "Use the Export shortcut command to save a copy of the task group as a JSON pipeline, and the Import icon to import previously saved task group definitions. Use this feature to transfer task groups between projects and enterprises, or replicate and save copies of your task groups.". Perhaps try this and see if it achieves what you need.

**Comment by dcasbonne** [comment]
Sorry to reopen a closed discussion but I don't have the import / export settings on TFS 2017. I've some task groups and variable groups in one project but I would like to share those between multiple projects of the same collection. Is there a way to do that ?
Thank you for your help !

**Comment by alexhomer1** [comment]
Thank you for your feedback. I will update the topic to indicate that importing and exporting task groups is not supported in TFS 2017. Note that bugs, issues, suggestions, and feature requests related to the product rather than the documentation can be posted on the Developer Community website at https://developercommunity.visualstudio.com/spaces/21/index.html, where they are tracked by the product teams.

**Comment by dcasbonne** [comment]
Oh sorry I always forgot this website... Thank you for your answer !

**Comment by sophiedasinger** [comment]
Still a bit confused on this documentation -- I have a single Task Group that I would like to share among multiple Build Pipelines. How do I go about adding this task group to an existing Build Pipeline? I don't see an "import" button on the Edit Build Pipeline UI or an option to add an existing Task Group.

**Comment by Polar-is** [comment]
@sophiedasinger  I had the same issue, to not find anything about that in the documentation. I figured out that once you have a task group in the "Task groups" list. It shows up in the list of available tasks in the "Add tasks" list in the build pipeline config in the respective category. E.g. when you assigned the task group to category "Build", it will show up in the list of "Build" tasks of the build pipeline. 

@dcasbonne Could this be added as a separate step in the support material at https://docs.microsoft.com/en-us/azure/devops/pipelines/library/task-groups?view=azure-devops ?

**Comment by dcasbonne** [comment]
@Polar-is it's not me that maintain the documentation, it's @alexhomer1 :)
