### ISSUE TITLE
It is not clear how to use the token

### ISSUE THREAD

**Issue by pcherkasova** [MicrosoftDocs/vsts-docs#1924]
should I assign the token to $PWD in the configuration script?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 344fb6c7-8770-a366-ed19-0626966be202
* Version Independent ID: 22ac2ad8-186a-3530-9a0e-fdbc860eb470
* Content: [Prepare permissions](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/prepare-permissions?view=vsts)
* Content Source: [docs/pipelines/agents/prepare-permissions.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/agents/prepare-permissions.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by vijayma** [comment]
https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/v2-windows?view=vsts explains that you will use the PAT token when prompted for the password while running the config script.
