### ISSUE TITLE
How do I authenticate to an AWS container registry?

### ISSUE THREAD

**Issue by atrauzzi** [MicrosoftDocs/vsts-docs#1929]
My container images currently reside in an AWS container registry.  How do I specify authentication in VSTS (I do not want to store credentials in source control) so that it can download my build container?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3339a2e0-be29-1363-f588-b231d4472c02
* Version Independent ID: 72dd11a3-704d-d0fd-6dfa-cf49f3352de3
* Content: [Container Jobs in Azure Pipelines and TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/container-phases?view=vsts&tabs=yaml#multiple-jobs)
* Content Source: [docs/pipelines/process/container-phases.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/container-phases.md)
* Product: **devops**
* GitHub Login: @erickson-doug
* Microsoft Alias: **macoope**

**Comment by TingluoHuang** [comment]
@atrauzzi i think you can just create a docker registry endpoint and put in you Amazon ECR credential.
it should be similar to reference an image from Azure Container Registry.

**Comment by atrauzzi** [comment]
Well, hold on a second, that's not going to work: https://github.com/aws/aws-vsts-tools/issues/111

You might do well to inform people of the 12 hour expiry for tokens.  It's not a Azure Devops issue necessarily.  But it is something to be mindful of because of how widespread AWS is.
