### ISSUE TITLE
GUID is not a GUID...

### ISSUE THREAD

**Issue by daggmano** [MicrosoftDocs/vsts-docs#193]
The provided Client ID is not a GUID - I presume a character was left off: Client ID: "872cd9fa-d31f-45e0-9eab-6e460a02d1f"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 294772ce-58a0-bb83-8927-3e69beca39df
* Version Independent ID: d9c4a4b3-3abf-d738-369e-fff8532e9dd9
* [Content](https://docs.microsoft.com/en-us/vsts/integrate/get-started/authentication/authentication-guidance)
* [Content Source](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/integrate/get-started/authentication/authentication-guidance.md)
* Service: unspecified

**Comment by steved0x** [comment]
@daggmano I have fixed this and it should be live later today, thank you for letting us know.
