### ISSUE TITLE
Installing XCode Certificates in YAML

### ISSUE THREAD

**Issue by nick-thompson** [MicrosoftDocs/vsts-docs#1930]
I've uploaded my p12 cert to the secure files library as suggested in the docs, but I can't find a way to successfully refer to that file from the YAML. Can we get a YAML example here?

I've tried referring to it directly by name, as well as going all the way through the visual installer and looking at the YAML generated by that to find some UUID that I suppose represents my file. But using that UUID manually in my YAML script also fails to find the secure file.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3e66a70d-e359-9d0a-0143-a9e43b263795
* Version Independent ID: 7b320a02-0a63-947a-3017-4826ab461112
* Content: [Sign Your Mobile App During CI - Azure Pipelines & TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/apps/mobile/app-signing?view=vsts&tabs=apple-install-during-build#sign-your-apple-ios-macos-tvos-or-watchos-app)
* Content Source: [docs/pipelines/apps/mobile/app-signing.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/apps/mobile/app-signing.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by nick-thompson** [comment]
Bump? :)

**Comment by nick-thompson** [comment]
Ok I was finally able to get my InstallAppleCertificate step working by going through the Visual Designer again and preparing an InstallAppleCertificate step there from which I copied the YAML output. This *only* worked, however, after destroying and recreating my pipeline.

Either way, I'll let this issue stand as an ask for documentation about an easier way to get a Secure File's UUID for use in this step.

**Comment by DavidStaheli** [comment]
Keep-alive

**Comment by davidstaheli** [comment]
It is now possible to use the secure file's **name** or **UUID** in YAML and the docs have been updated to describe this.
