### ISSUE TITLE
GitHub Tags are not triggering Build

### ISSUE THREAD

**Issue by tthiery** [MicrosoftDocs/vsts-docs#1933]
I think a note should be added informing that GitHub git tag additions do not trigger a build (while commits and PR do)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e59bebc3-fe8a-ad9e-7c55-884a8c7b4bac
* Version Independent ID: 7db3d604-b118-2f7b-85f4-1bd52244b279
* Content: [Build open source projects](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/ci-public?view=vsts&tabs=github)
* Content Source: [docs/pipelines/build/ci-public.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/build/ci-public.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by andyjlewis** [comment]
When you observed that tag additions do not trigger a build, was that something that you were surprised or disappointed to see?

**Comment by vijayma** [comment]
While this is not very intuitive, you can configure the CI triggers to work with tags as well. In YAML file, the following snippet will trigger a CI when a tag is created.

trigger:
  branches:
    include:
    - refs/tags/*
    - master

**Comment by tthiery** [comment]
I tried that in the trigger override settings for the build. Did not work.

I tried adding your suggestion to the yaml, failed as refs/tags/v* and also refs/tags/*. I read that way to trigger also somewhere related to TFS repos (which I belief will work) but my gut tells me that this is the GitHub integration which has the bug.

I was surprised and disappointed. My intent was to write a pipeline to publish a .NET NuGet to the NuGet.org repository whenever I tag my open source project with a v* tag (e.g. v1.4.5).

**Comment by vijayma** [comment]
@DavidStaheli can you confirm that tag pushes trigger builds with GitHub?

**Comment by tthiery** [comment]
@vijayma @DavidStaheli Without change in the build definition, tag pushes to GitHub are now working to trigger a build (starting at least at 2018-11-21). I guess you fixed something or some IT hickup ended ;).

**Comment by DavidStaheli** [comment]
Hi @tthiery.  Yes, the fix for this just made it to production.  We also added better wildcard support for the tag name.  Thanks for your patience and help diagnosing!
