### ISSUE TITLE
Update to Azure DevOps

### ISSUE THREAD

**Issue by trickpatty** [MicrosoftDocs/vsts-docs#1935]
Last line in the document should refer to Azure DevOps instead of VSTS.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 113ca148-4ba7-2330-eff1-ae88af26b910
* Version Independent ID: d05063b5-ffbf-23eb-a8ad-1dddf53e874a
* Content: [Agile Culture - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/learn/agile/agile-culture)
* Content Source: [https://mseng.visualstudio.com/DefaultCollection/TechnicalContent/_git/devops-learn-pr?path=%2fdocs%2fagile%2fagile-culture.md&version=GBlive&_a=contents](https://mseng.visualstudio.com/DefaultCollection/TechnicalContent/_git/devops-learn-pr?path=%2fdocs%2fagile%2fagile-culture.md&version=GBlive&_a=contents)
* Product: **devops**
* Git Login: **samgu**
* Microsoft Alias: **abjork**

**Comment by steved0x** [comment]
@trickpatty Thanks for letting us know, I fixed this and it should be live shortly, and I'm doing another sweep to make sure no other ones slipped through.
