### ISSUE TITLE
Incomplete Documentation Around Release Trigger Branch Filter

### ISSUE THREAD

**Issue by keithsmithjbs** [MicrosoftDocs/vsts-docs#1936]
@alexhomer1 - I see you last updated the documentation around using custom variables in branch filters. I tried to add a variable and set the branch filter to use that variable and it's not working. 

https://github.com/MicrosoftDocs/vsts-docs/blame/master/docs/pipelines/release/triggers.md#L48

My variable name TestBranch and I set the value to "master" (with no quotes).

![image](https://user-images.githubusercontent.com/13368986/46302184-6ec4bc80-c576-11e8-931f-56f894b644e4.png)

I then created an include branch filter and set the variable to $(TestBranch). 

![image](https://user-images.githubusercontent.com/13368986/46302135-50f75780-c576-11e8-8ea8-afdb57a7f7d6.png)

After kicking of the build, I get the artifact conditions not met:

![image](https://user-images.githubusercontent.com/13368986/46302264-961b8980-c576-11e8-8575-311818b52f22.png)

Is there some type of escaping I need to include to make this work? 

Thanks!

**Comment by alexhomer1** [comment]
Thank you for your feedback. I have passed this on to the product team for advice.

**Comment by RoopeshNair** [comment]
Currently variables are supported only for artifact triggers (screenshot below). Looks like you are trying to set artifact filters for an environment. We haven't had any requests for supporting variables for the artifact filters, you can vote for this on[ user voice](https://visualstudio.uservoice.com/forums/330519-team-services/category/145269-release-management?page=3)

![image](https://user-images.githubusercontent.com/1370480/46392345-b4ac8c80-c6fe-11e8-8016-6a1abdc16fbe.png)
