### ISSUE TITLE
The screenshots are out of date

### ISSUE THREAD

**Issue by dendle** [MicrosoftDocs/vsts-docs#1938]
The lastest Azure Devops experience has a vertical menu, and a simplified horizontal top menu, on which the "Import Repository" menu item does not appear.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d24126ce-abfc-07d0-ceea-51534f745e55
* Version Independent ID: 60861ae7-4b6d-e360-8ab7-28b276326569
* Content: [Import repositories from TFVC to Git - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/import-from-tfvc?view=vsts)
* Content Source: [docs/repos/git/import-from-TFVC.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/repos/git/import-from-TFVC.md)
* Product: **devops**
* GitHub Login: @steved0x
* Microsoft Alias: **atinb**

**Comment by dendle** [comment]
Actually, the import option only appeared after I created a blank Git repo.
I had an old Team project in VSTS.  It had a single TFVC repo.  No import option on repo dropdown.
Created a new git repo in the same project, and the new menu item appeared, allowing me to import the TFVC repo into a new repo.  I had to create two Git repos in order to use the import tool, which seems like a bug.

**Comment by steved0x** [comment]
@dendle Thank you for letting us know - that does sound odd. I'll add a note to the article to describe this workaround, and I'll report this to the product group.

**Comment by martinpinto** [comment]
What were the reasons for the Windows team to not migrate the TFVC history?
