### ISSUE TITLE
AKS

### ISSUE THREAD

**Issue by spacecat** [MicrosoftDocs/vsts-docs#194]
Can you also add a doc page describing how to deploy to managed kubernetes (AKS)?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a86dced-9bbf-5b3d-f373-ff2568f20efa
* Version Independent ID: 65d17578-9c65-bc4c-1e13-985f7beaf80d
* [Content](https://docs.microsoft.com/en-us/vsts/build-release/apps/cd/azure/deploy-container-kubernetes)
* [Content Source](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/build-release/apps/cd/azure/deploy-container-kubernetes.md)
* Service: unspecified

**Comment by alexhomer1** [comment]
Thank you. This is in our plan for upcoming documentation.
