### ISSUE TITLE
Windows Machine File Copy task - Get-ResourceFQDNTagKey is not recognized 

### ISSUE THREAD

**Issue by RXtr** [MicrosoftDocs/vsts-docs#1940]
Trying to run version 1.0.41 of the Windows Machine File Copy task. Not sure if there's a new version somewhere, I work on an offline environment using Microsoft Visual Studio Team Foundation Server version 15.117.26912.0

Exception is thrown in the  script that doesn't recognize 'Get-ResourceFQDNTagKey' as a valid function

**Comment by steved0x** [comment]
@RXtr Thank you for your feedback. The issues in this repo are for content feedback, can you let me know the URL of the article that goes with this feedback so I can pass it along to the correct author? If this is a product issue (something not working properly, or a feature request), please file an issue here: https://developercommunity.visualstudio.com/spaces/21/index.html

Thank you.

**Comment by steved0x** [comment]
@RoopeshNair Can you assist?

**Comment by RXtr** [comment]
Oh man sorry about that, I haven't checked my replies on this in a while.

I was actually able to solve my problem. The issue was that I was using a
new version of the Build Agent with an old copy of Vsts build, as we are a
standalone installation.

Thanks for following up though!

**Comment by RoopeshNair** [comment]
Thanks for confirming, closing the issue
