### ISSUE TITLE
Flow Charts

### ISSUE THREAD

**Issue by Bene-Graham** [MicrosoftDocs/vsts-docs#1941]
It would be amazing to have functionality like https://mermaidjs.github.io/ to do flowcharts within the wiki.

It would be a lot easier then to create them in Visio and export as images.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fa622358-f5bb-1f5c-177a-081a37b6acef
* Version Independent ID: 72f7fd16-a822-66c8-3a34-8905645ce5f2
* Content: [Markdown syntax for files, widgets, wikis - Azure DevOps & TFS](https://docs.microsoft.com/en-us/azure/devops/project/wiki/markdown-guidance?view=vsts#basic-format-elements)
* Content Source: [docs/project/wiki/markdown-guidance.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/project/wiki/markdown-guidance.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@Bene-Graham  - Thank you for the feedback. I'll pass this along to the PM. Meanwhile, you may want to add this as a feature request to our [User Voice page](https://visualstudio.uservoice.com/forums/330519-team-services).

**Comment by adramasu** [comment]
@Bene-Graham Thanks for raising this feedback. We have a [uservoice ](https://visualstudio.uservoice.com/forums/330519-azure-devops-formerly-visual-studio-team-services/suggestions/31210696-wiki-mermaid-plantuml-support) for the same. Can you please upvote this? This will keep you updated about this feature when we take it up.
