### ISSUE TITLE
Broken link "Azure DevOps Pricing"

### ISSUE THREAD

**Issue by dburnison** [MicrosoftDocs/vsts-docs#1945]
"Azure DevOps Pricing" is broken, it should go to: 
https://azure.microsoft.com/en-us/pricing/details/devops/azure-devops-services/

Dave.Burnison@Microsoft.com

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 52303279-70fd-a0f6-cc6f-96bf73ed8c32
* Version Independent ID: cb30fbe3-b069-2665-d8da-9f714a23290a
* Content: [Billing frequently asked questions (FAQ)](https://docs.microsoft.com/en-us/azure/devops/organizations/billing/billing-faq?view=vsts&tabs=new-nav#q-can-i-use-the-azure-monetary-commitment-funds-from-my-enterprise-agreement-to-buy-azure-devops)
* Content Source: [docs/organizations/billing/billing-faq.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/billing/billing-faq.md)
* Product: **devops**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Thanks @dburnison, I've updated all links. Should be live sometime this afternoon. Thanks again!
