### ISSUE TITLE
Show sample specifying a custom location for composer.json

### ISSUE THREAD

**Issue by jftl6y** [MicrosoftDocs/vsts-docs#1947]
Would it be possible to show an example for the correct yaml syntax for composer install when the composer.json does not live in the root directory (i.e. specify the location for the composer.json).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4d21b6ef-2440-f2b7-7f38-465ade7c14c6
* Version Independent ID: 9b2ebcef-924d-6850-9c27-4f14a2b45b53
* Content: [PHP](https://docs.microsoft.com/en-us/azure/devops/pipelines/languages/php?view=vsts)
* Content Source: [docs/pipelines/languages/php.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/languages/php.md)
* Product: **devops**
* GitHub Login: @erickson-doug
* Microsoft Alias: **dastahel**

**Comment by joebourneMS** [comment]
Hi John, I've asked my team to look into this now. Stay tuned, I'll get you a sample soon.

**Comment by alepauly** [comment]
@jftl6y - Is your composer.json in a subfolder? You can always pass in the --working-dir argument to composer, something like (assuming composer.json is inside subfolder ```pkgs```):
```
composer install --no-interaction --working-dir=pkgs
```

You can also specify the absolute path, using the built-in [system variables](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables):
```
composer install --no-interaction --working-dir='$(system.defaultWorkingDirectory)/pkgs'
```

We'll look into coming up with a sample, but hopefully that answers what you're looking for. If not, please let me know.

**Comment by chu01** [comment]
I am trying to build a pipeline for Drupal 8. when i start and run for PHP, i encountered an error. here:  
`- script: composer install --no-interaction --prefer-dist
  displayName: 'composer install'`

any suggestion?

**Comment by thejoebourneidentity** [comment]
https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/languages/php.md#using-a-custom-composer-location
