### ISSUE TITLE
Git branch permissions. 

### ISSUE THREAD

**Issue by glugo** [MicrosoftDocs/vsts-docs#195]
I need to Deny Create branch for some branches and allow create branch for other branches in the same repo. It's possible ? The documentation do not explain how to modify the permissions create Branch for specific branches.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 64f60178-1529-9b48-379a-2ca42c5bb741
* Version Independent ID: 468a3fe4-4551-022b-9000-a2acdd2968cc
* [Content](https://docs.microsoft.com/en-us/vsts/security/set-git-tfvc-repository-permissions)
* [Content Source](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/security/set-git-tfvc-repository-permissions.md)
* Service: unspecified

**Comment by steved0x** [comment]
@glugo See [this](https://docs.microsoft.com/en-us/vsts/git/how-to/require-branch-folders?view=vsts&tabs=vsts-tfs-web-portal) for how you can require branch folders by denying create access for branches at the root. Would an approach like this work for you? Or do you want to block creation of branches with certain names?

**Comment by glugo** [comment]
Hi Steve, thanks for your email. Let me check and I will you know !

Thanks and best regards.
GL

**Comment by steved0x** [comment]
@glugo I'm going to go ahead and close this issue, but please open up a new one if that article wasn't able to help you with your question about branches. Thank you.
