### ISSUE TITLE
`Subscriptions` and `Project REST API` links broken

### ISSUE THREAD

**Issue by ranjan-ranjan** [MicrosoftDocs/vsts-docs#1954]
`Subscriptions` and `Project REST API` links broken

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 162ea8ce-f3c4-5ea1-fecc-663ac351a60b
* Version Independent ID: 7f40bf79-259f-43bc-0582-7e8f5721a294
* Content: [Subscribe to Azure DevOps Services events from another service](https://docs.microsoft.com/en-us/azure/devops/service-hooks/create-subscription?view=vsts)
* Content Source: [docs/service-hooks/create-subscription.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/service-hooks/create-subscription.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by elbatk** [comment]
Hi @ranjan-ranjan , fixing these links today, thank you!
