### ISSUE TITLE
More information needed on how to configure self-hosted agents

### ISSUE THREAD

**Issue by tonuv** [MicrosoftDocs/vsts-docs#1957]
How can one install dependent software on self-hosted agents? Like a specific missing VS SDK?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 47625b86-abd5-ee15-6d61-8bcf81861b96
* Version Independent ID: be9a6174-a69b-7aed-d584-5f602fcc5eb4
* Content: [Build and Release Agents - Azure Pipelines & TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/agents?view=vsts#feedback)
* Content Source: [docs/pipelines/agents/agents.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/agents/agents.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by andyjlewis** [comment]
Whoever owns the machine can install Visual Studio on it.
