### ISSUE TITLE
Lock Page for Editing

### ISSUE THREAD

**Issue by czalin** [MicrosoftDocs/vsts-docs#1958]
There needs to be a way to lock the pages for editing. If another team member opens the page, makes a quick change, and saves it at the same time that I'm making a larger change, all of my changes are lost.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d7892ee5-8b56-bd95-29bb-41ebb8a8bd7e
* Version Independent ID: eccf0785-0968-d6a2-d29e-0c4796aa165c
* Content: [Add, edit, or print wiki pages - Azure DevOps & TFS](https://docs.microsoft.com/en-us/azure/devops/project/wiki/add-edit-wiki?view=vsts&tabs=new-nav)
* Content Source: [docs/project/wiki/add-edit-wiki.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/project/wiki/add-edit-wiki.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@czalin - Thank you for the feedback. I'll pass this along to the PM. Meanwhile, you may want to add this as a feature request to our [User Voice page](https://visualstudio.uservoice.com/forums/330519-team-services).

**Comment by adramasu** [comment]
@czalin We have a suggestion for the same in our [Uservoice](https://visualstudio.uservoice.com/forums/330519-azure-devops-formerly-visual-studio-team-services/suggestions/33538690-wiki-concurrent-editing). Please upvote the same so that when we take this up, you are updated.
