### ISSUE TITLE
"Why do these operations take so long?" should be on separate line in "Too many files" section

### ISSUE THREAD

**Issue by judemars** [MicrosoftDocs/vsts-docs#1962]
I believe the bullet points in that section were meant to be spaced like so:

- ‘git status’ takes up to 10 minutes, even where there are no dirty files in the repo
- ‘git checkout’ can take 3 hours
- ‘git commit’ takes 30 minutes 

Why do these operations take so long? Two fundamental reasons:
- Git maintains an index file that contains a flat list of every file in the repo. This creates overhead for every single command that needs the index, since Git has to read and parse the index every time you run those commands.
- When you run an operation like status or checkout, Git essentially has to walk through every single file in your working directory, compare those files to the related entry in the index, and then compare the entries in the index to the corresponding objects in the Git tree. With over 3M files in the repo, the sheer cost of all that file IO means there’s no way for the operation to complete quickly enough to feel responsive.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b891ab97-f15e-79b7-df68-38c29e45efaf
* Version Independent ID: 52b38d10-59c6-7c3b-a00c-7ccdab65a5b8
* Content: [Technical Scale Challenges with Git - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/learn/git/technical-scale-challenges)
* Content Source: [https://mseng.visualstudio.com/DefaultCollection/TechnicalContent/_git/devops-learn-pr?path=%2fdocs%2fgit%2ftechnical-scale-challenges.md&version=GBlive&_a=contents](https://mseng.visualstudio.com/DefaultCollection/TechnicalContent/_git/devops-learn-pr?path=%2fdocs%2fgit%2ftechnical-scale-challenges.md&version=GBlive&_a=contents)
* Product: **devops**
* Git Login: **samgu**
* Microsoft Alias: **sanoursa**

**Comment by steved0x** [comment]
@judemars Looks like the formatting got messed up when these articles were migrated (OK I just did a quick sweep of the Git at Scale articles and only this one had that issue). I just merged a fix for this into our private repo and it should be live soon. Thanks for letting us know!

**Comment by judemars** [comment]
No problem! Thanks for the awesome documentation
