### ISSUE TITLE
Why is the prompt for a service connection "Subscription" ?

### ISSUE THREAD

**Issue by kgreed** [MicrosoftDocs/vsts-docs#1963]
A subscription is something I pay for
A service connection is something I set up

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72b90dd0-49f9-4ed4-3010-9a64dde6ae5a
* Version Independent ID: 6e679d50-4e94-eee3-8793-af884cc909ca
* Content: [Service connections in Azure Pipelines and Team Foundation Server](https://docs.microsoft.com/en-us/azure/devops/pipelines/library/service-endpoints?view=vsts#use-a-service-connection)
* Content Source: [docs/pipelines/library/service-endpoints.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/library/service-endpoints.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment]
Thank you for your feedback. The drop-down list shows both your subscriptions and your configured service connections. The YAML property accepts both types. It's often easier to select a subscription, but if you have configured additional security for the service connection you should select this instead.
