### ISSUE TITLE
Out dated titles?

### ISSUE THREAD

**Issue by philip-reed** [MicrosoftDocs/vsts-docs#1964]
This content appears under TFS 2013. But I think it is still relevant to TFS 2018 & Azure Devops. Worth updating?  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b9f448dd-3246-389f-39dd-f12b885f8fb2
* Version Independent ID: e05664ed-7a58-77d2-a27d-a28f938fa41f
* Content: [Use Visual Studio and Team Foundation Server with Git - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/overview-2013?view=tfs-2013&viewFallbackFrom=tfs-2018)
* Content Source: [docs/repos/git/overview-2013.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/repos/git/overview-2013.md)
* Product: **devops**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
@philip-reed The updated version of that page is [here](https://docs.microsoft.com/en-us/azure/devops/repos/git/overview?view=vsts) - now that we have the version switcher for the documentation I could combine them, but just about everything in that 2013 version page should also be in this updated page? What part felt missing, and I can add it?

**Comment by philip-reed** [comment]
@steved0x Hi, This is the page I was referring to:

https://docs.microsoft.com/en-us/azure/devops/repos/git/overview-2013?view=tfs-2013&viewFallbackFrom=tfs-2018

After using the version switcher, there is a banner at the top of the page stating:

"The requested page is not available for Team Foundation Server 2018. You have been redirected to the newest product version this page is available for." Which is TFS2013.  Maybe it should redirect to the page you mentioned? Not sure, just thought the page was out of date when I saw references to 2013.

![image](https://user-images.githubusercontent.com/7798175/46655658-245dc400-cba4-11e8-81da-6b7072f62c1c.png)

**Comment by steved0x** [comment]
@philip-reed I'm sorry for the great delay. There is a newer version of that page (without -2013 in the filename here:

https://docs.microsoft.com/en-us/azure/devops/repos/git/overview?view=azure-devops

I'll see if I can set up a redirect or something instead of the experience that you are seeing.
