### ISSUE TITLE
A way for TOC to skip first title

### ISSUE THREAD

**Issue by DavidHenri008** [MicrosoftDocs/vsts-docs#1965]
It would be nice to have a way for TOC to skip the very first page `<h1>` title.
In the example below, It does not make sense to include the "Main Page Title" in the table of contents since it appears after the first `<h1>` title.

# Main Page Title
some text ...
[[_TOC_]]
## Section 1
some text ... 
## Section 2
some text ...

**Comment by steved0x** [comment]
@DavidHenri008 Thank you for your feedback. The issues in this repo are for content feedback, can you let me know the URL of the article that goes with this feedback so I can pass it along to the correct author? If this is a product issue (something not working properly, or a feature request), please file an issue here: https://developercommunity.visualstudio.com/spaces/21/index.html

Thank you.

**Comment by DavidHenri008** [comment]
@steved0x I would like to submit an enhancement to the markdown used by Azure DevOps' wiki. Do you suggest me to add it there: [https://developercommunity.visualstudio.com/spaces/21/index.html](https://developercommunity.visualstudio.com/spaces/21/index.html)?

**Comment by steved0x** [comment]
@DavidHenri008 Yes exactly, please submit it there and it will go right to the product group and help them with planning new features and enhancements to existing features.

**Comment by DavidHenri008** [comment]
@steved0x It is strange but when I try to add a feature for DevOps it tells me I do not have access.
