### ISSUE TITLE
Task Groups not supported in YAML builds is not clearly indicated

### ISSUE THREAD

**Issue by hintbw** [MicrosoftDocs/vsts-docs#1966]
The result of the following issue - https://github.com/Microsoft/azure-pipelines-agent/issues/1498 is that it should be clearly documented that task groups are not supported in YAML builds and that, presumably, YAML templates are mechanism where this will be accomplished. I don't see this called out anywhere and it inhibits our adoption of YAML builds because we use task groups in almost every build we have and are struggling to understand the migration path.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1e6b773c-dfb0-5c58-1463-e9b865d73af6
* Version Independent ID: 83f332ed-719a-5347-acd8-bfe3bdb397b4
* Content: [Task Groups in Azure Pipelines and Team Foundation Server](https://docs.microsoft.com/en-us/azure/devops/pipelines/library/task-groups?view=vsts)
* Content Source: [docs/pipelines/library/task-groups.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/library/task-groups.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment]
Topic has been updated. I will pass your comment on to the product team. Thank you.

**Comment by grayjeremy** [comment]
The documentation seems to be updated with a purple warning that indicates this isn't applicable for YAML...it looks like this issue can be closed.
