### ISSUE TITLE
Get a sample package to push section got wrong command

### ISSUE THREAD

**Issue by doggy8088** [MicrosoftDocs/vsts-docs#1968]
The following command is not working in the **Get a sample package to push** section of this article.

```powershell
nuget.exe install Azure DevOps Services-HelloWorld -ExcludeVersion
```

---
#### 文件詳細資料

⚠ *請勿編輯此區段。 這是 docs.microsoft.com ➟ GitHub 問題連結的必要項。*

* ID: 9a10a409-5468-9532-f0dc-5a28cdd566d8
* Version Independent ID: 2ef20266-bc45-448b-27f5-e5c3bffed2ef
* Content: [Get Started with NuGet Azure Artifacts in Azure DevOps Services and TFS](https://docs.microsoft.com/zh-tw/azure/devops/artifacts/get-started-nuget?view=vsts&tabs=new-nav)
* Content Source: [docs/artifacts/get-started-nuget.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/artifacts/get-started-nuget.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by elbatk** [comment]
Hi @doggy8088 , this may have been a rebrand copy/paste error. Adding @alexmullans to take a look.

**Comment by doggy8088** [comment]
@elbatk I just created a PR for this.
