### ISSUE TITLE
Collections

### ISSUE THREAD

**Issue by PJBowron** [MicrosoftDocs/vsts-docs#1972]
I'm looking for information on 'Collections'. An entry here, even a link to documentation elsewhere, would be helpful.
Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f817e38b-fbed-c55f-00fb-3dc90eb64199
* Version Independent ID: 3a286eb8-fe12-f628-21d2-84547472b991
* Content: [Security terms used in Azure DevOps & TFS](https://docs.microsoft.com/en-us/azure/devops/organizations/security/security-glossary?view=vsts)
* Content Source: [docs/organizations/security/security-glossary.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/security/security-glossary.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@PJBrown - Thank you for your inquiry. I will add an entry to our glossary to cover Collections. 
For now, here is an brief definition and links to additional resources: 

A collection is a container for a number of Azure DevOps projects. Within Azure DevOps Services, a collection corresponds to an organization. For on-premises TFS deployments, you can add and manage collections to specify the logical and physical resources available to the projects within the collection. 

Learn more: [About projects and scaling your organization](https://docs.microsoft.com/en-us/azure/devops/organizations/projects/about-projects), [Manage organizations](https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/organization-management?view=vsts) or [Manage project collections in Team Foundation Server](https://docs.microsoft.com/en-us/tfs/server/admin/manage-team-project-collections).
