### ISSUE TITLE
user input variables to start a pipeline

### ISSUE THREAD

**Issue by chvalean** [MicrosoftDocs/vsts-docs#1975]
I'm looking for what other CI's can do - allow a user to provide certain input variables - various entry format, lists of choice items or text input that will be used as variables in the pipeline execution.
This seems to be missing in Azure pipelines.

**Comment by andyjlewis** [comment]
We do support user-defined variables as strings https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables.
