### ISSUE TITLE
Absolute path in TFVC (or Git) for images in Wiki

### ISSUE THREAD

**Issue by plarge** [MicrosoftDocs/vsts-docs#1982]
I’m not sure that’s an issue. Maybe I don’t really understand the documentation.

I tried to insert an image in the wiki page with an absolute path in TFVC, but it didn’t work.
I tried the same action with an absolute path in git, with the same result.

I will need to store my images in a source controller like TFVC (we work with TFS 2018).

Could you please help me, and explain what's wrong.

**Comment by danhellem** [comment]
You should not need to store your images any place. You can cut and paste, or drag and drop, images from other sources directly into the wiki page. 

if you want to use [source control for your wiki ](https://docs.microsoft.com/en-us/azure/devops/project/wiki/publish-repo-to-wiki?view=vsts&tabs=new-nav)we suggest doing so with a git repo. I don't believe TFVC is supported.
