### ISSUE TITLE
How can I create a highlight block like the [!NOTE] elements on this page?

### ISSUE THREAD

**Issue by dahlsailrunner** [MicrosoftDocs/vsts-docs#1983]
I'd like to include highlight blocks in my readme (I'm using on-prem TFS 2018) just like the ones you have on this page (first appears inside the Emphasis section).  I've tried the following both with and without the moniker lines:

::: moniker range="tfs-2018"
&gt; [!NOTE]  
&gt; My custom notes here....
::: moniker-end

Any guidance or input would be helpful / appreciated.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fa622358-f5bb-1f5c-177a-081a37b6acef
* Version Independent ID: 72f7fd16-a822-66c8-3a34-8905645ce5f2
* Content: [Markdown syntax for files, widgets, wikis - Azure DevOps & TFS](https://docs.microsoft.com/en-us/azure/devops/project/wiki/markdown-guidance?view=vsts)
* Content Source: [docs/project/wiki/markdown-guidance.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/project/wiki/markdown-guidance.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by steved0x** [comment]
@dahlsailrunner The [!NOTE] sections are part of the custom build process for our documentation and I don't believe they are available in the parts of Azure DevOps Services or TFS that use markdown like wikis, pull request comments, work item descriptions, etc... I am assigning this to the author of that article for her feedback as she may have an idea.

**Comment by dahlsailrunner** [comment]
Sounds good -- this would be great functionality to add.  It's in YOUR docs and it's a great way to add some emphasis to a point.  It's one of the things I like a lot about "Read The Docs".  Looking forward to further dialog on this.  :)

**Comment by KathrynEE** [comment]
@dahlsailrunner - Thank you for your inquiry. As Steve notes, this feature is part of our documentation build process and not a supported feature in the Wiki or elsewhere. You can always suggest it as a request feature in our [User Voice page](https://visualstudio.uservoice.com/forums/330519-team-services).

**Comment by perezd** [comment]
That User Voice page is now a 404, where is the best place to make a feature request for something like that? This is super useful.
