### ISSUE TITLE
Manage user access to Azure DevOps is a broken link

### ISSUE THREAD

**Issue by mdavis332** [MicrosoftDocs/vsts-docs#1985]
Under Q: Why can't users access some features?, the link that says "Learn how to manage users and access levels for Azure DevOps" (which points to https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/add-account-users-assign-access-levels), is a broken link that results in a 404. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bf9c6be4-bc1b-4658-6a2d-747e7f1eab3e
* Version Independent ID: 1a938c62-a80e-0768-80d7-078faf93dcff
* Content: [Troubleshoot adding and deleting organization users in the Azure DevOps Users](https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/faq-add-delete-users?view=vsts#find-owner)
* Content Source: [docs/organizations/accounts/faq-add-delete-users.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/accounts/faq-add-delete-users.md)
* Product: **devops**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
@mdavis332 thanks for letting us know! I've submitted a fix that should go live sometime this afternoon. Thanks again.
