### ISSUE TITLE
Content selector needed at main level

### ISSUE THREAD

**Issue by huntantr** [MicrosoftDocs/vsts-docs#1987]
When browsing through the documentation, I have to keep changing the content selector to the version of TFS I'm using. It would be very useful if from the main documentation page, for example: https://docs.microsoft.com/en-us/azure/devops/index you could select the version then this carries forward with any other child page that is then loaded. Knowing that I'm consistently looking at the correct content will help me in finding the information I need.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 104e3946-4f75-5c58-52da-f621b0a939ed
* Version Independent ID: 0e9d0800-5d7f-9e4b-054e-879a0aeee89a
* Content: [About process customization and inherited processes - Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/organizations/settings/work/inheritance-process-model?view=vsts&viewFallbackFrom=tfs-2017)
* Content Source: [docs/organizations/settings/work/inheritance-process-model.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/settings/work/inheritance-process-model.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@huntantr - Thank you for the feedback. I have passed on your request to our engineering group who are looking at the next updates to support version selection.
