### ISSUE TITLE
REST API to unlist and/or delete package versions from feed

### ISSUE THREAD

**Issue by juanyaw** [MicrosoftDocs/vsts-docs#1988]
I'm trying to figure out how to get the correct token or API call to unlist or delete package versions.

When attempting a call:

$patchNode = @{op="add";path="/isDeleted";value=$true}
irm -Headers @{Authorization="Basic <PAT>"} -Method PATCH -Body (ConvertTo-Json $patchNode) -ContentType "application/json-patch+json" "https://feeds.dev.azure.com/{org}/_apis/packaging/feeds/{feedId}/packages/{packageId}/versions/{versionId}?api-version=5.0-preview.1"

I get a FeedsPermissionException which tells me that the user needs InternalAdmin, but the PAT I've generated is based on an account that is Owner on the feed and I've enabled Package permissions for the PAT (even if I do full permissions it still fails).

How can this be done via REST API or do I have to use nuget.exe to unlist only?

**Comment by elbatk** [comment]
Hi @juanyaw , it looks like you're trying to access the feeds API but you should be trying to access the packages. Take a look at this: https://docs.microsoft.com/en-us/rest/api/azure/devops/artifactspackagetypes/npm/unpublish%20package?view=azure-devops-rest-5.0. That's NPM, but you can see other package types as well. I'm not too sure about the permission exception, it may still occur, but this is a good step in the right direction.
