### ISSUE TITLE
Modify the presentation of the Predefined variables table

### ISSUE THREAD

**Issue by corydeppen** [MicrosoftDocs/vsts-docs#199]
It's difficult to read the Variable Name column when only 5-8 characters are displayed on each line.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ffebdc8-521c-44b5-cde4-4abdc1bd6f18
* Version Independent ID: dc0effda-6d93-62aa-64c5-4e6f283b0826
* [Content](https://docs.microsoft.com/en-us/vsts/build-release/concepts/definitions/build/variables?tabs=batch#feedback)
* [Content Source](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/build-release/concepts/definitions/build/variables.md)
* Service: unspecified

**Comment by corydeppen** [comment]
![image](https://user-images.githubusercontent.com/313264/36620280-4d0f5478-18c0-11e8-8703-787d3c26adad.png)

**Comment by andyjlewis** [comment]
Thanks for the feedback! The engineering team is following up, so I hope we get some alternative way to render this table.

**Comment by andyjlewis** [comment]
I changed the format to flat Markdown. You should see this change in next day or so.
