### ISSUE TITLE
New Field is disabled for member of Project Collection Administrators group,

### ISSUE THREAD

**Issue by nirnaybansal** [MicrosoftDocs/vsts-docs#1993]
New Field is disabled for member of Project Collection Administrators group.
witadmin exportwitd givign error : The feature is disabled. Contact your Azure DevOps Sever Administrator. Process Id: &lt;&lt;Some Guid&gt;&gt;

But I am the Administrator. I created the project.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c1d7885e-7aa6-1e0e-8f90-a7177a53b0d7
* Version Independent ID: 0494e296-574f-b226-5bfd-0193667ad40d
* Content: [Add a custom field to an inherited process - Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/organizations/settings/work/add-custom-field?view=vsts&tabs=new-nav)
* Content Source: [docs/organizations/settings/work/add-custom-field.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/settings/work/add-custom-field.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@nirnaybansal  - Thank you for your inquiry. Please confirm that you are working from Azure DevOps Services and not an on-premises TFS. The topic you reference is valid for Azure DevOps Services only. If you are working from Azure DevOps Services, please contact [Deveoper community(v) to get help with this issue.
