### ISSUE TITLE
Publishing build artefacts when validating PR from fork

### ISSUE THREAD

**Issue by tomconte** [MicrosoftDocs/vsts-docs#1994]
Does this documentation need to have more details about handling pull requests from forks? I have opened the following product feedback where the PublishBuildArtifacts task does not work in this context.

https://developercommunity.visualstudio.com/content/problem/350007/build-from-github-pr-fork-error-tf400813-the-user-1.html

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e59bebc3-fe8a-ad9e-7c55-884a8c7b4bac
* Version Independent ID: 7db3d604-b118-2f7b-85f4-1bd52244b279
* Content: [Build open source projects](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/ci-public?view=vsts&tabs=github#validate-contributions-from-forks)
* Content Source: [docs/pipelines/build/ci-public.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/build/ci-public.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by MarkIannucci** [comment]
I ran into the same issue and opened a GitHub issue about this here:
https://github.com/Microsoft/azure-pipelines-tasks/issues/8732

**Comment by DavidStaheli** [comment]
This capability has been added to Azure Pipelines.  I'm hopeful it will be available in all of production by the end of next week (November 9).

**Comment by DavidStaheli** [comment]
Hi @tomconte and @MarkIannucci.  Though this has been deployed to production, it's still behind a feature flag.  We found one bug that we want to still address before enabling the feature flag for everyone to use the feature.  The bug should be addressed by the first part of December.  I'll close this issue for now, but please reopen if we can provide specific help.
