### ISSUE TITLE
how to run a build job on multiple agent in parallel?

### ISSUE THREAD

**Issue by hamed-shirbandi** [MicrosoftDocs/vsts-docs#1995]
I have a build pipeline that contains one task and linked to an agent pool that have 2 self-hosted agents.
I set Parallelism to Multi-agent and Number of agents to 2.
Both of agents in agent pool are online.
But when I queue new build, it doesn't run in parallel and run Twice on first agent !

![1](https://user-images.githubusercontent.com/19574409/46572943-1c7f0380-c99b-11e8-854c-c36ecc8074e7.png)
![2](https://user-images.githubusercontent.com/19574409/46572945-1f79f400-c99b-11e8-85b9-664c1dd915b1.png)
![3](https://user-images.githubusercontent.com/19574409/46572947-230d7b00-c99b-11e8-9e18-60c9ee9c02e6.png)
![4](https://user-images.githubusercontent.com/19574409/46572948-27399880-c99b-11e8-8b37-cdfec616817a.png)
![5](https://user-images.githubusercontent.com/19574409/46572949-2bfe4c80-c99b-11e8-9e6a-570ab63a2dc3.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cb26f633-6068-0e2a-0b8d-e97f8acdbb09
* Version Independent ID: 449ffa66-9707-c87a-6128-57beeb22f0fc
* Content: [Parallel jobs in Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/licensing/concurrent-jobs-vsts?view=vsts)
* Content Source: [docs/pipelines/licensing/concurrent-jobs-vsts.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/licensing/concurrent-jobs-vsts.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by vijayma** [comment]
This could happen for two reasons: 

1. You do not have enough concurrency in your org. By default, all orgs get a concurrency of 1 for free. You can purchase additional concurrency by clicking on "Manage parallel limits".

2. You have enough concurrency, but the second agent does not satisfy the demands of your job. You can check this by looking at the demands of the job and by matching those to the capabilities of each of the agents.

**Comment by jimicze** [comment]
@vijayma No. It works as it should. But @hamed-shirbandi need to setup pipeline in different way.

The manner in which the job’s tasks are parallelized. 

None: Tasks will run on a single agent.

Multi-configuration: Run the same set of tasks on multiple configurations as specified in the multipliers. Configurations will run in parallel and each configuration will use a single agent. The total number of agents used by the job will depend on the number of configurations, and can be limited by specifying the maximum number of agents. 

Multi-agent: Run the same set of tasks on multiple agents using the specified number of agents. 

More information.
