### ISSUE TITLE
What is the purpose of the status badge?

### ISSUE THREAD

**Issue by kgreed** [MicrosoftDocs/vsts-docs#1996]
Why do I want to get one?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 38f7a23b-ebd4-af3e-68a2-275f7e45c33e
* Version Independent ID: f552a18c-ba29-00d4-03b6-254d7556d319
* Content: [Create your first pipeline - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/get-started-yaml?view=vsts)
* Content Source: [docs/pipelines/get-started-yaml.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/get-started-yaml.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by andyjlewis** [comment]
https://docs.microsoft.com/en-us/azure/devops/pipelines/get-started

**Comment by andyjlewis** [comment]
Sorry, misread the issue and the topic at first. Good suggestion, thanks. We'll look into it.

**Comment by kgreed** [comment]
Thanks Andy.  I will try to make it clearer that I am making a suggestion next time.

**Comment by kgreed** [comment]
Maybe something like 
"Now that you have a build pipeline wouldn't it be great if you could see the status of your build in the read me file?

We can use a status badge to do this. The steps are as follows:"

**Comment by andyjlewis** [comment]
Thanks @kgreed, I agree that we need to briefly state the reason to do it. I'm working on some related content about badges. I'll follow up.

**Comment by kgreed** [comment]
Great. I only just browsed to a github Readme.md  ( https://github.com/Microsoft/WindowsTemplateStudio/blob/master/README.md ) and was able to see  the  badges.  Being new to opensource I never realized you could do this!.

**Comment by andyjlewis** [comment]
fixed in a commit I just made to our internal master, should publish soon. thank you for the feedback.
