### ISSUE TITLE
Need Help understanding apk signing keystore file path

### ISSUE THREAD

**Issue by joychandru** [MicrosoftDocs/vsts-docs#2000]
Hi Team,

I am currently working in Azure DevOps, and xamarin android application development. 
I am able to create build pipeline and build android source successfully. but when I try to sign my android apk I am facing challenges to give android keystore file. 

Note: I have placed my keystore file in my project android source code and main source code path as well.  now i really don't know how to specify this keystore file path in my pipeline.yml file.  Below is my yml content.

_# Xamarin.Android
# Build a Xamarin.Android project.
# Add steps that test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xamarin

pool:
  vmImage: 'macOS 10.13'

variables:
  buildConfiguration: 'Release'
  outputDirectory: '$(build.binariesDirectory)/$(buildConfiguration)'

steps:
- task: NuGetToolInstaller@0

- task: NuGetCommand@2
  inputs:
    restoreSolution: '**/*.sln'

- task: XamarinAndroid@1
  inputs:
    projectFile: '**/*droid*.csproj'
    outputDirectory: '$(outputDirectory)'
    configuration: '$(buildConfiguration)'

- task: AndroidSigning@3
  inputs:
    apkFiles: '$(outputDirectory)/*.apk'
    apksign: true
    apksignerKeystoreFile: '$(build.sourcesDirectory)/pockeystore.keystore'
    apksignerKeystorePassword: 'pockeystore'
    apksignerKeyPassword: 'pockeystore'
    zipalign: false

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(outputDirectory)'_

Please help me to setup keystore file path.

Joy
Innovation Lead

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4b1fbcd8-d799-879e-d672-9dee164401ef
* Version Independent ID: 7208d03d-9042-7753-ab4d-d1ad8e99ef1d
* Content: [Android signing build and release task](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/android-signing?view=vsts)
* Content Source: [docs/pipelines/tasks/build/android-signing.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/build/android-signing.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by joychandru** [comment]
I have upload my android keystore file in Library-> SecureFiles Section. Then i try to use it in Build Task but its showing error message Job Job1: Step input secureFile references secure file pockeystore.keystore which could not be found. The secure file does not exist or has not been authorized for use. For authorization details, refer to https://aka.ms/yamlauthz.  
My Yaml script is:
# Xamarin.Android
# Build a Xamarin.Android project.
# Add steps that test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xamarin

pool:
  vmImage: 'macOS 10.13'

variables:
  buildConfiguration: 'Release'
  outputDirectory: '$(build.binariesDirectory)/$(buildConfiguration)'

steps:
- task: NuGetToolInstaller@0

- task: NuGetCommand@2
  inputs:
    restoreSolution: '**/*.sln'

- task: XamarinAndroid@1
  inputs:
    projectFile: '**/*droid*.csproj'
    outputDirectory: '$(outputDirectory)'
    configuration: '$(buildConfiguration)'

- task: DownloadSecureFile@1
  inputs:
    secureFile: 'pockeystore.keystore'

- task: AndroidSigning@3
  inputs:
    apkFiles: '$(outputDirectory)/*.apk'
    apksign: false
    zipalign: false
    #apksignerKeystoreFile: 'pockeystore.keystore' 
    #apksignerKeystorePassword: 'pockeystore'
    #apksignerKeyPassword: 'pockeystore'
   
- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(outputDirectory)'

**Comment by DavidStaheli** [comment]
Keep-alive

**Comment by davidstaheli** [comment]
@joychandru thank you for reporting this and apologies for the confusion.  The Android Signing docs have been updated to address this and will be live within a couple of days.  If you still face the problem that the secure file "has not be authorized for use", please visit https://aka.ms/yamlauthz or click on the secure file and set it to be authorized for use by all pipelines:

![image](https://user-images.githubusercontent.com/1767415/60728667-e1e8ce00-9f0e-11e9-8d38-acaac582aa16.png)

**Comment by aaRopi** [comment]
Hi @davidstaheli !

I have a similar issue, where the builds are (I think) not being signed. I checked "Pipeline permissions" on the "Secure files" tab, and tried turning it on. But it is always turned back to off. 

Strangely, when I change the setting, the "Save"-button (can be seen in your screenshot) does not turn on. This is even though I am the administrator of my project (since I created it).

Do you experience the same issue?

**Comment by AbhiAbzs** [comment]
> Hi @davidstaheli !
> 
> I have a similar issue, where the builds are (I think) not being signed. I checked "Pipeline permissions" on the "Secure files" tab, and tried turning it on. But it is always turned back to off.
> 
> Strangely, when I change the setting, the "Save"-button (can be seen in your screenshot) does not turn on. This is even though I am the administrator of my project (since I created it).
> 
> Do you experience the same issue?

I'm also experiencing the same issue, even though I have turned on the pipeline permission.
Although this works when I use the classical mode for signing the apk.
![image](https://user-images.githubusercontent.com/29309508/73660362-0b90f000-46be-11ea-9395-8fa2afde2c87.png)

![image](https://user-images.githubusercontent.com/29309508/73660478-45fa8d00-46be-11ea-952a-4ac79d0a912e.png)
