### ISSUE TITLE
Two different entries for "Command" argument

### ISSUE THREAD

**Issue by gsacavdm** [MicrosoftDocs/vsts-docs#2002]
There are two different entries for "Command" in the Arguments section. Their descriptions are very different and one is required whereas the other is not.

Command: (Optional) Command to run in the Docker container. For example, if the image contains a simple Python Flask web application you can specify 'python app.py' to launch the web application.

Command: (Required) Docker command to execute, with arguments. For example, 'rmi -f image-name' to force remove an image.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d9dbf88-7e55-d427-145e-d36b04fb197f
* Version Independent ID: a3f30c00-817c-9c05-7a57-3f2bf618821e
* Content: [Docker](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/docker?view=vsts)
* Content Source: [docs/pipelines/tasks/build/docker.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/build/docker.md)
* Product: **devops**
* GitHub Login: @erickson-doug
* Microsoft Alias: **dastahel**

**Comment by sallespro** [comment]
confusing. i would like to attach to a network.

**Comment by gedeh** [comment]
Anyone confused by this doc, see https://github.com/Microsoft/azure-pipelines-tasks/blob/master/Tasks/DockerV1/containerbuild.ts for the code. It doesn't seems taking any much parameter as listed above. For example _Build Arguments_ doesn't seems working at all. Instead, use:
{{arguments:
  --build-args ARGUMENT_NAME=argument-value}}

**Comment by shashankbarsin** [comment]
Thanks for reporting this! We have updated the input labels and have done a completely rewrite for the documentation of this task.
