### ISSUE TITLE
Lacking documentation on "Action" argument

### ISSUE THREAD

**Issue by gsacavdm** [MicrosoftDocs/vsts-docs#2003]
The "Action" argument is listed as required yet it's not covered anywhere this documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d9dbf88-7e55-d427-145e-d36b04fb197f
* Version Independent ID: a3f30c00-817c-9c05-7a57-3f2bf618821e
* Content: [Docker](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/docker?view=vsts)
* Content Source: [docs/pipelines/tasks/build/docker.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/build/docker.md)
* Product: **devops**
* GitHub Login: @erickson-doug
* Microsoft Alias: **dastahel**

**Comment by shashankbarsin** [comment]
@gsacavdm thanks for reporting this issue! We have updated the documentation to reflect YAML input names, required/optional status and the default values for all these inputs.
