### ISSUE TITLE
Checkout submodules - relative path didn't work

### ISSUE THREAD

**Issue by Robbos** [MicrosoftDocs/vsts-docs#2007]
The documentation says:
git submodule add /../../submodule.git mymodule
but I think it should be:
git submodule add ../../submodule.git mymodule

When I tried the first command I got this error:
fatal: repository '/../../ProjectName/_git/SubModuleName' does not exist

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 41d4fcf8-3fd9-27b5-89e5-a026cc4a2b6a
* Version Independent ID: 76481ffb-aec5-50cd-6cdd-9e53c59e2933
* Content: [Build pipeline source repositories](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/repository?view=vsts)
* Content Source: [docs/pipelines/build/repository.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/build/repository.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by olaeld** [comment]
I am facing the same challenge.
