### ISSUE TITLE
This article doesn't make sense

### ISSUE THREAD

**Issue by ravensorb** [MicrosoftDocs/vsts-docs#2010]
You recommend not to check the PAT key into source control and yet the only way for the PAT key to work correctly is to add it into a config file.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a1a158fb-d1e3-a0d9-492e-3f78dde5d97c
* Version Independent ID: 71055426-3ba1-27f3-11db-cadb688ae123
* Content: [Use dotnet with Azure DevOps Services feeds](https://docs.microsoft.com/en-us/azure/devops/artifacts/nuget/dotnet-exe?view=vsts)
* Content Source: [docs/artifacts/nuget/dotnet-exe.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/artifacts/nuget/dotnet-exe.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by kumaranbsundar** [comment]
Agreed. Doesn't make any sense. I cannot find any valid article on how to restore the Azure Artifacts nuget package via command line on a build server. Every article out there points to using Visual Studio and Interactive mode to authenticate and pull the packages. How do we automate this process in CI server?

**Comment by alexmullans** [comment]
Using the old method, you'd want to securely store that token somewhere in your build system and then construct your nuget.config on the server.

However, there's now an easier way to do this with the Azure Artifacts Credential Provider. I've updated the doc with the new guidance.

**Comment by kumaranbsundar** [comment]
@alexmullans, thx! I am interested to know the setup for non-interactive scenario like in build servers on Linux. Following this article now i am able to download and setup the credential provider from here https://raw.githubusercontent.com/Microsoft/artifacts-credprovider/master/helpers/installcredprovider.sh

I have also setup these two env variables..
NUGET_CREDENTIALPROVIDER_SESSIONTOKENCACHE_ENABLED
VSS_NUGET_EXTERNAL_FEED_ENDPOINTS

However "dotnet restore" still could not download my packages from my private vsts feed. I am pretty sure it is not searching from my private feed. On my laptop i can add sources via "nuget sources" command. How do i add sources to the nuget source list on linux?

**Comment by kumaranbsundar** [comment]
okay i did add a local nuget.config and have specified the source. However I don't want to specify my credentials in there because this will be checked-in. I was hoping to pass the credentials using the environment variables specified here - https://github.com/Microsoft/artifacts-credprovider#environment-variables
However setting it doesn't seem to have any effect. "dotnet restore" now hits my private feed but returns a 401. Doesn't the cross platform credential provider not take the credentials from the ENV variable?

**Comment by kumaranbsundar** [comment]
To add more context, I am running dotnet restore inside docker as part of my build pipeline. 
Here is the Docker File....
FROM microsoft/dotnet:2.1-sdk AS build-env 
ENV NUGET_CREDENTIALPROVIDER_SESSIONTOKENCACHE_ENABLED true
ENV VSS_NUGET_EXTERNAL_FEED_ENDPOINTS {"endpointCredentials": [{"endpoint":"https://xxx/_packaging/xxx/nuget/v3/index.json","username":"optional","cleartextpassword":"xxx"}]}
WORKDIR /app
COPY ./src/*.csproj .
RUN wget -qO- https://raw.githubusercontent.com/Microsoft/artifacts-credprovider/master/helpers/installcredprovider.sh | bash
COPY ./NuGet.Config /root/.nuget/NuGet/

RUN dotnet restore

The restore fails with this error 
/usr/share/dotnet/sdk/2.1.401/NuGet.targets(114,5): error : Unable to load the service index for source https://xxxx.pkgs.visualstudio.com/_packaging/xxxx/nuget/v2/index.json. [/app/xxxx.csproj]
/usr/share/dotnet/sdk/2.1.401/NuGet.targets(114,5): error :   Response status code does not indicate success: 401 (Unauthorized). [/app/xxxx.csproj]

Here is my nuget.config file
<?xml version="1.0" encoding="utf-8"?>
<configuration>
    <packageSources>
        <add key="xxxxx" value="https://xxxxx.pkgs.visualstudio.com/_packaging/xxxx/nuget/v3/index.json" />
    </packageSources>
</configuration>

**Comment by kumaranbsundar** [comment]
Here is my nuget.config file.....

<?xml version="1.0" encoding="utf-8"?>
<configuration>
    <packageSources>
        <add key="xxxxx" value="https://xxxxx.pkgs.visualstudio.com/_packaging/xxxxx/nuget/v3/index.json" />
    </packageSources>
</configuration>

**Comment by alexmullans** [comment]
Ah, sorry, I've conflated a few things. Use "password" instead of "cleartextpassword" in your Dockerfile. cleartextpassword is something specific to the nuget.config file, which we're bypassing altogether by using the Credential Provider.

**Comment by elbatk** [comment]
I'm closing this issue as it's been over a month. @alexmullans let me know if you think another doc update (it looks like you've already mae one) should come out of this.

**Comment by ravensorb** [comment]
I am curious what additional info is needed?  I think a number of us are running into the same issue -- how to use a PAT token without using some sort of credential store in Azure.

**Comment by alexmullans** [comment]
@ravensorb yeah - you're hitting a weak spot in our documentation - sorry about that. I've queued a feature on our internal backlog (hoping to get to it in December, but may slip to January with holidays coming up) to ensure we've clearly documented using authenticated feeds in Docker containers.
