### ISSUE TITLE
Update for Azure Dev?

### ISSUE THREAD

**Issue by MarcRohde** [MicrosoftDocs/vsts-docs#2011]
The second image when connecting to dev.azure.com above doesn't match what project appears to be expecting.  I have tried dozens of permutations of dev.azure.com/myorg with different directory structures and non-appear to work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4f6edd47-46d7-ab0d-db47-d73bc45d6b43
* Version Independent ID: 6ac2ae49-0bd0-2c28-fc87-7f034dd96443
* Content: [Create your backlog and tasks using Project - Azure Boards and TFS](https://docs.microsoft.com/en-us/azure/devops/boards/backlogs/office/create-your-backlog-tasks-using-project?view=vsts&tabs=office-365)
* Content Source: [docs/boards/backlogs/office/create-your-backlog-tasks-using-project.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/boards/backlogs/office/create-your-backlog-tasks-using-project.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@MarcRohde - Apologies for any confusion. When connecting to Azure DevOps Services, you need to follow this procedure: 

(1) Choose **Servers...**, (2) choose **Add...**, (3) enter the URL of your Azure Boards organization, (4) check that the preview matches the URL that you entered, and then choose **OK**.
![image](https://user-images.githubusercontent.com/10856840/46757522-424c2700-cc7f-11e8-9bbf-e6a1a0cccf50.png)

I'm updating the topic to clarify. Please feel free to reopen this issue if it doesn't resolve your problem - or contact technical support.
