### ISSUE TITLE
Why should I use script-based commands in YAML?

### ISSUE THREAD

**Issue by atrauzzi** [MicrosoftDocs/vsts-docs#2012]
The documentation on this page suggests that I use script based commands in YAML builds.  I don't really have a problem with this advice, but I'm curious as to why.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d9dbf88-7e55-d427-145e-d36b04fb197f
* Version Independent ID: a3f30c00-817c-9c05-7a57-3f2bf618821e
* Content: [Docker](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/docker?view=vsts)
* Content Source: [docs/pipelines/tasks/build/docker.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/build/docker.md)
* Product: **devops**
* GitHub Login: @erickson-doug
* Microsoft Alias: **dastahel**

**Comment by azooinmyluggage** [comment]
@atrauzzi 
You can use either the built-in Docker task or script. You can even use a combination. For example:
Use Docker task to login to ACR by using Azure Service connection (no need to manage) user id password of ACR as variables. And then invoke a script.

The Docker task helps in getting Docker build and push done by selecting a couple of options.  We are working on adding deeper support for Docker and Kubernetes in our tasks and if you want to know more let me know. We are looking for customers who can give us early feedback.

**Comment by atrauzzi** [comment]
Well, that doesn't so much answer my question though.

![image](https://user-images.githubusercontent.com/115199/51502764-25a2ad80-1d9d-11e9-872d-bf3f676dd996.png)

I want to know why this is suggested.
