### ISSUE TITLE
witadmin

### ISSUE THREAD

**Issue by nirnaybansal** [MicrosoftDocs/vsts-docs#2013]
On other URL(https://docs.microsoft.com/en-us/azure/devops/reference/witadmin/witadmin-customize-and-manage-objects-for-tracking-work?view=tfs-2018) it is written that :
The witadmin command-line tool is not supported on Azure DevOps Services. Instead, you use inherited processes.

But here it says it is supported.

My witadmin is not working for Azure DevOps project. Please confirm.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b7617be-b5a7-5e1c-873d-e541e9382376
* Version Independent ID: 3c286b88-d74f-88eb-0b6d-aa2388f1643b
* Content: [Customize the layout of the work item web form - Azure DevOps & TFS](https://docs.microsoft.com/en-us/azure/devops/reference/customize-wit-form?view=vsts)
* Content Source: [docs/reference/customize-wit-form.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/reference/customize-wit-form.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@nirnaybansal - Apologies for any confusion. The witadmin tool is not supported in anyway on Azure DevOps Services (formerly known as Visual Studio Team Services). I'm updating the topic to reflect this to make more clear.
