### ISSUE TITLE
Pull Request Secret Usage

### ISSUE THREAD

**Issue by gtbuchanan** [MicrosoftDocs/vsts-docs#2015]
I can't seem to find any docs on secret usage in pull requests. Other build agents, such as [Travis CI](https://docs.travis-ci.com/user/pull-requests/#pull-requests-and-security-restrictions), prevent the usage of encrypted variables in pull requests for security reasons.

I see from these docs that the secret variable is masked in the Pipelines output window, but is there anything keeping pull requests from using the secrets?

Just making sure a malicious user can't submit a pull request that exposes the secret externally or uses it in another unapproved way.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd7e0bd3-1f7d-d7b6-cc72-5ef63c31b46a
* Version Independent ID: dae87abd-b73d-9120-bcdb-6097d4b40f2a
* Content: [Pipeline variables - Azure Pipelines & TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=vsts&tabs=yaml%2Cbatch)
* Content Source: [docs/pipelines/process/variables.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/variables.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by gtbuchanan** [comment]
I found the information I was looking for here:

https://docs.microsoft.com/en-us/azure/devops/pipelines/build/ci-public?view=vsts&tabs=github#validate-contributions-from-forks

![image](https://user-images.githubusercontent.com/715687/46701302-e3d26a80-cbe4-11e8-82b1-3ef59db211d7.png)

Perhaps a brief note in the secrets section and/or link to this info would suffice?

**Comment by DavidStaheli** [comment]
Hi Taylor.  Apologies that this information wasn't immediately clear.  Great suggestion to add a note/link in the "Secret variables" section.  That has been done and should be live later today.  Thanks a lot!
