### ISSUE TITLE
Does not work on selfhosted

### ISSUE THREAD

**Issue by lomholdt** [MicrosoftDocs/vsts-docs#2016]
Maybe it should be noted that this does not work out of the box if HipChat is self hosted.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2cbac8bb-754d-600d-9626-d29ba57dbd9e
* Version Independent ID: 20f6fea6-cbaa-8143-f5d3-ed45c5773001
* Content: [HipChat with Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/service-hooks/services/hipchat?view=vsts)
* Content Source: [docs/service-hooks/services/hipchat.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/service-hooks/services/hipchat.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by elbatk** [comment]
Hey @lomholdt , these service hooks docs are getting refreshed right now so I'll add this to the list of todos, thank you!
