### ISSUE TITLE
Security permissions changed

### ISSUE THREAD

**Issue by lywyn** [MicrosoftDocs/vsts-docs#2017]
Section on creating PAT token has wrong permission

4. For the scope select Agent Pools (read, manage) and make sure all the other boxes are cleared. If it's a deployment group agent, for the scope select **Deployment group (read, manage)** and make sure all the other boxes are cleared.

There is no permission Deployment Group, this may have been renamed to Machine Group (Read & manage)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43799c5d-2f13-cc76-a1c0-a3f850e16d4e
* Version Independent ID: 97a5b73f-faf7-f9c0-9269-fc79984616d6
* Content: [Deploy a build and release agent on Windows](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/v2-windows?view=vsts)
* Content Source: [docs/pipelines/agents/v2-windows.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/agents/v2-windows.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by RoopeshNair** [comment]
Documentation is correct, it the UI that has the bug. I have logged a bug to track this internally. Thanks for reporting it.
