### ISSUE TITLE
Permissions Missing for Most VSTS management pages

### ISSUE THREAD

**Issue by LouMM** [MicrosoftDocs/vsts-docs#2018]
**Issue(s)**
- Most pages in the documentation for VSTS (Azure Dev OPs), do not provide information on which Permissions are required to perform the operations. 
- The UI for VSTS does not show operations/tasks if end-users do not have access or permissions to perform the operations. Since this is the case, the user spends time searching around in the VSTS UI to try and follow the documentation, but ultimately just thinks the documentation is out of date. 
- Each documentation page , at the top of the page, should provide details on required permissions, and a link to how to check your permissions and role. This will prevent people from wasting time from reading the article only to find out they can't even find/see the operations or workflow.

**Comment by steved0x** [comment]
@LouMM Thank you for this feedback, I have added this to some topics ([here](https://docs.microsoft.com/en-us/azure/devops/repos/git/git-tags?view=vsts&tabs=new-nav#create-tag) is one example) and I agree, we should add it to more. I am passing this along. Do you have a specific area where you are being blocked, if so, I can try and help you with the required permissions for that area?
