### ISSUE TITLE
icon.png not consistent with logo.png

### ISSUE THREAD

**Issue by StevenTCramer** [MicrosoftDocs/vsts-docs#202]
In the vss-extension.json the following line:
"path": "images/logo.png", "addressable": true
should be
"path": "images/icon.png", "addressable": true
To be consistent

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 14955ee9-29f2-46fe-3a8d-a42666f53ffc
* Version Independent ID: 5d417cd0-a671-ee30-8fca-5f8b0addd328
* [Content](https://docs.microsoft.com/en-us/vsts/extend/get-started/node)
* [Content Source](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/extend/get-started/node.md)
* Service: unspecified

**Comment by elbatk** [comment]
Ah, great catch @StevenTCramer , implementing that change now!
