### ISSUE TITLE
Incomplete sentence

### ISSUE THREAD

**Issue by kimbleyGriffin** [MicrosoftDocs/vsts-docs#2021]
[Enter feedback here]  Missing the remainder of the last sentence, i.e., "To initate web-based exploratory testing for a user story, you need to install **the Exploratory testing ,** see Exploratory test your web app directly in your browser."

What exactly is it that you need to install to initiate web-based exploratory testing for a user story?  Something is missing from the end of this sentence.

------------------------------------------------------------------------------------------------------------
Related articles
Use inline tests for lightweight traceability and to manage manual tests for user stories or other backlog items that they support. To learn more about test case management, see Create manual tests. 
...
Additional ways you can quickly add linked items and objects to user stories from the Kanban board:
Add inline tasks
Create a new branch, drive Git development 
To initate web-based exploratory testing for a user story, you need to install <b>the Exploratory testing , </b> see Exploratory test your web app directly in your browser.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 91132cbe-8fd9-d73e-a1b7-d122022c9413
* Version Independent ID: a0dd8148-d039-af4b-ef5d-735fa32a3fb3
* Content: [Add, run, and update inline tests - Azure Boards and TFS](https://docs.microsoft.com/en-us/azure/devops/boards/boards/add-run-update-tests?view=vsts&tabs=new-nav)
* Content Source: [docs/boards/boards/add-run-update-tests.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/boards/boards/add-run-update-tests.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@kimbleyGriffin - Thank you for your feedback. I'm updating the text to read: 
To initate web-based exploratory testing for a user story, you need to install the [Test & Feedback Marketplace extension](https://marketplace.visualstudio.com/items?itemName=ms.vss-exploratorytesting-web). For details, see [Install the Test & Feedback extension](../../test/perform-exploratory-tests.md).
