### ISSUE TITLE
Typo: design > designed

### ISSUE THREAD

**Issue by kimbleyGriffin** [MicrosoftDocs/vsts-docs#2022]
[Enter feedback here]
"Test iterations are design to support data-driven scenarios, not workflow-driven scenarios. From a best practice perspective, if you have two test scenarios where the workflows are different, consider creating separate test cases."

Should be...

"Test iterations are **designed** to support data-driven scenarios, not workflow-driven scenarios. From a best practice perspective, if you have two test scenarios where the workflows are different, consider creating separate test cases." 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2cf72265-156c-de8c-d729-ba7b3b90193d
* Version Independent ID: 1a0c7272-6d36-6036-06cf-5801b55e2f70
* Content: [Create manual tests - Azure DevOps and Team Foundation Server TestTools](https://docs.microsoft.com/en-us/azure/devops/test/create-test-cases?view=vsts)
* Content Source: [docs/test/create-test-cases.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/test/create-test-cases.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by steved0x** [comment]
@kimbleyGriffin Thanks for letting us know, I have fixed this and it should be live soon.

**Comment by alexhomer1** [comment]
Thank you for your feedback. I will update the topic to include your recommendations.
