### ISSUE TITLE
Can this be done programmatically?

### ISSUE THREAD

**Issue by teejam2** [MicrosoftDocs/vsts-docs#2027]
We would like to regularly save all of our project's data for back up and disaster recovery purposes. How best should we achieve this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 292b98f0-e640-9f76-35f9-4392655b4a73
* Version Independent ID: a794807b-ab76-ae45-1358-7031df22abba
* Content: [Save project data - Azure DevOps & TFS](https://docs.microsoft.com/en-us/azure/devops/organizations/projects/save-project-data?view=vsts)
* Content Source: [docs/organizations/projects/save-project-data.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/projects/save-project-data.md)
* Product: **devops**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @teejam2 thanks for posting your question. I'm looking into this and will be in touch as soon as I receive guidance.

**Comment by chcomley** [comment]
@teejam2 Thanks for your patience on this - Microsoft already performs all the appropriate backups in case of a disaster. Please see the Data Protection Overview for more information: https://docs.microsoft.com/en-us/azure/devops/articles/team-services-security-whitepaper?view=vsts. I'll be adding this information to this topic you commented on. Thanks so much.

**Comment by teejam2** [comment]
Hi @chcomley I agree with you, but my workplace is insisting that an on-prem back-up is required

**Comment by chcomley** [comment]
@teejam2 Azure DevOps does not support comprehensive customer-available backups of all Azure DevOps Organization data in any meaningful way. That data is spread across multiple multi-tenant Azure SQL Databases, multiple multi-tenant Azure Storage accounts, and so forth. Depending on your specific requirements, you can manually back up subsets of important data. For example, you could set up an automated process to mirror important Git repositories to an on-premises server. If you need comprehensive backups of all data, you’ll need to use our on-premises product.
