### ISSUE TITLE
Need link to YAML documentation

### ISSUE THREAD

**Issue by CoolDadTx** [MicrosoftDocs/vsts-docs#2028]
This is really a quick start guide for YAML. There doesn't seem to be any link to the actual YAML documentation that people are going to need to do anything beyond the most simplistic hello world app.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 483dcb1c-1a89-2b20-4cf2-abd3ae88d9ed
* Version Independent ID: dc4722ed-5a4b-26ec-e7d5-a149bf6e79a7
* Content: [Building .NET Core projects with Azure Pipelines and TFS - Azure Pipelines & TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/languages/dotnet-core?view=vsts&tabs=yaml)
* Content Source: [docs/pipelines/languages/dotnet-core.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/languages/dotnet-core.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by CoolDadTx** [comment]
I do see the reference material under References on the side bar now and it does list the available tasks so I guess this is the official replacement. We need a link to this within this topic though.

**Comment by eriawan** [comment]
There is YAML schema under Reference on the left sidebar. This is the link: https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=vsts

**Comment by CoolDadTx** [comment]
Yes but no place in the quickstart does it even mention the reference.  Hence people have to go find it themselves.

**Comment by eriawan** [comment]
@CoolDadTx 

I understand. Thank you for your suggestions! It makes sense. 
Ok, I will try to submit PR to update this page to add link to YAML schema reference.
