### ISSUE TITLE
Template expressions only work if they start and end the line

### ISSUE THREAD

**Issue by CoolDadTx** [MicrosoftDocs/vsts-docs#2030]
This was an ongoing GitHub discussion for a while. The current (Oct 2018) implementation of template expressions only work if the entire line is wrapped in a template expression. If the line doesn't start with a template expression then it won't be evaluated as such. 

This has been resolved in an update that is supposed to go out soon and should be available for all accounts from what the GitHub poster says. https://github.com/Microsoft/azure-pipelines-agent/issues/1772

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6724abea-bbdc-bf66-ed5e-3214fa6c3e66
* Version Independent ID: 4f8dab21-3f0e-da32-cc0e-1d85c13c0065
* Content: [Job and step templates - Azure Pipelines & TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/templates?view=vsts#template-expressions)
* Content Source: [docs/pipelines/process/templates.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/templates.md)
* Product: **devops**
* GitHub Login: @vtbassmatt
* Microsoft Alias: **alewis**

**Comment by vtbassmatt** [comment]
Thanks! This change is coming soon enough that I don't want to document the current (poor) behavior.
