### ISSUE TITLE
Cannot reference external scripts

### ISSUE THREAD

**Issue by CoolDadTx** [MicrosoftDocs/vsts-docs#2031]
An important limitation of the current implementation (https://github.com/Microsoft/azure-pipelines-yaml/issues/6) is that you cannot reference external files from within a step template. In a regular YAML file you can have some logic in an external script (e.g. PowerShell) and call it from within YAML. This doesn't work if the YAML is a step template in another repository.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6724abea-bbdc-bf66-ed5e-3214fa6c3e66
* Version Independent ID: 4f8dab21-3f0e-da32-cc0e-1d85c13c0065
* Content: [Job and step templates - Azure Pipelines & TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/templates?view=vsts#template-expressions)
* Content Source: [docs/pipelines/process/templates.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/templates.md)
* Product: **devops**
* GitHub Login: @vtbassmatt
* Microsoft Alias: **alewis**

**Comment by vtbassmatt** [comment]
This is a product request, not really a docs issue. We're looking into some ideas on doing this. Keeping around a docs bug isn't going to influence our decision, though, so I'll go ahead and close this.
