### ISSUE TITLE
Don't have ability to export/import process?

### ISSUE THREAD

**Issue by cdietschrun** [MicrosoftDocs/vsts-docs#2033]
I follow this guide and I don't see the import or export ability that we'd really like to experiment with. Do I need to do anything else to allow this to happen? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f3f646c2-3c97-597c-c452-5f12f20c9889
* Version Independent ID: 9481bb73-bc5f-2666-b48c-3fca017ef536
* Content: [Customize a process to import using Hosted XML - Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/organizations/settings/work/import-process/customize-process?toc=%2Fazure%2Fdevops%2Freference%2Ftoc.json&bc=%2Fazure%2Fdevops%2Freference%2Fbreadcrumb%2Ftoc.json&view=vsts&tabs=new-nav)
* Content Source: [docs/organizations/settings/work/import-process/customize-process.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/settings/work/import-process/customize-process.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@cdietschrun - Thank you for your inquiry and apologies for the delay in response. The Hosted XML process model is only available to select Azure DevOps Services. 

@danhellem - Is the Hosted XML process model still available for an organization to sign up for use?
