### ISSUE TITLE
The API URI is outdated

### ISSUE THREAD

**Issue by hjlarrea** [MicrosoftDocs/vsts-docs#2038]
In the second code sample the API URI is refered to as: "https://{0}.visualstudio.com/{1}/_apis/repos/git/repositories/{2}/pullrequests/{3}/statuses?api-version=4.0-preview"

And it should be: "https://dev.azure.com/{0}/{1}/_apis/git/repositories/{2}/pullRequests/{3}/statuses?api-version=4.1-preview.1"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 915c7aa9-0969-912b-bbc4-a2b0bf9b1533
* Version Independent ID: 6a97a5e8-8397-be98-5528-70d20e8fbed8
* Content: [Use Azure Functions to create custom branch policies - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/create-pr-status-server-with-azure-functions?view=vsts)
* Content Source: [docs/repos/git/create-pr-status-server-with-azure-functions.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/repos/git/create-pr-status-server-with-azure-functions.md)
* Product: **devops**
* GitHub Login: @steved0x
* Microsoft Alias: **yohasna**

**Comment by steved0x** [comment]
@hjlarrea I just fixed the URL part yesterday, but both URL formats should work (see [Can I still use visualstudio.com?](https://docs.microsoft.com/en-us/azure/devops/user-guide/what-happened-vsts?view=vsts#can-i-still-use-visualstudiocom))

I will fix the `api-version` today as I have some other changes going out. Thanks for letting us know!

**Comment by steved0x** [comment]
I just pushed the fix for this, it should be live later today. Thanks for letting us know!

**Comment by hjlarrea** [comment]
Thanks guys! Glad to help!
