### ISSUE TITLE
Gaps Between YAML Builds and Visual Designer: Linking Work Items?

### ISSUE THREAD

**Issue by tannerwatson** [MicrosoftDocs/vsts-docs#2039]
When the documentation was in github there was a section which described the feature gaps of YAML builds. Is this documented somewhere else now, or were all gaps filled in? Specificly, one of these was the inability to link Work Items to builds. Is this still the case?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 38f7a23b-ebd4-af3e-68a2-275f7e45c33e
* Version Independent ID: f552a18c-ba29-00d4-03b6-254d7556d319
* Content: [Create your first pipeline - Azure Pipelines & TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/get-started-yaml?view=vsts)
* Content Source: [docs/pipelines/get-started-yaml.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/get-started-yaml.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by vtbassmatt** [comment]
Work item linking still isn't offered in YAML. It's on our backlog, but I don't have a concrete date where we plan to deliver it.

**Comment by chudson121** [comment]
looking forward to this feature!
