### ISSUE TITLE
Capabilities

### ISSUE THREAD

**Issue by tonuv** [MicrosoftDocs/vsts-docs#2042]
Is it possible to request capabilities based on greater than type of a comparison, for example OS version > 10.0.14939?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 47625b86-abd5-ee15-6d61-8bcf81861b96
* Version Independent ID: be9a6174-a69b-7aed-d584-5f602fcc5eb4
* Content: [Build and Release Agents - Azure Pipelines & TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/agents?view=vsts#capabilities)
* Content Source: [docs/pipelines/agents/agents.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/agents/agents.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by vtbassmatt** [comment]
Demands are limited to existence and equality.
