### ISSUE TITLE
DevOps TestCase "Associated Automation" is still grayed for MSTestV2, and i cant find some workaround for Selenium tests under MSTest framework.

### ISSUE THREAD

**Issue by jimicze** [MicrosoftDocs/vsts-docs#2043]
MS Docs:
[associate-automated-test-with-test-case](https://docs.microsoft.com/cs-cz/azure/devops/test/associate-automated-test-with-test-case?view=vsts)

```
Q: What types of tests are supported?
A: These are the limitations for each type of test:
- Coded UI test, Selenium tests, and unit tests written using Version 1 of the MSTest framework can be associated with a test case.
- Unit tests that use the.NET Core framework cannot be associated with a test case.
- Tests that use other test frameworks such as Version 2 of the MSTest framework, xUnit, nUnit, Chutzpah, and others cannot be associated with a test case.
- Associating ordered tests and generic tests may work, but running these tests is not supported.
```

_Originally posted by @jimicze in https://github.com/MicrosoftDocs/vsts-docs/issues/1516#issuecomment-428848105_

**Comment by alexhomer1** [comment]
Thank you for your feedback. I have passed this on to the product team for advice.

**Comment by PBoraMSFT** [comment]
@jimicze - support for associating MSTest v2 tests is available in the latest Visual Studio release (currently preview) - https://visualstudio.microsoft.com/vs/preview/
