### ISSUE TITLE
Why Hosted Agent not have administrator permission?

### ISSUE THREAD

**Issue by TerryFei** [MicrosoftDocs/vsts-docs#2044]
I try to install certificate with powershell command "Import-PfxCertificate". but It failed with error message "Access is denied. 0x80070005 (WIN32: 5 ERROR_ACCESS_DENIED)". seems it not run the command as administrator.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 99af681d-41ad-da15-0b72-08b5cd5a11ac
* Version Independent ID: 2fa0df36-a437-8cbb-b019-b49b31b1e116
* Content: [Microsoft-hosted agents for Azure Pipelines - Azure Pipelines & TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=vsts&tabs=yaml#capabilities-and-limitations)
* Content Source: [docs/pipelines/agents/hosted.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/agents/hosted.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by vtbassmatt** [comment]
Was this on a hosted agent?

**Comment by TerryFei** [comment]
Yes, I add a task to hosted agent job to install certificate.

**Comment by TerryFei** [comment]
in addition it works in hosted vs2017 agent, but not work in hosted agent.

**Comment by vtbassmatt** [comment]
Ah, OK. The Hosted agent is a little different - I don't think the build runs as admin there. We're not going to take a change in that image, as too many people depend on its quirks :(

**Comment by RehanSaeed** [comment]
So how can we install a certificate?

**Comment by vtbassmatt** [comment]
You probably can't on that pool. Is there any reason you can't use one of the newer pools, like VS2017 or VS2019?
