### ISSUE TITLE
Multiple configurations

### ISSUE THREAD

**Issue by tonuv** [MicrosoftDocs/vsts-docs#2045]
While the default variable for multiple configurations is separated by | (x86|x64) this documentation instructions to use ,
Also there is no multiconfigations options on options tab.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 29f86c97-f534-50ad-bfb1-a2cf78c7af94
* Version Independent ID: acea40e3-512b-4d9a-9389-71b8b24327be
* Content: [Visual Studio Build build and release task - Azure Pipelines & TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/visual-studio-build?view=vsts)
* Content Source: [docs/pipelines/tasks/build/visual-studio-build.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/build/visual-studio-build.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by evakili** [comment]
It seems that Multiple-configuration options moved to each phase options. Select phase in tasks tab and on the right hand side you can find the option under execution plan section.

**Comment by andyjlewis** [comment]
Thank you for reporting this issue. Apologies for the very delayed response. I've added this issue to our backlog.
