### ISSUE TITLE
Estimation and precision

### ISSUE THREAD

**Issue by GrumpyBusted** [MicrosoftDocs/vsts-docs#2054]
I am not sure if this is the right place for this comment, but here it goes.
In many estimation methodologies, estimates are given with uncertainty or precision. For example in "The Programmer's Oath", Robert "Uncle Bob" Martin makes us pledge to produce honest estimates and always include the precision of these, but yet I have not found a way to capture this on the Work items in TFS/VSTS/Azure DevOps.
Is there a way to capture this on the Work Items/Tasks?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 80aca099-85bb-85fd-72e7-bdcd9453f0b2
* Version Independent ID: 003e27ad-b6fe-0197-dd9d-5e8fe6e38af9
* Content: [Burndown guidance - Azure DevOps & TFS](https://docs.microsoft.com/en-us/azure/devops/report/dashboards/burndown-guidance?view=vsts)
* Content Source: [docs/report/dashboards/burndown-guidance.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/report/dashboards/burndown-guidance.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by danhellem** [comment]
you can revise your estimates on the task. If you are using the scrum template then you can update the remaining work as you learn and know more about the task. Agile template is simular but also provides an estimated work field. If it is important for you to capture estimated work down to the precision level for other work item types (users stories, bugs) you can always [add a custom field](https://docs.microsoft.com/en-us/azure/devops/organizations/settings/work/customize-process-field?view=vsts&tabs=new-nav).
