### ISSUE TITLE
Import and exporting repositories

### ISSUE THREAD

**Issue by propellor** [MicrosoftDocs/vsts-docs#2057]
May I suggest a guide on moving code from TFS or VSTS to devops?  I have a solution I'd like to migrate from TFS to devops and am not sure how to do it. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 527651eb-b068-313d-9a1f-78f5613b1d7a
* Version Independent ID: a8b55dcd-c261-5eed-edfc-6a4e74b2caee
* Content: [Add and manage projects to support collaboration on software development](https://docs.microsoft.com/en-us/azure/devops/organizations/projects/index?view=vsts)
* Content Source: [docs/organizations/projects/index.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/projects/index.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by steved0x** [comment]
@propellor If you are asking about a guide to migrate from on-premises TFS to Azure Devops Services (formerly known as VSTS), would this help you: [Migrate data from TFS to Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/articles/migration-overview?view=vsts)
