### ISSUE TITLE
Microsoft Docs Search is not working well for Azure DevOps topics

### ISSUE THREAD

**Issue by dburnison** [MicrosoftDocs/vsts-docs#2059]
For example, I am searching on " "Azure DevOps" Release "Azure Key Vault" Task " in Microsoft Docs and Bing. My goal is to get to https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-key-vault?view=vsts. This is the 1st or 2nd result in a Bing search, but I cannot find it when using search inside of Microsoft Docs. Something seems very broken if I have to use Bing instead of the built in search. 
Dave Burnison - dabu@microsoft.com

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c00c80cb-e1fa-8af1-25a7-0e1fd679b879
* Version Independent ID: 51baa23d-66da-3d19-ddc7-56c101e9e09d
* Content: [Feature overview - Azure DevOps Services & TFS](https://docs.microsoft.com/en-us/azure/devops/user-guide/alm-devops-features?toc=/azure/devops/user-guide/toc.json&view=vsts)
* Content Source: [docs/user-guide/alm-devops-features.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/user-guide/alm-devops-features.md)
* Product: **devops**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Appreciate the heads up, @dburnison. I've created a work item to address this.
