### ISSUE TITLE
Deploying dotNet core api app with docker fails when deploying multi container web app

### ISSUE THREAD

**Issue by kkho** [MicrosoftDocs/vsts-docs#2060]
Tried to deploy with dotnet core Project. Just a dummy app. Followed the recipe all the steps except step 3 (which does not find web app container that I created in azure portal) and tried to run web app wtih multi containers. Uploaded a docker compose script and got an error saying that the image was not found, also when I tried to deploy a container as a web app from acr. It did not even work, still got the same problem with image not found...

Running locally works and please fix this problem.

**Comment by shashankbarsin** [comment]
Marking the issue as stale and closing it as a link to the document being referenced wasn't provided
