### ISSUE TITLE
Plugin name

### ISSUE THREAD

**Issue by michazag** [MicrosoftDocs/vsts-docs#2073]
"Azure DevOps Services" doesn't appear under "Browse Repositories" in IntelliJ. I found a  "Visual Studio Team Services" plugin 
 however - hope this is the one

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b71f9c7b-a10e-4adc-22d0-58d4b40b35c8
* Version Independent ID: 90cda752-8667-2e9c-4ba9-5af1abbb63b8
* Content: [Get the IntelliJ IDEA Azure DevOps Services plug-in](https://docs.microsoft.com/en-us/azure/devops/java/download-intellij-plug-in?view=vsts)
* Content Source: [docs/java/download-intellij-plug-in.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/java/download-intellij-plug-in.md)
* Product: **devops**
* GitHub Login: @erickson-doug
* Microsoft Alias: **douge**

**Comment by andersoyvind** [comment]
That plugin is referenced at the top of the page: http://plugins.jetbrains.com/plugin/7981
I agree on the confusion, as I just did that myself.

**Comment by steved0x** [comment]
@michazag That is the right one, it looks like the renaming of things to "Azure DevOps Services" is not exactly in sync with one another. I will get this article updates to reflect the correct name and it should be live later today.

**Comment by michazag** [comment]
Thanks!
