### ISSUE TITLE
Given that I have downloaded the credential provider do I still need to make a personal access token?

### ISSUE THREAD

**Issue by kgreed** [MicrosoftDocs/vsts-docs#2074]
I managed to get 1 package into my package store but now get Access is denied when I try to add more. https://stackoverflow.com/questions/52772765/how-do-i-set-up-azure-dev-ops-to-build-dev-express-xaf-xpo-project

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab0a3735-a9b0-2ed7-f08f-5321f55f8c90
* Version Independent ID: 2153f6c0-def7-eed1-286d-5e61c9fcbec4
* Content: [Use NuGet with Azure DevOps Services feeds](https://docs.microsoft.com/en-us/azure/devops/artifacts/nuget/nuget-exe?view=vsts&tabs=new-nav)
* Content Source: [docs/artifacts/nuget/nuget-exe.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/artifacts/nuget/nuget-exe.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by kgreed** [comment]
OK, I don't need a PAT because I am using V3. However this page is linked to by "I am having trouble with authentication" on the "Connect to feed" dialog and it does not give me any troubleshooting steps on how to authenticate.

**Comment by elbatk** [comment]
Hi @kgreed , it looks like you got your issue figured out, great! I'm going to close this but I'm adding @alexmullans as he is working on redesigning that connect to feed dialog. Alex, also we may need to talk about auth troubleshooting, but what's new? :)
