### ISSUE TITLE
matrix - how do you have multiple variables?

### ISSUE THREAD

**Issue by johnnyreilly** [MicrosoftDocs/vsts-docs#2075]
Hi,

I work on [ts-loader](https://github.com/TypeStrong/ts-loader); a nodejs project that brings TypeScript and webpack together.  

We're just evaluating Azure Pipelines as it looks very promising indeed!  However, we've stumbled along the way and wanted to ask you for some help.  It's not obvious to me how to have multiple variables in a test matrix?  What I mean is, with ts-loader, we like to test building ts-loader with multiple versions of nodejs, and then test it against multiple versions of TypeScript. 

So for node 6 and 8 we'd like to test for the following versions of TypeScript:

  - typescript@next
  - typescript@3.0.1
  - typescript@2.9.2
  - typescript@2.8.1
  - typescript@2.7.1
  - typescript@2.6.1
  - typescript@2.5.2
  - typescript@2.4.1

This is fairly straightforward to do with Travis / AppVeyor:

https://github.com/TypeStrong/ts-loader/blob/master/.travis.yml
https://github.com/TypeStrong/ts-loader/blob/master/appveyor.yml

But we can't work out how you'd achieve the same with Azure Pipelines.  No doubt it's doable, it's just not clear what it would look like!

Can you help?  You can see our first cut of playing with Azure Pipelines here: https://github.com/TypeStrong/ts-loader/pull/856 - please feel free to hack on that if it helps.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 54bf6c2f-95c1-943d-26ae-d7099143bccf
* Version Independent ID: 0833bb55-1e54-6953-ee69-de6d191d2ec1
* Content: [Build and release jobs in Azure Pipelines and TFS - Azure Pipelines & TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/phases?tab=yaml&view=vsts&tabs=yaml#parallelexec)
* Content Source: [docs/pipelines/process/phases.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/phases.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment]
Thank you for your feedback. I have passed this on to the product team for advice.

**Comment by PBoraMSFT** [comment]
@DavidStaheli - feedback to improve the matrix strategy docs.

**Comment by DavidStaheli** [comment]
Hi @johnnyreilly.  Thanks a lot for posting this and for giving Azure Pipelines a try.  I'm sorry it didn't yet have the ideal approach to the matrix expansion that you need.  I'll close this issue in favor of the discussion happening in [your PR](https://github.com/TypeStrong/ts-loader/pull/856).  But please feel free to reopen this issue if we can provide additional help here.
