### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by jordanchang** [MicrosoftDocs/vsts-docs#2076]
Got this to work on a Mac after adding my Private Repo Url & a personal access token to the nuget.config file in my $HOME/.nuget/nuget folder.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a1a158fb-d1e3-a0d9-492e-3f78dde5d97c
* Version Independent ID: 71055426-3ba1-27f3-11db-cadb688ae123
* Content: [Use dotnet with Azure Artifacts feeds](https://docs.microsoft.com/en-us/azure/devops/artifacts/nuget/dotnet-exe?view=vsts)
* Content Source: [docs/artifacts/nuget/dotnet-exe.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/artifacts/nuget/dotnet-exe.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by elbatk** [comment]
Closing this as it looks like you've figured it out @jordanchang . Feel free to reach back out if you're still having issues.
