### ISSUE TITLE
Where is the help for bitbucket?

### ISSUE THREAD

**Issue by kgreed** [MicrosoftDocs/vsts-docs#2077]
This page mentions that there is some

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 15a9c9ac-02c4-839a-555b-8d9d22d08fab
* Version Independent ID: 259fcc03-e73d-2004-dfa6-067728a85981
* Content: [Import a Git repo into your project - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/import-git-repository?view=vsts)
* Content Source: [docs/repos/git/import-git-repository.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/repos/git/import-git-repository.md)
* Product: **devops**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by kgreed** [comment]
![image](https://user-images.githubusercontent.com/1795966/46923419-2374d880-d063-11e8-94d6-cc79e9a15b57.png)

**Comment by steved0x** [comment]
@kgreed Bitbucket is one of the providers from which we can import a Git repo, by pasting in the clone URL and the authentication in the import page. I personally haven't imported from a Bitbucket repository - if you've tried it, was there an issue in performing the import that could be addressed with some additional steps in the documentation?
