### ISSUE TITLE
what rights do the different access levels give?

### ISSUE THREAD

**Issue by kgreed** [MicrosoftDocs/vsts-docs#2078]
Does Stakeholder give better access than Basic?  This information or a link in it should be in this help.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 75aa416a-b842-77d0-e18a-bee7f7bf7205
* Version Independent ID: 65942145-45ca-48bb-6adc-c16bd662b80a
* Content: [Manage users and access in Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/manage-users-table-view?view=vsts&tabs=new-nav)
* Content Source: [docs/organizations/accounts/manage-users-table-view.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/accounts/manage-users-table-view.md)
* Product: **devops**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Thanks @kgreed, I've created a user story to add more information to the topic. To answer your question, no, stakeholder is never better than basic. Here's a link to compare features: https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fazure.microsoft.com%2Fen-us%2Fservices%2Fdevops%2Fcompare-features%2F&data=02%7C01%7CChrystal.Comley%40microsoft.com%7Cd50da26c85364f06690b08d632b88b17%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636752165522378811&sdata=jgD6VGmVqG5%2BoLQhXZRftFVrA21CUCdllLT62lfvzLU%3D&reserved=0

**Comment by kgreed** [comment]
Hi @chcomley  where is the user story?  The compare features link does not tell me anything about what rights a Basic user has.  The word Basic only appears at the very bottom of the page and I aren't sure it is in the same context.

**Comment by nschonni** [comment]
Think you're looking for https://docs.microsoft.com/en-ca/azure/devops/organizations/security/access-levels?toc=%2fazure%2fdevops%2fbilling%2ftoc.json&%3bbc=%2fazure%2fdevops%2fbilling%2fbreadcrumb%2ftoc.json&%3bview=vsts&view=vsts

**Comment by kgreed** [comment]
What is a VSTS User ?
Since VSTS Is devops then this is circular.
Do I need to have paid money to get basic access?

**Comment by kgreed** [comment]
In dev.azure.com/myorganisation/_settings/users   
Change access level
![image](https://user-images.githubusercontent.com/1795966/46978692-54b0df80-d11b-11e8-91d6-9329f0bd1ec5.png)

Visual Studio Subscriber is not mentioned in the access levels help Can it be?
Could the order of the combo box be changed to reflect the access level?

**Comment by chcomley** [comment]
@kgreed Please see _inline_:
What is a VSTS User? _There is only an Azure DevOps user, since VSTS is no longer the name of the product._
Since VSTS Is devops then this is circular. _Did you see VSTS mentioned mistakenly somewhere in our documentation? If so, please forward, thank you._
Do I need to have paid money to get basic access? _Five users who get Basic features can join your organization for free._
