### ISSUE TITLE
Run Task if Previous Task Ran

### ISSUE THREAD

**Issue by ahaleiii** [MicrosoftDocs/vsts-docs#208]
How would I set the condition to run a task only if a previous task ran, regardless of whether that task succeeded or failed? My specific use case relates to the Publish Test Results task. If the custom task which runs the tests fails, I still want to publish the results. However, if a task fails earlier and the test task never runs, I do not want to run this publish task.

What I think I will do in the meantime is set the publish task to run even if any other task failed, and would expect it to fail if the test task never runs.

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f151218-9a11-0078-e038-f96198a76143
* Version Independent ID: 09c4d032-62f3-d97c-79d7-6fbfd89910e9
* [Content](https://docs.microsoft.com/en-us/vsts/build-release/concepts/process/conditions)
* [Content Source](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/build-release/concepts/process/conditions.md)
* Service: unspecified

**Comment by andyjlewis** [comment]
Hi ahaleiii, I'm researching and will get back to you.

**Comment by andyjlewis** [comment]
Hi ahaleiii, you could use a logging command to set a custom variable from the task which runs the tests (https://docs.microsoft.com/en-us/vsts/build-release/concepts/definitions/build/variables?view=vsts&tabs=batch#set-in-script) and then check for the value of that variable in your publish test results task.

**Comment by ahaleiii** [comment]
I will look into this, thanks for getting back to me!

**Comment by MilanRaval** [comment]
@andyjlewis : "check for the value of that variable in your publish test results task." - Can you tell how to access user defined variable in custom condition ?
