### ISSUE TITLE
Any plans to support Pull request builds in YAML syntax?

### ISSUE THREAD

**Issue by RTodorov** [MicrosoftDocs/vsts-docs#2083]
At this point I don't know if this is still a limitation of the platform or if the documentation is outdated.

Do we already support pull request builds in YAML syntax? If not, are there any plans or any place I can follow up on this? It really doesn't make sense to have part of your pipeline automated, part you have to use the designer. Also, the PR flow is pretty basic for any pipeline I guess.

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5673ec1-c7d1-e0ac-043a-8fc3d5b226a9
* Version Independent ID: b4872831-51c0-6cf8-1c56-de20beb38a80
* Content: [Build pipeline triggers - Azure Pipelines & TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/triggers?view=vsts&tabs=yaml)
* Content Source: [docs/pipelines/build/triggers.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/build/triggers.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by vtbassmatt** [comment]
Coming in the next 3 weeks. It'll be documented once the feature ships.

**Comment by escalonn** [comment]
Shipped but not documented here or anywhere.

**Comment by vtbassmatt** [comment]
Shipped for a fraction of our customers, but not the majority. We roll features out in rings.

**Comment by nonameolsson** [comment]
Is this rollde out to all customers yet? I have specified it in my yml-file but I can't seem to get it to work.

**Comment by vtbassmatt** [comment]
@nonameolsson it's available everywhere. One gotcha is that new pipelines still set the "override PR triggers" flag in the UI. You have to turn that off to explicitly opt into YAML-based syntax. I'll make that clearer in the docs.

**Comment by binnisb** [comment]
Hey, the PR option in my azure-pipeline.yml doesn't seem to work. 
I've tested
```
pr:
- master
```
and
```
pr:
  branches:
    include:
    - master
```
and I have tried without the `pr` option but nothing works.
I made sure that under Triggers the checkbox is unchecked for overriding YAML config.

Any reason I can't get this working?

**Comment by binnisb** [comment]
I see you talk about "override PR triggers" in your previous comment. I can't seem to find that one under the "edit in visual designer" UI. Am I missing this option somewhere?

**Comment by vtbassmatt** [comment]
Sorry - override PR triggers in the UI only applies to GitHub repos. I'm assuming your code is in Azure Repos? I'm digging in to see if I can get a repro right now.

**Comment by binnisb** [comment]
Yes, repo in Azure. Thanks 👍

**Comment by vtbassmatt** [comment]
I can't repro this; PR triggers are working for me. Can you please file an issue over at [Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html) so the right people will take a look?

**Comment by nordquist** [comment]
> Coming in the next 3 weeks. It'll be documented once the feature ships.

Any news?

**Comment by vtbassmatt** [comment]
`pr` triggers in YAML work for non-Azure Repos repos. For Azure Repos, you must configure branch policy.

**Comment by nordquist** [comment]
> `pr` triggers in YAML work for non-Azure Repos repos. For Azure Repos, you must configure branch policy.

So what exactly was "coming in the next 3 weeks" ?

**Comment by vtbassmatt** [comment]
PR triggers for GitHub repos.
