### ISSUE TITLE
Conditionally Adding Branch Name to the Build Name

### ISSUE THREAD

**Issue by RehanSaeed** [MicrosoftDocs/vsts-docs#2085]
I'm trying to build a Docker image. I use the build name as the Docker image version. This is the build name I am currently using in my yml:

```
name: 1.0.$(BuildId)-$(SourceBranchName)
```

For the foo branch, build ID 5, this produces the name:

```
1.0.5-foo
```

If it's the master branch though, I don't want `-master` on the end of the name. I would like the build name to be:

```
1.0.5
```

Is this possible? I have seen [expressions](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/expressions?view=vsts) used in the yaml and am trying to understand if they work here too and if so, how?

**Comment by shashankbarsin** [comment]
@RehanSaeed you can achieve this by having two scripts, each with a condition associated with them as shown below - 

```
- script: echo '1.0.$(Build.BuildId)'
  condition: eq(variables['Build.SourceBranchName'], 'master')
  
- script: echo '1.0.$(Build.BuildId)-$(Build.SourceBranchName)'
  condition: ne(variables['Build.SourceBranchName'], 'master')
```

So if the BuildId was 5 and SourceBranchName was 'master', only the first script would execute and would echo 1.0.5. The second script would be skipped as the condition would fail

On the other hand if the BuildId was 5 and SourceBranchName was 'foo', the first script would be skipped as the condition would fail. The second script would execute and would echo 1.0.5-foo

**Comment by RehanSaeed** [comment]
What if I wanted to output a variable called `Version` at the end of this?

**Comment by RehanSaeed** [comment]
I want to do something like this:

```
- bash: echo '##vso[task.setvariable variable=Version;isOutput=true]$(Build.BuildNumber)'
  condition: eq(variables['Build.SourceBranchName'], 'master')
  displayName: 'Version=$(Build.BuildNumber)'
- bash: echo '##vso[task.setvariable variable=Version;isOutput=true]$(Build.BuildNumber)-$(Build.SourceBranchName)'
  condition: ne(variables['Build.SourceBranchName'], 'master')
  displayName: 'Version=$(Build.BuildNumber)-$(Build.SourceBranchName)'
- bash: echo $(Version)
  displayName: 'echo version'
``

**Comment by vtbassmatt** [comment]
Template expressions aren't allowed at the root of the pipeline. But, if you fix up your third step to be `echo ##vso[build.updatebuildnumber]$(Version)`, you should get what you want.
