### ISSUE TITLE
Embedded videos do not work as documented

### ISSUE THREAD

**Issue by 24mu13** [MicrosoftDocs/vsts-docs#2089]
If you try exactly the same documented way to embed video, simply doesn't work!
::: video
&lt;iframe width="560" height="315" src="https://www.youtube.com/embed/OtqFyBA6Dbk" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen&gt;&lt;/iframe&gt;
:::

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fa622358-f5bb-1f5c-177a-081a37b6acef
* Version Independent ID: 72f7fd16-a822-66c8-3a34-8905645ce5f2
* Content: [Markdown syntax for files, widgets, wikis - Azure DevOps & TFS](https://docs.microsoft.com/en-us/azure/devops/project/wiki/markdown-guidance?view=vsts)
* Content Source: [docs/project/wiki/markdown-guidance.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/project/wiki/markdown-guidance.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by Sniipe** [comment]
@24mu13 - this now works for me.  Azure Dev Ops must have updated last night in our org.

**Comment by 24mu13** [comment]
Yes me too.

**Comment by crh225** [comment]
Does not let me embed loom videos
