### ISSUE TITLE
Can a custom condition use Process variable?

### ISSUE THREAD

**Issue by MeliSantana** [MicrosoftDocs/vsts-docs#209]
Hi I'm trying to define a custom condition based on a Variable defined in the release definition, so it looks like this: 
and(failed(), eq(variables['CustomVariable'], 'Value'))
But I haven't been able to make it work. I'm sure the variable name is right and the value is that. 
The custom conditions only work with predefined variables? 
Thank you in advance

**Comment by steved0x** [comment]
@KathrynEE This is an issue filed by a customer directly in Github and now through the new feedback control on docs.microsoft.com. Is this your area? 

@MeliSantana What article were you looking at when you didn't find the answer? Once we figure out the answer, we can add it there. Thank you.

**Comment by MeliSantana** [comment]
@steved0x this is the article I was looking https://docs.microsoft.com/en-gb/vsts/build-release/concepts/process/conditions

All the examples there use Build. or Agent. Variables. I tried with a custom variable I don't know if there is a prefix missing.

**Comment by steved0x** [comment]
@MeliSantana THank you for letting me know the article, I am forwarding it to the correct author. Thank you.

@andyjlewis This feedback is on one of your articles.

**Comment by alexhomer1** [comment]
Thank you for your feedback. I have passed your question on to the development team and will let you know their response.

**Comment by alexhomer1** [comment]
Apologies for the delay in replying. Custom conditions do work with variables you define yourself. If you define the variable local to an environment, you must qualify the variable name with the appropriate environment name.
