### ISSUE TITLE
Pipelines/Build and Release is incomplete / incorrect

### ISSUE THREAD

**Issue by riQQ** [MicrosoftDocs/vsts-docs#2091]
The row for the task `View builds` is missing. Also, if I'm not mistaken, Stakeholders only have access to release pipelines and not to build pipelines.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a35602ee-9d11-9746-4b79-075e295a5fb8
* Version Independent ID: dbea8e30-e80b-8f13-987e-ef0ad3ba9b83
* Content: [Default permissions and access quick reference - Azure DevOps & TFS](https://docs.microsoft.com/en-us/azure/devops/organizations/security/permissions-access?view=tfs-2017#pipelinesbuild-and-release)
* Content Source: [docs/organizations/security/permissions-access.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/security/permissions-access.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by chcomley** [comment]
@riQQ thanks for the information. I've created a user story on my backlog to address this.

**Comment by riQQ** [comment]
@chcomley any update on this?

**Comment by chcomley** [comment]
Hi @riQQ , I've learned that the "view builds" task is not applicable to this topic and there is no required update.  @KathrynEE should be able to help, if you have any further questions or concerns. Please let us know. Thank you.
