### ISSUE TITLE
Trust

### ISSUE THREAD

**Issue by craig-wagner** [MicrosoftDocs/vsts-docs#2092]
I personally feel the words "at scale" should be omitted in the statement, "When practicing Agile at scale, trust is a 2-way street:" The points below that apply regardless of team size or number of teams.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f4bc244f-e07c-f8a4-0f00-04c8e015821f
* Version Independent ID: 2a37fdcf-eac8-3738-af46-7d70826ec660
* Content: [Scale Agile to Large Teams - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/learn/agile/scale-agile-large-teams)
* Content Source: [https://mseng.visualstudio.com/DefaultCollection/TechnicalContent/_git/devops-learn-pr?path=%2fdocs%2fagile%2fscale-agile-large-teams.md&version=GBlive&_a=contents](https://mseng.visualstudio.com/DefaultCollection/TechnicalContent/_git/devops-learn-pr?path=%2fdocs%2fagile%2fscale-agile-large-teams.md&version=GBlive&_a=contents)
* Product: **devops**
* Git Login: **samgu**
* Microsoft Alias: **gregboe**

**Comment by steved0x** [comment]
@craig-wagner Thank you for your feedback, I have passed this along to the author.
