### ISSUE TITLE
YAML syntax documentation

### ISSUE THREAD

**Issue by memark** [MicrosoftDocs/vsts-docs#2094]
It would be very helpful to include a link to the documentation for the YAML syntax allowed in these files. Where can I find it?

---
#### Dokumentinformation

⚠ *Redigera inte det här avsnittet. Det krävs för docs.microsoft.com ➟ länkning till GitHub-problem.*

* ID: 38f7a23b-ebd4-af3e-68a2-275f7e45c33e
* Version Independent ID: f552a18c-ba29-00d4-03b6-254d7556d319
* Content: [Create your first pipeline - Azure Pipelines & TFS](https://docs.microsoft.com/sv-se/azure/devops/pipelines/get-started-yaml?view=vsts)
* Content Source: [docs/pipelines/get-started-yaml.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/get-started-yaml.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by andyjlewis** [comment]
https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema

**Comment by memark** [comment]
Thank you, that's great! As I also pointed out, it would be great to include this in the documentation page for others to find.

**Comment by andyjlewis** [comment]
fixed in a commit I just made to our internal master, should publish soon. thank you for the feedback.
