### ISSUE TITLE
This documentation is out of date

### ISSUE THREAD

**Issue by ckrempp91** [MicrosoftDocs/vsts-docs#2095]
After investigation into a compression issue of the Android APK I stumbled across a github ticket that outlines a major change of this functional task. The change is that the task transitioned from using the jarsigner to the apksigner. It would be very helpful to have this document match the functionality, and to list all of the supported platforms: DevOps, TFS 2018, etc...

Here is the pull request: https://github.com/Microsoft/azure-pipelines-tasks/pull/7544
Here is the git ticket: https://github.com/Microsoft/vsts-tasks/issues/4783

From the pull request and the ticket it appears they are still listed as "Open", but after posting a comment to one of the contributors the code change has been released within V3 of the task. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4b1fbcd8-d799-879e-d672-9dee164401ef
* Version Independent ID: 7208d03d-9042-7753-ab4d-d1ad8e99ef1d
* Content: [Android signing build and release task - Azure Pipelines & TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/android-signing?view=vsts#feedback)
* Content Source: [docs/pipelines/tasks/build/android-signing.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/build/android-signing.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by ckrempp91** [comment]
Just an update, for a more specific platform support info, it appears the update was released within TFS 2018 Update 3 as mentioned within this comment on the linked pull request: https://github.com/Microsoft/azure-pipelines-tasks/pull/7544#issuecomment-430364336

**Comment by DavidStaheli** [comment]
Thanks for reporting this with such helpful details, @ckrempp91!  We'll address this ASAP.

**Comment by DavidStaheli** [comment]
Keep-alive

**Comment by Timmeey86** [comment]
When updating this documentation, make sure to also update the Keystore File section: The Decrypt File task will no longer work. The file must be stored within the pipeline as an encrypted file, but can then be referenced using the file identifier specified in the pipeline

**Comment by juandelacruz23** [comment]
Also, it says that the keystore can be in the source code, but I never found the way to select it. Only by adding a Secure File under the Library Option, I was able to add it without directly adding it in the task file selector (because I want to mantain a backup). I wonder if the option of taking it from sc is not available anymore (but this doc doesn't say it)

**Comment by davidstaheli** [comment]
The documentation has finally been updated for this.  It should be live in a couple of days.  Thank you for your suggestions and patience.
