### ISSUE TITLE
Need an example and steps to do Alternative to using the Checkout submodules option 

### ISSUE THREAD

**Issue by gmarbury** [MicrosoftDocs/vsts-docs#2097]
the line below is not enough. Please provide an example with a fake PAT with all zeros  or a PAT like this abcdefghijklmnopqrstqrs12345 .

git -c http.https://&lt;url of submodule repository&gt;.extraheader="AUTHORIZATION: basic ********" submodule update --init --recursive

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 41d4fcf8-3fd9-27b5-89e5-a026cc4a2b6a
* Version Independent ID: 76481ffb-aec5-50cd-6cdd-9e53c59e2933
* Content: [Build pipeline source repositories - Azure Pipelines & TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/repository?view=vsts)
* Content Source: [docs/pipelines/build/repository.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/build/repository.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by DavidStaheli** [comment]
Keep-alive

**Comment by davidstaheli** [comment]
Thank you for suggesting this.  The docs have been updated with this and should be live within a few days.
