### ISSUE TITLE
Does VSTS login username and password can be used to connect with git repo

### ISSUE THREAD

**Issue by lvsezhufu** [MicrosoftDocs/vsts-docs#210]
The document only list three authentication types (PAT, SSH and alternate credentials) to connect with VSTS git repo. What about using VSTS login usename (email address) and password?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f8b4989-21f0-53c5-dfce-6d5f1a66b8b2
* Version Independent ID: 2f4419a7-408b-40cd-9190-985a9976d556
* [Content](https://docs.microsoft.com/en-us/vsts/git/auth-overview)
* [Content Source](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/git/auth-overview.md)
* Service: unspecified

**Comment by steved0x** [comment]
I'll find out and update you shortly.

**Comment by steved0x** [comment]
@lvsezhufu If you are using Git Credential Manager for Windows and connecting to your VSTS Git repo, you can use your VSTS username and password in the Git Credential login window.

**Comment by lvsezhufu** [comment]
@steved0x But actually not. For some VCS GUI the email address and password can not be recognized (like GitKranken).  While for some VCS GUI the email address and password can be recognized (like sourcetree). That's confusing.
