### ISSUE TITLE
What about team explorer compatibility?

### ISSUE THREAD

**Issue by dombat** [MicrosoftDocs/vsts-docs#2101]
Some of our users are using old versions of Visual Studio and Team Explorer (e.g. 2012 & 13) so are these comptible with newer TFS? (They do have legitimate reasons for using these old versions) 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 641b37fc-f117-aca0-32f4-8ea9b73e9d71
* Version Independent ID: 211130c6-43b8-f47f-3589-cb4d2a330231
* Content: [Requirements and compatibility](https://docs.microsoft.com/en-us/tfs/server/requirements)
* Content Source: [docs/server/requirements.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/server/requirements.md)
* Product: **devops-server**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by dombat** [comment]
Ah, I see it's on the next page called "Compatibility".  https://docs.microsoft.com/en-us/tfs/server/compatibility

**Comment by elbatk** [comment]
Glad you found it, @dombat :) closing this out!
