### ISSUE TITLE
Unclear where these are found

### ISSUE THREAD

**Issue by krilbe** [MicrosoftDocs/vsts-docs#2102]
It is not clear in this document where we can set/view these parameters in Azure DevOps. There are build pipelines and release pipelines, but I find no parameters view for either. Variables, yes, but parameters? Trying to set Parameters.WebsiteName to something else than "Default Web Site"...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 214c853e-63ba-240c-9cff-7ea3ab7a788c
* Version Independent ID: 781b5018-0c34-353a-a035-5d84af3994a0
* Content: [Process parameters - Azure Pipelines & TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/parameters?view=vsts)
* Content Source: [docs/pipelines/process/parameters.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/parameters.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by prabhakarreddy1234** [comment]
Yes, I know a way to do that by edititing the release definition/YAML file. But it's good to have them configurable in UI.

**Comment by MichaCo** [comment]
Only option I have in the UI is to "unlink All" which removes all step level variables...

![image](https://user-images.githubusercontent.com/5837539/51486279-95fefe00-1da0-11e9-8aff-27ee1a5f6de3.png)

This feature needs much better UI support so that you can define variables which can be linked and select a variable to link within the step...
Right now, that feels very lackluster, I actually couldn't figure out why I cannot change certain properties in a `Manage IISWebsite` task...

**Comment by danieleusebio** [comment]
I don´t know were to set.  
I reinforce:
"It is not clear in this document where we can set/view these parameters in Azure DevOps. There are build pipelines and release pipelines, but I find no parameters view for either. Variables, yes, but parameters? Trying to set Parameters.WebsiteName to something else than "Default Web Site"..."

**Comment by andyjlewis** [comment]
Thank you for the question. Apologies for the very delayed response. Heads up to @steved0x

**Comment by edgariscoding** [comment]
How do I create a pipeline parameter?

**Comment by cd83** [comment]
![linkedparameters](https://user-images.githubusercontent.com/12536689/62971452-89db9c00-bdd7-11e9-8b38-376132ed6add.png)

Still an issue. No option to link new parameters.

**Comment by RoopeshNair** [comment]
Ack. Documentation on process parameters needs improvements. Please note, setting process parameters is supported only in build pipelines and not in release pipelines. [[Doc](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/parameters?view=azure-devops)s]. 

If you'd like to promote a task input as a process parameter, click on "i" icon next to the field and click on "Link". You can optionally customize the "Display name", when done, the input field will show up as a process parameter on the 

![image](https://user-images.githubusercontent.com/1370480/63008553-76483800-bea0-11e9-9c96-806886253acd.png)

![image](https://user-images.githubusercontent.com/1370480/63008652-a68fd680-bea0-11e9-8186-07f155cd2f3f.png)

![image](https://user-images.githubusercontent.com/1370480/63008696-ba3b3d00-bea0-11e9-8cfa-2f0d4d9726ab.png)

**Comment by abelal83** [comment]
How do we link settings from a task group? It's all well and good adding individual tasks repeatedly for those who enjoy it but I'd rather use a task group but not able to link any settings. Is that available?

**Comment by dev-arjunan** [comment]
Create a task like ".Net build" under agent. This task will have an option "Link settings" at the top.Click the "Link settings" option, select required parameters and click on Link button. It will be available in the build pipeline parameters now.

**Comment by tdopun** [comment]
How do you add these parameters if they got deleted? I don't have an option to "link" in the 'i' tooltip.

**Comment by RoopeshNair** [comment]
@tdopun  - are you trying to link in build or release? Note update "RoopeshNair commented on 14 Aug 2019 "

**Comment by andrewrandsbluestone** [comment]
I'm facing a similar issue.

I have created an IIS Deployment release pipeline. The IIS Web App Manage task has Website name fixed as 'Default Web Site'. The link thing states "This setting is linked to the 'Website name' (Parameters.WebsiteName) pipeline parameter."

I just _cannot_ figure out how to access this Parameters.WebsiteName setting

**Comment by adhamenaya** [comment]
> I'm facing a similar issue.
> 
> I have created an IIS Deployment release pipeline. The IIS Web App Manage task has Website name fixed as 'Default Web Site'. The link thing states "This setting is linked to the 'Website name' (Parameters.WebsiteName) pipeline parameter."
> 
> I just _cannot_ figure out how to access this Parameters.WebsiteName setting

@andrewrandsbluestone did you manage it?

**Comment by andrewrandsbluestone** [comment]
@adhamenaya Eventually, after much sharing of screen shots ! The recipe should build a pipeline that has this structure: 

Stage 1 (deployment process)
-- IIS Deployment 
    -- IIS Web App Manage
    -- IIS Web App Deploy

Website name is at the 'Stage 1' level, which isn't at all obvious.

**Comment by Joebeazelman** [comment]
As usual, Microsoft knows how to take the simplest concepts and turn it into hell!  What is a parameter?  How is it different from a variable?  I wish I could say it's the worst part of Azure DevOps, but it's not. 

The user interface is horrid.  It's like a evil game of _Where's Waldo_ and hide and seek with booby traps at every corner! Whoever designed this interface needs to retire and grow turnips in Antartica where they can't cause no further damage!
