### ISSUE TITLE
misspelled word

### ISSUE THREAD

**Issue by randallrmz** [MicrosoftDocs/vsts-docs#2103]
'usng' instead of 'using' line 1 from anchor: https://docs.microsoft.com/en-us/azure/devops/learn/git/git-pull-requests#learn-more

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ff23ed00-53ad-e289-bf1e-084055036ec3
* Version Independent ID: 6a428e43-b647-9631-add5-43d54c4981b6
* Content: [Get feedback with pull requests - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/learn/git/git-pull-requests#learn-more)
* Content Source: [https://mseng.visualstudio.com/DefaultCollection/TechnicalContent/_git/devops-learn-pr?path=%2fdocs%2fgit%2fgit-pull-requests.md&version=GBlive&_a=contents](https://mseng.visualstudio.com/DefaultCollection/TechnicalContent/_git/devops-learn-pr?path=%2fdocs%2fgit%2fgit-pull-requests.md&version=GBlive&_a=contents)
* Product: **devops**
* Git Login: **samgu**
* Microsoft Alias: **routlaw**

**Comment by steved0x** [comment]
@randallrmz Thanks for letting us know, I am fixing this and it should be live soon.
