### ISSUE TITLE
yaml syntax incomplete for additional arguments

### ISSUE THREAD

**Issue by cmeyertons** [MicrosoftDocs/vsts-docs#2105]
it would be nice to see yaml snippets of all the available arguments and their defaults for the different docker commands

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d9dbf88-7e55-d427-145e-d36b04fb197f
* Version Independent ID: a3f30c00-817c-9c05-7a57-3f2bf618821e
* Content: [Docker - Azure Pipelines & TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/docker?view=vsts)
* Content Source: [docs/pipelines/tasks/build/docker.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/build/docker.md)
* Product: **devops**
* GitHub Login: @erickson-doug
* Microsoft Alias: **dastahel**

**Comment by gedeh** [comment]
Hi there, any update on this issue? The documentation is very poor for docker task in Azure pipeline

**Comment by shashankbarsin** [comment]
@cmeyertons and @gedeh, thanks for reporting this issue. We have now completely re-written our Docker task documentation to provide more samples on how to use the task and its inputs.
