### ISSUE TITLE
Typo in section Timeouts' example

### ISSUE THREAD

**Issue by vuminhle** [MicrosoftDocs/vsts-docs#2108]
The example in [Timeouts](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/phases?tabs=yaml&view=vsts#timeouts) should contain `job` instead of `pool`. It should also contain real numbers to be consistent with other surrounding sections. 

```yaml
jobs:
- job: Test
  timeoutInMinutes: 10
  cancelTimeoutInMinutes: 2
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 54bf6c2f-95c1-943d-26ae-d7099143bccf
* Version Independent ID: 0833bb55-1e54-6953-ee69-de6d191d2ec1
* Content: [Build and release jobs in Azure Pipelines and TFS - Azure Pipelines & TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/phases?tabs=yaml&view=vsts#timeouts)
* Content Source: [docs/pipelines/process/phases.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/phases.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment]
Thank you for your feedback. I will update the topic to include your recommendations.
