### ISSUE TITLE
Is there a PSCredential available to be used?

### ISSUE THREAD

**Issue by StingyJack** [MicrosoftDocs/vsts-docs#211]
Some build activities (invoke-webrequest, etc) require a credential to be provided when making requests. Is the build agent's user context available as a PSCredential I can supply to those activities?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ffebdc8-521c-44b5-cde4-4abdc1bd6f18
* Version Independent ID: dc0effda-6d93-62aa-64c5-4e6f283b0826
* [Content](https://docs.microsoft.com/en-us/vsts/build-release/concepts/definitions/build/variables?tabs=batch)
* [Content Source](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/build-release/concepts/definitions/build/variables.md)
* Service: unspecified

**Comment by andyjlewis** [comment]
Hi StingyJack, I'm following up with the product team.

**Comment by andyjlewis** [comment]
I'm sorry about the delayed response. Does this help: https://docs.microsoft.com/en-us/vsts/build-release/actions/scripts/powershell?view=vsts#use-the-oauth-token-to-access-the-rest-api? BTW, on the service today you actually need to select the phase in the tasks tab to select the Allow Scripts to Access OAuth Token checkbox. The token is also useful for more than just accessing the REST API. We've got an item on the backlog to update the topic.

**Comment by StingyJack** [comment]
No worry on the timing, but what am I to do with an OAuth token?

The build agents are windows services that run under a specific domain account on a windows server in the LAN. I just want to have them use that service credential to perform deployment or other actions to other servers on the LAN, but that doesnt seem to work. 

To make it work like XAML builds used to work, I have to enter that domain account's credentials somewhere in the build def or elsewhere, and construct a NetworkCredential then convert that to a PSCredential.

**Comment by TingluoHuang** [comment]
When you configure the agent as windows service, the agent process will run as the service account you picked during agent config, NetworkService by default.
When your build running on the agent, the agent process will use an OAuth token to talk back to VSTS/TFS endpoint.
But since the process is running as your Service Account, you should be able to use integrate auth for that service in PowerShell to invoke-webrequest to your local resources.

**Comment by StingyJack** [comment]
@TingluoHuang  - That would make sense and would be great if it worked, but it doesn't. I use a specific domain account for the service account, and this credential is not available to inline script block tasks that try to `-UseDefaultCredentials`  to download a build artifact or file from TFVC.

I've worked around the immediate issue as mentioned in OP, but not the maintenance burden.

**Comment by riezebosch** [comment]
https://docs.microsoft.com/en-us/vsts/pipelines/build/options?view=vsts#allow-scripts-to-access-the-oauth-token

Tasks already have access to the token but for custom scripts you need to allow it on the build options page. Of course, there's a security implication with that.

**Comment by StingyJack** [comment]
There is no token involved.

**Comment by vtbassmatt** [comment]
We don't have first-class support for exposing the Windows identity the agent is running under. The only thing we provide is an OAuth token for the build service identity with respect to VSTS.

**Comment by StingyJack** [comment]
I get that, but is there any setting that would prevent the active build from inheriting the windows identity of the service account when executing things like Invoke-WebRequest in a build task?

**Comment by vtbassmatt** [comment]
The agent spins up a new process for each task/step. It wouldn't surprise me if that process is started as a really low-privilege identity different from the agent itself, but I don't know for sure. @TingluoHuang can you provide any definitive answers here?

**Comment by StingyJack** [comment]
Thanks for the definite answer, I appreciate it.
