### ISSUE TITLE
Problem with usage of pre-defined variables in a Command Script

### ISSUE THREAD

**Issue by hayesgb** [MicrosoftDocs/vsts-docs#2114]
I'm executing a git in a command script.  When I pass:
git remote add origin $(Build.Repository.Uri)
I'm getting the base url of the git repository, not the full repository URI.

However, if I pass:
git remote add origin $(Build.Repository.Uri)/$(Build.Repository.Name)
Then I get an error, because the full repository URL + the repository name is appended, such that:  https://xx.yy.com/_git/repo_name/repo_name.

Any suggestions?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ffebdc8-521c-44b5-cde4-4abdc1bd6f18
* Version Independent ID: dc0effda-6d93-62aa-64c5-4e6f283b0826
* Content: [Predefined build variables - Azure Pipelines & TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=vsts)
* Content Source: [docs/pipelines/build/variables.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/build/variables.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by vijayma** [comment]
@hayesgb I tried this and it worked fine for me. For instance, the Build.Repository.Uri in my test was https://adventworks.visualstudio.com/Experiments/_git/npmtest. The git command works fine with that uri. Can you shed some more light on this issue?

**Comment by yaananth** [comment]
please make sure the service endpoint points the right URL.
We set that based on how you configure the end point.
Eg:
![image](https://user-images.githubusercontent.com/12280011/49845558-29521600-fd95-11e8-8ab7-7c3df8638302.png)

We shouldn't be allowing such URL, we are fixing that.
