### ISSUE TITLE
How do we filter tests like NUnit

### ISSUE THREAD

**Issue by nikolay-advolodkin** [MicrosoftDocs/vsts-docs#2119]
How do we select and filter tests from a framework like NUnit? Any docs on this available?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c52f6c7a-51d5-bb16-7818-40236e8ed8ef
* Version Independent ID: c2e57832-cf8b-ec17-bd45-fe5ef10b95ea
* Content: [Azure Pipelines and TFS Build and Test - Run Functional Tests task - Azure Pipelines & TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/test/run-functional-tests?view=vsts)
* Content Source: [docs/pipelines/tasks/test/run-functional-tests.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/test/run-functional-tests.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment]
Thank you for your feedback. I have passed this on to the product team for advice.

**Comment by alexhomer1** [comment]
NUnit tests produce DLLs, so the same filtering logic as Windows DLLs applies. More information about test case filtering is available at https://github.com/Microsoft/vstest-docs/blob/master/docs/filter.md. Note that the Run Functional Tests task is deprecated - consider using the Visual Studio Test task instead (https://docs.microsoft.com/azure/devops/pipelines/tasks/test/vstest).

**Comment by nikolay-advolodkin** [comment]
The documentation is using the "dotnet test" command. How can we do this in an Azure DevOps pipeline using a YAML configuration?

**Comment by alexhomer1** [comment]
I assume you are looking at the Designer (UI) approach. This shows the YAML code: https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core?view=vsts&tabs=yaml#run-your-tests

**Comment by nikolay-advolodkin** [comment]
So you're suggesting something like this to run some tests from NUnit from the YAML?
`- script: dotnet test <test-project> --filter "Category=bvt"`
Thanks in advance
