### ISSUE TITLE
Incorrect YAML example for docker login

### ISSUE THREAD

**Issue by xtellurian** [MicrosoftDocs/vsts-docs#2121]
YAML script docker login for ACR example is:

`docker login -u $(dockerId).azurecr.io -p $(pswd) $(dockerid).azurecr.io`

but should be

`docker login -u $(dockerId) -p $(pswd) $(dockerid).azurecr.io`

without the .azurecr.io on the username

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e825c07d-2168-c0aa-782a-ef6f9c7ba95e
* Version Independent ID: 5cb6926b-215a-bf89-8e63-b2e1129e41df
* Content: [Docker - Azure Pipelines & TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/languages/docker?view=vsts&tabs=yaml)
* Content Source: [docs/pipelines/languages/docker.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/languages/docker.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by xtellurian** [comment]
huh - the repo has been updates, but docs.microsoft.com has not

https://docs.microsoft.com/en-us/azure/devops/pipelines/languages/docker?view=vsts&tabs=yaml#push-an-image

**Comment by eriawan** [comment]
@steved0x 

The online Docs shows correct syntax now: https://docs.microsoft.com/en-us/azure/devops/pipelines/languages/docker?view=vsts&tabs=yaml#push-an-image

![image](https://user-images.githubusercontent.com/8773147/48938386-a41cd380-ef43-11e8-9ba5-2469664936ac.png)

I suggest to close this issue 🙂

**Comment by andyjlewis** [comment]
thanks for the heads up @eriawan
