### ISSUE TITLE
How to choose between Agile & Scrum

### ISSUE THREAD

**Issue by ripper234** [MicrosoftDocs/vsts-docs#2122]
As someone doing some informal form of Agile/Scrum for years, it's the first time I am asked to choose a template.
Any advice on how to choose between the two? What works for which teams/processes?
Is the difference mostly semantic, in the terminology of the states?
Can this be changed later?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b3466d1-72cc-2d47-d98b-7029639c0f79
* Version Independent ID: 4ff82210-6b5a-589d-261e-1ddbd3007e2a
* Content: [Choose a process - Azure Boards and TFS](https://docs.microsoft.com/en-us/azure/devops/boards/work-items/guidance/choose-process?view=vsts)
* Content Source: [docs/boards/work-items/guidance/choose-process.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/boards/work-items/guidance/choose-process.md)
* Product: **devops**
* GitHub Login: @erickson-doug
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@ripper234 - Thank you for your inquiry. The main differences between Scrum and Agile processes are: 
- work item type names are different 
- workflow states, Agile has one additional state from Active to Resolve; Scrum doesn't
- Task work item type for Agile includes Orignal Estimate and Completed Work, Scrum only contains Remaining Work (you can change this for Scrum)  

Once you select a process for a project, you can't switch to a different process- That is you can't switch from Agile to Scrum or Scrum to Agile.
