### ISSUE TITLE
What happens to a PAT if user account is disabled?

### ISSUE THREAD

**Issue by StefanSchoof** [MicrosoftDocs/vsts-docs#2124]
What happens with the valid PAT, when a User Account is removed from Azure DevOps. Are the still valid to the given date or are they become invalid?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2bfea574-db69-a5fd-37fe-64ecfdac502a
* Version Independent ID: 4037d475-f194-2ac9-ffd6-70530fc3140a
* Content: [Authenticate access with personal access tokens](https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/use-personal-access-tokens-to-authenticate?view=vsts)
* Content Source: [docs/organizations/accounts/use-personal-access-tokens-to-authenticate.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/accounts/use-personal-access-tokens-to-authenticate.md)
* Product: **devops**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @StefanSchoof , once a user is removed from Azure DevOps, the PAT is invalidated within 1 hour. Please let us know if you have any other questions. Thank you.

**Comment by StefanSchoof** [comment]
Thanks for the answer

**Comment by vijay-gowda** [comment]
Hi @chcomley,

I want to use a PAT token for configuring build agent, but I do not want the PAT to be invalidated if I leave my organization, as the build agents will be used by rest of the organization members. What option do I have?

**Comment by chcomley** [comment]
Hi @vijay-gowda, You can use a service account and generate a PAT for the service account and use that. That way, the team can own the service account and you don’t have to worry about PATs getting invalidated when one person leaves the team.
