### ISSUE TITLE
Need link of the attachment!

### ISSUE THREAD

**Issue by moyanming** [MicrosoftDocs/vsts-docs#2127]
I need a link of the attachment, so I can add this link to the text of the content within the discussions.
![qq 20181017200246](https://user-images.githubusercontent.com/13234209/47085023-e453ac80-d247-11e8-9e70-b6f4d56e770d.jpg)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ef3955e8-20ca-18ad-172a-bce3b4374b92
* Version Independent ID: 92133948-fb31-db82-6d60-7cebb8c05bcc
* Content: [Add work items - Azure Boards and TFS](https://docs.microsoft.com/en-us/azure/devops/boards/backlogs/add-work-items?toc=/azure/devops/boards/work-items/toc.json&bc=/azure/devops/boards/work-items/breadcrumb/toc.json&view=vsts)
* Content Source: [docs/boards/backlogs/add-work-items.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/boards/backlogs/add-work-items.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@moyanming - Thank you for your inquiry. The only way to get the URL of an attachment is to use the REST API, https://docs.microsoft.com/en-us/rest/api/vsts/wit/work%20items/get%20work%20item?view=vsts-rest-4.1. call GET work item REST API with proper expand option, and they will be able to find the url of attachments there. 

You may want to ask for a [feature request](https://developercommunity.visualstudio.com/spaces/21/index.html) to add an option to the menu which would provide a URL to the attachment.
