### ISSUE TITLE
@CurrentIteration +/- n macro in Excel

### ISSUE THREAD

**Issue by pauldalyii** [MicrosoftDocs/vsts-docs#2128]
Are there plans to update the Office Integration Tools to support @CurrentIteration +/- n macros so that we can open queries in Excel?  If so, do you have an ETA?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba14ee34-2de7-706f-ae44-be969fde352b
* Version Independent ID: f7ba18e9-42e4-ef07-e36b-377fb787aa72
* Content: [Query by date or current iteration - Azure Boards and TFS](https://docs.microsoft.com/en-us/azure/devops/boards/queries/query-by-date-or-current-iteration?view=vsts)
* Content Source: [docs/boards/queries/query-by-date-or-current-iteration.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/boards/queries/query-by-date-or-current-iteration.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by danhellem** [comment]
Sorry no, we don't have any plans to support the @CurrentIteration +/- macros in Excel in the short term. We will make sure this is on the backlog though to review and consider in the future.
