### ISSUE TITLE
.NET Core applications is not covered

### ISSUE THREAD

**Issue by pekspro** [MicrosoftDocs/vsts-docs#2132]
This document doesn't cover how to unit test .NET Core applications, would be nice if that was explicitly mentioned (than I might have got to sleep earlier).

This is how I got it to work:
* I removed the VsTest task.
* I added the task .NET Core
* In this task I selected "test" as command and entered an appropriate path to the project files (I used **/*my*test*.csproj)

That's it! :-)

---
#### Dokumentinformation

⚠ *Redigera inte det här avsnittet. Det krävs för docs.microsoft.com ➟ länkning till GitHub-problem.*

* ID: f69faf41-3074-0ce2-fb3f-3d9cc570e010
* Version Independent ID: 9ce392b3-b1cc-55f7-93e5-e8d2cc9bd788
* Content: [Run unit tests with your builds in Azure Pipelines and TFS - Azure Pipelines & TFS](https://docs.microsoft.com/sv-se/azure/devops/pipelines/test/getting-started-with-continuous-testing?view=vsts)
* Content Source: [docs/pipelines/test/getting-started-with-continuous-testing.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/test/getting-started-with-continuous-testing.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment]
Thank you for your feedback. The process for testing .NET Core apps is described in https://docs.microsoft.com/en-gb/azure/devops/pipelines/languages/dotnet-core?view=vsts&tabs=designer#run-your-tests. I will add a link to the topic to reflect this and other test options.
