### ISSUE TITLE
The Work Items Page in TFS 2018.2 is Missing

### ISSUE THREAD

**Issue by scottkuhl** [MicrosoftDocs/vsts-docs#2134]
The documentation states that the new Work Item pages is available in TFS 2018.2 but I am not seeing it.  Is this feature actually available on premises or cloud only?  

https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/boards/work-items/view-add-work-items.md

**Comment by KathrynEE** [comment]
@scottkuhl - Thank you for your inquiry. The Work Items page isn't available from TFS 2018.2. It will be available with the RC1 release of TFS 2019, now known as Azure DevOps Server 2019. My apologies for the confusion. I'm updating the topic now.

**Comment by scottkuhl** [comment]
Thanks

Scott
________________________________
