### ISSUE TITLE
Environment variables only exist on 'Hosted VS2017' agents

### ISSUE THREAD

**Issue by MisterReally** [MicrosoftDocs/vsts-docs#2135]
The environment variables mentioned in this article for the selenium browser drivers like "ChromeWebDriver" don't exist on the hosted agents -  please clarify that it is only the Hosted VS2017 agents that host Chrome and the web drivers.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 09e51d18-72ec-1ad4-9ae7-8185c8e1dcd6
* Version Independent ID: 9f2f0471-d123-8e95-1606-cd811d1ece9a
* Content: [Selenium testing with continuous integration in Azure Pipelines - Azure Pipelines & TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/test/continuous-test-selenium?view=vsts)
* Content Source: [docs/pipelines/test/continuous-test-selenium.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/test/continuous-test-selenium.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment]
Thank you for your feedback. I will update the topic to include your recommendations.
