### ISSUE TITLE
Please describe the workspace -> clean values

### ISSUE THREAD

**Issue by spbrogan** [MicrosoftDocs/vsts-docs#2137]
Anytime their is a set of valid values for a field can they be briefly described.  Specifically my ask is for the workspace clean options.  

workspace:
    clean: outputs | resources | all # what to clean up after the job runs

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7458d5b2-1bb7-7d87-7ce6-2b0c430b0155
* Version Independent ID: edf5bbd3-a3f0-5426-e985-31290f8afd05
* Content: [YAML schema - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=vsts&tabs=schema#job)
* Content Source: [docs/pipelines/yaml-schema.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/yaml-schema.md)
* Product: **devops**
* GitHub Login: @erickson-doug
* Microsoft Alias: **macoope**

**Comment by Silvenga** [comment]
We totally need this documented.

**Comment by vtbassmatt** [comment]
@TingluoHuang it wasn't obvious to me (from reading the code) how the workspace clean options get mapped to the agent, or what each one does. Can you share, and then @steved0x can fix up the doc? The options are "outputs", "resources", and "all".

**Comment by TingluoHuang** [comment]
resources: delete $(Build.SourcesDirectory)  => _work\1\s
outputs: delete $(Build.BinariesDirectory) => _work\1\b
all: delete $(agent.builddirectory) => _work\1
