### ISSUE TITLE
Typo in document

### ISSUE THREAD

**Issue by apopovsky** [MicrosoftDocs/vsts-docs#2140]
pookl instead of pool at https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/pools-queues?view=vsts#creating-agent-pools

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4409a9cb-8448-edd6-da0a-243e5601aa3e
* Version Independent ID: ec15f71a-a76d-c3f9-1d31-832f92183ef4
* Content: [Agents pools - Azure Pipelines & TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/pools-queues?view=vsts#creating-agent-pools)
* Content Source: [docs/pipelines/agents/pools-queues.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/agents/pools-queues.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by andyjlewis** [comment]
good catch, thanks. pushed fix to an internal PR, should be published this week
