### ISSUE TITLE
Maven Upsteam Source Capabilities

### ISSUE THREAD

**Issue by robertkearnes** [MicrosoftDocs/vsts-docs#2141]
There is no mention of Maven upsteam source capabilities, is this available and if not when is it scheduled to be available in the same way as discussed for NuGet and npm?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d5f022df-36c3-34b1-cac1-ac33995a7d73
* Version Independent ID: 9634b0c8-7b14-4453-2c04-aedabbf331f1
* Content: [Upstream sources](https://docs.microsoft.com/en-us/azure/devops/artifacts/concepts/upstream-sources?view=vsts)
* Content Source: [docs/artifacts/concepts/upstream-sources.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/artifacts/concepts/upstream-sources.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by elbatk** [comment]
Gonna let @alexmullans tackle this one for ya, @robertkearnes

**Comment by alexmullans** [comment]
We're working on the infrastructure required for Maven upstream sources now. Expecting to enable them sometime in Q1.

**Comment by elbatk** [comment]
Closing this issue for now. Be on the lookout for the docs for that in Q1 @robertkearnes

**Comment by kczelusniak** [comment]
Were Maven upstream sources enabled?

**Comment by alexmullans** [comment]
Yep, they're deployed and enabled everywhere - look for a new option in **Upstream sources** in feed settings.

**Comment by kczelusniak** [comment]
Awesome!

However, I think the point made by the original post still stands. I don't think the documentation was updated to reflect that upstream sources are now supported for Maven.

**Comment by mimatn** [comment]
Only Maven Central is enabled; you can't add Maven custom upstreams. That is... quite limiting to say the least: JCenter, Gradle Plugin repository and Spring repository are major sources that contain additional material to Central.
