### ISSUE TITLE
.NET Standard support?

### ISSUE THREAD

**Issue by mattfrear** [MicrosoftDocs/vsts-docs#2142]
I have been waiting for this to exist for years! Finally a way to step into and debug NuGet packages.

I am trying to get SourceLink to work with our in-house NuGet package.
I am running a netcore2.1 web application which references a netstandard2.0 NuGet package hosted on our Azure Devops feed.

**Question 1:** Are .NET Standard packages supported?

I have followed the instructions in this post. 
The Build pipeline Publish symbols path appears to be working - in the logs I see:
```
Succeeded processing D:\a\1\s\src\MyCompany.Core.Services.SnapshotClient\bin\release\netstandard2.0\MyCompany.Core.Services.SnapshotClient.pdb:
```

When I start debugging I see a bunch of output in the Output window:
```
'dotnet.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\2.1.4\Microsoft.AspNetCore.Hosting.dll'. Cannot find or open the PDB file.
```
But for my NuGet package I see "Symbols loaded" which seems promising. BTW, my NuGet package does not include .pdb files **Question 2 - should it?**
However, I never see the prompt "Source Link will download from the internet" in your screenshot above.

Consequently, when I debug and attempt to Step-In to my NuGet package, it just steps over it.

I have tried:
1. Following the instructions on this page
2. When that didn't work, I headed over to https://github.com/dotnet/sourcelink and followed their instructions and installed the Microsoft.SourceLink.Vsts.Git package (**Question 3** is that necessary?)
3. When that didn't work, I upgraded every darn package in my application, which forced me to install .NET Core SDK 2.1.403 which forced me to reboot my machine which caused me to lose this post and have to type it in again!
4. **Update:** Tried adding some stuff to the .csproj of my NuGet package, after trawling GitHub issues
```
<PublishRepositoryUrl>true</PublishRepositoryUrl> 
<AllowedOutputExtensionsInPackageBuildOutputFolder>$(AllowedOutputExtensionsInPackageBuildOutputFolder);.pdb</AllowedOutputExtensionsInPackageBuildOutputFolder>
```
and
```
<DebugType>portable</DebugType>
<ci>true</ci>
```
Now my .nupkg includes .pdb files too. Still doesn't help me step in debug though.
5. installed the sourcelink cli tools from https://www.nuget.org/packages/sourcelink/ and ran `sourcelink print-urls` on the .pdb from my .nupkg. Looks correct, I think? URLs are present.
6. Disabled indexing after seeing a comment https://github.com/MicrosoftDocs/vsts-docs/issues/1336#issuecomment-414415049 from @mitchdenny . Still doesn't work.

And now I'm stumped as to why it's not working. Am I missing something? The help page here makes it seem as though all you need to do is Enable a VSTS task, but I have spent hours trying to get this working to no avail.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 728b7c25-2ef7-3807-b898-b9024ba297e2
* Version Independent ID: 4b2eda64-1f32-fdf8-ee09-420dbb8b9f4d
* Content: [Setting up GitHub Source Linking with Azure DevOps Services Build & Azure DevOps Services Symbol Server](https://docs.microsoft.com/en-us/azure/devops/artifacts/symbols/setting-up-github-sourcelinking?view=vsts)
* Content Source: [docs/artifacts/symbols/setting-up-github-sourcelinking.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/artifacts/symbols/setting-up-github-sourcelinking.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by elbatk** [comment]
Hi @mattfrear ! I'm glad you're excited about this! These types of questions (re: "how do I do xxxx") are better suited for StackOverflow. However there could be a docs consequence that comes out of that discussion and if that's the case I'd love to hear it so I can make helpful changes. 

Closing this issue here for now, but to try to help, I'm adding @mitchdenny to take a look for you if he can help you quickly here. I still suggest you post on SO as well.

**Comment by mattfrear** [comment]
OK, I've asked over on stackoverflow too.

https://stackoverflow.com/questions/52889238/debug-nuget-package-with-azure-devops-and-source-link
