### ISSUE TITLE
NuGet YAML task documentation confusion

### ISSUE THREAD

**Issue by davidroberts63** [MicrosoftDocs/vsts-docs#2144]
The doc on the [NuGet task YAML](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/package/nuget.md) is a bit confusing. I've forked and begun some modification to that document to clarify how to use it.

Before any questions, if what I want to work on is not needed, no worries, let me know and I'll step back. Simply want to offer help where I can.

1. Is there a contribution guide?  Do I need to contact Douge Erickson, if so how?
1. What elements of Markdown are available to use (github flavor, etc?)
1. What I'd want to do is to use the name of the YAML inputs as the values in the 'Argument' column and provide a description that is more relevant to the YAML usage. Right now it's mostly in reference to what you'd do in the GUI.

**Comment by alexmullans** [comment]
@steved0x or @elbatk can one of you answer 1 and 2? I think a PR is sufficient for 1 but one of them can confirm.

3. sounds great, thanks for the contribution!

**Comment by elbatk** [comment]
Hi @davidroberts63 , I think I have some answers for ya:

1. [Contributor Guide](https://review.docs.microsoft.com/en-us/help/contribute/?branch=master)
2. You can use the GitHub flavored superset of Markdown, there is a couple of articles on Markdown in the contributor guide, just search "markdown" in the search bar above the table of contents. Here is the [main page on markdown](https://review.docs.microsoft.com/en-us/help/contribute/contribute-how-to-write-use-markdown?branch=master) for convenience.

Thanks in advance for your contribution!

**Comment by elbatk** [comment]
Gonna go ahead and close this and I look forward to seeing a PR from ya 👍

**Comment by davidroberts63** [comment]
Sounds good to me. Just a note. @elbatk those links are giving a 403. I tried via my corporate login as well as a personal (Microsoft account) login. I'll go forward using the GitHub flavored superset.
