### ISSUE TITLE
Subscriptions REST API link is out of date

### ISSUE THREAD

**Issue by kailuMSFT** [MicrosoftDocs/vsts-docs#2145]
Clicking the subscriptions link (https://visualstudio.microsoft.com/docs/integrate/api/hooks/subscriptions) takes me to a 404 Not Found.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 571ca92c-4252-2138-6899-8477f4d5dcf3
* Version Independent ID: 6a5fc398-1799-df19-d6c0-987491108fa4
* Content: [Service hooks in Azure DevOps Services REST APIs](https://docs.microsoft.com/en-us/azure/devops/integrate/concepts/service-hooks?view=vsts)
* Content Source: [docs/integrate/concepts/service-hooks.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/integrate/concepts/service-hooks.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by elbatk** [comment]
Thank you for the heads up, it's supposed to link here: https://docs.microsoft.com/en-us/rest/api/vsts/hooks/subscriptions?view=vsts-rest-4.1

Fixing now :)
