### ISSUE TITLE
Cannot concatenate string to template parameter

### ISSUE THREAD

**Issue by sbomer** [MicrosoftDocs/vsts-docs#2147]
The example given above does not appear to work:
- script: echo ${{ coalesce(parameters.foo, parameters.bar, 'Nothing to see') }}

This can be accomplished by making the script contents a template expression using format. The docs should clarify that template parameter expansion does not occur inside strings (if my understanding is correct).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6724abea-bbdc-bf66-ed5e-3214fa6c3e66
* Version Independent ID: 4f8dab21-3f0e-da32-cc0e-1d85c13c0065
* Content: [Job and step templates - Azure Pipelines & TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/templates?view=vsts)
* Content Source: [docs/pipelines/process/templates.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/templates.md)
* Product: **devops**
* GitHub Login: @vtbassmatt
* Microsoft Alias: **alewis**

**Comment by vtbassmatt** [comment]
Whoops, you are correct. Good find! That one slipped in from the future, as we're currently rolling out a feature which makes that syntax work properly. Since it's literally rolling out right now, I don't think I'll fix the docs just to have to fix them back in a week.
