### ISSUE TITLE
Typo in howto-provision-deployment-group-agents.md

### ISSUE THREAD

**Issue by natelistrom** [MicrosoftDocs/vsts-docs#2148]
There's a typo under the section **Install the Azure Pipelines Agent Azure VM extension**, item # 4:

> sub~a~cription

Should be:

> sub**s**cription

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 09fa0c14-9937-41bc-cc34-179edb379083
* Version Independent ID: 10fe3600-21a5-12db-5e21-5ade3a8fa484
* Content: [How to provision agents for deployment groups - Azure Pipelines & TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/deployment-groups/howto-provision-deployment-group-agents?view=vsts)
* Content Source: [docs/pipelines/release/deployment-groups/howto-provision-deployment-group-agents.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/release/deployment-groups/howto-provision-deployment-group-agents.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment]
Thank you for your feedback. I have merged your PR.
