### ISSUE TITLE
Add or remove tags from templates

### ISSUE THREAD

**Issue by SyntaxC4** [MicrosoftDocs/vsts-docs#2151]
Could we expand the documentation here to show how to support adding multiple tags? I'm not sure if I need to use a comma `,` or a semi-colon `;` or some other deliminator.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1debd814-eb48-c984-a4f9-7606093e9617
* Version Independent ID: f48ef796-c2e3-8fa3-6c41-326a5b252a3d
* Content: [Work item templates - Azure Boards and TFS](https://docs.microsoft.com/en-us/azure/devops/boards/backlogs/work-item-template?view=vsts&tabs=browser#add-or-remove-tags-from-templates)
* Content Source: [docs/boards/backlogs/work-item-template.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/boards/backlogs/work-item-template.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@SyntaxC4 - Thanks Cory for your feedback. You can use a comma delimiter, I'll update the topic.
