### ISSUE TITLE
DOTNET Restore Fails behind proxy still

### ISSUE THREAD

**Issue by JCanlett** [MicrosoftDocs/vsts-docs#2152]
Running the following commands at the root of my dotnet core console application fails with a 401. 

dotnet nuget locals -c all
dotnet restore 

![image](https://user-images.githubusercontent.com/1483636/47185202-9a1f0980-d2e1-11e8-8566-26063bad6407.png)

I have followed several github posts in an attempt to add proxy settings in nuget.config. and while restoring via VisualStudio works fine, anything from the command line fails with 401. The work around to use VS to restore isn't plausable as I am creating a dotnet CLI tool and need to be able to install it via dotnet tool install from my private azure devops feed.

**Comment by steved0x** [comment]
@JCanlett Thank you for your feedback. The issues in this repo are for content feedback, can you let me know the URL of the article that goes with this feedback so I can pass it along to the correct author? If this is a product issue (something not working properly, or a feature request), please file an issue here: https://developercommunity.visualstudio.com/spaces/21/index.html

Thank you.

**Comment by JCanlett** [comment]
I have looked at so many now, one is here:  https://github.com/NuGet/Home/issues/6978
And the documentation here  https://docs.microsoft.com/en-us/azure/devops/artifacts/nuget/dotnet-exe?view=vsts  is lacking.

However based on one of the links in the docs above, I found this page describing how to manually create the NuGet plugins folder for dotnet. https://github.com/Microsoft/artifacts-credprovider 

However that doesn't seem to work for the dotnet tools install command which doesn't understand --interactive (although you can see the output of dotnet restore suggesting this) I have no work around for the Proxy issues as even after all that manual process I have to do the following to get around this. 

* Clear all local nuget package caches 
* From the root of a dotnet core project run dotnet restore --interactive (which calls cred manager and fails behind proxy)  
* after auth is complete and a token is generated in local cache, I can then run dotnet tool install "packagename"  

Not sure where to put any of these issues.

**Comment by steved0x** [comment]
@JCanlett I have assigned this to the author of the docs.microsoft.com article you provided so they can address the feedback on that article. Thank you.

**Comment by alexmullans** [comment]
The .NET Core CLI task is updated with support for proxies. It's rolling out as part of the current deployment, will be available in the next few weeks.

**Comment by tremblaysimon** [comment]
@alexmullans do you know if it will be available in the next 2.1.x SDK version?
