### ISSUE TITLE
Embedded videos work however MS Stream vids do not work

### ISSUE THREAD

**Issue by Sniipe** [MicrosoftDocs/vsts-docs#2154]
This works:
```
::: video
<iframe width="560" height="315" src="https://www.youtube.com/embed/OtqFyBA6Dbk" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>
:::
```

However this does not work:
```
::: video
<iframe width="560" height="315" src="https://web.microsoftstream.com/video/fccd4ef9-4a3e-4505-9f1b-7a3971d68ad3" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>
:::
```

I can access the link https://web.microsoftstream.com/video/fccd4ef9-4a3e-4505-9f1b-7a3971d68ad3 no problem, but it doesn't appear correctly on the wiki page and appears as below (shows youtube works and ms stream doesn't):

![image](https://user-images.githubusercontent.com/9591486/47217663-ebda9900-d3a0-11e8-91a0-4c6c650fa92b.png)

**Comment by steved0x** [comment]
@Sniipe Thank you for your feedback. The issues in this repo are for content feedback, can you let me know the URL of the article that goes with this feedback so I can pass it along to the correct author? If this is a product issue (something not working properly, or a feature request), please file an issue here: https://developercommunity.visualstudio.com/spaces/21/index.html

Thank you.

**Comment by Sniipe** [comment]
Hi @steved0x  sorry, I'm pretty new to this.  The Issue relates to [Syntax guidance for markdown usage->Embed Videos in a Wiki page](https://docs.microsoft.com/en-us/azure/devops/project/wiki/markdown-guidance?view=vsts#embed-videos-in-a-wiki-page)

**Comment by steved0x** [comment]
@Sniipe Thank you, for providing that, I have assigned this issue to the author of that article and they can help out. If that format is supported, we can update the documentation with the correct syntax.

**Comment by chcomley** [comment]
Hi @Sniipe Your link has the “embed” parameter missing in the URL. We'll be adding another example to our documentation. Thank you for your input.

**Comment by Sniipe** [comment]
perfect, I see how to do it now.  I have to add "/embed" before "/video" - on my ms stream video there is no way to find the embed url.  I figured it out after a quick search.

**Comment by shashicm** [comment]
> perfect, I see how to do it now. I have to add "/embed" before "/video" - on my ms stream video there is no way to find the embed url. I figured it out after a quick search.

Hi, Sniipe, I have the same problem, Isteam videos are not working in the wiki can you please let me know how you fixed it?

below is my wiki embed video. please help. 

::: video
<iframe src="https://000000.sharepoint.com/personal=StreamWebApp&referrerScenario=EmbedDialog.Create" width="640" height="360" frameborder="0" scrolling="no" allowfullscreen title="GIT - Team Explorer Branches - Local vrs Remote 2.mp4"></iframe>
:::


Thanks
Shashi

**Comment by cjazinski** [comment]
> > perfect, I see how to do it now. I have to add "/embed" before "/video" - on my ms stream video there is no way to find the embed url. I figured it out after a quick search.
> 
> Hi, Sniipe, I have the same problem, Isteam videos are not working in the wiki can you please let me know how you fixed it?
> 
> below is my wiki embed video. please help.
> 
> ::: video
> 
> <iframe src="https://000000.sharepoint.com/personal=StreamWebApp&referrerScenario=EmbedDialog.Create" width="640" height="360" frameborder="0" scrolling="no" allowfullscreen title="GIT - Team Explorer Branches - Local vrs Remote 2.mp4"></iframe> :::
> Thanks Shashi

I'm having the same issue as well. Works fine from YouTube.

**Comment by Thairam** [comment]
I have a video on sharepoint.

This is the sharing URL

`https://myorgcombr.sharepoint.com/:v:/s/MY-ORG20232024/EcIU7ZDgxPtDoKmPZDRUrxIBlMsXhWqmuRos7b_P4PDBig?e=E8LC12&nav=ayJyZ...
`

In Sharepoint there is an option "Insertion Code" where I can copy the code, similar to this:

`
<iframe src="https://myorgcombr.sharepoint.com/sites/MY-ORG20232024/_layouts/15/embed.aspx?UniqueId=90ed14c2-XXXX-...&embed=%7B%22ust%22%3Atrue%2C %22hv%22%3A%22CopyEmbedCode%22%7D&referrer=StreamWebApp&referrerScenario=EmbedDialog.Create" width="640" height="360" frameborder="0" scrolling="no"allowfullscreen title="My video on Sharepoint.mp4" </iframe>
`

I put this code on the Azure wiki, as way below and it worked fine.

`
::: video
<iframe src="https://myorgcombr.sharepoint.com/sites/MY-ORG20232024/_layouts/15/embed.aspx?UniqueId=90ed14c2-XXXX-...&embed=%7B%22ust%22%3Atrue%2C %22hv%22%3A%22CopyEmbedCode%22%7D&referrer=StreamWebApp&referrerScenario=EmbedDialog.Create" width="640" height="360" frameborder="0" scrolling="no"allowfullscreen title="My video on Sharepoint.mp4" </iframe>
:::
`
