### ISSUE TITLE
The Revision number doesn't have to have the "." in the format

### ISSUE THREAD

**Issue by alansingfield** [MicrosoftDocs/vsts-docs#2157]
You don't need the "." within the revision number format.
$(date:yyyyMMdd).$(rev:r) is the same as $(date:yyyyMMdd)$(rev:.r)
I wanted to start my revision numbers at 101 rather than 1, so I set the format to: 
$(date:yyyyMMdd).1$(rev:rr)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0fa5a83c-70fd-6925-a8c8-256b21c21a2e
* Version Independent ID: 75f4a136-7245-7878-2953-6b68272fe4ec
* Content: [Build pipeline options - Azure Pipelines & TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/options?view=vsts&tabs=yaml)
* Content Source: [docs/pipelines/build/options.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/build/options.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by alansingfield** [comment]
Probably the default format needs to be amended, going forward you could set it to:

$(date:yyyyMMdd).$(rev:r)
rather than
$(date:yyyyMMdd)$(rev:.r)

This wouldn't break anything would it?

**Comment by dagood** [comment]
I'm not sure if you're asking me the question--just in case: I don't know, I'm just another AzDO user. 😄 I'm just pointing out a very related doc issue that I imagine will be fixed at the same time as this one.

**Comment by alansingfield** [comment]
OK - understood!

**Comment by andyjlewis** [comment]
https://docs.microsoft.com/azure/devops/pipelines/process/run-number

Thank you for the suggestion. Apologies for the very delayed response.
