### ISSUE TITLE
Source code link to Apple Provisioning Profile task is broken

### ISSUE THREAD

**Issue by heaths** [MicrosoftDocs/vsts-docs#2161]
The link https://github.com/Microsoft/vsts-tasks/tree/master/Tasks/InstallAppleProvisioningProfile results in a 404. This is used under the heading https://docs.microsoft.com/en-us/azure/devops/pipelines/library/secure-files?view=vsts#how-can-i-create-a-custom-task-using-secure-files as an example of how to develop a task using a secureFile type.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 140dcb9a-2ed0-11d5-064b-068f863ed97f
* Version Independent ID: 672d2aa3-cf0d-9207-c97c-e2eba14506b7
* Content: [Secure files for Azure Pipelines and Team Foundation Server - Azure Pipelines & TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/library/secure-files?view=vsts)
* Content Source: [docs/pipelines/library/secure-files.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/library/secure-files.md)
* Product: **devops**
* GitHub Login: @erickson-doug
* Microsoft Alias: **madhurig**

**Comment by steved0x** [comment]
@heaths I believe [this](https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks/InstallAppleProvisioningProfileV1) is the correct link and I will verify that and get it fixed. Thanks for letting us know.

https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks/InstallAppleProvisioningProfileV1

**Comment by heaths** [comment]
That makes sense. I knew the project URLs changed but was getting redirected automatically. Apparently that only happens with the root project URL. Thanks.

**Comment by steved0x** [comment]
@heaths I verified this link and just made the fix and it should be live soon, thanks again for letting us know.
