### ISSUE TITLE
How to publish build artifacts using azure-pipelines.yml very hard to discover

### ISSUE THREAD

**Issue by foolip** [MicrosoftDocs/vsts-docs#2162]
There's nothing in this document, and searching I've mostly ended up here:
https://docs.microsoft.com/en-us/azure/devops/pipelines/release/artifacts?view=vsts

Which says nothing about azure-pipelines.yml. Finally, I found this:
https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/publish-build-artifacts?view=vsts

Perhaps the answer is within, it's not clear yet.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7458d5b2-1bb7-7d87-7ce6-2b0c430b0155
* Version Independent ID: edf5bbd3-a3f0-5426-e985-31290f8afd05
* Content: [YAML schema - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=vsts&tabs=schema)
* Content Source: [docs/pipelines/yaml-schema.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/yaml-schema.md)
* Product: **devops**
* GitHub Login: @erickson-doug
* Microsoft Alias: **macoope**

**Comment by elbatk** [comment]
Hi @foolip , thanks for the feedback.

I'm currently working on something that will help with this issue. Namely, I'm updating this document on build artifacts to include yaml instructions:
https://docs.microsoft.com/en-us/azure/devops/pipelines/build/artifacts?view=vsts

I believe the YAML schema document is fine, it covers the broader concept of "Tasks" in YAML and then links to this [catalog of tasks ](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/index?view=vsts)that you can use, which includes publishing build artifacts.

**Comment by foolip** [comment]
Great, that is the documentation I ended up at, so unless examples there would have been great.

**Comment by elbatk** [comment]
Closing this as I've made the update mentioned above and I think we are in a good spot :) please feel free to reach out if you think otherwise, @foolip !

**Comment by foolip** [comment]
@elbatk is it https://docs.microsoft.com/en-us/azure/devops/pipelines/build/artifacts?view=vsts that was updated?

Following the link from there to https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/build-artifacts?view=azure-devops&tabs=yaml does have an example, so that looks good. Thanks!
