### ISSUE TITLE
Add my wallet

### ISSUE THREAD

**Issue by chefsaroar** [MicrosoftDocs/vsts-docs#2164]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba91e46a-de53-c0c1-f7f7-c02e797d527c
* Version Independent ID: 6f478148-461f-694a-ed82-deb4d731854e
* Content: [Azure Pipelines and TFS Build and Test - Publish Test Results task - Azure Pipelines & TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/test/publish-test-results?view=vsts&tabs=yaml#yaml-snippet)
* Content Source: [docs/pipelines/tasks/test/publish-test-results.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/test/publish-test-results.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by chefsaroar** [comment]
ba91e46a-de53-c0c1-f7f7-c02e797d527c

**Comment by chefsaroar** [comment]
6f478148-461f-694a-ed82-deb4d731854e

**Comment by chefsaroar** [comment]
Please chick my bitcoin.

**Comment by IanKemp** [comment]
why is this trash not closed
