### ISSUE TITLE
 Migration path?

### ISSUE THREAD

**Issue by grahambunce** [MicrosoftDocs/vsts-docs#2169]
The most worrying aspect for any organisation is migrating from Microsoft Accounts to Azure AD. What’s the process, what will be lost, will we retain audit trails, change history, work item.... can I have Azure AD and Microsoft accounts as an interim? What if the Microsoft account and AD account is the same email address? Etc

There needs to be guide on this process - we want to change but as an early adopter we had to use Microsoft Accounts; now we have 30 developers across the globe and the perceived risk to our business is high

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 39c81ce4-7085-f5cd-e29a-e434074d449a
* Version Independent ID: e9bbaf41-404e-d1b7-5e39-33b68ffe7ef0
* Content: [Azure DevOps access with Azure AD groups](https://docs.microsoft.com/en-gb/azure/devops/organizations/accounts/manage-azure-active-directory-groups?view=vsts&tabs=new-nav)
* Content Source: [docs/organizations/accounts/manage-azure-active-directory-groups.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/accounts/manage-azure-active-directory-groups.md)
* Product: **devops**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @grahambunce thanks for your message. There is a guide on this process and answers to your questions here: https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/connect-organization-to-azure-ad?view=vsts&tabs=new-nav.
Please let us know if you have any other questions or concerns - I've filed a work item to ensure the tutorial is linked to from the Manage Azure Active Directory Groups topic, where you began.
