### ISSUE TITLE
Consuming in Visual Studio Code

### ISSUE THREAD

**Issue by garfbradaz** [MicrosoftDocs/vsts-docs#2170]
Hey Guys,

Any similar instructions for Visual Studio Code?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 899a78d6-9d08-7744-108d-10add2ba7e2c
* Version Independent ID: 6ab31e96-fed8-4335-ed81-b97663d8300f
* Content: [Consume NuGet packages in Visual Studio](https://docs.microsoft.com/en-gb/azure/devops/artifacts/nuget/consume?view=vsts&tabs=new-nav)
* Content Source: [docs/artifacts/nuget/consume.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/artifacts/nuget/consume.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by elbatk** [comment]
Hi @garfbradaz , we currently don't have any plans to add documentation for consuming NuGet packages in VS Code, but I think it's a good idea. I'll reach out to the PM to see if we can't add something to the backlog, thank you!

**Comment by JoeBrockhaus** [comment]
@elbatk Any update on this?

**Comment by elbatk** [comment]
@JoeBrockhaus funny enough, after a role change, I'm now the PM that I originally planned on reaching out to. I'm learning towards the mindset that this sort of documentation would fall more in the VS Code area, but I'd love to sync with someone on their docs team. I'll make it a point to do that in this quarter - we're pretty booked over the next couple of sprints.

**Comment by garfbradaz** [comment]
Should be keep this one open @elbatk?

**Comment by elbatk** [comment]
@garfbradaz I think so, reopening.

**Comment by pascaljr** [comment]
I'm using Microsoft Artifacts Provider, and it works well. Below is the link
https://github.com/microsoft/artifacts-credprovider

**Comment by elbatk** [comment]
So, I talked to the VS Code docs team, and we're not sure how/where to add documentation for this. VS Code doesn't have a special package manager for Azure Artifacts like VS IDE does, so the basic support for consuming through VS Code would to be to use the dotnet CLI like you would from a command line. What information would you all like to see and where would you want to find it?

**Comment by elbatk** [comment]
Going to close this as I haven't gotten a response in a bit :)
