### ISSUE TITLE
Visual Code Instructions

### ISSUE THREAD

**Issue by garfbradaz** [MicrosoftDocs/vsts-docs#2171]
Are there instruction on how to accomplish this in Visual Studio Code?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 899a78d6-9d08-7744-108d-10add2ba7e2c
* Version Independent ID: 6ab31e96-fed8-4335-ed81-b97663d8300f
* Content: [Consume NuGet packages in Visual Studio](https://docs.microsoft.com/en-gb/azure/devops/artifacts/nuget/consume?view=vsts&tabs=new-nav)
* Content Source: [docs/artifacts/nuget/consume.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/artifacts/nuget/consume.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by elbatk** [comment]
Hi everyone, sorry for the delay. We do not currently have documentation plans to cover consuming in VS Code. I'm going to add @mitchdenny to possibly add notes about the scenario. This is related to #2170 . Closing this for now, but we'll see what Mitch says (I believe he's out of the office today).
