### ISSUE TITLE
Scope Info for vss-extension.json

### ISSUE THREAD

**Issue by tmcoma** [MicrosoftDocs/vsts-docs#2172]
In case anyone else gets tripped up here, I had to add this property to my vss-extension.json

 "scopes": ["vso.work"],

in order to use "TFS/WorkItemTracking/RestClient"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0f99e26d-54fa-ac2c-1814-e1b3f97a87b5
* Version Independent ID: 0ed84e7f-b46f-3a44-16f6-d9bcf77bf11d
* Content: [How to Call a REST API](https://docs.microsoft.com/en-us/azure/devops/extend/develop/call-rest-api?view=vsts)
* Content Source: [docs/extend/develop/call-rest-api.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/extend/develop/call-rest-api.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by elbatk** [comment]
Ahh, I'll add this as a note @tmcoma , thanks!
