### ISSUE TITLE
Link is not displayed properly

### ISSUE THREAD

**Issue by shayki5** [MicrosoftDocs/vsts-docs#2173]
Under "Helpful links" the first link is not displayed properly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b3d1eca9-3a6d-e9e5-c424-30f4d4b8b544
* Version Independent ID: 2b542142-15dd-c4ad-8dde-c3df0b6204c8
* Content: [Developing extensions for Azure DevOps Services and Team Foundation Server](https://docs.microsoft.com/en-us/azure/devops/extend/overview?view=vsts)
* Content Source: [docs/extend/overview.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/extend/overview.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by elbatk** [comment]
Ah, this has been fixed so closing :) Thank you!
