### ISSUE TITLE
Issue with code coverage and multi-module project. 

### ISSUE THREAD

**Issue by err108** [MicrosoftDocs/vsts-docs#2174]
I can't seem to find any good documentation on or examples using the code coverage arguments.   My project consists of a parent pom with multiple modules.  Build is executed on the parent pom.  I've supplied a list of paths in the codeCoverageClassFilesDirectories and codeCoverageSourceDirectories based on the tooltip help in the build configuration.  However when the build runs, it fails with the following errors/warnings: 

"An Ant BuildException has occured: Unable to read execution data file C:\agent\_work\20\s\CCReport43F6D5EF\jacoco.exec"

"No code coverage found to publish. There might be a build failure resulting in no code coverage or there might be no tests."

It either isn't generating any code coverage reports, or can't aggregate the reports from the child modules.  Tests are publishing fine and I can see the results aggregated for of all the tests run in the child modules.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 589e076c-9f67-77df-3204-4f549566f21b
* Version Independent ID: 2e51ef13-8fd3-1397-82f0-27c92f1ccee5
* Content: [Maven build and release task - Azure Pipelines & TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/maven?view=vsts#feedback)
* Content Source: [docs/pipelines/tasks/build/maven.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/build/maven.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by DavidStaheli** [comment]
Keep-alive

**Comment by davidstaheli** [comment]
Thanks for reporting this. We're going to move this issue to this repo for better tracking and visibility:
https://github.com/Microsoft/azure-pipelines-tasks

/move to Microsoft/azure-pipelines-tasks
