### ISSUE TITLE
The "Set up authentication" section looks out of date

### ISSUE THREAD

**Issue by jamesw966** [MicrosoftDocs/vsts-docs#2179]
The "Set up authentication" section looks out of date

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 38bbae0b-c29c-0325-ad4d-868a4f2ab13a
* Version Independent ID: b9d492af-0137-5761-fb38-95da18c7b402
* Content: [Install a Maven artifact using Gradle and Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/artifacts/gradle/pull-package-gradle?view=vsts)
* Content Source: [docs/artifacts/gradle/pull-package-gradle.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/artifacts/gradle/pull-package-gradle.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by elbatk** [comment]
You are right - this is from the previous navigation, adding the new one alongside this right now, thanks!
