### ISSUE TITLE
Don't recommend keeping nuget packages in source control

### ISSUE THREAD

**Issue by jawn** [MicrosoftDocs/vsts-docs#218]
The following tip seems obsolete:
"Even if you decide to use NuGet, you should probably still add the binaries to version control so that you can reproduce and build historical versions of your code."

This seems to be an outdated recommendation. Especially when using git repos, you want to keep the repos small, as documented in https://docs.microsoft.com/en-us/nuget/consume-packages/packages-and-source-control

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6221f95f-b9c3-10d5-63d8-ba6182185dca
* Version Independent ID: cee686a8-5600-3e7a-3f1e-c6cfc28ec65b
* [Content](https://docs.microsoft.com/en-us/vsts/tfvc/add-files-server)
* [Content Source](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/tfvc/add-files-server.md)
* Service: unspecified

**Comment by steved0x** [comment]
@jawn Sorry for the delay in responding to this, we just implemented a new feedback control that files customer feedback as GitHub issues (which I really like) but as a result we started off with a bit of a backlog. I've added this to our TFVC documentation backlog and I'll get this updated shortly. Thank you.

**Comment by steved0x** [comment]
@jawn I just checked in an update to this topic, it should be live soon.
