### ISSUE TITLE
Why is the Task Called PublishTestResults@2?

### ISSUE THREAD

**Issue by RehanSaeed** [MicrosoftDocs/vsts-docs#2181]
I have seen the similar yaml in several places in the docs:

```
# Publish Test Results to Azure Pipelines/TFS
- task: PublishTestResults@2
```

Is the name `PublishTestResults` significant? Is there a list of pre-defined tasks? If so, the search cannot find them.

Also, what is the significance of the number after the `@` sign? Once again, I can't find any docs for it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba91e46a-de53-c0c1-f7f7-c02e797d527c
* Version Independent ID: 6f478148-461f-694a-ed82-deb4d731854e
* Content: [Azure Pipelines and TFS Build and Test - Publish Test Results task - Azure Pipelines & TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/test/publish-test-results?view=vsts&tabs=yaml)
* Content Source: [docs/pipelines/tasks/test/publish-test-results.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/test/publish-test-results.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment]
The list of tasks is at https://docs.microsoft.com/azure/devops/pipelines/tasks/. These are built-in or extension tasks that are executed within Azure Pipelines or a TFS build or release process. The number after the task name indicates the task version number. You can choose which version of a task you want to use. Tasks can be viewed and added to a pipeline in the designer (UI) view of a build or release in Azure DevOps or TFS.
