### ISSUE TITLE
If dotnet test fails in a Docker build, you get no test results

### ISSUE THREAD

**Issue by RehanSaeed** [MicrosoftDocs/vsts-docs#2183]
When `dotnet test` fails, it returns a non-zero exit code which will mean that building the Dockerfile in the docs will fail and you will not get any test results out of the build. The only time you would get test results is if all tests succeeded.

```
FROM microsoft/dotnet:2.1-sdk
WORKDIR /app
COPY . ./
RUN dotnet restore
RUN dotnet build -c Release
RUN dotnet test dotnetcore-tests/dotnetcore-tests.csproj -c Release --logger "trx;LogFileName=testresults.trx"
RUN dotnet publish -c Release -o out
ENTRYPOINT dotnet dotnetcore-sample/out/dotnetcore-sample.dll
```

Am I missing something?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba91e46a-de53-c0c1-f7f7-c02e797d527c
* Version Independent ID: 6f478148-461f-694a-ed82-deb4d731854e
* Content: [Azure Pipelines and TFS Build and Test - Publish Test Results task - Azure Pipelines & TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/test/publish-test-results?view=vsts&tabs=yaml)
* Content Source: [docs/pipelines/tasks/test/publish-test-results.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/test/publish-test-results.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment]
Thank you for your feedback. I have passed this on to the product team for advice.

**Comment by PBoraMSFT** [comment]
@RehanSaeed - can you please report this on the test platform repo? 
https://github.com/microsoft/vstest/

@vinodjo - can you look at this docker scenario please?

**Comment by olaj** [comment]
Is this fixed somewhere? Any recommendations how to solve this issue?

**Comment by olaj** [comment]
I've added "exit 0" to the end of this line as this: RUN dotnet test MyProject.Tests.csproj -c Release --logger "trx;LogFileName=testresults.trx"; exit 0

**Comment by chamindac** [comment]
> I've added "exit 0" to the end of this line as this: RUN dotnet test MyProject.Tests.csproj -c Release --logger "trx;LogFileName=testresults.trx"; exit 0

This did not work for me as there was returns a non-zero exit code with msbuild in a Windows container.
I got below error
 `MSBUILD : error MSB1008: Only one project can be specified.`
 
 But below fixed the issue for me in a Windows container using `|| exit 0` instead of `; exit 0`.
 
 RUN dotnet test "MyTests/My.Tests.csproj" -c Release -r win-x64 --no-restore --logger "trx;LogFileName=/src/testresults/My.Tests.Docker.trx" || exit 0
