### ISSUE TITLE
Disabling an upstream feed

### ISSUE THREAD

**Issue by davidroberts63** [MicrosoftDocs/vsts-docs#2184]
How does one disable an upstream feed? Mentioned in the `Offline upstreams` section. I see nothing to 'disable' a feed. Only to delete. Perhaps delete a feed and then add it once it's online is the approach which was meant?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d5f022df-36c3-34b1-cac1-ac33995a7d73
* Version Independent ID: 9634b0c8-7b14-4453-2c04-aedabbf331f1
* Content: [Upstream sources](https://docs.microsoft.com/en-us/azure/devops/artifacts/concepts/upstream-sources?view=vsts#upstream-metadata-cache)
* Content Source: [docs/artifacts/concepts/upstream-sources.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/artifacts/concepts/upstream-sources.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by elbatk** [comment]
You are right, I'm switching it to "delete" and "re-add" in a PR coming up soon :) Thanks!
