### ISSUE TITLE
Is the name azure-pipelines.docker.yml Significant?

### ISSUE THREAD

**Issue by RehanSaeed** [MicrosoftDocs/vsts-docs#2185]
Is the name `azure-pipelines.docker.yml` or `azure-pipelines.acr.yml` significant?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e825c07d-2168-c0aa-782a-ef6f9c7ba95e
* Version Independent ID: 5cb6926b-215a-bf89-8e63-b2e1129e41df
* Content: [Docker - Azure Pipelines & TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/languages/docker?view=vsts&tabs=yaml)
* Content Source: [docs/pipelines/languages/docker.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/languages/docker.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by vijayma** [comment]
No, it is not. We just had to put multiple variations of azure-pipelines.yml file in the sample repo. Depending on your need, we expect you to pick the right one, and rename it to azure-pipelines.yml.
