### ISSUE TITLE
How to write unit-test for powershell task scripts?

### ISSUE THREAD

**Issue by arefinsami** [MicrosoftDocs/vsts-docs#2187]
This example here shows unit testing for a Node js task. But my task is implemented using Power Shell. Is there a similar thing/framework for that? Also, is there a way to do unit testing of a gate task?
Thanks. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 44581f4a-93df-7507-3844-eadedf9a6cc4
* Version Independent ID: 33c7bcf0-1512-975f-5ef8-9f2a192a84ad
* Content: [Add a Build or Release Task](https://docs.microsoft.com/en-us/azure/devops/extend/develop/add-build-task?view=vsts#createtask)
* Content Source: [docs/extend/develop/add-build-task.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/extend/develop/add-build-task.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by nschonni** [comment]
Generally, Pester is probably the biggest for PowerShell testing https://github.com/pester/Pester.
I've found most unit testing around TFS extensions to be difficult

**Comment by elbatk** [comment]
Hi @arefinsami , I'm going to reach out to the product team member that helped write this article for some help. I'm hoping that he has some insight.

**Comment by elbatk** [comment]
Hi @arefinsami , so yeah, it seems that we default to Node as it's cross platform and where most of our 1st party tasks are authored. We don't really have a strong opinion on unit-testing frameworks for other types, but it looks like Pester (mentioned above) is the community standard.
