### ISSUE TITLE
Don't see "change work item type" option despite using VSTS

### ISSUE THREAD

**Issue by jlian** [MicrosoftDocs/vsts-docs#219]
Hi, in the documentation it says that the "change work item type" feature is available to VSTS customers. We're using VSTS but for some reason can't see the option in the dropdown menu. It doesn't say in the documentation what the cause could be and how I might resolve it.

This is what I see 
![image](https://user-images.githubusercontent.com/2320572/36744692-53c9bb5c-1ba2-11e8-9012-66d5636dc5b0.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 381ce2dc-5c1b-0ab7-1a2d-2a6e03e63d9c
* Version Independent ID: 6551b454-1091-65e2-2de0-4b1bbda04e4a
* [Content](https://docs.microsoft.com/en-us/vsts/work/backlogs/remove-delete-work-items?tabs=browser#change-type)
* [Content Source](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/work/backlogs/remove-delete-work-items.md)
* Service: unspecified

**Comment by KathrynEE** [comment]
@jlian - if you are indeed on a VSTS account and not a TFS server, then this is odd. I recommend that you contact technical support and have them troubleshoot the issue. https://www.visualstudio.com/team-services/support/
