### ISSUE TITLE
The pro tip is really annoying!

### ISSUE THREAD

**Issue by kgreed** [MicrosoftDocs/vsts-docs#2195]
So I should not be learning the visual designer it seems.  Then I press the link to create the first pipeline and it takes me  back to the section I have just completed.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 02b747eb-53c2-dd5f-cd2b-f337c15e0864
* Version Independent ID: 04538505-00cd-33ac-8008-4b85cca089e3
* Content: [Use the visual designer to create a CI/CD pipeline - Azure Pipelines & TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/get-started-designer?view=vsts&tabs=new-nav)
* Content Source: [docs/pipelines/get-started-designer.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/get-started-designer.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by elbatk** [comment]
Hi @kgreed , the visual designer quickstart and the "create your first pipeline" quickstart cover the same goal, creating a pipeline. It's not a linear progression, you can choose one or the other, and we recommend using YAML for a couple of different reasons. 

Am I misunderstanding? When you say the section you have just completed are you referring to the YAML guide?

**Comment by kgreed** [comment]
Yes. I guess the link does make sense to have  if you arrive at the page via search.
Because I never learned TFS I am learning the visual designer for the first time and it is really off putting to be told that you recommend not using it.  Why should I bother learning it then?

**Comment by vijayma** [comment]
At this point, we have customers that are using the designer. We would like all new customers to use YAML, and for existing customers to think about YAML pipelines for the benefits that they provide. But, we understand that YAML is not necessarily what every customer wants. As a new user looking at our service, I am assuming you are open to using either of these approaches. Is that correct? How can we communicate this message better to you? In one place? On each page? Through tabs on each page? Thanks for sharing your thoughts.
