### ISSUE TITLE
The link  "Add a script to your repository " simply refreshes the page 

### ISSUE THREAD

**Issue by kgreed** [MicrosoftDocs/vsts-docs#2196]
Why have it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 02b747eb-53c2-dd5f-cd2b-f337c15e0864
* Version Independent ID: 04538505-00cd-33ac-8008-4b85cca089e3
* Content: [Use the visual designer to create a CI/CD pipeline - Azure Pipelines & TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/get-started-designer?view=vsts&tabs=new-nav)
* Content Source: [docs/pipelines/get-started-designer.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/get-started-designer.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by elbatk** [comment]
Ah, sorry about that. That link is supposed to take you to the step labeled "Add a script to your repository" so you don't have to waste time on a "set-up" step that you may have already done. Fixing it now :)

**Comment by kgreed** [comment]
Thanks
