### ISSUE TITLE
The instruction to turn off the preview feature should be at the top

### ISSUE THREAD

**Issue by kgreed** [MicrosoftDocs/vsts-docs#2197]
putting it at the end of point 2 makes the beginning of point 3 out of context.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 02b747eb-53c2-dd5f-cd2b-f337c15e0864
* Version Independent ID: 04538505-00cd-33ac-8008-4b85cca089e3
* Content: [Use the visual designer to create a CI/CD pipeline - Azure Pipelines & TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/get-started-designer?view=vsts&tabs=new-nav)
* Content Source: [docs/pipelines/get-started-designer.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/get-started-designer.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by elbatk** [comment]
Hey @kgreed , sorry for the delay. I think this step is fine where it is, it's a little bit of a detour, but if it's in the beginning, it could also be out of context.
