### ISSUE TITLE
What is meant by 5) Go to the Code hub, Files tab?

### ISSUE THREAD

**Issue by kgreed** [MicrosoftDocs/vsts-docs#2198]
What is the Code hub?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 02b747eb-53c2-dd5f-cd2b-f337c15e0864
* Version Independent ID: 04538505-00cd-33ac-8008-4b85cca089e3
* Content: [Use the visual designer to create a CI/CD pipeline - Azure Pipelines & TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/get-started-designer?view=vsts&tabs=new-nav)
* Content Source: [docs/pipelines/get-started-designer.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/get-started-designer.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by elbatk** [comment]
The Code hub is where you access your files, branches, pull requests, etc. in TFS and in the previous navigation of Azure DevOps. It is called "Azure Repos" in Azure DevOps. I could probably change it to Azure Repos and then mention the Code hub.

**Comment by kgreed** [comment]
So it is in Visual Studio ?

**Comment by elbatk** [comment]
If you look at the [initial step of "Initialize your repository",](https://docs.microsoft.com/en-us/azure/devops/pipelines/get-started-designer?view=vsts&tabs=new-nav#intialize-your-repository) you can get some grounding around what this is referring to. 

When VSTS became Azure DevOps, the UI was also updated. Currently, we allow users to use this new UI (New navigation), or they can turn it off in the Preview Features and use the old nav (Previous navigation). Currently, the latest iteration of TFS matches the old nav of Azure DevOps.

Some helpful info:
* [Azure Repos documentation](https://docs.microsoft.com/en-us/azure/devops/repos/?view=vsts)
* [Preview Features (including new navigation update)](https://docs.microsoft.com/en-us/azure/devops/project/navigation/preview-features?view=vsts&tabs=new-nav)
* [Blog post about UI update](https://blogs.msdn.microsoft.com/devops/2018/09/24/navigation-update-for-azure-devops/)

**Comment by elbatk** [comment]
I'm updating that bullet to say "Go to Azure Repos" if you're reading the Azure DevOps version of this article, so that should be a little more clear. Thanks for the input, closing this issue as I think that'll solve this confusion.
