### ISSUE TITLE
'Sliding window of team iterations' behaves not as expected

### ISSUE THREAD

**Issue by Megadesty** [MicrosoftDocs/vsts-docs#2201]
The example query under _Query for items based on a sliding window of team iterations_ doesn't seem to work for me because there is no work item in `@CurrentIteration - 2` _and_ `@CurrentIteration` _and_ `@CurrentIteration + 2`. Also even if I use _or_ instead of _and_, the work items from `@CurrentIteration - 1` and `@CurrentIteration + 1` are not returned.
Am I or is the example doing something wrong?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba14ee34-2de7-706f-ae44-be969fde352b
* Version Independent ID: f7ba18e9-42e4-ef07-e36b-377fb787aa72
* Content: [Query by date or current iteration - Azure Boards and TFS](https://docs.microsoft.com/en-us/azure/devops/boards/queries/query-by-date-or-current-iteration?view=vsts#query-for-items-based-on-belonging-to-a-teams-current-iteration)
* Content Source: [docs/boards/queries/query-by-date-or-current-iteration.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/boards/queries/query-by-date-or-current-iteration.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@Megadesty - Thank you for your inquiry.  I'm updating the topic with the following notes: 

For the **@CurrentIteration** macro to work, the team must have selected an Iteration Path whose date range encompasses the current date. For details, see [Define iteration paths (aka sprints) and configure team iterations](https://docs.microsoft.com/en-us/azure/devops/organizations/settings/set-iteration-paths-sprints?view=azure-devops&tabs=new-nav#select-team-sprints-and-default-iteration-path). Also, queries that contain this macro are only valid when run from the the web portal.

For the **@CurrentIteration +/- n** macro to work, the team must have selected Iteration Paths that meet the +/- n criteria and date ranges encompass the current date for the **@CurrentIteration**. Also, queries contain this macro are only valid when run from the the web portal. For details about team selection of Iteration Paths, see [Define iteration paths (aka sprints) and configure team iterations](https://docs.microsoft.com/en-us/azure/devops/organizations/settings/set-iteration-paths-sprints?view=azure-devops&tabs=new-nav#select-team-sprints-and-default-iteration-path). 

See also the section [Client restrictions on the use of the @CurrentIteration macros](https://docs.microsoft.com/en-us/azure/devops/boards/queries/query-by-date-or-current-iteration#current_sprint_restrict) later in the article.
