### ISSUE TITLE
Email aliases?

### ISSUE THREAD

**Issue by seeafish** [MicrosoftDocs/vsts-docs#2205]
I seem to remember that you could set email aliases in your profile before (similar to github) on your  account, so that your commits from a different email in your gitconfig would be picked up as you. This doesn't seem to exist in the new profile section.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d28a6661-50d4-527e-9727-ab5974da951d
* Version Independent ID: fdac329a-b9b4-77d0-916a-dee6d2576379
* Content: [View and change your user preferences - Azure DevOps & TFS](https://docs.microsoft.com/en-us/azure/devops/organizations/settings/set-your-preferences?view=vsts&tabs=new-nav)
* Content Source: [docs/organizations/settings/set-your-preferences.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/settings/set-your-preferences.md)
* Product: **devops**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @seeafish thanks for letting us know. I am looking into it and will respond back to this issue as soon as possible.

**Comment by chcomley** [comment]
@seeafish We have always had support for a “contact email,” which is where notifications are directed.  We use this email when authoring commits (e.g. web commits, PR merge commits).  So, this leads to situations where users might be creating commits with multiple emails and they appear as coming from the same user.  But we never had a feature where you could add multiple email addresses in your profile to map them to your identity.

**Comment by seeafish** [comment]
I am fairly sure it was there. The reason I say this is that on my corporate VSTS my commits are recognised as me (i.e. my corporate profile) even though my gitconfig uses my personal email. This wouldn't work unless VSTS had my private email stored as well. No matter what git tool I use (gitlan, github, bitbucket), the first thing I do is add an email alias so that I can use my standard gitconfig anywhere. 
Of course I can't show where in VSTS it was, but in case there's confusion, it's similar to this page on GitHub https://github.com/settings/emails

If you're 100% it didn't exist, I'd be curious to know how can I commit using a different email yet still have my commits show up as me (name and display pic) on VSTS?

Thanks.

**Comment by chcomley** [comment]
Glad you got it figured out. You can go here to see the Azure DevOps Features Timeline: https://docs.microsoft.com/en-us/azure/devops/release-notes/ 
And you can go here to request a feature: https://developercommunity.visualstudio.com/content/idea/post.html?space=21
Hope this helps, thanks.
