### ISSUE TITLE
Missing Git as an Artifact Source option for Release source

### ISSUE THREAD

**Issue by iaincbeat** [MicrosoftDocs/vsts-docs#2209]
The documentation and the picture provided indicate that any external Git should be available as as an artifact source for release artifacts, however there only seems to be an option for GitHub and an external addon for GitLab, nothing for just a plain, ordinary external Git itself.

**Comment by steved0x** [comment]
@iaincbeat Can you let me know the URL of the article that had the statement and picture and I will assign this to the author to have a look.

Is it this one?

https://docs.microsoft.com/en-us/azure/devops/pipelines/release/artifacts?view=vsts#sources

@alexhomer1 Please reassign if @iaincbeat replies back that this is not the right article.

**Comment by alexhomer1** [comment]
Thank you for your feedback. I have passed this on to the product team for advice and update the topic.

**Comment by alexhomer1** [comment]
In a release pipeline you can add artifacts from GitHub and Azure Repos (including a TFS Git repo). The product team tell me that you cannot add other types of Git repo as an artifact in Azure Pipelines.
