### ISSUE TITLE
Screenshots for Agentless Phase show two tasks in one Agentless Phase

### ISSUE THREAD

**Issue by hintbw** [MicrosoftDocs/vsts-docs#221]
The screenshots for the Agentless Phase show two tasks in one Agentless Phase, but that is not possible. When a user tries to save it will not let the release definition be saved with multiple tasks in one Agentless phase. The screenshots should be updated and it would be useful to call out the current limitation of allowing one one task per agentless phase in text right below the section header.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 54bf6c2f-95c1-943d-26ae-d7099143bccf
* Version Independent ID: 0833bb55-1e54-6953-ee69-de6d191d2ec1
* [Content](https://docs.microsoft.com/en-us/vsts/build-release/concepts/process/phases#agentless-phase)
* [Content Source](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/build-release/concepts/process/phases.md)
* Service: unspecified

**Comment by alexhomer1** [comment]
Thank you. I will update the screenshots and check with the development team whether the limitation is just temporary or permanent.
