### ISSUE TITLE
How to handle 404 errors in extension API?

### ISSUE THREAD

**Issue by tmcoma** [MicrosoftDocs/vsts-docs#2210]
The docs say "If this collection does not exist or a document with that ID does not exist, then a 404 will be returned, which should be handled by the extension," but it is not clear to me how this is to be done.  The promise returned by the API's get methods has a "then" callback and nothing else.  When I request a document that hasn't been created, I see the 404 in the browser's console, but the callback I registered through the promise doesn't get called, and wrapping the entire call in a try/catch doesn't seem to get me anywhere.  Is there somewhere I'm supposed to register something to handle a 404?

VSS.getService(VSS.ServiceIds.ExtensionData).then(function (dataService) {
  try {
    var id = '1234' // not a real id
    dataService.getDocument('CorrelationDoc', id).then(function (doc) {
      // never called
      console.log(doc)
    })
  } catch (e) {
    // also never called
    console.log('oh no!')
    console.log(e)
  }
})

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8490096d-54dd-697b-62a3-9c930d0733d1
* Version Independent ID: 04f42aed-a8c2-f124-1c32-37daf54e8400
* Content: [Data and Setting Storage](https://docs.microsoft.com/en-us/azure/devops/extend/develop/data-storage?view=vsts)
* Content Source: [docs/extend/develop/data-storage.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/extend/develop/data-storage.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by tmcoma** [comment]
Looking further, I now see that "then" takes two arguments, the second one being an error handler.
```javascript
dataService.getDocument('CorrelationDoc', id)
.then(function (doc) {
	console.log(doc)
}, function (err) {
	console.log(err)
})

```

**Comment by riezebosch** [comment]
This should be part of the documentation and not hidden in closed comments! Spend some time to figure it out myself only to found this comments afterward!

**Comment by adamtoakley** [comment]
> This should be part of the documentation and not hidden in closed comments! Spend some time to figure it out myself only to found this comments afterward!

This is part of standard promise architecture, `getDocument()` returns a promise so it can be assumed that the second parameter for the `.then()` is the promise rejection

See this link for more info: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/then

**Comment by riezebosch** [comment]
Maybe but then it should also be possible to [catch](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/catch). My guess is it has to do with Q being used instead of native promises.

**Comment by adamdavies001** [comment]
> This is part of standard promise architecture, getDocument() returns a promise so it can be assumed that the second parameter for the .then() is the promise rejection

@adamtoakley That's a horrible presumption. The purpose of documentation is to be explicit about the usage of a feature; there should be no assumptions here. The error callback function needs to be included in the documentation.

**Comment by jithureddy** [comment]
@adamdavies001 If this error is due to collection then how to create that collection. Which is not explained in the documentation.
