### ISSUE TITLE
Any ETA on .coverage Format Support

### ISSUE THREAD

**Issue by RehanSaeed** [MicrosoftDocs/vsts-docs#2211]
I am using Cake build and not the VS tasks for my build and running tests. Therefore, I can't easily use the `VSTest` task which seems to include support for `.coverage` file formats. Instead I would like to use the `PublishCodeCoverageResults` task instead but this does not support the `.coverage` file format. Is there any ETA on when this support would be added?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6ac4ff4-9839-6a6d-8d20-a25084d221ef
* Version Independent ID: bd09f139-8e69-8ea1-6671-b7bba8e17c23
* Content: [Publish Code Coverage Results task - Azure Pipelines & TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/test/publish-code-coverage-results?view=vsts)
* Content Source: [docs/pipelines/tasks/test/publish-code-coverage-results.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/test/publish-code-coverage-results.md)
* Product: **devops**
* GitHub Login: @erickson-doug
* Microsoft Alias: **vinojos**

**Comment by PBoraMSFT** [comment]
@RehanSaeed - can you please file this enhancement issue on the tasks repo? 
https://github.com/Microsoft/azure-pipelines-tasks

This repo tracks documentation issues, so I am closing this one out.
