### ISSUE TITLE
No where near enough information on permissions

### ISSUE THREAD

**Issue by pthorsley** [MicrosoftDocs/vsts-docs#2213]
Please add real permissions detail, not just a one or two sentence ambiguous sentence....."Has permissions to contribute fully to the project code base and work item tracking.". Please describe what they have access to, link a grid to this sentence at the very least so we can know exactly what they can access.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 68686c2b-c69a-d9e4-3e21-a46d231b649c
* Version Independent ID: 049659da-1772-3166-f909-4feeb8a97730
* Content: [Permissions and groups reference - Azure DevOps & TFS](https://docs.microsoft.com/en-us/azure/devops/organizations/security/permissions?view=vsts)
* Content Source: [docs/organizations/security/permissions.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/security/permissions.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@pthorsley - Thank you for the feedback. I have added a backlog item to update the content within the coming weeks.
