### ISSUE TITLE
Is the screen dump out of date for devops?

### ISSUE THREAD

**Issue by kgreed** [MicrosoftDocs/vsts-docs#2214]
&gt;&gt; Navigate to the Files tab of the Code hub, and then click Set up build.
I cant seem to find a screen looking like this

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b846f94-2bb5-d5a8-63c8-8227ab1b613b
* Version Independent ID: 5ba1aaac-6076-c5e0-fec0-c2ac2405b138
* Content: [Build your Universal Windows Platform app - Azure Pipelines & TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/apps/windows/universal?view=vsts&tabs=vsts)
* Content Source: [docs/pipelines/apps/windows/universal.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/apps/windows/universal.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by andyjlewis** [comment]
Thank you for posting this issue. Apologies for the very delayed response. I've added this request to our backlog.
