### ISSUE TITLE
Missing Python versions 3.5, 3.6, 3.7 for x86 architecture

### ISSUE THREAD

**Issue by spacether** [MicrosoftDocs/vsts-docs#2216]
Though the docs[ list x86 as a valid python system architecture](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/use-python-version?view=vsts), the tool cache is missing:
Python versions 3.5, 3.6, 3.7 for x86 architecture in Ubuntu 16.04 and macOS-10.13

Please add the x86 Python versions to the tool cache for the above operating systems.

**Comment by DavidStaheli** [comment]
Hi @spacether.  Thank you for posting this.  Apologies for taking so long to get back to you.  I moved this issue to the repo where we track enhancements needed to the Microsoft-hosted build images ([here](https://github.com/Microsoft/azure-pipelines-image-generation/issues/365)).  Thanks again!

**Comment by brcrista** [comment]
@DavidStaheli , can we reopen this?  I would consider this a docs issue.  We should add more detail to how people can see what versions of Python are on the agents.

Also, the `architecture` param on the task is optional.

**Comment by DavidStaheli** [comment]
The docs are now updated to clarify that Python x86 versions are available on Microsoft-hosted Windows, but not Linux nor macOS.  The updates should be live later today.
