### ISSUE TITLE
The UI should use the same terminology as the docs.

### ISSUE THREAD

**Issue by kgreed** [MicrosoftDocs/vsts-docs#2218]
The docs talk about "process parameters" where as the UI talks about "parameters"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 214c853e-63ba-240c-9cff-7ea3ab7a788c
* Version Independent ID: 781b5018-0c34-353a-a035-5d84af3994a0
* Content: [Process parameters - Azure Pipelines & TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/parameters?view=vsts)
* Content Source: [docs/pipelines/process/parameters.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/parameters.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by andyjlewis** [comment]
Thank you for the suggestion. I'm sorry for the very long delay in response. Please request product enhancements here: https://developercommunity.visualstudio.com/spaces/21/index.html
