### ISSUE TITLE
Deployment Groups for PaaS?

### ISSUE THREAD

**Issue by asmagin** [MicrosoftDocs/vsts-docs#2219]
What if I need to do blue/green deployment in PaaS or I have multiple App Services in one environment?
Can I leverage deployment groups and how?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3b38c265-be4c-b038-e3a9-783a5e5ce659
* Version Independent ID: 67da69da-3651-a8f4-f06a-c35aa3aa98fc
* Content: [Deployment groups in Azure Pipelines - Azure Pipelines & TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/deployment-groups/?view=vsts)
* Content Source: [docs/pipelines/release/deployment-groups/index.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/release/deployment-groups/index.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment]
Thank you for your feedback. I have passed this on to the product team for advice.

**Comment by DanielBMann9000** [comment]
Deployment groups are for servers, not PaaS services. If you need to deploy to PaaS services, use an agent registered to a regular agent pool.

**Comment by RoopeshNair** [comment]
@asmagin @DanielBMann9000  - we are working on feature aka Deployment Groups 2.0 that will support both PaaS and IaaS resources, stay tuned. Closing the thread here.
