### ISSUE TITLE
"Activity field (Agile, Scrum)" is incorrect

### ISSUE THREAD

**Issue by Arithmomaniac** [MicrosoftDocs/vsts-docs#2222]
It's a copy of "Backlog priority field (Scrum)". The field definition for the Task WIT contains an actual Activity field.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc831b8e-1cd8-82af-4e52-57a35823d19b
* Version Independent ID: 7553ac9f-01ef-471a-55e0-55598acc49ed
* Content: [Add work item types to backlogs and boards - Azure DevOps & TFS](https://docs.microsoft.com/en-us/azure/devops/reference/add-wits-to-backlogs-and-boards?view=tfs-2018#add-a-wit-to-track-it-like-a-task)
* Content Source: [docs/reference/add-wits-to-backlogs-and-boards.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/reference/add-wits-to-backlogs-and-boards.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@Arithmomaniac - Thank you for this feedback. The article is getting updated.
