### ISSUE TITLE
queue is not explained

### ISSUE THREAD

**Issue by StefanSchoof** [MicrosoftDocs/vsts-docs#2223]
View the YAML Configuration of existing Builds get an `queue` Element. 

eg:

```
queue:
  name: Hosted VS2017
```

This documentation does not say if, this is only an alias for pool or has some other meaning.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7458d5b2-1bb7-7d87-7ce6-2b0c430b0155
* Version Independent ID: edf5bbd3-a3f0-5426-e985-31290f8afd05
* Content: [YAML schema - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=vsts&tabs=schema)
* Content Source: [docs/pipelines/yaml-schema.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/yaml-schema.md)
* Product: **devops**
* GitHub Login: @erickson-doug
* Microsoft Alias: **macoope**

**Comment by vtbassmatt** [comment]
That's a bug in what we're generating from the YAML exporter. It's an older, deprecated syntax for `pool`. The snippet you want is:
```yaml
pool:
  vmImage: vs2017-win2016
```
