### ISSUE TITLE
Build on Hosted Pool fails with link this page and this page has no information

### ISSUE THREAD

**Issue by StefanSchoof** [MicrosoftDocs/vsts-docs#2224]
My build fails with a
`Could not find a pool with name My OnPrem. The pool does not exist or has not been authorized for use. For authorization details, refer to https://aka.ms/yamlauthz.`

The link go to this page, but here is no information about this error.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee4ec9d0-e0d5-4fb4-7c3e-b84abfa290c2
* Version Independent ID: 3e2b80d9-30e5-0c48-49f0-4fcdfedf5eee
* Content: [Resources - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/resources?view=vsts#troubleshooting-authorization-for-a-yaml-pipeline)
* Content Source: [docs/pipelines/process/resources.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/resources.md)
* Product: **devops**
* GitHub Login: @vtbassmatt
* Microsoft Alias: **alewis**

**Comment by vtbassmatt** [comment]
Sorry for the trouble. Did it not forward you to [this section](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/resources?view=vsts#troubleshooting-authorization-for-a-yaml-pipeline)? A pool is considered a resource, so you can follow the troubleshooting steps there.
