### ISSUE TITLE
Install custom software

### ISSUE THREAD

**Issue by yowl** [MicrosoftDocs/vsts-docs#2225]
As part of the build I need to run a code generation tool consisting of a exe/dlls/license file.  Is it possible to pull that from somewhere e.g. Azure storage, and extract/run the installer, or maybe it should just be part of the source and a powershell/cmd script run to extract/install it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 99af681d-41ad-da15-0b72-08b5cd5a11ac
* Version Independent ID: 2fa0df36-a437-8cbb-b019-b49b31b1e116
* Content: [Microsoft-hosted agents for Azure Pipelines - Azure Pipelines & TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=vsts&tabs=yaml)
* Content Source: [docs/pipelines/agents/hosted.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/agents/hosted.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by vtbassmatt** [comment]
Yup, you are admin on the Windows image and password-less sudo on the Linux image, so you can install whatever you need.

**Comment by yowl** [comment]
Ok, but I was hoping there would be a task to help.  I guess I just have to script up some powershell to do the pulling?

**Comment by vtbassmatt** [comment]
Ah, gotcha. If your package is on Chocolatey, you can do:
```yaml
- script: choco install -y <package>
```

Otherwise, you can use `Invoke-WebRequest` or your method of choice to download an installer, then run it.

**Comment by yowl** [comment]
Thanks

**Comment by jefgen** [comment]
FYI: It looks like there is no Chocolatey on the 'vs2015-win2012r2' image.

**Comment by vtbassmatt** [comment]
@joebourneMS for the missing `choco` installer on the vs2015 image.
