### ISSUE TITLE
Networking

### ISSUE THREAD

**Issue by pndkrwap86** [MicrosoftDocs/vsts-docs#223]
How to merge my web/links ?

---
#### Detail Dokumen

⚠ *Jangan edit bagian ini. Diperlukan untuk masalah penautan docs.microsoft.com ➟ GitHub.*

* ID: 593c3abc-7b38-6673-62b6-7787d0dda4dd
* Version Independent ID: cbb2b875-b220-596c-7b4d-c2cf6c644335
* [Content](https://docs.microsoft.com/id-id/vsts/build-release/apps/cd/deploy-docker-webapp??toc=/vsts/deploy-azure/toc.json&bc=/vsts/deploy-azure/breadcrumb/toc.json#feedback)
* [Content Source](https://mseng.visualstudio.com/DefaultCollection/TechnicalContent/_git/vsts-docs-pr?path=%2fdocs%2fbuild-release%2fapps%2fcd%2fdeploy-docker-webapp.md&version=GBlive&_a=contents)
* Service: unspecified

**Comment by alexhomer1** [comment]
I am not sure what is being requested here - please provide more information.

**Comment by Skavenger0** [comment]
Step 4: App Service type: Select Web App for Containers.

Web App for Containers is not in the drop down. Any ideas?
