### ISSUE TITLE
Links need updating for Azure Devops

### ISSUE THREAD

**Issue by JustinGrote** [MicrosoftDocs/vsts-docs#2230]
Links like "create a feed if you haven't" are broken and fall back to the front page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a10a409-5468-9532-f0dc-5a28cdd566d8
* Version Independent ID: 2ef20266-bc45-448b-27f5-e5c3bffed2ef
* Content: [Get Started with NuGet Azure Artifacts in Azure DevOps Services and TFS](https://docs.microsoft.com/en-us/azure/devops/artifacts/get-started-nuget?view=vsts&tabs=new-nav#publish-a-package)
* Content Source: [docs/artifacts/get-started-nuget.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/artifacts/get-started-nuget.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by elbatk** [comment]
Ah, fixing this, thank you! @JustinGrote
