### ISSUE TITLE
IP addresses

### ISSUE THREAD

**Issue by Brood** [MicrosoftDocs/vsts-docs#2235]
The two mentioned IP addresses 13.107.6.183 and 13.107.9.183, how static are these and are they hosted in Azure?

Unfortunately I can't find them or any subnet starting with 13.1 in the "Microsoft Azure Datacenter IP Ranges" xml (downloaded 2018-10-26, last updated 2018-10-22) or in the "Azure IP Ranges and Service Tags - Public Cloud" json (downloaded 2018-10-26, last updated 2018-10-22).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43799c5d-2f13-cc76-a1c0-a3f850e16d4e
* Version Independent ID: 97a5b73f-faf7-f9c0-9269-fc79984616d6
* Content: [Deploy a build and release agent on Windows - Azure Pipelines & TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/v2-windows?view=vsts)
* Content Source: [docs/pipelines/agents/v2-windows.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/agents/v2-windows.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by vtbassmatt** [comment]
Yeah, that's not right. Looks like it escaped our notice for a year or so.

**Comment by vtbassmatt** [comment]
[Fixed](https://github.com/MicrosoftDocs/vsts-docs/commit/195b14ce1045d5ea84ecf92cf9c0a56ec8a89c94#diff-7b4a1f35a73c0e9c3ab43a427c8dced0).

**Comment by Brood** [comment]
Actually, you just did the opposite of what I would have though :)

Since `nslookup dev.azure.com` returns `13.107.6.183`, if not this one which IP addresses should I whitelist to allow SSH?

**Comment by vtbassmatt** [comment]
The problem with documenting an IP at all is that it can (and does) change over time. I'd rather document the domain names and let people do their own translation to whatever format they need (IPv4, IPv6, etc.)
