### ISSUE TITLE
One project organisation for multiple projects

### ISSUE THREAD

**Issue by Mendallas** [MicrosoftDocs/vsts-docs#2237]
"Even if you have many teams working on hundreds of different applications and software projects, you can most easily manage them within a single project." -&gt; this is very suprising to me. 

The opposite is said here : https://docs.microsoft.com/en-us/azure/devops/user-guide/define-organizations-and-projects?view=vsts "Most companies work on several products or services at a time. In those cases, we recommend having multiple projects." 

Which one is it ? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8327ce3e-a6f7-74ba-7cc0-95885c247a75
* Version Independent ID: ae36a4ea-20cb-4f29-e760-8f6c362c5a47
* Content: [Scale your organization by adding a project - Azure DevOps & TFS](https://docs.microsoft.com/en-us/azure/devops/organizations/projects/about-projects?view=vsts&tabs=new-nav#feedback)
* Content Source: [docs/organizations/projects/about-projects.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/projects/about-projects.md)
* Product: **devops**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Thanks for pointing this discrepancy out, @Mendallas. I've created a work item to address this. 
Even if you have many teams working on hundreds of different applications and software projects, you can manage them within a single Azure DevOps project. However, if you want to manage more granular security between your software projects and their teams, consider using multiple Azure DevOps projects. At the highest level of isolation is an Azure DevOps organization, where each organization has its own Azure AD tenancy.

**Comment by SamirFarhat** [comment]
Qny news about this discrepancy ?

**Comment by SamirFarhat** [comment]
Any news about this discrepancy ?

**Comment by chcomley** [comment]
Hi @SamirFarhat thanks for following up. I'll be addressing these docs this sprint to remove any specific recommendations, as both statements are right. What?! Here's the thing -  partitioning by product or org is absolutely fair and a good idea.  But, if the same people work on those different products then we’ve potentially made things more difficult (using Teams instead would fix it) and the same is true for roll-up reporting.  The big benefits for multiple projects is different processes and harder security boundaries.  But, those are also the biggest downfalls depending upon your goal. 
Please let me know if you'd like me to connect you with someone who may be able to help you determine what's best for your specific scenario, as I'd be happy to do so.

**Comment by SamirFarhat** [comment]
Hi @chcomley,
I would imagine a page of 1 vs Multiple Projects Pro and Cons, with same examples. I think that we need that as a starting point.

**Comment by chcomley** [comment]
This is an excellent idea, thank you. I've created a work item to be addressed within the next sprint. Thanks again.

**Comment by wi1s0n** [comment]
Hey @chcomley!
Is there a possibility to get in touch with someone who may help me and my team, what's best for us with our current team/repo setup in Azure DevOps?
I came across this text change a few months ago and would like to have some kind of input of best practices. 
Sorry for hijacking this closed issue, but I didn't find any other contact information to you @chcomley . 
Thank you!
Br Wilson

**Comment by chcomley** [comment]
Hi @wi1s0n, I am on the hunt for someone who may be able to help you further. I'll be in touch!

**Comment by chcomley** [comment]
Hi @wi1s0n, I found someone! Please contact Martina Hiemstra at marthiATmicrosoftDOTcom. Thank you!

**Comment by RobertoBorges** [comment]
Hey @chcomley, All this discussion about using Single Project is based on the premisses that this project is using GITVC, because using TFSVC it's quite hard.
And the article don't mention anything about the type os repo that is used in the project.

**Comment by dmckinstry** [comment]
Hi @RobertoBorges - Good call on the TFVC.  @chcomley and I can work on getting that updated.  The general guidance is that if you are using TFVC and heading toward a consolidated project model, you create root folders for different teams/projects/... just as you would create separate repos in Git.  Folders can be secured as needed and workspace mappings can control what segments of the repo you're actively using.  Did this help?

**Comment by thomjames** [comment]
Hi @chcomley/@dmckinstry.  I am struggling with this same concept and I am reaching out for help.  My issue boils down to confusion over terminology and how I configure my single project to work under the 1 project model.

We're a very small development team but we have many small in-house applications (desktop/web/shell scripts) that we support across our organization.  We're using Git, and currently we are just starting out using the 1 project = 1 application in Azure DevOps Server 2019(1).  

The problem with that approach is giving my manager the roll-up they want.  They want to see a Board with all the work that is piling up, what's in progress, and what's recently completed.  That is really the problem I'm trying to solve.

Help would be most appreciated!
