### ISSUE TITLE
Will the symbol server be available in TFS 2017 at some point?

### ISSUE THREAD

**Issue by trousyt** [MicrosoftDocs/vsts-docs#224]
The article doesn't mention whether a built-in symbol server will be implemented for package management in the on-prem TFS 2017 product, but I'm interested if it will be...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 946d67f6-9bb7-481f-f32f-59b5965f9590
* Version Independent ID: 8865f1e2-15b3-8cdb-1d8c-939c665e9bdc
* [Content](https://docs.microsoft.com/en-us/vsts/build-release/tasks/build/index-sources-publish-symbols)
* [Content Source](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/build-release/tasks/build/index-sources-publish-symbols.md)
* Service: unspecified

**Comment by nschonni** [comment]
It's marked as `Future` on the feature roadmap https://docs.microsoft.com/en-ca/vsts/release-notes/#current-features so it 2018.3 is probably the earliest it might land. AFAIK 2017 is only in bug fix mode for stuff like https://blogs.msdn.microsoft.com/bharry/2018/03/02/13895/
