### ISSUE TITLE
How to run Nunit tests

### ISSUE THREAD

**Issue by nikolay-advolodkin** [MicrosoftDocs/vsts-docs#2244]
Hello, I'm trying to follow the documentation to use Visual Designer or YAML to create a CI pipeline and filter NUnit tests. However, that's not on this page for .NET Framework. How can I filter NUnit tests for .NET Framework and not .NET Core. Thanks in advance :)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a494f5a-6143-e567-6c0f-e2c817b1f1a9
* Version Independent ID: 15819679-5914-25f6-34f8-91f1da16b0bf
* Content: [.NET - Azure Pipelines & TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/apps/aspnet/build-aspnet-4?view=vsts)
* Content Source: [docs/pipelines/apps/aspnet/build-aspnet-4.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/apps/aspnet/build-aspnet-4.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by alexhomer1** [comment]
You should find the following topics useful:

"Run unit tests with your builds" : https://docs.microsoft.com/azure/devops/pipelines/test/getting-started-with-continuous-testing?view=vsts

"Visual Studio Test task" : https://docs.microsoft.com/azure/devops/pipelines/tasks/test/vstest?view=vsts
