### ISSUE TITLE
PublishBuildArtifacts should specify whether PathtoPublish is recursive or not 

### ISSUE THREAD

**Issue by cdmihai** [MicrosoftDocs/vsts-docs#2246]
By trial and error I found that it's not. Opened https://github.com/Microsoft/azure-pipelines-tasks/issues/8719

**Comment by steved0x** [comment]
@cdmihai Thank you for the feedback. Can you let me know which article this feedback is for, so I can assign it to the author? You can reply here with the URL of the topic, or you can browse to the topic on docs.microsoft.com and choosing **Content feedback** at the bottom. 

![image](https://user-images.githubusercontent.com/1580889/42953695-fd174150-8b48-11e8-94de-26924ca79c71.png)

**Comment by cdmihai** [comment]
https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/publish-build-artifacts?view=vsts

**Comment by DavidStaheli** [comment]
Hi @cdmihai.  Thanks a lot for letting us know.  Apologies for taking so long to reply.  I've updated the docs (probably to go live later today), and we'll address your good suggestion in the task issue you opened ASAP.  Thanks again!
