### ISSUE TITLE
Thanks for sharing these experiments

### ISSUE THREAD

**Issue by realnooshin** [MicrosoftDocs/vsts-docs#2247]
Just got this news when reading this article: Microsoft finalizes its $7.5 billion GitHub acquisition. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 351f23cd-0f45-4f9e-6907-7e25b31fe4b4
* Version Independent ID: ec7c8359-810d-79e7-03b3-8d5ddab31aee
* Content: [Git at Scale - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/learn/git/git-at-scale)
* Content Source: [https://mseng.visualstudio.com/DefaultCollection/TechnicalContent/_git/devops-learn-pr?path=%2fdocs%2fgit%2fgit-at-scale.md&version=GBlive&_a=contents](https://mseng.visualstudio.com/DefaultCollection/TechnicalContent/_git/devops-learn-pr?path=%2fdocs%2fgit%2fgit-at-scale.md&version=GBlive&_a=contents)
* Product: **devops**
* Git Login: **samgu**
* Microsoft Alias: **sanoursa**

**Comment by steved0x** [comment]
@realnooshin Thank you for the feedback, I will pass it along to Saeed.
