### ISSUE TITLE
Azure DevOps Web Extension - REST client to get work details for a specific Iteration

### ISSUE THREAD

**Issue by titodotnet** [MicrosoftDocs/vsts-docs#2248]
Team,

Please provide the REST client for getting Work details for a specific iteration.

![image](https://user-images.githubusercontent.com/6754353/47603371-dbfa2f00-da08-11e8-8448-1ba6fe1c117e.png)

Now with the existing REST client API, we need to do the following to evaluate total capacity of each member for the specific iteration.
1. Call [getTeamSettings()](https://docs.microsoft.com/en-us/azure/devops/extend/reference/client/api/tfs/work/restclient/workhttpclient2_2?view=vsts#getteamsettings()) to get the number of working days.

2. Call [getIteration](https://docs.microsoft.com/en-us/azure/devops/extend/reference/client/api/tfs/work/restclient/workhttpclient2_2?view=vsts#getteamiteration()) and [getTeamDaysOff](https://docs.microsoft.com/en-us/azure/devops/extend/reference/client/api/tfs/work/restclient/workhttpclient2_2?view=vsts#getteamdaysoff()) to calculate the number of applicable working days for the specific Iteration.

3. Call [getCapacities](https://docs.microsoft.com/en-us/azure/devops/extend/reference/client/api/tfs/work/restclient/workhttpclient2_2?view=vsts#getcapacities()) to get the capacity per day and number of daysOff of each developer.

4. Based on the above three steps, calculate the number of applicable working days for each developer and calculate the capacity for the iteration. 

Rather than if you can provide the REST client API to retrieve the work details as mentioned in the above diagram, it'll be straightforward. 

Thanks,
D.Tito.

**Comment by steved0x** [comment]
@titodotnet Thank you for your feedback. The issues in this repo are for content feedback, and this looks like a product feedback. For product feedback, including feature requests, please file an issue here: https://developercommunity.visualstudio.com/spaces/21/index.html

If this is a documentation feedback, please open a new issue that is associated with a topic by browsing to the topic on docs.microsoft.com and choosing **Content feedback** at the bottom, and I'll assign it to the author of that topic for review.

![image](https://user-images.githubusercontent.com/1580889/42953695-fd174150-8b48-11e8-94de-26924ca79c71.png)

Thank you.
