### ISSUE TITLE
Add release dates for all versions (or subset of most recent versions)

### ISSUE THREAD

**Issue by ahsteele** [MicrosoftDocs/vsts-docs#2249]
From a release planning perspective it would be nice to know how far behind you are based on release date. It's good to know what release your version number relates to, but knowing how far behind you are based on date would be helpful.

As an example these are the dates I was able to quickly ascertain for the last year of releases.

| TFS Release | Update | Version number | Date |
| --- | --- | --- | --- |
| **TFS 2018** | 2018.3 | 16.131.28106.2 | September 12, 2018 |
|  | 2018.2 | 16.131.27701.1 | May 7, 2018 |
|  | 2018.1 | 16.122.27409.2 | February 20, 2018 |
|  | RTW | 16.122.27102.1 | November 15, 2017 |
|  | RC2 | 16.122.26918.3 | September 25, 2017 |
|  | RC1 | 16.121.26818.0 | August 30, 2017 |
| **TFS 2015** | Update 3 | 15.117.27024.0 | November 6, 2017 |
|  | Update 3 RC | 15.117.26912.0 | September 20, 2017 |
|  | Update 2.1 | 14.95.25229.0 | ? |
|  | Update 2 | 14.95.25122.0 | July 24, 2017 |

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 486447a6-a627-df82-4706-2318135540cc
* Version Independent ID: 7d6953c7-9ee6-50d6-9fce-238a4539ecc9
* Content: [Get support and provide feedback - Azure DevOps Services and TFS](https://docs.microsoft.com/en-us/azure/devops/user-guide/provide-feedback?view=vsts#what-platformversion-am-i-using)
* Content Source: [docs/user-guide/provide-feedback.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/user-guide/provide-feedback.md)
* Product: **devops**
* GitHub Login: @erickson-doug
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Thanks for your suggestion, @ahsteele I've created a work item to address this.

**Comment by chcomley** [comment]
@ahsteele, we actually have the information here: https://docs.microsoft.com/en-us/azure/devops/release-notes/#server-build-numbers
Thank you for your input!

**Comment by ahsteele** [comment]
Works for me. Should a link be added to the other page that just points to
here?

**Comment by chcomley** [comment]
Yes, @ahsteele, that's a great idea. I've added this to my backlog. Thanks again!
