### ISSUE TITLE
Needs clearer steps

### ISSUE THREAD

**Issue by swatibhartiya** [MicrosoftDocs/vsts-docs#225]
I would love the documentation to images for each of the steps involved in building a project using Gradle and running the unit tests as well.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 00499395-fdc3-b150-3469-aee2f9fb7cbc
* Version Independent ID: 44e630e1-1689-2d2e-212b-3ce2baf8771f
* [Content](https://docs.microsoft.com/en-us/vsts/build-release/tasks/build/gradle)
* [Content Source](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/build-release/tasks/build/gradle.md)
* Service: unspecified

**Comment by andyjlewis** [comment]
Hi swatibhartiya, thanks for the feedback. https://docs.microsoft.com/en-us/vsts/build-release/apps/java/build-gradle is the topic that covers the step-by-step approach. The sample source includes tests.

Seems we do need to add a link to the step-by-step and remove link to deprecated topic, so I'll hold this issue open until we've done that.

**Comment by andyjlewis** [comment]
added link to tutorial
