### ISSUE TITLE
Dead links

### ISSUE THREAD

**Issue by gperrego** [MicrosoftDocs/vsts-docs#2256]
Both the rest api link above is dead and if I try to leave content feedback on "directly on GitHub" the link is also dead.  Maybe its a renaming to Azure DevOps thing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 413163f0-28c3-a2a7-d626-fcb81bcb2257
* Version Independent ID: 57c127da-2b1e-d29e-9abb-a3c258762ccf
* Content: [.NET Client Libraries for Azure DevOps Services (and TFS)](https://docs.microsoft.com/en-us/azure/devops/integrate/concepts/dotnet-client-libraries?view=vsts#packages)
* Content Source: [docs/integrate/concepts/dotnet-client-libraries.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/integrate/concepts/dotnet-client-libraries.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by elbatk** [comment]
Hi @gperrego , I'm fixing the REST API link now, it should point to here:
https://docs.microsoft.com/en-us/rest/api/vsts/?view=vsts-rest-4.1

The GitHub directory resolves for me, are you logged into your corporate GitHub account?

**Comment by elbatk** [comment]
Closing this as the REST API link is fixed now! Let me know if you have other issues!
