### ISSUE TITLE
Missing Images

### ISSUE THREAD

**Issue by isaiahwilliams** [MicrosoftDocs/vsts-docs#2259]
The Azure DevOps images referenced in this article are not included in the repository. So, none of the images are rendering as excepted. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 11f43544-e181-b021-b362-dd7c5c631d7c
* Version Independent ID: 01897be8-0c56-1e83-0e1e-8dea747911ec
* Content: [Configure package management for Maven with Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/java/labs/mavenpmvsts/?view=vsts)
* Content Source: [docs/java/labs/mavenpmvsts/index.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/java/labs/mavenpmvsts/index.md)
* Product: **devops**
* GitHub Login: @erickson-doug
* Microsoft Alias: **douge**

**Comment by steved0x** [comment]
@isaiahwilliams Thanks for letting us know, I'll take a look and see if I can find and restore those images.

**Comment by thomps23** [comment]
On repro it appears this issue was addressed. Most likely thanks to this feedback- thank you.
