### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by SRIJANLA** [MicrosoftDocs/vsts-docs#226]
This is very easy to understand and useful document  for the beginners. Good Work !!! 

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5f412c4c-d759-6260-e59b-80923d6372df
* Version Independent ID: 94be3497-80cf-25ee-1741-bd9f49ca560e
* [Content](https://docs.microsoft.com/en-gb/vsts/user-guide/devops-alm-overview?toc=/vsts/user-guide/)
* [Content Source](https://mseng.visualstudio.com/DefaultCollection/TechnicalContent/_git/vsts-docs-pr?path=%2fdocs%2fuser-guide%2fdevops-alm-overview.md&version=GBlive&_a=contents)
* Service: unspecified

**Comment by steved0x** [comment]
Thank you very much!
