### ISSUE TITLE
Update for New DevOps UI

### ISSUE THREAD

**Issue by CastleArg** [MicrosoftDocs/vsts-docs#2261]
Would be good to have this for the new DevOps UI.  I no longer have the delete repo option.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b03af1d9-4eeb-ac18-d517-a0a44a2478be
* Version Independent ID: 842691c8-8c41-facf-2cff-03542262f2e5
* Content: [Delete a Git repo from your project - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/delete-existing-repo?view=vsts)
* Content Source: [docs/repos/git/delete-existing-repo.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/repos/git/delete-existing-repo.md)
* Product: **devops**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
@CastleArg I have got this on my backlog to complete, in the meantime were you able to find it? In the new UI, go to Repos, Files, and click the name of the repo to get the drop-down menu, and choose Manage repositories.

![image](https://user-images.githubusercontent.com/1580889/47801694-19aad080-dd05-11e8-84f8-a1fac95c16fc.png)

Then, select the name of the repository, click the ... menu, and choose Delete repository.

![image](https://user-images.githubusercontent.com/1580889/47801732-2b8c7380-dd05-11e8-810a-cacd6aad04b6.png)

I am going to update the whole section of articles for managing repos shortly and get these screenshots updated. Thanks for the feedback and sorry that you ran into trouble.

Steve
