### ISSUE TITLE
Unclear as to which Git this is?

### ISSUE THREAD

**Issue by grahambunce** [MicrosoftDocs/vsts-docs#2263]
Does this reference migrating from a VSO project that is based on TFVS source control to Git based source control? There are so many terms for Git, it's confusing (Git, Github, Gitlab, Bitbucket...etc.). What I'm trying to find out is how to change an existing project, that has a work item history, team settings etc, but just happens to be based on TFVS source control so that it's source control is based on Git running within VSO. 

Is this possible or do we have to create a new project, losing everything that's gone on before, and start again?

It's unfortunate that it looks like that when you create a VSO project it appears that you're locked into that source control system for ever... is that true?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 44afc4fe-66c8-a745-0037-00748a80beb7
* Version Independent ID: 0ea09401-6a08-d745-ff50-7a7b74c41f32
* Content: [Migrate from TFVC to Git - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/learn/git/migrate-from-tfvc-to-git)
* Content Source: [https://mseng.visualstudio.com/DefaultCollection/TechnicalContent/_git/devops-learn-pr?path=%2fdocs%2fgit%2fmigrate-from-tfvc-to-git.md&version=GBlive&_a=contents](https://mseng.visualstudio.com/DefaultCollection/TechnicalContent/_git/devops-learn-pr?path=%2fdocs%2fgit%2fmigrate-from-tfvc-to-git.md&version=GBlive&_a=contents)
* Product: **devops**
* Git Login: **samgu**
* Microsoft Alias: **routlaw**

**Comment by steved0x** [comment]
@grahambunce I am sorry that this one fell through the cracks. Git in Azure Repos Git is standard Git which follows the protocols set forth in the Git standard here: https://git-scm.com/

GitHub, GitLab, Bitbucket, and also Azure Repos provide an implementation of Git that matches that standard.

If you have a TFVC project, and want to migrate it to Azure Repos Git, then this article (the one that you commented on to leave the feedback) contains the steps you need to follow.

In your projects, you can have as many Git repos as you need, but only 1 TFVC repo.

There are some more details available [here](https://docs.microsoft.com/en-us/azure/devops/repos/git/import-from-TFVC?view=azure-devops)
