### ISSUE TITLE
Missing Comments in azure-pipelines.yaml

### ISSUE THREAD

**Issue by bogan** [MicrosoftDocs/vsts-docs#2264]
The YAML sample part of the section titled 'Example' says that "The preceding sample code includes an azure-pipelines.yml file at the root of the repository. This file includes some additional instructions in comments to deploy...".
However, when I look in this file, there are no comments about how to deploy the app.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a40a853-83d6-844a-4752-8b00909c9ffb
* Version Independent ID: e3121964-de38-2a57-2414-c1e29a880477
* Content: [Azure Web App deployment - Azure Pipelines & TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/targets/webapp?view=vsts&tabs=yaml)
* Content Source: [docs/pipelines/targets/webapp.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/targets/webapp.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment]
Thank you for your feedback. I will update the topic to take account of your comments. This topic contains the details of how you can deploy a .NET Core Web App. For more details of how to build .NET Core apps, see https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core.
