### ISSUE TITLE
What is the security for the connection in between the VSTS and the agent on premises?

### ISSUE THREAD

**Issue by Geekays** [MicrosoftDocs/vsts-docs#2266]
Many customers ask this question "What is the security for the connection in between the VSTS and the agent on premises?" and my answer is the https connection. But many still have concerns and ask for if there can be a VPN based connectivity to VSTS. I could not find any definitive answer so far. I believe, there is none for a VPN.

Is there something concrete as a documentation that I may refer to answer such concerns.

Regards,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 47625b86-abd5-ee15-6d61-8bcf81861b96
* Version Independent ID: be9a6174-a69b-7aed-d584-5f602fcc5eb4
* Content: [Build and Release Agents - Azure Pipelines & TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/agents?view=vsts)
* Content Source: [docs/pipelines/agents/agents.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/agents/agents.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by vtbassmatt** [comment]
Customers are free to setup their network however they prefer, including the use of a VPN. The agent needs to be able to reach the Azure DevOps instance on its public URL, which is documented, and anything beyond that is out of our control.
