### ISSUE TITLE
Please give a detailed example about select certain agent from one private agent.

### ISSUE THREAD

**Issue by roger-gao** [MicrosoftDocs/vsts-docs#2270]
So simple about your example with private pool and not mentioned the agent from certain private pool.
example: 
private pool name: Default
This default pool has 3 private agents: A1(enabled), A2(enabled), A3(disabled)
Now i want to use A2 to run build, what is the correct yaml writing ? Could you please give me some guidance? 
Thanks in advance. ^_^

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7458d5b2-1bb7-7d87-7ce6-2b0c430b0155
* Version Independent ID: edf5bbd3-a3f0-5426-e985-31290f8afd05
* Content: [YAML schema - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=vsts&tabs=schema)
* Content Source: [docs/pipelines/yaml-schema.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/yaml-schema.md)
* Product: **devops**
* GitHub Login: @erickson-doug
* Microsoft Alias: **macoope**

**Comment by vtbassmatt** [comment]
Hey @roger-gao -- I'm not sure I understand your question. We don't have a way to target particular agents, that's the whole idea behind pools :) But I'm wondering if maybe you're asking for more information about demands.

**Comment by roger-gao** [comment]
Thanks for your feedback^_^. 
Does this yaml file only can be deployed to build ? could it be deployed to release pipeline?
If possible, more official documents guidance or information provided is helpful to me. So what else website could i invite to learn more about yaml with Azure DevOps? Thanks.

**Comment by vtbassmatt** [comment]
Right now, YAML is for build only. We're working on adding release management features; no ETA for that, though.

The schema doc you found is not the easiest place to get started from. It's meant as a reference. The really intro guide is [here](https://docs.microsoft.com/en-us/azure/devops/pipelines/get-started-yaml?view=vsts), and we also have a set of [templates](https://github.com/Microsoft/azure-pipelines-yaml/tree/master/templates) available that you can check out.
