### ISSUE TITLE
Informative

### ISSUE THREAD

**Issue by CarikeBL** [MicrosoftDocs/vsts-docs#2279]
Thank you for this information. I found it to be really helpful.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 419f53ee-528e-bb71-31b2-e67ddef00ddd
* Version Independent ID: f648e732-f5fe-360d-d185-8278c1af144e
* Content: [Visual Studio Team Services is now Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/user-guide/what-happened-vsts?view=vsts)
* Content Source: [docs/user-guide/what-happened-vsts.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/user-guide/what-happened-vsts.md)
* Product: **devops**
* GitHub Login: @erickson-doug
* Microsoft Alias: **douge**

**Comment by steved0x** [comment]
@CarikeBL Tank you for the feedback, I am passing it along!
