### ISSUE TITLE
Adding default subscriptions

### ISSUE THREAD

**Issue by edwinpjacques** [MicrosoftDocs/vsts-docs#2283]
[Enter feedback here]

It would be good to have the ability to add default subscriptions.  To do that now, I would have to have every user add the subscription individually.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66283a57-5d7c-2882-7055-89c51aab3a9a
* Version Independent ID: 58f97c9f-e9a4-1b57-71b7-aad213bb434e
* Content: [Default and supported notifications - Azure DevOps Services & TFS](https://docs.microsoft.com/en-us/azure/devops/notifications/oob-built-in-notifications?view=vsts)
* Content Source: [docs/notifications/oob-built-in-notifications.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/notifications/oob-built-in-notifications.md)
* Product: **devops**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @edwinpjacques thanks for your comment. Since this isn't a documentation question or update, please enter your feature request here: https://developercommunity.visualstudio.com/content/idea/post.html?space=21 
And let us know if we can help any further. Thanks again.

**Comment by davidcorrigan714** [comment]
Adding default subscriptions through extensions seems to be possible. It'd be nice if there was documentation about subscription contributions.
