### ISSUE TITLE
Variable Group - Tell whether variable is still being referenced outside of the group before deleting it.

### ISSUE THREAD

**Issue by ideoclickVanessa** [MicrosoftDocs/vsts-docs#2286]
Is there a way to tell whether a variable within a variable group is currently being referenced by a pipeline?

I would like to do some cleanup of our variable groups. However, the task seems quite daunting and impractical if I have to manually verify that each of our pipelines are no longer using the variable and/or group and hope that I don't mistakenly delete one that is still being used by a pipeline.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4827aa99-ae62-bd63-6f2f-a87a4065ed27
* Version Independent ID: c9e461ee-7f42-3503-9460-18fa3a807bbb
* Content: [Variable groups for Azure Pipelines and TFS - Azure Pipelines & TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/library/variable-groups?view=vsts)
* Content Source: [docs/pipelines/library/variable-groups.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/library/variable-groups.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment]
Thank you for your feedback. At present there is no way to do this. You might like to post a request on the Developer Community website at https://developercommunity.visualstudio.com/spaces/21/index.html, where they are tracked by the product teams. Thank you.
