### ISSUE TITLE
sentence needs a little fix

### ISSUE THREAD

**Issue by mikeblome** [MicrosoftDocs/vsts-docs#229]
This sentence has a repetitive redundancy: From the product backlog page, set Parents to Show when you want to drill up or down within the hierarchy, set Parents to Show.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a8284fb-ecde-cdaf-be87-cc8c2a7135dd
* Version Independent ID: f44fe86d-319d-b38e-e181-9d17304a1908
* [Content](https://docs.microsoft.com/en-us/vsts/work/backlogs/organize-backlog#map-items-to-group-them-under-a-feature-or-epic)
* [Content Source](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/work/backlogs/organize-backlog.md)
* Service: unspecified

**Comment by KathrynEE** [comment]
@mikeblome , Thank you for the correction. An update should be published later today.
