### ISSUE TITLE
Deleteing Via Powershell

### ISSUE THREAD

**Issue by joseq-terawe** [MicrosoftDocs/vsts-docs#2290]
Can this be done through PowerShell (example: either through straight PowerShell cmdlets or invoking Rest Method?)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a614791-0c5d-4373-3194-11695e40e1d1
* Version Independent ID: 737e5a3b-d7be-9d36-7b5a-638976406d74
* Content: [Delete or remove a project - Azure DevOps & TFS](https://docs.microsoft.com/en-us/azure/devops/organizations/projects/delete-project?view=vsts&tabs=new-nav)
* Content Source: [docs/organizations/projects/delete-project.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/projects/delete-project.md)
* Product: **devops**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @joseq-terawe, there is a REST API for it: https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Frest%2Fapi%2Fvsts%2Fcore%2Fprojects%2Fdelete%3Fview%3Dvsts-rest-4.1&data=02%7C01%7CChrystal.Comley%40microsoft.com%7Cd04ca90513864d832eac08d63f2cc1fe%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636765858810719787&sdata=B6OSmhKJ0PTeCAFbJv6i%2BRtGltMeaC3ZPuBV52Ksbvs%3D&reserved=0 
Hope this helps.
