### ISSUE TITLE
Create the build pipeline

### ISSUE THREAD

**Issue by brennaman** [MicrosoftDocs/vsts-docs#2296]
Can we get an walk through of creating the build pipeline?  Step-by-step.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fd6a020f-35b0-8d92-9f8b-d05e658236e8
* Version Independent ID: e6208061-614b-a084-9c91-ab2ea12c7e2b
* Content: [Build an Azure Virtual Machine using Azure RM templates - Azure Pipelines & TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/apps/cd/azure/build-azure-vm-template?view=vsts)
* Content Source: [docs/pipelines/apps/cd/azure/build-azure-vm-template.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/apps/cd/azure/build-azure-vm-template.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment]
Thank you for your feedback. A walk-through for creating a build and release pipeline is at https://docs.microsoft.com/en-us/azure/devops/pipelines/get-started-designer?view=vsts&tabs=new-nav. Details of the build triggers for continuous integration can be found at https://docs.microsoft.com/en-us/azure/devops/pipelines/build/triggers?view=vsts&tabs=designer together with other topics related to builds. Depending on the language you choose, you can see topics for each one such as https://docs.microsoft.com/en-us/azure/devops/pipelines/languages/dotnet-core?view=vsts.
