### ISSUE TITLE
Powershell task-> Inline (Version 2) don't have Arguments

### ISSUE THREAD

**Issue by Shakevg** [MicrosoftDocs/vsts-docs#2299]
Powershell task-> Inline  don't have Arguments. Is it rights?
How to specify arguments for Inline mode?

**Comment by steved0x** [comment]
@Shakevg Thank you for the feedback. Can you let me know which article this feedback is for, so I can assign it to the author? is it this one?

https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/powershell?view=vsts

**Comment by Shakevg** [comment]
It is defect in Powershell task code. I posted issue on incorrect place. Sorry.
I already found issue on github https://github.com/Microsoft/azure-pipelines-tasks/pull/8705

**Comment by bergmeister** [comment]
@Shakevg Your referenced item is a pull request to make it so, not an issue.
