### ISSUE TITLE
Add link and explanation for all preview features

### ISSUE THREAD

**Issue by jawn** [MicrosoftDocs/vsts-docs#2300]
Some of the preview features are mentioned without a link to more info. If would be helpful and time-saving to have at least some info or screenshot for any preview feature.

These are the preview features without additional info at this time:
- Git commit menu extension points
- New build result page

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b4f95345-6686-8e29-ff3f-cbea4a6eb24d
* Version Independent ID: 695d975e-ea9b-139b-4f98-f9655a751f59
* Content: [Turn preview features on or off - Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/project/navigation/preview-features?view=vsts&tabs=new-nav)
* Content Source: [docs/project/navigation/preview-features.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/project/navigation/preview-features.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by jawn** [comment]
Still an open issue

**Comment by KathrynEE** [comment]
@jawn - Agree with your feedback. We make an effort to document the preview features - however, some new features do get pushed out for which no documentation is available.
