### ISSUE TITLE
docker login to non acr  and non dockerhub registries

### ISSUE THREAD

**Issue by justinhauer** [MicrosoftDocs/vsts-docs#2304]
What are the tasks to login to a non ACR or docker hub registry, like quay.io?

your instructions are only for acr: 
- task: Docker@1
  displayName: Login
  inputs:
    azureSubscriptionEndpoint: 'ContosoAzureSubscription'
    azureContainerRegistry: contoso.azurecr.io
    command: login

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d9dbf88-7e55-d427-145e-d36b04fb197f
* Version Independent ID: a3f30c00-817c-9c05-7a57-3f2bf618821e
* Content: [Docker task - Azure Pipelines & TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/docker?view=vsts)
* Content Source: [docs/pipelines/tasks/build/docker.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/build/docker.md)
* Product: **devops**
* GitHub Login: @erickson-doug
* Microsoft Alias: **dastahel**

**Comment by csinge** [comment]
First define a service connection in the project settings - [https://docs.microsoft.com/en-au/azure/devops/pipelines/library/service-endpoints?view=vsts]
Then in your inputs section add
```
containerRegistryType: Container Registry
dockerRegistryEndpoint: <name of service>
```
Also make sure the changes you are making are being pushed to the default branch (or change your default branch). This way the service endpoint that you have create is authorized.

Good luck
