### ISSUE TITLE
PR Status not updating

### ISSUE THREAD

**Issue by andrew-buckley** [MicrosoftDocs/vsts-docs#2305]
After removing WIP from the title of the PR a new request is never sent to my server. Anyone else experiencing this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e8f48d8a-33fb-9f6d-1db1-4cccb5b987d9
* Version Independent ID: 3e18fcbf-331d-9de2-62ae-c4e7c888cc48
* Content: [Create a pull request status server with Node.js - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/create-pr-status-server?view=vsts)
* Content Source: [docs/repos/git/create-pr-status-server.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/repos/git/create-pr-status-server.md)
* Product: **devops**
* GitHub Login: @mmitrik
* Microsoft Alias: **mmitrik**

**Comment by steved0x** [comment]
@andrew-buckley I am checking on this, a few other folks have reported the same issue recently.

**Comment by steved0x** [comment]
There are two service hooks that need to be configured:

- Pull request created
- Pull request updated

The procedure for the first one is documented, but the 2nd is given in a single line. I will update this article to call out that second one.
