### ISSUE TITLE
Unexpected error in Search service" message page

### ISSUE THREAD

**Issue by sblasko4868** [MicrosoftDocs/vsts-docs#2309]
When following the instructions on the "Unexpected error in Search service" message page (https://blogs.msdn.microsoft.com/tapas_sahoos_blog/2018/10/06/performing-a-clean-uninstall-of-search-extensions-in-team-foundation-server/#comment-19245) and running the "DELETE FROM [Search].[tbl_IndexingUnitChangeEvent] where EntityType = '%EntityType%'" command, SQL throws an error stating EntityType is not a column in the [Search].[tbl_IndexingUnitChangeEvent] table.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be0bdbf7-3132-9007-6c6a-368c5bcb0f3d
* Version Independent ID: 58118f61-f88f-24b9-b785-d8f9d8a1fefd
* Content: [Code, Wiki and Work Item Search set up](https://docs.microsoft.com/en-us/azure/devops/project/search/administration?view=vsts&tabs=new-nav#trouble-tfs)
* Content Source: [docs/project/search/administration.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/project/search/administration.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by thomps23** [comment]
@SrinivasMSFT Is this blog post mis-communicating something that our docs need to clarify?

**Comment by ShubhamJain1992** [comment]
Hi,
In the blog, I could not find any script with the mentioned command. There is no EntityType column in the tbl_IndexingUnitChangeEvent table hence the error.
