### ISSUE TITLE
Something missing?

### ISSUE THREAD

**Issue by joeshepherdmba** [MicrosoftDocs/vsts-docs#231]
It seems like we are missing a step here. In the section titled: Finish the CI process definition. The first step is to Navigate to the Builds tab of the Build and Release hub, and then choose + New. 

To someone new to this process it would be helpful to point me directly to where this is done. I actually had to create a project in VSTS and link it to my github repo before this option showed up. That requires a few steps that are missing from this document. Maybe I missed something?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 483dcb1c-1a89-2b20-4cf2-abd3ae88d9ed
* Version Independent ID: dc4722ed-5a4b-26ec-e7d5-a149bf6e79a7
* [Content](https://docs.microsoft.com/en-us/vsts/build-release/apps/aspnet/build-aspnet-core?tabs=github%2Cyaml%2Cdeploy-windows#feedback)
* [Content Source](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/build-release/apps/aspnet/build-aspnet-core.md)
* Service: unspecified

**Comment by andyjlewis** [comment]
Hi joeshepherdmba, thanks for the feedback. After a quick glance I think I see the issue. Just to confirm, you were following the GitHub YAML path, correct? I'll take a deeper look at it as soon as I can.

**Comment by DavidSSL** [comment]
Hi @andyjlewis, I'm also trying to follow the path for Github and YAML and the instructions are out of date. I never even had the option of using the yaml.

**Comment by andyjlewis** [comment]
@DavidSSL are you using VSTS or TFS? YAML is only on VSTS.

**Comment by DavidSSL** [comment]
@andyjlewis. I'm using VSTS.

**Comment by andyjlewis** [comment]
OK, I think you helped me find another issue with particular topic. In the YAML topic, we do advise, but in this one we didn't. To use this capability, you must have the Build YAML definitions preview feature enabled on your account.

**Comment by DavidSSL** [comment]
@andyjlewis thanks for letting me know.

**Comment by DavidSSL** [comment]
@andyjlewis. How do you exercise the build based off the yaml file on a local development machine?

**Comment by andyjlewis** [comment]
https://docs.microsoft.com/en-us/vsts/build-release/concepts/agents/agents#install
