### ISSUE TITLE
Specify the difference between `Release.Artifacts.{alias}.SourceBranch` and `Release.Artifacts.{alias}.SourceBranchName`

### ISSUE THREAD

**Issue by Kira-Lappo** [MicrosoftDocs/vsts-docs#2312]
Description doesn't say how `SourceBranchName` is generated and `master` branch doesn't show how it really converts the string.

How it works :
- `Release.Artifacts.{alias}.SourceBranch` cotnains **full** branch name, ie `/refs/heads/fix/web-app/microsoft-does-its-best`
- `Release.Artifacts.{alias}.SourceBranchName` cotnains **the last part of the branch**. It means the value of this variable is `microsoft-does-its-best`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 611642f0-881f-10b9-ae94-3c562001d1f0
* Version Independent ID: 41efb94b-4c7a-64a3-b23b-70c8634ae727
* Content: [Release variables in Azure Pipelines - Azure Pipelines & TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/variables?view=vsts&tabs=batch)
* Content Source: [docs/pipelines/release/variables.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/release/variables.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by Kira-Lappo** [comment]
Thank you for your feedback. I have passed this on to the product team for advice.

**Comment by alexhomer1** [comment]
Thank you for your feedback. I will update the topic to include your recommendations.
