### ISSUE TITLE
Update toggle button that is read-only with updated value

### ISSUE THREAD

**Issue by Stoffe** [MicrosoftDocs/vsts-docs#2314]
When setting a toggle-button to read-only, and update the status of that togglebutton with a rule further down the line, the togglebutton does not update its value, thus showing a wrong toggle even though, you do not want the user to be able to change it manually.
(Azure DevOps)

**Comment by steved0x** [comment]
@Stoffe Thank you for the feedback. Can you let me know which article this feedback is for, so I can assign it to the author? You can reply here with the URL of the topic, or you can create a new issue by browsing to the topic on docs.microsoft.com and choosing **Content feedback** at the bottom. 

![image](https://user-images.githubusercontent.com/1580889/42953695-fd174150-8b48-11e8-94de-26924ca79c71.png)

**Comment by steved0x** [comment]
Thank you for your feedback. The issues in this repo are for content feedback, and this looks like a product feedback. For product feedback, including feature requests, please file an issue here: https://developercommunity.visualstudio.com/spaces/21/index.html

Thank you.
