### ISSUE TITLE
The HTTP request to the remote WebDriver server timed out.

### ISSUE THREAD

**Issue by marius-bughiu** [MicrosoftDocs/vsts-docs#2318]
I'm getting the following error message even for the simplest UI test (i.e a simple login test):

Initialization method [Namespace].Init threw exception. OpenQA.Selenium.WebDriverException: The HTTP request to the remote WebDriver server for URL http://localhost:1692/session timed out after 60 seconds. ---&gt; System.Net.WebException: The operation has timed out.

I'm running them with the free hosted agent provided by Azure DevOps using the Chrome driver. I've got UI tests enabled (mixed tests), and I've tried running them both with and without specifying the path to the driver from the environment variables. I've also tried increasing the command timeout to 3 minutes, but the error message still says that the request timed out after 60 seconds. I've also tried the adding the no-sandbox argument without any luck.

The tests run just fine locally, in all browsers (Chrome, Firefox, IE). 
Any ideas?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 09e51d18-72ec-1ad4-9ae7-8185c8e1dcd6
* Version Independent ID: 9f2f0471-d123-8e95-1606-cd811d1ece9a
* Content: [Selenium testing with continuous integration in Azure Pipelines - Azure Pipelines & TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/test/continuous-test-selenium?view=vsts)
* Content Source: [docs/pipelines/test/continuous-test-selenium.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/test/continuous-test-selenium.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by PBoraMSFT** [comment]
@marius-bughiu - How are you running the tests? Is it the Visual Studio Test task? 
If so, can you enable video recording using a runsettings file to see what's going on? 

Also, please report this issue on the tasks repo https://github.com/Microsoft/azure-pipelines-tasks/
as this repo tracks documentation work and issues.

**Comment by govanikunal** [comment]
@marius-bughiu, were you able to get any solution for this ? I am also facing the same issue.

**Comment by ShreyasRmsft** [comment]
@govanikunal please open an issue in https://github.com/Microsoft/azure-pipelines-tasks/ and provide the link here.

Provide the full debug logs zip. Also try to run a selenium test against say www.google.com to check whether it's an issue with the application or a general driver issue.

**Comment by marius-bughiu** [comment]
@govanikunal This weekend I had another go at it and got it working, but I still don't know what the issue was:
- I had upgraded all of the NuGet packages in my test projects and then the error changed from the one mentioned above to another one saying that the driver version that I'm using requires a specific version of Chrome which cannot be found on the agent.
- I've then downgraded the Chrome driver nuget package to match the version of the driver installed on the agent (you can check that in the details for the agent pool, for my MSFT Hosted VS207 they are: chrome-2.40, gecko-0.19.1, ie-3.8.0.0). Then everything started working.
- And now the weird part - just to double check that the package version was indeed the issue, I've upgraded them again to the latest version. And everything still works... I'm guessing it could be some cached DLLs and that I will have to downgrade again (though I'm doing a workspace cleanup before each build).

Hope this helps.
