### ISSUE TITLE
Cross-link objects One Project vs Two or more

### ISSUE THREAD

**Issue by javirivas80** [MicrosoftDocs/vsts-docs#2319]
"A single project minimizes the maintenance of administrative tasks and allows full flexibility to cross-link objects"
Can you give more details on the "full flexibility to cross-link objects." Part ?. What do I lose if I have two separate projects?

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: 8327ce3e-a6f7-74ba-7cc0-95885c247a75
* Version Independent ID: ae36a4ea-20cb-4f29-e760-8f6c362c5a47
* Content: [Scale your organization by adding a project - Azure DevOps & TFS](https://docs.microsoft.com/es-es/azure/devops/organizations/projects/about-projects?view=vsts&tabs=new-nav)
* Content Source: [docs/organizations/projects/about-projects.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/projects/about-projects.md)
* Product: **devops**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Thanks @javirivas80 I've clarified this in the document and the update is now live.

**Comment by jderose9** [comment]
https://github.com/MicrosoftDocs/vsts-docs/commit/bd5cc012d0f1316f3427545f426f990f30a8036c#diff-01f4794c487fbf5b02ffb8c0d72435f7

Hi @chcomley, I'm still not seeing an explanation of what feature(s) are lost when cross-linking objects across projects rather than teams. Is it in a different document?

**Comment by chcomley** [comment]
Hi @jderose9, I'm sorry I haven't made this clear. I've followed up with my PM for a better understanding and will get back to you as soon as possible.

**Comment by chcomley** [comment]
There is not feature loss when you link objects across projects - cross project linking is supported. Users may encounter visibility/permission issues if they only have permission to Project A and it links to things in a restricted Project B (however, restricted permissions on objects may be the desired end goal of linking objects across projects - certain people may only have access to work items while they don't have access to code for example).
Hi @jderose9, please let me know if the following doesn't clear things up. Thanks so much for your patience! I'm going to close this issue, but will reopen if you need anything further.

In the latest on prem version (Azure DevOps 2019) you can even move work items between projects when you disable the warehouse and use the new Analytics service for reporting. The impact of splitting into multiple projects is primarily administrative overhead and a loss of what I would categorize as "convenience features." For example, when your build fails you can trigger a work item to be automatically created and linked to the build. 
Nothing prevents you from putting this work item into another project (link still preserved) or from adding a parameter to create the item in another project, but by default we will assume you want to create the work item in the same project as the build.
Project is just a permission/administrative boundary and does not limit scenarios between artifacts.
