### ISSUE TITLE
Script type value in Yaml snippet is not the correct case

### ISSUE THREAD

**Issue by nlrowe** [MicrosoftDocs/vsts-docs#2320]
`#scriptType: # Optional. Options: , inline Script, file Path`

`inline Script` failed for me, I had to use `Inline Script` as it is referenced in other parts of the document. The Yaml snippet seems to be the only place in the document that references the option list, so it is probably the most popular place for someone to copy/paste the value.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 29c94df7-9de9-ea1a-8b77-d1e6023694dc
* Version Independent ID: a525989e-2e0a-0399-556e-9011ee95da4e
* Content: [Azure App Service Deploy task - Azure Pipelines & TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-rm-web-app-deployment?view=vsts)
* Content Source: [docs/pipelines/tasks/deploy/azure-rm-web-app-deployment.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/deploy/azure-rm-web-app-deployment.md)
* Product: **devops**
* GitHub Login: @erickson-doug
* Microsoft Alias: **dastahel**

**Comment by RoopeshNair** [comment]
This task has few fields that are meant for designer and is not optimized for YAML. If you look at the documentation. We are working on YAML optimised version of App service task(s) that should address this.
