### ISSUE TITLE
Please provide more clarity on the "Planned Effort" calculation in item 4 above.

### ISSUE THREAD

**Issue by pfogerty** [MicrosoftDocs/vsts-docs#2323]
It will be great to understand how "Planned Effort" is calculated when there are both User Stories with Story Points assigned to them AND Tasks with Original Estimates. I expect that since this in information in the Planning Pane, that the "Planned Effort" calculation is a sum of all Story Points for the Stories in the iteration that is being planned. But I will love a clarification if that is the case.

Thanks very much for your consideration!
p@

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4880004e-aae6-a8c7-1aa2-218b6fb00b71
* Version Independent ID: c6e35d98-3b07-2881-536d-0174a71be14d
* Content: [Assign work to a sprint - Azure Boards and TFS](https://docs.microsoft.com/en-us/azure/devops/boards/sprints/assign-work-sprint?view=vsts&tabs=new-nav)
* Content Source: [docs/boards/sprints/assign-work-sprint.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/boards/sprints/assign-work-sprint.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by danhellem** [comment]
You can see how capacity is calculated on used by following these 2 links

https://docs.microsoft.com/en-us/azure/devops/boards/sprints/set-capacity?view=vsts&tabs=new-nav
https://docs.microsoft.com/en-us/azure/devops/boards/sprints/adjust-work?view=vsts&tabs=new-nav
