### ISSUE TITLE
Q: how to make sure that pull requests cannot access the secure file?

### ISSUE THREAD

**Issue by andrewrk** [MicrosoftDocs/vsts-docs#2325]
Someone could create a pull request that modifies the azure-pipelines.yml file to send them the secure file. What mechanism prevents this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 140dcb9a-2ed0-11d5-064b-068f863ed97f
* Version Independent ID: 672d2aa3-cf0d-9207-c97c-e2eba14506b7
* Content: [Secure files for Azure Pipelines and Team Foundation Server - Azure Pipelines & TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/library/secure-files?view=vsts)
* Content Source: [docs/pipelines/library/secure-files.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/library/secure-files.md)
* Product: **devops**
* GitHub Login: @erickson-doug
* Microsoft Alias: **madhurig**

**Comment by DavidStaheli** [comment]
Hi @andrewrk.  Thank you for asking this.  I apologize for taking so long to get back to you.  By default, secrets like secure files are not sent to PR builds of forks.  You can enable this, but it's definitely not recommended for open source / public projects.  You can find more details [here](https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/github?view=vsts#validate-contributions-from-forks).

We're working on a safer way to allow this for PR builds of public forks, where builds will not automatically trigger.  Instead, you as a repo contributor can first review the code changes before allowing the PR build to proceed.  This will be an optional capability.

I'm closing this issue now, but please reopen it if we can provide additional help.  Thanks again!
