### ISSUE TITLE
Provide GitHub login for VSCode Marketplace review/rating system

### ISSUE THREAD

**Issue by NikolasKomonen** [MicrosoftDocs/vsts-docs#2326]
Allow users to login with their GitHub accounts to review and rate marketplace extensions. Just like I logged into my GitHub account to be able to write this feedback.

This feature will make it less of a hassle for users to better engage with the marketplace.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 145e9748-0039-e0df-2bc1-7ad5e74ab75a
* Version Independent ID: cf629735-b15d-3948-86a3-6fffe25ec0ae
* Content: [Marketplace support](https://docs.microsoft.com/en-us/azure/devops/marketplace/marketplace-billing-qa?view=vsts)
* Content Source: [docs/marketplace/marketplace-billing-qa.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/marketplace/marketplace-billing-qa.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by elbatk** [comment]
Hi @NikolasKomonen , I'm going to tag @harishkragarwal here for awareness, but in the future product suggestions should go to the [Azure DevOps developer community](https://developercommunity.visualstudio.com/spaces/21/index.html).

**Comment by NikolasKomonen** [comment]
@elbatk Thanks for pointing me in the right direction.

**Comment by harishkragarwal** [comment]
@NikolasKomonen: thanks for the suggestion. We have this on our backlog and wish to enable it soon.
