### ISSUE TITLE
How to promote packages in views programmatically?

### ISSUE THREAD

**Issue by olivier-spinelli** [MicrosoftDocs/vsts-docs#2333]
On  "Communicate package quality with release views" page: "You can also promote using REST APIs."
I can't find any information. 
My workflow is quite simple, it just needs 4 views:
- Stable
- Latest
- Preview
- CI
One package pushed to the feed must be followed by one (for CI) packages to 4 promotions (Stable packages must also be available in Latest, Preview and CI views).
This doesn't seem "incredible", does it?

I found this [VSTS task](https://github.com/renevanosnabrugge/vsts-promotepackage-task/blob/master/vsts-promotepackage-task/vsts-promotepackage-task.ps1)  but it seems clearly outdated since even the urls are not the ones from "Azure DevOps".

The [REST API](https://docs.microsoft.com/en-us/rest/api/vsts/packaging/views?view=vsts-rest-5.0), in version 5.0 preview as well as in version 4.1 doesn't seem to expose any API point to perform this (quite simple) operation.

Any help will be greatly appreciated.

Olivier

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1a891e9b-bf26-ea09-1da3-ebe3e57b7e26
* Version Independent ID: bf53c51c-c1c1-1931-44ef-81433746e5ec
* Content: [Views on Azure DevOps Services feeds](https://docs.microsoft.com/en-us/azure/devops/artifacts/concepts/views?view=vsts)
* Content Source: [docs/artifacts/concepts/views.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/artifacts/concepts/views.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by bcrosnier** [comment]
The page [Communicate package quality with release views](https://docs.microsoft.com/en-us/azure/devops/artifacts/feeds/views) pages *does* state *You can also promote using REST APIs*, without linking or hinting at a REST API, and I can't find one publicly available either.

There may be a workaround for this, however.

On the Azure DevOps Web UI, promoting a NuGet or NPM package version to a Azure Artifacts view triggers the following REST API call (shortened for reference; standard authentication applies):

```
POST https://pkgs.dev.azure.com/{organization}/_apis/packaging/feeds/{feedId}/{nuget|npm}/packagesBatch
Content-Type: application/json

{
  "data": {
    "viewId": "{viewId}"
  },
  "operation": 0,
  "packages": [{
    "id": "{packageName}",
    "version": "{packageVersion}",
    "protocolType": "{NuGet|Npm}"
  }]
}
```

This call returns a `202 Accepted` response with no body.

Please keep in mind that API is not officially documented (I can't find anything about `/packagesBatch` here), and is therefore subject to breaking changes at any given time.

**Comment by olivier-spinelli** [comment]
@bcrosnier, you're great!

Any hope to have a clear statement about the long term availability of this /packagesBatch?

**Comment by sitwalkstand** [comment]
> The page [Communicate package quality with release views](https://docs.microsoft.com/en-us/azure/devops/artifacts/feeds/views) pages _does_ state _You can also promote using REST APIs_, without linking or hinting at a REST API, and I can't find one publicly available either.
> 
> There may be a workaround for this, however.
> 
> On the Azure DevOps Web UI, promoting a NuGet or NPM package version to a Azure Artifacts view triggers the following REST API call (shortened for reference; standard authentication applies):
> 
> ```
> POST https://pkgs.dev.azure.com/{organization}/_apis/packaging/feeds/{feedId}/{nuget|npm}/packagesBatch
> Content-Type: application/json
> 
> {
>   "data": {
>     "viewId": "{viewId}"
>   },
>   "operation": 0,
>   "packages": [{
>     "id": "{packageName}",
>     "version": "{packageVersion}",
>     "protocolType": "{NuGet|Npm}"
>   }]
> }
> ```
> This call returns a `202 Accepted` response with no body.
> 
> Please keep in mind that API is not officially documented (I can't find anything about `/packagesBatch` here), and is therefore subject to breaking changes at any given time.

Great find @bcrosnier !  Might be time to learn how to write my own extension.

**Comment by jerickmsft** [comment]
Looks like our REST APIs, which we just took some time to more thoroughly document, fell off the web site recently.  We'll get those back up ASAP.

**Comment by sitwalkstand** [comment]
@jerickmsft  Can you post the url here when they are re-posted?

**Comment by jerickmsft** [comment]
It's up now: https://docs.microsoft.com/en-us/rest/api/azure/devops/artifactspackagetypes/nuget/update%20package%20version?view=azure-devops-rest-5.0

**Comment by jerickmsft** [comment]
Batch is here: https://docs.microsoft.com/en-us/rest/api/azure/devops/artifactspackagetypes/nuget/update%20package%20versions

**Comment by elbatk** [comment]
Hi all! I work on the content around Azure Artifacts (and actually, lucky for me, REST APIs as well), I wanted to reach out and find out a docs solution that would have helped you find a solution or made your life a little easier. Please reach out and let me know what would have helped in the docs and I'll look to make the change!

**Comment by elbatk** [comment]
Sounds like we're good here :) let me know if there's anything we can do to help make your lives easier!

**Comment by kagarlickij** [comment]
Here's curl example:
```
curl --header 'Content-Type: application/json' -X PATCH --user your_user:your_pass \
https://pkgs.dev.azure.com/your_org/_apis/packaging/feeds/you_feed_id/upack/packages/apim/versions/you_pack_version?api-version=5.0-preview.1 \
--data '{"views": {"op": "add", "path": "/views/-", "value": "Prerelease"}}'
```

**Comment by kduenke** [comment]
The [Promote package to Release View](https://marketplace.visualstudio.com/items?itemName=rvo.vsts-promotepackage-task&targetId=fa45b7fa-fe18-4746-aee2-517cf3453d19&utm_source=vstsproduct&utm_medium=ExtHubManageList) extension by Rene van Osnabrugge worked great for me in Azure DevOps.

**Comment by catalintomescu** [comment]
> Here's curl example:
> 
> ```
> curl --header 'Content-Type: application/json' -X PATCH --user your_user:your_pass \
> https://pkgs.dev.azure.com/your_org/_apis/packaging/feeds/you_feed_id/upack/packages/apim/versions/you_pack_version?api-version=5.0-preview.1 \
> --data '{"views": {"op": "add", "path": "/views/-", "value": "Prerelease"}}'
> ```

I'm using the same code and getting a 202 response but the view is not set. This used to work fine in TFS on premise but we recently upgraded to Azure DevOps on premise and it stopped working. Any idea why that could be?

**Comment by abij** [comment]
I have tried the Azure-CLI and found 2 options:
- `az devops invoke`, but came to the conclusion that the commands are hard to put together and the preview api versions are not supported (https://github.com/Azure/azure-devops-cli-extension/issues/946)
- `az rest`, which handles authentication for you, before calling the rest api.

The Azure CLI as normally pre-installed on pipeline agents, which is great!
Docs for the the API call: https://learn.microsoft.com/en-us/azure/devops/artifacts/feeds/views?view=azure-devops#promote-packages-using-the-rest-api

Example for promoting a Python package to Prerelease, but can be adjusted for any feed type:

```bash
# note: if feed is project scoped instead of organisation scoped:
# org='SampleOrg/TestProject' 
org='SampleOrg' 
feedId='private_pipy'
packageName='numpy'
packageVersion='1.24.2'

az rest --resource 499b84ac-1321-427f-aa17-267ca6975798 \
  --method PATCH \
  --url "https://pkgs.dev.azure.com/${org}/_apis/packaging/feeds/${feedId}/pypi/packages/${packageName}/versions/${packageVersion}?api-version=7.1-preview.1' \
  --body '{"views": {"op": "add", "path": "/views/-", "value": "Prerelease"}}'
```

Breakdown:
- `499b84ac-1321-427f-aa17-267ca6975798` is Enterprise Application Object Id of AzureDevOps _(fixed)_
- do a PATCH request to the feed/package/version url with a json playload, using the latest api.
