### ISSUE TITLE
I can't choose the title from the Table of contents with [[_TOC_]]

### ISSUE THREAD

**Issue by jesuscampos** [MicrosoftDocs/vsts-docs#2334]
What if my wiki is in other language than English? If I use `[[_TOC_]]` I always get **Content** as title.

I think it would be necessary something like this:
For spanish
    `[[_TOC_(Contenido)]]`
For french
    `[[_TOC_(Le contenu)]]`
...

It's just an example to try to explain the issue. Surely it is not the most appropriate way.

**Comment by adramasu** [comment]
Thanks for highlighting this. We are working on this.

**Comment by KathrynEE** [comment]
@jesuscampos - Thank you for the inquiry. The product team is working on the issue. I'm closing this as answered
