### ISSUE TITLE
YAML snippet for NuGetCommand@2 does not line up with what the task actually requires

### ISSUE THREAD

**Issue by CoolDadTx** [MicrosoftDocs/vsts-docs#2337]
Parameters are from here: https://github.com/Microsoft/azure-pipelines-tasks/blob/master/Tasks/NuGetCommandV2/task.json

Some of the discrepancies I see.
 YAML = feedsToUse, Task = selectOrConfig
 YAML = restoreSolution, Task = solution
 YAML = vstsFeed, Task = feedRestore

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0fa37a3f-6551-16ad-e164-a4ac522cdaab
* Version Independent ID: a3fd6935-2b99-92ef-4eb3-3249fca01f8a
* Content: [NuGet restore, pack, and publish task - Azure Pipelines & TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/package/nuget?view=vsts)
* Content Source: [docs/pipelines/tasks/package/nuget.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/package/nuget.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by elbatk** [comment]
Hi @CoolDadTx ! I took a look at the task reference, and it looks like everything is okay here. So the Task has the names that you've mentioned above, but the YAML is showing the "alias" for those input parameters. So the "alias" values are what we show and prefer people use, and they work exactly as the actual value. You will find that if you use the YAML values you refer to, they work just fine :)
