### ISSUE TITLE
What is the difference between build and pipeline artifacts?

### ISSUE THREAD

**Issue by AArnott** [MicrosoftDocs/vsts-docs#2341]
There are _build_ artifact publishing and downloading tasks. There are also _pipeline_ artifact publishing and downloading tasks. What is the difference between build and pipeline artifacts? When is one appropriate over the other?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 41baa0b5-175c-a697-4b7d-c150259c6e6b
* Version Independent ID: 75085b15-1acc-526a-0495-74a13c42c1d5
* Content: [Publish Pipeline Artifacts task - Azure Pipelines & TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/publish-pipeline-artifact?view=vsts)
* Content Source: [docs/pipelines/tasks/utility/publish-pipeline-artifact.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/utility/publish-pipeline-artifact.md)
* Product: **devops**
* GitHub Login: @mitchdenny
* Microsoft Alias: **midenn**

**Comment by afeblot** [comment]
I just stumbled on that too. I noted the following differences:

- a build artifact is contained in a folder named after the artifact name, and when you download it, all your stuff is in that folder. The pipeline artifact is not, allowing to transfer things from one job to another and having them extracted exactly at the same location.
- a build artifact can be downloaded as a zip from the Azure GUI. A pipeline artifact can't
- a pipeline artifact is not downloaded by a release "download build artifacts" task.

**Comment by alexmullans** [comment]
@mitchdenny and @elbatk are working on docs that cover this in detail.

**Comment by AArnott** [comment]
I wonder if pipeline artifact will work where build artifacts fail during build of a PR from a forked repo.

**Comment by afeblot** [comment]
Wouldn't it make sense that pipeline artifacts are not visible in the build artifact list after the build is completed. Or that they appear in a different tab? AFAIU, their purpose is only the pass stuff across jobs of a build, they're not meant to be retrieved by users.

**Comment by AArnott** [comment]
Where do you find the purpose documented, @afeblot?

**Comment by afeblot** [comment]
@AArnott, I did not find any documented purpose. That should as well be added to the doc to help users decide what they should use. That was just my own understanding, based on task names and behaviors.

**Comment by afeblot** [comment]
Hi, 
Thanks for that.
So, the fact that currently, a pipeline artifact can't be downloaded as a single zip and is not retrieved by a release pipeline "get artifacts" task are part of the temporary gaps which will be filled?

**Comment by AArnott** [comment]
Thanks, @mitchdenny. Do pipeline artifacts suffer from the same permissions issue that build artifacts do? Namely, that github PRs from forks aren't allowed to upload them?

**Comment by JustinGrote** [comment]
@afeblot Single-FIle download still works, so my "workaround" since its backlogged is to zip up my artifacts first before pipeline publishing, if my intent is to have them for an easy download for testing and whatnot. Not great but its there.

**Comment by mitchdenny** [comment]
Sorry for the delay in responding. I didn't see these. Download as Zip is done we just had a bug where we had to turn it off in the UX. Once that is fixed it will be available and will behave the same way as artifacts published via the Published Build Artifacts task. Similarly we are working on fixing the gaps which are stopping Pipeline Artifact download tasks automatically being injected into release pipelines. That work is underway right now (it does work already in some limited scenarios but we had some gaps).

**Comment by mitchdenny** [comment]
@JeremyTCD we don't currently have a way to remove Pipeline Artifacts from a Pipeline run (can't do that with the old artifact type either). It is a good idea though let me think on that one a bit.

**Comment by OXINARF** [comment]
> I just stumbled on that too. I noted the following differences:
> 
> * a build artifact is contained in a folder named after the artifact name, and when you download it, all your stuff is in that folder. The pipeline artifact is not, allowing to transfer things from one job to another and having them extracted exactly at the same location.
> * a build artifact can be downloaded as a zip from the Azure GUI. A pipeline artifact can't

Just documenting that besides these differences, the old build artifacts are downloadable for public projects, but the new pipeline artifacts aren't. This might be related to the zip feature, given that the Artifact Explorer isn't available for anonymous access even for old build artifacts (would be nice to get it though).

**Comment by Erikvdv** [comment]
> Sorry for the delay in responding. I didn't see these. Download as Zip is done we just had a bug where we had to turn it off in the UX. Once that is fixed it will be available and will behave the same way as artifacts published via the Published Build Artifacts task. Similarly we are working on fixing the gaps which are stopping Pipeline Artifact download tasks automatically being injected into release pipelines. That work is underway right now (it does work already in some limited scenarios but we had some gaps).

Any idea on timelines for this fix? We would love to have the feature to be able to download release artifacts.

**Comment by alexmullans** [comment]
Early 2019 - we're currently in a deployment freeze for the holidays but will be back at full speed in January.

**Comment by mitchdenny** [comment]
For now you can insert the ```Download Pipeline Artifact``` task. We are making some enhancements to make auto-injection of download tasks more reliable across all artifact usage scenarios. We've done the work we are just waiting to deploy it (soon!).

**Comment by andrewkress** [comment]
> For now you can insert the `Download Pipeline Artifact` task. We are making some enhancements to make auto-injection of download tasks more reliable across all artifact usage scenarios. We've done the work we are just waiting to deploy it (soon!).

The Download Pipeline Artifact task was stalling for me:

```
2019-01-15T01:54:59.5825130Z ##[section]Starting: Download Pipeline Artifact
2019-01-15T01:54:59.5828137Z ==============================================================================
2019-01-15T01:54:59.5828194Z Task         : Download Pipeline Artifact
2019-01-15T01:54:59.5828226Z Description  : Download Pipeline Artifact
2019-01-15T01:54:59.5828257Z Version      : 0.139.0
2019-01-15T01:54:59.5828325Z Author       : Microsoft Corporation
2019-01-15T01:54:59.5828358Z Help         : Download named artifact from a pipeline to a local path.
2019-01-15T01:54:59.5828389Z ==============================================================================
2019-01-15T01:54:59.9928757Z Download from the specified build: #142
2019-01-15T01:54:59.9928958Z Download artifact to: /home/vsts/work/r1/a
2019-01-15T01:55:04.0620411Z Information, Could not initialize dataport.
2019-01-15T01:55:04.0663733Z Information, Downloaded 0.0 MB out of 121.6 MB (0%).
2019-01-15T01:55:09.0652383Z Information, Downloaded 5.7 MB out of 121.6 MB (5%).
2019-01-15T01:55:14.0654811Z Information, Downloaded 5.7 MB out of 121.6 MB (5%).
2019-01-15T01:55:19.0657708Z Information, Downloaded 5.7 MB out of 121.6 MB (5%).
2019-01-15T01:55:24.0660477Z Information, Downloaded 5.7 MB out of 121.6 MB (5%).
2019-01-15T01:55:29.0663282Z Information, Downloaded 5.7 MB out of 121.6 MB (5%).
2019-01-15T01:55:34.0666061Z Information, Downloaded 5.7 MB out of 121.6 MB (5%).
2019-01-15T01:55:39.0668951Z Information, Downloaded 5.7 MB out of 121.6 MB (5%).
2019-01-15T01:55:44.0672298Z Information, Downloaded 5.7 MB out of 121.6 MB (5%).
```

With that last line continuing until my timeout hit.  Hoping the updates are set to release soon!

**Comment by mitchdenny** [comment]
@andrewkress sorry to hear you are having this problem. Could you provide some details about the org/team project/pipeline/build ID so we can take a closer look. If you prefer you can e-mail them to me at midenn@microsoft.com.

**Comment by davenewza** [comment]
Note this bugs still seems to exist - https://stackoverflow.com/questions/53591249/vs402864-no-artifact-type-found-corresponding-to-id-pipelineartifact

**Comment by mitchdenny** [comment]
Yes - I am looking at that bug right now. We are waiting for one of our services to deploy and we should be able to validate the fix. Shouldn't be long now.

**Comment by elbatk** [comment]
This docs issue has gone around the world and back it seems! I'm glad so many people have interest in our new(er) Pipeline Artifacts. I'm going to go ahead and close the conversation as a docs issue here. If you find that a change should be made to the docs here, please feel free to create a PR (we are always happy to review PRs!), or create another issue from the topic you think should change! Thanks everyone!

**Comment by messnerdev** [comment]
> Similarly we are working on fixing the gaps which are stopping Pipeline Artifact download tasks automatically being injected into release pipelines

Hi @mitchdenny, this is affecting my team. Could you point me to the specific work item this refers to so I can track progress.

**Comment by Lawls91** [comment]
> @JeremyTCD we don't currently have a way to remove Pipeline Artifacts from a Pipeline run (can't do that with the old artifact type either). It is a good idea though let me think on that one a bit.

Is there any updates on the unpublish functionality? Has this been raised as a feature request somewhere?
