### ISSUE TITLE
Git in VS and ... is standard Git

### ISSUE THREAD

**Issue by Styxxy** [MicrosoftDocs/vsts-docs#2342]
In the note below Git, it says

> Git in Visual Studio, Azure DevOps Services, and TFS is standard Git.

This feels a little bit strange. I think the first word should be something like "source control"? Or maybe I misinterpret the sentence (in that case, the wording confuses me).

Update: maybe you mean the _flavour_ of git is standard git?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a1dc9a4a-7828-f40f-4cf0-e0b1f5476ff2
* Version Independent ID: 278aed60-558e-3beb-2ed4-c2517c2cd05d
* Content: [Git and TFVC version control - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/tfvc/comparison-git-tfvc?view=vsts)
* Content Source: [docs/repos/tfvc/comparison-git-tfvc.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/repos/tfvc/comparison-git-tfvc.md)
* Product: **devops**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
@Styxxy Thank you for your feedback. I can try to clarify that sentence, what it is trying to say is that the Git used in those products and services is just regular standardized Git. What do you think?

**Comment by Styxxy** [comment]
@steved0x Thanks :-). Like I thought (in my update), it is about the "flavour" of git. I don't know exactly how to rephrase the note though.

**Comment by thomps23** [comment]
Looks like this notation was updated to add clarity
