### ISSUE TITLE
Provide clearer explanation where to set Artifact source alias and examples how to use it

### ISSUE THREAD

**Issue by grawcho** [MicrosoftDocs/vsts-docs#2343]
{source alias} needs to be replaced by the value that the user sets or default from the release definition artifact stage (source Alias field which fills automatically by default) i've been working with VSTS (azure devops) for ages and it took me half a day to realize this allegedly obvious thing.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 611642f0-881f-10b9-ae94-3c562001d1f0
* Version Independent ID: 41efb94b-4c7a-64a3-b23b-70c8634ae727
* Content: [Release variables in Azure Pipelines - Azure Pipelines & TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/variables?view=vsts&tabs=batch#artifact-variables)
* Content Source: [docs/pipelines/release/variables.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/release/variables.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment]
Thank you for your feedback. I will update the topic to make more clear on this point.
