### ISSUE TITLE
Can't find guidance to build .NET Framework apps using YAML

### ISSUE THREAD

**Issue by eriawan** [MicrosoftDocs/vsts-docs#2344]
There is YAML sample on .NET Core and also Docker. 
Is there sample to have .NET Framework build in Azure DevOps pipelines using YAML? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a494f5a-6143-e567-6c0f-e2c817b1f1a9
* Version Independent ID: 15819679-5914-25f6-34f8-91f1da16b0bf
* Content: [.NET - Azure Pipelines & TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/apps/aspnet/build-aspnet-4?view=vsts)
* Content Source: [docs/pipelines/apps/aspnet/build-aspnet-4.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/apps/aspnet/build-aspnet-4.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by vstribrny** [comment]
I cannot find it too - it wound be nice to provide the guidance for CI for .NET Framework ASP.NET apps.

**Comment by andyjlewis** [comment]
Thank you for the suggestion! 

I should share some context. Although you can't tell right now, this topic title is going to revert back to be more specifically about ASP.NET (notice this is what it's been all along from the file name). We've had aspirations to do more general .NET Framework guidance, but so far not sufficient resources to make it happen. 

Based on this suggestion I've added an item to the backlog to create a .NET Framework topic. I'll continue to track and seek resources to write it. But at the moment I don't expect it to happen soon. Most of our .NET Framework customers use designer pipelines.

**Comment by eriawan** [comment]
@andyjlewis 

Could I offer my help to update the content's page to add using YAML for .NET Framework's ASP.NET WebForms project/solution?

I have one sample YAML to build ASP.NET WebForms project already working well: 
https://github.com/eriawan/docker-dotnet/blob/add_netfx_4.7.2_aspnetsample/azure-devops-multijobs.yml

And this is the Azure DevOps Pipelines CI build result sample, using that YAML:
https://rxcommunica.visualstudio.com/rxpubliccrepo/_build/results?buildId=69&view=results

**Comment by andyjlewis** [comment]
@eriawan thanks for the offer! Give me a bit of time to consider how we would want to add YAML into this scenario and sync with others involved in this topic.

**Comment by jpvelasco** [comment]
@andyjlewis I wrote a blog post about crafting YAML based build configurations for ASP.NET (.NET 4.7.2) applications. Hope this helps: https://jpvelasco.com/build-aspnet-framework-apps-with-azure-pipelines/
