### ISSUE TITLE
Reference variable group from YAML

### ISSUE THREAD

**Issue by HermanCordes** [MicrosoftDocs/vsts-docs#2345]
The yaml schema snippet seems to indicate that referencing variable groups from a YAML file is possible using:

variables:
- group: my-variable-group

However, it's not supported yet. See also: https://stackoverflow.com/a/52378188/249948

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4827aa99-ae62-bd63-6f2f-a87a4065ed27
* Version Independent ID: c9e461ee-7f42-3503-9460-18fa3a807bbb
* Content: [Variable groups for Azure Pipelines and TFS - Azure Pipelines & TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/library/variable-groups?view=vsts&tabs=yaml)
* Content Source: [docs/pipelines/library/variable-groups.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/library/variable-groups.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment]
Thank you for your feedback. I have passed this on to the product team for advice and I will update the topic to include their recommendation.

**Comment by alexhomer1** [comment]
I'm informed by the product team that this feature is now implemented and is working in Azure DevOps Services.

**Comment by tombrereton** [comment]
There is an easy work around for this.

Edit the YAML on Azure Devops and then click 'Edit in Visual Designer'.

You can then go:
Variables > Varaible Groups> Link Variable Group
