### ISSUE TITLE
Activity log export

### ISSUE THREAD

**Issue by markarnolditpro** [MicrosoftDocs/vsts-docs#2347]
I'm looking for audit logs related to who has cloned repos and when.  Is this available?  If not, is it conceivable that MS support could provide these logs when required?  Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 361c08ef-48be-de59-d223-595cadc65a7b
* Version Independent ID: 4bab93d0-8ee5-5e18-a217-c5f6a3eea441
* Content: [Export access level audit log - Azure DevOps & TFS](https://docs.microsoft.com/en-us/azure/devops/organizations/security/export-users-audit-log?view=vsts&tabs=new-nav)
* Content Source: [docs/organizations/security/export-users-audit-log.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/security/export-users-audit-log.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@markarnolditpro - Thank you for the inquiry. An audit log of who has cloned repos is not a supported feature. I recommend that you add it to our [Suggest a Feature](https://developercommunity.visualstudio.com/content/idea/post.html?space=21).  Our product team is always interested in determining what our customers want audited.
