### ISSUE TITLE
Pull request triggers in TFS 2018.3?

### ISSUE THREAD

**Issue by MoiMoiDG** [MicrosoftDocs/vsts-docs#2348]
Hi,

I do not see the "Pull request triggers" option in TFS 2018.3 + Git Repos. Do I need to activate anything? How can I trigger a release pipeline for artifacts originating from a Pull Request targeting e.g. the branches "master" and "develop" only?

Remark: The current documentation does not distinguish whether some features are available only for some editions.

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d9e313c5-9120-9172-bc27-c21d10fcd5ae
* Version Independent ID: 1a837182-591f-3cbc-1632-7b50d857b13c
* Content: [Release triggers for stages, branches, and pipelines - Azure Pipelines & TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/triggers?view=vsts)
* Content Source: [docs/pipelines/release/triggers.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/release/triggers.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment]
Thank you for your feedback. I have passed this on to the product team for advice and I will update the topic to include their recommendation.

**Comment by alexhomer1** [comment]
The product team tell me that the "Pull Request Triggers" feature that is available now in Azure Devops Services will be included in the next release of TFS. It is not supported in TFS 2018.
