### ISSUE TITLE
How many failures is too many failures for a restriction to become disabled?

### ISSUE THREAD

**Issue by MarkIannucci** [MicrosoftDocs/vsts-docs#235]
My subscription is failing a bit too frequently and occasionally becoming disabled.  It would be nice if I knew how many failures caused my service hook to get disabled so I would know when to re-enable it as we're working through the fix to the root cause.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 96287641-3e4f-b038-148f-08e8471bd573
* Version Independent ID: b0034cd1-4f29-2e2d-c2bb-49004552dae8
* [Content](https://docs.microsoft.com/en-us/vsts/service-hooks/troubleshoot)
* [Content Source](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/service-hooks/troubleshoot.md)
* Service: unspecified

**Comment by davidtetreault** [comment]
Same question here.

And what's the difference between "Disabled" and "Enabled (restricted)", since it no longer processes the messages and never reenables.

**Comment by pswetz** [comment]
Same question - My hooks go into Enabled (restricted) after 1 500 fail and never try again, seems like you may as well go right to Disabled. What does 'restricted' actually mean here?

**Comment by elbatk** [comment]
Hi all, does this help clear things up?

**Failure types**
Failures from a Service Hooks notification can be grouped into three categories:

Terminal Failures
Transient Failures
Enduring Failures.

**Terminal Failures**
The only Terminal Failure is HTTP Status Code 410 (Gone). When a subscription encounters a Terminal Failure, it is automatically disabled regardless of its prior status.

**Transient Failures**
When a subscription encounters a Transient Failure, it will attempt to resend the notification up to 8 times, with an increasing delay between each attempt.

Transient Failures include

408 (Request Timeout)
502 (Bad Gateway)
503 (Service Unavailable)
504 (Gateway Timeout)

Sequence of retries for transient failures
Before retry 1: wait ~1 second
Before retry 2: wait ~2 seconds (total delay of 3 seconds)
Before retry 3: wait ~4 seconds (total delay of 7 seconds)
Before retry 4: wait ~8 seconds (total delay of 15 seconds)
Before retry 5: wait ~16 seconds (total delay of 31 seconds)
Before retry 6: wait ~32 seconds (total delay of 63 seconds)
Before retry 7: wait ~60 seconds (max backoff time, total delay of 123 seconds)
Before retry 8: wait ~60 seconds (max backoff time, total delay of 183 seconds)

If the notification exhausts all of its retries, and continues to encounter a Transient Failure for each attempt, the subscription will stop trying to send the notification, and will treat the notification as if it encountered an Enduring Failure.

**Enduring Failures**
Enduring Failures include all other HTTP failure codes (for example: 404 (Not Found), 500 (Internal Server Error), etc.).

When a subscription encounters an Enduring Failure, it is placed on probation.*

**Probation**
While on probation, a subscription will be limited in the number of notifications it is allowed to send. If the subscription continues to hit Enduring Failures, then it will be increasingly limited, and eventually disabled. If the subscription receives a successful response while on probation, it will be restored to a fully enabled state.

Sequence of 7 maximum retries while subscription is on probation
Before retry 1: wait ~20 minutes
Before retry 2: wait ~40 minutes (total probation time of 1 hour)
Before retry 3: wait ~1 hour 20 minutes (total probation time of 2.33 hours)
Before retry 4: wait ~2 hours 40 minutes (total probation time of 5 hours)
Before retry 5: wait ~5 hours 20 minutes (total probation time of 10.33 hours)
Before retry 6: wait ~10 hours 40 minutes (total probation time of 21 hours)
Before retry 7: wait ~15 hours (max backoff time, total probation time of 36 hours)
After 7 retries, the subscription status will be set to DisabledBySystem if notifying the consumer fails

**Comment by midgleyc** [comment]
Hi @elbatk, this is very useful information to know. Would you mind adding it to the documentation to make it more discoverable (specifically, the total number of retries / wait times for transient failures)?

From my testing, it seems that after 30 seconds of no response, the client times out with the error message "A task was canceled", and this counts as an enduring failure. Is this correct? I can avoid the enduring failure by responding with a 504 after 25 seconds, and given the transient retries that gives me a few minutes more to get a response, which is long enough.

**Comment by elbatk** [comment]
Hi @midgleyc , I'm adding this info to the doc as we speak. I'm not too sure about the 30 seconds without a response scenario, reaching out to someone on our team now about that now. Keep in mind the holidays are here, but hopefully we can get a response soon :)

**Comment by elbatk** [comment]
Hi @midgleyc , I couldn't get an answer on the 30 second delay you mentioned. It sounds like it may be an error on our end with how we handle certain scenarios, but our team is looking into it! I'm going to close this for now as I have the documentation change coming, but if you have any product issues still, a good place for them is the [Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html).
