### ISSUE TITLE
"categories": ["Repos"] should be fixed to supported values.

### ISSUE THREAD

**Issue by gh-sachip** [MicrosoftDocs/vsts-docs#2351]
When I compile the extension , it errors with message
error: Error: There were errors with your extension. Address the following and re-run the tool.
error: The following categories are not valid: Repos. Valid categories are: Build and release, Collaborate, Code, Test, Plan and track, Insights, Integrate, Developer samples.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 14955ee9-29f2-46fe-3a8d-a42666f53ffc
* Version Independent ID: 5d417cd0-a671-ee30-8fca-5f8b0addd328
* Content: [Develop a web extension for Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/extend/get-started/node?view=vsts)
* Content Source: [docs/extend/get-started/node.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/extend/get-started/node.md)
* Product: **devops**
* GitHub Login: @willsmythe
* Microsoft Alias: **wismythe**

**Comment by elbatk** [comment]
Ah, this must have been a find+replace error when switching to the new area names, fixing this now and it should go live within a day or so! Thank you! "Code" is the correct one for here, I believe.
