### ISSUE TITLE
Ambiguous sentence 

### ISSUE THREAD

**Issue by ahmadyo** [MicrosoftDocs/vsts-docs#2352]
what do you mean by "automaticaly places" in "step 6: Specifying the extensions in the xml automaticaly places ..."? The content is about editing the xml; how it place "automaticaly"!!?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e7687d0f-cb54-022d-2a2a-7670251e73a4
* Version Independent ID: b1abeb4f-1f46-d759-6b01-0bb560c53778
* Content: [Configure work item form extensions in TFS](https://docs.microsoft.com/en-us/azure/devops/extend/develop/configure-workitemform-extensions?view=tfs-2018)
* Content Source: [docs/extend/develop/configure-workitemform-extensions.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/extend/develop/configure-workitemform-extensions.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by elbatk** [comment]
Hi @ahmadyo , I don't find this sentence ambiguous. It means that after you add your extension in the XML, both contributions of type **page** or **group** are automatically placed in the form. If you continue reading it adds some clarification by saying that contributions of type **control** are not automatically placed and they must be added with a contribution tag within the form.

**Comment by elbatk** [comment]
Closing this issue as it's been a couple of weeks, let me know if you have any other questions!
