### ISSUE TITLE
The link "Build Docker image and publish Helm chart" is a little bit misleading

### ISSUE THREAD

**Issue by eriawan** [MicrosoftDocs/vsts-docs#2353]
The link "Build Docker image and publish Helm chart" is a little bit misleading. 
The current link points to https://docs.microsoft.com/en-us/azure/devops/pipelines/languages/docker?view=vsts, but the content on that link has no mention about Helm related topics at all.

Also I could not find any topics about leveraging Helm in the current docs of Azure Pipelines.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4fa99181-afb1-98c4-5978-6dab603b55f9
* Version Independent ID: 8f4ec1e8-f3b2-f427-0b3f-4e658a573095
* Content: [Deploy a Docker container app to an Azure Kubernetes Service (AKS) - Azure Pipelines & TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/apps/cd/deploy-aks?view=vsts)
* Content Source: [docs/pipelines/apps/cd/deploy-aks.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/apps/cd/deploy-aks.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment]
Thank you for your feedback. I have passed this on to the product team for advice and will update the topics based on their recommendations.

**Comment by eriawan** [comment]
@alexhomer1 

Any updates on this issue? Please confirm. 
It's been a month, without any updates...

cc @azooinmyluggage @vijayma

**Comment by eriawan** [comment]
@alexhomer1 @vijayma @azooinmyluggage 

Guys, looks like it's been fixed!

![image](https://user-images.githubusercontent.com/8773147/52612611-19ea6880-2ebd-11e9-92f5-6ad27e79ae48.png)

The link works, and it has the right context of using Helm chart. I close this.

Many thanks! 👍 🙂

**Comment by manuchandel** [comment]
Cannot see this link of creating a helm chart. Can you post actual link, instead of image? That will be helpful. Also according to current documentation, process of helms chart is not going through. Cannot create a successful release because of helm charts.

**Comment by cramsey86** [comment]
Agreed. I do not see the link to creating the Helm chart either.

**Comment by tommasodotNET** [comment]
This was the helm link which was linked in that version of the page. Had to use web.archive.org to retrieve that:
https://docs.microsoft.com/en-gb/azure/devops/pipelines/build/helm-provenance?view=azure-devops

**Comment by tommasodotNET** [comment]
Should you need to access the version of the page from which was taken that screenshot, here it is:
https://web.archive.org/web/20190522075032/https://docs.microsoft.com/en-us/azure/devops/pipelines/apps/cd/deploy-aks?view=azure-devops#define-your-ci-build-process
