### ISSUE TITLE
finer title

### ISSUE THREAD

**Issue by ahmadyo** [MicrosoftDocs/vsts-docs#2354]
It is better to change "JavaScript sample" title to "TypeScript..." or change the sample code to JavaScript

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6e6cb0ed-c129-901c-10a2-909354aa562f
* Version Independent ID: ceb10d41-b306-0d3f-ccb2-124a3ba69332
* Content: [Add a custom control to the work item form](https://docs.microsoft.com/en-us/azure/devops/extend/develop/custom-control?view=vsts)
* Content Source: [docs/extend/develop/custom-control.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/extend/develop/custom-control.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by elbatk** [comment]
You are right, fixing this now and it should be live within a day or so. Thank you!
