### ISSUE TITLE
Select a branching strategy link is broken

### ISSUE THREAD

**Issue by mloskot** [MicrosoftDocs/vsts-docs#2355]
This article references  "select a branching strategy" pointing at https://visualstudio.com/articles/git-branching-guidance
Apparently, the target link is broken.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d05453e8-ded7-b09d-26c0-78906b16a67c
* Version Independent ID: 195d2303-45f4-e074-b234-67235219dc5a
* Content: [Plan your migration to Git - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/learn/git/centralized-to-git)
* Content Source: [https://mseng.visualstudio.com/DefaultCollection/TechnicalContent/_git/devops-learn-pr?path=%2fdocs%2fgit%2fcentralized-to-git.md&version=GBlive&_a=contents](https://mseng.visualstudio.com/DefaultCollection/TechnicalContent/_git/devops-learn-pr?path=%2fdocs%2fgit%2fcentralized-to-git.md&version=GBlive&_a=contents)
* Product: **devops**
* Git Login: **samgu**
* Microsoft Alias: **samgu**

**Comment by steved0x** [comment]
@mloskot Thanks for letting us know, I just fixed this and it should be live later today. Here is the updated link: https://docs.microsoft.com/en-us/azure/devops/repos/git/git-branching-guidance?view=vsts

**Comment by mloskot** [comment]
@steved0x Thanks for the prompt fix
