### ISSUE TITLE
Can I change the directory after signup?

### ISSUE THREAD

**Issue by JozoSlejko** [MicrosoftDocs/vsts-docs#2356]
Can I change the directory after signup?
A: Yes, see Change your organization's Azure Active Directory instance.

The link here points to changing organization location, not changing the AAD instance as it should.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: db3dc01a-591e-4c6e-5727-83f5cfba2bbd
* Version Independent ID: c273e7c8-ec87-2fcd-2d66-f1c0c0872eb6
* Content: [Troubleshoot creating an Azure DevOps organization](https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/faq-create-organization?view=vsts#ChangeDirectory)
* Content Source: [docs/organizations/accounts/faq-create-organization.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/accounts/faq-create-organization.md)
* Product: **devops**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Thanks @JozoSlejko for the heads up. I've created a work item to address this. The updated link should be live by sometime this afternoon. Thanks again.
