### ISSUE TITLE
Test Platform Installer task does not appear in TFS 2018 update 1

### ISSUE THREAD

**Issue by guylevy** [MicrosoftDocs/vsts-docs#2358]
We have an on-premise TFS 2018 update 1 (Version 16.122.27409.2). I cannot find the "Visual Studio Test Platform Installer" task in the tasks menu and the "Visual Studio Test" task does not show the "Installed by Tools Installer" option.  What do we need to do so that these new tasks / options appear?

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6cdab61-a70b-e725-cd74-f258620447b7
* Version Independent ID: ee1753a6-2b6c-8304-5cba-73b86606ebb3
* Content: [Visual Studio Test Platform Installer task - Azure Pipelines & TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/vstest-platform-tool-installer?view=vsts)
* Content Source: [docs/pipelines/tasks/tool/vstest-platform-tool-installer.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/tool/vstest-platform-tool-installer.md)
* Product: **devops**
* GitHub Login: @erickson-doug
* Microsoft Alias: **dastahel**

**Comment by PBoraMSFT** [comment]
@guylevy - this is a documentation bug. The VSTest platform installer task is available only in TFS 2018 Update 2 or later.

@alexhomer1 - can we please update the task doc to say that this is TFS 2018 Update 2?

**Comment by alexhomer1** [comment]
Update to topic has now been submitted for publication.
