### ISSUE TITLE
Office 365 integration and individualized targets

### ISSUE THREAD

**Issue by alburdette619** [MicrosoftDocs/vsts-docs#236]
It'd be awesome given that Office365 has access to my active directory and everything that I could set this up to send a message directly to reviewers of a PR per say instead of just to a channel.  Channel based messaging becomes chaff.  I will say I haven't tested this yet.  If it tags users that is better than nothing but individualized messaging would be far more effective.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1cddc0ae-93af-297c-2e71-334143ebee1e
* Version Independent ID: cb76e516-8471-c3e1-45f4-0a20a223f32a
* [Content](https://docs.microsoft.com/en-us/vsts/service-hooks/services/teams)
* [Content Source](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/service-hooks/services/teams.md)
* Service: unspecified

**Comment by IronYop** [comment]
Deprecated, this connector doesn't exist
