### ISSUE TITLE
"Working folder with package.json" is misleading 

### ISSUE THREAD

**Issue by dcaro** [MicrosoftDocs/vsts-docs#2360]
We worked with several customers that found "Working folder with package.json" misleading and suggesting to use "Working folder that contains package.json". 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c00d3b8-64c1-9f1b-83f8-62d8cf07817b
* Version Independent ID: 5fcdebed-cfb8-c5a6-d807-1315b2db5e57
* Content: [npm task - Azure Pipelines & TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/package/npm?view=vsts)
* Content Source: [docs/pipelines/tasks/package/npm.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/package/npm.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by vtbassmatt** [comment]
Looks like this was fixed but the bug never closed.
