### ISSUE TITLE
Path Filter: how do you say every .md file in the /src folder

### ISSUE THREAD

**Issue by TravisEz13** [MicrosoftDocs/vsts-docs#2363]
`/src/*.md` only works for files directly in the `/src` folder.  How do you say every `.md` file in any subfolder under `/src`?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5673ec1-c7d1-e0ac-043a-8fc3d5b226a9
* Version Independent ID: b4872831-51c0-6cf8-1c56-de20beb38a80
* Content: [Build pipeline triggers - Azure Pipelines & TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/triggers?tabs=yaml&view=vsts#continuous-integration-ci)
* Content Source: [docs/pipelines/build/triggers.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/build/triggers.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by GoshaNick** [comment]
Does `/src/**/*.md` work?

**Comment by TravisEz13** [comment]
I got an answer that currently the wildcard must be at the end (they answered me directly.)

**Comment by MattMencel** [comment]
So is the example by @GoshaNick the correct syntax or is there a different way to do it?

**Comment by TravisEz13** [comment]
Actually, I think there needs to be a functional bug to add this functionality first.  

they support 

```
exclude:
   - 'markdown/*'
```

but no wildcards except at the very end currently.

**Comment by TravisEz13** [comment]
please fix this.  Actually I would love the feature to work as documented.

**Comment by vtbassmatt** [comment]
@DavidStaheli can you take a look at this (both docs and how it works) and make sure we have the right feature here?

**Comment by DavidStaheli** [comment]
Yes, we should add support for better matching, possibly wildcards anywhere, glob patterns, regex, etc.
(Also tracked internally by Microsoft as feature # [1486320](https://dev.azure.com/mseng/AzureDevOps/_workitems/edit/1486320).)

**Comment by mijacobs** [comment]
It looks like this is an issue with the product itself, rather than an issue with the documentation. To make sure it gets in front of the right people, please [submit your bug]( https://developercommunity.visualstudio.com/content/problem/post.html?space=21) if you haven't already.

**Comment by TravisEz13** [comment]
Docs should still be updated to reflect what is allowed

**Comment by TravisEz13** [comment]
looks like the docs have been updated.

**Comment by mijacobs** [comment]
Thanks for checking and letting us know, @TravisEz13 !
