### ISSUE TITLE
Options setting unclear

### ISSUE THREAD

**Issue by artidoro** [MicrosoftDocs/vsts-docs#2364]
Some of these options don't have a clear explanation of how they can be set. For example timeout.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0fa5a83c-70fd-6925-a8c8-256b21c21a2e
* Version Independent ID: 75f4a136-7245-7878-2953-6b68272fe4ec
* Content: [Build pipeline options - Azure Pipelines & TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/options?view=vsts&tabs=yaml#job-cancel-timeout)
* Content Source: [docs/pipelines/build/options.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/build/options.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by andyjlewis** [comment]
Thanks for the feedback I've got a work in progress to refactor the guidance in this topic.
