### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by cowinr** [MicrosoftDocs/vsts-docs#2367]
The user type links in the first paragraph are broken. E.g. Basic Features link https://visualstudio.microsoft.com/team-services/compare-features/ gives 404. Should probably be https://azure.microsoft.com/en-us/services/devops/compare-features/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 75aa416a-b842-77d0-e18a-bee7f7bf7205
* Version Independent ID: 65942145-45ca-48bb-6adc-c16bd662b80a
* Content: [Manage users and access in Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/manage-users-table-view?view=vsts&tabs=new-nav)
* Content Source: [docs/organizations/accounts/manage-users-table-view.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/accounts/manage-users-table-view.md)
* Product: **devops**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Thanks for the heads up, @cowinr. This fix should be live sometime this afternoon. Thanks again!
