### ISSUE TITLE
Limitations on Azure Pipelines for invoiced GitHub customers

### ISSUE THREAD

**Issue by joakimhellum-in** [MicrosoftDocs/vsts-docs#2368]
There is a  known limitation of the GitHub Marketplace, namely that organizations which are paid via PO/invoice (as opposed to PayPal or debit/credit card), cannot use the Marketplace to add non-GitHub integrations.

This means that any invoiced customer cannot install Azure Pipelines from GitHub Marketplace, and will receive an error message if they try. So for our organization we cannot use the recommended authentication type (GitHub App), which is the only method that supports GitHub Checks.

It would be great if this was in the docs or if you could fix the issue please.

To be clear: our organization cannot enable GitHub Checks, because we are invoiced customer.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bfba9a21-e0f9-4fc6-43fc-bfdc51af31d3
* Version Independent ID: d93c7852-ce63-a6d0-417a-45f8cf2fc522
* Content: [Build GitHub repositories - Azure Pipelines & TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/github?view=vsts#authorize-access-to-your-repositories)
* Content Source: [docs/pipelines/repos/github.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/repos/github.md)
* Product: **devops**
* GitHub Login: @DavidStaheli
* Microsoft Alias: **dastahel**

**Comment by DavidStaheli** [comment]
That is great to know.  Thank you, @joakimhellum-in.  We will add this to the docs and look into a fix.

There is a separate, non-Marketplace page for installing the app.  Will this work for you?
https://github.com/apps/azure-pipelines

**Comment by DavidStaheli** [comment]
Oh, that's great news!  We've got to make it more discoverable.  I'll try some things when I add the info you suggested at the very top of this issue.  Thank you!

**Comment by DavidStaheli** [comment]
I added words to our docs that should make this more easily findable in web searches (below). Thanks again for bringing this to our attention, @joakimhellum-in!  I'm closing this issue now, but please reopen it if we can provide additional help.

---

### [Install the GitHub App](https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/github?view=vsts#install-the-github-app)

To use the GitHub App, install it in your GitHub organization or user account. The app can be installed and uninstalled from 2 locations:

1. The app's [homepage](https://github.com/apps/azure-pipelines) - This is recommended when no parallel jobs are being purchased, **or when your organization pays GitHub by purchase order (PO) or invoice**.
1. The app's [GitHub Marketplace listing](https://github.com/marketplace/azure-pipelines/) where additional parallel jobs can be purchased for private repositories, but where cancelation of the price plan may delay uninstallation until the end of your GitHub billing period, even for the free plan.
