### ISSUE TITLE
Process dimensions for expanded capacity instructions are refrencing the wrong dimension

### ISSUE THREAD

**Issue by SamGrantham** [MicrosoftDocs/vsts-docs#237]
The Error Provided and the dimension refrenced in the document are for WORKITEMS not VERSION CONTROL,
->Physical file: \\?\I:\OLAP\Data\Tfs_Analysis.0.db\vDimWorkItemOverlay.5.dim\7.WorkItemSK.asstore.
 ->vDimWorkItemOverlay. 
are WORK ITEM Dimensions.

The dimension for Version Control is dimFile and you would have to ping me to find/repro an example of that error.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b218b072-adff-201c-30f4-1286ca241826
* Version Independent ID: f107498f-9f47-a5b6-a52b-018b059fbefb
* [Content](https://docs.microsoft.com/en-us/vsts/report/admin/manually-process-data-warehouse-and-cube#process-dimensions-for-expanded-capacity)
* [Content Source](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/report/admin/manually-process-data-warehouse-and-cube.md)
* Service: unspecified

**Comment by SamGrantham** [comment]
it should read like one or both of these:

Process dimensions for expanded capacity
You should run the ProcessDimensionsForExpandedCapacity web service when you receive the following error message: 
Copy 
Microsoft.TeamFoundation.Warehouse.WarehouseException: TF221122: An error occurred running job Full Analysis Database Sync for team project collection or Team Foundation server TEAM FOUNDATION.  

Microsoft.TeamFoundation.Warehouse.WarehouseException: Failed to Process Analysis Database 'Tfs_Analysis'.  

You should run the ProcessDimensionsForExpandedCapacity web service when you receive the following error message: 
Microsoft.TeamFoundation.Warehouse.WarehouseException: TF221122: An error occurred running job Full Analysis Database Sync for team project collection or Team Foundation server TEAM FOUNDATION.
Microsoft.TeamFoundation.Warehouse.WarehouseException: Failed to Process Analysis Database 'Tfs_Analysis'. 
Microsoft.TeamFoundation.Warehouse.WarehouseException: File system error: A string store or binary store with a compatibility level of '1050' is at the maximum file size of 4 gigabytes. To store additional strings, you can change the StringStoresCompatibilityLevel property of the associated dimension or distinct count measure to '1100' and reprocess. This option is only available on databases with a compatibility level of '1100' or higher.
Physical file: \\?\I:\OLAP\Data\Tfs_Analysis.0.db\vDimWorkItemOverlay.5.dim\7.WorkItemSK.asstore.
This service changes the StringStoresCompatibilityLevel to 1100 for the Work Item  dimension and performs a full cube reprocess.
1.	From the Warehouse Control Web Service, choose ProcessDimensionsForExpandedCapacity. 
2.	Enter the name of the dimension. From the above error message, the dimension name is dimWorkItem. 
3.	The service returns True when it successfully resets the value to 1100. 
Wait until the cube processing has succeeded.


You should run the ProcessDimensionsForExpandedCapacity web service when you receive the following error message: 
Copy 
Microsoft.TeamFoundation.Warehouse.WarehouseException: TF221122: An error occurred running job Full Analysis Database Sync for team project collection or Team Foundation server TEAM FOUNDATION.  

Microsoft.TeamFoundation.Warehouse.WarehouseException: Failed to Process Analysis Database 'Tfs_Analysis'.  


You should run the ProcessDimensionsForExpandedCapacity web service when you receive the following error message: 
Microsoft.TeamFoundation.Warehouse.WarehouseException: TF221122: An error occurred running job Full Analysis Database Sync for team project collection or Team Foundation server TEAM FOUNDATION.
Microsoft.TeamFoundation.Warehouse.WarehouseException: Failed to Process Analysis Database 'TFS_Analysis'. 
Microsoft.TeamFoundation.Warehouse.WarehouseException: File system error: A string store or binary store with a compatibility level of '1050' is at the maximum file size of 4 gigabytes. To store additional strings, you can change the StringStoresCompatibilityLevel property of the associated dimension or distinct count measure to '1100' and reprocess. This option is only available on databases with a compatibility level of '1100' or higher. Physical file: \\?\E:\OLAP\Data\TFS_Analysis.0.db\File.0.dim\232.FileSK.asstore.

This service changes the StringStoresCompatibilityLevel to 1100 for the Version Control  dimension and performs a full cube reprocess.
1.	From the Warehouse Control Web Service, choose ProcessDimensionsForExpandedCapacity. 
2.	Enter the name of the dimension. From the above error message, the dimension name is dimFile. 
3.	The service returns True when it successfully resets the value to 1100. 
Wait until the cube processing has succeeded.

**Comment by KathrynEE** [comment]
@SamGrantham - Thank you for your contribution. I've updated the topic per your suggestion.

**Comment by SamGrantham** [comment]
Hi @KathrynEE A member of my team pointed out the the error on the "File" version of the error is incorrect, it should be like above in my Message:
 \?\E:\OLAP\Data\TFS_Analysis.0.db\File.0.dim\232.FileSK.asstore. 
but it is still: 
\?\I:\OLAP\Data\Tfs_Analysis.0.db\vDimWorkItemOverlay.5.dim\7.WorkItemSK.asstore.
Can you please use the message from my comment earlier here?
Sorry it took us so long to notice!
