### ISSUE TITLE
Great article

### ISSUE THREAD

**Issue by mokarian** [MicrosoftDocs/vsts-docs#2370]
Thank you this was a great article. Encourages the reader to gain curiosity to continue reading!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0cf98c4b-9185-00d5-a980-e2adb3e291fd
* Version Independent ID: f6005931-c9b5-48d9-e6c3-f835bb9b01b1
* Content: [What is DevOps? - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/learn/what-is-devops#how-to-achieve-devops)
* Content Source: [https://mseng.visualstudio.com/DefaultCollection/TechnicalContent/_git/devops-learn-pr?path=%2fdocs%2fwhat-is-devops.md&version=GBlive&_a=contents](https://mseng.visualstudio.com/DefaultCollection/TechnicalContent/_git/devops-learn-pr?path=%2fdocs%2fwhat-is-devops.md&version=GBlive&_a=contents)
* Product: **devops**
* Git Login: **samgu**
* Microsoft Alias: **samgu**

**Comment by steved0x** [comment]
@mokarian Thank you for the feedback, I will pass it along!
