### ISSUE TITLE
How do you use different data for different environments?

### ISSUE THREAD

**Issue by ravensorb** [MicrosoftDocs/vsts-docs#2371]
This article covers using test data, however it seems to be missing information on using different parameters for different environments (TEST, UAT, PROD) 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f7761a45-1375-dd7d-a3e8-d1d6d4bdbf9c
* Version Independent ID: 11be5092-02c1-37f7-3e52-e398b0cb6abd
* Content: [Repeat a test with different data](https://docs.microsoft.com/en-us/azure/devops/test/repeat-test-with-different-data?view=vsts)
* Content Source: [docs/test/repeat-test-with-different-data.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/test/repeat-test-with-different-data.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment]
Thank you for your feedback. Is it possible that this topic will help you: https://docs.microsoft.com/en-us/azure/devops/test/test-different-configurations?view=vsts. The section "Run tests with each configuration" describes how to run a specific test for selected parameters. Or are you runnign tests within a build or release pipeline? If you still have difficulties, please provide more information and I will pass your question on to the product team. Thank you.

**Comment by ravensorb** [comment]
Thanks, however that seems to be for test configurations (like browsers), what i am referring to is test data like different users, different URLs within a test case.  So for the UAT env, I would like to execute a test where param1 = http://uat.mysite.com  and in QA I would like param1 = http://qa.mysite.com 

Does that make sense?

**Comment by alexhomer1** [comment]
I will consult the product team and let you know their response. Thank you.
