### ISSUE TITLE
The release permisions need to be updated to contain the new names

### ISSUE THREAD

**Issue by vriesmarcel** [MicrosoftDocs/vsts-docs#2372]
the docs still use pipelines, the tool itself shows the following names in the dialog (copy past from my project):
Administer release permissions
Create releases
Delete release definition
Delete release environment
Delete releases
Edit release definition
Edit release environment
Manage deployments
Manage release approvers
Manage releases
View release definition
View releases

At the stage level, the product still uses the name environments. This should be renamed in the product to stage:
current names in the product:
Administer release permissions
Delete release environment
Edit release environment
Manage deployments
Manage release approvers

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a8c6f274-a008-fac6-7d99-13d2ce7c8dc3
* Version Independent ID: 916fef9e-d644-2114-b466-e5bda8028ee9
* Content: [Build and release permissions and security roles - Azure Pipelines & TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/policies/permissions?view=vsts)
* Content Source: [docs/pipelines/policies/permissions.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/policies/permissions.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by alexhomer1** [comment]
Thank you for your feedback. I will update the topic to include your recommendations.
