### ISSUE TITLE
Broken link xcodebuild man page.

### ISSUE THREAD

**Issue by luisnaranjo733** [MicrosoftDocs/vsts-docs#2373]
Link to xcodebuild man page is a 404

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ff158626-303c-b9aa-0507-50f9b898e364
* Version Independent ID: cf4561a9-40fa-af57-0e29-75cd339d7b7b
* Content: [Xcode Build build and release task - Azure Pipelines & TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/xcode-build?view=tfs-2018&viewFallbackFrom=vsts)
* Content Source: [docs/pipelines/tasks/build/xcode-build.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/build/xcode-build.md)
* Product: **devops**
* GitHub Login: @erickson-doug
* Microsoft Alias: **dastahel**

**Comment by DavidStaheli** [comment]
Thank you for reporting this, @luisnaranjo733!  It has been fixed and should be in production within 1 day.
