### ISSUE TITLE
Should provide steps to create a new repository

### ISSUE THREAD

**Issue by wsmelton** [MicrosoftDocs/vsts-docs#2374]
The content on this page shows the steps to create an additional repository, not an actually "new" repository for a project that was just newly created.

Under the new UI, the steps to create an initial repository on a new project require you to go into the project settings &gt; Code &gt; Repositories.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: df523114-2647-3282-525e-a0e4fe605dfb
* Version Independent ID: 91af894a-fb2f-ac3f-311f-978cd7dbf359
* Content: [Create a new Git repo in your project - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/create-new-repo?view=vsts&tabs=new-nav)
* Content Source: [docs/repos/git/create-new-repo.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/repos/git/create-new-repo.md)
* Product: **devops**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
@wsmelton A new project should include a repository by default, but if a TFVC repository was specified then there wouldn't be an initial Git repository and so you would have to perform the steps you describe, is that your scenario? I can make a note and link to this content: https://docs.microsoft.com/en-us/azure/devops/organizations/projects/create-project?view=vsts&tabs=new-nav#add-a-repository

Thank you.

**Comment by wsmelton** [comment]
Yeah I forgot about the default repo that exist. It might be worth adding a note on what you would see based on what version control was selected for a project.
