### ISSUE TITLE
Property dereference syntax for Variables gives a bad example

### ISSUE THREAD

**Issue by RickKra** [MicrosoftDocs/vsts-docs#2375]
The example for Property dereference syntax for Variables is variables.Build.SourceBranch. This example does not work because the prop name contains a period. (Not on the list of allowed chars.)

A different example should be used for this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77c58a78-a567-e99a-9eb7-62dddd1b90b6
* Version Independent ID: 680a79bc-11de-39fc-43e3-e07dc762db18
* Content: [Expressions - Azure Pipelines & TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/expressions?view=vsts#variables)
* Content Source: [docs/pipelines/process/expressions.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/expressions.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by vtbassmatt** [comment]
Fix is already published :)
