### ISSUE TITLE
Publish to Azure Artifacts nuget feed

### ISSUE THREAD

**Issue by martosource** [MicrosoftDocs/vsts-docs#2376]
The documentation is light on to publish a nuget package to the Azure Artifacts nuget feed.

Here is my complete .yml 

pool:
  vmImage: 'VS2017-Win2016'
  
steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'pack'
    configuration: 'release'
    packagesToPack: 'MyStuff/MyPackage.csproj' 
  
- task: NuGetCommand@2
  inputs:
    command: push
    nuGetFeedType: external
    publishFeedCredentials: '&lt;what should be here?&gt;'
    versioningScheme: byEnvVar
    versionEnvVar: Version

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f2512189-84f9-f997-0255-13b276c233b4
* Version Independent ID: c7ccb0ba-4221-bdac-85e1-111eaf51943b
* Content: [Publishing to NuGet feeds - Azure Pipelines & TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/targets/nuget?view=vsts&tabs=yaml)
* Content Source: [docs/pipelines/targets/nuget.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/targets/nuget.md)
* Product: **devops**
* GitHub Login: @erickson-doug
* Microsoft Alias: **amullans**

**Comment by sameera** [comment]
use `nuGetFeedType:internal` and remove the `publishFeedCredentials` property entirely.
I was struggling with this myself and found:
https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/package/nuget?view=vsts

**Comment by martosource** [comment]
I did find this, error as the feed URL was incorrect was missing the feed name for the project.
E.g. https://pkgs.dev.azure.com/<org>/_packaging/nuget/v3/index.json

Side note, is it possible to have a global/collection level nugget feed?

**Comment by sameera** [comment]
By playing around with the Visual Designer for Pipelines, I found that the YAML needs
`publishVstsFeed: 'your-feeds-uuid'`
By copying the feed UUID in the Designer generated UUID, I was able to get this working. I couldn't figure out where in the Az DevOps UI this UUID is listed. Providing the feed name instead of the UUID did not work.

**Comment by martosource** [comment]
Thanks @sameera all working.

**Comment by alexmullans** [comment]
@elbatk can you add a second example to this doc covering how to publish to a VSTS feed? Example YAML:
```yaml
steps:
- task: NuGetCommand@2
  displayName: 'NuGet push'
  inputs:
    command: push
    publishVstsFeed: 'af432f1b-f4b2-4a4f-bc9c-fef924f8f823'
    allowPackageConflicts: true
```

[Example designer build for screenshots](https://dev.azure.com/codesharing-demo/FabrikamFiber/_apps/hub/ms.vss-ciworkflow.build-ci-hub?_a=edit-build-definition&id=67)

**Comment by elbatk** [comment]
I've added that sample and it should hit live today, thanks everyone :)
