### ISSUE TITLE
Initializing the Driver from Environmental Variables makes out tests run for hours, and times out the build.

### ISSUE THREAD

**Issue by jfreal** [MicrosoftDocs/vsts-docs#2379]
If we run our tests locally and on Azure Devops with `Driver = new ChromeDriver(); ` the tests run fine.

If we use `Driver = new ChromeDriver(Environment.GetEnvironmentVariable("ChromeWebDriver"));` the tests take forever and will eventually exceed a six hour time limit.

![image](https://user-images.githubusercontent.com/144533/48199674-db2b9c00-e32a-11e8-8b60-c7fb5cdaa3fe.png)

Running with a remote Selenium with Browser Stack's Automate product works fine as well.

**Comment by jfreal** [comment]
I wanted this issue to link to: https://docs.microsoft.com/en-us/azure/devops/pipelines/test/continuous-test-selenium?view=vsts

I see using Github's UI didn't automatically add the linking code.

**Comment by alexhomer1** [comment]
Thank you for your feedback. I have passed this on to the product team for advice.

**Comment by alexhomer1** [comment]
The product team want to investigate this further. Please post all the information you have in their product development area at https://github.com/Microsoft/azure-pipelines-image-generation. Thank you!
