### ISSUE TITLE
Videos should be downloadable

### ISSUE THREAD

**Issue by dburnison** [MicrosoftDocs/vsts-docs#2380]
We need to have a way to download these videos. My practice has been to download various readiness videos and watch them on an airplane when I have to travel to meet with customers. Now that we are using Stream for internal videos and YouTube for public facing videos this is no longer possible. I REALLY MISS this capability.

Dave Burnison - Microsoft

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7e5835c5-57ca-e68d-f033-d97ec7bd106f
* Version Independent ID: 20ff829f-93d5-b3b8-8a34-612a9a5dc841
* Content: [DevOps at Microsoft - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/learn/devops-at-microsoft/)
* Content Source: [https://mseng.visualstudio.com/DefaultCollection/TechnicalContent/_git/devops-learn-pr?path=%2fdocs%2fdevops-at-microsoft%2findex.md&version=GBlive&_a=contents](https://mseng.visualstudio.com/DefaultCollection/TechnicalContent/_git/devops-learn-pr?path=%2fdocs%2fdevops-at-microsoft%2findex.md&version=GBlive&_a=contents)
* Product: **devops**
* Git Login: **samgu**
* Microsoft Alias: **samgu**

**Comment by steved0x** [comment]
@dburnison This is good feedback. For video content that is hosted on Channel 9, you can download it by clicking the Channel 9 icon in the embedded video which takes you to the Channel 9 website, and then you can download from there.

![image](https://user-images.githubusercontent.com/1580889/48360078-675ffb00-e66c-11e8-8b81-69c8945e15fc.png)

![image](https://user-images.githubusercontent.com/1580889/48360093-73e45380-e66c-11e8-9804-7693d282f7b5.png)

In this example, the video is hosted on Youtube, which doesn't have a download option (but there may be some options for viewing content offline in YouTube but I am not that familiar with it) and it looks like that video was from an O'Reilly conference, so I don't think we have a Channel 9 version.
