### ISSUE TITLE
Agent.JobName returns "Job"

### ISSUE THREAD

**Issue by teejam2** [MicrosoftDocs/vsts-docs#2382]
Agent.JobName returns "Job"...pretty self-explanatory

Here is my powershell task that echo $(Agent.JobName)

![image](https://user-images.githubusercontent.com/27975947/48213607-1901e200-e376-11e8-8824-6a75e6e94e25.png)

Here is the Job:

![image](https://user-images.githubusercontent.com/27975947/48213675-43ec3600-e376-11e8-9281-7be70ad53772.png)

Is this a bug, or have I done something wrong?

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 47625b86-abd5-ee15-6d61-8bcf81861b96
* Version Independent ID: be9a6174-a69b-7aed-d584-5f602fcc5eb4
* Content: [Build and Release Agents - Azure Pipelines & TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/agents?view=vsts)
* Content Source: [docs/pipelines/agents/agents.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/agents/agents.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by andyjlewis** [comment]
Which product are you using, Azure Pipelines or TFS? If that later, which version?

**Comment by vtbassmatt** [comment]
The display name isn't the same as the name. I don't think there's a way to choose your own job name in the visual editor, only in YAML. (We *also* had a bug for a while, but I think that's been fixed.)

**Comment by teejam2** [comment]
Could we have the Display Name as a predefined variable? Or make it possible to choose Name in the visual editor?

**Comment by vtbassmatt** [comment]
It's not an unreasonable request. Could you file a request on the [Azure Pipelines agent repo](https://github.com/Microsoft/azure-pipelines-agent)?
