### ISSUE TITLE
Product Backlog Definition Repeated

### ISSUE THREAD

**Issue by thekwilson** [MicrosoftDocs/vsts-docs#2386]
The Product Backlog definition is listed twice/repeated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6ad27465-68e9-82e0-588e-0fe164dd2041
* Version Independent ID: a9909dd9-486e-6f6d-dd63-9acd2a4f6ee1
* Content: [Key concepts and terminology for Azure Boards - Azure Boards & TFS](https://docs.microsoft.com/en-us/azure/devops/boards/get-started/key-concepts?view=vsts)
* Content Source: [docs/boards/get-started/key-concepts.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/boards/get-started/key-concepts.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@thekwilson - Thank you for the feedback. The article is being corrected as noted.
