### ISSUE TITLE
Define new YAML pipeline with another repo

### ISSUE THREAD

**Issue by teejam2** [MicrosoftDocs/vsts-docs#2387]
Hi,

Can we define a new YAML pipeline with another repo eg. Bitbucket?

Can this be set inside the YAML definition itself?

![image](https://user-images.githubusercontent.com/27975947/48251558-f6191180-e3f9-11e8-9332-a5a57a71b6c9.png)

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 38f7a23b-ebd4-af3e-68a2-275f7e45c33e
* Version Independent ID: f552a18c-ba29-00d4-03b6-254d7556d319
* Content: [Create your first pipeline - Azure Pipelines & TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/get-started-yaml?view=vsts)
* Content Source: [docs/pipelines/get-started-yaml.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/get-started-yaml.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by DavidStaheli** [comment]
Hi @teejam2.  Thanks for asking.  Currently, YAML can only be used with Azure Repos, GitHub, and GitHub Enterprise repositories.  YAML support for Bitbucket Cloud should be available by the end of 2018.  The repository type has to be set when the pipeline is created - in the Azure PIpelines UI or REST API.  Please let me know if I can help with anything you're trying.

**Comment by DavidStaheli** [comment]
Hi @teejam2. Support for using YAML with Bitbucket Cloud should be available in the first quarter of 2019. I'm closing this issue now, but please reopen it if we can provide additional help.

**Comment by fernandezjose** [comment]
I just ran into this issue. I can't move 57 repos to Github from Bitbucket. Is 'first quarter of 2019' still a firm announcement?

**Comment by DavidStaheli** [comment]
Hi @fernandezjose.  Yes, this feature is complete.  It should roll out to production between February 25 - March 1, 2019.

**Comment by DavidStaheli** [comment]
@fernandezjose and @teejam2, can you email me the name of your Azure DevOps organization?  We can possibly enable it for you early.  I'm at dastahel at microsoft -dot- com.

**Comment by letmaik** [comment]
Is there a plan to allow YAML pipelines for arbitrary servers? I realize there won't be an automatic trigger out of the box, but one could still run scheduled builds or possibly Azure Pipelines could allow for a triggering builds via a REST API (which it probably supports already?).

**Comment by b-long** [comment]
I'm also interested in this feature 👍

**Comment by christiansparre** [comment]
@DavidStaheli did it roll out to production as expected?

**Comment by DavidStaheli** [comment]
@christiansparre, unfortunately, it didn't make it as scheduled because of an unexpected "shape" in some peoples' data.  :(  The work is done, but it's looking like end-of-March before it's deployed and enabled everywhere.  I can enable it early on your Azure DevOps organization if needed.

**Comment by christiansparre** [comment]
@DavidStaheli ok. I pinged the Azure DevOps twitter account and had it enabled on friday :) so we're good. Will probably be trying it out this week.
