### ISSUE TITLE
Error in Run Docker image example

### ISSUE THREAD

**Issue by boskjoett** [MicrosoftDocs/vsts-docs#2389]
The example in "Run Docker images" section contains a wrong displayName. 
displayName: 'Push an image'
It should have been "Run image".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d9dbf88-7e55-d427-145e-d36b04fb197f
* Version Independent ID: a3f30c00-817c-9c05-7a57-3f2bf618821e
* Content: [Docker task - Azure Pipelines & TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/docker?view=vsts)
* Content Source: [docs/pipelines/tasks/build/docker.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/build/docker.md)
* Product: **devops**
* GitHub Login: @erickson-doug
* Microsoft Alias: **dastahel**

**Comment by shashankbarsin** [comment]
@boskjoett We have corrected this in our recent updates for the Docker task documentation :)
