### ISSUE TITLE
Missing documentation

### ISSUE THREAD

**Issue by boskjoett** [MicrosoftDocs/vsts-docs#2390]
This task is very poorly documented. Please document it like other tasks where you show all arguments and their default value. Many of the arguments marked as (Required) are not required. Several arguments are shown twice in the table, for example Command.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d9dbf88-7e55-d427-145e-d36b04fb197f
* Version Independent ID: a3f30c00-817c-9c05-7a57-3f2bf618821e
* Content: [Docker task - Azure Pipelines & TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/docker?view=vsts)
* Content Source: [docs/pipelines/tasks/build/docker.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/build/docker.md)
* Product: **devops**
* GitHub Login: @erickson-doug
* Microsoft Alias: **dastahel**

**Comment by shashankbarsin** [comment]
Sorry for the inconvenience caused. We are currently working on the rewriting the documentation for this task entirely. The changes should get merged soon.

**Comment by mrumpf** [comment]
In order to find the YAML syntax  I need to have a project using the graphical build pipeline definition and when setting an option, I need to switch to the "View YAML" display to find the YAML based notation for a property :(

**Comment by azooinmyluggage** [comment]
Thanks for the feedback. this will be fixed in the next few days :|

**Comment by shashankbarsin** [comment]
Thanks for reporting this issue. We have updated Docker task documentation to reflect the required/optional and default values.

**Comment by spcaswell-mindbody** [comment]
"Use this task in a build or release pipeline to build, tag, push, or run Docker images, or to run a Docker command."

There is absolutely zero documentation in this entire article pertaining to the last action in the quoted sentence.  I can run a Docker command from the graphical build tool, but where is equivalent yaml syntax?
