### ISSUE TITLE
Maximum limit of the recycle bin

### ISSUE THREAD

**Issue by Tracy933** [MicrosoftDocs/vsts-docs#2391]
Recycle bin can't show more than 99999 items. Is the maximum limit of the recycle bin 99999 work items?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e9f02cb-f094-d6bc-ca7b-973db9de0082
* Version Independent ID: 1af6a7f5-9e99-ec99-081d-c0bf9e7ac5f5
* Content: [Move, change, or delete work items - Azure Boards and TFS](https://docs.microsoft.com/en-us/azure/devops/boards/backlogs/remove-delete-work-items?view=vsts&tabs=new-nav#feedback)
* Content Source: [docs/boards/backlogs/remove-delete-work-items.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/boards/backlogs/remove-delete-work-items.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@Tracy933  - Thank you for your inquiry.  The maximum items in the Recycle Bin is the same as that for a mazimum query result size. For on-prem this is set to 99999. For cloud service accounts, it is set to 19999.

**Comment by hitesh1292** [comment]
Is there a way to filter the number of records to be below the 20k limit in the API query?
