### ISSUE TITLE
Using azure-pipelines.yml of master branch to build feature branches is wrong!

### ISSUE THREAD

**Issue by bravecobra** [MicrosoftDocs/vsts-docs#2394]
There are multiple reasons why using the master version of `azure-pipelines.yml` to build other branches is wrong
Some use something like gitversion. Committing to master would affect the version of your app (which a feature should never do). Furthermore, the whole concept of branches is that changes in one branch doesn't affect another. Here that concept is violated! 
If I build a feature branch, I expect it to use the version of `azure-pipelines.yml` in the same branch to build it. 

The fact that only the master version is consider is the main reason why I would never use Azure-Devops!

Is there a way to the behaviour I expected in the first place?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 521b594c-dbb9-54d5-f56f-00e2f5fa1d92
* Version Independent ID: 509d3e4e-23db-8493-e1a6-acb67ec47e81
* Content: [Building multiple branches - Azure Pipelines & TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/ci-build-git?view=vsts&tabs=yaml)
* Content Source: [docs/pipelines/build/ci-build-git.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/build/ci-build-git.md)
* Product: **devops**
* GitHub Login: @mlearned
* Microsoft Alias: **mlearned**

**Comment by vlef** [comment]
I found the documentation to not be very clear about this, but I don't think you are experiencing the correct behavior.

From my observations today, you do need a azure-pipelines.yml file in your master branch. But then, when you create a branch and edit the azure-pipelines.yml (within that new branch), when building that branch your modifications will be used (even though they are not yet merged with the master). The azure-pipelines.yml from your branch will be used for the build.

Using conditions (such as `condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))`) allows you to not have conflicts between branches and master at all time when you want different build behaviors between some branches and the master.

**Comment by exbarboss** [comment]
As I understand, you have 2 options create a giant yml config with all conditions for separate branches or use git merge strategies and use specific yml pipeline config per branch.

**Comment by bravecobra** [comment]
@vlef I was merely making the point that the documentation doesn't reflect that behavior. On the referenced page, there is no mention that when editing the `azure-pipelines.yml` in a branch, the build pipeline will be using that version of the file instead of the one in master, which was the conclusion I was talking after reading the docs. 
You would want the file to be able to be used in multiple branches. It needs to be resilient to your branching model, but at the same time you don't want new 'code' to leak into the master branch just to run the build.
Can we have the documentation to at least reflect that behavior and maybe add some extra part on how and where the `azure-pipelines.yml` is being read from an build-agent perspective. In other words, how does a build-agent read your repository and/or `azure-pipelines.yml` when it's triggered?

**Comment by tonyabbott** [comment]
When manually building a branch my experience is that it uses the yml file from HEAD (which in my case is develop, not master) instead of the one from the branch being built. I've tried changing the "Default branch for manual and scheduled builds" under "Get sources" to my feature branch but it still uses the definition from develop (which is how I conclude it must be using HEAD.) This is most annoying because it means I can't test changes to the build definition without first completing the PR and risking breaking the build.

I haven't tested with triggered builds but I assume it also uses HEAD. I can see there being a chicken-and-egg problem in that you must first decide which version of the yml to use when processing triggers before you know which branch(es) will be built. I'm not sure how one would resolve that, but certainly for manual builds I find the current behaviour counter-intuitive and unhelpful.

**Comment by andyjlewis** [comment]
@bravecobra thanks for the feedback and I'm sorry about the delayed response. I'm pretty sure the essence of the content in topic you originally posted your issue about has been refactored into other topics. One of them is this one: https://docs.microsoft.com/azure/devops/pipelines/repos/github. Please see that and other topics under Repositories and feel free to raise another issue over there if you are not finding what you need.

**Comment by steved0x** [comment]
We have added a FAQ for this as well [here](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/triggers?view=azure-devops&tabs=yaml#the-yaml-file-in-my-branch-is-different-than-the-yaml-file-in-my-master-branch-which-one-is-used) and also a few mentions in some other places like the one linked above. In short, it is the yaml file in the branch that is being pushed that is used.

**Comment by jons-aura** [comment]
What about manually triggered builds? I can't find anything in the linked documentation about which definition YAML is used when manually building a branch with an updated YAML file. From our testing it appears to be using the master branch definition still in that case.
