### ISSUE TITLE
Markdown code block does not render jsx properly

### ISSUE THREAD

**Issue by DavidHenri008** [MicrosoftDocs/vsts-docs#2395]
In the wiki of Azure DevOps, if I create a block of code and label it jsx, the jsx content does not render properly.
In the example below you may see that Github renders it properly, meaning the keywords are colored appropriately. With Azure DevOps starting from the fourth line (`return <img alt="Good" src="good.jpg" />;`) the text is all colored black even the last const keyword.
```jsx
export const getStatusImage = status => {
  switch (status) {
    case Status.GOOD:
      return <img alt="Good" src="good.jpg" />;
      break;
    default:
      return <img alt="Bad" src="bad.jpg" />;
      break;
  }
};
const dummy = "DUMMY";
```
From Azure DevOps:
![prtscr capture_14](https://user-images.githubusercontent.com/33123302/48264631-31b2dc00-e3f8-11e8-9a6f-0bb74fa463e6.jpg)

**Comment by steved0x** [comment]
@DavidHenri008 Thank you for reporting this. Do you believe it is a documentation error? If so can you let me know the URL of the article so I can forward this feedback to the author? Is it [this one](https://docs.microsoft.com/en-us/azure/devops/project/wiki/markdown-guidance?view=vsts#code-highlighting)?

If you are reporting a bug or issue with the product (sounds like an issue in the syntax highlighting?), please file an issue here: https://developercommunity.visualstudio.com/spaces/21/index.html

Thank you.

**Comment by steved0x** [comment]
@DavidHenri008 Thank you very much for the feedback.
