### ISSUE TITLE
DevOps Services Docs Search is not very flexible

### ISSUE THREAD

**Issue by klreeher** [MicrosoftDocs/vsts-docs#2397]
It's very hard to find documentation by the search in the DevOps services docs, as the search is only by title of the documentation. Being able to search by task name (ie, not only Publish Test Results, but also PublishTestResults) would make the documentation much faster and easier to use.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba91e46a-de53-c0c1-f7f7-c02e797d527c
* Version Independent ID: 6f478148-461f-694a-ed82-deb4d731854e
* Content: [Publish Test Results task - Azure Pipelines & TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/test/publish-test-results?view=vsts&tabs=yaml#feedback)
* Content Source: [docs/pipelines/tasks/test/publish-test-results.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/test/publish-test-results.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment]
Thank you for your feedback. I will pass this on to the website development team.
