### ISSUE TITLE
Link Multiple Existing Work Items to Features

### ISSUE THREAD

**Issue by ShaneCourtrille** [MicrosoftDocs/vsts-docs#2398]
Can this be added to this?  There is a separate Tutorial for Link work items but it doesn't talk about the explicit path for PBIs to Features and it's not obvious at all.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 82d92157-ab0e-b538-c284-32c70da8e2dd
* Version Independent ID: 86d6c2eb-5931-27ee-3df9-a1d0889d510a
* Content: [Define features and epics - Azure Boards and TFS](https://docs.microsoft.com/en-us/azure/devops/boards/backlogs/define-features-epics?view=vsts&tabs=new-nav)
* Content Source: [docs/boards/backlogs/define-features-epics.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/boards/backlogs/define-features-epics.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@ShaneCourtrille  - Thank you for the feedback. I have added a task to my backlog to update the content accordingly.
