### ISSUE TITLE
vsts wiki checklist

### ISSUE THREAD

**Issue by dmholb01** [MicrosoftDocs/vsts-docs#2399]
Hello,

I'm trying to create a checklist via a wiki. I loved the task list feature in github and had never had issues with it. I'm creating the checklist but the checkboxes are disabled. We cannot click on them. 

Example:

1. Something something here

- [ ] 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fa622358-f5bb-1f5c-177a-081a37b6acef
* Version Independent ID: 72f7fd16-a822-66c8-3a34-8905645ce5f2
* Content: [Markdown syntax for files, widgets, wikis - Azure DevOps & TFS](https://docs.microsoft.com/en-us/azure/devops/project/wiki/markdown-guidance?view=vsts)
* Content Source: [docs/project/wiki/markdown-guidance.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/project/wiki/markdown-guidance.md)
* Product: **devops**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @dmholb01 please go here for clarification: https://docs.microsoft.com/en-us/azure/devops/project/wiki/markdown-guidance?view=vsts#checklist-or-task-list 
Thanks and have a great day.

**Comment by dmholb01** [comment]
I've tried these instructions it's not working. Checkbox is disabled and not clickable when someone views the page.

**Comment by sandeepchads** [comment]
You cannot click on the check box when you are just viewing the page. You need to click on EDIT on the page, and then put a cross x between the braces [ ] to see the check box appear. This is a common mark standard.
E.g. in this  github issue try pasting the below code and preview it. You cannot change the check box items in preview but you can click on edit and put the crosses between the braces to check the checkboxes.

Hope this helps?

- [x] A  
- [ ] B  
- [x] C
