### ISSUE TITLE
Error message 'Source path does not exist' when Source is a unc path on a remote machine

### ISSUE THREAD

**Issue by nde-agridea** [MicrosoftDocs/vsts-docs#240]
I want to copy files from a remote folder to a remote folder, both on the same machine. However this produces an error 'Source path {0} does not exist' whereas the path does indeed exist. This contradicts the doc above about argument Source. Digging a bit further, this comes from the function Validate-SourcePath that the agent executes (see \path\to\agent\\_work\\_tasks\WindowsMachineFileCopy_731004d4-1d66-4f70-8c05-638018b22210\1.0.36\WindowsMachineFileCopy.ps1 lines 114-117). If, as a workaround, the check performed at those lines is commented, the task does proceed as expected. I believe this is a bug and that should be fixed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5e0ef2cf-ed52-6ded-bf14-4820d73b4ed0
* Version Independent ID: 7781e0f0-43aa-9008-abda-c03a37e2d7b4
* [Content](https://docs.microsoft.com/en-us/vsts/build-release/tasks/deploy/windows-machine-file-copy)
* [Content Source](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/build-release/tasks/deploy/windows-machine-file-copy.md)
* Service: unspecified

**Comment by alexhomer1** [comment]
I have passed your feedback onto the development team and they are looking into the issue. I understand that they intend to update the task to fix this issue.

Thank you
Alex

**Comment by GITGW** [comment]
Preparing task execution handler.
Executing the powershell script: D:\a\_tasks\WindowsMachineFileCopy_731004d4-1d66-4f70-8c05-638018b22210\1.0.42\WindowsMachineFileCopy.ps1

System.Management.Automation.RuntimeException: Source path '\\192.168.100.253\d$\REPO' does not exist. ---> System.Management.Automation.RuntimeException: Source path '\\192.168.100.253\d$\REPO' does not exist.
   --- End of inner exception stack trace ---
   at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)
   at System.Management.Automation.PowerShell.Worker.ConstructPipelineAndDoWork(Runspace rs, Boolean performSyncInvoke)
   at System.Management.Automation.PowerShell.Worker.CreateRunspaceIfNeededAndDoWork(Runspace rsToUse, Boolean isSync)
   at System.Management.Automation.PowerShell.CoreInvokeHelper[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
   at System.Management.Automation.PowerShell.CoreInvoke[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
   at Microsoft.TeamFoundation.DistributedTask.Handlers.LegacyVSTSPowerShellHost.VSTSPowerShellHost.Main(String[] args)

LegacyVSTSPowerShellHost.exe completed with return code: -1.

**Comment by SchneiderPatrick** [comment]
I have nearly the same problem. my source is using $(Build.Repository.LocalPath) and the final result looks like: C:\agent02\_work\r1\a\$(Build.Repository.LocalPath)

**Comment by roizentner** [comment]
@GITGW I just tried copying from file share and it worked.
I noticed the log states that the source path '\192.168.100.253\d$\REPO' does not exist.
You might be missing a backslash at the beginning there.

**Comment by MrVitaly** [comment]
I use 'Windows Machine File Copy' task (Description  : Copy files to remote machine(s); Version      : 1.0.41) in TFS Version 15.117.27024.0 and I have the same problem:

> Executing the powershell script: C:\BuildAgent\_work\_tasks\WindowsMachineFileCopy_731004d4-1d66-4f70-8c05-638018b22210\1.0.41\WindowsMachineFileCopy.ps1
> System.Management.Automation.RuntimeException: Source path _<SourcePath>_ does not exist. ---> System.Management.Automation.RuntimeException: Source path _<SourcePath>_ does not exist. 

It works on some build agents and does not work on others.

I see many differences in the lists of system capabilities provided by these hosts. Several of them are in the table below. I hope it will be helpful for the investigations of the issue.

| Capability name|Value (OK)|Value (Failed)|
|----------|:-------------|:------|
| Agent.OSVersion | 06.03.9600 | 10.0.14393 |
| HOST_IP | _not specified_ | _specified_ |
| HOST_NAME | _not specified_ | _specified_ |
| InteractiveSession | FALSE |   TRUE |
| PowerShell | 4.0 | 5.1.14393.1770 |
| USERDNSDOMAIN | _specified_ | _not specified_ |
