### ISSUE TITLE
Typo under select-team-sprints-and-default-iteration-path

### ISSUE THREAD

**Issue by hyonlim** [MicrosoftDocs/vsts-docs#2400]
Typo under
https://docs.microsoft.com/en-us/azure/devops/organizations/settings/set-team-defaults?view=vsts&tabs=new-nav#select-team-sprints-and-default-iteration-path

[New Navigation] Tab.
Project settings&gt;Work&gt;Team Configuration&gt;Iterations for a team.
actually
Project settings&gt;Boards&gt;Team Configuration&gt;Work&gt;Iterations for a team.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b3630a3f-5c46-ad60-577e-a78e7f916458
* Version Independent ID: 6a589739-e167-6ec3-ed56-ba184a4dabcd
* Content: [Set team defaults - Azure DevOps & TFS](https://docs.microsoft.com/en-us/azure/devops/organizations/settings/set-team-defaults?view=vsts&tabs=new-nav#select-team-sprints-and-default-iteration-path)
* Content Source: [docs/organizations/settings/set-team-defaults.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/settings/set-team-defaults.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@hyonlim  - Thank you for the feedback. The article is being updated accordingly.
