### ISSUE TITLE
HTML typo in "Update your last commit" section command line version 

### ISSUE THREAD

**Issue by feliperomero3** [MicrosoftDocs/vsts-docs#2402]
There is a strange HTML sentence in the middle of the git *commit* command. I'm thinking maybe the contributor forgot to write the closing brackets or something. Would you mind if I do a PR with the fix? Regards.

**It reads**
````
git commit -m --amend <font color="#b5bd68">"short descriptive message"
```` 
**And it should be**
```` 
git commit -m --amend "short descriptive message"
```` 

---

#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9654b64d-80e5-a28e-30d8-240b02bbe175
* Version Independent ID: c4f3eb8e-e203-7452-ba96-b0990107339a
* Content: [Save your changes with Git commits - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/commits?view=vsts&tabs=command-line)
* Content Source: [docs/repos/git/commits.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/repos/git/commits.md)
* Product: **devops**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
@feliperomero3 Thank you for letting us know, this is an artifact from when we migrated over to docs.microsoft.com, I'll get that fixed. Thank you.
