### ISSUE TITLE
Work details pane has different user interface.

### ISSUE THREAD

**Issue by limhyon** [MicrosoftDocs/vsts-docs#2404]
Work details pane has different user interface.
I can't see any progress bar style graph on my Azure DevOps.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de93c4e5-f491-af61-6df5-e7253d727dc9
* Version Independent ID: 417246fa-90ed-38a0-cc68-1de7895e96ce
* Content: [Set team capacity to support sprint planning - Azure Boards and TFS](https://docs.microsoft.com/en-gb/azure/devops/boards/sprints/set-capacity?view=vsts&tabs=new-nav)
* Content Source: [docs/boards/sprints/set-capacity.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/boards/sprints/set-capacity.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by evangeline-liu** [comment]
Hi Hyon! Thanks for your feedback. A couple of questions:

1. Have you set capacity for team members?
2. Have you set remaining work for any work items?

If these two items are properly set, then you should see the bars on your work details pane.

**Comment by KathrynEE** [comment]
CLosing this issue for now as haven't heard back from the customer.

**Comment by olivierhelin** [comment]
I guess Hyon is using Stories and effort field. We have the same issue, we don't use the task-level and we only set the effort field on Stories. So we would like to set team capacity in story points and have a work details pane based on story points instead of "task remaining hours".
