### ISSUE TITLE
"Days past start date" is incorrect

### ISSUE THREAD

**Issue by kulov** [MicrosoftDocs/vsts-docs#2408]
"Days past start date of iteration when planned work is final: " should read "Highlight work completed late: "

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1a948662-d534-bb71-a6b8-ce6d884b0ebb
* Version Independent ID: f065bef6-017a-2615-3292-4ca5787f8458
* Content: [Configure the Velocity widget based on Analytics data - Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/report/dashboards/team-velocity?toc=/azure/devops/report/analytics/toc.json&bc=/azure/devops/report/analytics/breadcrumb/toc.json&view=vsts)
* Content Source: [docs/report/dashboards/team-velocity.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/report/dashboards/team-velocity.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@kulov - thank you for the feedback. The article is getting updated accordingly.
