### ISSUE TITLE
Azure Keyvault parameters overwritten

### ISSUE THREAD

**Issue by dodsminister** [MicrosoftDocs/vsts-docs#2413]
Hi,

We have a task group that includes an Azure Key Vault task. This produces two variables. Lets call them $(a) and $(b). In the next task we use them as parameters for a PowerShell script ( -a $(a) -b $(b) ). 

When creating a task group, $(a) and $(b) becomes parameters and require a default value. When given that, the Azure Key Vault-task is no longer able to write to them, or perhaps parameters are reset to their default values before initiating the next task. Either way, this is a problem for us.

Is there a known work around?

**Comment by steved0x** [comment]
@dodsminister Thank you for the feedback. Can you let me know which article this feedback is for, so I can assign it to the author? You can reply here with the URL of the topic, or you can create a new issue by browsing to the topic on docs.microsoft.com and choosing **Content feedback** at the bottom. 

![image](https://user-images.githubusercontent.com/1580889/42953695-fd174150-8b48-11e8-94de-26924ca79c71.png)

**Comment by dodsminister** [comment]
This really did not end up where it was supposed to go! My mistake, closing
