### ISSUE TITLE
An Image needed to be Replaced

### ISSUE THREAD

**Issue by Yash-Yadav** [MicrosoftDocs/vsts-docs#2414]
In the TFVC section (Just above the Package management Section), the issue is that the 3rd image should be of x-Code as its link also directs to the x-Codel only, but the image is of Visual Studio (Just repetitive)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5f412c4c-d759-6260-e59b-80923d6372df
* Version Independent ID: 94be3497-80cf-25ee-1741-bd9f49ca560e
* Content: [DevOps overview for Azure DevOps Services and TFS](https://docs.microsoft.com/en-us/azure/devops/user-guide/devops-alm-overview?view=vsts)
* Content Source: [docs/user-guide/devops-alm-overview.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/user-guide/devops-alm-overview.md)
* Product: **devops**
* GitHub Login: @erickson-doug
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@Yash-Yadav thank you for your feedback. The article is being updaetd.
