### ISSUE TITLE
First Note is Baffling

### ISSUE THREAD

**Issue by schellem** [MicrosoftDocs/vsts-docs#2417]
I have absolutely no idea how to interpret the below Note. If you see a vertical sidebar it says enable new navigation but it also says New navigation has a vertical sidebar.

Choose New navigation if you see a vertical sidebar or if the New Navigation feature is enabled. The vertical sidebar along with other navigational features are enabled when New Navigation has been enabled for the signed-in user or the organization. To learn how to use the web portal effectively, see Web portal navigation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 90ff4c66-0e6e-48e2-de64-2b772e1d10da
* Version Independent ID: ac420358-3388-6270-6372-2fef766917ba
* Content: [Navigating within the web portal - Azure DevOps Services & TFS](https://docs.microsoft.com/en-us/azure/devops/project/navigation/index?view=vsts&tabs=new-nav)
* Content Source: [docs/project/navigation/index.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/project/navigation/index.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@schellem  - Thank you for the feedback. I agree that the first note was confusing. I'm in the process of correcting it.
