### ISSUE TITLE
Broken screenshot images

### ISSUE THREAD

**Issue by SarahSexton** [MicrosoftDocs/vsts-docs#2419]
There are broken references to screenshot images in the "Create a Build Pipeline" section, "2. Create a new pipeline" sub-section. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 02b747eb-53c2-dd5f-cd2b-f337c15e0864
* Version Independent ID: 04538505-00cd-33ac-8008-4b85cca089e3
* Content: [Use the visual designer to create a CI/CD pipeline - Azure Pipelines & TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/get-started-designer?view=vsts&tabs=new-nav#feedback)
* Content Source: [docs/pipelines/get-started-designer.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/get-started-designer.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by elbatk** [comment]
I'm not seeing these broken image links, and the file hasn't been updated recently, are you still seeing them? Which version of the article are you viewing (Azure DevOps Services vs. TFS?)

**Comment by elbatk** [comment]
Closing this as I think we've resolved it :)
