### ISSUE TITLE
Old screenshot for adding New work item type

### ISSUE THREAD

**Issue by kulov** [MicrosoftDocs/vsts-docs#2421]
The screenshot for "Add or modify work item types" for adding new work item type in "2. From the Work Item Types page, choose the New work item type." is from the old user experience.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bbd11642-1af2-c211-68bc-7e324131a6cb
* Version Independent ID: 81d3f210-59e5-8487-0347-3db574242a97
* Content: [Customize a project - Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/organizations/settings/work/customize-process?view=vsts&tabs=new-nav)
* Content Source: [docs/organizations/settings/work/customize-process.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/settings/work/customize-process.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@kulov - thank you for the feedback. I've added a task to my backlog to update the screenshot.
