### ISSUE TITLE
Spelling

### ISSUE THREAD

**Issue by shehackspurple** [MicrosoftDocs/vsts-docs#2422]
Hi, I tried to edit this myself but when I forked the code it wasn't spelled incorrectly anymore...

"Refer to the oswa zap vsts extension"

Should say

"Refer to the OWASP zap vsts extension"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 31e62447-f971-a085-7ded-442a363f31e7
* Version Independent ID: 5c650019-951f-b103-3010-bfee05b99acc
* Content: [Add Continuous Security Validation to your CICD Pipeline](https://docs.microsoft.com/en-us/azure/devops/articles/security-validation-cicd-pipeline?view=vsts)
* Content Source: [docs/articles/security-validation-cicd-pipeline.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/articles/security-validation-cicd-pipeline.md)
* Product: **devops**
* GitHub Login: @mikedouglasdev
* Microsoft Alias: **douge**

**Comment by nschonni** [comment]
Fixed in #2820
