### ISSUE TITLE
Readers group, documentation wrong?

### ISSUE THREAD

**Issue by SebastianSchuetze** [MicrosoftDocs/vsts-docs#2424]
This article as well as the article on the article page https://docs.microsoft.com/en-us/azure/devops/organizations/security/permissions?view=vsts#git-repository-object-level talk about a project collection level "Readers group" which has basically read access to all projects by default. This group can nowhere be found on Azure DevOps.

The bug report states. that such a feature (read onnly access on project collection level) does not exist.

https://developercommunity.visualstudio.com/content/problem/189218/how-to-created-a-read-only-project-collection-acce.html

What is correct in that regard?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ae5c3b5-9751-743f-6e68-d20a2fac6243
* Version Independent ID: 66756817-161b-cadf-f13c-10a216fae08a
* Content: [Set project or collection-level permissions - Azure DevOps & TFS](https://docs.microsoft.com/en-us/azure/devops/organizations/security/set-project-collection-level-permissions?view=vsts&tabs=new-nav)
* Content Source: [docs/organizations/security/set-project-collection-level-permissions.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/security/set-project-collection-level-permissions.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@SebastianSchuetze - Thank you for your inquiry. You are correct, the Readers group isn't a default group iat the organization or collection level. I will make a note to update the articles accordingly.
