### ISSUE TITLE
How to correctly tie work items to release builds

### ISSUE THREAD

**Issue by tanzencoder** [MicrosoftDocs/vsts-docs#2426]
I love this approach to branches and we have started implementing them for our projects. One thing that has come up though is that in the creation of a release branch and subsequent build the associated work items don't reflect what was included since the last release branch it includes all of them. We like the feature of associated work items so how do we get that worked out?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d1235ec4-e7e9-b0c2-8f1f-ee9682175a05
* Version Independent ID: a473750a-fbb6-4eed-e0e6-34e8a5009507
* Content: [Release Flow - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/learn/devops-at-microsoft/release-flow)
* Content Source: [https://mseng.visualstudio.com/DefaultCollection/TechnicalContent/_git/devops-learn-pr?path=%2fdocs%2fdevops-at-microsoft%2frelease-flow.md&version=GBlive&_a=contents](https://mseng.visualstudio.com/DefaultCollection/TechnicalContent/_git/devops-learn-pr?path=%2fdocs%2fdevops-at-microsoft%2frelease-flow.md&version=GBlive&_a=contents)
* Product: **devops**
* Git Login: **samgu**
* Microsoft Alias: **ethomson**

**Comment by true-zanuda** [comment]
I'm still interested in a response.

**Comment by andybowles66** [comment]
This is a bit clunky, but I think it works:

Suppose that you have just released v 1.1, and you're now in a sprint called "1.2/Sprint 1"
- Create an iteration called "1.1/Fixes".  Don't associate a sprint with it.
- In the user story for the fix, create two tasks:
 * A development task, assigned to 1.2/Sprint 1
 * A task for merging the patch into into version 1, assigned to 1.1/Fixes

Now the user story will be visible in both iterations.

Now you will see the user story in both
