### ISSUE TITLE
Update the default composer version

### ISSUE THREAD

**Issue by zanechua** [MicrosoftDocs/vsts-docs#2429]
The composer version included in the default version is v1.0 built in 2016. Kinda an old build and would be nice if it was updated to something more recent. 

See relevant issue and solutions: https://developercommunity.visualstudio.com/content/problem/343384/update-composer-in-php-pipeline-ubuntu-1604.html

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4d21b6ef-2440-f2b7-7f38-465ade7c14c6
* Version Independent ID: 9b2ebcef-924d-6850-9c27-4f14a2b45b53
* Content: [Building PHP projects with Azure Pipelines or TFS - Azure Pipelines & TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/languages/php?view=vsts)
* Content Source: [docs/pipelines/languages/php.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/languages/php.md)
* Product: **devops**
* GitHub Login: @erickson-doug
* Microsoft Alias: **dastahel**

**Comment by JoshTango** [comment]
I just tried pipelines to make a php environment and it failed on composer install?

**Comment by JoshTango** [comment]
2018-11-13T16:14:44.5819906Z Composer could not find a composer.json file in /home/vsts/work/1/s
2018-11-13T16:14:44.5820517Z To initialize a project, please create a composer.json file as described in the https://getcomposer.org/ "Getting Started" section
2018-11-13T16:14:44.6041123Z ##[error]Bash exited with code '1'.
2018-11-13T16:14:44.6052940Z ##[section]Finishing: composer install

**Comment by JoshTango** [comment]
well I just imported drupal 8.3 from GitHub into a repo and ran a php build and it failed on composer install

**Comment by zanechua** [comment]
@JoshTango 

Don't think this is the right place for this. Please create your own issue.

**Comment by nschonni** [comment]
Both are probably better for https://developercommunity.visualstudio.com/spaces/21/index.html since they don't relate to the docs

**Comment by zanechua** [comment]
@nschonni 

Sure definitely. But definitely worth mentioning on the docs page for people looking.

**Comment by Bilge** [comment]
The version included is actually pre-1.0, but regardless, the main problem with the bundled Composer version is that it doesn't have the self-update command, so upgrading it is far more painful than on other CI systems.

**Comment by zanechua** [comment]
Confirm and tested fixed.

Re: https://developercommunity.visualstudio.com/solutions/400040/view.html

**Comment by AnthonyG4** [comment]
> Confirm and tested fixed.
> 
> Re: https://developercommunity.visualstudio.com/solutions/400040/view.html

That link doesn't work for me (404).
**What was the fix please?**

Also, @nschonni though I appreciate the point that the docs would not need updating so long as the linked pages are up to date, while those linked pages/resources are not up to date, the piece of documentation is technically faulty given that they cannot be followed to completion without adding steps that are not (yet) documented.

**Comment by zanechua** [comment]
Hey @AnthonyG4 

I can't seem to find the actual thread that I linked to anymore and seems like they just lift and shifted without due care for older URLs so I'm not exactly sure what that pointed to.

As for the default composer version, I believe this issue doesn't happen anymore?

The only reference I have to this is my `azure-pipelines.yml` that I edited around the date that I said that this was fixed.

https://github.com/poowf/invoiceneko/commit/037e212e390adc56e8d6d2b60c348a88a1fe0e13

I have a feeling I was referencing to a post where someone posted that they had updated the composer version in the default runners and the problem shouldn't exist. Alternatively you can use my commit as a reference to install composer manually.

Hopefully that helps?
