### ISSUE TITLE
Version section is missing details about the BUILD version

### ISSUE THREAD

**Issue by nschonni** [MicrosoftDocs/vsts-docs#243]
Although the `version` field does not support full Semantic Versioning numbers (EX: 1.0.0-alpha), it does support a fourth digit in the version number that isn't indicated here.
> Should be in the format major.minor.patch, for example 0.1.2 or 1.0.0

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d8b703fe-8982-4284-6db0-ef33abac08a4
* Version Independent ID: 0fc84d11-1c32-0a49-04ec-641b68f44886
* [Content](https://docs.microsoft.com/en-us/vsts/extend/develop/manifest#feedback)
* [Content Source](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/extend/develop/manifest.md)
* Service: unspecified

**Comment by elbatk** [comment]
Adding this in an upcoming PR today, thanks!
