### ISSUE TITLE
Really confusing and broken

### ISSUE THREAD

**Issue by Simone000** [MicrosoftDocs/vsts-docs#2430]
Sometimes it change behaviours by itself, it's confusing and unclear.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a1944149-ef01-c421-2ec8-c51626c31e0a
* Version Independent ID: e774788f-e1db-babf-556f-9aff176a4bd9
* Content: [Manage notifications for an organization - Azure DevOps Services & TFS](https://docs.microsoft.com/en-us/azure/devops/notifications/howto-manage-organization-notifications?view=vsts)
* Content Source: [docs/notifications/howto-manage-organization-notifications.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/notifications/howto-manage-organization-notifications.md)
* Product: **devops**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @Simone000 I'm sorry you're confused and things are unclear. It sounds like your feedback should be addressed to the following Developer Community site, where you can report a problem and/or suggest a feature. They'll be able to help you out. Thank you.
