### ISSUE TITLE
Add examples for Windows Host/Linux on how to use Build.ArtifactStagingDirectory 

### ISSUE THREAD

**Issue by phil-lgr** [MicrosoftDocs/vsts-docs#2437]
as title, I need to set "Compose File Path" but I am not sure how to enter the path for a Windows host

is it $(Build.ArtifactStagingDirectory)/docker-compose-ci.yml ? where docker-compose-ci.yml is my artefact

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ffebdc8-521c-44b5-cde4-4abdc1bd6f18
* Version Independent ID: dc0effda-6d93-62aa-64c5-4e6f283b0826
* Content: [Predefined build variables - Azure Pipelines & TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=vsts)
* Content Source: [docs/pipelines/build/variables.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/build/variables.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by vtbassmatt** [comment]
`$()` is simply string replacement, so what you wrote will work cross-plat. If you're only ever going to run on Windows, it might be more clear to write `$(Build.ArtifactStagingDirectory)\docker-compose-ci.yml` to keep the slashes going the same direction.
