### ISSUE TITLE
Seems there is no way to define Counters in Designer

### ISSUE THREAD

**Issue by TqrHsn** [MicrosoftDocs/vsts-docs#2438]
Could not find a way to define Counters in non yaml based Build definitions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd7e0bd3-1f7d-d7b6-cc72-5ef63c31b46a
* Version Independent ID: dae87abd-b73d-9120-bcdb-6097d4b40f2a
* Content: [Pipeline variables - Azure Pipelines & TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=vsts&tabs=designer%2Cbatch)
* Content Source: [docs/pipelines/process/variables.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/variables.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by Vossekop** [comment]
You can just create a variable in the designer for the build definition and set the value to $[counter('versioncounter', 100)] for instance. This just works. However, it doesn't work in releases as far as I have been able to determine.

**Comment by vijayma** [comment]
Updated the doc to include an example of how to do this in designer.
