### ISSUE TITLE
Registry

### ISSUE THREAD

**Issue by mmj78** [MicrosoftDocs/vsts-docs#244]
Adding another location for Registry to check. If you are using Office365, check this as well:
HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Office\ClickToRun\REGISTRY\MACHINE\Software\Wow6432Node\Microsoft\Office\Excel\Addins\TFCOfficeShim.Connect.1x

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cc3b1a8f-f0cb-a613-9fd2-dc200310e951
* Version Independent ID: 8ca63218-a03c-4d4a-2281-56aefc4fef2a
* [Content](https://docs.microsoft.com/en-us/vsts/work/backlogs/office/tfs-office-integration-issues)
* [Content Source](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/work/backlogs/office/tfs-office-integration-issues.md)
* Service: unspecified

**Comment by KathrynEE** [comment]
@mmj78 - Thank you for your comment. However, the topic explicitly states that Office365 is not supported, so I'm rejecting adding this additional registry key to check.

**Comment by ClaytonBenPRA** [comment]
Kathryn - I can't find any statement that Office 365 (Excel 2016, native) is unsupported. Further, Excel 2016 is explicitly listed as supported in the document "https://docs.microsoft.com/en-us/vsts/tfs-server/requirements" under the "Client Compatibility"/"Office" section. 

Can you please re-open this comment and have support investigate the registry key? Thanks.
