### ISSUE TITLE
Replace `variables.Agent.OS` with `variables['Agent.OS']`

### ISSUE THREAD

**Issue by janpio** [MicrosoftDocs/vsts-docs#2440]
In "Switch based on platform" the three conditions for the steps are broken right now. Instead of `variables.Agent.OS` you have to use `variables['Agent.OS']`, otherwise the variable evaluates to NULL which will not match the string.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 797838e7-f32b-868e-8766-8d96973bf18f
* Version Independent ID: 20c9e62d-56ec-f5a0-c3f9-6f72bf96252e
* Content: [Cross-platform scripting - Azure Pipelines & TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/scripts/cross-platform-scripting?view=vsts&tabs=yaml)
* Content Source: [docs/pipelines/scripts/cross-platform-scripting.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/scripts/cross-platform-scripting.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by kittaakos** [comment]
The example script has been updated via. https://github.com/MicrosoftDocs/vsts-docs/commit/1a246f2ad9faa5693fc00366ed10ec47d77d8c13.
