### ISSUE TITLE
fixe broken links

### ISSUE THREAD

**Issue by nikoNguyen** [MicrosoftDocs/vsts-docs#2443]
Manage users and access in Azure DevOps

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4248a01c-87cf-b534-d3aa-c139265e47f3
* Version Independent ID: 94e10c7f-f3a5-3b13-0ac3-9d6614bc19b5
* Content: [Change access levels for a user or group, manage access to features - TFS](https://docs.microsoft.com/en-us/azure/devops/organizations/security/change-access-levels?view=vsts)
* Content Source: [docs/organizations/security/change-access-levels.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/security/change-access-levels.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@nikoNguyen - thank you for the feedback. I believe the link is now fixed.
