### ISSUE TITLE
Add example on how to clone a simple repo using a PAT without credential manager

### ISSUE THREAD

**Issue by JoseFMP** [MicrosoftDocs/vsts-docs#2444]
This is totally missing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2bfea574-db69-a5fd-37fe-64ecfdac502a
* Version Independent ID: 4037d475-f194-2ac9-ffd6-70530fc3140a
* Content: [Authenticate access with personal access tokens](https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/use-personal-access-tokens-to-authenticate?view=vsts)
* Content Source: [docs/organizations/accounts/use-personal-access-tokens-to-authenticate.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/accounts/use-personal-access-tokens-to-authenticate.md)
* Product: **devops**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by steved0x** [comment]
@JoseFMP Is this the approach that you are talking about? Including the PAT on the command line when cloning?

https://blogs.msdn.microsoft.com/uk_faculty_connection/2016/10/26/using-git-cmd-prompt-with-visual-studio-team-services/

If so we can add an example, and sorry that you ran into trouble.

**Comment by chcomley** [comment]
@JoseFMP Since this is not a common case, nor something we want to encourage users to use, we won't be updating the documentation. However, if you need to do it, Open Issue #1474 has a good thread on this. In summary, here's what's needed: -c http.extraheader={base64(":" + token)}
Where token is the PAT. Thank you!

**Comment by JoseFMP** [comment]
The method provided by @steved0x seems to work for me. I will try on the other machine later.
