### ISSUE TITLE
re/using custom powershell module (.psm1) in vnext  

### ISSUE THREAD

**Issue by verbaloid** [MicrosoftDocs/vsts-docs#2445]
May one use/call powershell module (.psm) functions out of this task?
What would be a correct approach to re/use powershell module out of vnext?

**Comment by steved0x** [comment]
@verbaloid Thank you for the feedback. Can you let me know which article this feedback is for, so I can assign it to the author? You can reply here with the URL of the topic, or you can create a new issue by browsing to the topic on docs.microsoft.com and choosing **Content feedback** at the bottom. 

![image](https://user-images.githubusercontent.com/1580889/42953695-fd174150-8b48-11e8-94de-26924ca79c71.png)

**Comment by vtbassmatt** [comment]
Yes, you can load PowerShell modules within the task.
