### ISSUE TITLE
CopyFiles task: Negative globbing doesn't work for me

### ISSUE THREAD

**Issue by benjamincburns** [MicrosoftDocs/vsts-docs#2446]
I'm using a YAML build pipeline definition. I'm trying to exclude the git directory and node_modules directories from my artifact publish. I've tried a bunch of different permutations, but I can't seem to get it to work. Based on the above, and on [the note over in the patterns reference doc to use `/` instead of `\` as a path separator](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/file-matching-patterns?view=vsts#slash) (this doc doesn't seem to follow that, however), I'd expect the following config to work. Instead, it copies zero files.

```
- task: CopyFiles@2
  inputs:
    targetFolder: '$(Build.ArtifactStagingDirectory)'
    contents: |
      '**'
      '!(node_modules|.git)/**'
```

Alternatively, I'd expect the following to work (this also copies zero files):

```
- task: CopyFiles@2
  inputs:
    targetFolder: '$(Build.ArtifactStagingDirectory)'
    contents: |
      '**'
      '**/!(node_modules|.git)/**'
```

This one also doesn't work (again, zero files copied):

```
- task: CopyFiles@2
  inputs:
    targetFolder: '$(Build.ArtifactStagingDirectory)'
    contents: '**/!(node_modules|.git)/**'
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 81f02378-b85b-d3a4-d3c8-f07d935367da
* Version Independent ID: fab57f76-35d2-4024-6f7f-1740d7b24743
* Content: [Copy Files task - Azure Pipelines & TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/copy-files?view=vsts)
* Content Source: [docs/pipelines/tasks/utility/copy-files.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/utility/copy-files.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by aaroncatlin** [comment]
I managed to get this to work with the following syntax:

  **
  !Backups\**

This copies all files in the target directory and subdirectories except for those in the Backups folder.

**Comment by rncwnd79** [comment]
This definitely needs a brush up!

This didn't work:
`!node_modules/**/*`

Nor did:
`!node_modules/**`

Also not working:
`!**/node_modules/**`

This works:
`!$(System.DefaultWorkingDirectory)/node_modules/**`

**Comment by aaroncatlin** [comment]
So instead of trying my example which I've mentioned actually works (I now have this in our production environment), you instead downvote my comment and then proceed to list all of the things you've tried that didn't work and do not match the syntax of my suggestion.  👏 

Have you tried the below?

**
!node_modules**

The first ** includes everything
The second line tells it to exclude anything in the node_modules folder.

**Comment by vtbassmatt** [comment]
There are a couple separate issues here:

- You don't need to quote lines in a `|` string in YAML. So it should be:
```yaml
contents: |
  **
  **/!(node_modules|.git)/**
```

That said, it still doesn't seem to work :) so I've filed a bug to get to the bottom of why. https://github.com/microsoft/azure-pipelines-tasks/issues/10395

**Comment by vtbassmatt** [comment]
The parenthetical pattern needs to include a leading `+`, per [`fnmatch` syntax](http://man7.org/linux/man-pages/man3/fnmatch.3.html). 

```yaml
contents: |
  **
  !+(node_modules|.git)/**
```

We can certainly doc that a little more clearly, so leaving this issue open.

**Comment by mmeneesnh** [comment]
I'm not sure why this issue is closed; I'm using the classic editor, and negative globbing doesn't work for me:

```
!.git/**/*
!.gitignore
```

I wondered if it was something with the dot files, but it even fails on something like `README.MD`.

**Comment by siburny** [comment]
@mmeneesnh I just set up a task using the classical editor, and I was able to exclude ".git" folder like this:
```
**/*
!.git/**/*
```

**Comment by Danielovich** [comment]
VmImage: ubuntu-20.04

```
    - task: CopyFiles@2
      displayName: 'Copy deployment files'
      inputs:
        SourceFolder: '$(Pipeline.Workspace)'
        contents: | 
          **
          !.git/**/*
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
        flattenFolders: true

```

This is not excluding my .git directory.

Produces the following output on my pipeline:

```
found 33 files
Copying /home/vsts/work/1/s/.git/FETCH_HEAD to /home/vsts/work/1/a/FETCH_HEAD
Copying /home/vsts/work/1/s/.git/HEAD to /home/vsts/work/1/a/HEAD
Copying /home/vsts/work/1/s/.git/config to /home/vsts/work/1/a/config
Copying /home/vsts/work/1/s/.git/description to /home/vsts/work/1/a/description
Copying /home/vsts/work/1/s/.git/hooks/applypatch-msg.sample to /home/vsts/work/1/a/applypatch-msg.sample
Copying /home/vsts/work/1/s/.git/hooks/commit-msg.sample to /home/vsts/work/1/a/commit-msg.sample
Copying /home/vsts/work/1/s/.git/hooks/fsmonitor-watchman.sample to /home/vsts/work/1/a/fsmonitor-watchman.sample
Copying /home/vsts/work/1/s/.git/hooks/post-update.sample to /home/vsts/work/1/a/post-update.sample
Copying /home/vsts/work/1/s/.git/hooks/pre-applypatch.sample to /home/vsts/work/1/a/pre-applypatch.sample
Copying /home/vsts/work/1/s/.git/hooks/pre-commit.sample to /home/vsts/work/1/a/pre-commit.sample
Copying /home/vsts/work/1/s/.git/hooks/pre-merge-commit.sample to /home/vsts/work/1/a/pre-merge-commit.sample
Copying /home/vsts/work/1/s/.git/hooks/pre-push.sample to /home/vsts/work/1/a/pre-push.sample
Copying /home/vsts/work/1/s/.git/hooks/pre-rebase.sample to /home/vsts/work/1/a/pre-rebase.sample
Copying /home/vsts/work/1/s/.git/hooks/pre-receive.sample to /home/vsts/work/1/a/pre-receive.sample
Copying /home/vsts/work/1/s/.git/hooks/prepare-commit-msg.sample to /home/vsts/work/1/a/prepare-commit-msg.sample
Copying /home/vsts/work/1/s/.git/hooks/push-to-checkout.sample to /home/vsts/work/1/a/push-to-checkout.sample
Copying /home/vsts/work/1/s/.git/hooks/sendemail-validate.sample to /home/vsts/work/1/a/sendemail-validate.sample
Copying /home/vsts/work/1/s/.git/hooks/update.sample to /home/vsts/work/1/a/update.sample
Copying /home/vsts/work/1/s/.git/index to /home/vsts/work/1/a/index
Copying /home/vsts/work/1/s/.git/info/exclude to /home/vsts/work/1/a/exclude
File /home/vsts/work/1/s/.git/logs/HEAD already exist at /home/vsts/work/1/a/HEAD
Copying /home/vsts/work/1/s/.git/logs/refs/remotes/origin/234fb901970f293e36e95ae7e9367aca6acf310b to /home/vsts/work/1/a/234fb901970f293e36e95ae7e9367aca6acf310b
Copying /home/vsts/work/1/s/.git/objects/23/4fb901970f293e36e95ae7e9367aca6acf310b to /home/vsts/work/1/a/4fb901970f293e36e95ae7e9367aca6acf310b
Copying /home/vsts/work/1/s/.git/objects/33/4a3c2b8a0ff71ac9f6c500575366ea6fa0f264 to /home/vsts/work/1/a/4a3c2b8a0ff71ac9f6c500575366ea6fa0f264
Copying /home/vsts/work/1/s/.git/objects/c9/2df27a8fd7722dc1211b2ff624de38bcd57c58 to /home/vsts/work/1/a/2df27a8fd7722dc1211b2ff624de38bcd57c58
Copying /home/vsts/work/1/s/.git/objects/e7/4b7c0711eaee4902a89c42d9a68da3c0201187 to /home/vsts/work/1/a/4b7c0711eaee4902a89c42d9a68da3c0201187
Copying /home/vsts/work/1/s/.git/objects/f7/f6a089af5dc7eb7d94d64c864a9b8048d9f632 to /home/vsts/work/1/a/f6a089af5dc7eb7d94d64c864a9b8048d9f632
Copying /home/vsts/work/1/s/.git/objects/fd/5f65674764b17e52c8d34f03c5ee453c9d9f4f to /home/vsts/work/1/a/5f65674764b17e52c8d34f03c5ee453c9d9f4f
File /home/vsts/work/1/s/.git/refs/remotes/origin/234fb901970f293e36e95ae7e9367aca6acf310b already exist at /home/vsts/work/1/a/234fb901970f293e36e95ae7e9367aca6acf310b
Copying /home/vsts/work/1/s/.git/shallow to /home/vsts/work/1/a/shallow
Copying /home/vsts/work/1/s/Dockerfile to /home/vsts/work/1/a/Dockerfile
Copying /home/vsts/work/1/s/azure-pipelines.yml to /home/vsts/work/1/a/azure-pipelines.yml
Copying /home/vsts/work/1/s/deploy/deploy.ps1 to /home/vsts/work/1/a/deploy.ps1
```

The exclude in this example is to my assumption not correct.  https://github.com/MicrosoftDocs/azure-devops-yaml-schema/blob/main/task-reference/copy-files-v2.md#yaml-1
