### ISSUE TITLE
Add example on how to use this to deploy a docker-compose setup to Web App for container

### ISSUE THREAD

**Issue by phil-lgr** [MicrosoftDocs/vsts-docs#2448]
as title

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d767aebb-620e-9ad3-e906-3e2bafa02ee9
* Version Independent ID: c8cb5a48-ccdf-778c-1547-a10db74cb56c
* Content: [Docker Compose task - Azure Pipelines & TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/docker-compose?view=vsts)
* Content Source: [docs/pipelines/tasks/build/docker-compose.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/build/docker-compose.md)
* Product: **devops**
* GitHub Login: @erickson-doug
* Microsoft Alias: **dastahel**

**Comment by stevo-knievo** [comment]
An example would be awesome.

**Comment by phil-lgr** [comment]
@stevo-knievo 

here's how I do it, directly in Azure Web App for now:

![image](https://user-images.githubusercontent.com/9644867/49887079-5fc97880-fe09-11e8-89ba-b36ede5743b2.png)

it was simply easier than finding how to do it manually in Azure Pipelines... but I'd like to do it from my CI and not through the automated web hook on the Azure side.

**Comment by stevo-knievo** [comment]
Thanks @phil-lgr! Same here. I would like to use Azure Pipelines as well. I'm wondering how to replace the image tag in the docker-compose.yml file from the current build $(Build.BuildId) and keep the other image tags.

**Comment by phil-lgr** [comment]
I ended up doing it from a npm script

something like:

`"docker:tag:client:releasev": "cross-var docker tag $npm_package_config_docker_registry/$npm_package_name$npm_package_config_docker_client_image_name:$npm_package_version $npm_package_config_docker_registry/$npm_package_name$npm_package_config_docker_client_image_release:$npm_package_version",`

where the $npm_packge_* are npm env variable

**Comment by phil-lgr** [comment]
so I tag my images `latest` and also with the package.json version, and then I push both to the registry

**Comment by azooinmyluggage** [comment]
We are working on adding this feature. I will close the issue once the feature is live. Thanks again for the feedback.

**Comment by ceemafour** [comment]
Any update on when this feature will be available. I’d like to use it from pipelines and do manually in azure

**Comment by secbug** [comment]
Still waiting for this feature to be fleshed out. Actually using DevOps/Azure Pipelines is terrible due to this documentation being terrible.

**Comment by azooinmyluggage** [comment]
This feature has gone live now 
![image](https://user-images.githubusercontent.com/6857119/61689090-3334f200-ad44-11e9-9bf6-5c150af01cf2.png)
Please let us know if you have any feedback.

**Comment by ceemafour** [comment]
Is there an example document somewhere that explains how to use this feature from Azure Devops?
Your screen shot above doesn't provide any such details.

**Comment by andyhutch77** [comment]
> This feature has gone live now
> ![image](https://user-images.githubusercontent.com/6857119/61689090-3334f200-ad44-11e9-9bf6-5c150af01cf2.png)
> Please let us know if you have any feedback.

Hi @azooinmyluggage , nice one. 
This is exactly what I need.

Where is this feature? I can't seem to find it.

Regards

Andy

**Comment by andyhutch77** [comment]
> Is there an example document somewhere that explains how to use this feature from Azure Devops?
> Your screen shot above doesn't provide any such details.

@ceemafour It is available in a 'Azure Web App for Containers' task.
