### ISSUE TITLE
Exit status of a Task added in Build Pipeline

### ISSUE THREAD

**Issue by ravneetarora** [MicrosoftDocs/vsts-docs#2449]
I don't think that there is an option to get the Exit status of a particular task added in Build Pipeline.
For instance; i added task 1 and task 2 and task 3. Task 1 is success and task 2 is Failure. Task 3 is customized email task which will run even if the previous task has failed. I want to include the status of task1, task2 in the email body?

**Comment by steved0x** [comment]
I'm closing this issue since it is not associated with a topic. To continue the discussion, please open a new issue that is associated with a topic by browsing to the topic on docs.microsoft.com and choosing **Content feedback** at the bottom. Thank you for your feedback.
