### ISSUE TITLE
Missing content on page?

### ISSUE THREAD

**Issue by RubixRevenge** [MicrosoftDocs/vsts-docs#245]
"Stop and uninstall the service as explained above."

There is nothing above that to refer to.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 022dbf46-5ccf-ac17-f47a-7557b98bcbd6
* Version Independent ID: cfd090f9-4428-d4f9-224e-9e42805e08c0
* [Content](https://docs.microsoft.com/en-us/vsts/build-release/actions/agents/_shared/v2/remove-and-reconfigure-unix)
* [Content Source](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/build-release/actions/agents/_shared/v2/remove-and-reconfigure-unix.md)
* Service: unspecified

**Comment by steved0x** [comment]
@RubixRevenge Thank you for this feedback, I am assigning it to the author of the article for review.

@andyjlewis This feedback is on a shared file that is referenced in a few of your articles so I'm assigning this to you. Thank you.

**Comment by andyjlewis** [comment]
Yeah, this content is a shared file that is not intended to be shown on its own. These apparently began showing up as pages after we migrated to our new site. I've added an item to our backlog to investigate and fix.

**Comment by christopherbauer** [comment]
Any updates? We have a deploy target that mysteriously went offline and no instructions on how to redeploy the agent...

**Comment by andyjlewis** [comment]
Does one of the following help? 
- https://docs.microsoft.com/en-us/vsts/build-release/actions/agents/v2-windows
- https://docs.microsoft.com/en-us/vsts/build-release/actions/agents/v2-osx
- https://docs.microsoft.com/en-us/vsts/build-release/actions/agents/v2-linux
