### ISSUE TITLE
DevOps Update

### ISSUE THREAD

**Issue by mattquinn** [MicrosoftDocs/vsts-docs#2450]
The URL for the APIs changes with the move from VSTS to Azure DevOps.

The url goes from being
https://{orgname}.visualstudio.com/_apis/...
to
https://dev.azure.com/{orgname}/_apis/...

Technically I guess the listed example URL "https://{organization}/_apis/notification/DiagnosticLogs/{event ID}/entries?startTime={date}&endTime={date}" cover that whole thing as {organisation}, but it foxed me for a minute so might be worth an update / clarification around URL pattern for Azure DevOps?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e4db6b52-d81d-410a-6237-ce7371a0ceb8
* Version Independent ID: 15af6008-ddfc-0c30-cc3e-1e6e027c67c1
* Content: [How to use subscription logging - Azure DevOps Services & TFS](https://docs.microsoft.com/en-us/azure/devops/notifications/howto-use-subscription-logging?view=vsts)
* Content Source: [docs/notifications/howto-use-subscription-logging.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/notifications/howto-use-subscription-logging.md)
* Product: **devops**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Thanks @mattquinn I've created a work item on my backlog to address this. Thanks again.
