### ISSUE TITLE
VSTS feed as upstream for external registry

### ISSUE THREAD

**Issue by lflpowell** [MicrosoftDocs/vsts-docs#2452]
How can an external registry, such as Artifactory, set a VSTS feed as one of its upstreams. Is this possible - how does it have to be authenticated?

**Comment by jerickmsft** [comment]
To confirm, you're looking to pull packages from Azure DevOps via Artifactory? I think we've looked at the reverse, but not that direction.

@alexmullans to comment

**Comment by alexmullans** [comment]
You would need to set up a [remote repository](https://www.jfrog.com/confluence/display/RTF/Remote+Repositories) on Artifactory using the connection details from the Azure Artifacts "Connect to feed" dialog. I believe Artifactory takes username/password auth - you would use any value as the username and a [Personal Access Token](https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/use-personal-access-tokens-to-authenticate?view=vsts) as the password.

**Comment by lflpowell** [comment]
Yes that's exactly what we have tried - however we get a 400 Bad Request error each time.

**Comment by alexmullans** [comment]
Not sure then. Since this isn't really a docs issue, could I ask you to post it as a question on [StackOverflow](https://stackoverflow.com/questions/tagged/azure-artifacts)? I think you'll get more eyes (including more folks with Artifactory expertise) there.

**Comment by steved0x** [comment]
@lflpowell @alexmullans Since this isn't a docs issue, I'm closing this GitHub issue, and you can resume the conversation over at [StackOverflow](https://stackoverflow.com/questions/tagged/azure-artifacts)
