### ISSUE TITLE
artifact feeds

### ISSUE THREAD

**Issue by gaborbernat** [MicrosoftDocs/vsts-docs#2453]
Here I don't find it clear what's the artifact feed? The external feeds I assume is the pypi conenction endpoint, not?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 638243e7-cdd6-7573-aa6a-87c39da1bb3d
* Version Independent ID: d0046f56-ed26-7af2-3b8f-3dd5ab6ab892
* Content: [Publish packages to PyPI - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/targets/pypi?view=vsts&tabs=yaml)
* Content Source: [docs/pipelines/targets/pypi.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/targets/pypi.md)
* Product: **devops**
* GitHub Login: @erickson-doug
* Microsoft Alias: **elbatk**

**Comment by jerickmsft** [comment]
Hi! I've reached out to the folks on my team who can take a look.

**Comment by shubham90** [comment]
@gaborbernat Artifact feeds are relevant if you are using Azure artifacts to host your python packages/distributions. More on how to do that [here](https://docs.microsoft.com/en-us/azure/devops/artifacts/quickstarts/python-packages?view=vsts&tabs=new-nav). External feeds, as you said, can be any external connection endpoint. It can include pypi, feeds in other Azure DevOps organization etc.

**Comment by gaborbernat** [comment]
Yeah thought soo, but I think the documentation should be updated with this information to be more readable.

**Comment by alexmullans** [comment]
@elbatk seems like reasonable feedback to me. Can you add a note that `artifactFeed` is the name of one more more Azure Artifacts feeds and `externalFeeds` is the name of one or more "Python package upload"-typed service connections?

We should also document the two Python service connection types here: https://docs.microsoft.com/en-us/azure/devops/pipelines/library/service-endpoints?view=vsts#common-service-connection-types

**Comment by elbatk** [comment]
I've made those updates and the change should go in today, thanks everyone :)
