### ISSUE TITLE
Manual identity mapping

### ISSUE THREAD

**Issue by kszicsillag** [MicrosoftDocs/vsts-docs#2454]
Is it possible to provide the identity mapping between AAD and on-premise AD (e.g. by modifying IndentityMapLog) instead of generating it? We do not use Azure AD Connect.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a35b397-3fe8-122e-042e-280326f88a38
* Version Independent ID: 3e0f0afc-abeb-01be-d767-813cd6ad78db
* Content: [Migration import from TFS to Azure DevOps Services - Azure DevOps Services & TFS](https://docs.microsoft.com/en-us/azure/devops/articles/migration-import?view=vsts)
* Content Source: [docs/articles/migration-import.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/articles/migration-import.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by elbatk** [comment]
Hi @kszicsillag , reaching out for some reinforcements here :) @roofers

**Comment by roofers** [comment]
@kszicsillag - At this time you can't manually edit the identity map log. The import utilizes Azure AD Connect to map identities solely. You will have to either configure Azure AD Connect or a do a completely historical import.

**Comment by kszicsillag** [comment]
Thanks for the info. I am closing this.
