### ISSUE TITLE
Option to skip build

### ISSUE THREAD

**Issue by josesimoes** [MicrosoftDocs/vsts-docs#2456]
Even if I add `***NO_CI***` to the commit title or message a build is always triggered. Isn't this supposed to work on Azure Pipelines?

**Comment by DavidStaheli** [comment]
Hi @josesimoes.  Thanks for asking.  Are you trying this with a GitHub repository?  If so, this doesn't yet work for GitHub repositories, but we're adding the capability right now.

**Comment by josesimoes** [comment]
Yes that's from a GitHub repo. Please do add this, it's a must have!!

**Comment by brad-jones** [comment]
Also I believe the unwritten standard that other ci services honour is `[skip ci]`

https://docs.travis-ci.com/user/customizing-the-build/#skipping-a-build
https://circleci.com/docs/2.0/skip-build/
https://documentation.codeship.com/general/projects/skipping-builds/#skipping-via-commit-message

**Comment by DavidStaheli** [comment]
This has now been implemented:
https://docs.microsoft.com/en-us/azure/devops/release-notes/2019/sprint-148-update#skip-continuous-integration-ci-for-a-commit

**Comment by brad-jones** [comment]
@DavidStaheli has this actually been rolled out?

A commit from a Github repository made yesterday with the message `chore(release): update changelog [skip ci]` still ran in it's entirety.

The linked change log is dated Feb 25, hence my confusion. If it literally only rolled out 4 hours ago in line with your comment above I'll give it another try.

**Comment by DavidStaheli** [comment]
Hi @brad-jones.  Sorry for the confusion.  There is still 1 of our deployment rings that hasn't received the update yet.  That update is scheduled for tomorrow (Monday).  I suspect your Azure DevOps organization is in that largest, last ring.
