### ISSUE TITLE
Build.SourceVersionMessage show up as NULL in Azure Pipelines

### ISSUE THREAD

**Issue by josesimoes** [MicrosoftDocs/vsts-docs#2457]
Was trying to use a tag in our commit messages in order to skip a job using the condition to analyse the message, but the "expand expression" shows that this variable is always NULL.

**Comment by DavidStaheli** [comment]
Hi @josesimoes.  Thanks for reporting this, and apologies for the frustration.  Can you tell us whether you're using Azure Pipelines with a GitHub repository, Azure Repos, or other?

**Comment by josesimoes** [comment]
That's with a GitHub repo. I've ended up adding a new job to grab the message and pass that as the condition to the dependent ones. A bit more work but the initial requirement is meet.
Anyway looking forward to have this working as announced. 😉

**Comment by DavidStaheli** [comment]
Note: user story 1376169

**Comment by DavidStaheli** [comment]
Keep-alive

**Comment by davidstaheli** [comment]
This has been fixed.
