### ISSUE TITLE
Link to "new REST APIs" is broken

### ISSUE THREAD

**Issue by dagood** [MicrosoftDocs/vsts-docs#2459]
The link in this line is broken, a 404:

> * Access both traditional client object model APIs and [new REST APIs](https://docs.microsoft.com/rest/api/vsts)

Regression of https://github.com/MicrosoftDocs/vsts-docs/issues/1874?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 413163f0-28c3-a2a7-d626-fcb81bcb2257
* Version Independent ID: 57c127da-2b1e-d29e-9abb-a3c258762ccf
* Content: [.NET Client Libraries for Azure DevOps Services (and TFS)](https://docs.microsoft.com/en-us/azure/devops/integrate/concepts/dotnet-client-libraries?view=vsts)
* Content Source: [docs/integrate/concepts/dotnet-client-libraries.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/integrate/concepts/dotnet-client-libraries.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by dagood** [comment]
The link works now as-is. I guess the site was just down for a bit, or something like that.

**Comment by elbatk** [comment]
@dagood We changed our URL from: https://docs.microsoft.com/en-us/rest/api/vsts/?view=azure-devops-rest-4.1 to https://docs.microsoft.com/en-us/rest/api/azure/devops/?view=azure-devops-rest-4.1, we just had to set up a redirect!
