### ISSUE TITLE
Don't suggest to revert merged pull requests

### ISSUE THREAD

**Issue by agr** [MicrosoftDocs/vsts-docs#246]
The documentation of this level should not casually suggest to revert merged pull requests without going into details about the can of worms it opens.
The typical scenario for reverting a pull request would be that someone merged something that was not yet ready to be merged, but would be ready after few iterations of fixes. In that case reverting the merge commit would look like it worked fine initially (the repo file layout/content was returned to pre-merge state), but would cause merge issues later (specifically, attempting to repeat the reverted pull request would result in "There are no changes to merge between the selected branches." although clearly branches have differences between them). Nothing mentions that. It would cause huge confusion for the unsuspecting user (especially, if they are not very familiar with git).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 028e7b61-62e4-a10e-e420-3535f7843f0e
* Version Independent ID: 1a6fdbe7-5ba4-a7f8-1b2e-271289a7b9fd
* [Content](https://docs.microsoft.com/en-us/vsts/git/pull-requests#revert-a-pull-request)
* [Content Source](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/git/pull-requests.md)
* Service: unspecified

**Comment by steved0x** [comment]
@agr Sorry for the delay in responding to this, we just implemented a new feedback control that files customer feedback as GitHub issues (which I really like) but as a result we started off with a bit of a backlog. I've added this to our documentation backlog and I'll get our PR documentation updated. Thank you.
