### ISSUE TITLE
Error in PowerShell Sample

### ISSUE THREAD

**Issue by clement-cunin** [MicrosoftDocs/vsts-docs#2464]
The first line of first example in Powershell section should be "powershell: echo Hello $(name)" instead of "script: echo Hello $(name)"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7458d5b2-1bb7-7d87-7ce6-2b0c430b0155
* Version Independent ID: edf5bbd3-a3f0-5426-e985-31290f8afd05
* Content: [YAML schema - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=vsts&tabs=example)
* Content Source: [docs/pipelines/yaml-schema.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/yaml-schema.md)
* Product: **devops**
* GitHub Login: @erickson-doug
* Microsoft Alias: **macoope**

**Comment by DavidStaheli** [comment]
Thanks a lot for bringing this to our attention, @clement-cunin!  I've applied the fix and it should be live later today or Monday.
