### ISSUE TITLE
Does the @mention feature work for external users?

### ISSUE THREAD

**Issue by PeterHamiltonTO** [MicrosoftDocs/vsts-docs#2465]
In our tenant, the @mention feature works great for internal users, but is not working for our external users.  Is there something we can do to provide external users the @mention functionality?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 34ae521f-6ae4-4d7f-2cce-f844e5811b66
* Version Independent ID: 18098490-1f34-e966-3135-cb90197bfa6f
* Content: [Use @mentions in work items and pull requests - Azure DevOps Services & TFS](https://docs.microsoft.com/en-us/azure/devops/notifications/at-mentions?view=vsts#feedback)
* Content Source: [docs/notifications/at-mentions.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/notifications/at-mentions.md)
* Product: **devops**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
@PeterHamiltonTO No, the @mention feature shouldn't work for external users - users who aren't part of the project or organization. Please let me know if you have further questions. Thank you.

**Comment by PeterHamiltonTO** [comment]
Thanks.  The external users are invited to our organization.  This was
actually a permissions issue, and I added the users to the 'Contributors'
security group, and they could then use the @mention command.

**Comment by griosha** [comment]
External user as contributor in security group, but still user couldn't able to @mention in the discussion. we have tried to give PCA rights as well, but still issue persists. Please advice on this

**Comment by chcomley** [comment]
@griosha, I am sorry you're experiencing issues with this. @roofers, can you please provide some clarity on this? Thanks very much!

**Comment by chcomley** [comment]
@griosha, Can you please [create a support ticket](https://azure.microsoft.com/en-us/support/devops/)? They'll be happy to assist you. I'll be closing this issue, but do let us know if you have any other questions. Thank you.
