### ISSUE TITLE
Triggering pipeline in a different project

### ISSUE THREAD

**Issue by phatcher** [MicrosoftDocs/vsts-docs#2466]
Is it possible to trigger a pipeline in a different project, scenario is that we have a library project and after that successfully builds I need to trigger one or more other projects builds to update the library dependencies

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d9e313c5-9120-9172-bc27-c21d10fcd5ae
* Version Independent ID: 1a837182-591f-3cbc-1632-7b50d857b13c
* Content: [Release triggers for stages, branches, and pipelines - Azure Pipelines & TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/triggers?view=vsts)
* Content Source: [docs/pipelines/release/triggers.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/release/triggers.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment]
Thank you for your feedback. I will pass this on to the product team and update the topic based on their response.

**Comment by RoopeshNair** [comment]
Not out-of-the-box, however, user can add custom step in the build pipeline to trigger other pipelines using REST apis

**Comment by phatcher** [comment]
@RoopeshNair  Can we have an example please, e.g. where do we get the PAT to pass etc
