### ISSUE TITLE
Build agents

### ISSUE THREAD

**Issue by fleed** [MicrosoftDocs/vsts-docs#2467]
What's the suggested method for build agents?
I'm using the PAT method, but it often fails with 401 error. It looks a little bit like an intermittent error, but it's really annoying.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab0a3735-a9b0-2ed7-f08f-5321f55f8c90
* Version Independent ID: 2153f6c0-def7-eed1-286d-5e61c9fcbec4
* Content: [Use NuGet with Azure DevOps Services feeds](https://docs.microsoft.com/en-us/azure/devops/artifacts/nuget/nuget-exe?view=vsts&tabs=new-nav)
* Content Source: [docs/artifacts/nuget/nuget-exe.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/artifacts/nuget/nuget-exe.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by elbatk** [comment]
Hi @fleed ! Adding @alexmullans here to help you out :)

**Comment by fleed** [comment]
Thank you @elbatk.
@alexmullans the build is now working again without any change required (I didn't change the PAT, the build, not even a new commit).
It seems that this is an intermittent problem on Azure Artifacts. Is there a better repository where I should report the issue?

**Comment by elbatk** [comment]
Hi @fleed! We have seen some other issues with intermittent 401s. I think the best place to report an issue will be the [Azure DevOps Services Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html) as this is more for docs-related inquiries. I'll go ahead and close this one here and hopefully you can get some traction in there, this problem should be addressed!
