### ISSUE TITLE
Integrating Azure DevOps in Slack

### ISSUE THREAD

**Issue by sitetriks** [MicrosoftDocs/vsts-docs#2468]
There is no description of whether the slack that is being used in the images above is the paid or the free version.
Currently, at least in the drop-down menu in slack (Slack's free version), there is only "Apps" button i/o "Apps & Integrations". Thus, your example is either outdated as Slack's menu had changed or it only implies to a paid version of Slack.

Please, do let us know which of the two statements is the correct one.
Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7fd5671b-b7b8-9acb-c195-7897fec3538b
* Version Independent ID: ff894c1b-f2f7-581d-94b4-dbc77d80ad6d
* Content: [Slack with Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/service-hooks/services/slack?view=vsts)
* Content Source: [docs/service-hooks/services/slack.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/service-hooks/services/slack.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by elbatk** [comment]
@roofers I've seen more than one question about this for this article, could you shine some light here and let me know if I need to make an update?

**Comment by roofers** [comment]
@sitetriks - I just check my for free Slack account and I can access the apps menu. It looks like Slack moved it around though. You need to go to "Administration" -> "Manage apps". 

@elbatk - We need to update that initial screenshot to show the new menu layout.

**Comment by elbatk** [comment]
These docs are getting a massive overhaul currently, I'll make sure this screenshot gets updated :)

**Comment by indolentdeveloper** [comment]
yes there is not apps and integration in slack. only apps. Also in market place cant find azure devops
