### ISSUE TITLE
Need example of sending JSON object in body

### ISSUE THREAD

**Issue by cnayan** [MicrosoftDocs/vsts-docs#247]
Like HTTP Headers, we also need a mechanism to place body content before POST call is generated. Can that be facilitated please?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4806b641-fdb1-c0e9-081c-c007807c7cdb
* Version Independent ID: f59d8501-1285-be79-b084-8371ed8395bb
* [Content](https://docs.microsoft.com/en-us/vsts/service-hooks/services/webhooks)
* [Content Source](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/service-hooks/services/webhooks.md)
* Service: unspecified

**Comment by EltonAlvess** [comment]
Any new about it?

**Comment by elbatk** [comment]
Hi @cnayan and @EltonAlvess , sorry for the embarrassingly long time to reply here. I've reached out to the product team and I'll let you know what they say!

**Comment by evanmcneal** [comment]
Any updates on this?

**Comment by elbatk** [comment]
Adding @roofers to help out here as he looks over the Service Hooks area.

**Comment by evanmcneal** [comment]
It looks like the default payload with the fabrikam git info is being sent to my webhook in Azure Automation, instead of the information I selected from the dropdown, at least specifically to the code pushed trigger.

**Comment by elbatk** [comment]
I know some people are waiting on updates here. I think the best place to ask product-based questions are on the [Azure DevOps Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html), which is actively monitored by the product team. I'm going to close this as a docs issue, but if something comes out from the ticket, please reach out and I'll update the doc!
