### ISSUE TITLE
How would these instructions apply when using YAML in a Pull Request build policy?

### ISSUE THREAD

**Issue by odelljl** [MicrosoftDocs/vsts-docs#2473]
Based on the recommendation here for authorizing a YAML pipeline … does this mean I cannot use a YAML build in a Pull Request policy?  The pull request creates a new branch each time and it fails authorization.

**Comment by steved0x** [comment]
@odelljl Thank you for the feedback. Can you let me know which article this feedback is for (where you mean by `here` in your line above), so I can assign it to the author? You can reply here with the URL of the topic, or you can create a new issue by browsing to the topic on docs.microsoft.com and choosing **Content feedback** at the bottom. 

![image](https://user-images.githubusercontent.com/1580889/42953695-fd174150-8b48-11e8-94de-26924ca79c71.png)

**Comment by steved0x** [comment]
I'm closing this issue since it is not associated with a topic. To continue the discussion, please open a new issue that is associated with a topic by browsing to the topic on docs.microsoft.com and choosing **Content feedback** at the bottom. Thank you for your feedback.
