### ISSUE TITLE
Invalid link 

### ISSUE THREAD

**Issue by skeeler** [MicrosoftDocs/vsts-docs#2481]
The link under "grant you permissions" in the "Create an inherited process" section is incorrect. Currently it points to "https://docs.microsoft.com/en-us/azure/devops/organizations/security/set-permissions-access-work-tracking?view=vsts#process-permissions", but the element id is wrong for the target page. Looking at the target page, this link should probably be pointing to: "https://docs.microsoft.com/en-us/azure/devops/organizations/security/set-permissions-access-work-tracking?view=vsts&tabs=new-nav#customize-an-inherited-process".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5969861-6f6b-3da1-7eb3-2ee278110937
* Version Independent ID: ae1c687d-7c93-ba01-f63c-2f1df95ed873
* Content: [Create and manage an inherited process - Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/organizations/settings/work/manage-process?view=vsts&tabs=new-nav#create-an-inherited-process)
* Content Source: [docs/organizations/settings/work/manage-process.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/settings/work/manage-process.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@skeeler - Thank you for the feedback. You are correct. I have updated the link to point to this article: https://docs.microsoft.com/en-us/azure/devops/organizations/security/set-project-collection-level-permissions?view=vsts&tabs=new-nav#add-a-group-and-change-its-permissions-at-the-organization-or-collection-level-group.
