### ISSUE TITLE
Does it support regex for condition in task of yml

### ISSUE THREAD

**Issue by neil-yechenwei** [MicrosoftDocs/vsts-docs#2484]
Does it support regex in condition like below sample code？

- powershell: |
             echo $(BUILD.SOURCEBRANCH)
        condition: and(succeeded(), eq(variables['build.sourceBranch'], "^refs/tags/v?[0-9]+\.[0-9]+\.[0-9]+$"))
        displayName: "PowerShell Script"

**Comment by steved0x** [comment]
@neil-yechenwei Thank you for the feedback. Can you let me know which article this feedback is for, so I can assign it to the author? You can reply here with the URL of the topic, or you can create a new issue by browsing to the topic on docs.microsoft.com and choosing **Content feedback** at the bottom. 

![image](https://user-images.githubusercontent.com/1580889/42953695-fd174150-8b48-11e8-94de-26924ca79c71.png)

**Comment by steved0x** [comment]
I'm closing this issue since it is not associated with a topic. To continue the discussion, please open a new issue that is associated with a topic by browsing to the topic on docs.microsoft.com and choosing **Content feedback** at the bottom. Thank you for your feedback.
