### ISSUE TITLE
Page Title in HTML has a misspelling

### ISSUE THREAD

**Issue by thekwilson** [MicrosoftDocs/vsts-docs#2487]
The title meta property has a misspelling for the world How.   (see below)

&lt;meta property="og:title" content="Hos are security and identity managed? - Azure DevOps & TFS" /&gt;

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 851595a3-32b8-c0e4-ff4f-aa84cf436175
* Version Independent ID: c2cb9c6c-de29-a7a9-9728-fbbc1d223a4f
* Content: [Hos are security and identity managed? - Azure DevOps & TFS](https://docs.microsoft.com/en-us/azure/devops/organizations/security/about-security-identity?view=vsts)
* Content Source: [docs/organizations/security/about-security-identity.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/security/about-security-identity.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@thekwilson - Thank you for the correction. I'm updating the article.
