### ISSUE TITLE
Work Item Count - This is not a default option 

### ISSUE THREAD

**Issue by jasonpadman** [MicrosoftDocs/vsts-docs#2489]
The "Work Item Count" referenced in this article is not created by default which makes this article confusing

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c9bc092b-7e31-59c0-148c-6dd2508a9c25
* Version Independent ID: db29bd31-fa3f-b959-0ae7-40213bbfeda9
* Content: [Example reports for Power BI Data Connector - Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/report/powerbi/data-connector-examples?view=vsts)
* Content Source: [docs/report/powerbi/data-connector-examples.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/report/powerbi/data-connector-examples.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@jasonpadman - Thank you for the feedback and sorry for the delayed response. You are correct that the article is out of date. I have created an item to either update or retire the article. For now, I'd direct you to this topic, https://docs.microsoft.com/en-us/azure/devops/report/powerbi/active-bugs-sample-report?view=vsts&tabs=new-nav#create-a-card-for-latest-bug-count, which outlines how to get the Work Item Count.
