### ISSUE TITLE
Creating yml build definitions

### ISSUE THREAD

**Issue by scottnasello** [MicrosoftDocs/vsts-docs#249]
Hello,

you provide 2 methods for creating yml build definitions:
1) automagically
2) manually via the gui

Suppose you need to create a yml build in a place other than the root (so you can't take advantage of the automatic method), do you have any documentation on creating a yml build definition programmatically? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 87686bea-7c46-cd47-d1a9-128e16b63a23
* Version Independent ID: ace78317-e562-e35d-781d-23cd7d2dfff2
* [Content](https://docs.microsoft.com/en-us/vsts/build-release/actions/build-yaml)
* [Content Source](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/build-release/actions/build-yaml.md)
* Service: unspecified

**Comment by andyjlewis** [comment]
Hi scottnasello, thanks for the question. I'll follow up with the product team and get back to you.

**Comment by andyjlewis** [comment]
Hi scottnasello, we aren't offering alternative paths to automatic build definitions at the moment, but check out this discussion: https://github.com/Microsoft/vsts-agent/pull/1430
