### ISSUE TITLE
If you follow the instructions you will run into a TSC compilation error

### ISSUE THREAD

**Issue by hoffiz** [MicrosoftDocs/vsts-docs#2490]
To fix the error I removed npm install vss-web-extension-sdk from my dependencies. Since I'm doing very simple tasks I don't think I need it yet. The error manifests the following way: 

```
node_modules/@types/node/index.d.ts:7686:5 - error TS2300: Duplicate identifier 'mod'.

7686     export = NodeJS.Module;
         ~~~~~~~~~~~~~~~~~~~~~~~

  node_modules/@types/requirejs/index.d.ts:38:11
    38  export = mod;
                 ~~~
    'mod' was also declared here.

node_modules/@types/requirejs/index.d.ts:38:11 - error TS2300: Duplicate identifier 'mod'.

38  export = mod;
             ~~~

  node_modules/@types/node/index.d.ts:7686:5
    7686     export = NodeJS.Module;
             ~~~~~~~~~~~~~~~~~~~~~~~
    'mod' was also declared here.

node_modules/@types/requirejs/index.d.ts:422:13 - error TS2403: Subsequent variable declarations must have the same type.  Variable 'require' must be of type 'NodeRequire', but here has type 'Require'.

422 declare var require: Require;
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 44581f4a-93df-7507-3844-eadedf9a6cc4
* Version Independent ID: 33c7bcf0-1512-975f-5ef8-9f2a192a84ad
* Content: [Add a Build or Release Task](https://docs.microsoft.com/en-us/azure/devops/extend/develop/add-build-task?view=vsts)
* Content Source: [docs/extend/develop/add-build-task.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/extend/develop/add-build-task.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by elbatk** [comment]
Adding @vtbassmatt to take a look at this for us :) Thanks @hoffiz !

**Comment by damccorm** [comment]
Looks like installing vss-web-extension-sdk is not actually necessary or desirable, adding a PR for this.
