### ISSUE TITLE
Where to find my build Artifact ?!

### ISSUE THREAD

**Issue by olileger** [MicrosoftDocs/vsts-docs#2491]
Regarding the "Publish Artifact" job / "Artifact publish location" field it says in this documentation : "Artifact publish location: Azure Artifacts/TFS" so I tried to retrieve my build artifact within Azure Artifacts... without any success.
I discover that on my task the location is called "Azure Pipelines/TFS" which is different from Azure Artifacts.
Is it possible to add clarification please ?
Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c028a99-45f1-3609-3219-89789dc6b966
* Version Independent ID: f626f40e-1bab-4d8a-cd19-ab3b5da4be0a
* Content: [Artifacts in Azure Pipelines - Azure Pipelines & TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/artifacts?view=vsts)
* Content Source: [docs/pipelines/build/artifacts.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/build/artifacts.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by elbatk** [comment]
hi @olileger , we could probably clarify this a bit better. If you chose "Azure Artifacts/TFS" as your publish location, you can find your artifacts in your completed build. If you go to Azure Pipelines and select the build definition and find the completed build, you will see them: 
![image](https://user-images.githubusercontent.com/19390261/48722580-58d88d00-ebf2-11e8-8014-79ffe0b0f7f5.png)

**Comment by olileger** [comment]
In fact @elbatk it just suggest "Azure Pipelines / TFS" and not "Azure Artifacts / TFS".
It's crystal clear from the application I'm publishing the artifact to the pipeline.
What was unclear to me was your typo "Azure Artifacts / TFS" driving me on a wrong way (was thinking about retrieving my artifact on Azure Artifact due to wearing the same name...)

**Comment by elbatk** [comment]
Ah, yes, I see now that in the product it says Azure Pipelines. So the product is clear but the docs are wrong, I'll get that fixed!

**Comment by elbatk** [comment]
Closing this as I have a fix incoming!
