### ISSUE TITLE
Warning firing on this task

### ISSUE THREAD

**Issue by cjfarrelly** [MicrosoftDocs/vsts-docs#2492]
Hi,

We have started seeing the following warning on this task, tested on both private and hosted rigs.

##[warning]The names of some imported commands from the module 'ServiceFabricHelpers' include unapproved verbs that might make them less discoverable. To find the commands with unapproved verbs, run the Import-Module command again with the Verbose parameter. For a list of approved verbs, type Get-Verb.

Thanks,

Colin.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7068e469-201e-c820-4d27-b798ea799b70
* Version Independent ID: d6bb717a-1c44-43a1-c7a5-9616b257c0e0
* Content: [Service Fabric Application Deployment task - Azure Pipelines & TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/service-fabric-deploy?view=vsts)
* Content Source: [docs/pipelines/tasks/deploy/service-fabric-deploy.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/deploy/service-fabric-deploy.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment]
Thank you for your feedback. I have passed this on to the product team for advice.

**Comment by bwolohan** [comment]
Any updates on this? I'm getting it while following the steps in https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-tutorial-deploy-app-with-cicd-vsts. I'm using the Hosted VS2017 agent and deploying to my own cluster.

TIA,
Bill

**Comment by bwolohan** [comment]
After getting this warning I get an unspecified error. Is this related? How can I get more details on the error?

2019-01-02T17:46:12.2632215Z Service fabric SDK version: 3.2.176.9494.
2019-01-02T17:46:12.9030523Z ##[error]One or more errors occurred.

**Comment by stofte** [comment]
https://github.com/Microsoft/azure-pipelines-tasks/pull/9413

**Comment by bishal-pdMSFT** [comment]
Fixed with microsoft/azure-pipelines-tasks#9413

**Comment by mijacobs** [comment]
It looks like you've encountered an issue with the product itself, rather than an issue with the documentation. If this issue hasn't been fixed yet, to make sure it gets in front of the right people, please [submit your bug]( https://developercommunity.visualstudio.com/content/problem/post.html?space=21).
