### ISSUE TITLE
Issues with implmentation

### ISSUE THREAD

**Issue by shehackspurple** [MicrosoftDocs/vsts-docs#2494]
Hi!

I made a video of me trying to install Rosyl and failing.  Can we connect so we can talk about which steps may have changed a bit and update this article?  :) . Message me here or my MSFT email.

Tanya

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 31e62447-f971-a085-7ded-442a363f31e7
* Version Independent ID: 5c650019-951f-b103-3010-bfee05b99acc
* Content: [Add Continuous Security Validation to your CICD Pipeline](https://docs.microsoft.com/en-us/azure/devops/articles/security-validation-cicd-pipeline?view=vsts&WT.mc_id=MSIgniteTheTour-MSIgniteTheTour-tajanca)
* Content Source: [docs/articles/security-validation-cicd-pipeline.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/articles/security-validation-cicd-pipeline.md)
* Product: **devops**
* GitHub Login: @mikedouglasdev
* Microsoft Alias: **douge**

**Comment by mikedouglasdev** [comment]
Hi Tanya,

So you are having issues trying to install the Roslyn analyzers?  I looked back through my notes and here is what I documented from a year ago.  I don't have your MSFT email but you can email at mikedouglas  **** at **** deliveron  dot  com.  If this doesn't work, I can look at doing it again.

![image](https://user-images.githubusercontent.com/9584557/48735531-49673d00-ec0e-11e8-986e-319d50b71c23.png)
