### ISSUE TITLE
dotnet test VSTS task: Allow specification of Publish Test Run name.

### ISSUE THREAD

**Issue by saikrishnav** [MicrosoftDocs/vsts-docs#2497]
Currently, if I use "dotnet" task to do "dotnet test" and select "Publish Test Results" option, it publishes the run as "VSTest Test Run" or something as default. Since we run different tests using different tasks and phases in the same run, we need to be able to specify "Test Run Title" or Name that gets published as.

**Comment by PBoraMSFT** [comment]
@saikrishnav - this is not a doc issue, but an ask on the task itself. Can you please log an issue on the [tasks repo](https://github.com/Microsoft/azure-pipelines-tasks), so we can track it there? 
I am closing this one out.
