### ISSUE TITLE
Difference in categories across TFS and VSTS

### ISSUE THREAD

**Issue by knowds** [MicrosoftDocs/vsts-docs#2499]
The doc mentions using Azure Pipelines for VSTS custom build tasks and Build and Release category for on-prem . Does this imply, that from now on we cannot have a single extension to cater to both VSTS and TFS since the vss-extension.json file will be different ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d8b703fe-8982-4284-6db0-ef33abac08a4
* Version Independent ID: 0fc84d11-1c32-0a49-04ec-641b68f44886
* Content: [Extension Manifest Reference](https://docs.microsoft.com/en-us/azure/devops/extend/develop/manifest?view=vsts#required-attributes)
* Content Source: [docs/extend/develop/manifest.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/extend/develop/manifest.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by elbatk** [comment]
Hi @knowds , that is a good question. I'll clear this up in the docs, but the older values (like Build and Release) actually are mapped to the newer values, so if you're wanting to target both, you should use Build and Release, and it should map to Azure Pipelines in the hosted version (Azure DevOps Services). 

I'll update the docs to say this :)

**Comment by knowds** [comment]
@elbatk , the values are not getting mapped and I see below error while uploading to Azure Dev Ops:
Upload Error

The stated category 'Build and Release' is no longer supported. Refer to the categories listed at https://aka.ms/extensioncategories and republish using one or more amongst them.
