### ISSUE TITLE
Doesn't always work

### ISSUE THREAD

**Issue by Leon99** [MicrosoftDocs/vsts-docs#2500]
&gt; In Azure Pipelines, use the .NET Core step's restore command, which automatically handles authentication to Azure Artifacts feeds. 

works on one of my machines, but ends with 401 on another. There must be some additional configuration needed.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a1a158fb-d1e3-a0d9-492e-3f78dde5d97c
* Version Independent ID: 71055426-3ba1-27f3-11db-cadb688ae123
* Content: [Use dotnet with Azure Artifacts feeds](https://docs.microsoft.com/en-au/azure/devops/artifacts/nuget/dotnet-exe?view=vsts)
* Content Source: [docs/artifacts/nuget/dotnet-exe.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/artifacts/nuget/dotnet-exe.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by elbatk** [comment]
Hi @Leon99 , thanks for reaching out. Just making sure you checked the Q&A below and that scenario doesn't affect you. It sounds like yours is machine specific so it's probably not that. Adding @alexmullans to help out :)

**Comment by alexmullans** [comment]
Not sure I understand. The quote you selected is about Azure Pipelines (i.e. automated builds), but you wrote "works on one of my machines" - did you mean an individual machine, or one of the machines in your private agent pool? 

This question is probably better suited for [StackOverflow](https://stackoverflow.com/questions/tagged/azure-artifacts).

**Comment by Leon99** [comment]
One of the machines in my private agent pool.

**Comment by alexmullans** [comment]
OK, thanks. Can you post your logs on [Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html)?

**Comment by Leon99** [comment]
@alexmullans I did open a ticket there as you suggested (https://developercommunity.visualstudio.com/content/problem/386927/dotnet-restore-fails-on-authenticating-to-a-vsts-n.html), but it hasn't been particularly helpful so far. While there definitely seems to be a problem with the latest ver. of dotnet tool, I believe it would help if this page had a better explanation of the "automatic" authentication mechanism. Another thing I've just realized - this automatic authentication that is meant to work in Azure Pipelines, does it apply to private agents or hosted ones only?

**Comment by Leon99** [comment]
Update: using Azure Artifacts Credential Provider plus VSS_NUGET_EXTERNAL_FEED_ENDPOINTS didn't work either.

**Comment by yannlebel** [comment]
Hello,
I have the same issue with two self hosted agent: one with windows 10 another with Ubuntu16.04 running the version 2.141.1 of the Azure DevOps agent.
The commands `dotnet restore` and `dotnet nuget push` fails with 401. 

Here is an extract of my CI yml file for the restore command
```
- task: DotNetCoreCLI@2
  displayName: Restore
  inputs:
    command: restore
    projects: '**/*.csproj'
    feedsToUse: config
    nugetConfigPath: NuGet.config
```

And the push command
```
- task: DotNetCoreCLI@2
  displayName: Publish
  inputs:
    command: push
    packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
    publishVstsFeed: 'MY_FEED_ID'
```

My NuGet.config file is simple as well just the feed URL in it
```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <clear />
    <add key="A.G.E Feed" value="https://####.visualstudio.com/_packaging/###/nuget/v3/index.json" protocolVersion="3" />
  </packageSources>
</configuration>
```

The ouput of `dotnet --info` on the windows agent (linux agent is using the same version)

> .NET Core SDK (reflecting any global.json):
>  Version:   2.1.500
>  Commit:    b68b931422
> 
> Runtime Environment:
>  OS Name:     Windows
>  OS Version:  10.0.16299
>  OS Platform: Windows
>  RID:         win10-x64
>  Base Path:   C:\Program Files\dotnet\sdk\2.1.500\
> 
> Host (useful for support):
>   Version: 2.1.6
>   Commit:  3f4f8eebd8
> 
> .NET Core SDKs installed:
>   2.0.3 [C:\Program Files\dotnet\sdk]
>   2.1.2 [C:\Program Files\dotnet\sdk]
>   2.1.4 [C:\Program Files\dotnet\sdk]
>   2.1.100 [C:\Program Files\dotnet\sdk]
>   2.1.103 [C:\Program Files\dotnet\sdk]
>   2.1.104 [C:\Program Files\dotnet\sdk]
>   2.1.200 [C:\Program Files\dotnet\sdk]
>   2.1.201 [C:\Program Files\dotnet\sdk]
>   2.1.202 [C:\Program Files\dotnet\sdk]
>   2.1.300 [C:\Program Files\dotnet\sdk]
>   2.1.302 [C:\Program Files\dotnet\sdk]
>   2.1.400 [C:\Program Files\dotnet\sdk]
>   2.1.402 [C:\Program Files\dotnet\sdk]
>   2.1.500 [C:\Program Files\dotnet\sdk]
> 
> .NET Core runtimes installed:
>   Microsoft.AspNetCore.All 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
>   Microsoft.AspNetCore.All 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
>   Microsoft.AspNetCore.All 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
>   Microsoft.AspNetCore.All 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
>   Microsoft.AspNetCore.App 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.NETCore.App 2.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 2.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 2.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 2.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

Sometimes it is also possible to get the `dotnet restore` command to work and in the same build the `dotnet nuget push` command fails with 401

**Comment by magols** [comment]
We have the same problem with our private agents. Last week they just stopped working and started giving us the 401. Using the dotnet restore task and a Azure Artifact Feed.

**Comment by elbatk** [comment]
Just wanted to remind everyone to post product issues on the [Azure DevOps Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html), which is monitored actively by the product team, as this forum is for documentation issues so you may not get the help you're looking for! (At least not as fast)

**Comment by elbatk** [comment]
It's been a while for this one, but I'm going to close it as a docs issue. The Azure DevOps Developer Community above would be the best place to get answers for this. If you find that there should be a docs change, feel free to reach back out!
