### ISSUE TITLE
Merge conflict in article

### ISSUE THREAD

**Issue by nschonni** [MicrosoftDocs/vsts-docs#2503]
There is a `&lt;&lt;&lt;&lt;&lt;&lt;&lt;` right at the start of this article

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ff0c895d-9660-6db7-676e-5aa194b403e8
* Version Independent ID: 5c14f6ec-f4b5-26dc-aaf2-d8fc445036b5
* Content: [What's new for Azure DevOps Server and Team Foundation Server](https://docs.microsoft.com/en-us/tfs/server/whats-new#feedback)
* Content Source: [https://mseng.visualstudio.com/DefaultCollection/TechnicalContent/_git/tfs-docs-pr?path=%2fdocs%2fserver%2fwhats-new.md&version=GBlive&_a=contents](https://mseng.visualstudio.com/DefaultCollection/TechnicalContent/_git/tfs-docs-pr?path=%2fdocs%2fserver%2fwhats-new.md&version=GBlive&_a=contents)
* Product: **devops-server**
* Git Login: **elbatk**
* Microsoft Alias: **elbatk**

**Comment by elbatk** [comment]
hi @nschonni , yeah this was a bad merge and I believe it's been fixed since, thank you!
