### ISSUE TITLE
Convert from visual designer to YAML

### ISSUE THREAD

**Issue by MisinformedDNA** [MicrosoftDocs/vsts-docs#2504]
I've been working with the visual designer for some time, but I read that we are encouraged to move to YAML. Is there a way to easily convert from visual designer to YAML?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f94a6e7d-3cb5-790c-2b8b-c09abd1de3f6
* Version Independent ID: a0d381e1-07ad-9191-4697-6faf600a7bd8
* Content: [Use Azure Pipelines - Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/pipelines/get-started/pipelines-get-started?toc=/azure/devops/pipelines/toc.json&bc=/azure/devops/boards/pipelines/breadcrumb/toc.json&view=vsts)
* Content Source: [docs/pipelines/get-started/pipelines-get-started.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/get-started/pipelines-get-started.md)
* Product: **devops**
* GitHub Login: @erickson-doug
* Microsoft Alias: **douge**

**Comment by RolfEleveld** [comment]
Export the yaml from the visual designer using view yaml (on the far right of the edit screen) copy the yaml and then paste that into a new file in the root of the git repository with name azure-pipeline.yml

**Comment by renenadorp** [comment]
Is it also possible to convert release-pipelines, initially developed using the visual designer, to yaml, and keep this separate from the build-pipeline?
Regards,
R.

**Comment by andyjlewis** [comment]
You can deploy from a YAML pipeline; some of our docs show examples of this. However, YAML pipelines don't have stages or approvals.

**Comment by vtbassmatt** [comment]
For designer builds, the "view YAML" button is the best bet.

As Andy said, we aren't quite there on feature parity for designer releases.

**Comment by yannduran** [comment]
@RolfEleveld , @vtbassmatt 

Does anyone know where the "View YAML" button went? I can't see it on the far right of the edit screen, or anywhere else for that matter.

**Comment by RolfEleveld** [comment]
@yannduran, open edit on the visual flow and now for each step, select the step and you can see yam button right top.

**Comment by yannduran** [comment]
@RolfEleveld, oh I see. You only see the YAML step-by-step, not for the whole pipeline. Thanks!

I was expecting something that allowed you to see the YAML for the whole pipeline. I mean you can export a whole pipeline to JSON, so it'd seem reasonable to expect that you could also see/export it to YAML, especially with the emphasis that's being placed on YAML now.

**Comment by vtbassmatt** [comment]
It's available at the Job level.

**Comment by f2calv** [comment]
FYI soon will be possible to export an entire pipeline as YAML;
- https://devblogs.microsoft.com/devops/replacing-view-yaml/
