### ISSUE TITLE
Related Articles are broken

### ISSUE THREAD

**Issue by kylejrp** [MicrosoftDocs/vsts-docs#2505]
The links to the related articles are broken

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f7cfd41-1c04-00ef-2aeb-6bb4a5c7ab3e
* Version Independent ID: 816dfa4b-7387-da69-cd0f-aeeef951c164
* Content: [Invite external users to Azure DevOps - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/invite-outside-users?view=vsts)
* Content Source: [docs/organizations/accounts/invite-outside-users.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/accounts/invite-outside-users.md)
* Product: **devops**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
@kylejrp Thank you so much for letting us know. I've fixed the links, which should be live by this afternoon.  Thanks again.
