### ISSUE TITLE
How one generates the Api Key for the nuget push to the feed?

### ISSUE THREAD

**Issue by EM1L** [MicrosoftDocs/vsts-docs#251]
This is VSTS question really - I can not figure out how to get an API Key for the package feed...
It would be helpful if this is covered too!

Thanks,
Emil

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a10a409-5468-9532-f0dc-5a28cdd566d8
* Version Independent ID: 2ef20266-bc45-448b-27f5-e5c3bffed2ef
* [Content](https://docs.microsoft.com/en-us/vsts/package/get-started-nuget)
* [Content Source](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/package/get-started-nuget.md)
* Service: unspecified

**Comment by EM1L** [comment]
It appears - I can use PAT for the APIKey...

**Comment by VinKamat** [comment]
Don't we really need a way to set up API key? depending on PAT is fine in some cases but not all. Ex: outside of VS

**Comment by bstoinev** [comment]
OK. I have generated a PAT with full access and supplied it to a "nuget.exe push" command.
There is no difference as it keeps asking for username and password.
Any thoughts? I really need to publish entirely from the command line without setting up a config file...
