### ISSUE TITLE
Description for working directory is undefined

### ISSUE THREAD

**Issue by atg-abhishek** [MicrosoftDocs/vsts-docs#2510]
In the arguments section of this page, the description for the "working directory" parameter is missing. It would be great to have it in place so that the exact purpose is clear for what this can be used for.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1eeb2956-beca-447d-c9a6-a859f3cfc4bf
* Version Independent ID: 89f2a014-99bb-420d-265c-42515d30c80b
* Content: [Python Script task - Azure Pipelines & TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/python-script?view=vsts)
* Content Source: [docs/pipelines/tasks/utility/python-script.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/utility/python-script.md)
* Product: **devops**
* GitHub Login: @erickson-doug
* Microsoft Alias: **brcrista**

**Comment by DavidStaheli** [comment]
Thanks @atg-abhishek!  Tracked as internal bug 1410665.

**Comment by hp685** [comment]
Should this be reopened? It still shows as undefined.
