### ISSUE TITLE
1-1 Mapping of argument names in the yaml sample with the documentation

### ISSUE THREAD

**Issue by atg-abhishek** [MicrosoftDocs/vsts-docs#2511]
The arguments section of this page would be much more effective if under the argument column, the values are the exact same as the ones in the yaml sample. There is a misalignment for some fields where it isn't immediately clear which field the argument (in the arguments section) is referring to. The current text is helpful and could be placed under an additional column

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c0a16bcf-af6c-e278-f0a6-8ec95012ce4a
* Version Independent ID: ae442106-33b3-786f-2158-34eed3fed6e0
* Content: [Download Build Artifacts task - Azure Pipelines & TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/download-build-artifacts?view=vsts)
* Content Source: [docs/pipelines/tasks/utility/download-build-artifacts.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/utility/download-build-artifacts.md)
* Product: **devops**
* GitHub Login: @erickson-doug
* Microsoft Alias: **dastahel**

**Comment by DavidStaheli** [comment]
@Lovakumar does your team own this task and its docs?  If so, could you please assign this issue appropriately?

**Comment by tillig** [comment]
I was about to leave this same feedback on a different page. For all the build task documentation it's hard to correlate a YAML sample with the prose documentation. The text "naming" the argument doesn't necessarily directly translate into the actual YAML item that needs to be present. This is possibly my largest frustration trying to get my builds into Azure DevOps so far. Makes the build very trial-and-error to get right.

**Comment by Lovakumar** [comment]
@DavidStaheli yes our team owns this task. Assigning it to me.

**Comment by DavidStaheli** [comment]
@Lovakumar I'm unable to assign this to you because you aren't in the MicrosoftDocs org.  Is there someone else on your team to whom it can be assigned?

**Comment by Lovakumar** [comment]
@DavidStaheli I just joined MicrosoftDocs org. Whom can I ask for write permission on this repo.

**Comment by kzu** [comment]
The doc is quite unusable without a column that has the *name* as it appears in the YAML

**Comment by randyram-at-ms** [comment]
It's been months since this was first flagged, can we get this updated please?

**Comment by ashokirla** [comment]
Thanks for the feedback. We are fixing this issue. Should be available in production very soon.

**Comment by ashokirla** [comment]
https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/download-build-artifacts?view=azure-devops
