### ISSUE TITLE
buildVersionToDownload missing description in the arguments section

### ISSUE THREAD

**Issue by atg-abhishek** [MicrosoftDocs/vsts-docs#2517]
While the yaml snippet has the enum values listed, it would be great to reiterate and expand on them in the argument's description section with specific meanings for each of the enum values.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c0a16bcf-af6c-e278-f0a6-8ec95012ce4a
* Version Independent ID: ae442106-33b3-786f-2158-34eed3fed6e0
* Content: [Download Build Artifacts task - Azure Pipelines & TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/download-build-artifacts?view=vsts)
* Content Source: [docs/pipelines/tasks/utility/download-build-artifacts.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/utility/download-build-artifacts.md)
* Product: **devops**
* GitHub Login: @erickson-doug
* Microsoft Alias: **dastahel**

**Comment by alexmullans** [comment]
@steved0x for the current-gen Build Artifacts (i.e. not the next-gen, in preview [Pipeline Artifacts](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/utility/download-pipeline-artifact.md)), can you route issues to @DavidStaheli's CIX team? I'll reroute this first batch you filed. Sorry for the confusion.

**Comment by DavidStaheli** [comment]
@Lovakumar does your team own this task and its docs?  If so, could you please assign this issue appropriately?

**Comment by DavidStaheli** [comment]
@Lovakumar does your team own this task and its docs? If so, could you please assign this issue appropriately?

**Comment by davidstaheli** [comment]
Thanks for the suggestion.  The docs have been updated for this and should be live within a few days.
