### ISSUE TITLE
Agent.OSArchitecture

### ISSUE THREAD

**Issue by asepdf** [MicrosoftDocs/vsts-docs#2519]
How to specify Agent.OSArchitecture? 
One of our Virtual Machine has a value of x64, however others used x86. Those virtual machines are set up using the same configurations.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 47625b86-abd5-ee15-6d61-8bcf81861b96
* Version Independent ID: be9a6174-a69b-7aed-d584-5f602fcc5eb4
* Content: [Build and Release Agents - Azure Pipelines & TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/agents?view=vsts)
* Content Source: [docs/pipelines/agents/agents.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/agents/agents.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by vtbassmatt** [comment]
The agent itself sets up Agent.OS and Agent.OSArchitecture for you. For some reason, the docs about Agent.OSArchitecture have disappeared off the site, so I'm looking into getting them restored.

**Comment by jdshkolnik** [comment]
How does the agent determine OSArchitecture? I have a Windows 2016 datacenter VM in Azure which the agent seems to have decided is x86.

**Comment by vtbassmatt** [comment]
It's [set at build time](https://github.com/Microsoft/azure-pipelines-agent/blob/ba677cc9139ef3b71aaf638d4dcbe9bdcfe871f9/src/Microsoft.VisualStudio.Services.Agent/Constants.cs#L82), so you may have installed an x86 agent.

**Comment by jdshkolnik** [comment]
Yep. I didn’t realize that’s the one which was returned by clicking download agent from the agent pools page.

**Comment by vtbassmatt** [comment]
Sorry for the confusion. There are pickers to let you choose between the different flavors (OS, architecture).

![image](https://user-images.githubusercontent.com/714283/50919587-2f2d2c80-1411-11e9-9eac-e811403514fc.png)

**Comment by jdshkolnik** [comment]
I see. My fault for being in a rush and just clicking download. Wouldn't it make more sense to default to x64?

**Comment by vtbassmatt** [comment]
Not a bad idea :grin: I have to believe more people want x64 than x86.
