### ISSUE TITLE
Please document environment variables

### ISSUE THREAD

**Issue by heaths** [MicrosoftDocs/vsts-docs#2521]
Many - if not most or even all - of these variables have corresponding environment variables. At one point these were documented, perhaps on MSDN. Please consider adding them back, as its easier than trying to discover them for use directly in scripts or redefining custom environment variables.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ffebdc8-521c-44b5-cde4-4abdc1bd6f18
* Version Independent ID: dc0effda-6d93-62aa-64c5-4e6f283b0826
* Content: [Predefined build variables - Azure Pipelines & TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=vsts)
* Content Source: [docs/pipelines/build/variables.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/build/variables.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by ar4hc** [comment]
on a linux agent add a bash task and do an "env" in there, that gives sth like:

SYSTEM_TEAMFOUNDATIONCOLLECTIONURI=https://dev.azure.com/********/
SYSTEM_TASKDEFINITIONSURI=https://dev.azure.com/********/
AGENT_VERSION=2.146.0
LEIN_HOME=/usr/local/lib/lein
RELEASE_REQUESTEDFOR=********
RELEASE_DEPLOYMENT_REQUESTEDFORID=*********
SYSTEM_HOSTTYPE=release
GOROOT_1_11_X64=/usr/local/go1.11
SYSTEM_JOBPARALLELISMTAG=Private
GOROOT_1_9_X64=/usr/local/go1.9
ANDROID_HOME=/usr/local/lib/android/sdk
RELEASE_DEFINITIONID=1
PARAMETERS_CONNECTIONTYPE=Azure Resource Manager
AGENT_MACHINENAME=fv-az507
RELEASE_SKIPARTIFACTSDOWNLOAD=False
SYSTEM_WORKFOLDER=/home/vsts/work
PARAMETERS_AZURERESOURCEGROUP=RG_EMEA_Digital_TST
RELEASE_REQUESTEDFOREMAIL=ar@homemadecode.de
GRADLE_HOME=/usr/share/gradle
AGENT_JOBNAME=Release
ANDROID_SDK_ROOT=/usr/local/lib/android/sdk
MSDEPLOY_HTTP_USER_AGENT=VSTS_bfe0de7b-efda-4a6f-ae94-59e56c03c95f_release_1_4_4_1
JAVA_HOME_8_X64=/usr/lib/jvm/zulu-8-azure-amd64
AGENT_OSARCHITECTURE=X64
AGENT_ACCEPTTEEEULA=True
ANT_HOME=/usr/share/ant
SYSTEM_CULTURE=en-US
JAVA_HOME_11_X64=/usr/lib/jvm/zulu-11-azure-amd64
AGENT_TEMPDIRECTORY=/home/vsts/work/_temp
USER=vsts
SYSTEM_TEAMFOUNDATIONSERVERURI=https://vsrm.dev.azure.com/******/
TF_BUILD=True
AZURE_HTTP_USER_AGENT=VSTS_bfe0de7b-efda-4a6f-ae94-59e56c03c95f_release_1_4_4_1
SYSTEM_TASKDISPLAYNAME=Bash Script
RELEASE_DEFINITIONNAME=Release to Test
RELEASE_REQUESTEDFORID=Ï
RELEASE_RELEASEID=4
RELEASE_REASON=Manual
SYSTEM_TEAMPROJECTID=7059e0ce-a947-45a0-aa01-cb4f9133d680
VSTS_PROCESS_LOOKUP_ID=vsts_cfc49a4c-28a3-4271-b5d0-9e49c42a129e
AGENT_ROOTDIRECTORY=/home/vsts/work
SYSTEM_TEAMPROJECT=EMEA Driver Companion
RELEASE_ENVIRONMENTNAME=Stage 1
AGENT_HOMEDIRECTORY=/home/vsts/agents/2.146.0
AGENT_TOOLSDIRECTORY=/opt/hostedtoolcache
RELEASE_ENVIRONMENTURI=vstfs:///ReleaseManagement/Environment/4
RELEASE_DEPLOYMENT_REQUESTEDFOREMAIL=ar@homemadecode.de
agent.jobstatus=Succeeded
SYSTEM=release
PARAMETERS_AZURESUBSCRIPTIONENDPOINT=65cc31c8-cab0-428a-a137-87c0e26c5a9f
AGENT_OS=Linux
DOTNET_SKIP_FIRST_TIME_EXPERIENCE=1
RELEASE_RELEASEURI=vstfs:///ReleaseManagement/Release/4
PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games"
LEIN_JAR=/usr/local/lib/lein/self-installs/leiningen-2.8.3-standalone.jar
VSTS_AGENT_PERFLOG=/home/vsts/agentperf
PWD=/home/vsts/work/r1/a/$(agent.builddirectory)/Chart
INPUT_ARGUMENTS=
CONDA=/usr/share/miniconda
GOROOT_1_10_X64=/usr/local/go1.10
JAVA_HOME=/usr/lib/jvm/zulu-8-azure-amd64
PARAMETERS_KUBERNETESSERVICEENDPOINT=
PARAMETERS_KUBERNETESCLUSTER=emeadigital-tst
JAVA_HOME_7_X64=/usr/lib/jvm/zulu-7-azure-amd64
RELEASE_RELEASENAME=Release-4
SYSTEM_ENABLEACCESSTOKEN=False
LANG=en_US.UTF-8
SYSTEM_TASKINSTANCENAME=cb88c0f23cd40b4a01557038d3f739d
RELEASE_ATTEMPTNUMBER=1
RELEASE_DEPLOYPHASEID=4
SYSTEM_SERVERTYPE=Hosted
RELEASE_DEPLOYMENTID=4
AGENT_WORKFOLDER=/home/vsts/work
SYSTEM_TIMELINEID=314d6be5-c27b-495c-8bdf-4b2d830e07c4
SYSTEM_ARTIFACTSDIRECTORY=/home/vsts/work/r1/a
SHLVL=1
RELEASE_TRIGGERINGARTIFACT_ALIAS=
AGENT_ID=25
M2_HOME=/usr/share/apache-maven-3.6.0
HOME=/home/vsts
REQUESTEDFORID=************************************
GOROOT=/usr/local/go1.11
SYSTEM_JOBPOSITIONINPHASE=1
RELEASE_RELEASEDESCRIPTION=
RELEASE_DEPLOYMENT_REQUESTEDFOR=Andreas Rabus
SYSTEM_TASKINSTANCEID=a2dd472f-eac6-4828-a93d-c7dcf7c23e7a
CHROME_BIN=/usr/bin/google-chrome
RELEASE_DEPLOYMENT_STARTTIME=2019-02-13 13:19:54Z
RELEASE_DEFINITIONENVIRONMENTID=1
SYSTEM_DEFAULTWORKINGDIRECTORY=/home/vsts/work/r1/a
RELEASE_ENVIRONMENTS_STAGE_1_STATUS=InProgress
SYSTEM_JOBID=e6518c05-cff4-4cce-a751-37cac859febd
RELEASE_RELEASEWEBURL=https://dev.azure.com/******/7059e0ce-a947-45a0-aa01-cb4f9133d680/_release?releaseId=4&_a=release-summary
SYSTEM_TOTALJOBSINPHASE=1
RELEASE_ENVIRONMENTID=4
AGENT_NAME=Hosted Agent
SYSTEM_PLANID=314d6be5-c27b-495c-8bdf-4b2d830e07c4
SYSTEM_COLLECTIONID=bfe0de7b-efda-4a6f-ae94-59e56c03c95f
AGENT_JOBSTATUS=Succeeded
TASK_DISPLAYNAME=Bash Script
ENDPOINT_URL_SYSTEMVSSCONNECTION=https://vsrm.dev.azure.com/********/
AGENT_RELEASEDIRECTORY=/home/vsts/work/r1/a
SYSTEM_PARALLELEXECUTIONTYPE=None
(some stuff replaced with "*"...)

**Comment by heaths** [comment]
@ar4hc I considered doing the same, but if it isn't documented it's not supported and could change at any time.

**Comment by newOnahtaN** [comment]
Any update on this?

**Comment by andyjlewis** [comment]
Thank you for posting this issue. Apologies for the delayed response. I've added this request to our backlog. Heads up to @steved0x
