### ISSUE TITLE
Issue with the frequency of notifications

### ISSUE THREAD

**Issue by vishnu4** [MicrosoftDocs/vsts-docs#2523]
I'm having an issue with notifications and how many are sent.  Is there a way to make a change so that we get only 1 email for a single 'event'.  For example:  I have 3 notification settings for my PRs.
* Personal
     * a pull request is created or updated
     * a comment is left on a pull request
* Project
     * pull request changes

Now if i have 5 people in my team set as optional reviewers, every time someone makes a PRs i will get about 10 emails about that one event.  One for each reviewer that is added to the PR, one for the PR that is created, one for the auto complete that is set, and a few other various ones.  If i'm getting multiple PRs sent to me by my team, i'm getting a TON of noise in my email box.  I want to be notified of changes, but not if they're all based on the same change.  can you group some of these events into 1 email or something?

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3b931cee-77fa-350a-bbed-4098dd1d711b
* Version Independent ID: a567ad58-83cf-d481-ae69-afdb0dbf9fe1
* Content: [Notifications FAQs - Azure DevOps Services & TFS](https://docs.microsoft.com/en-us/azure/devops/notifications/faq-notifications?view=vsts)
* Content Source: [docs/notifications/faq-notifications.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/notifications/faq-notifications.md)
* Product: **devops**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @vishnu4, Thanks for your question. I hope the following helps.

There are a couple of global subscriptions that are turned on by default, as follows:

•	Personal
o	PR reviewers added or removed – For PRs you created, a notification is sent when someone is added or removed from a PR.
o	PR Completion fails – A PR you created failed to get merged
o	PR Change – For PRs you created or PRs you’re a reviewer for, notify you about comments made 
•	Project (the team)
o	PR Changes – Notifies the team (i.e. all members of the team group) when a PR where the team is a reviewer is getting updated
o	PR reviewers added or removed – Notify the team (i.e. all members of the team group) it’s added or removed as a reviewer of the PR

When an event occurs, like adding a reviewer, all subscriptions are checked to see if there is match. For each match, those that are targets of the subscription are sent an email. So, depending on the scenario, it’s possible that adding, removing, commenting, etc. could be seen as multiple events or one that match to one or multiple subscriptions, resulting in one or multiple emails. The best route would be for you to evaluate opting out of perhaps the team level default subscriptions and letting team members utilize their personal subscriptions. 

I recommend starting with the following [troubleshooting doc](https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fazure%2Fdevops%2Fnotifications%2Ftroubleshoot-unexpected-email%3Fview%3Dvsts&data=02%7C01%7CChrystal.Comley%40microsoft.com%7Cb58c6fafe7274e38e34c08d64fd3b517%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636784168024179435&sdata=DZqkjNtEFJ9TzlmvsgBSfSGBjy3ryYI8YRtA8kcSF7o%3D&reserved=0) to help you figure out which subscriptions you want to stay subscribed to. If you’re still stuck, then you should open a free support ticket: https://docs.microsoft.com/en-us/azure/devops/user-guide/provide-feedback?view=vsts

**Comment by vishnu4** [comment]
Hi, i'm sorry but i understand all those settings you've described, but I thought i was clear above that i had already used them and turned them on.  My issue isn't that they aren't working, but that they perhaps work too well.   Say i have set in my notifications:

- PR Changes
- PR Reviewers added or removed

Now of course i want to know if someone is added or removed to a PR that was created yesterday or something like that. But if a PR is created, i don't want 10 emails telling me that the PR was made, and then 9 extra emails for each reviewer that has been added to that PR.  That's just spamming me with information at this point.

I don't want to turn off being notified if a reviewer has been added, i just don't want multiple notifications of basically the same event if they're all tied together.  Some smart bundling is all i'm asking for.
