### ISSUE TITLE
 Alwayson High availability Group deployment via Visual Studio

### ISSUE THREAD

**Issue by Ramakoteswarudu** [MicrosoftDocs/vsts-docs#2524]
When i am trying to deploy Dacpac on always on high availability group  sql server 2016 i am getting following errors.

.Net SqlClient Data Provider: Msg 1468, Level 16, State 1, Line 5 The operation cannot be performed on database "Database" because it is involved in a database mirroring session or an availability group.  Some operations are not allowed on a database that is participating in a database mirroring session or in an availability group.  

 IF EXISTS (SELECT 1
          FROM   [master].[dbo].[sysdatabases]
          WHERE  [name] = N'$(DatabaseName)')
   BEGIN
         ALTER DATABASE [$(DatabaseName)]
           SET PAGE_VERIFY NONE,
                 DISABLE_BROKER 
            WITH ROLLBACK IMMEDIATE;
    END

How to deploy to high availability group using winRM in on-prem SQL servers.

**Comment by Ramakoteswarudu** [comment]
In Primary server i have DB dbo access where as in fail-over server has read only access.

**Comment by steved0x** [comment]
@Ramakoteswarudu Thank you for the feedback. Can you let me know which article this feedback is for, so I can assign it to the author? You can reply here with the URL of the topic, or you can create a new issue by browsing to the topic on docs.microsoft.com and choosing **Content feedback** at the bottom. 

![image](https://user-images.githubusercontent.com/1580889/42953695-fd174150-8b48-11e8-94de-26924ca79c71.png)

**Comment by steved0x** [comment]
I'm closing this issue since it is not associated with a topic. To continue the discussion, please open a new issue that is associated with a topic by browsing to the topic on docs.microsoft.com and choosing **Content feedback** at the bottom. Thank you for your feedback.

![image](https://user-images.githubusercontent.com/1580889/42953695-fd174150-8b48-11e8-94de-26924ca79c71.png)
