### ISSUE TITLE
How do I provide release variables when invoking via a trigger, REST or an Azure Logic App?

### ISSUE THREAD

**Issue by atrauzzi** [MicrosoftDocs/vsts-docs#2525]
There doesn't appear to be documentation anywhere about how to provide this, yet I can set variables when I manually create them in the dashboard.

#### Related
- https://feedback.azure.com/forums/287593-logic-apps/suggestions/36074281-azure-devops-releases-allow-variables-to-be-spec
- https://developercommunity.visualstudio.com/content/idea/388532/specify-variables-with-release-trigger.html
- https://twitter.com/Omega_/status/1065271010876903425

Without an option to provide variables when triggering builds, I end up having to do this, which is less than ideal:

![image](https://user-images.githubusercontent.com/115199/48855299-69ffd600-ed79-11e8-86e8-7781bd6d2d5d.png)

The problem here is that if I need to update my pipeline, I now have to hand-edit it in two places rather than using a single consistent one.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 611642f0-881f-10b9-ae94-3c562001d1f0
* Version Independent ID: 41efb94b-4c7a-64a3-b23b-70c8634ae727
* Content: [Release variables in Azure Pipelines - Azure Pipelines & TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/variables?view=vsts&tabs=batch)
* Content Source: [docs/pipelines/release/variables.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/release/variables.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment]
Thank you for your feedback. I have passed this on to the product team for advice.

**Comment by bansalaseem** [comment]
@atrauzzi Can you please look at method CreateRelease in this [file ](https://github.com/Microsoft/vsts-dotnet-samples/blob/master/ClientLibrary/Snippets/Microsoft.TeamServices.Samples.Client/Release/ReleasesSample.cs) and see whether it works for you or not?

**Comment by atrauzzi** [comment]
@bansalaseem - I have no idea what this file is doing or how it pertains to my original issue.

**Comment by guillaume-kizilian** [comment]
I am also very interested in some documentation or tutorials on the matter.

Also i've noticed this line when creating a draft release but couldn't find the informations in the linked documentation (learn more link).
![image](https://user-images.githubusercontent.com/6792560/55468758-59ebe300-5604-11e9-80f4-adfaf8e13079.png)

It seems documentation isn't even available through basic trigger, let alone through Rest API.

Thanks you.

**Comment by atrauzzi** [comment]
@bansalaseem - I'm still waiting for you to respond. I'm not sure you understood the original question.

**Comment by bansalaseem** [comment]
@atrauzzi , I am assuming that you are looking for a rest API with which you can specify variables at release creation time. If yes, this API should help. 

https://docs.microsoft.com/en-us/rest/api/azure/devops/release/Releases/Create?view=azure-devops-rest-5.0

![image](https://user-images.githubusercontent.com/22289943/55631079-d33a3000-57d4-11e9-8226-f21870e00759.png)

**Comment by atrauzzi** [comment]
This ticket specifically states for an Azure Logic App task.  So I'm not responsible in this case for constructing an API request.

**Comment by bansalaseem** [comment]
I did not get your question then. Can you please share the screenshots of the mechanism that you follow via RM UI today so that I can tell you how can achieve the same thing via API?
