### ISSUE TITLE
Search Administration needs update

### ISSUE THREAD

**Issue by michha** [MicrosoftDocs/vsts-docs#2526]
Scripts for sections _Pause indexing_ and _Resume indexing_ are not available on [github](https://github.com/Microsoft/Code-Search), so probably these sections need to be updated (or the scripts need to be made available)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be0bdbf7-3132-9007-6c6a-368c5bcb0f3d
* Version Independent ID: 58118f61-f88f-24b9-b785-d8f9d8a1fefd
* Content: [Code, Wiki and Work Item Search set up](https://docs.microsoft.com/en-us/azure/devops/project/search/administration?view=vsts&tabs=new-nav)
* Content Source: [docs/project/search/administration.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/project/search/administration.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by nschonni** [comment]
https://github.com/Microsoft/Code-Search/blob/master/PauseIndexing.ps1
https://github.com/Microsoft/Code-Search/blob/master/ResumeIndexing.ps1

**Comment by michha** [comment]
I am sry for missing this (I also searched the github project for the filename in the documentation).

Its somehow confusing that there are version-specific folders but also some files outside that should be copied all together.

How about moving the root scripts into the specific folders, so someone just needs the version-specific folder that contains everything.

**Comment by alexhomer1** [comment]
Thank you for your feedback. I have passed this on to the product team for attention.

**Comment by ShubhamJain1992** [comment]
I validated that the documentation has been updated and the common scripts have bee copied to version specific folders.
