### ISSUE TITLE
Seriously, where's the documentation?

### ISSUE THREAD

**Issue by boblechat** [MicrosoftDocs/vsts-docs#2527]
- There is too few examples on GitHub
- Unanswered issues on GitHub
- There's not a single release note / changelog for these libraries: what's new and what has been removed since the previous version?
- Lots of methods are undocumented (contextual help or IntelliSense in Visual Studio)
- REST APIs are not present in the documentation (where's the Identity API?)
- ...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 413163f0-28c3-a2a7-d626-fcb81bcb2257
* Version Independent ID: 57c127da-2b1e-d29e-9abb-a3c258762ccf
* Content: [.NET Client Libraries for Azure DevOps Services (and TFS)](https://docs.microsoft.com/en-us/azure/devops/integrate/concepts/dotnet-client-libraries?view=vsts)
* Content Source: [docs/integrate/concepts/dotnet-client-libraries.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/integrate/concepts/dotnet-client-libraries.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by mtrtm** [comment]
I second this.  Just trying to figure out how to delete a branch is impossible.  There is a DeleteRefFavoriteAsync() method - but good luck trying to figure out what a favorite id (int) is.  Where do I get that?  I just want to delete a branch.

**Comment by elbatk** [comment]
Hey everyone, adding @willsmythe here for awareness. Weak .NET Client Library documentation is definitely on our radar and something we are trying to address.

**Comment by avishnyakov** [comment]
Overall, same-same experience as @boblechat and @mtrtm mentioned with .NET and nodejs versions of these APIs. Confusing, under documented, and lacking working examples.

@elbatk @willsmythe did we have any news on this?

**Comment by willsmythe** [comment]
Official .NET client reference can be found here: https://docs.microsoft.com/en-us/azure/devops/integrate/concepts/dotnet-client-libraries?view=azure-devops (may not answer all questions, but is a start --- we'll do more to make this easier to find, it's currently a little buried in our docs)

**Comment by chcomley** [comment]
Following up on this issue - did you all get your questions answered to your liking? Please let me know, otherwise I'll close this issue at end of week. Happy to find answers if needed. Thanks!
