### ISSUE TITLE
SQLPackage?

### ISSUE THREAD

**Issue by ianrandell** [MicrosoftDocs/vsts-docs#2528]
Would be nice to have a link to SQLPackage, in particular how to get it/install it

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cd85890a-ccba-8697-b406-b662aabeb27f
* Version Independent ID: a1d371df-c0a0-1cd6-37f8-4b60913a2e97
* Content: [Azure SQL database deployment - Azure Pipelines & TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/targets/azure-sqldb?view=vsts&tabs=yaml#additional-sql-actions)
* Content Source: [docs/pipelines/targets/azure-sqldb.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/targets/azure-sqldb.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment]
Thank you for your feedback. I will update the topic to include your recommendations.
