### ISSUE TITLE
Categories in vss-extension needs updating

### ISSUE THREAD

**Issue by steveculshaw** [MicrosoftDocs/vsts-docs#2533]
Reading https://docs.microsoft.com/en-us/azure/devops/extend/develop/manifest?view=vsts#required-attributes I believe the categories in the vss-extension.json needs updating to ...  "categories": ["Azure Pipelines"],

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 44581f4a-93df-7507-3844-eadedf9a6cc4
* Version Independent ID: 33c7bcf0-1512-975f-5ef8-9f2a192a84ad
* Content: [Add a Build or Release Task](https://docs.microsoft.com/en-gb/azure/devops/extend/develop/add-build-task?view=vsts)
* Content Source: [docs/extend/develop/add-build-task.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/extend/develop/add-build-task.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by elbatk** [comment]
Hi @steveculshaw, I've reached out to the dev who helped me write this article, and we'll get it fixed!

**Comment by elbatk** [comment]
We got this change handled and is on the way to live today - thank you!
