### ISSUE TITLE
Missed arrow

### ISSUE THREAD

**Issue by youreeck** [MicrosoftDocs/vsts-docs#2535]
Hi,
It looks like that possibility to link TFVC changeset to the build is missed in https://docs.microsoft.com/en-us/azure/devops/boards/queries/link-work-items-support-traceability?view=vsts&tabs=new-web-form#work-items-linked-to-code-artifacts-and-builds
Best regards,
Yury

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba7c85b2-fb57-aefe-af67-fcdcbb94e595
* Version Independent ID: ea532ac5-f00b-d570-80b4-781190c9b4ed
* Content: [Link work items to support traceability - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/queries/link-work-items-support-traceability?view=vsts&tabs=new-web-form#link-work-items)
* Content Source: [docs/boards/queries/link-work-items-support-traceability.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/boards/queries/link-work-items-support-traceability.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@youreeck - Thank you for your inquiry. This article addresses linking work items to various objects. Linking TFVC changeset to a build isn't covered here. I have a backlog item to address end-to-end traceability which will address other types of links. Meanwhile - this article may address tracking changesets: https://docs.microsoft.com/en-us/azure/devops/repos/tfvc/view-where-when-changesets-have-been-merged?view=vsts.
