### ISSUE TITLE
How to specify branch in artifacts URL?

### ISSUE THREAD

**Issue by StrikerRUS** [MicrosoftDocs/vsts-docs#2536]
How can I download latest artifacts from a **specific branch**?

Simple appending `&branchName=` doesn't work.

According to the [docs](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/download-build-artifacts?view=vsts), it's possible to do via the task (`branchName` argument). But in which URL parameter is this argument translated?

Thanks in advance!

**Comment by StrikerRUS** [comment]
ping @DavidStaheli as [you kindly suggested your help recently](https://github.com/Microsoft/LightGBM/pull/1660#issuecomment-421343042).

**Comment by StrikerRUS** [comment]
Docs about REST API don't state this possibility, they offer only `buildId` field: 
https://docs.microsoft.com/ru-ru/rest/api/azure/devops/build/artifacts/get?view=azure-devops-rest-4.1

**Comment by alexmullans** [comment]
@steved0x I think this goes to @DavidStaheli (who's out for most of this month) or someone on his team.

**Comment by pjquirk** [comment]
@StrikerRUS Artifacts are only associated with builds. The task allows you to specify a branch name which it uses to determine the build to retrieve the artifact from.  In other words, if your task was setup as below:

    - task: DownloadBuildArtifacts@0
    inputs:
        project: 'My project name'
        pipeline: 'My pipeline name'
        buildType: 'specific'
        buildVersionToDownload: 'latestFromBranch'
        branchName: 'refs/heads/MyBranch'

The task would look for the latest build that built from `refs/heads/MyBranch`, and then use that build's Id to retrieve artifacts.  You could do something similar by first querying the [List Builds](https://docs.microsoft.com/en-us/rest/api/azure/devops/build/builds/list?view=azure-devops-rest-4.1) endpoint and specifying a branch name, and then using the Id of the build returned to query its artifacts.

**Comment by StrikerRUS** [comment]
@pjquirk Thanks a lot for your answer!

I see [`queryOrder`](https://docs.microsoft.com/en-us/rest/api/azure/devops/build/builds/list?view=azure-devops-rest-4.1#buildqueryorder) argument for the API, but I don't see how to sort returned builds by IDs. Is it possible?
BTW, in `4.1` description is broken:

![image](https://user-images.githubusercontent.com/25141164/49406556-f8eff380-f766-11e8-91ee-cf0102a2c59e.png)

**Comment by pjquirk** [comment]
There's no explicit sort for build Id, but since you're interested in build artifacts and they're most useful once the build has completed, I'd suggest using `finishTimeDescending` and getting the first build.

Thanks for pointing out the issue with the enum's descriptions, I'll look into resolving that.

**Comment by StrikerRUS** [comment]
@pjquirk Thank you for the information and suggestion!

The last question: what is the default sort behavior in REST API and in `task: DownloadBuildArtifacts@0` with `buildVersionToDownload: 'latestFromBranch'`?

**Comment by StrikerRUS** [comment]
@pjquirk Thank you very much for your answers!

Where can I post a feature request for sorting order by IDs?

**Comment by pjquirk** [comment]
Developer Community: https://developercommunity.visualstudio.com/spaces/21/index.html
