### ISSUE TITLE
Anyone can update the global retention policy

### ISSUE THREAD

**Issue by BetaVersionAnurag** [MicrosoftDocs/vsts-docs#2539]
We have seen that global retention policy for our collection is changing on frequent basis, while investigating further we have found that any user with any permissions to TFS can update the Global Retention policy. Is there any restriction for that for restrict only authorized users can update the Global retention policies ?

**Comment by steved0x** [comment]
https://docs.microsoft.com/en-us/azure/devops/pipelines/policies/retention?view=vsts
