### ISSUE TITLE
Even after a second read, this documentation isn't helping.

### ISSUE THREAD

**Issue by RubixRevenge** [MicrosoftDocs/vsts-docs#254]
So I gave the documentation another chance. PLEASE. How about TFS documentation? One-size-fits all isn't working.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2d588805-0219-7eb1-6a5c-1f1363f41870
* Version Independent ID: 515fb392-083b-644b-b824-efb581aa0a91
* [Content](https://docs.microsoft.com/en-us/vsts/build-release/test/example-continuous-testing)
* [Content Source](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/build-release/test/example-continuous-testing.md)
* Service: unspecified

**Comment by alexhomer1** [comment]
Thank you for your feedback. TFS and VSTS share a UI and features, however the release schedule for updates to VSTS is more regular - which causes some disconnect in the documentation until TFS releases catch up. We are working to provide a new documentation experience that clearly shows the differences between VSTS and each version of TFS. You will see this new experience appearing in the coming months.
