### ISSUE TITLE
Release.Deployment.StartTime

### ISSUE THREAD

**Issue by Locoxella** [MicrosoftDocs/vsts-docs#2540]
Why Release.Deployment.StartTime is not being included in here? Is in the logs as RELEASE_DEPLOYMENT_STARTTIME. Is it planned to stop declaring this variable or is just missing in the documentation?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 611642f0-881f-10b9-ae94-3c562001d1f0
* Version Independent ID: 41efb94b-4c7a-64a3-b23b-70c8634ae727
* Content: [Release variables in Azure Pipelines - Azure Pipelines & TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/variables?view=vsts&tabs=batch)
* Content Source: [docs/pipelines/release/variables.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/release/variables.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by Locoxella** [comment]
Scratch that... I see that only a few variables are Included in the documentation as per disclaimer: "Some of the most significant variables are described in the following tables."

**Comment by Locoxella** [comment]
Created Pull Request #2544 to clarify even further that the tables in [docs/pipelines/release/variables.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/release/variables.md) do not contain the fully up to date list of variables, but only "Some of the most significant".

**Comment by Locoxella** [comment]
Closing PR #2544 due to automated validation failures... Opened PR #2546 : same validation errors

**Comment by alexhomer1** [comment]
Thank you for your feedback. I will update the topic to include your recommendations.

**Comment by acds** [comment]
Is there a "Full" list of variable available ?
