### ISSUE TITLE
Is it possible to use it in releases as mentioned in the summary?

### ISSUE THREAD

**Issue by fleed** [MicrosoftDocs/vsts-docs#2542]
When trying to use it in a release, I get the following error:

`##[error]This task must run in a build to publish artifacts to Azure Pipelines/TFS.`

which seems in contradiction with the initial sentence **Use this task in a build or release pipeline..**
Is it an error in the documentation, or are there limitations?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b3f565b-88e4-88d6-a534-48ec21e6e3d8
* Version Independent ID: 9fca89ae-4a6e-a43a-2834-1a91ad44c256
* Content: [Publish Build Artifacts task - Azure Pipelines & TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/publish-build-artifacts?view=vsts)
* Content Source: [docs/pipelines/tasks/utility/publish-build-artifacts.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/utility/publish-build-artifacts.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by RoopeshNair** [comment]
As of now, Publish build artifacts tasks can be used only in build pipelines.

**Comment by joseph-cloudthing** [comment]
parallel & parallelCount don't seem to have any effect?

**Comment by fleed** [comment]
If I'm right, I should prefer using `PublishPipelineArtifact`, shouldn't I?
A message with a link in the documentation would help.

Then I think that we could close this issue.

**Comment by elbatk** [comment]
I believe we updated the text here, thanks Roopesh! @fleed, are you saying a blurb with "if you want to use this in a release pipeline, use Pipeline Artifacts instead." would be helpful? Adding @vijayma to confirm that if you want to publish in a release pipeline, you must use Pipeline Artifacts.

**Comment by fleed** [comment]
@elbatk it seems that even the other task doesn‘t work in a release pipeline

**Comment by DavidNewby** [comment]
so is there a way to publish artifacts that are generated from a RELEASE (not build) pipeline?

I want to be able to create an output file in stage 1, then download that in stage 2 and deploy directly the image verses creating an image from scratch in each stage...

**Comment by chasewilson** [comment]
@DavidNewby Thanks for the questions. I believe the PublishPipelined Artifacts Should work for release Pipelines. If you having issues there, you should open a new issue under that page or reach out to the  [Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html). I'll be closing this issue for now :)
