### ISSUE TITLE
There is a different pattern format which is not mentioned

### ISSUE THREAD

**Issue by davidda** [MicrosoftDocs/vsts-docs#2551]
It seems that some prarameters of build tasks excpect a different pattern format that looks like this:

HelloWorldApp\*.sln;-:**\Dummy.sln

So ; for multiple patterns and -: for exclusions. Maybe this sould be mentioned, because I was trying the format describe in this article and it didn't work, but that other format did.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8fd54e81-9a0c-c5e5-fb89-9534372805ff
* Version Independent ID: f3d49618-32d7-0abc-1c33-8211eb7dd073
* Content: [File matching patterns reference for Azure Pipelines and TFS - Azure Pipelines & TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/file-matching-patterns?view=vsts)
* Content Source: [docs/pipelines/tasks/file-matching-patterns.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/file-matching-patterns.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by vtbassmatt** [comment]
I think he was saying there's an additional, undocumented format that works.

**Comment by davidda** [comment]
@damccorm Yes, it is the Nuget Installer Task. Parameter: Path to Solution. I'm on TFS 2018 Update 3 and I'm using v0.* of the task.

@vtbassmatt No, in this instance only the format from my comment works.

**Comment by damccorm** [comment]
It looks like this is task specific functionality and isn't based on the task-lib, the Nuget Installer Task calls the common [resolveFilterSpec](https://github.com/Microsoft/azure-pipelines-tasks/blob/942c77ee610f753e959b3e3afc5acd715865da1d/Tasks/Common/packaging-common/nuget/Utility.ts#L13) function which does this. @vtbassmatt is it expected that all built-in tasks will conform to this matching pattern? Regardless if this task is going to keep the pattern it could probably use better documentation

**Comment by vtbassmatt** [comment]
Gotcha, thanks. We have an upcoming push to fix some of these papercuts in the task docs.

**Comment by vtbassmatt** [comment]
@elbatk reassigning this to you. The NuGet Installer task isn't using the standard task-lib matcher. Ideally we'd fix that in a future major version. Either way, you'll need to document what's supported in your tasks.

**Comment by elbatk** [comment]
Thanks Matt, I'll add this to the docs update backlog for our team, appreciate the investigation from you and Danny.

**Comment by elbatk** [comment]
I just checked and it looks like we upgraded to using the task-lib matcher with V1 of this a couple of months ago (4 at least). I'm going to close this as the pattern matching should be fine.
