### ISSUE TITLE
test results and coverage will only publish on success

### ISSUE THREAD

**Issue by matcha440** [MicrosoftDocs/vsts-docs#2553]
I noticed that tasks like this one really should have a condition defined  so that they run even if tests fail. Not doing so means you will only get the success results and never the failures.

https://github.com/MicrosoftDocs/pipelines-javascript/blob/master/azure-pipelines.yml#L22

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c99686eb-6c78-0336-1ec3-802a53c9868d
* Version Independent ID: 6eaf1acb-24d4-5bb7-3935-17abe7e59dd9
* Content: [Building JavaScript and Node.js apps with Azure Pipelines or TFS - Azure Pipelines & TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/languages/javascript?view=vsts&tabs=yaml#package-and-deliver-your-code)
* Content Source: [docs/pipelines/languages/javascript.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/languages/javascript.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by vijayma** [comment]
Fixed the azure-pipelines.yml in the repo to have condition: succeededOrFailed() for Publish Test Results task. Thanks for the feedback.
