### ISSUE TITLE
Example provided does not work

### ISSUE THREAD

**Issue by JamesReate** [MicrosoftDocs/vsts-docs#2555]
Two problems with the example provided:
1. `gulp@1` does not exist. Only `Gulp@0` exists. Figured out by trial and error
2. Once you use `Gulp@0`, and run the build, you end up with the error: `Local gulp not found in D:\a\1\s`. Have not found a solution to this one - seems like VM image simply does not have gulp installed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0f19b029-4ee8-9a2f-10b2-55d691c89e69
* Version Independent ID: 69566433-f3be-a902-082d-2ed935cb2b63
* Content: [Gulp build and release task - Azure Pipelines & TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/gulp?view=vsts)
* Content Source: [docs/pipelines/tasks/build/gulp.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/build/gulp.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by jonathantwite** [comment]
This page is not clear, but this tasks needs the Npm task running first:
- task: Npm@1
  inputs:
    command: 'install'
    #workingDir: 'some/dir' #if needed

**Comment by andyjlewis** [comment]
Are you using a Microsoft-hosted agent or a self-installed agent?

**Comment by JamesReate** [comment]
I was using a Microsoft Hosted agent. If gulp@1 now exists, and it actually is tested working, then I think we can close this issue after @jonathantwite request for more clarity is done. 
Looks like it was a situation where documentation was ahead of what the Hosted Agent supported.
