### ISSUE TITLE
Group Rule Automatic Re-Evaluation

### ISSUE THREAD

**Issue by ksix** [MicrosoftDocs/vsts-docs#2558]
How often (or are?) group rules re-evaluated automatically? There is a button in the UI, but would hope this happens on its own at least daily. Can clarity on this be added to the documentation?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba38644a-fe6c-e644-2f35-2cf6fa092650
* Version Independent ID: 7d18b423-923f-d9c4-e451-ab7f8ff27bb1
* Content: [Assign access levels and extensions to users by group membership in Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/assign-access-levels-and-extensions-by-group-membership?view=vsts&tabs=new-nav)
* Content Source: [docs/organizations/accounts/assign-access-levels-and-extensions-by-group-membership.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/accounts/assign-access-levels-and-extensions-by-group-membership.md)
* Product: **devops**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @ksix, I can certainly add some clarity to the documentation. I've reached out to a few of my PMs for clarification and will keep you updated. Thank you.

**Comment by chcomley** [comment]
Hi @ksix Thanks for your patience on this. They are automatically re-run every 12 hrs. I've created a work item to have this added to the documentation. Thanks again!
