### ISSUE TITLE
Errors in document text (analytics documentation)

### ISSUE THREAD

**Issue by FokkoVeegens** [MicrosoftDocs/vsts-docs#2559]
Hi,

The last sentence of the first paragraph of this article contains some errors:

> Azure DevOps Server 2019 RC1 and later **support the installing** the Analytics extension. Team Foundation **Servier** (TFS) version 2018 and prior do not support Analytics.

Should be

> Azure DevOps Server 2019 RC1 and later **support installing** the Analytics extension. Team Foundation **Server** (TFS) version 2018 and prior do not support Analytics.

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a92a6599-73d6-492c-71c7-12284e6d5a71
* Version Independent ID: 95fa37ba-7def-a618-f02d-50bbc9225a73
* Content: [Reporting roadmap - Azure DevOps & TFS](https://docs.microsoft.com/en-us/azure/devops/report/analytics/reporting-roadmap?view=vsts)
* Content Source: [docs/report/analytics/reporting-roadmap.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/report/analytics/reporting-roadmap.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@FokkoVeegens - Thank you for the corrections. I'm updating the article accordingly.
