### ISSUE TITLE
'twine' is not recognized

### ISSUE THREAD

**Issue by wagenrace** [MicrosoftDocs/vsts-docs#2560]
Trying to follow this I get the following error:
twine : The term 'twine' is not recognized as the name of a cmdlet, function, script file, or operable program.

I have tried adding 'Import-Module twine' but without success.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 638243e7-cdd6-7573-aa6a-87c39da1bb3d
* Version Independent ID: d0046f56-ed26-7af2-3b8f-3dd5ab6ab892
* Content: [Publish packages to PyPI - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/pypi?view=vsts&tabs=yaml)
* Content Source: [docs/pipelines/artifacts/pypi.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/artifacts/pypi.md)
* Product: **devops**
* GitHub Login: @erickson-doug
* Microsoft Alias: **elbatk**

**Comment by gaborbernat** [comment]
twine is a python package and probably needs to be installed on the side by you, see e.g. https://github.com/pytest-dev/pytest-print/blob/master/azure-pipelines.yml#L132

**Comment by steved0x** [comment]
@wagenrace Did @gaborbernat suggestion work for you?

**Comment by wagenrace** [comment]
Sorry for the later reaction. Using 'pip install twine' did solve the problem. Thank you for you help

**Comment by elbatk** [comment]
I'm adding the twine installation step to the document as the first step, it should go live tomorrow. Thanks everyone!
