### ISSUE TITLE
Option to ignore error

### ISSUE THREAD

**Issue by josesimoes** [MicrosoftDocs/vsts-docs#2561]
The NuGet command for push should have an option for ignoring errors related with a package already existing.
It could not be possible to check on the conditions if this step should happen or not. In the event that the package already exists on NuGet (because they don't allow updating packages) it should be possible to ignore the error and continue, because that could be the expected outcome of this step.

**Comment by steved0x** [comment]
@josesimoes That sounds like a good idea. The issues in the vsts-docs repo are for documentation feedback, so i can pass this along, but bug reports and product improvement suggestions carry more weight when they are submitted by customers. You can file this issue [here](https://developercommunity.visualstudio.com/spaces/21/index.html) and it will go right to the product team.

Thank you for your feedback.
