### ISSUE TITLE
More information on debugging / troubleshooting strategies

### ISSUE THREAD

**Issue by atg-abhishek** [MicrosoftDocs/vsts-docs#2562]
Using ADO Pipelines in a project right now, a few things that my team and I found useful for debugging and troubleshooting were (which would be useful to capture somewhere in the documentation) 

1) Using visual pipelines, often breaking into atomic parts, to test out different pieces helps in accelerating the debugging process

2) When working staging and build artifacts, to make sure that the artifacts were saved in the correct paths, you can use the "script" task to see the contents of the directory 

3) Scoping of build and pipeline variables, especially as it pertains to jobs run by agents within the same pipeline is important to note

4) For bash tasks, there is a difference in the way the script behaves locally (even when using the same OS hosted agent) and remotely. E.g. in the availability of certain tools like "bc"  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 611642f0-881f-10b9-ae94-3c562001d1f0
* Version Independent ID: 41efb94b-4c7a-64a3-b23b-70c8634ae727
* Content: [Release variables in Azure Pipelines - Azure Pipelines & TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/variables?view=vsts&tabs=batch#debug-mode)
* Content Source: [docs/pipelines/release/variables.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/release/variables.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment]
Thank you for your feedback. I will consult the documentation team and update the topic based on their response.
