### ISSUE TITLE
 Owner Pacort of repository https://github.com/MicrosoftDocs/vsts-docs has lost Admin permission

### ISSUE THREAD

**Issue by nschonni** [MicrosoftDocs/vsts-docs#2564]
Looks like the OpenBuild bot got setup, but it's not quite working yet and marking PRs are failed https://github.com/MicrosoftDocs/vsts-docs/pull/2563#issuecomment-441691515

**Comment by steved0x** [comment]
@nschonni The repo synching between a public and private repo isn't working when one of them is an Azure Repos Git repo, we have been having an issue with syncing the changes between the two repos, and I think this is an artifact of that, I've got a ticket filed and it should be resolved soon. Once they have it fixed I'll merge the outstanding PRs (the one that can merge, and hopefully the issue with the others will be resolved by then)

**Comment by nschonni** [comment]
Looks like the OpenBuild setup was removed, so I'll close this.
Hope it does get setup in the future though :wink:
