### ISSUE TITLE
Default switches to RoboCopy

### ISSUE THREAD

**Issue by JoeBonifazi** [MicrosoftDocs/vsts-docs#2566]
When I use the Windows Machine File Copy task, I notice in the output console that the /S and /E switches to RoboCopy are included by default.  

Is this something my TFS Administrators added to our implementation, or is this the default in this task?   Can this be overridden when configuring the task in my build definition?  If so how?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5e0ef2cf-ed52-6ded-bf14-4820d73b4ed0
* Version Independent ID: 7781e0f0-43aa-9008-abda-c03a37e2d7b4
* Content: [Windows Machine File Copy task - Azure Pipelines & TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/windows-machine-file-copy?view=vsts)
* Content Source: [docs/pipelines/tasks/deploy/windows-machine-file-copy.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/deploy/windows-machine-file-copy.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment]
Thank you for your feedback. I have passed this on to the product team for advice.

**Comment by RoopeshNair** [comment]
They are default in the task and can't be overridden
