### ISSUE TITLE
How To Automate PAT Generation

### ISSUE THREAD

**Issue by JarekToro** [MicrosoftDocs/vsts-docs#2569]
We have a Azure Vm Scale Set that adds the vm to the deployment group as it is initiated. We would the like the build process too avoid a UI interface currently the only known way to generate a PAT is via the Webapp. Are there other options?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2bfea574-db69-a5fd-37fe-64ecfdac502a
* Version Independent ID: 4037d475-f194-2ac9-ffd6-70530fc3140a
* Content: [Authenticate access with personal access tokens in Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/use-personal-access-tokens-to-authenticate?view=vsts)
* Content Source: [docs/organizations/accounts/use-personal-access-tokens-to-authenticate.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/accounts/use-personal-access-tokens-to-authenticate.md)
* Product: **devops**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by steved0x** [comment]
@JarekToro I'll see if I can find out, looking at the source code for Git Credential Manager for Windows, there seems to be an example of that here:

https://github.com/Microsoft/Git-Credential-Manager-for-Windows/blob/d8b3b320c253cea8594fcc3f3f57d76b0abc1d79/AzureDevOps.Authentication/Src/Authentication.cs#L421

Would that work for you?

**Comment by JarekToro** [comment]
Thank you it looks promising.

**Comment by grayjeremy** [comment]
@JarekToro Did this work for you?

**Comment by grayjeremy** [comment]
Rats, now I have to try :)

**Comment by chcomley** [comment]
Hi @JarekToro and @grayjeremy, please let me know whether you need any further help with this...
