### ISSUE TITLE
In TFS 2018, I do not see "Deploy: WinRM - IIS Web App Deployment"

### ISSUE THREAD

**Issue by RubixRevenge** [MicrosoftDocs/vsts-docs#257]
In TFS 2018, I do not see "Deploy: WinRM - IIS Web App Deployment". Even choosing "All" in the "Add Tasks" pane, I do not see it. I see "Deploy: Windows Machine File Copy", but not "Deploy: WinRM - IIS Web App Deployment".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6037c0a7-9595-eff1-3f5c-2607baa73c4d
* Version Independent ID: 7b8cf300-4d91-ac77-3ffd-ef1a83c79af7
* [Content](https://docs.microsoft.com/en-us/vsts/build-release/apps/cd/deploy-webdeploy-iis-winrm)
* [Content Source](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/build-release/apps/cd/deploy-webdeploy-iis-winrm.md)
* Service: unspecified

**Comment by alexhomer1** [comment]
Did you install the extension as described in the topic.

>>IIS WinRM extension
Install the IIS Web App Deployment Using WinRM extension from Visual Studio Marketplace to your VSTS account or TFS.<<
https://marketplace.visualstudio.com/items?itemName=ms-vscs-rm.iiswebapp

**Comment by elonmallin** [comment]
I only see it in the marketplace and it says it's installed but I can't use it. My repo is GIT. That seems to be the problem since I can use it with my TFVC repos. Is it just not supported for GIT repos or?
