### ISSUE TITLE
Add documentation around using npm install -g in Linux environments

### ISSUE THREAD

**Issue by alexmullans** [MicrosoftDocs/vsts-docs#2570]
Per https://developercommunity.visualstudio.com/content/problem/382704/cannot-use-npm-global-install-on-ubuntu-1604.html, it'd be good to update this page (specifically the "Install tools" section and any other sections that reference `npm install -g`) to note that when building on Linux, it's necessary to add `sudo` to `npm install -g` commands.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c99686eb-6c78-0336-1ec3-802a53c9868d
* Version Independent ID: 6eaf1acb-24d4-5bb7-3935-17abe7e59dd9
* Content: [Building JavaScript and Node.js apps with Azure Pipelines or TFS - Azure Pipelines & TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/languages/javascript?view=vsts&tabs=yaml)
* Content Source: [docs/pipelines/languages/javascript.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/languages/javascript.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by DavidStaheli** [comment]
Done.  It should be in production later today.
