### ISSUE TITLE
Stakeholders cannot view code published as a wiki

### ISSUE THREAD

**Issue by schmalls** [MicrosoftDocs/vsts-docs#2571]
This page states that *Anyone with access to the team project, including stakeholders, can view the wiki*, but I have found no way to make that happen. In fact, there [are](https://visualstudio.uservoice.com/forums/330519-visual-studio-team-services/suggestions/33980284-allow-stakeholders-to-view-wikis-published-from-co) [several](https://github.com/MicrosoftDocs/vsts-docs/issues/1602) [places](https://developercommunity.visualstudio.com/content/idea/365939/allow-stakeholders-to-view-wikis-published-from-co.html) that mention that it will not be implemented. So this document needs to be fixed or preferably stakeholders should be able to view code published as a wiki.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8d4fe5c7-0ab6-a0e4-4a6e-f98d0355f49a
* Version Independent ID: ce022fef-054d-cdc2-43e9-a8ee3b8fb592
* Content: [Publish markdown files from a Git repository to a wiki in Azure DevOps - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/project/wiki/publish-repo-to-wiki?view=vsts&tabs=new-nav)
* Content Source: [docs/project/wiki/publish-repo-to-wiki.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/project/wiki/publish-repo-to-wiki.md)
* Product: **devops**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Thanks @schmalls, I'm following up on this and have created a work item in my backlog for updates (fixes). To be completed S145 or S146. Thanks again!
