### ISSUE TITLE
How can the commit not exist?

### ISSUE THREAD

**Issue by MisinformedDNA** [MicrosoftDocs/vsts-docs#2572]
I don't understand this statement:

> The commit may not exist when the agent attempts to check it out.

How can it not exist? Further up it says

> the branch to build is resolved to a commit ID

So we get a commit ID and then try to checkout that commit ID, but it is no longer there? How does that happen? Is there an issue to fix this?

I only care about my latest code, so a shallow fetch with depth 1 sounds awesome, but not if it's going to cause other problems.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 800c5477-b39f-48e6-6f9c-aa7994b2ec2a
* Version Independent ID: db9e2e97-d44d-734e-6a6f-b01f60f01c95
* Content: [Pipeline options for Git repositories - Azure Pipelines & TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/pipeline-options-for-git?view=vsts)
* Content Source: [docs/pipelines/repos/pipeline-options-for-git.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/repos/pipeline-options-for-git.md)
* Product: **devops**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by MisinformedDNA** [comment]
Based on [this issue](https://developercommunity.visualstudio.com/content/problem/373462/git-get-sources-shallow-fetch-is-broken-subject-to.html) I found, the problem is that Azure DevOps is grabbing the last n commits based on HEAD and not based on the actual commit ID.

**Comment by steved0x** [comment]
@MisinformedDNA Thanks for letting us know, I'll check into it, and see if we can add a note in the meantime until such a time as there is a resolution.

**Comment by jwisener** [comment]
this is broken
