### ISSUE TITLE
Work Item Link in Table

### ISSUE THREAD

**Issue by ksix** [MicrosoftDocs/vsts-docs#2574]
When putting a work item reference in table it fails to render if I don't have at least 1 space on both sides of the reference. For example:
|#1| renders as "#1"
| #1 | renders as "Epic 1: Title"
Is this expected or a bug? Please update the documentation if it is expected, or fix if it is a bug.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fa622358-f5bb-1f5c-177a-081a37b6acef
* Version Independent ID: 72f7fd16-a822-66c8-3a34-8905645ce5f2
* Content: [Markdown syntax for files, widgets, and wikis in Azure DevOps - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/project/wiki/markdown-guidance?view=vsts)
* Content Source: [docs/project/wiki/markdown-guidance.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/project/wiki/markdown-guidance.md)
* Product: **devops**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Thanks @ksix I'm following up on this and will keep you updated.

**Comment by chcomley** [comment]
@ksix The documentation has been updated and should be live by sometime this afternoon. Thank you.
