### ISSUE TITLE
Native support of rollup does not work in VSTS currently.

### ISSUE THREAD

**Issue by BruceLofland** [MicrosoftDocs/vsts-docs#2581]
Native support of rollup is not a feature of VSTS apparently.  I have tried following these directions and it does not work and does not give an error.  I am switching to VSTS Rollup.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f6ed3f5-b5a4-10a9-f823-8591da27096d
* Version Independent ID: 1e955842-c971-2e15-777f-bbb95096698a
* Content: [Support rollup of work and other fields - Azure DevOps & TFS](https://docs.microsoft.com/en-us/azure/devops/reference/xml/support-rollup-of-work-and-other-fields?view=vsts)
* Content Source: [docs/reference/xml/support-rollup-of-work-and-other-fields.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/reference/xml/support-rollup-of-work-and-other-fields.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by neraath** [comment]
Agreed. I'm trying to get rollups for Completed Work at a User Story level, and I cannot get it to work.

The documentation references specific field type names, but when I dug into the labyrinth of docs on how to edit the User Story work item definition, I found we can't use witadmin for Azure DevOps for modifying the work item definition. 

Please add this capability to VSTS or correct the documentation.
