### ISSUE TITLE
How do I specify "always latest" task version in YAML?

### ISSUE THREAD

**Issue by JustinGrote** [MicrosoftDocs/vsts-docs#2582]
This documentation needs to be here. Do I do PublishTestResults@0? PublishTestResults@99? Some other special syntax?

Further, the task list referenced doesn't show that available versions there are. Where do I go to find this information?

Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8098f527-ebdf-60d5-3989-5228b7a207c1
* Version Independent ID: ce27c817-9599-00ef-5af2-3ac1dbad8dc6
* Content: [Build and Release Tasks in Azure Pipelines and TFS - Azure Pipelines & TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/tasks?view=vsts&tabs=yaml)
* Content Source: [docs/pipelines/process/tasks.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/tasks.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by andyjlewis** [comment]
I realize this might not answer all you questions, but see if this helps: https://docs.microsoft.com/en-us/azure/devops/pipelines/process/tasks?view=vsts&tabs=yaml#task-versions

**Comment by vtbassmatt** [comment]
Actually, it's not "can specify the major version". It's "must specify". I'll get that fixed.

We considered doing a feature to let you opt into "@latest", but it really doesn't have a good use case. We only major-version tasks when things break, so you're by definition opting into having your builds break at a task author's whim.

**Comment by JustinGrote** [comment]
Thanks @vtbassmatt, that makes sense. Right now the tasks don't list what versions are available without going to designer which is very point-and-clicky, I had to go to the Github Tasks repository for a quick reference. A table of tasks and available versions would be nice. When writing a yaml "from scratch" it was pretty annoying to hunt this info down, it should be readily available.

**Comment by JustinGrote** [comment]
@andyjlewis you do realize that I am literally filing an issue on the document you referenced right? :)

**Comment by vtbassmatt** [comment]
Agreed, and we're working to make that better. There will be some web UI coming soon, but also have you tried our [VS Code extension](https://marketplace.visualstudio.com/items?itemName=ms-azure-devops.azure-pipelines)?

**Comment by JustinGrote** [comment]
I have not! Thanks for the heads up.

**Comment by andyjlewis** [comment]
Got it. I was moving too fast while scanning the content source field and so thought this issue targeted a different doc. Thanks for reporting the issue.
