### ISSUE TITLE
Gradle 5.0 has error on Mac OS X Hosts

### ISSUE THREAD

**Issue by ThadHouse** [MicrosoftDocs/vsts-docs#2583]
Starting with Gradle 5.0, Hosted Mac OS Gradle builds fail during configuration. One of the initialize scripts uses a class that does not exist anymore in Gradle. 

Attached in the failure, and this happens on a basic project using the Gradle Wrapper for 5.0.

[MacGradleLog.txt](https://github.com/MicrosoftDocs/vsts-docs/files/2621153/MacGradleLog.txt)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 00499395-fdc3-b150-3469-aee2f9fb7cbc
* Version Independent ID: 44e630e1-1689-2d2e-212b-3ce2baf8771f
* Content: [Gradle build and release task - Azure Pipelines & TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/gradle?view=vsts)
* Content Source: [docs/pipelines/tasks/build/gradle.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/build/gradle.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by marcphilipp** [comment]
That's due to a change in 5.0:

> The internal `org.gradle.util` package is no longer imported by default.

You can either import it or use the fully-qualified class name.

**Comment by DavidStaheli** [comment]
Thanks a lot for the help, @marcphilipp.  @ThadHouse, thanks for creating this issue and making us aware.  I'll close this for now, but please reopen if there's anything we can do to help.

**Comment by ThadHouse** [comment]
@DavidStaheli This issue is a problem on the azure build environment side, not anything done by the user script.

Gradle automatically applies any gradle scripts included in `~/.gradle/init.d`. On the mac instances, there is a script included `/Users/vsts/.gradle/init.d/log-gradle-version-plugin.gradle` that no longer works with gradle 5.0. That script is installed with the build instance, so any users using gradle 5.0 on mac will have broken builds. So this is an issue that needs to be fixed on your side.

**Comment by joshmgross** [comment]
@ThadHouse This was also reported here: https://github.com/Microsoft/azure-pipelines-tasks/issues/8918

Until we get this fixed, the workaround is to delete that script. Something like:
 ```
- task: DeleteFiles@1
    inputs:
      sourceFolder: '/Users/vsts/.gradle/init.d/'
      contents: 'log-gradle-version-plugin.gradle'
```
Thanks for the help isolating this issue!

**Comment by syendev** [comment]
> @ThadHouse This was also reported here: [microsoft/azure-pipelines-tasks#8918](https://github.com/microsoft/azure-pipelines-tasks/issues/8918)
> 
> Until we get this fixed, the workaround is to delete that script. Something like:
> 
> ```
> - task: DeleteFiles@1
>    inputs:
>      sourceFolder: '/Users/vsts/.gradle/init.d/'
>      contents: 'log-gradle-version-plugin.gradle'
> ```
> 
> Thanks for the help isolating this issue!

This doesn't work, I am getting the following error:
```
/azure-pipelines.yml: (Line: 14, Col: 11, Idx: 299) - (Line: 14, Col: 11, Idx: 299): Mapping values are not allowed in this context.
```
