### ISSUE TITLE
Please document the build variable populated by the task

### ISSUE THREAD

**Issue by kvpt** [MicrosoftDocs/vsts-docs#2584]
I wanted to use the nuget installed by this task in a later task.
So I needed the variable populated by this task that contains the path of the nuget executable.
I searched in the documentation and found nothing about it.
So I went on Github to find in the source code that the build variable populated was **NuGetExeToolPath**.
Please add this information to the documentation.

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2d4861e9-3c5e-ccc8-6918-f5a7327de545
* Version Independent ID: 8681cf86-9935-2063-ab5d-7ece1e14a2b1
* Content: [NuGet Tool Installer task - Azure Pipelines & TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/nuget?view=vsts)
* Content Source: [docs/pipelines/tasks/tool/nuget.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/tool/nuget.md)
* Product: **devops**
* GitHub Login: @erickson-doug
* Microsoft Alias: **amullans**

**Comment by alexmullans** [comment]
There's no need to use the `NuGetExeToolPath` variable. The Tool Installer tasks add the tool to the PATH directly, so you can just call `nuget [arguments]` in a script.

**Comment by kvpt** [comment]
Hum ..., It's been a while since I done this task but I'm remember that it did not work properly.
I will recheck this tomorrow.

**Comment by kvpt** [comment]
Ok it works for me.
Thank you.

**Comment by kw4k10** [comment]
hello some people can me tell anything aboutthis githube ??
