### ISSUE TITLE
artifactFeeds attribute not working

### ISSUE THREAD

**Issue by abhij22** [MicrosoftDocs/vsts-docs#2586]
When I define the task as following in my .vsts-ci.yaml
```
- task: TwineAuthenticate@0
  inputs:
    artifactFeeds: XXXXXX
```
 I get Successfully added auth for 0 internal feeds and 0 external endpoint.

I was able to get it to work by using `feedList` instead of `artifactFeeds`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 726683ec-c811-46b7-17d6-527fbafaf8d0
* Version Independent ID: 6d964146-88fb-1975-1263-4d4f6584a03a
* Content: [Python Twine Upload Authenticate - Azure Pipelines & TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/package/twine-authenticate?view=vsts)
* Content Source: [docs/pipelines/tasks/package/twine-authenticate.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/package/twine-authenticate.md)
* Product: **devops**
* GitHub Login: @erickson-doug
* Microsoft Alias: **elbatk**

**Comment by elbatk** [comment]
Hmm, I'm wondering why this was the case for you, @abhij22 . Maybe this was a product bug that we've fixed? Adding @mitchdenny for clarification, because from what I see, the docs show the correct command (the one that didn't work for you).

**Comment by mitchdenny** [comment]
Can you provide an example of what value you had under ```artifactFeeds:```?

**Comment by abhij22** [comment]
I had the name of our Azure Devops PyPi repo. We continue to use `feedList` as of today.

**Comment by chasewilson** [comment]
@abhij22 I appreciate you taking the time to give feedback. I think this issue was fixed. However, I want to make sure you are no longer having this issue. If you have any more feedback, please reach out and I'll get back to you ASAP

**Comment by perbu** [comment]
FWIW I have the same exact problem. 
```
- task: TwineAuthenticate@1
  inputs:
    artifactFeed: twine-feed/py-objectstore
  displayName: 'Authenticate twine'
```
And I get
```
Successfully added auth for 0 internal feeds and 0 external endpoint.
```
After this the file pointed at by $PYPIRC_PATH contains:
```
[distutils]
index-servers=
```

The whole pipeline is at https://github.com/arkivverket/py-objectstore/blob/2dcfc8cb0c2070639b0df6936ecbbf743384f3e6/azure-pipelines.yml

It's all OSS so no worries about sharing. I'll come back to this on Friday and see if I can make sense of it then, but so far I've had no success. This is the only relevant hit Google can give me.

**Comment by perbu** [comment]
I've got my TwineAuthenticate working. So, if anyone else stumbles upon this what I did wrong was the following.

I used feed/endpoint as the artifactFeed. But the feed is project/feed. And there is no validation on the artifactFeed so if it is invalid there is no error shown to the user.

Another thing that confused me a bit was that TwineAuthenticate@1 says you're supposed to give twine "-r feed/endpoint". This didn't work for me. It can only take the feed as a parameter as the feed is referencing the pypirc file.

**Comment by fuglede** [comment]
I came across this one because `PipAuthenticate@1` returned the same result; "Successfully added auth for 0 internal feeds and 0 external endpoint."

In my case, the issue was that I had used `artifactFeed` instead of `artifactFeeds`. It's pretty confusing that you need to do exactly the opposite compared to `TwineAuthenticate@1`, which wants you to drop the plural when you only have one feed.
