### ISSUE TITLE
Missing YAML documentation for Task Control Options

### ISSUE THREAD

**Issue by JohnMichaelMiller** [MicrosoftDocs/vsts-docs#2587]
Where are is the YAML documentation for the task control options? I need to run a publish test results task even when a test fails.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8098f527-ebdf-60d5-3989-5228b7a207c1
* Version Independent ID: ce27c817-9599-00ef-5af2-3ac1dbad8dc6
* Content: [Build and Release Tasks in Azure Pipelines and TFS - Azure Pipelines & TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/tasks?view=vsts&tabs=yaml)
* Content Source: [docs/pipelines/process/tasks.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/tasks.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by andyjlewis** [comment]
https://docs.microsoft.com/en-us/azure/devops/pipelines/process/conditions?view=vsts&tabs=yaml I believe should give you what we need. Looks like we might need to integrate the topics a little better.

**Comment by PatrickGrub** [comment]
On the [Conditions[https://docs.microsoft.com/en-us/azure/devops/pipelines/process/conditions?view=vsts&tabs=yaml) page it says to use `condition:` after the `job`, but the initial question is about a condition on a `task`.

Do you mean I can use the `condition` on a `task` the same way like on the `job`?

### Same here "I need to run a publish test results task even when a test fails."

**Comment by vtbassmatt** [comment]
I just completed a PR to fix the original issue (with the tasks topic). I can also see how the conditions topic is confusing; will think about ways to improve.
