### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by danielgary** [MicrosoftDocs/vsts-docs#259]
This URL doesn't appear to be valid anymore: https://app.vssps.visualstudio.com/app/register

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ac47cbcf-45ed-81aa-b532-e7ad0046658e
* Version Independent ID: 7aa1f60e-069f-3d62-5cac-b65e4b1116ef
* [Content](https://docs.microsoft.com/en-us/vsts/integrate/get-started/authentication/oauth)
* [Content Source](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/integrate/get-started/authentication/oauth.md)
* Service: unspecified

**Comment by elbatk** [comment]
Hi @danielgary ! Thanks for this, a fix is in flight for this issue and the new URL for the fix is: https://app.vsaex.visualstudio.com/app/register
