### ISSUE TITLE
Importing backlogs from excel in tree format

### ISSUE THREAD

**Issue by codenamekarna** [MicrosoftDocs/vsts-docs#2591]
Hi
I have downloaded backlogs from one organization in azure devops using queries in tree format. 
I want to upload this to another organization, the input list allows only flat file format excel for upload. Is it possible to upload backlogs using tree format?

Also is it possible to migrate backlog history in any way to another organization?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 505849d3-01c8-a2cd-dc6c-271dd1120e2d
* Version Independent ID: 577fc252-60e4-f670-bb92-6bdbcb7d5c69
* Content: [Bulk modify using Excel - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/backlogs/office/bulk-add-modify-work-items-excel?view=vsts)
* Content Source: [docs/boards/backlogs/office/bulk-add-modify-work-items-excel.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/boards/backlogs/office/bulk-add-modify-work-items-excel.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@codenamekarna - Thank you for your inquiry. You can input a tree list. This is documented in the article your reference, https://docs.microsoft.com/en-us/azure/devops/boards/backlogs/office/bulk-add-modify-work-items-excel?view=vsts#add-linked-backlog-items-and-tasks, by choosing the Add tree Level to add the hierarchy to the list. 

As for migrating backlog history to another organization - no that is not possible.
