### ISSUE TITLE
VSTS is now Azure DevOps

### ISSUE THREAD

**Issue by thommck** [MicrosoftDocs/vsts-docs#2594]
The rebrand to Azure DevOps has completely changed the UI. Will the resources here be updated to cover that (and legacy ones removed)?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5f8713f1-4602-9394-26a3-34b7dca62093
* Version Independent ID: 5f5f6f3a-d9eb-3c27-d779-779c81e67865
* Content: [DevOps Resources - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/learn/events-and-talks/index)
* Content Source: [https://mseng.visualstudio.com/DefaultCollection/TechnicalContent/_git/devops-learn-pr?path=%2fdocs%2fevents-and-talks%2findex.md&version=GBlive&_a=contents](https://mseng.visualstudio.com/DefaultCollection/TechnicalContent/_git/devops-learn-pr?path=%2fdocs%2fevents-and-talks%2findex.md&version=GBlive&_a=contents)
* Product: **devops**
* Git Login: **Dan Hellem**
* Microsoft Alias: **samgu**

**Comment by steved0x** [comment]
@thommck It looks like this page hasn't been updated with the most recent talks and presentations, I'll send a note. Do you think we should take the legacy stuff out? Or maybe add a note to explain that while the concepts may be current, the Demos and UI may be outdated?

**Comment by thommck** [comment]
Personally I think you should remove the legacy stuff as you can't get the old version anymore AFAIA.
If the concepts stay true then leave that there until you can fully update it

Thanks,
Thom McKiernan

Sent from 07468 473239

________________________________

**Comment by dmckinstry** [comment]
Thanks @thommck and @steved0x - You are absolutely right.  We just noticed this internally as well and will pick it back up.

**Comment by thomps23** [comment]
This appears to have been refreshed.
