### ISSUE TITLE
Broken Link - 404 - Artifacts

### ISSUE THREAD

**Issue by wgv-srsedate** [MicrosoftDocs/vsts-docs#2596]
Under the "Azure Artifacts" section, clicking the "unlist or remove a package" link results in a 404 error.  There is nowhere in the ADO documentation that defines what unlisting means and when it is appropriate to unlist or deprecate a package.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c00c80cb-e1fa-8af1-25a7-0e1fd679b879
* Version Independent ID: 51baa23d-66da-3d19-ddc7-56c101e9e09d
* Content: [Feature overview for Azure DevOps - Azure DevOps Services & TFS](https://docs.microsoft.com/en-us/azure/devops/user-guide/alm-devops-features?view=vsts)
* Content Source: [docs/user-guide/alm-devops-features.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/user-guide/alm-devops-features.md)
* Product: **devops**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by steved0x** [comment]
@wgv-srsedate Thank you for letting us know. Does this information help? [Delete packages from Azure Artifacts feeds
](https://docs.microsoft.com/en-us/azure/devops/artifacts/how-to/delete-and-recover-packages?view=vsts&tabs=maven%2Cnew-nav#delete-packages-from-azure-artifacts-feeds)

We can get that broken link fixed.

**Comment by wgv-srsedate** [comment]
Not exactly, because there's clearly a difference between **unlisting** a package and **deleting** one.  I came to the documentation to try and understand what that difference was, since those are two different commands.

**Comment by chcomley** [comment]
Thanks @wgv-srsedate I'm following up on this and will keep you updated.

**Comment by steved0x** [comment]
@chcomley When you get this sorted please ping me, there are some redirects going to that 404 that I need to fix up.

**Comment by chcomley** [comment]
Thanks for your patience, @wgv-srsedate. The fix has been published. Thank you!
