### ISSUE TITLE
Output variables not working with multi-job scenarios in designer pipelines?

### ISSUE THREAD

**Issue by mganeshphani** [MicrosoftDocs/vsts-docs#2600]
Does the designer support this?
https://github.com/Microsoft/azure-pipelines-agent/blob/master/docs/preview/outputvariable.md

I wonder it should, as this link is mentioned in designer task output section in pipelines.. but not working as mentioned in the doc

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd7e0bd3-1f7d-d7b6-cc72-5ef63c31b46a
* Version Independent ID: dae87abd-b73d-9120-bcdb-6097d4b40f2a
* Content: [Pipeline variables - Azure Pipelines & TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=vsts&tabs=designer%2Cbatch)
* Content Source: [docs/pipelines/process/variables.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/variables.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by vijayma** [comment]
There is no way to pass output variables from one job to another using designer. YAML builds support this.
