### ISSUE TITLE
Release Variables In Service Connections

### ISSUE THREAD

**Issue by keggster101020** [MicrosoftDocs/vsts-docs#2601]
Hi, I'm trying to add a service connection to use in a release task. 
I would like to populate a field of the service connection with a release variable populated from another release task (say key vault). 

Is it possible to pass release variables to service connections? 

thanks!

**Comment by steved0x** [comment]
@keggster101020 Thank you for the feedback. Can you let me know which article this feedback is for (or which article was missing the steps you needed), so I can assign it to the author? You can reply here with the URL of the topic, or you can create a new issue by browsing to the topic on docs.microsoft.com and choosing **Content feedback** at the bottom. 

![image](https://user-images.githubusercontent.com/1580889/42953695-fd174150-8b48-11e8-94de-26924ca79c71.png)

**Comment by steved0x** [comment]
@alexhomer1 Do you know any details about this, or know who might?

**Comment by RoopeshNair** [comment]
> I would like to populate a field of the service connection with a release variable populated from another release task (say key vault).

I presume, you're trying to update the fields of service connection from a variable and not the service connection itself. If yes, have you tried `##vso[task.setendpoint]value`? check out the agent l[ogging commands](https://github.com/Microsoft/azure-pipelines-tasks/blob/master/docs/authoring/commands.md)

If you intend the latter, that is setting the service connection as a variable, then it is not supported.
