### ISSUE TITLE
Agile

### ISSUE THREAD

**Issue by alejagapatrick10** [MicrosoftDocs/vsts-docs#2602]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 409050e0-dac3-9619-bf5c-f4189229e309
* Version Independent ID: 8dcdbacc-8886-9a72-f033-6052a3e56ebd
* Content: [What is Agile? - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/learn/agile/what-is-agile)
* Content Source: [https://mseng.visualstudio.com/DefaultCollection/TechnicalContent/_git/devops-learn-pr?path=%2fdocs%2fagile%2fwhat-is-agile.md&version=GBlive&_a=contents](https://mseng.visualstudio.com/DefaultCollection/TechnicalContent/_git/devops-learn-pr?path=%2fdocs%2fagile%2fwhat-is-agile.md&version=GBlive&_a=contents)
* Product: **devops**
* Git Login: **samgu**
* Microsoft Alias: **abjork**

**Comment by steved0x** [comment]
@alejagapatrick10 Thank you for leaving feedback. It looks like your comments were lost. Can you create a new issue with your feedback? Thank you.
