### ISSUE TITLE
Example projects

### ISSUE THREAD

**Issue by KristoferMar** [MicrosoftDocs/vsts-docs#2603]
Do you have any example projects where you make use of the Core SDK just do demonstrate how the different methods can be used?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f699a190-5e7e-1103-8d9d-c3d58e698e3a
* Version Independent ID: 1e54fe20-7e4d-d5ff-1682-8659f7a8fba8
* Content: [Core Client SDK](https://docs.microsoft.com/en-us/azure/devops/extend/reference/client/core-sdk?view=vsts)
* Content Source: [docs/extend/reference/client/core-sdk.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/extend/reference/client/core-sdk.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by elbatk** [comment]
Hi @KristoferMar , have you seen this article for how to call a REST API? https://docs.microsoft.com/en-us/azure/devops/extend/develop/call-rest-api?view=azure-devops

I'm not sure if we have example projects where we use the Core SDK. You could try looking through our sample extensions: https://docs.microsoft.com/en-us/azure/devops/extend/develop/samples-overview?view=azure-devops. Going to close this as I'm trying to clean up the backlog, but please let me know if this isn't what you're looking for.
