### ISSUE TITLE
Not clear about where to put the task.json file

### ISSUE THREAD

**Issue by xtu** [MicrosoftDocs/vsts-docs#2604]
It reads 'Next, we will create a task.json file in the root directory' but it feels like implies that it should be in 'buildAndReleaseTask' folder.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 44581f4a-93df-7507-3844-eadedf9a6cc4
* Version Independent ID: 33c7bcf0-1512-975f-5ef8-9f2a192a84ad
* Content: [Add a Build or Release Task](https://docs.microsoft.com/en-us/azure/devops/extend/develop/add-build-task?view=vsts)
* Content Source: [docs/extend/develop/add-build-task.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/extend/develop/add-build-task.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by mikederksen** [comment]
In the example-json for the task.json it says:

"categories": [
        "Azure Pipelines"
    ],

When deploying this to the marketplace, I'm given the error "The task.json for contribution buildAndReleaseTask could not be deserialized.Unexpected character encountered while parsing value: [. Path 'category', line 7, position 17"

Changing the category to "category": "Azure Pipelines" fixes this issue

**Comment by elbatk** [comment]
Hi @xtu , you're right, it should be in the buildAndReleaseTask folder, fixing now to make it a bit more clear.

**Comment by patros** [comment]
@elbatk  this is still a problem

**Comment by elbatk** [comment]
@patros thank you! I believe the PR that fixed this got mixed up over the holidays, actually fixing now. Appreciate you helping me out!

**Comment by elbatk** [comment]
@patros I agree, this is meant to be a beginner's guide so I feel like things should be explicit. I'm also adding a line under Step 1 that says every part of the Step should be done within the buildAndReleaseTask folder.

**Comment by patros** [comment]
Apologies for the piece meal feedback, I'm just working through it right now, but I think the start of step 2 should be under buildAndReleaseTask too.
