### ISSUE TITLE
Needs to be updated

### ISSUE THREAD

**Issue by KristoferMar** [MicrosoftDocs/vsts-docs#2605]
When i get the user i get the following members.
- Email:   string
- Id:   string
- Name:   string
- subjectId:   string
- subjectType:   string
- uniqueName:   string

does the documentation need an update? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f199a03-2fed-96f5-3b9c-afcb9e5d5ff6
* Version Independent ID: 5696ec2b-fa78-1d8a-d8bd-be0c0efdfb35
* Content: [VSS/References/SDK.Interfaces UserContext API](https://docs.microsoft.com/en-us/azure/devops/extend/reference/client/api/vss/references/sdk_interfaces/usercontext?view=vsts)
* Content Source: [docs/extend/reference/client/api/VSS/References/SDK_Interfaces/UserContext.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/extend/reference/client/api/VSS/References/SDK_Interfaces/UserContext.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by elbatk** [comment]
Hi @KristoferMar , yes, these APIs are older and are not updated anymore. Is there any reason you would need to use the older APIs instead of the new ones here? https://docs.microsoft.com/en-us/rest/api/azure/devops/?view=azure-devops-rest-5.0&viewFallbackFrom=vsts-rest-4.1

**Comment by KristoferMar** [comment]
Hi @elbatk no it's alright i found another solution.
Thank you for responding.

**Comment by elbatk** [comment]
Ah okay, I"m glad you found something @KristoferMar that worked for you. Going to close this one, cheers!
