### ISSUE TITLE
Parallel build (/m) on hosted agent

### ISSUE THREAD

**Issue by 24mu13** [MicrosoftDocs/vsts-docs#2606]
Is not clear if setting the parallel build (MSBuild/Windows only) is actually working for hosted agent.
Most importantly, it this may affect the performance.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 99af681d-41ad-da15-0b72-08b5cd5a11ac
* Version Independent ID: 2fa0df36-a437-8cbb-b019-b49b31b1e116
* Content: [Microsoft-hosted agents for Azure Pipelines - Azure Pipelines & TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=vsts&tabs=yaml)
* Content Source: [docs/pipelines/agents/hosted.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/agents/hosted.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by andyjlewis** [comment]
Is your project private? If so, do you have sufficient parallel jobs? see https://docs.microsoft.com/en-us/azure/devops/pipelines/licensing/concurrent-jobs-vsts

**Comment by vtbassmatt** [comment]
The hosted agents have 2 virtual cores. Parallel build may or may not offer you a speedup depending on how I/O-bound vs CPU-bound your build is.
