### ISSUE TITLE
Attachment links to work items is missing a key point

### ISSUE THREAD

**Issue by dalemyers** [MicrosoftDocs/vsts-docs#2607]
When you want to add an attachment to a work item, you first upload said attachment, then link the attachment to the work item. However, it does not specify that you _MUST_ have a comment in the link for these. 

All other link types do not require a comment. Only this one requires it. 

Should you miss out the comment, you get the unexpected issue of your attachment linking, but being set to 0KB and you cannot view it. 

It should be specified that you _MUST_ have a comment in the link operation. e.g.:

    {
        "op": "add",
        "path": "/relations/-",
        "value": {
            "rel": "AttachedFile",
            "url": "https://attachment.url/goes/here",
            "attributes": {
                "comment": "This can be whatever you want. Even empty."
            }
        }
    }

**Comment by steved0x** [comment]
@dalemyers Thank you for the feedback, do we need to fix our reference documentation for this? Can you let me know the URL of the documentationt hat was in error, so I can forward this to the author?

**Comment by dalemyers** [comment]
There isn't really a dedicated page for this. It's spread out. I think it's actually a bug, but I don't know how or where to report it.

**Comment by steved0x** [comment]
@dalemyers If you think it is a bug, you can report it here: https://developercommunity.visualstudio.com/spaces/21/index.html

This will go right to the product team and they'll take a look. Thanks for letting us know.

**Comment by dalemyers** [comment]
Whether it is a bug or not, the documentation doesn't align with the actual behavior. I believe it should be updated to reflect the current behavior for now.
