### ISSUE TITLE
I'm getting Cannot convert null to type "System.Net.SecurityProtocolType error

### ISSUE THREAD

**Issue by itaccounts-sw** [MicrosoftDocs/vsts-docs#2608]
I tried this command: [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12

This is result: Exception setting "SecurityProtocol": "Cannot convert null to type "System.Net.SecurityProtocolType" due to
enumeration values that are not valid. Specify one of the following enumeration values and try again. The possible
enumeration values are "Ssl3, Tls"."

Tried Tls and that does not work. What do I need to do to get this target registered?

**Comment by steved0x** [comment]
@itaccounts-sw Thank you for the feedback. Can you let me know which article this feedback is for, so I can assign it to the author? You can reply here with the URL of the topic, or you can create a new issue by browsing to the topic on docs.microsoft.com and choosing **Content feedback** at the bottom. 

![image](https://user-images.githubusercontent.com/1580889/42953695-fd174150-8b48-11e8-94de-26924ca79c71.png)

**Comment by itaccounts-sw** [comment]
This issue can be closed.
