### ISSUE TITLE
Missing documentation for Argument flattenFolder

### ISSUE THREAD

**Issue by propellor** [MicrosoftDocs/vsts-docs#2609]
Hi, 
I'm not finding any documentation for Argument flattenFolder, you may want to add it.
Thanks,
Sam

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 81f02378-b85b-d3a4-d3c8-f07d935367da
* Version Independent ID: fab57f76-35d2-4024-6f7f-1740d7b24743
* Content: [Copy Files task - Azure Pipelines & TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/copy-files?view=vsts&tabs=yaml)
* Content Source: [docs/pipelines/tasks/utility/copy-files.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/utility/copy-files.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by elbatk** [comment]
Ah, yes. Thanks @propellor . This is the description in the product: "Flatten the folder structure and copy all files into the specified target folder." I'll add it to the docs :)

**Comment by tene666** [comment]
However, flatten folder is not available in TFS 2015, so TFS 2015 version of this page should not show it
