### ISSUE TITLE
Navigation Title is Incorrect

### ISSUE THREAD

**Issue by jbramwell** [MicrosoftDocs/vsts-docs#261]
The title in the treeview under "Tutorials" is shown as "Content VSTS account to AAD" whereas "Content" should likely be "Connect" (to match with the actual document title).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f56d653-f3ed-88a3-c307-1ba6eec6cbc2
* Version Independent ID: 5f5b1c72-7b2a-a7cf-aea7-39cf84b11005
* [Content](https://docs.microsoft.com/en-us/vsts/accounts/connect-account-to-aad)
* [Content Source](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/accounts/connect-account-to-aad.md)
* Service: unspecified

**Comment by steved0x** [comment]
@jbramwell Thanks for letting us know, you are correct, and this issue is fixed. Thank you!
