### ISSUE TITLE
How to auth using PAT over 90 days ? 

### ISSUE THREAD

**Issue by spike008t** [MicrosoftDocs/vsts-docs#2612]
Hello,

As the documentation said, we can use PAT to be able to avoid renew the token every 90 days to access to npm feeds. But when I follow the documentation, I still have a 401 on `npm install`.

The documentation tell to add the following lines on `~/.npmrc`:

```
//pkgs.dev.azure.com/<yourorganization>/_packaging/<yourfeed>/npm/registry/:username=YOUR-USERNAME
//pkgs.dev.azure.com/<yourorganization>/_packaging/<yourfeed>/npm/registry/:_password=BASE64-ENCODED-PAT-GOES-HERE
//pkgs.dev.azure.com/<yourorganization>/_packaging/<yourfeed>/npm/registry/:email=YOUREMAIL@EXAMPLE.COM
//pkgs.dev.azure.com/<yourorganization>/_packaging/<yourfeed>/npm/registry/:always-auth=true
```

Questions:

1. The strange thing is the url for registry on `.npmrc` project file is not the same as decribe (eg: `registry=https://<organization>.pkgs.visualstudio.com/_packaging/<feed>/npm/registry/`)
2. What should I use as username? I did try the organization name, my email even the email prefix before the `@`, but nothing works...

I did try to set both URL, but nothing works...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cb7c2ab6-4ba1-51d5-96bb-38a9ab6b50c3
* Version Independent ID: 415de875-ba1b-476b-f08b-1a61dc7a2747
* Content: [Set up your client's npmrc](https://docs.microsoft.com/en-us/azure/devops/artifacts/npm/npmrc?view=vsts&tabs=new-nav%2Cwindows)
* Content Source: [docs/artifacts/npm/npmrc.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/artifacts/npm/npmrc.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by spike008t** [comment]
@elbatk thank you for your answer.

1. I do not have the right on my org, I'll ask to the manager to turn it on.

**Comment by elbatk** [comment]
I've made that change more clear in the docs in a PR today, @alexmullans . I'm assuming you're trying to say what's between the `&lt;` and `&gt;`.

**Comment by alexmullans** [comment]
Yep, sorry. Fixed my comment.

**Comment by spike008t** [comment]
@alexmullans thank you for your response. I did give a try, but nothings
works...
Of couse i did set the correct value on the placeholder (orgs and feed
name). I've also try to update the npm to the latest version, nothing.

Le jeu. 29 nov. 2018 à 21:42, Alex Mullans <notifications@github.com> a
écrit :

**Comment by visargashi** [comment]
@alexmullans, I have been trying to get this working for two days as well, I keep getting 401s even after setting everything up as documented. A few questions:
1. Why does the PAT npmrc section say "JSON" when the file is not JSON (or is it?)?
2. I have tried using the generated PAT as a password using basic authentication against the NPM url, and I get a response (using a random username). I am not clear on how the PAT is being used by the NPM, but obviously just placing the PAT in the npmrc doesn't help, and neither does converting it to base 64. Is something missing in the documentation?

**Comment by visargashi** [comment]
I should clarify what I am doing:
1. I have a Linux docker container.
2. I create a .npmrc file in the project folder with the registry (copied and pasted from the VSTS npm tool)
3. I create a .npmrc file in the ~/ location, using the link paths documented in this page, the username is random, the _password is my PAT (have also tried the base64 version of the PAT), my email address, and always auth = true
4. I try npm i library@version (where lib/version are actuals from my private VSTS artifact repo). I get a 401 error

**Comment by spike008t** [comment]
@elbatk Right, so I'm gonna post on Developer Community and I'll update this feed once I do have the response. Very weird that nobody have these issue (maybe they all use the 90 days token...)

**Comment by elbatk** [comment]
You'd probably get a quicker response that way, @spike008t , please do report back though because if it's something we should add to the docs to make everyone's life easier, then I'm happy to do it!

**Comment by spike008t** [comment]
@elbatk I've submit a PR to solve this issue
@visargashi the issue was the return line generated by the command before to call base64... The token should end with 2 equal at the end. See below.

To explain the issue, as the documentation said, we have to call:
```
$> base64 <<< "rrmenqsndeegleqv7qfqxm3bfesxelhdqr4q4i55p2ec4vwrovka"
cnJtZW5xc25kZWVnbGVxdjdxZnF4bTNiZmVzeGVsaGRxcjRxNGk1NXAyZWM0dndyb3ZrYQo=
```
But with the previous command, a return line is added at the end of the token before to call base64..
The correct command to get the base64 token is:

```
$> echo -n azwygnzegueq24jqxhrpvl5fnvvuqm2gwyz2nukmy6gz5lre4zxq | base64
YXp3eWduemVndWVxMjRqcXhocnB2bDVmbnZ2dXFtMmd3eXoybnVrbXk2Z3o1bHJlNHp4cQ==
```

And now all works, hope that will help

**Comment by visargashi** [comment]
@spike008t, that did it... thank you. I didn't think to question the base64 generation
