### ISSUE TITLE
Can we publish code coverage reports to the widget (code coverage)

### ISSUE THREAD

**Issue by rizwaans** [MicrosoftDocs/vsts-docs#2614]
Hi, 
Might be a silly question, but can someone explain or suggest me if we can publish the code coverage reports directly to the code coverage widget on the dashboards (Azure DevOps / VSTS) 
or please suggest me a way to check the code coverage results in a standard way by not have to download them from the artifacts folder

![image](https://user-images.githubusercontent.com/25411949/49254103-3a458200-f48d-11e8-8a32-7714d374022c.png)

@sdavis3 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dcb11d2d-86bd-ff52-d191-4da86d54b473
* Version Independent ID: 79438e17-b3d3-0331-5040-98107eb840a2
* Content: [Dashboards, charts, & widgets - Azure DevOps & TFS](https://docs.microsoft.com/en-us/azure/devops/report/dashboards/overview?view=vsts)
* Content Source: [docs/report/dashboards/overview.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/report/dashboards/overview.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by sdavis3** [comment]
I’m not sure I understand the question. If you use the Code Coverage Widgets extension from the marketplace there is no downloading of artifact since it uses the Rest API directly.

**Comment by greggboer** [comment]
There are [2 code coverage widgets on the marketplace](https://marketplace.visualstudio.com/search?term=code%20coverage&target=AzureDevOps&category=All%20categories&sortBy=Relevance).

They might work for you. However, there are no Azure DevOps out-of-box widgets that do code coverage.

**Comment by KathrynEE** [comment]
@rizwaans - Thank you for the inquiry. I'm closing this issue as answered.
