### ISSUE TITLE
How do I run multiple commands in containerCommand field?

### ISSUE THREAD

**Issue by mkliu** [MicrosoftDocs/vsts-docs#2617]
The example above shows "npm install", what if I also need to execute another command?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d9dbf88-7e55-d427-145e-d36b04fb197f
* Version Independent ID: a3f30c00-817c-9c05-7a57-3f2bf618821e
* Content: [Docker task - Azure Pipelines & TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/docker?view=vsts)
* Content Source: [docs/pipelines/tasks/build/docker.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/build/docker.md)
* Product: **devops**
* GitHub Login: @erickson-doug
* Microsoft Alias: **dastahel**

**Comment by shashankbarsin** [comment]
Use either of the following formats - 
`containerCommand: /bin/bash -c "echo hello; echo world"`
or
`containerCommand: /bin/bash -c "echo hello && echo world`
depending on your requirement. In the first case when ';' is used, the second command runs regardless of the whether the first command gave an error (non-zero) as exit status or not (exit status zero). On the other hand && makes the second command run only if the first command had an exit status of zero (no-errors)
