### ISSUE TITLE
The page loading does not end.

### ISSUE THREAD

**Issue by changeworld** [MicrosoftDocs/vsts-docs#2618]
[フィードバックをこちらに入力してください]
The page loading does not end, even if I wait more than an hour.
In the lower left of the browser, it is displayed as attached.
<img width="295" alt="2018-11-30 14 14 29" src="https://user-images.githubusercontent.com/1207985/49269963-ecd80d80-f4aa-11e8-9922-c82dc13db762.png">

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: c33341d5-6655-4d3a-fba8-fdfc0c814afc
* Version Independent ID: a17d5cc5-fbd9-15e3-e14b-70f27702f554
* Content: [Exploratory and Manual Testing -  TestTools](https://docs.microsoft.com/ja-jp/azure/devops/test/index?view=vsts)
* Content Source: [docs/test/index.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/test/index.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment]
Thank you for your feedback. I have passed this on to the product team for advice.

**Comment by harishkragarwal** [comment]
@changeworld: I am failing to understand the issue at hand here i.e. which page is not loading for you. Kindly elaborate. If it involves any info that should not be public then shoot an email to devops_tools@microsoft.com so that we can take a deeper look.

**Comment by harishkragarwal** [comment]
Closing due to no response.
