### ISSUE TITLE
Nuget restore External Service Connetion

### ISSUE THREAD

**Issue by Dushelov** [MicrosoftDocs/vsts-docs#2620]
Currently external private nuget feed can be used during "nuget push" option. Please add possibility to use external private nuget feeds which are added through "Nuget service connection" to make "nuget restore".

**Comment by steved0x** [comment]
@Dushelov Thank you for your feedback. The issues in this repo are for content feedback, and this looks like a product feedback. For product feedback, including feature requests, please file an issue here: https://developercommunity.visualstudio.com/spaces/21/index.html

Thank you.
