### ISSUE TITLE
parallel & parallelCount don't have effect?

### ISSUE THREAD

**Issue by joseph-cloudthing** [MicrosoftDocs/vsts-docs#2621]
These two parameters are documented but don't seem to have any effect in practice?

Are docs ahead of live?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b3f565b-88e4-88d6-a534-48ec21e6e3d8
* Version Independent ID: 9fca89ae-4a6e-a43a-2834-1a91ad44c256
* Content: [Publish Build Artifacts task - Azure Pipelines & TFS](https://docs.microsoft.com/en-gb/azure/devops/pipelines/tasks/utility/publish-build-artifacts?view=vsts)
* Content Source: [docs/pipelines/tasks/utility/publish-build-artifacts.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/utility/publish-build-artifacts.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by elbatk** [comment]
Ah, yes. Thanks @joseph-cloudthing , I don't see them in the product either. I'll take a look into this.

**Comment by joaofpereira** [comment]
@elbatk Did you find anything about this? We don't see it live either

**Comment by ROunofF** [comment]
Just giving a spin on this as this looks possibly easy to fix/improve. The parallel is in the code as seen here :

https://github.com/Microsoft/azure-pipelines-tasks/blob/master/Tasks/PublishBuildArtifactsV1/publishbuildartifacts.ts#L90

However it seems the param isn't configurable from the interface. Not sure about the yaml definition... Probably there could be a debug output that confirms / deny the parameter count be easily added...

**Comment by chasewilson** [comment]
Is anyone still having an issue with this?

**Comment by chasewilson** [comment]
I'm closing this issue. If there are any more issues with this, please open a new issue.
