### ISSUE TITLE
A "step 5" is referred to, but not present in image

### ISSUE THREAD

**Issue by dendle** [MicrosoftDocs/vsts-docs#2627]
Documentation mentions a "step 5" - there is no corresponding "red circle" that represents step 5 in the image.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5f5ce059-ec92-5413-0910-4e28033db034
* Version Independent ID: 540610d3-6073-664d-97f8-e7d8e0a21a20
* Content: [Set Git or TFVC repository permissions - Azure DevOps & TFS](https://docs.microsoft.com/en-us/azure/devops/organizations/security/set-git-tfvc-repository-permissions?view=vsts&tabs=new-nav)
* Content Source: [docs/organizations/security/set-git-tfvc-repository-permissions.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/security/set-git-tfvc-repository-permissions.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by dendle** [comment]
Sorry - it is there, but the image is cropped off in the page, and I'm on a widescreen.  Noone will see step 5 unless they click the zoom button.

**Comment by KathrynEE** [comment]
@dendle - Thank you for the feedback. If you click the image it will expand - this is a "lightbox" image feature. I've updated the article to reflect the need to click the image to expand it.
