### ISSUE TITLE
Upgrading Legacy Feeds - Release Notes?

### ISSUE THREAD

**Issue by MikeHofer-SM** [MicrosoftDocs/vsts-docs#2629]
Was this capability ever released? I've been going through the release notes and haven't found it yet.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2963d2fc-350f-0d4d-bd1a-900cdfb81474
* Version Independent ID: 474d13a9-83cf-e445-f2d2-2ca917a2b09a
* Content: [Upgrading a legacy feed](https://docs.microsoft.com/en-us/azure/devops/artifacts/reference/feed-upgrade-learn-more?view=vsts)
* Content Source: [docs/artifacts/reference/feed-upgrade-learn-more.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/artifacts/reference/feed-upgrade-learn-more.md)
* Product: **devops**
* GitHub Login: @alexmullans
* Microsoft Alias: **amullans**

**Comment by MikeHofer-SM** [comment]
I found the [release notes](https://docs.microsoft.com/en-us/azure/devops/release-notes/2018/jun-19-vsts#use-upstream-sources-in-legacy-feeds) that say that you can do this. However, it doesn't provide any guidance on _how_ to do it, and the [Legacy Feeds](https://docs.microsoft.com/en-us/azure/devops/artifacts/reference/feed-upgrade-learn-more?view=vsts) page hasn't been updated.

We're trying to create a build pipeline to a third party NuGet feed, and we can't because DevOps refuses to recognize it as a NuGet feed. We can only assume it's treating it as a Legacy Feed (there's no option to select NuGet from the dropdown). Without any available guidance on how to resolve the issue, this is a breaking, blocking issue for us.

**Comment by Banner-Keith** [comment]
I am also interested in upgrading a legacy feed. Please add this documentation. As Mike said, the release notes clearly say that it is possible.

**Comment by alexmullans** [comment]
@MikeHofer-SM it was released, yes. If your feed needs to be upgraded you should see a banner in the Packages hub and a button in the feed settings (on the Feed details tab). However, I think there may be a separate issue here. Are you trying to set up the NuGet task in build? Or, are you trying to add another NuGet feed as an upstream source? If the latter, only NuGet.org and other Azure Artifacts feed are supported as upstream sources for NuGet packages.

**Comment by MikeHofer-SM** [comment]
Our build pipeline needs to use a 3rd party NuGet feed. From what we understand from the documentation, you have to configure that as an upstream source in Azure Artifacts, and select it as the NuGet source in the build pipeline. Is that not correct? Is there more thorough complete documentation that describes the process for consuming a third-party NuGet feed that is not NuGet.org?

Mike Hofer | Integration Developer
ServiceMac| Jacksonville, FL | Mobile: 904.333.0576

CONFIDENTIALITY NOTICE: This e-mail message, including any attachments, is for the sole use of the intended recipient(s) and may contain confidential and privileged information. Any unauthorized review, use, disclosure or distribution is prohibited. If you are not the intended recipient, please contact the sender by reply e-mail, delete and then destroy all copies of the original message.

**Comment by alexmullans** [comment]
@MikeHofer-SM you can just configure the NuGet task in Azure Pipelines to get packages directly from your external NuGet feed (just like you would `nuget sources add` or use Visual Studio's settings on your developer machine). These docs may help: https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/package/nuget?view=vsts#restore-nuget-packages. Specifically, you'll want to check in a nuget.config file that references your external feed, select it in the task's settings, and then use the task to create a [NuGet service endpoint](https://docs.microsoft.com/en-us/azure/devops/pipelines/library/service-endpoints?view=vsts#sep-nuget) that has the URL and credentials for your external feed.

**Comment by elbatk** [comment]
Hi @MikeHofer-SM , I hope this worked out for you! We haven't heard from you in a bit, so I'm going to close this issue here. Please reach out if you haven't gotten your issue resolved.

**Comment by MikeHofer-SM** [comment]
It did work. Thank you.
