### ISSUE TITLE
Add a workflow isn't in the New Navigation Style

### ISSUE THREAD

**Issue by 5nowx** [MicrosoftDocs/vsts-docs#2630]
The section 'Add a workflow State' isn't in the new navigation style, only in the old one

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 715eca62-8a31-4163-c27b-f5e71d781982
* Version Independent ID: 06dc711f-1946-29e9-aece-75af903da09b
* Content: [Customize the workflow of an inherited process - Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/organizations/settings/work/customize-process-workflow?view=vsts&tabs=new-nav)
* Content Source: [docs/organizations/settings/work/customize-process-workflow.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/settings/work/customize-process-workflow.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@5nowx - Thank you for the feedback. This articles is being updated accordingly.
