### ISSUE TITLE
Date query is incorrect

### ISSUE THREAD

**Issue by Mini-Geek** [MicrosoftDocs/vsts-docs#2633]
> For example, you can find all items created in the last week with the clause `Created Date=@Today-7`.

This is incorrect, it instead shows items created one week ago, to the day. Most likely what was intended is `Created Date>=@Today-7`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a718268-1105-4def-5f9e-20ea21afc0d7
* Version Independent ID: 0f08fa18-3075-4275-22c7-d5d1c1e260b0
* Content: [Query fields, operators, and macros/variables - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/queries/query-operators-variables?view=vsts#feedback)
* Content Source: [docs/boards/queries/query-operators-variables.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/boards/queries/query-operators-variables.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@Mini-Geek - Thank you for the correction. The article is getting updated.
