### ISSUE TITLE
Applies to TFS 2018?

### ISSUE THREAD

**Issue by MattDavisRM** [MicrosoftDocs/vsts-docs#2635]
I'm trying to verify whether multiple jobs running in parallel is supported in TFS 2018.3?  The dependencies option is not available and when I setup a basic multi-phase build, the phases are executing sequentially instead of in parallel.  Is the parallel options mentioned here really available in TFS 2018?  Or it not really available until 2019.RC1 or later?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a14fc554-e74e-2c76-34d1-37a2e0dd7b2f
* Version Independent ID: e95259f4-61ef-5e99-a492-eb77d7d1e657
* Content: [Workflow using multiple jobs in Azure Pipelines Build and Release - Azure Pipelines & TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/multiple-phases?view=vsts&tabs=designer)
* Content Source: [docs/pipelines/process/multiple-phases.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/multiple-phases.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment]
Thank you for your feedback. I have passed this on to the product team for advice.
