### ISSUE TITLE
Publishing via Command Line fails with 401 (Not authorized)

### ISSUE THREAD

**Issue by bugra-derre** [MicrosoftDocs/vsts-docs#2636]
Publishing my extension fails with an 401 (Not authorized). Even though I set up a personal access token. I posted also a question to Stackoverflow for more details https://stackoverflow.com/questions/53579969/publish-an-azure-devops-extension-from-command-line-fails-with-401 hoping that you have an answer for this issue.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4b2914b5-105a-32f7-c7be-5f1604775f61
* Version Independent ID: 0070cd88-c1f7-6a69-ef9c-fb5b4f3b8544
* Content: [Publishing and Packaging an Extension from the Command Line](https://docs.microsoft.com/en-us/azure/devops/extend/publish/command-line?view=vsts)
* Content Source: [docs/extend/publish/command-line.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/extend/publish/command-line.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by elbatk** [comment]
Hi @bugra-derre , sorry you're having this issue. I can't really help more, but I can point you to the [Azure DevOps Services Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html) which is monitored by the product team. Hopefully you can find help there! Best of luck :)
