### ISSUE TITLE
How to fetch certificates using Azure Key Vault task ?

### ISSUE THREAD

**Issue by nkwolf** [MicrosoftDocs/vsts-docs#2637]
Can this task be really used to fetch certificates? When it runs, it only seems to download secrets. The service principal I'm using for the task has get;list permissions to both certificates and secrets. Please clarify

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 69ff8e50-4187-3622-1beb-155f006af5f5
* Version Independent ID: bc56fa96-bded-95f8-39a4-a9e5242db1bf
* Content: [Azure Key Vault task - Azure Pipelines & TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-key-vault?view=vsts)
* Content Source: [docs/pipelines/tasks/deploy/azure-key-vault.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/deploy/azure-key-vault.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment]
Thank you for your feedback. I have passed this on to the product team for advice.

**Comment by shashban** [comment]
@nkwolf I'm closing this issues for now. Please reopen and let us know if you continue to have this issue.
