### ISSUE TITLE
No documentation about permissions for plans with TfS 2017

### ISSUE THREAD

**Issue by spashx** [MicrosoftDocs/vsts-docs#2638]
Hi,
The documentation about permissions is missing for TFS 2017.
Regards,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ef517e1-f614-a2e5-d968-e32bdaac6183
* Version Independent ID: babf6a50-0147-74bb-0e20-b1939de397af
* Content: [Review team delivery plans - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/plans/review-team-plans?view=vsts&tabs=new-nav)
* Content Source: [docs/boards/plans/review-team-plans.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/boards/plans/review-team-plans.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@spashx - Thank you for the feedback. Actually, the permissions for plans are missing for all versions. I'm correcting this with a new topic to be published soon.
