### ISSUE TITLE
Doc for multiple azure-devops pipelines in one repo

### ISSUE THREAD

**Issue by yhvicey** [MicrosoftDocs/vsts-docs#2639]
I see there're multiple azure devops pipelines under [AspNetCore](https://github.com/aspnet/AspNetCore/tree/master/.azure/pipelines) repo but there seems no doc about it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7458d5b2-1bb7-7d87-7ce6-2b0c430b0155
* Version Independent ID: edf5bbd3-a3f0-5426-e985-31290f8afd05
* Content: [YAML schema - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=vsts&tabs=schema)
* Content Source: [docs/pipelines/yaml-schema.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/yaml-schema.md)
* Product: **devops**
* GitHub Login: @erickson-doug
* Microsoft Alias: **macoope**

**Comment by andyjlewis** [comment]
Not sure I understand the issue. We do have docs on using Azure Pipelines with ASP.NET Core: https://docs.microsoft.com/en-us/azure/devops/pipelines/languages/dotnet-core. If you have questions or requests for info about https://github.com/aspnet/AspNetCore/tree/master/.azure/pipelines, please open a PR or issue over there.

**Comment by yhvicey** [comment]
No, I'm not talking about "Using Azure Pipelines with ASP.NET Core", but "Using multiple Azure Pipelines within one git repo". The ASP.NET Core repo link here is a example repo, because it contains multiple Azure Pipelines.

**Comment by andyjlewis** [comment]
I see. OK, yeah, I think there's a bit of a hole

**Comment by yhvicey** [comment]
Found how to config this. Go to Azure DevOps -> Your Project -> Build -> Edit your Build Definition -> Switch to Visual Designer -> Edit YAML file path.

![image](https://user-images.githubusercontent.com/8000820/50342083-76d03f00-055c-11e9-916a-e1f6c0f85ec2.png)

![image](https://user-images.githubusercontent.com/8000820/50342094-85b6f180-055c-11e9-8ed0-c348f4249b07.png)

**Comment by M0ns1gn0r** [comment]
Yes you can create a pipeline manually and target it to the yaml in a sub-folder, but that's some external configuration which somewhat contradicts the Infrastructure-as-Code principle. Therefore I have created a separate issue https://github.com/MicrosoftDocs/vsts-docs/issues/6367.
