### ISSUE TITLE
Enable CORS for Storage Account access

### ISSUE THREAD

**Issue by SamirFarhat** [MicrosoftDocs/vsts-docs#2643]
Hi,
The link you provided to enable CORS is generic.
What are the CORS settings that we should set to allow CORS requests from your domain. Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a59ea95e-b51a-e529-37a8-215e383c9a0b
* Version Independent ID: f1afdb0e-f090-3193-9bb8-ce5952016768
* Content: [Azure Resource Group Deployment task - Azure Pipelines & TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-resource-group-deployment?view=vsts)
* Content Source: [docs/pipelines/tasks/deploy/azure-resource-group-deployment.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/deploy/azure-resource-group-deployment.md)
* Product: **devops**
* GitHub Login: @erickson-doug
* Microsoft Alias: **dastahel**

**Comment by RoopeshNair** [comment]
@SamirFarhat - please post your suggestions on [DeveloperCommunity](https://developercommunity.visualstudio.com/spaces/21/index.html) so that it gets prioritized appropriately.
