### ISSUE TITLE
The URL's in the examples are all broken. 

### ISSUE THREAD

**Issue by StingyJack** [MicrosoftDocs/vsts-docs#2644]
they should be "https://mytfsserver/tfs/DefaultCollection" if using SSL, or "http://mytfsserver:8080/tfs/DefaultCollection" where 8080 is the default port

Otherwise you will just get a big fat useless error and wonder why this doesnt work for you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f225bc86-a0d2-78d7-c060-82abf1a65229
* Version Independent ID: 7e1f2e49-2130-f15d-f11c-6db5638c5355
* Content: [Builds](https://docs.microsoft.com/en-us/azure/devops/integrate/previous-apis/build/builds?view=tfs-2018)
* Content Source: [docs/integrate/previous-apis/build/builds.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/integrate/previous-apis/build/builds.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by elbatk** [comment]
Adding @willsmythe to verify this for me, and then I'll make the change :) Thanks @StingyJack !

**Comment by StingyJack** [comment]
@stale[bot] still needs some tweaking? 

It and it's ilk need to be banned from any community minded place.

**Comment by chcomley** [comment]
Hi @StingyJack, as I scan the doc, it looks like this was addressed last August. I'll be closing this issue, however, if you feel that the doc needs more work, please respond to this message and we'll create a new issue. Thanks very much.

**Comment by StingyJack** [comment]
@cchomley the problem was that the urls would break and then be fixed and repeat every few months. I don't need the on premise API reference docs anymore.
