### ISSUE TITLE
What parameters are required to find deleted but not destroyed builds?

### ISSUE THREAD

**Issue by StingyJack** [MicrosoftDocs/vsts-docs#2645]
The retention policy ate one of the builds I need. I want to find the build to restore it

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f225bc86-a0d2-78d7-c060-82abf1a65229
* Version Independent ID: 7e1f2e49-2130-f15d-f11c-6db5638c5355
* Content: [Builds](https://docs.microsoft.com/en-us/azure/devops/integrate/previous-apis/build/builds?view=tfs-2018)
* Content Source: [docs/integrate/previous-apis/build/builds.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/integrate/previous-apis/build/builds.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by elbatk** [comment]
Hey @StingyJack , sorry for the delay. I'm not sure this is possible. Adding @vtbassmatt who can help us or he knows who can :)

**Comment by StingyJack** [comment]
@elbatk - Don't sweat it, I was able to recreate the needed parts in a few hours. I'll log a feedback item about the default retention policies being too aggressive.
