### ISSUE TITLE
Specifics on validation we do

### ISSUE THREAD

**Issue by liang2zhu1** [MicrosoftDocs/vsts-docs#2646]
WRT 'Azure Boards performs a check to ensure that you've entered a valid link.' - The link must be a repository integrated with the team project or the validation will fail, can you capture this in doc? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c82842d8-dd84-249f-cce1-9e93ecf703bf
* Version Independent ID: eaf9a299-4492-8e09-287a-f10b63d15e29
* Content: [Link GitHub commits and pull requests to work items in Azure Boards - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/github/link-to-from-github?view=vsts)
* Content Source: [docs/boards/github/link-to-from-github.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/boards/github/link-to-from-github.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@liang2zhu1 - Thank you for the feedback. Article is getting updated.
