### ISSUE TITLE
What are the claims inside System.AccessToken? Can it be used to authorize the caller?

### ISSUE THREAD

**Issue by konrad-jamrozik** [MicrosoftDocs/vsts-docs#2649]
I have a server-based [service-bus-based](https://github.com/Microsoft/azure-pipelines-tasks/blob/master/docs/authoring/servertaskauthoring.md) Azure DevOps extension, to which I pass OAuth token by having in its `task.json` entry like this (see the token at the bottom):

```
  "execution": {
    "ServiceBus": {
      "Events": {
        // ...
      },
      "Execute": {
        "EndpointId": "$(connectedServiceName)",
        "ConnectionString": "$(endpoint.serviceBusConnectionString)",
        "ServiceBusQueueName": "$(endpoint.serviceBusQueueName)",
        "messageBody": {
          // ...
          "vstsUrl": "$(System.teamFoundationCollectionUri)",
          "vstsPlanUrl": "$(System.teamFoundationCollectionUri)",
          "authToken": "$(System.AccessToken)",
```

My back-end service is reading the message from the service bus, including the auth token. Can I authenticate and authorize the caller using the token? For example, I want to confirm that the caller has access to given Azure DevOps organization, and has permissions necessary to submit a specific build of specific project in the specific organization (all that data is also provided in the message put on the service bus). I know Azure DevOps is doing this for me, but here we assume a scenario in which the attacker has managed to put a message on the service bus circumventing Azure DevOps permissions checks, and we want to apply defense in depth by doing additional checks on the back-end service side.

I only know how to authenticate, by creating a `VssConnection` ([source](https://dev.azure.com/mseng/AzureDevOps/_git/AzureDevOps?path=%2FVssf%2FClient%2FWebApi%2FVssConnection.cs&version=GBmaster)) instance using the token and trying to `ConnectAsync()` to it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ffebdc8-521c-44b5-cde4-4abdc1bd6f18
* Version Independent ID: dc0effda-6d93-62aa-64c5-4e6f283b0826
* Content: [Predefined build variables - Azure Pipelines & TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=vsts&tabs=batch#systemaccesstoken)
* Content Source: [docs/pipelines/build/variables.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/build/variables.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by vtbassmatt** [comment]
I don't think System.AccessToken has a claim about the user who initiated the pipeline. Let me check with someone who's an expert, though.

**Comment by konrad-jamrozik** [comment]
Thanks @vtbassmatt, that's what I suspected.

**Comment by konrad-jamrozik** [comment]
Unfortunately, there is no API for viewing PAT token permissions, according to [Justin's answer](https://github.com/MicrosoftDocs/vsts-rest-api-specs/issues/138#issuecomment-445068798). Closing this thread.
