### ISSUE TITLE
Azure artifacts with Universal package

### ISSUE THREAD

**Issue by Kaali09** [MicrosoftDocs/vsts-docs#2650]
is there anyway to download the latest artifacts by using universal packages?

**Comment by elbatk** [comment]
Hi @Kaali09 , could you expand on your question a bit here? What exactly are you wanting to accomplish? Here is an example of downloading a universal package using the Azure CLI with the Azure DevOps extension: https://docs.microsoft.com/en-us/azure/devops/artifacts/quickstarts/universal-packages?view=vsts&tabs=azuredevops#download-a-universal-package

**Comment by alexmullans** [comment]
@mitchdenny for the feedback. There is not a way to get latest today, but we're thinking about adding it.

**Comment by mitchdenny** [comment]
hi @Kaali09 can I clarify what you mean by download latest?

Our service uses SemVer to version Universal Packages. As a result you could publish packages in the following order:

1. mypackage@1.0.0
2. mypackage@1.0.1
3. mypackage@2.0.0
4. mypackage@1.0.3

If I say get latest. Chronologically that would mean version 1.0.3, however following the rules of semantic versioning the highest version is 2.0.0.

We are about to embark on this work in the next month or so and we believe that when people say get latest, they really mean get highest (so they want version 2.0.0). Are we correct in your scenario?

**Comment by elbatk** [comment]
Hi @Kaali09  , I'm going to close this issue as we haven't heard from you, but we would like to! If you could help give us some insight as to what "latest" would mean to you, it will help us implement the right feature for our users :)

**Comment by Eragra3** [comment]
Hi,

we would like to see similar feature as well.
I think using wildcards would be fine, so using @mitchdenny example:

`--version "1.0.*"` would give me `1.0.3`
`--version "*"` would give me `2.0.0`
`--version "1.*.0"` would probably give me `1.0.0` then.
Latest meaning latest version (following semver)

I think behaviour similar to NuGet [package rererences](https://docs.microsoft.com/pl-pl/nuget/reference/package-versioning#references-in-project-files-packagereference) wildcards would be nice.

I created another ask (that should probably go into some VSTS issue tracker), that is somewhat similar here #4098.
