### ISSUE TITLE
Pipeline Build Html Code Coverage incorrect display

### ISSUE THREAD

**Issue by RaymsDev** [MicrosoftDocs/vsts-docs#2654]
I'm trying to display code coverage result generated by [istanbul.js](https://istanbul.js.org/), i have inline css in html file. I can't fit all the page height : 

## Expected Result:
![image](https://user-images.githubusercontent.com/14817349/49514687-0efbd200-f895-11e8-9257-284be6dee024.png)

## Actual Result:
![image](https://user-images.githubusercontent.com/14817349/49514609-d6f48f00-f894-11e8-9223-7497e55d1d3c.png)

Edit:
Only happen on Chrome.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fabbd5e2-993f-89da-665f-f39ab63d7c42
* Version Independent ID: 493c2582-69a4-1bbe-03b5-0bb5f1d41aed
* Content: [Code coverage Azure Pipelines and TFS - Azure Pipelines & TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/test/review-code-coverage-results?view=vsts)
* Content Source: [docs/pipelines/test/review-code-coverage-results.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/test/review-code-coverage-results.md)
* Product: **devops**
* GitHub Login: @vinojos
* Microsoft Alias: **vinojos**

**Comment by PBoraMSFT** [comment]
@RamysDev - thank you for reporting the issue. This is a known issue with rendering in Chrome browser that was fixed and deployed last week. The new bits should reach you any day now, if they aren't already available in your Azure DevOps organization.
If you continue to see this bug, please feel free to reopen the issue.
