### ISSUE TITLE
Ambiguous "unique feed"

### ISSUE THREAD

**Issue by LucaMahler** [MicrosoftDocs/vsts-docs#2655]
Regarding your first point, "Each repository should have a unique feed"; do you mean that there should be a 1:1 mapping between repository and feed, or do you just want to make sure that a repository doesn't rely on more than one feed, thus you could use a feed for more than one repository?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cdf693ac-c5c3-96a6-7f4b-bbc2271a6375
* Version Independent ID: 4f76c74c-1d6c-644f-f00d-97d7738d7b01
* Content: [Best practices for using packages in Azure DevOps Services and TFS](https://docs.microsoft.com/en-us/azure/devops/artifacts/concepts/best-practices?view=vsts)
* Content Source: [docs/artifacts/concepts/best-practices.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/artifacts/concepts/best-practices.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by jockerman-ipspark** [comment]
I too would like to know the meaning of this best practice recommendation.

My organization has a set of internal libraries. Wherein each library is contained in an independent repository. Furthermore, these libraries are used across many consumer applications and possibly other libraries.

The original thought I had was to make a common feed to dump all of the internally built library packages. Then use this common feed to source packages for the different application projects\repositories.

**Comment by elbatk** [comment]
Hey people, this is a good question and I'll get this clarification. I'm tagging @alexmullans but I know he is out this week so hopefully we can get an answer to ya soon.

**Comment by michaelw85** [comment]
+1 would also like to know the answer. 
Having 1 feed per repo which could end up being just a single package sounds like allot of overhead to me unless this document assumes you're running a monorepo strategy. I'm currently publishing multiple packages from different private repo's into 1 single private feed and don't feel the need to split them into "unique" feeds.

**Comment by alexmullans** [comment]
Great question, thanks for asking. Quoting from your question, we recommend "to make sure that a repository doesn't rely on more than one feed, thus you could use a feed for more than one repository." I've made a small update to clarify - should be out with the next batch later today or early tomorrow.
