### ISSUE TITLE
No description of "Run unit tests" in designer tab

### ISSUE THREAD

**Issue by davidsk** [MicrosoftDocs/vsts-docs#2657]
Selecting the designer tab of the "Run unit tests" step gives a short paragraph on publishing test and coverage results, there is no information on configuring the steps to perform the test

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c99686eb-6c78-0336-1ec3-802a53c9868d
* Version Independent ID: 6eaf1acb-24d4-5bb7-3935-17abe7e59dd9
* Content: [Build JavaScript and Node.js apps with Azure Pipelines or TFS - Azure Pipelines & TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/languages/javascript?view=vsts&tabs=designer#run-unit-tests)
* Content Source: [docs/pipelines/languages/javascript.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/languages/javascript.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by alexhomer1** [comment]
Thank you for your feedback. This is not a documentation issue. Product bugs, suggestions, and feature requests are best posted on the Developer Community website at https://developercommunity.visualstudio.com/spaces/21/index.html, where they are tracked by the product teams. Please post your suggestion there. Thank you.

**Comment by davidsk** [comment]
I don't understand, can you please explain why?  It seems to me that content is missing.

**Comment by alexhomer1** [comment]
This feedback channel is to report issues with the online documentation. The pop-up help tips are built into the product, and as such need to be actioned by the product development team. I have notified them of your feedback, but I cannot implement changes within the product. Hence, I suggest using the "Product Feedback" feature that is also provided in every help topic.

**Comment by davidsk** [comment]
I'm not reporting an issue with the product, or pop-up help tips, I'm reporting an issue with the online documentation here: https://docs.microsoft.com/en-us/azure/devops/pipelines/languages/javascript?view=vsts&tabs=designer#run-unit-tests

The content of the [YAML tab](https://docs.microsoft.com/en-us/azure/devops/pipelines/languages/javascript?view=vsts&tabs=yaml#run-unit-tests) contains examples of how to invoke tests directly, call a predefined task in addition to publishing the results.  The [Designer tab](https://docs.microsoft.com/en-us/azure/devops/pipelines/languages/javascript?view=vsts&tabs=designer#run-unit-tests), in contrast, does not contain the equivalent information.

I am assuming the purpose of the tabs is to allow the reader to select the approach best suited for them in which case the contents of the tabs should be equivalent.  Is this not the case?

**Comment by alexhomer1** [comment]
I'll consult with the documentation team to add the appropriate content in the Designer tab.

**Comment by davidsk** [comment]
@alexhomer1 Thanks
