### ISSUE TITLE
Publish your packages Designer screenshot shows invalid positioning of NuGet push task

### ISSUE THREAD

**Issue by saluce65** [MicrosoftDocs/vsts-docs#2658]
In the [*Publish your packages*](https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/nuget?view=vsts&tabs=designer#publish-your-packages) section of [**Publish to NuGet feeds**](https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/nuget?view=vsts&tabs=designer), the screenshot for the Designer shows the `NuGet push` task in the wrong position.  The screenshot shows to put the `NuGet push` command immediately after the `NuGet pack` command.  However, if the user is using MSBuild to create the NuGet packages, there won't be a `NuGet pack` and the task needs to be placed after the `Copy files to: $(build.artifactstagingdirectory)` task, since the NuGet package won't be in the staging folder until after that task.  The documentation does not make that clear.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f2512189-84f9-f997-0255-13b276c233b4
* Version Independent ID: c7ccb0ba-4221-bdac-85e1-111eaf51943b
* Content: [Publishing to NuGet feeds - Azure Pipelines & TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/nuget?view=vsts&tabs=designer#publish-packages)
* Content Source: [docs/pipelines/artifacts/nuget.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/artifacts/nuget.md)
* Product: **devops**
* GitHub Login: @erickson-doug
* Microsoft Alias: **amullans**

**Comment by elbatk** [comment]
Hi @saluce65 , thanks for the feedback. I think the point of the screenshot here is to mostly just show the NuGet Push task configuration itself more than the correct sequence of tasks. You do raise a valid point though that if your NuGet package is already created and lives in a directory, it must be copied over to the artifact staging directory before publishing (or you can set your Path to NuGet package(s) to publish variable to where it was created). Did you find it confusing as it is? The only thing I could see changing is to add a blurb below stating what you've mentioned.

**Comment by alexmullans** [comment]
@elbatk we should, at some point, invest in some more comprehensive documentation for creating and publishing NuGet packages, esp. in .NET Core workflows. We could probably work with @anangaur from the NuGet team.

**Comment by elbatk** [comment]
I've created a work item for this and I'll reach out to Anand, thanks Alex!

**Comment by thomps23** [comment]
Closing out as @elbatk has placed the work is the team backlog.
