### ISSUE TITLE
GitHub Connections link missing from my Project Settings

### ISSUE THREAD

**Issue by stevefuzzy** [MicrosoftDocs/vsts-docs#2659]
I'm using the new navigation, yet I do not see GitHub Connections button/link under Project Settings.
Why?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 04afcda8-8a01-6fda-8387-778feaba9fea
* Version Independent ID: a0c518ee-dc43-42a6-07d9-150dfa8724c3
* Content: [Connect a project in Azure DevOps Services with a GitHub repository - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/github/connect-to-github?toc=/azure/devops/boards/get-started/toc.json&bc=/azure/devops/boards/get-started/breadcrumb/toc.json&view=vsts)
* Content Source: [docs/boards/github/connect-to-github.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/boards/github/connect-to-github.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by joukevandermaas** [comment]
Also missing for us.

**Comment by mehagar** [comment]
Also missing for us.

**Comment by KathrynEE** [comment]
@stevefuzzy, @joukevandermaas - As new features are released on Azure DevOps Services, it can take up to 3 weeks for them to roll out to all cloud servers. If the feature doesn't show up by 12/25, please contact [support](https://azure.microsoft.com/en-us/support/devops/).
