### ISSUE TITLE
Simpler way of saving than changing branches

### ISSUE THREAD

**Issue by yevster** [MicrosoftDocs/vsts-docs#2660]
Changing the build host appears to also force the build to save (and authorize resources), just as saving branches does. The former, however, does not require creating another resources and can thus be accomplished in fewer steps.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee4ec9d0-e0d5-4fb4-7c3e-b84abfa290c2
* Version Independent ID: 3e2b80d9-30e5-0c48-49f0-4fcdfedf5eee
* Content: [Resources - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/resources?view=vsts#troubleshooting-authorization-for-a-yaml-pipeline)
* Content Source: [docs/pipelines/process/resources.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/resources.md)
* Product: **devops**
* GitHub Login: @vtbassmatt
* Microsoft Alias: **alewis**

**Comment by vtbassmatt** [comment]
Thanks for the suggestion. The reason we don't document it that way is that often, you're adding a new resource in a new branch. If you change the host, it will reauthorize the resources used on the default branch, which won't catch the new one on the branch.

Real fix: make this auth stuff more explicit in the UI, which we're working on.
