### ISSUE TITLE
Can you convert an existing Visual Designer build to a YAML build?

### ISSUE THREAD

**Issue by anblanco** [MicrosoftDocs/vsts-docs#2661]
I can make a new build off of the generated YAML, but can I also convert an existing build to YAML in place? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 38f7a23b-ebd4-af3e-68a2-275f7e45c33e
* Version Independent ID: f552a18c-ba29-00d4-03b6-254d7556d319
* Content: [Create your first pipeline - Azure Pipelines & TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/get-started-yaml?view=vsts)
* Content Source: [docs/pipelines/get-started-yaml.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/get-started-yaml.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by andyjlewis** [comment]
There's no automated way to convert a designer build to a YAML build. However, you can copy YAML to the clipboard from your designer build.

**Comment by andyjlewis** [comment]
Interesting, @tgdane, thanks for sharing the scenario. you might want to also mention your concerns here: https://developercommunity.visualstudio.com/spaces/21/index.html

**Comment by a-einstein** [comment]
I want to support this.

It seems very logical to convert the whole pipeline into YAML in one go. Now there are only fragments one has to paste to some file, like in a separate YAML pipeline. Those fragments even do not entirely make sense as there are error messages about missing variables. Why not STORE the whole pipeline as YAML to begin with?

Related to that: there is no way of testing the YAMLs first before committing. The only way is to commit first, or test in a classic pipeline as fragments. I do not want to end up with a whole series of 'test commits'. So the way to go in my opinion is to design and test in the classic designer, store as YAML, then commit.

Besides. It is pretty murky how to start a pipeline as YAML, and choosing one's own file name while it does not exist yet, and get some generated YAML into it. This what I would want while starting (as a beginner), of course based on existing templates one can choose and adapt.

Of course as logical related matter: release pipelines should be storable as YAML too (like requested elsewhere). Maybe put both (all) pipelines in one file.

**Comment by vtbassmatt** [comment]
Thanks for the feedback, @a-einstein. It's not as simple as storing designer pipelines in YAML. The two frontends have slightly different feature sets (for instance, designer has task groups while YAML has templates).

We've added a click-through wizard: when you start creating a new pipeline, we'll analyze your repo and suggest a template to get your started.

Release definitions as YAML was just announced at //Build yesterday. The preview will be available in your Azure DevOps organization soon.

**Comment by f2calv** [comment]
FYI https://devblogs.microsoft.com/devops/replacing-view-yaml/
