### ISSUE TITLE
Unable to connect with TFS git repository using ssh from local machine

### ISSUE THREAD

**Issue by EthanWeber7** [MicrosoftDocs/vsts-docs#2662]
Previously, I was able to access our TFS git repository with ssh.  At some point today it stopped working.  To my knowledge, no settings were changed.  Here is the error I received.

`remote:
remote: Your Git command did not succeed.
remote: Details:
remote:         TF14045: The identity with type 'Microsoft.IdentityModel.Claims.ClaimsIdentity' could not be found.
remote:
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.`

**Comment by nschonni** [comment]
https://developercommunity.visualstudio.com/spaces/22/index.html is a better place for a product issue

**Comment by EthanWeber7** [comment]
Thanks
