### ISSUE TITLE
How can I view my permissions programmatically?

### ISSUE THREAD

**Issue by konrad-jamrozik** [MicrosoftDocs/vsts-docs#2665]
As in subject. Related question: [What are the claims inside System.AccessToken? Can it be used to authorize the caller?](https://github.com/MicrosoftDocs/vsts-docs/issues/2649)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce8b2923-a3dc-7055-6550-d4943faa5a68
* Version Independent ID: fce8bd86-a25c-341e-5be4-61f19e4dd08f
* Content: [View permissions for yourself or others - Azure DevOps & TFS](https://docs.microsoft.com/en-us/azure/devops/organizations/security/view-permissions?view=vsts&tabs=new-nav)
* Content Source: [docs/organizations/security/view-permissions.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/security/view-permissions.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by vtbassmatt** [comment]
@andyjlewis this isn't a pipelines question, it's for someone on the enterprise auth team to help with.

**Comment by konrad-jamrozik** [comment]
Unfortunately, there is no API for viewing PAT token permissions, according to [Justin's answer](https://github.com/MicrosoftDocs/vsts-rest-api-specs/issues/138#issuecomment-445068798). Closing this thread.
