### ISSUE TITLE
Minor correction in Section "Define your CD Pipeline"

### ISSUE THREAD

**Issue by kishanparekh-techpartner** [MicrosoftDocs/vsts-docs#2666]
Section "Define your CD Pipeline", item 8, please change "Shell Script" to "Bash" within Search text box. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: abf8bb33-e4cf-3dc5-5510-1111b8f1bdbf
* Version Independent ID: 3148d97d-2ff1-30f5-0487-dbfe93888a3f
* Content: [Deploy a nginx web server on a Linux Virtual Machine - Azure Pipelines & TFS](https://docs.microsoft.com/en-in/azure/devops/pipelines/apps/cd/deploy-linuxvm-deploygroups?view=vsts)
* Content Source: [docs/pipelines/apps/cd/deploy-linuxvm-deploygroups.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/apps/cd/deploy-linuxvm-deploygroups.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment]
Thank you for your feedback. I will update the topic to include your recommendations.
