### ISSUE TITLE
Update YAML sample to reflect non-alias properties

### ISSUE THREAD

**Issue by BernieWhite** [MicrosoftDocs/vsts-docs#2667]
Since `testResultsFormat` is an alias for `testRunner` and `buildConfiguration` is an alias for `configuration`, maybe the YAML sample can just show the non-aliased properties.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba91e46a-de53-c0c1-f7f7-c02e797d527c
* Version Independent ID: 6f478148-461f-694a-ed82-deb4d731854e
* Content: [Publish Test Results task - Azure Pipelines & TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/test/publish-test-results?view=vsts&tabs=yaml#feedback)
* Content Source: [docs/pipelines/tasks/test/publish-test-results.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/test/publish-test-results.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment]
Thank you for your feedback. I will pass this on to the product team and update the topic based on their response.

**Comment by rishavsharan** [comment]
Hey @bernie-msft 

In the case of `testResultsFormat` vs `testRunner`, this is to account for the fact that while we support test report xmls in the formats of junit/xunit and nunit, they may have been generated by any test runner other than JUnit/XUnit or NUnit frameworks. For example, Mochajs can generate xunit formatted xmls and the `testResultsFormat` here will be xunit. But the `testRunner` is clearly not XUnit (but is instead mocha).

About `buildConfiguration` vs `configuration`, while I am not very sure about the core scenario here, I believe it has to with the fact this parameter is used to refer to and to override the metadata value for the overall `buildConfiguration` variable. It is explicitly supposed to hold only the platform types like x86 and x64. Calling it `configuration` may be confusing to users who may think that this `configuration` may also refer to things like browser configs, OS configs etc.

In both cases, I feel that the aliases improve the clarity vs the base names and unless there are very strong reasons for us to change the docs, I would prefer them to remain.

**Comment by bernie-msft** [comment]
Hey @rishavsharan believe you have the wrong Bernie. :-)

**Comment by PBoraMSFT** [comment]
@rishavsharan - I believe this issue be closed?

**Comment by rishavsharan** [comment]
Yes. Marking it as closed.

**Comment by PBoraMSFT** [comment]
The aliased names are more descriptive and clearer to understand (e.g., buildConfiguration rather than configuration). Closing the issue.
