### ISSUE TITLE
Can't view Git repos

### ISSUE THREAD

**Issue by teejam2** [MicrosoftDocs/vsts-docs#2668]
Git repositories for my projects do not appear in Eclipse, but TFVC repos do:

![image](https://user-images.githubusercontent.com/27975947/49580495-f4823100-f946-11e8-868f-ff6d32550747.png)

![image](https://user-images.githubusercontent.com/27975947/49580546-154a8680-f947-11e8-90cd-00a714001461.png)

Is this a bug? Do I need to configure something?

**Comment by steved0x** [comment]
@teejam2 It sounds like it might be a bug - the issues in the repo are for reporting documentation issues - can you report this bug here:

https://developercommunity.visualstudio.com/spaces/21/index.html

Thank you for the feedback.
