### ISSUE TITLE
Task group title not displayed in the UI

### ISSUE THREAD

**Issue by elmicka** [MicrosoftDocs/vsts-docs#2670]
Hello everyone
I have a little question about task groups in pipelines.
Let's say we have two tasks "TASK A" & "TASK B" in a job, and we make a task group "TASKGROUP AB" from those two tasks.
Now, in the job, we add two occurrences of this task group "TASKGROUP AB", and we give each one a specific name, let's say "AB1" & "AB2". when the pipeline runs and the job gets executed, we don't see anywhere in the UI/logs the title of the task group. all we will see is "TASK A", "TASK B", "TASK A", "TASK B".
wouldn't there be anyway to display the task group title in the logs, before its inner tasks are being executed?
I actually use a workaround, I just add an "empty" task before calling each task group, just a simple inline powershell that does nothing, and in the task title i put the name of the task group that is just gonna be executed next. but I was wondering if there is not a better way to do that because it's kind of redundant.
maybe displaying the task groups hierarchy in the pipeline run wiew?
thx

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1e6b773c-dfb0-5c58-1463-e9b865d73af6
* Version Independent ID: 83f332ed-719a-5347-acd8-bfe3bdb397b4
* Content: [Task Groups in Azure Pipelines and Team Foundation Server - Azure Pipelines & TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/library/task-groups?view=vsts)
* Content Source: [docs/pipelines/library/task-groups.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/library/task-groups.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment]
Thank you for your feedback. I have passed this on to the product team for advice.

**Comment by JamesMBristow2** [comment]
+1
The tasks within a task sequence could be formatted like <TaskSequenceName>:<TaskSequenceDifferentiator>:<TaskName>. A field or checkbox to the side of one of the task sequence variables could be used to specify that variable as the differentiator.

**Comment by JamesMBristow2** [comment]
*formatted like TaskSequenceName:TaskSequenceDifferentiator:TaskName

**Comment by ashokirla** [comment]
Taskgroup is a design time concept and during runtime, the tasks are expanded are executed. We will add this request to our backlog.
