### ISSUE TITLE
.symbols.nupkg -- isn't this now .snupkg?

### ISSUE THREAD

**Issue by teejam2** [MicrosoftDocs/vsts-docs#2671]
.symbols.nupkg -- The other article said this was deprecated in favor of .snupkg

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6717bf11-8e32-75ac-8d60-87a984699acf
* Version Independent ID: 36ceecbc-50ec-d795-bede-289851cbceca
* Content: [Symbol files (PDBs)](https://docs.microsoft.com/en-us/azure/devops/artifacts/concepts/symbols?view=vsts)
* Content Source: [docs/artifacts/concepts/symbols.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/artifacts/concepts/symbols.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by annie21409** [comment]
https://docs.microsoft.com/en-us/nuget/create-packages/symbol-packages-snupkg

**Comment by chasewilson** [comment]
@teejam2, @annie21409,
Thank you both for the feedback!
You are correct and the article will be updated shortly. The issue will be closed when a PR is merged. 
I've created a backlog item for this issue. Thank you again and feel free to reach out with any more feedback.
