### ISSUE TITLE
vcpkg support for C++ project builds on Azure-Pipeline

### ISSUE THREAD

**Issue by vSzemkel** [MicrosoftDocs/vsts-docs#2672]
I'm using AppVeyor. They have a **vcpkg** preinstalled on build machines for quite a long time.
C'mon guys, this is MSFT orginated package manager. Add the support for this, please.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 02b0c082-81b3-79af-8841-8b3033dedf4a
* Version Independent ID: de8aab33-f9ef-0d8d-dbbc-49e23930f1c6
* Content: [C++ - Azure Pipelines & TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/apps/windows/cpp?view=vsts)
* Content Source: [docs/pipelines/apps/windows/cpp.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/apps/windows/cpp.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by jjpepper** [comment]
Vcpkg is installed in the linux image and not in the windows ones.  Can someone from Microsoft explain the reasoning behind this?  Vcpkg is also begging for a build cache of course too.

**Comment by ta2gch** [comment]
I'm not from Microsoft. However, see this pull request. I guess you can use vcpkg in the Windows.
https://github.com/Microsoft/azure-pipelines-image-generation/pull/682/files

**Comment by jjpepper** [comment]
Thanks :-)
