### ISSUE TITLE
Work Item Template Management instructions are slightly off

### ISSUE THREAD

**Issue by markfields** [MicrosoftDocs/vsts-docs#2673]
https://docs.microsoft.com/en-us/azure/devops/boards/backlogs/work-item-template?view=vsts&tabs=browser#manage-work-item-templates

It says "Expand Work and choose Team configuration. " but for me it's under "Boards" not "Work".  And the screenshot doesn't show the list of settings containing these options, but that would be helpful.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1debd814-eb48-c984-a4f9-7606093e9617
* Version Independent ID: f48ef796-c2e3-8fa3-6c41-326a5b252a3d
* Content: [Work item templates - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/backlogs/work-item-template?view=vsts&tabs=browser#manage-work-item-templates)
* Content Source: [docs/boards/backlogs/work-item-template.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/boards/backlogs/work-item-template.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@markfields - Thank you for the correct. The article is getting updated.
