### ISSUE TITLE
Create a visual designer from a yaml file

### ISSUE THREAD

**Issue by sethalicious** [MicrosoftDocs/vsts-docs#2674]
Using the visual designer is way easier than configuring a yaml file. I'd love to (at least) be able to import a yaml pipeline and get the visual designer loaded. That way, I can edit my pipeline in the visual designer and then export it back out to a new yaml file.

Even better, we can have the visual designer work with our yaml pipelines under source control. Switching branches reflects the changes in the visual designer.

I tried advocating switching our pipelines to source controlled yaml, but people really love the convenience of the visual editor. Even though we can easily break branches or lose something we need to revert to! 

Feature request. Please let us import yaml pipelines into the visual editor. 
Another request. Allow the visual editor to work with source controlled pipelines. 

Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 02b747eb-53c2-dd5f-cd2b-f337c15e0864
* Version Independent ID: 04538505-00cd-33ac-8008-4b85cca089e3
* Content: [Use the visual designer to create a CI/CD pipeline - Azure Pipelines & TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/get-started-designer?view=vsts&tabs=new-nav)
* Content Source: [docs/pipelines/get-started-designer.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/get-started-designer.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by andyjlewis** [comment]
Please request features here: https://developercommunity.visualstudio.com/spaces/21/index.html
