### ISSUE TITLE
First Two Scenarios Identical (mistake?) but have different recommendations

### ISSUE THREAD

**Issue by cbailiss** [MicrosoftDocs/vsts-docs#268]
The first two bullet points/scenarios under the "Understand where you're starting from" heading have practically the same description but different recommendations.  One basically implies "follow the steps in this document", the second implies "don't follow this document but contact CSS instead".  Which is it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f56d653-f3ed-88a3-c307-1ba6eec6cbc2
* Version Independent ID: 5f5b1c72-7b2a-a7cf-aea7-39cf84b11005
* [Content](https://docs.microsoft.com/en-us/vsts/accounts/connect-account-to-aad)
* [Content Source](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/accounts/connect-account-to-aad.md)
* Service: unspecified

**Comment by chcomley** [comment]
@cbailiss I have clarified this and it should be live later today, thank you for your feedback.
