### ISSUE TITLE
Fabrikam Fiber

### ISSUE THREAD

**Issue by DonisMarshall** [MicrosoftDocs/vsts-docs#2683]
The Fabrikam Fiber project is referenced in various documentation on Azure Devops from Microsoft, including this document.  What are the steps to import that project into Azure Devops?  That would be a great asset in reviewing and improving the learning experience.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a4ce0e03-d28d-f0c7-9cc4-f89b0768ebe4
* Version Independent ID: 76e3bd85-325b-7a66-446b-163694d438bd
* Content: [Add organization users to Azure Active Directory tenant - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/add-users-to-azure-ad?view=vsts)
* Content Source: [docs/organizations/accounts/add-users-to-azure-ad.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/accounts/add-users-to-azure-ad.md)
* Product: **devops**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by steved0x** [comment]
@DonisMarshall This is a great question, and unfortunately there is no way to import the Fabrikam Fiber projects we use for screenshots and sample documentation.

However, check out the Azure DevOps Services demo generator:

https://docs.microsoft.com/en-us/azure/devops/demo-gen/use-demo-generator-v2?view=vsts

I think this may be able to provide the same benefit as importing the Fabrikam Fiber projects (if they were availble).

Please give it a try and let us know what you think.
