### ISSUE TITLE
Does the MSA to AD mapping process consider alternative email addresses / IDs?

### ISSUE THREAD

**Issue by cbailiss** [MicrosoftDocs/vsts-docs#269]
VSTS allows an alternate email address to be associated with your account, as described here:
https://docs.microsoft.com/en-us/vsts/billing/faq-link-msdn-subscription-org-account

If my primary VSTS login is an MSA account (e.g. peter@hotmail.com) and if I have set my work AD email address (e.g. peter.smith@contoso.com) as the alternate account, when the VSTS to Azure AD connection is switched on, will my MSA login automatically be mapped to my AD login or will I lose access to VSTS?   This needs to be clarified in the documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f56d653-f3ed-88a3-c307-1ba6eec6cbc2
* Version Independent ID: 5f5b1c72-7b2a-a7cf-aea7-39cf84b11005
* [Content](https://docs.microsoft.com/en-us/vsts/accounts/connect-account-to-aad)
* [Content Source](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/accounts/connect-account-to-aad.md)
* Service: unspecified

**Comment by chcomley** [comment]
Thank you for your feedback. We do not use the alt-email from the subscription for mapping at all.
