### ISSUE TITLE
Right syntax for only path trigger

### ISSUE THREAD

**Issue by StefanSchoof** [MicrosoftDocs/vsts-docs#2694]
I want to have a trigger on every branch in one folder. Having this:
```yml
trigger:
  paths:
    include:
      - path
```
results in no trigger. I need to do a:
```yml
trigger:
  branches:
   include:
     - "*"
  paths:
    include:
      - path
```
But the [VSCode Azure Pipelines Extension](https://marketplace.visualstudio.com/items?itemName=ms-azure-devops.azure-pipelines) says now  to the branches include "`String does not match the pattern of \"^[^\\/~\\^\\: \\[\\]\\*\\\\]+(\\/[^\\/~\\^\\: \\[\\]\\*\\\\]+)*(\\/\\*)?$\".`", but it works.

Is it correct that a path filter needs a branch filter? (If yes this should in the documentation) Is there any other "correct" way to have only a path filter or is this a bug in the Azure Pipelines Extension.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5673ec1-c7d1-e0ac-043a-8fc3d5b226a9
* Version Independent ID: b4872831-51c0-6cf8-1c56-de20beb38a80
* Content: [Build pipeline triggers - Azure Pipelines & TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/triggers?view=vsts&tabs=yaml)
* Content Source: [docs/pipelines/build/triggers.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/build/triggers.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by bkwdesign** [comment]
I have the same question. 
I've got multiple yml based build pipelines which pertain to different parts of my repo. So, I want WebApp1.yml to run regardless of branch, but only when certain files change, and the same goes for WebApp2.yml

I've also noted it is possible to create "branch policies" that let you add "build policies" which also feature a file-based filter.. it would be nice to know which one wins if a build policy is defined on a branch AND the yml has a filter.

**Comment by vlef** [comment]
Same root problem when using the UI for your pipeline: in the **Triggers** tab, when you check the **Override YAML Continuous Integration trigger from here** checkbox, if you setup a Path Filter it won't let you save unless you also setup a Branch filter.

Message is "You must add at least one branch filter."

**Comment by vtbassmatt** [comment]
(Note to self: also need to move some of the "how path include/exclude works" stuff out of the Designer tab and into the general area.)

**Comment by ggirard07** [comment]
Just it the exact same issue today.
Including a branch filter with '*' seems to workaround issue.

Can you provide official doc for this with proper syntax?

**Comment by mathieu-benoit** [comment]
FYI `*` alone is indeed not supported, instead you could do: `refs/heads/*`. Agree with you that part of the doc https://docs.microsoft.com/en-us/azure/devops/pipelines/build/triggers?view=azure-devops&tabs=yaml#branches should be updated accordingly.

**Comment by vtbassmatt** [comment]
Erg. Thanks. Fixing. `'*'` also works.

**Comment by vtbassmatt** [comment]
Also, to the original question, that's a bug in the VS Code extension.

**Comment by kczelusniak** [comment]
I believe the documentation is still misleading.

The documentation says the following:

> If you don't specify any branch triggers, the default is as if you wrote:
> ```yaml
> trigger:
>   branches:
>     include:
>     - '*'  # must quote since "*" is a YAML reserved character; we want a string
> ```

But as the original issue states, this isn't true. If I include a path trigger without a branch trigger, then it doesn't seem like the trigger works for any branches.
```yaml
trigger:
  paths:
    include:
      - 'foo/*'
```

I need to explicitly set a branch trigger to trigger on all branches if I add a path trigger:
```yaml
trigger:
  branches:
    include:
      - '*'
  paths:
    include:
      - 'foo/*'
```

**Comment by vtbassmatt** [comment]
Ah, thanks. You're right - will fix.
