### ISSUE TITLE
How to get Version 2.*

### ISSUE THREAD

**Issue by chilakamarthi** [MicrosoftDocs/vsts-docs#2695]
Hi,

In our VSTS I see only Version 1.*. How to get Version 2.* Does it need to install any updates? Our Microsoft Visual Studio Team Foundation Server Version is 15.117.27414.0

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8cddddb9-2731-3366-2a76-9089b58d7f96
* Version Independent ID: b34de428-c3d2-14d6-a452-302c68b74c87
* Content: [Publish symbols for debugging - Azure Pipelines & TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/symbols?view=vsts)
* Content Source: [docs/pipelines/artifacts/symbols.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/artifacts/symbols.md)
* Product: **devops**
* GitHub Login: @erickson-doug
* Microsoft Alias: **amullans**

**Comment by alexmullans** [comment]
@mitchdenny can say for sure, but I think it was TFS 2018.

**Comment by chasewilson** [comment]
@chilakamarthi Thank you again for the question. I've updated the versioning for the documentation to be more accurate. Please let me know if you have any more feedback or questions!
