### ISSUE TITLE
The request was aborted: Could not create SSL/TLS secure channel

### ISSUE THREAD

**Issue by seelamk** [MicrosoftDocs/vsts-docs#2698]
Facing said error while executing Load test for HTTPS based application by using HAR file. 
Is there a solution to overcome this issue to a load test (HAR based) for https://xxxxx.com?

Stack Trace:
at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
 at Microsoft.VisualStudio.TestTools.WebStress.WebTestTransaction.ResponseReceived(IAsyncResult result)

We are able to resolve this issue by WebTest plugin for TLS 1.2 on Performance tests using web test file in Visual Studio... 
do we have similar thing in cloud based load test?

If we have a solution.. it will be huge benefit for my tests.. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 46fb478b-e602-c911-28bb-2dc9c9d50b79
* Version Independent ID: d830b560-3735-1c43-49b9-431ea73814bc
* Content: [Record and replay cloud-based load tests with Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/test/load-test/record-and-replay-cloud-load-tests?view=vsts)
* Content Source: [docs/test/load-test/record-and-replay-cloud-load-tests.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/test/load-test/record-and-replay-cloud-load-tests.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment]
Thank you for your feedback. I have passed this on to the product team for advice.

**Comment by PBoraMSFT** [comment]
@seelamk - no, this is currently not supported for HAR based tests.
