### ISSUE TITLE
cloud based load test for HTTPs enabled web site

### ISSUE THREAD

**Issue by seelamk** [MicrosoftDocs/vsts-docs#2699]
I have used private rig for load testing.. but i am seeing below error with "The request was aborted: Could not create SSL/TLS secure channel. 

at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
 at Microsoft.VisualStudio.TestTools.WebStress.WebTestTransaction.ResponseReceived(IAsyncResult result)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 46fb478b-e602-c911-28bb-2dc9c9d50b79
* Version Independent ID: d830b560-3735-1c43-49b9-431ea73814bc
* Content: [Record and replay cloud-based load tests with Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/test/load-test/record-and-replay-cloud-load-tests?view=vsts)
* Content Source: [docs/test/load-test/record-and-replay-cloud-load-tests.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/test/load-test/record-and-replay-cloud-load-tests.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment]
Thank you for your feedback. I have passed this on to the product team for advice.

**Comment by PBoraMSFT** [comment]
@seelamk - If the website you are trying to test uses TLS 1.2, then that is not supported by default. You will need to create a webtest plugin [link](https://social.msdn.microsoft.com/Forums/vstudio/en-US/bc3ebf23-575d-4e54-bd6b-a1ed87fe5213/web-performance-test-is-not-working-with-tls12-enabled) to use TLS 1.2.

If your question is not related to TLS 1.2, please log a bug on the [developer community](https://developercommunity.visualstudio.com/spaces/21/index.html)
