### ISSUE TITLE
There is no "Visual Studio template" shown in TFS 2018.

### ISSUE THREAD

**Issue by RubixRevenge** [MicrosoftDocs/vsts-docs#270]
"3. Select the Visual Studio template." There is no Visual Studio template shown in TFS 2018.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a56478c9-7dfc-43e9-c348-357dc6862d73
* Version Independent ID: dd3cd0a1-dc03-15d3-1298-b76d770e4760
* [Content](https://docs.microsoft.com/en-us/vsts/build-release/apps/aspnet/build-aspnet-dacpac)
* [Content Source](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/build-release/apps/aspnet/build-aspnet-dacpac.md)
* Service: unspecified

**Comment by Yawarmurtaza** [comment]
Not available on TFS 2017.

**Comment by Yawarmurtaza** [comment]
It worked for me - I used .Net Desktop template and got rid of Nuget and test tasks. I have a successful build and the drop folder contains docpack file under bin/release folder.

**Comment by RubixRevenge** [comment]
In my case, I'm using TFS 2018. I [re-read the page](https://docs.microsoft.com/en-us/vsts/build-release/apps/aspnet/build-aspnet-dacpac) to see if I missed any "but first install X" gotchas. Nope. There no reference to anything else that needs to be installed.

**Comment by Yawarmurtaza** [comment]
There is nothing to install. The .Net Desktop template come under the default list of templates. I think they should have said select .Net Desktop template instead of saying Visual Studio template. 
Hope this helps!

**Comment by RubixRevenge** [comment]
"I think they should have said..." I can work with that.

**Comment by alexhomer1** [comment]
Thank you for your feedback. We will update the topic.
