### ISSUE TITLE
Adding correct build service identity to feed

### ISSUE THREAD

**Issue by adhishchugh** [MicrosoftDocs/vsts-docs#2700]
Hey, when I try to deploy a maven build jar to a feed, I get a 401 unauthorized error. I've selected the "Authenticate built in maven feed" parameter. Is there anything else I need to do? 
Is there any documentation on adding the correct build service identity to the feed?
Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 60230978-ce5b-6964-23ba-1dd31b1fa1c9
* Version Independent ID: 9b1eb982-b07a-8b67-ab0b-b2a4d3dade12
* Content: [Use Maven artifact feeds - Azure Artifacts](https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/maven?view=vsts)
* Content Source: [docs/pipelines/artifacts/maven.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/artifacts/maven.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by elbatk** [comment]
I've seen a couple of things about this article where the authentication doesn't seem to work itself out as the article says. @alexmullans could you investigate and circle back here if we need a documentation change?

**Comment by KoduIsGreat** [comment]
I'm having the exact same issue, The way i solved it is by using gradle and using the auth token as a variable in the build... its kinda messy but it works until this issue gets resolved. unfortunately maven auth doesn't magically happen as they state it does.  

1+ if you guys can suggest a better solution

**Comment by naveenav** [comment]
Hi All, we are struggling with the same issue. Any resolution will be appreciated.

**Comment by elbatk** [comment]
Hi everyone, I wanted to let you know that for product issues, it would be best to post to the [Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html). It's actively monitored by the product team, so you'll get faster and better traction. However, I have seen this issue before so I'd like to update our docs if there's a need, so I'll leave this issue here open for a bit.

**Comment by alexmullans** [comment]
@elbatk would probably be good to add a link to this section of the permissions page: https://docs.microsoft.com/en-us/azure/devops/artifacts/feeds/feed-permissions?view=vsts&tabs=new-nav#package-permissions-in-azure-pipelines

The page should also mention that you need to check the "Authenticate to built-in Maven feeds" box here: 
![image](https://user-images.githubusercontent.com/483400/50237870-ceab5200-0372-11e9-9b0f-6ad675301486.png)

**Comment by ManuelGalindo** [comment]
@alexmullans We tried that and we hit the same status code 401
From Build Logs

`[ERROR] Failed to execute goal on project enterprise-mainframe-system-api: Could not resolve dependencies for project com.MYPROY.enterprise:enterprise-mainframe-system-api:mule-application:1.0.0-SNAPSHOT: Failed to collect dependencies at com.MYPROY:enterprise-global-exception-handler:jar:1.0.0-RELEASE: Failed to read artifact descriptor for com.MYPROY:enterprise-global-exception-handler:jar:1.0.0-RELEASE: Could not transfer artifact com.MYPROY:enterprise-global-exception-handler:pom:1.0.0-RELEASE from/to ecolab-visualstudio-com-ecolab-arcs-source_internal (https://ecolab.pkgs.visualstudio.com/_packaging/arcs-source_internal/maven/v1): Unauthorized (401) -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal on project enterprise-mainframe-system-api: Could not resolve dependencies for project com.myproy.enterprise:enterprise-mainframe-system-api:mule-application:1.0.0-SNAPSHOT: Failed to collect dependencies at com.MYPROY:enterprise-global-exception-handler:jar:1.0.0-RELEASE`

For sanity check we used the URL (to confirm the package exist on the feed and worked)
Also making this restore from a local machine works as a charm

**Comment by alexmullans** [comment]
OK, sorry about that. Can you post this on [Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html)?

**Comment by amgadalaa** [comment]
You need to add the following line to your maven pipeline 
mavenAuthenticateFeed: true

**Comment by mineyannik** [comment]
Still not working:
Return code is: 401, ReasonPhrase: Unauthorized. -> [Help 1]

**Comment by yevster** [comment]
I'm guessing (and this is only a guess) that the reason why this is not working has to do with [this issue](https://github.com/Microsoft/azure-pipelines-tasks/issues/8897). 

Until this is fixed, use the following workaround:
1. Create a "settings.xml" file locally, using the snippet generate in the "Connect to Feed" tab under Artifacts.
2. Upload this settings.xml as a secret file.
3. Add a "Download Secret File" task to the beginning of your build pipeline. Make sure you set the output reference to something meaningful, e.g. "secretxml".
4. Immediately after the above task, add a PowerShell task to run the following inline script:
```powershell
New-Item -Type Directory -Force "${HOME}/.m2"
Copy-Item -Force "$(settingsxml.secureFilePath)" "${HOME}/.m2/settings.xml"
```

**Comment by vvoinov** [comment]
This feature worked for some projects and then suddenly stooped working :( 
I posted it at Developer Community as well - [link](https://developercommunity.visualstudio.com/content/problem/451589/maven-fails-to-download-and-deploy-to-artifact-wit.html). Very sad - we need to get back to using settings.xml and pipeline env varaiables to keep pipelines buildable  - it is very annoying.

**Comment by smaziano** [comment]
Use:
  mvn deploy --settings="settings.xml" 
instead of 
  mvn deploy

I'm assuming you're where your settings file is located.

**Comment by elbatk** [comment]
Hey everyone, I want to close this because we've swapped from our old Maven task and are encouraging people to try our new [Maven Authenticate Task](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/package/maven-authenticate?view=azure-devops), but I'd like to get people trying it and get feedback before I do that. Any help would be appreciated.

**Comment by soccerjoshj07** [comment]
@elbatk  , the [Maven Authenticate Task](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/package/maven-authenticate?view=azure-devops) worked great for me!
