### ISSUE TITLE
Users should be allowed to replace non-edited default pull request templates

### ISSUE THREAD

**Issue by eddylu94** [MicrosoftDocs/vsts-docs#2702]
Currently, VSTS pull requests only allow a user to "append" the description field when adding an alternative pull request template from the "Add a template" drop-down. However, there exists a common scenario in which a user creates a new pull request with the intent of using an alternative pull request template other than the default template. For this scenario, the user has to manually clear the description field of the pull request prior to adding the desired alternative template.

Perhaps an action item should be created that will allow users to conveniently replace non-edited pull request descriptions, that have been pre-populated with default pull request templates, with the desired alternative templates.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a297d54f-48b3-1b68-e828-15d1559d9b2d
* Version Independent ID: fd9dcb35-72f9-f5a9-e0c0-75c3e59ba8d9
* Content: [Improve your pull request descriptions using pull request templates - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/pull-request-templates?view=vsts#additional-pull-request-templates)
* Content Source: [docs/repos/git/pull-request-templates.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/repos/git/pull-request-templates.md)
* Product: **devops**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
@eddylu94 That is a great feature idea. I am going to pass that along to the product team. Feature requests and product feedback carry more weight when they come directly from customers, so if you had a moment, please file your request here and it will go straight to the team: https://developercommunity.visualstudio.com/spaces/21/index.html

Thank you.
