### ISSUE TITLE
It would be good to include a link to creating NuGet packages for the project so you are setup to take advantage of Artifacts. 

### ISSUE THREAD

**Issue by rguthriemsft** [MicrosoftDocs/vsts-docs#2703]
Not sure where best to put it but it would be good to have a link to https://docs.microsoft.com/en-us/nuget/create-packages/creating-a-package in the doc.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a10a409-5468-9532-f0dc-5a28cdd566d8
* Version Independent ID: 2ef20266-bc45-448b-27f5-e5c3bffed2ef
* Content: [Get Started with NuGet Azure Artifacts in Azure DevOps Services and TFS](https://docs.microsoft.com/en-us/azure/devops/artifacts/get-started-nuget?view=vsts&tabs=new-nav)
* Content Source: [docs/artifacts/get-started-nuget.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/artifacts/get-started-nuget.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by chasewilson** [comment]
Hi @rguthriemsft, Thank you for the feedback!. It's taken a bit but the documentation will now (on the next release) let the user choose to use the demo package or create a package of their own by linking the suggested article. If you have any more feedback feel free to reach out!
