### ISSUE TITLE
The example urls do not work 

### ISSUE THREAD

**Issue by StingyJack** [MicrosoftDocs/vsts-docs#2709]
most of them 404. 

As an example, Ive tried the query in various combinations...

- `https://onpremserver.domain.com/_apis/notification/subscriptionquery` - per example  
- `https://onpremserver.domain.com/tfs/_apis/notification/subscriptionquery` - what the examples used to have for on prem
- `https://onpremserver.domain.com/tfs/DefaultCollection/_apis/notification/subscriptionquery` - with the collection name  
- `https://onpremserver.domain.com/tfs/DefaultCollection/SomeTeamProject/_apis/notification/subscriptionquery` - with the collection name and project name

.... OH. Someone made the query REST api into a POST request. This is unexpected but still gives the same 404 result using the powershell script below.

``` powershell
Clear-Host
$Error.Clear()
$url = <from above>
$res = Invoke-WebRequest -Uri $url -Method Post  -UseDefaultCredentials
$res
```
the error
``` 
Invoke-WebRequest : Error
The page you are looking for is currently unavailable.
Page not found.
 More information about this error
Page not found.
Things you can try:
Refresh the current page 
Go back to the previous page 
Sign in as a different user 
Submit feedback to Microsoft about this error 
Microsoft Visual Studio Team Foundation Server
© Microsoft Corporation. All rights reserved. 
At line:5 char:8
+ $res = Invoke-WebRequest -Uri $url -Method Post  -UseDefaultCredentia ...
+        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 04e7c9e4-500d-7809-3197-c324050927f8
* Version Independent ID: 93fc1005-cebf-128b-ea3c-5f698e033ed4
* Content: [Notification subscriptions](https://docs.microsoft.com/en-us/azure/devops/integrate/previous-apis/notification/subscriptions?view=tfs-2015#query)
* Content Source: [docs/integrate/previous-apis/notification/subscriptions.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/integrate/previous-apis/notification/subscriptions.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by StingyJack** [comment]
@elbatk - The reason was "on Premise TFS 2015". While I'm not personally using that any longer, there are some who are and that would probably appreciate not being confused with broken/unusable docs for the next 5-6 years while that product is still in mainstream support. 

Its not the first time I've asked for these examples to be corrected, specifically for this reason. It feels like both the rest API docs and the VS marketplace are trying very hard to pretend that on prem has never existed.

**Comment by chcomley** [comment]
Hi @StingyJack, It looks as if this issue was addressed a few months ago, as I'm not seeing the examples you provided. I'll be closing this issue, however do respond if you'd like to request any further clarification or changes in the documentation, and then we'll create a new issue. Thanks very much.
