### ISSUE TITLE
Step 7 for TFS 2017

### ISSUE THREAD

**Issue by Tankatronic** [MicrosoftDocs/vsts-docs#271]
This step is deprecated for TFS 2017 and can be skipped

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f6f911f3-a2a9-6440-036c-8286b668c9f7
* Version Independent ID: 2d682124-3d0a-c46e-f343-ea4e93809055
* [Content](https://docs.microsoft.com/en-us/vsts/tfs-server/admin/backup/restore-data-different-instance#step-7-prepare-sql-server-for-team-foundation-server)
* [Content Source](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/tfs-server/admin/backup/restore-data-different-instance.md)
* Service: unspecified

**Comment by elbatk** [comment]
Thanks @Tankatronic , I know this was forever ago, but working on clearing out our backlog. I'm making this change!
