### ISSUE TITLE
Stage general options 

### ISSUE THREAD

**Issue by SamirFarhat** [MicrosoftDocs/vsts-docs#2713]
I think we mean '''Stage owners are not automatically assigned any additional permissions.' instead of ''Stage owners are not automatically assigned any addition permissions.''

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4266f72c-c774-0046-4593-d01eb775d3c3
* Version Independent ID: f20827aa-a6c5-96a8-5969-e576ffbc2e38
* Content: [Stages in Azure Pipelines - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/environments?view=vsts)
* Content Source: [docs/pipelines/release/environments.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/release/environments.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment]
Thank you for your feedback. I will update the topic to include your recommendations.
