### ISSUE TITLE
Term inconsist between the "phase" and "job"

### ISSUE THREAD

**Issue by cbfrank** [MicrosoftDocs/vsts-docs#2715]
Are "job" is the new name of "phase" in azure build pipeline? All azure build pipeline documents about Yaml use "job", but the exported Yaml of an existing azure build pipeline (created with the visual disigner) use "phase" in Yaml.
It a little confused for a beginner which want to learn the Yaml from an existing build pipeline.

**Comment by alexhomer1** [comment]
Thank you for your feedback. Yes, the term "phase" is being replaced by "job". There may still be references to phases in some parts of the product, especially in previous releases of Team Foundation Server.
