### ISSUE TITLE
2 types of links to remote work items not 3

### ISSUE THREAD

**Issue by BrickOven** [MicrosoftDocs/vsts-docs#2717]
Hi - minor correction
In this section
[Link to a remote work item
](https://docs.microsoft.com/en-us/azure/devops/boards/backlogs/add-link?view=vsts&tabs=browser#link-to-a-remote-work-item)
Text is: Choose from one of the following **three** remote link types supported.
Text should be: Choose from one of the following **two** remote link types supported.

There are only two items in the list below the sentence

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a0aa4019-9343-7791-d5e6-d68063cea6c4
* Version Independent ID: a165a19b-2caa-f7f3-d202-1ca4d1e20049
* Content: [Link user stories, issues, bugs, and other work items - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/backlogs/add-link?view=vsts&tabs=browser)
* Content Source: [docs/boards/backlogs/add-link.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/boards/backlogs/add-link.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@BrickOven - Thanks for the correction. Article is getting updated.
