### ISSUE TITLE
What permissions are required to create links

### ISSUE THREAD

**Issue by BrickOven** [MicrosoftDocs/vsts-docs#2718]
I can't find anywhere in the documentation the permissions required to create a parent/child link to a work item in another project. The user only requires change in the project where they are creating a link. They can successfully create a link even if they only have read in the project they are linking from.

Since the link information shows up on work items I was thinking contributor would be required to create links in both projects but it seems Contributor in one and read in the other is enough.

It might be good to call this out somewhere.

The Setup - 2 Projects, 1 user - Jane Fabrikam, both use the Scrum template and are in the same Azure DevOps organization.
Project 1: CorporateObjectives - Jane was added to the readers project group
Project 2: ProductX - Jane was added to the project administrators group

Jane can successfully create a parent link to a work item from a feature in the product X project to an Epic in the CorporateObjectives project.

 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3a3b3b65-bfe8-442f-c649-24c3157f0bc7
* Version Independent ID: caa7762c-6e14-4e5f-fa81-bfa2e1c85964
* Content: [Default work tracking permissions & access - Azure Boards & TFS](https://docs.microsoft.com/en-us/azure/devops/organizations/security/permissions-access-work-tracking?view=vsts)
* Content Source: [docs/organizations/security/permissions-access-work-tracking.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/security/permissions-access-work-tracking.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@BrickOven - Thank you for your inquiry. Apologies for the delayed response. You bring up a good question and I have added to my backlog to update content around link permissions. There are no explicit link permissions - but clarifying the work tracking permissions required to support linking is a good idea.
