### ISSUE TITLE
What are the consequences when enabling and later disabling Features and Epics?

### ISSUE THREAD

**Issue by rschindhelm-haba** [MicrosoftDocs/vsts-docs#2723]
I'm wondering if those hierarchy levels can be enabled and disabled at any given time and what the consequences would be.
Any insights on this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 13e0835d-3a94-c06c-8e38-e22598884b26
* Version Independent ID: b19ea878-26f8-7607-9a63-9846e0ab511b
* Content: [Select backlog navigation levels - Azure DevOps & TFS](https://docs.microsoft.com/en-us/azure/devops/organizations/settings/select-backlog-navigation-levels?view=vsts&tabs=new-nav)
* Content Source: [docs/organizations/settings/select-backlog-navigation-levels.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/settings/select-backlog-navigation-levels.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@rschindhelm-haba - Thank you for your inquiry. there are no consequences. Any team can enable or disable the features and backlogs for their team at any time. The only consequence is that the team doesn't have access to a feature or epic backlog and board.  A Project Administrator can also completely [disable the Epic or Feature work item type](https://docs.microsoft.com/en-us/azure/devops/organizations/settings/work/customize-process-wit?view=vsts&tabs=new-nav#enable-or-disable-a-wit) without consequence. This would disable being able to create work items with the associated type - but any work items already create are still accessible and remain in the data store.

**Comment by rschindhelm-haba** [comment]
@KathrynEE Great. Thank you for clarifying.
