### ISSUE TITLE
How to use latest version of nuget.exe?

### ISSUE THREAD

**Issue by loic-sharma** [MicrosoftDocs/vsts-docs#2724]
I have a NuGet task that pushes my nupkg and snupkg to nuget.org. It seems that the default nuget.exe on Azure DevOps is nuget.exe v4.1, which cannot push snupkg files (nuget v4.1 client incorrectly pushes the snupkg as a nupkg, causing nuget.org to return an HTTP 409 response). How can I use nuget.exe 4.9.1 to do an authenticated push to nuget.org on Azure DevOps? Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 11ed58a1-5819-f3a4-c674-dafcdbd56fbc
* Version Independent ID: d68aca4d-3fd3-1864-09f5-6060295e0399
* Content: [Publishing to NuGet feeds - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/nuget?view=vsts&tabs=yaml#publish-your-packages)
* Content Source: [docs/pipelines/artifacts/nuget.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/artifacts/nuget.md)
* Product: **devops**
* GitHub Login: @erickson-doug
* Microsoft Alias: **amullans**

**Comment by alexmullans** [comment]
The [NuGet Tool Installer task](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/nuget?view=vsts) will help.

**Comment by loic-sharma** [comment]
Ah, that's good to know! Should we add a note for this on the `Publishing to NuGet feeds` page? Ideally, that documentation should have a section dedicated for snupkgs. I can send a pull request if y'all would like

**Comment by alexmullans** [comment]
Sure! We always appreciate PRs. /cc @elbatk to review when it's ready.

**Comment by elbatk** [comment]
Hi @loic-sharma , checking in here to see if you're still interested in submitting this PR, let me know :)
