### ISSUE TITLE
Category

### ISSUE THREAD

**Issue by mikederksen** [MicrosoftDocs/vsts-docs#2725]
In the example-json for the task.json it says:

"categories": [
"Azure Pipelines"
],

When deploying this to the marketplace, I'm given the error "The task.json for contribution buildAndReleaseTask could not be deserialized.Unexpected character encountered while parsing value: [. Path 'category', line 7, position 17"

Changing the category to "category": "Azure Pipelines" fixes this issue

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 44581f4a-93df-7507-3844-eadedf9a6cc4
* Version Independent ID: 33c7bcf0-1512-975f-5ef8-9f2a192a84ad
* Content: [Add a Build or Release Task](https://docs.microsoft.com/en-us/azure/devops/extend/develop/add-build-task?view=vsts#step-3-create-the-extension-manifest-file)
* Content Source: [docs/extend/develop/add-build-task.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/extend/develop/add-build-task.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by elbatk** [comment]
Hi @mikederksen . I believe the article is correct. The confusing thing is: in the extension manifest file, it is "categories", but in the task.json, it is "category". Does that line up with your experience and the article?

**Comment by mikederksen** [comment]
Hi @elbatk , This lines up with what I have in my task.json and manifest file, yes. It's however about the content of the task.json file. The instructions tell me that I should have the following in my task.json file:

```
{
    "id": "some-guid",
    "name": "FancyTask",
    "friendlyName": "Fancy Task",
    "description": "Description of my fancy task",
    "helpMarkDown": "",
    "category": [
        "Azure Pipelines"
    ],
   "more properties....": "etc..."
```

When I deploy this to the marketplace it tries to parse my files. It then gives the error I described in my original question. Changing the task.json content to the example below, the marketplace gives a success message and lets me deploy my extension successfully:

```
{
    "id": "some-guid",
    "name": "FancyTask",
    "friendlyName": "Fancy Task",
    "description": "Description of my fancy task",
    "helpMarkDown": "",
    "category": "Azure Pipelines",
   "more properties....": "etc..."
```

Note the 'category' property. I removed the '[' and ']'. This seems to fix the error given by the marketplace.

**Comment by harishkragarwal** [comment]
Sorry for the confusion here. Our documentation was in a faulty state and have just completed a PR to fix it.  In your task.json please have it as 

 "category": "Utility"

'Azure Pipelines' is not a category to be used in the task.json. 
I expect the documentation update to be reflected in a day. Or in the worst case post the new year.
