### ISSUE TITLE
Missing info about how to fire an event like refresh from your extension within a workitem extension

### ISSUE THREAD

**Issue by DalpheSDC** [MicrosoftDocs/vsts-docs#2727]
Hi

we are missing information how to interact with a work item event. Like firing an event like refresh or save from the extension.

regards

Peter Dahl

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 59e5d359-480e-bb6d-04d9-45510ae3788b
* Version Independent ID: 06b2073e-795e-d7ce-6112-9610509e2000
* Content: [Extend the work item form](https://docs.microsoft.com/en-us/azure/devops/extend/develop/add-workitem-extension?view=vsts#feedback)
* Content Source: [docs/extend/develop/add-workitem-extension.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/extend/develop/add-workitem-extension.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by elbatk** [comment]
Hi @DalpheSDC , does this blog post help? https://blogs.msdn.microsoft.com/devops/2017/11/13/creating-work-item-form-extensions-in-visual-studio-team-services/

**Comment by elbatk** [comment]
Hi @DalpheSDC , we haven't heard from ya in a bit so I'm going to close this issue out. Let us know if you're having problems still.
