### ISSUE TITLE
On-premise GitHub compatibility

### ISSUE THREAD

**Issue by ohelin2** [MicrosoftDocs/vsts-docs#2728]
Is it possible to connect an on-premise GitHub repository with Azure DevOps ?

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 04afcda8-8a01-6fda-8387-778feaba9fea
* Version Independent ID: a0c518ee-dc43-42a6-07d9-150dfa8724c3
* Content: [Connect a project in Azure DevOps Services with a GitHub repository - Azure Boards](https://docs.microsoft.com/fr-fr/azure/devops/boards/github/connect-to-github?view=vsts)
* Content Source: [docs/boards/github/connect-to-github.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/boards/github/connect-to-github.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@ohelin2 - That feature isn't supported at this time. You may want to suggest this as a new feature through our developer community page, https://developercommunity.visualstudio.com/spaces/21/index.html.
