### ISSUE TITLE
Opening a solution in VS test pro 2017

### ISSUE THREAD

**Issue by Abutu** [MicrosoftDocs/vsts-docs#2729]
There is a steps of Associating your test
"Open your solution in Visual Studio 2017 Enterprise, Professional, or Test Professional, or a later version."
https://docs.microsoft.com/en-us/azure/devops/test/associate-automated-test-with-test-case?view=vsts

Can you actually open a solution on VS 2017 Test Pro? There is only a thick client MTM but couldn't find a VS IDE.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7d8a7e40-73d6-795f-7b8c-77104ef606e8
* Version Independent ID: 8f15995b-bd94-8d9f-1e8b-82f1f364d221
* Content: [Associate automated tests with test cases - Azure Test Plans](https://docs.microsoft.com/en-us/azure/devops/test/associate-automated-test-with-test-case?view=vsts)
* Content Source: [docs/test/associate-automated-test-with-test-case.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/test/associate-automated-test-with-test-case.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by nschonni** [comment]
Also from https://visualstudio.microsoft.com/vs/pricing/ for Test Professional
> No Visual Studio IDE included in subscription, but subscribers can use Visual Studio Code (free for anyone) and Visual Studio Community (free for open source projects, classroom learning, and academic research, plus for any use by up to 5 people in small organizations)

**Comment by PBoraMSFT** [comment]
@alexhomer1 - mention of Test Professional is incorrect. There is no IDE for that edition. Also, we need to make this agnostic of VS versions, now that VS 2019 Preview 1 is available. The steps are applicable to VS 2017 and above versions. Can you please fix the docs?

**Comment by alexhomer1** [comment]
Updates to teh topic will be published soon.
