### ISSUE TITLE
TFS 2018 Access Levels

### ISSUE THREAD

**Issue by Hal-Cenlar** [MicrosoftDocs/vsts-docs#273]
Does TFS 2018 not support using TFS groups for Access Levels?  I seem to only be able to add users or AD groups.  This means if I don't want to add an AD group I need to manage membership at both the Access Levels and the groups in TFS.  Am I understanding this correctly?  The document is unclear on this item.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bb8b2f77-9933-f598-e213-8f72b6cadf13
* Version Independent ID: 8c556e96-b356-6142-9d94-3f8cf8ce3b56
* [Content](https://docs.microsoft.com/en-us/vsts/security/change-access-levels)
* [Content Source](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/security/change-access-levels.md)
* Service: unspecified

**Comment by elbatk** [comment]
Hi @Hal-Cenlar , thanks for this and sorry for the delay - I'm going to forward this to the product team and try to get an answer for you shortly!

**Comment by elbatk** [comment]
I know this has been open forever, doing some backlog cleaning. @chcomley I believe you cover organizations/security now? It may be that @Hal-Cenlar has already found an answer, but I'm not sure who to reach out to for this now.

**Comment by chcomley** [comment]
The mentioned article has been updated numerous times since March 2018, which was almost 1 year ago. I'm closing this issue, however, @Hal-Cenlar please do let us know if it remains unclear or if you have any other questions. Thanks!
