### ISSUE TITLE
Windows: Registration script does not work behind proxy

### ISSUE THREAD

**Issue by geofflamrock** [MicrosoftDocs/vsts-docs#2731]
Hi,

I'm not sure if this is the correct spot to raise this, apologies if it is not. 

The registration script for powershell in Windows that gets shown in a deployment group doesn't work when the user is behind a proxy, it detects the proxy ok but the download of the agent zip file fails as the credentials are not set properly on the proxy.

Adding `$WebClient.Proxy.Credentials =[System.Net.CredentialCache]::DefaultNetworkCredentials` to the script seems to make it work.

If this would be able to be fixed in the registration script that would be great.

Thanks :)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e47a1942-09cb-f294-f1d3-09999645afb7
* Version Independent ID: 7b885f66-7165-ae4f-d35f-3cffe84cce28
* Content: [Run the agent behind a web proxy - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/proxy?view=vsts&tabs=windows)
* Content Source: [docs/pipelines/agents/proxy.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/agents/proxy.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by vtbassmatt** [comment]
Thanks for raising the issue. This is probably better suited for https://github.com/Microsoft/azure-pipelines-agent/issues.

**Comment by awentzel** [comment]
@geofflamrock did you end up creating a new issue for this?  I have an agent running, but, jobs are just queuing and not running so looking for a solution.  Thanks

**Comment by geofflamrock** [comment]
@awentzel I have raised the issue now, not sure if you are facing the same thing as our issue was during installation, once the agent was running deployments were fine.
