### ISSUE TITLE
Use multiplier variable in Custom condition

### ISSUE THREAD

**Issue by qualmon** [MicrosoftDocs/vsts-docs#2733]
In the Custom condition of a Phase, can we reference a multiplier variable? For example, given a user variable 'myvar' specified as a multiplier on the Phase, with the values 'foo, bar'. Can we somehow use variables['myvar'] or similar to get the value 'foo' in the first instance of the phase and 'bar' in the second?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f151218-9a11-0078-e038-f96198a76143
* Version Independent ID: 09c4d032-62f3-d97c-79d7-6fbfd89910e9
* Content: [Conditional tasks - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/conditions?view=vsts&tabs=yaml)
* Content Source: [docs/pipelines/process/conditions.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/conditions.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by vtbassmatt** [comment]
I don't believe this is wired up for designer builds. In YAML, it's a [dependency](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/conditions?view=vsts&tabs=yaml#dependencies).

**Comment by vijayma** [comment]
This might be a bug or a limitation of how we evaluate the variables. It looks like the value of variables['myvar'] is 'foo, bar' when evaluated in the condition of the job. However, the value of $(myvar) is correctly set to either 'foo' or 'bar' inside each of the two jobs. We will get a developer to look at this and see what is going on here.

**Comment by vtbassmatt** [comment]
@ericsciple do you have any thoughts on this one?

(Ignore my Dec 13 comment; I think it was wrong.)

**Comment by ericsciple** [comment]
@qualmon Unfortunately no. The phase condition is evaluated once, before the matrix is evaluated.

To implement the behavior you desire, it sounds like we would need to flip the order. The condition would need to be evaluated for each job produced by the matrix.

Based on where we are going with the phase concept (deployment phases, which dynamically generate N jobs), I don't think we will flip the order. I believe we need it be evaluated at the phase (before matrix expansion), not per job.

**Comment by vtbassmatt** [comment]
This is a product change request, not a doc issue. I don't think we can make such a change. If you want to pursue it, though, please file a request at [Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html).

The best workaround I can think of: use $(myVar) as a condition on each task.
