### ISSUE TITLE
App title is confusing

### ISSUE THREAD

**Issue by adriangodong** [MicrosoftDocs/vsts-docs#2734]
Is the app title "Azure DevOps Services" (as in the step 2) or "Visual Studio Team Services" (as in the step 2's image) -- apparently the image won. Please fix so we can find the app easily.

And the issue below is still valid -- the screenshot is way outdated. Please update.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7fd5671b-b7b8-9acb-c195-7897fec3538b
* Version Independent ID: ff894c1b-f2f7-581d-94b4-dbc77d80ad6d
* Content: [Slack with Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/service-hooks/services/slack?view=vsts)
* Content Source: [docs/service-hooks/services/slack.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/service-hooks/services/slack.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by elbatk** [comment]
Hi @adriangodong , I believe we have a plan for revamping all of the Service Hook documentation. It's quite expensive to try to keep all of these articles updated as they are all require accounts for different products. Thank you for your feedback.
