### ISSUE TITLE
No delete option

### ISSUE THREAD

**Issue by Knnthra** [MicrosoftDocs/vsts-docs#2735]
I don't have the option to delete the repo, I can only rename it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b03af1d9-4eeb-ac18-d517-a0a44a2478be
* Version Independent ID: 842691c8-8c41-facf-2cff-03542262f2e5
* Content: [Delete a Git repo from your project - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/delete-existing-repo?view=vsts&tabs=new-nav)
* Content Source: [docs/repos/git/delete-existing-repo.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/repos/git/delete-existing-repo.md)
* Product: **devops**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
@Knnthra If the repo is the only Git repo in your project, you can't delete it until you first [create another repo](https://docs.microsoft.com/en-us/azure/devops/repos/git/create-new-repo?view=vsts). You must also have [Delete Repository permissions](https://docs.microsoft.com/en-us/azure/devops/organizations/security/set-git-tfvc-repository-permissions?view=vsts#git-repository) to delete a repo from a project.

Do either of those conditions apply? If not, could you show me a screenshot and maybe I can help from that?

Thank you.

**Comment by sergAleshchenko** [comment]
Wtf? 
Isn't it too complicate to add the "Delete repository" button to main page of the repo (as in git web interface)?

**Comment by J0hnRoger** [comment]
Even when we have a VSTC project, we can't delete the git project ...
![image](https://user-images.githubusercontent.com/749433/51691196-a1e5fc80-1ffa-11e9-9d4f-3a2f38deab6c.png)

**Comment by sergAleshchenko** [comment]
I solve the problem. Deletion is available in "Organization settings" ->
"Projects" -> "..." (near the project name).

**Comment by NodeJSmith** [comment]
> I solve the problem. Deletion is available in "Organization settings" -> "Projects" -> "..." (near the project name).

This deletes the Project, not the repo.

**Comment by sergAleshchenko** [comment]
I think the repo will be available for deletion only after creating another
one. Azure wrap looks strange in comparison with usual git or bitbucket =)

чт, 24 янв. 2019 г., 21:48 Smith notifications@github.com:

**Comment by JohnGoldsmith** [comment]
If delete option were available even on a single repo then it could also add a temporary repo by default.  Currently to 'reset' a single repo with the same name you have to add a new temporary repo, delete your original, then add a new one of the same name and finally delete your temporary repo.
