### ISSUE TITLE
"Administer account features" link is broken

### ISSUE THREAD

**Issue by paulmarshall** [MicrosoftDocs/vsts-docs#2736]
Clicking on this link does nothing

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8db47b85-e178-7969-40d3-3fa83aa3fb54
* Version Independent ID: a78e453b-4b8f-c885-42ee-8a9d9979f345
* Content: [What access levels are supported? - Azure DevOps & TFS](https://docs.microsoft.com/en-us/azure/devops/organizations/security/access-levels?view=vsts#administer-account)
* Content Source: [docs/organizations/security/access-levels.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/security/access-levels.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@paulmarshall - thank you for the feedback. Corrections to this article are now being made.
