### ISSUE TITLE
Duplicated tabs

### ISSUE THREAD

**Issue by turibbio** [MicrosoftDocs/vsts-docs#2737]
In "View your personal notifications" section I see 2 previous version tab

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c2fdc7bf-dd88-5f39-cfaf-77dca428990e
* Version Independent ID: c939066c-c671-7f50-3ba3-9916b0f4cd4c
* Content: [Manage personal notification settings - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/notifications/howto-manage-personal-notifications?view=tfs-2017&tabs=previous-nav%2Cnew-nav#view-your-personal-notifications)
* Content Source: [docs/notifications/howto-manage-personal-notifications.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/notifications/howto-manage-personal-notifications.md)
* Product: **devops**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
@turibbio Thanks for the heads up. Currently working on it and will push a fix to master today. Thanks again!
