### ISSUE TITLE
Deployment group job [more information] link is pointing to this documentation which is wrong

### ISSUE THREAD

**Issue by a-mosheh** [MicrosoftDocs/vsts-docs#2741]
Deployment group job help [more information] link is pointing to https://go.microsoft.com/fwlink/?LinkId=852588 which is wrong.
It should be pointing to https://docs.microsoft.com/en-us/azure/devops/pipelines/process/deployment-group-phases?view=vsts&tabs=yaml

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72b90dd0-49f9-4ed4-3010-9a64dde6ae5a
* Version Independent ID: 6e679d50-4e94-eee3-8793-af884cc909ca
* Content: [Service connections in Azure Pipelines and Team Foundation Server - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/library/service-endpoints?view=vsts)
* Content Source: [docs/pipelines/library/service-endpoints.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/library/service-endpoints.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by a-mosheh** [comment]
or this https://docs.microsoft.com/en-us/azure/devops/pipelines/release/deployment-groups/index?view=vsts

**Comment by alexhomer1** [comment]
Thank you for your feedback. This is an issue in the product, not the documentation. I've passed it to the development team for them to correct the redirection entry.
