### ISSUE TITLE
No  new testplan button

### ISSUE THREAD

**Issue by Knnthra** [MicrosoftDocs/vsts-docs#2742]
I'm unable to see the no new testplan button when I try to create  a test plan

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c8e2cb79-709d-972b-6747-6d26c965fb2a
* Version Independent ID: d512ea69-a97a-e5ff-a804-6691c5dfe1e6
* Content: [Create a test plan - Azure Test Plans](https://docs.microsoft.com/en-us/azure/devops/test/create-a-test-plan?view=vsts)
* Content Source: [docs/test/create-a-test-plan.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/test/create-a-test-plan.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment]
Thank you for your feedback. I have passed this on to the product team for advice.

**Comment by harishkragarwal** [comment]
Hi, 
Where are you are trying to locate the '+ New Test Plan' action? 

In my case I am at https://harishkragarwal.visualstudio.com/MyFirstProject/_testManagement/mine and see the following: 
![image](https://user-images.githubusercontent.com/11025866/49884032-ec9c2280-fe59-11e8-9308-1db5cdd3a314.png)

Also do ensure that you have the license to create a Test Plan by having the Test Manager license as listed at https://marketplace.visualstudio.com/items?itemName=ms.vss-testmanager-web#pricing.

**Comment by Knnthra** [comment]
Oh wow @harishkragarwal thank you so much. The problem was with the Test plan license. Added it and now I have the correct options.

**Comment by harishkragarwal** [comment]
Glad, its resolved :)
