### ISSUE TITLE
Error in number of steps

### ISSUE THREAD

**Issue by RWillup** [MicrosoftDocs/vsts-docs#2743]
Hi,

There is an error here:
https://docs.microsoft.com/en-us/azure/devops/extend/develop/add-build-task?view=vsts#steps

The number of steps is 5 or 6 and in the text above it says there are four.

Please update.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 44581f4a-93df-7507-3844-eadedf9a6cc4
* Version Independent ID: 33c7bcf0-1512-975f-5ef8-9f2a192a84ad
* Content: [Add a Build or Release Task](https://docs.microsoft.com/en-us/azure/devops/extend/develop/add-build-task?view=vsts)
* Content Source: [docs/extend/develop/add-build-task.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/extend/develop/add-build-task.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by elbatk** [comment]
Ah, fixing this now, thank you @RWillup . Just going to make it generic :)
