### ISSUE TITLE
How can I reference non-addressable files?

### ISSUE THREAD

**Issue by alanboy** [MicrosoftDocs/vsts-docs#2745]
What are the use cases for non-addressable files? How can I reference them in my extensions?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b68bebb-14b6-8f83-b362-03d643d39538
* Version Independent ID: de6d224b-2a80-b093-0330-4f70b5892fe3
* Content: [Add a Hub](https://docs.microsoft.com/en-us/azure/devops/extend/develop/add-hub?view=vsts)
* Content Source: [docs/extend/develop/add-hub.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/extend/develop/add-hub.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by elbatk** [comment]
Hi @alanboy , I think this question would be better addressed on the [Azure DevOps Services Developer Community site](https://developercommunity.visualstudio.com/spaces/21/index.html), which is monitored by the product team. If there is something you find that you think should be added to the docs, feel free to come back here :)
