### ISSUE TITLE
Web and Load Test test support in Azure DevOps

### ISSUE THREAD

**Issue by cytron201** [MicrosoftDocs/vsts-docs#2746]
Other MSDN pages are listing that Visual Studio 2019 will be the last version to support Performance and Load test projects. Downloading DevOps web tests created in the browser produces a project of this type. What's the long term roadmap here? Difficult to commit to these if there's a limited lifespan.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6e19f646-d820-7582-0672-e5d3b3fe8966
* Version Independent ID: 37f94f23-23bb-3306-840a-1291ca0e66b5
* Content: [Load test before release - Azure Test Plans](https://docs.microsoft.com/en-us/azure/devops/test/load-test/run-performance-tests-app-before-release?view=vsts)
* Content Source: [docs/test/load-test/run-performance-tests-app-before-release.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/test/load-test/run-performance-tests-app-before-release.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment]
Thank you for your feedback. I will pass this on to the product team and update the topic based on their response.

**Comment by nschonni** [comment]
https://devblogs.microsoft.com/devops/cloud-based-load-testing-service-eol/

**Comment by PBoraMSFT** [comment]
@cytron201 - we blogged about the deprecation of the service early this year. You can find the blog post at https://devblogs.microsoft.com/devops/cloud-based-load-testing-service-eol/
