### ISSUE TITLE
Typos in otherwise fantastic resource

### ISSUE THREAD

**Issue by njray** [MicrosoftDocs/vsts-docs#2749]
Change "ot" to "to" here: names just ot achieve political correctness.
Change to "on-premises" (needs end s) here:  from a slower-moving world of on-premise software
Insert "shows" after "Moore" here: Along the way, Tom Moore how we use telemetry

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7e5835c5-57ca-e68d-f033-d97ec7bd106f
* Version Independent ID: 20ff829f-93d5-b3b8-8a34-612a9a5dc841
* Content: [DevOps at Microsoft - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/learn/devops-at-microsoft/)
* Content Source: [https://mseng.visualstudio.com/DefaultCollection/TechnicalContent/_git/devops-learn-pr?path=%2fdocs%2fdevops-at-microsoft%2findex.md&version=GBlive&_a=contents](https://mseng.visualstudio.com/DefaultCollection/TechnicalContent/_git/devops-learn-pr?path=%2fdocs%2fdevops-at-microsoft%2findex.md&version=GBlive&_a=contents)
* Product: **devops**
* Git Login: **samgu**
* Microsoft Alias: **samgu**

**Comment by steved0x** [comment]
@njray I'lll get these fixed and they should be live by tomorrow. Thank you for your feedback.
