### ISSUE TITLE
What is the expected value of Agent.JobName?

### ISSUE THREAD

**Issue by lifesoccult** [MicrosoftDocs/vsts-docs#2751]
Currently when trying to use `Agent.JobName` (in bash, so `$AGENT_JOBNAME`) its value is just `Job`. I expected this to be the name of the Job/Phase, e.g. `Build` or `Build Job` as shown in the build pipeline UI. Here's the yaml and output where I'm trying to test it.

YAML:
```
jobs:
  - job: Build
    pool: 'Local macOS Pool'
    steps:
      - bash: |
          ...
          echo "DEBUG: Agent.JobName is: ${AGENT_JOBNAME}"
          ...
```

Output:
```
2018-12-12T22:28:06.3069500Z ==============================================================================
2018-12-12T22:28:06.3069640Z Task         : Bash
2018-12-12T22:28:06.3069690Z Description  : Run a Bash script on macOS, Linux, or Windows
2018-12-12T22:28:06.3069730Z Version      : 3.142.2
2018-12-12T22:28:06.3069830Z Author       : Microsoft Corporation
2018-12-12T22:28:06.3069880Z Help         : [More Information](https://go.microsoft.com/fwlink/?LinkID=613738)
2018-12-12T22:28:06.3069970Z ==============================================================================
2018-12-12T22:28:06.4757450Z Generating script.
2018-12-12T22:28:06.4844430Z [command]/bin/bash --noprofile --norc /Users/dev1/workspace/_temp/74d89d8f-f8d0-487a-b88a-ec9f0fc50be5.sh
...
2018-12-12T22:28:06.5078660Z DEBUG: Agent.JobName is: Job
...
```

I'm trying to use this value as a grouping ID in influx/grafana, and a value of `Job` clearly does not give enough definition for me to uniquely separate different jobs. To be clear, I expect this value to match the name of the job, which in this case is `Build`. If I am using the incorrect variable, please let me know.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ffebdc8-521c-44b5-cde4-4abdc1bd6f18
* Version Independent ID: dc0effda-6d93-62aa-64c5-4e6f283b0826
* Content: [Predefined build variables - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=vsts)
* Content Source: [docs/pipelines/build/variables.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/build/variables.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by andyjlewis** [comment]
Are you using TFS, Azure DevOps Server 2019, or the Azure DevOps service?

**Comment by vtbassmatt** [comment]
This is a bug we're tracking in the product (1362323 for anyone with access to the internal bug db). As a workaround until it's fixed, you can specify the name in a variable and use it. Example:

```yaml
jobs:
- job: Build
  steps:
  - bash: echo $JOBNAME
  - script: echo %JOBNAME%
  variables:
    JobName: Build
```

**Comment by lifesoccult** [comment]
@vtbassmatt I don't have access to the internal bug db. How will we know when this bug is addressed?

**Comment by vtbassmatt** [comment]
Sorry, there's not a great way to give that level of visibility into the bug tracker.

**Comment by vtbassmatt** [comment]
Finally got to the bottom of this one. The docs are wrong; this variable was supposed to be the job name. We're planning to add a way to get the display name of the job, which will be documented when it's available.
