### ISSUE TITLE
Authentication failed using personal access token

### ISSUE THREAD

**Issue by fakhrulhilal** [MicrosoftDocs/vsts-docs#2754]
I use on premise TFS 2018 update 3 with domain account as authentication. I create a feed and successfully push the package using personal access token with packaging read, write & manage for the scope. But I can't consume the package using the same token, either using nuget CLI or visual studio (2017 15.9.4). It just give error message: 'Response status code does not indicate success: 401 (Unauthorized)'. Here's how I add and consume the feed using cli:
```
nuget sources add -Name Company -Source [on premise url]/tfs/[project]/_packaging/[feed]/nuget/v3/index.json -username [domain user] -password [PAT] -ConfigFile [solution folder]\.nuget\NuGet.config -StorePasswordInClearText
```
VS list the source but couldn't show any package with that error message. When I try to consume using cli `nuget list [keyword] -ConfigFile [solution folder]\.nuget\NuGet.config -source Company`, it prompts for the username & password. The first try fails using domain username and PAT. The second try works by using domain username & password.

Please clarify which one is correct.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab0a3735-a9b0-2ed7-f08f-5321f55f8c90
* Version Independent ID: 2153f6c0-def7-eed1-286d-5e61c9fcbec4
* Content: [Use NuGet with Azure DevOps Services feeds](https://docs.microsoft.com/en-us/azure/devops/artifacts/nuget/nuget-exe?view=vsts&tabs=new-nav)
* Content Source: [docs/artifacts/nuget/nuget-exe.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/artifacts/nuget/nuget-exe.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by elbatk** [comment]
Hi @fakhrulhilal , thank you for your question. 

Could you copy/paste your NuGet config file?

Adding @alexmullans for a heads up, but I'm going to try to figure this one out.

**Comment by fakhrulhilal** [comment]
The original NuGet.config
```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
    <solution>
        <add key="disableSourceControlIntegration" value="true" />
    </solution>
    <packageRestore>
        <add key="enabled" value="True" />
        <add key="automatic" value="True" />
    </packageRestore>
  <packageSources>
    <add key="Company" value="https:/[TFS URL]/tfs/[collection]/_packaging/Internal/nuget/v3/index.json" />
  </packageSources>
  <packageSourceCredentials>
    <Company>
      <add key="Username" value="[Domain Username]" />
      <add key="ClearTextPassword" value="[PAT]" />
    </Company>
  </packageSourceCredentials>
</configuration>
```
It works by changing `ClearTextPassword` to domain password.

**Comment by elbatk** [comment]
I think @alexmullans's advice in the other issue is probably still applicable here. If you open a ticket on the [developer community](https://developercommunity.visualstudio.com/spaces/21/index.html), you'll get a better/faster response from the product team, as this repo is just for docs issues. Thank you and best of luck! If you believe there is a docs change that should come out of this, feel free to come back to this and let me know :)
