### ISSUE TITLE
How to remove?

### ISSUE THREAD

**Issue by dombat** [MicrosoftDocs/vsts-docs#2756]
Need details of how to remove a self-hosted agent

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 47625b86-abd5-ee15-6d61-8bcf81861b96
* Version Independent ID: be9a6174-a69b-7aed-d584-5f602fcc5eb4
* Content: [Build and Release Agents - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/agents?view=vsts)
* Content Source: [docs/pipelines/agents/agents.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/agents/agents.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by LanceMcCarthy** [comment]
You can find instructions on how to remove the agent in the host-specific documentation.

For example, here's the windows version https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/v2-windows?view=vsts#remove-and-re-configure-an-agent

**Comment by pzerger** [comment]
@dombat, you can remove with '/config.sh remove' or by clicking the X to the right of the agent in the pool. Beware the X may be hidden due to Requests pane, but if you resize the requests pane you will find it.
