### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by LouOtway** [MicrosoftDocs/vsts-docs#2758]
In section Delete your AKS cluster
Should be --no-wait not --now-wait

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 31c95c7b-388a-7b39-5283-43193bb643df
* Version Independent ID: 943fc46d-a114-5555-d6e0-6ad2400d1ad0
* Content: [Deploy to Kubernetes on AKS with Jenkins - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/integrate-jenkins-pipelines-aks?view=vsts)
* Content Source: [docs/pipelines/release/integrate-jenkins-pipelines-aks.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/release/integrate-jenkins-pipelines-aks.md)
* Product: **devops**
* GitHub Login: @nicolela
* Microsoft Alias: **nicolela**

**Comment by steved0x** [comment]
@LouOtway Thanks for letting us know, I just merged https://github.com/MicrosoftDocs/vsts-docs/pull/2760 so it should be live soon. Thank you.
