### ISSUE TITLE
Plans to update?

### ISSUE THREAD

**Issue by damoando4** [MicrosoftDocs/vsts-docs#2759]
Excellent detail but any plans to update or move to the GitHub repo for community to keep updated?

e.g. VFSForGit no longer is using the sparse-checkout or always_exclude to track files and folders (now using the ModifiedPaths). 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 49c37596-91af-710a-5465-e4211f0b2819
* Version Independent ID: 40a52f21-cdcc-615f-d9e8-58be9ef9c059
* Content: [Git Virtual File System Architecture - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/learn/git/gvfs-architecture)
* Content Source: [https://mseng.visualstudio.com/DefaultCollection/TechnicalContent/_git/devops-learn-pr?path=%2fdocs%2fgit%2fgvfs-architecture.md&version=GBlive&_a=contents](https://mseng.visualstudio.com/DefaultCollection/TechnicalContent/_git/devops-learn-pr?path=%2fdocs%2fgit%2fgvfs-architecture.md&version=GBlive&_a=contents)
* Product: **devops**
* Git Login: **samgu**
* Microsoft Alias: **sanoursa**

**Comment by steved0x** [comment]
@damoando4 I checked with the author of the topic and they agree it is due for a refresh, and that it is on their backlog, but I don't have an ETA at this time.
