### ISSUE TITLE
"Allow scripts to access the OAuth token" doesn't work with custom secret variables

### ISSUE THREAD

**Issue by beatcracker** [MicrosoftDocs/vsts-docs#2761]
I'm unable to access custom secret variables in scripts using Visual Designer. `SYSTEM_ACCESS` token is set, but custom variables are not. If this is intended, documentation should explicitly warn that only `System.AccessToken` is available when using Visual Designer.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd7e0bd3-1f7d-d7b6-cc72-5ef63c31b46a
* Version Independent ID: dae87abd-b73d-9120-bcdb-6097d4b40f2a
* Content: [Pipeline variables - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=vsts&tabs=designer%2Cbatch)
* Content Source: [docs/pipelines/process/variables.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/variables.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by beatcracker** [comment]
Related: #2303 ?

**Comment by vijayma** [comment]
You have to pass the secrets explicitly to the scripts using environment properties. You can do that by opening the "Environment variables" section of the task inputs and adding the secrets that you want to pass in. For instance Name = pswd, Value = $(myPassword), where myPassword is defined as a pipeline variable, and pswd is what your script expects. Let us know if this does not work, and we will reopen the issue. Thanks.
