### ISSUE TITLE
Clarify default condition

### ISSUE THREAD

**Issue by letmaik** [MicrosoftDocs/vsts-docs#2762]
I'm assuming the default condition of a step is "succeeded()". Is that correct? This should be added to this page as it's a good starting point when thinking about writing custom conditions. For example, what would happen if the condition is only `eq(variables['Build.SourceBranch'], 'refs/heads/master')`? Would this step run whether the preceeding tasks have failed or succeeded?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f151218-9a11-0078-e038-f96198a76143
* Version Independent ID: 09c4d032-62f3-d97c-79d7-6fbfd89910e9
* Content: [Conditional tasks - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/conditions?tabs=yaml&view=vsts)
* Content Source: [docs/pipelines/process/conditions.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/conditions.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by bricelam** [comment]
+1 Is `succeded()` the default?

**Comment by AdamYoblick** [comment]
I'd like to know this as well, it's not clear from the documentation. Can anyone on the AzDo team clarify?
