### ISSUE TITLE
Invoke Rest API completion callback

### ISSUE THREAD

**Issue by ribrdb** [MicrosoftDocs/vsts-docs#2763]
There should be documentation for how to make the callback when you set the Completion Event to Callback.
The only thing I can find is this blog post which uses the C# api: https://blogs.msdn.microsoft.com/aseemb/2017/12/18/async-http-agentless-task/
Please document how to do it using just the rest api for people not using C#.
I've spent probably an entire day trying to figure this out. 
It looks like maybe I need to post to dev.azure.com/{organization_name}/{projectid}/_apis/distributedtask/hubs/{hubName}/plans/{planId}/events
where hubName is "rm" for release management or "build" for builds.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 89bc6da4-5a1e-5989-f4f0-27465953b5fd
* Version Independent ID: fd12f976-5d3b-3b1b-3d0a-a0bf2a60c961
* Content: [Invoke HTTP REST API task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/http-rest-api?view=vsts)
* Content Source: [docs/pipelines/tasks/utility/http-rest-api.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/utility/http-rest-api.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by shashban** [comment]
Thanks for the feedback. We have added the details of the POST required to the docs.
