### ISSUE TITLE
Native wiki repos are NOT exposed via Azure DevOps Git interfaces

### ISSUE THREAD

**Issue by JamesInDenver** [MicrosoftDocs/vsts-docs#2764]
This documentation falsely describes how the default wiki repo for a project can follow the same Git workflows as any other repo.  This is not the case because the Project.wiki repo is hidden from the Repos service and from the "Repositories" settings.  This means you can't configure branch permissions or policies, you can't manage pull requests or even view files or history.  I truly wish the wiki repo was treated like any other repo but it is not.  The alternative is a Code Wiki but then you lose all of the out of the box wiki editing and management UI. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 172eecd7-1a6b-30d0-96c0-fa6ae56b521c
* Version Independent ID: adc2c741-a41f-68d9-cdaf-dac696e68b9f
* Content: [Clone and update Azure DevOps wiki content offline - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/project/wiki/wiki-update-offline?view=vsts)
* Content Source: [docs/project/wiki/wiki-update-offline.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/project/wiki/wiki-update-offline.md)
* Product: **devops**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @JamesInDenver, thank you for your feedback. I've reached out to my PMs for clarity and will update you as soon as possible. Thanks again.

**Comment by chcomley** [comment]
@JamesInDenver, I don’t believe we intend to expose the Project Wiki Repo in the list of Repos. There is a [uservoice](https://developercommunity.visualstudio.com/content/idea/365795/wiki-un-hide-git-repository-wiki.html) around that. We are updating the document to explicitly say that Git workflows will be supported only for code wiki. Meanwhile, you can use APIs to set up branch policies and fulfill your scenarios. Please let us know if you have any further questions. Thanks for contacting us.

**Comment by JamesInDenver** [comment]
Thanks for the update and for clarify the documentation.  FYI, the default Wiki repository is also not manageable via the API.  At least you cannot get the repoID (needed by all other operations) via the repo list endpoint.

**Comment by rajbos** [comment]
Update on retrieving the RepoId from the API, this can be done by using the `includeHidden` parameter on the call, as documented [here](https://docs.microsoft.com/en-us/rest/api/azure/devops/git/repositories/list?view=azure-devops-rest-5.1):

```
GET https://dev.azure.com/{organization}/{project}/_apis/git/repositories?includeLinks={includeLinks}&includeAllUrls={includeAllUrls}&includeHidden={includeHidden}&api-version=5.1
```
