### ISSUE TITLE
Migrating GitLab issues + history to Azure DevOps

### ISSUE THREAD

**Issue by cpetry** [MicrosoftDocs/vsts-docs#2766]
How can I migrate my GitLab issues + comments + attachments to Azure DevOps work items?
I got 3 ideas:
- Existing direct migration tool?!
- GitLab REST Api -&gt; JSON -&gt; Azure REST API
- GitLab REST Api -&gt; CSV/Excel -&gt; Azure DevOps

Is there a How-To for one of those?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4ca74dfe-b281-987f-ca06-0ed3e51aa8d6
* Version Independent ID: 3b36bca7-53ae-655f-f836-581b893c813b
* Content: [Edit multiple user stories, bugs, issues, tasks, & other work items - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/backlogs/bulk-modify-work-items?view=vsts)
* Content Source: [docs/boards/backlogs/bulk-modify-work-items.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/boards/backlogs/bulk-modify-work-items.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by mmitrik** [comment]
@cpetry There is a partner that offers data migration between dozens of VC and work tracking systems - www.opshub.com.  I know we have had many customers use their tools successfully, and it looks like they support GitLab.

**Comment by mmitrik** [comment]
Actually, on closer inspection, it looks like they only support GitLab commit info :(  I'll ask around to see if anyone knows of a better solution.  Otherwise, the Excel option is probably easiest for most people (even if it's lower fidelity).

**Comment by mmitrik** [comment]
@cpetry Ok, looks like our recommended partner for this is [Tasktop](https://www.tasktop.com/integrations), and according to their site, they support GitLab issues 😄

**Comment by johannesprinz** [comment]
I just did this for my Organisation, Used Powershell Core and this gits https://gist.github.com/johannesprinz/d60e764890a588c0cccdfeca61a06747 
this is just a backup and specific to my needs but should be enough to get anyone started much quicker than from scratch.
