### ISSUE TITLE
Fork configuration for PR trigger

### ISSUE THREAD

**Issue by mydiemho** [MicrosoftDocs/vsts-docs#2767]
In the UI, one can configure build to run for pull request from forks.  There's also a setting for secrets availability.  What is the equivalent in yaml?

![screen shot 2018-12-13 at 3 16 57 pm](https://user-images.githubusercontent.com/1634185/49973852-94adfc00-feeb-11e8-82a5-fbf58cc9566d.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7458d5b2-1bb7-7d87-7ce6-2b0c430b0155
* Version Independent ID: edf5bbd3-a3f0-5426-e985-31290f8afd05
* Content: [YAML schema - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=vsts&tabs=schema)
* Content Source: [docs/pipelines/yaml-schema.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/yaml-schema.md)
* Product: **devops**
* GitHub Login: @erickson-doug
* Microsoft Alias: **macoope**

**Comment by vtbassmatt** [comment]
There's no YAML equivalent. Because of the security implications, we've opted not to expose that control to all contributors to a repo. Instead, only those with access to the pipelines UI can opt in.

**Comment by mydiemho** [comment]
Thanks for the explanation @vtbassmatt, that makes sense. 

It would be great to add this to the documentation so that user are aware that they would have to configure this in the UI.
