### ISSUE TITLE
LFS support on TFS2018 on premise

### ISSUE THREAD

**Issue by ttplaya** [MicrosoftDocs/vsts-docs#2768]
I've installed git-lfs 2.6.1 locally, tracked a file as an LFS file and then pushed to my remote sitting on TFS2018. Then when I tried cloning the repo again into a new local folder, I get the following error:

Downloading documentation/&lt;masked&gt; (14 KB)
Error downloading object: documentation/&lt;masked&gt; (2a6b695): Smudge error: Error downloading documentation/&lt;masked&gt; (2a6b6951f7ddf3086a7f78c6fce146c682fe6e30527a38539282a51cb719959f): [2a6b6951f7ddf3086a7f78c6fce146c682fe6e30527a38539282a51cb719959f] LFS object not found: [404] LFS object not found

Errors logged to &lt;masked&gt;
Use `git lfs logs last` to view the log.
error: external filter 'git-lfs filter-process' failed
fatal: documentation/&lt;masked&gt;: smudge filter lfs failed
warning: Clone succeeded, but checkout failed.

How can I check whether a file is actually stored as LFS successfully on the server? And is there any extra setup I need to do on the TFS server to make LFS work?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f3d0afd1-bce9-b05e-ff1d-2914f63e2884
* Version Independent ID: 4b69aa48-977c-cf18-bd30-17185814c8e5
* Content: [Work with large files in your Git repo - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/manage-large-files?view=vsts)
* Content Source: [docs/repos/git/manage-large-files.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/repos/git/manage-large-files.md)
* Product: **devops**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
@ttplaya I'm checking on the TFS 2018 part of your question.

There are a few steps here for troubleshooting that may be of assistance:

https://github.com/git-lfs/git-lfs#need-help

**Comment by steved0x** [comment]
I just heard back, there are no special requirement to use Git LFS on TFS, it is supported as of TFS 2015 Update 1.

**Comment by ttplaya** [comment]
I found the problem -- I was using a URL set in IIS for the remote, but had forgotten to set the Public URL in the TFS admin console. After setting the Public URL, I was able to get it to work.
