### ISSUE TITLE
Error: 'libpython3.6m.so.1.0: cannot open shared object file: No such file or directory'

### ISSUE THREAD

**Issue by nbcsm** [MicrosoftDocs/vsts-docs#2770]
command to reproduce:
      pip install onnxruntime
      python -c 'import onnxruntime as rt'

Choose python3.5 is fine, while choose python3.6 will fail.
UsePythonVersion is supposed to handle this properly

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e765cfad-8ab9-443a-1171-5af81a31252f
* Version Independent ID: 8ff69d93-0128-dbeb-9d63-45266ed73020
* Content: [Use Python Version task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/use-python-version?view=vsts)
* Content Source: [docs/pipelines/tasks/tool/use-python-version.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/tool/use-python-version.md)
* Product: **devops**
* GitHub Login: @erickson-doug
* Microsoft Alias: **brcrista**

**Comment by DavidStaheli** [comment]
Internal reference: https://mseng.visualstudio.com/AzureDevOps/_workitems/edit/1418210

**Comment by davidstaheli** [comment]
This issue has been fixed.  Thanks for reporting it!
