### ISSUE TITLE
Outdated

### ISSUE THREAD

**Issue by carlkenne** [MicrosoftDocs/vsts-docs#2771]
This document doesn't appear to be correct. Many of the keys eems to be outdated? Are there a newer version somewhere?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d227a6f2-a94b-1c05-57e4-b63d42e2b9e5
* Version Independent ID: d063e189-d0fd-4ca3-c108-a0bd2ae49d22
* Content: [.NET Core CLI task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/dotnet-core-cli?view=vsts)
* Content Source: [docs/pipelines/tasks/build/dotnet-core-cli.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/build/dotnet-core-cli.md)
* Product: **devops**
* GitHub Login: @erickson-doug
* Microsoft Alias: **dastahel**

**Comment by chasewilson** [comment]
@carlkenne Thanks for the feedback, I've updated the entire documentation. I'll be closing this issue but would love your feedback if you had time to take a look and open a new issue if there's anything you see. Thanks again and have a great day!
