### ISSUE TITLE
Request: allow parameter defaults to use other parameters

### ISSUE THREAD

**Issue by OXINARF** [MicrosoftDocs/vsts-docs#2776]
I've tried to define a parameter default using another parameter but it's apparently not possible. It would be useful to have it - it could/should only expand passed parameters, that would probably make implementation easier.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6724abea-bbdc-bf66-ed5e-3214fa6c3e66
* Version Independent ID: 4f8dab21-3f0e-da32-cc0e-1d85c13c0065
* Content: [Job and step templates - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/templates?view=vsts#passing-parameters)
* Content Source: [docs/pipelines/process/templates.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/templates.md)
* Product: **devops**
* GitHub Login: @vtbassmatt
* Microsoft Alias: **alewis**

**Comment by afeblot** [comment]
I second this request.

**Comment by steved0x** [comment]
@OXINARF @afeblot Thank you for the feedback, I am assigning this to the author of the article to see if this is possible, and if so, to add the missing documentation.

If this is a feature request, please close this issue (the issues in this repo are for documentation feedback) and submit your request here:

Please report Azure DevOps or TFS software bugs, feedback, or questions in the [Azure DevOps Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html).

Thank you again for your feedback.

**Comment by OXINARF** [comment]
@steved0x Thank you for the reply. I tried and couldn't make it work, but it would be nice to get confirmation it's not supposed to work - the documentation doesn't say anything about it. In the meantime, I've created a suggestion too: https://developercommunity.visualstudio.com/idea/414463/pipelines-templates-allow-parameter-defaults-to-us.html

**Comment by vtbassmatt** [comment]
Thanks for opening the other issue. This isn't presently supported (so closing this doc bug).
