### ISSUE TITLE
wrong task name in Example > Designer tab

### ISSUE THREAD

**Issue by xbitdigital** [MicrosoftDocs/vsts-docs#2778]
https://docs.microsoft.com/en-gb/azure/devops/pipelines/languages/javascript?view=vsts&tabs=yaml

![capture](https://user-images.githubusercontent.com/45901917/50060506-e9bc6d00-018c-11e9-90c1-305c290aef51.PNG)

that should probably be "Publish Build Artifacts" instead.

**Comment by steved0x** [comment]
@xbitdigital Thank you for letting us know, I will get that fixed.
