### ISSUE TITLE
"Updating the TF Registry using Powershell" link is incorrect

### ISSUE THREAD

**Issue by nschonni** [MicrosoftDocs/vsts-docs#2779]
Currently points to the fwlink currently points to https://docs.microsoft.com/en-us/sql/analysis-services/multidimensional-models/grant-database-permissions-analysis-services?view=sql-server-2017 which isn't related

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 23c0a4db-e251-40f8-5d3c-106a43a07a8a
* Version Independent ID: af207449-abc0-7035-0c6b-e28c0b3514c4
* Content: [Change the synchronization retry or resubmit interval - TFS](https://docs.microsoft.com/en-ca/azure/devops/reference/tfs-ps-sync/change-synchronization-retry-or-resubmit-interval?view=vsts)
* Content Source: [docs/reference/tfs-ps-sync/change-synchronization-retry-or-resubmit-interval.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/reference/tfs-ps-sync/change-synchronization-retry-or-resubmit-interval.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@nschonni - Thank you for the correction. I'm updating the content today.
