### ISSUE TITLE
how to set filed value as new GUID?

### ISSUE THREAD

**Issue by ahmadyo** [MicrosoftDocs/vsts-docs#2787]
how to set filed value as new GUID?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c1d94b21-0d87-af97-bb99-40595bfb38e2
* Version Independent ID: 0c118aeb-8b37-84a7-1d5c-ac8557258146
* Content: [Define default value or copy a value - TFS](https://docs.microsoft.com/en-us/azure/devops/reference/xml/define-default-copy-value-field?view=vsts)
* Content Source: [docs/reference/xml/define-default-copy-value-field.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/reference/xml/define-default-copy-value-field.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@ahmadyo - The ability to set a field value as a new GUID is not a supported feature.
