### ISSUE TITLE
Allow access to all pipelines

### ISSUE THREAD

**Issue by ddkserv** [MicrosoftDocs/vsts-docs#2791]
When using both Agent and deployment groups you have the "Allow access to all pipelines". This is not part of the documentation for variable groups.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4827aa99-ae62-bd63-6f2f-a87a4065ed27
* Version Independent ID: c9e461ee-7f42-3503-9460-18fa3a807bbb
* Content: [Variable groups for Azure Pipelines and TFS - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/library/variable-groups?view=vsts&tabs=yaml)
* Content Source: [docs/pipelines/library/variable-groups.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/library/variable-groups.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment]
Ok, I see what you mean. Thank you for your feedback. I will update the topic to include this option.

**Comment by cnatan** [comment]
I was looking the docs for the option "Allow access to all pipelines" today and still was not able to found it.
I want to know how this option relates with the default security mechanism based in users/groups.

**Comment by alexhomer1** [comment]
"Create a variable group" Step 2 includes the text "Decide if you want the variable group to be accessible for any pipeline if you have more than one." and the image shows the option. I agree the wording is not ideal - I'll look at updating it to make it more clear. Thank you.

**Comment by gaziqbal** [comment]
Likewise. I'm not sure what this means either. What do pipelines refer to? Builds and Releases?

**Comment by nholling** [comment]
I have no idea what this option does either.  There is no in-context help bubble (i) to explain what the option does either.

**Comment by jhgoodwin** [comment]
There is a similar option for Agent Pools. It's unclear what it does, since the agent pool is already being used for pipelines. I'd love to see clear documentation of the intent of these checkboxes.

**Comment by cloudlene** [comment]
I'm creating a VG at run time using the SYSTEM_ACCESSTOKEN from a pipeline using the Azure DevOps API.  I want any other pipeline to be able to use this VG without requiring permission.  Question:  How to I set this "allow access to  all pipelines" using Azure DevOps API?
