### ISSUE TITLE
pt-br localization

### ISSUE THREAD

**Issue by tanure** [MicrosoftDocs/vsts-docs#2792]
How can I help do create docs for VSTS in Brazilian Portuguese!?

**Comment by steved0x** [comment]
@tanure You can read about our localization of content on docs.microsoft.com here:

[Announcing New International Features on docs.microsoft.com](https://docs.microsoft.com/teamblog/announcing-new-international-features)

We have a localization team that translates the docs.microsoft.com content into different languages, and if we don't have the content that you are looking for in your language, you can leave a feedback at the bottom of that [Announcing New International Features on docs.microsoft.com](https://docs.microsoft.com/teamblog/announcing-new-international-features) article which would go to that team, and you can also leave a feedback and let them know that you would like to help.

Thank you for your offer to help.

Steve
