### ISSUE TITLE
Historical Data Filters make Burnup/Burndown Charts useless

### ISSUE THREAD

**Issue by markyates90** [MicrosoftDocs/vsts-docs#2794]
Due to the way Historical Data Filters are applied, it makes it impossible to reorganize a backlog after a project has started. We are a couple of months into the project had needed to add tags or area paths to organize the backlog by sub-projects. The Burnup charts do not work because it only includes items as of the date the tag or area path was assigned. It should include all items tagged as completed items regardless of when it was tagged.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 735ade53-bdab-5f12-37b1-4ce7019b8d98
* Version Independent ID: 89fa7b00-dad1-0549-2616-5eec922fb474
* Content: [Filtering on historical data from Analytics - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/report/analytics/analytics-historical-filtering?view=vsts)
* Content Source: [docs/report/analytics/analytics-historical-filtering.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/report/analytics/analytics-historical-filtering.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by steved0x** [comment]
@markyates90 I am assigning this to the author of that article to see if we need to update our documentation to address this. I recommend that you also file this as a bug report/feature request here: 

Please report Azure DevOps or TFS software bugs, feedback, or questions in the [Azure DevOps Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html).
