### ISSUE TITLE
Policy to require source branch to be deleted when squash merging

### ISSUE THREAD

**Issue by bartsipes** [MicrosoftDocs/vsts-docs#2795]
I've seen lots of branches left over after merges are complete, including after a squash merge. It would be really nice to be able set a policy that if you squash merge a PR, then the source branch is automatically deleted.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 56dec464-f25a-5c46-52e7-2cbf17a2db1d
* Version Independent ID: bbe4d6d1-71a7-0c47-7bfb-1577760e003b
* Content: [Squash merge your pull requests - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/merging-with-squash?view=vsts)
* Content Source: [docs/repos/git/merging-with-squash.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/repos/git/merging-with-squash.md)
* Product: **devops**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
@bartsipes You can check the box to delete the source branch as part of completing the PR (when you complete your own PR on the branch you created), but if someone else completes your PR they don't have that option. Am I misunderstanding your question, it sounds like we may already have the capability to do what you are asking. Can you provide more details for your scenari?

**Comment by MisinformedDNA** [comment]
@steved0x bartsipes is not asking how he can do it, he's asking for a branch policy to ensure that it _always_ happens.

**Comment by bartsipes** [comment]
Correct, I am wanting a rule to always force branch deletion after PR completion.

**Comment by nickfoster** [comment]
And vice-versa, I'd really appreciate being able to disallow squash merges into some branches. We have dev and master branches that are long lived, and when someone squashes the merge in a PR between the branches it makes a horrible mess because they can't delete the source branch.

**Comment by Baffour** [comment]
Agreed @nickfoster just came here to work out if that was possible!

**Comment by adinunzio84** [comment]
Might be good to post a feature suggestion here:
https://developercommunity.visualstudio.com/content/idea/post.html?space=21

Found this one, but it was closed:
https://developercommunity.visualstudio.com/content/idea/365984/allow-auto-deletion-of-merged-branches-by-policy.html

Also would love to have this feature.

**Comment by mijacobs** [comment]
Thanks for the suggestion! To make sure it gets in front of the product team for triage, please [submit your idea]( https://developercommunity.visualstudio.com/content/idea/post.html?space=21) here.

**Comment by janderson-connectwise** [comment]
https://developercommunity.visualstudio.com/idea/767668/pull-request-global-policy-only-allow-squashrebase.html Created a new feature suggestion, since older ones somehow got closed as fixed.

**Comment by bartsipes** [comment]
@janderson-connectwise thank you!

**Comment by timblaktu** [comment]
I like this idea, but you'll need to take care for cases where submodules are being merged. Squash-merging AND deleting source branches is dangerous thusly: If you squash-merge the submodule, there end up 2 new commits to the target branch, the squash one and the merge one. If you also delete the source branch, you're also deleting the commits made on that branch, so unless you take care to update it, the superrepo will be pointing to a non-existing commit!
