### ISSUE TITLE
Just a checkbox of Squash is not enough

### ISSUE THREAD

**Issue by gongminmin** [MicrosoftDocs/vsts-docs#2796]
Why not mentioning the term "rebase"? Git has 3 idioms to handle pull request merge,
1. Merge, which is the same as diagram 1,
2. Squash + rebase, which is close to diagram 2,
3. Rebase, it keeps the history, but rebase to the tip.
(4. Squash + merge, rarely used)
Basically squash and rebase are orthogonal. Squash does not imply rebase, vice versa. Just provide a checkbox is very confusing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 56dec464-f25a-5c46-52e7-2cbf17a2db1d
* Version Independent ID: bbe4d6d1-71a7-0c47-7bfb-1577760e003b
* Content: [Squash merge your pull requests - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/merging-with-squash?view=vsts)
* Content Source: [docs/repos/git/merging-with-squash.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/repos/git/merging-with-squash.md)
* Product: **devops**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
I am passing this info along to the team. Thank you for your feedback.
