### ISSUE TITLE
Value cannot be null

### ISSUE THREAD

**Issue by Resultfactory** [MicrosoftDocs/vsts-docs#2797]
Our build always fails with this error 'Value cannot be null' and Parameter name: workspace. We are building an iOS Xamarin.Forms app, but we never pass this step. Is there something we miss here or is this a bug?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5891d09-bbcf-012e-483d-795eb4b469e5
* Version Independent ID: be1f16ef-ea88-ee8e-fa90-61b5228dc454
* Content: [Install Apple Provisioning Profile task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/install-apple-provisioning-profile?view=vsts)
* Content Source: [docs/pipelines/tasks/utility/install-apple-provisioning-profile.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/utility/install-apple-provisioning-profile.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by DavidStaheli** [comment]
@Resultfactory I'm sorry for the slow response.  The error sounds like an issue with Xamarin.  Can you please confirm whether you still see the problem?  Thanks.

**Comment by Resultfactory** [comment]
Hello David,
Thanks for the response, the problem does not occur anymore.
Kind regards,
Godfried

Van: David Staheli <notifications@github.com>
Verzonden: woensdag 20 maart 2019 17:26
Aan: MicrosoftDocs/vsts-docs <vsts-docs@noreply.github.com>
CC: Godfried Seegers <godfried@resultfactory.com>; Mention <mention@noreply.github.com>
Onderwerp: Re: [MicrosoftDocs/vsts-docs] Value cannot be null (#2797)


@Resultfactory<https://github.com/Resultfactory> I'm sorry for the slow response. The error sounds like an issue with Xamarin. Can you please confirm whether you still see the problem? Thanks.
