### ISSUE TITLE
Update screenshots for new navigation

### ISSUE THREAD

**Issue by MattDavisRM** [MicrosoftDocs/vsts-docs#2798]
The screenshot for finding the web hooks is using the old navigation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4806b641-fdb1-c0e9-081c-c007807c7cdb
* Version Independent ID: f59d8501-1285-be79-b084-8371ed8395bb
* Content: [WebHooks with Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/service-hooks/services/webhooks?view=vsts)
* Content Source: [docs/service-hooks/services/webhooks.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/service-hooks/services/webhooks.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by elbatk** [comment]
Ah, you're right @MattDavisRM , this documentation is getting revamped, so stay tuned for the update! I'm going to close this as we've got work in progress to address this! Thanks!
