### ISSUE TITLE
Agent Updates

### ISSUE THREAD

**Issue by MattDavisRM** [MicrosoftDocs/vsts-docs#2799]
Should this list include vstsagentpackage.azureedge.net?  See the question here:

https://stackoverflow.com/questions/53512760/azure-devops-vsts-self-hosted-agent-update-url/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e191f4bf-deef-1c48-aaa7-db424c322ae3
* Version Independent ID: 866d576f-77e4-1fc4-d4db-484628e0b518
* Content: [Troubleshoot network connections and whitelist addresses](https://docs.microsoft.com/en-us/azure/devops/organizations/security/faq-network-connections?view=vsts)
* Content Source: [docs/organizations/security/faq-network-connections.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/security/faq-network-connections.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by chcomley** [comment]
@MattDavisRM I've just pushed an update to this article, adding vstsagentpackage.azureedge.net to the list. This update should be live by sometime this afternoon. Thanks for taking the time to give us the feedback, we appreciate it!
