### ISSUE TITLE
Receiving Error When Attempting to Create a VSTS LTicket From Zendesk

### ISSUE THREAD

**Issue by scottballard** [MicrosoftDocs/vsts-docs#280]
Hello,

When trying to create a new ticket in VSTS from an existing ticket in Zendesk we are receiving the following error:

TF401320: Rule Error for field Source. Error Code: Required, HasValues, LimitedToValues, AllowsOldValue, InvalidEmpty. 

No matter what settings I change in either Zendesk or VSTS the message appears. 

Any help on what may be causing this error would be greatly appreciated. 

-Thanks, 
Scott 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c1646acb-1bd0-d506-fe70-1b749cccbbc4
* Version Independent ID: 89aa9387-8ce6-9877-8e90-5f7c655b4b77
* Content: [Zendesk with VSTS | Microsoft Docs](https://docs.microsoft.com/en-us/vsts/service-hooks/services/zendesk)
* Content Source: [docs/service-hooks/services/zendesk.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/service-hooks/services/zendesk.md)
* Service: **unspecified**
* GitHub Login: @douge
* Microsoft Alias: **elbatk**

**Comment by elbatk** [comment]
Hey @scottballard , forwarding this to the product team to hopefully get some help for you.

**Comment by scottballard** [comment]
Hello, Is there an update on this?

**Comment by Steve-A-Greenwood** [comment]
Hi, My team and I are also having this problem.  We can link to existing WITs but cannot create new ones from Zendesk

**Comment by elbatk** [comment]
Adding @willsmythe to take a look at this one for ya

**Comment by willsmythe** [comment]
What type of work item are you trying to create in VSTS? Have you customized this work item type in anyway? Also, does the Zendesk ticket have any attachments?

**Comment by elbatk** [comment]
Closing this for cleanup :)
