### ISSUE TITLE
None of the fwlink are pointing at the correct content

### ISSUE THREAD

**Issue by nschonni** [MicrosoftDocs/vsts-docs#2800]
All the links under "To learn more, see one of the following topics:" are pointing pages unrelated to the topics in the text of the links

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc5e7bed-20b2-b95b-ebb1-27ef37244586
* Version Independent ID: 1c0afce3-80e6-faa3-6dae-942261d85bd0
* Content: [SQL Server Collation Requirements for Team Foundation Server - Azure DevOps Server & Team Foundation Server](https://docs.microsoft.com/en-ca/tfs/server/install/sql-server/collation-requirements?view=vsts)
* Content Source: [https://mseng.visualstudio.com/DefaultCollection/TechnicalContent/_git/tfs-docs-pr?path=%2fdocs%2fserver%2finstall%2fsql-server%2fcollation-requirements.md&version=GBlive&_a=contents](https://mseng.visualstudio.com/DefaultCollection/TechnicalContent/_git/tfs-docs-pr?path=%2fdocs%2fserver%2finstall%2fsql-server%2fcollation-requirements.md&version=GBlive&_a=contents)
* Product: **devops-server**
* Git Login: **elbatk**
* Microsoft Alias: **elbatk**

**Comment by elbatk** [comment]
Thanks Nick :) Updating those links now!
