### ISSUE TITLE
Project Page URL - incorrect formatting

### ISSUE THREAD

**Issue by gdprtcl** [MicrosoftDocs/vsts-docs#2809]
[In "Open your project in Visual Studio", Step 2, the Project Page URL is not formatted correctly. Kindly Check. PFA the screensht for the same.]

![vs-tfvc](https://user-images.githubusercontent.com/19777169/50143029-8425c900-02d1-11e9-9bad-3ed59db62a98.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7cdfa4b3-b755-4454-26c2-4a960d9c142f
* Version Independent ID: d534865f-db3d-1cc0-5eec-71dc5b89b822
* Content: [Develop and share your code in TFVC using Visual Studio - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/tfvc/share-your-code-in-tfvc-vs?view=vsts)
* Content Source: [docs/repos/tfvc/share-your-code-in-tfvc-vs.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/repos/tfvc/share-your-code-in-tfvc-vs.md)
* Product: **devops**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by nschonni** [comment]
#2784 fixes this

**Comment by steved0x** [comment]
@gdprtcl Thanks for letting us know, @nschonni thanks for fixing it. That PR is merged and should be live shortly, with a possible delay due to the holidays.
