### ISSUE TITLE
"which used used to identify"

### ISSUE THREAD

**Issue by archi-tekt** [MicrosoftDocs/vsts-docs#281]
It should be "which is used to identify"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7cd986e0-608c-1d8c-6faf-ecdb12e10bc6
* Version Independent ID: d60c996e-187e-dd6b-7f3a-dd056a1603f4
* Content: [Protect your Git branches with policies | Microsoft Docs](https://docs.microsoft.com/en-us/vsts/git/branch-policies#feedback)
* Content Source: [docs/git/branch-policies.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/git/branch-policies.md)
* Service: **unspecified**
* GitHub Login: @douge
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
@archi-tekt Thanks for letting us know, I am fixing this and it should be live later today. Thank you!
