### ISSUE TITLE
Nginx is spelled incorrecly

### ISSUE THREAD

**Issue by jorisvergeer** [MicrosoftDocs/vsts-docs#2810]
In the screenshot of step 7 there is a machine named "myNgenix" where is hould be "myNginx"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: abf8bb33-e4cf-3dc5-5510-1111b8f1bdbf
* Version Independent ID: 3148d97d-2ff1-30f5-0487-dbfe93888a3f
* Content: [Deploy nginx to a Linux VM - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/apps/cd/deploy-linuxvm-deploygroups?view=vsts)
* Content Source: [docs/pipelines/apps/cd/deploy-linuxvm-deploygroups.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/apps/cd/deploy-linuxvm-deploygroups.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment]
Thank you for your feedback. I will update the topic to include your recommendations.
