### ISSUE TITLE
Merge marker in Doc

### ISSUE THREAD

**Issue by StiviiK** [MicrosoftDocs/vsts-docs#2811]
There are merge "marker"
e.g.
![image](https://user-images.githubusercontent.com/8115642/50152098-fcd15900-02c2-11e9-8b37-6d7575855fab.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7cafb5cd-55e7-2600-ffa2-e3c9e40c73f7
* Version Independent ID: ed4a9ee5-1df4-fa2b-30b4-65fc1b3051a7
* Content: [Add, run, update inline tests - Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/user-guide/add-run-manual-tests?view=vsts&tabs=new-nav)
* Content Source: [docs/user-guide/add-run-manual-tests.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/user-guide/add-run-manual-tests.md)
* Product: **devops**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by nschonni** [comment]
#2790 should resolve this
