### ISSUE TITLE
Don't use arrow function in Mocha description

### ISSUE THREAD

**Issue by karelkral** [MicrosoftDocs/vsts-docs#2812]
Because it causes every test to fail: https://stackoverflow.com/a/46392720/245460

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 44581f4a-93df-7507-3844-eadedf9a6cc4
* Version Independent ID: 33c7bcf0-1512-975f-5ef8-9f2a192a84ad
* Content: [Add a Build or Release Task](https://docs.microsoft.com/en-us/azure/devops/extend/develop/add-build-task?view=vsts)
* Content Source: [docs/extend/develop/add-build-task.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/extend/develop/add-build-task.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by damccorm** [comment]
Hm, didn't realize this, definitely seems like you're right that we should avoid this though ([Mocha docs agree](https://mochajs.org/#arrow-functions)). I'll go ahead and fix this in the docs.

**Comment by elbatk** [comment]
We've got a PR going for this, thanks everyone :)
