### ISSUE TITLE
Before 2017.3 no NuGet option

### ISSUE THREAD

**Issue by csutorasr** [MicrosoftDocs/vsts-docs#2813]
If you have 2017.2 or older versions you have no NuGet Service option. You have to use Generic Connection. Please update the docs according to this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 11ed58a1-5819-f3a4-c674-dafcdbd56fbc
* Version Independent ID: d68aca4d-3fd3-1864-09f5-6060295e0399
* Content: [Publishing to NuGet feeds - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/nuget?view=tfs-2018&tabs=designer)
* Content Source: [docs/pipelines/artifacts/nuget.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/artifacts/nuget.md)
* Product: **devops**
* GitHub Login: @erickson-doug
* Microsoft Alias: **amullans**

**Comment by alexmullans** [comment]
@elbatk can you add a moniker section for < TFS 2017.3 that covers using the Generic service connection instead of the NuGet one?

**Comment by elbatk** [comment]
@alexmullans we can't do subversions through monikers, but I can a note for just TFS 2017 that states the guidance for either 2017.2 or older and then 2017.3

**Comment by elbatk** [comment]
I'm adding a note that mentions this in the TFS 2017 docs: 

"To publish to an external NuGet feed, you must first create a service connection to point to that feed. You can do this by going to **Project settings**, selecting **Services**, and then creating a **New service Endpoint**. Select the **NuGet** option for the service connection. To connect to the feed, fill in the feed URL and the API key or token.

> If you are running TFS Update 2 or older, **Nuget** is not a service endpoint option, you must use the **Generic** connection."

Closing this, thanks for the heads up @csutorasr !
