### ISSUE TITLE
Mac OS build agent Xcode and SDK versions

### ISSUE THREAD

**Issue by jzeferino** [MicrosoftDocs/vsts-docs#2815]
Azure devops mac os build host is running on Xcode 9.4 and SDK version 11.4.

And Apple says:

> WARNING ITMS-90725: "SDK Version Issue. This app was built with the iOS 11.4 SDK. Starting March 2019, all iOS apps submitted to the App Store must be built with the iOS 12.1 SDK or later, included in Xcode 10.1 or later."

So, the build agent must be updated.

**Comment by steved0x** [comment]
@jzeferino I'll pass this along, and moving forward, the best place to file issues with the product is here: 

Please report Azure DevOps or TFS software bugs, feedback, or questions in the [Azure DevOps Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html).

**Comment by wis-jellis** [comment]
Hi @steved0x, we are running into this same issue with our Xamarin.iOS app.  It appears that locally I am using Mono 5.16, but the build machine is using 5.12.  Perhaps this is leading to incorrect Xamarin.iOS version selection? Could you please point me to the appropriate place to track/discuss this topic? I tried searching the devops community link posted, but have not found much.  Thanks!

**Comment by wis-jellis** [comment]
for reference, we are using the Hosted macOS image documented here https://github.com/Microsoft/azure-pipelines-image-generation/blob/master/images/macos/macos-Readme.md and building a Xamarin.iOS app that attempts to target the latest iOS SDK

**Comment by wis-jellis** [comment]
OK, have posted here https://developercommunity.visualstudio.com/content/problem/416822/azure-devops-hosted-macos-xamarinios-build-sdk-ver.html

also included in link above - a promising looking workaround for a script build task that allows you to select desired versions of Xcode, Mono, Xamarin.iOS, if anyone else is hitting the same issue.
