### ISSUE TITLE
add to this documentation: when an owner is removed he/she is removed from the PCA group

### ISSUE THREAD

**Issue by pathakneeti** [MicrosoftDocs/vsts-docs#2817]
add to this documentation: when an owner is removed he/she is removed from the PCA group

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: df27392f-aec0-41d9-726c-88abc12468e0
* Version Independent ID: f21e6a50-99f5-819b-4e09-99a84253bf9d
* Content: [Change the owner of an organization - Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/change-organization-ownership?view=vsts&tabs=new-nav)
* Content Source: [docs/organizations/accounts/change-organization-ownership.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/accounts/change-organization-ownership.md)
* Product: **devops**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Thanks @pathakneeti, I've updated the article. This should be live by sometime this afternoon. Thanks again!
