### ISSUE TITLE
Explain that the environment variable contains only the path to the folder

### ISSUE THREAD

**Issue by StefanSchoof** [MicrosoftDocs/vsts-docs#2822]
I set up a Selenium Test in node. The node Selenium api require the full path to the driver (include the exe part). The documentation should mention that the environment var does only contain the path.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 09e51d18-72ec-1ad4-9ae7-8185c8e1dcd6
* Version Independent ID: 9f2f0471-d123-8e95-1606-cd811d1ece9a
* Content: [Perform UI tests with Selenium - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/test/continuous-test-selenium?view=vsts)
* Content Source: [docs/pipelines/test/continuous-test-selenium.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/test/continuous-test-selenium.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment]
Thank you for your feedback. I have passed this on to the product team for advice and I will update the topic to include their recommendation.

**Comment by StefanSchoof** [comment]
Thanks. Reading this again I see the last sentence is missing a important pice:
> The documentation should mention that the environment var does only contain the path **to the folder**.

**Comment by alexhomer1** [comment]
I'm updating the topic to reflect this.
