### ISSUE TITLE
Download does not work

### ISSUE THREAD

**Issue by geedsen** [MicrosoftDocs/vsts-docs#2823]
https://pkgs.dev.azure.com/{organizationName}/_apis/public/nuget/client/CredentialProviderBundle.zip  download results in a "The resource cannot be found." Might be good to mention that the {organizationName} needs to be replaced by your own organization name.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab0a3735-a9b0-2ed7-f08f-5321f55f8c90
* Version Independent ID: 2153f6c0-def7-eed1-286d-5e61c9fcbec4
* Content: [Use NuGet with Azure DevOps Services feeds](https://docs.microsoft.com/en-us/azure/devops/artifacts/nuget/nuget-exe?view=vsts&tabs=new-nav#download-the-credential-provider-directly)
* Content Source: [docs/artifacts/nuget/nuget-exe.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/artifacts/nuget/nuget-exe.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by elbatk** [comment]
Hi @geedsen , it's our standard to write variables/pieces that need to be updated in brackets, but I'll add another note just to make sure we avoid all confusion!
