### ISSUE TITLE
Can't disconnect Azure DevOps organization from AD

### ISSUE THREAD

**Issue by bogdanbanciu** [MicrosoftDocs/vsts-docs#2824]
I am getting the following error when I try to disconnect the AD: "AAD Tenant disconnection failed due to the error : Account entitlement not found in the dictionary for source identity '**************************'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7244b36c-6f57-1673-7ce4-27006923fec8
* Version Independent ID: c8a5b13d-b62e-8f20-f8bd-9e41946f71b4
* Content: [Disconnect organization from Azure Active Directory - Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/disconnect-organization-from-azure-ad?view=vsts)
* Content Source: [docs/organizations/accounts/disconnect-organization-from-azure-ad.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/accounts/disconnect-organization-from-azure-ad.md)
* Product: **devops**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @bogdanbanciu, I'm sorry you're experiencing issues. I've followed up with my PM and will get back to you shortly.

**Comment by andresgallo36** [comment]
@bogdanbanciu - Please create a ticket with our support team at https://azure.microsoft.com/en-us/support/create-ticket/ (choosing Basic or Premium depends on whether your organization has a Premier contract with Microsoft), and we will be able to unblock you from there.
