### ISSUE TITLE
Display Graphs in iFrame

### ISSUE THREAD

**Issue by ebrucucen** [MicrosoftDocs/vsts-docs#2825]
Is there any way to display iframes as graph? It would be helpful to display thirdparty graphs to be linked.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fa622358-f5bb-1f5c-177a-081a37b6acef
* Version Independent ID: 72f7fd16-a822-66c8-3a34-8905645ce5f2
* Content: [Markdown syntax for files, widgets, and wikis in Azure DevOps - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/project/wiki/markdown-guidance?view=vsts)
* Content Source: [docs/project/wiki/markdown-guidance.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/project/wiki/markdown-guidance.md)
* Product: **devops**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @ebrucucen, I've followed up with my PM and will get back to you shortly. Thanks for your question.

**Comment by chcomley** [comment]
@ebrucucen, Currently, there is no way to display iframes as graphs, the only way we support iframes is with embeded videos. We do, however, recommend making a [feature suggestion](https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdevelopercommunity.visualstudio.com%2Fcontent%2Fidea%2Fpost.html%3Fspace%3D21&data=02%7C01%7C%7C3d5a3783f016463d520608d6663647b6%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636808780645354497&sdata=C0Jssks2u%2FY9%2BewYrhl55KrI2IACPKlSD67gzQGsWUY%3D&reserved=0), including more details on the scenario and your exact expectation. Thank you!
