### ISSUE TITLE
Support says only individual emails accepted not groups

### ISSUE THREAD

**Issue by BrickOven** [MicrosoftDocs/vsts-docs#2826]
HI - Please make the list of valid selections for email more clear and tell people you can only select individual email addresses even though the dialog box even says search users and groups.  

From this {issue)[https://developercommunity.visualstudio.com/content/problem/386392/email-work-item-feature-fails-for-dls-with-an-apos.html] The support site says groups are not supported.. only individuals

and 

If you select an email distribution list the product throws an ugly TF400898: An Internal Error Occurred.  [which based on this issue is apparently by design.](https://developercommunity.visualstudio.com/content/problem/411521/email-from-backlog-to-distribution-list-results-in.html)

The current text below sounds reasonable but doesn't actually match the behavior of the system if a DL is a valid email recognized by the system.

You can only send the email to addresses that are recognized by the system, that is project members. If you add an email account that the system doesn't recognize, you receive a message that one or more recipients of your email don't have permissions to read the mailed work items.

I've submitted an [issue ](https://developercommunity.visualstudio.com/content/problem/412300/email-work-item-allows-users-to-select-distributio.html)saying the Send Work Items in email screen To field says search users and groups too. 

Thanks,
-Brian
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4b4a9a4d-3517-28c2-d8b9-7b1d025b17af
* Version Independent ID: 1b55ace1-77fd-7980-b2bf-ac97c03a112a
* Content: [Email or print user stories, issues, bugs, or other work items - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/work-items/email-work-items?view=vsts&tabs=browser)
* Content Source: [docs/boards/work-items/email-work-items.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/boards/work-items/email-work-items.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@BrickOven - Thanks Brian for the feedback. I'm updating the article to better reflect the restricitons.
