### ISSUE TITLE
Edit / Overview templates

### ISSUE THREAD

**Issue by guytenaerefe** [MicrosoftDocs/vsts-docs#2827]
Managing templates for releases this way is not really efficient. Are there any plans to make these templates editable from an overview page?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce3b1a51-8a5d-1aad-470c-a1e9ed1a3bf7
* Version Independent ID: 857c4c85-1915-8ec2-4586-a758eb423514
* Content: [Use stage templates in deployments - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/env-templates?view=vsts)
* Content Source: [docs/pipelines/release/env-templates.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/release/env-templates.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment]
Thank you for your feedback. Product bugs, issues, suggestions, and feature requests are best posted on the Developer Community website at https://developercommunity.visualstudio.com/spaces/21/index.html, where they are tracked by the product teams and are updated with their responses. Please post your feedback there. Thank you.
