### ISSUE TITLE
Configuring build agent account

### ISSUE THREAD

**Issue by daniel-dorroh** [MicrosoftDocs/vsts-docs#2828]
The doc says
> Whether you run an agent as a service or interactively, you can choose which account you use to run the agent

but doesn't explain how the choice of user account is done when running the agent as a service.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 47625b86-abd5-ee15-6d61-8bcf81861b96
* Version Independent ID: be9a6174-a69b-7aed-d584-5f602fcc5eb4
* Content: [Build and Release Agents - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/agents?view=vsts)
* Content Source: [docs/pipelines/agents/agents.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/agents/agents.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by Materia-xx** [comment]
When you initially register the agent to run as a service you provide the user/pass and it creates a windows service. You can see this in services.msc. The credentials that the service is running as are the credentials (the user account) that are used. If your password rolls or credentials change, you can update it directly in the windows service as well.

**Comment by awentzel** [comment]
What is the recommended method to run as a service? Running as a user/pass could break the builds when password expires. What about Network Service / Local Service etc?

**Comment by sunandita16** [comment]
I have configured the agent to run as a service with a particular username, which has access to a shared drive. I am running a powershell script for build but it fails to access the shared drive. I used UNC in my script for accessing the shared drive

**Comment by vtbassmatt** [comment]
Adding a note about this.
