### ISSUE TITLE
URL for TFS2018 is differnent

### ISSUE THREAD

**Issue by HaraldSchmitt** [MicrosoftDocs/vsts-docs#283]
The URL to download a Build Agent for TFS2018 is different to the one of TFS2017, which was provided. You do not have a /tfs/ in the path. The correct Url is:
https://{your_server}/DefaultCollection/_admin/_AgentPool

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 47625b86-abd5-ee15-6d61-8bcf81861b96
* Version Independent ID: be9a6174-a69b-7aed-d584-5f602fcc5eb4
* Content: [Build and Release Agents | Microsoft Docs](https://docs.microsoft.com/en-us/vsts/build-release/concepts/agents/agents)
* Content Source: [docs/build-release/concepts/agents/agents.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/build-release/concepts/agents/agents.md)
* Service: **unspecified**
* GitHub Login: @douge
* Microsoft Alias: **alewis**

**Comment by alexhomer1** [comment]
Thank you for your feedback. We will add this to the topic.

**Comment by andyjlewis** [comment]
re-opening until this fix is made

**Comment by TASlavens** [comment]
What the OP states may be true when TFS 2018 is freshly installed, but my TFS 2018u2 upgrade from TFS 2017u3.1 still retains the "/tfs" portion of the URL.

**Comment by vtbassmatt** [comment]
Addressed with a pending doc change.
