### ISSUE TITLE
How to install packages on Azure DevOps bash plugin?

### ISSUE THREAD

**Issue by anshuman-goel** [MicrosoftDocs/vsts-docs#2831]
I want to install packages like I use to do on Linux. "apt-get -y install jq"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 36fff5ec-d766-b589-39ff-9c69ab26dd5b
* Version Independent ID: 12deb045-2511-b5bf-9e41-0d223bef516b
* Content: [Shell Script task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/shell-script?view=vsts)
* Content Source: [docs/pipelines/tasks/utility/shell-script.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/utility/shell-script.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by vtbassmatt** [comment]
On hosted, `sudo apt-get -y install jq`. (Though `jq` is already installed - assuming this was an example only.) Password-less sudo is [documented](https://docs.microsoft.com/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml#capabilities-and-limitations).
