### ISSUE TITLE
Server Endpoint

### ISSUE THREAD

**Issue by seansparkman** [MicrosoftDocs/vsts-docs#2832]
You need to explain what Server Endpoint is in your documentation.  It is in the example.  You should also have documentation to explain how to set up an App Link to Visual Studio App Center.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: da6643ac-ea32-1761-a7e9-0f17a3c0b8ee
* Version Independent ID: 2442af0f-3f01-a91c-a98a-29c2f32d35b9
* Content: [App Center Distribute task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/app-center-distribute?view=vsts)
* Content Source: [docs/pipelines/tasks/deploy/app-center-distribute.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/deploy/app-center-distribute.md)
* Product: **devops**
* GitHub Login: @erickson-doug
* Microsoft Alias: **dastahel**

**Comment by courfeyrak** [comment]
I agree the documentation is very poor, you should explain better where to get the parameters.

**Comment by seansparkman** [comment]
This is still an issue and hasn't been fixed.

**Comment by WilliamAntonRohm** [comment]
Thanks for the suggestion! The product teams aren’t always watching this repository, so to make sure it gets in front of them for triage, please [submit your idea]( https://developercommunity.visualstudio.com/content/idea/post.html?space=21) here.
