### ISSUE TITLE
The category 'Azure Pipelines' is not available in language 'en-us'.

### ISSUE THREAD

**Issue by woonyin2014** [MicrosoftDocs/vsts-docs#2835]
I have issue when upload new item (.vsix) file to TFS2017 update 1 on premise. 
this is the error "The category 'Azure Pipelines' is not available in language 'en-us'." 

Who can help me on this?

**Comment by kev160967** [comment]
How did you resolve this?

**Comment by axmrnv** [comment]
TFS2017 support neither `Pipelines` nor `Azure Pipelines` categories. For extensions aimed at TFS2017, specify category value as "Build and release".
