### ISSUE TITLE
Download pipeline artifact into release pipeline

### ISSUE THREAD

**Issue by andreymir** [MicrosoftDocs/vsts-docs#2837]
&gt; If you're using pipeline artifacts to deliver artifacts into a release pipeline, you don’t need to add the task. Release pipelines will automatically inject the task into your stages.

This documentation is wrong. I am trying to use pipeline artifact from a release pipeline. The release pipeline does not automatically fetch the artifact. I have to add a task to download the artifact.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 861ce7a5-4fa4-55f1-2c97-46a9cc6a2f66
* Version Independent ID: bdf954b9-9bbe-8b34-b674-71ad8153519d
* Content: [Publish and consume Pipeline artifacts in builds - Azure Pipelines and TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/pipeline-artifacts?view=vsts&tabs=yaml)
* Content Source: [docs/pipelines/artifacts/pipeline-artifacts.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/artifacts/pipeline-artifacts.md)
* Product: **devops**
* GitHub Login: @alexmullans
* Microsoft Alias: **amullans**

**Comment by alexmullans** [comment]
Sorry about that - the docs got ahead of the deployment. Per https://github.com/Microsoft/azure-pipelines-tasks/issues/8119#issuecomment-448909063, the next deployment (first few weeks of 2019, after the holiday deployment freeze ends) will fix some issues with the download task being injected automatically.

**Comment by trhumphries** [comment]
Looks like this hasn't been fixed yet. Anytime frame for the fix?

**Comment by exbarboss** [comment]
Still the issue.

Googling leads to solution to use: 

> - task: PublishBuildArtifacts@1

After that, creating release pipeline works as expected.

Using pipeline artifacts still not injecting the task into release pipeline:
`- task: PublishPipelineArtifact@0
  inputs:
    #artifactName: 'drop' 
    targetPath: '$(Build.ArtifactStagingDirectory)'`
![image](https://user-images.githubusercontent.com/883804/54785221-ea78fb00-4be2-11e9-8db1-6e63331afd03.png)

Using Publish Build Artifacts though do the job:

> - task: PublishBuildArtifacts@1

![image](https://user-images.githubusercontent.com/883804/54785340-3c218580-4be3-11e9-9c13-6e076dce1f5a.png)
