### ISSUE TITLE
Encoding issues in VSTS documentation

### ISSUE THREAD

**Issue by jawn** [MicrosoftDocs/vsts-docs#284]
Question marks are displayed in code, probably encoding related.

Page: https://docs.microsoft.com/en-gb/vsts/work/customize/reference/process-configuration-xml-element

What you see in Chrome:
![image](https://user-images.githubusercontent.com/1705112/37144094-535d75ec-22bd-11e8-9d03-0d257b9ae1f4.png)

View raw source shows same issue:
https://raw.githubusercontent.com/MicrosoftDocs/vsts-docs/live/docs/work/customize/reference/process-configuration-xml-element.md

![image](https://user-images.githubusercontent.com/1705112/37144157-7f1023e2-22bd-11e8-8107-a22726eeddd5.png)

Editing the md file
https://github.com/MicrosoftDocs/vsts-docs/edit/live/docs/work/customize/reference/process-configuration-xml-element.md

Shows the github warning: 
![image](https://user-images.githubusercontent.com/1705112/37144204-9c4f1f62-22bd-11e8-87dd-e2128d477e2b.png)

**Comment by KathrynEE** [comment]
Thank you for reporting this issue. I'll update this topic later today.
