### ISSUE TITLE
Screenshots misleading?

### ISSUE THREAD

**Issue by dvdgutzmann** [MicrosoftDocs/vsts-docs#2840]
In the example there are *_img* and *_shared* folders. However, they are not shown in the screenshots of the wiki. Are they somehow hidden? Or just not visible on the screenshot? 

We would love the ability to hide certain folders!

Also are the icons in the wiki screenshots up to date?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 172eecd7-1a6b-30d0-96c0-fa6ae56b521c
* Version Independent ID: adc2c741-a41f-68d9-cdaf-dac696e68b9f
* Content: [Clone and update wiki content offline - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/project/wiki/wiki-update-offline?view=vsts)
* Content Source: [docs/project/wiki/wiki-update-offline.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/project/wiki/wiki-update-offline.md)
* Product: **devops**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @dvdgutzmann, The _img and _shared folders just weren't visible in the screenshot, however I've just pushed a new replacement shot, which includes those folders. Thanks for the heads up on that, as well as the icons, as those screenshots have been replaced also. The updates should be live by sometime this afternoon or early morning tomorrow. 
If you want to suggest a feature, please do so! Go here: https://developercommunity.visualstudio.com/spaces/8/index.html 
Thanks again!
