### ISSUE TITLE
Release Notes for new Features

### ISSUE THREAD

**Issue by wsmckenz** [MicrosoftDocs/vsts-docs#2842]
ADO is changing very quickly, usually for the better :-) But these changes often break our pipelines in unexpected ways. It would be good to have release notes as new things are rolled out, particularly for API and Yaml builds.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6037c0a7-9595-eff1-3f5c-2607baa73c4d
* Version Independent ID: 7b8cf300-4d91-ac77-3ffd-ef1a83c79af7
* Content: [Deploy to IIS using WinRM - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/apps/cd/deploy-webdeploy-iis-winrm?view=vsts#feedback)
* Content Source: [docs/pipelines/apps/cd/deploy-webdeploy-iis-winrm.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/apps/cd/deploy-webdeploy-iis-winrm.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by MattDavisRM** [comment]
Have you seen [this ](https://docs.microsoft.com/en-us/azure/devops/release-notes/)already?

**Comment by alexhomer1** [comment]
The section of our documentation at https://docs.microsoft.com/en-us/azure/devops/release-notes/ contains release notes and details of changes for each update to the product, even though the title of the page is actually "Features Timeline". If you encounter a specific issue related to product updates, it is helpful to post details on the Developer Community website at https://developercommunity.visualstudio.com/spaces/21/index.html, where they are tracked by the product teams and they may be able to offer assistance. Thank you.
