### ISSUE TITLE
Can't reference multiple variable groups from YAML

### ISSUE THREAD

**Issue by alicejgibbons** [MicrosoftDocs/vsts-docs#2844]
I can't reference multiple variable groups from within the yaml pipeline editor. It seems like only the first variable group is picked up unless I manually link the second group through the visual editor.

variables:
- group: my-variable-group1
- group: my-variable-group2

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4827aa99-ae62-bd63-6f2f-a87a4065ed27
* Version Independent ID: c9e461ee-7f42-3503-9460-18fa3a807bbb
* Content: [Variable groups for Azure Pipelines and TFS - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/library/variable-groups?view=vsts&tabs=yaml#use-a-variable-group)
* Content Source: [docs/pipelines/library/variable-groups.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/library/variable-groups.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment]
Thank you for your feedback. I have passed this on to the product team for advice.

**Comment by shashban** [comment]
@alicejgibbons I am sorry. We are not able to repro the issue.
The azure-pipelines.yaml I used is at https://github.com/shashban/extensions/blob/master/azure-pipelines.yml and was able to print variable values from two separate variable groups linked in the yml file.
Can you please point us to the pipeline definition where this didn't work?

**Comment by Obsidian01** [comment]
Looking at the example, I only see one group being used 
- group: test

how does this show the use of multiple, separate variable groups?

**Comment by telekosmos** [comment]
I guess @shashban rushed too much to close the issue. I agree @AnticliMaxtic and still wondering whether or not is possible to use multiple groups in the YAML file. 

Please, clarify.

**Comment by kenkuo** [comment]
@shashban please re-open this issue, I need to access multiple variable groups in my build

**Comment by shanoor** [comment]
Not even one variable group works for me. If I add the groups through the visual editor, the second group overwrites the first one but it works (so it's not an authorization issue nor a group/vault issue).

I tried a very simple pipeline:

```yaml
trigger:
- master

pool:
  vmImage: 'ubuntu-latest'
variables:
  group: vault1
steps:
  - checkout: none
  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: 'echo $mysecret | base64'
    env:
      mysecret: $(mysecret)
```
It echoes `JChteXNlY3JldCkK` (`$(mysecret)` in base64).

**Comment by NickSpag** [comment]
@shanoor you're missing a hyphen. Should be:

```
variables:
- group: name
```

**Comment by paulsancer** [comment]
> @shashban please re-open this issue, I need to access multiple variable groups in my build

@kenkuo Did you manage to use multiple variable groups in your build?

**Comment by pierowman** [comment]
Fyi for all that read this
trigger:
- master

pool:
  vmImage: 'ubuntu-latest'
variables:
  - group: vault1
  - group: vault2

This allows multiple variable groups
