### ISSUE TITLE
Yaml Schema Incorrect

### ISSUE THREAD

**Issue by Silvenga** [MicrosoftDocs/vsts-docs#2846]
Looks like `restoreSolution` should actually be `solution`. At least, this is what the AzureDevOps pipeline VSCode extension says.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0fa37a3f-6551-16ad-e164-a4ac522cdaab
* Version Independent ID: a3fd6935-2b99-92ef-4eb3-3249fca01f8a
* Content: [NuGet restore, pack, and publish task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/package/nuget?view=vsts)
* Content Source: [docs/pipelines/tasks/package/nuget.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/package/nuget.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by elbatk** [comment]
Hi @Silvenga , I'm showing that restoreSolution should still be right. @vijayma / @mitchdenny  do either of you know who owns the Azure DevOps Pipelines VSCode extension? Or if this would be different for that?

**Comment by mitchdenny** [comment]
Adding @vijayma

**Comment by Silvenga** [comment]
@elbatk if I'm reading the code correctly, I think it uses `solution` as the key.

https://github.com/Microsoft/azure-pipelines-tasks/blob/1d75fa8f66aa1cf7a9cb62946939f30f087b2969/Tasks/NuGetCommandV2/nugetrestore.ts#L41-L45

**Comment by Silvenga** [comment]
Looks like everything works now, not sure what happened. Both values work.

**Comment by riverar** [comment]
restoreSolution still seems invalid as of today.

**Comment by thomps23** [comment]
@vijayma Could confirm as to whether or not restoreSolution is correct.

**Comment by bender2k14** [comment]
I just created a .Net Core `restore` task with these values...

![Screenshot 2019-05-31 13 12 38](https://user-images.githubusercontent.com/34664007/58725887-e10bcc00-83a5-11e9-8436-78ca491382c2.png)

...and this is the text that it adds to yml file.

```
- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: 'path_to_project(s)'
    feedsToUse: 'config'
    nugetConfigPath: 'path_to_NuGet.config'
```

The key in question is `solutions`, which is neither `solution` nor `restoreSolution`.

**Comment by bender2k14** [comment]
Furthermore, the Azure DevOps UI says that `solution` and `restoreSolution` are unexpected "properties:

![Screenshot 2019-05-31 13 46 06](https://user-images.githubusercontent.com/34664007/58727696-a0fb1800-83aa-11e9-9c7a-05877fb1ce08.png)

![Screenshot 2019-05-31 13 45 20](https://user-images.githubusercontent.com/34664007/58727699-a3f60880-83aa-11e9-8b7a-bb8908140d53.png)

**Comment by bender2k14** [comment]
Oh, I my comments are about the Azure DevOps Pipeline build task called [.NET Core](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/dotnet-core?view=azure-devops).  As linked in the OP, this issue is about the task called [NuGet](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/dotnet-core-cli?view=azure-devops).

For what it's worth, the relevant property created by the Azure DevOps UI for this task is `restoreSolution`.

**Comment by chasewilson** [comment]
Hi all! Thank you for all of the feedback. That task input is "restore" and it's alias is "restoresolution". Either will work, however, it's suggested to use the alias as a best practice. I will be closing this issue if there are no further comments @elbatk If there is anything I'm missing, feel free to throw it out here :)
