### ISSUE TITLE
I want to contribute to provide the Azure DevOps pt-bt location docs

### ISSUE THREAD

**Issue by Powerhelmsman** [MicrosoftDocs/vsts-docs#2848]
This feedback is from @tanure from https://github.com/MicrosoftDocs/feedback/issues/983

I would like to contribute to AzureDevOps docs for the pt-BR location: https://docs.microsoft.com/en-us/azure/devops/user-guide/index?view=vsts
How I can proceed?
Thanks

**Comment by steved0x** [comment]
@Powerhelmsman I am looking into how to do this and will reply back when I ave more information.

**Comment by tanure** [comment]
I would still like to understand how I can contribute;

**Comment by thomps23** [comment]
@tanure the Azure DevOps content is currently not localized for that locale. (ex. https://docs.microsoft.com/pt-br/azure/devops/user-guide/index?view=azure-devops&viewFallbackFrom=vsts) - notice that only the top navigation is localized, everything else is in english.

However, if the content **_were_** localized you would contribute english content to this repo, and our localization services would complete localization within the month. Unfortunately I don't have an ETA or plan of record in regards to the localization of this content set.
