### ISSUE TITLE
VSTS REST API: add documentation to get list of agents

### ISSUE THREAD

**Issue by jawn** [MicrosoftDocs/vsts-docs#285]
The VSTS REST API lets you list builds and agent queues.
This is documented at https://www.visualstudio.com/en-us/docs/integrate/api/overview

What I did not find documented is how to get the list of agents.

Based on request logging, it seems this is used:
`https://<name>.visualstudio.com/_apis/distributedtask/pools/<id>/agents?includeCapabilities=false&includeAssignedRequest=true`

Please add to the docs if this is supported.

**Comment by elbatk** [comment]
hi @jawn , this information can be found here, I believe:
https://docs.microsoft.com/en-us/rest/api/vsts/clt/agents

Let me know if that's not quite what you're looking for, I'll have to ping the product team if not.

**Comment by LodewijkSioen** [comment]
I agree. Right now the resources for **Build** Agent Pools are there, but they are just not documented.

**Comment by andyfisher100** [comment]
This definitely needs adding!

**Comment by elbatk** [comment]
Hi all! This seems to be a pretty popular request so I've reached out to the Build team to see what they have!

**Comment by vtbassmatt** [comment]
Hey folks. Pipelines platform PM here. I'll try to get some docs added. In full transparency, it might be a while; we have a lot of other things we need to focus on right now.

In the meantime, feel free to use tools like Fiddler, Visual Studio IntelliSense on the .NET clients, or looking at the [Node.JS client source](https://github.com/Microsoft/azure-devops-node-api/blob/master/api/TaskAgentApi.ts) to discover these APIs. Anything in the `_apis/` namespace is a public contract and should not have breaking changes.

**Comment by nmangtani** [comment]
Here is how you can get agent pool at organization level
https://organizationname.visualstudio.com/_apis/build/Queues

Here is how you can get agent pool at project level
https://organizationname.visualstudio.com/projectname/_apis/distributedtask/queues

**Comment by vtbassmatt** [comment]
This is in progress.

**Comment by vtbassmatt** [comment]
Still trying to get this through. I'm a PM, not a dev, so I don't normally have to make changes in the core codebase. It turns out there are various gates I wasn't previously aware of 😁

**Comment by jawn** [comment]
@vtbassmatt thanks for your grit.

**Comment by vtbassmatt** [comment]
This finally got published and no one notified me :grin:

[Pools](https://docs.microsoft.com/en-us/rest/api/azure/devops/distributedtask/pools?view=azure-devops-rest-5.1), [queues](https://docs.microsoft.com/en-us/rest/api/azure/devops/distributedtask/queues?view=azure-devops-rest-5.1), and [agents](https://docs.microsoft.com/en-us/rest/api/azure/devops/distributedtask/agents?view=azure-devops-rest-5.1) are out there. Although they're marked under "5.1-preview", they've been around a while and should work at least back to 4.0.
