### ISSUE TITLE
Language options

### ISSUE THREAD

**Issue by jackbond** [MicrosoftDocs/vsts-docs#2850]
My organization is interested in building a few custom pipeline tasks. Is it possible to code them in c#, and not in javascript, the worst language ever inflicted on humanity?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 44581f4a-93df-7507-3844-eadedf9a6cc4
* Version Independent ID: 33c7bcf0-1512-975f-5ef8-9f2a192a84ad
* Content: [Add a Build or Release Task](https://docs.microsoft.com/en-us/azure/devops/extend/develop/add-build-task?view=vsts)
* Content Source: [docs/extend/develop/add-build-task.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/extend/develop/add-build-task.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by elbatk** [comment]
Hi @jackbond , we default to showing Node as it's cross-platform and where most of our 1st party tasks are authored. I'm **assuming** that you can code them in C#, but that's an assumption. Adding @vtbassmatt to straighten me out!

**Comment by vtbassmatt** [comment]
No, it is not possible. You can either use something that compiles to JavaScript (we like TypeScript on our team) or PowerShell for Windows-only tasks. We've considered adding .NET / C# as another option, but it has a lot of operational downsides for fairly limited upside.
