### ISSUE TITLE
Confusing YAML Schema description

### ISSUE THREAD

**Issue by mrumpf** [MicrosoftDocs/vsts-docs#2851]
The structure above this sentence does not show what the sentence mentions: "jobs":
"For simpler pipelines, not all of these levels are required. For example, in a single-job build, you can omit the container for "jobs" since there are only steps. Also, many options shown here are optional and have good defaults, so your YAML definitions are unlikely to include all of them."
Instead of some logical structure, you should give a precise structure definition and an example, which you can copy if you want to create a pipeline with multiple jobs.

What is also missing here is a guideline what should go in a job. Do I run maven package and docker build in 2 steps of one job or should this go into different jobs with single steps each?

For example, if I add a "jobs" container to my azure-pipelines.yml I get the following error:
````
Could not queue the build because there were validation errors or warnings.
azure-pipelines.yml (Line: 13, Col: 1): 'pool' is not allowed. 'jobs' is already defined and is mutually exclusive.
azure-pipelines.yml (Line: 16, Col: 1): 'steps' is not allowed. 'jobs' is already defined and is mutually exclusive.
````
After a lot of trial and error I was able to get the following azure-pipelines.yml working:
````
trigger:
- master

jobs:
- job: build
  pool:
    vmImage: 'Ubuntu-16.04'
  steps:
  - script: |
      echo Starting the build
      env
      java -version
      ./mvnw clean package -Dmaven.test.failure.ignore=true -e -U
    displayName: 'Build with Maven'
  - script: |
      env
      echo docker build -t $(dockerId)/$(imageName) .
    displayName: Docker Build
- job: test
  dependsOn: build
  condition: succeeded()
  pool:
    vmImage: 'Ubuntu-16.04'
  steps:
  - script: |
      echo Performing tests
      env
      ls -la
    displayName: 'Running integration tests'
````
The next issue is how I get the ACR coordinates injected into the 2nd build step.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7458d5b2-1bb7-7d87-7ce6-2b0c430b0155
* Version Independent ID: edf5bbd3-a3f0-5426-e985-31290f8afd05
* Content: [YAML schema - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=vsts&tabs=schema)
* Content Source: [docs/pipelines/yaml-schema.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/yaml-schema.md)
* Product: **devops**
* GitHub Login: @erickson-doug
* Microsoft Alias: **macoope**

**Comment by vtbassmatt** [comment]
Thanks for the feedback. We need a better entry point for people writing their first YAML, or growing from a super simple one to a more complex one. The schema doc isn't that place, and it isn't supposed to be. (Of course, the schema doc should link to that place, wherever it is, to help with discoverability.) I'll take a look at this tomorrow.

**Comment by vtbassmatt** [comment]
Thanks for the feedback. We need a better entry point for people writing their first YAML, or growing from a super simple one to a more complex one. The schema doc isn't that place, and it isn't supposed to be. (Of course, the schema doc should link to that place, wherever it is, to help with discoverability.)

**Comment by vtbassmatt** [comment]
@vijayma this is the kind of feedback I was mentioning this morning. We have "101" (just get SOMETHING working) and "400+" (I'm an expert and need a refresher on the precise syntax) content, but we've got a big hole in the middle.

**Comment by AceHack** [comment]
You've got a big hole on the 400+ content as well.  Missing a lot here.

**Comment by vtbassmatt** [comment]
@AceHack can you elaborate? I want to prioritize giving the people what they want -- suggestions welcomed.

**Comment by santusri** [comment]
Hi All, I have an angular app that creates Clouformation template. Thus it can be deployed on self-hosted aws (ubuntu) from vsts pipeline.  Thus, in release pipeline, I have included s3 upload and cloud formation update/create stack task. I achieved uploading the cloudformation templates to S3, but not able to map to CFI stack. FYI.. I am unable to map the s3 artifacts to my CFI, as it's my Self hosted agent. Please share your thoughts..? thanks.

**Comment by vtbassmatt** [comment]
@santusri it sounds like you need some specific help with the product. Please file a ticket on [Developer Community](https://developercommunity.visualstudio.com/spaces/21/visual-studio-team-services.html).

**Comment by santusri** [comment]
@vtbassmatt, thanks for the information. Can you help to resolve this error on build pipeline with self-hosted agent. Error "No agent found in pool Ubuntu-EC2-UE1 which satisfies the specified demands:
 maven
 Agent.Version -gtVersion 1.91.0"

**Comment by vtbassmatt** [comment]
Please open an issue on Developer Community.

**Comment by vtbassmatt** [comment]
http://docs.microsoft.com/azure/devops/pipelines/process/runs now describes better what happens in each kind of container (stages, jobs, steps). We've also improved the schema doc with concrete examples of syntax everywhere.
