### ISSUE TITLE
Full path of the downloaded file is not $env:DOWNLOADSECUREFILE_SECUREFILEPATH

### ISSUE THREAD

**Issue by yxie97** [MicrosoftDocs/vsts-docs#2854]
Based on my experience, the full path of the downloaded file is not $env:DOWNLOADSECUREFILE_SECUREFILEPATH as documented. If it's in a task group, then i can't even control it as an output variable. It generates some kind of the ID and concatenated with "securefilepath". If it is used in a release pipeline directly, you can specify an output variable so it can be referenced as a more user friendly name such as myCertFilePath.SecureFilePath 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a5f8376-3654-0ed4-d9f8-d15f28350783
* Version Independent ID: f393daba-6515-6c26-71ac-b557e8c8dad1
* Content: [Download Secure File task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/download-secure-file?view=vsts)
* Content Source: [docs/pipelines/tasks/utility/download-secure-file.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/utility/download-secure-file.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by gbaytler** [comment]
This path worked for me in the task inside Task Group. I also placed Download Secure File task in the same task group.
$(Agent.TempDirectory)\file-name-used-when-adding-secure-file-to-the-library

**Comment by phroiland** [comment]
Here's a nice little hack to get the filepath from yaml:

steps:
  - script: echo $(Agent.TempDirectory)
