### ISSUE TITLE
Docker task, Build Context missing info

### ISSUE THREAD

**Issue by rauljmz** [MicrosoftDocs/vsts-docs#2855]
In the page:
https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/docker?view=vsts
for the property ```Build Context```, add info explaining its value is ignored unless ```Use Default Context``` is set to *false* (default is *true*)

Also, ```Use Default Build Context``` should be ```Use Default Context``` (already reported in [this issue](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/docker?view=vsts#), which is now closed but it seems it has not been fixed).

**Comment by shashankbarsin** [comment]
We've updated the Docker task documentation to match the YAML input names as well as the labels in Designer version of the task.

About `buildContext` input, build context is a set of files located at the path provided as value for this task input. These files are sent to the docker daemon during the build which can be used in the filesystem of the image. About the importance of this input, take the example of a large monorepo where the path corresponding to the entire monorepo directory has been specified as value to the `buildContext` input. This would result in a slower docker build as it means compression will be done over more files and sent across to the docker daemon.

Thanks for the suggestion on adding this to our docs. We are working on a set of How-to Guides for Azure Pipelines with respect to container. I will certainly consider adding a note on this

**Comment by damienwebdev** [comment]
@shashankbarsin just to comment in here, as there's still some vagueness here:

`buildContext` docs currently state: 

> (Required if useDefaultContext == false) Path to the buildContext.

But don't clarify where the path is relative to. For example, should I assume that the `buildContext is relative to the directory of the `Dockerfile` specified, or from the location of the `azure-pipelines.yml` file or from the base build directory?

Some clarity here would also be helpful.

**Comment by bbernovici** [comment]
I have also been confused by this. Having the following structure:
- folder 1
| ----------  Dockerfile
- folder 2
| ----------  Dockerfile
- folder 3 (files manipulated by Dockerfile)

When I ran a Docker task, I was unable to retrieve contents from folder 3 before specifying the buildContext property, which is relative to the azure-pipelines.yml. 
`buildContext: .` worked for me.

**Comment by zahidferz** [comment]
Is there any update of this? I m tryng to use a dockerfile from one repo , and send the context of other repo to the docker task

   --------Yaml---------

 - checkout: docker-repo
      path: docker-repo
    - checkout: self
      path: self

    - task: Docker@1
      displayName: Build image
      inputs:
        command: build
        azureSubscriptionEndpoint: $(azureSubscriptionContainerRegistry)
        azureContainerRegistry: $(azureContainerRegistry)    
        dockerFile: $(Agent.BuildDirectory)/docker-repo/Docker/Dockerfile
        imageName: $(Build.Repository.Name):v$(Build.BuildNumber)
        buildContext: $(Agent.BuildDirectory)/self

Im getting an error on the build context . It seems that the task is not seing my /self repo (where the context is)
