### ISSUE TITLE
Where is the designer?

### ISSUE THREAD

**Issue by Daniel15** [MicrosoftDocs/vsts-docs#2861]
I don't want to have to deal with YAML manually, and would rather get started with a designer (and manually tweak the YAML if needed). The article says "After you have the sample code in your own repository, create a pipeline using the instructions in Use the designer", however after adding the Azure Pipelines GitHub app I don't see a designer at all:

![](https://d.sb/2018/12/firefox_21-11.34.35.png)

 Do I really need to manually type YAML?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a494f5a-6143-e567-6c0f-e2c817b1f1a9
* Version Independent ID: 15819679-5914-25f6-34f8-91f1da16b0bf
* Content: [Build ASP.NET apps - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/apps/aspnet/build-aspnet-4?view=vsts)
* Content Source: [docs/pipelines/apps/aspnet/build-aspnet-4.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/apps/aspnet/build-aspnet-4.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by andyjlewis** [comment]
Hi @Daniel15. A couple of things to note. 

A pipeline is either a designer pipeline or a YAML pipeline. If you choose designer, then you don't use YAML at all. You instead use the drag-and-drop designer. (You can copy snippets of YAML to help you replicate your logic if you later decide you want to instead create a new YAML pipeline.)

If you want to use the designer, and you're using the new YAML pipeline creation experience, then in Step 1 you should see a link to use the designer.

![image](https://user-images.githubusercontent.com/14275472/50384868-4e9a2a80-0699-11e9-8cbb-13ec3c225ca1.png)

**Comment by paule96** [comment]
I have the same wish like @Daniel15

**Comment by vtbassmatt** [comment]
We're continuing to improve the experience around editing YAML, both on the web and in our [VS Code extension](https://marketplace.visualstudio.com/items?itemName=ms-azure-devops.azure-pipelines). It's not on the roadmap (and not a goal) to make the existing visual editor directly work on YAML pipelines. If you like the visual editor, feel free to keep using it -- both types of pipelines use the same orchestration engine, task model, and agents.

There's a "view as YAML" button you can use on a per-step or per-pipeline basis. However, as with most generated code, the output often needs some cleaning up before it's nice to work with.
