### ISSUE TITLE
Need improvement in custom conditions

### ISSUE THREAD

**Issue by abhinavadepu502** [MicrosoftDocs/vsts-docs#2862]
Add a path match to the predefined variables to return true or false in the build pipeline task

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5673ec1-c7d1-e0ac-043a-8fc3d5b226a9
* Version Independent ID: b4872831-51c0-6cf8-1c56-de20beb38a80
* Content: [Build pipeline triggers - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/triggers?view=vsts&tabs=yaml)
* Content Source: [docs/pipelines/build/triggers.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/build/triggers.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by vtbassmatt** [comment]
@abhinavadepu502 can you say a little more about what you're looking for here? I don't have enough context to understand the request. Thanks!

**Comment by steved0x** [comment]
@abhinavadepu502 I'm closing this issue due to no response, but if this is still something you are looking for, please file an issue here: https://developercommunity.visualstudio.com/spaces/21/index.html

Thank you for your feedback.
