### ISSUE TITLE
Lock does not prevent commits

### ISSUE THREAD

**Issue by Naphier** [MicrosoftDocs/vsts-docs#2865]
I just tried this out. Created a branch and locked master. I did a PR from the new branch back in to master. No problem. I did a change on master and pushed directly in to master. No good. Does the lock not lock out the person who put up the lock? I'll have to test when my team is back, but I would prefer this not be the case (you know in case I forget and push to master...). 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c8ffea81-86af-46cb-a290-5ce83924f235
* Version Independent ID: 2ea32d72-75d8-42f9-bf33-756b1e00b3f2
* Content: [Lock a branch in your Git repo - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/lock-branches?view=vsts)
* Content Source: [docs/repos/git/lock-branches.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/repos/git/lock-branches.md)
* Product: **devops**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
@Naphier I can check but I believe when you lock a branch, it is locked for others but not for you.

If you are talking about master branch, can you use branch policies which would disable pushing directly to master, and ensure that your team doesn't have [Bypass policies when pushing](https://docs.microsoft.com/en-us/azure/devops/organizations/security/permissions?view=vsts#git-repository-object-level) permission which would allow them to override that policy? (By default, contributors group does not have this). Enabling any branch policy on master would prevent direct pushes to master. More info on branch policies: https://docs.microsoft.com/en-us/azure/devops/repos/git/branch-policies?view=vsts

**Comment by blueelvis** [comment]
@steved0x - Could you please add this clarification in the document as well? I just encountered this same issue and this is not documented.

/reopen
