### ISSUE TITLE
No hint about issues with using variable groups in build pipeline

### ISSUE THREAD

**Issue by mrumpf** [MicrosoftDocs/vsts-docs#2867]
My azure-pipelines.yml looks like this:

````
trigger:
- master

variables:
- group: azure-coordinates

jobs:
- job: build
  pool:
    vmImage: 'Ubuntu-16.04'
  steps:
  - script: |
      echo Starting the build
      env
      az --version
      java -version
      ./mvnw clean package -Dmaven.test.failure.ignore=true -e -U
      ls -la *
    displayName: 'Build with Maven'
````
When committing the yaml I get the following error:
````
An error occurred while loading the YAML build pipeline. Variable group azure-coordinates was not found or is not authorized for use.
````

I cannot find any hint about this error message on the internet.

Thank you for your feedback!

The issues in this repo are for documentation feedback.

If you are submitting your documentation feedback issue directly through GitHub, please provide the URL of the article so we can route the feedback to the correct author.

Please report Azure DevOps or TFS software bugs, feedback, or questions in the [Azure DevOps Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html).

**Comment by mrumpf** [comment]
In the visual designer of my azure-pipelines.yml I found a tab "variables" and on the "variables group" item I could click on "link variable group" and select the azure-coordinates group I created.
After I did that the above YAML started to work :(

**Comment by mrumpf** [comment]
More questions about this:

1. Why is adding the "variables.group:" keys to my azure-pipelines.yml not enough linking? With adding the "variables.group: azure-coordinates" entry, I'm actually linking my project with the variable group.
2. How do I link a variable group to a project programmatically? I could not find anything in the REST API when searching for the keyword "link"

**Comment by gitfool** [comment]
I just hit the same issue with [Cake.Dungeon/#18](https://dev.azure.com/gitfool/Cake.Dungeon/_build/results?buildId=18&view=results). Reading the docs I had the impression I only needed to add the variable group to `azure-pipelines.yml`, but it seems it must be linked via the UI too.

**Comment by mrumpf** [comment]
A similar issue seems to happen when I try to build a Docker image and use a service connection in the azureSubscriptionEndpoint parameter.
```
Could not queue the build because there were validation errors or warnings.
Job build: Step  input azureSubscriptionEndpoint references service connection mrumpfContainerRegistryRGServiceConnection which could not be found. The service connection does not exist or has not been authorized for use. For authorization details, refer to https://aka.ms/yamlauthz.
```
When I click "authorize resources and run" this authorization is granted and the build starts.
Why is this manual action necessary here? When referencing the service connection I implicitly authorize the resource to be accessed.

Shall I create a new ticket for that?

**Comment by vtbassmatt** [comment]
Doc update is pending.

**Comment by mrumpf** [comment]
Thanks for the update! From an automation perspective, having to use the UI to do the linking is breaking the YAML flow here. In GitLab I do not need to do that. Someone creating a variable group in their organization needs to be aware of the fact that all projects in that org have access to the variable groups.
In other CI tools I can just add my YAML file and the build/deployment works. In Azure DevOps I need to add a YAML, but in order to make it work, I need either to link a variable group via UI (or probably via API?) or define a service connection also via UI (or API). 

Why not moving the manual interaction to the entity which is referenced here?
So when someone creates a variable group at the organization level, then the permission is automatically granted to reference it from all builds in that organization. When you want to limit the scope of the variable group, you create it as part of a project instead and only this project is allowed to refernce it.
In this case you could access the variable group without having to link it explicitly from the build.

**Comment by vtbassmatt** [comment]
Thanks for the feedback. Different CI systems have come at this problem from different angles. I know in at least one system, they have you encrypt the secret using the web and then embed it directly into the YAML directly. I didn't know how GitLab did theirs, so that's interesting to learn.

Soon, service connections will have an auto-authorize flow by default. And even in cases where you lock it down, the experience of getting authorized will be better. I'm not sure what our plans are for variable groups, but I'll pass your feedback along to the PM who owns it.

**Comment by gtbuchanan** [comment]
> It's a security feature, though: anyone with the ability to push to your repo (including, potentially, forks) can alter your pipeline definition. So, mentioning the variable group in the YAML isn't enough -- if I knew the name of a sensitive variable group, I could maliciously grab whatever secrets it's holding.

@vtbassmatt I wanted to get some clarification on your statement here. I inferred, potentially incorrectly, that you meant a PR from a fork could grab secrets from a variable group. However, in my understanding, it is also a security feature that PRs from forks are not passed secrets by default ([per docs](https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/github?view=azure-devops&tabs=yaml#validate-contributions-from-forks)). Are you saying this does not apply to variable groups?

**Comment by vtbassmatt** [comment]
Secrets in a variable group are not passed to pipeline runs against forks, unless you choose (in the UI) to give secrets to forks.

**Comment by jontreynes** [comment]
> In the visual designer of my azure-pipelines.yml I found a tab "variables" and on the "variables group" item I could click on "link variable group" and select the azure-coordinates group I created.
> After I did that the above YAML started to work :(

@mrumpf   Is there a way to do this with the new multi-pipeline feature? I do not see an option to link variables, but I see an option to "Authorize Access" which fails
