### ISSUE TITLE
Which versions of TFS does this apply to, if any?

### ISSUE THREAD

**Issue by andreymladenov** [MicrosoftDocs/vsts-docs#287]
It would be great if these types of articles stated what version of TFS this is included in, or when it is coming in. My company is using 2017 and have access to secure files, but this task is not available.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a5f8376-3654-0ed4-d9f8-d15f28350783
* Version Independent ID: f393daba-6515-6c26-71ac-b557e8c8dad1
* Content: [Download Secure File | Microsoft Docs](https://docs.microsoft.com/en-us/vsts/build-release/tasks/utility/download-secure-file)
* Content Source: [docs/build-release/tasks/utility/download-secure-file.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/build-release/tasks/utility/download-secure-file.md)
* Service: **unspecified**
* GitHub Login: @douge
* Microsoft Alias: **alewis**

**Comment by madhurig** [comment]
This task is only available on VSTS currently as indicated in the docs. It will be available in the next update of TFS 2018

**Comment by staal-it** [comment]
As of today this task is available: https://docs.microsoft.com/en-us/visualstudio/releasenotes/tfs2018-update2#secure-files-can-be-downloaded-to-agents-during-build-or-release
