### ISSUE TITLE
What is a draft release?

### ISSUE THREAD

**Issue by dudeNumber4** [MicrosoftDocs/vsts-docs#2872]
I know what it _sounds_ like, I want to know for sure.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8f3fff1a-f727-649e-fe35-5a2a879b4c19
* Version Independent ID: 99485814-29e5-76a4-0d1d-7637ef5907d2
* Content: [Understand releases and deployments - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/releases?view=vsts)
* Content Source: [docs/pipelines/release/releases.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/release/releases.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment]
Creating a draft release allows you to edit some of the settings for the release and the tasks, depending on your role permissions, before starting the deployment. The changes apply only to that release, and do not affect the settings of the original pipeline . Create a draft release using the "..." ellipses link in the release pipeline definition screen.

Thank you for your feedback, I will add this information to the appropriate topic.
