### ISSUE TITLE
Reference to VSS.SDK.js causes 404

### ISSUE THREAD

**Issue by myersnick** [MicrosoftDocs/vsts-docs#2875]
During my development, I had to swap:

sdk/scripts/VSS.SDK.js

for

lib/VSS.SDK.min.js

To avoid a 404 error on sdk/scripts/VSS.SDK.js

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 19c5725d-4a59-7019-7dd8-c77be8456e45
* Version Independent ID: b45dc1c1-3ba0-b517-8aa8-c947cfc1f2a2
* Content: [Add an Action](https://docs.microsoft.com/en-us/azure/devops/extend/develop/add-action?view=vsts#your-javascript)
* Content Source: [docs/extend/develop/add-action.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/extend/develop/add-action.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by nschonni** [comment]
Looks like the previous step aliased lib https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/extend/get-started/node.md so the example here should have done the same

**Comment by elbatk** [comment]
Adding a note to fix this, thanks people! :)
