### ISSUE TITLE
MS Project and Azure DevOps

### ISSUE THREAD

**Issue by TonieStark** [MicrosoftDocs/vsts-docs#2877]
Hi,

I just noticed the bad news at the top that the support for integrating MS Project and Azure DevOps will be dropped on the next release of the Office plug-in :-(

That is very unfortunate!

I do have some follow up questions:

1. Where is the official information about this support being dropped?

2. For how long will one be able to use the current version of the plug-in (Team Foundation Server Office® Integration 2017)?

3. What is the long-term replacement for this functionality (supporting integration of WI handling and project scheduling, that is)?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4f6edd47-46d7-ab0d-db47-d73bc45d6b43
* Version Independent ID: 6ac2ae49-0bd0-2c28-fc87-7f034dd96443
* Content: [Create your backlog and tasks using Project - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/backlogs/office/create-your-backlog-tasks-using-project?view=vsts&tabs=office-365)
* Content Source: [docs/boards/backlogs/office/create-your-backlog-tasks-using-project.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/boards/backlogs/office/create-your-backlog-tasks-using-project.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by danhellem** [comment]
Hello Tonie,

1) You can see this in the [VS 2019 Release notes](https://docs.microsoft.com/en-us/visualstudio/releases/2019/release-notes-preview#VS2019_Preview1)

2) Right now we don't have plans to deprecate the plugin from connecting to Azure DevOps or older versions of TFS

3) We don't have any short term plans to replace it. The reality is it does not get a lot of use. We are tracking this and may invest further in the future.

note: Excel plugin will continue to work as is

**Comment by GaryAshby** [comment]
Hello Danhellem, I'm not that I'm understanding this clearly. We use the TFS Office plugin in MS Project to edit stories in Azure DevOps. Our project managers don't use Visual Studio. 
1. Will this keep working for the near future?
2. Will there be a future sync between Project Online and Azure DevOps?
