### ISSUE TITLE
Can we add an example for using Hosted Windows Container?

### ISSUE THREAD

**Issue by denhsu** [MicrosoftDocs/vsts-docs#2878]
as title

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3339a2e0-be29-1363-f588-b231d4472c02
* Version Independent ID: 72dd11a3-704d-d0fd-6dfa-cf49f3352de3
* Content: [Container Jobs in Azure Pipelines and TFS - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/container-phases?view=vsts&tabs=yaml)
* Content Source: [docs/pipelines/process/container-phases.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/container-phases.md)
* Product: **devops**
* GitHub Login: @erickson-doug
* Microsoft Alias: **macoope**

**Comment by vtbassmatt** [comment]
If you're using hosted pools, all the Asp.Net tools are already available. Is this for a private agent scenario?

**Comment by denhsu** [comment]
Hi @vtbassmatt Thanks for the reply.  Basically, we are using NPM in our build pipeline with hosted agent VS2017.   the NPM steps are taking a while and we are looking for ways to improve the build performance or containerize the build like http://upflow.co/l/OEpo/2018/10/containerized-build-pipeline-azure-devops

**Comment by denhsu** [comment]
just looking for ways to improve our npm build whether to use hosted agent or private agent.
