### ISSUE TITLE
Typo in 'What is an Organization?' section

### ISSUE THREAD

**Issue by geokaps** [MicrosoftDocs/vsts-docs#2882]
On this page under the 'Structure your organization' -&gt; 'What is an Organization', the paragraph starts with "And organization in Azure DevOps is a..." where it should say "*An* organization in Azure DevOps is a..."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 01770b43-fd5b-efbc-36f5-af91a3c8cf5a
* Version Independent ID: 7c046a91-37f9-32e3-dc3e-dfa922c456be
* Content: [Plan your organizational structure - Azure DevOps - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/user-guide/plan-your-azure-devops-org-structure?view=vsts)
* Content Source: [docs/user-guide/plan-your-azure-devops-org-structure.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/user-guide/plan-your-azure-devops-org-structure.md)
* Product: **devops**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by nschonni** [comment]
This is being fixed in #2871

**Comment by chcomley** [comment]
Thanks for letting us know and for providing the fix! @geokaps and @nschonni
