### ISSUE TITLE
Need clarification on Agent Pool Maintenance Setting Days

### ISSUE THREAD

**Issue by patrick-king** [MicrosoftDocs/vsts-docs#2883]
What happens in Agent Pool Settings -&gt; Maintenance if I don't check any days (which is the default)? Does that cause the maintenance to run every day, or no days? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4409a9cb-8448-edd6-da0a-243e5601aa3e
* Version Independent ID: ec15f71a-a76d-c3f9-1d31-832f92183ef4
* Content: [Agents pools - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/pools-queues?view=tfs-2018)
* Content Source: [docs/pipelines/agents/pools-queues.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/agents/pools-queues.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by vtbassmatt** [comment]
Fixing
