### ISSUE TITLE
service has different name

### ISSUE THREAD

**Issue by ShimonLeb** [MicrosoftDocs/vsts-docs#2885]
> Run services.msc and look for "Azure Pipelines Agent (name of your agent)"

for me it was `vstsagent.{organization}.{agent_name}`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43799c5d-2f13-cc76-a1c0-a3f850e16d4e
* Version Independent ID: 97a5b73f-faf7-f9c0-9269-fc79984616d6
* Content: [Deploy a build and release agent on Windows - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/v2-windows?view=vsts)
* Content Source: [docs/pipelines/agents/v2-windows.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/agents/v2-windows.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by LanceMcCarthy** [comment]
Just wanted to cross-reference a potentially related bug report because I mention this issue in the bug report: https://developercommunity.visualstudio.com/content/problem/419236/windows-agent-incorrect-function-error-when-window.html

**Comment by vtbassmatt** [comment]
We've changed the name a few times over the years. Doc'ing the ones I know about.
