### ISSUE TITLE
Issue installing provisioning profile on macOS agent

### ISSUE THREAD

**Issue by frankyang289** [MicrosoftDocs/vsts-docs#2886]
I am running this command: sudo cp &lt;myProfile&gt; ~/Library/MobileDevice/Provisioning\ Profiles/&lt;myProfileUUID&gt;.mobileprovision and get the following error

cp: /Users/vsts/Library/MobileDevice/Provisioning\ Profiles/&lt;myProfileUUID&gt;.mobileprovision: No such file or directory

Is anyone else getting the same issue?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3e66a70d-e359-9d0a-0143-a9e43b263795
* Version Independent ID: 7b320a02-0a63-947a-3017-4826ab461112
* Content: [Sign Your Mobile App During CI - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/apps/mobile/app-signing?view=vsts&tabs=apple-preinstall#apple)
* Content Source: [docs/pipelines/apps/mobile/app-signing.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/apps/mobile/app-signing.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by hashtagchris** [comment]
Hi @frankyang289, did you replace the `<myProfile>` and `<myProfileUUID>` placeholders? What does `ls -la ~/Library/MobileDevice` return?

**Comment by frankyang289** [comment]
Hi @hashtagchris, I am getting: ls: /Users/vsts/Library/MobileDevice: No such file or directory. I also did ls -al

**Comment by nacient** [comment]
I am potentially getting a similar issue where my xcode task (xcodeversion=10) fails to find the ProvisioningProfile that my InstallAppleCertificate@2 task is supposed to install:
error: "Register" requires a provisioning profile with the Wireless Accessory Configuration feature. Select a provisioning profile for the "Release" build configuration in the project editor. (in target 'Register')
2019-02-08T01:35:10.6560090Z ** BUILD FAILED **

My pipeline is using yaml. The build logs show that the 'Pre-job: InstallAppleProvisioningProfile' and 'InstallAppleProvisioningProfile' tasks are successful, however they do not show any command being executed. I saw this thread (https://github.com/Microsoft/azure-pipelines-tasks/issues/8387) and have tried provisioning files with both extensions:  'mobileprovision' and 'provisionprofile'.

**Comment by hashtagchris** [comment]
@frankyang289 You can run `mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles` ahead of the copy. However if you're using a Microsoft-hosted macOS pool, you should follow the "Install during the build" instructions, not the "Preinstall on the build agent" instructions.

**Comment by hashtagchris** [comment]
@nacient You should see the pre-jobs running commands (`openssl`, `security`, etc). I've added a sample yaml with Xcode signing [here](https://github.com/hashtagchris/XcodeHelloWorld/blob/master/azure-pipelines-Xcode-signing.yml). Build [here](https://dev.azure.com/hashtagchris/public/_build/results?buildId=30&_a=summary).

**Comment by nacient** [comment]
Hi @hashtagchris thanks for updating the documentation and providing a sample! That helped me. Ultimately my problem was a silly misspelling of the provisioningProfileLocation value ('Secure Files' instead of 'secureFiles'.) Was following the UI documentation (https://docs.microsoft.com/en-us/azure/devops/pipelines/apps/mobile/app-signing?view=azure-devops&tabs=apple-install-during-build) and that is how the UI spells which is different from the yaml task. 

I am getting a different error now related to my pod schemes not supporting provisioning but one was specified manually. I found this thread and will attempt this solution: https://github.com/fastlane/fastlane/issues/10543#issuecomment-336759615

If I set the signingOption to default like you have it in the sample, my xcode build fails with:
No profiles for 'com.***.' were found: Xcode couldn't find any iOS App Development provisioning profiles matching 'com.***.register'. Automatic signing is disabled and unable to generate a profile. To enable automatic signing, pass -allowProvisioningUpdates to xcodebuild. (in target 'Register'). Do you know how I can pass this option in the yaml build?

**Comment by hashtagchris** [comment]
@nacient You can pass additional arguments to xcodebuild using the `args` task input. (There's also an `exportArgs` input, used for the export phase of packaging if `packageApp` is true.) See https://github.com/Microsoft/azure-pipelines-tasks/blob/master/Tasks/XcodeV5/task.json for a list of all inputs.

To use `-allowProvisioningUpdates`, I think you have to be signed into your Apple Developer account within Xcode (Xcode > Preferences ... > Accounts > Apple IDs). You can do this for self-hosted agents, but it's not an option for the Microsoft-hosted macOS pool. BTW, I see something about a "Register" target in your error message. I'm not familiar with this target, but if your build registers new development devices with Apple, you'll probably need to use a self-hosted agent and the `-allowProvisioningDeviceRegistration` option.

A couple of suggestions for diagnosing Xcode build failures:

* Try running the same `xcodebuild` command-lines the Xcode task runs on the Mac you use for development, tweaking file paths as necessary. Something like:

```
# Switch to the root directory of the Xcode project.
cd ~/Documents/XcodeProjects/XcodeHelloWorld

# Optionally target a specific version of Xcode.
# This is equivalent to running xcode-select --switch, but only affects the current session. 
export DEVELOPER_DIR=/Applications/Xcode_10.app/Contents/Developer/

# Confirm the version of Xcode is close to the version used on the build agent.
xcodebuild -version

# Run the "build" target, using the XcodeHelloWorld scheme.
xcodebuild -sdk iphoneos -configuration Release -workspace ./XcodeHelloWorld.xcodeproj/project.xcworkspace -scheme XcodeHelloWorld build
```

In general, if the command-line works locally, it should work on the agent, assuming you're installing the right certificate and provisioning profile, and using the same version of Xcode.

* If you get xcodebuild working locally, look at the output from CodeSign to see what provision profiles you need to install. Example from my build:

```
Signing Identity:     "iPhone Developer: Chris Sidi (7RZ3N927YF)"
Provisioning Profile: "iOS Team Provisioning Profile: com.hashtagchris.*"
                      (6ffac825-ed27-47d0-8134-95fcf37a666c)
```

* On the Mac you use for development, start with a clean slate by committing all your changes to your git repository, closing Xcode and renaming the Provisioning Profiles directory (`mv ~/Library/MobileDevice/Provisioning\ Profiles ~/Library/MobileDevice/Old\ Provisioning\ Profiles`). Then launch Xcode and get your project building. The provisioning profile(s) under `~/Library/MobileDevice/Provisioning\ Profiles` are the ones you need to install as part of your build.

**Comment by nacient** [comment]
Thanks @hashtagchris! Will try this out.

**Comment by davidstaheli** [comment]
Closing since it appears this was resolved.  Otherwise, please feel free to re-open.
