### ISSUE TITLE
Biased towards Git based source control systems

### ISSUE THREAD

**Issue by bogan** [MicrosoftDocs/vsts-docs#2887]
The section titled "Azure Pipelines" seems unnecessarily biased towards Git based source control systems. Surely you should also mention TFVC? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 916ab215-0c42-fd49-d600-52f2d9ed18ac
* Version Independent ID: a2d1f2b1-a9f0-7513-a52d-c48dc51e3ba7
* Content: [Get started with Azure Pipelines - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/get-started/?toc=/azure/devops/pipelines/toc.json&bc=/azure/devops/boards/pipelines/breadcrumb/toc.json&view=vsts)
* Content Source: [docs/pipelines/get-started/index.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/get-started/index.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by steved0x** [comment]
@bogan Thank you for your feedback. I am forwarding this feedback along, and here is some info for using Pipelines with TFVC, which is  a supported scenario:

https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/tfvc?view=vsts
