### ISSUE TITLE
Bold display of numbers/characters used as bullets

### ISSUE THREAD

**Issue by ozdemirveysel** [MicrosoftDocs/vsts-docs#2888]
How do I display numbers/chars as bold when using numbering in nested lists?

1. First item.
   a. Item 1
   b. Item 2
   c. Item 3
2. Second item.
   a. Nested item 1
   b. Nested item 2
   c. Nested item 3

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fa622358-f5bb-1f5c-177a-081a37b6acef
* Version Independent ID: 72f7fd16-a822-66c8-3a34-8905645ce5f2
* Content: [Markdown syntax for files, widgets, and wikis in Azure DevOps - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/project/wiki/markdown-guidance?view=vsts#lists)
* Content Source: [docs/project/wiki/markdown-guidance.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/project/wiki/markdown-guidance.md)
* Product: **devops**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by steved0x** [comment]
@ozdemirveysel Do you mean like this?

**1.** Item 1
**2.** Item 2
etc...

I don't think that is supported by markdown but I am assigning this to the author of the topic for their feedback.

**Comment by ozdemirveysel** [comment]
Yes @steved0x I want it to look like your example. However, if I do this way, unfortunately, the indents are not supported.
Thanks for your feedback

**Comment by ozdemirveysel** [comment]
any update?

**Comment by chcomley** [comment]
Hi @ozdemirveysel, I'm sorry for any confusion. What Steve said is correct - bolded indenting is not supported. If you're interested, please submit a [feature request](https://azure.microsoft.com/en-us/support/devops/) by selecting **Submit an idea**. Thanks!

**Comment by ozdemirveysel** [comment]
hi @chcomley, no problem. Thank you for your response.
