### ISSUE TITLE
latestFromBranch does not work

### ISSUE THREAD

**Issue by vigsterkr** [MicrosoftDocs/vsts-docs#2889]
I'm trying to use this task to in a PR to download artifacts from the refs/heads/develop branch (as stated by the documentation), but i'm always getting a 'Latest build from branch refs/heads/develop not found' error (see https://dev.azure.com/shogunml/shogun/_build/results?buildId=165).

i've even tried to specify a specific build as a source for the artifact (both the build is there and it was successful), but then i'm getting 'Build with ID 158 not found': https://dev.azure.com/shogunml/shogun/_build/results?buildId=169

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c0a16bcf-af6c-e278-f0a6-8ec95012ce4a
* Version Independent ID: ae442106-33b3-786f-2158-34eed3fed6e0
* Content: [Download Build Artifacts task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/download-build-artifacts?view=vsts)
* Content Source: [docs/pipelines/tasks/utility/download-build-artifacts.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/utility/download-build-artifacts.md)
* Product: **devops**
* GitHub Login: @erickson-doug
* Microsoft Alias: **dastahel**

**Comment by elbatk** [comment]
Hi @vigsterkr , sorry you're seeing this issue. Thanks for posting the logs, but I think that you will find a better answer for your question on the Azure DevOps Developer Community(https://developercommunity.visualstudio.com/spaces/21/index.html) which is actively monitored by the product team. I'm going to tag @alexmullans here for awareness, but also close this as a docs issue. When you find the solution to your issue, please feel free to reach out if you think there's something we should change with the docs to help others :)

**Comment by ajklotz** [comment]
I'm having the same problem here. Too bad issues filed here just can't be communicated directly to the product team.
