### ISSUE TITLE
"Full Syntax" is missing dependsOn & condition

### ISSUE THREAD

**Issue by edwardaskew** [MicrosoftDocs/vsts-docs#2890]
The Artifact download example contains dependsOn and condition fields which are not documented in the "full syntax" section. These *are* documented under the Multiple Jobs page but having the syntax for a single element split over multiple pages is a pain to deal with.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 54bf6c2f-95c1-943d-26ae-d7099143bccf
* Version Independent ID: 0833bb55-1e54-6953-ee69-de6d191d2ec1
* Content: [Build and release jobs in Azure Pipelines and TFS - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/phases?view=vsts&tabs=yaml)
* Content Source: [docs/pipelines/process/phases.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/phases.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment]
Thank you for your feedback. There is a separate topic related to conditions at https://docs.microsoft.com/azure/devops/pipelines/process/conditions?view=vsts&tabs=yaml. I'll add more prominent links to this in the related topics, including this one.
