### ISSUE TITLE
Permissions Audit Report

### ISSUE THREAD

**Issue by madrum** [MicrosoftDocs/vsts-docs#2891]
How do I get a report of changes to user or group permissions with a Project, as well as to Git Repos? for example, if I have no access to a Git repo on Monday, then full access on Tuesday, and then no access on Wednesday, how do I get a report showing those changes?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce8b2923-a3dc-7055-6550-d4943faa5a68
* Version Independent ID: fce8bd86-a25c-341e-5be4-61f19e4dd08f
* Content: [View permissions for yourself or others - Azure DevOps & TFS](https://docs.microsoft.com/en-us/azure/devops/organizations/security/view-permissions?view=vsts&tabs=new-nav)
* Content Source: [docs/organizations/security/view-permissions.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/security/view-permissions.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
The ability to audit permission changes isn't a supported feature at this time. You may want to suggest it through our [Suggest a Feature page](https://developercommunity.visualstudio.com/content/idea/post.html?space=21), or upvote this suggest: [Organization Security Audit Log](https://developercommunity.visualstudio.com/content/idea/337057/organization-security-audit-log.html).
