### ISSUE TITLE
Cannot download artifact

### ISSUE THREAD

**Issue by nealAR** [MicrosoftDocs/vsts-docs#2893]
The Publish Pipeline Artifact task in the initial project appears to work fine. In order the console output reads: 

Information, Processed 1 files from /home/vsts/work/1/a successfully.
Information, Uploading 1 files from directory /home/vsts/work/1/a to Drop service.

The values I'm using are: 

steps:
- task: PublishPipelineArtifact@0
  displayName: 'Publish Pipeline Artifact'
  inputs:
    artifactName: buildparams.csv

    targetPath: '$(Build.ArtifactStagingDirectory)'

However I cannot download the artifact in the next build (YAML below). 

steps:
- task: DownloadPipelineArtifact@0
  displayName: 'Download Pipeline Artifact'
  inputs:
    pipelineId: UtilityService.Dev

    artifactName: buildparams.csv

    targetPath: '$(Build.ArtifactStagingDirectory)'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 861ce7a5-4fa4-55f1-2c97-46a9cc6a2f66
* Version Independent ID: bdf954b9-9bbe-8b34-b674-71ad8153519d
* Content: [Publish and consume Pipeline artifacts in builds - Azure Pipelines and TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/pipeline-artifacts?view=vsts&tabs=yaml#download-pipeline-artifacts)
* Content Source: [docs/pipelines/artifacts/pipeline-artifacts.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/artifacts/pipeline-artifacts.md)
* Product: **devops**
* GitHub Login: @alexmullans
* Microsoft Alias: **amullans**

**Comment by alexmullans** [comment]
Can you post logs from the unsuccessful download step on https://developercommunity.visualstudio.com/spaces/21/index.html?

**Comment by greigs** [comment]
I have having the same issue. This seems to be related to this issue: https://github.com/Microsoft/azure-pipelines-tasks/issues/8812

**Comment by elbatk** [comment]
Closing this one, thanks Mitch! If anyone has any other issues, feel free to open another issue!
