### ISSUE TITLE
The Maven task does not give an option for setting the server connection on the live system.

### ISSUE THREAD

**Issue by trajano** [MicrosoftDocs/vsts-docs#2899]
The Maven task does not give an option for setting the server connection on the live system.  Since it does not the following error appears

Failed to connect to localhost/127.0.0.1:9000: Connection refused (Connection refused) -&gt; [Help 1]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3009185e-269f-b9bb-d48c-7f5dfba67456
* Version Independent ID: 5d79be92-46ae-6500-500f-e2598ac99a6f
* Content: [Use SonarQube with Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/java/sonarqube?view=vsts)
* Content Source: [docs/java/sonarqube.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/java/sonarqube.md)
* Product: **devops**
* GitHub Login: @erickson-doug
* Microsoft Alias: **douge**

**Comment by davidstaheli** [comment]
Thanks for reporting this. We're going to move this issue to this repo:
https://github.com/Microsoft/azure-pipelines-tasks

/move to Microsoft/azure-pipelines-tasks
