### ISSUE TITLE
GitHttpClient.GetAnnotatedTagAsync    VssServiceResponseException: Found

### ISSUE THREAD

**Issue by DanXXu** [MicrosoftDocs/vsts-docs#2902]
i got a exception( VssServiceResponseException: Found ) when i  get git-annotatedTag from our tfs server by GitHttpClient.GetAnnotatedTagAsync.

## http request ##
GET http://mytfsserver.com/tfs/DefaultCollection/myproject/_apis/git/repositories/79e14f94-ef76-4ff4-8c87-ecd307afc5bd/annotatedTags/cdf05f24fa1dfab5ffe5e7890abcb0fa3f58f3a7 HTTP/1.1
Accept: application/json; api-version=3.2-preview
User-Agent: VSServices/15.131.28119.3 (xx.exe)
X-VSS-E2EID: 73ef52bf-f14c-4313-8da4-1c675f8877a3
Accept-Language: zh-CN
X-TFS-FedAuthRedirect: Suppress
X-TFS-Session: 826496e9-25b7-47eb-8ed8-c5dc2e1a770c
X-VSS-Agent: VSS: 04c96644-51e8-4b20-8157-83a0ad9c5e9c
Authorization: Basic OjdsazJlZXc0NGlrY2tpejZlNDVnNGFsb3hrcmlma3E3YW90ZnRwenV2cjVqazR2ZXhjY3E=
Accept-Encoding: gzip

## http response ##
HTTP/1.1 302 Found
Cache-Control: no-cache
Pragma: no-cache
Content-Type: application/json; charset=utf-8; api-version=3.2-preview.1
Expires: -1
Server: Microsoft-IIS/10.0
X-TFS-ProcessId: 69ad2774-206d-47d1-b0d2-295ab00ddbe4
ActivityId: c4b0b18f-a147-4809-8365-96ca925de408
X-TFS-Session: 826496e9-25b7-47eb-8ed8-c5dc2e1a770c
X-VSS-E2EID: 73ef52bf-f14c-4313-8da4-1c675f8877a3
X-FRAME-OPTIONS: SAMEORIGIN
X-VSS-UserData: 89d22540-a11d-47ff-bf3d-a09b58439ec1:xuxiaolong6
X-AspNet-Version: 4.0.30319
X-Powered-By: ASP.NET
P3P: CP="CAO DSP COR ADMa DEV CONo TELo CUR PSA PSD TAI IVDo OUR SAMi BUS DEM NAV STA UNI COM INT PHY ONL FIN PUR LOC CNT"
Lfs-Authenticate: NTLM
X-Content-Type-Options: nosniff
Date: Thu, 03 Jan 2019 07:24:48 GMT
Content-Length: 457

{"name":"refs/tags/5.4.1","objectId":"cdf05f24fa1dfab5ffe5e7890abcb0fa3f58f3a7","taggedObjectId":"1b74f2c095b39a902144c48b3be3ca48b235dfc7","taggedObjectType":"commit","taggedBy":{"name":"xxx","email":"xxx","date":"2018-12-20T03:49:28"},"message":"","url":"http://xxxx/tfs/DefaultCollection/xxx/_apis/git/repositories/79e14f94-ef76-4ff4-8c87-ecd307afc5bd/annotatedTags/cdf05f24fa1dfab5ffe5e7890abcb0fa3f58f3a7"}

 My english is poor , I hope someone can understand my question, and thanks.

**Comment by steved0x** [comment]
@DanXXu Thank you for your question. The GitHub issues in this repo are for documentation feedback, and it sounds like you have a product question. Please post your question here and they will take a look:

https://developercommunity.visualstudio.com/spaces/21/index.html

Thank you.

**Comment by DanXXu** [comment]
thanks.
