### ISSUE TITLE
Clarify support for Azure SQL Database

### ISSUE THREAD

**Issue by jawn** [MicrosoftDocs/vsts-docs#2904]
The release notes at https://docs.microsoft.com/en-us/tfs/release-notes/azuredevops2019 
mention "Support for Azure SQL Database".

This should be updated in this article wherever SQL Server is mentioned and the 2019 version applies.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 641b37fc-f117-aca0-32f4-8ea9b73e9d71
* Version Independent ID: 211130c6-43b8-f47f-3589-cb4d2a330231
* Content: [Requirements and compatibility - Azure DevOps Server & Team Foundation Server](https://docs.microsoft.com/en-us/tfs/server/requirements?view=vsts)
* Content Source: [https://mseng.visualstudio.com/DefaultCollection/TechnicalContent/_git/tfs-docs-pr?path=%2fdocs%2fserver%2frequirements.md&version=GBlive&_a=contents](https://mseng.visualstudio.com/DefaultCollection/TechnicalContent/_git/tfs-docs-pr?path=%2fdocs%2fserver%2frequirements.md&version=GBlive&_a=contents)
* Product: **devops-server**
* Git Login: **elbatk**
* Microsoft Alias: **elbatk**

**Comment by elbatk** [comment]
Hi @jawn , adding @aaronhallberg for awareness here, but we do need to add some info about that.

**Comment by KathrynEE** [comment]
@jawn - Thank you for your feedback. The Requirements article has been updated.
