### ISSUE TITLE
Can you give an example of codeCoverageClassFilter?

### ISSUE THREAD

**Issue by trajano** [MicrosoftDocs/vsts-docs#2907]
Can you give an example of codeCoverageClassFilter?  I can't seem to get any results when I use it.  But without it I get all the code which I don't want either.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 589e076c-9f67-77df-3204-4f549566f21b
* Version Independent ID: 2e51ef13-8fd3-1397-82f0-27c92f1ccee5
* Content: [Maven build and release task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/maven?view=vsts)
* Content Source: [docs/pipelines/tasks/build/maven.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/build/maven.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by davidstaheli** [comment]
Thanks for the suggestion.  Examples have been added to the docs and should be live within a few days.

```
codeCoverageClassFilter: # Optional. Comma-separated list of filters to include or exclude classes from collecting code coverage. For example: +:com.*,+:org.*,-:my.app*.*
```
