### ISSUE TITLE
Misleading YAML examples

### ISSUE THREAD

**Issue by tomjaguarpaw** [MicrosoftDocs/vsts-docs#2908]
The YAML examples on https://docs.microsoft.com/en-us/azure/devops/pipelines/process/container-phases?view=vsts&tabs=yaml are misleading.  They suggest that the `resources` stanza should be at the same level as `pool`, `container` and `steps`, but actually it should be at the level above, at the same level as `jobs`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3339a2e0-be29-1363-f588-b231d4472c02
* Version Independent ID: 72dd11a3-704d-d0fd-6dfa-cf49f3352de3
* Content: [Container Jobs in Azure Pipelines and TFS - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/container-phases?view=vsts&tabs=yaml)
* Content Source: [docs/pipelines/process/container-phases.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/container-phases.md)
* Product: **devops**
* GitHub Login: @erickson-doug
* Microsoft Alias: **macoope**

**Comment by vtbassmatt** [comment]
That would make the hierarchy more clear. (Did you try it, though? It works just fine as-is: we have a shortcut syntax for single-job pipelines.)

**Comment by tomjaguarpaw** [comment]
> It works just fine as-is: we have a shortcut syntax for single-job pipelines

Ah, I see.  When I saw

```yaml
resources:
  ...

pool:
  ...

strategy:
  ...

container: ...

steps:
  ...
```

I assumed that that block of YAML had to go into a higher level

```yaml
jobs:
  job:
    ...
```

block, because I've only ever seen `steps` inside a `job`, never at the top level.  I didn't realise the intention was give the file verbatim.  It turned out that putting `resources` inside `job: ... jobs: ...` doesn't work and that's why I filed this issue.

As you say the example is correct as given so you can consider the issue resolved from my point of view.  Whether you want to make any changes to inform readers about the shortcut syntax is up to you!

**Comment by vtbassmatt** [comment]
Cool. I did make a change to one of the examples (to help disambiguate), and I added an explicit reference to the two different syntaxes.
