### ISSUE TITLE
Permission and access to manage test plans

### ISSUE THREAD

**Issue by rmsjts88** [MicrosoftDocs/vsts-docs#2909]
Your article is wrong. Contributors can not 'manage test plans' unless their account is a member of the access level of Vs Enterprise. Please be specific when making statements about permissions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 92d59beb-f1ee-75d6-0d8b-5a5612003b23
* Version Independent ID: 0c875a53-b71b-86e1-00d4-8f453147b786
* Content: [Permissions and access for manual testing - Azure Test Plans](https://docs.microsoft.com/en-us/azure/devops/test/manual-test-permissions?view=vsts)
* Content Source: [docs/test/manual-test-permissions.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/test/manual-test-permissions.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment]
The test team tell me that:

“Manage test plans” is area path level permission. And It is ‘not set’ by default for ‘reader’ and ‘allow’ for ‘contributors’.

Anyhow for create test plan user would need VS enterprise access/test pro subscription/test manager license assigned. Access level permission and their use case is mentioned here : https://docs.microsoft.com/en-us/azure/devops/organizations/security/access-levels?view=vsts&tabs=stakeholder 

![1](https://user-images.githubusercontent.com/19287943/51547503-6282a900-1e5e-11e9-9e10-197cd11f1f23.png)

![2](https://user-images.githubusercontent.com/19287943/51547504-6282a900-1e5e-11e9-831c-6800ce89cc48.png)

**Comment by rmsjts88** [comment]
Thanks for your reply, I was mostly focused on the Access Level since if the user is not in VS Enterprise then he will not have access.
Can you tell me about the requirements?  We are not using TFS 'Azure Devops' services, we have a local TFS instance install. Since we have about a hundred users creating tests it is expensive to give Visual Studio Enterprise licensing to all of them. My security officer does not believe that a MTM license is enough since we are 'on prem' with TFS. 
Randy SchultzTFS Admin MCHS IT services

    On Tuesday, January 22, 2019, 9:57:39 AM CST, Alex Homer <notifications@github.com> wrote:  
 
 
The test team tell me that:

“Manage test plans” is area path level permission. And It is ‘not set’ by default for ‘reader’ and ‘allow’ for ‘contributors’.

Anyhow for create test plan user would need VS enterprise access/test pro subscription/test manager license assigned. Access level permission and their use case is mentioned here : https://docs.microsoft.com/en-us/azure/devops/organizations/security/access-levels?view=vsts&tabs=stakeholder
