### ISSUE TITLE
Use "build pipeline" instead of just "pipeline" throughout

### ISSUE THREAD

**Issue by sh4nji** [MicrosoftDocs/vsts-docs#2917]
What I find really confusing is that _pipelines_ gets used for both, _build pipelines_ and _release pipelines_. At least in the UI those two are different things with different features. As far as I understand YAML is only available for _build pipelines_. So should't this be called "Create your first build pipeline"?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 38f7a23b-ebd4-af3e-68a2-275f7e45c33e
* Version Independent ID: f552a18c-ba29-00d4-03b6-254d7556d319
* Content: [Create your first pipeline - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/get-started-yaml?view=vsts)
* Content Source: [docs/pipelines/get-started-yaml.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/get-started-yaml.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by andyjlewis** [comment]
The title is deliberately leading the target a bit. In many cases both building and deploying from YAML makes sense and we've begun showing examples of that approach. Also, we've got [Multi-stage pipelines](https://dev.azure.com/mseng/Azure%20DevOps%20Roadmap/_workitems/edit/1364226) on our [features timeline](https://docs.microsoft.com/en-us/azure/devops/release-notes/).
