### ISSUE TITLE
Build and Release Tasks Azure Pipelines - C# Custom Tasks

### ISSUE THREAD

**Issue by akash3456** [MicrosoftDocs/vsts-docs#2918]
is it possible to develop and run a custom c# task as a build task without using the third party task that is currently available in the azure devops Marketplace?

**Comment by steved0x** [comment]
@akash3456 That is a great question (and unfortunately I don't know the answer or I would tell it). The GitHub issues in this particular repo are for content feedback. For product questions and feedback, please file an issue here, and the right folks on the product team will take a look and get right back with you.

https://developercommunity.visualstudio.com/spaces/21/index.html

Thank you.
