### ISSUE TITLE
Missing > character (mistake)

### ISSUE THREAD

**Issue by amrock-my** [MicrosoftDocs/vsts-docs#2919]
The "Special characters in Wiki page titles" table lists all characters and their UTF-8 code, except the greater than sign '&gt;' is blank for that row.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d7892ee5-8b56-bd95-29bb-41ebb8a8bd7e
* Version Independent ID: eccf0785-0968-d6a2-d29e-0c4796aa165c
* Content: [Add, edit, or print wiki pages in Azure DevOps - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/project/wiki/add-edit-wiki?view=vsts&tabs=new-nav#special-characters-in-wiki-page-titles)
* Content Source: [docs/project/wiki/add-edit-wiki.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/project/wiki/add-edit-wiki.md)
* Product: **devops**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
I've published the update, which should go live within the next 2-12 hours. Thanks again for your feedback @amrock-my.
