### ISSUE TITLE
Provide explanation of /nodetect parameter 

### ISSUE THREAD

**Issue by cecedxx** [MicrosoftDocs/vsts-docs#292]
This documentation doesn't provide explanation of /nodetect parameter, please update it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d796f92a-8065-b7da-6af3-1f61f52f37d9
* Version Independent ID: 2c7e9f56-ab32-c6c3-4eb2-26ac6a5dbfd8
* Content: [Status command | Microsoft Docs](https://docs.microsoft.com/en-us/vsts/tfvc/status-command)
* Content Source: [docs/tfvc/status-command.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/tfvc/status-command.md)
* Service: **unspecified**
* GitHub Login: @douge
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
@cecedxx Thank you for letting us know, I've added this to our documentation backlog and we'll get it updated. Thank you.
