### ISSUE TITLE
Add try/catch around jObject accesses

### ISSUE THREAD

**Issue by fabricebauer** [MicrosoftDocs/vsts-docs#2921]
Hello, I think it would be safer to use try/catch around jObject accesses in case the function is called with a body which does not contain a pull request.
Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 915c7aa9-0969-912b-bbc4-a2b0bf9b1533
* Version Independent ID: 6a97a5e8-8397-be98-5528-70d20e8fbed8
* Content: [Use Azure Functions to create custom branch policies - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/create-pr-status-server-with-azure-functions?view=vsts)
* Content Source: [docs/repos/git/create-pr-status-server-with-azure-functions.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/repos/git/create-pr-status-server-with-azure-functions.md)
* Product: **devops**
* GitHub Login: @steved0x
* Microsoft Alias: **yohasna**

**Comment by fabricebauer** [comment]
I completely overlooked the global try/catch statement, please close my comment.
Thanks very much.

**Comment by steved0x** [comment]
@fabricebauer Thank you for your feedback and comments, and I am closing this issue per your request. Thank you.
