### ISSUE TITLE
More information in regards to creating template extension.

### ISSUE THREAD

**Issue by kdelorey** [MicrosoftDocs/vsts-docs#2923]
In regards to the "Can I publish or consume new templates through extensions in VS Marketplace?" section, it simply links to a blog post (which links to a [GitHub Sample](https://github.com/Microsoft/azure-pipelines-extensions/blob/master/Extensions/EnvironmentTemplateSample/vss-extension.json)) about creating a template extension. This works fine for basic scenarios, but I'm interested in having a bit more information.

My current struggle is creating linked process parameter inputs (see below example):
![alt text](https://i.imgur.com/uPLOJKR.png "Azure App Service")

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce3b1a51-8a5d-1aad-470c-a1e9ed1a3bf7
* Version Independent ID: 857c4c85-1915-8ec2-4586-a758eb423514
* Content: [Use stage templates in deployments - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/env-templates?view=vsts)
* Content Source: [docs/pipelines/release/env-templates.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/release/env-templates.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment]
Thank you for your feedback. I am unable to locate any additional information related to your question, but I will pass this on to the product team and update the topic based on any suitable response. You might also consider responding to the related blog post to see if you can solicit more details from the author.

**Comment by lleoh** [comment]
Page not found for link in the chapter about:
Can I publish or consume new templates through extensions in VS Marketplace?
Yes. See Adding release stage templates to your VSS extension for more details.

**Comment by alexhomer1** [comment]
Thank you. I will investigate to see if I can find an alternative page.
