### ISSUE TITLE
Redirect back to Azure DevOps instructions confusing for the Python project

### ISSUE THREAD

**Issue by michhar** [MicrosoftDocs/vsts-docs#2925]
Main Doc link:  https://docs.microsoft.com/en-us/azure/devops/pipelines/get-started-yaml?view=vsts#get-your-first-build

Note, this link was only part of the "Build Python apps in Azure Pipelines" tutorial [here](https://docs.microsoft.com/en-us/azure/devops/pipelines/languages/python?view=vsts&tabs=ubuntu-16-04)

Steps 5 and 6 are confusing.  When I'm back in the build Pipeline I'm shown "Select a template", "Configuration as code" with YAML as the option and "Featured" - not sure which to select as the instructions only says (with no mention of the "Select a template" blade that shows up.

```text
5. When you're redirected back to Azure Pipelines, select the sample app repository.

6. For the third step, Azure Pipelines analyzes the code in your repository. If your repository already contains an azure-pipelines.yml file, which is the case for all sample repositories, then this step is skipped. Or else, Azure Pipelines recommends a starter template based on the code in your repository.
```

Desired behavior:  Show a screenshot of the blade that is presented:

![image](https://user-images.githubusercontent.com/13988934/50703921-8050b100-100a-11e9-8b99-77edcbe8a748.png)

and add instructions on whether to select "Configuration as code" or "Python package" as the template.

Thanks!

**Comment by thomps23** [comment]
Closing as item exists in backlog to address if topic not updated already.
