### ISSUE TITLE
Need corrected wording and better instructions in "Get your first build section"

### ISSUE THREAD

**Issue by michhar** [MicrosoftDocs/vsts-docs#2926]
Doc Link:  https://docs.microsoft.com/en-us/azure/devops/pipelines/get-started-yaml?view=vsts#get-your-first-build

I'm not actually shown the YAML file used as is stated in step 7 - just the ability to select the YAML file path.  In reference to step 8, there is a drop down menu that has "Save & queue" with a "Save" option, however, a "Run" button nor a "Save and run" button appears.

![image](https://user-images.githubusercontent.com/13988934/50704213-754a5080-100b-11e9-9f68-6a0410534331.png)

Desired behavior:  Correct terminology in steps and a screenshot could be useful here.

**Comment by andyjlewis** [comment]
Thanks for the heads up. I believe if you enable the New YAML pipeline creation experience preview feature then the instructions might make more sense. I've got a backlog item tracking this concern.

**Comment by thomps23** [comment]
Closing as item exists in backlog to address if topic not updated already.
