### ISSUE TITLE
Unable to set user defined variable value to pre-defined variable.

### ISSUE THREAD

**Issue by veleek** [MicrosoftDocs/vsts-docs#2927]
It doesn't seem possible to set a user-defined variables default value to another pre-defined variable.

For example I have a package suffix which I want to default to the source branch name (e.g. `$(Build.SourceBranchName)`) but still allow it to be overridden at queue time.  Using the designer, setting the value of the User-Defined variable to `$(Build.SourceBranchName)` just causes that exact string to be used for the value instead.

The documentation states: "Almost any place where a pipeline requires a text string or a number, you can use a variable instead of hard-coding a value."  It would be nice if there was a way to easily determine (or have documented somewhere) whether or not the place I'm attempting to use a variable is supported.  I'm not sure if this is going to be a ridiculously long list in either direction so I don't know how feasible that would be.

**Comment by alexhomer1** [comment]
Thank you for your feedback. I will check with the product team to get a list of the other places that variables are not supported, and update the topic based on their response. I will also ask if they intend to allow variables to be used in the way you describe in future releases.
