### ISSUE TITLE
Current Status of Support is INCORRECT

### ISSUE THREAD

**Issue by SamGrantham** [MicrosoftDocs/vsts-docs#293]
The Content Pack is Provided AS-IS you may continue to use this product but it is unsupported, read only, and deprecated.  This is causing incorrect expectations for both PowerBI teams and VSTS teams and need to be updated ASAP.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1c984954-6878-f381-71c1-2752b78759cc
* Version Independent ID: f4e559c8-e58d-ff55-45fa-9715c727efc9
* Content: [Connect Power BI | Microsoft Docs](https://docs.microsoft.com/en-us/vsts/report/powerbi/connect-vso-pbi-vs)
* Content Source: [docs/report/powerbi/connect-vso-pbi-vs.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/report/powerbi/connect-vso-pbi-vs.md)
* Service: **unspecified**
* GitHub Login: @douge
* Microsoft Alias: **kaelli**

**Comment by markble** [comment]
This is no longer listed in the powerBI services. Would be nice to have a sample dashboard.

**Comment by JoshCZimmerman** [comment]
Updates to this documentation are in progress.  Sam is correct, the VSTS Content Pack is deprecated and in-supported.

**Comment by KathrynEE** [comment]
@markble - Thank you for your comment. I'm closing this issue as the content is in the process of being updated.

**Comment by SamGrantham** [comment]
@KathrynEE @JoshCZimmerman 
Hey Guys this is still incorrect and it's been over a month can we double check that it's still in the pipeline?

**Comment by JoshCZimmerman** [comment]
The doc changes are complete, unfortunately they are part of a larger batch of updates for our Power BI story.  They are in PR and we are just waiting for the product deployment to complete.

Josh
