### ISSUE TITLE
Broken link for technical report

### ISSUE THREAD

**Issue by iloabn** [MicrosoftDocs/vsts-docs#2933]
Hello.
Since I wanted to dive deeper I tried accessing the last link in this document which links [here](https://www.microsoft.com/research/wp-content/uploads/2016/02/bosu2015useful.pdf) however, that simply redirects me to the startpage of Microoft research. I've searched the net and found [this](https://www.microsoft.com/en-us/research/wp-content/uploads/2016/02/bosu2015useful.pdf) file with the same filename and just seems like the current URL is missing `en-us` in it. It would be fantastic if the link could be updated to point to a working copy of the report.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2c76f5b3-b88e-94e2-f797-b4bbe7d6bced
* Version Independent ID: 62b06ebc-755f-a9b2-4650-e87785db53e1
* Content: [Boosting your code reviews with useful comments - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/learn/devops-at-microsoft/boosting-code-reviews-useful-comments)
* Content Source: [https://mseng.visualstudio.com/DefaultCollection/TechnicalContent/_git/devops-learn-pr?path=%2fdocs%2fdevops-at-microsoft%2fboosting-code-reviews-useful-comments.md&version=GBlive&_a=contents](https://mseng.visualstudio.com/DefaultCollection/TechnicalContent/_git/devops-learn-pr?path=%2fdocs%2fdevops-at-microsoft%2fboosting-code-reviews-useful-comments.md&version=GBlive&_a=contents)
* Product: **devops**
* Git Login: **samgu**
* Microsoft Alias: **mgreiler**

**Comment by steved0x** [comment]
@iloabn Thank you for letting us know, I am fixing that link right now. That is unusual that it requires the locale in the link, and I am taking a look in that as well. I just merged the fix and this should be live in the next day or two.
