### ISSUE TITLE
Old image being used for build image

### ISSUE THREAD

**Issue by kilasuit** [MicrosoftDocs/vsts-docs#2935]
The image used in the `Explore, download, and deploy your artifacts` section is outdated as it is the older view

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7175ebdc-0bba-7e00-d113-036a5cffe5fa
* Version Independent ID: 149ab9f4-0b7d-97e7-6cf5-1b54fd04c63c
* Content: [Publish and consume build artifacts in builds - Azure Pipelines and TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/build-artifacts?view=vsts&tabs=yaml)
* Content Source: [docs/pipelines/artifacts/build-artifacts.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/artifacts/build-artifacts.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by elbatk** [comment]
Hi @kilasuit , good catch, I'm creating a work item for this now!

**Comment by elbatk** [comment]
Just updated this, you should see it live tomorrow, thank you!
