### ISSUE TITLE
The copy link is pointless

### ISSUE THREAD

**Issue by Walt-D-Cat** [MicrosoftDocs/vsts-docs#2936]
since the code block have hard `cr-lf` copying and pasting this code into a console window does not work.  I suggest either getting rid of the _copy_ link or removing the `cr-lf`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: baa3aa13-7e1e-b327-132b-26fdfd2c0f6e
* Version Independent ID: d62debf7-71cc-2f94-faf2-b83393aa85d9
* Content: [Git permission command - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/tfvc/git-permission-command?view=vsts)
* Content Source: [docs/repos/tfvc/git-permission-command.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/repos/tfvc/git-permission-command.md)
* Product: **devops**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
@Walt-D-Cat I see what you mean. If you paste it in, it will try and execute it as several commands. But if we leave it as one long line, it all scrolls off the page, and that is not useful for folks that are reading to learn about how to use the combinations of parameters. The copy button is automatic for all code blocks except for inline single blocks, so we can't take it out.

I've added a note to clarify in the article. Thank you for the feedback and sorry that you ran into trouble.

**Comment by Walt-D-Cat** [comment]
ty
