### ISSUE TITLE
Can't get root if using container: with standard distro images

### ISSUE THREAD

**Issue by njsmith** [MicrosoftDocs/vsts-docs#2939]
The example here demonstrates using the `container:` feature with the `ubuntu:16.04` image. Which is great! This is exactly what I want to do, though with `ubuntu:18.10` to test my software on the latest versions of everything (in particular openssl 1.1.1).

And the `container:` feature is pretty slick: it goes to a lot of trouble to map things into the container in a clever way, and set up a non-root user to run as, while granting that user `sudo` permissions, etc.

But... the standard images maintained by dockerhub, like `ubuntu:16.04` and `ubuntu:18.10` or `debian:testing`, don't have sudo installed. Which means that if you use them with `container:`, you actually *cannot* get root inside the container. It's impossible.

I guess the `container:` feature is useful for folks who are already maintaining some kind of development-environment images for their own use, but this makes it a complete non-starter for my use case, where I just want to use pipelines normally, but test on a different distro. I guess in theory I could maintain my own image that is just the official `ubuntu:18.10` + `sudo` installed, but there's no way maintaining an image like that is worth it for this.

Instead I've had to give on up using `container:` and am instead writing things like:

```
      - bash: |
          set -ex
          sudo docker run -v $PWD:/t ubuntu:rolling /bin/bash -c "set -ex; cd /t; apt update; apt install -y python3.7-dev python3-virtualenv git build-essential; python3.7 -m virtualenv -p python3.7 venv; source venv/bin/activate; source ci/ci.sh"
```

This is workable, but it's really a shame to lose all the slick `container:` features just because of this.

It would be really nice if the `container:` feature could some make sure it was possible to get root inside the container. For example, there could be a config key to request running as `root`, either for the whole job or just for a specific `script` or `bash` task. Or the container setup phase could mount in a volume containing a suid `sudo` or [`gosu`](https://github.com/tianon/gosu). Or anything, really...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3339a2e0-be29-1363-f588-b231d4472c02
* Version Independent ID: 72dd11a3-704d-d0fd-6dfa-cf49f3352de3
* Content: [Container Jobs in Azure Pipelines and TFS - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/container-phases?view=vsts&tabs=yaml)
* Content Source: [docs/pipelines/process/container-phases.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/container-phases.md)
* Product: **devops**
* GitHub Login: @erickson-doug
* Microsoft Alias: **macoope**

**Comment by vtbassmatt** [comment]
This isn't a doc issue per se. I've moved discussion over to the agent repo, where we can consider adding a feature. https://github.com/Microsoft/azure-pipelines-agent/issues/2043

**Comment by planetmarshall** [comment]
Well, it is a doc issue, in that the documentation doesn't explain that containers that don't install `sudo`, ie most of the useful ones on DockerHub, cannot be used.

The documentation explains that Docker images must satisfy some prerequisites in order to be used, installing `sudo` should be added to this list.
