### ISSUE TITLE
The WORST security maintenance EVER!

### ISSUE THREAD

**Issue by Serjster** [MicrosoftDocs/vsts-docs#294]
I am so frustrated right now.... I have read what seems countless intructions on giving one of my users access to the Work items and no matter what I do, they keep getting TF401232 Work item does not exist (Which it does) or you do not have permission to read it! Why make this soooo painful!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 347e480b-40b9-cba5-2552-3c71e402a651
* Version Independent ID: 26b14743-9d8c-31f4-0c92-994e0186181c
* Content: [Set project-level or collection-level permissions for VSTS & TFS | Microsoft Docs](https://docs.microsoft.com/en-us/vsts/security/set-project-collection-level-permissions)
* Content Source: [docs/security/set-project-collection-level-permissions.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/security/set-project-collection-level-permissions.md)
* Service: **unspecified**
* GitHub Login: @douge
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@Serjster - I'm sorry that you are encountering problems. Is it possible that restrictions have been made to the area path node in which the work item is assigned? Please see this topic for more information: https://docs.microsoft.com/en-us/vsts/security/set-permissions-access-work-tracking?toc=/vsts/work/customize/toc.json&bc=/vsts/work/customize/breadcrumb/toc.json#create-child-nodes-modify-work-items-under-an-area-path.  See also this support article: https://support.microsoft.com/en-us/help/959055/users-in-custom-team-foundation-server-project-level-group-are-unable.

**Comment by Serjster** [comment]
Yes, that ended up being the reason. Would be nice if there was a section at the bottom or something describing these  common issues.

**Comment by KathrynEE** [comment]
@Serjster - I will do as you suggest. Thank you for your comments.
