### ISSUE TITLE
Missing "Mapping file" option in Build Pipelines

### ISSUE THREAD

**Issue by RohanChhipa** [MicrosoftDocs/vsts-docs#2940]
In the documentation, it says that we can specify the mapping.txt file for an Android build, however, this option is not available on the App Center Distribute task. The documentation and the actual App Center Distribute task is inconsistent. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: da6643ac-ea32-1761-a7e9-0f17a3c0b8ee
* Version Independent ID: 2442af0f-3f01-a91c-a98a-29c2f32d35b9
* Content: [App Center Distribute task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/app-center-distribute?view=vsts)
* Content Source: [docs/pipelines/tasks/deploy/app-center-distribute.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/deploy/app-center-distribute.md)
* Product: **devops**
* GitHub Login: @erickson-doug
* Microsoft Alias: **dastahel**

**Comment by RohanChhipa** [comment]
Any news on this?

**Comment by patniko** [comment]
Mentioning @dimazaid and @jwargo who own distribution and docs in App Center respectively.

**Comment by dboyjq** [comment]
any update on this. AppCenter has much less VSTS integration support and this is just one of reason why we don't want to migrate to it

**Comment by jwargo** [comment]
@botatoes or @dimazaid can we do a doc update for this?

**Comment by botatoes** [comment]
@jwargo created a pr to the vsts docs, for for it to get approved.

**Comment by jwargo** [comment]
@botatoes thanks!

**Comment by jwargo** [comment]
@patniko can you close this?

**Comment by patniko** [comment]
Not a collaborator on this repo @jwargo. @RohanChhipa or one of the repo collaborators will have to do it.
