### ISSUE TITLE
DoD not available in Scrum projects? 

### ISSUE THREAD

**Issue by Sjoerd77** [MicrosoftDocs/vsts-docs#2941]
In our Scrum project in Azure DevOps, the "Definition of Done" section is not available under Settings. Is there a way to add this? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 934d334d-3af9-2e60-22d2-b0291ff0a344
* Version Independent ID: 0c18bb6f-5902-367d-d6b0-8f01d042e6a1
* Content: [Definition of Done on the Kanban board - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/boards/definition-of-done?view=vsts&tabs=new-nav)
* Content Source: [docs/boards/boards/definition-of-done.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/boards/boards/definition-of-done.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@Sjoerd77 - Thank you for your inquiry. The Definition of Done is enabled and configured for each interior column (all columns except the first and last). If you go to the Columns tab and choose an interior column and don't see the Definition of Done setting as shown in the following image, then please report the problem in our [Developer Community portal](https://developercommunity.visualstudio.com/spaces/21/index.html).

![image](https://user-images.githubusercontent.com/10856840/50798602-c79aa400-128d-11e9-8707-ffbb9b9a5c56.png)
