### ISSUE TITLE
Remove hardcoded values accountName, projectName and repositoryName

### ISSUE THREAD

**Issue by fabricebauer** [MicrosoftDocs/vsts-docs#2945]
Hello, 
I wanted to get rid of the accountName, projectName and repositoryName hardcoding, as they should come from the initial function's input. This makes the code more generic and reusable.
I tried using jObject.resource.url + "/statuses?api-version=4.1-preview.1" to build the target URL and this works well, so wanted to share.
Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 915c7aa9-0969-912b-bbc4-a2b0bf9b1533
* Version Independent ID: 6a97a5e8-8397-be98-5528-70d20e8fbed8
* Content: [Use Azure Functions to create custom branch policies - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/create-pr-status-server-with-azure-functions?view=vsts)
* Content Source: [docs/repos/git/create-pr-status-server-with-azure-functions.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/repos/git/create-pr-status-server-with-azure-functions.md)
* Product: **devops**
* GitHub Login: @steved0x
* Microsoft Alias: **yohasna**

**Comment by steved0x** [comment]
@fabricebauer Thank you for your feedback, I have passed it along tot he Azure Repos team.
