### ISSUE TITLE
Example for byEnvVar versioning doesn't work

### ISSUE THREAD

**Issue by CoolDadTx** [MicrosoftDocs/vsts-docs#2950]
For byEnvVar versioning scheme it says "whatever env var (e.g. $(MyVersion)) but trying to put $(MyVersion) doesn't work for this task. You have to specify just the env-var name instead. 

Putting YAML examples in for the less-clear parameters would help people who keep going through iterations trying to get the syntax right.

```yaml
versioningScheme: byEnvVar
versionEnvVar: MyVersion
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0fa37a3f-6551-16ad-e164-a4ac522cdaab
* Version Independent ID: a3fd6935-2b99-92ef-4eb3-3249fca01f8a
* Content: [NuGet restore, pack, and publish task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/package/nuget?view=vsts)
* Content Source: [docs/pipelines/tasks/package/nuget.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/package/nuget.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by elbatk** [comment]
Thank you, @CoolDadTx , does '$(MyVersion)` work (with single quotes)? Just want to get the correct syntax documented!

**Comment by elbatk** [comment]
Putting in a PR to fix this now!
