### ISSUE TITLE
NSG Source Service Tag

### ISSUE THREAD

**Issue by mstearman** [MicrosoftDocs/vsts-docs#2951]
What nsg source service tag should I set to limit port 5986 to only the pipeline agent?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 622daa35-c6a1-dac3-17ee-3f9308fc60cd
* Version Independent ID: 2c28a59b-8ef5-d7ab-46a6-58748ec552f5
* Content: [Azure File Copy task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-file-copy?view=vsts)
* Content Source: [docs/pipelines/tasks/deploy/azure-file-copy.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/deploy/azure-file-copy.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by RoopeshNair** [comment]
If you are using Hosted agents, then we rely on Azure Global network, [IP ranges vary over time](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=vsts&tabs=yaml#agent-ip-ranges). You can try with `AzureCloud` or `Internet`. 

Refer to [service tags](https://docs.microsoft.com/en-us/azure/virtual-network/security-overview#service-tags) for other options
