### ISSUE TITLE
There is no CLI for AngularJS

### ISSUE THREAD

**Issue by bevans-allmeds** [MicrosoftDocs/vsts-docs#2952]
I suspect the intention here in the documentation is to refer to the CLI for Angular. Admittedly, it is confusing, but AngularJS refers to version 1.x of Angular, for which there is no CLI. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c99686eb-6c78-0336-1ec3-802a53c9868d
* Version Independent ID: 6eaf1acb-24d4-5bb7-3935-17abe7e59dd9
* Content: [Build, test, and deploy JavaScript and Node.js apps - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/languages/javascript?view=vsts&tabs=designer#angularjs)
* Content Source: [docs/pipelines/languages/javascript.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/languages/javascript.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by andyjlewis** [comment]
@bevans-allmeds thank you for reporting this issue, which is now fixed.
