### ISSUE TITLE
Is the domain changed?

### ISSUE THREAD

**Issue by GongT** [MicrosoftDocs/vsts-docs#2954]
I comes from link on azure artifacts "Connect to feed" window.

There is many `pkgs.dev.azure.com` on the page. I'm new to azure devops, but I think these links are broken...

Isn't it `[user].pkgs.visualstudio.com`?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 484077fa-696c-63e1-a4ba-f2680d076bfd
* Version Independent ID: aa0f98e6-6b82-a848-de65-0c39af8f8650
* Content: [Use npm scopes for private packages](https://docs.microsoft.com/en-us/azure/devops/artifacts/npm/scopes?view=vsts&tabs=new-nav%2Cwindows)
* Content Source: [docs/artifacts/npm/scopes.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/artifacts/npm/scopes.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by elbatk** [comment]
Hi @GongT , when we transitioned to dev.azure.com, our protocol endpoint for Azure Artifacts changed as well. Namely, it went from `<org>.pkgs.visualstudio.com` to `pkgs.dev.azure.com/<org>`. If you are seeing the old one, you should go to `https://dev.azure.com/<org>/_settings/organizationOverview` and toggle the "Use the new URL" option. I hope this helps! Closing for now, but if you have more questions, feel free to reach out.

**Comment by GongT** [comment]
Thanks, that link works for me.
