### ISSUE TITLE
kubectlVersion is required

### ISSUE THREAD

**Issue by Huffers** [MicrosoftDocs/vsts-docs#2956]
This page says kubectlVersion is optional, but actually you need to set that value or else you'll get the error "versionSpec parameter is required".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6730d493-93eb-12c0-eae3-a60f9462ab18
* Version Independent ID: 5b6ce957-8fa9-43d5-dc1a-129ddd553910
* Content: [Helm Tool Installer task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/helm-installer?view=vsts)
* Content Source: [docs/pipelines/tasks/tool/helm-installer.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/tool/helm-installer.md)
* Product: **devops**
* GitHub Login: @erickson-doug
* Microsoft Alias: **dastahel**

**Comment by shashankbarsin** [comment]
@Huffers we were not able to repro this issue. I used the following pipeline and it ran successfully without any errors - 

```
steps:
- task: HelmInstaller@0
  displayName: 'Install Helm'
  inputs:
    helmVersion: 2.9.1
```

If installKubectl and kubectlVersion are not specified under inputs, they take their default values.
Please let me know if the above snippet works for you. If not, please provide details on the agent type and if possible a screenshot or logs of the error you are running into. This will help us in debugging the issue
