### ISSUE TITLE
Cannot Configure Features in Azure DevOps Server 2019 RC1

### ISSUE THREAD

**Issue by Beakster** [MicrosoftDocs/vsts-docs#2958]
It seems impossible to run configure features in Azure DevOps Server 2019 RC1.  
When I try to open a backlog for a project upgraded from 2010 via 2015 I get the following message:
"Configuration required
This feature cannot be used until you configure it for this team project.
Configure feature"

Clicking on Configure features links to https://myurl.com/Technology/Websites/_settings/enableFeatures which then redirects to https://myurl.com/Technology/Websites/_settings/projectOverview#_a=enableFeatures

There is no Configure features link on this page as described above, despite the fact I am an Admin.  This worked in TFS2018, how can I use it in 2019?  This is a big impediment for me as we have migrated to 2019 but cannot use Backlogs on our existing projects.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 42254a33-0443-c538-cb90-d32aef2569d8
* Version Independent ID: ba9a9e4f-4241-26ab-35de-1ce32168fab5
* Content: [Configure features after an upgrade](https://docs.microsoft.com/en-us/azure/devops/reference/configure-features-after-upgrade?view=azdevserver-2019)
* Content Source: [docs/reference/configure-features-after-upgrade.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/reference/configure-features-after-upgrade.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@Beakster - Apologies for the trouble you're having. I suggest you contact [Support](https://developercommunity.visualstudio.com/content/problem/post.html?space=21) to help with this issue.

**Comment by Beakster** [comment]
> @Beakster - Apologies for the trouble you're having. I suggest you contact [Support](https://developercommunity.visualstudio.com/content/problem/post.html?space=21) to help with this issue.

This has been raised with support: https://developercommunity.visualstudio.com/content/problem/421341/feature-enablement-doesnt-work-in-azure-devops-ser.html

However, that doesn't change the fact that the documentation doesn't reflect the application.  Even though Azure DevOps Sever 2019 is selected at the top left, the screenshot shown is from TFS 2015.  Now that we have the new navigation view this is completely inaccurate.  This page needs to be updated.

**Comment by steji113** [comment]
@KathrynEE checking back in to see if the documentation for this page can be updated?
