### ISSUE TITLE
my best greeting to microsoft Azure team

### ISSUE THREAD

**Issue by bahr2** [MicrosoftDocs/vsts-docs#2959]
I'm more than grateful about Microsoft team teachers and engineers who give me this amazing opportunity and being able to build my first app.you guys are definitely an inspiration .iwant to explore more from your modern technology as a new developer very exciting to learn more from you.thanks god bless you all

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f2fe2521-cc98-8946-89b4-5a8199a6d898
* Version Independent ID: dbc4b6cf-ddb1-ac16-c634-eaf15072e111
* Content: [Library for Azure Pipelines and Team Foundation Server - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/library/index?view=vsts#security)
* Content Source: [docs/pipelines/library/index.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/library/index.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by steved0x** [comment]
@bahr2 Thank you for your feedback. I am sending this to the author and also sharing it with our team.

**Comment by alexhomer1** [comment]
Thank you for your comments. I have passed them on to the team.
