### ISSUE TITLE
Please provide an overview of the different process templates and their versions

### ISSUE THREAD

**Issue by oleschri** [MicrosoftDocs/vsts-docs#296]
Right now there are multiple versions of "MSF for Agile Software Development" inside TFS and their naming/versioning is inconsistent. It is not intuitive to find out which one is the most recent version.

MSF for Agile Software Development - v4.0
MSF for Agile Software Development - v4.2
MSF for Agile Software Development 2013.2
MSF for Agile Software Development 2013.5
MSF for Agile Software Development 6.2

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d5d33f3b-9390-f4f6-58ac-ebc45631cc80
* Version Independent ID: eddeda4c-b139-eb81-c34e-67a931689f03
* Content: [Agile process template for VSTS & TFS | Microsoft Docs](https://docs.microsoft.com/en-us/vsts/work/work-items/guidance/agile-process?toc=/vsts/work/work-items/toc.json&bc=/vsts/work/breadcrumb/toc.json)
* Content Source: [docs/work/work-items/guidance/agile-process.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/work/work-items/guidance/agile-process.md)
* Service: **unspecified**
* GitHub Login: @douge
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
I have done as you suggested. The updates should appear later today.

**Comment by oleschri** [comment]
Sadly the markup code for the table looks broken and does not render as a table.
The |-------------|-----------------------| is missing one additional | bar. :/
Same issue is in on the "Scrum process guidance" and "CMMI process guidance" pages.

**Comment by KathrynEE** [comment]
@oleschri - Yes, made a format error. This is now fixed.
