### ISSUE TITLE
Can you provide an example of how to redraw the board so as to create calculated fields on the cards

### ISSUE THREAD

**Issue by KeroKowboy** [MicrosoftDocs/vsts-docs#2962]
Thank you for your feedback!

The issues in this repo are for documentation feedback.

If you are submitting your documentation feedback issue directly through GitHub, please provide the URL of the article so we can route the feedback to the correct author.

Please report Azure DevOps or TFS software bugs, feedback, or questions in the [Azure DevOps Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html).

**Comment by KathrynEE** [comment]
@KeroKowboy - The feature you are looking for is not supported. You may find something in the [Marketplace](https://marketplace.visualstudio.com/search?target=AzureDevOps&category=Azure%20Boards&sortBy=Downloads) that would help or you could create your own extension.
