### ISSUE TITLE
 --collect “Code coverage” does not work (Issue Identified)

### ISSUE THREAD

**Issue by ikemtz** [MicrosoftDocs/vsts-docs#2963]
Hello all!  I spent HOURS on the following error message:

MSBUILD : error MSB1008: Only one project can be specified.
Switch: coverage”

The core of the issue is a simple copy-paste user error.  If you look at the additional information popup associated with the code coverage checkbox on the dotnet test task, it says the following:

-------------------------------------------------------------------------------------------------------------------------------------------
Code coverage can be collected by adding --collect “Code coverage” option to the command line arguments. This is currently only available on the Windows platform.
-------------------------------------------------------------------------------------------------------------------------------------------

Here in lies the problem.  If you do a simple copy/paste, you'll erroneously copy the double quote left and right characters.  To fix the problem be sure to use double quotes (0x22) --collect "Code coverage".

I hope this saves the next person some time.
-Isaac Martinez

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d227a6f2-a94b-1c05-57e4-b63d42e2b9e5
* Version Independent ID: d063e189-d0fd-4ca3-c108-a0bd2ae49d22
* Content: [.NET Core CLI task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/dotnet-core-cli?view=vsts)
* Content Source: [docs/pipelines/tasks/build/dotnet-core-cli.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/build/dotnet-core-cli.md)
* Product: **devops**
* GitHub Login: @erickson-doug
* Microsoft Alias: **dastahel**

**Comment by steved0x** [comment]
@ikemtz Thank you for letting us know, and sorry that you ran into trouble. I took a look at the associated article as I was going to remove the smart quotes and change them with regular quotes, but I didn't see that in the topic. To fix this, do we need to make a documentation change, or do we need to make a fix to text on one of the screens in the Azure Pipelines product?

**Comment by steved0x** [comment]
@ikemtz I've sent this to them, thanks for letting us know.

**Comment by PBoraMSFT** [comment]
Thank you for reporting this @ikemtz - I assume you are referring to the tooltip in the dot net task in the pipeline (image below). Will get that fixed.

![image](https://user-images.githubusercontent.com/23308203/53152757-7267e700-35dc-11e9-9b5d-339d755b5865.png)

If you have observed this anywhere else, please do let me know.

**Comment by ikemtz** [comment]
Yes, that's exactly where I found it.  If I run into anything I'll let you know.
