### ISSUE TITLE
How to create a non-public extension

### ISSUE THREAD

**Issue by trajano** [MicrosoftDocs/vsts-docs#2964]
I want to create an extension for my own team which is a fork of an existing one but tweaks it so that it works in a way I wanted.  However, I don't really want to publish it publicly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 14955ee9-29f2-46fe-3a8d-a42666f53ffc
* Version Independent ID: 5d417cd0-a671-ee30-8fca-5f8b0addd328
* Content: [Develop a web extension for Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/extend/get-started/node?view=vsts)
* Content Source: [docs/extend/get-started/node.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/extend/get-started/node.md)
* Product: **devops**
* GitHub Login: @willsmythe
* Microsoft Alias: **wismythe**

**Comment by elbatk** [comment]
Hi @trajano , all extensions are private by default, see this section on sharing/testing:
https://docs.microsoft.com/en-us/azure/devops/extend/get-started/node?view=vsts#install-your-extension

See this bit for more information on private flags and making your extension public:
https://docs.microsoft.com/en-us/azure/devops/extend/publish/publicize?view=vsts

Hope that helps!
