### ISSUE TITLE
Documentation not up to date

### ISSUE THREAD

**Issue by wima75** [MicrosoftDocs/vsts-docs#2965]
Why openNewWindow and navigate are not listed here?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 407ce9c3-9426-ed32-fe60-d6e35afdf766
* Version Independent ID: 884b6bf4-dc75-2d22-1505-f0fc2d169fc9
* Content: [VSS/SDK/Services/Navigation HostNavigationService API](https://docs.microsoft.com/en-us/azure/devops/extend/reference/client/api/vss/sdk/services/navigation/hostnavigationservice?view=vsts#method_updateHistoryEntry)
* Content Source: [docs/extend/reference/client/api/VSS/SDK/Services/Navigation/HostNavigationService.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/extend/reference/client/api/VSS/SDK/Services/Navigation/HostNavigationService.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by elbatk** [comment]
Hi @wima75 , thank you for your feedback. These VSS SDK Services are not actively maintained, as it would be really expensive. What would be a great help to us is if you find something that should be documented, to go ahead and grab a branch from master and submit a PR with the change, I'll be happy to review!

**Comment by wima75** [comment]
I made a PullRequest: https://github.com/MicrosoftDocs/vsts-docs/pull/3115
Happy reviewing ;-)

**Comment by elbatk** [comment]
@wima75 you have no idea how much it helps me to get PRs :) thank you! Merged!
