### ISSUE TITLE
Dashboard Edit as Stakeholder

### ISSUE THREAD

**Issue by seapeter** [MicrosoftDocs/vsts-docs#2968]
View, Edit and Manage dashboards is selected, the user is set as a member of the team. However, they are only a stakeholder.  They still do not have edit permissions for the dashboard.  Is this by design?  Above it states that all team members have permissions to edit dashboard if the edit permission is set.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b3a8994c-97ff-1347-d621-66ae5e9c11ce
* Version Independent ID: 7e558469-28b6-bade-4ff0-4e2bf9a24e85
* Content: [Set dashboard permissions for team members - Azure DevOps & TFS](https://docs.microsoft.com/en-us/azure/devops/report/dashboards/dashboard-permissions?view=tfs-2017&tabs=new-nav)
* Content Source: [docs/report/dashboards/dashboard-permissions.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/report/dashboards/dashboard-permissions.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@seapeter - Thank you for your inquiry. Stakeholders only have view access to dashboards. Even if added as a team member, they aren't able to add, edit, or manage permissions for dashboards. I'll update the article accordingly.
