### ISSUE TITLE
Source code for built-in widgets

### ISSUE THREAD

**Issue by tstahnke2** [MicrosoftDocs/vsts-docs#2971]
Good afternoon, we are looking into customizing the Release Pipeline Overview widget for enabling single click deployments. Is there source code for the built-in widgets so we can customize functionality?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 514ba817-c404-380b-6c8d-67ea982e9a22
* Version Independent ID: 915a8f30-5192-8b0a-d6a4-43fe7a606ff6
* Content: [Catalog of widgets you can add to a dashboard - Azure DevOps & TFS](https://docs.microsoft.com/en-us/azure/devops/report/dashboards/widget-catalog?view=vsts#related-notes)
* Content Source: [docs/report/dashboards/widget-catalog.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/report/dashboards/widget-catalog.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by tstahnke2** [comment]
I was able to find the ReleasePipeline/Scripts/ in the Azure DevOps Server 2019 preview; so I'm guessing that'll have to do for now :)

**Comment by steved0x** [comment]
@tstahnke2 If that source code you found doesn't work for you, you can post an issue here and they may be able to help:

https://developercommunity.visualstudio.com/spaces/21/index.html
