### ISSUE TITLE
How to display the output using ITestOutputHelper from XUnit on VSTS?

### ISSUE THREAD

**Issue by ranouf** [MicrosoftDocs/vsts-docs#2972]
Hi,

I created an Issue on XUnit Github (Source: https://github.com/xunit/xunit/issues/1879) which adviced me to contact VSTS directly.

______________________________________________________

Hi,

Packages used:
```
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="2.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.TestHost" Version="2.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="xunit" Version="2.4.1" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.4.1">
```

Code:
```
ITestOutputHelper output
output.WriteLine("Test");
```

On VS I am able to see the output:
![image](https://user-images.githubusercontent.com/1764519/50922657-09a42100-1419-11e9-9a0d-99733a3ca9a5.png)

Here is the build definition:
![image](https://user-images.githubusercontent.com/1764519/50923150-3f95d500-141a-11e9-9e32-1e228ec7ce36.png)

When I run the Test in VSTS, I m supposed to see the output in the attchment section, but it s empty.
![image](https://user-images.githubusercontent.com/1764519/50922853-78817a00-1419-11e9-9261-b3a77e9ee414.png)

How to configure the XUnit Project to get the output in VSTS?

Thanks

**Comment by steved0x** [comment]
@ranouf The issues in this repo are for documentation feedback, and for product issues (including questions like yours) you can file an issue here:

https://developercommunity.visualstudio.com/spaces/21/index.html

Thank you.

**Comment by ranouf** [comment]
Thanks for your reply, I will contact there.
