### ISSUE TITLE
Navigation

### ISSUE THREAD

**Issue by steveaf** [MicrosoftDocs/vsts-docs#2975]
On step 2, my portal.azure.com looks nothing like the screenshots and description:
"In the Microsoft Azure portal, at the bottom of the navigation pane, click NEW. "
  Has the portal page changed since these instructions?  (I see "Create a Resource", "New Dashboard", or I can go to "All Services" and find storage resources.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8cd475cc-3510-5c4b-29e0-698eab618041
* Version Independent ID: bf3fff29-d364-b8ee-78ea-620363067c0e
* Content: [Azure Storage with Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/service-hooks/services/azure-storage?view=vsts)
* Content Source: [docs/service-hooks/services/azure-storage.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/service-hooks/services/azure-storage.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by elbatk** [comment]
Hi @steveaf ! Thank you for your feedback. All of these Service Hooks docs are getting some love in the next couple of weeks. Check back and hopefully you'll see something better! As for now, if you're having an issue with the product, head over to the Developer Community at https://developercommunity.visualstudio.com/spaces/21/index.html for help!
