### ISSUE TITLE
Plugin Name Incorrect

### ISSUE THREAD

**Issue by KevinZinn** [MicrosoftDocs/vsts-docs#2976]
Step 2 tells you to search for "Azure Devops Services", but there is no plugin with this name. The correct plugin, which the link in step 3 points to, is named "Visual Studio Team Services"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3378875f-5f9d-8992-a01d-8ea87e019861
* Version Independent ID: b098532e-61ee-0906-8b50-9108e50e2732
* Content: [Get the Android Studio Azure DevOps Services plug-in](https://docs.microsoft.com/en-us/azure/devops/java/download-android-studio-plug-in?view=vsts)
* Content Source: [docs/java/download-android-studio-plug-in.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/java/download-android-studio-plug-in.md)
* Product: **devops**
* GitHub Login: @erickson-doug
* Microsoft Alias: **douge**

**Comment by steved0x** [comment]
@KevinZinn Sorry that you ran into trouble. Some things that were renamed when VSTS became Azure DevOps Services haven't quite caught up. I will update the article. Thanks for letting us know.
