### ISSUE TITLE
Dead link for "How-to Guides/Test/FAQs for testing"

### ISSUE THREAD

**Issue by andreas-wilm** [MicrosoftDocs/vsts-docs#2979]
Hi,

The link for "How-to Guides/Test/FAQs for testing" points to https://docs.microsoft.com/en-us/azure/devops/pipelines/test/reference-qa?view=vsts, which is dead (and gets redirected to https://docs.microsoft.com/en-gb/azure/devops/pipelines/index?view=vsts instead)

Andreas

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 03256f96-b530-9a49-3fce-3702e5f96c6b
* Version Independent ID: 344a3b48-52b2-3424-85da-55c905de0fa1
* Content: [Glossary of testing terms - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/test/test-glossary?view=vsts)
* Content Source: [docs/pipelines/test/test-glossary.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/test/test-glossary.md)
* Product: **devops**
* GitHub Login: @vinojos
* Microsoft Alias: **vinojos**

**Comment by steved0x** [comment]
@andreas-wilm Can you paste in a screenshot of the bad link with it highlighted, I think I am looking in the wrong place and I don't see it.

**Comment by andreas-wilm** [comment]
Hey @steved0x, can't find it either. Looks like this was removed in ed20c5826
