### ISSUE TITLE
Need the Odata version

### ISSUE THREAD

**Issue by steveaf** [MicrosoftDocs/vsts-docs#2981]
The URL provided has {version} included yet no comment of how to find this, where it is assigned, or what a good guess is.  I guessed /v4  , /v4.0, and /4  all of which return a 404 error.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4a432cd5-b2aa-b274-a17f-80c13a45e2ae
* Version Independent ID: 71a68a40-31ae-e09c-fa89-b68a4428e4bb
* Content: [Query work tracking data using OData - Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/report/extend-analytics/wit-analytics?view=vsts)
* Content Source: [docs/report/extend-analytics/wit-analytics.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/report/extend-analytics/wit-analytics.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by erramire** [comment]
Hello v1.0 and v1.0-preview version worked for me, actually i found this https://docs.microsoft.com/en-us/azure/devops/report/extend-analytics/odata-api-version?view=vsts

**Comment by KathrynEE** [comment]
@steveaf - Thank you for the feedback. Please use v1.0 for now. I will update the content so that it more apparent what version is supported.
