### ISSUE TITLE
IaaC Template

### ISSUE THREAD

**Issue by vmaruhpe** [MicrosoftDocs/vsts-docs#2982]
Is there a template/walkthrough to deploy Infrastructure as a Code ? Eg: What is the effective way to Deploy PS scripts or Terraform Automation to deploy Infrastructure on Azure.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 598465e1-85d4-4961-b8b6-902d6026c5e3
* Version Independent ID: 5ef1308a-3aeb-fcc4-dec7-6f10785612a3
* Content: [Release artifacts and artifact sources - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/artifacts?view=vsts)
* Content Source: [docs/pipelines/release/artifacts.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/release/artifacts.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment]
You can use this task: https://docs.microsoft.com/azure/devops/pipelines/tasks/deploy/powershell-on-target-machines to execute PowerShell scripts on your target machines. Other tasks that may be useful are listed at https://docs.microsoft.com/azure/devops/pipelines/tasks/. Various techniques for deployments that use scripting include https://docs.microsoft.com/azure/devops/pipelines/apps/cd/deploy-linuxvm-deploygroups and https://docs.microsoft.com/azure/devops/pipelines/apps/cd/deploy-aks.

**Comment by vmaruhpe** [comment]
Thank you Alex, appreciate quick response. Is there a task to deploy to Azure Functions as well? Essentially invoking Azure Functions with PowerShell IaC code, that way the overhead of having a VM can be avoided. Workflow will be to pick up PowerShell Script form Azure DevOps repository, push it to Azure Functions and run the function to create a desired resources(s). Later a workflow app can be created to create a runbook. I am already experimenting using Functions Task but if there is an existing how-to that would be great.

Thanks,
Maruthi

**Comment by alexhomer1** [comment]
As far as I'm aware, the only Azure Functions docs are at https://docs.microsoft.com/azure/azure-functions/functions-overview.
