### ISSUE TITLE
Inactivate or Disable Project instead of Deleting

### ISSUE THREAD

**Issue by mdsundquist** [MicrosoftDocs/vsts-docs#2983]
Is there no way to take a project offline (i.e. disable it)? If there isn't, what is the purpose of the Status column?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a614791-0c5d-4373-3194-11695e40e1d1
* Version Independent ID: 737e5a3b-d7be-9d36-7b5a-638976406d74
* Content: [Delete, remove project - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/projects/delete-project?view=vsts&tabs=new-nav)
* Content Source: [docs/organizations/projects/delete-project.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/projects/delete-project.md)
* Product: **devops**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @mdsundquist, 
The only way to "disable" a project is to delete it. The project status is a translation of the project state. If a project is in any state other than well formed, then the status will appear to be offline. A status is offline when an error has occurred in the project creation job and the project is in a half created state. 
I'm going to close this issue, but please let me know if you need further clarification. Thank you!
