### ISSUE TITLE
Will the MS Project integration continue to be supported in the Azure DevOps free version?

### ISSUE THREAD

**Issue by LaurieHeer** [MicrosoftDocs/vsts-docs#2984]
This blog was written in November 2018 and indicated that Project support is not available in 2019. Am I misunderstanding your note? Will this work with Azure DevOps free version?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4f6edd47-46d7-ab0d-db47-d73bc45d6b43
* Version Independent ID: 6ac2ae49-0bd0-2c28-fc87-7f034dd96443
* Content: [Create your backlog and tasks using Project - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/backlogs/office/create-your-backlog-tasks-using-project?view=vsts&tabs=office-365)
* Content Source: [docs/boards/backlogs/office/create-your-backlog-tasks-using-project.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/boards/backlogs/office/create-your-backlog-tasks-using-project.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@LaurieHeer - The TFS Office Integration plug-in will continue to be available, however, the vNext version yet to be released won't  support connection between TFS and Office Project or PowerPoint. The [current version](https://go.microsoft.com/fwlink/?LinkId=832491&clcid=0x409) available from the download page will continue to work with the Azure DevOps and TFS 2017 and later on-prem versions.

**Comment by weirbt2k** [comment]
@KathrynEE

Hi, I know you've already closed this but can you clarify your statement that the vNext version won't support connection between TFS and Office Project? When you say TFS, do you also mean Azure DevOps? 

I'm just starting to look at how to use the Office Integration plug-in so I can connect MS Project Pro to an Azure DevOps team (we're enterprise customers, not using any free version). Unfortunate I can't get to work right now and looking for a solution I came across this thread. 

I'm not writing you to help me with my issue, my concern is that this vNext version won't support integration between Project Pro and our Azure DevOps boards as outlined in this article.

https://docs.microsoft.com/en-us/azure/devops/boards/backlogs/office/create-your-backlog-tasks-using-project?view=tfs-2018&tabs=office-365

Can you confirm if this vNext version will allow for integration between MS Project Pro and Azure DevOps or if we'll need to continue to use the existing plug-in?

Thanks
