### ISSUE TITLE
Specify VM type for Azure Pipelines

### ISSUE THREAD

**Issue by jedbrown** [MicrosoftDocs/vsts-docs#2985]
It would be extremely useful (and many would pay) to support specifying VM type (e.g., NCv2, etc.) for Azure Pipelines. Many projects, especially in the machine learning and scientific computing space, include code that needs to be tested on specialized hardware such as GPUs or CPUs with specific instruction sets (AVX-512). Azure supports such hardware, but it is not accessible via Pipelines, thus inhibiting CI and/or pushing users to build complex one-off solutions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5552e8c4-b0c2-f3ff-c69a-607166afb611
* Version Independent ID: 8e73c13c-9b2b-0eac-45ec-4bd3a8d01bb1
* Content: [Create a multi-platform pipeline - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/get-started-multiplatform?view=vsts)
* Content Source: [docs/pipelines/get-started-multiplatform.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/get-started-multiplatform.md)
* Product: **devops**
* GitHub Login: @vtbassmatt
* Microsoft Alias: **alewis**

**Comment by vtbassmatt** [comment]
Agreed, and it's something we're investigating right now. I'm going to close this issue since it's not a documentation bug. You can see the spec I'm working on over [here](https://github.com/Microsoft/azure-pipelines-agent/blob/proposals/byos-refresh/docs/design/byos.md), though.

**Comment by jedbrown** [comment]
Thanks. Is there an issue to watch for progress on that feature?

**Comment by vtbassmatt** [comment]
Just the doc for now. I'll go ahead and open a PR so you can add your thoughts: https://github.com/Microsoft/azure-pipelines-agent/pull/2053
