### ISSUE TITLE
Stuck indefinitely at Login-AzureRmAccount

### ISSUE THREAD

**Issue by vmaruhpe** [MicrosoftDocs/vsts-docs#2986]
Tried to execute a sample PS Script to deploy a VM on Azure using Hosted and Hosted VS2017 Agent Pools. All the bootstrap steps (Fetching the files from DevOps repo) succeed. However, the first step of the script, that is Logging into Target Azure  Subscription using Login-AzureRmAccount gets stuck indefinitely or times out. Validated correct subscription Id etc. It does not even throw an error message.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fb215324-b1a0-93b5-5022-4bcc7da93bb7
* Version Independent ID: 9eb2977b-ac34-9d53-670e-04fa027bc8e4
* Content: [Azure PowerShell task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-powershell?view=vsts)
* Content Source: [docs/pipelines/tasks/deploy/azure-powershell.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/deploy/azure-powershell.md)
* Product: **devops**
* GitHub Login: @erickson-doug
* Microsoft Alias: **dastahel**

**Comment by steved0x** [comment]
@vmaruhpe Sorry that you ran into trouble with this. The GitHub issues in this repo are for documentation feedback. For product issues, please file an issue here:

https://developercommunity.visualstudio.com/spaces/21/index.html

Thank you.

**Comment by vmaruhpe** [comment]
Thank you for the link.

Thanks,
Maruthi
