### ISSUE TITLE
Is there any documentation for building extension on premise for TFS2018

### ISSUE THREAD

**Issue by dariusneo** [MicrosoftDocs/vsts-docs#2994]
Hi Is there any documentation for building extension on premise for TFS2018?

**Comment by elbatk** [comment]
Have you checked out our Extend documentation? https://docs.microsoft.com/en-us/azure/devops/extend/get-started/node?view=tfs-2018

**Comment by dariusneo** [comment]
Thank you! i have managed to build my first extension for TFS2018. in TFS2013 i used to use process editor to customise the look and feel of the workitem. Is there any tools i can use for TFS2018 workitem?

**Comment by elbatk** [comment]
Awesome! I'm not aware of anything like that existing for TFS 2018 /:  There is this for TFS 2017 (an extension): https://marketplace.visualstudio.com/items?itemName=KarthikBalasubramanianMSFT.TFSProcessTemplateEditor

And then this question was asked on StackOverflow for 2018:
https://stackoverflow.com/questions/52429121/tfs-2018-process-template-editor-gone

Hope this helps! Closing this for now, but I'm excited that you've already built your first one so fast!
