### ISSUE TITLE
Restrict modification of work items based on a user or group not implemented

### ISSUE THREAD

**Issue by renezersi** [MicrosoftDocs/vsts-docs#2997]
Hi there 
this Section: Restrict modification of work items based on a user or group 

with this content: 

For On-premises XML process model, you can customize work item types to support these restriction requests: 
Restrict who can create or modify a work item 
Restrict who can create specific work item types, such as Epics or Features 
You achieve this by adding a rule to the work item type, usually within the WORKFLOW section. To learn more, see Add a rule to a work item type, Apply or ignore rules based on user or group. 

Is not working, at least there is nothing that show that I really can restrict a certain User or Group to view and edit the Epic Work Item Type. 
So I think this part of the Article is just not true.
But if it is true How can I do it, what would I have to change in the Process XML to achieve this ?

Rules can be added on Field level but not on WorkItem Level?

thanks in advance 
Rene

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b9a3085-d952-f4ba-e7c5-88e8ea7b3b29
* Version Independent ID: fb29b46c-3b07-ec11-f731-78c1371eef33
* Content: [Grant or restrict access to select features - Azure DevOps & TFS](https://docs.microsoft.com/en-us/azure/devops/organizations/security/restrict-access?view=azdevserver-2019#restrict-modification-of-work-items-based-on-a-user-or-group)
* Content Source: [docs/organizations/security/restrict-access.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/security/restrict-access.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@renezersi - You can't restrict users from viewing the Epic work item types; you can only restrict a user or user group from viewing work item types under a specific Area Path as described [here](https://docs.microsoft.com/en-us/azure/devops/organizations/security/set-permissions-access-work-tracking?toc=%2Fazure%2Fdevops%2Forganizations%2Fsecurity%2Ftoc.json&bc=%2Fazure%2Fdevops%2Forganizations%2Fsecurity%2Fbreadcrumb%2Ftoc.json&view=vsts&tabs=new-nav#create-child-nodes-modify-work-items-under-an-area-path). 

For On-premises XML - to restrict users ability to create or edit an Epic work item type, you would add a field rule within the WORKFLOW section, either under the STATES or TRANSISTIONS sections. 

This code snippet restricts the Assigned To field to the Epic Authors security group added to the project. 
 
```
<STATE value="New">  
      <FIELDS>  
. . .  
      <FIELD refname="System.AssignedTo">  
         <ALLOWEDVALUES expanditems="true">
  		<LISTITEM value="[ProjectName]\Epic Authors"/>
	</ALLOWEDVALUES>
      </FIELD>  
      </FIELDS>  
</STATE>  
```
 

Here is another example where the ability to transition a work item from the Resolved to the Completed state is restricted to all project testers, except for new testers who have just joined the team.

```
<TRANSITION from="Resolved" to="Complete" for="[project]\AllTesters" not="[project]\NewTesters">  
</TRANSITION>  
```
