### ISSUE TITLE
Set Team Favorites Link Changes Menu on Left

### ISSUE THREAD

**Issue by spottedmahn** [MicrosoftDocs/vsts-docs#3]
When I'm here: [Review Team Delivery Plans](https://docs.microsoft.com/en-us/vsts/work/scale/review-team-plans) and I click on [Set team favorites](https://docs.microsoft.com/en-us/vsts/collaborate/set-favorites), the menu on the left changes.  I don't think that is supposed to happen, right?

**Before click**

![image](https://user-images.githubusercontent.com/14079228/32020517-75ec1bc8-b99e-11e7-9925-0ab187b10bdc.png)

**After click**

![image](https://user-images.githubusercontent.com/14079228/32020544-89aa9356-b99e-11e7-8804-ea89b78c17ae.png)

**Comment by KathrynEE** [comment]
This issue can be closed. The toc has been updated to work as expected.

**Comment by spottedmahn** [comment]
@KathrynEE nice!  works now 👍
