### ISSUE TITLE
(no author)

### ISSUE THREAD

**Issue by pilcherd** [MicrosoftDocs/vsts-docs#300]
When extracting SVN authors, can you say how to cope with an output of (no author) from the PowerShell command?  I.e. how do you map that to a user?  Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: edd6cbc8-5e3b-c3a1-4672-d42510cc058b
* Version Independent ID: 8fe81fb5-7c2d-2562-5659-55fccbb3126c
* Content: [Perform the migration from SVN to Git | Microsoft Docs](https://docs.microsoft.com/en-us/vsts/articles/perform-migration-from-svn-to-git)
* Content Source: [docs/articles/perform-migration-from-svn-to-git.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/articles/perform-migration-from-svn-to-git.md)
* Service: **unspecified**
* GitHub Login: @hkamel
* Microsoft Alias: **hkamel**

**Comment by steved0x** [comment]
@hkamel Can you take a look at this customer question? What should they do in this situation? Thank you.

**Comment by hkamel** [comment]
@pilcherd in case the author information is missing for any commit, the work around is to map the no author in your authors file. something like 
(no author) = no_author <no_author@no_author>

**Comment by pilcherd** [comment]
Thank you.

**Comment by steved0x** [comment]
@hkamel Thank you for that information, @pilcherd I'm closing this issue. Thank you for your feedback!
