### ISSUE TITLE
The publish YAML example doesn't mention you need to set publishVstsFeed to your own feed ID

### ISSUE THREAD

**Issue by jhorv-bvb** [MicrosoftDocs/vsts-docs#3001]
I thought maybe the GUID provided was some global constant, then realized that was silly.
Either way, it should mention you need to replace that GUID with your own, and how to find that.  I had to create the step in the designer to get my feed's ID.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 11ed58a1-5819-f3a4-c674-dafcdbd56fbc
* Version Independent ID: d68aca4d-3fd3-1864-09f5-6060295e0399
* Content: [Publishing to NuGet feeds - Azure Pipelines and TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/nuget?view=vsts&tabs=yaml)
* Content Source: [docs/pipelines/artifacts/nuget.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/artifacts/nuget.md)
* Product: **devops**
* GitHub Login: @erickson-doug
* Microsoft Alias: **amullans**

**Comment by elbatk** [comment]
Hi @jhorv-bvb , sorry for the confusion here! It looks like another (better) option here is to just use the feed name, and not a random GUID that is hard to find! I'm updating the docs to just say <feedName> there instead of a GUID. Thanks!

**Comment by hammady** [comment]
I discovered by chance that the feed name should include the project name. For example: `Project1/my-feed`.
