### ISSUE TITLE
No way to reset/update/delete the counter

### ISSUE THREAD

**Issue by avivanoff** [MicrosoftDocs/vsts-docs#3006]
How do I reset, update or delete a counter?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd7e0bd3-1f7d-d7b6-cc72-5ef63c31b46a
* Version Independent ID: dae87abd-b73d-9120-bcdb-6097d4b40f2a
* Content: [Pipeline variables - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=vsts&tabs=yaml%2Cbatch#feedback)
* Content Source: [docs/pipelines/process/variables.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/variables.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by vijayma** [comment]
This is on our backlog. We plan to work on this soon. @andyjlewis Can you pls assign this to moswald, who will be working on this? Thanks.

**Comment by jtemperv** [comment]
@vijayma, can we follow the progress somewhere or subscribe to get a notification when this is implemented?

**Comment by vijayma** [comment]
The counter gets reset automatically when the prefix changes. There is no out-of-band way of doing this currently. If you want that, please open a suggestion on https://developercommunity.visualstudio.com/spaces/21/index.html.
