### ISSUE TITLE
Is pattern case sensitive?

### ISSUE THREAD

**Issue by StephenHodgson** [MicrosoftDocs/vsts-docs#3010]
Not sure if the pattern is case sensitive.

For example the pattern:
```
[Mm]atch.dll
```

Would it match both of these files?
```
Match.dll
match.dll
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8fd54e81-9a0c-c5e5-fb89-9534372805ff
* Version Independent ID: f3d49618-32d7-0abc-1c33-8211eb7dd073
* Content: [File matching patterns reference for Azure Pipelines and TFS - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/file-matching-patterns?view=vsts)
* Content Source: [docs/pipelines/tasks/file-matching-patterns.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/file-matching-patterns.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by vtbassmatt** [comment]
This is platform dependent. For a file "Match.dll":

| Pattern: | "Match.dll" | "match.dll" | "[Mm]atch.dll" |
|---|---|---|---|
| Windows | matches | matches | matches |
| Linux | matches | doesn't match | matches |

**Comment by StephenHodgson** [comment]
Okay, will it's definitely not obvious that there is platform dependant matches. Could we update the docs to reflect this please?

**Comment by vtbassmatt** [comment]
Should be published today.

**Comment by StephenHodgson** [comment]
Awesome, thanks :)
