### ISSUE TITLE
Deny users to view Variable groups and Task Groups on Azure pipelines

### ISSUE THREAD

**Issue by PatrickGrub** [MicrosoftDocs/vsts-docs#3014]
In total I love the DevOps Docs, thanks for this great Work, it helps me a lot!

One thing I could not find:
How can I deny to view variable groups and Task Groups on Azure pipelines for specific users?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f2fe2521-cc98-8946-89b4-5a8199a6d898
* Version Independent ID: dbc4b6cf-ddb1-ac16-c634-eaf15072e111
* Content: [Library for Azure Pipelines and Team Foundation Server - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/library/index?view=vsts#security)
* Content Source: [docs/pipelines/library/index.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/library/index.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment]
Thank you for your feedback. I have passed this on to the product team for advice.

**Comment by ashokirla** [comment]
@PatrickGrub : If you are admin on a Variable group, you can remove all the users/groups with 'Reader' role.

**Comment by PatrickGrub** [comment]
**Thanks** @ashokirla it worked as you said for Variable Groups!

How about to deny Read access to `Task Groups`?

**Comment by ashokirla** [comment]
For task groups, we don't have deny read permissions. The philosophy of task groups is to enhance developer productivity and collaboration by being able to write once and share everywhere. It is similar to any other tasks where anyone can view and use the tasks. You can only control who can update/delete the task group.
