### ISSUE TITLE
Add warning about Deprecation of the Work Item Tracking (WIT) and Test Client OM

### ISSUE THREAD

**Issue by jawn** [MicrosoftDocs/vsts-docs#3015]
This page contains SOAP examples of an API that will deprecated in future versions.
It would be helpful to add a warning about this for readers that arrive directly on this page.

https://docs.microsoft.com/en-us/azure/devops/integrate/concepts/wit-client-om-deprecation

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aa8505e8-cef0-fee8-866a-e000058ac233
* Version Independent ID: d6858ee2-4282-b4e1-fb3b-e8b531b950b7
* Content: [.NET Client Library Samples for Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/integrate/get-started/client-libraries/samples?view=azdevserver-2019)
* Content Source: [docs/integrate/get-started/client-libraries/samples.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/integrate/get-started/client-libraries/samples.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by elbatk** [comment]
Thanks for catching this @jawn , adding a warning now with a link to the deprecation page!
