### ISSUE TITLE
Viewing all Projects' Objects (Work Items, Sprint Planning, etc)

### ISSUE THREAD

**Issue by crisher0219** [MicrosoftDocs/vsts-docs#3017]
Is it possible to hook into all the projects that you have in your org, or select them as needed?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 916ec07a-d3fb-cfd5-0052-245296d69f49
* Version Independent ID: 5c87aa39-9a7b-6a84-c8f3-ae51f5465392
* Content: [View, filter, & add user stories, issues, and bugs from the Work Items hub - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/work-items/view-add-work-items?view=vsts&tabs=new-nav)
* Content Source: [docs/boards/work-items/view-add-work-items.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/boards/work-items/view-add-work-items.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@crisher0219 - I'm not sure what you mean by "hook into all projects you have in your org". Please see [Switch project, repository, team](https://docs.microsoft.com/en-us/azure/devops/project/navigation/go-to-project-repo?view=vsts&tabs=new-nav) and [Work across projects](https://docs.microsoft.com/en-us/azure/devops/project/navigation/work-across-projects?view=vsts&tabs=new-nav). If you still have questions - please reopen this issue.

**Comment by crisher0219** [comment]
Oh, boy, @KathrynEE, I am sorry. I meant to post that comment here: https://docs.microsoft.com/en-us/azure/devops/report/powerbi/data-connector-connect?view=vsts. What I am trying to do is connect to all work items for an org in Azure DevOps. It might just be that I have to pull each project in individually. Also, it probably makes sense for me to move this thread over to the feedback on the above link.
