### ISSUE TITLE
Pull Request Validation for repositories hosted in DevOps

### ISSUE THREAD

**Issue by StephenHodgson** [MicrosoftDocs/vsts-docs#3018]
The workflow for repositories hosted in DevOps is a lot different from ones hosted with GitHub

In the visual designer, the Pull Request Validation trigger is shown properly for GitHub hosted repositories.

![image](https://user-images.githubusercontent.com/13334553/51135660-72134980-17ef-11e9-92a5-e9f598a3cd7c.png)

But the visual designer doesn't show Pull Request Validation triggers for Git repositories hosted in Azure DevOps.

![image](https://user-images.githubusercontent.com/13334553/51136028-55c3dc80-17f0-11e9-9ef5-7198e1678882.png)

Instead users need to go to the specific branch and setup branch policies. This wasn't obvious at first.

![image](https://user-images.githubusercontent.com/13334553/51135748-9e2eca80-17ef-11e9-843c-475522b8f491.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5673ec1-c7d1-e0ac-043a-8fc3d5b226a9
* Version Independent ID: b4872831-51c0-6cf8-1c56-de20beb38a80
* Content: [Build pipeline triggers - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/triggers?view=vsts&tabs=designer)
* Content Source: [docs/pipelines/build/triggers.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/build/triggers.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by StephenHodgson** [comment]
I found more relevant data on [this page](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/ci-build-git?view=vsts&tabs=yaml#azure-pipelines-or-tfs-repository)

Seems to be a duplicate page? Or they're slightly different?

**Comment by ryanmendoza** [comment]
Thank you for this comment!

**Comment by steved0x** [comment]
@StephenHodgson Sorry that it took me so long to respond to this issue. I am a new writer for Azure pipelines and I'll be working on repos and triggers. I'm taking a look right now and will add some info to the following section to call that out.

https://docs.microsoft.com/en-us/azure/devops/pipelines/build/triggers?view=azdevops&tabs=designer#pull-request-validation

Sorry that you ran into trouble; I am taking a look at this documentation right now and it should be live shortly.

**Comment by steved0x** [comment]
@StephenHodgson I just fixed this and it should be live later today. Thanks for letting us know.
