### ISSUE TITLE
Later scripts wrong $ should be $_

### ISSUE THREAD

**Issue by pilcherd** [MicrosoftDocs/vsts-docs#302]
E.g. correct script for last powershell script is:
git for-each-ref --format='%(refname)' refs/remotes | % { $_.Replace('refs/remotes/','') } | % { git branch "$_" "refs/remotes/$_"; git branch -r -d "$_"; }

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: edd6cbc8-5e3b-c3a1-4672-d42510cc058b
* Version Independent ID: 8fe81fb5-7c2d-2562-5659-55fccbb3126c
* Content: [Perform the migration from SVN to Git | Microsoft Docs](https://docs.microsoft.com/en-us/vsts/articles/perform-migration-from-svn-to-git)
* Content Source: [docs/articles/perform-migration-from-svn-to-git.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/articles/perform-migration-from-svn-to-git.md)
* Service: **unspecified**
* GitHub Login: @hkamel
* Microsoft Alias: **hkamel**

**Comment by steved0x** [comment]
@hkamel Can you take a look at this one too? Thank you.

**Comment by steved0x** [comment]
@pilcherd I'm taking a look at this one, and I think I'm looking at it wrong - the script you have in the issue description matches the one in the article - what change s exactly do I need to make to fix this? If it's easier to show rather than tell, you can make a PR directly into this repo with the change? Thank you.

**Comment by pilcherd** [comment]
When I run the current script:

git for-each-ref --format='%(refname)' refs/remotes | % { $.Replace('refs/remotes/','') } | % { git branch "$" "refs/remotes/$"; git branch -r -d "$"; }

I get a bunch of errors:

$.Replace : The term '$.Replace' is not recognized as the name of a cmdlet, function, script file, or operable
program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:59
+ ... r-each-ref --format='%(refname)' refs/remotes | % { $.Replace('refs/r ...
+                                                         ~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: ($.Replace:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException


If I change to this:


git for-each-ref --format='%(refname)' refs/remotes | % { $_.Replace('refs/remotes/','') } | % { git branch "$_" "refs/remotes/$_"; git branch -r -d "$_"; }

It runs ok (just ran it in PS against a folder). 

I believe the other script would also be wrong too:

cd c:\new-bare.git
git for-each-ref --format='%(refname)' refs/heads/tags | % { $.Replace('refs/heads/tags/','') } | % { git tag $ "refs/heads/tags/$"; git branch -D "tags/$" }

And should be

cd c:\new-bare.git
git for-each-ref --format='%(refname)' refs/heads/tags | % { $.Replace('refs/heads/tags/','') } | % { git tag $_ "refs/heads/tags/$_"; git branch -D "tags/$_" }

**Comment by pilcherd** [comment]
How interesting.... the items are not appearing in here correctly!!

![image](https://user-images.githubusercontent.com/25464172/37419578-26fa8c9c-278b-11e8-9bbf-c43429f0fad9.png)

**Comment by pilcherd** [comment]
Here is what my screen looks like in editor mode for the post (which looks like I haven't changed anything...)

![image](https://user-images.githubusercontent.com/25464172/37419716-77afd7f0-278b-11e8-895e-bfde993115af.png)

**Comment by pilcherd** [comment]
I missed one too.  I believe all $ in those should be "$_".

**Comment by steved0x** [comment]
@picherd I edited your comment to put code fences around it, like this?

```
git for-each-ref --format='%(refname)' refs/remotes | % { $_.Replace('refs/remotes/','') } | % { git branch "$_" "refs/remotes/$_"; git branch -r -d "$_"; }
```

and 

```
cd c:\new-bare.git
git for-each-ref --format='%(refname)' refs/heads/tags | % { $_.Replace('refs/heads/tags/','') } | % { git tag $_ "refs/heads/tags/$_"; git branch -D "tags/$_" }
```

**Comment by steved0x** [comment]
@pilcherd This change is live, thanks for letting us know!
