### ISSUE TITLE
Create in different AAD Tenant (Directory) 

### ISSUE THREAD

**Issue by liamfoneill** [MicrosoftDocs/vsts-docs#3021]
I have a work account that is a member of multiple AAD directories. I want to create the Azure DevOps organisation in a specific directory. I don't want to the thing changing the owner to a microsoft account as when I do that it errors when I try to change the owner to my outlook.com account.

In short, how do I pick up front which AAD to create the AZ DevOps org in? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b1b9dd76-4131-bf69-f9bc-c7f7ef562609
* Version Independent ID: 8d3bfbae-3398-c0a2-ca4d-c4782a3b4370
* Content: [Create, configure a new organization - Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/create-organization?view=vsts)
* Content Source: [docs/organizations/accounts/create-organization.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/accounts/create-organization.md)
* Product: **devops**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @liamfoneill, thanks for reaching out. I've contacted my PMs for some clarity and will get back to you shortly. Thanks

**Comment by chcomley** [comment]
@liamfoneill, Please see the following screenshot - you have an option within your profile page to select the directory from the dropdown. Create a new organization after you choose the right directory. 
![azure-portal-confirm-connected-directory](https://user-images.githubusercontent.com/35748196/51339322-04f6f280-1a41-11e9-8309-eeedd821356e.png)
I'm going to close this issue, however if you have any further questions, please let me know.
