### ISSUE TITLE
Duplicate content

### ISSUE THREAD

**Issue by vijay-gowda** [MicrosoftDocs/vsts-docs#3022]
Duplicate content - "You can't change type, move work items, or delete/restore work items whose work item types support test management or that belong to the Hidden Types Category. This includes all work items that track tests—such as test cases, shared steps, and shared parameters—code review requests and responses, and feedback requests and responses."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e9f02cb-f094-d6bc-ca7b-973db9de0082
* Version Independent ID: 1af6a7f5-9e99-ec99-081d-c0bf9e7ac5f5
* Content: [Move, change, delete, or restore user stories, bugs, tasks, and other work items - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/backlogs/remove-delete-work-items?view=vsts&tabs=new-nav)
* Content Source: [docs/boards/backlogs/remove-delete-work-items.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/boards/backlogs/remove-delete-work-items.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@vijay-gowda - Thank you for the feedback, I'm working to remove the duplicate content.
