### ISSUE TITLE
Specifying a particular commit for an additional repo (for templates)

### ISSUE THREAD

**Issue by laurawalker** [MicrosoftDocs/vsts-docs#3024]
The documentation (at https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=vsts&tabs=schema#repository-resource) states that "If your pipeline has templates in another repository, you must let the system know about that repository. The repository resource lets you specify an external repository.". The schema and syntax show that you can point to a particular branch or tag for that repo (with a ref) but I can't see any way to pin it to a particular commit. Is there a way to achieve that?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7458d5b2-1bb7-7d87-7ce6-2b0c430b0155
* Version Independent ID: edf5bbd3-a3f0-5426-e985-31290f8afd05
* Content: [YAML schema - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=vsts&tabs=schema#repository-resource)
* Content Source: [docs/pipelines/yaml-schema.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/yaml-schema.md)
* Product: **devops**
* GitHub Login: @erickson-doug
* Microsoft Alias: **macoope**

**Comment by vtbassmatt** [comment]
Create a tag pointing at the commit you want to pin to, then use the `ref` keyword to point at it. Interesting idea to allow pinning to precisely a commit, though, and I'll take it into consideration.

**Comment by laurawalker** [comment]
I guess that does achieve it, it's just a bit more clunky (and has the overhead of needing to manage tags) than I'd like. For context here, what would actually be really useful is just to be able to pick up the file from a submodule directly.

Thanks for the info though!

**Comment by vtbassmatt** [comment]
Understood and thanks for the context + feedback.
