### ISSUE TITLE
Inject Test Case parameters into associated automation?

### ISSUE THREAD

**Issue by mike-rogers** [MicrosoftDocs/vsts-docs#3026]
The Test Cases in our suite will sometimes have Parameters associated with them. I would like to inject these parameters into the execution of an associated automated test. Is that possible?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7b6c92a2-2f5c-e34e-f285-3e1a2a02604b
* Version Independent ID: 6f31f4c2-94ac-20eb-da01-e1d47f041945
* Content: [Run automated tests from test plans - Azure Test Plans](https://docs.microsoft.com/en-us/azure/devops/test/run-automated-tests-from-test-hub?view=vsts)
* Content Source: [docs/test/run-automated-tests-from-test-hub.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/test/run-automated-tests-from-test-hub.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment]
Thank you for your feedback. There is a link in the topic (How do I pass parameters to my test code from a build or release pipeline?) that links to the topic https://docs.microsoft.com/azure/devops/test/run-automated-tests-from-test-hub#pass-params. This explains you can use a runsettings file (https://docs.microsoft.com/visualstudio/test/configure-unit-tests-by-using-a-dot-runsettings-file). Does that answer your question?
