### ISSUE TITLE
Issue with repo types

### ISSUE THREAD

**Issue by AceHack** [MicrosoftDocs/vsts-docs#3030]
The doc says "Pipelines support two types of repositories, git and github." but the vsts extensions for vscode says, "Value is not accepted. Valid values: "github", "tfsgit", "tfsversioncontrol"."  What one is correct?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7458d5b2-1bb7-7d87-7ce6-2b0c430b0155
* Version Independent ID: edf5bbd3-a3f0-5426-e985-31290f8afd05
* Content: [YAML schema - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=vsts&tabs=schema#repository-resource)
* Content Source: [docs/pipelines/yaml-schema.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/yaml-schema.md)
* Product: **devops**
* GitHub Login: @erickson-doug
* Microsoft Alias: **macoope**

**Comment by vtbassmatt** [comment]
The VS Code extension has a [bug](https://github.com/Microsoft/azure-pipelines-vscode/issues/197). Thanks for the reminder; I thought I had already filed that.
