### ISSUE TITLE
Missing description for update Agent local as mention in the release letter Azure Devops server "Locally update your agent"

### ISSUE THREAD

**Issue by DalpheSDC** [MicrosoftDocs/vsts-docs#3032]
Hi where can I find the description for how to Locally update your agent. On server not on the internet? We are already running Azure Devops Server RC 1

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43799c5d-2f13-cc76-a1c0-a3f850e16d4e
* Version Independent ID: 97a5b73f-faf7-f9c0-9269-fc79984616d6
* Content: [Deploy a build and release agent on Windows - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/v2-windows?view=vsts)
* Content Source: [docs/pipelines/agents/v2-windows.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/agents/v2-windows.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by andyjlewis** [comment]
https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/v2-windows?view=azdevserver-2019#can-i-update-my-v2-agents-that-are-part-of-an-azure-devops-server-pool?

**Comment by vtbassmatt** [comment]
Also note the note :grin: that on RC1, it's a different folder name than on subsequent releases.

**Comment by DalpheSDC** [comment]
This doesn't give me any details about updating a client from TFS server without internet. Where I place the agent on a specific network location or on the local TFS apptier server to update all agent automaticaly.

**Comment by vtbassmatt** [comment]
Sorry for the confusion - we renamed the version selector (was "azdevserver-2019", now "azure-devops-2019") which broke the link above. Then it probably defaulted you to the service, which doesn't need or have this feature, so the content was missing.

Here's a corrected link, and I'll update my previous comment as well: https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/v2-windows?view=azure-devops-2019#can-i-update-my-v2-agents-that-are-part-of-an-azure-devops-server-pool

On RC1, you put the agent package in `%ProgramData%\Microsoft\DevOps\Agents`. On RC2 and later, you put the agent package in `%ProgramData%\Microsoft\Azure DevOps\Agents`. Both locations are on the app tier.

**Comment by DalpheSDC** [comment]
Thank you for the Update is this the same for the deployment groups or are it still a manuel update when the server is not on the internet?

**Comment by vtbassmatt** [comment]
Should work for deployment groups as well.
