### ISSUE TITLE
Dissociate fork from upstream repo

### ISSUE THREAD

**Issue by mchelen** [MicrosoftDocs/vsts-docs#3033]
Is there any way to dissociate a fork from its upstream repo? For example, Repo A might be forked to create Repo B, and then B diverges into its own independent codebase. New branches in Repo B should always have their pull requests default to Repo B, not Repo A.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 240f15e3-daf9-78f8-7423-cc17490ee401
* Version Independent ID: 3f1934d0-75c4-56b3-32d5-676b7fbe70b7
* Content: [Fork your repository - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/forks?view=vsts&tabs=visual-studio)
* Content Source: [docs/repos/git/forks.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/repos/git/forks.md)
* Product: **devops**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by joebourneMS** [comment]
Hello, unfortunately there is no way to disassociate a fork from it's parent repo. This is not ideal, but you could clone B locally and push the contents to a new repo C. You would lose history etc. but it would allow you to begin pushing to 'Repo C'

**Comment by congyiwu** [comment]
> Can we request that some better alternative be added, maybe in the repo's settings?

Yeah, that's a reasonable feature request.  See and upvote: https://developercommunity.visualstudio.com/idea/365802/allow-option-of-converting-forks-to-repos.html

**Comment by mchelen** [comment]
Great, I'll upvote the issue over there. Thanks!
