### ISSUE TITLE
Broker Links

### ISSUE THREAD

**Issue by shoatman** [MicrosoftDocs/vsts-docs#3034]
Links in acceptance criteria section are broken.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dbdbe4c8-400b-0f3f-2214-4233a05c1752
* Version Independent ID: 4dafb9ad-de23-5d3c-130e-c1baa944ecb4
* Content: [What are best practices for working with product and portfolio backlogs - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/backlogs/best-practices-product-backlog?view=vsts#feedback)
* Content Source: [docs/boards/backlogs/best-practices-product-backlog.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/boards/backlogs/best-practices-product-backlog.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@shoatman - Thank you for the feedback. I'm working to remove the broken  links.
