### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by joebates25** [MicrosoftDocs/vsts-docs#3036]
"Although makes branching easy, the overhead of managing branches can become significant if you have many branches."

I think something is missing from this sentence after 'although'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 767bcd21-4e4a-80b2-30c8-7a5059661a3b
* Version Independent ID: 031e819f-31a3-4b72-f462-4aa961741776
* Content: [Branch strategically - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/tfvc/branch-strategically?view=vsts#feedback)
* Content Source: [docs/repos/tfvc/branch-strategically.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/repos/tfvc/branch-strategically.md)
* Product: **devops**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
@joebates25 Thanks for letting us know, I just fixed this and it should be live shortly.

#please-close
