### ISSUE TITLE
.NET Core Build Task builds all projects not just the ones specified in the .sln file

### ISSUE THREAD

**Issue by dkimbell13** [MicrosoftDocs/vsts-docs#3038]
Scenario: I have a solution w/ multiple projects in it. All projects are in a TFS Git Repository. I have manually removed one of the projects from the .sln file, but still want the source code to be in the repository. 

The .NET Core Build tasks builds all projects based on the found .csproj files. NOT the ones specified in the solution only (and there is no way to specify this option).

I realize that I could add/change the wildcard values so that it doesn't pick up the .csproj of the project that I don't want to build, but is that really the only option available now?

Dom

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 483dcb1c-1a89-2b20-4cf2-abd3ae88d9ed
* Version Independent ID: dc4722ed-5a4b-26ec-e7d5-a149bf6e79a7
* Content: [Build, test, and deploy .NET Core apps - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/languages/dotnet-core?view=vsts&tabs=yaml)
* Content Source: [docs/pipelines/languages/dotnet-core.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/languages/dotnet-core.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by adventworks** [comment]
Please open this issue on the task implementation in the [Azure pipelines tasks](https://github.com/Microsoft/azure-pipelines-tasks) repo.
