### ISSUE TITLE
Portable PDBs and Source Link

### ISSUE THREAD

**Issue by AceHack** [MicrosoftDocs/vsts-docs#3039]
Is this still true?

If you're using Portable PDBs, Source Link cannot currently authenticate to private source repositories (like Azure DevOps Services), and thus will not work.

If so when do we expect a resolution?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d921846-31fc-69eb-edef-6c41c050f592
* Version Independent ID: 83678a41-bf22-2318-4867-710ab7a14494
* Content: [Debug with symbols in Visual Studio](https://docs.microsoft.com/en-us/azure/devops/artifacts/symbols/debug-with-symbols-visual-studio?view=vsts)
* Content Source: [docs/artifacts/symbols/debug-with-symbols-visual-studio.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/artifacts/symbols/debug-with-symbols-visual-studio.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by StacyHenwood** [comment]
I have the same question as Acehack above. I have managed to wrangle Azure DevOps to create my snupkg file and upload it, but that all seems useless if we can't actually access it while debugging...

**Comment by mitchdenny** [comment]
With VS 2017.7 (I think) portable PDBs with SourceLink information will be able to fetch sources from private repositories. We don't support *.snupkg packages at the moment, we would like to and it is on the backlog. So in the meantime you still have the publish the PDB files (regardless of whether they are portable) to the Symbol Server using the Index and Publish Symbols task. In the case of Portable PDBs you don't have to index the symbols with the task, thats done with SourceLink.

I've got a PR outstanding which makes this a bit more clear in the docs.

**Comment by AceHack** [comment]
Can you please link to the PR here?  I would love to see the more clear documentation on this.  Thanks.

**Comment by mitchdenny** [comment]
Unfortunately the PR is to an internal Azure repos repository which isn't public.

**Comment by elbatk** [comment]
Hi @AceHack , we pushed that PR to our master branch and you should see it live within a day. Closing this issue and #3040 as it fixes both :) Cheers, and thanks for the feedback!

**Comment by joshmouch** [comment]
Is there a ticket somewhere on when SourceLink will be available in Azure DevOps?  I am finding very old information everywhere.
