### ISSUE TITLE
This document is great for mapping an existing project to SAFe.  How about an article starting from scratch

### ISSUE THREAD

**Issue by tapuzzo** [MicrosoftDocs/vsts-docs#304]
I have created SAFe projects in VSTS from scratch.  When I created teams, I let it create area paths because I have a one to one mapping (which is what I believe you are doing in the article above).
It is much easier (less user entry less opportunity for error)  to create teams and allow VSTS to create the area path at the same time.  Is this an ok practice?  If yes then I recommend a shorter article on getting started with SAFe....creating a new SAFE project. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c1cb521-d930-b7da-6568-4577d2d72487
* Version Independent ID: affd6426-51a1-da62-a008-97c751acd1e7
* Content: [Scaled Agile Framework | Microsoft Docs](https://docs.microsoft.com/en-us/vsts/work/scale/scaled-agile-framework)
* Content Source: [docs/work/scale/scaled-agile-framework.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/work/scale/scaled-agile-framework.md)
* Service: **unspecified**
* GitHub Login: @douge
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@tapuzzo - Thank you for your comment. The practice of creating area paths when adding teams is definitely a recommended practice. I've captured your input for a topic that addresses SAFe by creating it from scratch.
