### ISSUE TITLE
Portable PDBs

### ISSUE THREAD

**Issue by AceHack** [MicrosoftDocs/vsts-docs#3040]
This statement seems to be false.

"If you're using portable PDBs, you don't need to use the Index Sources and Publish Symbols task. For portable PDBs, the build does the indexing. This is a design feature of portable PDBs and .NET."

I do need this but it's not supported.  How do I debug with symbols from portable PDBs?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8cddddb9-2731-3366-2a76-9089b58d7f96
* Version Independent ID: b34de428-c3d2-14d6-a452-302c68b74c87
* Content: [Publish symbols for debugging - Azure Pipelines and TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/symbols?view=vsts)
* Content Source: [docs/pipelines/artifacts/symbols.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/artifacts/symbols.md)
* Product: **devops**
* GitHub Login: @erickson-doug
* Microsoft Alias: **amullans**

**Comment by mitchdenny** [comment]
@AceHack you are correct. That doc is incorrect, you still use the task to publish the symbols, but you don't index them with the task/ We'll get that text updated.

**Comment by mitchdenny** [comment]
OK - I've submitted a PR on our internal docs repository - @elbatk I've added you as a reviewer to that PR.

**Comment by AceHack** [comment]
Can you link the PR here?  Thanks.

**Comment by mitchdenny** [comment]
Unfortunately the PR is to one of our internal Azure Repos repositories.
