### ISSUE TITLE
Linux and portable PDB source indexing

### ISSUE THREAD

**Issue by AceHack** [MicrosoftDocs/vsts-docs#3041]
It's not clear from this documentation how to get this working on Linux.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 946d67f6-9bb7-481f-f32f-59b5965f9590
* Version Independent ID: 8865f1e2-15b3-8cdb-1d8c-939c665e9bdc
* Content: [Index Sources & Publish Symbols build and release task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/index-sources-publish-symbols?view=vsts)
* Content Source: [docs/pipelines/tasks/build/index-sources-publish-symbols.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/build/index-sources-publish-symbols.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by mitchdenny** [comment]
Currently we don't support publishing symbols from a Linux machine. What you could do is use SourceLink to index as usual as part of your build and then have a job that runs on Windows to publish the symbols. When we look at support *.snupkg packaging we will look to address the Linux symbol publishing scenario.

**Comment by AceHack** [comment]
How do I publish Portable PDBs from windows to VSTS.  All the documentation says this is not possible.

**Comment by mitchdenny** [comment]
You just use this process:
https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/symbols?view=vsts

This doc has an error (PR submitted) where it says for portable PDBs you don't index them, but you still publish the usual way and consume them the usual way. The SourceLinking package does what indexing normally does.
