### ISSUE TITLE
Can copy happen over another protocol ?

### ISSUE THREAD

**Issue by vmaruhpe** [MicrosoftDocs/vsts-docs#3042]
Looks like this approach needs SMB to be enabled. What is a recommended approach for copy over internet into the VM on prem ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5e0ef2cf-ed52-6ded-bf14-4820d73b4ed0
* Version Independent ID: 7781e0f0-43aa-9008-abda-c03a37e2d7b4
* Content: [Windows Machine File Copy task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/windows-machine-file-copy?view=vsts)
* Content Source: [docs/pipelines/tasks/deploy/windows-machine-file-copy.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/deploy/windows-machine-file-copy.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment]
Thank you for your feedback. I have passed this on to the product team for advice.

**Comment by shashban** [comment]
Copy files can happen over SSH using [Copy files over ssh](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/copy-files-over-ssh?view=azure-devops) task.
You can also use [Azure file copy](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-file-copy?view=azure-devops) task to copy files to Azure VMs over WinRM
