### ISSUE TITLE
Please update - Deployment Group is no longer in preview.

### ISSUE THREAD

**Issue by denhsu** [MicrosoftDocs/vsts-docs#3046]
Hi,
At the top of page, it says there"
A simpler way to deploy web applications to IIS servers is by using deployment groups instead of WinRM. Deployment groups are currently in preview for some users in Azure Pipelines. They are not yet available in TFS."

Deployment group is no longer preview.  Please update.  Is Deployment group still better choice to deploy to on-premise server?

thanks,
Dennis

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6037c0a7-9595-eff1-3f5c-2607baa73c4d
* Version Independent ID: 7b8cf300-4d91-ac77-3ffd-ef1a83c79af7
* Content: [Deploy to IIS using WinRM - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/apps/cd/deploy-webdeploy-iis-winrm?view=vsts)
* Content Source: [docs/pipelines/apps/cd/deploy-webdeploy-iis-winrm.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/apps/cd/deploy-webdeploy-iis-winrm.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment]
Thank you for your feedback. I will update the topic to include your recommendations.

**Comment by alexhomer1** [comment]
Deployment groups are likely to be the better choice to deploy to on-premises servers.
