### ISSUE TITLE
Mention analytics as one of the options

### ISSUE THREAD

**Issue by hkamel** [MicrosoftDocs/vsts-docs#305]
Can we mention Analytics as one of the available options for VSTS under "And, available today only in VSTS" https://docs.microsoft.com/en-us/vsts/report/analytics/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a830bcfa-4584-922f-f28c-531cb59a454e
* Version Independent ID: 4f288fb1-78b1-0339-6627-316f6fb7686a
* Content: [Understand differences between VSTS and TFS | Microsoft Docs](https://docs.microsoft.com/en-us/vsts/user-guide/about-vsts-tfs#feedback)
* Content Source: [docs/user-guide/about-vsts-tfs.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/user-guide/about-vsts-tfs.md)
* Service: **unspecified**
* GitHub Login: @douge
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
Thank you for your comment. I will update the topic as you suggest.
