### ISSUE TITLE
Missing GUI option in yaml (Create work item on failure) 

### ISSUE THREAD

**Issue by fokkeantonides** [MicrosoftDocs/vsts-docs#3050]
In the GUI you can tick a box to create a work item when the build/release fails. In yaml there is not yet this option? 

I see a lot of great additions on the roadmap, but this one is still missing I think.

Thanks in advance!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7458d5b2-1bb7-7d87-7ce6-2b0c430b0155
* Version Independent ID: edf5bbd3-a3f0-5426-e985-31290f8afd05
* Content: [YAML schema - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=vsts&tabs=schema)
* Content Source: [docs/pipelines/yaml-schema.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/yaml-schema.md)
* Product: **devops**
* GitHub Login: @erickson-doug
* Microsoft Alias: **macoope**

**Comment by vtbassmatt** [comment]
This is a feature request, not a documentation issue. Please file it on [Developer Community](https://developercommunity.visualstudio.com/spaces/22/index.html) for consideration.
