### ISSUE TITLE
SQL Server Database Deploy is deprecated

### ISSUE THREAD

**Issue by pnwguy** [MicrosoftDocs/vsts-docs#3051]
SQL Server Database Deploy task has been deprecated, would be good to update the document, pointing to WinRM - SQL Server DB Deployment task.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4e2663d5-b101-2eca-984a-51a25b972d0b
* Version Independent ID: 6779599b-291e-4324-8dca-992885856e57
* Content: [Deploy apps and databases with Deployment Groups - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/apps/cd/howto-webdeploy-iis-deploygroups?view=vsts#database)
* Content Source: [docs/pipelines/apps/cd/howto-webdeploy-iis-deploygroups.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/apps/cd/howto-webdeploy-iis-deploygroups.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment]
Thank you for your feedback. I have passed this on to the product team for advice and I will update the topic to include their recommendation.

**Comment by RoopeshNair** [comment]
No, SQL Server Database Deploy task mentioned in the doc is valid one The SQL deploy task that is deprecated has [Deprecated] in the title. Refer to the screenshot below. You have two options to deploy to SQL server. 
- You can use either the deployment group SQL Server Deploy task. You don't have to open WinRM port to the machine but you install the build/release agent on the target.
- or you can use WinRM task from the marketplace. 


![image](https://user-images.githubusercontent.com/1370480/51386628-1f1bf800-1b49-11e9-8395-6f484bd7f224.png)
