### ISSUE TITLE
Select agents by specifying demands by checking greater, lesser than and not just -equals

### ISSUE THREAD

**Issue by daminetreg** [MicrosoftDocs/vsts-docs#3052]
Dear Devops team,

It looks like it's possible to specify demands when selecting the pool by checking the equality of a capability.

Is there a way to do this by checking if for say a capability named RAM is greater than some value ?

Like : 
```
pool:
  demands:
  - RAM -greater-than 16  
  - agent.os -equals Darwin  # check for specific string in capability
```

Thanks for the great documentation.
Cheers,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7458d5b2-1bb7-7d87-7ce6-2b0c430b0155
* Version Independent ID: edf5bbd3-a3f0-5426-e985-31290f8afd05
* Content: [YAML schema - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=vsts&tabs=example#pipeline-structure)
* Content Source: [docs/pipelines/yaml-schema.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/yaml-schema.md)
* Product: **devops**
* GitHub Login: @erickson-doug
* Microsoft Alias: **macoope**

**Comment by vtbassmatt** [comment]
Thanks for your kind words :grin:

Sorry, the demands language is limited to existence and equality. You can file a feature request over [here](https://developercommunity.visualstudio.com/spaces/21/visual-studio-team-services.html?type=idea), but in full transparency, I don't see us prioritizing a change to that area.
