### ISSUE TITLE
Images and descriptions for 2017 don't seem to be correct

### ISSUE THREAD

**Issue by nschonni** [MicrosoftDocs/vsts-docs#3053]
There is a note at the top that the terms have changed in after 2018, but with the images and features being different, this isn't a page I can send to anyone to learn about the topic in 2017

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d589bb13-a51a-77a5-d2f0-f424e42ede04
* Version Independent ID: 7b250082-a9c0-7dc2-9381-d04fbc5b7624
* Content: [Define a multi-stage CD release pipeline - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/define-multistage-release-process?view=tfs-2017)
* Content Source: [docs/pipelines/release/define-multistage-release-process.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/release/define-multistage-release-process.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment]
Thank you for your feedback. I plan to update these topics to cover all versions of TFS. Hoever, at present I don't have a completion date for this.
