### ISSUE TITLE
Change status to something else then done

### ISSUE THREAD

**Issue by MaxHogervorst** [MicrosoftDocs/vsts-docs#3054]
Hi,

First, awesome new feature!

Is it also possible to change settings regarding to which status it moves or what the target branch is?

for example instead of moving to done when it's in the master branch, move it to our 'ready for testing' status?

Thanks,

Max

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c82842d8-dd84-249f-cce1-9e93ecf703bf
* Version Independent ID: eaf9a299-4492-8e09-287a-f10b63d15e29
* Content: [Link GitHub commits and pull requests to work items in Azure Boards - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/github/link-to-from-github?view=vsts)
* Content Source: [docs/boards/github/link-to-from-github.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/boards/github/link-to-from-github.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@mmitrik - Can you respond to Max per his questions in this issue?

**Comment by mmitrik** [comment]
@MaxHogervorst, we don't yet support customizations to the state transitions, but it is a scenario that we're thinking about.  If you were given a choice between these options, which would you prefer?
1. **The ability to define custom verbs and map them to states**.  For example, `start` might map to the `in progress` state, and a mention like, "Start AB#123" would move the work item to the `in progress` state.
2. **The ability to use state names in mentions**.  In this case, a mention like "ready for testing AB#123" would put the work item directly in the `ready for testing` state.
