### ISSUE TITLE
Argument Names do not map to real names

### ISSUE THREAD

**Issue by katlimruiz** [MicrosoftDocs/vsts-docs#3055]
example
Azure subscription &gt;&gt; azureSubscriptionEndpoint

which is barely one of the few we can deduct (based on this document examples)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d9dbf88-7e55-d427-145e-d36b04fb197f
* Version Independent ID: a3f30c00-817c-9c05-7a57-3f2bf618821e
* Content: [Docker task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/docker?view=vsts#arguments)
* Content Source: [docs/pipelines/tasks/build/docker.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/build/docker.md)
* Product: **devops**
* GitHub Login: @erickson-doug
* Microsoft Alias: **dastahel**

**Comment by shashankbarsin** [comment]
Thanks for reporting this issue. We have updated the documentation to address this issue.
