### ISSUE TITLE
Guest account access

### ISSUE THREAD

**Issue by aminoplacid** [MicrosoftDocs/vsts-docs#3057]
As consultants, we create Teams in our own tenant in order to manage projects for our clients who we must deploy DevOps in their own tenant and do not have Teams licenses. We need the ability to create DevOps integration to manage projects for our clients. We cannot simply create a Team in our clients tenant.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1cddc0ae-93af-297c-2e71-334143ebee1e
* Version Independent ID: cb76e516-8471-c3e1-45f4-0a20a223f32a
* Content: [Microsoft Teams with Azure DevOps Services and Team Foundation Server](https://docs.microsoft.com/en-us/azure/devops/service-hooks/services/teams?view=vsts)
* Content Source: [docs/service-hooks/services/teams.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/service-hooks/services/teams.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by elbatk** [comment]
Hi @aminoplacid , I'm going to add @roofers for awareness, but I'm going to close this as a docs issue as I think you'll be better reaching out to the [Azure DevOps Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html) to get in touch with the product team.
