### ISSUE TITLE
issues when publish package 

### ISSUE THREAD

**Issue by anarchitect** [MicrosoftDocs/vsts-docs#3058]
i follow the instruction but get error when use vsts publish. 

the error is "Microsoft.VisualStudio.Services.Common.VssUnauthorizedException: VS30063: You are not authorized to access https://dev.azure.com.
   at Microsoft.VisualStudio.Services.Common.VssHttpMessageHandler.&lt;SendAsync&gt;d__17.MoveNext() ......". Can you please help?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77bcd39f-91ab-bb93-40fc-dd4fc5f2374f
* Version Independent ID: c228aece-669a-57d6-b3ed-d427586f8a61
* Content: [Publish and then download a Universal Package](https://docs.microsoft.com/en-us/azure/devops/artifacts/quickstarts/universal-packages?view=vsts&tabs=azuredevops)
* Content Source: [docs/artifacts/quickstarts/universal-packages.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/artifacts/quickstarts/universal-packages.md)
* Product: **devops**
* GitHub Login: @alexmullans
* Microsoft Alias: **amullans**

**Comment by alexmullans** [comment]
That sounds like you're not signed in. Ddi you complete the "Log in to Azure DevOps" section with a PAT that has the Packaging (write) scope enabled?

If so, please post this on [Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html). I'm closing this GitHub issue as it's not a docs-specific issue.
