### ISSUE TITLE
Use build completion trigger with a build that doesn't complete successfully

### ISSUE THREAD

**Issue by raketenolli** [MicrosoftDocs/vsts-docs#3059]
I am running Selenium tests for a website as nightly builds and the tests and thus the build usually do(es) not complete successfully. Another build that uses the same SauceLabs resources, but for a different configuration, should start once the first build is complete (I could use scheduled triggering, but the run times vary wildly). Unfortunately, it seems to not start if the first build does not complete successfully. Is this true, and if yes, is there a way to circumvent this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5673ec1-c7d1-e0ac-043a-8fc3d5b226a9
* Version Independent ID: b4872831-51c0-6cf8-1c56-de20beb38a80
* Content: [Build pipeline triggers - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/triggers?view=vsts&tabs=designer#build-completion-triggers)
* Content Source: [docs/pipelines/build/triggers.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/build/triggers.md)
* Product: **devops**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
@raketenolli I got confirmation that the build completion trigger only works when the build succeeds. I am closing this issue, but you can continue the thread by filing a feature request at https://developercommunity.visualstudio.com/spaces/21/index.html to have this functionality added.

Thank you for your feedback.
