### ISSUE TITLE
Doesn't Match Actual Nav

### ISSUE THREAD

**Issue by macux** [MicrosoftDocs/vsts-docs#3061]
When I rename my organisation I have a Name option and the URL is auto generated underneath. Changing the name shows a Save button which when clicked asks for confirmation similar to the confirmation screen you show above and requires me to re-enter the name.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 129e3d78-3ac8-8d07-d573-5530cd018656
* Version Independent ID: 1fbe6f52-2967-114e-1d2b-af4771080ac7
* Content: [Rename your organization - Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/rename-organization?view=vsts&tabs=new-nav)
* Content Source: [docs/organizations/accounts/rename-organization.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/accounts/rename-organization.md)
* Product: **devops**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Thanks for the heads up on this, @macux. I've published a fix, which should go live sometime this afternoon or early morning tomorrow. Thanks again.
