### ISSUE TITLE
Not possible to use visual designer anymore?

### ISSUE THREAD

**Issue by cdietschrun** [MicrosoftDocs/vsts-docs#3063]
The documentation refers to the visual designer and how to use it. When I create a new pipeline for a repo of mine, I no longer see any way to get to the visual designer. 

I really disagree with being forced to use the YAML for every pipeline, it's so much overhead and very error prone, and the visual designer is just better in every way for many of my needs. Why are we being forced to use it?

I also have some other pipelines that show me the YAML, but have an "edit in visual designer" link that I can't get to with this new repo. Is this intended?

**Comment by steved0x** [comment]
@cdietschrun You can turn off the new XAML pipeline editing experience as described in step 2 of here:

https://docs.microsoft.com/en-us/azure/devops/pipelines/get-started-designer?view=vsts&tabs=new-nav#create-a-build-pipeline

I'm not sure why some YAML pipelines have and "edit in visual designer" and some do not, and I am passing this along to see if I can get more information for you.

**Comment by vtbassmatt** [comment]
All YAML pipelines have a few settings which you can only edit on the web. We've been moving some things around in the UI; is it possible you're looking at repos in two different Azure DevOps organizations? If so, it's possible that a UI change has reached one of them but not the other yet. A screenshot of the two different cases would be helpful (though see below about where to file).

Please file suggestions for the product [here](https://developercommunity.visualstudio.com/spaces/21/visual-studio-team-services.html?type=idea) and bugs [here](https://developercommunity.visualstudio.com/spaces/21/visual-studio-team-services.html?type=problem). This repo is for the docs, which seem to be correct.
