### ISSUE TITLE
Not clear how to reference variables from appcmd.exe commands

### ISSUE THREAD

**Issue by krilbe** [MicrosoftDocs/vsts-docs#3064]
It is not clear how to reference variables from appcmd.exe commands. Do we use Windows batch references, PowerShell... or what?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 244121ae-5de4-14cd-a9c3-d9cda5ad0a3b
* Version Independent ID: 313238b7-d67b-bc60-1188-cbe305179600
* Content: [IIS Web App Manage task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/iis-web-app-management-on-machine-group?view=vsts)
* Content Source: [docs/pipelines/tasks/deploy/iis-web-app-management-on-machine-group.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/deploy/iis-web-app-management-on-machine-group.md)
* Product: **devops**
* GitHub Login: @erickson-doug
* Microsoft Alias: **dastahel**

**Comment by RoopeshNair** [comment]
$(variable) should work for the build/release variables. Since the task is based on PowerShell Handler you can also use the PowerShell variables directly.
