### ISSUE TITLE
Page level access management.

### ISSUE THREAD

**Issue by igorushi** [MicrosoftDocs/vsts-docs#307]
Is it possible to grant wiki access rights per page?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 58d291c7-b242-57ae-e4ae-2a75eaf3c91d
* Version Independent ID: 4d491730-d433-05a5-e685-9cbaa16141cb
* Content: [Manage permissions for READMEs and wiki pages | Microsoft Docs](https://docs.microsoft.com/en-us/vsts/collaborate/manage-readme-wiki-permissions#feedback)
* Content Source: [docs/collaborate/manage-readme-wiki-permissions.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/collaborate/manage-readme-wiki-permissions.md)
* Service: **unspecified**
* GitHub Login: @douge
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
Thank you for your inquiry. No, permissions to access the wiki are made for all pages and not individual pages.

**Comment by Budenniy** [comment]
Would be really nice to see per-page access control and per-area wiki-s, since managing multiple projects IN TFS as areas within a single main project became a common practice, also with Sharepoint integration being dropped.

**Comment by VinKamat** [comment]
How do we share wiki links with every member in your company who is on AAD?
