### ISSUE TITLE
Internet Connectivity ?

### ISSUE THREAD

**Issue by vmaruhpe** [MicrosoftDocs/vsts-docs#3070]
Can we configure Microsoft Hosted Agent Pools to have internet connectivity ? There are scenarios, where we may need updated software eg : downloading updated Power Shell modules. Is this supported on MS Hosted Agents or Custom Agents is the only way ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4409a9cb-8448-edd6-da0a-243e5601aa3e
* Version Independent ID: ec15f71a-a76d-c3f9-1d31-832f92183ef4
* Content: [Agents pools - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/pools-queues?view=vsts)
* Content Source: [docs/pipelines/agents/pools-queues.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/agents/pools-queues.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by vtbassmatt** [comment]
The hosted agents have full internet connectivity. Did you have trouble installing software on them?

**Comment by vmaruhpe** [comment]
Matt,

Thanks for the response. Yes, tried to pull some PowerShell commandlets  for Azure Stack to setup the environment but  there was an error to the effect that  there was no external connectivity. I tried this over a month back.

Thanks,
Maruthi

**Comment by vtbassmatt** [comment]
OK, give it another try now - could have been something transient. If that still doesn't work, open a ticket on [Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html). Thanks!
