### ISSUE TITLE
Needs update for Azure Devops Server

### ISSUE THREAD

**Issue by cakriwut** [MicrosoftDocs/vsts-docs#3072]
The "Code Search" extensions is not available for Azure Devops Server. There is confusion between Azure Devops **Server** vs Azure Devops **Service**. 
Kindly update the documentation on how to activate code search for Azure Devops Server 2019.

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be0bdbf7-3132-9007-6c6a-368c5bcb0f3d
* Version Independent ID: 58118f61-f88f-24b9-b785-d8f9d8a1fefd
* Content: [Administer code, wiki and workitem search](https://docs.microsoft.com/en-us/azure/devops/project/search/administration?view=vsts&tabs=new-nav)
* Content Source: [docs/project/search/administration.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/project/search/administration.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment]
Thank you for your feedback. We are currently updating this topic. Please check back in a few days time.
