### ISSUE TITLE
Is load testing in Azure DevOps depreciated?

### ISSUE THREAD

**Issue by mcasperson** [MicrosoftDocs/vsts-docs#3073]
The text at the top of this pages that says "Start running cloud-based load tests in almost no time with Azure DevOps" directs you to https://azure.microsoft.com/en-au/services/devops/test-plans/.

The content of the page https://azure.microsoft.com/en-au/services/devops/test-plans/ suggests that load tests are run in Azure Devops under the `Test Plans` -&gt; `Load test` section.

![image](https://user-images.githubusercontent.com/160104/51449495-09404a00-1d78-11e9-9760-ba8777579955.png)

In Azure Devops the `Load test` page tells you you can upload a `Visual Studio webtest`. If you click the `Create test` button you will be shown a dialog that says "Author user scenario using webtest. Learn more".

![image](https://user-images.githubusercontent.com/160104/51449509-18bf9300-1d78-11e9-8afd-fc79eac067b4.png)

If you click "Learn more" you are taken to https://docs.microsoft.com/en-us/previous-versions/visualstudio/visual-studio-2008/ms182539(v=vs.90). This page tells you it is not being updated regularly. 

![image](https://user-images.githubusercontent.com/160104/51449522-26751880-1d78-11e9-9b6d-2f1f13a2c9c4.png)

So you go ahead and google "Visual Studio Web Test" and you will find a page like https://docs.microsoft.com/en-us/visualstudio/test/quickstart-create-a-load-test-project?view=vs-2017 which says "Web performance and load test functionality is deprecated."

I'm a little confused by all this and can not find any concrete explanation as to whether the depreciation of the web performance and load test functionality in Visual Studio impacts Azure Devops. The two offerings seem to be tightly coupled, but I haven't seen any indication that load testing in Azure is depreciated.

If anyone can shed some light on the future of the load testing solution in Azure it would be much appreciated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 938662b3-8e6d-aebf-062b-d00b4ed4c22e
* Version Independent ID: fe2487bf-0d3d-24f3-6cf1-4cd18973ef79
* Content: [Load test in the cloud with Visual Studio - Azure Test Plans](https://docs.microsoft.com/en-us/azure/devops/test/load-test/getting-started-with-performance-testing?view=vsts)
* Content Source: [docs/test/load-test/getting-started-with-performance-testing.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/test/load-test/getting-started-with-performance-testing.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by nschonni** [comment]
https://devblogs.microsoft.com/devops/cloud-based-load-testing-service-eol/

**Comment by PBoraMSFT** [comment]
@mcasperson  - Yes, the service is deprecated. The announcement was made last week https://devblogs.microsoft.com/devops/cloud-based-load-testing-service-eol/ 
The docs team is helping with updating the docs to show the deprecated status - it should be done in the next couple of days.

**Comment by rajanikanthr** [comment]
> @mcasperson - Yes, the service is deprecated. The announcement was made last week https://devblogs.microsoft.com/devops/cloud-based-load-testing-service-eol/
> The docs team is helping with updating the docs to show the deprecated status - it should be done in the next couple of days.

Any chance of extending the EOL date from March 31 2020?

**Comment by girishacharya** [comment]
In the above notice, it says 

"Running a load test in the cloud using Visual Studio (both auto-provisioned agents and self-provisioned ‘bring-your-own’ agents): You can continue to run the tests but self-hosted with Test Controller/Test Agent option outlined above."

After reading this I am further confused. If we have our load test agents created in Azure - then can we use them to perform the load test? Can someone please clarify?
