### ISSUE TITLE
How to get tags for deployment targets ?

### ISSUE THREAD

**Issue by thinkriver** [MicrosoftDocs/vsts-docs#3075]
I have deployment group contains multiple targets (server), each server has multiple tags, for example Web1A, Web1B.

In one task, some variable is need to changed depend on tag, for example if server has Web1A tag, then using '1' as the value, otherwise using '0' as the value.

However, I have checked document, I haven't find out a way to get tags for the server. Is there a way to get tags of deployment target ? Thanks

https://developercommunity.visualstudio.com/content/problem/431755/how-to-get-tags-from-deployment-group-target.html

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3b38c265-be4c-b038-e3a9-783a5e5ce659
* Version Independent ID: 67da69da-3651-a8f4-f06a-c35aa3aa98fc
* Content: [Use deployment groups in a release pipeline - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/deployment-groups/?view=vsts)
* Content Source: [docs/pipelines/release/deployment-groups/index.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/release/deployment-groups/index.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment]
Your Developer Community reuest has been answered:

Currently we are not supporting tags as release variable and is already in our backlog.
But you can simply make rest call from your script to get tags . Reference: https://docs.microsoft.com/en-us/rest/api/azure/devops/distributedtask/targets/get?view=azure-devops-rest-5.0 If you still face any issue please write to RM_Customer_Queries@microsoft.com.

Thank you.
