### ISSUE TITLE
Wrong language displayed in modal dialog docs

### ISSUE THREAD

**Issue by steevokovsky** [MicrosoftDocs/vsts-docs#3076]
Issue:
---
- The language specified in the docs don't match with the real ones, e.g. [Displaying a form in a modal dialog](https://docs.microsoft.com/en-us/azure/devops/extend/develop/ui-controls/modaldialogo?view=vsts#displaying-a-form-in-a-modal-dialog)
- the title states, that this is javascript but it is clearly typescript.

Solution: 
---
- rename the title to typescript
- add another section and add the javascript code

Thanks :)

**Edit:**
---
Issue also occurs in [Menubar](https://docs.microsoft.com/en-us/azure/devops/extend/develop/ui-controls/menubaro?view=vsts)

**Comment by elbatk** [comment]
Ah, thanks @steevokovsky , fixing this now!
