### ISSUE TITLE
".vsts-ci.yml" or "azure-pipelines.yml"

### ISSUE THREAD

**Issue by trajano** [MicrosoftDocs/vsts-docs#3077]
What's the current official file to trigger an automatic build?  Is it ".vsts-ci.yml" or "azure-pipelines.yml"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6724abea-bbdc-bf66-ed5e-3214fa6c3e66
* Version Independent ID: 4f8dab21-3f0e-da32-cc0e-1d85c13c0065
* Content: [Job and step templates - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/templates?view=vsts)
* Content Source: [docs/pipelines/process/templates.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/templates.md)
* Product: **devops**
* GitHub Login: @vtbassmatt
* Microsoft Alias: **alewis**

**Comment by vtbassmatt** [comment]
Either will work, and you can have a leading `.` or not for either one. Our style preference is "azure-pipelines.yml" since that's our new name :)

**Comment by trajano** [comment]
But it appears that .vsts-ci.yml is the one that generates the build job automatically where-as azure-pipelines.yml require an explicit build job to be created.

**Comment by vtbassmatt** [comment]
Hmm... I thought we fixed that. @DavidStaheli we should be auto-creating a build on `azure-pipelines.yml`, right?

**Comment by DavidStaheli** [comment]
The build job should now be created -only- for `azure-pipelines.yml`, but the automatic creation currently only works for pushes to Azure Repos Git - so not GitHub, Bitbucket Cloud, etc. repositories.

**Comment by trajano** [comment]
It didn't occur on my last push but it could just be a blip

**Comment by DavidStaheli** [comment]
I just sent an email for this to be investigated.

**Comment by trajano** [comment]
I'm going to do a quick test again... basically clone an existing repo which already has `azure-pipelines.yml` working and see if it creates a new build.

**Comment by trajano** [comment]
Seems to have worked on my last try a few minutes ago.  I'll reopen if I notice it failing again.

**Comment by trajano** [comment]
Tried again with a new repo containing `azure-pipelines.yml`, no luck.  It does not appear to work consistently.

**Comment by JerryWang20** [comment]
i have the same question, what's way to create auto build pipeline now?

**Comment by JerryWang20** [comment]
Progress on it? It looks like a bug for VSTS

**Comment by davidstaheli** [comment]
@trajano and @JerryWang20, can one of you please report this issue on the [Azure DevOps Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html)?  That's the primary location for bug reports and it will ensure that this long-running issue gets tracked and routed appropriately.

**Comment by davidstaheli** [comment]
Closed per comment above.

**Comment by Glober777** [comment]
A link to this issue on the Azure DevOps Developer Community:
https://developercommunity.visualstudio.com/content/problem/1244535/azure-pipelinesyml-no-longer-creates-a-new-build.html
