### ISSUE TITLE
Does powershell recognize `$IPADDR` written in the "Switch based on platform" example YAML?

### ISSUE THREAD

**Issue by norio-nomura** [MicrosoftDocs/vsts-docs#3078]
It seems necessary to rewrite to `%IPADDR%`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 797838e7-f32b-868e-8766-8d96973bf18f
* Version Independent ID: 20c9e62d-56ec-f5a0-c3f9-6f72bf96252e
* Content: [Cross-platform scripting - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/scripts/cross-platform-scripting?view=vsts&tabs=yaml#switch-based-on-platform)
* Content Source: [docs/pipelines/scripts/cross-platform-scripting.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/scripts/cross-platform-scripting.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by vtbassmatt** [comment]
The `$(IPADDR)` syntax is actually a pipeline variable, not an environment variable that would be specific to the script type.
