### ISSUE TITLE
Amazing

### ISSUE THREAD

**Issue by Tiedroid** [MicrosoftDocs/vsts-docs#3081]
Thank you for your feedback!

The issues in this repo are for documentation feedback.

If you are submitting your documentation feedback issue directly through GitHub, please provide the URL of the article so we can route the feedback to the correct author.

Please report Azure DevOps or TFS software bugs, feedback, or questions in the [Azure DevOps Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html).

**Comment by Tiedroid** [comment]
Wonderful and seamless

**Comment by steved0x** [comment]
@Tiedroid Thank you for your feedback! I am passing it along to the team.
