### ISSUE TITLE
Can we use Microsoft for startups 0036P sponsored subscriptions credit to buy Azure Devops?

### ISSUE THREAD

**Issue by Benjiiim** [MicrosoftDocs/vsts-docs#3082]
Can we use Microsoft for startups 0036P sponsored subscriptions credit to buy Azure Devops?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 52303279-70fd-a0f6-cc6f-96bf73ed8c32
* Version Independent ID: cb30fbe3-b069-2665-d8da-9f714a23290a
* Content: [Frequently asked questions about billing management - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/billing/billing-faq?view=vsts&tabs=new-nav)
* Content Source: [docs/organizations/billing/billing-faq.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/billing/billing-faq.md)
* Product: **devops**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @Benjiiim, Thanks for posting your question. I've followed up with my PM and will be in touch shortly.

**Comment by chcomley** [comment]
We allow using that type of subscription for Azure DevOps, so it should work. The offer details [here](https://azure.microsoft.com/en-us/offers/ms-azr-0036p/) mention that it has a specific term.
There should be a path to let you convert to paying. Please let me know if you have further questions.
