### ISSUE TITLE
links broken

### ISSUE THREAD

**Issue by nicos99** [MicrosoftDocs/vsts-docs#3083]
§ "End-to-end sequence to define and assign Area Paths", point, The links mentionned after "Follow the steps provided later in this article" are not displayed

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: b52fb8a5-d949-dbe6-7e3f-56ac61984e8a
* Version Independent ID: 5e1aeb8b-35bd-8c40-769c-fdac56768b0d
* Content: [How are area and iteration paths used? - Azure DevOps & TFS](https://docs.microsoft.com/fr-fr/azure/devops/organizations/settings/about-areas-iterations?view=vsts)
* Content Source: [docs/organizations/settings/about-areas-iterations.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/settings/about-areas-iterations.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@nicos99 - Thank you for the feedback. I'm updating the article to provide working links.
