### ISSUE TITLE
How to manage keys for multiple users

### ISSUE THREAD

**Issue by NeubauerJohannes** [MicrosoftDocs/vsts-docs#3084]
Is there a way to manage the keys for multiple users automatically (e.g. with puppet)?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 64e85ff9-9add-d15c-e92f-02d7dd05e0f2
* Version Independent ID: 0cbd7427-6acd-3cfc-1a3b-8bf5ca60f3bd
* Content: [Connect to your Git repos with SSH - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/use-ssh-keys-to-authenticate?view=vsts)
* Content Source: [docs/repos/git/use-ssh-keys-to-authenticate.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/repos/git/use-ssh-keys-to-authenticate.md)
* Product: **devops**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by marcpopMSFT** [comment]
There is nothing built in like puppet but you may be able to use the details from the QA section of this document related to multiple SSH keys (note quite the same scenario as multiple users but closest we have). Q: I have multiple SSH keys. How do I use different SSH keys for different SSH servers or repos?
