### ISSUE TITLE
API "Approve a release" is NOT working for TFS 2017

### ISSUE THREAD

**Issue by gauravlakhani** [MicrosoftDocs/vsts-docs#3085]
I am working on TFS 2017 (latest upate) and ServiceNow integration.
I am getting issue with this API "Approve a Release". API version as per this document is api-version = 4.0-preview.2 OR 4.0-preview but it doesn’t work with this as TFS 2017 doesn't support this version of API. I have tried with other API versions which are supported like 3.0, 3.1, 3.2 and 3.2-Preview but it it is still not working. Tried with parameters.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 664c74de-5612-9eb4-06f8-dc95c304c2fe
* Version Independent ID: ff6be0b3-1619-7813-27c4-58d00094f9e9
* Content: [Release approvals](https://docs.microsoft.com/en-us/azure/devops/integrate/previous-apis/rm/approvals?view=tfs-2017)
* Content Source: [docs/integrate/previous-apis/rm/approvals.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/integrate/previous-apis/rm/approvals.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by elbatk** [comment]
Hi @gauravlakhani , from the [version chart](https://docs.microsoft.com/en-us/rest/api/azure/devops/?view=azure-devops-rest-5.0#api-and-tfs-version-mapping), it looks like TFS 2017 Update 2 would use version 3.2. Adding @wnjenkin to see if she has any input on why this wouldn't be working.

**Comment by gauravlakhani** [comment]
I am still waiting for any concrete answer to this. I think the solution is to update to TFS 2018 and then try API version 4.0. Please confirm.

**Comment by chcomley** [comment]
Hi @gauravlakhani, Please accept our sincerest apologies for losing sight of this issue. I'm hoping you've found your way by now, however please do let me know if you have any further questions. Thanks for your feedback.

**Comment by vtbassmatt** [comment]
@chcomley sorry, neither Will nor I own this API. It would be someone from the RM team.

**Comment by chcomley** [comment]
I'll be closing this issue, as there's been no reply for over 4 months. We can always create a new issue and get to the bottom of it, if need be. Thanks everyone.
