### ISSUE TITLE
maven task fails to authenticate inside a container job when authenticateMavenFeed is true

### ISSUE THREAD

**Issue by KoduIsGreat** [MicrosoftDocs/vsts-docs#3086]
I have a scenario where I need to run my build job inside a custom container. 
Everything goes fine until it attempts to deploy and i get 401 unauthorized.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 589e076c-9f67-77df-3204-4f549566f21b
* Version Independent ID: 2e51ef13-8fd3-1397-82f0-27c92f1ccee5
* Content: [Maven build and release task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/maven?view=vsts)
* Content Source: [docs/pipelines/tasks/build/maven.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/build/maven.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by terminatur** [comment]
I am running into this issue as well, and is a blocker for us. Any updates on this?

**Comment by cforce** [comment]
Would be great to have any documentation for this parameter "authenticateMavenFeed".

**Comment by brianlongmsc** [comment]
I suspect this is a typo as this parameter appears as 'mavenFeedAuthenticate' when generating the build pipeline from the wizard?

**Comment by davidstaheli** [comment]
The docs now show that the correct parameter name is `mavenAuthenticateFeed`.  Apologies for the confusion!
