### ISSUE TITLE
Can I search for all of my @mentions?

### ISSUE THREAD

**Issue by JaxSmitty** [MicrosoftDocs/vsts-docs#3090]
Or can I search for @mentions of a certain user?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 34ae521f-6ae4-4d7f-2cce-f844e5811b66
* Version Independent ID: 18098490-1f34-e966-3135-cb90197bfa6f
* Content: [Use @mentions in work items and pull requests - Azure DevOps Services & TFS](https://docs.microsoft.com/en-us/azure/devops/notifications/at-mentions?view=vsts)
* Content Source: [docs/notifications/at-mentions.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/notifications/at-mentions.md)
* Product: **devops**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @JaxSmitty, 
No, it only works for mention on you – the @RecentMentions operator. Please let us know if you have any more questions.

**Comment by rselvarajbsd** [comment]
Without a way to search mentions as part of a query. The emails gets lost and no way for us to respond.

**Comment by herkyjerky** [comment]
This is a feature request disguised as a question.  while one can use 'history' field and search for your specific mention name string.  however, it would be much easier if there was an @me parameter within history so any user can see THEIR mentions in a shared query.

**Comment by chcomley** [comment]
Hi @rselvarajbsd and @herkyjerky, 
We address content feedback on this avenue, however here's a link if you'd like to submit a feature request, idea, or get support: https://developercommunity.visualstudio.com/content/idea/post.html?space=21. Thanks.
