### ISSUE TITLE
Unable to find "Shell Script" task

### ISSUE THREAD

**Issue by ssctx66** [MicrosoftDocs/vsts-docs#3093]
Per https://docs.microsoft.com/en-us/azure/devops/pipelines/apps/c-cpp/gcc?view=vsts&tabs=github#azure-pipelines-and-tfs-2018, I should be able to find this via a search by clicking the "+" on Job 1.  A search for "shell script" yields 6 results although none of them have "shell script" in the description nor do any of the respective descriptions seem particularly applicable.  Please advise as to how to determine which task to add.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28aa2b0d-f269-c37f-527d-dfb2265ba8ed
* Version Independent ID: 0ed27461-46e4-9b7a-6528-936de585ca0c
* Content: [Build your GCC C/C++ app - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/apps/c-cpp/gcc?view=vsts&tabs=github#azure-pipelines-and-tfs-2018)
* Content Source: [docs/pipelines/apps/c-cpp/gcc.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/apps/c-cpp/gcc.md)
* Product: **devops**
* GitHub Login: @erickson-doug
* Microsoft Alias: **dastahel**

**Comment by ssctx66** [comment]
I meant to note that I am following this tutorial in an attempt to establish an Azure Pipeline

**Comment by steved0x** [comment]
@vijayma Do you have any ideas to help with this one?

**Comment by vijayma** [comment]
@ssctx66, please use the "Bash" task. We renamed this task and since then haven't updated the doc. @steved0x, pls update the doc, or open a work item in the docs backlog.

**Comment by ssctx66** [comment]
Understood, @vijayma.  Thanks for the guidance.
