### ISSUE TITLE
Variables and parameters

### ISSUE THREAD

**Issue by fleed** [MicrosoftDocs/vsts-docs#3095]
Is it possible to specify the variables as parameters that can be optionally set when queuing the build?
Is it also possible to restrict the possible values for variables to a specific set? E.g.: configuration can only have the values 'Debug' or 'Release'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd7e0bd3-1f7d-d7b6-cc72-5ef63c31b46a
* Version Independent ID: dae87abd-b73d-9120-bcdb-6097d4b40f2a
* Content: [Pipeline variables - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=vsts&tabs=yaml%2Cbatch)
* Content Source: [docs/pipelines/process/variables.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/variables.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by alexhomer1** [comment]
Thank you for your feedback. You may want to explore using variable groups, see https://docs.microsoft.com/en-us/azure/devops/pipelines/library/variable-groups?view=azdevops&tabs=yaml#variable-groups-in-a-build-or-release. You can specify the values for variables when you queue a release. You cannot limit the value range for variables in a variable group.
