### ISSUE TITLE
Refer to a repo from another organization

### ISSUE THREAD

**Issue by slawekww** [MicrosoftDocs/vsts-docs#3097]
Repository resource schema for Azure Pipelines define type: git.
If you choose git as your type, then name refers to another repository in the same project. For example, otherRepo. To refer to a repo in another project within the same organization, prefix the name with that project's name. For example, OtherProject/otherRepo.

Please advise when it would be possible to refer to a repo from another organization.
My goal is to define common pipelines templates as repo to share across many organizations.
If you have suggestions how to achieve it, welcome to share.

Docs reference: https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=vsts&tabs=schema#repository-resource

**Comment by slawekww** [comment]
Hi, possibility to use Azure templates repository between different organization is key feature for my company. Shall I raise it as feature in different way?

**Comment by steved0x** [comment]
@afeblot Thank you for sharing that. @slawekww If your issue matches the issue linked by @afeblot, you can vote it up, or create your own issue.

For feature requests, bugs, or any product related feedback, the best place is to file the issue at:

https://developercommunity.visualstudio.com/spaces/21/index.html

 Or you can choose **Product feedback** at the bottom of the article.

![image](https://user-images.githubusercontent.com/1580889/51848904-90e40680-22ec-11e9-893f-ded2716f3ea2.png)

**Comment by steved0x** [comment]
@slawekww I just confirmed that this isn't possible right now, so filing an issue at https://developercommunity.visualstudio.com/spaces/21/index.html (or upvoting the existing issue) would be the way to go.

Thank you.
