### ISSUE TITLE
Restrictions on artifact source alias are incorrect

### ISSUE THREAD

**Issue by midgleyc** [MicrosoftDocs/vsts-docs#3099]
The documentation claims

&gt;The source alias can contain only alphanumeric characters and underscores, and must start with a letter or an underscore

In practice, the source alias can contain dashes, can start with a number, can contain (and start with) non-ASCII characters like 剣. When adding / I got the error message "It cannot contain these characters: \ / : * ? " &lt; &gt; and |. ". This is the only restriction I could find.

Restricting to only alphanumeric and underscores and needing to start with a letter or underscore might be sensible -- bash variables are well-defined for only alphanumeric and underscores, and cannot start with a numeric. However, the current behaviour allows many more characters than the documentation claims.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 598465e1-85d4-4961-b8b6-902d6026c5e3
* Version Independent ID: 5ef1308a-3aeb-fcc4-dec7-6f10785612a3
* Content: [Release artifacts and artifact sources - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/artifacts?view=vsts)
* Content Source: [docs/pipelines/release/artifacts.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/release/artifacts.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment]
Thank you for your feedback. I have updated this topic to remove the paragraph related to the limitation. I have also passed your feedback to the product team as the will need to update the UI message that is displayed in the pipeline tab.
