### ISSUE TITLE
List SqlPackage.exe minimum version required

### ISSUE THREAD

**Issue by catsburg** [MicrosoftDocs/vsts-docs#310]
For the DACPAC import, it turns out you need an unspecified, minimum version of SqlPackage.exe. I used the SqlPackage.exe available with the SQL Server installation (2014), which turned out to be too old. After 3 hours of making the back-up and another 40 minutes uploading it to Azure, the import tooling failed with error:

[Error] The version of SqlPackage.exe used to create your DACPAC is not supported. Please download the latest version from https://aka.ms/vstssqlpackage and recreate the DACPAC.

If it's known which minimum version of SqlPackage.exe is required, please explicitly add it to the docs. Hopefully, that will save someone else a setback of a few hours during their migration.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a35b397-3fe8-122e-042e-280326f88a38
* Version Independent ID: 3e0f0afc-abeb-01be-d767-813cd6ad78db
* Content: [Migration import from TFS to Visual Studio Team Services (VSTS) | Microsoft Docs](https://docs.microsoft.com/en-us/vsts/articles/migration-import)
* Content Source: [docs/articles/migration-import.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/articles/migration-import.md)
* Service: **unspecified**
* GitHub Login: @douge
* Microsoft Alias: **douge**

**Comment by steved0x** [comment]
@catsburg I will find out and get it added to the article, sorry that you ran into trouble with your migration. Thank you for letting us know.

**Comment by steved0x** [comment]
@catsburg I've got this over to the right person and I have a work item on the backlog to get this document updated as soon as I get the min version for the migration. I'm going to close the issue, but I will update here when I have the change merged in. Thanks again for letting us know and sorry for the trouble.

**Comment by sabarishmadhana** [comment]
Hello Mr, steved0x,
We have also faced same issue while uploading into Azure. We also have same configuration as mentioned above.  Kindly please specify the version in the document, also possible share the work item link here, so that we can track if we can get any information from it.

Thanks in advance!!

**Comment by steved0x** [comment]
@catsburg @sabarishmadhana I’ve got some information about the minimum version of SQLPackage.exe to use when making your DACPAC.
 
* TFS 2017 imports needs to use the version in the 130 folder or higher
* TFS 2018 imports needs to use the version in the 140 folder or higher
 
The numbered folder (for example 130 or 140) might be in a couple of different locations, depending on how you installed it:
 
**SQL Server Data Tools** (change 14.0 to match your version of Visual Studio)
SQLPackage is in:
* C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\SQLDB\DAC\130\sqlpackage.exe
*C:\Program Files (x86)\Microsoft Visual Studio\*2017 or 2016*\SQL\Common7\IDE\Extensions\Microsoft\SQLDB\DAC\*140 or 130*
 
**SQL Server Management Studio**
%PROGRAMFILES%\Microsoft SQL Server\*130 or 140*\DAC\bin\sqlpackage.exe
 
For example, for TFS 2017 import, you must use SQLPackage.exe from the 130 or 140 folder, and for TFS 2018 import you must use the SQLPackage.exe from the 140 folder.
 
There are two versions of the SQL Server Data Tools (VS2015 and VS 2017) available for download here: https://aka.ms/vstssqlpackage
 
Both of these version contains a 130 and a 140 folder that is in either of the two Visual Studio folders listed above.

I'm getting this document updated to include that information.

Thanks,
Steve
