### ISSUE TITLE
Managers would love "estimated completion date" per feature

### ISSUE THREAD

**Issue by maxkreilein** [MicrosoftDocs/vsts-docs#3100]
The forecast tool is great and we use it for checking quickly if a sprint is "overbooked" during planning.
However, I'd (respectively my manager) like to see a column which displays the "estimated completion date" or "forecast date", based on the forecast, for every feature/user story.
This date would simply be the end date of the iteration that has been estimated by the forecast for backlog every item (independent of the potentially assigned iteration path)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9e47f8c5-7b66-ec49-a03c-1240ad9fe4f0
* Version Independent ID: 21551259-e300-329a-3ce1-95dbb4730bc5
* Content: [Forecasting - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/sprints/forecast?view=vsts&tabs=new-nav)
* Content Source: [docs/boards/sprints/forecast.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/boards/sprints/forecast.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@maxkreilein - Thank you for the feedback. To give product feedback, please visit https://developercommunity.visualstudio.com/spaces/21/index.html, and click on Suggest a feature.
