### ISSUE TITLE
Documentation Translation

### ISSUE THREAD

**Issue by miltoncamara** [MicrosoftDocs/vsts-docs#3101]
How do I help translate VSTS documentation for PT-BR? Is there any guide?

**Comment by steved0x** [comment]
@miltoncamara I will find out and get back to you.

**Comment by miltoncamara** [comment]
Hello @steved0x do you have any news to help me?

**Comment by thomps23** [comment]
@miltoncamara the Azure Devops content on docs isn't currently localized beyond en-US, and our current workflow for localized content doesn't include direct contribution per-locale.

I'll raise the issue of localization of this content internally, but for now there isn't a path forward.
