### ISSUE TITLE
Confusing Next Step

### ISSUE THREAD

**Issue by jawn** [MicrosoftDocs/vsts-docs#3103]
At the end of the article, the next step is "Deploy to IIS web servers on Windows". 

Why it's confusing: 
- This points to a different section in the docs.
- The current article has a broader scope than IIS based scenarios.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a5b870a-5ea3-402f-e40f-4c05bbd10531
* Version Independent ID: 20497cc1-7311-d41b-cf6b-bc84708d1963
* Content: [Control deployments with approvals and gates - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/deploy-using-approvals?view=vsts)
* Content Source: [docs/pipelines/release/deploy-using-approvals.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/release/deploy-using-approvals.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment]
Thank you for your feedback. I agree that the link does not perhaps point to a particularly relevant topic. I will review and update this during the next few days.
