### ISSUE TITLE
g,h   Go to Dashboards should be Go Home in Azure DevOps

### ISSUE THREAD

**Issue by jawn** [MicrosoftDocs/vsts-docs#3105]
In the current version of Azure DevOps
the following doc doesn't seem to be correct: 
g,h   Go to Dashboards 

It takes me to the homepage, showing all my projects.

Is there a different shortcut for the dashboards now?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c2fe0af-744d-e535-b300-8d1060945db6
* Version Independent ID: 10892c8d-ff0b-3072-46bd-cad31923c240
* Content: [Web portal& Team Explorer keyboard shortcuts - Azure DevOps Services & TFS](https://docs.microsoft.com/en-gb/azure/devops/project/navigation/keyboard-shortcuts?view=vsts)
* Content Source: [docs/project/navigation/keyboard-shortcuts.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/project/navigation/keyboard-shortcuts.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@jawn - Thank you for the inquiry. I am updating the content, the g,h shortcut opens the Projects page for the organization or collection. There is no shortcut to go to Dashboards.
