### ISSUE TITLE
Another solution to AAD Timeout Exception

### ISSUE THREAD

**Issue by automagicallyio** [MicrosoftDocs/vsts-docs#3106]
Another reason for AAD Timeout Exception is that you're running behind a corporate proxy. If you are using an outbound proxy for connecting to the Internet, the following setting in the C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\machine.config file must be added. This text must be entered at the bottom of the file. In this code, <PROXYADDRESS> represents the actual proxy IP address or host name.

    <system.net>
        <defaultProxy>
            <proxy
            usesystemdefault="true"
            proxyaddress="http://<PROXYADDRESS>:<PROXYPORT>"
            bypassonlocal="true"
            />
        </defaultProxy>
    </system.net> 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1798e45e-200d-f201-e4dd-58aac2427d29
* Version Independent ID: 86df23f9-1e19-65ae-de6d-cc6069521f34
* Content: [Troubleshooting the migration import from TFS to Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/articles/migration-troubleshooting?view=vsts)
* Content Source: [docs/articles/migration-troubleshooting.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/articles/migration-troubleshooting.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by elbatk** [comment]
Hi @roofers , could you take a look at this and let me know if we need to add something to the docs?

**Comment by roofers** [comment]
@automagicallyio - Thanks for your feedback. I'm going to be doing an overhaul on these documents this month. I'll take your feedback into consideration.
