### ISSUE TITLE
Can't add a clause in middle for grouping with existing clause not the last one

### ISSUE THREAD

**Issue by softwarecraft** [MicrosoftDocs/vsts-docs#3108]
I want to add a new clause to my query to create a grouping with an existing clause that is not the last one. The "create group" icon is only enabled when two or more consecutive clauses are selected. Hence to achieve my result I have to delete all the in-between clauses, add the new clause, and re-create the deleted clauses. The UI should support re-ordering the clauses.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 309b3b5f-7355-57ac-3775-b441f6e037f1
* Version Independent ID: 0d30ed27-9dc4-e8de-ef7e-c71842c9b4c3
* Content: [Create managed queries with the Query Editor - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/queries/using-queries?view=vsts&tabs=new-nav)
* Content Source: [docs/boards/queries/using-queries.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/boards/queries/using-queries.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@softwarecraft - Thank you for your feedback. I believe that you can do this through the Query Editor. Here is an image of where I was able to insert three clauses in between two grouped clauses. 

![image](https://user-images.githubusercontent.com/10856840/52236415-a1abf380-287b-11e9-97a0-dd9e8e428964.png)
