### ISSUE TITLE
Outdated commands

### ISSUE THREAD

**Issue by sameer-kumar** [MicrosoftDocs/vsts-docs#311]
PrepareClone is also deprecated. This needs to be mentioned here https://docs.microsoft.com/en-us/vsts/tfs-server/command-line/tfsconfig-cmd#deprecated-commands alongwith it's replacement. Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 160a2e8b-6f84-1ee7-8b96-73560c18331e
* Version Independent ID: 5a1d6835-4ae1-89ef-c798-c35ad6a049fb
* Content: [Manage TFS server configuration with TFSConfig | Microsoft Docs](https://docs.microsoft.com/en-us/vsts/tfs-server/command-line/tfsconfig-cmd#deprecated-commands)
* Content Source: [docs/tfs-server/command-line/tfsconfig-cmd.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/tfs-server/command-line/tfsconfig-cmd.md)
* Service: **unspecified**
* GitHub Login: @douge
* Microsoft Alias: **elbatk**

**Comment by elbatk** [comment]
Hi again, @sameer-kumar , forwarding this one to the product team as well in hopes we can get the replacement all figured out! Thanks again!
