### ISSUE TITLE
Need more detail information about 'What parts of the build get deleted'

### ISSUE THREAD

**Issue by thinkriver** [MicrosoftDocs/vsts-docs#3110]
If a build was linked to a work item, when this build is deleted, what will happen for this linked work item ? Will the link be removed?

Build record: You can choose to delete the entire build record or keep basic information about the build even after the build is deleted.

What are included in the 'Build record' ? Artifacts ?

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43a285f9-738d-9f76-4de0-a4c4ecf6f5f5
* Version Independent ID: 9581a043-4873-bf0a-138f-85f6a61ae950
* Content: [Build and release retention policies - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/policies/retention?view=vsts)
* Content Source: [docs/pipelines/policies/retention.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/policies/retention.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by andyjlewis** [comment]
Thank you for reporting this issue. I'm sorry for the long delay in response. I was out of the office for a long period of time earlier this year.

**Comment by chasewilson** [comment]
@thinkriver, thanks for the feedback. I've updated the documentation and will be live by tomorrow. What version of TFS/Azure DevOps are you using?

**Comment by chasewilson** [comment]
I'll be closing this issue for now. Feel free to open a new issue if you need more clarification :)
