### ISSUE TITLE
Use same repo name, Find-Modules should not use *

### ISSUE THREAD

**Issue by pspill** [MicrosoftDocs/vsts-docs#3111]
1. use the same repository name throughout.  In step 5, Find-Module uses "PowershellAzureDevopsServices" and Install-Module uses "PowershellVSTS".  They should match.
2. The Find-Module command should not include the *.  It should be "Find-Module -Repository PowershellAzureDevopsServices -Credential $credsAzureDevopsServices"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 35b3cd51-b365-433b-9149-697582d64e88
* Version Independent ID: 1cb1f4a3-5928-223d-592f-f3462fef4e4c
* Content: [Use Azure Artifacts as a private PowerShell repository](https://docs.microsoft.com/en-us/azure/devops/artifacts/tutorials/private-powershell-library?view=vsts&viewFallbackFrom=vsts%3A)
* Content Source: [docs/artifacts/tutorials/private-powershell-library.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/artifacts/tutorials/private-powershell-library.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by elbatk** [comment]
Thank you so much @pspill , I'm updating these now to help future users.
