### ISSUE TITLE
Allow for notifications to go to a specific team member

### ISSUE THREAD

**Issue by greengumby** [MicrosoftDocs/vsts-docs#3112]
Should a build fail currently it posts a message to the channel for the whole team to see. However if the branch being tested is a branch that is specific to a developer then it would be good to @Tag the developer. With many developers it becomes difficult to filter the notifications that need to be looked at.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1cddc0ae-93af-297c-2e71-334143ebee1e
* Version Independent ID: cb76e516-8471-c3e1-45f4-0a20a223f32a
* Content: [Microsoft Teams with Azure DevOps Services and Team Foundation Server](https://docs.microsoft.com/en-us/azure/devops/service-hooks/services/teams?view=vsts)
* Content Source: [docs/service-hooks/services/teams.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/service-hooks/services/teams.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by elbatk** [comment]
Hi @greengumby , I'm adding @roofers to see if this is possible. If it is, I can add it to the docs, if not, you may want to just post it to the [Azure DevOps Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html) as a request.

**Comment by roofers** [comment]
@greengumby - This is great feedback. Currently, we don't have the ability to @ mention someone in a hook. I recommend that you follow up on the developer community that @elbatk linked to above. It will help us better track these requests.
