### ISSUE TITLE
Example for OfflineDetach has wrong parameter

### ISSUE THREAD

**Issue by blackford** [MicrosoftDocs/vsts-docs#3113]
The parameter /configDB in the OfflineDetach example is not recognised by tfsconfig.exe. Should be /configurationDB as stated above.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43e93b61-8bfc-ad93-9463-554a69e90d9b
* Version Independent ID: 716ab768-6fb3-56a8-2e32-f91eca286e99
* Content: [Configure with TFSConfig - Azure DevOps Server & Team Foundation Server](https://docs.microsoft.com/en-us/tfs/server/ref/command-line/tfsconfig-cmd#offlinedetach)
* Content Source: [https://mseng.visualstudio.com/DefaultCollection/TechnicalContent/_git/tfs-docs-pr?path=%2fdocs%2fserver%2fref%2fcommand-line%2ftfsconfig-cmd.md&version=GBlive&_a=contents](https://mseng.visualstudio.com/DefaultCollection/TechnicalContent/_git/tfs-docs-pr?path=%2fdocs%2fserver%2fref%2fcommand-line%2ftfsconfig-cmd.md&version=GBlive&_a=contents)
* Product: **devops-server**
* Git Login: **elbatk**
* Microsoft Alias: **elbatk**

**Comment by elbatk** [comment]
Thank you @blackford , making the change now :)
