### ISSUE TITLE
Add new public content stream screenshot outdated

### ISSUE THREAD

**Issue by tene666** [MicrosoftDocs/vsts-docs#3116]
Currently the package type is a dropdown, not set of checkboxes, and in my 2 instances it only offers npm as possible package type, even if the URL pasted is NuGet compatible. Documentation leads to believe it is possible to add custom NuGet sources, but this is currently not the case

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 03b6ce9e-b09c-69a8-5153-8bb814c25f54
* Version Independent ID: ebc53603-e70e-fdcd-5895-8ebc8f980703
* Content: [Set up upstream sources for packages in Azure DevOps Services and TFS](https://docs.microsoft.com/en-us/azure/devops/artifacts/how-to/set-up-upstream-sources?view=vsts)
* Content Source: [docs/artifacts/how-to/set-up-upstream-sources.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/artifacts/how-to/set-up-upstream-sources.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by elbatk** [comment]
Ah, yeah sorry about that. We will get an updated screenshot and explain what is currently available a little better. @tene666

**Comment by Moza805** [comment]
Hi @elbatk is there any progress on this? Was rather hoping to add an upstream NuGet source.

**Comment by elbatk** [comment]
Hi @Moza805 , I'm assuming you mean a custom NuGet upstream. Unfortunately I have to be the bearer of bad news and say that custom sources for other protocols are in our backlog but the work is not scheduled yet. So today, for the next quarter or two, your upstream sources options are: the main public repository for each protocol:

- NuGet - nuget.org
- npm - npmjs.com
- Maven - Maven Central
- Python - PyPI

and npm custom upstreams. @chasewilson is going to make some updates to the doc to make this more clear

**Comment by Moza805** [comment]
Thanks for the prompt reply, bad news today but good to hear it's in the pipeline for some good news in the future.

Cheers again.
