### ISSUE TITLE
Jenkins needs to be updated before one can select Git in the Source Code Management section

### ISSUE THREAD

**Issue by robinmanuelthiel** [MicrosoftDocs/vsts-docs#3119]
While following the guide, I was unable to select Git in the Source Code Management section of a new item. Jenkins itself showed me some errors in the top menu bar. After updating Jenkins to the latest version, I was able to select Git and could proceed.

![screen shot 2019-01-24 at 16 20 51](https://user-images.githubusercontent.com/5874465/51688453-e5d60300-1ff4-11e9-8346-fedf0e0e13d3.png)

We should mention in the docs, that one might have to update the Jenkins installation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d3a995c1-0297-29df-ef46-408edccd2958
* Version Independent ID: f719cab3-cbe1-f2cd-74c2-ec52ba4549e2
* Content: [Build a package for Maven with Jenkins and Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/java/labs/mavenpmjenkins/?view=vsts#configure-the-jenkins-maven-installation)
* Content Source: [docs/java/labs/mavenpmjenkins/index.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/java/labs/mavenpmjenkins/index.md)
* Product: **devops**
* GitHub Login: @erickson-doug
* Microsoft Alias: **douge**

**Comment by davidstaheli** [comment]
Thank you for this suggestion. The docs have been updated and should be live within a few days.
