### ISSUE TITLE
Cannot add Service connection from Azure DevOps to local Jenkins

### ISSUE THREAD

**Issue by robinmanuelthiel** [MicrosoftDocs/vsts-docs#3120]
In the last step "Integrate Azure DevOps Services Team Build and Jenkins", you describe to use `http://10.0.0.4:8080` as the Server URL for the Jenkins service connection. If I do that, I get an error message like seen below. You might have run into the same problem, as you also added a screenshot where you edited the connection with the public DNS of the VM's Jenkins on port 8080. Please clarify that!

![screen shot 2019-01-24 at 17 00 02](https://user-images.githubusercontent.com/5874465/51690931-0eacc700-1ffa-11e9-8ca4-968284910b75.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d3a995c1-0297-29df-ef46-408edccd2958
* Version Independent ID: f719cab3-cbe1-f2cd-74c2-ec52ba4549e2
* Content: [Build a package for Maven with Jenkins and Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/java/labs/mavenpmjenkins/?view=vsts#integrate-azure-devops-services-team-build-and-jenkins)
* Content Source: [docs/java/labs/mavenpmjenkins/index.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/java/labs/mavenpmjenkins/index.md)
* Product: **devops**
* GitHub Login: @erickson-doug
* Microsoft Alias: **douge**

**Comment by robinmanuelthiel** [comment]
I now think, that it is totally fine, that the connection from Azure DevOps to Jenkins cannot be verified, because the Jenkins server is not public. It can be reached from the Docker Build Host on the virtual machine though.

I would like to suggest to remove the "Verify the connection" step from the guide and also remove the misleading screenshot, where the verification was successful but with a public URL.

**Comment by davidstaheli** [comment]
Thank you for these suggestions.  The docs have been updated and should be live within a few days.
