### ISSUE TITLE
Section numbering mismatch between "in this article" sidebar and "in this topic"

### ISSUE THREAD

**Issue by geeeyetee** [MicrosoftDocs/vsts-docs#3124]
The section numbering is inconsistent between the "in this article" sidebar and the listing under "in this topic" within the article. In the "in this article" sidebar, the number 4 is skipped and there is no number beside "Configure projects".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9170997a-3bb0-d093-a8b2-cb8ef1381756
* Version Independent ID: 3f8d176d-adb9-17a2-b057-457041acb9c0
* Content: [Move a project collection - Azure DevOps Server & Team Foundation Server](https://docs.microsoft.com/en-us/tfs/server/admin/move-project-collection)
* Content Source: [https://mseng.visualstudio.com/DefaultCollection/TechnicalContent/_git/tfs-docs-pr?path=%2fdocs%2fserver%2fadmin%2fmove-project-collection.md&version=GBlive&_a=contents](https://mseng.visualstudio.com/DefaultCollection/TechnicalContent/_git/tfs-docs-pr?path=%2fdocs%2fserver%2fadmin%2fmove-project-collection.md&version=GBlive&_a=contents)
* Product: **devops-server**
* Git Login: **elbatk**
* Microsoft Alias: **elbatk**

**Comment by elbatk** [comment]
Ah, thank you @geeeyetee , fixing now :)
