### ISSUE TITLE
Impersonation with REST API

### ISSUE THREAD

**Issue by LiohAu** [MicrosoftDocs/vsts-docs#3125]
I have tools based on the impersonation mecanism which is not available (I think) in the REST API, what are our options ? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 58fa4b52-1f5c-11c5-329b-2526613833fa
* Version Independent ID: 6d1fb152-1612-a0ec-06fc-4ea2e2135541
* Content: [Deprecation of the Work Item Tracking (WIT) and Test Client OM - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/integrate/concepts/wit-client-om-deprecation?view=vsts)
* Content Source: [docs/integrate/concepts/wit-client-om-deprecation.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/integrate/concepts/wit-client-om-deprecation.md)
* Product: **devops**
* GitHub Login: @danhellem
* Microsoft Alias: **dahellem**

**Comment by chcomley** [comment]
Hi @LiohAu, Following up on this issue from way back - did you find the answers you were looking for? Please let me know if I can look into this further for you. If I don't hear back by the end of the week, I'll close this issue. You can still respond once it's closed, and then we can reopen it, if necessary. Thank you!

**Comment by LiohAu** [comment]
No I did not find any solution for my problem.
I think microsoft is deprecating this api without taking into account that features are missing in the new REST one (like impersonation)...

**Comment by chcomley** [comment]
Adding @willsmythe for some clarity please. Thanks!

**Comment by chcomley** [comment]
@LiohAu, I've been in contact with @danhellem , who will be contacting you soon.

**Comment by danhellem** [comment]
Sorry, the REST API's work differently that SOAP. We don't have any plans to replace the impersonation mechanism in REST. We suggest using a PAT for your REST calls.
