### ISSUE TITLE
URL in example no longer works

### ISSUE THREAD

**Issue by davidmatson** [MicrosoftDocs/vsts-docs#3128]
I think the REST API has changed. I tried using the example, but I get a 404. When I change the URL to this pattern:
https://docs.microsoft.com/en-us/rest/api/azure/devops/build/builds/list?view=azure-devops-rest-5.0
It works.

Specifically,  project URL segment is now required, and the API group is "build" rather than "build-release".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 53f99d2d-363b-d01d-039d-4fdc636fa2df
* Version Independent ID: f47330d5-e2de-36a4-e5b3-5bc77505b161
* Content: [Authenticating with personal access tokens](https://docs.microsoft.com/en-us/azure/devops/integrate/get-started/authentication/pats?view=vsts)
* Content Source: [docs/integrate/get-started/authentication/PATs.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/integrate/get-started/authentication/PATs.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by elbatk** [comment]
Ah, you are absolutely correct @davidmatson , thanks for catching and reporting. I'll send out a fix for this today!
