### ISSUE TITLE
What does `Interleaved exclude patterns` mean?

### ISSUE THREAD

**Issue by ggirard07** [MicrosoftDocs/vsts-docs#3130]
Is it possible to have an example about `Interleaved exclude patterns are supported`?
Sorry but the term is not so easy to understand for non English speakers around there like me (or I may possible lack some education too ^^)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8fd54e81-9a0c-c5e5-fb89-9534372805ff
* Version Independent ID: f3d49618-32d7-0abc-1c33-8211eb7dd073
* Content: [File matching patterns reference for Azure Pipelines and TFS - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/file-matching-patterns?view=vsts)
* Content Source: [docs/pipelines/tasks/file-matching-patterns.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/file-matching-patterns.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by Paul-Dempsey** [comment]
I agree that this is an obscure sentence. I'm guessing that it is talking about a situation where the set of matched files for two (or more) patterns intersect. The "Double exclude" example in the topic is one such example, and should help clarify what that statement is intended to convey

**Comment by andyjlewis** [comment]
Thank you for reporting this issue. I'm sorry for the long delay in response. I was out of the office for a long period of time earlier this year.
