### ISSUE TITLE
What permissions/user levels?

### ISSUE THREAD

**Issue by srend42** [MicrosoftDocs/vsts-docs#3131]
This article should also show what permissions/user levels are required to see and restore...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 93b1cf79-de4e-500b-388a-64665e3af89b
* Version Independent ID: 2cdda8ac-9e42-eed7-8d0c-9ab8dfc2c5f8
* Content: [Restore a project - Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/organizations/projects/restore-project?view=vsts)
* Content Source: [docs/organizations/projects/restore-project.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/projects/restore-project.md)
* Product: **devops**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @srend42, great suggestion. Thanks for taking the time to let us know. I've created a user story, set to be completed this sprint. I'll be closing this issue, however please let me know if you have any other feedback or questions. Thanks again!
