### ISSUE TITLE
Dependent artifacts

### ISSUE THREAD

**Issue by MikeGlue** [MicrosoftDocs/vsts-docs#3132]
I have 2 pipelines. Pipeline 1 produces an artifact that is required by pipeline 2. These are individual pipelines as they are also individual repos. What's the best practice approach for how to deal with this? Basically what I need to happen is when pipeline 2 is run, it needs to retrieve the latest successful build artifact from pipeline 1, download it, and use it within the pipeline 2 process.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 212c7e28-54ee-d501-7fbe-c22d78fbaea6
* Version Independent ID: da5afdc4-c8fd-517f-ad8a-1db9d97e4457
* Content: [Artifacts in Azure Pipelines - Azure Pipelines and TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/artifacts-overview?view=vsts)
* Content Source: [docs/pipelines/artifacts/artifacts-overview.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/artifacts/artifacts-overview.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by stoopered** [comment]
Just curious, is the release pipeline for both always the same? If the release cadence is the same for both, and they they have a build dependence why not just place them both in the same repo? Or even the same solution (this way they will be versioned together, and makes versioning a breeze). MonoRepo is what many large companies do. Google only has 1 repo (though I do not follow this strategy). And Azure DevOps now supports path filters in your build policy if you need them. Also what is the Trigger that kicks off your builds?

**Comment by chasewilson** [comment]
@MikeGlue , Thanks for the questions. Unfortunately I think your best option is to reach out to the [Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html) and ask there. I'll be closing this issue for now, however, if you feel like there should be changes or additions, please feel free to open a new issue or make a feature request to the Developer Community :)
