### ISSUE TITLE
No link here to RC2 release notes yet

### ISSUE THREAD

**Issue by TASlavens** [MicrosoftDocs/vsts-docs#3133]
RC2 was available yesterday, but the release notes aren't linked from here yet.

https://docs.microsoft.com/en-us/tfs/release-notes/azuredevops2019

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ff0c895d-9660-6db7-676e-5aa194b403e8
* Version Independent ID: 5c14f6ec-f4b5-26dc-aaf2-d8fc445036b5
* Content: [What's new for Azure DevOps Server and Team Foundation Server - Azure DevOps Server & Team Foundation Server](https://docs.microsoft.com/en-us/tfs/server/whats-new)
* Content Source: [https://mseng.visualstudio.com/DefaultCollection/TechnicalContent/_git/tfs-docs-pr?path=%2fdocs%2fserver%2fwhats-new.md&version=GBlive&_a=contents](https://mseng.visualstudio.com/DefaultCollection/TechnicalContent/_git/tfs-docs-pr?path=%2fdocs%2fserver%2fwhats-new.md&version=GBlive&_a=contents)
* Product: **devops-server**
* Git Login: **elbatk**
* Microsoft Alias: **elbatk**

**Comment by elbatk** [comment]
Ah, yes @TASlavens , thanks for catching this. I'll add this to the backlog and get it added today!

**Comment by TASlavens** [comment]
Still not showing RC2...  Cleared the browser cache and so on, so I think it's not on my end.

**Comment by elbatk** [comment]
It should be live by the end of the day, sorry about that!
