### ISSUE TITLE
Organization & owner

### ISSUE THREAD

**Issue by StijnBt** [MicrosoftDocs/vsts-docs#3135]
If I create an organization with my Work Account (O365 & Azure tennant) is this organization tied to my user?
By default I am owner of the organization, but what if the account of the owner get suspendend?
What is the impact of this on the existing organization created by that user?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b1b9dd76-4131-bf69-f9bc-c7f7ef562609
* Version Independent ID: 8d3bfbae-3398-c0a2-ca4d-c4782a3b4370
* Content: [Create, configure a new organization - Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/create-organization?view=azdevops#)
* Content Source: [docs/organizations/accounts/create-organization.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/accounts/create-organization.md)
* Product: **devops**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @StijnBt,  for your first question, “If I create an organization with my Work Account (O365 & Azure tenant) is this organization tied to my user?“ The answer is Yes. The organization is associated with the email account that created it. 
As for the second question, "By default I am owner of the organization, but what if the account of the owner gets suspended? What is the impact of this on the existing organization created by that user?" I'm not sure I understand - are you referring to the impact on the members or the organization, or on resources like projects and builds in the organization? Thanks for clarifying...

**Comment by chcomley** [comment]
@StijnBt, just following up with you on this - is there anything I can help you further with? Please let me know. Thanks!

**Comment by StijnBt** [comment]
> As for the second question, "By default I am owner of the organization, but what if the account of the owner gets suspended? What is the impact of this on the existing organization created by that user?" I'm not sure I understand - are you referring to the impact on the members or the organization, or on resources like projects and builds in the organization? Thanks for clarifying...

Can the organization remain to exist if the original creator is no longer part of the O365/Azure tennant?
Sorry for the delay...

**Comment by chcomley** [comment]
Hi @StijnBt. The answer is yes, an organization can remain if the original creator is removed from the Azure AD tennant. Make sure you don't remove EVERY member of the organization from the Azure AD tenant. I'll be closing out this issue, however please let me know if you'd like any further clarification. Thank you!
