### ISSUE TITLE
The description of "Agile" appears twice

### ISSUE THREAD

**Issue by lesterw1** [MicrosoftDocs/vsts-docs#3136]
In the section titled "Basic, Agile, Scrum, and CMMI", the "Agile" description (and associated image) appears twice in the table. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b3466d1-72cc-2d47-d98b-7029639c0f79
* Version Independent ID: 4ff82210-6b5a-589d-261e-1ddbd3007e2a
* Content: [Choose a process - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/work-items/guidance/choose-process?view=azdevops&viewFallbackFrom=vsts)
* Content Source: [docs/boards/work-items/guidance/choose-process.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/boards/work-items/guidance/choose-process.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@lesterw1 - Thank you for the correction. I'll update the article soon.
