### ISSUE TITLE
Please provide some screenshots showing where to locate these roles.

### ISSUE THREAD

**Issue by stofte** [MicrosoftDocs/vsts-docs#3137]
Im completely unable to find this Agent Pool on the collection level. What is the collection level? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 65536478-7839-8477-b030-965159151e40
* Version Independent ID: 42f54ed3-8173-65b7-0a3a-e77b4c9b3d7a
* Content: [Understand how security roles work - Azure DevOps & TFS](https://docs.microsoft.com/en-us/azure/devops/organizations/security/about-security-roles?view=azdevops&viewFallbackFrom=vsts#agent-queue-security-roles)
* Content Source: [docs/organizations/security/about-security-roles.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/security/about-security-roles.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
Added screenshots to the article.
