### ISSUE TITLE
Typo in Work link types affected by section

### ISSUE THREAD

**Issue by nadamgm** [MicrosoftDocs/vsts-docs#3138]
Hi Everyone!

I suspect there is a typo in the Work Link types part of this document. At the "Affects - Affected by" section the document says that the reference names are: 
Microsoft.VSTS.Common.Affects.Forward
Microsoft.VSTS.Common.Affects.Reverse

This is incorrect and doesn't work on TFS 2018.
The correct reference is:
Microsoft.VSTS.Common.Affects-Forward
Microsoft.VSTS.Common.Affects-Reverse

Hope it helps, took me a few hours to figure out.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d9818350-b7e0-7789-95b4-77d5c5dd472e
* Version Independent ID: e4318c77-d744-e056-fc2a-4aa879be22cc
* Content: [Link types reference - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/queries/link-type-reference?view=tfs-2018#feedback)
* Content Source: [docs/boards/queries/link-type-reference.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/boards/queries/link-type-reference.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@nadamgm - Thank you for the feedback and correction. I'm updating the topic to reflect the correction.
