### ISSUE TITLE
VALIDUSER rule is not supported for System.CreatedBy

### ISSUE THREAD

**Issue by farooqkh** [MicrosoftDocs/vsts-docs#314]
Seems like the example given to restrict creation of WIT to a specific group is incorrect. I'm getting following error when I'm trying to add VALIDUSER rule to System.CreatedBy field....

TF26062: Rule '<VALIDUSER for="[Global]\Product Manager" not="[VTLS]\VTLS Team" />' is not supported for the field 'System.CreatedBy'.

Apparantly the same issue was reported on forum 4 years ago and conclusion was its an error in documentation...
https://social.msdn.microsoft.com/Forums/vstudio/en-US/dab18b4d-e1a0-4251-997c-3446d435ea3f/restricting-access-to-work-items?forum=tfsworkitemtracking

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7edefe89-30f7-a8e6-3db3-b63e21556d0b
* Version Independent ID: ccc297e8-f9ff-8ec8-b531-6e041d4f72d9
* Content: [Add or modify a work item type (WIT) | Microsoft Docs](https://docs.microsoft.com/en-us/vsts/work/customize/add-modify-wit)
* Content Source: [docs/work/customize/add-modify-wit.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/work/customize/add-modify-wit.md)
* Service: **unspecified**
* GitHub Login: @douge
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@farooqkh - Thank you for your comment. I will update the topic. Elsewhere we do document that most rules cannot be applied to System fields, however, this particular content has been held over for several years. Again, thank you for your comment.
