### ISSUE TITLE
Layout deprecated, safe to delete?

### ISSUE THREAD

**Issue by Bebo2345** [MicrosoftDocs/vsts-docs#3140]
The Layout element is deprecated, correct?
Is it safe to delete the Layout out of the form?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9029628e-b936-e977-0c5f-6a4a6a702063
* Version Independent ID: 36af8d47-7358-a353-aa78-5afb1923b0c6
* Content: [Layout XML element reference - TFS](https://docs.microsoft.com/en-us/azure/devops/reference/xml/layout-xml-element-reference?view=tfs-2015&viewFallbackFrom=tfs-2017)
* Content Source: [docs/reference/xml/layout-xml-element-reference.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/reference/xml/layout-xml-element-reference.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by nschonni** [comment]
If you still have people connecting from (old) Visual Studio it would be used

**Comment by KathrynEE** [comment]
@Bebo2345 - @nschonni is correct. If you have anyone connecting to your TFS from earlier versions of Visual Studio - it would be good to have kept the Layout section of the form.

**Comment by raluca-m** [comment]
How can I delete the Layout out of the Form? I am using Team Foundation Server 2019 and if I try to import the xml without the form I get a error.
![error](https://user-images.githubusercontent.com/54262195/82660230-45184780-9c2a-11ea-9409-b27dcbdde524.JPG)
