### ISSUE TITLE
Can we add 'features' to sprints?

### ISSUE THREAD

**Issue by axisc** [MicrosoftDocs/vsts-docs#3141]
Our current project has a different hierarchy on how the planning items are structured. Basically, I want to add 'features' to the backlog and then break them down to 'product backlog' items - which is the most granular work item type in the current project. 

Is this doable?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4880004e-aae6-a8c7-1aa2-218b6fb00b71
* Version Independent ID: c6e35d98-3b07-2881-536d-0174a71be14d
* Content: [Assign backlog items to a sprint - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/sprints/assign-work-sprint?view=azdevops&tabs=new-nav)
* Content Source: [docs/boards/sprints/assign-work-sprint.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/boards/sprints/assign-work-sprint.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@axisc - Yes, you can do as you propose. I suggest working on the Features Kanban Board and adding PBIs for each feature to accomplish the breakdown. You can then use the product backlog page to assign work to sprints. You can use the Parents On view to see the hiearchy and multi-select and assign to iterations very easily. You can use the Kanban Board view and filter on Iterations.
