### ISSUE TITLE
Cannot specify a File

### ISSUE THREAD

**Issue by JustinGrote** [MicrosoftDocs/vsts-docs#3144]
Targetpath says "Path to the folder or file you want to publish", however if you try a file path it errors with 
"The source directory provided does not exist, or is not a directory.", unless I'm getting the syntax wrong:

targetpath: '$(Build.ArtifactStagingDirectory)/testfile.txt'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 41baa0b5-175c-a697-4b7d-c150259c6e6b
* Version Independent ID: 75085b15-1acc-526a-0495-74a13c42c1d5
* Content: [Publish Pipeline Artifacts task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/publish-pipeline-artifact?view=azdevops)
* Content Source: [docs/pipelines/tasks/utility/publish-pipeline-artifact.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/utility/publish-pipeline-artifact.md)
* Product: **devops**
* GitHub Login: @mitchdenny
* Microsoft Alias: **midenn**

**Comment by steved0x** [comment]
@mitchdenny Thanks for the update. @JustinGrote I am closing this issue since it is resolved (or will be shortly). Thanks for letting us know.

**Comment by 97turbotalon** [comment]
Any update when the resolution for this issue will be released?

**Comment by mitchdenny** [comment]
Wildcard support is not implemented yet. You can use the ‘’’.artifactignore’’’ file for now.
