### ISSUE TITLE
Can single PBI be child of multiple Features (parents) ?

### ISSUE THREAD

**Issue by JiriZidek** [MicrosoftDocs/vsts-docs#3145]
The switch Parents on/off suggests that.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7899d58b-c8eb-0ab4-9126-54cbf0de4dc6
* Version Independent ID: ab4d7f52-536e-e3e2-77cf-47581f5cc2d6
* Content: [Organize your product backlog into a hierarchy of items - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/backlogs/organize-backlog?view=azdevops&tabs=new-nav)
* Content Source: [docs/boards/backlogs/organize-backlog.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/boards/backlogs/organize-backlog.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@JiriZidek - Thank you for the inquiry. The Parents On/Off switch is used to enable or disable an hierarchical view.  Hierarchical links only allow one parent for each work item. So no, a single PBI cannot be a child of multiple Features.
