### ISSUE TITLE
Missing Info for "Run your tests"

### ISSUE THREAD

**Issue by ModernRonin** [MicrosoftDocs/vsts-docs#3147]
Under "Collect Code Coverage" it says
"For this functionality, the test project must reference Microsoft.NET.Test.SDK version 15.8.0 or higher. "

The same should be stated under "Run your tests", too, because without it, the dotnet test ... run aborts with an error about not finding testhost.dll.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 483dcb1c-1a89-2b20-4cf2-abd3ae88d9ed
* Version Independent ID: dc4722ed-5a4b-26ec-e7d5-a149bf6e79a7
* Content: [Build, test, and deploy .NET Core apps - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/languages/dotnet-core?view=azdevops&viewFallbackFrom=vsts&tabs=designer#run-your-tests)
* Content Source: [docs/pipelines/languages/dotnet-core.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/languages/dotnet-core.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by andyjlewis** [comment]
@PBoraMSFT can you verify this and please give us a PR?

**Comment by vijayma** [comment]
Fix is in PR. Thanks for pointing this out.
