### ISSUE TITLE
Feedback Items

### ISSUE THREAD

**Issue by danielstocker** [MicrosoftDocs/vsts-docs#3149]
The "Install Azure DevOps Server" link in the "See also" section seems to be broken. (getting a 404)

Going through the installation process I was prompted to create databases with the "AzureDevOps_" prefix rather than the "Tfs_" prefix. 

So: AzureDevOps_Configuration & AzureDevOps_Collection respectively. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cec26a46-9137-57ee-af85-f7a1269c3b90
* Version Independent ID: 3b5e9bff-304f-3b14-6508-791f0f7eb66f
* Content: [Use Azure SQL Database - Azure DevOps Server & Team Foundation Server](https://docs.microsoft.com/en-us/tfs/server/install/install-azure-sql)
* Content Source: [https://mseng.visualstudio.com/DefaultCollection/TechnicalContent/_git/tfs-docs-pr?path=%2fdocs%2fserver%2finstall%2finstall-azure-sql.md&version=GBlive&_a=contents](https://mseng.visualstudio.com/DefaultCollection/TechnicalContent/_git/tfs-docs-pr?path=%2fdocs%2fserver%2finstall%2finstall-azure-sql.md&version=GBlive&_a=contents)
* Product: **devops-server**
* Git Login: **v-masebo**
* Microsoft Alias: **v-masebo**

**Comment by elbatk** [comment]
Hi @danielstocker , thank you for this feedback. @itillis , I have these changes in a PR, can you confirm the change from `Tfs_xxxx` to `AzureDevOps_xxxx` for me to push this change?

**Comment by itillis** [comment]
@elbatk That's correct, good catch!

**Comment by elbatk** [comment]
Closing this then :)
