### ISSUE TITLE
Missing VSTS IPs

### ISSUE THREAD

**Issue by dezdez** [MicrosoftDocs/vsts-docs#315]
Judging from my experience there is at least one missing VSTS IP for Western Europe when using a SQL Azure VM for large collections. I had to enable all traffic on port 1433 from the internet for the migration to be scheduled successfully. On the SQL VM I can see that it is being accessed from 13.95.233.212, which is not listed above. 

This IP address seems to only have been utilised for this recently, as I was able to perform a dry run migration 2 weeks ago.

Unfortunately figuring this out cost me a production migration weekend. I hope that this information helps someone else avoid the same.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a35b397-3fe8-122e-042e-280326f88a38
* Version Independent ID: 3e0f0afc-abeb-01be-d767-813cd6ad78db
* Content: [Migration import from TFS to Visual Studio Team Services (VSTS) | Microsoft Docs](https://docs.microsoft.com/en-us/vsts/articles/migration-import#vsts-ips)
* Content Source: [docs/articles/migration-import.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/articles/migration-import.md)
* Service: **unspecified**
* GitHub Login: @douge
* Microsoft Alias: **douge**

**Comment by steved0x** [comment]
@dezdez I will try and find out what happened, and get this added to the article, sorry that you ran into trouble with your migration. Thank you for letting us know. I'll update this issue as soon as I have more information.

**Comment by steved0x** [comment]
@dezdez This missing IP has been added and the others reviewed. Thank you very much for your feedback.
