### ISSUE TITLE
Link to Selenium Code misleading

### ISSUE THREAD

**Issue by GilShalit** [MicrosoftDocs/vsts-docs#3150]
The link goes to the Selenium IDE, which cannot (currently?) export test scripts to C# or any other language.  I found Katalon Recorder which can do so but will need to re-record...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 09e51d18-72ec-1ad4-9ae7-8185c8e1dcd6
* Version Independent ID: 9f2f0471-d123-8e95-1606-cd811d1ece9a
* Content: [Perform UI tests with Selenium - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/test/continuous-test-selenium?view=azdevops)
* Content Source: [docs/pipelines/test/continuous-test-selenium.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/test/continuous-test-selenium.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment]
Thank you for your feedback. The topic does not cover recording or exporting Selenium code. However, if you feel that this is a missing feature from the topic please let us know more details in a new GitHub Issue and we will investigate further.
