### ISSUE TITLE
Great documentation

### ISSUE THREAD

**Issue by marcvlima** [MicrosoftDocs/vsts-docs#3151]
Detailed and useful documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1a948662-d534-bb71-a6b8-ce6d884b0ebb
* Version Independent ID: f065bef6-017a-2615-3292-4ca5787f8458
* Content: [Configure the Velocity widget based on Analytics data - Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/report/dashboards/team-velocity?view=azdevops)
* Content Source: [docs/report/dashboards/team-velocity.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/report/dashboards/team-velocity.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@marcvlima  - Thanks for the feedback.
