### ISSUE TITLE
Can you explain how group ownership works?

### ISSUE THREAD

**Issue by cbeltPinnergy** [MicrosoftDocs/vsts-docs#3156]
Thank you for your feedback!

The issues in this repo are for documentation feedback.

If you are submitting your documentation feedback issue directly through GitHub, please provide the URL of the article so we can route the feedback to the correct author.

Please report Azure DevOps or TFS software bugs, feedback, or questions in the [Azure DevOps Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html).

**Comment by steved0x** [comment]
@cbeltPinnergy Thank you for your feedback. It looks like it might have gotten lost somehow. Can you submit a new issue by navigating to the topic for which you wish to leave feedback, and selecting **Content Feedback**? Thank you.

![image](https://user-images.githubusercontent.com/1580889/51848491-af95cd80-22eb-11e9-81a2-1680fc40caf9.png)
