### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by ggrater-touchmark** [MicrosoftDocs/vsts-docs#3157]
On the page:   "Work item field index"
Hosted by url:  https://docs.microsoft.com/en-us/azure/devops/boards/work-items/guidance/work-item-field?view=azdevops
Under the Section: "Hidden field attributes and the Work Item Field Explorer"
The Link "Work Item Field Attributes - What You Can and Can't Change."
Points to the href:  "http://blogs.msdn.com/devops/2012/08/17/work-item-field-attributes-what-you-can-and-can-t-change.aspx"

Which results in a 404:  Oops! That page can’t be found.

This should point to an actual page.   We are attempting to update the "Created By" field for work items.  But "Created By" seems to be read-only.   We would like to change it because some of our work items were created by a user that no longer works at the company.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 12084832-5567-c723-2e87-aeaac920aa31
* Version Independent ID: 7620ba4b-7bbd-0c1d-882f-374b9278a315
* Content: [Index of default and system work item fields - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/work-items/guidance/work-item-field?view=azdevops)
* Content Source: [docs/boards/work-items/guidance/work-item-field.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/boards/work-items/guidance/work-item-field.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@ggrater-touchmark - Sorry for the broken link, I'll get that updated today. Meanwhile - you can reach the blog post here: https://blogs.msdn.microsoft.com/devops/2012/08/17/work-item-field-attributes-what-you-can-and-cant-change/.  The Created By field is indeed Read-only. You might consider closing the work items and then changing the state to Active or Proposed, which will update the Activated By field by the user who reactivated the work items. There is no way that I know of to update the Created By field.
