### ISSUE TITLE
Package Views?

### ISSUE THREAD

**Issue by stoopered** [MicrosoftDocs/vsts-docs#3158]
Wouldn't using a package view be another/better option? Is there a plan to make it so development teams can quickly change the source on their local machine to use a package vs needing to repoint the app a project if they want to step through and debug. If one developer is working on the package, they need to push, do a pull request, then a build must complete, before another developer can test it. It would be slick to have a "Ghost Reference" to a local project which could quickly be turned off and on that they could just pull the repo down and do testing on that specific project. And also somehow allow for easy switching of that project reference vs the nuget reference. There has got to be a quicker way to test others changes without having to wait for that package to be created. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 11ed58a1-5819-f3a4-c674-dafcdbd56fbc
* Version Independent ID: d68aca4d-3fd3-1864-09f5-6060295e0399
* Content: [Publishing to NuGet feeds - Azure Pipelines and TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/nuget?view=azdevops&tabs=yaml)
* Content Source: [docs/pipelines/artifacts/nuget.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/artifacts/nuget.md)
* Product: **devops**
* GitHub Login: @steved0x
* Microsoft Alias: **amullans**

**Comment by Izzmo** [comment]
This! Having a "dev" view and then for everything else, you just use the default or "Release" view.

**Comment by elbatk** [comment]
Hi people :) We're taking a serious look at views over in Azure Artifacts as the product evolves, this is great feedback and something we'll add to the list of considerations moving forward, keep it coming.

As for the article, it only mentions package versioning but views are a great way of testing packages/ensuring quality before releasing packages to the public.

**Comment by chasewilson** [comment]
Hi all! This looks to be aimed toward the Azure DevOps Developer Community and highly encourage you to leave feedback there! If you have any more issues with the documentation around this, feel free to open a new issue.
 Thank you all for your contributions!
