### ISSUE TITLE
Are Hosted VS2019 pools available now?

### ISSUE THREAD

**Issue by zbourdeau** [MicrosoftDocs/vsts-docs#3159]
Are Hosted VS2019 pools available now?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 99af681d-41ad-da15-0b72-08b5cd5a11ac
* Version Independent ID: 2fa0df36-a437-8cbb-b019-b49b31b1e116
* Content: [Microsoft-hosted agents for Azure Pipelines - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azdevops&tabs=yaml)
* Content Source: [docs/pipelines/agents/hosted.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/agents/hosted.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by MattDavisRM** [comment]
Maybe relevant:  https://github.com/Microsoft/azure-pipelines-image-generation/issues/268#issuecomment-459418357

**Comment by joebourneMS** [comment]
Yes, details have been added

**Comment by andyjlewis** [comment]
@joebourneMS are you able to close this issue? If not, @thomps23 should be able to get you set up to close issues in this repo

**Comment by joebourneMS** [comment]
@joebourneMS , I am not able to close issues.
