### ISSUE TITLE
Non IIS aplications

### ISSUE THREAD

**Issue by GaboFDC** [MicrosoftDocs/vsts-docs#316]
What if we want to deploy a non ISS application? just an standard .net app for desktop, could you guys provide a guide for this?
I've being searching, but I haven't found any documentation related to this.
Any example will be apretiated

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca1c5394-611b-b119-dbf3-b88404e351d5
* Version Independent ID: fcc23259-21ec-f9fa-4e25-f587e1e0f41b
* Content: [Deploy to an IIS web server on a Windows Virtual Machine | Microsoft Docs](https://docs.microsoft.com/en-us/vsts/build-release/apps/cd/deploy-webdeploy-iis-deploygroups)
* Content Source: [docs/build-release/apps/cd/deploy-webdeploy-iis-deploygroups.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/build-release/apps/cd/deploy-webdeploy-iis-deploygroups.md)
* Service: **unspecified**
* GitHub Login: @douge
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment]
Consider packaging your app during a build process (or with other tools) and then copy to the target using Windows File Copy, Copy Over SSH, or a PowerShell script in a release process. This discussion on StackOverflow might be useful: https://stackoverflow.com/questions/46154179/vsts-ci-cd-for-desktop-apps.
