### ISSUE TITLE
What does cancelTimeoutInMinutes really do?

### ISSUE THREAD

**Issue by molant** [MicrosoftDocs/vsts-docs#3160]
I'm trying to figure out what `cancelTimeoutInMinutes` does but I have no idea and even after trying it out in my configuration I don't see any change:

> The `cancelTimeoutInMinutes` allows a limit to be set for the job cancel time. When not specified, the default is 5 minutes.

Does this mean that if I stop a build the job will be canceled within 5 minutes? That if no output is on the screen for 5 minutes it will be canceled or what exactly?
I've had jobs not output anything for more than 30 minutes and the agent was only stopped after the 1h mark (even when I clicked on "Stop the build").

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cb951805-1beb-5f01-344a-8bbe96bd38f2
* Version Independent ID: 5ad8d8fa-e0eb-4f78-ba3a-c1669f7cd5ac
* Content: [Server jobs in Azure pipelines Build and Release - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/server-phases?view=azdevops&tabs=yaml)
* Content Source: [docs/pipelines/process/server-phases.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/server-phases.md)
* Product: **devops**
* GitHub Login: @alewis
* Microsoft Alias: **alewis**

**Comment by andyjlewis** [comment]
I'm sorry for the long delay in response. I was out of the office for a long period of time earlier this year. I believe the following topic is relevant, but I'm not sure that it answers your question: https://docs.microsoft.com/azure/devops/pipelines/process/phases#timeouts

**Comment by jwikman** [comment]
@andyjlewis 
> I'm sorry for the long delay in response. I was out of the office for a long period of time earlier this year. I believe the following topic is relevant, but I'm not sure that it answers your question: https://docs.microsoft.com/azure/devops/pipelines/process/phases#timeouts

But that link only points to the same fuzzy statement that @molant quotes.

I found that statement too, googled to find anything that explained it better and ended up here, point back to first place. Circle referencing ;-)

So once again, what does `cancelTimeoutInMinutes` really do?
