### ISSUE TITLE
Specify job queue timeout

### ISSUE THREAD

**Issue by sgh-msft** [MicrosoftDocs/vsts-docs#3162]
Is there an easy way to set a timeout for how long a job waits in the queue? The scenario I'm trying to fix is when the only applicable agent to run a job goes offline for an extended period of time and the entire pipeline waits forever for that job to queue instead of eventually bypassing

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 54bf6c2f-95c1-943d-26ae-d7099143bccf
* Version Independent ID: 0833bb55-1e54-6953-ee69-de6d191d2ec1
* Content: [Build and release jobs in Azure Pipelines and TFS - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/phases?view=azdevops&tabs=yaml)
* Content Source: [docs/pipelines/process/phases.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/phases.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment]
Thank you for your feedback. Does this section of the topic help: https://docs.microsoft.com/azure/devops/pipelines/process/phases#timeouts. The job should be abandoned when the timout completes. Please let us know if you are not seeing this behavior from your choice of agent. For more details about agents, see https://docs.microsoft.com/azure/devops/pipelines/agents/agents.

**Comment by alexhomer1** [comment]
OK, I'll pass this on to the product team for them to investigate further.

**Comment by RoopeshNair** [comment]
@chrisrpatterson for CI / platform queries

**Comment by chrisrpatterson** [comment]
The timeout option is for the job once it starts running.  At the moment there is no timeout option for the job sitting in the queue.

**Comment by alexhomer1** [comment]
Thank you for your feedback. I will update the related topics to include this information.

**Comment by GaTechThomas** [comment]
It appears that we're seeing jobs timeout after 30 days while waiting on approval to run on an agent for the first time. May be the same timer generally for waiting in queue? It would certainly be helpful to be able to configure these timeouts at various levels: org, project, pipeline, stage, and job.

**Comment by WilliamAntonRohm** [comment]
@GaTechThomas -- Thomas, thank you for your follow-up.  Please add your suggestion here:
- [Developer Community](https://developercommunity.visualstudio.com/search?space=21)
