### ISSUE TITLE
Does @mention work with a group of users in Azure DevOps?

### ISSUE THREAD

**Issue by denhsu** [MicrosoftDocs/vsts-docs#3165]
for example, can we do @[Cloud]\Cloud Operation team

it is a team in Cloud - Azure DevOps project.
Thanks,
Dennis

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 34ae521f-6ae4-4d7f-2cce-f844e5811b66
* Version Independent ID: 18098490-1f34-e966-3135-cb90197bfa6f
* Content: [Use @mentions in work items and pull requests - Azure DevOps Services & TFS](https://docs.microsoft.com/en-us/azure/devops/notifications/at-mentions?view=azdevops)
* Content Source: [docs/notifications/at-mentions.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/notifications/at-mentions.md)
* Product: **devops**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by denhsu** [comment]
Hi Please close it.

I realize you can update Delivery setting in Team Notification section and send to a distributed email list or send to everyone in the team.

Thanks,
Dennis

**Comment by chcomley** [comment]
@denhsu No problem. Please let us know if you have any other questions. Thanks!
