### ISSUE TITLE
Missing example on Logging

### ISSUE THREAD

**Issue by patware** [MicrosoftDocs/vsts-docs#3167]
Please provide an example of how to write Diagnostics information.

What WriteLine do I use in Code? Debug.WriteLine, Debugger.WriteLine, Console.WriteLine, TestContext.WriteLine or Trace.WriteLine ?

Is a runSettings necessary ?  If so, what do enter and where ?  &lt;CaptureTraceOutput/&gt; has a default of True.

In the VsTest Task, if there's a runSettings involved, it must be specified in the "Settings file", but is there anything else?  does the variable System.Debug have an impact on the "logging" ?

When the build is done, where to look ?  Should the messages appear in the Build result&gt;Logs ?  

In the Build result&gt;Tests, under the UnitTest in question: Under Debug, should there be something an entry ?  

Confusing

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 16bd8dd1-7650-8c18-2553-38a8bc54e892
* Version Independent ID: f9fa517a-7adc-e327-d12e-256295a1ed52
* Content: [Visual Studio Test task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/test/vstest?view=azdevops&viewFallbackFrom=vsts)
* Content Source: [docs/pipelines/tasks/test/vstest.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/test/vstest.md)
* Product: **devops**
* GitHub Login: @steved0x
* Microsoft Alias: **dastahel**

**Comment by PBoraMSFT** [comment]
@patware - any of Console.WriteLine, TestContext.WriteLine or Trace.WriteLine should work. Output is made available as an attachment to the test. You can find them in the 'attachments' section for a failing test in the 'Test' tab of a build/release. Here's a screenshot

![image](https://user-images.githubusercontent.com/23308203/52275656-2da24600-2976-11e9-85a8-6b8e539bc301.png)

If the test passed, these details are not available. There's no need for specifying runsettings to make this work. 
System.Debug does not have an impact on this. System.Debug causes tasks to produce verbose output but does not impact the test output itself.
Hope this helps and unblocks you for now. 
Will look into adding this to an appropriate doc.

**Comment by PBoraMSFT** [comment]
@alexhomer1 - sent you the details of how to address this ask. Please address in the docs and close this issue when done.

**Comment by alexhomer1** [comment]
Thank you for your feedback. I will update the topic to include your recommendations.
