### ISSUE TITLE
SSH Key formats

### ISSUE THREAD

**Issue by danpetitt** [MicrosoftDocs/vsts-docs#3169]
What formats are supported as whatever i try it says:
"Error: Cannot parse privateKey: Unsupported key format."

I have tried RSA2048 and ED25519

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 89132320-da86-8a4e-4468-cf651561892c
* Version Independent ID: 4946284d-9666-4a15-9e03-72377693ecb0
* Content: [Copy Files Over SSH task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/copy-files-over-ssh?view=azdevops#is-this-task-supported-for-target-machines-running-operating-systems-other-than-linux)
* Content Source: [docs/pipelines/tasks/deploy/copy-files-over-ssh.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/deploy/copy-files-over-ssh.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment]
Thank you for your feedback. I assume you are using a SSH Service Connection created within Azure DevOps or TFS, and providing an SSH private key in the Service Connection dialog. If this is the case, and the key is giving an error, you may find some help at https://www.ssh.com/ssh/public-key-authentication. Meanwhile, I have passed your question on to the product team who may be able to provide additional information to resolve your issue.

**Comment by danpetitt** [comment]
Yes I am trying to copy some build artifacts to our SSH server; I can connect to it from FileZilla using the same private key file, but Azure always fails.

Unfortunately that link doesnt help as to what private key formats, encryption and other settings your DevOps Task supports; as it seems to have some undocumented restrictions.

**Comment by nschonni** [comment]
The actual task is here https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks/CopyFilesOverSSHV0 if you want to dig in the code (but that doesn't fix the documentation part)

**Comment by lkillgore** [comment]
Hi @danpetitt, the task is using the `ssh2-streams` node library.  Their documentation is [here](https://github.com/mscdex/ssh2-streams), and if I'm not mistaken, your failure is logged [here](https://github.com/mscdex/ssh2-streams/blob/master/lib/keyParser.js#L1367).

FWIW, the CopyFilesOverSSH task recently updated the version of the library used, and will be rolling out to production end of February - beginning of March timeframe.

**Comment by danpetitt** [comment]
Thanks; yeah I looked at the source of the task and noted this library so I was going to debug it; but lost the incentive atm. I will return to it again later

**Comment by benydc** [comment]
I confirm the updated version of the ssh2 library used works, I used the parseKey util. Tested the parseKey on older version of the library and it failed, going to debug further why...

**Comment by joshmgross** [comment]
The CopyFilesOverSSH task uses the `ssh2` node library [here](https://github.com/mscdex/ssh2), which did not add support for the newer OpenSSH key format until version v0.7.0. (See this issue for more info: https://github.com/mscdex/ssh2/issues/746)

The task version 0.148 update will have v0.8 of the `ssh2` library and support for the new OpenSSH key format. Prior to that task version, the `-m PEM` flag must be passed to `ssh-keygen` so that the key works with the task.

The newer version of the task should be rolling out in the next few weeks.

I will update the documentation with this information.

**Comment by DavidStaheli** [comment]
The documentation has been updated and should be live in production within 24 hours.
