### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by softwarecraft** [MicrosoftDocs/vsts-docs#3170]
In intro section link for "Feature matrix" https://visualstudio.microsoft.com/vsts/compare-features/ is broken in sentence "For a comparison chart of Stakeholder versus Basic access, see the Feature matrix."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a35602ee-9d11-9746-4b79-075e295a5fb8
* Version Independent ID: dbea8e30-e80b-8f13-987e-ef0ad3ba9b83
* Content: [Default permissions and access quick reference - Azure DevOps & TFS](https://docs.microsoft.com/en-us/azure/devops/organizations/security/permissions-access?view=azdevops)
* Content Source: [docs/organizations/security/permissions-access.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/security/permissions-access.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by softwarecraft** [comment]
Is correct link possibly [https://azure.microsoft.com/en-ca/services/devops/compare-features/](https://azure.microsoft.com/en-ca/services/devops/compare-features/) ?

**Comment by KathrynEE** [comment]
@softwarecraft - Thank you for the feedback. I'll update the topic later today. For now, the correct URL is https://azure.microsoft.com/en-us/services/devops/compare-features/.
