### ISSUE TITLE
Need more explanations on licensing details between Azure Test Plans and Test Manager extension

### ISSUE THREAD

**Issue by justinyoo** [MicrosoftDocs/vsts-docs#3176]
According to this [this document](https://azure.microsoft.com/en-us/services/devops/compare-features/), a Basic access-level user can use Azure Test Plans. However, the [Azure Pricing Calculator](https://azure.microsoft.com/en-au/pricing/calculator/?service=azure-devops) says, in order to use Azure Test Plans, it requires an extra license.

First 5 Basic access-level users are free to use Azure Artifacts, but not Azure Test Plans, according to the pricing calculator. Is this correct?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c8e2cb79-709d-972b-6747-6d26c965fb2a
* Version Independent ID: d512ea69-a97a-e5ff-a804-6691c5dfe1e6
* Content: [Create test plans and suites - Azure Test Plans](https://docs.microsoft.com/en-us/azure/devops/test/create-a-test-plan?view=azdevops)
* Content Source: [docs/test/create-a-test-plan.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/test/create-a-test-plan.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment]
Thank you for your feedback. I will update the topic with the latest information:

Visual Studio Enterprise, Visual Studio Test Professional, and MSDN Platforms subscribers have access to use this extension. These users do not require an additional license, and can acquire this extension on their organization or collection for free (see Compare Visual Studio subscriptions https://www.visualstudio.com/vs/pricing for details).

Non-subscribers must purchase licenses to use this extension. This can be for any specified number of users.

Notes:

    Manual testers do not need this extension and can execute tests as a Basic user in an Azure DevOps organization or collection.

    This extension cannot be assigned to Stakeholders.

    Licenses for this extension also gives users rights to use Microsoft Test Manager (a deprecated on-premises client).
