### ISSUE TITLE
"Review FIPS" is confusing + formatting wrong

### ISSUE THREAD

**Issue by Styxxy** [MicrosoftDocs/vsts-docs#3181]
The "Review FIPS" part is quite confusing. When would the error occur? Do we need to check this by default? How we check this by default?

Also the formatting of the exception info is not well.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f96caf4e-05c3-53e5-c1f6-3b24a95dac70
* Version Independent ID: 190fa3f7-dbba-315a-56bc-dc9f15355188
* Content: [Change the maximum attachment size for work items - TFS](https://docs.microsoft.com/en-us/azure/devops/reference/xml/change-maximum-attachment-size-work-items?toc=/azure/devops/reference/toc.json&bc=/azure/devops/reference/breadcrumb/toc.json&view=tfs-2018)
* Content Source: [docs/reference/xml/change-maximum-attachment-size-work-items.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/reference/xml/change-maximum-attachment-size-work-items.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@Styxxy - Thank you for the feedback. I'm updating the article to format it better and clarify that you only need to review the FIPS content should you receive an exception similar to the one listed.
