### ISSUE TITLE
How do I use custom variables to prompt for values during the execution of a release?

### ISSUE THREAD

**Issue by midgleyc** [MicrosoftDocs/vsts-docs#3182]
Midway down the page there is the line

&gt; You can use custom variables to prompt for values during the execution of a release. For more details, see Approvals.

I couldn't see anything in the linked page that gives more details. Where do I specify variables that I'd like an approver to give the value of?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 611642f0-881f-10b9-ae94-3c562001d1f0
* Version Independent ID: 41efb94b-4c7a-64a3-b23b-70c8634ae727
* Content: [Release variables  and debugging - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/variables?view=azdevops&viewFallbackFrom=vsts&tabs=batch)
* Content Source: [docs/pipelines/release/variables.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/release/variables.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment]
Thank you for your feedback. This topic: https://docs.microsoft.com/en-us/azure/devops/pipelines/release/variables?view=azure-devops&tabs=batch#using-default-variables shows how to use variables in your tasks, and this topic: https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/manual-intervention?view=azure-devops shows how to use variables in a Manual Intervention task. Define varaible in the "Variables" tab of your pipeline, or use Variable Groups (described here: https://docs.microsoft.com/en-us/azure/devops/pipelines/library/variable-groups?view=azure-devops).
