### ISSUE TITLE
Desktop application UI testing

### ISSUE THREAD

**Issue by rolfik** [MicrosoftDocs/vsts-docs#3183]
It would be nice to write about current desktop (Windows) applications (using WPF, UWP, ...) UI testing, because this page covers only web applications.
Frameworks like Appium and others could be described.

Thank you
Marek Istvanek

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 09e51d18-72ec-1ad4-9ae7-8185c8e1dcd6
* Version Independent ID: 9f2f0471-d123-8e95-1606-cd811d1ece9a
* Content: [Perform UI tests with Selenium - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/test/continuous-test-selenium?view=azdevops)
* Content Source: [docs/pipelines/test/continuous-test-selenium.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/test/continuous-test-selenium.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment]
Thank you for your feedback. I have passed this comment on to the product team for advice, and I will add related topics they recommend.
