### ISSUE TITLE
Need to highlight that the users/groups that are assigned as approvers need "View Releases" permission 

### ISSUE THREAD

**Issue by dburnison** [MicrosoftDocs/vsts-docs#3185]
Had a customer report that users were getting the following error: 
VS402904: Access denied: User Doe, John does not have view releases permission. Contact your release manager.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fc105eb0-4766-77a1-dfec-c0cc2b4b3f08
* Version Independent ID: 8bd8c066-745b-5c89-39c3-bb0a959cb7a2
* Content: [Control deployments by using approvals - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/approvals/approvals?view=tfs-2018)
* Content Source: [docs/pipelines/release/approvals/approvals.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/release/approvals/approvals.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment]
Thank you for your feedback. I will update the topic to include your recommendations.
