### ISSUE TITLE
Force inline script to always log contents?

### ISSUE THREAD

**Issue by mchelen** [MicrosoftDocs/vsts-docs#3186]
When using an inline script the actual commands are only shown sometimes?

For example the logs for this task:
```yaml
- script: |
    echo "hello world"
```
Would show:
```
2019-01-30T20:53:37.4128279Z Generating script.
2019-01-30T20:53:37.4144502Z Script contents:
2019-01-30T20:53:37.4145166Z echo "hello world"
```

Whereas this task:
```yaml
- script: |
    echo "hello"
    echo "world"
```

Would be logged as:
```
2019-01-30T20:52:29.8966200Z Generating script.
2019-01-30T20:52:29.9008810Z [command]/bin/bash --noprofile --norc /home/vsts/work/_temp/5f705bd0-5f9f-4946-b2cd-6cd611c1f1a1.sh
```

The second log format makes it difficult to understand when reading the logs.
Is there any way to force it to always output the script contents?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 450ac349-5c33-6cdf-1ecd-6eb989a00334
* Version Independent ID: a7119c1a-59b2-3081-a241-e93aa0d6b4b9
* Content: [Bash task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/bash?view=azdevops)
* Content Source: [docs/pipelines/tasks/utility/bash.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/utility/bash.md)
* Product: **devops**
* GitHub Login: @steved0x
* Microsoft Alias: **dastahel**

**Comment by vtbassmatt** [comment]
Moved to the tasks repo: https://github.com/Microsoft/azure-pipelines-tasks/issues/9505
