### ISSUE TITLE
The installation for Sharepoint 2013 not tested on fresh Windows Server 2016 Update 1

### ISSUE THREAD

**Issue by kraftc** [MicrosoftDocs/vsts-docs#319]
The installation for Sharepoint 2013 prerequisites will not complete successfully on a fresh Windows Server2016 Update 1 machine, because it requires the ApplicationServer role, which does not exist.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 566a65f6-a86a-4b99-cb54-3efef5f20254
* Version Independent ID: 9b5e0c05-f601-c4a0-d4b6-a77e8ccbe86c
* Content: [Configure SharePoint integration - TFS | Microsoft Docs](https://docs.microsoft.com/en-us/vsts/report/sharepoint-dashboards/configure-sharepoint-tfs-2017-earlier)
* Content Source: [docs/report/sharepoint-dashboards/configure-sharepoint-tfs-2017-earlier.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/report/sharepoint-dashboards/configure-sharepoint-tfs-2017-earlier.md)
* Service: **unspecified**
* GitHub Login: @douge
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@kraftc - Thank you for your inquiry.  Reviewing [Sharepoint 2013 requirements](https://docs.microsoft.com/en-us/sharepoint/install/hardware-and-software-requirements-0) indicates that Windows Server 2016 RTM is not supported.
