### ISSUE TITLE
Promote folder to page?

### ISSUE THREAD

**Issue by assofohdz** [MicrosoftDocs/vsts-docs#3190]
How do we promote a folder to a page  ? This page is referenced when I view a folder in the Wiki, but I can't seem to figure it out...

---
#### Dokumentoplysninger

⚠ *Undlad at redigere denne sektion. Det er påkrævet til docs.microsoft.com ➟ GitHub-problemlinkning.*

* ID: 8d4fe5c7-0ab6-a0e4-4a6e-f98d0355f49a
* Version Independent ID: ce022fef-054d-cdc2-43e9-a8ee3b8fb592
* Content: [PublishMarkdown files from a Git repository to a wiki in Azure DevOps - Azure DevOps](https://docs.microsoft.com/da-dk/azure/devops/project/wiki/publish-repo-to-wiki?view=azdevops&viewFallbackFrom=vsts&tabs=new-nav)
* Content Source: [docs/project/wiki/publish-repo-to-wiki.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/project/wiki/publish-repo-to-wiki.md)
* Product: **devops**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @assofohdz, thanks for reaching out. I'll be back to you soon with some clarity on this. Thanks!

**Comment by chcomley** [comment]
Hi @assofohdz, For a folder to be a page as well, there should be a markdown file with the same name as the folder as a sibling to the folder, meaning both the folder and the md file of the same name should lie next to each other. Does this help? I'm going to close this issue, however please let me know if I can help clarify things further.
