### ISSUE TITLE
Equivalent of Microsoft.TeamFoundationServer.Client/IIdentityManagementService on new Rest APIS

### ISSUE THREAD

**Issue by arvinatwork** [MicrosoftDocs/vsts-docs#3194]
I can't seem to find the rest api for the function that is handled before by Microsoft.TeamFoundationServer.Client/IIdentityManagementService. Basically I want to update the project's permission sets via the new Rest Apis

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 413163f0-28c3-a2a7-d626-fcb81bcb2257
* Version Independent ID: 57c127da-2b1e-d29e-9abb-a3c258762ccf
* Content: [.NET Client Libraries for Azure DevOps Services (and TFS)](https://docs.microsoft.com/en-us/azure/devops/integrate/concepts/dotnet-client-libraries?view=azdevops)
* Content Source: [docs/integrate/concepts/dotnet-client-libraries.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/integrate/concepts/dotnet-client-libraries.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by chcomley** [comment]
Hi @arvinatwork, I'm following up on this issue from long ago - did you figure this out, or should I look into this further? Please let me know, otherwise I'll close this issue. Thank you!

**Comment by chcomley** [comment]
Hi @arvinatwork, I've determined that we don't have an API for Microsoft.TeamFoundationServer.Client/IIdentityManagementService. You'll need to continue to user the client dll. If you want to provide product feedback or make a feature request, please go here: https://developercommunity.visualstudio.com/content/problem/post.html?space=21. Thanks!
