### ISSUE TITLE
Docker Run Arguments/ Docker Run do not support --network

### ISSUE THREAD

**Issue by arag0n** [MicrosoftDocs/vsts-docs#3197]
Arguments field is ignored by docker run. There is no way to define the --network argument

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d9dbf88-7e55-d427-145e-d36b04fb197f
* Version Independent ID: a3f30c00-817c-9c05-7a57-3f2bf618821e
* Content: [Docker task - Azure Pipelines & TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/docker?view=azdevops#run-command)
* Content Source: [docs/pipelines/tasks/build/docker.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/build/docker.md)
* Product: **devops**
* GitHub Login: @steved0x
* Microsoft Alias: **dastahel**

**Comment by shashankbarsin** [comment]
Closing this issue as it is not related to the documentation but the task. Related issue exists in azure-pipeline-tasks repo

https://github.com/Microsoft/azure-pipelines-tasks/issues/9034
