### ISSUE TITLE
Cannot get this to work.

### ISSUE THREAD

**Issue by okiedude** [MicrosoftDocs/vsts-docs#3199]
I have Visual Studio installed, and the Team Foundation add-in appears in both MSP Pro 2016 and MS Excel. The Excel integration with Azure DevOps works flawlessly. However, every time I try to connect  to DevOps from MSP Pro 2016, I get error TF80070 "Team Foundation encountered an error while performing the operation. It is recommended that you save your work and restart the application."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4f6edd47-46d7-ab0d-db47-d73bc45d6b43
* Version Independent ID: 6ac2ae49-0bd0-2c28-fc87-7f034dd96443
* Content: [Create your backlog and tasks using Project - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/backlogs/office/create-your-backlog-tasks-using-project?view=azdevops&tabs=office-2007)
* Content Source: [docs/boards/backlogs/office/create-your-backlog-tasks-using-project.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/boards/backlogs/office/create-your-backlog-tasks-using-project.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by okiedude** [comment]
My steps to re-create this are to open MSP Pro on my computer (not Project Server) > Start with a Blank project > Switch to Task Sheet view > Go to Team ribbon and click "Choose Team Project" > click on desired project, and then I receive the above error.

**Comment by okiedude** [comment]
Welp, it started working after a re-install of MS Project Pro 2016.

**Comment by steved0x** [comment]
@okiedude Glad you got it working, I'm assigning this to the author of the article for review before closing the issue.

**Comment by KathrynEE** [comment]
@okiedude - Thank you for your inquiry, and glad you were able to get it to work. Please note that starting with Visual Studio 2019, the Team Foundation plug-in for Office is deprecating support for Office Project. You will be able to continue to use Office Excel.

**Comment by okiedude** [comment]
Yeah, I picked up on that during my research, which I find very
unfortunate. I will probably have to revert to using MS Project exclusively
if/when that occurs.

VSTS / Azure DevOps is very lacking in long-term planning capabilities.

Cheers though, and thanks for the note.

Andy
