### ISSUE TITLE
Single or double quote in cross job variable syntax

### ISSUE THREAD

**Issue by sysofwan** [MicrosoftDocs/vsts-docs#3200]
Please clarify the syntax for `$[]` syntax for cross job variables. I tried using double quotes instead of single quotes in the syntax (i.e. `myVarFromJobA: $[ dependencies.A.outputs["setvarStep.myOutputVar"] ]`, and the pipeline failed with an unknown error. Can you support both single and double quotes or be clear that the requirement need to be double quote in the docs? This is important because it is easier to mix double and single quotes rather than figuring out how to escape them in yaml.

**Comment by sysofwan** [comment]
This is for the variables [varaibles](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch) docs.

**Comment by alexhomer1** [comment]
Thank you for your feedback. I have passed this on to the product team for advice and I will update the topic to include their recommendation.

**Comment by vtbassmatt** [comment]
We only accept single quotes. I'll make that more clear.
