### ISSUE TITLE
Missing URLs

### ISSUE THREAD

**Issue by anmason** [MicrosoftDocs/vsts-docs#3201]
This document is missing the dev.azure.com URLs, as well as some IPs listed in this doc: https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/v2-windows?view=azure-devops#q--a

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e191f4bf-deef-1c48-aaa7-db424c322ae3
* Version Independent ID: 866d576f-77e4-1fc4-d4db-484628e0b518
* Content: [Troubleshoot network connections and whitelist addresses](https://docs.microsoft.com/en-us/azure/devops/organizations/security/faq-network-connections?view=azdevops)
* Content Source: [docs/organizations/security/faq-network-connections.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/security/faq-network-connections.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by chcomley** [comment]
@anmason, Thanks so much for the heads up. I've submitted a PR, which is under review. The updates should be live within the next day or so. Thanks again!
