### ISSUE TITLE
TestContext is only available for MSTest

### ISSUE THREAD

**Issue by SabotageAndi** [MicrosoftDocs/vsts-docs#3205]
The TestContext class of the first example is only available for MSTest. 
But there is no info about this. People who use XUnit or NUnit can't to this.

Please add the info or add examples for XUnit and NUnit. Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 300d9b37-13c9-a249-451e-1d1340c1b5ff
* Version Independent ID: 68c63219-bd8a-42d2-8dce-940b64efe199
* Content: [Collect screenshots, video, logs, and attachments - Azure Test Plans](https://docs.microsoft.com/en-us/azure/devops/test/collect-screenshots-and-video?view=azure-devops&viewFallbackFrom=vsts)
* Content Source: [docs/test/collect-screenshots-and-video.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/test/collect-screenshots-and-video.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment]
Thank you for your feedback. I will update the topic to make this clear, and arrange with the product team for additional examples to be added.

**Comment by jeffreypalermo** [comment]
This does work with NUnit.  And the attachments get uploaded. Why does this say that it doesn't work with NUnit. I'm using this feature successfully with NUnit - which is great!

**Comment by SabotageAndi** [comment]
MSTest and NUnit have both TestContext classes, but they have different methods.

NUnit: https://github.com/nunit/docs/wiki/TestContext
MSTest: https://docs.microsoft.com/en-us/dotnet/api/microsoft.visualstudio.testtools.unittesting.testcontext?view=mstest-net-1.2.0

In NUnit the class has a lot of static methods. In MSTest you have to get an instance via property injection.
