### ISSUE TITLE
Update counter only on master branch

### ISSUE THREAD

**Issue by psandhu79** [MicrosoftDocs/vsts-docs#3206]
The counter is really good, however I would like it to update only if the build is running on the master branch. Ignore all pull request and feature branch builds

**Comment by steved0x** [comment]
@psandhu79 Thank you for the feedback. Can you let me know which article this feedback is for, so I can assign it to the author? You can reply here with the URL of the topic, or you can create a new issue by browsing to the topic on docs.microsoft.com and choosing **Content feedback** at the bottom. 

![image](https://user-images.githubusercontent.com/1580889/51848491-af95cd80-22eb-11e9-81a2-1680fc40caf9.png)

If this is something that we can change in the documentation we'll take a look, but if it is a feature request, you'll need to file a separate issue for that.

To submit product feedback, such as bug reports or feature requests, please choose **Product feedback** at the bottom of the article:

![image](https://user-images.githubusercontent.com/1580889/51848904-90e40680-22ec-11e9-893f-ded2716f3ea2.png)

or you can file an issue directly at https://developercommunity.visualstudio.com/spaces/21/index.html

**Comment by psandhu79** [comment]
HI

The URL is

https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?tabs=yaml%2Cbatch&view=azure-devops

Pod

**Comment by steved0x** [comment]
@psandhu79 Thank you, I am assigning this to the writer for Variables.

**Comment by alexhomer1** [comment]
Thank you for your feedback. We are unable to provide assistance with specific programming issues. You would need to create custom scripts to perform the task you require. You may be able to get assistance from the Azure DevOps Developer Community website at https://developercommunity.visualstudio.com/spaces/21/index.html, or from another site such as https://stackoverflow.com.
