### ISSUE TITLE
Invalid results file after running ordered test

### ISSUE THREAD

**Issue by B-Raya** [MicrosoftDocs/vsts-docs#3208]
I am running ordered test  on remote machine using Visual Studio test runner in my CD(release) pipeline.  Please find the details of the version below:

Task         : Visual Studio Test
Description  : Run tests with Visual Studio test runner
Version      : 2.0.55
Author       : Microsoft Corporation

The ordered test runs with out any issue and it logs how may tests in the ordered test passed/failed etc. 
However the test tab doesn't show any details of the test execution. 
This is command which is getting executed:
c:\agent\TestPlatform\vstest.console.exe C:\agent\_work\r1\a\SmokeTestSuite.orderedtest /logger:trx "/TestAdapterPath:\"C:\agent\_work\r1\a\"" /platform:x64

I am seeing the below  warning in the log after the executing of the ordered test:
##[warning]Invalid results file. Make sure the result format of the file 'C:\agent\_work\r1\a\TestResults\SupportUser_FP_ACCEPT01_2019-02-01_09_52_53.trx' matches 'VSTest' test results format.

I am not sure how to fix this. Any help will be appreciated. 

Thanks...

**Comment by PBoraMSFT** [comment]
@B-Raya - The thread has been inactive for more than 90 days now. We are closing this issue.

If this issue is persisting for you, please open this issue on the [tasks repo](https://github.com/Microsoft/azure-pipelines-tasks) for our engg. team to take a look and help with the next steps.
