### ISSUE TITLE
PowerShell version

### ISSUE THREAD

**Issue by manuelcanepa** [MicrosoftDocs/vsts-docs#3209]
I cant deploy on a VM on Azure because PowerShell version is 2.0, and Continuos Integration need PS 3.0. How can i update powershell or fix this issue?

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: ca1c5394-611b-b119-dbf3-b88404e351d5
* Version Independent ID: fcc23259-21ec-f9fa-4e25-f587e1e0f41b
* Content: [Deploy to IIS on a Windows VM - Azure Pipelines](https://docs.microsoft.com/es-es/azure/devops/pipelines/apps/cd/deploy-webdeploy-iis-deploygroups?view=azure-devops)
* Content Source: [docs/pipelines/apps/cd/deploy-webdeploy-iis-deploygroups.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/apps/cd/deploy-webdeploy-iis-deploygroups.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment]
Thank you for your feedback. I have passed this on to the product team for advice and I will update the topic to include their recommendation.

**Comment by RoopeshNair** [comment]
@manuelcanepa - update the VM with WMF 5.0 or later?
