### ISSUE TITLE
XPath syntax is wrong, test won't run

### ISSUE THREAD

**Issue by search8** [MicrosoftDocs/vsts-docs#321]
Since I'm new to selenium it took me quite some time to figure this out. Instead of //ol[@id='b_results']/li/h2/a/strong[3] it should be (//ol[@id='b_results']/li/h2/a/strong)[3]

Also, if you're running IE 11 (which we currently are) you have to add the following registry key.

For IE 11 only, you will need to set a registry entry on the target computer so that the driver can maintain a connection to the instance of Internet Explorer it creates. For 32-bit Windows installations, the key you must examine in the registry editor is HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Internet Explorer\Main\FeatureControl\FEATURE_BFCACHE. For 64-bit Windows installations, the key is HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\Internet Explorer\Main\FeatureControl\FEATURE_BFCACHE. Please note that the FEATURE_BFCACHE subkey may or may not be present, and should be created if it is not present. Important: Inside this key, create a DWORD value named iexplore.exe with the value of 0.

https://github.com/SeleniumHQ/selenium/wiki/InternetExplorerDriver

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 09e51d18-72ec-1ad4-9ae7-8185c8e1dcd6
* Version Independent ID: 9f2f0471-d123-8e95-1606-cd811d1ece9a
* Content: [Selenium testing in VSTS | Microsoft Docs](https://docs.microsoft.com/en-us/vsts/build-release/test/continuous-test-selenium)
* Content Source: [docs/build-release/test/continuous-test-selenium.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/build-release/test/continuous-test-selenium.md)
* Service: **unspecified**
* GitHub Login: @douge
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment]
Thank you for your feedback. I have passed it onto the product team so that they can update the documentation.
