### ISSUE TITLE
Update with newer screenshot

### ISSUE THREAD

**Issue by ravensorb** [MicrosoftDocs/vsts-docs#3213]
It looks like the information in this article is a little outdated.  Are there any plans to update the process and screenshots?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 90db6e4c-6240-fe2e-3043-0a7d186b9ca7
* Version Independent ID: a62ec500-3330-e28a-8019-118a3b9e261f
* Content: [Service Endpoints](https://docs.microsoft.com/en-us/azure/devops/extend/develop/service-endpoints?view=azure-devops)
* Content Source: [docs/extend/develop/service-endpoints.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/extend/develop/service-endpoints.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by chcomley** [comment]
Hi @ravensorb, It's only been over a year since you created this issue. We dropped the ball on getting back to you, please accept our apology. However, the extension articles will be updated within the new quarter or two. Good news! Thanks for your feedback.

**Comment by SychevIgor** [comment]
@chcomley screenshots are still not updated. Today is November. this screen if from VSTS (rebranded in 2018) 
![image](https://user-images.githubusercontent.com/578954/98926321-33807000-24e8-11eb-8f6e-ce2a8d025a83.png)

**Comment by chcomley** [comment]
@SychevIgor thanks for your feedback. I've removed the outdated image. We're working towards allocating some resources for updating this documentation set. In the future, I invite you to consider contributing to our docs! If you're interested, please see our [Contributor guide](https://docs.microsoft.com/en-us/contribute/) for a quick ramp up. Thank you and hope you have a great day.
