### ISSUE TITLE
Documentation about ad hoc templates

### ISSUE THREAD

**Issue by m0mk** [MicrosoftDocs/vsts-docs#3216]
There used to be a page here about Ad hoc (vs. managed) templates - where you can pre-populate new work item attributes by passing them in the URL via the query string (for example by appending something like /_workItems/create/Bug?&%5BSystem.Title%5D=%5BPerformance%5D), but it isn't available anymore (or I can't find it through search) - can someone please either:
* Point us to the existing article by cross-referencing it in the Related articles section, or
* Locate the old one, re-publish it and cross-link, or
* Writing a new one, and cross-linking it?

+ Bonus points for letting search results show up for ad hoc (spelled as two words; not one)

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 47213512-6329-54d7-2a27-5d06a5e56549
* Version Independent ID: 5dbf0ad2-1ed9-c5b2-c303-779ccc94b3c7
* Content: [Perform adhoc searches for quick queries - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/queries/search-box-queries?view=azure-devops&tabs=new-nav#feedback)
* Content Source: [docs/boards/queries/search-box-queries.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/boards/queries/search-box-queries.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@m0mk - Thank you for the feedback. I'll update the content per your suggestions. Meanwhile, I believe what you're looking for is documented here, [for TFS 2013 and TFS 2015](https://docs.microsoft.com/en-ca/azure/devops/boards/backlogs/work-item-template?toc=%2Fazure%2Fdevops%2Fboards%2Fwork-items%2Ftoc.json&bc=%2Fazure%2Fdevops%2Fboards%2Fwork-items%2Fbreadcrumb%2Ftoc.json&view=tfs-2015&tabs=browser#capture-a-work-item-as-a-template). I will make clear that this is available for all versions of Azure DevOps.
