### ISSUE TITLE
Something wrong in Common tasks

### ISSUE THREAD

**Issue by kozhemyak** [MicrosoftDocs/vsts-docs#3218]
&lt;th ="col-md-8"&gt;Areas &lt;th ="col-md-8"&gt;

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 187a9dcb-5ff8-ac7e-9fa0-61420025811d
* Version Independent ID: a1b238a5-f0ec-9d08-14a9-7b0034ba32b9
* Content: [Git | REST API Reference for Team Foundation Server](https://docs.microsoft.com/en-us/azure/devops/integrate/previous-apis/git/overview?view=tfs-2017)
* Content Source: [docs/integrate/previous-apis/git/overview.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/integrate/previous-apis/git/overview.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by steved0x** [comment]
@kozhemyak Thank you for the feedback, I have passed it along, but it looks like some of your feedback may have been clipped. All I can see is this:

![image](https://user-images.githubusercontent.com/1580889/52227604-fd777c00-287d-11e9-9f21-42a3c8b1698f.png)

Can you provide more details as to how we should apply that feedback?

**Comment by kozhemyak** [comment]
Of course! I am sorry, but i see this message on the page between the title "Common tasks" and link "Git Repositories".

**Comment by kozhemyak** [comment]
The issue is closed by pull request #5116
