### ISSUE TITLE
Is it Agent.MachineName or Agent.ComputerName

### ISSUE THREAD

**Issue by mstaessen** [MicrosoftDocs/vsts-docs#3224]
When I add a demand for Agent.MachineName on TFS2017 (onprem) I get an error that there are no agents for the given demand, but if I use Agent.ComputerName, it works.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ffebdc8-521c-44b5-cde4-4abdc1bd6f18
* Version Independent ID: dc0effda-6d93-62aa-64c5-4e6f283b0826
* Content: [Predefined build variables - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops)
* Content Source: [docs/pipelines/build/variables.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/build/variables.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by alexhomer1** [comment]
Thank you for your feedback. I will update the topic to include your recommendations.

**Comment by edrandall** [comment]
This should be re-opened because the documentation still contains similar errors - #9707
