### ISSUE TITLE
Error reporting guidelines

### ISSUE THREAD

**Issue by rainersigwald** [MicrosoftDocs/vsts-docs#3225]
It would be nice to see some guidelines about "how to write a good script to run in the build", specifically with regard to error handling.

How can I ensure that a descriptive error shows up in the summary when my script fails? Is it sufficient to write to standard error? Must I use the `##vso[task.issue type=error;]` syntax?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 96dafbb6-b4ba-d4ab-7468-55e6df71b5e1
* Version Independent ID: 634b0719-9641-59fd-9f6f-f3a2082f9b39
* Content: [Batch Script task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/batch-script?view=azure-devops)
* Content Source: [docs/pipelines/tasks/utility/batch-script.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/utility/batch-script.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by vtbassmatt** [comment]
Finally got the [logging commands](https://docs.microsoft.com/en-us/azure/devops/pipelines/scripts/logging-commands?view=azure-devops&tabs=bash) doc'd.
