### ISSUE TITLE
Unable to use AzurePowerShell@4

### ISSUE THREAD

**Issue by rstra** [MicrosoftDocs/vsts-docs#3227]
Every time I try to use v4 I get the following error: `An error occurred while loading the YAML build pipeline. wrong number of segments`
When I change it to v3 it will run. I am using the VS2017 hosted image in Azure Devops. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fb215324-b1a0-93b5-5022-4bcc7da93bb7
* Version Independent ID: 9eb2977b-ac34-9d53-670e-04fa027bc8e4
* Content: [Azure PowerShell task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-powershell?view=azure-devops&viewFallbackFrom=vsts)
* Content Source: [docs/pipelines/tasks/deploy/azure-powershell.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/deploy/azure-powershell.md)
* Product: **devops**
* GitHub Login: @steved0x
* Microsoft Alias: **dastahel**

**Comment by vtbassmatt** [comment]
This belongs to @kmkumaran but for some reason I can't assign to him.

**Comment by rstra** [comment]
@vtbassmatt Do you know when version 4 will be able to be used on the hosted images?

**Comment by vtbassmatt** [comment]
I don't. @kmkumaran ?

**Comment by kmkumaran** [comment]
Since this is task related functional issue (and not doc related), can you report this in https://github.com/Microsoft/azure-pipelines-tasks and assign this on me. When you open the issue please enable system.debug to true and share the logs. That will help us debug this.

**Comment by leonfs** [comment]
I've been experiencing the same problem. @kmkumaran with regards to the logs, there are no logs. It fails before executing the job. 

![image](https://user-images.githubusercontent.com/654615/52583664-0c36d380-2e28-11e9-9e7e-17e2985e2004.png)

**Comment by kmkumaran** [comment]
@leonfs - Is this seen with AzurePowershell@4 task version? If so, we haven't shipped the version 4 yet.
https://github.com/Microsoft/azure-pipelines-tasks/issues/9524#issuecomment-461832489 

If you are noticing this when used with a different task, please provide those details. You can open a issue in https://github.com/Microsoft/azure-pipelines-tasks repo with those details.

**Comment by leonfs** [comment]
@kmkumaran - Yes, this was seen when using V4 of the task. I was just following the published documentation. Maybe adding a comment to the docs would help, or keep it at v3 (the one I'm currently using) until v4 is released.

**Comment by kmkumaran** [comment]
Thanks for letting us know @leonfs , 
+ @RoopeshNair - for feedback on documentation referring to V4. The V4 task will ship in next deployment.

**Comment by rstra** [comment]
@kmkumaran Do you know when the next deployment will happen?

**Comment by ytugarev** [comment]
@kmkumaran, @RoopeshNair
Can you sync somehow so next time we will be sure that Docs are accurate and not rush ahead actual release?

**Comment by whatsamattr** [comment]
@kmkumaran  - do you mean the Q1 deployment or the Q2 deployment ?

**Comment by thomps23** [comment]
@kmkumaran Just confirming v4 was deployed in Q2 before I close out.

**Comment by kmkumaran** [comment]
Yes. The v4 version of the task is shipped.

**Comment by thomps23** [comment]
@kmkumaran - Great, closing this out.

**Comment by davec643** [comment]
I'm having the same issue with using AzurePowerShell@4 task in an On Premise installation of Azure DevOps. We updated to the latest build agent version 2.155.1 and the issue occurs. Do you know if v4 is shipped for on premise installations yet?
