### ISSUE TITLE
Problem with **

### ISSUE THREAD

**Issue by varnk** [MicrosoftDocs/vsts-docs#323]
According to the documentation, ** copies just the root folder, but that is not the case.  ** copies all subfolders too.  How can I just copy the root folder without subfolders?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 34301e0e-fc7e-bf7a-de61-c466756f22a3
* Version Independent ID: 2595a9cf-03b2-4206-6dda-43ac1b903add
* Content: [Copy and publish build artifacts | Microsoft Docs](https://docs.microsoft.com/en-us/vsts/build-release/tasks/utility/copy-and-publish-build-artifacts)
* Content Source: [docs/build-release/tasks/utility/copy-and-publish-build-artifacts.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/build-release/tasks/utility/copy-and-publish-build-artifacts.md)
* Service: **unspecified**
* GitHub Login: @douge
* Microsoft Alias: **alewis**

**Comment by mlearned** [comment]
@varnk  were you able to get unblocked here?  I'm looking into this one and will be back.

**Comment by varnk** [comment]
@mlearned.  I stopped using Copy and Publish Build artifacts and opted to use the two-step process of first calling Copy Files and then calling Publish Build Artifacts.  However, I still thought it was a good idea to post the issue with Copy and Publish Build artifacts.

**Comment by andyjlewis** [comment]
Yes, we recommend you use the Copy Files task. The Copy and Publish Build artifacts task is deprecated.
