### ISSUE TITLE
Add team administrator link is broken

### ISSUE THREAD

**Issue by CoolDadTx** [MicrosoftDocs/vsts-docs#3234]
Clicking the Add Team Administrator link in content gives a 404. The search recommends this link (https://docs.microsoft.com/en-us/azure/devops/organizations/settings/add-team-administrator) instead.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de6d2e51-6c3e-512a-0fcb-5141c0290663
* Version Independent ID: a25c921a-6ec4-eeed-fa93-1105d4444408
* Content: [Customize cards on a board - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/boards/customize-cards?view=azure-devops&tabs=new-nav)
* Content Source: [docs/boards/boards/customize-cards.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/boards/boards/customize-cards.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@CoolDadTx - Thank you for the correction. I'll update the article today. The correct link is: 

To configure team settings, you must be [added as a team administrator](/azure/devops/organizations/settings/add-team-administrator) or be a member of the **Project Administrators** or **Project Collection Administrators** group. See [Set permissions at the project- or collection-level](/azure/devops/organizations/security/set-project-collection-level-permissions).
