### ISSUE TITLE
How to do variable substitutions when deploying a console app to a VM?

### ISSUE THREAD

**Issue by jholovacs** [MicrosoftDocs/vsts-docs#3236]
I have an appsettings.json file for a .net core console app that I'm going to run as a windows service on a VM, but I can't figure out how to use variable substitution if it's not an Azure web app.  Is this not supported, and if not... why not?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 315ff823-9992-9f9b-62a1-42ce622ed41c
* Version Independent ID: 72ec3ffc-1dc9-b2dc-e3d4-4f14deae3720
* Content: [File transforms and variable substitution - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/transforms-variable-substitution?view=azure-devops)
* Content Source: [docs/pipelines/tasks/transforms-variable-substitution.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/transforms-variable-substitution.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by codyb11989** [comment]
This would be a nice feature to have. Currently using a 3rd party extension but it can only do one setting at a time.

**Comment by alexhomer1** [comment]
Thank you for your feedback. I have passed this on to the product team for advice.

**Comment by wi1s0n** [comment]
I thought the "File Transform (Preview)" in the release pipeline was meant for this. I have some issues getting it to work. But is the "File Transform (Preview)" not the solution for this, to change some value in the appsettings.json?

**Comment by codyb11989** [comment]
I was not aware this existed, it is definitely a preview mode task. I can't get it working.

**Comment by jholovacs** [comment]
Yeah that's brand new, but still doesn't work.

**Comment by wi1s0n** [comment]
According to the this issue:
https://github.com/Microsoft/azure-pipelines-tasks/issues/9488
They have fixed it, but not yet rolled out it.
Maybe one could add the working code to the agent oneself..?

**Comment by N-Usha** [comment]
File transform task should help you use variable substitution on any XML/JSON file and would work even it's not an Azure web app. We have fixed the reported bugs and the new updated task is currently getting deployed and would be broadly available in a couple of weeks.
