### ISSUE TITLE
Custom condition for Success only

### ISSUE THREAD

**Issue by orionmelt** [MicrosoftDocs/vsts-docs#3237]
When a deployment group job has multiple targets and one of them fails, the job is marked as "Partially Succeeded". `succeeded()` seems to evaluate to true when the previous job status is "Succeeded" or "Partially Succeeded", but how do we tell these apart? We want the release pipeline to go ahead with all subsequent jobs **if and only if** a previous job has "Succeeded", as we want to treat a partial success as a failure.

We tried `eq(variables['Agent.JobStatus'], 'Succeeded')` but it doesn't work at the job level - the variable is expanding to null.

**Comment by steved0x** [comment]
@orionmelt Thank you for the feedback. Can you let me know which article this feedback is for, so I can assign it to the author? You can reply here with the URL of the topic, or you can create a new issue by browsing to the topic on docs.microsoft.com and choosing **Content feedback** at the bottom. 

![image](https://user-images.githubusercontent.com/1580889/51848491-af95cd80-22eb-11e9-81a2-1680fc40caf9.png)
