### ISSUE TITLE
How to publish a package to a private feed from an external CI source

### ISSUE THREAD

**Issue by mrahhal** [MicrosoftDocs/vsts-docs#3238]
I'm trying to figure out a way to publish packages from an external CI build (appveyor) but I just can't find a way. This article should be the right place to include this in. I have no idea how I'll be able to push those to a private package feed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 11ed58a1-5819-f3a4-c674-dafcdbd56fbc
* Version Independent ID: d68aca4d-3fd3-1864-09f5-6060295e0399
* Content: [Publishing to NuGet feeds - Azure Pipelines and TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/nuget?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/artifacts/nuget.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/artifacts/nuget.md)
* Product: **devops**
* GitHub Login: @steved0x
* Microsoft Alias: **amullans**

**Comment by mrahhal** [comment]
From [this SO question](https://stackoverflow.com/questions/54532465/how-to-publish-nuget-packages-from-appveyor-ci-to-azure-devops-artifacts/54550148#54550148), it seems there are current problems preventing this from working.

**Comment by chasewilson** [comment]
Hi @mrahhal, thank you so much for the questions. The Azure DevOps team isn't currently supporting or planning to support this feature. If you would like more in-depth information or would like to make a feature request, please reach out to the [Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html). I'm closing this issue but I hope you will reach out or create a new issue if you have any more feedback.
