### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by athanasios-kapelonis** [MicrosoftDocs/vsts-docs#3239]
If your a project administrator -&gt; If YOU ARE a project administrator

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 88778b05-c63e-dd7f-2a05-10b7e48b61a2
* Version Independent ID: a072de48-16c8-67e3-260f-f3a5d652f10b
* Content: [Learn how to create, organize, and filter your backlog of user stories, features, and epics - Azure Boards](https://docs.microsoft.com/en-gb/azure/devops/boards/backlogs/index?view=azure-devops)
* Content Source: [docs/boards/backlogs/index.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/boards/backlogs/index.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@athanasios-kapelonis - thank you for the correction. I'll update the article.
