### ISSUE TITLE
Regarding Determine which user is performing the connection of VSTS to Azure AD

### ISSUE THREAD

**Issue by zingaroo** [MicrosoftDocs/vsts-docs#324]
- What do you mean by "Is not using the Microsoft account identity that matches the Azure AD identity" under "Determine which user is performing the connection of VSTS to Azure AD"? Shouldn't it be that it is in fact used?
- Same section step 3, the user has to be invited/added first before it can be set as an owner
- Step 6 is redundant since it is already mentioned in step 3 (should be Settings page though)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f56d653-f3ed-88a3-c307-1ba6eec6cbc2
* Version Independent ID: 5f5b1c72-7b2a-a7cf-aea7-39cf84b11005
* Content: [Connect VSTS account to Azure Active Directory (Azure AD) | Microsoft Docs](https://docs.microsoft.com/en-us/vsts/accounts/connect-account-to-aad#determine-which-user-is-performing-the-connection-of-vsts-to-azure-ad)
* Content Source: [docs/accounts/connect-account-to-aad.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/accounts/connect-account-to-aad.md)
* Service: **unspecified**
* GitHub Login: @douge
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
@zingaroo Thanks for letting us know, I added some clarification and it should be live soon.
