### ISSUE TITLE
Use old form on Azure DevOps Server 2019

### ISSUE THREAD

**Issue by MattDavisRM** [MicrosoftDocs/vsts-docs#3241]
I see mentioning that can use the older form on TFS 2018.  Is this also an option on Azure DevOps server?  Could you add to the documentation to clarify now that the new version is released?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cabc9181-c452-e4bb-f65c-98e5af9792f3
* Version Independent ID: 96f171a7-3c06-6855-4534-5bc8d4f195dd
* Content: [Manage new form roll out - TFS](https://docs.microsoft.com/en-us/azure/devops/reference/manage-new-form-rollout?view=tfs-2017&viewFallbackFrom=azure-devops-2019)
* Content Source: [docs/reference/manage-new-form-rollout.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/reference/manage-new-form-rollout.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by danhellem** [comment]
The older form is deprecated on TFS 2018+ (Azure DevOps Server)
