### ISSUE TITLE
Missing link in section Color-Code tags on board 

### ISSUE THREAD

**Issue by jcfiorenzano** [MicrosoftDocs/vsts-docs#3242]
Look in the section Color-Code tags on board, the sentence "To learn more, see [Customize cards, color-code tags]("
it looks like an incomplete markdown link.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9bf3ce0a-184f-ca49-5453-01317e23dde5
* Version Independent ID: 0af9b10e-1126-2fda-982b-63d5795f9213
* Content: [Add tags to work items - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/queries/add-tags-to-work-items?view=azure-devops)
* Content Source: [docs/boards/queries/add-tags-to-work-items.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/boards/queries/add-tags-to-work-items.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@jcfiorenzano - Thank you for the feedback. The link that is missing is [Customize cards, color-code tags](../boards/customize-cards.md#color-tags). I'll update the article today.
