### ISSUE TITLE
System teams

### ISSUE THREAD

**Issue by FireFighter1017** [MicrosoftDocs/vsts-docs#3243]
Hi,

Great documentation!  There's one point I am still trying to figure out.
How do you deal with Systems teams?  shared services teams and so on...
They aren't part of any team but they participate in a lot of Team's stories.

At first I tried using subareas within a Functional Team area.
But I'm not sure how this will pan out for the teams... Or should it be the other way around (sub area in the shared services team's area)

I welcome any suggestions if based on actual experience.

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1c926cb3-ed15-3489-65f8-2a5c1fd129d4
* Version Independent ID: 1b441906-10f0-2ec0-d1aa-d3686ff94146
* Content: [Scaled Agile Framework - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/plans/scaled-agile-framework?view=azure-devops&viewFallbackFrom=azdevops)
* Content Source: [docs/boards/plans/scaled-agile-framework.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/boards/plans/scaled-agile-framework.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by mmitrik** [comment]
@FireFighter1017 This may not work for every organization, but our team (Azure DevOps team) made a shift to organize our teams to include engineers working on both front-end and back-end components for a given charter (which has it's own feature team and area path).  This means that more of those "shared services" engineers are working within feature teams.  Here is a good article that goes into more detail: [Agile principles in practice](https://docs.microsoft.com/en-us/azure/devops/learn/devops-at-microsoft/agile-principles-in-practice) (check out the [We changed our approach to teams](https://docs.microsoft.com/en-us/azure/devops/learn/devops-at-microsoft/agile-principles-in-practice#we-changed-our-approach-to-teams) section)

We do also have "shared services" teams for some of the larger subsystems (identity, auth, etc.) and those teams all have their own area paths like the other feature teams.  Here's a snippet from our area path hierarchy to demonstrate this:

![image](https://user-images.githubusercontent.com/940508/53049944-25620480-3466-11e9-8996-1f2c02587c48.png)

Each of the child nodes is a team (Commerce, Identity, VC Server, etc.), and you'll notice that some of them have sub areas, but that's a decision left up to each team.
