### ISSUE TITLE
Example of YAML based docker-compose for separate build and push tasks

### ISSUE THREAD

**Issue by kieronlanning** [MicrosoftDocs/vsts-docs#3244]
Using the new YAML build pipeline, there isn't a clear way of:

- Using docker-compose with a yaml file to build.
- Using docker-compose with a yaml file to push to an Azure Container Registry.

The YAML validation currently fails for things like `serviceName`, which isn't required for building or pushing as everything is defined in the docker-compose yaml(s).

**Comment by steved0x** [comment]
@shashankbarsin @azooinmyluggage Can you take a look at this in the context of containers, or should it go to a YAML person?

**Comment by shashankbarsin** [comment]
@kieronlanning, we updated the docs recently. Based on the recent set of docs, there is an example of [pushing to Azure Container Registry](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/docker-compose?view=azure-devops#push-service-images) and an [example of build](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/docker-compose?view=azure-devops#build-service-images). Please review the latest [doc for this task](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/docker-compose?view=azure-devops) and let me know if this doc needs further improvements.

**Comment by kieronlanning** [comment]
@shashankbarsin That's perfect, thankyou!
