### ISSUE TITLE
Outbound Internet Access ?

### ISSUE THREAD

**Issue by vmaruhpe** [MicrosoftDocs/vsts-docs#3245]
Hi,
Looks like there is no outbound internet access on the hosted servers. Other than deploy custom Agents, is there a way to download additional software dependencies. E.g: special environments, enable auto-updates for tools etc. on Microsoft Hosted Agents ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 99af681d-41ad-da15-0b72-08b5cd5a11ac
* Version Independent ID: 2fa0df36-a437-8cbb-b019-b49b31b1e116
* Content: [Microsoft-hosted agents for Azure Pipelines - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/agents/hosted.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/agents/hosted.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by vtbassmatt** [comment]
Hosted agents have full outbound network capabilities. Did you have problems installing software?
