### ISSUE TITLE
Is there a field for previous assignee?

### ISSUE THREAD

**Issue by balilingm** [MicrosoftDocs/vsts-docs#3247]
If a bug is assigned to another developer, how can the new owner know the previous owner without looking at the history? Is this supported or possible?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c1d94b21-0d87-af97-bb99-40595bfb38e2
* Version Independent ID: 0c118aeb-8b37-84a7-1d5c-ac8557258146
* Content: [Define default value or copy a value - TFS](https://docs.microsoft.com/en-us/azure/devops/reference/xml/define-default-copy-value-field?view=tfs-2018)
* Content Source: [docs/reference/xml/define-default-copy-value-field.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/reference/xml/define-default-copy-value-field.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@balilingm - Thank you for the inquiry. There is no default field that support this. If you work from an on-premises deployment, then you can do this using the On-premises XML process and create a custom field and create a rule: whenChanged assignedTo copy from assignedto.
