### ISSUE TITLE
Update document regarding location of Multi-configuration

### ISSUE THREAD

**Issue by vtjc2002** [MicrosoftDocs/vsts-docs#325]
Please update official document on where the Multi-configuration is located.  Thank you

https://developercommunity.visualstudio.com/content/problem/126232/multi-configuration-option-missing.html

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0fa5a83c-70fd-6925-a8c8-256b21c21a2e
* Version Independent ID: 75f4a136-7245-7878-2953-6b68272fe4ec
* Content: [Build definition options | Microsoft Docs](https://docs.microsoft.com/en-us/vsts/build-release/concepts/definitions/build/options#feedback)
* Content Source: [docs/build-release/concepts/definitions/build/options.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/build-release/concepts/definitions/build/options.md)
* Service: **unspecified**
* GitHub Login: @douge
* Microsoft Alias: **alewis**

**Comment by alexhomer1** [comment]
Thank you for your feedback. We will update the topic.
