### ISSUE TITLE
Release.Reason variable

### ISSUE THREAD

**Issue by harry12311** [MicrosoftDocs/vsts-docs#3250]
I was trying to prepare a custom expression for execution of tasks in my release pipeline and was referring to this document for the values against variable - "Release.Reason". I figured out the actual values pipeline is showing against this variables are :
'ContinuousIntegration', 'Manual', 'Schedule'
and not the one mentioned in this document. Please update the doc are let me know if I am missing any thing!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 611642f0-881f-10b9-ae94-3c562001d1f0
* Version Independent ID: 41efb94b-4c7a-64a3-b23b-70c8634ae727
* Content: [Release variables  and debugging - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/variables?view=azure-devops&tabs=batch&viewFallbackFrom=vsts)
* Content Source: [docs/pipelines/release/variables.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/release/variables.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment]
Thank you for your feedback. We are currently in the process of updating this topic and will incorporate your feedback into the new version.
