### ISSUE TITLE
Outdated information

### ISSUE THREAD

**Issue by Aculeo** [MicrosoftDocs/vsts-docs#3252]
The arguments for the P12 certificate or the provisioning profile don't exist anymore in version 2 of this task.

![grafik](https://user-images.githubusercontent.com/3977620/52341121-08fbac00-2a12-11e9-808d-09119b810239.png)

And what really isn't clear to me is whether I have to set my project to manual provisioning or not, as this argument is also gone - are these settings done automatically or not? How exactly does it select the certificate? This is incredibly confusing and there's so much outdated blog articles out there.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4d91aa34-87c4-d934-28e2-456eac57432d
* Version Independent ID: 5725c1ab-d894-f79c-f7e0-0c5b8b5cca56
* Content: [Xamarin.iOS build and release task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/xamarin-ios?view=azure-devops)
* Content Source: [docs/pipelines/tasks/build/xamarin-ios.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/build/xamarin-ios.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by ravero** [comment]
I'm having the same issue, and it's sad to see that 2 months passed and no one provided a decent answer.

**Comment by ravero** [comment]
This is really disappointing because the link to the documentation comes here to this outdated documentation.

**Comment by davidstaheli** [comment]
The documentation has been updated to remove outdated information.  Now, it also links to the latest documentation on using Xamarin in YAML and how to sign/provision an app.  The updates should be live within a couple of days.
