### ISSUE TITLE
Contribute to Pull Requests

### ISSUE THREAD

**Issue by MattDavisRM** [MicrosoftDocs/vsts-docs#3256]
What does 'Contribute to Pull Requests' mean?  It might be nice to expand out what is/isn't controlled by each of these permissions.  I'm looking for where completing pull requests is captured but having a tough time finding where it is spelled out.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5f5ce059-ec92-5413-0910-4e28033db034
* Version Independent ID: 540610d3-6073-664d-97f8-e7d8e0a21a20
* Content: [Set Git or TFVC repository permissions - Azure DevOps & TFS](https://docs.microsoft.com/en-us/azure/devops/organizations/security/set-git-tfvc-repository-permissions?view=azure-devops&tabs=new-nav)
* Content Source: [docs/organizations/security/set-git-tfvc-repository-permissions.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/security/set-git-tfvc-repository-permissions.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by chcomley** [comment]
@MattDavisRM, Thanks for your comment, and I'm sorry for the confusion. I've created a user story for my backlog, so I can look into this. I'll be in touch. Thank you!

**Comment by chcomley** [comment]
Hi @MattDavisRM Here's where you can find more information on what the permission, [Contribute to pull requests](https://docs.microsoft.com/en-us/azure/devops/organizations/security/permissions?view=azure-devops#git-repository-object-level) entails. I've also pasted the permission and description below.
Contribute to pull requests = Can create, comment on, and vote on pull requests.
I'll be closing out this issue, however please let me know if you have any further questions. Thank you!

**Comment by pengsiya** [comment]
I think it would be helpful to have link to these useful docs on the ADO UI.
