### ISSUE TITLE
correction to 3rd sentence - only PCAs can modify the Privacy URL field

### ISSUE THREAD

**Issue by pathakneeti** [MicrosoftDocs/vsts-docs#3258]
Hi doc team! we need to modify the 3rd sentence - only PCAs can modify the Privacy URL field. Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 05b491f8-3ab7-1d68-5fa9-82ae62852bee
* Version Independent ID: 33bf9215-4e69-520a-3283-066a2c2f2478
* Content: [Add privacy URL for your organization to comply with the GDPR - Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/add-privacy-url?view=azure-devops)
* Content Source: [docs/organizations/accounts/add-privacy-url.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/accounts/add-privacy-url.md)
* Product: **devops**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
@pathakneeti Thanks so much for the heads up! I've completed a PR for this update, which should be live by sometime this afternoon. Thanks again!
