### ISSUE TITLE
Multiple values in Solution parameter

### ISSUE THREAD

**Issue by jeffhebrank** [MicrosoftDocs/vsts-docs#326]
Instead of doing **\*.sln can I list multiple solution files? What is the format to do so? Comma separated, semi-colons, returns?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8b96fad0-7bfb-8c02-701a-5960da7fb313
* Version Independent ID: 74847500-c617-31f4-999c-a344e7b4299e
* Content: [New Build Editor | Microsoft Docs](https://docs.microsoft.com/en-us/vsts/build-release/archive/preview/2017-user-experience)
* Content Source: [docs/build-release/archive/preview/2017-user-experience.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/build-release/archive/preview/2017-user-experience.md)
* Service: **unspecified**
* GitHub Login: @douge
* Microsoft Alias: **alewis**

**Comment by alexhomer1** [comment]
You cannot specify more than one search criteria. If you want to build a single solution, click the ... button and select the solution. If you want to build multiple solutions, specify search criteria. You can use a single-folder wildcard (*) and recursive wildcards (**). For example, **\*.sln searches for all .sln files in all subdirectories.
