### ISSUE TITLE
Grid not showing data in IE11 nor Edge

### ISSUE THREAD

**Issue by riezebosch** [MicrosoftDocs/vsts-docs#3260]
Even [the example](https://github.com/Microsoft/vsts-extension-samples/blob/master/contributions-guide/contextForm.html) (with some dummy data added) does show the grid but no data in IE11 nor Edge.

**Comment by steved0x** [comment]
@riezebosch Thank you for the feedback. I have moved your issue to here:

https://github.com/Microsoft/vsts-extension-samples/issues/129

And we'll take a look over there.

Thank you
