### ISSUE TITLE
Linking additional parameters?

### ISSUE THREAD

**Issue by nickalbrecht** [MicrosoftDocs/vsts-docs#3266]
As the documentation states, the `Unlink` is listed exactly where is says it should be. But I've looked and looked, and I can't find any way to link new parameters other than using variable groups (which you can then use via things like `$(variableName)`). The documentation states that there is a `Link` option next to the task's argument, but I can't find that anywhere. And if you unlink a parameter, the only way to get it back is to remove the stage entirely, and use the a template to get you back to the defaults again.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 214c853e-63ba-240c-9cff-7ea3ab7a788c
* Version Independent ID: 781b5018-0c34-353a-a035-5d84af3994a0
* Content: [Process parameters - Azure Pipelines](https://docs.microsoft.com/en-ca/azure/devops/pipelines/process/parameters?view=azure-devops)
* Content Source: [docs/pipelines/process/parameters.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/parameters.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by nickalbrecht** [comment]
I'm specifically looking the IIS Web App Deploy task, if that helps

**Comment by ChristophLindemann** [comment]
This "Link" button is missing from both TFS 2018.2 and Azure DevOps Server 2019 RC1

**Comment by Dash** [comment]
Issue persists in Azure DevOps Server 2019 RTM.

Problem: https://developercommunity.visualstudio.com/content/problem/502975/link-settings-button-missing-from-release-pipeline.html

**Comment by warzinskid** [comment]
This is still an issue.

**Comment by smphayward** [comment]
This is completely and utterly useless. There is no way in Azure DevOps to add new process parameters. All I can do is unlink all. What a piece of garbage feature. How on earth can this be in production???

**Comment by shashban** [comment]
The link and unlink functionality is available for build pipelines only. They aren't available for release pipelines. We'll get the docs fixed to reflect the same.

**Comment by nickalbrecht** [comment]
That doesn't make sense though. If you create a brand new release pipeline, and for example pick/apply the template "IIS website deployment", you will see that it has 5 different parameters linked. So obviously the feature is there, and is used/supported. It just doesn't expose the ability for the user to manage those links.

There's UI for disconnecting all 5 parameters in this case, but not for disconnecting individual ones, or re-establishing any of those links after you've removed them.

**Comment by RoopeshNair** [comment]
Yes, you are right. the feature was never fully implemented in release. Process parameters that you see in release are shipped out of the box. Option create was not exposed to end users. 

There were a few design challenges in the approach and the work was stalled. Some of the release tasks have visibility rules that change the inputs dynamically and it doesn't play well with process parameters feature. We will not be able to enable it in release until we have a clean solution to handle this. 

At this point in time we are working issues, features that impact broader set of customers and we will not able to prioritize this.
