### ISSUE TITLE
Environment variables section is confusing

### ISSUE THREAD

**Issue by letmaik** [MicrosoftDocs/vsts-docs#3271]
It sounds like `$(FOO)` is the only way to use environment variables as arguments when running a script. It should also mention that you can invoke a script by simply calling it like:
```
steps:
- script: echo $FOO
```
Or `%FOO%` if you're on Windows.

Maybe this section should be merged with the other sections somehow since the whole artical covers environment variables in different places, so it seems odd to have a heading called "Environment variables" which only contains a small part of the whole story.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd7e0bd3-1f7d-d7b6-cc72-5ef63c31b46a
* Version Independent ID: dae87abd-b73d-9120-bcdb-6097d4b40f2a
* Content: [Pipeline variables - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch#environment-variables)
* Content Source: [docs/pipelines/process/variables.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/variables.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by vijayma** [comment]
Updated the doc to explain this.

**Comment by letmaik** [comment]
Please reference the commit/PR so that I can have a look.
