### ISSUE TITLE
Difference between "variables:" and "parameters:"

### ISSUE THREAD

**Issue by letmaik** [MicrosoftDocs/vsts-docs#3272]
The [YAML schema doc](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema#script) doesn't mention "variables:" at all. Is this Variables article outdated?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd7e0bd3-1f7d-d7b6-cc72-5ef63c31b46a
* Version Independent ID: dae87abd-b73d-9120-bcdb-6097d4b40f2a
* Content: [Pipeline variables - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch#environment-variables)
* Content Source: [docs/pipelines/process/variables.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/variables.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by adventworks** [comment]
The "variables:" is mentioned in multiple places in the YAML schema doc. I am not sure what you mean.

**Comment by letmaik** [comment]
You're right, I'm not sure why I didn't see that. My bad!

**Comment by letmaik** [comment]
I think it would be good to have a summary somewhere that says what the difference between variables and parameters is, mentioning for example that parameters are not directly accessible as environment variables, but variables are.
