### ISSUE TITLE
Use consistent syntax when referencing variables in scripts

### ISSUE THREAD

**Issue by letmaik** [MicrosoftDocs/vsts-docs#3274]
At the beginning of this article it says that in scripts (which includes inline script blocks a la `script: ...`) you have to use normal environment variable syntax of the respective shell. Some of the following examples follow this, but then for some reason the [Counters](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch#counters) example and some of the following ones use the `$(..)` syntax, which is confusing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd7e0bd3-1f7d-d7b6-cc72-5ef63c31b46a
* Version Independent ID: dae87abd-b73d-9120-bcdb-6097d4b40f2a
* Content: [Pipeline variables - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch#counters)
* Content Source: [docs/pipelines/process/variables.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/variables.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by vijayma** [comment]
Updated the doc with more examples to clarify this.

**Comment by letmaik** [comment]
Please reference the commit/PR so that I can have a look.
