### ISSUE TITLE
Links to "Desktop client developer tools" are not working

### ISSUE THREAD

**Issue by Styxxy** [MicrosoftDocs/vsts-docs#3275]
Links listed in section "Desktop client developer tools" are broken. They go to a non-existing page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 878f028a-4418-1f6c-bf27-d469b249b621
* Version Independent ID: 7209b942-b6ab-e9f6-6cfd-bd5d89ea9aa8
* Content: [Tools and clients that connect - Azure DevOps Services & TFS - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/user-guide/tools?view=azure-devops)
* Content Source: [docs/user-guide/tools.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/user-guide/tools.md)
* Product: **devops**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Thanks so much for the heads up, @Styxxy. I've fixed these broken links and completed a PR. These fixes should go live sometime this afternoon. In the meantime, here they are: 

- [Android Studio with the Azure DevOps Services Plug-in for Android Studio](https://review.docs.microsoft.com/en-us/azure/devops/java/download-android-studio-plug-in?view=tfs-2013)
- [IntelliJ with the Azure DevOps Services Plugin for IntelliJ](https://review.docs.microsoft.com/en-us/azure/devops/java/download-intellij-plug-in?view=tfs-2013)
- [Visual Studio Code](https://review.docs.microsoft.com/en-us/azure/devops/java/vscode-extension?view=tfs-2013)

Thanks again!
