### ISSUE TITLE
Link redirects to 404 not found page on Github

### ISSUE THREAD

**Issue by Daniel-Krzyczkowski** [MicrosoftDocs/vsts-docs#3276]
The link to see the delay taks on Github not working correctly (displaying 404 not found):
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks/Delay

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 05e99925-c1f9-5041-311f-39469c124d85
* Version Independent ID: 81b0a6bf-d7cb-7208-3759-3455efc5bf13
* Content: [Delay task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/delay?view=azure-devops)
* Content Source: [docs/pipelines/tasks/utility/delay.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/utility/delay.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment]
Thank you for your feedback. I will update the topic to fix this.
