### ISSUE TITLE
How do you _define_ an environmental variable in TFS 2018?

### ISSUE THREAD

**Issue by RubixRevenge** [MicrosoftDocs/vsts-docs#328]
How do you _define_ an environmental variable in TFS 2018? I need to create an environmental variable that all of my projects can read from. An example or two would be helpful. Google searches on "how to define an environmental variable in TFS" brings me back to _this_ page. And I don't see any examples here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ffebdc8-521c-44b5-cde4-4abdc1bd6f18
* Version Independent ID: dc0effda-6d93-62aa-64c5-4e6f283b0826
* Content: [Build variables | Microsoft Docs](https://docs.microsoft.com/en-us/vsts/build-release/concepts/definitions/build/variables?tabs=batch#environment-variables)
* Content Source: [docs/build-release/concepts/definitions/build/variables.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/build-release/concepts/definitions/build/variables.md)
* Service: **unspecified**
* GitHub Login: @douge
* Microsoft Alias: **alewis**

**Comment by andyjlewis** [comment]
Does this part not cover what you need: https://docs.microsoft.com/en-us/vsts/build-release/concepts/definitions/build/variables?tabs=batch#set-in-script ?

**Comment by RubixRevenge** [comment]
So you can only set an environmental variable in script? You can't define it through the GUI? Maybe the cited explanation makes no sense because I don't know what "sauce" and "secret sauce" are. It's an orphaned dictionary response that doesn't tell me much. This style of document helps if you already know what you're doing and need to jog your memory, but if you're doing this for the very first time, the document is not helpful.

**Comment by andyjlewis** [comment]
I've been assuming you were talking about a build process (this content is all about using build and release processes to compile, test, deploy, etc. your app). But it now occurs to me after re-reading your original question above that maybe you're not talking about something other than a build process?

If we are talking about a build process, you can define and initialize a variable on the variables tab. If later in the process you want to programmatically change the value of a variable, then the only way to do it is via writing a logging command. It doesn't have to be a script, it can be any program that writes the command to standard out.

**Comment by RubixRevenge** [comment]
I _am_ talking about build and release processes. At present I'm having to repeat myself by manually adding the same variable name and value in multiple projects by hand. I was hoping there would be a way that I only have to write the variables once and be able to use them as needed in _any_ project. But from what I'm reading, what I need to do cannot be done from within TFS itself.

**Comment by andyjlewis** [comment]
Got it. OK, you can use variable groups (https://docs.microsoft.com/en-us/vsts/build-release/concepts/library/variable-groups) to share a variable across build definitions in the same team project. We don't yet offer this option scoped to an account/team project collection level. You can vote on this feature here: https://visualstudio.uservoice.com/forums/330519-visual-studio-team-services/suggestions/18918109-make-variable-groups-visible-across-team-projects
