### ISSUE TITLE
How to select a job based on tagged commits?

### ISSUE THREAD

**Issue by jaraco** [MicrosoftDocs/vsts-docs#3281]
I'd like to do the common task of only running Publish jobs on tagged commits. How does one write that?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f151218-9a11-0078-e038-f96198a76143
* Version Independent ID: 09c4d032-62f3-d97c-79d7-6fbfd89910e9
* Content: [Conditional tasks - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/conditions?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/process/conditions.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/conditions.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by hhslepicka** [comment]
Maybe you can achieve it with:
condition: contains($(Build.SourceBranch), 'tags')

**Comment by jaraco** [comment]
Looks like [maybe not](https://dev.azure.com/jaraco/pip-run/_build/results?buildId=4). Other suggestions?

**Comment by saurabhjn76** [comment]
Try:
condition:contains(variables['Build.SourceBranch'], 'tags')

**Comment by jaraco** [comment]
At first blush, that's doing the trick. [This build skipped the publish step](https://dev.azure.com/jaraco/pip-run/_build/results?buildId=5).

**Comment by jaraco** [comment]
Next, I tried tagging that commit and pushing that tag, [which you can find here](https://github.com/jaraco/pip-run/releases/tag/test-build). Unfortunately, it seems that pushing that tag did not produce another build. Is that because the commit was pushed before the tag was present, but pushing the tag itself doesn't trigger any behavior? Is there something else I need to do to cause a tagged build to trigger a release?

**Comment by gldraphael** [comment]
Tags don't trigger builds by default. You need to include them manually. See https://docs.microsoft.com/en-us/azure/devops/pipelines/build/triggers?view=azure-devops&tabs=yaml#tags
