### ISSUE TITLE
Permanent delete of branch

### ISSUE THREAD

**Issue by clisc** [MicrosoftDocs/vsts-docs#3282]
How do I permanently delete a branch so that it can no longer be restored?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 23a72b8d-3241-a54a-e2c2-4c17b52678c1
* Version Independent ID: 8502eb8f-805b-54da-2c56-523a9aca7ce4
* Content: [Delete a branch in your Git repo - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/delete-branch?view=azure-devops)
* Content Source: [docs/repos/git/delete-branch.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/repos/git/delete-branch.md)
* Product: **devops**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by AlexChongMicrosoft** [comment]
Hands up. I have same question.

**Comment by thomps23** [comment]
@steved0x This issue has a matching issue assigned to the restore a branch topic. Is there a way to permanently delete the branch so that it doesnt appear in the restore workflow either?

**Comment by steved0x** [comment]
@clisc I believe the answer is no based on this reply to @AlexChongMicrosoft question. https://github.com/MicrosoftDocs/vsts-docs/issues/4295
