### ISSUE TITLE
multi-configuration Multipliers in release

### ISSUE THREAD

**Issue by ArnoldKen** [MicrosoftDocs/vsts-docs#3283]
How can we use secret variables in Azure DevOps release variable in multi-configuration as Multipliers?

Get error when I try to save the release definition.
The values 'Test1' are not valid for deployment inputs 'Multipliers' for deploy job 'Agent job'. Specify valid inputs and try again.

But when i add a similar variable (secret), and use it in multi-configuration as Multipliers and save the build, it allows me to save.

**Comment by steved0x** [comment]
@ArnoldKen Thank you for the feedback. Can you let me know which article this feedback is for, so I can assign it to the author? You can reply here with the URL of the topic, or you can create a new issue by browsing to the topic on docs.microsoft.com and choosing **Content feedback** at the bottom. 

![image](https://user-images.githubusercontent.com/1580889/51848491-af95cd80-22eb-11e9-81a2-1680fc40caf9.png)

**Comment by ArnoldKen** [comment]
@steved0x https://docs.microsoft.com/en-us/azure/devops/pipelines/process/phases?view=azure-devops&tabs=yaml#multi-configuration

Thank you for getting back on this

**Comment by alexhomer1** [comment]
Thank you for your feedback. I have passed this on to the product team for advice.

**Comment by ArnoldKen** [comment]
@alexhomer1 Thanks for the update. Waiting for more details.

**Comment by shashban** [comment]
Thanks for the feedback. Using a secret variable as a multiplier variable is not supported in both builds and releases. Even though designer build allows saving the pipeline, at run time the multiplier configuration is not applied. 
We're adding this to the docs.
