### ISSUE TITLE
Tester Webpage 

### ISSUE THREAD

**Issue by JPVenson** [MicrosoftDocs/vsts-docs#3287]
Hey, i have some complex lookups and do not want to restart the whole pipeline each time i want to debug something, can you create some sort of "tester" webpage where this can be easy tested?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8fd54e81-9a0c-c5e5-fb89-9534372805ff
* Version Independent ID: f3d49618-32d7-0abc-1c33-8211eb7dd073
* Content: [File matching patterns reference for Azure Pipelines and TFS - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/file-matching-patterns?view=azure-devops&viewFallbackFrom=vsts)
* Content Source: [docs/pipelines/tasks/file-matching-patterns.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/file-matching-patterns.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by andyjlewis** [comment]
Thank you for the suggestion.  I'm sorry for the long delay in response. I was out of the office for a long period of time earlier this year. Please request product enhancements here: https://developercommunity.visualstudio.com/spaces/21/index.html
