### ISSUE TITLE
Single board for multiple projects

### ISSUE THREAD

**Issue by sitetriks** [MicrosoftDocs/vsts-docs#3294]
As a team, we work on multiple projects and to best manage our assets, we need to see a board that has all the tasks for the given sprint regardless of the projects they belong to. We could not find such documentation and we are wondering whether it is a documentation content issue or missing functionality in Azure DevOps.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b3a8994c-97ff-1347-d621-66ae5e9c11ce
* Version Independent ID: 7e558469-28b6-bade-4ff0-4e2bf9a24e85
* Content: [Set dashboard permissions for team members - Azure DevOps & TFS](https://docs.microsoft.com/en-us/azure/devops/report/dashboards/dashboard-permissions?view=azure-devops#set-permissions)
* Content Source: [docs/report/dashboards/dashboard-permissions.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/report/dashboards/dashboard-permissions.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@[sitetriks](/sitetriks) - Thank you for your inquiry. We don't have any content that addresses this specific scenario, however, I will add it to my backlog of content to provide. Meanwhile, - There are a few ways to accomplish what you want. 
- If you want a list of tasks - create a query that goes across projects to pick up the tasks. You can then add that query using the [Query Results Widget](https://docs.microsoft.com/en-us/azure/devops/report/dashboards/widget-catalog?view=azure-devops#query-results-widget) to any dashboard you want. 
- Another tool you might consider is [Delivery Plans](https://docs.microsoft.com/en-us/azure/devops/boards/plans/review-team-plans?view=azure-devops&tabs=new-nav). This provides a calendar view of sprints, picking up the work items you configure for each team across all projects. This is more of a visual display then a list.

Let me know if there is some other criteria you are looking to address.

**Comment by sitetriks** [comment]
Hi Kathryn,

 

Many thanks for the prompt reply.

I see how one can filter all the work item types for a specific project, but I am having trouble figuring out how to set the query that should go across the various projects. I just do not see the filter (field) that could do this.  

 

Any help with this would be greatly appreciated.

 

Thanks,

Edoardo
