### ISSUE TITLE
Fail to retrieve any connections Please Help!

### ISSUE THREAD

**Issue by LarsVoith** [MicrosoftDocs/vsts-docs#3298]
Getting an error "Failed to retrieve any connections" With no way to configure anything, is this working properly?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 04afcda8-8a01-6fda-8387-778feaba9fea
* Version Independent ID: a0c518ee-dc43-42a6-07d9-150dfa8724c3
* Content: [Connect a project in Azure DevOps Services with a GitHub repository - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/github/connect-to-github?view=azure-devops)
* Content Source: [docs/boards/github/connect-to-github.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/boards/github/connect-to-github.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@[LarsVoith](/LarsVoith) - Hello Lars, without more details, it is hard to provide any guidance. You may have better luck by contacting our support page, https://azure.microsoft.com/en-us/support/devops/.
