### ISSUE TITLE
Copyright (yours) being infringed on another site

### ISSUE THREAD

**Issue by erickhagstrom** [MicrosoftDocs/vsts-docs#3299]
This article, "Adopt a Git branching strategy", published on https://docs.microsoft.com/en-us/azure/devops/repos/git/git-branching-guidance?view=azure-devops#feedback, has been plagiarized as "How to adopt a Git branching strategy", published at https://medium.freecodecamp.org/adopt-a-git-branching-strategy-ac729ff4f838. The publisher claims to honor DCMA requests.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe168fc3-2ed2-b3e6-ce30-cac721165ceb
* Version Independent ID: 8d63fbd7-12c4-9a94-92f6-969e7eb41037
* Content: [Git branching guidance - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/git-branching-guidance?view=azure-devops#feedback)
* Content Source: [docs/repos/git/git-branching-guidance.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/repos/git/git-branching-guidance.md)
* Product: **devops**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
It looks like they have deleted it
