### ISSUE TITLE
Possible mistake in the instructions?

### ISSUE THREAD

**Issue by schwammy** [MicrosoftDocs/vsts-docs#3302]
Hi,
Following the instructions for the second section - "Create an Azure Resource Manager service connection with an existing service principal", I believe step 9 is not needed, assuming step 1 is completed. It seems that steps 1 and 9 do the same thing: create an AD application and service principal and therefor provide a principle Id and Key.
Thanks,
Andy

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 26477658-d1ad-a4c9-0d9e-59aeead8a71e
* Version Independent ID: 45dfbd24-b9f4-fdf2-48a2-5648220204fe
* Content: [Connect to Microsoft Azure - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/library/connect-to-azure?view=azure-devops#feedback)
* Content Source: [docs/pipelines/library/connect-to-azure.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/library/connect-to-azure.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment]
Thank you for your feedback. I have updated the topic to include your recommendations.
