### ISSUE TITLE
Feature request: devops cli support

### ISSUE THREAD

**Issue by smpilo** [MicrosoftDocs/vsts-docs#3303]
Expose branch policy management via azure devops cli to facilitate scripting branch policy configuration across multiple repos.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7cd986e0-608c-1d8c-6faf-ecdb12e10bc6
* Version Independent ID: d60c996e-187e-dd6b-7f3a-dd056a1603f4
* Content: [Protect your Git branches with policies - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/branch-policies?view=azure-devops)
* Content Source: [docs/repos/git/branch-policies.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/repos/git/branch-policies.md)
* Product: **devops**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by nschonni** [comment]
The repo for that is over here https://github.com/Microsoft/azure-devops-cli-extension
Probably a better place to open an issue that isn't related to the documentation

**Comment by smpilo** [comment]
Makes sense, thanks.
