### ISSUE TITLE
ignoreLASTEXITCODE - in the arguments section this is ignore$LASTEXITCODE (causes the build to fail)

### ISSUE THREAD

**Issue by craig-martin** [MicrosoftDocs/vsts-docs#3307]
trying out this option and don't have it working yet but noticed the item in the arguments section is not spelled correctly.
Should be: ignoreLASTEXITCODE
Currently: ignore$LASTEXITCODE

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a0e444c2-69c6-4d71-6fd0-94d0f4097d3a
* Version Independent ID: 3a727833-1cc3-c2fb-c5b3-22605eee2721
* Content: [PowerShell task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/powershell?view=azure-devops)
* Content Source: [docs/pipelines/tasks/utility/powershell.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/utility/powershell.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by steved0x** [comment]
@craig-martin Thank you for fixing that.

**Comment by steved0x** [comment]
This is fixed and should be live soon.

**Comment by craig-martin** [comment]
Thanks!
