### ISSUE TITLE
Concepts -> Pipelines -> Templates -> Required Parameters

### ISSUE THREAD

**Issue by gregpakes** [MicrosoftDocs/vsts-docs#3310]
I tried to implement the bash script in the **Required parameters** section of https://docs.microsoft.com/en-us/azure/devops/pipelines/process/templates?view=azure-devops#required-parameters.

It did not work because I needed to put quotes around the **echo** statement.

> echo "##vso[task.complete result=Failed;]Missing template parameter \"solution\""

Without the quotes, it didn't work for me.  Agent was hosted VS2017.

**Comment by gregpakes** [comment]
PR here: https://github.com/MicrosoftDocs/vsts-docs/compare/master...gregpakes:patch-1

**Comment by steved0x** [comment]
@gregpakes Thank you for catching this, the PR should be merged shortly. (And thanks for the PR)

**Comment by gregpakes** [comment]
Closing this issue as it will be tracked in the PR:

https://github.com/MicrosoftDocs/vsts-docs/compare/master...gregpakes:patch-1
