### ISSUE TITLE
Where is "Deployment Pools Page"?

### ISSUE THREAD

**Issue by micblo** [MicrosoftDocs/vsts-docs#332]
IN TFS 2018, I CANNOT find "Deployment Pools Page". I just want to set the same machine to more deployment groups. HOW CAN I SHARE? This document cheats me. :(

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 3b38c265-be4c-b038-e3a9-783a5e5ce659
* Version Independent ID: 67da69da-3651-a8f4-f06a-c35aa3aa98fc
* Content: [Deployment groups in Release Management | Microsoft Docs](https://docs.microsoft.com/zh-cn/vsts/build-release/concepts/definitions/release/deployment-groups/#share-a-deployment-group)
* Content Source: [docs/build-release/concepts/definitions/release/deployment-groups/index.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/build-release/concepts/definitions/release/deployment-groups/index.md)
* Service: **unspecified**
* GitHub Login: @douge
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment]
The Deployment Pools feature is available in VSTS and in TFS Update 2 and later. On the Deployment Groups page there is a tab for Available pools. Select one to see the sharing capabilities.
