### ISSUE TITLE
.order file needs more information: syntax and examples

### ISSUE THREAD

**Issue by Paul-Dempsey** [MicrosoftDocs/vsts-docs#3322]
Under. ".order File", it desperately needs more information on where you put these file(s), what is the format of file content, and provide examples. As given, I have no clue what to put in the file, how it relates to what appears in the UI when viewing the wiki, and how it relates to folder organization of files in the repo.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 361efecd-d973-82ed-1dd8-ca01afe12f5d
* Version Independent ID: 629f3af2-8218-e53c-45c3-0e40c03f2273
* Content: [Wiki repository files, structure, and conventions in Azure DevOps - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/project/wiki/wiki-file-structure?view=azure-devops)
* Content Source: [docs/project/wiki/wiki-file-structure.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/project/wiki/wiki-file-structure.md)
* Product: **devops**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
@Paul-Dempsey, We're sorry for any troubles, but thank you for your contribution to docs. We've published updates! The updates should go live sometime this afternoon. Please let us know if you have any other questions. Thanks again.
