### ISSUE TITLE
Ungrammatical sentence: "Titles of pages added offline titles must not contain a blank space"

### ISSUE THREAD

**Issue by Paul-Dempsey** [MicrosoftDocs/vsts-docs#3323]
The sentence: "Titles of pages added offline titles must not contain a blank space" is ungrammatical, and I don't know what it is trying to tell me. Doesn't it simply mean that you can't add a file with a space in the name?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 361efecd-d973-82ed-1dd8-ca01afe12f5d
* Version Independent ID: 629f3af2-8218-e53c-45c3-0e40c03f2273
* Content: [Wiki repository files, structure, and conventions in Azure DevOps - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/project/wiki/wiki-file-structure?view=azure-devops)
* Content Source: [docs/project/wiki/wiki-file-structure.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/project/wiki/wiki-file-structure.md)
* Product: **devops**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
@Paul-Dempsey, We're sorry for any troubles, but thank you for your contribution to docs. We've published updates! The updates should go live sometime this afternoon. Please let us know if you have any other questions. Thanks again.
