### ISSUE TITLE
ID In @RecentMentions in TS / VS queries?

### ISSUE THREAD

**Issue by cbordeman** [MicrosoftDocs/vsts-docs#3324]
Would really like to use this predicate in my query in Visual Studio so I can see all items in which I'm mentioned.  I can't use the portal because my eyes are so sensitive to white light I can't see the screen, and plugins like Dark Reader can't darken the background on this site (please fix that too!!).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a718268-1105-4def-5f9e-20ea21afc0d7
* Version Independent ID: 0f08fa18-3075-4275-22c7-d5d1c1e260b0
* Content: [Query fields, operators, and macros/variables - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/queries/query-operators-variables?view=azure-devops)
* Content Source: [docs/boards/queries/query-operators-variables.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/boards/queries/query-operators-variables.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@cbordeman - Thank you for your inquiry. Please add your product suggestions to this page: https://developercommunity.visualstudio.com/content/idea/post.html?space=21. While the **@RecentMentions** macro doesn't work in Visual Studio 2017, you can view that list when you upgrade to VS 2019 with the new **Work Items** page as documented here: https://docs.microsoft.com/en-us/azure/devops/boards/work-items/view-add-work-items?view=azure-devops&tabs=visual-studio#view-work-items. 
![image](https://user-images.githubusercontent.com/10856840/52829501-edcc1480-3081-11e9-81e5-fb13bb56cfe5.png)

Also - if you use the Azure DevOps cloud service, you can choose a Theme from your user profile menu to get a different contrast screen: 
![image](https://user-images.githubusercontent.com/10856840/52829636-6c28b680-3082-11e9-9273-add541cc5d02.png)
