### ISSUE TITLE
Carthage example

### ISSUE THREAD

**Issue by kimdv** [MicrosoftDocs/vsts-docs#3326]
Hello! 
I use Carthage for at project, it would be nice with an example like CocoaPods. 
Also with private Carthage repo. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6209704c-87e7-20c3-1641-98f6bfec27a0
* Version Independent ID: f72e2fe4-c1f6-e775-8571-33495a70dc0d
* Content: [Build, test, and deploy Xcode apps - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/languages/xcode?view=azure-devops)
* Content Source: [docs/pipelines/languages/xcode.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/languages/xcode.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by whilethis** [comment]
I'd like to see the same thing. I can't seem to get ssh or https working with my private repositories.

**Comment by kimdv** [comment]
I got it working! 🚀

Added a env key called `GITHUB_ACCESS_TOKEN `. 

Carthage should automatically catch this

**Comment by andyjlewis** [comment]
Thanks @kimdv for the feedback and I'm glad to hear you got your scenario working! @DavidStaheli please review this scenario to see if there's an enhancement you think we ought to add to the backlog for this topic.

**Comment by davidstaheli** [comment]
Thanks for reporting this and for the helpful suggestion.  The documentation has been updated and should be live within a few days.
