### ISSUE TITLE
Example for Required Parameters doesn't work

### ISSUE THREAD

**Issue by reznet** [MicrosoftDocs/vsts-docs#3333]
Creating a new repo with the two files in the example and then building the pipeline, the build does not fail.  The step that is supposed to fail when the parameter is not provided finishes successfully, and then the following msbuild step runs which does fail (because there is no code in the repository).

Required Parameters: https://docs.microsoft.com/en-us/azure/devops/pipelines/process/templates?view=azure-devops#required-parameters

I have not found a way to fail a step using the magic vso variable syntax.  Is there some step missing from the example?  Even a pipeline with a single bash (or script, doesn't seem to matter) task that echos the vso message does not fail.

- bash: |
    if [ -z "$SOLUTION" ]; then
      echo ##vso[task.complete result=Failed;]Missing template parameter \"solution\"
    fi
  env:
    SOLUTION: ${{ parameters.solution }}
  displayName: Check for required parameters

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6724abea-bbdc-bf66-ed5e-3214fa6c3e66
* Version Independent ID: 4f8dab21-3f0e-da32-cc0e-1d85c13c0065
* Content: [Job and step templates - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/templates?view=azure-devops#required-parameters)
* Content Source: [docs/pipelines/process/templates.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/templates.md)
* Product: **devops**
* GitHub Login: @vtbassmatt
* Microsoft Alias: **alewis**

**Comment by gregpakes** [comment]
I think this is covered by this issue https://github.com/MicrosoftDocs/vsts-docs/issues/3310 and this PR https://github.com/MicrosoftDocs/vsts-docs/pull/3311

**Comment by reznet** [comment]
@gregpakes yup, with quotes the step now fails.  However, and perhaps this is a separate issue, the failure message doesn't appear anywhere.  does it for you?

in the example of `echo "##vso[task.complete result=Failed;]Missing template parameter"` I would expect that somewhere in the build details I'd see the message "Missing template parameter" but I don't.  Instead, I just see that the step failed, and if I drill into the step's log, I see the output of the script, but do not see that message.  In a non-yaml build, the message would appear in the build UI.

**Comment by gregpakes** [comment]
Yeh - I have the same issue.  I have to run the pipeline with diagnostics on to see the error and even then I have to go and hunt for it in the logs.

Worth keeping this issue open for that I think.

**Comment by vtbassmatt** [comment]
Thanks everyone. You're right, there's a surprising behavior that `##vso[task.complete]` doesn't offer up its error message anywhere in the UI. You actually need two steps: one to surface the message and the other to fail the step. I will update the docs; in the meantime, it's:
```yaml
steps:
- powershell: |
    echo "##vso[task.logissue type=error;]This error message will be shown in the UI"
    echo "##vso[task.complete result=Failed;]"
```

**Comment by vtbassmatt** [comment]
Fixed, and will get published later today.

**Comment by davidtom** [comment]
I seem to be having the opposite issue with this now, wherein the Required Parameter check always fails. Here is my code:

```bash
- bash: |
          # debug logs for sanity
          echo "destroy command "$DESTROY_COMMAND""
          echo "destroy param ${{ parameters.destroy_command }}"

          if [ -z "$DESTROY_COMMAND" ]; then
            echo "##vso[task.logissue type=error;]Missing template parameter \"DESTROY_COMMAND\""
            echo "##vso[task.complete result=Failed;]"
          fi
        env:
          DESTROY_COMMAND: ${{ parameters.destroy_command }}
        displayName: Check for Destroy Command
```

This fails my pipeline every time, even though I've defined `destroy_command`. I'm a bit fearful I'm just messing up the bash, but when I run a local script doing the same conditional block, I get the expected behavior. Has anyone else run into this?

**Comment by vtbassmatt** [comment]
@davidtom hmm, for short scripts which don't contain a `##`, we do echo the script out. But yours is both long enough and contains `##` so we shouldn't be preemptively echoing it.

You're not turning on `set -x` somewhere, are you?

**Comment by davidtom** [comment]
Hi @vtbassmatt, I am so sorry for the delayed response on this.

I have not turned on `set -x` anywhere in the `azure-pipelines.yaml` file. If there is another place that it could be set I can check for it, but as far as I'm aware it shouldn't be on.
