### ISSUE TITLE
Typo with Markdown syntax

### ISSUE THREAD

**Issue by pascalberger** [MicrosoftDocs/vsts-docs#3338]
There's a typo with markdown syntax in the following sentence:

```
**Differential data backups (databases)   **
```

Should be

```
**Differential data backups (databases)**
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4d2b336e-6b64-615b-ac24-416772d184c7
* Version Independent ID: 33e3cb7c-581c-1f82-581e-ec210fa80b6e
* Content: [Understand TFS databases, deployment topologies, and backup - Azure DevOps Server & Team Foundation Server](https://docs.microsoft.com/en-us/tfs/server/admin/backup/backup-db-architecture)
* Content Source: [https://mseng.visualstudio.com/DefaultCollection/TechnicalContent/_git/tfs-docs-pr?path=%2fdocs%2fserver%2fadmin%2fbackup%2fbackup-db-architecture.md&version=GBlive&_a=contents](https://mseng.visualstudio.com/DefaultCollection/TechnicalContent/_git/tfs-docs-pr?path=%2fdocs%2fserver%2fadmin%2fbackup%2fbackup-db-architecture.md&version=GBlive&_a=contents)
* Product: **devops-server**
* Git Login: **elbatk**
* Microsoft Alias: **elbatk**

**Comment by steved0x** [comment]
@pascalberger Thanks for letting us know, I am fixing that now.
