### ISSUE TITLE
Copy only modified compoenets using Windows machine file copy

### ISSUE THREAD

**Issue by vinothkumarb4u** [MicrosoftDocs/vsts-docs#3340]
Thank you for your feedback!

The issues in this repo are for documentation feedback.

If you are submitting your documentation feedback issue directly through GitHub, please provide the URL of the article so we can route the feedback to the correct author.

Please report Azure DevOps or TFS software bugs, feedback, or questions in the [Azure DevOps Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html).

I have an requirement to copy only modified file from repository to target folder. is there any option to do this using windows machine file copy
ex
Source repo
a1.txt
b1.txt - Modified.
c1.txt

Target folder
Should have only b1.txt

**Comment by steved0x** [comment]
@vinothkumarb4u The issues in this repo are for documentation feedback, I have transferred your issue over to here and we'll take a look using the new issue.

https://github.com/Microsoft/azure-pipelines-tasks/issues/9586

Thank you
