### ISSUE TITLE
Private agent configured as stated still invokes browser in headless mode

### ISSUE THREAD

**Issue by triccaj** [MicrosoftDocs/vsts-docs#3345]
Hi,

I have taken the steps in this article to do the following:

1. Create a Virtual machine hosted in Azure to my spec
2. Install n this machine a private agent
3. Configure this private agent as the execution target of my selenium suite
4. Updated our pipelines to use this

When I am RDP'ed in to the VM, the tests run in what is described as 'Visible UI Mode', but when I am not RDP'ed into the VM, they appear to run in headless mode.

I believe this to be the case as what pushed me to do the above steps was a test that passed repeatedly locally, but then failed in an agent pool. It transpired this is due to the tests running in headless mode and thus the field I am asserting not being visible in this configuration.

As I say, if I leave my local machine remote'd into the VM, then the tests pass on each release, but this isn't really sustainable.

Any advice as to what's happening here?

**Comment by triccaj** [comment]
I should also note I am using the tson script referenced in the article and this is kicking me from the VM.

**Comment by steved0x** [comment]
@triccaj Thank you for the feedback. Can you let me know which article this feedback is for, so I can assign it to the author? You can reply here with the URL of the topic, or you can create a new issue by browsing to the topic on docs.microsoft.com and choosing **Content feedback** at the bottom. 

![image](https://user-images.githubusercontent.com/1580889/51848491-af95cd80-22eb-11e9-81a2-1680fc40caf9.png)

**Comment by triccaj** [comment]
Hi,

Thanks for getting back and apologies for raising this in the incorrect area!

Here's the URL of the article in question:
https://docs.microsoft.com/en-us/azure/devops/pipelines/test/ui-testing-considerations?view=azure-devops&tabs=mstest

**Comment by steved0x** [comment]
@triccaj I have assigned this issue to the author of that article, thank you for letting us know which one it was.

**Comment by alexhomer1** [comment]
Thank you for your feedback. I have passed this on to the product team for advice.

**Comment by alexhomer1** [comment]
Bugs and issues related to the product rather than the documentation are best posted on the Developer Community website at https://developercommunity.visualstudio.com/spaces/21/index.html, where they are tracked by the product teams. Please post your feedback there. Thank you.
