### ISSUE TITLE
Documentation should be updated for Microsoft Credential Provider (msbuild, dotnet.exe & nuget.exe support)

### ISSUE THREAD

**Issue by rrelyea** [MicrosoftDocs/vsts-docs#3348]
Seems like this page (and perhaps others) should point toward the Microsoft Credential Provider that works with nuget in all CLI code paths (NuGet.exe, msbuild, dotnet.exe)
https://github.com/Microsoft/artifacts-credprovider 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec99483d-828e-093b-a5af-bd2d25ea27d1
* Version Independent ID: 36f67ced-654b-3cbb-2f4e-4f7b540959ba
* Content: [Publish a NuGet package from the command line](https://docs.microsoft.com/en-us/azure/devops/artifacts/nuget/publish?view=azure-devops&tabs=new-nav)
* Content Source: [docs/artifacts/nuget/publish.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/artifacts/nuget/publish.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by lnicolae** [comment]
when i try 
nuget.exe push -Source {NuGet package source URL} -ApiKey key {your_package}.nupkg
from console:
error:
Pushing ConsoleApp2.1.0.1.nupkg to 'https://www.nuget.org/'...
  PUT https://www.nuget.org/api/v2/package/
  Forbidden https://www.nuget.org/api/v2/package/ 873ms
Response status code does not indicate success: 403 (The specified API key is invalid, has expired, or does not have permission to access the specified package.).
KEY IS VALID WAS GENERATED 2 minute before the command line

**Comment by lnicolae** [comment]
PS I use nuget.exe 5.3.1

**Comment by ramiMSFT** [comment]
@rrelyea Thank you for your feedback. An updated version of the article will be deployed shortly.
