### ISSUE TITLE
Where did docs on counters go?

### ISSUE THREAD

**Issue by natemcmaster** [MicrosoftDocs/vsts-docs#3350]
This doc says

&gt; For more information about counters and other expressions, see [expressions](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/expressions?view=azure-devops)

But the 'expressions' page says nothing about counters.

There used to be a section about counters (see https://github.com/MicrosoftDocs/vsts-docs/blob/68a6952c8bc0f647648b217d5c0d49e24ebd121d/docs/pipelines/process/variables.md#counters). This was removed in https://github.com/MicrosoftDocs/vsts-docs/commit/0b64c24e4f3f6c98bfc782b534bce2cfbe9c8798 by @vijaymatest1. Was this intentional?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd7e0bd3-1f7d-d7b6-cc72-5ef63c31b46a
* Version Independent ID: dae87abd-b73d-9120-bcdb-6097d4b40f2a
* Content: [Variables - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch)
* Content Source: [docs/pipelines/process/variables.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/variables.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by vijayma** [comment]
Please stay tuned for an update on the expressions doc. That will roll out later this week.

**Comment by sumptersmartt** [comment]
I'm also interested in the counter documentation. Thank you @natemcmaster for pointing me in the right direction.

**Comment by andyjlewis** [comment]
Thank you for reporting this issue. I believe it's been fixed: https://docs.microsoft.com/en-us/azure/devops/pipelines/process/expressions?view=azure-devops#counter
