### ISSUE TITLE
Add example repo that actually has pipeline support

### ISSUE THREAD

**Issue by jseward** [MicrosoftDocs/vsts-docs#3351]
The linked example repo `https://github.com/adventworks/cpp-sample` does not have `azure-pipelines.yml`. The documentation here recommends using the designer which is not optimal for just seeing an example `yaml` file.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 02b0c082-81b3-79af-8841-8b3033dedf4a
* Version Independent ID: de8aab33-f9ef-0d8d-dbbc-49e23930f1c6
* Content: [C++ - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/apps/windows/cpp?view=azure-devops)
* Content Source: [docs/pipelines/apps/windows/cpp.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/apps/windows/cpp.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by andyjlewis** [comment]
Thank you for the suggestion. I've added it to our backlog.
