### ISSUE TITLE
Where is the variables tab?

### ISSUE THREAD

**Issue by jseward** [MicrosoftDocs/vsts-docs#3354]
I feel like I've searched everywhere for the "variables tab" on an existing pipeline.

```
Tip: Declare a build variable such as BuildConfiguration on the Variables tab (selecting Allow at Queue Time)
```

I can add variables when I go through the "Queue" button, but how can I specify multiple variables (`debug,release`) for the pipeline to use at all times?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 29f86c97-f534-50ad-bfb1-a2cf78c7af94
* Version Independent ID: acea40e3-512b-4d9a-9389-71b8b24327be
* Content: [Visual Studio Build build and release task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/visual-studio-build?view=azure-devops)
* Content Source: [docs/pipelines/tasks/build/visual-studio-build.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/build/visual-studio-build.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by jseward** [comment]
ok, look to have found it.

1. `Edit` button top right (opens up `/azure-pipelines.yml` for editing so I ignored this page)
2. From here click the new `...` -> `Pipeline Settings`

It really feels like `Pipeline Settings` should be accessible directly.

**Comment by vijayma** [comment]
Variables tab has now been prominently added on both YAML and classic pipelines. This has been addressed in the product.
