### ISSUE TITLE
Expose environment variables as parameter of a task group

### ISSUE THREAD

**Issue by ggirard07** [MicrosoftDocs/vsts-docs#3355]
Just tried to add some environment variable in a PowerShell task included in a task group were the values of those were in fact references to other variables.
I expected those variables used as environment variable values to pop as parameters on my task group but nothing.

Is this supported?
Can you explain more how environment variables are loaded and to why this case is not working?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a0e444c2-69c6-4d71-6fd0-94d0f4097d3a
* Version Independent ID: 3a727833-1cc3-c2fb-c5b3-22605eee2721
* Content: [PowerShell task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/powershell?view=azure-devops)
* Content Source: [docs/pipelines/tasks/utility/powershell.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/utility/powershell.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by vtbassmatt** [comment]
I'm not quite following what you want to do. Can you give me a more concrete example or perhaps if it's a YAML pipeline, paste in a snippet of your YAML? Thanks!

**Comment by ggirard07** [comment]
Root cause of my issue was bad PowerShell syntax. I found a way to achieve what I wanted without using environment variable.

But in case someone needs it, what I initially wanted to achieve was something like:
![image](https://user-images.githubusercontent.com/2625886/52879458-2b39ac00-312d-11e9-9b1e-8b5dffa2b4c7.png)
But in this case `$(SomeInput)` is not displayed as a task group parameter.

**Comment by chtay1** [comment]
This is closed but is actually an issue. Task groups do not detect as parameters to the task group variables that are supplied to the Environment Variables section of a powershell task. I'm not sure how to work around this.

**Comment by PatrickTetz** [comment]
Has this been fixed? @vtbassmatt has closed the issue because the original author bypassed the problem. However we're invoking PS from a file and don't have that option. Arguments specified via "Environment Variables" do not generate a parameter for the task group.

**Comment by vtbassmatt** [comment]
You can file this as a feature request on [Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html). In full transparency, we aren't making any investments in classic Build right now, so it's unlikely to get prioritized. With enough demand (as evidenced by people piling on there), we could consider it, though. Thanks.
