### ISSUE TITLE
Title Incorrect

### ISSUE THREAD

**Issue by bogan** [MicrosoftDocs/vsts-docs#3357]
The title of the article is called "Develop code ...". This is incorrect. You don't develop code, you write it. Instead, it is software that you develop, not code. The title should be "Write code..." or alternatively just "Code....

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 13a6dc12-5086-e93c-e198-898fb49c44a3
* Version Independent ID: a2a75ab4-2038-6ce2-77bf-28670deb5676
* Content: [Develop code and manage pending changes - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/tfvc/develop-code-manage-pending-changes?view=azure-devops)
* Content Source: [docs/repos/tfvc/develop-code-manage-pending-changes.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/repos/tfvc/develop-code-manage-pending-changes.md)
* Product: **devops**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by apawast** [comment]
Hi @bogan. I agree that the exact definition of 'develop' is what you said, however, I feel that in this context it is more about the implications of the word and how the developing community often uses or interprets it. Thank you for your feedback!
