### ISSUE TITLE
Azure DevOps ricing

### ISSUE THREAD

**Issue by KNShrinidhi** [MicrosoftDocs/vsts-docs#3358]
Spelling mistake in Pricing 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9433f55f-62e8-c143-539d-f1e03dea0bb3
* Version Independent ID: 14911897-df06-41a9-1d47-c5f8f61ae7e9
* Content: [Add a user who can buy extensions - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/billing/add-backup-billing-managers?view=azure-devops)
* Content Source: [docs/organizations/billing/add-backup-billing-managers.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/billing/add-backup-billing-managers.md)
* Product: **devops**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
@KNShrinidhi, Thanks so much for the heads up. I've pushed an update to master, which should go live sometime this afternoon! Thanks again!
