### ISSUE TITLE
Did we removed "Hosted Linux Preview Pool"

### ISSUE THREAD

**Issue by SychevIgor** [MicrosoftDocs/vsts-docs#3359]
"The Hosted Linux Preview Pool is deprecated and will be removed in December 2018."
If it was removed- we must drop "will be" and replace on "was". If it wasn't removed- it also should be reflected.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 99af681d-41ad-da15-0b72-08b5cd5a11ac
* Version Independent ID: 2fa0df36-a437-8cbb-b019-b49b31b1e116
* Content: [Microsoft-hosted agents for Azure Pipelines - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/agents/hosted.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/agents/hosted.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by vtbassmatt** [comment]
Yep, it's gone. Updating.
