### ISSUE TITLE
Documentation makes assumptions

### ISSUE THREAD

**Issue by TwoSeven99** [MicrosoftDocs/vsts-docs#3360]
This documentation makes assumption that the user is an expert in the tools being discussed and contains ambiguous statements.

For example:  1.Go to the Agent pools control panel tab:
And
2.In your web browser, sign in to Azure Pipelines, and navigate to the Agent pools tab

In Azure Devops above instructions dont seem to match the product.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43799c5d-2f13-cc76-a1c0-a3f850e16d4e
* Version Independent ID: 97a5b73f-faf7-f9c0-9269-fc79984616d6
* Content: [Deploy a build and release agent on Windows - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/v2-windows?view=azure-devops)
* Content Source: [docs/pipelines/agents/v2-windows.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/agents/v2-windows.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by vinothkumarb4u** [comment]
Ok in

**Comment by vtbassmatt** [comment]
@TwoSeven99 - I'm open to feedback on this topic (and made a few small tweaks while I was looking at it). But I'm not sure what to do with your feedback.

Everywhere that we instruct you to "go to the Agent Pools tab", it lists the 4 URLs that are possible depending on what version you're running. What's missing? Thanks!
