### ISSUE TITLE
Provide some description of available projects

### ISSUE THREAD

**Issue by SychevIgor** [MicrosoftDocs/vsts-docs#3361]
Please, add some list of available templates to import. Our team need an information to discuss before we will start deployment.  Now can see a description only during the process 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: effb8fd9-ac4a-e3aa-f8bd-62cc45db3d62
* Version Independent ID: bdd12bec-6789-4178-cc6a-c3c31ae18459
* Content: [What is the Azure DevOps Services Demo Generator?](https://docs.microsoft.com/en-us/azure/devops/demo-gen/?view=azure-devops)
* Content Source: [docs/demo-gen/index.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/demo-gen/index.md)
* Product: **devops**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

![image](https://user-images.githubusercontent.com/578954/52774201-bfccdd00-304d-11e9-8751-5a27f6aae8a9.png)

**Comment by hsachinraj** [comment]
I have updated the doc. Thanks for the feedback.
