### ISSUE TITLE
Incorrect definition for custom field naming

### ISSUE THREAD

**Issue by AndrewChill** [MicrosoftDocs/vsts-docs#3363]
This article incorrectly states that a custom field would have a reference name of "{ProcessName}.{FieldName}", when in practice my custom field had a reference name of "Custom.{FieldName}".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aa7a0948-ee09-8734-ed6e-bc45bd78ce01
* Version Independent ID: da9ac11c-958d-f5dd-efad-0c20c2d7cf2f
* Content: [Describes work item fields, attributes and how to list them - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/work-items/work-item-fields?view=azure-devops)
* Content Source: [docs/boards/work-items/work-item-fields.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/boards/work-items/work-item-fields.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by danhellem** [comment]
Thanks Steve, we will get this fixed

**Comment by KathrynEE** [comment]
@AndrewChill - Thank you for the feedback. You are correct and I'll be updating the topic to reflect same.

**Comment by scuba6388** [comment]
Still not updated.  Spent a lot of time troubleshooting because of this.
