### ISSUE TITLE
Small typo

### ISSUE THREAD

**Issue by mwittenbols** [MicrosoftDocs/vsts-docs#3364]
At the bottom in the Advanced Options section: 

"(Optional) The maximum amount of memory available to the container as a integer with optional suffixes; for example, 2GB."

It should read: as aN integer

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d9dbf88-7e55-d427-145e-d36b04fb197f
* Version Independent ID: a3f30c00-817c-9c05-7a57-3f2bf618821e
* Content: [Docker task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/docker?view=azure-devops)
* Content Source: [docs/pipelines/tasks/build/docker.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/build/docker.md)
* Product: **devops**
* GitHub Login: @steved0x
* Microsoft Alias: **shasb**

**Comment by shashankbarsin** [comment]
@mwittenbols we've updated the documentation to reflect the major version task upgrade we announced recently in the form of Docker@2. I'm hoping we haven't made any typos in this document 🙈. But either ways thanks for reporting the typo in the previous version of the document!
