### ISSUE TITLE
Bulk modify of Stages

### ISSUE THREAD

**Issue by mguirao** [MicrosoftDocs/vsts-docs#3365]
I have my release pipeline defined with a total of 7+ stages/environment. All are clones of each other with a change in the service endpoint to deploy (aka Azure Subscription).
I'm doing a modification in the pipeline to add a step and i want to add it for all stages, today i'm doing it one by one.
Are you planning to add a bulk modifier in order to do it 1 time for all stages since they are supposed to be all the same (almost) ?
Regards,
Michael

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d589bb13-a51a-77a5-d2f0-f424e42ede04
* Version Independent ID: 7b250082-a9c0-7dc2-9381-d04fbc5b7624
* Content: [Define a multi-stage CD release pipeline - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/define-multistage-release-process?view=azure-devops#extend-a-release-pipeline-by-adding-stages)
* Content Source: [docs/pipelines/release/define-multistage-release-process.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/release/define-multistage-release-process.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment]
Thank you for your feedback. Issues, suggestions, and feature requests related to the product rather than the documentation are best posted on the Developer Community website at https://developercommunity.visualstudio.com/spaces/21/index.html, where they are tracked by the product teams. Please post your feedback there. Thank you.
