### ISSUE TITLE
Doc needed: Who is the requester in a continuous deployment triggered release?

### ISSUE THREAD

**Issue by beachseeker** [MicrosoftDocs/vsts-docs#3366]
This should be documented in the Approval policies section.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fc105eb0-4766-77a1-dfec-c0cc2b4b3f08
* Version Independent ID: 8bd8c066-745b-5c89-39c3-bb0a959cb7a2
* Content: [Control deployments by using approvals - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/approvals/approvals?view=azure-devops)
* Content Source: [docs/pipelines/release/approvals/approvals.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/release/approvals/approvals.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment]
Thank you for your feedback. I havce added a link to this topic: https://docs.microsoft.com/azure/devops/pipelines/build/variables#how-are-the-identity-variables-set which explains how the identity is determined.
