### ISSUE TITLE
regarding TFS 2018 and TFS 2017 compatibility with Windows Server 2019

### ISSUE THREAD

**Issue by RamprasathSaminathan** [MicrosoftDocs/vsts-docs#3368]
Is TFS 2017 and TFS 2018 supported with Windows Server 2019 ?

As per the https://docs.microsoft.com/en-us/windows-server/get-started-19/app-compat-19 its supported. But as per https://docs.microsoft.com/en-us/tfs/server/requirements#operating-systems, we dont mention anything about its supportablity. If supported, can we have the document updated ?

**Comment by steved0x** [comment]
@aaronhallberg Can you take a look at this one?

**Comment by RamprasathSaminathan** [comment]
Hi @aaronhallberg ,  just checking if you have any update on this.

**Comment by KathrynEE** [comment]
@RamprasathSaminathan - Thank you for your inquiry. The topic is up to date. TFS 2017 and TFS 2018 are not supported with Windows Server 2019.
