### ISSUE TITLE
Documentation does not explain how the artefacts from the previous build (which compiles the source) to the docker image.

### ISSUE THREAD

**Issue by cyberjacob** [MicrosoftDocs/vsts-docs#337]
Documentation does not explain how the artefacts from the previous build (which compiles the source) to the docker image.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0fc9593a-77be-75c1-8d20-86a995d925f6
* Version Independent ID: 63c81326-3b7a-8452-bc04-95ff06e517a7
* Content: [Build and push a Docker image | Microsoft Docs](https://docs.microsoft.com/en-us/vsts/build-release/apps/containers/build?tabs=web)
* Content Source: [docs/build-release/apps/containers/build.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/build-release/apps/containers/build.md)
* Service: **unspecified**
* GitHub Login: @douge
* Microsoft Alias: **alewis**

**Comment by stewartadam** [comment]
+1 after navigating through a maze of documentation, the different articles don't connect up so the build is successful but nothing is present on the release agent node, causing Docker tasks to fail.

**Comment by andyjlewis** [comment]
This doc has been updated.
