### ISSUE TITLE
Can we Use Deployment Groups to Deploy to  On-Premise Production Servers?  Is It Secure?

### ISSUE THREAD

**Issue by denhsu** [MicrosoftDocs/vsts-docs#3370]
Hi,
We are trying to figure out a secure way to deploy web app from Azure DevOps to our on-premise environments (Dev, QA, Staging, and Prod).

Using deployment groups, we are kind of making the target serverd in production environment as private agent and listening for jobs. Our security team has issue with this design.  Is there any security page for deployment groups? What port they use?  I wonder if Azure DevOps product team use deployment groups to deploy apps to their on-premise "production" server?  Any best practice?

The other deployment method from AzDO to on-premise is to use the WinRM way. https://docs.microsoft.com/en-us/azure/devops/pipelines/apps/cd/deploy-webdeploy-iis-winrm?view=azure-devops

We are trying to setup servers like design with line of sight (https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/agents?view=azure-devops#communication-to-deploy-to-target-servers), but we encountered issues with WinRM task (missing functionality) and just need to open many firewalls per server.  It just seems too much effort require for deploying each app, so we prefer to use the Deployment Groups way and just need to get our Security team onboard.   
Is it possible to use deployment groups with line of sight setup? 

Any feedback is welcome.

Thanks,
Dennis

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3b38c265-be4c-b038-e3a9-783a5e5ce659
* Version Independent ID: 67da69da-3651-a8f4-f06a-c35aa3aa98fc
* Content: [Use deployment groups in a release pipeline - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/deployment-groups/?view=azure-devops)
* Content Source: [docs/pipelines/release/deployment-groups/index.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/release/deployment-groups/index.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by RoopeshNair** [comment]
In case of deployment group, you install the agents directly on the target servers. The agents need to have line-of-sight to Azure DevOps.

![image](https://user-images.githubusercontent.com/1370480/52856474-81691800-314a-11e9-98a9-4a898a177d3e.png)


Deployment groups work in pull model unlike WinRM which needs opening the firewall ports.  The [communication model is same](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/agents?view=azure-devops#communication) as the agent used in deployment group is same except that it is registered with a deployment group. You configure the agents with https 443. The payload of the messages exchanged between the agent and Azure Pipelines/TFS are secured using asymmetric encryption. Each agent has a public-private key pair, and the public key is exchanged with the server during registration. The server uses the public key to encrypt the payload of the job before sending it to the agent.

**Comment by denhsu** [comment]
Thanks @RoopeshNair! Great information.  As a follow up, I wonder if MS security team approve the use of deployment groups on production server to deploy apps to on-premise? This is our current issue with our security team.  Any insight is appreciated.

**Comment by smetsth** [comment]
@denhsu Are you running the agent on production?

**Comment by gautamksr** [comment]
@RoopeshNair @denhsu - I can see this thread had been closed. I have same query and my security team has asked. Will it be safe to allow ADO agent url (for deployment) and install the deployment agent to on-premise "production" environment?  If any one has answer please share. Thanks in advance.
