### ISSUE TITLE
Can you get the public tier build limits if your repo is hosted on github ?

### ISSUE THREAD

**Issue by clmcgrath** [MicrosoftDocs/vsts-docs#3372]
We have a repo hosted in github and we have a pipelines only project in azure devops set to public,  
does the repo have to be hosted on azure devops to get the public tier build agent limit ? we are currently still queueing in private  tier even tho our build project is public 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8b846aea-82f7-a988-67d8-1b5e74b61ed2
* Version Independent ID: 2d632729-bb33-c0a0-c996-e1d8e86c2e23
* Content: [Build Azure Repos Git repositories - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/azure-repos-git?view=azure-devops)
* Content Source: [docs/pipelines/repos/azure-repos-git.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/repos/azure-repos-git.md)
* Product: **devops**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
@clmcgrath Sorry for the delay, we have updated the GitHub article to cover this scenario. If both your GH repo and your project are public, you get the public limits. See [Public GitHub repository and Azure Pipelines in a public project](https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/github?view=azure-devops&tabs=yaml#public-github-repository-and-azure-pipelines-in-a-public-project)

Are you still getting the private tier queuing? If your pipeline is in a public project, and your GH repo is public, it sounds like there may be a product issue. If this is still an issue, please reactivate this GH issue and @mention me and I will follow up and get you an answer ASAP.
