### ISSUE TITLE
Can't add inherited WIT to a backlog

### ISSUE THREAD

**Issue by dezdez** [MicrosoftDocs/vsts-docs#3376]
This page indicates that you can 'add WITs' to backlogs. But you actually can't add existing WITs that are inherited. This is explicitly stated in the article below, but should also be stated here to prevent frustration & confusion.

https://docs.microsoft.com/en-us/azure/devops/organizations/settings/work/inheritance-process-model?view=azure-devops

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2b6067a-50a8-dc02-fc43-8f55527b507c
* Version Independent ID: 3287e2ac-ef6d-3f52-47f4-1b337cfc077f
* Content: [Customize backlogs and boards - Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/organizations/settings/work/customize-process-backlogs-boards?view=azure-devops&tabs=new-nav)
* Content Source: [docs/organizations/settings/work/customize-process-backlogs-boards.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/settings/work/customize-process-backlogs-boards.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by chcomley** [comment]
@dezdez, Thank you for the heads up! I've created a user story for this update, slated for completion in March 2019. I'm closing this issue, however, please let me know if you have any other feedback or questions. Thanks again!
