### ISSUE TITLE
How am I supposed to create the file share?

### ISSUE THREAD

**Issue by landrus** [MicrosoftDocs/vsts-docs#3377]
What is completely missing here is the part where the build agent gets the share or authenticates against the share. If I want to use the Azure Storage File share (which is easily setup), I have no way to connect that share to a build agent. And this task has no authentication information as well, so this suggests it requires an already connected share.

But again, HOW to connect the file share to the agent. Without this information the file share task is unusable.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 475548ee-1af8-7ef5-bb8c-7efaed9598a2
* Version Independent ID: 0108f9da-6b28-54f2-ee15-e030a0a1daa2
* Content: [Download Fileshare Artifacts task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/download-fileshare-artifacts?view=azure-devops)
* Content Source: [docs/pipelines/tasks/utility/download-fileshare-artifacts.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/utility/download-fileshare-artifacts.md)
* Product: **devops**
* GitHub Login: @steved0x
* Microsoft Alias: **omeshp**

**Comment by RoopeshNair** [comment]
@landrus - This task isn't for downloading from Azure File Share. It is to download the [artifacts published during Azure DevOps Build Pipeline](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/publish-build-artifacts?view=azure-devops). 

Using publish artifacts during build, you have an option of storing it in a file share path or to a server drop.  DownloadFileShare Artifacts task downloads from the file share specified.
