### ISSUE TITLE
Branch is not deleted once pull request is accpeted

### ISSUE THREAD

**Issue by ravick4u** [MicrosoftDocs/vsts-docs#3379]
Even after checking "Delete &lt;branch name&gt; after merging" branch is not deleted.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 028e7b61-62e4-a10e-e420-3535f7843f0e
* Version Independent ID: 1a6fdbe7-5ba4-a7f8-1b2e-271289a7b9fd
* Content: [Review and merge code with pull requests - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/pull-requests?view=azure-devops&tabs=new-nav#update-code-in-response-to-feedback)
* Content Source: [docs/repos/git/pull-requests.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/repos/git/pull-requests.md)
* Product: **devops**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
@ravick4u Thank you for letting us know. This issue should not be happening, source PR branches should be deleted if that box is checked. Note that the branch is deleted on the server, and you must delete your local branches (for example by running `git fetch --prune`). If it is still happening, please file a request at https://developercommunity.visualstudio.com/spaces/21/index.html

Thank you
