### ISSUE TITLE
Couple pieces of feedback

### ISSUE THREAD

**Issue by weshaggard** [MicrosoftDocs/vsts-docs#3380]
1) Doc states variable groups are only available for release pipelines but we can use them in build pipelines now as well so we should update that section.

2) For security it isn't clear if the Creator role also implies user role as well. I'm seeing some issues with some users which I believe have creator roles but cannot view the variable groups when trying to link to a build pipeline and the tooltip says they need user role access to be able to view the variable groups to link one. Clarification of the docs would be good. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f2fe2521-cc98-8946-89b4-5a8199a6d898
* Version Independent ID: dbc4b6cf-ddb1-ac16-c634-eaf15072e111
* Content: [Library for Azure Pipelines and Team Foundation Server - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/library/index?view=azure-devops#security)
* Content Source: [docs/pipelines/library/index.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/library/index.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment]
Thank you for your feedback. I will update the topic to include your recommendations.
The Creator role does not include Reader or User permissions - these must be explicitly provided in addition to the Creator role.

**Comment by weshaggard** [comment]
It would also be nice to add some documentation on how to grant both Creator and User permissions as I've not been able to figure out how to grant both as it is a drop down to pick one or the other.
