### ISSUE TITLE
PublishBuildArtifacts appears to publish sub-directories

### ISSUE THREAD

**Issue by weshaggard** [MicrosoftDocs/vsts-docs#3381]
Doc says `Subdirectories of the specified path will not be published. Wildcards in the path are not supported. ` but from my testing that appears to be incorrect it definitely appears to be publishing all files and sub-directories under the path that is given to it. So either the documentation is incorrect or the product has a bug.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b3f565b-88e4-88d6-a534-48ec21e6e3d8
* Version Independent ID: 9fca89ae-4a6e-a43a-2834-1a91ad44c256
* Content: [Publish Build Artifacts task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/publish-build-artifacts?view=azure-devops)
* Content Source: [docs/pipelines/tasks/utility/publish-build-artifacts.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/utility/publish-build-artifacts.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by weshaggard** [comment]
For what it is worth I found the code in the task that explicitly passes `/E` (https://github.com/Microsoft/azure-pipelines-tasks/blob/master/Tasks/PublishBuildArtifactsV1/Invoke-Robocopy.ps1#L61)  to robocopy which does the copying so it would seem that it does support it.

**Comment by davidstaheli** [comment]
Thanks for reporting this. We're going to move this issue to this repo:
https://github.com/Microsoft/azure-pipelines-tasks

/move to Microsoft/azure-pipelines-tasks
