### ISSUE TITLE
add custom upstream source in TFS 2018

### ISSUE THREAD

**Issue by gforceg** [MicrosoftDocs/vsts-docs#3382]
This feedback is related to the article: https://docs.microsoft.com/en-us/azure/devops/artifacts/concepts/upstream-sources?view=tfs-2018

> NOTE: Custom upstream sources are currently only supported for npm.

**Does this mean I can plug in a custom URL instead of registry.npmjs.com?** [issue 2845](https://github.com/MicrosoftDocs/vsts-docs/issues/2845) alludes to this functionality.

I can't seem to find the feature in TFS 2018 or Azure Devops Server RC2.

**Comment by steved0x** [comment]
@gforceg I moved your issue to here and closed this one.
