### ISSUE TITLE
Incorrect sentence

### ISSUE THREAD

**Issue by FrankAtHexagon** [MicrosoftDocs/vsts-docs#3383]
In the first section, the first "checkbox" says the following: "Use gitignore to prevent tracking or files". Shouldn't the "or" be "of"?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b3f73e6a-75c9-6a8d-c2e1-08feeb9700c1
* Version Independent ID: 80570118-9b20-9999-6464-6e9e522c1ab7
* Content: [Ignore files in your Git repo - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/ignore-files?view=azure-devops&tabs=visual-studio)
* Content Source: [docs/repos/git/ignore-files.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/repos/git/ignore-files.md)
* Product: **devops**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
@FrankAtHexagon It should, thank you for letting us know.
