### ISSUE TITLE
Some additional content would be helpful

### ISSUE THREAD

**Issue by ravensorb** [MicrosoftDocs/vsts-docs#3384]
It would be helpful if there was a list of steps to completely remove a connection from the Visual Studio IDE

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a12963af-3340-7a74-569e-47bd40632262
* Version Independent ID: a23b6117-0cbe-0104-e820-ac88817624ee
* Content: [Troubleshoot connecting project - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/user-guide/troubleshoot-connection?view=azure-devops)
* Content Source: [docs/user-guide/troubleshoot-connection.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/user-guide/troubleshoot-connection.md)
* Product: **devops**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
@ravensorb, Thanks for your comment. I've created a user story, so I can look into this further. I'll be in touch. Thanks again.

**Comment by StingyJack** [comment]
@ravensorb - in your c:\users\_<user name>_\AppData\Roaming\Microsoft\VisualStudio\_<vs version number>_\Team Explorer folder there is a `TeamExplorer.confg` file. Thats the list of connections that VS has stored for connections.

VS Version number will sometimes be followed by a few letters like "16.0_365cef21". When I have had to troubleshoot connectivity issues, I will close all VS windows (check for orphan processes in task manager like msbuild.exe, etc and kill them too), and then just rename this file. Then I can re-add the connections I want.

**Comment by chcomley** [comment]
@ravensorb Please let us know whether you have any further questions, thanks!

**Comment by ravensorb** [comment]
Ok, so the only option right now is to edit that file?

**Comment by StingyJack** [comment]
No, you can remove connections by using the VS UI, but it's not a consistent experience

**Comment by chcomley** [comment]
Hi @ravensorb, it appears that @StingyJack has answered your question. I'll be closing this issue, however if you still feel that the documentation needs more information, please chime in on [this issue](https://github.com/MicrosoftDocs/vsts-docs/issues/4085) and we'll address it there. We appreciate it, thank you.
