### ISSUE TITLE
add custom upstream source in TFS 2018

### ISSUE THREAD

**Issue by steved0x** [MicrosoftDocs/vsts-docs#3386]
@gforceg From: https://github.com/MicrosoftDocs/vsts-docs/issues/3382

This feedback is related to the article: https://docs.microsoft.com/en-us/azure/devops/artifacts/concepts/upstream-sources?view=tfs-2018

&gt; NOTE: Custom upstream sources are currently only supported for npm.

**Does this mean I can plug in a custom URL instead of registry.npmjs.com?** [issue 2845](https://github.com/MicrosoftDocs/vsts-docs/issues/2845) alludes to this functionality.

I can't seem to find the feature in TFS 2018 or Azure Devops Server RC2.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d5f022df-36c3-34b1-cac1-ac33995a7d73
* Version Independent ID: 9634b0c8-7b14-4453-2c04-aedabbf331f1
* Content: [Upstream sources](https://docs.microsoft.com/en-us/azure/devops/artifacts/concepts/upstream-sources?view=tfs-2018)
* Content Source: [docs/artifacts/concepts/upstream-sources.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/artifacts/concepts/upstream-sources.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by chasewilson** [comment]
@elbatk, Custom npm upstream sources available in on prem versions?

**Comment by chasewilson** [comment]
This currently isn't available for on prem versions up to and including Azure DevOps Server 2019. I'll update to moniker the article and it won't show as an available feature. I'm closing this issue and thank you for the input!
