### ISSUE TITLE
Is Hosted Windows2016 with containers pool ?

### ISSUE THREAD

**Issue by jjindrich** [MicrosoftDocs/vsts-docs#3389]
I need to build windows image based on lts-2016. If I use Windows container host, it will fail because of win1803. Please can you publish Hosted Windows2016 container ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 99af681d-41ad-da15-0b72-08b5cd5a11ac
* Version Independent ID: 2fa0df36-a437-8cbb-b019-b49b31b1e116
* Content: [Microsoft-hosted agents for Azure Pipelines - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml#use-a-microsoft-hosted-agent)
* Content Source: [docs/pipelines/agents/hosted.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/agents/hosted.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by thejoebourneidentity** [comment]
What is failing? Building the container or running the container? You should be able to build the container as long as you are targetting the right base https://hub.docker.com/_/microsoft-windows-servercore

To run the container, you'll need to run it with Hyper V isolation: https://docs.microsoft.com/en-us/virtualization/windowscontainers/manage-containers/hyperv-container
