### ISSUE TITLE
Anonymous access

### ISSUE THREAD

**Issue by MichelZ** [MicrosoftDocs/vsts-docs#3390]
This one does not exist anymore in Azure DevOps (Online)

It now states:

Security policies:
External guest access
Allow public projects
Enable Azure Active Directory Conditional Access Policy Validation

You might want to update this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a18e09c1-5c84-4fd6-9d62-2299a3bd53cd
* Version Independent ID: c1627714-5e55-1be0-4ba5-63f264b96e5c
* Content: [Change application access policies for organizations - Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/change-application-access-policies?view=azure-devops&viewFallbackFrom=vsts)
* Content Source: [docs/organizations/accounts/change-application-access-policies.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/accounts/change-application-access-policies.md)
* Product: **devops**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
I've created a user story on my backlog for this update. Thanks for reaching out and thanks for the heads up! Much appreciated.
