### ISSUE TITLE
Documentation is totally out of sync and complexity of the libraries make it almost impossible to use

### ISSUE THREAD

**Issue by LennartAJansson** [MicrosoftDocs/vsts-docs#3391]
Hi,
I've been working with creating tools for TFS since 2008 version and it feels like the libraries are growing like a Hydra, chop of one head and two new will be created. At the same time the documentation is decreasing so you have to make a lot of assumptions and wild guesses most of the time. That has led me to try the hardest to skip using the libraries and simply use my own http/https wrappers directly against the REST API, I only use the libraries where it's in any other way impossible to accomplish what I need (mostly working with the security model, altering groups, users, rights etc). Isn't the libraries ment to be a support to the users? Imagine buying a new car and not get any service or even a manual to read for it, comparison is valid because if you have any questions there's noone answering, only the same mantra: "I will add this and that person to the question", but after that, only a big silence!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 413163f0-28c3-a2a7-d626-fcb81bcb2257
* Version Independent ID: 57c127da-2b1e-d29e-9abb-a3c258762ccf
* Content: [.NET Client Libraries for Azure DevOps Services (and TFS)](https://docs.microsoft.com/en-us/azure/devops/integrate/concepts/dotnet-client-libraries?view=azure-devops#known-issues)
* Content Source: [docs/integrate/concepts/dotnet-client-libraries.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/integrate/concepts/dotnet-client-libraries.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by willsmythe** [comment]
@wnjenkin - one "easy" fix is adding links to the .NET reference (https://docs.microsoft.com/dotnet/api/index?view=azure-devops-dotnet) and .NET samples (https://github.com/microsoft/vsts-dotnet-samples). 

This page should be reorganized as *the* landing page for .NET developers (wanting to integrate with Azure DevOps). Currently the page is focused on the client packages, which are obviously important but not the "lead story". A better starting point would be a good reference example that then links into the packages, other samples, and reference.

**Comment by chcomley** [comment]
Hi @LennartAJansson, I've created a user story on my backlog to capture this work and will be in touch. Thanks so much for the feedback.

**Comment by chcomley** [comment]
Hi @LennartAJansson, This content update is slated for "future," so I wanted to let you know that I'll be closing this issue, however, once the updated content is published, you'll be notified via this thread. Thanks for helping us to help others better.
