### ISSUE TITLE
PublishPipelineArtifact not available in release pipelines

### ISSUE THREAD

**Issue by BrianVallelunga** [MicrosoftDocs/vsts-docs#3392]
It's hard to tell from the docs and comments, but is PublishPipelineArtifact working right now? I ask because while it doesn't error, I can't tell where the artifacts are actually published. The logs simply state that the files are uploaded to the "Drop service."

In theory they're supposed to be available in the release pipelines, and when I go through the steps to import the artifacts into a release pipeline, everything appears to work. However, when the release pipeline tries to use an artifact there are none to be found.

For example, I'm publishing an ARM template as an artifact and the UI picker let's me select the artifact file with a path of:

$(System.DefaultWorkingDirectory)/my-build/my-templates/azuredeploy.json

However, there are no sub-directories within $(System.DefaultWorkingDirectory) when my release pipeline gets to that step. I've confirmed this by doing a command line 'dir' on that directory.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 861ce7a5-4fa4-55f1-2c97-46a9cc6a2f66
* Version Independent ID: bdf954b9-9bbe-8b34-b674-71ad8153519d
* Content: [Publish and consume Pipeline artifacts in builds - Azure Pipelines and TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/pipeline-artifacts?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/artifacts/pipeline-artifacts.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/artifacts/pipeline-artifacts.md)
* Product: **devops**
* GitHub Login: @alexmullans
* Microsoft Alias: **amullans**

**Comment by mitchdenny** [comment]
Pipeline Artifacts is working, you can publish and download artifacts. In RM you need to manually add the Download Pipeline Artifact task. This is a point in time problem we are rolling out an update right now that has these tasks automatically injected into your RM jobs just like existing Build Artifacts.

Sorry for the delay getting this feature out - its in the current deployment train and I've verified it in production we just need to wait until it reaches all of our scale units.

**Comment by mitchdenny** [comment]
Just a quick update on this. The Pipeline Artifact V1 task has been rolled out, it is automatically injecting correctly into pipelines, and as an added bonus, with the V1 task you can now select Pipeline Artifacts from other Pipelines.

**Comment by turimbar1** [comment]
I keep getting "Cannot upload to a pipeline artifact from release environment" - am I misunderstanding the meaning of "Publish a local directory or file as a named artifact for the current pipeline." Can we actually publish files from the release directory?

**Comment by mitchdenny** [comment]
Publishing Pipeline Artifacts is not supported from Release pipelines, you can only download in release pipelines.

**Comment by BrianVallelunga** [comment]
Thanks for the updates and I'm happy to see this has been pushed live. I'll go delete my Download Artifact steps now.

**Comment by BrianVallelunga** [comment]
I just tried this and bumped the PublishPipelineArtifact to @1. This resulted in a build error. Is this still not working yet?

**Comment by mitchdenny** [comment]
Download Pipleine Artifacts is V1, Publish is V0. Publish is only available in Build pipelines.

**Comment by BrianVallelunga** [comment]
I'm still confused by this. Do we need to add the DownloadPipelineArtifacts@1 step to a release pipeline if I'm publishing a pipeline artifact with PublishPipelineArtifact@0 in a build pipeline? I thought the download step was supposed to be unnecessary in a release pipeline now.

**Comment by mitchdenny** [comment]
@BrianVallelunga it looks like there are some instances where the feature flag hasn't been enabled. Looking into it.

**Comment by BrianVallelunga** [comment]
> @BrianVallelunga it looks like there are some instances where the feature flag hasn't been enabled. Looking into it. Actually if you e-mail me your org name at midenn at microsoft dot com I'll enable the feature flag whilst we are waiting just whilst I am doing the investigation.

Email sent. Thanks!

**Comment by cforce** [comment]
Is there a working example yml code, that does publishing of at least two files on the first job/agent and then downloads into a second job/agent? Then use the file somehow. I really would to know where files then finally are located in case with and without 'artifact name' set

**Comment by s-bauer** [comment]
@mitchdenny Why is it not possible to publish a pipeline artifact in a release? In AzDo there is currently no way to transfer data between the release phases, other than using universal artifacts (which is not possible in many cases). Or am I missing something?

**Comment by mitchdenny** [comment]
Even though "build" pipelines and "release" pipelines are very similar in terms of task execution, job scehduling etc - there are many higher level differences. One of the differences is that a release pipeline just doesn't have an artifact concept for artifacts produced within the pipeline.

One work around that we have is that you could associate the artifact you are publishing with one of the Build pipeline inputs into your Release pipeline (we don't do this today, just thinking out loud).

We just released the ```az pipelines runs artifact``` command as part of the AZ CLI. If you wanted to you could use this command to upload a Pipeline artifact and associate it with one of your builds as a way of keeping the content (indirectly) associated with the release pipeline.

There are some changes coming around build/release pipelines that might make this a non-issue though. We've got your ask :)

**Comment by s-bauer** [comment]
@mitchdenny Thanks for your fast reply! Is the azure cli part of the default image of a Hosted Agent? If so this could be a viable workaround for now!

**Comment by mitchdenny** [comment]
I think it is, although it might not be running the 0.4.0 version of the CLI right now, but will be soon. In the meantime I'll think about supporting it in the task.

**Comment by cforce** [comment]
$ az pipeline
az: 'pipeline' is not in the 'az' command group. See 'az --help'.

$ az --version
azure-cli                         2.0.61

acr                                2.2.3
acs                               2.3.20
advisor                            2.0.0
ams                                0.4.3
appservice                        0.2.16
backup                             1.2.2
batch                              4.0.0
batchai                            0.4.8
billing                            0.2.1
botservice                         0.1.9
cdn                                0.2.1
cloud                              2.1.1
cognitiveservices                  0.2.5
command-modules-nspkg               2.0.2
configure                         2.0.20
consumption                        0.4.2
container                         0.3.15
core                              2.0.61
cosmosdb                           0.2.9
dla                                0.2.5
dls                                0.1.8
dms                                0.1.3
eventgrid                          0.2.2
eventhubs                          0.3.4
extension                          0.2.4
feedback                           2.1.4
find                               0.3.1
hdinsight                          0.3.2
interactive                        0.4.2
iot                                0.3.7
iotcentral                         0.1.6
keyvault                          2.2.13
kusto                              0.2.1
lab                                0.1.6
maps                               0.3.4
monitor                           0.2.11
network                            2.3.5
nspkg                              3.0.3
policyinsights                     0.1.2
profile                            2.1.4
rdbms                              0.3.9
redis                              0.4.2
relay                              0.1.4
reservations                       0.4.2
resource                          2.1.12
role                               2.4.3
search                             0.1.1
security                           0.1.1
servicebus                         0.3.4
servicefabric                     0.1.15
signalr                            1.0.0
sql                                2.2.0
sqlvm                              0.1.1
storage                            2.3.2
telemetry                          1.0.2
vm                                2.2.17

**Comment by s-bauer** [comment]
@mitchdenny I've tried uploading an artifact using the provided command (`az piplines runs artifact upload --project [...] -run-id [...] --artifact-name [...] --path [...]`), but it always fails telling me:
```
Microsoft.TeamFoundation.Build.WebApi.AccessDeniedException: Access denied. [My Name] needs Update build information permissions for vstfs:///Build/Build/[Build ID] in team project [Project Name] to perform the action.
```
I'm already collection and project admin and see no possibility to grant me the given permission! Can you point me in the right direction?

**Comment by mitchdenny** [comment]
So if you go into your Pipeline definition, on the top right hand corner click the ellipsis button and then select security. A permissions dialog should come up. You can add/search for your identity on the top left of the dialog and then once your identity is in that list you can grant it permission.

The default is that no-one has rights to modify the set of artifacts associated with a build (security reasons).

**Comment by chasewilson** [comment]
I'll be closing this issue for now as it looks like it was resolved in comments. If you have any more questions or feedback, feel free to reach out!
