### ISSUE TITLE
The paragraph about upstream sources is hard to understand.

### ISSUE THREAD

**Issue by kgreed** [MicrosoftDocs/vsts-docs#3393]
Omitting the brackets so I can read more easily the sentence is still hard to understand.
"If you're using upstream sources, package versions in the upstream source that haven't yet been saved into your feed won't appear in the NuGet Package Manager search. To install these packages:"

It has a double negative  : "Haven't yet" and "wont"

Also it introduces "Upstream Sources" to me for the first time. the link does not define what an Upstream Source is.

It would be better if it had something like 

"If you don't see your packages here are some possible causes"

As it happened I did not see my packages. This turned out to be because I missed clicking UPDATE when adding the feed. ( I think)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a10a409-5468-9532-f0dc-5a28cdd566d8
* Version Independent ID: 2ef20266-bc45-448b-27f5-e5c3bffed2ef
* Content: [Get started with NuGet packages in Azure DevOps Services and TFS](https://docs.microsoft.com/en-us/azure/devops/artifacts/get-started-nuget?view=azure-devops&tabs=new-nav#consume-packages)
* Content Source: [docs/artifacts/get-started-nuget.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/artifacts/get-started-nuget.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by kgreed** [comment]
Is an "upstream source" a package source that has been used in the projects that make up the package?

**Comment by elbatk** [comment]
These graphics may help you understand upstream sources a bit more: 
https://docs.microsoft.com/en-us/azure/devops/artifacts/concepts/package-graph?view=azure-devops

Essentially, if you have a feed, "Foo", you can set up upstream sources to other package sources (like npmjs, or nuget.org) to "Foo". "Foo" will then have access to the packages in those sources.

**Comment by chasewilson** [comment]
I'll be closing this issue. Please feel free to open a new issue if the answer provided is still not clear
