### ISSUE TITLE
private npm package in azure devops artifacts

### ISSUE THREAD

**Issue by hoksource** [MicrosoftDocs/vsts-docs#3394]
npm publish has arguments flag "--access restricted" do I have to include this if I want my npm package to be private in azure devops artifacts?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c76bc6d6-8906-d43f-c0d0-ddc40201c635
* Version Independent ID: 9fa2bd0f-9031-7c7e-b2e5-e8cc1c5f966f
* Content: [Publish an npm package](https://docs.microsoft.com/en-us/azure/devops/artifacts/npm/publish?view=azure-devops)
* Content Source: [docs/artifacts/npm/publish.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/artifacts/npm/publish.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by elbatk** [comment]
Hi @hoksource , feeds are currently private by default, so only people that have Package Read permissions in your org would be able to see them.
