### ISSUE TITLE
Provided cURL doesn't support sftp protocol

### ISSUE THREAD

**Issue by noisymime** [MicrosoftDocs/vsts-docs#3396]
Documentation states that sftp is one of the supported protocols for the cURL uploader however attempting to use it results in an error stating: `Protocol "sftp" not supported or disabled in libcurl`

Looks like the included version of cURL was not compiled with sftp support (At least on this image)

Image: vs2017-win2016

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 27c64186-7c87-9eb2-718b-b3913036974e
* Version Independent ID: 109cc272-5926-c8eb-eb30-27e0dada1f28
* Content: [cURL Upload Files task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/curl-upload-files?view=azure-devops)
* Content Source: [docs/pipelines/tasks/utility/curl-upload-files.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/utility/curl-upload-files.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by davidstaheli** [comment]
Thanks for reporting this. We're going to move this issue to this repo for better tracking:
https://github.com/Microsoft/azure-pipelines-image-generation

/move to Microsoft/azure-pipelines-image-generation
