### ISSUE TITLE
Custom variable doesn't get carried forward in consecutive build pipelines

### ISSUE THREAD

**Issue by arefinsami** [MicrosoftDocs/vsts-docs#3397]
Scenario: Two build pipelines and a release pipeline. BuildPipeline2 gets triggered when BuildPipeline1 finishes. ReleasePipeline1 gets triggered when BuildPipeline2 finishes.

BuildPipeline1-&gt;BuildPipeline2-&gt;ReleasePipeline1

Assume a variable $(myVariable) defined and initialized in BuildPipeline1, which needs to be used and updated in BuildPipeline2 and ReleasePipeline1 as well. However, Azure DevOps doesn't seem like to support that. Is there a way to do it? FYI- variable group doesn't work here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd7e0bd3-1f7d-d7b6-cc72-5ef63c31b46a
* Version Independent ID: dae87abd-b73d-9120-bcdb-6097d4b40f2a
* Content: [Variables - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=designer%2Cbatch)
* Content Source: [docs/pipelines/process/variables.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/variables.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by vijayma** [comment]
That is correct. Please open a suggestion on https://developercommunity.visualstudio.com/spaces/21/index.html, as this is a product suggestion and not a doc issue.
