### ISSUE TITLE
How to get previous build pipeline's build number in case of consecutive build pipelines?

### ISSUE THREAD

**Issue by arefinsami** [MicrosoftDocs/vsts-docs#3398]
Assume BuildPipeline2 gets triggered when BuildPipeline1 finishes. 

BuildPipeline1-&gt;BuildPipeline2

When BuildPipeline2 is getting executed is there a way to get BuildPipeline1's build number? I am looking for something like Last.Build.BuildNumber. Os is there a way to pass the BuildPipeline1's build number to BuildPipeline2 ?
Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd7e0bd3-1f7d-d7b6-cc72-5ef63c31b46a
* Version Independent ID: dae87abd-b73d-9120-bcdb-6097d4b40f2a
* Content: [Variables - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=designer%2Cbatch)
* Content Source: [docs/pipelines/process/variables.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/variables.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by cyberblast** [comment]
Share variables across pipelines: https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch#share-variables-across-pipelines

**Comment by arefinsami** [comment]
@cyberblast, I am not sure how this helps. 

In each agent job the variables in a group get reinitialized to the original vcalue defined in the group. The updated value doesn't carry forward. So variable group is not a solution. It needs somehting like Last.Build.BuildNumber.

**Comment by cyberblast** [comment]
you can also simply write it to a file on the agent or into the repo and check it in.

**Comment by levenleven** [comment]
Not sure but you might be looking for `Build.TriggeredBy.BuildId` 
https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml

**Comment by sukoneck** [comment]
Anyone figure this out? I'm in the same boat as @arefinsami

**Comment by sukoneck** [comment]
@benc-uk found the answer [here](https://github.com/MicrosoftDocs/vsts-docs/issues/6350). Here's how to get metadata across pipelines:

1. Define the first pipeline as a [resource](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=example%2Cparameter-schema#pipeline-resource)
2. Call that pipeline's metadata using [this schema](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=example%2Cparameter-schema#the-pipeline-resource-metadata-as-predefined-variables), where `<alias>` is the friendly identifier you defined in the pipeline resource block

Two notes that were helpful for my situation:

3. I was struggling through getting the pipeline trigger to work as expected using YAML, and still haven't. Instead, I removed the pipeline trigger (i.e. the `trigger:` that's within the pipeline resource block) and added a "regular" CI trigger. This does what I want, which is to trigger the second build pipeline off of a change to a repo while also bringing in metadata from the build that changed that repo
4. The metadata that was really what I needed was the first build's `Build.BuildNumber` which translates to `resources.pipeline.<Alias>.runName`

**Comment by ashokirla** [comment]
Thanks for the feedback. We have plans to add support for exposing info about the resource that has triggered the pipeline. We will work on it starting next quarter.

**Comment by PaulCharlton** [comment]
there's another way ... for those who want this information in bash or shell scripts, the environment variables appear to have the following:

```
# identifies upstream pipeline
RESOURCES_PIPELINE_{upstream_pipeline_name}_PIPELINEID
RESOURCES_PIPELINE_{upstream_pipeline_name}_PIPELINENAME
RESOURCES_PIPELINE_{upstream_pipeline_name}_RUNID [ {build#} ]
RESOURCES_PIPELINE_{upstream_pipeline_name}_RUNURI [ vstfs:///Build/Build/{build#} ]
RESOURCES_PIPELINE_{upstream_pipeline_name}_RUNNAME [ date.pipeline_build_iteration ]

# identifies upstream repository and commit
RESOURCES_PIPELINE_{upstream_pipeline_name}_SOURCEBRANCH
RESOURCES_PIPELINE_{upstream_pipeline_name}_SOURCEPROVIDER
RESOURCES_PIPELINE_{upstream_pipeline_name}_SOURCECOMMIT

**Comment by t-l-k** [comment]
It is a shame, or so it appears, that the `resources.pipeline.<Alias>.runName` variable, cannot be referenced, when it appears within an expression on the RHS of the pipeline attribute `name`. This attribute is responsible for setting the build number. 

You might imagine, that you'd want a 2nd build (CD) triggered from by a 1st build (CI), and that you'd want the the build number of the CD pipeline to closely match to the build number of the CI pipeline, perhaps with an additional sprinkling of naming metadata. 

I've opened a [ticket for this issue](https://github.com/MicrosoftDocs/azure-devops-docs/issues/9052), because to me it sounds like a very reasonable use case!

**Comment by eyesfree** [comment]
> @benc-uk found the answer [here](https://github.com/MicrosoftDocs/vsts-docs/issues/6350). Here's how to get metadata across pipelines:
> 
> 1. Define the first pipeline as a [resource](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=example%2Cparameter-schema#pipeline-resource)
> 2. Call that pipeline's metadata using [this schema](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=example%2Cparameter-schema#the-pipeline-resource-metadata-as-predefined-variables), where `<alias>` is the friendly identifier you defined in the pipeline resource block
> 
> Three notes that were helpful for my situation:
> 
> 1. I was struggling through getting the pipeline trigger to work as expected using YAML, and still haven't. Instead, I removed the pipeline trigger (i.e. the `trigger:` that's within the pipeline resource block) and added a "regular" CI trigger. When you define the `resources:` block, the default action of a pipeline trigger is nothing- they don't run unless you explicitly specify the `trigger:`, which is the opposite pattern of a CI trigger which runs by default unless explicitly told `trigger: none`. So, this does what I want, which is to trigger the second build pipeline off of a change to a repo while also bringing in metadata from the build that changed that repo
> 2. The metadata that was really what I needed was the first build's `Build.BuildNumber` which translates to `resources.pipeline.<Alias>.runName`
> 3. Not so much helpful, but might be related to why I couldn't get the pipeline trigger to work: the YAML for both of my pipelines were colocated in the root of the same repo

In Step 2 - it was runID instead of runName for me - i was trying to use the exact buildId.
