### ISSUE TITLE
support of Right to Left(RTL) contemt?

### ISSUE THREAD

**Issue by mahmoud690** [MicrosoftDocs/vsts-docs#3399]
Currently there is no way to generate RTL content. No markup support, even the HTML support you have provided eliminate "direction:rtl" from "style attribute. (Tested in TFS 2018.3)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fa622358-f5bb-1f5c-177a-081a37b6acef
* Version Independent ID: 72f7fd16-a822-66c8-3a34-8905645ce5f2
* Content: [Markdown syntax for files, widgets, and wikis in Azure DevOps - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/project/wiki/markdown-guidance?view=azure-devops&viewFallbackFrom=vsts)
* Content Source: [docs/project/wiki/markdown-guidance.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/project/wiki/markdown-guidance.md)
* Product: **devops**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @mahmoud690, I've created a user story on my backlog and have followed up with my PM. I'll be in touch. Thanks for reaching out!

**Comment by chcomley** [comment]
Hi @mahmoud690, We don’t have a Markdown way to generate RTL content. But we do have HTML support for RTL.
<p dir="rtl">Write this text right-to-left!</p>
![right-to-left](https://user-images.githubusercontent.com/35748196/53111879-d7471280-34f2-11e9-8b31-31fc7d658009.jpg)
There is also a [suggestion ticket](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdevelopercommunity.visualstudio.com%2Fcontent%2Fidea%2F460824%2Frtl-support-for-wiki-editor.html&data=02%7C01%7CChrystal.Comley%40microsoft.com%7Cc54360b19a874a6e38ef08d696f01366%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636862355223526748&sdata=jGVLxMlMvf2SvA1dLT%2BO%2BEIji6q0Bd3jfFzzA6%2BHzHU%3D&reserved=0) for this. Please upvote this ticket.
I'll be closing this issue, however please let me know if you have any further questions. Thanks!

**Comment by mahmoud690** [comment]
The problem is that when you paste a right aligned html in editor, the renderer eliminates related style attribute. For example put the following line in tfs 2018.3 wiki editor:
<span style="direction:rtl;color:red"> hello </span>

The renderer will remove direction:rtl attribue.

**Comment by adramasu** [comment]
Hi @mahmoud690,
Please try this syntax for HTML
`<p dir="rtl">Write this text right-to-left!</p>`
Do let us know if this works.

**Comment by mahmoud690** [comment]
Thanks Adramasu! it works. btw, it is more common to use css attribute in order to make a text right to left. So with your solution when I paste an RTL aligned html content, I should correct it by hand. It would be great if you support this css style too.

**Comment by tsahi** [comment]
W3C recommends using `dir="rtl"` rather than CSS: https://www.w3.org/International/tutorials/bidi-xhtml/ and https://www.w3.org/TR/i18n-html-tech-bidi/#ri20030728.09474480

**Comment by khooz** [comment]
Using HTML `dir="rtl"` for RTL support leads to flat lists when using nested lists in markdown.

**Comment by DanielGabbay** [comment]
`<div dir="rtl">עברית</div>`

**Comment by DanielGabbay** [comment]
`<p dir="rtl">Write this text right-to-left</p>`

**Comment by yanivush** [comment]
it's not OK! all text boxes should have RTL option, because text  which mixed Hebrew and English makes salad and unreadable..

that's why people looks for alternatives to manage missions at another platforms which do support RTL option..

**Comment by WilliamAntonRohm** [comment]
This repo is solely for documentation issues, and this issue is product-related. To make sure it gets in front of the right people, [please add it here](https://developercommunity.visualstudio.com/search?space=21).

**Comment by PuyaGoodarzi** [comment]
> Hi @mahmoud690, We don’t have a Markdown way to generate RTL content. But we do have HTML support for RTL:
> 
> Write this text right-to-left!
> 
> 
> There is also a [suggestion ticket](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdevelopercommunity.visualstudio.com%2Fcontent%2Fidea%2F460824%2Frtl-support-for-wiki-editor.html&data=02%7C01%7CChrystal.Comley%40microsoft.com%7Cc54360b19a874a6e38ef08d696f01366%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636862355223526748&sdata=jGVLxMlMvf2SvA1dLT%2BO%2BEIji6q0Bd3jfFzzA6%2BHzHU%3D&reserved=0) for this. Please upvote this ticket.
> I'll be closing this issue, however please let me know if you have any further questions. Thanks!

Hi @chcomley ... thanks for your answer. yes text boxes has rtl support . but when you write a rtl text in the title box of a user story (for example) , it will be ltr again after saving. and re opening the story.
