### ISSUE TITLE
branch policy change log

### ISSUE THREAD

**Issue by madrum** [MicrosoftDocs/vsts-docs#340]
Is there a log of when branch policies are changed? For example, how will we know if branch policies were not followed because they were changed for a period of time to allow unauthorized changes and then reverted to cover the tracks?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7cd986e0-608c-1d8c-6faf-ecdb12e10bc6
* Version Independent ID: d60c996e-187e-dd6b-7f3a-dd056a1603f4
* Content: [Protect your Git branches with policies](https://docs.microsoft.com/en-us/vsts/git/branch-policies)
* Content Source: [docs/git/branch-policies.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/git/branch-policies.md)
* Service: **unspecified**
* GitHub Login: @douge
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
@madrum You can get a list of historical revisions for branch policy using the VSTS code policies API here: [Historical revisions](https://www.visualstudio.com/en-us/docs/integrate/api/policy/configurations#get-a-list-of-historical-revisions). If you are looking for other functionality in this area, please file a UserVoice request [here](https://developercommunity.visualstudio.com/spaces/21/index.html). Please reactivate this issue if this doesn't answer your question. Thank you!
