### ISSUE TITLE
People-To-Peoples

### ISSUE THREAD

**Issue by JoesaDmercado** [MicrosoftDocs/vsts-docs#3402]
I-US=WE

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b1806955-863f-295c-0c49-2145754fa58e
* Version Independent ID: c87eee1f-3d0b-ee1d-4cd8-97930678d6cf
* Content: [Configure settings for projects, collections, organizations - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/settings/?toc=/azure/devops/organizations/settings/toc.json&bc=/azure/devops/organizations/settings/breadcrumb/toc.json&view=azure-devops)
* Content Source: [docs/organizations/settings/index.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/settings/index.md)
* Product: **devops**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by JoesaDmercado** [comment]
VM

**Comment by chcomley** [comment]
Hi @JoesaDmercado. I've created a user story on my backlog for this work, however could you please elaborate on the updates you feel are necessary for this article? Thanks very much!

**Comment by thomps23** [comment]
@JoesaDmercado Additional information would help us conduct a final triage. Let us know if you still have a question or feedback

**Comment by chcomley** [comment]
@JoesaDmercado, I'm closing this issue, but please let us know if we can help. You can still respond to this issue after it's closed, and then we can open new one and get to work! Thank you.
