### ISSUE TITLE
Marketplace extension installation with Azure DevOps Server (RC2) 

### ISSUE THREAD

**Issue by JukkaAtWork** [MicrosoftDocs/vsts-docs#3403]
Just a heads up while waiting for Azure DevOps Server documentation updates: "Install extensions for disconnected TFS" is not valid for Azure DevOps Server (RC2) anymore. Installing an extension downloaded from Marketplace now works like "Pre-installed extensions (first-party) for disconnected TFS"; select an uploaded extension and click "Get it Free" for installation dialogue.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 46849bf5-07ed-62cd-66a5-2ebabe449855
* Version Independent ID: d12ad05e-4348-f13a-ea35-7bb4761c3b0b
* Content: [Install extensions for Visual Studio Team Foundation Server (TFS)](https://docs.microsoft.com/en-us/azure/devops/marketplace/get-tfs-extensions?view=azure-devops-2019&viewFallbackFrom=azure-devops)
* Content Source: [docs/marketplace/get-tfs-extensions.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/marketplace/get-tfs-extensions.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by harishkragarwal** [comment]
Thank you for the feedback @JukkaAtWork. We will update the page.
