### ISSUE TITLE
Clarity required on how to use secret variables

### ISSUE THREAD

**Issue by GuyHarwood** [MicrosoftDocs/vsts-docs#3405]
The documentation suggests that secret variables are not automatically mapped, and then provides an example, which is rather confusing.

if i have a secret variable called $PASSWORD and i want to consume this in my bash script without changing its name (due to it being referenced in other scripts called by the main bash script), how can i do that?  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 450ac349-5c33-6cdf-1ecd-6eb989a00334
* Version Independent ID: a7119c1a-59b2-3081-a241-e93aa0d6b4b9
* Content: [Bash task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/bash?view=azure-devops)
* Content Source: [docs/pipelines/tasks/utility/bash.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/utility/bash.md)
* Product: **devops**
* GitHub Login: @steved0x
* Microsoft Alias: **dastahel**

**Comment by abombss** [comment]
If you don't want to change the name, then just map it with the same name.

```yaml
- script: echo $PASSWORD
- env: 
    PASSWORD: $(Password)
```

**Comment by GuyHarwood** [comment]
so secret variables are no longer protected once in the script body?  

this deviates from standard behaviour of secret variables.  Is there a particular reason why?

**Comment by vtbassmatt** [comment]
> so secret variables are no longer protected once in the script body?
Secrets are available as an environment variable once you ask us to map them into an environment variable. That's what the `env` entry does. (I did have to edit abombss's example since it had an extraneous `-`.)
