### ISSUE TITLE
Delete Test Artifact link seems to be wrong.  Takes you to the same page, is it supposed to do that?

### ISSUE THREAD

**Issue by gperrego** [MicrosoftDocs/vsts-docs#3406]
Delete Test Artifact link seems to be wrong.  Takes you to the same page, is it supposed to do that?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e9f02cb-f094-d6bc-ca7b-973db9de0082
* Version Independent ID: 1af6a7f5-9e99-ec99-081d-c0bf9e7ac5f5
* Content: [Move, change, delete, or restore user stories, bugs, tasks, and other work items - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/backlogs/remove-delete-work-items?tabs=new-nav&view=azure-devops#delete-test)
* Content Source: [docs/boards/backlogs/remove-delete-work-items.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/boards/backlogs/remove-delete-work-items.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@gperrego - thank you for the feedback. You are correct, and I'm updating the links in this article today.
