### ISSUE TITLE
Generic Secrets does not work when literal value is an encrypted variable

### ISSUE THREAD

**Issue by boreys** [MicrosoftDocs/vsts-docs#3407]
--from-literal=contoso=$(token)

This command does not work, if the token is an encrypted variable stored in the release pipeline. the "contoso" key will have empty string. However, if the token is plain text, it works.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dcbb25d1-a706-e8fc-61e4-d5b86aa54f47
* Version Independent ID: 5634d9dd-fd92-761c-24b8-5e32ed6c6c35
* Content: [Deploy to Kubernetes task - Azure Pipelines & TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/kubernetes?view=azure-devops)
* Content Source: [docs/pipelines/tasks/deploy/kubernetes.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/deploy/kubernetes.md)
* Product: **devops**
* GitHub Login: @steved0x
* Microsoft Alias: **dastahel**

**Comment by shashankbarsin** [comment]
@boreys apologies for the delayed response. We are investigating this issue and will get back with an update as soon as possible

**Comment by mijacobs** [comment]
It looks like you've encountered an issue with the product itself, rather than an issue with the documentation. To make sure it gets in front of the right people, please [submit your bug here]( https://developercommunity.visualstudio.com/content/problem/post.html?space=21).
