### ISSUE TITLE
Can you run a condition based on a trigger that has a wildcard?

### ISSUE THREAD

**Issue by Eldorian** [MicrosoftDocs/vsts-docs#3408]
For example my triggers:

trigger:
- master
- releases/*

I want a step to only run if the PR is in the releases\* branch. I see examples that specify a particular branch but wanted to check to see if conditions allow wildcards.

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f151218-9a11-0078-e038-f96198a76143
* Version Independent ID: 09c4d032-62f3-d97c-79d7-6fbfd89910e9
* Content: [Conditional tasks - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/conditions?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/process/conditions.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/conditions.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by Eldorian** [comment]
Looks like you can use the startsWith condition and use the SourceBranch with the folder name. Example was given, I just needed to read better I guess :) This can be closed.

**Comment by sachinmishra-gep** [comment]
You may use $(Build.Reason)  -eq "Pull Request"
