### ISSUE TITLE
Branch policy change log

### ISSUE THREAD

**Issue by madrum** [MicrosoftDocs/vsts-docs#341]
Is there a log of when branch policies are changed? For example, how will we know if branch policies were not followed because they were changed for a period of time to allow unauthorized changes and then reverted to cover the tracks?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1bf345ce-1831-bc64-bc2a-617fb69b3352
* Version Independent ID: 3f1e08ea-3db8-92e8-1873-953d1f026f25
* Content: [Set Git branch security and permissions](https://docs.microsoft.com/en-us/vsts/git/branch-permissions)
* Content Source: [docs/git/branch-permissions.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/git/branch-permissions.md)
* Service: **unspecified**
* GitHub Login: @douge
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
@madrum You can get a list of historical revisions for branch policy using the VSTS code policies API here: [Historical revisions](https://www.visualstudio.com/en-us/docs/integrate/api/policy/configurations#get-a-list-of-historical-revisions). If you are looking for other functionality in this area, please file a UserVoice request [here](https://developercommunity.visualstudio.com/spaces/21/index.html). Please reactivate this issue if this doesn't answer your question. Thank you!
