### ISSUE TITLE
Incorrect or unaccurate values in Release.Reason

### ISSUE THREAD

**Issue by jmaragon** [MicrosoftDocs/vsts-docs#3411]
As you can state looking at the Release values from any deployment (Initialize Job Step) the correct value for Scheduled build should be "Scheduled"  not "schedule" as the documentation states, because evaluation of custom conditions will fail .

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 611642f0-881f-10b9-ae94-3c562001d1f0
* Version Independent ID: 41efb94b-4c7a-64a3-b23b-70c8634ae727
* Content: [Release variables  and debugging - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/variables?view=azure-devops&tabs=batch)
* Content Source: [docs/pipelines/release/variables.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/release/variables.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment]
Thank you for your feedback. I will update the topic to include your recommendations.
