### ISSUE TITLE
Commit directly to the master branch

### ISSUE THREAD

**Issue by charlottesoderstrom** [MicrosoftDocs/vsts-docs#3414]
In step 8, where can you commit directly to the master branch when only the save and run-button is active? I have a pipeline-project, so all my code is at GitHub. 

---
#### Dokumentinformasjon

⚠ *Ikke rediger denne delen. Den kreves for koblingen docs.microsoft.com ➟ GitHub-problem.*

* ID: 38f7a23b-ebd4-af3e-68a2-275f7e45c33e
* Version Independent ID: f552a18c-ba29-00d4-03b6-254d7556d319
* Content: [Create your first pipeline - Azure Pipelines](https://docs.microsoft.com/nb-no/azure/devops/pipelines/get-started-yaml?view=azure-devops)
* Content Source: [docs/pipelines/get-started-yaml.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/get-started-yaml.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by andyjlewis** [comment]
@charlottesoderstrom I'm sorry for the long delay in response. I was out of the office for a long period of time earlier this year. We've made a lot of fixes and changes since you posted this issue. I hope you were able to work out the issue, but please re-open if not.
