### ISSUE TITLE
How to retrieve build.parameters?

### ISSUE THREAD

**Issue by ahmadyo** [MicrosoftDocs/vsts-docs#3416]
Not retrieved using propertyFilters.
2- Is it "properties" or "propertyFilters"? there is mismatch between syntax and parameter list in this doc.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f225bc86-a0d2-78d7-c060-82abf1a65229
* Version Independent ID: 7e1f2e49-2130-f15d-f11c-6db5638c5355
* Content: [Builds](https://docs.microsoft.com/en-us/azure/devops/integrate/previous-apis/build/builds?view=tfs-2017)
* Content Source: [docs/integrate/previous-apis/build/builds.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/integrate/previous-apis/build/builds.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by willsmythe** [comment]
@vtbassmatt - since these docs are hand-written (i.e. not easily maintained at this point), one solution may be to reference the later/generated reference docs. You might also want to chat with @wnjenkin about a more general solution for pushing people to the newer docs (i.e. the current purple info message may not be sufficient).

**Comment by vtbassmatt** [comment]
This doc is owned by @vijayma

**Comment by chcomley** [comment]
Hi @ahmadyo, Following up on this issue, it appears to be almost 6 months old now! The doc has been updated since then, however I'm unsure of what has been updated. Please let us know whether you feel it still needs an update, otherwise I'll be closing this issue. Thanks very much.

**Comment by ahmadyo** [comment]
This bug is about "Builds" [https://docs.microsoft.com/en-us/azure/devops/integrate/previous-apis/build/builds?view=tfs-2017]
Simply compare syntax with pameters list; syntax has "[&propertyFilters={string}]" but list has "properties" instead.

How a good job you did! Let bug unanswered 6 month, and close it within 6 hours simply without reading it!
Nice.

**Comment by elbatk** [comment]
Hi @ahmadyo , I got this notification so I wanted to swing by and offer some context. These APIs are for older versions of TFS, and as Will mentioned above, they were hand-written once upon a time and very expensive to maintain/update. We like to point people to our [new REST API docs](https://docs.microsoft.com/en-us/rest/api/azure/devops/?view=azure-devops-rest-5.0) that are autogenerated, but we know they don't work for older versions. 

That being said, we don't mind reviewing PRs for these docs if users find out they're incorrect. Did you test out this API call for us, did you find which one worked? That would be extremely helpful in this scenario. From the new [Builds - List API](https://docs.microsoft.com/en-us/rest/api/azure/devops/build/builds/list?view=azure-devops-rest-5.0), it looks like "properties" is probably correct, any chance you could confirm that?

**Comment by ahmadyo** [comment]
First of all, I did not test it for you, I tried to use it, but it's not working.
Secondly, all prefer that customers use latest version, but sadly I can't update our TFS just for a bug and that is another project.
