### ISSUE TITLE
Consume and publish Artifacts

### ISSUE THREAD

**Issue by polybioz** [MicrosoftDocs/vsts-docs#3419]
In my pipeline I want to first consume artifacts from different build pipeline and then publish new build artifacts . Recommended path for consuming artifacts is System.ArtifactsDirectory. Recommended path for publishing artifacts is Build.ArtifactStagingDirectory. But these variables point to the same directory, so I end up publishing also the artifacts I consumed. Should I use subfolders to separate incoming and outgoing artifacts or am I missing something?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7175ebdc-0bba-7e00-d113-036a5cffe5fa
* Version Independent ID: 149ab9f4-0b7d-97e7-6cf5-1b54fd04c63c
* Content: [Publish and consume build artifacts in builds - Azure Pipelines and TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/build-artifacts?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/artifacts/build-artifacts.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/artifacts/build-artifacts.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by elbatk** [comment]
Hi @polybioz , you don't have to use those directories if you don't want to. You could do a download to that directory, do a copy files to another, and publish from the new one.

**Comment by elbatk** [comment]
Closing this one for now, let me know if you have any other questions!
