### ISSUE TITLE
Permissions Change log

### ISSUE THREAD

**Issue by madrum** [MicrosoftDocs/vsts-docs#342]
Is there a log of when permissions are changed? For example, how will we know if permissions were changed for a period of time to allow unauthorized changes and then reverted to cover the tracks?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 64f60178-1529-9b48-379a-2ca42c5bb741
* Version Independent ID: 468a3fe4-4551-022b-9000-a2acdd2968cc
* Content: [Set Git or TFVC repository permissions for VSTS & TFS](https://docs.microsoft.com/en-us/vsts/security/set-git-tfvc-repository-permissions#git-repository)
* Content Source: [docs/security/set-git-tfvc-repository-permissions.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/security/set-git-tfvc-repository-permissions.md)
* Service: **unspecified**
* GitHub Login: @douge
* Microsoft Alias: **douge**

**Comment by steved0x** [comment]
@madrum Unfortunately, (unlike the branch policy we discussed in https://github.com/MicrosoftDocs/vsts-docs/issues/341),  there isn't a way to get a historical list of permissions. Please file a UserVoice request for this feature [here](https://developercommunity.visualstudio.com/spaces/21/index.html) and the team will add it to the backlog to review, and possibly implement. Thank you.
