### ISSUE TITLE
Can you bulk follow items?

### ISSUE THREAD

**Issue by j-martens** [MicrosoftDocs/vsts-docs#3423]
Is there a way to follow everything in an epic or user story?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 50fb5639-2338-9141-1129-682e46676f7f
* Version Independent ID: 5002bb9e-5ec3-d773-2843-8b20468d6c69
* Content: [Track updates by following a user story, bug, or other work item or pull request - Azure Boards & Azure Repos](https://docs.microsoft.com/en-us/azure/devops/boards/work-items/follow-work-items?view=azure-devops&tabs=new-nav)
* Content Source: [docs/boards/work-items/follow-work-items.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/boards/work-items/follow-work-items.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by ampious** [comment]
+1

**Comment by KathrynEE** [comment]
@j-martens - Thank you for your inquiry. No, you can't bulk follow work items or children of work items. Please consider adding it as a feature request from our [Developer Community page](https://developercommunity.visualstudio.com/spaces/21/index.html).
