### ISSUE TITLE
Why don't you have clear indication for tasks on which agent type it can run on?

### ISSUE THREAD

**Issue by ytugarev** [MicrosoftDocs/vsts-docs#3427]
Many times I try to run a task and find out that it is not compatible with Ubuntu based agent pool. I can suggest to put additional line below "Azure Pipelines | TFS 2018 | TFS 2017 | TFS 2015.3" with something "Agent type: Windows xx"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 622daa35-c6a1-dac3-17ee-3f9308fc60cd
* Version Independent ID: 2c28a59b-8ef5-d7ab-46a6-58748ec552f5
* Content: [Azure File Copy task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-file-copy?view=azure-devops#q--a)
* Content Source: [docs/pipelines/tasks/deploy/azure-file-copy.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/deploy/azure-file-copy.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment]
Thank you for your feedback. I have passed this on to the product team for advice and will update the relevant topics accordingly.

**Comment by nickform-ost** [comment]
I totally agree with this. From experimenting with Azure Pipelines and from some knowledge of which platforms certain tools work on (_e.g._ XCode), it is clear that not all of the tasks in the catalog are supported on all agent types. It's a big surprise then to find that there is no mention that I have found in a reasonable amount of searching of any such restrictions, let alone a complete matrix of what is supported where.

@alexhomer1 - appreciate the effort to update the topics comprehensively, but in the meantime, is it possible you could provide a table showing which tasks are and aren't expected to work on each of the Microsoft-hosted agent types?

**Comment by syonekura** [comment]
I don't know if this should be in another issue, but as of today, at least the docs of Azure Copy File doesn't specify that only runs on Windows agents. [The demands section has "None" as requirements](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-file-copy?view=azure-devops#demands), so the current docs are at least misleading.

Is there anywhere a matrix like @nickform-ost sugested?

**Comment by HughDevlin** [comment]
please re-open and address
