### ISSUE TITLE
Is Conda preinstalled on windows hosted agents?

### ISSUE THREAD

**Issue by tvandera** [MicrosoftDocs/vsts-docs#3428]
Is Conda installed on **all** Windows Hosted agents?

Is the CONDA environment variable set on all of these hosted agents:

- vs2017-win2016
- vs2015-win2012r2

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b99fb08-2474-be71-62db-cbafec749cb3
* Version Independent ID: af525f70-f636-4fb2-e4e6-03a2dd759c24
* Content: [Run pipelines with Anaconda environments - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/languages/anaconda?view=azure-devops&tabs=vs2017#add-conda-to-your-system-path)
* Content Source: [docs/pipelines/languages/anaconda.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/languages/anaconda.md)
* Product: **devops**
* GitHub Login: @steved0x
* Microsoft Alias: **brcrista**

**Comment by tvandera** [comment]
I am asking because using VS 2015 is recommended [here](https://conda.io/projects/conda-build/en/latest/source/user-guide/tutorials/build-windows.html#microsoft-visual-studio), but Conda seems to be installed only on the VS 2017 hosts.

**Comment by MattDavisRM** [comment]
@tvandera You might be aware of it already, but the image contents are document in this [repository](https://github.com/Microsoft/azure-pipelines-image-generation#image-contents)

**Comment by tvandera** [comment]
@MattDavisRM Thanks
