### ISSUE TITLE
How do I move one project from one organization to another if I need to scale up

### ISSUE THREAD

**Issue by Geekays** [MicrosoftDocs/vsts-docs#3429]
I'm planning the organization structure. If I start with one organization as suggested and create multiple projects under it as needed, this may work fine for now.

However, if the structure grows and we need to create multiple organizations, how may I be able to move one or more projects from the current organization to a new one that I may create later?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 01770b43-fd5b-efbc-36f5-af91a3c8cf5a
* Version Independent ID: 7c046a91-37f9-32e3-dc3e-dfa922c456be
* Content: [Plan your organizational structure - Azure DevOps - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/user-guide/plan-your-azure-devops-org-structure?view=azure-devops)
* Content Source: [docs/user-guide/plan-your-azure-devops-org-structure.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/user-guide/plan-your-azure-devops-org-structure.md)
* Product: **devops**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @Geekays thanks for reaching out! Please see the following guidance on [Migration options](https://docs.microsoft.com/en-us/azure/devops/articles/migrate-from-tfs?view=azure-devops). I'll be adding a link to this article within the article you've referenced. Please let me know if you have any further questions. Thanks!

**Comment by GaTechThomas** [comment]
Would be helpful to have a terse answer on whether projects can be migrated across organizations. The guidance provided is very heavy. I think that I'm seeing that moving projects across orgs is not an option. Is that correct?

**Comment by chcomley** [comment]
Yes, you can move a project to a different organization. To further assist you, please send me an email and I'd be happy to engage the experts who've written the following article: [Migration options](https://docs.microsoft.com/en-us/azure/devops/articles/migrate-from-tfs?view=azure-devops). Thank you! chcomley@microsoft.com
