### ISSUE TITLE
HttpRequestException when Windows machine is joined the AD domain and DC is not available

### ISSUE THREAD

**Issue by iromanovsky** [MicrosoftDocs/vsts-docs#3430]
If you are doing 
- git clone from VS Code or from console
- your source is hosted on Azure DevOps Git Repo
- your Windows machine is part of AD Domain
- domain controller is not available

Credential manager will not work, you will be prompted for password without any explanations.
When doing git clone you will see this error

fatal: HttpRequestException encountered.
   An error occurred while sending the request. 

You enable SET GCM_TRACE=1 and try to git clone again, you will get
trace: [LogEvent] System.Net.Http.HttpRequestException: An error occurred while sending the request. ---&gt; System.Net.WebException: The remote server returned an error: (401) Unauthorized. ---&gt; System.ComponentModel.Win32Exception: The system cannot contact a domain controller to service the authentication request. Please try again later

You need a connection to a domain controller to successfully complete the git clone operation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f8b4989-21f0-53c5-dfce-6d5f1a66b8b2
* Version Independent ID: 2f4419a7-408b-40cd-9190-985a9976d556
* Content: [Authenticate with your Git repos - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/auth-overview?view=azure-devops)
* Content Source: [docs/repos/git/auth-overview.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/repos/git/auth-overview.md)
* Product: **devops**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by JozoSlejko** [comment]
I have the same issue when doing push to remote DevOps repo.

fatal: HttpRequestException encountered.
   An error occurred while sending the request.

After the DC is contacted the first time, subsequent logins are now showing the authentication screen without the need for the private connection to the DC.

git version 2.21.0.windows.1
Git Credential Manager for Windows version 1.18.4
