### ISSUE TITLE
How can we checkout only one branch?

### ISSUE THREAD

**Issue by JSerieys** [MicrosoftDocs/vsts-docs#3431]
When using Git checkout (with Azure Git repo), all remote branches are fetched (which is very slow in our case).
As a workaround, we set the "Don't sync sources" and run git fetch with command line.
But is it possible to have this options directly in VSTS?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 800c5477-b39f-48e6-6f9c-aa7994b2ec2a
* Version Independent ID: db9e2e97-d44d-734e-6a6f-b01f60f01c95
* Content: [Options for Git repositories - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/pipeline-options-for-git?view=azure-devops)
* Content Source: [docs/pipelines/repos/pipeline-options-for-git.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/repos/pipeline-options-for-git.md)
* Product: **devops**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by JSerieys** [comment]
Issue has been created in "Product feedback" instead

**Comment by jwisener** [comment]
@JSerieys where? do you have a link?

**Comment by JSerieys** [comment]
> @JSerieys where? do you have a link?

You can search "git fetch one branch" on google.

Here is the code we are using:
`
git init
git remote add origin https://AAA.visualstudio.com/BBB/_git/CCC
git fetch origin $(Build.SourceVersion) --depth=1
git reset --hard FETCH_HEAD
`
