### ISSUE TITLE
Ancherlink "Variables" does not work

### ISSUE THREAD

**Issue by dNsl9r** [MicrosoftDocs/vsts-docs#3432]
When you follow the Anchorlink in "Variables" nothing happens because the target is not defined in this document.
Sentence with link: "For more information about how to use variables to specify the current project, user, or date, see Variables."
Link Target: "https://docs.microsoft.com/en-us/azure/devops/boards/queries/using-queries?view=azure-devops&tabs=new-nav#variables"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 309b3b5f-7355-57ac-3775-b441f6e037f1
* Version Independent ID: 0d30ed27-9dc4-e8de-ef7e-c71842c9b4c3
* Content: [Create managed queries with the Query Editor - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/queries/using-queries?view=azure-devops&tabs=new-nav#variables)
* Content Source: [docs/boards/queries/using-queries.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/boards/queries/using-queries.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@dNsl9r - Thank you for the correction. I'll update the content today. The link should jump to [Query macros or variables](https://docs.microsoft.com/en-us/azure/devops/boards/queries/query-operators-variables?view=azure-devops#query-macros-or-variables).

**Comment by dNsl9r** [comment]
Thank you for the update and help @KathrynEE
