### ISSUE TITLE
Typo in Markdown syntax for available TFS versions

### ISSUE THREAD

**Issue by pascalberger** [MicrosoftDocs/vsts-docs#3434]
For the supported TFS versions there's a typo in the Markdown syntax.

`**TFS 2018 **` should be `**TFS 2018**` (without space)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 075891be-ca2c-8bcf-54ca-cf2ec195dc22
* Version Independent ID: b425a067-4540-0550-3a4d-1007b645d3b5
* Content: [Configure a backup schedule and plan for Team Foundation Server - Azure DevOps Server & Team Foundation Server](https://docs.microsoft.com/en-us/tfs/server/admin/backup/config-backup-sched-plan)
* Content Source: [https://mseng.visualstudio.com/DefaultCollection/TechnicalContent/_git/tfs-docs-pr?path=%2fdocs%2fserver%2fadmin%2fbackup%2fconfig-backup-sched-plan.md&version=GBlive&_a=contents](https://mseng.visualstudio.com/DefaultCollection/TechnicalContent/_git/tfs-docs-pr?path=%2fdocs%2fserver%2fadmin%2fbackup%2fconfig-backup-sched-plan.md&version=GBlive&_a=contents)
* Product: **devops-server**
* Git Login: **elbatk**
* Microsoft Alias: **aaronha**

**Comment by KathrynEE** [comment]
@pascalberger - thank you for the correction, It appears to be fixed now.
