### ISSUE TITLE
Bummer!

### ISSUE THREAD

**Issue by rncwnd79** [MicrosoftDocs/vsts-docs#3436]
Of all things `:octocat:` is not working!

https://docs.microsoft.com/en-us/azure/devops/project/wiki/markdown-guidance?view=azure-devops#emoji

**Comment by steved0x** [comment]
@rncwnd79 It's on the list of supported emoji linked from that article. Let me research if we need to make a change to the article, or if it is a product bug.

**Comment by chcomley** [comment]
Hi @rncwnd79 We've filed a bug for this, as it is indeed a product bug. Thanks so much for reaching out!
