### ISSUE TITLE
Azure Active Directory Integrated Authentication

### ISSUE THREAD

**Issue by osmant** [MicrosoftDocs/vsts-docs#3437]
Hi, 
Recently, I started to see Autentication Type drop down when using database deployment task which was did no t exists a month ago. Can you please provide how Azure Active Directory Integrated authentication works? If I chose that option, with which user deployment is performed? can you please elaborate in the documentation?

Regards

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cd85890a-ccba-8697-b406-b662aabeb27f
* Version Independent ID: a1d371df-c0a0-1cd6-37f8-4b60913a2e97
* Content: [Deploy to Azure SQL Database - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/targets/azure-sqldb?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/targets/azure-sqldb.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/targets/azure-sqldb.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment]
Thank you for your feedback. I will update the topic to include your recommendations.

**Comment by jarz** [comment]
@alexhomer1 I've been trying to find details on this too. Any update?
