### ISSUE TITLE
Doesn't list the build steps

### ISSUE THREAD

**Issue by garybushey** [MicrosoftDocs/vsts-docs#3439]
Am I missing something or are there no steps listed under "Create the build pipeline"?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fd6a020f-35b0-8d92-9f8b-d05e658236e8
* Version Independent ID: e6208061-614b-a084-9c91-ab2ea12c7e2b
* Content: [Build a VM using RM templates - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/apps/cd/azure/build-azure-vm-template?view=azure-devops)
* Content Source: [docs/pipelines/apps/cd/azure/build-azure-vm-template.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/apps/cd/azure/build-azure-vm-template.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment]
Thank you for your feedback. I will update the topic to include your recommendations.
