### ISSUE TITLE
Multiple Docker Compose File Args not parsing through

### ISSUE THREAD

**Issue by RyanSpartan117** [MicrosoftDocs/vsts-docs#3441]
We're trying to parse in multiple variables into a docker compose task using the `dockerComposeFileArgs` flag. So far, the first argument will contain the contents of the other key value pairs despite the documentation saying seperate using a new line.

example:

```
   variables:
      firstArg=first_arg
      secondArg=second_arg
```

```
- task: DockerCompose@0
  displayName: 'Container build'
  inputs:
	  .
	  .
	  .
  	 dockerComposeFileArgs: 
        firstArg=$(firstArg)
        secondArg=$(secondArg)
```
Which will put everything into the first argument. 

```
RUN echo $firstArg
&gt; first_arg secondArg=second_arg
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d767aebb-620e-9ad3-e906-3e2bafa02ee9
* Version Independent ID: c8cb5a48-ccdf-778c-1547-a10db74cb56c
* Content: [Docker Compose task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/docker-compose?view=azure-devops)
* Content Source: [docs/pipelines/tasks/build/docker-compose.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/build/docker-compose.md)
* Product: **devops**
* GitHub Login: @steved0x
* Microsoft Alias: **shasb**

**Comment by flcdrg** [comment]
You need to use the | operator in YAML to indicate that newlines should be preserved.

eg.
``` yaml
dockerComposeFileArgs: |
  firstArg=$(firstArg)
  secondArg=$(secondArg)
```

See https://stackoverflow.com/a/21699210/25702 for more info.

Would be good to mention this in the documentation

**Comment by chasewilson** [comment]
The documentation. Thank you for the feedback. If you see anything else, feel free to open a new issue
