### ISSUE TITLE
It is unclear what version of AZ CLI you can expect when setting up this task

### ISSUE THREAD

**Issue by hansmbakker** [MicrosoftDocs/vsts-docs#3442]
The version of AZ CLI that is installed on the agent might differ from the version of AZ CLI that is installed locally.

The version matters because only newer versions of AZ CLI have built-in support for Azure Bot Services.

The `az bot` commands seem unavailable on the Hosted VS2017 agent.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8de3304e-98f9-bac0-3ccc-c65f68a89e87
* Version Independent ID: 8fb2f6a9-545d-dff1-ff86-974694a85054
* Content: [Azure CLI task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-cli?view=azure-devops)
* Content Source: [docs/pipelines/tasks/deploy/azure-cli.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/deploy/azure-cli.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment]
Thank you for your feedback. This topic: https://docs.microsoft.com/cli/azure/install-azure-cli?view=azure-cli-latest describes how to discover the installed Azure CLI version and install a newer version. This topic: https://docs.microsoft.com/azure/devops/pipelines/agents/agents?view=azure-devops#agent-version-and-upgrades discusses agent versions, while this topic: https://docs.microsoft.com/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml#software has links to see what software is installed on each agent.
