### ISSUE TITLE
How to generate a authorization with readonly access?

### ISSUE THREAD

**Issue by RolfJordi** [MicrosoftDocs/vsts-docs#3443]
I only found how to generate a settings.xml with read/write with the "connect to feed" in maven.
I would like to have a settings.xml with only read access and a custom duration. How can i generate a valid authorization?

I can do so for gradle by generating a custom PAT with custom access but not for maven

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba866498-1246-7db4-8ae9-1c35dbbcf0e0
* Version Independent ID: f0f4333d-f912-f1bb-b6b3-0951b591c63c
* Content: [Configure Maven client with Azure DevOps Services or Team Foundation Server](https://docs.microsoft.com/en-us/azure/devops/artifacts/maven/pom-and-settings?view=azure-devops&tabs=new-nav)
* Content Source: [docs/artifacts/maven/pom-and-settings.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/artifacts/maven/pom-and-settings.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by hacketiwack** [comment]
We have the same problem in our company.
This issue is slowly becoming urgent and we are wondering if we can stay with this product if the configuration is so cumbersome.

**Comment by espoelstra** [comment]
If you visit the page mentioned on the "Install package with Gradle" page, you can edit the generated token to remove the "Read&Write" permission leaving just "Read" on the token.

https://docs.microsoft.com/en-us/azure/devops/artifacts/gradle/pull-package-gradle?view=azure-devops#set-up-authentication

**Comment by elbatk** [comment]
This connect to feed dialog is something we're actively looking at on our team. As @espoelstra said, you can create a PAT via those instructions and use that PAT in your Maven settings.xml. You used to have to do some base64 encoding with the old Connect to Feed but we've updated it recently so it should just be a copy/paste to the PAT you created with the permissions you want (just read). Closing this but please let me know if have any thoughts on a better flow/what you'd like to see different. Would you want to be able to create a PAT/set perms right from the feed window? etc.
