### ISSUE TITLE
inputs are not properly documented

### ISSUE THREAD

**Issue by johngallardo** [MicrosoftDocs/vsts-docs#3446]
This documentation is not comprehensive. For example, how does one set the 'Add project name to publish path' input? Its not actually documented!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d227a6f2-a94b-1c05-57e4-b63d42e2b9e5
* Version Independent ID: d063e189-d0fd-4ca3-c108-a0bd2ae49d22
* Content: [.NET Core CLI task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/dotnet-core-cli?view=azure-devops)
* Content Source: [docs/pipelines/tasks/build/dotnet-core-cli.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/build/dotnet-core-cli.md)
* Product: **devops**
* GitHub Login: @steved0x
* Microsoft Alias: **dastahel**

**Comment by chasewilson** [comment]
Hey @johngallardo Thanks for the feedback. I've just made some updates and thingk your scenario is a little clearer now. However, I would love and feedback you have if you had some time to take a look at the refreshed docs.

**Comment by chasewilson** [comment]
I'll be closing this issue, feel free to open another issue if you have any more feedback
