### ISSUE TITLE
How to Publish a Docker Image as an Artifact?

### ISSUE THREAD

**Issue by VinceSJ** [MicrosoftDocs/vsts-docs#3447]
Is there a simple way to build a Docker image and publish it in a job for later access in the pipeline by other jobs? I'm not looking to deploy/publish the image to any sort of repository (eg, DockerHub), I just want the image to be available for subsequent jobs that depend on the built image, such as a testing job.

Right now the only option I see is to `docker save` the image as a tar archive, publish that as an artifact, then in the subsequent job(s) `docker load` the tar in so I can run the image. Am I missing some way to make that Docker image accessible to subsequent jobs without doing an explicit export/artifact publish/import process over multiple jobs?

Many thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 861ce7a5-4fa4-55f1-2c97-46a9cc6a2f66
* Version Independent ID: bdf954b9-9bbe-8b34-b674-71ad8153519d
* Content: [Publish and consume Pipeline artifacts in builds - Azure Pipelines and TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/pipeline-artifacts?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/artifacts/pipeline-artifacts.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/artifacts/pipeline-artifacts.md)
* Product: **devops**
* GitHub Login: @alexmullans
* Microsoft Alias: **amullans**

**Comment by mitchdenny** [comment]
Hey @VinceSJ - we have seen people use Universal Packages and Pipeline Artifacts to take a snapshot of the /var/lib/docker/* directories as a way of quickly snapshotting the content and moving it. However I can't yet vouch for the safety of this approach as the documentation for Docker states that we should leave directories like /var/lib/docker/overlay2 alone.

It could be that file system attributes that don't currently get picked up by either Universal Packages or Pipeline Artifacts are critical when you go to place these files back down on disk. The safest way is to use a save/load combo for sure.

That said - if you can make it work it is probably OK. This is actually an area we are investigating at the moment for caching purposes.

**Comment by elbatk** [comment]
Hi @VinceSJ , I think Mitch's comment has what you're looking for, going to close this for now but please let us know if you have any more questions or feedback for us; as Mitch said, we're investigating this scenario currently so anything helps!

**Comment by VinceSJ** [comment]
Thanks! If I wind up doing anything interesting on my end for the implementation, I'll try to come back and update this.

**Comment by relgames** [comment]
Hi @VinceSJ! I'm trying exactly the same use case, where a build stage creates a docker image and a subsequent deploy stage deploys it. I tried to use Container Registry to push images, put an image name into a text file and publish that, then download that file and get the image name, but it looks ugly.

Have you found anothe way to transfer docker images between stages by any chance? 
Or just kept docker save/load?

**Comment by VinceSJ** [comment]
Hi @relgames,

Sadly, my team never figured out a good way to pass Docker images between Jobs. We did some testing where one Job would do an image build and save it as an artifact, then a later Job could pull that artifact in to use it for testing, publishing to DockerHub, etc, but we wound up seeing massive slowdown. It was rather shocking -- I think it was on the order of 10 minutes to do the roundtrip save (as artifact) then load (from that artifact) in a later job. Images were ~1gig. That would have more than doubled the time of our pipeline running, so we dropped it. That was a while ago though, so maybe things changed? We haven't looked into it at all since then.

Instead, we just do a single, giant mono-Job. We build the image, run the tests, and conditionally deploy all from the same Job, just broken out over many conditional Steps/Tasks. Since everything is happening on the same Agent, there's no issues with passing things around. I don't love it from a philosophical standpoint, but it works fine, and I've made my peace with it. If your workflow could really benefit from parallelized Jobs all running simultaneously, that might not be such a great answer. But if you're really only building a single image at a time, I'd just keep it all in a single Job and break things out over conditional Steps. It would be great if there's some feature that was released since I last posted here, but if not, I'd just encourage the past of least resistance.

Best of luck to you!

**Comment by relgames** [comment]
Thanks, @VinceSJ, for the detailed answer!!

In the end, I went a different route and push images to a separate Azure Container Registry based on a variable which is defined in the root pipeline YAML, that way all stages know the full image name. 

So it works like this:
* Image name is defined in the root variable based on a build number, for example image:123
* Build stage builds & tests the image and pushes to ACR using the image name variable
* Deploy stages pull the image from ACR and push to production repositories 

Downside is costs for ACR, but at this moment I have some credit on the account so it should be enough for the next year.
And then maybe I will change to push to AWS instead of ACR, where they have a free tier, or maybe Microsoft finally does something about container jobs.
