### ISSUE TITLE
Show how can you do in case the tag contais ':'

### ISSUE THREAD

**Issue by Nepomuceno** [MicrosoftDocs/vsts-docs#3448]
It is really common to do docker build -t myimage:latest but the syntax highlight goes crazy because of the : on multline scripts

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e825c07d-2168-c0aa-782a-ef6f9c7ba95e
* Version Independent ID: 5cb6926b-215a-bf89-8e63-b2e1129e41df
* Content: [Build, test, and push Docker container apps - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/languages/docker?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/languages/docker.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/languages/docker.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by shashankbarsin** [comment]
According to [Docker's documentation on tags](https://docs.docker.com/engine/reference/commandline/tag/), tag name must adhere to the following format - 

`A tag name must be valid ASCII and may contain lowercase and uppercase letters, digits, underscores, periods and dashes. A tag name may not start with a period or a dash and may contain a maximum of 128 characters.`

Closing this issue as only underscores, periods and dashes have been mentioned as accepted special characters for tags and not colons.
