### ISSUE TITLE
Does the Unit Test work?

### ISSUE THREAD

**Issue by MouthOfMadness** [MicrosoftDocs/vsts-docs#345]
It all works great, the continuous integration, the build, the deployment, everything except the unit test; there must be some crucial steps missing or that I'm overlooking as I cannot get the unit tests to run.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2d588805-0219-7eb1-6a5c-1f1363f41870
* Version Independent ID: 515fb392-083b-644b-b824-efb581aa0a91
* Content: [Continuous integration, test, and deployment tutorial | Microsoft Docs](https://docs.microsoft.com/en-us/vsts/build-release/test/example-continuous-testing)
* Content Source: [docs/build-release/test/example-continuous-testing.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/build-release/test/example-continuous-testing.md)
* Service: **unspecified**
* GitHub Login: @douge
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment]
Thank you for your feedback. I will investigate and let you know if I can identify the issue.

**Comment by MouthOfMadness** [comment]
I can clarify with more details.

If I create a .Net web application (4.7); it’s a flawless execution.

If I create a .Net Core web application (2.x), it fails the unit test.  I came to think that the path to the test dll is incorrect, as the dll deploys to netcore2.0 folder under bin.  I corrected the path with a \**\

Unfortunately, I exhausted my 240 test minutes for the month to follow up with my theory.

**Comment by alexhomer1** [comment]
I just tested this using VS 2017 to create the app and then VSTS to build it. The tests were executed. Check that you are using the correct build template detailed in the topic, and that you have checked the "Add Unit Tests" box when creating the app in Visual Studio.

**Comment by alexhomer1** [comment]
I believe that, at present, the Visual Studio Test task does not support unite tests in a .NET Core app - this is why the topic uses a .NET app. Updates to the Visual Studio Test task are in progress to include .NET Core apps.
