### ISSUE TITLE
Access test run information from Analytics View

### ISSUE THREAD

**Issue by jawn** [MicrosoftDocs/vsts-docs#3451]
On https://docs.microsoft.com/en-us/rest/api/azure/devops/test/results/list?view=azure-devops-rest-5.0#examples
the section "With test iterations and workitem details" shows how to use the REST API to obtain test runs with related work items.

Example call:
GET https://dev.azure.com/fabrikam/Fabrikam-Fiber-TFVC/_apis/test/Runs/31/results?detailsToInclude=WorkItems,Iterations&$top=100&api-version=5.0

Is it possible to access test run data in a custom analytics view?
If not, is that something that is envisioned for the future?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 508bfe7d-16cf-7b44-53a7-26a9f9563be8
* Version Independent ID: f365dd42-530f-e145-5dd3-28420237bc7b
* Content: [What are Analytics views? - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/report/analytics/what-are-analytics-views?view=azure-devops)
* Content Source: [docs/report/analytics/what-are-analytics-views.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/report/analytics/what-are-analytics-views.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@jawn - Thank you for your inquiry. It isn't possible to use Analytics Views today to do as you ask. I recommend that you suggest it as a feature to be supported on our [Developer Community page](https://developercommunity.visualstudio.com/spaces/21/index.html).  The [Data available](https://docs.microsoft.com/en-us/azure/devops/report/analytics/data-available-in-analytics?view=azure-devops) article indicates that Test Plans are a focus of future road maps and more details will be provided in the future.
