### ISSUE TITLE
Article doesn't describe Remote Link not showing up

### ISSUE THREAD

**Issue by robmck-ms** [MicrosoftDocs/vsts-docs#3454]
Just tried to add a Remote Link. This doesn't appear as an option for me. The above article doesn't describe what might cause this, or what steps I can take to remedy this. (Near as I can tell, I meet all the prerequisites described at the top of the article.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a0aa4019-9343-7791-d5e6-d68063cea6c4
* Version Independent ID: a165a19b-2caa-f7f3-d202-1ca4d1e20049
* Content: [Link user stories, issues, bugs, and other work items - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/backlogs/add-link?view=azure-devops&tabs=browser#link)
* Content Source: [docs/boards/backlogs/add-link.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/boards/backlogs/add-link.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@robmck-ms - Hello Rob. Thank you for your inquiry.  Are you working from the cloud? or an on-prem server? Remote linking is only available from Azure DevOps Services (the cloud). If you are working from the cloud, has your organization linked two or more organizations through Azure Active Directory? That is the other key requirement. You check that by opening Organization Settings and view Azure Active Directory.  If all these criteria are met, then I suggest you open a bug on the [Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html) page.
