### ISSUE TITLE
Package steps throw 'chart metadata (Chart.yaml) missing' error

### ISSUE THREAD

**Issue by sharedito** [MicrosoftDocs/vsts-docs#3455]
While trying the package steps, but chart Path explanation is not very clear on what should I set the path to. Setting the path to './demo' or anything like it, would say that no such directory exists. Setting chart Path to  '/home/vsts/.helm', would throw the error saying that the chart metadata is missing. I've read the documentation of the task, but it is not very helpful, it actually contains almost the same description for chartPath that this guid. This are the tasks that I have in the YAML file of the build definition:

- task: HelmDeploy@0
  inputs:
    connectionType: Azure Resource Manager
    azureSubscription: KubernetesDemo
    azureResourceGroup: KubernetesDemo
    kubernetesCluster: kubernetes-demo
    command: init
    arguments: --client-only

- task: HelmDeploy@0
  inputs:
    command: package
    chartPath: ./demo
    chartVersion: $(Build.BuildNumber)
    destination: $(Build.ArtifactStagingDirectory)
    updateDependency: true

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3d8a8c57-a152-3525-0cb8-bdd2f7b76649
* Version Independent ID: 3dbd38b9-5f74-31bb-c6d1-55700f8256eb
* Content: [Package a Docker-enabled app in a Helm chart - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/languages/helm?view=azure-devops)
* Content Source: [docs/pipelines/languages/helm.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/languages/helm.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment]
Thank you for your feedback. I have passed this on to the product team for advice.

**Comment by vyunev** [comment]
Same confusion here

**Comment by azooinmyluggage** [comment]
Thanks, I will get the help text and documents updated.

To give you an example, I used the following path
chartPath: '$(System.DefaultWorkingDirectory)/draft-helm-nodejs/charts/javascript'

I have published the following GitHub repo as an artifact. The name of the artifact is draft-helm-nodejs
https://github.com/azooinmyluggage/draft-helm-nodejs/tree/master/charts/javascript

**Comment by zoha21** [comment]
When can we expect an update on this? I'm running into the same problem

**Comment by praburamkr** [comment]
Im running with the same issue.im blocked right now.Is there any update on this issue?

**Comment by chasewilson** [comment]
The documentation has been updated. If you have any more feedback, feel free to open a new issue.
