### ISSUE TITLE
On Top of Listed URLS and IPs, Do We Need To Whitelist These?

### ISSUE THREAD

**Issue by denhsu** [MicrosoftDocs/vsts-docs#3456]
Hi,

We are using *.visualstudio.com domain, so we have whitelisted below sites in our server:
https://login.microsoftonline.com
https://app.vssps.visualstudio.com 
https://{organization_name}.visualstudio.com
https://{organization_name}.vsrm.visualstudio.com
https://{organization_name}.pkgs.visualstudio.com
https://{organization_name}.vssps.visualstudio.com

However, we still can't access Azure DevOps.  When we login Azure DevOps on the server, we found extra URLs and IPs are blocked by our firewall.   Do we need to whitelist the following URLs and IP?

3.107.246.10.443:
152.199.4.44.443:
23.204.37.21.443:
72.21.81.200.443: 
aadcdn.msauth.net  13.107.246.10 
aadcdn.msftauth.net  152.199.4.44 
secure.aadcdn.microsoftonline-p.com  23.204.37.21  

If there are extra URLs and IPs that need to be whitelisted, please update the content in this page.  Thanks! Please note that we don't want our server to have Internet access, except access to Azure DevOps.

Thanks,
Dennis

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43799c5d-2f13-cc76-a1c0-a3f850e16d4e
* Version Independent ID: 97a5b73f-faf7-f9c0-9269-fc79984616d6
* Content: [Deploy a build and release agent on Windows - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/v2-windows?view=azure-devops#im-running-a-firewall-and-my-code-is-in-azure-repos-what-urls-does-the-agent-need-to-communicate-with)
* Content Source: [docs/pipelines/agents/v2-windows.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/agents/v2-windows.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by denhsu** [comment]
Hi,

Please close this, we got it working.

Thanks,
Dennis

**Comment by awentzel** [comment]
@denhsu Can you provide details for how your team solved this for other's that may be experiencing similar issues?

**Comment by denhsu** [comment]
@awentzel Hi, our firewall team ended up opening many MS sites as logining Azure DevOps require authentication to our federation server, so those URLS needs to be whitelist as well.  It might be unique to each company.  The best suggestion is to run fiddler and check which sites are blocked and whitelist them.
