### ISSUE TITLE
Headless Selenium Tests and Interactive Mode

### ISSUE THREAD

**Issue by jtucker276** [MicrosoftDocs/vsts-docs#3457]
If a self-hosted agent runs a Selenium Test that uses ChromeDriver to run Chrome in headless mode, one would think that it would not be necessary to have that agent configured to run in interactive mode. Could the documentation be updated to reflect whether this is or is not the case? Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 09e51d18-72ec-1ad4-9ae7-8185c8e1dcd6
* Version Independent ID: 9f2f0471-d123-8e95-1606-cd811d1ece9a
* Content: [Perform UI tests with Selenium - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/test/continuous-test-selenium?view=tfs-2017)
* Content Source: [docs/pipelines/test/continuous-test-selenium.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/test/continuous-test-selenium.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment]
Thank you for your feedback. I have passed this on to the product team for advice.

**Comment by PBoraMSFT** [comment]
@jtucker276 - thanks for the feedback. 
This (and other general considerations for UI testing) have been discussed in this topic https://docs.microsoft.com/en-us/azure/devops/pipelines/test/ui-testing-considerations?view=azure-devops
We will look at cross-referencing appropriately from the Selenium topic.

**Comment by VladyslavGoloshchapov** [comment]
@PBoraMSFT that topic doesn`t say anything about headless mode.
It only says that interactive mode is required for visible ui tests.

So what about headless mode ?

**Comment by PBoraMSFT** [comment]
@VladyslavGoloshchapov - This is already discussed in the doc. https://docs.microsoft.com/en-us/azure/devops/pipelines/test/ui-testing-considerations?view=azure-devops&tabs=mstest#headless-mode-or-visible-ui-mode

**Comment by VladyslavGoloshchapov** [comment]
ok, thanks
