### ISSUE TITLE
Bulk author and edit test cases using Test hub

### ISSUE THREAD

**Issue by ivanb007** [MicrosoftDocs/vsts-docs#3458]
Under 'Test Authoring' above it is claimed that the 'Web-based test features' allow 'Bulk author and edit test cases'. I presume this is referring to the Grid view of a Test Suite but I can find no instructions on how to actually do it and all my attempts using Grid view only allow single line Insert, Delete or Clear Row. Not even a Copy Row. I don't call that 'bulk author'. Is it really possible to bulk author test cases using Test hub and if so, how?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e32b0e4-8af5-4bb3-d65b-bc661210944c
* Version Independent ID: a5987d1f-fb94-4a49-f70b-9f8932925e54
* Content: [Guidance on MTM usage - Azure Test Plans](https://docs.microsoft.com/en-us/azure/devops/test/mtm/guidance-mtm-usage?view=azure-devops&viewFallbackFrom=vsts)
* Content Source: [docs/test/mtm/guidance-mtm-usage.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/test/mtm/guidance-mtm-usage.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment]
Thank you for your feedback. I have passed this on to the product team for advice.

**Comment by harishkragarwal** [comment]
Hi @ivanb007,
https://docs.microsoft.com/en-us/azure/devops/test/reference-qa?view=azure-devops#q-is-there-a-way-to-quickly-add-multiple-test-cases-at-the-same-time and the next few FAQs is what we offer in the product today. Yes, it is limited in its bulk editing capabilities. Overtime the desire is to provide actual Excel integration to make this be easier.
