### ISSUE TITLE
Navigation to administration page should reference the "Overview" tab

### ISSUE THREAD

**Issue by evl5051** [MicrosoftDocs/vsts-docs#346]
If you have selected a different tap within the "Gear" icon page (e.g. "Notifications" or "Agent Queues", you are automatically directed to that page when clicking the gear icon. This step:

    From the web portal, click the gear settings icon icon to open the administration page for the team project.

should instead read:

    From the web portal, click the gear settings icon, then "Overview", to open the administration page for the team project.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c7f59ca3-f70a-5316-9bb5-147c8b1b23c5
* Version Independent ID: 597d78c8-9b00-94a8-8748-526cdf97ff96
* Content: [Add a team administrator](https://docs.microsoft.com/en-us/vsts/work/scale/add-team-administrator)
* Content Source: [docs/work/scale/add-team-administrator.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/work/scale/add-team-administrator.md)
* Service: **unspecified**
* GitHub Login: @douge
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@evl5051 - Agree with your suggestion. I've updated the topic and changes should be live later today.
