### ISSUE TITLE
Require branches to be created in folders on Azure Repos (Azure DevOps Services)

### ISSUE THREAD

**Issue by MAHDTech** [MicrosoftDocs/vsts-docs#3463]
In relation to the [Require branches to be created in folders](https://docs.microsoft.com/en-us/azure/devops/repos/git/require-branch-folders?view=azure-devops&tabs=browser&viewFallbackFrom=vsts) article, can this be achieved on Azure DevOps Services?

I am looking at the new Azure DevOps PowerShell module and it seems to be missing this functionality, and the tf cli seems to be deprecated?

What is the correct method to use now?

**Comment by MAHDTech** [comment]
This is in a recent release, but seems to not include the functionality I am looking for.

https://github.com/Microsoft/azure-devops-cli-extension/issues/432

**Comment by atbagga** [comment]
@MAHDTech  Your request seems more aligned with Issue https://github.com/Microsoft/azure-devops-cli-extension/issues/418
Permission management should be available soon on Azure Devops Extension. Feel free to comment with your requirements on that issue.

**Comment by kachkaev** [comment]
Is it possible to use Azure DevOps web interface to restrict root branch creation, but still allow branch creation in certain 'folders'? I'm on macos.
