### ISSUE TITLE
PAT created successfully but not saved

### ISSUE THREAD

**Issue by DonyG97** [MicrosoftDocs/vsts-docs#3464]
When creating a PAT with certain accounts the token is generated however it is not saved so it does not work. I can create PATs with another account and have asked other users to try it but for some reason this account cannot, although the account has equal or higher permissions to other users. 

![image](https://user-images.githubusercontent.com/28715960/53323904-55caf800-38d7-11e9-95a5-400f841e501b.png)

**Comment by steved0x** [comment]
@DonyG97 Sorry that you ran into trouble, I recommend you report this as a product bug by choosing **Product feedback** at the bottom of any article that discusses PATs:

![image](https://user-images.githubusercontent.com/1580889/51848904-90e40680-22ec-11e9-893f-ded2716f3ea2.png)

or you can file an issue directly at https://developercommunity.visualstudio.com/spaces/21/index.html

Please include a link back to this doc issue, and if there are any additional documentation changes to be made as a result of this, we will add them.

Thank you for your feedback.
