### ISSUE TITLE
christie Church should be Christie Church

### ISSUE THREAD

**Issue by cortz** [MicrosoftDocs/vsts-docs#3465]
"christie Church" should be Christie Church

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b4914adf-b6bb-f209-d08e-88d35ff8ea78
* Version Independent ID: b00bc0d2-4eb7-d154-425c-48022ce41b4b
* Content: [Adjust work to fit sprint capacity - Azure Boards and TFS](https://docs.microsoft.com/en-us/azure/devops/boards/sprints/adjust-work?view=azure-devops)
* Content Source: [docs/boards/sprints/adjust-work.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/boards/sprints/adjust-work.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@cortz - Thank you for the correction. The article will be updated later today.
