### ISSUE TITLE
Azure AD user convert

### ISSUE THREAD

**Issue by Jtayta** [MicrosoftDocs/vsts-docs#3466]
The document notes that the user must exist in Azure AD as a member.  If the user is an Azure AD guest, rather than member, follow this article: Convert Azure AD UserType from Member to Guest using Azure AD PowerShell.
But this article is about converting a user *from* a member *to* a guest.  Is that not the opposite of what we are trying to achieve?  What am I missing here?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 031380a0-4f04-4105-199a-81715b42c653
* Version Independent ID: 570b2795-90ad-32b4-7ad0-1fceb186ffa3
* Content: [Connect organization to Azure Active Directory - Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/connect-organization-to-azure-ad?view=azure-devops)
* Content Source: [docs/organizations/accounts/connect-organization-to-azure-ad.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/accounts/connect-organization-to-azure-ad.md)
* Product: **devops**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @Jtayta, thanks for reaching out. I'll provide some clarity within the next few days. Thanks so much for your patience. We'll get this straightened out!
