### ISSUE TITLE
integration with other services

### ISSUE THREAD

**Issue by christophedemey** [MicrosoftDocs/vsts-docs#3467]
Hi

I am in charge of migration to this new feed but stumble upon a problem.
We integrate nuget feed in our release monitoring, we query the nuget feed several times.
With our previous feed this was easy i would integrate Nuget.Core package into an application, then run this code :
 ```
    //ID of the package to be looked up
            string packageID = "EntityFramework";

            //Connect to the official package repository
            IPackageRepository repo = PackageRepositoryFactory.Default.CreateRepository("https://packages.nuget.org/api/v2");

            //Get the list of all NuGet packages with ID 'EntityFramework'       
            List&lt;IPackage&gt; packages = repo.FindPackagesById(packageID).ToList();

            //Filter the list of packages that are not Release (Stable) versions
            packages = packages.Where(item =&gt; (item.IsReleaseVersion() == false)).ToList();

            //Iterate through the list and print the full name of the pre-release packages to console
            foreach (IPackage p in packages)
            {
                Console.WriteLine(p.GetFullName());
            }
```

But now when i point this to the azure artifacts feed i get unauthorized exception :
```
An error occurred while loading packages from 'https://pkgs.dev.azure.com/build-orisnv/_packaging/OrisFeed/nuget/v3': The remote server returned an error: (401) Unauthorized.'
```

How can i resolve this ?

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab0a3735-a9b0-2ed7-f08f-5321f55f8c90
* Version Independent ID: 2153f6c0-def7-eed1-286d-5e61c9fcbec4
* Content: [Use NuGet with Azure DevOps Services feeds](https://docs.microsoft.com/en-us/azure/devops/artifacts/nuget/nuget-exe?view=azure-devops&tabs=new-nav)
* Content Source: [docs/artifacts/nuget/nuget-exe.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/artifacts/nuget/nuget-exe.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by elbatk** [comment]
Hi @christophedemey , are you authenticated to the Azure Artifacts feed that you're trying to pull from?

**Comment by christophedemey** [comment]
Hi 

I already found A solution, maybe this could be added to the docs.

Create and call this function before the http call.
```
   private void InitializeCredentialProvider()
        {
            ISettings settings = Settings.LoadDefaultSettings(null, null, null);
            var packageSourceProvider = new PackageSourceProvider(settings);
            var credentialProvider = new SettingsCredentialProvider(new AzureDevopsCredentialProvider("username", "password"), packageSourceProvider);

            HttpClient.DefaultCredentialProvider = credentialProvider;
        }
```

Implement the AzureDevopsCredentialProvider class.
```
 public class AzureDevopsCredentialProvider : ICredentialProvider
    {
        private readonly string username=string.Empty;
        private readonly string password=string.Empty;

        public AzureDevopsCredentialProvider(string username, string password)
        {
            this.username = username;
            this.password = password;
        }

        public ICredentials GetCredentials(Uri uri, IWebProxy proxy, CredentialType credentialType, bool retrying)
        {
            return new NetworkCredential(username, password);
        }
    }
```
Now the httpclient call will work.
If you have an other more easier way please let me know.
