### ISSUE TITLE
Update sample NuGet.config

### ISSUE THREAD

**Issue by cremor** [MicrosoftDocs/vsts-docs#3468]
The shown sample NuGet.config file should be updated.

1. Change URL for new domain name of Azure DevOps.
2. Change NuGet URL to v3 API (and add `protocolVersion="3"` if that actually does anything).
3. activePackageSource [is deprecated](https://docs.microsoft.com/en-us/nuget/reference/nuget-config-file#activepackagesource). Although I don't know if a replacement exists.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c78a9f20-b8d2-4aa7-c52d-a968ab87315d
* Version Independent ID: 3880a787-8f70-8c13-176e-c732b619fb06
* Content: [Restore Package Management NuGet packages in Azure Pipelines - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/packages/nuget-restore?view=azure-devops&viewFallbackFrom=azdevops)
* Content Source: [docs/pipelines/packages/nuget-restore.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/packages/nuget-restore.md)
* Product: **devops**
* GitHub Login: @steved0x
* Microsoft Alias: **amullans**

**Comment by ramiMSFT** [comment]
@cremor Thank you for your feedback. The updated version of the article will go live soon.
