### ISSUE TITLE
Witadmin?

### ISSUE THREAD

**Issue by lavahot** [MicrosoftDocs/vsts-docs#347]
The top section of this document suggests using witadmin, going so far as to how to find it. Witadmin is the wrong tool for this and the top section should be referring to TCM, which is in a directory further up.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: db3f586e-e0a8-bb3f-9736-279429b327bf
* Version Independent ID: 2117aff3-ea0a-465c-0412-654d84a0ac8a
* Content: [Customize and manage the test experience - TFS](https://docs.microsoft.com/en-us/vsts/work/customize/reference/witadmin/tcm-customize-manage-test-experience#examples)
* Content Source: [docs/work/customize/reference/witadmin/tcm-customize-manage-test-experience.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/work/customize/reference/witadmin/tcm-customize-manage-test-experience.md)
* Service: **unspecified**
* GitHub Login: @douge
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@lavahot - Thank you for the correction. I have updated the topic to reflect your input.
