### ISSUE TITLE
Missing GUI option: Create git tag after successful build

### ISSUE THREAD

**Issue by Bouke** [MicrosoftDocs/vsts-docs#3471]
The current visual build pipelines allow to tag a git commit after the build has succeeded. I can't seem to find this option in the new yaml builds.

**Comment by steved0x** [comment]
@Bouke I have moved your issue over to here: https://github.com/Microsoft/azure-pipelines-yaml/issues/139

You can continue the conversation with the product team on that new issue. Thank you for your feedback.
