### ISSUE TITLE
How to publish release pipeline artifacts?

### ISSUE THREAD

**Issue by DavidNewby** [MicrosoftDocs/vsts-docs#3472]
Is there a way to publish artifacts that are generated from a RELEASE (not build) pipeline?

I want to be able to create an output file in release stage 1, then download that in stage 2 and deploy directly the image verses creating an image from scratch in each stage...

**Comment by elbatk** [comment]
Hi @DavidNewby , adding @mitchdenny who can help out here :)

**Comment by mitchdenny** [comment]
Sorry - at the moment we don't support this. As an alternative you could use Universal Packages instead.
