### ISSUE TITLE
Mercurial support

### ISSUE THREAD

**Issue by jmadderson** [MicrosoftDocs/vsts-docs#3473]
how come azure devops doesn't support mercurial repositories? VSTS used to support hg and bitbucket integration didnt it?

**Comment by steved0x** [comment]
@jmadderson Thank you for your feedback. I'm not sure who to send this feedback to from the documentation side, but you can ask the product team directly by filing an issue here:

https://developercommunity.visualstudio.com/spaces/21/index.html

Is this for build pipelines, or some other integration?
