### ISSUE TITLE
New Navigation - step 2 image highlights wrong option

### ISSUE THREAD

**Issue by steve-hawkins** [MicrosoftDocs/vsts-docs#3474]
Documentation states 'Manage extensions'

Image highlights 'Browse Marketplace'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 650e14dd-88eb-e6ef-2afd-5357c9ccc62d
* Version Independent ID: 43864fb1-e3bf-e9b2-123e-5ea343ec4b25
* Content: [Uninstall or disable extensions in Azure DevOps Services or Team Foundation Server (TFS)](https://docs.microsoft.com/en-us/azure/devops/marketplace/uninstall-disable-extensions?view=azure-devops&tabs=new-nav)
* Content Source: [docs/marketplace/uninstall-disable-extensions.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/marketplace/uninstall-disable-extensions.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by harishkragarwal** [comment]
Thanks for reporting this @steve-hawkins . Will fix this.

**Comment by alexhomer1** [comment]
Thank you for your feedback. I will update the topic to include your recommendations.
