### ISSUE TITLE
Ability to download Python packages from Package feed?

### ISSUE THREAD

**Issue by cdietschrun** [MicrosoftDocs/vsts-docs#3475]
Thank you for your feedback!

The issues in this repo are for documentation feedback.

If you are submitting your documentation feedback issue directly through GitHub, please provide the URL of the article so we can route the feedback to the correct author.

Please report Azure DevOps or TFS software bugs, feedback, or questions in the [Azure DevOps Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html).

https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/download-package?view=azure-devops

My question is when is this task going to support more than NuGet feeds? Or more generally, what is the best way to consume Python packages from a feed of mine inside a Pipeline? Should I be doing the pip.conf route and doing pip install?

**Comment by chasewilson** [comment]
@cdietschrun Thank you for the questions and I am sorry for the late response. This task currently supports downloading python packages according to the documentation. I'll be closing this issue for now. Feel free to respond or create a new issue if you have any more feedback.
