### ISSUE TITLE
These options are not available on Azure DevOps SERVER???

### ISSUE THREAD

**Issue by renanleandrof** [MicrosoftDocs/vsts-docs#3476]
When i tried to create it on my azure server it says: The feature is disabled. Contact your Azure DevOps Server administrator.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aafd89c0-d6e2-c44a-d3aa-b89ee5e5fe5c
* Version Independent ID: 355f816b-b187-cb56-af8a-82581cd02ea6
* Content: [Customize a work item type for an inherited process - Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/organizations/settings/work/customize-process-wit?view=azure-devops#add-wit)
* Content Source: [docs/organizations/settings/work/customize-process-wit.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/settings/work/customize-process-wit.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by danhellem** [comment]
I would start by checking with your Azure DevOps admin to make sure that the selected the Inherited option when creating a collection.

**Comment by KathrynEE** [comment]
@renanleandrof - Are you still having an issue with getting to the Inheritance process UI. Please note that it is only available for New Project Collections which were configured to support Inheritance. More is provided here: https://docs.microsoft.com/en-us/azure/devops/server/admin/manage-project-collections?view=azure-devops#create-a-project-collection.
