### ISSUE TITLE
How unique is build id?

### ISSUE THREAD

**Issue by arefinsami** [MicrosoftDocs/vsts-docs#3477]
I am guessing the build id unique per build pipeline. I am not sure if the scope is much bigger. In what scope the build id is unique? Is it unique only per build pipeline or per team project? 

Same question for release id. 

Thanks. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0fa5a83c-70fd-6925-a8c8-256b21c21a2e
* Version Independent ID: 75f4a136-7245-7878-2953-6b68272fe4ec
* Content: [Build pipeline options - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/options?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/build/options.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/build/options.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by StingyJack** [comment]
After a quick visual check using the build rest API and they seem to be unique across the organization.

**Comment by wnjenkin** [comment]
@arefinsami Thanks for your feedback. I'll update the doc to be clearer. The change will go out in the next update of the doc.

**Comment by WilliamAntonRohm** [comment]
@jasonrberk -- Jason, thank you for your followup.  I'm an editor, not a subject expert-- this section is the nearest I've found for `BuildId`:
- [Tokens](https://learn.microsoft.com/en-us/azure/devops/pipelines/process/run-number?view=azure-devops&tabs=yaml#tokens)

and this for `ReleaseID`:
- [Release](https://learn.microsoft.com/en-us/azure/devops/pipelines/release/variables?view=azure-devops&tabs=batch#release)

@steved0x -- Steve, please add/edit these suggestions.
