### ISSUE TITLE
Would love to see an update to the capabilities list here.

### ISSUE THREAD

**Issue by jwittner** [MicrosoftDocs/vsts-docs#348]
For example it seems like script access to OAUTH tokens is supported in YAML now: https://github.com/Microsoft/vsts-agent/blob/master/docs/preview/yamlgettingstarted-token.md

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 87686bea-7c46-cd47-d1a9-128e16b63a23
* Version Independent ID: ace78317-e562-e35d-781d-23cd7d2dfff2
* Content: [CI Build in code using YAML](https://docs.microsoft.com/en-us/vsts/build-release/actions/build-yaml#feedback)
* Content Source: [docs/build-release/actions/build-yaml.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/build-release/actions/build-yaml.md)
* Service: **unspecified**
* GitHub Login: @douge
* Microsoft Alias: **alewis**

**Comment by andyjlewis** [comment]
Thank you for the feedback. We're working on an update.

**Comment by andyjlewis** [comment]
We've added info about it to this topic and here: https://docs.microsoft.com/en-us/vsts/build-release/concepts/process/phases?view=vsts&tabs=yaml#access-to-oauth-token
