### ISSUE TITLE
Briefed on the objective 

### ISSUE THREAD

**Issue by Bigsby11** [MicrosoftDocs/vsts-docs#3483]
Thank you for your feedback!

The issues in this repo are for documentation feedback.

If you are submitting your documentation feedback issue directly through GitHub, please provide the URL of the article so we can route the feedback to the correct author.

Please report Azure DevOps or TFS software bugs, feedback, or questions in the [Azure DevOps Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html).

**Comment by steved0x** [comment]
Thank you for your feedback. It looks like it might have gotten lost somehow as I only see the default issue template in your post above. Can you submit a new issue by navigating to the topic on https://docs.microsoft.com for which you wish to leave feedback, and selecting **Content Feedback**? Thank you.

![image](https://user-images.githubusercontent.com/1580889/51848491-af95cd80-22eb-11e9-81a2-1680fc40caf9.png)
