### ISSUE TITLE
Draft Pull Request from the CLI

### ISSUE THREAD

**Issue by MAHDTech** [MicrosoftDocs/vsts-docs#3484]
Is it possible to set a PR into Draft mode using the ``az repos pr create``` ?

I have tried both prefixing with "WIP" and "DO NOT MERGE", as well as looking for a flag for this option.

https://docs.microsoft.com/en-us/azure/devops/repos/git/pull-requests?view=azure-devops&tabs=new-nav#draft-pull-requests

**Comment by steved0x** [comment]
@MAHDTech I have asked the product team and will let you know once we get an answer.

**Comment by gauravsaralMs** [comment]
This is now possible
![image](https://user-images.githubusercontent.com/43203065/58611978-99fed780-82ce-11e9-86e7-6c5afe027461.png)

reference for getting started:
https://github.com/Azure/azure-devops-cli-extension/blob/master/doc/getting_started.md
