### ISSUE TITLE
Need more info

### ISSUE THREAD

**Issue by pthorsley** [MicrosoftDocs/vsts-docs#3486]
soooo... using a GUI editor to build the pipline. Why not show how to do a simple transform from web.config with a web.dev.config to the outcome. We use this method constantly in VS why not just show that?  There is not one sample on this page, very unhelpful. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 064f48ba-1c34-6422-5fe3-c3e88d2803c4
* Version Independent ID: c38f5761-4718-9aae-bc83-063257a78eb3
* Content: [File Transform task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/file-transform?view=azure-devops)
* Content Source: [docs/pipelines/tasks/utility/file-transform.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/utility/file-transform.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment]
Thank you for your feedback. I added this link: "See also [File transforms and variable substitution reference](https://docs.microsoft.com/azure/devops/pipelines/tasks/transforms-variable-substitution)" to the topic a few days ago. The target page (https://docs.microsoft.com/azure/devops/pipelines/tasks/transforms-variable-substitution) contains more details about, and examples of transformations. However, it does not show the GUI-based task in use either. I will investigate how I can add more information to the topic related to this and update the topic in due course.
