### ISSUE TITLE
Is there a way to import the .zip file programmatically?

### ISSUE THREAD

**Issue by MarkIannucci** [MicrosoftDocs/vsts-docs#3488]
Hi, when we were running TFS on prem, we used the [importwitd.exe](https://docs.microsoft.com/en-us/azure/devops/reference/witadmin/witadmin-import-export-manage-wits?view=azure-devops-2019) and other TFS admin commands to interact with the work item management system.  By doing this, we put our WIT xml files under source control and were able to adjust and import them in a CI process.

This document indicates that we should use the web front end to import a .zip file.  Is there a way to feed the .zip file using another mechanism so we can keep our WIT XMLs in source and have a CI process to deploy and manage changes? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: efa97384-8347-5612-9fb9-f5d55cc338c0
* Version Independent ID: 7151c774-9b48-aac9-0f83-c4c6c8f5867f
* Content: [Import a process - Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/organizations/settings/work/import-process/import-process?view=azure-devops)
* Content Source: [docs/organizations/settings/work/import-process/import-process.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/settings/work/import-process/import-process.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by danhellem** [comment]
TFS on-prem does not use Hosted XML to import work item customization. It is still using the witadmin.exe. if you are looking to automate I would suggest checking out [these scripts](https://github.com/Microsoft/process-customization-scripts) to help you.

**Comment by MarkIannucci** [comment]
@danhellem, thanks!  I didn't believe that I would be able to keep using `witadmin.exe` to interact with the Azure DevOps service, but I was able to export the XML and I think I'm now well on my way.  @KathrynEE, I'm not sure if it makes sense to include some text indicating that `witadmin.exe` can still be used for those seeking a command line interface for updating their work item processes in Azure DevOps.
