### ISSUE TITLE
no way in the GUI to set windowsAuthenticationForWebsite

### ISSUE THREAD

**Issue by mattseaboard** [MicrosoftDocs/vsts-docs#3489]
the IIS web app manage task documentation located at https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/iis-web-app-management-on-machine-group?view=azure-devops shows in the YAML snippet that you can set the windowsAuthenticationForWebsite property, but in the user interface in Azure Devops there is no setting or dropdown visible in order to set this.

How do you set this? The YAML is read-only.

**Comment by RoopeshNair** [comment]
here is screenshot for your reference: 

![image](https://user-images.githubusercontent.com/1370480/59751543-5cbeb180-929e-11e9-89fb-6d15c6c955e8.png)
