### ISSUE TITLE
Requirement Quality Widget not respecting selected Query (Release Pipeline)

### ISSUE THREAD

**Issue by Hupka** [MicrosoftDocs/vsts-docs#3490]
Hey Azure DevOps Team,

I am having issues with the Requirement Quality Widget that you describe in this document here. 

In short: the widget does not show the results of our linked automated tests, when we follow the steps described above.

Even after associating tests with stories, they still show up in the test analytics pane as "not associated" tests. When looking into a user story on the links pane, it shows all linked tests, but as non-clickable url: "vstfs:///TestManagement/TcmTest/48177591". Where should I post my issue description to find help? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c179cd8-483f-b664-6081-0984cc74d519
* Version Independent ID: 2925de17-0d71-52e8-ed79-1d9affd1bc9e
* Content: [Trace test requirements - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/test/requirements-traceability?view=azure-devops#help-and-support)
* Content Source: [docs/pipelines/test/requirements-traceability.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/test/requirements-traceability.md)
* Product: **devops**
* GitHub Login: @vinodjo
* Microsoft Alias: **vinojos**

**Comment by divais** [comment]
Hi Hupka,

Apologies that you are facing this issue. Can you please log the issue in our [Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html ) so that our engineers can look into it. Also request you to please add screenshots to help us repro. 

Can you also clarify what you mean by "not show up in the **test analytics pane** as "not associated" tests"?

**Comment by Hupka** [comment]
Hi @divais, thanks for asking!

I just tried it again and now it works - I just had to remove all the old links and now it's working. The Requirement Tests Widget properly shows test/failure rates. There is one other issue though: I could not get the widget to actually respect the selected Query. it is always showing all User Stories that have linked tests within a release pipeline. 

Is it enough to raise the issue here?

Regards,
Adrian

**Comment by divais** [comment]
Will look into this and get back.

**Comment by thomps23** [comment]
@divais Any follow up here? Thanks!

**Comment by divais** [comment]
Hi @thomps23 ,

This works as expected, the widget doesnt take a WIT query as input rather shows all user stories associated with the selected build or release pipeline. 

https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/test/requirements-traceability.md#quality-traceability

**Comment by thomps23** [comment]
Thanks, closing this issue out.

**Comment by nabond251** [comment]
> Hi @divais, thanks for asking!
> 
> I just tried it again and now it works - I just had to remove all the old links and now it's working. The Requirement Tests Widget properly shows test/failure rates. There is one other issue though: I could not get the widget to actually respect the selected Query. it is always showing all User Stories that have linked tests within a release pipeline. 
> 
> Is it enough to raise the issue here?
> 
> Regards,
> Adrian

Having the same issue. @Hupka I know this is dated, but is there any chance you could recall how you addressed this? You mention you removed the old links - what were the new ones; did you update your instance of DevOps?

Thanks,
Nathan

**Comment by Hupka** [comment]
Uh, not so easy.. I recall that the behavior seemed a bit healthy. I am recalling that the clickable URL vanished later again. At some point already after a few weeks we abandoned this widget. 🤷🏻‍♂️

**Comment by nabond251** [comment]
@Hupka ok. I did manage to find something of a workaround for anyone running into the same issue. Using the link button has never yet worked for me, but using the add bug button has always worked. So if I change the requirement to a bug, add the test result to it, and then change the "bug" back to a requirement, it works just fine.
