### ISSUE TITLE
When changing Hosted Linux Preview to Hosted Ubuntu 16.04, while pulling the nginx, build is failing

### ISSUE THREAD

**Issue by kireeti123** [MicrosoftDocs/vsts-docs#3492]
Thank you for your feedback!

The issues in this repo are for documentation feedback.

The dockerfile we are using is the below.

FROM nginx
COPY dist /usr/share/nginx/html
COPY DockerImage/default.conf /etc/nginx/conf.d/default.conf

Fails with an error:

Step 1/5 : FROM nginx
latest: Pulling from library/nginx
no matching manifest for unknown in the manifest list entries
##[error]C:\Program Files\Docker\docker.exe failed with return code: 1
##[section]Finishing: Build Docker Image

Need your recommendations on how to fix if this issue.

Please report Azure DevOps or TFS software bugs, feedback, or questions in the [Azure DevOps Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html).

**Comment by shashankbarsin** [comment]
@kireeti123 we were unable to reproduce this issue on Hosted Ubuntu 16.04 agents
