### ISSUE TITLE
Package and publish Extension documentation not updated for new navigation

### ISSUE THREAD

**Issue by GingerBr** [MicrosoftDocs/vsts-docs#3493]
Hi, 
This documentation still shows the old navigation.  Can you please update it with screenshots from the new navigation? 
thanks,
Ashley

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3d3bc9b6-7944-5d58-7ec8-156a5ed81cdc
* Version Independent ID: 8f466811-4c19-9d69-68a8-5b715cabb50e
* Content: [Package, publish, & unpublish extensions](https://docs.microsoft.com/en-us/azure/devops/extend/publish/overview?view=azure-devops)
* Content Source: [docs/extend/publish/overview.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/extend/publish/overview.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by chcomley** [comment]
Hi Ashley, I'm following up on some old issues, and this one is no exception. Please accept my apology for the over-year-long delay. We're going to begin updating our extension articles within this or the next quarter. Thanks so much for your feedback.
