### ISSUE TITLE
Really outdated documentation

### ISSUE THREAD

**Issue by stoopered** [MicrosoftDocs/vsts-docs#3496]
Could you update this documentation. And is there any plans to make integration with view and VS better? If I am not referencing a view, and instead looking at the entire feed, I would like the prerelease checkbox to work. So if there is a way to tag the view as a prerelease view in AzureDevOps, and VS will read that tag to know it is a prerelease, that would be nice. I know it would also require changes in Nuget restore and other tasks. But right now SemVer seems like a better way to separate packages, even though it is immutable. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b254809-bcfe-5859-42e1-05df82aa730b
* Version Independent ID: cd8e1d01-c11b-4173-8f36-95d4237bc6a5
* Content: [Communicate package quality with release views](https://docs.microsoft.com/en-us/azure/devops/artifacts/feeds/views?view=azure-devops&tabs=new-nav)
* Content Source: [docs/artifacts/feeds/views.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/artifacts/feeds/views.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by wgv-srsedate** [comment]
I think this relates to their comment on using the `-prerelease` argument for metadata information, and that they plan on improving this experience.

https://docs.microsoft.com/en-us/azure/devops/artifacts/feeds/views?view=azure-devops#what-about-semver-and--prerelease

Although, that line was added 2 years ago, so who knows when they're getting around to it.

https://github.com/MicrosoftDocs/vsts-docs/commit/4556acf9e8cf39ddb670877dd0f608237dba9c17#diff-6a59095de830655e06c88cf702e9de26R4

**Comment by Misiu** [comment]
Link to uservoice does no work.
I also would like checkbox in VS to work.
Right now I use VersionSuffix to add `pre` suffix, but when I promote package to Release view I'd like that suffix to get released. This way I could build a single package and move the exact same package to proper view - without the need to recompile everything

**Comment by ramiMSFT** [comment]
@stoopered Thank you for your feedback. The updated article is live now [Here](https://docs.microsoft.com/en-us/azure/devops/artifacts/feeds/views?view=azure-devops).

If you have new feature suggestion please use the "Suggest a feature" link in our [Azure DevOps Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html)
