### ISSUE TITLE
Typo in Grunt - Designer

### ISSUE THREAD

**Issue by cotyhamilton** [MicrosoftDocs/vsts-docs#3498]
The simplest way to create a build pipeline if your app uses ~~Gulp~~ **Grunt** is to use the Node.js with Grunt build template when creating the pipeline. This will automatically add various tasks to invoke Gulp commands and to publish artifacts. In the task, select the Publish to TFS/Team Services option to publish test results, and select Enable Code Coverage to enable code coverage by using Istanbul.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c99686eb-6c78-0336-1ec3-802a53c9868d
* Version Independent ID: 6eaf1acb-24d4-5bb7-3935-17abe7e59dd9
* Content: [Build, test, and deploy JavaScript and Node.js apps - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/languages/javascript?view=azure-devops&tabs=designer)
* Content Source: [docs/pipelines/languages/javascript.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/languages/javascript.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by andyjlewis** [comment]
thanks for the heads up
