### ISSUE TITLE
What about Service Connection for a Management Group ?

### ISSUE THREAD

**Issue by SamirFarhat** [MicrosoftDocs/vsts-docs#3499]
Hi,
We understand that a Service Connection for a Subscription will allow the pipeline to automatically login to that Subscription.
What happens when using a management group ?

Samir

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 26477658-d1ad-a4c9-0d9e-59aeead8a71e
* Version Independent ID: 45dfbd24-b9f4-fdf2-48a2-5648220204fe
* Content: [Connect to Microsoft Azure - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/library/connect-to-azure?view=azure-devops)
* Content Source: [docs/pipelines/library/connect-to-azure.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/library/connect-to-azure.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment]
Thank you for your feedback. I have passed this on to the product team for advice.

**Comment by RoopeshNair** [comment]
Azure Management Groups allows you to group multiple subscriptions and perform actions across them. For example, apply governance conditions such as policies to multiple subscriptions at once. Currently Azure Service Connections scoped to a Management Group can used in Azure PowerShell task. Support for AZ CLI is work in progress. 
Learn more about [Azure Management Group](https://azure.microsoft.com/en-in/features/management-groups/)
