### ISSUE TITLE
XML Transformation is hard to get working from Build Definitons

### ISSUE THREAD

**Issue by harre096** [MicrosoftDocs/vsts-docs#350]
Story:
I have been working a lot this week to get transforms working in my build definition. 
After much searching, I finally ended up digging through the source code and found that the final piece I was missing in getting transforms working was an unset variable. All I needed to do was set the 'Release.EnvironmentName' variable. Then the transforms worked perfectly.
Then, I did the stg release and everything just worked out of the box.

So the takeaway would seem to be that this XML Transform tool is intended for usage on Releases and not Builds.
For context, our current pattern is a dev build that has release steps and a stg release. I am realizing that this is not the best pattern and will work to convert my projects as I can. However, I would like to shed some light on this in case others are encountering the same sort of issue.

Improvement idea:
Add a note in the description specifying that XML Transformation is designed for use in Releases and not Build Definitions.
 -> This will encourage people to change their build/release patterns to separate the builds/releases if they haven't done so. :)

Alternatively, if ya'll think using  XML Transformation in Build Definitions is worth doing/telling people about, we add a note saying that 'Release.EnvironmentName' variable should be set manually if the deploy task is triggered from a build definition.

Let me know what we can do,
Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 315ff823-9992-9f9b-62a1-42ce622ed41c
* Version Independent ID: 72ec3ffc-1dc9-b2dc-e3d4-4f14deae3720
* Content: [File transforms and variable substitution](https://docs.microsoft.com/en-us/vsts/build-release/tasks/transforms-variable-substitution#xml-transformation)
* Content Source: [docs/build-release/tasks/transforms-variable-substitution.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/build-release/tasks/transforms-variable-substitution.md)
* Service: **unspecified**
* GitHub Login: @douge
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment]
Thank you for your feedback. I will pass your question onto the product team and let you know their response.

**Comment by alexhomer1** [comment]
The product team are investigating and we will update the topic with new information when available.
