### ISSUE TITLE
Note about NuGet package has bad markup

### ISSUE THREAD

**Issue by vtbassmatt** [MicrosoftDocs/vsts-docs#3502]
The note about the NuGet package has its Markdown showing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6033d681-9093-547c-20fd-b31183c2bb33
* Version Independent ID: 0d92e3f0-7fb4-57e5-d913-f305a055a819
* Content: [Service hooks event reference](https://docs.microsoft.com/en-us/azure/devops/service-hooks/events?view=azure-devops)
* Content Source: [docs/service-hooks/events.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/service-hooks/events.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by steved0x** [comment]
@vtbassmatt Fixed and should be live soon.
