### ISSUE TITLE
Service Connection Policies

### ISSUE THREAD

**Issue by drueckert** [MicrosoftDocs/vsts-docs#3505]
What does the checkbox allow "All pipelines to use this endpoint" do? I don't see an explanation in your doc and I haven't found an explanation through an internet search. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72b90dd0-49f9-4ed4-3010-9a64dde6ae5a
* Version Independent ID: 6e679d50-4e94-eee3-8793-af884cc909ca
* Content: [Service connections in Azure Pipelines and Team Foundation Server - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/library/service-endpoints?view=azure-devops)
* Content Source: [docs/pipelines/library/service-endpoints.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/library/service-endpoints.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment]
Thank you for your feedback. This new option allows pipelines defined in YAML, which are not automatically authorized for service connections, to use this connection. We will be adding more information about this option to the topic soon.
