### ISSUE TITLE
Missing TFVC

### ISSUE THREAD

**Issue by eggersa** [MicrosoftDocs/vsts-docs#3506]
It says "Azure Pipelines integrates with GitHub, Azure Repos, Bitbucket, and Subversion." However, the listing seems missing that it also integrates with Team Foundation Version Control.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f15f40a4-bae9-154b-752a-2e9f453d79e3
* Version Independent ID: 3b937e0b-f919-f227-742f-dc740ad4e6f9
* Content: [What is Azure Pipelines? - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/get-started/what-is-azure-pipelines?view=azure-devops)
* Content Source: [docs/pipelines/get-started/what-is-azure-pipelines.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/get-started/what-is-azure-pipelines.md)
* Product: **devops**
* GitHub Login: @steved0x
* Microsoft Alias: **jillfra**

**Comment by ManuWink** [comment]
According to this docs site, Azure Repos includes both GIT and TFVC repositories:
https://docs.microsoft.com/de-de/azure/devops/repos/get-started/what-is-repos?view=azure-devops

**Comment by steved0x** [comment]
That is correct, and I will update this article to make it clear that TFVC is supported.
