### ISSUE TITLE
Build Version with Included Projects?

### ISSUE THREAD

**Issue by jhardcastle-veroscreening** [MicrosoftDocs/vsts-docs#3509]
Hi,

Why does the help advise against, and the task prevent you from including referenced projects AND using the build number?

I appreciate this is a contentious topic - but you use to get a warning, and now you just can't do it. Instead I am working around it using the custom option.

Thanks.

**Comment by steved0x** [comment]
Thank you for the feedback. Can you let me know which article this feedback is for, so I can assign it to the author? You can reply here with the URL of the topic, or you can create a new issue by browsing to the topic on docs.microsoft.com and choosing **Content feedback** at the bottom. 

![image](https://user-images.githubusercontent.com/1580889/51848491-af95cd80-22eb-11e9-81a2-1680fc40caf9.png)
