### ISSUE TITLE
Missing property for DownloadPipelineArtifact

### ISSUE THREAD

**Issue by david-s-svedberg** [MicrosoftDocs/vsts-docs#3511]
I figured out that I need to specify artifactName for DownloadPipelineArtifact as well otherwise it seems to default to dump. Should be included in example to avoid missunderstandings.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 861ce7a5-4fa4-55f1-2c97-46a9cc6a2f66
* Version Independent ID: bdf954b9-9bbe-8b34-b674-71ad8153519d
* Content: [Publish and consume Pipeline artifacts in builds - Azure Pipelines and TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/pipeline-artifacts?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/artifacts/pipeline-artifacts.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/artifacts/pipeline-artifacts.md)
* Product: **devops**
* GitHub Login: @alexmullans
* Microsoft Alias: **amullans**

**Comment by mitchdenny** [comment]
Thanks for the report @david-s-svedberg - we are going to be changing the behavior here to default to the name of the job that created the artifact. But we'll update the docs in the meantime (PR submitted).

**Comment by mitchdenny** [comment]
@andyjlewis - I tagged you in the PR if you can get a chance to review.

**Comment by willsmythe** [comment]
Docs have been fixed.
