### ISSUE TITLE
Export user list does not exist in DevOps Server 2019 RC2

### ISSUE THREAD

**Issue by renezersi** [MicrosoftDocs/vsts-docs#3512]
According to the Documentation, DevOps Server 2019 should also expose a Users Menu Item and one should be able to Export the Users List. 

I have DevOps Server 2019 RC2 installed, but there is no Users Item and so no Export available. 
Please verify it. 

Many thanks 
René 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 361c08ef-48be-de59-d223-595cadc65a7b
* Version Independent ID: 4bab93d0-8ee5-5e18-a217-c5f6a3eea441
* Content: [Export access level audit log - Azure DevOps & TFS](https://docs.microsoft.com/en-us/azure/devops/organizations/security/export-users-audit-log?view=azure-devops-2019)
* Content Source: [docs/organizations/security/export-users-audit-log.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/security/export-users-audit-log.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by chcomley** [comment]
Hi @renezersi, thanks for reaching out! I've created a work item to address this and will update you soon. Thank you!

**Comment by carloreggiani** [comment]
We discovered the csv file exported has now only 5 field and not 7 as before... We have developed jobs to import this file to coordinate license beetwen online and on premise Azure DevOps configuration. 
Did you know any changelog about it?

**Comment by chcomley** [comment]
Hi @carloreggiani, I've added @KathrynEE for further guidance. Thanks!

**Comment by KathrynEE** [comment]
@renezersi - Thank you for your inquiry. The Users section is only valid for the cloud - Azure DevOps Services. For Azure DevOps Server, you can only export the audit log from the Access Levels page for a project collection. I am updating the topic to reflect this correction.

**Comment by KathrynEE** [comment]
@carloreggiani - I asked the PMs about the change around the number of fields exported and they were not aware of any changelog.

**Comment by nk111** [comment]
Hi @carloreggiani 

I'm interested in how you actually coordinate license beetwen online and on premise Azure DevOps configuration? We have the same problem and it quite difficult to get information about proper licensing when using azure devops on premise and in the cloud at the same time.
