### ISSUE TITLE
Parameter 'toolPath' cannot be null or empty.

### ISSUE THREAD

**Issue by xutpuu** [MicrosoftDocs/vsts-docs#3514]
I add Python task and wrote inline script to run on self-hosted pool. In the build it failed with error "Parameter 'toolPath' cannot be null or empty." I tried to add tool "Use Python Version" but I can't undetstand where I should add $AGENT_TOOLSDIRECTORY.
I installed Python on build machine and added python to PATH.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1eeb2956-beca-447d-c9a6-a859f3cfc4bf
* Version Independent ID: 89f2a014-99bb-420d-265c-42515d30c80b
* Content: [Python Script task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/python-script?view=azure-devops)
* Content Source: [docs/pipelines/tasks/utility/python-script.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/utility/python-script.md)
* Product: **devops**
* GitHub Login: @steved0x
* Microsoft Alias: **brcrista**

**Comment by colindomoney** [comment]
I had a similar issue - I ended up doing a local install of Python 3.6.5 from source using the --prefix option to locate this inside my _work/_tool directory. I also had to create a symlink to python3 to python or I got the above message. I'll write this up in detail and post here - it is possible to get this to work.

**Comment by davidstaheli** [comment]
Thanks for reporting this. We're going to move this issue to this repo:
https://github.com/Microsoft/azure-pipelines-tasks

/move to Microsoft/azure-pipelines-tasks

**Comment by kauayrocha** [comment]
I have a problem for running python script.
Has this issue been resolved?

**Comment by RobertoPrevato** [comment]
Hi @kauayrocha,
If you refer to what @xutpuu described when opening this issue, the situation is still like Colin Domoney mentioned in the comment above, and described in his [blog post here](https://medium.com/@colin.domoney/local-build-agents-for-azure-devops-50e6046f87ea).

I am working on the same thing; you need to create a folder structure like this:
```
/azp/agent/_work/_tool/Python/3.7.3/
    --> x64/            # <--- this folder contains /bin from Python
        x64.complete    # <--- this is an empty file with this name
```
I managed to make a working agent running in Docker. Unfortunately, the first time my agent connects to DevOps, something automatically wipes out the `_tool` folder, therefore I didn't manage, yet, to create a Docker image that works right after its first start: for now I only managed installing Python getting inside the container after its first connection to Azure DevOps.

I just published my work in progress in GitHub, so if you use Ubuntu, then you can use this [bash script to install Python in the right location](https://github.com/RobertoPrevato/AzureDevOps-agents/blob/master/ubuntu16.04-tools/scripts/installers/python.sh), having this environmental variable:

```bash
TOOLSFOLDER=/azp/agent/_work/_tool
```
