### ISSUE TITLE
How does this work for multiple environments (stages)?

### ISSUE THREAD

**Issue by hansmbakker** [MicrosoftDocs/vsts-docs#3515]
In Azure Pipelines -&gt; Releases we can define variables multiple times and scope them to stages.

Should I use a different variable group per stage if I want to share variables among different release pipelines?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4827aa99-ae62-bd63-6f2f-a87a4065ed27
* Version Independent ID: c9e461ee-7f42-3503-9460-18fa3a807bbb
* Content: [Variable groups for Azure Pipelines and TFS - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/library/variable-groups?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/library/variable-groups.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/library/variable-groups.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment]
Thank you for your feedback. If all the variables in a group apply to a specific stage, and you have several different sets of values for these variables, it makes sense to create a matrix of variable groups and attach the relevant ones to each pipeline to match the stages that pipeline contains - scoping each variable group to the specifc stage where possible to avoid unintentional overwriting of values.
