### ISSUE TITLE
Slicing options

### ISSUE THREAD

**Issue by LMSSonos** [MicrosoftDocs/vsts-docs#3522]
Using the UI you could slice based on the past running time of tests (see https://docs.microsoft.com/en-us/azure/devops/pipelines/test/parallel-testing-vstest?view=azure-devops#strategy). How can that be achieved in the yaml pipeline?

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 54bf6c2f-95c1-943d-26ae-d7099143bccf
* Version Independent ID: 0833bb55-1e54-6953-ee69-de6d191d2ec1
* Content: [Build and release jobs in Azure Pipelines and TFS - Azure Pipelines](https://docs.microsoft.com/de-de/azure/devops/pipelines/process/phases?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/process/phases.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/phases.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment]
Thank you for your feedback. In the UI you set the slicing using the "Batch tests" property of the Visual Studio Test task. In YAML you do the same by setting the "distributionBatchType" property of the task. See the YAML example and the table of property settings in https://docs.microsoft.com/azure/devops/pipelines/tasks/test/vstest?view=azure-devops#arguments. The options for this property are:
`distributionBatchType: Optional. Options: basedOnTestCases, basedOnExecutionTime, basedOnAssembly`
