### ISSUE TITLE
Inaccurate content on powershell requirements

### ISSUE THREAD

**Issue by awentzel** [MicrosoftDocs/vsts-docs#3524]
This statement "We recommend you configure the agent from an elevated PowerShell window." is inaccurate.  It's not "recommended"  it is "required" .  Especially, if you want to run as a service.  There should be notations on this.

Also, I tried running with configure and a single command passing in all of the command arguments and it didn't ask me to setup as a service.  So content should be updated to specifically call out what's required if you want to run as a service.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43799c5d-2f13-cc76-a1c0-a3f850e16d4e
* Version Independent ID: 97a5b73f-faf7-f9c0-9269-fc79984616d6
* Content: [Deploy a build and release agent on Windows - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/v2-windows?view=azure-devops)
* Content Source: [docs/pipelines/agents/v2-windows.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/agents/v2-windows.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by vtbassmatt** [comment]
The first part is an easy fix.

I have an item on my backlog to document unattended setup. I'll try to get to that today.
