### ISSUE TITLE
We should discuss in detail how to run this as a service

### ISSUE THREAD

**Issue by awentzel** [MicrosoftDocs/vsts-docs#3525]
On Windows just running `.\config.cmd` at the end asks you if you want to run as a service.  This isn't a question on Linux so it can be confusing if coming from Linux onto Windows.  

For Windows VM on Azure if you choose the default option to run as "NT AUTHORITY\SYSTEM" account the service will finish installing, however, upon starting the service from within the services management console it will fail with "incorrect function".  Instead, I had to switch to use "Local System" account.  If you try and use "Local System" from the configuration step it will fail and you have to remove and reconfigure from scratch.

It would be nice to show example of running through the command prompt questions and describing gotchas if any.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43799c5d-2f13-cc76-a1c0-a3f850e16d4e
* Version Independent ID: 97a5b73f-faf7-f9c0-9269-fc79984616d6
* Content: [Deploy a build and release agent on Windows - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/v2-windows?view=azure-devops)
* Content Source: [docs/pipelines/agents/v2-windows.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/agents/v2-windows.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by vtbassmatt** [comment]
The default is NT AUTHORITY\\NETWORK SERVICE - does that cause you problems?

The other nits, I agree and am fixing. Thanks!

**Comment by awentzel** [comment]
@vtbassmatt - Yes, the default from CLI prompt will allow you setup your agent.  However, when you attempt to start the Windows service it will fail with the message indicated above "incorrect function" dialog.  Also, note that if connecting to your VM using AAD / JIT from inside Azure Portal using a user account will also fail, because the service doesn't understand user accounts formatted by emails.  I may have written another issue on this. But, i've forgotten so hopefully this doesn't confuse the issue.  Thanks

**Comment by vtbassmatt** [comment]
I think this is fixed with the publish Steve did 2 weeks ago.
