### ISSUE TITLE
Token for pipelines

### ISSUE THREAD

**Issue by gschrader** [MicrosoftDocs/vsts-docs#3526]
What is the correct procedure to provide a token in pipeline jobs? I can create a personal access token and include that in my gradle file in my repos but obviously that is less than ideal since then it is essentially "public" and will also eventually expire. 

I see there are pipeline tasks for nuget to push to artifacts but there doesn't seem to be an equivalent for maven/gradle artifacts.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 52da1009-6733-d555-3c00-1a1bd77f1759
* Version Independent ID: 72b916de-2836-460b-2889-67981ffea5a4
* Content: [Publish a Maven artifact using Gradle and Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/artifacts/gradle/publish-package-gradle?view=azure-devops&tabs=new-nav)
* Content Source: [docs/artifacts/gradle/publish-package-gradle.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/artifacts/gradle/publish-package-gradle.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by elbatk** [comment]
Hi @gschrader , you should be able to use the [Maven build task](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/maven?view=azure-devops). Are you using the designer or YAML, and are you just trying to push to an Azure Artifacts feed in your org?

**Comment by gschrader** [comment]
@elbatk I assume you mean the [Gradle task](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/gradle?view=azure-devops). Yes I've started with the designer, I guess YAML will probably offer me more possibilities and I should look to convert to that. Yes I'm just trying to push to a feed in my org. I think I'm going to have the same issue with reading from that same feed from another project, although maybe I'm jumping to conclusion and the pipeline agents will already have access.

**Comment by gschrader** [comment]
I thought maybe I figured it out with `$(System.AccessToken)` but it looks like that token doesn't work, at least not with the `AZURE_ARTIFACTS` username anyway.

**Comment by gschrader** [comment]
I got this to work, I found a blog post that suggested `VSTS` as a user, it still didn't work but then found a spot where I wasn't setting the environment variable and after that it worked! So I'm not sure I needed to change the user. I'll see if I can find some time to raise a PR for the docs with an example.

**Comment by elbatk** [comment]
Sorry I was on a flight today! I'm glad you got it working, and I'd be very open to a PR to the docs with an example because I feel like this scenario should be covered. Going to close this, if you don't think you'll have time to do a PR, let me know so I can try to get one going

**Comment by gschrader** [comment]
No worries. I hope your flight was good. It's maybe worth holding off on the documentation until the upstream maven source feature has been released, I'll be one of the first to try that out.

**Comment by elbatk** [comment]
Good to hear! Holding off isn't a bad idea, since we pretty much recommend all of our users to utilize upstreams.
