### ISSUE TITLE
Set your preferences in Azure DevOps Services How-to guides

### ISSUE THREAD

**Issue by johncrossland** [MicrosoftDocs/vsts-docs#3527]
Helpful documentation here to change the date format. Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d28a6661-50d4-527e-9727-ab5974da951d
* Version Independent ID: fdac329a-b9b4-77d0-916a-dee6d2576379
* Content: [View, change user preferences - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/settings/set-your-preferences?view=azure-devops#feedback)
* Content Source: [docs/organizations/settings/set-your-preferences.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/settings/set-your-preferences.md)
* Product: **devops**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Thanks so much, @johncrossland, glad to hear it.
