### ISSUE TITLE
Add additional platforms example results in ubuntu hosted agent for each job rather than using multiple platforms

### ISSUE THREAD

**Issue by petong** [MicrosoftDocs/vsts-docs#3532]
I tested out the matrix example listed here but each of the job pools used the ubuntu hosted agent rather than the image name listed in the matrix.

You can see the build and results here: https://dev.azure.com/augurproject/augur/_build/results?buildId=1689

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5552e8c4-b0c2-f3ff-c69a-607166afb611
* Version Independent ID: 8e73c13c-9b2b-0eac-45ec-4bd3a8d01bb1
* Content: [Create a multi-platform pipeline - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/get-started-multiplatform?view=azure-devops)
* Content Source: [docs/pipelines/get-started-multiplatform.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/get-started-multiplatform.md)
* Product: **devops**
* GitHub Login: @vtbassmatt
* Microsoft Alias: **alewis**

**Comment by vtbassmatt** [comment]
We had a product bug which caused this issue; the example should be working again now.
