### ISSUE TITLE
Azure Pipelines AgentPool URL is wrong

### ISSUE THREAD

**Issue by OranguTech** [MicrosoftDocs/vsts-docs#3533]
Documentation says https://dev.azure.com/{your_organization}/_admin/_AgentPool

At least for us, still using the visualstudio domain, it's 
https://{your_organization}.visualstudio.com/_settings/agentpools

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43799c5d-2f13-cc76-a1c0-a3f850e16d4e
* Version Independent ID: 97a5b73f-faf7-f9c0-9269-fc79984616d6
* Content: [Deploy a build and release agent on Windows - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/v2-windows?view=azure-devops#feedback)
* Content Source: [docs/pipelines/agents/v2-windows.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/agents/v2-windows.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by vtbassmatt** [comment]
Fix in progress, thanks!
