### ISSUE TITLE
How to assign a Parent story to template?

### ISSUE THREAD

**Issue by imag33** [MicrosoftDocs/vsts-docs#3534]
When creating a template I would like the Parent User Story to be defaulted. There is not a pre-determined field in the template. Would/could this be under a user defined selection? Thank you

**Comment by KathrynEE** [comment]
@esunilkumare - Thank you for your inquiry. The capability to default a Parent User Story within a template isn't a supported feature at this time. You can suggest a feature through our [Developer Community page](https://developercommunity.visualstudio.com/spaces/21/index.html).  Please note that you may find a solution in the Marketplace extensions, specifically see [Work item form one click actions](https://marketplace.visualstudio.com/items?itemName=mohitbagra.witoneclickactions). Another method is to use [Excel Tree Query](https://docs.microsoft.com/en-us/azure/devops/boards/backlogs/office/bulk-add-modify-work-items-excel?toc=/azure/devops/boards/backlogs/toc.json&bc=/azure/devops/boards/backlogs/breadcrumb/toc.json&view=azure-devops) to add linked items quickly.
