### ISSUE TITLE
unattended vs service

### ISSUE THREAD

**Issue by awentzel** [MicrosoftDocs/vsts-docs#3538]
Why would someone choose to run 'unattended' vs 'as a service'?  There is another page for this that I've since lost, but, maybe including a link to that page would be useful. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 23328b13-f079-ad21-5d7a-6c640f25391c
* Version Independent ID: 4a39889d-fa00-ae2b-aa43-f358631b7b1a
* Content: [Deploy a build and release agent on Linux - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/v2-linux?view=azure-devops)
* Content Source: [docs/pipelines/agents/v2-linux.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/agents/v2-linux.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by vtbassmatt** [comment]
The instructions already include a pointer to a doc discussing when to run interactively vs as a service. The wording there needed some love, so I've done that.
