### ISSUE TITLE
Example is not very intuitive

### ISSUE THREAD

**Issue by compulim** [MicrosoftDocs/vsts-docs#354]
For example, the "Goal" section only include handful files (no EXE/DLL), and the "Results" section actually got it. Without the knowledge of C#, people will have a hard time understand what's going beneath.

What's more, the example has clunky names like "ConsoleApplication" and "ClassLibrary", not only they are long, they looks very similar when glancing (starts with letter C and a long text).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 81f02378-b85b-d3a4-d3c8-f07d935367da
* Version Independent ID: fab57f76-35d2-4024-6f7f-1740d7b24743
* Content: [Copy Files](https://docs.microsoft.com/en-us/vsts/build-release/tasks/utility/copy-files#goal)
* Content Source: [docs/build-release/tasks/utility/copy-files.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/build-release/tasks/utility/copy-files.md)
* Service: **unspecified**
* GitHub Login: @douge
* Microsoft Alias: **alewis**

**Comment by pjshah70** [comment]
It doesn't tell simple thing, What happen if file mentioned to copy is not found.
 - Is it going to fail and throw error?
 - Is it going to continue and show error in execution log?
 - Is it going to continue without message?

**Comment by mlearned** [comment]
@pjshah70 you control at the task level if you want to continue on error, and yes you get logging as part of this.  Does this make sense?
![image](https://user-images.githubusercontent.com/17324782/41662479-de375656-7466-11e8-84fd-7770416a560c.png)

**Comment by elbatk** [comment]
I've made some updates to this article that should prove helpful, please let me know if there are more things I should add or things I should change!
