### ISSUE TITLE
Can't delete last repo

### ISSUE THREAD

**Issue by vplauzon** [MicrosoftDocs/vsts-docs#3540]
I can't delete the only repo of my project.

I moved my code to GitHub and wanted to use only CI/CD in DevOps for that project.

Is that a limitation if it is the only repo of the project?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b03af1d9-4eeb-ac18-d517-a0a44a2478be
* Version Independent ID: 842691c8-8c41-facf-2cff-03542262f2e5
* Content: [Delete a Git repo from your project - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/delete-existing-repo?view=azure-devops&tabs=new-nav#feedback)
* Content Source: [docs/repos/git/delete-existing-repo.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/repos/git/delete-existing-repo.md)
* Product: **devops**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by Paul-Dempsey** [comment]
yes, it's a known limitation (reported elsewhere). You can create a new blank repo to leave as the last one.
