### ISSUE TITLE
Not up to date FAQ

### ISSUE THREAD

**Issue by vladad** [MicrosoftDocs/vsts-docs#355]
You should update question "Q: Is there support for TFVC repositories?", because some support of TFVC is implemented.

See referenced description on GitHub source code:
"This is a plugin for working with Git and TFVC repositories on Visual Studio Team Services (VSTS) and Team Foundation Server (TFS) 2015+ inside IntelliJ, Android Studio, and various other Jetbrains IDEs."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3378875f-5f9d-8992-a01d-8ea87e019861
* Version Independent ID: b098532e-61ee-0906-8b50-9108e50e2732
* Content: [Get the Android Studio VSTS plug-in](https://docs.microsoft.com/en-us/vsts/java/download-android-studio-plug-in)
* Content Source: [docs/java/download-android-studio-plug-in.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/java/download-android-studio-plug-in.md)
* Service: **unspecified**
* GitHub Login: @douge
* Microsoft Alias: **douge**

**Comment by steved0x** [comment]
@vladad Thanks for letting us know, I have just fixed this and it should be live soon. Thank you!
