### ISSUE TITLE
Generate YML from azure portal

### ISSUE THREAD

**Issue by trysivaprakash** [MicrosoftDocs/vsts-docs#3552]
Can we generate azure-pipelines.yml from portal after we do configure everything in portal itself? Seems easy to set triggers, and post deployment actions in portal rather than editing an yml file with appropriate syntax.

**Comment by steved0x** [comment]
@trysivaprakash In some places there is a "View YAML" button that lets you see the YAML configuration for the elements that you have configured in the designer:

![image](https://user-images.githubusercontent.com/1580889/53748007-731d3a80-3e72-11e9-8e1a-a818bac6a165.png)

Note that some features are not available in YAML and if you are configuring those features, you wouldn't be able to get a YAML configuration generated for those. For example you can configure build pipelines with YAML but not yet release pipelines. For example, in the Build pipeline triggers article:

https://docs.microsoft.com/en-us/azure/devops/pipelines/build/triggers?view=azure-devops&tabs=yaml#scheduled

Scheduled and Build completion triggers are not yet supported for YAML, but CI and PR builds are.

What sort of pipeline are you building?
