### ISSUE TITLE
Additional configuration required for self-hosted agents

### ISSUE THREAD

**Issue by Leon99** [MicrosoftDocs/vsts-docs#3553]
Neither this page nor https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/agents?view=azure-devops#install mentions that additional configuration is required in order to use self-hosted agents. Related issues:
https://github.com/Microsoft/azure-pipelines-tasks/issues/4449
https://github.com/Microsoft/azure-pipelines-agent/issues/1003
Also, just adding `"group" : "Network Service"` to daemon.json didn't help me to solve the `open //./pipe/docker_engine: Access is denied` error, only reconfiguring the agent to run under SYSTEM did.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e825c07d-2168-c0aa-782a-ef6f9c7ba95e
* Version Independent ID: 5cb6926b-215a-bf89-8e63-b2e1129e41df
* Content: [Build, test, and push Docker container apps - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/languages/docker?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/languages/docker.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/languages/docker.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by Leon99** [comment]
@steved0x were there any changes made? Why was this closed?

**Comment by lonevvolf** [comment]
Please advise - we are also hitting this issue.

**Comment by arcotek-ltd** [comment]
I'm not sure why @steved0x closed this. This vital piece of information seems to be missing from all Azure DevOps / Docker information

I _must_ have the VSTS agent running as a particular service account. e.g. svc_vsts.

The only way I could get rid of the `access denied` error was to add svc_vsts to local administrators group and set the Docker Engine service to run as the same service account (svc_vsts) as the VSTS agent.

@Microsoft, we need _exact_ details of what permissions are required. I cannot leave svc_vsts in local administrators. [Be sure your pipelines agent has permission to access the Docker daemon](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/container-phases?view=azure-devops&tabs=yaml#windows-containers). is _not_ enough, as per @TingluoHuang's comment https://github.com/microsoft/azure-pipelines-agent/issues/2082#issuecomment-463734426.

TIA.

**Comment by devneutz** [comment]
Still encountering this issue - has there been any progress or different approaches?

**Comment by davewasthere** [comment]
Yeah, still an issue, but this is how I resolved it.

- Create a local user (azureagent)
- Add that user to the Docker Users group
- Modify the azureAgent service to logon as that user

Restart the service, and you're golden. The agent logs in as a user rather than Network Service account, and correctly has access to docker daemon without any other privileges.
