### ISSUE TITLE
How do we configure firewall on Azure using VM's

### ISSUE THREAD

**Issue by awentzel** [MicrosoftDocs/vsts-docs#3557]
We should not assume users implementing self-hosted agents understand how to configure their firewalls.

Please add instructions on how someone would go about "To ensure your organization works with any existing firewall or IP restrictions, ensure that dev.azure.com is open and the 13.107.6.183 and 13.107.9.183 IP addresses are allowed."  while using Azure VM's.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43799c5d-2f13-cc76-a1c0-a3f850e16d4e
* Version Independent ID: 97a5b73f-faf7-f9c0-9269-fc79984616d6
* Content: [Deploy a build and release agent on Windows - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/v2-windows?view=azure-devops)
* Content Source: [docs/pipelines/agents/v2-windows.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/agents/v2-windows.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by vtbassmatt** [comment]
Thanks for the feedback. Exact steps to configure particular firewalls is beyond the scope of what we can reasonably document. In a vanilla Azure VM, you shouldn't need to configure the Windows firewall since the agent only makes outbound connections.

**Comment by awentzel** [comment]
@vtbassmatt, what about adding a note based on your response --> "In a vanilla Azure VM, you won't need to configure the firewall since the agent only makes outbound connections"  

For a while, when I was having trouble getting up and running I started questioning everything and so these extra notes are helpful to isolate potential issues when working on this for the first time. Also, It sometimes useful, to provide a link to firewall management for those advanced scenarios.
