### ISSUE TITLE
Why would I want to run behind a web proxy

### ISSUE THREAD

**Issue by awentzel** [MicrosoftDocs/vsts-docs#3558]
How would someone know whether or not they should run behind a web proxy?  The intro to this page should first cover **why** then cover key scenarios that are best practices.  This way it's helpful to the user to get the best configuration.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e47a1942-09cb-f294-f1d3-09999645afb7
* Version Independent ID: 7b885f66-7165-ae4f-d35f-3cffe84cce28
* Content: [Run the agent behind a web proxy - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/proxy?view=azure-devops&tabs=windows)
* Content Source: [docs/pipelines/agents/proxy.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/agents/proxy.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by fowl2** [comment]
eg. "Note: This is only required if the network your agents are connected to requires the use of an HTTP proxy to access the Azure DevOps servers" ?

**Comment by vtbassmatt** [comment]
Good idea!
