### ISSUE TITLE
.NET Core example doesn't work on Windows

### ISSUE THREAD

**Issue by Leon99** [MicrosoftDocs/vsts-docs#3559]
https://github.com/MicrosoftDocs/pipelines-dotnet-core/blob/master/azure-pipelines.docker.yml (as well as https://github.com/MicrosoftDocs/pipelines-dotnet-core/blob/master/azure-pipelines.acr.yml) uses `$pswd` inside a command, which won't work on Windows since `script` step is executed using cmd.exe on Windows.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e825c07d-2168-c0aa-782a-ef6f9c7ba95e
* Version Independent ID: 5cb6926b-215a-bf89-8e63-b2e1129e41df
* Content: [Build, test, and push Docker container apps - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/languages/docker?view=azure-devops&tabs=yaml#troubleshooting)
* Content Source: [docs/pipelines/languages/docker.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/languages/docker.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by vijayma** [comment]
The repo and instructions have been updated using the above PR.
