### ISSUE TITLE
How about error "Failed to query service endpoint"

### ISSUE THREAD

**Issue by jpalo** [MicrosoftDocs/vsts-docs#356]
I've successfully created service endpoint for DEV, but subsequently trying to create same for TEST/PROD Resource Groups fail with error when pressing "Verify connection":
"Failed to query service endpoint api: https://management.azure.com//subscriptions/<GUID>?api-version=2016-06-01. Error Message: The remote server returned an error: (403) Forbidden.." 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 010be6f9-10ae-a117-5354-7084a6843518
* Version Independent ID: 25941814-7c61-cc10-b943-7e47a8e90177
* Content: [How to troubleshoot Azure Resource Manager service endpoints in VSTS and TFS](https://docs.microsoft.com/en-us/vsts/build-release/actions/azure-rm-endpoint)
* Content Source: [docs/build-release/actions/azure-rm-endpoint.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/build-release/actions/azure-rm-endpoint.md)
* Service: **unspecified**
* GitHub Login: @douge
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment]
Thank you for your feedback. I will pass your question onto the product team and let you know their response.

**Comment by alexhomer1** [comment]
Unfortunately I am unable to obtain any more useful information. If you are still experiencing this problem, please let me know with more details that I can pass on to the product team.

**Comment by vocko** [comment]
I do experience the same thing with TFS 2017, I suspect it is somehow related to the service principal permissions.

**Comment by rajivramanjani** [comment]
I am also facing this issue with TFS 2019.  Do we have any resolution to this?

**Comment by rajivramanjani** [comment]
@alexhomer1 did you ever get a solution from the product team.  We have a Azure container registry tied to an Azure app service.  Code sits on TFS 2019.  We are unable to create a service principal connection between TFS 2019 and the Azure container registry.  An app registry is also in place on the Azure Active Directory.
