### ISSUE TITLE
Supported PowerShell versions

### ISSUE THREAD

**Issue by Leon99** [MicrosoftDocs/vsts-docs#3560]
From 
&gt; You can run a PowerShell Script on a Windows build agent
I make an assumption that there is no way to make use of PS6, but it'd be good to have that explicitly stated. Also, would be good to see any info related to support of pwsh, if it's possible somehow or, at least, planned.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77731c06-e4fd-8125-0daf-870c9ccedd3f
* Version Independent ID: 0d5c338d-80f9-c64e-b675-bf7b4eb8e32b
* Content: [Use a PowerShell script to customize your build pipeline - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/scripts/powershell?view=azure-devops)
* Content Source: [docs/pipelines/scripts/powershell.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/scripts/powershell.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by vtbassmatt** [comment]
This will be fixed by an unrelated commit that's landing soon.
