### ISSUE TITLE
Create more detailed feedback

### ISSUE THREAD

**Issue by eal61** [MicrosoftDocs/vsts-docs#3566]
I would like to be able to have the error message from a deployment failure to be included in the webhook message. It's pretty vague when every failure is reported as "Deployment status: rejected"

https://docs.microsoft.com/en-us/azure/devops/service-hooks/services/slack?view=azure-devops

**Comment by steved0x** [comment]
@eal61 I checked with the product team, they recommend that you file a feature request to have this additional details included. You can file it by choosing **Product feedback** at the bottom of the article:

![image](https://user-images.githubusercontent.com/1580889/51848904-90e40680-22ec-11e9-893f-ded2716f3ea2.png)

or you can file an issue directly at https://developercommunity.visualstudio.com/spaces/21/index.html

Thank you for your feedback.
