### ISSUE TITLE
Documentation for counters is missing

### ISSUE THREAD

**Issue by avivanoff** [MicrosoftDocs/vsts-docs#3567]
Looks like documentation for counter expressions  is missing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77c58a78-a567-e99a-9eb7-62dddd1b90b6
* Version Independent ID: 680a79bc-11de-39fc-43e3-e07dc762db18
* Content: [Expressions - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/expressions?view=azure-devops)
* Content Source: [docs/pipelines/process/expressions.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/expressions.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by NightOwl888** [comment]
For the time being, it seems all of the information about `counter()` is at https://stackoverflow.com/a/52735197 and https://github.com/Microsoft/azure-pipelines-agent/pull/1489/files#diff-364a30a6897fc5fa754cb0755dcaf891

**Comment by andyjlewis** [comment]
Thanks for the feedback. I believe changes we made in May fixed this issue.
