### ISSUE TITLE
Is this data safe to delete?

### ISSUE THREAD

**Issue by StingyJack** [MicrosoftDocs/vsts-docs#357]
the Dim/Fact TestResult tables have millions of rows of data that is taking up several gigs of space. We don't really use it and I would like to know the implications of deleting the data in whole or part.

As an aside, much of it is duplicated due to a defect in the vNext build Test task, where it's globbing pattern picks up the same test dll in multiple folders and runs the test assembly multiple times for a build. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3deea0ff-18e2-d8dd-1265-2e09467b1edf
* Version Independent ID: df72b337-3167-0c7b-50c0-d58d154ac356
* Content: [Test Result tables](https://docs.microsoft.com/en-us/vsts/report/sql-reports/test-result-tables)
* Content Source: [docs/report/sql-reports/test-result-tables.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/report/sql-reports/test-result-tables.md)
* Service: **unspecified**
* GitHub Login: @douge
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@StingyJack - Thank you for your inquiry. Please review this topic - https://docs.microsoft.com/en-us/vsts/manual-test/getting-started/how-long-to-keep-test-results?view=vsts - to learn how to set the retention policy for test results. Meanwhile, I will update the topic you inquired about with this same information.

**Comment by StingyJack** [comment]
@KathrynEE  -  I know how to set the retention policy, but that does not seem to affect test results already stored that I wanted to remove.  (That setting also is kind of sucky that its a per project one and not a per-collection one.) 

I ended up just recreating a new warehouse and cube recently as it decided to stop updating, so I guess that is how to delete the extra table data
