### ISSUE TITLE
Task arguments in YAML task

### ISSUE THREAD

**Issue by amirschw** [MicrosoftDocs/vsts-docs#3571]
I'm trying to use this task in a YAML pipeline but am unsure regarding what is a valid input to the feed & definition parameters. The task fails when I try something like the following:
- task: DownloadPackage@0
  displayName: 'Download Package'
  inputs:
    feed: 'feedName'
    definition: 'packageName'
    version: 1.0.0

Thanks,
Amir

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ff8354ee-807f-0c1f-8e5b-9303c4591c60
* Version Independent ID: 1fd42523-8504-76cf-deec-26c5fccd0109
* Content: [Download Package task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/download-package?view=azure-devops#feedback)
* Content Source: [docs/pipelines/tasks/utility/download-package.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/utility/download-package.md)
* Product: **devops**
* GitHub Login: @steved0x
* Microsoft Alias: **dastahel**

**Comment by amirschw** [comment]
I tried using lower cased letters for the definition (package name) and it worked.

**Comment by elbatk** [comment]
Hi @amirschw , was the package you were trying to download in all lower cased? As in, was this just a case the task being case-sensitive, or does the package use upper-cased and you had to use all lower-cased (which would be a bug, I think).

**Comment by amirschw** [comment]
Hi @elbatk. The package does use upper-case letters.

**Comment by elbatk** [comment]
Ah okay. I'll check it out. It sounds like this task really uses the REST APIs to find a GUID for the package. We have some updates in the works for it, but for now I may update the documentation here a bit. Thanks!
