### ISSUE TITLE
SQL Server Comparability Chart

### ISSUE THREAD

**Issue by DoomerDGR8** [MicrosoftDocs/vsts-docs#3572]
I need to know what version of SQL Server is required by TFS 2018

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 84ec61ca-02ef-740d-d9a3-98f088e3f27d
* Version Independent ID: d5ed9d97-9db5-9d9e-70ed-414093d79fa9
* Content: [Look up version compatibility for Azure DevOps clients - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/server/compatibility?view=azure-devops)
* Content Source: [https://mseng.visualstudio.com/DefaultCollection/TechnicalContent/_git/tfs-docs-pr?path=%2fdocs%2fcompatibility.md&version=GBlive&_a=contents](https://mseng.visualstudio.com/DefaultCollection/TechnicalContent/_git/tfs-docs-pr?path=%2fdocs%2fcompatibility.md&version=GBlive&_a=contents)
* Product: **devops-server**
* Git Login: **aaronhallberg**
* Microsoft Alias: **aaronha**

**Comment by nschonni** [comment]
That is the page before in the right hand menu https://docs.microsoft.com/en-us/azure/devops/server/requirements?view=tfs-2018
