### ISSUE TITLE
maxParallel and parallel in YAML Schema

### ISSUE THREAD

**Issue by YoDaMa** [MicrosoftDocs/vsts-docs#3575]
In the YAML schema reference there's an indication for how to use maxParallel with Matrix, but not with parallel. I think there's a bug where you cannot use maxParallel and parallel in tandem when writing a pipeline... 

Also for reference:
https://stackoverflow.com/questions/55029457/limiting-number-of-parallel-jobs-in-azure-devops-pipeline-yaml/55029519#55029519

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7458d5b2-1bb7-7d87-7ce6-2b0c430b0155
* Version Independent ID: edf5bbd3-a3f0-5426-e985-31290f8afd05
* Content: [YAML schema - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=example#feedback)
* Content Source: [docs/pipelines/yaml-schema.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/yaml-schema.md)
* Product: **devops**
* GitHub Login: @steved0x
* Microsoft Alias: **macoope**

**Comment by steved0x** [comment]
@YoDaMa Thank you for your feedback. I am sending you a private email.

**Comment by vtbassmatt** [comment]
Product bug. I'm closing this docs bug as we're tracking internally.
