### ISSUE TITLE
Customizing Microsoft Host Agent (build-machine)

### ISSUE THREAD

**Issue by Imran-Siddiqui-POMS** [MicrosoftDocs/vsts-docs#3578]
@vtbassmatt Hi, I need to install third party software in Microsoft Hosted Agent in order to successfully build our solution in build pipeline.
1. BarTender
2. Loftware Clients
3. Oracle Clients
4. ODAC
5. Crystal Reports Runtime for .NET

I've tried to install these third party dependencies using CMD, Powershell, Batch Script, Silent Installation tasks available in build pipeline and I also need to confirm that software are actually installed or not. so, I used powershell to export registry or list of installed software from Microsoft Hosted Agent after the tasks succeeded but the problem is that only Crystal Reports Runtime for .NET is appearing in both exports and other software are not.

Could anyone suggest alternate ways to do this in Microsoft Hosted Agent? I do not want to use Self Hosted Agent for some reasons.

**Comment by vtbassmatt** [comment]
On your local machine, after you install that software, does your registry export and list of installed software show those packages? I'm trying to narrow down if this is something specific to the build agent or if it's the nature of the packages you're installing.

On the hosted agents, you should have administrator privileges to install any software you need. You might need to tell the installers to do unattended installs or pass a command-line flag to let it know there's no human present - perhaps they're getting stuck waiting on a wizard screen or something?

**Comment by Imran-Siddiqui-POMS** [comment]
@vtbassmatt Yes all of them does. (build pipeline's tasks are added to install them, tasks succeed in execution, but as I said software never installed in actual (I have confirmed through getting installed software list and registry export from build agent).

I've tasks to do full silent installation for installer software and batch execution files for ODAC and Oracle Clients, already tested on VMs and Local Machine to do the right job.

**Comment by vtbassmatt** [comment]
Hmm, OK. Sounds like we need deeper troubleshooting. Here's what I'd ask you to do: use "Report a problem" on [Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html). We're currently chatting in the documentation repo, which isn't the right place for support. When you open that issue, please make sure to include:
- the scripts doing the installation -- whether those are inline script tasks, or .sh/.cmd/.ps1 files, etc.
- the scripts doing the checking
- a complete copy of your build logs *with System.Debug set to **True*** - you can run a build with that variable set, then click "Download logs" after it completes to get a zip file

If any of this is sensitive, there are ways to post attachments such that only Microsoft personnel can see them.

Thanks, and sorry for the hassle!
