### ISSUE TITLE
Dead link for TfsMigrator tool

### ISSUE THREAD

**Issue by jeyoung** [MicrosoftDocs/vsts-docs#3581]
The link to the TfsMigrator tool and documentation download does not work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a5f4848a-7264-7f5b-ed00-55a7a1274f3f
* Version Independent ID: 6bbfd17e-309f-435b-0e57-a3807b5f5b20
* Content: [Migration overview from TFS to Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/articles/migration-overview?view=azure-devops#feedback)
* Content Source: [docs/articles/migration-overview.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/articles/migration-overview.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by elbatk** [comment]
Adding @roofers to take a look.

**Comment by roofers** [comment]
@jeyoung - Which link isn't working for you? I clicked through all the aka.ms links on the page and they appear to be working.

**Comment by jeyoung** [comment]
![image](https://user-images.githubusercontent.com/67193/53972366-8dffe100-40f6-11e9-8479-5ea5ff05bc44.png)

Which takes to https://www.microsoft.com/en-us/download/details.aspx?id=54274, but I get a "page not found" error:

![image](https://user-images.githubusercontent.com/67193/53972475-cb646e80-40f6-11e9-900c-e88fa7672d59.png)

**Comment by jeyoung** [comment]
Right after I posted my comment, the link started working again. Go figure 🤷‍♂️

**Comment by elbatk** [comment]
Glad it works :) going to close this now, let us know if you're having issues again.
