### ISSUE TITLE
Subscribing to build started

### ISSUE THREAD

**Issue by SoumitaDatta** [MicrosoftDocs/vsts-docs#3585]
When I attempt to subcribe to Build Started on a build pipeline, I dont see the option in the dropdown. Only option available is the Build completed. What am I missing ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 99a6f5aa-7e92-a028-d13e-e1e4b7fede86
* Version Independent ID: be7e5d7c-0033-6b72-4bd1-809f7d1894aa
* Content: [Azure Pipelines with Slack - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/integrations/slack?view=azure-devops#feedback)
* Content Source: [docs/pipelines/integrations/slack.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/integrations/slack.md)
* Product: **devops**
* GitHub Login: @atinb
* Microsoft Alias: **atinb**

**Comment by atinb** [comment]
@SoumitaDatta You are right. There is no Build Started event, only Build Completed with filters on the outcome of the Build. Thanks

**Comment by xilefius** [comment]
We be really nice to have this options, I currently have so use a custom slack integration for the build definition for this

**Comment by 97turbotalon** [comment]
We are also in need of a Build Started event for this app be a complete replacement for our current slack integration.

**Comment by atinb** [comment]
@97turbotalon We are using the same service hooks as the current Slack integration. Service hooks do not support Build started event and hence I am interested to understand how you are getting these events in your current integration.

**Comment by carct** [comment]
@atinb can the release part (stage selection and approval) be updated to work with the new multi-stage yaml deployments ?

**Comment by atinb** [comment]
@carct We are working on supporting the yaml based pipelines. We should have this support live in the next couple of sprints. Thanks!

**Comment by swiatlamiasta** [comment]
@atinb Hello, not sure if it's a good place to ask, but has the support for yaml release pipelines been implemented? I tried to set up notifications for one the other day but it didn't seem to work properly. Thanks in advance.

**Comment by mijacobs** [comment]
Thanks, everyone! It looks like the issue has been resolved, closing it.  To make future suggestions/feature requests  get in front of the right people for triage, please [submit your idea]( https://developercommunity.visualstudio.com/content/idea/post.html?space=21) here.
