### ISSUE TITLE
Specify Application Url Clarification

### ISSUE THREAD

**Issue by JoshuaBelden** [MicrosoftDocs/vsts-docs#3586]
For this document to be useful, it would be good to describe how we go about telling DevOps to allow client urls.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1c792d9d-54c9-e8d1-b82c-a60f818a4389
* Version Independent ID: d1f483e8-3bd7-5a29-50e1-cfc7788b64ba
* Content: [Cross-origin resource sharing (CORS) with Azure DevOps Services REST APIs](https://docs.microsoft.com/en-us/azure/devops/integrate/concepts/cross-origin-resource-sharing?view=azure-devops#feedback)
* Content Source: [docs/integrate/concepts/cross-origin-resource-sharing.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/integrate/concepts/cross-origin-resource-sharing.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by KathrynEE** [comment]
@thomps23 - Ryan - I'm reassigning this back to you. Not sure who should be covering Elijah's work, but I know it isn't me.

**Comment by JoshuaBelden** [comment]
I might have been confusing the oauth flow and simply auth'ing with a personal access token. With Postman, I was able to call the api with a PAT. When I wired up a test Angular app, the PAT would authorize, but their were no CORS headers returned. I believe this was because I would have to actually implement the oauth flow. At the time, I didn't see any mention of adding a client url.

**Comment by chcomley** [comment]
That's great, @JoshuaBelden. I believe this GitHub Issue can be closed then, but do let us know if you have any other feedback or questions please. We can always create a new issue. Have a great day!
