### ISSUE TITLE
pwsh?

### ISSUE THREAD

**Issue by Leon99** [MicrosoftDocs/vsts-docs#3587]
According to https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=example#pwsh, there is `pwsh` alias. However, it's not mentioned here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a0e444c2-69c6-4d71-6fd0-94d0f4097d3a
* Version Independent ID: 3a727833-1cc3-c2fb-c5b3-22605eee2721
* Content: [PowerShell task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/powershell?view=azure-devops)
* Content Source: [docs/pipelines/tasks/utility/powershell.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/utility/powershell.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by FISHMANPET** [comment]
My guess on reading between the lines and seeing some examples is that the pwsh alias would run Powershell Core, while the powershell alias runs non-core Powershell (what the heck do we call that, classic? desktop? legacy? old?)

And then I'm further guessing that if you're running the PowerShell task without the alias, and either don't specify pwsh or set it to false, that it will run non-core Powershell, and if you set it to true it will run with Powershell Core.

Digging into the source code, and finding some closed issues referencing pwsh confirms my belief.

**Comment by Leon99** [comment]
@FISHMANPET I suspect you're right, but documentation can definitely be improved to highlight the differences between the shortcuts, as well as describe `pwsh` flag, which is only mentioned commented out in the sample and not explained anywhere.

**Comment by AArnott** [comment]
Yes. In fact every Pipeline task in these docs list parameter names and then in a table describe (some of) them by a human name instead of a machine name. Please update all the tables to actually include a column for that *actual* task parameter name in addition to the human readable names so we know what parameter name is being described.
