### ISSUE TITLE
Widget Position Does Not Stick When Page Refreshes

### ISSUE THREAD

**Issue by KennyDay** [MicrosoftDocs/vsts-docs#3588]
I've added widgets to my dashboard both via the "Add Widget" method and copying and existing widget.  I go into edit mode and place them where I want them, exit edit mode and everything looks good.  I then refresh the page and the controls have moved back to the spot they we're when they we're added.  

The dashboard has 175 widgets and the first 160+ hold their position as expected.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dcb11d2d-86bd-ff52-d191-4da86d54b473
* Version Independent ID: 79438e17-b3d3-0331-5040-98107eb840a2
* Content: [Dashboards, charts, & widgets - Azure DevOps & TFS](https://docs.microsoft.com/en-us/azure/devops/report/dashboards/overview?view=azure-devops#feedback)
* Content Source: [docs/report/dashboards/overview.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/report/dashboards/overview.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KennyDay** [comment]
I ***beleive*** I see what's going on.  I can't find any information on the max width of a dashboard and making an assumption it's 25 tiles.  Any tile I place in column 26+ reverts back to it's original location when refreshing.  It's a bit confusing because a widget can expand beyond 25 columns if it starts in column 25.

Can I have just 1 more column please:).

**Comment by KathrynEE** [comment]
@KennyDay - Thank you for your inquiry. You can suggest a feature through our [Developer Community page](https://developercommunity.visualstudio.com/spaces/21/index.html). I will follow up with the PM to determine the maximum tiles and columns that we support and update the topic accordingly.
