### ISSUE TITLE
Missing info on how often reevaluation will happen

### ISSUE THREAD

**Issue by borys86** [MicrosoftDocs/vsts-docs#3589]
There is a button to reevaluate group-based resource membership but it is unclear how often it will happen.
It would also be cool to know how to automate this. We would love to run this reevaluation at least once an hour. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b11efd92-bbc3-2ae9-e0a6-0cf51cafe0dd
* Version Independent ID: 72839556-39e4-5719-7f98-a7cf35536a72
* Content: [Migrate to group-based resource management - Azure DevOps - Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/migrate-to-group-based-resource-management?view=azure-devops#feedback)
* Content Source: [docs/organizations/accounts/migrate-to-group-based-resource-management.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/accounts/migrate-to-group-based-resource-management.md)
* Product: **devops**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @borys86, thanks for reaching out! I've created a user story for my backlog to address your feedback and will be in touch. Thanks again.

**Comment by chcomley** [comment]
Hi @borys86, I've followed up with the product group and learned that it's automated on our side and runs every six hours. Anytime the group rule changes, the rules are also re-run. I've added this clarifying info to the article, as well, which should be live sometime this afternoon. Please let me know if you have any further questions. Thank you.
