### ISSUE TITLE
Revoking access by a global admin

### ISSUE THREAD

**Issue by KumoJosh** [MicrosoftDocs/vsts-docs#359]
Is there a way to revoke access of PAT's by a global admin?  I'd like the ability as a global admin to revoke access tokens for employees if they have generated PATs and then their account becomes terminated.  

Or alternatively, if a user's account is terminated, do all of the PAT's get automatically revoked?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ac980303-2c9f-210b-b00e-155065cac059
* Version Independent ID: 90e734ea-1745-ef3b-cf46-4ae8a2954fda
* Content: [Authenticate access with personal access tokens](https://docs.microsoft.com/en-us/vsts/accounts/use-personal-access-tokens-to-authenticate)
* Content Source: [docs/accounts/use-personal-access-tokens-to-authenticate.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/accounts/use-personal-access-tokens-to-authenticate.md)
* Service: **unspecified**
* GitHub Login: @douge
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
@KumoJosh Thank you for your comments! Currently there is no way for an admin to revoke alt-auth credentials, such as PATs.  We have it on our backlog to add this feature but don’t have a timeline for delivery yet.  If an account is disabled or deleted, the PATs will no longer work.  If there is ever any doubt, you can call customer support and have them revoke a PAT for you.
