### ISSUE TITLE
duplicate page

### ISSUE THREAD

**Issue by borys86** [MicrosoftDocs/vsts-docs#3590]
https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/assign-access-levels-and-extensions-by-group-membership?view=azure-devops

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b11efd92-bbc3-2ae9-e0a6-0cf51cafe0dd
* Version Independent ID: 72839556-39e4-5719-7f98-a7cf35536a72
* Content: [Migrate to group-based resource management - Azure DevOps - Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/migrate-to-group-based-resource-management?view=azure-devops)
* Content Source: [docs/organizations/accounts/migrate-to-group-based-resource-management.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/accounts/migrate-to-group-based-resource-management.md)
* Product: **devops**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Thanks @borys86. I've created a user story on my backlog to investigate this. Thanks for your feedback!

**Comment by chcomley** [comment]
Hi @borys86, I've merged the two articles and so we're left with [this one](https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/assign-access-levels-and-extensions-by-group-membership?view=azure-devops), which should be live this afternoon. Thanks again for your feedback! We appreciate it.
