### ISSUE TITLE
This documentation is just not working.

### ISSUE THREAD

**Issue by ricrogz** [MicrosoftDocs/vsts-docs#3595]
Trying to build anything inside a conda environment on a Ubuntu or Mac image is the most frustrating thing I have tried in a long time. Using the instructions to add conda to the path just don't work, it always ends up in a "CommandNotFoundError: Your shell has not been properly configured to use 'conda activate'. [...]" message, after which the build fails, because the conda environment cannot be activated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b99fb08-2474-be71-62db-cbafec749cb3
* Version Independent ID: af525f70-f636-4fb2-e4e6-03a2dd759c24
* Content: [Run pipelines with Anaconda environments - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/languages/anaconda?view=azure-devops&tabs=ubuntu-16-04#feedback)
* Content Source: [docs/pipelines/languages/anaconda.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/languages/anaconda.md)
* Product: **devops**
* GitHub Login: @steved0x
* Microsoft Alias: **brcrista**

**Comment by tallamjr** [comment]
@ricrogz how were you able to resolve this?

**Comment by ricrogz** [comment]
I haven't. My mac builds keep failing the tests, and I can't figure why.

Besides that, instructions to add conda to the path only work for Win, and any useful information about the system or how to get things done is disseminated all over the place.

For linux & mac, you need to resource conda.sh and activate your env in each script/bash item, as it seems each of those is executed in a separate shell session. And, of course, sourcing bash and profile scripts is disabled by default in bash. It would be quite nice to just dump whatever env preparing into one of those and have it done automatically... but no, the default behavior is not to source them.

**Comment by jainr** [comment]
Is this resolved, I am also running into same issue, source activate does not work
#
# To activate this environment, use:
# > source activate nlp
#
# To deactivate an active environment, use:
# > source deactivate
#

# conda environments:
#
base                  *  /usr/share/miniconda
ml                      /usr/share/miniconda/envs/ml

/home/vsts/work/_temp/674bae98-1428-43b1-8887-e7e8ffcbf097.sh: line 5: activate: No such file or directory
##[error]Bash exited with code '1'.

**Comment by ricrogz** [comment]
> Is this resolved, I am also running into same issue, source activate does not work
> # To activate this environment, use:
> # > source activate nlp
> # To deactivate an active environment, use:
> # > source deactivate
> # conda environments:
> 
> base * /usr/share/miniconda
> ml /usr/share/miniconda/envs/ml
> 
> /home/vsts/work/_temp/674bae98-1428-43b1-8887-e7e8ffcbf097.sh: line 5: activate: No such file or directory
> ##[error]Bash exited with code '1'.

I think "source activate" is outdated. Works with "conda activate", I think.

**Comment by tallamjr** [comment]
Hi @jainr , I managed to resolve this with these commands in my `azure-pipelines.yml` : 
```
     ...
      - source $HOME/miniconda/etc/profile.d/conda.sh
      - conda activate <YOUR-ENV-NAME>
    ...
```
Note, I removed the "add conda to you path" that is listed in the docs and found the following to be more helpful:
```
  - bash: |
      - sudo apt-get update
      - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
      - bash miniconda.sh -b -p $HOME/miniconda
      - export PATH="$HOME/miniconda/bin:$PATH"
      - hash -r
      - conda config --set always_yes yes --set changeps1 no
      - conda update -q conda
      - conda info -a
      - which conda
      - conda --version
      - conda env create -f environment.yml
      - echo $PATH
      - source $HOME/miniconda/etc/profile.d/conda.sh
      - conda activate <YOUR-ENV-NAME>
    displayName: 'Setup conda/install dependencies'

```
Hope this helps..
