### ISSUE TITLE
Update notes about unavailability of Microsoft-hosted 1803 hosts

### ISSUE THREAD

**Issue by o-farooq** [MicrosoftDocs/vsts-docs#3598]
Now that [Microsoft-hosted 1803 hosts](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml) are available  , please add a section for Windows Server 1803 (win1803)  under Build environment and remove the following notes 

> We don't yet have a pool of Microsoft-hosted agents running Windows Server 1803. Until this is available, you can build Windows Server 1803 images by using self-hosted agents

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e825c07d-2168-c0aa-782a-ef6f9c7ba95e
* Version Independent ID: 5cb6926b-215a-bf89-8e63-b2e1129e41df
* Content: [Build, test, and push Docker container apps - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/languages/docker?view=azure-devops&tabs=yaml&viewFallbackFrom=vsts#use-docker-compose)
* Content Source: [docs/pipelines/languages/docker.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/languages/docker.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by vijayma** [comment]
Fixed through the above PR.
