### ISSUE TITLE
Best practices

### ISSUE THREAD

**Issue by trajano** [MicrosoftDocs/vsts-docs#3599]
Can we have a page that details the best practices of doing a release pipeline?  Or some recipes for 

* Approval processes
* Multiple microservice deployments

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7836427c-b7e4-bd71-88f4-b851334c4ba5
* Version Independent ID: 92ffae5e-9ecc-4639-8a7c-38f68383df2c
* Content: [Understand release pipelines and options - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/?view=azure-devops)
* Content Source: [docs/pipelines/release/index.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/release/index.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment]
Thank you for your feedback. This topic describes techniques for using approvals: https://docs.microsoft.com/azure/devops/pipelines/release/approvals/. These two topics describe how to use multi-stage pipelines with approvals: https://docs.microsoft.com/azure/devops/pipelines/release/define-multistage-release-process and https://docs.microsoft.com/azure/devops/pipelines/release/deploy-using-approvals. I hope this helps.
