### ISSUE TITLE
Typo in the Shielding distractions paragraph

### ISSUE THREAD

**Issue by monosoul** [MicrosoftDocs/vsts-docs#3601]
There's a typo in the Shielding distractions paragraph (https://docs.microsoft.com/en-us/azure/devops/learn/devops-at-microsoft/agile-principles-in-practice#shielding-distractions): "...to plan activities outside of work **mcuh** easier"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 80853077-4c90-2663-7ed6-5fadbcf4f4ed
* Version Independent ID: 4864bcb3-1930-d4f1-c927-1adbbb2899ac
* Content: [Agile principles in practice - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/learn/devops-at-microsoft/agile-principles-in-practice)
* Content Source: [https://mseng.visualstudio.com/DefaultCollection/TechnicalContent/_git/devops-learn-pr?path=%2fdocs%2fdevops-at-microsoft%2fagile-principles-in-practice.md&version=GBlive&_a=contents](https://mseng.visualstudio.com/DefaultCollection/TechnicalContent/_git/devops-learn-pr?path=%2fdocs%2fdevops-at-microsoft%2fagile-principles-in-practice.md&version=GBlive&_a=contents)
* Product: **devops**
* Git Login: **samgu**
* Microsoft Alias: **samgu**

**Comment by KathrynEE** [comment]
@anipind - Can you make this correction?
