### ISSUE TITLE
Restricting set of build pipelines

### ISSUE THREAD

**Issue by fleed** [MicrosoftDocs/vsts-docs#3605]
Is it possible to restrict the set of build pipelines? Specific pipelines or, even better, specific folders?
From the documentation it seems that it is "all or nothing". Is that the only possibility?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ebb7276b-e7ab-8d3f-f89c-4f5130808f61
* Version Independent ID: f11655e2-14f9-7755-dffa-61b21db1be67
* Content: [Set build and release permissions - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/policies/set-permissions?view=azure-devops)
* Content Source: [docs/pipelines/policies/set-permissions.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/policies/set-permissions.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by andyjlewis** [comment]
Thank you for the feedback. Yes, it is possible to restrict permissions. You can get some details by changing the version of this page to TFS 2018. You might need to interpret the info you see if you are using Azure DevOps Server 2019 or Azure Pipelines. More details are also available here: https://docs.microsoft.com/azure/devops/pipelines/policies/permissions.

I think we might need to better integrate these details, so I've added a story to our backlog. Heads up to @steved0x and @vijayma .
