### ISSUE TITLE
IntelliJ link is broken 404

### ISSUE THREAD

**Issue by daniel-farina** [MicrosoftDocs/vsts-docs#3609]
IntelliJ link is broken 404 under: 
https://docs.microsoft.com/en-us/azure/devops/user-guide/devops-alm-overview?view=azure-devops#git

The link it points to is:
https://docs.microsoft.com/java/download-intellij-plug-in.md

I believe the correct link should be:
https://plugins.jetbrains.com/plugin/7981-visual-studio-team-services

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5f412c4c-d759-6260-e59b-80923d6372df
* Version Independent ID: 94be3497-80cf-25ee-1741-bd9f49ca560e
* Content: [DevOps tools overview for Azure DevOps - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/user-guide/devops-alm-overview?view=azure-devops#git)
* Content Source: [docs/user-guide/devops-alm-overview.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/user-guide/devops-alm-overview.md)
* Product: **devops**
* GitHub Login: @steved0x
* Microsoft Alias: **kaelli**

**Comment by chcomley** [comment]
Thanks for the heads up, @daniel-farina! I've updated the link, which should be live by tomorrow morning. Thanks again!
