### ISSUE TITLE
When Analytics is General Avaiable (GA), this will not be free? Timeline for GA?

### ISSUE THREAD

**Issue by denhsu** [MicrosoftDocs/vsts-docs#3611]
Hi Azure DevOps Analytics team,

When analytics is GA, it will not free? Depends on the pricing, it might affect our decision to continue use it or not.

Also when will this be GA? any roadmap? 2019 Q4?

Any information is appreciated.

Thanks,
Dennis

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a92a6599-73d6-492c-71c7-12284e6d5a71
* Version Independent ID: 95fa37ba-7def-a618-f02d-50bbc9225a73
* Content: [Reporting roadmap - Azure DevOps & TFS](https://docs.microsoft.com/en-us/azure/devops/report/analytics/reporting-roadmap?view=azure-devops)
* Content Source: [docs/report/analytics/reporting-roadmap.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/report/analytics/reporting-roadmap.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by angurusw** [comment]
Hi Dennis, Analytics is now GA for Azure DevOps Services. For more details, please refer to this blog post: https://devblogs.microsoft.com/devops/analytics-for-azure-devops-services-is-now-generally-available/. Let me know if you have more questions. Thanks!
