### ISSUE TITLE
Several variable descriptions have bad [!INCLUDE] references

### ISSUE THREAD

**Issue by DrEsteban** [MicrosoftDocs/vsts-docs#3612]
For example, `System.DefaultWorkingDirectory`, `Build.StagingDirectory`, `System.AccessToken`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ffebdc8-521c-44b5-cde4-4abdc1bd6f18
* Version Independent ID: dc0effda-6d93-62aa-64c5-4e6f283b0826
* Content: [Predefined build variables - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml#feedback)
* Content Source: [docs/pipelines/build/variables.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/build/variables.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by thomps23** [comment]
@steved0x This looks to have been addressed, either as a part of a larger update or in response to this issue- could you confirm?

**Comment by andyjlewis** [comment]
Sync with @vtbassmatt who has been making fixes in this area this morning

**Comment by vtbassmatt** [comment]
Must have been fixed incidentally. I didn't consciously do anything here, but a spot check of all versions for `System.DefaultWorkingDirectory` shows no sign of the issue.
