### ISSUE TITLE
Incorrect queue name for Windows 2019 agents

### ISSUE THREAD

**Issue by gregpakes** [MicrosoftDocs/vsts-docs#3615]
The queue name for the 2019 agent in the documentation says:

**Hosted Windows 2019 with VS 2019**

It is supposed to be:

**Hosted Windows 2019 with VS2019**

Builds will not queue otherwise.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 99af681d-41ad-da15-0b72-08b5cd5a11ac
* Version Independent ID: 2fa0df36-a437-8cbb-b019-b49b31b1e116
* Content: [Microsoft-hosted agents for Azure Pipelines - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml#feedback)
* Content Source: [docs/pipelines/agents/hosted.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/agents/hosted.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by thejoebourneidentity** [comment]
This was resolved with #5028
