### ISSUE TITLE
No way to copy/duplicate a user story with all its child tasks

### ISSUE THREAD

**Issue by esunilkumare** [MicrosoftDocs/vsts-docs#3619]
Now it is not possible to copy/duplicate an existing user story with all its child tasks. This should be possible to avoid time delays in creating stories/tasks with similar attributes

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aa195a89-e867-a1a2-b217-7897eaf658cc
* Version Independent ID: dbca0b38-fbd2-0e97-5494-b7303b4b3f4b
* Content: [Copy or clone user stories, issues, bugs, tasks, or other work items - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/backlogs/copy-clone-work-items?view=azure-devops&tabs=browser#feedback)
* Content Source: [docs/boards/backlogs/copy-clone-work-items.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/boards/backlogs/copy-clone-work-items.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@esunilkumare - Thank you for your inquiry. You can suggest a feature through our [Developer Community page](https://developercommunity.visualstudio.com/spaces/21/index.html).  Please note that you may find a solution in the Marketplace extensions, specifically see [Work item form one click actions](https://marketplace.visualstudio.com/items?itemName=mohitbagra.witoneclickactions). Another method is to use Excel Tree Query to add linked items quickly.

**Comment by sarinhah1** [comment]
Same here

**Comment by xPryds** [comment]
Same here

**Comment by DanielHolth** [comment]
This is a fundamental feature for all super users. Please prioritize.

**Comment by uniquelau** [comment]
This is still a major frustration for the team here, especially when creating new projects.
