### ISSUE TITLE
This and the linked "User Accounts" page are missing information about what to put on the Reporting dialog...

### ISSUE THREAD

**Issue by StingyJack** [MicrosoftDocs/vsts-docs#362]
... for the user accounts on both the Analysis Services and Reports tabs. 

Does it want SQL users? or windows accounts? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bbab5d1b-3e12-5550-5d15-7087676b4165
* Version Independent ID: f9d4e569-17c8-aa5d-170f-7dc855c28fd6
* Content: [Rebuild the data warehouse and cube](https://docs.microsoft.com/en-us/vsts/report/admin/rebuild-data-warehouse-and-cube#2-rebuild-the-data-warehouse-and-restart-services)
* Content Source: [docs/report/admin/rebuild-data-warehouse-and-cube.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/report/admin/rebuild-data-warehouse-and-cube.md)
* Service: **unspecified**
* GitHub Login: @douge
* Microsoft Alias: **kaelli**

**Comment by StingyJack** [comment]
I mean this dialog
![image](https://user-images.githubusercontent.com/15381181/37632672-c77a2e1e-2bc5-11e8-80e2-f79d0db30172.png)

**Comment by KathrynEE** [comment]
@StingyJack - Thank you for your inquiry and apologies for the delay in responding. The account you use is the Report Reader account which is described in here: [Requirements, Accounts](https://docs.microsoft.com/en-us/vsts/tfs-server/requirements?view=vsts#accounts).
