### ISSUE TITLE
Sample missing

### ISSUE THREAD

**Issue by trailmax** [MicrosoftDocs/vsts-docs#3622]
It would be great to see a sample PS script. Stuff like passing variables would be great!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fb215324-b1a0-93b5-5022-4bcc7da93bb7
* Version Independent ID: 9eb2977b-ac34-9d53-670e-04fa027bc8e4
* Content: [Azure PowerShell task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-powershell?view=azure-devops#open-source)
* Content Source: [docs/pipelines/tasks/deploy/azure-powershell.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/deploy/azure-powershell.md)
* Product: **devops**
* GitHub Login: @steved0x
* Microsoft Alias: **dastahel**

**Comment by lukebailey** [comment]
+1

**Comment by psblah** [comment]
Still no example?
