### ISSUE TITLE
TOC Doesn't work in Markdown Preview

### ISSUE THREAD

**Issue by mchelen** [MicrosoftDocs/vsts-docs#3625]
Table of Contents does not function when previewing a Markdown file, as reported by: https://developercommunity.visualstudio.com/content/problem/411901/-toc-doesnt-work-in-azure-devops-preview-page-for.html

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fa622358-f5bb-1f5c-177a-081a37b6acef
* Version Independent ID: 72f7fd16-a822-66c8-3a34-8905645ce5f2
* Content: [Markdown syntax for files, widgets, and wikis in Azure DevOps - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/project/wiki/markdown-guidance?view=azure-devops)
* Content Source: [docs/project/wiki/markdown-guidance.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/project/wiki/markdown-guidance.md)
* Product: **devops**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @mchelen, thanks for reaching out. I've engaged our PM, so please stay tuned. Thanks!

**Comment by chcomley** [comment]
Hi @mchelen, Good news! Per our PM, we are in the process of fixing this bug! Please let me know whether you have any other questions. Have a fantastic weekend.

**Comment by mchelen** [comment]
@chcomley Great to hear, thanks you too!

**Comment by lennybacon** [comment]
Any updates on this?

**Comment by chcomley** [comment]
Hi @lennybacon and @mchelen, this fix should be deployed by the end of this week! Thanks.
