### ISSUE TITLE
Process (Object-level) misspelling 

### ISSUE THREAD

**Issue by RiadKatby** [MicrosoftDocs/vsts-docs#3627]
on following section 
https://docs.microsoft.com/en-us/azure/devops/organizations/security/permissions?view=azure-devops#process-object-level

Project Collection Administrators are granted all permissions to create, edit, and manage process (NOT plans). Valid users are granted View (read-only) permissions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 68686c2b-c69a-d9e4-3e21-a46d231b649c
* Version Independent ID: 049659da-1772-3166-f909-4feeb8a97730
* Content: [What are all the default permissions and groups? - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/security/permissions?view=azure-devops#feedback)
* Content Source: [docs/organizations/security/permissions.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/security/permissions.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@RiadKatby - Thank you for the correction. The article will get updated soon.
