### ISSUE TITLE
IP address/range-only allowed behind firewall

### ISSUE THREAD

**Issue by 24mu13** [MicrosoftDocs/vsts-docs#3628]
In our CD scenario for production, the customer allows us to define rules only by *IP addresses* or *ranges*. Is it possible to have a list of IPs to provide them instead of URIs?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43799c5d-2f13-cc76-a1c0-a3f850e16d4e
* Version Independent ID: 97a5b73f-faf7-f9c0-9269-fc79984616d6
* Content: [Deploy a build and release agent on Windows - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/v2-windows?view=azure-devops#feedback)
* Content Source: [docs/pipelines/agents/v2-windows.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/agents/v2-windows.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by pricoppd** [comment]
Hi @thomps23 have you managed to get the list of IP addresses?

**Comment by thomps23** [comment]
@pricoppd Unfortunately I am only assisting with initial triage of issues and not in a position to provide that information.

**Comment by steved0x** [comment]
@24mu13 Do you mean the URLs listed in one of these sections:

* [I'm running a firewall and my code is in Azure Repos. What URLs does the agent need to communicate with?](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/v2-windows?view=azure-devops#im-running-a-firewall-and-my-code-is-in-azure-repos-what-urls-does-the-agent-need-to-communicate-with)
* [How do I configure the agent to bypass a web proxy and connect to Azure Pipelines?](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/v2-windows?view=azure-devops#how-do-i-configure-the-agent-to-bypass-a-web-proxy-and-connect-to-azure-pipelines)

I don't know if these are published anywhere, similar to the way the [Azure Azure Datacenter IP Ranges](https://www.microsoft.com/en-us/download/details.aspx?id=41653) are published but even if they were it would be unlikely that it would include the `https://{organization_name}.visualstudio.com` ones or the ones like `https://*.dev.azure.com`

Let me know which section maps to the IP ranges you're trying to use and I'll see if I can get more information. It may be that you may have to periodically lookup the IP addresses and cache them and use that list in your Pipeline.

**Comment by justhchung** [comment]
Thank you for your feedback. 

We are closing this issue and directing you to seek an answer through our support web site: [Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html).
