### ISSUE TITLE
Package Migration Documentation

### ISSUE THREAD

**Issue by jrummell** [MicrosoftDocs/vsts-docs#3629]
It would be great if the documentation included steps to migrate another private feed, such as myget, to an Azure DevOps feed. We have a few dozen packages with many versions that need to be migrated (about 1000 .nupkg files total), and pushing them from the command line one at a time is going to be tedious.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a10a409-5468-9532-f0dc-5a28cdd566d8
* Version Independent ID: 2ef20266-bc45-448b-27f5-e5c3bffed2ef
* Content: [Get started with NuGet packages in Azure DevOps Services and TFS](https://docs.microsoft.com/en-us/azure/devops/artifacts/get-started-nuget?view=azure-devops#automate-the-process-with-continuous-integration)
* Content Source: [docs/artifacts/get-started-nuget.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/artifacts/get-started-nuget.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by jrummell** [comment]
Turns out this isn't too bad. Assuming you downloaded the NuGet+Credential Provider for the command line, you can push a local folder of nuget packages fairly easily:

```
nuget.exe sources Add -Name "AzureDevOpsFeed" -Source "https://account.pkgs.visualstudio.com/_packaging/AzureDevOpsFeed/nuget/v3/index.json"

.\CredentialProviderBundle\NuGet.exe push -Source "AzureDevOpsFeed" -ApiKey AzureDevOps .\old-feed-packages\*.nupkg
```

**Comment by elbatk** [comment]
Hey @jrummell , glad it turned out to be easy-ish for you :) I'm adding this type of documentation to my list of potential improvements to the Azure Artifacts docs.

**Comment by jrummell** [comment]
Thanks!

> Hey @jrummell , glad it turned out to be easy-ish for you :) I'm adding this type of documentation to my list of potential improvements to the Azure Artifacts docs.

**Comment by elbatk** [comment]
Closing this as it's on my tracker :)
