### ISSUE TITLE
"SonarQube Endpoint" not showed in the maven task (maybe add a troubleshootting section in documentation)

### ISSUE THREAD

**Issue by carloreggiani** [MicrosoftDocs/vsts-docs#363]
Checkin the "Run SonarQube Analysis" checkbox, no way to have showed the "SonarQube Endpoint" configured and correctly showed in the same text box in the task "Sonarqube preparation".
I have the same problem in 2017.2 anche 2018.... any suggestion?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1a639e3a-376a-2ce9-529b-5504286daa12
* Version Independent ID: 870922d8-ab89-9ef2-7912-3910815ef778
* Content: [Configuring SonarQube for VSTS for a Java project](https://docs.microsoft.com/en-us/vsts/java/labs/sonarqube/#modify-the-build-to-integrate-with-sonarqube)
* Content Source: [docs/java/labs/sonarqube/index.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/java/labs/sonarqube/index.md)
* Service: **unspecified**
* GitHub Login: @douge
* Microsoft Alias: **douge**

**Comment by erickson-doug** [comment]
I've forwarded this to the product team for an update and response. Thank you for the feedback!

**Comment by DavidStaheli** [comment]
Hi @carloreggiani.  I apologize that you've received no response until now.  If you are still interested, I recommend that you install the SonarQube extension [from the marketplace](https://marketplace.visualstudio.com/items?itemName=SonarSource.sonarqube).  At that same page, you will find details from SonarSource about how to configure a build with SonarQube.  Please reopen this issue if we can provide additional help.
