### ISSUE TITLE
Documentation is total garbage

### ISSUE THREAD

**Issue by Izzmo** [MicrosoftDocs/vsts-docs#3630]
Can someone from Microsoft please go in and make this up to date? Half of these input properties don't even work for the commands. You need to go in and specify which ones work with what. Sorry, I would do this, but I don't have the time or get paid to maintain dotnet… please and thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d227a6f2-a94b-1c05-57e4-b63d42e2b9e5
* Version Independent ID: d063e189-d0fd-4ca3-c108-a0bd2ae49d22
* Content: [.NET Core CLI task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/dotnet-core-cli?view=azure-devops)
* Content Source: [docs/pipelines/tasks/build/dotnet-core-cli.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/build/dotnet-core-cli.md)
* Product: **devops**
* GitHub Login: @steved0x
* Microsoft Alias: **dastahel**

**Comment by chasewilson** [comment]
@Izzmo Thanks for the feedback. I've just done a major overhaul to hopefully make this  a little more clear and up to date. I'll be closing this issue but if you have any more feedback, I hope you will open a new issue!

**Comment by Izzmo** [comment]
@chasewilson the added content is nice, but the original problem still exists: not all the input options apply to every single command, so it's confusing as to what you need for what. We either need to explicitly state out what inputs are used for what command (via a mapping table) or simple list examples for each command type.
