### ISSUE TITLE
Arguments ignored when type is inline.

### ISSUE THREAD

**Issue by iricigor** [MicrosoftDocs/vsts-docs#3631]
I do not understand the sentence "arguments are ignored when the type is inline."

Can you please explain how can I run inline PowerShell script with arguments, for example, something like this? 

param ($Name) 
"Hello $Name"

This functionality was present in v1, and it is required feature for "Task Group" functionality, but it is missing now. I cannot go back to v1, due to its limitations.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a0e444c2-69c6-4d71-6fd0-94d0f4097d3a
* Version Independent ID: 3a727833-1cc3-c2fb-c5b3-22605eee2721
* Content: [PowerShell task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/powershell?view=azure-devops)
* Content Source: [docs/pipelines/tasks/utility/powershell.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/utility/powershell.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by CoolDadTx** [comment]
I'm interested in this as well. Using inline tasks with task groups doesn't behave properly without it. To reference an "argument" in the script you have to use the `$(Arg)` syntax. But if this is a string you have to then enclose it in single or double quotes. But if the argument value contains single or double quotes then that messes up the script. See [here](https://stackoverflow.com/questions/49447813/vsts-task-group-powershell-parameter?noredirect=1&lq=1). There doesn't seem to be any way to pass parameters from a task group to a PowerShell inline script AND allow the parameter to contain single/double quotes unless you manually try to enforce some rules. Having inline accept script arguments would solve this I believe.

**Comment by vtbassmatt** [comment]
Inline scripts aren't reusable, so it doesn't make a lot of sense for them to be written to take parameters. We expect that an inline script takes direct dependencies on anything it needs, such as environment variables.

I don't understand this:

> There doesn't seem to be any way to pass parameters from a task group to a PowerShell inline script

**Comment by PainElemental** [comment]
@vtbassmatt: We use inline scripts as part of Task groups. They can be reused by many different build definitions and that's why we need the parameters!
For now I cannot use the powershell 2.x task, but have to use the 1.x version.

**Comment by vtbassmatt** [comment]
I'm tweaking the docs slightly, and I've reactivated a bug in the agent repo to consider making `arguments` work with inline scripts. It's a product issue, not a doc issue, so I'll be closing this one.
