### ISSUE TITLE
Use work around with caution

### ISSUE THREAD

**Issue by kirkone** [MicrosoftDocs/vsts-docs#3634]
Hi,

There is a problem with the suggested walk around. You can not create a new feed with the same name immediately after deleting a feed.
This bit of information is not provided bevor you delete the feed. This behavior can cause some trouble.

Maybe it is a good Idea to add this information here.

Thank you,
KirK

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1475397e-1e4f-e51d-8cd8-29553112a059
* Version Independent ID: 4a8053f8-1ca5-a2aa-89ac-bbe0b2a6128f
* Content: [Key concepts for Azure Artifacts](https://docs.microsoft.com/en-us/azure/devops/artifacts/artifacts-key-concepts?view=azure-devops&viewFallbackFrom=vsts#feedback)
* Content Source: [docs/artifacts/artifacts-key-concepts.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/artifacts/artifacts-key-concepts.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by chcomley** [comment]
Hi @kirkone, thanks for the heads up. I've created a user story for my backlog to address this. Thanks for reaching out!

**Comment by nkdavis63** [comment]
I have also just ran into this problem do to missing documentation or broken functionality. this may need an open a bug report on this

**Comment by elbatk** [comment]
We will get the documentation updated with that warning - I hate to give you the whole "it's not a bug, it's a feature", but we purposely hang on to deleted feeds for bit.

**Comment by chasewilson** [comment]
@kirkone Thank you for the feedback! I've update the doc to not the delay for recreating feeds. You should see it within the next 24 hours. Feel free to reach out or create a new issue for any more feedback :)
