### ISSUE TITLE
Issue Tracking

### ISSUE THREAD

**Issue by davidnarciso** [MicrosoftDocs/vsts-docs#3636]
How are we supposed to track issues using the built-in WIT? I understand that I could set up a query and share it with my team, but that seems like a lot of work - and that workflow works against resolving issues. They seem hidden instead of showing and previewing issues as items to eventually resolve or to eventually translate into Features, User Stories, or Tasks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2b6067a-50a8-dc02-fc43-8f55527b507c
* Version Independent ID: 3287e2ac-ef6d-3f52-47f4-1b337cfc077f
* Content: [Customize backlogs and boards - Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/organizations/settings/work/customize-process-backlogs-boards?view=azure-devops#feedback)
* Content Source: [docs/organizations/settings/work/customize-process-backlogs-boards.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/settings/work/customize-process-backlogs-boards.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@davidnarciso - Thank you for your inquiry. For Azure DevOps Services - you can add a new work item type - say Issues 2 - to the Requirements Backlog. You would then Change the type of your Issues to Issues 2 (you can bulk update these). Issues 2 will now show up on your Kanban board and Backlog at the same level as user stories.  There is no way at this time to add the default Issues work item type to the Requirement Backlog for an Inherited Process.  If you'd like to see this feature out of the box, please [suggest it as a feature](https://developercommunity.visualstudio.com/spaces/21/index.html).
