### ISSUE TITLE
Syncing fork back original repository doesn't work

### ISSUE THREAD

**Issue by BrianMinister** [MicrosoftDocs/vsts-docs#364]
[this](https://docs.microsoft.com/en-us/vsts/git/concepts/forks#sync-your-fork-to-latest ) refers to being able to have a dropdown on the fetch button, but I don't have that, and I am on VS version 15.6.3. So where is this feature?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 240f15e3-daf9-78f8-7423-cc17490ee401
* Version Independent ID: 3f1934d0-75c4-56b3-32d5-676b7fbe70b7
* Content: [Fork your repository in VSTS or TFS](https://docs.microsoft.com/en-us/vsts/git/concepts/forks#sync-your-fork-to-latest)
* Content Source: [docs/git/concepts/forks.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/git/concepts/forks.md)
* Service: **unspecified**
* GitHub Login: @douge
* Microsoft Alias: **macoope**

**Comment by hemantkd** [comment]
Hi @BrianMinister, I can see the dropdown fine. Have you followed the step 3 from [Clone Your Fork Locally](https://docs.microsoft.com/en-us/vsts/git/concepts/forks?view=vsts#clone-your-fork-locally)?

**Comment by BrianMinister** [comment]
I did. I always work on local copies of forks. A habit from working with Github. 🙂

I ended up backing up everything locally. Blowing away all repositories in VSTS and Local.
Then rebuild from backup.

**Comment by steved0x** [comment]
@BrianMinister If this issue happens again, please open up a new issue and let us know. Sorry for the trouble and I'm glad you got it working.
