### ISSUE TITLE
Azure AD connect error

### ISSUE THREAD

**Issue by arseniog2** [MicrosoftDocs/vsts-docs#3642]
After following all the steps, and trying the connect my Azure AD I get the following error:

User: arsenioguzman@outlook.com is not allowed to link organization: tekhsoft to AAD tenant: tekhsoft.com. Only active members of the AAD tenant are allowed to perform the link.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 031380a0-4f04-4105-199a-81715b42c653
* Version Independent ID: 570b2795-90ad-32b4-7ad0-1fceb186ffa3
* Content: [Connect organization to Azure Active Directory - Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/connect-organization-to-azure-ad?view=azure-devops#feedback)
* Content Source: [docs/organizations/accounts/connect-organization-to-azure-ad.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/accounts/connect-organization-to-azure-ad.md)
* Product: **devops**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @arseniog2, thanks for reaching out. I've in turn reached out to my PMs for some clarity on this and will get back to you as soon as possible!

**Comment by chcomley** [comment]
Hi @arseniog2, we recommend that you contact an Azure DevOps organization administrator, who is an active MEMBER of the Azure AD, to perform the connection. Please let us know if you have any further questions.

**Comment by arseniog2** [comment]
But that's the problem, what active MEMBER means for you?.

My case is that the Azure DevOps was create with an Microsoft account that has the same domain as my Office 365 subscription.

Now, I can't add more users in Azure DevOps because they can create a Microsoft Account and I can't connect to Azure AD

**Comment by andresgallo36** [comment]
@arseniog2 - We were able to identify the source of the issue you're facing right now: when a user tries to connect the Azure DevOps organization to an Azure AD tenant that has a custom domain, and the user is doing this from inside the organization (Organization settings\Azure Active Directory\Connect directory), the operation will fail with the error message "Only active members of the AAD tenant are allowed to perform the link". Users should not face this problem when connecting the same organization to the same tenant from the Azure Portal (you can review our previous version of this document for details on this process [here](https://github.com/MicrosoftDocs/vsts-docs/blob/1b0753ae8c049a7a874a2413b2c74d5217647390/docs/organizations/accounts/connect-organization-to-azure-ad.md)), or if you prefer, I can perform this operation for you from our back-end tools too.

**Comment by arseniog2** [comment]
Thanks Andres,

I could perform the operation with the document guidance and connect to Azure AD.

**Comment by chcomley** [comment]
That's awesome! Thanks for letting us know @arseniog2.

**Comment by mdvdhurk** [comment]
``` Our product team is working to fix this issue, but in the meantime users should not face this problem when connecting the same organization to the same tenant from the Azure Portal (you can review our previous version of this document for details on this process [here](https://github.com/MicrosoftDocs/vsts-docs/blob/1b0753ae8c049a7a874a2413b2c74d5217647390/docs/organizations/accounts/connect-organization-to-azure-ad.md)), or if you prefer, we can perform this operation for you from our back-end tools too.```
Hi! I am trying to connect our Azure DevOps to our AAD (with custom domain) and I am facing the same error message. Could you please let me know how to get in touch with the team to let the connection be performed by your back-end tools? Thanks!
