### ISSUE TITLE
Features available across products

### ISSUE THREAD

**Issue by garudatwo** [MicrosoftDocs/vsts-docs#3646]
Good article - just wanted to say that, since the article is tagged with multiple Azure and TFS products, it would be helpful to note if a Markdown feature isn't supported in one of the products (e.g. TOC doesn't work in TFS).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fa622358-f5bb-1f5c-177a-081a37b6acef
* Version Independent ID: 72f7fd16-a822-66c8-3a34-8905645ce5f2
* Content: [Markdown syntax for files, widgets, and wikis in Azure DevOps - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/project/wiki/markdown-guidance?view=azure-devops#feedback)
* Content Source: [docs/project/wiki/markdown-guidance.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/project/wiki/markdown-guidance.md)
* Product: **devops**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Thanks for the feedback, @garudatwo, we appreciate it. I've created a user story on my backlog to address this. Thanks again.

**Comment by chcomley** [comment]
Hi @garudatwo, the TOC is available for Azure DevOps Server 2019 (what TFS 2019 is now called). If you update to the latest version, you should be able to use the TOC. Please let me know whether you have any further questions or feedback. Thanks and enjoy your weekend!

**Comment by garudatwo** [comment]
Wonderful, thanks for the tip!
