### ISSUE TITLE
Wiki Markdown Content In Widget

### ISSUE THREAD

**Issue by sheldonhull** [MicrosoftDocs/vsts-docs#3648]
If I create a normal github repo with markdown, I can leverage the content to populate the widget with the contents of the markdown file. 

If I use the wiki, I'm unable to see this in the repository list to link to content, and instead can only link to the wiki page. Is there any acceptable way to link to the _content_ of the wiki in the markdown widget, not just the file itself?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b21c46ee-e19c-9dc4-11c2-8749c6576925
* Version Independent ID: 09ad6f7f-5169-f1b5-4f71-410bd85c62df
* Content: [Add markdown content to a team dashboard - Azure DevOps & TFS](https://docs.microsoft.com/en-us/azure/devops/report/dashboards/add-markdown-to-dashboard?view=azure-devops#feedback)
* Content Source: [docs/report/dashboards/add-markdown-to-dashboard.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/report/dashboards/add-markdown-to-dashboard.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@sheldonhull  - I don't believe there is a way to do this. Adding @adramasu to see if he has any additional information. You might consider suggesting this feature be supported via our [Suggest a feature page](https://developercommunity.visualstudio.com/spaces/21/index.html).

**Comment by adramasu** [comment]
Hi @sheldonhull, we don't have this currently. You may want to upvote [this suggestion ticket](https://developercommunity.visualstudio.com/content/idea/447215/ability-to-add-a-wiki-page-to-a-dashboard.html) which is for the exact ask.
