### ISSUE TITLE
Interesting but unavailable

### ISSUE THREAD

**Issue by GeoffreyDelmee** [MicrosoftDocs/vsts-docs#365]
This feature seems really interesting and a time saver to manage VSTS.
But, even the documentation is from one month ago, I can't see the feature in my VSTS environment.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c9fa6b17-595a-05e9-e95d-b5c290127abb
* Version Independent ID: 62524794-e27b-f9a2-7e80-cc1c3585706c
* Content: [Assign access levels and extensions to users by group membership](https://docs.microsoft.com/en-us/vsts/accounts/assign-access-levels-and-extensions-by-group-membership)
* Content Source: [docs/accounts/assign-access-levels-and-extensions-by-group-membership.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/accounts/assign-access-levels-and-extensions-by-group-membership.md)
* Service: **unspecified**
* GitHub Login: @douge
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
@GeoffreyDelmee Thank you for your comment! I've updated the doc accordingly, by adding a note about how the feature is still rolling out and you can expect to see it available within the next 3 weeks (as of today, 3/20).
