### ISSUE TITLE
Capacity for Testing?

### ISSUE THREAD

**Issue by pabrams** [MicrosoftDocs/vsts-docs#3653]
I can't find any guidance about how to track Capacity for Testing. Out of the box, we have a Discipline for testing, which we can select on a Task, but Task isn't used for testing; Test Case is, and that doesn't allow any links to tasks. Is the recommendation to create a duplicate Task for every Test Case, and link them only indirectly, via their links to requirement(s)?

https://docs.microsoft.com/en-us/azure/devops/boards/work-items/guidance/cmmi-process-workflow?view=azure-devops

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3898d7ea-7829-2ac2-33df-5e36155981a5
* Version Independent ID: 99b6a8b0-6783-7844-d16c-2e69f7958e47
* Content: [CMMI process work item types & workflow - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/work-items/guidance/cmmi-process-workflow?view=azure-devops)
* Content Source: [docs/boards/work-items/guidance/cmmi-process-workflow.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/boards/work-items/guidance/cmmi-process-workflow.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@pabrams  - Thank you for your question. The only work item types that are counted against Capacity are the Bug and Task types. So, if you want to track capacity for testing - you have to define a Task. You may want to [suggest a feature](https://developercommunity.visualstudio.com/spaces/21/index.html) to include Test Case in capacity planning.
