### ISSUE TITLE
Can we add two extensions to the same hub group?

### ISSUE THREAD

**Issue by PerthCharern** [MicrosoftDocs/vsts-docs#3656]
Can we add two extensions to the same hub group? If so, could you provide an example?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2e94149d-382d-3ae4-dc13-d9b233d695a9
* Version Independent ID: 444fe755-202c-7ecb-f43f-6f1c396f28d9
* Content: [Add a Hub Group](https://docs.microsoft.com/en-us/azure/devops/extend/develop/add-hub-group?view=azure-devops)
* Content Source: [docs/extend/develop/add-hub-group.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/extend/develop/add-hub-group.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by chcomley** [comment]
Hi @PerthCharern, thanks for reaching out. You can have as many hub contributions as you like to target the same hub group, just give them different IDs. See the following hub contribution sample: 
{
        "id": "Fabrikam.HelloWorld",
        "type": "ms.vss-web.hub",
        "description": "Adds a 'Hello' hub to the Work hub group.",
        "targets": [
            ".sample-hub-group"
        ],
        "properties": {
            "name": "Hello",
            "order": 99,
            "uri": "hello-world.html"
        }
    }

So I can add another of these that targets the same hubgroup:
{
        "id": "Fabrikam.HelloWorld2",
        "type": "ms.vss-web.hub",
        "description": "Adds a second 'Hello' hub to the Work hub group.",
        "targets": [
            ".sample-hub-group"
        ],
        "properties": {
            "name": "Hello2",
            "order": 99,
            "uri": "hello-world.html"
        }
    }
Please let me know if you have any further questions, or whether I can close this issue. Thanks for your time!

**Comment by PerthCharern** [comment]
Thanks @chcomley 

Should this work with contributions from *different* extensions? I tried that and it didn't work - the second extension doesn't seem to be able to find the hub group created by the first extension. I can give it another try.

**Comment by chcomley** [comment]
@PerthCharern, Following up on this - since we haven't heard from you, I'm assuming you gave it another try and it worked? Can you please confirm whether you still need help? I'll be closing this issue, otherwise. Thanks very much.
