### ISSUE TITLE
Typo in Windows image name

### ISSUE THREAD

**Issue by hosszubalazs** [MicrosoftDocs/vsts-docs#3657]
"Use the Windows agents (win2016-vs2017 image" 
That vm name is incorrect. It should be the other way around : vs2017-win2016 .
Based on:
- other parts of the page
- https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e825c07d-2168-c0aa-782a-ef6f9c7ba95e
* Version Independent ID: 5cb6926b-215a-bf89-8e63-b2e1129e41df
* Content: [Build, test, and push Docker container apps - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/languages/docker?view=azure-devops&tabs=yaml#feedback)
* Content Source: [docs/pipelines/languages/docker.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/languages/docker.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by hosszubalazs** [comment]
Probably that parts needs a more general update too.
windows-2019 and win1803 are also capable of running containers.

The Docker task documentation suggests that the win2016 image is needed, which is not true anymore if I understand correctly.

Thanks for looking into this and cheers!

**Comment by vijayma** [comment]
Fixed through the above PR.
