### ISSUE TITLE
Wrong IP Address given in documentation 

### ISSUE THREAD

**Issue by vishnuvg1984** [MicrosoftDocs/vsts-docs#3658]
Background of Issue: We are using Azure Devops Pipeline to deploy a series of files using Powershell Remote. For that we created a new Azure Windows VM , opened the inbound firewall rule : port 5986 for enable Powershell Remote and was able to connect successfully from Azure Devops Pipeline and successfully deployed.

However there is a requirement we on-premise VM, instead of using Azure VM. Our company has requirement to open only specific IP inbound rules, so to find the exact ip's from azure devops pipelines,  we came across this documentation.  Our Azure Devops region is West Europe, so according to this document the West Europe Pipelines IP is as given below

Releases service - West Europe	13.95.223.69, 104.45.64.13

We opened a firewall for that ip and connected the powershell from Devops pipeline to our VM and found failed. When we netstat the earlier Azure VM we created we could see a different set o fIP from Azure Piplines which was accessing the VM . These were the IP's we found while net stat from Azure VM. 

52.166.58.206:1987,52.166.58.206:1988,52.166.58.206:1989,52.166.58.206:1990.

Issue 

The IP given in documentation for West Europe is entirely wrong. The actual IP we saw while using netstat in VM is 52.166.58.206

Kindly give more clarity on this. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a35b397-3fe8-122e-042e-280326f88a38
* Version Independent ID: 3e0f0afc-abeb-01be-d767-813cd6ad78db
* Content: [Migration import from TFS to Azure DevOps Services - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/articles/migration-import?view=azure-devops#feedback)
* Content Source: [docs/articles/migration-import.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/articles/migration-import.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by chcomley** [comment]
Thanks for reaching out, @vishnuvg1984. I've created a user story for my backlog to address this and will follow up with you. Thanks again!

**Comment by roofers** [comment]
@vishnuvg1984 - The IP addresses on the page that you discovered are meant for the data migration tool for Azure DevOps only. They cover a small segment slice of the total product space that participate in bringing customer's data in from Azure DevOps Server (on-prem) to Azure DevOps (hosted). While we try to keep the IP addresses up to date, we sometimes fall behind. Therefore, our client tool has a catch to provide a missing IP address if any of them changes. 

I recommend downloading the agent IP list on the following page: https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml

They cover the scenario that you're looking handle.

**Comment by chcomley** [comment]
@vishnuvg1984, based on the information provided by @roofers, I'll be closing this issue. However, please do respond if you have any further questions. Thank you and have a great day!
