### ISSUE TITLE
kıhık

### ISSUE THREAD

**Issue by adememir** [MicrosoftDocs/vsts-docs#366]
jljk

---
#### Belge Ayrıntıları

⚠ *Bu bölümü düzenlemeyin. docs.microsoft.com ➟ GitHub sorunu bağlantısı için gereklidir.*

* ID: dbfd7c2a-8a23-3a15-2888-4170352eb260
* Version Independent ID: e1c83f61-657d-4ec3-aaff-54d736a7c1c2
* Content: [VSTS Git tutorial](https://docs.microsoft.com/tr-tr/vsts/git/tutorial/gitworkflow#next-steps)
* Content Source: [docs/git/tutorial/gitworkflow.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/git/tutorial/gitworkflow.md)
* Service: **unspecified**
* GitHub Login: @douge
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
@adememir I'm closing this issue because it looks like the comments were truncated, please reopen it if you can provide more details. Thank you for your feedback.
