### ISSUE TITLE
How to allow external users to Azure Devops to have access to manage the backlog and sprints

### ISSUE THREAD

**Issue by jeevaeastpoint** [MicrosoftDocs/vsts-docs#3660]
Thank you for your feedback!

The issues in this repo are for documentation feedback.

If you are submitting your documentation feedback issue directly through GitHub, please provide the URL of the article so we can route the feedback to the correct author.

Please report Azure DevOps or TFS software bugs, feedback, or questions in the [Azure DevOps Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html).

**Comment by KathrynEE** [comment]
@jeevaeastpoint - thank you for your inquiry. I understand "external users" to mean users that are outside of your organization. Are you on Azure DevOps Services or an on-premises Azure DevOps Server or TFS? 
For users to access backlogs and sprints, they must be added to an Azure DevOps security group and an Access Level. Stakeholder Access is limited in managing backlogs and sprints - so you would have to give them Basic access.  The other way to go is to create a Public Project in Azure DevOps Services and open the project up. You can learn more from the following resources: 
- [About access levels](https://docs.microsoft.com/en-us/azure/devops/organizations/security/access-levels?view=azure-devops&tabs=stakeholder)
- [Default permission and access](https://docs.microsoft.com/en-us/azure/devops/organizations/security/permissions-access?view=azure-devops)
