### ISSUE TITLE
Incompletely described for inline script

### ISSUE THREAD

**Issue by Miles-Davies-HORIBA** [MicrosoftDocs/vsts-docs#3661]
There is no clear description about version 1 vs 2. For version 2 it is unclear how to access predefined variables within the script. The example script cannot be saved as it needs attention but there is no clear reason given as to why? This seems only partially documented and assumes the powershell is in file not inline. Some clear examples of use in all 4 possible cases would be helpful

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a0e444c2-69c6-4d71-6fd0-94d0f4097d3a
* Version Independent ID: 3a727833-1cc3-c2fb-c5b3-22605eee2721
* Content: [PowerShell task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/powershell?view=azure-devops)
* Content Source: [docs/pipelines/tasks/utility/powershell.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/utility/powershell.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by iainxt** [comment]
In case it helps others I eventually got a working example for my requirement of putting the build number into a property file using powershell.

steps:
  - task: PowerShell@2
    inputs:
      targetType: inline
      script: ((Get-Content -path .env.production -Raw) -replace 'REPLACE_BUILD_NUMBER','$(Build.BuildNumber)') | Set-Content -Path .env.production

**Comment by andyjlewis** [comment]
@Miles-Davies-HORIBA  and @iainxt , thanks for the feedback and suggestion. I've attached this issue to one of our backlog items.
