### ISSUE TITLE
More info about required permissions for Slack bot

### ISSUE THREAD

**Issue by jlucktay** [MicrosoftDocs/vsts-docs#3663]
I was having trouble setting up the [Azure Pipelines Slack bot](https://docs.microsoft.com/azure/devops/pipelines/integrations/slack) and contacted Microsoft about it.

Their response stated the following:

> You need to be an admin of the Project containing the pipelines to set up the subscriptions.

It would be great if this piece of information could be added to the documentation page linked above.

Thanks!

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 99a6f5aa-7e92-a028-d13e-e1e4b7fede86
* Version Independent ID: be7e5d7c-0033-6b72-4bd1-809f7d1894aa
* Content: [Azure Pipelines with Slack - Azure Pipelines](https://docs.microsoft.com/en-gb/azure/devops/pipelines/integrations/slack?view=azure-devops)
* Content Source: [docs/pipelines/integrations/slack.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/integrations/slack.md)
* Product: **devops**
* GitHub Login: @atinb
* Microsoft Alias: **atinb**

**Comment by RGKarthik** [comment]
Documentation is updated with relevant details. This is addressed

**Comment by jlucktay** [comment]
Thanks @RGKarthik !
