### ISSUE TITLE
YAML PR triggers

### ISSUE THREAD

**Issue by amirschw** [MicrosoftDocs/vsts-docs#3667]
Is this feature scheduled to be available in Azure Pipelines?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5673ec1-c7d1-e0ac-043a-8fc3d5b226a9
* Version Independent ID: b4872831-51c0-6cf8-1c56-de20beb38a80
* Content: [Build pipeline triggers - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/triggers?tabs=designer&view=azure-devops#feedback)
* Content Source: [docs/pipelines/build/triggers.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/build/triggers.md)
* Product: **devops**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by Starkie** [comment]
We have the same question regarding Azure Devops Server: Will this be available for repos hosted on Azure instead of GitHub?

**Comment by steved0x** [comment]
@amirschw @Starkie I apologize for the delay in replying. In Azure Repos Git, the PR trigger functionality is implemented using branch policies, as described [here](https://docs.microsoft.com/en-us/azure/devops/repos/git/branch-policies?view=azure-devops#build-validation). When configuring a build validation using this branch policy, you select a Pipeline, but only the build portion of that pipeline is used, and if the selected pipeline has any other triggers specified (CI or scheduled, or even PR) they won't be used in the scope of the build validation branch policy. In the case of branch policy build validation, the branch policy controls the trigger, and the pipeline controls the build.

There is an existing feature request to move the PR trigger functionality into YAML on Developer Communities that you can vote for, and add comments to provide more details.

https://developercommunity.visualstudio.com/idea/385329/pr-triggers-in-yaml-should-be-supported-on-azure-d.html
