### ISSUE TITLE
Difficult to understand how to use variables

### ISSUE THREAD

**Issue by cluetjen** [MicrosoftDocs/vsts-docs#3668]
It's quite difficult to understand how to use variables in yaml.

* What's the name to use as reference? In your screenshot the group is named "HO Website Configuration" but in the yaml example a group named "my-variable-group" is referenced. I guess I have to use the "name" value?
* How to access a variable from a group somewhere in my yaml? Will it be prefixed with the group name or just the variable name?

For me a sample "if you want to use variable named 'app-name' from group 'HO Website Configuration' in your yaml, do it like this…" would be very helpful. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4827aa99-ae62-bd63-6f2f-a87a4065ed27
* Version Independent ID: c9e461ee-7f42-3503-9460-18fa3a807bbb
* Content: [Variable groups for Azure Pipelines and TFS - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/library/variable-groups?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/library/variable-groups.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/library/variable-groups.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment]
To use a variable, simply reference it by name. It must be in the same scope as the pipeline (and the same stage if defined at stage level when linked to a pipeline). See https://docs.microsoft.com/azure/devops/pipelines/release/variables#custom-variables. Variables in a variable group are available along with all locally declared variables, so be aware of name clashes as described in that topic.
