### ISSUE TITLE
duchnocu de la vilardiére

### ISSUE THREAD

**Issue by terryparker639674** [MicrosoftDocs/vsts-docs#3669]
[Tapez vos commentaires ici]

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 4cf58945-edff-cb3b-ab71-d45d480f1044
* Version Independent ID: 8a1c8ac9-a829-837b-5e52-81766c1f545e
* Content: [Requirements for setup, upgrade, and administration - Azure DevOps Server & TFS](https://docs.microsoft.com/fr-fr/azure/devops/server/requirements?view=azure-devops)
* Content Source: [https://mseng.visualstudio.com/DefaultCollection/TechnicalContent/_git/tfs-docs-pr?path=%2fdocs%2frequirements.md&version=GBlive&_a=contents](https://mseng.visualstudio.com/DefaultCollection/TechnicalContent/_git/tfs-docs-pr?path=%2fdocs%2frequirements.md&version=GBlive&_a=contents)
* Product: **devops-server**
* Git Login: **aaronhallberg**
* Microsoft Alias: **aaronha**

**Comment by thomps23** [comment]
@terryparker639674 It looks like your feedback wasn't captured in this Issue, would you like to enter it as a comment?
