### ISSUE TITLE
Images and descriptions are slightly out of date

### ISSUE THREAD

**Issue by AspenForester** [MicrosoftDocs/vsts-docs#367]
One of the first examples is in the section describing how to publish an artifact.  Today the basic settings are "display name", "Path to publish", "Artifact name", and "Artifact publish location" but not "Artifact Type"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 02b747eb-53c2-dd5f-cd2b-f337c15e0864
* Version Independent ID: 04538505-00cd-33ac-8008-4b85cca089e3
* Content: [Create your first build and release](https://docs.microsoft.com/en-us/vsts/build-release/actions/ci-cd-part-1)
* Content Source: [docs/build-release/actions/ci-cd-part-1.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/build-release/actions/ci-cd-part-1.md)
* Service: **unspecified**
* GitHub Login: @douge
* Microsoft Alias: **alewis**

**Comment by andyjlewis** [comment]
updated for VSTS recently; fixes for tfs are coming very soon
