### ISSUE TITLE
Parsing error in JSON

### ISSUE THREAD

**Issue by InstantHotCocoa** [MicrosoftDocs/vsts-docs#3670]
For line ""ms.vss-work-web.iteration-backlog-tabs",", the comma is unnecessary.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ecfe2d0d-197f-cca7-b2dd-bbe04942e611
* Version Independent ID: 2e664299-3598-6a29-d2d1-23f0d2217ae2
* Content: [Add tabs on backlog pages](https://docs.microsoft.com/en-us/azure/devops/extend/develop/add-backlog-tabs?view=azure-devops#feedback)
* Content Source: [docs/extend/develop/add-backlog-tabs.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/extend/develop/add-backlog-tabs.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by chcomley** [comment]
Hi @InstantHotCocoa, Thanks so much for your feedback. I've just completed a PR that fixes this, which should be live sometime this afternoon. Thanks again, and I love your user name!

**Comment by InstantHotCocoa** [comment]
Haha. Thank you, I'm so happy to hear you like it.
