### ISSUE TITLE
Need some clarification on some terms used in this article

### ISSUE THREAD

**Issue by Rod-in-NM** [MicrosoftDocs/vsts-docs#3672]
In the first paragraph of this help document it says, "The method you use to customize projects, which impacts all teams, depends on the process model you use." 

Reading through the article I understand the 'process model' to be either Inheritance, Hosted XML or On-Premises XML. I'm working with on-premises XML. 

What I don't understand in this help document is what the 'projects' is that I'm customizing, such as, "The method you use to customize projects...". Is that the TFS Team Project? And I'm really lost as to what the 'teams' are that are a part of the projects customized. Please help me by either defining these terms or linking to their definitions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f1152275-e1e9-cad2-4b6d-e7bab8ed1b74
* Version Independent ID: 231b91a8-c5ac-36db-e2ae-8d837fb70e4b
* Content: [Customize your work tracking experience - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/reference/customize-work?view=azure-devops)
* Content Source: [docs/reference/customize-work.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/reference/customize-work.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@Rod-in-NM - Thank you for your question. I will update the topic to better explain and introduce new terms. Meanwhile, you can get a definition of these terms with links to more information from [Key concepts](https://docs.microsoft.com/en-us/azure/devops/boards/get-started/key-concepts?view=azure-devops#teams).  Project within the Azure Boards content always refers to a project defined in TFS - it used to be referred to as a team project, but now is referred to simply as a project.
