### ISSUE TITLE
I've been using VS 2017 to do some TFS administration; is that wrong?

### ISSUE THREAD

**Issue by Rod-in-NM** [MicrosoftDocs/vsts-docs#3673]
In the section titled, 'How to run the witadmin command-line tool', a note says, "If you are connecting to TFS, you must use the same version of Visual Studio or Team Explorer as TFS. For example, if you connect to a TFS 2017 instance, you must connect from Visual Studio 2017 or Team Explorer 2017. There is no Team Explorer 2015 version." For quite a while now I've been connecting to TFS 2015, using VS 2017, to create TFS Team Projects. And as far as I can tell, there've been no negative repercussions. Is it the case that what I've done so far is OK, using VS 2017? I will have to run witAdmin to do some customization of work objects, so in this case I should not run VS 2017 as I have? Must I use VS 2015's command prompt to perform actions with witAdmin?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 79a9c3fe-7f7a-6050-cc6b-79b1882478c0
* Version Independent ID: 7680f29b-c977-0c83-bbd5-c9ed35372527
* Content: [witAdmin:Customize and manage objects for tracking work - TFS](https://docs.microsoft.com/en-us/azure/devops/reference/witadmin/witadmin-customize-and-manage-objects-for-tracking-work?view=azure-devops-2019&viewFallbackFrom=azure-devops)
* Content Source: [docs/reference/witadmin/witadmin-customize-and-manage-objects-for-tracking-work.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/reference/witadmin/witadmin-customize-and-manage-objects-for-tracking-work.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@Rod-in-NM - Thank you for your inquiry. In general, you need to be on the same version TFS and client. However, if you don't run into a problem, then the different  versions are compatible. If VS 2017 is working against TFS 2015 - then you shouldn't have a problem. 

You may also want to look at using [TFSTeamProjectManager](https://github.com/jelledruyts/TfsTeamProjectManager) for work tracking customization.
