### ISSUE TITLE
Intermediate outputs from stages

### ISSUE THREAD

**Issue by IdiotLeon** [MicrosoftDocs/vsts-docs#3674]
Where to save the output from previous stages, so that I can apply it in latter stages?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4266f72c-c774-0046-4593-d01eb775d3c3
* Version Independent ID: f20827aa-a6c5-96a8-5969-e576ffbc2e38
* Content: [Release stages, queuing policies, and options - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/environments?view=azure-devops)
* Content Source: [docs/pipelines/release/environments.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/release/environments.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment]
Thank you for your feedback. I have passed this on to the product team for advice.

**Comment by RoopeshNair** [comment]
There is no out-of-box support for persisting output from a stage and re-using it in another. As an alternative, you can write to them to a persistent store, for example Azure Storage (upload files using Azure File Copy task) and consume it in later stages

**Comment by IdiotLeon** [comment]
Since there is no easy way to pass output from previous stages to latter stages, I would guess there is no easy way to pass output from previous releases to latter releases. 
Please help confirm that this is correct. Thanks.

**Comment by IdiotLeon** [comment]
I noticed that there are [custom variables](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/variables?view=azure-devops&tabs=batch) to be set. 
Is it possible to set the custom variable in one stage, and later on apply it somewhere else? Or even throughout the whole release pipeline?

**Comment by mchelen** [comment]
@RoopeshNair Thank you for clarifying, can you please add this to the documentation here?
