### ISSUE TITLE
Artifacts Missing from the Menu

### ISSUE THREAD

**Issue by spottedmahn** [MicrosoftDocs/vsts-docs#3679]
The artifacts icon was missing from my project.  Apparently, it can be turned off/on in the Project Settings -&gt; Overview.

Perhaps that should be noted here?  Or a reference to the doc page that describes this?

Thoughts 💭?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3a853a38-a03e-21bd-e7ea-83b452abcadf
* Version Independent ID: 2493af06-7b82-155c-a377-76aba7677a84
* Content: [Where is Package Management?](https://docs.microsoft.com/en-us/azure/devops/artifacts/where-is-package-management?view=azure-devops)
* Content Source: [docs/artifacts/where-is-package-management.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/artifacts/where-is-package-management.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by chcomley** [comment]
@spottedmahn Thanks for this feedback. I've created a user story on my backlog to follow up. I'll be in touch!

**Comment by chasewilson** [comment]
@spottedmahn Thanks for the great feedback and I'm really sorry about the late response. I agree that this is a good place for a note like that and have made the changes. You should see them live within 24 hours. Thank you again and feel free to reach out or create new issues if you have anymore feedback.

**Comment by spottedmahn** [comment]
Nice!  Thanks! 😀

**Comment by spottedmahn** [comment]
looks good 👍

Screenshot for reference:

![image](https://user-images.githubusercontent.com/14079228/66945607-54447080-f01d-11e9-9f7f-c7dfff749716.png)
