### ISSUE TITLE
Git

### ISSUE THREAD

**Issue by JuanZamudioGBM** [MicrosoftDocs/vsts-docs#368]
This does not work as described with a Git repo

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 29c747d0-263d-1ed2-1e6a-477a712ef1d3
* Version Independent ID: 7d062cbc-c549-fde4-4e9a-d04200c3c3e9
* Content: [Compare folders](https://docs.microsoft.com/en-us/vsts/tfvc/compare-folders)
* Content Source: [docs/tfvc/compare-folders.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/tfvc/compare-folders.md)
* Service: **unspecified**
* GitHub Login: @douge
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
@JuanZamudioGBM This article describes the compare folder process for Team Foundation Version Control, which is a different version control system than Git. Here is an article that describes how to view history and file differences with Git: [Review history](https://docs.microsoft.com/en-us/vsts/git/tutorial/history?view=vsts&tabs=visual-studio). Does that info help?
