### ISSUE TITLE
Custom Variables as intermediate outputs

### ISSUE THREAD

**Issue by IdiotLeon** [MicrosoftDocs/vsts-docs#3680]
Is it possible to set the custom variable in one stage, and later on apply it somewhere else? Or even throughout the whole release pipeline?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 611642f0-881f-10b9-ae94-3c562001d1f0
* Version Independent ID: 41efb94b-4c7a-64a3-b23b-70c8634ae727
* Content: [Release variables  and debugging - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/variables?view=azure-devops&tabs=batch)
* Content Source: [docs/pipelines/release/variables.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/release/variables.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment]
Thank you for your feedback. I have passed this on to the product team for advice.

**Comment by RoopeshNair** [comment]
Passing variables across stages is not supported. You will have to write it to a persistent store and retrieve it in subsequent stage(s)
