### ISSUE TITLE
Tortoise SVN Client & Server SSL certificate verification fails

### ISSUE THREAD

**Issue by KarlMaynardDK** [MicrosoftDocs/vsts-docs#3681]
In case anyone else comes across this issue - here is a work around.

In the DevOps SVN service connection you can enable "Accept untrusted SSL certificates", however you may still get the SLL certificate verification fails problem.

When this option is checked/enabled DevOps adds   --trust-server-cert  to the SVN command line sent to the build agent, for Toroise SVN this tells the client to allow for an "unknown certificate authority" (the option is now in fact depreciated - see svn help info).

This means that if the name in your certificate does not match the url you are getting the sources from, the svn client will not connect. This may occur if you are using the ip address for the server.

The simplest way to work around this is to use you browser to view the certificate that you are using, check the cn value (the name of the server specified in the certificate). Then on the server that is running the build agent, add a record to the hosts file that matches this name and point it to the ip address of your svn server.

The new option --trust-server-cert-failures that replaces the option allows for different combinations of options, including an option of 'cn-mismatch'. This option allows the url and the name in the certificate to be different. At the time of writing, DevOps svn only supports the older (depreciated) command.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a8fa162b-f422-0dee-9ddf-ff725dacb4d3
* Version Independent ID: fc95545a-a8f8-c21d-243f-ed1fb3f65c32
* Content: [Use Subversion with Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/java/subversion?view=azure-devops#feedback)
* Content Source: [docs/java/subversion.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/java/subversion.md)
* Product: **devops**
* GitHub Login: @DavidStaheli
* Microsoft Alias: **dastahel**

**Comment by davidstaheli** [comment]
Thank you for this workaround, @KarlMaynardDK.  We added it to the docs (which should be live in a few days) and have it on our backlog to adopt the newer svn command line option `--trust-server-cert-failures`.
