### ISSUE TITLE
On different Azure DevOps account, the list of MS hosted agents are not the same and it doesn't have Windows 2019 agent

### ISSUE THREAD

**Issue by eriawan** [MicrosoftDocs/vsts-docs#3683]
Hi guys, 

When I want to create build agent from designer, on one account, it is not showing `Hosted Windows 2019 with VS 2019` choice at all.

This is the screenshot of my accounts on creating CI using web designer:

![image](https://user-images.githubusercontent.com/8773147/54591861-b58f6b80-4a5d-11e9-83a7-4ebfe37e5889.png)

I just want to know why this happened. If the deployment of hosted agents are still in progress, then the documentation must be updated too. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 99af681d-41ad-da15-0b72-08b5cd5a11ac
* Version Independent ID: 2fa0df36-a437-8cbb-b019-b49b31b1e116
* Content: [Microsoft-hosted agents for Azure Pipelines - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/agents/hosted.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/agents/hosted.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by eriawan** [comment]
FYI, I have submitted feedback on Microsoft/azure-pipelines-image-generation repo.

See Microsoft/azure-pipelines-image-generation#796 for reference.

This confusion may belongs to Azure Pipelines team solely, but I think it;s quite related because if the Windows 2019 agent is not fully deployed on all Azure DevOps account, current MS Docs of Azure DevOps Pipelines should explicitly state this problem.

**Comment by thejoebourneidentity** [comment]
Let us know if this is still unresolved for you.
