### ISSUE TITLE
Job templates with parameters does documentation does not match schema

### ISSUE THREAD

**Issue by dwilsonbst** [MicrosoftDocs/vsts-docs#3686]
Following the documentation [Job templates with parameters](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/templates?view=azure-devops#job-templates-with-parameters) gives an
error "/templates/microservice-templates/net-core.yml@templates (Line: 2, Col: 3): A sequence was not expected"

In an editor, I get "unexpected property parameters". I've tried to copy the example verbatim and still get the same error.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6724abea-bbdc-bf66-ed5e-3214fa6c3e66
* Version Independent ID: 4f8dab21-3f0e-da32-cc0e-1d85c13c0065
* Content: [Job and step templates - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/templates?view=azure-devops#passing-parameters)
* Content Source: [docs/pipelines/process/templates.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/templates.md)
* Product: **devops**
* GitHub Login: @vtbassmatt
* Microsoft Alias: **alewis**

**Comment by dwilsonbst** [comment]
My mistake, the editor says invalid no matter what, but I've resolved my underlying issue.

**Comment by vtbassmatt** [comment]
Thanks, sorry for the trouble. We have some schema bugs we need to resolve in the editor :)
