### ISSUE TITLE
Add Consistency in Branching Guidance

### ISSUE THREAD

**Issue by ChristopherMank** [MicrosoftDocs/vsts-docs#369]
The article "How We Use Git at Microsoft" (https://www.visualstudio.com/learn/use-git-microsoft/) describes hotfixes in the Feature Flag section. It indicates you create a branch off of master like anything else and after it's been PRd back into master, you cherry-pick the change from master back into the release branch. I like how this works, however it's different than what's stated above in this guide. This guide indicates you branch off of release and cherry-pick those changes back down to master. While they are pretty similar, it would be nice to see them consistent. Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe168fc3-2ed2-b3e6-ce30-cac721165ceb
* Version Independent ID: 8d63fbd7-12c4-9a94-92f6-969e7eb41037
* Content: [Git branching guidance](https://docs.microsoft.com/en-us/vsts/git/concepts/git-branching-guidance)
* Content Source: [docs/git/concepts/git-branching-guidance.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/git/concepts/git-branching-guidance.md)
* Service: **unspecified**
* GitHub Login: @douge
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
@ChristopherMank Sorry for the long delay in responding, we had a backlog of git issues. I'm tracking a work item to make this update - I think I will add a short description and link from the Branching Guidance article to the How we use Gt at Microsoft article and discuss both approaches. I don't have an ETA but I'll make this change. Thank you for your feedback.

**Comment by chkapil** [comment]
Hello, any update on this? What I read on this page is in contradiction to what I hear from Edward (in the embedded video).  I feel that point raised by @ChristopherMank still remains valid and not sure why this discussion has been marked as closed?
