### ISSUE TITLE
Will the docs show previous versions of the task or only the current version?

### ISSUE THREAD

**Issue by jafin** [MicrosoftDocs/vsts-docs#3690]
Is there a way in the docs to see the previous task version or will they only ever publish the current task version?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b03d67d0-8738-72e6-dbe7-324c1784d4fc
* Version Independent ID: bbb4d774-cd98-3ecb-7ccf-5f49e6f2b425
* Content: [Download Pipeline Artifact task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/download-pipeline-artifact?view=azure-devops#feedback)
* Content Source: [docs/pipelines/tasks/utility/download-pipeline-artifact.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/utility/download-pipeline-artifact.md)
* Product: **devops**
* GitHub Login: @steved0x
* Microsoft Alias: **midenn**

**Comment by chasewilson** [comment]
@jafin Thank you for the question. There are some issues with older versions of the tasks and will be deprecated in the future. As of right now, we are only supporting the current version of a task. If you have an more questions or feedback. Feel free to reach out!
