### ISSUE TITLE
Are there any size limits?

### ISSUE THREAD

**Issue by nayanshah** [MicrosoftDocs/vsts-docs#3691]
The page doesn't mention any size limits for JSON documents. Are there total, per user limit or per document limits? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8490096d-54dd-697b-62a3-9c930d0733d1
* Version Independent ID: 04f42aed-a8c2-f124-1c32-37daf54e8400
* Content: [Data and Setting Storage](https://docs.microsoft.com/en-us/azure/devops/extend/develop/data-storage?view=azure-devops#feedback)
* Content Source: [docs/extend/develop/data-storage.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/extend/develop/data-storage.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by chcomley** [comment]
Hi @nayanshah, I've followed up with the team and will get back to you as soon as possible on this. Thanks for reaching out!

**Comment by chcomley** [comment]
Hi @nayanshah, There are currently no limits, however you should be aware that depending on how large the size of the data is within your document, it can affect the performance of the extension. Please let us know if you have any further questions, as I'll be closing this issue. Thank you!
