### ISSUE TITLE
Work Item Types

### ISSUE THREAD

**Issue by serpent5** [MicrosoftDocs/vsts-docs#3693]
In the opening paragraph, it reads:

> You do this by adding one of three work item types—user stories, bugs, features, epics, and tasks—that the Agile process provides.

The content states that there are three work item types and then immediately lists five.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ef5b4734-b75e-95c3-73d2-78216e166bf1
* Version Independent ID: e4404510-ff79-aabf-1214-1d1ccb968aba
* Content: [Understand what you get with Azure Boards - Azure Boards](https://docs.microsoft.com/en-gb/azure/devops/boards/get-started/what-is-azure-boards?toc=%2Fazure%2Fdevops%2Fboards%2Fget-started-agile%2Ftoc.json&bc=%2Fazure%2Fdevops%2Fboards%2Fget-started-agile%2Fbreadcrumb%2Ftoc.json&view=azure-devops#feedback)
* Content Source: [docs/boards/get-started/what-is-azure-boards.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/boards/get-started/what-is-azure-boards.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@serpent5  - Thank you for the correction. Will update the article.
