### ISSUE TITLE
Platform UI code blocks should be labelled as TypeScript instead of JavaScript

### ISSUE THREAD

**Issue by alexkokkinos** [MicrosoftDocs/vsts-docs#37]
Some "Use a Platform UI control" code blocks (like the TreeView or Grid pages with examples) are labeled as JavaScript even though the code is written in TypeScript.
```
``` javascript
```
should be
```
``` typescript
```

Pages with this issue that I've found:

https://docs.microsoft.com/en-us/vsts/extend/develop/ui-controls/grido
https://docs.microsoft.com/en-us/vsts/extend/develop/ui-controls/menubaro
https://docs.microsoft.com/en-us/vsts/extend/develop/ui-controls/waitcontrolo

**Comment by erickson-doug** [comment]
@elbatk can you address this?

**Comment by alexkokkinos** [comment]
@erickson-doug @elbatk I hope my PR doesn't address this poorly/incorrectly, obviously you can close/disregard if so.

I just wanted to make sure I brought up the slight confusion that some of these docs created for me when they presented TypeScript as JavaScript-labeled code blocks.

I didn't update `menubaro.md` since that document was strangely almost entirely in HTML rather than markdown, so I just didn't dedicate any time trying to convert the entire document - especially if there was a specific reason for that being written in HTML that I wasn't aware of.

**Comment by elbatk** [comment]
I've fixed the two that you had in a PR here. I didn't realize `menubaro.md` was written like that, I'll need to go in and change it because it should just be markdown. Thanks @alexkokkinos !

**Comment by steved0x** [comment]
Following up on this issue, I believe that these issues have been addressed by @elbatk and I am closing this issue. Thank you for your contribution!
