### ISSUE TITLE
What about authentication of TestManagement?

### ISSUE THREAD

**Issue by hira29feb** [MicrosoftDocs/vsts-docs#370]
What about authentication of TestManagement, kindly elaborate that as well. Im facing TeamFoundationServerUnauthorizedException while running the query in single sing-in and REST API.

Here's my code:
string batchQuery = string.Format( "SELECT * FROM TestResult where TestCaseId IN ({0}) GROUP BY [TestPointId] ORDER BY [TestRunId] desc,[TestPointId] desc ", testCaseIDs);
ITestCaseResultCollection testCaseResultColl = WIProject.TestManagementProject.TestResults.Query(batchQuery);
// gets exception in last line

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aa8505e8-cef0-fee8-866a-e000058ac233
* Version Independent ID: d6858ee2-4282-b4e1-fb3b-e8b531b950b7
* Content: [.NET Client Library Samples for VSTS](https://docs.microsoft.com/en-us/vsts/integrate/get-started/client-libraries/samples?view=vsts)
* Content Source: [https://mseng.visualstudio.com/DefaultCollection/TechnicalContent/_git/vsts-docs-pr?path=%2fdocs%2fintegrate%2fget-started%2fclient-libraries%2fsamples.md&version=GBlive&_a=contents](https://mseng.visualstudio.com/DefaultCollection/TechnicalContent/_git/vsts-docs-pr?path=%2fdocs%2fintegrate%2fget-started%2fclient-libraries%2fsamples.md&version=GBlive&_a=contents)
* Service: **unspecified**
* GitHub Login: @douge
* Microsoft Alias: **elbatk**

**Comment by elbatk** [comment]
@hira29feb super sorry for the long delay here! We've just recently switched to this new feedback system and things got crazy there for a bit. Assigning this to the product team so we can try to get your question answered!

**Comment by wnjenkin** [comment]
@vinodjo to help out.

**Comment by vinodjo** [comment]
The information provided above doesn't give enough context to provide any meaningful help. Request you to send the issue details along with the code snippet at devops_tools@microsoft.com for us to be able to help you.
