### ISSUE TITLE
Broken image in 'Approve release deployments from your channel' 

### ISSUE THREAD

**Issue by rolnikrolnik** [MicrosoftDocs/vsts-docs#3701]
There is a broken image link in that part of the article:

![Approval image |10x10](../_img/integrations-slack/Approve.gif =850x400)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 99a6f5aa-7e92-a028-d13e-e1e4b7fede86
* Version Independent ID: be7e5d7c-0033-6b72-4bd1-809f7d1894aa
* Content: [Azure Pipelines with Slack - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/integrations/slack?view=azure-devops#feedback)
* Content Source: [docs/pipelines/integrations/slack.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/integrations/slack.md)
* Product: **devops**
* GitHub Login: @atinb
* Microsoft Alias: **atinb**

**Comment by RGKarthik** [comment]
This has been fixed

**Comment by atinb** [comment]
@steved0x Kindly close. Thanks
