### ISSUE TITLE
Reference "Content Type" for Azure Key Vault Secret

### ISSUE THREAD

**Issue by BevanG** [MicrosoftDocs/vsts-docs#3704]
Can you please provide a method to reference the "Content Type" field of an Azure Keyvault Secret? This would be handy to reference as $(KVSecret).ContentType or a variable or some other method. The field and value is there in the UI, so I'm hoping there's some way to reference it.

We store the username in the "Content Type" field of the corresponding secret. For some reason Key Vault does not allow underscores in the "Name" field so we can't use the Name field as the username.

This would allow us to reference the username and secret as relative values rather than have the username in a normal Variable Group and the password in a Secret Variable Group.

The alternative is to allow underscores in the Name field of KeyVault and we wouldn't need to worry.

![Azure DevOps Key Vault Secret](https://user-images.githubusercontent.com/29765765/54733425-b525da80-4bed-11e9-865e-6c0fe6e24385.png)

**Comment by thomps23** [comment]
@BevanG Thanks for your suggestion. Please accept our apologies for the delay in getting to thiss issue. To make sure your idea gets in front of the right people, please [submit your idea]( https://developercommunity.visualstudio.com/content/idea/post.html?space=21).
