### ISSUE TITLE
So how to write workItemControl.html?

### ISSUE THREAD

**Issue by InstantHotCocoa** [MicrosoftDocs/vsts-docs#3705]
As title.

Is this part of document related to https://github.com/Microsoft/vsts-extension-color-control?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6e6cb0ed-c129-901c-10a2-909354aa562f
* Version Independent ID: ceb10d41-b306-0d3f-ccb2-124a3ba69332
* Content: [Add a custom control to the work item form](https://docs.microsoft.com/en-us/azure/devops/extend/develop/custom-control?view=azure-devops)
* Content Source: [docs/extend/develop/custom-control.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/extend/develop/custom-control.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by chcomley** [comment]
Hi @InstantHotCocoa! I'm looking into this and will be in touch. Thank you!

**Comment by chcomley** [comment]
Hi @InstantHotCocoa, So, if you're asking if the github link is an example of how to write a control for work items, then the answer is yes. If not, please clarify your question so we can better help you. Thank you!

**Comment by InstantHotCocoa** [comment]
Yes that's just what I meant. Thank you.
