### ISSUE TITLE
Azure Artifact supported types

### ISSUE THREAD

**Issue by alessio80** [MicrosoftDocs/vsts-docs#3707]
According to this [sprint update](https://docs.microsoft.com/en-us/azure/devops/release-notes/2019/sprint-148-update#all-artifacts-package-types-supported-in-releases) all artifact types should be supported but it seems they're not (only NuGet).
It's only a matter of time?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 598465e1-85d4-4961-b8b6-902d6026c5e3
* Version Independent ID: 5ef1308a-3aeb-fcc4-dec7-6f10785612a3
* Content: [Release artifacts and artifact sources - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/artifacts?view=azure-devops#nuget)
* Content Source: [docs/pipelines/release/artifacts.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/release/artifacts.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment]
Thank you for your feedback. Bugs and issues related to the product rather than the documentation are best posted on the Developer Community website at https://developercommunity.visualstudio.com/spaces/21/index.html, where they are tracked by the product teams. Please post your feedback there. Thank you.

**Comment by 24mu13** [comment]
mmm.. it's not fair, since it's a matter of documentation: you say something new is supported when actually is not!
anyway, here it is: https://developercommunity.visualstudio.com/content/problem/502935/still-nuget-only-packages-are-supported-in-release.html

**Comment by alexhomer1** [comment]
Thank you. I will consult the deveopment team and ask them to investigate.
