### ISSUE TITLE
Incorrect markdown in anchor example

### ISSUE THREAD

**Issue by wtjones** [MicrosoftDocs/vsts-docs#372]
This example has a space after the section name. I realize that it is just an example, but it might be a good idea to use `heading-id` instead

>[text to display](./target.md#heading id)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 63e81f8a-e33c-afb7-493b-f51f40fafd49
* Version Independent ID: c9495a96-c3e8-00f1-1e53-da6ce584412b
* Content: [Syntax usage for Markdown files, widgets, wikis, and pull requests - VSTS & TFS](https://docs.microsoft.com/en-us/vsts/collaborate/markdown-guidance?view=vsts#links)
* Content Source: [https://mseng.visualstudio.com/DefaultCollection/TechnicalContent/_git/vsts-docs-pr?path=%2fdocs%2fcollaborate%2fmarkdown-guidance.md&version=GBlive&_a=contents](https://mseng.visualstudio.com/DefaultCollection/TechnicalContent/_git/vsts-docs-pr?path=%2fdocs%2fcollaborate%2fmarkdown-guidance.md&version=GBlive&_a=contents)
* Service: **unspecified**
* GitHub Login: @douge
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@wtjones - Thank you for your comment. I am updating the topic per your suggestion.
