### ISSUE TITLE
Edit Link

### ISSUE THREAD

**Issue by ChristopherMank** [MicrosoftDocs/vsts-docs#373]
The edit link to this document connects to a VSTS account and not Git Hub to create a PR to update the doc.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 29515e24-2993-544a-5ac5-183a3d78b1e1
* Version Independent ID: 7690fa54-341a-30bc-9a58-4a61562227b3
* Content: [Delete users for Visual Studio Team Services](https://docs.microsoft.com/en-us/vsts/accounts/delete-account-users?view=vsts)
* Content Source: [https://mseng.visualstudio.com/DefaultCollection/TechnicalContent/_git/vsts-docs-pr?path=%2fdocs%2faccounts%2fdelete-account-users.md&version=GBlive&_a=contents](https://mseng.visualstudio.com/DefaultCollection/TechnicalContent/_git/vsts-docs-pr?path=%2fdocs%2faccounts%2fdelete-account-users.md&version=GBlive&_a=contents)
* Service: **unspecified**
* GitHub Login: @douge
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
@ChristopherMank Thanks for alerting us and I'm sorry the Edit function isn't working correctly. Our engineering team is currently resolving this issue. I am also working on the update you provided.
