### ISSUE TITLE
git-svn link was wrong

### ISSUE THREAD

**Issue by ShaneZhengNZ** [MicrosoftDocs/vsts-docs#3732]
https://docs.microsoft.com/en-us/azure/devops/repos/git/perform-migration-from-svn-to-git?view=azure-devops

the git-svn utility link was wrong.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: edd6cbc8-5e3b-c3a1-4672-d42510cc058b
* Version Independent ID: 8fe81fb5-7c2d-2562-5659-55fccbb3126c
* Content: [Migrate from Subversion (SVN) to Git](https://docs.microsoft.com/en-us/azure/devops/repos/git/perform-migration-from-svn-to-git?view=azure-devops)
* Content Source: [docs/repos/git/perform-migration-from-svn-to-git.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/repos/git/perform-migration-from-svn-to-git.md)
* Product: **devops**
* GitHub Login: @hkamel
* Microsoft Alias: **hkamel**

**Comment by ShaneZhengNZ** [comment]
Create a PR #3733

**Comment by thomps23** [comment]
@ShaneZhengNZ Thanks again for fixing this issue with a PR. Closing out the issue.
