### ISSUE TITLE
Is there a mapping for agent pool agent and agent vmImage?

### ISSUE THREAD

**Issue by WeihanLi** [MicrosoftDocs/vsts-docs#3739]
Is there a mapping for agent pool agent and agent vmImage?

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 483dcb1c-1a89-2b20-4cf2-abd3ae88d9ed
* Version Independent ID: dc4722ed-5a4b-26ec-e7d5-a149bf6e79a7
* Content: [Build, test, and deploy .NET Core apps - Azure Pipelines](https://docs.microsoft.com/zh-cn/azure/devops/pipelines/languages/dotnet-core?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/languages/dotnet-core.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/languages/dotnet-core.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by vijayma** [comment]
You can find the mappings here: https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml. Also, I am pushing an update to the dotnetcore topic to include a link to the hosted agents topic.

**Comment by WeihanLi** [comment]
Thanks so much @vijayma
