### ISSUE TITLE
Sub-areas, several areas ID

### ISSUE THREAD

**Issue by 4dnomaid** [MicrosoftDocs/vsts-docs#3740]
Hello! I have some problems with using the WHEN or WHENNOT tags. Our project has an area "Product" and its sub-areas (children): "Documents", "SDK", etc.

1. I need to specify the area with the sub-area (child). For example:
&lt;FIELD  ...&gt; 
   &lt;WHEN field="System.AreaPath" value="Product\Documents"&gt;  ...  &lt;/WHEN&gt;
&lt;/FIELD&gt;

An error occurs during import "User/Group 'Product\Documents' is not found. The account you entered is not recognized". The condition only works when value="Product".

2. &lt;FIELD  ...&gt; 
   &lt;WHEN field="System.AreaId" value="10"&gt;  ...  &lt;/WHEN&gt;
&lt;/FIELD&gt;

I want to list several IDs. For example, "10, 12, 25". Can I perform this in one condition?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0897217b-652f-b83e-f6e4-bb5b3a2009f3
* Version Independent ID: e18350ad-2a42-702e-96ef-ef716b226193
* Content: [Assign conditional-based values and rules - Azure DevOps & TFS](https://docs.microsoft.com/en-us/azure/devops/reference/xml/assign-conditional-based-values-and-rules?view=azure-devops#feedback)
* Content Source: [docs/reference/xml/assign-conditional-based-values-and-rules.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/reference/xml/assign-conditional-based-values-and-rules.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@4dnomaid - The scenario you ask about isn't supported.
