### ISSUE TITLE
Describe implicit jobs

### ISSUE THREAD

**Issue by hosszubalazs** [MicrosoftDocs/vsts-docs#3741]
Creating an example pipeline for dotnet core does not include a "jobs" tag. I believe in this case there is still a job (the step needs to exist somewhere), although it is implicit. I think describing this behaviour is extremely important for newcomers, stating out from the example pipelines.

Please update the documentation to describe the possibility of implicit jobs!

Thanks and cheers,
Balázs

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 54bf6c2f-95c1-943d-26ae-d7099143bccf
* Version Independent ID: 0833bb55-1e54-6953-ee69-de6d191d2ec1
* Content: [Build and release jobs in Azure Pipelines and TFS - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/phases?view=azure-devops&tabs=yaml#feedback)
* Content Source: [docs/pipelines/process/phases.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/phases.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment]
Thank you for your feedback. I have passed this on to the product team for advice.

**Comment by vijayma** [comment]
Thanks. We have fixed this and explained that you do not have to use the job keyword in the simplest case. This updated doc will roll out on 5/6/2019 or 5/7. Thank you.
