### ISSUE TITLE
Clarification for ability to run MS hosted agents on interactive mode

### ISSUE THREAD

**Issue by jaaakkko** [MicrosoftDocs/vsts-docs#3742]
Hey,

I've been looping over the documentation without finding an answer to my question. I have tried to figure out that is it possible to run MS hosted agents for example Hosted VS2017 in interactive mode or not.

Article https://docs.microsoft.com/en-us/azure/devops/pipelines/test/ui-testing-considerations?view=azure-devops&tabs=mstest doesn't provide the information and leads to this article, where the information is missing also.

Release notes from December 2017 says "If you’re using the Hosted VS2017 queue, your build and release tasks now run as administrator, in interactive mode. This means you can now use this hosted pool to run UI tests and install whatever software you need." But I've found also people saying they are running as a service.

Which one is it? Or is it possible to choose somehow?

If its really running in interactive mode by default, what is the max resolution for that agent and is it possible to alter that?

Br, Jaakko

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 09e51d18-72ec-1ad4-9ae7-8185c8e1dcd6
* Version Independent ID: 9f2f0471-d123-8e95-1606-cd811d1ece9a
* Content: [Perform UI tests with Selenium - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/test/continuous-test-selenium?view=azure-devops)
* Content Source: [docs/pipelines/test/continuous-test-selenium.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/test/continuous-test-selenium.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment]
Thank you for your feedback. I have passed this on to the product team for advice.

**Comment by PBoraMSFT** [comment]
@jaaakkko - Please see the following sections in the UI testing considerations doc:
* [Visible UI testing using Microsoft hosted agents](https://docs.microsoft.com/en-us/azure/devops/pipelines/test/ui-testing-considerations?view=azure-devops&tabs=mstest#visible-ui-testing-using-microsoft-hosted-agents) - as mentioned in this section, hosted agents are pre-configured for UI testing. You do not need to do anything else for using hosted agents for UI testing.

*[Setting screen resolution](https://docs.microsoft.com/en-us/azure/devops/pipelines/test/ui-testing-considerations?view=azure-devops&tabs=mstest#setting-screen-resolution) - contains a link to the screen resolution utility.
