### ISSUE TITLE
release pipelines may find artifacts at $(System.ArtifactsDirectory)/**/*.nupkg

### ISSUE THREAD

**Issue by ctaggart** [MicrosoftDocs/vsts-docs#3745]
It may be worth mentioning that release pipelines download the pipeline artifacts to `$(System.ArtifactsDirectory)` by default. Therefore, to push the artifacts, I used `$(System.ArtifactsDirectory)/**/*.nupkg`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0fa37a3f-6551-16ad-e164-a4ac522cdaab
* Version Independent ID: a3fd6935-2b99-92ef-4eb3-3249fca01f8a
* Content: [NuGet restore, pack, and publish task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/package/nuget?view=azure-devops)
* Content Source: [docs/pipelines/tasks/package/nuget.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/package/nuget.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by chasewilson** [comment]
@ctaggart, I've updated the documentation with a note to reference the pipelines! Thank you for the feedback and I hope you will create a new issue if you have any more :)
