### ISSUE TITLE
setting hard-coded variables in yaml doesn't worrk

### ISSUE THREAD

**Issue by mydiemho** [MicrosoftDocs/vsts-docs#3747]
I have set a variable in the yaml file but the build couldn't pick it up.

Here's the failed build
https://dev.azure.com/msft-vott/VoTT/_build/results?buildId=1938

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7458d5b2-1bb7-7d87-7ce6-2b0c430b0155
* Version Independent ID: edf5bbd3-a3f0-5426-e985-31290f8afd05
* Content: [YAML schema - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=example#bash)
* Content Source: [docs/pipelines/yaml-schema.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/yaml-schema.md)
* Product: **devops**
* GitHub Login: @steved0x
* Microsoft Alias: **macoope**

**Comment by zeniri** [comment]
Hi mydiemho, Can't see your failed build. All I see is a successful build. If you however have resolved the issue feel free to publish the answer and close the topic. Thanks

**Comment by damccorm** [comment]
Thank you for your feedback. 
We are closing this issue as there is no action to take on our part to address the issue.  The guidance provided is correct, requested additional information was not provided, or the content referenced is no longer relevant.
