### ISSUE TITLE
Screenshot from VSTS require an update

### ISSUE THREAD

**Issue by SychevIgor** [MicrosoftDocs/vsts-docs#3748]
This screenshot was done in VSTS, for Azure DevOps url will be different. Please update, to avoid potential issues with artifact troubleshooting. 
![image](https://user-images.githubusercontent.com/578954/54866021-18e00d00-4d80-11e9-9004-c1f994a338c7.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30d1eafd-a130-355c-a0d6-fd3a5b1b37b0
* Version Independent ID: 809003e5-b5bc-611b-3f56-9e5e62f2ee56
* Content: [Keep your OSS packages safe with upstream sources](https://docs.microsoft.com/en-us/azure/devops/artifacts/tutorials/protect-oss-packages-with-upstream-sources?view=azure-devops&tabs=nuget)
* Content Source: [docs/artifacts/tutorials/protect-oss-packages-with-upstream-sources.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/artifacts/tutorials/protect-oss-packages-with-upstream-sources.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by chcomley** [comment]
Thanks @SychevIgor, I've created a work item to address this!

**Comment by chasewilson** [comment]
I have updated the screenshot and should see the updates within 24 hours. Thank you for your feedback!
