### ISSUE TITLE
Update screenshot with navigation panel from VSTS

### ISSUE THREAD

**Issue by SychevIgor** [MicrosoftDocs/vsts-docs#3749]
https://docs.microsoft.com/en-us/azure/devops/artifacts/how-to/_img/us-with-sources.png?view=azure-devops screenshot was done in VSTS. new looks a bit different.
Please, update this screenshot it

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 03b6ce9e-b09c-69a8-5153-8bb814c25f54
* Version Independent ID: ebc53603-e70e-fdcd-5895-8ebc8f980703
* Content: [Set up upstream sources for packages in Azure DevOps Services and TFS](https://docs.microsoft.com/en-us/azure/devops/artifacts/how-to/set-up-upstream-sources?view=azure-devops)
* Content Source: [docs/artifacts/how-to/set-up-upstream-sources.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/artifacts/how-to/set-up-upstream-sources.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by chcomley** [comment]
Thanks for letting us know, @SychevIgor. I've created an item on my backlog to address this! Thanks again!

**Comment by chasewilson** [comment]
@SychevIgor I don't believe there is a screenshot in the most recent documentation here so I'll be closing this issue. If you have anymore feedback, please feel free to open a new issue :)

**Comment by SychevIgor** [comment]
item in a backlog... in the past it means "maybe in a few years"

**Comment by SychevIgor** [comment]
@chasewilson cool... April-November. 6 months.

**Comment by elbatk** [comment]
@SychevIgor Sorry for the delay, we've had some significant turnover in both the product space and docs space for Azure Artifacts. That's calmed down quite a bit and you shouldn't see such ridiculous delays in issues like this, thanks :)
