### ISSUE TITLE
Add Notes for Work Item Impact

### ISSUE THREAD

**Issue by ChristopherMank** [MicrosoftDocs/vsts-docs#375]
I would add this to the doc via a PR but see issue# 373 for that. Verbiage should be added to indicate the impact this has on the work items. For example, user is no longer selectable in user dropdowns, however their name still shows on all work items they were related to and they can still be searched in queries. The name will not show in the name drop down in the query, but you can still type the name in manually and it will search. Also, if you do add the user back in later, it will link back to that user if you use the same email address. The only deviance from this is if you use the TFS Import tool. This might need it's own doc that this doc references. My .02 :-)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 29515e24-2993-544a-5ac5-183a3d78b1e1
* Version Independent ID: 7690fa54-341a-30bc-9a58-4a61562227b3
* Content: [Delete users for Visual Studio Team Services](https://docs.microsoft.com/en-us/vsts/accounts/delete-account-users?view=vsts)
* Content Source: [https://mseng.visualstudio.com/DefaultCollection/TechnicalContent/_git/vsts-docs-pr?path=%2fdocs%2faccounts%2fdelete-account-users.md&version=GBlive&_a=contents](https://mseng.visualstudio.com/DefaultCollection/TechnicalContent/_git/vsts-docs-pr?path=%2fdocs%2faccounts%2fdelete-account-users.md&version=GBlive&_a=contents)
* Service: **unspecified**
* GitHub Login: @douge
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
@ChristopherMank Thanks for your update! I've added a note, which better clarifies the impact and it should be reflected online sometime today. Thank you!

**Comment by ChristopherMank** [comment]
Looks great, thanks!
