### ISSUE TITLE
Cur VSTS header

### ISSUE THREAD

**Issue by SychevIgor** [MicrosoftDocs/vsts-docs#3752]
https://docs.microsoft.com/en-us/azure/devops/artifacts/_img/delete/delete-maven-package.png?view=azure-devops
please, cut header from VSTS age. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 31a8d31b-229b-7383-1cc0-f3d7c65eca84
* Version Independent ID: 70ba7acf-adae-e1b7-a42d-3f1344c5293c
* Content: [Delete and recover packages](https://docs.microsoft.com/en-us/azure/devops/artifacts/how-to/delete-and-recover-packages?view=azure-devops&tabs=maven)
* Content Source: [docs/artifacts/how-to/delete-and-recover-packages.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/artifacts/how-to/delete-and-recover-packages.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by chasewilson** [comment]
I have updated the screen shot and you should be able to see the update within 24 hours. If you have anymore feedback, please feel free to reach out or create a new issue
