### ISSUE TITLE
Create a feed link is wrong

### ISSUE THREAD

**Issue by zariye** [MicrosoftDocs/vsts-docs#3759]
Seems like the creation of a feed is not properly linked, it goes back to:https://docs.microsoft.com/en-gb/azure/devops/artifacts/?view=azure-devops

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77bcd39f-91ab-bb93-40fc-dd4fc5f2374f
* Version Independent ID: c228aece-669a-57d6-b3ed-d427586f8a61
* Content: [Publish and then download a Universal Package](https://docs.microsoft.com/en-gb/azure/devops/artifacts/quickstarts/universal-packages?view=azure-devops&tabs=azuredevops#create-a-feed)
* Content Source: [docs/artifacts/quickstarts/universal-packages.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/artifacts/quickstarts/universal-packages.md)
* Product: **devops**
* GitHub Login: @alexmullans
* Microsoft Alias: **amullans**

**Comment by mitchdenny** [comment]
Thanks for reporting the issue, we've submitted a PR on our side to fix the issue.

**Comment by steved0x** [comment]
Both the create feed and edit feed links were broken and the fix will be live today, thanks for letting us know.
