### ISSUE TITLE
Small mistake

### ISSUE THREAD

**Issue by jmilch** [MicrosoftDocs/vsts-docs#376]
"Areas" and "Iterations" are mixed up above the first screenshots

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 98f473c6-87ae-591e-24be-74e556af8155
* Version Independent ID: 15e3ef29-a1ad-d902-b2db-82dbaa765023
* Content: [About area and iteration paths - VSTS & TFS](https://docs.microsoft.com/en-us/vsts/work/customize/about-areas-iterations?view=vsts)
* Content Source: [https://mseng.visualstudio.com/DefaultCollection/TechnicalContent/_git/vsts-docs-pr?path=%2fdocs%2fwork%2fcustomize%2fabout-areas-iterations.md&version=GBlive&_a=contents](https://mseng.visualstudio.com/DefaultCollection/TechnicalContent/_git/vsts-docs-pr?path=%2fdocs%2fwork%2fcustomize%2fabout-areas-iterations.md&version=GBlive&_a=contents)
* Service: **unspecified**
* GitHub Login: @douge
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@jmilch - Thank you for your correction. I'm updating the topic to reflect it.
