### ISSUE TITLE
I can't understand the fix for the build failing because of resource authorization

### ISSUE THREAD

**Issue by chris31389** [MicrosoftDocs/vsts-docs#3760]
The instructions dictate:

1. Navigate to the pipeline in Azure Pipelines.
2. Switch the pipeline's default branch to the branch that includes the new service connection reference. For example, if you've made a change in a branch called features/add-resource, then switch the pipeline's default branch to features/add-resource.
3. Save the pipeline.
4. Revert back to the prior default branch and save the pipeline again.

I am trying to fix a build in my PR that is refusing to build configured with yaml because of resource authorization.  

I am struggling to work out what you mean by "Navigate to the pipeline in Azure Pipelines".  I can't see anything on the website that states that it is a pipeline.

I'm not in release management, this is for a PR build.  Please can you help instruct me on how I can achieve this work around?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee4ec9d0-e0d5-4fb4-7c3e-b84abfa290c2
* Version Independent ID: 3e2b80d9-30e5-0c48-49f0-4fcdfedf5eee
* Content: [Resources - Azure Pipelines](https://docs.microsoft.com/en-gb/azure/devops/pipelines/process/resources?view=azure-devops&viewFallbackFrom=vsts#troubleshooting-authorization-for-a-yaml-pipeline)
* Content Source: [docs/pipelines/process/resources.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/resources.md)
* Product: **devops**
* GitHub Login: @vtbassmatt
* Microsoft Alias: **alewis**

**Comment by vtbassmatt** [comment]
https://dev.azure.com/<your_organization>/<your_project>/_build will give you the list of build pipelines. From there you should be able to find the pipeline that's giving you trouble and follow the instructions.

Thanks for the doc feedback, too. For a GitHub user, the instructions aren't clear enough since you may never have logged into your Azure DevOps account.

**Comment by chris31389** [comment]
@vtbassmatt Thanks for replying so fast. 

When I follow your instructions I "edit" the build that is giving me problems, but I can't work out what step 2 means.  Does this mean, change the branch that triggers the build?

I've found out how to complete the workaround.

In the documentation, I propose the following change:

1. Navigate to the Build definition of the build that is failing.
1. Click Edit.  You should see the YAML script that defines the build.
1. Click the button with the three vertical dots, and select Triggers.  
1. Navigate to the YAML tab (far left)
1. Highlight the `Get Sources` within the Pipeline
1. Switch the pipeline's default branch to the branch that includes the new service connection reference. For example, if you've made a change in a branch called features/add-resource, then switch the pipeline's default branch to features/add-resource.
1. Save the pipeline.
1. Revert back to the prior default branch and save the pipeline again.

I've expanded out the first point into 5 points to make it clearer

**Comment by vtbassmatt** [comment]
Thanks. The user interface is undergoing some flux right now, and not all customers see the exact same steps. That's why the message is a little more generic than what you wrote.

Soon, this won't be a problem at all, as we'll address the underlying authorization differently.
