### ISSUE TITLE
Use System.Links.IncludeAll instead of System.IncludeAllExternalLinks and System.IncludeAllWorkItemLinks

### ISSUE THREAD

**Issue by echalone** [MicrosoftDocs/vsts-docs#3762]
FYI for anybody who had the same problem as me: If you want to include all external links or all work item links, at least in TFS 2018 Update 3.2 Patch 2 on-premise, you will have to use the type "System.Links.IncludeAll" instead of the here listed "System.IncludeAllExternalLinks" and "System.IncludeAllWorkItemLinks" (which will not be recognized on work item template import).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 53aa48e0-7006-fa63-9915-c7d72dd5623d
* Version Independent ID: b3816d11-7cb9-1c56-4cfc-1158e05187cb
* Content: [LinksControlOptions XML elements reference - Azure DevOps & TFS](https://docs.microsoft.com/en-us/azure/devops/reference/xml/linkscontroloptions-xml-elements?view=tfs-2018#feedback)
* Content Source: [docs/reference/xml/linkscontroloptions-xml-elements.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/reference/xml/linkscontroloptions-xml-elements.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@echalone - Thank you for the correction, and apologies for the delay in responding. I'm in the process of updating the article.
