### ISSUE TITLE
Use WorkItemTypeFiltersScope="project | all" instead of WorkItemFiltersScope="Project | All"

### ISSUE THREAD

**Issue by echalone** [MicrosoftDocs/vsts-docs#3763]
If you want to display only work items from the same project in the links-control, again at least with TFS 2018 Update 3.2 Patch 2 on-premise, you will have to name the attribute "WorkItemTypeFiltersScope" instead of the here stated "WorkItemFiltersScope" and the values can be "project" (for Project scope) or "all" (to display work items from all projects). The case of the first letter is important, so do not use "Project" with an upper case "P", but "project" with a lower case "p".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 53aa48e0-7006-fa63-9915-c7d72dd5623d
* Version Independent ID: b3816d11-7cb9-1c56-4cfc-1158e05187cb
* Content: [LinksControlOptions XML elements reference - Azure DevOps & TFS](https://docs.microsoft.com/en-us/azure/devops/reference/xml/linkscontroloptions-xml-elements?view=tfs-2018)
* Content Source: [docs/reference/xml/linkscontroloptions-xml-elements.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/reference/xml/linkscontroloptions-xml-elements.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@echalone - Thank you for the correction, and apologies for the delay in responding. I'm in the process of updating the article.
