### ISSUE TITLE
Incorrect text in example

### ISSUE THREAD

**Issue by robbratton** [MicrosoftDocs/vsts-docs#3765]
This example:
git clone https://contoso-ltd.visualstudio.com/MyFirstProject/_git/contoso-&gt;demo

should read:
git clone https://contoso-ltd.visualstudio.com/MyFirstProject/_git/contoso-demo

I removed an extraneous greater than symbol.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc4e7f5a-08f4-5c12-cb6d-424d6e5dadaa
* Version Independent ID: e317a392-cb78-7fcc-fcf8-2cecaa9e6580
* Content: [Code with Git - Azure DevOps - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/user-guide/code-with-git?view=azure-devops)
* Content Source: [docs/user-guide/code-with-git.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/user-guide/code-with-git.md)
* Product: **devops**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Thanks for the heads up, @robbratton! I've completed a PR today that removes the symbol. It should go live sometime today. Thanks again!
