### ISSUE TITLE
Link not working in the "Prerequisites" section

### ISSUE THREAD

**Issue by raviteja333** [MicrosoftDocs/vsts-docs#3767]
The link which guides to convert the Azure AD user type under the prerequisites section is not working.

 Link : Convert Azure AD UserType from Guest to Member using Azure AD PowerShell (https://blogs.msdn.microsoft.com/dstfs/2015/12/23/issues-with-azure-active-directory-guest-users-in-aad-backed-visual-studio-team-services-accounts/).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 031380a0-4f04-4105-199a-81715b42c653
* Version Independent ID: 570b2795-90ad-32b4-7ad0-1fceb186ffa3
* Content: [Connect organization to Azure Active Directory - Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/connect-organization-to-azure-ad?view=azure-devops#feedback)
* Content Source: [docs/organizations/accounts/connect-organization-to-azure-ad.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/accounts/connect-organization-to-azure-ad.md)
* Product: **devops**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Thanks for the heads up, @raviteja333. I'm looking into this and will keep you posted.

**Comment by chcomley** [comment]
Hi @raviteja333, This blog post has been removed. I've added the instructions to our [FAQ article](https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/faq-add-delete-users?view=azure-devops), which should go live sometime today. Thank you!
