### ISSUE TITLE
Hosted build agent specs?

### ISSUE THREAD

**Issue by mchelen** [MicrosoftDocs/vsts-docs#3768]
What are the specs of the hosted build agents, like CPU and RAM? It says 10GB storage available, but there are no other specs listed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 99af681d-41ad-da15-0b72-08b5cd5a11ac
* Version Independent ID: 2fa0df36-a437-8cbb-b019-b49b31b1e116
* Content: [Microsoft-hosted agents for Azure Pipelines - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/agents/hosted.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/agents/hosted.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by fume** [comment]
it says it's a Standard DS2_v2 Azure VM, so you can find the specs at: https://docs.microsoft.com/en-us/azure/virtual-machines/windows/sizes-general#dsv2-series

**Comment by thejoebourneidentity** [comment]
Let us know if you still have questions.
