### ISSUE TITLE
Finding the repository guid via the REST APIs

### ISSUE THREAD

**Issue by christothes** [MicrosoftDocs/vsts-docs#377]
The git functionality for the wiki is great, however I'd like to do something using the REST API for pull requests relating to that repo. The only problem is that the repository is not listed in the visualstudio.com/_apis/git/repositories/ API response, so it's not possible to find the guid to address the specific repo. 

Is it possible to find the wiki's git repo guid by some other means, or can the api be changed to expose it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 889cc132-e8ed-ea22-cfff-51ee434fb113
* Version Independent ID: 47e62550-289d-e89a-1122-2a6319dc2711
* Content: [Create a wiki for your team project - VSTS & TFS 2018](https://docs.microsoft.com/en-us/vsts/collaborate/wiki-create-repo?view=vsts)
* Content Source: [https://mseng.visualstudio.com/DefaultCollection/TechnicalContent/_git/vsts-docs-pr?path=%2fdocs%2fcollaborate%2fwiki-create-repo.md&version=GBlive&_a=contents](https://mseng.visualstudio.com/DefaultCollection/TechnicalContent/_git/vsts-docs-pr?path=%2fdocs%2fcollaborate%2fwiki-create-repo.md&version=GBlive&_a=contents)
* Service: **unspecified**
* GitHub Login: @douge
* Microsoft Alias: **kaelli**

**Comment by sandeepchadda** [comment]
Hi, you should be able to use the WIKI REST APIs to extract the repo id or repo name:
https://docs.microsoft.com/en-us/rest/api/vsts/wiki/wikis/get

**Comment by KathrynEE** [comment]
@christothes - Thank you for your inquiry. As Sandeep mentions above, you should be able to use the WIKI REST APIs to extract the repo id or repo name:
https://docs.microsoft.com/en-us/rest/api/vsts/wiki/wikis/get. I've added a link from the TOC to the REST API.
