### ISSUE TITLE
Corrupt documentation

### ISSUE THREAD

**Issue by mschofie** [MicrosoftDocs/vsts-docs#3772]
The 'Expressions' documentation appears to be corrupt - it contains Git merge markers.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77c58a78-a567-e99a-9eb7-62dddd1b90b6
* Version Independent ID: 680a79bc-11de-39fc-43e3-e07dc762db18
* Content: [Expressions - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/expressions?view=azure-devops#feedback)
* Content Source: [docs/pipelines/process/expressions.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/expressions.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by Paul-Dempsey** [comment]
Checked by following the links, and as far as I can tell, has been fixed already.

**Comment by mschofie** [comment]
Yup - things look better now. Thanks for checking!
