### ISSUE TITLE
Agent Pools graphic still refers to 'Queues'

### ISSUE THREAD

**Issue by MisterReally** [MicrosoftDocs/vsts-docs#3773]
Queues were renamed to Project Agent Pools in 8/2018 for Azure DevOps, but the graphic on the page still refers to 'Queues' and doesn't distinguish Organization Agent Pools vs Project Agent Pools ('Queue1', 'Queue2', 'Queue1' in the graphic).

Also, I expect some versions of TFS on-prem still use the term Queues (2015/2017/2018) ; if that is the case, the documentation will be confusing to the users of those version seeking help because there is no mentioned of Queues anymore.  

![image](https://user-images.githubusercontent.com/1761739/54975713-3ca87c00-4f55-11e9-8929-0f6196a08cc5.png)

I'm also noticing visualstudio.com is also still referred to in the graphic.  I believe the graphic is used on other pages in the documentation as well. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4409a9cb-8448-edd6-da0a-243e5601aa3e
* Version Independent ID: ec15f71a-a76d-c3f9-1d31-832f92183ef4
* Content: [Agents pools - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/pools-queues?view=azure-devops#feedback)
* Content Source: [docs/pipelines/agents/pools-queues.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/agents/pools-queues.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by vijayma** [comment]
Thanks for pointing this out. We are now updating the topic so that you will see the corresponding picture based on the version of the product for which you are reviewing the doc. We do not have a picture yet for Azure Pipelines specifically, but will consider adding that in the future.
