### ISSUE TITLE
Know branch for event git.push

### ISSUE THREAD

**Issue by AlessandroDalMas** [MicrosoftDocs/vsts-docs#3775]
When I set a web hook for every push in all repository, I can't select the branch that I'm looking for obviously. But I would like to see in the event git.push for which branch i get it. So I can filter for the branch I'm interested. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6033d681-9093-547c-20fd-b31183c2bb33
* Version Independent ID: 0d92e3f0-7fb4-57e5-d913-f305a055a819
* Content: [Service hooks event reference](https://docs.microsoft.com/en-us/azure/devops/service-hooks/events?view=azure-devops#tfvc.checkin)
* Content Source: [docs/service-hooks/events.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/service-hooks/events.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by chcomley** [comment]
Hi @AlessandroDalMas, I'm following up on this and will be in touch. Thanks for reaching out!

**Comment by chcomley** [comment]
Hi @AlessandroDalMas, can you please confirm whether you're looking for the branch name in the payload of the web hook? Thanks for your time!

**Comment by AlessandroDalMas** [comment]
Hi, thank you for your reply.

(My English is not quite good)

I would like to see inside the payload git.push, probably under 'repository' section:

`    "repository": {
      "id": "278d5cd2-584d-4b63-824a-2ba458937249",
      "name": "Fabrikam-Fiber-Git",
      "url": "https://dev.azure.com/fabrikam-fiber-inc/DefaultCollection/_apis/repos/git/repositories/278d5cd2-584d-4b63-824a-2ba458937249",
      "project": {
        "id": "6ce954b1-ce1f-45d1-b94d-e6bf2464ba2c",
        "name": "Fabrikam-Fiber-Git",
        "url": "https://dev.azure.com/fabrikam-fiber-inc/DefaultCollection/_apis/projects/6ce954b1-ce1f-45d1-b94d-e6bf2464ba2c",
        "state": "wellFormed"
      },
      "defaultBranch": "refs/heads/master",
      "remoteUrl": "https://dev.azure.com/fabrikam-fiber-inc/DefaultCollection/_git/Fabrikam-Fiber-Git"
    },`

or right after the `"eventType": "git.push",`

the information: `"sourceBranch": "master"`

**Comment by chcomley** [comment]
Hi @AlessandroDalMas,

Inside of the “refUpdates” object in the payload there is a “name” property that has the branch. 
"refUpdates": [
            {
                "name": "refs/heads/users/roferg/newtest",
                "oldObjectId": "c65a129c49084964fe9671f5cebeb924874d1275",
                "newObjectId": "099741bbd685f95e1648d4facb279ff4a03b8cc4"
            }
This should allow you to do the client side filtering you’re looking to do. 

Please let us know if you have any further questions. Thank you!

**Comment by AlessandroDalMas** [comment]
Hi there, sorry for the long time it took me to answer.

I was collecting data to show you as I already tried this and I show you this result:

```
Name: refs/tags/RichiesteEnti.Metriche.Manual_2019.4.10.1
Old Object Id: 0000000000000000000000000000000000000000
New Object Id: 616e280cc29222813e5606e25891d5f6384db9ff
```

What is this exactly?

**Comment by chcomley** [comment]
Hi @AlessandroDalMas, When you add a tag to a repo it’s considered a push, so it causes a web hook to fire under the git.push scenario. If you don't care about tags, then you can just ignore web hooks related to tags. Does this help? Thanks!

**Comment by AlessandroDalMas** [comment]
Hi, thank you for your time replying me.

In this specific case I just need to filter for all pushes on master repositories, but in an immediate future I would use all kind of git.push events to trigger different behaviors on my system.

So, back to my question, in case of tags, can I get the branch where the tag has been added directly in the webhook?

And, is there any other refUpdate type that I will get for other behaviors?

**Comment by chcomley** [comment]
@AlessandroDalMas, Tags aren't associated with a [branch](https://docs.microsoft.com/en-us/azure/devops/repos/git/git-tags?view=azure-devops). They're associated with a commit. So, there won't be a branch to report in the Git.Push payload when a tag is added. 
Please let me know if you need further assistance with this, as I can engage an expert. Thanks!

**Comment by AlessandroDalMas** [comment]
I am pretty sure that I misunderstand something.
From a tag-git.push webhook, I would not be able to see the associated branch where the related commit has been pushed as a commit can be in multiple branches or in no branch.

Is this right?

Than I should ask git api about in which branch is the commit.

**Comment by chcomley** [comment]
Hi @AlessandroDalMas, I've engaged an expert, who can help you further. He should be in touch soon. Thanks!

**Comment by roofers** [comment]
@AlessandroDalMas - Tags in Git are associated with a commit, not a branch. A commit can be on one branch or more many branches. You will need to as Git which branch a given commit is on. You can use something like "Git branch --contains <commit>".

**Comment by AlessandroDalMas** [comment]
@roofers, @chcomley  Ok, thank you both, I reviewed the concept of tag and how it affect my problem.
I have been on holidays for some quite days and couldn't answer before.

I close the issue as is not one.
Thanks for your time.
