### ISSUE TITLE
Azure Stack doc does not mention creating a private agent that runs on Azure Stack

### ISSUE THREAD

**Issue by dburnison** [MicrosoftDocs/vsts-docs#3778]
Regarding https://docs.microsoft.com/en-us/azure/devops/pipelines/targets/azure-stack?view=azure-devops:  This document does not mention creating a Private Build/Release agent on the Azure Stack that you are targeting for deployment. However, "Tutorial: Deploy apps to Azure and Azure Stack" https://docs.microsoft.com/en-us/azure/azure-stack/user/azure-stack-solution-pipeline says that having a Private Agent is a prerequisite. Does this doc need to be updated? Do the two documents need to be combined into a single document? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 102bd9d0-0c29-3eb9-b6a1-3d2d41da0643
* Version Independent ID: a96f92b7-dc0b-ae2d-a35d-6e66dba6e4dc
* Content: [Deploy to Azure Stack - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/targets/azure-stack?view=azure-devops)
* Content Source: [docs/pipelines/targets/azure-stack.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/targets/azure-stack.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by RoopeshNair** [comment]
@N-Usha - can you please take a look?

**Comment by N-Usha** [comment]
Thanks for the feedback @dburnison . We'll have the docs fixed and cross linked.

**Comment by N-Usha** [comment]
Closing this as the doc has been enhanced with the pre-req details for private build agent. Thanks!
