### ISSUE TITLE
Why doesn't the .NET Core sample have the azure-pipelines.yml file?

### ISSUE THREAD

**Issue by JimInWA** [MicrosoftDocs/vsts-docs#3780]
This is referring to https://docs.microsoft.com/en-us/azure/devops/pipelines/get-started-yaml?view=azure-devops&viewFallbackFrom=vsts

Under the "Get the sample code" section, with the exception of the .NET Core all of the samples have a predefined azure-pipeline.yml file.

The text in "Get your first build", step 6 says "If your repository already contains an azure-pipelines.yml file (which is the case for the sample repositories in this article)"

However, if you go to the .NET Core sample and look at the README.md text at https://github.com/MicrosoftDocs/pipelines-dotnet-core, there the text implies that this article will show you how to create the first pipeline.

So which item needs to be changed to break the circular reference?

**Comment by andyjlewis** [comment]
Thank you for reporting this issue. Fixed by some changes a while back.
