### ISSUE TITLE
If a PAT expires for an account that is federated with Azure Active Directory, and something attempts to access Azure DevOps using the expired PAT can the authentication failures cause the account to get locked out in AD?

### ISSUE THREAD

**Issue by MarkIannucci** [MicrosoftDocs/vsts-docs#3782]
We had a PAT expire on a service account which we use to automate updates to work items.  The PAT expired and we started getting a bunch of authentication errors from our service account.  At roughly the same time, the account got locked out of Active Directory.  

We think that the service account attempting to authenticate with an expired PAT is why the account got locked out of Active Directory, but we don't have sufficient access to our domain controllers to confirm our suspicion.  

So we thought we'd turn to the documentation to see if an expired PAT can lockout an AD account if AD is federated with an organization in Azure Dev Ops, and unfortunately the documentation is silent on that.

So, is it possible for failed PAT authentication attempts to lock out an account in AD?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2bfea574-db69-a5fd-37fe-64ecfdac502a
* Version Independent ID: 4037d475-f194-2ac9-ffd6-70530fc3140a
* Content: [Authenticate with personal access tokens - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/use-personal-access-tokens-to-authenticate?view=azure-devops)
* Content Source: [docs/organizations/accounts/use-personal-access-tokens-to-authenticate.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/accounts/use-personal-access-tokens-to-authenticate.md)
* Product: **devops**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @MarkIannucci, thanks for reaching out. I'll look into this and be in touch soon.

**Comment by chcomley** [comment]
Hi @MarkIannucci, In regards to your question, "Is it possible for failed PAT authentication attempts to lock out an account in AD?" the answer is no.  It’s most likely a coincidence, as the PAT expiration and disabling the account happened around the same time. Do let us know if you have any further questions. I'll be closing this issue. Thanks!

**Comment by MarkIannucci** [comment]
Thank you for your research for us.  We'll keep our eye out for the actual root cause.

**Comment by lincolnzocateli** [comment]
I'm a DevOps admin for the company I work for, the company is big, has AD integrated with DevOps. The PAT used on agent (on-premises) was generated by me, but if I'm no longer in AD tomorrow, how will DevOps handle the PAT generated for this agent? How can we generate a PAT for a service user who would not be connected to a person?

**Comment by MarkIannucci** [comment]
@lincolnzocateli , I had a similar question.  The [documentation indicates](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/v2-windows?view=azure-devops#server-url-and-authentication) that the PAT is only used for initial configuration.  Once the agent is running, it does its own authentication thereafter.
