### ISSUE TITLE
Extension points for ms.vss-code-web.git-branches* are not working

### ISSUE THREAD

**Issue by eumikhailov** [MicrosoftDocs/vsts-docs#3786]
Extension points for branches menu described here [here](https://docs.microsoft.com/en-us/azure/devops/extend/reference/targets/overview?view=tfs-2018#menus-and-toolbars) are not working or not actual:
```
ms.vss-code-web.git-branches-tree-menu
ms.vss-code-web.git-branches-summary-grid-menu
ms.vss-code-web.git-branches-summary-grid-diff-menu
```

**Comment by chcomley** [comment]
Hi @eumikhailov, Thank you for reaching out. I'm following up on this and will be in touch.

**Comment by chcomley** [comment]
Hi @eumikhailov, It looks like this issue got away from me - please accept my sincere apology! Are you still experiencing this behavior? Did you get help from [Support](https://visualstudio.microsoft.com/vs/support/#talktous)? Please let me know, otherwise I'll be closing this issue.

**Comment by eumikhailov** [comment]
Hi @chcomley, you can close this issue, thank you for your help.
