### ISSUE TITLE
Pipelines should be noted available to Stakeholders in the "Supported access levels" section 

### ISSUE THREAD

**Issue by dburnison** [MicrosoftDocs/vsts-docs#3789]
I believe the following section should be marked as available for **Stakeholders**: 
**Author Release Pipelines and Manage Releases**
Includes defining release pipelines and multi-stage continuous deployment (CD) pipelines, and using approvals and gates to control deployments

This is in the "Supported access levels" section. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8db47b85-e178-7969-40d3-3fa83aa3fb54
* Version Independent ID: a78e453b-4b8f-c885-42ee-8a9d9979f345
* Content: [What are access levels? What access levels are supported? - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/security/access-levels?view=azure-devops&viewFallbackFrom=vsts#stakeholder-access)
* Content Source: [docs/organizations/security/access-levels.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/security/access-levels.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@dburnison - Thank you for your comment. The View Releases and Manage Approvals feature is available to Stakeholders. The Author Release Pipelines and Manage Releases feature is not, except for Azure DevOps Services when the **Full access to Azure Pipelines for Stakeholders** preview feature is enabled for the organization.  I've add more clarification for this.

**Comment by dburnison** [comment]
@KathrynEE, Thank you for the clarification.
