### ISSUE TITLE
Capabilities field lacks information

### ISSUE THREAD

**Issue by gewoonwoutje** [MicrosoftDocs/vsts-docs#3790]
https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/agents?view=azure-devops#capabilities

Some things are unclear to me:
How can Capabilities be used in combination with Microsoft-hosted agents. If "Each time you run a pipeline, you get a fresh virtual machine." is true:
  - Why can I set user-defined Capabilities on a Microsoft-hosted agent?
  - Can I define what should be pre-installed on a Microsoft-hosted agent? If so:
     - "After you install new software on a agent, you must restart the agent for the new capability to show up." How?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 47625b86-abd5-ee15-6d61-8bcf81861b96
* Version Independent ID: be9a6174-a69b-7aed-d584-5f602fcc5eb4
* Content: [Build and Release Agents - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/agents?view=azure-devops#capabilities)
* Content Source: [docs/pipelines/agents/agents.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/agents/agents.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by vijayma** [comment]
We are fixing the document to clarify that capabilities do not apply to Microsoft-hosted agents. They only apply to self-hosted agents. Also, we are clarifying the note on "After you install new software..." to say that this is for self-hosted agents.
