### ISSUE TITLE
Incorrect Information

### ISSUE THREAD

**Issue by gi-joe-moto** [MicrosoftDocs/vsts-docs#3792]
This statement: "You can view the version of an agent by navigating to Agent pools and selecting the Capabilities tab for the desired agent." is inaccurate.  When I go to the capabilities tab I see nothing about version, only the ability to add USER CAPABILITIES.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 47625b86-abd5-ee15-6d61-8bcf81861b96
* Version Independent ID: be9a6174-a69b-7aed-d584-5f602fcc5eb4
* Content: [Build and Release Agents - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/agents?view=azure-devops#feedback)
* Content Source: [docs/pipelines/agents/agents.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/agents/agents.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by vijayma** [comment]
You are probably looking at one of the Microsoft-hosted pools. The hosted pools do not show any system capabilities. Also, they are always kept up to date. If you look at any of the self-hosted pools, then the capabilities tab includes system capabilities, and one of the tags in that is Agent.Version.
