### ISSUE TITLE
Build notifications for failed

### ISSUE THREAD

**Issue by gaborbuzasi** [MicrosoftDocs/vsts-docs#3795]
Is it possible to filter the build notifications for failed notifications only?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 99a6f5aa-7e92-a028-d13e-e1e4b7fede86
* Version Independent ID: be7e5d7c-0033-6b72-4bd1-809f7d1894aa
* Content: [Azure Pipelines with Slack - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/integrations/slack?view=azure-devops#feedback)
* Content Source: [docs/pipelines/integrations/slack.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/integrations/slack.md)
* Product: **devops**
* GitHub Login: @atinb
* Microsoft Alias: **atinb**

**Comment by gaborbuzasi** [comment]
Just wondering if there's any update on this please?

**Comment by atinb** [comment]
@gaborbuzasi Sorry for the delay in responding. This functionality is present in the app. Please see [this documentation](https://docs.microsoft.com/en-us/azure/devops/pipelines/integrations/slack?view=azure-devops) for subscribing only to failed build notifications. Thanks

**Comment by gaborbuzasi** [comment]
@atinb 
Ah that's brilliant! Thank you for the update!
