### ISSUE TITLE
Add Build.Repository.Id

### ISSUE THREAD

**Issue by newOnahtaN** [MicrosoftDocs/vsts-docs#3796]
Please add Build.Repository.Id to this documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ffebdc8-521c-44b5-cde4-4abdc1bd6f18
* Version Independent ID: dc0effda-6d93-62aa-64c5-4e6f283b0826
* Content: [Predefined build variables - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml#feedback)
* Content Source: [docs/pipelines/build/variables.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/build/variables.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by mloskot** [comment]
Any news on this?

It would also be good to explain relation to `BUILD_REPOSITORY_NAME`

**Comment by shayki5** [comment]
`Build.Repoistory.Id` could be so useful!

**Comment by newOnahtaN** [comment]
FYI to mloskot & shayki5, BUILD_REPOSITORY_ID already existed as an environment variable at the time I posted this comment, and still does.

However, this documentation does not reflect it's existence.

In fact, if you inspect your agent build tasks, you will find that there are quite a lot of variables which very much seem like they should be a part of this documentation but are not. I wonder if this documentation has been forgotten.

**Comment by shayki5** [comment]
I checked now and you right! thanks!
Should I open a PR?
