### ISSUE TITLE
Azure DevOps Services Demo Generator Link

### ISSUE THREAD

**Issue by popalex** [MicrosoftDocs/vsts-docs#3797]
The Azure DevOps Services Demo Generator Link link on this page - https://Azure DevOps Servicesdemogenerator.azurewebsites.net/ is invalid.
The correct link should probably be https://azuredevopsdemogenerator.azurewebsites.net/ .

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2923ce2c-7fc0-efef-67b2-c4f1c48600fa
* Version Independent ID: 59129be1-1da1-8260-2a64-4611ccb8fd42
* Content: [Setting up Azure DevOps Services for a Java project](https://docs.microsoft.com/en-us/azure/devops/java/labs/settingvstsproject/?view=azure-devops#feedback)
* Content Source: [docs/java/labs/settingvstsproject/index.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/java/labs/settingvstsproject/index.md)
* Product: **devops**
* GitHub Login: @DavidStaheli
* Microsoft Alias: **dastahel**

**Comment by davidstaheli** [comment]
Thanks!  Verified fixed.
