### ISSUE TITLE
"New Boards Hub"

### ISSUE THREAD

**Issue by boysensci** [MicrosoftDocs/vsts-docs#380]
When the "New Boards Hub" preview is not available yet, why do you then promote it here, and also in videos, e.g. https://www.youtube.com/watch?v=16gOTI_OBw8?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 600604e7-d788-bef3-2542-0c1409dabd8d
* Version Independent ID: 0cd0809c-749f-6c4b-56f3-74563219ad0a
* Content: [Turn preview features on or off - VSTS & TFS](https://docs.microsoft.com/en-us/vsts/collaborate/preview-features?view=vsts)
* Content Source: [https://mseng.visualstudio.com/DefaultCollection/TechnicalContent/_git/vsts-docs-pr?path=%2fdocs%2fcollaborate%2fpreview-features.md&version=GBlive&_a=contents](https://mseng.visualstudio.com/DefaultCollection/TechnicalContent/_git/vsts-docs-pr?path=%2fdocs%2fcollaborate%2fpreview-features.md&version=GBlive&_a=contents)
* Service: **unspecified**
* GitHub Login: @douge
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@boysensci - Thank you for your comment. I've removed the entry in the preview topic. I can't address what others promote in the video - perhaps they are providing coming attractions.
