### ISSUE TITLE
Updating Custom Tasks Versions

### ISSUE THREAD

**Issue by Dejulia489** [MicrosoftDocs/vsts-docs#3800]
I am unable to locate the documentation for when a extension is updated in the Organization and how the task gets updated on the build/release agent itself.  If an extension is published multiple times in a day to the market place with the organization automatically install the latest version of the extension when the release is triggered?

**Comment by chcomley** [comment]
Hi @Dejulia489, Thanks for reaching out. I'm following up on this and will be in touch! Thanks again.

**Comment by chcomley** [comment]
Hi @Dejulia489 ,
When extensions are published, the next time there is activity for the organization is when the latest version of the extension is installed. 
During this installation process, if there is a task in the extension, we start a process to install the tasks in the Azure Dev Ops service.
At runtime of the build/release the agent gets a message that contains what tasks are needed. The agent then downloads these tasks from the service. The agent will pull the latest task version within the major version that the Build/Release author chose. So, if they chose 2.* and the task is updated from 2.1.0 to 2.1.1 the agent will pull 2.1.1.
Does this help? Please let me know whether you have any further questions. Thank you!

**Comment by Dejulia489** [comment]
Hello @chcomley , 
This is very helpful thank you!

**Comment by ahmadyo** [comment]
Previously defined builds not using new updated version of task, until edit each definition.
