### ISSUE TITLE
Clarify firewall access requirements for downloading universal packages

### ISSUE THREAD

**Issue by geofflamrock** [MicrosoftDocs/vsts-docs#3801]
Hi,

Are there any specific URLs which are used during the download of universal packages from a release pipeline? 

We have opened up firewall access as directed in https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/v2-windows?view=azure-devops&viewFallbackFrom=vsts and other artifact downloads are occurring correctly, however universal packages are failing to download with a connection refused error, so just wondering if there are other URLs that are not mentioned anywhere.

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 405dfb6a-2f3d-1d74-2d28-d00be3bb069d
* Version Independent ID: d446b533-c215-6302-3df2-93b1ffd936df
* Content: [Publish and download Universal Packages in pipelines - Azure Pipelines and TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/universal-packages?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/artifacts/universal-packages.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/artifacts/universal-packages.md)
* Product: **devops**
* GitHub Login: @alexmullans
* Microsoft Alias: **amullans**

**Comment by mitchdenny** [comment]
Azure DevOps is hosted on Azure and our content can be stored up from any of the IPs in which your Azure DevOps organization is hosted:

https://www.microsoft.com/en-us/download/details.aspx?id=41653

Universal Packages uses a combination of access to Azure Compute, Azure Storage and Azure CDN/Edge to serve up Universal Package content. If you tell us what your organization name is we can help you identify the set of datacenters in that list in whcih you need to whitelist.

**Comment by geofflamrock** [comment]
Thanks for your help @mitchdenny our organization is https://dev.azure.com/blueshift

A couple of follow up questions:
1. Are there any other URLs that need to be whitelisted for universal packages in addition to these IPs?
2. The url I mentioned in the original description mentions 2 IP addresses already, would the documentation for universal packages be able to be updated to indicate that these 2 IPs aren't enough, there needs to be more opened if IP filtering is being performed?

**Comment by mitchdenny** [comment]
For Universal Packages you may need to add the ussouth range of addresses. The reason for this is that Universal Packages pulls content directly from Azure Storage accounts via a SAS URL and isn't always proxied through our front-end caches.

**Comment by geofflamrock** [comment]
@mitchdenny thanks for your help, is there any way I can work out these SAS URLs that are being used to pull content from Azure Storage? 

We are using Azure Pipelines agents on-prem at client sites and they will need to open up firewall access for us to be able to download universal packages as part of a release pipeline, so if the URL could be known it would be great. We could potentially try and get them to open up based on the IP ranges from the download link you sent, however they normally prefer to use a URL.

Thanks again for your assistance with this.

**Comment by mitchdenny** [comment]
I've asked our team if there is a way if we can query this on our side to give you a list. It is an implementation detail of the service and there are hundreds of hosts that hte content gets pulled from.

**Comment by geofflamrock** [comment]
Thanks @mitchdenny much appreciated

**Comment by mitchdenny** [comment]
Here is a list of all the storage accounts that a Universal Package or Pipeline Artifact chunk could be downloaded from:

StorageAccount
vsblobprodscussu5shard90
vsblobprodscussu5shard9
vsblobprodscussu5shard89
vsblobprodscussu5shard88
vsblobprodscussu5shard87
vsblobprodscussu5shard86
vsblobprodscussu5shard85
vsblobprodscussu5shard84
vsblobprodscussu5shard83
vsblobprodscussu5shard82
vsblobprodscussu5shard81
vsblobprodscussu5shard80
vsblobprodscussu5shard8
vsblobprodscussu5shard79
vsblobprodscussu5shard78
vsblobprodscussu5shard77
vsblobprodscussu5shard76
vsblobprodscussu5shard75
vsblobprodscussu5shard74
vsblobprodscussu5shard73
vsblobprodscussu5shard72
vsblobprodscussu5shard71
vsblobprodscussu5shard70
vsblobprodscussu5shard7
vsblobprodscussu5shard69
vsblobprodscussu5shard68
vsblobprodscussu5shard67
vsblobprodscussu5shard66
vsblobprodscussu5shard65
vsblobprodscussu5shard64
vsblobprodscussu5shard63
vsblobprodscussu5shard62
vsblobprodscussu5shard61
vsblobprodscussu5shard60
vsblobprodscussu5shard6
vsblobprodscussu5shard59
vsblobprodscussu5shard58
vsblobprodscussu5shard57
vsblobprodscussu5shard56
vsblobprodscussu5shard55
vsblobprodscussu5shard54
vsblobprodscussu5shard53
vsblobprodscussu5shard52
vsblobprodscussu5shard51
vsblobprodscussu5shard50
vsblobprodscussu5shard5
vsblobprodscussu5shard49
vsblobprodscussu5shard48
vsblobprodscussu5shard47
vsblobprodscussu5shard46
vsblobprodscussu5shard45
vsblobprodscussu5shard44
vsblobprodscussu5shard43
vsblobprodscussu5shard42
vsblobprodscussu5shard41
vsblobprodscussu5shard40
vsblobprodscussu5shard4
vsblobprodscussu5shard39
vsblobprodscussu5shard38
vsblobprodscussu5shard37
vsblobprodscussu5shard36
vsblobprodscussu5shard35
vsblobprodscussu5shard34
vsblobprodscussu5shard33
vsblobprodscussu5shard32
vsblobprodscussu5shard31
vsblobprodscussu5shard30
vsblobprodscussu5shard3
vsblobprodscussu5shard29
vsblobprodscussu5shard28
vsblobprodscussu5shard27
vsblobprodscussu5shard26
vsblobprodscussu5shard25
vsblobprodscussu5shard24
vsblobprodscussu5shard23
vsblobprodscussu5shard22
vsblobprodscussu5shard21
vsblobprodscussu5shard20
vsblobprodscussu5shard2
vsblobprodscussu5shard19
vsblobprodscussu5shard18
vsblobprodscussu5shard17
vsblobprodscussu5shard16
vsblobprodscussu5shard15
vsblobprodscussu5shard14
vsblobprodscussu5shard13
vsblobprodscussu5shard12
vsblobprodscussu5shard11
vsblobprodscussu5shard10
vsblobprodscussu5shard1

These account names could have either of these suffixes:

{storageaccountname}.vsblob.vsassets.io
{storageaccountname}.blob.core.windows.net

So you'd need to whitelist those 200 or so URLs. RIght now the second format is going to be most common but there is possibly a future were we swap the former.

**Comment by geofflamrock** [comment]
Thanks @mitchdenny really appreciate the help, i'll see if we can get clients to whitelist these (maybe with some sort of wildcard), hopefully that will get us able to download.

**Comment by chasewilson** [comment]
It looks like this one is taken care of. I'll be closing this issue

**Comment by piroinno** [comment]
I know this has been closed but can anyone point me to where I can get a list of storage accounts?

**Comment by chasewilson** [comment]
Hey @piroinno, I no longer own these docs but have you tried using Azure CLI or Azure PowerShell to get a list of yoru storage accounts? 
```powershell
az login
az storage account list --output table
```
Not sure if this is what you are looking for but I hope it helps :)

**Comment by piroinno** [comment]
I need the list of storage accounts which Azure devops hosts feed  artifacts. Just like the original poster

**Comment by chasewilson** [comment]
I don't have an ADO pipline set up so are you able to use that command or the equal PowerShell command to list the storage accounts and filter out based on the earlier mentioned naming standards?

**Comment by s041507** [comment]
> Here is a list of all the storage accounts that a Universal Package or Pipeline Artifact chunk could be downloaded from:
> 
> StorageAccount vsblobprodscussu5shard90 vsblobprodscussu5shard9 vsblobprodscussu5shard89 vsblobprodscussu5shard88 vsblobprodscussu5shard87 vsblobprodscussu5shard86 vsblobprodscussu5shard85 vsblobprodscussu5shard84 vsblobprodscussu5shard83 vsblobprodscussu5shard82 vsblobprodscussu5shard81 vsblobprodscussu5shard80 vsblobprodscussu5shard8 vsblobprodscussu5shard79 vsblobprodscussu5shard78 vsblobprodscussu5shard77 vsblobprodscussu5shard76 vsblobprodscussu5shard75 vsblobprodscussu5shard74 vsblobprodscussu5shard73 vsblobprodscussu5shard72 vsblobprodscussu5shard71 vsblobprodscussu5shard70 vsblobprodscussu5shard7 vsblobprodscussu5shard69 vsblobprodscussu5shard68 vsblobprodscussu5shard67 vsblobprodscussu5shard66 vsblobprodscussu5shard65 vsblobprodscussu5shard64 vsblobprodscussu5shard63 vsblobprodscussu5shard62 vsblobprodscussu5shard61 vsblobprodscussu5shard60 vsblobprodscussu5shard6 vsblobprodscussu5shard59 vsblobprodscussu5shard58 vsblobprodscussu5shard57 vsblobprodscussu5shard56 vsblobprodscussu5shard55 vsblobprodscussu5shard54 vsblobprodscussu5shard53 vsblobprodscussu5shard52 vsblobprodscussu5shard51 vsblobprodscussu5shard50 vsblobprodscussu5shard5 vsblobprodscussu5shard49 vsblobprodscussu5shard48 vsblobprodscussu5shard47 vsblobprodscussu5shard46 vsblobprodscussu5shard45 vsblobprodscussu5shard44 vsblobprodscussu5shard43 vsblobprodscussu5shard42 vsblobprodscussu5shard41 vsblobprodscussu5shard40 vsblobprodscussu5shard4 vsblobprodscussu5shard39 vsblobprodscussu5shard38 vsblobprodscussu5shard37 vsblobprodscussu5shard36 vsblobprodscussu5shard35 vsblobprodscussu5shard34 vsblobprodscussu5shard33 vsblobprodscussu5shard32 vsblobprodscussu5shard31 vsblobprodscussu5shard30 vsblobprodscussu5shard3 vsblobprodscussu5shard29 vsblobprodscussu5shard28 vsblobprodscussu5shard27 vsblobprodscussu5shard26 vsblobprodscussu5shard25 vsblobprodscussu5shard24 vsblobprodscussu5shard23 vsblobprodscussu5shard22 vsblobprodscussu5shard21 vsblobprodscussu5shard20 vsblobprodscussu5shard2 vsblobprodscussu5shard19 vsblobprodscussu5shard18 vsblobprodscussu5shard17 vsblobprodscussu5shard16 vsblobprodscussu5shard15 vsblobprodscussu5shard14 vsblobprodscussu5shard13 vsblobprodscussu5shard12 vsblobprodscussu5shard11 vsblobprodscussu5shard10 vsblobprodscussu5shard1
> 
> These account names could have either of these suffixes:
> 
> {storageaccountname}.vsblob.vsassets.io {storageaccountname}.blob.core.windows.net
> 
> So you'd need to whitelist those 200 or so URLs. RIght now the second format is going to be most common but there is possibly a future were we swap the former.

@mitchdenny Can you tell me how you got this list? I would like to get this list for West Europe region, and also keep it up to date in the future. So some sort of script would help.
