### ISSUE TITLE
Artfiact Download option is not displaying in Agent Job task

### ISSUE THREAD

**Issue by qlee94** [MicrosoftDocs/vsts-docs#3804]
We have two accounts under one organization in Azure Devops and we have noticed, that Artifact Download option is only displaying in our Dev environment.
Please refer to the screenshots below.
Dev environment
![image](https://user-images.githubusercontent.com/49030909/55162416-16a6f580-5168-11e9-9106-f53cd4699628.png)

Prod environment
![image](https://user-images.githubusercontent.com/49030909/55162425-1c9cd680-5168-11e9-90bd-7f69e046c103.png)

Is there an option somewhere where we can turn this feature on? Or is it just a bug?
Thanks in advance

**Comment by chcomley** [comment]
Hi @qlee94, Thanks for reaching out. I'm following up on this and will be in touch. Thanks again.

**Comment by chcomley** [comment]
Hi @qlee94, 
Please accept my sincerest apology for letting this issue slide. Since this was months ago, I imagine it's worked itself out, so I'll be closing this issue. If it does remain an issue, please let me know. Thanks!
