### ISSUE TITLE
Expressions examples

### ISSUE THREAD

**Issue by rbeauchamp** [MicrosoftDocs/vsts-docs#3805]
Please provide usage examples for each of the expressions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77c58a78-a567-e99a-9eb7-62dddd1b90b6
* Version Independent ID: 680a79bc-11de-39fc-43e3-e07dc762db18
* Content: [Expressions - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/expressions?view=azure-devops#feedback)
* Content Source: [docs/pipelines/process/expressions.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/expressions.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by dazinator** [comment]
I'd like to use an expression so that a task runs only if a variable is present on the release. How would I do that?

**Comment by mattduguid** [comment]
- ${{ if eq(variables['Toggle_Release_Task_123'], 'true') }}: # only run if condition is true 
            - task: PowerShell@2
            etc...

**Comment by IanYates** [comment]
Examples would be *very* welcome

**Comment by Glober777** [comment]
Is there a way to have an expression on a build step to run only if the source branch contains changes within certain sub-folder?

**Comment by dazinator** [comment]
Thanks @mattduguid will give that a try.
