### ISSUE TITLE
Error 404 when clicking links in this doc

### ISSUE THREAD

**Issue by DominoX** [MicrosoftDocs/vsts-docs#3807]
All the links at the top of this page that should show the 'Basic Features', Stakeholder features' and 'Visual Studio Subscriber features' are broken - result 404

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 75aa416a-b842-77d0-e18a-bee7f7bf7205
* Version Independent ID: 65942145-45ca-48bb-6adc-c16bd662b80a
* Content: [Manage users and access levels - Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/manage-users-table-view?view=azure-devops#feedback)
* Content Source: [docs/organizations/accounts/manage-users-table-view.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/accounts/manage-users-table-view.md)
* Product: **devops**
* Technology: **devops-accounts**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
@DominoX, Thanks for reaching out, we appreciate the feedback. I’ve created a user story to address this. Thanks again!

**Comment by chcomley** [comment]
@DominoX, after further investigation, these links are working fine for me in both Microsoft Edge and Google Chrome. Please check again. Thanks!

**Comment by DominoX** [comment]
Thanks. Must have been a temporary outage. Just rechecked the links and found OK now. Thanks for following up.

**Comment by chcomley** [comment]
@DominoX, you bet! Glad it's working now. Have a great weekend.
