### ISSUE TITLE
How do one find out when monthly limit is reached

### ISSUE THREAD

**Issue by artisticcheese** [MicrosoftDocs/vsts-docs#3808]
As per instructions it's possible to see monthly limits and use but there is no indication how to find out when those limits are reset to 0.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c6a488b-88f6-dff6-e2ee-402167e17ad4
* Version Independent ID: 9a4dedda-e82c-2833-f28c-5ab346fb1b38
* Content: [Parallel jobs in Azure Pipelines - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/licensing/concurrent-jobs?view=azure-devops&viewFallbackFrom=vsts#microsoft-hosted-cicd)
* Content Source: [docs/pipelines/licensing/concurrent-jobs.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/licensing/concurrent-jobs.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by artisticcheese** [comment]
It's calendar month I found

**Comment by guestdj** [comment]
It's that you have confirmed that it's monthly, but when in the month is it reset? Is it dependant on some contractual start date where can I find that information so that I can manage the usage of my pipelines. Or is it a fixed day in the month for every customer? Please can someone at MS confirm this

**Comment by dsfrederic** [comment]
Looking for an answer for this as well

**Comment by smholvoet** [comment]
> It's calendar month I found

Can you please share where you found this information?
