### ISSUE TITLE
Setting variables belong to group at queue time

### ISSUE THREAD

**Issue by ItielBeeri** [MicrosoftDocs/vsts-docs#381]
Can variables in variable group be settable at queue time, as regular varibales can?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4827aa99-ae62-bd63-6f2f-a87a4065ed27
* Version Independent ID: c9e461ee-7f42-3503-9460-18fa3a807bbb
* Content: [Variable groups for VSTS and TFS](https://docs.microsoft.com/en-us/vsts/build-release/concepts/library/variable-groups?view=vsts)
* Content Source: [https://mseng.visualstudio.com/DefaultCollection/TechnicalContent/_git/vsts-docs-pr?path=%2fdocs%2fbuild-release%2fconcepts%2flibrary%2fvariable-groups.md&version=GBlive&_a=contents](https://mseng.visualstudio.com/DefaultCollection/TechnicalContent/_git/vsts-docs-pr?path=%2fdocs%2fbuild-release%2fconcepts%2flibrary%2fvariable-groups.md&version=GBlive&_a=contents)
* Service: **unspecified**
* GitHub Login: @douge
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment]
Thanks you for your feedback. I have passed your question to the product team and will let you know their response.

**Comment by alexhomer1** [comment]
Setting the value of variables in a variable group at build queue time is not supported at the moment.

**Comment by ramandeep-singh-1983** [comment]
This is really a required feature. I have the following use case:
1) An Angular app generated and build using Angular CLI. It supports different target environments (dev/test/production).
2) The build step for Angular application requires a target environment at the build time i.e. ng build -dev -e {dev/test/prod}
3) Now, i want to use the same build definition to build and deploy to any environment. I can specify the environment at build queue time (i.e. ng build -dev -e $(build.environment}) but i can't use the same release definition to deploy this build to different target environments. 
4) I need to share the build target variable between a build and release definition, so i can set it at queue time while starting a build and this variable can be picked up by a release definition that can deploy it to either dev or test environment depending on this variable value.

**Comment by Rabadash8820** [comment]
I agree this would be a very useful feature.

@alexhomer1  I'm disappointed to see GitHub Issues turning into a customer support forum.  You shouldn't be "passing questions to the product team", the product team should be looking at these issues directly.  And you can't just close an Issue by saying "this is not supported at the moment" because by definition that means that the Issue is not closed!  Please re-open this Issue and close it when we are actually able to set variable-group-variables at queue time, or at least when the "product team" decides that they will not be implementing this feature and provide _their_ reasoning.

**Comment by ramandeep-singh-1983** [comment]
+1 to the above, this should be kept open.

**Comment by alexhomer1** [comment]
I don't know of a date for the feature to be introduced, or even whether it is planned. As mentioned in the documentation, there is a specific site for feature requests and development progress: https://visualstudio.uservoice.com/forums/330519-team-services. Please post your requests there for consideration by the product team as part of future development. Thank you!

**Comment by ramandeep-singh-1983** [comment]
Thanks, voted for this: https://visualstudio.uservoice.com/forums/330519-visual-studio-team-services/suggestions/32083207-allow-variables-in-variable-groups-to-be-settable
