### ISSUE TITLE
Creating Badge for DevOps Artifacts 

### ISSUE THREAD

**Issue by alohaninja** [MicrosoftDocs/vsts-docs#3810]
First off - love this ability to create badges for simpler semantic versioning! 🙌

One gotcha we ran into is that the badge generated for nuget artifact markdown structure doesn't URL encode the team project name - so adding the markdown badge in github requires you translate special URL characters to their proper encoding - e.g. if my team project is "**My Team**" - the markdown generated badge would require this edit:

**Example**: `https://dev.azure.com/mydevopstenant/My Team/_packaging?_a=package&feed=guid&package=0101`

translated to proper markdown...

**Corrected**: `https://dev.azure.com/mydevopstenant/My%20Team/_packaging?_a=package&feed=guid&package=0101`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d6f530be-df56-eb28-e9a5-9e076554277f
* Version Independent ID: 37367a1e-e655-14ee-dfe4-7270ad85c7eb
* Content: [Share your Azure DevOps Services packages with badges](https://docs.microsoft.com/en-us/azure/devops/artifacts/package-badges?view=azure-devops)
* Content Source: [docs/artifacts/package-badges.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/artifacts/package-badges.md)
* Product: **devops**
* Technology: **devops-artifacts**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by elbatk** [comment]
Hey @alohaninja , thanks for the feedback! I would definitely say that isn't behaving properly. I'll create a bug for the dev team and we'll track it there :)
