### ISSUE TITLE
Hard to understand

### ISSUE THREAD

**Issue by PZ-CFDuToit** [MicrosoftDocs/vsts-docs#3811]
"deployment of a new." - Seems like the sentence is cut short.
"successive environment the next upon successful " - The words seems to be in the wrong order?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 895ed016-6ddc-3458-db9e-ebbedf218982
* Version Independent ID: 36e017f5-b012-fcec-6906-1966f3a97cb4
* Content: [What is Continuous Delivery? - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/learn/what-is-continuous-delivery#feedback)
* Content Source: [https://mseng.visualstudio.com/DefaultCollection/TechnicalContent/_git/devops-learn-pr?path=%2fdocs%2fwhat-is-continuous-delivery.md&version=GBlive&_a=contents](https://mseng.visualstudio.com/DefaultCollection/TechnicalContent/_git/devops-learn-pr?path=%2fdocs%2fwhat-is-continuous-delivery.md&version=GBlive&_a=contents)
* Product: **devops**
* Technology: **devops-learn**
* Git Login: **samgu**
* Microsoft Alias: **samgu**

**Comment by WilliamAntonRohm** [comment]
@PZ-CFDuToit -- Francois, thank you for your feedback.  These typos appear to have been fixed in the article.

My apologies for the delay in responding.
