### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by lachris76** [MicrosoftDocs/vsts-docs#3814]
First link in first purple box is broken.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 02ab6fbc-4df4-bc2d-da58-19dee9395256
* Version Independent ID: e613f4a0-37a5-c2fa-fdf5-345c945de6db
* Content: [How are Backlogs used to support portfolios, priority, and multi-team ownership - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/backlogs/backlogs-overview?view=azure-devops#feedback)
* Content Source: [docs/boards/backlogs/backlogs-overview.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/boards/backlogs/backlogs-overview.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@lachris76  - Thank you for the correction. This is fixed now.
