### ISSUE TITLE
it doesn't work

### ISSUE THREAD

**Issue by fthkucuk** [MicrosoftDocs/vsts-docs#3816]
the Id attribute is invalid ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e7687d0f-cb54-022d-2a2a-7670251e73a4
* Version Independent ID: b1abeb4f-1f46-d759-6b01-0bb560c53778
* Content: [Configure work item form extensions in TFS](https://docs.microsoft.com/en-us/azure/devops/extend/develop/configure-workitemform-extensions?view=azure-devops#feedback)
* Content Source: [docs/extend/develop/configure-workitemform-extensions.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/extend/develop/configure-workitemform-extensions.md)
* Product: **devops**
* Technology: **devops-ecosystem**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by chcomley** [comment]
Hi @fthkucuk, Thanks for reaching out. Are you still experiencing an issue with the documentation? Do let us know and please clarify which part of the doc that may need review. Thanks

**Comment by fthkucuk** [comment]
Hi @chcomley, Thank you for your interest. This is my fault, I figured it out.

**Comment by chcomley** [comment]
That's great! Thanks for letting us know!
