### ISSUE TITLE
Use of localhost address for content hosting

### ISSUE THREAD

**Issue by t-l-k** [MicrosoftDocs/vsts-docs#3819]
It appears as if the `baseUri` property of the `vss-extension.json` file can be used for the inner dev cycle to get AzDO to load content from a localhost web server for ease of script source referencing.

I think this content resource referencing should be made a lot more obvious as it appears to be inferred from other topics (like step 7 in "Deploy web content to Azure" https://docs.microsoft.com/en-us/azure/devops/extend/publish/publish-azure?view=azure-devops), and isn't suggested in the quickstart topics, develop how-tos topics, or here where it makes the most sense in terms of "debugging".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9aef8b13-4b92-251c-01bf-01c31eddb08e
* Version Independent ID: af442847-54cb-fbbc-8b91-a6d60489235d
* Content: [Extension Debugging in a Browser](https://docs.microsoft.com/en-us/azure/devops/extend/test/debug-in-browser?view=azure-devops#feedback)
* Content Source: [docs/extend/test/debug-in-browser.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/extend/test/debug-in-browser.md)
* Product: **devops**
* Technology: **devops-ecosystem**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by chcomley** [comment]
Hi @t-l-k, Thanks for reaching out. I'm following up on this and will be in touch. Thanks again.

**Comment by willsmythe** [comment]
One reason we haven't promoted using a localhost `baseUri` is because it's generally not easy to configure a local HTTPS (secure) web server, and hosting from an HTTP (insecure) web server will result in errors/warnings in the browser (due to the mixing of HTTPS and HTTP content). So, from a doc perspective, it easier to just have developers publish a new version of the extension. Talking about this as an "advanced topic" makes sense though.

**Comment by t-l-k** [comment]
> 
> 
> So, from a doc perspective, it easier to just have developers publish a new version of the extension.

I would consider stating this as a recommended workflow, because it left me guessing.

When you say local HTTPS, is certificate security the only concern here, or is it more AzDO's CORS policy?

**Comment by willsmythe** [comment]
Makes sense / good feedback.

Yah, it's likely not just a certificate problem. There will likely be CORS-related problems (but I can't say for sure since it's been awhile since I tried localhost/HTTP).

**Comment by davidsk** [comment]
Tried this just now - HTTPS is easy enough (asp.net core web with static files package and generated a certifcate using the dev-cert global tool) but when the request to the REST api fails with CORS error.
Access to XMLHttpRequest at 'https://xyz.visualstudio.com/61305bfe-e010-481c-8439-b580d2f29597/_apis/build/definitions' from origin 'https://localhost:5001' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource

**Comment by chcomley** [comment]
Hi @t-l-k, I've created a user story to capture updating this as a "recommended workflow." Thanks very much for your feedback. @davidsk, if you have remaining questions, please contact [Support](https://visualstudio.microsoft.com/vs/support/#talktous), as they can better assist you with a technical issues. Thanks! I'll be closing this issue, however once the user story is completed and the update is published, this thread is automatically notified. Thank you!
