### ISSUE TITLE
Organization rename incomplete or lagging?

### ISSUE THREAD

**Issue by tice17** [MicrosoftDocs/vsts-docs#3820]
After successfully the organization name, the old name still appears in the left pane, under "My Organizations", where the new organization name was expected.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 129e3d78-3ac8-8d07-d573-5530cd018656
* Version Independent ID: 1fbe6f52-2967-114e-1d2b-af4771080ac7
* Content: [Rename your organization - Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/rename-organization?view=azure-devops#feedback)
* Content Source: [docs/organizations/accounts/rename-organization.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/accounts/rename-organization.md)
* Product: **devops**
* Technology: **devops-accounts**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @tice17, this is a good question, which would be better answered by the Support group. Please go here to report a bug: https://azure.microsoft.com/en-us/support/devops/ . Thankk you!

**Comment by jsudesign** [comment]
This also happened to me. I created a new organization which didn't ask for the name of the organization and gave me a default name of Justin0682, when I renamed the organization to our actual organization name it left the justin0682 name on the left panel and when I click on that it 404's. I tried to log out and log back in, still shows the organization name as the old one in the navigation.

**Comment by chcomley** [comment]
@jsudesign, Please go [https://azure.microsoft.com/en-us/support/devops/], and then select **Report a bug**.
