### ISSUE TITLE
What about disabling users?

### ISSUE THREAD

**Issue by lukos** [MicrosoftDocs/vsts-docs#3823]
We need to disable a user who might be returning to work for us full or part time. I don't want to remove him from the system because he has a load of permissions set up. Can we not disable the user account instead?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 27d0fe85-7e69-29b7-206f-797a168505c1
* Version Independent ID: 0e1f085d-0d1f-32bf-51e2-c60bc3f0a763
* Content: [Delete or remove users from team or project - Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/delete-organization-users?view=azure-devops)
* Content Source: [docs/organizations/accounts/delete-organization-users.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/accounts/delete-organization-users.md)
* Product: **devops**
* Technology: **devops-accounts**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @lukos, I'm following up on this and will get back to you shortly. Thanks for reaching out!

**Comment by chcomley** [comment]
Hi @lukos, If you were to downgrade his access level to Stakeholder, he'd be limited. If/when he returns to work, he could be upgraded back to Basic and all of his permissions would work as before. Please let me know if you have any more questions. Thanks!

**Comment by nokturnal** [comment]
Adding to this, @chcomley what happens to commits, board contibributions, and any other items the to be delete user may have had?

**Comment by chcomley** [comment]
@nokturnal, Since the user is not really being deleted (they are just being assigned a different access level), all of those would remain.

**Comment by IIStevowII** [comment]
@chcomley I think @nokturnal is more interested in what happens to work items etc. when the user is actually deleted. (At least I am)

I assume these items will just get unassigned?

**Comment by nokturnal** [comment]
@chcomley: @iistevowll is right... And this should probably be a new post... But since we are here... If the user is deleted vs. an access level change, what happens to that users items / contributions in boards, repos, etc?

**Comment by chcomley** [comment]
Hi @nokturnal and @IIStevowII, The user's history and items will all persist, even if they are removed from the organization.

**Comment by chcomley** [comment]
@nokturnal and @IIStevowII, I'm closing this issue, however do let me know if you have any further questions please. Thank you!
