### ISSUE TITLE
Can't check "Delete branch" option when marking a PR as Auto-Complete / Complete

### ISSUE THREAD

**Issue by cosminstirbu** [MicrosoftDocs/vsts-docs#3826]
Hello,

Recently it seems that the option to delete the source branch before completing a PR is disabled if you are not the owner of the PR (a colleague created it).
Can we configure this, so we can allow anyone who can complete a PR to also delete the source branch?

Thank you,
Cosmin

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 028e7b61-62e4-a10e-e420-3535f7843f0e
* Version Independent ID: 1a6fdbe7-5ba4-a7f8-1b2e-271289a7b9fd
* Content: [Review and merge code with pull requests - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/pull-requests?view=azure-devops)
* Content Source: [docs/repos/git/pull-requests.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/repos/git/pull-requests.md)
* Product: **devops**
* Technology: **devops-code-git**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by marcpopMSFT** [comment]
Thanks for the feedback. I've filed an internal feature request for this since this is a suggestion rather than a documentation bug.  You are also welcome to file this suggestion on https://developercommunity.visualstudio.com/ so you can track status.

**Comment by GiriB** [comment]
@marcpopMSFT Can you share the link to where you created the suggestion? The link your shared above is the developer community homepage

**Comment by marcpopMSFT** [comment]
@GiriB My link above was so the customer could file their own issue if they wanted.  The internal request I filed is here though I have since left the organization: https://dev.azure.com/mseng/AzureDevOps/_queries/edit/1656932/

**Comment by GiriB** [comment]
Thanks @marcpopMSFT. I found a similar suggestion thread here -https://developercommunity.visualstudio.com/content/problem/380224/cannot-delete-source-branch-when-completing-a-pull.html. Posting it here for future viewers.
