### ISSUE TITLE
story points

### ISSUE THREAD

**Issue by josersleal** [MicrosoftDocs/vsts-docs#3828]
When using the sprint board under scrum process the Stories are estimated using story points, however, the tasks created under each are using hours as measurement for remaining work. So is the capacity of each member of team entered by using hours rather than story points.

This is confusing to me at least. because if I estimate a user story in points, then being forced to estimate each sub-task in hours imo defies the purpose of story points and calculating velocity.

The correlation between time and story points should only become semi-available when the velocity stabilises. An since it does not, it simply has less variability, then no fixed hours to measure work should be in the process.

That is how I see it, kindly clarify

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f701e3c3-095b-f60a-ffad-bded9323aa9b
* Version Independent ID: 091f2580-aa9e-4411-89fc-0f26515fa92d
* Content: [Add tasks to support sprint planning - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/sprints/add-tasks?view=azure-devops)
* Content Source: [docs/boards/sprints/add-tasks.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/boards/sprints/add-tasks.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@josersleal - Thank you for your inquiry and apologies for the delay in response.  Currently, the Story Points used to track velocity and hours or days to estimate and track tasks is the way the system works.  With the Analytics Velocity widget, you can now estimate velocity by a count of work items or a sum of a field. This provides teams more options to measure their velocity. Additional options are in development that should widen these choices more.
