### ISSUE TITLE
Gramatical errors in Limited Refs - Azure Devops

### ISSUE THREAD

**Issue by moverperfect** [MicrosoftDocs/vsts-docs#3829]
There are two gramatical error in the last sentance of the section **Finding other people’s branches**.

"They’ve created a command line tool that will call the Azure DevOps REST APIs to favorite a **branch.If** a user wants to favorite a branch, they can just call that **tooland** pass in the name of the branch, and then run git fetch again.

1. Space between fullstop and the start of the final sentance
2. "tool and" instead of "tooland"
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5cc997b4-66b2-486a-8a67-68ee5219eb17
* Version Independent ID: 7157acbc-0feb-2414-8eb8-b1db010371c0
* Content: [Limited Refs - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/learn/git/limited-refs)
* Content Source: [https://mseng.visualstudio.com/DefaultCollection/TechnicalContent/_git/devops-learn-pr?path=%2fdocs%2fgit%2flimited-refs.md&version=GBlive&_a=contents](https://mseng.visualstudio.com/DefaultCollection/TechnicalContent/_git/devops-learn-pr?path=%2fdocs%2fgit%2flimited-refs.md&version=GBlive&_a=contents)
* Product: **devops**
* Technology: **devops-learn**
* Git Login: **samgu**
* Microsoft Alias: **sanoursa**

**Comment by WilliamAntonRohm** [comment]
@moverperfect -- Jack, thank you for your feedback.  These typos have been fixed.
