### ISSUE TITLE
Update supported actions

### ISSUE THREAD

**Issue by ChristopherMank** [MicrosoftDocs/vsts-docs#383]
This document currently lists the supported actions for custom work item rules. It is missing the action to set a field as "read-only".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 053c0f1f-7f66-e48f-438d-5e2d63eb7349
* Version Independent ID: dcc06bfa-a1eb-fa99-3796-4c02ce493a03
* Content: [Add a custom rule to a work item type - VSTS](https://docs.microsoft.com/en-us/vsts/work/customize/process/custom-rules?view=vsts)
* Content Source: [https://mseng.visualstudio.com/DefaultCollection/TechnicalContent/_git/vsts-docs-pr?path=%2fdocs%2fwork%2fcustomize%2fprocess%2fcustom-rules.md&version=GBlive&_a=contents](https://mseng.visualstudio.com/DefaultCollection/TechnicalContent/_git/vsts-docs-pr?path=%2fdocs%2fwork%2fcustomize%2fprocess%2fcustom-rules.md&version=GBlive&_a=contents)
* Service: **unspecified**
* GitHub Login: @douge
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@ChristopherMank - Thank you for your input. The topic has been updated as you suggest.
