### ISSUE TITLE
Add info about users explicitly added

### ISSUE THREAD

**Issue by anmason** [MicrosoftDocs/vsts-docs#3831]
This article should also mention that if a user is explicitly added here but none of the default permissions are changed, the user will not appear on the list the next time the permissions page is loaded.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5f5ce059-ec92-5413-0910-4e28033db034
* Version Independent ID: 540610d3-6073-664d-97f8-e7d8e0a21a20
* Content: [Set Git or TFVC repository permissions - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/security/set-git-tfvc-repository-permissions?view=azure-devops#feedback)
* Content Source: [docs/organizations/security/set-git-tfvc-repository-permissions.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/security/set-git-tfvc-repository-permissions.md)
* Product: **devops**
* Technology: **devops-security**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@anmason  - Thank you for the correction. I have updated the article to reflect the way permissions operate.
