### ISSUE TITLE
Not a single one of the quickstart repos contains a YAML file

### ISSUE THREAD

**Issue by Paul-Dempsey** [MicrosoftDocs/vsts-docs#3835]
I'm looking for info on how to set up a YAML pipeline for an existing C# .Net framework app in Azure Devops git, but not getting anywhere, either in the docs, the samples, or the Azure Devops UI.  None of the sample repos contains a .yml file, so I'm pretty lost on how to get started.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 38f7a23b-ebd4-af3e-68a2-275f7e45c33e
* Version Independent ID: f552a18c-ba29-00d4-03b6-254d7556d319
* Content: [Create your first pipeline - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/get-started-yaml?view=azure-devops)
* Content Source: [docs/pipelines/get-started-yaml.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/get-started-yaml.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by jeffpapp** [comment]
Looks like this was removed in https://github.com/MicrosoftDocs/pipelines-dotnet-core/pull/32 for the .Net Core sample.  That seems to reference a wizard which will create a auzre-pipelines.yaml file but I don't see that in the Azure Pipelines UI

**Comment by ernonewman** [comment]
Any updates on this issue from the docs team? I am interested in working through the quickstart, for .Net Core, but can't currently do so.

**Comment by Paul-Dempsey** [comment]
@jeffpapp : This isn't a wizard - just a step-by-step walkthrough of the UI.

**Comment by ernonewman** [comment]
@Paul-Dempsey, the list of changes in the PR referenced by @jeffpapp mentions a wizard.

I suspect it's something the doc team means to add but it's prob still in a private branch.

**Comment by Paul-Dempsey** [comment]
Docs should reflect the shipped features and the shipped (master) branch of the sample.

**Comment by ernonewman** [comment]
In a perfect world, sure, at least we seem to be getting some traction as this issue has been assigned to the dev who made the code change.

For the record, it only seems that the two .NET Core based samples are missing their YAML files, I worked through NodeJS sample without any issues and the Java/Go/Python samples all have their YAML files present.

Also, here's a link to the original YAML file from the .NET Core repo before it was deleted which should allow you to work through that sample: [https://github.com/MicrosoftDocs/pipelines-dotnet-core/blob/3fbf349c0116f4a6c6e6ac7761110044b992666c/azure-pipelines.yml](https://github.com/MicrosoftDocs/pipelines-dotnet-core/blob/3fbf349c0116f4a6c6e6ac7761110044b992666c/azure-pipelines.yml)

Hope that helps.

**Comment by steved0x** [comment]
@Paul-Dempsey The original article has been replaced and redirected to this article:

https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/create-first-pipeline.md

The new content is live here:

https://docs.microsoft.com/en-us/azure/devops/pipelines/create-first-pipeline?view=azure-devops&tabs=tfs-2018-2

If there is no YAML file in the repo, the repo is analyzed and one is generated, and you have a chance to edit it before it is committed to the repo.

I believe these docs are up to date with the current experience, can you check them out and see if it resolves your issue?

**Comment by andyjlewis** [comment]
@Paul-Dempsey, @ernonewman: Thanks for the feedback. @vijayma and I are in the process of removing the YAML pipeline files from the samples so that we can align the docs to pick up where the product leaves off. For example, if you try the .NET Core scenario, you'll see how Azure Pipelines creates the YAML file for you. The product team will continue updating the template that generates that YAML file, so we don't want to have a YAML file in the sample repo that will inevitably get stale.

I've got this work in progress as we speak, so not all the samples and not all the docs are updated yet. In fact, it occurs to me now that I might want to add a links from some of the docs to the relevant templates in case people want to see those: https://github.com/Microsoft/azure-pipelines-yaml/tree/master/templates

So thanks again for this helpful feedback! I'll follow up and leave this issue open until I've copied it to my backlog.

**Comment by andyjlewis** [comment]
copied to backlog

**Comment by Paul-Dempsey** [comment]
I don’t want to sign up for github, clone a sample repo that isn’t the language/project type of my project (4.6.2 .net framework, c#), walk through a bunch of steps just to be able to see and read a working pipeline yaml definition.

 I want to just look at one to see how a particular aspect is done — in my case resolve nuget packages in MY Azure Devops feed (requires authentication), not a public feed.
