### ISSUE TITLE
Should show how to set environment variables as well

### ISSUE THREAD

**Issue by trajano** [MicrosoftDocs/vsts-docs#3839]
The bash and script tasks have the capability of supporting environment variables. Perhaps it can be added to this as well.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 36fff5ec-d766-b589-39ff-9c69ab26dd5b
* Version Independent ID: 12deb045-2511-b5bf-9e41-0d223bef516b
* Content: [Shell Script task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/shell-script?view=azure-devops)
* Content Source: [docs/pipelines/tasks/utility/shell-script.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/utility/shell-script.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by vtbassmatt** [comment]
The script tasks don't take additional environment variables. That's a feature of all steps (whether they're `task`, `bash`, `script`, etc.) and is documented in the [schema](https://docs.microsoft.com/azure/devops/pipelines/yaml-schema).
