### ISSUE TITLE
Where can I change the setting for my process iteration duration?

### ISSUE THREAD

**Issue by Anand-Moghe** [MicrosoftDocs/vsts-docs#3842]
If I am using a Scrum based process for my devops project, where can I alter or customize the iteration duration for my Sprint in Azure DevOps Service? 

I was reviewing the [demo labs](https://www.azuredevopslabs.com/) for Azure DevOps services.
I noticed that when I tried to create a new iteration (sprint), It was selecting 3 weeks by default based on sample examples of boards in PartsUnlimited project sample.

So is it automatically detecting the sprint duration based on existing (previous) sprints?
Or is there a setting somewhere which I can edit to set the default duration of iteration in my DevOps Project?

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 715eca62-8a31-4163-c27b-f5e71d781982
* Version Independent ID: 06dc711f-1946-29e9-aece-75af903da09b
* Content: [Customize the workflow of an inherited process - Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/organizations/settings/work/customize-process-workflow?view=azure-devops)
* Content Source: [docs/organizations/settings/work/customize-process-workflow.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/settings/work/customize-process-workflow.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@Anand-Moghe - You specify the duration of a sprint by setting the Start and End date of the sprint. Described here: [Define iteration paths (aka sprints) and configure team iterations](https://docs.microsoft.com/en-us/azure/devops/organizations/settings/set-iteration-paths-sprints?toc=/azure/devops/organizations/settings/scale/toc.json&bc=/azure/devops/organizations/settings/scale/breadcrumb/toc.json&view=azure-devops). The system detects the pattern you set when you define the dates and prompts the start and end dates for the next sprint you define - however, you can override that and change it at any time.
