### ISSUE TITLE
GitRestClient getPullRequestWorkItems is not a function

### ISSUE THREAD

**Issue by aguacongas** [MicrosoftDocs/vsts-docs#3844]
On local **Team Foundation Server 2018 UPDATE 2**  
I'm trying to use the `GitHttpClient2_2.getPullRequestWorkItems` function in vsts extension:

``` js
VSS.require(["VSS/Service", "TFS/VersionControl/GitRestClient"], function (VSS_Service, TFS_Wit_WebApi) {
        // Get the REST client
        var gitClient = VSS_Service.getCollectionClient(TFS_Wit_WebApi.GitHttpClient2_2);

        gitClient.getPullRequestWorkItems(pr.repositoryId, pr.pullRequestId)
            .then(function(items) {
               // process items
            }, function(error) {
                showError(error.message || "Unknow exception");
            });
    });
```

But I received the error : **getPullRequestWorkItems is not a function**

But `GitHttpClient2_2` has a not documented `getPullRequestWorkItemRefs` function returning:

``` js
[
  {
    id: number
    url: string
  }
]
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 35b914aa-bdf4-0523-9e15-5c1537733c0e
* Version Independent ID: 5ca8376f-10e0-b29c-b93e-ba6e3679b226
* Content: [TFS/VersionControl/GitRestClient GitHttpClient2_2 API](https://docs.microsoft.com/en-us/azure/devops/extend/reference/client/api/tfs/versioncontrol/gitrestclient/githttpclient2_2?view=tfs-2018)
* Content Source: [docs/extend/reference/client/api/TFS/VersionControl/GitRestClient/GitHttpClient2_2.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/extend/reference/client/api/TFS/VersionControl/GitRestClient/GitHttpClient2_2.md)
* Product: **devops**
* Technology: **devops-ecosystem**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by aguacongas** [comment]
The `getPullRequestWorkItems` function doesn't exist on **Azure DevOps Services** but on **TFS 2018 UPDATE 1** 
The `getPullRequestWorkItemRefs` function exists on **Azure DevOps Services** but not on **TFS 2018 UPDATE 1**  
so I path my code with :  
`gitClient.getPullRequestWorkItemRefs = gitClient.getPullRequestWorkItemRefs || gitClient.getPullRequestWorkItems;`

**Comment by chcomley** [comment]
Hi @aguacongas, I've reached out to the product team to find out more and will be in touch. For now, you could reach out to the [Azure DevOps Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html) which is monitored by the product team to see if you can get a solid answer there!

**Comment by chcomley** [comment]
@aguacongas, Here's what you want to be using: “getPullRequestWorkItemRefs” 
This has existed since version 2.0. Make sure you're using the most recent version. Please let us know if you have any further questions. Thanks!

**Comment by aguacongas** [comment]
@chcomley, but the doc mention **getPullRequestWorkItems** not  **getPullRequestWorkItemRefs**, so it has be be fixed IMO.

**Comment by chcomley** [comment]
@aguacongas agreed! I've created a user story on my backlog to address this. Thanks for the feedback!
