### ISSUE TITLE
Is "Removed" state recommended or not?

### ISSUE THREAD

**Issue by jaysnlee** [MicrosoftDocs/vsts-docs#3847]
Hi,

I think the "Removed" state for some of my workflow items (specifically: Epics, Features and User Stories) would be very handy.  However, the article below written on 11/18/2018 warns against using this state as it is being deprecated:

https://docs.microsoft.com/en-us/azure/devops/boards/work-items/workflow-and-state-categories?view=azure-devops

However, this document, which was written afterwards (2/13/2019) talks about using the "Removed" state and makes no mention of the state being deprecated.

What is the should I do here?  Should I use the "Removed" state or is there a recommended alternative?  

Thanks!

Jason

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e9f02cb-f094-d6bc-ca7b-973db9de0082
* Version Independent ID: 1af6a7f5-9e99-ec99-081d-c0bf9e7ac5f5
* Content: [Move, change, delete, or restore user stories, bugs, tasks, and other work items - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/backlogs/remove-delete-work-items?view=azure-devops#feedback)
* Content Source: [docs/boards/backlogs/remove-delete-work-items.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/boards/backlogs/remove-delete-work-items.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@jaysnlee - Thank you for the question. You can use the Removed state as long as it works for you. Even if it becomes deprecated, you'll be able to update your work items you've set to Removed to another state, or simply do a Bulk delete.  I will remove the note for now as there are no plans to remove it at this time.

**Comment by jaysnlee** [comment]
@KathrynEE - Thank you!!
