### ISSUE TITLE
how to enable the "add a template" drop list when creating a Pull request?

### ISSUE THREAD

**Issue by feshe** [MicrosoftDocs/vsts-docs#3849]
[Enter feedback here]
In the doc, I see there is a "add a template" drop down list. However I did not see it when creating a PR. I created the PR template first and tried to apply the template in the middle step of creating PR. But I don't find that option. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a297d54f-48b3-1b68-e828-15d1559d9b2d
* Version Independent ID: fd9dcb35-72f9-f5a9-e0c0-75c3e59ba8d9
* Content: [Improve your pull request descriptions using pull request templates - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/pull-request-templates?view=azure-devops#feedback)
* Content Source: [docs/repos/git/pull-request-templates.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/repos/git/pull-request-templates.md)
* Product: **devops**
* Technology: **devops-code-git**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
@feshe Ensure that the templates are present in one of the approved locations in the default branch (typically master) and then when you create a PR you should see the drop down that lets you specify the templates. Can you verify the branch and name of your PR template?

**Comment by brunomartinspro** [comment]
Tried activating this in VSTS and failed.

Step 1: created a pull request from feature to develop with a template "pull_request_template.md" with the content "Hello world". FAILED
Step 2: added the template to master and created a pull request from feature to develop. FAILED

My version of VSTS is: 
"Microsoft Visual Studio Team Foundation Server
Version 15.117.27414.0"

@steved0x @feshe am i doing something wrong?
Thanks!

**Comment by todomedahueva** [comment]
I had the same issue here the swolution:

You need to create the next path:

Docs/pull_request_template/additional.md

and my default template is at

Docs/pull_request_template.md

best regards.

**Comment by steved0x** [comment]
@feshe @brunomartinspro Do you get your PR templates working? I have been on Azure Pipelines and didn't check the status of this Azure Repos issue. I am sorry for the delay. Please re-activate this issue if you are still having trouble. Thank you.

**Comment by brunomartinspro** [comment]
@steved0x yes, i got it working by having a file "pull_request_template.md" inside a ".azuredevops" folder in the root of the repository. Thanks!

**Comment by henryraygan** [comment]
@brunomartinspro @todomedahueva hello, i have same a problem, but not enable the dropdown option on follow the steps before. 

I am trying in a branch different: feature-2020 so i m not in master or develop, this is a problem? 

if speak spanish, respond in spanish please for community in spanish

**Comment by brunomartinspro** [comment]
> @brunomartinspro @todomedahueva hello, i have same a problem, but not enable the dropdown option on follow the steps before.
> 
> I am trying in a branch different: feature-2020 so i m not in master or develop, this is a problem?
> 
> if speak spanish, respond in spanish please for community in spanish
En mi caso, tener el archivo "pull_request_template.md" en una carpeta ".azuredevops" en la raíz del repositorio de git resolvió el problema.
(Google translator)

**Comment by MonsieurPatate** [comment]
The templates should present in target branch already, so it would not apply if you add template and create pull request at first time. 

> The filenames and folder locations are not case sensitive, but they must be in the default branch of your repository.

I spent a couple of hours to figure it out =)
