### ISSUE TITLE
Download PDF is broken

### ISSUE THREAD

**Issue by BrianMinister** [MicrosoftDocs/vsts-docs#385]
I cannot download this via PDF.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a922f18-55a1-cf8d-732e-8420b5466187
* Version Independent ID: f70e2d11-4920-b88b-92b2-f3124f4ac8d5
* Content: [Continuous Testing](https://docs.microsoft.com/en-us/vsts/build-release/test/?view=vsts#feedback)
* Content Source: [docs/build-release/test/index.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/build-release/test/index.md)
* Service: **unspecified**
* GitHub Login: @douge
* Microsoft Alias: **ahomer**

**Comment by steved0x** [comment]
@BrianMinister PDF download looks like it is down for the whole site, I am filing a support ticket and I'll update you when it is fixed. Thanks for letting us know.

**Comment by steved0x** [comment]
@BrianMinister Our ops team is working the ticket now and should be resolved soon.

**Comment by steved0x** [comment]
@BrianMinister It's fixed, you should be able to download the PDF of the docs for this area (and the other VSTS areas as well). Thanks again for letting us know about this.
