### ISSUE TITLE
Missing any information about feed authentication in Azure Pipelines

### ISSUE THREAD

**Issue by Paul-Dempsey** [MicrosoftDocs/vsts-docs#3850]
One of the basic frequent issues with azure pipelines and nuget feeds (both private and Azue Devops artifact feeds), is feed authentication. This topic and the others in this area are silent on authentication and how to get things to actually work. This is an urgent and critical area that needs addressing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 96561b11-820d-b386-4208-e88e9552f5fc
* Version Independent ID: 42918fea-f9ad-260c-ec38-70254a47de5d
* Content: [.NET Core build and release task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/dotnet-core?view=azure-devops)
* Content Source: [docs/pipelines/tasks/build/dotnet-core.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/build/dotnet-core.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **amullans**

**Comment by infin8x** [comment]
Few things here. In the short term, we should link to https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/nuget?toc=%2Fazure%2Fdevops%2Fartifacts%2Ftoc.json&view=azure-devops&tabs=yaml and its various equivalents for different languages. We have different docs for "on a dev box" and "in Azure Pipelines". @andyjlewis possibly something for Chase to consider later on down the road.

Separately, we're going to make significant updates to the tools and best practices for doing feed authentication in Pipelines. The current spec for that is here: https://github.com/microsoft/azure-pipelines-yaml/blob/users/amullans/artifacts/design/artifacts-in-pipelines.md. We'll want to update the various `pipelines/artifacts/{lang}` docs when that work is getting ready to release.

**Comment by andyjlewis** [comment]
@chasewilson please sync with @infin8x to get this fixed. follow up with me afterward if you want to review potential future story ideas mentioned above

**Comment by chasewilson** [comment]
@Paul-Dempsey < thank you for the feedback. I'm closing this issue as we are removing this page and only using the DotNetCoreCli documentation moving forward. This is great feedback however and will need to update that page. 
I've created a new Issue here and hope to resolve it soon. Thank you again!
