### ISSUE TITLE
(applies to all topics under Tasks in the Reference) Name in Arguments column does not match YAML argument name.

### ISSUE THREAD

**Issue by Paul-Dempsey** [MicrosoftDocs/vsts-docs#3852]
This entire subset of the Pipelines docs is rendered nearly useless for YAML because the name in the "Argument" column is not the actual argument name that must be used in the YAML.  Sometimes you're lucky enough that the YAML snippet contains the argument and you can mostly guess the mapping. But very often the snippet doesn't cover all the arguments, or the mapping from the UI-friendly name to the actual YAML argument name is ambiguous or obscure. These need to match, or there needs to be an additional column containing the actual argument name.

I can't emphasize enough how bad this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e7ba5cf3-d229-03d0-ad6a-a30a0379afc0
* Version Independent ID: ccffed3b-ea44-517f-f7a8-a1c4c4147495
* Content: [Catalog of the built-in tasks for build-release and Azure Pipelines & TFS - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/?view=azure-devops)
* Content Source: [docs/pipelines/tasks/index.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/index.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by andyjlewis** [comment]
@Paul-Dempsey thank you for the feedback. I've added this issue to our backlog.
