### ISSUE TITLE
Missing "Acceptance Criteria" filed on Custom rule

### ISSUE THREAD

**Issue by sureshmvp** [MicrosoftDocs/vsts-docs#3854]
I don't see "Acceptance Criteria" filed on custom rule as mentioned on this article. 

Reference Link : https://docs.microsoft.com/en-us/azure/devops/organizations/settings/work/custom-rules?view=azure-devops

![Missinc Acceptance Criteria](https://user-images.githubusercontent.com/35755657/55520312-57f44500-5641-11e9-8c0e-84dac257e9a8.png)

**Comment by chcomley** [comment]
Hi @sureshmvp, thanks for reaching out. I'm looking into this and will be in touch! Thanks!

**Comment by chcomley** [comment]
@sureshmvp could you please let me know whether the work item type you're trying to add to this rule has “Acceptance Criteria” on the type/layout?
By default, ‘Acceptance Criteria’ field is available in “scrum” process, but the states you have in the screenshot are default states of “agile."
Thanks!

**Comment by sureshmvp** [comment]
Yes, work Item does have "Acceptance Criteria" 
![image](https://user-images.githubusercontent.com/35755657/55661161-c49d4a00-57cf-11e9-992e-dca7bfc386fa.png)
Your right, I did create a custom Agile Process to have different swimline and process. 

Let me know if you have any other questions. 

Thanks
