### ISSUE TITLE
Please clarify mis-leading text re: Azure AD Tenancy

### ISSUE THREAD

**Issue by dburnison** [MicrosoftDocs/vsts-docs#3855]
In the "How many projects do you need?" section the following statement is misleading: 
"At the highest level of isolation is an organization, where each organization has its own Azure AD tenancy."

One customer thought that you needed a new Azure AD tenant for every Azure DevOps organization that was created. 

I would suggest updating the text to something like this:
"At the highest level of isolation is an organization, where each organization is connected to a single Azure AD tenant. NOTE: A single Azure AD Tenant can be connected to many Azure DevOps organizations."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 01770b43-fd5b-efbc-36f5-af91a3c8cf5a
* Version Independent ID: 7c046a91-37f9-32e3-dc3e-dfa922c456be
* Content: [Plan your organizational structure - Azure DevOps - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/user-guide/plan-your-azure-devops-org-structure?view=azure-devops)
* Content Source: [docs/user-guide/plan-your-azure-devops-org-structure.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/user-guide/plan-your-azure-devops-org-structure.md)
* Product: **devops**
* Technology: **devops-new-user**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
@dburnison, this is a fantastic suggestion, thank you. I've made the update and pushed to master. Master is pushed to live multiple times throughout the day, so it'll be live at some point today. Thanks again!

**Comment by dburnison** [comment]
@chcomley Thank you for the quick turn around!
