### ISSUE TITLE
Use all variables in Library variable group 

### ISSUE THREAD

**Issue by jjang3530** [MicrosoftDocs/vsts-docs#3861]
I have a variable group in Library has many variables.
I use these variables in my release pipeline. My script call a variable as an input to a task, wrap it in $(VariableName).
However, if I add new variable in group, I have to add another call a variable in my pipeline script.
$(NewVariable)
Is there anyway to call ALL the variables in Library variable group???

Thanks Advance

**Comment by juliakm** [comment]
There is no way to reference all the variables in a variable group at once. If you would like to suggest this as a feature request, please post to our [Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html).  That site is monitored by our product team.
