### ISSUE TITLE
Duplicate "view and manage work" paragraph

### ISSUE THREAD

**Issue by cschleiden** [MicrosoftDocs/vsts-docs#3863]
This paragraph:

&gt; You can also view and manage work that you're following from Boards&gt;Work Items and pivot to Following.

Is included twice, once above a screenshot, once below.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 50fb5639-2338-9141-1129-682e46676f7f
* Version Independent ID: 5002bb9e-5ec3-d773-2843-8b20468d6c69
* Content: [Track updates by getting notified of changes made to a user story, bug, or other work item or pull request - Azure Boards & Azure Repos](https://docs.microsoft.com/en-us/azure/devops/boards/work-items/follow-work-items?view=azure-devops#feedback)
* Content Source: [docs/boards/work-items/follow-work-items.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/boards/work-items/follow-work-items.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@cschleiden - Thank you for the correction. The topic is being updated.
