### ISSUE TITLE
Its not clear why to use an Issue (rather than say a Task)

### ISSUE THREAD

**Issue by dombat** [MicrosoftDocs/vsts-docs#3865]
There is plenty of description text but it doesn't make clear why to use Issue workitems. Why not use a Task? Is an issue supposed to have child workitems to do the actual work?

OR is it supposed to become a to-do list, so you can have a query of "Issues/Impediments" such as 
* Update SSMS on Server#1
* Get some budget for Tool-X that we need in the next sprint
* Reassign Sallys work to Samij because she is leaving

Maybe some examples like this would be good (if that's what they're for).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f3745d89-ac9e-5365-25b7-4788a3374ae5
* Version Independent ID: 6691cf6d-547b-a12d-f5d7-8ee9c3ff38e0
* Content: [Add and manage issues or impediments - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/backlogs/manage-issues-impediments?toc=%2fazure%2fdevops%2fboards%2fwork-items%2ftoc.json&%3bbc=%2fazure%2fdevops%2fboards%2fwork-items%2fbreadcrumb%2ftoc.json&view=azure-devops)
* Content Source: [docs/boards/backlogs/manage-issues-impediments.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/boards/backlogs/manage-issues-impediments.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@dombat - Thank you for your inquiry. We recommend using tasks when you want to link users stories to tasks to view on a taskboard or as a checklist within the Kanban board. Or, when wanting to track work using Remaining Work. Issues/impediments represent a different type of item to track - usually an event or dependency that needs tracking - but doesn't represent specific work related to the user story.

**Comment by RobertoBorges** [comment]
Still not clear, if an Issue it's a different type of item to track, why we can't track in any board? the only place that the Issue appears is in the Workitem pane.

**Comment by nezoic** [comment]
@RobertoBorges I think I can help as I just had this conversation with my team. We are using Issues specifically when a story is blocked/impeded by some "issue". Example: "Waiting on security for xyz" or "need infrastructure in place for xyz. Anything the prevents a story from being in a "Ready to work" state that is NOT a story dependency is an issue. These are typically things you can assign to someone within the organization but not necessarily on you team.

**Comment by konradsikorski** [comment]
I agree the Issue should be visible on product/sprint backlog
