### ISSUE TITLE
Can templates be used in release pipelines?

### ISSUE THREAD

**Issue by johncrim** [MicrosoftDocs/vsts-docs#3866]
It's clear from this doc that they can be used in build pipelines, but using them from release pipelines would be very helpful. Is there a way to make that work, either today, or in the near future?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6724abea-bbdc-bf66-ed5e-3214fa6c3e66
* Version Independent ID: 4f8dab21-3f0e-da32-cc0e-1d85c13c0065
* Content: [Job and step templates - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/templates?view=azure-devops#feedback)
* Content Source: [docs/pipelines/process/templates.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/templates.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @vtbassmatt
* Microsoft Alias: **alewis**

**Comment by vtbassmatt** [comment]
We're bringing RM's capabilities into the YAML world over the next few quarters. There's not really a hard cutover, so whenever we've brought "enough" of those capabilities into YAML for your use case, you can switch over to using YAML and get templates.
