### ISSUE TITLE
Question / Suggestion : Why do upstream feeds cache for 24 hours?

### ISSUE THREAD

**Issue by awentzel** [MicrosoftDocs/vsts-docs#3868]
If you are submitting your documentation feedback issue directly through GitHub, please provide the URL of the article so we can route the feedback to the correct author.

https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/artifacts/concepts/upstream-sources.md

It's great to see [Benefits of upstream sources](https://docs.microsoft.com/en-us/azure/devops/artifacts/concepts/upstream-sources?view=azure-devops#benefits-of-upstream-sources).  Though I think directly after that you should include Drawbacks of upstream sources.  For which, I think think the 24 hour caching period would be better suited.

Recommend moving [this entire section](https://docs.microsoft.com/en-us/azure/devops/artifacts/concepts/upstream-sources?view=azure-devops#metadata-cached-from-upstream-sources) to directly after "Benefits of upstream sources" 

Also, It's nice to understand Why something is cached when it obviously can impact your release strategy. Especially, for private upstream feeds that you may have published for a feature request and now someone has to wait 24 hours to install.  Just doesn't feel like a real world scenario.  Things are built and deployed on the web in minutes not hours or days.

Should I file a bug or feature to request an setting that turns off caching? Is this even possible?

**Comment by chcomley** [comment]
Hi @awentzel, Thanks for your input! I'm following up on this and will be in touch. Thanks again for reaching out!

**Comment by elbatk** [comment]
Hi @awentzel , I'm having trouble understanding your scenario here. 

Why do you consider package caching from upstream sources a bad thing? We keep metadata from packages from upstream sources for up to 24 hours, in an effort to keep your builds working that rely on those packages even if that public source (nuget.org, npmjs, etc.) goes down.

If you're talking about the delay between when a package is pushed to an upstream source and when a feed has access to it, that delay is around 3 hours today (refreshed every 3 hours), and it's something that our team is actively working on getting down.

**Comment by chcomley** [comment]
Thanks for your feedback, @awentzel. I'll be closing this issue today. Here's a link to submit an idea, if you'd like: https://developercommunity.visualstudio.com/content/idea/post.html?space=21. If you have any further feedback, please do share. Thanks very much!
