### ISSUE TITLE
Clarify configuring NuGet tools

### ISSUE THREAD

**Issue by dan-meier** [MicrosoftDocs/vsts-docs#3870]
Within the "Publish a package" section, item 3 states, "Follow steps 1, 2, and 3 to get the tools, add the feed to your local NuGet configuration, and push the package."  The steps mentioned are highlighted in the accompanying screen shot.  However, the download package contains no instructions for what to do with the pieces inside.  It'd be helpful to provide instructions and best-practices for what to do with the two .exe files in this download, especially with respect to credentials.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a10a409-5468-9532-f0dc-5a28cdd566d8
* Version Independent ID: 2ef20266-bc45-448b-27f5-e5c3bffed2ef
* Content: [Get started with NuGet packages in Azure DevOps Services and TFS](https://docs.microsoft.com/en-us/azure/devops/artifacts/get-started-nuget?view=azure-devops)
* Content Source: [docs/artifacts/get-started-nuget.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/artifacts/get-started-nuget.md)
* Product: **devops**
* Technology: **devops-artifacts**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by chcomley** [comment]
Hi @dan-meier, thanks for the suggestions and sorry for any troubles. I'm following up with the product team and will be in touch. Thanks! In the meantime, you could also reach out to the [Azure DevOps Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html), which is monitored by the product team, to see if you can get any advice!

**Comment by chcomley** [comment]
@dan-meier, The idea behind that zip file is that you unpack it to your local disk and run nuget.exe like what is shown in the step (the zip file contains nuget.exe). In terms of best practices, you would probably want to download the files to a directory on your machine where you keep utilities and then add it to your path. 
I've created a user story to capture the revision of this article for my backlog. Thank you.

**Comment by chasewilson** [comment]
@dan-meier , thanks for the input. I'm updating the page to reference the NuGet Documentation and you should see it live within the next 24 hours. I'll be closing the issue for now but if you have any more questions or feedback, you'll reach out or open a new issue. :)
