### ISSUE TITLE
Unclear how to call updatePullRequest()

### ISSUE THREAD

**Issue by m-akinc** [MicrosoftDocs/vsts-docs#3872]
I'm running into CORS issues when trying to call updatePullRequest(). I can call getPullRequest() just fine, but calling updatePullRequest() is giving me the following errors:

PATCH &lt;my pull request url&gt; 401

Access to XMLHttpRequest at '&lt;my pull request url&gt;' from origin 'https://ni.gallerycdn.vsassets.io' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 35b914aa-bdf4-0523-9e15-5c1537733c0e
* Version Independent ID: 5ca8376f-10e0-b29c-b93e-ba6e3679b226
* Content: [TFS/VersionControl/GitRestClient GitHttpClient2_2 API](https://docs.microsoft.com/en-us/azure/devops/extend/reference/client/api/tfs/versioncontrol/gitrestclient/githttpclient2_2?view=azure-devops#feedback)
* Content Source: [docs/extend/reference/client/api/TFS/VersionControl/GitRestClient/GitHttpClient2_2.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/extend/reference/client/api/TFS/VersionControl/GitRestClient/GitHttpClient2_2.md)
* Product: **devops**
* Technology: **devops-ecosystem**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by willsmythe** [comment]
Does your extension manifest have the `vso.code_write` scope? (not just `vso.code`)?

**Comment by m-akinc** [comment]
It didn't, and that was the cause of my CORS error. Thanks! But I've hit another block. I'm trying to change reviewer votes. I've tried passing in an object that only has a reviewers member (with reviewer objects copied from the pull request). I've also tried just updating the votes in the pull request object and passing the whole thing in. In both cases, I get the same error: 
```TFS.WebApi.Exception: Invalid argument value.
Parameter name: You can only update reviewers, descriptions, titles, merge status, and status.```
I found some posts that make me wonder if the error is misleading, and it's actually not possible to modify reviewers (votes) via `updatePullRequest`. https://developercommunity.visualstudio.com/content/problem/388569/rest-api-docs-and-and-error-message-suggest-pr-pat.html

Any help would be appreciated. The documentation could definitely benefit from some examples and caveats.

**Comment by m-akinc** [comment]
I was able to successfully reset a reviewer's vote with `createPullRequestReviewer()`, though, surprisingly, not `createPullRequestReviewers()`. I was hoping I could reset multiple in one batch call, but that doesn't seem to be supported.

**Comment by chcomley** [comment]
Hi @m-akinc, Following up on this issue, it appears that your issues have been resolved. Please let me know if you have any further questions. I've created a user story on my backlog to capture updating this doc with some examples, so thank you for the feedback!

**Comment by LockTar** [comment]
Setting the correct scope of the extension helped me to solve the CORS problem from 'https://gallerycdn.vsassets.io'
