### ISSUE TITLE
The details, examples and simple explanation  

### ISSUE THREAD

**Issue by tahiralvi** [MicrosoftDocs/vsts-docs#3875]
Last week I was assigned a task to test the application which are deployed on Azure for load test. I start finding out the ways recommended by the Microsoft. I came across this page about the Http Archive testing which at least i am not familiar with before this week.

It help me a lot, especially for the apps which used dynamic parameters during its run. Off course all load test perform on the Azure portal. I finished my task earlier and got other advance topic knowledge during that phase.

I would like to appreciate to the Microsoft Team who write and compile this documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 46fb478b-e602-c911-28bb-2dc9c9d50b79
* Version Independent ID: d830b560-3735-1c43-49b9-431ea73814bc
* Content: [Record and replay load tests - Azure Test Plans](https://docs.microsoft.com/en-us/azure/devops/test/load-test/record-and-replay-cloud-load-tests?view=azure-devops)
* Content Source: [docs/test/load-test/record-and-replay-cloud-load-tests.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/test/load-test/record-and-replay-cloud-load-tests.md)
* Product: **devops**
* Technology: **devops-test**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by thomps23** [comment]
Thank you for your feedback. We appreciate getting the opportunity to hear how the Azure DevOps documentation has made a customer's job easier :)
