### ISSUE TITLE
Hosted Python libraries on Linux are not compiled with the shared option

### ISSUE THREAD

**Issue by bencefr** [MicrosoftDocs/vsts-docs#3876]
This issue prevents building C extension modules for python.

/usr/bin/ld: /opt/hostedtoolcache/Python/2.7.15/x64/lib/python2.7/config/libpython2.7.a(abstract.o): relocation R_X86_64_32 against `.rodata.str1.8' can not be used when making a shared object; recompile with -fPIC

Same for all versions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e765cfad-8ab9-443a-1171-5af81a31252f
* Version Independent ID: 8ff69d93-0128-dbeb-9d63-45266ed73020
* Content: [Use Python Version task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/use-python-version?view=azure-devops#feedback)
* Content Source: [docs/pipelines/tasks/tool/use-python-version.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/tool/use-python-version.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **brcrista**

**Comment by steved0x** [comment]
@bencefr Thank you for your feedback. We are going to move this issue to here: https://github.com/Microsoft/azure-pipelines-image-generation

/move to Microsoft/azure-pipelines-image-generation

**Comment by steved0x** [comment]
@bencefr Sorry about that, we had a glitch, I'm getting that fixed and we'll get your issue moved shortly.
