### ISSUE TITLE
No way to convert on-premises XML process collections (yet)

### ISSUE THREAD

**Issue by jonatan-comfact** [MicrosoftDocs/vsts-docs#3878]
This documentation page states that there is no way to migrate on-premises XML process based collections. This makes it sound like there never will be, perhaps prompting teams to undergo a difficult manual migration process when they would have been content with waiting.

According to [this](https://developercommunity.visualstudio.com/idea/365391/allow-for-updating-process-templates-on-existing-p.html) developer community entry, the functionality to migrate On-premise XML process model collections to the inheritance base process model is on the roadmap.

Is there a way to include information about this in the documentation page?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f1152275-e1e9-cad2-4b6d-e7bab8ed1b74
* Version Independent ID: 231b91a8-c5ac-36db-e2ae-8d837fb70e4b
* Content: [Customize your work tracking experience - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/reference/customize-work?view=azure-devops-2019#feedback)
* Content Source: [docs/reference/customize-work.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/reference/customize-work.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by Oxymoron290** [comment]
Is there any update on this functionality?

**Comment by Oxymoron290** [comment]
it would appear a month after dan's comment here, the decision was made that this would be removed from the roadmap. https://developercommunity.visualstudio.com/t/bring-inherited-process-to-existing-projects-for-a/614232#T-N717611
