### ISSUE TITLE
Build app with extension

### ISSUE THREAD

**Issue by rajeshaz09** [MicrosoftDocs/vsts-docs#3879]
Thank you for your feedback!

The issues in this repo are for documentation feedback.

If you are submitting your documentation feedback issue directly through GitHub, please provide the URL of the article so we can route the feedback to the correct author.

Please report Azure DevOps or TFS software bugs, feedback, or questions in the [Azure DevOps Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html).

**Comment by thomps23** [comment]
@rajeshaz09 it looks as if the URL to the topic you are providing feedback on did not get included in your filed Issue. If this is a content issue could you please provide the topic and comments/suggestions?

If this is a request support you can create a new post in the community [here](https://developercommunity.visualstudio.com/spaces/21/index.html).
