### ISSUE TITLE
CV monikers not being compiled

### ISSUE THREAD

**Issue by gumgl** [MicrosoftDocs/vsts-docs#388]
e.g.
> ::: moniker range=">= tfs-2018"

This is also showing outside of corpnet.
Looks like it is due to this commit: 959e797ca6dc365db0b428ba991895ef3b98f3bf

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 63e81f8a-e33c-afb7-493b-f51f40fafd49
* Version Independent ID: c9495a96-c3e8-00f1-1e53-da6ce584412b
* Content: [Syntax usage for Markdown files, widgets, wikis, and pull requests - VSTS & TFS](https://docs.microsoft.com/en-us/vsts/collaborate/markdown-guidance?view=vsts#links)
* Content Source: [docs/collaborate/markdown-guidance.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/collaborate/markdown-guidance.md)
* Service: **unspecified**
* GitHub Login: @douge
* Microsoft Alias: **kaelli**

**Comment by steved0x** [comment]
@gumgl Thanks for letting us know, we'll get these fixed up.

**Comment by KathrynEE** [comment]
@gumgl - Yes, thanks for the alert. The topic has been updated and fixed.
