### ISSUE TITLE
permission to Add external users to your organization

### ISSUE THREAD

**Issue by nikoNguyen** [MicrosoftDocs/vsts-docs#3882]
This doc says :
"You must be a member of the Project Collection Administrators group for the organization that you want to invite external users to"
I tested it , and you just need to be "Project Administrator" to invite External users" from the Team project "overview" page
is it the doc that is wrong OR the application that has a bug ?

---
#### Détails du document

⚠ *Ne pas modifier cette section. Elle est requise pour docs.microsoft.com ➟ problème de liaison GitHub.*

* ID: b6db4fba-7322-16bc-3431-6b8f933a84bf
* Version Independent ID: a20bd1b0-06d7-8f49-30d2-25c5e188b674
* Content: [Add, invite external users, guest users to your organization - Azure DevOps Services](https://docs.microsoft.com/fr-ca/azure/devops/organizations/accounts/add-external-user?view=azure-devops&viewFallbackFrom=vsts#feedback)
* Content Source: [docs/organizations/accounts/add-external-user.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/accounts/add-external-user.md)
* Product: **devops**
* Technology: **devops-accounts**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @nikoNguyen, I'm confirming with the product team and will be in touch soon. Thanks for reaching out!

**Comment by chcomley** [comment]
Hi @nikoNguyen, The doc has been updated and should be live sometime today, as Project Admins can also add external users. The difference between Project Admin and PCA is that Project Admins can't change user licenses. Because of you, I learned something new today! Thanks very much for reaching out!
