### ISSUE TITLE
Publish a Universal Package with Legacy URL has wrong syntax

### ISSUE THREAD

**Issue by 13thsymphony** [MicrosoftDocs/vsts-docs#3885]
The example command given is:

az artifacts package universal publish --organization https://fabrikam.visualstudio.com --feed FabrikamFiber --name my-first-package --version 1.0.0 --description "Your description" --path .

But the 'package' keyword is incorrect and should be deleted.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77bcd39f-91ab-bb93-40fc-dd4fc5f2374f
* Version Independent ID: c228aece-669a-57d6-b3ed-d427586f8a61
* Content: [Publish and then download a Universal Package](https://docs.microsoft.com/en-us/azure/devops/artifacts/quickstarts/universal-packages?view=azure-devops&tabs=vsts#publish-a-universal-package)
* Content Source: [docs/artifacts/quickstarts/universal-packages.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/artifacts/quickstarts/universal-packages.md)
* Product: **devops**
* Technology: **devops-artifacts**
* GitHub Login: @alexmullans
* Microsoft Alias: **amullans**

**Comment by mitchdenny** [comment]
Thanks for reporting the issue, its in PR #3894

**Comment by alexmullans** [comment]
Resolved by @mitchdenny's PR
