### ISSUE TITLE
Custom task is not showing up in https://dev.azure.com/{organization}/

### ISSUE THREAD

**Issue by yijiamicrosoft** [MicrosoftDocs/vsts-docs#3886]
I have followed the document to create a draft of custom task. And in the marketplace.visualstudio.com, I shared it under msazure which is the place host our project. However, I cannot find the task when I create a new build pipeline. Is there any step I missed?

Thanks,
Yiming

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 44581f4a-93df-7507-3844-eadedf9a6cc4
* Version Independent ID: 33c7bcf0-1512-975f-5ef8-9f2a192a84ad
* Content: [Add a Build or Release Task](https://docs.microsoft.com/en-us/azure/devops/extend/develop/add-build-task?view=azure-devops)
* Content Source: [docs/extend/develop/add-build-task.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/extend/develop/add-build-task.md)
* Product: **devops**
* Technology: **devops-ecosystem**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by chcomley** [comment]
Hi @yijiamicrosoft, I'm looking into this and will be in touch. Thanks for reaching out!

**Comment by chcomley** [comment]
@yijiamicrosoft, I've been told that you've been helped internally. But to complete the answer, once it is shared with an organization an organization admin or a user with extension management rights needs to then install the extension into the organization.  There will be a link to install it from the extension management tab on organization settings view. Thanks!
