### ISSUE TITLE
How do I use a variable to define the name of my release?

### ISSUE THREAD

**Issue by SinghManvir** [MicrosoftDocs/vsts-docs#3887]
Assuming that my source alias is '_Foo API - CD Build', I am trying to change the name of the release to Release - $(Release.Artifacts._Foo.API.-.CD.Build.BuildNumber). But it does not resolve to anything. In my release logs, I can see that the same appears as a variable with correct value. Is the above possible?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 611642f0-881f-10b9-ae94-3c562001d1f0
* Version Independent ID: 41efb94b-4c7a-64a3-b23b-70c8634ae727
* Content: [Release variables  and debugging - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/variables?view=azure-devops&tabs=batch#feedback)
* Content Source: [docs/pipelines/release/variables.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/release/variables.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by amclin** [comment]
Same question, I'm trying to use `${Build.BuildId}` or `$(Build.BuildId)` but those strings show up in the release name instead of the values.

**Comment by jijohn14** [comment]
There is limited variables available for defining release name. You will have to use $(Build.BuildNumber). I opened an [issue ](https://developercommunity.visualstudio.com/content/problem/531739/buildsourcebranchname-pre-defined-variable-not-sub.html)related to this as well.

Refer below link to see the list.
https://docs.microsoft.com/en-us/azure/devops/pipelines/release/index?view=azure-devops#how-do-i-manage-the-names-for-new-releases

**Comment by RoopeshNair** [comment]
You need to use $(Build.BuildNumber). For other supported variables check this [link](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/index?view=azure-devops#how-do-i-manage-the-names-for-new-releases)
