### ISSUE TITLE
Poor, very poor.

### ISSUE THREAD

**Issue by Korporal** [MicrosoftDocs/vsts-docs#3889]
This page is close to useless. It refers to downloading NuGet + VSTS Credential Provider - but says nothing about what to do with these once downloaded or where to put the downloaded files. I simply cannot comprehend why this publishing capability is not accessible with a few mouse clicks in the GUI, why oh why oh why is it considered acceptable to have this gap in how nuget is supported? 

The article glibly refers to "run these commands" as if this was a GUI mouse click, it isn't. How do we run those commands? do I open a console window? if so where? what folder must I be in when I run the commands? What if the .exe isn't found? must I edit my path environment variable? etc, etc, etc...

I had hoped that Visual Studio 2019 would make this easy, after all it has a dedicated "Package" property window in my .Net Standard project and I can right-click a project and choose "Pack" and then...well that's it - I must then trawl the web, open power shell windows, struggle with poor documentation and fumble along. After all that I have to explain to my coworkers how I did the publish!!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec99483d-828e-093b-a5af-bd2d25ea27d1
* Version Independent ID: 36f67ced-654b-3cbb-2f4e-4f7b540959ba
* Content: [Publish a NuGet package from the command line](https://docs.microsoft.com/en-us/azure/devops/artifacts/nuget/publish?view=azure-devops)
* Content Source: [docs/artifacts/nuget/publish.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/artifacts/nuget/publish.md)
* Product: **devops**
* Technology: **devops-artifacts**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by alexmullans** [comment]
Thank you for the feedback. We know the experience here is way out-of-date, and the docs aren't far ahead. We're working right now on an updated design for the "Connect to feed" dialog that we hope to have rolled out (along with updated docs) by the end of Q2.

**Comment by Korporal** [comment]
@alexmullans - Thank you Alex, this is very encouraging!

**Comment by MarkSFrancis** [comment]
Would it be helpful to add links to the page for how to create and publish a NuGet package in [dotnet and NET Standard](https://docs.microsoft.com/en-us/nuget/quickstart/create-and-publish-a-package-using-the-dotnet-cli) and NET Framework [using Visual Studio](https://docs.microsoft.com/en-us/nuget/quickstart/create-and-publish-a-package-using-visual-studio-net-framework), or [using the nuget CLI](https://docs.microsoft.com/en-us/nuget/create-packages/creating-a-package)?

This way, someone could follow the guide to create the package, then come back to this guide to publish the package. This publish topic is only relevant immediately after following a guide to create a package, so it makes sense to link the two.

The linked articles cover both creating and publishing the nuget packages, so you'd want to only want to follow the parts that define creating the package, then come back to these docs to publish it to Azure Artifacts.

**Comment by jariwalaraj** [comment]
Agreed.

Below steps worked for me while posting a package to internal Azure Artifacts. 
1. Opened Package manger in VS 2019. (had 2.2.401 installed)
2. Ran command 
PM>  dotnet nuget push "*Path where your .nupkg file exists*" --source "*Your Package source URL*" -k AzureDevOps --interactive
3. It should display a unique code, which you have to provide by going to 'https://microsoft.com/devicelogin' from browser. 

This should authenticate your VS for future push as well.

**Comment by bwirt** [comment]
Thanks jariwalaraj.  This helped me.

**Comment by ahaynes-gw** [comment]
> Thank you for the feedback. We know the experience here is way out-of-date, and the docs aren't far ahead. We're working right now on an updated design for the "Connect to feed" dialog that we hope to have rolled out (along with updated docs) by the end of Q2.

"End of Q2."-- It's September.

@jariwalaraj This didn't work for me. Instead of getting a unique code, I simply got a 401 unauthorized. "Unable to load the service index for source..."

**Comment by ramiMSFT** [comment]
@Korporal Thank you for your feedback. An updated version of the article will be deployed shortly.
