### ISSUE TITLE
How do I transfer my project to a new organization

### ISSUE THREAD

**Issue by truedat101** [MicrosoftDocs/vsts-docs#3890]
Please document how to transfer a Project from one organization to a new organization.  This is a standard capability that is useful, and it would be nice to have this include the tasks/boards in addition to the source code.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 527651eb-b068-313d-9a1f-78f5613b1d7a
* Version Independent ID: a8b55dcd-c261-5eed-edfc-6a4e74b2caee
* Content: [Add and manage projects to support collaboration on software development - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/projects/?view=azure-devops)
* Content Source: [docs/organizations/projects/index.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/projects/index.md)
* Product: **devops**
* Technology: **devops-accounts**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @truedat101, Thanks for your feedback. I've created a user story on my backlog to address this. Thanks again!

**Comment by chcomley** [comment]
Hi @truedat101, Looks like this one got away from me. I still have the User story, however I've discovered that there is no built in functionality for moving projects between organizations. This is a highly requested item on the developer community site, so I recommend going [here](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdevelopercommunity.visualstudio.com%2Fcontent%2Fidea%2F365365%2Fmake-it-possible-to-move-a-team-project-between-te-1.html&data=02%7C01%7CChrystal.Comley%40microsoft.com%7C370bc1f8d9b648a08d6608d709605ab0%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636988181744804357&sdata=hYaeyeFmDKybcjEibN4F8PSe%2FNmP2CroblU3VYbQuHU%3D&reserved=0) to upvote this feature request! Thanks very much!
