### ISSUE TITLE
Deleting builds/pipelines

### ISSUE THREAD

**Issue by stofte** [MicrosoftDocs/vsts-docs#3897]
Is quite troublesome, please add steps that provide hints such as what artifacts are preventing deletion, etc. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a614791-0c5d-4373-3194-11695e40e1d1
* Version Independent ID: 737e5a3b-d7be-9d36-7b5a-638976406d74
* Content: [Delete, remove project - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/projects/delete-project?view=azure-devops)
* Content Source: [docs/organizations/projects/delete-project.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/projects/delete-project.md)
* Product: **devops**
* Technology: **devops-accounts**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
@stofte, thanks for your feedback. I've created a user story for my backlog to address your feedback. Thanks very much!

**Comment by andyjlewis** [comment]
confirmed it's on the backlog
