### ISSUE TITLE
Accepting invitation e-mail seems to be a hard requirement

### ISSUE THREAD

**Issue by mcetkovsky** [MicrosoftDocs/vsts-docs#390]
Docs states:
What if new team members don't receive or lose the invitation email? You can just send a link to the project page to the new team members, which is what the email contains.

User actually gets:
Sorry, but [user name and email] (Microsoft Account) is not auhtorized to access this page because they have not yet accepted the [organization] organization invitation email.
VS403318: [email] has not accepted the invitation to the [organization] organization.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f7bc86e-59a7-962c-a79c-4cc91830e0b1
* Version Independent ID: 9cbd3555-6949-aac6-8d0e-48ddd315eaba
* Content: [VSTS - Add team project members](https://docs.microsoft.com/en-us/vsts/accounts/add-team-members-vs?view=vsts)
* Content Source: [docs/accounts/add-team-members-vs.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/accounts/add-team-members-vs.md)
* Service: **unspecified**
* GitHub Login: @douge
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
@mcetkovsky Thank you for your feedback, I've updated this topic for better clarity. A fix for this is on our backlog.
