### ISSUE TITLE
Broken link to Stakeholder vs Basic feature matrix

### ISSUE THREAD

**Issue by aaron-11** [MicrosoftDocs/vsts-docs#3901]
Under the related articles section of this page, the link to the Stakeholder vs Basic feature matrix is broken: https://visualstudio.microsoft.com/team-services/compare-features/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17e7fef2-40df-4923-e62e-74ac556cbc6a
* Version Independent ID: af9269b4-1db4-df1f-2520-78ad20baf17b
* Content: [Get started with Stakeholder access - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/security/get-started-stakeholder?view=azure-devops#feedback)
* Content Source: [docs/organizations/security/get-started-stakeholder.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/security/get-started-stakeholder.md)
* Product: **devops**
* Technology: **devops-new-user**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@aaron-11 - Thank you for the correction. I'm updating the topic.
