### ISSUE TITLE
YAML snippet documents a pipeline value, Arguments mentions pipelineId

### ISSUE THREAD

**Issue by kzu** [MicrosoftDocs/vsts-docs#3903]
Which one is it then? It's unclear.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b03d67d0-8738-72e6-dbe7-324c1784d4fc
* Version Independent ID: bbb4d774-cd98-3ecb-7ccf-5f49e6f2b425
* Content: [Download Pipeline Artifact task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/download-pipeline-artifact?view=azure-devops#feedback)
* Content Source: [docs/pipelines/tasks/utility/download-pipeline-artifact.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/utility/download-pipeline-artifact.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **midenn**

**Comment by d3r3kk** [comment]
From using this, and checking the code in the task, it is indeed pipelineId and not pipeline (name). Docs need to be updated, or code needs to be updated, or both.

**Comment by chasewilson** [comment]
Hi @kzu and @d3r3kk. Thank you both for the feedback and input. I've recently updated with the current, correct guidance as well as an update coming today with examples. I'm going to close this issue. However, if you have any more feedback, feel free to open a new issue!
