### ISSUE TITLE
Batch variable upload

### ISSUE THREAD

**Issue by Omarmtz** [MicrosoftDocs/vsts-docs#3905]
Is there a way to upload a batch of variables in the variable group editor?
As many applications sometimes have multiple variables, It would be very usefull to write a string of multiple var = value or maybe a file...
Thank you!.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4827aa99-ae62-bd63-6f2f-a87a4065ed27
* Version Independent ID: c9e461ee-7f42-3503-9460-18fa3a807bbb
* Content: [Variable groups for Azure Pipelines and TFS - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/library/variable-groups?view=azure-devops&tabs=yaml#feedback)
* Content Source: [docs/pipelines/library/variable-groups.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/library/variable-groups.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by nikhil2007rock** [comment]
Any update on this requirement? This is pretty much needed and is awaited!

**Comment by iharrington** [comment]
Upload a config.yml would be nice!

**Comment by RoopeshNair** [comment]
Please share your suggestions on [developer community](https://developercommunity.visualstudio.com/spaces/21/index.html) > suggest a feature.
