### ISSUE TITLE
Filter by Date only works on Committed Date

### ISSUE THREAD

**Issue by keremispirli** [MicrosoftDocs/vsts-docs#3909]
On TFS 2018 RTW (16.122.27102.1), when I want to see the commit history between certain dates, commits are searched w.r.t. their Committed Date's i.s.o. Authored Date's, even though the dates I see in the history page are Authored Date's. It may be good to include this information on this page, unless it is changed in newer versions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6de6ffd-afcc-17f9-8e89-6845c0a5bd6c
* Version Independent ID: caea7004-b42b-9084-befc-6b33168570b4
* Content: [View commit history - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/commit-history?view=azure-devops)
* Content Source: [docs/repos/git/commit-history.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/repos/git/commit-history.md)
* Product: **devops**
* Technology: **devops-code-git**
* GitHub Login: @steved0x
* Microsoft Alias: **sancha**

**Comment by apawast** [comment]
Hi @keremispirli. Thank you for pointing this out. I will clarify with this information in the docs and we have added an item to our backlog to make the UI more clear as well.
