### ISSUE TITLE
Guest are also allowed not only members 

### ISSUE THREAD

**Issue by PrateekChaudharyDevOps** [MicrosoftDocs/vsts-docs#391]
Under heading "How does Azure AD control access to VSTS?" in first line It says "directory so that only users who are members " 

I think this can create confusion, it should say " users who are members or guest in that directory..."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a13b33d2-ea72-cc70-4572-f65ad9f357d6
* Version Independent ID: 502c6ac4-320b-41b6-21d5-cd66072fa9ef
* Content: [VSTS - Access with Azure AD](https://docs.microsoft.com/en-us/vsts/accounts/access-with-azure-ad?view=vsts#how-does-azure-ad-control-access-to-vsts)
* Content Source: [docs/accounts/access-with-azure-ad.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/accounts/access-with-azure-ad.md)
* Service: **unspecified**
* GitHub Login: @douge
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
@PrateekChaudharyDevOps  Thanks for the update! I've added this detail to the topic and it should be live online sometime today.
