### ISSUE TITLE
YAML-based PR triggers do not work for Azure Repos

### ISSUE THREAD

**Issue by reynoldsbd** [MicrosoftDocs/vsts-docs#3911]
According to [this report](https://developercommunity.visualstudio.com/content/problem/402133/yaml-definition-does-not-work-with-pull-requests.html), YAML-based PR triggers do not work if the Git repo is hosted on Azure Repos. Would it make sense to document that fact on this page?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5673ec1-c7d1-e0ac-043a-8fc3d5b226a9
* Version Independent ID: b4872831-51c0-6cf8-1c56-de20beb38a80
* Content: [Build pipeline triggers - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/triggers?view=azure-devops&tabs=yaml#feedback)
* Content Source: [docs/pipelines/build/triggers.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/build/triggers.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
@reynoldsbd You are correct, when hosting your code in Azure Repos Git, PR triggers don't work, but you can use branch policies to achieve the same result. I have updated our documentation to make that more clear and it should be live later today. Thanks for letting us know and sorry that you ran into trouble.
