### ISSUE TITLE
Change "Privacy URL" to "Privacy Policy URL"

### ISSUE THREAD

**Issue by securestep9** [MicrosoftDocs/vsts-docs#3912]
Privacy URL Doesn't make sense - please change to either "Privacy Policy URL" or "Privacy Notice URL" as per GDPR regulations

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 05b491f8-3ab7-1d68-5fa9-82ae62852bee
* Version Independent ID: 33bf9215-4e69-520a-3283-066a2c2f2478
* Content: [Add privacy URL for your organization to comply with the GDPR - Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/add-privacy-url?view=azure-devops)
* Content Source: [docs/organizations/accounts/add-privacy-url.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/accounts/add-privacy-url.md)
* Product: **devops**
* Technology: **devops-accounts**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Thanks for this, @securestep9. I've published the update. https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/add-privacy-policy-url?view=azure-devops
