### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by prasalia** [MicrosoftDocs/vsts-docs#3916]
For job dependencies based on variables set by another job, 

"echo ##vso[task.setvariable variable=skipsubsequent;isOutput=true]false"

should be changed to 

echo "##vso[task.setvariable variable=skipsubsequent;isOutput=true]false"

else it doesn't work

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f151218-9a11-0078-e038-f96198a76143
* Version Independent ID: 09c4d032-62f3-d97c-79d7-6fbfd89910e9
* Content: [Conditional tasks - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/conditions?view=azure-devops&tabs=yaml#feedback)
* Content Source: [docs/pipelines/process/conditions.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/conditions.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by vtbassmatt** [comment]
Fixed, pending PR and publish
