### ISSUE TITLE
When using an inline script, I can't see any output when running a release pipeline

### ISSUE THREAD

**Issue by jmoralesv** [MicrosoftDocs/vsts-docs#3919]
Hello, I'm using this Azure PowerShell task (task version 3) to run an inline script which tries to start some virtual machines in Azure, depending on whether their status is running or not. 

The inline script has Write-Output statements which work fine when running on my local machine (Windows 10 and Windows PowerShell), but the release pipeline doesn't show any output from the script. It just shows the message "Waiting for console output from an agent...". 

Is there a way to make the pipeline display the Write-Output messages correctly while running it? 

Thanks,
Jorge

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fb215324-b1a0-93b5-5022-4bcc7da93bb7
* Version Independent ID: 9eb2977b-ac34-9d53-670e-04fa027bc8e4
* Content: [Azure PowerShell task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-powershell?view=azure-devops)
* Content Source: [docs/pipelines/tasks/deploy/azure-powershell.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/deploy/azure-powershell.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **dastahel**

**Comment by jmoralesv** [comment]
Any comment on this, please?

**Comment by vtbassmatt** [comment]
This isn't a doc bug (and it isn't in my area, so I'm not sure what's happening). Please file an issue on [Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html).
