### ISSUE TITLE
Authentication using PAT for Azure DevOps GIT Rest API

### ISSUE THREAD

**Issue by nikhilepicor** [MicrosoftDocs/vsts-docs#3926]
See https://github.com/MicrosoftDocs/vsts-docs/issues/2455#issuecomment-439503194. I learnt that by using the URL in the form "https://&lt;user&gt;:&lt;PAT&gt;@dev.azure.com/..." I can do a git clone with no extra headers or authentication. 
I wanted to do the same thing with the REST API to access Items (See Items Rest API https://docs.microsoft.com/en-us/rest/api/azure/devops/git/items/get?view=azure-devops-rest-5.0). 
For example, I want to authenticate the following API call using the above way if possible -
GET https://dev.azure.com/{organization}/{project}/_apis/git/repositories/{repositoryId}/items?path={path}&api-version=5.0

Is it possible, or am I misinformed about this possibility?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 53f99d2d-363b-d01d-039d-4fdc636fa2df
* Version Independent ID: f47330d5-e2de-36a4-e5b3-5bc77505b161
* Content: [Authenticating with personal access tokens](https://docs.microsoft.com/en-us/azure/devops/integrate/get-started/authentication/pats?view=azure-devops&viewFallbackFrom=vsts#feedback)
* Content Source: [docs/integrate/get-started/authentication/PATs.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/integrate/get-started/authentication/PATs.md)
* Product: **devops**
* Technology: **devops-ecosystem**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by lusocoding** [comment]
Similiar issue here when trying to use PAT to authorize the creation of a new release. I'm trying to make a POST to https://vsrm.dev.azure.com/{organizationId}/{projectId}/_apis/Release/releases?api-version=5.0 with the header "Authorization: Basic {BASE64 Encoded Token}" (similiar code as example above). I'm always getting a 203 Non-Authorative response, even after adding full permissions to the PAT in use. Can someone help with this?

**Comment by chcomley** [comment]
Hi @nikhilepicor and @lusocoding, I've engaged one of our experts, @JimsonChalissery , so he should be able to help you shortly. Thank you!

**Comment by JimsonChalissery** [comment]
Some tools like Postman apply base64 encoding by default. SoiIf you are trying the APIs via tools like Postman there is no need to apply base64 encoding. Try this and see it that helps.

**Comment by lusocoding** [comment]
Hi @JimsonChalissery, for me that's not the case. I'm trying to call the REST API either via C# HttpClient or via curl request. Not using any of those tools. I followed the C# example in the documentation and the way the authorization header is being set is exactly the same.

**Comment by lusocoding** [comment]
Finally able to find what was happening. When encoding to base64 I was only using the PAT. Instead the format "{username}:{pat}" must be used, which in this case user is empty:

``` csharp
var authToken =  Convert.ToBase64String(Encoding.ASCII.GetBytes($":{accessToken}"));
httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Basic", authToken);
```

**Comment by vsha041** [comment]
> Finally able to find what was happening. When encoding to base64 I was only using the PAT. Instead the format "{username}:{pat}" must be used, which in this case user is empty:
> 
> ```cs
> var authToken =  Convert.ToBase64String(Encoding.ASCII.GetBytes($":{accessToken}"));
> httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Basic", authToken);
> ```

Just as an FYI for others, I ran these commands to get the token and used $token as accessToken (in nuno-barreiro's solution)
az login
$token = az account get-access-token --query accessToken -o tsv;
