### ISSUE TITLE
How can you check if you're on the latest version?

### ISSUE THREAD

**Issue by sebastiaandurand** [MicrosoftDocs/vsts-docs#3927]
I have a devops organization that needs to be moved between tenants, the uses will get a new e-mail. According to this pages a resolve button will be available? I can't see it on my devops organisation

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 031380a0-4f04-4105-199a-81715b42c653
* Version Independent ID: 570b2795-90ad-32b4-7ad0-1fceb186ffa3
* Content: [Connect organization to Azure Active Directory - Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/connect-organization-to-azure-ad?view=azure-devops#feedback)
* Content Source: [docs/organizations/accounts/connect-organization-to-azure-ad.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/accounts/connect-organization-to-azure-ad.md)
* Product: **devops**
* Technology: **devops-accounts**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @sebastiaandurand, it looks like the deployment of this feature is a bit delayed. Apologies for any confusion. I'll update the docs to reflect that this is "coming soon." Please let me know if you have any further questions. Thanks!

**Comment by chcomley** [comment]
I'll be closing this issue, @sebastiaandurand, but please do leave a comment if you have any further questions. Thanks for reaching out.
