### ISSUE TITLE
Misleading text

### ISSUE THREAD

**Issue by nikoNguyen** [MicrosoftDocs/vsts-docs#3930]
Hi,
The following sentence from this page is false :
 "Contact your company's Azure administrator to gain permissions to create an organization or to have them create one for you"
There is no permission  to control who can or cannot create an "organization", I have allready submitted this , but the doc is still wrong

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 01770b43-fd5b-efbc-36f5-af91a3c8cf5a
* Version Independent ID: 7c046a91-37f9-32e3-dc3e-dfa922c456be
* Content: [Plan your organizational structure - Azure DevOps - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/user-guide/plan-your-azure-devops-org-structure?view=azure-devops)
* Content Source: [docs/user-guide/plan-your-azure-devops-org-structure.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/user-guide/plan-your-azure-devops-org-structure.md)
* Product: **devops**
* Technology: **devops-new-user**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Thanks for the feedback, @nikoNguyen. I'll be completing a PR today which removes this text, so it should be live by this afternoon or tomorrow. Thanks again!
