### ISSUE TITLE
DoD only documents the criteria, it doesn't enforce them, correct?

### ISSUE THREAD

**Issue by jetboy2k** [MicrosoftDocs/vsts-docs#3932]
It's not possible to set up quality gates or policy enforcement that would block users from advancing an item on a board, is it? For example, if I wanted policy that user stories must meet the following criteria before they can be moved to the last column on the board:

1. Required tasks to be associated with a user story
2. Required the tasks associated with a user story to be in the Closed state

I could, using DoD, document it as this page describes, but I can't configure the board to "lock" an item into a column until the policy was met, correct?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 934d334d-3af9-2e60-22d2-b0291ff0a344
* Version Independent ID: 0c18bb6f-5902-367d-d6b0-8f01d042e6a1
* Content: [Definition of Done on the Kanban board - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/boards/definition-of-done?view=azure-devops)
* Content Source: [docs/boards/boards/definition-of-done.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/boards/boards/definition-of-done.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@jetboy2k - Thank you for your inquiry. You are correct, there isn't any way to enforce DoD guidelines. T
