### ISSUE TITLE
Documentation for when Build is started?

### ISSUE THREAD

**Issue by dpaulino** [MicrosoftDocs/vsts-docs#3935]
Hello, I'm just wondering if DevOps has a webhook event for Build Started and if there's documentation for it? Please let me know. Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6033d681-9093-547c-20fd-b31183c2bb33
* Version Independent ID: 0d92e3f0-7fb4-57e5-d913-f305a055a819
* Content: [Service hooks event reference](https://docs.microsoft.com/en-us/azure/devops/service-hooks/events?view=azure-devops#ms.vss-release.deployment-started-event)
* Content Source: [docs/service-hooks/events.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/service-hooks/events.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by chcomley** [comment]
Hi @dpaulino, We don’t support a build started event. The best way to see the full list of supported events is to try to create a generic web hook and look at the event drop-down list. The web hook subscriber supports all event types. Hope this helps! Please let me know whether you have any further questions. Thanks!

**Comment by dpaulino** [comment]
Appreciate the response, thanks 👍🏽
