### ISSUE TITLE
Update AzureRmWebAppDeployment documentation to use version 4

### ISSUE THREAD

**Issue by worldspawn** [MicrosoftDocs/vsts-docs#3937]
It currently references version 3. Its always helpful if the documentation references the most recent version :)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a40a853-83d6-844a-4752-8b00909c9ffb
* Version Independent ID: e3121964-de38-2a57-2414-c1e29a880477
* Content: [Deploy an Azure Web App - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/targets/webapp?view=azure-devops&tabs=yaml#feedback)
* Content Source: [docs/pipelines/targets/webapp.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/targets/webapp.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by srivatsamarichi** [comment]
The task document is [here](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-rm-web-app-deployment?view=azure-devops) for the latest version. There are isolated tasks based on the Web App types.

**Comment by iamsrivatsa** [comment]
The task document is [here ](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-rm-web-app-deployment?view=azure-devops)for the latest version. There are isolated tasks based on the Web App types.

**Comment by chasewilson** [comment]
@worldspawn thanks for the feedback! The documentation has been updated by @iamsrivatsa and I'll be closing the issue. If you have any more feedback I hope you will create a new issue :) Thanks for the great work @iamsrivatsa
