### ISSUE TITLE
Embed content of a wiki page

### ISSUE THREAD

**Issue by bartdk-be** [MicrosoftDocs/vsts-docs#3938]
Is it possible to embed the content of a VSTS-wiki page inside a widget ? 
No link, but the actual content.
Since our wiki is not stored in a repository, we can nog Select a markdown file.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b21c46ee-e19c-9dc4-11c2-8749c6576925
* Version Independent ID: 09ad6f7f-5169-f1b5-4f71-410bd85c62df
* Content: [Add markdown content to a team dashboard - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/report/dashboards/add-markdown-to-dashboard?view=azure-devops)
* Content Source: [docs/report/dashboards/add-markdown-to-dashboard.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/report/dashboards/add-markdown-to-dashboard.md)
* Product: **devops**
* Technology: **devops-analytics**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@bartdk-be - Thank you for your inquiry. I don't believe this is supported at this time. @adramasu - can you comment further?

**Comment by adramasu** [comment]
Hi @bartdk-be, we don't have support for this. Please raise a suggestion ticket for the same. You can raise one [here](https://developercommunity.visualstudio.com/content/idea/post.html?space=21).
