### ISSUE TITLE
Incorrect information specified

### ISSUE THREAD

**Issue by vijay-gowda** [MicrosoftDocs/vsts-docs#3944]
Above it is specified....

"Use the Related link type when the work items being linked are at the same level—such as two user stories that define features that overlap one another—or to link work items that are defined in different projects or managed by different teams."

However, I have tried to create a link against a Work item in one project and when I selected Relate link type, there is no option to select another project to list the corresponding work item. Please note I am not talking about cross organization, but only cross project i.e., linking one User Story in say Project A with another user story in Project B. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba7c85b2-fb57-aefe-af67-fcdcbb94e595
* Version Independent ID: ea532ac5-f00b-d570-80b4-781190c9b4ed
* Content: [Link work items to support traceability - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/queries/link-work-items-support-traceability?view=azure-devops&tabs=new-web-form)
* Content Source: [docs/boards/queries/link-work-items-support-traceability.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/boards/queries/link-work-items-support-traceability.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by vijay-gowda** [comment]
In fact I want to have the capability to link work items across work items types and projects.

**Comment by KathrynEE** [comment]
@vijay-gowda - Thank you for your inquiry. You can create links using the Related link type across work item types and projects. There is no drop-down menu to select the project, but you can use the search function in the **Work items to link to** box to put in a keyword. The search function will list items that meet the search criteria across projects. Or, you can input the ID of the work item you want to link to.
