### ISSUE TITLE
Project-level groups is missing a "Release Administrators" row

### ISSUE THREAD

**Issue by stephenacrown** [MicrosoftDocs/vsts-docs#3946]
The "Project-level groups" section on this page is missing a "Release Administrators" row

https://docs.microsoft.com/en-us/azure/devops/organizations/security/permissions?view=azure-devops#project-level-groups

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 68686c2b-c69a-d9e4-3e21-a46d231b649c
* Version Independent ID: 049659da-1772-3166-f909-4feeb8a97730
* Content: [What are all the default permissions and groups? - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/security/permissions?view=azure-devops#feedback)
* Content Source: [docs/organizations/security/permissions.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/security/permissions.md)
* Product: **devops**
* Technology: **devops-security**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@stephenacrown - Thank you for your comment. The Release Administrators group is a built-in group which is created after the first release pipeline is defined. I  will update the article to reflect this.
