### ISSUE TITLE
87

### ISSUE THREAD

**Issue by StayFan** [MicrosoftDocs/vsts-docs#395]
7

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 8f065206-e7a8-a43a-bc6b-27c95d29af99
* Version Independent ID: 37f9de5e-aff1-89b5-de68-f5144d5df3f5
* Content: [Review your repo history](https://docs.microsoft.com/fr-fr/vsts/git/tutorial/history?view=vsts&tabs=visual-studio)
* Content Source: [docs/git/tutorial/history.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/git/tutorial/history.md)
* Service: **unspecified**
* GitHub Login: @douge
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
@StayFan Thank you for your feedback, I am closing this issue since I don't see any actions for me to take, but please reactivate this issue if you have additional details to provide. Thank you for your feedback.
