### ISSUE TITLE
Open source?

### ISSUE THREAD

**Issue by Daniel15** [MicrosoftDocs/vsts-docs#3954]
Is this available for open-source projects, or is it only in the paid version? The page doesn't really specify.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a10a409-5468-9532-f0dc-5a28cdd566d8
* Version Independent ID: 2ef20266-bc45-448b-27f5-e5c3bffed2ef
* Content: [Get started with NuGet packages in Azure DevOps Services and TFS](https://docs.microsoft.com/en-us/azure/devops/artifacts/get-started-nuget?view=azure-devops#feedback)
* Content Source: [docs/artifacts/get-started-nuget.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/artifacts/get-started-nuget.md)
* Product: **devops**
* Technology: **devops-artifacts**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by alexmullans** [comment]
Right now Azure Artifacts requires a license for each user and is only available for private projects. Stay tuned to the Build announcements on May 6 for some updates on these topics.
