### ISSUE TITLE
Git commit menu extension points documentation

### ISSUE THREAD

**Issue by debben** [MicrosoftDocs/vsts-docs#3961]
Under the preview features menu in Azure Repos is a flag for "Git commit menu extension points". There's no documentation for what target id should be used for how one can create contributions that target this menu.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 56437af3-75da-d219-5364-9b7927298ece
* Version Independent ID: ca01655a-9195-cf92-14b4-77ef66053dcf
* Content: [Extension Points](https://docs.microsoft.com/en-us/azure/devops/extend/reference/targets/overview?view=azure-devops#feedback)
* Content Source: [docs/extend/reference/targets/overview.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/extend/reference/targets/overview.md)
* Product: **devops**
* Technology: **devops-ecosystem**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by chcomley** [comment]
Thanks for your feedback, @debben. I've created a user story on my backlog to address this!

**Comment by hross** [comment]
While we work on documenting this, here are the extension points that exist when that preview feature is turned on:

"ms.vss-code-web.git-commit-list-menu" is for the "..." menu on the commit listing page:

![image](https://user-images.githubusercontent.com/166143/56207559-0d010700-601d-11e9-990b-630baa808116.png)

"ms.vss-code-web.git-commit-details-menu" is for the "..." menu on the commit detail page:

![image](https://user-images.githubusercontent.com/166143/56207949-fc9d5c00-601d-11e9-8656-aab70a02a306.png)

**Comment by chcomley** [comment]
Hi @debben, I've updated the article, which should go live on 07/23. Thanks again for your valuable feedback!
