### ISSUE TITLE
Extension manifest is invalid

### ISSUE THREAD

**Issue by planetmarshall** [MicrosoftDocs/vsts-docs#3962]
The extension manifest in the [Dashboard Widget Tutorial]( https://docs.microsoft.com/en-us/azure/devops/extend/develop/add-dashboard-widget?toc=/azure/devops/report/dashboards/toc.json&bc=/azure/devops/report/dashboards/breadcrumb/toc.json&view=azure-devops) is missing the required `categories` group. Attempting to package the extension using `tfx` results in the following error: 

```
error: Error: There were errors with your extension. Address the following and re-run the tool.
error: One or more 'categories' must be provided.
```

**Comment by chcomley** [comment]
Hi @planetmarshall, I'll be looking into this and updating the docs accordingly. Thanks so much for reaching out.
