### ISSUE TITLE
Allow specifying a PowerShell script for the Azure CLI task

### ISSUE THREAD

**Issue by craigtp** [MicrosoftDocs/vsts-docs#3963]
The Azure CLI task within Azure DevOps currently allows either a Windows batch file (.bat), a Windows Command file (.cmd) or a Linux Bash script (.sh) to be used as part of the task.

It would be nice if a PowerShell script (.ps1) could be used also.

This should allow usage of a single type of script (.ps1) that should work cross-platform, meaning it should work irrespective of the chosen host (i.e. either Hosted VS2017 or Hosted Ubuntu hosts should work)

**Comment by thomps23** [comment]
@craigtp Please accept our apologies for the delay in getting to your issue. The best place to promote new Azure DevOps features is using [this form](https://developercommunity.visualstudio.com/content/idea/post.html?space=21) in the developer community portal.
