### ISSUE TITLE
Azure DevOps (specifically, Pipelines) incorrectly redirects users to this page

### ISSUE THREAD

**Issue by amang2205** [MicrosoftDocs/vsts-docs#3964]
By using the https://go.microsoft.com/fwlink/?LinkId=829603 link, users who want to learn more from the tooltip associated to 'Don't sync sources' get redirected to this page which doesn't reference what sync sources from the Pipelines agents' perspective means.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e59bebc3-fe8a-ad9e-7c55-884a8c7b4bac
* Version Independent ID: 7db3d604-b118-2f7b-85f4-1bd52244b279
* Content: [Build source repositories - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/index?view=azure-devops#feedback)
* Content Source: [docs/pipelines/repos/index.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/repos/index.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by brandonmcclure** [comment]
That is why I am here... I am going to just try checking some boxes and seeing what happens

**Comment by rickrain** [comment]
The page you're looking for is here:
https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/pipeline-options-for-git

The correct place to report this bug is here:
https://developercommunity.visualstudio.com/spaces/21/index.html

**Comment by rickrain** [comment]
Reported this in the Azure DevOps feedback page:
https://developercommunity.visualstudio.com/content/problem/578692/azure-devops-specifically-pipelines-incorrectly-re.html

**Comment by amang2205** [comment]
With all due respect Rick, the issue is reported HERE because the docs.microsoft.com issue report button automatically directs a user who comes across issues to this repository. If that too is incorrect, please fix that first. Otherwise, though I report these issues with pleasure, I don't believe you're taking my concerns seriously.

**Comment by thomps23** [comment]
@amang2205 Thanks for taking the time to report this issue, and I can understand how you arrived here to provide feedback about your experience. 

It looks like the engineering team confirmed that they received your feedback (per the community link provided by @rickrain ).
