### ISSUE TITLE
Screenshot in step #6 contains a create project option, which does not exist

### ISSUE THREAD

**Issue by p2well** [MicrosoftDocs/vsts-docs#3965]
Screenshot in step #6 inside the 'Sign up for Azure DevOps with a personal Microsoft account' section shows an option to create an organization project, which members of my organization can view. This option does not exist.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b1b10281-bec5-1510-635f-57705972fb58
* Version Independent ID: 98d26279-c7af-85a2-24c0-9bffd8962842
* Content: [Sign up, invite teammates - Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/user-guide/sign-up-invite-teammates?view=azure-devops#feedback)
* Content Source: [docs/user-guide/sign-up-invite-teammates.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/user-guide/sign-up-invite-teammates.md)
* Product: **devops**
* Technology: **devops-new-user**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @p2well, the content has been updated! Thanks so much for the feedback!
