### ISSUE TITLE
So, how do you run some tests?

### ISSUE THREAD

**Issue by vonj** [MicrosoftDocs/vsts-docs#3966]
Looks like a little thing is missing, how do you kick off some tests?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d0d23bbb-55aa-f3d6-9b6c-045d21ad4a63
* Version Independent ID: eb389501-8a8c-e41e-d357-05c44bcde5d7
* Content: [Test Overview](https://docs.microsoft.com/en-us/azure/devops/integrate/previous-apis/test/overview?view=azure-devops-2019#feedback)
* Content Source: [docs/integrate/previous-apis/test/overview.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/integrate/previous-apis/test/overview.md)
* Product: **devops**
* Technology: **devops-ecosystem**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by chcomley** [comment]
Hi @vonj, Thanks for reaching out! Does this help? https://docs.microsoft.com/en-us/azure/devops/integrate/previous-apis/test/runs?view=azure-devops-2019#create-new-test-run
