### ISSUE TITLE
Assign work from a common backlog

### ISSUE THREAD

**Issue by paulomorgado** [MicrosoftDocs/vsts-docs#3969]
Aren't the two images supposed to be different?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c4623db6-ec0a-8b47-62a1-07e58a759516
* Version Independent ID: 984b231c-2b4e-b653-984a-f46f03300cfd
* Content: [Portfolio management - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/plans/portfolio-management?view=azure-devops#feedback)
* Content Source: [docs/boards/plans/portfolio-management.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/boards/plans/portfolio-management.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@paulomorgado  - Thank you for your inquiry. The two images are different, check the labels under the Node Name column. I will update the topic and highlight the differences so that it is clearer.
