### ISSUE TITLE
Path filters wildcard support

### ISSUE THREAD

**Issue by KacperMucha** [MicrosoftDocs/vsts-docs#397]
Wildcards are supported in branch filters, but what about path filters? I tried several different path formats, but the only one that works is absolute path. I'd like to be able to exclude all subfolders at certain level. For example:
/folder1/src/tools
/folder2/src/tools
Is it possible to exclude all tools folders with one filter rule? Something like /*/src/tools?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5673ec1-c7d1-e0ac-043a-8fc3d5b226a9
* Version Independent ID: b4872831-51c0-6cf8-1c56-de20beb38a80
* Content: [Build definition triggers](https://docs.microsoft.com/en-us/vsts/build-release/concepts/definitions/build/triggers?view=vsts)
* Content Source: [docs/build-release/concepts/definitions/build/triggers.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/build-release/concepts/definitions/build/triggers.md)
* Service: **unspecified**
* GitHub Login: @douge
* Microsoft Alias: **alewis**

**Comment by vijayma** [comment]
Thanks for the suggestion. Wildcards are not supported presently in path filters. We will add this to the backlog. You can also post this suggestion on [user voice](https://visualstudio.uservoice.com/forums/330519-visual-studio-team-services?category_id=145254).

**Comment by lucianjp** [comment]
Documentation states otherwise.
Added a comment on the line (https://github.com/MicrosoftDocs/vsts-docs/commit/dd508c92f0cc8aaf7762fc312106966018658a74#r30568581) about this. Not sure if the contributor is notified tho. But in the doc for Path Filters it shows a `docs/*` suggesting it supports wildcards. I did some tests and unfortunatly it seems it doesn't work. So there is a mismatch between the doc and the feature.

**Comment by Mgamerz** [comment]
I just spent several hours trying to figure out why this would not work in my yml file, just to find this document that explains the documentation is wrong and has been for **years**! Why isn't the documentation updated (or better yet, this implemented?)

**Comment by PavloAndriiesh** [comment]
Wildcard support and documentation update will be rolled out over the next two to three weeks according to the latest [release notes](https://docs.microsoft.com/en-us/azure/devops/release-notes/2021/sprint-192-update#support-for-wild-cards-in-path-filters).
