### ISSUE TITLE
Can't add chart to dashboard

### ISSUE THREAD

**Issue by Nubestic** [MicrosoftDocs/vsts-docs#3976]
The button ... add to dashboard doesn't exist, I'm project admin and fill access to entire project but still can't add to dashboard, on the other hand when trying to add a widget to dashboard and define the query in that case no query is shown for selection, so can't select the query either from dashboard side.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 379200c5-cd1b-9c69-3cce-ec7dcafbd2f2
* Version Independent ID: 4de1aff6-26f4-6cd7-1178-ce2b106fc52f
* Content: [Add built-in charts to a team dashboard - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/report/dashboards/add-charts-to-dashboard?view=azure-devops)
* Content Source: [docs/report/dashboards/add-charts-to-dashboard.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/report/dashboards/add-charts-to-dashboard.md)
* Product: **devops**
* Technology: **devops-analytics**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@Nubestic - Thank you for your inquiry. Are you using the hosted/cloud version or an on-premises? If so, what version on-prem are you using.

**Comment by KathrynEE** [comment]
Closing issue - not enough information to respond.
