### ISSUE TITLE
Pools are scoped to your project in TFS 2017 and newer and in Azure Pipelines

### ISSUE THREAD

**Issue by paulomorgado** [MicrosoftDocs/vsts-docs#3979]
What does "Pools are scoped to your project in TFS 2017 and newer and in Azure Pipelines" mean?

That **newer** sounds strange.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4409a9cb-8448-edd6-da0a-243e5601aa3e
* Version Independent ID: ec15f71a-a76d-c3f9-1d31-832f92183ef4
* Content: [Agents pools - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/pools-queues?view=azure-devops)
* Content Source: [docs/pipelines/agents/pools-queues.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/agents/pools-queues.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by vijayma** [comment]
We are re-wording this. Thanks for pointing out.
