### ISSUE TITLE
Show the Result of clicking save button when adding a new Remote

### ISSUE THREAD

**Issue by hemantkd** [MicrosoftDocs/vsts-docs#398]
Hi,

I think it will help with clarity if a screenshot of the Repository Settings window is shown once Save button is clicked when adding a new remote.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 240f15e3-daf9-78f8-7423-cc17490ee401
* Version Independent ID: 3f1934d0-75c4-56b3-32d5-676b7fbe70b7
* Content: [Fork your repository in VSTS or TFS](https://docs.microsoft.com/en-us/vsts/git/concepts/forks?view=vsts#clone-your-fork-locally)
* Content Source: [docs/git/concepts/forks.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/git/concepts/forks.md)
* Service: **unspecified**
* GitHub Login: @douge
* Microsoft Alias: **macoope**

**Comment by steved0x** [comment]
@hemantkd I agree, I have added a work item to the backlog and this screenshot should be added shortly. Thank you for your feedback!
