### ISSUE TITLE
Viewing Your App in VS

### ISSUE THREAD

**Issue by Riddletonm** [MicrosoftDocs/vsts-docs#3985]
Step 2 of the "Test your extension" section does not explain how to actually start your app in Visual Studio so that Azure DevOps Services can access it.  Could this have some additional info please?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3448467b-09a7-98a5-12b0-8c04a133a479
* Version Independent ID: 873dfccf-da1d-ecf7-0b31-1f553127bf6e
* Content: [Create your first Extension with Visual Studio](https://docs.microsoft.com/en-us/azure/devops/extend/get-started/visual-studio?view=azure-devops#feedback)
* Content Source: [docs/extend/get-started/visual-studio.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/extend/get-started/visual-studio.md)
* Product: **devops**
* Technology: **devops-ecosystem**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by chcomley** [comment]
Hi @Riddletonm, thanks for reaching out. I'll be looking into this and will get back to you. Thanks again!

**Comment by chcomley** [comment]
Hi @Riddletonm, You can either hit ctrl+f5  or from the Debug menu choose “Dtart debugging” or “Start without debugging.” I'll be closing this issue, but do please comment if you have any further questions. Thanks and have a great weekend!
