### ISSUE TITLE
Space missing following linked text

### ISSUE THREAD

**Issue by dustyjuhl** [MicrosoftDocs/vsts-docs#3988]
Under the "Branch policies" section, the 2nd sentence displays as "Set up branch policiesto ensure...." Needs a space following the "branch policies" link.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4e18eead-7795-0752-93b0-e07f6d088089
* Version Independent ID: f637de69-b13c-eed8-ab05-3515106c9270
* Content: [What is Git? - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/learn/git/what-is-git#feedback)
* Content Source: [https://mseng.visualstudio.com/DefaultCollection/TechnicalContent/_git/devops-learn-pr?path=%2fdocs%2fgit%2fwhat-is-git.md&version=GBlive&_a=contents](https://mseng.visualstudio.com/DefaultCollection/TechnicalContent/_git/devops-learn-pr?path=%2fdocs%2fgit%2fwhat-is-git.md&version=GBlive&_a=contents)
* Product: **devops**
* Technology: **devops-learn**
* Git Login: **samgu**
* Microsoft Alias: **kangan**

**Comment by WilliamAntonRohm** [comment]
Thank you for your feedback.  I have updated the documentation and it should be live by tomorrow.
