### ISSUE TITLE
The type "Integrated in release environment" is not listed on this page

### ISSUE THREAD

**Issue by deadlydog** [MicrosoftDocs/vsts-docs#3989]
I think this may be a newer ExternalLinkFilter type and that's why it's not in the documentation yet, but the "Integrated in release environment" type is valid and will display links to a release environment deployment that the work item has been tagged in.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d9818350-b7e0-7789-95b4-77d5c5dd472e
* Version Independent ID: e4318c77-d744-e056-fc2a-4aa879be22cc
* Content: [Link types reference - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/queries/link-type-reference?view=azure-devops#external-link-types)
* Content Source: [docs/boards/queries/link-type-reference.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/boards/queries/link-type-reference.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@deadlydog - Thank you for your feedback. You are correct that this is a valid link type that is created by the system when a user enables the “Report deployment status to Work” checkbox on a release definition as shown in the image below. 

 
![image](https://user-images.githubusercontent.com/10856840/60829746-7dc24600-a16a-11e9-8bd3-b12b1956277a.png)


I will update the article accordingly.
