### ISSUE TITLE
Does this use the Build Agent's windows service credentials if the admin login/password arent supplied?

### ISSUE THREAD

**Issue by StingyJack** [MicrosoftDocs/vsts-docs#399]
needless description

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5e0ef2cf-ed52-6ded-bf14-4820d73b4ed0
* Version Independent ID: 7781e0f0-43aa-9008-abda-c03a37e2d7b4
* Content: [Windows Machine File Copy build and release task for VSTS and TFS](https://docs.microsoft.com/en-us/vsts/build-release/tasks/deploy/windows-machine-file-copy?view=vsts)
* Content Source: [docs/build-release/tasks/deploy/windows-machine-file-copy.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/build-release/tasks/deploy/windows-machine-file-copy.md)
* Service: **unspecified**
* GitHub Login: @douge
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment]
Thanks you for your feedback. I have passed the question on to the product team and will let you know their response.

**Comment by alexhomer1** [comment]
The task requires credentials to be supplied. It will not use the agent's credentials.

**Comment by StingyJack** [comment]
ty!

**Comment by PaulMEdwards** [comment]
My boss is also asking why this is the case... We both agree that the copy task should have the option to use the agent credentials.

**Comment by edgariscoding** [comment]
@alexhomer1 are you sure? The yaml snippet above says that credentials are optional.
