### ISSUE TITLE
Sentence doesn't read correctly

### ISSUE THREAD

**Issue by cschleiden** [MicrosoftDocs/vsts-docs#3990]
Should this be .. "prevents you from using ..."? 

&gt; When IIS Basic Authentication is enabled on your windows machine, it prevents your using personal access tokens (PATs) as an authentication mechanism.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 71fa3b01-218c-9a5f-5b71-affdf65c945c
* Version Independent ID: 7c414686-f52d-51ce-87e1-794deade8506
* Content: [Enabling IIS Basic Authentication invalidates using Personal Access Tokens](https://docs.microsoft.com/en-us/azure/devops/integrate/get-started/authentication/iis-basic-auth?view=azure-devops#feedback)
* Content Source: [docs/integrate/get-started/authentication/iis-basic-auth.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/integrate/get-started/authentication/iis-basic-auth.md)
* Product: **devops**
* Technology: **devops-ecosystem**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by chcomley** [comment]
Yes, thanks for the suggestion, @cschleiden. I've created a user story to capture this update. Thanks again!

**Comment by chcomley** [comment]
I've completed this PR, so it should be live by sometime this afternoon. Thank you!
