### ISSUE TITLE
Azure DevOps Server 2019 External User

### ISSUE THREAD

**Issue by jeremycec** [MicrosoftDocs/vsts-docs#3991]
hi.. Our Azure DevOps Server 2019 in Azure VM that joined to Azure Active Directory Domain Server. 

In Azure DevOps Server 2019. Is there a way to authenticate external user that is invited through Azure Active Directory? We can search and locate the user but the windows authentication prompt always complain wrong password.

**Comment by pathakneeti** [comment]
Hi Jeremy, is the user a Guest or Member of the AAD? Do they show up in the Users tab in your Organization?

**Comment by jeremycec** [comment]
Hi there,
Yes. It is a guest user. It did showed up as "domain name\userid". 

best regards,Jeremy Chu 

    On Saturday, 20 April 2019, 02:39:05 GMT+8, pathakneeti <notifications@github.com> wrote:  
 
 
Hi Jeremy, is the user a Guest or Member of the AAD? Do they show up in the Users tab in your Organization?

**Comment by ramrajesh** [comment]
Hi Jeremy,

The external user has to be added to your active directory for them to use Azure DevOps Server. If you have setup AAD connect, that will sync your AAD identities to your on-premises AD and the user can use the same password to sign into Azure DevOps Server. Keep in mind that Azure DevOps Server does not support authenticating with Azure Active Directory and rather only with on-premises AD using NTLM/Kerberos.

Thanks,
Rajesh Ramamurthy
