### ISSUE TITLE
Please add the https://{organization_name}.vstmr.visualstudio.com to the firewall exclusion list.

### ISSUE THREAD

**Issue by navin22** [MicrosoftDocs/vsts-docs#3992]
Please add **_"https://{organization_name}.vstmr.visualstudio.com"_**
to the list in [here ](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/v2-windows?view=azure-devops#for-organizations-using-the-visualstudiocom-domain)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43799c5d-2f13-cc76-a1c0-a3f850e16d4e
* Version Independent ID: 97a5b73f-faf7-f9c0-9269-fc79984616d6
* Content: [Deploy a build and release agent on Windows - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/v2-windows?view=azure-devops#im-running-a-firewall-and-my-code-is-in-vsts-what-urls-does-the-agent-need-to-communicate-with)
* Content Source: [docs/pipelines/agents/v2-windows.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/agents/v2-windows.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by gautamksr** [comment]
https://{organization_name}.vstmr.visualstudio.com this url reports 404

**Comment by navin22** [comment]
@gautamksr : It's a micro service URL hence it's giving the 404. But in firewall allowing just that's enough for further communications over network.

eg: In the existing doc we have `https://{organization_name}.vsrm.visualstudio.com`  which also returns 404.

If you want to test the micro services are working fine you can try `https://{organization_name}.vstmr.visualstudio.com/_apis/connectiondata` which will return a JSON.

**Comment by steved0x** [comment]
Fixed in https://github.com/MicrosoftDocs/vsts-docs/pull/5614

**Comment by Girishpdesai** [comment]
Is this url " https://{organization_name}.vstmr.visualstudio.com/_apis/connectiondata" same as 
 https://dev.azure.com/{organization_name}/_apis/connectiondata ?
We are using Azure DevOps and having similar issue
