### ISSUE TITLE
No way to query work item which has a pull request in certain state

### ISSUE THREAD

**Issue by vijay-gowda** [MicrosoftDocs/vsts-docs#3993]
Is there a way to list work items which has at least one pull request in certain states like completed or active, etc.?

I want to report on work items that has been successfully integrated into upstream branch i.e., have a pull request with certain properties i.e., target and state, etc. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1f815700-6b3e-18f0-331f-5c54767c0e09
* Version Independent ID: ff670fd4-dbe8-b303-0c6b-fdb3f6eb8566
* Content: [Look up definitions and sample queries - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/queries/query-index-quick-ref?view=azure-devops)
* Content Source: [docs/boards/queries/query-index-quick-ref.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/boards/queries/query-index-quick-ref.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@vijay-gowda - Thank you for your inquiry. This feature is not supported at this time. Consider adding it as a feature request at our [Developer Community page](https://developercommunity.visualstudio.com/spaces/21/index.html).
