### ISSUE TITLE
what about upstream sources that are disabled/removed for security reasons, ie malware?

### ISSUE THREAD

**Issue by Korijn** [MicrosoftDocs/vsts-docs#3995]
&gt; Peace of mind: packages used via upstream sources are guaranteed to be saved in the feed on first use; if the upstream source is disabled/removed, or the remote feed goes down or deletes a package you depend on, you can continue to develop and build

Sometimes upstream sources are removed for security reasons, ie malware (for example you can google "eslint malware"). Will the feed still serve me the malicious package? I'm not entirely sure if that gives me "peace of mind" :)

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: d5f022df-36c3-34b1-cac1-ac33995a7d73
* Version Independent ID: 9634b0c8-7b14-4453-2c04-aedabbf331f1
* Content: [Upstream sources](https://docs.microsoft.com/nl-nl/azure/devops/artifacts/concepts/upstream-sources?view=azure-devops#feedback)
* Content Source: [docs/artifacts/concepts/upstream-sources.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/artifacts/concepts/upstream-sources.md)
* Product: **devops**
* Technology: **devops-artifacts**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by elbatk** [comment]
Hi @Korijn , if an upstream is removed/disabled, we will no longer fetch from that upstream. With upstream sources, we cache/save previously fetched packages, so you will be able to continue developing and building with the package that we have previously fetched and cached but we will not serve you a new package from an upstream that is brought down. Does that make sense?

**Comment by Korijn** [comment]
Yes, that was already clear. The situation I describe is slightly different: what if this package is already cached, and _afterwards_ the vulnerability/malware is found and the package is removed from upstream.

**Comment by elbatk** [comment]
Currently, we have facilities for permanently blocking particular package names/versions system-wide (upstream or not), which we use at purely our team's discretion to respond to widely-reported malicious (as distinct from insecure) package incidents. Packages that we do block are blocked from both upload and download, regardless of how the package got into the feed. Other than that, any packages that have been ingested before being deleted from upstream will remain in the feed.

Moving forward, if upstream providers publish the reason for a package being removed, we _may_ be able to automate or semi-automate the blocking process at some point. We do not have plans to do so at this time but is something we can add to the list of considerations as we continue to improve the product.

**Comment by Korijn** [comment]
Thanks!
