### ISSUE TITLE
Unclear what Destination ID should be

### ISSUE THREAD

**Issue by andrewleader** [MicrosoftDocs/vsts-docs#3997]
When distributing to the Store, I don't know what the Destination ID is supposed to be. Docs should clarify where this ID is suppsoed to come from.

My distribution task is always failing (and the error gives me no info why), so I'm trying to double check everything, and there's no info here!!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: da6643ac-ea32-1761-a7e9-0f17a3c0b8ee
* Version Independent ID: 2442af0f-3f01-a91c-a98a-29c2f32d35b9
* Content: [App Center Distribute task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/app-center-distribute?view=azure-devops#feedback)
* Content Source: [docs/pipelines/tasks/deploy/app-center-distribute.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/deploy/app-center-distribute.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @thomps23
* Microsoft Alias: **dastahel**

**Comment by DavidStaheli** [comment]
Related task issue here: https://github.com/Microsoft/azure-pipelines-tasks/issues/10158

**Comment by vldalx** [comment]
https://docs.microsoft.com/en-us/appcenter/distribution/vsts-deploy

**Comment by alkumaroii** [comment]
Here is explained in great detail.
https://www.youtube.com/watch?v=-Hh3qNSolOM
