### ISSUE TITLE
"Allow for external invitations" cannot be found under Organization Settings

### ISSUE THREAD

**Issue by hpka** [MicrosoftDocs/vsts-docs#3998]
Under Prerequisites, the third point reads:
"The organization to which you want to invite external users must allow for external invitations. Go to the Organization Settings page to confirm."

However, I've hunted all over Org Settings and just cannot find this specific setting, except the setting that's shown in the first point/screenshot (which I have on).

Please can this third point be clarified?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b6db4fba-7322-16bc-3431-6b8f933a84bf
* Version Independent ID: a20bd1b0-06d7-8f49-30d2-25c5e188b674
* Content: [Add, invite external users, guest users to your organization - Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/add-external-user?view=azure-devops#feedback)
* Content Source: [docs/organizations/accounts/add-external-user.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/accounts/add-external-user.md)
* Product: **devops**
* Technology: **devops-accounts**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by spottedmahn** [comment]
>The organization to which you want to invite external users must allow for external invitations. Go to the Organization Settings page to confirm.

Yes, what organization settings page?

[We're having trouble adding users](https://developercommunity.visualstudio.com/content/problem/566761/successfully-added-1-user-with-stakeholder-access.html?childToView=570821#comment-570821)...

**Comment by spottedmahn** [comment]
Upon further deliberation, it seems that these are the same thing (purple boxes)? 🤔

![image](https://user-images.githubusercontent.com/14079228/57929704-07981600-7882-11e9-9985-d7e392dcb606.png)

**Comment by chcomley** [comment]
Hi @hpka,
I apologize for the significant delay in response. + @spottedmahn,  I'm looking into this and hope to have an answer for you today. Thanks!

**Comment by chcomley** [comment]
Hi @hpka and @spottedmahn - good news, I've just confirmed that the third bullet is redundant! I'll be removing it from the doc! Thanks so much for your feedback and apologies for any confusion.

**Comment by chcomley** [comment]
I've completed the PR, so this update should be live this afternoon. Thank you!
