### ISSUE TITLE
Referring to Dockerfile in different Repo

### ISSUE THREAD

**Issue by rjosephp** [MicrosoftDocs/vsts-docs#4001]
inputs:
    command: build
    buildContext: How can I refer to a Dockerfile in a different repository in here?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d9dbf88-7e55-d427-145e-d36b04fb197f
* Version Independent ID: a3f30c00-817c-9c05-7a57-3f2bf618821e
* Content: [Docker task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/docker?view=azure-devops#feedback)
* Content Source: [docs/pipelines/tasks/build/docker.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/build/docker.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @thomps23
* Microsoft Alias: **shasb**

**Comment by shashankbarsin** [comment]
@rjosephp it's not possible to refer to a Dockerfile in a different repository from this task. It's usually observed that the task (and thus the pipeline) is used with a repo that contains a Dockerfile. The task takes as input associated with the same repository as well. For a Dockerfile located in a different repo, it's advisable to create a pipeline for that repo and build the image from there
