### ISSUE TITLE
.artifactignore seems not to work at all?

### ISSUE THREAD

**Issue by J0F3** [MicrosoftDocs/vsts-docs#4004]
I have tried both gitignore (extact same content as a .gitignore file which works with Git) syntax and the syntax used by a CopyFiles taks. But both does not have any effect. All files are uploaded to the aritfact. 

So whats the matter with the .artifactignore file? Should it work as described above or is this perhabs not even implemented in the preview yet?!

Thanks for clarifying...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 861ce7a5-4fa4-55f1-2c97-46a9cc6a2f66
* Version Independent ID: bdf954b9-9bbe-8b34-b674-71ad8153519d
* Content: [Publish and consume Pipeline artifacts in builds - Azure Pipelines and TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/pipeline-artifacts?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/artifacts/pipeline-artifacts.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/artifacts/pipeline-artifacts.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @alexmullans
* Microsoft Alias: **amullans**

**Comment by J0F3** [comment]
Ok, my fault. The .artifactignore file has to be in the same directory as defined as target path of the publish pipeline artifact task. (Not only int the root of the repo like the  azure-pipelines.yml as I first thought...)

Maybe worth to mention in the documentation to make it clear?

**Comment by mitchdenny** [comment]
Making it more explicit in the docs: #4012

**Comment by kirikintha** [comment]
@J0F3 - Hi there, I am having the same issue - can you post a yaml of how you are referencing this file? I am not sure how to set up the build for this. Any screenshot would be a total help. Thanks!

**Comment by J0F3** [comment]
@kirikintha  Here you go 😉: https://www.jfe.cloud/control-pipeline-artifacts-with-artifactignore-file/
The key is really to place the file in the same folder as also the 'upload' task is pointing to. Only then the file is interpreted by the task.

**Comment by nmaaruf** [comment]
there is no way actually to make .artifactignore file works I tried everything putting it in every folders is just doesn't work

**Comment by J0F3** [comment]
So which path have you defined in the settings of the  Publish Pipeline Artifact task in the pipeline and where you have saved the .artifactignore file?
What ist the content of your .artifactignore file?

**Comment by nmaaruf** [comment]
- task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: Frontend'
    inputs:
      path: $(System.DefaultWorkingDirectory)/frontend
      artifact: Frontend


and I have .artifactignore inside frontend, I just need to ignore node_modules after build

**Comment by nmaaruf** [comment]
` - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: Frontend'
    inputs:
      path: $(System.DefaultWorkingDirectory)/frontend
      artifact: Frontend`


and I have .artifactignore inside frontend, I just need to ignore node_modules after build

**Comment by infin8x** [comment]
Ah, you're using the old `PublishBuildArtifacts` task. Switch to `PublishPipelineArtifact@1`

**Comment by kirikintha** [comment]
I hate to cross pollinate a closed ticket, so I wrote up a stack on this: https://stackoverflow.com/questions/57042995/publishpipelineartifact-artifact-ignore-not-recognized/57051248?noredirect=1#comment100719362_57051248 - I got it working for my Angular project. Thanks!

**Comment by nmaaruf** [comment]
thanks guys works great now!

**Comment by karthikeyan-kandasamy** [comment]
My react native project has been not chosen the .artifactignore file as I mentioned @kirikintha 
I have output as complete project 

```
**/*
!android/app/build/outputs/apk/debug/**.*
!android/app/build/outputs/apk/release/**.*
!ios/**.*
```

YML

```
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Pipeline.Workspace)/'
    Contents: '**/.artifactignore'
    TargetFolder: '$(Pipeline.Workspace)'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Pipeline.Workspace)'
    artifact: 'my-artifact'
```

output as complete project with node_modules and all the files in my git file size 504mb.

**Comment by mvonballmo** [comment]
I know that this issue is closed, but I have a related question: does `.artifactignore` have any effect when the `publishLocation` is `filepath`?
