### ISSUE TITLE
Missing information on feature target

### ISSUE THREAD

**Issue by davidcorrigan714** [MicrosoftDocs/vsts-docs#4006]
This page should include documentation for the "ms.vss-web.managed-features" & "ms.vss-web.managed-features-onprem" targets

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 56437af3-75da-d219-5364-9b7927298ece
* Version Independent ID: ca01655a-9195-cf92-14b4-77ef66053dcf
* Content: [Extension Points](https://docs.microsoft.com/en-us/azure/devops/extend/reference/targets/overview?view=azure-devops)
* Content Source: [docs/extend/reference/targets/overview.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/extend/reference/targets/overview.md)
* Product: **devops**
* Technology: **devops-ecosystem**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by chcomley** [comment]
Thanks for the suggestion, @davidcorrigan714. I'm looking into this and will be in touch. Have a great weekend!

**Comment by chcomley** [comment]
Hi @davidcorrigan714, Please accept my "delayed" reply, we appreciate you reaching out. I hope the following information is helpful.

Features are used to provide a user a way to turn on or off functionality in your extension. Here is an example: https://github.com/microsoft/azure-devops-extension-sample/tree/a3a789521efb84f1b857a0a299ed507e5f7c40e6/src/Samples/Feature

When you define a feature, it will appear in this panel: https://docs.microsoft.com/en-us/azure/devops/project/navigation/preview-features?view=azure-devops

You can add a feature as a constraint to other contributions. So, if the feature is enabled, the contribution will appear and if disabled it will not appear.

_ms.vss-web.managed-features_ will appear in hosted service.
_ms.vss-web.managed-features-onprem_ will appear in on prem product.

Do let us know if you have any further suggestions or questions! Thank you!
