### ISSUE TITLE
First link is broken. "cloud-based load tests" link

### ISSUE THREAD

**Issue by Dann1112** [MicrosoftDocs/vsts-docs#4007]
First link is pointing to https://visualstudio.microsoft.com/features/vso-cloud-load-testing-vs but page is not there anymore

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ vinculación de problemas de GitHub.*

* ID: 938662b3-8e6d-aebf-062b-d00b4ed4c22e
* Version Independent ID: fe2487bf-0d3d-24f3-6cf1-4cd18973ef79
* Content: [Load test in the cloud with Visual Studio - Azure Test Plans](https://docs.microsoft.com/es-mx/azure/devops/test/load-test/getting-started-with-performance-testing?view=azure-devops#feedback)
* Content Source: [docs/test/load-test/getting-started-with-performance-testing.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/test/load-test/getting-started-with-performance-testing.md)
* Product: **devops**
* Technology: **devops-test**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by steved0x** [comment]
I have removed the link, please note that the cloud-based load test service is deprecated as described in https://docs.microsoft.com/azure/devops/test/load-test/overview?view=azure-devops
