### ISSUE TITLE
Update documentation for DockerV2

### ISSUE THREAD

**Issue by mbrancato** [MicrosoftDocs/vsts-docs#4013]
Please update the docs to be current. Specifying an imagename and other things are no longer configurable in DockerV2, which is the default in DevOps.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d9dbf88-7e55-d427-145e-d36b04fb197f
* Version Independent ID: a3f30c00-817c-9c05-7a57-3f2bf618821e
* Content: [Docker task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/docker?view=azure-devops#feedback)
* Content Source: [docs/pipelines/tasks/build/docker.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/build/docker.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @thomps23
* Microsoft Alias: **shasb**

**Comment by kvpt** [comment]
From the source code of the task, it's the field named repository which is used for set the image name.
https://github.com/Microsoft/azure-pipelines-tasks/blob/a98820a0b10f861ccfaf012735ee5a9e313258d9/Tasks/Common/docker-common/containerconnection.ts#L66
I agree that it's not obvious at all.

**Comment by shashankbarsin** [comment]
I've updated the documentation for this task. It's now relevant for Docker@2. 

@kvpt, The input was named 'repository' to stay consistent with [standard Docker nomenclature](https://docs.docker.com/docker-hub/repos/)
