### ISSUE TITLE
Can't see the "Follow" button

### ISSUE THREAD

**Issue by hilari0n** [MicrosoftDocs/vsts-docs#4014]
Is this actually released? I can't see the button on our Azure DevOps project's wiki pages.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cd3da932-a8f8-f0b9-668d-0eb498df93b6
* Version Independent ID: 51e6cad0-1737-017a-9ce1-8c6c0090fc56
* Content: [Follow wiki page, get notifications - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/project/wiki/follow-notifications-wiki-pages?view=azure-devops#feedback)
* Content Source: [docs/project/wiki/follow-notifications-wiki-pages.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/project/wiki/follow-notifications-wiki-pages.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by adramasu** [comment]
Hi @hilari0n, I hope the follow button is visible now. If not, please let me know.

**Comment by hilari0n** [comment]
> Hi @hilari0n, I hope the follow button is visible now. If not, please let me know. cc: @chcomley

It is, thanks.
