### ISSUE TITLE
Reference Receiver Nuget Package

### ISSUE THREAD

**Issue by RyanMathewson** [MicrosoftDocs/vsts-docs#402]
This seems like a good place to reference the receiver Nuget package
https://www.nuget.org/packages/Microsoft.AspNet.WebHooks.Receivers.VSTS
Note that as of 3/26/2018 not all of the event types have receivers.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6033d681-9093-547c-20fd-b31183c2bb33
* Version Independent ID: 0d92e3f0-7fb4-57e5-d913-f305a055a819
* Content: [Service hooks event reference](https://docs.microsoft.com/en-us/vsts/service-hooks/events?toc=/vsts/integrate/toc.json&bc=/vsts/integrate/breadcrumb/toc.json&view=vsts)
* Content Source: [docs/service-hooks/events.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/service-hooks/events.md)
* Service: **unspecified**
* GitHub Login: @douge
* Microsoft Alias: **elbatk**

**Comment by elbatk** [comment]
@RyanMathewson awesome! I've added this to the page and it should be live within the next day.
