### ISSUE TITLE
Docker Run envVars option uses '-e' even with name value pairs

### ISSUE THREAD

**Issue by colinross** [MicrosoftDocs/vsts-docs#4021]
Using the docker `run` command, the options `-e`, `--env` (and `--env-file`) are different, not aliases.

In the docker task, the envVar (according to the docs) expects name=value pairs but uses the `-e` option, not the correct `--env` option.  `-e` is for presence only env vars, and the values will be blank.

I think it would be great to allow for all three, but as the documentation stands, the `--env` option should really be used.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d9dbf88-7e55-d427-145e-d36b04fb197f
* Version Independent ID: a3f30c00-817c-9c05-7a57-3f2bf618821e
* Content: [Docker task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/docker?view=azure-devops#run-command)
* Content Source: [docs/pipelines/tasks/build/docker.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/build/docker.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @thomps23
* Microsoft Alias: **shasb**

**Comment by shashankbarsin** [comment]
We've upgraded the Docker task to Docker@2. This version of the task doesn't have custom handling in the form of envVars as described in this issue. The command input can be specified as 'run' and any arguments that are to be passed onto docker binary can be done so through the 'arguments' input directly.  We've updated the documentation to reflect the same under the [Other commands and arguments](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/docker?view=azure-devops#other-commands-and-arguments) section of the doc
