### ISSUE TITLE
Powershell task with Excel use

### ISSUE THREAD

**Issue by VineetMehra** [MicrosoftDocs/vsts-docs#4023]
**New-Object : Retrieving the COM class factory for component with CLSID 
{00000000-0000-0000-0000-000000000000} failed due to the following error: 
80040154 Class not registered (Exception from HRESULT: 0x80040154 
(REGDB_E_CLASSNOTREG)).**

Pipeline is throwing above error for below line, when creating Excel, object:
           **$ObjExcel = New-Object -ComObject Excel.Application**

**Comment by thomps23** [comment]
@VineetMehra - is there a specific topic within our documentation you were following when you encountered this error?
