### ISSUE TITLE
Gateway Connectivity

### ISSUE THREAD

**Issue by joshuamoneill** [MicrosoftDocs/vsts-docs#4034]
Hello, is Azure DevOps an Enterprise Gateway connection option (or are there any plans to make this available)?  Also, is there a product owner for this specific connectivity?  I have some feedback to provide on the general DevOps to Power BI functionality!

Thank you,
Josh

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a874f64-4330-f3c5-b75f-24bc474b2c83
* Version Independent ID: 9034e780-4edc-415c-db3a-64243f5775ea
* Content: [Learn about Power BI integration and supported connection methods - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/report/powerbi/overview?view=azure-devops#feedback)
* Content Source: [docs/report/powerbi/overview.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/report/powerbi/overview.md)
* Product: **devops**
* Technology: **devops-analytics**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by thomps23** [comment]
@joshuamoneill Please accept our apologies for the delay in getting to this issue. This channel is intended for feedback about the Azure DevOps documentation. 

Your questions about the product can be properly routed through the Submit an Idea and Report a Bug forms at [https://azure.microsoft.com/en-us/support/devops/](https://azure.microsoft.com/en-us/support/devops/)
