### ISSUE TITLE
Is Visual Studio 2019 still in preview on hosted agent?

### ISSUE THREAD

**Issue by boskjoett** [MicrosoftDocs/vsts-docs#4038]
On this page it says that the  'windows-2019' hosted agent is still running Visual Studio 2019 Preview. Is it really still using the preview version now that the final VS 2019 is released?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 99af681d-41ad-da15-0b72-08b5cd5a11ac
* Version Independent ID: 2fa0df36-a437-8cbb-b019-b49b31b1e116
* Content: [Microsoft-hosted agents for Azure Pipelines - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops)
* Content Source: [docs/pipelines/agents/hosted.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/agents/hosted.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by jnyrup** [comment]
This PR looks related: https://github.com/Microsoft/azure-pipelines-image-generation/pull/745

From [page](https://github.com/Microsoft/azure-pipelines-image-generation/blob/master/images/win/Vs2019-Server2019-Readme.md) 
> Version: VisualStudio/16.0.0+28711.60.rc.2

From the Agent Pool settings on my Azure DevOps
> Version: VisualStudio/16.0.0+28729.10<br/>

**Comment by thejoebourneidentity** [comment]
CLosing as this should be resolved, let us know if not the case
