### ISSUE TITLE
"Hosted pipelines" section missing maximum single job duration details for PAID pipelines

### ISSUE THREAD

**Issue by MS-Trev** [MicrosoftDocs/vsts-docs#404]
Current: "With the first purchase of a hosted pipeline, the 240 minute limit on total build and release time as well as the 30 minute limit on a single job are waived."

Expected: "With the first purchase of a hosted pipeline, the 240 minute limit on total build and release time is waived and the maximum duration of a single job is increased to 6 hours. "

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cb26f633-6068-0e2a-0b8d-e97f8acdbb09
* Version Independent ID: 449ffa66-9707-c87a-6128-57beeb22f0fc
* Content: [Concurrent pipelines in VSTS](https://docs.microsoft.com/en-us/vsts/build-release/concepts/licensing/concurrent-pipelines-ts?view=vsts#feedback)
* Content Source: [docs/build-release/concepts/licensing/concurrent-pipelines-ts.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/build-release/concepts/licensing/concurrent-pipelines-ts.md)
* Service: **unspecified**
* GitHub Login: @douge
* Microsoft Alias: **alewis**

**Comment by vijayma** [comment]
Thanks for the suggestion. We have updated the text and it will be live soon.
