### ISSUE TITLE
Grammar suggestions

### ISSUE THREAD

**Issue by Doomfist0** [MicrosoftDocs/vsts-docs#4046]
The Azure DevOps Services Demo Generator is a service WHICH helps you provision projects....

....that includes source code, work items, iterations, service connections, AND build and release pipelines....

(suggestions in all caps)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: effb8fd9-ac4a-e3aa-f8bd-62cc45db3d62
* Version Independent ID: bdd12bec-6789-4178-cc6a-c3c31ae18459
* Content: [What is the Azure DevOps Services Demo Generator?](https://docs.microsoft.com/en-us/azure/devops/demo-gen/?view=azure-devops#feedback)
* Content Source: [docs/demo-gen/index.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/demo-gen/index.md)
* Product: **devops**
* Technology: **devops-new-user**
* GitHub Login: @thomps23
* Microsoft Alias: **sdanie**

**Comment by KathrynEE** [comment]
@Doomfist0 - Thank you for these suggestions, Am implementing them now.
