### ISSUE TITLE
Views documentation doesn't say whether views are supported for Maven

### ISSUE THREAD

**Issue by kczelusniak** [MicrosoftDocs/vsts-docs#4047]
The views documentation says:
> Views enable you to share subsets of the NuGet and npm package-versions in your feed with consumers.

But it doesn't mention Maven. It leads me to believe that views aren't supported for Maven. But I can see view related settings for Maven after clicking the `Connect to feed` button:
![image](https://user-images.githubusercontent.com/1730871/56597088-633eee80-65b7-11e9-8cb6-77ea41948ddc.png)

I also see the option to promote a Maven artifact to a higher view:
![image](https://user-images.githubusercontent.com/1730871/56597336-e2ccbd80-65b7-11e9-8bb9-8dfc38897827.png)

Is the documentation out-of-date?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1a891e9b-bf26-ea09-1da3-ebe3e57b7e26
* Version Independent ID: bf53c51c-c1c1-1931-44ef-81433746e5ec
* Content: [Views on Azure DevOps Services feeds](https://docs.microsoft.com/en-us/azure/devops/artifacts/concepts/views?view=azure-devops)
* Content Source: [docs/artifacts/concepts/views.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/artifacts/concepts/views.md)
* Product: **devops**
* Technology: **devops-artifacts**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by elbatk** [comment]
@kczelusniak ah, yeah, Views for Maven is a new feature. I'll update the docs right now, thanks for catching and reporting :)

**Comment by kczelusniak** [comment]
Great!

You probably already know this, but this means that the following page is also out-of-date:
https://docs.microsoft.com/en-us/azure/devops/artifacts/feeds/views?view=azure-devops#managing-views

**Comment by elbatk** [comment]
Hitting them both :)
