### ISSUE TITLE
Link this page under Extension Manifest Reference

### ISSUE THREAD

**Issue by chown-your-poptarts** [MicrosoftDocs/vsts-docs#4049]
It took me too long to find this page and should be linked in the Extension Manifest Reference for contribution Target IDs. I had to look in user comments to find this page. I think this section should be renamed to Contribution Targets as well.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 56437af3-75da-d219-5364-9b7927298ece
* Version Independent ID: ca01655a-9195-cf92-14b4-77ef66053dcf
* Content: [Extension Points](https://docs.microsoft.com/en-us/azure/devops/extend/reference/targets/overview?view=azure-devops)
* Content Source: [docs/extend/reference/targets/overview.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/extend/reference/targets/overview.md)
* Product: **devops**
* Technology: **devops-ecosystem**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by chcomley** [comment]
Thanks @chown-your-poptarts, I've created a user story for my backlog to address this. I'll be in touch. Thanks again!

**Comment by chcomley** [comment]
@chown-your-poptarts, I've just completed a PR with updates, which will go live this afternoon. Thanks!
