### ISSUE TITLE
Aside notes for "3. Do the upgrade!" could use improvement

### ISSUE THREAD

**Issue by ErikNoren** [MicrosoftDocs/vsts-docs#405]
Under item #3 in the aside there are references to steps that need to be taken to upgrade to TFS 2015 which is specific to that version. This document is more generally titled as upgrading to the latest TFS version and is the landing result for links from a TFS to VSTS migration guide PDF (https://www.microsoft.com/en-us/download/details.aspx?id=54274)

I would suggest one of the following:
 - The aside be rewritten to be more general about the possible need for intermediate upgrades from older versions with a reference to another doc if one exists
 - The aside be updated to reference TFS 2018 (which would require maintenance with each new TFS version)
 - Embed a scaled version of the upgrade path matrix image which can be found at the top of the TFS 2018 release notes (https://docs.microsoft.com/en-us/visualstudio/releasenotes/tfs2018-update1) or Page 26 of the TFS to VSTS migration guide PDF whose download link is above (which would require maintenance with each new TFS version)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 62f1c723-08ef-f40b-aa20-d6ae348dd256
* Version Independent ID: 410df71f-cfc2-c583-e351-24189a84094c
* Content: [Upgrade your TFS deployment](https://docs.microsoft.com/en-us/vsts/tfs-server/upgrade/get-started?utm_source=ms&utm_medium=guide&view=tfs-2018)
* Content Source: [docs/tfs-server/upgrade/get-started.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/tfs-server/upgrade/get-started.md)
* Service: **unspecified**
* GitHub Login: @douge
* Microsoft Alias: **elbatk**

**Comment by elbatk** [comment]
It looks like the upgrade matrix was added, so I'll close this :) Thank you @ErikNoren ! Sorry for the abnormally long delay here.
