### ISSUE TITLE
Release Flow Pipelines

### ISSUE THREAD

**Issue by murraj** [MicrosoftDocs/vsts-docs#4050]
The "Release Flow" documentation at the following URL is great: https://docs.microsoft.com/en-us/azure/devops/learn/devops-at-microsoft/release-flow. 

The one thing that would be very helpful is another page documenting how you would setup the pipelines (build and release) for a project that uses the release-flow branching strategy. For example, let's say developers have their own personal development environment, they share one or more non-production environments (such as DEV and QA), and there is a production environment.  What would be a good build/release pipeline? When are builds/releases kicked off? Do you do a build after every pull request into master? When do you create a release after each build or manually create a release when you want to push to non-production environment DEV?

Thanks!

**Comment by steved0x** [comment]
@murraj I have forwarded this to the authors and it is on their backlog, sorry for the long delay in following up.
