### ISSUE TITLE
Can't find the "Report build status" / "Tag sources" options in the YAML schema

### ISSUE THREAD

**Issue by jcleavel** [MicrosoftDocs/vsts-docs#4053]
Regular WYSIWYG build definitions have options under the "Get sources" stage for GitHub Enterprise called "Report build status" and "Tag sources". Are these exposed via the YAML build definitions in any way?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7458d5b2-1bb7-7d87-7ce6-2b0c430b0155
* Version Independent ID: edf5bbd3-a3f0-5426-e985-31290f8afd05
* Content: [YAML schema - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema)
* Content Source: [docs/pipelines/yaml-schema.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/yaml-schema.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @vtbassmatt
* Microsoft Alias: **macoope**

**Comment by vtbassmatt** [comment]
Neither of these are supported in YAML. "Report build status" is a feature with Azure Repos, I don't believe it works with GHE. "Tag sources" is something we're considering the best way to bring forward: it's probably not a pipeline setting, but rather a task you can drop in.

**Comment by jcleavel** [comment]
"Report build status" is most certainly a feature for the other source control providers:

![image](https://user-images.githubusercontent.com/30474698/56611899-d4869d80-65c7-11e9-8c12-6d53ab5a6a19.png)

**Comment by vtbassmatt** [comment]
My mistake, I misread the docs and didn't realize we posted commit status to GitHub. The more you know!

In YAML pipelines, especially against GitHub, we don't want to require all pipelines to have write access back to the repo. But we don't have a way to conditionalize that, either, especially against GitHub.com using the app. My preferred solution is a task either in the box or on the Marketplace, but we haven't gotten to that work yet. @DavidStaheli FYI.

**Comment by DavidStaheli** [comment]
This is in a rough state right now, but you can get to these settings for GitHub pipelines by clicking Edit to edit the pipeline, click the "..." context menu and selecting Triggers.  That brings you to the classic designer where you can click the YAML tab, and finally select the "Get sources" row to change the settings.

![image](https://user-images.githubusercontent.com/1767415/56656582-e3229280-6663-11e9-86dc-80ae9eedeb0d.png)

**Comment by stevengibbszions** [comment]
> This is in a rough state right now, but you can get to these settings for GitHub pipelines by clicking Edit to edit the pipeline, click the "..." context menu and selecting Triggers. That brings you to the classic designer where you can click the YAML tab, and finally select the "Get sources" row to change the settings.
> 
> ![image](https://user-images.githubusercontent.com/1767415/56656582-e3229280-6663-11e9-86dc-80ae9eedeb0d.png)

Any chance this has made its way into the YAML spec?  Would love to have my builds report status without having to manually check that box.
