### ISSUE TITLE
Authorize resource button does nothing

### ISSUE THREAD

**Issue by robsteen** [MicrosoftDocs/vsts-docs#4054]
I click the button and it says "resources authorized", but if I refresh the page or queue a new build I get the same error and see the button again

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee4ec9d0-e0d5-4fb4-7c3e-b84abfa290c2
* Version Independent ID: 3e2b80d9-30e5-0c48-49f0-4fcdfedf5eee
* Content: [Resources - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/resources?view=azure-devops#feedback)
* Content Source: [docs/pipelines/process/resources.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/resources.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @vtbassmatt
* Microsoft Alias: **alewis**

**Comment by VidyaKukke** [comment]
Yes I am experiencing the same issue. @robsteen I was trying to add "ACR" registry to be accessible in my pipeline so had picked service connection to "Docker Registry". As a workaround I picked ARM type in service connection instead  and now I'm able to kick off my pipeline without any authorization errors. FYI.

**Comment by vtbassmatt** [comment]
Please file an issue on [Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html), since it's a product bug. Thanks.

**Comment by vtbassmatt** [comment]
Ah, checked with some folks internally and this is a known issue. We're working on a fix right now.

**Comment by dapalmi** [comment]
@vtbassmatt Can you please add a link to the open issue, since I still have the same problem...

**Comment by vtbassmatt** [comment]
@dapalmi sure: https://developercommunity.visualstudio.com/content/problem/543727/using-containerized-services-in-build-pipeline-wit.html#reply-559534
