### ISSUE TITLE
Where are output files written for this task?

### ISSUE THREAD

**Issue by prabhushrikant** [MicrosoftDocs/vsts-docs#4055]
I would like to grab the output csv file generated out of this task and process it to calculate 95% percentile , also add couple of other extra columns to my csv file , such as x-request-id , so that in case of error, I can lookup the failing request with x-request-id in splunk.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd21d5d3-fc82-49e1-5637-37a1f3d1c359
* Version Independent ID: 0b1e2ca1-0c0b-19ab-002a-58751774a459
* Content: [Cloud-based Apache JMeter Load Test task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/test/run-jmeter-load-test?view=azure-devops#feedback)
* Content Source: [docs/pipelines/tasks/test/run-jmeter-load-test.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/test/run-jmeter-load-test.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @thomps23
* Microsoft Alias: **dastahel**

**Comment by prabhushrikant** [comment]
Any update on this? It's kinda urgent for us to have a pipeline based approach for load testing.

**Comment by PBoraMSFT** [comment]
@prabhushrikant - the task runs a cloud-load test with JMeter. It does not produce files / make the results available on the agents. The results of the JMeter test and its output can be found in the load test hub under Test Plans. See https://docs.microsoft.com/en-us/azure/devops/test/load-test/get-started-jmeter-test?view=azure-devops

Please note that we announced the deprecation of the cloud load testing service earlier this year and it will be discontinued on March 31st, 2020. Given this, we will not be making any further enhancements to the experience here. Closing this issue.
