### ISSUE TITLE
Can't start the task

### ISSUE THREAD

**Issue by prabhushrikant** [MicrosoftDocs/vsts-docs#4056]
I keep receiving following error, when I add this task to my pipeline. 

```##[error]The current operating system is not capable of running this task. That typically means the task was written for Windows only. For example, written for Windows Desktop PowerShell.```

Agent used for my pipeline Ubuntu 16.04, with Core Powershell, Also tried Hosted VS 2017 agent which comes with azure powershell. Both agents failed to run this task.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd21d5d3-fc82-49e1-5637-37a1f3d1c359
* Version Independent ID: 0b1e2ca1-0c0b-19ab-002a-58751774a459
* Content: [Cloud-based Apache JMeter Load Test task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/test/run-jmeter-load-test?view=azure-devops#feedback)
* Content Source: [docs/pipelines/tasks/test/run-jmeter-load-test.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/test/run-jmeter-load-test.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @thomps23
* Microsoft Alias: **dastahel**

**Comment by prabhushrikant** [comment]
I was able to get this resolved by using Hosted VS 2017 agent pool.

**Comment by thomps23** [comment]
@prabhushrikant  Thanks for following up with the fix you discovered. We'll review the content with this information.
