### ISSUE TITLE
Visual Studio Version dropdown

### ISSUE THREAD

**Issue by drinkwater99** [MicrosoftDocs/vsts-docs#4058]
The Visual Studio Version dropdown does not contain "Visual Studio 2019", it only contains up to Visual Studio 2017. Is this normal ?

**Comment by KathrynEE** [comment]
@drinkwater99 - Could you provide a URL where you are seeing this behavior.

**Comment by KathrynEE** [comment]
@drinkwater99 - Hi - I'm closing this issue. Without a URL of the page you are seeing this behavior, there isn't much we can do. If you have more information, please reopen this issue.

**Comment by goelakhil** [comment]
Hi, I'd like to reopen this issue, as i am also seeing the same behavior. Although, i cannot sent you the URL as its secured URL for my organization, yet, i am attaching a screen shot of the same where in we see "The Visual Studio Version dropdown does not contain "Visual Studio 2019", it only contains up to Visual Studio 2017".
Please help
![vs build version](https://user-images.githubusercontent.com/39486497/58930738-657d9680-877a-11e9-9aae-5194021a0e3d.PNG)

**Comment by nschonni** [comment]
Probably an issue for https://github.com/microsoft/azure-pipelines-tasks, but might be because you're running an older version of https://github.com/microsoft/azure-pipelines-agent that is shipped with an older task

**Comment by goelakhil** [comment]
> Probably an issue for https://github.com/microsoft/azure-pipelines-tasks, but might be because you're running an older version of https://github.com/microsoft/azure-pipelines-agent that is shipped with an older task

Hi, Is there any update on this issue being worked upon.
Also, we've checked and are running the updated versions of https://github.com/microsoft/azure-pipelines-agent. Therefore, not sure why we are still facing it.

**Comment by nschonni** [comment]
No clue, this is the repo for the docs so product issues usually get bounced to the agent repos that I pointed out, or the MS bug tracker https://developercommunity.visualstudio.com/spaces/21/index.html

**Comment by goelakhil** [comment]
So, in that case do we need to install Visual studio 2019 on TFS Build Servers/Agents to get 2019 version available?

> No clue, this is the repo for the docs so product issues usually get bounced to the agent repos that I pointed out, or the MS bug tracker https://developercommunity.visualstudio.com/spaces/21/index.html

So, in that case do we need to install Visual studio 2019 on TFS Build Servers/Agents to get 2019 version available?
