### ISSUE TITLE
Order file documentation bug

### ISSUE THREAD

**Issue by mwolford** [MicrosoftDocs/vsts-docs#4060]
Above in the "Change the page sequence, add or update a .order file" it states "Each entry should mirror the file name with dashes replaced with a space and without the .md file type. ".  I have found this is incorrect and I have to format it as same as the MD file but only no .md at the end.  Meaning you leave the -.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8d4fe5c7-0ab6-a0e4-4a6e-f98d0355f49a
* Version Independent ID: ce022fef-054d-cdc2-43e9-a8ee3b8fb592
* Content: [Publish Markdown files from a Git repository to a wiki in Azure DevOps - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/project/wiki/publish-repo-to-wiki?view=azure-devops#feedback)
* Content Source: [docs/project/wiki/publish-repo-to-wiki.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/project/wiki/publish-repo-to-wiki.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @mwolford, thanks for reaching out. I've created a user story to address this. Have a great day!

**Comment by chcomley** [comment]
Hi @mwolford, We've published an update to the article. Thanks very much for your feedback!
