### ISSUE TITLE
Install-Module does not work 'Could not get response from query' when Register-PSRepository is ran with v3 endpoint

### ISSUE THREAD

**Issue by stephentung-tec** [MicrosoftDocs/vsts-docs#4063]
For anyone like me who was struggling to complete the last `Install-Module` step, beware it does not seem to work when `Register-PSRepository` is ran with a v3 nuget endpoint (which Azure DevOps suggests you use). 

```
WARNING: Could not get response from query
'https://pkgs.dev.azure.com/executivecentre/_apis/packaging/4195951b-9f46-4fbb-8dae-75019870fcdc/nuget/commitLog/9a9
fb5d43cc3496e94a670054a121492'.
PackageManagement\Install-Package : No match was found for the specified search criteria and module name
'Install-TecDeploymentPrerequisites'. Try Get-PSRepository to see all available registered module repositories.
At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1:1772 char:21
+ ...          $null = PackageManagement\Install-Package @PSBoundParameters
+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Microsoft.Power....InstallPackage:InstallPackage) [Install-Package],
    Exception
    + FullyQualifiedErrorId : NoMatchFoundForCriteria,Microsoft.PowerShell.PackageManagement.Cmdlets.InstallPackage
```

I am using PowerShellGet v1.0.0.1, the default for most Windows machines I believe.

If the v2 endpoint is registered instead (which this article suggests to use), then things worked fine for me.

Maybe a footnote should be added about v3 not working?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 35b3cd51-b365-433b-9149-697582d64e88
* Version Independent ID: 1cb1f4a3-5928-223d-592f-f3462fef4e4c
* Content: [Use Azure Artifacts as a private PowerShell repository](https://docs.microsoft.com/en-us/azure/devops/artifacts/tutorials/private-powershell-library?view=azure-devops)
* Content Source: [docs/artifacts/tutorials/private-powershell-library.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/artifacts/tutorials/private-powershell-library.md)
* Product: **devops**
* Technology: **devops-artifacts**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by chcomley** [comment]
Hi @stephentung-tec, thanks so much for reaching out. I'm glad it worked out for you in the end. I've created a user story for my backlog to address this. Thanks again!

**Comment by chasewilson** [comment]
Hi @stephentung-tec, Thank you again for the feedback. I ran through the process and you are correct that you have to define a v2 endpoint as PowerShell doesn't support NuGet v3. Here is a Note specifying this under the copy block:
![image](https://user-images.githubusercontent.com/31453523/58279250-c22c8a80-7d52-11e9-8f58-88bd67df9564.png)
[https://docs.microsoft.com/en-us/azure/devops/artifacts/tutorials/private-powershell-library?view=azure-devops#connecting-to-the-feed-as-a-powershell-repo](url)

I believe that clarifies correctly. However, if you have more feedback or feel like it's not clear enough, the input is greatly appreciated!

**Comment by Apholisha** [comment]
I've been trying to push a package to a v2 url but it either doesn't show up in the feed, or it shows up in the v3 list. 
I'm not sure that AzureDevOps feeds suppord a v2 feed at all.
