### ISSUE TITLE
StandingSetlementInstrucions

### ISSUE THREAD

**Issue by CEO1980** [MicrosoftDocs/vsts-docs#4064]
Thank you for your feedback!

The issues in this repo are for documentation feedback.

If you are submitting your documentation feedback issue directly through GitHub, please provide the URL of the article so we can route the feedback to the correct author.

Please report Azure DevOps or TFS software bugs, feedback, or questions in the [Azure DevOps Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html).

**Comment by thomps23** [comment]
Looks like the Issue dropped your feedback, could you please comment on this issue with your feedback and topic its associated with?

**Comment by CEO1980** [comment]
<standard_settlement_instructions_dtc_alert_assyst>

**Comment by WilliamAntonRohm** [comment]
@CEO1980 -- please provide more context so we can pursue your issue.

**Comment by WilliamAntonRohm** [comment]
I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
