### ISSUE TITLE
Cycle Time calculation doesn't appear to follow the rules as documented

### ISSUE THREAD

**Issue by thecontrarycat** [MicrosoftDocs/vsts-docs#4065]
The article states:
&gt; Cycle time is calculated from first entering an In Progress state to entering a Completed state

However, for work items that return to In Progress after being set to Done, the Cycle Time seems to calculated like this:
&gt; Cycle time is calculated using the difference between the last time it entered an In Progress state and the last time it entered a Completed state.

This is unintuitive - and causes misleading charts - as I'd expect the calculation to be the difference between the first time it went to In Progress and the last time it went to Completed (i.e. ignoring the close/reopen in the calculation)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1e813268-5e00-7c84-2479-3068e27ea443
* Version Independent ID: 269b0352-2a6a-d5c9-96a3-68d5ce93c616
* Content: [Cycle time and lead time control charts - Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/report/dashboards/cycle-time-and-lead-time?view=azure-devops#feedback)
* Content Source: [docs/report/dashboards/cycle-time-and-lead-time.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/report/dashboards/cycle-time-and-lead-time.md)
* Product: **devops**
* Technology: **devops-analytics**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by angurusw** [comment]
@thecontrarycat, would you be able to email me at Anand.Guruswamy@microsoft.com with screenshots of this issue happening? I can help you take a look and diagnose this.

**Comment by KathrynEE** [comment]
Closing as angurusw has followed up.
