### ISSUE TITLE
replace expression

### ISSUE THREAD

**Issue by gaborbernat** [MicrosoftDocs/vsts-docs#4069]
Job names can only contain a subset of characters it could be nice to be able to replace other characters with legal ones.

**Comment by thomps23** [comment]
@gaborbernat If you could provide more context by providing a link to the topic this is related to that would help us triage this Issue.

**Comment by gaborbernat** [comment]
@thomps23 job names can only contain underscore and ASCII characters. We need an expression that allows us doing this normalization when the job name is an argument to a template, where the argument can get any character (such as ``-``).

**Comment by gaborbernat** [comment]
not sure I understand why this is a documentation bug rather than a feature request 🤔

**Comment by steved0x** [comment]
@gaborbernat The vsts-docs repo contains our documentation and the issues in this repo are intended for documentation feedback. From your question above, are you asking one of the below:

* Asking how to do a substitution of invalid characters in job names when they are passed in as a template parameter? For example by providing a sample in the docs
* Giving us the feedback that this is a gap in the product, and we should add a new feature that allows you to substitute the invalid characters in a job name that is passed as a template

If you are suggesting a new feature to be added, please file a feature request [here](https://developercommunity.visualstudio.com/spaces/21/index.html)

If we need to make an update to one of our docs about jobs, please let us know the URL of the article and we will try to update it to provide the missing information.

Thank you for your feedback.
