### ISSUE TITLE
Research Spikes

### ISSUE THREAD

**Issue by kamranrahman** [MicrosoftDocs/vsts-docs#407]
Is there a way to see research spikes on backlogs and boards? I've tried to get it visible in the people-view board, but that doesn't seem to work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 415554cc-34ca-621f-e12c-e6e084739395
* Version Independent ID: 6d70829a-71a0-0e01-aed9-151649755e93
* Content: [Show bugs on backlogs and boards - VSTS & TFS](https://docs.microsoft.com/en-us/vsts/work/customize/show-bugs-on-backlog?view=vsts#feedback)
* Content Source: [docs/work/customize/show-bugs-on-backlog.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/work/customize/show-bugs-on-backlog.md)
* Service: **unspecified**
* GitHub Login: @douge
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@kamranrahman  - Thank you for your inquiry. The people-view board that you mention is a Task board and is designed to update tasks. Please review this topic, [Backlogs, boards, and plans](https://docs.microsoft.com/en-us/vsts/work/backlogs/backlogs-boards-plans?view=vsts), for details on the differences between Kanban boards and Task boards.  Usually research spikes are tracked using stories, backlog items, or requirements, If you've used these work item types, they will show up on your Kanban board.
