### ISSUE TITLE
Publishing Custom Widget But Organization Ownership Missing.

### ISSUE THREAD

**Issue by d-h-morrison** [MicrosoftDocs/vsts-docs#4079]
After following the guidance, I get this when I do the final installation step for my organization:

```We did not find an organization for which you are an owner or a member.```

_Clearly I did something wrong, but what?_

What did I do wrong?  Guidance states:

**_Create a publisher
All extensions, including extensions from Microsoft, live under a publisher. Anyone can create a publisher and publish extensions under it. You can also give other people access to your publisher if a team is developing the extension._**

**_Next up we're told to:_**
```Sign in to the Visual Studio Marketplace management portal
If you don't already have a publisher, you'll be prompted to create one.
In the Create Publisher form, enter your name in the publisher name field. The ID field should get set automatically based on your name
```
_________

I'm a bit perplexed.  Did I miss a step?  Is the guidance incorrect?  How do I let the portal know about my "organization for which [I am] an owner or a member?"

David

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 14955ee9-29f2-46fe-3a8d-a42666f53ffc
* Version Independent ID: 5d417cd0-a671-ee30-8fca-5f8b0addd328
* Content: [Develop a web extension for Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/extend/get-started/node?view=azure-devops#feedback)
* Content Source: [docs/extend/get-started/node.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/extend/get-started/node.md)
* Product: **devops**
* Technology: **devops-ecosystem**
* GitHub Login: @willsmythe
* Microsoft Alias: **wismythe**

**Comment by d-h-morrison** [comment]
Hi all, what's the status of this?  Any updates?  Any guidance?  Working on this?  Bagged it?  Rip Van Winkling back in 20?

**Comment by oskaremil** [comment]
Do you have access to a Azure DevOps instance by going to dev.azure.com and logging in ?

**Comment by d-h-morrison** [comment]
Yes, we have an instance that is in use for various team projects.

**Comment by chcomley** [comment]
Hi @d-h-morrison, I'm closing this issue, as it's stale and close to 1 year old. Please @mention me if this remains an issue or you have further questions. Thanks and it really looks like we dropped the ball on this one, sorry.

**Comment by cloghead** [comment]
I got the same error, but after some time I realized that I had missed/skipped the part in the manual where it said that you have to share the extension with your organization, otherwise you cannot install it. The error message is quite misleading.
