### ISSUE TITLE
Couldn't run in my pipeline with following error.

### ISSUE THREAD

**Issue by prabhushrikant** [MicrosoftDocs/vsts-docs#4082]
Step references task 'Delay' at version '1.1.6' which is not valid for the given job target.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 05e99925-c1f9-5041-311f-39469c124d85
* Version Independent ID: 81b0a6bf-d7cb-7208-3759-3455efc5bf13
* Content: [Delay task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/delay?view=azure-devops)
* Content Source: [docs/pipelines/tasks/utility/delay.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/utility/delay.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by RoopeshNair** [comment]
@shahban for Gate/Server phase tasks

**Comment by shashban** [comment]
Looks like you have a specific task version referred in the yaml.
Can you confirm your yaml looks like the following?

`- job: RunsOnServer
    pool: Server
    steps:
    - task: Delay@1
      inputs:
        delayForMinutes: '1'`

**Comment by shashban** [comment]
Closing the issue due to no response from the customer

**Comment by felaray** [comment]
same problem

msg:  

> Job Job: Step references task 'Delay' at version '1.1.8' which is not valid for the given job target. 

`# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:

- task: NuGetToolInstaller@1

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: true

- task: Delay@1
  inputs:
    delayForMinutes: '05'

- task: CopyFiles@2
  inputs:
    targetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(build.artifactStagingDirectory)\WebApp.zip" /p:DeployIisAppPath="Default Web Site"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'


`

**Comment by M0ns1gn0r** [comment]
@MS please add an understandable error message instead of this obscure one.
