### ISSUE TITLE
Azure Boards app does not exist

### ISSUE THREAD

**Issue by mregni** [MicrosoftDocs/vsts-docs#4083]
There is no Azure Boards app in the marketplace making this article a bit useless.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ffffb75a-67a8-f005-9980-de1270efbabf
* Version Independent ID: 4ae8f3f0-24e2-05f7-5c2e-d0a23aa330c0
* Content: [Learn how to connect/integrate GitHub with Azure Boards - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/github/?view=azure-devops#feedback)
* Content Source: [docs/boards/github/index.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/boards/github/index.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by alexcnichols** [comment]
Stay tuned. The Azure Boards app for GitHub is in preview. Watch for public availability in the GitHub Marketplace and announcement in our release notes and blog soon.
