### ISSUE TITLE
This page is missing the actual tools links

### ISSUE THREAD

**Issue by StingyJack** [MicrosoftDocs/vsts-docs#4084]
Links like Microsoft.TeamFoundationServer.Client, ExtendedClient, or Microsoft.VisualStudio.Services.Client. They used to be around here somewhere. Where are those docs now?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 878f028a-4418-1f6c-bf27-d469b249b621
* Version Independent ID: 7209b942-b6ab-e9f6-6cfd-bd5d89ea9aa8
* Content: [Tools and clients that connect - Azure DevOps - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/user-guide/tools?view=azure-devops#desktop-client-developer-tools)
* Content Source: [docs/user-guide/tools.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/user-guide/tools.md)
* Product: **devops**
* Technology: **devops-new-user**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hey @StingyJack. I'm looking into this and will be in touch. Thanks for reaching out.

**Comment by chcomley** [comment]
Try this: https://docs.microsoft.com/en-us/azure/devops/integrate/get-started/client-libraries/samples?view=azure-devops

**Comment by StingyJack** [comment]
@chcomley - Thanks!  How/where did you manage to locate that? Can this page be linked to it? 

Also, the .net client libraries reference link on that page seems to be broken. It just goes to a docs home page.
![image](https://user-images.githubusercontent.com/15381181/56940884-11c6c000-6adf-11e9-9af1-d5cea97acfd0.png)

**Comment by chcomley** [comment]
@StingyJack, I got the link from a colleague and will certainly incorporate it into the tools article. I've created a user story to capture this work. The [.NET link](https://docs.microsoft.com/en-us/azure/devops/integrate/concepts/dotnet-client-libraries?view=azure-devops) works for me. Please let me know if you have any further suggestions or questions. I'll be closing this issue, however you can still send a comment, if needed. Thank you for the feedback!
