### ISSUE TITLE
This should also include information about what TLS versions are supported...

### ISSUE THREAD

**Issue by StingyJack** [MicrosoftDocs/vsts-docs#4085]
... as well as any problems with using FIPS, etc for clients, application servers, and sql servers.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a12963af-3340-7a74-569e-47bd40632262
* Version Independent ID: a23b6117-0cbe-0104-e820-ac88817624ee
* Content: [Troubleshoot connecting project - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/user-guide/troubleshoot-connection?view=tfs-2015)
* Content Source: [docs/user-guide/troubleshoot-connection.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/user-guide/troubleshoot-connection.md)
* Product: **devops**
* Technology: **devops-security**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
@StingyJack Thanks for your suggestions. I've created a user story on my backlog to address this. Thanks!

**Comment by chcomley** [comment]
Hi @StingyJack, Could you please let me know which version of the doc/product it is that you're referring to? Can you further explain what you mean by mentioning FIPS, as it's not related to connectivity issues? Thanks in advance for any further information.

**Comment by chcomley** [comment]
Hi @StingyJack at this point, we don't believe an update to the article is necessary, however if you feel differently, could you please create a new issue, mentioning your version of the product and any other clarifying information? If you need support of any kind, please go here: https://visualstudio.microsoft.com/vs/support/#talktous
We very much appreciate you taking the time to provide feedback. Have a great weekend!

**Comment by StingyJack** [comment]
Does azure devops work with TLS 1.0, 1.1, and 1.2 ?

**Comment by chcomley** [comment]
@StingyJack, Do you have Azure DevOps Services, or a version of Azure DevOps Server? Adding @aaronhallberg.

**Comment by StingyJack** [comment]
Currently the former. I had to change some TLS settings at the OS level for a project and found later that I couldnt connect to DevOps and had some cryptic error. 

A statement of what TLS version is supported for Azure Dev OPs Services or Server on this page would probably be useful as at least a hint to someone having a connection problem related to TLS like I was having.
