### ISSUE TITLE
Allow for external invitations" cannot be found under Organization Settings

### ISSUE THREAD

**Issue by fpiazza99** [MicrosoftDocs/vsts-docs#4086]
I too did not see the Add New User option until i clicked on the Active Directory menu item, then extensions, then Users?? May be a bug with the Users feature of the Portal?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b6db4fba-7322-16bc-3431-6b8f933a84bf
* Version Independent ID: a20bd1b0-06d7-8f49-30d2-25c5e188b674
* Content: [Add, invite external users, guest users to your organization - Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/add-external-user?view=azure-devops)
* Content Source: [docs/organizations/accounts/add-external-user.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/accounts/add-external-user.md)
* Product: **devops**
* Technology: **devops-accounts**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @fpiazza99, This is a permissions thing. Non-admins can invite other people to their organization via project invitations, team invitations, assigning a new user a work item, and so on. Only people in the organization's Project Collection Administrators (PCA) group can add users using the "add new user" in the Organization settings. Please let me know if you have any further questions. Thanks!
