### ISSUE TITLE
"Print then cancel" workaround to export data

### ISSUE THREAD

**Issue by bmordue** [MicrosoftDocs/vsts-docs#4088]
"Q: Can I export the test plan to share or review offline?
A: Yes, you can export test plans, test suites, and test cases. Select the details that you want in the report. Then email or print this report for review."

This 'print to export' workaround is also mentioned in "Q: When I export a test plan, can I just view the data or copy it to a Word document?".

This is a hacky, unintuitive workaround for what seems to me like a basic, widely required feature: reporting on test outcomes.
Is data export (specifically, for test outcomes) likely to appear in ADO as a first-class feature?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 985ecee3-e347-43bb-5ed2-08ce3aee7621
* Version Independent ID: fdf465fc-a9e1-0198-2e8c-e859c74252b3
* Content: [FAQs and problem solutions - Azure Test Plans](https://docs.microsoft.com/en-us/azure/devops/test/reference-qa?view=azure-devops)
* Content Source: [docs/test/reference-qa.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/test/reference-qa.md)
* Product: **devops**
* Technology: **devops-test**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by steved0x** [comment]
@bmordue That is a good question, I do see this item on the [Azure DevOps Feature Timeline - Features under development](https://docs.microsoft.com/en-us/azure/devops/release-notes/#features-under-development)

Search for `test progress report` and click the link, which takes you to that work item [here](https://dev.azure.com/mseng/AzureDevOpsRoadmap/_workitems/edit/1424595). Does that match the new feature you are describing?

If not, you can file a feature request directly with the team [here](https://developercommunity.visualstudio.com/spaces/21/index.html).

Thank you for your feedback!
