### ISSUE TITLE
Dockerfile is missing zip and unzip packages

### ISSUE THREAD

**Issue by joao-paulo-costa** [MicrosoftDocs/vsts-docs#4089]
When you run a Job with an "ArchiveFiles@2" task and "archiveType" set to 'zip' it fails.

In order for it to work, just add "zip" and "unzip" to the Dockerfile:

RUN apt-get update \\
&& apt-get install -y --no-install-recommends \\
        ca-certificates \\
        curl \\
        jq \\
        git \\
        iputils-ping \\
        libcurl3 \\
        libicu55 \\
        **zip \\
        unzip**

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b31d4f6c-d16d-2ba1-1294-6aa94e328046
* Version Independent ID: 88aec599-4410-697d-1002-1c41b1c17bb6
* Content: [Running the agent in Docker - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/docker?view=azure-devops#feedback)
* Content Source: [docs/pipelines/agents/docker.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/agents/docker.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @juliobbv
* Microsoft Alias: **alewis**

**Comment by vtbassmatt** [comment]
The Dockerfile we specify won't run every task out there, not even our in-box ones. It's worth mentioning that - fixing now. Thanks!

**Comment by vtbassmatt** [comment]
Oops, we're on documentation lockdown this week. I have a PR prepared and will complete it next week.
