### ISSUE TITLE
Typo: fist should be first

### ISSUE THREAD

**Issue by dburnison** [MicrosoftDocs/vsts-docs#4092]
This statement needs to be updated: "taking effect on the **fist** day of the next month." should be "taking effect on the **first** day of the next month."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 52303279-70fd-a0f6-cc6f-96bf73ed8c32
* Version Independent ID: cb30fbe3-b069-2665-d8da-9f714a23290a
* Content: [Frequently asked questions about billing management - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/billing/billing-faq?view=azure-devops&viewFallbackFrom=DevOps)
* Content Source: [docs/organizations/billing/billing-faq.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/billing/billing-faq.md)
* Product: **devops**
* Technology: **devops-billing**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Thanks so much, @dburnison. We'll get this corrected. Have a great day.
