### ISSUE TITLE
Link for cherry-picking

### ISSUE THREAD

**Issue by spottedmahn** [MicrosoftDocs/vsts-docs#4103]
>The release branch strategy extends the basic feature branch workflow to handle releases. Your team doesn't have to adopt any new version control process other than the cherry-pick to port changes.

What about a link for "cherry-pick" in the above?  If it's something new the team must adopt it would be nice to learn more about it.

Is there some existing doc(s) on cherry-picking?

Thoughts? 💭

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe168fc3-2ed2-b3e6-ce30-cac721165ceb
* Version Independent ID: 8d63fbd7-12c4-9a94-92f6-969e7eb41037
* Content: [Git branching guidance - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/git-branching-guidance?view=azure-devops#review-and-merge-code-with-pull-requests)
* Content Source: [docs/repos/git/git-branching-guidance.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/repos/git/git-branching-guidance.md)
* Product: **devops**
* Technology: **devops-code-git**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
@spottedmahn We have some content:

* [https://docs.microsoft.com/en-us/azure/devops/repos/git/cherry-pick?view=azure-devops&tabs=command-line](https://docs.microsoft.com/en-us/azure/devops/repos/git/cherry-pick?view=azure-devops&tabs=command-line)
* [Commit details](https://docs.microsoft.com/en-us/azure/devops/repos/git/commit-details?view=azure-devops&tabs=visual-studio#what-actions-can-you-perform)
* [Cherry pick a pull request](https://docs.microsoft.com/en-us/azure/devops/repos/git/pull-requests?view=azure-devops#cherry-pick-a-pull-request)

Would one of these work or do we need some new/additional cherry-pick content to link to from the spot you mentioned?

**Comment by spottedmahn** [comment]
Hi @steved0x - thanks for the links!

I like: [Cherry pick a pull request](https://docs.microsoft.com/en-us/azure/devops/repos/git/pull-requests?view=azure-devops#cherry-pick-a-pull-request)

(though I wish that doc section had some screenshots but that's a different issue 😊)

**Comment by spottedmahn** [comment]
I'm curious, was a change made?  If so, PR #?
