### ISSUE TITLE
Scheduled stage triggers docs are misleading

### ISSUE THREAD

**Issue by rosshamish** [MicrosoftDocs/vsts-docs#4105]
&gt; Note that, with scheduled triggers, a new deployment is created that deploys the artifacts **from the most recently available release**, overwriting any previously deployed artifacts for the stage.

This is misleading and is not the observed behavior. In fact, what happens is that when multiple deployments of the same scheduled stage queue up, when the schedule time happens, they all deploy sequentially. To get this behavior it's necessary to incorporate Queuing Policy, specifically "Deploy latest and cancel others" as described in https://docs.microsoft.com/en-us/azure/devops/pipelines/release/environments?view=azure-devops#queuing-policies.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d9e313c5-9120-9172-bc27-c21d10fcd5ae
* Version Independent ID: 1a837182-591f-3cbc-1632-7b50d857b13c
* Content: [Release triggers for stages, branches, and pipelines - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/triggers?view=azure-devops#stage-scheduled-triggers)
* Content Source: [docs/pipelines/release/triggers.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/release/triggers.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by RoopeshNair** [comment]
@shashban - resident expert on releases

**Comment by shashban** [comment]
Thanks. That is correct. We'll fix the docs to reflect the correct behavior.
