### ISSUE TITLE
Video Embedded Error.

### ISSUE THREAD

**Issue by camilettomsft** [MicrosoftDocs/vsts-docs#4106]
[!Video https://channel9.msdn.com/Events/Connect/2017/T251/player]

Thanks, team. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c05a00ec-8714-dd48-26cc-53b95ef323b4
* Version Independent ID: 712ec787-c324-4acc-c824-031525de026b
* Content: [Create Power BI reports from Analytics service - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/report/powerbi/index?view=azure-devops#videos)
* Content Source: [docs/report/powerbi/index.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/report/powerbi/index.md)
* Product: **devops**
* Technology: **devops-analytics**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
AB#1514308

**Comment by KathrynEE** [comment]
@camilettomsft - Thank you for the correction. I'll update the page to fix it.
