### ISSUE TITLE
Please show how to use gradle tasks with multiple tasks

### ISSUE THREAD

**Issue by nickform-ost** [MicrosoftDocs/vsts-docs#4109]
The commented-out examples in the snippet are quite helpful but aren't quite full reference documentation on how to compose a gradle task. My specific problem is that I'd like to run two tasks 'build' and 'test' from the one step. The schema for the Gradle@2 task suggests this is possible as the fields is plural ("tasks") but I have not found how to specify more than one.

I have tried:
```
...
   tasks: 'build,test'
...
```
which ran but resulted in error message "Task 'build,test' not found in root project"

I have also tried
```
...
  tasks:
    - 'build'
    - 'test'
...
```
which caused a failure to even queue the job (message: "/azure-pipelines.yml (Line: 18, Col: 9): A sequence was not expected"). Could you document how to use the apparent plurality of this field?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 00499395-fdc3-b150-3469-aee2f9fb7cbc
* Version Independent ID: 44e630e1-1689-2d2e-212b-3ce2baf8771f
* Content: [Gradle build and release task - Azure Pipelines](https://docs.microsoft.com/en-gb/azure/devops/pipelines/tasks/build/gradle?view=azure-devops)
* Content Source: [docs/pipelines/tasks/build/gradle.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/build/gradle.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @DavidStaheli
* Microsoft Alias: **dastahel**

**Comment by nickform-ost** [comment]
I eventually figured out that space-delimited was the right option. So:
```
...
  tasks: 'build test'
...
```
...exactly as gradle excepts on the command line. Seems obvious now but the plural field-name made me think that the Azure Pipelines wrapper was somehow managing the different tasks. Leaving the issue open so that the dev team can decide whether it merits a change.

**Comment by davidstaheli** [comment]
Thanks for reporting this. The documentation has been updated and should be live within a few days.

**Comment by nickform-ost** [comment]
Thank you!

**Comment by rabacadabra** [comment]
if more than one task is added, are they going to execute sequentially, or in parallel?
