### ISSUE TITLE
Hybrid Project Pool

### ISSUE THREAD

**Issue by tmgirvin** [MicrosoftDocs/vsts-docs#4110]
I want to create a project pool composed of (delegates to) both my org-hosted agents (an org pool) and MS hosted agents (the MS hosted pool).  If my hosted pool was first in line, my builds would be run on my infrastructure and cost MS nothing.  But, if my agents were busy or offline for some reason, the build would be picked up by the MS agents.  It would give me high-availability with low cost.  And since we can already create a project pool that defers to an org pool, couldn't we just compose a project pool from an org pool and the MS hosted pool? Or, would it deliver all the jobs to the first pool and they'd get stuck there if the agents were busy or offline?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4409a9cb-8448-edd6-da0a-243e5601aa3e
* Version Independent ID: ec15f71a-a76d-c3f9-1d31-832f92183ef4
* Content: [Agents pools - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/pools-queues?view=azure-devops)
* Content Source: [docs/pipelines/agents/pools-queues.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/agents/pools-queues.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by vijayma** [comment]
Thank you for the suggestion. This is not a capability that we currently have. Please open a suggestion ticket here: https://developercommunity.visualstudio.com/spaces/21/visual-studio-team-services.html?type=idea.
