### ISSUE TITLE
Link correction

### ISSUE THREAD

**Issue by ksiomelo** [MicrosoftDocs/vsts-docs#4111]
The correct link for the Azure Pipeline Agent Pools settings is: Azure Pipelines: https://dev.azure.com/{your_organization}/_settings/agentqueues  not https://dev.azure.com/{your_organization}/_settings/agentpools

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 344fb6c7-8770-a366-ed19-0626966be202
* Version Independent ID: 22ac2ad8-186a-3530-9a0e-fdbc860eb470
* Content: [Prepare permissions - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/prepare-permissions?view=azure-devops#feedback)
* Content Source: [docs/pipelines/agents/prepare-permissions.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/agents/prepare-permissions.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by steved0x** [comment]
@ksiomelo We have updated this content to show UI instructions on how to get there vs providing the links, if this issue is still present please reactivate and we'll take another look. Thank you.
