### ISSUE TITLE
Docker guidance shouldn't suggest passing secrets in command line parameters

### ISSUE THREAD

**Issue by dbjorge** [MicrosoftDocs/vsts-docs#4113]
Throughout the [Build, test, and push Docker container apps - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/languages/docker?view=azure-devops#feedback), the example guidance on how to use the `docker login` command suggests passing a password to the command by specifying a secret variable as a command line argument.

This guidance is not in keeping with the guidance about secret variable usage in the  [Variables documentation](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch#secret-variables), which states in an "Important" box (emphasis theirs), "**Never pass secrets on the command line.** Instead, we suggest that you map your secrets into environment variables."

Even if we're confident that the secret would be stripped out of applicable logs in this particular case, it would be nice to not be tacitly encouraging users that it's a recommended practice.

Consider instead using an environment variable for the secret and recommending a command line that uses that variable in combination with a `docker login --password-stdin` based command line.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e825c07d-2168-c0aa-782a-ef6f9c7ba95e
* Version Independent ID: 5cb6926b-215a-bf89-8e63-b2e1129e41df
* Content: [Build, test, and push Docker container apps - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/languages/docker?view=azure-devops#feedback)
* Content Source: [docs/pipelines/languages/docker.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/languages/docker.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by shashankbarsin** [comment]
I've update the entire set of docs associated with container ecosystem. The new documentation uses [Docker registry service connections](https://docs.microsoft.com/azure/devops/pipelines/library/service-endpoints?view=azure-devops#sep-docreg) for the purpose of specifying the credentials and authentication required by the Docker task when [pushing the images to the container registry](https://docs.microsoft.com/azure/devops/pipelines/ecosystems/containers/push-image?view=azure-devops).
