### ISSUE TITLE
Erroneous backtick in example

### ISSUE THREAD

**Issue by ckempo** [MicrosoftDocs/vsts-docs#4117]
Really small issue: 

"yields underlined text`" should read: "yields underlined text"

:smile:

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fa622358-f5bb-1f5c-177a-081a37b6acef
* Version Independent ID: 72f7fd16-a822-66c8-3a34-8905645ce5f2
* Content: [Markdown syntax for files, widgets, and wikis in Azure DevOps - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/project/wiki/markdown-guidance?view=azure-devops#feedback)
* Content Source: [docs/project/wiki/markdown-guidance.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/project/wiki/markdown-guidance.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Thanks for letting us know, @ckempo! I'll get this fixed within the next few days, as I've created a user story to remove the "  '  ". :)

**Comment by chcomley** [comment]
This update will be live around 4pm today. Thank you for the feedback!
