### ISSUE TITLE
The supported version of apache jmeter appears to be 3.2 which is substantially behind the current release and preventing adoption of the tool.

### ISSUE THREAD

**Issue by leparduk** [MicrosoftDocs/vsts-docs#4118]
Thank you for your feedback!

The issues in this repo are for documentation feedback.

If you are submitting your documentation feedback issue directly through GitHub, please provide the URL of the article so we can route the feedback to the correct author.

Please report Azure DevOps or TFS software bugs, feedback, or questions in the [Azure DevOps Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html).

**Comment by thomps23** [comment]
@leparduk It looks like you've encountered an issue with the product itself, rather than an issue with the documentation. To make sure it gets in front of the right people, please [submit your bug]( https://developercommunity.visualstudio.com/content/problem/post.html?space=21) here.
