### ISSUE TITLE
What exactly is the yml for the named conditions

### ISSUE THREAD

**Issue by jordonedavidson** [MicrosoftDocs/vsts-docs#4121]
This is super frustrating.  

At the very beginning of this documentation it states:

On each step and job, you can specify the conditions under which the step or job will run.
- Only when all previous tasks have succeeded
- Even if a previous task has failed, unless the build or release was canceled
- Even if a previous task has failed, even if the build was canceled
- Only when a previous task has failed
- Custom conditions

But nowhere on the page are the corresponding formulae documented.

Additionally in the full definition for the -task method "condition" is defined as a string, but it actually is a boolean.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f151218-9a11-0078-e038-f96198a76143
* Version Independent ID: 09c4d032-62f3-d97c-79d7-6fbfd89910e9
* Content: [Conditional tasks - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/conditions?view=azure-devops&tabs=yaml#feedback)
* Content Source: [docs/pipelines/process/conditions.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/conditions.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by FISHMANPET** [comment]
I played around with a task in the class editor and kept checking the YAML, this is what I've got:

- Only when all previous tasks have succeeded: Not sure, this is the "default" so it doesn't show up in the YAML, I suspect it's `succeeded()`
- Even if a previous task has failed, unless the build or release was canceled: `succeededOrFailed()`
- Even if a previous task has failed, even if the build was canceled: `always()`
- Only when a previous task has failed: `failed()`
- Custom conditions: the documentation appears to cover this, indicating that a custom condition is just an `expression` (with the above values mixed in)

It's the end of the day so I won't make a PR right now but maybe next week I'll add these to the doc and make a PR

**Comment by FISHMANPET** [comment]
also not sure what to do about the boolean thing, using `condition` in VSCode with the Azure Pipelines extension autocomplete suggests either true or false, but I think that's an issue with the condition definition not the documentation, don't know where that data comes from

**Comment by FISHMANPET** [comment]
Or, presumably, now that I think about it, those are functions that will return a true or false value, so it's technically correct that Condition requires a boolean.  And now I see that the status are documented on the expressions page, https://docs.microsoft.com/en-us/azure/devops/pipelines/process/expressions?view=azure-devops, which explains that they're functions that will return a boolean value

**Comment by jordonedavidson** [comment]
Indeed, this link does appear to answer the originally posed question:
https://docs.microsoft.com/en-us/azure/devops/pipelines/process/expressions?view=azure-devops#job-status-functions

Thanks for the investigation.

**Comment by jordonedavidson** [comment]
Although, I'm going to leave this open since these descriptions should simply be on the original page I was looking at, where they are first described.

**Comment by juliakm** [comment]
It looks like this was updated since this ticket was opened and there is now a link to the Job status functions. 

<img width="598" alt="Screen Shot 2019-11-07 at 11 17 49 AM" src="https://user-images.githubusercontent.com/64906/68406714-42537a80-0150-11ea-8a27-d516208027d8.png">
