### ISSUE TITLE
Per-Period Values for Completed Work

### ISSUE THREAD

**Issue by jitterbox** [MicrosoftDocs/vsts-docs#4127]
It would be really helpful to see an example (OData or using an analytics view) demonstrating the best way to retrieve/calculate only the value of the Completed Work that is actually completed WITHIN any given period...I assume this has to be done through comparing a given period's snapshot data with prior (period-1) snapshot data, but it's a problem we need to solve to quantify when work is being done on a per-item basis.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c8bd7960-cd48-a216-4af9-6050376501e7
* Version Independent ID: 0d2ae084-27e1-8012-d786-e07a848ae0a0
* Content: [Extend Analytics with OData - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/report/extend-analytics/index?view=azure-devops#feedback)
* Content Source: [docs/report/extend-analytics/index.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/report/extend-analytics/index.md)
* Product: **devops**
* Technology: **devops-analytics**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@jitterbox - Thank you for your request. I will put it on our content backlog and look at addressing it in an upcoming sprint.
