### ISSUE TITLE
Publish Code Coverage Results - Specify Working Directory - Feature Request

### ISSUE THREAD

**Issue by aschlicht** [MicrosoftDocs/vsts-docs#4128]
We are generating unit test source code coverage information from gcovr into a Cobertura style xml file (coverage.xml). The unit tests are built and run with ceedling and the gcov plugin generates the code coverage information with gcovr. On Azure DevOps, I'm using the Publish Code Coverage Results task to parse and display the coverage information. Our project directory is structured as follows:

- project
    - source
    - test
        - static_analysis
        - unit_test

The unit_test directory contains project.yml, which is ceedling's project file. Ceedling must be run from the unit_test directory, which then runs gcovr with the unit_test directory as its root. The resulting coverage.xml has paths like, filename="../../source/feature.c". When running the Publish Code Coverage Results task on coverage.xml, ReportGenerator.exe is able to correctly parse the coverage; however, ReportGenerator.exe reports warnings saying every source file is missing. I see the warnings no matter which directory coverage.xml is copied to. Example warning: `File '.\..\..\source\feature.c' does not exist (any more).`

I have a workaround python script that changes all `filename="../../source/feature.c"` to `filename="source/feature.c"` and outputs to cobertura.xml. I can then put the new cobertura.xml into any directory, call it with the Publish Code Coverage Results task, and ReportGenerator.exe correctly finds all files and generates html with coverage info without warnings or errors.

My feature request is to be able specify a working directory for the Publish Code Coverage Results task or a root directory for coverage.xml.

Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6ac4ff4-9839-6a6d-8d20-a25084d221ef
* Version Independent ID: bd09f139-8e69-8ea1-6671-b7bba8e17c23
* Content: [Publish Code Coverage Results task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/test/publish-code-coverage-results?view=azure-devops#feedback)
* Content Source: [docs/pipelines/tasks/test/publish-code-coverage-results.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/test/publish-code-coverage-results.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @PBoraMSFT
* Microsoft Alias: **pbora**

**Comment by thomps23** [comment]
@aschlicht To make sure it gets in front of the right people, please [submit your feature request here](https://developercommunity.visualstudio.com/content/idea/post.html?space=21).
