### ISSUE TITLE
Stop environment variables being upper-cased

### ISSUE THREAD

**Issue by benny-gold** [MicrosoftDocs/vsts-docs#4129]
I would like the variables I specify to be made available to my jobs exactly as typed in `azure-pipelines.yml` - Terraform is one example where this matters:
&gt; On operating systems where environment variable names are case-sensitive, Terraform matches the variable name exactly as given in configuration, and so the required environment variable name will usually have a mix of upper and lower case letters...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd7e0bd3-1f7d-d7b6-cc72-5ef63c31b46a
* Version Independent ID: dae87abd-b73d-9120-bcdb-6097d4b40f2a
* Content: [Variables - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch)
* Content Source: [docs/pipelines/process/variables.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/variables.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by thomps23** [comment]
@benny-gold Thanks for your feedback; we appreciate it. To make sure that this is logged in the right place, please use the [“Suggest a feature”](https://developercommunity.visualstudio.com/content/idea/post.html) option in the to file the issue.
