### ISSUE TITLE
Missing Option

### ISSUE THREAD

**Issue by Skavenger0** [MicrosoftDocs/vsts-docs#413]
https://docs.microsoft.com/en-us/vsts/build-release/apps/cd/deploy-docker-webapp?view=vsts

Step 4: App Service type: Select Web App for Containers.

Web App for Containers is not an item in the drop down list. Any ideas

**Comment by alexhomer1** [comment]
Thank you for your feedback. We are currently updating this topic because the options for VSTS have changed.
