### ISSUE TITLE
Missing node version requirement

### ISSUE THREAD

**Issue by cadsit** [MicrosoftDocs/vsts-docs#4130]
As part of setup, there is no mention of the version of Node that runs on Azure DevOps agents , which is currently 6.10.3. The current version of Node is 12.1.0 and the LTS is 10.15.3 at time of writing.

It is easy to write custom tasks under the misconception that you will be working with cutting edge features in Node and publish them to Azure DevOps only to realize that your task does not work there because your development setup is vastly different from production. I'd like this information to be more accessible so fewer people have to deal with the frustration of having to unexpectedly retro-fit their code to work with this older version of Node.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 44581f4a-93df-7507-3844-eadedf9a6cc4
* Version Independent ID: 33c7bcf0-1512-975f-5ef8-9f2a192a84ad
* Content: [Add a Build or Release Task](https://docs.microsoft.com/en-us/azure/devops/extend/develop/add-build-task?view=azure-devops#feedback)
* Content Source: [docs/extend/develop/add-build-task.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/extend/develop/add-build-task.md)
* Product: **devops**
* Technology: **devops-ecosystem**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by cadsit** [comment]
To clarify, this is not talking about the version of Node that is installed on a particular agent.

The Node executable that is responsible for running tasks is bundled in with the Azure Devops agent executable.

**Comment by cadsit** [comment]
I see from http://blog.majcica.com/2018/12/04/node10-provider-available-for-agent-v2-144-0/ that there is an option to use Node10 in the more recent versions of the agent. Would it be possible to bubble up this information?

**Comment by chcomley** [comment]
Hi @cadsit, thanks for reaching out. We’ll be back in touch shortly!

**Comment by kdubau** [comment]
1000% this. 

The documentation sets you up for failure as the preparation steps read: "The latest version of node, which can be downloaded here"  and then the sample `task.json` has:
```json
"execution": {
        "Node": {
            "target": "index.js"
        }
    }
```
..but that will use Node v6 on the agent.

The user needs to use `Node10` as @cadsit  pointed out.

**Comment by DanielHabenicht** [comment]
How come that this is not already in the documentation? 
Just wasted 20 minutes of my life for this.
