### ISSUE TITLE
Argument Names Missing

### ISSUE THREAD

**Issue by david-s-svedberg** [MicrosoftDocs/vsts-docs#4133]
All the argument names are missing in the Command arguments section, you can figure it out if you scroll up and down, but it would be nice to have it specified directly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0fa37a3f-6551-16ad-e164-a4ac522cdaab
* Version Independent ID: a3fd6935-2b99-92ef-4eb3-3249fca01f8a
* Content: [NuGet restore, pack, and publish task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/package/nuget?view=azure-devops)
* Content Source: [docs/pipelines/tasks/package/nuget.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/package/nuget.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by batkoski** [comment]
Hi @david-s-svedberg , do you mean for the custom NuGet command? That command just lets you use any NuGet command with any arguments you'd like, so it would be tough to list them.

**Comment by elbatk** [comment]
Hi @david-s-svedberg , are you referring to the custom NuGet Command task? If so, that lets you use whichever NuGet command you'd like, with whatever arguments you need. Specifying all of these would be tough I think.

**Comment by david-s-svedberg** [comment]
Hi, no. Hard to describe but if you look under the [Argument sektion](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/package/nuget?view=azure-devops#arguments) there's a table where the first column is Argument, in that coumn I would expect the name of the argument to be listed, but instead there's a short description. The value of the first row is 
> Path to solution, packages.config, or project.json

but the argument you need to use is
``` restoreSolution ```

Sure you can figure this out by scrolling up and looking at the [YAML snippet](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/package/nuget?view=azure-devops#yaml-snippet), but it takes some guesswork and scrolling.

It looks like it's the same for all the Tasks.

**Comment by RehanSaeed** [comment]
Can confirm, the tables first column should be the argument name but it is missing.

**Comment by chasewilson** [comment]
@RehanSaeed, @david-s-svedberg, thanks for the feedback. I currently have a backlog item and branch I'm working on to straighten out the inputs and updates. I will let you know when that will be pushed to live :)

**Comment by chasewilson** [comment]
@RehanSaeed, @david-s-svedberg, thank you again for the feedback! I've update the documentation and you should see it live within 24 hours. 
I'm closing this issue for now and I hope you will open a new issue if you have any more feedback!
