### ISSUE TITLE
Confirmation dialog example doesn't work 

### ISSUE THREAD

**Issue by m-akinc** [MicrosoftDocs/vsts-docs#4134]
I can't for the life of me figure out how to make a basic yes/no confirmation dialog. **The example code doesn't work, because the yes/no callbacks reference the `dialog` variable, which isn't set until *after* the `Dialogs.show` call returns.** It seems there are a couple different ways to configure the options to make a confirmation dialog:
1.  _Using `buttons` to define my own yes/no buttons with callbacks_. How can I close the dialog in response to a button being pressed? I need a reference to the dialog object in order to call `close()` on it.
2. _Using `okCallback` and `cancelCallback`._ These appear to close the dialog automatically (after executing my callback), but the "OK" button is initially disabled. You apparently must call `updateOkButton(true)` to enable it, but there is no opportunity to do that. The `Dialogs.show` call does not return until the dialog is dismissed, so I don't have an instance of the dialog to call `updateOkButton` on.

Am I missing something basic, or is this just fundamentally broken? Did anyone try running these examples?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0953986b-fd40-e559-9072-e6f977f3040f
* Version Independent ID: 9b110d21-35db-6a36-a663-b275b318a264
* Content: [Use the Dialog Control](https://docs.microsoft.com/en-us/azure/devops/extend/develop/ui-controls/modaldialogo?view=azure-devops)
* Content Source: [docs/extend/develop/ui-controls/modaldialogo.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/extend/develop/ui-controls/modaldialogo.md)
* Product: **devops**
* Technology: **devops-ecosystem**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by chcomley** [comment]
Hi @m-akinc, we’re sorry you’re experiencing issues. Glad you reached out. We’ll be back in touch shortly!

**Comment by m-akinc** [comment]
Hey, any updates? Or just guidance? I'm still stuck.

**Comment by chcomley** [comment]
Hi @m-akinc, I'm assigning this to @willsmythe, for timely assistance.

**Comment by chcomley** [comment]
Hi @m-akinc, a colleague said he ran through the sample with no issues. The dialog variable will be set prior to the callbacks being executed. Can you  let us know what errors you are seeing?

**Comment by m-akinc** [comment]
Looks like I was misinterpreting the behavior I was seeing. Sorry for that. I thought that Dialogs.show was designed to block until it was dismissed, but the reason it's not returning in my case is that it's throwing an error:
```
vss-bundle-ext-core-v6RSBD4v2X6bb0AObvd6yQOTO8sh0bkyWQas17edJ7c4=:248
TypeError: r.getClientRects is not a function
    at w.fn.init.offset (jquery.min.js:2)
    at Object.getWithinInfo (Content?bundle=vss-bundle-async-vd8w7_sXizZ_LZr1N5RmBNjbiNNlh5Ev0GTG-XS81w7Y=:190)
    at w.fn.init.n.fn.position (Content?bundle=vss-bundle-async-vd8w7_sXizZ_LZr1N5RmBNjbiNNlh5Ev0GTG-XS81w7Y=:190)
    at n.<computed>.<computed>._position (Content?bundle=vss-bundle-async-vd8w7_sXizZ_LZr1N5RmBNjbiNNlh5Ev0GTG-XS81w7Y=:214)
    at n.<computed>.<computed>._position (Content?bundle=vss-bundle-async-vd8w7_sXizZ_LZr1N5RmBNjbiNNlh5Ev0GTG-XS81w7Y=:87)
    at n.<computed>.<computed>.open (Content?bundle=vss-bundle-async-vd8w7_sXizZ_LZr1N5RmBNjbiNNlh5Ev0GTG-XS81w7Y=:214)
    at n.<computed>.<computed>.open (Content?bundle=vss-bundle-async-vd8w7_sXizZ_LZr1N5RmBNjbiNNlh5Ev0GTG-XS81w7Y=:87)
    at n.<computed>.<computed>._init (Content?bundle=vss-bundle-async-vd8w7_sXizZ_LZr1N5RmBNjbiNNlh5Ev0GTG-XS81w7Y=:214)
    at n.<computed>.<computed>._init (Content?bundle=vss-bundle-async-vd8w7_sXizZ_LZr1N5RmBNjbiNNlh5Ev0GTG-XS81w7Y=:87)
    at n.<computed>.<computed>._createWidget (Content?bundle=vss-bundle-async-vd8w7_sXizZ_LZr1N5RmBNjbiNNlh5Ev0GTG-XS81w7Y=:87)
```
Here's my js code, based on the documenation:
```
VSS.require(["VSS/Controls/Dialogs"], function(Dialogs) {
    var dialog = Dialogs.show(Dialogs.ModalDialog, {
        title: "Confirmation",
        content: $("<p/>").addClass("confirmation-text").html(`Are you sure?`),
        buttons: {
            "Yes": function() {
                console.log("confirmed!");
                dialog.close();
            },
            "No": function() {
                dialog.close();
            }
        }
    });
});
```
I'm trying to show this from a menu action (of a PR custom status menu: "ms.vss-code-web.pull-request-status-menu"). Maybe the problem is related to the fact that the menu action's html is not actually being displayed?

It's worth noting that after opening this issue, I came across the HostDialogService documentation (https://docs.microsoft.com/en-us/azure/devops/extend/reference/client/api/vss/sdk/services/dialogs/hostdialogservice?view=azure-devops) and was able to get a modal dialog working that way.

**Comment by chcomley** [comment]
Thanks @m-akinc, I'm closing this issue. Please let us know if you have any other questions. Have a fantastic weekend!

**Comment by m-akinc** [comment]
Well, it's still the case that the example code doesn't work where I was trying to use it. Can you provide any insight into the error I get? Did I guess correctly that you can't show that dialog from a menu action? If so, the documentation ought to include some information about that (or any other) restriction as well as a suggestion to use the HostDialogService instead.

**Comment by chcomley** [comment]
Hi @m-akinc, Unfortunately, I can't provide any insight into the error you got, but I'm adding @willsmythe  for potential insight. Thank you.
