### ISSUE TITLE
Task publishes report from multiple files, but summary just shows first match

### ISSUE THREAD

**Issue by andrewdmay** [MicrosoftDocs/vsts-docs#4135]
The behavior for a task configured with a wildcard path for the coverage file is a little inconsistent:
```
      - task: PublishCodeCoverageResults@1
        inputs:
          codeCoverageTool: cobertura
          summaryFileLocation: $(System.DefaultWorkingDirectory)/**/coverage.cobertura.xml
```

In this example there are 4 coverage.cobertura.xml files from separate test runs, all of which are included in the code coverage report, but the summary only shows the results from one of these:

```
##[warning]Multiple file or directory matches were found. Using the first match: /__w/1/s/Provider.Api.Sdk.Tests/coverage.cobertura.xml
[command]/usr/bin/dotnet /__w/_tasks/PublishCodeCoverageResults_2a7ebc54-c13e-490e-81a5-d7561ab7cd97/1.151.1/netcoreapp2.0/ReportGenerator.dll -reports:/__w/1/s/**/coverage.cobertura.xml -targetdir:/__w/_temp/cchtml -reporttypes:HtmlInline_AzurePipelines
Loading report '/__w/1/s/Provider.Api.Tests/coverage.cobertura.xml' 1/4
 Preprocessing report
 Initiating parser for Cobertura
  Current Assembly: Provider.Api
Loading report '/__w/1/s/Provider.FileProcessing.Tests/coverage.cobertura.xml' 2/4
 Preprocessing report
 Initiating parser for Cobertura
  Current Assembly: Provider.FileProcessing
Loading report '/__w/1/s/Provider.Api.Sdk.Tests/coverage.cobertura.xml' 3/4
 Preprocessing report
 Initiating parser for Cobertura
  Current Assembly: Provider.Api.Sdk
Loading report '/__w/1/s/Provider.Data.Tests/coverage.cobertura.xml' 4/4
 Preprocessing report
 Initiating parser for Cobertura
  Current Assembly: Provider.Data
```

Ideally the summary would show the coverage for each assembly separately. Because I'm trying to reuse a template across multiple projects I don't want to have to configure the task for each assembly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6ac4ff4-9839-6a6d-8d20-a25084d221ef
* Version Independent ID: bd09f139-8e69-8ea1-6671-b7bba8e17c23
* Content: [Publish Code Coverage Results task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/test/publish-code-coverage-results?view=azure-devops#feedback)
* Content Source: [docs/pipelines/tasks/test/publish-code-coverage-results.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/test/publish-code-coverage-results.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @PBoraMSFT
* Microsoft Alias: **pbora**

**Comment by pshirshov** [comment]
I second this. Actually in my case (scala project) there is no summary, just a link to coverage report.

The report itself is consistent and contains all the aggregated data from all the reports in the project, but I'm getting a naughty warning "Multiple file or directory matches were found. Using the first match: /__w/1/s/distage/distage-config/target/scala-2.12/coverage-report/cobertura.xml", which actually makes no sense because aggregation happens correctly.

<img width="1315" alt="Screenshot 2019-05-08 at 16 48 44" src="https://user-images.githubusercontent.com/295225/57388952-2d058f80-71b1-11e9-8de8-20f4c8975f85.png">

**Comment by pkuczynski** [comment]
Similar issue reported https://github.com/microsoft/azure-pipelines-tasks/issues/10353

**Comment by PBoraMSFT** [comment]
@andrewdmay @pkuczynski - if you have an open source github repo, can you please point me to a build where this issue is seen? 

@pshirshov - the reason you don't see coverage summary is that you are viewing builds that are in-progress. Coverage summary only lights up when builds complete.

**Comment by pshirshov** [comment]
@PBoraMSFT : I still think that the warning makes no sense.

**Comment by pkuczynski** [comment]
Unfortunately, I have closed source repo only. But the company I work for is a big Azure partner.

**Comment by atariq6298** [comment]
How do I specify multiple summary files? I have 2 files, one named cobertura-coverage.xml and the other named cobertura.coverage.xml

**Comment by PBoraMSFT** [comment]
We have updated the documentation with the current limitations. [Link](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/test/publish-code-coverage-results?view=azure-devops#q--a). 

We are currently working on enhancing our code coverage reporting capabilities that will overcome these limitations.

Closing the doc issue.

**Comment by msrinivascharan** [comment]
> How do I specify multiple summary files? I have 2 files, one named cobertura-coverage.xml and the other named cobertura.coverage.xml
I have a project with three different modules, two Java and one Python. all three modules generate Cobertura based code coverage reports. I am able to merge all three into one using @danielpalme "ReportGenerator" extension. able to apply gating condition using merged coverage report. Please refer [this](https://github.com/coverlet-coverage/coverlet/issues/474).

**Comment by msrinivascharan** [comment]
I have a project with three different modules, two Java and one Python. all three modules generate Cobertura based code coverage reports. I am able to merge all three into one using @danielpalme "ReportGenerator" extension. able to apply gating condition using merged coverage report. Please refer [this](https://github.com/coverlet-coverage/coverlet/issues/474).
