### ISSUE TITLE
Incorrect Link - conceptual introduction

### ISSUE THREAD

**Issue by dankellett** [MicrosoftDocs/vsts-docs#4137]
It seems the link to a conceptual introduction in this article does not link to the correct article. It links back to the root Azure Artifacts documentation page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 078a8c96-ec59-c10b-e48e-8c5586c8cb09
* Version Independent ID: 200f5723-2404-298d-e6bb-533592a28ff3
* Content: [Azure Artifacts in Azure DevOps Services and Azure DevOps Server](https://docs.microsoft.com/en-us/azure/devops/artifacts/overview?view=azure-devops)
* Content Source: [docs/artifacts/overview.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/artifacts/overview.md)
* Product: **devops**
* Technology: **devops-artifacts**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by chcomley** [comment]
Thanks @dankellett, I’ve created a user story to address this!

**Comment by chasewilson** [comment]
@dankellett thanks for your feedback. The link was to the correct location, however we have renamed the title of the link to make it more clear.

**Comment by chasewilson** [comment]
@dankellett, after further review, I reverted the wording to the previous version and updated the link to the Key Concepts page which lines up better with getting a basic understanding of working with packages. 
Thank you again and feel free to reach out with any more feedback!
