### ISSUE TITLE
Travis migration guide displays BUILD_REPOSITORYNAME instead of BUILD_REPOSITORY_NAME

### ISSUE THREAD

**Issue by mloskot** [MicrosoftDocs/vsts-docs#4139]
The "Predefined variables" section of this guide
https://github.com/MicrosoftDocs/vsts-docs/blob/6f50897b7b87123d5b3d5bff9fcf667528b93fa2/docs/pipelines/migrate/from-travis.md#L40-50
should display `BUILD_REPOSITORY_NAME` instead of `BUILD_REPOSITORYNAME `

**Comment by steved0x** [comment]
This has been fixed, thank you.
