### ISSUE TITLE
ffaad

### ISSUE THREAD

**Issue by amitpatelupw** [MicrosoftDocs/vsts-docs#4140]
ffadasd

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 90ff4c66-0e6e-48e2-de64-2b772e1d10da
* Version Independent ID: ac420358-3388-6270-6372-2fef766917ba
* Content: [Navigating within the web portal - Azure DevOps](https://docs.microsoft.com/en-in/azure/devops/project/navigation/index?view=azure-devops)
* Content Source: [docs/project/navigation/index.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/project/navigation/index.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by thomps23** [comment]
@amitpatelupw It looks like your feedback wasn't captured. If you could provide more information we'll be able to triage.
