### ISSUE TITLE
I am unable to access service connection data in my custom build task 

### ISSUE THREAD

**Issue by shudv** [MicrosoftDocs/vsts-docs#4142]
I followed steps mentioned in this documented and created a service endpoint which I expect to be able to access via the getEndpoint* methods in my custom build task. But I am not able to access the endpoint. Am I missing any step?

To be more specific, following is what I did
1 - Created a extension with a build task and a service endpoint contribution with basic authentication scheme.
2 - Create a service connection named "Test" in my account and set it to be visible to all pipelines.  
2 - Called getEndpointUrl("Test") method from my task expecting to get the configured URL but instead I get - Endpint "Test" not found.   

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 90db6e4c-6240-fe2e-3043-0a7d186b9ca7
* Version Independent ID: a62ec500-3330-e28a-8019-118a3b9e261f
* Content: [Service Endpoints](https://docs.microsoft.com/en-us/azure/devops/extend/develop/service-endpoints?view=azure-devops#feedback)
* Content Source: [docs/extend/develop/service-endpoints.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/extend/develop/service-endpoints.md)
* Product: **devops**
* Technology: **devops-ecosystem**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by chcomley** [comment]
Hi @shudv, thanks for reaching out. We’ll be in touch shortly.

**Comment by shudv** [comment]
@chcomley, I tried fetching the connection information using the connection id instead of the name, it worked. So we can do either of the following here-

- Request support for fetching connection info by name
- Make it clearer in this doc or some other related doc that you need the connection id to fetch the info. 

Obviously as a user, I'd prefer the first.

**Comment by Lovakumar** [comment]
We need to make it clear in the doc that service connection parameters must be fetched by service connection ID.

**Comment by chcomley** [comment]
Hi @shudv, I wanted to follow up and let you know that we are currently updating this article and will notify you once it has been published. Thank you!

**Comment by gtedeschi** [comment]
Hi! I've the same problem... How to get data from datasource/service?

**Comment by chcomley** [comment]
@ashokirla can you please provide an estimate as to when I can review your PR? Thanks so much!

**Comment by ashokirla** [comment]
@chcomley As part of service connections UX refresh, we are planning to update the entire service connections documentation. The work is currently in progress. I will publish a doc PR during the week of Oct 21-25.

**Comment by chcomley** [comment]
Hi @ashokirla,

Following up on this - have you published these updates yet? Thanks for your help.

**Comment by chcomley** [comment]
@shudv, While @ashokirla's group works on updating the article, as a whole, I've added a note that highlights that service connection parameters must be fetched by service connection ID. Thanks so much for your feedback!
