### ISSUE TITLE
There doesn't seem to be mention of the "`windows-latest`" `vmImage` or any other `*-latest` `vmImage`s for Microsoft-hosted agents.

### ISSUE THREAD

**Issue by nelsonjchen** [MicrosoftDocs/vsts-docs#4143]
Yesterday it was probably `vs2017-win2016`, today `windows-2019`, tomorrow maybe `windows-2022`. 

`windows-latest` appears when you ask Pipelines to generate some steps during a repository setup for .NET Desktop. It doesn't appear in this documentation. I haven't examined other pre-written templates, but is there a `ubuntu-latest` or `macos-latest`? 

While I guess most people go to this page for locking `vmImage`s I could see it being useful for people who build a build that specifically target sort of a "nightly" channel where things aren't pinned and seeing upcoming breakage in the future platform can be very helpful. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 99af681d-41ad-da15-0b72-08b5cd5a11ac
* Version Independent ID: 2fa0df36-a437-8cbb-b019-b49b31b1e116
* Content: [Microsoft-hosted agents for Azure Pipelines - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops#feedback)
* Content Source: [docs/pipelines/agents/hosted.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/agents/hosted.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by joebourneMS** [comment]
@nelsonjchen working on these docs updates now, thanks!

**Comment by bladellium** [comment]
Will there be a 1903 image soon as i require this to build 1903 container images for aspnet and windowsservercore

**Comment by thejoebourneidentity** [comment]
Hi @bladellium , please follow https://github.com/microsoft/azure-pipelines-image-generation/issues/802 for updates on this.

**Comment by bluebirdtech** [comment]
Hi.  I was looking for details on what -latest images are available too - this document doesn't seem to be updated yet?

**Comment by thejoebourneidentity** [comment]
Updates coming soon, see this PR: https://github.com/MicrosoftDocs/vsts-docs/pull/5028
