### ISSUE TITLE
Argument Names

### ISSUE THREAD

**Issue by david-s-svedberg** [MicrosoftDocs/vsts-docs#4145]
Seems to be a general issue (or comment, might be intentional) for all the Tasks documentation but the argument names aren't specified in the tables, just a short and long description. You can often figure it out by why not add another column for the real names(Or remove the short description, doesn't really add anything)?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 96561b11-820d-b386-4208-e88e9552f5fc
* Version Independent ID: 42918fea-f9ad-260c-ec38-70254a47de5d
* Content: [.NET Core build and release task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/dotnet-core?view=azure-devops)
* Content Source: [docs/pipelines/tasks/build/dotnet-core.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/build/dotnet-core.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @pulkitaggarwl
* Microsoft Alias: **puagarw**

**Comment by david-s-svedberg** [comment]
#4133

**Comment by andyjlewis** [comment]
@david-s-svedberg I think you're asking to have the yaml input name added, like has already been done in other tasks such as https://docs.microsoft.com/azure/devops/pipelines/tasks/deploy/azure-function-app. Am I understanding you correctly?

**Comment by david-s-svedberg** [comment]
Precisely!

Den tors 6 juni 2019 02:12andyjlewis <notifications@github.com> skrev:

**Comment by chasewilson** [comment]
Hi @david-s-svedberg, thank you for the feedback. I'll be releasing an update to https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/dotnet-core-cli?view=azure-devops in just a bit. The info from this page is going to be moved here and follow the pattern you suggested. If you have any more issues with it please open a new issue on that page :) Have a great day1
