### ISSUE TITLE
Is there a delay after changing the preferred email address for notifications ?

### ISSUE THREAD

**Issue by Yanal-Yves** [MicrosoftDocs/vsts-docs#4146]
Hello,

I have just updated my email address as describe in this wiki page.
When I go to https://dev.azure.com/&lt;project&gt;/_usersSettings/notifications I still see the old email address.

Is there a delay after changing the preferred email address for notifications? If yes, I think it's worth mentioning it on this wiki page.
Am I missing something?

Have a good day
Yanal

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c94a78f-77de-a612-1fc8-749518195166
* Version Independent ID: fba4f685-1c59-e1e6-2138-aaa5477e476d
* Content: [Change your preferred email address for notifications - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/notifications/change-email-address?view=azure-devops#feedback)
* Content Source: [docs/notifications/change-email-address.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/notifications/change-email-address.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @Yanal-Yves, I'm sorry for the delayed response. My guess is that you're no longer seeing your old email address, am I right? It's possible for it to take 5 mins or more for the new preferred email address to display. I'm going to close this issue, however if you still don't see it, please [contact Support](https://azure.microsoft.com/en-us/support/devops/) for assistance. Have a great day!
