### ISSUE TITLE
When I the change organization owner I am removed from the PCA group

### ISSUE THREAD

**Issue by leonpw** [MicrosoftDocs/vsts-docs#4147]
When I change ownership to someone else; From user A to user B as a Project Collection Administrator. My own account is removed from the PCA group. I think this is unintended. If I mistakenly choose the wrong account everybody except this person would be locked out of the organisation.

The docs:
https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/faq-change-organization-ownership?view=azure-devops

**Comment by KathrynEE** [comment]
Reassigning to chcomley.

**Comment by chcomley** [comment]
Hi @leonpw, This is how it has been implemented, which is definitely not ideal. We hope to address this soon, but in the meantime I've created a user story for my backlog to add some clarity to the article and point you in the right direction. Thanks for reaching out, we appreciate it.
