### ISSUE TITLE
Keystore file and Secure Files

### ISSUE THREAD

**Issue by arek-avanade** [MicrosoftDocs/vsts-docs#4151]
The Keystore file description doesn't say a word that the keystore file should be store in Secure file area in DevOps. This should be clearly stated in the docs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4b1fbcd8-d799-879e-d672-9dee164401ef
* Version Independent ID: 7208d03d-9042-7753-ab4d-d1ad8e99ef1d
* Content: [Android signing build and release task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/android-signing?view=azure-devops#feedback)
* Content Source: [docs/pipelines/tasks/build/android-signing.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/build/android-signing.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @DavidStaheli
* Microsoft Alias: **dastahel**

**Comment by DavidStaheli** [comment]
Thank you for reporting this, @arek-avanade, and apologies for any frustration it caused.  It has been fixed and should be available in production within 48 hours.

**Comment by samaneh-kamalian** [comment]
Hi. I follow all steps but when run, return Error: unable to verify the first certificate
I upload my self sign certificate and create my keystore file with this command:
keytool -genkeypair -v -keystore my-upload-key.keystore -alias my-key-alias -keyalg RSA -keysize 2048 -validity 10000

what does this error mean?
