### ISSUE TITLE
search for the Azure Pipelines app

### ISSUE THREAD

**Issue by docgregt** [MicrosoftDocs/vsts-docs#4156]
Azure Piplines does not exist in teams App Store.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b9adc845-adee-a494-79b4-3466f51d3ec9
* Version Independent ID: 12445205-8acc-98e6-fe65-9508e0dccb5c
* Content: [Azure Pipelines with Microsoft Teams - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/integrations/microsoft-teams?view=azure-devops)
* Content Source: [docs/pipelines/integrations/microsoft-teams.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/integrations/microsoft-teams.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @atinb
* Microsoft Alias: **atinb**

**Comment by thomps23** [comment]
@steved0x I also couldn't find it searching the Microsoft Teams app store.

**Comment by miladnzsuperfund** [comment]
Same here. I couldn't find Azure Pipelines in the store

**Comment by n122vu** [comment]
I see the same issue.  Azure Pipelines does not exist in the Teams app store.  

![image](https://user-images.githubusercontent.com/1396060/57460931-080e2c80-7244-11e9-8598-b06b323541f7.png)

**Comment by KingstonFE** [comment]
The Same. I couldn't find Azure Pipelines in the store....

**Comment by nonameolsson** [comment]
It will probably take a couple of weeks. Just like the releases in DevOps, they appear a week or more after the release note is published.

**Comment by steved0x** [comment]
I have asked the product team to see if I can get an ETA for when the app will appear in the Teams store and will report back.

**Comment by atinb** [comment]
Thanks for the interest and sorry about the wait. It took a little while to get through the approval pipeline. The app is now live on the Teams store. Thanks!

**Comment by JoepKillaars** [comment]
Still unable to find the app in the teams store. Anyone else able to install it? Am I doing something wrong?

**Comment by atinb** [comment]
@JoepKillaars @miladnzsuperfund The app is live. Can you try the "Get it now" on the Microsoft appsource link : [https://appsource.microsoft.com/en-us/product/office/WA200000055?tab=Overview](https://appsource.microsoft.com/en-us/product/office/WA200000055?tab=Overview)

**Comment by JoepKillaars** [comment]
![image](https://user-images.githubusercontent.com/1288033/57618059-acfd7200-7582-11e9-9411-f7fed075a0b7.png)

**Comment by atinb** [comment]
@JoepKillaars Sorry about that. If you go to appsource.microsoft.com and search for Azure Pipelines, what do you see? This is what I get - 
![image](https://user-images.githubusercontent.com/12844776/57618185-57d05900-75a0-11e9-82a5-84f50ae72b83.png)

**Comment by JoepKillaars** [comment]
@atinb This works, I can find the app in appsource using search, and the installer popup opens as well, however, when opening the teams app to install, it throws an error.

**Comment by ljfraney** [comment]
@JoepKillaars, I got that error too. After clicking "Get it Now" from the link provided by @atinb, choose "Use the web app instead". This worked for me, and it shows up in the channel using the client once you set it up on the web app.

**Comment by rpulijala** [comment]
I dont see in the web app either, get same error in web app

**Comment by kylepauljohnson** [comment]
I was able to install it via the web version of Teams without issue, but not the desktop client.

**Comment by JoepKillaars** [comment]
@atinb I get the error regardless whether I use the web app or the desktop client.

**Comment by KingstonFE** [comment]
I already loo it and can use it. But I hope I only receive "Release deployment approval pending notifications" in release pipeline

**Comment by atinb** [comment]
@KingstonFE Once you subscribe to a pipeline, you can always to go your subscriptions and add/remove to get only the notifications you need.

**Comment by dotnetcanuck** [comment]
I can also confirm, I can't find the app within MS Teams... the direct link posted above works, but when I try to install the app, I get the "Something went wrong" error, regardless of whether I use the desktop or web client.

**Comment by atinb** [comment]
@dotnetcanuck @JoepKillaars Is there a chance that 3rd party apps (non-Microsoft apps) are disabled on your Teams account? That could be one reason why the app fails to install. Can you please confirm? Thanks!

**Comment by atinb** [comment]
@dotnetcanuck @JoepKillaars We think this issue should not be fixed. Can you please confirm? Thanks!

**Comment by dotnetcanuck** [comment]
@atinb I'll dig into this for you by Friday

**Comment by dotnetcanuck** [comment]
@atinb It appears to be installing correctly now. The app appeared in the app search within MS Teams as well.

Some kind of replication issue, perhaps?

**Comment by atinb** [comment]
Great, thank you for confirming that things are working now!
@steved0x Feel free to resolve the issue. Thanks!

**Comment by steved0x** [comment]
@atinb Thank you, will do.
