### ISSUE TITLE
MSBuild 16 / VS2019 not supported

### ISSUE THREAD

**Issue by CZEMacLeod** [MicrosoftDocs/vsts-docs#4157]
The msbuildVersionOption does not have 16 available as an option.
The MSBuild and Visual Studio Build tasks have been updated already.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17217289-b764-14a7-e3d9-862d1d9cf503
* Version Independent ID: e1dd6942-3210-a148-b971-af869272c9a3
* Content: [Xamarin.Android build and release task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/xamarin-android?view=azure-devops#feedback)
* Content Source: [docs/pipelines/tasks/build/xamarin-android.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/build/xamarin-android.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @DavidStaheli
* Microsoft Alias: **dastahel**

**Comment by Thorocaine** [comment]
If you set the pool name to `Hosted Windows 2019 with VS2019` it will try running on VS15, not find it, and _fall back_ to `16`.

**Comment by CZEMacLeod** [comment]
@Thorocaine that's fine if you are not using your own build servers which have both installed.

**Comment by davidstaheli** [comment]
Thanks for reporting this. We're going to move this issue to this repo:
https://github.com/Microsoft/azure-pipelines-tasks

/move to Microsoft/azure-pipelines-tasks
