### ISSUE TITLE
About user hiding

### ISSUE THREAD

**Issue by samuraiblue2003** [MicrosoftDocs/vsts-docs#4160]
All user information will be displayed. I want to show or hide only specific information like Projects.
([Organization Settings]-[General]-[Projects])

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 75aa416a-b842-77d0-e18a-bee7f7bf7205
* Version Independent ID: 65942145-45ca-48bb-6adc-c16bd662b80a
* Content: [Manage users and access levels - Azure DevOps Services](https://docs.microsoft.com/ja-jp/azure/devops/organizations/accounts/manage-users-table-view?view=azure-devops&viewFallbackFrom=vsts#feedback)
* Content Source: [docs/organizations/accounts/manage-users-table-view.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/accounts/manage-users-table-view.md)
* Product: **devops**
* Technology: **devops-accounts**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by samuraiblue2003** [comment]
I do not want to let other users know their email address, name, etc.

**Comment by chcomley** [comment]
Hi @samuraiblue2003, Thanks for reaching out. I’ll investigate and get back to you!

**Comment by chcomley** [comment]
Hi @samuraiblue2003, Apparently you're not the only one who wants this functionality, as we're currently investigating a solution for this. If you want to, you could search for this feedback and upvote it, or submit your idea [here](https://visualstudio.microsoft.com/vs/support/#talktous).

At the moment, there are two permissions bits that you can try setting to see if it gives you the desired behavior: view project-level information and view instance-level information. Start there and hopefully we can implement something soon! Thanks!
