### ISSUE TITLE
Multi-stage pipelines experience available yet?

### ISSUE THREAD

**Issue by J0F3** [MicrosoftDocs/vsts-docs#4162]
The documentation says "make sure the Multi-stage pipelines experience is turned on". But I can not find where it can be turned on. I can not see it on the preview features. Got I someting wrong someting or is the feature actually not yet rolled-out?

Thx!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4266f72c-c774-0046-4593-d01eb775d3c3
* Version Independent ID: f20827aa-a6c5-96a8-5969-e576ffbc2e38
* Content: [Stages in Azure Pipelines - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/stages?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/process/stages.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/stages.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @vijayma
* Microsoft Alias: **vijayma**

**Comment by vijayma** [comment]
The rollout is in progress. It has reached a few orgs, but not all. You can expect this feature to be available in all orgs by the end of next week (5/17).

**Comment by J0F3** [comment]
@vijayma cool, thank you for the very fast response.  So I was just too impatience. 😳👍
