### ISSUE TITLE
Inherrited Process Note still valid?

### ISSUE THREAD

**Issue by MattDavisRM** [MicrosoftDocs/vsts-docs#4164]
Is this note still valid with the release of Azure DevOps Server 2019?  I believe we can have an Inherrited process?  Do we have to created a new collection to be able to use it though?

 Important

To customize an on-premises TFS project, see On-premises XML process model. This article applies to Azure DevOps Services only.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5969861-6f6b-3da1-7eb3-2ee278110937
* Version Independent ID: ae1c687d-7c93-ba01-f63c-2f1df95ed873
* Content: [Create and manage an inherited process - Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/organizations/settings/work/manage-process?view=azure-devops#feedback)
* Content Source: [docs/organizations/settings/work/manage-process.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/settings/work/manage-process.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@MattDavisRM - Thank you for your inquiry. Yes, you can use the Inherited Process Model with Azure DevOps Server 2019 when you create a new collection and specify the Inherited process. Upgraded Project collections can only use the XML process model. I will update the topic to clarify.
