### ISSUE TITLE
Custom Hub Group

### ISSUE THREAD

**Issue by piense** [MicrosoftDocs/vsts-docs#4166]
This page says "Extensions can contribute both hubs and hub groups." So how do I create a custom hub group? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 56437af3-75da-d219-5364-9b7927298ece
* Version Independent ID: ca01655a-9195-cf92-14b4-77ef66053dcf
* Content: [Extension Points](https://docs.microsoft.com/en-us/azure/devops/extend/reference/targets/overview?view=azure-devops#feedback)
* Content Source: [docs/extend/reference/targets/overview.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/extend/reference/targets/overview.md)
* Product: **devops**
* Technology: **devops-ecosystem**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by davidcorrigan714** [comment]
Looks like this page got orphaned at some point, took forever to find it with google:
https://docs.microsoft.com/en-us/azure/devops/extend/develop/add-hub-group?view=azure-devops
