### ISSUE TITLE
Not found error

### ISSUE THREAD

**Issue by vishnuvg1984** [MicrosoftDocs/vsts-docs#4167]
The github url https://github.com/MicrosoftDocs/pipelines-javascript-docker not found

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cbceb1f5-05c3-487d-6e21-dc1b4936a55c
* Version Independent ID: 35355737-9ad9-9df5-b612-806d9df2462b
* Content: [Deploy to Azure Kubernetes Service - Azure Pipelines](https://docs.microsoft.com/en-gb/azure/devops/pipelines/languages/aks-template?view=azure-devops)
* Content Source: [docs/pipelines/languages/aks-template.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/languages/aks-template.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @shashankbarsin
* Microsoft Alias: **shasb**

**Comment by rbmathis** [comment]
+1

**Comment by shashankbarsin** [comment]
@vishnuvg1984 and @rbmathis we've fixed this issue. The same [repo](https://github.com/MicrosoftDocs/pipelines-javascript-docker) should work now. Please try out the end-to-end guide now 😊
