### ISSUE TITLE
Azure DevOps Artifacts Billing - Needs updating with pay for storage model

### ISSUE THREAD

**Issue by ArchSerpo** [MicrosoftDocs/vsts-docs#4169]
As per the improvements detailed here - https://devblogs.microsoft.com/devops/a-simpler-way-to-buy-azure-devops/

It still makes mention of "Each organization gets five free licenses. If you need more than five licenses, complete the following steps." directly under the "Pay for Artifacts" header

PS: This change is much appreciated, I'm trying to push for Azure DevOps at my company and this change is going to make my life much much easier!

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b5531731-8bd5-b178-9307-f01b3d2f23b3
* Version Independent ID: 8dea3b69-ad79-5045-3820-4a83a0bc4ce0
* Content: [Sign up for Azure Artifacts](https://docs.microsoft.com/en-gb/azure/devops/artifacts/sign-up-azure-artifacts?view=azure-devops#feedback)
* Content Source: [docs/artifacts/sign-up-azure-artifacts.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/artifacts/sign-up-azure-artifacts.md)
* Product: **devops**
* Technology: **devops-artifacts**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @ArchSerpo, my apologies for a delayed response, as this was updated last week. I do hope your life is easier now! Please let us know if you have any other questions or feedback. Have a great day!
