### ISSUE TITLE
Artifact download in DevOps Server 2019

### ISSUE THREAD

**Issue by centreboard** [MicrosoftDocs/vsts-docs#4170]
Selecting which artifacts are downloaded is not enabled by default in DevOps Server 2019, you can only choose to skip download (and download with a task if required.)

https://developercommunity.visualstudio.com/content/problem/520932/azure-devops-server-2019-where-is-partially-downlo.html

Should the Artifact download text be the same as for TFS 2018?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 598465e1-85d4-4961-b8b6-902d6026c5e3
* Version Independent ID: 5ef1308a-3aeb-fcc4-dec7-6f10785612a3
* Content: [Release artifacts and artifact sources - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/artifacts?view=azure-devops-2019#feedback)
* Content Source: [docs/pipelines/release/artifacts.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/release/artifacts.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by RoopeshNair** [comment]
@ashokirla

**Comment by justhchung** [comment]
Thank you for your feedback. 
We are closing this issue and directing you to seek an answer through our support web site: [Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html).

**Comment by centreboard** [comment]
@justhchung I've already provided a link to developer community answer, the issue is the docs for Azure DevOps Server don't match the answer given there.

The choice to select which artifacts to download as shown in https://docs.microsoft.com/en-us/azure/devops/pipelines/release/artifacts?view=azure-devops-2019#download is not present in 2019 and is behind a preview flag in 2019.1 Should the docs mention this?
