### ISSUE TITLE
same article using devops user interface

### ISSUE THREAD

**Issue by MohammadMQ** [MicrosoftDocs/vsts-docs#4173]
Can you make this same tutorial only using the Azure DevOps User Interface?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 483dcb1c-1a89-2b20-4cf2-abd3ae88d9ed
* Version Independent ID: dc4722ed-5a4b-26ec-e7d5-a149bf6e79a7
* Content: [Build, test, and deploy .NET Core apps - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/languages/dotnet-core?view=azure-devops)
* Content Source: [docs/pipelines/languages/dotnet-core.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/languages/dotnet-core.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by andyjlewis** [comment]
@MohammadMQ are you using the Azure Pipelines service, Azure DevOps Server, or TFS? If you're using the service, then YAML is now the recommended approach, but you can still use the classic editor if you prefer.

**Comment by MisinformedDNA** [comment]
YAML may be the recommended approach, but a) classic is still supported, b) classic is still the most widely used and c) the [YAML task assistant](https://docs.microsoft.com/en-us/azure/devops/release-notes/2019/sprint-150-update#task-assistant-for-editing-yaml-files) basically carries classic forward.

**Comment by vijayma** [comment]
@MisinformedDNA All of the content, with the exception of YAML snippet examples, applies to classic build pipelines as well. One thing we can do for classic users is to include screenshots or a concise list of the same inputs in the place of YAML snippet. We thought that it is straightforward to infer the inputs for the tasks based on what is shown in the YAML file. That is why we de-prioritized this item on our backlog.

**Comment by MohammadMQ** [comment]
Hi Vijayma
Including screenshots or a concise list of the same inputs in the place of YAML snippet would be a nice start.

**Comment by MohammadMQ** [comment]
Hi andyjlewis!
I'm using Azure Pipeline Services, I'm aware that YAML is what is being encouraged, however I prefer the classic editor.
