### ISSUE TITLE
Adding variable group to specific environment in release definition?

### ISSUE THREAD

**Issue by sxm0275** [MicrosoftDocs/vsts-docs#418]
Hi, 
I have created a variable group and i have dev, test and prod environments on my release definition. I want to link the variable group i created to just the dev environment. How can i do that? 
When i try to link the variable group like documented above, i don't see my dev, test and prod environments release environments. 
In other words how can i scope my variable group to just one environment in a release definition?
Thanks. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4827aa99-ae62-bd63-6f2f-a87a4065ed27
* Version Independent ID: c9e461ee-7f42-3503-9460-18fa3a807bbb
* Content: [Variable groups for VSTS and TFS](https://docs.microsoft.com/en-us/vsts/build-release/concepts/library/variable-groups?view=vsts)
* Content Source: [docs/build-release/concepts/library/variable-groups.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/build-release/concepts/library/variable-groups.md)
* Service: **unspecified**
* GitHub Login: @douge
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment]
Thank you for your feedback. The ability to link a variable group to one or more specific environments is available in VSTS. It will be available in TFS from Update 2.

**Comment by TheBeardedLlama** [comment]
We are running TFS 2017 Update 2 RTM (15.117.26714.0), but the option is not available. Perhaps I cannot see it. Any pointers please?

**Comment by TheBeardedLlama** [comment]
@alexhomer1 please see above

**Comment by alexhomer1** [comment]
I'll check with the product team and report back.

**Comment by RoopeshNair** [comment]
@TheBeardedLlama 

Scoping variable groups to environments was added recently and is available in [TFS 2018 Update 2](https://docs.microsoft.com/en-us/visualstudio/releasenotes/tfs2018-update2#scope-a-variable-group-to-specific-environments)

**Comment by TheBeardedLlama** [comment]
Ok, thank you for clarifying I will submit a PR to update the docs then as it's a bit vague

**Comment by KNShrinidhi** [comment]
Does Process Variable override the variable in the Variable Group?
For ex: I've a variable defined in variable group for Dev environment ConnectionString and now I want use the variable group for QA environment but only Connection String from process variable? So now which connection string get substituted ?

**Comment by KNShrinidhi** [comment]
Any updates here?

**Comment by shashban** [comment]
@KNShrinidhi yes process variables override the variable from variable group. The order of precedence for variables is "Release scoped variable group" < "Release scoped process variable" < "Environment scoped variable group" < "Environment scoped process variable" < "Variable updated by one of the previous tasks in the phase"

**Comment by KNShrinidhi** [comment]
@shashban  Thank you for the answer, in the mean while I tried and it worked for me. Thanks again!!!

**Comment by blaze515** [comment]
@alexhomer1 Any chance that this will be added as an update to TFS 2017 as well?

**Comment by RoopeshNair** [comment]
@blaze515 No, we can't backport this to an earlier version.
