### ISSUE TITLE
Documentation and code sample are inconsistent for Restore NuGet packages

### ISSUE THREAD

**Issue by abatishchev** [MicrosoftDocs/vsts-docs#4180]
Documentation says argument is optional but sample says it's not. And other way around, mandatory parameter is commended.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 96561b11-820d-b386-4208-e88e9552f5fc
* Version Independent ID: 42918fea-f9ad-260c-ec38-70254a47de5d
* Content: [.NET Core build and release task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/dotnet-core?view=azure-devops#restore-nuget-packages)
* Content Source: [docs/pipelines/tasks/build/dotnet-core.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/build/dotnet-core.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @pulkitaggarwl
* Microsoft Alias: **puagarw**

**Comment by chasewilson** [comment]
Hi @abatishchev thanks for the feedback! I'll be removing this page and the information will be moved [here](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/dotnet-core-cli?view=azure-devops). This will be the most up to date info. The input becomes mandatory if the command if the custom command is run. If you have any more feedback, I hope you will open a new issue!
