### ISSUE TITLE
Parameter restoreDirectory has no documentation

### ISSUE THREAD

**Issue by abatishchev** [MicrosoftDocs/vsts-docs#4181]
Parameter `restoreDirectory` cannot be found anywhere on the page other than the overall parameters list.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d227a6f2-a94b-1c05-57e4-b63d42e2b9e5
* Version Independent ID: d063e189-d0fd-4ca3-c108-a0bd2ae49d22
* Content: [.NET Core CLI task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/dotnet-core-cli?view=azure-devops)
* Content Source: [docs/pipelines/tasks/build/dotnet-core-cli.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/build/dotnet-core-cli.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @pulkitaggarwl
* Microsoft Alias: **puagarw**

**Comment by abatishchev** [comment]
Actually I'm incorrect, the page mentions it:

>Destination directory
> (Required)  Specifies the folder in which packages are installed. If no folder is  specified, packages are restored into the default NuGet package cache.

With current structure of documentation it's just to find it. I'd like a paragraph for each parameter to mention it again to simplify finding it.

**Comment by chasewilson** [comment]
Hi @abatishchev I've just made some updates to the page and I believe is a little clearer under packagesDirectory. I'm closing this issue and if you have any more feedback, we'd love to hear it.
