### ISSUE TITLE
COLIN JAMES BARR

### ISSUE THREAD

**Issue by colinbarr1965** [MicrosoftDocs/vsts-docs#4182]
Thank you for your feedback!

The issues in this repo are for documentation feedback.

If you are submitting your documentation feedback issue directly through GitHub, please provide the URL of the article so we can route the feedback to the correct author.

Please report Azure DevOps or TFS software bugs, feedback, or questions in the [Azure DevOps Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html).

**Comment by thomps23** [comment]
@colinbarr1965 It looks like your feedback wasn't fully captured. If you can provide your issue and topic associated with it we can triage.
