### ISSUE TITLE
"Add users or groups" page hangs on loading identities

### ISSUE THREAD

**Issue by jaymebowers** [MicrosoftDocs/vsts-docs#4183]
Repro steps:
1. View the debug console.
2. Refresh the Feed Settings page.
3. Select Add users/groups.
4. Type something in the Search users or groups textbox.

Error in debug console: 
Unhandled promise rejection: TypeError: Cannot read property 'entityId' of undefined
_onUnhandledRejection @ ms.vss-web.platform-content.es6.6ko0gcvorgpnR7J2.min.js:1
ms.vss-features.identities-content.es6.PhitRCzFMz2RMIlj.min.js:1 Uncaught (in promise) TypeError: Cannot read property 'entityId' of undefined

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e77774e-012a-45cc-d566-7170d86003cd
* Version Independent ID: 778dafea-bf98-3292-f451-d82ce8db5bbc
* Content: [Secure and share packages using feed permissions](https://docs.microsoft.com/en-us/azure/devops/artifacts/feeds/feed-permissions?view=azure-devops)
* Content Source: [docs/artifacts/feeds/feed-permissions.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/artifacts/feeds/feed-permissions.md)
* Product: **devops**
* Technology: **devops-artifacts**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by chcomley** [comment]
Hi @jaymebowers, thanks for reaching out. As this isn't specifically document-related, I'd suggest that you create a support ticket. Please go here to do so: https://developercommunity.visualstudio.com/content/problem/post.html?space=21 

I'll be closing this issue, however if you have any other questions, please do reply and I'd be happy to help. Thank you and enjoy your weekend!

**Comment by jaymebowers** [comment]
Will do. Thanks for the direction!

Regards,
Jayme
