### ISSUE TITLE
What happens to the Auto renewed license?

### ISSUE THREAD

**Issue by RohitSarangi-MS** [MicrosoftDocs/vsts-docs#4184]
The clear information regarding the fact that users will no longer need a separate Package Management license should have been mentioned here. Also what happens to the people who got their Package Management licenses auto renewed on 1-May-2019.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3a853a38-a03e-21bd-e7ea-83b452abcadf
* Version Independent ID: 2493af06-7b82-155c-a377-76aba7677a84
* Content: [Where is Package Management?](https://docs.microsoft.com/en-us/azure/devops/artifacts/where-is-package-management?view=azure-devops)
* Content Source: [docs/artifacts/where-is-package-management.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/artifacts/where-is-package-management.md)
* Product: **devops**
* Technology: **devops-artifacts**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by chcomley** [comment]
Hi @RohitSarangi-MS, thanks for the recommendation, I've created a user story to cover adding the info to the article. I've reached out to get an answer for you about  what happens to the people who got their Package Management licenses auto renewed on 1-May-2019. We'll be in touch. Happy Friday!

**Comment by chcomley** [comment]
Hi @RohitSarangi-MS, in regards to your licensing question:
Existing customers were charged for the month of May under the per user model. They receive 12 months of Artifacts storage for free, before they need to pay for Artifacts storage under the new model.
