### ISSUE TITLE
Repo is not found in GitHub

### ISSUE THREAD

**Issue by leizhang1984** [MicrosoftDocs/vsts-docs#4185]
Dear,

When I check: https://github.com/MicrosoftDocs/pipelines-javascript-docker, GitHub display web page is not found and 404 error

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45ba2ebe-27c4-111b-18b4-0192d8c3fb3a
* Version Independent ID: f48fdf00-e04f-b406-93f3-20b7fad568be
* Content: [Build and push to Azure Container Registry - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/languages/acr-template?view=azure-devops#feedback)
* Content Source: [docs/pipelines/languages/acr-template.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/languages/acr-template.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @shashankbarsin
* Microsoft Alias: **shasb**

**Comment by shashankbarsin** [comment]
We had forgotten to make the repo public before publishing the doc. We made it public the same day realising the mistake. Apologies for the inconvenience.
