### ISSUE TITLE
StakeHolder Access for Project Wiki

### ISSUE THREAD

**Issue by bbarman4u** [MicrosoftDocs/vsts-docs#4186]
Is there a plan to to provide access to the Project Wiki's to users with StakeHolder Permissions who may want to just view a knowledge base ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 954f4dc2-be98-46f5-1771-4cef3ba527bc
* Version Independent ID: b63d6819-4b5e-c1f3-5d49-83e9690f658b
* Content: [Provide free access to pipelines for Stakeholders - Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/organizations/security/provide-stakeholder-pipeline-access?view=azure-devops#feedback)
* Content Source: [docs/organizations/security/provide-stakeholder-pipeline-access.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/security/provide-stakeholder-pipeline-access.md)
* Product: **devops**
* Technology: **devops-new-user**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by adramasu** [comment]
Hi @bbarman4u,

Stakeholders can see Project Wikis, but won't be able to edit it. Please see [this link](https://docs.microsoft.com/en-us/azure/devops/project/wiki/wiki-readme-permissions?view=azure-devops) for more information on stakeholder permission.

**Comment by bbarman4u** [comment]
Thank you !
