### ISSUE TITLE
Very helpful, thanks!

### ISSUE THREAD

**Issue by jsuddsjr** [MicrosoftDocs/vsts-docs#4190]
Exactly what I needed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1debd814-eb48-c984-a4f9-7606093e9617
* Version Independent ID: f48ef796-c2e3-8fa3-6c41-326a5b252a3d
* Content: [Add and use work item templates to update user stories, tasks, issues, and other work items - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/backlogs/work-item-template?view=azure-devops&tabs=browser#feedback)
* Content Source: [docs/boards/backlogs/work-item-template.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/boards/backlogs/work-item-template.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@jsuddsjr - Thank you for the note. I appreciate it.
