### ISSUE TITLE
Pipeline Triggers Documentation Implies Incorrect Behaviour

### ISSUE THREAD

**Issue by BenResTech** [MicrosoftDocs/vsts-docs#4195]
Hi,

On the [Pipeline Triggers documentation ](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/build/triggers.md), in the section defining CI behaviour based on branches, there is the statement:

> If you don't specify any triggers, the default is as if you wrote:
> 
> ```
> trigger:
>   branches:
>     include:
>     - '*'  # must quote since "*" is a YAML reserved character; we want a string
> ```

In the Q&A section at the bottom, there is then the statement:

> The YAML file in my branch is different than the YAML file in my master branch, which one is used?
> When you have configured a CI trigger or a PR trigger, the YAML file that is in the branch being pushed is used.
> 
> - For CI triggers, the YAML file that is in the branch you are pushing is evaluated to see if a CI build should be run.
> - For PR triggers, the YAML file that is in the source branch of the PR is evaluated to see if a PR build should be run.

This suggests that the *only* thing that will cause the yml file in the push branch to be used is if a CI or PR trigger is defined. Because of the earlier statement that one is defined by default, the suggestion to me was that only if the CI or PR trigger was *customised to be different from master* would the local branch be used.

However, testing this behaviour shows that a change to a section other than the trigger, has the local change incorporated in the build. My testing example was to change the Agent Pool for the build job, leaving the default trigger in place in both master and my branch.

Rather than behaving as I would expect based on the above wording (I have not specified a trigger, so I would expect the master yml to be used), I instead see the non-trigger change (changing the Agent Pool) incorporated in my new build.

I would suggest that the behaviour of VSTS is correct, as I would always expect the 'local' pipeline yml to be used (unless advised otherwise as in this case!).
I think that the documentation should be updated to reword the Q&A section to state that the 'local' version of the pipelines yml will always be used (unless there *are* any use cases where it wouldn't be triggered from the branched version - I just haven't found one yet).

Let me know if more information is required.
Ben

**Comment by steved0x** [comment]
@BenResTech I'll make an update to the documentation to make it clearer that it is the YAML file in the branch being pushed that is used, even if you don't have a CI or PR trigger explictly defined in the YAML file. I can see how the "When you have configured a trigger" portion is ambiguous. I'll get that fixes, thank you for pointing that out.
