### ISSUE TITLE
Copied tickets keep the "Closed by" field, but docs say no history is copied

### ISSUE THREAD

**Issue by pabrams** [MicrosoftDocs/vsts-docs#4200]
[This doc](https://docs.microsoft.com/en-us/azure/devops/boards/backlogs/copy-clone-work-items?view=azure-devops&tabs=browser#copy-or-clone-a-work-item) says "No history or attachments are copied.", but we noticed that the "Closed by" field is copied from a Closed work item (TFS 2017, Update 3).  Is that part of the History?  Is this a bug in the docs, or a bug in TFS?

**Comment by KathrynEE** [comment]
@pabrams - I tried this on Azure DevOps Services and teh Closed by field wasn't copied over. I believe this could be a bug. Please report this on the support page here: https://azure.microsoft.com/en-us/support/devops/.

**Comment by pabrams** [comment]
@kathrynee the page I linked from says tfs 2017.  Why did you close the issue if you didnt try tfs?  The docs dont say only azure
