### ISSUE TITLE
Still in public preview?

### ISSUE THREAD

**Issue by NelsonLamprecht** [MicrosoftDocs/vsts-docs#4205]
Still in public preview?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77bcd39f-91ab-bb93-40fc-dd4fc5f2374f
* Version Independent ID: c228aece-669a-57d6-b3ed-d427586f8a61
* Content: [Publish and then download a Universal Package](https://docs.microsoft.com/en-us/azure/devops/artifacts/quickstarts/universal-packages?view=azure-devops&tabs=azuredevops#feedback)
* Content Source: [docs/artifacts/quickstarts/universal-packages.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/artifacts/quickstarts/universal-packages.md)
* Product: **devops**
* Technology: **devops-artifacts**
* GitHub Login: @mitchdenny
* Microsoft Alias: **midenn**

**Comment by mitchdenny** [comment]
Fixed via an internal PR.
