### ISSUE TITLE
Minor Typo in Commands

### ISSUE THREAD

**Issue by blueelvis** [MicrosoftDocs/vsts-docs#4209]
When trying to generate the name of the agent, there is a typo in both the sections for Windows & Linux. Instead of `--agent "${AZP_AGENT_NAME:-$(hostname)}" \`, it should be `--agent "${AZP_AGENT_NAME}:-$(hostname)" \` . That way, the hostname of the container gets appended properly.

Thanks,
Pranav

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b31d4f6c-d16d-2ba1-1294-6aa94e328046
* Version Independent ID: 88aec599-4410-697d-1002-1c41b1c17bb6
* Content: [Running a self-hosted agent in Docker - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/docker?view=azure-devops)
* Content Source: [docs/pipelines/agents/docker.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/agents/docker.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @juliobbv
* Microsoft Alias: **alewis**

**Comment by rpresser** [comment]
The purpose of the original code segment is not to append the hostname, but to use the hostname if no AZP_AGENT_NAME was supplied as an environment variable. The agent name is not permitted to contain a colon, so your correction of the typo is not usable.  If you truly want the hostname appended to whatever AZP_AGENT_NAME the container received then you should use `--agent "${AZP_AGENT_NAME}-$(hostname)" \`

**Comment by blueelvis** [comment]
@rpresser - Yea, this was my bad. Thanks for the explanation. I had some modifications to the script somehow. Closing this issue.
