### ISSUE TITLE
On premises target server

### ISSUE THREAD

**Issue by danobri** [MicrosoftDocs/vsts-docs#421]
Does the target server have to be an Azure VM, or could it be an on-premises Windows VM? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca1c5394-611b-b119-dbf3-b88404e351d5
* Version Independent ID: fcc23259-21ec-f9fa-4e25-f587e1e0f41b
* Content: [Deploy to an IIS web server on a Windows Virtual Machine](https://docs.microsoft.com/en-us/vsts/build-release/apps/cd/deploy-webdeploy-iis-deploygroups?view=vsts#feedback)
* Content Source: [docs/build-release/apps/cd/deploy-webdeploy-iis-deploygroups.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/build-release/apps/cd/deploy-webdeploy-iis-deploygroups.md)
* Service: **unspecified**
* GitHub Login: @erickson-doug
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment]
Thank you for your feedback. You can use any Windows server that is installed in the deployment group. It can be on-premises or cloud-hosted, VM or hardware, as long as the agent is installed and IIS is configured as shown.
