### ISSUE TITLE
Why was the BuildNumberFormat info removed?

### ISSUE THREAD

**Issue by hjtroteclaser** [MicrosoftDocs/vsts-docs#4211]
Why have you removed the BuildNumberFormatInfo? Now you give now no information at all. Who was that "smart" guy who removed that? Many external docs, stackoverflow links, ... are referring to this information but now its missing.
It took me some time to find it in an older version:
https://github.com/MicrosoftDocs/vsts-docs/blob/e5d4e6f62d381a0d78b2c3dba7ffeedcf25be73a/docs/pipelines/build/options.md

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0fa5a83c-70fd-6925-a8c8-256b21c21a2e
* Version Independent ID: 75f4a136-7245-7878-2953-6b68272fe4ec
* Content: [Build options - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/options?view=azure-devops#feedback)
* Content Source: [docs/pipelines/build/options.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/build/options.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by Leon99** [comment]
Not just external docs, I came here from https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml.

**Comment by srikcgaa2** [comment]
Me too reached from the above Microsoft documentation to find it missing!

**Comment by andyjlewis** [comment]
Thanks for the feedback. We need to add a link to https://docs.microsoft.com/en-us/azure/devops/pipelines/process/run-number. Heads up to @steved0x

**Comment by FixRM** [comment]
This is ridiculous! Please move this info back as build option page still refer to this article!

**Comment by scuba6388** [comment]
Just wow

**Comment by thelethalkind** [comment]
@andyjlewis @steved0x This is still an issue, are we able to get this information back?  Clicked on the info link next to "Build number format" under build definition and it links me here with no relevant information.

**Comment by jrm346** [comment]
ditto

**Comment by PJBowron** [comment]
And again...

**Comment by kollmats** [comment]
Does anyone know if the equivalent functionality is available elsewhere?

**Comment by jamers99** [comment]
Here is the version right before it was removed:
https://github.com/MicrosoftDocs/vsts-docs/blob/e5d4e6f62d381a0d78b2c3dba7ffeedcf25be73a/docs/pipelines/build/options.md

**Comment by steved0x** [comment]
I have updated that link in the Pipelines UI so that this will now take you to the right page, which is [Run (build) number](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/run-number?view=azure-devops&tabs=yaml

![image](https://user-images.githubusercontent.com/1580889/68246872-b45c8000-ffe7-11e9-971e-9fb35741012a.png)
)
