### ISSUE TITLE
Credential expiration and rollover process

### ISSUE THREAD

**Issue by jfcomst** [MicrosoftDocs/vsts-docs#4213]
It would be helpful if this also described expected behavior on credential expiration (if that is tracked) and recommended rollover process.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72b90dd0-49f9-4ed4-3010-9a64dde6ae5a
* Version Independent ID: 6e679d50-4e94-eee3-8793-af884cc909ca
* Content: [Service connections in Azure Pipelines and Team Foundation Server - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/library/service-endpoints?view=azure-devops#feedback)
* Content Source: [docs/pipelines/library/service-endpoints.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/library/service-endpoints.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by JayCooper73** [comment]
I agree. I have 175 projects and have to update 175 endpoints when the credentials expire. Anyone have any methodologies they use? Too bad we cant use a single connection across projects.

**Comment by RoopeshNair** [comment]
We don't track expiration of credentials. Typically Azure sends notification about the expiring credentials to the credential owners. However, we do plan to support sharing of service connections across projects. That way the overhead is minimal. @ashokirla  for timelines.

**Comment by jfcomst** [comment]
I appreciate that Microsoft is working on functionality to support multiple projects, but I want to make sure that we don't get sidetracked, and that we are still thinking about adding documentation describing the Microsoft recommended process for a credential rollover.  Thanks!

**Comment by RoopeshNair** [comment]
Got it thanks! We will try and add a blurb. However, it is determined by end user's company policies. 
By default auto-created Service Principal credentials are valid for an year. However, everytime you click on update service connection, it regenerates the credentials. The update frequency usually depends on company policy, we have seen customers rotating credentials from 15-days to a quarter or so.

**Comment by ashokirla** [comment]
Sharing of service connections across projects work now completed. We are doing some fit and finish. If you are interested, we can enable the preview version for you. Please reach out to us directly with your account details.

**Comment by WilliamAntonRohm** [comment]
@jfcomst -- please see @ashokirla's comment above.

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
