### ISSUE TITLE
Is it required to have the teams in the same AAD as the DevOps?

### ISSUE THREAD

**Issue by StefanSchoof** [MicrosoftDocs/vsts-docs#4218]
The documentation does not answer the question, if we can use the Teams App, with Teams in one AAD and the Azure DevOps in an other AAD. In our case the user have a B2B connection to the DevOps AAD.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b9adc845-adee-a494-79b4-3466f51d3ec9
* Version Independent ID: 12445205-8acc-98e6-fe65-9508e0dccb5c
* Content: [Azure Pipelines with Microsoft Teams - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/integrations/microsoft-teams?view=azure-devops)
* Content Source: [docs/pipelines/integrations/microsoft-teams.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/integrations/microsoft-teams.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @atinb
* Microsoft Alias: **atinb**

**Comment by fabricebauer** [comment]
Hello, on our side it works with two different AADs, provided you sign in with your target AAD when using the app from Teams.

**Comment by RGKarthik** [comment]
@StefanSchoof 

Are you hitting into any issue? Please write to us at AzureDevOpsTeamsApps@microsoft.com with details so that we can look  into it.

**Comment by StefanSchoof** [comment]
@RGKarthik thanks for the offer.

We expired problems in this setup in previous integrations and now I wanted upfront to know if this is a supported setup. But with this info, I think we will give it a try.

**Comment by atinb** [comment]
@StefanSchoof Were you able to get this working? Do let us know if you are running into issues. Thanks!

**Comment by StefanSchoof** [comment]
Thanks for your answers. I will not able to test this.
