### ISSUE TITLE
Azure DevOps Server pricing?

### ISSUE THREAD

**Issue by tompatib** [MicrosoftDocs/vsts-docs#4219]
This change is much appreciated. Will we have similar model coming to Azure DevOps Server 2019? I don't find the page if I select the on-prem version.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b5531731-8bd5-b178-9307-f01b3d2f23b3
* Version Independent ID: 8dea3b69-ad79-5045-3820-4a83a0bc4ce0
* Content: [Sign up for Azure Artifacts](https://docs.microsoft.com/en-us/azure/devops/artifacts/sign-up-azure-artifacts?view=azure-devops&viewFallbackFrom=azure-devops-2019#feedback)
* Content Source: [docs/artifacts/sign-up-azure-artifacts.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/artifacts/sign-up-azure-artifacts.md)
* Product: **devops**
* Technology: **devops-artifacts**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @tompatib, thanks for reaching out! I've created a user story to have this version added to the documentation. In the meantime, I can tell you that for Azure DevOps Server 2019, if you have a Basic license you have access to Azure Artifacts. Please let me know if you have any further questions, thank you.

**Comment by tompatib** [comment]
Hi @chcomley, I know that the Azure Artifacts is available with the on-prem version, but prior versions and the 2019 RC had the per user per month subscribe model (free with MSDN Enterprise), which seems to changed to per size model for the Azure DevOps Services. Question if we will have the same per size licensing available for the Azure DevOps Server 2019.

**Comment by chcomley** [comment]
Hi @tompatib,

For Server 2019, Azure Artifacts is included with the Basic access

Check out this blog: https://devblogs.microsoft.com/devops/a-simpler-way-to-buy-azure-devops/ 

**On-premises Azure Artifacts now included with Basic license**
Users with a Basic license will now be able to use Azure Artifacts on-premises without needing to purchase an Azure Artifacts extension. This means with Azure DevOps Server 2019 (formerly Team Foundation Server), users with a Basic License can create and consume Azure Artifacts on-premises if they have a Basic license assigned. Please note that for previous versions of our server product, an Azure Artifacts extension is still needed to access this functionality.

Hopefully this answers your question. Please let me know. Thanks!

**Comment by chcomley** [comment]
I'm going to close this issue, @tompatib. Please let me know if I can help any further. Thanks!
