### ISSUE TITLE
Scrum workflow states: Committed state description

### ISSUE THREAD

**Issue by NikGovorov** [MicrosoftDocs/vsts-docs#422]
Hi Team,

Shouldn't the description of Committed state on [Scrum process work item types and workflow](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/work/work-items/guidance/scrum-process-workflow.md#scrum-workflow-states) page 
be changed to 
> The team updates the status to Committed when they decide to ~~complete~~ **start** the work during the sprint

?

**Comment by NikGovorov** [comment]
Technically the current description is not incorrect, however it confused me as not native English speaker.

**Comment by KathrynEE** [comment]
@NikGovorov - Thank you for your comment. The text was written with 'complete' as Scrum practices emphasize that the team commits to completing the items in a Sprint. However, I understand how it would be confusing, so I have updated the text to "when they decide to commit to working on it during the sprint"

**Comment by NikGovorov** [comment]
Thanks @KathrynEE !
