### ISSUE TITLE
What about Azure DevOps server?

### ISSUE THREAD

**Issue by evertonmc** [MicrosoftDocs/vsts-docs#4220]
Please share a timeline for the on-prem support, or at least for deploying and consuming artifacts to/from ADO-Services from a on-prem installation

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77bcd39f-91ab-bb93-40fc-dd4fc5f2374f
* Version Independent ID: c228aece-669a-57d6-b3ed-d427586f8a61
* Content: [Publish and then download a Universal Package](https://docs.microsoft.com/en-us/azure/devops/artifacts/quickstarts/universal-packages?view=azure-devops&tabs=azuredevops)
* Content Source: [docs/artifacts/quickstarts/universal-packages.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/artifacts/quickstarts/universal-packages.md)
* Product: **devops**
* Technology: **devops-artifacts**
* GitHub Login: @mitchdenny
* Microsoft Alias: **midenn**

**Comment by chasewilson** [comment]
Hi @evertonmc , thanks for the question. As far as I know, There isn't going to be support for DevOps Server. I would suggest reaching out to the [Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html) for a feature request or further information.
