### ISSUE TITLE
How to configure bash on Windows self hosted build agent?

### ISSUE THREAD

**Issue by EM1L** [MicrosoftDocs/vsts-docs#4223]
Please add section how to configure bash on self hosted windows based agents.
I guess it requires [WSL](https://aka.ms/wslstore) being installed. I have the Ubuntu distro, however it appears there is a problem! 
I am not sure if it is a configuration or a bug, however I have submitted a [bug report here](https://developercommunity.visualstudio.com/content/problem/568027/bash-step-doesnt-work-on-windows-self-hosted-agent.html).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43799c5d-2f13-cc76-a1c0-a3f850e16d4e
* Version Independent ID: 97a5b73f-faf7-f9c0-9269-fc79984616d6
* Content: [Deploy a Azure Pipelines agent on Windows - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/v2-windows?view=azure-devops)
* Content Source: [docs/pipelines/agents/v2-windows.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/agents/v2-windows.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by steved0x** [comment]
Closing here since the bug is being tracked [here](https://developercommunity.visualstudio.com/content/problem/568027/bash-step-doesnt-work-on-windows-self-hosted-agent.html)
