### ISSUE TITLE
Documentation is incorrect about pre-installed Python. No python is installed on win1803 hosted machines.

### ISSUE THREAD

**Issue by kevinmmarlow** [MicrosoftDocs/vsts-docs#4226]
https://docs.microsoft.com/en-us/azure/devops/pipelines/languages/python?view=azure-devops

**Comment by steved0x** [comment]
You are correct and it looks like that page has been updated. To see a list of software installed on each Microsoft-hosted agent image, see: https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops
