### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by ranjan-ranjan** [MicrosoftDocs/vsts-docs#4227]
In https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/integrate/concepts/dotnet-client-libraries.md , the words `new REST APIs` have broken link

**Comment by ranjan-ranjan** [comment]
#1874

**Comment by chcomley** [comment]
Thanks for reaching out @ranjan-ranjan. I've just completed a PR, fixing this link, which should go live sometime this morning. Until then, here's the [link](https://docs.microsoft.com/en-us/rest/api/azure/devops/?view=azure-devops-rest-5.0). Please let me know if I can help any further. Thanks and happy Friday!
