### ISSUE TITLE
Filter option not documented

### ISSUE THREAD

**Issue by fritsboers** [MicrosoftDocs/vsts-docs#423]
In October 2017 the option to filter work items that are shown on the plan was added. But this feature is not documented!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d704a22b-6a65-7a4c-1111-944c9aeff944
* Version Independent ID: 5880f4f1-ce11-3f43-e0dd-d569f5206b4d
* Content: [Review team delivery plans - VSTS & TFS](https://docs.microsoft.com/en-us/vsts/work/scale/review-team-plans?view=vsts)
* Content Source: [docs/work/scale/review-team-plans.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/work/scale/review-team-plans.md)
* Service: **unspecified**
* GitHub Login: @erickson-doug
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@fritsboers - Thank you for your comment. I've added a work item to my backlog to update the topic. Updates should get published within the next few weeks. FYI - we don't always document every feature, particularly if they are easily discoverable.
