### ISSUE TITLE
bash: ./start.sh: /bin/bash^M: bad interpreter: No such file or directory

### ISSUE THREAD

**Issue by lusocoding** [MicrosoftDocs/vsts-docs#4230]
When I first tried to run the docker container, after building it in a Windows 10 machine, I got the following error: "standard_init_linux.go:207: exec user process caused "no such file or directory"". Some research and an interactive session were enough to find the solution to this issue (https://askubuntu.com/questions/304999/not-able-to-execute-a-sh-file-bin-bashm-bad-interpreter). Therefore recommend to modify the last RUN as follows: 

RUN chmod +x start.sh \
&& sed -i -e 's/\r$//' start.sh

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b31d4f6c-d16d-2ba1-1294-6aa94e328046
* Version Independent ID: 88aec599-4410-697d-1002-1c41b1c17bb6
* Content: [Running a self-hosted agent in Docker - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/docker?view=azure-devops)
* Content Source: [docs/pipelines/agents/docker.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/agents/docker.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @juliobbv
* Microsoft Alias: **alewis**

**Comment by rpresser** [comment]
A better alternative might be to use an advanced editor, like Vim or Notepad++, that can save files with unix line endings; or to simply use `dos2unix` before copying the file into the container image.

**Comment by lusocoding** [comment]
In this specific case the editor used was VS Code. However I do think it would be best to have that additional step in the Docker image so that the example Dockerfile can be built either in Windows or Linux systems without requiring to run additional software.

**Comment by mariuszdotnet** [comment]
If you're using VS Code change the "End of Line Sequence" from CRLF to LF on the "start.sh" file that did the trick for me.

**Comment by andyjlewis** [comment]
@vtbassmatt if you want these assigned to @juliobv, then he needs to be added to this repo
