### ISSUE TITLE
Possible to use msal.js?

### ISSUE THREAD

**Issue by ranarn** [MicrosoftDocs/vsts-docs#4232]
Since msal is promoted as the replacement for adal, would this work msal? and if so, how?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 294772ce-58a0-bb83-8927-3e69beca39df
* Version Independent ID: d9c4a4b3-3abf-d738-369e-fff8532e9dd9
* Content: [Guidance for authentication](https://docs.microsoft.com/en-us/azure/devops/integrate/get-started/authentication/authentication-guidance?view=azure-devops#feedback)
* Content Source: [docs/integrate/get-started/authentication/authentication-guidance.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/integrate/get-started/authentication/authentication-guidance.md)
* Product: **devops**
* Technology: **devops-ecosystem**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by chcomley** [comment]
Hi @ranarn, I'm looking into this and will get back to you as soon as possible. Thank you for reaching out!

**Comment by chcomley** [comment]
Hi @ranarn, I've been in touch with a PM who says that for accessing Azure DevOps REST APIs, simply presenting the Azure AD token wouldn't work.
Do let us know if you have any further questions, please!
Thanks!
