### ISSUE TITLE
Please go into more detail on connecting using SSH access keys. 

### ISSUE THREAD

**Issue by stuartdotnet** [MicrosoftDocs/vsts-docs#4235]
The dialog asks for a username and won't work without it...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 15a9c9ac-02c4-839a-555b-8d9d22d08fab
* Version Independent ID: 259fcc03-e73d-2004-dfa6-067728a85981
* Content: [Import a Git repo into your project - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/import-git-repository?view=azure-devops#feedback)
* Content Source: [docs/repos/git/import-git-repository.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/repos/git/import-git-repository.md)
* Product: **devops**
* Technology: **devops-code-git**
* GitHub Login: @apawast
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
@stuartdotnet We're checking to see if import using SSH is supported and if so what the right syntax is for the import dialog, and will report back soon.

**Comment by steved0x** [comment]
@stuartdotnet Unfortunately ssh authentication isn't supported for importing Git repos, but you can follow the manual steps in [this](https://docs.microsoft.com/en-us/azure/devops/repos/git/import-git-repository?view=azure-devops#manually-import-a-repo) section to import your repo that uses SSH.

I'll update the article to include that SSH isn't supported for importing using the wizard.
