### ISSUE TITLE
target Path Description does not match text on Pipeline artifacts in Azure Pipelines

### ISSUE THREAD

**Issue by StefanSchoof** [MicrosoftDocs/vsts-docs#4236]
On this page

> targetPath: ... Typically, you'll specify $(Build.ArtifactStagingDirectory)

On [Pipeline artefacts in Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/pipeline-artifacts?view=azure-devops&tabs=yaml):

> With pipeline artifacts, we recommend pointing the Publish Pipeline Artifacts tasks directly to the paths to be published.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 41baa0b5-175c-a697-4b7d-c150259c6e6b
* Version Independent ID: 75085b15-1acc-526a-0495-74a13c42c1d5
* Content: [Publish Pipeline Artifacts task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/publish-pipeline-artifact?view=azure-devops&viewFallbackFrom=vsts)
* Content Source: [docs/pipelines/tasks/utility/publish-pipeline-artifact.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/utility/publish-pipeline-artifact.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @mitchdenny
* Microsoft Alias: **midenn**

**Comment by StevenLiekens** [comment]
I'd like to add that `targetPath` appears to be optional. If not specified, the entire working directory is published. That can be useful when combined with `.artifactignore` files.

**Comment by mitchdenny** [comment]
#please-close
