### ISSUE TITLE
Countdown Widget extension link is incorrect

### ISSUE THREAD

**Issue by hobpet** [MicrosoftDocs/vsts-docs#424]
It is hhttps://marketplace.visualstudio.com/items?itemName=ms-devlabs.CountdownWidget
Note the extra "h"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c51be3f2-f0da-4018-7c0a-7579221b6c9d
* Version Independent ID: 7690501c-6c92-d82e-1c44-02aa794ee6e5
* Content: [DevOps - Phase the roll-out of your application through rings](https://docs.microsoft.com/en-us/vsts/articles/phase-rollout-with-rings?view=vsts)
* Content Source: [docs/articles/phase-rollout-with-rings.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/articles/phase-rollout-with-rings.md)
* Service: **unspecified**
* GitHub Login: @josh garverick
* Microsoft Alias: **willys**

**Comment by steved0x** [comment]
@hobpet Thanks for catching that, I'll get that fixed today. Thank you.
