### ISSUE TITLE
Does Sprint taskboard have split column feature?

### ISSUE THREAD

**Issue by jknapp25** [MicrosoftDocs/vsts-docs#4243]
The split column feature is also valuable to our team on our Sprint taskboard. Is this feature available on the sprint taskboards as well?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6874a2f-2115-85a1-a60e-b024071ab2d2
* Version Independent ID: 859c2346-f23f-5cc6-1f83-a1c8316145b8
* Content: [Split columns on your Kanban board - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/boards/split-columns?view=azure-devops#feedback)
* Content Source: [docs/boards/boards/split-columns.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/boards/boards/split-columns.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@jknapp25 - Thank you for your inquiry. The Split column feature is only available on Kanban boards. It isn't available on sprint taskboards.
