### ISSUE TITLE
Dump statement

### ISSUE THREAD

**Issue by keithdoyle9** [MicrosoftDocs/vsts-docs#4244]
Is it possible to dump a database from Azure DB for MySQL via this task?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 087218d2-1d70-a629-5d90-07a8141fe806
* Version Independent ID: 8ddec4c9-8669-1583-bd36-dd9349af29bc
* Content: [Azure Database for Mysql Deployment task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-mysql-deployment?view=azure-devops#feedback)
* Content Source: [docs/pipelines/tasks/deploy/azure-mysql-deployment.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/deploy/azure-mysql-deployment.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by keithdoyle9** [comment]
No longer an issue for me. Using bash commands to do this.

**Comment by RoshanKumarMicrosoft** [comment]
We are not supporting taking Mysql dump using AzureMysql task . But you are right you can use bash command to do so. 
![Capture1](https://user-images.githubusercontent.com/33001640/62927641-927ea300-bdd4-11e9-921a-5cbd639ae770.PNG)
Mysqldump exe is already inside mysql client bin folder.
