### ISSUE TITLE
Missing documentation "Connect to your Azure DevOps Services TFVC Repository"

### ISSUE THREAD

**Issue by JamesMiera** [MicrosoftDocs/vsts-docs#4245]
Title is self explanatory - You are missing documentation "Connect to your Azure DevOps Services TFVC Repository".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e818c26d-b8fd-e532-95af-7f5654acf7e2
* Version Independent ID: d837a5c4-4634-dac2-79e8-c5aa15deaaed
* Content: [VS Code extension for Java development with Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/java/vscode-extension?view=azure-devops)
* Content Source: [docs/java/vscode-extension.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/java/vscode-extension.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @DavidStaheli
* Microsoft Alias: **dastahel**

**Comment by davidstaheli** [comment]
Thanks for reporting this James.  We have insufficient bandwidth to address this for TFVC.
