### ISSUE TITLE
Restricting Notifications for Specific Pipeline Release Stages

### ISSUE THREAD

**Issue by alohaninja** [MicrosoftDocs/vsts-docs#4248]
We have half-dozen stages in our release pipeline and don't need notifications for all of them - how can we restrict which notifications we receive? Many of the notifications are not critical for sharing in our teams/slack channel. 

Would be great if the Teams App supported configuration for which stages published notifications like we have for status badge options or during queue release time.

### Release Pipeline Options - Status Badges
![image](https://user-images.githubusercontent.com/26234626/57896612-69b33580-7806-11e9-828c-4f4a1543c813.png)

### Queuing New Release
![image](https://user-images.githubusercontent.com/26234626/57896646-9f581e80-7806-11e9-95d4-517cbd870e26.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b9adc845-adee-a494-79b4-3466f51d3ec9
* Version Independent ID: 12445205-8acc-98e6-fe65-9508e0dccb5c
* Content: [Azure Pipelines with Microsoft Teams - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/integrations/microsoft-teams?view=azure-devops)
* Content Source: [docs/pipelines/integrations/microsoft-teams.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/integrations/microsoft-teams.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @atinb
* Microsoft Alias: **atinb**

**Comment by RGKarthik** [comment]
@alohaninja ,
The app supports your ask. Please follow below steps

a) Run '@Azure Pipelines subscriptions'
b) Click on 'add subscription' button
c) Apply filters to suit your need (select required stages) & create subscription
d) If here are old subscriptions for the same event without any filters (the one which is spamming your channel), remove them 
Just curious from a usability perspective; was this capability tough to discover?

**Comment by atinb** [comment]
@alohaninja Did this work for you? Can we close this ticket? Thanks!

**Comment by alohaninja** [comment]
@atinb - I was able to successfully filter the stages of a release - however the workflow is not very intuitive. Maybe this GH issue will help to server others seeking to do the same. Once I completed it for one subscription - it was easier to add filters for the other stages and statuses. 

For Builds - it seems you can't get notified when builds start like you can for releases - is there any way to add **Build Started** as an option?

![image](https://user-images.githubusercontent.com/26234626/59310231-9407df80-8c5a-11e9-98fc-cd68eaf9c0ce.png)

**Comment by atinb** [comment]
Thanks @alohaninja - we are looking to see how we can make it easy for users to discover the command.
Unfortunately, Build Started is not an option provided by Azure DevOps events currently.

**Comment by atinb** [comment]
@andyjlewis Kindly close
