### ISSUE TITLE
DevOps demo generator source code

### ISSUE THREAD

**Issue by inverted360** [MicrosoftDocs/vsts-docs#4249]
Please add git location for demo generator source (so I can submit issues and help resolve)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a4208398-e77f-5bef-5739-6539c3ba53bb
* Version Independent ID: f09154ed-0d77-6ed6-3dc8-4b91e6563236
* Content: [Use Azure DevOps Demo Generator](https://docs.microsoft.com/en-us/azure/devops/demo-gen/use-demo-generator-v2?view=azure-devops#feedback)
* Content Source: [docs/demo-gen/use-demo-generator-v2.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/demo-gen/use-demo-generator-v2.md)
* Product: **devops**
* Technology: **devops-new-user**
* GitHub Login: @thomps23
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
@inverted360 Here it is: https://github.com/microsoft/AzureDevOpsDemoGenerator

Thank you.

**Comment by softwarecraft** [comment]
Link provided by @steved0x is broken and doesn't appear in Internet Archives, did it ever exist? This issue is still an issue. Please re-open it!

**Comment by shajusukumaran** [comment]
The link is broken. Can you please share the updated link? Two questions:
1. Can we create custom templates and use it with the generator? If yes, do you have a documentation on how to create a template?
2. Are you planning to open source the Azure DevOps demo generator code?

Thanks,
Shaju
