### ISSUE TITLE
Not enough information

### ISSUE THREAD

**Issue by tmciver** [MicrosoftDocs/vsts-docs#4253]
It would be helpful to see a full pipeline yaml file using this task.  Also, it's not clear what the value for `containerRegistry` should be - even when visiting the "Docker registry service connection" link.  A full example should be shown.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d9dbf88-7e55-d427-145e-d36b04fb197f
* Version Independent ID: a3f30c00-817c-9c05-7a57-3f2bf618821e
* Content: [Docker task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/docker?view=azure-devops#feedback)
* Content Source: [docs/pipelines/tasks/build/docker.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/build/docker.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @shashankbarsin
* Microsoft Alias: **shasb**

**Comment by DrSensor** [comment]
It's also not clear how to input multiple `arguments`. Is it the same as `tags`?

**Comment by shashankbarsin** [comment]
@tmciver the value for containerRegistry needs to be the name of the Docker registry service connection (Connection name field in [Docker registry service connection](https://docs.microsoft.com/en-us/azure/devops/pipelines/library/service-endpoints?view=azure-devops&tabs=yaml#sep-docreg)).

Adding a full pipeline YAML in the task documentation will not be possible as we are trying to keep the task documents task specific. However, this [sample snippet](https://docs.microsoft.com/en-us/azure/devops/pipelines/languages/acr-template?view=azure-devops#how-we-build-your-pipeline) from the Build and push to ACR template showcases this end to end flow. Please refer to the same and let us know if more details are required

**Comment by shashankbarsin** [comment]
@DrSensor arguments input is not the same as tags. It exists to pass any optional overrides that you may want to pass to the docker cli that is run under the hood for the Docker task as shown [in this section of the Docker task doc](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/docker?view=azure-devops#other-commands-and-arguments)
