### ISSUE TITLE
Path-based?

### ISSUE THREAD

**Issue by rfalanga** [MicrosoftDocs/vsts-docs#4255]
Comparing TFVC to Git, under Branching, is written, "Path-based branches are used mostly as long-standing constructs to isolate risk of change among feature teams and releases." What do you mean by "path-based"?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a1dc9a4a-7828-f40f-4cf0-e0b1f5476ff2
* Version Independent ID: 278aed60-558e-3beb-2ed4-c2517c2cd05d
* Content: [Git and TFVC version control - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/tfvc/comparison-git-tfvc?view=azure-devops#feedback)
* Content Source: [docs/repos/tfvc/comparison-git-tfvc.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/repos/tfvc/comparison-git-tfvc.md)
* Product: **devops**
* Technology: **devops-code-tfvc**
* GitHub Login: @apawast
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
@rfalanga Path based can be organizing your branches into different areas, such as `features`, `users/youralias/description`, `hotfix`, and the like, as a way to help keep things organized. For more information, see [Git branching strategies](https://docs.microsoft.com/en-us/azure/devops/repos/git/git-branching-guidance?view=azure-devops). Does that info help? Please reactivate this issue, or create a new one if you have additional feedback. Thank you.
