### ISSUE TITLE
Don't provide unusable examples without caveats

### ISSUE THREAD

**Issue by RachelAmbler** [MicrosoftDocs/vsts-docs#426]
Attempting to use a `LabelText` element inside any control hosted inside the `SystemControls` block yields the following error:

_The element 'Control' cannot contain child element 'LabelText' because the parent element's content model is empty._

According to [TF237070](https://developercommunity.visualstudio.com/content/problem/111416/tfs20172-tf237070-the-element-control-cannot-conta.html "TFS2017.2 TF237070: The element 'Control' cannot contain child element 'LabelText' because the parent element's content model is empty.") this is **_NOT_** a bug, but a message that will be given if `LabelText` is used inside a control hosted on the `SystemControls` block.

This being the case, why does Microsoft provide an example (**Example: Add a hyperlink to a field**) of using this in an property (`System.Title`) that pretty much only is ever used inside the `SystemControls` block?

Could you have at least put this down as a warning (or better still, used another, none `SystemControls` used property, such as `Microsoft.VSTS.Scheduling.Effort`) ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a199127-c2cc-bcbb-31b8-0fb4c74b0875
* Version Independent ID: c397bf57-c7ee-77f9-7211-baa52f3425dc
* Content: [Link and Param XML elements reference](https://docs.microsoft.com/en-us/vsts/work/customize/reference/link-param-xml-elements-reference?view=vsts#remarks)
* Content Source: [docs/work/customize/reference/link-param-xml-elements-reference.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/work/customize/reference/link-param-xml-elements-reference.md)
* Service: **unspecified**
* GitHub Login: @erickson-doug
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@rachel-msft - Thank you for your comment. I've updated this topic and the example to better reflect what is supported. The updates should be live later today.
