### ISSUE TITLE
Stop HTML-encoding comments when using docs.microsoft.com interface

### ISSUE THREAD

**Issue by letmaik** [MicrosoftDocs/vsts-docs#4261]
E.g. > becomes `&gt;` in the issue text. This is annoying as I then have to open the new issue on GitHub and fix the formatting.

**Comment by thomps23** [comment]
@letmaik I filed this issue in the repo for site experience feedback [here](https://github.com/MicrosoftDocs/feedback/issues/1513). Feel free to add to it etc... 

I'm going to close _**this**_ issue out as its not directly related to the Azure DevOps documentation.
