### ISSUE TITLE
How to limit access of service connection to selected YAML pipelines?

### ISSUE THREAD

**Issue by letmaik** [MicrosoftDocs/vsts-docs#4262]
I created a separate YAML pipeline that is not triggered by CI/PR but has to be manually invoked by an authorized member. This pipeline uses a GitHub service connection with permissions that I want to restrict to be used *only* by this pipeline. How can I do that? 
Currently, it looks like I can only use the "Allow all pipelines to use this connection" option. This is bad, since a malicious actor could edit one of the other PR-triggered YAML pipelines and use this "elevated" service connection very easily and do damage. EDIT: This would only work if "Make secrets available to builds of forks" is enabled (service connection is a secret, as I just found out), and by default it's disabled. So it looks like it's not a security issue in general.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72b90dd0-49f9-4ed4-3010-9a64dde6ae5a
* Version Independent ID: 6e679d50-4e94-eee3-8793-af884cc909ca
* Content: [Service connections in Azure Pipelines and Team Foundation Server - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/library/service-endpoints?view=azure-devops&tabs=yaml#use-connection)
* Content Source: [docs/pipelines/library/service-endpoints.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/library/service-endpoints.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by RoopeshNair** [comment]
Support for limiting pipelines that can access the service connection is in the works. 
Adding @ashokirla  for timelines.

**Comment by ashokirla** [comment]
We are shipping pipeline permissions for service connections as a preview feature along with new service connections UX. It will be available in 3 weeks from now.

**Comment by WilliamAntonRohm** [comment]
I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
