### ISSUE TITLE
itemPath is exclude files with .

### ISSUE THREAD

**Issue by StefanSchoof** [MicrosoftDocs/vsts-docs#4264]
The `itemPattern` default value `**` exclude hidden files starting with `.`. I think that is an important behavior, especially because the `PublishPipelineArtifact` has no such restriction, and should be clear documented.

To get all files I changed the `itemPattern` to `{**,.*}`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b03d67d0-8738-72e6-dbe7-324c1784d4fc
* Version Independent ID: bbb4d774-cd98-3ecb-7ccf-5f49e6f2b425
* Content: [Download Pipeline Artifact task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/download-pipeline-artifact?view=azure-devops)
* Content Source: [docs/pipelines/tasks/utility/download-pipeline-artifact.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/utility/download-pipeline-artifact.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @mitchdenny
* Microsoft Alias: **midenn**

**Comment by wgv-srsedate** [comment]
This solution did not work for us, we are still unable to download hidden files (files that start with a period/dot).

**Comment by StefanSchoof** [comment]
I my case the hidden file was in the root folder. To get all hidden files you need `{**/.*,**}`.

**Comment by StefanSchoof** [comment]
The behavior has changed 3 weeks ago and hidden files are download by default
