### ISSUE TITLE
Index Sources & Publish Symbols task - Version 1

### ISSUE THREAD

**Issue by fowl2** [MicrosoftDocs/vsts-docs#4266]
This page only appears to document version 2 of the task, where are the docs for v1?

I've got a bunch of pipelines that were already using v1 and it'd be nice to know what they're doing! (And then upgrade them if there are benefits)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 946d67f6-9bb7-481f-f32f-59b5965f9590
* Version Independent ID: 8865f1e2-15b3-8cdb-1d8c-939c665e9bdc
* Content: [Index Sources & Publish Symbols build and release task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/index-sources-publish-symbols?view=azure-devops#feedback)
* Content Source: [docs/pipelines/tasks/build/index-sources-publish-symbols.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/build/index-sources-publish-symbols.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @PBoraMSFT
* Microsoft Alias: **pbora**

**Comment by PBoraMSFT** [comment]
@andyjlewis @davidstaheli - not sure why this got assigned to me. Can you please route appropriately?

**Comment by steved0x** [comment]
@fowl2 Sorry for the extreme delay - I had followed up this and the information I got was that we don't keep the source code for all older version in the repo, and this is one of them. If you had a specific question about the task you could file an issue here and they will take a look at it: https://github.com/microsoft/azure-pipelines-tasks
