### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by ississippi** [MicrosoftDocs/vsts-docs#4268]
Link "based on research" leads to the Main Research page instead of the specific link "convergent-software-peer-review-practices".

https://www.microsoft.com/research/publication/convergent-software-peer-review-practices/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe168fc3-2ed2-b3e6-ce30-cac721165ceb
* Version Independent ID: 8d63fbd7-12c4-9a94-92f6-969e7eb41037
* Content: [Git branching guidance - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/git-branching-guidance?view=azure-devops#feedback)
* Content Source: [docs/repos/git/git-branching-guidance.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/repos/git/git-branching-guidance.md)
* Product: **devops**
* Technology: **devops-code-git**
* GitHub Login: @apawast
* Microsoft Alias: **sdanie**

**Comment by ississippi** [comment]
This works:
https://www.microsoft.com/en-us/research/publication/convergent-software-peer-review-practices/

**Comment by thomps23** [comment]
@steved0x is this one you can knock out quickly?

**Comment by steved0x** [comment]
@ississippi Thanks for letting us know, you are the 2nd person to report this (the other one is in #4290) It looks like it has been fixed now, as the original link seems to be working. Please let us know if it still is not working for you. Thank you!

**Comment by spottedmahn** [comment]
works today, maybe a bug fix on https://www.microsoft.com/research/ ? 🤔
