### ISSUE TITLE
Bad encoding or other errors in first paragraph

### ISSUE THREAD

**Issue by RachelAmbler** [MicrosoftDocs/vsts-docs#427]
Text in the 1st paragraph on the  `en-us` version of this page currently reads as:

>   You can change the workflow for a work item type (WIT) to support your business and team processes. WITs support tracking all types of workâ”€requirements, tasks, code defectsâ”€to support software development.

It should probably be something like:

> You can change the workflow for a work item type (WIT) to support your business and team processes. WITs support tracking all types of work (requirements, tasks, code defects) to support software development.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e7710ee0-e1b8-393f-97c3-f049293e5312
* Version Independent ID: 7bb16831-6f86-d1a8-3c71-76f60cc7e1a3
* Content: [Change the workflow for a work item type](https://docs.microsoft.com/en-us/vsts/work/customize/reference/change-workflow-wit?toc=/vsts/work/customize/toc.json&bc=/vsts/work/customize/breadcrumb/toc.json&view=vsts)
* Content Source: [docs/work/customize/reference/change-workflow-wit.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/work/customize/reference/change-workflow-wit.md)
* Service: **unspecified**
* GitHub Login: @erickson-doug
* Microsoft Alias: **kaelli**

**Comment by steved0x** [comment]
@RachelAmbler Thanks for catching that - those garbled characters are actually hyphens, I have fixed them and they'll be live later today. Thank you for letting us know!

**Comment by KathrynEE** [comment]
@rachel-msft - Thank you for your comment. I'm updating the topic and the updates should be live later today.
