### ISSUE TITLE
Test Plan and Stakeholders

### ISSUE THREAD

**Issue by fhack2** [MicrosoftDocs/vsts-docs#4270]
In Azure DevOps Stakeholders can't see the Test Plan option. So it's misleading that it says they can here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a35602ee-9d11-9746-4b79-075e295a5fb8
* Version Independent ID: dbea8e30-e80b-8f13-987e-ef0ad3ba9b83
* Content: [Default permissions and access quick reference - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/security/permissions-access?view=azure-devops#test-plans)
* Content Source: [docs/organizations/security/permissions-access.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/security/permissions-access.md)
* Product: **devops**
* Technology: **devops-security**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@fhack2 - Thank you for your comment. You are correct that Stakeholders cannot see the Test Plans pages, however, the Test & Feedback extension is available to Stakeholders.  So leaving the content as is for now.

**Comment by fhack2** [comment]
That extension requires you to have Basic license. Basic users can already see test plans.

Fahim Hack
