### ISSUE TITLE
When created Bug template, able to include link to specific PBI?

### ISSUE THREAD

**Issue by sorikorik** [MicrosoftDocs/vsts-docs#4271]

**Comment by sorikorik** [comment]
Following instructions from here: https://docs.microsoft.com/en-us/azure/devops/boards/backlogs/work-item-template?view=azure-devops&tabs=browser

I don't see any way of having the bug template to also automatically linking to a parent PBI. We are trying to do a bug bash and would like all new bugs created within the template to automatically be linked to a PBI, Feature, or Initiative.

**Comment by KathrynEE** [comment]
@sorikorik - Thank you for your inquiry. The scenario you suggest isn't a supported feature. If you'd like to suggest this as a feature to be supported, please do so here: https://developercommunity.visualstudio.com/content/idea/post.html?space=21.  Meanwhile - you might want to add a tag to your bug template and then do a bulk update to link all work items with that tag to a parent work item.
