### ISSUE TITLE
GUI For Task

### ISSUE THREAD

**Issue by dotnetcoder01** [MicrosoftDocs/vsts-docs#4273]
Is the File Transform task available in the Azure DevOps Server 2019 GUI?  I do not use YAML builds and could really use this task for app.config files.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 064f48ba-1c34-6422-5fe3-c3e88d2803c4
* Version Independent ID: c38f5761-4718-9aae-bc83-063257a78eb3
* Content: [File Transform task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/file-transform?view=azure-devops-2019#feedback)
* Content Source: [docs/pipelines/tasks/utility/file-transform.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/utility/file-transform.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by RoopeshNair** [comment]
@dotnetcoder01  - Azure App Service deploy task supports file transforms, have you tried it? Independent file transform tasks didn't make it in TFS 2019

**Comment by dotnetcoder01** [comment]
I am deploying to on premise.  I was looking for the independent file transformation task.  From the documentation it is not clear that the task was not included with Azure Devops Server 2019 .

**Comment by nk111** [comment]
Actually none of the methods described [here](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/transforms-variable-substitution?view=azure-devops) work on premise. This is quite frustrating since it's a usefull feature. I ended up adding powershell script tasks which do the replace.
