### ISSUE TITLE
Examples Using > [Field] Syntax

### ISSUE THREAD

**Issue by KennyDay** [MicrosoftDocs/vsts-docs#4275]
I'm not able to find any examples of queries that use the [Field] syntax.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: af1f1eca-034e-c54b-8770-6d287d3cea44
* Version Independent ID: c76c65ee-d77d-00b7-04f0-cce651d0b676
* Content: [Learn how to find, list, and filter work items using queries - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/queries/?toc=%2Fazure%2Fdevops%2Fboards%2Fqueries%2Ftoc.json&bc=%2Fazure%2Fdevops%2Fboards%2Fqueries%2Fbreadcrumb%2Ftoc.json&view=azure-devops)
* Content Source: [docs/boards/queries/index.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/boards/queries/index.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@KennyDay - Thank you for your feedback. You are correct that there are currently no examples showing how to use a Field in a query. I will add your request to my backlog and address your request in a future sprint.
