### ISSUE TITLE
Discrepancy between this page and another

### ISSUE THREAD

**Issue by RachelAmbler** [MicrosoftDocs/vsts-docs#428]
Acknowledged document feedback on [Add or modify a work item type](https://docs.microsoft.com/en-us/vsts/work/customize/add-modify-wit?view=vsts) would seem to indicate that this page is incorrect when it references **ValidUser** as being able to be used with System fields, such as **Created By** (`System.CreatedBy`).

Whilst the current text doesn't explicitly state you can use **ValidUser** with System controls like that, it does heavily infer it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 291b0681-307a-755f-fe95-3f3d04363653
* Version Independent ID: f12f653e-71aa-a45f-465f-faf1b4d39bd5
* Content: [Apply a field rule](https://docs.microsoft.com/en-us/vsts/work/customize/reference/apply-rule-work-item-field?toc=/vsts/work/customize/toc.json&bc=/vsts/work/customize/breadcrumb/toc.json&view=vsts)
* Content Source: [docs/work/customize/reference/apply-rule-work-item-field.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/work/customize/reference/apply-rule-work-item-field.md)
* Service: **unspecified**
* GitHub Login: @erickson-doug
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@RachelAmbler - Thank you for your correction. This content used to be valid for previous versions of TFS, but isn't valid for current versions. . I'm updating the topic and the updates should be live later today.
