### ISSUE TITLE
Marketplace extensions cannot be installed when DevOps Server is connected via Internet Proxy

### ISSUE THREAD

**Issue by micheleIT** [MicrosoftDocs/vsts-docs#4287]
When the DevOps Server has no direct connection the the internet, it's not possible to connect with the marketplace and install paid extensions. Variables HTTP_PROXY and HTTPS_PROXY are ignored.

**Comment by thomps23** [comment]
@micheleIT was this in reference to an info gap in a specific topic? If you could provide the topic we can triage.

**Comment by micheleIT** [comment]
@thomps23 no, sorry. I found some information about how to use the connected mode through a proxy server on stackoverflow, but can't find it in the current documentation.
Maybe you can document it in a new topic how this should be done to work properly?

**Comment by KathrynEE** [comment]
@micheleIT - Thank you for your inquiry. The instructions you required are documented under the TFS Server 2019 version selection: https://docs.microsoft.com/en-us/azure/devops/marketplace/get-tfs-extensions?view=tfs-2018#install-team-foundation-server-extensions-when-disconnected.
