### ISSUE TITLE
Technical details on PATs

### ISSUE THREAD

**Issue by lettucemode** [MicrosoftDocs/vsts-docs#4288]
Where can I find more technical details on how the PAT is generated? For example, is the length of the PAT always the same?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2bfea574-db69-a5fd-37fe-64ecfdac502a
* Version Independent ID: 4037d475-f194-2ac9-ffd6-70530fc3140a
* Content: [Authenticate with personal access tokens - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/use-personal-access-tokens-to-authenticate?view=azure-devops)
* Content Source: [docs/organizations/accounts/use-personal-access-tokens-to-authenticate.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/accounts/use-personal-access-tokens-to-authenticate.md)
* Product: **devops**
* Technology: **devops-accounts**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @lettucemode, you can find details here: https://docs.microsoft.com/en-us/azure/devops/organizations/security/credential-storage?view=azure-devops
Please let me know if you have any further questions! Thanks!

**Comment by lettucemode** [comment]
Thank you!
