### ISSUE TITLE
Typo in second paragraph

### ISSUE THREAD

**Issue by RachelAmbler** [MicrosoftDocs/vsts-docs#429]
Second paragraph currently reads:

>The `Control` element `AttachmentsControl``Type` attribute lets you enable users to see and manage the file attachments of a work item. By adding this control to a work item form, you can open, add, and remove file attachments. In the following example, a tab that is labeled "Attachments" is added to a work item form by using all the controls that are shown.

Should perhaps read:

> The `Control` element `AttachmentsControl` Type attribute lets you enable users to see and manage the file attachments of a work item. By adding this control to a work item form, you can open, add, and remove file attachments. In the following example, a tab that is labeled "Attachments" is added to a work item form by using all the controls that are shown.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f3c20e9-beb1-8f39-b189-fe9fde8b1114
* Version Independent ID: 60e7ea53-7c71-e345-fd94-c268df7955d1
* Content: [Add the Attachments control](https://docs.microsoft.com/en-us/vsts/work/customize/reference/add-the-attachments-control?toc=/vsts/work/customize/toc.json&bc=/vsts/work/customize/breadcrumb/toc.json&view=vsts)
* Content Source: [docs/work/customize/reference/add-the-attachments-control.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/work/customize/reference/add-the-attachments-control.md)
* Service: **unspecified**
* GitHub Login: @erickson-doug
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@RachelAmbler - Thank you for your comment. I'm updating the topic and the updates should be live later today.
