### ISSUE TITLE
Call out where to find the authorize all pipelines settings

### ISSUE THREAD

**Issue by ForrestTrepte** [MicrosoftDocs/vsts-docs#4292]
I had a difficult time finding this setting. You need to click project settings, agent pools, click your pool (e.g. Default), and then click the Security tab. Perhaps include a screenshot of the setting?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee4ec9d0-e0d5-4fb4-7c3e-b84abfa290c2
* Version Independent ID: 3e2b80d9-30e5-0c48-49f0-4fcdfedf5eee
* Content: [Resources - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/resources?view=azure-devops#troubleshooting-authorization-for-a-yaml-pipeline)
* Content Source: [docs/pipelines/process/resources.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/resources.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @vtbassmatt
* Microsoft Alias: **macoope**

**Comment by vtbassmatt** [comment]
We've started to avoid screenshots in the docs because they rapidly get out of date. Resource auth is also being heavily worked on right now, so I expect this to be easier going forward.
