### ISSUE TITLE
PackageForAndroid target?

### ISSUE THREAD

**Issue by Thorocaine** [MicrosoftDocs/vsts-docs#4293]
The documentation says:
&gt; Note: The projects must have a PackageForAndroid target.

However, nowhere does it tell me what on earth that means.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17217289-b764-14a7-e3d9-862d1d9cf503
* Version Independent ID: e1dd6942-3210-a148-b971-af869272c9a3
* Content: [Xamarin.Android build and release task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/xamarin-android?view=azure-devops#feedback)
* Content Source: [docs/pipelines/tasks/build/xamarin-android.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/build/xamarin-android.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @DavidStaheli
* Microsoft Alias: **dastahel**

**Comment by davidstaheli** [comment]
Thanks for pointing this out, @Thorocaine.  The documentation has been updated for this and will be live within a few days.

**Comment by kelsosharp** [comment]
This documentation STILL does not address the original question, What is PackageForAndroid, How is it defined, what are valid entries for the Target parameter, what is an example of how to use this? For people that are new to Xamarin development, this explains almost nothing, especially when they get a build error in Azure DevOps when it builds locally just fine.

**Comment by JonDouglas** [comment]
@kelsosharp The most up to date documentation on MSBuild properties can be found here https://docs.microsoft.com/en-us/xamarin/android/deploy-test/building-apps/build-process

or the source code:

https://github.com/xamarin/xamarin-android/blob/master/src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets

DevOps documentation is out of date as this isn't remotely related outside of Android Wear apps.

**Comment by bkstephen** [comment]
Any updates on this issue?
