### ISSUE TITLE
How to completely remove this branch history?

### ISSUE THREAD

**Issue by AlexChongMicrosoft** [MicrosoftDocs/vsts-docs#4295]
I don't want to restore this branch history because of security. How could I clean up the history?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b2f7bb6-eca8-ba34-0595-3bf2ec7c0e0f
* Version Independent ID: 28093f80-26b9-b9f8-0d5d-639c1da1f493
* Content: [Restore a deleted branch in your Git repo - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/restore-deleted-branch?view=azure-devops)
* Content Source: [docs/repos/git/restore-deleted-branch.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/repos/git/restore-deleted-branch.md)
* Product: **devops**
* Technology: **devops-code-git**
* GitHub Login: @kaylangan
* Microsoft Alias: **kangan**

**Comment by kaylangan** [comment]
You cannot permanently delete the history of a branch that has been pushed to a repository on Azure DevOps. We don't do garbage collection on the server so the branch/commits remain part of the repo and its history.
