### ISSUE TITLE
Automatic package versioning

### ISSUE THREAD

**Issue by heing** [MicrosoftDocs/vsts-docs#4296]
On this page, one of the suggested methods to version NuGet packages is this: $(Major).$(Minor).$(rev:.r)
One problem with this is that when the package is not built for 30 days (default retention period), the $(rev:.r) is reset and causes version numbering conflict when the package is published.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 11ed58a1-5819-f3a4-c674-dafcdbd56fbc
* Version Independent ID: d68aca4d-3fd3-1864-09f5-6060295e0399
* Content: [Publishing to NuGet feeds - Azure Pipelines and TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/nuget?view=azure-devops&tabs=yaml#feedback)
* Content Source: [docs/pipelines/artifacts/nuget.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/artifacts/nuget.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @thomps23
* Microsoft Alias: **amullans**

**Comment by CraigHead** [comment]
You can version your packages using the date time as part of the field. For example:
1.$(date:yyMM).$(date:dd).$(Rev:rr)

**Comment by heing** [comment]
> You can version your packages using the date time as part of the field. For example:
> 1.$(date:yyMM).$(date:dd).$(Rev:rr)

Thanks. I am aware of that, but that version format does not suit our needs, at least not for production releases. I have found a work-around using counters which seem to work well though.
See this post on StackOverflow: https://stackoverflow.com/a/56111209/1835620

**Comment by gojanpaolo** [comment]
We find GitVersion to work best with automated versioning.

**Comment by ramiMSFT** [comment]
@heing Thank you for your contribution. This seems to be a product issue and I just talked to one of the PMs and I will be filing a bug for this issue.
Thank you for reporting this.
