### ISSUE TITLE
Video issue

### ISSUE THREAD

**Issue by camilettomsft** [MicrosoftDocs/vsts-docs#4298]
Good day team. The video embedded code is wrong ([!Video https://channel9.msdn.com/Events/Connect/2017/T251/player]). Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c05a00ec-8714-dd48-26cc-53b95ef323b4
* Version Independent ID: 712ec787-c324-4acc-c824-031525de026b
* Content: [Create Power BI reports from Analytics service - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/report/powerbi/index?view=azure-devops#feedback)
* Content Source: [docs/report/powerbi/index.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/report/powerbi/index.md)
* Product: **devops**
* Technology: **devops-analytics**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@camilettomsft - Thank you for the correction. The article has been updated.
