### ISSUE TITLE
Spurious Unicode symbol in all examples (maybe a bad Tab conversion?)

### ISSUE THREAD

**Issue by RachelAmbler** [MicrosoftDocs/vsts-docs#430]
For example, the very last XML example is

```XML
<FIELD refname="MyCorp.StateDate" name="Date Of Last State Change" type="DateTime">  
<!-- Make the StateDate field read-only when the State field is not changed -->  
       <WHENNOTCHANGED field="MyCorp.State">  
        �<READONLY />  
       </WHENNOTCHANGED>  
</FIELD>
```

Should be

```XML
<FIELD refname="MyCorp.StateDate" name="Date Of Last State Change" type="DateTime">  
<!-- Make the StateDate field read-only when the State field is not changed -->  
       <WHENNOTCHANGED field="MyCorp.State">  
          <READONLY />  
       </WHENNOTCHANGED>  
</FIELD>
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d7deb2b6-ba37-c6f7-12bd-c428b61faf0a
* Version Independent ID: dd590fcc-16bc-6e24-e095-120d6eb36156
* Content: [Assign conditional-based values and rules](https://docs.microsoft.com/en-us/vsts/work/customize/reference/assign-conditional-based-values-and-rules?toc=/vsts/work/customize/toc.json&bc=/vsts/work/customize/breadcrumb/toc.json&view=vsts)
* Content Source: [docs/work/customize/reference/assign-conditional-based-values-and-rules.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/work/customize/reference/assign-conditional-based-values-and-rules.md)
* Service: **unspecified**
* GitHub Login: @erickson-doug
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@RachelAmbler - Thank you for your comment. I'm updating the topic and the updates should be live later today.
