### ISSUE TITLE
Where are pipeline settings?

### ISSUE THREAD

**Issue by fcooper8472** [MicrosoftDocs/vsts-docs#4301]
The information for scheduling builds says:

"Scheduled builds are not yet supported in YAML syntax. After you create your YAML build pipeline, you can use pipeline settings to specify a scheduled trigger."

Where are "pipeline settings" - how do you get there?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5673ec1-c7d1-e0ac-043a-8fc3d5b226a9
* Version Independent ID: b4872831-51c0-6cf8-1c56-de20beb38a80
* Content: [Build pipeline triggers - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/triggers?tabs=yaml&view=azure-devops#scheduled-triggers)
* Content Source: [docs/pipelines/build/triggers.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/build/triggers.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by lordjeb** [comment]
Took me some work to find this as well. Click Edit in the upper-right - takes you to your YAML editor. Then click the ellipses in the upper right, and go to settings, trigger, or variables.

**Comment by fcooper8472** [comment]
Thank you @lordjeb - that's really not obvious at all!

Even once there, I cannot see any options for `scheduled trigger`.  Under `triggers` I can `Override the YAML continuous integration trigger from here`, but nothing there about scheduling builds?

**Comment by lordjeb** [comment]
@fcooper8472 On the right I have "Override the YAML continuous integration trigger from here" and on the left I have "Continuous Integration", "Scheduled", and "Build Completion". Next to scheduled there is a "+Add" link.

**Comment by fcooper8472** [comment]
@lordjeb on the left I have "Continuous Integration", "Pull Request Validation", and "Build Completion" - no "Scheduled"..!

**Comment by fcooper8472** [comment]
(And, incidentally, the `+Add` button next to "Build Completion" is styled like a link but is no clickable...)

**Comment by lflake** [comment]
I'm having this exact problem - I don't even see an option to schedule triggers for building a pipeline. (and agree this was hard to find). What I see doesn't match the screenshot in the docs - no Scheduled option, and Build Completion Add + is greyed out. Save & Queue and Discard are also greyed out. 

I noticed my access level says "Basic" - is that the problem?

**Comment by steved0x** [comment]
We have just made some updates, I updated the screenshots for classic editor scheduled triggers (they weren't showing the latest version), and YAML scheduled triggers are now supported, and covered in this article under the [Scheduled Triggers](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/triggers?view=azure-devops&tabs=yaml#scheduled-triggers) section.
