### ISSUE TITLE
Delay when scrolling on the Backlog view page (Azure DevOps Server 2019)

### ISSUE THREAD

**Issue by jok26r** [MicrosoftDocs/vsts-docs#4302]
I faced a problem with the delaying of the display of backlog items on the Backlog View page when scrolling.
We have a project with about 200 backlog items, I think it's not too much. It looks like the problem relates to forced reflow or layout of the page every time I scroll. In my case, the layout process takes from 75% to almost 99% of the time of the whole display task, and the average time of display after the scrolling about 500ms.
Could you try to investigate this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 02ab6fbc-4df4-bc2d-da58-19dee9395256
* Version Independent ID: e613f4a0-37a5-c2fa-fdf5-345c945de6db
* Content: [How are Backlogs used to support portfolios, priority, and multi-team ownership - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/backlogs/backlogs-overview?view=azure-devops)
* Content Source: [docs/boards/backlogs/backlogs-overview.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/boards/backlogs/backlogs-overview.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by thomps23** [comment]
@jok26r Thanks for your question. It looks like you've encountered an issue with the product itself, rather than an issue with the documentation. To make sure it gets in front of the right people, please [submit your bug]( https://developercommunity.visualstudio.com/content/problem/post.html?space=21) here.
