### ISSUE TITLE
Please add documentation for the other arguments

### ISSUE THREAD

**Issue by samsmithnz** [MicrosoftDocs/vsts-docs#4304]
This page is under documented, but seems to be key for multi-stage pipelines. For example, how to use "downloadPath", and some examples of how to download an artifact from the build

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b03d67d0-8738-72e6-dbe7-324c1784d4fc
* Version Independent ID: bbb4d774-cd98-3ecb-7ccf-5f49e6f2b425
* Content: [Download Pipeline Artifact task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/download-pipeline-artifact?view=azure-devops)
* Content Source: [docs/pipelines/tasks/utility/download-pipeline-artifact.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/utility/download-pipeline-artifact.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @mitchdenny
* Microsoft Alias: **midenn**

**Comment by chasewilson** [comment]
@samsmithnz, Thank you for the feedback! We will be adding some updates soon to give some relevant, useful examples. In the mean time, the task has been updated to v2 and if you want to take a look and provide any more feedback, it's always appreciated :)

**Comment by chasewilson** [comment]
@samsmithnz Thanks again for the feedback. I've updated the page with examples and it should be pushed to live soon. If you have any more feedback on this or any of our docs pages, I hope you'll open a new issue! I'm closing this one.
