### ISSUE TITLE
How do I install and enable the "Artifacts service"?

### ISSUE THREAD

**Issue by clisc** [MicrosoftDocs/vsts-docs#4309]
The second sentence in this document says: "Users can use Package Search by default when Artifacts service is installed and enabled in Azure DevOps Services."  However, it doesn't have instructions or a link to instructions on how to do this.  How can I verify that the Artifacts service is installed an enabled for my organization?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4488541f-e00f-aa81-4731-9649800e2640
* Version Independent ID: 59b5b0cf-0d9f-c710-d9f5-e56a578f74f4
* Content: [advanced package search syntax](https://docs.microsoft.com/en-us/azure/devops/project/search/advanced-package-syntax?view=azure-devops#feedback)
* Content Source: [docs/project/search/advanced-package-syntax.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/project/search/advanced-package-syntax.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @KathrynEE
* Microsoft Alias: **sumallel**

**Comment by infin8x** [comment]
@KathrynEE Artifacts is now enabled for all organizations, we can remove that sentence.

**Comment by KathrynEE** [comment]
@clisc  - Thank you for your inquiry. We are updating the article to indicate that package search is available without installation.

**Comment by superfon** [comment]
> The second sentence in this document says: "Users can use Package Search by default when Artifacts service is installed and enabled in Azure DevOps Services." However, it doesn't have instructions or a link to instructions on how to do this. How can I verify that the Artifacts service is installed an enabled for my organization?
> 
> #### Document Details
>  _Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking._
> 
> * ID: 4488541f-e00f-aa81-4731-9649800e2640
> * Version Independent ID: 59b5b0cf-0d9f-c710-d9f5-e56a578f74f4
> * Content: [advanced package search syntax](https://docs.microsoft.com/en-us/azure/devops/project/search/advanced-package-syntax?view=azure-devops#feedback)
> * Content Source: [docs/project/search/advanced-package-syntax.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/project/search/advanced-package-syntax.md)
> * Product: **devops**
> * Technology: **devops-collab**
> * GitHub Login: @KathrynEE
> * Microsoft Alias: **sumallel**
