### ISSUE TITLE
Typo in "Define a default value" example

### ISSUE THREAD

**Issue by RachelAmbler** [MicrosoftDocs/vsts-docs#431]
```XML
<FIELD refname="MyCorp.Priority" name="Priority" type="String">  
<HELPTEXT>Specify the severity of the problem</HELPTEXT>  
       <ALLOWEDVALUES>  
        �<LISTITEM value="P1"/>  
        �<LISTITEM value="P2"/>  
        �<LISTITEM value="P3"/>  
       </ALLOWEDVALUES>  
<DEFAULT from="value" value="P3"/>  
</FIELD>
```

Should be:

```XML
<FIELD refname="MyCorp.Priority" name="Priority" type="String">  
<HELPTEXT>Specify the severity of the problem</HELPTEXT>  
       <ALLOWEDVALUES>  
          <LISTITEM value="P1"/>  
          <LISTITEM value="P2"/>  
          <LISTITEM value="P3"/>  
       </ALLOWEDVALUES>  
<DEFAULT from="value" value="P3"/>  
</FIELD>
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 26e4975c-b133-4fb0-a592-107327fd2768
* Version Independent ID: 4948ae48-c89d-0336-ce3b-73987cb14072
* Content: [Define default value or copy a value](https://docs.microsoft.com/en-us/vsts/work/customize/reference/define-default-copy-value-field?toc=/vsts/work/customize/toc.json&bc=/vsts/work/customize/breadcrumb/toc.json&view=vsts)
* Content Source: [docs/work/customize/reference/define-default-copy-value-field.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/work/customize/reference/define-default-copy-value-field.md)
* Service: **unspecified**
* GitHub Login: @erickson-doug
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@RachelAmbler - Thank you for your correction. I've updated the topic and the updates are now live.
