### ISSUE TITLE
Can't figure out how to pass an output variable to the next task as a property

### ISSUE THREAD

**Issue by clisc** [MicrosoftDocs/vsts-docs#4310]
I have a batch script task which is creating an ad-hoc output variable using:

@echo ##vso[task.setvariable variable=GitCommitId;isSecret=false;isOutput=true;]%commit%

I want to read GitCommitId variable in the next task, but that task is not a script but a GUI task.  So I need to pass it as a parameter.  I wish I could paste an image, but it seems its not letting me.  Anyways, it's through the GUI, not a script.  I've tried simply $(GitCommitId) but that fails because it passes the string literal "$(GitCommitId)" instead of the value of the variable GitCommitId.

How do I pass a variable into a task?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd7e0bd3-1f7d-d7b6-cc72-5ef63c31b46a
* Version Independent ID: dae87abd-b73d-9120-bcdb-6097d4b40f2a
* Content: [Variables - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=classic%2Cbatch)
* Content Source: [docs/pipelines/process/variables.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/variables.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by clisc** [comment]
Figured this out.  It looks like I had to declare a value for Output Variable/Reference Name in the script that was outputting the value then I had to reference the value as $(VersionBumpScript.GitCommitId).

This was *not* clear to me from the documentation on this page.  I got lucky via trial and error.  Please clarify that this is required in the documentation.  Thanks!

**Comment by clisc** [comment]
Thank you!

**Comment by rpresser** [comment]
@clisc : you wrote "had to declare a value for Output Variable/Reference Name in the script that was outputting the value"
Can you explain HOW? Or tell me where in the documentation it says how? All I can find is that on the page describing variables it says you have to set this in the "Output Variables section of the task editor". I have a self-hosted TFS 2018 and there is no such section.

**Comment by clisc** [comment]
> @clisc : you wrote "had to declare a value for Output Variable/Reference Name in the script that was outputting the value"
> Can you explain HOW? Or tell me where in the documentation it says how? All I can find is that on the page describing variables it says you have to set this in the "Output Variables section of the task editor". I have a self-hosted TFS 2018 and there is no such section.

I did this in Azure DevOps so I'm not sure if it applies to TFS 2018 on-prem or not.  But here's a screenshot:

![image](https://user-images.githubusercontent.com/23040875/58909948-54814680-86e2-11e9-89f0-aa9fbb61ed1d.png)

This section is at the bottom of the task when editing a build pipeline.  Hope this helps.

**Comment by rpresser** [comment]
Thanks for the screenshot, I think it confirms what I said -- there is no such section in TFS 2018 on-prem :) 
This is the entire task section for me:
![image](https://user-images.githubusercontent.com/1588623/58968442-12104600-8784-11e9-87e6-af643766c001.png)
![image](https://user-images.githubusercontent.com/1588623/58968472-19375400-8784-11e9-8880-fa500d809e2d.png)

**Comment by rpresser** [comment]
For what it's worth, it seems to be working for me now *without* a Reference name. The next step in my build def is using this expression as a custom condition now, and it seems to be working:

![image](https://user-images.githubusercontent.com/1588623/58968646-5f8cb300-8784-11e9-90b7-7956a1cea827.png)

**Comment by clisc** [comment]
I had not tried the custom condition before.  I was referencing it directly in other fields.

Glad you were able to get it working, though!  😊
