### ISSUE TITLE
Link to SonarQube integration article does not work.

### ISSUE THREAD

**Issue by waynethompson** [MicrosoftDocs/vsts-docs#4311]
clicked the link and got 403 forbidden

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 58aacca7-05a2-e8dd-6a6f-3025d734ef20
* Version Independent ID: 3eea19c1-8bda-6b60-e77d-8c0e82c3f096
* Content: [Define & manage bugs or code defects - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/backlogs/manage-bugs?view=azure-devops&tabs=new-web-form#feedback)
* Content Source: [docs/boards/backlogs/manage-bugs.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/boards/backlogs/manage-bugs.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by thomps23** [comment]
@kathrynee its a link to a blog post on our blog platform

**Comment by KathrynEE** [comment]
@waynethompson - THank you for the correction. I'm updating the link to the blog post now.
