### ISSUE TITLE
Test Case order in combination with configurations

### ISSUE THREAD

**Issue by JokeGijsbrechts** [MicrosoftDocs/vsts-docs#4315]
When ordering test cases with different configurations, the order of the test cases is not always correct. eg. the 10th test case is ordered before the 1st.

![Capture](https://user-images.githubusercontent.com/50956364/58259453-d6817f00-7d74-11e9-9a84-eae5296479df.PNG)

![Capture2](https://user-images.githubusercontent.com/50956364/58259523-0466c380-7d75-11e9-88d4-8fac3d8d4163.PNG)

**Comment by WilliamAntonRohm** [comment]
It looks like you've encountered an issue with the product itself, rather than an issue with the documentation. To make sure it gets in front of the right people, please [submit your bug]( https://developercommunity.visualstudio.com/content/problem/post.html?space=21) here.
