### ISSUE TITLE
Close and Start a New PowerShell Session Required After Register-PSRepository

### ISSUE THREAD

**Issue by rlvandaveer** [MicrosoftDocs/vsts-docs#4316]
I found that I had to close and start a new PowerShell session after the call to Register-PSRepository in the section Connecting to the feed as a PowerShell repo Step 2. Otherwise, I always got the following response when executing Find-Module: "WARNING: Unable to resolve package source 'https://pkgs.dev.azure.com/<REDACTED_ORG>/_packaging/<REDACTED_FEED>/nuget/v2'."

You could likely save some users time troubleshooting by adding a close and start step before Step 4.

&gt;$PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.1.0
PSEdition                      Core
GitCommitId                    6.1.0
OS                             Darwin 18.6.0 Darwin Kernel Version 18.6.0: Thu Apr 25 23:16:27 PDT 2019; root:xnu-4903.261.4~2/RELEASE_X86_64
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 35b3cd51-b365-433b-9149-697582d64e88
* Version Independent ID: 1cb1f4a3-5928-223d-592f-f3462fef4e4c
* Content: [Use Azure Artifacts as a private PowerShell repository](https://docs.microsoft.com/en-us/azure/devops/artifacts/tutorials/private-powershell-library?view=azure-devops)
* Content Source: [docs/artifacts/tutorials/private-powershell-library.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/artifacts/tutorials/private-powershell-library.md)
* Product: **devops**
* Technology: **devops-artifacts**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by chasewilson** [comment]
@thomps23, thank you for the feedback! I've created a user story in our backlog to address this issue. Please feel free to reach out with any more input!

**Comment by JasperCodes** [comment]
I can confirm that this resolved the same issue I had with registering a new repository.

**Comment by ramiMSFT** [comment]
@rlvandaveer Thank you for your feedback. I'm updating the content of this article and will include it in the new version.

@JasperCodes Thank you for the confirmation.
