### ISSUE TITLE
Unable to change current working directory

### ISSUE THREAD

**Issue by nawawn** [MicrosoftDocs/vsts-docs#4317]
Issue: This throws an error.
- task: AzurePowerShell@4
  inputs:
    azureSubscription:
    workingDirectory: "$(Build.SourcesDirectory)\Tests"

Workaround:
- task: AzurePowerShell@4
    inputs:
      azureSubscription: 
      ScriptType: 'InlineScript'
      Inline: |
        Set-Location "$(Build.SourcesDirectory)\Tests"
        Invoke-Pester -Script @{Path = '.\Az-Infrastructure.Tests.ps1'; Parameters = @{ConfigFile = '.\Config.psd1'}}

Are we expecting the 'workingDriectory' soon for the AzurePowerShell yaml?

**Comment by vtbassmatt** [comment]
This is a product request; feel free to file it on the [azure-pipelines-tasks](https://github.com/microsoft/azure-pipelines-tasks) repo.
