### ISSUE TITLE
Remove Windows File Extension

### ISSUE THREAD

**Issue by rlvandaveer** [MicrosoftDocs/vsts-docs#4318]
The article assumes a user is following the tutorial from Windows. In "Package and send the module" Step 2, three of the four nuget calls use the file extension exe. Removing those would make it more cross platform friendly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 35b3cd51-b365-433b-9149-697582d64e88
* Version Independent ID: 1cb1f4a3-5928-223d-592f-f3462fef4e4c
* Content: [Use Azure Artifacts as a private PowerShell repository](https://docs.microsoft.com/en-us/azure/devops/artifacts/tutorials/private-powershell-library?view=azure-devops)
* Content Source: [docs/artifacts/tutorials/private-powershell-library.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/artifacts/tutorials/private-powershell-library.md)
* Product: **devops**
* Technology: **devops-artifacts**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by chasewilson** [comment]
@thomps23, thank you for the feedback! I've created a user story in our backlog to address this issue. Please feel free to reach out with any more input!
