### ISSUE TITLE
Current sprint burndown widget only uses work not story points

### ISSUE THREAD

**Issue by bernardoflynn** [MicrosoftDocs/vsts-docs#4319]
How come this widget only does work and not story points like the other Burndown widget?
In the other widget I can choose all sorts of things to show as burndown but I have to manually select the current sprint each time we start a new sprint. 
For the current sprint burndown widget, it uses work as the burndown and doesn't allow me to choose story points. I hope most teams use story points to estimate and hence the burndown should either only use story points, or allow me to at least choose story points.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f040e253-b5a0-7bf6-32d1-d845df44887d
* Version Independent ID: a487ad96-3d1e-cc14-26e0-a7169ff0319e
* Content: [Sprint burndown - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/sprints/sprint-burndown?view=azure-devops#feedback)
* Content Source: [docs/boards/sprints/sprint-burndown.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/boards/sprints/sprint-burndown.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@bernardoflynn - Thank you for your inquiry. The sprint chart and widget is based on the work tracking data and not the Analytics service. It predates many of the new features that have been added. Therefore, it  only supports Remaining Work defined for tasks. For more choices in seeing sprint burndown, see this article: [Configure a Burndown or Burnup widget](https://docs.microsoft.com/en-us/azure/devops/report/dashboards/configure-burndown-burnup-widgets?view=azure-devops).

**Comment by bernardoflynn** [comment]
Hi KathrynEE
Thanks for responding. But this is the default burndown widget that is displayed in DevOps, so its not really cool to just answer that it predates the analytics service and close the issue :) 
This widget is useless for any team that is actually using agile practices, i.e. not using the out of date concept of using time estimates.
