### ISSUE TITLE
More typo's in examples

### ISSUE THREAD

**Issue by RachelAmbler** [MicrosoftDocs/vsts-docs#432]
e.g.

```XML
<gl:GLOBALLISTS xmlns:gl="http://schemas.microsoft.com/VisualStudio/2008/workitemtracking/globallists">  
       <GLOBALLIST name="NameOfGlobalList">  
        �<LISTITEM value="ListItem1" />  
        �<LISTITEM value="ListItem2" />  
        �<LISTITEM value="ListItem3" />  
        �<LISTITEM value="ListItem4" />  
        �. . .  
        �<LISTITEM value="ListItemN" />  
       </GLOBALLIST>  
</gl:GLOBALLISTS>
```

Should be:

```XML
<gl:GLOBALLISTS xmlns:gl="http://schemas.microsoft.com/VisualStudio/2008/workitemtracking/globallists">  
       <GLOBALLIST name="NameOfGlobalList">  
          <LISTITEM value="ListItem1" />  
          <LISTITEM value="ListItem2" />  
          <LISTITEM value="ListItem3" />  
          <LISTITEM value="ListItem4" />  
          . . .  
          <LISTITEM value="ListItemN" />  
       </GLOBALLIST>  
</gl:GLOBALLISTS>
```

Multiple examples of this found on this page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 95a10d39-9182-bfc8-044e-5990e2b6085e
* Version Independent ID: 5faef7b9-c69f-c3df-7ca0-6dca66f019ac
* Content: [Define global lists](https://docs.microsoft.com/en-us/vsts/work/customize/reference/define-global-lists?toc=/vsts/work/customize/toc.json&bc=/vsts/work/customize/breadcrumb/toc.json&view=vsts)
* Content Source: [docs/work/customize/reference/define-global-lists.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/work/customize/reference/define-global-lists.md)
* Service: **unspecified**
* GitHub Login: @kaelli
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@RachelAmbler - Thank you for your corrections. I've updated the topic and the updates are now live.
