### ISSUE TITLE
Downloads v's Installs

### ISSUE THREAD

**Issue by VisualMicro** [MicrosoftDocs/vsts-docs#4320]
It is difficult to understand why there are many more downloads than installs. The two should really go hand in hand unless there are installer issues. How can we report on this and understand the reasons? Can we also more clearly show which IDE was used for download when downloading from within the IDE?

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 902e2181-c7cf-b144-367e-2e0091c2b6f3
* Version Independent ID: bed48ac7-63c7-5942-d59a-542fdd11343c
* Content: [Extension Report](https://docs.microsoft.com/en-us/azure/devops/marketplace/extension-report?view=azure-devops#feedback)
* Content Source: [docs/marketplace/extension-report.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/marketplace/extension-report.md)
* Product: **devops**
* Technology: **devops-marketplace**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by chcomley** [comment]
Hi @VisualMicro, I'm looking into this and will get back to you as soon as possible. Thanks for reaching out!

**Comment by VisualMicro** [comment]
Thanks, looking at other extensions it seems to be a common theme. I wonder if vs is auto downloading extensions and then users never see the prompt to install after the IDE closes.

The 2017 installer changed to install after the IDE is closes, if I made any request it would be to undo the installer change that runs after close. It's the most unnatural strange workflow for users I have ever seen 🙂

Other than that keep up the great work.


Thanks


Tim Leek

Visual Micro Limited

web: https://www.visualmicro.com


________________________________

**Comment by harishkragarwal** [comment]
@VisualMicro: 
installs is the # of unique installations, not including updates. 
downloads is the # installs, including updates. 

Hence you see the remarkable diff between them. Over time we will remove the download count and just keep the install count.
