### ISSUE TITLE
New timeline for NetStandard 2.0 version of the Azure DevOps OM?

### ISSUE THREAD

**Issue by MarkIannucci** [MicrosoftDocs/vsts-docs#4323]
Microsoft says: 

`We updated our dependencies in our latest code branch` ... `These packages will be should be available sometime in March 2019.`  May 2019 is almost over, and the packages are still listed on NuGet in preview.  Does Microsoft have a new timeline for the NetStandard 2.0 compatible packages being out of preview?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 413163f0-28c3-a2a7-d626-fcb81bcb2257
* Version Independent ID: 57c127da-2b1e-d29e-9abb-a3c258762ccf
* Content: [.NET Client Libraries for Azure DevOps Services (and TFS)](https://docs.microsoft.com/en-us/azure/devops/integrate/concepts/dotnet-client-libraries?view=azure-devops)
* Content Source: [docs/integrate/concepts/dotnet-client-libraries.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/integrate/concepts/dotnet-client-libraries.md)
* Product: **devops**
* Technology: **devops-ecosystem**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by tedchamb** [comment]
We just published version 16.143.1, which is a released package that includes the NetStandard 2.0 binaries.  These packages correlate to Azure DevOps Server 2019 RTW, and are fully compatible with the service.

**Comment by deven** [comment]
Is the 16.143.1 version backwards-compatible with older TFS servers such as TFS 2017?
