### ISSUE TITLE
Link "Rename and delete feed" is broken

### ISSUE THREAD

**Issue by lg2de** [MicrosoftDocs/vsts-docs#4325]
Under section "Feed permissions overview" the link to "Rename and delete feed" is broken.

It is configured to
https://docs.microsoft.com/en-us/azure/devops/artifacts/feeds/edit-feed?view=azure-devops
and it get the page
https://docs.microsoft.com/de-de/azure/devops/artifacts/?view=azure-devops

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e77774e-012a-45cc-d566-7170d86003cd
* Version Independent ID: 778dafea-bf98-3292-f451-d82ce8db5bbc
* Content: [Secure and share packages using feed permissions](https://docs.microsoft.com/en-us/azure/devops/artifacts/feeds/feed-permissions?view=azure-devops#feedback)
* Content Source: [docs/artifacts/feeds/feed-permissions.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/artifacts/feeds/feed-permissions.md)
* Product: **devops**
* Technology: **devops-artifacts**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by batkoski** [comment]
Thanks @lg2de , @chasewilson we can probably just remove that link altogether, I believe we got rid of that article because it wasn't getting hits and wasn't very helpful.

**Comment by elbatk** [comment]
Responding from the right GitHub account :)

Thanks @lg2de , @chasewilson we can probably just remove that link altogether, I believe we got rid of that article because it wasn't getting hits and wasn't very helpful.
