### ISSUE TITLE
Can artifacts be published to private share folder via "Publish Pipeline Artifact"

### ISSUE THREAD

**Issue by stefanjarina** [MicrosoftDocs/vsts-docs#4326]
Can artifacts be published to private share folder via "Publish Pipeline Artifact" in case that build/artifact/release process needs to be in-house for whatever reason?
We are able to do this via "Publish Build Artifacts".
Cheers.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 861ce7a5-4fa4-55f1-2c97-46a9cc6a2f66
* Version Independent ID: bdf954b9-9bbe-8b34-b674-71ad8153519d
* Content: [Publish and consume Pipeline artifacts in builds - Azure Pipelines and TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/pipeline-artifacts?view=azure-devops&tabs=yaml#feedback)
* Content Source: [docs/pipelines/artifacts/pipeline-artifacts.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/artifacts/pipeline-artifacts.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @alexmullans
* Microsoft Alias: **amullans**

**Comment by willsmythe** [comment]
Not yet, but it's coming (under development now).

@chasewilson - this might be worth adding in the FAQ. The answer will change in a few weeks, but worth mentioning for now. The net-net: "Q: Can this task publish artifacts to a shared folder or network path? A: Not currently, but this feature is planned."

**Comment by stefanjarina** [comment]
Nice, thanks a lot for answer. Will this work also from linux machine? We have both windows and linux pipeline and we need a way to publish artifacts to mounted network drive on both systems. And so far couldn’t find satisfying solution for that particular case. Cheers
