### ISSUE TITLE
The space usage limit for published artifacts is not mentioned anywhere.

### ISSUE THREAD

**Issue by vijay-gowda** [MicrosoftDocs/vsts-docs#4328]
My publish build task generates artifacts of size upto 300MB and is stored against the build itself on Azure DevOps. I am not sure if there is a space limit. I know from the billing page by default for free access it is 2 GB for Azure Artifacts. However, even after I have generated so many artifacts of big size, my space usage against Azure Artifacts shows zero. Does that mean the build artifacts published as part of the Publish task in my build has unlimited space?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7175ebdc-0bba-7e00-d113-036a5cffe5fa
* Version Independent ID: 149ab9f4-0b7d-97e7-6cf5-1b54fd04c63c
* Content: [Publish and consume build artifacts in builds - Azure Pipelines and TFS](https://docs.microsoft.com/en-gb/azure/devops/pipelines/artifacts/build-artifacts?view=azure-devops&tabs=classic#feedback)
* Content Source: [docs/pipelines/artifacts/build-artifacts.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/artifacts/build-artifacts.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by cg3y** [comment]
Actually, it is mentioned, although it's not easy to find. See this URL: 

https://docs.microsoft.com/en-us/azure/devops/artifacts/sign-up-azure-artifacts?toc=%2Fazure%2Fdevops%2Forganizations%2Ftoc.json&bc=%2Fazure%2Fdevops%2Forganizations%2Fbreadcrumb%2Ftoc.json&view=azure-devops#faqs

Here they state:

"Pipeline Artifacts, Build Artifacts, and Pipeline Caching are included in Azure Pipelines and do not count towards your storage total in Azure Artifacts as of today."

**Comment by chasewilson** [comment]
@cg3y, thank you for the answer here! @vijay-gowda, does this answer your question?

**Comment by vijay-gowda** [comment]
Thanks
