### ISSUE TITLE
Script de pull request

### ISSUE THREAD

**Issue by kviatcovskii** [MicrosoftDocs/vsts-docs#4329]
Bom dia
Gostaria  de um script em powershell para a requisição de uma pull request? 

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: 028e7b61-62e4-a10e-e420-3535f7843f0e
* Version Independent ID: 1a6fdbe7-5ba4-a7f8-1b2e-271289a7b9fd
* Content: [Review and merge code with pull requests - Azure Repos](https://docs.microsoft.com/pt-br/azure/devops/repos/git/pull-requests?view=azure-devops&viewFallbackFrom=vsts#feedback)
* Content Source: [docs/repos/git/pull-requests.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/repos/git/pull-requests.md)
* Product: **devops**
* Technology: **devops-code-git**
* GitHub Login: @apawast
* Microsoft Alias: **sdanie**

**Comment by thomps23** [comment]
@apawast Looks like a request for a powershell script for pull requests in this topic.

**Comment by steved0x** [comment]
@kviatcovskii Thank you for your feedback, are you requesting a powershell script for pull requests or offering to provide one? Thank you.
