### ISSUE TITLE
Please correct error/warning logging docs per the github page

### ISSUE THREAD

**Issue by randyram-at-ms** [MicrosoftDocs/vsts-docs#4332]
This page needs to be rectified with https://github.com/microsoft/azure-pipelines-tasks/blob/master/docs/authoring/commands.md

The instructions for logging and error/message on this page didn't work for me.  The github method worked.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a0e444c2-69c6-4d71-6fd0-94d0f4097d3a
* Version Independent ID: 3a727833-1cc3-c2fb-c5b3-22605eee2721
* Content: [PowerShell task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/powershell?view=azure-devops#feedback)
* Content Source: [docs/pipelines/tasks/utility/powershell.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/utility/powershell.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @vtbassmatt
* Microsoft Alias: **macoope**

**Comment by vtbassmatt** [comment]
You're right, that's a hot mess right now.
