### ISSUE TITLE
What permission allows modifying GitHub repositories for Azure Boards?

### ISSUE THREAD

**Issue by elhutchi** [MicrosoftDocs/vsts-docs#4336]
When setting up the Azure Boards app integration with GitHub, not all Contributors can add their repository to the GitHub connection. Is there an Azure DevOps permission that allows editing the list of linked GitHub repositories? The documentation doesn't explain the prerequisite for editing this list.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e0f91070-b95b-fbb7-a6f2-bf11f6ceff43
* Version Independent ID: fe6f39f4-d718-522e-129a-de5c09b5c021
* Content: [Install and configure the Azure Boards app for GitHub - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/github/install-github-app?view=azure-devops#add-or-remove-repositories-from-azure-boards)
* Content Source: [docs/boards/github/install-github-app.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/boards/github/install-github-app.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@elhutchi - Thank you for your inquiry. The permissions to edit the list are the same as those listed under Prerequisites.

**Comment by elhutchi** [comment]
@KathrynEE actually that section only explains what access within GitHub you need to have. I'm wondering about what access in Azure DevOps you need to have to [add or remove repositories from Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/github/install-github-app?view=azure-devops#add-or-remove-repositories-from-azure-boards)

**Comment by elhutchi** [comment]
To be more specific, most users can't see the ellipsis to edit the GitHub connection. Even if they are added as Admins on GitHub repositories.

![image](https://user-images.githubusercontent.com/11701985/58357485-a0a9cc80-7e40-11e9-8dff-c3da67cd8c9e.png)
