### ISSUE TITLE
this build doesnt work for anniversary update and above

### ISSUE THREAD

**Issue by touseefbsb** [MicrosoftDocs/vsts-docs#434]
if the uwp app minimum target is anniversary update or above then this default agent for uwp build in VSTS doesnt work, the build fails.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b846f94-2bb5-d5a8-63c8-8227ab1b613b
* Version Independent ID: 5ba1aaac-6076-c5e0-fec0-c2ac2405b138
* Content: [Build your Universal Windows Platform app](https://docs.microsoft.com/en-us/vsts/build-release/apps/windows/universal?view=vsts&tabs=vsts)
* Content Source: [docs/build-release/apps/windows/universal.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/build-release/apps/windows/universal.md)
* Service: **unspecified**
* GitHub Login: @erickson-doug
* Microsoft Alias: **alewis**

**Comment by andyjlewis** [comment]
I'm sorry for the delayed response. We're planning some major updates to topics like this one. I've added this concern to the story on our backlog.
