### ISSUE TITLE
Public GitHub repository time limits

### ISSUE THREAD

**Issue by rajsite** [MicrosoftDocs/vsts-docs#4342]
Using an open source GitHub project with Azure DevOps I'm getting timeouts with Microsoft Build Agents that say: 
```
The job running on agent Hosted Agent has exceeded the maximum execution time of 60. For more information, see https://go.microsoft.com/fwlink/?linkid=2077134 
```

The [timeouts documentation](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/phases?view=azure-devops&tabs=yaml#timeouts) is not specific as to how public GitHub projects / repositories are treated for build agent timeouts. I'd hope that open source GitHub projects using Azure DevOps Pipelines with Microsoft-Hosted Agents would get the 360 timeout.

Edit: Actually it is documented that a public github repository with Azure Pipelines in a public project should qualify for the free tier on a [separate page](https://docs.microsoft.com/en-us/azure/devops/pipelines/licensing/concurrent-jobs?view=azure-devops#how-do-i-qualify-for-the-free-tier-of-public-projects). Do you know why a project in that configuration would hit the 60 minute agent limit? [Example build](https://dev.azure.com/milandro/webvi-experiments/_build/results?buildId=38).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 67504b34-d64b-02a4-2e10-ab99f3b8cfe4
* Version Independent ID: 2cf63b2e-184b-7726-3b8a-d8baffd6fcce
* Content: [Jobs in Azure Pipelines, Azure DevOps Sever, and TFS - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/phases?view=azure-devops&tabs=yaml#timeouts)
* Content Source: [docs/pipelines/process/phases.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/phases.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @vijayma
* Microsoft Alias: **vijayma**

**Comment by rajsite** [comment]
I went back and read the docs more closely, I apparently need to set the timeout to zero in order to utilize the full timeout. I'll give that a try in a future build.

**Comment by khs1994** [comment]
set to 0,also run 60 min,why?
