### ISSUE TITLE
Azure DevOps Developer Community

### ISSUE THREAD

**Issue by knbz** [MicrosoftDocs/vsts-docs#4344]
Thank you for your feedback!

The issues in this repo are for documentation feedback.

If you are submitting your documentation feedback issue directly through GitHub, please provide the URL of the article so we can route the feedback to the correct author.

Please report Azure DevOps or TFS software bugs, feedback, or questions in the [Azure DevOps Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html).

**Comment by thomps23** [comment]
@knbz Hello! It looks like the tool didnt capture your feedback. If you could try posting your feedback as a comment here with the URL to the topic is relates to we can triage on our end.
