### ISSUE TITLE
These instructions are so complex they're useless - and I've installed and been using TFS 2017 for a long time.

### ISSUE THREAD

**Issue by LJ9999** [MicrosoftDocs/vsts-docs#4345]
Also, the reference: "http://{Server}/tfs/_gallery)" is wrong. There is no such address on my server when installing TFS 2018 on the same server as TFS 2017.

But no worries. I'll figure it all out. 'Like I've done with Microsoft docs over the last 30 years.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be0bdbf7-3132-9007-6c6a-368c5bcb0f3d
* Version Independent ID: 58118f61-f88f-24b9-b785-d8f9d8a1fefd
* Content: [Administer code, wiki and workitem search](https://docs.microsoft.com/en-us/azure/devops/project/search/administration?view=tfs-2018#install-tfs)
* Content Source: [docs/project/search/administration.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/project/search/administration.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by chcomley** [comment]
Hi @LJ9999, Thanks for your feedback! I've created a user story to address this and update the article. I'll let you know when the changes are published, however do let us know if you need help in the meantime. Thanks for being a customer for 30 years!

**Comment by chcomley** [comment]
Adding @sandeepchadda, Do we need to replace this reference: _http://{Server}/tfs/_gallery)_? Please advise and thanks very much!

**Comment by chcomley** [comment]
Hi @LJ9999, I'm working on an update now and I'll let you know once it's been published. Thank you.

**Comment by chcomley** [comment]
@LJ9999 I've refreshed the article and updated the mentioned URL within the text. I hope it's an improvement to your liking. Thanks again for your feedback.
