### ISSUE TITLE
Difference between Azure App Service Deployment and Azure Web App Deployment is not clear

### ISSUE THREAD

**Issue by hansmbakker** [MicrosoftDocs/vsts-docs#4348]
There are two tasks that seem to do the same.
- [Azure App Service Deployment](https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/AzureRmWebAppDeploymentV4)
- [Azure Web App Deployment](https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/AzureWebAppV1)

What are the differences and what task should we use?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a40a853-83d6-844a-4752-8b00909c9ffb
* Version Independent ID: e3121964-de38-2a57-2414-c1e29a880477
* Content: [Deploy an Azure Web App - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/targets/webapp?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/targets/webapp.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/targets/webapp.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by RoopeshNair** [comment]
Azure App Service Task is superset task that does many things viz. deploy to web app, function app container app etc. We split them into more manageable purpose built tasks with Azure Web App, Azure Function App etc. The earlier task is kept around for backward compatibility.
