### ISSUE TITLE
Small typo - R1 should be R2 in the next to last paragraph

### ISSUE THREAD

**Issue by sergeimgithub** [MicrosoftDocs/vsts-docs#4349]
The "Next, a request for post-deployment approval is sent out for release R1." seems should be "Next, a request for post-deployment approval is sent out for release R2."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4266f72c-c774-0046-4593-d01eb775d3c3
* Version Independent ID: f20827aa-a6c5-96a8-5969-e576ffbc2e38
* Content: [Stages in Azure Pipelines - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/stages?view=azure-devops&tabs=classic#feedback)
* Content Source: [docs/pipelines/process/stages.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/stages.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @vijayma
* Microsoft Alias: **vijayma**

**Comment by vijayma** [comment]
It is correct as stated in the doc. The **post-deployment approval** for R1's QA stage is sent out as soon as the steps in R1's QA stage are finished. Once R1 exits QA stage, R2's pre-deployment approval is sent out.
