### ISSUE TITLE
Upgrading pip gives an error

### ISSUE THREAD

**Issue by akshaybabloo** [MicrosoftDocs/vsts-docs#4355]
The line which upgrades `pip`

```
python -m pip install --upgrade pip setuptools wheel
```

Gives an error as 

```
Collecting pip
  Downloading https://files.pythonhosted.org/packages/5c/e0/be401c003291b56efc55aeba6a80ab790d3d4cece2778288d65323009420/pip-19.1.1-py2.py3-none-any.whl (1.4MB)
Installing collected packages: pip
Successfully installed pip-8.1.1
You are using pip version 8.1.1, however version 19.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Traceback (most recent call last):
  File "/usr/bin/pip", line 9, in <module>
    from pip import main
ImportError: cannot import name main
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2ca42420-9324-1988-16bd-501be69e278d
* Version Independent ID: 400c0122-a0cc-bb52-b6cc-8aa93ff2c47a
* Content: [Build and test Python apps - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/languages/python?view=azure-devops)
* Content Source: [docs/pipelines/languages/python.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/languages/python.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @thomps23
* Microsoft Alias: **dastahel**

**Comment by davidstaheli** [comment]
@brcrista do you know what might cause this, or whether it's been fixed?

**Comment by brcrista** [comment]
This looks like an issue with "system Python" (the version of Python that ships with the operating system as opposed to a version we install).

@akshaybabloo, which image are you running on?  Also, which version of Python is in PATH here?

**Comment by akshaybabloo** [comment]
I'm running it on Ubuntu 16.04

**Comment by brcrista** [comment]
Sounds like the issue is that you're using system Python.  Run this script and you'll see the issue:

```yml
- script: |
    which python
    python --version
    which pip
    pip --version
  displayName: Check Python and pip versions
```

The installation is failing because these live in `/usr` and you need to `sudo`.

But the best practice is to run Use Python Version as described [earlier in the guide](https://docs.microsoft.com/azure/devops/pipelines/languages/python#build-environment).  The current step assumes you've done that.

**Comment by akshaybabloo** [comment]
Yes, I'm sticking to python versions for now. Thanks for your help. Closing this issue
