### ISSUE TITLE
Build pipeline repository access issue - Documentation is wrong

### ISSUE THREAD

**Issue by clement-fleury-assoconnect** [MicrosoftDocs/vsts-docs#4357]
The documentation says :
&gt; If the repository that you wish to build is in the same project as your pipeline, you're all set. Your builds will automatically have access to the repository.

And to be able to clone a repository in my project I had to use `git clone -c http.extraheader="AUTHORIZATION: bearer $(System.AccessToken)" ...`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8b846aea-82f7-a988-67d8-1b5e74b61ed2
* Version Independent ID: 2d632729-bb33-c0a0-c996-e1d8e86c2e23
* Content: [Build Azure Repos Git repositories - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/azure-repos-git?view=azure-devops#feedback)
* Content Source: [docs/pipelines/repos/azure-repos-git.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/repos/azure-repos-git.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by cg3y** [comment]
I've been trying to figure this out for a couple of days...your comment is extremely helpful!! Thank you! I wish the documentation was accurate and included this information.

**Comment by Decker-Russell** [comment]
+1 just wasted 2 hours trying to find some setting in DevOps to grant pipelines access to other repos. @MS pleasssssseeeee update your docs so other people don't waste time
