### ISSUE TITLE
Additional basic user pricing

### ISSUE THREAD

**Issue by elliotpryde** [MicrosoftDocs/vsts-docs#4359]
https://docs.microsoft.com/en-us/azure/devops/organizations/billing/buy-basic-access-add-users?view=azure-devops

Nowhere is the pricing mentioned for adhoc additional basic users.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 608a8c53-51a9-0878-da16-bfb7f977e01b
* Version Independent ID: 52155a9a-b7bf-607c-a90d-547395f059d6
* Content: [Buy Basic access for users in Azure DevOps - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/billing/buy-basic-access-add-users?view=azure-devops)
* Content Source: [docs/organizations/billing/buy-basic-access-add-users.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/billing/buy-basic-access-add-users.md)
* Product: **devops**
* Technology: **devops-billing**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @elliotpryde, thanks for your feedback. I've added a link to the Azure DevOps pricing calculator to a bunch of our billing articles. These updates should be live by sometime today. Until then, please go here for the pricing calculator: https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fazure.microsoft.com%2Fen-us%2Fpricing%2Fcalculator%2F%3Fservice%3Dazure-devops&data=02%7C01%7CChrystal.Comley%40microsoft.com%7C840f7ea3e67b42dedcdb08d6e3967619%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636946632692060474&sdata=hKIC0CA6xqo%2BlwlQSHwPxQlo71oslBTjGo9DJBXR%2BT4%3D&reserved=0

**Comment by lukeschlather** [comment]
Can you just include the cost directly?

**Comment by chcomley** [comment]
Hi @lukeschlather, 

We can't include the cost directly because if that cost changes, our article would be out of sync and incorrect. I've just published an update, however, that leads you to the [Azure DevOps pricing page](https://azure.microsoft.com/en-us/pricing/details/devops/azure-devops-services/), rather than the calculator. Thanks!
