### ISSUE TITLE
Several Items Missing Here

### ISSUE THREAD

**Issue by JustinGrote** [MicrosoftDocs/vsts-docs#4360]
For instance, the Azure Function App Deploy task is not listed on this "index" page

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e7ba5cf3-d229-03d0-ad6a-a30a0379afc0
* Version Independent ID: ccffed3b-ea44-517f-f7a8-a1c4c4147495
* Content: [Catalog of the built-in tasks for build-release and Azure Pipelines & TFS - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/index?view=azure-devops)
* Content Source: [docs/pipelines/tasks/index.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/index.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by steved0x** [comment]
@JustinGrote Sorry that you ran into trouble, you are correct, this page is still a work in progress and there are several different groups creating new tasks and this top level page sometimes doesn't get updated. It will be retired soon with a different (TBD) mechanism for enumerating all of the available tasks.
