### ISSUE TITLE
Unclear docs

### ISSUE THREAD

**Issue by andre-ss6** [MicrosoftDocs/vsts-docs#4361]
"Set a home page" gives an example on how to set a home page, but doesn't explain what in the example is the thing that sets up the homepage. I'm guessing "New Home Page" makes the page referenced in the line below it to be the homepage? Even if that's the case, I think it should be clearer.

Then, the next section does the opposite: it tries to explain the folder structure needed to promote a folder to a page, but provided no examples.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8d4fe5c7-0ab6-a0e4-4a6e-f98d0355f49a
* Version Independent ID: ce022fef-054d-cdc2-43e9-a8ee3b8fb592
* Content: [Publish Markdown files from a Git repository to a wiki in Azure DevOps - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/project/wiki/publish-repo-to-wiki?view=azure-devops)
* Content Source: [docs/project/wiki/publish-repo-to-wiki.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/project/wiki/publish-repo-to-wiki.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @andre-ss6, You're right, we're missing some information. Thanks for your feedback. I've created a user story to address this and will be back in touch soon.
