### ISSUE TITLE
pr element only supported for GitHub repos?

### ISSUE THREAD

**Issue by lukeschlather** [MicrosoftDocs/vsts-docs#4363]
This developer community post appears to say that Azure-hosted git repos don't support the pr: block:

https://developercommunity.visualstudio.com/content/problem/402133/yaml-definition-does-not-work-with-pull-requests.html

Seems like a bug if the case, at the least it should throw an error. Ideally it would just work?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7458d5b2-1bb7-7d87-7ce6-2b0c430b0155
* Version Independent ID: edf5bbd3-a3f0-5426-e985-31290f8afd05
* Content: [YAML schema - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema#feedback)
* Content Source: [docs/pipelines/yaml-schema.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/yaml-schema.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @vtbassmatt
* Microsoft Alias: **macoope**

**Comment by lukeschlather** [comment]
I feel like there's a higher-level problem here with the way includes/excludes are applied. For most purposes, the path-based include/excludes are identical and I don't want to have to include them in 2 different places. If I want to include/exclude a file, I have to put it in the trigger and then manually also add it to the build policy via the UI. which is really hard to keep track of. Ideally there would just be one set of path include/excludes consumed both by both pr and master builds.

**Comment by vtbassmatt** [comment]
The initial issue is documented in the section on [triggers](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema#pr-trigger) in a blue info box.

The later comment is product feedback that, while welcomed, isn't a doc issue. Feel free to file a suggestion on Developer Community with that. Thanks!
