### ISSUE TITLE
What about exclude?

### ISSUE THREAD

**Issue by liranms** [MicrosoftDocs/vsts-docs#4365]
Sometimes you want to archive a directory but exclude files/directories - for example the ".git" directory, how about adding that option?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: add63018-4f2c-f258-76ea-9f76aa43ff09
* Version Independent ID: c71f17c9-9a78-396e-7a0f-ad8b52b01724
* Content: [Archive Files task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/archive-files?view=azure-devops)
* Content Source: [docs/pipelines/tasks/utility/archive-files.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/utility/archive-files.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @vtbassmatt
* Microsoft Alias: **macoope**

**Comment by vtbassmatt** [comment]
The design for that task is that you stage the files you want to compress into a directory, then compress it. You can use the CopyFiles task, or simply shell commands.
