### ISSUE TITLE
Missing libraries

### ISSUE THREAD

**Issue by x-jokay** [MicrosoftDocs/vsts-docs#4366]
There seems to be missing some libraries to get the agent using docker to work, see https://github.com/bbtsoftware/docker-azure-devops-agent/issues/6.

**Comment by thomps23** [comment]
@x-jokay is this related to a specific example in the content? Or is this product feedback?

**Comment by thomps23** [comment]
@x-jokay I see you filed a pull request related to this feedback- thank you.
