### ISSUE TITLE
What about Azure DevOps Server 2019 and api-version 5.0/1?

### ISSUE THREAD

**Issue by shayki5** [MicrosoftDocs/vsts-docs#4368]
There are missing details about Azure DevOps Server 2019 and Rest API version 5.0.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 84af2b0f-cd64-018f-585f-70d17f393f85
* Version Independent ID: 8b25aa9b-95b8-14d3-0348-8d8ffd6d2843
* Content: [REST API versioning for Azure DevOps Services (and TFS)](https://docs.microsoft.com/en-us/azure/devops/integrate/concepts/rest-api-versioning?view=azure-devops#feedback)
* Content Source: [docs/integrate/concepts/rest-api-versioning.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/integrate/concepts/rest-api-versioning.md)
* Product: **devops**
* Technology: **devops-ecosystem**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by chcomley** [comment]
Hi @shayki5, Thanks for your feedback. I've created a user story on my backlog to address this. Until then, did you have any questions? Thanks again!

**Comment by shayki5** [comment]
Hi @chcomley thanks for your response!
Which version Azure DevOps Server 2019 supports?

**Comment by chcomley** [comment]
Hi @shayki5, You can find that here: https://docs.microsoft.com/en-us/rest/api/azure/devops/?view=azure-devops-rest-5.0#api-and-tfs-version-mapping 
I've updated the doc accordingly, however it won't go live until sometime later this afternoon. Thanks!

**Comment by shayki5** [comment]
Thank you @chcomley!
What is Azure DevOps Server vNext?

**Comment by chcomley** [comment]
Hey @shayki5, vNext is whatever is going to be the next version of Azure DevOps Server. Current version is 2019. Thanks!

**Comment by shayki5** [comment]
Thanks @chcomley ! So the next versions not will be "years" versions? but only "vNext"? when it will be released? thank you!

**Comment by chcomley** [comment]
@shayki5, I'm sorry, I wasn't clear! The next version will likely be 2020 or 2021...still year-based. We just refer to any next version as vNext until it is released, and then the NEXT version we'd also refer to as vNext. Does that make sense?
