### ISSUE TITLE
Using this task has no effect on the "Deploy to Kubernetes" task

### ISSUE THREAD

**Issue by booyaa** [MicrosoftDocs/vsts-docs#4372]
What's the use case for this tool? Are you meant to just use it via a command line or bash script task?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: efef7470-b172-c5f9-924a-f66ec84adc43
* Version Independent ID: 3c951d4f-51c5-ed67-8ee0-521770a4ae35
* Content: [Kubectl installer task - Azure Pipelines & TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/kubectl-installer?view=azure-devops)
* Content Source: [docs/pipelines/tasks/tool/kubectl-installer.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/tool/kubectl-installer.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @shashankbarsin
* Microsoft Alias: **shasb**

**Comment by shashankbarsin** [comment]
The use case for this tool is to install a specific version of kubectl binary on an agent. This can be used if one wants to change the version of kubectl binary on any of the hosted agents. It can also be used to install kubectl from scratch on a self hosted agent as well.
