### ISSUE TITLE
Stakeholders Access to Test in TFS 2015

### ISSUE THREAD

**Issue by fhack2** [MicrosoftDocs/vsts-docs#4374]
Stakeholders in the web portal have access to the Test tab in TFS 2015.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8db47b85-e178-7969-40d3-3fa83aa3fb54
* Version Independent ID: a78e453b-4b8f-c885-42ee-8a9d9979f345
* Content: [What are access levels? What access levels are supported? - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/security/access-levels?view=tfs-2015)
* Content Source: [docs/organizations/security/access-levels.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/security/access-levels.md)
* Product: **devops**
* Technology: **devops-security**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@chcomley  - Can you check with the PM and correct if true.

**Comment by fhack2** [comment]
https://marketplace.visualstudio.com/items?itemName=ms.vss-testmanager-web&ssr=false#pricing

Mentions that Stakeholders cannot have it. It’s a lost of function coming from TFS 2015 to Azure DevOps. We have stakeholder on TFS executing test plans, but now it’s changed to having basic to perform that function.

Even if they allowed Stakeholders to get this extension, it’s cheaper to make them Basic users instead.

Fahim Hack

**Comment by chcomley** [comment]
Hi @fhack2, 
For full access to Test Plans, the user needs a Basic + Test Plans license (or MSDN Platforms or VS Test Professional). https://azure.microsoft.com/en-us/pricing/details/devops/azure-devops-services/
Thanks for your feedback!
