### ISSUE TITLE
Cannot Find The "Order" button

### ISSUE THREAD

**Issue by rreyes-macpro** [MicrosoftDocs/vsts-docs#4375]
When I create a bunch of test cases within test suite, i usually add on the fly and later hit that "Order" button to re arrange the test cases according to order of execetion. Now, I dont know the reason why MS removes that functionality.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fb46332b-83bd-5525-cb42-11bcfef0843a
* Version Independent ID: aa9542b6-0b48-1818-092f-1989fbb45cf6
* Content: [Plan manual tests with MTM - Azure Test Plans](https://docs.microsoft.com/en-us/azure/devops/test/mtm/plan-manual-tests-with-microsoft-test-manager?view=azure-devops#feedback)
* Content Source: [docs/test/mtm/plan-manual-tests-with-microsoft-test-manager.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/test/mtm/plan-manual-tests-with-microsoft-test-manager.md)
* Product: **devops**
* Technology: **devops-test**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by WilliamAntonRohm** [comment]
It looks like you've encountered an issue with the product itself, rather than an issue with the documentation. To make sure it gets in front of the right people, please [submit your bug]( https://developercommunity.visualstudio.com/content/problem/post.html?space=21) here.
