### ISSUE TITLE
How to remove credentials and authenticate again

### ISSUE THREAD

**Issue by xperiandri** [MicrosoftDocs/vsts-docs#4377]
https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/disconnect-organization-from-azure-ad?view=azure-devops

What about telling how to remove old credentials from Windows and authenticate to Git repository again?
It must be specified on that page too.

**Comment by xperiandri** [comment]
This solution helped me
https://stackoverflow.com/posts/52749883/edit

**Comment by KathrynEE** [comment]
Assigning to @chcomley.

**Comment by chcomley** [comment]
Hi @xperiandri, I'm glad you found something that worked for you. Let me share another article that is a good starting point: https://docs.microsoft.com/en-us/azure/devops/repos/git/set-up-credential-managers?view=azure-devops. There are more specific manuals to the Git credential manager that are linked to within this doc, as well. I'll be closing this issue, however do let me know if you have any further questions or comments. Thanks so much for your feedback.

**Comment by xperiandri** [comment]
@chcomley I can't find how that article can help to solve my issue
