### ISSUE TITLE
Parallel forked and joined deployments could do with an example

### ISSUE THREAD

**Issue by StingyJack** [MicrosoftDocs/vsts-docs#4378]
What would the release pipeline definition look like? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d9e313c5-9120-9172-bc27-c21d10fcd5ae
* Version Independent ID: 1a837182-591f-3cbc-1632-7b50d857b13c
* Content: [Release triggers for stages, branches, and pipelines - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/triggers?view=azure-devops)
* Content Source: [docs/pipelines/release/triggers.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/release/triggers.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by RoopeshNair** [comment]
I believe it is captured in this section: "[Parallel forked and joined deployments](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/triggers?view=azure-devops#parallel-forked-and-joined-deployments)". Let us know if you are looking for something else here. Thank you

**Comment by StingyJack** [comment]
@RoopeshNair if it was, I wouldn't have asked.

**Comment by RoopeshNair** [comment]
@StingyJack  - here is the screenshot from the doc link shared earlier. The image has the release pipeline stage settings for running it in parallel (forking) and joining the stage workflows. Let me know if I'm missing something

![image](https://user-images.githubusercontent.com/1370480/58635411-70b06c80-830b-11e9-9c9a-b701452bdfd6.png)

**Comment by StingyJack** [comment]
@RoopeshNair - that is a _logical_ depiction. I'm asking for an **actual** example, because as far as I can tell, two stages cannot join back into one.

**Comment by RoopeshNair** [comment]
@StingyJack - if you look at Production in the figure, the setting says "After stage" - and the stages selected are "QA" and "Pre-prod". Meaning "Production" stage deployment will not start until both "QA" and "Pre-prod" are completed.

**Comment by StingyJack** [comment]
@RoopeshNair  - I think what I am ultimately struggling with is that all these say "After Stage". which means that they will be executed as soon as the deployment to the prior stage is completed. This is kind of ridiculous and means that using this model will move code from dev to QA/Pre-prod to Prod without testing being completed in any of those environments.  Adding a approval gate can help with this, but the definition of the promotion path gets lost when choosing manual.

For example, with those selections, I do get the rejoining lines, and a very specific promotion path
![image](https://user-images.githubusercontent.com/15381181/58752869-1b4b9b00-8484-11e9-982e-4060d0952d34.png)


however by selecting Manual triggering, I lose any kind of enforcement on the promotion path
![image](https://user-images.githubusercontent.com/15381181/58752866-0242ea00-8484-11e9-814e-2e54c66cfd90.png)

And we can deploy right to prod and bypass any other environments.

**Comment by RoopeshNair** [comment]
> they will be executed as soon as the deployment to the prior stage is completed. This is kind of ridiculous and means that using this model will move code from dev to QA/Pre-prod to Prod without testing being completed in any of those environments.

I'm not sure I got this. Isn't QA/Pre-prod supposed to include testing too? Are you referring to Manual testing? If yes, I would recommend checking out "[Manual Intervention](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/manual-intervention?view=azure-devops)" (MI) step.  With MI step in QA/Pre-prod stage, tester can sign-off and push the button to promote the release. Your pipeline structure remains intact and will the stage dependencies. Let me know if it helps

**Comment by StingyJack** [comment]
> Isn't QA/Pre-prod supposed to include testing too? Are you referring to Manual testing?

Yes, the QA/Pre-Prod environments include testing, and that is the point I am trying to make. When you have these automated deployment triggers as are configured in the parallel and forked deployments example, there is nothing prevent a release from being instantly promoted to  the next environment at the moment the prior stage deployment is complete. 

The MI step is for a deployment in progress. It would have to be used in its own stage in between the conventional stages in order to be effective, but that seems to be "bloaty". 

Is there no way to preserve/enforce a promotion path with these tools that does not also require automatic deployments or crazy tasks or configuration?

**Comment by RoopeshNair** [comment]
Not really, deployment to production that is dependent on QA and Pre-Prod will not start until both QA and Pre-prod stages complete. Maybe we can have quick call?

**Comment by StingyJack** [comment]
A stage being complete means that all activity for that stage is completed, not just the deployment steps in a release pipeline for that stage. 

Consider this schedule...

11:00  - build produces artifact
11:01 - release is created from artifact
11:02 - release deployment begins to DEV
11:05 - release deployment completed to DEV
<with triggers setup as they are in the forked and joined example> 
11:06 - release deployment begins to QA
11:06 - release deployment begins to Pre-Prod
11:09 - release deployment completed to QA
11:09 - release deployment completed to Pre-Prod
11:10 - release deployment begins to Prod
11:10 - release deployment completed to Prod

There isnt any "STOP and wait for testing".  By making them manual triggers, users can bypass stages entirely.

**Comment by RoopeshNair** [comment]
This helps, as described earlier, you define MI step in QA / Pre-prod and assign this to testers so that they can sign-off once done. MI is meant for steps that can't be automated including manual tests
