### ISSUE TITLE
Is there any integration planned for Azure DevOps and SeviceNow Knowledge Managment.

### ISSUE THREAD

**Issue by raisingcode** [MicrosoftDocs/vsts-docs#4379]
Just curious. Currently our engineers are using Azure Wikis but its seperated from ServiceNow portal

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d07f29c5-affb-47bb-5f68-fc49e691c741
* Version Independent ID: 661d3781-8784-868d-261f-1e994a154a35
* Content: [Control deployments by using ServiceNow - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/approvals/servicenow?view=azure-devops#feedback)
* Content Source: [docs/pipelines/release/approvals/servicenow.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/release/approvals/servicenow.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by RoopeshNair** [comment]
@shashban  - can you please take a look?

**Comment by shashban** [comment]
AFAIK there isn't a plan for this integration. 
@raisingcode Would it be possible to help us with more details on the scenario you are looking for.
We can channel the requirement to the wiki team and let them prioritize.

**Comment by raisingcode** [comment]
@shashban thanks for the reply. I would rank this as extremley low; at least for us at this point in time. The scenario we had in mind was being deploy servicenow knowledge base article(s) as part of the production release process. servicenow is our  change mangment record of truth so integrating artifacts from azure devops artificats to into to link changes is good start and then growing futher with documentation and support for the front-line services. We use Azure wikis now as development group but our support ticketing process is highly coupled with servicenow. We're also looking at calling a ServiceNow API as part of a task/step in the pipeline

**Comment by adramasu** [comment]
hey @raisingcode, we don't have an integration story with servicenow. You can use the URLs of wiki pgaes to add links to external applications. The pages are also available with REST APIs. So with a little bit of code, you can get the page creation process automated. Documentation for REST APIs can be found [here](https://docs.microsoft.com/en-us/rest/api/azure/devops/wiki/pages/create%20or%20update?view=azure-devops-rest-5.0#add-a-page).

**Comment by RoopeshNair** [comment]
@shashban

**Comment by WilliamAntonRohm** [comment]
@raisingcode -- Jason, I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
