### ISSUE TITLE
How do I find out the list of retained indefinitely builds?

### ISSUE THREAD

**Issue by choksheak** [MicrosoftDocs/vsts-docs#438]
I am not able to clean up builds which I previously marked as Retain Indefinitely but which I no longer need now.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43a285f9-738d-9f76-4de0-a4c4ecf6f5f5
* Version Independent ID: 9581a043-4873-bf0a-138f-85f6a61ae950
* Content: [Build and release retention policies](https://docs.microsoft.com/en-us/vsts/build-release/concepts/policies/retention?view=vsts)
* Content Source: [docs/build-release/concepts/policies/retention.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/build-release/concepts/policies/retention.md)
* Service: **unspecified**
* GitHub Login: @erickson-doug
* Microsoft Alias: **alewis**

**Comment by vijayma** [comment]
We have a new page coming up for displaying the history of all builds. That will help you see which ones are retained indefinitely. Until then, you have to do one of the following - (1) Use API to retrieve a list of builds, iterate through them checking for this flag, and delete them (2) Navigate to the build history of each definition (All definitions -> Select definition -> History), find the builds that are retained indefinitely (using the lock icon) and then delete them,

**Comment by choksheak** [comment]
Hi Vijay, thank you for your response and yes the build history is what I
used, but note that once the build gets old and buried deep within the
history, it is excruciating hard to find an old build by its build id. I
think it would be nice to have a page of "Retained Builds" that can allow
us to find the retained builds easily. I think the current system actually
makes it very easy to leave old junk builds behind as it is so hard to
clean them up. Also the "Retained Builds" page should have a "Last
Accessed" timestamp to let us know which ones can be deleted and which ones
can't. Thank you for your help.

**Comment by andyjlewis** [comment]
Thanks for the suggestion. FYI, you can post suggestions like this on [user voice](https://visualstudio.uservoice.com/forums/330519-visual-studio-team-services?category_id=145254).

**Comment by StingyJack** [comment]
RE: User voice...
![image](https://user-images.githubusercontent.com/15381181/62215206-7dd1f200-b374-11e9-899c-de8e6cbcb555.png)

**Comment by vijayma** [comment]
https://developercommunity.visualstudio.com/content/idea/post.html?space=21
