### ISSUE TITLE
Adding notifications to the default list

### ISSUE THREAD

**Issue by robmck-ms** [MicrosoftDocs/vsts-docs#4381]
This doesn't describe how to add organization-wide notifications to this list. If that's not possible, it would be helpful to state that here so that I don't keep looking for a way.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a1944149-ef01-c421-2ec8-c51626c31e0a
* Version Independent ID: e774788f-e1db-babf-556f-9aff176a4bd9
* Content: [Manage notifications for an organization - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/notifications/howto-manage-organization-notifications?view=azure-devops)
* Content Source: [docs/notifications/howto-manage-organization-notifications.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/notifications/howto-manage-organization-notifications.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @robmck-ms, Thanks for the feedback. I've reached out to my PM for clarification and will let you know as soon as possible!

**Comment by chcomley** [comment]
Hi @robmck-ms, We don't support organization-wide notifications, and so I've updated the doc, which should go live sometime this afternoon. Although, technically, you could provide an email DL that goes to your whole organization, if you want. Let me know if you have any further questions please. Thanks for reaching out!

**Comment by robmck-ms** [comment]
I wasn't looking for a way to notify the organization, but rather how to add to the default set of notifications. Every time I create a project, there are 3 additional notifications I want created in it. I was hoping to find a way to create them in the default notification list so that I don't have to do this manually all the time.

**Comment by chcomley** [comment]
Gotcha, @robmck-ms. In that case, I'd recommend filing a feature request here: https://developercommunity.visualstudio.com/content/idea/post.html?space=21 
Thanks and have a great day!
