### ISSUE TITLE
misspelled word

### ISSUE THREAD

**Issue by paulclavier** [MicrosoftDocs/vsts-docs#4384]
you misspelled two 

Developer Command Prompt to bring up the merge tool directly against any tow files. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 318c9e4a-6c12-ab7d-4fc8-f4640f0bd755
* Version Independent ID: aa8d36c5-a69e-8bf4-83da-bc52a6b9f7f5
* Content: [Compare files - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/tfvc/compare-files?view=azure-devops&viewFallbackFrom=vsts#feedback)
* Content Source: [docs/repos/tfvc/compare-files.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/repos/tfvc/compare-files.md)
* Product: **devops**
* Technology: **devops-code-tfvc**
* GitHub Login: @apawast
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
@paulclavier Thanks for letting us know, we'll get that fixed.
