### ISSUE TITLE
publishWebProjects not documented

### ISSUE THREAD

**Issue by MisinformedDNA** [MicrosoftDocs/vsts-docs#4385]
The task has a property `publishWebProjects`, but it's not documented here. This property [causes some confusion](https://developercommunity.visualstudio.com/content/problem/405294/dotnet-publish-seems-to-ignore-working-directory.html) since it basically ignores the working directory.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 483dcb1c-1a89-2b20-4cf2-abd3ae88d9ed
* Version Independent ID: dc4722ed-5a4b-26ec-e7d5-a149bf6e79a7
* Content: [Build, test, and deploy .NET Core apps - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/languages/dotnet-core?view=azure-devops)
* Content Source: [docs/pipelines/languages/dotnet-core.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/languages/dotnet-core.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by Kissaki** [comment]
This seems to be documented now in the section “Package and deliver your code” -> “Deploy a web app”.

Or do you mean something else?

**Comment by MisinformedDNA** [comment]
Correct, except it is only used in a single example with no (textual) documentation to go along with it. It could use some explanation, with particular regard for the [issue linked](https://developercommunity.visualstudio.com/content/problem/405294/dotnet-publish-seems-to-ignore-working-directory.html).

**Comment by chasewilson** [comment]
Hi @MisinformedDNA, thanks for the feedback! There is the actual [task documentation](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/dotnet-core-cli?view=azure-devops) the has full documentation on all inputs. Do you think it would be helpful to have a link or to that documentation?

**Comment by MisinformedDNA** [comment]
@chasewilson Hmmm, a link to that would certainly help, but I may have looked at that documentation and didn't understand it anyway. Contrary to most dotnet commands, which would use the working directory as a starting point, this one is looking through the _entire_ repo. So maybe it needs a special callout. Instead of 

> If true, the task will try to find the web projects in the repository and run the publish command on them. Web projects are identified by presence of either a web.config file or wwwroot folder in the directory.

maybe it could be changed to (italics used to call out differences):

> If true, the task will try to find _all_ web projects in the _entire_ repository and run the publish command on them. Web projects are identified by presence of either a web.config file or wwwroot folder in the directory. _NOTE: `workingDirectory` is ignored._

Maybe that's too many quantifiers, but I'll leave that to you. :)

**Comment by chasewilson** [comment]
Alright, I've updated the info with a note. I'll be closing this issue but you should see it live within 24 hours. Feel free to open a new issue with any more feedback you have and it will keep it at the top of my issues :) Thanks again for all of the feedback @MisinformedDNA
