### ISSUE TITLE
How to overcome this rate limit?

### ISSUE THREAD

**Issue by AlexChongMicrosoft** [MicrosoftDocs/vsts-docs#4387]
How to overcome this rate limit?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5c2c2355-60a5-d53f-2c72-8f032c1b8cf2
* Version Independent ID: 711bf22d-99c9-51b2-382c-e095bdb2c37f
* Content: [Resource limits & constraints - Azure DevOps Services](https://docs.microsoft.com/en-US/azure/devops/integrate/concepts/rate-limits?view=azure-devops#pipelines)
* Content Source: [docs/integrate/concepts/rate-limits.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/integrate/concepts/rate-limits.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by v-wilock** [comment]
@AlexChongMicrosoft - You can reach out to the RASP team for a temporary exception. If you need help, feel free to reach out to me via Teams and I can put you in contact.

**Comment by AlexChongMicrosoft** [comment]
Thank you for quick response. You help me a lot. Could you tell me what RASP stands for? I will contact you in Teams if necessary.

**Comment by v-wilock** [comment]
RASP is the team dedicated to making Azure DevOps a **R**eliable, **A**daptive, and **S**ecure **P**latform.

**Comment by AmitSheth** [comment]
Is this option of temporary exception available to anyone?

**Comment by v-wilock** [comment]
I'm not sure, but it seems unlikely. You're much more likely to get delays than to have out-and-out errors pop up unless you're really hammering the system. And if you are, that raises some question marks on its own. Those question marks will go on sentences like "Can you optimize this?"

**Comment by KathrynEE** [comment]
Closing issue for now.

**Comment by prolitaaron** [comment]
Some documentation on best practice in dealing with throttling would be great.
