### ISSUE TITLE
*an stage* typo

### ISSUE THREAD

**Issue by wachulski** [MicrosoftDocs/vsts-docs#4389]
Should rather go *a stage*

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 315ff823-9992-9f9b-62a1-42ce622ed41c
* Version Independent ID: 72ec3ffc-1dc9-b2dc-e3d4-4f14deae3720
* Content: [File transforms and variable substitution - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/transforms-variable-substitution?view=azure-devops#feedback)
* Content Source: [docs/pipelines/tasks/transforms-variable-substitution.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/transforms-variable-substitution.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by RoopeshNair** [comment]
I'm sorry, it is not clear to me, what is ask here?

**Comment by RoopeshNair** [comment]
Can doc team take care of this, pls?

**Comment by WilliamAntonRohm** [comment]
Thank you for your feedback.  I have updated the documentation and it should be live by tomorrow.

**Comment by WilliamAntonRohm** [comment]
Fix PR is https://dev.azure.com/mseng/TechnicalContent/_git/vsts-docs-pr/pullrequest/494399

**Comment by WilliamAntonRohm** [comment]
PR is still in review -- reopening issue.

**Comment by WilliamAntonRohm** [comment]
Thank you for your feedback.  I have updated the documentation and it should be live by tomorrow.
