### ISSUE TITLE
Not clear on how Release Admins are created

### ISSUE THREAD

**Issue by PhilPeters304** [MicrosoftDocs/vsts-docs#4391]
As discussed here(https://developercommunity.visualstudio.com/content/problem/588081/azure-devops-not-creating-release-administrator-gr.html) it is not clear on this page that Release Administrators are only created when a user creates a release. Please update to make it clear that "by design" the Release Administrators group is not created until a release is created. 

Thanks 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 68686c2b-c69a-d9e4-3e21-a46d231b649c
* Version Independent ID: 049659da-1772-3166-f909-4feeb8a97730
* Content: [What are all the default permissions and groups? - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/security/permissions?view=azure-devops#feedback)
* Content Source: [docs/organizations/security/permissions.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/security/permissions.md)
* Product: **devops**
* Technology: **devops-security**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@PhilPeters304 - Thank you for the correction. I am updating the topic to clarify that the project-level Release Administrators group is defined with the first release pipeline.
