### ISSUE TITLE
Are stage variables supported yet?

### ISSUE THREAD

**Issue by guythetechie** [MicrosoftDocs/vsts-docs#4394]
This section seems to suggest stage variables are supported already:

stages:
- stage: string  # name of the stage, A-Z, a-z, 0-9, and underscore
  displayName: string  # friendly name to display in the UI
  dependsOn: string | [ string ]
  condition: string
  VARIABLES: { string: string } | [ variable | variableReference ] 
  jobs: [ job | templateReference]

However, it doesn't seem to work for me. The AKS-NAME variable below doesn't seem to work. Here's how I have it defined:
- stage: dev
  displayName: dev
  dependsOn: build
  variables:
    AKS-NAME: myvar
  jobs: etc...

According to this link (https://devblogs.microsoft.com/devops/whats-new-with-azure-pipelines/#comments-325), it says the capability will be added soon. Is this supported yet?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4266f72c-c774-0046-4593-d01eb775d3c3
* Version Independent ID: f20827aa-a6c5-96a8-5969-e576ffbc2e38
* Content: [Stages in Azure Pipelines - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/stages?view=azure-devops&tabs=yaml#feedback)
* Content Source: [docs/pipelines/process/stages.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/stages.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @vijayma
* Microsoft Alias: **vijayma**

**Comment by andy-otter** [comment]
This does seem to work, think that your yaml may be incorrect

Example.
```
stages:
- stage: build
  displayName: build displayName
  variables:
  - group: a-variable-group
  - name: fu
    value: 'bar'

  jobs:
  - job: jobA
```
```

**Comment by arkiaconsulting** [comment]
@andy-otter How do you reference variables between stages ?

**Comment by vijayma** [comment]
@andy-otter You cannot reference variables between stages yet. That is on our backlog.
