### ISSUE TITLE
deploymentMethod should explicity describe the options

### ISSUE THREAD

**Issue by JustinGrote** [MicrosoftDocs/vsts-docs#4396]
I had to go to the source code to find this, it should be on this page:
export enum DeploymentType {
    auto,
    zipDeploy,
    runFromPackage,
    warDeploy
}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f82ad1fa-cee5-c5c6-7050-21aaec6b714a
* Version Independent ID: 617316ff-2dab-d021-880f-c1c79313c320
* Content: [Azure Function App task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-function-app?view=azure-devops#open-source)
* Content Source: [docs/pipelines/tasks/deploy/azure-function-app.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/deploy/azure-function-app.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @shashankbarsin
* Microsoft Alias: **shasb**

**Comment by JustinGrote** [comment]
To be clear, the documentation above just says "Zip Deploy", but you have to explicitly say "zipdeploy" for it to work. The documentation should have a table of each explicit option, and what it corresponds to, rather than the "general" nonspecific directions that currently exist.

**Comment by RoopeshNair** [comment]
@N-Usha  - can you please take a look?

**Comment by N-Usha** [comment]
Thanks @JustinGrote for reporting this . We will have our documentation updated with the accepted values for deploymentMethod parameter.

**Comment by N-Usha** [comment]
Can be closed the documentation has been updated
