### ISSUE TITLE
Loading page takes long time

### ISSUE THREAD

**Issue by sonpeppers** [MicrosoftDocs/vsts-docs#4399]
Viewing content on Organization settings &gt; Pipelines &gt; Retention and parallel jobs &gt; Parallel jobs took over a minute to load.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c6a488b-88f6-dff6-e2ee-402167e17ad4
* Version Independent ID: 9a4dedda-e82c-2833-f28c-5ab346fb1b38
* Content: [Parallel jobs in Azure Pipelines - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/licensing/concurrent-jobs?view=azure-devops)
* Content Source: [docs/pipelines/licensing/concurrent-jobs.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/licensing/concurrent-jobs.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by thomps23** [comment]
@sonpeppers This repository primarily tracks issues against the documentation, if you could provide your feedback as a bug at [this location](https://developercommunity.visualstudio.com/content/problem/post.html?space=21) it will have a better chance of getting in front of the appropriate team for triage.
