### ISSUE TITLE
Combined install and authorize steps for Azure Boards GitHub app

### ISSUE THREAD

**Issue by alexcnichols** [MicrosoftDocs/vsts-docs#4400]
The "Install and Authorize" steps for installing the Azure Boards GitHub app have been combined. Step 4 needs a new screenshot and text. Step 6 can be removed.

https://docs.microsoft.com/en-us/azure/devops/boards/github/install-github-app?view=azure-devops#install-and-configure-the-azure-boards-app

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e0f91070-b95b-fbb7-a6f2-bf11f6ceff43
* Version Independent ID: fe6f39f4-d718-522e-129a-de5c09b5c021
* Content: [Install and configure the Azure Boards app for GitHub - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/github/install-github-app?view=azure-devops#feedback)
* Content Source: [docs/boards/github/install-github-app.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/boards/github/install-github-app.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@alexcnichols - Thanks for the update. I'll get the content updated by EOD.

**Comment by pravinpande** [comment]
@alexcnichols @KathrynEE Is this supported for GitHub.com only? What about enterprise repos?

**Comment by alexcnichols** [comment]
@pravinpande the fact that install and authorize steps have been combined is a setting specific to the Azure Boards app in GitHub.com. The options for integrating with GitHub Enterprise Server are a bit different.

**Comment by alexcnichols** [comment]
@KathrynEE this issue appears to have been closed without being fixed. The steps in the flow are different than what's in the docs.
