### ISSUE TITLE
Running Deployment Job in Container

### ISSUE THREAD

**Issue by davidtom** [MicrosoftDocs/vsts-docs#4401]
I'd like to utilize deployment jobs in my multi-stage pipeline, but in order to do so I need to be able to run my tasks in a container. This is possible with jobs, but doesn't seem to be possible to do with deployment jobs. Am I just making a mistake specifying the container in the YAML?

If it is indeed not possible, why? Is there a roadmap for when it will be possible?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5aeeaace-1c5b-a51b-e41f-f25b806155b8
* Version Independent ID: fd7ff690-b2e4-41c7-a342-e528b911c6e1
* Content: [Deployment jobs - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/deployment-jobs?view=azure-devops#feedback)
* Content Source: [docs/pipelines/process/deployment-jobs.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/deployment-jobs.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @shashankbarsin
* Microsoft Alias: **shasb**

**Comment by RoopeshNair** [comment]
container jobs/ server jobs aren't supported in the deployment job. It will be a while before we can add support for it. (4+ months). We are currently working on adding additional properties to the deployment job. For example, variables, variable groups, timeouts, conditions, template references etc.

We know this is important for you. We will continue to track this on our backlog. For the moment, you can use the regular job which supports the container workloads.

**Comment by davidtom** [comment]
Thanks for the response Roopesh. Really appreciate the clarity on timeline and will look forward to using it whenever its ready.

For the time being I have continued with the regular job in order to utilize my containers. This works well enough, but the fact that each job checks out my source code has been a bit of a problem that I've had to work around (I'd prefer to work directly with the files in my container instead).

My understanding was that deployment jobs do not do this `Checkout` step, but is there any way to disable that step in a regular container job? I've looked through the documentation, but haven't found anything. I assume because this is a built in feature of build pipelines?

**Comment by RoopeshNair** [comment]
You can turn of syncing using 
```yaml
steps:
- checkout: none
```

**Comment by thomps23** [comment]
@RoopeshNair do we need to document this checkout option or are we covered?

**Comment by davidtom** [comment]
Thank you @RoopeshNair! This is just what I was looking for.

@thomps23 I couldn't find this in the documentation when I was trying to solve my issue, but now that I know what to look for I was actually able to find it [here](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema#checkout). This seems like the logical place for it to be, so I'd say you guys are covered.

Thanks again!

**Comment by IPO-srh-sloan** [comment]
Hi is there any update on when deployment container jobs will be available please?

**Comment by RoopeshNair** [comment]
No time-lines that can be shared yet. Tentatively q1/q1 2020
