### ISSUE TITLE
Creating teams 

### ISSUE THREAD

**Issue by bbulldis** [MicrosoftDocs/vsts-docs#4402]
This article states “Only members of the Project Administrators group or those who have been granted explicit permissions to edit project information can add and delete teams.“  however if you grant another group edit project level and grant every permission for that matter, they still can not create teams. We want a sub project admin that can create everything including teams but is not able to delete anything. Is there any way to allow a group other than project admin to create teams?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 112e8056-a242-c7d5-8a7a-13883b1d9834
* Version Independent ID: 898ba7df-2a34-0ceb-d613-f200b5fc9bf8
* Content: [Add a team, move from one team to several teams - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/settings/add-teams?view=azure-devops#feedback)
* Content Source: [docs/organizations/settings/add-teams.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/settings/add-teams.md)
* Product: **devops**
* Technology: **devops-settings**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by smithago** [comment]
Thanks for reaching out. 

Currently you need to be in project admin group to create a team. Edit project information permission does not work anymore. 

We will update the document.
