### ISSUE TITLE
Locking secrets to branch builds

### ISSUE THREAD

**Issue by baloo** [MicrosoftDocs/vsts-docs#4403]
Would someone know how to lock secrets to Github branch builds and not pull requests?

For an opensource repository, that would enable anyone to fetch secrets by modifying the pipeline tasks. And this is a bad thing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 69ff8e50-4187-3622-1beb-155f006af5f5
* Version Independent ID: bc56fa96-bded-95f8-39a4-a9e5242db1bf
* Content: [Azure Key Vault task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-key-vault?view=azure-devops#feedback)
* Content Source: [docs/pipelines/tasks/deploy/azure-key-vault.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/deploy/azure-key-vault.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by RoopeshNair** [comment]
Azure Key vaults are linked via Variable Groups and consumed in pipelines (builds/release stages). Or you can download them using this task. Either way, you can configure security on variable groups, or on the service connections to key vault and the pipeline itself. You have multiple layers of control on how the key vault is consumed.

**Comment by baloo** [comment]
@RoopeshNair Sorry I have not been cleared enough, I was looking for a policy like the one described in https://github.com/MicrosoftDocs/vsts-docs/issues/2325 but for azure key vault.

**Comment by RoopeshNair** [comment]
@baloo  - We don't have policies that can be applied to KeyVault and branches. The solution proposal detailed in @2325 by @davidstaheli seems valid here as well apart for security permissions that can be applied on the the pipelines
