### ISSUE TITLE
User cannot control order of picklist items

### ISSUE THREAD

**Issue by prlcutting** [MicrosoftDocs/vsts-docs#4406]
For picklists, the documentation states *Add the items in the order you want them to appear in the list.*.  This does not appear to be correct.  No matter what order items are added to the list, they are always presented alphabetically.  For example, adding the values "High", "Medium" and "Low" (in that order) results in a pick list with entries in this order: "High", "Low", "Medium", which is counter-intuitive.  Presumably they are being sorted alphabetically ascending and presented as such.  I don't know if this is a bug in the software or a mistake in the documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 89a8f6f1-da40-5a76-6336-dc04ad779d85
* Version Independent ID: 1c39c3fe-aa40-c8d7-d52a-3f4d967cbaa5
* Content: [Add and manage fields to an inherited process - Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/organizations/settings/work/customize-process-field?view=azure-devops#add-a-custom-field)
* Content Source: [docs/organizations/settings/work/customize-process-field.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/settings/work/customize-process-field.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by prlcutting** [comment]
I guess a simple workaround would be to prefix each entry with a number to get the sort order you want, e.g. "1 - High", "2 - Medium", "3 - Low".  I see that this is how the Severity field is presented for a Bug in the Agile process.

**Comment by KathrynEE** [comment]
@prlcutting - Thank you for your inquiry. This is a mistake in the documentation, which I will correct. The workaround you note is how we currently get around the limitation. The scenario you outline is on the product backlog. It should ship within the next could of months.

**Comment by prlcutting** [comment]
@kathrynee Is there a link to a work item you can send me please to track progress on this enhancement for users to control the order of items in a picklist?

**Comment by prlcutting** [comment]
@KathrynEE - Could you please provide a status update on when we will be able to manually control the order of items (i.e. not just alphabetical), or perhaps point us to a work item that we can follow to monitor progress?  In June you mentioned that functionality would be shipping in a couple of months.  We're now in November and it doesn't appear that it is available yet.  Thanks.

**Comment by mdressman** [comment]
This still seems like an issue. I don't want to have to prefix my picklist options. Any updates on when we will be able to reorder the options please?

**Comment by KathrynEE** [comment]
@mdressman, @prlcutting - This feature has shipped and the article updated to reflect the updates. See this release note: https://docs.microsoft.com/en-us/azure/devops/release-notes/2019/sprint-149-update#state-value-order-on-work-item-form.  It was shipped for on-prem with Azure DevOps Server 2019 Update 1, https://docs.microsoft.com/en-us/azure/devops/server/release-notes/azuredevops2019u1?view=azure-devops#state-value-order-on-work-item-form.

**Comment by tbeavers** [comment]
@KathrynEE, do you happen to know when this feature will be available for custom pick list fields in Azure DevOps Services?

**Comment by KathrynEE** [comment]
@tbeavers - Hello. The feature to order the custom picklist isn't on the Roadmap.  You may want to suggest it as a new feature on our[ Developer Community page](https://developercommunity.visualstudio.com/report?space=21&q=picklist+custom+order&entry=suggestion).

**Comment by njpaul** [comment]
I recently created an extension that lets you order the items. It may fit your needs.

https://marketplace.visualstudio.com/items?itemName=njpaul.ordered-dropdown
