### ISSUE TITLE
hostName should be knownHostsEntry

### ISSUE THREAD

**Issue by AnticliMaxtic** [MicrosoftDocs/vsts-docs#4408]
The example yaml snippet says 
```bash
# Install SSH Key
# Install an SSH key prior to a build or release
- task: InstallSSHKey@0
  inputs:
    hostName: 
    sshPublicKey: 
    #sshPassphrase: # Optional
    sshKeySecureFile: 
```
but hostName should be knownHostsEntry 

It is eluded to in the explination below but should be correct in the example as well. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ce9d017-fc43-c904-d94b-87cf91265ffc
* Version Independent ID: ecf3b0b7-6c2c-1cd9-33a9-2cf562932e2b
* Content: [Install SSH Key task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/install-ssh-key?view=azure-devops)
* Content Source: [docs/pipelines/tasks/utility/install-ssh-key.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/utility/install-ssh-key.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @DavidStaheli
* Microsoft Alias: **dastahel**

**Comment by davidstaheli** [comment]
This has been fixed.  Thanks, @AnticliMaxtic!
