### ISSUE TITLE
Multiple known_hosts

### ISSUE THREAD

**Issue by AnticliMaxtic** [MicrosoftDocs/vsts-docs#4411]
It does not seem to be possible to use a known_hosts file rather than a string for a single known hosts. I have multiple servers that I need the same ssh key to authenticate against and I have put them all in together as one string, but that does not seem to work. I can only access the first one in the list

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ce9d017-fc43-c904-d94b-87cf91265ffc
* Version Independent ID: ecf3b0b7-6c2c-1cd9-33a9-2cf562932e2b
* Content: [Install SSH Key task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/install-ssh-key?view=azure-devops#feedback)
* Content Source: [docs/pipelines/tasks/utility/install-ssh-key.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/utility/install-ssh-key.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @DavidStaheli
* Microsoft Alias: **dastahel**

**Comment by yahalawa** [comment]
any update on this?

**Comment by davidstaheli** [comment]
@yahalawa thanks for asking about this.  We're going to move this issue to this repo:
https://github.com/Microsoft/azure-pipelines-tasks

/move to Microsoft/azure-pipelines-tasks
