### ISSUE TITLE
the sample function does not compile without explicit ref to Newtonsoft.Json package

### ISSUE THREAD

**Issue by lukka** [MicrosoftDocs/vsts-docs#4415]
The provided C# script file misses at the beginning the usage of the Newtonsoft.Json package:

`#r "Newtonsoft.Json"
`

The function does not compile without it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 915c7aa9-0969-912b-bbc4-a2b0bf9b1533
* Version Independent ID: 6a97a5e8-8397-be98-5528-70d20e8fbed8
* Content: [Use Azure Functions to create custom branch policies - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/create-pr-status-server-with-azure-functions?view=azure-devops)
* Content Source: [docs/repos/git/create-pr-status-server-with-azure-functions.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/repos/git/create-pr-status-server-with-azure-functions.md)
* Product: **devops**
* Technology: **devops-code-git**
* GitHub Login: @apawast
* Microsoft Alias: **yohasna**

**Comment by apawast** [comment]
Thank you for letting us know! I will add that.
