### ISSUE TITLE
This worked once, but never again. 

### ISSUE THREAD

**Issue by StingyJack** [MicrosoftDocs/vsts-docs#4418]
It should not be this hard to use these CLI tools. If I register a AzArtifacts source without specifying credentials (per the first screenshot) I get prompted for UserName and Password when trying to push. I can give it the correct credentials, but it just asks me again for the credentials. 

If i add the source using the PAT (that has permissions to "Packaging (Read & write)"), it reports 403 error because I dont have "Add Package" permission.  This worked once a few weeks ago and I havent changed the nuget config at all since then.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab0a3735-a9b0-2ed7-f08f-5321f55f8c90
* Version Independent ID: 2153f6c0-def7-eed1-286d-5e61c9fcbec4
* Content: [Use NuGet with Azure DevOps Services feeds](https://docs.microsoft.com/en-us/azure/devops/artifacts/nuget/nuget-exe?view=azure-devops)
* Content Source: [docs/artifacts/nuget/nuget-exe.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/artifacts/nuget/nuget-exe.md)
* Product: **devops**
* Technology: **devops-artifacts**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by gburghardt** [comment]
I ran into this problem too, but was able to solve it by downloading the credential provider, and then putting the `NuGet.exe` and `CredentialProvider.Vss.exe` files in the same directory (where that directory is in your windows %PATH%).

**Comment by chasewilson** [comment]
@StingyJack Thanks for the feedback. I believe @gburghardt. 
There is going to be a revamp of the connect to feed experience and documentation soon. I'm closing this issue for now but feel free to open a new issue in the updated documentation if you are still having issues.
