### ISSUE TITLE
Decorator for Release

### ISSUE THREAD

**Issue by mcollis2** [MicrosoftDocs/vsts-docs#4419]
Hi, this seems to work great for "Pipelines", adding a custom task to all builds for example.  However it does not work on releases.  Is there a way to get it to work?  The target for pipelines is ms.azure-pipelines-agent-job.pre-job-tasks.  Is there an equivalent for releases?  I want to enforce a task whether a user is running a build, multi-stage yaml build/release, or just a release.

Thanks,
Matthew

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0704e7ce-a2bb-7ccd-4ad4-2c6ad55bc8f4
* Version Independent ID: 4efcddb9-864d-f895-8122-451c1045b272
* Content: [Pipeline decorators](https://docs.microsoft.com/en-us/azure/devops/extend/develop/add-pipeline-decorator?toc=%2Fazure%2Fdevops%2Fextend%2Ftoc.json&bc=%2Fazure%2Fdevops%2Fextend%2Fbreadcrumb%2Ftoc.json&view=azure-devops)
* Content Source: [docs/extend/develop/add-pipeline-decorator.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/extend/develop/add-pipeline-decorator.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @stephenmichaelf
* Microsoft Alias: **stfrance**

**Comment by stephenmichaelf** [comment]
Hey Matthew,

This does not exist for releases yet. We have plans to add it in the future but I don't know what the timeline is. It should work today for build and multi-stage build/release.

Stephen

**Comment by mcollis2** [comment]
Thanks for the update!

**Comment by lettucemode** [comment]
Hi @stephenmichaelf , are you aware of any updates to this planned feature? 

I'm on the build team at a large corporation, and one of the things we'd like to do is gather statistics on how many releases are done daily and what kinds of technologies are in use. For example, what % of our applications are .NET and hosted in Azure. This release decorator would be perfect for that, since we could drop it into everyone's releases without them needing to do anything.

**Comment by stephenmichaelf** [comment]
@lettucemode They've been added! Let me find out if we've updated the docs for how to use them.

**Comment by stephenmichaelf** [comment]
I've reached out to the team that implemented decorators for release and asked them to respond here with steps and to updated our docs [here](https://docs.microsoft.com/en-us/azure/devops/extend/develop/add-pipeline-decorator?view=azure-devops).

**Comment by madhuv-msft** [comment]
@lettucemode we have added the info in this [document](https://docs.microsoft.com/en-us/azure/devops/extend/develop/add-pipeline-decorator?view=azure-devops#author-a-pipeline-decorator). You can find info on what to add as targets, _ms.azure-release-pipelines-agent-job.pre-job-tasks and ms.azure-release-pipelines-agent-job.post-job-tasks targets inject the decorators in jobs in release pipelines._

We also have few more details on this in this [decorator expression context](https://docs.microsoft.com/en-us/azure/devops/extend/develop/pipeline-decorator-context?view=azure-devops) also.

**Comment by lettucemode** [comment]
Thank you both!
