### ISSUE TITLE
Xnxnjxjdjdjjdj

### ISSUE THREAD

**Issue by fkfkfkf** [MicrosoftDocs/vsts-docs#442]
Jsjdjdjjdjdjdjdjj

---
#### รายละเอียดเอกสาร

⚠ *อย่าแก้ไขส่วนนี้ กำหนดให้ต้องจัดทำ docs.microsoft.com ➟ การเชื่อมโยงปัญหา GitHub*

* ID: 1fd3e188-c59c-c204-fa15-d5ec7b7deebd
* Version Independent ID: f5d79338-4296-c9b1-9979-762101d2976a
* Content: [Status and trend work item, query-based charts - VSTS & TFS](https://docs.microsoft.com/th-th/vsts/report/dashboards/charts?view=vsts)
* Content Source: [docs/report/dashboards/charts.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/report/dashboards/charts.md)
* Service: **unspecified**
* GitHub Login: @erickson-doug
* Microsoft Alias: **kaelli**

**Comment by steved0x** [comment]
@fkfkfkf I'm closing this issue since I don't see any actionable feedback. Thank you.
