### ISSUE TITLE
Add the explanation and the default value for workspace.clean

### ISSUE THREAD

**Issue by haokanga** [MicrosoftDocs/vsts-docs#4422]
workspace:
    clean: outputs | resources | all # what to clean up before the job runs

* What is the default behavior?
* What will be the behavior when `workspace clean` is set to `outputs, resources, or all`?
* What are outputs and resources?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 67504b34-d64b-02a4-2e10-ab99f3b8cfe4
* Version Independent ID: 2cf63b2e-184b-7726-3b8a-d8baffd6fcce
* Content: [Jobs in Azure Pipelines, Azure DevOps Sever, and TFS - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/phases?tabs=yaml&view=azure-devops)
* Content Source: [docs/pipelines/process/phases.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/phases.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @vijayma
* Microsoft Alias: **vijayma**

**Comment by vijayma** [comment]
@haokanga Thanks for the feedback. I just updated the content for this topic. It will now include another section for "Workspace" that describes what you asked for. Thank you. (PS: It may take a day for this change to be live).
