### ISSUE TITLE
docker script is not right

### ISSUE THREAD

**Issue by jzhang3-rms** [MicrosoftDocs/vsts-docs#4423]
"docker run --rm -d"" will just detach the container, you have no idea when tests will run into finish and results are available for copying. Also you don't want to remove the container after run and before copy.

Instead, you can just do,
docker run --name test xxx
docker cp test:/container-path /local-path
docker rm test

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba91e46a-de53-c0c1-f7f7-c02e797d527c
* Version Independent ID: 6f478148-461f-694a-ed82-deb4d731854e
* Content: [Publish Test Results task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/test/publish-test-results?view=azure-devops&tabs=yaml#feedback)
* Content Source: [docs/pipelines/tasks/test/publish-test-results.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/test/publish-test-results.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @PBoraMSFT
* Microsoft Alias: **pbora**

**Comment by PBoraMSFT** [comment]
@divais - can you take a look?

**Comment by gldraphael** [comment]
The example assumes tests are run during `docker build`. It's just an example on how to get the test results out of the image. We've used it before and it worked just fine.
