### ISSUE TITLE
Typo?

### ISSUE THREAD

**Issue by jlroper99** [MicrosoftDocs/vsts-docs#4424]
"The method you use to customize work tracking depends on the process model you subscribe to:

Inheritance: Supports WSIWIG customization, available for Azure DevOps Services and Azure DevOps Server 2019"

Don't you mean WYSIWYG instead of WSIWIG?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f1152275-e1e9-cad2-4b6d-e7bab8ed1b74
* Version Independent ID: 231b91a8-c5ac-36db-e2ae-8d837fb70e4b
* Content: [Customize your work tracking experience - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/reference/customize-work?view=azure-devops#feedback)
* Content Source: [docs/reference/customize-work.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/reference/customize-work.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@jlroper99 - Thank you for the correction. I'll update the article later today.
