### ISSUE TITLE
From a task, copying the field's value from its parent User Story

### ISSUE THREAD

**Issue by rsbaa** [MicrosoftDocs/vsts-docs#4428]
Hi,
I understand it's possible to copy a value from a work item into itself but is it possible to copy the value from a parent, like a task inheriting the value of a custom fielfds from its Parent User Story ?
I guess not but just in case I didn't see where the magic happens...
Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4107b23a-ba0a-5a1b-b689-072717cfe8ec
* Version Independent ID: 1ed09ce9-be9b-6146-9cb8-a2a50e12a3c2
* Content: [Add a custom rule to a work item type - Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/organizations/settings/work/custom-rules?view=azure-devops#feedback)
* Content Source: [docs/organizations/settings/work/custom-rules.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/settings/work/custom-rules.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@rsbaa - Thank you for your inquiry. The scenario you describe isn't supported at this time.

**Comment by WesleyWeber** [comment]
I think we should re-open this as a new feature request in the next release of Azure DevOps Web.

**Comment by buhlergroup** [comment]
Yes, this would be a nice function: Copy (Access) a field from the parent item. E.g. to overtake a funding number.
It reduces the need to write Azure functions.
