### ISSUE TITLE
Visual Studio ID Management and Permission

### ISSUE THREAD

**Issue by bnhassin** [MicrosoftDocs/vsts-docs#4429]
[Azure DevOp Auth]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 16e43dd6-5424-c25c-6b1d-be9aba62c388
* Version Independent ID: 7682284c-cdd7-b192-8803-708344776064
* Content: [Authorize Other Services](https://docs.microsoft.com/en-us/azure/devops/service-hooks/authorize?view=azure-devops)
* Content Source: [docs/service-hooks/authorize.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/service-hooks/authorize.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by thomps23** [comment]
@bnhassin Could you provide any additional information to assist us in the triage of this issue? Thank you

**Comment by bnhassin** [comment]
Following Authorisation ⤵
![Screenshot_20190613-000533](https://user-images.githubusercontent.com/1473765/59394190-b5f68480-8d76-11e9-8859-27dae3d878ae.png)
![Screenshot_20190613-003702](https://user-images.githubusercontent.com/1473765/59394258-e0484200-8d76-11e9-946a-df9cb554410d.png)
![Screenshot_20190613-003728](https://user-images.githubusercontent.com/1473765/59394286-f6ee9900-8d76-11e9-8dde-0c99ccfe1c15.png)

**Comment by WilliamAntonRohm** [comment]
@bnhassin -- thank you for replying.  Please provide additional context regarding this issue.

**Comment by WilliamAntonRohm** [comment]
I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
