### ISSUE TITLE
This option is not available in VSTS or in TFS 2018

### ISSUE THREAD

**Issue by SGStino** [MicrosoftDocs/vsts-docs#443]
There is no Retention tab in the package source settings page on both TFS 2018 and VSTS as of 2018/03/30

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 98c670aa-2abf-2f51-a80c-1f5c8d454f7b
* Version Independent ID: 84fed01a-0ffa-9cb9-1337-dc10c3bc7308
* Content: [Configure retention policies in VSTS](https://docs.microsoft.com/en-us/vsts/package/how-to/retention-policies?view=vsts)
* Content Source: [docs/package/how-to/retention-policies.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/package/how-to/retention-policies.md)
* Service: **unspecified**
* GitHub Login: @erickson-doug
* Microsoft Alias: **elbatk**

**Comment by elbatk** [comment]
hey @SGStino ! thanks for catching this - I reached out to the product team and there was a hiccup with the release of this functionality but that it will be up and running by the end of the week!

**Comment by SGStino** [comment]
hey @elbatk , that still means that the Applies to "VSTS | TFS 2018 | TFS 2017" line is incorrect and could cause confusion.
