### ISSUE TITLE
analytics.dev.azure.com Repository

### ISSUE THREAD

**Issue by scottnasello** [MicrosoftDocs/vsts-docs#4430]
[Enter feedback here]

Hello, 

when I use https://analytics.dev.azure.com/{OrganizationName}/_odata/v3.0-preview/Branches, I receive both RepositoryId and RepositoryVstsId in the output yet I don't see any reference in your model for how I can return the corresponding Repo Name. 

![image](https://user-images.githubusercontent.com/8529173/58931208-aa221700-8713-11e9-9de5-ac1d70c39413.png)

 I've tried the following on the off chance the API isn't documented but works:
* https://analytics.dev.azure.com/{OrganizationName}/_odata/v3.0-preview/Repositories
* https://analytics.dev.azure.com/{OrganizationName}/_odata/v3.0-preview/Repository
* https://analytics.dev.azure.com/{OrganizationName}/_odata/v3.0-preview/Repos

Do you have any suggestions about how I might derive the the Repo name given a Repo Id?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: df0406dd-f852-001f-eba5-a665ed4ef7a0
* Version Independent ID: 51657f61-8b0c-3132-59d4-7d876b08af6d
* Content: [Data model for the Analytics Service - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/report/extend-analytics/data-model-analytics-service?view=azure-devops)
* Content Source: [docs/report/extend-analytics/data-model-analytics-service.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/report/extend-analytics/data-model-analytics-service.md)
* Product: **devops**
* Technology: **devops-analytics**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by greggboer** [comment]
Repo data is not yet in the Analytics Service. And we only have Branch data for Branches that were referenced by Builds, or Automated Tests run as a part of a Build or Release.

Also, in the future, if you hit the end-point without entities, it will return the list of entities available:
https://analytics.dev.azure.com/%7BOrganizationName%7D/_odata/v3.0-preview/
