### ISSUE TITLE
Can't add hyperlink in Azure Boards (Azure DevOps Services)

### ISSUE THREAD

**Issue by henryrt** [MicrosoftDocs/vsts-docs#4432]
This page describes the ability to add a hyperlink from a work item just as you would add related items, but it is not possible in Azure Boards. I am using the Agile process.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba7c85b2-fb57-aefe-af67-fcdcbb94e595
* Version Independent ID: ea532ac5-f00b-d570-80b4-781190c9b4ed
* Content: [Link work items to support traceability - Azure Boards](https://docs.microsoft.com/en-gb/azure/devops/boards/queries/link-work-items-support-traceability?view=azure-devops&tabs=new-web-form#feedback)
* Content Source: [docs/boards/queries/link-work-items-support-traceability.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/boards/queries/link-work-items-support-traceability.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@henryrt - Thank you for your inquiry. If you go to the Links tab, choose Existing item, and then scroll to the Work category-- you should see the Hyperlink link type. This allows you to link to a URL. 

![image](https://user-images.githubusercontent.com/10856840/59297542-4f218000-8c3d-11e9-801a-d17f9d4d97cf.png)

**Comment by jlipford** [comment]
@KathrynEE I think the issue here is that you have to go to the links menu to see all of these options. when you click a simliar menu from the quick link on the default layout, the expanded options (which include hyperlink) are not there.

**Comment by mmuresan** [comment]
The Hyperlink type of link is not available in the Scrum process, only in Agile process.
I have no idea who decided that Scrum doesn't need hyperlinks, but Agile does.
Scrum is also a form of Agile.
How to add that type of Link in the Scrum Process? I have a lot of users asking for this.

**Comment by filipjonckers** [comment]
I understand that the **Related Work** was designed to show work items only but again, the question is how to show other links like **hyperlink** and **storyboard** on the main work item page without having to click on the Links tab to switch screen.  We have X number of related documents (use cases, screenshots, ...) on sharepoint that we need to link to a work item.  Adding one custom field with a URL is not an option as there can be more than one linked document on sharepoint/onedrive/etc 
There is really a need for a separate group listing all links (besides the separate links tab screen)

**Comment by KathrynEE** [comment]
@filipjonckers - The only way to accomplish what you are requesting is through a custom control. I found this control - https://marketplace.visualstudio.com/items?itemName=MarkHawkes.clickable-link-control-extension - in the markeplace that might meet your need. I haven't tried it myself. Other than that, you would have to create or adapt another custom control. Best regards.

**Comment by filipjonckers** [comment]
> @filipjonckers - The only way to accomplish what you are requesting is through a custom control. I found this control - https://marketplace.visualstudio.com/items?itemName=MarkHawkes.clickable-link-control-extension - in the markeplace that might meet your need. I haven't tried it myself. Other than that, you would have to create or adapt another custom control. Best regards.

Hi Kathryn, thanks for your comment!
I had a look at this extension and although it comes close .. it does only support one link for one field value, we need to be able to show multiple hyperlink and/or multiple storyboard links which are already visible in the links tab
I also looked for an existing extension which could be forked/adapted into a new extension.
I don't have any experience with this though so I hoped that someone has created this already ;-)
