### ISSUE TITLE
"Alternate" as authentication type is not supported at all - Mac OSX agent 2.144.2

### ISSUE THREAD

**Issue by spashx** [MicrosoftDocs/vsts-docs#4433]
The Mac OSX agent 2.144.2 does not support the "Alternate" choice at all:

```
Enter authentication type (press enter for Negotiate) > Alternate
Enter a valid value for authentication type.
Enter authentication type (press enter for Negotiate) > alternate
Enter a valid value for authentication type.
Enter authentication type (press enter for Negotiate) > Basic
Enter a valid value for authentication type.
Enter authentication type (press enter for Negotiate) > Exiting...
```

You should provide an updated list of options or better  the ability to get the available choices from the agent itself depending on the platform.

Regards

**Comment by thomps23** [comment]
@spashx Could you let us know which topic you were looking at to assist in triage?

**Comment by spashx** [comment]
Hi,
In this page https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/v2-windows?view=azure-devops-2019, the "Alternate" mode is specified, just below the "Download and configure the agent" chapter.

In fact "Alternate" does not work. The keyword on the command line is "alt".  I had to dive into the agent source code to find it.

**Comment by steved0x** [comment]
@spashx I apologize for the great delay, I believe this page has been updated to correct the error, if it has not, can you file a new issue and let me know exactly what line has the error and I'll get it looked at quickly. Thank you.
