### ISSUE TITLE
Prerequisites section is duplicated

### ISSUE THREAD

**Issue by KitPatterson** [MicrosoftDocs/vsts-docs#4435]
Same "Prerequisites" section appears twice. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 82d92157-ab0e-b538-c284-32c70da8e2dd
* Version Independent ID: 86d6c2eb-5931-27ee-3df9-a1d0889d510a
* Content: [Group/organize backlog items - define features and epics - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/backlogs/define-features-epics?view=azure-devops)
* Content Source: [docs/boards/backlogs/define-features-epics.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/boards/backlogs/define-features-epics.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@KitPatterson - Thank you for the correction. I'll update the topic later today.
