### ISSUE TITLE
Can't figure how to set a variable

### ISSUE THREAD

**Issue by ericoporto** [MicrosoftDocs/vsts-docs#4441]
I need to create a variable like `export TAGNUMBER=$(git describe $(git rev-list --tags --max-count=1))`, so I can have a variable `$TAGNUMBER` to use later on the Github Release Edit action . I can't seem to be able to figure out how to run a bash task and write the result to a variable.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 450ac349-5c33-6cdf-1ecd-6eb989a00334
* Version Independent ID: a7119c1a-59b2-3081-a241-e93aa0d6b4b9
* Content: [Bash task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/bash?view=azure-devops)
* Content Source: [docs/pipelines/tasks/utility/bash.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/utility/bash.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @vtbassmatt
* Microsoft Alias: **macoope**

**Comment by ericoporto** [comment]
Finally did it -> https://github.com/ericoporto/AGSNormalMap/blob/master/azure-pipelines.yml#L68

**Comment by vtbassmatt** [comment]
And for future searchers, it's doc'd here: https://docs.microsoft.com/azure/devops/pipelines/scripts/logging-commands
