### ISSUE TITLE
Update IP addresses with new IP firewall rules by June 28, 2019

### ISSUE THREAD

**Issue by gholliday** [MicrosoftDocs/vsts-docs#4442]
The last part of the page mentions:
&gt;&gt; ... and the 13.107.6.183 and 13.107.9.183 IP addresses are allowed.

The blog post at https://devblogs.microsoft.com/devops/new-ip-firewall-rules-for-azure-devops/ includes new IP address ranges that need to be added to this page:

IPv4 ranges
13.107.6.0/24
13.107.9.0/24
13.107.42.0/24
13.107.43.0/24

IPv6 ranges
2620:1ec:4::/48
2620:1ec:a92::/48
2620:1ec:21::/48
2620:1ec:22::/48

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43799c5d-2f13-cc76-a1c0-a3f850e16d4e
* Version Independent ID: 97a5b73f-faf7-f9c0-9269-fc79984616d6
* Content: [Deploy a Azure Pipelines agent on Windows - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/v2-windows?view=azure-devops#feedback)
* Content Source: [docs/pipelines/agents/v2-windows.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/agents/v2-windows.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
@gholliday I have just submitted a fix and it should be live very soon, thank you.
