### ISSUE TITLE
Be specific about the communication of MS hosted Agents

### ISSUE THREAD

**Issue by OliCSADoerr** [MicrosoftDocs/vsts-docs#4446]
Please correct the following statement, since it is not completely correct:
"The Microsoft-hosted agent pools, by default, have connectivity to Azure websites and servers running in Azure."
That does not apply, if you e. g. have a Azure Kubernetes Engine running in your own V-Net. Than you will need to have a self-hosted agent that is connect to a V-Net which is peered with the V-Net were the Kubernetes Engine is running.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 47625b86-abd5-ee15-6d61-8bcf81861b96
* Version Independent ID: be9a6174-a69b-7aed-d584-5f602fcc5eb4
* Content: [Azure Pipelines Agents - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/agents?view=azure-devops#feedback)
* Content Source: [docs/pipelines/agents/agents.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/agents/agents.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by Romiko** [comment]
I agree, what if I want to use the AzureDevops SSH task:
From: Microsoft Hosted Agent
To: Internal IP of an Azure Virtual Machine (never want to use public ip's

Is this possible with MS hosted agents?

**Comment by zackAtPEX** [comment]
Please add instructions for getting agent info without using the UI. On prem rest api doesn't look to have the methods and I'm not sure which cmd/powershell utility to use. At least include a link?

**Comment by steved0x** [comment]
@Romiko that is a good question, can you create a new issue so I can track it there? Please @ mention me when you create the issue. I believe we are working on some sample code for a similar scenario that may help you.

@zackAtPEX Do you mean for Microsoft-hosted agents? They should match the specifications given [here](https://github.com/Microsoft/azure-pipelines-agent/releases). For self-hosted agents you can use capabilities and demands to ensure that the right agent is used. I feel like I must be misunderstanding your question. Can you create a new issue to track this, and please @ mention me.

@OliCSADoerr I am updating this article to fix the part that you mention and it should be live soon.

**Comment by steved0x** [comment]
@zackAtPEX That sounds like a good idea. I will forward that to our team, and I recommend that you do the same by filing a feature request for that functionality here:

https://developercommunity.visualstudio.com/spaces/21/index.html
