### ISSUE TITLE
Run number not explained

### ISSUE THREAD

**Issue by kine** [MicrosoftDocs/vsts-docs#4447]
Hello, seems that the page is just copy of the original text from https://docs.microsoft.com/en-us/azure/devops/pipelines/build/options?view=azure-devops page, but the Run ID is not explained at all. It is not used in the exmaple format, it is not exmplained in the token table, it is not part of the yaml example. 

How can I use the Run ID at all?

Please, fix this copy/pasted text to really explain what should be explained on this page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a57f8545-bb15-3a71-1876-3a9ec1a59b93
* Version Independent ID: 28c87c8d-c28d-7493-0c7c-8c38b04fbcd7
* Content: [Run number - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/run-number?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/process/run-number.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/run-number.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by svsvirid** [comment]
trying shows that $(Build.BuildId) is filled in (with number like 194218)  while $(Release.ReleaseId) stays empty. That causes 404 in calls like Release GET,  but Build Get api call with BuildID number works fine. That makes me think that Run number/ID is a BuildID.

**Comment by JoeBrockhaus** [comment]
The explanation here (for the mysterious 'Run ID') may simply be that it's a typo. 

Under [Example](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/run-number?view=azure-devops&tabs=yaml#example) the bullet `Run ID: 752` should likely be `Build ID: 752`, as the value `752` _is referred to_ lower under [Tokens](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/run-number?view=azure-devops&tabs=yaml#tokens) as the value for `$(BuildID)`.

**Comment by juliakm** [comment]
In Microsoft Team Foundation Server (TFS) 2018 and previous versions, runs are called builds.  I'll update the documentation line @JoeBrockhaus identified to say Build ID.
