### ISSUE TITLE
Field Length

### ISSUE THREAD

**Issue by jeffpatton1971** [MicrosoftDocs/vsts-docs#4449]
It would be nice to have an understanding of field restrictions, you have naming restrictions, but for example, how much text could be placed in a multi-line description? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd295aab-1529-fd48-74a8-62243ee940ce
* Version Independent ID: 01fcb7de-3bcd-9a8e-1813-c25dcdcf6acd
* Content: [FIELD (Definition) element reference - Azure DevOps & TFS](https://docs.microsoft.com/en-us/azure/devops/reference/xml/field-definition-element-reference?view=azure-devops)
* Content Source: [docs/reference/xml/field-definition-element-reference.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/reference/xml/field-definition-element-reference.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@jeffpatton1971 - Thank you for your inquiry.  There is no restriction on the number of characters you can enter into a PlainText or HTML field. There is a restriction for the String field of 255 characters.

- PlainText: Supports entry of a text string that can contain more than 255 Unicode characters.

- String: Supports entry of a text string that can contain up to 255 Unicode characters. Use a String field for a label or other short text string up to one line long.
