### ISSUE TITLE
Deleting Published Wiki

### ISSUE THREAD

**Issue by yashkv1** [MicrosoftDocs/vsts-docs#4451]
How do I delete published wiki? I would like keep the code wiki only. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 59cb387d-5f46-0743-efbb-c393c4e5bd85
* Version Independent ID: cb6912c2-e640-f992-0a1f-5cbbe88d87dc
* Content: [Differences between provisioned and published wikis - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/project/wiki/provisioned-vs-published-wiki?view=azure-devops)
* Content Source: [docs/project/wiki/provisioned-vs-published-wiki.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/project/wiki/provisioned-vs-published-wiki.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @yashkv1, Thanks for reaching out. First, [unpublish the wiki](https://docs.microsoft.com/en-us/azure/devops/project/wiki/wiki-select-unpublish-versions?view=azure-devops#unpublish-a-published-wiki). Please let me know if you need any further clarification and I'll be happy to provide. Thanks!

**Comment by yashkv1** [comment]
After unpublishing, I would like to set the code wiki as default. How should I do that?

**Comment by chcomley** [comment]
@yashkv1, great question. I've added @adramasu for guidance please! Thank you!

**Comment by ironstine** [comment]
Similar to @yashkv1, I would like to completely remove the Project Wiki (which was created in error) and use only Code Wikis. The Project Wiki is confusing to our users, despite training them to only use the Code Wikis we still have users that continue to create content in The Project Wiki. We also tried removing 'Read' permissions to solve this issue however users were presented with the message 'You don't have access to any wiki'.

Is there a way to 1) remove the Provisioned wiki and 2) make Publish code as wiki the default?

**Comment by yashkv1** [comment]
I found a solution. I have to try if this will work for deleting Provisioned wiki.

**Comment by adramasu** [comment]
You cannot delete a provisioned wiki. However, you can delete the underlying repo  of the wiki by following the steps in this document [DELETE PROJECT WIKI.docx](https://github.com/MicrosoftDocs/vsts-docs/files/3284289/DELETE.PROJECT.WIKI.docx). This will in effect delete the provisioned wiki. 
As for preventing the creation, you can deny "create repo" permission to users who should not create a provisioned wiki.

**Comment by chcomley** [comment]
I've added the process for deleting a wiki repo, from the previous comment, to the article. The PR is complete, so it should be live within a few hours. Do let us know if you have any further questions!

**Comment by kosherhog** [comment]
I'm attempting to use this process in powershell using invoke-restmethod, but I'm getting an error indicating DELETE is not supported on the controller.  Is there something I'm missing?  Any chance of just updating the az devops CLI to not error out when attempting to delete a provisioned wiki?

**Comment by gd-ksc** [comment]
Thanks for the reference info, posted here.

Following is the procedure I've used, successfully:

#### Setup: Personal Access Token
- Go to: User Settings
- Select: Personal access tokens
- Select: New Token
- Select: Name: whatever
- Select: Expiration
- Select: Custom define
- Select: the calendar
- Select: Go to today
- Select: Full access
- Select: Create
- Copy: the token
- Select: Close

#### Use: curl, to access the API
- Get: the repositoryId

``
curl -vvv -u myuser@mydomain:token -k -X GET https://dev.azure.com/MY-ORGANIZATION/MY-PROJECT/_apis/wiki/wikis?api-version=5.0
``

- Delete: the repositoryId

``
curl -vvv -u myuser@mydomain:token -k -X DELETE https://dev.azure.com/MY-ORGANIZATION/MY-PROJECT/_apis/git/repositories/{repositoryId}?api-version=5.0
``

**Comment by kosherhog** [comment]
Perfect!  Thanks for the assist here!
