### ISSUE TITLE
Need to make it clear that the highest authorization/security access for a PAT is limited to what the creator of the PAT has.

### ISSUE THREAD

**Issue by thoaingan** [MicrosoftDocs/vsts-docs#4453]
We've had a few customers not understanding that the PATs can only access/do what the creators of those PATs are allowed to and get extremely nervous about PATs in their Azure DevOps org. Please make this more clear in our documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2bfea574-db69-a5fd-37fe-64ecfdac502a
* Version Independent ID: 4037d475-f194-2ac9-ffd6-70530fc3140a
* Content: [Authenticate with personal access tokens - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/use-personal-access-tokens-to-authenticate?view=azure-devops)
* Content Source: [docs/organizations/accounts/use-personal-access-tokens-to-authenticate.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/accounts/use-personal-access-tokens-to-authenticate.md)
* Product: **devops**
* Technology: **devops-accounts**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @thoaingan, Thank you for reaching out. We will certainly add some clarity to the docs - I've created a user story to capture this task. Thanks.

**Comment by chcomley** [comment]
Hi @thoaingan, The update has been published. Thanks again for your feedback, we appreciate it. I added the following: "Since PATs are an alternate form of user authentication, using a PAT gives you the same access level. If you create a PAT with a narrower scope, your access is limited to that particular scope."
