### ISSUE TITLE
Support multiple schedules in stage trigger

### ISSUE THREAD

**Issue by cannehag** [MicrosoftDocs/vsts-docs#4459]
Is there a plan to support multiple schedules in a stage trigger ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d9e313c5-9120-9172-bc27-c21d10fcd5ae
* Version Independent ID: 1a837182-591f-3cbc-1632-7b50d857b13c
* Content: [Release triggers for stages, branches, and pipelines - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/triggers?view=azure-devops#feedback)
* Content Source: [docs/pipelines/release/triggers.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/release/triggers.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by thomps23** [comment]
@cannehag We have our feature roadmap published [here](https://docs.microsoft.com/azure/devops/release-notes/). If you don't find what you're looking for you can always [submit your idea]( https://developercommunity.visualstudio.com/content/idea/post.html?space=21) here.
