### ISSUE TITLE
Is this VSTS task deprecated?

### ISSUE THREAD

**Issue by Kalaicompute** [MicrosoftDocs/vsts-docs#446]
Hi,
        I couldn't see this task(Update Service Fabric App Version) in VSTS now. Is this task deprecated? I see another similar task named "Update Service Fabric Manifests" task. But, I couldn't find any documentation about it. Please clarify. Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b41ba27-633a-37d4-ce78-a1444a99b5b1
* Version Independent ID: 387739fb-276b-d0c9-4848-45426b6e2319
* Content: [Update Service Fabric App Versions build task VSTS and TFS](https://docs.microsoft.com/en-us/vsts/build-release/tasks/utility/service-fabric-versioning?view=vsts)
* Content Source: [docs/build-release/tasks/utility/service-fabric-versioning.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/build-release/tasks/utility/service-fabric-versioning.md)
* Service: **unspecified**
* GitHub Login: @erickson-doug
* Microsoft Alias: **alewis**

**Comment by alexhomer1** [comment]
Thank you for your feedback. I will pass this on to the product team and update the topic based on their response.

**Comment by alexhomer1** [comment]
A new version of the more general Azure Service Fabric task is currently being developed that will incorporate a wide range of functions.
