### ISSUE TITLE
Deployment from Azure Container Registry (or any other private one)

### ISSUE THREAD

**Issue by Leon99** [MicrosoftDocs/vsts-docs#4460]
This page doesn't explain how to deploy a container from an Azure Container Registry (or any other that requires authentication).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 29c94df7-9de9-ea1a-8b77-d1e6023694dc
* Version Independent ID: a525989e-2e0a-0399-556e-9011ee95da4e
* Content: [Azure App Service Deploy task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-rm-web-app-deployment?view=azure-devops)
* Content Source: [docs/pipelines/tasks/deploy/azure-rm-web-app-deployment.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/deploy/azure-rm-web-app-deployment.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by RoopeshNair** [comment]
@Leon99  - If you have credentials configured in app service. You can update the image using the task. We don't support updating the credentials using the task. If that's what your looking for

**Comment by Dimchord** [comment]
When deploying manually from an Azure container registry, you don't need the credentials (just select Image source -> Azure container registry). However with using this task, it seems that the Image source is set to "Docker hub" instead. Can you force it to use Azure CR?
