### ISSUE TITLE
How to set task condition to continue on failure?

### ISSUE THREAD

**Issue by lukewis** [MicrosoftDocs/vsts-docs#4461]
I see that the task condition can be set to "Even if a previous dependency has failed, unless the run was canceled", but I can't figure out how to configure this.  Maybe an example could be added to the page?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8098f527-ebdf-60d5-3989-5228b7a207c1
* Version Independent ID: ce27c817-9599-00ef-5af2-3ac1dbad8dc6
* Content: [Build and Release Tasks in Azure Pipelines and TFS - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/tasks?view=azure-devops&tabs=yaml#feedback)
* Content Source: [docs/pipelines/process/tasks.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/tasks.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by lukewis** [comment]
Aside from updating the documentation, if anyone had a few minutes to give a yml snippet here of the solution that would be awesome!

**Comment by johnschult** [comment]
Not a single example of the conditions are on this page.

**Comment by jasoncabot-ms** [comment]
@lukewis - I think you want:

```
steps:
- task: ...
  condition: succeededOrFailed()
```

Which should run unless cancelled. The condition syntax is an expression, which you can read more of in the docs about [conditions](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/conditions?view=azure-devops) or [expressions](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/expressions?view=azure-devops)
