### ISSUE TITLE
JAVA setup

### ISSUE THREAD

**Issue by strahinjanis** [MicrosoftDocs/vsts-docs#4462]
The part:
"During installation, the wizard sets the JAVA_HOME environment variable to point to the JRE installation folder. The configuration wizard may fail to detect an existing JRE installation if it is not correctly configured, or if the JAVA_HOME setting points to an earlier version than that required by Search."
seems to be pretty wrong in some aspects, in my opinion, and her is it why:
why should installer create JAVA_HOME if JRE is needed (not JDK), instead of JRE_HOME? This is a bad practice, I'd like to point to: https://confluence.atlassian.com/doc/setting-the-java_home-variable-in-windows-8895.html as a good one.
This simple works if you have an empty box, where you advice ZuluJDK, but in many cases you have servers with multiple roles (specially in EXpress case), so it would be worth to consider that already JRE/JDK (or both) are in place with proper setup (all env. variables) so in that sense setup should be tested, which obviously wasn't the case, or you intentionally wanna ignore the proper (JRE) setup.
Thank you,
Stan

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be0bdbf7-3132-9007-6c6a-368c5bcb0f3d
* Version Independent ID: 58118f61-f88f-24b9-b785-d8f9d8a1fefd
* Content: [Administer code, wiki and workitem search](https://docs.microsoft.com/en-us/azure/devops/project/search/administration?view=tfs-2018&tabs=new-nav#feedback)
* Content Source: [docs/project/search/administration.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/project/search/administration.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by KathrynEE** [comment]
@strahinjanis - Thank you for your feedback and inquiry. After conferring with one of the engineers, I'm updating the article with the following note: 

We don't advise installing Elasticsearch on a machine where resources are shared, especially on a large enterprise environment with multiple application tiers. Instead, we recommend setting up Elasticsearch in a separate dedicated machine. In that way, the JAVA environment isn't shared across machines for other purposes.
