### ISSUE TITLE
Deployment outputs could use an example

### ISSUE THREAD

**Issue by MisinformedDNA** [MicrosoftDocs/vsts-docs#4463]
For instance it is not obvious that you need to wrap the object in a string.

So if one outputs to a variable `Outputs`, then they would parse the value with `ConvertFrom-Json '$(Outputs)`

Also, this value should likely be assigned and then used to find an ARM output, such as databaseName, like

```powershell
$outputs = ConvertFrom-Json '$(Outputs)
$outputs.databaseName
```

and if they wanted to make the value visible to subsequent tasks, they could do 

```powershell
Write-Host "##vso[task.setvariable variable=databaseName;]$outputs.databaseName"
```

Also, will this work with outputs of type `securestring`?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a59ea95e-b51a-e529-37a8-215e383c9a0b
* Version Independent ID: f1afdb0e-f090-3193-9bb8-ce5952016768
* Content: [Azure Resource Group Deployment task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-resource-group-deployment?view=azure-devops)
* Content Source: [docs/pipelines/tasks/deploy/azure-resource-group-deployment.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/deploy/azure-resource-group-deployment.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by RoopeshNair** [comment]
@N-Usha - can you please take a look?

**Comment by jochenvanwylick** [comment]
+1 - I'm interested how to continue using the output variable in a subsequent Azure CLI task!

**Comment by N-Usha** [comment]
@MisinformedDNA - Yes, You can use the “ConvertFrom-Json” PowerShell cmdlet to parse the JSON object and access the individual output values. 
However [ARM template syntax](https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-group-authoring-templates#outputs) states that output variables of type securestring will be masked and can't be used as an input for another deployment . Instead of passing secure information between deployments reference to that secret should be used. 
Hope that helps.

**Comment by N-Usha** [comment]
@jochenvanwylick - Output variables of a task are accessible in all the subsequent tasks within the same job including Az cli task. You can refer it using $(variable_name) that you provide within the task  field "Deployment outputs". Hope that helps.

**Comment by MisinformedDNA** [comment]
It does. And I'd like to see this information added/clarified in the documentation.

**Comment by jochenvw** [comment]
> @jochenvanwylick - Output variables of a task are accessible in all the subsequent tasks within the same job including Az cli task. You can refer it using $(variable_name) that you provide within the task field "Deployment outputs". Hope that helps.

Hi @N-Usha, thanks for getting back to me ! Indeed, `$(var)` is available in the subsequent task but I needed some trickery to actually make it useful for me. It took me some effort to make it valid JSON and queryable using `jq`. In case you're interested: [https://stackoverflow.com/questions/57264556/prevent-quotes-from-disappearing-in-json-in-between-azure-devops-tasks/57388706#57388706](https://stackoverflow.com/questions/57264556/prevent-quotes-from-disappearing-in-json-in-between-azure-devops-tasks/57388706#57388706)

**Comment by RoopeshNair** [comment]
#5163

**Comment by N-Usha** [comment]
Documentation updated: https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/AzureResourceGroupDeploymentV2#deployment-outputs
