### ISSUE TITLE
Pipelines Accessing Repos of Same Project

### ISSUE THREAD

**Issue by Decker-Russell** [MicrosoftDocs/vsts-docs#4465]
I am attempting to clone repos from same project into a pipeline. This is confusing me :
"Azure Pipelines must be granted access to your repositories to display them, trigger their builds, and fetch their code during builds. If the repository that you wish to build is in the same project as your pipeline, you're all set. Your builds will automatically have access to the repository. "

Do I need to generate a PAT to accomplish this or is there a setting in DevOps to grant pipelines access to the other repos? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8b846aea-82f7-a988-67d8-1b5e74b61ed2
* Version Independent ID: 2d632729-bb33-c0a0-c996-e1d8e86c2e23
* Content: [Build Azure Repos Git repositories - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/azure-repos-git?view=azure-devops#feedback)
* Content Source: [docs/pipelines/repos/azure-repos-git.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/repos/azure-repos-git.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by thomps23** [comment]
@apawast Could you review and see if the documentation could be clear here?

**Comment by steved0x** [comment]
@Decker-Russell For cloning repos in the same project in your pipeline, you shouldn't need to do anything special, in a classic editor pipeline you would be running under project scope or project collection scope (and have [this](https://developercommunity.visualstudio.com/content/problem/213410/allow-scripts-to-access-the-oauth-token-option-dis.html#reply-214483) setting checked if you are using a script), and in YAML pipelines you are running under project scope, and the token goes along by default to your scripts.

Which type of pipeline do you have, what is happening when you try to clone the other repos, and what method are you using to clone them?
