### ISSUE TITLE
Multi-job output variables across Stages?

### ISSUE THREAD

**Issue by cwiederspan** [MicrosoftDocs/vsts-docs#4466]
In the "Set a multi-job output variable" section above, this definitely works across jobs within the same Stage, but there's no documentation about whether or not this can be used across jobs within different stages. Can you confirm one way or another, and also clarify within the documentation?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd7e0bd3-1f7d-d7b6-cc72-5ef63c31b46a
* Version Independent ID: dae87abd-b73d-9120-bcdb-6097d4b40f2a
* Content: [Variables - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch#feedback)
* Content Source: [docs/pipelines/process/variables.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/variables.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by PaulVrugt** [comment]
I'm using a [setvariable task](https://marketplace.visualstudio.com/items?itemName=jessehouwing.jessehouwing-vsts-variable-tasks&targetId=7e5e1ac1-118b-4ead-b4ae-3f7165fe853c&utm_source=vstsproduct&utm_medium=ExtHubManageList) to set a variable. I now need to set this variable in EACH job. I too would like to be able to do this ONCE, and use the set variables across jobs in multiple stages. The only way I can think of how to do that, is to create a stage with once job that sets the variable, and save this variable. But then I need some way to access this variable across stages.

**Comment by JohnTortugo** [comment]
FYI: that features is being worked on. The workaround for now is to persist the variable in an artifact.

**Comment by juliakm** [comment]
Right now, you cannot have multi-job output variables that work across stages. Updating docs to clarify.
