### ISSUE TITLE
Removing firewall rules where server lock set

### ISSUE THREAD

**Issue by haymansfield** [MicrosoftDocs/vsts-docs#4467]
I've just added a lock to my SQL server as this seemed a prudent action.

This is now causing the removal of the firewall rule to fail. Is there a workaround here, or is the defined process above incompatible with locks?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cd85890a-ccba-8697-b406-b662aabeb27f
* Version Independent ID: a1d371df-c0a0-1cd6-37f8-4b60913a2e97
* Content: [Deploy to Azure SQL Database - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/targets/azure-sqldb?view=azure-devops&tabs=yaml#feedback)
* Content Source: [docs/pipelines/targets/azure-sqldb.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/targets/azure-sqldb.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by RoopeshNair** [comment]
@haymansfield - can you please share your buiid/release debug log files

**Comment by Ajay-MS** [comment]
@haymansfield - if you are still facing this issue please share debug logs.

**Comment by RoopeshNair** [comment]
Closing as there is no response for more than 20+ days. Please re-open if the issue isn't resolved
