### ISSUE TITLE
Incorrect information

### ISSUE THREAD

**Issue by claudioandre-br** [MicrosoftDocs/vsts-docs#4468]
The webpage [1] states that for a "public project" it is granted "10 free Microsoft-hosted parallel jobs that can run for up to 360 minutes (6 hours) each time, with no overall time limit per month."

My project and my repository are public (in fact, Open Source):

Regardless, I see in my job runs:
"The job running on agent Hosted Agent has exceeded the maximum execution time of 60. ..."

It also states that:
"When the free tier is no longer sufficient:
\- Public project: Contact us to get your free tier limits increased."

I do not want any increase in time. But, my project and my repository are public and Open Source. So:
- is the documentation wrong?
- ~~contact who?~~
- ~~what rule am I breaking?~~

[1] https://docs.microsoft.com/en-us/azure/devops/pipelines/licensing/concurrent-jobs?view=azure-devops

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c6a488b-88f6-dff6-e2ee-402167e17ad4
* Version Independent ID: 9a4dedda-e82c-2833-f28c-5ab346fb1b38
* Content: [Parallel jobs in Azure Pipelines - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/licensing/concurrent-jobs?view=azure-devops)
* Content Source: [docs/pipelines/licensing/concurrent-jobs.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/licensing/concurrent-jobs.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by claudioandre-br** [comment]
BTW: confirmed, I am in the free tier (the documentation wrong):

![Captura de tela de 2019-06-08 16-55-01](https://user-images.githubusercontent.com/1702923/59151707-4139e800-8a0e-11e9-8b66-1bcfd951cbb1.png)

**Comment by thomps23** [comment]
@claudioandre-br Thanks for doing the extra work to confirm the doc issue.

**Comment by claudioandre-br** [comment]
It is solved now. Thanks.
