### ISSUE TITLE
Checkout Path

### ISSUE THREAD

**Issue by rlvandaveer** [MicrosoftDocs/vsts-docs#4469]
This part of the article, https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/pipeline-options-for-git?view=azure-devops#checkout-path, seems to be incorrect or incomplete. There isn't any property in the UI to specify a path for checkout. Specifying `checkout` at the root of a YAML pipeline results in green squiggles in the web UI and an error when the pipeline runs: `47: "/<path-to.yml> (Line: <line_number>, Col: <column_number>): Unexpected value 'checkout'"`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 800c5477-b39f-48e6-6f9c-aa7994b2ec2a
* Version Independent ID: db9e2e97-d44d-734e-6a6f-b01f60f01c95
* Content: [Options for Git repositories - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/pipeline-options-for-git?view=azure-devops#checkout-path)
* Content Source: [docs/pipelines/repos/pipeline-options-for-git.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/repos/pipeline-options-for-git.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
@rlvandaveer There is no option to set the path in a classic editor pipeline, that option is only available for YAML pipelines. I can clarify that in the documentation.

However, it sounds like you also tried to set the checkout path in a YAML pipeline, and received some error, can you share any more details on that? Or did I misunderstand the original question.

To specify the checkout step (and modify the default path) you use the checkout step and specify the relative path there:

https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema#checkout

**Comment by rlvandaveer** [comment]
@steved0x Classic pipelines have a different setting, 'don't sync sources' or something similar. I was trying to use `checkout` in a YAML pipeline and had some difficulties from being relatively new to YAML pipelines and the lack of examples or further links in the article. I think including an example or the link you referenced above, would go a long way towards making the article better.
