### ISSUE TITLE
Ability to clone variable groups

### ISSUE THREAD

**Issue by jeffhebrank** [MicrosoftDocs/vsts-docs#447]
It would be cool to be able to clone variable groups. I want to create a group for my dev environment, clone it for my production environment so it has the exact same variables, and then update the variable values.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4827aa99-ae62-bd63-6f2f-a87a4065ed27
* Version Independent ID: c9e461ee-7f42-3503-9460-18fa3a807bbb
* Content: [Variable groups for VSTS and TFS](https://docs.microsoft.com/en-us/vsts/build-release/concepts/library/variable-groups?view=vsts)
* Content Source: [docs/build-release/concepts/library/variable-groups.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/build-release/concepts/library/variable-groups.md)
* Service: **unspecified**
* GitHub Login: @erickson-doug
* Microsoft Alias: **ahomer**

**Comment by BharathMannem** [comment]
I echo jeffhebrank, even i am looking for this change.

**Comment by alexhomer1** [comment]
Thank you for your feedback. I have passed the comment on to the product development team and will advise you of their response.

**Comment by alexhomer1** [comment]
The product team have asked that you post the request on UserVoice (https://visualstudio.uservoice.com/forums/330519-team-services?category_id=145269). It seems a reasonable suggestion, and can be implemented if there are sufficient votes. Thank you!

**Comment by TheBeardedLlama** [comment]
@alexhomer1 I'm sorry, but this is standard behaviour; we should not have to "vote" for it; it should be there already; cloning/importing/exporting should always be part of the MVP when it comes to build/release configuration et al

**Comment by livioos** [comment]
Exactly. It's not professional to define from the blank list Variable Groups on each projects. Is non sense.

**Comment by livioos** [comment]
Import and Export Variable Groups is must-be feature. I think that Variable Groups should be defined outside the particular project.

**Comment by alexhomer1** [comment]
Thank you. I will pass on your comments.

**Comment by Abbyjeet** [comment]
Octopus Deploy has this feature since a long time. As @TheBeardedLlama said, this feature should be standard feature of this system and we should not have to request for it. Think from the user's perspective. This feature, exporting and  ability to specify multiple environment scopes to each variable - should have been included by now.

**Comment by kirylbokach** [comment]
Badly needed this feature as well. So went ahead and created a small utility to copy variable groups. Please feel free to use: https://github.com/AssureCare/vststools

**Comment by livioos** [comment]
Thanks. I'll try this weekend.



2018-05-18 18:39 GMT+02:00 Kiryl Bokach <notifications@github.com>:

**Comment by TheBeardedLlama** [comment]
cheers @kirylbokach 
I'll give it a go at some point and give you feedback

**Comment by rituraj190** [comment]
Clone feature should be there for variable group.

**Comment by Abbyjeet** [comment]
> The product team have asked that you post the request on UserVoice (https://visualstudio.uservoice.com/forums/330519-team-services?category_id=145269). It seems a reasonable suggestion, and can be implemented if there are sufficient votes. Thank you!

Really! keep moving the issue from one place to another, then to another, rather than solving the issue!!
