### ISSUE TITLE
Failed Authentication for git push

### ISSUE THREAD

**Issue by Brucius** [MicrosoftDocs/vsts-docs#4471]
Hi, I was trying out the labs with Azure Devops and followed this documentation to clone the repo with PAT. But when I made some changes to the code and push to master branch, I keep getting authentication failed. message.

```
&gt; git push origin master:master
fatal: Authentication failed for 'https://orgName:pat@dev.azure.com/pagerops/partsUnlimited/_git/partsUnlimited/'
```
Pull was ok for me though.
```
&gt; git pull --tags origin master
From https://dev.azure.com/orgName/partsUnlimited/_git/partsUnlimited
 * branch            master     -&gt; FETCH_HEAD
```
Any idea what's causing this and the remedy to this problem?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2bfea574-db69-a5fd-37fe-64ecfdac502a
* Version Independent ID: 4037d475-f194-2ac9-ffd6-70530fc3140a
* Content: [Authenticate with personal access tokens - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/use-personal-access-tokens-to-authenticate?view=azure-devops)
* Content Source: [docs/organizations/accounts/use-personal-access-tokens-to-authenticate.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/accounts/use-personal-access-tokens-to-authenticate.md)
* Product: **devops**
* Technology: **devops-accounts**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @Brucius, t\Thanks for reaching out. I'm following up on this and will get back to you. Thanks!

**Comment by Brucius** [comment]
Seems like I got it working with a work around by re-cloning the repo using the below command. So will have to use username in the HTTPS URL and not the default clone command from the repo itself.
```git clone https://username@dev.azure.com/orgName/partsUnlimited/_git/partsUnlimited```

**Comment by chcomley** [comment]
I'm so glad you got it working. Thanks for letting me know. In the future, if you have an issue with the product, you can go [here](https://visualstudio.microsoft.com/vs/support/#talktous) to get technical support or submit an idea, etc. Have a great day!
