### ISSUE TITLE
unauthorized: authentication required

### ISSUE THREAD

**Issue by kcox1021** [MicrosoftDocs/vsts-docs#4473]
I agree with tmciver's comment that there is not enough information provided in this documentation to get build/push working from an Azure DevOps pipeline.

I have created a Docker registry service connection (named 'MyContainerRegistry') that refers to my Azure Container Registry, and this service connection has been made available to all pipelines.

My azure-pipelines.yml includes a Docker@2 login task followed by a Docker@2 buildAndPush task, as documented on this page.  However, when I queue the pipeline, I notice that the login task produces no real log output (other than a banner), making me wonder whether it is really doing anything.  Here is the full log output of that task:

##[section]Starting: Login to ACR
==============================================================================
Task         : Docker
Description  : Build or push Docker images, login or logout, or run a Docker command
Version      : 2.152.3
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/build/docker
==============================================================================
##[section]Finishing: Login to ACR

The buildAndPush task successfully builds the image, but then fails with an "unauthorized: authentication required" message when attempting to push the image to my ACR.  Here are the relevant logs:

[command]/usr/bin/docker push keycloakdemocontainerregistry.azurecr.io/sample-app:latest
The push refers to repository [keycloakdemocontainerregistry.azurecr.io/sample-app]
7434b1b4d0ea: Preparing
ea06a73e56fc: Preparing
22c458a3ff08: Preparing
6270adb5794c: Preparing
unauthorized: authentication required
##[error]unauthorized: authentication required
##[error]/usr/bin/docker failed with return code: 1
##[section]Finishing: Build and Push

What else do I need to do to successfully authenticate with the ACR besides establishing the Docker registry service connection (which I've done)?

Here are the tasks in my azure-pipelines.yml:

steps:
- task: Docker@2
  displayName: Login to ACR
  inputs:
    command: login
    containerRegistry: MyContainerRegistry
- task: Docker@2
  displayName: Build and Push
  inputs:
    command: buildAndPush
    containerRegistry: MyContainerRegistry
    repository: sample-app
    tags: |
      latest

Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d9dbf88-7e55-d427-145e-d36b04fb197f
* Version Independent ID: a3f30c00-817c-9c05-7a57-3f2bf618821e
* Content: [Docker task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/docker?view=azure-devops#feedback)
* Content Source: [docs/pipelines/tasks/build/docker.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/build/docker.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @thomps23
* Microsoft Alias: **shasb**

**Comment by andreitoupinets** [comment]
I had same problem yesterday without any changes from my side, I recreate `Service connection` for ACR and tasks work now. I figured it out when I clicked "Update service connection", but its failed with exception.

**Comment by JonKragh** [comment]
Is this a confirmed issue with Microsoft? Both managed identity and explicit logins to ACR in the service connections do not authenticate with ACR from Azure DevOps.

**Comment by shashankbarsin** [comment]
I'm unable to reproduce this issue as the Docker registry service connection I configured for a private ACR registry worked fine when I tried. Based upon how @andreitoupinets mentioned it worked fine when he recreated service connection, it may be the case that the new service principal that was created to back the service connection got it working again. So it may be the case that the service principal backing the older service connection was either deleted or the permissions revoked for access to the ACR registry. @kcox1021, @JonKragh can you try recreating the service connection from your logged in identity so that a new service principal gets created?
