### ISSUE TITLE
No context menu

### ISSUE THREAD

**Issue by johnwc** [MicrosoftDocs/vsts-docs#4474]
I am trying to convert a fairly new project from Basic to Agile, but I do not get any context menu for the project. Is there something else I need to do prior?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 365bff0e-8532-ae8a-f1c9-37ea7017e5b1
* Version Independent ID: a324129d-0edb-00ce-1217-819be9fda4f6
* Content: [Change process from Basic to Agile - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/organizations/settings/work/change-process-basic-to-agile?view=azure-devops)
* Content Source: [docs/organizations/settings/work/change-process-basic-to-agile.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/settings/work/change-process-basic-to-agile.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @danhellem
* Microsoft Alias: **kaelli**

**Comment by danhellem** [comment]
@johnwc we are going to be releasing this feature in the next 3-4 weeks. We do have a private preview if you want to try it now. Just email me directly at dahellem@microsoft.com
