### ISSUE TITLE
Option Side Effects

### ISSUE THREAD

**Issue by exwindchiller** [MicrosoftDocs/vsts-docs#4478]
It would be helpful if the documentation stated behavioral side-effects caused by enabling options.  For example, enabling code coverage, inserts the 'clean' goal into the Maven goals list when Maven is called.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 589e076c-9f67-77df-3204-4f549566f21b
* Version Independent ID: 2e51ef13-8fd3-1397-82f0-27c92f1ccee5
* Content: [Maven build and release task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/maven?view=azure-devops#feedback)
* Content Source: [docs/pipelines/tasks/build/maven.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/build/maven.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @DavidStaheli
* Microsoft Alias: **dastahel**

**Comment by davidstaheli** [comment]
Thanks for suggesting this.  The docs have been updated and will be live within a few days.

**Comment by exwindchiller** [comment]
Thanks.  That is helpful, but it would also be helpful to know why 'clean' is forced when Code Coverage is enabled.  Why isn't 'clean' a checkbox option related to enabling Code Coverage?
The forced 'clean' is causing a real problem now that I need to enable Code Coverage.
