### ISSUE TITLE
Missing options

### ISSUE THREAD

**Issue by jessehouwing** [MicrosoftDocs/vsts-docs#448]
Based on examples on the vsts-task repository it seems that jsonpath and xpath are also available as functions for conditionals.
https://github.com/Microsoft/vsts-tasks/blob/8027c121c20250d35bd16218dc930b16033fb54e/docs/authoring/servertaskauthoring.md

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f151218-9a11-0078-e038-f96198a76143
* Version Independent ID: 09c4d032-62f3-d97c-79d7-6fbfd89910e9
* Content: [Conditional task expressions](https://docs.microsoft.com/en-us/vsts/build-release/concepts/process/conditions?view=vsts)
* Content Source: [docs/build-release/concepts/process/conditions.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/build-release/concepts/process/conditions.md)
* Service: **unspecified**
* GitHub Login: @erickson-doug
* Microsoft Alias: **alewis**

**Comment by trailmax** [comment]
Is it possible to check if tag is applied to a git-commit and go from there? Here is a scenario: I would like to push to nuget feed a release package - this should only happen when commit is on master branch with tag applied.

**Comment by vtbassmatt** [comment]
Those functions are available in task completion context (documented in the file you linked). Those functions aren't available in other expression contexts.
