### ISSUE TITLE
There are no details about the environment keyword

### ISSUE THREAD

**Issue by steveculshaw** [MicrosoftDocs/vsts-docs#4485]
The article on this page https://devblogs.microsoft.com/devops/whats-new-with-azure-pipelines/ mentions an environment keyword, but there are no details ??

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7458d5b2-1bb7-7d87-7ce6-2b0c430b0155
* Version Independent ID: edf5bbd3-a3f0-5426-e985-31290f8afd05
* Content: [YAML schema - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema#stage)
* Content Source: [docs/pipelines/yaml-schema.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/yaml-schema.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @vtbassmatt
* Microsoft Alias: **macoope**

**Comment by RoopeshNair** [comment]
More about Environments [here](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/environments?view=azure-devops)

**Comment by vtbassmatt** [comment]
@RoopeshNair when will environments (and other deployment stuff) land in the [YAML schema](https://docs.microsoft.com/azure/devops/pipelines/yaml-schema) doc?
