### ISSUE TITLE
Is there an online test tool to test conditionals?

### ISSUE THREAD

**Issue by jessehouwing** [MicrosoftDocs/vsts-docs#449]
That would be really helpful. Or even a "test" button in the task UI.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f151218-9a11-0078-e038-f96198a76143
* Version Independent ID: 09c4d032-62f3-d97c-79d7-6fbfd89910e9
* Content: [Conditional task expressions](https://docs.microsoft.com/en-us/vsts/build-release/concepts/process/conditions?view=vsts)
* Content Source: [docs/build-release/concepts/process/conditions.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/build-release/concepts/process/conditions.md)
* Service: **unspecified**
* GitHub Login: @erickson-doug
* Microsoft Alias: **alewis**

**Comment by chrisrpatterson** [comment]
You can use postman or similar tool to post to this api
https://<accountname>.visualstudio.com/_apis/distributedtask/inputvalidation

with this body

{"inputs":{"expression":{"type":"expression","value":"VALUE"}}}

**Comment by Erchamion** [comment]
I'm receiving a page not found when calling the api.

**Comment by vtbassmatt** [comment]
Chris's response was missing escape characters. Also, the domain name has changed:

`POST https://dev.azure.com/{your_organzation_name}/_apis/distributedtask/inputvalidation`

Body:
```json
{
  "inputs": {
    "expression": {
      "type": "expression",
      "value": "{your expression to test}"
    }
  }
}
```
