### ISSUE TITLE
Service account token expires frequently

### ISSUE THREAD

**Issue by jleach** [MicrosoftDocs/vsts-docs#4491]
The `AppStoreRelease@1` task works fine but the service account requires a token from `fastlane` that expires frequently; mine seem to last a day at most. This renders the task pretty useless if we have to go back every day and manually refresh the token. You can see the expiration date in the token itself ` max_age: 1800\n` (30 minutes) when you copy it from `fastlane`.

Please confirm and update this page so that people are aware of this limitation. Thx.

You can read more on the issue [here](https://github.com/fastlane/fastlane/issues/14301).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6209704c-87e7-20c3-1641-98f6bfec27a0
* Version Independent ID: f72e2fe4-c1f6-e775-8571-33495a70dc0d
* Content: [Build, test, and deploy Xcode apps - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/languages/xcode?view=azure-devops#feedback)
* Content Source: [docs/pipelines/languages/xcode.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/languages/xcode.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @DavidStaheli
* Microsoft Alias: **dastahel**

**Comment by davidstaheli** [comment]
The docs have been updated and should be live in a few days.  Thanks!
