### ISSUE TITLE
Can you add instructions on manually installing the extension

### ISSUE THREAD

**Issue by akuchotrani** [MicrosoftDocs/vsts-docs#4495]
I have VSIX file of the extension that I downloaded from the marketplace. There are no instructions on the page to install this file manually. It would be useful for other developers to include it in the documentation.

Steps to install:
Navigate to the Azure DevOps Server Extensions page on your server.
(For example, http://someserver/_gallery/manage)
Click upload new extension and select the file you have just downloaded.
After the extension has successfully uploaded, click Install and select the Team Project Collection to install into.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 46849bf5-07ed-62cd-66a5-2ebabe449855
* Version Independent ID: d12ad05e-4348-f13a-ea35-7bb4761c3b0b
* Content: [Install extensions for on-premises servers](https://docs.microsoft.com/en-us/azure/devops/marketplace/get-tfs-extensions?view=azure-devops-2019)
* Content Source: [docs/marketplace/get-tfs-extensions.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/marketplace/get-tfs-extensions.md)
* Product: **devops**
* Technology: **devops-marketplace**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by chcomley** [comment]
Hi @akuchotrani, Thanks for your feedback. I'm following up on your request and will get back to you soon!

**Comment by chcomley** [comment]
Hi @akuchotrani, At this time, we are unable to process your request for providing the manual steps within the current documentation. We do appreciate your feedback, so thank you. In the future, if you have a suggestion or feature request for the tool, or need technical support, please go here: https://visualstudio.microsoft.com/vs/support/#talktous

**Comment by karlingen** [comment]
@akuchotrani were you able to proceed? I'm experiencing the same issues
