### ISSUE TITLE
Support for dotnet Core

### ISSUE THREAD

**Issue by Chris113113** [MicrosoftDocs/vsts-docs#4498]
TIA support for dotnet Core would be phenomenal. Is this on the roadmap anywhere?

**Comment by thomps23** [comment]
@Chris113113 The Azure DevOps feature team maintains a view of their feature roadmap [here](https://docs.microsoft.com/en-us/azure/devops/release-notes/). If you don't find what you're looking for you can also promote it by submitting it [as an idea](https://developercommunity.visualstudio.com/content/idea/post.html?space=21).
