### ISSUE TITLE
Multi Environment Sample

### ISSUE THREAD

**Issue by markgar** [MicrosoftDocs/vsts-docs#4499]
Can you please provide an example of a pipeline like you are describing here?  I'd like to see a multi-environment pipeline that deploys to multiple environments (dev, test, prod). 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77d95db6-9983-7346-d0eb-4b7443e4e252
* Version Independent ID: 0a22cccc-318d-592f-d1ab-09ec01d88087
* Content: [Environment - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/environments?view=azure-devops#feedback)
* Content Source: [docs/pipelines/process/environments.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/environments.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @shashankbarsin
* Microsoft Alias: **shasb**

**Comment by markgar** [comment]
It would be nice if the sample were a nice full yaml file.  A build of an ASPNET Core app, then deployment to Dev, Test, Prod including approvals before deploying to Prod.

**Comment by RoopeshNair** [comment]
Here is a [sample](https://github.com/RoopeshNair/AzurePipelineSamples/blob/master/multistagesample.yml)

Let me know if you need more information

**Comment by khasibhatla** [comment]
Hey @RoopeshNair, Thanks for the sample above. It covers the multi-stage pipeline. 

Would you please kind to provide us with an example that can help us with "approvals before deploying to prod"?

**Comment by RoopeshNair** [comment]
Approvals feature is not yet supported in the new multi-stage YAML pipelines. It is in the works, (~6-8 Weeks). Please stay tuned

**Comment by fmms** [comment]
@RoopeshNair approvals have hit DevOps now. However, there is the unexpected requirement that everyone of the approvers have to approve. That is unusable for me. For me it would be one person out of several. Any idea how to cope with this?

**Comment by RoopeshNair** [comment]
Adding individual users mandates all of them to approve. If you add a group instead, any one of them can approve.

**Comment by fmms** [comment]
> Adding individual users mandates all of them to approve. If you add a group instead, any one of them can approve.

thank you so much! Just for everyone else in addition to user names one can specify Azure Devops Teams here. Teams are configured at Project Settings - Tems.
