### ISSUE TITLE
Turning off Default notifications.

### ISSUE THREAD

**Issue by sxm0275** [MicrosoftDocs/vsts-docs#450]
Hi, 

Can we turn off default notifications? 

We have post test approvers to approve release to prod environments. But developers don't want the approvers to get emails everytime they release somtehing to test. They want approvers to approve certian releases only. So we want to turn off the email notification for deployment approval, which we could do in TFS 2015 but we don't see any option for that in 2018.

Is there anything we can do to turn off that notification beside approvers going into tfs and unsubscribing themselves from notification.

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aeeb3695-9131-3598-c00b-0ae63fa6f33b
* Version Independent ID: 203d91ee-3831-0149-19e2-118de41ca5ae
* Content: [Understand the basics of how notifications work in VSTS and TFS](https://docs.microsoft.com/en-us/vsts/notifications/about-notifications?view=vsts)
* Content Source: [docs/notifications/about-notifications.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/notifications/about-notifications.md)
* Service: **unspecified**
* GitHub Login: @erickson-doug
* Microsoft Alias: **elbatk**

**Comment by elbatk** [comment]
Hey @sxm0275 , shooting this to the Notifications team so we can get an answer for ya.

**Comment by sxm0275** [comment]
Sounds good. Thanks.

**Comment by wnjenkin** [comment]
@sxm0275 can you try going to the following url, searching by the name of the post test approvers group, then try to disable the permission. 
http://{collection}:8080/tfs/DefaultCollection/_admin/_notifications?tab=Subscribers&view=Subscribers

if you want to turn it off for the entire collection then you can navigate here.
http://{collection}:8080/tfs/DefaultCollection/_admin/_notifications?

**Comment by sxm0275** [comment]
That worked. Thanks for the help.

**Comment by elbatk** [comment]
Closing this issue as I think we've got it solved, thanks @wnjenkin !
