### ISSUE TITLE
Unclear what to use the collection level groups for, e.g., Project Collection Build Service Accounts

### ISSUE THREAD

**Issue by LasseNisted** [MicrosoftDocs/vsts-docs#4502]
For a pipeline running with the "Build job authorization scope" set to "Project collection" we expect that giving the group "Project Collection Build Service Accounts" contribute rights to a repository would enable push.

However, we get the error: "remote: TF401027: You need the Git 'GenericContribute' permission to perform this action." during the build.

We can fix it by manually adding the user "Project Collection Build Service ({our organization})" to the repo permissions and giving contribute rights.

It seems the group "Project Collection Build Service Accounts" does not contain the user "Project Collection Build Service ({our organization})". Is that intentional? If it is, then what is the purpose of the group? Additionally, we cannot add said user to the group, but get the error "We are unable to add members to this group at this time. Please try again at a later time or contact support for help.".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 68686c2b-c69a-d9e4-3e21-a46d231b649c
* Version Independent ID: 049659da-1772-3166-f909-4feeb8a97730
* Content: [What are all the default permissions and groups? - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/security/permissions?view=azure-devops#collection-level-groups)
* Content Source: [docs/organizations/security/permissions.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/security/permissions.md)
* Product: **devops**
* Technology: **devops-security**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@andyjlewis - Adding you for insight as this relates to build service.

**Comment by KathrynEE** [comment]
Adding @vijayma for his insights.

**Comment by chasewilson** [comment]
@LasseNisted, thanks for the question. Sorry for the late reply. @vijayma just giving this a boost to see if you have any input?

**Comment by vijayma** [comment]
I am getting someone on the team to look at this. Sorry about the delay.

**Comment by chweems** [comment]
"Project Collection Build Service Accounts" is a legacy group used for XAML builds and the build service identity ("Project Collection Build Service ({your organization})") is a separate entity used for current builds. The service identity is the correct place to update the permissions.

**Comment by LasseNisted** [comment]
Thanks, @chweems - that makes sense. It would help if the docs are updated to clearly state this distinction.

**Comment by marcpopMSFT** [comment]
Taking a look at this update now.
