### ISSUE TITLE
Does the news that WCF might make it to core mean that the extended client might too?

### ISSUE THREAD

**Issue by AlexisColes** [MicrosoftDocs/vsts-docs#4503]
Thank you for your feedback!

The issues in this repo are for documentation feedback.

If you are submitting your documentation feedback issue directly through GitHub, please provide the URL of the article so we can route the feedback to the correct author.

Please report Azure DevOps or TFS software bugs, feedback, or questions in the [Azure DevOps Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html).

**Comment by AlexisColes** [comment]
You state the following in your documentation:

"The Microsoft.TeamFoundationServer.ExtendedClient currently doesn't support a NetStandard compliant version. This package includes our older SOAP object model, which has been replaced by our newer REST object model. At this point, we're no longer investing in the older SOAP object model, and have no plans to create a NetStandard version of it."

does the news that WCF is being ported to .netcore change this any?
https://dotnetfoundation.org/blog/2019/06/07/welcoming-core-wcf-to-the-net-foundation

Or will I have to knuckle down and rewrite all the code that is using it for sure?

**Comment by chcomley** [comment]
Hi @AlexisColes, Thanks for reaching out. I'm following up on this and will get back to you soon!

**Comment by chcomley** [comment]
Hi @AlexisColes, The guidance within the article you referenced still stands, as of today.
I welcome you to submit a suggestion to our engineers, however, by going [here](https://developercommunity.visualstudio.com/spaces/8/index.html), and then select **Suggest a feature**, and then **Azure DevOps**. Thanks and do let us know if you have any further questions.
