### ISSUE TITLE
DownloadPipelineArtifact@1 is in use now

### ISSUE THREAD

**Issue by adriantorrie** [MicrosoftDocs/vsts-docs#4504]
DownloadPipelineArtifact@0 is documented only.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 861ce7a5-4fa4-55f1-2c97-46a9cc6a2f66
* Version Independent ID: bdf954b9-9bbe-8b34-b674-71ad8153519d
* Content: [Publish and consume Pipeline artifacts in builds - Azure Pipelines and TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/pipeline-artifacts?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/artifacts/pipeline-artifacts.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/artifacts/pipeline-artifacts.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @alexmullans
* Microsoft Alias: **amullans**

**Comment by willsmythe** [comment]
This doc is in the process of being updated with the latest task details. This should be live in the next day or two.. As a preview ... Download Pipeline Artifact V2 adds support for downloading both pipeline artifacts and build artifacts (i.e. artifacts published with Publish Build Artifacts).
