### ISSUE TITLE
Python example for sys.args not documented for Python script

### ISSUE THREAD

**Issue by claesjanwolff** [MicrosoftDocs/vsts-docs#4506]
In the Python script task, one can enter arguments, which will be interpreted as  a python sys.args[] list
I cant see an example on how to enter the arguments in the Arguments field. e.g. I have 2 string arguments I need to pass: "ABC" and "123,xyc" notice the comma in the string. How do I pass to the python interpreter? I tried with comma separated, lists [], string encapsulating (e.g. '"ABC", "123,xyz"'. nothing seems to work.

**Comment by thomps23** [comment]
@claesjanwolff It looks like the feedback tool didn't capture the topic you were on. Could you provide a URL so we can triage this item?

**Comment by claesjanwolff** [comment]
trial and errored, aruments are passed in the task as blank separated strings
