### ISSUE TITLE
Use iframe that is not a video?

### ISSUE THREAD

**Issue by alexrest** [MicrosoftDocs/vsts-docs#4507]
Is it possible to insert an iframe element on the page that's not a video? It would be really helpful to insert an Adobe XD, InVision, or Framer prototype using an iframe.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 29f1e43f-a069-dd88-7fc7-9cc497fb94f0
* Version Independent ID: c261afa7-6eb7-b3f0-9f92-6d2f3c5ac336
* Content: [Markdown syntax for wikis in Azure DevOps - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/project/wiki/wiki-markdown-guidance?view=azure-devops#feedback)
* Content Source: [docs/project/wiki/wiki-markdown-guidance.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/project/wiki/wiki-markdown-guidance.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @alexrest, Thanks for reaching out. Unfortunately, it's not possible for security reasons. The only place it is allowed is inside an embedded video wrapper. You're always welcome to submit a feature request or further feedback on the product [here](https://visualstudio.microsoft.com/vs/support/#talktous). Thank you!

**Comment by simonsabin** [comment]
This has been raised https://developercommunity.visualstudio.com/content/idea/608314/allow-iframe-elements-to-be-embedded-in-wiki-pages.html

**Comment by kedano** [comment]
It would be awesome if you whitelisted Figma embeds in the DevOps docs. https://www.figma.com/blog/announcing-live-figma-embeds/

**Comment by pomSense** [comment]
thumbs up for figma embeds
