### ISSUE TITLE
Missing API references for Microsoft.VisualStudio.Services.Release.Client package

### ISSUE THREAD

**Issue by dpaulino** [MicrosoftDocs/vsts-docs#4510]
I am trying to find API reference docs for the namespaces included in the Microsoft.VisualStudio.Services.Release.Client package, but I cannot find any information. In particular, my goal is to find all the classes in this namespace: `Microsoft.VisualStudio.Services.ReleaseManagement.WebApi`.  This namespace is found inside of the Microsoft.VisualStudio.Services.Release.Client package.

I have tried to search through Microsoft's .NET API browser tool (https://docs.microsoft.com/en-us/dotnet/api/) but I could not find this namespace. Any ideas on where I can find information on that namespace? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 413163f0-28c3-a2a7-d626-fcb81bcb2257
* Version Independent ID: 57c127da-2b1e-d29e-9abb-a3c258762ccf
* Content: [.NET Client Libraries for Azure DevOps Services (and TFS)](https://docs.microsoft.com/en-us/azure/devops/integrate/concepts/dotnet-client-libraries?view=azure-devops)
* Content Source: [docs/integrate/concepts/dotnet-client-libraries.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/integrate/concepts/dotnet-client-libraries.md)
* Product: **devops**
* Technology: **devops-ecosystem**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by thomps23** [comment]
@dpaulino I was able to find [this site page](https://apisof.net/catalog/Microsoft.VisualStudio.Services.ReleaseManagement.WebApi) does that help?

**Comment by chcomley** [comment]
Hi @dpaulino, Please do let us know whether you have any further questions, otherwise I'll be closing this issue. Thank you!

**Comment by dpaulino** [comment]
Yes, that site page helps @thomps23. Thanks @chcomley
