### ISSUE TITLE
Other auth methods than PAT?

### ISSUE THREAD

**Issue by epernst** [MicrosoftDocs/vsts-docs#4512]
You write:
"Your agent can authenticate to Azure Pipelines or TFS using one of the following methods:
Personal Access Token (PAT):"
If PAT is the only option, then should it be not rather say:
"Your agent can authenticate to Azure Pipelines or TFS using the following method:
Personal Access Token (PAT):".

Or are there other methods?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 47625b86-abd5-ee15-6d61-8bcf81861b96
* Version Independent ID: be9a6174-a69b-7aed-d584-5f602fcc5eb4
* Content: [Azure Pipelines Agents - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/agents?view=azure-devops)
* Content Source: [docs/pipelines/agents/agents.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/agents/agents.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by brent-robinson** [comment]
There are four authentication types, but PAT is the only type Azure Pipelines supports. Azure DevOps Server 2019 (or TFS) supports the other authentication types. They're detailed on the "Self-Hosted agents" pages: https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/v2-windows?view=azure-devops#unattended-config

This document should be updated to include the other options as this document targets Pipelines, DevOps Server, and TFS.

**Comment by bluebaroncanada** [comment]
The problem is that this document is not loading properly.  Someone pointed me to this document, which I'd already been to and his version shows that section.  You can get it from the document's source, though.

https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/agents/agents.md

**Comment by steved0x** [comment]
@epernst I have updated the article since I agree it is confusing to see a statement talking about the following "methods" but there is only 1, and I am reviewing to make sure that the rendering is correct for on-premises versions to show the other methods. This update should be live soon, thank you.
