### ISSUE TITLE
Badges for New Yaml (With Stages) Does Not Work

### ISSUE THREAD

**Issue by RehanSaeed** [MicrosoftDocs/vsts-docs#4514]
These badges were copied from the Azure DevOps site but they don't actually work.

```
[![Build Status](https://dev.azure.com/schema-net/Schema.NET/_apis/build/status/Schema.NET?branchName=master&stageName=Build&jobName=Build&configuration=Build%20Linux)](https://dev.azure.com/schema-net/Schema.NET/_build/latest?definitionId=1&branchName=master)

[![Build Status](https://dev.azure.com/schema-net/Schema.NET/_apis/build/status/Schema.NET?branchName=master&stageName=Build&jobName=Build&configuration=Build%20Mac)](https://dev.azure.com/schema-net/Schema.NET/_build/latest?definitionId=1&branchName=master)

[![Build Status](https://dev.azure.com/schema-net/Schema.NET/_apis/build/status/Schema.NET?branchName=master&stageName=Build&jobName=Build&configuration=Build%20Windows)](https://dev.azure.com/schema-net/Schema.NET/_build/latest?definitionId=1&branchName=master)
```

This is what they look like:

![image](https://user-images.githubusercontent.com/2270364/59494755-c2b5ce00-8e85-11e9-91c9-6964d22312df.png)

See badges live at the bottom of [this project](https://github.com/RehanSaeed/Schema.NET) page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d6f530be-df56-eb28-e9a5-9e076554277f
* Version Independent ID: 37367a1e-e655-14ee-dfe4-7270ad85c7eb
* Content: [Share your Azure DevOps Services packages with badges](https://docs.microsoft.com/en-us/azure/devops/artifacts/package-badges?view=azure-devops#feedback)
* Content Source: [docs/artifacts/package-badges.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/artifacts/package-badges.md)
* Product: **devops**
* Technology: **devops-artifacts**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by encelo** [comment]
I am experiencing the same issue since a couple days, all my badges are gray: https://ncine.github.io/ci/

**Comment by elbatk** [comment]
It looks like these are Azure Pipelines badges, not Azure Artifacts (I see some of your Azure Artifacts badges behaving normally). Adding @andyjlewis to take a look and point you to the right people. Closing this issue here as it seems like a product problem and not a docs problem. Andy, hoping you can help these people out :)

**Comment by andyjlewis** [comment]
@vijayma can you take a look?

**Comment by RehanSaeed** [comment]
Can I raise this issue elsewhere, so it's tracked?

**Comment by moswald** [comment]
@RehanSaeed I apologize. There was a change made internally for looking up the specific jobs, and it has broken status badges. If you revisit the badge generator dialog it should show you a corrected link. Additionally, work is being done to see if we can easily detect these older badge requests and silently treat them as having been made with the correct information.

**Comment by moswald** [comment]
If you find that the generator dialog still doesn't generate correct links, file an issue at the [Azure DevOps Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html), and then tag me (maoswald at msft) in a comment.

**Comment by encelo** [comment]
Badges are still broken for me. :cry: 
Only the Pipeline Scope from the Status badge window is working, but none of the singular job ones.
For example in this project of mine: https://dev.azure.com/encelo/nCine/_build?definitionId=3

**Comment by RehanSaeed** [comment]
Can confirm that badges are still broken in in the Azure DevOps badge generator screen.

**Comment by RehanSaeed** [comment]
Raised issue https://developercommunity.visualstudio.com/content/problem/627180/badges-for-new-yaml-with-stages-does-not-work.html
