### ISSUE TITLE
Project contributors do not have access to the Wiki repository

### ISSUE THREAD

**Issue by jarlarntzen** [MicrosoftDocs/vsts-docs#4515]
"By default, all project contributors have read and edit access of the wiki repository. "

This is not true for my team members. 
I have tried adding them to the Contributors group (they were already added) and I have tried adding individual users to the wiki to no avail.

Do you have any suggestions here? How should I set the permissions of the Access Control Summary?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c86f5178-e331-f45e-b60a-f0f3955f7a08
* Version Independent ID: 8a0882a7-8f48-32bb-c741-12976b428c38
* Content: [Manage permissions for READMEs and wiki pages in Azure DevOps - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/project/wiki/manage-readme-wiki-permissions?view=azure-devops#feedback)
* Content Source: [docs/project/wiki/manage-readme-wiki-permissions.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/project/wiki/manage-readme-wiki-permissions.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @jarlarntzen, Thanks for reaching out. I've engaged our PM, @adramasu, for his expertise. Thanks!

**Comment by adramasu** [comment]
Hi @jarlarntzen, can you please check if the permissions "Contribute" and "Read" are in allow state?

**Comment by chcomley** [comment]
Hoping you got this figured out, however if we've missed you, please respond and we can reopen this issue. Thanks very much.
