### ISSUE TITLE
What happens if I do not specify artifactName?

### ISSUE THREAD

**Issue by sandersaares** [MicrosoftDocs/vsts-docs#4516]
The docs say it is optional but what does this mean exactly? What is downloaded if the name is not specified? This should be documented.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b03d67d0-8738-72e6-dbe7-324c1784d4fc
* Version Independent ID: bbb4d774-cd98-3ecb-7ccf-5f49e6f2b425
* Content: [Download Pipeline Artifact task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/download-pipeline-artifact?view=azure-devops#feedback)
* Content Source: [docs/pipelines/tasks/utility/download-pipeline-artifact.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/utility/download-pipeline-artifact.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @willsmythe
* Microsoft Alias: **wismyth**

**Comment by chasewilson** [comment]
@sandersaares Thank you for the feedback! I've taken your recommendation and doc will have an explicit answer pushed out today. To answer your question, If left empty, all artifacts associated to the pipeline run will be downloaded. 
I'll be closing this issue but please feel free to reach out or open a new issue with any more feedback!
