### ISSUE TITLE
Grant Access To Boards -> Boards readonly

### ISSUE THREAD

**Issue by kolendomichal** [MicrosoftDocs/vsts-docs#4517]
I would like to grant access for non-members to view status of kanban board , as it is linked in my project [Readme.md](https://github.com/kolendomichal/SVGAnimation/blob/master/README.md) by **Azure Boards** plugin. 
For now all non-members are getting 401 Unauthorized, which is pretty ugly.
Is there a way to configure this setting? I cannot seem to find it in Azure devops.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0ee798dd-0f8b-ed6c-c4e9-cce9d093176c
* Version Independent ID: a5aae6ab-05f7-272e-e6a4-bff9f2e6dbea
* Content: [Differences and limitations - Azure DevOps Services Public Project](https://docs.microsoft.com/en-us/azure/devops/organizations/public/feature-differences?view=azure-devops#feedback)
* Content Source: [docs/organizations/public/feature-differences.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/public/feature-differences.md)
* Product: **devops**
* Technology: **devops-public-projects**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @kolendomichal, 
Please accept my sincerest apology for letting this slip through my radar. I'm looking into this today and will be in touch. Thank you.

**Comment by kolendomichal** [comment]
Hi @chcomley 
Any new informations regarding this issue? :)

**Comment by chcomley** [comment]
Hi @kolendomichal, I appreciate you checking in. I just received a response from our PM, which states that Kanban boards are not visible to non-members. I imaging there may be a feature request for this already, so I'd recommend finding it and upvoting, or you can create your own feature request here: https://developercommunity.visualstudio.com/content/idea/post.html?space=21. Thanks and I hope you have a great day!
