### ISSUE TITLE
Change Process Wizard does not appear

### ISSUE THREAD

**Issue by benbeaton** [MicrosoftDocs/vsts-docs#4518]
In step 3 of this guide, there is no ellipsis available to run the Change Process Wizard - the only fields visible on the Projects page for the process are "Name" and "Description".  Was this article written using a pre-release version of Azure DevOps?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b35f891-bcd6-da03-9c07-a5ac494ab5cc
* Version Independent ID: dcb0faba-7b49-0e9b-f430-2e2e43ed62d9
* Content: [Change process from Agile to Scrum - Azure Boards](https://docs.microsoft.com/en-gb/azure/devops/organizations/settings/work/change-process-agile-to-scrum?view=azure-devops#feedback)
* Content Source: [docs/organizations/settings/work/change-process-agile-to-scrum.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/settings/work/change-process-agile-to-scrum.md)
* Product: **devops**
* GitHub Login: @danhellem
* Microsoft Alias: **kaelli**

**Comment by thomps23** [comment]
@KathrynEE I was able to repro the difference between current service experience and what the docs discuss. Could you double check?

**Comment by KathrynEE** [comment]
@thomps23, @benbeaton , @danhellem - I believe that this feature is currently turned on for only a few customer accounts. It will become generally available in a few weeks. Dan - can you confirm?

**Comment by JIMHarwood** [comment]
I have the same issue, are there certain permissions i would need in able to see the change process wizard?

**Comment by danhellem** [comment]
This feature is in preview only right now. I updated the docs accordingly. If you wish to participate in the preview please email me directly at dahellem@microsoft.com and we can get you setup.
