### ISSUE TITLE
Bing custom search - Autosuggest API typo

### ISSUE THREAD

**Issue by TestUser20191** [MicrosoftDocs/vsts-docs#4519]
I'm using the document https://docs.microsoft.com/en-us/rest/api/cognitiveservices-bingsearch/bing-custom-autosuggest-api-v7-reference for my reference. 

The autosuggest endpoint as per the document is:
https://api.cognitive.microsoft.com/bingcustomsearch/v7.0/suggestions/search

When I use this with correct key, I'm getting:
        "message": "Access denied due to invalid subscription key. Make sure to provide a valid key for an active subscription."
 

Where as when I use the endpoint as 
https://api.cognitive.microsoft.com/bing/v7.0/suggestions
with the same subscription key, I'm getting the response as:
```{
    "_type": "Suggestions",
    "queryContext": {
        "originalQuery": ""
    },
    "suggestionGroups": [
        {
            "name": "Web",
            "searchSuggestions": []
        }
    ]
}```
 

Endpoint requires updating in the document. Also there is no document to explain how we could integrate Autosuggest API along with Bing Web search API.

**Comment by thomps23** [comment]
@TestUser20191 Could you provide additional context around how this fits into your Azure DevOps scenario so that we can check the documentation.

**Comment by TestUser20191** [comment]
@thomps23. Sorry, added in wrong repo. This is an issue with azure not with devops. I'll close this issue here as it is not related to devops.
