### ISSUE TITLE
[skip ci] to skip CI for a pull request

### ISSUE THREAD

**Issue by pllim** [MicrosoftDocs/vsts-docs#4522]
Hi, thank you for this service! I was told that inserting `[skip ci]` in a commit message does not skip CI for a pull request that triggered it. Is that true? Do you have plans to enable `[skip ci]` (and all the supported variants) directive for a pull request?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bfba9a21-e0f9-4fc6-43fc-bfdc51af31d3
* Version Independent ID: d93c7852-ce63-a6d0-417a-45f8cf2fc522
* Content: [Build GitHub repositories - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/github?view=azure-devops&tabs=yaml#comment-triggers)
* Content Source: [docs/pipelines/repos/github.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/repos/github.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @DavidStaheli
* Microsoft Alias: **dastahel**

**Comment by thomps23** [comment]
@pllim The Azure DevOps group tracks their feature roadmap [here](https://docs.microsoft.com/en-us/azure/devops/release-notes/). If you don't see what you're looking for on their roadmap, you can [submit this as a product idea](https://developercommunity.visualstudio.com/content/idea/post.html?space=21) to make sure it gets in front of the right people.
