### ISSUE TITLE
Storage questions

### ISSUE THREAD

**Issue by vectorhacker** [MicrosoftDocs/vsts-docs#453]
Do hosted agents keep generated files between builds? Like if I used a build system that caches builds, will that cache be there on the next build?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 99af681d-41ad-da15-0b72-08b5cd5a11ac
* Version Independent ID: 2fa0df36-a437-8cbb-b019-b49b31b1e116
* Content: [Hosted agents for VSTS](https://docs.microsoft.com/en-us/vsts/build-release/concepts/agents/hosted?view=vsts)
* Content Source: [docs/build-release/concepts/agents/hosted.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/build-release/concepts/agents/hosted.md)
* Service: **unspecified**
* GitHub Login: @erickson-doug
* Microsoft Alias: **alewis**

**Comment by alexhomer1** [comment]
No. You have 10 GB of space available during the build. After the build is complete, this space is cleared before the next build.
