### ISSUE TITLE
Versioning with date not working

### ISSUE THREAD

**Issue by andyf1ynn** [MicrosoftDocs/vsts-docs#4532]
In Azure devops potal, if i create a pipeline variable which has a value $(Major).$(Minor).$(Patch).$(date:yyyyMMdd) and in Nuget-Pack task i set the version to the variable, I get this error: - The nuget command failed with exit code(1) and error(Version string specified for package reference '1.0.1.$(date:yyyyMMdd)' is invalid.)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 11ed58a1-5819-f3a4-c674-dafcdbd56fbc
* Version Independent ID: d68aca4d-3fd3-1864-09f5-6060295e0399
* Content: [Publishing to NuGet feeds - Azure Pipelines and TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/nuget?view=azure-devops&tabs=yaml#feedback)
* Content Source: [docs/pipelines/artifacts/nuget.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/artifacts/nuget.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @thomps23
* Microsoft Alias: **amullans**

**Comment by msebolt** [comment]
@andyf1ynn Thank you for your feedback!  

The author has been notified with your support issue.

@thomps23 Can you please take a look at this issue?

**Comment by chasewilson** [comment]
@andyf1ynn sorry for the late response. Are you still having this issue?

**Comment by chasewilson** [comment]
I'll be closing this issue for now. I want to make sure you are no longer having this issue so please either respond here or make a new issue and I will get back to you as soon as possible.
