### ISSUE TITLE
Does YAML schema support approval?

### ISSUE THREAD

**Issue by pinyuko** [MicrosoftDocs/vsts-docs#4533]
We can use "approvals" with Azure pipelines & stages as mentioned in https://docs.microsoft.com/en-us/azure/devops/pipelines/release/deploy-using-approvals 
Does YAML schema also support approval? Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7458d5b2-1bb7-7d87-7ce6-2b0c430b0155
* Version Independent ID: edf5bbd3-a3f0-5426-e985-31290f8afd05
* Content: [YAML schema - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema)
* Content Source: [docs/pipelines/yaml-schema.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/yaml-schema.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @vtbassmatt
* Microsoft Alias: **macoope**

**Comment by shashban** [comment]
Preview of multi-stage YAML pipelines currently does not support seeking manual approvals for deployments. We are actively working on including this support in the preview.
Stay tuned on the developments through release notes for Azure DevOps.
