### ISSUE TITLE
Does WIQL only support workitems table currently?

### ISSUE THREAD

**Issue by BrightRan** [MicrosoftDocs/vsts-docs#4534]
Which tables does WIQL support currently? Does WIQL only support workitems table currently?
There no have any description to explain this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 710af5f2-8a31-e0d3-4f20-00c79dc54713
* Version Independent ID: 1d4d9580-984c-9fee-861a-a02ce828d3db
* Content: [WIQL reference syntax - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/queries/wiql-syntax?view=azure-devops#feedback)
* Content Source: [docs/boards/queries/wiql-syntax.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/boards/queries/wiql-syntax.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@BrightRan - Thank you for the question. WIQL stands for Work Item Query Language - so WIQL only supports querying the data store for work items.
