### ISSUE TITLE
Provide link to module reference

### ISSUE THREAD

**Issue by davidsk** [MicrosoftDocs/vsts-docs#4535]
I would be helpful if a link was provided detailing the different modules that are available to be [required](https://docs.microsoft.com/en-us/azure/devops/extend/reference/client/core-sdk?view=azure-devops#require()).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f699a190-5e7e-1103-8d9d-c3d58e698e3a
* Version Independent ID: 1e54fe20-7e4d-d5ff-1682-8659f7a8fba8
* Content: [Core Client SDK](https://docs.microsoft.com/en-us/azure/devops/extend/reference/client/core-sdk?view=azure-devops)
* Content Source: [docs/extend/reference/client/core-sdk.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/extend/reference/client/core-sdk.md)
* Product: **devops**
* Technology: **devops-ecosystem**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by chcomley** [comment]
Thanks for your feedback, @davidsk, I'll follow up on this soon and get back to you. Hope you enjoy your  weekend.

**Comment by SephirotJustin** [comment]
Is there any documentation now? 
Its a pain in the ass to figure it out self, only reading the type definitions. 
Would be really helpfull

**Comment by chcomley** [comment]
Hi @SephirotJustin, I've followed up on this and will let you know once we've published an update. Thanks very much!

**Comment by chcomley** [comment]
@SephirotJustin, I'm publishing an update to the article today, adding an Important note containing a link to our latest and greatest guidance, which is here: https://developer.microsoft.com/en-us/azure-devops/develop/extensions. I'm closing this issue, however please @mention me if you have any further questions. 
Thank you!
