### ISSUE TITLE
Incorrect time estimate

### ISSUE THREAD

**Issue by ajmeese7** [MicrosoftDocs/vsts-docs#4536]
There is no reason this page would take 19 minutes to read. Several other pages of similar lengths have time estimates of two minutes, which is much more reasonable. This should take five minutes at most, not 19.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7336a04e-5b38-d02f-8bba-a55445b2f094
* Version Independent ID: 783c30b3-63b6-da7c-1336-b000bb8b4c66
* Content: [Create your first pipeline - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/create-first-pipeline?view=azure-devops&tabs=tfs-2018-2#feedback)
* Content Source: [docs/pipelines/create-first-pipeline.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/create-first-pipeline.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by WilliamAntonRohm** [comment]
@ajmeese7 -- thank you for bringing this to our attention.

@andyjlewis -- please investigate the reading time calculation.

**Comment by steved0x** [comment]
Some of the other versions of the topic, like this [TFS 2017 version](https://docs.microsoft.com/en-us/azure/devops/pipelines/create-first-pipeline?view=tfs-2017&tabs=tfs-2018-2) are much longer, and I think the build system (that automatically adds the reading estimates) uses the contents of the whole file. We don't have a way to change that, sorry for any confusion.
