### ISSUE TITLE
Update Scaled-Agile-Framework 4.0 to 4.6

### ISSUE THREAD

**Issue by tcsllcga** [MicrosoftDocs/vsts-docs#4538]
Greetings from James Price,

**Situation:** Over past year, I've worked with numerous PMs on how to use Azure DevOps and Scaled Agile Framework (SAFe) to manage portfolios. I've relied heavily on the article, Implement Scaled Agile Framework® to support epics, release trains, and multiple backlogs. However, article demonstrate SAFe 4.0 and several images are dated. Though, article's underlying theory remains sound. **Path: docs/boards/plans/scaled-agile-framework.md**

Good article, What’s New in SAFe 4.6: [https://www.scaledagileframework.com/whats-new-in-safe-46/](url)

**Offer**: With Microsoft's blessing, I would like to give back by giving this article a makeover. I would start by updating Mardown content (verbiage & images) and then demonstrate how to configure Azure DevOps Services to implement SAFe 4.6.  I had plan to Visual Studio Code (markdown editor) and use my own instance of Azure DevOps [https://tcsllcga.visualstudio.com/](url) and extract images from an Agile-based project created by Azure DevOps Demo Generator project based on Agile.  Ultimately, I would also like to update related docs in the docs/boards/plans folder. 

**My Background - James Price:**
Since 2008, I've worked as certified Project Management Professional (PMP) and Corporate Trainer for few F100 companies. I've managed software projects using Azure DevOps, VSTS, Team Foundation Server. Over last 5 years, I have had the opportunity to gain a wealth of experience (hands-on and formal) with SAFe as an enterprise governance model. 

**Thanks and I look forward to receiving your response,
James Price**
Mobile: 470.538.8220 - 8am-8pm EST
Email: james.price@tcsllcga.com
LinkedIn: [www.linkedin.com/in/jameswprice](url)

@KathrynEE  @steved0x

**Comment by WilliamAntonRohm** [comment]
@tcsllcga -- thank you for your offer of assistance.  Please feel free to create a PR with your suggested changes.
