### ISSUE TITLE
will upgrade from TFS2018 to Azure Devops server 2019 break exisiting TFS reports

### ISSUE THREAD

**Issue by angelwang** [MicrosoftDocs/vsts-docs#4539]
[Enter feedback here]
Hi,
We are on TFS2018, we have lots of TFS report running against warehouse and analysis database. I am wondering if those report will break if we upgrade to Azure Devops Server 2019 since it introduced Analytic report feature ?

Thanks,
Angel

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d40bd959-f4d3-351f-6fc5-0116ebc03231
* Version Independent ID: ac42cfa7-52ec-1634-ae08-6ec0b65b3eb0
* Content: [Data available from the Analytics Service - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/report/powerbi/data-available-in-analytics?view=azure-devops)
* Content Source: [docs/report/powerbi/data-available-in-analytics.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/report/powerbi/data-available-in-analytics.md)
* Product: **devops**
* Technology: **devops-analytics**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by msebolt** [comment]
@angelwang Thank you for your question!  The author has been notified.

@KathrynEE Can you comment on upgrading the reports feature of TFS?

**Comment by KathrynEE** [comment]
@angelwang, @msebolt - No reports will be broken by upgrading to Azure DevOps Server 2019. The Analytics service is distinct from the data warehouse and analysis databases that the SQL Server Reports run against.
