### ISSUE TITLE
Invoke REST API callback works in TFS 2018.2 agentless task but not in gate

### ISSUE THREAD

**Issue by toddbrownmcis** [MicrosoftDocs/vsts-docs#4541]
Does the Callback work from a gate in TFS 2018.2?  It works from an agentless task with hubname "release".  I'm using hubname "gates" from the gate.  The callback returns a HTTP StatusCode 204 in both cases but the gate is not successful.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 89bc6da4-5a1e-5989-f4f0-27465953b5fd
* Version Independent ID: fd12f976-5d3b-3b1b-3d0a-a0bf2a60c961
* Content: [Invoke HTTP REST API task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/http-rest-api?view=azure-devops#feedback)
* Content Source: [docs/pipelines/tasks/utility/http-rest-api.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/utility/http-rest-api.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by msebolt** [comment]
@toddbrownmcis Thank you for the feedback!  The author has been notified.

@RoopeshNair Can you please address this issue?

**Comment by RoopeshNair** [comment]
@shashban - can you please take a look?

**Comment by shashban** [comment]
@toddbrownmcis Could you please share a URL to the release where the gate did not complete after the callback? We would like to look at logs/ product traces to see what could be missing.

**Comment by toddbrownmcis** [comment]
@shashban I'm running in on-prem TFS 2018.2. Is there some other way for me to provide the logs/traces you are looking for?

**Comment by toddbrownmcis** [comment]
@shashban @RoopeshNair I found the underlying issue for a callback to a Gate.  The body jobid is the taskid value and the taskid is an empty guid value.  See [GetJobId](https://github.com/microsoft/azure-pipelines-extensions/blob/5762a0bb4c87b4e44ebd1a9e63a0d68ee5a06b9d/ServerTaskHelper/DistributedTask.ServerTask.Remote.Common/TaskProgress/TaskClient.cs#L117) and [GetTaskId](https://github.com/microsoft/azure-pipelines-extensions/blob/5762a0bb4c87b4e44ebd1a9e63a0d68ee5a06b9d/ServerTaskHelper/DistributedTask.ServerTask.Remote.Common/TaskProgress/TaskClient.cs#L131).

When is the planVersion greater than 12?  Is that tied to a specific version of TFS/Azure DevOps or do I need to get the plan by planId?

**Comment by divman25** [comment]
@toddbrownmcis Sorry for the (extremely) late response on this to begin with. What you have figured out w.r.t to the plan version change is indeed correct. The change from plan version 12 to 13 is already live on AzureDevOps, and rolls out to TFS with Server 2019.1 RC1.
