### ISSUE TITLE
Which is the correct statement

### ISSUE THREAD

**Issue by realolap** [MicrosoftDocs/vsts-docs#4542]
On this page it states that VS Enterprise and Pro users have Basic +testplans included in their subscriptions.
But the VS pricing page https://visualstudio.microsoft.com/vs/pricing/ seems to suggest that only Enterprise has the testplans addition?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 73fdf4b3-7ff5-f9ab-d28c-45e804b314de
* Version Independent ID: e916c6aa-2ca5-1517-614c-091fb5b7572b
* Content: [Buy Basic + Test Plans access - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/billing/buy-basic-plus-test-plans?view=azure-devops)
* Content Source: [docs/organizations/billing/buy-basic-plus-test-plans.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/billing/buy-basic-plus-test-plans.md)
* Product: **devops**
* Technology: **devops-billing**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @realolap, Thanks for reaching out. There isn't a discrepancy - the confusion is perhaps with "Test." 

**Basic + Test Plans is included with…**
Visual Studio Enterprise
Visual Studio **Test** Professional
MSDN Platforms

**But not…**
Visual Studio Professional

Thanks again and please let us know if you have any further questions.
