### ISSUE TITLE
Wildcard filter for build trigger in yaml build

### ISSUE THREAD

**Issue by sujitks** [MicrosoftDocs/vsts-docs#4544]
**### Wildcard branch for trigger**

Hi, 

I am trying to configure a build pipeline using the yaml and when specify '*' as branch for triggering the build it does not work. Can you provide some example please?

**Comment by WilliamAntonRohm** [comment]
@sujitks -- thank you for contacting us.  You may find relevant information here:  https://docs.microsoft.com/en-us/azure/devops/pipelines/build/triggers?view=azure-devops&tabs=yaml

Please follow up with us if you need more information.
