### ISSUE TITLE
Documentation incomplete

### ISSUE THREAD

**Issue by pabrams** [MicrosoftDocs/vsts-docs#4547]
https://docs.microsoft.com/en-us/azure/devops/extend/develop/ui-controls/comboo?view=azure-devops#main

Where are all the properties and descriptions of what they do? For example, enableFilter and autoComplete are not listed anywhere.

**Comment by WilliamAntonRohm** [comment]
@pabrams -- thank you for your feedback.  

@chcomley -- does this issue seem related to [this issue](https://github.com/MicrosoftDocs/vsts-docs/issues/1229)?

**Comment by pabrams** [comment]
They are related to the same combo control, and they're both about incomplete docs, but that's about it....

**Comment by chcomley** [comment]
Hi @pabrams, For the most up-to-date developer documentation, please go here: https://developer.microsoft.com/en-us/azure-devops/. Please let us know if you have any further questions. Thank you!
