### ISSUE TITLE
Event workitem.updated - add details for changedFields setting

### ISSUE THREAD

**Issue by fume** [MicrosoftDocs/vsts-docs#4548]
As stated here: https://docs.microsoft.com/en-us/azure/devops/service-hooks/events?view=azure-devops#work-item-updated , we can use the changedFields setting to __Filter events to include only work items with the specified field**(s)** changed__.
Note the **(s)**. I guess this means we can specify MORE than one field but the GUI will let you select one field only. If more than one field can be specified, how can we do so? Using a string array? Seperating fields by a comma or a semicolon? Please, add details about the changedFields setting in general!

Thanks, regards

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6033d681-9093-547c-20fd-b31183c2bb33
* Version Independent ID: 0d92e3f0-7fb4-57e5-d913-f305a055a819
* Content: [Service hooks event reference](https://docs.microsoft.com/en-us/azure/devops/service-hooks/events?view=azure-devops#workitem.updated)
* Content Source: [docs/service-hooks/events.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/service-hooks/events.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by msebolt** [comment]
Hi @fume, thank you for the feedback.

@thomps23 Can you check this issue?

**Comment by fume** [comment]
any news on this? thanks

**Comment by fume** [comment]
Hi, please this is important to us. We need to understand if we MUST create many subscriptions - one for each field we want to monitor - or if we can (even programmatically, that's fine) create just one subscription with MANY fields whatched.

thanks, regards

**Comment by chcomley** [comment]
Hi @fume, Unfortunately the answer is that you can only have one field changed clause per Service Hook subscription.  Allowing multiple selections for each filter type has been considered in the past, and I'd welcome you to submit a feature request here: https://visualstudio.microsoft.com/vs/support/#talktous 
Please let me know if you have any further questions, thanks very much.

**Comment by fume** [comment]
Hi @chcomley , got it, thanks. But please, can you specify this in the docs? All the plurals in the JSON property and in the description are misleading.

thanks, regards

**Comment by chcomley** [comment]
Yes, @fume, I've created a user story on my backlog to address this. Thanks again!
