### ISSUE TITLE
'Check Complete linked work items after merging to complete any linked work items.' is inaccurate if you use the scrum template.

### ISSUE THREAD

**Issue by DevOps-Travis** [MicrosoftDocs/vsts-docs#4549]
If you are using the scrum template this statement isn't true 'Check Complete linked work items after merging to complete any linked work items.' Only tasks get automatically completed, Linked bugs and PBIs will not close because there is no transition for them in the scrum template. The wording here and in the PR user interface suggest that all linked work items regardless of type automatically complete when its selected which is not how it works.

If you want it to happen you have to modify the template for the team project.

https://developercommunity.visualstudio.com/content/problem/200302/complete-linked-work-items-after-merging-does-not.html

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 028e7b61-62e4-a10e-e420-3535f7843f0e
* Version Independent ID: 1a6fdbe7-5ba4-a7f8-1b2e-271289a7b9fd
* Content: [Review and merge code with pull requests - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/pull-requests?view=azure-devops#feedback)
* Content Source: [docs/repos/git/pull-requests.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/repos/git/pull-requests.md)
* Product: **devops**
* Technology: **devops-code-git**
* GitHub Login: @apawast
* Microsoft Alias: **sdanie**

**Comment by msebolt** [comment]
Hi @DevOps-Travis, thank you for the feedback.

The issue has been assigned to the author for further investigation.

**Comment by apawast** [comment]
Hi @DevOps-Travis, just to clarify are you making a feature suggestion to change the wording of the feature in the prouct, change the wording in the tutorial document, or change how the feature works to automatically work with work items in a scrum template?
