### ISSUE TITLE
adding groups is different, and for me, fails...

### ISSUE THREAD

**Issue by marct22** [MicrosoftDocs/vsts-docs#4552]
for me, If I got to organization settings, there is no explicit security page, just a title with two entries, policies and permissions.  Seemed permissions was the right one, so I went in, picked an existing group (valid users), went to that group's members, clicked on + add members, typed in my AD group (which was a specific team which has users in it), which showed up. when I click save, I see 'the selected member is not active. please check the member status before trying again'.  Uh, I'm adding a group, not a user.  AFAIK, a group won't have a basic/stakeholder/msdn, it's just a group of developers, each of which would have basic/stakeholder/msdn.  but it doesn't save the group.  I can only see azure devops groups, not AD groups.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 39c81ce4-7085-f5cd-e29a-e434074d449a
* Version Independent ID: e9bbaf41-404e-d1b7-5e39-33b68ffe7ef0
* Content: [Manage access with Azure Active Directory groups - Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/manage-azure-active-directory-groups?view=azure-devops#feedback)
* Content Source: [docs/organizations/accounts/manage-azure-active-directory-groups.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/accounts/manage-azure-active-directory-groups.md)
* Product: **devops**
* Technology: **devops-accounts**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @marct22, I'm sorry you're experiencing difficulties. Can you please tell me what version you're using? This article is for Azure DevOps Services. Also, can you please confirm that you've met the [prerequisites](https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/manage-azure-active-directory-groups?view=azure-devops#prerequisites)? Looking forward to your reply. Have a nice weekend.

**Comment by marct22** [comment]
We are using azure AD.  I am org owner.  How can i tell what version I'm using?  I am not using an on-premises version, it's in the cloud.  This isn't TFS, it's azure devops...

**Comment by chcomley** [comment]
Hi @marct22, We believe that either your Azure AD group you're trying to add is inactive for some reason, or there may be a bug. Please [create a support ticket](https://support.microsoft.com/en-us/supportforbusiness/requests) and those great folks will be happy to help you get this figured out. 

![create support ticket](https://user-images.githubusercontent.com/35748196/60137863-1fa26580-975d-11e9-88ef-93617eca5376.png)
Also, since you're in the cloud, I'd consider your "version" Azure DevOps Services, so please disregard that previous question. Thank you!
