### ISSUE TITLE
Variable group shared across different team projects in a same organization

### ISSUE THREAD

**Issue by BrightRan** [MicrosoftDocs/vsts-docs#4561]
Is there a way/feature to share Variable group across different team projects in a same organization?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4827aa99-ae62-bd63-6f2f-a87a4065ed27
* Version Independent ID: c9e461ee-7f42-3503-9460-18fa3a807bbb
* Content: [Variable groups for Azure Pipelines and TFS - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/library/variable-groups?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/library/variable-groups.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/library/variable-groups.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by BrightRan** [comment]
I mean that we only need to put these variable group in one place, then we can use the variable group in different team projects.

**Comment by RoopeshNair** [comment]
Sharing of Variable groups is on our backlog. At this point in time there is no time-line that I can share. 
We know this is important for you. If you could take time and vote/suggest feature request on [Developer Community](https://developercommunity.visualstudio.com/content/idea/post.html?space=21), it will help us prioritize it appropriately.

For now, if you are using Azure, you can store the secrets in Azure Key Vault and use it across multiple projects

**Comment by stan-dcip** [comment]
It is ridiculous that this still isn't a feature - you should not have to put ALL of your code under one project to share variables.  Octopus has had this feature for 5+ years.
