### ISSUE TITLE
Required parameter example is wrong

### ISSUE THREAD

**Issue by NightOwl888** [MicrosoftDocs/vsts-docs#4566]
The example given:

```
- bash: |
    if [ -z "$SOLUTION" ]; then
      echo "##vso[task.logissue type=error;]Missing template parameter \"solution\""
      echo "##vso[task.complete result=Failed;]"
    fi
```

will only function if `$(Solution)` is defined as a pipeline variable within the scope of the template. The condition is not referencing the template parameter that is defined, so it will give a false negative whenever `$(Solution)` is not actually in scope, and will give incorrect results entirely if `$(Solution)` is not being set as the value of the parameter.

Although I haven't tried it with BASH, I suspect the correct way would be to use expression syntax.

```
- bash: |
    if [ -z "${{ parameters.solution }}" ]; then
      echo "##vso[task.logissue type=error;]Missing template parameter \"solution\""
      echo "##vso[task.complete result=Failed;]"
    fi
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6724abea-bbdc-bf66-ed5e-3214fa6c3e66
* Version Independent ID: 4f8dab21-3f0e-da32-cc0e-1d85c13c0065
* Content: [Job and step templates - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/templates?view=azure-devops)
* Content Source: [docs/pipelines/process/templates.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/templates.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @vtbassmatt
* Microsoft Alias: **macoope**

**Comment by vtbassmatt** [comment]
The `env` keyword below the script body ensures that the template parameter will be propagated into the environment.

Gory details: Your version is semantically equivalent, but the one in the docs avoids a template formatting expansion on the inline script. For a script of this size, it makes no difference, but we have a character limit on formatting expansions (2000 characters I think), so a really long script would fail.
