### ISSUE TITLE
Secrets Not Mapped to Environmental Variables In Downstream Steps

### ISSUE THREAD

**Issue by rhizohm** [MicrosoftDocs/vsts-docs#4567]
The docs say that ENV is used for "A list of additional items to map into the process's environment. For example, secret variables are not automatically mapped. If you have a secret variable called Foo, you can map it in like this:- powershell: echo $env:MYSECRET
  env:
    MySecret: $(Foo)

However, those environmental variables are not there for downstream steps, even in the same job. Is this a bug in the documentation. If so, how does one get at secrets as environmental variables in a downstream step? If this is correct, is it a bug in the product?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a0e444c2-69c6-4d71-6fd0-94d0f4097d3a
* Version Independent ID: 3a727833-1cc3-c2fb-c5b3-22605eee2721
* Content: [PowerShell task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/powershell?view=azure-devops)
* Content Source: [docs/pipelines/tasks/utility/powershell.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/utility/powershell.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @vtbassmatt
* Microsoft Alias: **macoope**

**Comment by vtbassmatt** [comment]
Both the docs and the product are correct. Using `env` at the step level only maps a variable for the scope of that step. Each step runs in its own process, so it won't be there in the next step.

If you need a secret in multiple steps within a job, you can map it using `variables` at the job, stage, or pipeline level.
