### ISSUE TITLE
Passing values to the dialog control

### ISSUE THREAD

**Issue by davidsk** [MicrosoftDocs/vsts-docs#4568]
The section [Passing values to the dialog control](https://docs.microsoft.com/en-us/azure/devops/extend/develop/using-host-dialog?view=azure-devops#passing-values-to-the-dialog-control) doesn't actually specify how the dialog can access these values.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4f7f0126-0e00-ccfe-d1df-74201dc46a93
* Version Independent ID: 6abadf7d-8a1f-21f4-d6e6-efa5d9481182
* Content: [Modal Dialog](https://docs.microsoft.com/en-us/azure/devops/extend/develop/using-host-dialog?view=azure-devops)
* Content Source: [docs/extend/develop/using-host-dialog.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/extend/develop/using-host-dialog.md)
* Product: **devops**
* Technology: **devops-ecosystem**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by chcomley** [comment]
Thanks for your feedback, @davidsk, I'll follow up with the product group and get back to you on this. Have a great weekend.

**Comment by chcomley** [comment]
Hi @davidsk, Please go to our newest informational site [here](https://developer.microsoft.com/en-us/azure-devops/components/dialog), which should provide the necessary info. If you have any further questions, please @mention me. Thanks very much!

**Comment by davidsk** [comment]
@chcomley just revisiting this now.  All the examples on the linked site use React - would I be right in thinking that all extensions must now be written in / using React?

**Comment by chcomley** [comment]
Hi @davidsk, adding @apawast to assist in answering this question. Thanks!

**Comment by davidsk** [comment]
Hi @apawast, can you help with my query from Apr 16th? cc @chcomley

**Comment by chcomley** [comment]
Adding @vijayma to help address the April 16th customer question, thanks!

**Comment by davidsk** [comment]
Hi @vijayma, can you answer my query of April 16th?  Is React a mandatory dependency of custom devops extensions?
