### ISSUE TITLE
Certificates are still not supported?

### ISSUE THREAD

**Issue by artisticcheese** [MicrosoftDocs/vsts-docs#4570]
Per this document only secrets are supported but I was able to successfully map a certificate as well from KeyVault. Is it supported now or it just works but not supported?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4827aa99-ae62-bd63-6f2f-a87a4065ed27
* Version Independent ID: c9e461ee-7f42-3503-9460-18fa3a807bbb
* Content: [Variable groups for Azure Pipelines and TFS - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/library/variable-groups?view=azure-devops&tabs=classic)
* Content Source: [docs/pipelines/library/variable-groups.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/library/variable-groups.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by RoopeshNair** [comment]
Since certificates are internally stored as secrets, it works. We have plans to support Certificates as first class on our backlog - however not a priority as we have workaround.
