### ISSUE TITLE
There is no "Change process" button

### ISSUE THREAD

**Issue by taoyouh** [MicrosoftDocs/vsts-docs#4573]
In step 3, the "..." button does not exist, and thus the change process button doesn't exist either.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1f73858a-31dd-e0fa-cb7f-53dd42192791
* Version Independent ID: f61f9f02-8fbc-4511-e655-3087834302bd
* Content: [Change process from Scum to Agile - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/organizations/settings/work/change-process-scrum-to-agile?view=azure-devops)
* Content Source: [docs/organizations/settings/work/change-process-scrum-to-agile.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/settings/work/change-process-scrum-to-agile.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @danhellem
* Microsoft Alias: **kaelli**

**Comment by danhellem** [comment]
This is in private preview at the moment. You can email me your org name and we can turn on the preview for you. dahellem@microsoft.com
