### ISSUE TITLE
How to delete Project administrators of a project?

### ISSUE THREAD

**Issue by Cherishty** [MicrosoftDocs/vsts-docs#4574]
I am a Project administrator, recently I added other one as Project administrator. But how can I remove him/her from admin list?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ae5c3b5-9751-743f-6e68-d20a2fac6243
* Version Independent ID: 66756817-161b-cadf-f13c-10a216fae08a
* Content: [Set project or collection-level permissions - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/security/set-project-collection-level-permissions?toc=%2fazure%2fdevops%2forganizations%2fprojects%2ftoc.json&%3bbc=%2fazure%2fdevops%2forganizations%2fprojects%2fbreadcrumb%2ftoc.json&view=azure-devops)
* Content Source: [docs/organizations/security/set-project-collection-level-permissions.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/security/set-project-collection-level-permissions.md)
* Product: **devops**
* Technology: **devops-security**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by mregni** [comment]
@Cherishty , how did you do this? Can't seem to find a way to delete my project administrators myself.
