### ISSUE TITLE
How to delete a Project administrator?

### ISSUE THREAD

**Issue by Cherishty** [MicrosoftDocs/vsts-docs#4575]
I am a Project administrator, recently I add another guy as Project administrator too.

How can I remove him/her from Project administrators list?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c9927339-4cf7-8da4-1177-d5b3978684f9
* Version Independent ID: 1b9217f1-0506-1033-2ce4-2f335af9f32f
* Content: [Troubleshoot adding administrators to projects and project collections - Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/faq-add-administrators?view=azure-devops)
* Content Source: [docs/organizations/accounts/faq-add-administrators.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/accounts/faq-add-administrators.md)
* Product: **devops**
* Technology: **devops-accounts**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @Cherishty, You should be able to select the **Remove** link per the attached screenshot. After a few seconds, select the refresh button, and then the name should be removed. 
![removeprojectadmin](https://user-images.githubusercontent.com/35748196/60039082-be9a6500-966a-11e9-9388-c75026196f69.png)
Please let us know if you have any further questions. Thank you!

**Comment by Cherishty** [comment]
It works! Thanks for your help 👍
