### ISSUE TITLE
Legacy Task Flow and additional description/examples

### ISSUE THREAD

**Issue by DanoThom** [MicrosoftDocs/vsts-docs#4580]
This is a welcome new task but could we please have some examples walking through the (now) old task based pipeline flow (non-yaml)? There is a lot of ambiguity in what to select and how to use each field in the task. Also, some of the errors returned while poking in the dark aren't very informative. (##[error]EISDIR: illegal operation on a directory, read)

Additionally, I think that a lot more detail needs to be added around how this task is intended to be used. For example, for manifests: is it a list of manifests you can specify, and if so is it a space or comma seperated list? Or just a folder?
For containers, is it also a list of image/tags you can specify?
Does the ordering of the manifest yaml matter or correlate to the containers? Etc etc.

Or is it just intended to create one of these tasks per manifest folder?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72bba72b-235b-ce64-b8fd-2c6ed52a9f1f
* Version Independent ID: 2ae1b3f1-e125-a9d2-a17c-d13047d69801
* Content: [Kubernetes Manifest task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/kubernetes-manifest?view=azure-devops)
* Content Source: [docs/pipelines/tasks/deploy/kubernetes-manifest.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/deploy/kubernetes-manifest.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @shashankbarsin
* Microsoft Alias: **shasb**

**Comment by shashankbarsin** [comment]
We do have documentation for the old task. It's there in a different page under task documentation. Here's the documentation for the older [Kubectl task](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/kubernetes?view=azure-devops).

The comments on the Kubernetes manifest task such as multiple manifest file inputs, multiple container inputs for artifact substitution have been addressed with examples in the recent set of doc updates for the Kubernetes manifest task
