### ISSUE TITLE
Escaping character examples shown incorrectly.

### ISSUE THREAD

**Issue by chao-master** [MicrosoftDocs/vsts-docs#4581]
Under the [Ignore or escape markdown section](https://docs.microsoft.com/en-us/azure/devops/project/wiki/markdown-guidance?view=azure-devops#ignore-or-escape-markdown-syntax-to-enter-specific-or-literal-characters) the examples are not correctly shown.

It reads:
- "Enter `\` to get \\" instead of "Enter `\\` to get \\"
- "Enter `\` to get \_" instead of "Enter `\_` to get \_"
- "Enter `#` to get \#" instead of "Enter `\#` to get \#"
and so on.

This is probably an issue with how the markdown parser on the docs.microsoft.com site, as the file shows correctly when parsed by github's markdown parser [in this repo](https://github.com/MicrosoftDocs/vsts-docs/blob/5ab995d12b44e21610a015d720517a7cf0ac6fd3/docs/project/wiki/markdown-guidance.md#ignore-or-escape-markdown-syntax-to-enter-specific-or-literal-characters)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fa622358-f5bb-1f5c-177a-081a37b6acef
* Version Independent ID: 72f7fd16-a822-66c8-3a34-8905645ce5f2
* Content: [Markdown syntax for files, widgets, and wikis in Azure DevOps - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/project/wiki/markdown-guidance?view=azure-devops)
* Content Source: [docs/project/wiki/markdown-guidance.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/project/wiki/markdown-guidance.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @chao-master, Thanks so much for the heads up on this. I've updated the markdown so the code shows up properly. This update should be live within the next 3-4 hours, if not before. Thanks again!
