### ISSUE TITLE
Section Says "You can create bugs from the web portal web portal"

### ISSUE THREAD

**Issue by TylerBuchanan97** [MicrosoftDocs/vsts-docs#4583]
In the #track-code-defects section there is "web portal" printed twice.

Track code defects
You can create bugs from the web portal web portal, Visual Studio, or when testing with Test Manager.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f85f904-14c5-c520-edc3-b8af6826b4fc
* Version Independent ID: 414874f2-1e30-04da-0feb-e459a4e51be8
* Content: [Agile process work item types & workflow - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/work-items/guidance/agile-process-workflow?view=azure-devops#track-code-defects)
* Content Source: [docs/boards/work-items/guidance/agile-process-workflow.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/boards/work-items/guidance/agile-process-workflow.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by msebolt** [comment]
@TylerBuchanan97 Thank you for the feedback!

Fix in review per https://dev.azure.com/mseng/TechnicalContent/_git/vsts-docs-pr/pullrequest/479923?_a=overview.
