### ISSUE TITLE
Missing Documentation for Scheduled Trigger

### ISSUE THREAD

**Issue by RichardMeadowsTC** [MicrosoftDocs/vsts-docs#4585]
My Azure DevOps builds no longer support setting scheduled triggers in the pipeline.  I am seeing this message on 6/19/2019 and 6/20/2019  'You can no longer define scheduled triggers in the editor. Instead, you must add schedules to your YAML file. For more information, see https://go.microsoft.com/fwlink/?linkid=2080841'

That URL sent me here.  There is no documentation here for Scheduled Triggers.  Please add it so I can change the time which my build runs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7458d5b2-1bb7-7d87-7ce6-2b0c430b0155
* Version Independent ID: edf5bbd3-a3f0-5426-e985-31290f8afd05
* Content: [YAML schema - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema#feedback)
* Content Source: [docs/pipelines/yaml-schema.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/yaml-schema.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @vtbassmatt
* Microsoft Alias: **macoope**

**Comment by Advin24** [comment]
This is also contradicting the following documentation page: [Build pipeline triggers - Scheduled Triggers](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/triggers?view=azure-devops&tabs=yaml#scheduled-triggers)

> Scheduled builds are not yet supported in YAML syntax. After you create your YAML build pipeline, you can use pipeline settings to specify a scheduled trigger.

**Comment by steved0x** [comment]
@RichardMeadowsTC The doc just went live, here is a link to it:

https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema
