### ISSUE TITLE
Typo on page

### ISSUE THREAD

**Issue by terrysmith-fiworks** [MicrosoftDocs/vsts-docs#4586]
In the "Writes an error" section of the page, the code comment is "Writes a warning" but should be "Writes an error".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a0e444c2-69c6-4d71-6fd0-94d0f4097d3a
* Version Independent ID: 3a727833-1cc3-c2fb-c5b3-22605eee2721
* Content: [PowerShell task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/powershell?view=azure-devops#feedback)
* Content Source: [docs/pipelines/tasks/utility/powershell.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/utility/powershell.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @vtbassmatt
* Microsoft Alias: **macoope**

**Comment by msebolt** [comment]
@terrysmith-fiworks Thank you for the feedback!

Fix submitted per https://dev.azure.com/mseng/TechnicalContent/_git/vsts-docs-pr/pullrequest/479915?_a=overview.

**Comment by msebolt** [comment]
Change under review, for internal reference see https://dev.azure.com/mseng/TechnicalContent/_git/vsts-docs-pr/pullrequest/485270?_a=overview.

**Comment by msebolt** [comment]
The changes are now merged.  Closing issue.
