### ISSUE TITLE
Upstreaming powershellgallery.com in a private Azure Devops nuget feed

### ISSUE THREAD

**Issue by tristanbarcelon** [MicrosoftDocs/vsts-docs#4587]
There is a good article on [setting up an Azure Devops artifacts feed as private powershell gallery](https://docs.microsoft.com/en-us/azure/devops/artifacts/tutorials/private-powershell-library?view=azure-devops). I've set something up like this and it's been running great for 2 yrs until June 11th this year. On that day, all our powershell code in that private repo or task groups which relied on modules from powershellgallery.com all started failing when PSGallery went down. It would have been great if we could have upstreamed powershellgallery.com from our private powershell galleries. After all, they're just nuget feeds. Why am I prevented by the UI from upstreaming a public, non-authenticated feed such as powershellgallery as long as the Nuget type is specified?

**Comment by msebolt** [comment]
@tristanbarcelon Thanks for the suggestion! 

The product teams aren’t always watching this repository, so to make sure it gets in front of them for triage, please [submit your idea]( https://developercommunity.visualstudio.com/content/idea/post.html?space=21) here.
