### ISSUE TITLE
Sample doesn't build. 

### ISSUE THREAD

**Issue by asklar** [MicrosoftDocs/vsts-docs#4590]
The return type of RunGetBugsQueryUsingClientLib should be Task&lt;List&lt;WorkItem&gt;&gt; since the method is async

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e978322f-15ae-3a89-ae89-497cdfa5070a
* Version Independent ID: f8654902-e266-c12b-8e25-a2fa7a2ac626
* Content: [Get work items programmatically from Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/integrate/quickstarts/work-item-quickstart?view=azure-devops#feedback)
* Content Source: [docs/integrate/quickstarts/work-item-quickstart.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/integrate/quickstarts/work-item-quickstart.md)
* Product: **devops**
* Technology: **devops-ecosystem**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by chcomley** [comment]
Hi @asklar, thanks so much for your feedback. I'm following up on this and will be in touch soon.

**Comment by danhellem** [comment]
@asklar good catch...we are fixing the docs

**Comment by Draaky** [comment]
Hasn't been updated since 27-06-2017...
