### ISSUE TITLE
Use of global variables in templates is unclear

### ISSUE THREAD

**Issue by rcarmo** [MicrosoftDocs/vsts-docs#4591]
I've been trying to get a global variable to work inside a template, and ${{ variables.GLOBAL }} is expanded to the null string for some reason. Either this is mis-documented or this is a bug.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6724abea-bbdc-bf66-ed5e-3214fa6c3e66
* Version Independent ID: 4f8dab21-3f0e-da32-cc0e-1d85c13c0065
* Content: [Job and step templates - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/templates?view=azure-devops#feedback)
* Content Source: [docs/pipelines/process/templates.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/templates.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @vtbassmatt
* Microsoft Alias: **macoope**

**Comment by vtbassmatt** [comment]
Can you post your pipeline (or preferably a minimal repro)? I'm not certain what's going on.

**Comment by rcarmo** [comment]
Sure. I have [an entire example pipeline](https://github.com/rcarmo/azure-pipelines-multiarch-docker) online.

I have to send in the auth info as parameters to [the job template](https://github.com/rcarmo/azure-pipelines-multiarch-docker/blob/master/.azure-pipelines-job.yml) because it cannot see the global variables I have set for the pipeline (i.e., `$DOCKER_USERNAME` and other variants expand to nothing at all).

**Comment by vtbassmatt** [comment]
Sorry for the delay, this fell off my radar.

You have a definition-defined variable but you're trying to reference it at template expansion time. The `variables` context only contains YAML-defined variables at template expansion time.

In the template, instead of referencing it as `${{ variables.DOCKER_USERNAME }}`, just use the `$(DOCKER_USERNAME)` syntax that you're currently using in the main pipeline definition.

```yaml
# ... snip
      steps:
# ... more snip
      - script: |
          echo $(DOCKER_PASSWORD) | $(DOCKER) login --username $(DOCKER_USERNAME) --password-stdin
          make push-$(ARCH)
```

**Comment by rcarmo** [comment]
Thanks. I tried that in earlier iterations and it did not work, but I’ll give it another go in a few hours and reply back here if there are any issues.
