### ISSUE TITLE
Support publish artifact to a special Azure Blob

### ISSUE THREAD

**Issue by zirain** [MicrosoftDocs/vsts-docs#4593]
Is there any plan about storage artifacts to private Azure Blob container?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b3f565b-88e4-88d6-a534-48ec21e6e3d8
* Version Independent ID: 9fca89ae-4a6e-a43a-2834-1a91ad44c256
* Content: [Publish Build Artifacts task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/publish-build-artifacts?view=azure-devops#feedback)
* Content Source: [docs/pipelines/tasks/utility/publish-build-artifacts.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/utility/publish-build-artifacts.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @DavidStaheli
* Microsoft Alias: **dastahel**

**Comment by msebolt** [comment]
@zirain Thank you for the question!

The product team publishes the roadmap [here](https://docs.microsoft.com/en-us/azure/devops/release-notes/).

If you can't find the information on the roadmap, please [submit your idea]( https://developercommunity.visualstudio.com/content/idea/post.html?space=21) here.
