### ISSUE TITLE
Dynamic CI Build Trigger for Classic Pipeline

### ISSUE THREAD

**Issue by gorillapower** [MicrosoftDocs/vsts-docs#4596]
We are trying to trigger a build using variables in the trigger path, but they dont seem to work. I know this feature is available in the yaml builds, will it be available for the classic build definition? The reason we havnt used yaml builds its because it doesnt suppport TFS repositories.

![image](https://user-images.githubusercontent.com/8879065/59929334-e5755300-9440-11e9-92a6-c08728ce2486.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5673ec1-c7d1-e0ac-043a-8fc3d5b226a9
* Version Independent ID: b4872831-51c0-6cf8-1c56-de20beb38a80
* Content: [Build pipeline triggers - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/triggers?view=azure-devops&tabs=classic#ci-triggers)
* Content Source: [docs/pipelines/build/triggers.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/build/triggers.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by msebolt** [comment]
@gorillapower Thanks for your question.

Please refer to the [roadmap](https://docs.microsoft.com/en-us/azure/devops/release-notes/).

If the feature can't be found on the roadmap, please [submit your idea]( https://developercommunity.visualstudio.com/content/idea/post.html?space=21) here.
