### ISSUE TITLE
Create custom fields on custom base process

### ISSUE THREAD

**Issue by ChristopherMank** [MicrosoftDocs/vsts-docs#460]
According to Sprint 121 (https://docs.microsoft.com/en-us/vsts/release-notes/2017/aug-04-team-services#work) you can now create a copy of a process. According to the notes, it's good practice to create a copy of a process, make your new updates, test and then move projecst to the new process. This is a way to test new process changes and I like this approach. Here is my feedback:

1. This should be somewhere in the VSTS docs, not just in sprint release notes.
2. If you follow this process, the Reference Name for the new fields will have a prefix of whatever process template the field was created under. So if you create a custom process called "ABC", the custom fields would be ABC.CustomField. If you create a new process to test new updates and name it ABC2, then those custom fields would be ABC2.CustomField2. While most people won't care, the API becomes confusing, trying to figure out if the field is prefixed with ABC or ABC2. This is a somewhat clean example. This gets ugly quick. So the suggestion (adding to the doc for my suggestion #1 above) is that you create a base custom process (ABC) that is not used by any team project and create all the custom fields there. Then the process templates that need it just add it. Then, all custom fields have the same prefixed Reference Name which makes API calls much happier. Hopefully this make sense :-).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bc086b3f-dda0-58d4-ab78-cdcc0a7f67d5
* Version Independent ID: 0a9bf2be-d61b-da59-659d-b9fd3114165a
* Content: [Add a custom field - VSTS](https://docs.microsoft.com/en-us/vsts/work/customize/process/customize-process-field?view=vsts#add-a-custom-field)
* Content Source: [docs/work/customize/process/customize-process-field.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/work/customize/process/customize-process-field.md)
* Service: **unspecified**
* GitHub Login: @erickson-doug
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@ChristopherMank - Thank you for your input. I've added your suggestion to my backlog and plan to update the content in the next several weeks.
