### ISSUE TITLE
Bullet list shortcut not working

### ISSUE THREAD

**Issue by Bar-Armon** [MicrosoftDocs/vsts-docs#4606]
Hi,
The shortcut mentioned above is not working for me. Any idea why?
The Numbered list shortcut does work. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 02128227-c915-a0d9-f919-c1ef2a3b834f
* Version Independent ID: bf4402f5-f9fe-a6d0-3738-01e2aca27209
* Content: [Keyboard shortcuts for work item form and Work Items hub - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/work-items/work-item-form-keyboard-shortcuts?view=azure-devops#feedback)
* Content Source: [docs/boards/work-items/work-item-form-keyboard-shortcuts.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/boards/work-items/work-item-form-keyboard-shortcuts.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @thomps23
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@Bar-Armon  - I just checked and found the Ctrl + .  does add a Bullet. Could you try again and see if it is working. If you can't make it work, please report it to our support team, https://developercommunity.visualstudio.com/spaces/21/index.html.

**Comment by mobrien-gw** [comment]
As per [Bar-Armon](https://github.com/Bar-Armon)'s post [on Jun 23, 2019](https://github.com/MicrosoftDocs/azure-devops-docs/issues/4606#issue-459549654), **Ctrl+.** does _not_ work for me, but **Ctrl+/** for numbered list does.
