### ISSUE TITLE
Options for hosting "Publish Profile"

### ISSUE THREAD

**Issue by mark-janos** [MicrosoftDocs/vsts-docs#4609]
It would really help if instructions were provided on how to use the "Secure files" feature to host Publish Profile .xml documents
https://docs.microsoft.com/en-us/azure/devops/pipelines/library/secure-files?view=azure-devops

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 19f07c04-6b05-0de0-9b74-e032226528a4
* Version Independent ID: f0363446-1415-4e48-4c40-9b56906654f2
* Content: [Azure SQL Database Deployment task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/sql-azure-dacpac-deployment?view=azure-devops#feedback)
* Content Source: [docs/pipelines/tasks/deploy/sql-azure-dacpac-deployment.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/deploy/sql-azure-dacpac-deployment.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by davidstaheli** [comment]
Thanks for the suggestion!  The documentation has been updated and will be live within a few days.
