### ISSUE TITLE
git command flag missing a dash

### ISSUE THREAD

**Issue by orshir** [MicrosoftDocs/vsts-docs#461]
in https://docs.microsoft.com/en-us/vsts/build-release/concepts/definitions/build/repository?view=vsts#alternative-to-using-the-checkout-submodules-option the command should end with --recursive not -recusive

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 41d4fcf8-3fd9-27b5-89e5-a026cc4a2b6a
* Version Independent ID: 76481ffb-aec5-50cd-6cdd-9e53c59e2933
* Content: [Build definition source repositories](https://docs.microsoft.com/en-us/vsts/build-release/concepts/definitions/build/repository?view=vsts#alternative-to-using-the-checkout-submodules-option)
* Content Source: [docs/build-release/concepts/definitions/build/repository.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/build-release/concepts/definitions/build/repository.md)
* Service: **unspecified**
* GitHub Login: @erickson-doug
* Microsoft Alias: **alewis**

**Comment by DavidStaheli** [comment]
This has been fixed:
https://docs.microsoft.com/en-us/vsts/build-release/concepts/definitions/build/repository?view=tfs-2015

Thanks a lot, @orshir!
@steved0x I don't have permission to close this issue.  Could you please?

**Comment by steved0x** [comment]
Thank you Andy for closing it.
