### ISSUE TITLE
The User Voice link is not active

### ISSUE THREAD

**Issue by tcarlander** [MicrosoftDocs/vsts-docs#4610]
https://visualstudio.uservoice.com/forums/330519-team-services/suggestions/15109674-allow-build-to-use-ssh-authentication-while-checki gives site deactivated

**Comment by WilliamAntonRohm** [comment]
@tcarlander Thanks for your feedback; we appreciate it. To make sure we have all the information needed to triage your issue, please let us know which topic you’re referencing, or provide more context around the general task.
