### ISSUE TITLE
New navigation is no longer in preview, update docs

### ISSUE THREAD

**Issue by jawn** [MicrosoftDocs/vsts-docs#4611]
Update the title and navigation link so the word preview is removed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eab519d8-dc41-91de-437a-4469edefddab
* Version Independent ID: edc98ac8-a89a-a79a-d75c-1435870a00d2
* Content: [Developing extensions for Azure DevOps Services vertical web navigation](https://docs.microsoft.com/en-us/azure/devops/extend/develop/web-navigation?view=azure-devops)
* Content Source: [docs/extend/develop/web-navigation.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/extend/develop/web-navigation.md)
* Product: **devops**
* Technology: **devops-ecosystem**
* GitHub Login: @willsmythe
* Microsoft Alias: **wismythe**

**Comment by WilliamAntonRohm** [comment]
@willsmythe -- Will, please confirm that vertical navigation is no longer in preview.  If it isn't, I'll create a PR to update the TOC & article.

Here's the current title and first sentence:

#### Guidance for extension developers impacted by new navigation preview
Our new vertical navigation preview brings with it changes that impact some extensions.

**Comment by WilliamAntonRohm** [comment]
@willsmythe -- I'm assigning this issue to you for now -- please let me know about the preview status and re-assign this issue to me if I need to create a PR.

**Comment by willsmythe** [comment]
@WilliamAntonRohm - correct (no longer in preview). It would made be good to have someone from Engineering (like @nkirchem or @apawast) review the rest of the content and make sure it's still applicable/correct.

**Comment by WilliamAntonRohm** [comment]
@willsmythe -- Will, thank you for that confirmation.

@apawast -- Apeksha, please review the above-mentioned PR 171.
