### ISSUE TITLE
Pipeline decorator example YAML is misleading

### ISSUE THREAD

**Issue by AndrewGibson100** [MicrosoftDocs/vsts-docs#4613]
The initial example YAML provided [here](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/extend/develop/add-pipeline-decorator.md#decorator-yaml) is misleading. If the example is used as is it will not work as the YAML must start with "steps:" in order for the pipeline decorator to function. This should be added to the example YAML.

**Comment by stephenmichaelf** [comment]
This has been fixed.
