### ISSUE TITLE
Can't work out source of parameter in yaml example

### ISSUE THREAD

**Issue by lordnelson** [MicrosoftDocs/vsts-docs#4615]
Looking at the yaml example: 
```inputs:
    appType: webAppContainer
```
I can't see where `appType` is coming from. Should it be `WebAppKind`?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 29c94df7-9de9-ea1a-8b77-d1e6023694dc
* Version Independent ID: a525989e-2e0a-0399-556e-9011ee95da4e
* Content: [Azure App Service Deploy task - Azure Pipelines](https://docs.microsoft.com/en-gb/azure/devops/pipelines/tasks/deploy/azure-rm-web-app-deployment?view=azure-devops#feedback)
* Content Source: [docs/pipelines/tasks/deploy/azure-rm-web-app-deployment.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/deploy/azure-rm-web-app-deployment.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by RoopeshNair** [comment]
In yaml, you don't have to specify the  `appType` input. It will be auto-detected at runtime. 
@N-Usha  - can you please get this updated?

**Comment by lordnelson** [comment]
Thanks for clarifying @RoopeshNair

**Comment by N-Usha** [comment]
Apologies for confusion @Iordnelson .
We have confirmed that appType input is NOT auto-detected for Azure App Service Deploy task and is a mandatory field in YAML.  We will have documentation updated to call out the accepted values for various app types.

**Comment by lordnelson** [comment]
Thanks @N-Usha I'm using ```WebAppKind: webApp``` for now and that seems to work fine.

**Comment by N-Usha** [comment]
Can be closed as the customer query is answered.
