### ISSUE TITLE
All the photos are from the old UI view

### ISSUE THREAD

**Issue by shayki5** [MicrosoftDocs/vsts-docs#4619]
Hi,

All the examples photos are from the old UI.
Can you update them to the new UI view?

Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 56437af3-75da-d219-5364-9b7927298ece
* Version Independent ID: ca01655a-9195-cf92-14b4-77ef66053dcf
* Content: [Extension Points](https://docs.microsoft.com/en-us/azure/devops/extend/reference/targets/overview?toc=%2Fazure%2Fdevops%2Fextend%2Ftoc.json&bc=%2Fazure%2Fdevops%2Fextend%2Fbreadcrumb%2Ftoc.json&view=azure-devops#feedback)
* Content Source: [docs/extend/reference/targets/overview.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/extend/reference/targets/overview.md)
* Product: **devops**
* Technology: **devops-ecosystem**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by chcomley** [comment]
Hi @shayki5, Thanks for the heads up. I've created a user story to capture this work, thank you.

**Comment by warren2k** [comment]
It's still not updated. When is the associated user story expected to be scheduled for work?

**Comment by chcomley** [comment]
Hi @warren2k, I currently have the iteration set for October. Thanks for checking in. I'll be in touch. Have a great weekend.

**Comment by chcomley** [comment]
@warren2k, As I begin working on this update, I've discovered a duplicate issue that's older and has more customer involvement. I'm combining these issues, so closing this one as a duplicate. Please refer to https://github.com/MicrosoftDocs/vsts-docs/issues/2020. I'll also @ mention you within that issue.

**Comment by warren2k** [comment]
Thanks.
