### ISSUE TITLE
Artifacts documentation clarification

### ISSUE THREAD

**Issue by spashx** [MicrosoftDocs/vsts-docs#4625]
Hi,

In the documentation of the Access Levels, filtered for Azure Devops Server 2019, the "Artifact" topics says:
https://docs.microsoft.com/en-us/azure/devops/organizations/security/access-levels?view=azure-devops-2019

> Artifacts
> Includes full access to all Azure Artifacts features (also referred to as package management), _up to 2GB free_

I think this applies only to Azure Devops Service, and not Server ? This should be clarified.

Regards,

**Comment by chasewilson** [comment]
Hello @spashx thanks for the feedback! The page has been updated and has the correct information listed now :) Thank you again and if you have anymore feedback. I hope you'll create a new issue :)
