### ISSUE TITLE
Use user defined build variables in Custom condition

### ISSUE THREAD

**Issue by MilanRaval** [MicrosoftDocs/vsts-docs#463]
I have added a user defined variable to the build definition, and that variable is updated by one of the build task. In the succeeding  task I want to check that variable value, and want to run task only if variable has some specific value. I am trying to do it using Custom conditions, but not able to find how to access the user defined variable's value in Custom conditions. Thanks !

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f151218-9a11-0078-e038-f96198a76143
* Version Independent ID: 09c4d032-62f3-d97c-79d7-6fbfd89910e9
* Content: [Conditional task expressions](https://docs.microsoft.com/en-us/vsts/build-release/concepts/process/conditions?view=vsts)
* Content Source: [docs/build-release/concepts/process/conditions.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/build-release/concepts/process/conditions.md)
* Service: **unspecified**
* GitHub Login: @erickson-doug
* Microsoft Alias: **alewis**

**Comment by AWBuchanan7** [comment]
I am also having this same problem.

**Comment by andyjlewis** [comment]
Is the task where you are trying to reference the variable in a different phase? What version are you using (e.g. VSTS, TFS 2018, etc.)?

**Comment by andyjlewis** [comment]
is the previous task in a different phase?

**Comment by lXxTheGhostxXl** [comment]
Same phase, for ex: Task 1: Powershell script to execute oracle scripts Task 2: IIS web deploy. Now, if the task 1 returns a variable and based on that variable i need to run task 2. Can this be done in current VSTS?

**Comment by andyjlewis** [comment]
yes: https://docs.microsoft.com/en-us/vsts/build-release/concepts/definitions/build/variables?view=vsts&tabs=batch#set-in-script

**Comment by lifesoccult** [comment]
@andyjlewis Why was this closed? The page you reference does not provide detail on how to handle custom variables in a condition. I have the same problem. Here's my condition:

`condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'), eq(variables[MYVAR], 'false'))`

And the error VSTS throws:

`2018-08-14T14:26:03.3824020Z ##[error]Unrecognized value: 'MYVAR'. Located at position 89 within expression: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'), eq(variables[MYVAR], 'false')).`

My variable is defined within a variable group library that is associated with the build. I'm not sure if I'm correctly referencing the variable as well as if VSTS is just unable to handle custom vars in a condition statement. Currently all of this is in one phase, but it needs to work for multi-phase builds too.

**Comment by ggirard07** [comment]
@lifesoccult in the code you pasted `MYVAR` is not quoted between `''` as variable keys should be. Try with `'MYVAR'`.

**Comment by XmlmXmlmX** [comment]
This issue isn't solved. Custom variables are not working.

**Comment by darshankumarys** [comment]
I need to run tasks only when i find  a file from build drop artifact, how can i put in custom condition?

**Comment by vijayma** [comment]
@darshankumarys Write a script task to check for the file and to set a variable. Then use the variable as a condition to the other task.

Please open new issues for the problems that you discover in this area, as it is not clear whether you are facing the problem in build, in release, when you use variable groups, or when you use task groups.

**Comment by MykolaPelyp-SoftServe** [comment]
> @lifesoccult in the code you pasted `MYVAR` is not quoted between `''` as variable keys should be. Try with `variables['MYVAR']` instead.

This solution works, thanks! Microsoft although recommends using something like:
and(succeeded(), eq('${{ variables.generateCerts }}', true))
Which is NOT working, what worked for me:

```and(succeeded(), eq(variables['generateCerts'], 'true'))```
Where ```generateCerts``` is variable that are contained within our Variable Group
