### ISSUE TITLE
Didn't Found git repository URL

### ISSUE THREAD

**Issue by ankitthakkar23** [MicrosoftDocs/vsts-docs#4636]
I have gone through this document. I didn't understood that where is git repository URL. I want to do SVN to Git Migration then where I can provide my New Git repository URL.

Is Bare Repository is required ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: edd6cbc8-5e3b-c3a1-4672-d42510cc058b
* Version Independent ID: 8fe81fb5-7c2d-2562-5659-55fccbb3126c
* Content: [Migrate from Subversion (SVN) to Git](https://docs.microsoft.com/en-us/azure/devops/repos/git/perform-migration-from-svn-to-git?view=azure-devops#feedback)
* Content Source: [docs/repos/git/perform-migration-from-svn-to-git.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/repos/git/perform-migration-from-svn-to-git.md)
* Product: **devops**
* Technology: **devops-whitepapers**
* GitHub Login: @hkamel
* Microsoft Alias: **hkamel**

**Comment by msebolt** [comment]
@ankitthakkar23 Thank you for the feedback!  

Yes, the process does require a local bare Git repo under step **Push repository to a bare git repository**.

See Step 7 of the [following](https://epicserve-docs.readthedocs.io/en/latest/git/svn_to_git.html) for a good example of moving your local repo to a remote URL.  This missing documentation is noted in https://github.com/MicrosoftDocs/vsts-docs/issues/4496.

**Comment by ankitthakkar23** [comment]
@msebolt  Thank you so much for Reply !!! I appreciate your efforts.
