### ISSUE TITLE
Re-deploy

### ISSUE THREAD

**Issue by randyram-at-ms** [MicrosoftDocs/vsts-docs#4637]
It's not clear if I am able to re-deploy, it seems like I can't.  This is important to re-run a test deployment when the tests fail.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5aeeaace-1c5b-a51b-e41f-f25b806155b8
* Version Independent ID: fd7ff690-b2e4-41c7-a342-e528b911c6e1
* Content: [Deployment jobs - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/deployment-jobs?view=azure-devops)
* Content Source: [docs/pipelines/process/deployment-jobs.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/deployment-jobs.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @shashankbarsin
* Microsoft Alias: **shasb**

**Comment by RoopeshNair** [comment]
@vijayma for re-deploy actions

**Comment by michaelw85** [comment]
Following, I would love to be able to redeploy without having to run a new build. Using existing artifacts (existing version) to redeploy is very useful for rollbacks!

**Comment by poveilleux** [comment]
I asked the question on [StackOverflow](https://stackoverflow.com/questions/56938975/is-it-possible-to-manually-trigger-a-stage-when-using-yaml-azure-pipelines) and someone told me there is a [feature request](https://developercommunity.visualstudio.com/idea/578950/re-run-a-single-stage-in-a-multi-stage-pipeline.html) and they already have [item](https://dev.azure.com/mseng/AzureDevOpsRoadmap/_workitems/edit/1454027) on their roadmap for this.

**Comment by michaelw85** [comment]
Thx for the info, upvoted the feature request.

**Comment by vijayma** [comment]
You can now do this using the retry feature. If you select this action on a failed stage, then it re-runs the failed jobs in that stage. If you select this action on a successful stage, it re-runs all the jobs in that stage.
