### ISSUE TITLE
How to define an array value?

### ISSUE THREAD

**Issue by andyli** [MicrosoftDocs/vsts-docs#4641]
`containsValue` takes an array for its first argument, but there is no doc on how to provide an array. I've tried using `containsValue(['windows', 'linux32'], parameters.platform)`, but that failed with error `Unexpected symbol: '['.`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77c58a78-a567-e99a-9eb7-62dddd1b90b6
* Version Independent ID: 680a79bc-11de-39fc-43e3-e07dc762db18
* Content: [Expressions - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/expressions?view=azure-devops#feedback)
* Content Source: [docs/pipelines/process/expressions.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/expressions.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by vtbassmatt** [comment]
@stephenmichaelf can you help me understand the correct syntax and where that function can be used? I don't mind to update the doc, once I get a little help.

**Comment by MisinformedDNA** [comment]
From reference, here is the updated documentation:

> There is no literal syntax in a YAML pipeline for specifying an array. This function is of limited use in general pipelines. It's intended for use in the pipeline decorator context with system-provided arrays such as the list of steps.
