### ISSUE TITLE
Secret passed to subsequent tasks as ****

### ISSUE THREAD

**Issue by darrenferguson** [MicrosoftDocs/vsts-docs#4644]
I'm getting very confused....

In my build pipeline I have a keyvault task:

task: AzureKeyVault@1
inputs:
azureSubscription: '**** redacted **'
KeyVaultName: '' redacted ******'
SecretsFilter: 'MoriyamaTest'
And in the debug output of this task I see:

##[debug]set MoriyamaTest=********
##[debug]Processed: ##vso[task.setvariable variable=MoriyamaTest;issecret=true;]***
##[debug]task result: Succeeded
##[debug]Processed: ##vso[task.complete result=Succeeded;]

Then I have a following powershell Task:

powershell: echo $env:MYSECRET
env:
MySecret: $(MoriyamaTest)
And the output from that is as follows:

##[command]"C:\windows\System32\WindowsPowerShell\v1.0\powershell.exe" -NoLogo -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command ". 'd:\a_temp\0ccb3c44-e414-4bbd-baf5-fb2462b02e5b.ps1'"

##[debug]$LASTEXITCODE is not set.

So for the value of my passed environment variable MySecret I am getting the string "***"

How can I pass a secret from keyvault to a subsequent powershell task?

Many Thanks.

**Comment by msebolt** [comment]
@darrenferguson Thank you for the feedback!

Please review [secrets](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch#secret-variables) and creating [variable groups](https://docs.microsoft.com/en-us/azure/devops/pipelines/library/variable-groups?view=azure-devops&tabs=yaml) to pass between tasks.  

Also see this [section](https://docs.microsoft.com/en-us/azure/devops/pipelines/library/variable-groups?view=azure-devops&tabs=yaml#link-secrets-from-an-azure-key-vault) for specifics on key vault variables.

If this still doesn't address the issue please feel free to add additional comments below.
