### ISSUE TITLE
Preserve VNet clarification

### ISSUE THREAD

**Issue by JackStromberg** [MicrosoftDocs/vsts-docs#4649]
Can you please clarify what Preserve VNet means in regards to Arguments?  Does this mean it preserves the source or destination slot's vnet settings?  I.e. if I swap from stage to prod, does stage's vnet configure get moved to prod when this is set to true or does it mean stage preserves it's vnet configuration and prod's vnet configuration is used?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f07461b2-a8a2-ec6f-769b-14b384777be3
* Version Independent ID: 2c72f09d-b198-461c-fc0d-1c3bd0a870c4
* Content: [Azure App Service Manage task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-app-service-manage?view=azure-devops#arguments)
* Content Source: [docs/pipelines/tasks/deploy/azure-app-service-manage.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/deploy/azure-app-service-manage.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by RoopeshNair** [comment]
If you want to swap the vnet config, then leave it unchecked.
The task actually passes this preference (true or false) to Azure REST API.

![image](https://user-images.githubusercontent.com/1370480/60248502-653b6b80-98e0-11e9-8447-6acd57e427f8.png)
