### ISSUE TITLE
Document the entire options object

### ISSUE THREAD

**Issue by adamdavies001** [MicrosoftDocs/vsts-docs#4650]
This page is apparently the API reference page for the Combo Control yet I see absolutely no useful information here. Document the entirety of the `options` object including the details of the `change` function and its properties/methods.

From the Combo Control examples page, I see that the `change` function has a `getText` method. What other properties and methods are there? Can I set the Combo Control's source _after_ I create it? This could all be answered with complete documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97777da6-f32b-a0f2-733f-91304a3ef163
* Version Independent ID: 70bf2041-914b-3f7a-3c05-f026b9c91b5f
* Content: [Combo Control](https://docs.microsoft.com/en-us/azure/devops/extend/reference/client/controls/combo?view=azure-devops)
* Content Source: [docs/extend/reference/client/controls/combo.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/extend/reference/client/controls/combo.md)
* Product: **devops**
* Technology: **devops-ecosystem**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by chcomley** [comment]
Hi @adamdavies001, Thanks for your feedback. I've created a user story on my backlog to address this and will be in touch. Thanks again.

**Comment by chcomley** [comment]
@adamdavies001, Here's a link to the newest documentation: https://developer.microsoft.com/en-us/azure-devops/. Please let us know if you have any further questions, thank you! Thanks for your feedback.
