### ISSUE TITLE
Code download audit logs

### ISSUE THREAD

**Issue by mirlenbrink** [MicrosoftDocs/vsts-docs#4651]
The intro to this article states "In some limited cases, it can also include accessing an artifact. Think permissions changes, resource deletion, code download, accessing the auditing feature, and much more." 

Of particular interest to me is the "code download" mention, as I'd like to be able to audit who download code across the organization.  However, I see no mention of Repos or code downloads of any kind under the Filter audit log categories and areas that are supported.

Are audit logs for code access available or are they a planned feature coming soon?  I'm not able to find any audit logs myself in my current organizations.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 52f60b32-5c3c-f01a-cbbf-f4e9bd17a3fc
* Version Independent ID: 94753ea7-b465-f92e-10c2-8b17d995e4ff
* Content: [Access, export, filter audit logs for Azure DevOps - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/settings/azure-devops-auditing?view=azure-devops)
* Content Source: [docs/organizations/settings/azure-devops-auditing.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/settings/azure-devops-auditing.md)
* Product: **devops**
* Technology: **devops-settings**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @mirlenbrink, Thanks for reaching out. I'll follow up with the PM and get back to you on this. Thanks again.

**Comment by chcomley** [comment]
Hi @mirlenbrink, We've updated the article, which should go live within just a few hours. Thanks again for the feedback. Here's what we added to the table in the [Areas section of the article](https://docs.microsoft.com/en-us/azure/devops/organizations/settings/azure-devops-auditing?view=azure-devops#areas):
|Git        | Branch policies, repository create, repository delete, repository rename |
Do let us know if you have further questions. Thanks!

**Comment by mirlenbrink** [comment]
Thanks for updating the content to make it more clear, however, I really would like the ability to audit code downloads (which is the wording that was removed 😏).  Do you have a roadmap of audit events that are coming?  Do you happen to know if code downloads or repo access events are planned?

**Comment by chcomley** [comment]
Hi @mirlenbrink, Check out our blog about [auditing in public preview](https://devblogs.microsoft.com/devops/auditing-for-azure-devops-is-now-in-public-preview/). You can share your thoughts directly with the product team using [@AzureDevOps, Developer Community](https://twitter.com/AzureDevOps), or comment on the blog post. You can also search for and upvote a feature suggestion, however I didn't find one that appeared to be related, or [create your own feature suggestion](https://developercommunity.visualstudio.com/spaces/8/index.html). Hope that's helpful. Have a great weekend!
