### ISSUE TITLE
Variable Inconsistency Builds Vs Releases

### ISSUE THREAD

**Issue by jjdougherty** [MicrosoftDocs/vsts-docs#4652]
When i post a variable from a powershell script to the build's variable stream I have no issues. See link

However when i post variable from a powershell script to the release's variable stream It doesn't look to be posting that variable to the stream.
[ImgurLink](https://imgur.com/a/eEYu8F9)

Is there some doc ive missed that discusses the proper way to reference/set release variables? 

forgive the poor formatting on this. This is my first post 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd7e0bd3-1f7d-d7b6-cc72-5ef63c31b46a
* Version Independent ID: dae87abd-b73d-9120-bcdb-6097d4b40f2a
* Content: [Variables - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=classic%2Cpowershell#feedback)
* Content Source: [docs/pipelines/process/variables.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/variables.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by jjdougherty** [comment]
I've tried updating the release steps to also have inline 
"$No = "No"

write-host "##vso[task.setvariable variable=dog;isOutput=true]$No"
" and reference it by $(POWERSHELL1.DOG)

Still no luck. It looks like releases dont store/reference variables the same as builds do

**Comment by jjdougherty** [comment]
Running a Get-ChildItem Env: after the variable is set but before we try to call it by name I'm able to see it in the builds



Name Value
---- -----

POWERSHELL1_DOG No



Same code but in a release the Get-ChildItem Env: results in this



Name Value
---- -----
69DAB4253E34CA88AF901A4F8FA... No

**Comment by jjdougherty** [comment]
looking a little deeper that value of SYSTEM_TASKINSTANCENAME but this value changes every build so im not sure how its useful or referencable by tasks in the release sequence or why this behaves differently than builds

**Comment by jjdougherty** [comment]
Looks like using ;isOutput=true is not necessary on releases. When i remove it from my variable declaration and call it by $(DOG) it works

**Comment by msebolt** [comment]
@jjdougherty Thanks for the feedback!

It appears as though you resolved the issue. Is there a particular section of the article that you can recommend a need for update?
