### ISSUE TITLE
Document whether and how Universal Packages can be consumed without the azure CLI

### ISSUE THREAD

**Issue by wez** [MicrosoftDocs/vsts-docs#4653]
This page doesn't include information on how to access this class of artifact *without* the azure CLI.   This is perhaps a duplicate of https://github.com/MicrosoftDocs/vsts-docs/issues/3834 but since this particular page duplicates some of that information, this would also be a useful fact to include here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77bcd39f-91ab-bb93-40fc-dd4fc5f2374f
* Version Independent ID: c228aece-669a-57d6-b3ed-d427586f8a61
* Content: [Publish and then download a Universal Package](https://docs.microsoft.com/en-us/azure/devops/artifacts/quickstarts/universal-packages?view=azure-devops&tabs=azuredevops#feedback)
* Content Source: [docs/artifacts/quickstarts/universal-packages.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/artifacts/quickstarts/universal-packages.md)
* Product: **devops**
* Technology: **devops-artifacts**
* GitHub Login: @chasewilson
* Microsoft Alias: **phwilson**

**Comment by melcloud** [comment]
This will be really good if we can do that through HTTP call. We can perhaps use this as a source for Terraform modules

**Comment by mijacobs** [comment]
Hi @wez, @melcloud, 

You must use the Azure CLI to download the package. Azure DevOps doesn't support direct HTTP/HTTPS download links or other ways to download the package. I've added this info to the article. 

Thank you for calling this issue to our attention!

**Comment by cpyfferoen** [comment]
I've made my feelings known on #3834. But w/o a way to download (button, http) outside of requiring an install of the Azure CLI installed **AND** the azure-devops extension to the Azure CLI - universal package feeds are *__practically__* useless. Because practicality matters in the real world.
