### ISSUE TITLE
Parameter re-use

### ISSUE THREAD

**Issue by hbuckle** [MicrosoftDocs/vsts-docs#4661]
I am creating templates to use for multi-stage builds. I would like to pass in a list of environments as parameters to each template and iterate over them, but I would like to define the list of environments in one place (ideally in its own template). Is it possible to use a template for defining default parameter values?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6724abea-bbdc-bf66-ed5e-3214fa6c3e66
* Version Independent ID: 4f8dab21-3f0e-da32-cc0e-1d85c13c0065
* Content: [Job and step templates - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/templates?view=azure-devops#feedback)
* Content Source: [docs/pipelines/process/templates.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/templates.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @vtbassmatt
* Microsoft Alias: **macoope**

**Comment by vtbassmatt** [comment]
That's not possible today. Please feel free to file a suggestion on [Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html), though, as I think that idea has a lot of merit.
