### ISSUE TITLE
"A request for release creation failed" missing in documentation

### ISSUE THREAD

**Issue by alenroki** [MicrosoftDocs/vsts-docs#4662]
https://docs.microsoft.com/en-us/azure/devops/notifications/oob-built-in-notifications?view=azure-devops

"A request for release creation failed" this one is part of the Default Subscriptions in Azure DevOps but is not described in the documenation.

**Comment by chcomley** [comment]
Hi @alenroki, Thanks for your feedback. I've created a user story to capture looking into this and will be in touch. Have a great day!

**Comment by chcomley** [comment]
Hi @alenroki, We aren't seeing it in the global notification subscriptions and believe this just falls under the following subscription as it’s a class of failure. 
![notifications](https://user-images.githubusercontent.com/35748196/60462915-75648b00-9bff-11e9-856f-0b2b96e40ebb.jpg)
I don't believe the docs need to be updated at this point. I'll be closing out this issue and the corresponding user story. Please let me know if you have any questions at all! Thanks for reaching out.
