### ISSUE TITLE
incorrect azpipeline command

### ISSUE THREAD

**Issue by perkops** [MicrosoftDocs/vsts-docs#4666]
In the same browser, start a new tab, navigate to https://slack.com, and sign in to your work space (use web client). Run the /azipelines signout command followed by the /azipelines signin command.

Should be:

In the same browser, start a new tab, navigate to https://slack.com, and sign in to your work space (use web client). Run the /azpipelines signout command followed by the /azpipelines signin command.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 99a6f5aa-7e92-a028-d13e-e1e4b7fede86
* Version Independent ID: be7e5d7c-0033-6b72-4bd1-809f7d1894aa
* Content: [Azure Pipelines with Slack - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/integrations/slack?view=azure-devops#configuration-failed-please-make-sure-that-the-organization-organization-name-exists-and-that-you-have-sufficient-permissions)
* Content Source: [docs/pipelines/integrations/slack.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/integrations/slack.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @atinb
* Microsoft Alias: **atinb**

**Comment by steved0x** [comment]
@perkops Thanks for letting us know, we just checked in a fix and it should be live soon.
