### ISSUE TITLE
FYI: Selecting "TFS 2018" in the dropdown does not result in "TFS 2018" body selection.

### ISSUE THREAD

**Issue by RubixRevenge** [MicrosoftDocs/vsts-docs#467]
To replicate 

1. Go to https://docs.microsoft.com/en-us/vsts/user-guide/?view=tfs-2018
2. The content dropdown above the filter box says "Team Foundation Server 2018"
3. The body (which should have updated to match the selection) says "VSTS  New to Visual Studio Team Services (VSTS)?" 

That is incorrect. If a user selects "TFS 2018" then the body content should match that and only that. VSTS should not be in the body at all.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9af38f5c-9fac-bd18-4102-3640d7d1c5a4
* Version Independent ID: 46cdad70-76a0-d5b6-6941-492a72fd8181
* Content: [Guide for users new to VSTS](https://docs.microsoft.com/en-us/vsts/user-guide/?view=tfs-2018#feedback)
* Content Source: [docs/user-guide/index.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/user-guide/index.md)
* Service: **unspecified**
* GitHub Login: @erickson-doug
* Microsoft Alias: **kaelli**

**Comment by steved0x** [comment]
@RubixRevenge We're still working on it and I agree. Right now the VSTS and TFS version switchers are at more of a "macro" level but we are fine tuning it. Look for these types of changes on the top level pages and articles (like this one) coming soon, and the rest of the topics on an ongoing basis. If you see one that is wrong, please let us know. Thank you.
