### ISSUE TITLE
Duplicate Text in Introduction Text

### ISSUE THREAD

**Issue by nbkhope** [MicrosoftDocs/vsts-docs#4671]
The second paragraph in the introductory text has the same content as the first paragraph:

```
You use cumulative flow diagrams (CFD) to monitor the flow of work through a system. The two primary metrics to track, cycle time and lead time, can be extracted from the chart. 
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ea9310f2-b131-3903-0c15-5bbebbd95959
* Version Independent ID: 22486f35-4e75-8dd4-7c97-cd3c6e8245fc
* Content: [Cumulative flow guidance - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/report/dashboards/cumulative-flow-cycle-lead-time-guidance?view=azure-devops)
* Content Source: [docs/report/dashboards/cumulative-flow-cycle-lead-time-guidance.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/report/dashboards/cumulative-flow-cycle-lead-time-guidance.md)
* Product: **devops**
* Technology: **devops-analytics**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by WilliamAntonRohm** [comment]
Documentation update is in https://dev.azure.com/mseng/TechnicalContent/_git/vsts-docs-pr/pullrequest/491370

**Comment by WilliamAntonRohm** [comment]
@nbkhope -- Renan, thank you for your feedback.  I have updated the documentation and it should be live by tomorrow.

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
