### ISSUE TITLE
Unable to get notifications (only) when build quality change

### ISSUE THREAD

**Issue by sherland** [MicrosoftDocs/vsts-docs#4673]
According to this document it should be possible to get notifications only when a build quality changes:
Category: Build
Template: A build's quality changes

The templates specified here does not match what is currently availabe in the gui. (At least for me.)
In the New subscription dialog the Build category contains the following templates:
- A build completes
- A build fails
- A legacy XAML build controller or agent's status changes
- A legacy XAML build's quality changes

We don't use legacy XAML builds. How can I configure a notification so that it's only triggering when the build's quality change?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66283a57-5d7c-2882-7055-89c51aab3a9a
* Version Independent ID: 58f97c9f-e9a4-1b57-71b7-aad213bb434e
* Content: [Default and supported notifications - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/notifications/oob-built-in-notifications?view=azure-devops)
* Content Source: [docs/notifications/oob-built-in-notifications.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/notifications/oob-built-in-notifications.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @sherland, I've reached out to our PM and will let you know what I find. Thanks to you for reaching out!

**Comment by chcomley** [comment]
Hi @sherland, Azure DevOps Support can better assist you with technical help. Please create a support ticket here: https://visualstudio.microsoft.com/vs/support/#talktous.  
Thanks for reaching out. Let us know if you have further questions about the documentation! Thanks

**Comment by sherland** [comment]
@chcomley , I don't understand. Are you saying that the documentation is correct, and that the list I get is "wrong" for some reason?

**Comment by chcomley** [comment]
Hi @sherland, Sorry for the confusion. The docs are correct, as the PM has advised me to direct you to Support for assistance: https://visualstudio.microsoft.com/vs/support/#talktous. Thank you!

**Comment by sherland** [comment]
For future readers, I'm adding a printscreen of the notifications window as it is for me now. As seen, this does not match the documentation.

![image](https://user-images.githubusercontent.com/1142647/60574047-1460c280-9d79-11e9-982e-35bf607ebef7.png)

I will add more info later if the issue is resolved.
