### ISSUE TITLE
Documentation for "pipeline" key is incorrect

### ISSUE THREAD

**Issue by MakotoE** [MicrosoftDocs/vsts-docs#4674]
I got confused with this argument as the documentation says that pipeline argument is "The name of the build pipeline." but it should be "The definition ID of the build pipeline."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b03d67d0-8738-72e6-dbe7-324c1784d4fc
* Version Independent ID: bbb4d774-cd98-3ecb-7ccf-5f49e6f2b425
* Content: [Download Pipeline Artifact task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/download-pipeline-artifact?view=azure-devops#)
* Content Source: [docs/pipelines/tasks/utility/download-pipeline-artifact.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/utility/download-pipeline-artifact.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @willsmythe
* Microsoft Alias: **wismyth**

**Comment by chasewilson** [comment]
Hey @MakotoE Thanks for the feedback! I went ahead and Updated that terminology to match your suggestion. I think it does clarify better than What we had before. Thanks again and I hope we'll get more feedback from you :)
