### ISSUE TITLE
Please make it more visible what is source and what is target

### ISSUE THREAD

**Issue by weitzhandler** [MicrosoftDocs/vsts-docs#4677]
Hi,
I always find myself coming back to check if source is the server or is it target.
Please make it more visible/TL;DR.
Best thing would be if add tooltips in VS.

![image](https://user-images.githubusercontent.com/2716316/60345094-e23e1200-99c0-11e9-8ae7-d188a395bc8c.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e2e2ddbb-512d-fe28-55c2-bfc4ff8aad73
* Version Independent ID: 9b7770d7-7f5d-3cb7-c619-a5cd23b5da09
* Content: [Resolve Git merge conflicts - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/merging?view=azure-devops&tabs=visual-studio)
* Content Source: [docs/repos/git/merging.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/repos/git/merging.md)
* Product: **devops**
* Technology: **devops-code-git**
* GitHub Login: @apawast
* Microsoft Alias: **sdanie**

**Comment by WilliamAntonRohm** [comment]
It looks like you've encountered an issue with the product itself, rather than an issue with the documentation. To make sure it gets in front of the right people, please [submit your bug]( https://developercommunity.visualstudio.com/content/problem/post.html?space=21) here.
