### ISSUE TITLE
Multiline scripts

### ISSUE THREAD

**Issue by KbLev** [MicrosoftDocs/vsts-docs#4678]
Is it possible to do multi-line scripts using a single step?

     steps:
      - script: echo first line of script
      - script: echo second line of script

This piece of code creates two steps instead of one.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a0e444c2-69c6-4d71-6fd0-94d0f4097d3a
* Version Independent ID: 3a727833-1cc3-c2fb-c5b3-22605eee2721
* Content: [PowerShell task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/powershell?view=azure-devops)
* Content Source: [docs/pipelines/tasks/utility/powershell.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/utility/powershell.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @vtbassmatt
* Microsoft Alias: **macoope**

**Comment by vtbassmatt** [comment]
```yaml
- script: |
    echo line 1
    echo line 2
```

YAML is complicated enough that someone's put up a whole domain related to it 🤣 : https://yaml-multiline.info/
