### ISSUE TITLE
Organisation Settings has no Security command

### ISSUE THREAD

**Issue by danpetitt** [MicrosoftDocs/vsts-docs#4680]
There is only a security heading which contains commands for policies and permissions; go into permissions and you cannot edit anything except the group description. There is nowhere I can see to assign users to a organisation group

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce8b2923-a3dc-7055-6550-d4943faa5a68
* Version Independent ID: fce8bd86-a25c-341e-5be4-61f19e4dd08f
* Content: [View permissions for yourself or others - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/security/view-permissions?view=azure-devops)
* Content Source: [docs/organizations/security/view-permissions.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/security/view-permissions.md)
* Product: **devops**
* Technology: **devops-security**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by WilliamAntonRohm** [comment]
It looks like you've encountered an issue with the product itself, rather than an issue with the documentation. To make sure it gets in front of the right people, please [submit your bug]( https://developercommunity.visualstudio.com/content/problem/post.html?space=21) here.
