### ISSUE TITLE
Support for Wikimedia Foundation markdown style

### ISSUE THREAD

**Issue by khooz** [MicrosoftDocs/vsts-docs#4682]
Hi,

I think the MediaWiki markdown (Markdown Extra) for wikis are rich and mature and can have some positive impact on the semantic of data stored in wikis. For instance, the `infobox` is a good way of documenting objects within a system and information about that object can be obtained in a glance.

Another well-designed aspect of MediaWiki's markdown is inline image-boxes with rich information, templating, and entry categorisation.

Here's a [sample link](https://en.wikipedia.org/wiki/2010_Men%27s_Junior_European_Volleyball_Championship) which shows the power of templating and other aspects of Wikimedia's markdown.

Thanks!

**Comment by WilliamAntonRohm** [comment]
Thanks for the suggestion! The product teams aren’t always watching this repository, so to make sure it gets in front of them for triage, please [submit your idea]( https://developercommunity.visualstudio.com/content/idea/post.html?space=21) here.
