### ISSUE TITLE
What has this decision taken for?

### ISSUE THREAD

**Issue by soroshsabz** [MicrosoftDocs/vsts-docs#4686]
ITNOA

I think this feature is very useful for enterprise software development team and company, and I think Visual Studio and TFS (Azure Dev Ops) try to provide unified and complete solution for development teams and company so why you have take this decision? why Microsoft deprecate useful features from products?

I think it is good to give some descriptions about cause of this decision and rationality. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cde00a22-c654-f6e9-5bad-c4deb0852899
* Version Independent ID: 88ff6f31-199d-e3f6-bc68-be91dc695b0e
* Content: [Load test overview - Azure Test Plans](https://docs.microsoft.com/en-us/azure/devops/test/load-test/overview?view=azure-devops)
* Content Source: [docs/test/load-test/overview.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/test/load-test/overview.md)
* Product: **devops**
* Technology: **devops-test**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by WilliamAntonRohm** [comment]
Thanks for the suggestion! The product teams aren’t always watching this repository, so to make sure it gets in front of them for triage, please [submit your idea]( https://developercommunity.visualstudio.com/content/idea/post.html?space=21) here.
