### ISSUE TITLE
Can't use doublestar/globstar (e.g **/nested) 

### ISSUE THREAD

**Issue by DrSensor** [MicrosoftDocs/vsts-docs#4687]
All vm (ubuntu, windows, mac) still use Bash version 3.1 instead of 4 or 5.
`shopt -s globstar` only available on v4 or newer ⚠️
https://www.linuxjournal.com/content/globstar-new-bash-globbing-option

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 450ac349-5c33-6cdf-1ecd-6eb989a00334
* Version Independent ID: a7119c1a-59b2-3081-a241-e93aa0d6b4b9
* Content: [Bash task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/bash?view=azure-devops)
* Content Source: [docs/pipelines/tasks/utility/bash.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/utility/bash.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @vtbassmatt
* Microsoft Alias: **macoope**

**Comment by DrSensor** [comment]
When I applied `#!/usr/bin/env bash` it works fine **except** for `macos-10.13`.
```console
##[section]Starting: Package crates
==============================================================================
Task         : Bash
Description  : Run a Bash script on macOS, Linux, or Windows
Version      : 3.151.1
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/bash
==============================================================================
Generating script.
========================== Starting Command Output ===========================
[command]/bin/bash --noprofile --norc /Users/vsts/agent/2.153.2/work/_temp/fb1cb9c1-c9a2-4a51-84d6-2be04acffa1f.sh
./scripts/package.sh: line 3: shopt: globstar: invalid shell option name
##[error]Bash exited with code '1'.
##[section]Finishing: Package crates
```

**Comment by vtbassmatt** [comment]
Apple ships the Bash version they ship on Mac hardware.
