### ISSUE TITLE
Type of Variable Set By a Script

### ISSUE THREAD

**Issue by MarkKoz** [MicrosoftDocs/vsts-docs#4690]
It's not specified what the type of a variable set by a script is (i.e. via `##vso[task.setvariable ...`). Experimentation has led me to the conclusion that it's always a string. It would be nice to mention this in the docs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd7e0bd3-1f7d-d7b6-cc72-5ef63c31b46a
* Version Independent ID: dae87abd-b73d-9120-bcdb-6097d4b40f2a
* Content: [Variables - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch#share-variables-across-pipelines)
* Content Source: [docs/pipelines/process/variables.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/variables.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by damccorm** [comment]
Hey, thanks for the feeback! I'm taking a look

**Comment by damccorm** [comment]
Thank you for your feedback. 
The article reference is being updated to address the issue.
