### ISSUE TITLE
Connect Azure AD with Azure DevOps On Premises 

### ISSUE THREAD

**Issue by omerahm** [MicrosoftDocs/vsts-docs#4692]
Can you please guide how to connect Azure DevOps on premises with Azure AD to get the users' details?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 031380a0-4f04-4105-199a-81715b42c653
* Version Independent ID: 570b2795-90ad-32b4-7ad0-1fceb186ffa3
* Content: [Connect organization to Azure Active Directory - Azure DevOps Services](https://docs.microsoft.com/en-gb/azure/devops/organizations/accounts/connect-organization-to-azure-ad?view=azure-devops#feedback)
* Content Source: [docs/organizations/accounts/connect-organization-to-azure-ad.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/accounts/connect-organization-to-azure-ad.md)
* Product: **devops**
* Technology: **devops-accounts**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @omerahm, 

Azure DevOps on-premises can connect with Active Directory, but not Azure Active Directory.

Try this article for some more info: http://www.tfstutorial.com/active-directory-integration

**Comment by omerahm** [comment]
Thanks for the article it works for me but our what if we connect our AD with Azure AD then how will it be reflected can it work in the same way?

**Comment by chcomley** [comment]
Go to the [Hybrid identity documentation](https://docs.microsoft.com/en-us/azure/active-directory/hybrid/). If you browse through these articles, I believe you'll find your answer. Do let me know if not, please.
