### ISSUE TITLE
Broken hyperlinks

### ISSUE THREAD

**Issue by alexmpmenezes** [MicrosoftDocs/vsts-docs#4697]
Hi, 

Just found two broken hyperlink under the page: 
https://docs.microsoft.com/en-us/azure/devops/user-guide/sign-up-invite-teammates?view=azure-devops#create-a-project

Please review the hyperlinks in the sentence: "See choosing the right version control for your project and choose a process for guidance"

![image](https://user-images.githubusercontent.com/40580177/60436886-5cfb6d00-9c0d-11e9-93b3-dfa4de85f2cd.png)

Best Regards
Alex

**Comment by WilliamAntonRohm** [comment]
@alexmpmenezes -- Alex, thank you for your feedback.  Those links appear to be working now.
