### ISSUE TITLE
Priority in parallel jobs

### ISSUE THREAD

**Issue by PaulVrugt** [MicrosoftDocs/vsts-docs#4699]
Is there some way to indicate a priority order in the jobs to execute? We have a limited amount of hosted pipelines, so not all jobs in the pipeline can run at once. However, one of the jobs run significantly longer than the other jobs. We would like to be able to prioritize this job, so that once an agent becomes available for our pipeline, it will first start processing this job. The order of the jobs in the YAML file seems to help queue the job first, but sometimes it is still not the first job to be executed

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7458d5b2-1bb7-7d87-7ce6-2b0c430b0155
* Version Independent ID: edf5bbd3-a3f0-5426-e985-31290f8afd05
* Content: [YAML schema - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema#feedback)
* Content Source: [docs/pipelines/yaml-schema.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/yaml-schema.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @vtbassmatt
* Microsoft Alias: **macoope**

**Comment by vtbassmatt** [comment]
You can make a job depend on another job, which will cause the depended-upon job to run to completion before the other(s) start. We don't offer any other prioritization or control than that.
