### ISSUE TITLE
How do I add parameters to task group after it is created?

### ISSUE THREAD

**Issue by sonpeppers** [MicrosoftDocs/vsts-docs#4701]
I don't see an option to do this in azure pipelines. Is this possible? I imagine it's an extremely typical use case that a new change has to happen and a new variable needs to be added to task group seamlessly across all the referencing pipelines ...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1e6b773c-dfb0-5c58-1463-e9b865d73af6
* Version Independent ID: 83f332ed-719a-5347-acd8-bfe3bdb397b4
* Content: [Task Groups in Azure Pipelines and Team Foundation Server - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/library/task-groups?view=azure-devops)
* Content Source: [docs/pipelines/library/task-groups.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/library/task-groups.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by sonpeppers** [comment]
Oh. the moment you update the definition, the variable is created. Thanks!

**Comment by paeppers** [comment]
Don't know how to close, so whoever sees this please just close or remove it, thanks. I guess take this as a +1 for a small note at bottom of page addressing original question since I had confusion for several minutes.

**Comment by WilliamAntonRohm** [comment]
@sonpeppers, @paeppers -- thank you for your interest and followup!  I am closing this issue now.
