### ISSUE TITLE
az --version not az -version

### ISSUE THREAD

**Issue by CarlRabeler** [MicrosoftDocs/vsts-docs#4704]
at least in my experience

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2690a4e0-d06e-2bf3-c4f4-dc7af10c58fa
* Version Independent ID: bd9c18bf-3e47-2827-2524-03839ab820b6
* Content: [Create your first pipeline using the Azure CLI - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/create-first-pipeline-cli?view=azure-devops)
* Content Source: [docs/pipelines/create-first-pipeline-cli.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/create-first-pipeline-cli.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @geverghe
* Microsoft Alias: **geverghe**

**Comment by geverghe** [comment]
That's right - thank  you for pointing this out. Will make the fix.

**Comment by geverghe** [comment]
The fix has been released. @CarlRabeler - kindly close the issue post verification.
