### ISSUE TITLE
Can not create the the AWS Service EndPoint

### ISSUE THREAD

**Issue by rifaterdemsahin** [MicrosoftDocs/vsts-docs#4711]
I am getting this error
I have tried with schema types "None","Certificate" and "Token"
{"$id":"1","innerException":null,"message":"Unable to find service connection type 'AWS' using authentication scheme 'None'.","typeName":"Microsoft.VisualStudio.Services.ServiceEndpoints.WebApi.ServiceEndpointException, Microsoft.VisualStudio.Services.ServiceEndpoints.WebApi","typeKey":"ServiceEndpointException","errorCode":0,"eventId":3000}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad945cf7-cd73-49da-90f5-21eb88f485e1
* Version Independent ID: d3032766-fb21-d299-e34f-05fe1010132c
* Content: [Authentication Schemas for Service Endpoints](https://docs.microsoft.com/en-us/azure/devops/extend/develop/auth-schemes?view=azure-devops#feedback)
* Content Source: [docs/extend/develop/auth-schemes.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/extend/develop/auth-schemes.md)
* Product: **devops**
* Technology: **devops-ecosystem**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @rifaterdemsahin, I'm sorry to hear you're experiencing difficulties. I'd consider this a Support issue, rather than a docs issue, however. Please submit a Support request here: https://visualstudio.microsoft.com/vs/support/#talktous 
Thank you and best of luck to you.
