### ISSUE TITLE
Update documentation to reflect change made 7-1

### ISSUE THREAD

**Issue by Justin-DynamicD** [MicrosoftDocs/vsts-docs#4716]
Subject matter summarizes it.  But the [July 1st Releases Notes](https://docs.microsoft.com/en-us/azure/devops/release-notes/2019/sprint-154-update#deployments-in-yaml-pipeline) include:

> We have also added support for additional properties to the deployment job. For example, here are few properties of a deployment job that you can now set, [...]
> For more details about deployment jobs and the full syntax to specify a deployment job, see Deployment job

Unfortunately this page hasn't been updated sense 5-1. and contains no details on what's been added.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5aeeaace-1c5b-a51b-e41f-f25b806155b8
* Version Independent ID: fd7ff690-b2e4-41c7-a342-e528b911c6e1
* Content: [Deployment jobs - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/deployment-jobs?view=azure-devops)
* Content Source: [docs/pipelines/process/deployment-jobs.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/deployment-jobs.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @shashankbarsin
* Microsoft Alias: **shasb**

**Comment by RoopeshNair** [comment]
The [schema](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/deployment-jobs?view=azure-devops#schema) section has been updated to include all supported options for the deployment job.
