### ISSUE TITLE
Deployment status widget has regressed

### ISSUE THREAD

**Issue by marchy** [MicrosoftDocs/vsts-docs#4720]
The deployment status widget, which is infinitely useful in CI/CD workflows has regressed and seems to no longer be available in the new Deployment Center. Moreover it looks like there is no way to go to the previous deployment flow for new instances.

How can we get the deployment status widget back?
I've opened a request for this regression here: https://feedback.azure.com/forums/169385-web-apps/suggestions/37918600-ability-to-pin-deployment-status-on-dashboard-widg

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 514ba817-c404-380b-6c8d-67ea982e9a22
* Version Independent ID: 915a8f30-5192-8b0a-d6a4-43fe7a606ff6
* Content: [Catalog of widgets you can add to a dashboard - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/report/dashboards/widget-catalog?view=azure-devops#deployment-status)
* Content Source: [docs/report/dashboards/widget-catalog.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/report/dashboards/widget-catalog.md)
* Product: **devops**
* Technology: **devops-analytics**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by msebolt** [comment]
@marchy  Thank you for the feedback!

Since this is a product request and not document related I will close the issue.  Please comment below if there are any further suggestions.
