### ISSUE TITLE
Print product backlog with description

### ISSUE THREAD

**Issue by omerahm** [MicrosoftDocs/vsts-docs#4721]
Is it possible to print any backlog description i.e. Description and Acceptance Criteria using DevOps online portal? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4b4a9a4d-3517-28c2-d8b9-7b1d025b17af
* Version Independent ID: 1b55ace1-77fd-7980-b2bf-ac97c03a112a
* Content: [Email or print user stories, issues, bugs, or other work items - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/work-items/email-work-items?view=azure-devops&tabs=browser)
* Content Source: [docs/boards/work-items/email-work-items.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/boards/work-items/email-work-items.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by PrinceTegaton** [comment]
Needed this just 6hrs after this issues is raised. Pls we need this feature. Thanks

**Comment by msebolt** [comment]
@PrinceTegaton Thank you for the suggestion! 

The product teams aren’t always watching this repository, so to make sure it gets in front of them for triage, please [submit the idea]( https://developercommunity.visualstudio.com/content/idea/post.html?space=21) here.
