### ISSUE TITLE
DevOps Server doesn't have personal UI Theme preference

### ISSUE THREAD

**Issue by cjwhitsitt** [MicrosoftDocs/vsts-docs#4728]
When selecting Azure DevOps Server 2019 on this page, the content doesn't change. However, there is no option to change the UI Theme preference in the place described on the on-prem product.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d28a6661-50d4-527e-9727-ab5974da951d
* Version Independent ID: fdac329a-b9b4-77d0-916a-dee6d2576379
* Content: [View, change user preferences - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/settings/set-your-preferences?view=azure-devops-2019#feedback)
* Content Source: [docs/organizations/settings/set-your-preferences.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/settings/set-your-preferences.md)
* Product: **devops**
* Technology: **devops-settings**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @cjwhitsitt, Thanks so much for your feedback. It looks like I need to add some versioning and new screenshots to the content. I've created a user story to capture this work. Thanks again!

**Comment by chcomley** [comment]
Hi @cjwhitsitt, I've just completed a PR, which will go live sometime between today and Monday morning. In the meantime, here's where you go to change the UI theme: Open your profile menu, and then select **Theme**. 
![image](https://user-images.githubusercontent.com/35748196/61162500-be4cf700-a4bd-11e9-9855-0e2853cafbd3.png)
From there you can choose between dark and light. Thanks again for the feedback and have a great weekend!

**Comment by nschonni** [comment]
Might be good to mention that the Theme isn't available till Update 1 of 2019. I know the moniker ranges don't currently support the updates as a version though
