### ISSUE TITLE
Title change

### ISSUE THREAD

**Issue by brillyints** [MicrosoftDocs/vsts-docs#4734]
Currently the page title is "Version Control - How to Simply Git Log History" - should be "Version Control - How to Simplify Git Log History"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 85dba85c-bcb6-1937-4e3e-9100d1e56472
* Version Independent ID: 5a344b30-dfc3-8c46-0a04-fff4f5a816b7
* Content: [Version Control - How to Simply Git Log History](https://docs.microsoft.com/en-us/azure/devops/repos/git/git-log-history-simplification?view=azure-devops)
* Content Source: [docs/repos/git/git-log-history-simplification.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/repos/git/git-log-history-simplification.md)
* Product: **devops**
* Technology: **devops-whitepapers**
* GitHub Login: @mlearned
* Microsoft Alias: **mlearned**

**Comment by mlearned** [comment]
looks like title was renamed. @steved0x  is this one good to close?
