### ISSUE TITLE
Nuget restore works different

### ISSUE THREAD

**Issue by FixRM** [MicrosoftDocs/vsts-docs#4735]
Said that: "Specifies the folder in which packages are installed. If no folder is specified, packages are restored into a packages/ folder alongside the selected solution, packages.config, or project.json." but I can see no "packages" is created in this case

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0fa37a3f-6551-16ad-e164-a4ac522cdaab
* Version Independent ID: a3fd6935-2b99-92ef-4eb3-3249fca01f8a
* Content: [NuGet restore, pack, and publish task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/package/nuget?view=azure-devops#restore-nuget-packages)
* Content Source: [docs/pipelines/tasks/package/nuget.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/package/nuget.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @chasewilson
* Microsoft Alias: **phwilson**

**Comment by bender2k14** [comment]
Are you specifying your NuGet package dependencies via [`PackageReference`](https://docs.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files)?  If so, then no such `packages` folder is created.

**Comment by FixRM** [comment]
Hello, I use both. Here is my repo: https://github.com/FixRM/LastSchedule. Most projects are SDK-style and use PackageReference but there is also folder-project and it use packages.json. VS is smart enough to restore all packages as expected but task filed.

**Comment by chasewilson** [comment]
@FixRM, thank you for the feedback. Have you reached out to the [Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html)

**Comment by chasewilson** [comment]
I'll be closing this issue for now. Feel free to open a new issue if the developer community provides feedback to update the doc
