### ISSUE TITLE
Missing docs for Repository creation extension point

### ISSUE THREAD

**Issue by evertonmc** [MicrosoftDocs/vsts-docs#4736]
https://docs.microsoft.com/en-us/azure/devops/server/release-notes/azuredevops2019u1?view=azure-devops#repository-creation-extension-point

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 56437af3-75da-d219-5364-9b7927298ece
* Version Independent ID: ca01655a-9195-cf92-14b4-77ef66053dcf
* Content: [Extension Points](https://docs.microsoft.com/en-us/azure/devops/extend/reference/targets/overview?toc=%2Fazure%2Fdevops%2Fextend%2Ftoc.json&bc=%2Fazure%2Fdevops%2Fextend%2Fbreadcrumb%2Ftoc.json&view=azure-devops#feedback)
* Content Source: [docs/extend/reference/targets/overview.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/extend/reference/targets/overview.md)
* Product: **devops**
* Technology: **devops-ecosystem**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by WilliamAntonRohm** [comment]
This appears to be a missing link target.

**Comment by evertonmc** [comment]
The release notes reference to a new **Repository creation extension point** which are not present in any documentation

**Comment by chcomley** [comment]
Hi @evertonmc, Thanks for letting us know. I'll be looking into this and in touch soon. Thanks again!

**Comment by chcomley** [comment]
Hi @evertonmc, Thanks for reaching out! Here's a link to a sample: https://github.com/microsoft/azure-devops-extension-sample/pull/18. Please let me know if you have any further questions.

**Comment by evertonmc** [comment]
Hey @chcomley that‘s awesome, thanks. I hope the docs will get updated soon.

**Comment by chcomley** [comment]
Absolutely. I've created a user story on my backlog for the doc updates. Thanks and have a great day!
