### ISSUE TITLE
Unclear how to remove a docker agent from pool

### ISSUE THREAD

**Issue by mkpankov** [MicrosoftDocs/vsts-docs#4737]
Removal from web-interface doesn't seem to be available. 
But removal from container is unergonomic and sometimes impossible (you might've removed the container altogether).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b31d4f6c-d16d-2ba1-1294-6aa94e328046
* Version Independent ID: 88aec599-4410-697d-1002-1c41b1c17bb6
* Content: [Running a self-hosted agent in Docker - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/docker?view=azure-devops-2019#feedback)
* Content Source: [docs/pipelines/agents/docker.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/agents/docker.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @juliobbv
* Microsoft Alias: **juliobv**

**Comment by msebolt** [comment]
@mkpankov It looks like you've encountered an issue with the product itself, rather than an issue with the documentation.

To make sure it gets in front of the right people, please [submit your idea]( https://developercommunity.visualstudio.com/content/problem/post.html?space=21) here.
