### ISSUE TITLE
Analytics is a Prerequisite

### ISSUE THREAD

**Issue by EQDGL** [MicrosoftDocs/vsts-docs#4738]
Although the Prerequisites section does mention "Analytics" it does not clearly state that it's a prereq.  Maybe more relevant for Azure Devops Server where Analytics is a separately installed extension (that's my understanding anyway). I presume these widgets don't become available until you install the extension.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a9d627b9-9aa8-c52c-3178-cffbefe9727a
* Version Independent ID: 31967bb3-2635-da97-782c-641f432750f7
* Content: [Configure Burndown & Burnup widgets - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/report/dashboards/configure-burndown-burnup-widgets?view=azure-devops#feedback)
* Content Source: [docs/report/dashboards/configure-burndown-burnup-widgets.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/report/dashboards/configure-burndown-burnup-widgets.md)
* Product: **devops**
* Technology: **devops-analytics**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@EQDGL - Thank you for your comment. If you make sure your content version selector is set to Azure DevOps Server 2019, you'll see the following item is added to the Prerequisites section: 

- Have [enabled or installed Analytics](/azure/devops/report/dashboards/analytics-extension.md). You must be an account owner or a member of the [Project Collection Administrator group](/azure/devops/organizations/security/set-project-collection-level-permissions) to add extensions or enable the service.

You are correct that all Analytics widgets are available only after Analytics is installed or enabled.
