### ISSUE TITLE
"Docker" not available in Configure step

### ISSUE THREAD

**Issue by montebhoover** [MicrosoftDocs/vsts-docs#4739]
I hit #4670 as well.  I selected my fork of [MicrosoftDocs/pipelines-javascript-docker](https://github.com/MicrosoftDocs/pipelines-javascript-docker) but it didn't seem to detect `pipelines-javascript-docker/app/Dockerfile` and "Docker" does not appear in the list when you click "show more."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45ba2ebe-27c4-111b-18b4-0192d8c3fb3a
* Version Independent ID: f48fdf00-e04f-b406-93f3-20b7fad568be
* Content: [Build and push to Azure Container Registry - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/languages/acr-template?view=azure-devops)
* Content Source: [docs/pipelines/languages/acr-template.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/languages/acr-template.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @shashankbarsin
* Microsoft Alias: **shasb**

**Comment by msebolt** [comment]
@montebhoover It looks like you've encountered an issue with the product itself, rather than an issue with the documentation.

To make sure it gets in front of the right people, please [submit your bug]( https://developercommunity.visualstudio.com/content/problem/post.html?space=21) here.

**Comment by montehoover** [comment]
Thanks @msebolt.  Submitted the issue here: https://developercommunity.visualstudio.com/content/problem/635703/docker-yaml-template-not-available-in-pipelines-co.html
