### ISSUE TITLE
az pipelines build show update

### ISSUE THREAD

**Issue by johnbergin-amtsybex** [MicrosoftDocs/vsts-docs#4742]
az pipelines build show uses --id instead of --build-id now (2.0.68)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 417acc67-23c3-779f-ce2e-cb7c62d4a59e
* Version Independent ID: b0dd8833-425d-c8ca-3626-ce53b3ca2908
* Content: [Start using Azure DevOps command line interface extension - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/cli/get-started?view=azure-devops#open-items-in-browser)
* Content Source: [docs/cli/get-started.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/cli/get-started.md)
* Product: **devops**
* Technology: **devops-ref**
* GitHub Login: @KathrynEE
* Microsoft Alias: **geverghe**

**Comment by KathrynEE** [comment]
@johnbergin-amtsybex - Thank you for the correction. I am updating the topic now. 
@geverghe - FYI.
