### ISSUE TITLE
Secret variable doesn't work as a azureSubscription value

### ISSUE THREAD

**Issue by armannds** [MicrosoftDocs/vsts-docs#4743]
I have defined the name of the Azure Resource Manager service connection as a secret variable, but the pipeline wont validate that. I always get an resource authorization issue, doesn't matter if the secret is wrapped with qoutes and/or single qoutes or even set as an environmental variable in the pipeline.  However, if I don't set the variable as a secret everything works just fine.

I would expect to be able to set this value as a secret instead of exposing it to all user that can modify a pipeline.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d955bb83-fa46-22e0-de73-7700ae214af8
* Version Independent ID: 1f55672f-711e-24fa-e6bc-edc0ca723eba
* Content: [Azure Web App task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-rm-web-app?view=azure-devops#feedback)
* Content Source: [docs/pipelines/tasks/deploy/azure-rm-web-app.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/deploy/azure-rm-web-app.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @shashankbarsin
* Microsoft Alias: **shasb**

**Comment by msebolt** [comment]
@armannds It looks like you've encountered an issue with the product itself, rather than an issue with the documentation. 

To make sure it gets in front of the right people, please [submit your bug]( https://developercommunity.visualstudio.com/content/problem/post.html?space=21) here.

**Comment by armannds** [comment]
@msebolt, thanks.

**Comment by Rod-Sychev** [comment]
I'm having the same issue here.
@armannds, have you filed a bug to Azure DevOps team?
