### ISSUE TITLE
Step 1 - Typo in command

### ISSUE THREAD

**Issue by p2well** [MicrosoftDocs/vsts-docs#4745]
Inside step 1 there is a typo inside command, which valides version of Azure CLI.
The correct command is `az --version` and not `az -version`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 417acc67-23c3-779f-ce2e-cb7c62d4a59e
* Version Independent ID: b0dd8833-425d-c8ca-3626-ce53b3ca2908
* Content: [Start using Azure DevOps command line interface extension - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/cli/get-started?view=azure-devops)
* Content Source: [docs/cli/get-started.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/cli/get-started.md)
* Product: **devops**
* Technology: **devops-ref**
* GitHub Login: @KathrynEE
* Microsoft Alias: **geverghe**

**Comment by KathrynEE** [comment]
@p2well - Thank you for the correction. I will update the topic today. 
@geverghe - FYI.

**Comment by geverghe** [comment]
Thank you @p2well for the correction. (y)
