### ISSUE TITLE
Incorrect Syntax/Parameters

### ISSUE THREAD

**Issue by pinkfloydx33** [MicrosoftDocs/vsts-docs#4748]
The command switch is `--use-git-aliases` (note the "es") and the argument is `true` and **not** `yes`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 33e556f5-b5a8-fdd5-11bf-4d8e71683082
* Version Independent ID: 16d7d78c-dde7-d7ed-6869-5a37c7b168e0
* Content: [Auto detect configuration and git aliases - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/cli/auto-detect-and-git-aliases?view=azure-devops#feedback)
* Content Source: [docs/cli/auto-detect-and-git-aliases.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/cli/auto-detect-and-git-aliases.md)
* Product: **devops**
* Technology: **devops-ref**
* GitHub Login: @KathrynEE
* Microsoft Alias: **geverghe**

**Comment by msebolt** [comment]
@pinkfloydx33 Thank you for the suggestion. 

The change has been moved to the repo and is currently under review.

**Comment by msebolt** [comment]
@KathrynEE 

See https://mseng.visualstudio.com/TechnicalContent/_git/vsts-docs-pr/pullrequest/483932?_a=overview.

**Comment by KathrynEE** [comment]
@msebolt - Thank you for the correction and the PR. @geverghe - for your awareness.

**Comment by msebolt** [comment]
Also see https://mseng.visualstudio.com/TechnicalContent/_git/vsts-docs-pr/pullrequest/483941?_a=overview.
