### ISSUE TITLE
Needs to clarify that Azure AD Government in NOT compatible

### ISSUE THREAD

**Issue by SamGrantham** [MicrosoftDocs/vsts-docs#4749]
Azure DevOps does not currently support the Government cloud. We are considering a government cloud instance, but it is not in the plans for this year. Up until January this year, the Gov cloud didn't have their own AAD instance setup, so it was actually still using the public cloud. Now that the gov AAD is on a separate cloud, gov AAD identities will no longer work for accessing any resource on DevOps, including artifacts, marketplace, etc.

You will need to either use a tenant hosted on the public cloud to use AAD Identities with Azure DevOps.

I would suggest adding a line in the prerequisites such as:
* Ensure that you are using Azure AD Public (not Azure AD Government) see. https://docs.microsoft.com/en-us/azure/azure-government/documentation-government-plan-identity for details.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 031380a0-4f04-4105-199a-81715b42c653
* Version Independent ID: 570b2795-90ad-32b4-7ad0-1fceb186ffa3
* Content: [Connect organization to Azure Active Directory - Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/connect-organization-to-azure-ad?view=azure-devops)
* Content Source: [docs/organizations/accounts/connect-organization-to-azure-ad.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/accounts/connect-organization-to-azure-ad.md)
* Product: **devops**
* Technology: **devops-accounts**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by msebolt** [comment]
@SamGrantham  Thank you for the suggestion.

The change has been moved to the repo and is currently under review.

@chcomley See https://mseng.visualstudio.com/TechnicalContent/_git/vsts-docs-pr/pullrequest/483938?_a=overview.

**Comment by msebolt** [comment]
The change has been made.
