### ISSUE TITLE
Update screenshots from vsts to azure devops ux (it's almost 1 year as released)

### ISSUE THREAD

**Issue by SychevIgor** [MicrosoftDocs/vsts-docs#4756]
https://docs.microsoft.com/en-us/azure/devops/extend/get-started/_img/account-home2.png?view=azure-devops
https://docs.microsoft.com/en-us/azure/devops/extend/get-started/_img/my-hub.png?view=azure-devops

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 14955ee9-29f2-46fe-3a8d-a42666f53ffc
* Version Independent ID: 5d417cd0-a671-ee30-8fca-5f8b0addd328
* Content: [Develop a web extension for Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/extend/get-started/node?view=azure-devops)
* Content Source: [docs/extend/get-started/node.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/extend/get-started/node.md)
* Product: **devops**
* Technology: **devops-ecosystem**
* GitHub Login: @willsmythe
* Microsoft Alias: **wismythe**

**Comment by chcomley** [comment]
Hi @SychevIgor, Thanks for your feedback. We'll be improving and refreshing this documentation set in the near future (Q3, Q4), which will include updated screenshots. Thanks again.
