### ISSUE TITLE
Is it still private preview?

### ISSUE THREAD

**Issue by SychevIgor** [MicrosoftDocs/vsts-docs#4757]
Last time this document was updated 3 years ago. Is it still private preview?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec855c91-2d07-f16b-c6ea-d94c761224aa
* Version Independent ID: fbd17954-d1d3-86f2-18ed-7a7ca58bb9ff
* Content: [TFS/TestManagement/RestClient TestHttpClient2_2 API](https://docs.microsoft.com/en-us/azure/devops/extend/reference/client/api/tfs/testmanagement/restclient/testhttpclient2_2?view=azure-devops)
* Content Source: [docs/extend/reference/client/api/TFS/TestManagement/RestClient/TestHttpClient2_2.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/extend/reference/client/api/TFS/TestManagement/RestClient/TestHttpClient2_2.md)
* Product: **devops**
* Technology: **devops-ecosystem**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @SychevIgor, Thanks for reaching out. I've contacted a PM to get some clarity on this and will be in touch. Thanks!

**Comment by chcomley** [comment]
Adding @aaronhallberg for input please. Thanks Aaron!

**Comment by chcomley** [comment]
Hi @SychevIgor, I've just confirmed that this is no longer in private preview and is GA. We'll be working on updating this set of articles soon. Here's the official documentation you can refer to: https://docs.microsoft.com/en-us/rest/api/azure/devops/test/runs?view=azure-devops-rest-5.1 
Do let us know if you have any further questions. Thank you!

**Comment by SychevIgor** [comment]
Well, for a 3 months- I already find the right link. Issue was created to save some time for others.

**Comment by chcomley** [comment]
@SychevIgor, Thanks for your intention, truly. Glad you found the right link.
