### ISSUE TITLE
Sending the comments to the groups

### ISSUE THREAD

**Issue by rifaterdemsahin** [MicrosoftDocs/vsts-docs#476]
How do we send this to a group ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 34ae521f-6ae4-4d7f-2cce-f844e5811b66
* Version Independent ID: 18098490-1f34-e966-3135-cb90197bfa6f
* Content: [Use @mentions to further discussion - VSTS & TFS](https://docs.microsoft.com/en-us/vsts/notifications/at-mentions?view=vsts)
* Content Source: [docs/notifications/at-mentions.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/notifications/at-mentions.md)
* Service: **unspecified**
* GitHub Login: @erickson-doug
* Microsoft Alias: **elbatk**

**Comment by elbatk** [comment]
Hey @rifaterdemsahin , shooting this to the product team to get you some guidance on how to send mentions to a group. I thought that groups would be an option by default once you start typing their name and press "enter" for search, but we'll figure it out for ya.

**Comment by elbatk** [comment]
@rifaterdemsahin , I have a quick clarification question: When you're trying to @mention a group, is the group not showing up as being able to be mentioned or is the group not getting the notification when you're mentioning them?

**Comment by msm34** [comment]
@elbatk

**Comment by elbatk** [comment]
@msm34 are you having the same issue? Could you answer the question above if so?

**Comment by sngehl01** [comment]
@elbatk I am having the same issue. It will allow me to tag the team but will send an email saying "The identity is not configured to receive notifications. "

I am able to tag them via @[project name]\team name -> using this format it will find them in the search, allow me to select them and then save the ticket. However, a few moments later I receive an email that says "[project name]\team name" cannot be mentioned in Product Backlog Item 000000. The identity is not configured to receive notifications. 

The email looks the same as an email you get when mentioned, however it's just letting you know that the @mention you used isn't set up to receive notifications.

**Comment by elbatk** [comment]
Thank you for the clarification, @sngehl01 , adding @willsmythe from the product team to look into this for you all.

**Comment by dinye** [comment]
Is it possible to use "@mention" in python script and automatically @ someone when the script runs? Thx!

**Comment by carlowahlstedt** [comment]
Was there ever a clarification on this? I realize this is a VSTS issue and not directly a docs issue, but we're having the same issue in VSTS. It seems the group additionally cannot receive emails for release approvals.

**Comment by elbatk** [comment]
Hey @willsmythe , is there a place for people to put this issue instead of the docs area so it might get more attention from the product team? @carlowahlstedt I believe if you got to [docs page](https://docs.microsoft.com/en-us/vsts/notifications/at-mentions?view=vsts), you can submit product feedback in a similar manner to docs feedback.

**Comment by carlowahlstedt** [comment]
I ended up resolving my issue, but it wasn't clear to me why exactly. I had to:
1. Go to Organization Settings > Notifications
1. Select Settings
1. Enable Deliver to individual members

Seems this is relative to groups in general and the members in them that aren't receiving emails. We had a group which had some regular users who code getting emails, but the others who were not. Enabling this setting and waiting a few min (assumingely to allow the setting to "catch up") allowed the other users to start receiving emails.

**Comment by elbatk** [comment]
Hi everyone, I know it's been a while. I'm going to close this issue here and suggest if you have issues with the product that you post to the [Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html) which is actively monitored by the product team. Thanks!
