### ISSUE TITLE
Can you please elaborate little more on "Each repository should have a unique feed"?

### ISSUE THREAD

**Issue by Anand-Moghe** [MicrosoftDocs/vsts-docs#4770]
Isn't each feed itself is like a container and repository in itself (which is a global resource within Azure DevOps Service Organization)? So what do you mean by "Each repository should have a unique feed"? 

Are you saying that there should be one to one mapping between feed and project's pipeline? Like one feed for each pipeline? And one should avoid sharing feed between pipelines for projects within organization?

or are you saying to create a unique feed with unique packages within organization? 
So that no two feeds within Organization duplicate the internal or external packages (like npm or nuget) ?

Appreciate if you could elaborate this further.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cdf693ac-c5c3-96a6-7f4b-bbc2271a6375
* Version Independent ID: 4f76c74c-1d6c-644f-f00d-97d7738d7b01
* Content: [Best practices for using packages in Azure DevOps Services and TFS](https://docs.microsoft.com/en-us/azure/devops/artifacts/concepts/best-practices?view=azure-devops)
* Content Source: [docs/artifacts/concepts/best-practices.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/artifacts/concepts/best-practices.md)
* Product: **devops**
* Technology: **devops-artifacts**
* GitHub Login: @chasewilson
* Microsoft Alias: **phwilson**

**Comment by alexkibler** [comment]
I was wondering the same thing. My team has a whole bunch of legacy apps which aren't in azure devops, but I was planning on creating a "Legacy" project in devops to host all of the nuget packages that are sharedbetween them

**Comment by chasewilson** [comment]
Hi @ alexkibler, @Anand-Moghe, take a look at [this issue](https://github.com/MicrosoftDocs/vsts-docs/issues/4993) and see if it answers your question.

**Comment by Anand-Moghe** [comment]
@chasewilson Thanks.
