### ISSUE TITLE
'Extract Files' task error: 'Would you like to replace the existing file'

### ISSUE THREAD

**Issue by gavinwa** [MicrosoftDocs/vsts-docs#4775]
https://developercommunity.visualstudio.com/content/problem/636028/extract-files-task-failed.html

I use 'Extract files' task in my release pipeline. It throws following error:

Would you like to replace the existing file:
  Path:     F:\agent-1\_work\r11\a\publish\bingads-webui-campaign-react-ui-next\PaxHeader
  Size:     168 bytes (1 KiB)
  Modified: 2019-07-05 23:15:16
with the file from archive:
  Path:     PaxHeader
  Size:     55099 bytes (54 KiB)
  Modified: 2019-07-05 23:15:16
? (Y)es / (N)o / (A)lways / (S)kip all / A(u)to rename all / (Q)uit? 
Archives with Errors: 1
code: 2 

Should provide a way to specify 'Always replace'?

**Comment by msebolt** [comment]
@gavinwa Is there an article or code sample you can provide as reference?

**Comment by msebolt** [comment]
Please comment below if you'd like the issue to be re-opened.

**Comment by msebolt** [comment]
#please-close
