### ISSUE TITLE
There has no "Project" item in my Organization Settings

### ISSUE THREAD

**Issue by showery-hwang** [MicrosoftDocs/vsts-docs#4776]
my Organization Settings is like follows.
Organization Settings
General
Overview
Users
Billing
...
There has no "Project" item. What's wrong with it?

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 5a614791-0c5d-4373-3194-11695e40e1d1
* Version Independent ID: 737e5a3b-d7be-9d36-7b5a-638976406d74
* Content: [Delete, remove project - Azure DevOps](https://docs.microsoft.com/ja-jp/azure/devops/organizations/projects/delete-project?view=azure-devops)
* Content Source: [docs/organizations/projects/delete-project.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/projects/delete-project.md)
* Product: **devops**
* Technology: **devops-accounts**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by AlanPBourke** [comment]
+1 not seeing Projects listed as an option either.

**Comment by chcomley** [comment]
Hi @showery-hwang and @alanpbourke,
We're sorry for the confusion. I'm currently updating this article. Until it is published, here's what to do:
1. Sign in to your organization (```https://dev.azure.com/{yourorganization}```), and then open the project that you want to delete.
2. Select **Project settings** > **Overview**, and then enter a new name and select **Save**. 
3. To confirm the rename, enter the new project name, check the box next to, "I understand the consequences of renaming this project," and then select **Save**.

**Comment by AlanPBourke** [comment]
An issue here is that on the <Organisation>/<Project>/Overview/Summary page, the 'cog' icon beside the project title which brings you into Project Details, where the Delete button is, is not visible until you hover over the title element. So people are looking at the left side menu and not seeing an option.
