### ISSUE TITLE
Checkout

### ISSUE THREAD

**Issue by adriantorrie** [MicrosoftDocs/vsts-docs#4777]
1. Document the defaults for [checkout](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema#checkout), so we know when we need to explicitly define this in our `azure-pipelines.yml` file, or not. We're dealing with LFS issue, as it looks that it's not enabled by default.
2. Define which are optional, and which are mandatory, this is not clear currently, and we're going to have to test it *just for the purpose of figuring it out*, instead of just defining the task from the documentation and then testing we've got things correct.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7458d5b2-1bb7-7d87-7ce6-2b0c430b0155
* Version Independent ID: edf5bbd3-a3f0-5426-e985-31290f8afd05
* Content: [YAML schema - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema#checkout)
* Content Source: [docs/pipelines/yaml-schema.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/yaml-schema.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @vtbassmatt
* Microsoft Alias: **macoope**

**Comment by JohnTortugo** [comment]
Is the NuGet cache cleaned up with any of the values for the checkout.clean ?
