### ISSUE TITLE
Variables added to the Azure DevOps project  not visible out of the VSTS(Azure DevOps)

### ISSUE THREAD

**Issue by chaitanya116** [MicrosoftDocs/vsts-docs#4782]
Variables added to the Azure DevOps project  not visible out of the VSTS(Azure DevOps)

Created variables in a given Azure DevOps project but that variable in the azure DevOps is not vissible to pass values externally like MS-Flows or any where else?

**Comment by msebolt** [comment]
@chaitanya116 Thank you for the feedback!

The issue involves product features and not documentation, so please use [suggest a feature](https://developercommunity.visualstudio.com/spaces/21/index.html).
