### ISSUE TITLE
Wrong (outdated) documentation

### ISSUE THREAD

**Issue by yacobcz** [MicrosoftDocs/vsts-docs#4784]
1) "To open the Security dialog, choose More &gt; Wiki Security." - I'm logged as basic user and project admin -  There is no "Wiki security" button, there are only "Rename wiki" and "Unpublish wiki" buttons.
2) "Users with Stakeholder access in a private project can read wiki pages" - I'm logged as stakeholder and member of Contributors group - I can´t see any Wiki pages, with following error page: "You don't have access to this wiki".
3) There is no "You do not have sufficient permissions to read wiki. Contact your administrator for necessary permissions. [Wiki security]" error page, only "You don't have access to this wiki" without "Wiki security" button.

---
#### Podrobnosti dokumentu

⚠ *Neupravujte tuto část. Vyžaduje se k propojení problémů docs.microsoft.com ➟ GitHub.*

* ID: c86f5178-e331-f45e-b60a-f0f3955f7a08
* Version Independent ID: 8a0882a7-8f48-32bb-c741-12976b428c38
* Content: [Manage permissions for READMEs and wiki pages in Azure DevOps - Azure DevOps](https://docs.microsoft.com/cs-cz/azure/devops/project/wiki/manage-readme-wiki-permissions?view=azure-devops&viewFallbackFrom=vsts#feedback)
* Content Source: [docs/project/wiki/manage-readme-wiki-permissions.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/project/wiki/manage-readme-wiki-permissions.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @yacobcz, Thanks for your feedback. I'm looking into this and will be in touch!

**Comment by adramasu** [comment]
Hi @yacobcz,
For the first 2 points, you are checking the options in a code wiki which is a wiki published from code. The wiki security for this is the Repo's setting page. Also, stakeholders cannot read code wikis. They can only read project wikis. 

For point 3, we will make the required change in the documentation. Thanks for highlighting this.

**Comment by chcomley** [comment]
Thanks @adramasu, and thanks to you, @msebolt, the updated article should go live sometime today. :)
