### ISSUE TITLE
File patterns in manifests parameter

### ISSUE THREAD

**Issue by jpestanota** [MicrosoftDocs/vsts-docs#4785]
It is stated that the manifests parameter could be Regular Expression (RE2 syntax). Shouldn't the documentation refer to Glob Patterns like following link? https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/file-matching-patterns?view=azure-devops

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72bba72b-235b-ce64-b8fd-2c6ed52a9f1f
* Version Independent ID: 2ae1b3f1-e125-a9d2-a17c-d13047d69801
* Content: [Kubernetes Manifest task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/kubernetes-manifest?view=azure-devops#open-source)
* Content Source: [docs/pipelines/tasks/deploy/kubernetes-manifest.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/deploy/kubernetes-manifest.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @shashankbarsin
* Microsoft Alias: **shasb**

**Comment by shashankbarsin** [comment]
This has been fixed with the recent set of documentation updates for Kubernetes manifest task
