### ISSUE TITLE
Exclude folders not containg .md files

### ISSUE THREAD

**Issue by marvhen** [MicrosoftDocs/vsts-docs#4792]
I am seeing folders which don't have any .md files show up in a published wiki.  Is there a way to prevent this?  It seems it should do this by default but a way to explicitly exclude certain folders would be nice.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8d4fe5c7-0ab6-a0e4-4a6e-f98d0355f49a
* Version Independent ID: ce022fef-054d-cdc2-43e9-a8ee3b8fb592
* Content: [Publish Markdown files from a Git repository to a wiki in Azure DevOps - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/project/wiki/publish-repo-to-wiki?view=azure-devops#feedback)
* Content Source: [docs/project/wiki/publish-repo-to-wiki.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/project/wiki/publish-repo-to-wiki.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @marvhen, Thanks for reaching out. I'm following up on this with the PM and will be in touch. Thanks!

**Comment by chcomley** [comment]
Hi @marvhen, So, it doesn't look like this functionality is in the plans, however I'd invite you to upvote this [feature suggestion ticket](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdevelopercommunity.visualstudio.com%2Fcontent%2Fidea%2F366069%2Fhide-folders-that-do-not-contain-markdown-files.html&data=02%7C01%7CChrystal.Comley%40microsoft.com%7Cf1827344e76d469ede7808d704f5285b%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636983323355156915&sdata=at03l5KFLsbjAzMiezDCowXagJ98%2BPnVFeFeeuhOrSo%3D&reserved=0). Thank you for reaching out.

**Comment by Bafff** [comment]
Is that resolved not long ago by prefixing with "." in the name of the folder?

**Comment by stoopered** [comment]
It's crazy that you cannot provide a special .ignore file for the wiki just like you do with Git and TFVC.  I am appalled that they even support an ordering, but if you just wanted the wiki to have the readme file, you should be able to specify the root, and have it only include the file you want. I did see a silly suggestion of having a cleanup button, why develop that when a simple text doc would give much more control. You could even block out or include certain subdirectories. This is a much wanted feature, and finding the ticket to upvote is often cumbersome. Microsoft NEEDS to allow feature requests in the documentation themselves, so we don't have to search and search to find existing tickets. And allow us to upvote within the documentation. There is no way that I am the first person to think of this type of thing, and it amazes me that Microsoft is so big, and they haven't thought of it. They could simply add tags to docs and feature requests for simple linking.
