### ISSUE TITLE
Documentation Incomplete

### ISSUE THREAD

**Issue by pabrams** [MicrosoftDocs/vsts-docs#4796]
The documentation on this page is incomplete:  https://docs.microsoft.com/en-us/azure/devops/extend/develop/ui-controls/comboo?view=tfs-2017#main

Where are all the properties and descriptions of what they do? For example, enableFilter and autoComplete are not listed anywhere.

I had already opened this as Issue #4547, but that was closed because I forgot to specify that I'm working with TFS 2017, so I can't use the new Azure Devops Extension Sdk.

**Comment by chcomley** [comment]
Thanks @pabrams, I've created a user story on my backlog to capture this work. Will be in touch!

**Comment by chcomley** [comment]
Hi @pabrams, Thanks so much for your patience on this. We have a newer design site, for which I've added a link within the article. See [Formula Design System - Filter](https://developer.microsoft.com/en-us/azure-devops/components/filter). Please @mention me if you have any further questions. Thanks!
