### ISSUE TITLE
Screen Capture is Outdated

### ISSUE THREAD

**Issue by alohaninja** [MicrosoftDocs/vsts-docs#4797]
Please update this screenshot - the image https://docs.microsoft.com/en-us/azure/devops/organizations/security/_img/git-tfvc-perm/open-repository-security-vert-reduced.png?view=azure-devops is no longer accurate. "Code" has been replaced by "Repos" - this is confusing. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5f5ce059-ec92-5413-0910-4e28033db034
* Version Independent ID: 540610d3-6073-664d-97f8-e7d8e0a21a20
* Content: [Set Git or TFVC repository permissions - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/security/set-git-tfvc-repository-permissions?view=azure-devops)
* Content Source: [docs/organizations/security/set-git-tfvc-repository-permissions.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/security/set-git-tfvc-repository-permissions.md)
* Product: **devops**
* Technology: **devops-security**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by msebolt** [comment]
@alohaninja Thank you for the feedback!

The version I'm using doesn't have the replacement.  Would you mind attaching a screenshot or version number?

**Comment by msebolt** [comment]
Closing issue, please add information below for the issue to be re-opened.
