### ISSUE TITLE
How to add a GKE (Google Kubernetes Engine) endpoint in VSTS

### ISSUE THREAD

**Issue by jgold6** [MicrosoftDocs/vsts-docs#480]
There is no built in support for adding a GKE endpoint in VSTS, but a user was kind enough to share the solution they found:

You can remove the Google auth provider and supply in its place a new basic auth method using the user name and password you can retrieve by going to "Show credentials" the web UI under your GKE cluster.
Just remove this from your kubeconfig:

  user:
    auth-provider:
      config:
        cmd-args: config config-helper --format=json
        cmd-path: /google/google-cloud-sdk/bin/gcloud
        expiry-key: '{.credential.token_expiry}'
        token-key: '{.credential.access_token}'
      name: gcp

And then you can add basic auth with a command:
kubectl config set-credentials cluster-admin --username=admin --password=uXFGweU9l35qcif

Which will add this to your kubeconfig

- name: cluster-admin
  user:
    as-user-extra: {}
    password: ******
    username: ******
 
Or you can just add that to the file. Nothing fancy there. The name will be the cluster name in GKE instead of cluster-admin.

I also am using the ACR for container registry and I just integrated it by creating a secret with an Azure SP and then I associated it with the default service account.

# Creating the Service Principle
az ad sp create-for-rbac --scopes /subscriptions/77ba06d0-a62/resourcegroups/YourRG/providers/Microsoft.ContainerRegistry/registries/YourRegistry --role Contributor --name YourSPName
 
# Create the secret
kubectl create secret docker-registry YourSecretName --docker-server reg01.azurecr.io --docker-email SomeOne@gmail.com --docker-username=YourSpName --docker-password YourSPPass
 
# Get the service account yaml to modify so it includes the secret
kubectl get serviceaccounts default -o yaml > ./sa.yaml
 
# Add the following at the bottom of the yaml file
imagePullSecrets:
- name: YourSecretName
 
# Replace the default service account to add the new imagepull spec
kubectl replace serviceaccount default -f ./sa.yaml

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72b90dd0-49f9-4ed4-3010-9a64dde6ae5a
* Version Independent ID: 6e679d50-4e94-eee3-8793-af884cc909ca
* Content: [Service endpoints in VSTS and Team Foundation Server](https://docs.microsoft.com/en-us/vsts/build-release/concepts/library/service-endpoints?view=vsts#feedback)
* Content Source: [docs/build-release/concepts/library/service-endpoints.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/build-release/concepts/library/service-endpoints.md)
* Service: **unspecified**
* GitHub Login: @erickson-doug
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment]
At present there are no plans to add a specific service endpoint for GKE. The generic Kubernetes Service Connection requires Kube config details, and can be used to connect to any Kubernetes cluster. Customers are using it now for deploying to AWS. The Kubernetes Deploy task (and, in a future release, the Helm task) supports creating image pull secret (container registry credentials). If you are using this feature then there is no need to run any az command.
