### ISSUE TITLE
rename organization

### ISSUE THREAD

**Issue by ianhuynh** [MicrosoftDocs/vsts-docs#4800]
is it possible to rename an organization in Azure DevOPS ? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bdda7871-1906-57bf-1973-203c0a76f959
* Version Independent ID: ebaf49b7-d53e-f1ef-4759-ef0e7afa1c2b
* Content: [Organization management articles - Azure DevOps - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/?toc=%2Fazure%2Fdevops%2Forganizations%2Faccounts%2Ftoc.json&bc=%2Fazure%2Fdevops%2Forganizations%2Faccounts%2Fbreadcrumb%2Ftoc.json&view=azure-devops#feedback)
* Content Source: [docs/organizations/accounts/index.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/accounts/index.md)
* Product: **devops**
* Technology: **devops-accounts**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @ianhuynh, Yes! It's in the How-to section of the page you referenced, but here's a direct link: https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/rename-organization?view=azure-devops. Please let me know if you have any further questions. Thanks!
