### ISSUE TITLE
Out-of-date documentation as of Sprint 150

### ISSUE THREAD

**Issue by JGCreator** [MicrosoftDocs/vsts-docs#4801]
As of Sprint 150, which dropped on April 8, there is no longer an option to retain a minimum number of build artifacts. There is now only a max number of days to keep artifacts, runs, and pull requests. This leaves badges in the "never run" state for pipelines that don't have a high volume of change to keep up with the retention policy, and should be thoroughly documented.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43a285f9-738d-9f76-4de0-a4c4ecf6f5f5
* Version Independent ID: 9581a043-4873-bf0a-138f-85f6a61ae950
* Content: [Build and release retention policies - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/policies/retention?view=azure-devops)
* Content Source: [docs/pipelines/policies/retention.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/policies/retention.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by chasewilson** [comment]
@JGCreator, Thank you for the feedback and I'm sorry for the slow response. The documentation has been update as well as a Note stating that functionality is in development for Azure DevOps. Thank you again and please feel free to create a new issue if you have any more feedback
