### ISSUE TITLE
Job Limits for Self-Hosted Public Projects

### ISSUE THREAD

**Issue by bramwelt** [MicrosoftDocs/vsts-docs#4802]
The documentation states that public, [self-hosted projects](https://docs.microsoft.com/en-us/azure/devops/pipelines/licensing/concurrent-jobs?view=azure-devops#self-hosted-cicd) are limited to 10 jobs:

> We provide a free tier of service by default in your organization:
> * Public project: 10 free self-hosted parallel jobs.

and

> When the free tier is no longer sufficient:
> * Public project: Contact us to get your free tier limits increased.

But projects settings states the jobs are unlimited:

![azure-pipelines](https://user-images.githubusercontent.com/324567/60928299-b133cc00-a261-11e9-8af5-549c0cc9b732.png)

The docs should be updated to reflect this change as I am assuming the UI is correct.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c6a488b-88f6-dff6-e2ee-402167e17ad4
* Version Independent ID: 9a4dedda-e82c-2833-f28c-5ab346fb1b38
* Content: [Parallel jobs in Azure Pipelines - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/licensing/concurrent-jobs?view=azure-devops#feedback)
* Content Source: [docs/pipelines/licensing/concurrent-jobs.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/licensing/concurrent-jobs.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by bramwelt** [comment]
Hey @andyjlewis I have a fix up in #4803 and I'm happy to work with you on any changes than need to happen. :)

**Comment by bramwelt** [comment]
@WilliamAntonRohm, @andyjlewis Any update here?

**Comment by bramwelt** [comment]
Pinging people who've merged changes in the last month. @chasewilson @steved0x @KathrynEE @chcomley
Still haven't seen a response from _anyone_ for this 1 line fix...
Maybe adding a [CODEOWNER](https://help.github.com/en/articles/about-code-owners)s file would help you?

**Comment by chasewilson** [comment]
@bramwelt I really appreciate the feedback as well as you keeping on top of this issue. Sorry about the slow response. I just very recently took over this section of docs and I'm working to get caught up on everything. In addition Thank you for creating your own PR! Really great to see the contribution! If you feel like your PR address this issue, feel free to close this one unless you have more feedback on it and I will take a look at your PR :)

**Comment by bramwelt** [comment]
@chasewilson No worries; squeaky wheel get the grease is all. :wink:  Thanks for the response!
