### ISSUE TITLE
Project-level Notifications no longer available in Azure DevOps Services

### ISSUE THREAD

**Issue by vhhughes** [MicrosoftDocs/vsts-docs#4805]
When following the instructions above. project-level notifications are no longer available. (use the "Project" URL above) I am forced to select a team within the project with which to set up a notification rule. I would really like to be able to do this *outside* a team at the project level. Very disappointed that this seems to have been removed despite the documentation here. It needs to be updated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1f52a6bb-319e-21ed-b0d5-0b719bb71567
* Version Independent ID: 51378110-e573-ba2e-5dcb-829e0d18ecaf
* Content: [Navigating the notifications UI - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/notifications/navigating-the-ui?view=azure-devops#feedback)
* Content Source: [docs/notifications/navigating-the-ui.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/notifications/navigating-the-ui.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @vhhughes, I'm glad you reached out. Nothing has been removed regarding project level subscriptions, however the URLs do need to be updated, so I've created a user story to capture that work. Until then, here's the updated URL for project-level notifications: https://dev.azure.com/{organization}/{project}/_settings/_notifications. Please let me know if you have any further questions at all. Thank you!

**Comment by vhhughes** [comment]
Interestingly, that URL does not work. (when filled in with our org and project) It pulls up the Security tab in our Azure DevOps Services project. If I then click on Notifications, it is as before: I'm forced to select a team.

**Comment by chcomley** [comment]
@vhhughes, I'm sorry for any confusion! I'll follow up on this tomorrow and will be in touch. Thanks
