### ISSUE TITLE
Confused as to what 'greyed out' On features mean.

### ISSUE THREAD

**Issue by AdrianSanguineti** [MicrosoftDocs/vsts-docs#4807]
I'm trying to understand what it means when a feature flag is greyed out and in the `On` state at the user and organisation level. An example is the `New release progress view` feature in the screenshot in the `Enable features at the organization level (for all users)` section.

As this feature flag is disabled at both user and organisation level, but is shown at the on state, is that conveying that:

a. The Feature is on by default for all users across the organisation and can't be turned off.
b. The Feature is not actually on, but can't be enabled right now.
c. The Feature is not available yet for preview.

We're confused about this because our testers would like to try out the new `Test tab in new web platform` feature, but they can't see it available in our organisation (deployed to Australia East). The flag is suggesting that they should be seeing the new feature, but they don't. We understand that the feature may still be rolling out to all instances, which can take some time (due to ring-deployments etc.) We're just really confused as to what the UI is telling us. Some clarification and updates to this page about this particular problem would be great.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b4f95345-6686-8e29-ff3f-cbea4a6eb24d
* Version Independent ID: 695d975e-ea9b-139b-4f98-f9655a751f59
* Content: [Turn preview features on or off - Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/project/navigation/preview-features?view=azure-devops)
* Content Source: [docs/project/navigation/preview-features.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/project/navigation/preview-features.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@AdrianSanguineti - Thank you for your inquiry. I checked with the PM for this feature and learned that: 
(1) The feature is greyed out as it is being turned ON by default
(2) The feature is still being rolled out still - so it might not be available until that completes. 

As for (1) - the plan is to change this experience and not use the greyed out UI. I will update the topic in the next few days. Thanks again.

**Comment by AdrianSanguineti** [comment]
@KathrynEE, thanks for clarifying.
