### ISSUE TITLE
No Server Specs for Search server

### ISSUE THREAD

**Issue by clizzotte** [MicrosoftDocs/vsts-docs#481]
Installing a standalone Search Server with my TFS2018 stack. What are the recommended specs for a large TFS installation? 1500+ users with build, test and release capabilities.
Loadbalanced Application servers and standalone SSRS utilizing multiple proxies.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 707d403c-b68d-4c8d-56da-0f37d3117dd2
* Version Independent ID: 9b043f37-0dd2-3aba-c201-8160cdbfac86
* Content: [Code and Work Item Search set up](https://docs.microsoft.com/en-us/vsts/search/code/administration?view=vsts#feedback)
* Content Source: [docs/search/code/administration.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/search/code/administration.md)
* Service: **unspecified**
* GitHub Login: @erickson-doug
* Microsoft Alias: **douge**

**Comment by alexhomer1** [comment]
Thank you for your feedback. It looks as though you have "VSTS" selected in the drop-down list at the top left of the page. Use this link to access the TFS content directly: https://docs.microsoft.com/en-us/vsts/search/code/administration?view=tfs-2017#config-tfs. Please let us know if this does not answer your question.
