### ISSUE TITLE
Missing Agent.TempDirectory variable on Agent variables

### ISSUE THREAD

**Issue by rockraft7** [MicrosoftDocs/vsts-docs#4810]
This article missing said variable, and when we use Download Secure File task, it will use temp directory to store the files.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ffebdc8-521c-44b5-cde4-4abdc1bd6f18
* Version Independent ID: dc0effda-6d93-62aa-64c5-4e6f283b0826
* Content: [Predefined variables - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml#feedback)
* Content Source: [docs/pipelines/build/variables.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/build/variables.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by andyedison** [comment]
Bumping this. I have pipelines using Agent.TempDirectory all over the place. After I noticed it was missing here, I checked the download secure file task, and it's no longer mentioned there either. Is Agent.TempDirectory going away?

**Comment by jsiegmund** [comment]
Not sure if it's due to this issue, but Agent.TempDirectory seems to be there now @ https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml#agent-variables. Case closed?

**Comment by damccorm** [comment]
Looks like this has been fixed so I'm going to close. Thanks for the feedback
