### ISSUE TITLE
isOutput=true variable scope

### ISSUE THREAD

**Issue by Willem-J-an** [MicrosoftDocs/vsts-docs#4811]
There is some peculiar behavior going on with the isOutput=true, which is not described in the docs.
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - powershell: |
      $JsonVar = 'VeryImportantVariableValue'
      Write-Host "##vso[task.setvariable variable=JsonVarOutput;isOutput=true]$JsonVar" # Works in secondJobFirstStep
      Write-Host "##vso[task.setvariable variable=JsonVar]$JsonVar" # Works In FirstJobSecondStep
    name: 'FirstJobFirstStep'
  - powershell: |
      Write-Host "Below does not work with isOutput=true"
      Write-Host "JsonVarOutput: "+ $Env:JSONVAROUTPUT " OR " # Causes error &gt;  $(JSONVAROUTPUT)
      Write-Host "Below works without isOutput=true"
      Write-Host "JsonVar: "+ $Env:JSONVAR " OR " $(JSONVAR)
      Write-Host "Below is the working syntax when isOutput is true"
      Write-Host "Job drill var notation" + $Env:FirstJobFirstStep_JsonVarOutput " OR " $(FirstJobFirstStep.JsonVarOutput)
    name: 'FirstJobSecondStep'
Results::
Below does not work with isOutput=true
JsonVarOutput:  +   OR 
Below works without isOutput=true
JsonVar:  + VeryImportantVariableValue  OR  VeryImportantVariableValue
Below is the working syntax when isOutput is true
Job drill var notation + VeryImportantVariableValue  OR  VeryImportantVariableValue

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd7e0bd3-1f7d-d7b6-cc72-5ef63c31b46a
* Version Independent ID: dae87abd-b73d-9120-bcdb-6097d4b40f2a
* Content: [Variables - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch#feedback)
* Content Source: [docs/pipelines/process/variables.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/variables.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by damccorm** [comment]
Hey @Willem-J-an, thanks for the feedback!

I think this is actually working as designed/doced. To walk through your example:

```
vmImage: 'vs2017-win2016'
steps:

- powershell: |
   $JsonVar = 'VeryImportantVariableValue'
   Write-Host "##vso[task.setvariable variable=JsonVarOutput;isOutput=true]$JsonVar" # Works in secondJobFirstStep
   Write-Host "##vso[task.setvariable variable=JsonVar]$JsonVar" # Works In FirstJobSecondStep
   name: 'FirstJobFirstStep'
```

This first step sets `JsonVarOutput` as an output, and `JsonVar` as a normal variable

```
- powershell: |
   Write-Host "Below does not work with isOutput=true"
   Write-Host "JsonVarOutput: "+ $Env:JSONVAROUTPUT " OR " # Causes error > $(JSONVAROUTPUT)
   Write-Host "Below works without isOutput=true"
   Write-Host "JsonVar: "+ $Env:JSONVAR " OR " $(JSONVAR)
   Write-Host "Below is the working syntax when isOutput is true"
   Write-Host "Job drill var notation" + $Env:FirstJobFirstStep_JsonVarOutput " OR " $(FirstJobFirstStep.JsonVarOutput)
   name: 'FirstJobSecondStep'
```

Results::
```
Below does not work with isOutput=true
JsonVarOutput: + OR
```

As you've noticed here, `JSONVAROUTPUT` doesn't resolve to a variable. This is because, per the docs, this variable needs to be prefixed with the scope it was set from - see [here](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch#set-a-multi-job-output-variable)

```
Below works without isOutput=true
JsonVar: + VeryImportantVariableValue OR VeryImportantVariableValue
Below is the working syntax when isOutput is true
Job drill var notation + VeryImportantVariableValue OR VeryImportantVariableValue
```

This part is working as you expected, so I won't add further comments on it.

**Comment by damccorm** [comment]
I'm going to close since this looks like a no-op on our end
