### ISSUE TITLE
Use Nuget with Azure Devops Services should be removed when filter is Azure Devops Server 2019

### ISSUE THREAD

**Issue by spashx** [MicrosoftDocs/vsts-docs#4812]
The documentation is very confusing because "Use Nuget with Azure Devops Services" still shows when filter is Azure Devops Server 2019. Most people will go into this page and trying with Nuget V2 scanerios to authenticate with PAT token, which does not work at all. The "Use Nuget or dotnet with TFS" shall replace it and be renamed "Use Nuget with Azure Devops Server".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab0a3735-a9b0-2ed7-f08f-5321f55f8c90
* Version Independent ID: 2153f6c0-def7-eed1-286d-5e61c9fcbec4
* Content: [Use NuGet with Azure DevOps Services feeds](https://docs.microsoft.com/en-us/azure/devops/artifacts/nuget/nuget-exe?view=azure-devops-2019#feedback)
* Content Source: [docs/artifacts/nuget/nuget-exe.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/artifacts/nuget/nuget-exe.md)
* Product: **devops**
* Technology: **devops-artifacts**
* GitHub Login: @chasewilson
* Microsoft Alias: **phwilson**

**Comment by chasewilson** [comment]
@spashx Thanks for the feedback! I'll be working on this issue to get it closed out as soon as possible. 
Feel free to reach out with any more questions or feedback
