### ISSUE TITLE
Task group parameter - picklist

### ISSUE THREAD

**Issue by manivasm** [MicrosoftDocs/vsts-docs#4813]
Created custom task with pick-list as parameter type. Created task group from this custom task. When created task group options appear as pick-list. If there is any update made later in task and saved.

Task group parameter types 'pick list' became 'edit'.

**Comment by WilliamAntonRohm** [comment]
@manivasm  Thanks for your feedback; we appreciate it. To make sure we have all the information needed to triage your issue, please let us know which topic you’re referencing, or provide more context around the general task.

**Comment by WilliamAntonRohm** [comment]
I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
