### ISSUE TITLE
Seems to suggest the values of Priority, Business Priority can be changed for Azure DevOps Services (Cloud Hosted) when it is not

### ISSUE THREAD

**Issue by krmeda** [MicrosoftDocs/vsts-docs#4817]
The notes: 
&gt; To change the menu selection, see Add or modify a field, customize a picklist.
seems to suggest that we can change the picklist value when it cannot be for the cloud hosted Azure DevOps Services using inherited processes. 

Can this be fixed?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f2a7ad6d-e610-358e-57ab-65c139ec2fad
* Version Independent ID: a84f995c-6511-7e3a-c911-8dca8e1fb357
* Content: [Pick list queries - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/queries/planning-ranking-priorities?view=azure-devops#feedback)
* Content Source: [docs/boards/queries/planning-ranking-priorities.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/boards/queries/planning-ranking-priorities.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@krmeda - Thank you for your inquiry. You are correct that currently you can't change the picklist values for  inherited fields for Azure DevOps Services. There are plans on the product backlog to support this capability. Meanwhile, I will update the topic to reflect the current restriction.
