### ISSUE TITLE
API for billing operations

### ISSUE THREAD

**Issue by borys86** [MicrosoftDocs/vsts-docs#4818]
Are there any APIs that can be used to perform some of billing operations?
In particular I would like programmatically increase number of basic user licenses and be able to retrieve number of available (free) basic licenses. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 53803b6d-5089-79d1-34f3-c708c088d42d
* Version Independent ID: b4b0d600-3fe6-ecc1-5abf-ddc1c7bc6c48
* Content: [Billing articles - Azure DevOps - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/billing/?toc=%2Fazure%2Fdevops%2Fbilling%2Ftoc.json&bc=%2Fazure%2Fdevops%2Fbilling%2Fbreadcrumb%2Ftoc.json&view=azure-devops)
* Content Source: [docs/organizations/billing/index.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/billing/index.md)
* Product: **devops**
* Technology: **devops-billing**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @borys86, Thanks for reaching out. We've had similar requests and those customers have been satisfied with the new billing model that we're implementing. Check out this [Roadmap Item 1366420](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdev.azure.com%2Fmseng%2FAzureDevOpsRoadmap%2F_workitems%2Fedit%2F1366420&data=02%7C01%7CChrystal.Comley%40microsoft.com%7C4398c7931ad54cd897bc08d705887242%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636983955902309956&sdata=ZMkvhgVVyVwYdUEmS4g85sWcsxgrNidHKRoaOnY2%2BE0%3D&reserved=0). If you're interested in joining the private preview, send an email to Andrew at Andrew dot Brenner at Microsoft dot com. Thanks very much!
