### ISSUE TITLE
Broken Syntax

### ISSUE THREAD

**Issue by kylejrp** [MicrosoftDocs/vsts-docs#4819]
The section "Rename, move, or delete an area path" has the following quote showing - it looks like something wasn't parsed correctly and shows up incorrectly formatted instead:
> =tfs-2017 &lt;= tfs-2018&gt; [!NOTE] When you delete an area node or change the Location field for a node, the system automatically updates the existing work items with the node that you enter at the deletion prompt.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d41d9341-94a7-4df3-ea46-d76c5c39c14d
* Version Independent ID: 777f7374-ce28-d9d7-9d64-ba44603693c7
* Content: [Define area paths for a project - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/organizations/settings/set-area-paths?view=azure-devops)
* Content Source: [docs/organizations/settings/set-area-paths.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/settings/set-area-paths.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by kylejrp** [comment]
![image](https://user-images.githubusercontent.com/6742479/61001730-05e44f00-a315-11e9-89ab-b371a5818aef.png)

**Comment by WilliamAntonRohm** [comment]
@KathrynEE -- this is line 300; I'm not sure of the correct versioning.

**Comment by KathrynEE** [comment]
@kylejrp - Thank you for the correction. I noticed this the other day and corrected it. I believe it is now fixed.
