### ISSUE TITLE
Consider documenting what the VSTS feed's Default view setting does

### ISSUE THREAD

**Issue by chwarr** [MicrosoftDocs/vsts-docs#482]
In a VSTS feed's Settings on the Views tab, each view has a radio button in the "Default" column. It's not clear from any of the documentation what this does. E.g., does it automatically promote newly pushed packages to this view? Does it silently redirect feed URLs that don't specify a view to this view? Something else?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b254809-bcfe-5859-42e1-05df82aa730b
* Version Independent ID: cd8e1d01-c11b-4173-8f36-95d4237bc6a5
* Content: [Communicate package quality with release views](https://docs.microsoft.com/en-us/vsts/package/feeds/views?view=vsts#feedback)
* Content Source: [docs/package/feeds/views.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/package/feeds/views.md)
* Service: **unspecified**
* GitHub Login: @erickson-doug
* Microsoft Alias: **amullans**

**Comment by steved0x** [comment]
@chwarr There is an update coming to the Feed docs that should include an answer to this question - I don't have the answer to share right now but I am told it is coming soon. Thank you.
