### ISSUE TITLE
Unable to see Docker template on Configure tab

### ISSUE THREAD

**Issue by webbsk** [MicrosoftDocs/vsts-docs#4821]
"When the Configure tab appears, select Docker. The Docker template requires additional inputs." I am unable to see Docker as an option from the Configure tab. Has this option been removed or merged into another? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e825c07d-2168-c0aa-782a-ef6f9c7ba95e
* Version Independent ID: 5cb6926b-215a-bf89-8e63-b2e1129e41df
* Content: [Build, test, and push Docker container apps - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/languages/docker?view=azure-devops#feedback)
* Content Source: [docs/pipelines/languages/docker.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/languages/docker.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @vijayma
* Microsoft Alias: **vijayma**

**Comment by webbsk** [comment]
Specifically, I have this problem when using the new Yaml editor rather than the classic Task oriented view for creating a pipeline.

**Comment by webbsk** [comment]
Not only that but I think it requires more documentation because of the service connection required. After selecting the "Click Authorize to configure an Azure service connection. A new Azure service principal will be created and added to the Contributor role, having access to all resources in the selected subscription." Is this a manual process when using the Yaml and has to be configured in the task or script properties?

**Comment by webbsk** [comment]
In the above comment, I meant to say after selecting the subscription containing your ACR you are prompted with "Click Authorize...".

**Comment by gvillenave** [comment]
Same here, even though my Azure Container Registry is linked correctly, the Docker option doesn't appear at all in the build pipeline templates.

**Comment by jpushpanathan** [comment]
Enabling Preview Features as suggested by @gvillenave fixed it for me.

**Comment by anandvardhandas** [comment]
> I had the same issue, but fixed it by going to Preview Features and enabled the Multi-Stage pipeline experience flight.

From where can I enable Preview feature for avoiding this issue?

**Comment by jpushpanathan** [comment]
@anandvardhandas 	you can find the preview feature by going to your AzureDevops portal (usually starts with https://dev.azure.com/{organisationid}), click the icon on the top right hand corner which will have your initials. The menu that showsup will have the Preview Feature.

**Comment by shashankbarsin** [comment]
This issue is associated with the old languages/docker.md doc. The entire set of documentation associated with container ecosystem has been updated and this issue no longer exists on the build-image.md doc file.

Also, a note on enabling the preview feature for multi-stage experience has been included in the doc on [Build and Push to Azure Container Registry](https://docs.microsoft.com/azure/devops/pipelines/ecosystems/containers/acr-template?view=azure-devops)
