### ISSUE TITLE
Example will not retrieve all work items under a given area path

### ISSUE THREAD

**Issue by jdshkolnik** [MicrosoftDocs/vsts-docs#4824]
The section header says "Retrieve all work items under a given Area Path" but equal is not the same as under. If I pass in an area path of "Root" the example will not also include "Root/Level2".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 44bc2357-48c9-e331-0d1c-ea07ea294c7b
* Version Independent ID: 989fb7bf-3078-6e27-3c7c-25b776611df3
* Content: [Analytics basic queries - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/report/extend-analytics/analytics-recipes?view=azure-devops)
* Content Source: [docs/report/extend-analytics/analytics-recipes.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/report/extend-analytics/analytics-recipes.md)
* Product: **devops**
* Technology: **devops-analytics**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@jdshkolnik - Thank you for your inquiry. We will look at updating the topic.
@gregg - Can you take a look at this issue and let me know of the update to make.

**Comment by greggboer** [comment]
The correct query is as follows. We'll update the topic as soon as we can.

https://analytics.dev.azure.com/{OrganizationName}/{ProjectName}/_odata/{version}//WorkItems?
  $filter= startswith(Area/AreaPath,'{area path}')
  &$select=WorkItemId, Title, State

**Comment by KathrynEE** [comment]
@jdshkolnik - Closing this issue as Gregg has provided a response. We will update the topic soon.
