### ISSUE TITLE
Automate most of the custom task folder creation

### ISSUE THREAD

**Issue by ricardoserradas** [MicrosoftDocs/vsts-docs#4828]
I have created this Gist to help accelerate/scaffold a new task folder:

https://gist.github.com/ricardoserradas/afe9cf365023e15e8f0490a108fa9dfd

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 44581f4a-93df-7507-3844-eadedf9a6cc4
* Version Independent ID: 33c7bcf0-1512-975f-5ef8-9f2a192a84ad
* Content: [Add a Build or Release Task](https://docs.microsoft.com/en-us/azure/devops/extend/develop/add-build-task?toc=%2Fazure%2Fdevops%2Fextend%2Ftoc.json&bc=%2Fazure%2Fdevops%2Fextend%2Fbreadcrumb%2Ftoc.json&view=azure-devops#feedback)
* Content Source: [docs/extend/develop/add-build-task.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/extend/develop/add-build-task.md)
* Product: **devops**
* Technology: **devops-ecosystem**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @ricardoserradas, Thanks for this. I'll review it with the PM!

**Comment by Balfa** [comment]
Looks like there's a breaking change in the API of `azure-pipelines-task-lib/task`. When I run `tsc` against the `index.ts` as presented above, I get `index.ts:5:15 - error TS2322: Type 'string | undefined' is not assignable to type 'string'.`.
Replacing `const inputString: string = tl.getInput('samplestring', true);` with `const inputString: string | undefined = tl.getInput('samplestring', true);` fixes the problem.
