### ISSUE TITLE
Contributions Guide extension no longer applies or works and confuses users, wastes time

### ISSUE THREAD

**Issue by cicorias** [MicrosoftDocs/vsts-docs#4836]
The link to the Contributions Guide extension, well it exists, but the extension doesn't work anymore. https://marketplace.visualstudio.com/items/ms-samples.samples-contributions-guide

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 56437af3-75da-d219-5364-9b7927298ece
* Version Independent ID: ca01655a-9195-cf92-14b4-77ef66053dcf
* Content: [Extension Points](https://docs.microsoft.com/en-us/azure/devops/extend/reference/targets/overview?view=azure-devops#feedback)
* Content Source: [docs/extend/reference/targets/overview.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/extend/reference/targets/overview.md)
* Product: **devops**
* Technology: **devops-ecosystem**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @cicorias, Thanks for reaching out. What doesn't work with it? We're seeing it work on our end. It's possible that some of the contribution points the extension used to target don't exist anymore, but for the targets that do exist, it works. Please let me know if you have further questions.

**Comment by cicorias** [comment]
not sure why you had it working. But I deployed it from the marketplace and it didn't. So I cloned the repo/published and needed to change the following for it to work.

![image](https://user-images.githubusercontent.com/1080406/61075258-912e1500-a3e7-11e9-9c22-4a7742d4bcbe.png)

**Comment by chcomley** [comment]
@cicorias, Glad you got it working. Thanks for letting us know! Have a great day.

**Comment by cicorias** [comment]
i guess the point is, the Marketplace version "wasn't" working - and that's what the Doc refers to.
