### ISSUE TITLE
Delete *.<stage>.config after deploy

### ISSUE THREAD

**Issue by oalexrivas** [MicrosoftDocs/vsts-docs#4839]
Such as deleting files *. &lt;Stage&gt; .config after successfully made the transformation and deployment on physical path (IIS)?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 315ff823-9992-9f9b-62a1-42ce622ed41c
* Version Independent ID: 72ec3ffc-1dc9-b2dc-e3d4-4f14deae3720
* Content: [File transforms and variable substitution - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/transforms-variable-substitution?view=azure-devops#feedback)
* Content Source: [docs/pipelines/tasks/transforms-variable-substitution.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/transforms-variable-substitution.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by RoopeshNair** [comment]
The workflow tasks doesn't delete any files after deploy. If you are looking to clean-up then I would recommend using script step to delete the intended files.
