### ISSUE TITLE
what is the deadline for this ?

### ISSUE THREAD

**Issue by rifaterdemsahin** [MicrosoftDocs/vsts-docs#484]
Right now, VSTS and TFS do not provide a guarantee that every package npm installed via a feed with upstreams enabled will be cached.

We need everything to be cached.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4ff57df1-4d85-8003-6b56-d8756187574c
* Version Independent ID: e58c2616-e859-e917-91f9-42c50c5f0582
* Content: [Use packages from npmjs.com](https://docs.microsoft.com/en-gb/vsts/package/npm/upstream-sources?view=vsts)
* Content Source: [docs/package/npm/upstream-sources.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/package/npm/upstream-sources.md)
* Service: **unspecified**
* GitHub Login: @erickson-doug
* Microsoft Alias: **cajone**

**Comment by alexmullans** [comment]
Thanks for the feedback. The story right now is a bit complex, but it'll be smoothed out over the next few sprints. 

Today, there is guaranteed caching for npm packages **if** you have a relatively new feed. You can check using the [instructions here](https://docs.microsoft.com/en-gb/vsts/package/concepts/upstream-sources?view=vsts#legacy-upstream-source-information). If you're able to add the nuget.org upstream source, your feed has guaranteed caching. If not, your feed is a 'legacy' feed that we'll be updating in a few sprints to move to the guaranteed caching feature.

If you do have a legacy feed, the workaround for now is to create a new feed. All new feeds have guaranteed caching enabled.

Thanks for logging a docs bug, we'll clarify this page.

**Comment by steved0x** [comment]
Thank you Alex.
