### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by ChristianBeier** [MicrosoftDocs/vsts-docs#4844]
Linking page
https://docs.microsoft.com/en-us/azure/devops/user-guide/sign-up-invite-teammates?view=azure-devops#create-a-project

the following links

1. https://docs.microsoft.com/en-us/azure/devops/repos/tfvc/comparison-git-tfvc.md
2. https://docs.microsoft.com/en-us/azure/vsts-docs/docs/boards/work-items/guidance/choose-process.md

are not reachable while pages are available in

1. https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/repos/tfvc/comparison-git-tfvc.md
2. https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/boards/work-items/guidance/choose-process.md

**Comment by msebolt** [comment]
Fix out for review at https://dev.azure.com/mseng/TechnicalContent/_git/vsts-docs-pr/pullrequest/486093?_a=overview.

**Comment by msebolt** [comment]
@ChristianBeier Thank you for the feedback!

The change has been made.
