### ISSUE TITLE
CA Policy blocking access within other Azure services

### ISSUE THREAD

**Issue by rohancragg** [MicrosoftDocs/vsts-docs#4845]
I've been discovering that a with Conditional Access policy as described here (i.e which is blocks access to 'Azure DevOps' Cloud app unless the user is coming from a Named Location).

I've found that this works as expected, but that it blocks other services such as Notebook (Git) version control in Azure Databricks (https://docs.azuredatabricks.net/user-guide/notebooks/azure-devops-services-version-control.html), and is also prevents an App Service (in this case a Function App) from performing a Git sync.

I have found what I hope are appropriate work-arounds (below) which may be useful to document here?

---
Workarounds
---

I have discovered that if I can identify IP addresses of the Databricks Control Plane NAT (https://docs.azuredatabricks.net/administration-guide/cloud-configurations/azure/udr.html#control-plane-nat-and-webapp-ip-addresses) and add those into the CA Policy as another Named Location to be excluded then this fixes the issue.

Similarly, for App Services, I can fix the problem by adding the outbound IP addresses of the App Service Resource (obtained as follows:   
https://docs.microsoft.com/en-us/azure/app-service/overview-inbound-outbound-ips)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 24bd6400-4207-6f85-8a4e-5c9b0cc99cff
* Version Independent ID: 0b018039-29d1-431a-1be9-4b46af7f084f
* Content: [Manage conditional access policies - Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/manage-conditional-access?view=azure-devops)
* Content Source: [docs/organizations/accounts/manage-conditional-access.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/accounts/manage-conditional-access.md)
* Product: **devops**
* Technology: **devops-accounts**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Thanks @rohancragg, This is good stuff. I'll review with the PM and will be in touch! Thanks again.

**Comment by chcomley** [comment]
@rohancragg, I've reassigned this issue to an Azure-specific writer, as we believe your workarounds/FAQs would be best documented there. Thanks so much for your feedback and we'll be in touch. Thanks to @MicrosoftGuyJFlo, for your assistance!

**Comment by MicrosoftGuyJFlo** [comment]
@chcomley

**Comment by chcomley** [comment]
@rohancragg, Turns out, there wasn't an appropriate location within the Azure docs, so I put a note into the article saying some third party extensions may require additional configuration changes. If we get more feedback like this, I may add some troubleshooting information, based on your workarounds. Thanks so much for your feedback, we appreciate it!

**Comment by rohancragg** [comment]
@chcomley this isn't a 3rd-party extension for Azure DevOps, but I agree there's no required configuration in Azure DevOps itself so probably not content for this area of the Docs. The workaround is a configuration made in Conditional Access (Azure Active Directory).

The information perhaps best belongs in the Azure Databricks documentation (probably here: https://docs.microsoft.com/en-us/azure/databricks/notebooks/azure-devops-services-version-control) as it's about how to use and Azure DevOps Repo as Git version control for a Databricks Notebook. Will I post something there or can you find a contact to pick this up?
