### ISSUE TITLE
Link to GitHub is broken

### ISSUE THREAD

**Issue by ritchxu** [MicrosoftDocs/vsts-docs#4846]
The GitHub link in this section is broken: https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/azure-function?view=azure-devops#open-source

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 788ade26-087e-737f-21fd-5cc9f36666a5
* Version Independent ID: 78733f37-e78e-e044-e2e9-5e67a2eae374
* Content: [Invoke Azure Function task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/azure-function?view=azure-devops#open-source)
* Content Source: [docs/pipelines/tasks/utility/azure-function.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/utility/azure-function.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by RoopeshNair** [comment]
@shashban

**Comment by msebolt** [comment]
Fix out for review at https://dev.azure.com/mseng/TechnicalContent/_git/vsts-docs-pr/pullrequest/486095?_a=overview.

**Comment by msebolt** [comment]
@ritchxu Thank you for the feedback!

The change has been made.
