### ISSUE TITLE
Typo in documentation

### ISSUE THREAD

**Issue by SaltyCybernaut** [MicrosoftDocs/vsts-docs#4849]
the phrase: "but this is discouraged unless your history is very simple." should be changed to: "but this is discouraged if your history is very simple."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 44afc4fe-66c8-a745-0037-00748a80beb7
* Version Independent ID: 0ea09401-6a08-d745-ff50-7a7b74c41f32
* Content: [Migrate from TFVC to Git - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/learn/git/migrate-from-tfvc-to-git#feedback)
* Content Source: [https://mseng.visualstudio.com/DefaultCollection/TechnicalContent/_git/devops-learn-pr?path=%2fdocs%2fgit%2fmigrate-from-tfvc-to-git.md&version=GBlive&_a=contents](https://mseng.visualstudio.com/DefaultCollection/TechnicalContent/_git/devops-learn-pr?path=%2fdocs%2fgit%2fmigrate-from-tfvc-to-git.md&version=GBlive&_a=contents)
* Product: **devops**
* Technology: **devops-learn**
* Git Login: **samgu**
* Microsoft Alias: **routlaw**

**Comment by WilliamAntonRohm** [comment]
Update is ready for merge in https://dev.azure.com/mseng/TechnicalContent/_git/devops-learn-pr/pullrequest/491305

@rloutlaw -- Robert, please confirm this change.

**Comment by WilliamAntonRohm** [comment]
@SaltyCybernaut -- thank you for your feedback.  This update is in the documentation and should be live by tomorrow.
