### ISSUE TITLE
Recommendations for workspaces and shelvesets

### ISSUE THREAD

**Issue by emilpeder1984** [MicrosoftDocs/vsts-docs#485]
It could be useful with recommendations on how to handle existing workspaces created with MSA accounts, since these will not be usable after switching to AAD. I suppose one idea is to make sure users unmap prior to the migration.
Additionally, it seems shelvesets created with MSA accounts cannot be accessed after the migration. It is possible to find all shelvesets, but clicking "View Shelveset Details" from Visual Studio, shows an error message that the shelveset could not be found. Is it possible to add a description for a work around on this?
To reduce disruption, a tutorial like this should ideally cover most scenarios that one has to account for before starting the migration. Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f56d653-f3ed-88a3-c307-1ba6eec6cbc2
* Version Independent ID: 5f5b1c72-7b2a-a7cf-aea7-39cf84b11005
* Content: [Connect VSTS account to Azure Active Directory (Azure AD)](https://docs.microsoft.com/en-us/vsts/accounts/connect-account-to-aad?view=vsts)
* Content Source: [docs/accounts/connect-account-to-aad.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/accounts/connect-account-to-aad.md)
* Service: **unspecified**
* GitHub Login: @erickson-doug
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
@emilpeder1984 Thanks for the feedback, we appreciate it. We are currently working on a fix for handling existing workspaces created with MSA accounts. Shelvesets created with MSA accounts should be accessible by the new Azure AD identity.

**Comment by emilpeder1984** [comment]
Thanks for the reply. Sounds good with a fix for handling workspaces. It seems the problems we experienced with accessing shelvesets were temporary in the hours following the migration.

Venlig hilsen

Emil Pedersen
IT Markedssystemer
+4524837425
epe@energinet.dk<mailto:epe@energinet.dk>


Fra: chcomley [mailto:notifications@github.com]
Sendt: 6. april 2018 00:29
Til: MicrosoftDocs/vsts-docs
Cc: Emil Pedersen; Mention
Emne: Re: [MicrosoftDocs/vsts-docs] Recommendations for workspaces and shelvesets (#485)


@emilpeder1984<https://github.com/emilpeder1984> Thanks for the feedback, we appreciate it. We are currently working on a fix for handling existing workspaces created with MSA accounts. Shelvesets created with MSA accounts should be accessible by the new Azure AD identity.

**Comment by chcomley** [comment]
@emilpeder1984 That's great to hear, thank you!
