### ISSUE TITLE
Description of argument "Preferred Azure PowerShell Version" seams to reference Powershell versions, not Az Powershell

### ISSUE THREAD

**Issue by aleksey-korolev** [MicrosoftDocs/vsts-docs#4850]
Description for argument Preferred Azure PowerShell Version says "The Hosted VS2017 pool currently supports versions: 2.1.0, 3.8.0, 4.2.1, 5.1.1" but according to https://github.com/Azure/azure-powershell/releases the latest Az PowerShell release is 2.4.0

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fb215324-b1a0-93b5-5022-4bcc7da93bb7
* Version Independent ID: 9eb2977b-ac34-9d53-670e-04fa027bc8e4
* Content: [Azure PowerShell task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-powershell?view=azure-devops#feedback)
* Content Source: [docs/pipelines/tasks/deploy/azure-powershell.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/deploy/azure-powershell.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by mhdubose** [comment]
This confused me as well. In version 4, the text reads "Preferred Azure PowerShell Version needs to be a proper semantic version eg. 1.2.3. Regex like 2.*,2.3.* is not supported. The Hosted VS2017 Pool currently supports Az module version: 1.0.0"

It is still very ambiguous whether they are asking for a powershell version number or the Az Module version number. I used 1.0.0, as I assumed it meant the module version, and it worked, but clarifying this would be nice.

**Comment by RoopeshNair** [comment]
Ack, the latest version of Azure PowerShell relies on Az modules. The help texts needs to be updated.

**Comment by msebolt** [comment]
Sorry for the delay, the an update to the article is under review.
