### ISSUE TITLE
Mention of `DotNetCoreInstaller@0` instead of `UseDotNet@2`

### ISSUE THREAD

**Issue by Kissaki** [MicrosoftDocs/vsts-docs#4856]
Is this outdated and was the previous way to do it, before `UseDotNet` existed?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 483dcb1c-1a89-2b20-4cf2-abd3ae88d9ed
* Version Independent ID: dc4722ed-5a4b-26ec-e7d5-a149bf6e79a7
* Content: [Build, test, and deploy .NET Core apps - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/languages/dotnet-core?view=azure-devops#build-your-project)
* Content Source: [docs/pipelines/languages/dotnet-core.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/languages/dotnet-core.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by chasewilson** [comment]
@Kissaki Thanks for your question! I don't believe this doc is out of date but if you see something that doesn't look right, I hope you'll open a new issue :) 
As for your question about the useDotNet task, that task actually allows you to change the version of Dot Net Core for subsequent tasks. You can find more info on the [task page here](https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/UseDotNetV2)
