### ISSUE TITLE
Code sample doesn't work

### ISSUE THREAD

**Issue by jakecahill** [MicrosoftDocs/vsts-docs#486]
When I test this code sample I keep getting this error on the line` using (WorkItemTrackingHttpClient workItemTrackingHttpClient = new WorkItemTrackingHttpClient(uri, credentials))`:

`Could not load file or assembly 'System.Net.Http, Version=2.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'`

I've already installed all the necessary nugets.
It's not a very helpful quickstart.

Please can someone look into this error and provide a solution, or update the quickstart with more comprehensive information.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e978322f-15ae-3a89-ae89-497cdfa5070a
* Version Independent ID: f8654902-e266-c12b-8e25-a2fa7a2ac626
* Content: [Get work items programmatically from Visual Studio Team Services](https://docs.microsoft.com/en-us/vsts/integrate/quickstarts/work-item-quickstart?view=vsts#feedback)
* Content Source: [docs/integrate/quickstarts/work-item-quickstart.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/integrate/quickstarts/work-item-quickstart.md)
* Service: **unspecified**
* GitHub Login: @erickson-doug
* Microsoft Alias: **elbatk**

**Comment by jakecahill** [comment]
If someone could just provide a way to make sure I have all the correct nugets, that would be great.

**Comment by wnjenkin** [comment]
Assigning this to @labrose to help out.

**Comment by mmanela** [comment]
I just tested the the sample works for me. @jakecahill can you share what versions of the nuget packages you have. This is what I have:


![image](https://user-images.githubusercontent.com/304410/38516213-57d2c23e-3beb-11e8-809a-85ba4600dc78.png)
![image](https://user-images.githubusercontent.com/304410/38516217-5e5f359c-3beb-11e8-9fd8-7775d68ec3c8.png)

**Comment by jakecahill** [comment]
Hi @mmanela , thanks for getting back to me. It seems that I don't have a System.Net.Http.WebRequest in my dotnet folder.

Do you have a link to where I can get the dll file?

I'd installed both of those nuget packages that you mentioned.

**Comment by mmanela** [comment]
I don't have that either. Here is my solution, can you try that. You will need to click on the solution first and restore packages.
[TEST.zip](https://github.com/MicrosoftDocs/vsts-docs/files/1895629/TEST.zip)

**Comment by jakecahill** [comment]
Hey @mmanela , thanks for providing the solutions. However, now I get the following error on the same line:

System.TypeInitializationException
  HResult=0x80131534
  Message=The type initializer for 'Microsoft.VisualStudio.Services.Common.VssHttpMessageHandler' threw an exception.
  Source=Microsoft.VisualStudio.Services.Common
  StackTrace:
   at Microsoft.VisualStudio.Services.Common.VssHttpMessageHandler.get_DefaultWebProxy()
   at Microsoft.VisualStudio.Services.Common.VssHttpMessageHandler.ApplySettings(HttpMessageHandler handler, ICredentials defaultCredentials, VssHttpRequestSettings settings)
   at Microsoft.VisualStudio.Services.Common.VssHttpMessageHandler..ctor(VssCredentials credentials, VssHttpRequestSettings settings, HttpMessageHandler innerHandler)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.BuildHandler(VssCredentials credentials, VssHttpRequestSettings settings, DelegatingHandler[] handlers)
   at Microsoft.TeamFoundation.WorkItemTracking.WebApi.WorkItemTrackingHttpClient..ctor(Uri baseUrl, VssCredentials credentials)
   at ConsoleApp1.ExecuteQuery.RunGetBugsQueryUsingClientLib() in H:\practice API\ConsoleApp1\ConsoleApp1\ExecuteQuery.cs:line 50
   at ConsoleApp1.Program.Main(String[] args) in H:\practice API\ConsoleApp1\ConsoleApp1\Program.cs:line 13

Inner Exception 1:
ConfigurationErrorsException: Error creating the Web Proxy specified in the 'system.net/defaultProxy' configuration section.

Inner Exception 2:
SocketException: An invalid argument was supplied

**Comment by mmanela** [comment]
Can you confirm that your nuget packages are all up-to-date? If you go to the package manager, make sure no pending updates.

/cc @tedchamb

**Comment by jakecahill** [comment]
Hi @mmanela, all my packages are up to date, I used your example, but I keep getting the same error

**Comment by mmanela** [comment]
Can you share me your solution? @jakecahill

**Comment by jakecahill** [comment]
I just used the same solution that you shared.
[ConsoleApp1.zip](https://github.com/MicrosoftDocs/vsts-docs/files/1914891/ConsoleApp1.zip) folder
[ConsoleApp1.zip](https://github.com/MicrosoftDocs/vsts-docs/files/1914895/ConsoleApp1.zip) solution file

**Comment by tedchambers** [comment]
@jakecahill Can you make sure you are not running as project located on a network share?  This is a .Net issue and not an issue with the vsts clients.  You can do a search for 'ConfigurationErrorsException: Error creating the Web Proxy specified in the 'system.net/defaultProxy' configuration section.' and you will see a number of reasons why this type of error can occur.  Running a project from a network share seams to be the most common.

**Comment by elbatk** [comment]
Closing this issue as it's been a month since the last comment, feel free to reopen if you're still having issues @jakecahill

**Comment by viniciusottoni** [comment]
I have the same issue with System.Net.Http.WebRequest, but with asp.net core 2.1.3 webapi.

**Comment by moqueur** [comment]
Have the same problem with asp.core 2.0

**Comment by elbatk** [comment]
Hey @tedchamb , it looks like you commented on this one a while back (April), could you take a look at the last two comments for me?

**Comment by HatemElshenawy** [comment]
any update , i have the same issue can not get correct ref
VssConnection connection = new VssConnection(_configuration.Source.Uri, new VssBasicCredential(string.Empty, _configuration.Source.AccessToken));
            // Get an instance of the work item tracking client
            _sourceClient = connection.GetClient<WorkItemTrackingHttpClient>();
WorkItemTrackingHttpClient   obj =_sourceClient.GetClient<WorkItemTrackingHttpClient>();

**Comment by tedchamb** [comment]
@HatemElshenawy Can you share a sample solution which repros your issue?

**Comment by ltsstar** [comment]
I have the same problem using .NET Core. Using .NET Framework works instead.
