### ISSUE TITLE
There are other actions you can't perform

### ISSUE THREAD

**Issue by cedricseah** [MicrosoftDocs/vsts-docs#4861]
Adding new work items (such as tasks) is one of them, unless you go into the full desktop view

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c102b9bf-accb-8166-9d5c-f12f1b8e1153
* Version Independent ID: 995cd9f2-17aa-86b4-6704-c89e02bdb3c2
* Content: [View and update work items via a mobile browser - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/project/navigation/mobile-work?view=azure-devops#feedback)
* Content Source: [docs/project/navigation/mobile-work.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/project/navigation/mobile-work.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@cedricseah - Thank you for your input. I will update the article to clarify.
