### ISSUE TITLE
Manifest file name

### ISSUE THREAD

**Issue by laedit** [MicrosoftDocs/vsts-docs#4862]
In this doc, the manifest is named `vss-extension.json` but in the [extension sample repository](https://github.com/microsoft/azure-devops-extension-sample) it is `azure-devops-extension.json`.
Which one should we use?
Are both accepted or should we migrate from vss to azure-devops?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d8b703fe-8982-4284-6db0-ef33abac08a4
* Version Independent ID: 0fc84d11-1c32-0a49-04ec-641b68f44886
* Content: [Extension Manifest Reference](https://docs.microsoft.com/en-us/azure/devops/extend/develop/manifest?view=azure-devops#feedback)
* Content Source: [docs/extend/develop/manifest.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/extend/develop/manifest.md)
* Product: **devops**
* Technology: **devops-ecosystem**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @laedit, Thanks for reaching out! It can be anything, so it doesn't matter which one you use. If you go for something like azure-devops-extension.json, then to package the extension,  call  _tfx extension create --rev-version --manifests azure-devops-extension.json_. I'll be closing this issue, but please let us know if you have any further questions. Thanks again!

**Comment by laedit** [comment]
@chcomley Thanks for your answer.
Just to be sure, there is no plan to replace the default `vss-extension.json` used by `tfx extension create` by `azure-devops-extension.json`?

**Comment by chcomley** [comment]
@laedit, There's no plan that I'm aware of. Thanks!
