### ISSUE TITLE
Atlassian - Jira Integration

### ISSUE THREAD

**Issue by jaikumarhm** [MicrosoftDocs/vsts-docs#4864]
Are there any thoughts around providing TFS - Jira integration?
When abc happens in Jira -&gt; do xyz in TFS
When def happens in TFS -&gt; do ghi in Jira 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4dc61b61-ed67-8313-99d4-d736e7f48234
* Version Independent ID: 3e0fcf87-9744-cec8-24f8-9f68371959c6
* Content: [Integrate with service hooks](https://docs.microsoft.com/en-us/azure/devops/service-hooks/overview?view=azure-devops#feedback)
* Content Source: [docs/service-hooks/overview.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/service-hooks/overview.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @chasewilson
* Microsoft Alias: **phwilson**

**Comment by nschonni** [comment]
There is pipelines integration https://devblogs.microsoft.com/devops/azure-pipelines-integration-with-jira-software/
If it's a feature request, it's better to post over on https://developercommunity.visualstudio.com/spaces/21/index.html

**Comment by chasewilson** [comment]
I'll be closing this issue for now. Feel free to open a new issue if you feel this one has been incorrectly closed.
