### ISSUE TITLE
Add examples for using variables with Script Path

### ISSUE THREAD

**Issue by aidangarnish** [MicrosoftDocs/vsts-docs#4865]
I have an inline script that references pipeline variables as follows:

call az group create --location uksouth --name $(resourcegroup)
call az appservice plan create --name $(appserviceplan) --resource-group $(resourcegroup) --sku B1

As soon as I switch to using a Script Path and using a .bat file the variables are not found. I suspect there is something simple that I am missing but have been unable to find the answer. Some examples of how to pass pipeline variables to the script file would be really useful.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8de3304e-98f9-bac0-3ccc-c65f68a89e87
* Version Independent ID: 8fb2f6a9-545d-dff1-ff86-974694a85054
* Content: [Azure CLI task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-cli?view=azure-devops#feedback)
* Content Source: [docs/pipelines/tasks/deploy/azure-cli.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/deploy/azure-cli.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by RoopeshNair** [comment]
The syntax for using these environment variables depends on the scripting language. Are you referring to them as in Batch script format?

- Batch script: %VARIABLE_NAME%
- PowerShell script: $env:VARIABLE_NAME
- Bash script: $VARIABLE_NAME

**Comment by aidangarnish** [comment]
That is great it was a simple syntax issue, I should have been using the batch script syntax. I think it would be worth linking to the documentation that describes the environment variable syntax for each scripting language. 
Blog posts tend to use one of these without explicitly calling out the type of script being used. Is there a general page that contains this information? If not I would be happy to help create one.

**Comment by RoopeshNair** [comment]
Here it is: https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch#set-variables-in-pipeline

**Comment by aidangarnish** [comment]
Brilliant - thanks! :-)
