### ISSUE TITLE
Link broken

### ISSUE THREAD

**Issue by jlian** [MicrosoftDocs/vsts-docs#4870]
In the first section it says "these videos at Scaled Agile Framework Foundations from Inbar Oren, the Lean Samurai, are a good way to orient yourself."

This link goes to a "not found" page

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1c926cb3-ed15-3489-65f8-2a5c1fd129d4
* Version Independent ID: 1b441906-10f0-2ec0-d1aa-d3686ff94146
* Content: [Scaled Agile Framework - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/plans/scaled-agile-framework?view=azure-devops&viewFallbackFrom=vsts)
* Content Source: [docs/boards/plans/scaled-agile-framework.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/boards/plans/scaled-agile-framework.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by msebolt** [comment]
@jlian Thank you for the feedback!

The change is currently under review.
