### ISSUE TITLE
Security Service Group is missed out at Collection-level groups

### ISSUE THREAD

**Issue by tompatib** [MicrosoftDocs/vsts-docs#4876]
All the groups are explained under the Collection-level groups section but Security Service Group, compared to the screenshot. Please add this group also to the grid as I couldn't find much information about that online and I had users assigned to that.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 68686c2b-c69a-d9e4-3e21-a46d231b649c
* Version Independent ID: 049659da-1772-3166-f909-4feeb8a97730
* Content: [What are all the default permissions and groups? - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/security/permissions?view=azure-devops#feedback)
* Content Source: [docs/organizations/security/permissions.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/security/permissions.md)
* Product: **devops**
* Technology: **devops-security**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@tompatib - Thank you for your inquiry. You are correct that this group isn't documented. I've added an item to my backlog to get it documented. This group was defined to hold users that were granted permissions, but were not added to any other security group. It was a hidden group at one time, but that caused problems.  This is not a security group to add users to directly. When you remove users from all security groups, you should remove them from this group as well as needed.
