### ISSUE TITLE
Im using https://dev.azure.com but the screen shots and instructions seem to be out of date.

### ISSUE THREAD

**Issue by kevshine** [MicrosoftDocs/vsts-docs#4877]
Step 7: Add Widget From the Catalog
Now, go to your team dashboard at http://dev.azure.com/{yourOrganization}/{yourProject}. If this page is already open, then refresh it. Hover on the Edit button in the bottom right

There is no edit button at the bottom right. 

There is an edit button at the top, this loads my widgets but I dont see my widget. As the instructions require some interpretation its hard  to know if I have an error or if the widget instructions dont work with the current version of azure. 

Fix:
----

Documentation should say:

-Go to project settings 
-Click Extensions
-Find the hello world Widget and click install  

Unless you do that you will not see the widget in the list for http://dev.azure.com/{yourOrganization}/{yourProject}

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bbe9c938-dde5-4eba-6e09-6e43ef0e8ee5
* Version Independent ID: 53f9961e-1c31-1080-1699-4ef901939b19
* Content: [Add a dashboard widget](https://docs.microsoft.com/en-gb/azure/devops/extend/develop/add-dashboard-widget?view=azure-devops#feedback)
* Content Source: [docs/extend/develop/add-dashboard-widget.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/extend/develop/add-dashboard-widget.md)
* Product: **devops**
* Technology: **devops-ecosystem**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by kevshine** [comment]
AH! Nothing about going to shared extensions and clicking install, but once I did that it worked. only a 36 hour delay.

**Comment by chcomley** [comment]
Thanks for the feedback, @kevshine. And I'm sorry for the confusion. I've created a user story to capture this update. Thanks again!

**Comment by chcomley** [comment]
I've published an update and linked the PR to this issue! Please let us know whether you have any further feedback on this. Thank you!
