### ISSUE TITLE
Chaotic reference, broken task

### ISSUE THREAD

**Issue by kkoyot** [MicrosoftDocs/vsts-docs#4880]
Both this document and the task itself is absolute rubbish:
- Tags are inconsistent with docker tag format
- No reason why there shouldn't be extra arguments input for buildAndPush (how about buildArguments and pushArguments parameters?)
- No explanation how to use build and push commands separately
- Tags don't work if you don't provide containerRegistry and repository parameters in build command (why should it matter? You're building locally. And again - consequence of tag format inconsistency and lack of documentation)
- containerRegistry should be named something along the lines of containerRegistryServiceConnection

Please simplify the task or document it better, I've spent half a day figuring out how to do an extremely trivial thing which is building and pushing my image

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d9dbf88-7e55-d427-145e-d36b04fb197f
* Version Independent ID: a3f30c00-817c-9c05-7a57-3f2bf618821e
* Content: [Docker task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/docker?view=azure-devops)
* Content Source: [docs/pipelines/tasks/build/docker.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/build/docker.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @thomps23
* Microsoft Alias: **shasb**

**Comment by shashankbarsin** [comment]
- For doing build and push separately, it's possible to have two Docker steps -first build and then push. For passing in arguments to each of them, `arguments` input can be used with each of the task. 
- Regarding the task needing container registry input as a required input, that's a bug and it will be fixed. Repository input is needed though
- Tags input is a multiline input where one tag can be mentioned in each line. Each of these tags are following standard docker tag format and there's no additional processing being done by the task.

**Comment by benny-gold** [comment]
I couldn't agree more: really unclear how to use this task. @shashankbarsin your comment hasn't fixed the documentation, why has this been closed?

**Comment by kkoyot** [comment]
@shashankbarsin :
- You haven't addressed the lack of build and push reference
- I've already figured out that build and push can be used separately, I've mentioned it in one of the points
- Please look up docker tag reference: https://docs.docker.com/engine/reference/commandline/tag/. By "following standard docker tag format" you mean the *optional* tag name but not the full image name along with the tag. I suggest adding an implicit image name splitting or other way of making the tags input by user accepting those compliant with docker standards

Last but not least: by no means this issue has been resolved, there are still some pain points that are needed to be addressed

**Comment by alexmg** [comment]
I have to agree the documentation here is lacking. Tasks that have multiple commands should have something in place to indicate what parameters are valid for each command. I end up having to go to the source repository to figure this out for myself.

**Comment by kitingChris** [comment]
Yep I also agree. Also completely missing are target. This task makes the usage of multi target dockerfiles impossible. 
Still need to fall back to a Bash task due to the lack of necessary inputs for this task
