### ISSUE TITLE
More information on choosing Multi-stage vs Release

### ISSUE THREAD

**Issue by milannankov** [MicrosoftDocs/vsts-docs#4881]
It would be great if you could provide some guidance as to when to choose creating a Release vs. creating a deploy stage in a multi-state pipeline. What are pros and cons of the two approaches. 

For example, I can have a pipeline with 2 stage (build, test) + Release which will deploy the artifacts to Azure. Versus, having a pipeline with 3 stages where the last stage is again deploying to Azure.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4266f72c-c774-0046-4593-d01eb775d3c3
* Version Independent ID: f20827aa-a6c5-96a8-5969-e576ffbc2e38
* Content: [Stages in Azure Pipelines - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/stages?view=azure-devops&tabs=yaml#feedback)
* Content Source: [docs/pipelines/process/stages.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/stages.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @vijayma
* Microsoft Alias: **vijayma**

**Comment by vijayma** [comment]
At present, the release approach has a lot more abilities such as automated gates, ability to retry failed deployments, etc. So, if you have to make a choice now, it would be primarily based on the set of available features in these two options. Over time, we expect that same set of features to be available in multi-stage pipelines as well. At that point, we expect that customers will prefer to use YAML files (config as code) to model their pipelines. Note that, you will be able to break up your pipeline into a CI pipeline and a CD pipeline - both modeled using YAML.

**Comment by fmms** [comment]
@vijayma how can i break up my pipeline between CI and CD? Can you point to any example? How can I reference the artifact of the CI pipeline when I break it up?
