### ISSUE TITLE
Unclear pre-requisites

### ISSUE THREAD

**Issue by brunoterkaly** [MicrosoftDocs/vsts-docs#4884]
Unclear guidance here:
https://docs.microsoft.com/en-us/azure/devops/extend/develop/add-build-task?toc=%2Fazure%2Fdevops%2Fextend%2Ftoc.json&bc=%2Fazure%2Fdevops%2Fextend%2Fbreadcrumb%2Ftoc.json&view=azure-devops#preparation-and-required-setup-for-this-tutorial

See Red box.

Unclear about having the correct image and size in the images folder. Asking the user to create vss-extension.json is confusing because the user has no idea what that means at this stage of the blog post. Also, why the README.md? Kind of self explanatory but still not clear.

![image](https://user-images.githubusercontent.com/1461866/61310764-cb156780-a7a9-11e9-8689-48fb4529ec2d.png)

**Comment by chcomley** [comment]
Hi @brunoterkaly, Thanks so much for the feedback. I've created a user story to capture this update and will be in touch. Thanks again!

**Comment by chcomley** [comment]
Hi @brunoterkaly, I've addressed your feedback, adding a bit of clarity, although we don't feel that there should be an explanation for the README, as most people who are coding at this level, creating tasks, will know that README's are quite common/standard. Please @mention me if you have any further questions or feedback. Thank you!
