### ISSUE TITLE
Faulty link for label format

### ISSUE THREAD

**Issue by roman-ledermann-erni** [MicrosoftDocs/vsts-docs#4885]
There are four links "label format" (in the sections Build.BuildNumber, Build.DefinitionName, Build.QueuedBy and Build.RequestedFor) which should lead to the documentation of the label format, but the linked page cannot be found.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ffebdc8-521c-44b5-cde4-4abdc1bd6f18
* Version Independent ID: dc0effda-6d93-62aa-64c5-4e6f283b0826
* Content: [Predefined variables - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml#feedback)
* Content Source: [docs/pipelines/build/variables.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/build/variables.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by msebolt** [comment]
@roman-ledermann-erni Thank you for the feedback.

A fix for this is currently under review.
