### ISSUE TITLE
persoanl spelling issue

### ISSUE THREAD

**Issue by daweim0** [MicrosoftDocs/vsts-docs#4888]
personal is spelled incorrectly in "For Azure DevOps, use a persoanl access token when prompt for credentials, see Authenticate access with personal access tokens"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a10a409-5468-9532-f0dc-5a28cdd566d8
* Version Independent ID: 2ef20266-bc45-448b-27f5-e5c3bffed2ef
* Content: [Get started with NuGet packages in Azure DevOps Services and TFS](https://docs.microsoft.com/en-us/azure/devops/artifacts/get-started-nuget?view=azure-devops)
* Content Source: [docs/artifacts/get-started-nuget.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/artifacts/get-started-nuget.md)
* Product: **devops**
* Technology: **devops-artifacts**
* GitHub Login: @chasewilson
* Microsoft Alias: **phwilson**

**Comment by WilliamAntonRohm** [comment]
Updated documentation with https://dev.azure.com/mseng/TechnicalContent/_git/vsts-docs-pr/pullrequest/491312

**Comment by WilliamAntonRohm** [comment]
@daweim0 -- David, thank you for your feedback.  I have updated the documentation and it should be live by tomorrow.
