### ISSUE TITLE
out of update document

### ISSUE THREAD

**Issue by tuantruong2206** [MicrosoftDocs/vsts-docs#4889]
This document has been out of updated for sample:
    - the section of "Create a Jenkins and AKS service connection in Azure Pipelines" - the screenshot is mismatch with current azure pipeline page version
        "Add a second service connection for the AKS cluster" step 4 is also out of update
    

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 31c95c7b-388a-7b39-5283-43193bb643df
* Version Independent ID: 943fc46d-a114-5555-d6e0-6ad2400d1ad0
* Content: [Deploy to Kubernetes on AKS with Jenkins - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/integrate-jenkins-pipelines-aks?view=azure-devops#feedback)
* Content Source: [docs/pipelines/release/integrate-jenkins-pipelines-aks.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/release/integrate-jenkins-pipelines-aks.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @mlearned
* Microsoft Alias: **mlearned**

**Comment by mlearned** [comment]
thanks, we have other updates coming for this doc, and we'll address the screenshot as well.
