### ISSUE TITLE
Not getting " Deploy to Azure Kubernetes Service" in configuration tab

### ISSUE THREAD

**Issue by geverghe** [MicrosoftDocs/vsts-docs#4895]
1. I clone the prescribed pipelines-javascript-docker repository and installed the app.
2. I tried creating a build pipeline and post analysis, I do not get the  Deploy to Kubernetes as a template option.
Including screenshot of options
![image](https://user-images.githubusercontent.com/16950956/61376944-d955a780-a8bf-11e9-99de-5d1dc3455c05.png)

**Comment by WilliamAntonRohm** [comment]
@geverghe Thanks for your feedback; we appreciate it. To make sure we have all the information needed to triage your issue, please let us know which topic you’re referencing, or provide more context around the general task.

**Comment by geverghe** [comment]
Closing this issue as I was checking for this on an account where the feature was not yet available.
