### ISSUE TITLE
Miss URL for Azure DevOps Server 2019.

### ISSUE THREAD

**Issue by kkamegawa** [MicrosoftDocs/vsts-docs#4896]
[Enter feedback here]

It missed URL for Azure DevOps Server 2019 in "Agent version and upgrades" and "Capabilities" and "How do I make sure I have the latest v2 agent version?" section.

miss:  
```
Azure DevOps Server 2019: https://dev.azure.com/{your_collection}/_settings/agentpools
```
collect:  
```
Azure DevOps Server 2019: https://{server}/{your_collection}/_settings/agentpools
```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 47625b86-abd5-ee15-6d61-8bcf81861b96
* Version Independent ID: be9a6174-a69b-7aed-d584-5f602fcc5eb4
* Content: [Azure Pipelines Agents - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/agents?view=azure-devops#feedback)
* Content Source: [docs/pipelines/agents/agents.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/agents/agents.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by WilliamAntonRohm** [comment]
Updated document in https://dev.azure.com/mseng/TechnicalContent/_git/vsts-docs-pr/pullrequest/491320

@steved0x -- Steve, please confirm this change.

**Comment by WilliamAntonRohm** [comment]
@kkamegawa -- Kazushi, thank you for your feedback.  We are updating the documentation now.
