### ISSUE TITLE
React

### ISSUE THREAD

**Issue by Liran-Dobrish** [MicrosoftDocs/vsts-docs#4897]
please show an example for react and the AzureDevops node modules

---
#### פרטי מסמך

⚠ *אין לערוך מקטע זה. פעולה זו נדרשת עבור קישור לנושאים ב- docs.microsoft.com ← GitHub.*

* ID: 6e6cb0ed-c129-901c-10a2-909354aa562f
* Version Independent ID: ceb10d41-b306-0d3f-ccb2-124a3ba69332
* Content: [Add a custom control to the work item form](https://docs.microsoft.com/he-il/azure/devops/extend/develop/custom-control?view=azure-devops)
* Content Source: [docs/extend/develop/custom-control.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/extend/develop/custom-control.md)
* Product: **devops**
* Technology: **devops-ecosystem**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Thanks very much for your feedback, @Liran-Dobrish. I'll look into this and will be in touch.

**Comment by chcomley** [comment]
Hi @Liran-Dobrish, Here are a few examples, thanks for your patience. Please let me know if you have any further questions. Thanks!
[Samples overview](https://docs.microsoft.com/en-us/azure/devops/extend/develop/samples-overview?toc=%2Fazure%2Fdevops%2Fextend%2Ftoc.json&bc=%2Fazure%2Fdevops%2Fextend%2Fbreadcrumb%2Ftoc.json&view=azure-devops)
[Extend the work item form](https://docs.microsoft.com/en-us/azure/devops/extend/develop/add-workitem-extension?view=azure-devops)

**Comment by Liran-Dobrish** [comment]
none of these links contains information of using the new Devops npm
packages (api, sdk, ui)
