### ISSUE TITLE
Updates?

### ISSUE THREAD

**Issue by nezoic** [MicrosoftDocs/vsts-docs#490]
Can we get some updated examples of this? Things do not match up exactly here. For example I do not see a "General" section anywhere. I assume it doesn't matter any more because I can use the MacOs hosting environment? I'm not sure though.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b39d73b6-f973-3757-0932-9b06d4ebc3ef
* Version Independent ID: 5be404ed-e1e4-5a96-5c08-298b18474a58
* Content: [The Cordova/Ionic/PhoneGap Command Tasks](https://docs.microsoft.com/en-us/vsts/build-release/archive/apps/mobile/cordova-command?view=vsts)
* Content Source: [docs/build-release/archive/apps/mobile/cordova-command.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/build-release/archive/apps/mobile/cordova-command.md)
* Service: **unspecified**
* GitHub Login: @erickson-doug
* Microsoft Alias: **alewis**

**Comment by andyjlewis** [comment]
Thanks for this feedback. I've copied this request to our backlog.
