### ISSUE TITLE
Edit multiple cases at one go.

### ISSUE THREAD

**Issue by Ahetejaz** [MicrosoftDocs/vsts-docs#4901]
Are we planning to bring ability to assign multiple test cases at one go like we have in previous view. Select multiple case, do a right click and edit multiple cases. Assign multiple cases at a time to individuals?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3c520dee-1218-777e-7405-551623817c03
* Version Independent ID: 82b5d172-ae1a-2b4c-82ac-595cd7609d3c
* Content: [New test plans page - Azure Test Plans](https://docs.microsoft.com/en-us/azure/devops/test/new-test-plans-page?view=azure-devops#feedback)
* Content Source: [docs/test/new-test-plans-page.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/test/new-test-plans-page.md)
* Product: **devops**
* Technology: **devops-test**
* GitHub Login: @harishkragarwal
* Microsoft Alias: **harishkragarwal**

**Comment by harishkragarwal** [comment]
Yes, we will @Ahetejaz. It should roll out with upcoming sprints payload.

**Comment by gfarnsworth** [comment]
Hi, has this been implemented? I still cannot edit multiple test cases at the same time like I used to.

**Comment by harishkragarwal** [comment]
It is yet to be implemented. However, its planned to be added to the new test plans page.

**Comment by Ahetejaz** [comment]
> Hi, has this been implemented? I still cannot edit multiple test cases at the same time like I used to.

To continue with your work for time being you may disable the new test plan feature from you profile, preview feature and edit multiple test cases at once. Then you may switch back to the new preview page 'Test plans*'.
