### ISSUE TITLE
Typo: "test suits" used in place of "test suites"

### ISSUE THREAD

**Issue by jaspecla** [MicrosoftDocs/vsts-docs#4902]
Near the end of the following section: 

https://docs.microsoft.com/en-us/azure/devops/test/create-a-test-plan?view=azure-devops#what-are-test-plans-test-suites-and-test-cases

In the callout:

For more details of the ways you can work with test plans, test suits, and test cases, see the FAQs for manual testing.

The phrase "test suits" is used, when "test suites" was intended.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c8e2cb79-709d-972b-6747-6d26c965fb2a
* Version Independent ID: d512ea69-a97a-e5ff-a804-6691c5dfe1e6
* Content: [Create test plans and suites - Azure Test Plans](https://docs.microsoft.com/en-us/azure/devops/test/create-a-test-plan?view=azure-devops)
* Content Source: [docs/test/create-a-test-plan.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/test/create-a-test-plan.md)
* Product: **devops**
* Technology: **devops-test**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by WilliamAntonRohm** [comment]
Documentation update is in https://dev.azure.com/mseng/TechnicalContent/_git/vsts-docs-pr/pullrequest/491359

**Comment by WilliamAntonRohm** [comment]
@jaspecla -- Jason, thank you for your feedback.  I have updated the documentation and it should be live by tomorrow.
