### ISSUE TITLE
BitBucket PR Path Triggers Completely Broken

### ISSUE THREAD

**Issue by ArchSerpo** [MicrosoftDocs/vsts-docs#4904]
I recently noticed that the BitBucket now seemed to support PR path triggers within the YAML file, so I undid my manual setup via the UI for most of my builds (some require the use of a customer variable, so those are still explicitly set)
I posted about that here - https://github.com/microsoft/azure-pipelines-yaml/issues/216
Now from yesterday morning, I noticed that it was no longer recognizing the YAML paths and kicking off a build for all of my definitions. Now upon closer look today, the ones with the explicit configuration in the UI are still kicking off when they should not be.
Are there any known issues with this integration?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5673ec1-c7d1-e0ac-043a-8fc3d5b226a9
* Version Independent ID: b4872831-51c0-6cf8-1c56-de20beb38a80
* Content: [Build pipeline triggers - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/triggers?tabs=yaml&view=azure-devops#pr-triggers)
* Content Source: [docs/pipelines/build/triggers.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/build/triggers.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by brcrista** [comment]
Tracked here: https://developercommunity.visualstudio.com/content/problem/653939/azure-pipelines-bitbucket-path-triggers-not-workin.html

**Comment by steved0x** [comment]
Closing since this issue is being tracked at Developer Communities
