### ISSUE TITLE
Documentation fixes

### ISSUE THREAD

**Issue by lbrownell-gpsw** [MicrosoftDocs/vsts-docs#4905]
Argument entry "Environment variables" (e.g., env:) is not shown in the yaml sample; it is shown in the shortcut example.  This is a case (see below) where the key name doesn't not match the Arguments entry name.

Keys "noProfile" and "noRc" are not described in Arguments.

General comment:  On all these pages, make the entry titles in the Arguments section be identical to the keys they describe.  Changing the casing and adding spaces is fine, but completely different wording is confusing for no benefit. We have the following in this page:

Key: targetType;  Argument: Type
Key: failOnStderr;  Argument: Fail on standard error  (OK, close enough, expanding a term of art to full text is cool)

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 450ac349-5c33-6cdf-1ecd-6eb989a00334
* Version Independent ID: a7119c1a-59b2-3081-a241-e93aa0d6b4b9
* Content: [Bash task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/bash?view=azure-devops)
* Content Source: [docs/pipelines/tasks/utility/bash.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/utility/bash.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @vtbassmatt
* Microsoft Alias: **macoope**

**Comment by vtbassmatt** [comment]
`env` is a standard part of a task step, it's not an input, hence why it's not documented there. (The feedback is good - it's just broader than this task and thus I don't plan to fix it as part of _this_ bugfix.)

The "arguments" section documents the titles as shown in the designer. We could do a better job on the product side making those consistent with the YAML titles.

I will add notes about `noProfile` and `noRc`.
