### ISSUE TITLE
Update docs for PublishPipelineArtifact@1

### ISSUE THREAD

**Issue by mikeharder** [MicrosoftDocs/vsts-docs#4908]
This page should be updated with documentation for the new task `PublishPipelineArtifact@1`.  Note the primary name of the parameter changed from `targetPath` to `path`, though `targetPath` is still a valid alias:

https://github.com/microsoft/azure-pipelines-tasks/blob/0b39a29c5640aada5534b937fff3416887bbc3ee/Tasks/PublishPipelineArtifactV1/task.json#L21-L24

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 41baa0b5-175c-a697-4b7d-c150259c6e6b
* Version Independent ID: 75085b15-1acc-526a-0495-74a13c42c1d5
* Content: [Publish Pipeline Artifacts task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/publish-pipeline-artifact?view=azure-devops)
* Content Source: [docs/pipelines/tasks/utility/publish-pipeline-artifact.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/utility/publish-pipeline-artifact.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @willsmythe
* Microsoft Alias: **wismyth**

**Comment by willsmythe** [comment]
Thanks for reporting. @chasewilson - can you sync this up with the V1 task in microsoft/azure-pipeline-tasks?

**Comment by chasewilson** [comment]
@mikeharder Thanks for the feedback! Docs are updated and will be released shortly! Closing the issue, but if you have any more feedback, feel free to create  a new issue :)

**Comment by akoeplinger** [comment]
Looks like this wasn't fixed, the page at https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/publish-pipeline-artifact?view=azure-devops still mentions `targetPath` instead of `path`
