### ISSUE TITLE
PAT token

### ISSUE THREAD

**Issue by julianparismorgan** [MicrosoftDocs/vsts-docs#491]
Under Publish your extension -> Upload your extension: "You'll need a personal access token, too."

Is this a PAT token generated in VSTS? Or some PAT token you have to generate to verify you're the publisher?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 14955ee9-29f2-46fe-3a8d-a42666f53ffc
* Version Independent ID: 5d417cd0-a671-ee30-8fca-5f8b0addd328
* Content: [Write your first extension for VSTS](https://docs.microsoft.com/en-us/vsts/extend/get-started/node?view=vsts)
* Content Source: [docs/extend/get-started/node.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/extend/get-started/node.md)
* Service: **unspecified**
* GitHub Login: @erickson-doug
* Microsoft Alias: **elbatk**

**Comment by steved0x** [comment]
@julianparismorgan A Personal Access Token (PAT) is something you generate in VSTS to identify and authenticate yourself when working with VSTS. For more information, see [Authenticate access with personal access tokens for VSTS and TFS](https://docs.microsoft.com/en-us/vsts/accounts/use-personal-access-tokens-to-authenticate?view=vsts#create-personal-access-tokens-to-authenticate-access)

**Comment by julianparismorgan** [comment]
Thanks Steve. I had scoped it just to my account, not all accessible accounts. That might be a note worth adding?
