### ISSUE TITLE
Clean does not work for deployment

### ISSUE THREAD

**Issue by michaelw85** [MicrosoftDocs/vsts-docs#4914]
Unexpected value 'workspace'"

I'm running into a situation where artifacts of a different pipeline remain in the Pipeline Workspace. I would like to clean the workspace and expected the options for the deployment job to be equal to the documentation of regular job.
```yml
workspace:
    clean: outputs | resources | all # what to clean up before the job runs
```

Could this documentation be updated with a list of options that are available for a deployment job or could a list of unsupported options be added?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5aeeaace-1c5b-a51b-e41f-f25b806155b8
* Version Independent ID: fd7ff690-b2e4-41c7-a342-e528b911c6e1
* Content: [Deployment jobs - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/deployment-jobs?view=azure-devops#feedback)
* Content Source: [docs/pipelines/process/deployment-jobs.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/deployment-jobs.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @shashankbarsin
* Microsoft Alias: **shasb**

**Comment by RoopeshNair** [comment]
Workspace attribute is not supported in deployment jobs. As you can see the schema section is documented with list of options supported in deployment job. It is also documented in YAML Schema docs: [Deployment Job](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema#deployment-job)

We are rethinking how workspace option is currently supported and want to close on it before we can introduce it in deployment job. Currently we are working on issues that are impacting broader set of customers. We are tracking this and will revisit at a later point in time (no time lines).
