### ISSUE TITLE
Limited size of inline scripts?

### ISSUE THREAD

**Issue by canoas** [MicrosoftDocs/vsts-docs#492]
inline scripts are limited in size to aprox 500 chars, right?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a0e444c2-69c6-4d71-6fd0-94d0f4097d3a
* Version Independent ID: 3a727833-1cc3-c2fb-c5b3-22605eee2721
* Content: [PowerShell](https://docs.microsoft.com/en-us/vsts/build-release/tasks/utility/powershell?view=vsts#qa)
* Content Source: [docs/build-release/tasks/utility/powershell.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/build-release/tasks/utility/powershell.md)
* Service: **unspecified**
* GitHub Login: @erickson-doug
* Microsoft Alias: **alewis**

**Comment by vijayma** [comment]
The 2.x version of Powershell task has a much larger limit on characters.

**Comment by andyjlewis** [comment]
Added this to the backlog.
