### ISSUE TITLE
missing entire "dependencies" group of predefined variables

### ISSUE THREAD

**Issue by diablodale** [MicrosoftDocs/vsts-docs#4921]
Missing the entire "dependencies" group of predefined variables. For example to get a var value from another job's output var you would access: dependencies.jobName.outputs['stepName.varname']
See https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch#set-in-script for them being used
...yet what are all the vars in the dependencies tree?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ffebdc8-521c-44b5-cde4-4abdc1bd6f18
* Version Independent ID: dc0effda-6d93-62aa-64c5-4e6f283b0826
* Content: [Predefined variables - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml#feedback)
* Content Source: [docs/pipelines/build/variables.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/build/variables.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by Advin24** [comment]
@diablodale - if it helps - the object structure for dependencies is briefly mentioned [here](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/expressions?view=azure-devops#dependencies).

**Comment by diablodale** [comment]
Hello. What was the action on this so I can verify the close?
