### ISSUE TITLE
New URL not listed for sign in

### ISSUE THREAD

**Issue by anmason** [MicrosoftDocs/vsts-docs#4923]
Currently, this doc lists vssps.visualstudio.com, but for organizations that have switched to the new dev.azure.com URLs, the URL is vssps.dev.azure.com

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e191f4bf-deef-1c48-aaa7-db424c322ae3
* Version Independent ID: 866d576f-77e4-1fc4-d4db-484628e0b518
* Content: [Troubleshoot network connections and lists of allowed addresses](https://docs.microsoft.com/en-us/azure/devops/organizations/security/faq-network-connections?view=azure-devops#list-of-urls-for-sign-in-and-licensing-connections)
* Content Source: [docs/organizations/security/faq-network-connections.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/security/faq-network-connections.md)
* Product: **devops**
* Technology: **devops-security**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by WilliamAntonRohm** [comment]
The documentation is updated in https://dev.azure.com/mseng/TechnicalContent/_git/vsts-docs-pr/pullrequest/491365

**Comment by WilliamAntonRohm** [comment]
@anmason -- thank you for your feedback.  I have updated the documentation and it should be live by tomorrow.
