### ISSUE TITLE
Does group rule take precedence over direct assignment if it assigns a higher license level. 

### ISSUE THREAD

**Issue by Chintunie** [MicrosoftDocs/vsts-docs#4929]
If a group rule assigns a higher license level, does it take precedence over direct assignment.

For example, if the user is added as a stakeholder directly in the organisation and later added to a group which assigns a Basic license, will the group rule take precedence since it assigns a higher licence?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e68cbc09-7665-c8cf-e422-4f83f9a56cc7
* Version Independent ID: 767f63c4-bfde-7a48-08f2-3beb1437abd1
* Content: [Remove direct assignments from users - Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/remove-direct-assignments?view=azure-devops#feedback)
* Content Source: [docs/organizations/accounts/remove-direct-assignments.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/accounts/remove-direct-assignments.md)
* Product: **devops**
* Technology: **devops-accounts**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @Chintunie, Thanks for reaching out. I'm confirming with the PM and will get back to you shortly. Thanks again!
