### ISSUE TITLE
Documentation wont stay on a specific version

### ISSUE THREAD

**Issue by StingyJack** [MicrosoftDocs/vsts-docs#493]
I can choose TFS 2015 from the DDL on the left, but as I navigate into the rest api reference it starts showing API v4 stuff.  I dont need to see what I could have if I upgraded, I need to see what I have in the version I have now. 

Also, I cant change that dropdown list once I navigate from this page. It needs to be available on every page in this library, especially because I cant navigate back to this page from the REST API reference

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4abeff84-74e7-7fd3-db28-fa92683143c8
* Version Independent ID: 9d289096-4cf9-cb30-0893-e9ae5a72a34d
* Content: [REST API samples for VSTS and Team Foundation Server](https://docs.microsoft.com/en-us/vsts/integrate/get-started/rest/samples?view=vsts)
* Content Source: [docs/integrate/get-started/rest/samples.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/integrate/get-started/rest/samples.md)
* Service: **unspecified**
* GitHub Login: @erickson-doug
* Microsoft Alias: **elbatk**

**Comment by steved0x** [comment]
@StingyJack Just as a quick sanity check, you are talking about when you drill down into [here](https://docs.microsoft.com/en-us/rest/api/vsts/?view=vsts), you lose the VSTS/TFS versions witcher and it always defaults to 4.1, correct?

**Comment by StingyJack** [comment]
Yes. That is where I lose the switcher

**Comment by steved0x** [comment]
@StingyJack - they are still working on that. I am going to go ahead and close this issue, but if it isn't resolved within a few months, please feel free to open a new issue and tell us to speed up :) It should be resolved shortly though. Thank you.

**Comment by StingyJack** [comment]
@steved0x  - why not leave this one open as a reminder for you, instead of pushing of the burden of memory to me?

**Comment by fbau3r** [comment]
I have the same issue, and at the moment I'm afraid to say that it's guesswork to use TFS2017 API.

1. Is there a reference to the issue "_they are still working on_"?
2. Is there a workaround to access the documentation of the other Versions meanwhile? (e.g. a source repository that's not yet included, a branch or so)

I also would like to see this Issue open for as long as the bug is not fixed without a reference to another bug.

**Comment by StingyJack** [comment]
@fbau3r - See if this link is useful for you

https://docs.microsoft.com/en-us/vsts/integrate/legacy-apis/overview?view=tfs-2017

It seems to be correct for the TFS 2015  set.

**Comment by steved0x** [comment]
I'll keep it open until I can verify the work item that this work is assigned to.

**Comment by steved0x** [comment]
@elbatk Do you have any better information to provide here than what I have been providing, like better timelines for when this may be resolved?

**Comment by elbatk** [comment]
We just added those legacy apis that were linked by @StingyJack for just these scenarios. They should be fine with that. Going to close this and we can reopen if there are more questions.

**Comment by fbau3r** [comment]
Thank you all for helping me with that issue! The link was exactly what I need, @StingyJack.
