### ISSUE TITLE
Refresh token expiry.

### ISSUE THREAD

**Issue by karanwagare123** [MicrosoftDocs/vsts-docs#4932]
what is a expiry for refresh token generated from Azure DevOps. OAuth.

**Comment by WilliamAntonRohm** [comment]
@karanwagare123  Thanks for your feedback; we appreciate it. To make sure we have all the information needed to triage your issue, please let us know which topic you’re referencing, or provide more context around the general task.

**Comment by WilliamAntonRohm** [comment]
I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
