### ISSUE TITLE
Deploy using azure hosted agent pools

### ISSUE THREAD

**Issue by marsilbenavides** [MicrosoftDocs/vsts-docs#4939]
Is there any way to deploy (publish to an azure feed) using hosted agent pools?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 60230978-ce5b-6964-23ba-1dd31b1fa1c9
* Version Independent ID: 9b1eb982-b07a-8b67-ab0b-b2a4d3dade12
* Content: [Use Maven artifact feeds - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/maven?view=azure-devops#feedback)
* Content Source: [docs/pipelines/artifacts/maven.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/artifacts/maven.md)
* Product: **devops**
* Technology: **devops-artifacts**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk, yebronsh**

**Comment by elbatk** [comment]
Hi @marsilbenavides , did ya find what you were looking for here?

**Comment by marsilbenavides** [comment]
Yes! Thanks. I am using the graphical pipeline... so I had to add two tasks to the pipeline,
1. Download secure file to copy the settings.xml (named settings) from the secure library
2. Create a bash with the following,
     mkdir -p ~/.m2
     echo Installing $(settings.secureFilePath) to the trusted ~/.m2 directory...
     mv $(settings.secureFilePath) ~/.m2/
