### ISSUE TITLE
This documentation does not describe the actual process to enable the live updates

### ISSUE THREAD

**Issue by robertbissonnette** [MicrosoftDocs/vsts-docs#494]
Please include some pictures / steps to enable this feature

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 51fd58ec-ec6e-60ef-addd-1c1c370ccd79
* Version Independent ID: d8945f72-1255-e1d2-45d4-eae93705e448
* Content: [Enable live updates](https://docs.microsoft.com/en-us/vsts/work/_shared/live-updates?view=vsts)
* Content Source: [docs/work/_shared/live-updates.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/work/_shared/live-updates.md)
* Service: **unspecified**
* GitHub Login: @erickson-doug
* Microsoft Alias: **douge**

**Comment by KathrynEE** [comment]
@robertbissonnette - I apologize for the confusion. The referenced content isn't a complete article (it shouldn't be indexed by search engines and I will raise this issue with our content engineering team). Please reference this article - https://docs.microsoft.com/en-us/vsts/collaborate/preview-features?view=vsts - for details on enabling preview features.
