### ISSUE TITLE
Closed By field is copied when copying a work item

### ISSUE THREAD

**Issue by pabrams** [MicrosoftDocs/vsts-docs#4940]
[This document](https://docs.microsoft.com/en-us/azure/devops/boards/backlogs/copy-clone-work-items?view=tfs-2017&tabs=browser#copy-or-clone-a-work-item) says that no history is copied over, but we noticed that the "Closed by" field is copied from a Closed work item (TFS 2017, Update 3). Is that part of the History? Is this a bug in the docs, or a bug in TFS?

This is like #4200, but it looks like I had the wrong link in that one - this time I made sure to grab the link specific to TFS 2017.

**Comment by KathrynEE** [comment]
@pabrams - Thank you for your inquiry. I received this reply from our engineer on this feature: 

It all depends on the customer’s process. If they have no state transition rule on their work item type that says to clear “ClosedBy” field when State is “New” or “Active”, it will get copied over. Our OOB templates have this rule so we wont be able to repro this issue with our OOB processes, but customers can define their process any way they want. We should ask the customer to give us their process (atleast for their particular affected work item type) so we can look at it.
I see a similar DTS from 3 months ago which explains the detailed reason in the discussion. To not have similar issues in future, we made a change in our copy logic to not copy some hardcoded field and ClosedBy is one such field, but this change is not in TFS 2017. 

I will update the topic to clarify the behind-the-scenes actions and the versions they apply to.
