### ISSUE TITLE
Build as an alias for primary artifact seems wrong

### ISSUE THREAD

**Issue by bluebirdtech** [MicrosoftDocs/vsts-docs#4944]
E.g. Build.BuildNumber - it's nothing to do with a build here, just artifact.  (The artifact may have come from a build, or may not)

Artifact.Version would seem like a nicer variable name.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 611642f0-881f-10b9-ae94-3c562001d1f0
* Version Independent ID: 41efb94b-4c7a-64a3-b23b-70c8634ae727
* Content: [Release variables and debugging - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/variables?view=azure-devops&tabs=batch#feedback)
* Content Source: [docs/pipelines/release/variables.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/release/variables.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by ashokirla** [comment]
Thanks for the feedback. Due to the nature of artifacts being of types build, repo, package and container we cannot have a standard variable format that works for all. We are working on documentation to make it clear about what variables are valid for each of the first class artifact sources.

**Comment by WilliamAntonRohm** [comment]
@bluebirdtech, thank you for your feedback, and @ashokirla for your response.

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
