### ISSUE TITLE
General artifact variables section is missing Azure Artifacts

### ISSUE THREAD

**Issue by bluebirdtech** [MicrosoftDocs/vsts-docs#4945]
It lists what the variables are set to in lots of other contexts, e.g. GitHub, Jenkins, but not from Azure Artifacts.

I guessed that Build.BuildNumber would be was going to be the package version, and it is.  My first guess was SourceVersion which was incorrect though.

See related point below, though that might be more of a product suggestion.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 611642f0-881f-10b9-ae94-3c562001d1f0
* Version Independent ID: 41efb94b-4c7a-64a3-b23b-70c8634ae727
* Content: [Release variables and debugging - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/variables?view=azure-devops&tabs=batch#feedback)
* Content Source: [docs/pipelines/release/variables.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/release/variables.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by ashokirla** [comment]
SourceVersion variable is applicable only for build or repo type artifacts where it points to the repository commit.

**Comment by WilliamAntonRohm** [comment]
@bluebirdtech, thank you for your feedback, and @ashokirla for your response.

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
