### ISSUE TITLE
Authorize Resources Failing

### ISSUE THREAD

**Issue by gluaxspeed** [MicrosoftDocs/vsts-docs#4948]
When clicking Authorize Resources an error message pops up.

An error occurred while auto-authorizing resources.

This doesn't really tell me anything about how I should fix this problem

**Comment by WilliamAntonRohm** [comment]
@gluaxspeed Thanks for your feedback; we appreciate it. To make sure we have all the information needed to triage your issue, please let us know which topic you’re referencing, or provide more context around the general task.

**Comment by WilliamAntonRohm** [comment]
I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
