### ISSUE TITLE
Callback endpoint

### ISSUE THREAD

**Issue by hbuckle** [MicrosoftDocs/vsts-docs#4949]
Is there any more documentation on the distributedtask/hubs endpoint used for the callbacks?
* Permissions required to call it?
* Can we do validation on the completion data?
* Is the user that made the call logged anywhere?

I want to ensure that only my Azure function can continue the pipeline, but from testing it seems that any user can call the endpoint and continue the pipeline.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 788ade26-087e-737f-21fd-5cc9f36666a5
* Version Independent ID: 78733f37-e78e-e044-e2e9-5e67a2eae374
* Content: [Invoke Azure Function task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/azure-function?view=azure-devops)
* Content Source: [docs/pipelines/tasks/utility/azure-function.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/utility/azure-function.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by RoopeshNair** [comment]
@shashban - can you please take a look?

**Comment by jwisener** [comment]
I guess @shashban doesn't care. I agree, is there no better documentation on this?

**Comment by shashban** [comment]
The call back API is documented at https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/azure-function?view=azure-devops#where-should-a-task-signal-completion-when-callback-is-chosen-as-the-completion-event

The URL is specific to each job in the release and guarded by the same authentication as other Azure DevOps APIs.

**Comment by hbuckle** [comment]
@shashban  - that doesn't quite answer the question - when I say permissions required to call it I mean permissions within Azure DevOps.

I also asked

Can we do validation on the completion data?
Is the user that made the call logged anywhere?
