### ISSUE TITLE
CodePlex support should be removed

### ISSUE THREAD

**Issue by christiannagel** [MicrosoftDocs/vsts-docs#4955]
The CodePlex support on this page should be removed. CodePlex is no longer active.

Bottom of the page, in the section **Integration and migration**.

Christian

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a1dc9a4a-7828-f40f-4cf0-e0b1f5476ff2
* Version Independent ID: 278aed60-558e-3beb-2ed4-c2517c2cd05d
* Content: [Git and TFVC version control - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/tfvc/comparison-git-tfvc?view=azure-devops)
* Content Source: [docs/repos/tfvc/comparison-git-tfvc.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/repos/tfvc/comparison-git-tfvc.md)
* Product: **devops**
* Technology: **devops-code-tfvc**
* GitHub Login: @apawast
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
I'll get this updated.
