### ISSUE TITLE
Error in Description of filters of Contents argument

### ISSUE THREAD

**Issue by DrPepperBianco** [MicrosoftDocs/vsts-docs#4956]
It says that "" (empty string) would be copy all files and "*" (single asterisk) is copy all files recursively. But if I remember correctly, it shoudl be "*" (single asterisk) for copying all files and "**" (double asterisk) for copying all files recursively!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 81f02378-b85b-d3a4-d3c8-f07d935367da
* Version Independent ID: fab57f76-35d2-4024-6f7f-1740d7b24743
* Content: [Copy Files task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/copy-files?view=azure-devops&tabs=yaml#feedback)
* Content Source: [docs/pipelines/tasks/utility/copy-files.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/utility/copy-files.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @vtbassmatt
* Microsoft Alias: **macoope**

**Comment by vtbassmatt** [comment]
Good catch, thanks. From looking at the HTML tag soup, I suspect we did some kind of automated copy from another content system and this got mangled. I'll fix it.
