### ISSUE TITLE
Repeated words

### ISSUE THREAD

**Issue by waqasm** [MicrosoftDocs/vsts-docs#4957]
There is repeated "it was" in the doc:
https://docs.microsoft.com/en-us/azure/devops/learn/devops-at-microsoft/progressive-experimentation-feature-flags

Currently it says:

"But in the case of something like the revert feature I used as an example here, it was it was great to be able to have that behind a feature flag"

**Comment by WilliamAntonRohm** [comment]
@waqasm -- Waqas, thank you for the feedback.  I have updated the documentation and it should be live by tomorrow.

**Comment by waqasm** [comment]
Thanks @WilliamAntonRohm
