### ISSUE TITLE
install link, links to preview app

### ISSUE THREAD

**Issue by timker** [MicrosoftDocs/vsts-docs#4958]
"To install the Azure Boards app to your Slack workspace, open a web browser, sign into Slack, and open the Azure Boards app."

this links to
Azure Boards PF

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b54bed72-4266-7c72-ef20-d48968dcaddd
* Version Independent ID: a7109901-c230-b420-88b6-b3000faf002e
* Content: [Azure Boards with Slack - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/integrations/boards-slack?view=azure-devops)
* Content Source: [docs/boards/integrations/boards-slack.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/boards/integrations/boards-slack.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @RGKarthik
* Microsoft Alias: **kaelli**

**Comment by RGKarthik** [comment]
@timker ,
Thank you for the observation. The link has been updated.
