### ISSUE TITLE
Typo on page - missing "to" in following text

### ISSUE THREAD

**Issue by chrisfothers** [MicrosoftDocs/vsts-docs#4959]
"Epics declare initiatives important the organizations success."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f4bc244f-e07c-f8a4-0f00-04c8e015821f
* Version Independent ID: 2a37fdcf-eac8-3738-af46-7d70826ec660
* Content: [Scale Agile to Large Teams - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/learn/agile/scale-agile-large-teams#feedback)
* Content Source: [https://mseng.visualstudio.com/DefaultCollection/TechnicalContent/_git/devops-learn-pr?path=%2fdocs%2fagile%2fscale-agile-large-teams.md&version=GBlive&_a=contents](https://mseng.visualstudio.com/DefaultCollection/TechnicalContent/_git/devops-learn-pr?path=%2fdocs%2fagile%2fscale-agile-large-teams.md&version=GBlive&_a=contents)
* Product: **devops**
* Technology: **devops-learn**
* Git Login: **samgu**
* Microsoft Alias: **samgu**

**Comment by WilliamAntonRohm** [comment]
@chrisfothers -- Chris, thank you for your feedback.  I have updated the documentation and it should be live by tomorrow.
