### ISSUE TITLE
Troubleshoot - old url or project name with spaces can be problem to signin

### ISSUE THREAD

**Issue by rodrigokono** [MicrosoftDocs/vsts-docs#4961]
Ex: `https://myorg.visualstudio.com/My Project Test/` is not a valid command
old url is visualstudio.com
Project Name with spaces: "My Project Test"

Error message: `https://myorg.visualstudio.com/My Project Test/` is not a valid command. Type `/azboards help` to see what you can do.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b54bed72-4266-7c72-ef20-d48968dcaddd
* Version Independent ID: a7109901-c230-b420-88b6-b3000faf002e
* Content: [Azure Boards with Slack - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/integrations/boards-slack?view=azure-devops#feedback)
* Content Source: [docs/boards/integrations/boards-slack.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/boards/integrations/boards-slack.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @RGKarthik
* Microsoft Alias: **kaelli**

**Comment by RGKarthik** [comment]
@rodrigokono 
Thanks a lot for your observation. The link has been fixed.

**Comment by RGKarthik** [comment]
@rodrigokono ,

Did you copy the URL from the browser or are you manually typing it? If it is the latter, can you please replace a space with %20 and try?

**Comment by rodrigokono** [comment]
Yeah. I did both and didn't have success.

**Comment by RGKarthik** [comment]
@rodrigokono ,
Can you please mail us at AzureDevOpsSlackApps@microsoft.com. Will need some more info to understand this.

**Comment by RGKarthik** [comment]
#please-close
