### ISSUE TITLE
Can I not paste the tasks into a PBI? 

### ISSUE THREAD

**Issue by jeffhandygeek** [MicrosoftDocs/vsts-docs#4963]
I'm not sure why else anyone would need to copy a list of tasks unless you're getting them into another PBI or story. Are agile developers working on this product? It seems counterintuitive that I can't copy multiple tasks or at least have a modifier key for copied items. Example, if I hold down my alt key while dragging multiple items, it should duplicate them into the new story/pbi.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 298ba56f-bad5-4fe6-ac55-fb8f09297322
* Version Independent ID: 887e79fd-280c-2780-7165-c8c1757146e0
* Content: [Copy a list of user stories, issues, bugs, tasks, or other work items - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/backlogs/copy-list?view=azure-devops#feedback)
* Content Source: [docs/boards/backlogs/copy-list.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/boards/backlogs/copy-list.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by WilliamAntonRohm** [comment]
It looks like you've encountered an issue with the product itself, rather than an issue with the documentation. To make sure it gets in front of the right people, please [submit your bug]( https://developercommunity.visualstudio.com/content/problem/post.html?space=21) here.
