### ISSUE TITLE
Why is the Work Items page is currently available from Azure DevOps Services etc? Will it come back?

### ISSUE THREAD

**Issue by dbruning** [MicrosoftDocs/vsts-docs#4966]
It's great that I can create a work item from a failure in Azure DevOps. However, if I come back in future to the transaction that caused the failure, I can't see the work item that I previously created from it. So I can't jump to it & see if it's resolved yet. This makes "Add work item" nearly useless.

It looks like you *used to* be able to see the work item from here in the past:
https://azure.microsoft.com/en-us/blog/application-insights-work-item-integration-with-visual-studio-team-services/
Is this feature going to come back?

**Comment by WilliamAntonRohm** [comment]
It looks like you've encountered an issue with the product itself, rather than an issue with the documentation. To make sure it gets in front of the right people, please [submit your bug]( https://developercommunity.visualstudio.com/content/problem/post.html?space=21) here.
