### ISSUE TITLE
Source code is only checked out in first stage - best practice on how to reference script from source control in later stage?

### ISSUE THREAD

**Issue by hansmbakker** [MicrosoftDocs/vsts-docs#4970]
I don't see the following usecase documented:

- I have a multi-stage yaml pipeline.
- only the first stage seems to do a checkout from source control &lt;--- can't find this documented
- in later stages I use az cli / powershell steps which I want to have in source control instead of as inline script (to make it reusable).
- these scripts cannot be read directly from the source checkout since later stages do not seem to checkout &lt;-- not documented what the best practice is for this?

Workarounds I can imagine are:
- use a yaml template and put inline script in there
- create a build artifact in the first stage to pass on the script required to run in later stages and use the build artifact in the later stages (ugly)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4266f72c-c774-0046-4593-d01eb775d3c3
* Version Independent ID: f20827aa-a6c5-96a8-5969-e576ffbc2e38
* Content: [Stages in Azure Pipelines - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/stages?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/process/stages.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/stages.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @vijayma
* Microsoft Alias: **vijayma**

**Comment by hansmbakker** [comment]
I see now in https://docs.microsoft.com/en-us/azure/devops/pipelines/process/phases?view=azure-devops&tabs=yaml#specifying-jobs that you can specify `checkout` as a step, but I cannot find the documentation for that.

**Comment by vijayma** [comment]
Glad you were able to find the checkout step. We will see where else we can include that in the docs.
