### ISSUE TITLE
Missing word on the page

### ISSUE THREAD

**Issue by LarryRothOakton** [MicrosoftDocs/vsts-docs#4973]
What is Continuous Delivery section seems to be missing a word after "a new":
"Multiple testing or staging environments create a Release Pipeline to automate the creation of infrastructure and deployment of a new. "

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 895ed016-6ddc-3458-db9e-ebbedf218982
* Version Independent ID: 36e017f5-b012-fcec-6906-1966f3a97cb4
* Content: [What is Continuous Delivery? - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/learn/what-is-continuous-delivery#feedback)
* Content Source: [https://mseng.visualstudio.com/DefaultCollection/TechnicalContent/_git/devops-learn-pr?path=%2fdocs%2fwhat-is-continuous-delivery.md&version=GBlive&_a=contents](https://mseng.visualstudio.com/DefaultCollection/TechnicalContent/_git/devops-learn-pr?path=%2fdocs%2fwhat-is-continuous-delivery.md&version=GBlive&_a=contents)
* Product: **devops**
* Technology: **devops-learn**
* Git Login: **samgu**
* Microsoft Alias: **samgu**

**Comment by msebolt** [comment]
@LarryRothOakton Thank you for the feedback.

The documentation has been fixed per change above.
