### ISSUE TITLE
What does 'Container' means in publishLocation?

### ISSUE THREAD

**Issue by qyxxxigd** [MicrosoftDocs/vsts-docs#4975]
I'm really confused about the 'Container' in 'publishLocation'. Is it a docker container or a storage container or something else? Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b3f565b-88e4-88d6-a534-48ec21e6e3d8
* Version Independent ID: 9fca89ae-4a6e-a43a-2834-1a91ad44c256
* Content: [Publish Build Artifacts task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/publish-build-artifacts?view=azure-devops#feedback)
* Content Source: [docs/pipelines/tasks/utility/publish-build-artifacts.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/utility/publish-build-artifacts.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @DavidStaheli
* Microsoft Alias: **dastahel**

**Comment by pemj** [comment]
Belated, but, there's another issue in the docs about this, so we might want to close this as a duplicate, make sure we've indicated that the other one is still unresolved:
https://github.com/MicrosoftDocs/vsts-docs/issues/3020

**Comment by chasewilson** [comment]
@qyxxxigd Thanks for the feedback and @pemj is right. I'll close this issue and issue will be updated on the other issue. @pemj thanks for the answer here and your patience on the other issue. I'll work on getting the other issue closed out ASAP
