### ISSUE TITLE
Should update the instructions for downloading extensions

### ISSUE THREAD

**Issue by Scott-Gall** [MicrosoftDocs/vsts-docs#4977]
should search for "Azure Repos" nore "Azure DevOps Services"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e818c26d-b8fd-e532-95af-7f5654acf7e2
* Version Independent ID: d837a5c4-4634-dac2-79e8-c5aa15deaaed
* Content: [VS Code extension for Java development with Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/java/vscode-extension?view=azure-devops#feedback)
* Content Source: [docs/java/vscode-extension.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/java/vscode-extension.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @DavidStaheli
* Microsoft Alias: **dastahel**

**Comment by msebolt** [comment]
@Scott-Gall Thank you for the feedback.

Your requested change has been submitted for review.
