### ISSUE TITLE
How to edit the Description of Secure file?

### ISSUE THREAD

**Issue by BrightRan** [MicrosoftDocs/vsts-docs#4982]
We can see there is a Description column in the Library &gt; Secure files page. But when open a Secure file, there have no the textbox for Description that allow us to edit the Description.
Just like Variable groups, when open a Variable group, we can see the textbox for Description and can edit the Description, the the Description will display in the Description column.
If it is designed that no have Description for Secure files, why let the Description column to display on the page?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 140dcb9a-2ed0-11d5-064b-068f863ed97f
* Version Independent ID: 672d2aa3-cf0d-9207-c97c-e2eba14506b7
* Content: [Secure files for Azure Pipelines and Team Foundation Server - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/library/secure-files?view=azure-devops)
* Content Source: [docs/pipelines/library/secure-files.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/library/secure-files.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @thomps23
* Microsoft Alias: **madhurig**

**Comment by WilliamAntonRohm** [comment]
It looks like you've encountered an issue with the product itself, rather than an issue with the documentation. To make sure it gets in front of the right people, please [submit your bug]( https://developercommunity.visualstudio.com/content/problem/post.html?space=21) here.
