### ISSUE TITLE
pr: as CI trigger is only valid for GitHub and Bitbucket Cloud

### ISSUE THREAD

**Issue by carlos-quintero** [MicrosoftDocs/vsts-docs#4983]
A note should be added to the Customize CI triggers section of this page indicating that "pr:" for pull request validation is only valid for GitHub and Bitbucket repos since Azure DevOps Git repos use branch policies. In fact I learned this much later reading such note that is present in the YAML Schema Reference page (https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema), PR Trigger section:

" Important

YAML PR triggers are only supported in GitHub and Bitbucket Cloud. If you are using Azure Repos Git, you can configure a branch policy for build validation in order to trigger your build pipeline for validation."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 521b594c-dbb9-54d5-f56f-00e2f5fa1d92
* Version Independent ID: 509d3e4e-23db-8493-e1a6-acb67ec47e81
* Content: [Customize your pipeline - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/customize-pipeline?view=azure-devops)
* Content Source: [docs/pipelines/customize-pipeline.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/customize-pipeline.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @vijayma
* Microsoft Alias: **vijayma**

**Comment by vijayma** [comment]
@steved0x can you add this note about the difference in how triggers work for various repos? Thank you.

**Comment by steved0x** [comment]
Section added [here](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema#pr-trigger)
