### ISSUE TITLE
Consider adding filter for the branches

### ISSUE THREAD

**Issue by max-lobanov** [MicrosoftDocs/vsts-docs#4987]
Hi, 
We have a build definition that runs on master branch (on each commit to master branch) and in pull-requests. We want to configure slack notification to get notifications only for master branch but it looks like it is not supported yet.
Could you please consider this possibility?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 99a6f5aa-7e92-a028-d13e-e1e4b7fede86
* Version Independent ID: be7e5d7c-0033-6b72-4bd1-809f7d1894aa
* Content: [Azure Pipelines with Slack - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/integrations/slack?view=azure-devops)
* Content Source: [docs/pipelines/integrations/slack.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/integrations/slack.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @atinb
* Microsoft Alias: **atinb**

**Comment by atinb** [comment]
Thanks for the feedback @max-lobanov. Since this is more of a feature suggestion, can you please add this feedback to [https://developercommunity.visualstudio.com/content/idea/post.html?space=21](https://developercommunity.visualstudio.com/content/idea/post.html?space=21)?

**Comment by kumarunster** [comment]
@maxim-lobanov @atinb was this suggestion/feature already requested? do you may share the link for it? Many thanks in advance.
