### ISSUE TITLE
Missing description for default agent pool "Azure Pipelines"

### ISSUE THREAD

**Issue by Mertsch** [MicrosoftDocs/vsts-docs#4989]
There is a new default agent pool "Azure Pipelines" with one "Hosted Agent".
Please add a description of the capabilities / the specialty compared to the other pools.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4409a9cb-8448-edd6-da0a-243e5601aa3e
* Version Independent ID: ec15f71a-a76d-c3f9-1d31-832f92183ef4
* Content: [Agents pools - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/pools-queues?view=azure-devops#feedback)
* Content Source: [docs/pipelines/agents/pools-queues.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/agents/pools-queues.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
@Mertsch We have got a work item on the backlog to add more information for that new single pool and it is coming out soon, but for now you can read about it here: https://docs.microsoft.com/en-us/azure/devops/release-notes/2019/sprint-155-update#single-hosted-pool
