### ISSUE TITLE
Verification of Kubernetes Service Connection fails due to wrong API URL

### ISSUE THREAD

**Issue by schdief** [MicrosoftDocs/vsts-docs#4990]
When adding a new service connection for kubernetes, the verification fails as Azure DevOps misses a slash "/" before the api-path.

Error:
Failed to query service connection API: 'https://HOST/k8s/clusters/c-qz6w5api/v1/nodes'. Status Code: 'NotFound', Response from server: '{"Code":{"Code":"NotFound","Status":404},"Message":"clusters.management.cattle.io \"HOSTapi\" not found","Cause":null,"FieldName":""} '

It uses "https://HOST/k8s/clusters/c-qz6w5api/v1/nodes" but it should be "https://HOST/k8s/clusters/c-qz6w5/api/v1/nodes".

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 72b90dd0-49f9-4ed4-3010-9a64dde6ae5a
* Version Independent ID: 6e679d50-4e94-eee3-8793-af884cc909ca
* Content: [Service connections in Azure Pipelines and Team Foundation Server - Azure Pipelines](https://docs.microsoft.com/de-de/azure/devops/pipelines/library/service-endpoints?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/library/service-endpoints.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/library/service-endpoints.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by bansalaseem** [comment]
we have fixed it in the latest code.

**Comment by danielstefanescu** [comment]
> we have fixed it in the latest code.
@bansalaseem Can you be more specific which is the latest code? We have the issue on Azure DevOps Server 2019.1.1.
