### ISSUE TITLE
This task requires a GitHub service connection

### ISSUE THREAD

**Issue by ctolkien** [MicrosoftDocs/vsts-docs#5001]
Which makes it painful to use for open source repositories....

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8cebdaea-9b1f-e65a-a789-6571b5e28c03
* Version Independent ID: ca0de77d-d8a7-d766-90e6-929bdb2c877f
* Content: [Download GitHub Release task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/download-github-release?view=azure-devops#feedback)
* Content Source: [docs/pipelines/tasks/utility/download-github-release.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/utility/download-github-release.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @ashokirla
* Microsoft Alias: **ashkir**

**Comment by WilliamAntonRohm** [comment]
It looks like you've encountered an issue with the product itself, rather than an issue with the documentation. To make sure it gets in front of the right people, please [submit your bug]( https://developercommunity.visualstudio.com/content/problem/post.html?space=21) here.
