### ISSUE TITLE
complete this page

### ISSUE THREAD

**Issue by Bertrand1967** [MicrosoftDocs/vsts-docs#5002]
Hello,
I suggest to add "branchname" to the "command-line" tab :
git branch branchname -d 
git push origin --delete branchname 

This is not obvious for learning people. Apart from that, this page is very useful.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 183b0984-8a99-c671-5e5a-c1a5d0d85f87
* Version Independent ID: 6e14f792-35d3-97e3-85db-78731cf9b3a5
* Content: [Create and delete a branch in your Git repo - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/branches?view=azure-devops&tabs=command-line#feedback)
* Content Source: [docs/repos/git/branches.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/repos/git/branches.md)
* Product: **devops**
* Technology: **devops-code-git**
* GitHub Login: @apawast
* Microsoft Alias: **sdanie**

**Comment by marcpopMSFT** [comment]
Working on this

**Comment by marcpopMSFT** [comment]
Completed
