### ISSUE TITLE
Why non-admin-of-the-project can't subscribe to pipelines

### ISSUE THREAD

**Issue by igor-teresco** [MicrosoftDocs/vsts-docs#5005]
As regular user I was able to setup and use Azure Devops app in Teams.
Azure Pipelines app allowed me to Sign In but I can't subscribe to a pipeline due to:
Looks like you do not have access to subscribe to this pipeline. Please make sure you are an administrator of the project containing the pipeline.
What is the sense then in using this app as non-admin user?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b9adc845-adee-a494-79b4-3466f51d3ec9
* Version Independent ID: 12445205-8acc-98e6-fe65-9508e0dccb5c
* Content: [Azure Pipelines with Microsoft Teams - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/integrations/microsoft-teams?view=azure-devops#feedback)
* Content Source: [docs/pipelines/integrations/microsoft-teams.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/integrations/microsoft-teams.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @atinb
* Microsoft Alias: **atinb**

**Comment by atinb** [comment]
Thanks for the feedback @igor-teresco. As you mentioned, the Azure Pipelines app requires you to be an admin to set up the subscriptions. However, you can still approve releases from the channel without being an admin. We are also soon releasing URL previews and messaging extension for Pipelines app that will work without the admin permissions.
