### ISSUE TITLE
Llinks to extensions in the marketplace

### ISSUE THREAD

**Issue by evertonmc** [MicrosoftDocs/vsts-docs#5008]
Not finding those extensions in the marketplace:
Work Item Search
Wiki Search
Package Search

only Code Search

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 4f03d007-1303-234b-c32c-de06924d8688
* Version Independent ID: c1bc50f6-d0f8-777c-2a83-d1d892841d12
* Content: [Search across all your code, wiki, packages and work items](https://docs.microsoft.com/de-de/azure/devops/project/search/overview?view=azure-devops)
* Content Source: [docs/project/search/overview.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/project/search/overview.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by evertonmc** [comment]
I've uninstalled this extension from Azure DevOps Server (for reasons) and I am not able to installed back. Any help how to find them?

**Comment by msebolt** [comment]
@evertonmc Thank you for the question.

In the items listed above, **Code Search** is the only Marketplace extension.  The others are included in the Azure DevOps installation.

Please refer to [this article](https://stackoverflow.com/questions/36746857/completely-uninstall-vs-code-extensions) on effectively deleting the extension.  Then try re-installing again.

**Comment by msebolt** [comment]
The changes have been merged, so I'm closing the issue.
