### ISSUE TITLE
Questions related to MS Accounts

### ISSUE THREAD

**Issue by AaliAlikoski** [MicrosoftDocs/vsts-docs#5009]
I am trying to switch from existing AAD to a new one and have a few questions related to the instructions:

What does this mean: "You can't sign in to your organization unless your work or school account has the same email address as your Microsoft account". As far as I know, you cannot create a MS Account with the same domain as you have associated to an existing AAD? That used to be possible but is no longer available, If you try to create a MS Account with a domain that is already "AAD-reserved", you will  get an error. Anyway, I have a completely separate MS Account that I have defined as the organization owner and can login to the organization just fine.

What does this mean: "Ensure that you exist in Azure AD as a member". Does "you" refer to the MS Account? If so, how do you add a MS Account to an AAD (either guest or member)? To the best of my knowledge this used to be available in the previous Azure portal, but has been removed when moving on the current portal. See https://stackoverflow.com/questions/40370571/how-do-i-add-a-microsoft-account-to-azure-active-directory

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 98f0caaf-2697-c506-339b-2dea64233e48
* Version Independent ID: 7cd2ea02-2079-85d0-09e0-a90af59937d9
* Content: [Change connection to Azure AD - Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/change-azure-ad-connection?view=azure-devops#feedback)
* Content Source: [docs/organizations/accounts/change-azure-ad-connection.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/accounts/change-azure-ad-connection.md)
* Product: **devops**
* Technology: **devops-accounts**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @AaliAlikoski, Thanks for reaching out. I've simplified the prerequisites in the article, which should go live within the next few hours. Just so you have them, I've pasted the prereqs below. Thanks again!
**Prerequisites**
Before you disconnect your organization from your directory, and then connect to a new directory, make sure the following is true:
- You're using a Microsoft account, not a school or work account
- You're the organization Owner
- You're in the Project Collection Administrator group (in Organization settings) for the organization 
- You're in the source Azure AD and destination Azure AD as a member. For more information, see how you can [convert an Azure AD guest into a member](faq-add-delete-users.md#q-how-can-i-convert-an-azure-ad-guest-into-a-member).

Thanks! Do let us know if you have any further questions!

**Comment by AaliAlikoski** [comment]
Thanks. I am still puzzled on how can I add a MS Account to Azure AD (either member or guest). Is this somehow possible?

**Comment by chcomley** [comment]
Hi @AaliAlikoski, I think you'll find that one of the following two links should help you. Thanks!

- https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/faq-add-delete-users?view=azure-devops#q-how-can-i-convert-an-azure-ad-guest-into-a-member

- https://docs.microsoft.com/en-us/azure/active-directory/b2b/user-properties#can-azure-ad-b2b-users-be-added-as-members-instead-of-guests

**Comment by AaliAlikoski** [comment]
I don't think those links help me at all. I am talking about not being able to add MS Accounts to Azure AD (which is needed for changing AD connection). Similar issue as described in https://devblogs.microsoft.com/devops/deadline-extended-for-connecting-vsts-accounts-to-azuread/. Justin Marks apparently no longer works for MS, maybe there is a replacement to give some insight into this?
