### ISSUE TITLE
is it tasks.json not task.json

### ISSUE THREAD

**Issue by peterremote1980** [MicrosoftDocs/vsts-docs#501]
in vs.code , is it tasks.json not task.json ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 44581f4a-93df-7507-3844-eadedf9a6cc4
* Version Independent ID: 33c7bcf0-1512-975f-5ef8-9f2a192a84ad
* Content: [Add a Build or Release Task](https://docs.microsoft.com/en-us/vsts/extend/develop/add-build-task?view=vsts)
* Content Source: [docs/extend/develop/add-build-task.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/extend/develop/add-build-task.md)
* Service: **unspecified**
* GitHub Login: @erickson-doug
* Microsoft Alias: **elbatk**

**Comment by nadcraker** [comment]
I believe it is task.json.

**Comment by elbatk** [comment]
Closing this @peterremote1980 , please reach out if you still have issues.
