### ISSUE TITLE
TCM not available with Visual Studio 2019

### ISSUE THREAD

**Issue by varnk** [MicrosoftDocs/vsts-docs#5010]
For some reason the TCM tool was left out of Visual Studio 2019.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1ea562a2-64c0-b7fc-68a8-b95f65059b64
* Version Independent ID: a7f11496-ca5d-ea28-2918-aa29286f0411
* Content: [Customize and manage the test experience - TFS](https://docs.microsoft.com/en-us/azure/devops/reference/witadmin/tcm-customize-manage-test-experience?view=azure-devops-2019#feedback)
* Content Source: [docs/reference/witadmin/tcm-customize-manage-test-experience.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/reference/witadmin/tcm-customize-manage-test-experience.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by msebolt** [comment]
@varnk Thank you for the feedback.

The TCM tool falls under product issues and is not generally covered here, though I have added a note to the documentation.

Please refer to [product support](https://social.msdn.microsoft.com/Forums/en-US/67437b63-f94f-43f9-a7cd-abcd2d3e3b4d/tcmexe-utility-missing-from-visual-studio-2019?forum=vsunittest) for the latest updates.

**Comment by msebolt** [comment]
The documentation has been updated.
