### ISSUE TITLE
Issue with building tags

### ISSUE THREAD

**Issue by jfboismenu** [MicrosoftDocs/vsts-docs#5013]
I'm trying to trigger a build when a tag is created. I'm using this snippet in azure-pipelines.yml
```
trigger:
  branches:
    include:
    - '*'
  tags:
    include:
    - v*
```

If the commit I am tagging is not already in Github, then doing a `git push origin --tags` will trigger a build with the a branch of `vU.Y.Z` in the build history. If the commit has already been pushed, the build is not triggered.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5673ec1-c7d1-e0ac-043a-8fc3d5b226a9
* Version Independent ID: b4872831-51c0-6cf8-1c56-de20beb38a80
* Content: [Build pipeline triggers - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/triggers?view=azure-devops&tabs=yaml#tags)
* Content Source: [docs/pipelines/build/triggers.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/build/triggers.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by hackhnaton1994** [comment]
Help wanted all security Please bug

**Comment by WilliamAntonRohm** [comment]
It looks like you've encountered an issue with the product itself, rather than an issue with the documentation. To make sure it gets in front of the right people, please [submit your bug]( https://developercommunity.visualstudio.com/content/problem/post.html?space=21) here.
