### ISSUE TITLE
Please Update Competitive Comparison Info

### ISSUE THREAD

**Issue by csprauve** [MicrosoftDocs/vsts-docs#5014]
Hi,

There have been a ton of changes from both Microsoft and GitLab since this article was posted on JAN 17, 2018.  Could you please update?

GitLab releases new features on the 22nd of every month (current streak of 96 months), so a lot has definitely changed 
Here is the comparison page for Microsoft Azure DevOps plus GitHub for your review. This will give you a better understanding of our updated capabilities to compare with your latest and greatest features - https://about.gitlab.com/devops-tools/azure-devops-vs-gitlab.html

Feel free to contact me if you have any questions or would like to contribute to updates on our site as well.

THX!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d96200b4-9fc1-7d8c-dce4-6a2b0cb5fa4d
* Version Independent ID: bf8e5f2c-a8a5-d2e1-f89c-5ed5129c32a3
* Content: [Azure DevOps vs GitLab - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/learn/compare/azure-devops-vs-gitlab#feedback)
* Content Source: [https://mseng.visualstudio.com/DefaultCollection/TechnicalContent/_git/devops-learn-pr?path=%2fdocs%2fcompare%2fAzure-DevOps-vs-GitLab.md&version=GBlive&_a=contents](https://mseng.visualstudio.com/DefaultCollection/TechnicalContent/_git/devops-learn-pr?path=%2fdocs%2fcompare%2fAzure-DevOps-vs-GitLab.md&version=GBlive&_a=contents)
* Product: **devops**
* Technology: **devops-learn**
* Git Login: **samgu**
* Microsoft Alias: **davemcki**

**Comment by msebolt** [comment]
@csprauve Thank you for the feedback.

The Azure DevOps team is committed for keeping up-to-date with the latest product news.

Our writers have been notified and the documentation has been updated with the link provided.

@KathrynEE

**Comment by csprauve** [comment]
THX @msebolt.  Can you provide the link to your updates? I didn't see it in your response.

**Comment by msebolt** [comment]
@csprauve  No, these changes are per private repo.  You'll be notified after publish.

**Comment by msebolt** [comment]
@csprauve The changes have been published, closing issue.
