### ISSUE TITLE
Project Permissions Settings page - Preview not working

### ISSUE THREAD

**Issue by dkamalakaran** [MicrosoftDocs/vsts-docs#5016]
Project Permissions Settings page - Preview is not considering permissions at project level and only org admins were able to administer permissions at project level. We had to turn off the preview for this to work fine.

**Comment by WilliamAntonRohm** [comment]
It looks like you've encountered an issue with the product itself, rather than an issue with the documentation. To make sure it gets in front of the right people, please [submit your bug]( https://developercommunity.visualstudio.com/content/problem/post.html?space=21) here.
