### ISSUE TITLE
Unclear distinction between "Software projects" and "team projects"

### ISSUE THREAD

**Issue by valeriobisignanesi** [MicrosoftDocs/vsts-docs#502]
In section "Software projects versus team projects" you wrote "Software projects differ from team projects". The section then goes on to describe what team projects are without any further reference to software projects... this makes no sense to me, am I missing something?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c915b8c-dfb0-154c-b0b0-5c04ee3592cc
* Version Independent ID: 9106e6ff-f787-efa8-3ca3-9e60f46c0f2c
* Content: [Key concepts for working with both VSTS & TFS](https://docs.microsoft.com/en-us/vsts/user-guide/concepts?view=vsts)
* Content Source: [docs/user-guide/concepts.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/user-guide/concepts.md)
* Service: **unspecified**
* GitHub Login: @erickson-doug
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@valeriobisignanesi - Thank you for your comment. I agree that greater clarification is required. I have updated the topic and the updates should be live later today.
