### ISSUE TITLE
How to create sequence variable?

### ISSUE THREAD

**Issue by JohnTortugo** [MicrosoftDocs/vsts-docs#5020]
How can I use this to create a variable containing sequence values. E.g., [1, 2, 3, 4]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 16bf0bbb-8b63-6384-aa33-b5b1e2b8cfe3
* Version Independent ID: f4da8dbd-a02f-bbdf-2cf2-60e081339237
* Content: [Logging commands - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/scripts/logging-commands?view=azure-devops&tabs=powershell)
* Content Source: [docs/pipelines/scripts/logging-commands.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/scripts/logging-commands.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @thomps23
* Microsoft Alias: **alewis**

**Comment by msebolt** [comment]
@JohnTortugo Thank you for the question.

For now you're limited to PowerShell workarounds, such as...

```
$i=0..9
# Set up sequence here...
$index=0
foreach ($element in $i) {
{
   Write-Host "##vso[task.setvariable variable=$index;]$element"
   $index += 1
}
```

Though built-in features such as the one you describe should be documented as they become available.
