### ISSUE TITLE
The content of this document doesn't match the title

### ISSUE THREAD

**Issue by The-Zenix** [MicrosoftDocs/vsts-docs#5022]
There is nothing on this page about managing group notifications. I was led here by an answer on this post https://developercommunity.visualstudio.com/content/problem/243123/vsts-mention-group-not-working.html

But this page has no solution to that problem.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f7bf3dc8-4c12-bf7f-2f65-74e5c90cfc3b
* Version Independent ID: e5b84ecc-d3fe-b65f-b9f7-3d94ee7aed72
* Content: [Manage notifications for a team - Azure DevOps](https://docs.microsoft.com/en-gb/azure/devops/notifications/howto-manage-team-notifications?view=azure-devops#feedback)
* Content Source: [docs/notifications/howto-manage-team-notifications.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/notifications/howto-manage-team-notifications.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @The-Zenix, Thanks for reaching out. I'm a little confused, as the article you mentioned does cover group/team notifications. I took a look at the developer community issue and at this point, I believe that technical support is needed, rather than a convo on the Developer Community. Please go [here,](https://visualstudio.microsoft.com/vs/support/#talktous) and then select **Technical Support**. Best of luck to you. Thanks very much!

**Comment by The-Zenix** [comment]
Hi @chcomley,

Could you show me where on that page group notification settings are mentioned? Could you quote a paragraph? 

The link says 'Manage team and group notifications', but there are literally no mentions of the word 'group' within the article content.

![image](https://user-images.githubusercontent.com/7004692/61987053-d5135200-b056-11e9-8196-fb5660fd99aa.png)

**Comment by chcomley** [comment]
Hi @The-Zenix., You're absolutely right. I'm so sorry about **my** confusion! I've added a section to the article for managing group notifications. It should go live within the next few hours.

Here are the steps, in the meantime, to manage group delivery settings:

1. Sign in to your organization (https://dev.azure.com/{yourorganization}).
2. Select  **Organization settings**. 
3. Select **Global notifications** > **Subscribers**, enter and find your group, and then select **Delivery settings**.
![image](https://user-images.githubusercontent.com/35748196/62084699-b8217f00-b20e-11e9-9f14-6b92632c02f3.png)

4. Choose which option best fits your group's needs, and then select **Save**.

We suspect that the group you're mentioning has the settings on "do not deliver." If you move it to "deliver to individual members," then it should work. If this doesn't work, reach out to [Customer Support](https://visualstudio.microsoft.com/vs/support/#talktous). 
Again, thanks very much for your feedback. Do let me know if you have any further questions or feedback on the new content please. Thanks!
