### ISSUE TITLE
Checkout clean schema says takes a boolean, but example uses "all"

### ISSUE THREAD

**Issue by ghelyar** [MicrosoftDocs/vsts-docs#5023]
schema:
```
steps:
- checkout: self  # self represents the repo where the initial Pipelines YAML file was found
  clean: boolean  # if true, execute `execute git clean -ffdx && git reset --hard HEAD` before fetching
```

example:
```
steps:
- checkout: self  # self represents the repo where the initial Pipelines YAML file was found
  clean: all
```

The Azure Pipelines extension for VS Code highlighted this for me when I tried to use `clean: true`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7458d5b2-1bb7-7d87-7ce6-2b0c430b0155
* Version Independent ID: edf5bbd3-a3f0-5426-e985-31290f8afd05
* Content: [YAML schema - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=example#checkout)
* Content Source: [docs/pipelines/yaml-schema.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/yaml-schema.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @vtbassmatt
* Microsoft Alias: **macoope**

**Comment by vtbassmatt** [comment]
Heh. We had a bug in the parser schema, which flowed into VS Code and which I had erroneously copied into the docs. I have now fixed the docs and the parser, but the VS Code extension needs to be updated as well.

**Comment by vtbassmatt** [comment]
Oh, sorry, I misread your comment. Yes, I see I failed to update the example.

**Comment by ghelyar** [comment]
For what it's worth, "all" works in Azure DevOps, so right now I think it's the schema tab in the documentation that is wrong because it says it takes a boolean but it actually takes a string.

**Comment by vtbassmatt** [comment]
It takes a string because we support runtime expressions there. Then, through a serious of hilarious typecasts, it accidentally works (by treating any non-empty string as `true`).
