### ISSUE TITLE
Document How to Convert Private to Public Feeds

### ISSUE THREAD

**Issue by RehanSaeed** [MicrosoftDocs/vsts-docs#5024]
I already have a private feed with packages in it. I want to convert it to a public feed. This should be documented. Is it even possible?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bceed83a-c520-5576-f54d-a28f8345795c
* Version Independent ID: c4c0690a-8156-4cd5-0f15-5244b077c971
* Content: [Share Packages Publicly](https://docs.microsoft.com/en-gb/azure/devops/artifacts/tutorials/share-packages-publicly?view=azure-devops#feedback)
* Content Source: [docs/artifacts/tutorials/share-packages-publicly.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/artifacts/tutorials/share-packages-publicly.md)
* Product: **devops**
* Technology: **devops-artifacts**
* GitHub Login: @chasewilson
* Microsoft Alias: **phwilson**

**Comment by msebolt** [comment]
@RehanSaeed Thank you for the question.

Public feeds are currently in preview and a feature such as the ability to convert from private to public will be documented as soon as it becomes available.

For now, a good place to keep up-to-date is the [Azure DevOps release notes](https://docs.microsoft.com/en-us/azure/devops/server/release-notes/azuredevops2019?view=azure-devops) page.
