### ISSUE TITLE
Change organization location may be requested by chatting with support bot

### ISSUE THREAD

**Issue by arjenkrap** [MicrosoftDocs/vsts-docs#5025]
Change organization location may be requested by chatting with support bot. So we don't need to *call* support anymore.

However the link is still correct. So maybe is replacing *call* with *contact* the least effort way of making this section up to date.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be194f45-05b2-8421-186f-f12700eea9aa
* Version Independent ID: efffdc56-fd4c-aeba-6cd3-d07aaf776d51
* Content: [Find or change location or region of organization - Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/change-organization-location?view=azure-devops#feedback)
* Content Source: [docs/organizations/accounts/change-organization-location.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/accounts/change-organization-location.md)
* Product: **devops**
* Technology: **devops-accounts**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @arjenkrap, Thanks for taking the time to reach out, we truly appreciate it! I've made this update and it should go live sometime this afternoon. Thanks again and have a great weekend.
