### ISSUE TITLE
What about "sshKeySecureFile:"?

### ISSUE THREAD

**Issue by lbrownell-gpsw** [MicrosoftDocs/vsts-docs#5027]
Shown in the yaml snippet, not described in the documentation.

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ce9d017-fc43-c904-d94b-87cf91265ffc
* Version Independent ID: ecf3b0b7-6c2c-1cd9-33a9-2cf562932e2b
* Content: [Install SSH Key task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/install-ssh-key?view=azure-devops)
* Content Source: [docs/pipelines/tasks/utility/install-ssh-key.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/utility/install-ssh-key.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @DavidStaheli
* Microsoft Alias: **dastahel**

**Comment by lbrownell-gpsw** [comment]
Ah, it's this:  SSH Key.  Not terribly obvious, please make the description names match the yaml keys.

**Comment by msebolt** [comment]
@lbrownell-gpsw Thank you for the feedback.

Your suggestion has been made and is currently under review.
