### ISSUE TITLE
- download: "current" => current is a required parameter

### ISSUE THREAD

**Issue by adibalwani** [MicrosoftDocs/vsts-docs#5029]
If I don't specify current I get =&gt; Error No task definition found matching ID 30f35852-3f7e-4c0c-9a88-e127b4f97211 and version 1.0.0. You must register the task definition before uploading the package.

Please clearly mention that download requires either current or none

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 861ce7a5-4fa4-55f1-2c97-46a9cc6a2f66
* Version Independent ID: bdf954b9-9bbe-8b34-b674-71ad8153519d
* Content: [Publish and consume artifacts in pipelines - Azure Pipelines and TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/pipeline-artifacts?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/artifacts/pipeline-artifacts.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/artifacts/pipeline-artifacts.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @alexmullans
* Microsoft Alias: **amullans**

**Comment by adibalwani** [comment]
Please document that current is a required parameter

**Comment by msebolt** [comment]
@adibalwani  Thank you for the feedback.

However, the documentation shows examples working properly with links to references as needed and the required nature of the parameter seems implied in the [Download task reference](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema#download).

Please comment below if there are any questions.
