### ISSUE TITLE
How to update the PAT used by an agent?

### ISSUE THREAD

**Issue by LarsKemmann** [MicrosoftDocs/vsts-docs#5031]
I just got an email that the PAT for one of my build agents is expiring. How do I update that, short of rebuilding the agent from scratch? I haven't found anything in any documentation or blog posts describing that necessary step.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 47625b86-abd5-ee15-6d61-8bcf81861b96
* Version Independent ID: be9a6174-a69b-7aed-d584-5f602fcc5eb4
* Content: [Azure Pipelines Agents - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/agents?view=azure-devops)
* Content Source: [docs/pipelines/agents/agents.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/agents/agents.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by LarsKemmann** [comment]
Never mind, I think I found it. https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/v2-windows?view=azure-devops#remove-and-re-configure-an-agent

**Comment by LarsKemmann** [comment]
So... actually, it looks like that PAT was only needed when I first configured the agent. Is that correct? If so, it would help if the documentation could clearly spell that out. I'm a little nervous right now that I'm going to have a stalled CI/CD pipeline in a day or so...

**Comment by msebolt** [comment]
@LarsKemmann  Thank you for the question.

You are correct, in that the PAT should be able to regenerate without any adverse effect on the currently running agent.  Please comment below if there any issues after regenerating the token.

Also, the documentation has been updated with a note to reflect this.

**Comment by msebolt** [comment]
The article has been updated for clarification (see [here](https://docs.microsoft.com/azure/devops/pipelines/agents/v2-windows#download-and-configure-the-agent)).
