### ISSUE TITLE
Yarn example uses inconsistent folders.

### ISSUE THREAD

**Issue by dammejed** [MicrosoftDocs/vsts-docs#5033]
In the 'Get Started' section, the example yaml with Yarn shows the yarn cache folder being set to:
`$(Pipeline.Workspace)/.yarn`

The explanatory text later says that the files in `$(Pipeline.Workspace)/.cache/yarn` will be cached.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77c20289-dab2-7a6e-4f63-4b30eaff2c71
* Version Independent ID: d75cc196-90c1-8291-9907-ff405bde4edf
* Content: [Pipeline caching - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/caching/?view=azure-devops)
* Content Source: [docs/pipelines/caching/index.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/caching/index.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @willsmythe
* Microsoft Alias: **wismythe**

**Comment by willsmythe** [comment]
Good catch. We'll fix.

**Comment by colindembovsky** [comment]
I couldn't get either directory to work. I had to use this:
```
- script: |
    export cpath=$(yarn cache dir)
    echo "##vso[task.setvariable variable=YARN_CACHE_PATH;]$cpath"
  displayName: 'Calculate yarn cache path'

- task: CacheBeta@0
  inputs:
    key: |
      yarn
      $(Build.SourcesDirectory)/yarn.lock
    path: $(YARN_CACHE_PATH)
  displayName: Cache Yarn packages
```

**Comment by willsmythe** [comment]
@colindembovsky - what version of Yarn are you using, btw? Yarn has been using the path specified by `YARN_CACHE_FOLDER` for a few years now, so it's not clear why this approach wasn't working for you.

**Comment by willsmythe** [comment]
The fix for this doc inconsistency should appear in the next 24 hours.

**Comment by jherby2k** [comment]
I just want to cache a simple .msi that i'm currently downloading on each build. How would I do that?
