### ISSUE TITLE
How to copy files from remote machines via ssh

### ISSUE THREAD

**Issue by sakthiyuvaraj** [MicrosoftDocs/vsts-docs#5034]
Thank you for your feedback!

The issues in this repo are for documentation feedback.

If you are submitting your documentation feedback issue directly through GitHub, please provide the URL of the article so we can route the feedback to the correct author.

Please report Azure DevOps or TFS software bugs, feedback, or questions in the [Azure DevOps Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html).

**Comment by msebolt** [comment]
@sakthiyuvaraj Both SSH and SCP (for file transfers) are now supported in Windows 10.  

Please see [Installation of SSH](https://docs.microsoft.com/windows-server/administration/openssh/openssh_install_firstuse) to get started.
