### ISSUE TITLE
Cannot find ANY instruction on how to RENAME a wiki page & navigation links on dev.azure.com

### ISSUE THREAD

**Issue by swalkersbw** [MicrosoftDocs/vsts-docs#5035]
Hi Guys, 

Would you be able to point me towards some instruction on how to rename a navigation 'page link' in dev.azure.com please?

i.e. is it simply a matter of getting the right permissions? 

Info: if it makes any difference we have enterprise subscription licenses and are able to create new pages but there don't appear to be any options to rename a page (& navigation link) after creation?

(PS: any option to add screenshots here that I'm not seeing?)

Interested to know,

Thanks,
Steve.
steven.walker@pwc.com
0434850541

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d7892ee5-8b56-bd95-29bb-41ebb8a8bd7e
* Version Independent ID: eccf0785-0968-d6a2-d29e-0c4796aa165c
* Content: [Add, edit, reorder and manage wiki pages in Azure DevOps - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/project/wiki/add-edit-wiki?view=azure-devops#feedback)
* Content Source: [docs/project/wiki/add-edit-wiki.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/project/wiki/add-edit-wiki.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @swalkersbw, Thanks for reaching out! From your wiki page, select **Edit** (top right corner of your screen), change the page title, and then select **Save**. Did I get your ask right? Is this helpful?
 
![edit-page-name-in-wiki](https://user-images.githubusercontent.com/35748196/62148590-db037000-b2ae-11e9-981b-05bd2fb406b8.jpg)
