### ISSUE TITLE
Manipulating pipeline variables

### ISSUE THREAD

**Issue by sadedil** [MicrosoftDocs/vsts-docs#5036]
Could you add some variable manipulation samples to this page?

For example i have a variable
```
variables:
  stringVar: imagerepo/image:55
```

And i want to use `imagerepo/image` and `55` as separate variables, how can i use string operations like split, substring, etc.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77c58a78-a567-e99a-9eb7-62dddd1b90b6
* Version Independent ID: 680a79bc-11de-39fc-43e3-e07dc762db18
* Content: [Expressions - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/expressions?view=azure-devops)
* Content Source: [docs/pipelines/process/expressions.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/expressions.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by steved0x** [comment]
@sadedil If you are wanting to assemble the `imagerepo/image:55` value out of `imagerepo/image` and `55` and it is for string concatenation you could use the format function:

```
variables:
  v1: imagerepo/imagerepo
  v2: 55
  v3: $[format('{0}:{1}', variables.v1, variables.v2)]
```

I'm not sure how to use expressions such as split or substring to get those individual values out, let me see if I can find out for you.

**Comment by steved0x** [comment]
@sadedil Sorry for the delay in following up to close the loop on this issue - pipeline expressions don't include string operations like split, substring, etc... The easiest way to do that would be to use a custom script task (for example all Microsoft-hosted agents have node installed) to do the string operations and return the desired parts, for example splitting up a version string to access the component parts.
