### ISSUE TITLE
devops server/TFS

### ISSUE THREAD

**Issue by CloudCrusader** [MicrosoftDocs/vsts-docs#5039]
"The Azure DevOps team is made of about 800 people that contribute to either the subscription-based cloud service (Azure DevOps Server) or the on-permise product (TFS)."

this no longer seems correct as 'Azure Devops' is the online version and 'Azure DevOps server' is the on-premise solution now.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 80853077-4c90-2663-7ed6-5fadbcf4f4ed
* Version Independent ID: 4864bcb3-1930-d4f1-c927-1adbbb2899ac
* Content: [Agile principles in practice - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/learn/devops-at-microsoft/agile-principles-in-practice#feedback)
* Content Source: [https://mseng.visualstudio.com/DefaultCollection/TechnicalContent/_git/devops-learn-pr?path=%2fdocs%2fdevops-at-microsoft%2fagile-principles-in-practice.md&version=GBlive&_a=contents](https://mseng.visualstudio.com/DefaultCollection/TechnicalContent/_git/devops-learn-pr?path=%2fdocs%2fdevops-at-microsoft%2fagile-principles-in-practice.md&version=GBlive&_a=contents)
* Product: **devops**
* Technology: **devops-learn**
* Git Login: **samgu**
* Microsoft Alias: **samgu**

**Comment by WilliamAntonRohm** [comment]
@CloudCrusader -- thank you for your feedback.  I have updated the documentation and it should be live by tomorrow.
