### ISSUE TITLE
Missing documentation of 'Output Variables'

### ISSUE THREAD

**Issue by iyerusad** [MicrosoftDocs/vsts-docs#504]
Although [Output Variables](https://github.com/Microsoft/vsts-agent/blob/master/docs/preview/outputvariable.md) are in preview, the fields appear to be available in VSTS today. It would make sense to bring in the amount of documentation that is relevant.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ffebdc8-521c-44b5-cde4-4abdc1bd6f18
* Version Independent ID: dc0effda-6d93-62aa-64c5-4e6f283b0826
* Content: [Build variables](https://docs.microsoft.com/en-us/vsts/build-release/concepts/definitions/build/variables?view=vsts&tabs=powershell)
* Content Source: [docs/build-release/concepts/definitions/build/variables.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/build-release/concepts/definitions/build/variables.md)
* Service: **unspecified**
* GitHub Login: @erickson-doug
* Microsoft Alias: **alewis**

**Comment by vijayma** [comment]
Thanks for the feedback. We will be working on the variables topic again in the next month or so. Will include information about output variables as part of this update.

**Comment by ArgTang** [comment]
@vijayma 

Could you also include a paragraph on how to consume the output variable in another step. I have an output variable but i have no idea how to use it later
