### ISSUE TITLE
REST APIs information

### ISSUE THREAD

**Issue by stephanmiehe** [MicrosoftDocs/vsts-docs#5041]
It currently says "Stay tuned for more information.". Do you have an ETA for when a REST API is going to be available? Alternatively, do you have a simple JSON feed that could be consumed? Something like: https://status.cloud.google.com/incidents.json

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 55f2bb3a-6619-88c0-ba29-23af30fcb301
* Version Independent ID: 0ede4455-b1df-ffef-743f-126a5e9a1a00
* Content: [Azure DevOps Service Status Documentation](https://docs.microsoft.com/en-us/azure/devops/user-guide/service-status-info?view=azure-devops#feedback)
* Content Source: [docs/user-guide/service-status-info.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/user-guide/service-status-info.md)
* Product: **devops**
* Technology: **devops-new-user**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @stephanmiehe, Thanks for reaching out. I'm looking into this and will be in touch, thanks!

**Comment by chcomley** [comment]
Hi @stephanmiehe, I heard back from a PM that we don't currently have any plans for a JSON feed. But, you can use [the RSS feed](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fstatus.dev.azure.com%2F_rss&data=02%7C01%7CChrystal.Comley%40microsoft.com%7Cdf5cd2d737bc4e76928308d7197a4a17%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637005885350098113&sdata=3rKRRfSJYPpgRIa7s0SQx4IurCmcfJjdqpCTLmIvn%2B0%3D&reserved=0) that is already in place. Hope that's helpful! Thank you!

**Comment by stephanmiehe** [comment]
Hi @chcomley, looking at the RSS schema the challenge is that there is no systematic way to evaluate if an incident is open or closed as this only seems to be communicated through plain text in the `<description>` section. Can you check with the team if they have a solution for this? Maybe add a `<status>` element for each incident which tracks open/closed?

**Comment by chcomley** [comment]
Hi @stephanmiehe, I've reached out and will be in touch. Have a nice day! Thanks!

**Comment by chcomley** [comment]
Hi @stephanmiehe, At the moment, the implementation of the RSS feed creates a new RSS item only when a new live site event is created. When a live site event is updated, no new feed is being created. The team tells me that they are looking at making some improvements to the RSS feed in the near future and will keep this piece of feedback in mind. If you're interested, you can also [submit your idea](https://visualstudio.microsoft.com/vs/support/#talktous). Thank you!
