### ISSUE TITLE
follow issue not available in TFS

### ISSUE THREAD

**Issue by nadavsinai** [MicrosoftDocs/vsts-docs#5043]
When will this feature be available for on-premise TFS ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cd3da932-a8f8-f0b9-668d-0eb498df93b6
* Version Independent ID: 51e6cad0-1737-017a-9ce1-8c6c0090fc56
* Content: [Follow wiki page, get notifications - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/project/wiki/follow-notifications-wiki-pages?view=azure-devops#feedback)
* Content Source: [docs/project/wiki/follow-notifications-wiki-pages.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/project/wiki/follow-notifications-wiki-pages.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @nadavsinai, Thanks for reaching out! This feature will be available with the Azure DevOps Server 2020 release. Thank you!
