### ISSUE TITLE
Running decorator after a task

### ISSUE THREAD

**Issue by WackPenguin** [MicrosoftDocs/vsts-docs#5047]
Hi, 

Reading through the docs, there's currently no way to run decorator after a specific task in a job. Let's say if you always want to run decorator after checkout, but you have self checkout in your pipeline yaml. In this case the decorator will run before checkout.

Is that going to be possible at some point in the future?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0704e7ce-a2bb-7ccd-4ad4-2c6ad55bc8f4
* Version Independent ID: 4efcddb9-864d-f895-8122-451c1045b272
* Content: [Pipeline decorators](https://docs.microsoft.com/en-us/azure/devops/extend/develop/add-pipeline-decorator?view=azure-devops#feedback)
* Content Source: [docs/extend/develop/add-pipeline-decorator.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/extend/develop/add-pipeline-decorator.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @stephenmichaelf
* Microsoft Alias: **stfrance**

**Comment by WilliamAntonRohm** [comment]
Thanks for the suggestion! The product teams aren’t always watching this repository, so to make sure it gets in front of them for triage, please [submit your idea]( https://developercommunity.visualstudio.com/content/idea/post.html?space=21) here.
