### ISSUE TITLE
No Branch filters.

### ISSUE THREAD

**Issue by josersleal** [MicrosoftDocs/vsts-docs#5049]
Follow the steps below to create a CI trigger that will run a build for feature branches.

Select Pipelines, and then choose Builds.

Locate the build pipeline that services your master branch. Select Edit.

Select the Triggers menu for your build. Ensure you have Continuous integration enabled.

Select the + Add icon under Branch filters.

-
Actual: Branch filters. is not visible

Pre-conditions:

Code repo is TFVC based

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a55e404e-010b-32e5-30e0-71a2663a4f89
* Version Independent ID: e011575a-691c-af48-2268-1959c9f3020b
* Content: [Building multiple branches - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/ci-build-git?view=azure-devops&tabs=classic)
* Content Source: [docs/pipelines/build/ci-build-git.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/build/ci-build-git.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
@josersleal I'm sorry for the delay in reviewing this issue - this topic is for Git only and does not apply to TFVC. This is noted in the [prerequisities](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/ci-build-git?view=azure-devops&tabs=classic#prerequisites) section of the topic. 

Is your code repo a TFVC repo or a Git repo? If it is a Git repo, it sounds like there might be a bug, please file an issue here: https://developercommunity.visualstudio.com/spaces/21/index.html

Thank you for your feedback and sorry that you ran into trouble.
