### ISSUE TITLE
Are tags really case sensitive?

### ISSUE THREAD

**Issue by olofhellman** [MicrosoftDocs/vsts-docs#5055]
This page says "Tags are case sensitive.", and I wish they were, but I cannot change a mis-cased tag to the correct case.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9bf3ce0a-184f-ca49-5453-01317e23dde5
* Version Independent ID: 0af9b10e-1126-2fda-982b-63d5795f9213
* Content: [Add tags to work items - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/queries/add-tags-to-work-items?view=azure-devops#feedback)
* Content Source: [docs/boards/queries/add-tags-to-work-items.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/boards/queries/add-tags-to-work-items.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by WilliamAntonRohm** [comment]
Thanks for the suggestion! The product teams aren’t always watching this repository, so to make sure it gets in front of them for triage, please [submit your idea]( https://developercommunity.visualstudio.com/content/idea/post.html?space=21) here.

**Comment by keparanj** [comment]
To follow up here, the OP posted this in the dev community forum [here](https://developercommunity.visualstudio.com/idea/670984/azure-devops-tags-should-be-case-sensitive.html), but that was shot down with a standard "we don't have time for this" reply. I ran into this lately, and can confirm that this is still an issue as of today.

Not acknowledging that this is a genuine bug and worse, misleading people via the documentation simply erodes trust and makes me wonder what else is broken out there. No documentation is better than bad documentation.

**Comment by KathrynEE** [comment]
@keparanj - You can't change a tag once you've started using it. However, if you remove all uses of it in work items, the system will delete it within 3 days. Please review this article for more information: https://docs.microsoft.com/en-us/azure/devops/boards/queries/add-tags-to-work-items?view=azure-devops#delete-remove-or-manage-tags.

**Comment by keparanj** [comment]
But then that's not really case sensitive in the conventional sense, is it? If "tag" and "TAG" cannot coexist in the system, then for all practical intents (filtering), there is at least one interpretation that they are case insensitive. (especially given that you may not always have control over a mis-cased tag).

**Comment by KathrynEE** [comment]
@keparanj - The tags are case sensitive. So you can enter Tag, tag, TAG and those three variations are registered by the system as different. However, with regards to queries and filtering - no, the case doesn't really matter.

**Comment by keparanj** [comment]
> So you can enter Tag, tag, TAG and those three variations are registered by the system as different
Sure, just not simultaneously.

**Comment by sarvasana** [comment]
Azure DevOps tagging is the worst I have ever experienced.
