### ISSUE TITLE
Any way to add a purple "note" in markdown docs like you show above?

### ISSUE THREAD

**Issue by dahlsailrunner** [MicrosoftDocs/vsts-docs#5059]
I'd like to include some "notes" in markdown docs like readme's etc in repos inside Azure DevOps.  It doesn't appear that there is a way to do this.  Is anything planned or can it be made possible?  Or even better, did I miss the right way to achieve this?

An example of what I'm trying to achieve is shown by this text above on this page: 
"Not all file formats are supported within pull requests, such as Microsoft Office Message (.msg) files."

Thanks in advance -
Erik

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fa622358-f5bb-1f5c-177a-081a37b6acef
* Version Independent ID: 72f7fd16-a822-66c8-3a34-8905645ce5f2
* Content: [Markdown syntax for files, widgets, and wikis in Azure DevOps - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/project/wiki/markdown-guidance?view=azure-devops#feedback)
* Content Source: [docs/project/wiki/markdown-guidance.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/project/wiki/markdown-guidance.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by StingyJack** [comment]
@dahlsailrunner - can you post a screencap?  I dont see what you mean on this page.

Markdown does accept HTML, perhaps its just a `<div>` element with some css that they have added.

**Comment by dahlsailrunner** [comment]
Yep -- here you go!  :)  And i did *try* to do this with html, but i couldn't get it to work.
![note-example](https://user-images.githubusercontent.com/8389867/62219953-d6a18a80-b374-11e9-9cb5-8be0190f9c74.PNG)

**Comment by chcomley** [comment]
Hi @dahlsailrunner, I'm not sure I completely understand your question - you're trying to add markdown files in repos, and then publish them as wikis? You can do that using code wikis: [Publish repo to wiki](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fazure%2Fdevops%2Fproject%2Fwiki%2Fpublish-repo-to-wiki%3Fview%3Dazure-devops&data=02%7C01%7CChrystal.Comley%40microsoft.com%7C6f1cdd423bc243c439f608d71573f3a7%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637001460078636876&sdata=AcIc5cX%2BKCp1bGHxWoxIDE0IiVz5P6SWHwOln6ypxcY%3D&reserved=0).
If I've misunderstood your intention, please let me know.

**Comment by dahlsailrunner** [comment]
I'm trying to add a purple "note" section in a markdown doc in a readme.md file within a repo - much like the one shown in the screenshot above.  It *looks* like there is some syntax like:
```
> [!NOTE]
> Put note text here...
```
but that doesn't seem to work in azure devops when it renders the md file.

**Comment by chcomley** [comment]
Hi @dahlsailrunner, These are special div class syntax tags that our publishing group supports for docs.microsoft.com. What you're trying to do isn't supported. If you'd like to submit an idea or feature request, please go here: https://visualstudio.microsoft.com/vs/support/#talktous. Thanks!

**Comment by dahlsailrunner** [comment]
Done!  In case anyone comes looking for it, the request is here: 

https://developercommunity.visualstudio.com/idea/670867/add-support-for-a-note-in-markdown.html

Thanks for the time / consideration.

**Comment by TroyWitthoeft** [comment]
Hey all, the github thread debating this is [enormous](https://github.com/community/community/discussions/16925).  
In the meantime here is some Azure DevOps [html style](https://learn.microsoft.com/en-us/azure/devops/project/wiki/wiki-markdown-guidance?source=recommendations&view=azure-devops#html-tag-support-in-wiki-pages) that gets us close.

Notes

```  
> <span style="color:cornflowerblue">🛈 Note</span>
> One day Azure DevOps will support notes.
```
![image](https://user-images.githubusercontent.com/1102958/213024976-35299f7a-e90d-48d6-9b93-dc4c55ff5f4c.png)

Warnings

```  
> <span style="color:orange">⚠️ Warning</span>
> Until then, we will do it ourselves.
```
![image](https://user-images.githubusercontent.com/1102958/213025085-be9b4319-d27b-4cb6-bd53-71d1ad0fef0e.png)

**Comment by DaleyKD** [comment]
@TroyWitthoeft : Thanks for this. I'll use it in the meantime.

I wonder if ADO will ever extend further support for some of its markdown.

**Comment by mikedizzle** [comment]
@DaleyKD my guess is no.
