### ISSUE TITLE
Patterns with * and / must be quoted?

### ISSUE THREAD

**Issue by rpavlik** [MicrosoftDocs/vsts-docs#5060]
A pattern like the example `**/*.zip` isn't actually allowed: the VS Code extension complains about not supporting multiple files, and the actual build itself fails with: 

```
/.azure-pipelines/ci.yml: (Line: 97, Col: 19, Idx: 2880) - (Line: 97, Col: 20, Idx: 2881): While scanning an anchor or alias, did not find expected alphabetic or numeric character.
```

However, the other approach, `*/*.zip`, breaks the azure pipeline the same way, it's only the vscode that accepts it.

Update: Looks like I can quote the single-star version and it will parse: `patterns: "*/*.dll"` parsed OK.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 861ce7a5-4fa4-55f1-2c97-46a9cc6a2f66
* Version Independent ID: bdf954b9-9bbe-8b34-b674-71ad8153519d
* Content: [Publish and consume artifacts in pipelines - Azure Pipelines and TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/pipeline-artifacts?view=azure-devops&tabs=yaml-task#feedback)
* Content Source: [docs/pipelines/artifacts/pipeline-artifacts.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/artifacts/pipeline-artifacts.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @alexmullans
* Microsoft Alias: **amullans**

**Comment by chasewilson** [comment]
Hi @rpavlik Thanks for the feedback! You are right, you should wrap the patterns in quotes and I'll update the docs accordingly :)
