### ISSUE TITLE
Can't share private extension with org

### ISSUE THREAD

**Issue by acsehi** [MicrosoftDocs/vsts-docs#5061]
Install your extension section, second point: "Select the + Organization button, enter the name of your organization, and press enter." There is not such a button. I am totally blocked on this issue.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 14955ee9-29f2-46fe-3a8d-a42666f53ffc
* Version Independent ID: 5d417cd0-a671-ee30-8fca-5f8b0addd328
* Content: [Develop a web extension for Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/extend/get-started/node?view=azure-devops#feedback)
* Content Source: [docs/extend/get-started/node.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/extend/get-started/node.md)
* Product: **devops**
* Technology: **devops-ecosystem**
* GitHub Login: @willsmythe
* Microsoft Alias: **wismythe**

**Comment by acsehi** [comment]
Meh, the button is visible in Legacy Edge browser but not in chrome...

**Comment by WilliamAntonRohm** [comment]
Thanks for the feedback! The product teams aren’t always watching this repository, so to make sure it gets in front of them for triage, please [submit your idea]( https://developercommunity.visualstudio.com/content/idea/post.html?space=21) here.
