### ISSUE TITLE
Link to https://docs.microsoft.com/en-us/azure/devops/pipelines/build/repos/index returns 404

### ISSUE THREAD

**Issue by epernst** [MicrosoftDocs/vsts-docs#5065]
Link to https://docs.microsoft.com/en-us/azure/devops/pipelines/build/repos/index from Build.BuildNumber section returns a 404 error.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ffebdc8-521c-44b5-cde4-4abdc1bd6f18
* Version Independent ID: dc0effda-6d93-62aa-64c5-4e6f283b0826
* Content: [Predefined variables - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/build/variables.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/build/variables.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by msebolt** [comment]
@epernst Thank you for the feedback.  

This was fixed per issue https://github.com/MicrosoftDocs/vsts-docs/issues/4885, though it appears the changes have not been published yet.

Changes should be available within the next 24 hours.

**Comment by msebolt** [comment]
Sorry for the delay, additional broken links have been found.  Changes are now under review.
