### ISSUE TITLE
basePath is not documented

### ISSUE THREAD

**Issue by IanKemp** [MicrosoftDocs/vsts-docs#5069]
Under "Advanced", there is an option to set the base path (equivalent to passing -BasePath to nuget.exe), but this is not documented, nor is the reason you would or would not use this option.

![image](https://user-images.githubusercontent.com/1726434/62207866-1e341080-b38d-11e9-88d4-71159eceafd4.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0fa37a3f-6551-16ad-e164-a4ac522cdaab
* Version Independent ID: a3fd6935-2b99-92ef-4eb3-3249fca01f8a
* Content: [NuGet restore, pack, and publish task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/package/nuget?view=azure-devops#arguments)
* Content Source: [docs/pipelines/tasks/package/nuget.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/package/nuget.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @chasewilson
* Microsoft Alias: **phwilson**

**Comment by msebolt** [comment]
@IanKemp  Thank you for the feedback.

`Base path` is appended when including files as described in [Nuspec](https://docs.microsoft.com/en-us/nuget/reference/nuspec#including-assembly-files) in case you wanted a more customized build process.

I'll see about including a brief description in the parameter file.

**Comment by msebolt** [comment]
The documentation has been updated.
