### ISSUE TITLE
Better link for "add those users as foreign principals" in the Note in the "Add users to your VSTS account" section

### ISSUE THREAD

**Issue by jgold6** [MicrosoftDocs/vsts-docs#507]
Currently the link for "add those users as foreign principals" links to this document: https://docs.microsoft.com/en-us/azure/active-directory/add-users-azure-active-directory#add-a-user
which does not address adding users as a "foreign principal" or even adding guest users, though there is a link at the bottom "Add guest users from another directory" which links to this document: https://docs.microsoft.com/en-us/azure/active-directory/active-directory-b2b-what-is-azure-ad-b2b
which does seem to cover it, but again never mentions "foreign principal" or even suggest clicking the "Add Guest User" button. 

This would be a better document to link to: https://docs.microsoft.com/en-us/vsts/accounts/add-external-user?view=vsts

Or better yet, that Note in the "Add users to your VSTS account" section should be re-written, something like:
"If have an Azure Active Directory (Azure AD) backed VSTS account, and you need to add users who are external to your Azure AD, please follow this guide: https://docs.microsoft.com/en-us/vsts/accounts/add-external-user?view=vsts

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ba25948-6554-762f-dd0b-0c0299b80066
* Version Independent ID: 87f00be4-5aae-0b9d-8968-31c35ddf6944
* Content: [Add account users for Visual Studio Team Services](https://docs.microsoft.com/en-us/vsts/accounts/add-account-users-from-user-hub?view=vsts#add-users-to-your-vsts-account)
* Content Source: [docs/accounts/add-account-users-from-user-hub.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/accounts/add-account-users-from-user-hub.md)
* Service: **unspecified**
* GitHub Login: @erickson-doug
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
@jgold6 Thanks so much for your input. I've updated the note and link. This change should be live by sometime this afternoon.
