### ISSUE TITLE
Create tag definition is not in herited from Project Valid Users

### ISSUE THREAD

**Issue by TinyLabIT** [MicrosoftDocs/vsts-docs#5070]
"Create tag definition" is mentioned twice in this doc. The first instance is correct, contributors have it set to Allow. The second section is not, "Create tag definition" is not set to Allow on Project Valid Users and therefore not inherited by Contributors and Readers. I checked this in a fresh Azure DevOps Server 2019 install and unmodified collection.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 68686c2b-c69a-d9e4-3e21-a46d231b649c
* Version Independent ID: 049659da-1772-3166-f909-4feeb8a97730
* Content: [What are all the default permissions and groups? - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/security/permissions?view=tfs-2018&tabs=preview-page)
* Content Source: [docs/organizations/security/permissions.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/security/permissions.md)
* Product: **devops**
* Technology: **devops-security**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@TinyLabIT - Thank you for your correction. I will update the article per the corrections  you have noted.
