### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by sylvainrodrigue** [MicrosoftDocs/vsts-docs#5071]
Would be nice to add a warning: converting a local workspace to a server workspace can take &gt; 10 minutes when the workspace contains more than 100 000 files.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9b16d189-fa47-b490-5186-76bc9acdcacc
* Version Independent ID: f8e87439-67ec-b342-7e2c-8bc162f53574
* Content: [Decide between using a local or a server workspace - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/tfvc/decide-between-using-local-server-workspace?view=azure-devops#feedback)
* Content Source: [docs/repos/tfvc/decide-between-using-local-server-workspace.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/repos/tfvc/decide-between-using-local-server-workspace.md)
* Product: **devops**
* Technology: **devops-code-tfvc**
* GitHub Login: @apawast
* Microsoft Alias: **sdanie**

**Comment by WilliamAntonRohm** [comment]
Thanks for the suggestion! The product teams aren’t always watching this repository, so to make sure it gets in front of them for triage, please [submit your idea]( https://developercommunity.visualstudio.com/content/idea/post.html?space=21) here.
