### ISSUE TITLE
Access to Conditions in task.json

### ISSUE THREAD

**Issue by mattchoi2** [MicrosoftDocs/vsts-docs#5073]
I am trying to put together a task extension for release pipelines.  I want the extension to run always even if an earlier task fails.  Is there a way for me to set this setting from the task.json file?  

I've looked at the [task.json schema](https://github.com/Microsoft/azure-pipelines-task-lib/blob/master/tasks.schema.json) but I wasn't able to find any attribute that matches the "condition" attribute as listed on the [conditions documentation page](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/conditions?view=azure-devops&tabs=yaml).  

I'd imagine you could type something like `"condition": "always"` into task.json but I can't seem to find out how to do this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 44581f4a-93df-7507-3844-eadedf9a6cc4
* Version Independent ID: 33c7bcf0-1512-975f-5ef8-9f2a192a84ad
* Content: [Add a Build or Release Task](https://docs.microsoft.com/en-us/azure/devops/extend/develop/add-build-task?view=azure-devops#feedback)
* Content Source: [docs/extend/develop/add-build-task.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/extend/develop/add-build-task.md)
* Product: **devops**
* Technology: **devops-ecosystem**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @mattchoi2, Thanks for reaching out. We don't allow that to be set at the task level. Only the definition creator can choose the task conditions.
Please let me know if you have any further questions. Thanks!
