### ISSUE TITLE
In dire need of examples

### ISSUE THREAD

**Issue by zarochi** [MicrosoftDocs/vsts-docs#5075]
This feature does not work as simply as stated with more complex pipelines. There are no other docs around on how to use this aside from personal blogs. I've spent the last 2 days just trying to pass a password around correctly in my pipeline. We need someone to do a write up of how to use this in multi stage pipelines where there are multiple jobs and tasks. A simple example does not suffice here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 69ff8e50-4187-3622-1beb-155f006af5f5
* Version Independent ID: bc56fa96-bded-95f8-39a4-a9e5242db1bf
* Content: [Azure Key Vault task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-key-vault?view=azure-devops)
* Content Source: [docs/pipelines/tasks/deploy/azure-key-vault.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/deploy/azure-key-vault.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by RoopeshNair** [comment]
@N-Usha

**Comment by zarochi** [comment]
I just wanted to add an update. All my issues ended up being due to nested variables. I'll put a note on the variables doc to have it updated to include this. I ended up having to get that information from an MSFT on StackOverflow. I still think this warrants more examples, but my original reason for an example is moot now.

**Comment by N-Usha** [comment]
Thanks @zarochi. In the doc, we have "Note" which states that "Values are retrieved as strings. For example, if there is a secret named connectionString, a task variable connectionString is created with the latest value of the respective secret fetched from Azure key vault. This variable is then available in subsequent tasks." And you should be able to access the variable as $(connectionString) just like how you access any other variable. Given that you already sorted your issues, Please be more specific about how can we improve the task doc further.

**Comment by ajklotz** [comment]
What happens if there are other variables already defined on the pipeline and this stuff comes down from the keyvault? Which variable wins?

**Comment by franzoir** [comment]
@N-Usha What is the expected behavior when a secret name contains hyphens? ex "my-awesome-secret" 
Will the pipeline variable become $(my-awesome-secret) or will it be formatted differently?
