### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by buzzwick** [MicrosoftDocs/vsts-docs#5077]
You can also sign up and sign in using your GetHub credentials.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ffffb75a-67a8-f005-9980-de1270efbabf
* Version Independent ID: 4ae8f3f0-24e2-05f7-5c2e-d0a23aa330c0
* Content: [Learn how to connect/integrate GitHub with Azure Boards - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/github/?view=azure-devops)
* Content Source: [docs/boards/github/index.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/boards/github/index.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by dplotnikov** [comment]
@KathrynEE please merge the PR and feel free to close this issue
