### ISSUE TITLE
Wrong Link in table:  "Capture page load performance data"

### ISSUE THREAD

**Issue by MisterReally** [MicrosoftDocs/vsts-docs#5078]
There is a link on the page in a comparison chart where the row reads: Capture page load performance data. 

Not sure where this is supposed to link to, but the existing link has nothing to do with capturing page load performance data.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e32b0e4-8af5-4bb3-d65b-bc661210944c
* Version Independent ID: a5987d1f-fb94-4a49-f70b-9f8932925e54
* Content: [Guidance on MTM usage - Azure Test Plans](https://docs.microsoft.com/en-us/azure/devops/test/mtm/guidance-mtm-usage?view=azure-devops)
* Content Source: [docs/test/mtm/guidance-mtm-usage.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/test/mtm/guidance-mtm-usage.md)
* Product: **devops**
* Technology: **devops-test**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by WilliamAntonRohm** [comment]
Addressed in https://dev.azure.com/mseng/TechnicalContent/_git/vsts-docs-pr/pullrequest/494407

**Comment by WilliamAntonRohm** [comment]
Thank you for your feedback.  I have updated the documentation and it should be live by tomorrow.
