### ISSUE TITLE
Check Notifications

### ISSUE THREAD

**Issue by MattMencel** [MicrosoftDocs/vsts-docs#5083]
I've been experimenting with this feature and it's working pretty well so far. Currently, I don't see that any notifications go out when there is a stage waiting on a review. Is this functionality still being planned or is there another way to approach that?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b067a175-f640-7503-9c1e-f0130c6dbeda
* Version Independent ID: ff743c7b-a103-eae6-4478-62ba995a4b36
* Content: [Checks - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/checks?view=azure-devops)
* Content Source: [docs/pipelines/process/checks.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/checks.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @shashankbansal
* Microsoft Alias: **shashban**

**Comment by WilliamAntonRohm** [comment]
Thanks for the suggestion! The product teams aren’t always watching this repository, so to make sure it gets in front of them for triage, please [submit your idea]( https://developercommunity.visualstudio.com/content/idea/post.html?space=21) here.

**Comment by mike74vh** [comment]
Another suggestion about notifications: these notifications to approvers could be also integrated to Azure Pipelines app for Slack.

**Comment by WilliamAntonRohm** [comment]
@mike74vh -- thank you for your feedback. Please consider using the above link to submit your idea.
