### ISSUE TITLE
No Delete button is displayed

### ISSUE THREAD

**Issue by mpathfinder** [MicrosoftDocs/vsts-docs#5085]
In our on premise Azure Devops installation, Although I am a member of a project's administrators, no Delete button is seen in Overview menu.
What's wrong? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a614791-0c5d-4373-3194-11695e40e1d1
* Version Independent ID: 737e5a3b-d7be-9d36-7b5a-638976406d74
* Content: [Delete, remove project - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/projects/delete-project?view=azure-devops)
* Content Source: [docs/organizations/projects/delete-project.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/projects/delete-project.md)
* Product: **devops**
* Technology: **devops-accounts**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @mpathfinder, Thanks for reaching out. A few things to make sure of first, are you sure you're in **Project** settings, rather than **Organization** settings? Are you a Project Admin for the project you wish to delete? Lastly, what version of the product are you using please? Thanks.

**Comment by chcomley** [comment]
I'll be closing this issue, as there's been no response. Did you get this figured out? If I've missed you, please do respond, and we can reopen this issue. Thanks very much.

**Comment by kawsar158** [comment]
> In our on premise Azure Devops installation, Although I am a member of a project's administrators, no Delete button is seen in Overview menu.
> What's wrong?
> 
> #### Document Details
> ⚠ _Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking._
> 
> * ID: 5a614791-0c5d-4373-3194-11695e40e1d1
> * Version Independent ID: 737e5a3b-d7be-9d36-7b5a-638976406d74
> * Content: [Delete, remove project - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/projects/delete-project?view=azure-devops)
> * Content Source: [docs/organizations/projects/delete-project.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/projects/delete-project.md)
> * Product: **devops**
> * Technology: **devops-accounts**
> * GitHub Login: @chcomley
> * Microsoft Alias: **chcomley**

On

**Comment by kawsar158** [comment]
On
