### ISSUE TITLE
deploy success but service can't visit

### ISSUE THREAD

**Issue by zhangwk02** [MicrosoftDocs/vsts-docs#5086]
use ssh  i deploy success 
![image](https://user-images.githubusercontent.com/38233062/62278623-0d61c880-b47b-11e9-866b-7f050a868863.png)
but when i visit the server ,is not allowed
![image](https://user-images.githubusercontent.com/38233062/62278695-2bc7c400-b47b-11e9-9ee9-58455846103e.png)

**Comment by WilliamAntonRohm** [comment]
@zhangwk02 -- Thanks for your feedback; we appreciate it. To make sure we have all the information needed to triage your issue, please let us know which topic you’re referencing, or provide more context around the general task.

**Comment by WilliamAntonRohm** [comment]
I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
