### ISSUE TITLE
"Docker" not available in Configure step 

### ISSUE THREAD

**Issue by montebhoover** [MicrosoftDocs/vsts-docs#5088]
"Docker" is not available in the Configure step unless you enable the Multi-stage pipelines in Preview features.  Please add this to the documentation.

#4670
#4739
https://developercommunity.visualstudio.com/content/problem/635703/docker-yaml-template-not-available-in-pipelines-co.html

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45ba2ebe-27c4-111b-18b4-0192d8c3fb3a
* Version Independent ID: f48fdf00-e04f-b406-93f3-20b7fad568be
* Content: [Build and push to Azure Container Registry - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/languages/acr-template?view=azure-devops)
* Content Source: [docs/pipelines/languages/acr-template.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/languages/acr-template.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @shashankbarsin
* Microsoft Alias: **shasb**

**Comment by shashankbarsin** [comment]
There is already a note in the documentation for the same - 
<img width="730" alt="image" src="https://user-images.githubusercontent.com/4594231/62624965-e9522b80-b941-11e9-8d7e-d1c1bc206789.png">
