### ISSUE TITLE
How to you restart a build agent?

### ISSUE THREAD

**Issue by RubixRevenge** [MicrosoftDocs/vsts-docs#509]
"After you install new software on a agent, you must restart the agent for the new capability to show up."  So how do you restart an agent? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 47625b86-abd5-ee15-6d61-8bcf81861b96
* Version Independent ID: be9a6174-a69b-7aed-d584-5f602fcc5eb4
* Content: [Build and Release Agents](https://docs.microsoft.com/en-us/vsts/build-release/concepts/agents/agents?view=vsts)
* Content Source: [docs/build-release/concepts/agents/agents.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/build-release/concepts/agents/agents.md)
* Service: **unspecified**
* GitHub Login: @erickson-doug
* Microsoft Alias: **alewis**

**Comment by andyjlewis** [comment]
If you're running the agent as a service, then run services.msc, and look for "VSTS Agent (name of your agent)". Right-click the entry and then choose restart. If you're running the agent interactively, then go to the PowerShell console in which it's running and press Ctrl+C to stop it and then run run.cmd to start it again.

**Comment by RubixRevenge** [comment]
Good to know. Thanks. It might be helpful if "restart" either linked to
that explanation or summarized it as you have in the email.

Henry Wyckoff
henry.wyckoff@gmail.com

**Comment by ahaleiii** [comment]
How do you restart an agent that is running as a service on Linux?

**Comment by andyjlewis** [comment]
Run the stop command and then the start command.
https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/v2-linux?view=vsts#commands

**Comment by ahaleiii** [comment]
Ah, I looked through that page, but I was searching for keyword "restart". It appears there is script to update the environment variables: `./env.sh`.

https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/v2-linux?view=vsts#service-update-environment-variables

Thanks!

**Comment by cveld** [comment]
@andyjlewis is there a way to restart an environment agent through a pipeline?

Currently I do the following:
```
cd ../../..
pwd
./env.sh
# Unfortunately the following will signal a hard stop to the running pipeline: 
./svc.sh stop
# So this command will never get fired:
./svc.sh start
```

Unfortunately the start command never gets executed.

**Comment by rdebath** [comment]
@cveld and in case anyone is interested... 

Your last command can be scheduled before the stop to run after by using the `at` command:
`echo './svc.sh start' | at 'now + 1 minute'`

Your devops job will still fail, but now after successfully completing the task.
