### ISSUE TITLE
uservoice

### ISSUE THREAD

**Issue by timschps** [MicrosoftDocs/vsts-docs#5090]
hello, the link to the artifacts uservoice is broken :(

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 078a8c96-ec59-c10b-e48e-8c5586c8cb09
* Version Independent ID: 200f5723-2404-298d-e6bb-533592a28ff3
* Content: [Azure Artifacts in Azure DevOps Services and Azure DevOps Server](https://docs.microsoft.com/en-us/azure/devops/artifacts/overview?view=azure-devops#feedback)
* Content Source: [docs/artifacts/overview.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/artifacts/overview.md)
* Product: **devops**
* Technology: **devops-artifacts**
* GitHub Login: @chasewilson
* Microsoft Alias: **phwilson**

**Comment by WilliamAntonRohm** [comment]
@chasewilson -- Chase, I've updated the document -- please review [PR 496467](https://dev.azure.com/mseng/TechnicalContent/_git/vsts-docs-pr/pullrequest/496467)

**Comment by WilliamAntonRohm** [comment]
Thank you for your feedback.  I have updated the documentation and it should be live by tomorrow.

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
