### ISSUE TITLE
License URL in sample script currently returns a 404

### ISSUE THREAD

**Issue by Zhaph** [MicrosoftDocs/vsts-docs#5091]
The link to the License file in the source code currently returns a 404:

https://www.microsoft.com/resources/sharedsource/licensingbasics/sharedsourcelicenses.mspx

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77731c06-e4fd-8125-0daf-870c9ccedd3f
* Version Independent ID: 0d5c338d-80f9-c64e-b675-bf7b4eb8e32b
* Content: [Use a PowerShell script to customize your build pipeline - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/scripts/powershell?view=azure-devops)
* Content Source: [docs/pipelines/scripts/powershell.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/scripts/powershell.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by chasewilson** [comment]
@Zhaph Thanks for the heads up! I'll update with appropriate licensing info or remove the null link
