### ISSUE TITLE
Release pipelines link point to Build pipelines

### ISSUE THREAD

**Issue by nicos99** [MicrosoftDocs/vsts-docs#5094]
At the begining of this article, under "see the following resources", there are a links list table. In the "DevOps permissions" list, the link "Release pipelines" point to the same page than "Build pipelines" : is it correct ?

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 68686c2b-c69a-d9e4-3e21-a46d231b649c
* Version Independent ID: 049659da-1772-3166-f909-4feeb8a97730
* Content: [What are all the default permissions and groups? - Azure DevOps](https://docs.microsoft.com/fr-fr/azure/devops/organizations/security/permissions?view=azure-devops&tabs=preview-page#iteration-path-object-level)
* Content Source: [docs/organizations/security/permissions.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/security/permissions.md)
* Product: **devops**
* Technology: **devops-security**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by WilliamAntonRohm** [comment]
@KathrynEE -- I've updated the documentation and combined these links -- please review [PR 496468](https://dev.azure.com/mseng/TechnicalContent/_git/vsts-docs-pr/pullrequest/496468)

**Comment by WilliamAntonRohm** [comment]
Thank you for your feedback.  I have updated the documentation and it should be live by tomorrow.
