### ISSUE TITLE
§ "Iteration Path" confusion with "area"

### ISSUE THREAD

**Issue by nicos99** [MicrosoftDocs/vsts-docs#5096]
In § "Iteration Path (object-level)", the 2 sentenses "Multiple teams may contribute to a project. When that's the case, you can set up teams that are associated with an area. Permissions for the team's work items are assigned by assigning permissions to the area." referes to the area concept (same sentenses as in § "Area path (object-level)") whereas here we should talk about iteration path associated to the team, no?

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 68686c2b-c69a-d9e4-3e21-a46d231b649c
* Version Independent ID: 049659da-1772-3166-f909-4feeb8a97730
* Content: [What are all the default permissions and groups? - Azure DevOps](https://docs.microsoft.com/fr-fr/azure/devops/organizations/security/permissions?view=azure-devops&tabs=preview-page#iteration-path-object-level)
* Content Source: [docs/organizations/security/permissions.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/security/permissions.md)
* Product: **devops**
* Technology: **devops-security**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@nicos99 - Thank you for the feedback. You are correct, I'm removing the text that discusses area paths under the Iteration section.
