### ISSUE TITLE
Arguments 'Contents', unclear about the folder pattern to use

### ISSUE THREAD

**Issue by nicos99** [MicrosoftDocs/vsts-docs#5097]
In § 'Arguments' / 'Contents', we have "The pattern is used to match only file paths, not folder paths. So you should specify patterns such as **\bin\** instead of **\bin\**." --&gt; I can't see the pattern difference !?!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 81f02378-b85b-d3a4-d3c8-f07d935367da
* Version Independent ID: fab57f76-35d2-4024-6f7f-1740d7b24743
* Content: [Copy Files task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/copy-files?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/tasks/utility/copy-files.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/utility/copy-files.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @vtbassmatt
* Microsoft Alias: **macoope**

**Comment by vtbassmatt** [comment]
🤦‍♂ I think I typo'd that fixing another bug.
