### ISSUE TITLE
Run stage only if previous stage 'SucceededWithIssues'?

### ISSUE THREAD

**Issue by liamfoneill** [MicrosoftDocs/vsts-docs#5100]
Would it be possible to included a condition in the docs to illustrate how a stage can be set to run only if the previous stage 'succeededWithIssues' but not 'Succeeded'? In the Visual Designer UI, the Checkbox only allow you to included both conditions, but not 'SucceededWithIssues' without 'Succeeded'

![image](https://user-images.githubusercontent.com/1243172/62316858-5ff9af80-b490-11e9-8980-686efcbf4a38.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77c58a78-a567-e99a-9eb7-62dddd1b90b6
* Version Independent ID: 680a79bc-11de-39fc-43e3-e07dc762db18
* Content: [Expressions - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/expressions?view=azure-devops#feedback)
* Content Source: [docs/pipelines/process/expressions.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/expressions.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by msebolt** [comment]
@liamfoneill Thank you for the feedback.

Is the `Failed` result sufficient for your needs?

Alternatively, if you are suggesting the `Failed` result be included in the Visual Designer UI, for product features we generally recommend using the [VSTS forums](https://developercommunity.visualstudio.com/spaces/21/index.html) where it could be voted on, etc.

**Comment by msebolt** [comment]
Please comment below if there are any further issues.
