### ISSUE TITLE
No "Azure Stack" Environment

### ISSUE THREAD

**Issue by eszych** [MicrosoftDocs/vsts-docs#5102]
I tried to create a new Azure Resource Manager Service connection as described. Though in the drop-down there is only "AzureCloud", "AzureChinaCloud", "AzureUSGoverment" and "AzureGermanCloud" - but no "AzureStack"...
Is it a bug or afeature?!?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 26477658-d1ad-a4c9-0d9e-59aeead8a71e
* Version Independent ID: 45dfbd24-b9f4-fdf2-48a2-5648220204fe
* Content: [Connect to Microsoft Azure - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/library/connect-to-azure?view=azure-devops#feedback)
* Content Source: [docs/pipelines/library/connect-to-azure.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/library/connect-to-azure.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by RoopeshNair** [comment]
It is a bug, we are in the process of deploying the fix. Please stay tuned. Apologies for the inconvenience

**Comment by RoopeshNair** [comment]
@eszych. This should be deployed by now. Let me know if you are still facing the issues.
