### ISSUE TITLE
which feed do they go to?

### ISSUE THREAD

**Issue by sasanmcp** [MicrosoftDocs/vsts-docs#5103]
when you publish the artifact, which feed do they go to? how can I define that?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 861ce7a5-4fa4-55f1-2c97-46a9cc6a2f66
* Version Independent ID: bdf954b9-9bbe-8b34-b674-71ad8153519d
* Content: [Publish and consume artifacts in pipelines - Azure Pipelines and TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/pipeline-artifacts?view=azure-devops&tabs=yaml#feedback)
* Content Source: [docs/pipelines/artifacts/pipeline-artifacts.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/artifacts/pipeline-artifacts.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @alexmullans
* Microsoft Alias: **amullans**

**Comment by msebolt** [comment]
@sasanmcp  Thank you for the question.

The `Publish` you're referring to is for file output only.  

Please refer to the feed-specific documentation (for instance, [Publish to Nuget feeds](https://docs.microsoft.com/azure/devops/pipelines/artifacts/nuget?toc=%2Fazure%2Fdevops%2Fartifacts%2Ftoc.json&view=azure-devops&tabs=yaml#publish-your-packages)) on how to specify specific feed information, such as feed URL, etc.
