### ISSUE TITLE
issecret not compatible with isOutput

### ISSUE THREAD

**Issue by Advin24** [MicrosoftDocs/vsts-docs#5107]
My builds are "failing" ( despite all Jobs succeeding ) if I utilize the variable logger with both issecret=true and isOutput=true. 

I do not see any documentation within this page, nor the Logging Command documenation ( https://github.com/microsoft/azure-pipelines-tasks/blob/master/docs/authoring/commands.md#task-logging-commands ) to potentially resolve.

As well, there seems to be an issue open - however the communication channel has stopped before potential resolutions were discussed: https://developercommunity.visualstudio.com/content/problem/593141/using-vars-in-multi-stage-pipeline-can-fail-withou.html

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd7e0bd3-1f7d-d7b6-cc72-5ef63c31b46a
* Version Independent ID: dae87abd-b73d-9120-bcdb-6097d4b40f2a
* Content: [Variables - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch#set-a-multi-job-output-variable)
* Content Source: [docs/pipelines/process/variables.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/variables.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by MisinformedDNA** [comment]
Can expressions like `$[ dependencies.A.outputs['job1.setvarStep.myOutputVar'] ]` be used directly or do they always need to be assigned to a variable first? When I tried using it directly in some places, I would just get the expression back, not the value.

**Comment by juliakm** [comment]
@Advin24 - Sorry for the delay on this. Are you still running into this problem? I used the minimal YAML from the [issue report](https://developercommunity.visualstudio.com/content/problem/593141/using-vars-in-multi-stage-pipeline-can-fail-withou.html) and it ran successfully.
