### ISSUE TITLE
Extension JSON needs to specify categories

### ISSUE THREAD

**Issue by asklar** [MicrosoftDocs/vsts-docs#5109]
When using the vss-extension.json as described on this page, the tool throws an error:
error: Error: There were errors with your extension. Address the following and re-run the tool.
error: One or more 'categories' must be provided.

In order to fix this you need to specify a category as described here: https://docs.microsoft.com/en-us/azure/devops/extend/develop/manifest?view=azure-devops&viewFallbackFrom=vsts

For example:
        "categories" : [
            "Azure Boards"
        ],

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bbe9c938-dde5-4eba-6e09-6e43ef0e8ee5
* Version Independent ID: 53f9961e-1c31-1080-1699-4ef901939b19
* Content: [Add a dashboard widget](https://docs.microsoft.com/en-us/azure/devops/extend/develop/add-dashboard-widget?view=azure-devops#feedback)
* Content Source: [docs/extend/develop/add-dashboard-widget.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/extend/develop/add-dashboard-widget.md)
* Product: **devops**
* Technology: **devops-ecosystem**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @asklar, Thanks for this info. I'll look into it and will be in touch. Thanks and have a great weekend!

**Comment by chcomley** [comment]
I've published an update and linked the PR to this issue! Please let us know whether you have any further feedback on this. Thank you!
