### ISSUE TITLE
Version does not have a latest option

### ISSUE THREAD

**Issue by jrm346** [MicrosoftDocs/vsts-docs#5112]
Hi guts I use this task to download a package from our devops feed. This is super useful but there is one thing that really annoys me. There is no option to select the 'latest' version. As such every time my package changes version I have to manually go into the pipeline that uses this task and change the version number to the latest one. could you please add a 'latest' option to the version argument.

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ff8354ee-807f-0c1f-8e5b-9303c4591c60
* Version Independent ID: 1fd42523-8504-76cf-deec-26c5fccd0109
* Content: [Download Package task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/download-package?view=azure-devops#feedback)
* Content Source: [docs/pipelines/tasks/utility/download-package.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/utility/download-package.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @chasewilson
* Microsoft Alias: **phwilson**

**Comment by jporcenaluk** [comment]
I also agree this could be very helpful! Using the release tags in any form could be helpful, or version wildcards, or both!

**Comment by WilliamAntonRohm** [comment]
It looks like you've encountered an issue with the product itself, rather than an issue with the documentation. To make sure it gets in front of the right people, please [submit your bug]( https://developercommunity.visualstudio.com/content/problem/post.html?space=21) here.

**Comment by XmlmXmlmX** [comment]
@WilliamAntonRohm Not a bug: https://developercommunity.visualstudio.com/content/problem/718698/download-package-task-missing-latest-version.html
