### ISSUE TITLE
Creating Project wikis

### ISSUE THREAD

**Issue by Yu-457** [MicrosoftDocs/vsts-docs#5118]
Hi, 
could you update the documentation on how to create project wikis? 
we've been wondering how to create multiple ones, this surely is prossible. 
But we couldnt figure out how since the article only describes the setup of the very first wiki when theres still the button for "new wiki"
https://docs.microsoft.com/en-us/azure/devops/project/wiki/wiki-create-repo?view=azure-devops

Best Regards,

**Comment by chcomley** [comment]
Hi @Yu-457, Thanks for reaching out! I've added a note to the article, so this is explained a bit further. It should be live by this afternoon. In the meantime, if you want to provision more wikis, then you need to [publish code as a wiki](https://docs.microsoft.com/en-us/azure/devops/project/wiki/publish-repo-to-wiki?view=azure-devops). You can set up multiple wiki repos within a single project.
Thank you!
