### ISSUE TITLE
What about refunding mistaken purchases?

### ISSUE THREAD

**Issue by paulharker** [MicrosoftDocs/vsts-docs#512]
This document does not describe how to initiate request for refund or disputes.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4136c15d-672e-44b0-b42b-16b877deb381
* Version Independent ID: 16df8860-d655-b092-2f8b-aaa5d1b2e955
* Content: [Troubleshooting getting extensions for VSTS](https://docs.microsoft.com/en-us/vsts/marketplace/faq-extensions?view=vsts#purchases--billing)
* Content Source: [docs/marketplace/faq-extensions.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/marketplace/faq-extensions.md)
* Service: **unspecified**
* GitHub Login: @erickson-doug
* Microsoft Alias: **elbatk**

**Comment by harishkragarwal** [comment]
You may cancel your purchase immediately after purchase. Also, for the short duration that you may be charged for, one can create an Azure support tickets to refund the amount.

**Comment by elbatk** [comment]
Going ahead and closing this as it seems to have been answered - @paulharker feel free to reach back out on this issue if you have any more questions.
