### ISSUE TITLE
pwsh is not a keyword

### ISSUE THREAD

**Issue by randyram-at-ms** [MicrosoftDocs/vsts-docs#5120]
I had to use the PowerShell@2 task specifically, got an error with pwsh

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd7e0bd3-1f7d-d7b6-cc72-5ef63c31b46a
* Version Independent ID: dae87abd-b73d-9120-bcdb-6097d4b40f2a
* Content: [Variables - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch#share-variables-across-pipelines)
* Content Source: [docs/pipelines/process/variables.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/variables.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by chasewilson** [comment]
Hi @randyram-at-ms, Thanks for the feedback. The [PowerShell Task Documentaion](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/powershell?view=azure-devops) states that using the `pwsh` keyword runs PowerShell COre. Do you have PowerShell Core installed on the build agent? if not, you can also use the `powershell` keyword to run Windows PowerShell

**Comment by randyram-at-ms** [comment]
Thanks, Chase, that was the issue, no pscore on the build agent.

**Comment by WilliamAntonRohm** [comment]
I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
