### ISSUE TITLE
Insufficient details on generic provider for k8s environment

### ISSUE THREAD

**Issue by mmisztal1980** [MicrosoftDocs/vsts-docs#5121]
[Enter feedback here]
The provided detail on Service Account / Role Binding is insufficient in order to configure the Environment using a generic provider from scratch.

It'd be beneficial if :
- The information would include the required privileges for the ServiceAccount.
- Code samples were provided

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7730ae4d-4101-9c83-1823-4ff43ff161ce
* Version Independent ID: 20a7e263-4819-783e-c984-c4f3b459e22f
* Content: [Environment - Kubernetes resource - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/environments-kubernetes?view=azure-devops#feedback)
* Content Source: [docs/pipelines/process/environments-kubernetes.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/environments-kubernetes.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @shashankbarsin
* Microsoft Alias: **shasb**

**Comment by shashankbarsin** [comment]
@mmisztal1980 a RoleBinding with edit cluster role is required to be associated with the ServiceAccount as environments and Kubernetes resource are used for deploying manifests to Kubernetes namespace. I do acknowledge the feedback though. I have included details on RoleBinding in the next set of documentation updates.
