### ISSUE TITLE
tfx extension init produces invalid package

### ISSUE THREAD

**Issue by asklar** [MicrosoftDocs/vsts-docs#5123]
When uploading the sample extension that 'tfx extension init' creates, you get an error on the marketplace saying: 

The stated category 'Other' is no longer supported. Refer to the categories listed at https://aka.ms/extensioncategories and republish using one or more amongst them.

The fix is to edit the azure-devops-extension.json file. However I expect that tfx extension init creates a valid sample extension.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 14955ee9-29f2-46fe-3a8d-a42666f53ffc
* Version Independent ID: 5d417cd0-a671-ee30-8fca-5f8b0addd328
* Content: [Develop a web extension for Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/extend/get-started/node?view=azure-devops)
* Content Source: [docs/extend/get-started/node.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/extend/get-started/node.md)
* Product: **devops**
* Technology: **devops-ecosystem**
* GitHub Login: @willsmythe
* Microsoft Alias: **wismythe**

**Comment by WilliamAntonRohm** [comment]
It looks like you've encountered an issue with the product itself, rather than an issue with the documentation. To make sure it gets in front of the right people, please [submit your bug]( https://developercommunity.visualstudio.com/content/problem/post.html?space=21) here.
