### ISSUE TITLE
Download Agent Link

### ISSUE THREAD

**Issue by gtordai** [MicrosoftDocs/vsts-docs#5126]
https://dev.azure.com/{your_organization}/_settings/agentpools

"Click the pool on the left side of the page and then click Roles."  Which Pool ? "Roles" is missing from page
"Click Download agent"  Link is missing from page

Instead I had to first select Default Pool (non-evident), then click New Agent, then the Download was available

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43799c5d-2f13-cc76-a1c0-a3f850e16d4e
* Version Independent ID: 97a5b73f-faf7-f9c0-9269-fc79984616d6
* Content: [Deploy a Azure Pipelines agent on Windows - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/v2-windows?view=azure-devops#feedback)
* Content Source: [docs/pipelines/agents/v2-windows.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/agents/v2-windows.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by SahanaPrabhakar** [comment]
Have been struggling for last 30 mins to figure out the download link. Played around with permissions until I saw this. Thank you. This is really hidden. Needs to be as per the docs.

**Comment by steved0x** [comment]
@gtordai @SahanaPrabhakar We just published an update to the docs where we replaced that table of URLs with screenshots and steps showing how to get to Agent Pools - can you take a look and let me know if that is helpful, or should we add some additional clarification?

**Comment by gabrieljoelc** [comment]
@steved0x Are you referring to the 2 screenshots in [this section](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/agents/v2-windows.md#azure-pipelines)? I don't see "Download agent" in the screenshots.
