### ISSUE TITLE
"Basic + Test Plans" access level doesn't exist in azure dev-ops' user management

### ISSUE THREAD

**Issue by vdheuvel** [MicrosoftDocs/vsts-docs#5130]
You write "Azure Test Plans uses an access level called Basic + Test Plans, which is available from Azure DevOps."
I cannot find this option. From organization settings -&gt; manage users -&gt; select myself -&gt; change access level -&gt; a pane on the right pops up with the following options: Basic; Stakeholder; Visual Studio subscriber. Basic + Test plans is not there. 

Or should I be looking somewhere else?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 92d59beb-f1ee-75d6-0d8b-5a5612003b23
* Version Independent ID: 0c875a53-b71b-86e1-00d4-8f453147b786
* Content: [Permissions and access for manual testing - Azure Test Plans](https://docs.microsoft.com/en-us/azure/devops/test/manual-test-permissions?view=azure-devops#feedback)
* Content Source: [docs/test/manual-test-permissions.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/test/manual-test-permissions.md)
* Product: **devops**
* Technology: **devops-test**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by PuffTMD** [comment]
I've also come across this issue, I have started a trial but there doesn't seem to be an option to assign this to a user

**Comment by harishkragarwal** [comment]
Hello, https://docs.microsoft.com/en-us/azure/devops/organizations/billing/buy-basic-plus-test-plans?view=azure-devops talks about purchasing/decreasing the number of 'Basic + Test Plans' access levels. Once done, you can assign them to appropriate users.
