### ISSUE TITLE
Using Area ID in WIT rules

### ISSUE THREAD

**Issue by mcrawley198** [MicrosoftDocs/vsts-docs#5131]
I was wondering why we can't use the Area ID or Area Path, which visible at all, in certain WIT rules (e.g. if this type of WIT is created, please set the area ID to X)

This would be very helpful in streamlining the creation of certain WIT's to go to the correct team.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d41d9341-94a7-4df3-ea46-d76c5c39c14d
* Version Independent ID: 777f7374-ce28-d9d7-9d64-ba44603693c7
* Content: [Define area paths for a project - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/organizations/settings/set-area-paths?view=azure-devops&tabs=browser)
* Content Source: [docs/organizations/settings/set-area-paths.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/settings/set-area-paths.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@mcrawley198 - Thank you for your inquiry.  You can suggest this as a new feature in our [Developer Community page](https://developercommunity.visualstudio.com/spaces/21/index.html).
