### ISSUE TITLE
hosted macos doesn't fire

### ISSUE THREAD

**Issue by PawelHaracz** [MicrosoftDocs/vsts-docs#5134]
Hi,
I have been waiting for 4 days to run my build in hosted macos mojave. i have only this one pipeline in my devops, Is it unavalibity in west europe or is it a bug?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 99af681d-41ad-da15-0b72-08b5cd5a11ac
* Version Independent ID: 2fa0df36-a437-8cbb-b019-b49b31b1e116
* Content: [Microsoft-hosted agents for Azure Pipelines - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops)
* Content Source: [docs/pipelines/agents/hosted.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/agents/hosted.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @joebourneMS
* Microsoft Alias: **jobourne**

**Comment by msebolt** [comment]
@PawelHaracz Thank you for the feedback.

Unfortunately West Europe has known issues (see note under [Agent IP ranges](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops#agent-ip-ranges)).

Have you adjusted these settings for your solution?

**Comment by msebolt** [comment]
Please comment below if there are any further issues.
