### ISSUE TITLE
What about Project troublesshoothing?

### ISSUE THREAD

**Issue by hermesmsft** [MicrosoftDocs/vsts-docs#5135]
I've successfully integrated Azure DevOps with Excel, however the Team tab doesn't appear in the Project ribbon.

These instructions work well for Excel, but they don't for Project, specifically the regedit section.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bf4c6dd3-d2d2-0d41-9958-d3f7d85b5c05
* Version Independent ID: e5e4a28f-30b8-0dab-b94b-d94fe6d341fe
* Content: [TFS-Office integration issues - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/backlogs/office/tfs-office-integration-issues?view=azure-devops#feedback)
* Content Source: [docs/boards/backlogs/office/tfs-office-integration-issues.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/boards/backlogs/office/tfs-office-integration-issues.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by nschonni** [comment]
Project is deprecated. EX: the note on https://docs.microsoft.com/en-us/azure/devops/boards/backlogs/office/schedule-projects-using-microsoft-project?toc=%2Fazure%2Fdevops%2Fboards%2Ftoc.json&bc=%2Fazure%2Fdevops%2Fboards%2Fbreadcrumb%2Ftoc.json&view=tfs-2018&viewFallbackFrom=azure-devops
> Starting with Visual Studio 2019, the Team Foundation plug-in for Office is deprecating support for Microsoft Project. Project integration and the TFSFieldMapping command is not supported for Azure DevOps Server 2019 nor for Azure DevOps Services. You can continue to use Microsoft Excel.

**Comment by hermesmsft** [comment]
Wow, this was quick! Awesome response time.

I see, now if that’s the case, wouldn’t it be convenient to update the documentation stating that?

I spent 2 hours to get to this point and troubleshooting, just to find out it no longer applies for Project.

Thank you.

Hermes López


Offering Lead
Support for Mission Critical

**Comment by KathrynEE** [comment]
@hermesmsft - Thank you for your inquiry, and apologies for any confusion on what is supported. With the latest version of Visual Studio 2019, the Team Foundation Add-in no longer supports Azure DevOps integration with Project or Power Point Storyboarding. I am working to update the articles to make that clearer.

**Comment by StavroulaSsi** [comment]
Hi, for me it is still not clear what is really deprecated here. Many colleagues of mine use this Team add-in clicking to "New List" to import query results to Excel. Is this for example deprecated? What means "is deprecating support for Microsoft Project" and "Project integration and the TFSFieldMapping command is not supported"? However, "we can continue to use Microsoft Excel", but the question is, will we have the option to connect Excel to Azure DevOps Server? Could someone please explain it? Thank you.
