### ISSUE TITLE
Is it possible to create a wiki for the collection scope?

### ISSUE THREAD

**Issue by RubixRevenge** [MicrosoftDocs/vsts-docs#514]
The wiki instructions shown here (https://docs.microsoft.com/en-us/vsts/collaborate/wiki-create-repo?view=vsts) are accurate for creation of a project-scope wiki.

Is it possible to create a collection-scope wiki to contain a general wiki for content that applies to all projects in the collection? I don't know whether this is supported at all or if it is and isn't documented.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 889cc132-e8ed-ea22-cfff-51ee434fb113
* Version Independent ID: 47e62550-289d-e89a-1122-2a6319dc2711
* Content: [Create a wiki for your team project - VSTS & TFS 2018](https://docs.microsoft.com/en-us/vsts/collaborate/wiki-create-repo?view=tfs-2018)
* Content Source: [docs/collaborate/wiki-create-repo.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/collaborate/wiki-create-repo.md)
* Service: **unspecified**
* GitHub Login: @erickson-doug
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@RubixRevenge - Thank you for your inquiry. Account-wide wiki is not a supported feature at this time. You can add your vote to this UserVoice suggestion, https://visualstudio.uservoice.com/forums/330519-visual-studio-team-services/suggestions/31921501-account-wide-wiki.
