### ISSUE TITLE
How to charge for Artifact?

### ISSUE THREAD

**Issue by liushuanggang** [MicrosoftDocs/vsts-docs#5146]
According to the document https://azure.microsoft.com/en-us/pricing/details/devops/azure-devops-services/

We could to know that if Azure Artifacts includes a free usage tier of 2 GB. Any usage below this level isn’t billed to your subscription. Above this limit, we charge you for your actual usage. The charge is 2 GB free, then starting at $2 per GB **/mo**.

Now the question is:

1. Is $2 per GB/mo settled by natural month? Or is it a one-month settlement based on the 30 days after the start of the day I applied?

2. If I applied for 2GB of extra space, but after using it for a while I cleared them from my feed, how is it billed after it is cleared?

Thanks.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b5531731-8bd5-b178-9307-f01b3d2f23b3
* Version Independent ID: 8dea3b69-ad79-5045-3820-4a83a0bc4ce0
* Content: [Sign up for Azure Artifacts](https://docs.microsoft.com/en-us/azure/devops/artifacts/sign-up-azure-artifacts?view=azure-devops#feedback)
* Content Source: [docs/artifacts/sign-up-azure-artifacts.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/artifacts/sign-up-azure-artifacts.md)
* Product: **devops**
* Technology: **devops-artifacts**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @liushuanggang, Thanks for reaching out. 

We bill daily, based on usage above the free amount. If you delete data, which drops you back under the free amount, you should see it reflected the next day (and charges are stopped). 

We do charge for the Recycle Bin – where packages are “stored” for 30 days after deletion, in case they need to be restored. So to see usage freed up, the deleted packages will have to be removed from the bin as well. We don't recommend deleting a feed. We keep storage around for 30 days, but there's no UI to restore/permanently delete, so some customers have increased their limit due to this.

Please let me know if you have any further questions. Thank you!

**Comment by liushuanggang** [comment]
Hi @chcomley, Thanks for your quickly reply. Your reply make me clear my second question, but I still confused about my first question:

> Is $2 per GB/mo settled by natural month? Or is it a one-month settlement based on the 30 days after the start of the day I applied?

You said you bill daily. That means if I use 3GB, I will pay for an extra 1GB. It is no problem at all. But if I just used extra space for up to 15 days, that means I only need to pay $1? No matter which day of the month I start applying and ending the use of my feed.

That means your pricing is $2  per GB month, but the actual settlement is based on daily?

**Comment by chcomley** [comment]
Hi @liushuanggang, 

Billing is set up by what you’re referring to as a “natural month."

While we charge monthly, we calculate the billed amount daily. We take your daily usage, take the monthly amount that would be charged, and divide that by 31. $1 per GB of storage per month for your first 10 (after the 2 free) GB of storage.

So, if you used 3GB of storage for one day, you'd be billed 1GB=$1/31 = 3.2 cents. If you had 3GB of storage for 15 days, then your bill would show 3.2 cents x 15 = .48 cents.

**Comment by liushuanggang** [comment]
@chcomley, Got it! Thanks for your detailed reply.
