### ISSUE TITLE
How to solve that "interesting problem"?

### ISSUE THREAD

**Issue by FixRM** [MicrosoftDocs/vsts-docs#5147]
@ethomson, can you please share more details on how do you do delivery of hot-fixes? Lets say we have fixed this 2 branches, now different rings are need to be patched with different versions. Is it a manual process? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d1235ec4-e7e9-b0c2-8f1f-ee9682175a05
* Version Independent ID: a473750a-fbb6-4eed-e0e6-34e8a5009507
* Content: [Release Flow - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/learn/devops-at-microsoft/release-flow)
* Content Source: [https://mseng.visualstudio.com/DefaultCollection/TechnicalContent/_git/devops-learn-pr?path=%2fdocs%2fdevops-at-microsoft%2frelease-flow.md&version=GBlive&_a=contents](https://mseng.visualstudio.com/DefaultCollection/TechnicalContent/_git/devops-learn-pr?path=%2fdocs%2fdevops-at-microsoft%2frelease-flow.md&version=GBlive&_a=contents)
* Product: **devops**
* Technology: **devops-learn**
* Git Login: **samgu**
* Microsoft Alias: **ethomson**

**Comment by WilliamAntonRohm** [comment]
@FixRM -- Artem, thanks for your feedback; we appreciate it. To make sure we have all the information needed to triage your issue, please let us know which topic you’re referencing, or provide more context around the general task.

**Comment by FixRM** [comment]
Hello, the question is about Moving On topic. It is said: "This raises an interesting problem: if we need to hotfix a change in the middle of a deployment, we may need to hotfix two different releases: the sprint 129 release and the sprint 130 release". But there's no explanation how does it is solved

**Comment by WilliamAntonRohm** [comment]
@FixRM -- Artem, thank you for clarifying your feedback.

**Comment by Pardiess** [comment]
Hello, I am also most interested in an answer to solve the "interesting problem". Kindly comment.

**Comment by lexslimx** [comment]
@FixRM  In my understanding, always creating a hotfix branch from master resolves this in these steps: 1. Create a hotfix branch from master, 2. code review it 3. complete a pull requests and cherry pick the changes and merge to both release branches. Remember that these two release branches will eventually be discarded in favour of the next release which will be branched from master.

**Comment by marcpopMSFT** [comment]
We reuse the existing release branches.  In the example in this document, I would check in the hotfix to both the 129 and 130 release branches.  Then we would deploy both branches but to different rings.  The 130 release branch would redeploy with the hotfix to all rings that had already been upgraded to 130.  129 would redeploy with the hotfix to any rings that hadn't yet moved to 130.  We have enough volume of hotfixes that we're redeploying almost daily on most rings.  

I've suggested some updates to this article to our documentation team that hopefully they can incorporate to cover this.

**Comment by steved0x** [comment]
Fixed in: https://github.com/MicrosoftDocs/devops-learn-pr/pull/10 and it should be live soon.
