### ISSUE TITLE
Disabled user 

### ISSUE THREAD

**Issue by ri-we** [MicrosoftDocs/vsts-docs#5149]
When the user is removed, the pat token is revoked. What happens if the user is disabled?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 54d83d2a-9d6a-b926-7951-4f8a81dda55d
* Version Independent ID: e8df73a8-1266-099c-b8e6-db456a971ef6
* Content: [Revoke personal access tokens for organization users - Admin - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/admin-revoke-user-pats?view=azure-devops#feedback)
* Content Source: [docs/organizations/accounts/admin-revoke-user-pats.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/accounts/admin-revoke-user-pats.md)
* Product: **devops**
* Technology: **devops-accounts**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @ri-we, Thanks for reaching out! When a user is disabled, the PAT token is also revoked, however there is a latency (up to an hour) before the PAT stops working after the disable/delete happens in Azure AD.

**Comment by ri-we** [comment]
Thanks, please add this info to the docs page.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
