### ISSUE TITLE
Cannot clone from another TFS Git repo v 2017.3

### ISSUE THREAD

**Issue by sprocter047** [MicrosoftDocs/vsts-docs#5152]
When attempting to use the import feature after creating a new Git repo in TFS, you cannot import from another GIT repo.  I have tried with and without authentication and it errors every time.  I have a git repo that I would like to use a template for others to create projects off of.  We are on TFS 2017.3 on prem.
![image](https://user-images.githubusercontent.com/21243330/62563977-a9a81880-b849-11e9-9288-7850ddbfd314.png)

**Comment by WilliamAntonRohm** [comment]
@sprocter047 Thanks for your feedback; we appreciate it. To make sure we have all the information needed to triage your issue, please let us know which topic you’re referencing, or provide more context around the general task.

**Comment by WilliamAntonRohm** [comment]
I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
