### ISSUE TITLE
helm upgrade command documentation wrong

### ISSUE THREAD

**Issue by jonnylangefeld** [MicrosoftDocs/vsts-docs#5154]
One of the parameters is `wait` in the documentation. But really what is needed is `waitForExecution` (like the other commands)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fc7eeb7f-4e6b-8fee-1d7f-582cfb018b02
* Version Independent ID: 00fb3082-1069-9060-012c-0b6d75ef120b
* Content: [Package and Deploy Helm Charts task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/helm-deploy?view=azure-devops#feedback)
* Content Source: [docs/pipelines/tasks/deploy/helm-deploy.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/deploy/helm-deploy.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @thomps23
* Microsoft Alias: **shasb**

**Comment by WilliamAntonRohm** [comment]
@thomps23 -- I've updated the document -- please review [PR 496476](https://dev.azure.com/mseng/TechnicalContent/_git/vsts-docs-pr/pullrequest/496476)

**Comment by WilliamAntonRohm** [comment]
Thank you for your feedback.  I have updated the documentation and it should be live by tomorrow.
