### ISSUE TITLE
Better quality graphics

### ISSUE THREAD

**Issue by ctahok** [MicrosoftDocs/vsts-docs#5158]
Hello,

Can you please replace the picture at "Live-site management in Azure DevOps is broken into three distinct tracks, shown as follows:" with a higher resolution one as this one is barely readable.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 52eb9f91-b952-afb6-6d17-d7092f46440d
* Version Independent ID: bb9113a5-8b8b-b20b-9c6f-09a57f53ba7c
* Content: [Azure DevOps - Data Protection](https://docs.microsoft.com/en-us/azure/devops/organizations/security/data-protection?view=azure-devops)
* Content Source: [docs/organizations/security/data-protection.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/security/data-protection.md)
* Product: **devops**
* Technology: **devops-whitepapers**
* GitHub Login: @mlearned
* Microsoft Alias: **mlearned**

**Comment by chcomley** [comment]
Hey there @ctahok, Better late than never, I've just published a new image that's easily readable. Thanks very much for your feedback. This shall be live sometime today.
