### ISSUE TITLE
Pricing calculator doesn't seem to match information on this page

### ISSUE THREAD

**Issue by leyshon** [MicrosoftDocs/vsts-docs#5160]
The information on this page makes it clear that if you purchase 1 parallel job then you will have 1 parallel job. The pricing calculator though seems to think that the first 2 parallel jobs cost the same as any additional 1 parallel job ($40 according to the current prices)

If you go to https://azure.microsoft.com/en-us/pricing/details/devops/azure-devops-services/ and under Azure Pipelines, Microsoft-Hosted select 2 jobs you'll see the price shown is $40 (the same as the cost for 1 additional parallel job). Is there a special pricing structure for the first 2 jobs or is the calculator just failing to account for the fact that if you buy 1 job you lose the free job?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c6a488b-88f6-dff6-e2ee-402167e17ad4
* Version Independent ID: 9a4dedda-e82c-2833-f28c-5ab346fb1b38
* Content: [Parallel jobs in Azure Pipelines - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/licensing/concurrent-jobs?view=azure-devops#feedback)
* Content Source: [docs/pipelines/licensing/concurrent-jobs.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/licensing/concurrent-jobs.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @chasewilson
* Microsoft Alias: **phwilson**

**Comment by msebolt** [comment]
@leyshon  Thank you for the question.

Sorry for the confusion, they are considering the free tier job to count as 1 job in any case since the minutes reset every month.  If you upgrade this job for $40/month, you will technically have 2 jobs for $40/month, since you will now have access to another free tier job (even if you have to wait until the next month to reset the minutes).

Apparently **free** at Microsoft is a really big thing.

**Comment by leyshon** [comment]
@msebolt The document states

```
Note

When you purchase your first Microsoft-hosted parallel job, the number of parallel jobs you have in the organization still stays at 1. This purchase only removes the limits on the free parallel job that you have. To be able to run two jobs concurrently, you will need to purchase two parallel jobs.
```
Your statement that if you upgade the free job you will technically have 2 jobs seems to contradict this. If what you say is correct then that note needs removing/amending.

**Comment by msebolt** [comment]
@leyshon  Thank you for the response.

I don't quite see a contradiction, but have redacted "purchase" from the note to leave open the option of second free tier.  Change under review.

**Comment by Sam-Martin** [comment]
I for one am very confused.
@leyshon is quoting.
>  To be able to run two jobs concurrently, you will need to purchase two parallel jobs.
But @msebolt is saying
> If you upgrade this job for $40/month, you will technically have 2 jobs 
That seems a direct contradiction to me. Having upgraded, will I be able to run two or one jobs in parallel?

**Comment by msebolt** [comment]
@Sam-Martin  The note has been changed to:

To be able to run two jobs concurrently, you will need two parallel jobs.

...whether you decide to purchase both or purchase one and keep the other in Free Tier is up to you.

**Comment by Sam-Martin** [comment]
But doesn't that mean that paying for one and paying for two is the same thing? What's the advantage to purchasing both?

**Comment by msebolt** [comment]
Either note...

> To be able to run two jobs concurrently, you will need two parallel jobs. 

> To be able to run two jobs concurrently with unlimited time, you will need to purchase two parallel jobs.

...provide accurate descriptions of the service, whereas the issue with the original note...

> To be able to run two jobs concurrently, you will need to purchase two parallel jobs.

...assumes you want or need unlimited time.

The advantage to purchasing both is to get unlimited time with both.

**Comment by leyshon** [comment]
Just to be clear, if I purchase 1 job, you are saying that I will be able to run two jobs at the same time because I can run one on the purchased job and one on the free tier job? 

I've just tried this and I'm unable to do so. The UI also makes no mention of the free tier job now that I have purchased a job. In fact, it seems to be much like the documentation I quoted said. Purchasing a job simply removed the limitation on the free tier. It didn't provide me with the ability to run two jobs concurrently.

![screenshot-paralleljobs](https://user-images.githubusercontent.com/14804737/62924202-84665d80-bda7-11e9-9c87-c802999113ab.png)

**Comment by msebolt** [comment]
@leyshon  If this is the case, then the documentation will need to be changed, primarily the marketing calculator referenced initially.  

Abandoned note re-wording and re-assigning this to the author.

**Comment by chasewilson** [comment]
@leyshon sorry for the late response. The documentation is correct. I know the terminology is a little confusing. Honestly, it took me a bit to parse through it too. Unfortunately, it's not the working or the documentation. It's the naming of what is considered a parallel job. The note you mentioned about accurately states what the tiers mean:

If you pay 40$ a month, you still have one **parallel job** (this means one job. I get the confusion as it's a parallel job) without the limitations of the free tier.

From there you can buy another parallel job for another $40 a month to run 2 **Concurrent Jobs** at the same time. 

I apologize for the confusion and you can see [this section](https://docs.microsoft.com/en-us/azure/devops/pipelines/licensing/concurrent-jobs?view=azure-devops#relationship-between-jobs-and-parallel-jobs) in the same doc to clarify the difference between _jobs_ and _parallel jobs_. I'll be closing this issue for now. Feel free to reach out with any questions or feedback.

**Comment by leyshon** [comment]
@chasewilson There's never been any difficulty with my understanding of the documentation. As I've been saying since the start, if the documentation on this page is correct then the pricing calculator is incorrect. However, the pricing calculator appears to have now been amended to match the documentation so all is resolved.

**Comment by chasewilson** [comment]
Ahh apologies. I took my first look when I closed the issue and I must have missed the original pricing calculator. I'm glad the docs are correct and hope to see more feedback from you in the future!
