### ISSUE TITLE
How would you use outputs?

### ISSUE THREAD

**Issue by sasanmcp** [MicrosoftDocs/vsts-docs#5163]
so I need access to the result output of the ARM template this task will run. unless somebody corrects me otherwise I believe I have to define either #deploymentOutputs or #outputVariable. this documentation does not explain how to use either variables in the pipleline and I need guidance on this:
is it like #outputVariable:$(pipelinevariable) or something like this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a59ea95e-b51a-e529-37a8-215e383c9a0b
* Version Independent ID: f1afdb0e-f090-3193-9bb8-ce5952016768
* Content: [Azure Resource Group Deployment task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-resource-group-deployment?view=azure-devops)
* Content Source: [docs/pipelines/tasks/deploy/azure-resource-group-deployment.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/deploy/azure-resource-group-deployment.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by RoopeshNair** [comment]
@N-Usha

**Comment by RoopeshNair** [comment]
@N-Usha
