### ISSUE TITLE
The first link in the "Where can I learn more about MSBuild?" section points to this same page.

### ISSUE THREAD

**Issue by StingyJack** [MicrosoftDocs/vsts-docs#5165]
Pete and Repeat were in a boat, and Pete jumped out. Who was left?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 22342679-18af-7c79-f902-fe9c0bb55379
* Version Independent ID: a8e7c201-6593-458b-5a81-b54e93fde4b5
* Content: [MSBuild build and release task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/msbuild?view=azure-devops#open-source)
* Content Source: [docs/pipelines/tasks/build/msbuild.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/build/msbuild.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @vijayma
* Microsoft Alias: **vijayma**

**Comment by msebolt** [comment]
@StingyJack  Thank you for the feedback.

The changes have been made and are pending review.
