### ISSUE TITLE
There is no blog anymore

### ISSUE THREAD

**Issue by ctahok** [MicrosoftDocs/vsts-docs#5169]
"They also aim to update the service status page and blog" those are now the same. If not please provide links.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 52eb9f91-b952-afb6-6d17-d7092f46440d
* Version Independent ID: bb9113a5-8b8b-b20b-9c6f-09a57f53ba7c
* Content: [Azure DevOps - Data Protection](https://docs.microsoft.com/en-us/azure/devops/organizations/security/data-protection?view=azure-devops)
* Content Source: [docs/organizations/security/data-protection.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/security/data-protection.md)
* Product: **devops**
* Technology: **devops-whitepapers**
* GitHub Login: @mlearned
* Microsoft Alias: **mlearned**

**Comment by msebolt** [comment]
@ctahok  Thank you for the feedback.

The changes have been made and are pending review.
