### ISSUE TITLE
Table much easier to read

### ISSUE THREAD

**Issue by AlasdairSQR** [MicrosoftDocs/vsts-docs#517]
The previous version of this page where the variables, their formats, and what they were for were all displayed in a table was much easier to read.
As a reference, developers will want to scan the content quickly to find the information they need.  The current layout requires the reader to read far more text to find the relevant information.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ffebdc8-521c-44b5-cde4-4abdc1bd6f18
* Version Independent ID: dc0effda-6d93-62aa-64c5-4e6f283b0826
* Content: [Build variables](https://docs.microsoft.com/en-us/vsts/build-release/concepts/definitions/build/variables?view=vsts&tabs=batch#feedback)
* Content Source: [docs/build-release/concepts/definitions/build/variables.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/build-release/concepts/definitions/build/variables.md)
* Service: **unspecified**
* GitHub Login: @erickson-doug
* Microsoft Alias: **alewis**

**Comment by andyjlewis** [comment]
Thanks for the feedback, and I hear you. Unfortunately even if the table format issues could be resolved (the way we have to break on non-word boundaries was not ideal) there's another problem with our new conceptual versioning control being incompatible with tables. I hope eventually we might be able to get back to a tabular format, but I can't say when that might happen.
