### ISSUE TITLE
Spelling error on 3rd sentence last word

### ISSUE THREAD

**Issue by awentzel** [MicrosoftDocs/vsts-docs#5177]
Replace "vverview" with "overview"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3c6b51d7-e615-8421-1789-4e74ff35b361
* Version Independent ID: d1e8f7de-9c60-cf00-71bf-59c70935be0e
* Content: [Connect using OData queries - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/report/powerbi/odataquery-connect?view=azure-devops)
* Content Source: [docs/report/powerbi/odataquery-connect.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/report/powerbi/odataquery-connect.md)
* Product: **devops**
* Technology: **devops-analytics**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by msebolt** [comment]
@awentzel  Thank you for the feedback.

The changes have been made and are pending review.
