### ISSUE TITLE
Access to Oauth Token configuration is wrong.

### ISSUE THREAD

**Issue by eHealthManny** [MicrosoftDocs/vsts-docs#518]
The "Use the OAuth token to access the REST API" section says that "To enable your script to use the build process OAuth token, go to the Options tab of the build definition and select Allow Scripts to Access OAuth Token." 

This is incorrect, its actually under the configuration section for each individual phase.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77731c06-e4fd-8125-0daf-870c9ccedd3f
* Version Independent ID: 0d5c338d-80f9-c64e-b675-bf7b4eb8e32b
* Content: [Use a PowerShell script to customize your build process](https://docs.microsoft.com/en-us/vsts/build-release/actions/scripts/powershell?view=vsts#use-the-oauth-token-to-access-the-rest-api)
* Content Source: [docs/build-release/actions/scripts/powershell.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/build-release/actions/scripts/powershell.md)
* Service: **unspecified**
* GitHub Login: @erickson-doug
* Microsoft Alias: **alewis**

**Comment by andyjlewis** [comment]
Thank you for the feedback. I've added this to our backlog.
