### ISSUE TITLE
Description of targetPath argument should specify whether wildcards are supported or not

### ISSUE THREAD

**Issue by carlos-quintero** [MicrosoftDocs/vsts-docs#5180]
If the targetPath argument of this Publish Pipeline Artifacts task doesn't support wildcards (which, by the way, would be great if supported) then the Description should document it: "Wildcards in the path are not supported.", like the Publish Build Artifacts task does (https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/publish-build-artifacts?view=azure-devops#arguments). It would have saved me 1 hour of my time...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 41baa0b5-175c-a697-4b7d-c150259c6e6b
* Version Independent ID: 75085b15-1acc-526a-0495-74a13c42c1d5
* Content: [Publish Pipeline Artifacts task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/publish-pipeline-artifact?view=azure-devops)
* Content Source: [docs/pipelines/tasks/utility/publish-pipeline-artifact.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/utility/publish-pipeline-artifact.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @willsmythe
* Microsoft Alias: **wismyth**

**Comment by wnjenkin** [comment]
@carlos-quintero thanks for report. Working on an update to this document

**Comment by wnjenkin** [comment]
@carlos-quintero I've update the doc with a note that wild cards are not supported. The change will be pushed in the next update.
