### ISSUE TITLE
Self-hosted agent UsePythonVersion configuration

### ISSUE THREAD

**Issue by tarrenj** [MicrosoftDocs/vsts-docs#5181]
[Documentation URL](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/use-python-version?view=azure-devops#how-can-i-configure-a-self-hosted-agent-to-use-this-task)

The documentation points to [this script](https://github.com/microsoft/azure-pipelines-image-generation/blob/master/images/linux/scripts/installers/python.sh#L15), which installs the packages into `$AGENT_TOOLSDIRECTORY/PyPy`, however 
 [test-toolcach.sh](https://github.com/microsoft/azure-pipelines-image-generation/blob/master/images/linux/scripts/installers/test-toolcache.sh#L17) looks in `$AGENT_TOOLSDIRECTORY/Python` instead. The agent fails to find the Python packages unless they're in `$AGENT_TOOLSDIRECTORY/Python`.

It's likely that the Packer builds work just fine, but the difference between the two locations makes configuring self-hosted agents difficult. (Adding some robustness to the script so it can be ran multiple times would be nice too.)

I'm happy to submit a PR to either the documentation or the script for this?

**Comment by msebolt** [comment]
@tarrenj  Thank you for the feedback.

This sounds like a candidate for either a script adjustment or note in **README**.

Please submit the issue to the [azure-pipelines-image-generation](https://github.com/microsoft/azure-pipelines-image-generation/issues) repo.

**Comment by tarrenj** [comment]
@msebolt Done, thanks!

**Comment by msebolt** [comment]
@tarrenj  Great, thank you for the contribution.
