### ISSUE TITLE
(classic)

### ISSUE THREAD

**Issue by trajano** [MicrosoftDocs/vsts-docs#5184]
On the TOC this is marked as *Release pipelines **(classic)** * what's the current way of doing a release?  Hopefully it's YAML based now and ideally make it easy to manage multiple services in a single pipeline.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d589bb13-a51a-77a5-d2f0-f424e42ede04
* Version Independent ID: 7b250082-a9c0-7dc2-9381-d04fbc5b7624
* Content: [Define a multi-stage CD release pipeline - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/define-multistage-release-process?view=azure-devops)
* Content Source: [docs/pipelines/release/define-multistage-release-process.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/release/define-multistage-release-process.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by mikeblakeuk** [comment]
@vijayma any news on this?
Will "Releases" go away and we use yml pipelines for builds and deployments?

**Comment by vijayma** [comment]
You have a choice - of using Pipelines and YAML for builds and deployments, or using classic Release as it exists now. At some distant point in the future, we might hide classic builds and releases for new users, but there are no plans of removing them for anyone that wants to use them.

**Comment by Bjego** [comment]
is there any replacement for the approvals in YAML pipelines,yet?
How can we achive this feature with a multistage YAML pipeline?
@vijayma

**Comment by vijayma** [comment]
@Bjego https://docs.microsoft.com/en-us/azure/devops/pipelines/process/approvals?view=azure-devops
