### ISSUE TITLE
YAML version

### ISSUE THREAD

**Issue by trajano** [MicrosoftDocs/vsts-docs#5188]
Does the YAML version support this yet?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a5b870a-5ea3-402f-e40f-4c05bbd10531
* Version Independent ID: 20497cc1-7311-d41b-cf6b-bc84708d1963
* Content: [Control deployments with approvals and gates - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/deploy-using-approvals?view=azure-devops)
* Content Source: [docs/pipelines/release/deploy-using-approvals.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/release/deploy-using-approvals.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by msebolt** [comment]
@trajeno  Thank you for the question.

Please refer to issue https://github.com/MicrosoftDocs/vsts-docs/issues/4497.
