### ISSUE TITLE
remove marketplace references

### ISSUE THREAD

**Issue by drdamour** [MicrosoftDocs/vsts-docs#5190]
seems like this is built in now, do we still need the marketplace references?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 67b0aa16-61d1-95a1-0607-83dbfba65e75
* Version Independent ID: a7e712dd-67ec-0b0d-34e4-9e95140bbbc5
* Content: [Search your code across your projects](https://docs.microsoft.com/en-us/azure/devops/project/search/code-search?view=azure-devops)
* Content Source: [docs/project/search/code-search.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/project/search/code-search.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@drdamour  - Thank you for your inquiry. Code Search remains an extension available to install on Azure DevOps Services and Azure DevOps Server 2019.  I just confirmed that I could install it on my organization. 

![image](https://user-images.githubusercontent.com/10856840/63050303-a1765b80-be8f-11e9-9846-a8ff3e34b4ce.png)

**Comment by drdamour** [comment]
Ok my bad I was under the impression it was built in now, my bad
