### ISSUE TITLE
Please include the namespaces in the examples

### ISSUE THREAD

**Issue by StingyJack** [MicrosoftDocs/vsts-docs#5192]
Things like `VssConnection` exist in more than one namespace, so copy/pasting the example to see it working immediately cant resolve the correct single namespace. 

![image](https://user-images.githubusercontent.com/15381181/62753394-82b03900-ba39-11e9-9f10-f7f74f886c39.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aa8505e8-cef0-fee8-866a-e000058ac233
* Version Independent ID: d6858ee2-4282-b4e1-fb3b-e8b531b950b7
* Content: [.NET Client Library Samples for Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/integrate/get-started/client-libraries/samples?view=azure-devops#authenticating-azure-devops-services)
* Content Source: [docs/integrate/get-started/client-libraries/samples.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/integrate/get-started/client-libraries/samples.md)
* Product: **devops**
* Technology: **devops-ecosystem**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hello @StingyJack! Thanks for your feedback, we'll address this as soon as possible and keep in touch. Have a great weekend!

**Comment by chcomley** [comment]
Hi @StingyJack, We only have one[ VssConnection](https://dev.azure.com/mseng/AzureDevOps/_search?action=contents&text=class%3Avssconnection&type=code&lp=code-Project&filters=ProjectFilters%7BAzureDevOps%7DRepositoryFilters%7BAzureDevOps%7D&pageSize=25&includeFacets=false&result=DefaultCollection%2FAzureDevOps%2FAzureDevOps%2FGBmaster%2F%2FVssf%2FClient%2FWebApi%2FVssConnection.cs) class in our code base and it is under the namespace: Microsoft.VisualStudio.Services.WebApi.  You must have a 3rd party binary loaded, which also has one.
Thanks! Let us know if you need more clarity.

**Comment by StingyJack** [comment]
@chcomley  - I didn't actually look for the types in the docs =O  (sorry).   i did have a screenshot of the two namespaces that were suggested. Isnt that the built-in type resolution context menu? Resharpers looks different I think. Either way, this is probably another bug for devcomm or youtrack.

**Comment by chcomley** [comment]
Thanks @StingyJack, I've created a ticket with the Developer Community. Here's a link: https://developercommunity.visualstudio.com/idea/692744/include-namespaces-in-examples-for-net-client-libr.html 
Thank you!
