### ISSUE TITLE
How to prevent task to run

### ISSUE THREAD

**Issue by minuz** [MicrosoftDocs/vsts-docs#5194]
Hi, I'm trying to setup a few tasks that should only run if it's on master, develop and release/* branches
I only saw reference to master using refs/heads/master. Can anyone shed some light on how to achieve that?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77c58a78-a567-e99a-9eb7-62dddd1b90b6
* Version Independent ID: 680a79bc-11de-39fc-43e3-e07dc762db18
* Content: [Expressions - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/expressions?WT.mc_id=ITOpsTalk-blog-nepeters&view=azure-devops)
* Content Source: [docs/pipelines/process/expressions.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/expressions.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by minuz** [comment]
This is what I've tried:

Evaluating: and(succeeded(), or(eq(variables['Build.SourceBranch'], 'refs/heads/master'), eq(variables['Build.SourceBranch'], 'refs/heads/develop'), eq(variables['Build.SourceBranch'], 'refs/heads/release/*')))
Expanded: and(True, or(eq('refs/heads/release/1.0.0', 'refs/heads/master'), eq('refs/heads/release/1.0.0', 'refs/heads/develop'), eq('refs/heads/release/1.0.0', 'refs/heads/release/*')))
Result: False

It seems the wildcard doesn't work...

**Comment by fernandobaba** [comment]
Apologies, I didn't read the documentation with too much attention. End up finding how :)

`and(succeeded(), or(eq(variables['Build.SourceBranch'], 'refs/heads/master'), eq(variables['Build.SourceBranch'], 'refs/heads/develop'), contains(variables['Build.SourceBranch'], 'refs/heads/release/')))`

For reference if anyone is looking for something similar

**Comment by WilliamAntonRohm** [comment]
I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.

**Comment by MichaelReitsma** [comment]
Hi, I have something similar: i want to prevent a task to run under different conditions though. It should only run when the previous step has failed. Not when the any of the other steps before that previous one have failed. If the latter happens then this step should be skipped as well. So using a custom condition only reflects th status of the Agent / Job whereas i would like to access the state of the previous step.
If the previous steps status is skipped then skip current skip. If previous step status is failed then run current step.

TIA
