### ISSUE TITLE
How to see which Release Pipelines reference a Variable Group?

### ISSUE THREAD

**Issue by Rosewood99** [MicrosoftDocs/vsts-docs#5195]
How can I see which Variable Groups are in use, and by which Release Pipeline?  I have dozens of Releases for various apps and quite a few Variable Groups shared by multiple Releases.

I had one situation where for some apps I only had a Dev and Prod environment and I added a new Test environment.  I cloned the Dev Variable Group for Test which worked great, but then I had to edit every Release to find which ones are using the Group so I can add the new one.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4827aa99-ae62-bd63-6f2f-a87a4065ed27
* Version Independent ID: c9e461ee-7f42-3503-9460-18fa3a807bbb
* Content: [Variable groups for Azure Pipelines and TFS - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/library/variable-groups?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/library/variable-groups.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/library/variable-groups.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by ashokirla** [comment]
Thanks for your feedback. We have this ask in our backlog to show the variable group references in the pipelines. As of now no timelines are finalized on this feature. We will update once we decide on the timelines.

**Comment by MarcoB1234** [comment]
Is there any update on this issue?
