### ISSUE TITLE
Missing link

### ISSUE THREAD

**Issue by DonFrazier** [MicrosoftDocs/vsts-docs#5196]
This page is the destination of the link https://go.microsoft.com/fwlink/?linkid=852344 where the text promises me more information about YAML Builds.  Here's the full text 'Below is a clipboard-friendly view of your selection. To copy to the clipboard, either right-click and choose 'Copy' from the browser’s context menu or press Ctrl+C. [more information about YAML builds]'   This is in Azure Dev ops at a page similar to /_apps/hub/ms.vss-ciworkflow.build-ci-hub?_a=edit-build-definition&id=1&view=Tab_Tasks where I'm trying to figure out how to check in a YAML build definition to my source tree.  It would be nice if the go link pointed somewhere useful instead of this useless page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7336a04e-5b38-d02f-8bba-a55445b2f094
* Version Independent ID: 783c30b3-63b6-da7c-1336-b000bb8b4c66
* Content: [Create your first pipeline - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/create-first-pipeline?view=azure-devops&tabs=tfs-2018-2)
* Content Source: [docs/pipelines/create-first-pipeline.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/create-first-pipeline.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
@DonFrazier We had some content move around and get renamed, and then this getting started tutorial was simplified. I think the right place for that link to go would be [here](https://docs.microsoft.com/en-us/azure/devops/pipelines/customize-pipeline?view=azure-devops) which gives more information about what the different parts of the YAML file do. I've updated that link, and thank you for letting us know.
