### ISSUE TITLE
What is format of demands?

### ISSUE THREAD

**Issue by Izzmo** [MicrosoftDocs/vsts-docs#5199]
Doesn't demands take a comma separated list, an array? It's not clarified.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e7541ee6-d2bb-84c0-fead-1aa8ee7d2372
* Version Independent ID: 5cf7c51e-37e1-6c67-e6c6-80262c4eb662
* Content: [Demands - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/demands?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/process/demands.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/demands.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by brianveltman** [comment]
it's documented at https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=example#demands

**Comment by Izzmo** [comment]
@brianveltman I see.. that does give some more information with is nice.

Can we get a link back and forth from this place? It's a bit odd.

Also, are "existance of" and "-equals" the only two cases you can use?

**Comment by steved0x** [comment]
@Izzmo I believe so, they are the only two items called out in the YAML Schema. I have updated the docs to provide more info, and I'll find out if [expressions](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/expressions?view=azure-devops) as supported there in addition to the `-equals` that is specifically called out.

**Comment by steved0x** [comment]
@Izzmo I have updated the docs with more information, and existence of a registered capability string, or -equals for a specific agent property are the two types of simple string match that are available for demands.

**Comment by Izzmo** [comment]
This is better, thanks @steved0x
