### ISSUE TITLE
Wiql query only returns IDs

### ISSUE THREAD

**Issue by CordellStocker** [MicrosoftDocs/vsts-docs#5203]
In this article, it states being able to use SELECT to choose which columns to return. However, regardless of the columns I include, the query only returns the IDs (even if Id is left out). I found this page while searching for answers: https://developercommunity.visualstudio.com/content/problem/262288/wiql-query-just-returns-ids.html. Which discusses the exact same problem. That problem was marked as "closed-fixed" over a year ago.
It's clear that the workitems api must be used to get the detailed work items, but this documentation is still out of date.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 710af5f2-8a31-e0d3-4f20-00c79dc54713
* Version Independent ID: 1d4d9580-984c-9fee-861a-a02ce828d3db
* Content: [WIQL reference syntax - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/queries/wiql-syntax?view=azure-devops#feedback)
* Content Source: [docs/boards/queries/wiql-syntax.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/boards/queries/wiql-syntax.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@CordellStocker - Thank you for your inquiry. I'm contacting the product team and will update you with a response as soon as I have one.

**Comment by KathrynEE** [comment]
@CordellStocker - The product team responded: 

> Yes, this behavior is by design, QueryByWiql will always return Ids, and workitem API needs to be called to retrieve the workitem details. For the columns stated after the “SELECT”, the wiql API will return its metadata in the “columns” and “sort columns” sections in the result json.  See: https://docs.microsoft.com/en-us/rest/api/azure/devops/wit/Wiql/Query%20By%20Wiql?view=azure-devops-rest-5.0#examples.
