### ISSUE TITLE
Auth snippet doesn't work

### ISSUE THREAD

**Issue by Leon99** [MicrosoftDocs/vsts-docs#5206]
As of v16.143.2 of Microsoft.VisualStudio.Services.Client.Interactive, `VssClientCredentialStorage` doesn't have a default (parameterless) constructor. Please update the auth snippet ASAP since it's impossible to use anything else without the authentication.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 413163f0-28c3-a2a7-d626-fcb81bcb2257
* Version Independent ID: 57c127da-2b1e-d29e-9abb-a3c258762ccf
* Content: [.NET Client Libraries for Azure DevOps Services (and TFS)](https://docs.microsoft.com/en-us/azure/devops/integrate/concepts/dotnet-client-libraries?view=azure-devops)
* Content Source: [docs/integrate/concepts/dotnet-client-libraries.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/integrate/concepts/dotnet-client-libraries.md)
* Product: **devops**
* Technology: **devops-ecosystem**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by tedchamb** [comment]
@Leon99 , the 16.143.2 version of our packages is the first released version that includes our NetStandard libraries alongside the net45 libraries.  This class has not changed in the net45 version of the binary.  In the NetStandard version we do not have the same implementation due to cross platform support, and as part of this does not have the parameterless constructor .  If you update your project to use the net45 version of the binaries included in the package, your existing code should work as it did before.

**Comment by Leon99** [comment]
What if I want to use .Net Core, as it's the platform MS currently recommends? Can we please have a similar example that works with the NetStandard version?

**Comment by tedchamb** [comment]
```
using Microsoft.VisualStudio.Services.Common;
using Microsoft.VisualStudio.Services.Client;
using Microsoft.TeamFoundation.SourceControl.WebApi;
using Microsoft.VisualStudio.Services.WebApi;

const String c_collectionUri = "https://dev.azure.com/fabrikam";
const String c_projectName = "MyGreatProject";
const String c_repoName = "MyRepo";

// Interactively ask the user for credentials if necessary
VssCredentials creds = new VssClientCredentials();

// Connect to Azure DevOps Services
VssConnection connection = new VssConnection(new Uri(c_collectionUri), creds);

// Get a GitHttpClient to talk to the Git endpoints
GitHttpClient gitClient = connection.GetClient<GitHttpClient>();

// Get data about a specific repository
var repo = gitClient.GetRepositoryAsync(c_projectName, c_repoName).Result;
```

**Comment by Leon99** [comment]
I've already figured it out, thanks @tedchamb. I still believe it should be clearly documented though. Given the very essential nature of this operation, this doesn't look expected:
![image](https://user-images.githubusercontent.com/6840381/65194700-1efd3f00-dac0-11e9-8c9a-6edf4f25291c.png)

**Comment by tedchamb** [comment]
@leon99, I agree that the documentation needs to be updated.  The work to do this is already under way.

@wireznak as fyi.
