### ISSUE TITLE
.NET Core support

### ISSUE THREAD

**Issue by Leon99** [MicrosoftDocs/vsts-docs#5207]
It would be good to know which of the authentication methods support .NET Core.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 294772ce-58a0-bb83-8927-3e69beca39df
* Version Independent ID: d9c4a4b3-3abf-d738-369e-fff8532e9dd9
* Content: [Guidance for authentication](https://docs.microsoft.com/en-us/azure/devops/integrate/get-started/authentication/authentication-guidance?view=azure-devops)
* Content Source: [docs/integrate/get-started/authentication/authentication-guidance.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/integrate/get-started/authentication/authentication-guidance.md)
* Product: **devops**
* Technology: **devops-ecosystem**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @Leon99, The only thing that I'm aware of that isn't supported is interactive auth.  This is because .NetCore is cross platform, and we don’t have a UI that works on all platforms. Hope this information is helpful. Do let us know if you have any further questions. Thank you for reaching out!

**Comment by Leon99** [comment]
Thanks for clarification @chcomley. Do you think it would be useful to mention in the documentation?

On a side note, do you happen to know if supporting .NET Core 3 is planned? Since it includes WinForms/WPF, there is nothing that should stop the interactive auth from working on Windows. Alternatively, are there any plans to implement cross-platform interactive auth workflow (like in VSCode)?

**Comment by Leon99** [comment]
For the record - I left a feature suggestion for browser-based interactive auth here: https://developercommunity.visualstudio.com/idea/702258/interactive-authentication-for-api-client-via-brow.html
