### ISSUE TITLE
Extracting parts of a version is not well documented

### ISSUE THREAD

**Issue by ghelyar** [MicrosoftDocs/vsts-docs#5209]
If a version is defined as
```
variables: 
  someVersion: 1.2.3
```

How can other variables and other tasks extract the individual version components (Major, Minor, Build, Revision)?

for example, how would you echo the major component of a version variable from a bash script (without string manipulation inside the script, as this was just an example of a task that might use it), or use it in a format string for another variable?

`sh: echo $(someVersion.Major)` does not seem to work, for example.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77c58a78-a567-e99a-9eb7-62dddd1b90b6
* Version Independent ID: 680a79bc-11de-39fc-43e3-e07dc762db18
* Content: [Expressions - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/expressions?view=azure-devops#format)
* Content Source: [docs/pipelines/process/expressions.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/expressions.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by dhirschfeld** [comment]
Since it explicitly mentions C#'s `TryParse` method it would probably be useful to cross-reference the docs for those unfamiliar with it:
https://docs.microsoft.com/en-us/dotnet/api/system.version.tryparse

**Comment by ghelyar** [comment]
It wouldn't hurt to link to the API docs, but that is only for parsing the version, not for extracting components of it.

So far I have not found any way to do this, making version little better than string.

I have tried `$( )`, `${{ }}` and `$[ ]` syntax to get e.g. the major component out with no luck.

The only thing I have found so far that works is treating it as a string and using powershell to parse it and set variables with  `Write-Host "##vso[task.setvariable` which is not ideal as it's an extra task to call all over the place and it can't be used in other variables, such as counters.

**Comment by steved0x** [comment]
@ghelyar You are correct, and others, sorry for the delay in following up to close the loop on this issue - pipeline expressions don't include string operations like split, substring, etc... which could be used to get the component parts of a version. The easiest way to do that would be to use a custom script task (for example all Microsoft-hosted agents have node installed) to do the string operations and return the desired parts, for example splitting up a version string to access the component parts.

Adding split and substring probably wouldn't be accepted as a feature request, but adding a built-in method to access the parts of a version might be (I agree with your comment: `making version little better than string`), so I recommend that anyone interested in that functionality to file a feature request at https://developercommunity.visualstudio.com/spaces/21/index.html

Thank you and I apologize for the delay in looping back.

**Comment by ghelyar** [comment]
I have added a feature request:
https://developercommunity.visualstudio.com/idea/763322/azure-pipelines-yaml-get-components-of-a-version-v.html

**Comment by ghelyar** [comment]
... and the feature request is now closed.

Maybe just remove any mention of a "version" type from the docs, if it's no better than a string?
