### ISSUE TITLE
CredentialProviderBundler vs. Azure Artifacts Credential Provider?

### ISSUE THREAD

**Issue by mahilleb-msft** [MicrosoftDocs/vsts-docs#5210]
From https://github.com/Microsoft/artifacts-credprovider, using NuGet.exe version 4.8.0.5385 or up is supported by artifacts-credprovider, is there a reason not to promote it here? The sister page dotnet-exe.md already does it for .NET Core ...

Took me quite a long journey through docs, which started from here :)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab0a3735-a9b0-2ed7-f08f-5321f55f8c90
* Version Independent ID: 2153f6c0-def7-eed1-286d-5e61c9fcbec4
* Content: [Use NuGet with Azure DevOps Services feeds](https://docs.microsoft.com/en-us/azure/devops/artifacts/nuget/nuget-exe?view=azure-devops)
* Content Source: [docs/artifacts/nuget/nuget-exe.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/artifacts/nuget/nuget-exe.md)
* Product: **devops**
* Technology: **devops-artifacts**
* GitHub Login: @chasewilson
* Microsoft Alias: **phwilson**

**Comment by andrewtyped** [comment]
I just discovered the artifacts-credprovider repo as well. I am extremely confused about this. What are the differences between these two tools? Why are there two workflows for authenticating with private feeds, and why is the tool *branded* with Azure not recommended here? My team has spent so much time getting NuGet authentication working locally and on build agents - this is a mess. Some unified guidance would be appreciated.

**Comment by chasewilson** [comment]
Hi @mahilleb-msft, @andrewtyped, thank you for the feedback! I'm bringing in the artifacts PM @elbatk. Elijah, you have any input on this?

**Comment by elbatk** [comment]
Thanks everyone for the feedback. We are in the middle of a big UX redesign of this Connect to Feed for all package types and tools. I think when that rolls out at the end of this quarter/start of the next and we get the docs updated, you'll see the more unified auth guidance that you're looking for!
