### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by neuropa** [MicrosoftDocs/vsts-docs#5213]
On [this](https://docs.microsoft.com/en-us/azure/devops/user-guide/about-azure-devops-services-tfs?view=azure-devops) page, this link is broken:
"To learn more, see [Plan your Azure DevOps organization structure](https://docs.microsoft.com/en-us/azure/devops/user-guide/plan-your-azure-devops-org-structure.md)."

This is the correct URL (without trailing ".md"):
https://docs.microsoft.com/en-us/azure/devops/user-guide/plan-your-azure-devops-org-structure

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 808dac3a-225a-f564-ea5e-de6bad168da4
* Version Independent ID: decabfe6-ae8d-183c-3698-acb829da81f5
* Content: [Understand differences between Azure DevOps Services and Azure DevOps Server - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/user-guide/about-azure-devops-services-tfs?view=azure-devops)
* Content Source: [docs/user-guide/about-azure-devops-services-tfs.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/user-guide/about-azure-devops-services-tfs.md)
* Product: **devops**
* Technology: **devops-new-user**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @neuropa, Thanks for the heads up, however the ."md" is correct. Troubleshooting on my side results in no broken links. We appreciate the time you took to provide this feedback, so thank you!

**Comment by neuropa** [comment]
Hey @chcomley,

Have you tried to reach it from outside your company network or something?

I get a HTTP 404 while the corrected URL works to me:

![image](https://user-images.githubusercontent.com/7249083/62928219-68b78300-bdb8-11e9-86c8-ce8b31de8f03.png)

![image](https://user-images.githubusercontent.com/7249083/62928389-bfbd5800-bdb8-11e9-90c3-c5f2d920de3e.png)

Regards,
B.

**Comment by chcomley** [comment]
@neuropa, I've had a few different people try it successfully. Perhaps it's cookies? Not sure, but it looks good on our end. Thanks again!

**Comment by Pyroneus** [comment]
@chcomley Did you click on "Plan your Azure DevOps organization structure." or "Plan your organizational structure in Azure DevOps."?
The first is broken, the latter works.

**Comment by chcomley** [comment]
@Pyroneus, you're so right. I'll publish this fix momentarily. Thank you so much for your feedback.
