### ISSUE TITLE
Three minute to publish code coverage?

### ISSUE THREAD

**Issue by ahaleiii** [MicrosoftDocs/vsts-docs#5214]
I am a fan of the new coverage reporting feature. It means I do not have to manage a tool to create the coverage reports myself, and it means that the reports look consistent across various types of projects.

However, ever since the Publish Code Coverage task was updated to auto-generate the coverage report, my build times have gone up because it's taking three minutes to upload all the files generated by the report. This is significantly impacting our feedback loop process, as publishing code coverage results is now the longest running task in the build.

Is there a way for this upload time to be reduced? An option to publish as zip and for the server to unzip them?

```
Publishing coverage summary data to TFS server.
Lines- 12685 of 14215 covered.
Branches- 1733 of 2637 covered.
Modifying Cobertura Index file
Publishing code coverage files to TFS server.
Uploading 1400 files
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6ac4ff4-9839-6a6d-8d20-a25084d221ef
* Version Independent ID: bd09f139-8e69-8ea1-6671-b7bba8e17c23
* Content: [Publish Code Coverage Results task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/test/publish-code-coverage-results?view=azure-devops)
* Content Source: [docs/pipelines/tasks/test/publish-code-coverage-results.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/test/publish-code-coverage-results.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @PBoraMSFT
* Microsoft Alias: **pbora**

**Comment by WilliamAntonRohm** [comment]
It looks like you've encountered an issue with the product itself, rather than an issue with the documentation. To make sure it gets in front of the right people, please [submit your bug]( https://developercommunity.visualstudio.com/content/problem/post.html?space=21) here.

**Comment by ahaleiii** [comment]
Thanks. Created here:
https://developercommunity.visualstudio.com/content/problem/692554/three-minute-to-publish-code-coverage.html
