### ISSUE TITLE
Can I connect my users from Office 365 GCC to DevOps Services?

### ISSUE THREAD

**Issue by Anand-Moghe** [MicrosoftDocs/vsts-docs#5215]
Can a users in Office 365 GCC connect to Azure DevOps Service without having any Azure Tenant and subscription in Azure Commercial cloud (MAC)? And if not, when would it be possible and is there any timeline/roadmap?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7eedc21a-4626-6f86-6972-c719a67848be
* Version Independent ID: 50e6989d-0cdf-fa10-dcbc-54afddcbef21
* Content: [Troubleshoot permissions and access via Azure Active Directory - Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/faq-azure-access?view=azure-devops#o365aad)
* Content Source: [docs/organizations/accounts/faq-azure-access.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/accounts/faq-azure-access.md)
* Product: **devops**
* Technology: **devops-accounts**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @Anand-Moghe, Thanks so much for reaching out. Azure DevOps is only available as a public service and doesn't currently support Government clouds. We’re evaluating the possibility of enabling this support in future but this capability isn't on our roadmap for at least a year. Thanks again!

**Comment by Anand-Moghe** [comment]
@chcomley Thank you.

**Comment by mfourieshieldai** [comment]
@chcomley any progress on this? My understanding is that right now I can not connect Azure DevOps to an O365 GCC High tenant AD. Correct?

**Comment by alsulli** [comment]
@mfourieshieldai We state that Azure DevOps Services connection is only supported for public tenants in [this doc](https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/connect-organization-to-azure-ad?view=azure-devops#prerequisites).

**Comment by Anand-Moghe** [comment]
@MS-alsulli O365 GCC is on Azure Commercial cloud. So it should be possible to connect to Azure DevOps Service Org, right?

**Comment by mfourieshieldai** [comment]
@Anand-Moghe GCC = Government Community Cloud, it's specifically not the Commercial cloud. Per the docs indicated above it does not work. @MS-alsulli is would be good to know if this is on the roadmap yet.

**Comment by MS-alsulli** [comment]
@mfourieshieldai The public roadmap for Azure DevOps Services features is found here: https://dev.azure.com/mseng/AzureDevOpsRoadmap/_workitems/recentlyupdated

Any user can view it, as it is a public project. With that being said, This feature is not on the roadmap, and no plans for it to be to the best of my knowledge.

**Comment by mfourieshieldai** [comment]
Thanks @MS-alsulli . I often click issues in release notes and get permission denied. I just figured out that the links and the one above don't work for authenticated users, it gives access denied. Shows fine in a **private** window.

401 - Uh-oh, you do not have access.
The request requires authentication.
11/4/2020 10:38:06 PM (UTC)
99d1fd88-d3b9-4c96-846b-9cd76a86aa06
Sign out and login with different account

Our work around for GCC High is to move to Azure DevOps Server and host ourselves.

Regards

Mike
