### ISSUE TITLE
Xcode task does not report code coverage - documentation is misleading

### ISSUE THREAD

**Issue by gh123man** [MicrosoftDocs/vsts-docs#5216]
"Tasks such as Visual Studio Test, .NET Core, Ant, Maven, Gulp, Grunt, and Xcode also provide the option to publish code coverage data to the pipeline. If you are using these tasks, you do not need a separate Publish Test Results task in the pipeline."

The Xcode task does not report code coverage however the quoted statement claims that it does. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6ac4ff4-9839-6a6d-8d20-a25084d221ef
* Version Independent ID: bd09f139-8e69-8ea1-6671-b7bba8e17c23
* Content: [Publish Code Coverage Results task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/test/publish-code-coverage-results?view=azure-devops#feedback)
* Content Source: [docs/pipelines/tasks/test/publish-code-coverage-results.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/test/publish-code-coverage-results.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @PBoraMSFT
* Microsoft Alias: **pbora**

**Comment by PBoraMSFT** [comment]
Fixed with the above mentioned pull request.

**Comment by rahulreddyv** [comment]
@PBoraMSFT Is there anyway we can review CC results of XCode inherently from the pipeline? I am working on the CC reports using slather and Cobertura

**Comment by nishantms** [comment]
@rahulreddyv : If you are generating your CC files in .cobertura format then Report Generator can help https://github.com/danielpalme/ReportGenerator/blob/master/README.md
