### ISSUE TITLE
Document $(Agent.TempDirectory)

### ISSUE THREAD

**Issue by AArnott** [MicrosoftDocs/vsts-docs#5217]
The Agent.TempDirectory variable is incidentally documented in several pages, but is not listed here. Its use case of a directory that's always cleared before a pipeline is executed makes it very useful as a scratch directory.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ffebdc8-521c-44b5-cde4-4abdc1bd6f18
* Version Independent ID: dc0effda-6d93-62aa-64c5-4e6f283b0826
* Content: [Predefined variables - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/build/variables.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/build/variables.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by trajano** [comment]
This would be a useful destination for the javatoolinstaller (I kind of wish they made it the  default)

**Comment by steved0x** [comment]
@AArnott I have added this to the docs and it should be live shortly.
