### ISSUE TITLE
Excluding weekends (non work days) from Burndown

### ISSUE THREAD

**Issue by brucedunbar** [MicrosoftDocs/vsts-docs#5219]
When using the burndown analytics widget, is there any way to exclude weekends in the dates that are plotted on the horizontal axis? When non-work days, like weekends, are plotted there is an illusion of more days available in the sprint than there actually are.
Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a9d627b9-9aa8-c52c-3178-cffbefe9727a
* Version Independent ID: 31967bb3-2635-da97-782c-641f432750f7
* Content: [Configure Burndown & Burnup widgets - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/report/dashboards/configure-burndown-burnup-widgets?view=azure-devops&viewFallbackFrom=vsts#feedback)
* Content Source: [docs/report/dashboards/configure-burndown-burnup-widgets.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/report/dashboards/configure-burndown-burnup-widgets.md)
* Product: **devops**
* Technology: **devops-analytics**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by APIWT** [comment]
We would like this feature too!

**Comment by WilliamAntonRohm** [comment]
Thanks for the suggestion! The product teams aren’t always watching this repository, so to make sure it gets in front of them for triage, please [submit your idea]( https://developercommunity.visualstudio.com/content/idea/post.html?space=21) here.

**Comment by brucedunbar** [comment]
Thanks @WilliamAntonRohm - looks like it's already filed here: https://developercommunity.visualstudio.com/content/idea/365930/weekends-cycle-time.html
Cheers!

**Comment by WilliamAntonRohm** [comment]
You're welcome, @brucedunbar!
