### ISSUE TITLE
Bad formatting in PAT docs

### ISSUE THREAD

**Issue by v-kydela** [MicrosoftDocs/vsts-docs#5222]
This paragraph appears to be badly formatted:

![image](https://user-images.githubusercontent.com/41968495/62903431-78cb5600-bd17-11e9-9ca3-4e1f1ae78420.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 53f99d2d-363b-d01d-039d-4fdc636fa2df
* Version Independent ID: f47330d5-e2de-36a4-e5b3-5bc77505b161
* Content: [Authenticate with personal access tokens - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/integrate/get-started/authentication/pats?view=azure-devops)
* Content Source: [docs/integrate/get-started/authentication/PATs.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/integrate/get-started/authentication/PATs.md)
* Product: **devops**
* Technology: **devops-ecosystem**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @v-kydela, Thanks so much for letting us know. I've published a fix, which should be live by tomorrow morning (PST). Thanks again!
