### ISSUE TITLE
Server job simplified syntax: Unexpected value 'server'

### ISSUE THREAD

**Issue by Bryce-L** [MicrosoftDocs/vsts-docs#5224]
When I try using the simplified syntax for a server job I get the following error.  Is there anything special I need for it to recognize the simplified syntax?

1479178: "/azure-pipelines.yml (Line: 59, Col: 5): Unexpected value 'server'"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 67504b34-d64b-02a4-2e10-ab99f3b8cfe4
* Version Independent ID: 2cf63b2e-184b-7726-3b8a-d8baffd6fcce
* Content: [Jobs in Azure Pipelines, Azure DevOps Server, and TFS - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/phases?view=azure-devops&tabs=yaml#feedback)
* Content Source: [docs/pipelines/process/phases.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/phases.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @vijayma
* Microsoft Alias: **vijayma**

**Comment by msebolt** [comment]
@Bryce-L  Thank you for the feedback.  

Instead, please try:

```
jobs:
- job: string
  pool: server
```

The documentation is in the process of being updated.

**Comment by WilliamAntonRohm** [comment]
@Bryce-L Thanks for your feedback; we appreciate it. To make sure we have all the information needed to triage your issue, please let us know which topic you’re referencing, or provide more context around the general task.
