### ISSUE TITLE
Within the scope of a release, I want to delete stages or disable triggers

### ISSUE THREAD

**Issue by itsjusth** [MicrosoftDocs/vsts-docs#5225]
Our release version matches our build version.  If our build version number is a certain format (contains the word 'dev'), that build must only ever be deployed to the dev environment.  If the build version is a parseable semantic version number, the code can be deployed to QA, Staging, and Production.  Currently, I have a powershell script in the later stages that cancels the deployment if the version contains the word 'dev'.  Within the scope of a single release, I want a script in the Dev stage to remove the later stages from the release OR disable their approval conditionals and triggers.

**Comment by itsjusth** [comment]
After some consideration, a post deployment gate that calls a simple function app to evaluate my version number may be the right way to handle this.

**Comment by msebolt** [comment]
@itsjusth Thank you for the question.

Perhaps using a combination of [pipeline variables](https://docs.microsoft.com/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch#set-in-script), for instance, `isDev` and [task control options](https://docs.microsoft.com/azure/devops/pipelines/process/tasks?view=azure-devops&tabs=yaml#controloptions)?  You can then add your initial script to this solution with the [PowerShell task](https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/powershell?view=azure-devops).

There are many possibilities here and the solution you posted might be the easiest depending on your situation.
