### ISSUE TITLE
"Don't migrate your history" might need more explanation

### ISSUE THREAD

**Issue by voltagex** [MicrosoftDocs/vsts-docs#5226]
This might need to be on another page or in another article, but

&gt;Due to the differences in how TFVC and Git store version control history, we recommend that you don't migrate your history. 

Can you please elaborate?

I'm assuming that you don't *lose* your history at the same time - you mean that commits before a certain date need to be looked up in an archived TFVC.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d24126ce-abfc-07d0-ceea-51534f745e55
* Version Independent ID: 60861ae7-4b6d-e360-8ab7-28b276326569
* Content: [Import repositories from TFVC to Git - Azure Repos](https://docs.microsoft.com/en-gb/azure/devops/repos/git/import-from-TFVC?view=azure-devops#feedback)
* Content Source: [docs/repos/git/import-from-TFVC.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/repos/git/import-from-TFVC.md)
* Product: **devops**
* Technology: **devops-code-git**
* GitHub Login: @apawast
* Microsoft Alias: **atinb**

**Comment by msebolt** [comment]
@voltagex  Thank you for the question.

Please refer to the **Advanced Migrations** section in [Migrate from TFVC to Git](https://docs.microsoft.com/azure/devops/learn/git/migrate-from-tfvc-to-git) for a more detailed description on the differences in history between the two.

The article is based on use of the [git-tfs](https://github.com/git-tfs/git-tfs) tool and includes some good descriptions of the pitfalls involved.
