### ISSUE TITLE
Use the original organization name

### ISSUE THREAD

**Issue by BrightRan** [MicrosoftDocs/vsts-docs#5227]
In the past, I used my email address (email1) to create an organization named BriRanOrg, now I want to use my another email address (email2) to create an organization with the same name BriRanOrg. I tried to change the original name to be another, such as BriRanOrg01, then use email2 to create the new organization with the name BriRanOrg, but it still tell me that the name is already taken. Why? 
After changing the organization name, whether the original name still only be used for the current organization, and will always be not available for another new organization?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 129e3d78-3ac8-8d07-d573-5530cd018656
* Version Independent ID: 1fbe6f52-2967-114e-1d2b-af4771080ac7
* Content: [Rename your organization - Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/rename-organization?view=azure-devops)
* Content Source: [docs/organizations/accounts/rename-organization.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/accounts/rename-organization.md)
* Product: **devops**
* Technology: **devops-accounts**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @BrightRan, I'm following up with a PM and will be in touch. Thanks for reaching out.
