### ISSUE TITLE
Verify vague

### ISSUE THREAD

**Issue by riezebosch** [MicrosoftDocs/vsts-docs#523]
Unclear what is meant by `highlighting a group on the Group rules tab and choosing Summary` and `highlighting a user on the Users page, and then clicking Summary`. Also some guidance please on whether to remove the direct assignments after group rules are in place.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4e193f57-621f-6b4b-6609-4cf6ab9fbdeb
* Version Independent ID: 26c4fcee-8a9b-d12c-426d-567b2f7cd768
* Content: [Migrate to group-based resource management](https://docs.microsoft.com/en-us/vsts/accounts/migrate-to-group-based-resource-management-in-vsts?view=vsts)
* Content Source: [docs/accounts/migrate-to-group-based-resource-management-in-VSTS.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/accounts/migrate-to-group-based-resource-management-in-VSTS.md)
* Service: **unspecified**
* GitHub Login: @erickson-doug
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
@riezebosch Thanks for letting us know. I've added a few screenshots for some clarity and this should be live sometime today. I've also added a work item to the backlog for guidance on whether to remove the direct assignments after group rules are in place. Thank you!
