### ISSUE TITLE
CacheBeta Post job does not respect Conditions on task

### ISSUE THREAD

**Issue by Xexiz** [MicrosoftDocs/vsts-docs#5230]
The CacheBeta Post job should respect the condition on the task. Even if I set the CacheBeta task to succeededOfFailed() it is totally ignored by the Post-Job and will always be skipped with the warning `Skipping because the job status was not 'Succeeded'`. Would it be possible to modify before final version of the task to use task conditions and not hardcode it to skip if Agent.JobStatus is not succeeded() (see https://github.com/microsoft/azure-pipelines-agent/blob/master/src/Agent.Plugins/PipelineCache/SavePipelineCacheV0.cs#L28)

I don't mind having to explicitly specify a custom condition `ne(variables['Agent.JobStatus'], 'Cancelled')` to make sure it will always be cached.

The usecase behind is that I am caching an AVD image (for android instrumentedTests) and if there are failing tests on the branch the pipeline is ran, then the AVD will always be downloaded until there is no test failure which is making the cache quite useless in some situations.

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77c20289-dab2-7a6e-4f63-4b30eaff2c71
* Version Independent ID: d75cc196-90c1-8291-9907-ff405bde4edf
* Content: [Pipeline caching - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/caching/?view=azure-devops#gradle)
* Content Source: [docs/pipelines/caching/index.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/caching/index.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @willsmythe
* Microsoft Alias: **wismythe**

**Comment by msebolt** [comment]
@Xexiz Thank you again for providing the details.

As mentioned before, product issues get better support under [azure-pipeline-tasks](https://github.com/microsoft/azure-pipelines-tasks/labels/Area%3A%20PipelineCaching).  If you have any issues with the documentation, please feel free to comment below.

Thank you for your feedback.
