### ISSUE TITLE
Publishing screenshot for failed tests using JUnit is quite complex

### ISSUE THREAD

**Issue by Xexiz** [MicrosoftDocs/vsts-docs#5231]
Hi, after hours trying to get my screenshots in the attachment tab of a Failed Test.. I just found out about these restrictions and I'm kinda disappointed. 

> If you are not using the Visual Studio Test task, you must publish attachments in your test results in a different way:
> 
> If you are running tests in the build (CI) pipeline, you can use the Copy and Publish Build Artifacts task to publish any additional files created in your tests. These will appear in the Artifacts page of your build summary.
> 
> Use the REST APIs to publish the necessary attachments. Code samples can be found in this GitHub repository.
> 

I eventually ended up publishing pipeline artifacts but it really is unusable with this solution. Having to download a zip file every time a test fail is quite inefficient. Using the REST api in an agentless job seems quite a lot of work to achieve this in a pipeline.

Would it be possible to add another option like "Upload test results files" (_not sure what this option does anyway there isn't any additional file attached even when I enable it_) to upload screenshots. Or perhaps just another path like "_Test results files_" but "_Test screenshot files_". I would see this option looking for a file with the testname in a specific location input as additional parameter. 

i.e. For a class `com.example.test.MyInstrumentedTest` with a test named `view_is_displayed` **Test screenshot folder** : ./app/build/reports/androidTests/connected/screenshots/failure/
The content of the test screenshot folder would contain:

- com.example.test.MyInstrumentedTest
  - view_is_displayed.png

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 300d9b37-13c9-a249-451e-1d1340c1b5ff
* Version Independent ID: 68c63219-bd8a-42d2-8dce-940b64efe199
* Content: [Collect screenshots, video, logs, and attachments - Azure Test Plans](https://docs.microsoft.com/en-us/azure/devops/test/collect-screenshots-and-video?view=azure-devops)
* Content Source: [docs/test/collect-screenshots-and-video.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/test/collect-screenshots-and-video.md)
* Product: **devops**
* Technology: **devops-test**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by msebolt** [comment]
@Xexiz Thank you for providing the details.

As mentioned before, product issues get better support under [azure-pipeline-tasks](https://github.com/microsoft/azure-pipelines-tasks/labels/Area%3A%20PipelineCaching).  If you have any issues with the documentation, please feel free to comment below.

Thank you again for your feedback.
