### ISSUE TITLE
Passing Pipeline running user dynamically to Git

### ISSUE THREAD

**Issue by mafiaazul** [MicrosoftDocs/vsts-docs#5232]
Our Pipelines are manually run. 
Is there a way to dynamically set the Git username/email based on who ran the Pipeline?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 024e4ed9-cf8d-155f-5e4a-73c2effaaed8
* Version Independent ID: f19c0538-4aae-b3b4-82b9-422e76723b01
* Content: [Run Git commands in a script - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/scripts/git-commands?view=azure-devops&tabs=yaml#feedback)
* Content Source: [docs/pipelines/scripts/git-commands.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/scripts/git-commands.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @chasewilson
* Microsoft Alias: **phwilson**

**Comment by msebolt** [comment]
@mafiaazul Thank you for the question.

Currently you could achieve this by configuring multiple [build agents](https://docs.microsoft.com/azure/devops/pipelines/agents/agents?view=azure-devops) and then setting specific git info per [agent variables](https://docs.microsoft.com/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml#agent-variables).  The user would then manually select the agent before each run.

For something more automated, perhaps try PowerShell? (see [how to get current user](https://stackoverflow.com/questions/2085744/how-do-i-get-the-current-username-in-windows-powershell) and [using the PowerShell task](https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/powershell?view=azure-devops)).
