### ISSUE TITLE
Set auto-complete by default

### ISSUE THREAD

**Issue by jknapp25** [MicrosoftDocs/vsts-docs#5234]
My team wants to enable auto-complete for all our PR's. We require Product Owner as a PR reviewer and one other developer, and we want the PR to auto-complete when both of these people have approved it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7cd986e0-608c-1d8c-6faf-ecdb12e10bc6
* Version Independent ID: d60c996e-187e-dd6b-7f3a-dd056a1603f4
* Content: [Protect your Git branches with policies - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/branch-policies?view=azure-devops#feedback)
* Content Source: [docs/repos/git/branch-policies.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/repos/git/branch-policies.md)
* Product: **devops**
* Technology: **devops-code-git**
* GitHub Login: @apawast
* Microsoft Alias: **sdanie**

**Comment by jknapp25** [comment]
How do we go about configuring this?

**Comment by msebolt** [comment]
@jknapp25  Thank you for the question.

What you describe is a good candidate for [service hooks](https://docs.microsoft.com/azure/devops/repos/git/create-pr-status-server-with-azure-functions?view=azure-devops), that are basically web service endpoints triggered by things such as a PR update.

From there you need to handle the endpoint, such as a [PowerShell server script](https://hinchley.net/articles/create-a-web-server-using-powershell/) combined with Azure CLI commands using the [pipelines extension](https://docs.microsoft.com/en-us/azure/devops/cli/get-started?view=azure-devops).  The extension allows you to query [PR reviewers](https://docs.microsoft.com/en-us/cli/azure/ext/azure-devops/repos/pr/reviewer?view=azure-cli-latest#ext-azure-devops-az-repos-pr-reviewer-list) and [update the PR](https://docs.microsoft.com/en-us/cli/azure/ext/azure-devops/repos/pr?view=azure-cli-latest#ext-azure-devops-az-repos-pr-update) with **auto-complete**.
