### ISSUE TITLE
Sharing Azure repo to another subscription

### ISSUE THREAD

**Issue by klogan12** [MicrosoftDocs/vsts-docs#5237]
Do we have a way to access repo from different subscription?
In my case , Dev/Test use one subscription and production uses different subscription. 
Azure Dev-Ops is configured on Dev-Test .... When configuing pipelines from Production subscription i do not have access to repo on Dev-Test subscription. 
What is the best way to give repo access?

**Comment by msebolt** [comment]
@klogan12 Thank you for the question.

This depends on how you access your repos.  If you're using the [pipelines Azure CLI](https://docs.microsoft.com/cli/azure/ext/azure-devops/pipelines?view=azure-cli-latest) you can just pull the pipeline schema, [change subscriptions](https://docs.microsoft.com/cli/azure/manage-azure-subscriptions-azure-cli?view=azure-cli-latest), and then add the schema to the second subscription.

Or this can be done [manually](https://stackoverflow.com/questions/50245719/how-do-you-import-a-release-definition-in-azure-devops-vsts).

**Comment by klogan12** [comment]
@msebolt   I access repo via deployment center option that comes with azure repos.
The manual method did not work for me.. My devops on production does not have any repo , so it is not having an import option..
What is the best way to share repo.

**Comment by klogan12** [comment]
This wont work for us. Can pipeline on one subscription deploy to apps in another subscription?
I am using Azure function app , deployment center feature.

**Comment by msebolt** [comment]
The [Azure functions deployment](https://docs.microsoft.com/azure/azure-functions/functions-how-to-azure-devops) has the `azureSubscription` parameter that should allow another subscription to be used.

Vice-versa, the [Azure Function app deployment task](https://docs.microsoft.com/azure/devops/pipelines/tasks/deploy/azure-function-app?view=azure-devops#deployment-methods) also supports an `azureSubscription` parameter.

If there are any further issues, please comment below or [create a support request](https://feedback.azure.com/forums/355860-azure-functions) as this feature should be supported.
