### ISSUE TITLE
needs pointer to new documentation

### ISSUE THREAD

**Issue by wmpauli** [MicrosoftDocs/vsts-docs#5238]
This page (https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/package/conda-environment?view=azure-devops) is documenting a deprecated feature, it mentions that it is deprecated, but does not provide pointers to detailed documentation for what to do instead. It merely states:

> # This task is deprecated. Use `conda` directly in script to work with Anaconda environments.

Which is insufficient.

Thanks

**Comment by msebolt** [comment]
@wmpauli  Thank you for the feedback.

The documentation has been updated and is pending review.
