### ISSUE TITLE
Is SSDT installed a prerequisite?

### ISSUE THREAD

**Issue by guylevy** [MicrosoftDocs/vsts-docs#524]
For on premise build agents (TFS 2018.1), do we have to first install SSDT on the agents to make this work?

Cheers,
Guy

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a56478c9-7dfc-43e9-c348-357dc6862d73
* Version Independent ID: dd3cd0a1-dc03-15d3-1298-b76d770e4760
* Content: [Build your SQL server database](https://docs.microsoft.com/en-us/vsts/build-release/apps/aspnet/build-aspnet-dacpac?view=vsts#qa)
* Content Source: [docs/build-release/apps/aspnet/build-aspnet-dacpac.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/build-release/apps/aspnet/build-aspnet-dacpac.md)
* Service: **unspecified**
* GitHub Login: @erickson-doug
* Microsoft Alias: **alewis**

**Comment by mlearned** [comment]
@guylevy yes VS with SSDT tools will be required on agent side.
