### ISSUE TITLE
Associate an Epic to more than one Releases/Sprints

### ISSUE THREAD

**Issue by hongvu68** [MicrosoftDocs/vsts-docs#5240]
For the purpose of planning, Epics are large and often span several sprints and even several releases. 
But the Iteration field can have only one value.
How can we associate an Epic to multiple sprints or releases.
Thank you
HongVu Le

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4880004e-aae6-a8c7-1aa2-218b6fb00b71
* Version Independent ID: c6e35d98-3b07-2881-536d-0174a71be14d
* Content: [Assign backlog items to a sprint - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/sprints/assign-work-sprint?view=azure-devops#feedback)
* Content Source: [docs/boards/sprints/assign-work-sprint.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/boards/sprints/assign-work-sprint.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by msebolt** [comment]
@hongvu68  Thank you for the question.

When you create **Sprints** (or **Iterations**) you can build them on top of one another.  For instance after you create `\MyProject\LargeSprint`, you could then create `\MyProject\LargeSprint\SmallSprint` and so on.  

Then once you're ready to create an **Epic** and select a **Iteration**, you can choose either `LargeSprint` or `SmallSprint`.
