### ISSUE TITLE
Cannot expand the parent-child hierarchy

### ISSUE THREAD

**Issue by hongvu68** [MicrosoftDocs/vsts-docs#5241]
We use TFS 2019
We have the Epics/Features/Stories linked in parent-child hierarchy.
And we have the config Parent = On.
However, when I click on the +/- sign, the Epic or Feature did not expand.
(I do have this working in another TFS 2019 env )
Is it because, on this env, I have lower access right ?
Or is there a config somewhere in TFS to enable this (in addition to the Parent=On)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7899d58b-c8eb-0ab4-9126-54cbf0de4dc6
* Version Independent ID: ab4d7f52-536e-e3e2-77cf-47581f5cc2d6
* Content: [Organize your product backlog into a hierarchy of items - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/backlogs/organize-backlog?view=azure-devops#feedback)
* Content Source: [docs/boards/backlogs/organize-backlog.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/boards/backlogs/organize-backlog.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by msebolt** [comment]
@hongvu68  Thank you for the question.

I think permissions is of concern here as many correspond directly to **Work Items** access.  

Please check with an administrator to see if the **Expand** feature is still missing.

**Comment by msebolt** [comment]
If there are any further issues, please comment below.
