### ISSUE TITLE
Making fields required and setting them read-only.

### ISSUE THREAD

**Issue by kubsztal** [MicrosoftDocs/vsts-docs#5244]
Hello,

I have three state workflow: New/InProgress/Done. The Description field shall be filled-in before going to InProgress and shall be read-only after going to InProgress. I can't find a setup of custom rules, which would make this working. I've tried the following:

Setup 1:
Custom rule 1a:
When A work item state changes to InProgress Then Make required Description.
Custom rule 1b:
When A work item state is InProgress Then Make read-only Description.

This causes that the Description field is made read-only immediately after selecting InProgress state. I'd expect, that Custom rule 1b should prevent transitioning to InProgress if the Description field is still empty.

Setup 2:
Custom rule 2a:
When A work item state changes to InProgress Then Make required Description.
Custom rule 2b:
When A work item state is InProgress And A value is defined for Description Then Make read-only Description.

In this case after selecting InProgress state and typing just first letter into Description field the following error pops-up: "The value for field 'Description' must be the same as the original value"... No idea what does it mean.

https://docs.microsoft.com/en-us/azure/devops/organizations/settings/work/custom-rules

**Comment by kubsztal** [comment]
It seems this is already known bug... Really, no intention to fix it?
https://developercommunity.visualstudio.com/content/problem/383000/use-of-required-then-read-only-in-work-item-rules.html

**Comment by kubsztal** [comment]
"that Custom rule 1b should prevent transitioning" - here I meant rule 1a, sorry for the mistake.

**Comment by danhellem** [comment]
Try the following:

Custom rule 1a:
When A work item state changes to InProgress Then Make required Description.

Custom rule 1b:
When A work item state is InProgress and no change was made to the value of ‘State changed date’ Then Make read-only Description.

**Comment by kubsztal** [comment]
Works perfectly, thanks!
