### ISSUE TITLE
Document benefits of setting up web app with this task over IIS Web App Deploy

### ISSUE THREAD

**Issue by CoolDadTx** [MicrosoftDocs/vsts-docs#5248]
I can find no resources anywhere that clarify why you would use this task over the IIS Web App Deploy task. It is clear that the Deploy task uses WebDeploy and that it doesn't have as many bells and whistles but in terms of creating/updating a web app and deploying it they both do the same thing.

In examples that I see you use IIS Web App Manage to set up the web app/pool and then use IIS Web App Deploy to deploy the web app itself. However IIS Web App Manage also supports setting up a web application (in addition to other things) so when would we use IIS Web App Manage to set up the pool/app vs just setting up the pool with IIS Web App Manage and letting IIS Web App Deploy set up the application while it deploys?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 244121ae-5de4-14cd-a9c3-d9cda5ad0a3b
* Version Independent ID: 313238b7-d67b-bc60-1188-cbe305179600
* Content: [IIS Web App Manage task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/iis-web-app-management-on-machine-group?view=azure-devops#feedback)
* Content Source: [docs/pipelines/tasks/deploy/iis-web-app-management-on-machine-group.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/deploy/iis-web-app-management-on-machine-group.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by CoolDadTx** [comment]
Nevermind on this. I took another look at the Deploy task and it does seem to just provide deployment options, not set up options.

**Comment by RoopeshNair** [comment]
IIS Manage task provides management capabilities such as create website, app pool etc. Feel free to reopen if you still have queries
