### ISSUE TITLE
Push your changes to a new branch on the origin remote and set the upstream branch

### ISSUE THREAD

**Issue by RandyDaddis** [MicrosoftDocs/vsts-docs#5253]
It would be helpful for this article to provide steps (or a link to steps) to perform the first commit in order to resolve the "The current branch does not track a remote branch" exception.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6d5ca6b5-523a-21d0-26f3-567846f7c298
* Version Independent ID: c712c338-46d6-a70a-0ba1-0d1ec3cd6ac7
* Content: [Sync your changes to a remote Git repo - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/pushing?view=azure-devops&tabs=visual-studio#feedback)
* Content Source: [docs/repos/git/pushing.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/repos/git/pushing.md)
* Product: **devops**
* Technology: **devops-code-git**
* GitHub Login: @apawast
* Microsoft Alias: **sdanie**

**Comment by RandyDaddis** [comment]
My issue was resolved by correcting the user email address in Visual Studio | Team Explorer | Repository Settings | User Email Address

**Comment by msebolt** [comment]
@RandyDaddis Thank you for the feedback.

The documentation has been updated and is pending review.
