### ISSUE TITLE
Story Points <> (leave Value field blank) doesnt appear to work

### ISSUE THREAD

**Issue by jasonslemons** [MicrosoftDocs/vsts-docs#5254]
when trying to query stories without story points(ie they need to be pointed) i tried "Story Points &lt;&gt; " (with nothing in the third column). This doesn't appear to return stories with no points(as indicated near the top of this page). Instead it returns all stories with point values that aren't blank. So... the opposite of what I wanted.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 432a3f21-2831-139f-77dd-752a32266e55
* Version Independent ID: a2201ee3-4a7b-7f34-d73f-3b687be104eb
* Content: [Query by numeric field - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/queries/query-numeric?view=azure-devops#feedback)
* Content Source: [docs/boards/queries/query-numeric.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/boards/queries/query-numeric.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@jasonslemons - Thank you for your inquiry. I'm updating the topic to indicate how to query on blank numeric fields. You need to use the = operator and then leave the Value blank. Here is the information: 

You can find work items that have an undefined field value by using the equals operator (=) and leaving the Value for the field blank. For example, the following filters will list all work items of type User Stories whose Story Points field is blank.  

![image](https://user-images.githubusercontent.com/10856840/63200782-6151dd00-c037-11e9-9e38-a7561dfc471c.png)
