### ISSUE TITLE
Vague explanation 

### ISSUE THREAD

**Issue by mibalago** [MicrosoftDocs/vsts-docs#5257]
Organizations in Azure DevOps Services get their own URLs (for example, https://dev.azure.com/fabrikamfiber), and they always have exactly one project collection. Organizations can have many projects, such as project collections.

The above statement is contradictory kindly rectify it

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 808dac3a-225a-f564-ea5e-de6bad168da4
* Version Independent ID: decabfe6-ae8d-183c-3698-acb829da81f5
* Content: [Understand differences between Azure DevOps Services and Azure DevOps Server - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/user-guide/about-azure-devops-services-tfs?view=azure-devops#feedback)
* Content Source: [docs/user-guide/about-azure-devops-services-tfs.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/user-guide/about-azure-devops-services-tfs.md)
* Product: **devops**
* Technology: **devops-new-user**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @mibalago, Thanks very much for letting us know! I've just completed a PR rectifying this.
