### ISSUE TITLE
Unable to add Azure AD group to an Azure DevOps Organization

### ISSUE THREAD

**Issue by jpzwarte** [MicrosoftDocs/vsts-docs#5265]
I came here from this article: https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/manage-azure-active-directory-groups?view=azure-devops

Our organisation is connected to Azure AD. Instead of adding individual users to an organisation so they can contribute to a project, i'm trying to add a *group* to an organisation. However, the screenshots in the article do not match the current UI.

All i see in the Organisation Settings is the ability to add individual users (Organisation Settings -> General -> Users -> Add)

So is what i'm trying to do possible? If so, how?

**Comment by chcomley** [comment]
Hi @jpzwarte, Thanks for reaching out. I'm following up on this and will be in touch shortly. Thank you!

**Comment by chcomley** [comment]
Hi @jpzwarte, When you assign permissions to an Azure AD group in the Permissions settings page, all users in that group get access. However, users must accept their invitation to join the Azure DevOps organization to materialize in the user hub as a member of the organization. 

In short – assign permissions to the group and have users sign into the Azure DevOps organization.

Please let us know if you need any further clarification. Have a great day!
