### ISSUE TITLE
Build.SourceVersionMessage should note that it is not available on stage and job level

### ISSUE THREAD

**Issue by trajano** [MicrosoftDocs/vsts-docs#5268]
Per my discussion https://chat.stackoverflow.com/transcript/message/47063725#47063725

The `Build.SourceVersionMessage` should state something like

&gt; This variable is only available on the `step` level.  It is neither available in the `job` nor `stage` levels as the message is not extracted until the job had started and checked out the code.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ffebdc8-521c-44b5-cde4-4abdc1bd6f18
* Version Independent ID: dc0effda-6d93-62aa-64c5-4e6f283b0826
* Content: [Predefined variables - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/build/variables.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/build/variables.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
Closing manually since merging the PR didn't close it
