### ISSUE TITLE
Users without permission showing as updating group membership in audit logs

### ISSUE THREAD

**Issue by huntleyh** [MicrosoftDocs/vsts-docs#5269]
We are seeing audit entries for users being removed as a member of a [AzDoOrgName]\DirectoryServiceAddMember<SOMEGUID>-Group. However the user specified in ActorDisplayName did not perform these tasks and also does not have the permission to perform this task.

Any idea on why this is happening?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 52f60b32-5c3c-f01a-cbbf-f4e9bd17a3fc
* Version Independent ID: 94753ea7-b465-f92e-10c2-8b17d995e4ff
* Content: [Access, export, filter audit logs for Azure DevOps - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/settings/azure-devops-auditing?view=azure-devops)
* Content Source: [docs/organizations/settings/azure-devops-auditing.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/settings/azure-devops-auditing.md)
* Product: **devops**
* Technology: **devops-settings**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
HI @huntleyh, Sorry to hear you're having difficulties. Please contact [Technical Support](https://visualstudio.microsoft.com/vs/support/#talktous), they ay want to look at specific data related to your organization. Thank you.
