### ISSUE TITLE
Missing an example of how to pass variables across stages

### ISSUE THREAD

**Issue by trajano** [MicrosoftDocs/vsts-docs#5272]
You have one for dependent jobs but not for dependent stages

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd7e0bd3-1f7d-d7b6-cc72-5ef63c31b46a
* Version Independent ID: dae87abd-b73d-9120-bcdb-6097d4b40f2a
* Content: [Variables - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch#allow-at-queue-time)
* Content Source: [docs/pipelines/process/variables.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/variables.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by simpers** [comment]
Is this possible today? I attempted converting our current pipeline to the new stage-based one but a variable wasn't passed between stages and nothing works so I had to revert. If so, how do I set it up?

**Comment by trajano** [comment]
I haven't my workaround is to store it as part of the pipeline artifacts.

**Comment by tgdane** [comment]
Also looking for this, for the moment writing the variable to a file and uploading that as an artifact, which is pretty clunky.

**Comment by Justin-DynamicD** [comment]
Add me to the list of those looking.

I have a few theories on the "how" but I'd rather avoid potential days of trial and error.

**Comment by kishoregp** [comment]
Any update on this?

**Comment by simpers** [comment]
My work-around was not that dramatic as I already had a script that creates the value, so I just rerun it later in the new stage(s), but it does not feel elegant to have to do that.

**Comment by Justin-DynamicD** [comment]
As far as I can tell, there is no way to natively move variables between stages as they are effectively as separate as classic build and release pipelines.  As such the only real option is to treat them like config settings that need to be bundled with an artifact and save them as a json or similar to re-import into later stages as needed.

The biggest "hang up" for me personally is that it means it becomes much harder to use the `dependsOn` parameter to gate later stages based on things like build results (only run deploy stage if build stage results in a change, for example)

**Comment by juliakm** [comment]
This is not supported right now. You can make a feature request to the product team at the [Azure DevOps Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html).
