### ISSUE TITLE
Try sign in but authorization failed

### ISSUE THREAD

**Issue by bigfox** [MicrosoftDocs/vsts-docs#5274]
I try command `/azpipelines signin`  in Slack channel.
After the redirects, I ended up on the page `https://azchatopprodcus1.azchatops.visualstudio.com/slackintegrationoauth/callback?error=InvalidScope` with message `Authorization failed. Please try again.`.

What am I doing wrong?

I am DevOps project admin ... I tried the procedures from the section 'Troubleshooting', but none helped.
Can you help me?

Thank you in advance.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 99a6f5aa-7e92-a028-d13e-e1e4b7fede86
* Version Independent ID: be7e5d7c-0033-6b72-4bd1-809f7d1894aa
* Content: [Azure Pipelines with Slack - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/integrations/slack?view=azure-devops#feedback)
* Content Source: [docs/pipelines/integrations/slack.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/integrations/slack.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @atinb
* Microsoft Alias: **atinb**

**Comment by atinb** [comment]
@bigfox Can you please mail us at AzureDevOpsSlackApps at microsoft dot com so that we can get on a call with you to figure this out? Thanks!

**Comment by bigfox** [comment]
Today i tried it again (same procedure as I wrote above) and it works!
