### ISSUE TITLE
YAML snippet input 'targetPath' does not match arguments list variable 'path'

### ISSUE THREAD

**Issue by Tankatronic** [MicrosoftDocs/vsts-docs#5275]
'targetPath' is used in the YAML snippet here:
https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/publish-pipeline-artifact?view=azure-devops#yaml-snippet

'path' is used as an example in the Arguments section here:
https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/publish-pipeline-artifact?view=azure-devops#arguments

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 41baa0b5-175c-a697-4b7d-c150259c6e6b
* Version Independent ID: 75085b15-1acc-526a-0495-74a13c42c1d5
* Content: [Publish Pipeline Artifacts task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/publish-pipeline-artifact?view=azure-devops#yaml-snippet)
* Content Source: [docs/pipelines/tasks/utility/publish-pipeline-artifact.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/utility/publish-pipeline-artifact.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @willsmythe
* Microsoft Alias: **wismyth**

**Comment by richardgavel** [comment]
I wonder if this changed between 0.x and 1.x of the task. I have a 0.x version using targetPath appropriately. Got bit using 1.x without realizing.
