### ISSUE TITLE
Can I move pull requests?

### ISSUE THREAD

**Issue by alexsandro-xpt** [MicrosoftDocs/vsts-docs#5280]
Is this move all Pull Request maded and all Pipelines?

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: b779541e-e77e-38e7-7134-fa1f4c698899
* Version Independent ID: fe82ec27-4640-d0f2-3978-01400e2b719b
* Content: [Move Git repositories between Team Projects](https://docs.microsoft.com/pt-br/azure/devops/repos/git/move-git-repos-between-team-projects?view=azure-devops)
* Content Source: [docs/repos/git/move-git-repos-between-team-projects.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/repos/git/move-git-repos-between-team-projects.md)
* Product: **devops**
* Technology: **devops-whitepapers**
* GitHub Login: @wpschaub
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
@alexsandro-xpt I don't think you can move pull requests and pipelines using this functionality. If your pipelines is a YAML pipeline, the YAML file will move (as part of your Git repository) but you may have to set the pipeline back up. You would also need to create new pull requests from the migrated branches.

**Comment by alexsandro-xpt** [comment]
@steved0x You said `If your pipelines is a YAML pipeline, the YAML file will move (as part of your Git repository)`

But I guess, I will lose all build history.
