### ISSUE TITLE
How are stage approvals set in YAML?

### ISSUE THREAD

**Issue by henry-padilla** [MicrosoftDocs/vsts-docs#5283]
I don't see anything addressing stage approvals in YAML pipelines. Is this gone? Do we register the pipeline in some way? Even a note saying it's being addressed would be helpful.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4266f72c-c774-0046-4593-d01eb775d3c3
* Version Independent ID: f20827aa-a6c5-96a8-5969-e576ffbc2e38
* Content: [Stages in Azure Pipelines - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/stages?view=azure-devops&tabs=yaml#feedback)
* Content Source: [docs/pipelines/process/stages.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/stages.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @vijayma
* Microsoft Alias: **vijayma**

**Comment by DanHK** [comment]
Seems that approvals are implemented as environment checks as documented here: https://docs.microsoft.com/fr-fr/azure/devops/pipelines/process/checks?view=azure-devops

**Comment by henry-padilla** [comment]
Thank you so much!
This is a huge help. I’ll look into this.

Henry Padilla
Senior Development Engineer, ML Development
Tax & Accounting North America

Office +1 469-528-2732
Henry.Padilla@wolterskluwer.com<mailto:Henry.Padilla@wolterskluwer.com>

**Comment by henry-padilla** [comment]
Ok, that is what I needed, thanks. Can we get a reference to that placed on the YAML page? The only "reference" as far as I can see is the "environment" field in the YAML and that only mentions in passing.

**Comment by juliakm** [comment]
There is an approvals section now that addresses this issue - https://docs.microsoft.com/en-us/azure/devops/pipelines/process/stages?view=azure-devops&tabs=yaml.
