### ISSUE TITLE
Looks very strange to me

### ISSUE THREAD

**Issue by Interface007** [MicrosoftDocs/vsts-docs#5287]
It may be a very strange idea, but when I'm searching for help with "creating a new pipeline on Azure DevOps Server 2019" (a Microsoft product for on-prem usage), I would expect to have a step by step guide to create a pipeline on "Azure DevOps Server" with de default language of Microsoft (until recently this was C#) which does not assume that I have a GitHub account (I'm using "Azure DevOps Server", because I cannot reach online resources). If I'm wrong, you might announce that Java is the new default language for Microsoft developers and GitHub is the default place for repositories and you don't want to support on-prem any more.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7336a04e-5b38-d02f-8bba-a55445b2f094
* Version Independent ID: 783c30b3-63b6-da7c-1336-b000bb8b4c66
* Content: [Create your first pipeline - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/create-first-pipeline?view=azure-devops&tabs=tfs-2018-2#feedback)
* Content Source: [docs/pipelines/create-first-pipeline.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/create-first-pipeline.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
@Interface007 If you go to this article, and select Azure DevOps Server 2019 from the upper left, the scenario demonstrated is a YAML pipeline from an Azure Repos Git repository in the same project, and it doesn't use GitHub. Please give that a try and see if that sample scenario matches more closely with how you are using the product.
![image](https://user-images.githubusercontent.com/1580889/63361232-bcd4e100-c33d-11e9-961e-3d6c3719a8ee.png)

Thank you for your feedback and sorry that you ran into trouble.
