### ISSUE TITLE
Incorrect general link at Get a list of commits

### ISSUE THREAD

**Issue by Volkmire** [MicrosoftDocs/vsts-docs#5289]
Link should not contain /repos/.
Probably all other occurrences are wrong as well. 
Tested on TFS2017U2

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6801055d-5579-6018-2aa0-a8f087b56f86
* Version Independent ID: 8010590d-097b-d7ff-d422-df03317fa256
* Content: [Git Commits](https://docs.microsoft.com/en-us/azure/devops/integrate/previous-apis/git/commits?view=tfs-2017#feedback)
* Content Source: [docs/integrate/previous-apis/git/commits.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/integrate/previous-apis/git/commits.md)
* Product: **devops**
* Technology: **devops-ecosystem**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
@Volkmire, Thank you for letting us know. I've created a user story for my backlog to address this.

**Comment by chcomley** [comment]
Thanks @Volkmire, I've addressed this issue, which should go live this afternoon. Thanks so much for the heads up! I've linked the PR to this issue, also.
