### ISSUE TITLE
404 on hyperlink 

### ISSUE THREAD

**Issue by julianparismorgan** [MicrosoftDocs/vsts-docs#529]
In this sentence, "Widgets can call any of the REST APIs in VSTS to interact with VSTS resources.", the hyperlink on REST APIs leads to https://www.visualstudio.com/integrate/api/overview.md, which throws a 404.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bbe9c938-dde5-4eba-6e09-6e43ef0e8ee5
* Version Independent ID: 53f9961e-1c31-1080-1699-4ef901939b19
* Content: [Add a dashboard widget](https://docs.microsoft.com/en-us/vsts/extend/develop/add-dashboard-widget?view=vsts)
* Content Source: [docs/extend/develop/add-dashboard-widget.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/extend/develop/add-dashboard-widget.md)
* Service: **unspecified**
* GitHub Login: @erickson-doug
* Microsoft Alias: **elbatk**

**Comment by elbatk** [comment]
Ah, thanks for letting me know, @julianparismorgan ! I've fixed the link to point to the suggestion that @steved0x provided, as it is the correct one! It should be live within 24 hours. Cheers :)
