### ISSUE TITLE
Azure DevOps Office Integration

### ISSUE THREAD

**Issue by segraef** [MicrosoftDocs/vsts-docs#5290]
Hi there, what about exchanging the old TFS integration with Azure DevOps Office Integration 2019 which also support Office 365 and Office 2019?

https://go.microsoft.com/fwlink/?linkid=2076587&clcid=0x409

**Comment by WilliamAntonRohm** [comment]
Thanks for the suggestion! The product teams aren’t always watching this repository, so to make sure it gets in front of them for triage, please [submit your idea]( https://developercommunity.visualstudio.com/content/idea/post.html?space=21) here.
