### ISSUE TITLE
Screenshots do not match up to tfs 2018

### ISSUE THREAD

**Issue by theoriginalcole** [MicrosoftDocs/vsts-docs#5292]
This only shows it for Azure devops, but says it is for tfs 2018 and earlier

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8753a98e-77ca-265d-d5e3-91a4b1319e5e
* Version Independent ID: bed9697d-3bea-3202-0bf1-80f37aea0286
* Content: [Define/plan your product backlog of user stories, issues, backlog items, or requirements - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/backlogs/create-your-backlog?view=azure-devops#feedback)
* Content Source: [docs/boards/backlogs/create-your-backlog.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/boards/backlogs/create-your-backlog.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@theoriginalcole - THank you for your inquiry. To view the content for TFS 2018, make sure that you have selected TFS 2018 from the version selector. The URL will change to: 
https://docs.microsoft.com/en-us/azure/devops/boards/backlogs/create-your-backlog?view=tfs-2018#feedback

The version selector is located above the table of contents. 

![image](https://user-images.githubusercontent.com/10856840/63305536-1dabdd00-c29c-11e9-89ae-3dc46f373f04.png)
