### ISSUE TITLE
No Guidance on ACR Authentication Setup/Requirements

### ISSUE THREAD

**Issue by ericdrobinson** [MicrosoftDocs/vsts-docs#5293]
This documentation sends us to the [ACR Quickstart](https://docs.microsoft.com/en-us/azure/container-registry/container-registry-get-started-portal) guide which defaults to having the "Admin User" setting **disabled**. According to [the documentation](https://docs.microsoft.com/en-us/azure/container-registry/container-registry-authentication#admin-account) _(emphasis mine)_:

>The admin account is designed for a single user to access the registry, **mainly for testing purposes**.

This documentation, however, [goes on to suggest](https://docs.microsoft.com/en-us/azure/devops/pipelines/languages/docker?view=azure-devops#push-an-image) that we can:

>get the admin user name and password from the **Access keys** section of the registry in the Azure portal.

which... is disabled by default and "mainly used for testing". This leads me to the following two questions:

1. Is there another way to authenticate here or is the Admin user required?
2. If the Admin user is required, can you expand this documentation with a note about enabling the Admin user and mention that, "yes, this is required"?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e825c07d-2168-c0aa-782a-ef6f9c7ba95e
* Version Independent ID: 5cb6926b-215a-bf89-8e63-b2e1129e41df
* Content: [Build, test, and push Docker container apps - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/languages/docker?view=azure-devops)
* Content Source: [docs/pipelines/languages/docker.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/languages/docker.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @vijayma
* Microsoft Alias: **vijayma**

**Comment by ericdrobinson** [comment]
After running around for a couple of hours researching [Service Principles](https://docs.microsoft.com/en-us/azure/container-registry/container-registry-auth-service-principal), I attempted to set one up (poorly) only to find that after I adjusted the Docker Task to use the `buildAndPull` task, Azure Pipelines indicated that there was an issue and pointed me towards something called the **Service Connection**.

It turns out that Pipelines appears to have this really cool feature called [Service Connections](https://docs.microsoft.com/en-us/azure/devops/pipelines/library/service-endpoints) that can be configured to allow the Pipeline to connect to various Azure (and other) resources (including an [Azure Container Registry](https://docs.microsoft.com/en-us/azure/devops/pipelines/library/service-endpoints?view=azure-devops&tabs=yaml#sep-docreg)). **This should be highlighted in the documentation.** The "Service Connection" term is mentioned but it is not linked. Please make that a link (and possibly capitalize it) as it helps call attention to it as a "Feature".

**Comment by shashankbarsin** [comment]
@ericdrobinson we've update the documentation for container ecosystem recently. References to [Docker registry service connection](https://docs.microsoft.com/en-us/azure/devops/pipelines/library/service-endpoints?view=azure-devops#sep-docreg) have been included under the guidance on [pushing the images to the container registries](https://docs.microsoft.com/azure/devops/pipelines/ecosystems/containers/push-image?view=azure-devops).

**Comment by ericdrobinson** [comment]
@shashankbarsin That's great - a **_vast_** improvement over the previous documentation. Thanks very much for adding it.

I would suggest that you do a grammar pass, however, as there are many simple-yet-distracting grammatical issues with [the document](https://docs.microsoft.com/en-us/azure/devops/pipelines/ecosystems/containers/push-image?view=azure-devops) in its current form.
