### ISSUE TITLE
Dotnet test - DotNetCLI@2?

### ISSUE THREAD

**Issue by qwertoyo** [MicrosoftDocs/vsts-docs#5296]
# Run tests and publish test results.
`- task: DotNetCLI@2`
`  inputs:`
`    command: 'test'`

I think we want to 'DotNetCoreCLI@2' there, I did a [blind] copypasta and the pipeline could not start because of the lack of task installed. Changed to 'DotNetCoreCLI@2', tests are run.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d1d9884-19f7-592b-f47c-8cf100639ff0
* Version Independent ID: 555c3826-60d9-2589-54af-850efbfbb13a
* Content: [.NET Core CLI task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/dotnet-core-cli?view=azure-devops)
* Content Source: [docs/pipelines/tasks/build/dotnet-core-cli.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/build/dotnet-core-cli.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @pulkitaggarwl
* Microsoft Alias: **puagarw**

**Comment by damccorm** [comment]
Thanks for the feedback! It looks like this has been fixed as there are no more references to `DotNetCLI@2` in the linked file, so I'm going to close.
