### ISSUE TITLE
Question about comment governance

### ISSUE THREAD

**Issue by VOVELEE** [MicrosoftDocs/vsts-docs#5300]
Hi team,

good addition to wiki functionality :) I have the following questions:
- Is there a role which can be used as comment moderator? The current implementation allows comments to be deleted only by the user who created the comment
- Is there any notification mechanism that new comment is created?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c85ebb83-c49f-e784-70b5-30c0ac01682b
* Version Independent ID: dc859870-0b8f-bee5-0b2f-e6b2aa3260c6
* Content: [Add comments to wiki pages - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/project/wiki/add-comments-wiki?view=azure-devops#feedback)
* Content Source: [docs/project/wiki/add-comments-wiki.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/project/wiki/add-comments-wiki.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @VOVELEE, I've followed up with our PM, so we'll get back to you as soon as possible on this. Thanks for reaching out!

**Comment by chcomley** [comment]
Hi @VOVELEE, Here are answers to your questions:
•	Is there a role which can be used as comment moderator? The current implementation allows comments to be deleted only by the user who created the comment
ANSWER: Comments are currently controlled by the “contribute” permission. There is no new permission introduced for comments. Also, there is no concept of moderators in wiki. 
•	Is there any notification mechanism that new comment is created?
ANSWER: A notification email is sent when a user is @mentioned in the comments.
Hope this helps. Thank you and have a great day!
