### ISSUE TITLE
PowerShell 2.* task documentation

### ISSUE THREAD

**Issue by dragosd** [MicrosoftDocs/vsts-docs#5304]
In my case it looked like having a variable named `Path` was causing the release to fail on a PowerShell 2.* task with the following message:
> ___
> Task         : PowerShell
> Description  : This is an early preview. Run a PowerShell script on Windows, macOS, or Linux.
> Version      : 2.129.0
> Author       : Microsoft Corporation
> Help         : [More Information](https://go.microsoft.com/fwlink/?LinkID=613736)
> ___
> Generating script.
> ##[error]The term 'powershell.exe' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
> ___

In this context it might be argued that the error message is explicit enough, but it wasn't obvious to me that the task was complaining about the `Path` release variable itself. I think that this behavior should be documented, as I couldn't find any reference to it anywhere else.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 611642f0-881f-10b9-ae94-3c562001d1f0
* Version Independent ID: 41efb94b-4c7a-64a3-b23b-70c8634ae727
* Content: [Release variables and debugging - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/variables?view=azure-devops&tabs=batch)
* Content Source: [docs/pipelines/release/variables.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/release/variables.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by chasewilson** [comment]
hi @dragosd, Thank you for your feedback.  Would it be possible to see a scrubbed version of your usage of the task?

**Comment by dragosd** [comment]
This is an export of a test release containing a single task that can be used to reproduce the issue. I've replaced all Guids with empty ones and renamed URLs/org/project names:

[PowerShell Task Test.json.txt](https://github.com/MicrosoftDocs/vsts-docs/files/3521737/PowerShell.Task.Test.json.txt)

There is a single task for PowerShell 2.* (preview) which just simply writes the variable:
![image](https://user-images.githubusercontent.com/1088837/63367667-5bffd580-c34a-11e9-91aa-3b8f01a00422.png)

This is the variable definition:
![image](https://user-images.githubusercontent.com/1088837/63367699-6d48e200-c34a-11e9-80c0-51e1f4612fa9.png)

This is the output:
[PowerShell Task Test.log.output.txt](https://github.com/MicrosoftDocs/vsts-docs/files/3521783/PowerShell.Task.Test.log.output.txt)

As soon as I rename `Path` to anything else, like `OkPath` the task completes successfully.

**Comment by dragosd** [comment]
Here is the output with `OkPath` instead:
[PowerShell Task Test-Ok.log.output.txt](https://github.com/MicrosoftDocs/vsts-docs/files/3521817/PowerShell.Task.Test-Ok.log.output.txt)

**Comment by chasewilson** [comment]
@dragosd, Thanks for the great, detailed response! You can see in the logs you have posted:
```
2019-08-20T16:52:20.9678236Z Environment variables available are below...
...
[PATH] --> [ok value]
```
In PowerShell in a Windows environment the path environment variable, `$env:Path`, references the windows path environment variable. When you replace that in your pipeline, the OS no longer nows how to get to PowerShell. 

Does that make sense?

**Comment by dragosd** [comment]
@chasewilson, yes it makes sense, as in the end I noticed the same thing. The reason that I opened this issue is that I was expecting this behavior to be documented. It's not an obvious reason for why the failure occurs, unless you are aware that pipeline variables will clash with the environment ones.

**Comment by chasewilson** [comment]
I understand, I think it might be difficult to document every scenario like this, I might be able to place a not to be aware of predefined language variables. Do you think that would be have helped you avoid some of the confusion?

**Comment by dragosd** [comment]
Yes, it would be helpful. Thanks!

**Comment by chasewilson** [comment]
I've created a note @dragosd. Thanks for all of your help and input! :) You should see the update within 24 hours
