### ISSUE TITLE
Please list the supported Azure sub types right here in this document

### ISSUE THREAD

**Issue by MS-Trev** [MicrosoftDocs/vsts-docs#531]
I've just had a customer follow this doc but they created a Free Trial AzSub because they didn't know any different and we didn't tell them. Now they have to muddle through the process of converting that to a PAYG or making a new one and doing an unlink\link for billing. What should have been a 15 minute process has doubled, or more.

We should really list the supported AzSub types at the top of this page, right below "If you don't have an Azure subscription, create a free account before you begin." to avoid this sort of thing. To be fair, we do provide this info on https://docs.microsoft.com/en-us/vsts/billing/vsts-billing-faq?view=vsts, but THIS doc doesn't even link to that (!?!), or I'm missing it. Either way I really think we need to list it here, regardless.

Please consider doing this to improve customer's experience. Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 191874e5-83ef-ee35-2c83-b7acc00875c4
* Version Independent ID: b758aeb1-ca2c-0984-b3ff-c5a4d5fbffd9
* Content: [Set up billing for VSTS](https://docs.microsoft.com/en-us/vsts/billing/set-up-billing-for-your-account-vs?view=vsts)
* Content Source: [docs/billing/set-up-billing-for-your-account-vs.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/billing/set-up-billing-for-your-account-vs.md)
* Service: **unspecified**
* GitHub Login: @erickson-doug
* Microsoft Alias: **chcomley**

**Comment by steved0x** [comment]
@MS-Trev @chcomley I'm sorry I somehow missed this one, we are taking a look now. Thank you.

**Comment by chcomley** [comment]
Thank you @MS-Trev, you should have a MSFT email in your Outlook, adding Zack A. for further investigation and guidance.
