### ISSUE TITLE
Maven Release plugin has issues with TFS 2015

### ISSUE THREAD

**Issue by davedoc** [MicrosoftDocs/vsts-docs#5310]
When you use the Options field the Release Plugin will put the values in a release.properties file. Maven will then attempt to check for changes with TFS and TFS will respond that it's not up to date because there is a new release.properties file not checked in.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 589e076c-9f67-77df-3204-4f549566f21b
* Version Independent ID: 2e51ef13-8fd3-1397-82f0-27c92f1ccee5
* Content: [Maven build and release task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/maven?view=azure-devops#feedback)
* Content Source: [docs/pipelines/tasks/build/maven.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/build/maven.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @DavidStaheli
* Microsoft Alias: **dastahel**

**Comment by msebolt** [comment]
@davedoc  Thank you for the feedback.

Since this is a product issue, please move this to [azure-pipelines-tasks](https://github.com/Microsoft/azure-pipelines-tasks/issues) for better support.

**Comment by davedoc** [comment]
Thank you Matt. Created an issue there, #11177

**Comment by msebolt** [comment]
@davedoc  You're welcome.

Thank you again for providing feedback.  Closing the issue.
