### ISSUE TITLE
It is not possible to just copy a virtual environment to a new machine

### ISSUE THREAD

**Issue by Armcollector** [MicrosoftDocs/vsts-docs#5311]
Hi,

The methodology used here does not work for python3.7.  Virtual environments cannot be copied to new machines and run there.  pip will retain a symlink to the original python installation (which does not exist on the new computer).    When your BuildGeneratorScript tries to upgrade pip it will fail.

see for example discussion here about what will happen if you remove orginal python installation for the virtual enviroment (copying venv to new machine is equivalent):

https://stackoverflow.com/questions/55025873/consequences-for-virtual-env-when-systems-python-is-removed-and-or-updated

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eefdcb17-b1e5-141c-aef8-36795c9983af
* Version Independent ID: 007ebfcf-12bf-755c-858b-540d0fc59f96
* Content: [Build and deploy Python web apps - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/languages/python-webapp?view=azure-devops#feedback)
* Content Source: [docs/pipelines/languages/python-webapp.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/languages/python-webapp.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @kraigb
* Microsoft Alias: **kraigb**

**Comment by br0cky** [comment]
Hi there,

Just to let you know in step 6, the final yaml template still has the step to install the virtual env and install dependencies, which will break when zipped and transferred over to the app service. 

Also, i found a simple method to push changes over to the App Service which doesn't involve zipping the entire directory each time and overwriting the App Service. Instead it simply uses git to push any modified files over to the App Service. The steps are included as part of this guide - https://www.youtube.com/watch?v=OMtpVqzpJ9w
