### ISSUE TITLE
Output parameters

### ISSUE THREAD

**Issue by MisinformedDNA** [MicrosoftDocs/vsts-docs#5312]
I think this page should discuss or link to a topic on accessing variables outputted within a template to be accessed by the parent pipeline.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6724abea-bbdc-bf66-ed5e-3214fa6c3e66
* Version Independent ID: 4f8dab21-3f0e-da32-cc0e-1d85c13c0065
* Content: [Job and step templates - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/templates?view=azure-devops#passing-parameters)
* Content Source: [docs/pipelines/process/templates.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/templates.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @vtbassmatt
* Microsoft Alias: **macoope**

**Comment by MisinformedDNA** [comment]
@steved0x @msebolt This didn't address my concern at all. I wasn't asking about variable groups, I was asking about a variable being set in a Template and then having that variable accessed by a parent Template.

**Comment by msebolt** [comment]
Closing this issue now.  Please comment below if there are any concerns.
