### ISSUE TITLE
Update documentation for the new UI

### ISSUE THREAD

**Issue by saciervo** [MicrosoftDocs/vsts-docs#5319]
Where can "Package Management" be found in the new UI anyways? I couldn't find it in the project settings anywhere.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4005817f-e61c-62fb-b40e-12463425b41a
* Version Independent ID: 2d6bff7b-159e-2729-3c66-451fce339c3d
* Content: [License Azure Artifacts for TFS 2017 and 2018](https://docs.microsoft.com/en-us/azure/devops/artifacts/license-azure-artifacts?view=tfs-2018#feedback)
* Content Source: [docs/artifacts/license-azure-artifacts.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/artifacts/license-azure-artifacts.md)
* Product: **devops**
* Technology: **devops-artifacts**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by msebolt** [comment]
@saciervo  Thank you for the question.

Until the documentation has been addressed, please refer to [Package Management is now Azure Artifacts](https://docs.microsoft.com/en-us/azure/devops/artifacts/where-is-package-management?view=azure-devops).

**Comment by chcomley** [comment]
Hi @saciervo, I've published an update to the article, adding information for Azure DevOps Server 2019. I'm hoping the link that was previously sent to you answered your question. The update should be live sometime within the next few hours. Thanks!
