### ISSUE TITLE
How to reuse tasks between CI triggers and PR triggers?

### ISSUE THREAD

**Issue by erinha** [MicrosoftDocs/vsts-docs#5322]
I have a build pipeline that is triggered by CI on check-ins to master and want to add a PR trigger. The build includes publishing steps that I'd like to not occur when the build is triggered by a PR. Is there a way to use the same build pipeline but set a variable based on how the build is triggered?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5673ec1-c7d1-e0ac-043a-8fc3d5b226a9
* Version Independent ID: b4872831-51c0-6cf8-1c56-de20beb38a80
* Content: [Build pipeline triggers - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/triggers?view=azure-devops&tabs=classic)
* Content Source: [docs/pipelines/build/triggers.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/build/triggers.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by mkajerski** [comment]
Using variables['Build.Reason'] as a condition for the publishing steps should do the trick, e.g. in(variables['Build.Reason'], 'IndividualCI', 'BatchedCI')) for CI and in(variables['Build.Reason'], 'PullRequest')) for PR triggered builds. 

See https://docs.microsoft.com/en-us/azure/devops/pipelines/process/conditions?view=azure-devops&tabs=yaml

**Comment by erinha** [comment]
Thanks, that worked!

**Comment by steved0x** [comment]
@mkajerski Thank you for supplying that information. @erinha I'm glad that worked for you. If you wanted to make an update to our documentation, you could submit a PR against this article [here](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/build/triggers.md), and maybe add it down in the QA section at the bottom? Or if you want to file a new issue on this topic, I can add it for you if you supply me a snippet of what you did?
