### ISSUE TITLE
Build Number Format information needed

### ISSUE THREAD

**Issue by ravensorb** [MicrosoftDocs/vsts-docs#5323]
I think there used to be some examples and details on using the Build Number Format -- can these be added back in?

Ex: $(Date:yyyyMMdd).$(rev:r)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0fa5a83c-70fd-6925-a8c8-256b21c21a2e
* Version Independent ID: 75f4a136-7245-7878-2953-6b68272fe4ec
* Content: [Build options - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/options?view=azure-devops#feedback)
* Content Source: [docs/pipelines/build/options.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/build/options.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by msebolt** [comment]
@ravensorb  Thank you for the feedback.

The issue has been noted in https://github.com/MicrosoftDocs/vsts-docs/issues/4211 and provides links to the previous samples.

Please refer there for further status update on the issue.
