### ISSUE TITLE
JetBrains Rider compatibility?

### ISSUE THREAD

**Issue by DylanFPS** [MicrosoftDocs/vsts-docs#533]
^

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b71f9c7b-a10e-4adc-22d0-58d4b40b35c8
* Version Independent ID: 90cda752-8667-2e9c-4ba9-5af1abbb63b8
* Content: [Get the IntelliJ IDEA VSTS plug-in](https://docs.microsoft.com/en-us/vsts/java/download-intellij-plug-in?view=vsts)
* Content Source: [docs/java/download-intellij-plug-in.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/java/download-intellij-plug-in.md)
* Service: **unspecified**
* GitHub Login: @erickson-doug
* Microsoft Alias: **douge**

**Comment by steved0x** [comment]
@DavidStaheli Do you know the answer?

**Comment by DavidStaheli** [comment]
Hi @steved0x.  Yes, the VSTS plugin for IntelliJ is compatible with Rider, but it ships "in the box", pre-enabled with Rider, so there's no need for users to install it there.

**Comment by DylanFPS** [comment]
You should specify this in the documentation ;)
