### ISSUE TITLE
PIT Backup retention

### ISSUE THREAD

**Issue by DavidDMicrosoft** [MicrosoftDocs/vsts-docs#5333]
I don't see details of how long the point in time backups are retained for - can you please clarify that? Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 52eb9f91-b952-afb6-6d17-d7092f46440d
* Version Independent ID: bb9113a5-8b8b-b20b-9c6f-09a57f53ba7c
* Content: [Azure DevOps - Data Protection](https://docs.microsoft.com/en-us/azure/devops/organizations/security/data-protection?view=azure-devops&viewFallbackFrom=azdevops#data-availability)
* Content Source: [docs/organizations/security/data-protection.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/security/data-protection.md)
* Product: **devops**
* Technology: **devops-whitepapers**
* GitHub Login: @mlearned
* Microsoft Alias: **mlearned**

**Comment by msebolt** [comment]
@DavidDMicrosoft Thank you for the question.

As per the article:

```
We have the capability of restoring your organization’s data to any point in time over the last 30 days.
```

Are you looking for something more specific?

**Comment by DavidDMicrosoft** [comment]
Thanks for clarifying, the 30 days was mentioned in the next section and I wasn’t sure if that was a 2nd backup track or explaining the PITR paragraph.

**Comment by msebolt** [comment]
@DavidDMicrosoft  You're welcome, I re-worded the second statement to avoid any confusion.

Changes pending review.

**Comment by DavidDMicrosoft** [comment]
Great, thanks!!

**Comment by msebolt** [comment]
Documentation has been updated.
