### ISSUE TITLE
incorrect word

### ISSUE THREAD

**Issue by tiagolima34** [MicrosoftDocs/vsts-docs#5334]
mistake in the word "organization" in the prerequisites chapter (currently "...a field from organizaiton..."

---
#### Detalhes do Documento

⚠ *Não edite esta secção. É necessário para a ligação de problemas docs.microsoft.com ➟ GitHub.*

* ID: a2b6067a-50a8-dc02-fc43-8f55527b507c
* Version Independent ID: 3287e2ac-ef6d-3f52-47f4-1b337cfc077f
* Content: [Customize backlogs and boards - Azure DevOps Services](https://docs.microsoft.com/pt-pt/azure/devops/organizations/settings/work/customize-process-backlogs-boards?view=azure-devops#feedback)
* Content Source: [docs/organizations/settings/work/customize-process-backlogs-boards.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/settings/work/customize-process-backlogs-boards.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by msebolt** [comment]
@tiagolima34  Thank you for the feedback.

The documentation has been updated and is pending review.
