### ISSUE TITLE
Special Characters in release variables

### ISSUE THREAD

**Issue by jfuller28495** [MicrosoftDocs/vsts-docs#5335]
Can we please have some concise documentation around what special characters are allowed in release variables for Azure DevOps releases? I cannot find one place where documentation exists around what characters are allowed and how to escape characters that cause issues so that the whole value can be passed in without data loss. Currently, the suggestion to use double quotes (i.e. "$(secretVarName)" versus $(secretVarName)) has not worked for me, the release still fails to use the whole value.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 82305566-bf0a-20ca-46b0-4a011ea65e0b
* Version Independent ID: 59b2347e-dc58-ee34-0000-c2c8eb309901
* Content: [Restrictions and conventions for naming - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/settings/naming-restrictions?view=azure-devops&viewFallbackFrom=vsts#feedback)
* Content Source: [docs/organizations/settings/naming-restrictions.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/settings/naming-restrictions.md)
* Product: **devops**
* Technology: **devops-settings**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by shashban** [comment]
@jfuller28495 Release variables are essentially strings used your scripts. Definition and handling of special characters depends on the scripting language and the task you are using.
