### ISSUE TITLE
How can we use a custom icon for the task icon?

### ISSUE THREAD

**Issue by nadcraker** [MicrosoftDocs/vsts-docs#534]
How can we use a custom icon for the task icon? I don't mean the icon for the extension. That part is working fine. I mean the icon for the build task that shows up in the build definition.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 44581f4a-93df-7507-3844-eadedf9a6cc4
* Version Independent ID: 33c7bcf0-1512-975f-5ef8-9f2a192a84ad
* Content: [Add a Build or Release Task](https://docs.microsoft.com/en-us/vsts/extend/develop/add-build-task?view=vsts)
* Content Source: [docs/extend/develop/add-build-task.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/extend/develop/add-build-task.md)
* Service: **unspecified**
* GitHub Login: @erickson-doug
* Microsoft Alias: **elbatk**

**Comment by elbatk** [comment]
Hey @nadcraker , check out the documentation here: https://docs.microsoft.com/en-us/vsts/extend/develop/build-task-schema?view=vsts along with the issue referenced to this one: https://github.com/MicrosoftDocs/vsts-docs/issues/535
