### ISSUE TITLE
Missing collection scope httprequest example

### ISSUE THREAD

**Issue by Nusserdt** [MicrosoftDocs/vsts-docs#5343]
can you also provide an example about a collection scoped document httprequest?

for user scoped it is clear:
GET _apis/ExtensionManagement/InstalledExtensions/{publisherName}/{extensionName}/Data/Scopes/User/Me/Collections/%24settings/Documents/myKey

but what is it for the collection scoped?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8490096d-54dd-697b-62a3-9c930d0733d1
* Version Independent ID: 04f42aed-a8c2-f124-1c32-37daf54e8400
* Content: [Data and Setting Storage](https://docs.microsoft.com/en-us/azure/devops/extend/develop/data-storage?view=azure-devops#feedback)
* Content Source: [docs/extend/develop/data-storage.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/extend/develop/data-storage.md)
* Product: **devops**
* Technology: **devops-ecosystem**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by cwelde** [comment]
So...any update on this?

**Comment by chcomley** [comment]
Hi @cwelde, I've just followed up with the engineer and will get back to you when I receive their response. Thanks very much.

**Comment by chcomley** [comment]
@cwelde and @Nusserdt, this just in: 
GET _apis/ExtensionManagement/InstalledExtensions/{publisherName}/{extensionName}/Data/Scopes/Default/Current/Collections/%24settings/Documents/myKey

Please let me know if you have any further questions. Thank you!
