### ISSUE TITLE
Plan your org structure - What is a project : count is wrong?

### ISSUE THREAD

**Issue by Styxxy** [MicrosoftDocs/vsts-docs#5344]
At the page "Plan your org structure", part "What is a project" (https://docs.microsoft.com/en-us/azure/devops/user-guide/plan-your-azure-devops-org-structure?view=azure-devops#what-is-a-project) it mentions that the organisation has 3 projects, though the image seems to contain four projects, which seems to be very confusing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 01770b43-fd5b-efbc-36f5-af91a3c8cf5a
* Version Independent ID: 7c046a91-37f9-32e3-dc3e-dfa922c456be
* Content: [Plan your organizational structure - Azure DevOps - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/user-guide/plan-your-azure-devops-org-structure?view=azure-devops#what-is-a-project)
* Content Source: [docs/user-guide/plan-your-azure-devops-org-structure.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/user-guide/plan-your-azure-devops-org-structure.md)
* Product: **devops**
* Technology: **devops-new-user**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @styxxy, Thanks very much for letting us know! I've just completed a PR rectifying this.
