### ISSUE TITLE
Site is loosing its version context

### ISSUE THREAD

**Issue by huntantr** [MicrosoftDocs/vsts-docs#5347]
I am currently using TFS2017 and TFS2018, and recently when trying to look for content for those versions, either it no longer exists or just redirects to ADOs and YAML. 
Please correct this as there are many companies still using the other versions and we need accurate documentation.

**Comment by WilliamAntonRohm** [comment]
@huntantr  Thanks for your feedback; we appreciate it. To make sure we have all the information needed to triage your issue, please let us know which areas or topics you’re referencing.

**Comment by KathrynEE** [comment]
@huntantr - I'm closing this issue for now. Without having specific URLs to review, we really can't act on this feedback. Please feel free to reopen if you can provide those URLs.
