### ISSUE TITLE
Step templates are coming soon, but not available in deployment jobs yet.

### ISSUE THREAD

**Issue by williamayerst** [MicrosoftDocs/vsts-docs#5348]
Step templates are coming soon, but not available in deployment jobs yet.

_Originally posted by @vtbassmatt in https://github.com/MicrosoftDocs/vsts-docs/issues/4358#issuecomment-496525996_

Is there any ETA on when step templates for deployment jobs will be ready?

**Comment by RoopeshNair** [comment]
Step templates are supported in deployment job. Let me know if you are having issues
