### ISSUE TITLE
Shouldn't taskIcon.png be icon.png?

### ISSUE THREAD

**Issue by nadcraker** [MicrosoftDocs/vsts-docs#535]
My custom icon didn't show up in the build task until I renamed it to icon.png in the task's folder, and made it 32x32 pixels.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 83f7acc5-1222-7216-571b-913fa63298e4
* Version Independent ID: 15b2e074-4a8d-9ac8-8aa8-56a0c11be534
* Content: [Custom build/release task reference](https://docs.microsoft.com/en-us/vsts/extend/develop/build-task-schema?view=vsts)
* Content Source: [docs/extend/develop/build-task-schema.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/extend/develop/build-task-schema.md)
* Service: **unspecified**
* GitHub Login: @erickson-doug
* Microsoft Alias: **elbatk**

**Comment by niofire** [comment]
Confused me as well, works when renaming the taskIcon.png to icon.png :)

**Comment by elbatk** [comment]
Finally getting around to fixing this, thanks for the heads up @nadcraker and @niofire !
