### ISSUE TITLE
supported languages link is now bad

### ISSUE THREAD

**Issue by jarek91** [MicrosoftDocs/vsts-docs#5350]
The link in the line "Set a language identifier for the code block to enable syntax highlighting for any of the supported languages." under `Code highlighting` goes to the latest version of the readthedocs site for highlightjs. In the latest version, the list of languages has been removed from the documentation. Currently the list still exists in stable but this will eventually change as well. The list of supported language specifications is really needed so if highlightjs is not going to list them, we need to find a new list or make one hosted here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fa622358-f5bb-1f5c-177a-081a37b6acef
* Version Independent ID: 72f7fd16-a822-66c8-3a34-8905645ce5f2
* Content: [Markdown syntax for files, widgets, and wikis in Azure DevOps - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/project/wiki/markdown-guidance?view=azure-devops#feedback)
* Content Source: [docs/project/wiki/markdown-guidance.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/project/wiki/markdown-guidance.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by Bafff** [comment]
Is that correct link maybe? https://github.com/highlightjs/highlight.js/tree/master/src/languages

Or that? https://highlightjs.org/download/

**Comment by jarek91** [comment]
Both of those links contain the information but it is cumbersome to get. What the old documentation ([stable](https://highlightjs.readthedocs.io/en/stable/css-classes-reference.html#language-names-and-aliases)) shows is a table of the language and what aliases you can use to set your code fence to that language. Your first link requires you to either use a particular filename (without extension) or to open the file and see what aliases are acceptable for that language. The latter gives you a cleaner list but none of the aliases. The ideal solution is to have a table like the stable version of the highlight.js docs have:
![image](https://user-images.githubusercontent.com/2422098/64119232-edb20e80-cd5e-11e9-91ba-48943f17dadf.png)

**Comment by chcomley** [comment]
Hi @jarek91, I'll look into this and be in touch. Thanks for reaching out!

**Comment by Bafff** [comment]
@chcomley what has changed?

**Comment by chcomley** [comment]
@Bafff, I added the following **bolded text** to the article, showing which versions the link supports: "Set a language identifier for the code block to enable syntax highlighting for any of the [supported languages](http://highlightjs.readthedocs.io/en/latest/css-classes-reference.html#language-names-and-aliases), **version v9.10.0 or later versions**." Thanks!

**Comment by Bafff** [comment]
@chcomley maybe I don't understand something but I think we need to have a link to the page with exact names of languages that wiki supports. Or please point me how can I find it from your link from docs. Sorry if I'm missing smth obvious

**Comment by chcomley** [comment]
@adramasu, can you please help us here...thanks

**Comment by adramasu** [comment]
We are consuming highlightjs version 9.10.0. The [link ](https://github.com/highlightjs/highlight.js/tree/9.10.0/src/languages)has the list of languages for the specified version. We will update the documentation to point to this link. cc :@chcomley

**Comment by Bafff** [comment]
That's what we wanted I think
