### ISSUE TITLE
Teams Rooms Deprecated

### ISSUE THREAD

**Issue by spottedmahn** [MicrosoftDocs/vsts-docs#536]
>Create and manage team rooms

Should there be a note that Team Rooms are deprecated?  [Reference](https://docs.microsoft.com/en-us/vsts/collaborate/collaborate-in-a-team-room?view=tfs-2017&viewFallbackFrom=vsts)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 16350d80-8e4d-9416-8deb-dac44a65a9b7
* Version Independent ID: 1ce522f1-c50c-909f-6044-2b03d4bbb64c
* Content: [Team administrator permissions](https://docs.microsoft.com/en-us/vsts/work/scale/team-administrator-permissions?view=vsts)
* Content Source: [docs/work/scale/team-administrator-permissions.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/work/scale/team-administrator-permissions.md)
* Service: **unspecified**
* GitHub Login: @erickson-doug
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@spottedmahn - Thank you for your comment. I've updated the topic and changes will be live later today.
