### ISSUE TITLE
Can I add my extension under Organization Level, Settings Menu?

### ISSUE THREAD

**Issue by PramodMn007** [MicrosoftDocs/vsts-docs#5361]
I am working on a requirement , where I need to add my extension in Organization level settings menu, Is there any way , I can achieve this?

Edit : I tried to use "ms.vss-admin-web.collection-overview-toolbar-menu" under targets and "ms.vss-web.action" under type in vss-extension.json file, No luck...

**Comment by chcomley** [comment]
Hi @PramodMn007, I think what you want to do is add a hub contribution that targets this: ms.vss-web.collection-admin-hub-group

Please see more information [here](https://docs.microsoft.com/en-us/azure/devops/extend/reference/targets/overview?view=azure-devops). Do let us know whether you have further questions please! Thanks!

**Comment by PramodMn007** [comment]
It worked... Thanks a lot...
