### ISSUE TITLE
Substitutions for "keyed" entries?

### ISSUE THREAD

**Issue by giwleb** [MicrosoftDocs/vsts-docs#5367]
I'm wondering if the following substitutions are possible given this JSON:

`{ "SyncMethods": [ { "SourceId": 1, "Folders": [ "C:\\temp\\x" ] }, { "SourceId": 2, "Folders": [ "C:\\temp\\y" ] } ] }`

If I wanted to substitute different Folders.0 for each SourceId, what sort of reference would i use?

Something like:

`SyncMethods.SourceId=1.Folders.0`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 315ff823-9992-9f9b-62a1-42ce622ed41c
* Version Independent ID: 72ec3ffc-1dc9-b2dc-e3d4-4f14deae3720
* Content: [File transforms and variable substitution - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/transforms-variable-substitution?view=azure-devops)
* Content Source: [docs/pipelines/tasks/transforms-variable-substitution.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/transforms-variable-substitution.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by giwleb** [comment]
Clarifying my example solution to better match the given JSON:

`SyncMethods.1.SourceId=1.Folders.1`

**Comment by SumiranAgg** [comment]
You could use something as under:
SyncMethods.0.Folders.0
SyncMethods.1.Folders.0

This should work for you. Please fell free to re-open issue in case of further questions.
