### ISSUE TITLE
Images / text not matching current Azure DevOps (online) services

### ISSUE THREAD

**Issue by Styxxy** [MicrosoftDocs/vsts-docs#5368]
1) The "project administrators" can (also) be viewed on the "Overview" page. The screenshot is slightly outdated.

2) The view the "Organization owner", you have to go to "Organization settings" as indicated in the screenshots and not "Admin settings" as indicated in the text. The second screenshot of the "Overview" page is outdated though.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 20dce3f1-1133-3084-c5f4-7a5d6d0d6cf8
* Version Independent ID: 31579324-f0e5-607a-caa1-ec31b444af79
* Content: [Find an admin or organization owner - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/security/lookup-organization-owner-admin?view=azure-devops#show-members-of-the-project-collection-administrators-group)
* Content Source: [docs/organizations/security/lookup-organization-owner-admin.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/security/lookup-organization-owner-admin.md)
* Product: **devops**
* Technology: **devops-security**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@Styxxy - Thank you for the feedback. I will update the topic within the next few days to reflect the current UI.
