### ISSUE TITLE
Typos in sample predefined variable values.

### ISSUE THREAD

**Issue by JunielKatarn** [MicrosoftDocs/vsts-docs#5373]
See https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml .

Sample value for predefined variables `Build.SourcesDirectory` and `Build.Repository.LocalPath`: `c:\agent_work\1\s` may be missing a slash (directory separator).

Likely, the intended value is `c:\agent\_work\1\s`.

**Comment by steved0x** [comment]
@JunielKatarn `c:\agent_work` is the correct folder, is it different for you and causing trouble in your pipelines? I am closing this issue, but if your issue isn't resolved, please reactivate and and provide more details, and we can look into it further. Thank you.
