### ISSUE TITLE
ADO project not in parent directory

### ISSUE THREAD

**Issue by mkushakov** [MicrosoftDocs/vsts-docs#5378]
You can't subscribe to ADO project if it is in another directory, even if you have full admin rights. 
We have a setup when we have 2 AAD directories and ADO project is in directory where my account is guest. When you try to subscribe it shows error:

`Configuration failed. Please make sure that the organization 'your_repo_name' exists and that you have sufficient permissions.`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 99a6f5aa-7e92-a028-d13e-e1e4b7fede86
* Version Independent ID: be7e5d7c-0033-6b72-4bd1-809f7d1894aa
* Content: [Azure Pipelines with Slack - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/integrations/slack?view=azure-devops#feedback)
* Content Source: [docs/pipelines/integrations/slack.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/integrations/slack.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @atinb
* Microsoft Alias: **atinb**

**Comment by mkushakov** [comment]
Seems that [posted](https://docs.microsoft.com/en-us/azure/devops/pipelines/integrations/slack?view=azure-devops#troubleshooting) workaround doesn't work in Safari, but in Chrome.

**Comment by atinb** [comment]
@msebolt We worked with @mkushakov to resolve the problem. Please close the issue. I do not have access to do so. Thanks

**Comment by mkushakov** [comment]
@atinb thanks for helping to debug this issue. If you don't want to keep it until Safari compatibility will be fixed I can close it.

**Comment by atinb** [comment]
@mkushakov We have opened an internal bug to track this issue. Thanks for reporting!
