### ISSUE TITLE
Linked deployment topics are not relevant.

### ISSUE THREAD

**Issue by daniel-dorroh** [MicrosoftDocs/vsts-docs#539]
This topic is about building your .NET desktop app. The next steps link to deployment topics that do not work for desktop apps -- they are all geared toward web apps.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 92f80d77-da2a-3c8d-efcf-3095bf293f69
* Version Independent ID: 36dcf393-e28a-2bc4-61e6-5c93cdacb625
* Content: [Build your .NET desktop app for Windows](https://docs.microsoft.com/en-us/vsts/build-release/apps/windows/dot-net?view=vsts&tabs=vsts)
* Content Source: [docs/build-release/apps/windows/dot-net.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/build-release/apps/windows/dot-net.md)
* Service: **unspecified**
* GitHub Login: @erickson-doug
* Microsoft Alias: **alewis**

**Comment by andyjlewis** [comment]
Thanks for finding and reporting this issue. I've added it to our backlog.

**Comment by shazam19** [comment]
any update on this topic?

**Comment by Calumfletcher** [comment]
+1

**Comment by leus** [comment]
Hello - this documentation hasn't changed is still as useless as it was when this was first reported. Any ideas on how to deploy a Windows Desktop Application (as an artifact for downloading)?

**Comment by leus** [comment]
Please let us know where in your backlog is this issue, or reopen this issue. There is still no way to deploy a setup file, for instance, from a pipeline to a web site, for example, without having to manually codify each step.
