### ISSUE TITLE
Missing description of system variables: System.StageName and System.StageDisplayName

### ISSUE THREAD

**Issue by NenoLoje** [MicrosoftDocs/vsts-docs#5393]
These system variables seem to exist, but are not yet documented. Please add them to the page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ffebdc8-521c-44b5-cde4-4abdc1bd6f18
* Version Independent ID: dc0effda-6d93-62aa-64c5-4e6f283b0826
* Content: [Predefined variables - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml#feedback)
* Content Source: [docs/pipelines/build/variables.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/build/variables.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by mikeblakeuk** [comment]
Should Pipeline.StartTime also be included?

**Comment by vtbassmatt** [comment]
> Should Pipeline.StartTime also be included?

I don't know when that variable got added nor whether the team intends to support it. I'll follow up and get the team to doc it (or remove it!).

The rest of these are done.
