### ISSUE TITLE
Source controlled binary file size limitations and totaly Repository size limitations

### ISSUE THREAD

**Issue by OzBob** [MicrosoftDocs/vsts-docs#5397]
I have read https://developercommunity.visualstudio.com posts about Task attachment, wiki and wiki gitrepo size and throughput issues.

Is there documentation on the absence or presence of any limitations on individual binary file sizes or the total size of a repository?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5c2c2355-60a5-d53f-2c72-8f032c1b8cf2
* Version Independent ID: 711bf22d-99c9-51b2-382c-e095bdb2c37f
* Content: [Resource limits & constraints - Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/integrate/concepts/rate-limits?view=azure-devops)
* Content Source: [docs/integrate/concepts/rate-limits.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/integrate/concepts/rate-limits.md)
* Product: **devops**
* Technology: **devops-ecosystem**
* GitHub Login: @chcomley
* Microsoft Alias: **kaelli**

**Comment by OzBob** [comment]
thank you. suggested git max size is Less than 10GB, single upload of a 'push' is 5GB.

**Comment by msebolt** [comment]
You're welcome, thank you for informing the post.
