### ISSUE TITLE
Step #6 is very vague - How are the list of "Azure DevOps Groups" populated and where / how do you add another group to that list?

### ISSUE THREAD

**Issue by securityvoid** [MicrosoftDocs/vsts-docs#5402]
"Complete the dialog box for the group for which you want to create a rule. Include an access level for the group and any optional project access or extensions for the group. Select Add."

How are the list of "Azure DevOps Groups" populated and where / how do you add another group to that list?

The names populated in Azure DevOps Groups do not match exactly with the names of the security groups in the projects. They're actually similar but different. It also appears that adding an additional security group does not get it in the Azure DevOps Groups drop-down; so where does that drop-down originate from and how does this work?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba38644a-fe6c-e644-2f35-2cf6fa092650
* Version Independent ID: 7d18b423-923f-d9c4-e451-ab7f8ff27bb1
* Content: [Add group rule to assign access levels, extensions - Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/assign-access-levels-and-extensions-by-group-membership?view=azure-devops)
* Content Source: [docs/organizations/accounts/assign-access-levels-and-extensions-by-group-membership.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/accounts/assign-access-levels-and-extensions-by-group-membership.md)
* Product: **devops**
* Technology: **devops-accounts**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @securityvoid, Thanks for reaching out. I'll look into this and be in touch. Thanks!

**Comment by chcomley** [comment]
Hi @securityvoid, The groups are just the standard short-list of groups that exist for all projects: Contributors, Readers, Administrators. We don't give the full list of groups for each project. If you want to add folks from one group to another group, you can add the whole group to the parent group. As users get added to the child group they automatically get added to the parent group. A Group Rule is not required for this. Please let me know if you have further questions. Thanks!
