### ISSUE TITLE
Using @Release Feed in builds

### ISSUE THREAD

**Issue by prodigz** [MicrosoftDocs/vsts-docs#5406]
Once I have promoted a package to a Release feed how would I target the @Release view in my NuGet Restore task in a build.
I have tried using name@Release but that does not seem to work.

**Comment by msebolt** [comment]
Under the feed settings, can you find a specific URL for the **@Release** view?

If so, you can use this in the nuget.config file, see [Specify sources in nuget.config](https://docs.microsoft.com/en-us/azure/devops/pipelines/packages/nuget-restore?view=azure-devops#specifying-sources-in-nugetconfig).  Then, specify the feed in the [Nuget restore task](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/package/nuget?view=azure-devops#restore-nuget-packages) settings.

Please comment below if there are issues.
