### ISSUE TITLE
NuGet Restore from @Release view in AzureDevOps Artifacts

### ISSUE THREAD

**Issue by prodigz** [MicrosoftDocs/vsts-docs#5407]
I am trying to target the @Release view from my Azure Artifacts/TFS feed for a restore option but I dont see a way to do that with this task.  Is it possible to only target packages that are on the @Prerelease or @Release views?

**Comment by msebolt** [comment]
@prodigz  Thank you for the question.

How is this different from https://github.com/MicrosoftDocs/vsts-docs/issues/5406?

**Comment by msebolt** [comment]
Please refer to the linked issue above.
