### ISSUE TITLE
Please include instructions on branch deletion events

### ISSUE THREAD

**Issue by andrebriggs** [MicrosoftDocs/vsts-docs#5408]
Please include instructions on how to be notified of branch deletion events. For instance In GitHub I can be notified of a branch deletion (see [here](https://developer.github.com/v3/activity/events/types/#deleteevent)). I haven't seen an equivalent event in ADO service hook documentation.

**Comment by msebolt** [comment]
@andrebriggs Thank you for the question.

For the command:
```
git push --delete <remote_name> <branch_name>
```
...you should be notified with a [code push event](https://docs.microsoft.com/en-us/azure/devops/notifications/oob-supported-event-types?view=azure-devops).

If you'd like more specific events included, you should use **Suggest a feature** on the [Azure DevOps forums](https://developercommunity.visualstudio.com/topics/Azure+DevOps.html).
