### ISSUE TITLE
Doc bug: Missing argument description for: packDirectory

### ISSUE THREAD

**Issue by NenoLoje** [MicrosoftDocs/vsts-docs#5411]
In the YAML snippet, there's an argument "packDirectory" listed, but it does not show up in the arguments list and thus is missing a description.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d1d9884-19f7-592b-f47c-8cf100639ff0
* Version Independent ID: 555c3826-60d9-2589-54af-850efbfbb13a
* Content: [.NET Core CLI task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/dotnet-core-cli?view=azure-devops#feedback)
* Content Source: [docs/pipelines/tasks/build/dotnet-core-cli.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/build/dotnet-core-cli.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @pulkitaggarwl
* Microsoft Alias: **puagarw**

**Comment by iamsrivatsa** [comment]
The **packDirectory** is the alias used for **outputDir** and same is already documented in the Arguments table along with the description.

**Comment by NenoLoje** [comment]
@iamsrivatsa Thanks for helping out. Now, we both know that, but the page itself has no indication of that relationship. How can we fix that docs page to make it clear for others, too?

**Comment by iamsrivatsa** [comment]
@NenoLoje  I'm still thinking of the format to include those alias as part of the document. Will be updated soon.
