### ISSUE TITLE
Username not needed in git clone when using PAT

### ISSUE THREAD

**Issue by richardjortega** [MicrosoftDocs/vsts-docs#5412]
Under the section entitled **Use your personal access token**, it mentions the use of a username in a `git clone` request. However, the PAT can be used to auth without a username provided.

The following two commands work (without a username)

```bash
git clone https://<yourPAT>@<yourOrgName>.visualstudio.com/<yourProjectName>/_git/<yourRepoName>
```

```bash
git clone https://<yourPAT>@dev.azure.com/<yourOrgName>/<yourProjectName>/_git/<yourRepoName>
```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2bfea574-db69-a5fd-37fe-64ecfdac502a
* Version Independent ID: 4037d475-f194-2ac9-ffd6-70530fc3140a
* Content: [Authenticate with personal access tokens - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/use-personal-access-tokens-to-authenticate?view=azure-devops#frequently-asked-questions)
* Content Source: [docs/organizations/accounts/use-personal-access-tokens-to-authenticate.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/accounts/use-personal-access-tokens-to-authenticate.md)
* Product: **devops**
* Technology: **devops-accounts**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @richardjortega, Thanks for reaching out. I'll look into this and be in touch.

**Comment by chcomley** [comment]
@richardjortega, I've updated the article, which should be live this afternoon. Thanks so much for your input!
