### ISSUE TITLE
Line comments via the commits tab

### ISSUE THREAD

**Issue by lozzadude** [MicrosoftDocs/vsts-docs#5417]
Commits help break up code changes into logical groups & can make it easier for a reviewer to review code, especially in a big pull request. However if you make line comments via the commits tab, they don't show up in the overview & don't count if you force all comments to be resolved before a PR can be completed. You have to make them via the files tab. This is very inconsistent. Github lets you add line comments when looking at individual commits & they actually count. It there any logic reason for this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 028e7b61-62e4-a10e-e420-3535f7843f0e
* Version Independent ID: 1a6fdbe7-5ba4-a7f8-1b2e-271289a7b9fd
* Content: [Review and merge code with pull requests - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/pull-requests?view=azure-devops#feedback)
* Content Source: [docs/repos/git/pull-requests.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/repos/git/pull-requests.md)
* Product: **devops**
* Technology: **devops-code-git**
* GitHub Login: @apawast
* Microsoft Alias: **sdanie**

**Comment by WilliamAntonRohm** [comment]
It looks like you've encountered an issue with the product itself, rather than an issue with the documentation. To make sure it gets in front of the right people, please [submit your bug]( https://developercommunity.visualstudio.com/content/problem/post.html?space=21) here.
