### ISSUE TITLE
Can I have Azure DevOps automatically make me follow work items I created or add comments on? (like in GitHub or Jira)

### ISSUE THREAD

**Issue by slawomir-brzezinski-at-clarksons** [MicrosoftDocs/vsts-docs#5419]
This is a standard and an essential feature of most issue tracking software (GitHub, Jira) but I can't find it in Azure DevOps.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 50fb5639-2338-9141-1129-682e46676f7f
* Version Independent ID: 5002bb9e-5ec3-d773-2843-8b20468d6c69
* Content: [Track updates by getting notified of changes made to a user story, bug, or other work item or pull request - Azure Boards & Azure Repos](https://docs.microsoft.com/en-us/azure/devops/boards/work-items/follow-work-items?view=azure-devops)
* Content Source: [docs/boards/work-items/follow-work-items.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/boards/work-items/follow-work-items.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by zlamma** [comment]
I guess not, as I can see there's [this feature request](https://developercommunity.visualstudio.com/content/idea/479189/automatically-follow-work-items-i-interact-with.html).

I must say I feel the feature is so essential that it deserves to be mentioned in the Q&A of this document.

**Comment by slawomir-brzezinski-at-clarksons** [comment]
I guess not, as I can see there's [this feature request](https://developercommunity.visualstudio.com/content/idea/479189/automatically-follow-work-items-i-interact-with.html).

I must say I feel the feature is so essential that it deserves to be mentioned in the Q&A of this document.

**Comment by KathrynEE** [comment]
@slawomir-brzezinski-at-clarksons  - Thank you for the inquiry. You can create a Notification subscription to get notified of changes made to work items you created. Documented here: [Manage your notifications](https://docs.microsoft.com/en-us/azure/devops/notifications/howto-manage-personal-notifications?view=azure-devops).  As for getting notification of work items where you have added a comment - there is no specific feature that covers this. The only way is to choose to Follow the work item once you add a comment.  I will update the topic to clarify.

**Comment by slawomir-brzezinski-at-clarksons** [comment]
Thank you @KathrynEE . Is there a way to have all [organization/team] members inherit such a subscription? It would need a dynamic recipients, i.e. only whoever is the creator should receive the email, not the whole team/organization.

**Comment by slawomir-brzezinski-at-clarksons** [comment]
Thank you @KathrynEE .
The 'Notifications subscription' seems like an inferior solution. It can probably be considered a very crude-grained workaround. That's because if you have a few tickets that you'd like not follow anymore, you need to put up with the noise or disable the whole rule. The 'Follow' feature, and setting of it automatically on certain interactions is what people really need.

**Comment by msedi** [comment]
I agree. In github each item is automatically followed. I'm creating many user stories a day but always forget to click follow.

**Comment by topcats** [comment]
DItto, most other Bug track platforms auto follow an item that you comment on

**Comment by papadi** [comment]
A good alternative or an enhancement would be to be able to subscribe to all comments or changes of a work item depending on its status. So roles are interested in a work item after it's approved, or after it's committed etc.

**Comment by WilliamAntonRohm** [comment]
@All, thank you for your interest in this issue.  Please consider upvoting this [feature request](https://developercommunity.visualstudio.com/t/automatically-follow-work-items-i-interact-with/479189) (mentioned above).
