### ISSUE TITLE
JSON Substitution not working for nested schemas

### ISSUE THREAD

**Issue by vigneshmsft** [MicrosoftDocs/vsts-docs#542]
In the above JSON file Data is the rootnode but none of the variables defined in the example follow the Data.{child}.{nextDescendant} pattern,
is it just {child}.{nextDescendant} is that correct?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 315ff823-9992-9f9b-62a1-42ce622ed41c
* Version Independent ID: 72ec3ffc-1dc9-b2dc-e3d4-4f14deae3720
* Content: [File transforms and variable substitution](https://docs.microsoft.com/en-us/vsts/build-release/tasks/transforms-variable-substitution?view=vsts#jsonvarsubs)
* Content Source: [docs/build-release/tasks/transforms-variable-substitution.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/build-release/tasks/transforms-variable-substitution.md)
* Service: **unspecified**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by vigneshmsft** [comment]
I have the below JSON schema in my appsettings.json
![image](https://user-images.githubusercontent.com/10269434/38724140-2f4ef5cc-3efb-11e8-89f2-43e1670d5ca9.png)

and the below variable in my release variable set in VSTS

![image](https://user-images.githubusercontent.com/10269434/38724229-7a32d612-3efb-11e8-8f1d-a1b921cd6fbc.png)

If you are unable to view the image, I have values set for
Api.Income.url & Api.PersonalInformation.url in release scope.

But once the deployment is complete, I can only see the variable getting substituted for
Api.PersonalInformation.url and not the next element.

Is this is a bug or am I doing something wrong?

Also I would like to access the variables in the sameway as I do it from code,
for example in code I would access these variables using the path
Api:Income:url, Api:PersonalInformation.url and this is also case insensitive
and this also allows me to have a dot(.) in the JSON token
for example I could have the below structure

![image](https://user-images.githubusercontent.com/10269434/38724624-b6da2f56-3efc-11e8-8ef2-e1873d986956.png)

But this won't work with VSTS variable substitution as VSTS looks at dot (.) as a element separator.

Thanks

**Comment by alexhomer1** [comment]
Thank you for your feedback. I have passed this on to the product team and will let you know their response.

**Comment by alexhomer1** [comment]
I understand that the product team have replied to you and cannot reproduce the issue. They are investigating further now.

**Comment by Kunjahamed-P** [comment]
![tempsnip](https://user-images.githubusercontent.com/42990066/45298675-e333af00-b526-11e8-9dbd-cc91ae2edec7.jpg)

can i change  AppSettings_Dev to AppSettings
