### ISSUE TITLE
Is there is a bug with the preview page ?

### ISSUE THREAD

**Issue by SamirFarhat** [MicrosoftDocs/vsts-docs#5421]
I'm noticing that at the Project level, we only have the Organization Level groups, and we cannot find the Project level groups. Is this expected ?

![image](https://user-images.githubusercontent.com/14938496/63950741-daf8ba80-ca7c-11e9-8a45-f02b5f6fdc5a.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ae5c3b5-9751-743f-6e68-d20a2fac6243
* Version Independent ID: 66756817-161b-cadf-f13c-10a216fae08a
* Content: [Set project or collection-level permissions - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/security/set-project-collection-level-permissions?view=azure-devops&tabs=preview-page)
* Content Source: [docs/organizations/security/set-project-collection-level-permissions.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/security/set-project-collection-level-permissions.md)
* Product: **devops**
* Technology: **devops-security**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by WilliamAntonRohm** [comment]
It looks like you've encountered an issue with the product itself, rather than an issue with the documentation. To make sure it gets in front of the right people, please [submit your bug]( https://developercommunity.visualstudio.com/content/problem/post.html?space=21) here.
