### ISSUE TITLE
Can only be run once per pipeline

### ISSUE THREAD

**Issue by MisinformedDNA** [MicrosoftDocs/vsts-docs#5422]
It should be said that this task can only be run once per pipeline. Or rather, the last run of this task will overwrite previous runs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6ac4ff4-9839-6a6d-8d20-a25084d221ef
* Version Independent ID: bd09f139-8e69-8ea1-6671-b7bba8e17c23
* Content: [Publish Code Coverage Results task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/test/publish-code-coverage-results?view=azure-devops)
* Content Source: [docs/pipelines/tasks/test/publish-code-coverage-results.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/test/publish-code-coverage-results.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @PBoraMSFT
* Microsoft Alias: **pbora**

**Comment by PBoraMSFT** [comment]
@MisinformedDNA - at present, yes, that is the case. However, we are working on improving our code coverage story - that will not only remove this limitation, but you will also get first-class coverage reporting experiences.

Will update the doc to call out the current limitations.

**Comment by PBoraMSFT** [comment]
@MisinformedDNA - [Task Docs](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/test/publish-code-coverage-results?view=azure-devops#q--a) have been updated.
