### ISSUE TITLE
##vso[build.updatebuildnumber]$yourNewBuildNumberHere - no mention of this very nice convenience!

### ISSUE THREAD

**Issue by t-l-k** [MicrosoftDocs/vsts-docs#5425]
If executing from a Powershell script:

```
write-host "##vso[build.updatebuildnumber]$yourNewBuildNumberHere"
```

Then the build number gets updated to the value of `$yourNewBuildNumberHere`! Very handy if you want to take a minimalist approach towards build numbering and use a script (e.g. Powershell) to trim down the the out-of-the-box offerings from the limited attribute set advised upon here. 

Presumably this works in all pipeline areas, I haven't yet tried, but a tip of the hat to this feature will surely help others.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a57f8545-bb15-3a71-1876-3a9ec1a59b93
* Version Independent ID: 28c87c8d-c28d-7493-0c7c-8c38b04fbcd7
* Content: [Run number - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/run-number?view=azure-devops&tabs=yaml#feedback)
* Content Source: [docs/pipelines/process/run-number.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/run-number.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
It's added: https://docs.microsoft.com/en-us/azure/devops/pipelines/scripts/logging-commands?view=azure-devops&tabs=bash#updatebuildnumber-override-the-automatically-generated-build-number
