### ISSUE TITLE
I'm looking for a bit more information on the WhenChanged flag.

### ISSUE THREAD

**Issue by peckhamm** [MicrosoftDocs/vsts-docs#5426]
Thank you for your feedback!

The issues in this repo are for documentation feedback.

If you are submitting your documentation feedback issue directly through GitHub, please provide the URL of the article so we can route the feedback to the correct author.

Please report Azure DevOps or TFS software bugs, feedback, or questions in the [Azure DevOps Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html).

**Comment by peckhamm** [comment]
I'm looking for a bit more information on the WHENCHANGED flag.    I am basically wondering if you can use something similar to WHEN's value="x".  

So if I change a switch from False to True I would like the date to fill in on another field.  BUT, when I change the switch back from True to False, I would like that date field to <EMPTY /> or clear itself.

**Comment by WilliamAntonRohm** [comment]
@peckhamm -- Mark, thanks for your feedback; we appreciate it. To make sure we have all the information needed to triage your issue, please let us know which topic you’re referencing, or provide more context around the general task.

**Comment by peckhamm** [comment]
For this example, we need to capture who did a code review in a ticket.  I've put a switch in (xml) and set it up, so when the switched is changed <WHENCHANGED> it auto fills in the Reviewer, the Date and a Status field.  Now really I only want to capture that information when the switch is flipped to True.  When it is changed to False I need it to <EMPTY /> those fields mentioned above.  

I hope that makes sense.  And I realize that in a lot of cases this information can be captured by other means, but for our auditing purposes, it looks like this will work best.

**Comment by WilliamAntonRohm** [comment]
@peckhamm -- Mark, thank you for clarifying.  Is there a particular article in the documentation that we should update?
