### ISSUE TITLE
Passing variable group name as template parameter causes resource authorization failures

### ISSUE THREAD

**Issue by lee0c** [MicrosoftDocs/vsts-docs#5427]
I am running a multi-stage pipeline that deploys an ARM template to multiple environments. Each stage runs a **job template** that takes a **variable group name as a parameter**, then uses the variables in that group to determine environment-specific details (subscription, resource group, prefix for resource names, etc). When a variable group contains as a variable the name of a resource that requires authorization such as a **service connection**, the pipeline fails to run due to a resource authorization error, saying that it cannot find and/or authorize service connection `$(azureServiceConnection)`.

Other notes:

- Other single- and multi-stage pipelines in this project that do not have templates do not appear to have this issue - so almost certainly a template issue.
- The service connection is authorized to be used by all pipelines.
- The variable group(s) used are authorized to be used by all pipelines.

In digging into this deeper, I have found: 

- If the service connection name is hard-coded into the template, the pipeline will run as expected (aka, it is not actually an authorization issue - the service connection exists and can be used by the pipeline)
- If the service connection name is passed as a parameter into the template, the pipeline will run as expected (aka, parameters are evaluated before resource authorization checks)
- If the variable name for the service connection is passed as a parameter, the pipeline fails in the same manner described above (aka, variables for the pipeline calling the template are not evaluated before resource authorization checks)
- Other variables in the variable group are evaluated correctly in the pipeline (aka, the pipeline can access the variable group)
- If the variable name for the service connection is used elsewhere in the pipeline (ex. a bash script echoing the name), the variable evaluates correctly (aka, the pipeline can correctly access the service connection variable)

I believe this is all the relevant details, but let me know if there's more information I can provide that would help, let me know.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6724abea-bbdc-bf66-ed5e-3214fa6c3e66
* Version Independent ID: 4f8dab21-3f0e-da32-cc0e-1d85c13c0065
* Content: [Job and step templates - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/templates?view=azure-devops#)
* Content Source: [docs/pipelines/process/templates.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/templates.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @vtbassmatt
* Microsoft Alias: **macoope**

**Comment by wimhollebrandse** [comment]
As per lee0c above, this is a real pain if you are referencing common variables in a YAML file and you have suffixed them with environment name in order to get hold of the correct resource names in your release template. This still fails as of October 14th 2019.

**Comment by vtbassmatt** [comment]
This has to do with what variables are available during template compilation. We're looking at opportunities to improve this, but don't have anything concrete on the backlog right now. CC @zachariahcox

If you want to have an official place to track this as a feature request, you can file it on [Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html) ("suggest a feature"). I'll leave this bug open for now, as I hope to get a topic up which explains how variables and templates interact.

**Comment by lee0c** [comment]
@vtbassmatt Did that topic on variables and templates get created? Why  was this closed if the issue persists?

**Comment by vtbassmatt** [comment]
[Templates](https://docs.microsoft.com/azure/devops/pipelines/process/templates) and [Runs](https://docs.microsoft.com/azure/devops/pipelines/process/runs) have been expanded to help with this.

**Comment by lee0c** [comment]
Just to make it easier to find:

>  It also answers another common issue: why can't I use variables to resolve service connection / environment names? Resources are authorized before a stage can start running, so stage- and job-level variables aren't available. Pipeline-level variables can be used, but only those explicitly included in the pipeline. Variable groups are themselves a resource subject to authorization, so their data is likewise not available when checking resource authorization.

From [this section](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/runs?view=azure-devops#process-the-pipeline) of the linked doc above.
