### ISSUE TITLE
Typo....

### ISSUE THREAD

**Issue by optiks** [MicrosoftDocs/vsts-docs#5428]
"Your are now ready"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a55e404e-010b-32e5-30e0-71a2663a4f89
* Version Independent ID: e011575a-691c-af48-2268-1959c9f3020b
* Content: [Building multiple branches - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/ci-build-git?view=azure-devops&tabs=yaml#feedback)
* Content Source: [docs/pipelines/build/ci-build-git.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/build/ci-build-git.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by msebolt** [comment]
@optiks  Thank you for the feedback.

The documentation has been updated and is pending review.
