### ISSUE TITLE
Remove "displayName" from under 'strategy/runOnce/deploy'

### ISSUE THREAD

**Issue by henry-padilla** [MicrosoftDocs/vsts-docs#5431]
Under "Deployment job" the entries listed are:
  environment: string  # target environment name and optionally a resource-name to record the deployment history; format: &lt;environment-name&gt;.&lt;resource-name&gt;
  strategy:
    runOnce:
      deploy:
      displayName: string                 # friendly name to display in the UI
        steps:

"displayName" is not supported under "strategy/runOnce/deploy".
It is (correctly) not mentioned on the dedicated "Deployment job" page (https://docs.microsoft.com/en-us/azure/devops/pipelines/process/deployment-jobs?view=azure-devops)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7458d5b2-1bb7-7d87-7ce6-2b0c430b0155
* Version Independent ID: edf5bbd3-a3f0-5426-e985-31290f8afd05
* Content: [YAML schema - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema#feedback)
* Content Source: [docs/pipelines/yaml-schema.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/yaml-schema.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @vtbassmatt
* Microsoft Alias: **macoope**

**Comment by msebolt** [comment]
@henry-padilla Thank you for the feedback.

The documentation has been updated and is pending review.
