### ISSUE TITLE
collapsible section

### ISSUE THREAD

**Issue by yzorg** [MicrosoftDocs/vsts-docs#5433]
The [blog post](https://devblogs.microsoft.com/devops/whats-new-in-azure-devops-sprint-152/) and [release notes](https://aka.ms/azuredevops/152) mention **collapsible section** via `&lt;summary&gt;` and `&lt;detail&gt;`, but that feature is not mentioned in the docs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 29f1e43f-a069-dd88-7fc7-9cc497fb94f0
* Version Independent ID: c261afa7-6eb7-b3f0-9f92-6d2f3c5ac336
* Content: [Markdown syntax for wikis in Azure DevOps - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/project/wiki/wiki-markdown-guidance?view=azure-devops#yaml-tags)
* Content Source: [docs/project/wiki/wiki-markdown-guidance.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/project/wiki/wiki-markdown-guidance.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Thanks for reaching out, @yzorg, we'll look into this and be in touch.

**Comment by adramasu** [comment]
Hi @yzorg, we have documented only markdown syntaxes in this document. There is no documentation explicitly for HTML syntaxes.
