### ISSUE TITLE
File attachment size

### ISSUE THREAD

**Issue by Bafff** [MicrosoftDocs/vsts-docs#5435]
I think that info about file sizes here: https://docs.microsoft.com/ru-ru/azure/devops/project/wiki/wiki-file-structure?view=azure-devops#file-naming-conventions is not relevant anymore as I can read here: https://docs.microsoft.com/en-us/azure/devops/release-notes/2019/sprint-156-update#fix-warning-in-large-test-attachments

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: 361efecd-d973-82ed-1dd8-ca01afe12f5d
* Version Independent ID: 629f3af2-8218-e53c-45c3-0e40c03f2273
* Content: [Wiki repository files, structure, and conventions in Azure DevOps - Azure DevOps](https://docs.microsoft.com/ru-ru/azure/devops/project/wiki/wiki-file-structure?view=azure-devops#file-naming-conventions)
* Content Source: [docs/project/wiki/wiki-file-structure.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/project/wiki/wiki-file-structure.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @Bafff, The new change is in Test, which isn't related to wiki file attachments. In Wiki, the limit is still what is mentioned in the documentation. Thank you!
