### ISSUE TITLE
The order file in this hierarchy is missing page entries. Please refer our documentation to fix it

### ISSUE THREAD

**Issue by Bafff** [MicrosoftDocs/vsts-docs#5436]
I am receiving this error message then I'm trying to move my standard project wiki page.

I cannot find any documentation about this issue. Is there any script I need to check?

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: 361efecd-d973-82ed-1dd8-ca01afe12f5d
* Version Independent ID: 629f3af2-8218-e53c-45c3-0e40c03f2273
* Content: [Wiki repository files, structure, and conventions in Azure DevOps - Azure DevOps](https://docs.microsoft.com/ru-ru/azure/devops/project/wiki/wiki-file-structure?view=azure-devops&viewFallbackFrom=vsts)
* Content Source: [docs/project/wiki/wiki-file-structure.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/project/wiki/wiki-file-structure.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @Bafff, Thanks for reaching out. I'm following up on this and will be in touch.

**Comment by chcomley** [comment]
Hi @bafff, This [link](https://docs.microsoft.com/en-us/azure/devops/project/wiki/wiki-file-structure?view=azure-devops#order-file) has details to help you ensure that the order file is formed correctly. Please navigate to the repo and ensure that the order file entries match the required hierarchies. Let us know if you have any further questions. Thanks!
