### ISSUE TITLE
Missing steps for configure

### ISSUE THREAD

**Issue by jclay** [MicrosoftDocs/vsts-docs#544]
The documentation is missing the steps after downloading the agent and before running .\run.cmd

I had to do the following:

- Extract download
- Move to tools\vsts-agent (personal preference)
- Enter project url
- Select `PAT` token type
- Paste token

It should also be noted that an elevated prompt is needed to run the agent as a service, otherwise the config has to be removed, and restarted from the beginning.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43799c5d-2f13-cc76-a1c0-a3f850e16d4e
* Version Independent ID: 97a5b73f-faf7-f9c0-9269-fc79984616d6
* Content: [Deploy an agent on Windows](https://docs.microsoft.com/en-us/vsts/build-release/actions/agents/v2-windows?view=vsts)
* Content Source: [docs/build-release/actions/agents/v2-windows.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/build-release/actions/agents/v2-windows.md)
* Service: **unspecified**
* GitHub Login: @erickson-doug
* Microsoft Alias: **alewis**

**Comment by mlearned** [comment]
@jclay thank you for the feedback, i'm looking into doc updates for this one and will update back here.

**Comment by rhubley** [comment]
+1 for elevated prompt, time to go make a new PAT because I've since cleared my clip board

**Comment by vtbassmatt** [comment]
Addressed in a pending doc change
