### ISSUE TITLE
Configuration styles don't look right or respect the dark theme

### ISSUE THREAD

**Issue by slushhpuppy** [MicrosoftDocs/vsts-docs#5444]
The widget styles look good, but the configuration styles don't match the out of the box Microsoft widgets. The spacing is different and everything about them just looks different. Building the sample linked above shows that prett clearly. Also, neiterh widget or configuration styles respect the dark theme. If I pick the dark theme and configure a customer widget, the config pael is white, it looks terrible. Can't the user's preferred styles just be inherited?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1db84ce4-2315-fe6d-96e4-b6cd301eeb60
* Version Independent ID: 4b7484e9-ab15-ef30-5e3d-552382f7c6a7
* Content: [Basic styles for widgets](https://docs.microsoft.com/en-us/azure/devops/extend/develop/styles-from-widget-sdk?view=azure-devops#feedback)
* Content Source: [docs/extend/develop/styles-from-widget-sdk.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/extend/develop/styles-from-widget-sdk.md)
* Product: **devops**
* Technology: **devops-ecosystem**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @slushhpuppy, Thanks for reaching out. I'll follow up on this and be in touch.

**Comment by JllyGrnGiant** [comment]
Hello @slushhpuppy!
Thanks for the feedback.

The widget styles documentation and widget extension support was written before theming was introduced in Azure DevOps.

Theming support for extensions was introduced with the new [Azure DevOps Web Extension SDK](https://github.com/Microsoft/azure-devops-extension-sdk), but currently widget extensions only support the [old extension SDK](https://github.com/Microsoft/vss-web-extension-sdk).

The good news is we're actively investigating adding support for widget/widget configuration development using the new SDK! As part of that work new widget extension development documentation will be written. However I don't have a date right now to share when that feature will be completed.

In the meantime, we recommend considering the current state of this widget styles document as deprecated and recommend styling your widgets and widget configurations without relying on `WidgetHelpers.IncludeWidgetStyles();` and `WidgetHelpers.IncludeWidgetConfigurationStyles();`

**Comment by chcomley** [comment]
Hi @slushhpuppy, I rather enjoy your username. :) I'm going to be closing this issue. Do let us know if you have any further questions! Thank you!
