### ISSUE TITLE
Incomplete documentation

### ISSUE THREAD

**Issue by Phydeauxman** [MicrosoftDocs/vsts-docs#545]
The article gives you the option of using VSTS or GitHub for source control but then the rest of the article focuses on using VSTS for source control.  There are steps missing when you don't use VSTS for source control.  If you use GitHub (or anything other than VSTS for source control), you have to connect your existing VSTS account with the source before you can perform the "Configure continuous delivery" steps.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f9e617bc-bf8d-0348-5fd4-7b040e4d2ff3
* Version Independent ID: ded5c7ec-feee-b573-ffbf-c972d25135bb
* Content: [Deploy your app to an Azure web app](https://docs.microsoft.com/en-us/vsts/build-release/apps/cd/azure/aspnet-core-to-azure-webapp?view=vsts&tabs=github)
* Content Source: [docs/build-release/apps/cd/azure/aspnet-core-to-azure-webapp.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/build-release/apps/cd/azure/aspnet-core-to-azure-webapp.md)
* Service: **unspecified**
* GitHub Login: @alewis
* Microsoft Alias: **alewis**

**Comment by alexhomer1** [comment]
Thank you for your feedback. I have passed it to the production team to investigate and will let you know their response.

**Comment by alexhomer1** [comment]
We are working on a new topic that fully explains how to connect to other source repositories. I'll update the topic with details when this is published.
