### ISSUE TITLE
migration from agile to scrum or visa versa

### ISSUE THREAD

**Issue by sanazramezan** [MicrosoftDocs/vsts-docs#5456]
None of the default processes can be migrated to another.
You can only migrate from parent to child process or child to parent that you have created yourself.
Therefore, you cannot migrate from scrum to agile or from agile to scrum unless you create a scrum-like or agile-like process in the sub directories of each process.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5969861-6f6b-3da1-7eb3-2ee278110937
* Version Independent ID: ae1c687d-7c93-ba01-f63c-2f1df95ed873
* Content: [Create and manage an inherited process - Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/organizations/settings/work/manage-process?view=azure-devops#feedback)
* Content Source: [docs/organizations/settings/work/manage-process.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/settings/work/manage-process.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@sanazramezan  - Thank you for the feedback. Your statement is correct. I believe this is documented in this topic - https://docs.microsoft.com/en-us/azure/devops/organizations/settings/work/change-process-agile-to-scrum?view=azure-devops - however, I'll clarify it in the current topic as you have noted.
