### ISSUE TITLE
Specs for hosted agents? Recommended specs for private agents?

### ISSUE THREAD

**Issue by iyerusad** [MicrosoftDocs/vsts-docs#546]
What is the SKU used for hosted agents? Assuming hosted on Azure IaaS.

What is the recommended specs for a private agent? Will this differ significantly whether using a docker container or running as system service?

These all questions I can make some educated guesses on, even validate to some extent by running a job to check what I can get from hosted agent instance, but presumably should be documented. The use case for this information is when spinning up private agents and wanting to maintain some semblance of similar performance/specs (if only to serve as template).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 47625b86-abd5-ee15-6d61-8bcf81861b96
* Version Independent ID: be9a6174-a69b-7aed-d584-5f602fcc5eb4
* Content: [Build and Release Agents](https://docs.microsoft.com/en-us/vsts/build-release/concepts/agents/agents?view=vsts)
* Content Source: [docs/build-release/concepts/agents/agents.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/build-release/concepts/agents/agents.md)
* Service: **unspecified**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by chrisrpatterson** [comment]
The hosted agents are DS2_v2 or DS2_v3 machines depending on the Azure region and what we are able to get capacity for in a given region.  For private agents it is heavily dependent on your workload.  For example to build our VSTS code base all up we have 24 core machines and run 4 agents on them.  For building the agent code base we use the hosted pools.

**Comment by VinKamat** [comment]
What are the other pre-requisites for private agent such that Azure tasks are run properly? I've installed Azure PS and AzureRM modules however still can't copy a file to Azure Blob Storage. This works fine on the Hosted VS2017 agent.

**Comment by chrisrpatterson** [comment]
You should ask this question on the https://github.com/microsoft/vsts-tasks repo

**Comment by mlearned** [comment]
@VinKamat  were you able to get your copy to work?

**Comment by vtbassmatt** [comment]
The [hosted agents](https://docs.microsoft.com/en-us/vsts/pipelines/agents/hosted?view=vsts#capabilities-and-limitations) topic now includes details about the SKUs. As Chris mentioned, it's not easy to recommend hardware for private agents, but I'll mention what we use as part of [that topic](https://docs.microsoft.com/en-us/vsts/pipelines/agents/v2-windows?view=vsts).
