### ISSUE TITLE
The documented Azure DevOps IP addresses are incomplete

### ISSUE THREAD

**Issue by floriankoch** [MicrosoftDocs/vsts-docs#5460]
Hi,

we try to open the Azure DevOps IP ranges in our on-prem firewall to use Azure DevOps git repositorys with ssh
The documented IP Ranges are only valid for https connections, the ssh endpoints are missing.

#SSH Clone URL
% ping vs-ssh.visualstudio.com
PING tfsprodweu2.westeurope.cloudapp.azure.com (52.236.147.103) 56(84) bytes of data.
^C
--- tfsprodweu2.westeurope.cloudapp.azure.com ping statistics ---
3 packets transmitted, 0 received, 100% packet loss, time 2002ms

#HTTPS Clone URL
% ping dvagazure.visualstudio.com
PING l-0009.l-msedge.net (13.107.42.18) 56(84) bytes of data.

kind regards

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc5a4cfa-aa84-9f0f-55f4-71ec4861c070
* Version Independent ID: d621620a-c924-03b1-8b43-f99c33e58bb8
* Content: [Add IP addresses and URLs to allow list - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/security/allow-list-ip-url?view=azure-devops#feedback)
* Content Source: [docs/organizations/security/allow-list-ip-url.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/security/allow-list-ip-url.md)
* Product: **devops**
* Technology: **devops-whitepapers**
* GitHub Login: @chcomley
* Microsoft Alias: **jominana**

**Comment by chcomley** [comment]
Hi @floriankoch, Thanks for reaching out. We'll look into this and be in touch. Thanks again!

**Comment by ryanps1** [comment]
Hi @chcomley - do you have any update on this?

**Comment by chcomley** [comment]
Hi @ryanps1, I'll be publishing an update to the article today, so stay tuned. Thanks for following up!

**Comment by congyiwu** [comment]
In the meantime, if your blocked, this is roughly what's going to be in the update:

## SSH connections 

If you need to connect to Git repositories on Azure DevOps with SSH, you’ll need to allow requests to port 22 for the following: 
* ssh.dev.azure.com  
* ssh.visualstudio.com
* All IP addresses in the "name": "AzureCloud" section of [this file](https://www.microsoft.com/en-us/download/details.aspx?id=56519) (updated weekly): Azure IP ranges and Service Tags - Public Cloud

**Comment by l3ender** [comment]
@congyiwu You mention the following hostnames:
* ssh.dev.azure.com
* ssh.visualstudio.com

However, if cloning a repo from Azure DevOps, I am seeing the following hostname instead:
* vs-ssh.visualstudio.com

If we are able to whitelist by hostname/domain, should we use the latter instead?

**Comment by congyiwu** [comment]
@l3ender sorry about that! `vs-ssh.visualstudio.com` is actually the correct hostname, not `ssh.visualstudio.com`.

I created a PR for a fix: #5843
