### ISSUE TITLE
Cancel an import

### ISSUE THREAD

**Issue by misd92** [MicrosoftDocs/vsts-docs#5462]
I would like to stop a running import, but I don't find any options to do. Is there a way to achieve this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4fa0ebd3-8437-8508-5a8d-462186fcce80
* Version Independent ID: efe892fe-387e-0a61-fe7d-33d2ac99dfa9
* Content: [Migration import from Azure DevOps Server to Azure DevOps Services - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/migrate/migration-import?view=azure-devops#feedback)
* Content Source: [docs/migrate/migration-import.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/migrate/migration-import.md)
* Product: **devops**
* Technology: **devops-learn**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by elbatk** [comment]
Hi @misd92 , adding @roofers for this one.

**Comment by roofers** [comment]
Hi @misd92 - There currently isn't a way to stop an import that's already running. You will have to wait for the currently running import to finish or open a customer support ticket to have the import cancelled.

**Comment by WilliamAntonRohm** [comment]
@misd92, thank you for your feedback.

@roofers, thanks for your answer.

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
