### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by tinohager** [MicrosoftDocs/vsts-docs#5464]
`This module is open source on GitHub.` the link to the github project is broken

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 210908e8-c062-c323-8463-fcace04ec775
* Version Independent ID: c5d9920b-15d1-ba28-b6e0-121977f4164f
* Content: [Migrate your packages to Azure Artifacts](https://docs.microsoft.com/en-us/azure/devops/artifacts/tutorials/migrate-packages?view=azure-devops)
* Content Source: [docs/artifacts/tutorials/migrate-packages.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/artifacts/tutorials/migrate-packages.md)
* Product: **devops**
* Technology: **devops-artifacts**
* GitHub Login: @chasewilson
* Microsoft Alias: **phwilson**

**Comment by msebolt** [comment]
@tinohager  Thank you for the feedback.

The link is working now.

**Comment by tinohager** [comment]
@msebolt It isn't working on my test

**Comment by msebolt** [comment]
@tinohager Sorry for the confusion, the link is a private repo.

**Comment by msebolt** [comment]
Re-assigned to the author.

**Comment by chasewilson** [comment]
@tinohager, thank you for the feedback and sorry about the link! The repo is supposed to be public but isn't yet for some reason. I'm working on getting that opened up and will let you know when I get it switched over.

**Comment by chasewilson** [comment]
@tinohager, the repo has been made public so you should be able to reach it :) feel free to reach out if you have any more issues
