### ISSUE TITLE
How do I escape backticks within code snippets?

### ISSUE THREAD

**Issue by biltongza** [MicrosoftDocs/vsts-docs#5473]
I am trying to demonstrate using string interpolation in a typescript file, which uses the backtick character to turn on the feature. I have tried using `\`string/${myVariable}\`` but that does not work and instead shows just the first backtick in the code snippet and then the rest of my string as plain text.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fa622358-f5bb-1f5c-177a-081a37b6acef
* Version Independent ID: 72f7fd16-a822-66c8-3a34-8905645ce5f2
* Content: [Markdown syntax for files, widgets, and wikis in Azure DevOps - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/project/wiki/markdown-guidance?view=azure-devops#ignore-or-escape-markdown-syntax-to-enter-specific-or-literal-characters)
* Content Source: [docs/project/wiki/markdown-guidance.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/project/wiki/markdown-guidance.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @biltongza, Thanks for reaching out and sorry you're experiencing an issue. I'm following up with my PM and will be in touch ASAP. Thanks!

**Comment by adramasu** [comment]
Hi @biltongza
Please try the following and let us know if this works.
![image](https://user-images.githubusercontent.com/39327028/64401442-92e62300-d08e-11e9-8f3d-617440d9ad48.png)
cc: @chcomley

**Comment by chcomley** [comment]
@biltongza, I'll be closing this issue. Please let us know if the example adramasu provided isn't helpful! Thanks!
