### ISSUE TITLE
Azure DevOps - Restrict modification of work items based on a user or group - System.State

### ISSUE THREAD

**Issue by Andy9874** [MicrosoftDocs/vsts-docs#5480]
I'm using Azure DevOps and trying to apply the rule "Restrict who can create specific work item types, such as Epics or Features". Under "Actions" for "Make read-only" I don't have the "State" or "System.State" field available to me. Please help.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b9a3085-d952-f4ba-e7c5-88e8ea7b3b29
* Version Independent ID: fb29b46c-3b07-ec11-f731-78c1371eef33
* Content: [Grant or restrict access to select features - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/security/restrict-access?view=azure-devops#feedback)
* Content Source: [docs/organizations/security/restrict-access.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/security/restrict-access.md)
* Product: **devops**
* Technology: **devops-security**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by msebolt** [comment]
@Andy9874  Thank you for the question.

States are integrated into the workflow and are not meant to be read-only.  The `System.State` in the article refers to a custom field the author created.

To restrict access to work items, either use [work areas](https://docs.microsoft.com/en-us/azure/devops/organizations/security/set-permissions-access-work-tracking?view=azure-devops) or use your rule above with your own custom state field.
