### ISSUE TITLE
Denying Read permission at the branch-level

### ISSUE THREAD

**Issue by asasine** [MicrosoftDocs/vsts-docs#5482]
Is it possible to deny a user or group permission to read specific branches within a repo while allowing them to read the remaining contents of the repo?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 68686c2b-c69a-d9e4-3e21-a46d231b649c
* Version Independent ID: 049659da-1772-3166-f909-4feeb8a97730
* Content: [What are all the default permissions and groups? - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/security/permissions?view=azure-devops&tabs=current-page#git-repository-object-level)
* Content Source: [docs/organizations/security/permissions.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/security/permissions.md)
* Product: **devops**
* Technology: **devops-security**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by msebolt** [comment]
@asasine Thank you for the question.

Please take a look at [branch permissions](https://docs.microsoft.com/en-us/azure/devops/repos/git/branch-permissions?view=azure-devops#use-the-branches-view-to-configure-security) for how to configure security on individual branches.

**Comment by asasine** [comment]
The branch permissions article does not mention how to deny a user or group the read permission for specific branches.

**Comment by msebolt** [comment]
Apparently this can only be done at the repo level, since Git branches are only pointers to commits.

More from [post](https://stackoverflow.com/questions/53560134/is-it-possible-to-hide-branches-in-azure-devops-for-specific-users) on StackOverflow.

**Comment by asasine** [comment]
Great, thanks for the clarity

**Comment by msebolt** [comment]
Sure, no problem.  

If there are any further issues please create another issue or post a comment below.
