### ISSUE TITLE
What wildcard is used for recursion?

### ISSUE THREAD

**Issue by clisc** [MicrosoftDocs/vsts-docs#5484]
For example, I want to run a build for check-in validation if any change was made to any file in the src/ directory, recursively.

The documentation only talks about src/* which appears to only include changes directly under the src/ directory.  What about recursion?  Does src/** work?  If so, can this be added to this doc?  Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7cd986e0-608c-1d8c-6faf-ecdb12e10bc6
* Version Independent ID: d60c996e-187e-dd6b-7f3a-dd056a1603f4
* Content: [Protect your Git branches with policies - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/branch-policies?view=azure-devops#what-type-of-wildcard-characters-are-supported-when-configuring-required-code-reviewers)
* Content Source: [docs/repos/git/branch-policies.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/repos/git/branch-policies.md)
* Product: **devops**
* Technology: **devops-code-git**
* GitHub Login: @apawast
* Microsoft Alias: **sdanie**

**Comment by DotNetSparky** [comment]
A single asterisk is automatically recursive...

> Single asterisks (*) are supported, and will match any number of characters, including both forward-slashes (/) and back-slashes (\). Question marks (?) will match any single character.

**Comment by clisc** [comment]
I see, I must have missed the part about forward slashes and back slashes, or it didn't immediately process to me that it meant recursion.  Thanks!
