### ISSUE TITLE
performMultiLevelLookup default's are not documented

### ISSUE THREAD

**Issue by onovotny** [MicrosoftDocs/vsts-docs#5485]
the description for performMultiLevelLookup talks about checked or unchecked but doesn't say what the default is. I assume the value should be `true`/`false`, but that's not specified either.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f9660c58-3366-f1be-8380-d6cf1d3c0150
* Version Independent ID: 226a4fd8-bce8-3333-d8d6-7af933c7b060
* Content: [.NET Core Tool Installer task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/dotnet-core-tool-installer?view=azure-devops#feedback)
* Content Source: [docs/pipelines/tasks/tool/dotnet-core-tool-installer.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/tool/dotnet-core-tool-installer.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @pulkitaggarwl
* Microsoft Alias: **puagarw**

**Comment by msebolt** [comment]
@onovotny  Thank you for the question.

You are correct, the value should be `true` or `false` and the default value is `false`.

Changes to the documentation are pending.

**Comment by msebolt** [comment]
The documentation has been updated.
