### ISSUE TITLE
Installation Instructions for .vsix Files

### ISSUE THREAD

**Issue by jmoser11** [MicrosoftDocs/vsts-docs#5486]
Please add instructions for installing Extensions via offline .vsix files. Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b4290c10-4f12-f4f2-a189-4395fbe5525b
* Version Independent ID: 41204723-bd4b-270d-f13f-df961c565ca9
* Content: [Install extensions](https://docs.microsoft.com/en-us/azure/devops/marketplace/install-extension?view=azure-devops-2019#feedback)
* Content Source: [docs/marketplace/install-extension.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/marketplace/install-extension.md)
* Product: **devops**
* Technology: **devops-marketplace**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @jmoser11, Thanks for your suggestion. I'll look into this and be in touch soon. Thanks again!

**Comment by chcomley** [comment]
Hi @jmoser11, I spoke with the PM who determined that we won't be addressing your ask at this time. Thank you very much for providing your feedback. If you ever run into troubles you can always contact [Support](https://visualstudio.microsoft.com/vs/support/#talktous). Thanks and have a great day.
