### ISSUE TITLE
Documentation unclear for --once flag

### ISSUE THREAD

**Issue by Launcelot555** [MicrosoftDocs/vsts-docs#5487]
The documentation implies --once should be used as part of .\config.cmd when, in fact, it should be used at part of .\run.cmd.

E.g. .\run.cmd --once for a one-time run.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43799c5d-2f13-cc76-a1c0-a3f850e16d4e
* Version Independent ID: 97a5b73f-faf7-f9c0-9269-fc79984616d6
* Content: [Deploy a Azure Pipelines agent on Windows - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/v2-windows?view=azure-devops)
* Content Source: [docs/pipelines/agents/v2-windows.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/agents/v2-windows.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by alex-peck** [comment]
Fixed 02690d83da2bb12a3f0bc721343ab89994c183af
