### ISSUE TITLE
Exterior matrix variables not working from inside templates

### ISSUE THREAD

**Issue by lashtear** [MicrosoftDocs/vsts-docs#5489]
Is there a way to pass variables defined in a matrix strategy to template invocations? `${{ parameter.foo }}` references only what it was sent to, e.g. invoking with `foo: $(bar)` will yield a literal `$(bar)` inside the instantiated template, and the variable does not automatically propagate, as best I can tell.  Forcing compile time eval of parameter settings, e.g. invoking with `foo: ${{ variables.bar }}` results in an empty string, because matrix variable instantiation is dynamic and not available at pipeline compile time.  So uh.  How do?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 67504b34-d64b-02a4-2e10-ab99f3b8cfe4
* Version Independent ID: 2cf63b2e-184b-7726-3b8a-d8baffd6fcce
* Content: [Jobs in Azure Pipelines, Azure DevOps Server, and TFS - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/phases?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/process/phases.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/phases.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @vijayma
* Microsoft Alias: **vijayma**

**Comment by vtbassmatt** [comment]
There's not a way to do this. Parameters are fully evaluated at template compilation time, while matrix variables are not available until job runtime.
