### ISSUE TITLE
Is "secureFile" type valid in task.json?

### ISSUE THREAD

**Issue by scott-lin** [MicrosoftDocs/vsts-docs#549]
The article states, "You can build your own tasks that use secure files by using inputs with type secureFile in the task.json." However, the tasks.json schema does not mention secureFile as a valid type. Schema definition I'm reading is https://raw.githubusercontent.com/Microsoft/vsts-task-lib/master/tasks.schema.json.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 140dcb9a-2ed0-11d5-064b-068f863ed97f
* Version Independent ID: 672d2aa3-cf0d-9207-c97c-e2eba14506b7
* Content: [Secure files for VSTS and Team Foundation Server](https://docs.microsoft.com/en-us/vsts/build-release/concepts/library/secure-files?view=vsts)
* Content Source: [docs/build-release/concepts/library/secure-files.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/build-release/concepts/library/secure-files.md)
* Service: **unspecified**
* GitHub Login: @erickson-doug
* Microsoft Alias: **madhurig**

**Comment by steved0x** [comment]
@scott-lin It is supported, we'll get the doc updated, and here is an example:

https://github.com/Microsoft/vsts-tasks/blob/master/Tasks/InstallAppleCertificate/task.json#L37

Thank you,

Steve
