### ISSUE TITLE
Duplicated content in first Note of the article

### ISSUE THREAD

**Issue by Dann1112** [MicrosoftDocs/vsts-docs#5490]
Duplicated content in first **Note** of the article

**ACTUAL:**
Area Paths and Iteration Paths are also referred to as Classification Nodes. You can manage them programmatically via the Classification Nodes (REST API) or the Azure DevOps CLI commands, az boards area (Azure DevOps CLI) and az boards area (Azure DevOps CLI).

**SUGGESTED:**
Area Paths and Iteration Paths are also referred to as Classification Nodes. You can manage them programmatically via the Classification Nodes (REST API) or the Azure DevOps CLI commands, az boards area (Azure DevOps CLI).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d41d9341-94a7-4df3-ea46-d76c5c39c14d
* Version Independent ID: 777f7374-ce28-d9d7-9d64-ba44603693c7
* Content: [Define area paths for a project - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/organizations/settings/set-area-paths?view=azure-devops&tabs=browser)
* Content Source: [docs/organizations/settings/set-area-paths.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/settings/set-area-paths.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by msebolt** [comment]
@Dann1112 Thank you for the feedback.

The documentation has been updated.
