### ISSUE TITLE
 update the documentation to reflect that the Docker template is accessible after enabling the Multi-stage pipeline from preview features

### ISSUE THREAD

**Issue by mengyang88** [MicrosoftDocs/vsts-docs#5495]
[Suggestion] update the documentation to reflect that the Docker template is accessible after enabling the Multi-stage pipeline from preview features

**Comment by WilliamAntonRohm** [comment]
@mengyang88  Thanks for your feedback; we appreciate it. To make sure we have all the information needed to triage your issue, please let us know which topic you’re referencing, or provide more context around the general task.

**Comment by msebolt** [comment]
@thomps23 Do you know of what article might be referenced above?

**Comment by WilliamAntonRohm** [comment]
@mengyang88 -- I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
