### ISSUE TITLE
--once is not a parameter for config

### ISSUE THREAD

**Issue by kirkone** [MicrosoftDocs/vsts-docs#5497]
Hello,

the parameter `--once` can not be used while configuration.
It can only be used for run.

Please have a look here:
https://github.com/microsoft/azure-pipelines-agent/issues/1997#issuecomment-468110209

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 23328b13-f079-ad21-5d7a-6c640f25391c
* Version Independent ID: 4a39889d-fa00-ae2b-aa43-f358631b7b1a
* Content: [Deploy a Azure Pipelines agent on Linux - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/v2-linux?view=azure-devops#feedback)
* Content Source: [docs/pipelines/agents/v2-linux.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/agents/v2-linux.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by msebolt** [comment]
@kirkone  Thank you for the feedback.

Please refer to open issue https://github.com/MicrosoftDocs/vsts-docs/issues/5487.
