### ISSUE TITLE
Someone must view a page in your organization regularly for CI and scheduled builds to run.  Is this an April fools joke?

### ISSUE THREAD

**Issue by Bossmojoman** [MicrosoftDocs/vsts-docs#5500]
The docs state:

"Someone must view a page in your organization regularly for CI and scheduled builds to run. It can be any page, including, for example, Azure Pipelines.

Your organization goes dormant five minutes after the last user signed out of Azure DevOps. After that, each of your build pipelines will run one more time. For example, while your organization is dormant:

A nightly build of code in your organization will run only one night until someone signs in again.

CI builds of an Other Git repo will stop running until someone signs in again."

This cant be serious right? In what world does pipeline automation require manual logging into a page to get your pipelines to function?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5673ec1-c7d1-e0ac-043a-8fc3d5b226a9
* Version Independent ID: b4872831-51c0-6cf8-1c56-de20beb38a80
* Content: [Build pipeline triggers - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/triggers?tabs=yaml&view=azure-devops#my-build-didnt-run-what-happened)
* Content Source: [docs/pipelines/build/triggers.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/build/triggers.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by buckleyGI** [comment]
+1 (lol)

**Comment by jb-git** [comment]
And why is it closed? It's so weird!

**Comment by Bossmojoman** [comment]
> And why is it closed? It's so weird!

I closed it and opened a suggestion on MS's suggestions page

**Comment by buckleyGI** [comment]
Thanks. Do you have a link to that suggestion?
