### ISSUE TITLE
If a user is in a group that is granted the visual studio subscription access level, and doesn't actually have a visual studio subscription, do they fall back to the stakeholder access level?

### ISSUE THREAD

**Issue by MarkIannucci** [MicrosoftDocs/vsts-docs#5504]
We would like to only maintain our visual studio subscriptions in one place (the visual studio subscriber portal), and we want a bunch of people to have stakeholder access to Azure Devops.  So if we have a bunch of users in an AD group some of them have VS subscriptions and some don't will people who have VS subscriptions assigned to them get the appropriate VS Subscriber access when they login?  Conversely, if the person doesn't have a VS subscription, will they get stakeholder access?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba38644a-fe6c-e644-2f35-2cf6fa092650
* Version Independent ID: 7d18b423-923f-d9c4-e451-ab7f8ff27bb1
* Content: [Add group rule to assign access levels, extensions - Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/assign-access-levels-and-extensions-by-group-membership?view=azure-devops)
* Content Source: [docs/organizations/accounts/assign-access-levels-and-extensions-by-group-membership.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/accounts/assign-access-levels-and-extensions-by-group-membership.md)
* Product: **devops**
* Technology: **devops-accounts**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @marklannucci, Thanks for reaching out. Yes, anyone with a VS subscription will get it when they sign in to Azure DevOps, regardless of the group (unless its one that happens to increase their access, ie. a Pro subscriber with a group rule that grants them Basic + Test Plans). If you set up a group rule that assigns Stakeholder to everyone, anyone with a subscription will get it, and everyone else will get Stakeholder. That will work as you described.
