### ISSUE TITLE
Terminology discrepancy is confusing, 'team' vs 'project' ?

### ISSUE THREAD

**Issue by MightyPen** [MicrosoftDocs/vsts-docs#5506]
In the header section named 'Add a work item using a template', the first step tells us to open the settings for a "team".  But the associated screenshot has a red circle around "Project settings". Which is it, 'team' or 'project'?
(PMs may have been changing their minds about terms after documentation was written.)

If 'team' and 'project' are synonyms, it might be less confusing to:
- Choose one term and stick with it, and discard usages of the other term.
- Choose the term that the UI uses (in this case 'project').

---

Thanks.  (GeneMi)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1debd814-eb48-c984-a4f9-7606093e9617
* Version Independent ID: f48ef796-c2e3-8fa3-6c41-326a5b252a3d
* Content: [Add and use work item templates to update user stories, tasks, issues, and other work items - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/backlogs/work-item-template?view=azure-devops&tabs=browser#add-a-work-item-using-a-template)
* Content Source: [docs/boards/backlogs/work-item-template.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/boards/backlogs/work-item-template.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by msebolt** [comment]
@MightyPen  Thank you for the feedback.

The documentation has been updated.
