### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by v-wilock** [MicrosoftDocs/vsts-docs#5507]
In the line "Authentication verifies a user's identify...", it should be "identity".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 851595a3-32b8-c0e4-ff4f-aa84cf436175
* Version Independent ID: c2cb9c6c-de29-a7a9-9728-fbbc1d223a4f
* Content: [How are security and identity managed? - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/security/about-security-identity?toc=%2Fazure%2Fdevops%2Forganizations%2Fsecurity%2Ftoc.json&bc=%2Fazure%2Fdevops%2Forganizations%2Fsecurity%2Fbreadcrumb%2Ftoc.json&view=azure-devops#feedback)
* Content Source: [docs/organizations/security/about-security-identity.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/security/about-security-identity.md)
* Product: **devops**
* Technology: **devops-security**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by msebolt** [comment]
@v-wilock Thank you for the feedback.

The documentation has been updated.
