### ISSUE TITLE
"vsts-npm-auth" - Could not find a part of the path 'Z:\'.

### ISSUE THREAD

**Issue by mlewis22** [MicrosoftDocs/vsts-docs#5508]
I am trying to connect to my artifact registry.

I have followed the instructions [here](https://docs.microsoft.com/en-us/azure/devops/artifacts/get-started-npm?view=azure-devops&tabs=windows)

- I have set up a .npmrc file in my folder along side a package.json.
- my registry has been added to .npmrc file.
- I have globally installed the vsts-npm-auth library
     `npm install -g vsts-npm-auth`
- i have add the following command to my package
`"scripts": {
    "refreshVSToken": "vsts-npm-auth -config .npmrc"
}`
- when i try running refreshVS Token.
`npm run refreshVSToken`

i get an error stating Could not find a part of the path 'Z:\'.

I am using Windows 10

What is causing this error?

**Comment by msebolt** [comment]
@mlewis22  We're sorry you're experiencing issues.

Can you try manually moving the `.npmrc` file from your Z: drive to the user folder?  (see [this post](https://stackoverflow.com/questions/44185308/npm-packages-management-using-vsts))

**Comment by msebolt** [comment]
Closing this now, please comment below if there are further issues.

**Comment by maslade** [comment]
If you need to work around this but don't have access to modify your environment variable (or don't want to), you can use `-T` or `-TargetConfig` to explicitly point to the .npmrc you want to write to. This bypasses the `$HOMEDIR` default behavior.

For example, this will authorize me using the .npmrc from my current directory, but will write the credentials to my user directory at `~/.npmrc`.

`$ vsts-npm-auth -config .npmrc -TargetConfig ~/.npmrc`

**Comment by jkobylec** [comment]
I think it would make sense for vsts-npm-auth to use `%HOME%` as the expected user .npmrc location, rather than explicitly concatenating `%HOMEDRIVE%` and `%HOMEPATH%`, if only for the sake of being consistent with npm's own behavior here. @maslade would you agree?

To that point, is there a proper place to record issues with the vsts-npm-auth utility itself, rather than the documentation? There's no repo linked on the npm page.
