### ISSUE TITLE
ADO IP Ranges Inaccurate

### ISSUE THREAD

**Issue by sspage** [MicrosoftDocs/vsts-docs#5509]
You have two different links in the doc above.  The link that is called "weekly JSON file" seems to go to the newer file (which is great that it breaks things down by service) and the link called "weekly file" goes to the deprecated XML... that should be fixed.

The bigger issue is when I use the weekly file, I see no service for Azure DevOps.  I tried searching for a known Azure DevOps IP that we have seen used and it's not in your list at all... not under "AzureCloud" or any other service that we can see.  It seems like something is missing here...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 99af681d-41ad-da15-0b72-08b5cd5a11ac
* Version Independent ID: 2fa0df36-a437-8cbb-b019-b49b31b1e116
* Content: [Microsoft-hosted agents for Azure Pipelines - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops#feedback)
* Content Source: [docs/pipelines/agents/hosted.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/agents/hosted.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @joebourneMS
* Microsoft Alias: **jobourne**

**Comment by msebolt** [comment]
@sspage Thank you for the feedback.

@thoms23  Can you check on the alias above and assign the writer?  @joebourneMS doesn't seem to exist anymore.

**Comment by phetzel1** [comment]
Moreover, it would be really helpful to give an example script to automatically grab the file and open the firewall based on the json. I'm having trouble connecting the dots on using the weekly json file to open up the firewall in an automated way.

**Comment by archiebw-amido** [comment]
> The bigger issue is when I use the weekly file, I **see no service for Azure DevOps.** I tried searching for a known Azure DevOps IP that we have seen used and it's not in your list at all... not under "AzureCloud" or any other service that we can see. It seems like something is missing here...

Is there any update on the above? I have checked the file referenced in #5509 and It's not clear if the Azure DevOps hosted agents IP ranges are listed.
