### ISSUE TITLE
How to use ${{ if...}} to modify task inputs

### ISSUE THREAD

**Issue by henry-padilla** [MicrosoftDocs/vsts-docs#5515]
I am trying to download build artifacts but some env need latest and some need specific build. So I'm trying to set the inputs like so:
          - task: DownloadPipelineArtifact@2
            inputs:
              project: 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx'
              source: 'specific'
              pipeline : 1111
              ${{ if parameters.useLatest }}:
                runVersion: 'latestFromBranch'
                runBranch: 'refs/heads/develop'
              ${{ if not(parameters.useLatest) }}:
                runVersion: 'specific'
                runId: 123456

I keep getting an error "##[error]No builds currently exist in the build definition supplied."
What is going wrong?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77c58a78-a567-e99a-9eb7-62dddd1b90b6
* Version Independent ID: 680a79bc-11de-39fc-43e3-e07dc762db18
* Content: [Expressions - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/expressions?view=azure-devops#functions)
* Content Source: [docs/pipelines/process/expressions.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/expressions.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by msebolt** [comment]
@henry-padilla  Thank you for the question.

Perhaps try changing the conditional syntax:

```
${{ if eq(parameters.useLatest, 'true') }}:
runVersion: 'latestFromBranch'
runBranch: 'refs/heads/develop'
${{ if ne(parameters.useLatest, 'true') }}:
runVersion: 'specific'
runId: 123456
```

See **Step template paramters** section [here](https://docs.microsoft.com/azure/devops/pipelines/process/templates?view=azure-devops#passing-parameters).
