### ISSUE TITLE
Not a cumulative flow diagram

### ISSUE THREAD

**Issue by nbrown02** [MicrosoftDocs/vsts-docs#5518]
This isn't actually a cumulative flow diagram. It's not cumulative over time it's simply showing the aggregation on a particular date - this is actually counter to your own cumulative flow diagrams (which are correct) within the core Azure DevOps product :/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b4de0feb-f387-0d5e-9615-28ee2ae90df0
* Version Independent ID: c93276b2-eaf0-c675-a3ba-cb7f48f3d18c
* Content: [Cumulative Flow Diagram (CFD) sample Power BI report - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/report/powerbi/sample-boards-cfd?view=azure-devops&tabs=powerbi#feedback)
* Content Source: [docs/report/powerbi/sample-boards-cfd.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/report/powerbi/sample-boards-cfd.md)
* Product: **devops**
* Technology: **devops-analytics**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@greggboer - Could you respond to this feedback?

**Comment by greggboer** [comment]
@nbrown02, it is actually exactly like the CFD that is in the Azure DevOps product. However, my example screenshot filters out the "Done" column, so it doesn't look like a CFD. If you filtered out the Done column on the in-product CFD, it would look similar
I'll update this doc to make sure the example shows a more CFD-looking chart.

**Comment by KathrynEE** [comment]
Closing as Gregg has answered the question.
