### ISSUE TITLE
Capitalization with multiple stage names

### ISSUE THREAD

**Issue by duanekord** [MicrosoftDocs/vsts-docs#5523]
The first 2 stages seem to be correctly capitalized but for some reason the third stage is not correct.  I have 3 stage - Build, Deploy_Dev30 and Deploy_Prod.  All of them are declared in the YAML file like that but when I view my previous runs - they display as Build, Deploy_Dev30, deploy_prod.  If needed I can share code/screenshots.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4266f72c-c774-0046-4593-d01eb775d3c3
* Version Independent ID: f20827aa-a6c5-96a8-5969-e576ffbc2e38
* Content: [Stages in Azure Pipelines - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/stages?view=azure-devops&tabs=yaml#feedback)
* Content Source: [docs/pipelines/process/stages.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/stages.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @vijayma
* Microsoft Alias: **vijayma**

**Comment by WilliamAntonRohm** [comment]
It looks like you've encountered an issue with the product itself, rather than an issue with the documentation. To make sure it gets in front of the right people, please [submit your bug]( https://developercommunity.visualstudio.com/content/problem/post.html?space=21) here.
