### ISSUE TITLE
Ambiguous walk-through

### ISSUE THREAD

**Issue by MaartjeVP** [MicrosoftDocs/vsts-docs#5530]
I work in a project that involves many sub-projects. Now one of those projects needs to be renamed. As we work with TFS source control, I want to make absolutely sure I take the right steps. 
But the above walk-through guide seems somewhat ambiguous and is therefore, at least to me, confusing.

For one, it seems that the step where you change the project name via the Organization Settings &gt; General &gt; Overview tab is optional and only needs to be done when you want to change the main project's name, correct?

Also, I don't quite understand why the guide instructs the developer to navigate to https://dev.azure.com/{yourorganization} when you already logged in at the previous step. 

Thirdly, I am now not sure whether it is sufficient to do the steps as listed here (see copied text between brackets) to rename a sub-project. 

Lastly, I am not sure if any additional steps, like renaming assemblies, namespaces etc. are required to make sure that all references are correctly adjusted and the build will succeed. 

----------------
Copied text:
(1. From the Projects page, open the  actions icon menu for the project that you want to rename and choose Rename.
2. Enter a new project name.
Edit the name.
Enter a new project name

If the Rename Project dialog doesn't appear, then you're not a member of the Project Administrators group for that particular project. Learn how to get added to the Project Administrators group.)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 03a7de30-26a7-c7ac-2d62-620522bb2f64
* Version Independent ID: 35d7c5ce-6ebb-19ff-55e0-fd1fe385f462
* Content: [Rename a project - Azure DevOps - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/projects/rename-project?view=azure-devops#rename-a-project)
* Content Source: [docs/organizations/projects/rename-project.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/projects/rename-project.md)
* Product: **devops**
* Technology: **devops-accounts**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @MaartjeVP, I'll get back to you ASAP after I've confirmed this process with my PM. Thanks so much for reaching out

**Comment by chcomley** [comment]
Hi @MaartjeVP, we're sorry for the confusion. I believe we haven't clearly stated that it's not two steps, but that you can do either one OR the other. I'll publish an update today, clearly indicating that you can rename your project either from the Project Settings > Overview page OR from the Projects page. Please let me know if this wasn't helpful. Thank you!

**Comment by MaartjeVP** [comment]
@chcomley This certainly clarifies things. Thanks for getting back to me so quickly and thanks for the clarification. Much appreciated!

**Comment by MaartjeVP** [comment]
@chcomley an additional question regarding my last comment in the original post: it is still not clear to me if I will need to manually rename namespaces and/or referenced assemblies etc.? Looking at your instruction it seems that renaming a project is all you need to do, apart from the extra steps such as clearing caches, updating remotes and getting latest versions. Can I assume that all dependent namespaces, assemblies etc. are automatically updated to reflect the name-change?
