### ISSUE TITLE
Default permissions & access > Build and Release incorrectly says Stakeholders can view build pipelines

### ISSUE THREAD

**Issue by riQQ** [MicrosoftDocs/vsts-docs#5532]
On the site `Default permissions & access` for the platform `TFS 2018` the section `Build and Release` incorrectly says that stakeholders can view build pipelines.

This problem was already fixed for the platform `Azure DevOps Services` in #2091, but it is still incorrect for all the other platforms.
It was fixed in https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/security/_shared/pipelines.md, but not in https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/security/_shared/build-release.md.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a35602ee-9d11-9746-4b79-075e295a5fb8
* Version Independent ID: dbea8e30-e80b-8f13-987e-ef0ad3ba9b83
* Content: [Default permissions and access quick reference - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/security/permissions-access?view=tfs-2018#feedback)
* Content Source: [docs/organizations/security/permissions-access.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/security/permissions-access.md)
* Product: **devops**
* Technology: **devops-security**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@riQQ - Thank you for the feedback. I've added to our backlog to update the topic.

**Comment by riQQ** [comment]
Fixed in 8465c01cc4178bf09e596a3e1e1ab0813cf1b384
