### ISSUE TITLE
Pipeline Name on the Portal

### ISSUE THREAD

**Issue by SamirFarhat** [MicrosoftDocs/vsts-docs#5534]
We are storing many YAML files on the same Repo (Azure Repo). The problem is when importing them, the portal automatically show the 'repo' name as the display name for the first repo, Repo (1) for the second and so on. Is there any 'Pipeline Display Name' option ? 
PS: We can rename the pipeline via the Portal, but why this option is not available as code ?

https://github.com/MicrosoftDocs/vsts-docs/issues/5534
![image](https://user-images.githubusercontent.com/14938496/64543905-57658600-d326-11e9-952d-97f027feba70.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7458d5b2-1bb7-7d87-7ce6-2b0c430b0155
* Version Independent ID: edf5bbd3-a3f0-5426-e985-31290f8afd05
* Content: [YAML schema - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema)
* Content Source: [docs/pipelines/yaml-schema.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/yaml-schema.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @vtbassmatt
* Microsoft Alias: **macoope**

**Comment by WilliamAntonRohm** [comment]
It looks like you've encountered an issue with the product itself, rather than an issue with the documentation. To make sure it gets in front of the right people, please [submit your bug]( https://developercommunity.visualstudio.com/content/problem/post.html?space=21) here.
