### ISSUE TITLE
How to mark build as error if no artifacts where created?

### ISSUE THREAD

**Issue by marcussonestedtbarium** [MicrosoftDocs/vsts-docs#5542]
Currently this is only a warning, so build passes. It shouldn't do that as something else was wrong and no files were created.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b3f565b-88e4-88d6-a534-48ec21e6e3d8
* Version Independent ID: 9fca89ae-4a6e-a43a-2834-1a91ad44c256
* Content: [Publish Build Artifacts task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/publish-build-artifacts?view=azure-devops#feedback)
* Content Source: [docs/pipelines/tasks/utility/publish-build-artifacts.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/utility/publish-build-artifacts.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @DavidStaheli
* Microsoft Alias: **dastahel**

**Comment by msebolt** [comment]
@marcussonestedtbarium Thank you for the feedback.

This seems like a product issue and should be moved to the [azure-pipelines-tasks](https://github.com/Microsoft/azure-pipelines-tasks/issues).

@thomps23 Another example of a transfer issue.

**Comment by marcussonestedtbarium** [comment]
@msebolt Ok. I'll add it there.
