### ISSUE TITLE
Document stakeholder access to Azure Artifacts

### ISSUE THREAD

**Issue by andrewtyped** [MicrosoftDocs/vsts-docs#5543]
I came to this page looking for information about stakeholder access to Azure Artifact feeds. Specifically, I'd like to know if stakeholders can download packages. This page details access to all other major DevOps features, but Artifacts are not mentioned at all. Can you add this information?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17e7fef2-40df-4923-e62e-74ac556cbc6a
* Version Independent ID: af9269b4-1db4-df1f-2520-78ad20baf17b
* Content: [Get started with Stakeholder access - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/security/get-started-stakeholder?view=azure-devops&tabs=agile-process#features-and-functions-available-to-stakeholders)
* Content Source: [docs/organizations/security/get-started-stakeholder.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/security/get-started-stakeholder.md)
* Product: **devops**
* Technology: **devops-new-user**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@andrewtyped - Thank you for your feedback. I will update the topic to reflect that Stakeholders have no access to Azure Artifacts.

**Comment by andrewtyped** [comment]
I'll bring this up because it's not the first time this has happened - but it is jarring when these issues are closed w/out a link to a PR or visible changes to the Docs website. How is the work tracked if not in this issue?
