### ISSUE TITLE
Using latestBuild variable in Build version to download field

### ISSUE THREAD

**Issue by smhbhdr** [MicrosoftDocs/vsts-docs#5546]
'Build version to download' field in 'Download Build Artifacts' has the following three options :

- Latest
- Latest from specific branch
- Specific version

When Specific version is selected system ask to enter build number that artifact will be downloaded. Is it possible here to use a variable ie latestBuild that it will get the latest successful build.

The reason is, I can make a pipeline parameter for this and set a default value. So whenever a pipeline is run, it will by default download the artifact from latest successful build. However, also user can overwrite the build number and enter specific build number to download the artifacts.

**Comment by msebolt** [comment]
@smhbhdr  Thank you for the question.

Try using the [Download Build Artifacts task](https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/download-build-artifacts?view=azure-devops) where it allows you to specify the `buildId` parameter you need using a variable.

If there are any issues please comment below.
