### ISSUE TITLE
How to read secret env vars from bash?

### ISSUE THREAD

**Issue by toqueteos** [MicrosoftDocs/vsts-docs#555]
Both `$FOO` and `$(FOO)` syntax resolve as an empty string in bash

**Comment by toqueteos** [comment]
The only relevant section seems to be [this one](https://docs.microsoft.com/en-us/vsts/build-release/concepts/definitions/build/variables?view=vsts&tabs=shell).

From this I understand that the only way to make this work is to explicitly make TFS resolve the variables by using `bash my_script.sh $(SECRET1) $(SECRET2) ... $(SECRETN)` otherwise they will never ever be available.

**Comment by toqueteos** [comment]
Np. I can wait for now. Worst-case scenario is passing the 15 secret env vars as an argument to the bash script I run 😕

**Comment by andyjlewis** [comment]
Yes, https://docs.microsoft.com/en-us/vsts/build-release/concepts/definitions/build/variables?view=vsts&tabs=shell#set-in-script is how you do it.

**Comment by toqueteos** [comment]
That link is the one I posted 16 days ago. So, again, not helpful.

It'd be clearer to state somewhere in that same page that this approach is the only way to go instead of a code snippet that doesn't even say where's its supposed to go.

Example: `In order to use secret env bars in a bash task you actually do need to explicitly send them as arguments otherwise they'll resolve to empty strings`.

**Comment by vtbassmatt** [comment]
[Secret variables](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=vsts&tabs=yaml%2Cbatch#secret-variables) are documented for both YAML and Designer now.
