### ISSUE TITLE
"Deploy to Azure Kubernetes Service" is no longer a valid option

### ISSUE THREAD

**Issue by abKrazy** [MicrosoftDocs/vsts-docs#5561]
"Deploy to Azure Kubernetes Service" is no longer a valid option in the Configure tab as documented in Step 6. As a result, all the remaining steps are invalid. Tutorial needs to be updated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cbceb1f5-05c3-487d-6e21-dc1b4936a55c
* Version Independent ID: 35355737-9ad9-9df5-b612-806d9df2462b
* Content: [Deploy to Azure Kubernetes Service - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/ecosystems/kubernetes/aks-template?view=azure-devops&tabs=java#feedback)
* Content Source: [docs/pipelines/ecosystems/kubernetes/aks-template.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/ecosystems/kubernetes/aks-template.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @shashankbarsin
* Microsoft Alias: **shasb**

**Comment by IrisZimmermann** [comment]
I am currently facing the same problem. Are there any news on this issue?

**Comment by IsNoGood** [comment]
"If this is not what you see, then make sure the Multi-stage pipelines experience is turned on."

**Comment by mcurko** [comment]
Same problem here. You should stress the fact in the doc that this preview feature needs to be on to follow the tutorial. Now it works.

**Comment by shashankbarsin** [comment]
@mcurko we had already added a note (shown below) on turning on the preview feature for multi-stage pipeline experience. Once that preview feature is turned on, the 'Azure Kubernetes Service' option appears in the recommended template list
![image](https://user-images.githubusercontent.com/4594231/68947725-2b5df980-07dc-11ea-8dab-c26e1aebac91.png)
