### ISSUE TITLE
Allow child teams to subscribe to the parent iteration

### ISSUE THREAD

**Issue by adriantorrie** [MicrosoftDocs/vsts-docs#5562]
We have parent and child teams, and would like to set the iterations once for all teams. How do we do this? It is really a pain to have to go into each and every team and have to add the iterations to.every.team.

This is making people in the org not want to use Azure DevOps boards, it is too admin intensive.

Summary: Allow a project iteration to be subscribed to by the teams so they don't have to manually update all the time.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 044f4655-31fc-ef54-8d71-561d77447295
* Version Independent ID: 2c6dfd7c-3ca2-c63e-8010-d8d34aaf24f0
* Content: [Define iteration paths or sprints for a project or team - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/organizations/settings/set-iteration-paths-sprints?view=azure-devops&tabs=browser#feedback)
* Content Source: [docs/organizations/settings/set-iteration-paths-sprints.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/settings/set-iteration-paths-sprints.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by msebolt** [comment]
@adriantorrie Thank you for the question.

Something like this would be suited to using the REST API.

Do calls to the **Projects** and **Teams** areas of the [Core API](https://docs.microsoft.com/en-us/rest/api/azure/devops/core/?view=azure-devops-rest-5.1) have the required functionality?

**Comment by msebolt** [comment]
Closing this now.  Please comment below if there are any issues.

**Comment by adriantorrie** [comment]
> @adriantorrie Thank you for the question.
> 
> Something like this would be suited to using the REST API.
> 
> Do calls to the **Projects** and **Teams** areas of the [Core API](https://docs.microsoft.com/en-us/rest/api/azure/devops/core/?view=azure-devops-rest-5.1) have the required functionality?

Possibly, but why would you close this issue without confirming that first?? Or at least providing a resolution? Project managers aren't likely to go crafting up REST calls either (they are the ones who typically administer the project in Azure Devops Boards after all).

[Iterations - List - Parameters](https://docs.microsoft.com/en-us/rest/api/azure/devops/work/iterations/list?view=azure-devops-rest-5.1#uri-parameters) appears to allow a call without specifying a team, which I would hope returns all the iterations of the project. From this a scrpt could be written up to generate the necessary POST requests according to [Iterations - Post Team Iteration](https://docs.microsoft.com/en-us/rest/api/azure/devops/work/iterations/post%20team%20iteration?view=azure-devops-rest-5.1). Not exactly user friendly for a Project Manager though.
