### ISSUE TITLE
lack of FQDN for Azure DevOps Service

### ISSUE THREAD

**Issue by tamatsuxyz** [MicrosoftDocs/vsts-docs#5564]
In the following doc, there are lack of FQDNs or invalid expression.
So could you update right information and more detail ?

Add IP addresses and URLs to allow list:
https://docs.microsoft.com/en-us/azure/devops/organizations/security/allow-list-ip-url?view=azure-devops

1 - Releated FQDNs for first sigin-in for Azure DevOps service
azure.microsoft.com
azurecomcdn.azureedge.net
amp.azure.net
aexprodea1.vsaex.visualstudio.com

  - Some of FQDNs are required to create organization.
  - Some of FQDNs are required for first sign-in.

2 - Related Azure AD FQDN
aadcdn.msftauth.net, aadcdn.msauth.net, and so on...
And some of the FQDNs described in DevOps doc, are too wide (live.com, windows.net,)

There are good docs for FQDNs which are used for Azure AD sing-in.
I suggest to clarify more, based on the following doc.

https://docs.microsoft.com/en-us/office365/enterprise/urls-and-ip-address-ranges#microsoft-365-common-and-office-online

3 - Related the "Other important URLs to consider"
Some of FQDNs are described as user should allow sub-domains.
but this document don't clarify. Many of FQDN filtering solution treats differently http://windows.net and http://*.windows.net.

So, it must be clear.
Additionally, you should delete "http://" and "https://"
e.x.) both of windows.net and microsoftonline.com are used https in some of sub-domain.
        * latter is used as login endpoint.
e.x)
  http://windows.net
  http://microsoftonline.com
  https://visualstudio.com
  https://microsoft.com
  https://live.com

**Comment by tamatsuxyz** [comment]
Hi, are there any updates?

**Comment by chcomley** [comment]
Hi @tamatsuxyz, Thanks for following up. The user story that I created for this is currently on my backlog. I hope to get to it next sprint. Do you have a specific question at the moment that we could help you out with? Thanks so much.

**Comment by chcomley** [comment]
Hi @tamatsuxyz, I'll be closing this issue since the item is on my backlog. I'll respond to this issue once the article is updated. Thank you!

**Comment by chcomley** [comment]
I've added some additional IPs, as well as links to more information within the article. Please don't hesitate to @mention me if you have any further feedback about the article. If you need more technical support, I recommend reporting a problem on the Developer Community. Go here: https://developercommunity.visualstudio.com/spaces/21/index.html, choose **Report a problem** > **Azure DevOps.** Thank you!
