### ISSUE TITLE
Documentation lacking on `format` expression

### ISSUE THREAD

**Issue by cocowalla** [MicrosoftDocs/vsts-docs#5567]
I'm trying to use the [format](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/expressions?view=azure-devops#format) expression to format a number, so it's zero-filled. Here's an example of what I've tried:

```
$[format('{0:00}', variables.MyBuildNumber)]
$[format('{0:D2}', variables.MyBuildNumber)]
$[format('{0:##}', variables.MyBuildNumber)]
```

However, no matter what I try I get `TF400898: An Internal Error Occurred` when trying to save my pipeline.

The central issue here appears to be that the docs don't say _anything_ about what format strings are supported - I presumed it supports all .NET format strings, but obviously not.

The request here is to update the documentation for `format` to include a comprehensive list of supported format strings.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77c58a78-a567-e99a-9eb7-62dddd1b90b6
* Version Independent ID: 680a79bc-11de-39fc-43e3-e07dc762db18
* Content: [Expressions - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/expressions?view=azure-devops)
* Content Source: [docs/pipelines/process/expressions.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/expressions.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by juliakm** [comment]
@cocowalla  The documentation will be updated shortly. You can use .NET formatting for updating dates with format. For example, this YAML should work. 

`trigger:
  - '*'

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job:
  variables:
    a: $[format('Hello {0} {1}', 'John', 'Doe')]
    b: $[format('{0:yyyyMMdd}', pipeline.startTime)]    

  steps:
    - bash: echo $(a)
    - bash: echo $(b)
    `

**Comment by asarapas** [comment]
Everyone keeps giving sample for the date. 
But how to format number which came from the counter function to D3 format?

**Comment by gh-andre** [comment]
As far as docs are concerned, the fact that formatting a number is not supported must be called out explicitly on the page describing formatting. The `format` function clearly fails on all variants of .Net format specifiers for numbers. Please fix the docs.

**Comment by celluj34** [comment]
Has this been fixed yet? Would LOVE to format a number that's not a date. Specifically, formatting a number as a result of `counter`.

Please re-open this issue within the context of formatting things that are not dates.

**Comment by gh-andre** [comment]
@celluj34 It's working for a variety of formats. Here's one example. Ignore the narrative around - it's in the context of better docs for `counter`.

https://github.com/MicrosoftDocs/azure-devops-docs/issues/11323#issuecomment-970846453

**Comment by gh-andre** [comment]
@celluj34 I tried your example and it works, with the exception of a padded counter - it just outputs a counter, like `2021.12.08.2`. Is this what you are talking about - to be able to format it `printf`-style, with padding for numbers?

**Comment by gh-andre** [comment]
I should also add that I'm trying it our in Azure DevOps, not on a server. Maybe this is where the difference is.

**Comment by celluj34** [comment]
Yes, you got it right, I want to be able to pad a number. I am also using Azure DevOps (and with azure-hosted build agents).

**Comment by gh-andre** [comment]
The help page only says .NET date formats are accepted and nothing on other formats, like numeric. Sounds like it's not supported. Will leave this to MS to comment on.

FWIW, as a side not, one work-around for same-length build numbers is to start the counter from `100`, so, they will be always 3 digits and it's not likely within a day you would reach the limit, in which case you could just use `1000`, etc.
