### ISSUE TITLE
The section for adding a workitem using a template says to copy the url...

### ISSUE THREAD

**Issue by StingyJack** [MicrosoftDocs/vsts-docs#5575]
... but not what to do with that URL

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1debd814-eb48-c984-a4f9-7606093e9617
* Version Independent ID: f48ef796-c2e3-8fa3-6c41-326a5b252a3d
* Content: [Add and use work item templates to update user stories, tasks, issues, and other work items - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/backlogs/work-item-template?view=azure-devops&tabs=browser#add-a-work-item-using-a-template)
* Content Source: [docs/boards/backlogs/work-item-template.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/boards/backlogs/work-item-template.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@StingyJack - Thank you for your feedback. I've updated the article to indicate that the URL is used to open the template in a browser.
