### ISSUE TITLE
Small mistake in doc

### ISSUE THREAD

**Issue by Omelianenko** [MicrosoftDocs/vsts-docs#5577]
Looks like it should be only two jobs on two different platforms and SDKs. 

"Select Save and then confirm the changes to see your build run three jobs on three different platforms and SDKs."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 521b594c-dbb9-54d5-f56f-00e2f5fa1d92
* Version Independent ID: 509d3e4e-23db-8493-e1a6-acb67ec47e81
* Content: [Customize your pipeline - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/customize-pipeline?view=azure-devops#feedback)
* Content Source: [docs/pipelines/customize-pipeline.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/customize-pipeline.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @vijayma
* Microsoft Alias: **vijayma**

**Comment by msebolt** [comment]
Documentation updated.
