### ISSUE TITLE
Can Follow WorkItem be configured to Follow all changes except for 1 specific field?

### ISSUE THREAD

**Issue by rwjdk** [MicrosoftDocs/vsts-docs#5580]
We have an automated schedule that every hour update a Workitem field with some new SLA information. This works, but also trigger workitems Followed to send out notifiactions which is technically right, but not the intended behaviour. 

Can “Follow Workitem” criterias be custimized somewhere?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 50fb5639-2338-9141-1129-682e46676f7f
* Version Independent ID: 5002bb9e-5ec3-d773-2843-8b20468d6c69
* Content: [Track updates by getting notified of changes made to a user story, bug, or other work item or pull request - Azure Boards & Azure Repos](https://docs.microsoft.com/en-us/azure/devops/boards/work-items/follow-work-items?view=azure-devops#feedback)
* Content Source: [docs/boards/work-items/follow-work-items.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/boards/work-items/follow-work-items.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@rwjdk - Thank you for your inquiry. There is a new feature rolling out to the cloud this week and next which allows you to configure when to get notified when Following a work item. The configure dialog supports the following: 
![image](https://user-images.githubusercontent.com/10856840/64892151-80d52900-d628-11e9-8c9d-7368ce37139f.png)

If it isn't enabled yet for your organization, it should be within the next 2 weeks.
