### ISSUE TITLE
Is there any mechanism to restrict selecting Microsoft-hosted agents

### ISSUE THREAD

**Issue by clix455** [MicrosoftDocs/vsts-docs#5581]
One of our organization's security policies is to use self-hosted agents only. Is there a mechanism to stop users from choosing the microsfot-hosted agents when configuring/running pipelines?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 47625b86-abd5-ee15-6d61-8bcf81861b96
* Version Independent ID: be9a6174-a69b-7aed-d584-5f602fcc5eb4
* Content: [Azure Pipelines Agents - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/agents?view=azure-devops#q--a)
* Content Source: [docs/pipelines/agents/agents.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/agents/agents.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by clix455** [comment]
Thank you Steve, any update on this topic?

**Comment by steved0x** [comment]
@clix455 Not yet, I just sent another ping to that team to see.

**Comment by clix455** [comment]
Thank you Steve.

**Comment by steved0x** [comment]
@clix455 I have some information for you, there are a few ways that you could do it:

1. On a per project basis, you can delete the Azure Pipelines pool by going to the project, project settings, Pipelines agent pool, and then delete it. Then if you decide to restore it you can do so by choosing Add pool, existing. These operations require [administrator permissions](https://docs.microsoft.com/en-us/azure/devops/pipelines/policies/permissions?view=azure-devops#deployment-pool-security-roles).

![image](https://user-images.githubusercontent.com/1580889/65176060-08a0a600-da22-11e9-88e5-f3d2c3822ee9.png)

2. Or you could restrict the readers on the Azure pipelines pool at the org level. Some high level details of this [here](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/pools-queues?view=azure-devops#security) and there is a Q/A about why a user can't see the pool. I think I will add to it, and include info on if they want to hide it, based on a scenario like yours.

**Comment by clix455** [comment]
Thank you Steve.
