### ISSUE TITLE
Git PR affected by a branch policy links are broken

### ISSUE THREAD

**Issue by soulis64** [MicrosoftDocs/vsts-docs#5584]
Under System variables, all "Git PR affected by a branch policy" links point to "https://docs.microsoft.com/en-us/azure/devops/repos/git/branch-policies.md", which is a 404. Under How are the identity variables set?, this link to "branch policy build" works (points to "https://docs.microsoft.com/en-us/azure/devops/repos/git/branch-policies?view=azure-devops")

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ffebdc8-521c-44b5-cde4-4abdc1bd6f18
* Version Independent ID: dc0effda-6d93-62aa-64c5-4e6f283b0826
* Content: [Predefined variables - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml#feedback)
* Content Source: [docs/pipelines/build/variables.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/build/variables.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by msebolt** [comment]
Documentation updated.

**Comment by rguthriemsft** [comment]
As of today this is still broken.  The links still point to branch-policies.md
