### ISSUE TITLE
vsts-npm-auth with on-premise feed

### ISSUE THREAD

**Issue by adraut** [MicrosoftDocs/vsts-docs#5587]
In the section 'Set up authentication on your dev box' it has a line that states the following:
&gt;`vsts-npm-auth` is not supported on TFS.
Does that mean `vsts-npm-auth` should work on Azure Devops Server 2019 or is the documentation just out of date and it still does not work with an on-premise server's feed?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cb7c2ab6-4ba1-51d5-96bb-38a9ab6b50c3
* Version Independent ID: 415de875-ba1b-476b-f08b-1a61dc7a2747
* Content: [Set up your client's npmrc](https://docs.microsoft.com/en-us/azure/devops/artifacts/npm/npmrc?view=azure-devops-2019&tabs=windows#feedback)
* Content Source: [docs/artifacts/npm/npmrc.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/artifacts/npm/npmrc.md)
* Product: **devops**
* Technology: **devops-artifacts**
* GitHub Login: @chasewilson
* Microsoft Alias: **phwilson**

**Comment by chasewilson** [comment]
@adraut Thanks for the question! I believe there is a differentiation between TFS and Azure DevOps Server and it should work with the latest version of AzureDevOps Server. @elbatk can you confirm this?

**Comment by elbatk** [comment]
Today, `vsts-npm-auth` doesn't work on-prem at all, the docs should read "TFS or Azure DevOps Server".

**Comment by chasewilson** [comment]
Great! I'll be updating the doc and you should see the update live within 24 hours! Thanks again @adraut
