### ISSUE TITLE
Mention "Azure DevOps Office Integration" component

### ISSUE THREAD

**Issue by flcdrg** [MicrosoftDocs/vsts-docs#5589]
I think it would be helpful to mention that you should check to make sure the "Azure DevOps Office Integration" component has been selected in the Visual Studio Installer.

eg.

![image](https://user-images.githubusercontent.com/384747/64829419-680a4a80-d60b-11e9-97b2-f02fad119689.png)

Once I made this change, then I was able to see the Teams menu in Excel and use the addin

**Comment by msebolt** [comment]
@flcdrg Thank you for the feedback.  Assigning to the author.

@chcomley Please refer to https://docs.microsoft.com/en-us/azure/devops/user-guide/tools?view=azure-devops.

**Comment by chcomley** [comment]
I've published an update and linked the PR to this issue! Please let us know whether you have any further feedback on this. Thank you!
