### ISSUE TITLE
Friendly version

### ISSUE THREAD

**Issue by f00-beerd** [MicrosoftDocs/vsts-docs#559]
[Enter feedback here]
The _home/About page should include the friendly version name.
This will avoid some confusion: e.g. 15.117.27024 isn't 2015, it's 2017. And, this will eliminate needing to google/bing around to find the version mapping to determine if you have Update 1, 2, etc.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 486447a6-a627-df82-4706-2318135540cc
* Version Independent ID: 7d6953c7-9ee6-50d6-9fce-238a4539ecc9
* Content: [Get support, provide feedback - VSTS & TFS](https://docs.microsoft.com/en-us/vsts/user-guide/provide-feedback?view=vsts)
* Content Source: [docs/user-guide/provide-feedback.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/user-guide/provide-feedback.md)
* Service: **unspecified**
* GitHub Login: @erickson-doug
* Microsoft Alias: **douge**

**Comment by chcomley** [comment]
@f00-beerd Thanks so much for your input! I've bolded the TFS versions, so they stand out for better clarity. This update should be live sometime this afternoon.
