### ISSUE TITLE
Manual approval in Yaml pipeline

### ISSUE THREAD

**Issue by jeremyklamer** [MicrosoftDocs/vsts-docs#5590]
Please add comments about Manual approval in Yaml pipeline. Also if its not possible it would be nice to state it here. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b067a175-f640-7503-9c1e-f0130c6dbeda
* Version Independent ID: ff743c7b-a103-eae6-4478-62ba995a4b36
* Content: [Pipeline deployment approvals - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/approvals?view=azure-devops)
* Content Source: [docs/pipelines/process/approvals.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/approvals.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @shashankbansal
* Microsoft Alias: **shashban**

**Comment by shashban** [comment]
@jeremyklamer By comments I believe you are talking about ability to provide comments when completing an approval. This support already exists in the platform.
![image](https://user-images.githubusercontent.com/16793896/65414305-0919b200-de11-11e9-9458-65c98944fdbb.png)

**Comment by jeremyklamer** [comment]
Wauw I never expected a response! What I actually meant was manual approval
before a stage in a yaml pipeline. Later I saw thst the article already
covered this subject and I just read over it.

Thanks a lot for the response though! That's amazing.

**Comment by Joramtech** [comment]
Approved
