### ISSUE TITLE
Team Feature in 2019

### ISSUE THREAD

**Issue by roby70** [MicrosoftDocs/vsts-docs#5591]
Please update current page with a warning about version requirements for group support.  
Something like "for availability of this feature check Features Timeline" (view response in closed item "@mentions to group") after "You can also use group mentions. Enter the name of a team or a security group, choose the search icon, and then select from the options listed.".
It can save a lot of time for people trying to use this feature.
Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 34ae521f-6ae4-4d7f-2cce-f844e5811b66
* Version Independent ID: 18098490-1f34-e966-3135-cb90197bfa6f
* Content: [Use @mentions in work items and pull requests - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/notifications/at-mentions?view=azure-devops#feedback)
* Content Source: [docs/notifications/at-mentions.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/notifications/at-mentions.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Thanks for your suggestion, @roby70, we'll look into this and be in touch. Have a great weekend!

**Comment by chcomley** [comment]
Hi @roby70, I've updated the article, by adding a note, which will go live today. Thanks so much for your feedback!
