### ISSUE TITLE
28 days not 30

### ISSUE THREAD

**Issue by ctahok** [MicrosoftDocs/vsts-docs#5595]
All the documents says 30 days but the products prompts 28 days. All the document where is says 30 needs to be changes to 28.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c8815945-eaa1-16e7-6ccd-ce4b5f8f8682
* Version Independent ID: 2eda53db-eaf1-e6d0-eacc-fa4507e0cb03
* Content: [Delete or remove an organization - Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/delete-your-organization?view=azure-devops)
* Content Source: [docs/organizations/accounts/delete-your-organization.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/accounts/delete-your-organization.md)
* Product: **devops**
* Technology: **devops-accounts**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by WilliamAntonRohm** [comment]
See also related issue #5596

**Comment by chcomley** [comment]
Thank you, @ctahok, I've completed the updates, which should be live within the next few hours. Thanks so much for helping our docs stay consistent and accurate! Have a lovely weekend.

**Comment by msebolt** [comment]
This is still unpublished.
