### ISSUE TITLE
Is Azure DevOps SERVER also free for the first 5 users for commercial use?

### ISSUE THREAD

**Issue by gojanpaolo** [MicrosoftDocs/vsts-docs#5598]
Is Azure DevOps SERVER also free for the first 5 users for commercial use?
Thanks! :)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 53803b6d-5089-79d1-34f3-c708c088d42d
* Version Independent ID: b4b0d600-3fe6-ecc1-5abf-ddc1c7bc6c48
* Content: [Billing articles - Azure DevOps - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/billing/?toc=%2Fazure%2Fdevops%2Fbilling%2Ftoc.json&bc=%2Fazure%2Fdevops%2Fbilling%2Fbreadcrumb%2Ftoc.json&view=azure-devops)
* Content Source: [docs/organizations/billing/index.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/billing/index.md)
* Product: **devops**
* Technology: **devops-billing**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @gojanpaolo, Thanks for posting your question. I'm double-checking with the team, so I'll be in touch as soon as possible. Have a great weekend!

**Comment by gojanpaolo** [comment]
@chcomley Thank you for the immediate response. Have a good one! :)

**Comment by chcomley** [comment]
I @gojanpaolo, I can confirm that Azure DevOps Server is NOT free for the first 5 users. Here's a link to the info, as well: https://docs.microsoft.com/en-us/azure/devops/organizations/billing/buy-access-tfs-test-hub?view=azure-devops-2019. 
Thanks for your patience while I confirmed this! Have a wonderful day.

**Comment by chcomley** [comment]
Please let us know if you have any further questions, @gojanpaolo.

**Comment by gojanpaolo** [comment]
@chcomley Could you please quote where it is stated on the link? I can't seem to find it, or maybe I'm just blind 🤣

**Comment by gojanpaolo** [comment]
> For [Azure DevOps Server](https://visualstudio.microsoft.com/tfs/), you pay per user for [Basic](https://visualstudio.microsoft.com/team-services/compare-features/) features like Code or Agile Planning

...It says we pay per user for Basic features. but then the link to the Basic feature redirects us to this page

![image](https://user-images.githubusercontent.com/16026608/65076126-f3624380-d95d-11e9-9b4b-3cd0e14bfb8a.png)


---

...The Azure DevOps Server tab is the following

![image](https://user-images.githubusercontent.com/16026608/65076205-2573a580-d95e-11e9-90a1-983825fb5fa7.png)


...The "Basic Plan license" link goes to the Azure DevOps Services page previously shown, which shows its free for 5 users
