### ISSUE TITLE
includeAssignedRequest and includeCapabilities return properties

### ISSUE THREAD

**Issue by patware** [MicrosoftDocs/vsts-docs#5600]
Hi gang,

The doc for Agents - List (https://docs.microsoft.com/en-us/rest/api/azure/devops/distributedtask/agents/list?view=azure-devops-rest-5.1) shows that we can specify in the query string the includeCapabilities, includeAssignedRequest, includeLastCompletedRequest, but it's not clear what this adds to the result, or where to look for in the result.

The URI Parameter Description could include an indicator that "if the agent is currently running a job, the assignedRequest (link) will contain a TaskAgent object

Lower, in the TaskAgent, in the description, include a hint "empty unless the argument includeAssignedRequest is specified in the query".  

If the agent is idle, there's no assignedRequest property, so by simply looking at the result object, it's impossible to know unless reading the doc.  

Also, in the includeLastCompletedRequest, indicate that the property will not appear if the agent has never run any job/task.

tx, Pat

**Comment by msebolt** [comment]
@patware  Thank you for the feedback, assigning to the author.

@wnjenkin The closest [parent article](https://docs.microsoft.com/en-us/rest/api/azure/devops/distributedtask/?view=azure-devops-rest-5.1) is assigned to you.  Do you know the author responsible for this?

**Comment by wnjenkin** [comment]
I would start with @vtbassmatt

**Comment by vtbassmatt** [comment]
`includeCapabilities` adds `systemCapabilities` and `userCapabilities` properties to the response. `includeLastCompletedRequest` adds a `lastCompletedRequest` property (unless, as you point out, the agent has never serviced a request).

We have this pattern all over the place (properties that don't show up until you request them). While I don't love it, I think it's pretty easy to discover.
