### ISSUE TITLE
Screenshots are outdated

### ISSUE THREAD

**Issue by clisc** [MicrosoftDocs/vsts-docs#5601]
Please see https://developercommunity.visualstudio.com/content/problem/733283/cannot-disable-preview-features.html

The screenshots are out of date which led me to believe I was unable to disable "Preview Features" because it wasn't showing up in the menu.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b4f95345-6686-8e29-ff3f-cbea4a6eb24d
* Version Independent ID: 695d975e-ea9b-139b-4f98-f9655a751f59
* Content: [Turn preview features on or off - Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/project/navigation/preview-features?view=azure-devops)
* Content Source: [docs/project/navigation/preview-features.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/project/navigation/preview-features.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
Closing this issue. Question has been addressed in Developer Community link.
