### ISSUE TITLE
The screenshot still says 30 days

### ISSUE THREAD

**Issue by ctahok** [MicrosoftDocs/vsts-docs#5609]
Please update the screenshot to reflect 28 days too. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c8815945-eaa1-16e7-6ccd-ce4b5f8f8682
* Version Independent ID: 2eda53db-eaf1-e6d0-eacc-fa4507e0cb03
* Content: [Delete or remove an organization - Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/delete-your-organization?view=azure-devops#feedback)
* Content Source: [docs/organizations/accounts/delete-your-organization.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/accounts/delete-your-organization.md)
* Product: **devops**
* Technology: **devops-accounts**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by msebolt** [comment]
Refer to https://github.com/MicrosoftDocs/vsts-docs/issues/5595.

**Comment by msebolt** [comment]
@ctahok  Thank you for the feedback.  

The change has been added to the private repo and is currently still awaiting publish, see issue above for further details.
