### ISSUE TITLE
Still incomplete?

### ISSUE THREAD

**Issue by gjbdebug** [MicrosoftDocs/vsts-docs#5612]
tcpdump on the target during a DevOps deploy revealed src IP 13.90.207.71.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc5a4cfa-aa84-9f0f-55f4-71ec4861c070
* Version Independent ID: d621620a-c924-03b1-8b43-f99c33e58bb8
* Content: [Add IP addresses and URLs to allow list - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/security/allow-list-ip-url?view=azure-devops#feedback)
* Content Source: [docs/organizations/security/allow-list-ip-url.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/security/allow-list-ip-url.md)
* Product: **devops**
* Technology: **devops-whitepapers**
* GitHub Login: @chcomley
* Microsoft Alias: **jominana**

**Comment by congyiwu** [comment]
By "Still incomplete", are you referring to !5460?
If so, https://docs.microsoft.com/en-us/azure/devops/organizations/security/allow-list-ip-url?view=azure-devops currently says: 
> If you need to connect to Git repositories on Azure DevOps with SSH, you need to allow requests to port 22 for the following:
> ssh.dev.azure.com
> ssh.visualstudio.com
> All IP addresses in the "name": "AzureCloud" section of [this file](https://www.microsoft.com/en-us/download/details.aspx?id=56519) (updated weekly): Azure IP ranges and Service Tags - Public Cloud.

The "AzureCloud" section of the linked file includes "13.90.0.0/16".  That block includes all addresses from 13.90.0.0-13.90.255.255., which includes the address you mentioned (13.90.207.71).

**Comment by gjbdebug** [comment]
Thank you for the response, and I probably should have been more clear about my context. It is not connecting to Git repos on DevOps with SSH, but rather using the "Copy files over SSH" DevOps deploy task. Only after I temporarily allowed "any" and captured the target's traffic during the SSH deploy (which finally succeeded) did I identify the source as 13.90.207.71.

**Comment by congyiwu** [comment]
Your asking about the IP address ranges for Microsoft-hosted Windows and Linux Pipelines agents, right 🤞?  If so, that's documented in the "Agent IP ranges" section of the "Microsoft-hosted agents" page:
https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops#agent-ip-ranges

Although that page could be a bit clearer that `"name": "AzureCloud.*"` (e.g. `"name": "AzureCloud.eastus"`) sections are ones you need to use.

Note that in practice, the IP address ranges for all hosted Pipelines agents matches the range for SSH Git access, but for hosted Pipelines agents.  The only difference is that for hosted Pipelines agents, you can narrow down the ranges by geography based on where your account is hosted.

@chcomley should we add a section right above the "Hosted Mac agents" section, called "Hosted Windows and Linux agents", that links to "Agent IP ranges" section of the "Microsoft-hosted agents" page?  That way all firewall related stuff would be discoverable from a single page.

**Comment by gjbdebug** [comment]
@congyiwu Yes, and now things are coming into focus. At https://docs.microsoft.com/en-us/azure/devops/organizations/security/allow-list-ip-url?view=azure-devops, I read past the “…connectivity from a user’s machine to Azure DevOps” (outbound) in the second paragraph and assumed the ranges under “Azure DevOps IP addresses” were inbound for hosted agent access to the deploy target (my bad and it did seem strange that there would be relatively few IPs if that was the case…). Regardless, personally I agree with your suggestion about adding https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops#agent-ip-ranges to the doc and for the reason you provided.
