### ISSUE TITLE
Code blocks are not formatted/structured well

### ISSUE THREAD

**Issue by Styxxy** [MicrosoftDocs/vsts-docs#5613]
The code blocks on this page are not formatted or structured well. I think it is for creating two tabs to offer two ways of doing (REST vs Client Libraries).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b65bc8c-1899-503d-b447-7d27624963c4
* Version Independent ID: 147aa3ca-aef0-9180-53ea-56c6f20a2f88
* Content: [Work Item Tracking Samples](https://docs.microsoft.com/en-us/azure/devops/integrate/previous-apis/wit/samples?view=azure-devops-2019)
* Content Source: [docs/integrate/previous-apis/wit/samples.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/integrate/previous-apis/wit/samples.md)
* Product: **devops**
* Technology: **devops-ecosystem**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @Styxxy, Thanks for your suggestion, I agree. I've created a user story on my backlog to address this. Thanks!

**Comment by chcomley** [comment]
Hi @Styxxy, This article is super old and should be archived at some point. I've added a note to the article, which states the following. 
Looking for Azure DevOps REST APIs? See the newest [Azure DevOps REST API reference](https://docs.microsoft.com/en-us/rest/api/azure/devops/?view=azure-devops-rest-5.1).
> api-version = 5.1
>  
> For information about .NET client libraries, see [.NET client libraries for Azure DevOps (and TFS)](../integrate/concepts/dotnet-client-libraries.md).

Please @mention me if these links don't provide the necessary information.

Thank you!
