### ISSUE TITLE
error when trying to disconnect

### ISSUE THREAD

**Issue by Ballzer0** [MicrosoftDocs/vsts-docs#5615]
after i write my tennant name and click disconnect i get an error like this
'''
System.Data.SqlClient.SqlError: %error="400101";%:spsprodweu4.Sps_spsprodweu4_d04f48ed-487c-464b-a264-9baf839608ae..prc_UpdateIdentityIdTranslations: new translations have a record that may corrupt the existing translation data
'''
it doesnt seem like anyone is experiencing the same issue. We want to move our organization from our test tennant to the production tennant

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 98f0caaf-2697-c506-339b-2dea64233e48
* Version Independent ID: 7cd2ea02-2079-85d0-09e0-a90af59937d9
* Content: [Change connection to Azure AD - Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/change-azure-ad-connection?view=azure-devops#feedback)
* Content Source: [docs/organizations/accounts/change-azure-ad-connection.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/accounts/change-azure-ad-connection.md)
* Product: **devops**
* Technology: **devops-accounts**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @Ballzer0, I'm sorry to hear you're getting an error. Since this isn't a documentation issue, please contact [Support](https://visualstudio.microsoft.com/vs/support/#talktous) and they'll help you further. Thanks for reaching out.
