### ISSUE TITLE
Managing PATs via REST API

### ISSUE THREAD

**Issue by coxcs1** [MicrosoftDocs/vsts-docs#5616]
Hi,
Is it possible to manage PATs via the REST API? The documentation here is not easily readable - https://docs.microsoft.com/en-us/rest/api/azure/devops/tokenadmin/personal%20access%20tokens/list?view=azure-devops-rest-5.1

I need to be able to refresh access tokens via some automated job rather than having the tokens expire and manually refreshing them via user interface.
Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 53f99d2d-363b-d01d-039d-4fdc636fa2df
* Version Independent ID: f47330d5-e2de-36a4-e5b3-5bc77505b161
* Content: [Authenticate with personal access tokens - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/integrate/get-started/authentication/pats?view=azure-devops#q--a)
* Content Source: [docs/integrate/get-started/authentication/PATs.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/integrate/get-started/authentication/PATs.md)
* Product: **devops**
* Technology: **devops-ecosystem**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by coxcs1** [comment]
I need to be able to auto-refresh PAT tokens so CI/CD jobs can run without having to manually refresh tokens each year.

**Comment by chcomley** [comment]
Hi @coxcs1, I'm glad you reached out. We don't have an API support for this. You'll have to manually refresh the PAT each year. We do send you an expiry notification 7 days before the expiry of a PAT. If you're interested in submitting a feature request, you can do so [here](https://developercommunity.visualstudio.com/spaces/8/index.html). Thank you!

**Comment by coxcs1** [comment]
Hello @chcomley,
If there another form of authentication that does have this feature, which I can use with Azure DevOps Services?

Thank you.

**Comment by chcomley** [comment]
Hi @coxcs1, Unfortunately, No. You could try using SSH key auth (depending on your scenario), since that doesn’t have an expiry for the SSH key, you would theoretically never have to refresh the key. But in general, that’s not a good security practice to not rotate a key. Trying to automate PAT generation or extending expiry of a PAT also falls outside of security best practices. 

Thank you.

**Comment by coxcs1** [comment]
@chcomley I would prefer to follow best security practices. Is there any plans to support service principles via Azure KeyVault wiht Azure DevOps Services API?

Thanks.

**Comment by chcomley** [comment]
Hi @coxcs1, There are no plans to support Service Principals, either.

**Comment by logicfox** [comment]
This is a very annoying limitation. Having CI/CD pipelines fail because of expired tokens could be classified as an unacceptable limitation. Will the team at least consider OAuth token or JWT auth? I can always pass a JWT as a password that can easily be verified.

**Comment by chcomley** [comment]
Hi @logicfox, I recommend submitting a feature request. You can do so [here](https://visualstudio.microsoft.com/vs/support/#talktous). We thank you for your input.

**Comment by DigitalTargit** [comment]
What you might be able to do is put the PAT in a secure file ... and then tie the uid of the secure file to a library variable and then access the library variable in your pipeline yml.
