### ISSUE TITLE
Is there a limit to the number of build pipelines allowed for an Azure Project

### ISSUE THREAD

**Issue by raisingcode** [MicrosoftDocs/vsts-docs#5620]
Using essentially free version of Azure DevOps right now in place of Jenkins. Feedback we want to understand is if there is/or is not a finite number of Azure Pipelines that can be created. I'm assuming running all the pipelines at the same time would be a question of the how many parallel jobs licenses our project has.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7336a04e-5b38-d02f-8bba-a55445b2f094
* Version Independent ID: 783c30b3-63b6-da7c-1336-b000bb8b4c66
* Content: [Create your first pipeline - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/create-first-pipeline?view=azure-devops&tabs=tfs-2018-2)
* Content Source: [docs/pipelines/create-first-pipeline.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/create-first-pipeline.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by azureDaveOps** [comment]
There is not a limit on how many pipelines you may define.  You are correct, there is a limit on how many pipelines you can concurrently execute, and that is tied to your licensing.

**Comment by steved0x** [comment]
@azureDaveOps Thank you for chiming in with the answer, @raisingcode in case you didn't see it already.
