### ISSUE TITLE
how to remove project administrator?

### ISSUE THREAD

**Issue by anarchitect** [MicrosoftDocs/vsts-docs#5624]
After adding a couple of project administrators, via Project Settings -&gt; General -&gt; Overview -&gt; Project Administrators.  I found no way of removing them from Project Administrator.  Can you please advise how to do this or fix it as a priority? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e56e5bfa-e2ea-c309-8487-3ba3236ee6ee
* Version Independent ID: 981fdeed-0f98-135c-effb-2446cff74ea9
* Content: [Add a team administrator - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/settings/add-team-administrator?view=azure-devops#feedback)
* Content Source: [docs/organizations/settings/add-team-administrator.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/settings/add-team-administrator.md)
* Product: **devops**
* Technology: **devops-settings**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@anarchitect - Thank you for your inquiry.  You can remove a member of group by going to the Members tab for that group. However over the actions icon and then choose Remove.  I will add these instructions to the Admin topic for Project Administrators. 

![image](https://user-images.githubusercontent.com/10856840/65073970-ba6ba400-d948-11e9-99b8-3bf5752194d0.png)

**Comment by sschuberth** [comment]
I cannot seem to find a group called "Project Administrators", in fact I do not see "Groups" at all. And neither are "Project Administrators" part of "Teams".

**Comment by KathrynEE** [comment]
@sschuberth - Please follow the instructions provided in this article: [Set permissions at the project- or collection-level](https://docs.microsoft.com/en-us/azure/devops/organizations/security/set-project-collection-level-permissions?view=azure-devops&tabs=preview-page#remove-a-user-or-a-group).  You need to go to **Project Settings>Permissions** to see the Groups.
