### ISSUE TITLE
Expecting DateTime value | Changed Date Format Wrong?

### ISSUE THREAD

**Issue by spottedmahn** [MicrosoftDocs/vsts-docs#563]
According to [this example](https://docs.microsoft.com/en-us/vsts/work/track/query-by-date-or-current-iteration?view=vsts#query-for-items-based-on-when-changes-occurred)

![image](https://user-images.githubusercontent.com/14079228/38867289-94318540-4211-11e8-9e15-eeccff308139.png)

but I get

>Expecting DateTime value. The error is caused by 4/17/2018.

![image](https://user-images.githubusercontent.com/14079228/38867315-af778836-4211-11e8-992b-f17feda0290f.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f98abc5c-97e7-e8c9-4f3e-d9c82065c574
* Version Independent ID: 77606a2d-92fd-cecd-6b0c-5d86cabb61b2
* Content: [Query by date or current iteration - VSTS & TFS](https://docs.microsoft.com/en-us/vsts/work/track/query-by-date-or-current-iteration?view=vsts)
* Content Source: [docs/work/track/query-by-date-or-current-iteration.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/work/track/query-by-date-or-current-iteration.md)
* Service: **unspecified**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@spottedmahn - Thank you for your inquiry. I don't see anything wrong with your date format. I suggest refreshing your browser and trying again. If you still have a problem, please let the product team know by filing an issue here: https://developercommunity.visualstudio.com/spaces/21/index.html.

**Comment by spottedmahn** [comment]
Ok, thanks @KathrynEE.  I've opened a [Dev Community Issue](https://developercommunity.visualstudio.com/content/problem/238823/expecting-datetime-value-changed-date-format-wrong.html).

**Comment by spottedmahn** [comment]
[I learned](https://developercommunity.visualstudio.com/content/problem/238823/expecting-datetime-value-changed-date-format-wrong.html) the issue was my user preference data format has to be in sync.

Since my user preference was yyyy-MM-dd, my query needed to be yyyy-MM-dd.

---

I don't see anything in [this doc page](https://docs.microsoft.com/en-us/vsts/work/track/query-by-date-or-current-iteration?view=vsts) talking about that, maybe I'm missing it?
