### ISSUE TITLE
The screenshots are outdated I believe - No Security Policies on that screen

### ISSUE THREAD

**Issue by alvipeo** [MicrosoftDocs/vsts-docs#5634]
I wanted to enable MFA for AzureDevOps but I see no "Security policies" on that screen. And my org is connected to Azure AD (where I have Conditional Access enabled).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 24bd6400-4207-6f85-8a4e-5c9b0cc99cff
* Version Independent ID: 0b018039-29d1-431a-1be9-4b46af7f084f
* Content: [Manage Conditional Access policies - Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/manage-conditional-access?view=azure-devops&viewFallbackFrom=vsts)
* Content Source: [docs/organizations/accounts/manage-conditional-access.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/accounts/manage-conditional-access.md)
* Product: **devops**
* Technology: **devops-accounts**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @alvipeo, Could you please go to the **Azure Active Directory tab** in **Organization settings** and verify that your connection to Azure AD is OK? If it is indeed connected, then you'll need to contact [Support](https://visualstudio.microsoft.com/vs/support/#talktous), so they can help investigate the issue. Thank you!

**Comment by alvipeo** [comment]
ok, yeah, it needed some time to show up!
