### ISSUE TITLE
Azure Pipelines/TFS repo branch policy navigation inconsistent with docs.

### ISSUE THREAD

**Issue by peterlanoie** [MicrosoftDocs/vsts-docs#5635]
Doc title: `Build multiple branches`
Doc URL: https://docs.microsoft.com/en-us/azure/devops/pipelines/build/ci-build-git?view=azure-devops-2019&tabs=classic#azure-pipelines-or-tfs-repository
Doc section: `Validate pull requests` > `Azure Pipelines or TFS repository section`

The documented steps don't match up with the current UI in on-prem Azure DevOps Server 2019. I started to author a change but then realized that there are all those conditionals (monikers and such) that drive the docs based on the ADO/TFS version and don't know if there are differences between the UI based on those variations.
It's a minor correction:

Step 3: The ellipsis next to the branch name only has the `Lock Branch` option. This step should be changed to direct the user to the `Branch Policies` link under the `Security for master branch in {repo name}` title.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a55e404e-010b-32e5-30e0-71a2663a4f89
* Version Independent ID: e011575a-691c-af48-2268-1959c9f3020b
* Content: [Building multiple branches - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/ci-build-git?view=azure-devops-2019&tabs=classic#azure-pipelines-or-tfs-repository)
* Content Source: [docs/pipelines/build/ci-build-git.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/build/ci-build-git.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by WilliamAntonRohm** [comment]
@steved0x -- Steve, please review the changes in the above-mentioned PR 79.

**Comment by steved0x** [comment]
@peterlanoie Thank you for your feedback. On Azure Devops Server 2019, the Branch menu hasn't changed in the areas of branch policies, it looks like this. Does yours look different? Even if your user account doesn't have the permission to change the branch policies, you can typically still see the menu item for branch policies, click it, and view the policies.

Based on the screenshot I just took, it matches the steps for Step 3: You will implement a branch policy to protect the master branch. Select the ellipsis to the right of your branch name and Select Branch policies.

What does yours show?

![image](https://user-images.githubusercontent.com/1580889/65355372-c4e3a300-dbbf-11e9-8560-757fed0c9a25.png)

**Comment by peterlanoie** [comment]
I see what the confusion was. In Azure DevOps Server 2019, the `Code` hub is now `Repos`. When I couldn't find `Code` in the hubs list, I went to `Project Settings` > `Code` > `Repositories` and then the branches under a repo. That's where the `...` menu for the branch only shows `Lock Branch`. The `Project Settings` > `Code` > `Policies` section has a note and screenshot directing us to the area you have in your screenshot, so that definitely aligns with the docs.

I do have what you have in the screenshot when in the `Repos` > `Branches` area. So the docs are mostly correct except for the `Code` vs. `Repos` labeling in step 1.

**Comment by WilliamAntonRohm** [comment]
I've updated https://github.com/MicrosoftDocs/azure-devops-docs-pr/pull/79 to reflect only that change (Code is now Repos).
