### ISSUE TITLE
Limit to Cumulative Flow Diagram rolling report period to 180 days, documentation

### ISSUE THREAD

**Issue by jstallm** [MicrosoftDocs/vsts-docs#5637]
Document limit to rolling period for **Cumulative Flow Diagram**

Appears as if the limit to report is 180 days. Is this documented anywhere?
I believe a logical place to document might be 
https://docs.microsoft.com/en-us/azure/devops/report/dashboards/cumulative-flow-cycle-lead-time-guidance?view=azure-devops

Screenshot below of report ran today, showing limit of 180. 
![rolling period constaint](https://user-images.githubusercontent.com/6054668/65071237-2cd98580-d943-11e9-9999-555091b69365.png)

**Comment by msebolt** [comment]
@jstallm Thank you for the feedback, assigning to the author.

**Comment by KathrynEE** [comment]
@jstallm - Thank you for the feedback. I will update the topic to note the limit. The limits are between 14 and 180 days.
