### ISSUE TITLE
Broken link: "supported languages" under heading "Code highlighting"

### ISSUE THREAD

**Issue by bradleyscollins** [MicrosoftDocs/vsts-docs#5638]
The "supported languages" link points to the following:

http://highlightjs.readthedocs.io/en/latest/css-classes-reference.html#language-names-and-aliases

That page does not produce a list of languages, but rather some CSS class reference.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fa622358-f5bb-1f5c-177a-081a37b6acef
* Version Independent ID: 72f7fd16-a822-66c8-3a34-8905645ce5f2
* Content: [Markdown syntax for files, widgets, and wikis in Azure DevOps - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/project/wiki/markdown-guidance?view=azure-devops#code-highlighting)
* Content Source: [docs/project/wiki/markdown-guidance.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/project/wiki/markdown-guidance.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
@bradleyscollins, I've just published a replacement for this link, which should be live sometime today. In the meantime, please go here: https://github.com/highlightjs/highlight.js/tree/9.10.0/src/languages. Thanks so much for reaching out!

**Comment by bradleyscollins** [comment]
Thanks a ton!
