### ISSUE TITLE
Feature Request: Add Verbose setting to the task

### ISSUE THREAD

**Issue by AakashMasand** [MicrosoftDocs/vsts-docs#5641]
The Powershell command New-AzResourceGroupDeployment has a -Verbose argument which gives us more information as to what resource is provisioning, what resource deployment has succeeded, etc. This is very helpful when debugging a deployment failure that might occur during the Azure Resource Group deployment task.

Would love tp have something like that with the Azure Resource Group Deployment task.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a59ea95e-b51a-e529-37a8-215e383c9a0b
* Version Independent ID: f1afdb0e-f090-3193-9bb8-ce5952016768
* Content: [Azure Resource Group Deployment task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-resource-group-deployment?view=azure-devops)
* Content Source: [docs/pipelines/tasks/deploy/azure-resource-group-deployment.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/deploy/azure-resource-group-deployment.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by chasewilson** [comment]
@AakashMasand this is not a doc bug, I'll be closing this issue. please reach out to the [Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html) or on the [Task GitHub Repo](https://github.com/microsoft/azure-pipelines-tasks) for this request
