### ISSUE TITLE
adjust activity drop-down

### ISSUE THREAD

**Issue by brujah6** [MicrosoftDocs/vsts-docs#5643]
hi
is it possible to adjust / add the fields of the activity drop-down
please consider if this is not possible

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de93c4e5-f491-af61-6df5-e7253d727dc9
* Version Independent ID: 417246fa-90ed-38a0-cc68-1de7895e96ce
* Content: [Set sprint capacity - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/sprints/set-capacity?view=azure-devops#feedback)
* Content Source: [docs/boards/sprints/set-capacity.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/boards/sprints/set-capacity.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@brujah6 - Thank you for your inquiry. Previously for the cloud hosted service, you couldn't change the Activity or Discipline pick list. However, with a recent update, you can by modifying an inherited process. See {Customize system picklist values}(https://docs.microsoft.com/en-us/azure/devops/release-notes/2019/sprint-156-update#customize-system-picklist-values). I will update the topic to clarify this new capability. 

![image](https://user-images.githubusercontent.com/10856840/65281536-b0cc7280-dae7-11e9-86e5-16a1983a7241.png)

**Comment by rathishrms** [comment]
this customization does not appear in Capacity. Any thoughts?
