### ISSUE TITLE
Does yaml have to define Output Variables

### ISSUE THREAD

**Issue by StefanSchoof** [MicrosoftDocs/vsts-docs#5644]
In GUI Pipelines there is a section named "Output Variables":
![grafik](https://user-images.githubusercontent.com/4662023/65123047-b5fbc580-d9f2-11e9-852f-0d618499e41b.png)

The "View YAML" seems not to export those values. But in this documentation is no note how to do it or that it is unsupported. I think this should added.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8098f527-ebdf-60d5-3989-5228b7a207c1
* Version Independent ID: ce27c817-9599-00ef-5af2-3ac1dbad8dc6
* Content: [Build and Release Tasks in Azure Pipelines and TFS - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/tasks?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/process/tasks.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/tasks.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by juliakm** [comment]
@StefanSchoof [Here]() is more information on [using output variables from tasks](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch#use-output-variables-from-tasks) in YAMLs. You may also find the reference to [setting a multi-job output variable](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch#set-a-multi-job-output-variable) helpful.
