### ISSUE TITLE
Different types of sample apps require seperate YAML build definitions

### ISSUE THREAD

**Issue by SanderHolvoet** [MicrosoftDocs/vsts-docs#5645]
The 4 different types of sample apps (Java / JavaScript / Python / .NET Core) each require a different *azure-pipelines.yml* build pipeline definition. 

Both the Docker build task and the *imageName* variable in the current build definition is specific to the JavaScript sample app as the Dockerfile path differs.

**JavaScript:**
```xaml
variables:
  imageName: 'pipelines-javascript-docker' # points to the JavaScript image

steps:
- task: Docker@2
  displayName: Build an image
  inputs:
    repository: $(imageName)
    command: build
    Dockerfile: app/Dockerfile # specific location of the Dockerfile
...
```

**The corresponding task for the .NET Core app:**
```xaml
variables:
  imageName: 'pipelines-dotnet-core-docker' # points to the .NET Core image

steps:
- task: Docker@2
  displayName: Build an image
  inputs:
    repository: $(imageName)
    command: build
    Dockerfile: Dockerfile # different location of the Dockerfile
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e825c07d-2168-c0aa-782a-ef6f9c7ba95e
* Version Independent ID: 5cb6926b-215a-bf89-8e63-b2e1129e41df
* Content: [Build an image - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/ecosystems/containers/build-image?view=azure-devops&tabs=dotnet-core#feedback)
* Content Source: [docs/pipelines/ecosystems/containers/build-image.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/ecosystems/containers/build-image.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @shashankbarsin
* Microsoft Alias: **shasb**

**Comment by msebolt** [comment]
@SanderHolvoet Thank you for the feedback.

Are you referring to the `Dockerfile`?  In that case, this could be the same depending on your setup, else you would need to use two variables, one for `$(imageName)` and one for `$(Dockerfile)`.

I think the idea here is that you can either create separate build definitions or use variables depending on your preference.

**Comment by SanderHolvoet** [comment]
@msebolt In the *Get the code* section, you're referring to 4 different types of sample repositories (Java, JavaScript, Python and .NET Core). In the *Create pipeline with build step* section (during step 4), we're told to setup the build pipeline by editing the azure-pipelines.yml file. However, the YAML snippet which is shown, is only meant to be used if you cloned the JavaScript repo in the previous step.

Minor issue obviously, but this might be a bit confusing. I would suggest using 4 separate tabs (similar to what is being done in the *Get the code* section), which each contain a separate build definition. Adding a `$(Dockerfile)` variable like you've mentioned might indeed highlight the fact that the Dockerfile will have a different location depending on the type of code which was cloned earlier:

- Java: `./complete/Dockerfile`
- JavaScript: `./app/Dockerfile`
- Python: `./Dockerfile`
- .NET Core: `./Dockerfile`

**Comment by msebolt** [comment]
@SanderHolvoet  Thank you for clarifying, assigning the author now.
