### ISSUE TITLE
Mermaid not available on Azure Dev Ops

### ISSUE THREAD

**Issue by artxe234** [MicrosoftDocs/vsts-docs#5646]
We're using the cloud version of Azure Dev Ops and would love to use the mermaid support on wiki pages.
Unfortunately the mermaid button is missing and the "::: mermaid" synthax is ignored.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 29f1e43f-a069-dd88-7fc7-9cc497fb94f0
* Version Independent ID: c261afa7-6eb7-b3f0-9f92-6d2f3c5ac336
* Content: [Markdown syntax for wikis in Azure DevOps - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/project/wiki/wiki-markdown-guidance?view=azure-devops#feedback)
* Content Source: [docs/project/wiki/wiki-markdown-guidance.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/project/wiki/wiki-markdown-guidance.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by msebolt** [comment]
@artxe234  Thank you for the feedback.

This feature is currently under development, please refer to this [Azure DevOps UserVoice feature listing](https://developercommunity.visualstudio.com/idea/365751/wiki-mermaid-plantuml-support.html).

**Comment by jamie-tillman** [comment]
Then, perhaps you should fix the documentation page, because the page that documents this feature is NOT in development.  It is live.  I just wasted 20 minutes trying to figure out why my project wiki doesn't support something the documentation says it does.

This is, after all, an issue report for the documentation, not the service itself.

**Comment by msebolt** [comment]
Please refer to https://github.com/MicrosoftDocs/vsts-docs/issues/5788.
