### ISSUE TITLE
Can Microsoft hosted Azure pipeline resolve private DNS domain

### ISSUE THREAD

**Issue by marc-bouvier** [MicrosoftDocs/vsts-docs#5648]
I have a sonarqube instance that is exposed in a private network in my organization.

Can a Microsoft hosted agent resolve this domain? Say https://sonarqube.myorg

Or should I prefer using self-hosted Azure devops pipeline agent?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 99af681d-41ad-da15-0b72-08b5cd5a11ac
* Version Independent ID: 2fa0df36-a437-8cbb-b019-b49b31b1e116
* Content: [Microsoft-hosted agents for Azure Pipelines - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops#feedback)
* Content Source: [docs/pipelines/agents/hosted.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/agents/hosted.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @thejoebourneidentity
* Microsoft Alias: **jobourne**

**Comment by thejoebourneidentity** [comment]
You should be able to resolve it, but you'll likely need to allow access to the Azure Datacenter IP ranges to allow access to your private network.
