### ISSUE TITLE
Example not working

### ISSUE THREAD

**Issue by ttermeer-reboundcg** [MicrosoftDocs/vsts-docs#565]
Using the last the example from the documentation, the following error is returned :
`TypeError: vstsGit.createPullRequestStatus is not a function`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e8f48d8a-33fb-9f6d-1db1-4cccb5b987d9
* Version Independent ID: 3e18fcbf-331d-9de2-62ae-c4e7c888cc48
* Content: [Create a pull request status server with Node.js](https://docs.microsoft.com/en-us/vsts/git/how-to/create-pr-status-server?toc=/vsts/integrate/toc.json&bc=/vsts/integrate/breadcrumb/toc.json&view=vsts)
* Content Source: [docs/git/how-to/create-pr-status-server.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/git/how-to/create-pr-status-server.md)
* Service: **unspecified**
* GitHub Login: @erickson-doug
* Microsoft Alias: **mmitrik**

**Comment by steved0x** [comment]
@ttermeer-reboundcg I'm checking into this, the [vso-node-api](https://www.npmjs.com/package/vso-node-api) package does have a [createPullRequestStatus](https://github.com/Microsoft/vsts-node-api/blob/master/api/GitApi.ts#L100) method and I have run this sample. Let me see if something has changed. Sorry for the delay in responding while we get familiar with the new doc feedback system.

**Comment by ttermeer-reboundcg** [comment]
@steved0x Yes it has. However the line
`var vstsGit = connection.getGitApi();` does not create a valid API object.
I am not sure if this the right way but I did the following to make the sample work
```
var vstsGit = null;
connection.getGitApi().then((api) => { vstsGit = api; }) 
```

**Comment by steved0x** [comment]
@ttermeer-reboundcg I'm updating the article to include your code - something did change at the lower level, possibly something in the async vs sync resolution) - this change should be live by tomorrow. Thank you.

**Comment by cajonemsft** [comment]
@steved0x I'm running through the [Create Pull Request Status Server](https://docs.microsoft.com/en-us/vsts/repos/git/create-pr-status-server?view=vsts) docs and running into the same issue.  I tried the above workaround but am still running into issues.  Is there another workaround here?
