### ISSUE TITLE
Feature Request : Approvals and Checks from Pipelines and Repos

### ISSUE THREAD

**Issue by Bjego** [MicrosoftDocs/vsts-docs#5650]
Hi, 
I'd like to see the approvals from signing off 

- PullRequests in Repos

- Checks in Pipelines

- Approvals in (classic) Releases

This would make it easy to see all sign offs for e.g. productional releases in one central place.

I think this could make the audit section even more helpful.

With best regards

**Comment by msebolt** [comment]
@Bjego  Thank you for the suggestions, please move this issue to the [Azure DevOps UserVoice](https://developercommunity.visualstudio.com/topics/Azure+DevOps.html).

There you can get direct feedback from the product team.

**Comment by Bjego** [comment]
@msebolt  I've moved it.
See it here : https://developercommunity.visualstudio.com/idea/739590/approvals-and-sign-offs-in-the-audit-log-or-anothe.html
