### ISSUE TITLE
No instructions for HA (fail-over or load-balancing)

### ISSUE THREAD

**Issue by TASlavens** [MicrosoftDocs/vsts-docs#5654]
Hello,

We have multiple AzDOS 2019u1 AT servers, so the indexer is installed on a separate VM, but currently we have only one of those.  I'm being asked to look into HA for the indexing, at least as hot fail-over with one server in each data center, if not fully load-balanced.  We're using F5 Big-IP, if that matters, but others will likely be using different products.

Would someone add detailed advice on how to configure multiple indexing servers in an HA configuration?  Thanks!

- Tom

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be0bdbf7-3132-9007-6c6a-368c5bcb0f3d
* Version Independent ID: 58118f61-f88f-24b9-b785-d8f9d8a1fefd
* Content: [Administer code, wiki and workitem search](https://docs.microsoft.com/en-us/azure/devops/project/search/administration?view=azure-devops#feedback)
* Content Source: [docs/project/search/administration.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/project/search/administration.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@TASlavens - I've reached out to the product team for instructions and will add more information as I receive it.

**Comment by TASlavens** [comment]
Hi, @KathrynEE - It has been nearly three months.  Could we have a status update on the AzDOS 2019u1 indexing HA question?  Thanks!

**Comment by KathrynEE** [comment]
@TASlavens - Apologies for the delay. I've reached out again to the product team and requested their support. I'll continue to drive this so it doesn't slip through the cracks again.

**Comment by ShubhamJain1992** [comment]
Hi @TASlavens ,
Apologies for missing out this request. Presently search service does not support high availability for indexing servers. (The reason why there is no documentation for that). We have an item to support HA in our backlog but it is less likely to be picked up right now. I request you to post this request in out community forum here https://developercommunity.visualstudio.com/content/idea/post.html?space=21 and you can track it when we prioritize.

Thanks,
Shubham Jain

**Comment by KathrynEE** [comment]
Closing the issue as it has been addressed.
