### ISSUE TITLE
pull request merge attempted trigger behaviour

### ISSUE THREAD

**Issue by dsahu1001** [MicrosoftDocs/vsts-docs#5656]
Kindly provide the usability and behavior of "pull request merge attempted"  trigger. It look like its not behaving how it's supposed to behave

**Comment by WilliamAntonRohm** [comment]
@dsahu1001 -- Thanks for your feedback; we appreciate it. To make sure we have all the information needed to triage your issue, please let us know which topic you’re referencing, or provide more context around the general task.

**Comment by dsahu1001** [comment]
I'm talking about the jenkins service hook in TFS git
