### ISSUE TITLE
Missing displayName property on deployment jobs

### ISSUE THREAD

**Issue by mbovo** [MicrosoftDocs/vsts-docs#5663]
Runing the example in page the result is failed with 
`Unexpected value 'displayName'"`

seems displayName is not available/the doc is not aligned with the code

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5aeeaace-1c5b-a51b-e41f-f25b806155b8
* Version Independent ID: fd7ff690-b2e4-41c7-a342-e528b911c6e1
* Content: [Deployment jobs - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/deployment-jobs?view=azure-devops#feedback)
* Content Source: [docs/pipelines/process/deployment-jobs.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/deployment-jobs.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by RoopeshNair** [comment]
Duplicate  of #5250

**Comment by RoopeshNair** [comment]
Raised PR #97

**Comment by juliakm** [comment]
Closing issue as the pull request was merged.
