### ISSUE TITLE
Update documentation to mention that "az devops extension commands now supports login done using az login"

### ISSUE THREAD

**Issue by RonakThakkar** [MicrosoftDocs/vsts-docs#5668]
If az login is already done, then there is no need to provide token as az devops commands now supports login already done using az login.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: af3bebb5-3c18-a905-67b7-a1c6bd4f4522
* Version Independent ID: d6c7802a-dfdf-9852-a51b-d2ba30be70fe
* Content: [Sign in with a Personal Access Token (PAT), Azure DevOps CLI - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/cli/log-in-via-pat?view=azure-devops&tabs=windows)
* Content Source: [docs/cli/log-in-via-pat.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/cli/log-in-via-pat.md)
* Product: **devops**
* Technology: **devops-ref**
* GitHub Login: @KathrynEE
* Microsoft Alias: **geverghe**

**Comment by KathrynEE** [comment]
@RonakThakkar - Thank you for the feedback. I will update the topic as advised.

**Comment by swapnild2111** [comment]
if I am doing `az login --service-principal ...`  should `az devops` work?
My az login worked with SP, but then I get below error -
```$az pipelines build list -o table
ERROR: Before you can run Azure DevOps commands, you need to run the login command(az login if using AAD/MSA identity else az devops login if using PAT token) to
setup credentials.  Please see https://aka.ms/azure-devops-cli-auth for more information.```
