### ISSUE TITLE
Does not include some error codes

### ISSUE THREAD

**Issue by rlvandaveer** [MicrosoftDocs/vsts-docs#5669]
This text is missing both TF400506 and TF400507. Examples:

[Error  @18:54:13.959] Step : ProcessValidation - Failure Type - Validation failed : Invalid process template: WorkItem Tracking\Process\ProcessConfiguration.xml:: The following element contains an error: BugWorkItems/BugWorkItems. TF400506: This element defines the states for work items that represent Bugs or Defects. Each state must exist in at least one of the work item types that are defined in: BugWorkItems. The following states do not exist in any of the work item types: New, Approved, Committed, Done.
[Error  @18:54:14.088] Step : ProcessValidation - Failure Type - Validation failed : Invalid process template: WorkItem Tracking\Process\ProcessConfiguration.xml:: The following element contains an error: BugWorkItems/BugWorkItems. TF400507: Each work item type must support an initial state value that matches one of the states defined in: BugWorkItems. The following work item types have initial states that do not include any states defined in the bug state configuration: Bug.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b5ecc59-b30a-cb41-aa6b-7ba24fb6fa2a
* Version Independent ID: f5b6f454-7b3b-79cf-ab86-2cf0f043a660
* Content: [Resolve validation errors - Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/organizations/settings/work/import-process/resolve-errors?view=azure-devops)
* Content Source: [docs/organizations/settings/work/import-process/resolve-errors.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/settings/work/import-process/resolve-errors.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@rlvandaveer - Thank you for the feedback, I will update the topic to address these validation errors.
