### ISSUE TITLE
Can't find project

### ISSUE THREAD

**Issue by magius96** [MicrosoftDocs/vsts-docs#567]
What do I do when Zapier doesn't see any projects, but it does see repositories and branches?  Where would I look to find the GUID of my project to manually enter it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 229dda3c-d750-fc3a-e626-e0695d47e884
* Version Independent ID: 0367b931-2282-0a33-6f4c-6f941c3efbf3
* Content: [Zapier with VSTS](https://docs.microsoft.com/en-us/vsts/service-hooks/services/zapier?view=vsts#feedback)
* Content Source: [docs/service-hooks/services/zapier.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/service-hooks/services/zapier.md)
* Service: **unspecified**
* GitHub Login: @erickson-doug
* Microsoft Alias: **elbatk**

**Comment by elbatk** [comment]
Assigning this to the product team to help you try to get this sorted out @magius96

**Comment by elbatk** [comment]
Hi @magius96 , I'm going to close this as a docs issue and suggest that you post to the [Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html) which is actively monitored by the product team. Best of luck!
