### ISSUE TITLE
Checkout other repos than self?

### ISSUE THREAD

**Issue by pollockm** [MicrosoftDocs/vsts-docs#5671]
The documentation only mentions how to checkout the repo that contains the YAML file.  This is the main use case.  It implies, however, that it is possible to checkout something other than self.  What does the syntax for this look like (example)?  If it is not possible to checkout something other than self, the documentation should say that.

checkout: self  # self represents the repo where the initial Pipelines YAML file was found

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7458d5b2-1bb7-7d87-7ce6-2b0c430b0155
* Version Independent ID: edf5bbd3-a3f0-5426-e985-31290f8afd05
* Content: [YAML schema - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema#checkout)
* Content Source: [docs/pipelines/yaml-schema.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/yaml-schema.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @vtbassmatt
* Microsoft Alias: **macoope**

**Comment by vtbassmatt** [comment]
Today we support `checkout: self` and `checkout: none`. In the future, it will be possible to checkout other repos.

**Comment by dotnetcanuck** [comment]
@pollockm Until support is added for checking out other repos, you can accomplish this with PowerShell.

https://stackoverflow.com/a/57810819/1371045
