### ISSUE TITLE
Duplicate field data type entry in table

### ISSUE THREAD

**Issue by zeusk** [MicrosoftDocs/vsts-docs#5678]
There is an identical duplicate entry for "string or Text field" in section "Query field data types and values".

> String or Text field (single line) | Short text string that can contain up to 255 Unicode characters. String text fields are often used to support picklists or drop-down menus.
> String or Text field (single line) | Short text string that can contain up to 255 Unicode characters. String text fields are often used to support picklists or drop-down menus.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a718268-1105-4def-5f9e-20ea21afc0d7
* Version Independent ID: 0f08fa18-3075-4275-22c7-d5d1c1e260b0
* Content: [Query fields, operators, and macros/variables - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/queries/query-operators-variables?view=azure-devops#feedback)
* Content Source: [docs/boards/queries/query-operators-variables.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/boards/queries/query-operators-variables.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by WilliamAntonRohm** [comment]
@zeusk -- Shantanu, thank you for your feedback & fix.

@KathrynEE -- Kathryn, please review the above-mentioned PR.

**Comment by KathrynEE** [comment]
@zeusk - Thank you for your contribution which has been merged.
