### ISSUE TITLE
Extra open bracket in markdown file

### ISSUE THREAD

**Issue by MorganW09** [MicrosoftDocs/vsts-docs#5688]
I noticed an extra open bracket on the following page.

https://docs.microsoft.com/en-us/azure/devops/project/wiki/wiki-markdown-guidance?view=azure-devops

On the bottom left of this image.
![image](https://user-images.githubusercontent.com/4063086/65357493-cb245000-dbbc-11e9-82c5-c8ca32571785.png)

Looking through the raw markdown 

```
> [![Tags for TOC](_img/toc_tags.png)
```
Should be
```
> ![Tags for TOC](_img/toc_tags.png)
```

Small issue, but I'd love to submit a PR to fix it.

**Comment by WilliamAntonRohm** [comment]
@MorganW09 -- thank you for finding and especially fixing this issue.
