### ISSUE TITLE
Update screenshots

### ISSUE THREAD

**Issue by loundy** [MicrosoftDocs/vsts-docs#5692]
Screenshots need updating for the new DevOps experience.

For example, the last screenshot showing "My Hub" is under "Repos &gt; My Hub"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 14955ee9-29f2-46fe-3a8d-a42666f53ffc
* Version Independent ID: 5d417cd0-a671-ee30-8fca-5f8b0addd328
* Content: [Develop a web extension for Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/extend/get-started/node?view=azure-devops#feedback)
* Content Source: [docs/extend/get-started/node.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/extend/get-started/node.md)
* Product: **devops**
* Technology: **devops-ecosystem**
* GitHub Login: @willsmythe
* Microsoft Alias: **wismythe**

**Comment by chcomley** [comment]
Hi @loundy, Thanks for your feedback. We'll be improving the extension docs in the near future (Q3, Q4), which will include updated screenshots. Thanks again.
