### ISSUE TITLE
The chapter "How SSH key authentication works" has wrong content

### ISSUE THREAD

**Issue by angel-p57** [MicrosoftDocs/vsts-docs#5696]
The content is based on misunderstanding.
1. Authentication keys are not for encryption/decryption. They are for signing/verifying the digital signature created through the authentication process.
2. Authentication keys have no effect on message encryption.  Even without authentication keys, e.g. even with password authentication, messages between server and client are encrypted.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 64e85ff9-9add-d15c-e92f-02d7dd05e0f2
* Version Independent ID: 0cbd7427-6acd-3cfc-1a3b-8bf5ca60f3bd
* Content: [Connect to your Git repos with SSH - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/use-ssh-keys-to-authenticate?view=azure-devops#feedback)
* Content Source: [docs/repos/git/use-ssh-keys-to-authenticate.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/repos/git/use-ssh-keys-to-authenticate.md)
* Product: **devops**
* Technology: **devops-code-git**
* GitHub Login: @apawast
* Microsoft Alias: **sdanie**

**Comment by marcpopMSFT** [comment]
Working on this now
