### ISSUE TITLE
Here is how to pick up & set variables in pipelines using Python

### ISSUE THREAD

**Issue by welabbar1** [MicrosoftDocs/vsts-docs#5697]
Use the following to pick up pipeline variables:
import os
os.environ['VARIABLE_NAME']

to set pipeline variables in scripts:

print ('##vso[task.setvariable variable=sauce]crushed tomatoes')
print('##vso[task.setvariable variable=secret.Sauce;issecret=true]crushed tomatoes with garlic')
print (f'##vso[task.setvariable variable=sauce]{pythonvariable}')

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd7e0bd3-1f7d-d7b6-cc72-5ef63c31b46a
* Version Independent ID: dae87abd-b73d-9120-bcdb-6097d4b40f2a
* Content: [Variables - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=classic%2Cbatch#feedback)
* Content Source: [docs/pipelines/process/variables.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/variables.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by welabbar1** [comment]
and

print (f'##vso[task.setvariable variable=sauce]{pythonvariable}')

**Comment by dantranter** [comment]
In order to set the property to a python variable....I had to do the following in my Python script (as the above suggestion didn't work...at least not for 2.7):
print '##vso[task.setvariable variable=sauce]' + sauce_python_var

**Comment by vtbassmatt** [comment]
f-strings were introduced in Python 3.6 (I believe), so it's expected that @welabbar1's snippet won't work in 2.7.

We document that [pipeline variables](https://docs.microsoft.com/azure/devops/pipelines/process/variables) are available as environment vars, and we document how you use logging commands to [create new ones](https://docs.microsoft.com/azure/devops/pipelines/scripts/logging-commands#setvariable-initialize-or-modify-the-value-of-a-variable). I don't think we want to get into a bunch of language-specific guidance on how to read env vars and write to stdout.

**Comment by welabbar1** [comment]
> In order to set the property to a python variable....I had to do the following in my Python script (as the above suggestion didn't work...at least not for 2.7):
> print '##vso[task.setvariable variable=sauce]' + sauce_python_var

Sorry! I forgot to mention this was for Python 3.6+

**Comment by LadyJaz** [comment]
> f-strings were introduced in Python 3.6 (I believe), so it's expected that @welabbar1's snippet won't work in 2.7.
> 
> We document that [pipeline variables](https://docs.microsoft.com/azure/devops/pipelines/process/variables) are available as environment vars, and we document how you use logging commands to [create new ones](https://docs.microsoft.com/azure/devops/pipelines/scripts/logging-commands#setvariable-initialize-or-modify-the-value-of-a-variable). I don't think we want to get into a bunch of language-specific guidance on how to read env vars and write to stdout.

The variables documented horribly. There isn’t only one example how we can get queue time variables from python file (not inline). Azure devops will be a pain if the documentation policy doesn’t change

**Comment by elabbarw** [comment]
I stopped following. But, yeah from a pure documentation standpoint Matt is right. @LadyJaz i'll send you a message.

**Comment by AliMzahem** [comment]
Anyone knows how to do it? The above-suggested ways did not work for me! I am working with Python 3.10

**Comment by elabbarw** [comment]
> Anyone knows how to do it? The above-suggested ways did not work for me! I am working with Python 3.10

Can you show me your example please?

**Comment by AliMzahem** [comment]
`print ('##vso[task.setvariable variable=sauce]crushed tomatoes')`

I tried this line of code in my Python Script task but the variable was not set in the pipeline variables! I even added the variable manually to the pipeline variables as an empty one, yet it did not work!

**Comment by elabbarw** [comment]
> `print ('##vso[task.setvariable variable=sauce]crushed tomatoes')`
> 
> I tried this line of code in my Python Script task but the variable was not set in the pipeline variables! I even added the variable manually to the pipeline variables as an empty one, yet it did not work!

You will need to add the "sauce" variable first before you can set a value. Try giving it a default value and then use:
```

import os

print (os.environ)

```
to see if the variable is part of the dictionary for environment variables 

:) all the best

**Comment by singularit-io** [comment]
Hey guys, two things: first, you want to set up this one so it can be picked up between stages, you need to use this:
print(f'##vso[task.setvariable variable=varName;isOutput=true]varValue

Accessing it between stages and validating its value against a given one would go like this:

eq(dependencies.STAGE_NAME.outputs['JOB_NAME.TASK_NAME.VAR_NAME'], 'the var value')

Also, something that can be super cool, if you want to define multiple ones by reading those through python script:

import os
import yaml
vars_dict = yaml.safe_load(Path('/home/vsts/work/1/s/pr_sources/pipeline_variables.yml').read_text())
for key in vars_dict:
    os.environ[key] = vars_dict[key]
    print(f'##vso[task.setvariable variable={key};isOutput=true]{vars_dict[key]}')

with say, your file pipeline_variables.yml containing

var1: val1
var2: val2

It's been such an effort to have this working I thought it would be nice to spare the trouble to others.
