### ISSUE TITLE
Industry Resources Links

### ISSUE THREAD

**Issue by rguthriemsft** [MicrosoftDocs/vsts-docs#5698]
The three scrum alliance links will 404 if you are not a member of scrum alliance which requires a paid membership.  You might add a note in the docs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 27e01fac-6a61-00a9-b914-2d42aa270bf8
* Version Independent ID: 6cc94467-d5d8-ff66-290f-c37304a83ccc
* Content: [Velocity metrics and usage guidance - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/report/dashboards/velocity-guidance?view=azure-devops)
* Content Source: [docs/report/dashboards/velocity-guidance.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/report/dashboards/velocity-guidance.md)
* Product: **devops**
* Technology: **devops-analytics**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by WilliamAntonRohm** [comment]
@rguthriemsft -- thank you for your feedback.

@KathrynEE -- please review the added wording in the above-mentioned PR.

**Comment by WilliamAntonRohm** [comment]
Answered in https://github.com/MicrosoftDocs/azure-devops-docs-pr/pull/129 -- the section and links are removed.
