### ISSUE TITLE
publishConfig property note should be improved

### ISSUE THREAD

**Issue by luckyrat** [MicrosoftDocs/vsts-docs#5708]
Please change "The build does not support using the publishConfig property" to something like "The build will fail, potentially with unrelated authentication errors, if you include the publishConfig property in your package.json config file" since this more closely describes the reality of this build system bug and the workaround required to avoid hitting it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d4cb48a1-d0bf-40b7-4645-910d4006fee9
* Version Independent ID: 9bddd101-2bc2-f65c-6a12-e395b76a2b98
* Content: [Publishing npm packages - Azure Pipelines and TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/npm?view=azure-devops&tabs=yaml#feedback)
* Content Source: [docs/pipelines/artifacts/npm.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/artifacts/npm.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @thomps23
* Microsoft Alias: **amullans**

**Comment by WilliamAntonRohm** [comment]
Thank you for your feedback.  I have updated the documentation and it should be live by tomorrow.
