### ISSUE TITLE
Exhaustive list of container requirements

### ISSUE THREAD

**Issue by Julio-Guerra** [MicrosoftDocs/vsts-docs#5714]
> Some of the extremely stripped-down containers available on Docker Hub, especially those based on Alpine Linux, don't satisfy these minimum requirements.

Please list the full requirements of a docker image. As the nodejs binary is mounted by the agent, we don't know what are its dependencies and you ask us to blindly install extra libraries.

So far, my alpine container still fails at the container initialization stage, but I could go further in this stage by blindly installing libc6-compat, gcompat, libstdc++, libgcc. Now it fails when doing:
`##[command]/usr/bin/docker exec  e581d30e8124a7f2c18f29a59f84d67e07620fcb1d091a756e222eb533289db9 bash -c "grep 1001 /etc/passwd | cut -f1 -d:"`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3339a2e0-be29-1363-f588-b231d4472c02
* Version Independent ID: 72dd11a3-704d-d0fd-6dfa-cf49f3352de3
* Content: [Container Jobs in Azure Pipelines and TFS - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/container-phases?view=azure-devops&tabs=yaml#feedback)
* Content Source: [docs/pipelines/process/container-phases.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/container-phases.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @thomps23
* Microsoft Alias: **macoope**

**Comment by Julio-Guerra** [comment]
Still stuck so far, using the container of the following Alpine [Dockerfile](https://github.com/sqreen/azure-pipelines-container-golang/blob/master/alpine/1.12/Dockerfile)

**Comment by juliakm** [comment]
@Julio-Guerra I've reached out for more information on the requirements and will let you know when there is an update.

**Comment by Julio-Guerra** [comment]
> "Some of the extremely stripped-down containers available on Docker Hub, especially those based on Alpine Linux, don't satisfy these minimum requirements."
> 
> Please list the full requirements of a docker image. As the nodejs binary is mounted by the agent, we don't know what are its dependencies and you ask us to blindly install extra libraries.
> 
> So far, my alpine container still fails at the container initialization stage, but I could go further in this stage by blindly installing libc6-compat, gcompat, libstdc++, libgcc. Now it fails when doing:
> `##[command]/usr/bin/docker exec e581d30e8124a7f2c18f29a59f84d67e07620fcb1d091a756e222eb533289db9 bash -c "grep 1001 /etc/passwd | cut -f1 -d:"`
> 
> #### Document Details
> ⚠ _Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking._
> 
> * ID: 3339a2e0-be29-1363-f588-b231d4472c02
> * Version Independent ID: 72dd11a3-704d-d0fd-6dfa-cf49f3352de3
> * Content: [Container Jobs in Azure Pipelines and TFS - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/container-phases?view=azure-devops&tabs=yaml#feedback)
> * Content Source: [docs/pipelines/process/container-phases.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/container-phases.md)
> * Product: **devops**
> * Technology: **devops-cicd**
> * GitHub Login: @thomps23
> * Microsoft Alias: **macoope**

###

**Comment by juliakm** [comment]
@Julio-Guerra The list of requirements for [Linux-based containers](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/container-phases?view=azure-devops&tabs=yaml#linux-based-containers) should be comprehensive. Please let us know if you have discovered any undeclared dependencies. The challenge we have run into in the past is that some of the Docker Hub containers do not meet these requirements.

**Comment by Julio-Guerra** [comment]
@juliakm this link is incomplete and that's why I was asking for every details. For example it also needs libc6, libstdc++, libgcc, and sudo. But the container still fails later in the container inits made by azure. Here is the dockerfile of Go on Alpine: https://github.com/sqreen/azure-pipelines-container-golang/blob/master/alpine/1.12/Dockerfile and it doesn't work: 

```
##[command]/usr/bin/docker version --format '{{.Server.APIVersion}}'
'1.40'
Docker daemon API version: '1.40'
##[command]/usr/bin/docker version --format '{{.Client.APIVersion}}'
'1.40'
Docker client API version: '1.40'
##[command]/usr/bin/docker ps --all --quiet --no-trunc --filter "label=186fd5"
##[command]/usr/bin/docker network prune --force --filter "label=186fd5"
##[command]/usr/bin/docker network create --label 186fd5 vsts_network_81ebd5836f754caeacad130b30f8bfbc
64a075d4cff2165dd73706660cf7f83cb62ceea59a967cdc402ea5334bcc0d4d
##[command]/usr/bin/docker pull julio/azure-pipelines-golang:1.13-alpine
1.13-alpine: Pulling from julio/azure-pipelines-golang
9d48c3bd43c5: Already exists
7f94eaf8af20: Pulling fs layer
9fe9984849c1: Pulling fs layer
43c4d47973b8: Pulling fs layer
9aaad45c37b5: Pulling fs layer
5fa4af64ccc1: Pulling fs layer
252a9b0b5e52: Pulling fs layer
5fc21c1a6248: Pulling fs layer
9aaad45c37b5: Waiting
252a9b0b5e52: Waiting
5fa4af64ccc1: Waiting
5fc21c1a6248: Waiting
7f94eaf8af20: Verifying Checksum
7f94eaf8af20: Download complete
9fe9984849c1: Verifying Checksum
9fe9984849c1: Download complete
7f94eaf8af20: Pull complete
9aaad45c37b5: Verifying Checksum
9aaad45c37b5: Download complete
9fe9984849c1: Pull complete
5fa4af64ccc1: Verifying Checksum
5fa4af64ccc1: Download complete
252a9b0b5e52: Verifying Checksum
252a9b0b5e52: Download complete
43c4d47973b8: Verifying Checksum
43c4d47973b8: Download complete
5fc21c1a6248: Verifying Checksum
5fc21c1a6248: Download complete
43c4d47973b8: Pull complete
9aaad45c37b5: Pull complete
5fa4af64ccc1: Pull complete
252a9b0b5e52: Pull complete
5fc21c1a6248: Pull complete
Digest: sha256:ec5b10b9a9c060ca443374c4bd45baa2b4d5c490ec60036252bc9ce232007478
Status: Downloaded newer image for julio/azure-pipelines-golang:1.13-alpine
docker.io/julio/azure-pipelines-golang:1.13-alpine
##[command]/usr/bin/docker inspect --format="{{index .Config.Labels \"com.azure.dev.pipelines.agent.handler.node.path\"}}" julio/azure-pipelines-golang:1.13-alpine
##[command]/usr/bin/docker create --name fc47506b89134a55b74c45f8e0b2c5fe_julioazurepipelinesgolangGOVERSION_8f5fd2 --label 186fd5 --network vsts_network_81ebd5836f754caeacad130b30f8bfbc  -e "GOARCH=amd64" -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/vsts/work/1":"/__w/1" -v "/home/vsts/work/_temp":"/__w/_temp" -v "/opt/hostedtoolcache":"/__t" -v "/home/vsts/work/_tasks":"/__w/_tasks" -v "/home/vsts/agents/2.158.0/externals":"/__a/externals":ro -v "/home/vsts/work/.taskkey":"/__w/.taskkey" julio/azure-pipelines-golang:1.13-alpine "/__a/externals/node/bin/node" -e "setInterval(function(){}, 24 * 60 * 60 * 1000);"
a33fedd56f7e43e7dd725aeaaaddc0007229bfbff85339e21b078972a2442ced
##[command]/usr/bin/docker start a33fedd56f7e43e7dd725aeaaaddc0007229bfbff85339e21b078972a2442ced
a33fedd56f7e43e7dd725aeaaaddc0007229bfbff85339e21b078972a2442ced
##[command]/usr/bin/docker ps --all --filter id=a33fedd56f7e43e7dd725aeaaaddc0007229bfbff85339e21b078972a2442ced --filter status=running --no-trunc --format "{{.ID}} {{.Status}}"
a33fedd56f7e43e7dd725aeaaaddc0007229bfbff85339e21b078972a2442ced Up Less than a second
##[command]/usr/bin/docker exec  a33fedd56f7e43e7dd725aeaaaddc0007229bfbff85339e21b078972a2442ced sh -c "command -v bash"
/bin/bash
##[command]whoami 
vsts
##[command]id -u vsts
1001
Try create an user with UID '1001' inside the container.
##[command]/usr/bin/docker exec  a33fedd56f7e43e7dd725aeaaaddc0007229bfbff85339e21b078972a2442ced bash -c "grep 1001 /etc/passwd | cut -f1 -d:"
##[error]Docker exec fail with exit code 126
##[section]Finishing: Initialize containers
```

**Comment by vtbassmatt** [comment]
Alpine containers are not glibc-based, which is a documented requirement. Alpine uses an alternative C runtime called musl.

We're working on extending our container support. In the meantime, we document a mechanism to use an Alpine-based container (but know that you're playing on "hard mode" at this point :grin:). See [this doc](https://github.com/microsoft/azure-pipelines-agent/blob/master/docs/design/non-glibc-containers.md) for instructions.

**Comment by Julio-Guerra** [comment]
It now works @vtbassmatt based on the doc example <3
Thanks!

For the record, dockerfile for go on alpine on azure pipeline

```
FROM node:10-alpine

RUN apk add --no-cache --virtual .pipeline-deps readline linux-pam \
  && apk add bash sudo shadow \
  && apk del .pipeline-deps

LABEL "com.azure.dev.pipelines.agent.handler.node.path"="/usr/local/bin/node"

# Go and gcc (go dependency) + libc6-compat to have the libc6.so symlink to muslc
RUN apk add 'go~1.12' libc6-compat

CMD [ "node" ]
```

**Comment by jakuboskera** [comment]
> Alpine containers are not glibc-based, which is a documented requirement. Alpine uses an alternative C runtime called musl.
> 
> We're working on extending our container support. In the meantime, we document a mechanism to use an Alpine-based container (but know that you're playing on "hard mode" at this point 😁). See [this doc](https://github.com/microsoft/azure-pipelines-agent/blob/master/docs/design/non-glibc-containers.md) for instructions.

@vtbassmatt What is the current status with supporting Alpine based images in Azure pipelines. It's been a 3y from last updated... 
Thanks

**Comment by vtbassmatt** [comment]
> @vtbassmatt What is the current status with supporting Alpine based images in Azure pipelines. It's been a 3y from last update... Thanks

I haven't worked on Azure Pipelines in years, so I have no idea, sorry. AFAIK the documentation that I pointed to in 2019 is still the latest.
