### ISSUE TITLE
Typo in link to Migration Guide download

### ISSUE THREAD

**Issue by OraDotNetDev** [MicrosoftDocs/vsts-docs#5716]
There's a typo in the link for the Migration Guide - clicking link redirects to MS Home Page.

```
https://aka.ms/AzureDevOpsImportt

should be 

https://aka.ms/AzureDevOpsImport
```

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bff3fd07-3d7b-1244-88e4-c2cfbb3fa204
* Version Independent ID: 63f4392f-2dc6-4620-a24f-c02070dd7115
* Content: [Troubleshooting the migration import from Azure DevOps Server to Azure DevOps Services](https://docs.microsoft.com/en-gb/azure/devops/migrate/migration-troubleshooting?view=azure-devops)
* Content Source: [docs/migrate/migration-troubleshooting.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/migrate/migration-troubleshooting.md)
* Product: **devops**
* Technology: **devops-learn**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by msebolt** [comment]
@OraDotNetDev Thank you for the feedback.

The documentation has been updated.

#please-close
