### ISSUE TITLE
Typo in 1st sentence

### ISSUE THREAD

**Issue by jonathanrelf** [MicrosoftDocs/vsts-docs#5718]
"If Microsoft Project is your preferred tool for tacking projects" should read "If Microsoft Project is your preferred tool for tracking projects"
Tacking / Tracking

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4f6edd47-46d7-ab0d-db47-d73bc45d6b43
* Version Independent ID: 6ac2ae49-0bd0-2c28-fc87-7f034dd96443
* Content: [Create your backlog and tasks using Microsoft Project - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/backlogs/office/create-your-backlog-tasks-using-project?view=tfs-2018&tabs=office-365#feedback)
* Content Source: [docs/boards/backlogs/office/create-your-backlog-tasks-using-project.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/boards/backlogs/office/create-your-backlog-tasks-using-project.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by msebolt** [comment]
@jonathanrelf Thank you for the feedback.

The documentation has been updated.
