### ISSUE TITLE
Invalid links

### ISSUE THREAD

**Issue by sasedlock** [MicrosoftDocs/vsts-docs#572]
Within the "Related Notes" section of this document, the link for "Work in Team Explorer" actually points to the page for "Work in Web Portal".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a261eec7-bb48-e092-5bb8-e8bb699ef860
* Version Independent ID: 37c7d060-ce28-2e1c-e8d9-1e5be240bf5c
* Content: [Connect to team projects in VSTS or TFS](https://docs.microsoft.com/en-us/vsts/user-guide/connect-team-projects?view=vsts#connectvs)
* Content Source: [docs/user-guide/connect-team-projects.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/user-guide/connect-team-projects.md)
* Service: **unspecified**
* GitHub Login: @erickson-doug
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
@sasedlock Thanks for letting us know, I am fixing that now and it should be live in a day or two.
