### ISSUE TITLE
Is possible to run as superuser (sudo)?

### ISSUE THREAD

**Issue by 24mu13** [MicrosoftDocs/vsts-docs#5720]
Is possible to run the specified command as superuers (sudo)?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a79d17fd-6e65-d8f0-ea05-f62d68456474
* Version Independent ID: 3f7338a7-aae7-b6b6-3291-5c985c6fa6f3
* Content: [Command Line task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/command-line?view=azure-devops&tabs=yaml#feedback)
* Content Source: [docs/pipelines/tasks/utility/command-line.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/utility/command-line.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @vtbassmatt
* Microsoft Alias: **macoope**

**Comment by vtbassmatt** [comment]
On the hosted pools, both Mac and Linux, you have password-less sudo on the agent user account. (So yes.) On a private agent, all bets are off - it has to do with how the person setting up the agent has configured the machine. (So it depends.)
