### ISSUE TITLE
Add a variable to access Organization Name

### ISSUE THREAD

**Issue by eric-labelle** [MicrosoftDocs/vsts-docs#5721]
It would be really useful to expose `organization` as it is needed for all Azure DevOps REST Api calls and is currently inaccessible (_as far as I know_). The only variable exposed is the CollectionId.

> System.CollectionId | The GUID of the TFS collection or Azure DevOps organization

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ffebdc8-521c-44b5-cde4-4abdc1bd6f18
* Version Independent ID: dc0effda-6d93-62aa-64c5-4e6f283b0826
* Content: [Predefined variables - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/build/variables.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/build/variables.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by ibrahim0814** [comment]
+1

**Comment by msebolt** [comment]
@eric-labelle Thank you for the feedback.

This is more of a feature request and would get better traction in front of the product team.

Please move this issue to **Suggest a Feature** in the [Azure DevOps User Voice](https://developercommunity.visualstudio.com/topics/Azure+DevOps.html).

**Comment by eric-labelle** [comment]
Allright. Sorry about that, here it is: https://developercommunity.visualstudio.com/idea/747962/add-a-variable-to-access-organization-name.html
