### ISSUE TITLE
Default value is not documented!

### ISSUE THREAD

**Issue by jimmcslim** [MicrosoftDocs/vsts-docs#5726]
It appears the default value for this is $(Date:yyyyMMdd).$(Rev:r)

It would be also handy if the 'Variables, predefined' section linked from the description of 'Build.BuildNumber' to this page (and could we also be consistent about whether we are talking about 'Run Number' or 'Build Number' please? - I'd suggest calling it Build Number...)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a57f8545-bb15-3a71-1876-3a9ec1a59b93
* Version Independent ID: 28c87c8d-c28d-7493-0c7c-8c38b04fbcd7
* Content: [Run number - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/run-number?view=azure-devops&tabs=yaml#feedback)
* Content Source: [docs/pipelines/process/run-number.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/run-number.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by juliakm** [comment]
Thanks @jimmcslim. Updates to these docs should be live soon.

**Comment by jimmcslim** [comment]
Thanks, hopefully this issue will be referenced in the commit/PR so that the changes will be clear!
