### ISSUE TITLE
Build.BuildNumber is unclear

### ISSUE THREAD

**Issue by jimmcslim** [MicrosoftDocs/vsts-docs#5727]
It appears that the discussion behind where Build.BuildNumber is set is inaccurate. I see nothing in ADO Pipeline options to set this. However it appears that it can be set with a top-level 'name' property in the pipeline YAML. There is discussion about this in the 'Run number' page. However it also confusing to have 'Run number' and 'Build number' which are both the same thing. Let's just refer to 'Build number' please (since the Builds list has a 'Build #' column).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ffebdc8-521c-44b5-cde4-4abdc1bd6f18
* Version Independent ID: dc0effda-6d93-62aa-64c5-4e6f283b0826
* Content: [Predefined variables - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/build/variables.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/build/variables.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by juliakm** [comment]
In Microsoft Team Foundation Server (TFS) 2018 and previous versions, _runs_ are called _builds_. We've added clarification of this as part of [#5726](https://github.com/MicrosoftDocs/vsts-docs/issues/5726) and that update will be live soon.
