### ISSUE TITLE
Templates for stages

### ISSUE THREAD

**Issue by fleed** [MicrosoftDocs/vsts-docs#5728]
Is it possible to use templates for stages?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6724abea-bbdc-bf66-ed5e-3214fa6c3e66
* Version Independent ID: 4f8dab21-3f0e-da32-cc0e-1d85c13c0065
* Content: [Job and step templates - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/templates?view=azure-devops)
* Content Source: [docs/pipelines/process/templates.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/templates.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @vtbassmatt
* Microsoft Alias: **macoope**

**Comment by hr-sn** [comment]
we are using templates for stages like this
- stage: CI_Build
  displayName: 'CI Build'
  jobs:
  - template: 'CI Build.yml'

**Comment by vtbassmatt** [comment]
Good catch, will fix.
