### ISSUE TITLE
Can i use dynamic variables (generated in powershell by ##vso.setVariable command) in {{ each ... }} statement?

### ISSUE THREAD

**Issue by tauke1** [MicrosoftDocs/vsts-docs#5729]
Can i use dynamic variables (generated in powershell by ##vso.setVariable command) in {{ each ... }} statement?
I want to generate some objects in powershell by ##vso.SetVariable command and iterate it by {{ each ....}} statement

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6724abea-bbdc-bf66-ed5e-3214fa6c3e66
* Version Independent ID: 4f8dab21-3f0e-da32-cc0e-1d85c13c0065
* Content: [Job and step templates - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/templates?view=azure-devops#feedback)
* Content Source: [docs/pipelines/process/templates.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/templates.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @vtbassmatt
* Microsoft Alias: **macoope**

**Comment by vtbassmatt** [comment]
You cannot. Template expressions (`${{ }}`) are fully expanded [before the run even really starts](https://docs.microsoft.com/azure/devops/pipelines/process/runs?view=azure-devops#process-the-pipeline).
