### ISSUE TITLE
Cannot playback video recordings created by the Test & Feedback extension

### ISSUE THREAD

**Issue by EugeneKonneh** [MicrosoftDocs/vsts-docs#5730]
[I am unable to playback video recordings from Test & Feedback extension.

I have both Chrome and  VLC Video player installed.
However, when I click on the video recording from Test &Feedback, it is trying to open MTMS files, advising me to look for a new app.

![image](https://user-images.githubusercontent.com/48555490/65588527-98dd6e80-df7f-11e9-9cc2-ce40f0098b0a.png)

]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 985ecee3-e347-43bb-5ed2-08ce3aee7621
* Version Independent ID: fdf465fc-a9e1-0198-2e8c-e859c74252b3
* Content: [FAQs and problem solutions - Azure Test Plans](https://docs.microsoft.com/en-us/azure/devops/test/reference-qa?view=azure-devops#feedback)
* Content Source: [docs/test/reference-qa.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/test/reference-qa.md)
* Product: **devops**
* Technology: **devops-test**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by msebolt** [comment]
@EugeneKonneh Thank you for the question, we're sorry you're experiencing issues.

It appears this issue has been filed before [here](https://developercommunity.visualstudio.com/content/problem/305783/unable-to-play-video-recording-from-test-feedback.html), please see if [these instructions](https://www.webmfiles.org/how-to-play-webm-files/) can resolve the issue.

**Comment by msebolt** [comment]
Closing the issue now, please comment below if there are any questions.
