### ISSUE TITLE
Microsoft hosted agents - what are the IP address ranges

### ISSUE THREAD

**Issue by kinseymd** [MicrosoftDocs/vsts-docs#5733]
Your section above provides the link to download all the IP ranges for Azure hosted services. No where in this json file is the word DevOps or agents. 
Specific section in this article: https://docs.microsoft.com/en-us/azure/devops/organizations/security/allow-list-ip-url?view=azure-devops#using-microsoft-hosted-agents
Linked resource: https://www.microsoft.com/en-us/download/details.aspx?id=56519

There is a separate article which actually lists the IP ranges for Azure DevOps. I don't know if this includes Microsoft hosted build agents or not. When I search for specific ranges listed in the article (linked just below), I also see no results in the JSON file. What are the IP ranges for Microsoft hosted build agents? As many customers implement firewall rules to protect their resources in Azure, we need this information to whitelist Azure DevOps build agents (specifically Microsoft hosted)
https://docs.microsoft.com/en-us/azure/devops/organizations/security/allow-list-ip-url?view=azure-devops#azure-devops-ip-addresses

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc5a4cfa-aa84-9f0f-55f4-71ec4861c070
* Version Independent ID: d621620a-c924-03b1-8b43-f99c33e58bb8
* Content: [Add IP addresses and URLs to allow list - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/security/allow-list-ip-url?view=azure-devops#feedback)
* Content Source: [docs/organizations/security/allow-list-ip-url.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/security/allow-list-ip-url.md)
* Product: **devops**
* Technology: **devops-security**
* GitHub Login: @chcomley
* Microsoft Alias: **jominana**

**Comment by chcomley** [comment]
Hi @kinseymd, Thanks for reaching out. I'm following up on this and will be in touch.

**Comment by chcomley** [comment]
Hi @kinseymd, Our team is working on this and we'll update the article accordingly. In the meantime, please follow [these instructions](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops#agent-ip-ranges).

There aren't specific ranges for hosted agents since the're dynamic and can change. You need to whitelist the IP address range in the entire geography. We know this isn't ideal - another workaround would be to use self-hosted agents if security is a concern. 

I'll be closing this issue, however do let us know if you have any other questions. Thanks!

**Comment by Damag3d** [comment]
So what do we need to search for in JSON file - can you, please, answer more specifically?

**Comment by pjirsa** [comment]
Search for the "AzureCloud.<regionname>" sections. those are the IPs you need to whitelist.

**Comment by baoduy** [comment]
I think this is a problem as we need to be whitelist the IP of the entire region. The Microsoft Host Agent should be run under a smaller IP Range. Could you please provide the range of Azure DevOps only?

**Comment by KeithDavis41** [comment]
An approach I took was to whitelist the ip address within the build using Inline Scripts. 
For an example, I wrote a blog [Whitelisting Microsoft Hosted Build Agents within Azure DevOps
]( https://keithjr.dev/development/hosted_build_agent/)

**Comment by JoelCBennett** [comment]
Why is this item closed @chcomley ?  This is still an issue, and there is no effective workaround.  It is not a reasonable approach to ask a security team to make weekly updates to IP ranges to firewall rules, nor is it a good security practice to whitelist blocks of IP addresses which can come from malicious sources.  

The real answer will be to expand service tag support for DevOps to the pipeline functionality.

**Comment by chcomley** [comment]
Hi @JoelCBennett, This issue has been closed for almost 2 years.
I highly recommend submitting a feature request for "expanding service tag support for DevOps to the pipeline functionality" to the [Developer Community](https://developercommunity.visualstudio.com/home), so we can get our engineers' eyes on it. Thanks and have a great day.

**Comment by JoelCBennett** [comment]
@chcomley I don't see why it is closed, as the original issue still persists with no solid work-around.  Happy to submit it as a feature request as well.

**Comment by haciz** [comment]
Still there is no some easy solution for this, specially when you use Terraform. With PS there is a decent workaround but not always suitable for different use cases, example is integration testing with terratest framework and access to storage account

**Comment by Damag3d** [comment]
We will implement similar approach to azure devops SQL server firewall bypass. I just needed more people on my team to do it for me. Not huge impact on security and limit access to specific agent only. Unfortunately only specific resources will be supported. But this became more and more problematic.
In private link environments I need to setup endpoint for each resource in addition to general usage endpoint. Nonsense.

**Comment by poleshe** [comment]
This should not be closed. This is not a good solution. Some regions have +350 IPS and Azure Firewalls only support up to 200, for example.
Also it seems that it's possible for the IPS to change mid-week and you have to wait for the weekly update to have your Agents working again.
This should be native.

**Comment by TeamDman** [comment]
Don't forget: [Microsoft hosted AzureDevOps pipeline agents aren't considered "microsoft services" for the purpose of Azure networking like on storage accounts](https://github.com/MicrosoftDocs/azure-docs/issues/19456)
Also relevant: https://github.com/MicrosoftDocs/azure-devops-docs/issues/12136
