### ISSUE TITLE
Mention the Git Credential Manager Core (Beta) for dev.azure.com repositories?

### ISSUE THREAD

**Issue by soccerjoshj07** [MicrosoftDocs/vsts-docs#5736]
Following the github page linked in this article to use brew to install git-credential-manager for MacOS did not work for dev.azure.com repos.

This worked- https://github.com/microsoft/Git-Credential-Manager-Core#download-and-install

Not sure if it is worth mentioning here for others.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c2f260d-9321-d669-172d-01289c233263
* Version Independent ID: 14e9ae18-df9d-7555-902c-3e8b4c2b2f22
* Content: [Connect to your Git repos using credential managers - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/set-up-credential-managers?view=azure-devops#feedback)
* Content Source: [docs/repos/git/set-up-credential-managers.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/repos/git/set-up-credential-managers.md)
* Product: **devops**
* Technology: **devops-code-git**
* GitHub Login: @apawast
* Microsoft Alias: **sdanie**

**Comment by marcpopMSFT** [comment]
Seems reasonable.  I'll take a look.
