### ISSUE TITLE
What about variables with same name across different variable groups and variables created using the web editor referenced in the same pipeline?

### ISSUE THREAD

**Issue by swappy208** [MicrosoftDocs/vsts-docs#5739]
if i created a variable "foo" in the pipeline variables with value "bar",
created a variable group with variable "foo" value "bar2" and referenced the variable group in the pipeline,
which one would have a precedence?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd7e0bd3-1f7d-d7b6-cc72-5ef63c31b46a
* Version Independent ID: dae87abd-b73d-9120-bcdb-6097d4b40f2a
* Content: [Variables - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch#expansion-of-variables)
* Content Source: [docs/pipelines/process/variables.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/variables.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by msebolt** [comment]
@swappy208 Thank you for the question.

The order of precedence for variables goes,

1.  Variables used in the yaml file.
2.  Variables declared in the pipeline's variables.
3.  Variables declared in the shared variable groups.

So to answer your question, the pipeline variable `foo` would take precedence over the variable group `foo`.

**Comment by v-avirao** [comment]
What happens when two variable groups having same variable are imported in a stage.
For Eg: Group1 has variable "variable1" and Group2 also has "variable1" and I am referring both the groups in one stage. How to access Group1.Variable1 ?
Thanks

**Comment by v-avirao** [comment]
What happens when two variable groups having same variable are imported in a stage.
For Eg: Group1 has variable "variable1" and Group2 also has "variable1" and I am referring both the groups in one stage. How to access Group1.Variable1 ?
Thanks
