### ISSUE TITLE
Bulk export URLs to all the wiki pages

### ISSUE THREAD

**Issue by joeschu33** [MicrosoftDocs/vsts-docs#5740]
We just went through an effort to lift and shift our content from mediawiki to ADO Wiki. Our Alerts in ICM have links to the wiki pages in the old wiki that we'd like to update to the new wiki pages in the new wiki. The problem is the full url's to the new wiki pages include a "page id" that I don't know how to bulk export and doing it one at a time is a giant pain. Is there an API or better yet, a table in Kusto I can use to get all the full urls to all the wiki pages?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d7892ee5-8b56-bd95-29bb-41ebb8a8bd7e
* Version Independent ID: eccf0785-0968-d6a2-d29e-0c4796aa165c
* Content: [Add, edit, reorder and manage wiki pages in Azure DevOps - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/project/wiki/add-edit-wiki?view=azure-devops#feedback)
* Content Source: [docs/project/wiki/add-edit-wiki.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/project/wiki/add-edit-wiki.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by msebolt** [comment]
@joeschu33 Thank you for the question.

The Azure DevOps REST API includes the [Wiki List](https://docs.microsoft.com/rest/api/azure/devops/wiki/wikis/list?view=azure-devops-rest-5.1) call that includes the `url` property.

Assigning this to the author for possible Kusto options.

**Comment by adramasu** [comment]
Hi,

Like @msebolt says, there are REST APIs to get this done. Kusto doesn't not have all the data related to pages, pageids and URLs. So, there would be only partial information in Kusto.

**Comment by chcomley** [comment]
Hi @joeschu33, Let us know if you have any further questions, however I'll be closing this issue. Thanks for reaching out!
