### ISSUE TITLE
Need some summary about the troubleshooting of the error MTOUCH : error MT2002: Failed to resolve

### ISSUE THREAD

**Issue by BrightRan** [MicrosoftDocs/vsts-docs#5741]
Need some summary about the troubleshooting of the error 
MTOUCH : error MT2002: Failed to resolve "......"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 54533c61-9265-2908-c92d-f49285b24333
* Version Independent ID: 004ded47-21ee-94a7-51fe-2b835e124b55
* Content: [Build Xamarin apps - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/ecosystems/xamarin?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/ecosystems/xamarin.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/ecosystems/xamarin.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @chasewilson
* Microsoft Alias: **phwilson**

**Comment by msebolt** [comment]
@BrightRan  Thank you for the feedback.

This error summary seems better suited for the [Xamarin docs repo](https://github.com/MicrosoftDocs/xamarin-docs/issues).

Please move this issue there to see if it can be added the docs.

**Comment by msebolt** [comment]
Closing the issue now, please comment below if there are any questions.
