### ISSUE TITLE
Run number environment variable not documented

### ISSUE THREAD

**Issue by lmeyerov** [MicrosoftDocs/vsts-docs#5742]
The docs provide information on defining Run Number format, but "Variables, predefined" does not document reading the Run Number environment variable within a script. It is unclear what environment variable to read to reference the Run Number, which is an important part of signing generated artifacts with correlation IDs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ffebdc8-521c-44b5-cde4-4abdc1bd6f18
* Version Independent ID: dc0effda-6d93-62aa-64c5-4e6f283b0826
* Content: [Predefined variables - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml#feedback)
* Content Source: [docs/pipelines/build/variables.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/build/variables.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by lmeyerov** [comment]
nudge @steved0x any guidance here?

**Comment by lmeyerov** [comment]
@msebolt @steved0x (ping)

**Comment by juliakm** [comment]
I've updated [Variables, predefined](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml#feedback) and added a FAQ question to [Run (build) number](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/run-number?view=azure-devops&tabs=yaml#how-can-you-reference-the-run-number-variable-within-a-script).
