### ISSUE TITLE
YAML Release Permissions?

### ISSUE THREAD

**Issue by liamfoneill** [MicrosoftDocs/vsts-docs#5746]
Now that YAML includes release stages also, how can the pipeline permissions be secured? An example scenario is a financial institution who wants developers to be able to create builds but wants oversight of the release and needs to ensure that the release pipeline contains sufficient quality before a release. If the pipeline is in the Repo, they do not want to have to approve every merge to master as that would slow developers down and they might not even be changing the pipeline file in that PR anyhow. They want to have confidence that the pipeline itself is an 'approved' pipeline. From this documentation it isn't clear how this can be achieved any more with YAML (it's clear how this can be done with legacy build and release pipelines).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a8c6f274-a008-fac6-7d99-13d2ce7c8dc3
* Version Independent ID: 916fef9e-d644-2114-b466-e5bda8028ee9
* Content: [Pipeline permissions and security roles - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/policies/permissions?view=azure-devops#feedback)
* Content Source: [docs/pipelines/policies/permissions.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/policies/permissions.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @chasewilson
* Microsoft Alias: **phwilson**

**Comment by msebolt** [comment]
@liamfoneill Thank you for the question.

For now, you need to use YAML from the [Invoke REST API task](https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/http-rest-api?view=azure-devops) and call the [Permissions endpoint](https://docs.microsoft.com/rest/api/azure/devops/security/permissions?view=azure-devops-rest-5.1).

Is this something along the lines with what you had in mind?

Also see https://github.com/MicrosoftDocs/vsts-docs/issues/5630 regarding [Approvals](https://docs.microsoft.com/azure/devops/pipelines/process/approvals?view=azure-devops) and use of the [manual intervention task](https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/manual-intervention?view=azure-devops) for additional security added via YAML.

**Comment by msebolt** [comment]
Closing the issue now, please comment below if there are any questions.
