### ISSUE TITLE
Checkout - Allow tagging on completion

### ISSUE THREAD

**Issue by adriantorrie** [MicrosoftDocs/vsts-docs#5749]
Add an attribute to `checkout` that allows the git repo to be tagged on success.

Raised in https://github.com/microsoft/azure-pipelines-yaml/issues/139 and https://github.com/microsoft/azure-pipelines-yaml/issues/325

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7458d5b2-1bb7-7d87-7ce6-2b0c430b0155
* Version Independent ID: edf5bbd3-a3f0-5426-e985-31290f8afd05
* Content: [YAML schema - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema#checkout)
* Content Source: [docs/pipelines/yaml-schema.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/yaml-schema.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @vtbassmatt
* Microsoft Alias: **macoope**

**Comment by vtbassmatt** [comment]
This is a product feature request, not a documentation bug.
