### ISSUE TITLE
Setting user capabilities when using unattended agent configuration

### ISSUE THREAD

**Issue by plang85** [MicrosoftDocs/vsts-docs#575]
We would like to set user capabilities for agents when we provision them, ie when we call config.sh - is this supported/on the roadmap?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 47625b86-abd5-ee15-6d61-8bcf81861b96
* Version Independent ID: be9a6174-a69b-7aed-d584-5f602fcc5eb4
* Content: [Build and Release Agents](https://docs.microsoft.com/en-us/vsts/build-release/concepts/agents/agents?view=vsts#capabilities)
* Content Source: [docs/build-release/concepts/agents/agents.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/build-release/concepts/agents/agents.md)
* Service: **unspecified**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by chrisrpatterson** [comment]
Any environment variables you set as part of the configuration that are not set in the ignore file will be published as capabilities. That is currently the suggested way to accomplish your scenario.

**Comment by plang85** [comment]
and even says so in the documentation :)
