### ISSUE TITLE
Does this install and remove the certificate?

### ISSUE THREAD

**Issue by henry-padilla** [MicrosoftDocs/vsts-docs#5750]
"To connect to the cluster, the service fabric task uses the machine cert store to store the information about the certificate. Using the same certificate, if two releases run together on one machine they will start properly. However, if one of the tasks is complete, the certificate from the machine cert store would be cleaned up, which would affect the second release"

This implies that the task will remove the certificate from the store. Does this also imply the task will install the certificate in the store for use? Is this part of the service connection?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7068e469-201e-c820-4d27-b798ea799b70
* Version Independent ID: d6bb717a-1c44-43a1-c7a5-9616b257c0e0
* Content: [Service Fabric Application Deployment task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/service-fabric-deploy?view=azure-devops)
* Content Source: [docs/pipelines/tasks/deploy/service-fabric-deploy.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/deploy/service-fabric-deploy.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by henry-padilla** [comment]
Answered my own question - per https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/ServiceFabricDeployV1 ... yes, it installs and removes the service endpoint certificate.

This can be closed.

**Comment by msebolt** [comment]
@henry-padilla Thank you for the feedback.

We welcome all contributions to the forum.
