### ISSUE TITLE
Sample index.ts doesn't compile

### ISSUE THREAD

**Issue by nickfoster** [MicrosoftDocs/vsts-docs#5753]
Index.ts from Step 1 does not compile.  Opening it in VS Code shows a problem at line 5:

const inputString: string = tl.getInput('samplestring', true);

Type 'string | undefined' is not assignable to type 'string'.
  Type 'undefined' is not assignable to type 'string'.ts(2322)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 44581f4a-93df-7507-3844-eadedf9a6cc4
* Version Independent ID: 33c7bcf0-1512-975f-5ef8-9f2a192a84ad
* Content: [Add a Build or Release Task](https://docs.microsoft.com/en-us/azure/devops/extend/develop/add-build-task?view=azure-devops&viewFallbackFrom=vsts#feedback)
* Content Source: [docs/extend/develop/add-build-task.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/extend/develop/add-build-task.md)
* Product: **devops**
* Technology: **devops-ecosystem**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by msebolt** [comment]
@nickfoster  Thank you for the feedback, we're sorry you're experiencing issues.

As per [this post](https://stackoverflow.com/questions/54496398/typescript-type-string-undefined-is-not-assignable-to-type-string), please try:

```const inputString: string = tl.getInput('samplestring', true)!;```

**Comment by msebolt** [comment]
Closing the issue now, please comment below if there are any questions.
