### ISSUE TITLE
Problem after logging out I no longer have access

### ISSUE THREAD

**Issue by dazinator** [MicrosoftDocs/vsts-docs#5756]
After following this guide, after disconnecting the old AD, and then signing out, when I sign in again it says I do not have access to the Azure DevOps organisation.

My account is a member in the old AD as well as the new AD. I followed all of the prereequisites above. So how come after logging out, and then logging back in - I no longer have access?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 98f0caaf-2697-c506-339b-2dea64233e48
* Version Independent ID: 7cd2ea02-2079-85d0-09e0-a90af59937d9
* Content: [Change connection to Azure AD - Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/change-azure-ad-connection?view=azure-devops)
* Content Source: [docs/organizations/accounts/change-azure-ad-connection.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/accounts/change-azure-ad-connection.md)
* Product: **devops**
* Technology: **devops-accounts**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by dazinator** [comment]
My scenario - we have a new azure organisation and subscription. I want to switch Azure DevOps AD to the Azure AD within our new Azure Organisation. 

I am the project owner in DevOps, so I invited myself as a guest into the new Azure AD - then I used the powershell script here to convert my user type from "guest" to "member": https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/faq-add-delete-users?view=azure-devops#q-how-can-i-convert-an-azure-ad-guest-into-a-member

My account is now a member in both AD's, it's the project owner and its in the Project Collection Administration group.

So I clicked the button the disconnect the old AD, and then it prompted me to log out, which I did. I then logged in with the very same email address. At this point it tells me I no longer have access to the Azure DevOps organisation. Therefore I am now stuck.

**Comment by msebolt** [comment]
@dazinator  Thank you for the feedback, we're sorry to hear you're experiencing issues.

This issue currently appears to be a [common problem in VSTS](https://developercommunity.visualstudio.com/search.html?f=&type=question+OR+problem+OR+idea&type=question+OR+problem+OR+idea&c=&redirect=search%2Fsearch&sort=relevance&q=lost+access+to+organization) with a variety of resolutions, though it is likely the product team will need your organization's specific details and you can go from there. 

Please move this to [Report a problem](https://developercommunity.visualstudio.com/spaces/21/index.html) and comment below if there are any issues.

**Comment by dazinator** [comment]
@msebolt 
It appears that after some period of time I was able to access it again. I'll close this for now but this was only done on a test organisation to test the process. I'll reopen the issue if it occurs again and does not resolve itself.

**Comment by msebolt** [comment]
Sounds good, thank you for the update.
