### ISSUE TITLE
Additional File copy parameters are not applied

### ISSUE THREAD

**Issue by JustinSchneiderPBI** [MicrosoftDocs/vsts-docs#5759]
We had a problem with overwrite recently, where 2 different build definitions incorrectly pointed to the same share. This caused a significant amount of duplicated work for a number of people, so the followups are rather important. In addition to correcting the destinations, we're preventing future misconfigurations by blocking overwrite of files. I added additional file copy parameters to exclude files that are either newer or older or different and to apply readonly setting in windows: /XC /XO /XN /A:+R. However, these settings were not applied. Please fix this.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b3f565b-88e4-88d6-a534-48ec21e6e3d8
* Version Independent ID: 9fca89ae-4a6e-a43a-2834-1a91ad44c256
* Content: [Publish Build Artifacts task - Azure Pipelines](https://docs.microsoft.com/en-ca/azure/devops/pipelines/tasks/utility/publish-build-artifacts?view=azure-devops#feedback)
* Content Source: [docs/pipelines/tasks/utility/publish-build-artifacts.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/utility/publish-build-artifacts.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @DavidStaheli
* Microsoft Alias: **dastahel**

**Comment by msebolt** [comment]
@JustinSchneiderPBI  Thank you for the feedback, we're sorry you're experiencing issues.

This problem is a good candidate for the product team to respond to.

Please move the issue to [azure-pipelines-tasks](https://github.com/Microsoft/azure-pipelines-tasks/issues) and comment below if there are any further issues.

**Comment by JustinSchneiderPBI** [comment]
Thanks. I followed the link in the build task, but it pointed me here instead of to file the bug. New issue in pipelines-tasks: https://github.com/microsoft/azure-pipelines-tasks/issues/11451.
Thanks!

**Comment by msebolt** [comment]
Thank you for transferring the issue.
