### ISSUE TITLE
download an artifact from a fileshare to the pipeline

### ISSUE THREAD

**Issue by marc-gmail-towersap** [MicrosoftDocs/vsts-docs#5760]
according to the yaml comment directly above, this 
Download artifacts from file share
By fileshare, I am assuming this is a UNC path (says \\share\drop).  But when I try to configure it to use \\mycomputername.domainname\uncshare, I get Error: UNKNOWN, scandir '\\mycomputername.domainname\uncshare'

First, does this have the agent download file(s) from that UNC share so I can use them?  I'm trying to use this for powerbi, where I don't want to check in the pbix file (which can get huge, and it is a binary), but instead, have the agent download it from the UNC share so I can use it as an build artifact to publish in a release pipeline to various workspaces. but if I can't get it to download from a UNC share, then this won't work...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 475548ee-1af8-7ef5-bb8c-7efaed9598a2
* Version Independent ID: 0108f9da-6b28-54f2-ee15-e030a0a1daa2
* Content: [Download Fileshare Artifacts task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/download-fileshare-artifacts?view=azure-devops)
* Content Source: [docs/pipelines/tasks/utility/download-fileshare-artifacts.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/utility/download-fileshare-artifacts.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by marc-gmail-towersap** [comment]
those are double backslashes matching a UNC pattern (fyi), it seemed to have slashed my double backslash...

**Comment by ashokirla** [comment]
Yes, when you publish your artifacts to fileshare, the agent downloads the artifacts from the UNC share it is pointed to. 
You need to provide the fileshare path (server/share) and the name of the artifact to download. You also need to ensure the agent has rights to download the artifact from the share.
