### ISSUE TITLE
Naming doesn't match pipeline UI

### ISSUE THREAD

**Issue by timheuer** [MicrosoftDocs/vsts-docs#5761]
When using the Azure Pipleines UI the task is not called '.NET Core Tool Installer' but rather 'Use .NET Core' and either the docs here should change or the task should change to match each other.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f9660c58-3366-f1be-8380-d6cf1d3c0150
* Version Independent ID: 226a4fd8-bce8-3333-d8d6-7af933c7b060
* Content: [.NET Core Tool Installer task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/dotnet-core-tool-installer?view=azure-devops)
* Content Source: [docs/pipelines/tasks/tool/dotnet-core-tool-installer.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/tool/dotnet-core-tool-installer.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @pulkitaggarwl
* Microsoft Alias: **puagarw**

**Comment by msebolt** [comment]
@timheuer Thank you for the feedback.

The documentation has been updated.
