### ISSUE TITLE
What does Wiki security have to with version control and how do I grant contributors the ability to add new pages?

### ISSUE THREAD

**Issue by StingyJack** [MicrosoftDocs/vsts-docs#5764]
Contributors should have access to this, but there isnt anything in the permissions list that says anything like "can add/edit pages". Its all strictly version control things like "can rename repository" and things like that. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c86f5178-e331-f45e-b60a-f0f3955f7a08
* Version Independent ID: 8a0882a7-8f48-32bb-c741-12976b428c38
* Content: [Manage permissions for READMEs and wiki pages in Azure DevOps - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/project/wiki/manage-readme-wiki-permissions?view=azure-devops)
* Content Source: [docs/project/wiki/manage-readme-wiki-permissions.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/project/wiki/manage-readme-wiki-permissions.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by WilliamAntonRohm** [comment]
@StingyJack -- Andrew, thank you for your feedback. 

@chcomley -- please look into this issue.

**Comment by chcomley** [comment]
Hello there @StingyJack, 
The Contribute permissions is used to cover "can add/edit pages." 
Contributing to a repository is about the ability to add and edit. Please let me know if you need further clarification, thank you!

**Comment by StingyJack** [comment]
@chcomley - I dont see "can add/edit pages" when I am looking at Wiki Security. The user in question is a member of the DevOps contributors group, which per one of the closed threads on this doc, should have access to do this. 

![i dont see add pages](https://user-images.githubusercontent.com/15381181/65995968-7efec880-e464-11e9-8e48-1693e093a3f7.png)

This is the same set of confusing permissions in the screenshot on the doc. Which of these should be toggled to grant the user the ability to edit wiki pages in a team project that has had TFVC for years and only one Git repo added recently?

**Comment by chcomley** [comment]
Hi @StingyJack, **Contribute** is the permission that we check. Is the wiki in question a project wiki or a code wiki? Is the user a **Stakeholder user**? A stakeholder user can't contribute to code wikis...

**Comment by StingyJack** [comment]
Got it. Thank you. Yes the user is/was a stakeholder. I had the impression that stakeholders would not be able to be added to groups like "Contributors", and this user was in that group.
