### ISSUE TITLE
Job Workspace is at the wrong level

### ISSUE THREAD

**Issue by Skintkingle** [MicrosoftDocs/vsts-docs#5766]
the Job schema implies that "workspace" is a member of Job. However the following issue https://developercommunity.visualstudio.com/content/problem/614016/there-is-no-way-how-to-clean-workspace-in-deployme.html (and subsequent resolution) shows that workspace should infact be a member of pool, not of job. The documentation on this page should be updated to reflect this as the indentation for workspace makes it look like it's at the same level as pool, not a member of it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7458d5b2-1bb7-7d87-7ce6-2b0c430b0155
* Version Independent ID: edf5bbd3-a3f0-5426-e985-31290f8afd05
* Content: [YAML schema - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema#job)
* Content Source: [docs/pipelines/yaml-schema.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/yaml-schema.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @vtbassmatt
* Microsoft Alias: **macoope**

**Comment by vtbassmatt** [comment]
Workspace is definitely a concern of the job, not of the pool. That feedback ticket is wrong, and has essentially made "workspace" a no-op because it's part of the agentspec for that pool. I will follow up.
