### ISSUE TITLE
Add to KaTeX users

### ISSUE THREAD

**Issue by ylemkimon** [MicrosoftDocs/vsts-docs#5768]
Hi, I'm a maintainer of @KaTeX.

I'd like to ask if Microsoft would mind adding Azure DevOps logo to [KaTeX user list](https://katex.org/users.html). Do you have a branding guideline on its usage?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fa622358-f5bb-1f5c-177a-081a37b6acef
* Version Independent ID: 72f7fd16-a822-66c8-3a34-8905645ce5f2
* Content: [Markdown syntax for files, widgets, and wikis in Azure DevOps - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/project/wiki/markdown-guidance?view=azure-devops#feedback)
* Content Source: [docs/project/wiki/markdown-guidance.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/project/wiki/markdown-guidance.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by WilliamAntonRohm** [comment]
@ylemkimon -- please look into this avenue:  https://www.microsoft.com/legal/intellectualproperty/trademarks/en-us.aspx

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.

**Comment by ylemkimon** [comment]
@WilliamAntonRohm I don't think the guideline covers our usage. Would it be possible to list your product like:
![image](https://user-images.githubusercontent.com/888148/66253744-ac6ead80-e7a7-11e9-839a-65fdae4a274a.png)
