### ISSUE TITLE
Multi-Select Disabled

### ISSUE THREAD

**Issue by ccoghill** [MicrosoftDocs/vsts-docs#5772]
In step 3, after selecting more than one test case, the Create Suites button becomes disabled now that the new view has rolled out.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c8e2cb79-709d-972b-6747-6d26c965fb2a
* Version Independent ID: d512ea69-a97a-e5ff-a804-6691c5dfe1e6
* Content: [Create test plans and suites - Azure Test Plans](https://docs.microsoft.com/en-us/azure/devops/test/create-a-test-plan?view=azure-devops#feedback)
* Content Source: [docs/test/create-a-test-plan.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/test/create-a-test-plan.md)
* Product: **devops**
* Technology: **devops-test**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by phamilton1212** [comment]
How is this a documentation bug if the functionality used to be there and now it's not?  The ability to create multiple test suites from query results is a huge benefit to users.  It's tedious to have to create suites one at a time from requirements.

Is this going to be fixed or is this functionality being removed from DevOps?

**Comment by Ahetejaz** [comment]
It seems the old and new feature behaves differently. For time being one could go to the right side corner of Azure DevOps services and select the preview features and turn off the new feature for Test Plan. The older view get enabled and could be used to create multiple requirement based test suite at once.

**Comment by steved0x** [comment]
I am reporting this to the test team, and I recommend that you file an issue at https://developercommunity.visualstudio.com/spaces/21/index.html as well (or search there to see if anyone else has reported this, and if so you can upvote their submission). Thank you.
