### ISSUE TITLE
How do I set up a condition to exclude certain types of commits from triggering a build? 

### ISSUE THREAD

**Issue by sujayvsarma** [MicrosoftDocs/vsts-docs#5774]
## This is a bug in the documentation because it is not documented!

My scenario is specific to GitHub-hosted projects.

I have set up an Azure DevOps Pipeline that builds and deploys a GitHub-hosted project to an Azure Web App. But the build fires for anything that is checked in to the branch. For example, if I update the readme.md file! I don't want that to happen.

How do I set up exclusion conditions in Azure DevOps?

NOTE: I do not know any YAML. So if you are providing those as instructions, please provide complete information and the actual statements to put in.

**Comment by msebolt** [comment]
@sujayvsarma Thank you for the feedback.

Please refer to the `Paths` section of [Build triggers](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/triggers?view=azure-devops&tabs=yaml).

There you'll find both descriptions and YAML examples.

**Comment by sujayvsarma** [comment]
So if I have multiple `.md` files in different places, I would need to exclude them one by one? (since I as per the documentation, cannot write `exclude: *.md`).

Also, I don't have a `.yaml` file. I used the Azure DevOps GUI to create the pipeline -- it builds and deploys to an App Service on Azure. So, where would I make these edits to the `.yaml` file?

**Comment by msebolt** [comment]
You should be able to reference them all if you refer to a root folder, such as `/build/*/*.md`.

To use YAML, see [Tasks](https://docs.microsoft.com/azure/devops/pipelines/process/tasks?view=azure-devops&tabs=yaml), though the easiest way is to add the `.yaml` file to your repo and point to it from the Pipelines screen.

![Capture](https://user-images.githubusercontent.com/6675884/66224663-53a9f280-e68b-11e9-92ae-53c3c50f0b95.PNG)
