### ISSUE TITLE
How to delete a classic pipeline?

### ISSUE THREAD

**Issue by Tiberriver256** [MicrosoftDocs/vsts-docs#5778]
Sorry for such a basic question but I can't seem to find anything in the docs here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7336a04e-5b38-d02f-8bba-a55445b2f094
* Version Independent ID: 783c30b3-63b6-da7c-1336-b000bb8b4c66
* Content: [Create your first pipeline - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/create-first-pipeline?view=azure-devops&tabs=tfs-2018-2#feedback)
* Content Source: [docs/pipelines/create-first-pipeline.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/create-first-pipeline.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by msebolt** [comment]
@Tiberriver256 Thank you for the question.

Go to **Pipelines** > **Builds**, select your build and expand the **...** (options) in the right-hand corner.  There you should find the **Delete** option.

Assigning this to the author to address including this in the docs.
