### ISSUE TITLE
Please add explanation of How I can test the 'Closed Date' field for Null or Empty, or.....

### ISSUE THREAD

**Issue by MightyPen** [MicrosoftDocs/vsts-docs#5779]
Please add explanation of How I can test the 'Closed Date' field for Null or Empty, or have article _**explicitly**_ state that no query can directly test a Date field for Null. (Which would be an important feature for the product to add soon.)
Thank you. (MightyPen = GeneMi)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a718268-1105-4def-5f9e-20ea21afc0d7
* Version Independent ID: 0f08fa18-3075-4275-22c7-d5d1c1e260b0
* Content: [Query fields, operators, and macros/variables - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/queries/query-operators-variables?view=azure-devops)
* Content Source: [docs/boards/queries/query-operators-variables.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/boards/queries/query-operators-variables.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by msebolt** [comment]
@MightyPen  Thank you for the feedback.

Assigning this to the author for review.

For feature requests, please use the [Azure Dev Ops Developer Community](https://developercommunity.visualstudio.com/topics/Azure+DevOps.html).

**Comment by KathrynEE** [comment]
@MightyPen - THank you for your inquiry. You can find work items whose Closed Date is Empty by:

Closed Date =  (leave Value field empty). 

I'll update the [Query by date or current iteration](https://docs.microsoft.com/en-us/azure/devops/boards/queries/query-by-date-or-current-iteration?view=azure-devops) topic with this example. Please note that several examples are provided under the Queries > Samples topics.
