### ISSUE TITLE
No documentation article explains exactly how to put parentheses between AND and FIELD NAME, for Boolean OR?

### ISSUE THREAD

**Issue by MightyPen** [MicrosoftDocs/vsts-docs#5781]
No documentation article, about Azure DevOps, explains exactly how to put parentheses between AND and FIELD NAME, for Boolean OR? No TOC title helps in this case.

REQUEST: Please add an article that shows a plain SQL-ish (or WIQL-ish) kinda like the following SQL; plus also shows the corresponding query form with the corresponding checkmarks for the _**parentheses**_ in the WHERE clause:

```
SELECT Column1, Column2
    FROM MyTable
    WHERE
        Column3 = 'a'
        AND
        (Column4 = 'Done'  OR  Column5 = 'Removed')
        AND
        Column6 = 'bb' ;
```

We need your documentation to provide this type of Rosetta stone. Otherwise, this grouping feature in the UI is just not exactly self-explanatory.

The existing article should explicitly link to an article that provides this info:
- `https://docs.microsoft.com/en-us/azure/devops/boards/queries/query-operators-variables?view=azure-devops`

Thank you.  (MightyPen = GeneMi)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a0aaa6c-4ed9-119c-539b-8a54c5ff562f
* Version Independent ID: e4bae907-2938-c870-4798-731b927edc94
* Content: [Organize and view queries, create query folders - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/queries/organize-queries?view=azure-devops)
* Content Source: [docs/boards/queries/organize-queries.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/boards/queries/organize-queries.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by MightyPen** [comment]
Explanation needed for precisely what these little checkboxes do to generate _**parentheses**_ in the query:

![Issue-5781 Azure-DevOps Parentheses](https://user-images.githubusercontent.com/9660758/65840365-f568c280-e2cc-11e9-94a5-835950217334.PNG)

**Comment by msebolt** [comment]
@MightyPen Thank you for the feedback.

Assigning this to the author for review.

**Comment by KathrynEE** [comment]
@MightyPen - I appreciate the feedback and will update topics to clarify the use of parenthesis in the Query UI. To support you in your efforts, I suggest you install the [WIQL query editor extension](https://marketplace.visualstudio.com/items?itemName=ottostreifel.wiql-editor) which will allow you to see the WIQL version of any Query UI entry.  

For example - this Query in the UI:
![image](https://user-images.githubusercontent.com/10856840/65917884-42ac6900-e38d-11e9-87be-37ce37c17610.png)

Yields this WIQL query: 
![image](https://user-images.githubusercontent.com/10856840/65917959-6e2f5380-e38d-11e9-8fef-ded4bd835448.png)

**Comment by Redno-Pnomis** [comment]
Why not keep it concise and have the following clause?

`System.State In (New, Committed, Approved)`
