### ISSUE TITLE
"Show children" removed

### ISSUE THREAD

**Issue by Kodack** [MicrosoftDocs/vsts-docs#5791]
Why would you remove such a handy feature? Now I have to switch between reports and the test plan. Do you talk to users? Was this a common request? 

Since it's not possible to query outcome of testing (Why is still a riddle to me, that's the one and only request PM has...) we could show all TC of a test plan. With that gone, no possibility to easily (copy, paste) bring it to Excel.

So one big wish: either enable a query for Outcome of TC or then bring back "Show children"

Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3c520dee-1218-777e-7405-551623817c03
* Version Independent ID: 82b5d172-ae1a-2b4c-82ac-595cd7609d3c
* Content: [New test plans page - Azure Test Plans](https://docs.microsoft.com/en-us/azure/devops/test/new-test-plans-page?view=azure-devops#feedback)
* Content Source: [docs/test/new-test-plans-page.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/test/new-test-plans-page.md)
* Product: **devops**
* Technology: **devops-test**
* GitHub Login: @harishkragarwal
* Microsoft Alias: **harishkragarwal**

**Comment by msebolt** [comment]
@Kodack  Thank you for the feedback.

Unfortunately, issues here are documentation only.  Perhaps the issue has already been reported [here](https://developercommunity.visualstudio.com/content/problem/747813/show-child-test-cases-from-child-suite-along-with.html)?  

If not, please move this issue to the [Azure Dev Ops Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html) for best traction with the product team.

**Comment by msebolt** [comment]
Closing the the issue now, please comment below if there are any concerns.
