### ISSUE TITLE
How to set default wiki?

### ISSUE THREAD

**Issue by torbennehmer** [MicrosoftDocs/vsts-docs#5792]
I'm missing a way to select the wiki shown by default in case multiple branches are published. In my example I've got a "develop" and a "master" branch. The system displays "develop" by default, but i'd like to present the "master" branch to my users. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c697355f-1e75-27a9-8214-195c26ede4e7
* Version Independent ID: 3f62c207-5449-d7f3-f3b3-82d6fc8f014d
* Content: [Publish new wiki version, select version, or unpublish a wiki in Azure DevOps - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/project/wiki/wiki-select-unpublish-versions?view=azure-devops)
* Content Source: [docs/project/wiki/wiki-select-unpublish-versions.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/project/wiki/wiki-select-unpublish-versions.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by msebolt** [comment]
@torbennehmer Thank you for the question.

When publishing the wiki, you should be able to select the version in the URL.

For master, use:

```
http://devops/DefaultCollection/DevOps/_wiki/wikis/wiki?wikiVersion=GBmaster&pagePath=%2FREADME
```

...instead of a branch-specific version:
```
http://devops/DefaultCollection/DevOps/_wiki/wikis/wiki?wikiVersion=GBtest2&pagePath=%2FREADME
```



Please comment below if this does not address your concern.

**Comment by torbennehmer** [comment]
@msebolt I do understand that, this is exactly, what I did. However, I want to change the branch, that gets shown by default when clicking on the Wiki Link in the menu without explicitly selecting a branch.

What I did:
1. Publish Branch "develop" 
2. Publish Branch "master"

Now if I click the Wiki link or select a general URL without a wikiVersion selector, DevOps shows me the "develop" docs. Instead I want DevOps to show the "master" docs, which effectively represent our release version. 

My question is about this default setting.

**Comment by msebolt** [comment]
@torbennehmer Sorry for the misunderstanding.

However, this is now more of a product feedback issue and will need to be moved to [Azure Dev Ops Developer Community](https://developercommunity.visualstudio.com/topics/Azure+DevOps.html) where the product team can weigh in on the feasibility.

**Comment by torbennehmer** [comment]
@msebolt If there is no option to influence the order, that's fine with me so far, I was looking for that information. Basically: Is the order sorted alphanumerically, is it in the order the wikis were published? I'm missing this information in the docs.
Apart from that I'll raise the issue in the dev community.

**Comment by msebolt** [comment]
@torbennehmer Thank you for moving the issue.  

I'll assign the author for feedback on default order and whether or not this should be added as a note.

**Comment by adramasu** [comment]
Hi,

At the moment we show it in the order in which the versions are published.
