### ISSUE TITLE
Feedback about new Test Plans page

### ISSUE THREAD

**Issue by ebrown424** [MicrosoftDocs/vsts-docs#5793]
I tried to email this to the email address listed above (devops_tools_microsoft.com) but it came back as undeliverable because I'm not allowed to email sadadirs@microsoft.com.  Here is my feedback:
On both the define and execute tabs, could you give us back the ability to expand contract the columns to see more of the test case title?

My usual way of execution is to open a test case, add an attachment that is my screenshots of proof of the test cases passing, and then closing the test case and hitting pass.  Now since everything is split into two tabs I’m not exactly sure how to make this happen.  I tried adding an attachment by clicking the “run” button, but now I can’t find the attachment.  So I finally gave up and went back to the define tab and opened the test case and added an attachment.  My platform is not web-based, and thus we don’t use many of the features VSTS offers.  I use it to add test cases, attach documentation, pass them, or open bugs.  Why can’t I click on a test case in the Execute tab and have it actually open?  I realize this complaint might not be taken seriously since my platform isn’t using your code repository or “run” options, but we’ve been using your software for over 5 years.  I never use the “run” button except to open a bug.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3c520dee-1218-777e-7405-551623817c03
* Version Independent ID: 82b5d172-ae1a-2b4c-82ac-595cd7609d3c
* Content: [New test plans page - Azure Test Plans](https://docs.microsoft.com/en-us/azure/devops/test/new-test-plans-page?view=azure-devops#feedback)
* Content Source: [docs/test/new-test-plans-page.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/test/new-test-plans-page.md)
* Product: **devops**
* Technology: **devops-test**
* GitHub Login: @harishkragarwal
* Microsoft Alias: **harishkragarwal**

**Comment by msebolt** [comment]
@ebrown424  Thank you for the feedback.

Unfortunately, issues here relate to documentation concerns only.

For better traction, please move this issue to [Azure Dev Ops Community](https://developercommunity.visualstudio.com/topics/Azure+DevOps.html) where the product team can offer engagement.

**Comment by msebolt** [comment]
Closing the issue now, please comment below if there are any questions.
