### ISSUE TITLE
Allow for download of source code as artifact

### ISSUE THREAD

**Issue by janabimustafa** [MicrosoftDocs/vsts-docs#5794]
Hello! Would love the ability to have source code be a type of artifact. We have a lot of deployment scripts that are not necessarily  compiled (ps1 files) and I don't want to go through the hassle of publishing an artifact just for the scripts

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 861ce7a5-4fa4-55f1-2c97-46a9cc6a2f66
* Version Independent ID: bdf954b9-9bbe-8b34-b674-71ad8153519d
* Content: [Publish and consume artifacts in pipelines - Azure Pipelines and TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/pipeline-artifacts?view=azure-devops&tabs=yaml#feedback)
* Content Source: [docs/pipelines/artifacts/pipeline-artifacts.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/artifacts/pipeline-artifacts.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @chasewilson
* Microsoft Alias: **phwilson**

**Comment by msebolt** [comment]
@janabimustafa Thank you for the question.

This sounds like more of a feature request then change needed for the documentation.

Please move the issue to **Suggest a Feature** on [Azure DevOps User Voice](https://developercommunity.visualstudio.com/topics/Azure+DevOps.html) for better traction with the product team.

**Comment by msebolt** [comment]
Closing the issue now, please comment below if there are any questions.
