### ISSUE TITLE
GitHub WorkItem Types are not defined

### ISSUE THREAD

**Issue by bobbytreed** [MicrosoftDocs/vsts-docs#5797]
For GitHub WorkItem types there are no System.(Something) references.

Every other linkType has an associated System.LinkType.Hierarchy-Forward, or something.

What is the linktype for GitHub

I'm submitting one in a patchDocument and it keeps erroring.
                patchDocument.Add(new JsonPatchOperation()
                {
                    Operation = Operation.Add,
                    Path = "/relations/-",
                    Value = new
                    {
                        url = payload.Issue.HtmlUrl,
                        rel = "Issue",
                        Title = payload.Issue.Title,

                    }
                });

**Comment by msebolt** [comment]
@bobbytreed  Thank you for the question.

Please refer to [GitHub link types](https://docs.microsoft.com/azure/devops/boards/queries/link-type-reference?view=azure-devops#github-link-types) and comment below if you have questions.

**Comment by bobbytreed** [comment]
@msebolt Refer to the article I read that brought me to this page: Check

Question, as stated above.

The link type for a hierachical link within Azure DevOps are: System.LinkTypes.Hierarchy-Forward
                                                                                              System.LinkTypes.Hierarchy-Reverse 

Which you can specify to the above code sample when creating a work item via code.

The link type for a GitHub Issue is what? Issue? GitHub.Isue? System.Issue?

There is no <DOT> name space type for those issues.

**Comment by msebolt** [comment]
Have you installed the [Azure Boards app](https://docs.microsoft.com/azure/devops/boards/github/install-github-app?view=azure-devops)?

Also, try using the API `https://dev.azure.com/{organization}/_apis/wit/workitemrelationtypes/{relation}?api-version=5.1` to see if the GitHub type is available.

Assigning this to the author now.

**Comment by bobbytreed** [comment]
Thanks.  
Hello @KathrynEE ,
GitHub AzureBoard integration is enabled in my org, but I don't see that GitHub link type available, or else it is hiding as another type (ExternalLink), etc.

I am looking for the oppositeEndReferenceName for GitHub Issue and PullRequest Links.

 https://dev.azure.com/{organization}/_apis/wit/workitemrelationtypes/{relation}?api-version=5.1

Example:
usage                    : workItemLink
editable                 : True
enabled                  : True
acyclic                  : True
directional              : True
singleTarget             : False
topology                 : tree
remote                   : False
isForward                : False
**oppositeEndReferenceName** : Microsoft.XLink.Dependency-Forward

**Comment by KathrynEE** [comment]
@bobbytreed - Hi. Thank you for your inquiry. For link types that connect work items to work items, you have the Reference names as you list above for the Dependency-Forward. These are all listed is this API: https://docs.microsoft.com/en-us/rest/api/azure/devops/wit/work%20item%20relation%20types/list?view=azure-devops-rest-5.0. 

However, for link types that link work items to other artifacts - such as builds, commits, pull requests, and such, there is no corresponding relationship elements. THese are Artifact link types and are listed here in the API: https://docs.microsoft.com/en-us/rest/api/azure/devops/wit/artifact%20link%20types/list?view=azure-devops-rest-5.0. 

If you aren't seeing the GitHub link types in your Link dialog after you've connected it to Azure Boards/Azure DevOps Services, then please check out the resources available to you here: https://developercommunity.visualstudio.com/spaces/21/visual-studio-team-services.html?type=problem - or report a problem.
