### ISSUE TITLE
Need editable diagrams

### ISSUE THREAD

**Issue by brettrowberry** [MicrosoftDocs/vsts-docs#5800]
Need an solution for displaying diagrams in the wiki that can be edited.

**Comment by msebolt** [comment]
@brettrowberry Thank you for the question.

Please refer to [mermaid](https://mermaidjs.github.io/#/) which is finally on the [release schedule](https://docs.microsoft.com/azure/devops/release-notes/features-timeline#features-under-development).

**Comment by jmorleyjones** [comment]
@brettrowberry I have implemented a way to generate plantuml diagrams to be part of the wiki. It would work for mermaid as well. I will write up and share if that will help.

**Comment by brettrowberry** [comment]
@jmorleyjones I would be interested in seeing that

**Comment by jmorleyjones** [comment]
@brettrowberry 

I am doing these instructions while I am on the road without laptop, here are the basics. I will write up a more detailed post next week. This should get you going.

Step 1) follow the steps in this post to configure the build pipeline to enable git check in - https://docs.microsoft.com/en-us/azure/devops/pipelines/scripts/git-commands?view=azure-devops&tabs=yaml

Step 2) configure a Pipeline with 
	A) Install Node Task
	B) NPM Task - install node-plantuml -g
	C) Powershell script Task - 
	 
	git config --global user.email "gituser"
	
	git status
	git branch $Env:BUILD_BUILDNUMBER
	git checkout $Env:BUILD_BUILDNUMBER
	
	$sourceRoot = "\*"
	
	Get-ChildItem $sourceDir -Recurse -Filter "*.puml" |
	 Foreach-Object {  
	     $fileWithPath = $_.Fullname         
	     $png =  ("{0}\{1}.png" -f $_.DirectoryName,$_.Basename )
	     $outputFile = Split-Path $fileWithPath -leaf 
	    $execute = "puml generate $fileWithPath -o $png "; 
	    Invoke-Expression -Command:$execute
	 }
	
	Copy-Item -Path $sourceRoot  -Recurse -Destination $destinationRoot -Container  -exclude *.puml  -Force
	
	git add --all
	
	git commit -m "$Env:BUILD_BUILDNUMBER"
	git checkout master
	git merge $Env:BUILD_BUILDNUMBER -m "$Env:BUILD_BUILDNUMBER"
	git branch -d $Env:BUILD_BUILDNUMBER
	git push origin
	
	
Replace the GitUser in the script above and paste this into the Powershell inline script.
This will build all the puml files and check in the pictures as well. You may want to configure a trigger on a exclusive directory’s etc.

Save the release pipeline and add a puml file in the repo.
For more information on PlantUML head to http://plantuml.com and https://github.com/RicardoNiepel/Azure-PlantUML
Reference the image in a markdown file.

Make the repo a wiki and you should be done.

**Comment by msebolt** [comment]
@jmorleyjones  Thank you for posting your solution.

Also, according to https://github.com/MicrosoftDocs/vsts-docs/issues/5788 mermaid was just released.

Closing the issue now, please comment below if there are any further questions.

**Comment by brettrowberry** [comment]
Thanks!
