### ISSUE TITLE
Conditional Step to skip checkout in azure pipeline?

### ISSUE THREAD

**Issue by hassaan4** [MicrosoftDocs/vsts-docs#5802]
I don't want to perform checkout process again on each run of azure devops pipeline.

**Comment by steved0x** [comment]
@hassaan4 You can use `checkout: none` in your YAML file to avoid syncing the sources, as described here:
https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema#checkout

But it sounds like you want to get the sources the first time, but not on subsequent runs?

If you are using a Microsoft-hosted agent, then you are getting a fresh image each time and so any previously fetched sources aren't available. If you are using a self-hosted agent, you can set `clean: false`, also in the `checkout` step, and if there haven't been any updates to the code, everything shoud be up to date and nothing will be fetched.

Do either of those options sound like they might work for you?
