### ISSUE TITLE
yaml variables in azure-pipelines.yml file

### ISSUE THREAD

**Issue by dazinator** [MicrosoftDocs/vsts-docs#5808]
I am directly updating an azure-pipelines.yml file to add the docker build step. The docs show the yaml that I'd need to add but they don't explain the variables and how they tie up to the acr registry.

For example where do I get the values for these yaml variables:

- $(imageRepository)
- $(dockerRegistryServiceConnection)

I thought I could guess these but my builds keep failing as it seems the docker build is trying to tag the image with an invalid tag name.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45ba2ebe-27c4-111b-18b4-0192d8c3fb3a
* Version Independent ID: f48fdf00-e04f-b406-93f3-20b7fad568be
* Content: [Build and push to Azure Container Registry - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/ecosystems/containers/acr-template?view=azure-devops)
* Content Source: [docs/pipelines/ecosystems/containers/acr-template.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/ecosystems/containers/acr-template.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @shashankbarsin
* Microsoft Alias: **shasb**

**Comment by dazinator** [comment]
And the failing build output is:
>  invalid argument "***/***/uniun:'0.2.0-feature.docker.246'" for "-t, --tag" flag: invalid reference format

**Comment by shashankbarsin** [comment]
@dazinator this particular document is an end-to-end walkthrough. Take any repository containing a Dockerfile as the starting point, create a new pipeline, and in the template recommendations choose the template corresponding to building and pushing images to Azure Container Registry. If these steps are followed, the $(imageRepository) and $(dockerRegistryServiceConnection) variables should get auto-populated.

Closing this issue for now as this is a question and not an issue with the documentation in this particular end-to-end guide.

For guidance on how to add to your pipeline after the end of this how-to guide, please refer to [Docker task](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/docker?view=azure-devops) and [Docker registry service connection](https://docs.microsoft.com/en-us/azure/devops/pipelines/library/service-endpoints?view=azure-devops#sep-docreg).
