### ISSUE TITLE
How to detect an empty array

### ISSUE THREAD

**Issue by poltj18** [MicrosoftDocs/vsts-docs#5811]
I'm struggling to come up with an expression to determine if an array is empty. ex: `dependsOn: []`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77c58a78-a567-e99a-9eb7-62dddd1b90b6
* Version Independent ID: 680a79bc-11de-39fc-43e3-e07dc762db18
* Content: [Expressions - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/expressions?view=azure-devops)
* Content Source: [docs/pipelines/process/expressions.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/expressions.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by juliakm** [comment]
Hi @poltj18, we'll need to check with the product team to find out more about this. For now, you can reach out to the [Azure DevOps Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html), which is monitored by the product team to see if you can get a solid answer there!

**Comment by poltj18** [comment]
@juliakm , Thanks for your reply. I'm interested to hear what they come back with.

**Comment by juliakm** [comment]
This isn't something that is supported. You can make a feature request to the product team at the [Azure DevOps Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html). As a workaround, you might look into solving this at runtime with bash or another scripting language.

**Comment by poltj18** [comment]
@juliakm , Thanks for the update. Unfortunately, I don't think the runtime solution will work for my use case. Specifically looking to allow users to provide a list of tasks via `bringYourOwnSteps: []` which would override my default list of tasks in my YAML template. For now, it seems possible to declare `bringYourOwnSteps: ''` and check if `bringYourOwnSteps` is an empty string. Somewhat surprisingly, the caller can still specify a list of steps.
