### ISSUE TITLE
Miss path delimiter on pipleline variables

### ISSUE THREAD

**Issue by StevenTCramer** [MicrosoftDocs/vsts-docs#5812]
https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml#pipeline-variables
Under Pipeline Variables, the path is missing the backslash.  
`C:\agent_work\1` should be `C:\agent\_work\1`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ffebdc8-521c-44b5-cde4-4abdc1bd6f18
* Version Independent ID: dc0effda-6d93-62aa-64c5-4e6f283b0826
* Content: [Predefined variables - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml#pipeline-variables)
* Content Source: [docs/pipelines/build/variables.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/build/variables.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by msebolt** [comment]
@StevenTCramer Thank you for the feedback.

The article seems to be using `C:\agent_work` as the example for any working folder, see [agent variables](https://docs.microsoft.com/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml#agent-variables), whereas `C:\agent` is the installation folder.

**Comment by msebolt** [comment]
Closing the issue, please comment below if there are any concerns.
