### ISSUE TITLE
Shut out from Wiki

### ISSUE THREAD

**Issue by matthiasburger** [MicrosoftDocs/vsts-docs#5816]
I am project admin and my boss is project collection admin. I changed the permissions for contributors (as I am a member, too) but not for project and project collection admin. Seems like the permissions for contributors are higher than for project admin. Neither my boss as PCA nor me as PA have access to the wiki anymore. 

**edit:** now my boss gave me both, Project Administrator and Project Collection Administrator, but nothing changed. Still not have permissions on wiki

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c86f5178-e331-f45e-b60a-f0f3955f7a08
* Version Independent ID: 8a0882a7-8f48-32bb-c741-12976b428c38
* Content: [Manage permissions for READMEs and wiki pages in Azure DevOps - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/project/wiki/manage-readme-wiki-permissions?view=azure-devops#feedback)
* Content Source: [docs/project/wiki/manage-readme-wiki-permissions.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/project/wiki/manage-readme-wiki-permissions.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by msebolt** [comment]
@matthiasburger  We're sorry your experiencing issues.

This is likely deals with account permissions in which case a member of the product team is needed to assist, our apologies for the inconvenience.

Please move the issue to the [Azure DevOps forum](https://developercommunity.visualstudio.com/topics/Azure+DevOps.html) for further escalation.

**Comment by matthiasburger** [comment]
Thanks you @msebolt  , I asked for help in the forum: https://developercommunity.visualstudio.com/content/problem/759418/shut-out-from-wiki.html - hope we can edit our wiki soon 😆

**Comment by matthiasburger** [comment]
@msebolt I removed "contributors" from my groups and had to remove contributos as parent of other groups and it worked.. still bit confusing why denying for contributors is higher than allowing for project administrator

**Comment by msebolt** [comment]
@matthiasburger Glad you figured it out and thank you for providing the solution.
