### ISSUE TITLE
Please document what "looks like a file path"

### ISSUE THREAD

**Issue by takluyver** [MicrosoftDocs/vsts-docs#5819]
&gt; any key segment that "looks like a file path" will be treated like a file path

"Looks like a file path" is rather vague. It seems from the examples that anything with a `.` in is considered a file path, but it would be good to have it spelled out.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77c20289-dab2-7a6e-4f63-4b30eaff2c71
* Version Independent ID: d75cc196-90c1-8291-9907-ff405bde4edf
* Content: [Pipeline caching - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/caching/?view=azure-devops#feedback)
* Content Source: [docs/pipelines/caching/index.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/caching/index.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @willsmythe
* Microsoft Alias: **wismythe**

**Comment by takluyver** [comment]
Off-topic, but nice work on this docs/issues integration I just used. :+1:

**Comment by damccorm** [comment]
Thanks for the feedback - I'm taking a look!

**Comment by damccorm** [comment]
You're correct that its basically anything containing a `.` - the article reference is being updated to address the issue.
