### ISSUE TITLE
authors-transform.txt issue

### ISSUE THREAD

**Issue by cpboyd** [MicrosoftDocs/vsts-docs#582]
Please note that the result from the PowerShell command is simply a list of usernames.
The instructions are slightly confusing when it explains the format as it does not match.
(i.e. you would get `willys` instead of `willys = willys <willys>`)

This is unlike the Unix command from https://john.albin.net/git/convert-subversion-to-git which actually outputs the specified format (i.e. `willys = willys <willys>`)
`svn log -q | awk -F '|' '/^r/ {sub("^ ", "", $2); sub(" $", "", $2); print $2" = "$2" <"$2">"}' | sort -u > authors-transform.txt`

Further, the PowerShell command seemed to create a text file with Windows encoding rather than UTF-8.
As a result, Git couldn't parse it properly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: edd6cbc8-5e3b-c3a1-4672-d42510cc058b
* Version Independent ID: 8fe81fb5-7c2d-2562-5659-55fccbb3126c
* Content: [Perform the migration from SVN to Git](https://docs.microsoft.com/en-us/vsts/articles/perform-migration-from-svn-to-git?view=vsts#feedback)
* Content Source: [docs/articles/perform-migration-from-svn-to-git.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/articles/perform-migration-from-svn-to-git.md)
* Service: **unspecified**
* GitHub Login: @hkamel
* Microsoft Alias: **hkamel**

**Comment by vova1987** [comment]
+1 to that. 
To make it work in the meantime you can use Git-Bash on windows and enter the exact command suggested by cpboyd - 
svn log -q | awk -F '|' '/^r/ {sub("^ ", "", $2); sub(" $", "", $2); print $2" = "$2" <"$2">"}' | sort -u > authors-transform.txt

**Comment by jiminygreen** [comment]
This also works

svn.exe log --quiet | ? { $_ -notlike '-*' } | % { "{0} = {0} <{0}>" -f ($_ -split ' \| ')[1] } | Select-Object -Unique > authors-transform.txt
