### ISSUE TITLE
Document how to create PR on GitHub via Work item

### ISSUE THREAD

**Issue by pjawesome** [MicrosoftDocs/vsts-docs#5821]
The introduction modal dialog allows users to open a PR on GitHub right after creating an issue as documented here https://www.youtube.com/watch?time_continue=356&v=A3jD3eWvYLE

At the moment though there doesn't seem to be an option to do this same operation beyond that on boarding dialog (e.g. one can only link existing PRs on the GitHub repository).

The use case for this would be to open a PR whenever work starts on a specific work item - is that possible?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c82842d8-dd84-249f-cce1-9e93ecf703bf
* Version Independent ID: eaf9a299-4492-8e09-287a-f10b63d15e29
* Content: [Link GitHub commits and pull requests to work items in Azure Boards - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/github/link-to-from-github?view=azure-devops#feedback)
* Content Source: [docs/boards/github/link-to-from-github.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/boards/github/link-to-from-github.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@pjawesome 	- Thank you for your suggestion. Product feature suggestions, such as this one, should be added here:  https://developercommunity.visualstudio.com/spaces/21/visual-studio-team-services.html?type=idea.
