### ISSUE TITLE
Invalid feedback email

### ISSUE THREAD

**Issue by jd-porter** [MicrosoftDocs/vsts-docs#5825]
The email address in the "Provide feedback" section is bouncing with the following. It's difficult to engage with the ADO team if we can't give feedback as requested. 

--
Your message to sadadirs@microsoft.com couldn't be delivered.

The group sadadirs only accepts messages from people in its organization or on its allowed senders list, and your email address isn't on the list.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3c520dee-1218-777e-7405-551623817c03
* Version Independent ID: 82b5d172-ae1a-2b4c-82ac-595cd7609d3c
* Content: [New test plans page - Azure Test Plans](https://docs.microsoft.com/en-us/azure/devops/test/new-test-plans-page?view=azure-devops#feedback)
* Content Source: [docs/test/new-test-plans-page.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/test/new-test-plans-page.md)
* Product: **devops**
* Technology: **devops-test**
* GitHub Login: @harishkragarwal
* Microsoft Alias: **harishkragarwal**

**Comment by steved0x** [comment]
@jd-porter I have identified the issue with that alias and am getting the team to fix it ASAP, ETA tomorrow. I apologize for the trouble, and I will loop back when the alias is fixed. Thank you for your feedback.

**Comment by steved0x** [comment]
That alias still isn't fixed, but I did learn that the feedback is getting through, even though it appears that it is not. The alias has as its members other aliases, and one of the members of those aliases is the one returning the non-deliverable message. I am keeping this issue open until the alias is fixed and no longer returns that non-deliverable message.

**Comment by stijnherreman** [comment]
@steved0x I just ran into this issue, I guess this was fixed and then broke again?
