### ISSUE TITLE
FIle Matching Patterns not working

### ISSUE THREAD

**Issue by jbeesonnuva** [MicrosoftDocs/vsts-docs#5827]
I'm trying to convert my Download Build Artifact tasks to pipeline artifact downloads and using the same file matching pattern is not working.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b03d67d0-8738-72e6-dbe7-324c1784d4fc
* Version Independent ID: bbb4d774-cd98-3ecb-7ccf-5f49e6f2b425
* Content: [Download Pipeline Artifact task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/download-pipeline-artifact?view=azure-devops#feedback)
* Content Source: [docs/pipelines/tasks/utility/download-pipeline-artifact.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/utility/download-pipeline-artifact.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @willsmythe
* Microsoft Alias: **wismyth**

**Comment by jbeesonnuva** [comment]
Specifically, I need to exclude nested folders.

**Comment by msebolt** [comment]
@jbeesonnuva  Thank you for the feedback.

This however is more of a product issue, then documentation.

Please transfer the issue to the [azure-pipelines-tasks repo](https://github.com/microsoft/azure-pipelines-tasks/issues) and attach the code in question.

**Comment by msebolt** [comment]
Closing this issue now, please comment below if there are any questions.
