### ISSUE TITLE
Doc updates

### ISSUE THREAD

**Issue by onovotny** [MicrosoftDocs/vsts-docs#5835]
This page could use some doc updates:

- `UseDotNet` task instead of `DotNetCoreInstaller`, along with mention of if/when you need to call it multiple times (with sdk vs runtime for multi targeting)
- Explicit example using Coverlet's integration and coverage publishing given that Pipelines won't display anything for .coverage but will display a full report for Coverlet
- Don't need to explicitly call `restore` at the beginning, `dotnet` does that implicitly.
- Publish NuGet package should also show what's needed for an Azure Artifacts feed

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec716c61-248c-75c9-2bc7-262749cc7421
* Version Independent ID: 45f47edc-e800-2c42-416a-92cd93c9e892
* Content: [Build, test, and deploy .NET Core apps - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/ecosystems/dotnet-core?view=azure-devops)
* Content Source: [docs/pipelines/ecosystems/dotnet-core.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/ecosystems/dotnet-core.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by juliakm** [comment]
[This pull request](https://github.com/MicrosoftDocs/vsts-docs/pull/5795) addressed using UseDotNet. Working through the other updates.

**Comment by onovotny** [comment]
@juliakm thanks -- there's one note on that new PR: https://github.com/MicrosoftDocs/vsts-docs/commit/0562c6139e5d1789e69d167e28e4b0bb31e34f70#r35426156
