### ISSUE TITLE
How to use the Docker images on Amazon ECR?

### ISSUE THREAD

**Issue by peterjc123** [MicrosoftDocs/vsts-docs#5837]
Related to https://github.com/MicrosoftDocs/vsts-docs/issues/1929. It is said to use the Docker Registry service connection, but it won't work because the token will expire in 12 hrs. The AWS extension provides the ECR pull task, maybe we can make use of that.

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 3339a2e0-be29-1363-f588-b231d4472c02
* Version Independent ID: 72dd11a3-704d-d0fd-6dfa-cf49f3352de3
* Content: [Container Jobs in Azure Pipelines and TFS - Azure Pipelines](https://docs.microsoft.com/zh-cn/azure/devops/pipelines/process/container-phases?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/process/container-phases.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/container-phases.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @thomps23
* Microsoft Alias: **macoope**

**Comment by munnja001** [comment]
Any update on using this with containers published to ECR?

**Comment by vtbassmatt** [comment]
@shashankbarsin is there any chance you could help me out here? You're a container guru and I have no experience with ECR.

**Comment by vtbassmatt** [comment]
After doing some research, I see now that Amazon ECR has a proprietary mechanism for getting an auth credential that Docker understands. This means that, without feature work in the Azure Pipelines agent, this likely won't work.

If anyone is keen to have this feature, we accept pull requests on https://github.com/microsoft/azure-pipelines-agent. The work would be in converting an AWS service connection (which contains an access key ID and secret access key) to a Docker login using the details [here](https://docs.aws.amazon.com/AmazonECR/latest/userguide/registries.html#registry_auth).

**Comment by markitovtr1** [comment]
Just in case someone reaches this while trying to figure out how to use ECR images as container resources on Azure DevOps:

If you are using self-hosted agents, you can configure AWS credentials on your host and use ECR credential helper ([link here](https://github.com/awslabs/amazon-ecr-credential-helper)). Be careful when configuring this to set it up to agent user (if you set agent to run with root user, you should configure credential helper on /root/.docker/config.json).
