### ISSUE TITLE
Add Requester filter to Release subscriptions

### ISSUE THREAD

**Issue by jjaspenextech** [MicrosoftDocs/vsts-docs#5840]
Using the Azure Pipelines Integration for Slack, I want to be able to subscribe to successful releases that a particular user requested, usually me.

Currently it doesn't have this filter. I added a screenshot of what user I mean from Azure DevOps.
![Release Page](https://user-images.githubusercontent.com/25592908/66160541-5c051d80-e5f8-11e9-9486-8bf7bbb607ff.png)

**Comment by WilliamAntonRohm** [comment]
Thanks for the suggestion! The product teams aren’t always watching this repository, so to make sure it gets in front of them for triage, please [submit your idea]( https://developercommunity.visualstudio.com/content/idea/post.html?space=21) here.
