### ISSUE TITLE
Template parameters cant have a dash "-" in their name.

### ISSUE THREAD

**Issue by Shpetz** [MicrosoftDocs/vsts-docs#5844]
It should be pointed out that unlike pipeline variables, yaml template parameters cant have dashes in their names.

eg. parameters.resource-group wont work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6724abea-bbdc-bf66-ed5e-3214fa6c3e66
* Version Independent ID: 4f8dab21-3f0e-da32-cc0e-1d85c13c0065
* Content: [Templates - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/templates?view=azure-devops#feedback)
* Content Source: [docs/pipelines/process/templates.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/templates.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @vtbassmatt
* Microsoft Alias: **macoope**

**Comment by xoac** [comment]
They can have `-`. You need just to call them like this `${{ parameters['my-variable-with-dashes'] }}`. so parameters[`resource-group`] will work as expected.

**Comment by Shpetz** [comment]
@xoac When I try and call it that way I get this error:
"While parsing a block mapping, did not find expected key"

**Comment by xoac** [comment]
@Shpetz I have use this. [Example](https://github.com/xoac/rust-azure-pipelines/blob/5e730aa4b88d4342dbb6ffe6f687579032228d77/ci/scenarios/check.yml#L11)

**Comment by vtbassmatt** [comment]
@shpetz feel free to post this over in [Developer Community](https://developercommunity.visualstudio.com/spaces/22/index.html) where we can help you troubleshoot. That error sounds unrelated to whether a parameter has a hyphen in it.
