### ISSUE TITLE
Scheduled release triggers: Missing documentation on option "Only schedule releases if the source or pipeline has changed"

### ISSUE THREAD

**Issue by derekbekoe** [MicrosoftDocs/vsts-docs#5846]
When defining a scheduled release trigger, there is a checkbox option for "Only schedule releases if the source or pipeline has changed". The behavior for this option isn't documented on the page.

For example, my question on this checkbox option is: If I have defined multiple artifacts in the releases definition, say GitHub Release (marked as Primary artifact) and Build Artifact, will a release be schedule if only the primary artifact has changed of if _any_ of the artifacts have changed? I am looking for a scheduled release to only be triggered if there is a new GitHub Release and not run if only the Build Artifact has changed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d9e313c5-9120-9172-bc27-c21d10fcd5ae
* Version Independent ID: 1a837182-591f-3cbc-1632-7b50d857b13c
* Content: [Release triggers for stages, branches, and pipelines - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/triggers?view=azure-devops#feedback)
* Content Source: [docs/pipelines/release/triggers.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/release/triggers.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by RoopeshNair** [comment]
Scheduling conditionally on select artifacts isn't possible. The schedule checks following 3 conditions:
- When any of the artifacts changes
- When there are zero releases for a given RD
- When the RD is modified later than the last release is created. For example due to whatever reason if the release is created at 1PM IST, if there are changes to RD post 1PM, then there will be a new release is created.

**Comment by StephenRSkinner** [comment]
My releases schedule even when no artifacts have changed. This doesn't appear to work the way you've described.

**Comment by rakol-ms** [comment]
@StephenRSkinner which artifacts are you using for your scheduled releases?
