### ISSUE TITLE
Information in Prequisite is bit misleading

### ISSUE THREAD

**Issue by vijay-gowda** [MicrosoftDocs/vsts-docs#5847]
The point below in pre-requisite indicates that a user with Basic or Stakeholder license have permission to change process by default.
"Users granted Basic or Stakeholder access are automatically granted permission to create, edit, and delete processes,...."

Another point below states, the user needs to be part of the Project Collection Administrators group, 
"To create, delete or edit a process, you must be a member of the Project Collection Administrators group, or have...."

Which one is true?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4107b23a-ba0a-5a1b-b689-072717cfe8ec
* Version Independent ID: 1ed09ce9-be9b-6146-9cb8-a2a50e12a3c2
* Content: [Add a custom rule to a work item type - Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/organizations/settings/work/custom-rules?view=azure-devops#feedback)
* Content Source: [docs/organizations/settings/work/custom-rules.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/settings/work/custom-rules.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@vijay-gowda - Apologies for the confusion, and thank you for your feedback. The second point is true and I'll be updating the article to remove the following statement - which is not accurate: 
> _Users granted Basic or Stakeholder access are automatically granted permission to create, edit, and delete processes, change the process of a project, and administer process permissions. To change these defaults, you can restrict access by setting permissions at the organization level and set permissions explicitly._
