### ISSUE TITLE
Не корректно работают ссылки типа "Hyperlink"

### ISSUE THREAD

**Issue by Iloer** [MicrosoftDocs/vsts-docs#5848]
Azure DevAps Server 2019 update1.
WorkItem - ChangeRequest
В WebLayout добавлен раздел:
            &lt;Group Label="Hyperlink"&gt;
              &lt;Control Type="LinksControl" Name="Hyperlink"&gt;
                &lt;LinksControlOptions&gt;
                  &lt;ListViewOptions GroupLinks="false"&gt;&lt;/ListViewOptions&gt;
                  &lt;LinkFilters&gt;
                    &lt;WorkItemLinkFilter Type="Hyperlink" /&gt;
                  &lt;/LinkFilters&gt;
                &lt;/LinksControlOptions&gt;
              &lt;/Control&gt;
            &lt;/Group&gt;
Проблемы:
1) Совместно с типом "Hyperlink" в разделе отобразились и все остальные ссылки.
2) Кнопка "Add link" отображает форму добавления ссылок, но список типов - пуст

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d9818350-b7e0-7789-95b4-77d5c5dd472e
* Version Independent ID: e4318c77-d744-e056-fc2a-4aa879be22cc
* Content: [Link types reference - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/queries/link-type-reference?view=azure-devops-2019#feedback)
* Content Source: [docs/boards/queries/link-type-reference.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/boards/queries/link-type-reference.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by msebolt** [comment]
**Issue (Translated)**

Links like "Hyperlink" do not work correctly
Together with the "Hyperlink" type, all other links were displayed in the section.
The "Add link" button displays the form for adding links, but the list of types is empty.

@Iloer  Thank you for the feedback.

Unfortunately changes here are for documentation only, please move this issue to **Report a Problem** in the [Azure DevOps community](https://developercommunity.visualstudio.com/spaces/21/index.html).

**(Translated)**

Спасибо за ваш отзыв!

К сожалению, изменения внесены только в документацию. Переместите эту проблему в раздел **Сообщить о проблеме** в сообществе разработчиков Azure.

**Comment by msebolt** [comment]
Closing the issue now, please comment below if there are any questions.
