### ISSUE TITLE
Team Services Accounts tags

### ISSUE THREAD

**Issue by aaronboock** [MicrosoftDocs/vsts-docs#585]
Can tags be applied to Team Services Accounts from the Azure portal?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 52303279-70fd-a0f6-cc6f-96bf73ed8c32
* Version Independent ID: cb30fbe3-b069-2665-d8da-9f714a23290a
* Content: [VSTS billing FAQ](https://docs.microsoft.com/en-us/vsts/billing/vsts-billing-faq?view=vsts)
* Content Source: [docs/billing/vsts-billing-faq.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/billing/vsts-billing-faq.md)
* Service: **unspecified**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
@aaronboock  Thanks for sending your question - I've updated the Billing FAQ for others' reference and it should be live sometime this afternoon. To answer your question, no, tags cannot be applied to Ream Services Accounts from the Azure portal. However this feature is on our backlog to add in the future. If you wouldn't mind sharing, what are you using tags for and how would it be valuable to tag the VSTS account in the Azure portal? Thanks!

**Comment by JuniorIce** [comment]
@aaronboock I’d love to get a better picture of what you need to do and see how we might be able to enable this in the future. Can you contact me (james.rice@microsoft.com<mailto:james.rice@microsoft.com>) and we can get together for a discussion over Skype?

**Comment by chcomley** [comment]
@JuniorIce, checking to see whether you have seen Aaron's response? Aaron, please contact James at james.rice@microsoft.com. Thank you.

**Comment by JuniorIce** [comment]
Aaron, would love to chat with you in more detail about your needs if you’re available—can you provide your email address?

**Comment by aaronboock** [comment]
Regards,

Aaron Boock
Hennepin County - IT Systems Engineer
300 South 6th Street
Minneapolis, MN 55487-0005
612.596.0205 | Office
612.290.2089 | Mobile
aaron.boock@hennepin.us<mailto:aaron.boock@hennepin.us>


Disclaimer: If you are not the intended recipient of this message, please immediately notify the sender of the transmission error and then promptly delete this message from your computer system.
