### ISSUE TITLE
Can we not download artefacts locally to systems like we could from the Summary Page without the Multi-Stage preview on

### ISSUE THREAD

**Issue by nishantvas** [MicrosoftDocs/vsts-docs#5851]
without the multi-stage pipeline preview on, we're able to download the artefacts from the Summary page of the pipeline to our systems and view things like test results that we have stored.
However, with the preview on, I don't see the option to download the artefacts to the local system using the GUI

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7458d5b2-1bb7-7d87-7ce6-2b0c430b0155
* Version Independent ID: edf5bbd3-a3f0-5426-e985-31290f8afd05
* Content: [YAML schema - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema#feedback)
* Content Source: [docs/pipelines/yaml-schema.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/yaml-schema.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @vtbassmatt
* Microsoft Alias: **macoope**

**Comment by vtbassmatt** [comment]
This isn't a doc bug, it's a product bug - could you file it over at [Developer Community](https://developercommunity.visualstudio.com/spaces/22/index.html)? Thanks!
