### ISSUE TITLE
backlogs

### ISSUE THREAD

**Issue by EldarAliev** [MicrosoftDocs/vsts-docs#5852]
Hello!
How to create several backlogs as in the picture? https://docs.microsoft.com/en-us/azure/devops/boards/sprints/_img/assign-items-sprint/backlog-team-selector-s155.png?view=azure-devops

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eca2985c-878e-ee5d-9df3-ad5755abd873
* Version Independent ID: cf61abed-bd24-817f-7d28-f9f8a0002926
* Content: [What tasks do backlogs, boards, & plans support? - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/backlogs/backlogs-boards-plans?view=azure-devops#feedback)
* Content Source: [docs/boards/backlogs/backlogs-boards-plans.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/boards/backlogs/backlogs-boards-plans.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by msebolt** [comment]
@EldarAliev  Thank you for the question.

Each **Backlog** is considered a one of the tools per [Team](https://docs.microsoft.com/azure/devops/organizations/settings/about-teams-and-settings?toc=%2Fazure%2Fdevops%2Fboards%2Ftoc.json&bc=%2Fazure%2Fdevops%2Fboards%2Fbreadcrumb%2Ftoc.json&view=azure-devops#each-team-gets-their-own-set-of-tools), so you will need to create multiple teams. 

Also refer to [Backlogs overview](https://docs.microsoft.com/azure/devops/boards/backlogs/backlogs-overview?view=azure-devops#backlog-configuration).

**Comment by EldarAliev** [comment]
@msebolt thanks for the answer.

with this question it is clear.
Tell me, please, how can I transfer the tasks between these teams?

**Comment by msebolt** [comment]
@EldarAliev  you're welcome.

Please see [this post](https://developercommunity.visualstudio.com/content/problem/399900/bulk-move-backlog-items-and-tasks-to-another-team.html) that uses a screen capture on bulk task migration.

**Comment by EldarAliev** [comment]
@msebolt thanks again )
