### ISSUE TITLE
The descriptions for *Basic and Basic + Test Plans seems a bit mixed up

### ISSUE THREAD

**Issue by freljung** [MicrosoftDocs/vsts-docs#5855]
Basic has description: "... and to users for whom you are paying for Basic + Test Plans access in an organization." and Basic + Test Plans has description: "... and to users for whom you're paying for Basic access in an organization.". This seems mixed up to me.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8db47b85-e178-7969-40d3-3fa83aa3fb54
* Version Independent ID: a78e453b-4b8f-c885-42ee-8a9d9979f345
* Content: [What are access levels? What access levels are supported? - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/security/access-levels?view=azure-devops#feedback)
* Content Source: [docs/organizations/security/access-levels.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/security/access-levels.md)
* Product: **devops**
* Technology: **devops-security**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by freljung** [comment]
Well that got added a bit sooner then expected. Anyhoo my point I was going to make was that Basic has description: "... and to users for whom you are paying for Basic + Test Plans access in an organization." and Basic + Test Plans has description: "... and to users for whom you're paying for Basic access in an organization.". This seems mixed up to me.

**Comment by KathrynEE** [comment]
@freljung - Agree that this is confusing. I will update the article to remove the confusion.
