### ISSUE TITLE
Copying Dashboards

### ISSUE THREAD

**Issue by powerdude** [MicrosoftDocs/vsts-docs#5857]
It would be nice if it was possible to copy/duplicate dashboards between/to other teams.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d3d9f6cf-89b6-a0e3-0a37-f23446ede457
* Version Independent ID: 988af21a-7ee0-66b4-0fac-07360b8be17d
* Content: [Add, rename, delete, and manage team dashboards - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/report/dashboards/dashboards?view=azure-devops#feedback)
* Content Source: [docs/report/dashboards/dashboards.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/report/dashboards/dashboards.md)
* Product: **devops**
* Technology: **devops-analytics**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by msebolt** [comment]
@powerdude  Thank you for the feedback.

Unfortunately changes here are for documentation only.

Please use the [Azure Dev Ops community](https://developercommunity.visualstudio.com/spaces/21/index.html) where your request can be voted on and responded to by the product team.

**Comment by msebolt** [comment]
Closing this issue now, please comment below if there are any questions.
