### ISSUE TITLE
Code Highlighting copy button missing

### ISSUE THREAD

**Issue by mick-anderson24** [MicrosoftDocs/vsts-docs#5861]
I am working on wiki's within Azure DevOps in a tfvc instance.  When i add a code block with the 3 ```  the copy button that is shown in the docs on this page isn't visible.  Is there a bug with this or is it not supposed to show up?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fa622358-f5bb-1f5c-177a-081a37b6acef
* Version Independent ID: 72f7fd16-a822-66c8-3a34-8905645ce5f2
* Content: [Markdown syntax for files, widgets, and wikis in Azure DevOps - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/project/wiki/markdown-guidance?view=azure-devops#feedback)
* Content Source: [docs/project/wiki/markdown-guidance.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/project/wiki/markdown-guidance.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @mick-anderson24, I'm confirming this behavior with the PM and will get back to you as soon as possible. Thanks for reaching out.

**Comment by chcomley** [comment]
Hi @mick-anderson24, We don't have copy button functionality for wiki. The copy button you see in the doc is docs.microsoft.com functionality. I'm closing this issue, but please do let me know if you have any further questions by @ mentioning me. Thanks!

**Comment by SudoCerb** [comment]
It's really unfortunate that this functionality hasn't made it to the wiki - I think it could be really valuable

**Comment by chcomley** [comment]
Hi @SudoCerb, I understand your frustration. I searched in the Developer Community and discovered a feature request for this functionality. It's currently "under review," so I recommend upvoting it! Please go to the [Developer Community item](https://developercommunity.visualstudio.com/search?space=21&q=wiki+code+copy). Thanks!
