### ISSUE TITLE
azurePowerShellVersion is mandatory argument

### ISSUE THREAD

**Issue by ChendrayanV** [MicrosoftDocs/vsts-docs#5868]
#azurePowerShellVersion: 'OtherVersion' # Optional. Options: latestVersion, otherVersion 
This needs to be changes as REQUIRED - Change is argument section as well.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fb215324-b1a0-93b5-5022-4bcc7da93bb7
* Version Independent ID: 9eb2977b-ac34-9d53-670e-04fa027bc8e4
* Content: [Azure PowerShell task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-powershell?view=azure-devops)
* Content Source: [docs/pipelines/tasks/deploy/azure-powershell.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/deploy/azure-powershell.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by M0ns1gn0r** [comment]
It's so irritating that this **requried** argument 
1. Doesn't have a meaningful default of 'latestVersion'.
1. Is not on the top => too easy to overlook it and get mysterious "Could not find the module path with given version.".
