### ISSUE TITLE
Missing information...

### ISSUE THREAD

**Issue by frozenskys** [MicrosoftDocs/vsts-docs#5869]
The title of this page is Set up *Active Directory* or Azure Active Directory - yet non of the information or links refer to normal Domain Active Directory. I understand that Microsoft is keen to push Azure, but please don't leave those of us who are mid-move to the cloud without the information we need to use your products.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 274f9b5a-b567-a123-b1cd-b0d68db17e74
* Version Independent ID: f6a0c699-de26-747d-7a80-46667f142b45
* Content: [Set up Active Directory or Azure Active Directory for Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/security/setup-ad-aad?view=azure-devops&viewFallbackFrom=azure-devops-2019%20and#feedback)
* Content Source: [docs/organizations/security/setup-ad-aad.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/security/setup-ad-aad.md)
* Product: **devops**
* Technology: **devops-security**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@frozenskys 	- Thank you for the feedback. I'll correct the article accordingly.

**Comment by KathrynEE** [comment]
@frozenskys - I've updated the article to remind users to select the version for Azure DevOps that they are interested in. If you select an on-premises version - you'll see content for the Active Directory Domain Services.  If you believe that there is still missing information, please reopen this issue and add a comment.


 **Important**

To view the content available for your platform, make sure that you select the correct version of this article from the version selector which is located above the table of contents.

Content version selector
![image](https://user-images.githubusercontent.com/10856840/66784943-b459dc00-ee90-11e9-8493-2158fd77096a.png)
