### ISSUE TITLE
Missing information about guest users

### ISSUE THREAD

**Issue by emarion0** [MicrosoftDocs/vsts-docs#587]
[Customer stated that in order to disconnect, the user doing the disconnect needs to be a guest in the tenant but added as a member through powershell. They were not able to get this to function without that step]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 33530bb1-f68e-4361-df9d-a02b73f00f4f
* Version Independent ID: 25d0042d-4002-7640-5e8e-17fea8910d2e
* Content: [Disconnect your VSTS account from your Azure AD](https://docs.microsoft.com/en-us/vsts/accounts/disconnect-account-from-aad?view=vsts)
* Content Source: [docs/accounts/disconnect-account-from-aad.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/accounts/disconnect-account-from-aad.md)
* Service: **unspecified**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
@emarion0 We appreciate you sharing your customer's experience - a fix is process!
