### ISSUE TITLE
Include "Building DevOps extension using Blazor" in  "Develop extensions" VSTS documentation dated 2016

### ISSUE THREAD

**Issue by tomview** [MicrosoftDocs/vsts-docs#5872]
There have been requests in past few months to support building DevOps Extensions using Asp.Net.Core/Blazor.

-  [Building Blazor DevOps extensions](https://developercommunity.visualstudio.com/content/problem/704085/building-blazor-devops-extensions.html)

- [Develop Azure DevOps Extensions using Blazor](https://developercommunity.visualstudio.com/idea/425875/develop-azure-devops-extensions-using-blazor.html)

Blazor is seen at **.NET Conf 2019** as the Microsoft future Web technology aligned for .NET developers

As a .NET developer and a true believer of the Microsoft Azure DevOps, I think I could speak for others that we dream to apply our creativity to improve our DevOps experience and productivity by developing AND sharing DevOps extensions with greater efficiency using FULL .NET instead of the recommended Javascript/NodeJs - that is ONLY **PARTLY** ALIGNED with the Microsoft future of Modern Web technology.

It is timely to update the documentation on [**Develop extensions**](https://docs.microsoft.com/en-us/azure/devops/extend/?toc=%2Fazure%2Fdevops%2Fextend%2Ftoc.json&bc=%2Fazure%2Fdevops%2Fextend%2Fbreadcrumb%2Ftoc.json&view=azure-devops) dated 2016 to include a tutorial on **how to develop DevOps Extensions using Blazor technology**.

**Comment by chcomley** [comment]
Hi @tomview, Thanks for your suggestion. Our extension docs are definitely in need of a makeover. I've created a user story for my backlog and will keep you updated. Thanks!

**Comment by chcomley** [comment]
Hi @tomview, I still have a user story in "proposed" state, marked for "future" iteration, for creating this content. I'm going to close this issue, however I'll link the PR to this issue and alert you when it's live. I'm unsure of when this will occurr, likely in the new year. Thanks very much for your suggestion!

**Comment by MarkKennedyAveva** [comment]
@chcomley  By saying the extension docs are in need of a makeover, are you saying this capability currently exists but it's just not documented yet?

**Comment by chcomley** [comment]
Hi @MarkKennedyAveva, 
As I understand it, Blazor Server is officially supported in .NET Core 3.0. Blazor Client (Blazor Webassembly of .NET Core 3.0) is slated for May 2020. Here's some more information from the Developer Community and what we currently have documented for building Blazor apps: 

- https://developercommunity.visualstudio.com/idea/425875/develop-azure-devops-extensions-using-blazor.html

- https://developercommunity.visualstudio.com/content/problem/704085/building-blazor-devops-extensions.html

- [Get started with ASP.NET Core Blazor](https://docs.microsoft.com/en-us/aspnet/core/blazor/get-started?view=aspnetcore-3.0&tabs=visual-studio)

Thanks and have a nice day.

**Comment by MarkKennedyAveva** [comment]
@chcomley One of those links is to a question where I was the original poster. Both of the first two links are questions regarding how to do it, NOT documentation on how to do it. The question is, _can_ we build DevOps custom extensions using Blazor? If not, will that be developed and if so, will there be documentation provided?

**Comment by chcomley** [comment]
@MarkKennedyAveva, 
**Your question:** Can we build DevOps custom extensions using Blazor? If not, will that be developed and if so, will there be documentation provided?
**Answer:** No. There's nothing on the roadmap that refers to its development. The user story that I created for this is closed.  I recommend submitting a new [feature request](https://developercommunity.visualstudio.com/spaces/21/index.html). Select the **Suggest a feature** dropdown menu, and then select **.NET**, rather than Azure DevOps. 
Sorry for any confusion on this.

**Comment by cveld** [comment]
It should theoretically be possible to create web-based Azure DevOps Extensions with ASP.NET Core Blazor.  Additionally, with Blazor WebAssembly you would not even be required to bring your own server. All required assets could be hosted by the Azure DevOps platform.

You will need to create extensive JavaScript interop code though, to really integrate with the SDK which is currently only provided for JavaScript.

**Comment by MaciekWin3** [comment]
If any of you are still interested in creating an Azure DevOps extension using Blazor, please check out my project designed to assist you: https://github.com/MaciekWin3/azure-devops-blazor-extension. I hope you find it appealing!

**Comment by MaciekWin3** [comment]
If any of you are still interested in creating an Azure DevOps extension using Blazor, please check out my project designed to assist you: https://github.com/MaciekWin3/azure-devops-blazor-extension. I hope you find it appealing!
