### ISSUE TITLE
Needs an example of using an output variable from a previous job in a custom condition

### ISSUE THREAD

**Issue by buck-mbeer** [MicrosoftDocs/vsts-docs#5873]
The syntax for using output parameters from previous job in conditions is not exactly as one might expect, as confirmed in this issue: https://developercommunity.visualstudio.com/content/problem/760780/in-multi-job-pipelines-job-variable-resolution-occ.html It's probably worth adding an example to the Conditions page of how to use output variables this way.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f151218-9a11-0078-e038-f96198a76143
* Version Independent ID: 09c4d032-62f3-d97c-79d7-6fbfd89910e9
* Content: [Conditions - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/conditions?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/process/conditions.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/conditions.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by juliakm** [comment]
@buck-mbeer You can see our updated doc [here](https://docs.microsoft.com//en-us/azure/devops/pipelines/process/conditions?view=azure-devops&tabs=yaml#use-the-output-variable-from-a-job-in-a-condition-in-a-subsequent-job).

**Comment by buck-mbeer** [comment]
Looks great, thanks for the update @juliakm
