### ISSUE TITLE
Re-creating a feed does not free up the name immediately

### ISSUE THREAD

**Issue by shubham90** [MicrosoftDocs/vsts-docs#5880]
Artifact feed's name does not free up after deleting it. It goes in the recycle bin and name frees up once it is permanently deleted from the recycle bin. Right now, there is no way to permanently delete feed from the UI.
While we work on the UI roll out for this feature, please use the following script to permanently delete the feed from recycle bin to free up the name immediately. Please make sure that you have manage access to feed/packaging.

[permanentDeleteFeed.zip](https://github.com/MicrosoftDocs/vsts-docs/files/3700118/permanentDeleteFeed.zip)

Please run the attached script and provide the correct org name, project name(if any), feed name and PAT to permanent delete the feed from recycle bin. If the feed was not project-scoped, then leave the field blank.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1475397e-1e4f-e51d-8cd8-29553112a059
* Version Independent ID: 4a8053f8-1ca5-a2aa-89ac-bbe0b2a6128f
* Content: [Key concepts for Azure Artifacts](https://docs.microsoft.com/en-us/azure/devops/artifacts/artifacts-key-concepts?view=azure-devops)
* Content Source: [docs/artifacts/artifacts-key-concepts.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/artifacts/artifacts-key-concepts.md)
* Product: **devops**
* Technology: **devops-artifacts**
* GitHub Login: @chasewilson
* Microsoft Alias: **phwilson**

**Comment by msebolt** [comment]
@shubham90  Thank you for the feedback, assigning the author for review.

**Comment by shubham90** [comment]
I have attached a temporary solution to this issue in the description. Please run the attached script and provide the correct org name, project name(if any), feed name and PAT to permanent delete the feed from recycle bin.

**Comment by shubham90** [comment]
This should not be fixed. We have rolled out the UI where you can access deleted feeds and perform restore and/or permanent delete operations on the feed. To free up the feed name, please permanent delete the feed from the feed settings page.
