### ISSUE TITLE
Preserve Target Timestamp fails

### ISSUE THREAD

**Issue by IrisChang0119** [MicrosoftDocs/vsts-docs#5884]
I used this task after the MSBuild task finished.
But I found it is failed.

The task log :
Problem applying the timestamp: undefined

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 81f02378-b85b-d3a4-d3c8-f07d935367da
* Version Independent ID: fab57f76-35d2-4024-6f7f-1740d7b24743
* Content: [Copy Files task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/copy-files?view=azure-devops&tabs=yaml#feedback)
* Content Source: [docs/pipelines/tasks/utility/copy-files.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/utility/copy-files.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @vtbassmatt
* Microsoft Alias: **macoope**

**Comment by vtbassmatt** [comment]
This is not a doc bug, it's a product issue. Please file it on [Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html).
