### ISSUE TITLE
Update the screenshots-

### ISSUE THREAD

**Issue by INPVIR** [MicrosoftDocs/vsts-docs#5885]
Request to update new UI screenshots to avoid confusion to the end users. New name of security now is Permissions

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 07738454-4b1a-eff5-6c16-69e963ab2663
* Version Independent ID: a63f1dad-0378-5ce3-97e9-ec66afffb206
* Content: [Add users to a team or project](https://docs.microsoft.com/en-us/azure/devops/organizations/security/add-users-team-project?view=azure-devops#feedback)
* Content Source: [docs/organizations/security/add-users-team-project.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/security/add-users-team-project.md)
* Product: **devops**
* Technology: **devops-security**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by msebolt** [comment]
@INPVIR  Thank you for the feedback, assigning this to the author.

**Comment by KathrynEE** [comment]
@INPVIR - Thank you for the feedback. I'll be updating the article screenshots to avoid confusion within the next 2 days.
