### ISSUE TITLE
Use drag and drop to nest test suites is no longer working

### ISSUE THREAD

**Issue by alejandraneolopan** [MicrosoftDocs/vsts-docs#5889]
Test suites are not able to be included in an already existing test suite.
User has to create a new test suite and is not able to move a test suite in another branch.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3c520dee-1218-777e-7405-551623817c03
* Version Independent ID: 82b5d172-ae1a-2b4c-82ac-595cd7609d3c
* Content: [New test plans page - Azure Test Plans](https://docs.microsoft.com/en-us/azure/devops/test/new-test-plans-page?view=azure-devops#feedback)
* Content Source: [docs/test/new-test-plans-page.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/test/new-test-plans-page.md)
* Product: **devops**
* Technology: **devops-test**
* GitHub Login: @harishkragarwal
* Microsoft Alias: **harishkragarwal**

**Comment by msebolt** [comment]
@alejandraneolopan Thank you for the feedback.

Issues here are only be applied to the documentation.  Can you please move this issue over to the [Azure DevOps forums](https://developercommunity.visualstudio.com/topics/Azure+DevOps.html)?  

There you'll receive an assessment directly from the product team.

**Comment by WilliamAntonRohm** [comment]
It looks like you've encountered an issue with the product itself, rather than an issue with the documentation. To make sure it gets in front of the right people, please [submit your feedback here]( https://developercommunity.visualstudio.com/content/problem/post.html?space=21).
