### ISSUE TITLE
Are there any options for controlling the results that are displayed?

### ISSUE THREAD

**Issue by StingyJack** [MicrosoftDocs/vsts-docs#589]
Clearly changing the query will control the results that are found, but I'm trying to find a way to show or hide some of those found results. 

A specific example of one that I encounter often from PM's is, if we want to see tasks that belong to a PBI or Bug that has a specific range of Stack Rank values, we can create that by a `workitems and direct links query` type. 

However we are querying for tasks, so the tasks are all that we want to see, but instead a nested PBI or BUG is in the display for every task displayed.  Can this extra info be filtered out?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a595239-37c5-6409-7c55-fb66ca64247e
* Version Independent ID: 0c7a3fbe-c450-869b-27f2-7c45115bddc7
* Content: [New queries experience - VSTS & TFS](https://docs.microsoft.com/en-us/vsts/work/track/queries-preview?view=vsts)
* Content Source: [docs/work/track/queries-preview.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/work/track/queries-preview.md)
* Service: **unspecified**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@StingyJack - Thank you for your inquiry. You can filter queries as described in this topic: https://docs.microsoft.com/en-us/vsts/work/backlogs/filter-backlogs?toc=/vsts/work/track/toc.json&bc=/vsts/work/track/breadcrumb/toc.json&view=vsts. You should be able to filter the query to show only those work item types you select.

**Comment by StingyJack** [comment]
Its not a backlog query, does that matter?

**Comment by StingyJack** [comment]
I can only filter on Tag Values 
![image](https://user-images.githubusercontent.com/15381181/39152320-f80c352a-4715-11e8-84a3-7ac6024eb740.png)
