### ISSUE TITLE
What is the max field length for System.Title?

### ISSUE THREAD

**Issue by StingyJack** [MicrosoftDocs/vsts-docs#5890]
There is a max length because the API is telling me its too long. I need to know what that max length is.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6859c579-3383-e4b7-366e-69f49a8bd1b6
* Version Independent ID: 5b7af784-0698-b77a-342f-252986038e92
* Content: [Query by title, ID, or rich-text fields - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/queries/titles-ids-descriptions?view=azure-devops)
* Content Source: [docs/boards/queries/titles-ids-descriptions.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/boards/queries/titles-ids-descriptions.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by msebolt** [comment]
@StingyJack  Thank you for the question.

Work item naming has a restriction of 128 Unicode characters, refer to [Naming restrictions](https://docs.microsoft.com/azure/devops/organizations/settings/naming-restrictions?view=azure-devops#work-items-work-item-types-and-customizations).

If you're finding different results, please comment below.

**Comment by StingyJack** [comment]
128 is for fields I add.

256 is what I could eventually stuff in it by pasting 1234567890 into the title bar until it stopped accepting input.

**Comment by msebolt** [comment]
Sounds good, thank you for posting your results.
