### ISSUE TITLE
Clarification needed on throttling specifications

### ISSUE THREAD

**Issue by prolitaaron** [MicrosoftDocs/vsts-docs#5894]
This line is a bit unclear:

"Their personal usage exceeds 200 times the consumption of a typical user within a (sliding) five-minute window."

That seems to indicate that if a user were to wait to do heavy work until a less-usage-heavy time period (such as overnight), they may actually be MORE likely to run into throttling because the "typical user" of the Azure DevOps at that time is much less active.  I imagine it LIKELY means "typical user" is some generic, any-time sense, but this feels like it means if the user is exceeding the average user IN THAT FIVE MINUTES.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5c2c2355-60a5-d53f-2c72-8f032c1b8cf2
* Version Independent ID: 711bf22d-99c9-51b2-382c-e095bdb2c37f
* Content: [Resource limits & constraints - Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/integrate/concepts/rate-limits?view=azure-devops#feedback)
* Content Source: [docs/integrate/concepts/rate-limits.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/integrate/concepts/rate-limits.md)
* Product: **devops**
* Technology: **devops-ecosystem**
* GitHub Login: @chcomley
* Microsoft Alias: **kaelli**

**Comment by msebolt** [comment]
@prolitaaron Thank you for the feedback, assigning this to the author for review.

**Comment by roofers** [comment]
Hi @prolitaaron - The consumption limits are fixed based on an average users usage. It doesn't change during low times. Therefore, the threshold is the same whether you exceed it during peek times or after hours.

**Comment by chcomley** [comment]
Thanks @roofers. Hi @prolitaaron, I'll be closing this issue. Please @ mention me if you have any further questions. Thank you!
