### ISSUE TITLE
searchPatternPush example to negate a pattern is incorrect

### ISSUE THREAD

**Issue by Tankatronic** [MicrosoftDocs/vsts-docs#5895]
`searchPatternPush` states the following

>The pattern to match or path to nupkg files to be uploaded. Multiple patterns can be separated by a semicolon, and you can make a pattern negative by prefixing it with `-:`. Example: `**/*.nupkg;-:**/*.Tests.nupkg`."

Expected Behavior:

The pattern negated with `-:[pattern]` will prevent packages matching the specified `[pattern ]` from being pushed.

Actual Behavior:

The pattern negated with `-:[pattern]` is not ignored. To negate a pattern you must use `!` instead of `-:`. Ex: `![pattern]`

I have not tested this with the `searchPatternPack` argument.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d1d9884-19f7-592b-f47c-8cf100639ff0
* Version Independent ID: 555c3826-60d9-2589-54af-850efbfbb13a
* Content: [.NET Core CLI task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/dotnet-core-cli?view=azure-devops#feedback)
* Content Source: [docs/pipelines/tasks/build/dotnet-core-cli.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/build/dotnet-core-cli.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @pulkitaggarwl
* Microsoft Alias: **puagarw**

**Comment by msebolt** [comment]
@Tankatronic  Thank you for the feedback, assigning this to the author for review.

**Comment by damccorm** [comment]
Thanks for the feedback - I'm taking a look!

**Comment by damccorm** [comment]
Thank you for your feedback. 
The article reference is being updated to address the issue.
