### ISSUE TITLE
Does the app work for more than one project?

### ISSUE THREAD

**Issue by quiarneto** [MicrosoftDocs/vsts-docs#5896]
Hello, Could you help me?
In my Azure DevOps organization I have four projects created and in slack I have a channel for each project. 
I can use azboards normally in just one. 
Would this be a limitation of the app? 
If not, how could you solve this? Because the notification of creation of a Work item, for example, only reaches the channel of one of the projects, for the others not enough.

Grateful for the attention

I apologize for the grammar now, I'm from Brazil and I'm still in the process of learning in English.

**Comment by msebolt** [comment]
@quiarneto No problem, thank you for the question.

From what I understand you need to setup [subscriptions](https://docs.microsoft.com/azure/devops/boards/integrations/boards-slack?view=azure-devops#set-up-subscriptions) per project and then link each subscription to a separate channel.

Please comment below if this does not address the issue.

**Comment by quiarneto** [comment]
@msebolt I was able to configure it!
Thank you so much for your support!
