### ISSUE TITLE
Want a Manifest json schema file

### ISSUE THREAD

**Issue by dengyakui** [MicrosoftDocs/vsts-docs#5899]
Manifiest has too many content to cover, cant we have a schema file so that we can get hint in vscode,  and support both TFS2018 and AzureDevOps

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d8b703fe-8982-4284-6db0-ef33abac08a4
* Version Independent ID: 0fc84d11-1c32-0a49-04ec-641b68f44886
* Content: [Extension Manifest Reference](https://docs.microsoft.com/en-us/azure/devops/extend/develop/manifest?view=azure-devops#feedback)
* Content Source: [docs/extend/develop/manifest.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/extend/develop/manifest.md)
* Product: **devops**
* Technology: **devops-ecosystem**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @dengyakui, I'm following up on your request and will be in touch. Thank you for reaching out.

**Comment by chcomley** [comment]
Hi @dengyakui, 
After discussion with an engineer, we definitely don't have anything available containing all of this information. He's advised that he has added your idea to their backlog. I'd also suggest submitting a feature request and get it up-voted. You can do so here: https://visualstudio.microsoft.com/vs/support/#talktous and then select **Submit an idea**. 
Thank you!
