### ISSUE TITLE
Great Information!

### ISSUE THREAD

**Issue by ChristianJarenfors** [MicrosoftDocs/vsts-docs#5905]
This will help me improve my pullrequests and is a great reference for anyone who wondering how the syntax for the markdown works!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fa622358-f5bb-1f5c-177a-081a37b6acef
* Version Independent ID: 72f7fd16-a822-66c8-3a34-8905645ce5f2
* Content: [Markdown syntax for files, widgets, and wikis in Azure DevOps - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/project/wiki/markdown-guidance?view=azure-devops#feedback)
* Content Source: [docs/project/wiki/markdown-guidance.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/project/wiki/markdown-guidance.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Thanks for the great feedback, @ChristianJarenfors! We appreciate this very much. Is there anything we can help you with, or were you just trying to make our day? :)

**Comment by chcomley** [comment]
Closing the issue, but do let us know if you have any further comments or questions and thanks again, @ChristianJarenfors!

**Comment by ChristianJarenfors** [comment]
I need no help at the moment. I was glad when I found it and thought you
should know and get some appreciation for it. :)
