### ISSUE TITLE
VS403373 error

### ISSUE THREAD

**Issue by tcgielow** [MicrosoftDocs/vsts-docs#591]
Ran into this issue that resulted from a split TFS collection.  You should add detail and resolution on this error.  The solution is simple but took help of the developer community to point it out.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1798e45e-200d-f201-e4dd-58aac2427d29
* Version Independent ID: 86df23f9-1e19-65ae-de6d-cc6069521f34
* Content: [Troubleshooting the migration import from TFS to Visual Studio Team Services (VSTS)](https://docs.microsoft.com/en-us/vsts/articles/migration-troubleshooting?view=vsts)
* Content Source: [docs/articles/migration-troubleshooting.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/articles/migration-troubleshooting.md)
* Service: **unspecified**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by elbatk** [comment]
Hi @tcgielow , getting around to the older stuff on my backlog, I've got a PR for this, thank you! :)
