### ISSUE TITLE
Expand callback documentation, including authToken requirement

### ISSUE THREAD

**Issue by PriceChild** [MicrosoftDocs/vsts-docs#5913]
The section "[Where should a task signal completion when Callback is chosen as the completion event?](Where should a task signal completion when Callback is chosen as the completion event?)" explains well the url structure and a hint to the possible payloads that can be provided, giving one example on marking the task completed.

It does not mention that the authtoken in the initiating request's body must be included in a basic authorisation header when attepmting to complete the callback. This took me longer than I'd like to admit to realise...

It would also be useful to document the other possible ways that api endpoint can be used to signal the start or report on progress.

The 'simple cmdline application' was a good reference, but clearer documentation would be better.

Is the api documented elsewhere?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 89bc6da4-5a1e-5989-f4f0-27465953b5fd
* Version Independent ID: fd12f976-5d3b-3b1b-3d0a-a0bf2a60c961
* Content: [Invoke HTTP REST API task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/http-rest-api?view=azure-devops)
* Content Source: [docs/pipelines/tasks/utility/http-rest-api.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/utility/http-rest-api.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by jorgemarti** [comment]
In my case, I can't make the `InvokeRESTAPI` task be marked as completed, even if sending a Callback with all the information. The pipeline task just goes on and on unless I stop it. What am I doing wrong?

```
curl --location --request POST 'https://dev.azure.com/xundp-icc/DLI%20Master/_apis/distributedtask/hubs/build/plans/bdf58a18-eff4-4e0d-adb4-3e703*****/events?api-version=2.0-preview.1' \
--header 'Content-Type: application/json' \
--header 'Authorization: Basic eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6Im9PdmN6N[...]' \
--header 'Content-Type: application/json' \
--data-raw '{
  "name": "TaskCompleted",
  "taskId": "e76a9607-9c2e-529f-cae8-913b97*****",
  "jobId": "12f1170f-54f2-53f3-20dd-22fc7df*****",
  "result": "succeeded"
}'
```

**Comment by jorgemarti** [comment]
Ok, I found the solution myself: the project ID must be an actual _project ID_ and not a project _name_.

**Comment by WilliamAntonRohm** [comment]
@jorgemarti -- Jorge, thank you for that answer.
