### ISSUE TITLE
Progress Report doesn't update to most recently used Test Plan

### ISSUE THREAD

**Issue by Bemarkl** [MicrosoftDocs/vsts-docs#5917]
We are using the Progress Report to track our Test Execution and its working really well except for the Default Filters being applied.  It seems that once you visit the Progress Report Page the Default Test Plan filter is set and it doesn’t update to the test plan you accessed last like the documentation says it should – “2. Whenever you visit the report, it will show you the data for the test plan you had accessed last. Currently we do not store your last set of filters and also do not let you store an instance of this report.” https://docs.microsoft.com/en-us/azure/devops/test/track-test-status?view=azure-devops#feedback

For some of my users its fine as the first time they accessed the report they were in the correct test plan and it defaults to that one but for others (myself included) it defaults to an old or unused test plan and we have to constantly uncheck the test plan and select the correct one.  Is there a way to “Reset” the default test plan to get it updated?  I’m also concerned that when we move to the next cycle of testing all of the users will be defaulting to the old test plan and not the new one.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 23cfb51b-0b54-7d26-f9b2-4167915fba7a
* Version Independent ID: 5716194c-87f4-b1dc-7f31-592529a1fd3a
* Content: [Track test status - Azure Test Plans](https://docs.microsoft.com/en-us/azure/devops/test/track-test-status?view=azure-devops#provide-feedback)
* Content Source: [docs/test/track-test-status.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/test/track-test-status.md)
* Product: **devops**
* Technology: **devops-test**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by WilliamAntonRohm** [comment]
It looks like you've encountered an issue with the product itself, rather than an issue with the documentation. To make sure it gets in front of the right people, please [submit your bug here]( https://developercommunity.visualstudio.com/content/problem/post.html?space=21).

**Comment by Bemarkl** [comment]
Just FYI the document says to email devops_tools@microsoft.com to provide feedback but that email address isn't accessible to senders outside of Microsoft, may want to remove that section or update it to point to the Developer Community.
