### ISSUE TITLE
Can appSettings be multiline?

### ISSUE THREAD

**Issue by zmarty** [MicrosoftDocs/vsts-docs#5918]
We run a quite complex Azure Function App with tens of app settings. 

1) Can the appSetting setting have a multiline value such that we can have each setting on a separate line?
2) If yes, can we send in this multiline string as a template parameter as well?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f82ad1fa-cee5-c5c6-7050-21aaec6b714a
* Version Independent ID: 617316ff-2dab-d021-880f-c1c79313c320
* Content: [Azure Function App task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-function-app?view=azure-devops)
* Content Source: [docs/pipelines/tasks/deploy/azure-function-app.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/deploy/azure-function-app.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @azooinmyluggage
* Microsoft Alias: **atulmal**

**Comment by msebolt** [comment]
@zmarty Thank you for the questions, assigning this to the author for comment.

If this feature is unavailable, please move this issue to the [azure-pipelines-tasks](https://github.com/Microsoft/azure-pipelines-tasks/issues) repo.

**Comment by zmarty** [comment]
I have tested this and multiline settings are indeed available and the deployment goes out fine. But it would be nice to have an example in the documentation, for people that have many settings. Something like this works:

```
appSettings: >-
    -APPINSIGHTS_INSTRUMENTATIONKEY "xxx"
    -BlobStorageConnectionString "yyy"
```

Reference: https://stackoverflow.com/questions/3790454/how-do-i-break-a-string-over-multiple-lines/21699210

**Comment by msebolt** [comment]
@zmarty  Thank you for the posting your solution.

...adding @azooinmyluggage to include this in a possible update.
