### ISSUE TITLE
What are the audit-able events

### ISSUE THREAD

**Issue by clix455** [MicrosoftDocs/vsts-docs#5920]
Would like to find out if there is a list of audit-able events? 
Kind regards,
Cl

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 52f60b32-5c3c-f01a-cbbf-f4e9bd17a3fc
* Version Independent ID: 94753ea7-b465-f92e-10c2-8b17d995e4ff
* Content: [Access, export, filter audit logs for Azure DevOps - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/settings/azure-devops-auditing?view=azure-devops)
* Content Source: [docs/organizations/settings/azure-devops-auditing.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/settings/azure-devops-auditing.md)
* Product: **devops**
* Technology: **devops-settings**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by msebolt** [comment]
@clix455  Thank you for the question, assigning this to the author for review.

**Comment by clix455** [comment]
Thank you there, any update on this query?

**Comment by chcomley** [comment]
Hi @clix455, 

I'm following up on the REST API documentation updates, as there's another [GitHub Issue](https://github.com/MicrosoftDocs/vsts-docs/issues/5985) that will address this. In the meantime, this will give you the list of audit events: 
https://auditservice.dev.azure.com/{ORG NAME HERE}/_apis/audit/actions

Please let me know if you have any further questions.
