### ISSUE TITLE
No instructions on how to unpublish a published Wiki repo branch

### ISSUE THREAD

**Issue by jamesmcroft** [MicrosoftDocs/vsts-docs#5921]
The instructions here show how it is possible to unpublish an entire Wiki including all of the published branches.

It would be useful to have documentation on removing individual published branches from a Wiki if the branch now wants to be removed.

This could be a feature request of Azure DevOps Wiki if this does not exist yet.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c697355f-1e75-27a9-8214-195c26ede4e7
* Version Independent ID: 3f62c207-5449-d7f3-f3b3-82d6fc8f014d
* Content: [Publish new wiki version, select version, or unpublish a wiki in Azure DevOps - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/project/wiki/wiki-select-unpublish-versions?view=azure-devops)
* Content Source: [docs/project/wiki/wiki-select-unpublish-versions.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/project/wiki/wiki-select-unpublish-versions.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by msebolt** [comment]
@jamesmcroft Thank you for the question, will assign this to author for comment.

For feature requests, please use the [Azure DevOps community](https://developercommunity.visualstudio.com/topics/Azure+DevOps.html).

**Comment by jamesmcroft** [comment]
@msebolt so I think I worked it out. Essentially, because it is a Git branch, to delete the published branch, the only current way to remove it is by deleting the actual branch. 

There doesn't appear to be a way of removing the published branch from the Wiki itself. 

I'd recommend that this doc updates to reflect this so others might find that of some use. 

I'll raise the feature request with the link you've provided 😄

**Comment by chcomley** [comment]
@jamesmcroft, Thanks for raising a feature request. I've just added a note to the article, which should be live sometime today. Thanks so much for your feedback.

**Comment by rroman81** [comment]
I looked at the relevant page and there still seems to be no way to unpublish a revision/version of the Wiki.  Is that still in the plans?

**Comment by chcomley** [comment]
Hi @rroman81, I've followed up with the product group and will get back to you soon. Thanks

**Comment by JefSchraag** [comment]
The page still does not state if it is possible to unpublish a branch nor how to achieve unpublishing a branch.

**Comment by georg-eckert-zeiss** [comment]
This information is still missing.
