### ISSUE TITLE
startup.ps1 runs in docker, errors out and quits.

### ISSUE THREAD

**Issue by ppumkin** [MicrosoftDocs/vsts-docs#5923]
When I start the docker image this is the output log.

```
3. Configuring Azure Pipelines agent...
>> Connect:
Connecting to server ...
>> Register Agent:
Scanning for tool capabilities.
Connecting to the server.
Successfully replaced the agent
Testing agent connection.
Error reported in diagnostic logs. Please examine the log for more details.
    - C:\azp\agent\_diag\Agent_20191009-210847-utc.log
The local machine's clock may be out of sync with the server time by more than five minutes. Please sync your clock with your domain or internet time and try again.
4. Running Azure Pipelines agent...
Error reported in diagnostic logs. Please examine the log for more details.
    - C:\azp\agent\_diag\Agent_20191009-210916-utc.log
An error occurred: Not configured
Cleanup. Removing Azure Pipelines agent...
Removing agent from the server
Cannot connect to server, because config files are missing. Skipping removing agent from the server.
Removing .credentials
Succeeded: Removing .credentials
```

First of all, thank you for deleting the log file that was created inside the agent. That was very helpful! (Sarcasm aside, maybe specify a logs directory that wont get nuked)

Second there is no information from the configure.cmd emitted to the console (that may solve the problem with deleting the log file?)

When I go and connect to the container by usage of `docker run -it dockeragent powershell` I run the `config.cmd` manually.

When I dug into the problem it was something to do with the time of your host is more than 5 minutes out of synch?
I could not set the time in the docker because i had no privileges (that me being a noob I dont know how to escalate my self yet in there)
The time service is not running.

The next morning every thing ran OK. 

I spent well over an hour trying to get to the error message and maybe another more trying to sort it with out luck

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b31d4f6c-d16d-2ba1-1294-6aa94e328046
* Version Independent ID: 88aec599-4410-697d-1002-1c41b1c17bb6
* Content: [Running a self-hosted agent in Docker - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/docker?view=azure-devops)
* Content Source: [docs/pipelines/agents/docker.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/agents/docker.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by msebolt** [comment]
@ppumkin Thank you for the feedback.

Unfortunately this is an issue for the product team, though feel free to comment on the documentation.

You can refer to this issue in the [Azure DevOps community](https://developercommunity.visualstudio.com/topics/Azure+DevOps.html).

**Comment by WilliamAntonRohm** [comment]
I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
