### ISSUE TITLE
Fail notification

### ISSUE THREAD

**Issue by JanSera** [MicrosoftDocs/vsts-docs#5925]
Is there any way how to setup Azure DevOps to send out notification when service hook fails?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4806b641-fdb1-c0e9-081c-c007807c7cdb
* Version Independent ID: f59d8501-1285-be79-b084-8371ed8395bb
* Content: [WebHooks with Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/service-hooks/services/webhooks?view=azure-devops#feedback)
* Content Source: [docs/service-hooks/services/webhooks.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/service-hooks/services/webhooks.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @chasewilson
* Microsoft Alias: **phwilson**

**Comment by msebolt** [comment]
@JanSera  Thank you for the question.

You will probably need to use the [REST API task](https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/http-rest-api?view=azure-devops) with a call to the service hook [diagnostics](https://docs.microsoft.com/rest/api/azure/devops/hooks/diagnostics/get?view=azure-devops-rest-5.1) endpoint, then send the notification if any status errors are detected.  

For an overview of status errors, see [Troubleshooting](https://docs.microsoft.com/azure/devops/service-hooks/troubleshoot?view=azure-devops).

**Comment by WilliamAntonRohm** [comment]
I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
