### ISSUE TITLE
Email sent to devops_tools@microsoft.com - is undelivered

### ISSUE THREAD

**Issue by RajeshwariMC** [MicrosoftDocs/vsts-docs#5926]
Though the document says - Provide feedback
Reach us at devops_tools@microsoft.com to share your thoughts on the Progress Report. In the process, share screenshots as appropriate.

However, email sent to devops_tools@microsoft.com - is undelivered

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 23cfb51b-0b54-7d26-f9b2-4167915fba7a
* Version Independent ID: 5716194c-87f4-b1dc-7f31-592529a1fd3a
* Content: [Track test status - Azure Test Plans](https://docs.microsoft.com/en-us/azure/devops/test/track-test-status?view=azure-devops#feedback)
* Content Source: [docs/test/track-test-status.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/test/track-test-status.md)
* Product: **devops**
* Technology: **devops-test**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by msebolt** [comment]
@RajeshwariMC Thank you for the feedback, please refer to https://github.com/MicrosoftDocs/vsts-docs/issues/5825.

Closing the issue now.
