### ISSUE TITLE
Missing a step

### ISSUE THREAD

**Issue by mossywell** [MicrosoftDocs/vsts-docs#5927]
"Verify that the artifact contains the Templates folder containing the template files WindowsVirtualMachine.json and WindowsVirtualMachine.parameters.json. This is the template that your release pipeline will consume to provision an Azure virtual machine." This sentence is only meaningful if you already know how to do it, in which case you wouldn't be reading this page. The URL to which it points does not contain the instructions needed to "verify that the artifact....". (Indeed, searching for the word "artifact" does not even return any results.) This is however a critical step in CI of ARM VMs and therefore classes as a missing step in the instructions. Please add it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fd6a020f-35b0-8d92-9f8b-d05e658236e8
* Version Independent ID: e6208061-614b-a084-9c91-ab2ea12c7e2b
* Content: [Build a VM using RM templates - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/apps/cd/azure/build-azure-vm-template?view=azure-devops)
* Content Source: [docs/pipelines/apps/cd/azure/build-azure-vm-template.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/apps/cd/azure/build-azure-vm-template.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by mossywell** [comment]
PS, actually all 4 step just link to the same document called "Create your first pipeline" which simply creates a noddy Java pipeline and a badge. Therefore, this may actually be a case of linking to the wrong document.

**Comment by msebolt** [comment]
@mossywell  Thank you for the feedback.

The documentation has been updated to point to a more relevant article, apologies for the confusion.
