### ISSUE TITLE
Unable to email and copy test cases from this new view

### ISSUE THREAD

**Issue by yeuruparaghoo** [MicrosoftDocs/vsts-docs#5932]
I have a user who has reported that two options that are available in the old view are not available in the new view, i.e. email specific test case(s) and copy a selected list of test cases from the columnar view and paste it into excel, word, email, etc.  He has a Basic +Test Plan license assigned.  Are these options going to be available in a future option for this new view?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3c520dee-1218-777e-7405-551623817c03
* Version Independent ID: 82b5d172-ae1a-2b4c-82ac-595cd7609d3c
* Content: [New test plans page - Azure Test Plans](https://docs.microsoft.com/en-us/azure/devops/test/new-test-plans-page?view=azure-devops#feedback)
* Content Source: [docs/test/new-test-plans-page.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/test/new-test-plans-page.md)
* Product: **devops**
* Technology: **devops-test**
* GitHub Login: @harishkragarwal
* Microsoft Alias: **harishkragarwal**

**Comment by msebolt** [comment]
@yeuruparaghoo Thank you for the question, assigning this to the author for review.

**Comment by harishkragarwal** [comment]
Hi,
Being able to export test cases is yet to be added to the new test page. It is planned and is stated at https://docs.microsoft.com/en-us/azure/devops/test/new-test-plans-page .

The grid has been enabled on the new page and you use it to copy test cases. 

Thanks, Harish

**Comment by lisaduplessis** [comment]
Hi @harishkragarwal, any idea when the export feature is being added? We need this for our TCR. Is there a workaround for the meantime? Can we go back to the old view anyway?

**Comment by lisaduplessis** [comment]
No worries, saw the workaround for the old view, thanks
