### ISSUE TITLE
Cannot Add Impediment to Backlog

### ISSUE THREAD

**Issue by huntleyh** [MicrosoftDocs/vsts-docs#5936]
In this article it states

"Impediments and issues don't appear on your backlog. Instead, you track them using queries. If you want them to appear on your backlog, or you want to track other work item types on your backlog, see Customize your backlogs or boards."
https://docs.microsoft.com/en-us/azure/devops/boards/backlogs/manage-issues-impediments?view=azure-devops#customize-issues-tracking

However in the linked article it states 
"You can't add an inherited WIT to any backlog level."
https://docs.microsoft.com/en-us/azure/devops/organizations/settings/work/customize-process-backlogs-boards?view=azure-devops#edit-rename-or-delete-a-portfolio-backlog

Trying to do this in Azure DevOps shows it does not allow adding Impediments to any backlog as stated in the second article.

Please either update this document or is there an ETA on support for this option in the service?

**Comment by msebolt** [comment]
@huntleyh  Thank you for the feedback, assigning this to the author for review.

**Comment by KathrynEE** [comment]
@huntleyh - thank you for the feedback. I will update the article. This isn't a supported feature in Azure DevOps Services and there is no plan at this time to support it in the cloud service.
