### ISSUE TITLE
How can we set query folder permissions via API?

### ISSUE THREAD

**Issue by pollockm** [MicrosoftDocs/vsts-docs#5938]
This page is great for manual effort, but I have been unable to find how to do so via the REST API.  We have thousands of queries, I do not want to manage them by hand. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 54179351-62b2-c41b-949b-0652a0f1d354
* Version Independent ID: 1ffcd0b3-e67b-6cfe-caa6-814a699627db
* Content: [Set query permissions - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/queries/set-query-permissions?view=azure-devops)
* Content Source: [docs/boards/queries/set-query-permissions.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/boards/queries/set-query-permissions.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by msebolt** [comment]
@pollockm  Thank you for the question, unfortunately issues here are for documentation only.

Please move the issue to the [Azure DevOps community](https://developercommunity.visualstudio.com/topics/Azure+DevOps.html) where the product team can respond and either solve your issue or consider adding this as a feature.

**Comment by WilliamAntonRohm** [comment]
I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.

**Comment by pollockm** [comment]
@WilliamAntonRohm  - so should I take it that this is confirmation that what I was hoping to see documentation of how to do is, in fact, not possible?

I assumed that it was possible, but the documentation on how to do so was just either not created yet or hard to find
