### ISSUE TITLE
coming soon

### ISSUE THREAD

**Issue by MrGPT** [MicrosoftDocs/vsts-docs#5939]
I see "(comparison coming soon)". The article appears to be 1.5 years old. Will updates be coming?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d96200b4-9fc1-7d8c-dce4-6a2b0cb5fa4d
* Version Independent ID: bf8e5f2c-a8a5-d2e1-f89c-5ed5129c32a3
* Content: [Azure DevOps vs GitLab - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/learn/compare/azure-devops-vs-gitlab#feedback)
* Content Source: [docs/compare/Azure-DevOps-vs-GitLab.md](https://github.com/MicrosoftDocs/devops-learn-pr/blob/live/docs/compare/Azure-DevOps-vs-GitLab.md)
* Product: **devops**
* Technology: **devops-learn**
* GitHub Login: @SamGu
* Microsoft Alias: **davemcki**

**Comment by msebolt** [comment]
@MrGPT  Thank you for the feedback, the documentation has been updated to remove any confusion.

Assigning this to the author for an update.
