### ISSUE TITLE
Add changeset to build no.

### ISSUE THREAD

**Issue by torbennehmer** [MicrosoftDocs/vsts-docs#594]
I'd like to add the current changeset to the build number as given here:

![image](https://user-images.githubusercontent.com/2812067/39114078-0b21907a-46de-11e8-9cec-91b9ac4d548b.png)

Unfortunately, I can't find a way to do this. Google returns only hits for older TFS on premise installations, while the build variable Build.SourceVersion is of scope agent, which isn't available in the build configuration.

Any insights would be welcome.

**Comment by andyjlewis** [comment]
@torbennehmer I'm sorry about the delayed response. In short, you should be able to use a logging command to do it. https://github.com/MicrosoftDocs/vsts-docs/issues/666 should give some idea. Longer term, we'll post an update to this content that includes the logging command.
