### ISSUE TITLE
No list of available tools when calling bash/powershell

### ISSUE THREAD

**Issue by iUnknwn** [MicrosoftDocs/vsts-docs#5943]
When writing scripts in [bash](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/bash?view=azure-devops) or [powershell](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/powershell?view=azure-devops), there's no list of provided build tools on the various agents. 

For example, can I call dotnet to manually build software from powershell task, or do I need a separate "install .net tools" step? If I want to run a python script that does some regex on other build files, do I need to install python, or is that already present? 

Having a clear list of what's already callable on the build machines (along with their versions) would make scripting easier, and allow teams to use existing build scripts.

**Comment by vtbassmatt** [comment]
This is [documented for the hosted build agents](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops#use-a-microsoft-hosted-agent). Private agents have whatever their owner has configured on them.

**Comment by iUnknwn** [comment]
Can we add a link in the bash and powershell pages to that the hosted build agents page, so it's easier to find (maybe under a "what software is available?" faq item). Right now, it's not immediately obvious.
