### ISSUE TITLE
Exemple with $1 does not work

### ISSUE THREAD

**Issue by Isarien** [MicrosoftDocs/vsts-docs#5945]
I try the affectation script et the reading script on azure devops, and the syntax $1 does not work, whereas the syntax $SAUCE is OK

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 611642f0-881f-10b9-ae94-3c562001d1f0
* Version Independent ID: 41efb94b-4c7a-64a3-b23b-70c8634ae727
* Content: [Release variables and debugging - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/variables?view=azure-devops&tabs=shell#feedback)
* Content Source: [docs/pipelines/release/variables.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/release/variables.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by vijayma** [comment]
Thank you for the feedback.
We are updating the doc to remove the references to $1 and $2 since they assume that the variables are passed as inputs to the script. However, the doc assumes that they are set as output variables in the previous step.
