### ISSUE TITLE
Pool Strategy/Schema

### ISSUE THREAD

**Issue by cawoodm** [MicrosoftDocs/vsts-docs#5950]
What is `pool:` and how can it be used to reference say a deployment pool or deployment group?
See "see pool schema" but not providing a link is not helpful.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5aeeaace-1c5b-a51b-e41f-f25b806155b8
* Version Independent ID: fd7ff690-b2e4-41c7-a342-e528b911c6e1
* Content: [Deployment jobs - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/deployment-jobs?view=azure-devops)
* Content Source: [docs/pipelines/process/deployment-jobs.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/deployment-jobs.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by RoopeshNair** [comment]
Deployment groups aren't supported in YAML yet. We are working on it. For a sneak peek at the designs refer [YAML designs repo](https://github.com/microsoft/azure-pipelines-yaml/tree/master/design)
