### ISSUE TITLE
User story automatically changes state to "Closed" after completing a pull request.

### ISSUE THREAD

**Issue by priyankadanda** [MicrosoftDocs/vsts-docs#5955]
How to stop changes in state of a user story despite approving the pull request. (Our process also has Ready for QA as a state. It would be nice if i could program it to go there instead of closed.

**Comment by WilliamAntonRohm** [comment]
@priyankadanda  Thanks for your feedback; we appreciate it. To make sure we have all the information needed to triage your issue, please let us know which topic you’re referencing, or provide more context around the general task.
