### ISSUE TITLE
force user to input value to 'settable at queue time' pipeline variable

### ISSUE THREAD

**Issue by swonge** [MicrosoftDocs/vsts-docs#5956]
is it possible to enforce user to input value for the pipeline variable that is set to "settable at queue time"?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd7e0bd3-1f7d-d7b6-cc72-5ef63c31b46a
* Version Independent ID: dae87abd-b73d-9120-bcdb-6097d4b40f2a
* Content: [Variables - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch#feedback)
* Content Source: [docs/pipelines/process/variables.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/variables.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by msebolt** [comment]
@swonge Thank you for the question.

I think your only option is to validate the user input and cancel the build if either no input or the wrong type of input is given.

If this is a feature you'd like to see implemented, please use the [Azure DevOps community](https://developercommunity.visualstudio.com/topics/Azure+DevOps.html).

**Comment by WilliamAntonRohm** [comment]
I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
