### ISSUE TITLE
Clone release definition by script

### ISSUE THREAD

**Issue by swonge** [MicrosoftDocs/vsts-docs#5957]
Is it possible to clone an existing release/build definition by script (i.e. CLI/API)?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 63234ade-28cc-02fc-a319-42e3491da601
* Version Independent ID: 7ccbfe96-d61e-8bf2-de22-61150d648abd
* Content: [Release pipelines - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/?view=azure-devops)
* Content Source: [docs/pipelines/release/index.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/release/index.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by msebolt** [comment]
@swonge  Thank you for the question.

Yes, please refer to the `Get` operation in the [Definitions API](https://docs.microsoft.com/en-us/rest/api/azure/devops/release/definitions?view=azure-devops-rest-5.1).

**Comment by WilliamAntonRohm** [comment]
I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
