### ISSUE TITLE
How to specify a deployment pool in a job?

### ISSUE THREAD

**Issue by cawoodm** [MicrosoftDocs/vsts-docs#5959]
&gt; you can specify the deployment targets for a job using a deployment group.
Yes, but how. If we specify
```
pool:
  name: MYDEPLOYMENTPOOL
```
Azure looks for an Agent Pool of this name and fails!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3b38c265-be4c-b038-e3a9-783a5e5ce659
* Version Independent ID: 67da69da-3651-a8f4-f06a-c35aa3aa98fc
* Content: [Use deployment groups in a release pipeline - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/deployment-groups/?view=azure-devops)
* Content Source: [docs/pipelines/release/deployment-groups/index.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/release/deployment-groups/index.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by msebolt** [comment]
@cawoodm Thank you for the question.

Deployment group jobs do not yet support YAML.

Please refer to [Deployment group jobs (classic)](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/deployment-group-phases?view=azure-devops&tabs=classic) for information on how to configure these through the UI or see https://github.com/MicrosoftDocs/vsts-docs/issues/4486 on the status of having this feature included.

**Comment by WilliamAntonRohm** [comment]
I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
