### ISSUE TITLE
error validating data: [apiVersion not set, kind not set]

### ISSUE THREAD

**Issue by techpassion** [MicrosoftDocs/vsts-docs#5962]
kubectl apply -f Azure-pipelines.yml 
[from local azure cli] 

**error: error validating "Azure-pipelines.yml": error validating data: [apiVersion not set, kind not set]; if you choose to ignore these errors, turn validation off with --validate=false**

are we supposed to run this yaml file only on Azure DevOps pipeline only? 
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cd85890a-ccba-8697-b406-b662aabeb27f
* Version Independent ID: a1d371df-c0a0-1cd6-37f8-4b60913a2e97
* Content: [Deploy to Azure SQL Database - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/targets/azure-sqldb?view=azure-devops&tabs=yaml#feedback)
* Content Source: [docs/pipelines/targets/azure-sqldb.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/targets/azure-sqldb.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by msebolt** [comment]
@techpassion  Thank you for the question.

Not necessarily, for any sort of custom containerization you will need a [custom Kubernetes resource definition](https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definitions/#create-custom-objects).

For an example of the Azure container, see the [Kubernetes walkthrough](https://docs.microsoft.com/en-us/azure/aks/kubernetes-walkthrough).

Is there a specific mention of this command in the topics that needs attention?

**Comment by msebolt** [comment]
Closing the issue now, please add comments if there any concerns.
