### ISSUE TITLE
Document limitation: Service Connection cannot be specified by variable

### ISSUE THREAD

**Issue by syndicatedshannon** [MicrosoftDocs/vsts-docs#5964]
Please add to documentation that Service Connection cannot be specified by variable. While I would prefer the limitation be fixed, since the issue ( https://github.com/Microsoft/azure-pipelines-agent/issues/1307 ) was closed 2 years ago without resolution, and not reopened since, the limitation should be documented. This sort of limitation takes quite a bit of time to diagnose, since it involves black-box evaluation of security connection functions at a point in the toolchain with poor diagnostic capability; this it fairly important to document to save teams time. To take my own experience with this issue as an example, I spent a few hours today just identifying the cause, although I have over 30 years of software and network engineering experience.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72b90dd0-49f9-4ed4-3010-9a64dde6ae5a
* Version Independent ID: 6e679d50-4e94-eee3-8793-af884cc909ca
* Content: [Service connections in Azure Pipelines and Team Foundation Server - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/library/service-endpoints?view=azure-devops&tabs=yaml#feedback)
* Content Source: [docs/pipelines/library/service-endpoints.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/library/service-endpoints.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by msebolt** [comment]
@syndicatedshannon Thank you for the feedback, assigning this to the author for review.

**Comment by jessebarocio** [comment]
Just wasted the better part of a day trying to get this to work and searching for answers. If the underlying issue isn't going to be fixed it should be documented ASAP.

**Comment by MichaKnoe** [comment]
I also spend a lot of time to understand that this is just not working. **PLEASE** at least document this properly that everybody can understand easily what is happening under the hood. **With the release pipelines UI, it was/is possible to use variables to define subscription by variables**. So this is **a regression coming with yaml** pipelines. It is just not obvious why it is not working. 

Another similar issue is, that you cannot use a variable to **define a stage name**. If you come up with a solution, please solve this right away.

Thanks a lot for listening to us

**Comment by aelmanaa** [comment]
agree. I also spent lot of time trying to figure this out :(

**Comment by srivatsamarichi** [comment]
The document has been updated and I'll be closing the issue. Thank you for the feedback and feel free to open a new issue if you have any more feedback.

**Comment by iamsrivatsa** [comment]
The document has been updated and I'll be closing the issue. Thank you for the feedback and feel free to open a new issue if you have any more feedback.

**Comment by fmms** [comment]
Hi,

I just was caught by this small note. 
However, if it cannot be specified as a variable, what is the workarround? We have different environments (e.g. YAML stages) on different tenants and thus they must use different service connections? How do you guys solve this issue?

regards

**Comment by MichaKnoe** [comment]
@fmms As far as I know this can only be achieved by hard coding environment variables either in yaml variable templates or by using hard coded yaml template parameters values.

**Comment by aelmanaa** [comment]
yes indeed. I also hardcoded the parameters values

**Comment by theneedyguy** [comment]
@MichaKnoe could you provide a sample on how to do the workaround? I've been trying to use variables to change the service connection name in my builds too.

**Comment by MichaKnoe** [comment]
It is hard to explain at the moment @theneedyguy : 
There is no real good workaround for this. 
When using yaml pipeline and variable templates you have the possibility to reuse templates with different parameters. Here you can provide the value of variables to be delivered as a parameter value.
But the same is not possible for serviceConnection names. That means you cannot retrieve such a value from a kind of centralized serviceConnectionLookupTable or something similar for better maintainability. You have to hardcode the value directly as a template parameter value. 
To understand this properly you need to understand and play around with templating a bit.
Sorry, but I cannot provide an example currently.
Best Regards.

**Comment by theneedyguy** [comment]
@MichaKnoe thanks. I worked around this by setting task variables and then executing the task based on the variable value (I basically have the same task multiple times but only one will execute based on the variable value) I had to hard code the ServiceConnection name in my "root" YAML file though. It's better than nothing.
