### ISSUE TITLE
with or without?

### ISSUE THREAD

**Issue by HughDevlin** [MicrosoftDocs/vsts-docs#5966]
seems like the 1st sentence should be "without the overhead of running a server."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43e576b8-a378-a985-33cb-8adb9d7d7957
* Version Independent ID: d1b99713-8e01-23d9-47b7-1a9b5c98d5ca
* Content: [Build and deploy to a Java web app on Linux - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/ecosystems/java-function?view=azure-devops#feedback)
* Content Source: [docs/pipelines/ecosystems/java-function.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/ecosystems/java-function.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by msebolt** [comment]
@HughDevlin Thank you for the feedback.

The documentation has been updated and is pending review.

**Comment by WilliamAntonRohm** [comment]
Thank you for your feedback.  We have updated the documentation and it should be live by tomorrow.

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
