### ISSUE TITLE
Automated transition from a Jenkins declarative pipeline into an Azure Pipelines YAML configuratio

### ISSUE THREAD

**Issue by firmsoil** [MicrosoftDocs/vsts-docs#5968]
Question: Is there a way in Azure to programmatically automate my .Net/MSBuid pipeline definition from its current Jenkins declarative pipeline format into the Azure Pipelines YAML configuration?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a0088651-e8ef-3226-3225-22053b76e832
* Version Independent ID: 78b114db-abf1-28ec-b7aa-ce5c72d37d36
* Content: [Migrate from Jenkins to Azure Pipelines - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/migrate/from-jenkins?view=azure-devops#feedback)
* Content Source: [docs/pipelines/migrate/from-jenkins.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/migrate/from-jenkins.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @ethomson
* Microsoft Alias: **ethomson**

**Comment by msebolt** [comment]
@firmsoil  Thank you for the question.

Please see if either the [Build Definitions](https://docs.microsoft.com/rest/api/azure/devops/build/definitions?view=azure-devops-rest-5.1) or [Release Definitions](https://docs.microsoft.com/rest/api/azure/devops/release/definitions?view=azure-devops-rest-5.1) API suits your needs and comment below if there are issues.

**Comment by msebolt** [comment]
Closing the issue, please add comments if there are concerns.
