### ISSUE TITLE
Add object-level security for Analytics

### ISSUE THREAD

**Issue by ChristopherMank** [MicrosoftDocs/vsts-docs#597]
I see that the security for analytics is mentioned at the top as well as the project level View Analytics permission. However, can we add a section for the object-level permissions as a group in here as well? So a heading under "In this article --> Permissions" and then a section for it. I'd create a PR for it but feel it's a big enough add that I don't want to get it wrong.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cc2adbee-5e62-a34a-5914-31bd417df13b
* Version Independent ID: 0f97e954-e8ef-b4b6-7182-24f9a9e3d92e
* Content: [Permissions and groups reference - VSTS & TFS](https://docs.microsoft.com/en-us/vsts/security/permissions?view=vsts#nbspnbspnbspgit-repository-object-level)
* Content Source: [docs/security/permissions.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/security/permissions.md)
* Service: **unspecified**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
@ChristopherMank, Thanks so much for your update. I've created a backlog item for this work.
