### ISSUE TITLE
Visual Studio Test task does not support .NET Core 3.0

### ISSUE THREAD

**Issue by TimThrill** [MicrosoftDocs/vsts-docs#5970]
In the "otherConsoleOptions", it does not support target to .NET Core 3.0.
Reference: [link](https://docs.microsoft.com/en-us/previous-versions/jj155796(v=vs.140)?redirectedfrom=MSDN)
Do you have any plan to update this tool to support .NET Core 3.0?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 16bd8dd1-7650-8c18-2553-38a8bc54e892
* Version Independent ID: f9fa517a-7adc-e327-d12e-256295a1ed52
* Content: [Visual Studio Test task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/test/vstest?view=azure-devops)
* Content Source: [docs/pipelines/tasks/test/vstest.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/test/vstest.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @PBoraMSFT
* Microsoft Alias: **pbora**

**Comment by msebolt** [comment]
@TimThrill Thank you for the question.

Unfortunately this is more of a question for the product team to address.

Please move this issue to the [azure-pipelines-tasks](https://github.com/Microsoft/azure-pipelines-tasks/issues) repo.

**Comment by TimThrill** [comment]
I think I found a solution to do this. Thank you. I'll close this one.
