### ISSUE TITLE
How to create YAML Pipelines with Azure DevOps Server (on-premise)

### ISSUE THREAD

**Issue by htho** [MicrosoftDocs/vsts-docs#5971]
I work with Azure DevOps Server (on-premise) at my job.
I can't find a way to create and run a pipeline. There are some missing links.

I created a `azure-pipeline.yml` in a TFS git repo, but there seems to be no link to the server interface.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7336a04e-5b38-d02f-8bba-a55445b2f094
* Version Independent ID: 783c30b3-63b6-da7c-1336-b000bb8b4c66
* Content: [Create your first pipeline - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/create-first-pipeline?view=azure-devops&tabs=tfs-2018-2#feedback)
* Content Source: [docs/pipelines/create-first-pipeline.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/create-first-pipeline.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by msebolt** [comment]
@htho  Thank you for the feedback.

What exactly are you seeing in the DevOps menu?  

You should be able to create a new pipeline like the following:

![Capture](https://user-images.githubusercontent.com/6675884/66786953-f259fe80-ee96-11e9-925a-daf1a72d36f8.PNG)

**Comment by msebolt** [comment]
Closing the issue, please add comments if there are any concerns.
