### ISSUE TITLE
Ability to skip stage or trigger particular stage manually in Multi-stages pipelines

### ISSUE THREAD

**Issue by maxim-lobanov** [MicrosoftDocs/vsts-docs#5972]
Hello everyone,
We are really excited with Multi-stages pipeline experience and possibility to store Pipeline structure via YAML. However, there is a limitation that prevents us to use this approach and hold us on classic release definitions: impossibility to trigger specific stage by manual click.

On classic release definition we have the following abilities:
(Imagine that you have pipeline with 3 sequential stages)
1) If the first stage fails, the whole pipeline stops but I can ignore this failed stage and run the next stage via manual click. (This case is most important because some long processes like testing can fail randomly, and we don't want to restart it and wait one more time, we just want to continue)
2) I can cancel the first stage during run and trigger the third stage manually (not run the second one at all).

Due to these 2 points, classic release definitions look more flexible for us and we have to continue using it.

Could you please consider this use-case?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4266f72c-c774-0046-4593-d01eb775d3c3
* Version Independent ID: f20827aa-a6c5-96a8-5969-e576ffbc2e38
* Content: [Stages in Azure Pipelines - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/stages?view=azure-devops&tabs=yaml#feedback)
* Content Source: [docs/pipelines/process/stages.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/stages.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @vijayma
* Microsoft Alias: **vijayma**

**Comment by msebolt** [comment]
@maxim-lobanov Thank you for the feedback.

Until the product team moves to GitHub, any use-case must be submitted through the [Azure DevOps community](https://developercommunity.visualstudio.com/topics/Azure+DevOps.html).

Please submit your idea there and link back to this issue.

**Comment by maxim-lobanov** [comment]
[Done](https://developercommunity.visualstudio.com/idea/777126/ability-to-skip-stage-or-trigger-particular-stage.html), thanks!
