### ISSUE TITLE
Identity field rules documentation seems incorrect

### ISSUE THREAD

**Issue by sunahe** [MicrosoftDocs/vsts-docs#5973]
According to section "Rules that cause a string field to be considered an identity field", a string field is recognized as an identity field when you specify one of the following rule elements within its FIELD definition: ALLOWEDVALUES, PROHIBITEDVALUES, VALIDUSER

This cannot be right: many built-in string fields have ALLOWEDVALUES and are not considered identity fields. For example, Value area field:

&lt;FIELD name="Value Area" refname="Microsoft.VSTS.Common.ValueArea" type="String"&gt;
        &lt;REQUIRED /&gt;
        &lt;ALLOWEDVALUES&gt;
          &lt;LISTITEM value="Architectural" /&gt;
          &lt;LISTITEM value="Business" /&gt;
        &lt;/ALLOWEDVALUES&gt;
        &lt;DEFAULT from="value" value="Business" /&gt;
        &lt;HELPTEXT&gt;Business = delivers value to a user or another system; Architectural = work to support other stories or components&lt;/HELPTEXT&gt;
      &lt;/FIELD&gt;

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f3f646c2-3c97-597c-c452-5f12f20c9889
* Version Independent ID: 9481bb73-bc5f-2666-b48c-3fca017ef536
* Content: [Customize a process to import using Hosted XML - Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/organizations/settings/work/import-process/customize-process?view=azure-devops)
* Content Source: [docs/organizations/settings/work/import-process/customize-process.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/settings/work/import-process/customize-process.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by msebolt** [comment]
@sunahe Thank you for the feedback, assigning this to the author for review.

**Comment by KathrynEE** [comment]
@sunahe - Thank you for the feedback and apologies for the delay in response. I have added this item to my backlog and will be updating the article to clarify any inaccuracies.
