### ISSUE TITLE
Conversation Replies from Azure Devops CI/CD task

### ISSUE THREAD

**Issue by jjpepper** [MicrosoftDocs/vsts-docs#5974]
Hi, it seems strange to me that there is 3rd party support for azure devops tasks that send telegram messages (say when your build fails), but there is no such thing for sending a message from Azure Devops to MS Teams conversations.  I imagine this should be pretty trivial and I wonder if it's on the roadmap for anyone?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8098f527-ebdf-60d5-3989-5228b7a207c1
* Version Independent ID: ce27c817-9599-00ef-5af2-3ac1dbad8dc6
* Content: [Build and Release Tasks in Azure Pipelines and TFS - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/tasks?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/process/tasks.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/tasks.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by msebolt** [comment]
@jjpepper  Thank you for the interest.

For current Teams support, please see [Team service hooks](https://docs.microsoft.com/en-us/azure/devops/service-hooks/services/teams?view=azure-devops) or [Integrate Teams and Azure DevOps](https://www.azuredevopslabs.com/labs/vstsextend/teams/).

Please comment below if these features are limiting in some way.

**Comment by msebolt** [comment]
Closing the issue now.
