### ISSUE TITLE
Reference Build Tags with Variable

### ISSUE THREAD

**Issue by itsjusth** [MicrosoftDocs/vsts-docs#5976]
I am able to add a Build tag and use it for filtering in my Release pipeline triggers, however, I do not see any way to reference this tag via an environment variable for my scripts.  Is this possible?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ffebdc8-521c-44b5-cde4-4abdc1bd6f18
* Version Independent ID: dc0effda-6d93-62aa-64c5-4e6f283b0826
* Content: [Predefined variables - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml#feedback)
* Content Source: [docs/pipelines/build/variables.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/build/variables.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by msebolt** [comment]
@itsjusth  Thank you for the question.

Currently, the only way to do this is through the `Build.SourceBranch` or `Build.SourceBranchName` variables, see [this post](https://stackoverflow.com/questions/56302207/is-it-possible-to-pass-in-a-git-repo-tag-to-an-ado-build-pipeline-as-a-variable).

If you need something more robust, please start dialog with the product team through the [Azure DevOps community](https://developercommunity.visualstudio.com/topics/Azure+DevOps.html).

**Comment by WilliamAntonRohm** [comment]
I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
