### ISSUE TITLE
Azure YAML Multi-stage pipeline artifacts missing from this page

### ISSUE THREAD

**Issue by cmeyertons** [MicrosoftDocs/vsts-docs#5978]
We are currently receiving the following error in our new multi-stage pipeline.

What are the domains that we need to whitelist in order to resolve?

```
Information, ApplicationInsightsTelemetrySender will correlate events with X-TFS-Session f32aa320-19ec-4d1e-b252-d69087307937
Information, DedupManifestArtifactClient will correlate http requests with X-TFS-Session f32aa320-19ec-4d1e-b252-d69087307937
Information, Minimatch patterns: [**]
Information, ArtifactHttpRetryMessageHandler.SendAsync: https://vsblobprodcus3.vsblob.visualstudio.com/Af9f035f5-03e9-4b6f-a0d8-6df7ef63c54a/_apis/dedup/chunks/EE9575CB71700117CDB942AB524E023CEAB5897C118EC6748296142B2C77D93D01 attempt 1/6 failed with StatusCode RedirectMethod, IsRetryableResponse False
Warning, [https://yttvsblobprodcus357.blob.core.windows.net/dbf9f035f503e94b6fa0d86df7ef63c54a/EE9575CB71700117CDB942AB524E023CEAB5897C118EC6748296142B2C77D93D01?sv=2017-04-17&sr=b&sig=AK5cbVsl9KUOQXo9vwuLXwPUcSzxjPv3e0Ng0xGr59o%3D&spr=https&se=2019-10-15T17%3A55%3A55Z&sp=r&rscl=x-e2eid-7a47eaa9-c05142f6-9363fcad-9ce90eb8-session-f32aa320-19ec4d1e-b252d690-87307937] Try 1/5, retryable exception caught. Retrying in 00:00:01. Details:
No LastRequestResponse on exception HttpRequestException: An error occurred while sending the request. System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.WinHttpException: Error 12029 calling WINHTTP_CALLBACK_STATUS_REQUEST_ERROR, 'A connection with the server could not be established'.
   at System.Threading.Tasks.RendezvousAwaitable`1.GetResult()
   at System.Net.Http.WinHttpHandler.StartRequest(WinHttpRequestState state)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Microsoft.VisualStudio.Services.Common.TaskCancellationExtensions.EnforceCancellation[TResult](Task`1 task, CancellationToken cancellationToken, Func`1 makeMessage, String file, String member, Int32 line)
   at Microsoft.VisualStudio.Services.BlobStore.WebApi.DedupStoreHttpClient.<>c__DisplayClass56_0.<<GetRedirectResponseAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc5a4cfa-aa84-9f0f-55f4-71ec4861c070
* Version Independent ID: d621620a-c924-03b1-8b43-f99c33e58bb8
* Content: [Add IP addresses and URLs to allow list - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/security/allow-list-ip-url?view=azure-devops#feedback)
* Content Source: [docs/organizations/security/allow-list-ip-url.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/security/allow-list-ip-url.md)
* Product: **devops**
* Technology: **devops-security**
* GitHub Login: @chcomley
* Microsoft Alias: **jominana**

**Comment by msebolt** [comment]
@cmeyertons  We're sorry you're experiencing issues.

Unfortunately, the product team is more apt to handle support requests.

However, there is an issue similar to what you describe above being tracked [here](https://developercommunity.visualstudio.com/content/problem/694835/download-artifact-failing-with-error-about-a-conne.html) on the [Visual Studio community](https://developercommunity.visualstudio.com).

Please refer there for help with your issue.

**Comment by WilliamAntonRohm** [comment]
I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
