### ISSUE TITLE
Ambiguous as to what permissions to grant the PAT for deployment group agents

### ISSUE THREAD

**Issue by thatnerdyguy** [MicrosoftDocs/vsts-docs#598]
What does

"For the scope select Agent Pools (read, manage) and make sure all the other boxes are cleared. If it's a deployment group agent, for the scope select Deployment group (read, manage) and make sure all the other boxes are cleared."

mean? If it's a deployment group agent do you need "Agent Pools (read, manage)" AND "Deployment group (read, manage)" selected? Or should the first sentence start with "If it's not a deployment group agent..."?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43799c5d-2f13-cc76-a1c0-a3f850e16d4e
* Version Independent ID: 97a5b73f-faf7-f9c0-9269-fc79984616d6
* Content: [Deploy an agent on Windows](https://docs.microsoft.com/en-us/vsts/build-release/actions/agents/v2-windows?view=vsts)
* Content Source: [docs/build-release/actions/agents/v2-windows.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/build-release/actions/agents/v2-windows.md)
* Service: **unspecified**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by azooinmyluggage** [comment]
I think it is not an _AND_. Just selecting _Deployment group (read, manage)_ will be enough. Adding @RoopeshNair for confirming once.

**Comment by RoopeshNair** [comment]
Depending on the agent type you need to select the appropriate PAT token scope, 
For build and release agents, select agent pool (read and manage)
For deployment group agents, select deployment group (read and manage)

Hope it helps

@alexhomer1  - to rephrase, if required.
