### ISSUE TITLE
missing examples

### ISSUE THREAD

**Issue by danielstefanescu** [MicrosoftDocs/vsts-docs#5984]
"You can access Analytics through dashboard widgets, in-context reports, Power BI, and OData" please provide some examples of **in-context reports**

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0618890e-ee0d-73b5-bdb9-f04355662dd8
* Version Independent ID: e0fbbecb-1e51-63fd-8396-3cc5bbc100bc
* Content: [What is Analytics - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/report/powerbi/what-is-analytics?view=azure-devops)
* Content Source: [docs/report/powerbi/what-is-analytics.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/report/powerbi/what-is-analytics.md)
* Product: **devops**
* Technology: **devops-analytics**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@danielstefanescu - Thank you for the feedback. I will update the article to provide more details. In the meantime - you can read more about in-context reports in these articles:
- [Cumulative flow](https://docs.microsoft.com/en-us/azure/devops/report/dashboards/cumulative-flow.md)
- [Team velocity](https://docs.microsoft.com/en-us/azure/devops/report/dashboards/team-velocity.md)
- [Sprint burndown chart](https://docs.microsoft.com/en-us/azure/devops/boards/sprints/sprint-burndown.md) 
- [Pipeline pass rate report](https://docs.microsoft.com/en-us/azure/devops/pipelines/reports/pipelinereport.md#pipeline-pass-rate-report)
- [Test failures report](https://docs.microsoft.com/en-us/azure/devops/pipelines/test/test-analytics.md#test-failures)
