### ISSUE TITLE
Azure Repos points to broken link

### ISSUE THREAD

**Issue by SanderHolvoet** [MicrosoftDocs/vsts-docs#5987]
The *Version Control control panel tab* in Azure Repos currently points to a broken link:
```
https://dev.azure.com/{your-organization}/DefaultCollection/{your-project}/_admin/_versioncontrol
```

The _DefaultCollection_ should be omitted, as this is only applicable for TFS:
```
https://dev.azure.com/{your-organization}/{your-project}/_admin/_versioncontrol
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 024e4ed9-cf8d-155f-5e4a-73c2effaaed8
* Version Independent ID: f19c0538-4aae-b3b4-82b9-422e76723b01
* Content: [Run Git commands in a script - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/scripts/git-commands?view=azure-devops&tabs=yaml#feedback)
* Content Source: [docs/pipelines/scripts/git-commands.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/scripts/git-commands.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @chasewilson
* Microsoft Alias: **phwilson**

**Comment by SanderHolvoet** [comment]
@WilliamAntonRohm Created PR #6007

**Comment by WilliamAntonRohm** [comment]
@SanderHolvoet -- Sander, thank you for your contribution.

@steved0x -- Steve, I'm assigning this to you to go with Sander's PR.

**Comment by steved0x** [comment]
Fixed in the associated PR
