### ISSUE TITLE
How can I look up the admin of an org that I don't have access to?

### ISSUE THREAD

**Issue by fiksen99** [MicrosoftDocs/vsts-docs#5990]
Navigating to an Azure DevOps organisation that I don't have access to indicates that I need to reach out to the admins of the org to get access. But without access to the org, I have no way to find out who the admin is.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 20dce3f1-1133-3084-c5f4-7a5d6d0d6cf8
* Version Independent ID: 31579324-f0e5-607a-caa1-ec31b444af79
* Content: [Find an admin or organization owner - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/security/lookup-organization-owner-admin?view=azure-devops&tabs=preview-page)
* Content Source: [docs/organizations/security/lookup-organization-owner-admin.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/security/lookup-organization-owner-admin.md)
* Product: **devops**
* Technology: **devops-security**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by msebolt** [comment]
@fiksen99  Thank you for the question.

You will need at minimum basic access to see this information, please refer to these [FAQ](https://docs.microsoft.com/azure/devops/organizations/accounts/faq-change-organization-ownership?view=azure-devops).

Private repos with no access allow no information to be accessed, unless alternatively an organization decides to create a public facing wiki, help page, etc.

If the screen is misleading, please include the details below and start a ticket in the [Azure DevOps Community](https://developercommunity.visualstudio.com/topics/Azure+DevOps.html).  Include a link to this issue and the product team can review and assess.
