### ISSUE TITLE
Export and select several suites when create requierement -based suites

### ISSUE THREAD

**Issue by Dede24** [MicrosoftDocs/vsts-docs#5995]
In your "new test plans page", you indicate that export will be added in 3 weeks. Did you have an approximative date that this option "Export" is available.
Other question, when we create a "New suite" with "Requirement based suites", it isn't possible to select many US, in the old view it was possible. Will be possible to add this option in the new view.
Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3c520dee-1218-777e-7405-551623817c03
* Version Independent ID: 82b5d172-ae1a-2b4c-82ac-595cd7609d3c
* Content: [New test plans page - Azure Test Plans](https://docs.microsoft.com/en-us/azure/devops/test/new-test-plans-page?view=azure-devops)
* Content Source: [docs/test/new-test-plans-page.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/test/new-test-plans-page.md)
* Product: **devops**
* Technology: **devops-test**
* GitHub Login: @harishkragarwal
* Microsoft Alias: **harishkragarwal**

**Comment by harishkragarwal** [comment]
Hi, both capabilities are likely are reach production around end of Nov.
