### ISSUE TITLE
How to set a configuration key for a slot?

### ISSUE THREAD

**Issue by katlimruiz** [MicrosoftDocs/vsts-docs#5998]
I have two slots: production and pre-prod.
I want to add config WEBJOBS_STOPPED=1 to pre-prod, but on production set WEBJOBS_STOPPED=0.
This so the pre-prod slot does not run its webjobs.
How can I do it with yaml task?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 29c94df7-9de9-ea1a-8b77-d1e6023694dc
* Version Independent ID: a525989e-2e0a-0399-556e-9011ee95da4e
* Content: [Azure App Service Deploy task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-rm-web-app-deployment?view=azure-devops)
* Content Source: [docs/pipelines/tasks/deploy/azure-rm-web-app-deployment.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/deploy/azure-rm-web-app-deployment.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by msebolt** [comment]
@katlimruiz Thank you for the question.

If you don't mind including a [Azure CLI task](https://docs.microsoft.com/azure/devops/pipelines/tasks/deploy/azure-cli?view=azure-devops), you can make a call to [az webapp config appsettings set](https://docs.microsoft.com/cli/azure/webapp/config/appsettings?view=azure-cli-latest#az-webapp-config-appsettings-set).

Please comment if there are issues with this approach.

**Comment by msebolt** [comment]
Closing the issue now.
