### ISSUE TITLE
Task.json Guid Error

### ISSUE THREAD

**Issue by singhp27** [MicrosoftDocs/vsts-docs#600]
Hey guys, 
When I upload vsix file it through me an error "Error converting value "{{taskguid}}" to type 'System.Guid'. Path 'id', line 3, position 24..". Any suggestions?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 44581f4a-93df-7507-3844-eadedf9a6cc4
* Version Independent ID: 33c7bcf0-1512-975f-5ef8-9f2a192a84ad
* Content: [Add a Build or Release Task](https://docs.microsoft.com/en-us/vsts/extend/develop/add-build-task?view=vsts#step-1-create-the-task-metadata-file)
* Content Source: [docs/extend/develop/add-build-task.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/extend/develop/add-build-task.md)
* Service: **unspecified**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by elbatk** [comment]
Hey @singhp27 , our resident "Extend" guy is on paternity leave right now but I'll try to track down someone else that can try to help you out here!

**Comment by Jashuva-D** [comment]
Replace your guid  "{{taskguid}}"  with one of the following..
Example guid s are given below :

                                "ca761232ed4211cebacd00aa0057b223",
                               "CA761232-ED42-11CE-BACD-00AA0057B223", 
                               "{CA761232-ED42-11CE-BACD-00AA0057B223}", 
                               "(CA761232-ED42-11CE-BACD-00AA0057B223)", 
                               "{0xCA761232, 0xED42, 0x11CE, {0xBA, 0xCD, 0x00, 0xAA, 0x00, 0x57, 0xB2, 0x23}}"


For Reference check below link:
https://msdn.microsoft.com/en-us/library/96ff78dc(v=vs.110).aspx

**Comment by elbatk** [comment]
Closing this issue as I think this is a valid solution, feel free to reopen and comment if you're still having trouble @singhp27 , thank you @Jashuva-D
