### ISSUE TITLE
There is a **not always** 2000 character limit recognized by browsers.

### ISSUE THREAD

**Issue by jamesjnadeau** [MicrosoftDocs/vsts-docs#6008]
I believe that 2000 character limit should be warned about, but it is not a hard stop. According to RFC 2616 (Hypertext Transfer Protocol HTTP/1.1) section 3.2.1 says:
```
The HTTP protocol does not place any a priori limit on the length of a URI. Servers MUST be able to handle the URI of any resource they serve, and SHOULD be able to handle URIs of unbounded length if they provide GET-based forms that could generate such URIs. A server SHOULD return 414 (Request-URI Too Long) status if a URI is longer than the server can handle (see section 10.4.15).
```
Perhaps supplying information on what the Azures servers limits are would be helpful? 

Most clients today support much more than a 2K limit. I think you should reword the Tip:
```
There is a 2000 character limit recognized by browsers.
```
to
```
Be sure to keep in mind that some clients impose a 2000 character limit on urls.
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1debd814-eb48-c984-a4f9-7606093e9617
* Version Independent ID: f48ef796-c2e3-8fa3-6c41-326a5b252a3d
* Content: [Add and use work item templates to update user stories, tasks, issues, and other work items - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/backlogs/work-item-template?view=azure-devops&tabs=browser#feedback)
* Content Source: [docs/boards/backlogs/work-item-template.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/boards/backlogs/work-item-template.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by msebolt** [comment]
@jamesjnadeau Thank you for the insightful feedback.

The documentation has been updated as noted and is under review.
