### ISSUE TITLE
Need Azure DevOps Locations

### ISSUE THREAD

**Issue by livehands** [MicrosoftDocs/vsts-docs#6009]
Add Links to the Azure DevOps Locations available worldwide.  Needed to find the locations for a customer in UK but when I search this is the document that shows so a "Other Resources" section which has a link to the listing of the locations available.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be194f45-05b2-8421-186f-f12700eea9aa
* Version Independent ID: efffdc56-fd4c-aeba-6cd3-d07aaf776d51
* Content: [Find or change location or region of organization - Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/change-organization-location?view=azure-devops#feedback)
* Content Source: [docs/organizations/accounts/change-organization-location.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/accounts/change-organization-location.md)
* Product: **devops**
* Technology: **devops-accounts**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by msebolt** [comment]
@livehands  Thank you for the feedback, assigning this to the author for review.

Perhaps [data locations for Azure DevOps](https://docs.microsoft.com/azure/devops/organizations/security/data-location?view=azure-devops) is what you had in mind?

**Comment by livehands** [comment]
Yes!  That is the link that would be useful
