### ISSUE TITLE
Document the purpose of "Commit changes after merge by default"

### ISSUE THREAD

**Issue by kraigb** [MicrosoftDocs/vsts-docs#601]
This option is visible in Team Explorer > Settings > Git Settings, and the "Learn More" link comes to this article, but the article doesn't say anything about the option at all. Nor does it say anything about the other checkboxes, for that matter.

The "Commit after merge" option is problematic for Python projects in VS that create virtual environments, because it causes the venv to be committed to source control immediately, and then you can't actually exclude it from source control from within VS (you have to use git rm -r on the command line and edit .gitignore manually).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3c28e08d-10ad-65f0-7145-0dcc9c94d780
* Version Independent ID: ca19fff9-06fa-6f95-a2fc-df12a7849112
* Content: [gitconfig files](https://docs.microsoft.com/en-us/vsts/git/concepts/git-config?tabs=visual-studio&view=vsts)
* Content Source: [docs/git/concepts/git-config.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/git/concepts/git-config.md)
* Service: **unspecified**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
@kraigb I just submitted a PR that contains significant updates to this article including that option - it should be live soon. Thank you for your feedback.

**Comment by kraigb** [comment]
Can you give me the link to the PR here?
