### ISSUE TITLE
"Team Foundation Server / Azure Pipelines service connection" option not available

### ISSUE THREAD

**Issue by ggirard07** [MicrosoftDocs/vsts-docs#6011]
I don't this is option listed in the new service connection dialog.
Only related option is `Azure Repos/Team Foundation Server`, but this connection takes a link to the external organization, not the pipeline I want to link to. Once created, it does not add any new entry in the pipeline/release creation UI (I can only access pipelines in my current organization).

Is this service connection still supported?
How can I configure it now since it is no longer available in the create service connection wizard?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72b90dd0-49f9-4ed4-3010-9a64dde6ae5a
* Version Independent ID: 6e679d50-4e94-eee3-8793-af884cc909ca
* Content: [Service connections in Azure Pipelines and Team Foundation Server - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/library/service-endpoints?view=azure-devops&tabs=classic#create-new)
* Content Source: [docs/pipelines/library/service-endpoints.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/library/service-endpoints.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by RoopeshNair** [comment]
Team Foundation Server service connection is through an extension. https://marketplace.visualstudio.com/items?itemName=ms-vscs-rm.vss-services-externaltfs

**Comment by ggirard07** [comment]
@RoopeshNair `Team Foundation Server / Azure Pipelines service connection` was the name of the option, but I am looking for the `Azure Pipelines` connection part. I am not interested in the `Team Foundation Server` connection part.

How to add a service connection to an azure pipeline in an external organization now that this service connection is gone?

**Comment by dootdootbeep** [comment]
> @RoopeshNair `Team Foundation Server / Azure Pipelines service connection` was the name of the option, but I am looking for the `Azure Pipelines` connection part. I am not interested in the `Team Foundation Server` connection part.
> 
> How to add a service connection to an azure pipeline in an external organization now that this service connection is gone?

In case anyone else finds this, the extension mentioned by RoopeshNair works with the "Team Foundation Server / Azure Pipelines" service connection. **It works with both TFS and Azure DevOps.**

It adds the options to select Artifacts from the external TFS/Azure DevOps build pipelines, Git Repo, TFVC, or external XAML build definition.  

![image](https://user-images.githubusercontent.com/24483326/72372182-e539ef00-36d3-11ea-9f21-77e06cc487dc.png)
