### ISSUE TITLE
GitHub PR trigger: checking out head vs merge

### ISSUE THREAD

**Issue by chuckatkins** [MicrosoftDocs/vsts-docs#6012]
When using PR triggers, is there a way for the checkout step to use the HEAD of the PR instead of the merge of the pr?

**Comment by msebolt** [comment]
@checkatkins  Thank you for the question.

Azure DevOps has some newer PR features such as **Rebase**, see [this blog post](https://devblogs.microsoft.com/devops/pull-requests-with-rebase/).

However, for more advanced commands, you're left with writing your own [Git task scripts](https://docs.microsoft.com/azure/devops/pipelines/scripts/git-commands?view=azure-devops&tabs=yaml#q--a).

If this still doesn't answer your question, please reference one of the articles or use the [Azure DevOps Community](https://developercommunity.visualstudio.com/spaces/21/index.html) to start a dialog with the product team.
