### ISSUE TITLE
Markdown syntax for anchor links requires "user-content" in wiki

### ISSUE THREAD

**Issue by johnmbaughman** [MicrosoftDocs/vsts-docs#6015]
The documentation shows standard Markdown syntax, but through trial and error I discovered that doesn't work.

To reach a heading like so
```
### My Heading ###
```

The syntax _should_ be
```
[My Heading](#my-heading)
```

Instead, it's
```
[My Heading](#user-content-my-heading)
```

Is there a reason for this? Should the really Markdown syntax work?

Thanks!

-John

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fa622358-f5bb-1f5c-177a-081a37b6acef
* Version Independent ID: 72f7fd16-a822-66c8-3a34-8905645ce5f2
* Content: [Markdown syntax for files, widgets, and wikis in Azure DevOps - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/project/wiki/markdown-guidance?view=azure-devops#feedback)
* Content Source: [docs/project/wiki/markdown-guidance.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/project/wiki/markdown-guidance.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by msebolt** [comment]
@johnmbaughman Thank you for the feedback.

This should probably be moved to the Azure DevOps Community for the product team to handle.

There is a related open-ticket item [here](https://developercommunity.visualstudio.com/content/problem/762156/wiki-anchor-links.html) where you can provide a link to this issue.
