### ISSUE TITLE
relation to https://github.com/microsoft/azure-pipelines-artifact-caching-tasks

### ISSUE THREAD

**Issue by cforce** [MicrosoftDocs/vsts-docs#6020]
Can you explain what is task "ESLighthouseEng.PipelineArtifactCaching" despite to to  "CacheBeta" ?

**Comment by WilliamAntonRohm** [comment]
@cforce -- Fabian, here is the answer from the code owner:

> The “1ESLighthouseEng.PipelineArtifactCaching” is a task that predates the “CacheBeta” task. The differences are that the “1ESLighthouseEng” task is packaged as an extension and is not officially supported (so it’s published by Microsoft DevLabs). The “CacheBeta” task is built by the Azure DevOps PG and is the officially supported caching task in Azure Pipelines.

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
