### ISSUE TITLE
Column options

### ISSUE THREAD

**Issue by RvsValori** [MicrosoftDocs/vsts-docs#6022]
In the define/execute tab am able to add additional columns, but I am not able to remove an _additional_ column once added because 'At least one column is required'. I get that there needs to be at least one column in the view, but I am not able to change the 5+ columns that are there by default to begin with.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3c520dee-1218-777e-7405-551623817c03
* Version Independent ID: 82b5d172-ae1a-2b4c-82ac-595cd7609d3c
* Content: [New test plans page - Azure Test Plans](https://docs.microsoft.com/en-us/azure/devops/test/new-test-plans-page?view=azure-devops#feedback)
* Content Source: [docs/test/new-test-plans-page.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/test/new-test-plans-page.md)
* Product: **devops**
* Technology: **devops-test**
* GitHub Login: @harishkragarwal
* Microsoft Alias: **harishkragarwal**

**Comment by harishkragarwal** [comment]
Hi, thanks for reporting this. We are aware of this and will be fixing it as part of upcoming sprints.
