### ISSUE TITLE
Topic branch condition doesn't work for feature/release branches

### ISSUE THREAD

**Issue by RobCoPKC** [MicrosoftDocs/vsts-docs#6024]
Hey there,

I'm currently trying to include certain tasks depending on which branch I'm building.

For example I want to run SonarCloud analysis for all feature branches:
- task: SonarCloudPrepare@1
  condition: and(always(), startsWith(variables['Build.SourceBranch'], 'refs/heads/feature/''))

However I am receiving the following error:
Job Job: Step specifies condition and(always(), startsWith(variables['Build.SourceBranch'], 'refs/heads/feature/'')) which is not valid. Reason: Unrecognized value: ''refs/heads/feature/''))'. Located at position 59 within expression: and(always(), startsWith(variables['Build.SourceBranch'], 'refs/heads/feature/'')). For more help, refer to https://go.microsoft.com/fwlink/?linkid=842996

How can I fix this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f151218-9a11-0078-e038-f96198a76143
* Version Independent ID: 09c4d032-62f3-d97c-79d7-6fbfd89910e9
* Content: [Conditions - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/conditions?view=azure-devops&tabs=yaml#feedback)
* Content Source: [docs/pipelines/process/conditions.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/conditions.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by RobCoPKC** [comment]
Nevermind, I am an idiot and didn't notice the second apostrophe.

Please close this issue.

**Comment by WilliamAntonRohm** [comment]
@RobCoPKC -- thank you for your feedback :)
