### ISSUE TITLE
No variable for the agent pool name?

### ISSUE THREAD

**Issue by rrnielsen** [MicrosoftDocs/vsts-docs#6029]
I am surprised that there is no variable for the name of the agent pool.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ffebdc8-521c-44b5-cde4-4abdc1bd6f18
* Version Independent ID: dc0effda-6d93-62aa-64c5-4e6f283b0826
* Content: [Predefined variables - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml#feedback)
* Content Source: [docs/pipelines/build/variables.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/build/variables.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by juliakm** [comment]
I've confirmed that there is no predefined variable for the agent pool name that needs to be added to our documentation. You can reach out to the [Azure DevOps Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html), which is monitored by the product team, to submit a feature request.
