### ISSUE TITLE
No information on configuring the Kubernetes Service Endpoint for AKS

### ISSUE THREAD

**Issue by hashtagchris** [MicrosoftDocs/vsts-docs#603]
This doc doesn't mention the "Kubernetes Service Connection" task input at all, and doesn't tell you how to add a the Kubernetes Service Endpoint for AKS. I was lost until I found a related walkthrough, https://almvm.azurewebsites.net/labs/vstsextend/kubernetes/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a86dced-9bbf-5b3d-f373-ff2568f20efa
* Version Independent ID: 65d17578-9c65-bc4c-1e13-985f7beaf80d
* Content: [CD Kubernetes to Azure Container Service](https://docs.microsoft.com/en-us/vsts/build-release/apps/cd/azure/deploy-container-kubernetes?view=vsts)
* Content Source: [docs/build-release/apps/cd/azure/deploy-container-kubernetes.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/build-release/apps/cd/azure/deploy-container-kubernetes.md)
* Service: **unspecified**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment]
Thank you for your feedback. We are currently working on a new version of this topic. I'm sorry you had issues using it. I will temporarily redirect to the lab topic you used.
