### ISSUE TITLE
Dark theme squashes formatting example

### ISSUE THREAD

**Issue by v-wilock** [MicrosoftDocs/vsts-docs#6034]
The text
"The project status is GREEN even though the bug count / developer may be in red. - Capability of span"
shows up all in white for me. I'm using the dark theme.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 29f1e43f-a069-dd88-7fc7-9cc497fb94f0
* Version Independent ID: c261afa7-6eb7-b3f0-9f92-6d2f3c5ac336
* Content: [Markdown syntax for wikis in Azure DevOps - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/project/wiki/wiki-markdown-guidance?view=azure-devops)
* Content Source: [docs/project/wiki/wiki-markdown-guidance.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/project/wiki/wiki-markdown-guidance.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by msebolt** [comment]
@v-wilock  Thank you for the feedback.

This currently has an open issue posted [here](https://developercommunity.visualstudio.com/idea/542332/wiki-header-colors-for-dark-theme.html).

Please add your comments there to get a response from the product team.

**Comment by v-wilock** [comment]
@msebolt - That issue is specifically for headers, as opposed to - presumably - spans.

**Comment by msebolt** [comment]
@v-wilock  Then you'll need to create a new issue, though link back to this in both cases.
