### ISSUE TITLE
Access to $(rev:r) outside of name:

### ISSUE THREAD

**Issue by henry-padilla** [MicrosoftDocs/vsts-docs#6036]
We should be able to use $(rev:r) in fields other than name. I would like to name the run with the pipeline name AND the build version, like so:
$(Build.DefinitionName)-$(Major).$(Minor).$(rev:r)

But when I try to use the $(Build.BuildNumber) to update the version it isn't formatted as a semantic version so I get an error. If I could use $(rev:r) in a variable it would be a great help.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a57f8545-bb15-3a71-1876-3a9ec1a59b93
* Version Independent ID: 28c87c8d-c28d-7493-0c7c-8c38b04fbcd7
* Content: [Run number - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/run-number?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/process/run-number.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/run-number.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by msebolt** [comment]
@henry-padilla  Thank you for the feedback.

Unfortunately this seems like more of a product issue then documentation concern.

Please move this issue to the [Azure DevOps Community](https://developercommunity.visualstudio.com/spaces/21/index.html) where the product team can address.

**Comment by fhurta** [comment]
@henry-padilla Did you succeed with getting $(rev:r) outside the name? I would like to get it as well..

**Comment by padillah** [comment]
@fhurta No. The best I could do was use the $(Build.BuildNumber) that was created from $(Rev:r)

If you have to you can always parse $(Build.BuildNumber) and get the $(Rev:r)

**Comment by fhurta** [comment]
> @fhurta No. The best I could do was use the $(Build.BuildNumber) that was created from $(Rev:r)
> 
> If you have to you can always parse $(Build.BuildNumber) and get the $(Rev:r)

Ok, thanks!
