### ISSUE TITLE
IdentityFile in ssh config should point to the private key file instead of the public one

### ISSUE THREAD

**Issue by timotgl** [MicrosoftDocs/vsts-docs#6037]
The page "Use SSH key authentication" answers the question ["I have multiple SSH keys. How do I use different SSH keys for different SSH servers or repos?"](https://docs.microsoft.com/en-us/azure/devops/repos/git/use-ssh-keys-to-authenticate?view=azure-devops#i-have-multiple-ssh-keys--how-do-i-use-different-ssh-keys-for-different-ssh-servers-or-repos) with an example of a `.ssh/config` file. In this snippet, the `IdentityFile` seems to point to a public key. This is wrong according to https://unix.stackexchange.com/questions/516207/is-file-specified-in-ssh-config-identityfile-private-or-public-key and also personal experience. It should point to the private key.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 64e85ff9-9add-d15c-e92f-02d7dd05e0f2
* Version Independent ID: 0cbd7427-6acd-3cfc-1a3b-8bf5ca60f3bd
* Content: [Connect to your Git repos with SSH - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/use-ssh-keys-to-authenticate?view=azure-devops)
* Content Source: [docs/repos/git/use-ssh-keys-to-authenticate.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/repos/git/use-ssh-keys-to-authenticate.md)
* Product: **devops**
* Technology: **devops-code-git**
* GitHub Login: @apawast
* Microsoft Alias: **sdanie**

**Comment by marcpopMSFT** [comment]
Working on updating this
