### ISSUE TITLE
vstsFeed is for Restore, not Push

### ISSUE THREAD

**Issue by henry-padilla** [MicrosoftDocs/vsts-docs#6038]
If you look at the GitHub project you will see the parameter to use for push is 'feedPublish'.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0fa37a3f-6551-16ad-e164-a4ac522cdaab
* Version Independent ID: a3fd6935-2b99-92ef-4eb3-3249fca01f8a
* Content: [NuGet restore, pack, and publish task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/package/nuget?view=azure-devops)
* Content Source: [docs/pipelines/tasks/package/nuget.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/package/nuget.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @chasewilson
* Microsoft Alias: **phwilson**

**Comment by koskila** [comment]
Isn't it "publishVstsFeed" ? That's documented on the page, but it indeed looks to be wrong in the example...
