### ISSUE TITLE
Reading and writing the response.

### ISSUE THREAD

**Issue by verodhi** [MicrosoftDocs/vsts-docs#6040]
I am trying to provide a json file from project directory as the body.
How can i do that? Documentation does not address it.

**Comment by msebolt** [comment]
@verodhi Thank you for the questions.

Most of the Azure DevOps [Web APIs](https://docs.microsoft.com/rest/api/azure/devops/?view=azure-devops-rest-5.1) return JSON.

For instance, calling:

```
GET https://feeds.dev.azure.com/{organization}/{project}/_apis/packaging/Feeds/{feedId}/packages?api-version=5.1-preview.1
```

...returns a JSON set of your project's packages.

What exact information do you need to send as JSON?

**Comment by verodhi** [comment]
@msebolt 

My apologies, I think I was not clear:

I am trying to execute an agentless task in DevOps; Namely: **[Invoke REST API Task](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/http-rest-api?view=azure-devops)**

It allows passing body as parameter i.e:

`- task: InvokeRESTAPI@1
  inputs:
    connectionType: 'connectedServiceName'
    serviceConnection: 'exampleconnection'
    method: 'POST'
    headers: |
      {
      "Content-Type":"application/json"
      }
    body: '{"json":"body"}'
    waitForCompletion: 'false'`

In the body field above I want to pass a json that is sitting in my project root directory as a file, i.e. appsettings.json
I was wondering how can I do that.
Thank you

**Comment by msebolt** [comment]
@verodhi Apologies for the delay.

This would require a custom solution based on either using the [Azure DevOps API](https://docs.microsoft.com/en-us/rest/api/azure/devops/distributedtask/variablegroups/update?view=azure-devops-rest-5.1) or something from the Marketplace:
- [file to variable](https://marketplace.visualstudio.com/items?itemName=maikvandergaag.maikvandergaag-file-to-variable)
- [json to variable](https://marketplace.visualstudio.com/items?itemName=OneLuckiDev.json2variable)

You could then use the **InvokeRESTAPI** task with the loaded file variable.

**Comment by msebolt** [comment]
Closing now, please comment below if there are further issues.
