### ISSUE TITLE
Jobs not running sequentially on self-hosted agent

### ISSUE THREAD

**Issue by Tr3yb0** [MicrosoftDocs/vsts-docs#6041]
I am running a single stage with 4 jobs in it. I originally had one job with dependsOn in it and the order of my jobs did not match the defined order. When I removed the dependsOn field, the order was preserved, but the actual processing order was seemingly random. I am under the impression that if no order is specified, the jobs will run in the order they are defined in the yaml. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 67504b34-d64b-02a4-2e10-ab99f3b8cfe4
* Version Independent ID: 2cf63b2e-184b-7726-3b8a-d8baffd6fcce
* Content: [Jobs in Azure Pipelines, Azure DevOps Server, and TFS - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/phases?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/process/phases.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/phases.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @vijayma
* Microsoft Alias: **vijayma**

**Comment by msebolt** [comment]
@Tr3yb0 Thank you for the feedback.

There is an active issue in the Developer Community [here](https://developercommunity.visualstudio.com/idea/611313/pipeline-job-ordering-in-ui-should-follow-order-in.html).

Follow this and/or add comments to get the product team's response.

**Comment by vijayma** [comment]
From an execution perspective, if you do not specify a 'dependsOn' between jobs in a stage, they run in parallel (provided you have enough concurrency/agents to run all of them). If you do not specify a 'dependsOn' between stages in a pipeline, they run in sequence in the order they are specified in the YAML file. It was not clear from your description if (a) you are not seeing this behavior in the execution or (b) if you are seeing this in the execution, but the UI does not render them in the correct order. Can you clarify that?
