### ISSUE TITLE
Flake8 return code not captured

### ISSUE THREAD

**Issue by davewilton** [MicrosoftDocs/vsts-docs#6044]
When I added this script as described in the document

- script: |
    python -m pip install flake8
    flake8 .
  displayName: 'Run lint tests'

The build didn't actually fail when the the lint failed, seems like it is not checking the return code?

This worked fine. 

- bash: 'flake8 .'
  displayName: 'run flake8'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2ca42420-9324-1988-16bd-501be69e278d
* Version Independent ID: 400c0122-a0cc-bb52-b6cc-8aa93ff2c47a
* Content: [Build and test Python apps - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/ecosystems/python?view=azure-devops#feedback)
* Content Source: [docs/pipelines/ecosystems/python.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/ecosystems/python.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @thomps23
* Microsoft Alias: **dastahel**

**Comment by msebolt** [comment]
@davewilton Thank you for the feedback and diagnosis.

Unfortunately this needs to involve the product team.

Please move the issue to the [azure-pipelines-tasks](https://github.com/Microsoft/azure-pipelines-tasks/issues) repo.
