### ISSUE TITLE
Azure App Service Deploy vs. Azure Function App vs. Azure Web App - which should I use ?

### ISSUE THREAD

**Issue by sengokyu** [MicrosoftDocs/vsts-docs#6045]
Each 3 tasks can deploy an application to Azure App Service.
- Azure App Service Deploy
- Azure Function App
- Azure Web App
Which do you recommend ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e7ba5cf3-d229-03d0-ad6a-a30a0379afc0
* Version Independent ID: ccffed3b-ea44-517f-f7a8-a1c4c4147495
* Content: [Catalog of the built-in tasks for build-release and Azure Pipelines & TFS - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/index?view=azure-devops#feedback)
* Content Source: [docs/pipelines/tasks/index.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/index.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by msebolt** [comment]
@sengokyu  Thank you for the question.

I'd recommend the [Azure App Service task](https://docs.microsoft.com/azure/devops/pipelines/tasks/deploy/azure-rm-web-app-deployment?view=azure-devops) as it provides a single framework to experiment with each.

This topic also includes links to information for each service type so you can decide which best fits your needs.
