### ISSUE TITLE
Bugs not linked

### ISSUE THREAD

**Issue by TroySchmidt** [MicrosoftDocs/vsts-docs#6046]
Are bugs not linked automatically?  The work item that was part of a commit is linked.  However, the bug that was linked to the pull request that contained the commit that was linked to a task was not shown.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 462be419-4cfd-4bfc-06cc-45800c0d888b
* Version Independent ID: 95cb8a7d-c61d-dfac-403f-12fe40ba1c49
* Content: [Link work items to deployments - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/work-items/work-item-deployments-control?view=azure-devops)
* Content Source: [docs/boards/work-items/work-item-deployments-control.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/boards/work-items/work-item-deployments-control.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by msebolt** [comment]
@TroySchmidt Thank you for the question.

Are you using the [Agile process](https://docs.microsoft.com/azure/devops/boards/get-started/plan-track-work?view=azure-devops&tabs=agile-process)?

Bug tracking doesn't appear to be available in the **basic process**, see [Show bugs on backlog](https://docs.microsoft.com/azure/devops/organizations/settings/show-bugs-on-backlog?view=azure-devops).

**Comment by TroySchmidt** [comment]
We are using a scrum customized process.  I think there are other things
not tailored to scrum process.

**Comment by nsinclair09** [comment]
We are using a customized agile process -  However, We do have "Working with Bugs" set to "Bugs are managed with requirements" and are still seeing this issue.  I'm unable to see were it is deployed after it has been released.

**Comment by msebolt** [comment]
Unfortunately, this is a product issue and should be handled by the [Azure DevOps Community](https://developercommunity.visualstudio.com/spaces/21/index.html).

Please use either **Report a problem** or **Suggest a feature** and link back to this issue to get the product team's feedback.
