### ISSUE TITLE
Cannot seem to give wiki edit permissions

### ISSUE THREAD

**Issue by ideoclickVanessa** [MicrosoftDocs/vsts-docs#6047]
I created a new Wiki Editors group and added users to it.  I also set the group's wiki permissions identical to Contributors like so:
![image](https://user-images.githubusercontent.com/44000426/67063727-a61ff000-f11c-11e9-97d9-9e893feaddd2.png)
however, the users only seem to get read access not write.  I'm also pretty sure the users are not stakeholders since their type says `user`:
![image](https://user-images.githubusercontent.com/44000426/67063837-0e6ed180-f11d-11e9-8f23-2633f15fef1b.png)

Can you please clarify what I'm missing?  As it is, the steps in this document don't seem to work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c86f5178-e331-f45e-b60a-f0f3955f7a08
* Version Independent ID: 8a0882a7-8f48-32bb-c741-12976b428c38
* Content: [Manage permissions for READMEs and wiki pages in Azure DevOps - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/project/wiki/manage-readme-wiki-permissions?view=azure-devops#feedback)
* Content Source: [docs/project/wiki/manage-readme-wiki-permissions.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/project/wiki/manage-readme-wiki-permissions.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by msebolt** [comment]
@ideoclickVanessa Thank you for the feedback, assigning this to the author for review.

**Comment by chcomley** [comment]
Hi @ideoclickVanessa, 

Wiki is backed by a Git repository, so the Contribute permissions set at the Git repo level are honored for Wiki. But, if the user is part of more than 1 group, and the Contribute permission is set to _Deny_ in any one group, then it will take precedence and the user won't be able to edit the wiki. 

Example:
Group-1 (Wiki Reader)  has User-1, User-2, and User-3 
Group-2 (Wiki Editor) has User-1, User-4

Contribute permission for Group-2 (Wiki Editor) is set to “Allow” and for Group-1 (Wiki Reader) it is set to “Deny”. Then even User-1 won't be able to edit wiki because their contribute permission is set to _Deny_ in one of the groups. 

Please @mention me to let me know whether you have any further questions. Thank you!

**Comment by ideoclickVanessa** [comment]
HI @chcomley,

Thanks for the additional information. It likely should be added to the article.
That said, I've confirmed that the user is only in one group which is the Wiki Editors group I posted in my OP.  Yet, they are still unable to edit.

**Comment by ideoclickVanessa** [comment]
Hi @chcomley,

I've double-checked with the user and they provided the below screenshot with all of the edit features greyed out:
![image](https://user-images.githubusercontent.com/44000426/67430567-5a939900-f597-11e9-8dd7-474fc26ca789.png)

Can I please get an update on how to correctly give the user edit permissions?

**Comment by chcomley** [comment]
Hi @ideoclickVanessa,

Can you please share answers to the following questions:
1.	Was the user able to edit the Wiki if they were added to “Contributors” group directly instead of “Wiki Editors”?
2.	Is this issue happening with a specific user or anyone who was added to “Wiki Editors” group were unable to edit the Wiki?

Thank you!

**Comment by ideoclickVanessa** [comment]
Hi @chcomley,

I'm not willing to do 1 as the user is external to the company.

I do have access to a different account (let's call it `x`) that is normally part of the default "Readers" group.  I logged in as `x` and verified that I could not edit the wiki.  I then removed `x` from "Readers" and added `x` to "Wiki Editors".  I logged back in as `x` and verified that I could now successfully edit the wiki. 

This leads me to believe that the issue is happening with just that specific user :(  I removed the specific user from the "Wiki Editors" group and then re-added them in hopes that it resets their permissions.  I'm still waiting to hear back on whether this was successful.  If it's not, what are my next steps?

Thanks.

**Comment by vivekjilla** [comment]
Hi @ideoclickVanessa  To get more info on what permissions a user has (and why), we can do the following:

Go to Wiki Security Dialog.
1. Click +Add..  button and select that user and them.
2. The User should now be visible in the users section. Click on that user to know what permission they have,
3. Click on the "why" beside the "contribute" permission to open the trace permission dialog
4. We will get an idea on why/how the user got that permission.

Screenshots to help:

![image](https://user-images.githubusercontent.com/6436807/67454377-9ede7200-f647-11e9-989c-d05278f300a0.png)
![image](https://user-images.githubusercontent.com/6436807/67454492-e49b3a80-f647-11e9-9a7b-20569e73e767.png)

Thank you.

**Comment by ideoclickVanessa** [comment]
Hi @chcomley,

I'm still waiting to hear back from the user whether the permissions are finally fixed for them; however, the following two screenshots makes it seem like it should:
![image](https://user-images.githubusercontent.com/44000426/67496090-b9592100-f630-11e9-9d97-3beed0fcc5a6.png)
![image](https://user-images.githubusercontent.com/44000426/67496204-e9082900-f630-11e9-8866-35920a707fcc.png)

I'm going to wait until I hear back from the user before I close this out, but thanks for the troubleshooting help particularly since the git repo permissions don't map that clearly to the wiki permissions.

**Comment by ideoclickVanessa** [comment]
While I visually confirmed with the user on Friday that they still can't edit the wiki even though their permissions match the above, I'm going to go ahead and close this issue since I can successfully give other users wiki edit permissions.

**Comment by chcomley** [comment]
Thank you for letting us know, @ideoclickVanessa. Have a nice day!

**Comment by NorthHighlandNicole** [comment]
I'm having the EXACT same issue. I've checked the user's groups and there are no "deny" permission set on "contribute" and "read" the wiki. Yet they still get the grayed out edit button. Additionally in the permissions for the wiki I explicitly set the user to allow for everything. Please help this is ridiculous that it shows they have permissions and yet they do not.

**Comment by rafaheringer** [comment]
I'm having the same issue too. In the same circumstances. I double checked the permissions and the hierarchy. And I explicitly set the user permission for everything.

**Comment by chcomley** [comment]
Hi @NorthHighlandNicole, This sounds like a case for Support. Please go [here ](https://developercommunity.visualstudio.com/spaces/21/index.html) and select **Report a problem**. Thank you.

**Comment by RFQED** [comment]
Try changing the user from a 'stakeholder' to 'basic' - https://manishkutar.wordpress.com/2020/08/05/azure-devops-edit-non-editable-wiki/
