### ISSUE TITLE
Errors on testing ENV:AZP_WORK in start.ps1 

### ISSUE THREAD

**Issue by tonkon** [MicrosoftDocs/vsts-docs#6048]
Should consider testing both Env:AZP_WORK and $Env:AZP_WORK. 

if (Test-Path Env:AZP_WORK) {
    if (-not (Test-Path $Env:AZP_WORK)) {
        New-Item $Env:AZP_WORK -ItemType directory | Out-Null
    }
}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b31d4f6c-d16d-2ba1-1294-6aa94e328046
* Version Independent ID: 88aec599-4410-697d-1002-1c41b1c17bb6
* Content: [Running a self-hosted agent in Docker - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/docker?view=azure-devops#)
* Content Source: [docs/pipelines/agents/docker.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/agents/docker.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by msebolt** [comment]
@tonkon  Thank you for the feedback, assigning this to the author for review.

**Comment by tonkon** [comment]
The issue is fixed in ee97732de5e523715741a102b86ad5f181494ca7.
