### ISSUE TITLE
Counterpart to startsWith?

### ISSUE THREAD

**Issue by RobCoPKC** [MicrosoftDocs/vsts-docs#6049]
Hey there,

is there any counterpart to the "startsWith"-parameter?
I would like to execute a task for all non-release-branches.

Kind regards,
Robin

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f151218-9a11-0078-e038-f96198a76143
* Version Independent ID: 09c4d032-62f3-d97c-79d7-6fbfd89910e9
* Content: [Conditions - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/conditions?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/process/conditions.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/conditions.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by msebolt** [comment]
@RobCoPKC Thank you for the question.

Please refer to either `contains` or `endsWith` in [functions](https://docs.microsoft.com/azure/devops/pipelines/process/expressions?view=azure-devops#functions).

What do you mean by counterpart?

**Comment by RobCoPKC** [comment]
The counterpart to "eq" would be "ne".
So I'm basically asking if there is a "doesntStartWith"-parameter.

Kind regards, 
Robin

**Comment by msebolt** [comment]
Thank you for clarifying.  You will need to use `not`, such as:

```
not(startsWith('ABCDE', 'AB'))
```

**Comment by RobCoPKC** [comment]
Works flawlessly.
Thank you very much!
Please close this issue.


Kind regards,

Robin
