### ISSUE TITLE
Add a note what is supported by which TFS Version

### ISSUE THREAD

**Issue by kirkone** [MicrosoftDocs/vsts-docs#605]
Hi,
please add information about the availability of the different elements in the different versions of TFS.

For example the checkbox is not working in TFS 2017 but there is no hint about that.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 63e81f8a-e33c-afb7-493b-f51f40fafd49
* Version Independent ID: c9495a96-c3e8-00f1-1e53-da6ce584412b
* Content: [Syntax usage for Markdown files, widgets, wikis, and pull requests - VSTS & TFS](https://docs.microsoft.com/en-us/vsts/collaborate/markdown-guidance?view=vsts#feedback)
* Content Source: [docs/collaborate/markdown-guidance.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/collaborate/markdown-guidance.md)
* Service: **unspecified**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@kirkone - Thank you for your correction. I've updated the topic to better reflect which features are supported based on TFS version and the update should be published later today.
