### ISSUE TITLE
Issue trying to add new existing test cases

### ISSUE THREAD

**Issue by pablogiroud** [MicrosoftDocs/vsts-docs#6050]
How its happened:
I created a requirement based suite, then I added an existing test case. After that I deleted the suite, and created a new one associated with other case. When I try to add te existing test case (the same that I used in the deleted suite) the case is not added to the suite.

Steps to reproduce:
I follow the workflow to add: click on the suite &gt; Add existing test case &gt; run query &gt; Select the tests from the list &gt; add &gt; nothing happens, the suite is shown empty.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3c520dee-1218-777e-7405-551623817c03
* Version Independent ID: 82b5d172-ae1a-2b4c-82ac-595cd7609d3c
* Content: [New test plans page - Azure Test Plans](https://docs.microsoft.com/en-us/azure/devops/test/new-test-plans-page?view=azure-devops#feedback)
* Content Source: [docs/test/new-test-plans-page.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/test/new-test-plans-page.md)
* Product: **devops**
* Technology: **devops-test**
* GitHub Login: @harishkragarwal
* Microsoft Alias: **harishkragarwal**

**Comment by msebolt** [comment]
@pablogiroud Thank you for the question.

Unfortunately this would be better geared towards the product team.

Please start a thread in the [Azure DevOps community](https://developercommunity.visualstudio.com/spaces/21/index.html) and link back to this issue.
