### ISSUE TITLE
adding group/user to security of iteration using cli

### ISSUE THREAD

**Issue by Zaniar0** [MicrosoftDocs/vsts-docs#6052]
how do i add a user/group to iteration security using the cli?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 022fb627-3fc3-e748-8431-a4597bb27ad5
* Version Independent ID: 0b56992a-b121-6095-5a60-65548fdd5a3b
* Content: [Set permissions and access for work tracking - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/security/set-permissions-access-work-tracking?view=azure-devops#create-child-nodes-modify-work-items-under-an-area-path)
* Content Source: [docs/organizations/security/set-permissions-access-work-tracking.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/security/set-permissions-access-work-tracking.md)
* Product: **devops**
* Technology: **devops-security**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by msebolt** [comment]
@Zaniar0 Thank you for the question.

Unfortunately you need to set the Iteration group manually and can then manage it using the CLI via [group](https://docs.microsoft.com/cli/azure/ext/azure-devops/devops/security/group?view=azure-cli-latest).

Though please consider submitting this as a feature request with the product team in the [Azure DevOps community](https://developercommunity.visualstudio.com/spaces/21/index.html).  A similar thread for [branch security API](https://developercommunity.visualstudio.com/idea/365711/set-branch-security-by-rest-api.html) is currently in discussion.

**Comment by Zaniar0** [comment]
Hi @msebolt is it possible to do using the API?

**Comment by msebolt** [comment]
@Zaniar0 Not currently, though you should probably check with the product team for the current status.

**Comment by jessehouwing** [comment]
If there is an existing team, you can add the group to the team. A team is just a security group, so you can query it like any other. Then add the group to it. `az devops security group membership add`
https://docs.microsoft.com/en-us/cli/azure/ext/azure-devops/devops/security/group/membership?view=azure-cli-latest#ext-azure-devops-az-devops-security-group-membership-add

If there isn't an existing team, you can create a new one using `az devops team create`. Then add the existing group to the team.
https://docs.microsoft.com/en-us/cli/azure/ext/azure-devops/devops/team?view=azure-cli-latest#ext-azure-devops-az-devops-team-create

You can add a team to an iteration using `az boards iteration team add`
https://docs.microsoft.com/en-us/cli/azure/ext/azure-devops/boards/iteration/team?view=azure-cli-latest#ext-azure-devops-az-boards-iteration-team-add

You can also use the old [TfsTeamTools](https://github.com/jessehouwing/TfsTeamTools) to accomplish some of these steps. One thing this tool can do is turning a group into a team by setting the required metadata on the identity. That would allow you to skip the team creation and adding a group to it. These tools were written at the time that the concept of Teams was first introduced and many existing TFS2010 setups had to be reconfigured to support that concept.

**Comment by jessehouwing** [comment]
Here is the underlying REST API: https://docs.microsoft.com/en-us/rest/api/azure/devops/work/iterations/post%20team%20iteration?view=azure-devops-rest-5.1

**Comment by Zaniar0** [comment]
Im probably explaining it wrong. I mean adding a "Azure DevOps Group" to the security part of an iteration. In the img below I've added "team2019" by clicking on the "+ Add" button on the webui. My question is, is it possible to do this using the cli or api.
`az boards iteration team add` does not do this. 

![adding team using cli]([Imgur](https://i.imgur.com/76IxlYZ.png))

**Comment by jessehouwing** [comment]
That part is exactly as I explained on Twitter. Just grant the group any of the listed permissions and they will be added to the list.

So:

![image](https://user-images.githubusercontent.com/4173387/67381227-e0114c00-f58b-11e9-88ad-a7b40710ab00.png)

With the correct token and permission bit will add the user to that list if you grant them any permission bit. The dialog just shows all users & groups who have permissions assigned. The trick to finding the right bits and tokens is as I explained on Twitter already, then tie all that together in a couple of statements in PowerShell (or your favorite script language).

```
az login
az extension add --name "azure-devops"

# Find the group identifier of the group you want to set permissions for

$org = "gdbc2019-westeurope"

# There is a weird edge case here when an Azure DevOps Organization has a Team Project with the same name as the org.
# In that case you must also add a query to filter on the right domain property `?@.domain == '?'`	

# Update with the group you want to add and set the correct group type
$subject = az devops security group list `
    --org "https://dev.azure.com/$org/" `
    --scope organization `
    --subject-types vssgp `
    --query "graphGroups[?@.principalName == '[$org]\Project Collection Administrators'].descriptor | [0]"

#Update with the correct namespace ("Iteration")
$namespaceId = az devops security permission namespace list `
    --org "https://dev.azure.com/$org/" `
    --query "[?@.name == 'Git Repositories'].namespaceId | [0]"

#Update with the correct permissions you want to grant.
$bit = az devops security permission namespace show `
    --namespace-id $namespaceId `
    --org "https://dev.azure.com/$org/" `
    --query "[0].actions[?@.name == 'PullRequestBypassPolicy'].bit | [0]"

#update with the correct token based on `az boards iteration project list`
$token = "..."

az devops security permission update `
    --id $namespaceId `
    --subject $subject `
    --token $token `
    --allow-bit $bit `
    --merge true `
    --org https://dev.azure.com/$org/
```

Or use the equivalent `tfssecurity` command, which is simpler as it does most of the lookups for you based on group names etc:

```
$NodeGuid = "..."
$Group = "..."
tfssecurity /a+ "Iteration" "vstfs:///Classification/Node/$NodeGuid" "GenericRead" $Group ALLOW /collection:https://dev.azure.com/$org
```

**Comment by Zaniar0** [comment]
your a legend. Thanks!!!!!
