### ISSUE TITLE
"Dimension" causes error

### ISSUE THREAD

**Issue by seanwhitepc** [MicrosoftDocs/vsts-docs#6057]
In the example to make a custom field, entering
   reportable="Dimension"
causes an error in regards to "Dimension." It should be "dimension" (lowercase d) which is also in line with the system fields, at least as far as the Agile template for TFS 2018 goes.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e2d013ba-2777-8e26-9fb2-c495eaad3f91
* Version Independent ID: ada5d0d6-bbb9-785a-a76b-bf29dceddef9
* Content: [Add or modify a work tracking field - Azure DevOps & TFS](https://docs.microsoft.com/en-us/azure/devops/reference/add-modify-field?view=tfs-2018)
* Content Source: [docs/reference/add-modify-field.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/reference/add-modify-field.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by msebolt** [comment]
@seanwhitepc Thank you for the feedback, assigning this to the author for review.

**Comment by KathrynEE** [comment]
@seanwhitepc - Thank you for the correction. I will update the content later today.
