### ISSUE TITLE
Supported on Ubuntu 18.04?

### ISSUE THREAD

**Issue by slushysnowman** [MicrosoftDocs/vsts-docs#6058]
This page specifies that this only works when Ubuntu 16.04 pool is used for Linux containers, however from my testing it also seems to work when using Ubuntu 18.04 pool - if this is correct, page should be updated to reflect this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3339a2e0-be29-1363-f588-b231d4472c02
* Version Independent ID: 72dd11a3-704d-d0fd-6dfa-cf49f3352de3
* Content: [Container Jobs in Azure Pipelines and TFS - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/container-phases?view=azure-devops&tabs=yaml#feedback)
* Content Source: [docs/pipelines/process/container-phases.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/container-phases.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @thomps23
* Microsoft Alias: **macoope**

**Comment by msebolt** [comment]
@slushysnowman Thank you for the question and image validation.

The documentation won't be updated until after official support for Ubuntu 18.04 is announced.

Please refer to https://github.com/Microsoft/azure-pipelines-image-generation/issues/506 for its status.

**Comment by mathieu-benoit** [comment]
Hi @msebold, this doc should be updated now https://docs.microsoft.com/en-us/azure/devops/release-notes/2019/sprint-160-update#ubuntu-1804-pool ;) Thanks!
