### ISSUE TITLE
I cannot get links to work at alll

### ISSUE THREAD

**Issue by henry-padilla** [MicrosoftDocs/vsts-docs#6059]
I am using the AzDO wiki from the left-side Wiki link.
I pulled down the "Select... dropdown and clicked "New wiki".
I selected my repository from the list, left the '_wiki', and added a unique path to link (dvopwiki),
I created the first page and added a bunch of Lorum Ipsum for content, put a header at the bottom (### HTP Clone ###) and a link at the top:
[Link 1](#http-clone)

It does not navigate to the bottom of the page.
I have tried every permutation of links and pages I can think of and none of them result in a valid navigation.

Where can I find valid reference material for the side-wiki markdown?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fa622358-f5bb-1f5c-177a-081a37b6acef
* Version Independent ID: 72f7fd16-a822-66c8-3a34-8905645ce5f2
* Content: [Markdown syntax for files, widgets, and wikis in Azure DevOps - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/project/wiki/markdown-guidance?view=azure-devops-2019)
* Content Source: [docs/project/wiki/markdown-guidance.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/project/wiki/markdown-guidance.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @henry-padilla,
We're sorry for the confusion. I'll follow up shorty. Thanks so much for reaching out!

**Comment by johnmbaughman** [comment]
This issue ticket I submitted describes this:

https://developercommunity.visualstudio.com/content/problem/789067/markdown-syntax-for-anchor-links-requires-user-con.html

**Comment by henry-padilla** [comment]
Please disregard this issue.
We had a Wiki add-on that was accessible from the main (left) navigation pane and that is where I was making changes. It has been obsolete for some time and our admin has simply not removed it.

Once I began using "Publish code as wiki" from the wiki option under the Overview menu all things work as expected.

**Comment by chcomley** [comment]
Here's what I saw:
Header at the bottom is (### HTP Clone ###)
And the link at the top is [Link 1](#http-clone)

Looks like the Header has only one ‘T’ in “HTP Clone”
Where as the link at the top has two ‘T’s “#http-clone”

Glad you got it working. :)
