### ISSUE TITLE
Service Unavailable error on launching a dockerised .NETCORE app

### ISSUE THREAD

**Issue by garimasingh15** [MicrosoftDocs/vsts-docs#606]
Hello,

I followed the [https://docs.microsoft.com/en-us/vsts/build-release/apps/aspnet/build-aspnet-core?view=vsts&tabs=gitvsts%2Cweb%2Cdeploy-container](article) to set up CI/CD for a .NETCORE application. The build and release succeed and the repository is created on the Azure Container Registry. The release steps though successful, do not successfully launch the webapp URL. I am getting a **"Service Unavailable"** error there.
I am new to docker and azure container registry. Any help would be appreciated.

Thanks

**Comment by andyjlewis** [comment]
Sorry for the delayed response. We've made some major updates in this area. Would you please give https://docs.microsoft.com/en-us/azure/devops/pipelines/languages/dotnet-core a try?
