### ISSUE TITLE
What effects will have change from one Azure Subscription to another

### ISSUE THREAD

**Issue by dreagor** [MicrosoftDocs/vsts-docs#6061]
I need to link a different Azure Subscription to my Azure DevOps Org.
What will happen with my Basic / Basic + Test licenses, extension licenses, service connections and build / release pipelines?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4f717dae-91b5-276f-2f87-4b98331fb303
* Version Independent ID: e6e9d3b1-c00d-24d2-5667-58b4822df718
* Content: [Change the Azure subscription used for organization billing - Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/organizations/billing/change-azure-subscription?view=azure-devops#feedback)
* Content Source: [docs/organizations/billing/change-azure-subscription.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/billing/change-azure-subscription.md)
* Product: **devops**
* Technology: **devops-billing**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by drewbren** [comment]
- Change subscription will transfer any charges from Subscription A to Subscription B 
- Extensions are all now paid to the publisher directly, so there is no change for extension licenses
- Service connections and build/release pipelines will be unchanged (only billing for pipelines will be transferred)
- 

Let us know if the answers your question

Thanks,
-Andrew

**Comment by chcomley** [comment]
Hi @dreagor, I'm closing this issue, however please @mention me if you do end up having any further questions. Thanks for reaching out!
