### ISSUE TITLE
TFS 2018 Package Feed SemVer 2.0 Metadata Not Supported

### ISSUE THREAD

**Issue by StephenRSkinner** [MicrosoftDocs/vsts-docs#6062]
When pointing to the TFS 2018 package feed configured as a passthrough for NuGet, the nuget.frameworks.5.0.0.nupkg package produces the following error.

The package is invalid: The package version had build metadata.  We do not support versions with build metadata.

This is not the only package to produce this error. It appears any package that has SemVer 2.0 metadata fails to download or cache in the package feed.

The package feed extension for TFS 2018 On-Prem needs to be updated to not fail in this scenario.

**Comment by WilliamAntonRohm** [comment]
@StephenRSkinner -- Thanks for your feedback; we appreciate it. To make sure we have all the information needed to triage your issue, please let us know which topic you’re referencing, or provide more context around the general task.

**Comment by StephenRSkinner** [comment]
What additional information do you need? TFS 2018 Package Feed. Right there in the first sentence. Please re-open and fix.
