### ISSUE TITLE
Multiple Configurations not supported

### ISSUE THREAD

**Issue by bitcrazed** [MicrosoftDocs/vsts-docs#6063]
The docs say that the VSBuild task can build multiple configurations, but I can't find the 'Multi-configuration' or 'Multipliers' fields in the job settings.

Also, the instruction to 'Select Tasks and click on the agent job' appears to be incorrect.

ALSO, Variables tab doesn't appear to populate itself with Variables from the pipeline definition. Is this intended?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 02b0c082-81b3-79af-8841-8b3033dedf4a
* Version Independent ID: de8aab33-f9ef-0d8d-dbbc-49e23930f1c6
* Content: [Build C++ Windows apps - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/apps/windows/cpp?view=azure-devops#feedback)
* Content Source: [docs/pipelines/apps/windows/cpp.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/apps/windows/cpp.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @chasewilson
* Microsoft Alias: **phwilson**

**Comment by iamsrivatsa** [comment]
@bitcrazed You can find the **Multi-Configurations** under the **Execution plan** as shown below. Let me know if you are able to see this?

You have to add the variables explicitly if you want Multi-Configuration support. The variables will not auto populate for multi-configurations.

**Comment by iamsrivatsa** [comment]
The document has been updated and I'll be closing the issue. Thank you for the feedback and feel free to open a new issue if you have any more feedback.
