### ISSUE TITLE
Confusing use of term "root folder"

### ISSUE THREAD

**Issue by electromaggot** [MicrosoftDocs/vsts-docs#607]
"Source Folder" Argument says that if left empty, it copies from the "root folder of the repo."  The "Contents" Argument's Description refers to "root folder" when it really means the specified source folder; it least that's how it seems to operate.  This is really confusing when everyone associates a root folder with "/" or "\\" and not some other defined folder.  The use of "**" versus "*" for files is confusing too, as is the line "The pattern is used to match only file paths, not folder paths."  It was easier for me to just write a "cp -R" Command Line Task than to figure out how to get this utility to work.  In fact, many of the Build Variables are unintuitive too.  I had to write another Command Line Task just to print those out, because they didn't have any of the values that I was expecting, nor did the Xcode Build Directory variable match where the build was really going.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 81f02378-b85b-d3a4-d3c8-f07d935367da
* Version Independent ID: fab57f76-35d2-4024-6f7f-1740d7b24743
* Content: [Copy Files](https://docs.microsoft.com/en-us/vsts/build-release/tasks/utility/copy-files?view=vsts)
* Content Source: [docs/build-release/tasks/utility/copy-files.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/build-release/tasks/utility/copy-files.md)
* Service: **unspecified**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by andyjlewis** [comment]
Thank you for this feedback. I've copied this issue to our backlog.
