### ISSUE TITLE
Server side job examples

### ISSUE THREAD

**Issue by kine** [MicrosoftDocs/vsts-docs#6078]
Hi, in section Server there is text:
---
server specifies a server job. Only server tasks such as manual intervention or invoking an Azure Function can be run in a server job.
---
Have tried to use the manual intervention in the YAML build and it failed. Is this task supported at all right now? (ended with error: 
Stage2:RunOnServer: "Task execution section of task definition for ID: bcb64569-d51a-4af0-9c01-ea5d05b3b622 is either missing or not valid.") Same question for Azure Functions (have not tested). If these tasks are not supported by YAML build, it is misleading to mention them here...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7458d5b2-1bb7-7d87-7ce6-2b0c430b0155
* Version Independent ID: edf5bbd3-a3f0-5426-e985-31290f8afd05
* Content: [YAML schema - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema#server)
* Content Source: [docs/pipelines/yaml-schema.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/yaml-schema.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @vtbassmatt
* Microsoft Alias: **macoope**

**Comment by vtbassmatt** [comment]
Manual intervention is not a supported server-side task in YAML, and the doc has been updated to reflect that.
