### ISSUE TITLE
Update repository resource options

### ISSUE THREAD

**Issue by stevenmg** [MicrosoftDocs/vsts-docs#6081]
According to the docs: "Pipelines support two types of repositories, git and github." Bitbucket should be added to the list of options.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7458d5b2-1bb7-7d87-7ce6-2b0c430b0155
* Version Independent ID: edf5bbd3-a3f0-5426-e985-31290f8afd05
* Content: [YAML schema - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema#resources)
* Content Source: [docs/pipelines/yaml-schema.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/yaml-schema.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @vtbassmatt
* Microsoft Alias: **macoope**

**Comment by patrikulus** [comment]
'githubenterprise' is also a valid option, but not referenced in documentation

**Comment by vtbassmatt** [comment]
GitHub Enterprise is not supported. It may work under some circumstances due to how our source providers are implemented.

(BitBucket was added to the docs already, so closing this.)
