### ISSUE TITLE
Release doesnt not show in deployment section when we take existing build and link it to development

### ISSUE THREAD

**Issue by santhoshrajr** [MicrosoftDocs/vsts-docs#6082]
Document URL: https://docs.microsoft.com/en-us/azure/devops/boards/work-items/work-item-deployments-control?view=azure-devops

I have integration turned on in my releases. However i linked a PR and build to a different work item than the one which i intended to. So my deployment section has releases for the wrong work item. i went ahead and added the links for PR and build to my WI which i want the development to show. But it still doesn't reflect the change? 
![image](https://user-images.githubusercontent.com/14833988/67234308-e6c88380-f412-11e9-880f-be0f4ba21e85.png)

**Comment by msebolt** [comment]
@santhoshrajr  Thank you for the feedback.

Unfortunately, issues here are for documentation concerns and this is more of a product issue.

Please get in touch with the product team using **Report a problem** in the [Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html) and link back to this issue.
