### ISSUE TITLE
Iteration and AssignedTo entities not returned

### ISSUE THREAD

**Issue by vgeldbr** [MicrosoftDocs/vsts-docs#6086]
Following the sample on this page does not return same results. For example the Iteration and AssignedTo entities are not returned so cannot be expanded. Other steps also do not match actual experience.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cae009f6-b650-9162-0a5c-f59570288022
* Version Independent ID: 8778491f-74cf-a42a-1fcd-658c16e80965
* Content: [Sprint Burndown sample Power BI report - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/report/powerbi/sample-boards-sprintburndown?view=azure-devops&tabs=powerbi#feedback)
* Content Source: [docs/report/powerbi/sample-boards-sprintburndown.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/report/powerbi/sample-boards-sprintburndown.md)
* Product: **devops**
* Technology: **devops-analytics**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@vgeldbr  - Thank you for the feedback. I'm sending this information on to the PM for this feature and will get back to you with their response.

**Comment by greggboer** [comment]
I'd be interested in seeing the query you used, and any screenshots you might have. 
If you want, you can send this information to "azdevrf@microsoft.com", and we can take a look at it.

**Comment by KathrynEE** [comment]
@vgeldbr - Closing this issue. If you still have questions, please contact azdevrf@microsoft.com.
