### ISSUE TITLE
Unable to copy data from single cell in grid mode

### ISSUE THREAD

**Issue by RvsValori** [MicrosoftDocs/vsts-docs#6087]
I would like to be able to copy values from one cell to another. Now when I copy either a cell or the text inside the cell and then paste on a new line/record, the entire line/record of the copied cell/text is inserted.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3c520dee-1218-777e-7405-551623817c03
* Version Independent ID: 82b5d172-ae1a-2b4c-82ac-595cd7609d3c
* Content: [New test plans page - Azure Test Plans](https://docs.microsoft.com/en-us/azure/devops/test/new-test-plans-page?view=azure-devops)
* Content Source: [docs/test/new-test-plans-page.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/test/new-test-plans-page.md)
* Product: **devops**
* Technology: **devops-test**
* GitHub Login: @harishkragarwal
* Microsoft Alias: **harishkragarwal**

**Comment by msebolt** [comment]
@RvsValori Thank you for the feedback.

Please vote and/or comment on this in the **Developer Community** using this [active issue](https://developercommunity.visualstudio.com/content/problem/760975/test-case-editing-grid-copy-paste-issues.html).

There you will also get updates on any resolution made by the product team.
