### ISSUE TITLE
Which files for CTest?

### ISSUE THREAD

**Issue by KUGA2** [MicrosoftDocs/vsts-docs#6090]
What files should i put into Test results files for CTest? The Testing\Temporary\LastTest.log file?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 16bd8dd1-7650-8c18-2553-38a8bc54e892
* Version Independent ID: f9fa517a-7adc-e327-d12e-256295a1ed52
* Content: [Visual Studio Test task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/test/vstest?view=azure-devops#feedback)
* Content Source: [docs/pipelines/tasks/test/vstest.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/test/vstest.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @PBoraMSFT
* Microsoft Alias: **pbora**

**Comment by msebolt** [comment]
@KUGA2 Thank you for the question, assigning this to the author for review.

In the meantime, please use the following resources:

- [Azure DevOps Support](https://azure.microsoft.com/en-us/support/devops/)
- [Azure DevOps Community](https://developercommunity.visualstudio.com/spaces/21/index.html)
- [Azure DevOps on StackOverflow](https://stackoverflow.com/questions/tagged/azure-devops)

...for additional support options.

**Comment by karanjitsingh** [comment]
@KUGA2,  don't understand your question here. Are you asking what is the source file you need to pass while running ctest or do you want to generate the test result files while running ctest?

**Comment by karanjitsingh** [comment]
You need to execute ctest with parameter -T Test. This will generate a test results xml, something like Test.xml. You need to pass this xml to the `testResultsFiles` argument of the publish test results task.

PS: moving this to microsoft/azure-pipelines-tasks
