### ISSUE TITLE
Typo in second paragraph

### ISSUE THREAD

**Issue by abby-d-chr** [MicrosoftDocs/vsts-docs#6092]
In the second paragraph of the summary section at the top of the article, there is a missing period and following space after the "Plan and track work" link:

If you're just getting started, read the information provided in this article. To jump right in and start tracking work on a Kanban board, see Plan and track [[[TYPO]]] workFor [[[TYPO]]] a quick reference to various work item tasks and key concepts, see Work item quick reference.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a197bf55-89c7-682d-bb1c-e82bec732349
* Version Independent ID: 5aa2afac-cb82-3f72-643c-25a0173cce98
* Content: [Understand how work items are used to track user stories, issues, bugs, features, and epics - Azure Boards and TFS](https://docs.microsoft.com/en-us/azure/devops/boards/work-items/about-work-items?view=azure-devops&viewFallbackFrom=vsts&tabs=agile-process#feedback)
* Content Source: [docs/boards/work-items/about-work-items.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/boards/work-items/about-work-items.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by msebolt** [comment]
@abby-d-chr Thank you for the feedback.

The documentation has been updated and will be published shortly.
