### ISSUE TITLE
Update download step documentation to include use with pipeline resources

### ISSUE THREAD

**Issue by stevenmg** [MicrosoftDocs/vsts-docs#6094]
The information under the "download" section is limited to downloading artifacts for the current pipeline. This should include the ability to download artifacts for other pipelines linked as a resource.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7458d5b2-1bb7-7d87-7ce6-2b0c430b0155
* Version Independent ID: edf5bbd3-a3f0-5426-e985-31290f8afd05
* Content: [YAML schema - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema#download)
* Content Source: [docs/pipelines/yaml-schema.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/yaml-schema.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @vtbassmatt
* Microsoft Alias: **macoope**

**Comment by msebolt** [comment]
@stevenmg  Thank you for the feedback, assigning this to the author for review.

**Comment by ashokirla** [comment]
The documentation is now updated. https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema#download
