### ISSUE TITLE
Need entire example

### ISSUE THREAD

**Issue by pkzOR** [MicrosoftDocs/vsts-docs#6096]
It would be helpful if the entire yml file was available as an example. The sections above are often being added as needed and seeing where they reside in an entire file would be helpful.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec716c61-248c-75c9-2bc7-262749cc7421
* Version Independent ID: 45f47edc-e800-2c42-416a-92cd93c9e892
* Content: [Build, test, and deploy .NET Core apps - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/ecosystems/dotnet-core?view=azure-devops)
* Content Source: [docs/pipelines/ecosystems/dotnet-core.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/ecosystems/dotnet-core.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by msebolt** [comment]
@pkzOR  Thank you for the feedback, assigning this to the author for review.

**Comment by juliakm** [comment]
@pkzOR If you go through the steps at the beginning of the article, it will generate a complete ASP.NET Core YAML. You can also see all of the templates [here](https://github.com/microsoft/azure-pipelines-yaml/tree/master/templates).
