### ISSUE TITLE
clarify scope of " These variables are available to downstream steps."

### ISSUE THREAD

**Issue by drdamour** [MicrosoftDocs/vsts-docs#6098]
i believe the variables are only available to downstream steps within the job, the won't persist to downstream jobs in the stage, or downstream stages in the pipeline, correct?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77c58a78-a567-e99a-9eb7-62dddd1b90b6
* Version Independent ID: 680a79bc-11de-39fc-43e3-e07dc762db18
* Content: [Expressions - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/expressions?view=azure-devops#variables)
* Content Source: [docs/pipelines/process/expressions.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/expressions.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by msebolt** [comment]
@drdamour  Thank you for the feedback.

You are correct, please use [Variable groups](https://docs.microsoft.com/azure/devops/pipelines/library/variable-groups?view=azure-devops&tabs=yaml) for access across pipelines.

The documentation has been updated.
