### ISSUE TITLE
update variable expansion precedence info for stage variables

### ISSUE THREAD

**Issue by drdamour** [MicrosoftDocs/vsts-docs#6099]
the section that says

```
When you set a variable with the same name in multiple scopes, the following precedence is used (highest precedence first).

Job level variable set in the YAML file
Pipeline level variable set in the YAML file
Variable set at queue time
Pipeline variable set in the web editor
```

doesn't mention stage variables, but they certainly must come into play here somewhere, right?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd7e0bd3-1f7d-d7b6-cc72-5ef63c31b46a
* Version Independent ID: dae87abd-b73d-9120-bcdb-6097d4b40f2a
* Content: [Variables - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch)
* Content Source: [docs/pipelines/process/variables.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/variables.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by msebolt** [comment]
@drdamour  Thank you for the feedback, assigning this to the author for review.

**Comment by juliakm** [comment]
@drdamour Variables at the job level override variables at the root and stage level. Variables at the stage level override variables at the root level. I'll update that part of the documentation.
