### ISSUE TITLE
When will "Building pull requests from repository forks" be restored?

### ISSUE THREAD

**Issue by manemarron** [MicrosoftDocs/vsts-docs#610]
Are there any updates on this issue?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 75a10513-2af9-8e16-61a4-25d4b09f6d32
* Version Independent ID: 788acaa2-d5a1-1d0d-18f4-e94a4e2fe2c9
* Content: [Define a CI build process for your GitHub repository](https://docs.microsoft.com/en-us/vsts/build-release/actions/ci-build-github?view=vsts)
* Content Source: [docs/build-release/actions/ci-build-github.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/build-release/actions/ci-build-github.md)
* Service: **vsts**
* GitHub Login: @erickson-doug
* Microsoft Alias: **mlearned**

**Comment by kenotron** [comment]
It is now mid-June and this is still the case. Is there a real ETA for this?

**Comment by joshuapoq** [comment]
+1 We're checking this page every week... we would love a little more transparency here, and would have been great to sign up to some sort of newsletter to be told that you were planning on removing the feature in the first place.

**Comment by mlearned** [comment]
@vijayma @andyjlewis  do we have updates for this one?

**Comment by mlearned** [comment]
@joshuapoq  @kenotron  we've got an internal thread going on this and will get you an answer.

**Comment by nschonni** [comment]
Looks like the Agent is still being worked on https://github.com/Microsoft/vsts-agent/pull/1653

**Comment by DavidStaheli** [comment]
Sorry for the delay, @kenotron, @joshuapoq, and @nschonni.  Fixing a security hole took longer than we expected.  A few days ago I noticed the docs were out-of-date and updated the ETA to July.  We expect the fix to start deploying next week.  It'll make it to all VSTS accounts within about 2 weeks and we'll turn the forks feature back on as quickly as that happens.  + @thechrisjohnson in case he wants to correct/add more.

**Comment by kenotron** [comment]
This is great news - it would be really great to get some idea of what the security issue was (secret leaking from PRs, etc?). And what kind of restrictions are going to be placed to help secure PR based triggers.

**Comment by kjacobsen** [comment]
+1 to wanting this feature back.

If the fix is going to take any longer, perhaps it is advisable to update some of the documentation to further highlight this feature is currently disabled? I just spent a few hours looking for it!

**Comment by nicolasg-playster** [comment]
@DavidStaheli Any update?

**Comment by DavidStaheli** [comment]
It's on schedule to be complete by July 20 and reach all of production ~August 3 with some stages getting it sooner.

**Comment by ravinderjangra** [comment]
It is still not working.

**Comment by DavidStaheli** [comment]
So sorry @ravinderjangra .  It's very close.  Please email me with your VSTS org/account name if I can enable it for you early.

**Comment by kjacobsen** [comment]
Hi,

Is there an ETA on when this will reach production?

**Comment by ravinderjangra** [comment]
@DavidStaheli please share your email. so I can send a request. Thanks

**Comment by DavidStaheli** [comment]
Finally, some information to share...  I'm so sorry for the wait.  The fix that was necessary before re-enabling fork PR builds was completed yesterday (Tues, Aug. 7).  Changes such as this deploy to production first to inner rings, proceeding to outer rings to ensure reliability along the way.  The changes will reach your VSTS organization over the next few days, depending on which ring it is in.  We are going to celebrate once this is fully deployed!  @ravinderjangra you can email me at dastahel@microsoft.com.

**Comment by DavidStaheli** [comment]
Believe it or not, we will start enabling it in each of our production rings starting today.  It should reach everyone by the middle of next week (August 23).

**Comment by DavidStaheli** [comment]
The joyous day has arrived.  Fork PR builds are available again on all VSTS organizations.

**Comment by nicolasg-playster** [comment]
@DavidStaheli Still not working for me...
