### ISSUE TITLE
"Azure Boards with Teams" link redirects to wrong URL

### ISSUE THREAD

**Issue by p2well** [MicrosoftDocs/vsts-docs#6102]
"Azure Boards with Teams" link (https://aka.ms/AzureBoardsTeamsIntegration) inside "Related articles" section redirects to Microsoft website and not to the corresponding documentation page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43aa8c60-c25d-535b-2166-f51fa9f171c6
* Version Independent ID: 8890a537-9eda-5606-4be4-580bdc9e8269
* Content: [Azure Repos with Microsoft Teams - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/integrations/repos-teams?view=azure-devops#feedback)
* Content Source: [docs/repos/integrations/repos-teams.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/repos/integrations/repos-teams.md)
* Product: **devops**
* Technology: **devops-code-git**
* GitHub Login: @RGKarthik
* Microsoft Alias: **karrg**

**Comment by WilliamAntonRohm** [comment]
Thank you for your feedback.  We have updated the documentation and it should be live by tomorrow.
