### ISSUE TITLE
Additional steps may be needed with Visual Studio installed

### ISSUE THREAD

**Issue by kvinther** [MicrosoftDocs/vsts-docs#6105]
I suggest adding a section, that explains that event though you may have Visual Studio installed, the "Office integration" component still needs to be explicitly installed - mine wasn't. I went into the installer and added the component - after that I got the Team tab in Excel.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 505849d3-01c8-a2cd-dc6c-271dd1120e2d
* Version Independent ID: 577fc252-60e4-f670-bb92-6bdbcb7d5c69
* Content: [Bulk modify work items using Microsoft Excel - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/backlogs/office/bulk-add-modify-work-items-excel?view=azure-devops#feedback)
* Content Source: [docs/boards/backlogs/office/bulk-add-modify-work-items-excel.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/boards/backlogs/office/bulk-add-modify-work-items-excel.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@kvinther - Thank you for the feedback. I have updated the referenced article and others to clarify the installation.
