### ISSUE TITLE
Please show me how...

### ISSUE THREAD

**Issue by joeshepherdmba** [MicrosoftDocs/vsts-docs#611]
There is a section here entitled: Update Kanban column-to-State mappings. The document doesn't actually show how to make these changes. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: afe3bf75-ae6d-c347-67f6-decbe4ee4588
* Version Independent ID: e3359ab1-1d45-f91e-e9f1-7f770477fb41
* Content: [Add columns to your Kanban board - VSTS & TFS](https://docs.microsoft.com/en-us/vsts/work/kanban/add-columns?view=vsts#feedback)
* Content Source: [docs/work/kanban/add-columns.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/work/kanban/add-columns.md)
* Service: **unspecified**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@joeshepherdmba - Thank you for your inquiry. You Update the Kanban column-to-State mappings on the Columns page of the Kanban board setting. Could you let me know what platform/TFS version you are using and perhaps I can provide more guidance?
