### ISSUE TITLE
Dark theme squashes formatting example (not headers)

### ISSUE THREAD

**Issue by v-wilock** [MicrosoftDocs/vsts-docs#6114]
The text
"The project status is GREEN even though the bug count / developer may be in red. - Capability of span"
shows up all in white for me. I'm using the dark theme.
Note that this is distinct from [the headers issue](https://developercommunity.visualstudio.com/idea/542332/wiki-header-colors-for-dark-theme.html), though both are formatting related.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 29f1e43f-a069-dd88-7fc7-9cc497fb94f0
* Version Independent ID: c261afa7-6eb7-b3f0-9f92-6d2f3c5ac336
* Content: [Markdown syntax for wikis in Azure DevOps - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/project/wiki/wiki-markdown-guidance?view=azure-devops)
* Content Source: [docs/project/wiki/wiki-markdown-guidance.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/project/wiki/wiki-markdown-guidance.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by WilliamAntonRohm** [comment]
@v-wilock -- William, thanks for your feedback; we appreciate it. You can submit issues related to the overall site experience, or suggestions for improved site functionality or design, at [https://aka.ms/sitefeedback/](https://aka.ms/sitefeedback).

**Comment by v-wilock** [comment]
@WilliamAntonRohm - I was specifically asked to create this second ticket after the last one was closed because it was conflated with being related to headers.

**Comment by chcomley** [comment]
Hi @v-wilock, 

I've reopened this issue and engaged our PM. We'll be in touch ASAP. 
Thanks for reaching out.

**Comment by chcomley** [comment]
Hi @v-wilock, I've published an update to the article, replacing the text with screenshots of light and dark themes. Is this what you meant? I also updated the versioning of the article, as HTML tags didn't get added until the [release of Azure DevOps Server 2019.1](https://docs.microsoft.com/en-us/azure/devops/release-notes/features-timeline). I'm sorry for any confusion. The updates should be live sometime today. Please let me know if you have any further questions. Thanks so much for creating this issue.

**Comment by v-wilock** [comment]
![image](https://user-images.githubusercontent.com/46005579/67599876-d3c0f680-f725-11e9-8a47-d8b1673a5551.png)
Attached a screenshot.

**Comment by chcomley** [comment]
@v-wilock What version of the product are you using please? Thanks!
