### ISSUE TITLE
artifactFeeds not artifactFeed

### ISSUE THREAD

**Issue by keokichang** [MicrosoftDocs/vsts-docs#6118]
Artifact feed name property is 'artifactFeeds' rather than 'artifactFeed'.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 726683ec-c811-46b7-17d6-527fbafaf8d0
* Version Independent ID: 6d964146-88fb-1975-1263-4d4f6584a03a
* Content: [Python Twine Upload Authenticate - Azure Pipelines](https://docs.microsoft.com/en-au/azure/devops/pipelines/tasks/package/twine-authenticate?view=azure-devops#feedback)
* Content Source: [docs/pipelines/tasks/package/twine-authenticate.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/package/twine-authenticate.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @chasewilson
* Microsoft Alias: **phwilson**

**Comment by msebolt** [comment]
@keokichang  Thank you for the feedback.

The `artifactFeeds` from [V0](https://docs.microsoft.com/azure/devops/pipelines/tasks/package/prev-versions/twine-authenticate-0?view=azure-devops) has been changed to `artifactFeed` in [V1](https://docs.microsoft.com/azure/devops/pipelines/tasks/package/twine-authenticate?view=azure-devops#feedback).

Please refer to [task.json](https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/TwineAuthenticateV1/task.json) and comment below if you have any questions.
