### ISSUE TITLE
Cobertura required XML format 

### ISSUE THREAD

**Issue by cristianbanarescu** [MicrosoftDocs/vsts-docs#6119]
Hi! I am trying to use this plugin to publish my code coverage results. Apparently i am missing something about my 'Summary file', meaning i am creating a wrong XML for the plugin in order to publish it. Can someone provide an example of how this XML file should look like in order for this plugin to work correctly and publish my code coverage results ? I am getting this warning: ##[warning]No coverage data found. Check the build errors/warnings for more details.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6ac4ff4-9839-6a6d-8d20-a25084d221ef
* Version Independent ID: bd09f139-8e69-8ea1-6671-b7bba8e17c23
* Content: [Publish Code Coverage Results task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/test/publish-code-coverage-results?view=azure-devops)
* Content Source: [docs/pipelines/tasks/test/publish-code-coverage-results.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/test/publish-code-coverage-results.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @PBoraMSFT
* Microsoft Alias: **pbora**

**Comment by msebolt** [comment]
@cristianbanarescu Thank you for the feedback.

This appears to be a recurring problem in the community, please see issues [2186](https://github.com/Microsoft/azure-pipelines-tasks/issues/2186), [3036](https://github.com/microsoft/azure-pipelines-tasks/issues/3036), [4814](https://github.com/microsoft/azure-pipelines-tasks/issues/4814), and [10149](https://github.com/Microsoft/azure-pipelines-tasks/issues/10149).

Can any of these be applied to your scenario?

**Comment by cristianbanarescu** [comment]
Hi, @msebolt ! I looked into the issues you specified and i will try some suggestions from there. I will let you know what i have accomplished.

**Comment by cristianbanarescu** [comment]
For anyone interested: if there is anyone using this task to publish XCode code coverage results, i suggest using slather framework to generate the required XML for this task. I used it and now i am able to publish my code coverage results
