### ISSUE TITLE
Breaking change in azure-pipelines-task-lib

### ISSUE THREAD

**Issue by Balfa** [MicrosoftDocs/vsts-docs#6122]
Looks like there's a breaking change in the API of `azure-pipelines-task-lib/task`. When I run `tsc` against the `index.ts` as presented above, I get `index.ts:5:15 - error TS2322: Type 'string | undefined' is not assignable to type 'string'.`.
Replacing `const inputString: string = tl.getInput('samplestring', true);` with `const inputString: string | undefined = tl.getInput('samplestring', true);` fixes the problem.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 44581f4a-93df-7507-3844-eadedf9a6cc4
* Version Independent ID: 33c7bcf0-1512-975f-5ef8-9f2a192a84ad
* Content: [Add a Build or Release Task](https://docs.microsoft.com/en-us/azure/devops/extend/develop/add-build-task?view=azure-devops#feedback)
* Content Source: [docs/extend/develop/add-build-task.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/extend/develop/add-build-task.md)
* Product: **devops**
* Technology: **devops-ecosystem**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by msebolt** [comment]
@Balfa  Thank you for the feedback, assigning this to the author for review.

In the meantime you should start an issue with the [azure-pipelines-task-lib](https://github.com/microsoft/azure-pipelines-task-lib/issues) repo.

**Comment by damccorm** [comment]
So this isn't really a breaking change - prior to the changes that caused this, our lib didn't allow strict type checking. With this change, it does, and we should only see this error when using strict typing. With that said, the docs should be updated.

`const inputString: string | undefined = tl.getInput('samplestring', true)` is indeed correct

**Comment by Balfa** [comment]
Why closed? The documentation is still wrong.

**Comment by chcomley** [comment]
@Balfa, See above your comment, where I referenced a PR, which is where the documentation updates were included. They will go live sometime today. Thanks

**Comment by chcomley** [comment]
@Balfa, No worries. It's good to know that it may not be reflected on your side. I'll look into it. Thanks so much. Have a wonderful weekend!
