### ISSUE TITLE
Can you copy files to Deployment Groups?

### ISSUE THREAD

**Issue by RealNoArms** [MicrosoftDocs/vsts-docs#6124]
Is there any way to use deployment groups with a Windows Machine File Copy or other task to deploy files to a server farm?

**Comment by msebolt** [comment]
@RealNoArms Thank you for the question.

Unfortunately this would better be served by the product team through the [Azure DevOps community](https://developercommunity.visualstudio.com/spaces/21/index.html) where they will start a feature request.  They can also offer temporary work-arounds.

Please start a thread there and link back to this issue.
