### ISSUE TITLE
RenderType documentation incorrect

### ISSUE THREAD

**Issue by larryms** [MicrosoftDocs/vsts-docs#6125]
under Bake, RenderType this page says " Acceptable values: helm2. "
After reviewing the source code, I believe this is incomplete; the acceptable values are: (per the source code)
                "helm2": "Helm 2",
                "kompose": "Kompose",
                "kustomize": "Kustomize"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72bba72b-235b-ce64-b8fd-2c6ed52a9f1f
* Version Independent ID: 2ae1b3f1-e125-a9d2-a17c-d13047d69801
* Content: [Kubernetes Manifest task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/kubernetes-manifest?view=azure-devops#open-source)
* Content Source: [docs/pipelines/tasks/deploy/kubernetes-manifest.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/deploy/kubernetes-manifest.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @shashankbarsin
* Microsoft Alias: **shasb**

**Comment by msebolt** [comment]
@larryms  Thank you for the feedback, assigning this to the author for review.

**Comment by shashankbarsin** [comment]
This issue has been addressed in the recent set of updates for this document.
