### ISSUE TITLE
Migrate Build and release pipeline from TFS 2018 update 3 to Azure devops service

### ISSUE THREAD

**Issue by Anand-Moghe** [MicrosoftDocs/vsts-docs#6126]
Does the latest data migration tool also migrate TFS 2018 update 3 Build and Release pipeline to Azure DevOps Service ?  Do I need to make any manual changes/update to build or release pipeline after migration on Azure DevOps Service?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 91d0174c-2ab8-1e50-9566-e1366cb39ded
* Version Independent ID: 8ab7e84f-c738-56dc-64a1-55d2cb4c4ed6
* Content: [Migration options for migrating from Azure DevOps Server to Azure DevOps Services - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/migrate/migrate-from-tfs?view=azure-devops)
* Content Source: [docs/migrate/migrate-from-tfs.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/migrate/migrate-from-tfs.md)
* Product: **devops**
* Technology: **devops-migrate**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by msebolt** [comment]
@Anand-Moghe  Thank you for the questions.

TFS 2018 update 3 is supported (see [here](https://devblogs.microsoft.com/devops/team-foundation-server-2018-update-3-and-update-1-1-are-available/)).  

For any problems please see contact listed in the [Migration overview](https://docs.microsoft.com/azure/devops/migrate/migration-overview?view=azure-devops#q--a) or contact the product team via [Azure DevOps community](https://developercommunity.visualstudio.com/spaces/21/index.html).

Post-installation steps are discussed in [Post import](https://docs.microsoft.com/azure/devops/migrate/migration-post-import?view=azure-devops), please refer to this if you have additional questions.

**Comment by Anand-Moghe** [comment]
@msebolt I will try my luck on Azure DevOps Community.
