### ISSUE TITLE
Removal of deprecated functionality

### ISSUE THREAD

**Issue by ofunky** [MicrosoftDocs/vsts-docs#6127]
In what version of Azure DevOps will the deprecated Copy and Publish Build Artifacts be removed?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 34301e0e-fc7e-bf7a-de61-c466756f22a3
* Version Independent ID: 2595a9cf-03b2-4206-6dda-43ac1b903add
* Content: [Copy and Publish Build Artifacts task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/copy-and-publish-build-artifacts?view=azure-devops#feedback)
* Content Source: [docs/pipelines/tasks/utility/copy-and-publish-build-artifacts.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/utility/copy-and-publish-build-artifacts.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @willsmythe
* Microsoft Alias: **wismyth**

**Comment by msebolt** [comment]
@ofunky  Thank you for the question.

Unfortunately this is more of a question for the product team.

Please move the issue to the [Azure DevOps community](https://developercommunity.visualstudio.com/spaces/21/index.html) and link back to this issue.
