### ISSUE TITLE
TF401232: Work item 15 does not exist, or you do not have permissions to read it.

### ISSUE THREAD

**Issue by DaveVoyles** [MicrosoftDocs/vsts-docs#6128]
I have exported all work items from ADO backlog A as .csv.
I've created a new ADO repository (B).
In ADO repository B, click the "import work items" button to upload the .csv from A.

That's when I receive this error:
``` TF401232: Work item 15 does not exist, or you do not have permissions to read it.```

I have no idea of what this is telling me, because this item exists. 
If I delete it, I then receive this error for the next row.

Unsure of how to proceed.

**Comment by msebolt** [comment]
@DaveVoyles Thank you for the feedback, sorry you're experiencing difficulties.

There is an active item started [here](https://developercommunity.visualstudio.com/content/problem/782030/error-tf401232-when-importing-csv-of-work-items.html) with the product team in **Azure DevOps** community.

Please add your comment there and link back to this issue, or comment below if this does not address your problem.

**Comment by RRohitmehta** [comment]
I still face this issue, 
Does this issue has been fixed?

**Comment by PlugueC** [comment]
any ideia guys? pls! tks!

**Comment by WilliamAntonRohm** [comment]
@RRohitmehta, @PlugueC -- please see the item Matt mentioned above:
> There is an active item started [here](https://developercommunity.visualstudio.com/content/problem/782030/error-tf401232-when-importing-csv-of-work-items.html) with the product team in **Azure DevOps** community.
