### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by ronwarner** [MicrosoftDocs/vsts-docs#6129]
Under Dependencies/Classic, there are two typos:
"With a After release trigger" should be changed to "With an After release."
"With a After stage trigger" should be changed to "With an After stage."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4266f72c-c774-0046-4593-d01eb775d3c3
* Version Independent ID: f20827aa-a6c5-96a8-5969-e576ffbc2e38
* Content: [Stages in Azure Pipelines - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/stages?view=azure-devops&tabs=classic)
* Content Source: [docs/pipelines/process/stages.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/stages.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @vijayma
* Microsoft Alias: **vijayma**

**Comment by msebolt** [comment]
@ronwarner  Thank you for the feedback and attention to detail.

The documentation has been updated and is pending review.
