### ISSUE TITLE
Azure Focused

### ISSUE THREAD

**Issue by shaun-dm-stewart** [MicrosoftDocs/vsts-docs#613]
This piece of documentation along with most of the other documentation around VSTS is focused closely on Azure.  As far as I am aware Azure is only one of many suitable target platforms.  It took a question from a reader to clarify whether this documentation applied to on premise physical devices.  An equally detailed description on how to achieve deployment to other platforms should be present here.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca1c5394-611b-b119-dbf3-b88404e351d5
* Version Independent ID: fcc23259-21ec-f9fa-4e25-f587e1e0f41b
* Content: [Deploy to an IIS web server on a Windows Virtual Machine](https://docs.microsoft.com/en-us/vsts/build-release/apps/cd/deploy-webdeploy-iis-deploygroups?view=vsts)
* Content Source: [docs/build-release/apps/cd/deploy-webdeploy-iis-deploygroups.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/build-release/apps/cd/deploy-webdeploy-iis-deploygroups.md)
* Service: **unspecified**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment]
Thank you for your feedback. Typically you can use deployment groups to deploy to any set of servers, not just Azure-based machines. For example: https://docs.microsoft.com/vsts/build-release/apps/cd/deploy-webdeploy-iis-winrm. Deployment groups are discussed here: https://docs.microsoft.com/vsts/build-release/concepts/definitions/release/deployment-groups/. I hope this answers your question.
