### ISSUE TITLE
Test Outcome from automated tests does not display in Test Plan

### ISSUE THREAD

**Issue by askjeevers** [MicrosoftDocs/vsts-docs#6130]
Not sure when this stopped working...

We have a build/release pipeline that runs automated tests.  Our automated tests are associated to Test Cases in Azure DevOps, which are also contained within a Test Plan.

Previously, when our build/release would run, the results of the automated tests would update the Test Outcome in our Test Plans.  This is no longer working in the 'new' and 'old' version of the Test Plan section.   When viewing a Test Case in Azure, under the 'Execution' tab.. there is no run history for the tests either.  

Our dashboard is being updated with the results.

How can we solve this?

**Comment by msebolt** [comment]
@askjeevers  Thank you for the feedback, we're sorry you're experiencing issues.

Unfortunately, something like this needs to be addressed by the product team.

Please use **Report a problem** in the [Azure DevOps community](https://developercommunity.visualstudio.com/spaces/21/index.html) to start a thread and link back to this issue.

A similar post [here](https://developercommunity.visualstudio.com/content/problem/784616/issue-trying-to-add-new-existing-test-cases.html) suggests removing and re-adding a test case to see if it re-appears.
