### ISSUE TITLE
Where is "Clean repository?"

### ISSUE THREAD

**Issue by ronwarner** [MicrosoftDocs/vsts-docs#6132]
The part of this document that reads "This option has no practical effect unless you also set Clean repository to False" could be more useful if it included a link to what "Clean repository" is, and where that option can be found.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 22342679-18af-7c79-f902-fe9c0bb55379
* Version Independent ID: a8e7c201-6593-458b-5a81-b54e93fde4b5
* Content: [MSBuild build and release task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/msbuild?view=azure-devops)
* Content Source: [docs/pipelines/tasks/build/msbuild.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/build/msbuild.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @vijayma
* Microsoft Alias: **vijayma**

**Comment by msebolt** [comment]
@ronwarner  Thank you for the feedback.

The repo's clean setting is an option set using `git`, refer to [clean the local repo](https://docs.microsoft.com/azure/devops/pipelines/repos/pipeline-options-for-git?view=azure-devops#clean-the-local-repo-on-the-agent).

The documentation has been updated and is pending review.
