### ISSUE TITLE
Can you add more detail for migrating TFS Release to Azure DevOps Service?

### ISSUE THREAD

**Issue by Anand-Moghe** [MicrosoftDocs/vsts-docs#6134]
The article explicitly mentioned XAML Build pipeline Migration process and clearly mention that to migrate it to Azure DevOps Service, one has to use **Manual approach and no automation is available.**

But does that also means that the **new TFS pipeline** which is based on the simpler task- and script-driven cross-platform approach **can be migrated using automation using Data Migration tool for migrating to Azure DevOps Service?**

Also can you add some recommendation or approach to plan for **moving TFS release pipeline to Azure Pipeline**? Can TFS release be also migrated to Azure DevOps Service using latest Data Migration tool? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c8c7b10c-fb6e-c491-bc0c-71c6af9a4766
* Version Independent ID: 2ae046aa-31c2-6409-fc80-796d54692450
* Content: [Migrate from XAML builds - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/migrate-from-xaml-builds?view=azure-devops)
* Content Source: [docs/pipelines/build/migrate-from-xaml-builds.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/build/migrate-from-xaml-builds.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by msebolt** [comment]
@Anand-Moghe Thank you for the question.

Please review the [migration overview](https://docs.microsoft.com/azure/devops/migrate/migration-overview?view=azure-devops) and add any questions below.

The data migration tool does support TFS though the descriptions are somewhat blurred since lthis is now referred to as Azure DevOps Server.

**Comment by Anand-Moghe** [comment]
@msebolt Thanks!
