### ISSUE TITLE
Missing information for Service Hooks consumption and limits

### ISSUE THREAD

**Issue by operick8** [MicrosoftDocs/vsts-docs#6135]
With this documentation It is unclear to me how are the service hooks affecting the global consumption limit. I understand that all actions performed by a user have related TSTUs. My guess is that when a service hook is triggered it will also have some TSTUs related but I didn't find anything specific to the service hooks consumption and limits here or in the service hook documentation. Specifically I think it would make sense to specify the following in this document (or perhaps in the Service hook document):
-Do Service hooks have a resource consumption limit too? If so, is it per trigger or different?
-Do all the Service hooks on a single project share the same resource consumption or each of them is treated as an individual entity with its own resource consumption (like the pipelines) or perhaps they share the consumption with the user who created them (or even triggered them)?
- Is it possible to see the usage of the Service Hooks somewhere?
- If a Service hook is triggered many times, can it be blocked/delayed because of exceding a rate limit?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5c2c2355-60a5-d53f-2c72-8f032c1b8cf2
* Version Independent ID: 711bf22d-99c9-51b2-382c-e095bdb2c37f
* Content: [Resource limits & constraints - Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/integrate/concepts/rate-limits?view=azure-devops#feedback)
* Content Source: [docs/integrate/concepts/rate-limits.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/integrate/concepts/rate-limits.md)
* Product: **devops**
* Technology: **devops-ecosystem**
* GitHub Login: @roofers
* Microsoft Alias: **kaelli**

**Comment by msebolt** [comment]
@operick8 Thank you for the feedback.

Please see the service hooks category starting with the [overview](https://docs.microsoft.com/azure/devops/service-hooks/overview?view=azure-devops).  Many examples are included here, such as [webhooks](https://docs.microsoft.com/azure/devops/service-hooks/services/webhooks?view=azure-devops).  If you need further examples or have any suggestions please comment below.

I don't see anything about the rate limits, assigning this to the author for review.

**Comment by operick8** [comment]
Hi @msebolt thanks for the prompt response. I do understand how to use service hooks and for the moment I don't need examples about them. What I do want to know is about the service hooks resource consumption. I think it is something important that should be included somewhere in the documentation.  @roofers Could you help answering the questions? Thanks in advance!

- Do Service hooks have a resource consumption limit too? If so, is it per trigger or different?
- Do all the Service hooks on a single project share the same resource consumption or each of them is treated as an individual entity with its own resource consumption (like the pipelines) or perhaps they share the consumption with the user who created them (or even triggered them)?
- Is it possible to see the usage of the Service Hooks somewhere?
- If a Service hook is triggered many times, can it be blocked/delayed because of exceding a rate limit?

**Comment by KathrynEE** [comment]
@operick8 - Thank you for your inquiry and apologies for the delay in response. I checked with the product team and they indicated that Rate Limits don't apply to Service Hooks.

**Comment by operick8** [comment]
Thanks for the response, appreciate it! It would be nice to add that information in the rate limits documentation.(https://docs.microsoft.com/en-us/azure/devops/integrate/concepts/rate-limits?view=azure-devops)
