### ISSUE TITLE
How do I remove git from my project in Visual Studio?

### ISSUE THREAD

**Issue by LJ9999** [MicrosoftDocs/vsts-docs#6136]
Are you telling me this cannot be done? Seriously?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b03af1d9-4eeb-ac18-d517-a0a44a2478be
* Version Independent ID: 842691c8-8c41-facf-2cff-03542262f2e5
* Content: [Delete a Git repo from your project - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/delete-existing-repo?view=azure-devops)
* Content Source: [docs/repos/git/delete-existing-repo.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/repos/git/delete-existing-repo.md)
* Product: **devops**
* Technology: **devops-code-git**
* GitHub Login: @apawast
* Microsoft Alias: **sdanie**

**Comment by msebolt** [comment]
@LJ9999  Thank you for the feedback.

The article is intended to accomplish this.

Are the instructions not working or is something missing from the steps?

**Comment by zLeki** [comment]
this was hella helpful

**Comment by firezdog** [comment]
UX issues like this is why Visual Studio has a bad reputation.
