### ISSUE TITLE
Using files from other repositories

### ISSUE THREAD

**Issue by michaldudak** [MicrosoftDocs/vsts-docs#6139]
Is it anyhow possible for the script from another repository to reference some other file from that repository?

For example, I'd like to have a "Common" repo with yaml templates that use powershell scripts (as external files) and "Application" repo that would include templates from the "Common" one.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6724abea-bbdc-bf66-ed5e-3214fa6c3e66
* Version Independent ID: 4f8dab21-3f0e-da32-cc0e-1d85c13c0065
* Content: [Templates - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/templates?view=azure-devops#using-other-repositories)
* Content Source: [docs/pipelines/process/templates.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/templates.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @vtbassmatt
* Microsoft Alias: **macoope**

**Comment by vtbassmatt** [comment]
[Templates can live in other repositories.](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/templates?view=azure-devops#using-other-repositories)

Soon we will be introducing multi-checkout, so you'll be able to grab the files (tools, scripts, etc.) from those other repos as well.

**Comment by michaldudak** [comment]
@vtbassmatt is the multicheckout feature status tracked anywhere publicly?

**Comment by vtbassmatt** [comment]
https://dev.azure.com/mseng/AzureDevOpsRoadmap/_workitems/edit/1454026
