### ISSUE TITLE
API to get data from custom hubs

### ISSUE THREAD

**Issue by DivvelaLakshmiraj** [MicrosoftDocs/vsts-docs#614]
Are there any API's to get data from these custom hubs...?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b68bebb-14b6-8f83-b362-03d643d39538
* Version Independent ID: de6d224b-2a80-b093-0330-4f70b5892fe3
* Content: [Add a Hub](https://docs.microsoft.com/en-us/vsts/extend/develop/add-hub?view=vsts)
* Content Source: [docs/extend/develop/add-hub.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/extend/develop/add-hub.md)
* Service: **unspecified**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by elbatk** [comment]
Hi @DivvelaLakshmiraj , I know it's been a while, but you will probably find better/quicker answers to product questions on the [Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html) which is actively monitored by the product team, thank you!
