### ISSUE TITLE
File copy from blob

### ISSUE THREAD

**Issue by junpark12** [MicrosoftDocs/vsts-docs#6140]
Hi 
Can i copy files from blob and deploy it to azure vm? It seems like i can only specify blob as target.
Thanks 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 622daa35-c6a1-dac3-17ee-3f9308fc60cd
* Version Independent ID: 2c28a59b-8ef5-d7ab-46a6-58748ec552f5
* Content: [Azure File Copy task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-file-copy?view=azure-devops#feedback)
* Content Source: [docs/pipelines/tasks/deploy/azure-file-copy.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/deploy/azure-file-copy.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by WilliamAntonRohm** [comment]
@junpark12 -- please see the "Destination Type" argument in [that article](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-file-copy?view=azure-devops#arguments).

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.

**Comment by junpark12** [comment]
hi William
My point was that I’d like to use blobs as source.
If I cannot do that now, do you have specific plan for that.
Thanks
