### ISSUE TITLE
Error: Cannot find module 'sync-request'

### ISSUE THREAD

**Issue by cpbattrick** [MicrosoftDocs/vsts-docs#6141]
I have run through the instructions, I believe to the letter.  When trying to run the command "mocha tests/_suite.js" it fails giving the error "Error: Cannot find module 'sync-request'".  Any ideas on whats gone wrong?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 44581f4a-93df-7507-3844-eadedf9a6cc4
* Version Independent ID: 33c7bcf0-1512-975f-5ef8-9f2a192a84ad
* Content: [Add a Build or Release Task](https://docs.microsoft.com/en-us/azure/devops/extend/develop/add-build-task?view=azure-devops#feedback)
* Content Source: [docs/extend/develop/add-build-task.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/extend/develop/add-build-task.md)
* Product: **devops**
* Technology: **devops-ecosystem**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by cpbattrick** [comment]
cracked it, i had the test folder in the route folder and not in the buildAndReleaseTask folder.  Maybe update the instructions so its a bit clearer?

**Comment by WilliamAntonRohm** [comment]
@cpbattrick -- thank you for your feedback.  

@chcomley -- please look into this issue.

**Comment by vairakkumar-vairaperumal** [comment]
I am getting this error even when I am running from within the buildAndReleaseTask 

npm version
{ buildandreleasetask: '1.0.0',
  npm: '6.12.0',
  ares: '1.15.0',
  brotli: '1.0.7',
  cldr: '35.1',
  http_parser: '2.8.0',
  icu: '64.2',
  modules: '64',
  napi: '4',
  nghttp2: '1.39.2',
  node: '10.16.3',
  openssl: '1.1.1c',
  tz: '2019a',
  unicode: '12.1',
  uv: '1.28.0',
  v8: '6.8.275.32-node.54',
  zlib: '1.2.11' }


internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'sync-request'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)

**Comment by jasoncabot-ms** [comment]
You can work around this by installing sync-request from inside the buildAndReleaseTask folder:

```
 npm i --save-dev sync-request
```

**Comment by chcomley** [comment]
@vairakkumar-vairaperumal Did @jasoncabot-ms's work around help? Please let us know if you're still stuck. Thanks!

**Comment by vairakkumar-vairaperumal** [comment]
Yes this resolved the problem. please update document accordingly. Don't know when that step is required to do explicitly and not required explicitly as documentation does not include that step

**Comment by chcomley** [comment]
Fantastic, thanks for letting us know. I'm going to close this issue, however I'll link the PR to this issue, so that you're aware of when the doc has been updated. Thanks very much! In the meantime, if you do have any further questions or feedback, please @mention me in this issue. Thanks very much!
