### ISSUE TITLE
Visual Studio Test Platform Installer and Team Foundation Server 2017

### ISSUE THREAD

**Issue by mayeager22** [MicrosoftDocs/vsts-docs#6143]
This page shows using the task "Visual Studio Platform Installer", yet that task in not available in TFS 2017 and I cannot find it to download from the marketplace.

Is the task available for TFS 2017?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 09e51d18-72ec-1ad4-9ae7-8185c8e1dcd6
* Version Independent ID: 9f2f0471-d123-8e95-1606-cd811d1ece9a
* Content: [Perform UI tests with Selenium - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/test/continuous-test-selenium?view=tfs-2017#feedback)
* Content Source: [docs/pipelines/test/continuous-test-selenium.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/test/continuous-test-selenium.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by PBoraMSFT** [comment]
@mayeager22 - the task is only available on TFS 2018 Update 2 and higher versions. Please refer the task documentation [here](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/vstest-platform-tool-installer?view=azure-devops) 

To run the tests without this task, you will need Visual Studio installed on the agent machines. See bullet #2 in the "Include the test in a release" section of the current doc.
