### ISSUE TITLE
"The master branch corresponds to WikiMaster."  ... should read wikiMaster

### ISSUE THREAD

**Issue by docunid** [MicrosoftDocs/vsts-docs#615]
One occurrence of CamelCase "WikiMaster" were all others occurrences speak of wikiMaster (which is the correct branch name as far as I can tell in git)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dfd8b86a-48ce-08ea-5b24-529c220cc682
* Version Independent ID: 142d1339-6613-29a7-b160-e5ed9a37979b
* Content: [Clone and update wiki pages offline - VSTS & TFS](https://docs.microsoft.com/en-us/vsts/collaborate/wiki-update-offline?view=vsts)
* Content Source: [docs/collaborate/wiki-update-offline.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/collaborate/wiki-update-offline.md)
* Service: **unspecified**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@docunid - Thank you for your correction. I've updated the topic and the update should be published later today.
