### ISSUE TITLE
There are broken line-breaks on the page.

### ISSUE THREAD

**Issue by koskila** [MicrosoftDocs/vsts-docs#6154]
Example:
packagesToPack
Path to csproj or nuspec file(s) to pack"	Pattern to search for csproj directories to pack.\n\nYou can separate multiple patterns with a semicolon, and you can make a pattern negative by prefixing it with '!'. Example: **\\*.csproj;!**\\*.Tests.csproj

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0fa37a3f-6551-16ad-e164-a4ac522cdaab
* Version Independent ID: a3fd6935-2b99-92ef-4eb3-3249fca01f8a
* Content: [NuGet restore, pack, and publish task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/package/nuget?view=azure-devops)
* Content Source: [docs/pipelines/tasks/package/nuget.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/package/nuget.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @chasewilson
* Microsoft Alias: **phwilson**

**Comment by koskila** [comment]
I think a screenshot illustrates this better:
![image](https://user-images.githubusercontent.com/4086860/67664381-373e6480-f970-11e9-9b4f-09b35c22945f.png)

**Comment by msebolt** [comment]
@koskila  Thank you for the feedback, we'll take a look at getting these changes made.

**Comment by koskila** [comment]
Not sure if you accept tiny contributions like this, but I actually already submitted a pull request ( #6155 ) to fix it 😅

**Comment by msebolt** [comment]
Yes, thank you for contributing.  I'll see if I can merge the changes.

**Comment by msebolt** [comment]
The documentation has been updated.

Thank you again for contributing to Microsoft Docs.

**Comment by koskila** [comment]
Thanks & my pleasure!
