### ISSUE TITLE
Add the setting for time zone for scheduled pipelines

### ISSUE THREAD

**Issue by yarko686** [MicrosoftDocs/vsts-docs#6156]
Currently, pipelines support only UTC timezones. It would be very helpful to have the timezone setting for pipelines.
For example we are in UTC+02:00 and we have to move to DST. In case with UTC schedule we will have to manually change the time of the next trigger. If the timezones settings were available this change would have been made automatically.
schedules:
- cron: "30 09 * * Mon-Fri"
  displayName: 'Nightly weekdays build - 4:30 EST'
  always: false
  branches:
    include:
    - master

**Comment by msebolt** [comment]
@yarko686  Thank you for the feedback, unfortunately this is an issue for the product team to address.

Please start a thread in the [Azure DevOps community](https://developercommunity.visualstudio.com/spaces/21/index.html) and link back to this issue.
