### ISSUE TITLE
Live Updates

### ISSUE THREAD

**Issue by timtmok** [MicrosoftDocs/vsts-docs#616]
Live updates weren't added until TFS 2017. The tags at the top list: VSTS | TFS 2018 | TFS 2017 | TFS 2015 | TFS 2013

That seems to imply that TFS 2015 and 2013 have live updates for the kanban board but this is not the case.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 22bc38ee-a124-c3ef-1c08-140d5e02362b
* Version Independent ID: 6e557a0e-3bdf-9a93-22d8-ba3ddfccee86
* Content: [Understand and configure your Kanban board - VSTS & TFS](https://docs.microsoft.com/en-us/vsts/work/kanban/kanban-basics?view=vsts)
* Content Source: [docs/work/kanban/kanban-basics.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/work/kanban/kanban-basics.md)
* Service: **unspecified**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@timtmok - Thank you for your comment. Live updates are support for TFS 2017 and later versions. I have updated the topic and the changes should be live later today or tomorrow.
