### ISSUE TITLE
Who should I believe ?

### ISSUE THREAD

**Issue by nikoNguyen** [MicrosoftDocs/vsts-docs#6161]
Maybe it is time to refresh this interesting comparison, GitLab page show a different result in many areas
https://about.gitlab.com/devops-tools/azure-devops-vs-gitlab.html

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d96200b4-9fc1-7d8c-dce4-6a2b0cb5fa4d
* Version Independent ID: bf8e5f2c-a8a5-d2e1-f89c-5ed5129c32a3
* Content: [Azure DevOps vs GitLab - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/learn/compare/azure-devops-vs-gitlab)
* Content Source: [docs/compare/Azure-DevOps-vs-GitLab.md](https://github.com/MicrosoftDocs/devops-learn-pr/blob/live/docs/compare/Azure-DevOps-vs-GitLab.md)
* Product: **devops**
* Technology: **devops-learn**
* GitHub Login: @SamGu
* Microsoft Alias: **davemcki**

**Comment by msebolt** [comment]
@nikoNguyen Thank you for the feedback.

The article is a dated comparison and we should probably address this in the beginning of the article, instead it's mentioned in the [compare for yourself](https://docs.microsoft.com/azure/devops/learn/compare/azure-devops-vs-gitlab#compare-for-yourself) section.

I'll have the note reworded and added to the top of the document.

**Comment by msebolt** [comment]
Documentation has been updated, please wait 1-2 days for the changes to be published live.
