### ISSUE TITLE
Missing Pipeline Resources Documentation

### ISSUE THREAD

**Issue by jschwanz** [MicrosoftDocs/vsts-docs#6162]
Sprint 159 introduced [CD capabilities for your multi-stage YAML pipelines](https://docs.microsoft.com/en-us/azure/devops/release-notes/2019/sprint-159-update#cd-capabilities-for-your-multi-stage-yaml-pipelines), but there's not any real documentation around how to use it. This is both on the main resources page and the [YAML schema](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema#resources) page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee4ec9d0-e0d5-4fb4-7c3e-b84abfa290c2
* Version Independent ID: 3e2b80d9-30e5-0c48-49f0-4fcdfedf5eee
* Content: [Resources - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/resources?view=azure-devops#feedback)
* Content Source: [docs/pipelines/process/resources.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/resources.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @vtbassmatt
* Microsoft Alias: **macoope**

**Comment by JamesInDenver** [comment]
Seeing this feature in the Sprint 159 update totally confused me.  Everything about multistage pipelines (including the documentation) suggested that the tooling was moving towards having CI/CD in a single pipeline definition.  Whereas this "CD capability" seems to be taking us back to the classic model of separating build and release into their own definitions.  Some high-level guidance on how this feature fits into the larger pipeline model and how it's intended to be used would be very helpful.

**Comment by ashokirla** [comment]
@JamesInDenver Thanks for the feedback. The intention of this feature to enable scenarios where you can split your pipeline and enable triggers and flow of artifacts across. As you grow up in your devops pipeline, you would need to enable complex scenarios where one team owns a part of your devops process and other teams take dependency on it. This feature is an extension of you CICD pipeline where you can enable CI and CD to be separate wherever required. We will provide full traceability across the pipelines. We will consider your feedback and incorporate in our documentation.

**Comment by BlairMcc** [comment]
Agreed, for example I'd love to know if it's possible to reference a pipeline via a service connection

**Comment by iamsrivatsa** [comment]
The document has been updated and I'll be closing the issue. Thank you for the feedback and feel free to open a new issue if you have any more feedback.
