### ISSUE TITLE
Typo involving publishFeedCredentials and verbosityRestore

### ISSUE THREAD

**Issue by bender2k14** [MicrosoftDocs/vsts-docs#6165]
In the [Arguments section](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/package/nuget?view=azure-devops#arguments), there are two consecutive rows with arguments `publishFeedCredentials` and `verbosityRestore` that look like

|Argument|Description|
|-- | --|
|`publishFeedCredentials` **NEWLINE** Verbosity | Specifies the amount of detail displayed in the output.|
|`verbosityRestore` **NEWLINE** NuGet server | The NuGet service connection that contains the external NuGet server’s credentials.|

That is the second time that `verbosityRestore` has appeared in that table.

These two rows are a typo; they should be combined into one row like this:

|Argument|Description|
|-- | --|
|`publishFeedCredentials` **NEWLINE** NuGet server | The NuGet service connection that contains the external NuGet server’s credentials.|

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0fa37a3f-6551-16ad-e164-a4ac522cdaab
* Version Independent ID: a3fd6935-2b99-92ef-4eb3-3249fca01f8a
* Content: [NuGet restore, pack, and publish task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/package/nuget?view=azure-devops)
* Content Source: [docs/pipelines/tasks/package/nuget.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/package/nuget.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @chasewilson
* Microsoft Alias: **phwilson**

**Comment by msebolt** [comment]
@bender2k14  Thank you for the contribution and feedback.

The documentation has been updated and is pending review.
