### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by kevinpshan** [MicrosoftDocs/vsts-docs#6169]
http://scaledagileframework.com/business-epic-kanban/  gives a 404.  In the new version it may be this link https://www.scaledagileframework.com/portfolio-kanban/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1c926cb3-ed15-3489-65f8-2a5c1fd129d4
* Version Independent ID: 1b441906-10f0-2ec0-d1aa-d3686ff94146
* Content: [Scaled Agile Framework - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/plans/scaled-agile-framework?view=azure-devops#feedback)
* Content Source: [docs/boards/plans/scaled-agile-framework.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/boards/plans/scaled-agile-framework.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by msebolt** [comment]
@kevinpshan  Thank you for the feedback and fixed link.

The document has been updated and is pending review.
