### ISSUE TITLE
benefits unclear

### ISSUE THREAD

**Issue by drdamour** [MicrosoftDocs/vsts-docs#6170]
this doc doesn't really seem to clarify why i would use a deployment job, it says i can view the history but doesn't say why a deployment job's history is different than any other job? is there a special place we can view deployment history? can we add a link to the docs about that place?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5aeeaace-1c5b-a51b-e41f-f25b806155b8
* Version Independent ID: fd7ff690-b2e4-41c7-a342-e528b911c6e1
* Content: [Deployment jobs - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/deployment-jobs?view=azure-devops)
* Content Source: [docs/pipelines/process/deployment-jobs.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/deployment-jobs.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by msebolt** [comment]
@drdamour  Thank you for the feedback, assigning this to the author for review.

**Comment by lukepuplett** [comment]
Agree. I'm beginning to doubt if the cost of learning, remembering and fighting for hours with the slow trial and error feedback loop of a build pipeline, and with all this YAML (which I'm sure will change next year and the year after that) beats using Az DevOps to trigger a tiny console app I could write and debug locally to run the whole thing, in a language of my choice, and with total freedom.

There's a lot of time-saving tech that looks irresistible, we're told is recommended, has social proof/pressure but turns out to be yak shaving.

**Comment by soccerjoshj07** [comment]
One of the benefits of a Deployment job is being able to target an environment, which lets you utilize approvals in the pipeline.

Another benefit is that a Deployment job will download all published pipeline artifacts automatically without having to specify them with -download or similar.

**Comment by RoopeshNair** [comment]
@drdamour - environment is a collection of resources that can be targeted by deployments from a pipeline. Environments can include Kubernetes clusters, Azure web apps, virtual machines, databases. Typical examples of environment names are Dev, Test, QA, Staging, and Production.

Not all pipelines runs reach all the way to production. So the traceability of what's new for an environment becomes important. Deployment job enables traceability. You can view what's new compared to previous deployment on the environment.

**Comment by drdamour** [comment]
@RoopeshNair why are you closing this without updating the article to explain the beneifts? You disnt address any of my questions at all. Yes i know it has history but look at what i asked:

> says i can view the history but doesn't say why a deployment job's history is different than any other job? is there a special place we can view deployment history? can we add a link to the docs about that place?

The documentation doesnt go far enough to explain why and how you use these benefits.  And youre not trying to convince me, i use them all the time.  The ticket is about the weakness of the documentation

**Comment by lukepuplett** [comment]
Hello - I agree with this sentiment. I usually raise GitHub doc issues not to get "tech support" but to have the documentation improved.

Thanks!
