### ISSUE TITLE
Does Universal Packages supported by Azure DevOps Server?

### ISSUE THREAD

**Issue by rofehaim** [MicrosoftDocs/vsts-docs#6175]
I tried to upload a universal package to Azure DevOps Server but I get an error "Universal Packages are not supported in Azure DevOps Server" but I can find any document that approves it...
I have Azure DevOps Server 2019 Update1 RC1

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 405dfb6a-2f3d-1d74-2d28-d00be3bb069d
* Version Independent ID: d446b533-c215-6302-3df2-93b1ffd936df
* Content: [Publish and download Universal Packages in pipelines - Azure Pipelines and TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/universal-packages?view=azure-devops&tabs=classic#feedback)
* Content Source: [docs/pipelines/artifacts/universal-packages.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/artifacts/universal-packages.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @chasewilson
* Microsoft Alias: **phwilson**

**Comment by chasewilson** [comment]
@rofehaim thank you for the feedback. We try and ensure that the Universal Packages documentation doesn't show when you are looking at the DevOps Server 2019 versioned docs. However. I think it is something I could add to the Q&A section of the documentation to make it a bit clearer. I'll update here when it's merged and ready to go live :)

**Comment by chasewilson** [comment]
@rofehaim Thank you again. The change has been made and you should be able to see it live within 24 hours
