### ISSUE TITLE
Usage of repository resource is extremely not obivious

### ISSUE THREAD

**Issue by nuclear0wl** [MicrosoftDocs/vsts-docs#6179]
Hello, now I'm trying to recognise how to add additional repositories to my pipeline and it is a real challenge.
I want to achieve such architecture: in one repository I have branch where my YAML pipelines are stored, in the same repository I have second branch where my source code which I want to build using my pipeline stored.
I've added following code to my YAML pipeline:
```
resources:
  repositories:
  - repository: 'source_code'
    type: git
    name: 'my-repo'
    ref: 'branch-with-source-code'
``` 
My pipeline was executed successfully, but if I can find source code contained in branch for pipelines in Build.SourcesDirectory directory, I can't see any footsteps of my second branch which containing my source code. In cause of that, I don't know how to build code which is stored in my source code branch.
Could you please provide some examples how repository resource should be used.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7458d5b2-1bb7-7d87-7ce6-2b0c430b0155
* Version Independent ID: edf5bbd3-a3f0-5426-e985-31290f8afd05
* Content: [YAML schema - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema#feedback)
* Content Source: [docs/pipelines/yaml-schema.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/yaml-schema.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @vtbassmatt
* Microsoft Alias: **macoope**

**Comment by vtbassmatt** [comment]
We have not rolled out [multi-repo checkout](https://github.com/microsoft/azure-pipelines-yaml/blob/master/design/multi-checkout.md) yet, so adding a second repository as a resource won't help you check out its code. That feature will ship in a few weeks, at which time the docs will be updated.

In the meantime, see [this topic](https://docs.microsoft.com/azure/devops/pipelines/repos/pipeline-options-for-git?view=azure-devops#clone-a-second-repo) for a workaround.
