### ISSUE TITLE
How often the agent ask for jobs?

### ISSUE THREAD

**Issue by leodaruiz** [MicrosoftDocs/vsts-docs#6190]
"Periodically, the agent checks to see if a new job request has been posted for it in the job queue in Azure Pipelines/TFS."
How often is that? Is there a way to configure this recurrence?
Are the "deployment groups" recommended for Production environments?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 47625b86-abd5-ee15-6d61-8bcf81861b96
* Version Independent ID: be9a6174-a69b-7aed-d584-5f602fcc5eb4
* Content: [Azure Pipelines Agents - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/agents?view=azure-devops#feedback)
* Content Source: [docs/pipelines/agents/agents.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/agents/agents.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by msebolt** [comment]
@leodaruiz Thank you for the question, assigning this to the author for review.

**Comment by damccorm** [comment]
Hey @leodaruiz thanks for the question

>"Periodically, the agent checks to see if a new job request has been posted for it in the job queue in Azure Pipelines/TFS."
How often is that? Is there a way to configure this recurrence?

The doc actually appears to be a little off on what's happening here. In reality, the agent is continuously waiting on the server via an HTTP long poll (a common pattern when the server is initiating interactions with the client). I'll update the docs shortly.

> Are the "deployment groups" recommended for Production environments?

Sure! In fact, one of the (hypothetical) groups mentioned in the first paragraph of our docs on deployment groups is labeled "Production" 😄

**Comment by damccorm** [comment]
Thank you for your feedback. 
The article reference is being updated to address the issue.
