### ISSUE TITLE
Small error regarding default setting for batch

### ISSUE THREAD

**Issue by Cepheus0815** [MicrosoftDocs/vsts-docs#6192]
In the doc it says: batch: boolean # batch changes if true (the default); start a new build for every push if false

But the default behavior seems to be set to false if not specified, not true

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7458d5b2-1bb7-7d87-7ce6-2b0c430b0155
* Version Independent ID: edf5bbd3-a3f0-5426-e985-31290f8afd05
* Content: [YAML schema - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema#feedback)
* Content Source: [docs/pipelines/yaml-schema.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/yaml-schema.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @vtbassmatt
* Microsoft Alias: **macoope**

**Comment by msebolt** [comment]
@Cepheus0815 Thank you for the feedback, assigning this to the author for review.

**Comment by vtbassmatt** [comment]
Sorry for the long delay. Confirmed that batching is now working, and that `batch: false` is the default.
