### ISSUE TITLE
Could not transfer artifact

### ISSUE THREAD

**Issue by brubom** [MicrosoftDocs/vsts-docs#6193]
Hi team,

I created my Azure DevOps company, project and user token. Tested with both with FullAccess permission and Custom Defined (Packaging -&gt; Read & Write) 

When I run my publish, I'm getting "Could not transfer artifact com.xxxx.xxxx:xxxi-lib:jar:1.1.0 from/to remote" and
"Received status code 404 from server: Not Found"

Can you please assist me?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 52da1009-6733-d555-3c00-1a1bd77f1759
* Version Independent ID: 72b916de-2836-460b-2889-67981ffea5a4
* Content: [Publish a Maven artifact using Gradle and Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/artifacts/gradle/publish-package-gradle?view=azure-devops#feedback)
* Content Source: [docs/artifacts/gradle/publish-package-gradle.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/artifacts/gradle/publish-package-gradle.md)
* Product: **devops**
* Technology: **devops-artifacts**
* GitHub Login: @chasewilson
* Microsoft Alias: **phwilson**

**Comment by brubom** [comment]
Fixed the issue. You need to Connect to Feed, choose Gradle and copy the displayed url.

**Comment by msebolt** [comment]
@brubom  Thank you for the feedback and solution.

Assigning this to the author as an added note to the documentation.

**Comment by chasewilson** [comment]
@brubom Thanks for the feedback and I'm glad that you were able to get things worked out! I'll be Adding a note for some clarity.
