### ISSUE TITLE
Unable to Use a custom task published and private since the account name is not recognized

### ISSUE THREAD

**Issue by vairakkumar-vairaperumal** [MicrosoftDocs/vsts-docs#6197]
Published a custom task successfully. However, it does not show up manually in the task list OR if I use get it it does not show the organization that I am associated with when I am logged into Azure DevOps.

Related Issue that I had resolved earlier as suggested in solution:
https://github.com/MicrosoftDocs/vsts-docs/issues/6141

**Comment by msebolt** [comment]
@vairakkumar-vairaperumal Thank you for the further info.

This can also be added as a note in the documentation until the underlying issue is resolved.

Assigning this to the author for review.

**Comment by chcomley** [comment]
@vairakkumar-vairaperumal I've added a note in a number of articles, pointing to the newest documentation on extension development, which is at [Azure DevOps Extension SDK](https://developer.microsoft.com/en-us/azure-devops/develop/extensions). Thank you and please let us know whether you have any further questions. PR is linked to this issue.
