### ISSUE TITLE
How to handle items being added to previously prioritized backlog

### ISSUE THREAD

**Issue by djhunt77** [MicrosoftDocs/vsts-docs#6198]
When team members move work items into the backlog iteration path, those items are injected into the prioritized backlog based on whatever Backlog Priority value they had prior to being moved. This leaves the impression that the new work items have been prioritized relative to the other work items already in the backlog, which of course is not true.

How do you suggest we handle new work items added to the backlog that need to be prioritized? Should we set the Backlog Priority to an arbitrarily high value so that they will automatically be added to the bottom of the list?

Urban Turtle has a nice feature for handling this. If the Backlog Priority is set to 0, then the work item will appear in a separate "Unordered Items" section where they can be moved and prioritized within the existing ordered items.

**Comment by msebolt** [comment]
@djhunt77 Thank you for the feedback.

Unfortunately this involves feedback for the product team address in the [Azure DevOps community](https://developercommunity.visualstudio.com/spaces/21/index.html).

Please see if either [this post](https://developercommunity.visualstudio.com/content/problem/214273/sort-by-priority-does-not-work.html) or [this](https://developercommunity.visualstudio.com/content/problem/299132/related-work-sorting-is-never-in-backlog-priority.html) addresses the issue, start a new thread, and link back to this issue.

**Comment by djhunt77** [comment]
Thank you Matthew.

I posted the following suggestion:

https://developercommunity.visualstudio.com/idea/801916/unable-to-identify-and-effectively-manage-items-ad.html
