### ISSUE TITLE
Need more info on Update All Agents

### ISSUE THREAD

**Issue by lygasch** [MicrosoftDocs/vsts-docs#6199]
When I (fearfully) clicked the button to Update All Agents, I got some of the information I needed, like that running jobs would complete and new jobs would be paused. But I would also like to know about how long it would take per agent, and to have that info in the docs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 47625b86-abd5-ee15-6d61-8bcf81861b96
* Version Independent ID: be9a6174-a69b-7aed-d584-5f602fcc5eb4
* Content: [Azure Pipelines Agents - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/agents?view=azure-devops#feedback)
* Content Source: [docs/pipelines/agents/agents.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/agents/agents.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by msebolt** [comment]
@lygasch  Thank you for the feedback.

Status of the time sounds more like a feature request and needs to be directed to the product team in the [Azure DevOps community](https://developercommunity.visualstudio.com/spaces/21/index.html).

Also this amount of time can vary and is determined by the length of the job.  What exactly can be added to the doc?

**Comment by lygasch** [comment]
I think that the doc should state what the pop-up told me - that running jobs would continue and new jobs would be paused - and that the down time would be on the order of X minutes each agent. As the owner of these systems for my team, I have to know what to expect when scheduling maintenance. Thanks!

**Comment by msebolt** [comment]
I see what you're describing, assigning this to the author for review.

**Comment by steved0x** [comment]
@lygasch Sorry for the long delay, I am adding some new info to the article describing the process for updating agents and with some limited detail about the upgrade process. I have a work item to provide more detail, and when I have it, I will update the article further. Thank you.
