### ISSUE TITLE
In Azure Test Plans, not able to Move a Test Case to another Test Suite in Test Plan view (Need Info)

### ISSUE THREAD

**Issue by BrianGator** [MicrosoftDocs/vsts-docs#6200]
In Microsoft Azure DevOps Test Plans / Test Manager, Test Plan view, how do you Move a Test Case to another Test Suite in the same Test Plan?

I am not able to drag and drop the test case to another suite in the same test plan like I was able to in Test Manager in TFS. 

Clicking the "..." on the test case does not give the option to move the test case. 

Under Test Case Define window, there is no option to move the test case or change the parent suite but there is an option to Add Related Work. 

The Microsoft Azure Dev Ops FAQ Website does not give any info on moving a test case either @ https://docs.microsoft.com/en-us/azure/devops/test/reference-qa?view=azure-devops

**Comment by msebolt** [comment]
@BrianGator Thank you for the feedback.

Please see if this [recent post](https://developercommunity.visualstudio.com/content/problem/752133/cannot-drag-abd-drop-test-case-from-one-test-suite.html) addresses the issue and comment if there are issues.

**Comment by msebolt** [comment]
Closing the issue now, please add additional comments below.
