### ISSUE TITLE
Release pipeline condition base on build variable

### ISSUE THREAD

**Issue by acheraime** [MicrosoftDocs/vsts-docs#6203]
I need to set a condition in my release pipeline based on a variable output of the build that triggered the release. 
Is there any example available for such use case?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f151218-9a11-0078-e038-f96198a76143
* Version Independent ID: 09c4d032-62f3-d97c-79d7-6fbfd89910e9
* Content: [Conditions - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/conditions?view=azure-devops&tabs=yaml#feedback)
* Content Source: [docs/pipelines/process/conditions.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/conditions.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by msebolt** [comment]
@acheraime Thank you for the question.

I think is a good candidate for [Variable groups](https://docs.microsoft.com/azure/devops/pipelines/library/variable-groups?view=azure-devops&tabs=yaml), however this is not yet available dynamically across pipelines, please refer to https://github.com/MicrosoftDocs/vsts-docs/issues/3702 for updates.

Until then a work-around has been posted [here](https://stackoverflow.com/questions/56558143/is-there-a-way-to-set-variables-in-variable-groups).

**Comment by msebolt** [comment]
Closing the issue now, please add additional comments below.
