### ISSUE TITLE
Enabling Templates when using az repos

### ISSUE THREAD

**Issue by rgr375** [MicrosoftDocs/vsts-docs#6204]
My team has starting using the az repos cli commands and I've noticed that when using `az repos pr create` you don't get an option to use a template. Then when you do open the PR in the UI `az repos pr show --id ###### --open` you don't seem to be able to apply / add a template. Is the only way to use templates is via the UI? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a297d54f-48b3-1b68-e828-15d1559d9b2d
* Version Independent ID: fd9dcb35-72f9-f5a9-e0c0-75c3e59ba8d9
* Content: [Improve your pull request descriptions using pull request templates - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/pull-request-templates?view=azure-devops#feedback)
* Content Source: [docs/repos/git/pull-request-templates.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/repos/git/pull-request-templates.md)
* Product: **devops**
* Technology: **devops-code-git**
* GitHub Login: @apawast
* Microsoft Alias: **sdanie**

**Comment by msebolt** [comment]
@rgr375  Thank you for the feedback.

The product team is more apt to handle this through the [Azure DevOps community](https://developercommunity.visualstudio.com/spaces/21/index.html).

Please see if [this issue](https://developercommunity.visualstudio.com/content/problem/396205/azure-pipelines-do-not-allow-you-to-create-from-a.html) is similar for comment (or start a new thread) and link back to this issue.

**Comment by msebolt** [comment]
Closing the issue now, please add additional comments below.
