### ISSUE TITLE
errorActionPreference not working

### ISSUE THREAD

**Issue by winstonhenke** [MicrosoftDocs/vsts-docs#6206]
I'm passing `errorActionPreference: stop` into my task but 
`write-host "error preference is: $errorActionPreference"`
is reporting 
`error preference is: Continue`
Version      : 4.159.3

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fb215324-b1a0-93b5-5022-4bcc7da93bb7
* Version Independent ID: 9eb2977b-ac34-9d53-670e-04fa027bc8e4
* Content: [Azure PowerShell task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-powershell?view=azure-devops)
* Content Source: [docs/pipelines/tasks/deploy/azure-powershell.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/deploy/azure-powershell.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by msebolt** [comment]
@winstonhenke Thank you for the feedback.

Unfortunately this is something better suited for the product team.

Please move to the [azure-pipelines-tasks](https://github.com/Microsoft/azure-pipelines-tasks/issues) repo and provide a link back to this issue.

**Comment by winstonhenke** [comment]
If anyone else has this issue I opened this issue
* https://github.com/microsoft/azure-pipelines-tasks/issues/11671
