### ISSUE TITLE
Contra documentation, increase from 10 free parallel jobs is not available

### ISSUE THREAD

**Issue by ryjones** [MicrosoftDocs/vsts-docs#6207]
[This document](https://docs.microsoft.com/en-us/azure/devops/organizations/billing/buy-more-build-vs?view=azure-devops#microsoft-hosted-cicd) says:

> If your pipelines are in a public project, then you run up to 10 free parallel jobs with unlimited minutes on Microsoft-hosted agents. If you need more, simply contact us.

If you "contact us", you will eventually be told there is no support for increasing this limit. I'm working for [Hyperledger](https://dev.azure.com/Hyperledger/), which is an [open source project](https://www.hyperledger.org) run by the Linux Foundation.

**Comment by msebolt** [comment]
@ryjones  Thank you for the feedback, apologies for the confusion.

The documentation has been updated and is under review.
