### ISSUE TITLE
Any widget example for azure-sdk?

### ISSUE THREAD

**Issue by SephirotJustin** [MicrosoftDocs/vsts-docs#6208]
Hello,

This documentation site using the old vss-sdk: https://docs.microsoft.com/en-us/azure/devops/extend/develop/add-dashboard-widget?view=azure-devops

Is there a newer documentation for widgets with the azure sdk or any examples?

I already found this repository with some examples: https://github.com/Microsoft/azure-devops-extension-sample
But there is no widget example or im misunderstood smth?

**Comment by msebolt** [comment]
@SephirotJustin Thank you for the question, assigning this to the author for review.

**Comment by chcomley** [comment]
Hi @SephirotJustin, This should work for you, but please tell me if it doesn't help: https://developer.microsoft.com/en-us/azure-devops/develop/extensions

**Comment by chcomley** [comment]
@SephirotJustin please let me know if you have any further questions by @mentioning me. Thanks!
