### ISSUE TITLE
out of date

### ISSUE THREAD

**Issue by elipapa** [MicrosoftDocs/vsts-docs#6211]
not talking about AD either

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8f06e24b-9d7d-b79c-f75f-44032c529027
* Version Independent ID: d0707a11-f483-f192-14c6-cbbfbe5b8071
* Content: [Add AD/Azure AD groups to security groups - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/security/add-ad-aad-built-in-security-groups?view=azure-devops#feedback)
* Content Source: [docs/organizations/security/add-ad-aad-built-in-security-groups.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/security/add-ad-aad-built-in-security-groups.md)
* Product: **devops**
* Technology: **devops-security**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by WilliamAntonRohm** [comment]
@elipapa -- Thanks for your feedback; we appreciate it. To make sure we have all the information needed to triage your issue, please provide more context around the general task.
