### ISSUE TITLE
azureSubscription value cannot use a Variable

### ISSUE THREAD

**Issue by SamirFarhat** [MicrosoftDocs/vsts-docs#6212]
Hi,
Please note the limitation that the azureSubscription field cannot contain a variable. The value needs to be hardcoded.
If i set a variable, the following error is thrown:

input ConnectedServiceNameARM references service connection $(connectedServiceName) which could not be found. The service connection does not exist or has not been authorized for use. For authorization details, refer to https://aka.ms/yamlauthz.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fb215324-b1a0-93b5-5022-4bcc7da93bb7
* Version Independent ID: 9eb2977b-ac34-9d53-670e-04fa027bc8e4
* Content: [Azure PowerShell task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-powershell?view=azure-devops)
* Content Source: [docs/pipelines/tasks/deploy/azure-powershell.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/deploy/azure-powershell.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by pholden77** [comment]
Try this,

azureSubscription: ${{ variables['connectedServiceName'] }}

It's working for me.

**Comment by SamirFarhat** [comment]
Top, it works!! Thanks
