### ISSUE TITLE
Using the virtual support agent

### ISSUE THREAD

**Issue by mkv2** [MicrosoftDocs/vsts-docs#6214]
I spent 5minutes attempting to ask questions that would cause the support agent to help me move organization region... ...it was clever enough to offer me a link to this page(!) but that didn't really help.

With increasing frustration, I clicked on the "Chat Menu" and saw "Change Azure Region" specifically listed.  A tweak to the pointer here, would've saved the bad thoughts.  Maybe this:

"To change your organization region, use Azure DevOps Virtual Support Agent, and click on the Chat Menu."  (if no direct link can be constructed)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be194f45-05b2-8421-186f-f12700eea9aa
* Version Independent ID: efffdc56-fd4c-aeba-6cd3-d07aaf776d51
* Content: [Find or change location or region of organization - Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/change-organization-location?view=azure-devops#feedback)
* Content Source: [docs/organizations/accounts/change-organization-location.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/accounts/change-organization-location.md)
* Product: **devops**
* Technology: **devops-accounts**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @mkv2, Thank you for the suggested update. I'm sorry for the inconvenience. This update is in a PR that's linked to this issue, which should go live sometime today. Thanks again!

**Comment by mkv2** [comment]
Wow that's fast. Thanks!


-------- Original message --------
