### ISSUE TITLE
Does not support Docs Markdown extension

### ISSUE THREAD

**Issue by ChristianJonsson** [MicrosoftDocs/vsts-docs#6216]
As a Microsoft product, it would be really neat if this supported https://docs.microsoft.com/en-us/contribute/markdown-reference

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fa622358-f5bb-1f5c-177a-081a37b6acef
* Version Independent ID: 72f7fd16-a822-66c8-3a34-8905645ce5f2
* Content: [Markdown syntax for files, widgets, and wikis in Azure DevOps - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/project/wiki/markdown-guidance?view=azure-devops)
* Content Source: [docs/project/wiki/markdown-guidance.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/project/wiki/markdown-guidance.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by msebolt** [comment]
@ChristianJonsson Thank you for the feedback.

This is a good idea though more of a suggestion for the product team.

Please use **Suggest a feature** in the [Azure DevOps community](https://developercommunity.visualstudio.com/spaces/21/index.html) to start a dialogue and link back to this issue.

**Comment by msebolt** [comment]
Closing the issue now, please comment any questions below.
