### ISSUE TITLE
Users need to be added to a project before you can add them to a repo

### ISSUE THREAD

**Issue by fiksen99** [MicrosoftDocs/vsts-docs#6219]
If a user has never been added to the project (e.g. by adding it to the Reader group, or any other group) it is not searchable in the repository permissions page. This page should reflect the criteria needed to make a user be searchable in the repo permissions page.

There also appears to be a delay between adding the user to the project and when you can search for that user in the repo, this should be documented.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5f5ce059-ec92-5413-0910-4e28033db034
* Version Independent ID: 540610d3-6073-664d-97f8-e7d8e0a21a20
* Content: [Set Git or TFVC repository permissions - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/security/set-git-tfvc-repository-permissions?view=azure-devops)
* Content Source: [docs/organizations/security/set-git-tfvc-repository-permissions.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/security/set-git-tfvc-repository-permissions.md)
* Product: **devops**
* Technology: **devops-security**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by msebolt** [comment]
@fiksen99 Thank you for the feedback, we apologize for the confusion.

Assigning this to the author for review.

In the meantime, please direct any changes such as page views to the product team in [Azure DevOps community](https://developercommunity.visualstudio.com/spaces/21/index.html) with a link back to this issue.

**Comment by fiksen99** [comment]
for context, my understanding is that adding the user to the project, configures them in the ims scope, which is why they need to added at a project level.

As for the delay between adding the user at project scope and being available to add at repo scope, it appears it can take up to 7 days (!)
https://stackoverflow.microsoft.com/questions/172446/user-not-searchable-in-repository-permissions-settings-for-some-time-after-addin/172927#172927

**Comment by KathrynEE** [comment]
@fiksen99 - Thank you for the feedback. I agree the article needs to be updated with the information you indicated. I will so so later today.

**Comment by fiksen99** [comment]
@KathrynEE It doesn't seem that this item was addressed, though the issue was closed
