### ISSUE TITLE
Secrets section update

### ISSUE THREAD

**Issue by Tr3yb0** [MicrosoftDocs/vsts-docs#6221]
I believe "Select the Secret lock icon to store the variable in an encrypted manner." has been updated in the UI, so the lock icon is no longer present on modal. 
Please update docs to say "Check the 'Keep this value secret' checkbox" or something to that effect.
Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd7e0bd3-1f7d-d7b6-cc72-5ef63c31b46a
* Version Independent ID: dae87abd-b73d-9120-bcdb-6097d4b40f2a
* Content: [Variables - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch)
* Content Source: [docs/pipelines/process/variables.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/variables.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by msebolt** [comment]
@Tr3yb0 Thank you for the feedback, assigning this to the author for review.

**Comment by juliakm** [comment]
Thanks @Tr3yb0. We'll fix this shortly.
