### ISSUE TITLE
Examples for the `Contents` key are misleading

### ISSUE THREAD

**Issue by selimb** [MicrosoftDocs/vsts-docs#6227]
- `\temp*` deletes all files in any sub-folder named temp.
- `\temp` deletes any file or folder with a name that begins with temp.

should be the opposite, no?

- `\temp` deletes all files in any sub-folder named temp.
- `\temp*` deletes any file or folder with a name that begins with temp.

Also, why does `temp` only say "all files" and `temp*` say "any file or folder"? Is this correct?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4cd0e110-4b14-2d96-f28e-d2d2ef53b966
* Version Independent ID: 76cb1df7-c2c5-2de0-fd14-93175838934f
* Content: [Delete Files task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/delete-files?view=azure-devops#feedback)
* Content Source: [docs/pipelines/tasks/utility/delete-files.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/utility/delete-files.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @vtbassmatt
* Microsoft Alias: **macoope**

**Comment by vtbassmatt** [comment]
Good catch. What happened here is that someone ran a tool over all of the docs, and it blindly turned all instances of `**` into `<strong></strong>` pairs. That's... not right in this case :grin: I'll fix it.

**Comment by selimb** [comment]
Aaah that's why the formatting looked off?Thanks for the explanation. Cheers.
