### ISSUE TITLE
Incorrect Information Regarding Azure DevOps IP Addresses

### ISSUE THREAD

**Issue by eriksendc** [MicrosoftDocs/vsts-docs#6230]
Regarding this documentation:
https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops

I have VM's at Rackspace that I deploy to from Azure DevOps. For a long time I had my firewall at Rackspace allowing inbound connections from Azure for port 5986 (WinRM SSL port). But I only whitelisted IP address ranges from the following file, but only for my region (East US 2). 

Recently my deployments stopped working. I spent an hour on the phone with Rackspace, and they watched the inbound traffic from Azure. We collected 5 different samples to see what the originating IP address was. Every single time the IP address not only changed, but it changed regoin. 

The documentation states that the hosted agent will be one from your region. I have proof that this is NOT the case.

Here's where I get the IP address ranges: 
https://www.microsoft.com/en-us/download/details.aspx?id=56519

This documentation should be updated OR the implementation should be fixed so that it's true that you always get a hosted agent from your region.

Feel free to reach out to me by email: eriksendc@yahoo.com.

Regards,
Brian Eriksen
CTO, GetYourPet.com

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 99af681d-41ad-da15-0b72-08b5cd5a11ac
* Version Independent ID: 2fa0df36-a437-8cbb-b019-b49b31b1e116
* Content: [Microsoft-hosted agents for Azure Pipelines - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops)
* Content Source: [docs/pipelines/agents/hosted.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/agents/hosted.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @thejoebourneidentity
* Microsoft Alias: **jobourne**

**Comment by thejoebourneidentity** [comment]
Hi @eriksendc. We tried to make the documentation clear that your hosted agent can run inside any region in your **geography**. https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops#agent-ip-ranges

> Your hosted agents run in the same Azure geography as your organization. Each geography contains one or more regions, and while your agent may run in the same region as your organization, it is not guaranteed to do so. To obtain the complete list of possible IP ranges for your agent, you must use the IP ranges from all of the regions that are contained in your geography. For example, if your organization is located in the United States geography, you must use the IP ranges for all of the regions in that geography.
> 
> To determine your geography, navigate to https://dev.azure.com/<your_organization>/_settings/organizationOverview, get your region, and find the associated geography from the Azure geography table. Once you have identified your geography, use the IP ranges from the weekly file for all regions in that geography.

Once you identify all the regions in your geography, The IP JSON file contains an array called values. Inside that array, you can find the supported IP addresses in an object with a name in the following format: `AzureCloud`.`{your-azure-region}`

**Comment by eriksendc** [comment]
@thejoebourneidentity thanks for the help.

When I go to https://dev.azure.com/getyourpet/_settings/ I see that my Region is East US 2. Can you tell me where to find the official, definitive Azure geography table so I know all the regions I need to deal with? I've googled around and I can't figure out whether US or North America is a geography. 

this is something I found on github:
https://github.com/MicrosoftDocs/azure-docs/blob/master/articles/best-practices-availability-paired-regions.md

this https://azure.microsoft.com/en-us/global-infrastructure/geographies/
seems to be a more "brochure ware" page.

But it seems like there should be something in a JSON file or some very specific table, but I googled "azure geography table" and I can't seem to find a good resource.

Thanks,
-Brian

**Comment by eriksendc** [comment]
@thejoebourneidentity Sorry Joe, I wrote a reply but I didn't read the online doc again and there's a link to the Azure Geography table. So, if I understand the table, then if my region is East US 2, then my Geography is Americas, right? Does that mean I need to whitelist all the regions in the UNITED STATES, AZURE GOVERNMENT, CANADA and BRAZIL columns? Or just those in the UNITED STATES column? The way that table reads with those columns, I'm still confused.

**Comment by thejoebourneidentity** [comment]
United States is the geography. "America's" is just a visual grouping for the geographies page.
