### ISSUE TITLE
Where is the REST API for health status?

### ISSUE THREAD

**Issue by SebastianSchuetze** [MicrosoftDocs/vsts-docs#6231]
The section "Using REST APIs" is saying, that there is a rest API to retrieve the current status, but I cannot find any API or documentation about it. Where can I find this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 55f2bb3a-6619-88c0-ba29-23af30fcb301
* Version Independent ID: 0ede4455-b1df-ffef-743f-126a5e9a1a00
* Content: [Azure DevOps Service Status Documentation](https://docs.microsoft.com/en-us/azure/devops/user-guide/service-status-info?view=azure-devops)
* Content Source: [docs/user-guide/service-status-info.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/user-guide/service-status-info.md)
* Product: **devops**
* Technology: **devops-new-user**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @SebastianSchuetze, Does this help? https://docs.microsoft.com/rest/api/azure/devops/test/runs?view=azure-devops-rest-5.1

**Comment by SebastianSchuetze** [comment]
Hi @chcomley, do it doesn't. The link is also given in the documentation, but it only forwards to the API part for "Test Runs" which is part of Azure Test Plans. But it does not say anything about a Service Availability API to get current Service Health of tenants or degradation notifications.

**Comment by chcomley** [comment]
How about now? https://docs.microsoft.com/en-us/azure/devops/user-guide/service-status-info?view=azure-devops

**Comment by chcomley** [comment]
Hi @SebastianSchuetze, Does this help? https://docs.microsoft.com/en-us/azure/service-health/service-health-overview

**Comment by SebastianSchuetze** [comment]
Thanks! This helped. I suggested an update on the documentation based on your links!

**Comment by chcomley** [comment]
Thanks for your collaboration and update, @SebastianSchuetze! I've just approved the PR. Have a great day!
