### ISSUE TITLE
Explain yaml Queuing policies

### ISSUE THREAD

**Issue by StefanSchoof** [MicrosoftDocs/vsts-docs#6233]
Even when yaml does not support Queuing policies, it should in this documentation explain how the Queuing policy behavior of multi stage yaml is.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4266f72c-c774-0046-4593-d01eb775d3c3
* Version Independent ID: f20827aa-a6c5-96a8-5969-e576ffbc2e38
* Content: [Stages in Azure Pipelines - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/stages?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/process/stages.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/stages.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @vijayma
* Microsoft Alias: **vijayma**

**Comment by vijayma** [comment]
Working on this update to the doc.

**Comment by vijayma** [comment]
Thank you for your feedback. 
The article has been updated to describe what "no queuing policies" means.

**Comment by StefanSchoof** [comment]
Thanks @vijayma
