### ISSUE TITLE
Extract pipeline tests reports

### ISSUE THREAD

**Issue by serbrech** [MicrosoftDocs/vsts-docs#6235]
https://docs.microsoft.com/en-us/azure/devops/pipelines/reports/pipelinereport?view=azure-devops#test-failures-report

These reports are great, however, I can't even copy paste the failing test list to include it in another document.
I want to be able to **export** this list or at least **copy paste it** in an excel sheet, or a wiki.

Maybe allow to create a WorkItem from a failing test in this list, to assign someone to fixing it.
Just visualizing the list does not make it actionable enough.

**Comment by WilliamAntonRohm** [comment]
Thanks for the suggestion! The product teams aren’t always watching this repository, so to make sure it gets in front of them for triage, please [submit your idea here]( https://developercommunity.visualstudio.com/content/idea/post.html?space=21).
