### ISSUE TITLE
Target topic missing: upgrade steps (for Azure DevOps Search)

### ISSUE THREAD

**Issue by NenoLoje** [MicrosoftDocs/vsts-docs#6237]
In the FAQ section, there are two issues with the following text:

&gt; Q: Why doesn't Search work post upgrade to Azure DevOps Server 2019 Update 1?
&gt; A: If the search is set up on a separate (remote) server and source version is TFS Update 2 (or higher), verify that these upgrade steps were followed. If not, then run this script to fix the issue.

Link: https://docs.microsoft.com/en-us/azure/devops/project/search/faq-search?view=azure-devops#q-why-doesnt-search-work-post-upgrade-to-azure-devops-server-2019-update-1

Issues:
1.  It mentions "upgrade steps" under the link: https://docs.microsoft.com/en-us/azure/devops/project/search/administration?view=azure-devops#upgrading-search, but that anchor does not exist on that page. Where is the "Upgrading Search" topic gone?
2. Also, in the text it states "TFS Update 2 (or higher)". It's not clear what version of TFS is meant. 2018? Please clarify!

Thanks,
--Neno

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 281d0249-2b4b-85cf-150b-509805c90931
* Version Independent ID: 897e1ea2-d3fd-b21b-a07c-e62218fad22b
* Content: [FAQs and problem solutions for Search](https://docs.microsoft.com/en-us/azure/devops/project/search/faq-search?view=azure-devops#feedback)
* Content Source: [docs/project/search/faq-search.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/project/search/faq-search.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @chcomley
* Microsoft Alias: **sunar**

**Comment by NenoLoje** [comment]
Follow up: It seems to be problem with the version selector. The FAQ item above is shown for the service, (whereas it really only makes sense for on-prem server), and thus the upgrading topic does not exist when the selector is set to service.

**Comment by chcomley** [comment]
Hi @NenoLoje, Thanks for the heads up on this. I'm about to complete a PR, which addresses your points. Here's the Upgrade Search link: https://docs.microsoft.com/en-us/azure/devops/project/search/administration?view=azure-devops-2019#upgrade-search
