### ISSUE TITLE
Images are outdated

### ISSUE THREAD

**Issue by M1Marcus** [MicrosoftDocs/vsts-docs#6244]
The images are outdated at https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/use-personal-access-tokens-to-authenticate?view=azure-devops&viewFallbackFrom=vsts#create-personal-access-tokens-to-authenticate-access. This is no longer how you get to PAT or the security page

**Comment by chcomley** [comment]
Thanks for your feedback, @M1Marcus. A PR is already in the works, which covers these new steps/screenshots. Thanks again!
