### ISSUE TITLE
Diagram

### ISSUE THREAD

**Issue by DaveJarvis** [MicrosoftDocs/vsts-docs#6246]
Consider adding a diagram that goes from the event, triggering a pipeline run, through to a job being executed on an Agent.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7f8c8539-89a7-a426-868b-96e961c39e29
* Version Independent ID: de260a68-aab7-7c6b-6727-90c92c65b225
* Content: [Azure Pipelines New User Guide - Key concepts - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/get-started/key-pipelines-concepts?view=azure-devops#feedback)
* Content Source: [docs/pipelines/get-started/key-pipelines-concepts.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/get-started/key-pipelines-concepts.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by DaveJarvis** [comment]
For example:

![overview](https://user-images.githubusercontent.com/2131950/68224897-55c1e280-ffa4-11e9-9094-4ff524d898c3.png?_sm_au_=iVVQWk3Sq7jk1qfjF23vvK3kcC4N6)

**Comment by juliakm** [comment]
@DaveJarvis Thank you for this amazing diagram!!!! I'm working on getting it updated to meet our style guidelines and incorporated into the docs.

**Comment by juliakm** [comment]
@DaveJarvis Thanks again for your work on this. An updated version of the graphic is [live](https://docs.microsoft.com/en-us/azure/devops/pipelines/get-started/key-pipelines-concepts?view=azure-devops). We've also added an author credit at the bottom. 

Do you have a Twitter account we can use in a Microsoft tweet? We want to highlight your contribution.

**Comment by DaveJarvis** [comment]
@juliakm I don't have an active Twitter account; a shout out to my technical writing blog would be terrific:  https://dave.autonoma.ca/blog

The posted version looks fantastic. On a minor note, the bulleted list could mention that the steps shown are examples of discrete actions that a step could perform. For example:

> A step can be a task or script and is the smallest building block of a pipeline. A task is a pre-packaged script, such as invoking a REST API or publishing a build artifact.

**Comment by juliakm** [comment]
Thanks for the suggestion. I've updated the text and given you author credit on [the commit](https://github.com/MicrosoftDocs/vsts-docs/commit/599b1a95f2ee61bc2577450bc17934235b1e7da3).
