### ISSUE TITLE
List of REST client reference

### ISSUE THREAD

**Issue by smardine** [MicrosoftDocs/vsts-docs#625]
It's also avalaible here 
https://web.archive.org/web/20161204030435/https:/www.visualstudio.com/en-us/docs/integrate/extensions/reference/client/rest-clients

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 0f99e26d-54fa-ac2c-1814-e1b3f97a87b5
* Version Independent ID: 0ed84e7f-b46f-3a44-16f6-d9bcf77bf11d
* Content: [How to Call a REST API](https://docs.microsoft.com/fr-fr/vsts/extend/develop/call-rest-api?view=tfs-2018)
* Content Source: [docs/extend/develop/call-rest-api.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/extend/develop/call-rest-api.md)
* Service: **unspecified**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by elbatk** [comment]
Thanks @smardine , I'm taking a look at how we can incorporate these elegantly into our new docs. Hopefully I'll execute a solid solution soon! :)
