### ISSUE TITLE
Is the Pipelines Agent supported on Windows Server 2019?

### ISSUE THREAD

**Issue by gholliday** [MicrosoftDocs/vsts-docs#6250]
Under `Check prerequisites` it links to https://aka.ms/vstsagentwinsystem, which makes no mention of `Windows Server 2019`

I expect that it is supported, given that the [Microsoft-hosted agents](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops#use-a-microsoft-hosted-agent) have a `windows-2019` image which runs the same agent.

Can we get the link or the docs updated to include what OS versions are supported?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43799c5d-2f13-cc76-a1c0-a3f850e16d4e
* Version Independent ID: 97a5b73f-faf7-f9c0-9269-fc79984616d6
* Content: [Deploy a Azure Pipelines agent on Windows - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/v2-windows?view=azure-devops#feedback)
* Content Source: [docs/pipelines/agents/v2-windows.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/agents/v2-windows.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by msebolt** [comment]
@gholiday  Thank you for the feedback and for noting the discrepancy.

This should probably changed in the original doc, please move this to the [azure-pipelines-agent](https://github.com/microsoft/azure-pipelines-agent/issues) repo issues and link back here.

Also including @juliobbv

**Comment by vtbassmatt** [comment]
https://github.com/MicrosoftDocs/azure-devops-docs-pr/pull/410
