### ISSUE TITLE
State color change is disabled.

### ISSUE THREAD

**Issue by sachinzen** [MicrosoftDocs/vsts-docs#6252]
Hi,
I am trying to change the color of "Resolved" state in all work items but Azure DevOps is not allowing to change the color. It seems to be disabled or locked.

Thanks
Sachin

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 715eca62-8a31-4163-c27b-f5e71d781982
* Version Independent ID: 06dc711f-1946-29e9-aece-75af903da09b
* Content: [Customize the workflow of an inherited process - Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/organizations/settings/work/customize-process-workflow?view=azure-devops)
* Content Source: [docs/organizations/settings/work/customize-process-workflow.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/settings/work/customize-process-workflow.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by msebolt** [comment]
@sachinzen  Thank you for the feedback.

Unfortunately, default states are non-editable and you will need to use a **custom state** instead.

For product team suggestions, please use **Suggest a Feature** in the [Azure DevOps community](https://developercommunity.visualstudio.com/spaces/21/index.html).  You can use [this post](https://developercommunity.visualstudio.com/content/problem/49890/default-work-item-types-color-changed-and-not-modi.html) for reference.

**Comment by msebolt** [comment]
Closing the issue now, please comment below if needed.
