### ISSUE TITLE
Multiple group rules affecting same user

### ISSUE THREAD

**Issue by LasseNisted** [MicrosoftDocs/vsts-docs#6254]
What determines the final access level if, one group rule assigns Visual Studio Subscriber and another assigns Basic for the same user because the user is in multiple AAD groups?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba38644a-fe6c-e644-2f35-2cf6fa092650
* Version Independent ID: 7d18b423-923f-d9c4-e451-ab7f8ff27bb1
* Content: [Add group rule to assign access levels, extensions - Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/assign-access-levels-and-extensions-by-group-membership?view=azure-devops)
* Content Source: [docs/organizations/accounts/assign-access-levels-and-extensions-by-group-membership.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/accounts/assign-access-levels-and-extensions-by-group-membership.md)
* Product: **devops**
* Technology: **devops-accounts**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by larsroholm** [comment]
And what if said user has no Visual Studio subscription, even though the group rule assigns that access level?

**Comment by msebolt** [comment]
@LasseNisted Thank you for the question, assigning this to the author for review.

In the meantime, please consider using the following support channels:

- [Azure DevOps Support](https://azure.microsoft.com/support/devops/)
- [Azure DevOps on StackOverflow](https://stackoverflow.com/questions/tagged/azure-devops)

**Comment by chcomley** [comment]
Hi @larsroholm, Thanks for reaching out. 

Group rule types are ranked in this order: Subscriber > Basic + Test Plans > Basic > Stakeholder. If a user has a Subscriber rule applied to them, it takes priority over any other applicable rules.

Users always get the best access level between all the group rules, including VS subscription. 

Does this help?

**Comment by LasseNisted** [comment]
Hi @chcomley 
That is a great help - and possibly it should make its way into the documentation?
What we are seeing, though, is that we have group rules that grant Basic and Subscriber, but because the user does not have a Visual Studio subscription, she ends up with "Visual Studio Subscriber (Warning triangle - subscription not found)"  and the behavior seems to indicate that she has Stakeholder access. For us, it would be ideal if it fell back to Basic instead of Stakeholder since we have a group rule granting it.

**Comment by chcomley** [comment]
@LasseNisted, Yes, I'll certainly add this information to an FAQ. It sounds like you may need some further assistance than I can provide here within documentation. Please contact 
[Azure DevOps Support](https://visualstudio.microsoft.com/vs/support/#talktous).
