### ISSUE TITLE
Title of page typo

### ISSUE THREAD

**Issue by JamesBroadberry** [MicrosoftDocs/vsts-docs#6255]
The title of the page has "Scrum" misspelled as "Scum" - this is appearing in Google search results.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1f73858a-31dd-e0fa-cb7f-53dd42192791
* Version Independent ID: f61f9f02-8fbc-4511-e655-3087834302bd
* Content: [Change process from Scum to Agile - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/organizations/settings/work/change-process-scrum-to-agile?view=azure-devops#feedback)
* Content Source: [docs/organizations/settings/work/change-process-scrum-to-agile.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/settings/work/change-process-scrum-to-agile.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @kaelli
* Microsoft Alias: **kaelli**

**Comment by msebolt** [comment]
@JamesBroadberry Thank you for the update and requested change.
