### ISSUE TITLE
Container support

### ISSUE THREAD

**Issue by nmeisenzahl** [MicrosoftDocs/vsts-docs#6258]
It looks like it's not possible to use containerized jobs in deployment jobs. Are there any plans to support those?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5aeeaace-1c5b-a51b-e41f-f25b806155b8
* Version Independent ID: fd7ff690-b2e4-41c7-a342-e528b911c6e1
* Content: [Deployment jobs - Azure Pipelines](https://docs.microsoft.com/en-gb/azure/devops/pipelines/process/deployment-jobs?view=azure-devops#feedback)
* Content Source: [docs/pipelines/process/deployment-jobs.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/deployment-jobs.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by RoopeshNair** [comment]
Yes, we do plan to support it at a future date. We are tracking this on our backlog.

**Comment by przem** [comment]
EOD ?

**Comment by wagnerbsouza** [comment]
Funny thing about this is that I need to run a job in a container using multi-stage pipeline/yaml.
But I need to add approval from a user, which I can do with environment, which I can't use container! :D
Tried to add "Manual intervention", but apparently it's not supported in multi-stage pipeline.

**Comment by RoopeshNair** [comment]
@wagnerbsouza  - we are working on actively to add support for container jobs in deployment. ETA 2-3 months, please stay tuned. We are tracking this closely
