### ISSUE TITLE
YAML: How to disambiguate between service connection that have the same name?

### ISSUE THREAD

**Issue by mahilleb-msft** [MicrosoftDocs/vsts-docs#6259]
Maybe I'm missing something, but service connection can end up having the same name if they're created via the ADO website, e.g., if users connect to an Azure subscription. In this case multiple service connection with the same name but different resource ID may be generated.

When specifying the service connection in YAML (as in the azureSubcription example above), how can two same-named instance be disambiguated? It is possible to specify a resource ID as well? An example would be great...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72b90dd0-49f9-4ed4-3010-9a64dde6ae5a
* Version Independent ID: 6e679d50-4e94-eee3-8793-af884cc909ca
* Content: [Service connections in Azure Pipelines and Team Foundation Server - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/library/service-endpoints?view=azure-devops&tabs=yaml#feedback)
* Content Source: [docs/pipelines/library/service-endpoints.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/library/service-endpoints.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by msebolt** [comment]
@mahilleb-msft  Thank you for the feedback, assigning this to the author for review.

**Comment by mahilleb-msft** [comment]
@ashokirla - could you comment whether this is even possible?

**Comment by ashokirla** [comment]
Hi @mahilleb-msft, you can use service connection ID(guid) instead. You can get the endpoint ID from the service connection URL.

**Comment by mahilleb-msft** [comment]
Thanks @ashokirla, I tried that but couldn't get it working so far.

```
azureSubscription: c2b4eb01-3d2d-44ff-9820-xxxxxxxxxxxx
```

This is the "resourceId" from the URL, or the id as it shows in the endpoint Azure DO Rest API.
Is it pending on a roll out? Is the format wrong?

**Comment by mahilleb-msft** [comment]
(Same connection specified by name works)

**Comment by mahilleb-msft** [comment]
Using resourceId worked now, can you confirm if it was part of a new roll-out? Thanks.

**Comment by ashokirla** [comment]
Yes, it is the resource ID from URL and it is currently supported in YAML. We have now stopped allowing creation of service connections with duplicate names. So you should not face this issue going forward. For the existing service connections with duplicate names, we are looking for ways to make them unique so that you can get unblocked in YAML. Until then, I suggest you to use endpoint ID instead of name.

**Comment by mahilleb-msft** [comment]
Thanks @ashokirla. We started doing that once supported.
