### ISSUE TITLE
Graph from statis suite

### ISSUE THREAD

**Issue by jojo268** [MicrosoftDocs/vsts-docs#626]
Hello, I would like to know if it's possible to create graph for all test campaign. Test campaing is consists of 5 statis suite: Acceptance t., Functional t. and 3 more. 
And every statis suite is consists of another statis suite and requirement-based suite. 
I am not able create graph just with first 5 statis suite. It's some solution for this or can TFS create graph based-on statis suite?
Thank you for answer.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec77cbbd-d4cc-c640-4b58-727a3a916937
* Version Independent ID: 0ac96dcc-ac51-349d-3fcb-b9540089c6eb
* Content: [Track test status - manual testing in VSTS](https://docs.microsoft.com/en-us/vsts/manual-test/getting-started/track-test-status?view=vsts)
* Content Source: [docs/manual-test/getting-started/track-test-status.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/manual-test/getting-started/track-test-status.md)
* Service: **unspecified**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by divais** [comment]
Yes, you can create chart for all Suites but it includes the data for all its child suites too. There isn't any mechanism available to create chart for specific children suites.

**Comment by PBoraMSFT** [comment]
@harishkragarwal - can you please take this forward? Divya responded a while ago, but the issue remains open and assigned to me for some reason. Moving this to you.

**Comment by harishkragarwal** [comment]
@jojo268: Divya did respond to your question. Do let know if anything is pending here.
