### ISSUE TITLE
Multiple Resources in the same K8s namespace

### ISSUE THREAD

**Issue by hardcorehead87** [MicrosoftDocs/vsts-docs#6260]
We have a k8s cluster we use for internal projects.
Each project gets deployed in a separate namespace to have some isolation.
A project however can consist of multiple microservices. So these end up in a single namespace.

When defining a K8s resource in a DevOps Environment, the resource name is coupled to that specific namespace it is created for. So we can only create a single resource for our single namespace. Multiple pipelines need to deploy to that same resource and the deployment history isn't split up per pipeline anymore.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77d95db6-9983-7346-d0eb-4b7443e4e252
* Version Independent ID: 0a22cccc-318d-592f-d1ab-09ec01d88087
* Content: [Environment - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/environments?view=azure-devops)
* Content Source: [docs/pipelines/process/environments.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/environments.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by RoopeshNair** [comment]
> Multiple pipelines need to deploy to that same resource and the deployment history isn't split up per pipeline anymore.

Deployments tab on the environment tracks the deployment across pipeline runs.  Can you elaborate what do you mean by history isn't split up per pipeline?

**Comment by hardcorehead87** [comment]
It is more the Resources tab on the environment that is the issue. Here we see the different resources and the last build deployed to that resource. If I for example have a Bookings and a Notification service, I want to see these as separate resources in my environment.

I can't create a Bookings and Notification resource linked to the same k8s namespace however. I'm stuck with a single resource for that single namespace and I can only see the latest build to that single resource. Either the last Bookings or Notification build. Whichever was last.

**Comment by hardcorehead87** [comment]
The current (classic) Releases page gives an overview per pipeline/microservice.
Here we see the history of releases and what release is on which environment.
We can quickly deploy/redeploy/rollback a release.
![releases](https://user-images.githubusercontent.com/5999142/68285928-7e1f0f00-0080-11ea-997a-0224c6a593e8.PNG)

The following image in the docs shows microservices as resources. This led me to believe the Enviroments tab would become the Yaml based counterpart for the Classic releases page.
![environments-run](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/_img/environments-run.png)

My actual issue is, where will I be able to deploy/redeploy/rollback deployments when I'm working with multi-stage yaml pipelines for my release management?

**Comment by RoopeshNair** [comment]
On the panel you see "View environments" button. That will take you to environments view and within that you will find deployment history across pipeline runs..

As for the requirement of re-deploy/rollback. This will be enabled on the stage in run  soon

![image](https://user-images.githubusercontent.com/1370480/68300720-5782c780-00c4-11ea-9d1a-f7e92fca2a17.png)
