### ISSUE TITLE
Relative links to images don't work with preview "New Repos landing pages" enabled

### ISSUE THREAD

**Issue by AndreSteenveld** [MicrosoftDocs/vsts-docs#6261]
When the preview feature "New Repos landing pages" is enabled relative links to images in the same directory don't work. I've tried the other methods of linking an image ("Absolute path in Git" and "Absolute path in TFVC") but these didn't seem to work either.

The browser I've used was Firefox 70.0 (64-bit) on windows. According to the inspector the links weren't correct simply causing a 404.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fa622358-f5bb-1f5c-177a-081a37b6acef
* Version Independent ID: 72f7fd16-a822-66c8-3a34-8905645ce5f2
* Content: [Markdown syntax for files, widgets, and wikis in Azure DevOps - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/project/wiki/markdown-guidance?view=azure-devops)
* Content Source: [docs/project/wiki/markdown-guidance.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/project/wiki/markdown-guidance.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by msebolt** [comment]
@AndreSteenveld Thank you for the feedback.

Unfortunately this is an issue more apt for feedback from the product team.

Please see if [this post](https://developercommunity.visualstudio.com/content/problem/798082/new-repos-landing-pages-preview-feature-doesnt-red.html) addresses the issue, else start a new issue and link back here.

**Comment by AndreSteenveld** [comment]
@msebolt Thanks for the quick reply, the issue you linked didn't seem to be related although someone else reported this exact same issue there as well ([New repo landing page images are not rendered](https://developercommunity.visualstudio.com/idea/807431/new-repo-landing-page-images-are-not-rendered.html)) so I'm guessing this is a known issue now :).

**Comment by sanjeev40084** [comment]
I agree with @AndreSteenveld, the relative path doesn't seem to work to display images in Azure DevOps wiki.
