### ISSUE TITLE
Can byPrereleaseNumber be used with csproj PackageVersion?

### ISSUE THREAD

**Issue by abelfiore** [MicrosoftDocs/vsts-docs#6266]
Is there a way to use NuGetCommand with byPrereleaseNumber to pack/push with the Major, Minor and Patch number defined in a csproj PackageVersion element? In other words, use the Semantic Version from the csproj, and append a generated prerlease number?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 11ed58a1-5819-f3a4-c674-dafcdbd56fbc
* Version Independent ID: d68aca4d-3fd3-1864-09f5-6060295e0399
* Content: [Publishing to NuGet feeds - Azure Pipelines and TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/nuget?view=azure-devops&tabs=yaml#feedback)
* Content Source: [docs/pipelines/artifacts/nuget.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/artifacts/nuget.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @thomps23
* Microsoft Alias: **amullans**

**Comment by msebolt** [comment]
@abelfiore Thank you for the question.

Unfortunately we cannot handle support requests in this forum.

For support options, please refer to:

- [Azure DevOps Support](https://azure.microsoft.com/support/devops/)
- [Azure DevOps on StackOverflow](https://stackoverflow.com/questions/tagged/azure-devops)

Additionally, if you find this feature is not yet available, please use **Suggest a feature** in the [Visual Studio community](https://developercommunity.visualstudio.com/spaces/21/index.html) to get feedback directly from the product team.

**Comment by msebolt** [comment]
Closing the issue now, please comment below if needed.
