### ISSUE TITLE
Broken link: Work item query language (WIQL) syntax

### ISSUE THREAD

**Issue by evilches** [MicrosoftDocs/vsts-docs#6269]
Broken link: Work item query language (WIQL) syntax

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a718268-1105-4def-5f9e-20ea21afc0d7
* Version Independent ID: 0f08fa18-3075-4275-22c7-d5d1c1e260b0
* Content: [Query fields, operators, and macros/variables - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/queries/query-operators-variables?view=azure-devops)
* Content Source: [docs/boards/queries/query-operators-variables.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/boards/queries/query-operators-variables.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by msebolt** [comment]
@evilches  Thank you for the feedback, however I can't seem to find any issues with the link.

Please see if you can access https://docs.microsoft.com/azure/devops/boards/queries/wiql-syntax and post any issues below.

**Comment by msebolt** [comment]
Closing the issue now, please comment below if there are any questions.
