### ISSUE TITLE
Microsoft Stream Video's don't seem to be supported

### ISSUE THREAD

**Issue by Sniipe** [MicrosoftDocs/vsts-docs#627]
For example this internal vid appears as "invalid"
<video src="https://web.microsoftstream.com/embed/video/fccd4ef9-4a3e-4505-9f1b-7a3971d68ad3?autoplay=false&showinfo=true" width=400 controls>
The video is on our Microsoft Stream and the VSTS wiki is ours also.

I tried a youtube link also to no avail.  The only thing that probably works are files ending in .mp4.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 63e81f8a-e33c-afb7-493b-f51f40fafd49
* Version Independent ID: c9495a96-c3e8-00f1-1e53-da6ce584412b
* Content: [Syntax usage for Markdown files, widgets, wikis, and pull requests - VSTS & TFS](https://docs.microsoft.com/en-ie/vsts/collaborate/markdown-guidance?view=vsts#html-tags)
* Content Source: [docs/collaborate/markdown-guidance.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/collaborate/markdown-guidance.md)
* Service: **unspecified**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@Sniipe - You are correct. Embedding a Microsoft Stream or YouTube video into a VSTS wiki isn't supported at this time. Only .mov and .mp4 formatted videos can be embedded with the <video> tag.  Please feel free to add a suggestion to our UserVoice page - https://visualstudio.uservoice.com/forums/330519-team-services.
