### ISSUE TITLE
Explain project retention settings

### ISSUE THREAD

**Issue by moswald** [MicrosoftDocs/vsts-docs#6270]
There has been some confusion on how the project-level retention settings work, and we should explain them a bit more thoroughly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2931f833-b378-efa9-2c43-0d2afea22bd7
* Version Independent ID: ba3138ef-dc42-16c9-fcb3-1af441be7eb8
* Content: [Build and release retention policies - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/policies/retention?view=azure-devops)
* Content Source: [docs/pipelines/policies/retention.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/policies/retention.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by msebolt** [comment]
@moswald  Thank you for the feedback.

If you don't mind, please include some additional details such as tasks to accomplish, missing info, or confusing sections, and I can assign this to the author.
