### ISSUE TITLE
Filter by Teams, rather than Area Path Example Has Multiple Syntax Errors

### ISSUE THREAD

**Issue by rlvandaveer** [MicrosoftDocs/vsts-docs#6271]
https://docs.microsoft.com/en-us/azure/devops/report/powerbi/sample-boards-sprintburndown?view=azure-devops&tabs=powerbi#filter-by-teams-rather-than-area-path

The team line is missing a closing parentheses and closing single quotes on each team value.

Current:
            &"and (Teams/any(x:x/TeamName eq '{teamname}) or Teams/any(x:x/TeamName eq '{teamname}) or Teams/any(x:x/TeamName eq '{teamname}) "

Corrected:
            &"and (Teams/any(x:x/TeamName eq '{teamname}') or Teams/any(x:x/TeamName eq '{teamname}') or Teams/any(x:x/TeamName eq '{teamname}')) "

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cae009f6-b650-9162-0a5c-f59570288022
* Version Independent ID: 8778491f-74cf-a42a-1fcd-658c16e80965
* Content: [Sprint Burndown sample Power BI report - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/report/powerbi/sample-boards-sprintburndown?view=azure-devops&tabs=powerbi#all-sprints-since-the-beginning-of-the-year)
* Content Source: [docs/report/powerbi/sample-boards-sprintburndown.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/report/powerbi/sample-boards-sprintburndown.md)
* Product: **devops**
* Technology: **devops-analytics**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by msebolt** [comment]
@rlvandaveer Thank you for the feedback, assigning this to the author for review.

**Comment by KathrynEE** [comment]
@rlvandaveer - Thank you for the correction. I will update the article today.
