### ISSUE TITLE
Demand on steps

### ISSUE THREAD

**Issue by KUGA2** [MicrosoftDocs/vsts-docs#6277]
Can a Step or a Step Template have additional demands?

This would be very handy. I know Tasks can have extra demands that are inherited to the job.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7458d5b2-1bb7-7d87-7ce6-2b0c430b0155
* Version Independent ID: edf5bbd3-a3f0-5426-e985-31290f8afd05
* Content: [YAML schema - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=example#step-templates)
* Content Source: [docs/pipelines/yaml-schema.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/yaml-schema.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @vtbassmatt
* Microsoft Alias: **macoope**

**Comment by vtbassmatt** [comment]
No. This is a feature of the task, not of a step or template.

**Comment by KUGA2** [comment]
Could you add this as a new feature?

I think it would be nice to specify the demands where they are generated instead of globally.
