### ISSUE TITLE
Why spaces in ${{ }}

### ISSUE THREAD

**Issue by KUGA2** [MicrosoftDocs/vsts-docs#6279]
In all examples in the documentation where the full template expression syntax is used it allways contains spaces in the brackets. Why?

It is not neccessary (https://camel.readthedocs.io/en/latest/yamlref.html#sequences) not is it used in other brackets.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6724abea-bbdc-bf66-ed5e-3214fa6c3e66
* Version Independent ID: 4f8dab21-3f0e-da32-cc0e-1d85c13c0065
* Content: [Templates - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/templates?view=azure-devops#template-expressions)
* Content Source: [docs/pipelines/process/templates.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/templates.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @vtbassmatt
* Microsoft Alias: **macoope**

**Comment by vtbassmatt** [comment]
I don't understand this feedback. From the point of view of a YAML parser, "`${{ whatever }}`" is just an arbitrary string. Whether it contains spaces inside the braces is not something YAML would have an opinion about. Spaces make expressions easier to read and to tell apart from `$(macro)` syntax.

Have I missed something about your feedback? If so, my apologies and please feel free to clarify.

**Comment by KUGA2** [comment]
No. I just wanted to know if there is any hidden Syntax difference between `${{ whatever }}` and `${{whatever}}`. There is not. You only use spaces to emphasize here.

Thanks.
