### ISSUE TITLE
Defining input with isRequired: "false" doesn't work

### ISSUE THREAD

**Issue by ez-ms** [MicrosoftDocs/vsts-docs#6283]
This documentation show how to define inputs for a custom control configuration: https://docs.microsoft.com/en-us/azure/devops/extend/develop/custom-control?view=azure-devops

However, using `WorkItemField` combined with `isRequired: "false"` doesn't work:
```
"inputs": [
    {
        "id": "FieldName",
        "description": "The field associated with the control.",
        "type": "WorkItemField",
        "properties": {
            "workItemFieldTypes": ["String"]
        },
        "validation": {
            "dataType": "String",
            "isRequired": false
        }
    }
...
```
This is the error I get when trying to submit the form:
![image](https://user-images.githubusercontent.com/57455601/68323166-ccea9a00-00bc-11ea-9f63-70292bba4f87.png)

**Comment by chcomley** [comment]
Hi @ez-ms, This bug is fixed and should ship with our next sprint deployment this month! Thanks so much for reaching out. Please let me know whether you have any further questions by @mentioning me. Have a great day.
