### ISSUE TITLE
Conflicting Info in Document

### ISSUE THREAD

**Issue by billdiekmann** [MicrosoftDocs/vsts-docs#6289]
https://docs.microsoft.com/en-us/azure/devops/user-guide/tools?view=azure-devops
Tools and clients that connect to Azure DevOps
10/30/2019

Office integration tools
You can integrate the following Microsoft Office tools with Azure DevOps.

**Document States**

Project: By using Project, you can plan projects, schedule tasks, assign resources, and track changes. You have access to additional features, such as a project calendar, Gantt charts, and resource views.
Project Professional: With Project Professional, project managers and software development teams can use the tools that they prefer, work at the level of precision that supports their needs, and easily share information.

Clicking on the links for either Project or Project Professional take you to a page that is 2 months older that states 
"Starting with Visual Studio 2019, the Team Foundation plug-in for Office is deprecating support for Microsoft Project. Project integration and the TFSFieldMapping command is not supported for Azure DevOps Server 2019 nor for Azure DevOps Services. However, you can continue to use Microsoft Excel."

Current DevOps document states you can use Project, but supporting document states it has been deprecated.
Which one is correct?

**Comment by msebolt** [comment]
@billdiekmann  Thank you for the feedback, please refer to the linked documentation noting the feature will be deprecated.

A note will be added to the initial document as well to avoid further confusion.
