### ISSUE TITLE
Not enough information for "Collect code coverage metrics with Coverlet"

### ISSUE THREAD

**Issue by jeffw-wherethebitsroam** [MicrosoftDocs/vsts-docs#6297]
This is included in the Run Tests task:
--settings $(System.DefaultWorkingDirectory)/CodeCoverage.runsettings
But fails with "The Settings file 'd:\a\1\s/CodeCoverage.runsettings' could not be found."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec716c61-248c-75c9-2bc7-262749cc7421
* Version Independent ID: 45f47edc-e800-2c42-416a-92cd93c9e892
* Content: [Build, test, and deploy .NET Core apps - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/ecosystems/dotnet-core?view=azure-devops#feedback)
* Content Source: [docs/pipelines/ecosystems/dotnet-core.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/ecosystems/dotnet-core.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by msebolt** [comment]
@jeffw-wherethebitsroam Thank you for the feedback.

Were you able to get the task running with the correct location of the *.runsettings* file?  

I'm guessing the author was also using `$(System.DefaultWorkingDirectory)` for their working Visual Studio projects folder.

**Comment by jeffw-wherethebitsroam** [comment]
@msebolt my issue here was that I don't have a .runsettings file or any idea what I would put in that file to make this work. I run coverlet locally using `dotnet test /p:CollectCoverage=true`. Is the .runsettings file a Visual Studio only thing? It seems a strange workflow for a linux user.

**Comment by msebolt** [comment]
@jeffw-wherethebitsroam Sorry for the delay on this, are you able to get the example working?

*.runsettings* is specific to Visual Studio, refer to [Configure unit tests](https://docs.microsoft.com/visualstudio/test/configure-unit-tests-by-using-a-dot-runsettings-file).

In your case you should be able to remove all arguments except `--CollectCoverage true`.

**Comment by msebolt** [comment]
Closing issue, please comment below if there are questions.
