### ISSUE TITLE
Template not found with complex folder structure

### ISSUE THREAD

**Issue by acheraime** [MicrosoftDocs/vsts-docs#6299]
It seems like templates have to live in same directory level as the pipeline that uses them otherwise the will not be found.
By example I have this folder structure:

I have a pipeline file under foo/bar/baz/azure-pipelines.yml which references a template located at foo/ci/template.yml.
In azure-pipelines.yml I call the template as follow
- template: ../../ci/template.yml
and 
- template: foo/ci/template.yml 
No luck. 
Did anyone try template with similar folder structure?

Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6724abea-bbdc-bf66-ed5e-3214fa6c3e66
* Version Independent ID: 4f8dab21-3f0e-da32-cc0e-1d85c13c0065
* Content: [Templates - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/templates?view=azure-devops)
* Content Source: [docs/pipelines/process/templates.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/templates.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @vtbassmatt
* Microsoft Alias: **macoope**

**Comment by vtbassmatt** [comment]
The path to the template should be relative to the place that includes it, so your first example is the correct syntax. I just tested this and it works for me.

File structure:
<img width="258" alt="image" src="https://user-images.githubusercontent.com/714283/68415884-581d6b80-0161-11ea-9186-1af159556f39.png">

Pipeline contents:
<img width="288" alt="image" src="https://user-images.githubusercontent.com/714283/68415951-7b481b00-0161-11ea-9481-265541a0eb34.png">

Results:
<img width="772" alt="image" src="https://user-images.githubusercontent.com/714283/68415908-68354b00-0161-11ea-9ec0-a6d685b2d380.png">

**Comment by acheraime** [comment]
@vtbassmatt That worked! I had a typo in my pipeline.


Thanks.
