### ISSUE TITLE
Remove preview tag from this article

### ISSUE THREAD

**Issue by rjmille2** [MicrosoftDocs/vsts-docs#6300]
According to this blog post https://devblogs.microsoft.com/devops/improved-continuous-delivery-capabilities-and-caching-for-azure-pipelines/ this feature is no longer in preview.  Just trying to figure out which document is correct.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77c20289-dab2-7a6e-4f63-4b30eaff2c71
* Version Independent ID: d75cc196-90c1-8291-9907-ff405bde4edf
* Content: [Pipeline caching - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/caching/?view=azure-devops#feedback)
* Content Source: [docs/pipelines/caching/index.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/caching/index.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @willsmythe
* Microsoft Alias: **wismythe**

**Comment by msebolt** [comment]
@rjmille2 Thank you for the feedback, assigning this to the author for review.

**Comment by wnjenkin** [comment]
@rjmille2 thank you for reporting this. Working on a fix

**Comment by Slooz** [comment]
Why was this closed? The documentation still says it's in preview. Is it in preview or is it not?

**Comment by steved0x** [comment]
It is out of preview and I am fixing that TOC right now, sorry for the delay.

**Comment by steved0x** [comment]
> Why was this closed? The documentation still says it's in preview. Is it in preview or is it not?

I am fixing this right now and it should contain a link to the commit with the fix, it will be live later today.

**Comment by steved0x** [comment]
@Slooz I just signed off on the PR to fix this so it should be live soon, sorry that this one fell through the cracks and thank you for letting us know and following up on it. 👋

**Comment by Slooz** [comment]
No problem, thanks for the prompt response!
