### ISSUE TITLE
Setting workingDirectory for all steps

### ISSUE THREAD

**Issue by nishants** [MicrosoftDocs/vsts-docs#6315]
Can I set a `workingDirectory ` at the build (steps) level, instead of setting for all tasks (step) individually ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7458d5b2-1bb7-7d87-7ce6-2b0c430b0155
* Version Independent ID: edf5bbd3-a3f0-5426-e985-31290f8afd05
* Content: [YAML schema - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema#feedback)
* Content Source: [docs/pipelines/yaml-schema.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/yaml-schema.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @vtbassmatt
* Microsoft Alias: **macoope**

**Comment by vtbassmatt** [comment]
Unfortunately not. You can file a feature request at [Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html).
