### ISSUE TITLE
Outdated screenshot

### ISSUE THREAD

**Issue by axelson** [MicrosoftDocs/vsts-docs#6317]
There are now two menus in the upper right. A picture of a person with a gear and your avatar/initials. The first screenshot on this page tells you to click your avatar/initials to get to "Personal access token" but now it is under the picture of a person with a gear.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 53f99d2d-363b-d01d-039d-4fdc636fa2df
* Version Independent ID: f47330d5-e2de-36a4-e5b3-5bc77505b161
* Content: [Authenticate with personal access tokens - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/use-personal-access-tokens-to-authenticate?view=azure-devops&tabs=preview-page#feedback)
* Content Source: [docs/organizations/accounts/use-personal-access-tokens-to-authenticate.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/accounts/use-personal-access-tokens-to-authenticate.md)
* Product: **devops**
* Technology: **devops-security**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by msebolt** [comment]
@axelson  Thank you for the feedback, assigning this to the author for review.

**Comment by chcomley** [comment]
Thanks very much for your feedback, @axelson. The update will be published today!

**Comment by axelson** [comment]
Awesome, thanks so much!
