### ISSUE TITLE
Is it possible to choose a previous version Microsoft-hosted agent?

### ISSUE THREAD

**Issue by AlexChongMicrosoft** [MicrosoftDocs/vsts-docs#6321]
The Microsoft-hosted agent update itself. Is it possible to choose one previous version of agent?
For example, now the Ubantu agent version is "2.160.0" with image version "20191025.1". Is it possible to choose image version "20190930.2"?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 61db3371-6395-88a2-fb78-09f98790ab1b
* Version Independent ID: ef6f1bf7-02b8-9093-b84e-c9bde7d98e57
* Content: [Microsoft-hosted agents for Azure Pipelines - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops#feedback)
* Content Source: [docs/pipelines/agents/hosted.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/agents/hosted.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @thejoebourneidentity
* Microsoft Alias: **jobourne**

**Comment by thejoebourneidentity** [comment]
Not today. It's something we've considered but have not committed to yet.

**Comment by AlexChongMicrosoft** [comment]
Hi @thejoebourneidentity , thank you very much.

**Comment by IanKemp** [comment]
Why would you want to do this?

**Comment by AlexChongMicrosoft** [comment]
@IanKemp thank you for attention. Honestly, one user meets issue after we upgrade the OS image. So the user want to get the privous one. But luckily, we found the root cause and overcome it. It's because customer's component is too old to get the new OS image's support.

Sorry to bother you. But at least, I know it's impossible. Next time I can reply users directly and try to help them find out the root cause.
