### ISSUE TITLE
plenty to read at what?

### ISSUE THREAD

**Issue by cblp** [MicrosoftDocs/vsts-docs#6322]
> It’s not quite so simple. Others have already documented the value of monorepos (plenty to read at ).

Plenty to read at what? Is something missed?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b96a80c2-e52c-85b6-d472-ced16f9154a2
* Version Independent ID: f721244d-2d89-8fce-4db6-ab0b6db25225
* Content: [Git Virtual File System Design History - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/learn/git/gvfs-design-history)
* Content Source: [docs/git/gvfs-design-history.md](https://github.com/MicrosoftDocs/devops-learn-pr/blob/live/docs/git/gvfs-design-history.md)
* Product: **devops**
* Technology: **devops-learn**
* GitHub Login: @SamGu
* Microsoft Alias: **sanoursa**

**Comment by msebolt** [comment]
@cblp  Thank you for the feedback.  

The documentation has been updated and is pending review.
