### ISSUE TITLE
Two words seem to be swapped

### ISSUE THREAD

**Issue by CarstenSchelp** [MicrosoftDocs/vsts-docs#6324]
Hi,

In the first paragraph the words "migration" and "history" appear to be swapped:

> However, many people want to perform a more advanced migration, including history. This guidance will introduce a __history__ with __migration__.

No big deal, but still ...

Kind regards, Carsten

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: edd6cbc8-5e3b-c3a1-4672-d42510cc058b
* Version Independent ID: 8fe81fb5-7c2d-2562-5659-55fccbb3126c
* Content: [Migrate from Subversion (SVN) to Git](https://docs.microsoft.com/en-us/azure/devops/repos/git/perform-migration-from-svn-to-git?view=azure-devops)
* Content Source: [docs/repos/git/perform-migration-from-svn-to-git.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/repos/git/perform-migration-from-svn-to-git.md)
* Product: **devops**
* Technology: **devops-code-git**
* GitHub Login: @hkamel
* Microsoft Alias: **hkamel**

**Comment by msebolt** [comment]
@CarstenSchelp  Thank you for the feedback.

The documentation has been updated and is pending review.
