### ISSUE TITLE
How to distribute tests on multiple agents?

### ISSUE THREAD

**Issue by marcussonestedtbarium** [MicrosoftDocs/vsts-docs#6325]
I'm struggling to find a good link and/or description of this in the documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 57dd4383-2206-3912-993e-773e8dc69c2d
* Version Independent ID: 537e5ce0-d483-2b56-5ec9-8bdef2d01635
* Content: [Visual Studio Test task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/test/vstest?view=azure-devops)
* Content Source: [docs/pipelines/tasks/test/vstest.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/test/vstest.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @PBoraMSFT
* Microsoft Alias: **pbora**

**Comment by msebolt** [comment]
@marcussonestedtbarium Thank you for the feedback, assigning this to the author for review.

**Comment by PBoraMSFT** [comment]
@marcussonestedtbarium - you can find a detailed doc [here](https://docs.microsoft.com/en-us/azure/devops/pipelines/test/parallel-testing-vstest?view=azure-devops).

And, using the multi-agent capability for distribution with other test runners is outlined [here](https://docs.microsoft.com/en-us/azure/devops/pipelines/test/parallel-testing-any-test-runner?view=azure-devops)

**Comment by marcussonestedtbarium** [comment]
Hi @PBoraMSFT,

Thanks for your response! The first link explains not with YAML, but with gui config. 

The second is what I was looking for. I think ti would help if that page was linked directly from the doc for the VSTest task.

Thanks for your awesome work on Azure devops

BR
/Marcus

**Comment by PBoraMSFT** [comment]
@marcussonestedtbarium - yes, we will get the topic linked from the VSTest task doc.
Also will enhance the doc to include the YAML snippet for job setup.

**Comment by marcussonestedtbarium** [comment]
👍👍

Den tis 12 nov. 2019 12:19Prachi Bora <notifications@github.com> skrev:
