### ISSUE TITLE
Example Result of Parent Query is Wrong

### ISSUE THREAD

**Issue by iamwyza** [MicrosoftDocs/vsts-docs#6335]
The parent query shows that multiple levels of parents will be returned, however in the current version of DevOps only the first ancestor is returned.  There does not appear to be a way to allow it to exceed the depth of 1.  (Ideally it should, but if it won't anymore, the documentation needs to be updated to note that depth of hierarchical queries is now fixed at 1.)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e97a5d24-74dc-c495-5a48-0ccad5a61304
* Version Independent ID: 6e6e297e-8491-243e-6744-f5e96f5b2f20
* Content: [Query for linked work items - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/report/extend-analytics/work-item-links?view=azure-devops#feedback)
* Content Source: [docs/report/extend-analytics/work-item-links.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/report/extend-analytics/work-item-links.md)
* Product: **devops**
* Technology: **devops-analytics**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@greggboer - Can you address this issue?

**Comment by greggboer** [comment]
I apologize. The doc is incorrect. We currently limit expands to a max levels of 1. 
To make the doc correct, we should
Remove the "levels=max" from the query statement
Remove the second level of Parents from the result set.

![image](https://user-images.githubusercontent.com/1141784/69160170-f1bc1580-0a9d-11ea-900f-624967d46235.png)

**Comment by KathrynEE** [comment]
@iamwyza - Thank you for your feedback. We are updating the article today.
