### ISSUE TITLE
Duplicated word

### ISSUE THREAD

**Issue by caminsha** [MicrosoftDocs/vsts-docs#6337]
Hi 

In the section [Give Great Feedback](https://docs.microsoft.com/en-us/azure/devops/learn/git/git-pull-requests#give-great-feedback) there is a typo in the following sentence:

> Identify the the issue and give a specific suggestions on what you would do differently.

In the above sentence the word "the" is written twice.

Correct sentence would be:
Identify the issue and give a specific suggestions on what you would do differently.

Kind Regards

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ff23ed00-53ad-e289-bf1e-084055036ec3
* Version Independent ID: 6a428e43-b647-9631-add5-43d54c4981b6
* Content: [Get feedback with pull requests - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/learn/git/git-pull-requests)
* Content Source: [docs/git/git-pull-requests.md](https://github.com/MicrosoftDocs/devops-learn-pr/blob/live/docs/git/git-pull-requests.md)
* Product: **devops**
* Technology: **devops-learn**
* GitHub Login: @SamGu
* Microsoft Alias: **routlaw**

**Comment by WilliamAntonRohm** [comment]
Thank you for your feedback.  I have updated the documentation and it should be live by tomorrow.
