### ISSUE TITLE
Notification setting required?

### ISSUE THREAD

**Issue by rbarna1** [MicrosoftDocs/vsts-docs#6340]
Hi, we're using @mentions in our work items.  No one is getting the email notifications mentioned on this page.  Is there some sort of user or organizational setting required to ensure that the @mention emails are sent?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 34ae521f-6ae4-4d7f-2cce-f844e5811b66
* Version Independent ID: 18098490-1f34-e966-3135-cb90197bfa6f
* Content: [Use @mentions in work items and pull requests - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/notifications/at-mentions?view=azure-devops#feedback)
* Content Source: [docs/notifications/at-mentions.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/notifications/at-mentions.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by rbarna1** [comment]
User error. :(  Notifications working fine.

**Comment by pantheraleonessa** [comment]
I'm having this same issue. I get notifications when mentioned on PRs, but not stories, tasks or features. Is there a way to be notified when mentioned on these? Or is it only for PRs?

**Comment by komatat** [comment]
Not working for us either for the last couple of months. Nothing about user mentions exists in Notifications settings.

**Comment by vvenkitaswamy** [comment]
@mentions work when we first send out notifications to a user. When the user responds to that notification just by hitting reply, it is received as an email and does not get transferred into the user story. I would like to have that trail for the communication when the user forgets to use View Work Item to respond .
