### ISSUE TITLE
Mermaid JS text is not rendered properly in DevOps Wiki

### ISSUE THREAD

**Issue by srinugopi09** [MicrosoftDocs/vsts-docs#6341]
Text is not rendered properly in a consistent way in DevOps Wiki. Lack of Consistency is preventing us to use Azure Wiki for long term.

**Comment by WilliamAntonRohm** [comment]
It looks like you've encountered an issue with the product itself, rather than an issue with the documentation. To make sure it gets in front of the right people, please [submit your bug]( https://developercommunity.visualstudio.com/content/problem/post.html?space=21) here.
