### ISSUE TITLE
No documentation about how to set variables using expressions when using variable groups

### ISSUE THREAD

**Issue by JGCreator** [MicrosoftDocs/vsts-docs#6346]
Because there is a contingency on using the name/value syntax for pipeline variables when that pipeline also uses group variables, there needs to be some documentation (or support) for setting pipeline variables in name/value syntax using expressions. The documentation about variables (https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch#set-variables-using-expressions)  is silent on how to set with expressions using this syntax. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4827aa99-ae62-bd63-6f2f-a87a4065ed27
* Version Independent ID: c9e461ee-7f42-3503-9460-18fa3a807bbb
* Content: [Variable groups for Azure Pipelines and TFS - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/library/variable-groups?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/library/variable-groups.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/library/variable-groups.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by fredbuluku** [comment]
> Because there is a contingency on using the name/value syntax for pipeline variables when that pipeline also uses group variables, there needs to be some documentation (or support) for setting pipeline variables in name/value syntax using expressions. The documentation about variables (https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch#set-variables-using-expressions) is silent on how to set with expressions using this syntax.
> 
> #### Document Details
> ⚠ _Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking._
> 
> * ID: 4827aa99-ae62-bd63-6f2f-a87a4065ed27
> * Version Independent ID: c9e461ee-7f42-3503-9460-18fa3a807bbb
> * Content: [Variable groups for Azure Pipelines and TFS - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/library/variable-groups?view=azure-devops&tabs=yaml)
> * Content Source: [docs/pipelines/library/variable-groups.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/library/variable-groups.md)
> * Product: **devops**
> * Technology: **devops-cicd**
> * GitHub Login: @RoopeshNair
> * Microsoft Alias: **ronai**

**Comment by daveneeley** [comment]
See also: https://github.com/microsoft/azure-pipelines-yaml/issues/340

**Comment by RoopeshNair** [comment]
@vtbassmatt for expression syntax documentation

**Comment by vtbassmatt** [comment]
[Name/value vs mapping syntax](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch#specifying-variables) was added during our docathon last month, so perhaps this is no longer an issue? Both of the following will work:

```yaml
variables:
  someVar: ${{ parameters.value }}
# -- vs --
variables:
- name: someVar
  value: ${{ parameters.value }}
```

I don't want to get into the business of showing every syntax feature combined with every other syntax feature - it's a combinatorial explosion :)
