### ISSUE TITLE
Is there any resource/feed subscription to be informed about build agent updates?

### ISSUE THREAD

**Issue by molehillrocker** [MicrosoftDocs/vsts-docs#6348]
Is there any resource/feed I can subscribe to, to get informed when build agents are updated with more up-to-date software/tool versions? If so, please point me to the direction, since I did not find anything (despite the GitHub repo which I'd have to monitor on a regular basis).

This week our builds were failing because we used tools that did depend on NodeJS 10 and as soon as the build agent was updated to NodeJS 12, our builds failed. Now we use the NodeJS extension to explicitly install NodeJS 10 again (until we move to NodeJS 12), but it would be nice to get informed about such changes prior to when they are applied so that we can react appropriately if something needs to be adjusted.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 99af681d-41ad-da15-0b72-08b5cd5a11ac
* Version Independent ID: 2fa0df36-a437-8cbb-b019-b49b31b1e116
* Content: [Microsoft-hosted agents for Azure Pipelines - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml&viewFallbackFrom=vsts#software)
* Content Source: [docs/pipelines/agents/hosted.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/agents/hosted.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @thejoebourneidentity
* Microsoft Alias: **jobourne**

**Comment by msebolt** [comment]
@molehillrocker Thank you for the question.

For now you just need to set a watch on the GitHub to **Releases only**, see [here](https://github.com/isaacs/github/issues/410).

For anything built-in please use either **Suggest a feature** in the [Azure DevOps community](https://developercommunity.visualstudio.com/spaces/21/index.html) or transfer the issue to [azure-pipelines-image-generation](https://github.com/microsoft/azure-pipelines-image-generation/issues) for a response from the product team.

**Comment by molehillrocker** [comment]
Thanks for the hint, I'll do that for now.
