### ISSUE TITLE
Undocumented "dynamic variable" $(build.containerId)

### ISSUE THREAD

**Issue by jan-kenneth** [MicrosoftDocs/vsts-docs#6352]
When publishing artifacts in a build pipeline you can get the container id it was published to by using the variable `$(build.containerId)` which is not documented as far as I can see.

Is the documentation lacking a section on "dynamic variables"?

This variable is useful within the build itself enabling generation of the URLs to specific files in the published build artifact, you can generate the same URL that will be available in the Azure DevOps UI if you manually click a build's "Artifacts Explorer" -> "Copy download URL" option.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ffebdc8-521c-44b5-cde4-4abdc1bd6f18
* Version Independent ID: dc0effda-6d93-62aa-64c5-4e6f283b0826
* Content: [Predefined variables - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/build/variables.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/build/variables.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by msebolt** [comment]
@jan-kenneth  Thank you for the question, assigning this to the author for review.

**Comment by juliakm** [comment]
I'm working on getting clarification from the product team on`$(build.containerId)`.
