### ISSUE TITLE
Unintended links.

### ISSUE THREAD

**Issue by GaTechThomas** [MicrosoftDocs/vsts-docs#6357]
We have comments with "#" in them in old git commits that have caused a ton of links to be created in work items. Is it possible to disable this functionality or filter what #'s are seen in some way?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 22780209-b809-62af-1d6e-ed4c91db867a
* Version Independent ID: 1d6afe6e-6420-2395-0e0b-05902572f7ab
* Content: [Use ID to link work items in discussions & pull requests - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/notifications/add-links-to-work-items?toc=%2Fazure%2Fdevops%2Fboards%2Ftoc.json&bc=%2Fazure%2Fdevops%2Fboards%2Fbreadcrumb%2Ftoc.json&view=azure-devops#feedback)
* Content Source: [docs/notifications/add-links-to-work-items.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/notifications/add-links-to-work-items.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by msebolt** [comment]
@GaTechThomas  Thank you for the question.

The product team is better apt to offer a recommendation or start a feature request if this is currently unsupported.

Please move this issue to the [Azure DevOps community](https://developercommunity.visualstudio.com/spaces/21/index.html) using either **Report a problem** or **Suggest a feature**.

**Comment by msebolt** [comment]
Closing this now, please comment below if there are any further issues.

**Comment by GaTechThomas** [comment]
I did find that this can be disabled at the repository level. The ADO repo UI exposes the functionality. Would be nice to have a bit more functionality, such as patterns that should be ignored or first changeset to start caring about.
