### ISSUE TITLE
Can I use Azure File Copy task to copy from blob storage to local or staging environment?

### ISSUE THREAD

**Issue by saroup** [MicrosoftDocs/vsts-docs#6366]
[Enter feedback here]
I want to use the azure file copy task in azdo ci pipepline to copy from a blob storage to a staging directory. Can I use the source path to put the url of the blob?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 622daa35-c6a1-dac3-17ee-3f9308fc60cd
* Version Independent ID: 2c28a59b-8ef5-d7ab-46a6-58748ec552f5
* Content: [Azure File Copy task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-file-copy?view=azure-devops)
* Content Source: [docs/pipelines/tasks/deploy/azure-file-copy.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/deploy/azure-file-copy.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by RoopeshNair** [comment]
@saroup  - The file copy step doesn't support copying from Azure Storage. Instead you can use `az storage blob download` or `AzCopy /Source:URLr /SourceKey:key /S`
