### ISSUE TITLE
Multi-pipelines for mono-repo

### ISSUE THREAD

**Issue by M0ns1gn0r** [MicrosoftDocs/vsts-docs#6367]
Although the default name of configuration file is "azure-pipeline**S**.yaml" it looks like this file allows to define only **a single** pipeline.

The docs don't mention this limitation explicitly. They also don't seem to provide a guide on how one supposes to maintain a set of pipelines for multiple microservices in a mono-repo.

Ideally I would like to have a single azure-pipelines.yaml in the root which references other pipeline definitions in sub-folders. When a new definition is added there, a corresponding pipeline is created in DevOps.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7458d5b2-1bb7-7d87-7ce6-2b0c430b0155
* Version Independent ID: edf5bbd3-a3f0-5426-e985-31290f8afd05
* Content: [YAML schema - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema&viewFallbackFrom=vsts)
* Content Source: [docs/pipelines/yaml-schema.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/yaml-schema.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @vtbassmatt
* Microsoft Alias: **macoope**

**Comment by vtbassmatt** [comment]
The name of the product is "Azure Pipelines", hence the name of the YAML file.

You can have multiple pipelines pointing to one YAML file. And for example, you could make that pipeline expect a variable telling it which directory to build, and then each of your definitions could set the variable differently. Alternatively, you can have as many pipeline YAMLs as you want in the repo.

Auto-creation is something we've considered, but it hasn't bubbled up the backlog yet. To make sure your voice is heard, you should file a feature request on [Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html). (And interestingly, [not everyone wants us to do the auto-creating thing at all](https://developercommunity.visualstudio.com/content/problem/348951/commiting-an-update-to-a-file-named-vsts-ciyml-aut.html).)

**Comment by M0ns1gn0r** [comment]
Thanks Matt, done: https://developercommunity.visualstudio.com/idea/820717/allow-defining-multiple-pipelines-in-one-yaml-conf.html
