### ISSUE TITLE
View deployment status cross-project

### ISSUE THREAD

**Issue by sudo-md** [MicrosoftDocs/vsts-docs#6368]
At this moment, it's not possible to view the deployment status of a pipeline in a different project. In our enterprise we differentiate between Agile projects and code projects. 

Is it possible to add this functionality?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 462be419-4cfd-4bfc-06cc-45800c0d888b
* Version Independent ID: 95cb8a7d-c61d-dfac-403f-12fe40ba1c49
* Content: [Link work items to deployments - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/work-items/work-item-deployments-control?view=azure-devops#feedback)
* Content Source: [docs/boards/work-items/work-item-deployments-control.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/boards/work-items/work-item-deployments-control.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by WilliamAntonRohm** [comment]
Thanks for the suggestion! The product teams aren’t always watching this repository, so to make sure it gets in front of them for triage, please [submit your idea]( https://developercommunity.visualstudio.com/content/idea/post.html?space=21) here.

**Comment by sudo-md** [comment]
hi @WilliamAntonRohm 

It's a shame that it's possible to do this automatically. anyway, I've made a post [here](https://developercommunity.visualstudio.com/idea/822152/view-deployment-status-cross-project.html) with the exact same question.

Have a nice day

**Comment by WilliamAntonRohm** [comment]
@sudo-md -- thank you for your feedback, and for making that post.

You as well!
