### ISSUE TITLE
Out of Date Videos

### ISSUE THREAD

**Issue by schellem** [MicrosoftDocs/vsts-docs#6371]
Main page videos are great in explaining the concepts but worthless for showing us how to do it things in the UI since Microsoft keeps changing the the UI.
https://docs.microsoft.com/en-us/azure/devops/repos/git/?toc=%2Fazure%2Fdevops%2Frepos%2Fgit%2Ftoc.json&bc=%2Fazure%2Fdevops%2Frepos%2Fgit%2Fbreadcrumb%2Ftoc.json&view=azure-devops

**Comment by CarlRabeler** [comment]
@schellem Is there a specific video to which are you referring? Is it one of the two on this page: https://docs.microsoft.com/en-us/azure/devops/repos/git/?toc=%2Fazure%2Fdevops%2Frepos%2Fgit%2Ftoc.json&bc=%2Fazure%2Fdevops%2Frepos%2Fgit%2Fbreadcrumb%2Ftoc.json&view=azure-devops#videos ?

**Comment by schellem** [comment]
@CarlRabeler correct

**Comment by CarlRabeler** [comment]
sent e-mail to listed author

**Comment by WilliamAntonRohm** [comment]
I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
