### ISSUE TITLE
Why $env:SECRET_SAUCE cannot be read?

### ISSUE THREAD

**Issue by mirsaeedi** [MicrosoftDocs/vsts-docs#6372]
There is no reason provided on not being able to read the $env:SECRET_SAUCE variable.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 611642f0-881f-10b9-ae94-3c562001d1f0
* Version Independent ID: 41efb94b-4c7a-64a3-b23b-70c8634ae727
* Content: [Release variables and debugging - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/variables?tabs=powershell&view=azure-devops)
* Content Source: [docs/pipelines/release/variables.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/release/variables.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by RoopeshNair** [comment]
Secret variables are not set as environment variables. You need to explicitly pass them as arguments to your scripts.
