### ISSUE TITLE
What is the "PipelinesSDK" user?

### ISSUE THREAD

**Issue by boblechat** [MicrosoftDocs/vsts-docs#6374]
This new unknown user shows up in all my git repositories permissions page.
What is this new user? What is it used for? Why do I see it in my git permissions page? Why isn't this documented?

![PipelinesSDK](https://user-images.githubusercontent.com/34745154/68879823-5f68ea00-070a-11ea-873b-dafdb13ed12a.png)

Same question here on [StackOverflow](https://stackoverflow.com/questions/56227164/what-is-the-pipelinessdk-user-and-why-has-it-been-added-to-all-of-my-code-repo).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a35602ee-9d11-9746-4b79-075e295a5fb8
* Version Independent ID: dbea8e30-e80b-8f13-987e-ef0ad3ba9b83
* Content: [Default permissions and access quick reference - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/security/permissions-access?view=azure-devops)
* Content Source: [docs/organizations/security/permissions-access.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/security/permissions-access.md)
* Product: **devops**
* Technology: **devops-security**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by marcpopMSFT** [comment]
The PipelinesSDK user identity is used when generating API-specific scoped security tokens.  We're discussing whether to hide it or document it.

**Comment by KathrynEE** [comment]
@boblechat - the Permissions and groups article has been updated with a description. See https://docs.microsoft.com/en-us/azure/devops/organizations/security/permissions?view=azure-devops&tabs=preview-page#user-accounts.
