### ISSUE TITLE
Re: Team Foundation version control command (tf.exe) 

### ISSUE THREAD

**Issue by ctahok** [MicrosoftDocs/vsts-docs#6383]
I spent 40 minutes to search tf.exe for my VS Stdudio code. 
It would be very handy to have a link to download page https://visualstudio.microsoft.com/thank-you-downloading-visual-studio/?sku=TeamExplorer&rel=15 please.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 330532da-d568-b010-a154-62afb1844e4a
* Version Independent ID: 4efad37d-4ec2-033e-51b1-b9f588e675c6
* Content: [Require branches to be created in folders - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/require-branch-folders?view=azure-devops&tabs=browser)
* Content Source: [docs/repos/git/require-branch-folders.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/repos/git/require-branch-folders.md)
* Product: **devops**
* Technology: **devops-code-git**
* GitHub Login: @apawast
* Microsoft Alias: **sdanie**

**Comment by msebolt** [comment]
@ctahok  Thank you for the feedback and apologies for any confusion.

We'll get this link added to the documentation.
