### ISSUE TITLE
Typo: WIT should be WIP

### ISSUE THREAD

**Issue by rhundhausen** [MicrosoftDocs/vsts-docs#6386]
In the first sentence of the "Set WIP limits" section.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c127d0e9-775d-f31f-04b6-8c98d4129a58
* Version Independent ID: d11e9b39-ba12-405d-c5d4-9fe7d831d438
* Content: [Configure WIP limits for Kanban board - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/boards/wip-limits?view=azure-devops#set-wip-limits)
* Content Source: [docs/boards/boards/wip-limits.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/boards/boards/wip-limits.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by msebolt** [comment]
@rhundhausen Thank you for the feedback.

We'll get this fix added to the documentation.
