### ISSUE TITLE
How to "analyze top tasks by duration" in pipeline reports?

### ISSUE THREAD

**Issue by twchapman** [MicrosoftDocs/vsts-docs#6393]
On the page for pipeline reports, under duration report it says "You can review the duration trend and **analyze the top tasks by duration to optimize the duration of the pipeline**."

However, I can't find a way to view that information. It does mention what the top task is on the summary tile, but that's it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2da4714e-d931-6777-d8be-b123a2b0fa17
* Version Independent ID: 09eec061-51ab-e6a9-e61c-0b6f618cd969
* Content: [Pipeline reports - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/reports/pipelinereport?view=azure-devops#pipeline-duration-report)
* Content Source: [docs/pipelines/reports/pipelinereport.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/reports/pipelinereport.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @Additi
* Microsoft Alias: **admahesh**

**Comment by iamsrivatsa** [comment]
@twchapman Thank you for the feedback. As part of the Analytics, you can only see the top counts based on the run duration etc. If you want a detailed insights, log view is the right place. Hope this finds useful.

**Comment by iamsrivatsa** [comment]
I'll be closing the issue. Thank you for the feedback and feel free to open a new issue if you have any more feedback.
