### ISSUE TITLE
Missing support info mentioned in FAQ

### ISSUE THREAD

**Issue by NenoLoje** [MicrosoftDocs/vsts-docs#6397]
On this page, it states:

&gt; "If the status column shows green/OK, and Search is still not working, contact support at the address shown at the end of this topic."

But: there is no contact support address or option at the end of the topic.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 281d0249-2b4b-85cf-150b-509805c90931
* Version Independent ID: 897e1ea2-d3fd-b21b-a07c-e62218fad22b
* Content: [FAQs and problem solutions for Search - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/project/search/faq-search?view=azure-devops-2019#feedback)
* Content Source: [docs/project/search/faq-search.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/project/search/faq-search.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @chcomley
* Microsoft Alias: **sunar**

**Comment by chcomley** [comment]
Hi @NenoLoje, Thanks for letting us know! I've updated the article to include hyperlinks to Support. Thanks again and have a great day!

**Comment by NenoLoje** [comment]
@chcomley - Follow-up question. I see the support link is now: https://visualstudio.microsoft.com/vs/support/#talktous

Is this the most appropriate place? I would think that issues with Azure DevOps Server/TFS Code Search, might be better suited at: https://azure.microsoft.com/en-us/support/devops/, no?
