### ISSUE TITLE
"azureSubscription" is badly named

### ISSUE THREAD

**Issue by riedgar-ms** [MicrosoftDocs/vsts-docs#6400]
On seeing the `azureSubscription` input, I automatically assumed that a subscription id was required. This was not successful, and I eventually discovered that I needed the name of the service connection I created on Project Settings page. While this is implicit in the 'Description' text for the `azureSubscription` input (and indeed makes some sense, since a variety of credentials could be available), the name is highly misleading; changing the input name to 'serviceConnectionName' (or similar) would be much more demonstrative for users.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 69ff8e50-4187-3622-1beb-155f006af5f5
* Version Independent ID: bc56fa96-bded-95f8-39a4-a9e5242db1bf
* Content: [Azure Key Vault task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-key-vault?view=azure-devops#feedback)
* Content Source: [docs/pipelines/tasks/deploy/azure-key-vault.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/deploy/azure-key-vault.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by WilliamAntonRohm** [comment]
It looks like you've encountered an issue with the product itself, rather than an issue with the documentation. To make sure it gets in front of the right people, please [submit your bug]( https://developercommunity.visualstudio.com/content/problem/post.html?space=21) here. 

@RoopeshNair -- fyi

**Comment by riedgar-ms** [comment]
Apologies for the misfiling. Have opened issue on the developer community as suggested. Thanks.

**Comment by WilliamAntonRohm** [comment]
@riedgar-ms -- Richard, no problem!  Thank you for creating that issue.
