### ISSUE TITLE
Add YAML example for self-hosted agent or pool

### ISSUE THREAD

**Issue by jawn** [MicrosoftDocs/vsts-docs#6405]
The only way I found in this page to specify an agent is for hosted agents.

>pool:
>  vmImage: 'ubuntu-16.04' # examples of other options: 'macOS-10.13', 'vs2017-win2016'

This block mentions you can set up a self-hosted agent and links to how you can set those up and their capabilities.

> As an alternative, you can set up a self-hosted agent and save the cost of running the tool installer.

What I would expect from this page
* An example of how to explicitly specify which hosted agent (or pool) is being used. If multiple ways exist, explain them.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec716c61-248c-75c9-2bc7-262749cc7421
* Version Independent ID: 45f47edc-e800-2c42-416a-92cd93c9e892
* Content: [Build, test, and deploy .NET Core apps - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/ecosystems/dotnet-core?view=azure-devops#run-your-tests)
* Content Source: [docs/pipelines/ecosystems/dotnet-core.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/ecosystems/dotnet-core.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by jawn** [comment]
Seems like the missing info is here

![image](https://user-images.githubusercontent.com/1705112/69129565-e9b8a180-0aae-11ea-82a5-251b68437ffc.png)

https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema#pool

**Comment by msebolt** [comment]
@jawn  Thank you for the feedback and for providing the solution.

The documentation has been updated and is pending review.
