### ISSUE TITLE
Modify ServiceHooks permissions for groups instead of user

### ISSUE THREAD

**Issue by pmthexton** [MicrosoftDocs/vsts-docs#6407]
I'm not sure where the best place to submit this is, so raising here in lieu of a better place.

In the Q&A section for service hooks overview, you give an example of using tfssecurity.exe to allow a specific user rights for Edit subscriptions & View subscriptions.

Is it possible to do this to allow a Group these permissions, to allow for more flexible/manageable configuration? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4dc61b61-ed67-8313-99d4-d736e7f48234
* Version Independent ID: 3e0fcf87-9744-cec8-24f8-9f68371959c6
* Content: [Integrate with service hooks - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/service-hooks/overview?view=azure-devops)
* Content Source: [docs/service-hooks/overview.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/service-hooks/overview.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @chasewilson
* Microsoft Alias: **phwilson**

**Comment by msebolt** [comment]
@pmthexton  Thank you for the question.

For further information on using *tfssecurity.exe*, please refer to [Use TFSSecurity to manage groups and permissions](https://docs.microsoft.com/azure/devops/server/command-line/tfssecurity-cmd) and post any additional questions below.

Groups in particular has its own command set, see section [groups](https://docs.microsoft.com/azure/devops/server/command-line/tfssecurity-cmd#groups).
