### ISSUE TITLE
Self-hosted agent and Linux/Windows containers on Windows Server 2019

### ISSUE THREAD

**Issue by ivanignatiev** [MicrosoftDocs/vsts-docs#6408]
Hello, 

Is there a documentation to launch the Azure Pipelines jobs on containers Linux and Windows on Windows Server 2019 ? 

Is it supported by self-hosted agent or we just must prepare our own image and run the agent inside containers? 

Thank you !

Best regards,
Ivan Ignatiev

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43799c5d-2f13-cc76-a1c0-a3f850e16d4e
* Version Independent ID: 97a5b73f-faf7-f9c0-9269-fc79984616d6
* Content: [Deploy a Azure Pipelines agent on Windows - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/v2-windows?view=azure-devops)
* Content Source: [docs/pipelines/agents/v2-windows.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/agents/v2-windows.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by msebolt** [comment]
@ivanignatiev Thank you for the question.

Typically the agent will run the container and you specify either your own or a pre-built image, see [azure-pipelines-image-generation](https://github.com/microsoft/azure-pipelines-image-generation).  Also note that containers are not currently supported on MacOS agents.

However, for added flexibility containers can also run agents, see [Running a self-hosted agent in Docker](https://docs.microsoft.com/azure/devops/pipelines/agents/docker).  

For further documentation, please refer to [Container jobs](https://docs.microsoft.com/azure/devops/pipelines/process/container-phases).
