### ISSUE TITLE
Old screenshot for external guest access

### ISSUE THREAD

**Issue by spottedmahn** [MicrosoftDocs/vsts-docs#6413]
Under the [prerequisites](https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/add-external-user?view=azure-devops#prerequisites) there is an outdated screenshot.

**Current one:**
![image](https://user-images.githubusercontent.com/14079228/69169997-50e25000-0ac7-11ea-9a78-2d8977e6089a.png)

**My View:**
![image](https://user-images.githubusercontent.com/14079228/69169962-3f994380-0ac7-11ea-958c-d25d836cb1c1.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b6db4fba-7322-16bc-3431-6b8f933a84bf
* Version Independent ID: a20bd1b0-06d7-8f49-30d2-25c5e188b674
* Content: [Add, invite external users, guest users to your organization - Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/add-external-user?view=azure-devops#prerequisites)
* Content Source: [docs/organizations/accounts/add-external-user.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/accounts/add-external-user.md)
* Product: **devops**
* Technology: **devops-accounts**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @spottedmahn, 

Thanks for the heads up. I've added a preview image in a PR, which will be live today. Thanks again!

**Comment by spottedmahn** [comment]
nice, thanks @chcomley 👍
