### ISSUE TITLE
What activity icon?

### ISSUE THREAD

**Issue by Darko-git** [MicrosoftDocs/vsts-docs#6416]
My profile page does not resemble anything described here. I could have sworn that I used to see these options but not anymore. Is this page out of date?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b4f95345-6686-8e29-ff3f-cbea4a6eb24d
* Version Independent ID: 695d975e-ea9b-139b-4f98-f9655a751f59
* Content: [Turn preview features on or off - Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/project/navigation/preview-features?view=azure-devops&source=docs)
* Content Source: [docs/project/navigation/preview-features.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/project/navigation/preview-features.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by Darko-git** [comment]
And it is 'action icon' not 'activity icon'. On my profile page I see some settings for Bookmarks, Connections... looks like a profile page for a social media app. Settings contain some email and notification preferences. Nothing resembling the screenshots on this page.

**Comment by msebolt** [comment]
@Darko-git Thank you for the feedback, assigning this to the author for review.

**Comment by KathrynEE** [comment]
@Darko-git - Thank you for your inquiry. The profile menu did recently change. I am updating the article now to reflect these recent changes. You can get to the Preview features by clicking on the ... actions icon from the profile menu and choosing **User settings**, and then **Preview features**.

![open-preview-features-s161](https://user-images.githubusercontent.com/10856840/69289452-66cc3f80-0bb1-11ea-86f4-736c608a0992.png)

**Comment by Darko-git** [comment]
I am not sure why this is closed, I cannot see what you are showing me.

This is what I see:
![image](https://user-images.githubusercontent.com/5216705/69292181-4eacee00-0bba-11ea-985d-203ad04c7438.png)

**Comment by Darko-git** [comment]
Thanks, I was trying to change this on the docs page which apparently has nothing to do with devops.
