### ISSUE TITLE
Agent IP ranges not clear

### ISSUE THREAD

**Issue by evmimagina** [MicrosoftDocs/vsts-docs#6418]
Hi,

The list that references the Azure Services IP ranges… there's no category for Azure Devops Agents VMs

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 61db3371-6395-88a2-fb78-09f98790ab1b
* Version Independent ID: ef6f1bf7-02b8-9093-b84e-c9bde7d98e57
* Content: [Microsoft-hosted agents for Azure Pipelines - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops#feedback)
* Content Source: [docs/pipelines/agents/hosted.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/agents/hosted.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by damccorm** [comment]
Hey @evmimagina - Azure DevOps agents share the same IPs as the machines they're running on, so they're the same as the IPs we publish, as described [here](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops#agent-ip-ranges)

**Comment by damccorm** [comment]
Thank you for your feedback. 
We are closing this issue as there is no action to take on our part to address the issue.  The guidance provided is correct.

**Comment by evmimagina** [comment]
Non sense, on that list is not clear which category includes the Azure Devops Agents….

**Comment by damccorm** [comment]
Hey @evmimagina - could you help me out a bit - which step are you getting stuck on? I can try to clarify here or in the docs as necessary:

> To determine your geography, navigate to https://dev.azure.com/<your_organization>/_settings/organizationOverview, get your region, and find the associated geography from the Azure geography table. Once you have identified your geography, use the IP ranges from the weekly file for all regions in that geography.

**Comment by evmimagina** [comment]
Ok, let me explain like that… we have that json file, right?

It starts like this;

{
  "changeNumber": 90,
  "cloud": "Public",
  "values": [
    {
      "name": "AzureActiveDirectory",
      "id": "AzureActiveDirectory",
....

Could someone know the name or id where the agent machines fall?

would be nice if the document points to the category that someone should look when trying to find the pool addresses for that machines where the agents are running...

I must say I've been walking and searching through all récords and there's something that looks like a generic category,...

….
      "name": "AzureCloud.westeurope",
      "id": "AzureCloud.westeurope",
….

which matches my region… let's asume we are not still worried about maching the geography, something that increases the list, but just that list is huge! and it looks like it refers to the whole Azure Cloud Service, which is not useful (I'm not gonna whitelist the whole Azure Cloud!)

Hope I've clarified a little bit my concerns about what someone would expect from that article.

Cheers,

**Comment by damccorm** [comment]
> but just that list is huge! and it looks like it refers to the whole Azure Cloud Service, which is not useful (I'm not gonna whitelist the whole Azure Cloud!)

Because we're just spinning up a VM in Azure, that's basically what is necessary - we intentionally don't have dedicated machines (and along with that IPs) for scale reasons, and we offer [self hosted agents](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/agents?view=azure-devops&tabs=browser#install) if that's not a security boundary you're comfortable with.

Even if we could offer a more restricted IP range, it wouldn't really change the security boundary - at the end of the day, we're using Azure machines to run our hosted pool, and other code can be run from that machine

**Comment by damccorm** [comment]
I'm going to close since I think the docs are correct.

**Comment by evmimagina** [comment]
Well Danny, it's not a matter of dedicated machines but just few dedicated pools of public IP addresses. 
I know I could use self hosted agents (thanks for the advice), but might be on Microsoft's interest to offer the chance to keep configuring Azure Cloud Services after provisioning some resources without having to whitelist the whole AzureCloud.
E.g. if I try to secure the AKS API access and keep configuring it using Azure Devops and their hosted agents... it's not possible without whitelisting that huge ammount of  addresses ranges :/

Anyway, close as you think the doc is correct.

Many thanks and best regards,
