### ISSUE TITLE
Selecting Agent at runtime

### ISSUE THREAD

**Issue by nspiteri** [MicrosoftDocs/vsts-docs#6423]
In classic way of creating pipelines, one could select the agent pool at runtime.

This had the added benefit that if I ran out of agents in my hosted pool, I could run it off my self hosted ones.

How do I do this in the Yaml pipelines?

I tried making the pool variable parametrized using expressions but after several attempts I have concluded that the variable would be a runtime variable while the pool parameter is parsed earlier then runtime.  Is this the right conclusion or is there a way around it?

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7458d5b2-1bb7-7d87-7ce6-2b0c430b0155
* Version Independent ID: edf5bbd3-a3f0-5426-e985-31290f8afd05
* Content: [YAML schema - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema#feedback)
* Content Source: [docs/pipelines/yaml-schema.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/yaml-schema.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @vtbassmatt
* Microsoft Alias: **macoope**

**Comment by vtbassmatt** [comment]
We have a feature coming early next year which will make this possible in YAML. Right now, you're correct - it's more or less not possible to override the pool at queue time.
