### ISSUE TITLE
No longer in private preview?

### ISSUE THREAD

**Issue by soccerjoshj07** [MicrosoftDocs/vsts-docs#6424]
This was announced in Sprint 159 so it no longer seems it is in private preview?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4296d1cc-f211-9d17-d97f-2b0858fdea7d
* Version Independent ID: cc66dfee-adde-cdfb-b3f5-5d58d89d3c81
* Content: [Import work items from a csv file through the web - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/queries/import-work-items-from-csv?view=azure-devops)
* Content Source: [docs/boards/queries/import-work-items-from-csv.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/boards/queries/import-work-items-from-csv.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by msebolt** [comment]
@soccerjoshj07 Thank you for the feedback.

The documentation has been updated and is pending review.
