### ISSUE TITLE
Are users charged only for storage of packages? How about upload/download?

### ISSUE THREAD

**Issue by vinyar** [MicrosoftDocs/vsts-docs#6425]
All of the pricing verbiage on this page is centered around 2GB free storage and then sliding scale.
It's unclear if there are any charges for upload/download of packages.

My use case example: I am looking to build 80 packages nightly on my server that lives outside of azure, and then upload all of the artifacts to azure. Lets say I have 8 GB transfer (4 in, 4 out) and 3 GB storage.

What exactly am I going to be charged for? 8GB? 3 GB? 11 GB?

Thank you

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b5531731-8bd5-b178-9307-f01b3d2f23b3
* Version Independent ID: 8dea3b69-ad79-5045-3820-4a83a0bc4ce0
* Content: [Start Using Azure Artifacts. - Azure Artifacts](https://docs.microsoft.com/en-ca/azure/devops/artifacts/start-using-azure-artifacts?toc=%2Fazure%2Fdevops%2Forganizations%2Ftoc.json&bc=%2Fazure%2Fdevops%2Forganizations%2Fbreadcrumb%2Ftoc.json&view=azure-devops)
* Content Source: [docs/artifacts/start-using-azure-artifacts.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/artifacts/start-using-azure-artifacts.md)
* Product: **devops**
* Technology: **devops-artifacts**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by vinyar** [comment]
All of the cloud hosting solutions explicitly call out transfer and hosting prices separately, or at least acknowledge that there is a price associated with transfer if their services are not used for deployment.

To sum it up. There are 3 components of pricing, but the article only references one:
Upload - do you charge for uploading artifacts?
Storage - this is addressed
Download - do you charge for download if packages are not used inside azure?

For reference:
Jfrog: https://jfrog.com/pricing/#saas
GitHub: https://github.com/features/packages#pricing
etc.
https://docs.microsoft.com/en-us/nuget/hosting-packages/overview

Thanks!

**Comment by chcomley** [comment]
Hi @vinyar, Thanks for reaching out. We only charge you for storage. We don't charge for uploading artifacts or downloading packages. We'll charge you for the 3 GB of storage only. I'll make this more clear in the doc. I'll be closing this issue, however please @mention me if you have any further questions! Thanks!

**Comment by vinyar** [comment]
@chcomley  - thank you for clarifying and updating the doc to be more clear.
