### ISSUE TITLE
Push size is limited to 5GB at a time ? Is it true ?

### ISSUE THREAD

**Issue by libihan** [MicrosoftDocs/vsts-docs#6428]
I tried in my machine and encountered the following two scenarios:
1) I have many files whose size is less than 100M, but the total size is 7G --&gt; I can push them at a time successfully
2) I have many files whose size is about 400M, but the total size is 4G --&gt; I can't push them at a time successfully, but only when I reset http.postBuffer, I can push them successfully.

So what the 5GB limitation means ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 96e60bfd-765f-81ad-312d-f46ef9a66ddc
* Version Independent ID: c7ea62ca-1ba4-9a63-30d5-4788f4dce0c4
* Content: [Git limits - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/limits?view=azure-devops#feedback)
* Content Source: [docs/repos/git/limits.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/repos/git/limits.md)
* Product: **devops**
* Technology: **devops-code-git**
* GitHub Login: @apawast
* Microsoft Alias: **sdanie**

**Comment by msebolt** [comment]
@libihan  Thank you for the question.

To address the first point, the individual file limit is `5GB` and the overall limit is `10GB` so this scenario is acceptable.

As to the second point, the `http.postBuffer` setting is more a reflection of Azure's [rate limits](https://docs.microsoft.com/azure/devops/integrate/concepts/rate-limits?view=azure-devops), a somewhat vague blend of CPU and throughput based on TSTUs.

For further information, please refer to the product team using the [Azure DevOps community](https://developercommunity.visualstudio.com/topics/Azure+DevOps.html).

**Comment by msebolt** [comment]
Closing now.  Please add comments below if there are further issues.
