### ISSUE TITLE
How to associate Environment with Release Stage with classic UI (without yaml)?

### ISSUE THREAD

**Issue by rolfik** [MicrosoftDocs/vsts-docs#6429]
Is it possible to associate an Environment to a Release stage using UI?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77d95db6-9983-7346-d0eb-4b7443e4e252
* Version Independent ID: 0a22cccc-318d-592f-d1ab-09ec01d88087
* Content: [Environment - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/environments?view=azure-devops)
* Content Source: [docs/pipelines/process/environments.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/environments.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by RoopeshNair** [comment]
Environments is YAML only concept and it is not supported in claissic. Deployment group is option however, it is focused only on VM resource

**Comment by rolfik** [comment]
Then it would help to state it in bold on this page:
Environments are only supported in yaml pipelines
