### ISSUE TITLE
How to add Release stages to a release to target some environments?

### ISSUE THREAD

**Issue by rolfik** [MicrosoftDocs/vsts-docs#6430]
When we make a release we would like to add additional stages representing deployments to some production environments.
It suggests itself to define our production environments first in Environments and than in a Release prepare the software from a build, test, etc., and than later add multiple stages to already run Release representing ad-hoc deployments to some of the production environments defined.
How to do it please?
Thank you
Marek Ištvánek

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77d95db6-9983-7346-d0eb-4b7443e4e252
* Version Independent ID: 0a22cccc-318d-592f-d1ab-09ec01d88087
* Content: [Environment - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/environments?view=azure-devops)
* Content Source: [docs/pipelines/process/environments.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/environments.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by msebolt** [comment]
@rolfik  Thank you for the question.

Please refer to the multiple stage example in [Stages](https://docs.microsoft.com/azure/devops/pipelines/process/stages?view=azure-devops&tabs=yaml). Here you will be able to add multiple environments as per [this example](
https://docs.microsoft.com/azure/devops/pipelines/process/environments?view=azure-devops#targeting-an-environment-from-a-deployment-job).

For additional support options, see:

- [Azure DevOps Support](https://azure.microsoft.com/support/devops/)
- [Azure DevOps on StackOverflow](https://stackoverflow.com/questions/tagged/azure-devops)

**Comment by msebolt** [comment]
Closing now.  Please add comments below if there are further issues.
