### ISSUE TITLE
'Insufficient privileges to complete the operation.' when attempting operations in a subscription/tenant that is not defined in the service connection

### ISSUE THREAD

**Issue by JasperCodes** [MicrosoftDocs/vsts-docs#6432]
I'm using a AzurePowerShell@4 task with a working service connection for tenant A. Somewhere in this pipeline I want to perform operations in tenant B (for which I don't have a service connection configured).

I can succesfully use `Connect-AzAccount` to connect to tenant B with the proper credentials, but when I want to perform any operation in tenant B I get an 'Insufficient privileges to complete the operation.' error. Even when just using `Get-` cmdlets. 

Is it impossible by design to connect to other tenants/subscription (as defined in the service connection) in Azure Powershell tasks? Or am I missing something here?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fb215324-b1a0-93b5-5022-4bcc7da93bb7
* Version Independent ID: 9eb2977b-ac34-9d53-670e-04fa027bc8e4
* Content: [Azure PowerShell task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-powershell?view=azure-devops)
* Content Source: [docs/pipelines/tasks/deploy/azure-powershell.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/deploy/azure-powershell.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by niadak** [comment]
It is not recommended to connect to a different subscription other that which is specified in the service connection in azurePowerShellV4 task.
You can do one of the following:
1.	Create a new service connection for subscript B as he already has the required credential and use that in AzurePowerShell task.
2.	Use simple PowerShell task (instead of AzurePowerShell task) to connect to subscription B using Connect-AzAccount command and the credential.

**Comment by msebolt** [comment]
@JasperCodes  Thank you for the question.

@niadak Thank you for your response.

Unfortunately any resolution to this issue requires input from the product team and should be moved to [azure-pipelines](https://github.com/microsoft/azure-pipelines-tasks/issues) repo.

Please move the issue there for continued discussion.

@thomps23

**Comment by msebolt** [comment]
Closing now.  Please add comments below if there are further issues.
