### ISSUE TITLE
Out of date

### ISSUE THREAD

**Issue by rlvandaveer** [MicrosoftDocs/vsts-docs#6435]
This document is out of date. Specifically this section: https://docs.microsoft.com/en-us/azure/devops/organizations/settings/work/import-process/import-process?view=azure-devops#import-a-process

![Process Import Dialog](https://user-images.githubusercontent.com/3236183/69346933-a2aee580-0c41-11ea-8e68-91496ac93605.png)

What does not checking "Replace existing template" do, create a copy of the template? If yes, how? Does it rename the process template you are importing?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: efa97384-8347-5612-9fb9-f5d55cc338c0
* Version Independent ID: 7151c774-9b48-aac9-0f83-c4c6c8f5867f
* Content: [Import a process - Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/organizations/settings/work/import-process/import-process?view=azure-devops#import-process)
* Content Source: [docs/organizations/settings/work/import-process/import-process.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/settings/work/import-process/import-process.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by msebolt** [comment]
@rlvandaveer Thank you for the feedback, assigning this to the author for review.

**Comment by KathrynEE** [comment]
@rlvandaveer - I've contacted the product team for an answer and will respond when they get back to me.

**Comment by KathrynEE** [comment]
@rlvandaveer - Apologies for the delay in response. I'm in the process of updating the screenshots and text for the Import process article.  You check the **Replace existing template** if you are updating an existing template. The import process overwrites any template that has the same name as the one you import and requires you check this box to confirm you want it replaced. If you don't check it, then you'll get a message that you can't import a same-name process template unless you check it.
