### ISSUE TITLE
Build getting failed with Code Signing Error

### ISSUE THREAD

**Issue by vishaleclass** [MicrosoftDocs/vsts-docs#6436]
I have followed all mentioned step but my Xcode build is getting failed with below error. 

Check dependencies
Code Signing Error: No profiles for 'com.abc.xyz.dev' were found:  Xcode couldn't find any iOS App Development provisioning profiles matching 'com.abc.xyz.dev'. Automatic signing is disabled and unable to generate a profile. To enable automatic signing, pass -allowProvisioningUpdates to xcodebuild.
Code Signing Error: Code signing is required for product type 'Application' in SDK 'iOS 12.1'

** BUILD FAILED **

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: faa38c9f-e56c-0c61-916a-f18861ecc03e
* Version Independent ID: 3c91cc9e-f134-b99e-b925-5374f4f8b617
* Content: [Build, test, and deploy Xcode apps - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/ecosystems/xcode?view=azure-devops#feedback)
* Content Source: [docs/pipelines/ecosystems/xcode.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/ecosystems/xcode.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @DavidStaheli
* Microsoft Alias: **dastahel**

**Comment by msebolt** [comment]
@vishaleclass Thank you for the feedback, we're sorry you're experiencing issues.

Please see if [this post](https://developercommunity.visualstudio.com/content/problem/156393/codesigning-on-hosted-macos-preview-doesnt-find-in.html) resolves the error and note that if the issue requires specific user-case settings, you can use the [Azure DevOps community](https://developercommunity.visualstudio.com/topics/Azure+DevOps.html) for product team support.

Assigning this to the author for review.

**Comment by justhchung** [comment]
Thank you for your feedback. 
We are closing this issue and directing you to seek an answer through our support web site: [Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html).
