### ISSUE TITLE
Is it possible to use Build Completion trigger for PR Build validations?

### ISSUE THREAD

**Issue by eric-labelle** [MicrosoftDocs/vsts-docs#6439]
Hi! I am using the "Build Completion" trigger for our pipelines and was wondering how if at all possible can I achieve this also in the context of a PR using [Build Validations](https://docs.microsoft.com/en-us/azure/devops/repos/git/branch-policies?view=azure-devops#build-validation). 

From what I've experienced I only can set automatic or manual trigger.  (_Both are required_)
* Setting it to **automatic** does not respect the build completion defined on the pipeline and starts both pipeline in parallel.
* Setting it to **manual** require us to launch the pipeline each time we make a push. The "Build Succeeded" status does not reset even when we push to the branch since it's set to manual apparently which is a big problem for me as all the code could have change between both commits.

Concretely, my usecase is that I have a pipeline A, and a pipeline B. I never want to execute pipeline B unless the A was successful. Both pipelines are required to pass in order to merge a PR.

Thanks in advance for your help

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7cd986e0-608c-1d8c-6faf-ecdb12e10bc6
* Version Independent ID: d60c996e-187e-dd6b-7f3a-dd056a1603f4
* Content: [Protect your Git branches with policies - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/branch-policies?view=azure-devops#build-validation)
* Content Source: [docs/repos/git/branch-policies.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/repos/git/branch-policies.md)
* Product: **devops**
* Technology: **devops-code-git**
* GitHub Login: @apawast
* Microsoft Alias: **sdanie**

**Comment by msebolt** [comment]
@eric-labelle Thank you for the question.

Please see if [this post](https://stackoverflow.com/questions/52940355/resetting-build-policy-on-branch-update-in-vsts-azure-devops) or https://github.com/Microsoft/azure-pipelines-yaml/issues/117 addresses the issue.

Workarounds are provided in each case, though unfortunately the feature is unsupported at this time.

@apawast

**Comment by eric-labelle** [comment]
Thanks for pointing the feature request! I voted up as it would improve the situation, although let me just point out an additional distinction for my use case. I'd like this trigger to respect the build completion trigger also! So perhaps an improved version of the request or just another feature, but it would be really useful to do like we can on pipeline's trigger.
Thanks, looking forward to future releases notes!! 😉

**Comment by msebolt** [comment]
Thank you for providing feedback and feel free to reach out to [Azure DevOps community](https://developercommunity.visualstudio.com/spaces/21/index.html) any time you need help with the product.

We are always in the need of giving priority to these requests.
