### ISSUE TITLE
Stage Owner Deployment Notifications Not As Expected

### ISSUE THREAD

**Issue by ViralSymphony** [MicrosoftDocs/vsts-docs#6441]
The documentation for classic pipelines under Specifying Stages says "Stage owners are notified whenever a deployment of a release is completed to that stage"

OOB, this doesn't seem to be the case - we have defined stage owners and they only receive notifications on failed deployments that make the environment unhealthy. The page at https://docs.microsoft.com/en-us/azure/devops/notifications/oob-built-in-notifications?view=azure-devops only lists stage owner as receiving notifications if the environment is made unhealthy, not on all deployments.

If this configuration has changed, can this page be updated to reflect that?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4266f72c-c774-0046-4593-d01eb775d3c3
* Version Independent ID: f20827aa-a6c5-96a8-5969-e576ffbc2e38
* Content: [Stages in Azure Pipelines - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/stages?view=azure-devops&tabs=classic#feedback)
* Content Source: [docs/pipelines/process/stages.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/stages.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @vijayma
* Microsoft Alias: **vijayma**

**Comment by msebolt** [comment]
@ViralSymphony Thank you for the feedback, assigning this to the author for review.

**Comment by vijayma** [comment]
Working on updating the doc.

**Comment by vijayma** [comment]
Thank you for your feedback. 
The article has been updated to address the issue.
