### ISSUE TITLE
Small typo

### ISSUE THREAD

**Issue by reggaeguitar** [MicrosoftDocs/vsts-docs#6446]
"and restrict deployments into or out of an stage using"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 63234ade-28cc-02fc-a319-42e3491da601
* Version Independent ID: 7ccbfe96-d61e-8bf2-de22-61150d648abd
* Content: [Release pipelines - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/?view=azure-devops)
* Content Source: [docs/pipelines/release/index.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/release/index.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by reggaeguitar** [comment]
This too "modeled within an stage"

**Comment by reggaeguitar** [comment]
Another one "deployment status of the each commit"

**Comment by msebolt** [comment]
@reggaeguitar Thank you for the feedback.

The documentation has been updated and is pending review.
