### ISSUE TITLE
Link should be higher

### ISSUE THREAD

**Issue by reggaeguitar** [MicrosoftDocs/vsts-docs#6447]
When I first started reading this page I was confused about the terms which the link about the "difference between a release and release pipeline" helped clarify. That link should be much higher up on the page in my opinion, or even better have a glossary at the beginning explaining the terms like "deployment", "release", "release pipeline", "artifact" etc

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 63234ade-28cc-02fc-a319-42e3491da601
* Version Independent ID: 7ccbfe96-d61e-8bf2-de22-61150d648abd
* Content: [Release pipelines - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/?view=azure-devops)
* Content Source: [docs/pipelines/release/index.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/release/index.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by msebolt** [comment]
@reggaeguitar Thank you for the feedback, assigning this to the author for review.

**Comment by iamsrivatsa** [comment]
The document has been updated and I'll be closing the issue. Thank you for the feedback and feel free to open a new issue if you have any more feedback.
