### ISSUE TITLE
Small typo

### ISSUE THREAD

**Issue by reggaeguitar** [MicrosoftDocs/vsts-docs#6448]
"There may be queuing policies defined for an stage"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8f3fff1a-f727-649e-fe35-5a2a879b4c19
* Version Independent ID: 99485814-29e5-76a4-0d1d-7637ef5907d2
* Content: [Understand releases and deployments - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/releases?view=azure-devops)
* Content Source: [docs/pipelines/release/releases.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/release/releases.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by msebolt** [comment]
@reggaeguitar Thank you for the feedback.

Changes are pending review.
