### ISSUE TITLE
Incorrect screenshot?

### ISSUE THREAD

**Issue by abby-d-chr** [MicrosoftDocs/vsts-docs#6454]
The screenshot immediately under the sentence in the **Connect to your data** section > #1 > “Or, you can find a similar button in the ribbon in the Home section.” seems to be incorrect/a duplicate of what is under #2. 
Of course, feel free to close/reject this if I’m wrong. Thank you! 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ea920e3-9644-ae0c-120d-db9e899ee192
* Version Independent ID: 452bf06e-28f4-7815-72b3-16a4c2086e47
* Content: [Connect to Power BI Data Connector - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/report/powerbi/data-connector-connect?view=azure-devops#feedback)
* Content Source: [docs/report/powerbi/data-connector-connect.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/report/powerbi/data-connector-connect.md)
* Product: **devops**
* Technology: **devops-analytics**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by msebolt** [comment]
@abby-d-chr Thank you for the feedback.

The documentation has been updated and is pending review.
