### ISSUE TITLE
Link broken

### ISSUE THREAD

**Issue by asifsid** [MicrosoftDocs/vsts-docs#6457]
The device Profile link is broken: https://azure.microsoft.com/resources/samples/active-directory-dotnet-deviceprofile/?v=17.23h

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 294772ce-58a0-bb83-8927-3e69beca39df
* Version Independent ID: d9c4a4b3-3abf-d738-369e-fff8532e9dd9
* Content: [Guidance for authentication - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/integrate/get-started/authentication/authentication-guidance?view=azure-devops#feedback)
* Content Source: [docs/integrate/get-started/authentication/authentication-guidance.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/integrate/get-started/authentication/authentication-guidance.md)
* Product: **devops**
* Technology: **devops-ecosystem**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by msebolt** [comment]
@asifsid Thank you for the feedback.

The documentation has been updated and is pending review.
