### ISSUE TITLE
Permission for Author's to Trigger Build's

### ISSUE THREAD

**Issue by btl5037** [MicrosoftDocs/vsts-docs#6458]
We are looking for a permission that will allow Author's of a GitHub Pull Request to re-run their own failed jobs without having to sign-up for an account and be added to our Azure Org. We are a large open-source project and we can't expect all of our contributors to be added to our Azure Org, that would be unreasonable and unfeasible. Is there a way to configure security such that, an author of a PR can retrigger. It would be acceptable to say a user has to at least sign up for Azure DevOps with the same GitHub ID as they are attempting to re-run the job with to be allowed to run it. Or at least introduce a permission that allows the author to click re-run in the GitHub Checks UI like AZP Admins can. It should also allow Authors to comment `/azp run` and run the build. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a8c6f274-a008-fac6-7d99-13d2ce7c8dc3
* Version Independent ID: 916fef9e-d644-2114-b466-e5bda8028ee9
* Content: [Pipeline permissions and security roles - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/policies/permissions?view=azure-devops)
* Content Source: [docs/pipelines/policies/permissions.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/policies/permissions.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by msebolt** [comment]
@btl5037  Thank you for the feedback.

Unfortunately this is beyond the scope of documentation and requires additional feedback from the product team.

Please use **Suggest a feature** in the [Azure DevOps community](https://developercommunity.visualstudio.com/spaces/21/index.html) and provide a link back to this issue.

@juliakm
