### ISSUE TITLE
BUILDKIT Not supported on Windows

### ISSUE THREAD

**Issue by arcotek-ltd** [MicrosoftDocs/vsts-docs#6459]
You mention we should / can use BUILDKIT, however, as soon as I enable it in Dockerfile, I get an error:

`failed to solve with frontend dockerfile.v0: failed to read dockerfile: failed to mount...`

Research suggests that [BUILDKIT is not supported](https://github.com/moby/buildkit/issues/1258#issuecomment-553215766) on Windows containers. Although your example may use Linux, it might be helpful to highlight this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e825c07d-2168-c0aa-782a-ef6f9c7ba95e
* Version Independent ID: 5cb6926b-215a-bf89-8e63-b2e1129e41df
* Content: [Build an image - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/ecosystems/containers/build-image?view=azure-devops#buildkit)
* Content Source: [docs/pipelines/ecosystems/containers/build-image.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/ecosystems/containers/build-image.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @shashankbarsin
* Microsoft Alias: **shasb**

**Comment by msebolt** [comment]
@arcotek-ltd Thank you for the feedback.

The documentation has been updated and is pending review.
