### ISSUE TITLE
Add documentation on Download Build Artifacts task

### ISSUE THREAD

**Issue by RichRowan** [MicrosoftDocs/vsts-docs#646]
There is no documentation on the Download Build Artifacts task. There is some on this page but its out of place now. 
https://docs.microsoft.com/en-gb/vsts/build-release/concepts/definitions/build/triggers?view=vsts

There's info on the publish task under Reference>Utility Tasks but none for Download.
https://docs.microsoft.com/en-gb/vsts/build-release/tasks/utility/publish-build-artifacts?view=vsts

**Comment by vijayma** [comment]
Thanks for the feedback. We have this on our backlog.
