### ISSUE TITLE
"When a build validation policy is enabled, a new build queue when a new pull request is created"

### ISSUE THREAD

**Issue by Spaceman1861** [MicrosoftDocs/vsts-docs#6460]
Should this be:
When a build validation policy is enabled, a new build queue is created when a new pull request is created

kinda hurts my brain reading that sentence.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7cd986e0-608c-1d8c-6faf-ecdb12e10bc6
* Version Independent ID: d60c996e-187e-dd6b-7f3a-dd056a1603f4
* Content: [Protect your Git branches with policies - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/branch-policies?view=azure-devops#feedback)
* Content Source: [docs/repos/git/branch-policies.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/repos/git/branch-policies.md)
* Product: **devops**
* Technology: **devops-code-git**
* GitHub Login: @apawast
* Microsoft Alias: **sdanie**

**Comment by msebolt** [comment]
@Spaceman1861 Thank you for the feedback, sorry for the confusion.

The documentation has been changed and is pending review.

**Comment by Spaceman1861** [comment]
No worries all good
