### ISSUE TITLE
Wrong/missleading information about paid extensions pre-conditions

### ISSUE THREAD

**Issue by mattias-skold** [MicrosoftDocs/vsts-docs#6464]
This section is wrong 
"For paid extensions, you need an Azure subscription to bill your purchase. If you don't have an Azure subscription, you can create a new subscription when you make your first purchase."

#rd party paid extensions doesnt require an azure subscription, please differentiate the pre-codtions for 3rd party paid extensions

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 46849bf5-07ed-62cd-66a5-2ebabe449855
* Version Independent ID: d12ad05e-4348-f13a-ea35-7bb4761c3b0b
* Content: [Install extensions for on-premises servers - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/marketplace/get-tfs-extensions?view=azure-devops-2019#feedback)
* Content Source: [docs/marketplace/get-tfs-extensions.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/marketplace/get-tfs-extensions.md)
* Product: **devops**
* Technology: **devops-marketplace**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by msebolt** [comment]
@mattias-skold Thank you for the feedback, assigning this to the author for review.

**Comment by chcomley** [comment]
Hi @mattias-skold,

Thanks for this. I've updated the Marketplace articles to reflect that you don't need an Azure subscription for **any** extensions. These updates should go live shortly today. Thanks again for contributing to our docs!
