### ISSUE TITLE
Is this feature not released yet? (Azure AD Tenant Policy Restriction on Org Creation)

### ISSUE THREAD

**Issue by danijam** [MicrosoftDocs/vsts-docs#6466]
I'm not seeing this policy option light up as shown in this doc page. Would be handy to flag if this is not rolled out yet. I've checked all the prerequisites as described.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 53e0bc69-0f15-0f14-b1cb-414848105cbf
* Version Independent ID: 7d0fba46-e37e-e7d0-3d7d-6ba606a58962
* Content: [Restrict new organization creation, Azure Active Directory tenant policy - Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/azure-ad-tenant-policy-restrict-org-creation?view=azure-devops#prerequisites)
* Content Source: [docs/organizations/accounts/azure-ad-tenant-policy-restrict-org-creation.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/accounts/azure-ad-tenant-policy-restrict-org-creation.md)
* Product: **devops**
* Technology: **devops-accounts**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by msebolt** [comment]
@danijam  Thank you for the feedback, assigning this to the author for review.

**Comment by chcomley** [comment]
Hi @danijam, I've just received confirmation that it's completely rolled out. Do you see the policies section at all? If so, just not this policy, you may need to be put onto the allow list. Please let me know if this helps. Thanks

**Comment by danijam** [comment]
Thanks @chcomley I can confirm I now see the policies section.
