### ISSUE TITLE
Not clear from docs: Are changes to "users" tracked?

### ISSUE THREAD

**Issue by NenoLoje** [MicrosoftDocs/vsts-docs#6468]
It's not clear from the docs if changes to the user list (e.g. add/invite user, change access level, assign license) are tracked or not.

Please clarify.

Thanks,
--Neno

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 52f60b32-5c3c-f01a-cbbf-f4e9bd17a3fc
* Version Independent ID: 94753ea7-b465-f92e-10c2-8b17d995e4ff
* Content: [Access, export, filter audit logs for Azure DevOps - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/settings/azure-devops-auditing?view=azure-devops&tabs=preview-page#feedback)
* Content Source: [docs/organizations/settings/azure-devops-auditing.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/settings/azure-devops-auditing.md)
* Product: **devops**
* Technology: **devops-settings**
* GitHub Login: @roferg
* Microsoft Alias: **chcomley**

**Comment by NenoLoje** [comment]
What makes this highly confusing is that:

- In the limitations section, it mentioned two events which are **not** tracked. Implying that all other events in the system **are** tracked.
- At the same time, when looking at the 'Areas' section, many things seem to be missing.

Can we updated the page to make clear what is/isn't tracked by the audit feature?

As an example, what about changes to (classic) releases? It's not clear from this doc, if those events are tracked or not.

Thanks!

**Comment by msebolt** [comment]
@NenoLoje Thank you for the feedback, assigning this to the author for review.

**Comment by roferg** [comment]
Hey @NenoLoje - I'm making some updates to make this more clear. In the meantime you can see all auditing events by going to https://auditservice.dev.azure.com/{YOUR ORGANIZATION}/_apis/audit/actions. Simply replace {YOUR ORGANIZATION} with your organiztion's name.

**Comment by NenoLoje** [comment]
Hey @roferg - awesome, that's super helpful. Thanks for sharing that tip!

![grafik](https://user-images.githubusercontent.com/13981145/69657816-50bff280-107b-11ea-8f9e-709b6d19743c.png)

**Comment by KathrynEE** [comment]
Closing this issue as the article has been updated with the requested info.
