### ISSUE TITLE
There are some validation rules that should be made clear

### ISSUE THREAD

**Issue by crmckenzie** [MicrosoftDocs/vsts-docs#6469]
Namely, that the `State` and `Effort` fields cannot be included on new records. As currently implemented, if you are importing workitems from another system you must first import the workitems as `New` and without effort attached. You'll then need to export the workitems to get the ID's, and ReImport the items with the updated `State` and `Effort`.

It would be nice if the import would accept these fields and fast-forward the workitems into the appropriate state, but since it currently doesn't these sorts of validation requirements should be made clear here. It took me quite some time to figure this out.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4296d1cc-f211-9d17-d97f-2b0858fdea7d
* Version Independent ID: cc66dfee-adde-cdfb-b3f5-5d58d89d3c81
* Content: [Import work items from a csv file through the web - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/queries/import-work-items-from-csv?view=azure-devops#feedback)
* Content Source: [docs/boards/queries/import-work-items-from-csv.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/boards/queries/import-work-items-from-csv.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@crmckenzie - Thank you for the feedback. I will update the topic to reflect the limitation that all work items imported start with the New state.

**Comment by Skupa** [comment]
@KarthrynEE  it would be good that it is made clear that custom created field are alsno not applicable for updating when making new work items
