### ISSUE TITLE
Possible to export/transfer/output an inherited process from one VSTS account to another VSTS acount?

### ISSUE THREAD

**Issue by FredConklin** [MicrosoftDocs/vsts-docs#647]
Is it possible to export/transfer/output an inherited process from one VSTS account and import it to another VSTS account?  We have been working on a Dev VSTS account and would like to use the inherited process in another VSTS account. Is there a way to do that?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 59b49815-8f3f-e1d2-4d09-f3b93d12f8dd
* Version Independent ID: 16502aff-79be-068f-f13f-71fb021af7b1
* Content: [Inheritance process model - VSTS](https://docs.microsoft.com/en-us/vsts/work/customize/inheritance-process-model?view=vsts)
* Content Source: [docs/work/customize/inheritance-process-model.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/work/customize/inheritance-process-model.md)
* Service: **unspecified**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@FredConklin - Hi Fred, thank you for your inquiry. There is no UI available to support the scenario you outlined at this time. However, there is a standalone tool being developed to support this which will be available soon. I will update you via your GitHub user ID when it becomes available. Regards.

**Comment by shailensukul** [comment]
@KathrynEE Can you also please post the link to the tool here as well? This is a common use case and a cause for frustration with my client who need to migrate inherited process templates across VSTS subscriptions.

**Comment by norschel** [comment]
@lvsezhufu It's been ages since you asked, but others certainly have the same problem and end up here. The tool is now available at https://github.com/microsoft/process-migrator .
