### ISSUE TITLE
mocha-multi-reporters last commit was on Dec 1 2017

### ISSUE THREAD

**Issue by hemodrow** [MicrosoftDocs/vsts-docs#6476]
mocha-multi-reporters dependecies are outdated (ex: uses mocha 3.1.2).

[cypress-multi-reporters](https://github.com/YOU54F/cypress-multi-reporters) is a fork thats being maintened.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 86b2fdca-9125-9720-3d03-3c6dd336f100
* Version Independent ID: b2a24e28-9858-fe1c-4527-745f1f387e4e
* Content: [Build and deploy JavaScript and Node.js apps - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/ecosystems/javascript?view=azure-devops#feedback)
* Content Source: [docs/pipelines/ecosystems/javascript.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/ecosystems/javascript.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by juliakm** [comment]
Thanks @hemodrow! We'll fix that shortly.
