### ISSUE TITLE
Visual Studio Test v 2.* fails if no test sources found (used to work a few days ago with just a warning)

### ISSUE THREAD

**Issue by gonzaloluna** [MicrosoftDocs/vsts-docs#6477]
I have a generic task group for some of my projects in which some of them have tests and others don't.
Now every time I try to build a project with no tests asseblies the build task fails. 
Previously the task would give me a warning, which was OK for me. 
Is this something you've just changed in the latest version? can you put it back? or just add an option to not fail the task?

##[debug]Agent.Version=2.155.1
##[debug]Release.ReleaseUri=undefined
##[debug]Release.ReleaseId=undefined
##[debug]Build.BuildUri=vstfs:///Build/Build/2383
##[debug]Build.Buildid=2383
##[debug]telemetry area: TestExecution feature: TestExecutionTask data: {"builduri":"vstfs:///Build/Build/2383","buildid":"2383","state":"completed"}
##[debug]Processed: ##vso[telemetry.publish area=TestExecution;feature=TestExecutionTask;]{"builduri":"vstfs:///Build/Build/2383","buildid":"2383","state":"completed"}
##[error]Error: Preparing the test sources file failed. Error : Error: No test sources found matching the given filter '**\*test*.dll,!**\*TestAdapter.dll,!**\obj\**'
##[debug]Processed: ##vso[task.issue type=error;]Error: Preparing the test sources file failed. Error : Error: No test sources found matching the given filter '**\*test*.dll,!**\*TestAdapter.dll,!**\obj\**'
##[debug]task result: Failed
##[error]VsTest task failed.
##[debug]Processed: ##vso[task.issue type=error;]VsTest task failed.
##[debug]Processed: ##vso[task.complete result=Failed;done=true;]VsTest task failed.
Finishing: VsTest - testAssemblies

**Comment by msebolt** [comment]
@gonzaloluna Thank you for the feedback.

Since this is more geared towards the product team, please move the issue to the [azure-pipelines-tasks](https://github.com/microsoft/azure-pipelines-tasks/issues) repo.

**Comment by msebolt** [comment]
Closing the issue, please comment below if there any questions.
