### ISSUE TITLE
.NET Core

### ISSUE THREAD

**Issue by jhaygood86** [MicrosoftDocs/vsts-docs#6478]
Are there any plans to make this work with .NET Core tests?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66e098a7-83b4-c389-3d30-21ad3446b76c
* Version Independent ID: cafbcbd5-3321-88cf-eeaf-038d49ec0ada
* Content: [Use Test Impact Analysis - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/test/test-impact-analysis?view=azure-devops#feedback)
* Content Source: [docs/pipelines/test/test-impact-analysis.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/test/test-impact-analysis.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @PBoraMSFT
* Microsoft Alias: **pbora**

**Comment by msebolt** [comment]
@jhaygood86 Thank you for the question.

Please move this issue to the [azure-pipelines-tasks](https://github.com/microsoft/azure-pipelines-tasks/issues) repo for product team feedback.

@PBoraMSFT

**Comment by msebolt** [comment]
Closing the issue, please comment below if there any questions.
