### ISSUE TITLE
Wrong reference name for Remote Related link type

### ISSUE THREAD

**Issue by ibmeister** [MicrosoftDocs/vsts-docs#6481]
The reference name for Remote Related should be "System.LinkTypes.Remote.Related" instead of "System.LinkTypes.RemoteRelated". System.LinkTypes.RemoteRelated does not work so I had to guess multiple variations until I got "System.LinkTypes.RemoteRelated" to work

**Comment by WilliamAntonRohm** [comment]
@ibmeister -- Ibrahim, thanks for your feedback; we appreciate it. Please let us know which topic you’re referencing and we will update the documentation.

**Comment by ibmeister** [comment]
@WilliamAntonRohm This topic https://docs.microsoft.com/en-us/azure/devops/boards/queries/link-type-reference?view=azure-devops

**Comment by WilliamAntonRohm** [comment]
@ibmeister -- Ibrahim, thank you for the clarification.  I am looking into this document.

**Comment by WilliamAntonRohm** [comment]
@KathrynEE -- please review the above-mentioned PR 602.
