### ISSUE TITLE
Description of inputs for AzureRmWebAppDeployment

### ISSUE THREAD

**Issue by timothies** [MicrosoftDocs/vsts-docs#6484]
Hi, apologies if this is a dumb question but I can't find any description of what inputs are available for
- task: AzureRmWebAppDeployment@4
Are there any references you could point me at?
Thanks for your help

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a40a853-83d6-844a-4752-8b00909c9ffb
* Version Independent ID: e3121964-de38-2a57-2414-c1e29a880477
* Content: [Deploy an Azure Web App - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/targets/webapp?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/targets/webapp.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/targets/webapp.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by iamsrivatsa** [comment]
Hi @timothies , you can find it [here](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-rm-web-app-deployment?view=azure-devops).

**Comment by timothies** [comment]
Thanks @iamsrivatsa.  That page looks like its missing some of the inputs for AzureRmWebAppDeployment@4 (e.g. packageForLinux) but I'll raise the issue on that page.

Really appreciate your help!

**Comment by iamsrivatsa** [comment]
Hi @timothies, the inputs are not missed in the document. The  **packageForLinux** is the alias used for **Package** same is already documented in the Arguments table.

**Comment by msebolt** [comment]
@timothies Thank you for the feedback.

Please refer to the [source documentation](https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/AzureRmWebAppDeploymentV4) and if anything is missing from the [doc](https://docs.microsoft.com/azure/devops/pipelines/tasks/deploy/azure-rm-web-app-deployment) referenced by @iamsrivatsa please comment below.

**Comment by timothies** [comment]
Thanks guys,  perhaps I'm wrong and all the inputs are listed but the alias packageForLinux is definitely missing though.
![packageForLinux](https://user-images.githubusercontent.com/4046886/70022006-c92c3380-15e6-11ea-8b52-6b7bc4e74c37.PNG)

**Comment by iamsrivatsa** [comment]
The changes are pushed. You can now see the updated document.

**Comment by timothies** [comment]
Thanks guys, appreciate your help
