### ISSUE TITLE
MacOS agent data location link is dead

### ISSUE THREAD

**Issue by ghelyar** [MicrosoftDocs/vsts-docs#6487]
> Notes on choosing "Hosted macOS"
> This option affects where your data is stored. Learn more.

Currently links to https://www.microsoft.com/TrustCenter/CloudServices/vsts/data-location

I'm guessing this should be https://docs.microsoft.com/en-us/azure/devops/organizations/security/data-location?view=azure-devops but not sure.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 99af681d-41ad-da15-0b72-08b5cd5a11ac
* Version Independent ID: 2fa0df36-a437-8cbb-b019-b49b31b1e116
* Content: [Microsoft-hosted agents for Azure Pipelines - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops)
* Content Source: [docs/pipelines/agents/hosted.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/agents/hosted.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by damccorm** [comment]
Hi, thanks for the feedback - I'm taking a look!

**Comment by damccorm** [comment]
Thank you for your feedback. 
The article reference is being updated to reference the link you mentioned.
