### ISSUE TITLE
WIQL syntax page missing description of tree and direct links querys

### ISSUE THREAD

**Issue by NenoLoje** [MicrosoftDocs/vsts-docs#6492]
While this page is doing a great job of explaining verious WIQL syntax elements, it's misingg the hierarchical queries, specifically tree queries and dircet links queries.

Let's add them to the docs! :)

Thanks!
--Neno

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 710af5f2-8a31-e0d3-4f20-00c79dc54713
* Version Independent ID: 1d4d9580-984c-9fee-861a-a02ce828d3db
* Content: [WIQL reference syntax - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/queries/wiql-syntax?view=azure-devops#feedback)
* Content Source: [docs/boards/queries/wiql-syntax.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/boards/queries/wiql-syntax.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by NenoLoje** [comment]
Maybe this might help: https://blogs.msdn.microsoft.com/team_foundation/2010/07/02/wiql-syntax-for-link-query/

**Comment by KathrynEE** [comment]
Thanks @NenoLoje - I've added a user story to my backlog to update the article with link queries.
