### ISSUE TITLE
Confusing steps for Confirm User has permission

### ISSUE THREAD

**Issue by Zhaph** [MicrosoftDocs/vsts-docs#6493]
Under [Confirm User has Permission](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/v2-windows?view=azure-devops#confirm-the-user-has-permission) step 2 directs you to the "Roles" tab of the Agent Pool settings, however this should be the "Security" tab, where you can then potentially see users and roles.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43799c5d-2f13-cc76-a1c0-a3f850e16d4e
* Version Independent ID: 97a5b73f-faf7-f9c0-9269-fc79984616d6
* Content: [Deploy a Azure Pipelines agent on Windows - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/v2-windows?view=azure-devops#confirm-the-user-has-permission)
* Content Source: [docs/pipelines/agents/v2-windows.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/agents/v2-windows.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by WilliamAntonRohm** [comment]
@steved0x -- please review this change in the above-mentioned PR 615.

**Comment by steved0x** [comment]
I'm updating this one.
