### ISSUE TITLE
Remove this page from TOC for Azure DevOps Services

### ISSUE THREAD

**Issue by NenoLoje** [MicrosoftDocs/vsts-docs#6496]
Maybe we can remove this page (and the other page on the same level) from the TOC, when Version = Azure DevOps Services, as they are not relevant?

Thanks,
--Neno

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f010168c-5717-ff43-3287-030f55c6b7e2
* Version Independent ID: c3039d68-269b-214e-b3de-6a0e70aaa522
* Content: [Configure process guidance - TFS](https://docs.microsoft.com/en-us/azure/devops/report/sharepoint-dashboards/configure-or-redirect-process-guidance?view=azure-devops#feedback)
* Content Source: [docs/report/sharepoint-dashboards/configure-or-redirect-process-guidance.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/report/sharepoint-dashboards/configure-or-redirect-process-guidance.md)
* Product: **devops**
* Technology: **devops-analytics**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by NenoLoje** [comment]
Link to the other page: https://docs.microsoft.com/en-us/azure/devops/report/sharepoint-dashboards/configure-or-add-a-project-portal?view=azure-devops

**Comment by KathrynEE** [comment]
@NenoLoje - The ability to designate a URL for the project portal or process guidance is supported for Azure DevOps Services. So leaving this as is for the time being.
