### ISSUE TITLE
Invalid link: supported web browser

### ISSUE THREAD

**Issue by NenoLoje** [MicrosoftDocs/vsts-docs#6499]
The link to "supported web browser" ends up with a 404 error.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 12a3813d-668f-f3f0-2a10-97eef5cda914
* Version Independent ID: 79f91447-90e1-716c-8ae0-ba4b09d356bb
* Content: [Organization and project scope queries - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/report/extend-analytics/account-scoped-queries?view=azure-devops#feedback)
* Content Source: [docs/report/extend-analytics/account-scoped-queries.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/report/extend-analytics/account-scoped-queries.md)
* Product: **devops**
* Technology: **devops-analytics**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@NenoLoje - Thank you for the feedback. Correcting the links today.
