### ISSUE TITLE
UI mismatch in project settings

### ISSUE THREAD

**Issue by zhongyi-zhang** [MicrosoftDocs/vsts-docs#6504]
Regarding to https://docs.microsoft.com/en-us/azure/devops/pipelines/test/flaky-test-management?view=azure-devops#enable-flaky-test-management, I can't find the section "test management" in my project settings, what is mentioned in the doc.
![image](https://user-images.githubusercontent.com/13326941/69798272-015cfc00-120c-11ea-9f6b-180f3d813f5c.png)

Any idea why? Thanks!

**Comment by KathrynEE** [comment]
@zhongyi-zhang - Thank you for your inquiry, and apologies for any confusion. The Test management settings is available for the cloud service only at this time. It was released on July 22 with the Sprint 155 release. 

From the UI screenshot you show above, it would appear you are on an on-premises version.  If this is not the case, please contact [product support](https://developercommunity.visualstudio.com/spaces/21/index.html) about your issue. 

According to the [Feature timeline](https://docs.microsoft.com/en-us/azure/devops/release-notes/features-timeline), the Flaky Test Management settings will ship with Azure DevOps Server 2020.
