### ISSUE TITLE
An error in bash script

### ISSUE THREAD

**Issue by yelenapakumirzakova** [MicrosoftDocs/vsts-docs#6509]
Hello Dear All,
 there is an error in bash script https://docs.microsoft.com/en-us/azure/devops/repos/git/set-up-credential-managers?view=azure-devops

Instead 

git-credential-manager install

supposed to be

git credential-manager install

without "-" between git and credential.

King regards,
Yelena.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c2f260d-9321-d669-172d-01289c233263
* Version Independent ID: 14e9ae18-df9d-7555-902c-3e8b4c2b2f22
* Content: [Connect to your Git repos using credential managers - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/set-up-credential-managers?view=azure-devops)
* Content Source: [docs/repos/git/set-up-credential-managers.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/repos/git/set-up-credential-managers.md)
* Product: **devops**
* Technology: **devops-code-git**
* GitHub Login: @apawast
* Microsoft Alias: **sdanie**

**Comment by WilliamAntonRohm** [comment]
@yelenapakumirzakova -- Yelena, thank you for bringing this to my attention.  It has been fixed in the documentation and should be live by tomorrow.
