### ISSUE TITLE
写的像屎一样的文档

### ISSUE THREAD

**Issue by chaozhangpower** [MicrosoftDocs/vsts-docs#6514]
Thank you for your feedback!

The issues in this repo are for documentation feedback.

If you are submitting your documentation feedback issue directly through GitHub, please provide the URL of the article so we can route the feedback to the correct author.

Please report Azure DevOps or TFS software bugs, feedback, or questions in the [Azure DevOps Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html).

**Comment by msebolt** [comment]
@chaozhangpower Thank you for the feedback.

If there are any issues or concerns, please comment below.
