### ISSUE TITLE
java

### ISSUE THREAD

**Issue by SamirNabadov** [MicrosoftDocs/vsts-docs#6517]
test

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f94a6e7d-3cb5-790c-2b8b-c09abd1de3f6
* Version Independent ID: a0d381e1-07ad-9191-4697-6faf600a7bd8
* Content: [Use Azure Pipelines - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/get-started/pipelines-get-started?view=azure-devops&tabs=classic#feedback)
* Content Source: [docs/pipelines/get-started/pipelines-get-started.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/get-started/pipelines-get-started.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by WilliamAntonRohm** [comment]
@SamirNabadov  Thanks for your feedback; we appreciate it. To make sure we have all the information needed to triage your issue, please provide more context around the general task.
