### ISSUE TITLE
ubuntu-latest points to 16.04, not 18.04

### ISSUE THREAD

**Issue by estensen** [MicrosoftDocs/vsts-docs#6518]
Running `print(platform.platform())` with Python I detected that the kernel versions of the host agents on `ubuntu-latest` and `ubuntu-18.04` differ, even though they point to the same image in the docs.

~~According to a [list of kernel](https://askubuntu.com/questions/517136/list-of-ubuntu-versions-with-corresponding-linux-kernel-version?noredirect=1&lq=1) version they map to different Ubuntu versions~~

~~`ubuntu-latest` -&gt; Linux-4.15.0-1061-azure-x86_64-with-glibc2.2.5 -> ubuntu 18.04
`ubuntu-18.04` -&gt; Linux-5.0.0-1023-azure-x86_64-with-glibc2.2.5 -> ubuntu 19.04~~

Edit: I'm wrong about kernel versions mapping to OS versions. The problem is that latest map to 16.04

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 99af681d-41ad-da15-0b72-08b5cd5a11ac
* Version Independent ID: 2fa0df36-a437-8cbb-b019-b49b31b1e116
* Content: [Microsoft-hosted agents for Azure Pipelines - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops)
* Content Source: [docs/pipelines/agents/hosted.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/agents/hosted.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by damccorm** [comment]
Thank you for your feedback - I'm taking a look!

**Comment by damccorm** [comment]
It turns out `ubuntu-latest` actually points to `ubuntu-16.04`, `ubuntu-16.04` and `ubuntu-18.04` both seem right though. We had to roll `latest` back to point to `16.04` due to capacity issues which have since been fixed. We're tracking a work item to make `latest` point to `18.04` again, that should go out after the holidays.

I'm going to close here since we're tracking the work to fix this on our end.

**Comment by estensen** [comment]
Closing this issue makes it harder for other folks to see that this is an issue.

**Comment by damccorm** [comment]
That's fair, we can reopen until this is fixed.

**Comment by JodyAndrews** [comment]
From what we can tell this is yet to be fixed, using ubuntu-latest we occasionally get 16.04, and other times 18.04. Explicitly specifying ubuntu-18.04 fails to spin up the pipeline. 

What's the current status on this, and is it possible to track?

**Comment by JodyAndrews** [comment]
Bump, still ongoing.

**Comment by edjwhho** [comment]
is this still a problem? im currently using ubuntu-latest in the pipeline

**Comment by Chris113113** [comment]
Still seeing this.

**Comment by vtbassmatt** [comment]
@alepauly @mitesch @densto88 customers are seeing `ubuntu-latest` route to 16.04 sometimes, as recently as April 7. Can you guys please investigate what's happening?

At this point we're dealing with a service bug, not a docs issue. If anyone feels like opening an issue on [Developer Community](https://developercommunity.visualstudio.com/search.html?f=&type=question+OR+problem+OR+idea&type=question+OR+problem+OR+idea&c=&redirect=search%2Fsearch&sort=relevance&q=ubuntu-latest) then feel free, but we will also run this down internally.

**Comment by vtbassmatt** [comment]
@Chris113113 we looked at service-side telemetry and cannot find any evidence of an `ubuntu-latest` build running against the Ubuntu16 pool. To dig further, please post a Developer Community ticket with your organization name, project name, and pipeline name. A pointer to a run where it occurred would also help. Thanks!
