### ISSUE TITLE
Documentation is wrong for Type: File/Inline

### ISSUE THREAD

**Issue by patchandthat** [MicrosoftDocs/vsts-docs#6519]
The actual parameter is 'targetType' not 'type'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a0e444c2-69c6-4d71-6fd0-94d0f4097d3a
* Version Independent ID: 3a727833-1cc3-c2fb-c5b3-22605eee2721
* Content: [PowerShell task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/powershell?view=azure-devops#feedback)
* Content Source: [docs/pipelines/tasks/utility/powershell.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/utility/powershell.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @vtbassmatt
* Microsoft Alias: **macoope**

**Comment by srivatsamarichi** [comment]
The documentation has been updated and I'll be closing the issue. Thank you for the feedback and feel free to open a new issue if you have any more feedback.

**Comment by WilliamAntonRohm** [comment]
@patchandthat -- Patrick, thank you for your feedback.

@srivatsamarichi -- Srivatsa, thank you for the follow-up.
