### ISSUE TITLE
Correct wrong word used

### ISSUE THREAD

**Issue by mayeager22** [MicrosoftDocs/vsts-docs#652]
In the sentence that starts "The scenario is anonymous to doing a...", I think you mean to say it is synonymous, not anonymous.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7268225d-815b-0faf-4dcf-e659272b48b9
* Version Independent ID: 19315f8f-685f-6aad-0fc2-467474f508d0
* Content: [Version Control - Map TFS version control (TFVC) actions to Git](https://docs.microsoft.com/en-us/vsts/git/concepts/mapping-my-tfvc-actions-to-git?view=vsts&tabs=visual-studio)
* Content Source: [docs/git/concepts/mapping-my-tfvc-actions-to-git.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/git/concepts/mapping-my-tfvc-actions-to-git.md)
* Service: **unspecified**
* GitHub Login: @wpschaub
* Microsoft Alias: **willys**

**Comment by steved0x** [comment]
@mayeager22 Agreed, fixed in https://github.com/MicrosoftDocs/vsts-docs/pull/654 Thanks for letting us know!
