### ISSUE TITLE
Ability to disable agent from the self-hosted agent itself

### ISSUE THREAD

**Issue by pawelros** [MicrosoftDocs/vsts-docs#6520]
I think that there should be a way to tell Azure DevOps from the agent (to be more specific, from the machine on which self-hosted agent is installed) - "I do not want to accept any more jobs".
Right now I do not see an easy solution for that, `svc.sh` script allows only to install, start, stop, display status and uninstall. 

Use case: I have an autoscaling group of virtual machines. When I scale up, a new VM is created and during its initialization `Self-hosted Linux agent` is installed on it, configured and started. The agent connects to my pool and everything is fine. Except when I scale down, running builds can be terminated which is not acceptable for me. Before scaling down my agents, I would like to disable them, wait some time and then safely terminate vms. The only way to achieve this now is to use `Azure DevOps Services REST API` but that requires at least 3 request->response->parse trips to do it in a nice way, without hardcoding any ids (GET pool with a name 'P', take its id -> GET agent 'A' from pool id 'Pid', take its id -> PATCH agent id 'Aid', disable it). It does not make much sense to me as on the vm where agent is running you already have established, authenticated connection with Azure DevOps, so sending there `disable` command sounds like an easy thing to implement.

Cloud providers in autoscaling groups allow executing lifecycle hooks, wait a certain amount of time and then terminate vm, with `./svc disable` in place that would be a great time saver.

**Comment by WilliamAntonRohm** [comment]
Thanks for the suggestion! The product teams aren’t always watching this repository, so to make sure it gets in front of them for triage, please [submit your idea]( https://developercommunity.visualstudio.com/content/idea/post.html?space=21) here.
