### ISSUE TITLE
Powershell Versions

### ISSUE THREAD

**Issue by willowJohn** [MicrosoftDocs/vsts-docs#6535]
Can you add the list of supported powershell versions for this task. It is so annoying trying to pick a static version. Rather than a free text field it would be better as a dropdown. 

Failing that update this page should have the known powershell versions listed. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a0e444c2-69c6-4d71-6fd0-94d0f4097d3a
* Version Independent ID: 3a727833-1cc3-c2fb-c5b3-22605eee2721
* Content: [PowerShell task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/powershell?view=azure-devops)
* Content Source: [docs/pipelines/tasks/utility/powershell.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/utility/powershell.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @vtbassmatt
* Microsoft Alias: **macoope**

**Comment by damccorm** [comment]
Hey @willowJohn - we don't install PowerShell, we just use whatever version of PowerShell you have on your path - I'm a little confused about what text field you're mentioning, would you mind clarifying?

**Comment by vtbassmatt** [comment]
The PowerShell task doesn't take a PowerShell version as input. Perhaps this is related to a Marketplace task or something?
