### ISSUE TITLE
Duplicate task document

### ISSUE THREAD

**Issue by mszixie** [MicrosoftDocs/vsts-docs#6537]
Hi team, this task document seems to be duplicate with this page: https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/azure-policy?view=azure-devops

These two should be the same task. Its current name is: Check Policy Compliance

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e340f7db-11b6-52c6-ac60-8c0be87aadd9
* Version Independent ID: be79dfc8-9686-268d-fa3d-31db541da0a3
* Content: [Azure Policy Check Gate task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-policy-check-gate?view=azure-devops#feedback)
* Content Source: [docs/pipelines/tasks/deploy/azure-policy-check-gate.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/deploy/azure-policy-check-gate.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by srivatsamarichi** [comment]
@mszixie Thank you for the feedback. Have fixed the duplicates. The changes will be reflected AEAP.
