### ISSUE TITLE
What does cancelTimeoutInMinutes really do?

### ISSUE THREAD

**Issue by jwikman** [MicrosoftDocs/vsts-docs#6544]
The same is reported in https://github.com/MicrosoftDocs/vsts-docs/issues/3160, but that points to an non-existing page, so I add it here as well.

What does this really means:
`The cancelTimeoutInMinutes allows a limit to be set for the job cancel time. When not specified, the default is 5 minutes.`

What is a "job cancel time"?

Maybe add something about "how much time to give 'run always even if cancelled tasks' before killing them" or similar?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 67504b34-d64b-02a4-2e10-ab99f3b8cfe4
* Version Independent ID: 2cf63b2e-184b-7726-3b8a-d8baffd6fcce
* Content: [Jobs in Azure Pipelines and TFS - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/phases?view=azure-devops&tabs=yaml#timeouts)
* Content Source: [docs/pipelines/process/phases.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/phases.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by juliakm** [comment]
@jwikman I'm updating the docs now. `cancelTimeoutInMinutes` relates to the setting for a deployment task to run the task even if the previous task failed. This sets how long those attempts will continue. Here's what that option looks like on a task in the UI. 

<img width="476" alt="Screen Shot 2019-12-05 at 1 45 08 PM" src="https://user-images.githubusercontent.com/64906/70264632-d5d79580-1766-11ea-9c17-d144f3bf8b03.png">
