### ISSUE TITLE
Update documentation for YAML Build Completion Trigger

### ISSUE THREAD

**Issue by delarooster** [MicrosoftDocs/vsts-docs#6553]
I searched and searched and finally had the assistance of a gracious SO response to direct me where to navigate to find the classic editor after creating a YAML pipeline.  Might I recommend we update the documentation to more clearly direct a user to the location of these Triggers vs the ambiguous answer currently given? https://stackoverflow.com/questions/59176925/how-to-create-a-build-completion-trigger-after-creating-yaml

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5673ec1-c7d1-e0ac-043a-8fc3d5b226a9
* Version Independent ID: b4872831-51c0-6cf8-1c56-de20beb38a80
* Content: [Build pipeline triggers - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/triggers?view=azure-devops&tabs=yaml#feedback)
* Content Source: [docs/pipelines/build/triggers.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/build/triggers.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by vijayma** [comment]
Working on this.

**Comment by vijayma** [comment]
Thank you for your feedback. 
The article is being updated to address the issue.
