### ISSUE TITLE
Update instructions to account for "hidden scope groups"

### ISSUE THREAD

**Issue by eponerine** [MicrosoftDocs/vsts-docs#6555]
In PAT section 4, it says to set scope for: 
- Agent Pools (read, manage)
- Deployment group (read, manage)

However, those do not appear by default and you have to find the tiny little text at the bottom of the blade that says "show more". Would be helpful to indicate that in the docs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 344fb6c7-8770-a366-ed19-0626966be202
* Version Independent ID: 22ac2ad8-186a-3530-9a0e-fdbc860eb470
* Content: [Prepare permissions - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/prepare-permissions?view=azure-devops#feedback)
* Content Source: [docs/pipelines/agents/prepare-permissions.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/agents/prepare-permissions.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
I'll get this updated, thanks for letting us know.
