### ISSUE TITLE
unable to copy commits history

### ISSUE THREAD

**Issue by suszig** [MicrosoftDocs/vsts-docs#6556]
unable to copy commits history

in previous version it was possible to copy commits history as table
currently i'm unable to copy

is there any other reporting tool that allows to export developers commit history in last month? i need this for reporting

**Comment by WilliamAntonRohm** [comment]
@suszig -- Thanks for your feedback; we appreciate it. To make sure we have all the information needed to triage your issue, please let us know which topic you’re referencing, or provide more context around the general task.
