### ISSUE TITLE
Please add more detail around the "always" tag for scheudled triggers. 

### ISSUE THREAD

**Issue by adunnells** [MicrosoftDocs/vsts-docs#6557]
I see now that there is a brief message about the always tag for scheduled triggers. This was not informative enough for me to know that it is required to run the pipeline more than once on the schedule. Can you please add a paragraph or two that explains in detail what this tag controls and that it is important for actually running pipelines on a schedule and not just a single execution.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5673ec1-c7d1-e0ac-043a-8fc3d5b226a9
* Version Independent ID: b4872831-51c0-6cf8-1c56-de20beb38a80
* Content: [Build pipeline triggers - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/triggers?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/build/triggers.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/build/triggers.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by vijayma** [comment]
Working on this.

**Comment by vijayma** [comment]
Thank you for your feedback. 
The article is being updated to address the issue.
