### ISSUE TITLE
Links are dead

### ISSUE THREAD

**Issue by rohrerb** [MicrosoftDocs/vsts-docs#6561]
The two links under https://docs.microsoft.com/en-us/azure/devops/server/admin/add-administrator-tfs are dead.

- https://docs.microsoft.com/en-us/azure/devops/server/admin/add-administrator-tfs
- https://docs.microsoft.com/en-us/azure/devops/server/admin/service-accounts-dependencies-tfs

**Comment by KathrynEE** [comment]
@rohrerb - Thank you for this feedback. I'm updating several files that had the old file names. You can find these topics here: 

- https://docs.microsoft.com/en-us/azure/devops/server/admin/add-administrator
- https://docs.microsoft.com/en-us/azure/devops/server/admin/service-accounts-dependencies
