### ISSUE TITLE
What about a yaml build file example

### ISSUE THREAD

**Issue by chillbilly79** [MicrosoftDocs/vsts-docs#6562]
I came to this page looking for example of how to do a variable substitution in appsettings.json from my yaml build file.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 315ff823-9992-9f9b-62a1-42ce622ed41c
* Version Independent ID: 72ec3ffc-1dc9-b2dc-e3d4-4f14deae3720
* Content: [File transforms and variable substitution - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/transforms-variable-substitution?view=azure-devops#feedback)
* Content Source: [docs/pipelines/tasks/transforms-variable-substitution.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/transforms-variable-substitution.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by msebolt** [comment]
@chillbilly79 Thank you for the feedback, assigning this to the author for review.

**Comment by dschlitt** [comment]
I'm also here for the same.

**Comment by iamsrivatsa** [comment]
The document has been updated and I'll be closing the issue. Thank you for the feedback and feel free to open a new issue if you have any more feedback.
