### ISSUE TITLE
DryRun versus ProductionRun

### ISSUE THREAD

**Issue by eponerine** [MicrosoftDocs/vsts-docs#6564]
Other than in the screenshot, the value of "ProductionRun" does not appear anywhere in this document. This is painful while doing any text search or search engine searching. Can an area be added describing "DryRun" versus "ProductionRun"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4fa0ebd3-8437-8508-5a8d-462186fcce80
* Version Independent ID: efe892fe-387e-0a61-fe7d-33d2ac99dfa9
* Content: [Migrate from Azure DevOps Server to Azure DevOps - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/migrate/migration-import?view=azure-devops)
* Content Source: [docs/migrate/migration-import.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/migrate/migration-import.md)
* Product: **devops**
* Technology: **devops-migrate**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by msebolt** [comment]
@eponerine Thank you for the feedback, assigning this to the author for review.

**Comment by KathrynEE** [comment]
@eponerine - Thank you for your request. I'm updating the article to clarify. The current section, [Determine the type of import](https://docs.microsoft.com/en-us/azure/devops/migrate/migration-import?view=azure-devops#determine-the-type-of-import), does describe the differences between Dry run and Production run - but could be clearer in equating them to the parameters, DryRun and ProductionRun.
