### ISSUE TITLE
VS 2019 16.4 and .NET Core 3.1 hosted agent availability

### ISSUE THREAD

**Issue by usysware** [MicrosoftDocs/vsts-docs#6565]
Hi there,

Just wanted to see if someone could share ETA for VS 2019 16.4 and .NET Core 3.1 hosted agent availability please.

Thanks in advance.

**Comment by msebolt** [comment]
@usysware Thank you for the question.

This issue would be better geared for the [azure-pipelines-image-generation](https://github.com/microsoft/azure-pipelines-image-generation) team.

Please move this issue [here](https://github.com/microsoft/azure-pipelines-image-generation) and link back here.

**Comment by usysware** [comment]
Sorry about that. I don't think I can move it myself so I'd appreciate if you guys do that for me. Thanks.

**Comment by msebolt** [comment]
@usysware  Sounds good, the issue has been moved.

Please refer to https://github.com/microsoft/azure-pipelines-image-generation/issues/1438.
