### ISSUE TITLE
No way to change "h" to "d" when tracking in days instead of hours

### ISSUE THREAD

**Issue by Pajohns343** [MicrosoftDocs/vsts-docs#6566]
Even though users can track capacity in days, in the Work Details pane, there is no way to reflect "days" with a d. It only shows h for hours. (e.g. if I put in .5 for capacity, it will show "x of 5 h" for a two-week sprint, rather than "x of 5 d")

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de93c4e5-f491-af61-6df5-e7253d727dc9
* Version Independent ID: 417246fa-90ed-38a0-cc68-1de7895e96ce
* Content: [Set sprint capacity - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/sprints/set-capacity?view=azure-devops#feedback)
* Content Source: [docs/boards/sprints/set-capacity.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/boards/sprints/set-capacity.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by msebolt** [comment]
@Pajohns343 Thank you for the feedback.

This is possibly the same issue as reported [here](https://developercommunity.visualstudio.com/content/problem/516700/work-details-pane-is-in-hours.html).

Please start an issue with the [Azure DevOps community](https://developercommunity.visualstudio.com/spaces/21/index.html) and link back here.  You can also reference or post to the above issue for more priority when the product team responds.

**Comment by Pajohns343** [comment]
I do believe this is the same problem.  However, it shows as "closed - not enough info."

Started an issue, you can find it [here](https://developercommunity.visualstudio.com/content/problem/516700/work-details-pane-is-in-hours.html).
