### ISSUE TITLE
@igoose  - If you open an issue for this topic and append the logo you want used, I'll update the topic to use that logo.

### ISSUE THREAD

**Issue by igoose** [MicrosoftDocs/vsts-docs#6568]
@igoose  - If you open an issue for this topic and append the logo you want used, I'll update the topic to use that logo.

_Originally posted by @KathrynEE in https://github.com/MicrosoftDocs/vsts-docs/pull/6539#issuecomment-561446948_

**Comment by igoose** [comment]
![ConnectALL-Logo](https://user-images.githubusercontent.com/2851923/70205124-13c5c100-1749-11ea-9803-3f9605fbc5fd.png)

Attached is the ConnectALL logo. This should be hyperlinked to https://www.connectall.com

**Comment by msebolt** [comment]
@igoose  Thank you for the update, assigning this to the author.

**Comment by KathrynEE** [comment]
@igoose - The logo has been updated.
