### ISSUE TITLE
Add-AzMetricAlertRuleV2 Fails in Azure DevOps with Agent "vs2017-win2016"

### ISSUE THREAD

**Issue by techsaau** [MicrosoftDocs/vsts-docs#6569]
Command "Add-AzMetricAlertRuleV2" is using object **<System.Collections.Generic.List`1[Microsoft.Azure.Commands.Insights.OutputClasses.IPSMultiMetricCriteria]>** for condition parameter in Az module. But "**Microsoft.Azure.Commands.Insights**" namespace was used in AzureRM.Insights. When I use Azure Powershell Task in DevOps (under agent "vs2017-win2016"), it gives error:

**Cannot find type [System.Collections.Generic.List[Microsoft.Azure.Commands.Insights.OutputClasses.IPSMultiMetricCriteria]]: verify that the assembly containing this type is loaded.**

How can I fix this?

Azure PowerShell Task
https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-powershell?view=azure-devops

**Comment by msebolt** [comment]
@techsaau Thank you for the feedback.

This issue is better apt for the [azure-pipelines-tasks](https://github.com/Microsoft/azure-pipelines-tasks) repo team.

Please move the issue [here](https://github.com/Microsoft/azure-pipelines-tasks/issues).

**Comment by techsaau** [comment]
Created a new issue [https://github.com/microsoft/azure-pipelines-tasks/issues/11917](url)
