### ISSUE TITLE
New variables not documented here

### ISSUE THREAD

**Issue by iyerusad** [MicrosoftDocs/vsts-docs#657]
Whole doc needs an update, many additional variables are now available (i.e. within Primary Artifact variable : Build.Repository.Name)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 611642f0-881f-10b9-ae94-3c562001d1f0
* Version Independent ID: 41efb94b-4c7a-64a3-b23b-70c8634ae727
* Content: [Variables in Release Management](https://docs.microsoft.com/en-us/vsts/build-release/concepts/definitions/release/variables?view=vsts&tabs=batch)
* Content Source: [docs/build-release/concepts/definitions/release/variables.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/build-release/concepts/definitions/release/variables.md)
* Service: **unspecified**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment]
Thank you for your feedback. I have passed on the question to the product team and will update the topic with any additional information they can provide.

**Comment by alexhomer1** [comment]
I'm adding a section to the topic: "View the current values of all release variables" - In the **Logs** page of a release summary, choose the **Initialize Job** step. The log pane includes a list of all the variables and their values for this release. Meantime, we'll review and update the lists of variables.
