### ISSUE TITLE
How do you add certificates to the agent so the Use nuget install tool will work?

### ISSUE THREAD

**Issue by DalpheSDC** [MicrosoftDocs/vsts-docs#6570]
How can I add the proxy certificates to the 
##[debug]Agent.CAInfo=undefined
##[debug]Agent.ClientCert=undefined
So I don't get this error when using task Use Nuget install tool
ERR:unable to get local issuer certificate

The Agent is version 2.160.1 and the server is Azure DevOps Server 2019 update 1, the server and build machine is behind a proxy.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e47a1942-09cb-f294-f1d3-09999645afb7
* Version Independent ID: 7b885f66-7165-ae4f-d35f-3cffe84cce28
* Content: [Run the agent behind a web proxy - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/proxy?view=azure-devops&tabs=windows)
* Content Source: [docs/pipelines/agents/proxy.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/agents/proxy.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by msebolt** [comment]
@DalpheSDC Thank you for the feedback, we apologize for the issues.

This has been reported in the **azure-pipelines-tasks** repo under https://github.com/microsoft/azure-pipelines-tasks/issues/9820.

Please refer there for further updates.
