### ISSUE TITLE
Docu not up to date

### ISSUE THREAD

**Issue by ccagahr** [MicrosoftDocs/vsts-docs#6574]
The button in visual studio redirects to a browser window opening the azure devops website with the process templates. There's no download option anymore. So how to get the xml definition? Only with the command line tools?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 60b7e8f3-68f7-80f9-3cfb-6dca0002435b
* Version Independent ID: e37d3809-9ad8-e82b-71c1-543066fc105d
* Content: [Upload, download, or delete a process template - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/boards/work-items/guidance/manage-process-templates?view=azure-devops)
* Content Source: [docs/boards/work-items/guidance/manage-process-templates.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/boards/work-items/guidance/manage-process-templates.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by msebolt** [comment]
@ccagahr Thank you for the feedback, assigning this to the author for review.

Is the [Process template REST API](https://docs.microsoft.com/rest/api/azure/devops/processadmin/processes/export%20process%20template?view=azure-devops-rest-5.1) a suitable work-around?

**Comment by KathrynEE** [comment]
@ccagahr - I checked with the product team and the functionality to export the process template has been removed and is not supported for Azure DevOps Services Inherited process model. Both export and import features aren't supported.  I will update the topic with this information. 

You may find a solution using https://github.com/microsoft/process-migrator.
