### ISSUE TITLE
Analytics View - Filter with created date 

### ISSUE THREAD

**Issue by manojpaidimarri** [MicrosoftDocs/vsts-docs#6575]
Hi Team,

When we try to create a new view with the filter criteria as 'created date' along with the date its taking the timestamp field also and  timestamp is taken as 18:30:00.000Z which is getting fixed with the created date field.  Along with the time its taking the 'N-1' date as created date.

**Comment by msebolt** [comment]
@manojpaidimarri Thank you for the feedback.

Please note this is a documentation forum so our support options are limited.  For product-related issues please move this issue [here](https://developercommunity.visualstudio.com/spaces/21/index.html).

What exactly does the `N-1` refer to?  Is the created date off by one day or do you need the time portion removed for easier filtering?

**Comment by msebolt** [comment]
Closing issue now.
