### ISSUE TITLE
azureSubscription input should clearly state that the value is the name of a Azure Resource Manager service connection

### ISSUE THREAD

**Issue by tbrophy** [MicrosoftDocs/vsts-docs#6578]
Using the name of a subscription—as the documentation suggests—will result in an error message; The pipeline is not valid. Job Job: Step AzureCLI input connectedServiceNameARM references service connection &lt;whatever value was supplied here&gt; which could not be found. The service connection does not exist or has not been authorized for use. For authorization details, refer to https://aka.ms/yamlauthz.

Also, for use cases where a Pipeline(s) should have access to one or all Resource Groups in a Subscription, the following appears to be another worth including in the documentation and error statement for creating a service connection.

- https://docs.microsoft.com/en-us/azure/devops/pipelines/library/connect-to-azure?view=azure-devops#create-an-azure-resource-manager-service-connection-using-automated-security

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8de3304e-98f9-bac0-3ccc-c65f68a89e87
* Version Independent ID: 8fb2f6a9-545d-dff1-ff86-974694a85054
* Content: [Azure CLI task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-cli?view=azure-devops&source=docs#feedback)
* Content Source: [docs/pipelines/tasks/deploy/azure-cli.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/deploy/azure-cli.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @ushan
* Microsoft Alias: **UshaN**

**Comment by msebolt** [comment]
@tbrophy Thank you for the feedback, assigning this to the author for review.

**Comment by iamsrivatsa** [comment]
The document has been updated and I'll be closing the issue. Thank you for the feedback and feel free to open a new issue if you have any more feedback.

**Comment by iamsrivatsa** [comment]
The document has been updated and I'll be closing the issue. Thank you for the feedback and feel free to open a new issue if you have any more feedback.
