### ISSUE TITLE
Using the '/' to in place of the word 'or' may suggest value assignments that are not clear.

### ISSUE THREAD

**Issue by tbrophy** [MicrosoftDocs/vsts-docs#6580]
Opinion; Within technical documentation, if two value options are mutually exclusive, it is clearer to express their relationship using the word 'or' or semantically equivalent grammar.  

Example for scriptType;  "Select bash/pscore script when running on Linux agent or batch/ps/pscore script when running on Windows agent."

Clearer statement; "Use the value of 'bash' or 'pscore' when running on Linux agent.  When running on Windows agent, use one of 'batch', 'ps' or 'pscore'."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8de3304e-98f9-bac0-3ccc-c65f68a89e87
* Version Independent ID: 8fb2f6a9-545d-dff1-ff86-974694a85054
* Content: [Azure CLI task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-cli?view=azure-devops&source=docs#feedback)
* Content Source: [docs/pipelines/tasks/deploy/azure-cli.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/deploy/azure-cli.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @ushan
* Microsoft Alias: **UshaN**

**Comment by msebolt** [comment]
@tbrophy Thank you for the feedback, a change to the documentation is pending.
