### ISSUE TITLE
Does canary deployment actually work for anyone?

### ISSUE THREAD

**Issue by yelob** [MicrosoftDocs/vsts-docs#6581]
If I try to use the strategy "canary" for my deployment job, the pipeline fails with no error messages. If I change to "runOnce", it runs as expected. Has anyone actually gotten the canary deployment job strategy to work? Simple example:
stages:
- stage: mystage
  displayName: 'Deploy Canary'
  jobs:
  - deployment: deploy
    pool:
      vmImage: ubuntu-latest
    environment: foo
    strategy:
      canary:
        increments: [10,20]
        deploy:
          steps:
          - task: PowerShell@2
            inputs:
              targetType: inline
              script: "write-host foo"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5aeeaace-1c5b-a51b-e41f-f25b806155b8
* Version Independent ID: fd7ff690-b2e4-41c7-a342-e528b911c6e1
* Content: [Deployment jobs - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/deployment-jobs?view=azure-devops)
* Content Source: [docs/pipelines/process/deployment-jobs.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/deployment-jobs.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by yelob** [comment]
Submitted a bug here: https://developercommunity.visualstudio.com/content/problem/846068/deployment-job-canary-strategy-fails-without-logs.html

**Comment by msebolt** [comment]
@yelob  Thank you for the feedback, closing now since the product team has picked up the issue.  

For additional comments/updates, please use the link above.
