### ISSUE TITLE
Azure Repos: Using a Single, Preexisting PAT with Git Credential Manager 

### ISSUE THREAD

**Issue by craigforr** [MicrosoftDocs/vsts-docs#6582]
As a follow-on to #2455, the "Use your personal access token" section of the how-to guide now includes examples of using a personal access token (PAT) with Git utilizing the native credential store, however, while the documentation suggests using Git Credential Manager instead, "to keep your token more secure," there are no examples of how to do so.

Git Credential Manager uses the interactive web pop-dialog when authenticating to an Azure Repo for the first time, however this generates a new PAT for each new repository, which quickly becomes unmanagable.  I have been unable to find a way to get a single, existing PAT credential to take with Git Credential Manager and persist across multiple git operations with Git for Windows.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 53f99d2d-363b-d01d-039d-4fdc636fa2df
* Version Independent ID: f47330d5-e2de-36a4-e5b3-5bc77505b161
* Content: [Authenticate with personal access tokens - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/use-personal-access-tokens-to-authenticate?view=azure-devops&tabs=preview-page)
* Content Source: [docs/organizations/accounts/use-personal-access-tokens-to-authenticate.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/accounts/use-personal-access-tokens-to-authenticate.md)
* Product: **devops**
* Technology: **devops-security**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @craigforr, Thanks for reaching out. I'm looking into this now and will be in touch soon. Thanks!

**Comment by chcomley** [comment]
Hi @craigforr, For every GIT repo a PAT is created the first time we connect to it. However, the code is in the public domain, so we'd be fine with you modifying the code to achieve your goal. My PM is curious as to what problem you're trying to solve by limiting everything to a single PAT, or in other words, what are your challenges with multiple PATs?

**Comment by craigforr** [comment]
Thanks for looking into this @chcomley...

Every PAT generated appears as follows under the Personal Access Tokens settings:

    Git: https://dev.azure.com/organization/ on COMPUTER-NAME

This makes managing their access privileges and renewals nearly impossible, because after I log into them all, I end up with a listing that looks like this:

    Git: https://dev.azure.com/organization/ on COMPUTER-NAME  Active  organization 12/6/2020
    Git: https://dev.azure.com/organization/ on COMPUTER-NAME  Active  organization 12/6/2020
    Git: https://dev.azure.com/organization/ on COMPUTER-NAME  Active  organization 12/6/2020
    Git: https://dev.azure.com/organization/ on COMPUTER-NAME  Active  organization 12/6/2020
    Git: https://dev.azure.com/organization/ on COMPUTER-NAME  Active  organization 12/6/2020
    ...

My goal, as I do with GitHub, is to utilize a single PAT for each endpoint/device from which I need to access a given set of repositories, pre-creating the PAT with a unique name that aptly identifies the endpoint it is used from, and their permissions.  I manage PATs used on remote systems/shells separate from the ones I use locally, on my computer.  I can keep the remote PATs at least privilege for the repositories they need to which they need access and, if any becomes compromised, it is very simple to revoke it with out disturbing the others.  In contrast, when the PATs have generic names (as VSTS/Azure Repos creates them, above), I have no clue where I'm using them or what repo they're associated with.

Hopefully, I'm making sense.  If not, just let me know, it's definitely my fault, and I'll try to clarify further.  And if there's a way of achieving what I'm aiming for in another way, or a better/smarter way, I'm game to try it.  Just let me know.  Thanks.

**Comment by chcomley** [comment]
@JimsonChalissery Please see the above comment and address. Please let me know if we need an update to the article, as well. Thank you!

**Comment by JimsonChalissery** [comment]
@craigforr Thank you for the details, it helps show how it can be a challenge to manage PATS when you have a lot of auto-created ones. While you have many PATs at this stage, I'm assuming the number of PATs have kind of accrued over time. One potential workaround would be to go to the PAT page and edit the name of the PAT to something more meaningful as soon as you've used GIT to clone a repo, for insakfe. That way you still have a way to distinguish the PATs as they are added. Another thing to note is that when PATs are auto-created, they are created with the minimal scopes required and if such a PAT expires, it will be auto-created as well. The real challenge might be for revocation of a  single compromised PAT, which I can imagine might be easier if they were named more meaningfully. Having said that its unlikely we'll get around to changing the behaviour here. This is not a popular request and hence would be difficult to prioritize.

**Comment by chcomley** [comment]
@craigforr, I'm going to close this issue, however please @mention me or Jimson if you have any further questions. Thanks very much and enjoy your weekend!
