### ISSUE TITLE
Language selection for a combo from type datetime picker

### ISSUE THREAD

**Issue by MarioMeldau** [MicrosoftDocs/vsts-docs#6585]
Hello,

how can i set the language for the combo from type datetimer picker? It is always german and i want to have english. I did not found anything to set the language.

**Comment by msebolt** [comment]
@MarioMeldau Thank you for the question.

Does the language change if you update your [general user settings](https://docs.microsoft.com/azure/devops/organizations/settings/set-your-preferences)?  

For the ability to use multiple languages, please direct the request [here](https://developercommunity.visualstudio.com/spaces/21/index.html) for feedback from the product team.

**Comment by MarioMeldau** [comment]
Thank you. Changing the general user settings helped.
