### ISSUE TITLE
Which version did I download?

### ISSUE THREAD

**Issue by mattlovett** [MicrosoftDocs/vsts-docs#6590]
Once I've run this task, how do I know which version of the artifact I'm working with? It would be good if the task set an output variable, so that I could use it later on in my yaml pipeline.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b03d67d0-8738-72e6-dbe7-324c1784d4fc
* Version Independent ID: bbb4d774-cd98-3ecb-7ccf-5f49e6f2b425
* Content: [Download Pipeline Artifacts task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/download-pipeline-artifact?view=azure-devops#feedback)
* Content Source: [docs/pipelines/tasks/utility/download-pipeline-artifact.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/utility/download-pipeline-artifact.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @vijayma
* Microsoft Alias: **vijayma**

**Comment by mattlovett** [comment]
Sorry, this is a duplicate of a closed issue!

**Comment by msebolt** [comment]
@mattlovett Thank you for the question, please see if [this post](https://stackoverflow.com/questions/57417485/how-to-specify-artifact-version-name-in-azure-devops) resolves your issue.

**Comment by jpricket** [comment]
Seems like mattlovett found what he needed and said this was a duplicate, so closing it.
