### ISSUE TITLE
Follow entire wiki?

### ISSUE THREAD

**Issue by softwarecraft** [MicrosoftDocs/vsts-docs#6591]
Hi, I want to follow the entire wiki for my DevOps project, including any new pages created by other people, without having to click Follow on each individual page.

Is this possible?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cd3da932-a8f8-f0b9-668d-0eb498df93b6
* Version Independent ID: 51e6cad0-1737-017a-9ce1-8c6c0090fc56
* Content: [Follow wiki page, get notifications - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/project/wiki/follow-notifications-wiki-pages?view=azure-devops#feedback)
* Content Source: [docs/project/wiki/follow-notifications-wiki-pages.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/project/wiki/follow-notifications-wiki-pages.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @softwarecraft, Thanks for reaching out. This feature is only available on the page level, so it's not possible to follow the entire wiki. I recommend submitting a [feature request](https://developercommunity.visualstudio.com/spaces/21/index.html). Thank you!

**Comment by soutchilin** [comment]
Hi @chcomley , any updates in planning of this feature?

**Comment by chcomley** [comment]
Hi @soutchilin, No updates yet. You can check on feature requests here: https://mseng.visualstudio.com/TechnicalContent/_queries/query-edit/f9b3de18-d757-42a5-a3fb-e63abd75b094/

**Comment by DdOtzen** [comment]
> Hi @soutchilin, No updates yet. You can check on feature requests here: https://mseng.visualstudio.com/TechnicalContent/_queries/query-edit/f9b3de18-d757-42a5-a3fb-e63abd75b094/

401 - Uh-oh, you do not have access

**Comment by OleksandrShamrai** [comment]
You can use a workaround. Check this link: https://stackoverflow.com/questions/70094824/how-to-follow-the-entire-wiki-in-azure-devops/70095981#70095981
