### ISSUE TITLE
Please improve the documentation of the version specification

### ISSUE THREAD

**Issue by logiclrd** [MicrosoftDocs/vsts-docs#6593]
The documentation of the version specification lists ">2.x" as an example. Based on this, I tried ">5.x" in my build pipeline and it did not work. ">5" didn't work either. Is there a way to simply always get the latest version? The documentation does not say whether the version spec can simply be omitted.

**Comment by msebolt** [comment]
@logiclrd Thank you for the feedback.

Please provide a link to the article in question and we will assign an author.

**Comment by logiclrd** [comment]
My apologies for that oversight, the page in question is:

https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/nuget?view=azure-devops

I think I ended up here by clicking on the "Send feedback about _this page_" option at the bottom of the page, and thought it would link up automatically, and so everything about the PR assumes that that context is known. I see now that it's completely missing :-)

**Comment by msebolt** [comment]
@logiclrd  Thank you for the update.

The documentation has been updated.  

Default version is 4.9 as per [source](https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/NuGetToolInstallerV1/nugettoolinstaller.ts).

You can omit the version and set `checkLatest` to true to keep up with the latest version as per the default above.
