### ISSUE TITLE
Page starts with a quote

### ISSUE THREAD

**Issue by SebastianSchuetze** [MicrosoftDocs/vsts-docs#6594]
Hi, I know that the first sentence on the page is how MS perceives the philosophy of DevOps, but I would prefer to reference quotes back to the originator!

http://donovanbrown.com/post/what-is-devops

I could imagine, that Donavan Brown is ok with it, but I also the perception of people is important. And (me coming from a university) I would prefer an approach to reference it back to the source!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0cf98c4b-9185-00d5-a980-e2adb3e291fd
* Version Independent ID: f6005931-c9b5-48d9-e6c3-f835bb9b01b1
* Content: [What is DevOps? - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/learn/what-is-devops#feedback)
* Content Source: [docs/what-is-devops.md](https://github.com/MicrosoftDocs/devops-learn-pr/blob/live/docs/what-is-devops.md)
* Product: **devops**
* Technology: **devops-learn**
* GitHub Login: @SamGu
* Microsoft Alias: **samgu**

**Comment by SebastianSchuetze** [comment]
Pull request for the suggested change: https://github.com/MicrosoftDocs/devops-learn-pr/pull/8

**Comment by msebolt** [comment]
@SebastianSchuetze Thank you for the feedback, reviewing the PR now.

**Comment by msebolt** [comment]
Started a new PR due to validation errors and submitted for further review.
