### ISSUE TITLE
Basic process: remove preview notice

### ISSUE THREAD

**Issue by NenoLoje** [MicrosoftDocs/vsts-docs#6598]
On two places, the basic process is stated to still be in preview:

- "selective Preview"
- "Note: Basic is currently in a selective Preview for new users of Azure Boards only."

Is that still the case, or should we rather remove the "preview" notes?

Thanks,
--Neno

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b3466d1-72cc-2d47-d98b-7029639c0f79
* Version Independent ID: 4ff82210-6b5a-589d-261e-1ddbd3007e2a
* Content: [Choose a process like Basic, Agile, Scrum, or CMMI - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/work-items/guidance/choose-process?view=azure-devops&tabs=basic-process#feedback)
* Content Source: [docs/boards/work-items/guidance/choose-process.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/boards/work-items/guidance/choose-process.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by msebolt** [comment]
@NenoLoje Thank you for the feedback, assigning this to the author for review.

**Comment by KathrynEE** [comment]
@NenoLoje - Thanks Neno, I'll update the topic to reflect that it is out of preview.

**Comment by larryclaman** [comment]
this issue was closed but it doesn't seem like the issue was addressed; the preview notice is still sprinkled throughout the page.

**Comment by NenoLoje** [comment]
@KathrynEE - could you take a look, please?
