### ISSUE TITLE
Use correct wording: Agent "queues" have become project-level agent pools

### ISSUE THREAD

**Issue by NenoLoje** [MicrosoftDocs/vsts-docs#6599]
In this document, the term "queue" is still used, whereas this has been renamed to agent pools (on the project level) a while ago.

Thanks,
--neno

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 65536478-7839-8477-b030-965159151e40
* Version Independent ID: 42f54ed3-8173-65b7-0a3a-e77b4c9b3d7a
* Content: [Understand how security roles work - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/security/about-security-roles?view=azure-devops#agent-queue-security-roles)
* Content Source: [docs/organizations/security/about-security-roles.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/security/about-security-roles.md)
* Product: **devops**
* Technology: **devops-security**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by msebolt** [comment]
@NenoLoje Thank you for the feedback.

The documentation will be updated shortly.
