### ISSUE TITLE
Agent communication lost error - docs improvement

### ISSUE THREAD

**Issue by GitHubSriramB** [MicrosoftDocs/vsts-docs#66]
The following FW link can be improved:
https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting#renew-lock

1. The error message it refers to is not current.
2. We can suggest looking at agent diagnostics logs by following troubleshooting docs.
3. If troubleshooting does not help, we can suggest filing an issue in vsts-agent repo.

**Comment by GitHubSriramB** [comment]
Raised following PR to make these improvements: 
https://github.com/MicrosoftDocs/vsts-docs/pull/67

**Comment by steved0x** [comment]
@GitHubSriramB I'm closing this issue since we have your PR, I have sent that over to the right folks for review and to get it merged. Thank you!
