### ISSUE TITLE
Where has the detailed REST API documentation gone?

### ISSUE THREAD

**Issue by ruairiohagan** [MicrosoftDocs/vsts-docs#660]
My old links aren't working anymore, just directing to this dumbed-down high level content.

Maybe I'm missing something obvious, but I can't find the detailed reference anywhere.

I've had to use the way back machine (web.archive.org) to get the documentation I need.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 740ea7a3-10a8-e631-210c-11a2a65fdc6d
* Version Independent ID: a14c0a3c-0f17-60cb-a430-5693b0f71de3
* Content: [Clients Services](https://docs.microsoft.com/en-us/vsts/extend/reference/client/client-services?view=vsts)
* Content Source: [docs/extend/reference/client/client-services.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/extend/reference/client/client-services.md)
* Service: **unspecified**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by elbatk** [comment]
Hey @ruairiohagan , we got rid of the old content as the old site (visualstudio.com) docs were taken down and we moved to this new one. I'll consult with the area owners and find out what they want to do about getting the old detailed docs up.

**Comment by elbatk** [comment]
Hey again @ruairiohagan, this may be helpful for you:
https://docs.microsoft.com/en-us/vsts/extend/reference/client/rest-clients?view=vsts

Going to close this issue but please feel free to reopen if this isn't what you're looking for!

**Comment by ruairiohagan** [comment]
Hi @elbatk , looks good, thanks for your help.
