### ISSUE TITLE
Update wording: TFS and "Team Foundation Server"

### ISSUE THREAD

**Issue by NenoLoje** [MicrosoftDocs/vsts-docs#6601]
This page still talks about "TFS" and "Team Foundation Server" instead of Azure DevOps Server. Please update.

Thanks,
--Neno

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 23328b13-f079-ad21-5d7a-6c640f25391c
* Version Independent ID: 4a39889d-fa00-ae2b-aa43-f358631b7b1a
* Content: [Deploy a Azure Pipelines agent on Linux - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/v2-linux?view=azure-devops#permissions)
* Content Source: [docs/pipelines/agents/v2-linux.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/agents/v2-linux.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by msebolt** [comment]
@NenoLoje Thank you for the feedback.

The documentation will be updated shortly.

**Comment by steved0x** [comment]
I am working on this one and it should be updated shortly.

**Comment by shashban** [comment]
Thanks for reporting Neno. Getting it fixed now.
