### ISSUE TITLE
Remove deployment notice

### ISSUE THREAD

**Issue by NenoLoje** [MicrosoftDocs/vsts-docs#6606]
The docs still say that the feature is "is in the process of deployment", which should meanwhile be obsolete and it creating confusion around users.

Thanks,
--Neno

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 29f1e43f-a069-dd88-7fc7-9cc497fb94f0
* Version Independent ID: c261afa7-6eb7-b3f0-9f92-6d2f3c5ac336
* Content: [Markdown syntax for wikis in Azure DevOps - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/project/wiki/wiki-markdown-guidance?view=azure-devops#add-mermaid-diagrams-to-a-wiki-page)
* Content Source: [docs/project/wiki/wiki-markdown-guidance.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/project/wiki/wiki-markdown-guidance.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by msebolt** [comment]
@NenoLoje Thank you for the feedback, assigning this to the author for review.

**Comment by chcomley** [comment]
Hi @NenoLoje, Thanks for this and sorry for any confusion. I've removed the deployment note from the article. Thanks again!
