### ISSUE TITLE
Lead

### ISSUE THREAD

**Issue by HughDevlin** [MicrosoftDocs/vsts-docs#6608]
"You can use a parallel job in Azure Pipelines to run a single job at a time in your organization."

If you come here to learn more about parallel jobs, the very 1st sentence is so confusing as to be off-putting. A parallel job can be used to run a single job at a time? OK, but then what's parallel about it? Is this trying to say jobs may be run, and optionally, run in parallel? Maybe lead by hazarding an informal definition of parallel jobs. "Parallel jobs refers to the ability to run more than one job at the same time, with certain limitations" or some such. Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c6a488b-88f6-dff6-e2ee-402167e17ad4
* Version Independent ID: 9a4dedda-e82c-2833-f28c-5ab346fb1b38
* Content: [Parallel jobs in Azure Pipelines - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/licensing/concurrent-jobs?view=azure-devops)
* Content Source: [docs/pipelines/licensing/concurrent-jobs.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/licensing/concurrent-jobs.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by msebolt** [comment]
@HughDevlin Thank you for the feedback, assigning this to the author for review.

**Comment by jimlamb** [comment]
Taking a look to see if I can come up with something a bit more clear.
