### ISSUE TITLE
Private project: One free parallel job

### ISSUE THREAD

**Issue by HughDevlin** [MicrosoftDocs/vsts-docs#6609]
In section "Microsoft-hosted CI/CD",  what is meant by "Private project: One free parallel job..."? Is this a clever way of saying jobs may not be run in parallel in the free tier? If so, it is so clever it is confusing. Do I understand from this, that Microsoft wants say sure, parallel jobs are available in the free tier, they just can't run jobs in parallel? It reads as if Microsoft is reluctant to simply state a fundamental limitation, which is that parallel jobs are for fee.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c6a488b-88f6-dff6-e2ee-402167e17ad4
* Version Independent ID: 9a4dedda-e82c-2833-f28c-5ab346fb1b38
* Content: [Parallel jobs in Azure Pipelines - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/licensing/concurrent-jobs?view=azure-devops)
* Content Source: [docs/pipelines/licensing/concurrent-jobs.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/licensing/concurrent-jobs.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by msebolt** [comment]
@HughDevlin Thank you for the feedback, assigning this to the author for review.

**Comment by damccorm** [comment]
Thanks for the feedback - I'm taking a look

**Comment by damccorm** [comment]
Thank you for your feedback. 
The article reference is being updated to address the issue.
