### ISSUE TITLE
 Azure classic portal does not exist anymore

### ISSUE THREAD

**Issue by mguntli** [MicrosoftDocs/vsts-docs#661]
Documentation issues:
1. Link to Azure classic portal redirects to default Azure portal.

Problem:
I am unable to delete the "Microsoft Visual Studio Team Services" Enterprise Application, which prevents me from deleting my Azure Active Directory

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c0449868-e233-3ada-067b-fc8de52ecc9a
* Version Independent ID: df871375-c579-12c1-6aec-394046c42746
* Content: [Delete or recover VSTS account](https://docs.microsoft.com/en-us/vsts/accounts/delete-your-vsts-account?view=vsts)
* Content Source: [docs/accounts/delete-your-vsts-account.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/accounts/delete-your-vsts-account.md)
* Service: **unspecified**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
@mguntli Thanks for bringing this to our attention, I'll update the documentation to reflect the "default" Azure portal. As for an answer to your problem, I'm hoping this blog post will help: https://blogs.msdn.microsoft.com/dstfs/2015/05/27/trouble-deleting-azure-active-directory-aad-due-to-visual-studio-online-item-in-aad-applications-list/ 
Thanks again!
