### ISSUE TITLE
Any changes in task,commands in sprint should notified to team

### ISSUE THREAD

**Issue by devopsdymyr** [MicrosoftDocs/vsts-docs#6610]
We are tried to configure notification for our project to send notification to team if there is any chnages in task or sprint should notify.
![image](https://user-images.githubusercontent.com/41105507/70294286-fe17d080-1808-11ea-8986-f43c96798450.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f7bf3dc8-4c12-bf7f-2f65-74e5c90cfc3b
* Version Independent ID: e5b84ecc-d3fe-b65f-b9f7-3d94ee7aed72
* Content: [Manage notifications for a team or group - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/notifications/howto-manage-team-notifications?view=azure-devops)
* Content Source: [docs/notifications/howto-manage-team-notifications.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/notifications/howto-manage-team-notifications.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by msebolt** [comment]
@devopsdymyr Thank you for the feedback.

Does this work if you change **Team preference** to **All team members**?  

If so, please refer to [Manage team delivery settings](https://docs.microsoft.com/azure/devops/notifications/howto-manage-team-notifications?view=azure-devops#manage) for troubleshooting.

**Comment by msebolt** [comment]
Closing the issue now.
