### ISSUE TITLE
Sharing test results ? 

### ISSUE THREAD

**Issue by jimicze** [MicrosoftDocs/vsts-docs#6611]
How can i share testresults from release pipe to slack channel with % pass rate ? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 99a6f5aa-7e92-a028-d13e-e1e4b7fede86
* Version Independent ID: be7e5d7c-0033-6b72-4bd1-809f7d1894aa
* Content: [Azure Pipelines with Slack - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/integrations/slack?view=azure-devops#feedback)
* Content Source: [docs/pipelines/integrations/slack.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/integrations/slack.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @atinb
* Microsoft Alias: **atinb**

**Comment by msebolt** [comment]
@jimicze Thank you for the question.

You would need to create a [custom service hook](https://docs.microsoft.com/azure/devops/service-hooks/services/webhooks) and query your results with the [Test Results API](https://docs.microsoft.com/rest/api/azure/devops/test/results), then subscribe to the hook using something like **Azure Pipelines app for Slack** referenced [here](https://docs.microsoft.com/azure/devops/service-hooks/services/slack?view=azure-devops).

Refer to [this post](https://developercommunity.visualstudio.com/idea/635122/add-test-run-related-events-for-service-hooks.html) to vote and/or comment on the ability to subscribe directly to test events.

**Comment by msebolt** [comment]
Closing the issue now.
