### ISSUE TITLE
No details or explanation provided

### ISSUE THREAD

**Issue by muraliwho** [MicrosoftDocs/vsts-docs#6612]
Some steps are missing. Please note that I am new to creating Azure DevOps Pipelines and when I see the section mentioned below (above in the article). How do I navigate to the project? I have not created it yet as per the article. Please fix the steps to make this article useful.
-------
Get your first run
Sign in to your Azure DevOps organization and navigate to your project.
-------

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7336a04e-5b38-d02f-8bba-a55445b2f094
* Version Independent ID: 783c30b3-63b6-da7c-1336-b000bb8b4c66
* Content: [Create your first pipeline - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/create-first-pipeline?view=azure-devops&tabs=browser%2Ctfs-2018-2)
* Content Source: [docs/pipelines/create-first-pipeline.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/create-first-pipeline.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by msebolt** [comment]
@muraliwho  Thank you for the feedback.

Please find steps to navigate to your project included in the topic [Sign up for Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/get-started/pipelines-sign-up?view=azure-devops).

A link to this topic is included in the **Prerequisites** section of [Create your first pipeline](https://docs.microsoft.com/azure/devops/pipelines/create-first-pipeline).

**Comment by msebolt** [comment]
Closing the issue now.
