### ISSUE TITLE
Update Go example from 1.11 to 1.13

### ISSUE THREAD

**Issue by estensen** [MicrosoftDocs/vsts-docs#6614]
The way modules are used differ between the versions. The docs should be update to (also) show an example for the latest release. I feel it's especially important since people copy-paste code found in documentation. The example is also more complex than it has to be since many of the values that are set are already set as defaults.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b86b5c3a-d266-e9fe-621e-eb6244199984
* Version Independent ID: 57ca9f4f-ad07-4ab5-3153-9853e6b24797
* Content: [Build and test Go projects - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/ecosystems/go?view=azure-devops)
* Content Source: [docs/pipelines/ecosystems/go.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/ecosystems/go.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by msebolt** [comment]
@estensen  Thank you for the feedback, assigning this to the author for review.

**Comment by estensen** [comment]
@v-albemi can you link to the PR or commit that fixed this issue or explain why it was closed?

**Comment by v-albemi** [comment]
@estensen 

It looks like this closed when I merged https://github.com/MicrosoftDocs/azure-devops-docs-pr/pull/680.

**Comment by estensen** [comment]
https://github.com/MicrosoftDocs/azure-devops-docs-pr/pull/680 gives me a 404

**Comment by v-albemi** [comment]
the link works for me. 

There's another link just above your comment from 5 minutes ago. Maybe that one will work?

**Comment by estensen** [comment]
If you hover over the link you posted you can tell they are the same

**Comment by v-albemi** [comment]
I think it's a permissions issue. There's a note in 680 that says it fixes this PR.

**Comment by estensen** [comment]
It would have been easier for outsiders to track the issue if it wasn't closed before the updates were in production. Also a link to the PR would make it easier to see if the issue was fixed.

**Comment by v-albemi** [comment]
@estensen 

Thanks for your contribution. The commit was pulled into another PR and the issue should be resolved and live soon.

**Comment by SpreeRaj** [comment]
Is it updated yet? I can still only use version 1.11
