### ISSUE TITLE
Variable Names handled inconsistently

### ISSUE THREAD

**Issue by BenResTech** [MicrosoftDocs/vsts-docs#6618]
The above information states (in the section on 'Set variables in pipeline)' that:
```
In the YAML file, you can set a variable at various scopes:

At the root level, to make it available to all jobs in the pipeline
At the stage level, to make it available only to a specific stage
At the job level, to make it available only to a specific job
...........
Notice that variables are also made available to scripts through environment variables. The syntax for using these environment variables depends on the scripting language. Name is upper-cased, . replaced with _, and automatically inserted into the process environment. Here are some examples:

Batch script: %VARIABLE_NAME%
PowerShell script: $env:VARIABLE_NAME
Bash script: $VARIABLE_NAME
```

However, having just tested this, the name of the variable supplied to the Bash script is not automatically made into upper case if the variable is defined as an env var to the Bash task. My example was using the built-in system.accesstoken variable.

The following (which is compliant with the above documentation) does not correctly use the variable:
```
- bash: 'echo  "my test token is" $AZUREDEVOPSTOKEN'
  env:
    AzureDevOpsToken: $(System.AccessToken)
```
```
==============================================================================
Generating script.
Script contents:
echo "my token is" $AZUREDEVOPSTOKEN
========================== Starting Command Output ===========================
/bin/bash --noprofile --norc /vsts/agent/_work/_temp/67dc4d29-07eb-47fa-9b90-55af36ab8f73.sh
my token is
```

While the below (which goes *against* the above documentation) does work:
```
- bash: 'echo  "my test token is" $AzureDevOpsToken'
  env:
    AzureDevOpsToken: $(System.AccessToken)
```
```
Generating script.
Script contents:
echo  "my test token is" $AzureDevOpsToken
========================== Starting Command Output ===========================
/bin/bash --noprofile --norc /vsts/agent/_work/_temp/cbf529fb-1768-405f-94b2-13ec4638704e.sh
my test token is ***

```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd7e0bd3-1f7d-d7b6-cc72-5ef63c31b46a
* Version Independent ID: dae87abd-b73d-9120-bcdb-6097d4b40f2a
* Content: [Variables - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch#set-variables-in-pipeline)
* Content Source: [docs/pipelines/process/variables.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/variables.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by msebolt** [comment]
@BenResTech Thank you for the feedback, assigning this to the author for review.

**Comment by mjroghelia** [comment]
I'm looking at this one.

**Comment by mjroghelia** [comment]
@BenResTech Thank you for your feedback. The documentation you referenced is describing the automatic translation of pipeline variables to environment variable and does not pertain to the environment variables you explicitly define yourself via the `env` options. Environment variables you yourself declare will remain as you declare them. In the following example, the first echo demonstrates what is being described in the referenced documentation, whereas the second is unrelated:

```
trigger: none
pool:
  vmImage: 'ubuntu-16.04'
steps:
 - bash: echo "agent build directory is $AGENT_BUILDDIRECTORY"
 - bash: echo "buildDir is $buildDir"
   env:
     buildDir: $(Agent.BuildDirectory)
```

**Comment by BenResTech** [comment]
@mjroghelia I'm sorry but I don't think that that is the case (or if it is the case then the page needs changing). The page states (in the 'Understand Variable Syntax' section):
```
Variables are also injected into the enironment. This includes both variables defined at the step level **and variables defined at the job or stage level**, with the most locally scoped variable winning. When variables are turned into environment variables, variable names become uppercase and periods turn into underscores. For example, the variable foo.bar becomes $FOO_BAR.
```
(Bold emphasis is mine)

If what you say is true and only variables defined at the pipeline level are manipulated in that way, then the above extract is wrong.

In addition the section in 'Set Variables in Pipelines' also repeats the same information, as originally posted when I opened the issue:
```
In the YAML file, you can set a variable at various scopes:

At the root level, to make it available to all jobs in the pipeline
At the stage level, to make it available only to a specific stage
At the job level, to make it available only to a specific job
....
Name is upper-cased, . replaced with _, and automatically inserted into the process environment. Here are some examples:

Batch script: %VARIABLE_NAME%
PowerShell script: $env:VARIABLE_NAME
Bash script: $VARIABLE_NAME
```
If these sections are only meant to refer to variables defined at the pipeline level, then the documentation needs to be corrected.

**Comment by mjroghelia** [comment]
@BenResTech To clarify, when I said "pipeline variables" I was referring to variables as the concept that exists in Pipelines and is described by this document, not variables defined only at the top level of the YAML. Variables can be defined in the YAML globally or at the stage or job level using the `variables` key.

This is separate from operating system environment variables. When you use the `env` key you are defining environment variables. If you use that method to declare an environment variable called "myVar" it will be called "myVar".

As a convenience, Pipelines creates environment variables for you from pipeline variables. When doing so, it uses the naming convention described in the docs.

This doc is not saying that it normalizes environment variables you yourself define with `env`.

**Comment by BenResTech** [comment]
Ah! Understood @mjroghelia, thanks for the clear explanation, that's makes a lot more sense.
Where is the above documented? I'd like to read through it further so I can nail it down in my head.
