### ISSUE TITLE
.NET Framework containers are no longer supported for 1803 servers

### ISSUE THREAD

**Issue by rastrup** [MicrosoftDocs/vsts-docs#6624]
https://github.com/dotnet/announcements/issues/141
How is the support for containers when running the win1803 image?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 99af681d-41ad-da15-0b72-08b5cd5a11ac
* Version Independent ID: 2fa0df36-a437-8cbb-b019-b49b31b1e116
* Content: [Microsoft-hosted agents for Azure Pipelines - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops#feedback)
* Content Source: [docs/pipelines/agents/hosted.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/agents/hosted.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by msebolt** [comment]
@rastrup  Thank you for the feedback, support for the `1803` image ended on November 12th, 2019.

Please refer to the  [Microsoft Docker repo](https://hub.docker.com/_/microsoft-windows-servercore) for more information and a current list supported images.

To see the version used by an agent, refer to the [azure-pipelines-image-generation](https://github.com/microsoft/azure-pipelines-image-generation) repo, for example, the [vs2017-win2016](https://github.com/microsoft/azure-pipelines-image-generation/blob/master/images/win/Vs2017-Server2016-Readme.md#docker-images) uses the `mcr.microsoft.com/windows/servercore:ltsc2016` image.

Assigning this to the author for review.
