### ISSUE TITLE
Set and Share variables across pipelines in YAML pipelines 

### ISSUE THREAD

**Issue by jashan05** [MicrosoftDocs/vsts-docs#6625]
Hello Team,

We have 2 pipelines in YAML format 
- Build pipeline - This pipeline builds some artifacts 
- Release Pipeline - This pipeline deploys the build artifacts built in the build pipline. 

I can copy the artifacts built using build pipeline, in my release pipeline. But i also need to set some Variables in my build pipeline which i want to use in release pipeline. This variable shouldnt be dependent on Agent Scope

Could you please guide me how can i achieve this.

Best Regards
Jashan

**Comment by tannguyen3** [comment]
@jashan05: did you try [variable group ](https://docs.microsoft.com/en-us/azure/devops/pipelines/library/variable-groups?view=azure-devops&tabs=yaml). 
It allows us to share variable between pipelines and can be used in yaml too.

**Comment by msebolt** [comment]
@jashan05 Thank you for the question.

As mentioned above, please refer to [Variable groups](https://docs.microsoft.com/en-us/azure/devops/pipelines/library/variable-groups?view=azure-devops&tabs=yaml), or use the **Azure DevOps community** to comment on the [latest variable feature](https://developercommunity.visualstudio.com/idea/365752/library-of-variable-and-task-groups-shared-between.html) and solicit help from the product team.

**Comment by jashan05** [comment]
@tannguyen3 @msebolt  Thanks for the response. I already tried the variable groups, but that doesnt help me in my use case. 
In my use case i need to set the variable as an Output of my build pipeline everytime i ran my build. 
Then my release pipeline uses that output variable of build pipelines as an input. 
As per my understanding Variable group can be used when we have a static variable to be shared between multiple pipelines.

**Comment by tannguyen3** [comment]
@jashan05 for your case, I don't know any feature that would help. One thing you can try is serializing the variables in build to a file, add it to the artifact and use them in the release.

**Comment by msebolt** [comment]
This feature is currently in progress, pease refer to [this issue](https://developercommunity.visualstudio.com/content/problem/701307/use-of-dynamic-variables-in-yaml-pipelines.html) for updates.

A possible work-around is to use the PowerShell task, see [here](https://stackoverflow.com/questions/58813136/dynamically-set-azure-devops-variable-in-scripts).

Closing issue now.
