### ISSUE TITLE
[Solved] The Azure DevOps Office Integration in VS2019 is not working

### ISSUE THREAD

**Issue by byronbayer** [MicrosoftDocs/vsts-docs#6626]
Installing the 'Azure DevOps Office Integration' that comes with the Visual Studio 2019 installer does not work. Just trying to connect to the server will give the following misleading error:

Azure DevOps Server

TF31003: Either you have not entered the necessary credentials or your user account does not have permission to connect to the Azure DevOps Server at https://dev.azure.com/organisation. Ask your server administrator to add the appropriate permissions to your account.

The following error was encountered: TF30063: You are not authorized to access https://dev.azure.com/organisation.

Solution:
-
To fix this issue you should

- remove the 'Azure DevOps Office Integration' via the Visual Studio installer
- install 'Azure DevOps Office® Integration 2019' from [https://visualstudio.microsoft.com/downloads/#other-family](https://visualstudio.microsoft.com/downloads/#other-family)
- Restart machine

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bf4c6dd3-d2d2-0d41-9958-d3f7d85b5c05
* Version Independent ID: e5e4a28f-30b8-0dab-b94b-d94fe6d341fe
* Content: [Azure DevOps Office integration issues - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/backlogs/office/tfs-office-integration-issues?view=azure-devops)
* Content Source: [docs/boards/backlogs/office/tfs-office-integration-issues.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/boards/backlogs/office/tfs-office-integration-issues.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by msebolt** [comment]
@byronbayer Thank you for providing the feedback.

We apologize for any difficulties, the issue was previously documented [here](https://docs.microsoft.com/azure/devops/reference/error/tf31003-user-account-no-permission-connect-tfs?view=azure-devops).

I'll make sure a note with link gets added to the [Office integration issues](https://docs.microsoft.com/azure/devops/boards/backlogs/office/tfs-office-integration-issues?view=azure-devops) page.
