### ISSUE TITLE
Lack of Billing Details

### ISSUE THREAD

**Issue by JakeWierzba** [MicrosoftDocs/vsts-docs#6629]
Why is it so hard to find prices for things in Azure.
On the Billing settings page why doesn't have the cost per pipeline in a column right beside the pipeline type.
At the very least when you change it and click save it should tell you that it will increase/decrease you monthly costs by X amount before you save it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7734edca-173b-ba47-bf1b-3c19f9bd93e1
* Version Independent ID: d6ea8680-546e-f102-fd55-b35af33a6aa5
* Content: [Buy CI/CD Azure Pipelines - Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/organizations/billing/buy-more-build-vs?view=azure-devops#feedback)
* Content Source: [docs/organizations/billing/buy-more-build-vs.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/billing/buy-more-build-vs.md)
* Product: **devops**
* Technology: **devops-billing**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @JakeWierzba, I'm sorry for your frustration. There was a link to the pricing calculator within the article, however it wasn't easy to find, so I've added a TIP to all of our billing articles, which states the following:
To configure costs for Azure DevOps, see the [Pricing calculator ](https://azure.microsoft.com/en-us/pricing/calculator/?service=azure-devops)or the [Azure DevOps pricing page](https://azure.microsoft.com/en-us/pricing/details/devops/azure-devops-services/).
Hope this is helpful. Thanks for reaching out!

**Comment by chcomley** [comment]
Please @mention me if you have any further questions, @JakeWierzba. Thanks again.

**Comment by JakeWierzba** [comment]
@chcomley
Thanks for the reply. I did look at the pricing calculator after you mentioned it and it did give me the information I needed.

**Comment by NeilMacMullen** [comment]
A minor point but in step 4 "Enter the amount of Microsoft-hosted CI/CD or Self-hosted CI/CD, and then select Save." the design of the billing page is confusing.  It shows the current free tier as "1800 minutes" so my first instinct was to enter *a number of minutes* into the "Paid" box until I realised it was meant to be the number of jobs.  I'm not quite sure what would have happened if I'd really tried to book 3000 parallel jobs but but I'm hoping it wouldn't have been a call from the credit card company! ;-)
