### ISSUE TITLE
"Copy Files" VSTS task throws an error and stops file copy when "Advance/Overwrite" option is unticked

### ISSUE THREAD

**Issue by mivica** [MicrosoftDocs/vsts-docs#663]
When "Advance/Overwrite" option is unticked, "Copy Files" VSTS task throws an error 
"##[error]Error: Failed cp: cp: dest file already exists: <some file>" and then stops copying even when "Continue On error" is selected. Can we have a switch to skip existing file and just continue copy without throwing an error?
An example scenario is where "Overwrite" is unticked to avoid unnecessary file copies/overwrites when flattening many files from many folders where file name duplication is expected. So copy the file once and then skip it if found again later on in the different source folder.

**Comment by vijayma** [comment]
Thanks for the feedback. Can you please post this feature request on https://github.com/Microsoft/vsts-tasks repository? That is where the "Copy Files" task source code is present. Closing this issue here since it is not specific to the documentation.
