### ISSUE TITLE
select between pre-installed java versions?

### ISSUE THREAD

**Issue by HughDevlin** [MicrosoftDocs/vsts-docs#6630]
Microsoft hosted agents typically come pre-installed with multiple versions of java installed. For example, currently pools ubuntu-latest and windows-latest include javas 7, 8, and 11. Can this tool be used to simply select among these options? The examples provided above involve downloads and installations.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 182d85e3-f124-b440-78cb-2b1c52617ae0
* Version Independent ID: 26372d15-3e1a-0e8b-f5bb-abf0165f6480
* Content: [Java Tool Installer task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/java-tool-installer?view=azure-devops)
* Content Source: [docs/pipelines/tasks/tool/java-tool-installer.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/tool/java-tool-installer.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @vijayma
* Microsoft Alias: **vijayma**

**Comment by HughDevlin** [comment]
Seems to me like this tool could gracefully handle selecting among pre-installed Javas. Maybe a new jdkSourceOption 'Pre-installed", which attempts to match on versionSpec and jdkArchitectureOption, if found activates without overhead of download & install. 

- script: |
    echo "##vso[task.setvariable variable=JAVA_HOME]$(JAVA_HOME_11_X64)"
    echo "##vso[task.setvariable variable=PATH]$(JAVA_HOME_11_X64)\bin;$(PATH)"
  displayName: "Set java version"

**Comment by msebolt** [comment]
@HughDevlin Thank you for the feedback.

Something like is better handled by the [azure-pipelines-tasks](https://github.com/Microsoft/azure-pipelines-tasks) team tasked with adding new features to the source code.

Please start this issue [here](https://github.com/Microsoft/azure-pipelines-tasks/issues) and reference this issue in the description if you'd prefer.

**Comment by msebolt** [comment]
Closing issue now.
