### ISSUE TITLE
Understand variable syntax: When pipeline variables are turned into environment variables...

### ISSUE THREAD

**Issue by HughDevlin** [MicrosoftDocs/vsts-docs#6633]
In section Understand variable syntax, the wording "When pipeline variables are turned into environment variables..." is awkward. "turned into" suggest some kind of action, what is it?. Are all pipeline variables stored as environment variables? If not, under what conditions are pipeline variables available as environment variables? When is the lower case syntax used and when is the uppercase syntax used? Also, add respectfully to the end of the last sentence after the series of 3 examples.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd7e0bd3-1f7d-d7b6-cc72-5ef63c31b46a
* Version Independent ID: dae87abd-b73d-9120-bcdb-6097d4b40f2a
* Content: [Variables - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch#understand-variable-syntax)
* Content Source: [docs/pipelines/process/variables.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/variables.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by msebolt** [comment]
@HughDevlin Thank you for the feedback, assigning this to the author for review.

**Comment by damccorm** [comment]
Thanks for your feedback - I'm taking a look.

**Comment by damccorm** [comment]
Thank you for your feedback. 
The article reference is being updated to address the issue.
