### ISSUE TITLE
Is it possible to force a page to sort alphabetically?

### ISSUE THREAD

**Issue by lehmacdj** [MicrosoftDocs/vsts-docs#6634]
When there is no `.order` file the pages are sorted alphabetically. For some scenarios this is desired. Is it possible to force this behavior and prevent pages from being reordered. 

Alternatively, is there a way to remove the .order file and revert to alphabetical sorting without cloning the wiki and removing the file manually?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 361efecd-d973-82ed-1dd8-ca01afe12f5d
* Version Independent ID: 629f3af2-8218-e53c-45c3-0e40c03f2273
* Content: [Wiki files, structure, and conventions - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/project/wiki/wiki-file-structure?view=azure-devops#feedback)
* Content Source: [docs/project/wiki/wiki-file-structure.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/project/wiki/wiki-file-structure.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @lehmacdj, Thanks for reaching out. I've followed up with the product group for clarification and will be in touch. Have a nice day.

**Comment by chcomley** [comment]
Hi @lehmacdj,
Removing the .order file is the only way to do so, however the following process may be easier, which I've added to the article:
When there's no *.order* file the pages are sorted alphabetically. To revert to alphabetical sorting, do the following steps: 
1. Copy the clone URL for the Wiki and open it in a browser. 
   Doing so opens the Git Repo (Files Hub), which backs the Wiki. 
2. Navigate to the *.order* file and delete it.

Please @mention me if you have any further questions! Thanks!

**Comment by angularsen** [comment]
@chcomley The `.order` file is added back every time a new sub-page is added. Is it possible to disable this feature? It would make sense to add `.order` file if someone intentionally moves a page up/down, but not when adding a new page.
