### ISSUE TITLE
Is it possible to associate Selenium test-case which are developed using Java language through Eclipse?

### ISSUE THREAD

**Issue by darsh2311** [MicrosoftDocs/vsts-docs#6637]
Hello, I am able to see that all the configuration to associate the selenium test cases with test plan or test case are shown through Visual studio and not with any other tool like Eclipse, So I want to know whether it's possible to associate selenium test cases which are developed in java language through Eclipse tool directly with the Azure DevOps test plan/test cases(manual test cases)? or Visual studio is necessary with .Net programming language to associate automated TCS.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7d8a7e40-73d6-795f-7b8c-77104ef606e8
* Version Independent ID: 8f15995b-bd94-8d9f-1e8b-82f1f364d221
* Content: [Associate automated tests with test cases - Azure Test Plans](https://docs.microsoft.com/en-us/azure/devops/test/associate-automated-test-with-test-case?view=azure-devops)
* Content Source: [docs/test/associate-automated-test-with-test-case.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/test/associate-automated-test-with-test-case.md)
* Product: **devops**
* Technology: **devops-test**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by msebolt** [comment]
@darsh2311 Thank you for the question.

Out of box setup requires Visual Studio, refer to [UI Test with Selenium](https://docs.microsoft.com/azure/devops/pipelines/test/continuous-test-selenium).

However, for a custom approach you can run Selenium from `java` like [this post](https://stackoverflow.com/questions/1231975/i-want-to-run-selenium-test-case-file-from-command-line) describes, then wrap this with the [Command-line task](https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/command-line).

**Comment by msebolt** [comment]
Closing issue now.

**Comment by jimicze** [comment]
How can i wrap it and associate them by command-line task ? because i need to connect to VSTS API to make some changes ..

**Comment by msebolt** [comment]
VSTS API is somewhat trickier but is accomplished by adding something like `curl` to the Command-line task, see [here](https://docs.microsoft.com/en-us/rest/api/azure/devops/?view=azure-devops-rest-5.1#create-the-request) for an example.

Out-of-box also supports the [Invoke REST API](https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/http-rest-api) task for this kind of thing which can be run after the Command-line task.

**Comment by eidermauricio** [comment]
What are the Test Harness Supported in .Net core in order to associate the automation to the workitem? Does it support  Microsoft Test Platform? does it Support XUnit?
