### ISSUE TITLE
Support for Git Tagging to publish different content versions

### ISSUE THREAD

**Issue by VOVELEE** [MicrosoftDocs/vsts-docs#6638]
Hi Team,

currently Azure DevOps wiki engine supports publishing different content versions based on a versioned branch of a Git repo. 
Do you plan supporting git tags for different content versions?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c697355f-1e75-27a9-8214-195c26ede4e7
* Version Independent ID: 3f62c207-5449-d7f3-f3b3-82d6fc8f014d
* Content: [Publish, select, or unpublish a wiki version - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/project/wiki/wiki-select-unpublish-versions?view=azure-devops)
* Content Source: [docs/project/wiki/wiki-select-unpublish-versions.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/project/wiki/wiki-select-unpublish-versions.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by msebolt** [comment]
@VOVELEE Thank you for the question.

Please refer to the [Azure DevOps timeline](https://docs.microsoft.com/azure/devops/release-notes/features-timeline) for new features currently slated on the release schedule.  

If this feature is missing, provide input to and get feedback from the product team by submitting this as a feature request [here](https://developercommunity.visualstudio.com/content/idea/post.html?space=21).

**Comment by VOVELEE** [comment]
Thanks. 

I already reviewed timeline - there is nothing planned for Git Tagging and wikis.
I have submit feature [request](https://developercommunity.visualstudio.com/idea/854050/enable-azure-devops-wiki-to-support-for-tagging-to.html)
