### ISSUE TITLE
How to retrieve pipeline variable in inline script ?

### ISSUE THREAD

**Issue by bertrandpons** [MicrosoftDocs/vsts-docs#6641]
Hello,

Could you please document how to retrieve pipeline variable in an inline script ?

Thank you !

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1cb6bb80-ad9e-525c-3cae-275955b00919
* Version Independent ID: 79d62477-08d2-f412-d59d-d8cbac75dc32
* Content: [PowerShell task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/powershell?view=azure-devops)
* Content Source: [docs/pipelines/tasks/utility/powershell.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/utility/powershell.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @vtbassmatt
* Microsoft Alias: **macoope**

**Comment by vtbassmatt** [comment]
It's documented [in the variables topics](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch#set-variables-in-pipeline). We take the variable name, uppercase it, and replace all `.` with `_`, then it's set in the environment.
