### ISSUE TITLE
How to retrieve build artifact in release to be consumed with yml file

### ISSUE THREAD

**Issue by bertrandpons** [MicrosoftDocs/vsts-docs#6644]
Hello,

I don't have find any indication on how to be able to retrieve generated build artifact in release pipeline to be deployed, with yaml file. Could you please explain how ?

Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7175ebdc-0bba-7e00-d113-036a5cffe5fa
* Version Independent ID: 149ab9f4-0b7d-97e7-6cf5-1b54fd04c63c
* Content: [Publish and consume build artifacts in builds - Azure Pipelines and TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/build-artifacts?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/artifacts/build-artifacts.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/artifacts/build-artifacts.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @chasewilson
* Microsoft Alias: **phwilson**

**Comment by msebolt** [comment]
@bertrandpons Thank you for the question.

Please refer to https://github.com/MicrosoftDocs/vsts-docs/issues/2341 for an extensive discussion on the subject.

**Comment by bertrandpons** [comment]
@msebolt Thank you for your answer and the link. The thing is that I cannot retrieve my zip file contained in a specific artifact to be deployed with app service deployment task. I tried many combinations to be able to specify the right path to the zip package but I have not found the right way.

Is there a documentation or something to do this very simple step in yaml: publish artifact in build then retrieve its content in release pipeline task?
With the classic editor, it is straightforward!

Thank you

**Comment by bertrandpons** [comment]
@msebolt well actually I have found a way that works: 
I use the task PublishPipelineArtifact@1 on build side with the targetPath set to '$(Build.ArtifactStagingDirectory)'
Then on deployment side, I use the task DownloadPipelineArtifact@2 with buildType set to 'current' and downloadPath set to '$(Build.ArtifactStagingDirectory)'

**Comment by shashban** [comment]
I am glad you were able to resolve the problem.
You can also use [publish](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema#publish) and [download] (https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema#download) macros instead of the complete tasks to the same effect.
Closing this issue now.
