### ISSUE TITLE
Only supported in windows environment

### ISSUE THREAD

**Issue by marcin-vt** [MicrosoftDocs/vsts-docs#6645]
I think it would be nice to add info about this important limtation: it can only be used in windows environment. So people can avoid this error: "The current operating system is not capable of running this task. That typically means the task was written for Windows only.". Or maybe even better add support for linux....

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ef10443a-d321-9965-d841-bedbd054d91d
* Version Independent ID: b30ed4f9-d20b-1dcb-9dff-4d16507a0822
* Content: [Azure SQL Database Deployment task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/sql-azure-dacpac-deployment?view=azure-devops#feedback)
* Content Source: [docs/pipelines/tasks/deploy/sql-azure-dacpac-deployment.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/deploy/sql-azure-dacpac-deployment.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by iamsrivatsa** [comment]
@marcin-vt Thank you for the feedback. The document has been updated and I'll be closing the issue. Thank you for the feedback and feel free to open a new issue if you have any more feedback.
