### ISSUE TITLE
Bad link

### ISSUE THREAD

**Issue by prittelm** [MicrosoftDocs/vsts-docs#6648]
Under Related Topics, the link to "Release pipelines and releases" is incorrect and is currently pointing to the current page (Approvals).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 16b27fd8-df35-5e98-8c6e-2924f541a504
* Version Independent ID: 4c6e6300-2354-a9ec-0cf3-7f935ea268ce
* Content: [Understand approvals and gates - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/approvals/index?view=azure-devops#feedback)
* Content Source: [docs/pipelines/release/approvals/index.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/release/approvals/index.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @shashankbarsin
* Microsoft Alias: **shashban**

**Comment by damccorm** [comment]
Thank you for your feedback - I'm taking a look at this now and will update the doc.

**Comment by damccorm** [comment]
Thank you for your feedback. 
The article reference is being updated to address the issue.
