### ISSUE TITLE
Include Software Link is Broken

### ISSUE THREAD

**Issue by farzadmf** [MicrosoftDocs/vsts-docs#6649]
It seems that the `README` for included software has moved to another repo (`virtual-environments`), but the links are still pointing to `azure-pipelines-image-generation` repo

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 99af681d-41ad-da15-0b72-08b5cd5a11ac
* Version Independent ID: 2fa0df36-a437-8cbb-b019-b49b31b1e116
* Content: [Microsoft-hosted agents for Azure Pipelines - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops#feedback)
* Content Source: [docs/pipelines/agents/hosted.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/agents/hosted.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by mithunshanbhag** [comment]
Yup, all these links are now broken.

![image](https://user-images.githubusercontent.com/2327905/70709510-06897300-1d03-11ea-9c01-39e0d4f8bad0.png)

**Comment by mithunshanbhag** [comment]
I've submitted a PR to fix the broken links. Please merge: https://github.com/MicrosoftDocs/vsts-docs/pull/6653

**Comment by WilliamAntonRohm** [comment]
@farzadmf -- Farzad, thank you for your feedback.

@mithunshanbhag -- Mithun, I appreciate your creating a PR for these.

@steved0x -- Steve, please look into this issue & the corresponding PR.

**Comment by steved0x** [comment]
Thank you for letting us know, I am tracking down the vs2015 link and will get it updated as soon as I find it, and I have approved your PR. Thank you!
