### ISSUE TITLE
Indicate BUILD_SOURCESDIRECTORY and BUILD_REPOSITORY_LOCALPATH are synonymous

### ISSUE THREAD

**Issue by englishmatt** [MicrosoftDocs/vsts-docs#665]
Indicate BUILD_SOURCESDIRECTORY and BUILD_REPOSITORY_LOCALPATH are synonymous.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ffebdc8-521c-44b5-cde4-4abdc1bd6f18
* Version Independent ID: dc0effda-6d93-62aa-64c5-4e6f283b0826
* Content: [Build variables](https://docs.microsoft.com/en-us/vsts/build-release/concepts/definitions/build/variables?view=vsts&tabs=batch)
* Content Source: [docs/build-release/concepts/definitions/build/variables.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/build-release/concepts/definitions/build/variables.md)
* Service: **unspecified**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by andyjlewis** [comment]
Thanks for the suggestion; done.
