### ISSUE TITLE
"Path to solution" does not support the minimatch pattern fully

### ISSUE THREAD

**Issue by FrankHeimes** [MicrosoftDocs/vsts-docs#6654]
The default string for the _Path to solution_ parameter is `**/*.sln`
This creates the impression that this parameter supports the minimatch pattern, but it does not.
Specifically, it does not honor exclude patterns.

E.g. the pattern:  `Main\**\*.sln;-:**\Libs\**` will include all solution files below `Main` but not exclude any in `*\Libs\*`.

The property does accept multiple include patterns, like `Main\???\**\*.sln;Main\Su*\**\*.sln`, though.

The _Visual Studio Test_ task on the other hand does support exactly the aforementioned notation with exclude patterns. It is frustrating to realize that the tasks for TFS build behave so inconsistently.

**Comment by WilliamAntonRohm** [comment]
Frank, it looks like you've encountered an issue with the product itself, rather than an issue with the documentation. To make sure it gets in front of the right people, please [submit your bug]( https://developercommunity.visualstudio.com/content/problem/post.html?space=21) here.
