### ISSUE TITLE
Reference and picture is outdated

### ISSUE THREAD

**Issue by ctahok** [MicrosoftDocs/vsts-docs#6655]
The page says "Choose (1) Project Settings, choose (2) GitHub connections", well there is no GitHub Connections under Project Settings.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 04afcda8-8a01-6fda-8387-778feaba9fea
* Version Independent ID: a0c518ee-dc43-42a6-07d9-150dfa8724c3
* Content: [Connect a project to a GitHub repository - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/github/connect-to-github?view=azure-devops#feedback)
* Content Source: [docs/boards/github/connect-to-github.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/boards/github/connect-to-github.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@ctahok - What version of Azure DevOps are you working from? This feature is only supported for the cloud and Azure DevOps Server 2019. To learn which on-premises version you are using, see [What platform/version am I using?](https://docs.microsoft.com/en-us/azure/devops/user-guide/provide-feedback#platform-version)

If you are on one of these platforms, then please reach out to our support web site: [Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html).

**Comment by ctahok** [comment]
Judging by Prerequisites which lists both "azure-devops-2019" & "azure-devops" I have had an impression that the article is valid for both. It appears it is valid for Azure DevOps server but not Azure DevOps services which I am using. Please clarify this to avoid further confusions.
