### ISSUE TITLE
Capabilities Tab does not show system capabilities

### ISSUE THREAD

**Issue by chrisevans9629** [MicrosoftDocs/vsts-docs#6657]
The capabilities tab no longer shows the system capabilities.  Where can I see the capabilities of an agent that are not user capabilities?  This doc is not accurate in this respect.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 47625b86-abd5-ee15-6d61-8bcf81861b96
* Version Independent ID: be9a6174-a69b-7aed-d584-5f602fcc5eb4
* Content: [Azure Pipelines Agents - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/agents?view=azure-devops&tabs=browser#feedback)
* Content Source: [docs/pipelines/agents/agents.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/agents/agents.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by chrisevans9629** [comment]
![image](https://user-images.githubusercontent.com/33850520/70720229-08c6df80-1cb9-11ea-8df0-141c4eea9282.png)

**Comment by steved0x** [comment]
I'm taking a look, thank you for letting us know.

**Comment by steved0x** [comment]
@chrisevans9629 You can see all the software that is installed on the Microsoft-hosted agents here:

https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops#use-a-microsoft-hosted-agent

I am finding out why that info is removed from the Capabilites tab in the Agent settings (is it a glitch or is it gone, but maybe displayed elsewhere?)

I will report back as soon as I have more info. Thank you, Steve

**Comment by chrisevans9629** [comment]
The links to the included software seem to be broken, for example:
https://github.com/Microsoft/azure-pipelines-image-generation/blob/master/images/macos/macos-10.14-Readme.md

**Comment by steved0x** [comment]
Found them, will have the links updated shortly, here is the page for macos10.14

https://github.com/actions/virtual-environments/blob/master/images/macos/macos-10.14-Readme.md

**Comment by steved0x** [comment]
OK found them all except for VS2015, will get that added shortly. Ont he Agent Pools page, system capabilities are displayed for Self-hosted agents, but system capabilities are not used for Hosted agents and so are not displayed. I have updated the documentation to cover this. As soon as I get the link for VS2015 I will get this published. Thank you for letting us know!
