### ISSUE TITLE
Build options for YAML

### ISSUE THREAD

**Issue by jimicze** [MicrosoftDocs/vsts-docs#6658]
We shifted our builds to YAML def, but the options tab is gone. How can i define creating workitem after build fails?? (e.g. bug) Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 521b594c-dbb9-54d5-f56f-00e2f5fa1d92
* Version Independent ID: 509d3e4e-23db-8493-e1a6-acb67ec47e81
* Content: [Customize your pipeline - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/customize-pipeline?view=azure-devops)
* Content Source: [docs/pipelines/customize-pipeline.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/customize-pipeline.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @vijayma
* Microsoft Alias: **vijayma**

**Comment by jimlamb** [comment]
I'm working on this one.

**Comment by WilliamAntonRohm** [comment]
@vijayma -- Vijay, please look into the above-mentioned PR.
