### ISSUE TITLE
Demands for Azure File Copy task is incorrect

### ISSUE THREAD

**Issue by Gary-Peluso** [MicrosoftDocs/vsts-docs#6659]
The Demands section of the Azure File Copy task documentation says none.  But the task will require the "azureps" capability on the agent.  

https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-file-copy?view=azure-devops

**Comment by msebolt** [comment]
@Gary-Peluso Thank you for the feedback, assigning this to the author for review.

**Comment by RoopeshNair** [comment]
@ninallam
