### ISSUE TITLE
Is this supported on Azure Devops Server 2019 or not?

### ISSUE THREAD

**Issue by nadcraker** [MicrosoftDocs/vsts-docs#6660]
We are running Devops Server 2019, on prem. When I try and use this task I get the following error: "##[error]Failed to get artifact tool. Universal Packages are not supported in Azure DevOps Server."

This page however says that this task can be run on "Azure Pipelines | Azure DevOps Server 2019 | TFS 2018"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b934d9e8-d417-1f45-dc87-e0dc25219c97
* Version Independent ID: 14bbdf7d-0608-f517-3b10-26d0e83eca85
* Content: [Universal Package, download and publish task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/package/universal-packages?view=azure-devops)
* Content Source: [docs/pipelines/tasks/package/universal-packages.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/package/universal-packages.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @chasewilson
* Microsoft Alias: **phwilson**

**Comment by msebolt** [comment]
@nadcraker Thank you for the feedback.

This feature is still in the process of being released as per [this thread](https://developercommunity.visualstudio.com/content/problem/447345/universal-package-publish-support-for-devops-serve.html).  

Please refer there for updates and/or create a new thread for the product team to address in the [Azure DevOps community](https://developercommunity.visualstudio.com/spaces/21/index.html).
