### ISSUE TITLE
Typo - Web.Contents

### ISSUE THREAD

**Issue by abby-d-chr** [MicrosoftDocs/vsts-docs#6662]
Typo in https://docs.microsoft.com/en-us/azure/devops/report/powerbi/data-connector-functions?view=azure-devops#vstsaccountcontents
The second paragraph says Web.Concents when it should say Web.Contents.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dbdc5841-fa63-c6df-8b26-90f05ffb6210
* Version Independent ID: dba4d2b1-7f7f-adeb-d8f3-f25a97c10093
* Content: [Connect using Power Query & Azure DevOps functions - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/report/powerbi/data-connector-functions?view=azure-devops#vstsaccountcontents)
* Content Source: [docs/report/powerbi/data-connector-functions.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/report/powerbi/data-connector-functions.md)
* Product: **devops**
* Technology: **devops-analytics**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by msebolt** [comment]
@abby-d-chr Thank you for the feedback.

We'll get the documentation updated shortly.
