### ISSUE TITLE
Some icons not loading

### ISSUE THREAD

**Issue by NenoLoje** [MicrosoftDocs/vsts-docs#6664]
Some icons on this page do not load correctly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c00c80cb-e1fa-8af1-25a7-0e1fd679b879
* Version Independent ID: 51baa23d-66da-3d19-ddc7-56c101e9e09d
* Content: [Feature overview for Azure DevOps - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/user-guide/alm-devops-features?view=azure-devops#feedback)
* Content Source: [docs/user-guide/alm-devops-features.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/user-guide/alm-devops-features.md)
* Product: **devops**
* Technology: **devops-new-user**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by NenoLoje** [comment]
Screenshot:

![grafik](https://user-images.githubusercontent.com/13981145/70759348-5e959900-1d46-11ea-91b3-191b773c357d.png)

**Comment by msebolt** [comment]
@NenoLoje Thank you for the feedback.

We'll get the document updated shortly.

**Comment by chcomley** [comment]
@NenoLoje I've just published a fix. Thanks so much for the heads up!
