### ISSUE TITLE
Add next step after creating the image

### ISSUE THREAD

**Issue by jeanpoelie** [MicrosoftDocs/vsts-docs#6669]
Create the next step to use Releases to deploy your newly made image to kubernetes cluster.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45ba2ebe-27c4-111b-18b4-0192d8c3fb3a
* Version Independent ID: f48fdf00-e04f-b406-93f3-20b7fad568be
* Content: [Build and push to Azure Container Registry - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/ecosystems/containers/acr-template?view=azure-devops#feedback)
* Content Source: [docs/pipelines/ecosystems/containers/acr-template.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/ecosystems/containers/acr-template.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @shashankbarsin
* Microsoft Alias: **shasb**

**Comment by shashankbarsin** [comment]
While the documentation on using setting up release pipelines is available piecemeal (different release constructs documented under various concept docs), please find below the [how-to guide](https://docs.microsoft.com/azure/devops/pipelines/ecosystems/kubernetes/canary-demo?view=azure-devops#setup-continuous-deployment) leveraging release pipelines on setting up canary deployments on Kubernetes clusters.
