### ISSUE TITLE
This document should be marked as deprecated.

### ISSUE THREAD

**Issue by PhilBrammer** [MicrosoftDocs/vsts-docs#667]
The TFS Warehouse Build details/coverage is only applicable for XAML builds, which have been marked as deprecated in TFS 2018+.  If you've moved away from XAML builds, you will not find any details in the TFS Warehouse for builds.

https://visualstudio.uservoice.com/forums/330519-visual-studio-team-services/suggestions/18472516-vnext-builds-data-should-be-transferred-to-the-cub

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fd55f984-23fe-fbe6-3b1f-e86c0f45d6e7
* Version Independent ID: aed7d929-f803-eae7-96c2-55f28f84e765
* Content: [Analyze and report on build details and build coverage - TFS](https://docs.microsoft.com/en-us/vsts/report/sql-reports/perspective-build-analyze-report-build-details-coverage?view=tfs-2018)
* Content Source: [docs/report/sql-reports/perspective-build-analyze-report-build-details-coverage.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/report/sql-reports/perspective-build-analyze-report-build-details-coverage.md)
* Service: **unspecified**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@PhilBrammer - Thank you for your comment. I've updated the topic you mention and several other topics with a note to reflect the fact that select reports, tables, and perspectives/measures are no longer supported for TFS 2018 as they rely on XAML builds.

**Comment by livioos** [comment]
What about support build new definitions (not in XAML) in Analysis Service? Are you planninng to correct it?
