### ISSUE TITLE
Bash Script Task run as if my Linux VM is a Windows machine

### ISSUE THREAD

**Issue by JasonAtallah** [MicrosoftDocs/vsts-docs#6678]
I have a Linux VM that I am trying to deploy to using a Bash Script task. Why is it trying to run Window's commands?

![image](https://user-images.githubusercontent.com/24923418/70853637-d4e0eb00-1e6d-11ea-8833-8b8241b34224.png)

**Comment by WilliamAntonRohm** [comment]
@JasonAtallah -- Thanks for your feedback; we appreciate it. To make sure we have all the information needed to triage your issue, please let us know which topic you’re referencing, or provide more context around the general task.
