### ISSUE TITLE
GVFS Architecture page is titled "Technical Scale Challenges with Git" in sidebar/outline

### ISSUE THREAD

**Issue by derrickstolee** [MicrosoftDocs/vsts-docs#668]
These do not match. Probably should use "Git Virtual File System Architecture" in the sidebar as it is more accurate.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 49c37596-91af-710a-5465-e4211f0b2819
* Version Independent ID: 40a52f21-cdcc-615f-d9e8-58be9ef9c059
* Content: [Git Virtual File System Architecture - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/git/gvfs-architecture)
* Content Source: [https://mseng.visualstudio.com/DefaultCollection/TechnicalContent/_git/devops-learn-pr?path=%2fdocs%2fgit%2fgvfs-architecture.md&version=GBlive&_a=contents](https://mseng.visualstudio.com/DefaultCollection/TechnicalContent/_git/devops-learn-pr?path=%2fdocs%2fgit%2fgvfs-architecture.md&version=GBlive&_a=contents)
* Service: **unspecified**
* GitHub Login: @samgu
* Microsoft Alias: **sanoursa**

**Comment by steved0x** [comment]
@derrickstolee I'll get that fixed, thanks for letting us know!

**Comment by steved0x** [comment]
@derrickstolee I just merged in the fix and it should be live soon, thanks again for letting us know.
