### ISSUE TITLE
#6643 still not fixed - strategy still appears to be an option in environment.

### ISSUE THREAD

**Issue by a30001539** [MicrosoftDocs/vsts-docs#6687]
Previous issue people thought the issue was with _my_ YAML, not the YAML in the doco.

This issue is with the YAML in the doco.

It seems that the link at [YAML schema reference - Environment](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema#environment) indicates that "strategy" is a valid child element of "environment". This will cause an error. In the image below, from the incorrect doco, the "strategy" element is indented one level too far.

![image](https://user-images.githubusercontent.com/49630705/70897240-57bc9e00-2046-11ea-876b-d79a88a60e6b.png)

**Comment by iamsrivatsa** [comment]
The document has been updated and I'll be closing the issue. Thank you for the feedback and feel free to open a new issue if you have any more feedback.
