### ISSUE TITLE
Tip: "Type f to move your cursor to the filter box " incorrect, shortcut does not work

### ISSUE THREAD

**Issue by SamHasler** [MicrosoftDocs/vsts-docs#6688]
It looks like the shortcut documented by the Tip starting "Type f to move your cursor to the filter box" does not work.

Per this page: https://docs.microsoft.com/en-us/azure/devops/boards/boards/kanban-board-keyboard-shortcuts?view=azure-devops

it should be "Ctrl+Shift+f"

Also, the text "To move the focus up or down within a column, enter the up/down arrows. " appears to be incorrect. CTRL +Shift +f places the cursor in the filter text input. (You can press Tab to the move the focus to the filter drop downs)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b5017884-bcc0-3fa7-6bfd-73bb04ab7524
* Version Independent ID: cadea453-739a-6498-268a-ad3391a4f65b
* Content: [Filter your Kanban board - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/boards/filter-kanban-board?view=azure-devops#feedback)
* Content Source: [docs/boards/boards/filter-kanban-board.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/boards/boards/filter-kanban-board.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by msebolt** [comment]
@SamHasler  Thank you for the feedback.

The documentation has been updated and is pending review.
