### ISSUE TITLE
Release run condition for skipped tasks

### ISSUE THREAD

**Issue by cordialamit** [MicrosoftDocs/vsts-docs#6692]
Hi,

I have azure dev ops release which has multiple steps which are hooked with each other. Each task has "Run only if all previous steps are successful" condition. However if someone directly executes given step then it should fail since previous step was not executed.

Can you provide guidance on how to enforce this automatically.

**Comment by msebolt** [comment]
@cordialamit Thank you for the question.

For now, you would need to use a custom [condition](https://docs.microsoft.com/azure/devops/pipelines/process/conditions) that is only set to **true** by the first task in the sequence.

For built-in automation, please direct this to the product team [here](https://developercommunity.visualstudio.com/spaces/21/index.html).
