### ISSUE TITLE
Mac Included Software

### ISSUE THREAD

**Issue by tboniger** [MicrosoftDocs/vsts-docs#6693]
The link for "Included Software" on mac is broken. Someone removed the readme files in Github.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 99af681d-41ad-da15-0b72-08b5cd5a11ac
* Version Independent ID: 2fa0df36-a437-8cbb-b019-b49b31b1e116
* Content: [Microsoft-hosted agents for Azure Pipelines - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops#feedback)
* Content Source: [docs/pipelines/agents/hosted.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/agents/hosted.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by IhorLeontiev** [comment]
Actually it was deleted with commit: https://github.com/actions/virtual-environments/commit/51964b2bf08632829a163829f191e9dd0e73b72a#diff-4394d8548d8c9fe8cfb040b0b1a76dff
As no relevant to Github Actions
But you can always access to the old version of file https://github.com/actions/virtual-environments/blob/51d02f26f42e53bb963bb6bc9754501b28a3d2ba/images/macos/macos-10.13-Readme.md

**Comment by jfro** [comment]
I was just trying to view this as well. I'm confused as to why this is removed... isn't it still relevant to DevOps at least? Also why wouldn't it be relevant to actions? Both have mac agents, so there going to be a different page with updated info or something?

**Comment by msebolt** [comment]
@tboniger Thank you for the feedback, assigning this to the author for review.

@shadyysf  Are these images no longer supported?

**Comment by shadyysf** [comment]
@msebolt, sorry for the confusion. The 10.13 and 10.14 readme files live in the old azure-pipelines-image-generation repository since they don't ship to Actions(https://github.com/microsoft/azure-pipelines-image-generation/tree/master/images/macos). The readme file for 10.15 which does ship in Actions lives in the virutal-enviornments repository (https://github.com/actions/virtual-environments/tree/master/images/macos).

**Comment by msebolt** [comment]
@shadyysf  No problem, thanks for clarifying.  I'll go ahead and update the documentation links.

**Comment by msebolt** [comment]
The documentation has been updated and is pending review.
