### ISSUE TITLE
remove the use of non-industry acronyms for public facing documentation 

### ISSUE THREAD

**Issue by awentzel** [MicrosoftDocs/vsts-docs#6694]
WIT's isn't a common industry term.  I had to search up in the page to figure out what that acronym meant.  I understand, it simplifies the word count when documenting by those that are intimately familiar with the documentation.  But, for customers, I'd recommend not abbreviating and just saying "work item types" in writing to save the majority of those reading this documentation time. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b3466d1-72cc-2d47-d98b-7029639c0f79
* Version Independent ID: 4ff82210-6b5a-589d-261e-1ddbd3007e2a
* Content: [Choose a process like Basic, Agile, Scrum, or CMMI - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/work-items/guidance/choose-process?view=azure-devops&tabs=agile-process#feedback)
* Content Source: [docs/boards/work-items/guidance/choose-process.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/boards/work-items/guidance/choose-process.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by msebolt** [comment]
@awentzel Thank you for the feedback, assigning this to the author for review.

**Comment by KathrynEE** [comment]
@awentzel - Thank you for the feedback. I'm the author of the work tracking content for Azure DevOps. Using acronyms, whether common in the industry or not, is always problematic. I do work to introduce an acronym early on in a topic by spelling it out in each topic where it appears. The WIT acronym is used throughout the work tracking content, and won't be updated to be removed any time soon. But thank you for the input.
