### ISSUE TITLE
Get raw content of a file in ADO

### ISSUE THREAD

**Issue by ata18** [MicrosoftDocs/vsts-docs#6695]
``` 
pat=":PAT"
encoded_user_pat=$(echo $pat | tr -d '\n' | base64)
curl -I -L -H "Content-Type:application/json" -H "Authorization: Basic $encoded_user_pat" https://dev.azure.com/AZGlobal/Magna%20Carta/_git/fluo-muchos?path=%2Fpipelines%2Foverrides%2Fmuchos-overrides-19-lvm&_a=content
```
This returns HTTP/1.1 200 OK. But on removing `-I` flag, the raw content is not returned. What is the correct way to get the raw content of a file in ADO. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 53f99d2d-363b-d01d-039d-4fdc636fa2df
* Version Independent ID: f47330d5-e2de-36a4-e5b3-5bc77505b161
* Content: [Authenticate with personal access tokens - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/use-personal-access-tokens-to-authenticate?view=azure-devops&tabs=preview-page)
* Content Source: [docs/organizations/accounts/use-personal-access-tokens-to-authenticate.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/accounts/use-personal-access-tokens-to-authenticate.md)
* Product: **devops**
* Technology: **devops-security**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by ata18** [comment]
Is there a `github gist` like feature available for ADO?

**Comment by msebolt** [comment]
@ata18  Thank you for the question.

Could it be perhaps the requested resource doesn't return content?

Does the example `curl -u username[:{personalaccesstoken}] https://dev.azure.com/{organization}/_apis/build-release/builds` return content as stated in the topic?

**Comment by ata18** [comment]
This doesn't work either.

**Comment by chcomley** [comment]
Hi @ata18, 

Here's a more appropriate article for downloading a file: https://docs.microsoft.com/en-us/rest/api/azure/devops/git/items/get?view=azure-devops-rest-5.1#download

Let me know if you have any further questions by @mentioning me. Thanks!

**Comment by ata18** [comment]
```
curl -H "Authorization: Basic $encoded_user_pat" https://dev.azure.com/AZGlobal/Magna%20Carta/_apis/git/repositories/b7389187-96c1-4210-9df5-048463f75903/items?scopePath=/pipelines/overrides/muchos-overrides-19-lvm
```
This works. Thanks!
