### ISSUE TITLE
How to set it up for the iOS app with extensions?

### ISSUE THREAD

**Issue by dev4jam** [MicrosoftDocs/vsts-docs#6696]
https://docs.microsoft.com/en-us/azure/devops/pipelines/apps/mobile/app-signing?view=azure-devops&tabs=apple-install-during-build#apple

I have an app with multiple extensions. I have several InstallAppleProvisioningProfile@1 tasks to import all provision profiles. But when I run Xcode@5 task there is only one provision profile field available.

Please assist in solving this issue.

**Comment by msebolt** [comment]
@dev4jam Thank you for the question.

Perhaps setting the `xcWorkspacePath` can solve this issue?

See [here](https://stackoverflow.com/questions/53225705/azure-devops-pipelines-xcode-project-with-multiple-provisioning-profiles-fails) for more information.
