### ISSUE TITLE
Provide information how to switch to organizations across multiple tenants

### ISSUE THREAD

**Issue by soutchilin** [MicrosoftDocs/vsts-docs#6699]
It is difficult to find the URL below. The information to the personal account (https://account.activedirectory.windowsazure.com/r/#/profile) shows the tenants only (misleadingly calling them organizations). The organizations inside of the tenants are not shown at all. So you need the following URL: https://app.vsaex.visualstudio.com/me?mkt=en-US There you see tenants, in each of the tenant its organizations and inside of the organizations the projects.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 01770b43-fd5b-efbc-36f5-af91a3c8cf5a
* Version Independent ID: 7c046a91-37f9-32e3-dc3e-dfa922c456be
* Content: [Plan your organizational structure - Azure DevOps - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/user-guide/plan-your-azure-devops-org-structure?toc=%2Fazure%2Fdevops%2Forganizations%2Ftoc.json&bc=%2Fazure%2Fdevops%2Forganizations%2Fbreadcrumb%2Ftoc.json&view=azure-devops)
* Content Source: [docs/user-guide/plan-your-azure-devops-org-structure.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/user-guide/plan-your-azure-devops-org-structure.md)
* Product: **devops**
* Technology: **devops-new-user**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by msebolt** [comment]
@soutchilin Thank you for the feedback, assigning this to the author for review.

**Comment by chcomley** [comment]
Hi @soutchilin, 

Go here for more information: [Change Azure AD Connection](https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/change-azure-ad-connection?view=azure-devops)

I'll also provide a link to this information within this article.

Please @mention me if you have any further feedback or questions. Thanks again!
