### ISSUE TITLE
Broken links for macOS 

### ISSUE THREAD

**Issue by janten** [MicrosoftDocs/vsts-docs#6701]
The macOS Included Software links in [hosted.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/agents/hosted.md](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops)) currently point to [github.com/actions/virtual-environments](https://github.com/actions/virtual-environments/blob/master/images/macos/). The path _images/macos/_ does not exist in that repository.

Earlier version linked to a different repository, [github.com/Microsoft/azure-pipelines-image-generation](https://github.com/Microsoft/azure-pipelines-image-generation/), which does contain the path but not the relevant files.

As a result, detailed information on the hosted agents for macOS is nowhere to be found.

**Comment by msebolt** [comment]
@janten  Thank you for the feedback.

This issue was reported earlier in https://github.com/MicrosoftDocs/vsts-docs/issues/6693, please refer there for further updates.
