### ISSUE TITLE
Can branch policies be inherited?

### ISSUE THREAD

**Issue by abelfiore** [MicrosoftDocs/vsts-docs#6702]
Can a branch inherit its policies from its parent? If so, how?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7cd986e0-608c-1d8c-6faf-ecdb12e10bc6
* Version Independent ID: d60c996e-187e-dd6b-7f3a-dd056a1603f4
* Content: [Protect your Git branches with policies - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/branch-policies?view=azure-devops#where-can-i-get-more-information-on-advanced-policy-configurations)
* Content Source: [docs/repos/git/branch-policies.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/repos/git/branch-policies.md)
* Product: **devops**
* Technology: **devops-code-git**
* GitHub Login: @apawast
* Microsoft Alias: **sdanie**

**Comment by msebolt** [comment]
@abelfiore Thank you for the feedback.

This issue is currently an open item found [here](https://developercommunity.visualstudio.com/idea/365671/inherit-branch-policies-from-parent-branch.html) in the **Azure DevOps community**.

Please refer there for further updates and/or to add feedback.
