### ISSUE TITLE
Documentation about Scheduled pipelines are incomplete

### ISSUE THREAD

**Issue by verschaevesiebe** [MicrosoftDocs/vsts-docs#6704]
The documentation around Scheduled pipelines don't define the fact that you also have to put a trigger and pr in order to make it Scheduled only.

trigger: none       //if not provided commits also trigger your pipeline.
pr: none              //if not provided pull requests also trigger your pipeline.
schedules: ......

Please make sure to add the preffered documentation including the above.
I personally ran into the issue that the pipeline kept triggering.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5673ec1-c7d1-e0ac-043a-8fc3d5b226a9
* Version Independent ID: b4872831-51c0-6cf8-1c56-de20beb38a80
* Content: [Build pipeline triggers - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/triggers?view=azure-devops&tabs=yaml#feedback)
* Content Source: [docs/pipelines/build/triggers.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/build/triggers.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by msebolt** [comment]
@verschaevesiebe Thank you for the feedback, assigning this to the author for review.

**Comment by steved0x** [comment]
@verschaevesiebe I'll get that clarification added, sorry that you ran into trouble, and thanks for letting us know.
