### ISSUE TITLE
An example of how to actually use these would be nice.

### ISSUE THREAD

**Issue by StingyJack** [MicrosoftDocs/vsts-docs#6705]
.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f8b4989-21f0-53c5-dfce-6d5f1a66b8b2
* Version Independent ID: 2f4419a7-408b-40cd-9190-985a9976d556
* Content: [Authenticate with your Git repos - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/auth-overview?view=azure-devops)
* Content Source: [docs/repos/git/auth-overview.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/repos/git/auth-overview.md)
* Product: **devops**
* Technology: **devops-code-git**
* GitHub Login: @apawast
* Microsoft Alias: **apawast**

**Comment by StingyJack** [comment]
Now I'm blocked for some unknown time period because MSFT cant be bothered to finish a doc, and I have to either hack or do research. 

Again. Real tired of this. I have actual work that needs to be done and I dont need to be spending time hacking at this BS.

**Comment by StingyJack** [comment]
This is where I found how to use the PAT. A link to this page would be appropriate.

https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/use-personal-access-tokens-to-authenticate?view=azure-devops&tabs=preview-page#use-your-personal-access-token

**Comment by msebolt** [comment]
@StingyJack Thank you for the feedback.

We'll get the document updated shortly.

**Comment by msebolt** [comment]
A link is now included in the document:

![Capture](https://user-images.githubusercontent.com/6675884/72128513-08f1e380-3328-11ea-9144-1cc0d032aac1.PNG)

Closing the issue now.
