### ISSUE TITLE
Does WIQL support Alias name as in SQL ?

### ISSUE THREAD

**Issue by Eldadc** [MicrosoftDocs/vsts-docs#6707]
Hi,

Does WIQL support Alias name as in SQL ?
SQL aliases are used to give a table, or a column in a table, a temporary name.

SELECT column_name AS alias_name
FROM table_name;

Thanks

**Comment by msebolt** [comment]
@Eldadc Thank you for the question.

It is unlikely the feature is supported at this time, please move this to the [Azure DevOps community](https://developercommunity.visualstudio.com/spaces/21/index.html) for feedback from the product team.

For additional support options, see:

- [Azure DevOps Support](https://azure.microsoft.com/support/devops/)
- [Azure DevOps on StackOverflow](https://stackoverflow.com/questions/tagged/azure-devops)

**Comment by adithyasai** [comment]
Any update on this?

**Comment by msebolt** [comment]
@adithyasai Thank you for the question.

All existing WIQL features are currently documented, you'll need to either add this as a new issue for the product team to address or comment on [this open JOIN functionality post](https://developercommunity.visualstudio.com/idea/881828/support-join-and-subqueries-in-wiql.html) to include aliasing.
