### ISSUE TITLE
extension publish PAT rights?

### ISSUE THREAD

**Issue by A-AontwSR** [MicrosoftDocs/vsts-docs#6709]
What rights are needed in the PAT for "tfx extension publish"? This page is only mentioning "You'll need a personal access token, too." Please add a description or link with more info.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 44581f4a-93df-7507-3844-eadedf9a6cc4
* Version Independent ID: 33c7bcf0-1512-975f-5ef8-9f2a192a84ad
* Content: [Add a Build or Release Task - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/extend/develop/add-build-task?view=azure-devops#feedback)
* Content Source: [docs/extend/develop/add-build-task.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/extend/develop/add-build-task.md)
* Product: **devops**
* Technology: **devops-ecosystem**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by msebolt** [comment]
@A-AontwSR Thank you for the feedback, assigning this to the author for review.

**Comment by chcomley** [comment]
Hi @A-AontwSR, 

Here's a link to [more information about PATs](https://docs.microsoft.com/en-us/azure/devops/extend/publish/command-line?view=azure-devops#acquire-a-personal-access-token). I've added a link to more info within the article as well. 

Thanks for your feedback! Please @mention me if you have any further questions.

**Comment by A-AontwSR** [comment]
Hi @chcomley ,
Thanks for the link with more information, that is excactly what i needed 👍.
But I can not find a link to this info in the article on https://docs.microsoft.com/en-us/azure/devops/extend/develop/add-build-task?view=azure-devops#upload-your-extension

**Comment by chcomley** [comment]
Hi @A-AontwSR, I'm so glad you got what you needed. I hadn't signed off on my PR, so it didn't get completed until just now, which is why you couldn't see the new link within the article. :) Thank you!
