### ISSUE TITLE
can this task build a war?

### ISSUE THREAD

**Issue by HughDevlin** [MicrosoftDocs/vsts-docs#6714]
In the Auto Detect Logic section, the War deploy subsection reads "Creates a .war deployment package..." This makes this task the Azure App Service Deploy task sound like a build-type task rather than a deploy-type task. Meanwhile, the Package parameter is described as requiring a path to a war file. Unclear, does this task build a war or move a war from a build environment to a deployed environment?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 29c94df7-9de9-ea1a-8b77-d1e6023694dc
* Version Independent ID: a525989e-2e0a-0399-556e-9011ee95da4e
* Content: [Azure App Service Deploy task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-rm-web-app-deployment?view=azure-devops#usage-notes)
* Content Source: [docs/pipelines/tasks/deploy/azure-rm-web-app-deployment.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/deploy/azure-rm-web-app-deployment.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by RoopeshNair** [comment]
@HughDevlin - Thanks for reporting this. No, this task doesn't create *.war, it expects *.war file as an input. Will get the docs udpated

**Comment by iamsrivatsa** [comment]
The document has been updated and I'll be closing the issue. Thank you for the feedback and feel free to open a new issue if you have any more feedback.
