### ISSUE TITLE
Mermaid Markdown Inconsistent with Common Practice

### ISSUE THREAD

**Issue by justrhysism** [MicrosoftDocs/vsts-docs#6717]
So the docs state that Mermaid can be used using the Wiki's three-colon invocation `:::`. But this goes against the common practice of placing Mermaid markdown syntax inside backticks `\`\`\``:

- https://github.com/temando/remark-mermaid
- https://docs.gitlab.com/ee/user/markdown.html#mermaid
- https://markdownmonster.west-wind.com/docs/_5ef0x96or.htm
- https://www.mweb.im/markdown.html#toc_19

Using VSCode, there are [mermaid extensions](https://marketplace.visualstudio.com/items?itemName=bierner.markdown-mermaid) which provide live markdown previews of the mermaid charts, but they require the standard practice of using backticks.

At the very least, please support both syntaxes.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 29f1e43f-a069-dd88-7fc7-9cc497fb94f0
* Version Independent ID: c261afa7-6eb7-b3f0-9f92-6d2f3c5ac336
* Content: [Markdown syntax for wikis in Azure DevOps - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/project/wiki/wiki-markdown-guidance?view=azure-devops#feedback)
* Content Source: [docs/project/wiki/wiki-markdown-guidance.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/project/wiki/wiki-markdown-guidance.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by msebolt** [comment]
@justrhysism Thank you for the feedback.

Please note to resolve issues in this forum, we can only make changes to the working documentation.  

For product issues and/or feature requests, please move the issue [here](https://developercommunity.visualstudio.com/spaces/22/index.html) for updates from the product team.

**Comment by msebolt** [comment]
Closing the issue now, please comment below if there are any questions.
