### ISSUE TITLE
specify extension/{id} in demands is not working

### ISSUE THREAD

**Issue by zkbule** [MicrosoftDocs/vsts-docs#6718]
![image](https://user-images.githubusercontent.com/13895180/71047096-58f5d580-20ef-11ea-843f-56539c532e2f.png)

**Comment by zkbule** [comment]
![image](https://user-images.githubusercontent.com/13895180/71047172-99555380-20ef-11ea-82fd-a13f2b95abe1.png)

**Comment by WilliamAntonRohm** [comment]
@zkbule -- Thanks for your feedback; we appreciate it. To make sure we have all the information needed to triage your issue, please let us know which topic you’re referencing, or provide more context around the general task.
