### ISSUE TITLE
Suggestion: add note that this is not a complete tutorial

### ISSUE THREAD

**Issue by dbiehle** [MicrosoftDocs/vsts-docs#672]
Like in between the "Add the custom endpoint contribution" json text and the "If you have successfully added the service contribution correctly,...", insert one of those blue-shaded note sections that says something like: "This is what your endpoint will look like after you've packaged and published your extension. See the Next Steps section below."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 90db6e4c-6240-fe2e-3043-0a7d186b9ca7
* Version Independent ID: a62ec500-3330-e28a-8019-118a3b9e261f
* Content: [Service Endpoints](https://docs.microsoft.com/en-us/vsts/extend/develop/service-endpoints?view=vsts)
* Content Source: [docs/extend/develop/service-endpoints.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/extend/develop/service-endpoints.md)
* Service: **unspecified**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by elbatk** [comment]
@dbiehle Ah thanks for this. This article shouldn't be worded as a tutorial, I'll add this in today!
