### ISSUE TITLE
Specifying version (tag, branch) when triggering a pipeline

### ISSUE THREAD

**Issue by woutervanvliet** [MicrosoftDocs/vsts-docs#6722]
Is it now also possible to specify what version to checkout when triggering a pipeline? 

I imagine it's possible to use variables for any of the configuration properties, but a regular variable just gives you a freetext field. Having a dropdown where one can select a valid branch or tag would be very nice (similar to how build artifacts are selected when triggering a release. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a0499c0-bd1c-47a0-b472-54a5d6c159b4
* Version Independent ID: ec3feae0-4f23-68ab-6307-75fde645468a
* Content: [Check out multiple repositories in your pipeline - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/multi-repo-checkout?view=azure-devops#feedback)
* Content Source: [docs/pipelines/repos/multi-repo-checkout.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/repos/multi-repo-checkout.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by msebolt** [comment]
@woutervanvliet Thank you for the question and feedback.

You can refer to some issues involving the use of variables posted [here](https://developercommunity.visualstudio.com/idea/388532/specify-variables-with-release-trigger.html) and [here](https://developercommunity.visualstudio.com/content/problem/212251/configuration-of-build-definition-variables-on-sch.html).

Please note that feature requests are better geared towards the product team and should be moved to the [Azure DevOps community](https://developercommunity.visualstudio.com/spaces/22/index.html) for direct feedback on feasibility and future availability.

**Comment by msebolt** [comment]
Closing the issue now, please comment below if there are any questions.
