### ISSUE TITLE
How can a developer find messages between reviewer and developer for future reference?

### ISSUE THREAD

**Issue by fordunka** [MicrosoftDocs/vsts-docs#6723]
The messages that are code and block specific don't seem to be easily retrievable using Azure Devops tool.   I need to see what those comments are from time to time without having to dig through emails to find the pertinent review.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6e0d4140-d512-8c58-0f35-dac14e355cdf
* Version Independent ID: b1dc4511-a1f5-0b0e-1af0-9bc2b177fb35
* Content: [Suspend work, fix a bug, and conduct a code review - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/tfvc/day-life-alm-developer-suspend-work-fix-bug-conduct-code-review?view=azure-devops#feedback)
* Content Source: [docs/repos/tfvc/day-life-alm-developer-suspend-work-fix-bug-conduct-code-review.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/repos/tfvc/day-life-alm-developer-suspend-work-fix-bug-conduct-code-review.md)
* Product: **devops**
* Technology: **devops-code-tfvc**
* GitHub Login: @apawast
* Microsoft Alias: **sdanie**

**Comment by msebolt** [comment]
@fordunka Thank you for the feedback.

Please see if [this post](https://developercommunity.visualstudio.com/idea/365924/search-filter-commit-messages.html) addresses your issue.

Else, you will need to start a new thread with the product team [here](https://developercommunity.visualstudio.com/spaces/21/index.html).

**Comment by msebolt** [comment]
Closing the issue now, please comment below if there are any questions.
