### ISSUE TITLE
Deleted runs still show up in pipeline reports

### ISSUE THREAD

**Issue by ata18** [MicrosoftDocs/vsts-docs#6726]
Is it possible to remove deleted runs from pipeline reports?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2da4714e-d931-6777-d8be-b123a2b0fa17
* Version Independent ID: 09eec061-51ab-e6a9-e61c-0b6f618cd969
* Content: [Pipeline reports - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/reports/pipelinereport?view=azure-devops)
* Content Source: [docs/pipelines/reports/pipelinereport.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/reports/pipelinereport.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by msebolt** [comment]
@ata18 Thank you for the feedback.

Please see if either [this post](https://developercommunity.visualstudio.com/idea/715299/azure-devops-pipeline-reports-custom-metrics.html) or [this post](https://developercommunity.visualstudio.com/idea/807720/allow-the-ui-to-delete-test-runs.html) addresses the issue.

Else, please move the issue [here](https://developercommunity.visualstudio.com/spaces/22/index.html) for a response from the product team.

**Comment by msebolt** [comment]
Closing the issue now, please comment below if there are any questions.

**Comment by ata18** [comment]
@msebolt Thanks, those links didn't answer my question. I have raised a request [here](https://developercommunity.visualstudio.com/content/idea/881074/remove-deleted-runs-from-pipeline-reports.html)
