### ISSUE TITLE
libssl issue on Ubuntu 19.04 when running ./config.sh

### ISSUE THREAD

**Issue by johndaly123** [MicrosoftDocs/vsts-docs#6728]
Enter authentication type (press enter for PAT) &gt; 
Enter personal access token &gt; ****************************************************
No usable version of the libssl was found
./config.sh: line 86:  6211 Aborted                 (core dumped) ./bin/Agent.Listener configure "$@"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 23328b13-f079-ad21-5d7a-6c640f25391c
* Version Independent ID: 4a39889d-fa00-ae2b-aa43-f358631b7b1a
* Content: [Deploy a Azure Pipelines agent on Linux - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/v2-linux?view=azure-devops#feedback)
* Content Source: [docs/pipelines/agents/v2-linux.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/agents/v2-linux.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by msebolt** [comment]
@johndaly123 Thank you for the feedback.

Please refer to https://github.com/microsoft/azure-pipelines-agent/issues/2349.

**Comment by johndaly123** [comment]
Great, thanks for the follow-up, we went with Ubuntu 18.04

**Comment by msebolt** [comment]
Sounds good, no problem.  Apologies for the inconvenience.

Please refer to [features timeline](https://docs.microsoft.com/azure/devops/release-notes/features-timeline) for updates on when 19.04 will be supported.
