### ISSUE TITLE
The documentation and the example don't match

### ISSUE THREAD

**Issue by oliverholliday** [MicrosoftDocs/vsts-docs#6735]
The argument documentation says they're all required, but the example says 4 are optional.

The argument list has totally different sets of which values are valid compared to the example and the names don't match up either.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8cebdaea-9b1f-e65a-a789-6571b5e28c03
* Version Independent ID: ca0de77d-d8a7-d766-90e6-929bdb2c877f
* Content: [Download GitHub Release task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/download-github-release?view=azure-devops)
* Content Source: [docs/pipelines/tasks/utility/download-github-release.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/utility/download-github-release.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @ashokirla
* Microsoft Alias: **ashkir**

**Comment by msebolt** [comment]
@oliverholliday Thank you for the feedback, assigning this to the author for review.

**Comment by iamsrivatsa** [comment]
The document has been updated and I'll be closing the issue. Thank you for the feedback and feel free to open a new issue if you have any more feedback.
