### ISSUE TITLE
Windows-2019 and vs2017-win2016 agents do not contain bower

### ISSUE THREAD

**Issue by nguyenlamlll** [MicrosoftDocs/vsts-docs#6736]
I used those two agents and when I tried to run `bower -v`. But both say the command is not recognized.

![image](https://user-images.githubusercontent.com/20963684/71172395-a9f1ff00-2292-11ea-9bae-4e3da2029e23.png)

The documents ([2019](https://github.com/actions/virtual-environments/blob/master/images/win/Windows2019-Readme.md#nodejs), and [2016](https://github.com/actions/virtual-environments/blob/master/images/win/Windows2019-Readme.md#nodejs)) suggest there is bower v1.8.8 installed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 99af681d-41ad-da15-0b72-08b5cd5a11ac
* Version Independent ID: 2fa0df36-a437-8cbb-b019-b49b31b1e116
* Content: [Microsoft-hosted agents for Azure Pipelines - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops)
* Content Source: [docs/pipelines/agents/hosted.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/agents/hosted.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by msebolt** [comment]
@nguyenlamlll Thank you for the feedback.

Unfortunatley changes in this forum can only apply to the documentation.

As referenced from your provided links, please move the issue to the [virtual-environments](https://github.com/actions/virtual-environments/issues) repo.

**Comment by msebolt** [comment]
Closing the issue now, please comment below if there are any questions.
