### ISSUE TITLE
Argument names

### ISSUE THREAD

**Issue by HughDevlin** [MicrosoftDocs/vsts-docs#6737]
The input parameter names in the YAML snippet do not match the Argument column in the Arguments section.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5e0ef2cf-ed52-6ded-bf14-4820d73b4ed0
* Version Independent ID: 7781e0f0-43aa-9008-abda-c03a37e2d7b4
* Content: [Windows Machine File Copy task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/windows-machine-file-copy?view=azure-devops)
* Content Source: [docs/pipelines/tasks/deploy/windows-machine-file-copy.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/deploy/windows-machine-file-copy.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by RoopeshNair** [comment]
Argument column is not meant to be YAML input names. You can use the task assistant to get the YAML snippet. 

![image](https://user-images.githubusercontent.com/1370480/71265407-29073600-236c-11ea-934d-2f9a66eeab68.png)

![image](https://user-images.githubusercontent.com/1370480/71265429-36242500-236c-11ea-8e59-e45211558828.png)

![image](https://user-images.githubusercontent.com/1370480/71265468-4c31e580-236c-11ea-91ea-d994d89e7bf4.png)

**Comment by HughDevlin** [comment]
Is it too much to ask, that the names of the parameters, used when coding up an invocation of this task, match the parameter names in the online documentation for this task? Really? The mapping between the actual parameter names and the parameter names in the documentation is available separately? Really?

**Comment by HughDevlin** [comment]
Please re-open for further discussion. Thank you.

**Comment by HughDevlin** [comment]
Everyone who uses this task is asked to perform the mental gymnastics of figuring out which actual parameter (in the YAML) corresponds to the description of the parameter in this doc. Consider this a cry for mercy. And yeah, I recognize it is not just this task, many if not all of the tasks exhibit this laziness in terms of documentation. It's almost as if this doc is automatically generated somehow and there is no commitment to get it right.
