### ISSUE TITLE
requires Windows agent

### ISSUE THREAD

**Issue by HughDevlin** [MicrosoftDocs/vsts-docs#6738]
page should state a Windows agent is required, both source and destination agents

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5e0ef2cf-ed52-6ded-bf14-4820d73b4ed0
* Version Independent ID: 7781e0f0-43aa-9008-abda-c03a37e2d7b4
* Content: [Windows Machine File Copy task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/windows-machine-file-copy?view=azure-devops)
* Content Source: [docs/pipelines/tasks/deploy/windows-machine-file-copy.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/deploy/windows-machine-file-copy.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by RoopeshNair** [comment]
We believe the task name is quite descriptive.

**Comment by HughDevlin** [comment]
in the context of Azure the requirements to run this task are not clear. For example, as I understand it, Powershell may be run on Windows or Linux, and bash scripts may be run on WIndows or Linux. Isn't it a simple matter to clearly state the requirements?

**Comment by tylerhartwig** [comment]
Agreed, I attempted to use this on a linux machine, thinking I may be able to copy from a linux agent, to a remote windows agent. The task name is unclear to me, and only implies that the remote machine must be windows.

**Comment by kevinferretti** [comment]
I just ran into this same issue. Based on my reading of the docs I thought only the destination machine needed to be windows. Especially after reading [AzureFileCopy docs](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/azure-file-copy-v5?view=azure-pipelines#remarks) which clearly note the shortcoming for linux agents.
