### ISSUE TITLE
Inappropriate Image 

### ISSUE THREAD

**Issue by pavankumarBL** [MicrosoftDocs/vsts-docs#6744]
This page of section is about Git But tag View History has a Image of TFVC history where it is a Centralized SCM. Previous sections tells to add commit and Push code to Git repo and in the portal while viewing the history of the changes image shown is TFVC so i feel we need a change here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc4e7f5a-08f4-5c12-cb6d-424d6e5dadaa
* Version Independent ID: e317a392-cb78-7fcc-fcf8-2cecaa9e6580
* Content: [Code with Git - Azure DevOps - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/user-guide/code-with-git?view=azure-devops#feedback)
* Content Source: [docs/user-guide/code-with-git.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/user-guide/code-with-git.md)
* Product: **devops**
* Technology: **devops-new-user**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by msebolt** [comment]
@pavankumarBL Thank you for the feedback, assigning this to the author for review.
