### ISSUE TITLE
Variables set in one task get prefixed?

### ISSUE THREAD

**Issue by sebader** [MicrosoftDocs/vsts-docs#6747]
I'm using a powershell script to set output variables in one task as outlined here: https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=classic%2Cpowershell#set-in-script

However, when I want to use them from the environment variables in the next task, they always get prefixed with either "POWERSHELL1_", or if I specify a reference name for the output, with that name. In the documentation example above, you simply use `$env:SAUCE` to read the variable without any prefix.
Did I miss anything here?

I set them like [this](https://github.com/microsoft/azure-pipelines-extensions/issues/660#issuecomment-533919205):

````
$json=Get-Content $jsonPath | ConvertFrom-Json
$json `
    | Get-Member -type NoteProperty `
    | ForEach-Object {
        $o=$json."$($_.Name)"
        "##vso[task.setvariable variable=$($_.Name);isOutput=true$(if ($o.sensitive -eq "True") {";issecret=true"})]$($o.value)"
    }
````

![image](https://user-images.githubusercontent.com/11445087/71243885-976ada80-2311-11ea-9642-3d63b2d3be62.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd7e0bd3-1f7d-d7b6-cc72-5ef63c31b46a
* Version Independent ID: dae87abd-b73d-9120-bcdb-6097d4b40f2a
* Content: [Variables - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=classic%2Cpowershell#set-in-script)
* Content Source: [docs/pipelines/process/variables.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/variables.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by sebader** [comment]
and update here? thanks

**Comment by jdkemme** [comment]
if you don't want the variables to be prefixed with the step name, drop the isOutput=true, as it shows in the first example at https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cpowershell#set-variables-in-scripts
isOutput is only needed if you want to reference the variable in a subsequent job, not task.

**Comment by sebader** [comment]
thank you so much @jdkemme ! That was in fact the issue for me. I hadn't noticed that before. I set it now to false and all is good.
