### ISSUE TITLE
Swimlanes in TFS 2017

### ISSUE THREAD

**Issue by jawn** [MicrosoftDocs/vsts-docs#6749]
Hi,
This page lists the following product versions:
Azure Boards | Azure DevOps Server 2019 | TFS 2018 | TFS 2017 | TFS 2015

However, I cannot find the Swimlane configuration in TFS 2017.

I do see the field Board Lane, but no setting to configure the use of swimlanes in TFS.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f1127f1b-f0d3-172b-6bc9-5e705a195cef
* Version Independent ID: 5714c6fa-14fe-b275-4257-3802d0e6b233
* Content: [Expedite work with swimlanes, use swimlanes to differentiate work items on your Kanban board - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/boards/expedite-work?view=tfs-2017)
* Content Source: [docs/boards/boards/expedite-work.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/boards/boards/expedite-work.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@jawn - Please check that you are selecting the Configuration tool from the Kanban board page. If you are on that page and aren't seeing the swimlane tab, then raise the issue on our developer community page: https://developercommunity.visualstudio.com/spaces/22/index.html. Regards.
