### ISSUE TITLE
Duplicate videos

### ISSUE THREAD

**Issue by FokkoVeegens** [MicrosoftDocs/vsts-docs#675]
Great article, but looks like some videos (about feature flags) are duplicated?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7e5835c5-57ca-e68d-f033-d97ec7bd106f
* Version Independent ID: 20ff829f-93d5-b3b8-8a34-612a9a5dc841
* Content: [DevOps at Microsoft - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/devops-at-microsoft/index)
* Content Source: [https://mseng.visualstudio.com/DefaultCollection/TechnicalContent/_git/devops-learn-pr?path=%2fdocs%2fdevops-at-microsoft%2findex.md&version=GBlive&_a=contents](https://mseng.visualstudio.com/DefaultCollection/TechnicalContent/_git/devops-learn-pr?path=%2fdocs%2fdevops-at-microsoft%2findex.md&version=GBlive&_a=contents)
* Service: **unspecified**
* GitHub Login: @samgu
* Microsoft Alias: **samgu**

**Comment by steved0x** [comment]
@FokkoVeegens Thanks for letting us know, I'll get those fixed up right away.

**Comment by steved0x** [comment]
@FokkoVeegens I just merged the fix, it should be live very soon, thanks again.
