### ISSUE TITLE
Apply the customized process to your project update

### ISSUE THREAD

**Issue by madrum** [MicrosoftDocs/vsts-docs#6752]
Before step 1, "Open the … context menu for the process and choose the Change team projects… option...", you must click the Process name that your current projects is using to view the process details. Click "Projects", which is to the right of "Work item types" and "Backlog levels". Then, click the "..." (meatballs) button and "-&gt; Change process". 

A side window will pop out where you can select the process you want to change your project to. Do that and click Save. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 69c94597-965d-0ece-cdbb-58ef30b68c63
* Version Independent ID: 860a6c08-0803-8dd4-57dd-f5ae8caebb53
* Content: [Add custom work item type to inherited process - Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/organizations/settings/work/add-custom-wit?view=azure-devops#feedback)
* Content Source: [docs/organizations/settings/work/add-custom-wit.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/settings/work/add-custom-wit.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@madrum - Thank you for the correction. I will look at updating the article to clarify the steps as you note.
