### ISSUE TITLE
Typo error on this page

### ISSUE THREAD

**Issue by kumarallamraju** [MicrosoftDocs/vsts-docs#6754]
[Enter feedback here]

>>>To use your these tools you simply check the corresponding checkbox in the

Do you mean

To use these tools you simply

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec7fc8c5-4ab5-d227-e930-9c3c3a5f62ac
* Version Independent ID: a6dfdeac-8b46-a4b8-f1a8-ac34a7e1900b
* Content: [Use standalone static analysis - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/java/standalone-tools?view=azure-devops)
* Content Source: [docs/java/standalone-tools.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/java/standalone-tools.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @DavidStaheli
* Microsoft Alias: **dastahel**

**Comment by WilliamAntonRohm** [comment]
@kumarallamraju -- thank you for spotting this.

@Potapy4 -- thank you Nikita for creating that PR.

@davidstaheli -- David, please review the above-mentioned PR 6771.
