### ISSUE TITLE
No doc for rootDirectory input parameter

### ISSUE THREAD

**Issue by HughDevlin** [MicrosoftDocs/vsts-docs#6757]
No documentation on the rootDirectory input parameter.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b2ea8b7b-44cb-e315-b086-c4e3361bf59a
* Version Independent ID: 5fcdaa72-ca89-2139-a8c9-2eb263b4824e
* Content: [FTP Upload task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/ftp-upload?view=azure-devops)
* Content Source: [docs/pipelines/tasks/utility/ftp-upload.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/utility/ftp-upload.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @vijayma
* Microsoft Alias: **vijayma**

**Comment by srivatsamarichi** [comment]
The documentation has been updated and I'll be closing the issue. Thank you for the feedback and feel free to open a new issue if you have any more feedback.

**Comment by iamsrivatsa** [comment]
The documentation has been updated and I'll be closing the issue. Thank you for the feedback and feel free to open a new issue if you have any more feedback.
