### ISSUE TITLE
Typo under Deploy agents to a deployment group section

### ISSUE THREAD

**Issue by kumarallamraju** [MicrosoftDocs/vsts-docs#6758]
[Enter feedback here]
>>>If the target machines are Azure VMs, you can quickly and easily prepare them by by installing the

There's an extra "by" in the above sentence
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3b38c265-be4c-b038-e3a9-783a5e5ce659
* Version Independent ID: 67da69da-3651-a8f4-f06a-c35aa3aa98fc
* Content: [Use deployment groups in a release pipeline - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/deployment-groups/?view=azure-devops)
* Content Source: [docs/pipelines/release/deployment-groups/index.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/release/deployment-groups/index.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by RoopeshNair** [comment]
[PR#742](https://github.com/MicrosoftDocs/azure-devops-docs-pr/pull/742)

**Comment by KathrynEE** [comment]
@kumarallamraju - The typo has been fixed.
