### ISSUE TITLE
Incorrect information for Azure Devops Docker Compose azureContainerRegistry

### ISSUE THREAD

**Issue by RothNRK** [MicrosoftDocs/vsts-docs#6760]
In the docs is clearly says `Name of the Azure Container Registry` while it really requires the Azure Container Registry `Login server`. 

In the docs:
azureContainerRegistry(Azure Container Registry) | (Required) Name of the Azure Container Registry.

General feedback:
The amount of time my team wastes on misleading, ambiguous, or incorrect documentation is adding up. Azure's poor documentation is a hidden cost that Microsoft passes to its customers and I hope that Azure starts to appreciate and corrects this massive deficiency.

Thank you 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d767aebb-620e-9ad3-e906-3e2bafa02ee9
* Version Independent ID: c8cb5a48-ccdf-778c-1547-a10db74cb56c
* Content: [Docker Compose task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/docker-compose?view=azure-devops#feedback)
* Content Source: [docs/pipelines/tasks/build/docker-compose.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/build/docker-compose.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @azooinmyluggage
* Microsoft Alias: **atulmal**

**Comment by srivatsamarichi** [comment]
@RothNRK Thanks for the feedback. Seems like you are referring the container registry types. Based on the types, there are arguments detailed in the document. 
If you are using [ACR](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/docker-compose?view=azure-devops#azure-container-registry), 
- then you have to use the `azureContainerRegistry` as your parameter. 

If you are using any other container registry types,
- then you have to use the `containerregistrytype` as your parameter.

The document already has a sample example snippets which covers both the scenarios. Hope this helps.

**Comment by iamsrivatsa** [comment]
@RothNRK Thanks for the feedback. Seems like you are referring the container registry types. Based on the types, there are arguments detailed in the document. 
If you are using [ACR](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/docker-compose?view=azure-devops#azure-container-registry), 
- then you have to use the `azureContainerRegistry` as your parameter. 

If you are using any other container registry types,
- then you have to use the `containerregistrytype` as your parameter.

The document already has a sample example snippets which covers both the scenarios. Hope this helps.

**Comment by iamsrivatsa** [comment]
The document has been updated and I'll be closing the issue. Thank you for the feedback and feel free to open a new issue if you have any more feedback.
