### ISSUE TITLE
Path to artifact cannot use wildcards

### ISSUE THREAD

**Issue by PiotrPerak** [MicrosoftDocs/vsts-docs#6762]
I think docs should clearly say that path in publish pipeline artifacts task can't use wildcards.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 861ce7a5-4fa4-55f1-2c97-46a9cc6a2f66
* Version Independent ID: bdf954b9-9bbe-8b34-b674-71ad8153519d
* Content: [Publish and consume artifacts in pipelines - Azure Pipelines and TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/pipeline-artifacts?view=azure-devops&tabs=yaml-task#feedback)
* Content Source: [docs/pipelines/artifacts/pipeline-artifacts.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/artifacts/pipeline-artifacts.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @chasewilson
* Microsoft Alias: **phwilson**

**Comment by mijacobs** [comment]
Hi @PiotrPerak ,
Can you provide an example? Wildcards are supported for pipelines. From the article:

* File matching patterns should assume the first segment of the pattern is (or matches) an artifact name. For example, WebApp/** matches all files from the WebApp artifact. The pattern */*.dll matches all files with a .dll extension at the root of each artifact.
* File matching patterns for the Download Build Artifacts task are expected to start with (or match) the artifact name, regardless if a specific artifact was specified or not. 

Are you saying that these patterns aren't working?

**Comment by PiotrPerak** [comment]
Two months later I don't really remember what was the issue.
My ticket should add more details when I was creating it. Sorry.

**Comment by jww3** [comment]
The doc has two sections, Publishing and Downloading

@PiotrPerak refers to the Publishing section in his post.  @mijacobs response cites the Downloading documentation.

The question remains whether Publishing supports wildcards?
