### ISSUE TITLE
Tag "categories" is missing on vss-extension.json code on Add a Hub example - Azure DevOps

### ISSUE THREAD

**Issue by juangps96** [MicrosoftDocs/vsts-docs#6764]
The Tag "categories" is missing on vss-extension.json code:

 "categories": ["Azure Boards"],

On this example: 

https://docs.microsoft.com/en-us/azure/devops/extend/develop/add-hub?view=azure-devops 

![Error](https://user-images.githubusercontent.com/13917423/71371683-f6ce2200-257f-11ea-8c29-462fc7fa8e68.png)

**Comment by chcomley** [comment]
@juangps96, Thanks so much for your feedback. The article is updated.
