### ISSUE TITLE
include short form 

### ISSUE THREAD

**Issue by drdamour** [MicrosoftDocs/vsts-docs#6768]
https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema#download describes a shortform that is not documented here and should be

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b03d67d0-8738-72e6-dbe7-324c1784d4fc
* Version Independent ID: bbb4d774-cd98-3ecb-7ccf-5f49e6f2b425
* Content: [Download Pipeline Artifacts task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/download-pipeline-artifact?view=azure-devops)
* Content Source: [docs/pipelines/tasks/utility/download-pipeline-artifact.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/utility/download-pipeline-artifact.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @vijayma
* Microsoft Alias: **vijayma**

**Comment by ashokirla** [comment]
the `download` keyword is used for consuming artifacts published in the current pipeline or from another pipeline that is referred as a `pipeline` resource. And this keyword has verifies the artifact type i.e. pipeline artifact or network share artifact and injects the appropriate task. So this is not a task specific property. We can provide a link as part of the task documentation to learn more about download keyword.

**Comment by iamsrivatsa** [comment]
The documentation has been updated and I'll be closing the issue. Thank you for the feedback and feel free to open a new issue if you have any more feedback.

**Comment by drdamour** [comment]
@ashokirla the link i provided says “ The publish keyword is a shortcut for the Publish Pipeline Artifact task. ” that certainly
Implies its a task. It appears in the pipeline output as a task as well.
