### ISSUE TITLE
Add match groups

### ISSUE THREAD

**Issue by Dash** [MicrosoftDocs/vsts-docs#6772]
For the Copy Files task, it would be a handy addition to utilise matches from the source in the destination.
e.g.
Source path:  SubProject1\**\bin\$(BuildConfiguration)\*.dll
Destination: $(build.artifactstagingdirectory)\SubProject1

Make the "SubProject1" a matching variable, so this produces the same effect, just dynamically:
Source path:  (?&lt;area&gt;*)\**\bin\$(BuildConfiguration)\*.dll
Destination: $(build.artifactstagingdirectory)\{area}

Or similar.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 81f02378-b85b-d3a4-d3c8-f07d935367da
* Version Independent ID: fab57f76-35d2-4024-6f7f-1740d7b24743
* Content: [Copy Files task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/copy-files?view=azure-devops&tabs=yaml#feedback)
* Content Source: [docs/pipelines/tasks/utility/copy-files.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/utility/copy-files.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @vtbassmatt
* Microsoft Alias: **macoope**

**Comment by vtbassmatt** [comment]
Feature requests should be filed on [Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html). Please feel free to file it there. (In full transparency, though, we're unlikely to take this one -- we use [glob](http://man7.org/linux/man-pages/man3/fnmatch.3.html), not regex, for path matching.)
