### ISSUE TITLE
Success Criteria for Requests returning JSON

### ISSUE THREAD

**Issue by SebastianSchuetze** [MicrosoftDocs/vsts-docs#678]
I have understood the the basic criteria, but if I have a JSON string returned with nested properties, then I can't find any information on how the success criteria expression must look like. The documentation on the field gives the following example:
for a repsonse like {"status" : "successful"}, the expression can be eq(root['status'], 'successful')

but how does it look like for a repsonse like

{"values" : [{"status":"successful"},{"status":"failed"}]} 

or

{"values" : {"status":"successful"}} 

A more detailed explanation in this document would improve that.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 89bc6da4-5a1e-5989-f4f0-27465953b5fd
* Version Independent ID: fd12f976-5d3b-3b1b-3d0a-a0bf2a60c961
* Content: [Invoke HTTP REST API task for Microsoft VSTS and TFS](https://docs.microsoft.com/en-us/vsts/build-release/tasks/utility/http-rest-api?view=vsts)
* Content Source: [docs/build-release/tasks/utility/http-rest-api.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/build-release/tasks/utility/http-rest-api.md)
* Service: **unspecified**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment]
Thank you for your feedback. I have passed this on to the product team and will update the topic based on their response.

**Comment by shashban** [comment]
Can you see if https://github.com/Microsoft/vsts-tasks/blob/master/docs/authoring/servertaskauthoring.md gives you the required information on how to parse jsons for success conditions?

**Comment by SebastianSchuetze** [comment]
Hi, thanks for the link. I found that one as well. But there are still some information missing, which I needed to find out myself.

For example: In a quality gate I have the following equation, which works:

`eq(jsonpath('$.value[*].environments[*].status')[0],'succeeded')`

I wanted to check if an environment has the status succeeded from the following VSTS api path

__apis/release/releases/?$top=1&$expand=environments_

I needed to find out myself, that I need to specifically access the array, which is returned from json path even though there is just one item returned. Also an information of which version of jsonpath is used would be great.

But still, the link you provided helped me! 

Btw. there is a link on that page pointing to GitHub, which does not exist anymore:
https://github.com/Microsoft/vsts-tasks/tree/master/Tasks/InvokeRestApi

**Comment by m1ckr1sk** [comment]
is your equation still working?  We are using a similar method
```
eq(jsonpath('$.environments[?(@.name==''env'')].status')[0],'inProgress')
```
which has recently stopped working.  The rest returns 200 with valid JSON but the expression returns:

```
Evaluation of expression 'eq(jsonpath('$.environments[?(@.name==''env'')].status')[0],'inProgress')' failed.
				
Exception Message: Object reference not set to an instance of an object. (type NullReferenceException)
```
It would be really useful if this was documented better.

**Comment by shashban** [comment]
Thanks for reporting the issue. We found it as a code bug on our side and have started a hotfix release for the same. The expression handling should get working again soon (some time next week depending upon the ring you account belongs to).

**Comment by jordanchang** [comment]
My response returns a Json array. Could you provide an example on how to check if the length of the array is greater than 0? I've tried root.length() and len(root). Neither works.

**Comment by shayki5** [comment]
Can you add more examples to json arrays? thank you!
