### ISSUE TITLE
Wrong Name PieChart instead of Chart

### ISSUE THREAD

**Issue by juangps96** [MicrosoftDocs/vsts-docs#6780]
Wrong Name PieChart instead of Chart
![Error Chart](https://user-images.githubusercontent.com/13917423/71487103-8a555c00-27e7-11ea-8655-496381d2fe40.png)

If it was written: 
 "contributions": [
        {
            "id": "chart",
on vss-extension.json 

It should also have been written:  
VSS.register("chart", function () { 
on the javascript 

but not: VSS.register("PieChart"

https://docs.microsoft.com/en-us/azure/devops/extend/develop/add-chart?view=azure-devops

**Comment by chcomley** [comment]
Hi @juangps96, Thanks for the heads up on this. I've updated the article, which should be live shortly. Thanks again!
