### ISSUE TITLE
[Visual Studio subscribers] link 404s

### ISSUE THREAD

**Issue by TeamDman** [MicrosoftDocs/vsts-docs#6789]
https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/manage-users-table-view?view=azure-devops&tabs=preview-page

![image](https://user-images.githubusercontent.com/9356891/71560187-8407ef80-2a34-11ea-933c-ed4448bdeb2f.png)

![image](https://user-images.githubusercontent.com/9356891/71560191-8b2efd80-2a34-11ea-85c1-0d560362c355.png)

**Comment by WilliamAntonRohm** [comment]
@TeamDman -- thank you for your feedback.  It appears this link has been fixed.

**Comment by TeamDman** [comment]
Still seems dead for me, signed in and signed out.

![image](https://user-images.githubusercontent.com/9356891/71855106-287dd780-30ae-11ea-9936-07a65db1dec3.png)

![image](https://user-images.githubusercontent.com/9356891/71855077-12701700-30ae-11ea-935c-76616a4e9e5a.png)
