### ISSUE TITLE
versioningScheme confusing

### ISSUE THREAD

**Issue by aplocher** [MicrosoftDocs/vsts-docs#6794]
versioningScheme mentions the options are: off, byPrereleaseNumber, byEnvVar, byBuildNumber

The description then mentions the options are: 'Use the date and time', 'Use an environment variable', 'Use the build number'

I assume "Use the date and time" is "byPreleaseNumber"?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d1d9884-19f7-592b-f47c-8cf100639ff0
* Version Independent ID: 555c3826-60d9-2589-54af-850efbfbb13a
* Content: [.NET Core CLI task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/dotnet-core-cli?view=azure-devops#feedback)
* Content Source: [docs/pipelines/tasks/build/dotnet-core-cli.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/build/dotnet-core-cli.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @pulkitaggarwl
* Microsoft Alias: **puagarw**

**Comment by msebolt** [comment]
@aplocher Thank you for the feedback, the documentation has been updated and is pending review.

Please consider how to become a [Microsoft Docs contributor](https://docs.microsoft.com/contribute/) where you can submit any suggestions directly.
