### ISSUE TITLE
Built in conditions don't have yaml keywords specified.

### ISSUE THREAD

**Issue by MarkIannucci** [MicrosoftDocs/vsts-docs#6796]
It would be great if the first section defines the yaml keywords to use.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f151218-9a11-0078-e038-f96198a76143
* Version Independent ID: 09c4d032-62f3-d97c-79d7-6fbfd89910e9
* Content: [Conditions - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/conditions?tabs=yaml&view=azure-devops)
* Content Source: [docs/pipelines/process/conditions.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/conditions.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by msebolt** [comment]
@Marklannucci  Thank you for the feedback, assigning this to the author for review.

**Comment by juliakm** [comment]
@Marklannucci Thanks for your pull request! It is merged now.
