### ISSUE TITLE
Incorrect documentation for 'includeReferencedProjects' mixed up with 'versionEnvVar'

### ISSUE THREAD

**Issue by AnthonyDewhirst** [MicrosoftDocs/vsts-docs#6800]
The documentation for 'includeReferencedProjects' is missing, instead the documentation is for 'versionEnvVar'.

**Comment by msebolt** [comment]
@AnthonyDewhirst Thank you for the feedback.

The documentation has been updated and is pending review.

Please consider becoming a [Microsoft Docs contributor](https://docs.microsoft.com/contribute/) if you'd like to submit suggestions directly.
