### ISSUE TITLE
Release Pipelines Classic?

### ISSUE THREAD

**Issue by gstevens-kyriba** [MicrosoftDocs/vsts-docs#6802]
Seems Release pipelines are now "Classic" - But I dont see anything about how to migrate..

There is a ton of stuff in a Release Pipeline.  Why not have a build.yml and release.yml file ?

I dont want them to run in the same process...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 521b594c-dbb9-54d5-f56f-00e2f5fa1d92
* Version Independent ID: 509d3e4e-23db-8493-e1a6-acb67ec47e81
* Content: [Customize your pipeline - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/customize-pipeline?view=azure-devops)
* Content Source: [docs/pipelines/customize-pipeline.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/customize-pipeline.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @vijayma
* Microsoft Alias: **vijayma**

**Comment by msebolt** [comment]
@gstevens-kyriba Thank you for the feedback.

Please refer to [this blog post](https://www.hanselman.com/blog/SettingUpAzureDevOpsCICDForANETCore31WebAppHostedInAzureAppServiceForLinux.aspx) on the subject or the following posts [here](https://stackoverflow.com/questions/58749486/how-to-convert-classic-build-job-to-yaml-build-in-azuredevops) and [here](https://stackoverflow.com/questions/57895383/migrating-existing-entire-azure-devops-pipeline-to-yaml-based-pipelines-in-bu) for further information.

To hear from the product team, you can also submit your suggestion to the [Azure DevOps community](https://developercommunity.visualstudio.com/spaces/21/index.html) or refer to [this active issue](https://developercommunity.visualstudio.com/idea/733456/export-entire-azure-devops-buildrelease-pipelines.html).

Including @vijayma  to note lack of documentation in this area.

**Comment by msebolt** [comment]
Closing this issue now, please comment below if there are additional questions.
