### ISSUE TITLE
Pipeline Caching - .net - multiple lock files

### ISSUE THREAD

**Issue by tymtam2** [MicrosoftDocs/vsts-docs#6805]
This is about https://docs.microsoft.com/en-us/azure/devops/pipelines/caching/index?view=azure-devops#netnuget 

The article states: "If you use PackageReferences to manage NuGet dependencies directly within your project file and have a packages.lock.json file, you can enable caching by setting the NUGET_PACKAGES environment variable to a path under $(Pipeline.Workspace) and caching this directory."

What if there are multiple lock files? I don't believe that solution wide lock files have implemented yet so any real project will have multiple packages.lock.json files.

**Comment by msebolt** [comment]
@tymtam2 Thank you for the question.

For product-related questions and/or issues, please start an issue [here](https://github.com/microsoft/azure-pipelines-tasks/issues/new?labels=Area%3A%20PipelineCaching), or use the **Report a problem**/**Suggest a feature** options in the [Azure DevOps community](https://developercommunity.visualstudio.com/spaces/21/index.html).

For additional support options, please refer to:

- [Azure DevOps Support](https://azure.microsoft.com/support/devops/)
- [Azure DevOps on StackOverflow](https://stackoverflow.com/questions/tagged/azure-devops)

@chasewilson If possible, perhaps this can be addressed under issue https://github.com/MicrosoftDocs/vsts-docs/issues/6806.

**Comment by msebolt** [comment]
Closing the issue now, please comment below if there are any questions.

**Comment by davicbaba** [comment]
Any news here?
