### ISSUE TITLE
Deployment Job dependencies.[jobname].outputs[] not processed for on: success: 

### ISSUE THREAD

**Issue by stweb1963** [MicrosoftDocs/vsts-docs#6807]
using
  on: 
     success: 
and consuming outputs from the deploy step does not produce desired results

specifying 
    $[ dependencies.[jobname].outputs['jobname.stepname.outputvariable'] ] 
is returned as a string equal to 
  "dependencies.[jobname].outputs['jobname.stepname.outputvariable']"

instead of the actual output of the variable

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5aeeaace-1c5b-a51b-e41f-f25b806155b8
* Version Independent ID: fd7ff690-b2e4-41c7-a342-e528b911c6e1
* Content: [Deployment jobs - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/deployment-jobs?view=azure-devops)
* Content Source: [docs/pipelines/process/deployment-jobs.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/deployment-jobs.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by stweb1963** [comment]
More specifically
how do we reference outputs from the deploy: steps from the on: failure: and on: success:

**Comment by msebolt** [comment]
@stweb1963 Thank you for the question.

Unfortunately our support options are limited and there is no record of this issue previously reported.

Please start an issue [here](https://developercommunity.visualstudio.com/spaces/21/index.html) (or let us know and we can start one for you) with further details included on how to reproduce the issue so the product team can best determine whether a fix is needed.

For additional support options, you can also try:

- [Azure DevOps Support](https://azure.microsoft.com/support/devops/)
- [Azure DevOps on StackOverflow](https://stackoverflow.com/questions/tagged/azure-devops)

**Comment by msebolt** [comment]
Closing this issue now, please comment below if there are additional questions.
