### ISSUE TITLE
Need more thorough documentation on macro usages

### ISSUE THREAD

**Issue by mtaylorfsmb** [MicrosoftDocs/vsts-docs#6810]
The documentation mentions the date macros like `@startOfYear` in a footnote but doesn't provide information on what it can do. For example I see in some queries that it supports an offset using the syntax of `@startOfDay('-7d') which seems to get the last 7 days. However this isn't documented anywhere. `-7m` also seems to be valid but it doesn't seem to return any results. However `-1Y` does not. 

Please document any parameters that can be used with these macros. It might also be nice to see an example of how to get all items within a sliding date range like the last year.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba14ee34-2de7-706f-ae44-be969fde352b
* Version Independent ID: f7ba18e9-42e4-ef07-e36b-377fb787aa72
* Content: [Query by date or current iteration - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/queries/query-by-date-or-current-iteration?view=azure-devops#feedback)
* Content Source: [docs/boards/queries/query-by-date-or-current-iteration.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/boards/queries/query-by-date-or-current-iteration.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by msebolt** [comment]
@mtaylorfsmb Thank you for the feedback, assigning this to the author for review.

**Comment by KathrynEE** [comment]
@mtaylorfsmb - Thank you for your input. I believe I provided 3 examples in this section: https://docs.microsoft.com/en-us/azure/devops/boards/queries/query-by-date-or-current-iteration?view=azure-devops#start-of-day-week-month-or-year-date-based-queries. However, I'll look at enhancing the article to also provide the example you suggest to get all items within a sliding date range like the last year. This can be done with the following settings: 

![image](https://user-images.githubusercontent.com/10856840/73026642-aa783b00-3de6-11ea-930e-c0704ece3681.png)
