### ISSUE TITLE
Steps to create a Release branch from master branch

### ISSUE THREAD

**Issue by saxenark** [MicrosoftDocs/vsts-docs#6811]
I have been struggling with what are the exact steps to follow for a Release workflow model, when I am going to create my Release R1.0 branch from master. Specifically, with respect to my CI pipeline, do I make my custom release related changes (e.g. version numbers) in the same yaml as the master branches pipeline. This means that for the same pipeline, the yamls would be different between master and R.10 branches. Alternatively, I can create a new R1.0.yaml with a exclude trigger for master *.. What does VSTS team follow? What are the pros and cons?

**Comment by msebolt** [comment]
@saxenark Thank you for the feedback.

Unfortunately the support options in this forum are limited, though feel free to reference specific articles for needed further expansion or clarification.

In the meantime, please see if [Release flow](https://docs.microsoft.com/azure/devops/learn/devops-at-microsoft/release-flow) addresses this topic.

For support options in regards to specific technical details, please see:

- [Azure DevOps Support](https://azure.microsoft.com/support/devops/)
- [Azure DevOps on StackOverflow](https://stackoverflow.com/questions/tagged/azure-devops)

**Comment by msebolt** [comment]
Closing this issue now, please comment below if there are additional questions.
