### ISSUE TITLE
Update screenshots to address modern URL format

### ISSUE THREAD

**Issue by SychevIgor** [MicrosoftDocs/vsts-docs#6816]
On all following screenshot, in url used old format "***pkgs.visualstudio.com", while current format is "https://pkgs.dev.azure.com/*"
Please, update screenshot to address current url format to avoid any possible confusions. 
It's minor moment, but my team faced with an issue and try old format of url, that no longer work at all.  

https://docs.microsoft.com/en-us/azure/devops/artifacts/_shared/_img/nuget-azure-devops-newnav.png?view=azure-devops
https://docs.microsoft.com/en-us/azure/devops/artifacts/_shared/_img/nuget-visual-studio-newnav.png?view=azure-devops
https://docs.microsoft.com/en-us/azure/devops/artifacts/_shared/_img/vs-addsource.png?view=azure-devops
https://docs.microsoft.com/en-us/azure/devops/artifacts/_shared/_img/vs-mac-settings.png?view=azure-devops

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a10a409-5468-9532-f0dc-5a28cdd566d8
* Version Independent ID: 2ef20266-bc45-448b-27f5-e5c3bffed2ef
* Content: [Get started with NuGet packages - Azure Artifacts](https://docs.microsoft.com/en-us/azure/devops/artifacts/get-started-nuget?view=azure-devops)
* Content Source: [docs/artifacts/get-started-nuget.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/artifacts/get-started-nuget.md)
* Product: **devops**
* Technology: **devops-artifacts**
* GitHub Login: @chasewilson
* Microsoft Alias: **phwilson**

**Comment by SychevIgor** [comment]
For npm and maven - documentation contains the same problem 
https://docs.microsoft.com/en-us/azure/devops/artifacts/_shared/_img/npm-azure-devops-newnav.png?view=azure-devops
https://docs.microsoft.com/en-us/azure/devops/artifacts/_shared/_img/connect-to-feed-npm-creds-azure-devops-newnav.png?view=azure-devops
https://docs.microsoft.com/en-us/azure/devops/artifacts/_shared/_img/maven-azure-devops-newnav.png?view=azure-devops

**Comment by msebolt** [comment]
@SychevIgor Thank you for the feedback, assigning this to the author for review.
