### ISSUE TITLE
GDPR Compliance?

### ISSUE THREAD

**Issue by adhiggs** [MicrosoftDocs/vsts-docs#682]
Does this document need to be scrubbed for GDPR compliance?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fd5e112c-5296-c8e1-547b-36b56a6c4582
* Version Independent ID: 99a12016-36c2-9380-49e5-113cd9b0c96c
* Content: [Bulk modify using Excel - VSTS & TFS](https://docs.microsoft.com/en-us/vsts/work/backlogs/office/bulk-add-modify-work-items-excel?view=vsts#feedback)
* Content Source: [docs/work/backlogs/office/bulk-add-modify-work-items-excel.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/work/backlogs/office/bulk-add-modify-work-items-excel.md)
* Service: **unspecified**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@adhiggs - Thank you for your inquiry. I will contact the Product Manager for this area and follow up as needed.
