### ISSUE TITLE
import log files

### ISSUE THREAD

**Issue by hemanth70052** [MicrosoftDocs/vsts-docs#6820]
the first line says that The log file titled DataMigrationTool.log is going to be the main log which contains details on everything that was run. but in that image there is no log file named as DataMigrationTool.log 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4fa0ebd3-8437-8508-5a8d-462186fcce80
* Version Independent ID: efe892fe-387e-0a61-fe7d-33d2ac99dfa9
* Content: [Import migrate process from on-premises to Azure DevOps - Azure DevOps](https://docs.microsoft.com/en-in/azure/devops/migrate/migration-import?view=azure-devops#related-articles)
* Content Source: [docs/migrate/migration-import.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/migrate/migration-import.md)
* Product: **devops**
* Technology: **devops-migrate**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by msebolt** [comment]
@hemanth70052 Thank you for the feedback, assigning this to the author for review.

**Comment by KathrynEE** [comment]
@roferg - Could you look into updating the image that shows log files?

**Comment by KathrynEE** [comment]
@@hemanth70052 - The article has been updated to remove the out of date image.
