### ISSUE TITLE
pipeline reference name in example doesnt follow required format

### ISSUE THREAD

**Issue by a30001539** [MicrosoftDocs/vsts-docs#6821]
According to the [vscode plugin](https://github.com/microsoft/azure-pipelines-vscode/blob/master/service-schema.json), the pipeline reference name (the entry after the `pipeline:` entry in a resource declaration) must follow the following regex

    "referenceName": {
			"type": "string",
			"pattern": "^[_A-Za-z0-9]*$"
		},

Note there is no `dash` (`-`)character in that regex, in contrast to the example give, which is `security-lib`

I haven't been able to find the actual repo the pipeline resources are defined in, maybe `-` is allowed, in which case the vscode plugin is wrong.

Can you please investigate

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5673ec1-c7d1-e0ac-043a-8fc3d5b226a9
* Version Independent ID: b4872831-51c0-6cf8-1c56-de20beb38a80
* Content: [Build pipeline triggers - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/triggers?view=azure-devops&tabs=yaml#feedback)
* Content Source: [docs/pipelines/build/triggers.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/build/triggers.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by msebolt** [comment]
@a30001539 Thank you for the feedback, assigning this to the author for review.

**Comment by steved0x** [comment]
@a30001539 Thanks for letting us know, I'll get that snippet fixed up, the `-` is not supported as part of that value.
