### ISSUE TITLE
Deployment Group Agent on Mac

### ISSUE THREAD

**Issue by rofehaim** [MicrosoftDocs/vsts-docs#6822]
Hi, a deployment group agent can be deployed on a Mac as well?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee31adc7-dad4-2df7-639c-eabdf3e1ae86
* Version Independent ID: 50eda1c6-7339-f636-b243-1fae4529bab0
* Content: [Use deployment groups in a release pipeline - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/deployment-groups/?view=azure-devops)
* Content Source: [docs/pipelines/release/deployment-groups/index.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/release/deployment-groups/index.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by msebolt** [comment]
@rofehaim Thank you for the question.

Yes, this feature is supported, please refer to [Deploy an agent on MacOS](https://docs.microsoft.com/azure/devops/pipelines/agents/v2-osx) and use the comments section below if there are any issues.

**Comment by msebolt** [comment]
Closing the issue now, please comment below if there are any questions.
