### ISSUE TITLE
Web Apps 

### ISSUE THREAD

**Issue by Decker-Russell** [MicrosoftDocs/vsts-docs#6823]
When will web apps be supported?

**Comment by msebolt** [comment]
@Decker-Russell Thank you for the question.

Currently supported web apps can be found in the existing documentation, for instance, see [Deploy an Azure Web App](https://docs.microsoft.com/azure/devops/pipelines/targets/webapp).

In general, new features are outlined in the [features timeline](https://docs.microsoft.com/azure/devops/release-notes/features-timeline), or by soliciting feedback from the product team through the [Azure DevOps community](https://developercommunity.visualstudio.com/spaces/21/index.html).

**Comment by Decker-Russell** [comment]
I understand you can deploy Web Apps via pipelines and many other ways but can the deployments be managed from Environments? I can only add Kubernetes resources, no option for web apps

**Comment by msebolt** [comment]
This is something only the product team can comment on, please use [suggest a feature](https://developercommunity.visualstudio.com/content/idea/post.html?space=21) for further information.

**Comment by msebolt** [comment]
Closing this issue now.

Please feel free to contact us again if there are any additional questions or issues.
