### ISSUE TITLE
"Edit build pipeline" not listed

### ISSUE THREAD

**Issue by gocoelho** [MicrosoftDocs/vsts-docs#6826]
The pipeline permission "Edit build pipeline" not listed. Azure DevOps Server Update 1.1

![image](https://user-images.githubusercontent.com/7503127/71849396-b2c73b00-30b0-11ea-8d02-471e611de50d.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 68686c2b-c69a-d9e4-3e21-a46d231b649c
* Version Independent ID: 049659da-1772-3166-f909-4feeb8a97730
* Content: [What are all the default permissions and groups? - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/security/permissions?view=azure-devops&tabs=preview-page#feedback)
* Content Source: [docs/organizations/security/permissions.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/security/permissions.md)
* Product: **devops**
* Technology: **devops-security**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by msebolt** [comment]
@gocoelho Thank you for the feedback, assigning this to the author for review.

**Comment by KathrynEE** [comment]
@gocoelho - Thank you for the correction. I'll update the topic to reflect the changes for Azure DevOps Server 2019.1,
