### ISSUE TITLE
Is there a way to trigger an update to a deployment group agent?

### ISSUE THREAD

**Issue by MarkIannucci** [MicrosoftDocs/vsts-docs#6827]
I noticed that we have a bunch of agents across a variety of versions in our environment.  This document is silent on how to update the agents, and they don't appear in `Agent Pools` so I can't use the [Agent version and upgrades documentation](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/agents?view=azure-devops&tabs=browser#agent-version-and-upgrades) to get this task completed.  Is there a way to trigger an update to a deployment group agent?  Does Microsoft have any recommendations on how frequently we should update them?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee31adc7-dad4-2df7-639c-eabdf3e1ae86
* Version Independent ID: 50eda1c6-7339-f636-b243-1fae4529bab0
* Content: [Use deployment groups in a release pipeline - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/deployment-groups/?view=azure-devops)
* Content Source: [docs/pipelines/release/deployment-groups/index.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/release/deployment-groups/index.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by RoopeshNair** [comment]
The deployment group agents are same as that of build and release agents. Self-hosted agents can usually be updated automatically by Azure Pipelines. An upgrade is requested when a platform feature or one of the tasks used in the pipeline requires a newer version of the agent.

You can manually trigger agent updates from the deployment group landing page. Using the  "..." overflow menu, --> Update targets.

**Comment by MarkIannucci** [comment]
Found it in the deployment groups page in releases:

![image](https://user-images.githubusercontent.com/16762974/71873122-a3a9b280-30db-11ea-8525-12b0814d1847.png)

Thank you.

**Comment by bahadir-be** [comment]
> The deployment group agents are same as that of build and release agents. Self-hosted agents can usually be updated automatically by Azure Pipelines. An upgrade is requested when a platform feature or one of the tasks used in the pipeline requires a newer version of the agent.
> 
> You can manually trigger agent updates from the deployment group landing page. Using the "..." overflow menu, --> Update targets.

@RoopeshNair Can we do it via REST-API?
