### ISSUE TITLE
What's the long term plan for Classic Release Pipelines?

### ISSUE THREAD

**Issue by MarkIannucci** [MicrosoftDocs/vsts-docs#6828]
With Microsoft adding multi-stage YAML pipelines to Azure DevOps, and naming this `Classic` my colleagues and I are wondering if Microsoft has a plan to deprecate some of the functionality in this portion of the product.  If that is the case, can  you update the requisite documentation so we can proactively avoid using stuff that will eventually be deprecated?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 24cf3799-20cb-4ccf-972d-482ec72704ad
* Version Independent ID: db1dca93-834f-54cc-96e6-ee2613a004cb
* Content: [Release pipelines - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/?view=azure-devops)
* Content Source: [docs/pipelines/release/index.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/release/index.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by RoopeshNair** [comment]
Currently there are no plans to deprecate Classic pipelines.  However, new features are being planned for YAML first.

**Comment by MarkIannucci** [comment]
Thank you.  Is it Microsoft's plan to incorporate all classic functionality into YAML?  Specifically, will we see deployment group agents be accessible in YAML at some point?

**Comment by RoopeshNair** [comment]
There are fundamental differences in Classic and YAML pipelines, it is not our intent to support every feature in classic to be in YAML. For example, Task Groups feature is never going to be in YAML. Having said, Deployment Groups - will not be in YAML in its current form. The equivalent feature would be Environments in YAML. We are rolling out VM resource support in Environments for YAML pipelines. This will support most functionality that is supported by Deployment Groups in classic.

**Comment by StingyJack** [comment]
@RoopeshNair thanks for not forcing everyone into source code churn (in this context as "pipeline as code", but the same happens when checking in changes for version numbering). There are a lot of us who need/prefer to refine or change the build process without requiring code changes.

**Comment by baermathias** [comment]
It would be great if it would be possible to convert yaml pipline -> classic pipeline

**Comment by RSwarnkar** [comment]
I agree with @baermathias. Microsoft need to have 1-on-1 correspondence between those. GUI is not going anywhere, so does the '-as-a-code'. Maintain both. What's big deal for MS?

**Comment by wallyhall** [comment]
> Currently there are no plans to deprecate Classic pipelines.

I trust this remains the case (or someone from MS can confirm here if it does not?).

I have to say, the two means of creating and maintaining pipelines are sufficiently different enough that it is certainly my opinion (and perhaps others agree?) that both hold sufficient distinct value to continue existing and being maintained.

For the organisations I've worked in (and am currently working in), _particularly_ at the "start of DevOps journeys" where there is an immaturity within the team, 90% of what we do is best served by a "simpler, drag-and-drop" interface - which is distinctly and intentionally separate from the codebase in git.

Equally, there's perhaps 30% (so a 20% overlap against the 90% already mentioned) where there is sufficient maturity and "other good reasons" to learn "port to" or "start with" YAML based pipelines backed by git.

I for one would very much appreciate the classic pipelines being maintained, _even if_ their functionality does not continue to be enriched going forward.

**Comment by WilliamAntonRohm** [comment]
@MarkIannucci, @baermathias, @RSwarnkar, @wallyhall -- thank you for your follow-up.  Please add your suggestions here:
- [Developer Community](https://developercommunity.visualstudio.com/search?space=21)
