### ISSUE TITLE
Command did not work

### ISSUE THREAD

**Issue by smcateer** [MicrosoftDocs/vsts-docs#6830]
The command `az webapp up -n &lt;your-appservice&gt;` (Provision the target Azure App Service, Step 6) did not work for me. I got the error: `validation error: Parameter 'ResourceGroup.location' can not be None.` I got it to work by changing the command to `az webapp up -n &lt;your-appservice&gt; --location centralus` 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eefdcb17-b1e5-141c-aef8-36795c9983af
* Version Independent ID: 007ebfcf-12bf-755c-858b-540d0fc59f96
* Content: [Build and deploy Python web apps - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/ecosystems/python-webapp?view=azure-devops#feedback)
* Content Source: [docs/pipelines/ecosystems/python-webapp.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/ecosystems/python-webapp.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @kraigb
* Microsoft Alias: **kraigb**

**Comment by kraigb** [comment]
Thanks for the issue. The az webapp up command shouldn't require the location on first deployment (but I believe it does if the app was deployed once already). Can you confirm that this was the first time you ran that particular command?

**Comment by kraigb** [comment]
And can you also give me the exact commands as you used them, without the <your-appservice> placeholders?

**Comment by kraigb** [comment]
Hello, @smcateer, do you have responses to my previous questions?

**Comment by kraigb** [comment]
Closing due to lack of response. If follow-up is needed, please reopen.

**Comment by niowniow** [comment]
I had the same issue while trying to create a new resource:
`az webapp up -n <your-appservice>`
Error message
`validation error: Parameter 'ResourceGroup.location' can not be None.`

**Comment by Relent97** [comment]
Hi Please specify the resource group.

"az webapp up -n <appname> --resource-group <resource group name>".

**Comment by niowniow** [comment]
Thanks, yes, in a way @smcateer  already gave the solution to the problem but it might be worthwhile to mention it in the tutorial.
