### ISSUE TITLE
Azure DevOps auditing is no longer in preview?

### ISSUE THREAD

**Issue by Styxxy** [MicrosoftDocs/vsts-docs#6831]
It seems that the Azure DevOps Auditing part is no longer in preview (can't see it anymore in the preview features).
Update this page to reflect it is GA?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 52f60b32-5c3c-f01a-cbbf-f4e9bd17a3fc
* Version Independent ID: 94753ea7-b465-f92e-10c2-8b17d995e4ff
* Content: [Access, export, filter audit logs for Azure DevOps - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/settings/azure-devops-auditing?view=azure-devops&tabs=preview-page)
* Content Source: [docs/organizations/settings/azure-devops-auditing.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/settings/azure-devops-auditing.md)
* Product: **devops**
* Technology: **devops-settings**
* GitHub Login: @roferg
* Microsoft Alias: **chcomley**

**Comment by roferg** [comment]
Hey @Styxxy - Auditing for Azure DevOps is still in a public preview at this time. I expect it to go GA in the first half of 2020.

**Comment by Styxxy** [comment]
@roferg Thanks for the clarification.

**Comment by msebolt** [comment]
Closing this issue now, please comment below if there are any additional questions.
