### ISSUE TITLE
link to .Net client libraries reference is broken

### ISSUE THREAD

**Issue by borys86** [MicrosoftDocs/vsts-docs#6832]
On the left list of links, ".Net client libraries reference" under "REST API and Client Reference" does not point directly to the reference but rather redirects to a more generic page of ".NET API Browser"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 413163f0-28c3-a2a7-d626-fcb81bcb2257
* Version Independent ID: 57c127da-2b1e-d29e-9abb-a3c258762ccf
* Content: [.NET Client Libraries - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/integrate/concepts/dotnet-client-libraries?view=azure-devops)
* Content Source: [docs/integrate/concepts/dotnet-client-libraries.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/integrate/concepts/dotnet-client-libraries.md)
* Product: **devops**
* Technology: **devops-ecosystem**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by msebolt** [comment]
@borys86 Thank you for the feedback.

The documentation has been updated and is pending review.
