### ISSUE TITLE
Azure Repos requires additional config - only supports HTTP version 1.1

### ISSUE THREAD

**Issue by MikeDiuga** [MicrosoftDocs/vsts-docs#6834]
For support in Azure Repos, execute the following in your Git repo's directory before pushing.
git config http.version HTTP/1.1

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f3d0afd1-bce9-b05e-ff1d-2914f63e2884
* Version Independent ID: 4b69aa48-977c-cf18-bd30-17185814c8e5
* Content: [Work with large files in your Git repo - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/manage-large-files?view=azure-devops#feedback)
* Content Source: [docs/repos/git/manage-large-files.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/repos/git/manage-large-files.md)
* Product: **devops**
* Technology: **devops-code-git**
* GitHub Login: @apawast
* Microsoft Alias: **sdanie**

**Comment by msebolt** [comment]
@MikeDiuga  Thank you for the feedback.

This issue is listed at https://github.com/git-lfs/git-lfs/issues/3875 and has been resolved in version 2.9.1.

Please use the above thread if there are any issues.

**Comment by msebolt** [comment]
Closing the issue now, please comment below if there are any questions.
