### ISSUE TITLE
The app uses a very outdated docker-compose version(from 2018), without the --parallel flag

### ISSUE THREAD

**Issue by yanivrozenblatepic** [MicrosoftDocs/vsts-docs#6840]
I was wondering why there is no update for the version, and it stopped 1 version before adding the --parallel to the build command, even though in the step itself the documentation includes the --parallel in the UI, it doesnt work when you add it(because the compose version is 1.22 and not 1.23)

Is there a plan to upgrade this any time?
If not I will have to write a script just to utilize it but that seems to be counter-productive.
Thank you,

**Comment by msebolt** [comment]
@yanivrozenblatepic Thank you for the feedback.

Please include a reference to the article in question and we can assign this to the author for review.

**Comment by yanivrozenblatepic** [comment]
Line 276
https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/DockerComposeV0/task.json

**Comment by msebolt** [comment]
Thank you for the update, this should be handled by the **azure-pipelines-tasks** repo.

Please move the issue [here](https://github.com/microsoft/azure-pipelines-tasks/issues) or let us know and we can start a new issue for you.

**Comment by msebolt** [comment]
Closing the issue now, please comment below if there are any questions.
