### ISSUE TITLE
No migration tool available for 2019.1.1 and its Tuesday 1/7

### ISSUE THREAD

**Issue by davidb-tenaco** [MicrosoftDocs/vsts-docs#6841]
"We’re targeting Monday, January 6th to bring 2019.1.1 migration support online. In the meantime, we’ll keep 2019.0.1 support going. It will end on Monday, January 6th to coincide with 2019.1.1 support coming online."

well, its tuesday jan. 7th now, and no new versions of the migration tool have been made available, and we cant move forward with moving our TFS collections to the cloud..

what is the ETA for the 2019.1.1 migration tool to be available?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 68737ab0-23e4-6127-3aef-3fec513c9612
* Version Independent ID: b127eb18-aac2-30b4-752c-ef1f50574976
* Content: [Azure DevOps Server to Services Migration overview - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/migrate/migration-overview?view=azure-devops&viewFallbackFrom=vsts)
* Content Source: [docs/migrate/migration-overview.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/migrate/migration-overview.md)
* Product: **devops**
* Technology: **devops-migrate**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by msebolt** [comment]
@davidb-tenaco Thank you for the question, assigning this to the author for review.

**Comment by davidb-tenaco** [comment]
@msebolt thank you.  i still dont see the 2019.1.1 data migration tool available for download yet and the note about targeting last monday (1/6) for bringing 2019.1.1 migration support online is still up on the page.

i understand this has been delayed per the note, but at the least updating that notice with a new (and hopefully more accurate) ETA would probably be appreciated by many.  

We have a migration project that is now being blocked from progressing until we are able to run imports to azure devops services from azure devops server 2019.1.1, and i dont have a new ETA to report back to the team and cant really make any scheduling decisions because of it.

**Comment by Hex-99** [comment]
Is there any feedback or ETA?

**Comment by davidb-tenaco** [comment]
@Hex-99 

Haven't heard anything at all, and pages still haven't been updated.  So who knows at this point.  :(

**Comment by davidb-tenaco** [comment]
@KathrynEE @msebolt 

It is now Monday 1/13.  A full week after the posted date of bringing migration support online for azure devops server 2019.1.1, and the related pages still haven't been updated to show that MS has completely missed the targeted date of 1/6, or that MS even has an ETA for 2019.1.1 migration support becoming available.

Please update the ETA in the page notes for enabling migration support for 2019.1.1.  If no one knows when it will be available, post that!  Posting something, is better than posting nothing hoping it will fix itself.

Thanks.

**Comment by davidb-tenaco** [comment]
looks like i found some kind of answer..  so it may take 2,3 or more weeks now...

**Comment by Hex-99** [comment]
Thanks for the link @davidb-tenaco. Kinda a let down for our teams focus. I guess I'll officially postpone and pick it up in Feb :(

**Comment by KathrynEE** [comment]
@davidb-tenaco - I reached out to the product manager and he has updated the note at the top. Target date is now Jan 21.

**Comment by davidb-tenaco** [comment]
@KathrynEE thanks for the update.  i hope it is more accurate than the last 'target date'.
