### ISSUE TITLE
PowerShell on Target Machine DOESNOT WORKS with Private IP

### ISSUE THREAD

**Issue by mananshah19** [MicrosoftDocs/vsts-docs#6842]
I want to use this task but my VM doesnot have a public IP. How can I achieve the above task!?

I already tried with public ip and it works fine but not with private IP

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fb12625b-7493-0efd-aa0f-d2dfc5ad7e18
* Version Independent ID: af94d8d8-7269-5dfa-e89a-0d3491edf5c7
* Content: [PowerShell on Target Machines task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/powershell-on-target-machines?view=azure-devops)
* Content Source: [docs/pipelines/tasks/deploy/powershell-on-target-machines.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/deploy/powershell-on-target-machines.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by RoopeshNair** [comment]
@mananshah19  - for PowerShell on Target, the destination should be reachable by the agent. If not, you can't connect. You can try this out by running the WinRM commands from the box where your agent is running (if private agent). 

A quick way to verify if the PS remoting is proper before you start using the machine in workflow is to execute below script. It is preferable to try this from the automation agent box to eliminate any possible failures during execution.

```PowerShell
$soptions = New-PSSessionOption -SkipCACheck

$cred = Get-Credential

$computername = <EnterComputerName>

$computerport = <EnterPort>

Enter-PSSession -ComputerName $computername -Port $computerport -Credential $cred -SessionOption $soptions -UseSSL
```

Alternatively you can check out [Deployment Groups](https://docs.microsoft.com/en-in/azure/devops/pipelines/release/deployment-groups/index?view=azure-devops), - it allows you to run the script on the target machine using a local agent.

**Comment by mananshah19** [comment]
No no! Please don't close the case or i have to write another feedback

I am using AzureGroupDeployment for deployment so WinRm etc is all
deployed. *As i said i am able to open a PSSession with PUBLIC IP but not
PRIVATE IP. Why is that?*
V/r,
*Manan Shah*
*Infrastructure and System Design*
Premier One
*Motorola Solutions*
*O:*  720-693-6354
*E:  **manan.shah@motorolasolutions.com <manan.shah@motorolasolutions.com>*

,




On Wed, Jan 8, 2020 at 12:54 AM RoopeshNair <notifications@github.com>
wrote:

> @mananshah19
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_mananshah19&d=DwMCaQ&c=q3cDpHe1hF8lXU5EFjNM_A&r=oFssNtQE9vh6hiu-nY3tiBzxAg3lNa5Xnl0HmIYxKno&m=kl6QtrEsW3ttcpvlH-zNsI6DLqSVp8AB6hiHW3xvXOc&s=MRq_OpdIMeaZzvB1pgG87Hrm7BPmq5Fd9yvOf1fWFnQ&e=>
> - for PowerShell on Target, the destination should be reachable by the
> agent. If not, you can't connect. You can try this out by running the WinRM
> commands from the box where your agent is running (if private agent).
>
> A quick way to verify if the PS remoting is proper before you start using
> the machine in workflow is to execute below script. It is preferable to try
> this from the automation agent box to eliminate any possible failures
> during execution.
>
> $soptions = New-PSSessionOption -SkipCACheck
> $cred = Get-Credential
> $computername = <EnterComputerName>
> $computerport = <EnterPort>
> Enter-PSSession -ComputerName $computername -Port $computerport -Credential $cred -SessionOption $soptions -UseSSL
>
> Alternatively you can check out Deployment Groups
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__docs.microsoft.com_en-2Din_azure_devops_pipelines_release_deployment-2Dgroups_index-3Fview-3Dazure-2Ddevops&d=DwMCaQ&c=q3cDpHe1hF8lXU5EFjNM_A&r=oFssNtQE9vh6hiu-nY3tiBzxAg3lNa5Xnl0HmIYxKno&m=kl6QtrEsW3ttcpvlH-zNsI6DLqSVp8AB6hiHW3xvXOc&s=XoRKhSjnJZWWMYDAMsmPtfIang8iXdl4rPAKXotgEoU&e=>,
> - it allows you to run the script on the target machine using a local agent.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_MicrosoftDocs_vsts-2Ddocs_issues_6842-3Femail-5Fsource-3Dnotifications-26email-5Ftoken-3DANODFM574YPSU6ZIVNF6XHTQ4VS7NA5CNFSM4KD5UNI2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEILIR7A-23issuecomment-2D571902204&d=DwMCaQ&c=q3cDpHe1hF8lXU5EFjNM_A&r=oFssNtQE9vh6hiu-nY3tiBzxAg3lNa5Xnl0HmIYxKno&m=kl6QtrEsW3ttcpvlH-zNsI6DLqSVp8AB6hiHW3xvXOc&s=9hilfpsNDh4WhJP2EELLDhU_qJMNkCK9d8lHizsnP6s&e=>,
> or unsubscribe
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ANODFMY6QCPBTP25HNIS76TQ4VS7NANCNFSM4KD5UNIQ&d=DwMCaQ&c=q3cDpHe1hF8lXU5EFjNM_A&r=oFssNtQE9vh6hiu-nY3tiBzxAg3lNa5Xnl0HmIYxKno&m=kl6QtrEsW3ttcpvlH-zNsI6DLqSVp8AB6hiHW3xvXOc&s=HkHPrM4EGOZDZyUp9uBWwS5Uk7RsvEaiiTQUhuop5sE&e=>
> .
>

-- 


Your privacy is important to us. That is why we have taken appropriate 
measures to ensure the data you provide to us is kept secure. To learn more 
about how we process your personal information, how we comply with 
applicable data protection laws, and care for the security and privacy of 
your personal data, please review our Privacy Policy 
<https://www.motorolasolutions.com/en_us/about/privacy-policy.html#privacystatement>. 
If you have any questions related to data protection and compliance with 
applicable laws, please contact us at our Security Operations Center at 
1-302-444-9838 or mail us at: 

Attention: Privacy Compliance Program, P.O. 
Box 59263, Schaumburg, IL USA, 60159-0263

**Comment by RoopeshNair** [comment]
For privateIp scenario check out [Deployment Groups,](https://docs.microsoft.com/en-in/azure/devops/pipelines/release/deployment-groups/index?view=azure-devops) - it allows you to run the script on the target machine using a local agent.
