### ISSUE TITLE
Missing Information

### ISSUE THREAD

**Issue by dbuch0** [MicrosoftDocs/vsts-docs#6843]
Work items, work item types, and customizations &gt; Field names, work item tracking &gt; Restrictions

Looks like when I try to create a field with a special character(&) I get the error:
These characters are prohibited .,;'`:~\/\*|?"&%$!+=()[]{}&lt;&gt;-

This restriction is not provided in this document

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 82305566-bf0a-20ca-46b0-4a011ea65e0b
* Version Independent ID: 59b2347e-dc58-ee34-0000-c2c8eb309901
* Content: [Restrictions and conventions for naming - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/settings/naming-restrictions?view=azure-devops#feedback)
* Content Source: [docs/organizations/settings/naming-restrictions.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/settings/naming-restrictions.md)
* Product: **devops**
* Technology: **devops-settings**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by msebolt** [comment]
@dbuch0 Thank you for the feedback, assigning this to the author for review.

**Comment by KathrynEE** [comment]
@dbuch0  - Thank you for the feedback. You are correct about these restrictions. I will update the article to correct the restrictions.
