### ISSUE TITLE
UTCNOW() or UTCTODAY()?

### ISSUE THREAD

**Issue by mwc360** [MicrosoftDocs/vsts-docs#6845]
In DevOps expressions, how do you call something like UTCNOW or TODAY?

I want to do lt(eq(variables.date, UTCNOW())

Thanks

**Comment by msebolt** [comment]
@mwc360 Thank you for the question.

Please see if [this post](https://stackoverflow.com/questions/44738944/vsotfs-get-current-date-time-as-variable) addresses the issue.

If not, or for new features and support request, please contact the product team [here](https://developercommunity.visualstudio.com/spaces/21/index.html).

**Comment by msebolt** [comment]
Closing the issue now, please comment below if there are any questions.
