### ISSUE TITLE
Hiding a field

### ISSUE THREAD

**Issue by brillyints** [MicrosoftDocs/vsts-docs#6846]
There are two instances on this page that make reference to hiding a field from the form. However, it's not in the "supported actions" screenshot, nor can I see an option like this in my DevOps Server 2019 install. Based on the context where the word "hide" appears on the page, I assume the action has the same limitation as the user/group conditions (i.e. currently only supported in DevOps Services)... but if that is the case, it's definitely not clear.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4107b23a-ba0a-5a1b-b689-072717cfe8ec
* Version Independent ID: 1ed09ce9-be9b-6146-9cb8-a2a50e12a3c2
* Content: [Add a custom rule to a work item type - Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/organizations/settings/work/custom-rules?view=azure-devops-2019#restrict-modification-of-work-items-based-on-a-user-or-group)
* Content Source: [docs/organizations/settings/work/custom-rules.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/settings/work/custom-rules.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by msebolt** [comment]
@brillyints Thank you for the feedback, assigning this to the author for review.

**Comment by KathrynEE** [comment]
@brillyints - Thank you for pointing out the lack of clarity. I'm updating the article to reflect that the rules based on conditions of a group - "When current user is member of group..." and "When current user is not member of group ..." rules  -- are currently only available for Azure DevOps Services.

**Comment by brillyints** [comment]
@KathrynEE Well, based on your response, not quite. It already clearly states that group membership as a condition is only available in Services. What's *not* clear on the page (nor in your response) is whether the ability to *hide a field as an action* follows the same availability for Services/Server that the group membership condition does.
