### ISSUE TITLE
Document is not accurate enough, need change last run to last successful run.

### ISSUE THREAD

**Issue by liushuanggang** [MicrosoftDocs/vsts-docs#6848]
According the document [Scheduled triggers](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/triggers?view=azure-devops&tabs=yaml#scheduled-triggers) said:

> always: boolean # whether to always run the pipeline or only if there have been source code changes since the last run. The default is false.

But as test, this only works if the build pipeline is successfully built, if the build failed, the pipeline always run. the document said the latest run, did not specify that it needs to run successfully.

For the detailed info, you could check this ticket:

https://stackoverflow.com/questions/59611345/azure-cron-pipeline-always-runs

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5673ec1-c7d1-e0ac-043a-8fc3d5b226a9
* Version Independent ID: b4872831-51c0-6cf8-1c56-de20beb38a80
* Content: [Build pipeline triggers - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/triggers?view=azure-devops&tabs=yaml#scheduled-triggers)
* Content Source: [docs/pipelines/build/triggers.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/build/triggers.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by msebolt** [comment]
@liushuanggang Thank you for the feedback, assigning this to the author for review.

**Comment by vijayma** [comment]
Thanks for reporting this. We are updating the doc to clarify what the behavior of schedules is when the previous run failed.

**Comment by FrancoisM** [comment]
There seems to be a bug on that feature actually.
I don't know where to report it, can someone points me to the proper place to do so?

Below my pipeline scheduled for every hour.
We can see it ran the same push (so no change in code) every hour. It should not have since 'always' is false and every previous run was successful.

![image](https://user-images.githubusercontent.com/3176568/154422574-9cb4f518-7bd8-4eab-b2ad-efd29fff5582.png)
