### ISSUE TITLE
No longer includes install instructions

### ISSUE THREAD

**Issue by nschonni** [MicrosoftDocs/vsts-docs#685]
It appears this page has replaced the old https://java.visualstudio.com/Docs/tools/eclipse, but that version included the actual steps to install the plug-in  https://web.archive.org/web/20170924094318/https://java.visualstudio.com/Docs/tools/eclipse

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9419941b-8945-9d1a-b7b8-828ab950fdb6
* Version Independent ID: 00263573-2be4-aca9-8a51-0a5f15febb0a
* Content: [Get the Eclipse Plug-in for VSTS & TFS support](https://docs.microsoft.com/en-us/vsts/java/download-eclipse-plug-in?view=vsts)
* Content Source: [docs/java/download-eclipse-plug-in.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/java/download-eclipse-plug-in.md)
* Service: **unspecified**
* GitHub Login: @erickson-doug
* Microsoft Alias: **douge**

**Comment by steved0x** [comment]
@nschonni I've got a work item to get those fixed up, several parts didn't come across in the migration. Should be done next week, I'll keep this issue open until I have the fix checked in.

**Comment by nschonni** [comment]
@steved0x did the install instructions end up getting ported to a different page?

**Comment by steved0x** [comment]
@nschonni It looks like they have moved to here:

https://docs.microsoft.com/en-us/azure/devops/java/labs/eclipsegit/?view=vsts

I am going to fix up the links and make it easier to find, and that should be done today.

**Comment by steved0x** [comment]
OK I brought the steps back to this article instead of linking because that seemed to work better, it should be live later today.

**Comment by nschonni** [comment]
That's not quite the same thing since the old one covered both the offline and marketplace installs.

PS: that article has a broken image in the middle `![Sign in to Azure DevOps Services](../_img/eclipsegit/browseAzure DevOps Services.png)`

**Comment by steved0x** [comment]
I'll check that image, and see if I can restore the offline installation instructions as well.

**Comment by steved0x** [comment]
Image is fixed, I don't see the offline instructions on that page (maybe I'm looking in the wrong place), I do see some here, is that it: https://web.archive.org/web/20171219195443/http://www.microsoft.com:80/en-us/download/details.aspx?id=47727

**Comment by nschonni** [comment]
You're right, it's not on that page. I wonder which one I was thinking of then, or if that was additional docs we wrote ourselves. It's mainly the same flow as https://web.archive.org/web/20161018133103/https://msdn.microsoft.com/en-us/library/hh301122(v=vs.120).aspx, but talking about downloading from the release zip from https://docs.microsoft.com/en-ca/azure/devops/java/download-eclipse-plug-in?view=vsts#standalone-download-links and using the "Archive" button for the location
