### ISSUE TITLE
use the go task

### ISSUE THREAD

**Issue by KnicKnic** [MicrosoftDocs/vsts-docs#6850]
go get, go build, and go test should all reference the go task. https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/go?view=azure-devops

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b86b5c3a-d266-e9fe-621e-eb6244199984
* Version Independent ID: 57ca9f4f-ad07-4ab5-3153-9853e6b24797
* Content: [Build and test Go projects - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/ecosystems/go?view=azure-devops#feedback)
* Content Source: [docs/pipelines/ecosystems/go.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/ecosystems/go.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by msebolt** [comment]
@KnicKnic Thank you for the feedback, assigning this to the author for review.
