### ISSUE TITLE
Is Azure DevOps Services Basic Plan free for the first 5 users for commercial use?

### ISSUE THREAD

**Issue by degubellini** [MicrosoftDocs/vsts-docs#6857]
Hello,
I was reading this page (tab "Azure DevOps Services")

https://azure.microsoft.com/en-us/pricing/details/devops/azure-devops-services/

and I would like a clarification

is Azure DevOps Services Basic Plan free for the first 5 users for commercial use?

what "for the first 5 users" exactly means?

If a small company is working on 2 small projects of which

3 employees are working on the first project and 
4 employees are working on the second project

Would the basic plan still free?

Thanks,
De'

**Comment by msebolt** [comment]
@degubellini Thank you for the questions.

Yes, under Azure DevOps basic the first 5 users are free.

Please refer to [Add users](https://docs.microsoft.com/azure/devops/organizations/security/add-users-team-project) for an idea as to what each user represents.

For your example, it would remain free as long as there are no more than 5 **TOTAL** employees, and both projects are limited to 1 pipeline, see [this post](https://developercommunity.visualstudio.com/content/problem/356593/how-can-i-share-a-pipeline-between-multiple-projec.html) on sharing pipelines.

**Comment by degubellini** [comment]
Hi,
thank you for the quick feedback and for the useful links

I suppose that for total you mean between the 2 projects. 
So if in my example they are all distinct employees, the total would be 7 employees and therefore it would be not free. Is this correct?

**Comment by msebolt** [comment]
@degubellini Not a problem, thank you for your interest in Azure DevOps.

Yes, you're correct.

You would be charged $12 per month for 7 distinct users, and an additional $15 if you want each project to have their own pipeline (though both projects can also share).

**Comment by degubellini** [comment]
@msebolt 

Thanks!
