### ISSUE TITLE
How to see if an extension is being used?

### ISSUE THREAD

**Issue by jnxxx** [MicrosoftDocs/vsts-docs#6858]
How to see if an extension is being used in builds, releases etc?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4136c15d-672e-44b0-b42b-16b877deb381
* Version Independent ID: 16df8860-d655-b092-2f8b-aaa5d1b2e955
* Content: [FAQs about getting extensions for Azure DevOps - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/marketplace/faq-extensions?view=azure-devops)
* Content Source: [docs/marketplace/faq-extensions.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/marketplace/faq-extensions.md)
* Product: **devops**
* Technology: **devops-marketplace**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by msebolt** [comment]
@jnxxx Thank you for the question.

Please refer to the [Extension Management API](https://docs.microsoft.com/rest/api/azure/devops/extensionmanagement/installed%20extensions) for all current exposed functionaliy.

For suggestions or to solicit feedback from the product team, please start a thread [here](https://developercommunity.visualstudio.com/spaces/21/index.html).

**Comment by msebolt** [comment]
Closing the issue now, please comment below if there are any questions.
