### ISSUE TITLE
Restrict branches to merge into

### ISSUE THREAD

**Issue by Danghor** [MicrosoftDocs/vsts-docs#6861]
Is it possible to restrict the branch users can merge into. For example, to prevent feature-branches to be merged directly into the master branch, so feature-branches must be merged into the "develop" branch first ans only "develop" can be merged into master using a fast-forward merge.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7cd986e0-608c-1d8c-6faf-ecdb12e10bc6
* Version Independent ID: d60c996e-187e-dd6b-7f3a-dd056a1603f4
* Content: [Protect your Git branches with policies - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/branch-policies?view=azure-devops)
* Content Source: [docs/repos/git/branch-policies.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/repos/git/branch-policies.md)
* Product: **devops**
* Technology: **devops-code-git**
* GitHub Login: @apawast
* Microsoft Alias: **sdanie**

**Comment by msebolt** [comment]
@Danghor Thank you for the question.

Please to refer to [branch locking](https://docs.microsoft.com/azure/devops/repos/git/lock-branches) for assistance with your issue.

If you still find these features lacking, get feedback from the product team [here](https://developercommunity.visualstudio.com/spaces/21/index.html).

**Comment by msebolt** [comment]
Closing the issue now, please comment below if there are any questions.
