### ISSUE TITLE
Broken link under "This blog post"...

### ISSUE THREAD

**Issue by iamjyotirmoy** [MicrosoftDocs/vsts-docs#6865]
The link to https://blogs.msdn.com/b/visualstudioalm/archive/2015/10/04/automating-azure-resource-group-deployment-using-a-service-principal-in-visual-studio-online-build-release-management.aspx leads to a 404!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fb215324-b1a0-93b5-5022-4bcc7da93bb7
* Version Independent ID: 9eb2977b-ac34-9d53-670e-04fa027bc8e4
* Content: [Azure PowerShell task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-powershell?view=azure-devops#feedback)
* Content Source: [docs/pipelines/tasks/deploy/azure-powershell.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/deploy/azure-powershell.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by RoopeshNair** [comment]
removed the link as the content is out-dated
