### ISSUE TITLE
Why is the Stack Rank blank for some items?

### ISSUE THREAD

**Issue by johnyesberg** [MicrosoftDocs/vsts-docs#6866]
I have a (modified) CMMI project, and some of the backlog items (mostly Requirements and Tasks) don't have any values in the Stack Rank field. This means that I can't recreate the order of the items from a CSV export.
Is there something I can do to ensure that a Stack Rank value is assigned to every item (or at least every item that has a sibling)?
This question also asked on stackoverflow: 
https://stackoverflow.com/questions/59644746/how-do-i-ensure-all-azure-devops-backlog-items-have-a-stack-rank-value

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 02ab6fbc-4df4-bc2d-da58-19dee9395256
* Version Independent ID: e613f4a0-37a5-c2fa-fdf5-345c945de6db
* Content: [Backlogs for portfolios, priority, & multi-team ownership - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/backlogs/backlogs-overview?view=azure-devops#backlog-priority-or-stack-rank-order)
* Content Source: [docs/boards/backlogs/backlogs-overview.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/boards/backlogs/backlogs-overview.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by msebolt** [comment]
@johnyesberg Thank you for the feedback.

Stack Rank must be manually assigned by the user, please refer to issue https://github.com/MicrosoftDocs/vsts-docs/issues/1696.

For alternatives, such as re-ordering items through the [Reorder backlog API](https://docs.microsoft.com/rest/api/azure/devops/work/workitemsorder/reorder%20backlog%20work%20items), please see [Prioritize work](https://docs.microsoft.com/azure/devops/boards/queries/planning-ranking-priorities?view=azure-devops#fields-used-to-plan-and-prioritize-work).

**Comment by johnyesberg** [comment]
Thanks @msebolt 
Looks like I can rely on the order in the CSV export for rows that have no Stack Rank.
