### ISSUE TITLE
What is the difference between copying a file to ArtifactStagingDirectory and publishing?

### ISSUE THREAD

**Issue by lambdakris** [MicrosoftDocs/vsts-docs#6867]
What is the difference between copying a file to ArtifactStagingDirectory and publishing? Is it necessary to do both? What about if I don't copy the files into the ArtifactStagingDirectory and I just set pathtoPublish to some other location, say something like "$(Build.SourcesDirectory)/dist" (assuming that the build output get's placed in "dist"), what should I expect to happen then?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7175ebdc-0bba-7e00-d113-036a5cffe5fa
* Version Independent ID: 149ab9f4-0b7d-97e7-6cf5-1b54fd04c63c
* Content: [Publish and consume build artifacts in builds - Azure Pipelines and TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/build-artifacts?view=azure-devops&tabs=yaml#feedback)
* Content Source: [docs/pipelines/artifacts/build-artifacts.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/artifacts/build-artifacts.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @chasewilson
* Microsoft Alias: **phwilson**

**Comment by msebolt** [comment]
@lambdakris Thank you for the question.

The *ArtifactStagingDirectory* is a system property and can be changed/customized based on need, see [Build variables](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables#build-variables).

Even use of the publishing task isn't necessary (though helpful for locations such as **VSTS** servers), 
 for publishing to simple locations such as network shares, etc. the [Copy Files](https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/copy-files) task may be adequate, see [this post](https://stackoverflow.com/questions/46410457/what-is-the-difference-between-copy-files-vs-publish-artifact-task-in-vsts).

**Comment by msebolt** [comment]
Closing this issue, please comment below if there are any further questions.
