### ISSUE TITLE
IP address ranges incorrect?

### ISSUE THREAD

**Issue by ausfestivus** [MicrosoftDocs/vsts-docs#6869]
I have a Azure DB for PostgreSQL instance which has some configuration steps performed on it via ADO pipelines.
The PostgreSQL instance firewall is configured to permit connections from the IP addresses listed above.

As of just now, my pipeline has reported an error:
`* postgresql_role.tfe-role: pq: no pg_hba.conf entry for host "13.75.185.197", user "OBSFICATED", database "postgres", SSL on
`

The 13.75.n.n network isn't listed anywhere on this page as a network that is used by ADO.

Can someone on the ADO team please advise what is going on here?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc5a4cfa-aa84-9f0f-55f4-71ec4861c070
* Version Independent ID: d621620a-c924-03b1-8b43-f99c33e58bb8
* Content: [Add IP addresses and URLs to allow list - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/security/allow-list-ip-url?view=azure-devops#ip-addresses-and-range-restrictions)
* Content Source: [docs/organizations/security/allow-list-ip-url.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/security/allow-list-ip-url.md)
* Product: **devops**
* Technology: **devops-security**
* GitHub Login: @chcomley
* Microsoft Alias: **ChComley**

**Comment by msebolt** [comment]
@ausfestivus Thank you for the feedback, assigning this to the author for review.

This looks similar to the Postgres connectivity settings for **Austrailia East**, see [here](https://docs.microsoft.com/azure/postgresql/concepts-connectivity-architecture).

@kummanish

**Comment by chcomley** [comment]
@ausfestivus, I've reached out to our team and will be in touch. Sorry you're experiencing difficulties.

**Comment by chcomley** [comment]
Hi @ausfestivus, It appears as if this may be some kind of role issue with Postgres, and could be specific to your setup. Since it doesn't particularly have to do with documentation, please submit your issue [here](https://developercommunity.visualstudio.com/spaces/21/index.html). Select **Report a problem**. Thank you.

**Comment by ausfestivus** [comment]
Hi @chcomley 

Can you please provide some more background to what led you to conclude its a problem with my setup?

Thankfully there hasn't been a repeat of the problem and thats with some very heavy usage/deployment.

**Comment by chcomley** [comment]
@ausfestivus, I'm glad there hasn't been a repeat of the problem! I didn't make any conclusions - an engineer contact mentioned that it could be part of your setup. Unfortunately that's all I have.
