### ISSUE TITLE
link broken (vs enterprise subscription)

### ISSUE THREAD

**Issue by LyalinDotCom** [MicrosoftDocs/vsts-docs#687]
Link above to "Visual Studio Enterprise subscription" goes to 404.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7d9d52f6-bbec-1b70-3624-5fbfb621b932
* Version Independent ID: 08466892-dd17-abc6-ebdb-96a0e07f83d0
* Content: [URL-based load testing with VSTS](https://docs.microsoft.com/en-us/vsts/load-test/get-started-simple-cloud-load-test?view=vsts#feedback)
* Content Source: [docs/load-test/get-started-simple-cloud-load-test.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/load-test/get-started-simple-cloud-load-test.md)
* Service: **unspecified**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by steved0x** [comment]
This link is fixed.
