### ISSUE TITLE
How/when to use continuous improvement & Maturity Assessment work items

### ISSUE THREAD

**Issue by karunakaranck** [MicrosoftDocs/vsts-docs#6871]
I have been searching for resources to know better  about the usage and recommendation on continuous improvement & Maturity Assessment work items. However, i could not succeed in finding an URL to read about them. Can you please through some light on the availability of tutorial items with the URLs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a197bf55-89c7-682d-bb1c-e82bec732349
* Version Independent ID: 5aa2afac-cb82-3f72-643c-25a0173cce98
* Content: [Using work items to track user stories, & more - Azure Boards and TFS](https://docs.microsoft.com/en-us/azure/devops/boards/work-items/about-work-items?view=azure-devops&tabs=agile-process#feedback)
* Content Source: [docs/boards/work-items/about-work-items.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/boards/work-items/about-work-items.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by karunakaranck** [comment]
Still I don't find details for the work items i had referred in our query.

**Comment by msebolt** [comment]
@karunakaranck Thank you for the feedback, assigning this to the author for review.

Is this in reference to the [CMMI model](https://docs.microsoft.com/azure/devops/boards/work-items/guidance/cmmi/guidance-background-to-cmmi)?

If so, please refer to the model's [process](https://docs.microsoft.com/azure/devops/boards/work-items/guidance/cmmi-process?view=azure-devops) and [work item types](https://docs.microsoft.com/azure/devops/boards/work-items/guidance/cmmi-process-workflow) for basic guidance.

**Comment by KathrynEE** [comment]
@karunakaranck - I'm updating the topic to provide links to the detail information on each process model. As noted, there is more information provided in [CMMI process](https://docs.microsoft.com/azure/devops/boards/work-items/guidance/cmmi/guidance-background-to-cmmi).
