### ISSUE TITLE
Availability for Azure DevOps Server ?

### ISSUE THREAD

**Issue by lezardo** [MicrosoftDocs/vsts-docs#6874]
Hi, 
do you have an idea when auditing feature will be available for Azure DevOps Server ? 
Especially regarding permission updates. 

In "Features Timeline" page [https://docs.microsoft.com/en-us/azure/devops/release-notes/features-timeline] it's only mentioned: | Auditing for Azure Repos events |   Repos	|   2020 | .

Does it mean we will have same "Auditing" featuire as it is now in a Public Preview on Azure DevOps Services ?

Thanks,
Lezardo

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 52f60b32-5c3c-f01a-cbbf-f4e9bd17a3fc
* Version Independent ID: 94753ea7-b465-f92e-10c2-8b17d995e4ff
* Content: [Access, export, filter audit logs for Azure DevOps - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/settings/azure-devops-auditing?toc=%2Fazure%2Fdevops%2Fsecurity-access-billing%2Ftoc.json&bc=%2Fazure%2Fdevops%2Fsecurity-access-billing%2Fbreadcrumb%2Ftoc.json&view=azure-devops&tabs=preview-page&viewFallbackFrom=azure-devops-2019#feedback)
* Content Source: [docs/organizations/settings/azure-devops-auditing.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/settings/azure-devops-auditing.md)
* Product: **devops**
* Technology: **devops-settings**
* GitHub Login: @roferg
* Microsoft Alias: **chcomley**

**Comment by msebolt** [comment]
@lezardo Thank you for the question.

Unfortunately the only information available to the authors is located on the [features timeline](https://docs.microsoft.com/azure/devops/release-notes/features-timeline) referenced above.

You will need to either look for updates using the [Azure DevOps blogs](https://devblogs.microsoft.com/devops/) or submit the request [here](https://developercommunity.visualstudio.com/spaces/21/index.html) for feedback from the product team.

**Comment by msebolt** [comment]
Closing the issue, please comment below if there are any further questions.
