### ISSUE TITLE
Talk page instead of comments at the bottom of entries

### ISSUE THREAD

**Issue by ujaya** [MicrosoftDocs/vsts-docs#6876]
Has there been any discussion of moving to the more standard wiki approach of having a talk page for each entry, rather than a comments section at the bottom of each entry? The comments section can get big and confusing for readers not involved in the maintenance of the wiki. This makes leveraging the ADO wiki feature for reference amongst partner teams and internal customers less than desirable. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c85ebb83-c49f-e784-70b5-30c0ac01682b
* Version Independent ID: dc859870-0b8f-bee5-0b2f-e6b2aa3260c6
* Content: [Add comments to wiki pages - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/project/wiki/add-comments-wiki?view=azure-devops#feedback)
* Content Source: [docs/project/wiki/add-comments-wiki.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/project/wiki/add-comments-wiki.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by msebolt** [comment]
@ujaya Thank you for the feedback.

You can refer to [this](https://developercommunity.visualstudio.com/content/idea/379601/ability-to-comment-wiki-content-like-in-pull-reque.html) open item in the developer community which is currently being scheduled for release.

If this request is different, please add your comments there or you can start a new thread [here](https://developercommunity.visualstudio.com/spaces/21/index.html).

**Comment by msebolt** [comment]
Closing the issue, please comment below if there are any further questions.
