### ISSUE TITLE
Link broken: https://www.visualstudio.com/support/subscription-support-vs

### ISSUE THREAD

**Issue by nschonni** [MicrosoftDocs/vsts-docs#688]
Referenced in docs/_shared/qa-visual-studio-subscription-support.md and docs/accounts/faq-set-up-vs.md

**Comment by steved0x** [comment]
@chcomley I was mistaken for this one, redirect not yet in place.

**Comment by steved0x** [comment]
I'm taking this one back since I have several others like it.

**Comment by steved0x** [comment]
This link is fixed.
