### ISSUE TITLE
Please Update Documentation!!!

### ISSUE THREAD

**Issue by webskydavid** [MicrosoftDocs/vsts-docs#6884]
Please Update documentation, tons of old stuff. You provide new library but documentation sucks. I can't work with this

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0f99e26d-54fa-ac2c-1814-e1b3f97a87b5
* Version Independent ID: 0ed84e7f-b46f-3a44-16f6-d9bcf77bf11d
* Content: [How to Call a REST API - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/extend/develop/call-rest-api?view=azure-devops#feedback)
* Content Source: [docs/extend/develop/call-rest-api.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/extend/develop/call-rest-api.md)
* Product: **devops**
* Technology: **devops-ecosystem**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by msebolt** [comment]
@webskydavid Thank you for the feedback, our apologies for the current state of the documentation.

Please provide some details and/or examples on what changes you'd like to see and we can fix them accordingly.

**Comment by webskydavid** [comment]
All of them, especially documentation about DevOps Extension Development. There are tons of old stuff. In some places you write about using SDK. But you mostly write about some outdated VSS library that does not much the SDK library. The whole documentation need an rewrite.
I spent most time (70%) to searching documentation.

**Comment by msebolt** [comment]
@webskydavid Thank you for the clarification and for including examples.

Again, we apologize for any outdated examples and will work harder to improve the doc set with regard to more current API scenarios.

Adding @chcomley for visibility.

Closing the issue now, please contact us again if there are additional issues.
