### ISSUE TITLE
Error: kill ESRCH on Post-job: InstallSSHKey

### ISSUE THREAD

**Issue by andrewCluey** [MicrosoftDocs/vsts-docs#6888]
Recently deployed a few new agent VMs to provide more capacity for our deployments. Since then we are getting an odd error on the InstallSSHKey task.

In our pipeline we have a pre-job task to install SSH keys right at the start of the run, this succeeds. 

The rest of the job continues without issue and runs fine. However, the Post-job: InstallSSHKey task fails with the error:
##[error]Error: kill ESRCH

Nothing obvious in log files, other than it records it failing (Step result: failed).

Seems to fail multiple times, across different pipelines, more often than not it fals on tis same task. So far I've seen this task succeed.

Any help appreciated.
Thanks

**Comment by msebolt** [comment]
@andrewCluey Thank you for the feedback.

This could be a result of https://github.com/microsoft/node-pty/issues/45, so make sure you're using the latest version of the task.

Unfortunately, our support options in the documentation forum are limited to the provided scenarios.  Please move this issue to the [azure-pipelines-tasks](https://github.com/Microsoft/azure-pipelines-tasks/issues) repo for further assistance.

**Comment by WilliamAntonRohm** [comment]
I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
