### ISSUE TITLE
Is there any way to trigger on a Pipeline being merged/closed?

### ISSUE THREAD

**Issue by eschwartz** [MicrosoftDocs/vsts-docs#6889]
We have PR builds that create artifacts outside the pipeline, that I would like to be able to cleanup when the PR is merged or closed. Is there any way to trigger a build on a PR being closed?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5673ec1-c7d1-e0ac-043a-8fc3d5b226a9
* Version Independent ID: b4872831-51c0-6cf8-1c56-de20beb38a80
* Content: [Build pipeline triggers - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/triggers?view=azure-devops&tabs=yaml#q--a)
* Content Source: [docs/pipelines/build/triggers.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/build/triggers.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by msebolt** [comment]
@eschwartz Thank you for the question.

Please refer to either [continuous integration](https://stackoverflow.com/questions/58089501/azure-devops-how-to-trigger-a-release-upon-pull-request-being-completed) or using the [build REST API](https://stackoverflow.com/questions/52718462/trigger-azure-pipelines-build-via-api).

If you need the REST option it will require a configuring a [service hook](https://docs.microsoft.com/azure/devops/service-hooks/services/webhooks?view=azure-devops) to get the [status of the PR](https://docs.microsoft.com/rest/api/azure/devops/build/source%20providers/get%20pull%20request?view=azure-devops-rest-5.0).

Please note our support options are limited to documented scenarios only, for additional support options, see:

- [Azure DevOps Support](https://azure.microsoft.com/support/devops/)
- [Azure DevOps on StackOverflow](https://stackoverflow.com/questions/tagged/azure-devops)

**Comment by WilliamAntonRohm** [comment]
I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
