### ISSUE TITLE
What is the different between Basic + Test Plans & VS Enterprise

### ISSUE THREAD

**Issue by angelwang** [MicrosoftDocs/vsts-docs#6891]
[Enter feedback here]
In the feature list table, Basic + Test Plans & VS Enterprise are combined in the same column. 
So I am wondering if there is any different between them, if not, why we have 2 separate access levels?

Thanks,
Angel

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8db47b85-e178-7969-40d3-3fa83aa3fb54
* Version Independent ID: a78e453b-4b8f-c885-42ee-8a9d9979f345
* Content: [What are access levels? What access levels are supported? - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/security/access-levels?view=azure-devops)
* Content Source: [docs/organizations/security/access-levels.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/security/access-levels.md)
* Product: **devops**
* Technology: **devops-security**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by msebolt** [comment]
@angelwang Thank you for feedback.

The one difference noted is for **web test management**:

![Capture](https://user-images.githubusercontent.com/6675884/72278025-f60d3680-35e7-11ea-8c1d-26b019cd4166.PNG)

For a more complete table of version features, please refer to the [Visual Studio compare](https://visualstudio.microsoft.com/vs/compare/) page.

**Comment by WilliamAntonRohm** [comment]
I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
