### ISSUE TITLE
No instructions to install private extensions

### ISSUE THREAD

**Issue by ez-ms** [MicrosoftDocs/vsts-docs#6892]
I am developing a new extension, and it's still private until I finish the development. I'd like to install it on a Server instance so I can test on that environment. However, following the instructions above get me stuck just after clicking "Get" on the marketplace page. It shows a never-ending loading indicator.
Is this an issue, or is there any limitations to installing private extensions?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 46849bf5-07ed-62cd-66a5-2ebabe449855
* Version Independent ID: d12ad05e-4348-f13a-ea35-7bb4761c3b0b
* Content: [Install extensions for on-premises servers - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/marketplace/get-tfs-extensions?view=azure-devops-2019)
* Content Source: [docs/marketplace/get-tfs-extensions.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/marketplace/get-tfs-extensions.md)
* Product: **devops**
* Technology: **devops-marketplace**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by msebolt** [comment]
@ez-ms Thank you for the question.

You can refer to **Why can't I install extensions?** in the [FAQ](https://docs.microsoft.com/azure/devops/marketplace/faq-extensions) for possible solutions, or find additional information [here](https://docs.microsoft.com/azure/devops/extend/publish/overview) and/or by running through the [extensions quickstart](https://docs.microsoft.com/azure/devops/marketplace/install-extension).

Please note our support options provided in the documentation forum are limited to the provided scenarios.

For additional support, please see:

- [Azure DevOps Support](https://azure.microsoft.com/support/devops/)
- [Azure DevOps on StackOverflow](https://stackoverflow.com/questions/tagged/azure-devops)

**Comment by WilliamAntonRohm** [comment]
I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.

**Comment by jacksoncds** [comment]
Having the same issue, never ending loading when trying to install private extension on a premise server. I am able to install public extensions fine.
