### ISSUE TITLE
404

### ISSUE THREAD

**Issue by michaelmcdaniel** [MicrosoftDocs/vsts-docs#6893]
following links result in 404:
CI/CD pipeline examples [https://blogs.msdn.microsoft.com/visualstudioalmrangers/tag/cicd-pipeline/]
Configuring your release pipelines for safe deployments [https://blogs.msdn.microsoft.com/visualstudioalm/2017/04/24/configuring-your-release-pipelines-for-safe-deployments/]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 076cd358-0935-41ac-ed07-96ac5ce4c914
* Version Independent ID: 17f39a3c-db2f-37d1-05d1-e1387e0297e8
* Content: [Progressively expose your releases using deployment rings - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/migrate/phase-rollout-with-rings?toc=%2Fazure%2Fdevops%2Fpipelines%2Ftoc.json&bc=%2Fazure%2Fdevops%2Fpipelines%2Fbreadcrumb%2Ftoc.json&view=azure-devops#feedback)
* Content Source: [docs/migrate/phase-rollout-with-rings.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/migrate/phase-rollout-with-rings.md)
* Product: **devops**
* Technology: **devops-migrate**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by msebolt** [comment]
@michaelmcdaniel Thank you for the feedback.

The first link seems to be up again, https://blogs.msdn.microsoft.com/visualstudioalmrangers/tag/cicd-pipeline/.

The documentation has been updated to remove the second link.

Please consider [becoming a contributor](https://docs.microsoft.com/contribute) with **Microsoft Docs**.
