### ISSUE TITLE
outdated screen shot and instructions

### ISSUE THREAD

**Issue by RoyKimYYZ** [MicrosoftDocs/vsts-docs#69]
For line "Go to More services > Developer tools > VSTS accounts. Select your VSTS account."

In my azure portal, I can't seem to find Team services accounts as instructed. Therefore seems outdated.

**Comment by steved0x** [comment]
It should be under All services->Developer Tools->Team Services accounts. Or you can just type Team Services into the Filter box at the top. Which article had this guidance and I'll take a look and see if I can get the screenshot updated.

![image](https://user-images.githubusercontent.com/1580889/34539443-7ae3a146-f09e-11e7-9ecc-8c17b5c17007.png)

**Comment by RoyKimYYZ** [comment]
Steve,


I found it it by scrolling down to the dev tools section. The other day I couldn't find by searching. But now I can search. weird.


Thanks for the help.

cheers,
Roy

________________________________

**Comment by steved0x** [comment]
@RoyKimYYZ My pleasure! Glad you were able to find it.
