### ISSUE TITLE
"Too high level" article not very useful

### ISSUE THREAD

**Issue by CESARDELATORRE** [MicrosoftDocs/vsts-docs#6900]
I think this article is a "Too high level" article and because of that it is not providing very useful information.
It should probably be removed or dramatically changed. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fa0194a9-ffa7-fa79-e6c7-8ecb5e8c93ec
* Version Independent ID: 4f5a9f04-b629-b8b1-1332-9260c95d13b7
* Content: [Azure Machine Learning training and deployment - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/targets/azure-machine-learning?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/targets/azure-machine-learning.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/targets/azure-machine-learning.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @azooinmyluggage
* Microsoft Alias: **atulmal**

**Comment by msebolt** [comment]
@CESARDELATORRE Thank you for the feedback, we're sorry you're having issues with the documentation.

Is there anything in particular that doesn't work with the given example?  If you provide further details on what should be changed we can assign this to the author for review.

For general descriptions, please refer to [Azure Pipelines](https://docs.microsoft.com/azure/devops/pipelines/?view=azure-devops) and [Azure Machine Learning](https://docs.microsoft.com/azure/machine-learning/).

**Comment by msebolt** [comment]
Closing this issue now, please comment below if there are additional questions.
