### ISSUE TITLE
AZURE_DEVOPS_EXT_PAT -- never worked

### ISSUE THREAD

**Issue by swapnild2111** [MicrosoftDocs/vsts-docs#6905]
Hello Team,
I have followed the steps you suggested. However the approach AZURE_DEVOPS_EXT_PAT never worked for me.
Solutions worked for me is: echo $AZURE_DEVOPS_EXT_PAT | az devops login
I do not want to echo since am exposing PAT on command line.
Am I missing something?

**Comment by WilliamAntonRohm** [comment]
@swapnild2111 -- Swapnil, thanks for your feedback; we appreciate it. To make sure we have all the information needed to triage your issue, please let us know which topic you’re referencing, or provide more context around your general task.

**Comment by jhealy** [comment]
Use echo to push it in, as in this gent's article.  [(https://medium.com/objectsharp/azure-cli-azure-devops-extension-7b77a7623911)] .  MSFT docs dont really show this.  Tested and it works.       

`echo $env:AZURE_DEVOPS_EXT_PAT | az devops login --org $ORG `
