### ISSUE TITLE
Explain 'pipeline' and 'source' entries better for pipeline triggers

### ISSUE THREAD

**Issue by cacti77** [MicrosoftDocs/vsts-docs#6913]
I want to trigger one pipeline from another but it's not clear to me what values I should use for the 'pipeline' and 'source' items under 'pipelines:'.

Is the 'pipeline' value a completely arbitrary name I can make up to define the pipeline resource (e.g., 'security-lib')? In other words I can pretty much call it anything I want because it's not referring to anything else?

But does the value of 'source' have to match the name of the triggering pipeline as listed under Pipelines in the Azure web UI?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5673ec1-c7d1-e0ac-043a-8fc3d5b226a9
* Version Independent ID: b4872831-51c0-6cf8-1c56-de20beb38a80
* Content: [Build pipeline triggers - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/triggers?view=azure-devops&tabs=yaml#pipeline-triggers)
* Content Source: [docs/pipelines/build/triggers.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/build/triggers.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by majusmisiak** [comment]
Same question here, while pipeline seems to be arbitrary name, that can be referenced later, but source is totally unclear.
Is `source` the

1. name of the resource pipeline?
2. ID (integer) of the resource pipeline?
3. Name of the git repository where the pipeline is defined?

If (1), which I assume - how are conflicts handled if multiple pipelines have the same name (__e.g.__ "security-lib" as in OP)? What is the referenced pipeline is in some directory, like "Tools\security-lib"?

**Comment by mcelrojb58** [comment]
So is the resource pipeline name the common name seen by users in DevOps or is it the name of the yaml file that the pipeline is watching?

**Comment by cacti77** [comment]
I have working pipelines triggering other pipelines now. The `pipeline` value appears to be completely arbitrary. The value of `source` must match the name of the triggering pipeline as it appears to users in the DevOps UI (e.g., under `your-org/your-project/Recent`. I've already found that if you rename your triggering pipeline then you must update the value of `source` to match it or else your pipeline trigger will fail.

**Comment by juliakm** [comment]
Related issue: https://github.com/MicrosoftDocs/vsts-docs/issues/7201

**Comment by cacti77** [comment]
@steved0x Err, why has this been closed please? The docs at https://docs.microsoft.com/en-us/azure/devops/pipelines/build/triggers?view=azure-devops&tabs=yaml#pipeline-triggers still look the same to me.

**Comment by steved0x** [comment]
@cacti77 @mcelrojb58 @majusmisiak Sorry I just saw this one, it got closed due to being referenced in a PR that added some more detail to the [Pipeline resource](https://review.docs.microsoft.com/en-us/azure/devops/pipelines/process/resources?view=azure-devops&branch=master&tabs=schema#resources-pipelines) schema.

I'm working on the Pipeline triggers section right now and it will have more detail and examples shortly. Sorry for the long delay and thank you.

**Comment by steved0x** [comment]
@cacti77 @mcelrojb58 @majusmisiak I am publishing an update to the article that answers your questions, including what the source element is, what to use for the name (including if it is in a different project or organization).

**Comment by cacti77** [comment]
@steved0x - thank you! That docs entry on pipeline triggers is much clearer now.
