### ISSUE TITLE
Template references and checkout do not work together or syntax is not clear

### ISSUE THREAD

**Issue by CoolDadTx** [MicrosoftDocs/vsts-docs#6919]
Given the documentation on template references and the documentation on checkout it seems like something like this should work.

```yaml
variables:
   somePath: path
```
```yaml
variables:
   template: myvariables.yml

steps:
- checkout: self
  path: ${{ variables.somePath }}
```
But it returns an empty string and is ignored. Using `$(somePath)` also doesn't work. 

Please document the correct syntax to use variables defined in a template for things like `checkout` paths.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7458d5b2-1bb7-7d87-7ce6-2b0c430b0155
* Version Independent ID: edf5bbd3-a3f0-5426-e985-31290f8afd05
* Content: [YAML schema - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=example#variable-templates)
* Content Source: [docs/pipelines/yaml-schema.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/yaml-schema.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by msebolt** [comment]
@CoolDadTx  Thank you for the feedback.

This issue was recently brought to our attention, please refer to https://github.com/MicrosoftDocs/vsts-docs/issues/6894.
