### ISSUE TITLE
Can you elaborate on the scope in which the build run?

### ISSUE THREAD

**Issue by alvipeo** [MicrosoftDocs/vsts-docs#6920]
This
"You can check the scope in which your builds run by opening the editor for your build pipeline, and looking at the Options tab"
IS NOT ENOUGH. I've been trying to fix this error for about an hour now!
&gt; Response status code does not indicate success: 403 (Forbidden - User '419a0839-...' lacks permission to complete this action. You need to have 'ReadPackages'.

What is this user?? Where to find it???

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 11ed58a1-5819-f3a4-c674-dafcdbd56fbc
* Version Independent ID: d68aca4d-3fd3-1864-09f5-6060295e0399
* Content: [Publishing to NuGet feeds - Azure Pipelines and TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/nuget?toc=%2Fazure%2Fdevops%2Fartifacts%2Ftoc.json&bc=%2Fazure%2Fdevops%2Fartifacts%2Fbreadcrumb%2Ftoc.json&view=azure-devops&tabs=classic)
* Content Source: [docs/pipelines/artifacts/nuget.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/artifacts/nuget.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @chasewilson
* Microsoft Alias: **phwilson**

**Comment by msebolt** [comment]
@alvipeo Thank you for the feedback, we're sorry you're experiencing issues.

Please refer to the possibly related incident in [this post](https://developercommunity.visualstudio.com/content/problem/800078/nuget-restore-tasks-throws-403-using-azure-devops.html) to see if you can resolve the issue.

**Comment by alvipeo** [comment]
Yeah, I found this one yesterday - https://developercommunity.visualstudio.com/content/problem/795493/403-error-during-nuget-restore.html

But guys, please fix this and make appropriate changes in the docs! Thanks!

**Comment by msebolt** [comment]
Closing the issue now since this is product-related incident. 

Please contact us again if there are further issues.
