### ISSUE TITLE
How to escape focus on a multiline text

### ISSUE THREAD

**Issue by vairakkumar-vairaperumal** [MicrosoftDocs/vsts-docs#6921]
How to escape focus on a multiline text, ex acceptance criteria, show can switch from markdown text editor to visualization.
Currently the only way to do is to by moving the KB focus to a different field by using mouse click outside the field. Can escape key be mapped for escaping edit mode on that field, and insert key (or what is industry standard) for editing texts

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 02128227-c915-a0d9-f919-c1ef2a3b834f
* Version Independent ID: bf4402f5-f9fe-a6d0-3738-01e2aca27209
* Content: [Shortcuts for work item form and Work Items hub - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/work-items/work-item-form-keyboard-shortcuts?view=azure-devops&viewFallbackFrom=vsts)
* Content Source: [docs/boards/work-items/work-item-form-keyboard-shortcuts.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/boards/work-items/work-item-form-keyboard-shortcuts.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @thomps23
* Microsoft Alias: **kaelli**

**Comment by msebolt** [comment]
@vairakkumar-vairaperumal Thank you for the question.

Keyboard shortcuts are based off rules for [Visual Studio shortcuts](https://docs.microsoft.com/visualstudio/ide/identifying-and-customizing-keyboard-shortcuts-in-visual-studio?view=vs-2015#bkmk_assign), so `Esc` is allowed, but not `Insert`.

For a list current shortcuts involving change of focus, please refer to [keyboard shortcuts](https://docs.microsoft.com/azure/devops/project/navigation/keyboard-shortcuts).

If there are still issues, it is likely a better issue for the product team to address, please start a thread [here](https://developercommunity.visualstudio.com/spaces/21/index.html).

**Comment by vairakkumar-vairaperumal** [comment]
@msebolt That should be a bug then. Escape key does not stop editing of texts in Acceptanct Criteria and Description fields

**Comment by msebolt** [comment]
@vairakkumar-vairaperumal Thank you for the update.

For bugs and other product-related issues, please use [report a problem](https://developercommunity.visualstudio.com/content/problem/post.html?space=21) for feedback from the product team.

**Comment by msebolt** [comment]
Closing this issue now.

Please feel free to contact us again if there are any additional questions or issues.
