### ISSUE TITLE
System.AccessToken default scope

### ISSUE THREAD

**Issue by ggirard07** [MicrosoftDocs/vsts-docs#6924]
What is the default scope of `System.AccessToken`?
More specifically, does it allow accessing any project in the organization, or only the current project the pipeline is associated with?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ffebdc8-521c-44b5-cde4-4abdc1bd6f18
* Version Independent ID: dc0effda-6d93-62aa-64c5-4e6f283b0826
* Content: [Predefined variables - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml#system-variables)
* Content Source: [docs/pipelines/build/variables.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/build/variables.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by msebolt** [comment]
@ggirard07 Thank you for the question.

The `System.AccessToken` corresponds to the service account so this would depend on the project's permissions, please see if [this post](https://developercommunity.visualstudio.com/content/problem/618929/what-is-the-scope-of-the-token-in-systemaccesstoke.html) answers your question.

@juliakm

**Comment by ggirard07** [comment]
@msebolt Not sure to understand how it can help me define whether the `System.AccessToken` available on my agent is suppose to give access to resources outside current project... Maybe some precision on my use-case could help.

From npm package `azure-devops-node-api`, I want to get detailed information from a pipeline runId (available from environment variable `resources.pipeline.${pipelineName}.runId`). For this, I use [`IBuildApi.getBuild(runId)`](https://github.com/microsoft/azure-devops-node-api/blob/v6.6.2/api/BuildApi.ts#L544) to retrieve the information I need.

- If I use a PAT I created manually I am able to retrieve any build information. This PAT is scoped by default to the entire organization and I can't scope it to a single project using the UI in Azure DevOps to create PAT.
- If I do the exact same thing but from a task executing in a pipeline using an hosted agent (in that case, using `System.AccessToken` instead of my own PAT), then I can't retrieve any information about pipelines/builds defined outside the project the pipeline lives in. The error I get in this case is
```log
S800075: The project with id 'vstfs:///Classification/TeamProject/be1e824d-3454-4cf5-9bbd-7d52db263d99' does not exist, or you do not have permission to access it.
```

That's why I am wondering if `System.AccessToken` is scoped to the current project in any way, or if the current limitation I see is due to anything else. Especially since the introduction of [YAML resources](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema#resources), it is now possible to access resources between projects.

**Comment by ggirard07** [comment]
I think I just found what is confirming default configuration for `System.AccessToken` is scoped to the current project only. Option is enabled by default in my case.

![image](https://user-images.githubusercontent.com/2625886/72379961-6dbf8c00-36e2-11ea-963c-247c76e9b1ae.png)

**Comment by ggirard07** [comment]
So I think I sorted this out... but some documentation on this could actually really help out!

**Which identity is used to generate the  `System.AccessToken`?**
- When the option shown in my previous post `Limit job authorization scope to current project` is enabled (default value for me), then the `System.AccessToken` is associated to a project specific user named as `{projectName} Build Service ({organizationName})`. This user is most of the time not listed anywhere by default. Only solution for me to find it was to go to "Project Settings > Permissions > Users", then perform a search on "MyProjectName" and finally select the "Expand Search" option.
- When the option is not activated, then the `System.AccessToken` is associated to a global group (organization wide) named `Project Collection Build Service Accounts`.


**How to keep `Limit job authorization scope to current project` enabled while allowing cross-project access?**
The project specific user (`{projectName} Build Service ({organizationName})`) needs to be part of the `Project Valid Users` group under `Permissions` of the "target" project. That group can't be modified directly, so you need to either add this user to any other existing group in the project (and grant him the associated rights), or to create a new, dedicated, group where you can select the appropriate rights (in my case, only "View project-level information" set to "Allow").  
Once this is done, you need to be sure the user has appropriate rights for the task you intend to perform. For example, if you want to access a pipeline run result (as I was trying to do), you need to go to the project > "Pipelines" > Click on the "3 dots" (top right) > "Manage Security" (or at a specific pipeline level), then search for the user `{projectName} Build Service ({organizationName})` and finally set its "View builds" permission to "Allow".

Hopes this can help anyone in the same situation as me until/unless Microsoft document this properly!

**Comment by ggirard07** [comment]
And finally once I know what I actually need, I am able to find [a well built documentation about all of it](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/options?view=azure-devops#build-job-authorization-scope)!  
Only issue is this looks specific to "Classic Build" while it is actually not and applies very well to YAML pipeline.

Looks like I need to work on my googling skills :)

**Comment by WilliamAntonRohm** [comment]
@ggirard07 -- thank you for your researches and followup.
