### ISSUE TITLE
How to verify correctness for this function

### ISSUE THREAD

**Issue by magina2019** [MicrosoftDocs/vsts-docs#6926]
This function is amazing. But Git usage is flexible, like our developers may merge other branchs (which links to other work items) to their own branch, this maybe complicates commit history. So How to verify correctness for this function use more theoretical evidence?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 462be419-4cfd-4bfc-06cc-45800c0d888b
* Version Independent ID: 95cb8a7d-c61d-dfac-403f-12fe40ba1c49
* Content: [Link work items to deployments - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/work-items/work-item-deployments-control?view=azure-devops#feedback)
* Content Source: [docs/boards/work-items/work-item-deployments-control.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/boards/work-items/work-item-deployments-control.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by msebolt** [comment]
@magina2019 Thank you for the question.

Correctness would need to be implemented with added functionality (or use an [extension](https://docs.microsoft.com/azure/devops/extend/overview?view=azure-devops), [service hooks](https://docs.microsoft.com/azure/devops/service-hooks/overview?view=azure-devops), or [REST API](https://docs.microsoft.com/rest/api/azure/devops/?view=azure-devops-rest-5.1)), and needs to be directed to the product team.  

Please see [this post](https://developercommunity.visualstudio.com/content/problem/883624/how-to-verify-correctness-for-link-work-items-to-d.html) for more info.

**Comment by msebolt** [comment]
Closing this issue now, please comment below if there are additional questions.
