### ISSUE TITLE
Invalid link to "How to discover menu group identifiers"

### ISSUE THREAD

**Issue by CodeRunRepeat** [MicrosoftDocs/vsts-docs#6929]
The page linked to from the groupId property documentation (https://docs.microsoft.com/en-us/azure/devops/extend/test/discover-menu-group-ids?view=azure-devops) is not available.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 19c5725d-4a59-7019-7dd8-c77be8456e45
* Version Independent ID: b45dc1c1-3ba0-b517-8aa8-c947cfc1f2a2
* Content: [Add an Action - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/extend/develop/add-action?view=azure-devops&source=docs#feedback)
* Content Source: [docs/extend/develop/add-action.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/extend/develop/add-action.md)
* Product: **devops**
* Technology: **devops-ecosystem**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by msebolt** [comment]
@CodeRunRepeat Thank you for the feedback.

The documentation has been updated and is pending review.

For future edits and/or change requests, please consider [becoming a contributor](https://docs.microsoft.com/contribute).

**Comment by Nardax** [comment]
3 months later and the link is still broken - when will the review be completed?

**Comment by Nardax** [comment]
So I went and looked at the open PRs to see if I could get a glympse and the upcoming fix. I don't see anything fixed and worse than then that it shows that @msebolt resolved the issue as "closed" the day after it was reported.

**Comment by Nardax** [comment]
The file got deleted but here is a link to an old version that worked for me. Thank you GIT! 
https://github.com/MicrosoftDocs/vsts-docs/blob/739fb3085a1ca0554775e02012441836fe7e17a5/docs/extend/test/discover-menu-group-ids.md

**Comment by msebolt** [comment]
The previously added redirect wasn't clear, so the link has now been removed.

To discover menu group identifiers, you'll need to use the [REST API](https://docs.microsoft.com/azure/devops/extend/develop/call-rest-api).
