### ISSUE TITLE
Doublet (Add a team admin)

### ISSUE THREAD

**Issue by MTRH** [MicrosoftDocs/vsts-docs#6930]
Hi
In the Additional administrative tasks section under Manage permissions "Add a team admin" is listed twice.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2142cf8c-de62-2cac-781c-27e2354797fb
* Version Independent ID: ce1d22c5-1182-03cd-6d51-c33dc490e04f
* Content: [About creating and managing organization - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/organization-management?view=azure-devops#feedback)
* Content Source: [docs/organizations/accounts/organization-management.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/accounts/organization-management.md)
* Product: **devops**
* Technology: **devops-accounts**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by WilliamAntonRohm** [comment]
@chcomley -- please review the above-mentioned PR 828.
