### ISSUE TITLE
Not allowing to create more than 100 templates?

### ISSUE THREAD

**Issue by sandippatil356097** [MicrosoftDocs/vsts-docs#6938]
Azure DevOps is not allowing to create more than 100 templates. Can this number be changed for specific project?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1debd814-eb48-c984-a4f9-7606093e9617
* Version Independent ID: f48ef796-c2e3-8fa3-6c41-326a5b252a3d
* Content: [Use work item templates to update stories, & more - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/backlogs/work-item-template?view=azure-devops&tabs=browser)
* Content Source: [docs/boards/backlogs/work-item-template.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/boards/backlogs/work-item-template.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@sandippatil356097 - Increasing the limit can have a potential performance impact and may need adjustments of some caches as well.  So increasing the limit isn't recommended. If you want to pursue this further, please file a [support ticket](https://support.microsoft.com/supportforbusiness/productselection?sapId=4d7c8158-200d-893b-5161-06d00803fd9c).
