### ISSUE TITLE
Error specifiying template that only defines a job

### ISSUE THREAD

**Issue by timothies** [MicrosoftDocs/vsts-docs#6939]
I tried to use the code snippet (copy/paste) defined for  # File: templates/jobs.yml  and got an error "Unexpected value 'jobs'"  When I add the stages and stage keyword it works (as below).     "Much like steps, jobs can be reused with templates." implies stages aren't necessary, am I missing something? 
Thanks for your help.

# File: templates/jobs.yml

stages:
- stage:
  jobs:
  - job: Build
    steps:
    - script: npm install

  - job: Test
    steps:
    - script: npm test

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6724abea-bbdc-bf66-ed5e-3214fa6c3e66
* Version Independent ID: 4f8dab21-3f0e-da32-cc0e-1d85c13c0065
* Content: [Templates - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/templates?view=azure-devops)
* Content Source: [docs/pipelines/process/templates.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/templates.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by msebolt** [comment]
@timothies Thank you for the feedback, we're sorry you're having issues with the code.

This example should be valid according to the [Jobs](https://docs.microsoft.com/azure/devops/pipelines/process/phases?view=azure-devops&tabs=yaml#multi-job-configuration) documentation, assigning this to the author for further review.

Please note if we are unable to reproduce this issue you will need to contact the product team [here](https://developercommunity.visualstudio.com/spaces/21/index.html) or try one of following support options:

- [Azure DevOps Support](https://azure.microsoft.com/support/devops/)
- [Azure DevOps on StackOverflow](https://stackoverflow.com/questions/tagged/azure-devops)

**Comment by dagardiner** [comment]
I'm experiencing a similar issue - throwing it into this thread in case the additional context is helpful.  I need to have a job (publishing) depend on the results of a template (build and add artifacts to the pipeline), so have them structured into a Stage as per the suggestion from [here](https://developercommunity.visualstudio.com/content/problem/642351/unable-to-define-dependson-with-stage-template.html).  I now have a structure similar to OP's, and am getting the same error of "Unexpected value 'jobs'".

`stages:
- stage: BuildAndPublish
  jobs:
  - job: buildStep
    pool:
      vmImage: 'windows-2019'
    steps:
    - template: build-extension.yml
      parameters:
        Name: 'blah'
...`

**Comment by juliakm** [comment]
@timothies Can you include your YAML so that we can see where you include the the jobs template?

**Comment by timothies** [comment]
Hi @juliakm , thanks for looking into this.  I've created an instance of the pipeline demonstrating the issue here: https://github.com/timothies/6939.    I get the error below

![image](https://user-images.githubusercontent.com/4046886/73409593-d863ff00-4353-11ea-89e4-ed548bf9e8b4.png)

**Comment by timothies** [comment]
Hey  @juliakm, do you have/know of an example of a working pipeline that calls on a templated job?

**Comment by Slooz** [comment]
@timothies, you're seeing an error because you're trying to start a job at the stage level. In `test-templates-pipeline.yml`, you specify `stages:` on [line 15](https://github.com/timothies/6939/blob/master/test-templates-pipeline.yml#L15). This means that the next items must be stages, not jobs. That's why `working-jobs.yml` works and why `broken-jobs.yml` doesn't work. In `working-jobs.yml`, you specify a stage that contains a job. This is what `stages:` in `test-templates-pipeline.yml` is expecting.

If you want a template that only specifies a job, you need to change [line 15](`test-templates-pipeline.yml`) in `test-templates-pipeline.yml` from `stages:` to `jobs:`.

Or, you have to do the following:
````yaml
stages:
  - template: templates/working-jobs.yml
  - stage:
    jobs:
      - template: templates/broken-jobs.yml

**Comment by timothies** [comment]
Ahh I understand - thanks @Slooz I feel like a goose but really appreciate your help.  Thank you very much!!
