### ISSUE TITLE
Delete Option Missing

### ISSUE THREAD

**Issue by Ixus** [MicrosoftDocs/vsts-docs#6940]
I have a rename option, but no delete option.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b03af1d9-4eeb-ac18-d517-a0a44a2478be
* Version Independent ID: 842691c8-8c41-facf-2cff-03542262f2e5
* Content: [Delete a Git repo from your project - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/delete-existing-repo?view=azure-devops#feedback)
* Content Source: [docs/repos/git/delete-existing-repo.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/repos/git/delete-existing-repo.md)
* Product: **devops**
* Technology: **devops-code-git**
* GitHub Login: @apawast
* Microsoft Alias: **sdanie**

**Comment by Ixus** [comment]
I have 3 projects/repos. I set it up online, but VS wants to create a new one. So I tried to delete it to no avail. I even tried to rename it,  but it appears projects are different than repos, even though it asks me to put in the repo name, not the project name in VS.

**Comment by msebolt** [comment]
@lxus  Thank you for the feedback, we're sorry you're having issues with the product.

Please make sure you have [delete permissions](https://docs.microsoft.com/azure/devops/organizations/security/set-git-tfvc-repository-permissions#git-repository) or try [deleting the project](https://docs.microsoft.com/azure/devops/organizations/projects/delete-project).
Unfortunately, our support options are limited to documentation examples only.

If this still doesn't work, see [this post](https://developercommunity.visualstudio.com/content/problem/476620/cant-delete-transfer-repository-in-azure-dev-ops.html) for known issues involving repo deletion and/or contact the product team [here](https://developercommunity.visualstudio.com/spaces/21/index.html) for further assistance.

@apawast

**Comment by Ixus** [comment]
I just had to delete the project. When VS said a repo had the same name, I was confused.
