### ISSUE TITLE
Enforce a filter on the dashboard list per group

### ISSUE THREAD

**Issue by Apholisha** [MicrosoftDocs/vsts-docs#6942]
How can I make sure that a group\team gets to see only the dashboards I want them to.. or just the dashboards they own.
Right now they see a full list of all available dashboards. I want to enforce a filter on it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dcb11d2d-86bd-ff52-d191-4da86d54b473
* Version Independent ID: 79438e17-b3d3-0331-5040-98107eb840a2
* Content: [Understand dashboards, charts, reports & widgets - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/report/dashboards/overview?view=azure-devops)
* Content Source: [docs/report/dashboards/overview.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/report/dashboards/overview.md)
* Product: **devops**
* Technology: **devops-analytics**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by msebolt** [comment]
@Apholisha Thank you for the question.

Currently anyone with access to the project can view dashboards, please see a similar issue recently posted [here](https://developercommunity.visualstudio.com/content/problem/502594/how-to-block-dash-board-view-permissions.html).

You can submit a request [here](https://developercommunity.visualstudio.com/spaces/21/index.html) if you'd like to have the product team revisit this feature.

**Comment by Apholisha** [comment]
thanks
