### ISSUE TITLE
Example in section Publish (UniversalPackages@0) is wrong

### ISSUE THREAD

**Issue by HofmeisterAn** [MicrosoftDocs/vsts-docs#6944]
The second source code example in section [Publish](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/package/universal-packages?view=azure-devops#publish) is wrong.

```yml
versionPublish: 'custom'
versionPublish: '1.2.3'
```

You use `versionPublish` twice. It should be `versionOption: 'custom'` I guess.

**Comment by msebolt** [comment]
@HofmeisterAn Thank you for the feedback.

The documentation has been updated and is pending review.

Please consider [becoming a contributor](https://docs.microsoft.com/contribute).

**Comment by HofmeisterAn** [comment]
Oh, I didn't know that I could contribute to the Microsoft documentation. Thanks for sharing.
