### ISSUE TITLE
Timeout for private projects with paid parallel jobs

### ISSUE THREAD

**Issue by svaenn** [MicrosoftDocs/vsts-docs#6946]
The Timeouts section of this page states that private projects always have a limit to run 60 minutes, this is not the case when the pipeline is paid: https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops#capabilities-and-limitations

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 67504b34-d64b-02a4-2e10-ab99f3b8cfe4
* Version Independent ID: 2cf63b2e-184b-7726-3b8a-d8baffd6fcce
* Content: [Jobs in Azure Pipelines and TFS - Azure Pipelines](https://docs.microsoft.com/de-de/azure/devops/pipelines/process/phases?view=azure-devops&tabs=yaml#timeouts)
* Content Source: [docs/pipelines/process/phases.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/phases.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by msebolt** [comment]
@svaenn Thank you for the feedback.

The documentation has been updated and is pending review.

Please consider [becoming a contributor](https://docs.microsoft.com/contribute).
