### ISSUE TITLE
'Import Work Items' not available

### ISSUE THREAD

**Issue by jdzik1001** [MicrosoftDocs/vsts-docs#6949]
I'm unable to see 'Import Work Items' in Azure Devops. Is this a feature that needs to be turned on for certain users?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4296d1cc-f211-9d17-d97f-2b0858fdea7d
* Version Independent ID: cc66dfee-adde-cdfb-b3f5-5d58d89d3c81
* Content: [Import or update work items from a CSV file - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/queries/import-work-items-from-csv?view=azure-devops#feedback)
* Content Source: [docs/boards/queries/import-work-items-from-csv.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/boards/queries/import-work-items-from-csv.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by msebolt** [comment]
@jdzik1001 Thank you for the question, we're sorry you're experiencing issues.

Please make sure you're using **Azure DevOps services**, not **Azure DevOps server**, and [contact the product team](https://developercommunity.visualstudio.com/spaces/21/index.html) for further assistance.

As a work-around, please refer to [bulk add work items with Excel](https://docs.microsoft.com/azure/devops/boards/backlogs/office/bulk-add-modify-work-items-excel).

**Comment by WilliamAntonRohm** [comment]
I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
