### ISSUE TITLE
Two broken image references

### ISSUE THREAD

**Issue by brillyints** [MicrosoftDocs/vsts-docs#6950]
The two images (/project/wiki/media/wiki/open-wiki-vert-brn.png and /boards/media/icons/project-icon.png) in the "Open Wiki" section result in a 404.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8d4fe5c7-0ab6-a0e4-4a6e-f98d0355f49a
* Version Independent ID: ce022fef-054d-cdc2-43e9-a8ee3b8fb592
* Content: [Publish Markdown files from Git repository to wiki - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/project/wiki/publish-repo-to-wiki?view=azure-devops&tabs=browser#open-wiki)
* Content Source: [docs/project/wiki/publish-repo-to-wiki.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/project/wiki/publish-repo-to-wiki.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by WilliamAntonRohm** [comment]
@chcomley -- please let me know the destination image links & I will update this document.
