### ISSUE TITLE
Hub group without any hubs

### ISSUE THREAD

**Issue by hanschristian2710** [MicrosoftDocs/vsts-docs#6951]
I have been trying to add a hub group without any hubs beneath it, but it won't display at all. Is it possible to have a hub group that will only display a specified URL something similar to the OOB hub group "Artifacts"?

I also noticed that a hub group must at least have 2 hubs beneath it in order for it to display? Is this true? I specified 1 hubs and that will never display, but 2 will display.

Here is my manifest on the contribution property with 1 hub only (and never get displayed)

"contributions": [
    {
      "id": "OnePlan.Hub.Group",
      "type": "ms.vss-web.hub-group",
      "description": "OnePlan Extension Hub Group",
      "targets": [
        "ms.vss-web.project-hub-groups-collection"
      ],
      "properties": {
        "name": "OnePlan",
        "icon": "img/OnePlan_Blue_128.png",
        "order": 1
      }
    },
    {
      "id": "OnePlan.Hub.Portfolio",
      "type": "ms.vss-web.hub",
      "description": "OnePlan Portfolio view",
      "targets": [
        "OnePlan.OnePlan.OnePlan.Hub.Group"
      ],
      "properties": {
        "name": "Portfolio",
        "order": 1,
        "uri": "portfolio.html"
      }
    }
  ]

**Comment by WilliamAntonRohm** [comment]
@hanschristian2710 -- Hans, thanks for your feedback; we appreciate it. To make sure we have all the information needed to triage your issue, please let us know which topic you’re referencing.
