### ISSUE TITLE
Documentation for rollup of remaining work is incorrect.

### ISSUE THREAD

**Issue by kyurthich** [MicrosoftDocs/vsts-docs#6952]
![image](https://user-images.githubusercontent.com/3331097/72462349-e7b54b00-379e-11ea-8b51-54c0f5916b71.png)

From experience the remaining work column never handles rollups. Rollups are handled by the remaining work rollup column so that would make the screenshot above that is on the document page inaccurate. 

If you had 20 in the remaining work column for the PBI then it would actually add to the remaining work for tasks and roll that total value of 40 up to the feature.

See correct concept in my screenshot of our environment.

![image](https://user-images.githubusercontent.com/3331097/72462595-65795680-379f-11ea-91f1-bac9fd59482b.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f6ed3f5-b5a4-10a9-f823-8591da27096d
* Version Independent ID: 1e955842-c971-2e15-777f-bbb95096698a
* Content: [Support rollup of work and other fields - Azure DevOps & TFS](https://docs.microsoft.com/en-us/azure/devops/reference/xml/support-rollup-of-work-and-other-fields?view=azure-devops)
* Content Source: [docs/reference/xml/support-rollup-of-work-and-other-fields.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/reference/xml/support-rollup-of-work-and-other-fields.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@kyurthich - Thank you for your inquiry. The Azure DevOps Services new feature Rollup column on the backlog pages works as you indicate, summing all values assigned to the same field for all child items. However, the Remaining Work column on the sprint backlog page is restricted to summing only those values assigned to Tasks. If you add the Remaining Work field to a requirements work item type, such as the Product Backlog Item or User Story, that value won't be summed. This is the way the product is engineered. If you believe it should be different, or want the Rollup column support added to the Sprints backlog pages, then please file a feture request on our [Developer Community page](https://developercommunity.visualstudio.com/spaces/21/index.html). Thank you.
