### ISSUE TITLE
Missing instruction on installing TFX

### ISSUE THREAD

**Issue by Diom** [MicrosoftDocs/vsts-docs#6956]
This page asks the user to use a `tfx extension create` command but does not instruct the user to actually install that tool:  
`npm i -g tfx-cli`

I found the information on another how-to guide but was a bit of a speed bump in my quick start. Luckily it drove me to the comments where I saw I needed a newer NPM SDK as well.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 14955ee9-29f2-46fe-3a8d-a42666f53ffc
* Version Independent ID: 5d417cd0-a671-ee30-8fca-5f8b0addd328
* Content: [Develop a web extension for Azure DevOps Services - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/extend/get-started/node?view=azure-devops#feedback)
* Content Source: [docs/extend/get-started/node.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/extend/get-started/node.md)
* Product: **devops**
* Technology: **devops-ecosystem**
* GitHub Login: @apawast
* Microsoft Alias: **apawast**

**Comment by chcomley** [comment]
Hi @diom, Thanks for the feedback, although the step for installing the TFX tool is step #3 within the Prerequisites section. Thank you!
