### ISSUE TITLE
Copy-paste mishap

### ISSUE THREAD

**Issue by flmontpetit** [MicrosoftDocs/vsts-docs#6959]
All three examples use "Bake K8s manifests from Helm chart" as the displayName

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 49d0eccc-f436-7367-cb24-b6da66b3a049
* Version Independent ID: 9bc5ee0d-3f00-dc10-ad69-77effc928290
* Content: [Bake manifests - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/ecosystems/kubernetes/bake?view=azure-devops#feedback)
* Content Source: [docs/pipelines/ecosystems/kubernetes/bake.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/ecosystems/kubernetes/bake.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @shashankbarsin
* Microsoft Alias: **shasb**

**Comment by WilliamAntonRohm** [comment]
@shashankbarsin -- Shashank, please review the above-mentioned PR 857.
