### ISSUE TITLE
Directions for folks new to Microsoft

### ISSUE THREAD

**Issue by Sparkdust** [MicrosoftDocs/vsts-docs#6966]
As a person new to Microsoft, it was not obvious to me what Azure Artifacts was. Would be nice to have links to appropriate devops places.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cb7c2ab6-4ba1-51d5-96bb-38a9ab6b50c3
* Version Independent ID: 415de875-ba1b-476b-f08b-1a61dc7a2747
* Content: [Set up your client's npmrc - Azure Artifacts](https://docs.microsoft.com/en-us/azure/devops/artifacts/npm/npmrc?view=azure-devops&tabs=windows#feedback)
* Content Source: [docs/artifacts/npm/npmrc.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/artifacts/npm/npmrc.md)
* Product: **devops**
* Technology: **devops-artifacts**
* GitHub Login: @chasewilson
* Microsoft Alias: **phwilson**

**Comment by msebolt** [comment]
@Sparkdust Thank you for providing feedback to Microsoft!

Assigning this to the author for further review.

**Comment by ramiMSFT** [comment]
@Sparkdust Thank you for your feedback. The updated version of the article will go live soon.
