### ISSUE TITLE
Create reports step fails on ubuntu

### ISSUE THREAD

**Issue by devpro** [MicrosoftDocs/vsts-docs#6971]
I copied/pasted the yaml sample from "Collect code coverage metrics with Coverlet" paragraph but the step "Create reports" fails with the error "line 1: reportgenerator: command not found".
Solution: add "./" before reportgenerator, with it the sample is running with success ("script: './reportgenerator -reports:$(Agent.TempDirectory)/**/coverage.cobertura.xml")

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec716c61-248c-75c9-2bc7-262749cc7421
* Version Independent ID: 45f47edc-e800-2c42-416a-92cd93c9e892
* Content: [Build, test, and deploy .NET Core apps - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/ecosystems/dotnet-core?view=azure-devops#feedback)
* Content Source: [docs/pipelines/ecosystems/dotnet-core.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/ecosystems/dotnet-core.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by WilliamAntonRohm** [comment]
@devpro -- Bertrand, thank you for catching this.

@juliakm -- Julia, please review the above-mentioned PR 859.
