### ISSUE TITLE
Broken Billing 

### ISSUE THREAD

**Issue by tomcoutts** [MicrosoftDocs/vsts-docs#6972]
When changing the organisation name there is a small window in which the Billing appears to be broken. This seemed to resolve itself after about an hour but may be worth reflecting this short delay in the docs.

**Comment by WilliamAntonRohm** [comment]
@tomcoutts -- Tom, thanks for your feedback; we appreciate it. To make sure we have all the information needed to triage your issue, please let us know which topic you’re referencing, or provide more context around the general task.

**Comment by tomcoutts** [comment]
Hi @WilliamAntonRohm I will happily give more context. So on one of our Azure DevOps instances we needed to change the org name as documented here : https://docs.microsoft.com/fr-fr/azure/devops/organizations/accounts/rename-organization?view=azure-devops&viewFallbackFrom=vsts

For a good hour or more after doing so we were unable to access change our modify are billing settings. It then seemed to resolve itself. I was wondering if changing the org name has an specific implications on this and if so is it worth documenting,

**Comment by msebolt** [comment]
@tomcoutts Thank you for the feedback.

This is likely due to an internal process that may vary depending on the organization setup and will hopefully be improved by the product team on a continual basis.

Closing this now, though please comment below if there are any further issues.
