### ISSUE TITLE
Error while trying to get full JSON Object.

### ISSUE THREAD

**Issue by mapoitras** [MicrosoftDocs/vsts-docs#6977]
While doing 

steps:
- script: echo ${{ resources.repositories['self'].name }}

works well

doing:

steps:
- script: echo ${{ resources }}

Fails during evaluation of template yaml.

It would be useful to be able to get the full JSON object for the resources.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e2f7712f-f527-4326-21d5-34f1c300bdd7
* Version Independent ID: d3e588cc-8552-ddae-1f82-0856cc84f2d9
* Content: [Pipeline decorator context - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/extend/develop/pipeline-decorator-context?view=azure-devops#feedback)
* Content Source: [docs/extend/develop/pipeline-decorator-context.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/extend/develop/pipeline-decorator-context.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @vtbassmatt
* Microsoft Alias: **macoope**

**Comment by vtbassmatt** [comment]
This is a feature request, not a docs issue. Please file it on [Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html). Thanks!
