### ISSUE TITLE
Azure Artifacts no longer requires licenses to be assigned

### ISSUE THREAD

**Issue by johnterickson** [MicrosoftDocs/vsts-docs#6980]
"you must first assign licenses for the Azure Artifacts" can be removed

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 598465e1-85d4-4961-b8b6-902d6026c5e3
* Version Independent ID: 5ef1308a-3aeb-fcc4-dec7-6f10785612a3
* Content: [Release artifacts and artifact sources - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/artifacts?view=azure-devops#feedback)
* Content Source: [docs/pipelines/release/artifacts.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/release/artifacts.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by RoopeshNair** [comment]
[PR#834](https://github.com/MicrosoftDocs/azure-devops-docs-pr/pull/834)
