### ISSUE TITLE
Title "Why is the Git repository hidden?" is misleading

### ISSUE THREAD

**Issue by fargs** [MicrosoftDocs/vsts-docs#6982]
The title asks a question but the content does not answer it. Easy fix is to change the title but better fix would be to add content that does answer it. I was actually searching for an answer to that exact question.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 973bb49c-7fcb-a953-21ff-82b03f899e73
* Version Independent ID: 507b2d8b-9560-9afb-4628-ae562832c7ce
* Content: [Create a project wiki to share information - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/project/wiki/wiki-create-repo?view=azure-devops&tabs=browser&source=docs#feedback)
* Content Source: [docs/project/wiki/wiki-create-repo.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/project/wiki/wiki-create-repo.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
@fargs, Thanks for your feedback. I've fixed the title and am following up on just why the repo is hidden. Thank you.
