### ISSUE TITLE
AccountName should be OrgName or CollectionName

### ISSUE THREAD

**Issue by NenoLoje** [MicrosoftDocs/vsts-docs#6984]
On this page, it says:

&gt; However, you can navigate to it from the following URL:
&gt;
&gt; https://dev.azure.com/&lt;AccountName&gt;/&lt;TeamProjectName&gt;/_git/&lt;WikiName&gt;

For Azure DevOps Services **AccountName** should actually be **OrgName**.

For DevOps Server 2019, it should still be "DefaultCollection".

Thanks!
--Neno

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 973bb49c-7fcb-a953-21ff-82b03f899e73
* Version Independent ID: 507b2d8b-9560-9afb-4628-ae562832c7ce
* Content: [Create a project wiki to share information - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/project/wiki/wiki-create-repo?view=azure-devops&tabs=browser#feedback)
* Content Source: [docs/project/wiki/wiki-create-repo.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/project/wiki/wiki-create-repo.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by WilliamAntonRohm** [comment]
@chcomley -- please review the above-mentioned PR 862.
