### ISSUE TITLE
Adding a custom variable to the release name

### ISSUE THREAD

**Issue by bobbrow** [MicrosoftDocs/vsts-docs#6985]
The section "How do I manage the names for new releases?" says that you can use a "custom variable" in your release name, but this doesn't seem to be working for me.  Could you clarify in the docs whether this is supposed to work, or help me understand what I'm doing wrong?

I added a "Pipeline Variable" in "Variables" tab and then tried to reference it in the "Options" -&gt; "Release name format". When I created a new release, it showed up in the name as "$(Variable)" instead of substituting the value of that variable.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 63234ade-28cc-02fc-a319-42e3491da601
* Version Independent ID: 7ccbfe96-d61e-8bf2-de22-61150d648abd
* Content: [Release pipelines - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/index?view=azure-devops#feedback)
* Content Source: [docs/pipelines/release/index.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/release/index.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by RoopeshNair** [comment]
You can update the release name with custom variable value using the [logging commands](https://github.com/microsoft/azure-pipelines-tasks/blob/master/docs/authoring/commands.md#release-logging-commands)

**Comment by RoopeshNair** [comment]
Submitted [PR #833](https://github.com/MicrosoftDocs/azure-devops-docs-pr/pull/833) for the doc changes

**Comment by bobbrow** [comment]
I tried:
```
Write-Host "##vso[release.updatereleasename]$(date:yyyyMMdd)$(rev:.r) $(ReleaseVersion)-$(InsidersVersion)"
```
But PowerShell didn't know how to resolve the date variable.  Are `$date` and `$rev` available in this context?  I thought they should have been substituted already.

```
date:yyyyMMdd : The term 'date:yyyyMMdd' is not recognized as the name of a cmdlet, function, script file, or operable
2020-01-21T17:04:37.8113216Z program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
```

**Comment by RoopeshNair** [comment]
When you are modifying the release name in PowerShell, you need to use native powershell variables. The built-in variables are available only in default name update scenarios.

**Comment by bobbrow** [comment]
I figured it out.  $(Build.BuildNumber) actually has the information I need already.  Thanks.

**Comment by cawoodm** [comment]
It seems the original question (How do I reference custom pipeline variables) was not answered here. If I create a pipeline variable, which the user enters when they create a new release - how do I use this variable in the "Release name format". I created `ReleaseNo` but found no way of referencing it `Parts-$(ReleaseNo)` does not work and neither does `Parts-$(Release.ReleaseNo).

**Comment by DiSae** [comment]
This does not seem to cover 'custom' variables.
For example, a variable value is stored in a variable group. How do we add it to the 'release name format'?
In my case I'd like to have it this format: Data-Restore-$(sourceEnv)-to-$(targetEnv)-Release-$(rev:r)
sourceEnv and targetEnv are variables in a group.
