### ISSUE TITLE
Not supported for new work item form?

### ISSUE THREAD

**Issue by tessajade** [MicrosoftDocs/vsts-docs#7001]
I am using on-premises Azure DevOps Server with the XML process model. I tried to add the release deployment control and got the following error: "Cannot create work item control of type "DeploymentsControl". Legacy extensions are no longer supported in new work item form." If this is only supported for the old work item form, that be much clearer given that most people should be using the new work item form by now?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3cdffff7-f341-d9af-a26e-ebf755b3769a
* Version Independent ID: 7aea2747-67f8-4256-722a-740cb3677aca
* Content: [Hosted XML process model - Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/organizations/settings/work/hosted-xml-process-model?view=azure-devops#feedback)
* Content Source: [docs/organizations/settings/work/hosted-xml-process-model.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/settings/work/hosted-xml-process-model.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@tessajade - Thank you for your inquiry. The release deployments control on the work item form is only supported for Azure DevOps Services (cloud). It isn't available on-premises as yet. The note directs users using the Hosted XML process model as those users work in the cloud.
