### ISSUE TITLE
Roadmap for future supported formats?

### ISSUE THREAD

**Issue by SirAlvarex** [MicrosoftDocs/vsts-docs#7013]
I see you have a comment on future formats will be supported in future milestones.  Our engineers have a desire to use this tooling but for the Cobertura format.  Is there a timeline for support of these formats, or is there a AzDO Task we can execute to convert Cobertura to .coverage?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aaa4f4c6-0a42-108e-79dd-5724e1049bd5
* Version Independent ID: f4a857d1-78bc-170b-b138-fcf490c85b38
* Content: [Code coverage for pull requests - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/test/codecoverage-for-pullrequests?view=azure-devops#help-and-support)
* Content Source: [docs/pipelines/test/codecoverage-for-pullrequests.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/test/codecoverage-for-pullrequests.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @PBoraMSFT
* Microsoft Alias: **pbora**

**Comment by msebolt** [comment]
@SirAlvarex Thank you for the question.

Please refer to the [Publish Code Coverage Results](https://docs.microsoft.com/azure/devops/pipelines/tasks/test/publish-code-coverage-results) task.

Any questions regarding upcoming features, not addressed in the [features timeline](https://docs.microsoft.com/azure/devops/release-notes/features-timeline), should be directed to the product team by starting a ticket [here](https://developercommunity.visualstudio.com/spaces/21/index.html).

**Comment by msebolt** [comment]
Closing this now, thank you for contacting Microsoft.
