### ISSUE TITLE
What Do We Do With YAML File?

### ISSUE THREAD

**Issue by clockwiseq** [MicrosoftDocs/vsts-docs#7014]
I can't find anything on this page (forgive me if I overlooked it) regarding what to do with the YAML file.  I already have release pipelines setup (classic I guess) and I want to use Environments and the Environment page led me here because it seems the only way to target an environment is via YAML?  Well, once I build a YAML file, what do I do with it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7458d5b2-1bb7-7d87-7ce6-2b0c430b0155
* Version Independent ID: edf5bbd3-a3f0-5426-e985-31290f8afd05
* Content: [YAML schema - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema#feedback)
* Content Source: [docs/pipelines/yaml-schema.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/yaml-schema.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by msebolt** [comment]
@clockwiseq Thank you for the question.

You can place the YAML file anywhere in the [repo](https://docs.microsoft.com/azure/devops/pipelines/repos), though keep the mind the default name is set to *azure-pipelines.yml* located in the root. 

Please refer to the pipeline settings to use a different name and/or location for this file:

![Capture](https://user-images.githubusercontent.com/6675884/72916157-60179100-3cf6-11ea-87de-0bdd1c18582f.PNG)

For further information, please refer to [Use Azure Pipelines](https://docs.microsoft.com/azure/devops/pipelines/get-started/pipelines-get-started).

**Comment by clockwiseq** [comment]
Perfect!  Exactly what I needed to know.
