### ISSUE TITLE
Pipeline Resource version string should be able to accept a variable

### ISSUE THREAD

**Issue by kbrady-vibrato** [MicrosoftDocs/vsts-docs#7017]
Hi,

The Pipeline Resource currently does not accept a variable value for the version key.
It would be a better experience if I could potentially have a variable specified at run time that would be used so I did not have to edit the yaml each time.

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7458d5b2-1bb7-7d87-7ce6-2b0c430b0155
* Version Independent ID: edf5bbd3-a3f0-5426-e985-31290f8afd05
* Content: [YAML schema - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema#resources)
* Content Source: [docs/pipelines/yaml-schema.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/yaml-schema.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by msebolt** [comment]
@kbrady-vibrato Thank you for the feedback.

Please see if [this post](https://developercommunity.visualstudio.com/idea/845445/pipeline-resource-version-property-as-a-variable-1.html) addresses the issue where you can comment and/or vote accordingly.

If not, please start a thread [here](https://developercommunity.visualstudio.com/content/idea/post.html?space=21) and start a thread with the product team.

**Comment by kbrady-vibrato** [comment]
hi @msebolt - yep that post covers exactly my use case.
is there any plan to implement the acceptance of variables in a pipeline resource? if so, is there a timeline on it?

**Comment by msebolt** [comment]
Hi @kbrady-vibrato  

Any plans on implementation needs to be directed to the product team.

For current features in the pipeline, please refer to the [Azure DevOps features timeline](https://docs.microsoft.com/azure/devops/release-notes/features-timeline).

**Comment by msebolt** [comment]
Closing this issue now.
