### ISSUE TITLE
Check out permisson renamed

### ISSUE THREAD

**Issue by Hgker01** [MicrosoftDocs/vsts-docs#702]
I couldn't find TFVC permission "Check out" in TFS 2018 Update 1. It's become clear to me, that it's renamed to "Pend a change in a server workspace".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cc2adbee-5e62-a34a-5914-31bd417df13b
* Version Independent ID: 0f97e954-e8ef-b4b6-7182-24f9a9e3d92e
* Content: [Permissions and groups reference - VSTS & TFS](https://docs.microsoft.com/en-us/vsts/security/permissions?view=vsts)
* Content Source: [docs/security/permissions.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/security/permissions.md)
* Service: **unspecified**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by steved0x** [comment]
@Hgker01 Apologies for the great delay, and thank you for letting us know. This permission was renamed starting with TFS 2017, and I have updated the documentation, and it should be live soon. Thank you.

**Comment by Hgker01** [comment]
Thank You, Steve!

Best regards,
Gábor Horváth

Steve Danielson <notifications@github.com> ezt írta (időpont: 2019. jún.
26., Sze, 0:25):
