### ISSUE TITLE
Documentation unclear for --runAsAutoLogon

### ISSUE THREAD

**Issue by olandese** [MicrosoftDocs/vsts-docs#7022]
Can you please explain what the --runAsAutoLogon does? and what is the difference with --runAsService ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43799c5d-2f13-cc76-a1c0-a3f850e16d4e
* Version Independent ID: 97a5b73f-faf7-f9c0-9269-fc79984616d6
* Content: [Deploy a Azure Pipelines agent on Windows - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/v2-windows?view=azure-devops#unattended-config)
* Content Source: [docs/pipelines/agents/v2-windows.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/agents/v2-windows.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by msebolt** [comment]
@olandese Thank you for the question.

The difference is whether you want to run the agent as a service or an interactive process.

Please refer to [interactive vs. service](https://docs.microsoft.com/azure/devops/pipelines/agents/agents#interactive-or-service) for more information.

@steved0x

**Comment by msebolt** [comment]
Closing this issue now, thank you for contacting Microsoft.
