### ISSUE TITLE
Provide information on how to escape Azure variable references

### ISSUE THREAD

**Issue by mklement0** [MicrosoftDocs/vsts-docs#7023]
Information is missing on how to pass tokens that _look_ like Azure variable references through to the target command by _escaping_ properly - assuming there is support for that.

For instance, syntax `$(...)` is also used by PowerShell itself, as the [subexpression operator](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_Operators#subexpression-operator--), typically used inside expandable strings (`"..."`).

So, if I wanted to pass the following command through to PowerShell, how would I escape the `$(...)` so that they're _not_ interpreted as an Azure macro?

```powershell
Write-Output "1 + 1 equals $(1 + 1)"
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd7e0bd3-1f7d-d7b6-cc72-5ef63c31b46a
* Version Independent ID: dae87abd-b73d-9120-bcdb-6097d4b40f2a
* Content: [Variables - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch)
* Content Source: [docs/pipelines/process/variables.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/variables.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by msebolt** [comment]
@mklement0 Thank you for the feedback.

Assigning this to the author for further review.

**Comment by juliakm** [comment]
@mklement0 You can use single quotes to escape the variable. I'll update the docs. 

`Write-Output "1 + 1 equals $(1 + 1)" # Prints 1 + 1 equals 2`
`Write-Output '1 + 1 equals $(1 + 1)' # Prints 1 + 1 equals $(1 + 1)`

**Comment by mklement0** [comment]
Thanks, @juliakm, I actually _do_ want Powershell to evaluate the `$(1+1)`, but the larger point is that I want to be able to prevent _Azure_ from interpreting and expanding the `$(1 + 1)` _up front_, before PowerShell ever sees it.

Or is that not what happens? I can't personally verify it, but my assumption was that since `$(1 + 1)` looks like an _Azure_ macro (e.g, `$(System.DefaultWorkingDirectory)`), it would attempt to expand it up front.

Or is that not the case, because what's _inside_ the `$(...)` in this case doesn't look like an Azure _variable name_?

However, note that even something like `$(hostname)`, which _does_ look like a variable name is a valid subexpression in PowerShell that one should be able to pass through to it (it executes the `hostname` utility and replaces `$(hostname)` with its output): `Write-Output "Hostname: $(hostname)"`

**Comment by vtbassmatt** [comment]
There is no escaping mechanism. We attempt to parse any `$()` as a reference to a variable. If that variable is undefined, we'll pass the string through unchanged. Your `$(1 + 1)` scenario will never be a problem, as "1 + 1" is never a valid variable name. `$(hostname)` would only be a problem if you also had a pipeline variable called `hostname`. We only parse these expressions in inline scripts, so another workaround (should the need arise) is to include the script in the repo instead of inline.

**Comment by mklement0** [comment]
Thanks for clarifying, @vtbassmatt.

I now see that the linked topic has a table that has a column "How does it render when not found?", which _implies_ what you're saying, but I feel it deserves a more explicit explanation:

* Users may come looking for an _escaping_ mechanism (as I did), which is the typical approach; mentioning that there is none explicitly would answer that question unambiguously.

* Explicitly assuring PowerShell users that their `$(...)` subexpressions will nonetheless be passed through intact (except in unlikely corner cases similar to `$(hostname)`) strikes me as important.

* Similarly, explicitly mentioning the fact that Azure's `$(...)` macro construct just happens to _look like_ PowerShell's can't hurt. That different layers are in charge of interpreting a `$(...)` construct, depending on the specifics of what's _inside_ (with at least _formal_ syntax overlap) is non-obvious.

**Comment by mklement0** [comment]
P.S.: That this syntax layering can cause confusion in practice is demonstrated in https://stackoverflow.com/q/59860674/45375; I've updated my answer there based on your feedback, but I'm hoping the information also makes it into the docs.
