### ISSUE TITLE
Update reference links for Mermaid

### ISSUE THREAD

**Issue by joshknutson** [MicrosoftDocs/vsts-docs#7024]
Flowcharts -&gt;https://mermaid-js.github.io/mermaid/#/flowchart
Sequence diagrams - &gt; https://mermaid-js.github.io/mermaid/#/sequenceDiagram
Gantt Charts - &gt; https://mermaid-js.github.io/mermaid/#/gantt

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 29f1e43f-a069-dd88-7fc7-9cc497fb94f0
* Version Independent ID: c261afa7-6eb7-b3f0-9f92-6d2f3c5ac336
* Content: [Markdown syntax for wikis in Azure DevOps - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/project/wiki/wiki-markdown-guidance?view=azure-devops#feedback)
* Content Source: [docs/project/wiki/wiki-markdown-guidance.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/project/wiki/wiki-markdown-guidance.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by msebolt** [comment]
@joshknutson Thank you for the feedback.

The documentation has been updated and is pending review.

Please consider [becoming a contributor](https://docs.microsoft.com/contribute).
