### ISSUE TITLE
Can't make wiki section private?

### ISSUE THREAD

**Issue by scosm** [MicrosoftDocs/vsts-docs#7028]
I want to make our dev wiki private to our team. But our wiki has to be part of the larger org's wiki, which is basically the whole division (CSEO). I can't set permissions on a per-page basis, ok. But I also can't make a whole section or group to have their own internal wiki. So, this is bad. I have a customer-facing wiki in DevOps, but our dev wiki is in OneNote (which is horribly). Please, is there a way you could allow permissions settings on a finer level of granularity??

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c86f5178-e331-f45e-b60a-f0f3955f7a08
* Version Independent ID: 8a0882a7-8f48-32bb-c741-12976b428c38
* Content: [Manage permissions for READMEs and wiki pages - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/project/wiki/manage-readme-wiki-permissions?view=azure-devops)
* Content Source: [docs/project/wiki/manage-readme-wiki-permissions.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/project/wiki/manage-readme-wiki-permissions.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by WilliamAntonRohm** [comment]
Thanks for the suggestion! The product teams aren’t always watching this repository, so to make sure it gets in front of them for triage, please [submit your idea]( https://developercommunity.visualstudio.com/content/idea/post.html?space=21) here. 

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
