### ISSUE TITLE
Is there any way to upload secure files programmatically?

### ISSUE THREAD

**Issue by alexkokkinos** [MicrosoftDocs/vsts-docs#703]
I'm trying to find out a way to do this, either via the VSTS REST API, Node API, Tasks Library, etc. I don't think it's possible at the moment.

**Comment by madhurig** [comment]
Here is a sample of how to upload a secure file using the vsts-node-api: https://github.com/Microsoft/vsts-node-api/blob/3c0c85e653f6449838249f1d8a970bd6bbf08930/samples/task.ts#L43 

Thanks,
Madhuri

**Comment by alexkokkinos** [comment]
It looks like I missed that,  I didn’t know where it lived.  Thanks for your help!
