### ISSUE TITLE
Clarification on using project scoped feeds 

### ISSUE THREAD

**Issue by ma-kern** [MicrosoftDocs/vsts-docs#7030]
Since all new feeds in Azure DevOps are now scoped to a project it might be helpful to note that you cannot just use feedName for new feeds, but instead have to use &lt;projectName&gt;/&lt;feedName&gt;.  Using just the feedName will result in a FeedNotFoundException when the pipeline is run. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d4cb48a1-d0bf-40b7-4645-910d4006fee9
* Version Independent ID: 9bddd101-2bc2-f65c-6a12-e395b76a2b98
* Content: [Publishing npm packages - Azure Pipelines and TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/npm?toc=%2Fazure%2Fdevops%2Fartifacts%2Ftoc.json&bc=%2Fazure%2Fdevops%2Fartifacts%2Fbreadcrumb%2Ftoc.json&view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/artifacts/npm.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/artifacts/npm.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @chasewilson
* Microsoft Alias: **phwilson**

**Comment by ramiMSFT** [comment]
@ma-kern Thank you for your feedback. The new version will go live shortly.
