### ISSUE TITLE
May stakeholder add workitems?

### ISSUE THREAD

**Issue by A-AontwSR** [MicrosoftDocs/vsts-docs#7037]
On this page, second line, is documented that
"With Stakeholder access, you can add and modify work items, ". And there is a paragraph about add-work-items-to-a-product-backlog

But in the table on, the linked, page https://docs.microsoft.com/en-us/azure/devops/organizations/security/access-levels?view=azure-devops-2019#supported-access-levels is documented:
"Agile boards
Includes limited access to Kanban boards. On Boards, Stakeholders can't add work items, can't drag-and-drop work items to update status, and can't update fields displayed on cards.".

My question is: **can** Stakeholders add work items or **can't** they add work items?
Thus which page is correct?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17e7fef2-40df-4923-e62e-74ac556cbc6a
* Version Independent ID: af9269b4-1db4-df1f-2520-78ad20baf17b
* Content: [Get started with Stakeholder access - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/security/get-started-stakeholder?view=azure-devops-2019&tabs=scrum-process)
* Content Source: [docs/organizations/security/get-started-stakeholder.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/security/get-started-stakeholder.md)
* Product: **devops**
* Technology: **devops-new-user**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
A-AontwSR - Thank you for your inquiry. Stakeholders can add work items to Backlogs and Sprint Backlogs. THey can't add work items to Kanban boards or tasks to Taskboards.

**Comment by A-AontwSR** [comment]
Thanks for the (short) answer.
Is it possible to make this clear from the page itself?

The page contains confusing texts, like:
top of page, third bullet (checkmark): Open the Kanban board and add a work item,
last section "Features not available to users with Stakeholder access" does not mention it
