### ISSUE TITLE
"Path filters": why don't just take the default path filters in the YAML pipeline??

### ISSUE THREAD

**Issue by obeyda** [MicrosoftDocs/vsts-docs#7038]
like this we have to rewrite/update the same filters twice, once for the pipeline and another time for the build policy, why don't just use the path filters in the pipeline?? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7cd986e0-608c-1d8c-6faf-ecdb12e10bc6
* Version Independent ID: d60c996e-187e-dd6b-7f3a-dd056a1603f4
* Content: [Protect your Git branches with policies - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/branch-policies?view=azure-devops#feedback)
* Content Source: [docs/repos/git/branch-policies.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/repos/git/branch-policies.md)
* Product: **devops**
* Technology: **devops-code-git**
* GitHub Login: @apawast
* Microsoft Alias: **sdanie**

**Comment by WilliamAntonRohm** [comment]
@obeyda -- Obeyda, thanks for the suggestion! The product teams aren’t always watching this repository, so to make sure it gets in front of them for triage, please [submit your idea]( https://developercommunity.visualstudio.com/content/idea/post.html?space=21) here. 

@apawast -- Apeksha, please look into this potential documentation issue.

**Comment by obeyda** [comment]
thanks @WilliamAntonRohm , there is indeed an idea about that in the dev community: https://developercommunity.visualstudio.com/idea/441897/build-validation-branch-policies-should-use-path-f.html
i'll follow that idea, so feel free to close this issue.

**Comment by apawast** [comment]
@obeyda As this is a product suggestion that you have found the developer community suggestion for, I am closing the issue. Thank you for your suggestion!
