### ISSUE TITLE
What input files will it use to build the docker image?

### ISSUE THREAD

**Issue by katlimruiz** [MicrosoftDocs/vsts-docs#7043]
Build.SourcesDirectory?
Agent.BuildDirectory?
Build.ArtifactStagingDirectory? &lt;&lt;&lt; this probably should be it.

however is not explicit anywhere here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d9dbf88-7e55-d427-145e-d36b04fb197f
* Version Independent ID: a3f30c00-817c-9c05-7a57-3f2bf618821e
* Content: [Docker task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/docker?view=azure-devops#build-and-push)
* Content Source: [docs/pipelines/tasks/build/docker.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/build/docker.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @shashankbarsin
* Microsoft Alias: **shasb**

**Comment by valentinburk** [comment]
By default, the context is a folder that contains your `Dockerfile` or you can specify it explicitly by setting `buildContext` parameter

```yaml
steps:
- task: Docker@2
  displayName: 'Build'
  inputs:
    command: build
    buildContext: path/to/context
```

**Comment by msebolt** [comment]
@katlimruiz Thank you for the question.

Both use of [Predefined variables](https://docs.microsoft.com/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml) or the `buildContext` as @valentinburk states should be feasible.

Please comment if there are any issues with this setup.

**Comment by msebolt** [comment]
Closing this issue now.  Please comment if there are any questions.

**Comment by arjunDhanAi** [comment]
Hi I have a COPY command in my docker file. 
My docker file is not on the root of the artifact staging directory nor the code which i want to copy is present there, its inside the Artifact staging directory.
My task in the devops pipeline is as follows
    - task: Docker@2
      inputs:
        buildContext: '$(Build.ArtifactStagingDirectory)/DIR1/dir2/PATH/TO/ACTUAL/CODE'
        containerRegistry: 'dicaChatImages'
        repository: $(imageRepository)
        command: 'buildAndPush'
        Dockerfile: '$(Build.ArtifactStagingDirectory)/DIR1/dir2/PATH/TO/ACTUAL/CODE/docker/docker_file'
        tags: |
          $(tag)

While running the COPY command the docker fails saying it does not have the path "DIR1/dir2/PATH/TO/ACTUAL/CODE"
