### ISSUE TITLE
Package Management as artifact source

### ISSUE THREAD

**Issue by ggirard07** [MicrosoftDocs/vsts-docs#705]
Looks like Package Management is now supported as an additional artifact source.
Can you add some details about it? Some example about details i was looking for:
- What package types are supported?
- How those artifacts are retrieved by the build agent?
  - Is the package extracted on disk?
  - For Powershell based packages, are they installed on the phase agents?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 598465e1-85d4-4961-b8b6-902d6026c5e3
* Version Independent ID: 5ef1308a-3aeb-fcc4-dec7-6f10785612a3
* Content: [Artifacts in Release Management](https://docs.microsoft.com/en-us/vsts/build-release/concepts/definitions/release/artifacts?view=vsts#sources)
* Content Source: [docs/build-release/concepts/definitions/release/artifacts.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/build-release/concepts/definitions/release/artifacts.md)
* Service: **unspecified**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment]
Thank you for your feedback. I will consult with the product team and add the required details.
