### ISSUE TITLE
AzureDevOps Client Library doesn't work

### ISSUE THREAD

**Issue by mswilson4040** [MicrosoftDocs/vsts-docs#7050]
I am trying to use AzureDevOps Client NET Libraries to get a release, but it doesn't look like it will work with azure functions:

```
public override void Configure(IFunctionsHostBuilder builder)
{
   builder.Services.AddTransient(x =>
   {
        var url = "<project url>";
        var pat = "<PAT>";
        var credentials = new VssBasicCredential(string.Empty, pat);
        return new VssConnection(new Uri(url), credentials); <-- Method Not Found...
    });
}
```

Results in:

> Microsoft.VisualStudio.Services.WebApi: Method not found: 'Newtonsoft.Json.JsonSerializerSettings System.Net.Http.Formatting.BaseJsonMediaTypeFormatter.get_SerializerSettings()'.

I am using dotnet core 3.1. I have also tried without using DI and I get the same result. The closest thread I could find was this but the [fix doesn't work](https://developercommunity.visualstudio.com/content/problem/878381/problem-with-microsoftvisualstudioservicesclient-n.html)

I also skimmed through [this article](https://mitchdenny.com/vsts-libraries-from-dotnet-core/), but the solution is geared towards windows. I'm on a mac

It suggests:
```
<PropertyGroup>
    <PackageTargetFallback>portable-net451+win8</PackageTargetFallback>
</PropertyGroup>
```

https://docs.microsoft.com/en-us/azure/devops/integrate/concepts/dotnet-client-libraries?view=azure-devops

Here is my full csproj file:

```
<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>netcoreapp3.1</TargetFramework>
        <AzureFunctionsVersion>v3</AzureFunctionsVersion>
        <RootNamespace>My.Project</RootNamespace>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="Microsoft.Azure.Functions.Extensions" Version="1.0.0" />
        <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="3.0.2" />
        <PackageReference Include="Microsoft.TeamFoundationServer.Client" Version="16.153.0" />
        <PackageReference Include="Microsoft.VisualStudio.Services.Client" Version="16.153.0" />
        <PackageReference Include="Microsoft.VisualStudio.Services.Release.Client" Version="16.153.0" />
    </ItemGroup>
    <ItemGroup>
        <None Update="host.json">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Update="local.settings.json">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
            <CopyToPublishDirectory>Never</CopyToPublishDirectory>
        </None>
    </ItemGroup>
</Project>
```

Here is a repo the reproduces the issue
https://github.com/mswilson4040/vssconnection-repro

**Comment by msebolt** [comment]
@mswilson4040 Thank you for the feedback, we're sorry you're having issues with code.

Have you updated your references to latest `Newtonsoft.Json` library?  This issue was reported in previous versions, see [this post](https://stackoverflow.com/questions/43175098/method-not-found-basejsonmediatypeformatter-get-serializersettings-when-using).

Please note our support options are limited to documentation samples only.

If you think there is an issue with the product itself, please start a ticket [here](https://developercommunity.visualstudio.com/content/problem/post.html?space=21) for feedback from the product team.

Otherwise, for additional support options, refer to:

- [Azure DevOps Support](https://azure.microsoft.com/support/devops/)
- [Azure DevOps on StackOverflow](https://stackoverflow.com/questions/tagged/azure-devops)

Including @chcomley for visibility.

**Comment by mswilson4040** [comment]
@msebolt I do not have any reference to the `Newtonsoft` library in my project. It's being referenced by the Azure DevOps client libraries. Can you point me to the repo that owns these libraries? I've tried SOF, and have seen a few other posts about this but I don't have a resolution yet. Going to the documentation for the client libraries, it takes you here. I realize this is for documentation, but I figured it was a good place to start/figure out where I can go to get an answer.

**Comment by msebolt** [comment]
@mswilson4040  Apologies for the delay.

Please see [Install and manage NuGet packages in Visual Studio for Mac](https://docs.microsoft.com/visualstudio/mac/nuget-walkthrough) and refer to the [Newtonsoft.Json](https://www.nuget.org/packages/Newtonsoft.Json/) package for specifics.

**Comment by mswilson4040** [comment]
@msebolt I'm not using visual studio for mac. I am using JetBrains Rider. I have installed all the required dependencies. I have also tried installing Newtonsoft.json and it doesn't fix anything.

**Comment by msebolt** [comment]
@mswilson4040 Thank you for the update.

This issue has been addressed with https://github.com/Azure/Azure-Functions/issues/1465, please refer there for future reference.

**Comment by msebolt** [comment]
Closing this issue now.
