### ISSUE TITLE
No Remove button on the state "Completed"

### ISSUE THREAD

**Issue by bjornhelle** [MicrosoftDocs/vsts-docs#7051]
Hi,

There are no Remove button on the state Completed. I was able to add a new custom state to this level, but not able to remove it. This is not described in your documentation.

![NoRemoveButton](https://user-images.githubusercontent.com/46591276/73044440-34361000-3e9c-11ea-8d72-736799c5baa0.png)

This creates an error on the boards.
![ErrorOnBoard](https://user-images.githubusercontent.com/46591276/73044725-6eec7800-3e9d-11ea-9ceb-413cb4de03b1.png)

https://docs.microsoft.com/en-us/azure/devops/organizations/settings/work/customize-process-workflow?view=azure-devops

**Comment by msebolt** [comment]
@bjornhelle Thank you for the feedback.

Assigning this to the author for review.

**Comment by KathrynEE** [comment]
@bjornhelle - Thank you for the feedback. I've added a backlog item to update the article to clarify operations.
