### ISSUE TITLE
Access variables through the environment - doesn't work if variable has a hyphen in the name

### ISSUE THREAD

**Issue by marcin-vt** [MicrosoftDocs/vsts-docs#7054]
When creating variable in the bash script
`echo "##vso[task.setvariable variable=${VAR};]${VAL}"`
If the name contains "-" the environmental variable will be created and available for all other stages, but it will be empty.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd7e0bd3-1f7d-d7b6-cc72-5ef63c31b46a
* Version Independent ID: dae87abd-b73d-9120-bcdb-6097d4b40f2a
* Content: [Variables - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch)
* Content Source: [docs/pipelines/process/variables.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/variables.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by msebolt** [comment]
@marcin-vt Thank you for the feedback.

Please see the similar issue in [this post](https://developercommunity.visualstudio.com/content/problem/580367/bug-in-vs-2019-with-docker-compose-when-an-environ.html), due to dashes not being allowed in the POSIX standard.

If there are further questions please comment below.

**Comment by marcin-vt** [comment]
Thnx for answer @msebolt. Just tought that since all dots and spaces in the names are already replaced with underscore, maybe also hyphen should be ([based on this](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/variables?view=azure-devops&tabs=batch#set-in-script)).
> Variable names are transformed to uppercase, and the characters "." and " " are replaced by "_".

**Comment by msebolt** [comment]
Closing this issue now.
