### ISSUE TITLE
Add link or text for how to move work items associated with test management between projects

### ISSUE THREAD

**Issue by Sonesson** [MicrosoftDocs/vsts-docs#7055]
Please add text below "Move a work item to another project" showing how it is possible if you use the Microsoft Test Manager. Deprecated after VS2017, but still available.
There is a good guide at: http://ericphan.net/blog/2018/1/3/migrating-test-cases-from-one-vsts-project-to-another.
(Alternatively fix the "Move to team project" command in the gui)
 

---
#### Dokumentinformation

⚠ *Redigera inte det här avsnittet. Det krävs för docs.microsoft.com ➟ länkning till GitHub-problem.*

* ID: 0e9f02cb-f094-d6bc-ca7b-973db9de0082
* Version Independent ID: 1af6a7f5-9e99-ec99-081d-c0bf9e7ac5f5
* Content: [Move, change, and delete work items - Azure Boards](https://docs.microsoft.com/sv-se/azure/devops/boards/backlogs/remove-delete-work-items?tabs=browser&view=azure-devops#move-a-work-item-to-another-project)
* Content Source: [docs/boards/backlogs/remove-delete-work-items.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/boards/backlogs/remove-delete-work-items.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by msebolt** [comment]
@Sonesson Thank you for the feedback.

Assigning this to the author for further review.

**Comment by KathrynEE** [comment]
@Sonesson - Thank you for the feedback. I've added a backlog item to update the article to clarify operations.
