### ISSUE TITLE
Templates from Artifact Feed or pipeline artifact possible?

### ISSUE THREAD

**Issue by Andy-bridle** [MicrosoftDocs/vsts-docs#7056]
Is it going to be possible to define an Artifact Feed or an upstream pipeline artefact as the source for a template file?

I'm distributing shared packages across multiple organisations through an Artifact feed, I want to include the reusable deployment steps in the versioned artifacts alongside the code in template-steps.yml files. 

Currently I will need to create a Git repo to accompany the Artifact Feed and do some work to keep the two in sync.

**Comment by msebolt** [comment]
@Andy-bridle Thank you for the question.

Please note this is the documentation forum and our support options are limited to topic examples only.

Either reference an example in a related article, or for product-related issues you can solicit feedback from the product team [here](https://developercommunity.visualstudio.com/content/problem/post.html?space=21).

For additional support options, please see:

- [Azure DevOps Support](https://azure.microsoft.com/support/devops/)
- [Azure DevOps on StackOverflow](https://stackoverflow.com/questions/tagged/azure-devops)

**Comment by msebolt** [comment]
Closing this issue now.
