### ISSUE TITLE
How to have scope in Variable groups?

### ISSUE THREAD

**Issue by hmendezm** [MicrosoftDocs/vsts-docs#7059]
Hi everybody

I have DEV, UAT, STAGE, PRODUCTION Stages in my release pipeline. I am using replace tokens tasks to replace values in a file. I  set variables with scope for each one of the stages. for instance, 
Variable name      Value        Scope
name                     'UAT'        UAT
name                     'STAGE'        STAGE
name                     'PRODUCTION'        PRODUCTION

This work but when I try to move these variables to Variable groups, I cannot find the scope column. is a way to set scope in variables groups? 

Best
H. Mendez

**Comment by msebolt** [comment]
@hmendezm Thank you for the question.

This feature is currently in discussion in the **Azure DevOps community**.

Please direct questions and/or comments to [this thread](https://developercommunity.visualstudio.com/idea/365749/scoping-for-variable-groups.html) for further feedback from the product team.

**Comment by hmendezm** [comment]
Thanks @msebolt

**Comment by msebolt** [comment]
Closing this issue now.
