### ISSUE TITLE
Doesn't work in Dockerfile

### ISSUE THREAD

**Issue by Farzad-Jalali** [MicrosoftDocs/vsts-docs#7060]
Hi 
I can get it work on my laptop and install my packages.
But now I started to containerizing my apps ,Now te pip install doesn't work 

FYI: everyone in my organization can download any package in our feed

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6cca7b9-7fe5-bc14-c7da-08983e920f81
* Version Independent ID: 7d8cf191-b229-0e2e-8cb3-01a80c4842fd
* Content: [Get started with Python packages - Azure Artifacts](https://docs.microsoft.com/en-us/azure/devops/artifacts/quickstarts/python-packages?view=azure-devops)
* Content Source: [docs/artifacts/quickstarts/python-packages.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/artifacts/quickstarts/python-packages.md)
* Product: **devops**
* Technology: **devops-artifacts**
* GitHub Login: @chasewilson
* Microsoft Alias: **phwilson**

**Comment by msebolt** [comment]
@Farzad-Jalali Thank you for the question.

Please see if [this post](https://developercommunity.visualstudio.com/content/problem/683856/pip-install-inside-dockerfile-using-private-artifa.html) addresses the issue and for further assistance start a thread with product team [here](https://developercommunity.visualstudio.com/spaces/21/index.html).

For additional support options, please refer to:

- [Azure DevOps Support](https://azure.microsoft.com/support/devops/)
- [Azure DevOps on StackOverflow](https://stackoverflow.com/questions/tagged/azure-devops)

**Comment by msebolt** [comment]
Closing this issue now.
