### ISSUE TITLE
Verify that removing members screenshot is correct

### ISSUE THREAD

**Issue by bucmic** [MicrosoftDocs/vsts-docs#7063]
Screenshot shows how to remove the Security Service Group but text says "highlight the user name".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 07738454-4b1a-eff5-6c16-69e963ab2663
* Version Independent ID: a63f1dad-0378-5ce3-97e9-ec66afffb206
* Content: [Add users to a team or project - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/security/add-users-team-project?view=azure-devops&tabs=preview-page#feedback)
* Content Source: [docs/organizations/security/add-users-team-project.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/security/add-users-team-project.md)
* Product: **devops**
* Technology: **devops-security**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by msebolt** [comment]
@bucmic  Thank you for the feedback.

If you add some details on what is wrong with the step we can assign an author to fix the documentation.

The text states `...highlight the user name and choose Remove` and the screenshot shows a user being highlighted with the **Remove** link visible.

How does the text and screenshot contradict each other or are both inaccurate?

**Comment by bucmic** [comment]
Goto https://docs.microsoft.com/en-us/azure/devops/organizations/security/add-users-team-project?view=azure-devops&tabs=preview-page and have a look at the last screenshot, here you find the screenshot showing how to remove the Security Service Group instead of a single user.
![image](https://user-images.githubusercontent.com/33121436/73245153-dcedb380-41ab-11ea-91fa-a8537f0aabca.png)

**Comment by msebolt** [comment]
Thank you for the update, the screenshot has been updated and is pending review/merge.
