### ISSUE TITLE
win1803 containers are being retired 2020-03-23 per an email 

### ISSUE THREAD

**Issue by marcussonestedtbarium** [MicrosoftDocs/vsts-docs#7066]
"Windows Container (win1803)
The usage of this image is the lowest among our pools – less than 1%. Any builds that target this pool will start failing on March 23, 2020."

So, remove it from this page to avoid giving people false hope. :)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 99af681d-41ad-da15-0b72-08b5cd5a11ac
* Version Independent ID: 2fa0df36-a437-8cbb-b019-b49b31b1e116
* Content: [Microsoft-hosted agents for Azure Pipelines - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops)
* Content Source: [docs/pipelines/agents/hosted.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/agents/hosted.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by msebolt** [comment]
@marcussonestedtbarium Thank you for the feedback.

Assigning this to the author for review.

**Comment by steved0x** [comment]
@marcussonestedtbarium I'll get that page updated, thank you.
