### ISSUE TITLE
package.json example typo....

### ISSUE THREAD

**Issue by tgrimm167** [MicrosoftDocs/vsts-docs#707]
There is an extra space at the end of the function name "refreshVSToken" in the example you provided for how to modify the package.json file that gave me a solid 2 hour debugging headache. If you did this intentionally to troll lazy copy pasters like me, well done, if this was any sort of accident though, please fix it :)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e4bbb17f-15a7-25d6-239c-2087d2b644b7
* Version Independent ID: f4949587-0bd0-6bfc-590f-0c4f6386dd7a
* Content: [Use npm to store JavaScript packages in Visual Studio Team Services](https://docs.microsoft.com/en-us/vsts/package/get-started-npm?view=vsts)
* Content Source: [docs/package/get-started-npm.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/package/get-started-npm.md)
* Service: **unspecified**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by elbatk** [comment]
Yikes, @tgrimm167 , I definitely didn't mean to take you on that journey. Fixing it now :)
