### ISSUE TITLE
Mermaid documentation is wrong

### ISSUE THREAD

**Issue by monroecheeseman** [MicrosoftDocs/vsts-docs#7086]
When clicking on any of the mermaid diagram links, it goes to the page "New diagrams in 8.4" mermaid in devops does not support the diagrams listed on that page.  It also doesn't support all the options for a flowchart that is listed on the page.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 29f1e43f-a069-dd88-7fc7-9cc497fb94f0
* Version Independent ID: c261afa7-6eb7-b3f0-9f92-6d2f3c5ac336
* Content: [Markdown syntax for wikis in Azure DevOps - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/project/wiki/wiki-markdown-guidance?view=azure-devops)
* Content Source: [docs/project/wiki/wiki-markdown-guidance.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/project/wiki/wiki-markdown-guidance.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Thank you @monroecheeseman, I'm following up with the PM and will notify you once I've confirmed any updates.

**Comment by chcomley** [comment]
We've published an update! Thanks @monroecheeseman, very much for your input.
