### ISSUE TITLE
System Error 64

### ISSUE THREAD

**Issue by keithnicholson** [MicrosoftDocs/vsts-docs#709]
I received the following Error as it started trying to copy to my UNC path.

     2018-05-03T22:03:30.7698315Z Copy started for - <machine name> 
     2018-05-03T22:03:31.1734790Z ##[error]System error 64 has occurred.

Is there a way to determine what the specific issue was?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5e0ef2cf-ed52-6ded-bf14-4820d73b4ed0
* Version Independent ID: 7781e0f0-43aa-9008-abda-c03a37e2d7b4
* Content: [Windows Machine File Copy task for use in the phases of all of your build and release definitions in Microsoft VSTS and TFS](https://docs.microsoft.com/en-us/vsts/build-release/tasks/deploy/windows-machine-file-copy?view=vsts)
* Content Source: [docs/build-release/tasks/deploy/windows-machine-file-copy.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/build-release/tasks/deploy/windows-machine-file-copy.md)
* Service: **unspecified**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by rokmicrosoft** [comment]
@keithnicholson  Can you please share contact details at RM_Customer_Queries@microsoft.com so we can debug this issue further. Also can you please share log with debug options true ?
