### ISSUE TITLE
Add section for skipping stages on PR triggers

### ISSUE THREAD

**Issue by qtzar** [MicrosoftDocs/vsts-docs#7098]
For PR Triggers I would like to suggest that a section be added to explain how to skip stages of the build pipeline by adding a condition to those stages. This is useful for when you want the PR to trigger a build but not trigger a deployment to certain environments.

The condition would look like :

condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5673ec1-c7d1-e0ac-043a-8fc3d5b226a9
* Version Independent ID: b4872831-51c0-6cf8-1c56-de20beb38a80
* Content: [Build pipeline triggers - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/triggers?view=azure-devops&tabs=yaml#feedback)
* Content Source: [docs/pipelines/build/triggers.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/build/triggers.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by msebolt** [comment]
@qtzar  Thank you for the feedback.

Assigning this to the author for review.

**Comment by vijayma** [comment]
Thanks for the suggestion. The next update of this doc will include this information.
