### ISSUE TITLE
Web hooks successfully proceed the the trigger but it failed on Total Results

### ISSUE THREAD

**Issue by arlind-shkrela** [MicrosoftDocs/vsts-docs#7099]
I am working on on premise version of DevOps 2019. It successfully proceed the trigger also returning successfully respond (200) but when it comes to show the total failed and succeeded calls It doesn't show correctly. Not happen just once. 
Bellow is one example img.
![image](https://user-images.githubusercontent.com/26505746/73370349-5ec90400-42b4-11ea-8c68-47afa9a46f91.png)

**Comment by WilliamAntonRohm** [comment]
@arlind-shkrela -- Arlindi, thanks for your feedback; we appreciate it. To make sure we have all the information needed to triage your issue, please let us know which topic you’re referencing, or provide more context around the general task.

**Comment by msebolt** [comment]
Closing this now, if this is product-related please submit to the product team [here](https://developercommunity.visualstudio.com/spaces/21/index.html).
