### ISSUE TITLE
Missing example for Agent.TempDirectory variable

### ISSUE THREAD

**Issue by FernandoKGA** [MicrosoftDocs/vsts-docs#7101]
https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml#system-variables

There is a missing example for the Agent.TempDirectory path, I would add to the documentation this:
`c:\agent_work\_temp`.

I wasn`t able to understand where the Agent.TempDirectory files were in the Azure DevOps pipeline.

**Comment by msebolt** [comment]
@FernandoKGA Thank you for the feedback.

Assigning this to the author for further review.
