### ISSUE TITLE
Scope of a "public project" is unclear

### ISSUE THREAD

**Issue by Justin-DynamicD** [MicrosoftDocs/vsts-docs#7103]
When toggling an Azure DevOps project to Public, it is not made clear if it is make public to the Organization or to the entire world at large.

This could cause a dangerous mistake to be made.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b9a4e9e9-6773-fad2-23fb-8b44313f8ef3
* Version Independent ID: 33cbd1fc-2230-4e0b-2627-2a63bf7c634e
* Content: [Make your project public or private - Azure DevOps Services Public Project](https://docs.microsoft.com/en-us/azure/devops/organizations/public/make-project-public?view=azure-devops#feedback)
* Content Source: [docs/organizations/public/make-project-public.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/public/make-project-public.md)
* Product: **devops**
* Technology: **devops-public-projects**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by msebolt** [comment]
@Justin-DynamicD Thank you for the feedback.

Assigning this to the author for further review.

**Comment by chcomley** [comment]
@Justin-DynamicD, I've updated the doc. Thanks so much for your input.
