### ISSUE TITLE
Is it possible to use this task on a self-hosted agent running Windows 10?

### ISSUE THREAD

**Issue by f1ben** [MicrosoftDocs/vsts-docs#7105]
The description of this task is clear, "run a Bash script on macOS, Linux, or Windows."  What setup is required on the build agent to run a Bash script on a self-hosted agent running Windows 10 Pro?  I've tried enabling WSL, and installing Ubuntu from the Microsoft Store.  When I attempt to run my bash script, I see this error message:  "Windows Subsystem for Linux has no installed distributions."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 07e70665-a794-82fd-287b-65a747488efa
* Version Independent ID: 0c34f5c3-bc80-061d-cf7a-f30c224ce3b1
* Content: [Bash task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/bash?view=azure-devops#feedback)
* Content Source: [docs/pipelines/tasks/utility/bash.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/utility/bash.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @vtbassmatt
* Microsoft Alias: **macoope**

**Comment by vtbassmatt** [comment]
Are you able to use Bash from the command line on that machine? (I don't have handy access to a Windows machine to test this.)

**Comment by f1ben** [comment]
Sorry I was unclear about this.  I am able to run bash from the command
line as the interactive user on this machine now that I've enabled the
Windows Subsystem for Linux and installed the Ubuntu distribution.
Enabling WSL is a system-wide setting, but it looks like the installation
of the Linux distribution is per-user.  The Bash Task runs on the agent as
the user "nt authority\network service".  I don't think there's a way to
login to Windows interactively as this user.  I have used psexec to launch
PowerShell as "nt authority\network service" and attempted to install
Ubuntu by following these directions:
http://www.kombitz.com/2019/09/06/command-line-to-install-ubuntu-18-04-on-windows-10/
Unfortunately, the Add-AppxPackage command fails with these errors:
Add-AppxPackage : Deployment failed with HRESULT: 0x80073D19, An error
occurred because a user was logged off.
error 0x80070002: Windows cannot register the package because of an
internal error or low memory.

**Comment by vtbassmatt** [comment]
Gotcha. Tasks runs as the user you configured the [agent to run as](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/agents?view=azure-devops&tabs=browser#account). How to do that sounds like a question for the [WSL team](https://github.com/microsoft/WSL).

**Comment by cpdohert** [comment]
Then the documentation needs to be changed to indicate that this Task will only run on Windows if you are using a Microsoft-hosted Windows agent.

**Comment by natilux2** [comment]
@vtbassmatt Can you guide how to configure the agent to run pls? I got the same issue but cant resolve it

**Comment by JayDoubleu** [comment]
@vtbassmatt what's the reason for closing this ? I'm searching for resolution to this and all github issues are closed without any resolution.

**Comment by jbizcloud** [comment]
2022 and still looking for a solution. Anyone can help, please?

**Comment by JayDoubleu** [comment]
@jbizcloud have a look here https://github.com/JayDoubleu/ado-virtual-environments 
It's a set of pipelines which allow you to essentially "1-1 MS Hosted agents" as your own private images which you can use with private agents.
