### ISSUE TITLE
Dynamic content in markdown

### ISSUE THREAD

**Issue by vort3xxx** [MicrosoftDocs/vsts-docs#7106]
It is unclear from the docs if it is possible to refer to dynamic content in markdown files via generic tokens rather than only static IDs.   The use case is this:  

0. Have a pull request template with self-referential content. 
1. Create a pull request.   
2. Have the pull request description contain a html document that refers to the pull request ID.  

What I would like to do is have my pull request template md file contain a hyperlink to http://my.staging.server/{pull_request_id}/demo, which would be a pull request based environment.

**Comment by WilliamAntonRohm** [comment]
@vort3xxx Thanks for your feedback; we appreciate it. To make sure we have all the information needed to triage your issue, please let us know which topic you’re referencing.

**Comment by msebolt** [comment]
@vort3xxx Thank you for the feedback.

Currently PR templates are only designed to get information from the submitter, not to provide them with any information such as a token or ID.

Accessing the PR ID for additional tasks such registering a PR, creating a preview, etc. should use [service hooks](https://docs.microsoft.com/azure/devops/service-hooks/services/webhooks?view=azure-devops) and the accompanying [REST API](https://docs.microsoft.com/rest/api/azure/devops).  Here you can send the user a notification with a link like the one you describe above.

**Comment by msebolt** [comment]
Closing this issue now.
