### ISSUE TITLE
How to leave an organization someone invited you to

### ISSUE THREAD

**Issue by dyslexicanaboko** [MicrosoftDocs/vsts-docs#7108]
There is an organization I am a member of. I no longer want to be a member of this organization and asking the owner to remove me isn't an option. I have been trying to figure out how to do this. Any help is appreciated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c8815945-eaa1-16e7-6ccd-ce4b5f8f8682
* Version Independent ID: 2eda53db-eaf1-e6d0-eacc-fa4507e0cb03
* Content: [Delete or remove an organization - Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/delete-your-organization?view=azure-devops)
* Content Source: [docs/organizations/accounts/delete-your-organization.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/accounts/delete-your-organization.md)
* Product: **devops**
* Technology: **devops-accounts**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by msebolt** [comment]
@dyslexicanaboko Thank you for the question.

Please refer to [this post](https://developercommunity.visualstudio.com/content/problem/333742/how-can-i-be-removed-from-a-stale-organization-in.html) and post any further issues below.

**Comment by dyslexicanaboko** [comment]
> @dyslexicanaboko Thank you for the question.
> 
> Please refer to [this post](https://developercommunity.visualstudio.com/content/problem/333742/how-can-i-be-removed-from-a-stale-organization-in.html) and post any further issues below.

Wow thank you so much! That did the trick exactly. I wish that was easier to find, I had been searching for a way to do that for such a long time and I kept coming up with nothing. This will help me clear my mind of a disastrous project, I no longer have to be reminded of it anymore thank you!
