### ISSUE TITLE
unable auth when select Azure subscription

### ISSUE THREAD

**Issue by seenualnat** [MicrosoftDocs/vsts-docs#7109]
not found https://app.vssps.visualstudio.com/oauth2/receive

**Comment by msebolt** [comment]
@seenualnat Thank you for the feedback.

Please post a reference to the article where this was listed and we will assign an author to fix the issue.

**Comment by msebolt** [comment]
Closing this now, please comment if there are further issues or contact the product team [here](https://developercommunity.visualstudio.com/spaces/21/index.html).
