### ISSUE TITLE
Extraneous asterixs in 'branches' content

### ISSUE THREAD

**Issue by DaveDustin** [MicrosoftDocs/vsts-docs#711]
In the 2nd paragraph of the Branches section, there are a number of asterisks between words which serve no purpose.  Removing them, the sentence reads correctly. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4e18eead-7795-0752-93b0-e07f6d088089
* Version Independent ID: f637de69-b13c-eed8-ab05-3515106c9270
* Content: [What is Git? - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/git/what-is-git#branches)
* Content Source: [https://mseng.visualstudio.com/DefaultCollection/TechnicalContent/_git/devops-learn-pr?path=%2fdocs%2fgit%2fwhat-is-git.md&version=GBlive&_a=contents](https://mseng.visualstudio.com/DefaultCollection/TechnicalContent/_git/devops-learn-pr?path=%2fdocs%2fgit%2fwhat-is-git.md&version=GBlive&_a=contents)
* Service: **unspecified**
* GitHub Login: @samgu
* Microsoft Alias: **kangan**

**Comment by steved0x** [comment]
@DaveDustin Thanks for letting us know, this content was recently migrated over from WordPress and it looks like some formatting errors slipped through, I'll get this fixed up.

**Comment by steved0x** [comment]
@DaveDustin I just checked in the fix and it should be live soon. Thanks for letting us know.
