### ISSUE TITLE
Should I be able to check the skip status of a stage?

### ISSUE THREAD

**Issue by kbrady-vibrato** [MicrosoftDocs/vsts-docs#7110]
The skip check for jobs as per https://docs.microsoft.com/en-us/azure/devops/pipelines/process/expressions?view=azure-devops#dependencies - does this work for a stage too?

If I have a stage dependency, can I set it to run even if the stage it depends on is skipped?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77c58a78-a567-e99a-9eb7-62dddd1b90b6
* Version Independent ID: 680a79bc-11de-39fc-43e3-e07dc762db18
* Content: [Expressions - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/expressions?view=azure-devops#dependencies)
* Content Source: [docs/pipelines/process/expressions.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/expressions.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by msebolt** [comment]
@kbrady-vibrato Thank you for the question.

Unfortunately questions outside the scope of the article need to be submitted [here](https://developercommunity.visualstudio.com/spaces/21/index.html) for feedback from the product team.

For additional support options, please refer to:

- [Azure DevOps Support](https://azure.microsoft.com/support/devops/)
- [Azure DevOps on StackOverflow](https://stackoverflow.com/questions/tagged/azure-devops)

@juliakm
