### ISSUE TITLE
Nuget restore doesn't get skipped even though cache is restored successfully

### ISSUE THREAD

**Issue by RobCoPKC** [MicrosoftDocs/vsts-docs#7111]
The 2 relevant pipeline steps:

- task: Cache@2
  condition: succeeded()
  displayName: Cache NuGet packages
  inputs:
    key: 'nuget | "$(Agent.OS)" | **/packages.lock.json'
    restoreKeys: |
       nuget | "$(Agent.OS)"
       nuget
    path: $(NUGET_PACKAGES)
    cacheHitVar: CACHE_RESTORED

- task: NuGetCommand@2
  condition: ne(variables.CACHE_RESTORED, 'true')
  displayName: Restore
  inputs:
    command: 'restore'
    restoreSolution: '**/*.sln'
    feedsToUse: 'config'

Even though the cache is restore successfully, the nuget restore doesn't get skipped.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77c20289-dab2-7a6e-4f63-4b30eaff2c71
* Version Independent ID: d75cc196-90c1-8291-9907-ff405bde4edf
* Content: [Pipeline caching - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/caching/?view=azure-devops)
* Content Source: [docs/pipelines/caching/index.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/caching/index.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @chasewilson
* Microsoft Alias: **phwilson**

**Comment by RobCoPKC** [comment]
This doesn't seem to be related to the cache restore since the nuget restore wasn't even skipped when I manually set the "CACHE_RESTORED"-variable to true.
Maybe a problem with how conditions work?

**Comment by PavelPikat** [comment]
The task order is wrong here.
In your case the cache will never be populated, because $(NUGET_PACKAGES) path is empty - NuGet packages are always restored after the Cache task.

**Comment by RobCoPKC** [comment]
I set $(NUGET_PACKAGES) to $(Pipeline.Workspace)/.nuget/packages via:

variables:
  VersionInfo.Build: $(Build.BuildNumber)
  NUGET_PACKAGES: $(Pipeline.Workspace)/.nuget/packages

Forgot to mention that in my OP.

**Comment by PavelPikat** [comment]
I meant that the folder will not have any packages there yet since they are restored afterwards.
You need to restore first, then cache.

**Comment by RobCoPKC** [comment]
The cache task downloads 468 MBs of packages and the nuget restore only takes seconds because all the packages are already there, so no, the caching is working fine...

![image](https://user-images.githubusercontent.com/56680419/73454674-db201d80-436e-11ea-9bb0-145f22600eca.png)

**Comment by PavelPikat** [comment]
Apologies, you are right, the cache task has to be first.
I think even if we accept that the condition does not work for NuGet restore task, you actually do want it to execute in your case, because you need to move packages from .nuget/packages into your solution folder. And this is what takes you seconds already.

**Comment by PavelPikat** [comment]
Btw, try using this condition instead, it is working for me:
`ne(variables['NUGET_CACHE_RESTORED'], 'true')`

**Comment by WilliamAntonRohm** [comment]
@RobCoPKC -- thank you for your feedback.

@PavelPikat -- thank you for sharing a viable syntax.

**Comment by WilliamAntonRohm** [comment]
@chasewilson -- Chase, please review the above-mentioned PR 937.

**Comment by WilliamAntonRohm** [comment]
This content has already been updated and is here:  https://docs.microsoft.com/en-us/azure/devops/pipelines/release/caching?view=azure-devops

**Comment by binair-io** [comment]
For others landing on this page, the solution is to set **cacheHitVar** to a variable which will then be updated accordingly, as shown in the page linked by @WilliamAntonRohm. (section [Conditioning on Cache Restoration](https://learn.microsoft.com/en-us/azure/devops/pipelines/release/caching?view=azure-devops#conditioning-on-cache-restoration))

```
variables:
  CACHE_RESTORED: 'false' <<----

steps:
- task: Cache@2
  inputs:
    key: mykey | mylockfile
    restoreKeys: mykey
    path: $(Pipeline.Workspace)/mycache
    cacheHitVar: CACHE_RESTORED <<----

- script: install-deps.sh
  condition: ne(variables.CACHE_RESTORED, 'true')  <<----

- script: build.sh
```
