### ISSUE TITLE
Scheduled YAML Builds Using UTC Time

### ISSUE THREAD

**Issue by droessmj** [MicrosoftDocs/vsts-docs#7117]
Appreciate the feedback, but that statement directly conflicts with the behavior I experienced when working with this yesterday. 

Our organization runs with UTC-6, 
![image](https://user-images.githubusercontent.com/6099561/73277498-deb97600-41af-11ea-9e8c-55a21efc20d0.png)
but I needed to set a schedule for 18:20 yesterday for it to trigger at 12:20PM CT. 

![image](https://user-images.githubusercontent.com/6099561/73277623-11636e80-41b0-11ea-90c0-0fa5932b36a1.png)
The first value was going to schedule at 6:20AM the following day, hence the update to 18:20. This was at 12:15 yesterday afternoon. 

Let me know if you'd prefer I open an issue, but this PR was submitted in an attempt to reduce future occurrences. 

Only other potential impact I can come up with offhand is that the pool in use is a Windows Hosted Agent rather than a corporately hosted pool. Not sure if that would make a difference or not on scheduling?

_Originally posted by @droessmj in https://github.com/MicrosoftDocs/vsts-docs/pull/7073#issuecomment-579300201_

**Comment by steved0x** [comment]
@droessmj It is in UTC time, I have approved your PR and I'm closing this issue. Thank you for your feedback.
