### ISSUE TITLE
Is it expected that you can't deprecate or demote Maven artifacts? 

### ISSUE THREAD

**Issue by soccerjoshj07** [MicrosoftDocs/vsts-docs#7119]
With Maven artifacts, you can only promote them. You cannot unpromote, demote, or deprecate them as you can with Nuget artifacts. Is this by intention? Not sure if this is a bug or if there was some intention behind this. See this example - this artifact is in the @Release view, but if I didn't want it in the Release view or placed it there accidentally, I have no recourse other than permanently deleting the package version.

See example: 
![image](https://user-images.githubusercontent.com/19912012/73483555-3a793000-4365-11ea-9109-c825d3167005.png)

And before you close this saying it's a problem with the product and not the documentation - at least make some note that artifacts are added to a view they cannot be removed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b254809-bcfe-5859-42e1-05df82aa730b
* Version Independent ID: cd8e1d01-c11b-4173-8f36-95d4237bc6a5
* Content: [Communicate package quality with release views - Azure Artifacts](https://docs.microsoft.com/en-us/azure/devops/artifacts/feeds/views?view=azure-devops)
* Content Source: [docs/artifacts/feeds/views.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/artifacts/feeds/views.md)
* Product: **devops**
* Technology: **devops-artifacts**
* GitHub Login: @chasewilson
* Microsoft Alias: **phwilson**

**Comment by ramiMSFT** [comment]
@soccerjoshj07 Thank you for the feedback. Package demotion is not supported currently. I'm adding a note for more clarification and will be reaching out to the product team to see if we can get this feature added to a future release
