### ISSUE TITLE
VSTS Nuget Package Source Authentication

### ISSUE THREAD

**Issue by drewwilliams1982** [MicrosoftDocs/vsts-docs#712]
In VSTS, under "Connect to feed" the link "How do I set up this package source in Visual Studio?" brings you to this page. This page doesn't detail how to handle authentication in visual studio.

All it needs is a link to the relevant document, and it would have saved me a lot of time.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 899a78d6-9d08-7744-108d-10add2ba7e2c
* Version Independent ID: 6ab31e96-fed8-4335-ed81-b97663d8300f
* Content: [Consume NuGet packages in Visual Studio](https://docs.microsoft.com/en-gb/vsts/package/nuget/consume?view=vsts#windows-add-the-feed-to-your-nuget-configuration)
* Content Source: [docs/package/nuget/consume.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/package/nuget/consume.md)
* Service: **unspecified**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by elbatk** [comment]
Hey @drewwilliams1982 , did you find the documentation you needed? Do you think we should add authentication to this document or link to another one? Adding @alexmullans from the product team to check out the input here as well.

**Comment by elbatk** [comment]
Didn't mean to close, oops! Reopening!

**Comment by alexmullans** [comment]
@drewwilliams1982 what are the authentication issues you're having? If you're on VS 2015 Update 1 or later, the NuGet Package Manager will automatically authenticate to VSTS feeds.

**Comment by drewwilliams1982** [comment]
Thanks for getting back to me.

I ended up having to install the Credential Provider. 

I am developing a small project in .net core and vscode, but I've got something funky going on with my feeds there, which only searches my corporate feed, not nuget.org nor any other feed I set up.

So I switched to VS2017, which manages all feeds just fine. If I recall correctly, that did prompt for credentials, however, it never authenticated. No error message as I recall. Installing the credential provider, as buried in this document (https://docs.microsoft.com/en-us/vsts/package/nuget/nuget-exe?view=vsts#download-the-credential-provider-directly) solved the issue for me.

Perhaps this is all due to an environmental config issue on my machine? Maybe a footnote on how authentication works in the different dev environments would help (.net core, > vs 2015 update 1, < vs 2015 update 1 etc...).

Thanks again!

**Comment by drewwilliams1982** [comment]
To follow up on this, trying to use "dotnet add package <package> -s <vsts url>" results in a 401. Even though I have the credential provider installed. It's not obvious where I can find out how to solve this.

**Comment by alexmullans** [comment]
The Credential Provider doesn't currently work with dotnet. You'll need to use the [instructions here for now](https://docs.microsoft.com/en-us/vsts/package/nuget/dotnet-exe?view=vsts). https://github.com/NuGet/Home/issues/6486 tracks the work to create a cross-platform Credential Manager that works in all NuGet endpoints (including dotnet).

**Comment by elbatk** [comment]
@drewwilliams1982 closing this issue as it seems @alexmullans has provided a solution for ya! Feel free to comment and reopen if you're still having issues.

**Comment by drewwilliams1982** [comment]
Yeah I'm happy I have my issue resolved. It would be useful for others to know about the dotnet link though! Perhaps update the docs to link to that?

**Comment by johnkors** [comment]
@alexmullans , I have the same issue sort of.  I cannot get an Azure Devops build pipeline to authenticate to a feed. It just spits out 401s when trying to restore a package from the artifacts feed.  See https://github.com/Microsoft/azure-pipelines-tasks/issues/8641 

Could you help out?

**Comment by fakhrulhilal** [comment]
I have the same issue with my on premise TFS 2018.3. I try to download using VS 2017 15.9.3, the error occurs with the following message:

[NugetKeyName] Unable to load the service index for source https://on-premise-server/tfs/[ProjectCollection]/_packaging/[FeedName]/nuget/v3/index.json.
  Response status code does not indicate success: 401 (Unauthorized).

It prompts when downloading for the first time, then I use my domain user but using PAT (packaging: manage, read, write) as password. Just note that I'm the feed owner who create that feed. However, I can open the feed link using browser (with json result). 

Can you help?

**Comment by alexmullans** [comment]
@johnkors @fakhrulhilal please post your questions on [Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html), which is actively monitored.

**Comment by fakhrulhilal** [comment]
Thanks, I'm starting new thread instead #2754
