### ISSUE TITLE
How to use pipeline decorator in Deployment job

### ISSUE THREAD

**Issue by MBiekem** [MicrosoftDocs/vsts-docs#7124]
I'm missing information about injecting the decorator inside the deployment jobs. 

The Sprint 163 update says:

> You can now add pipeline decorators to deployment jobs. You can have any custom step (e.g. vulnerability scanner) auto-injected to every life cycle hook execution of every deployment job.

How do I inject a decorator to a life cycle hook for deployment jobs?

Using the targets property, I get it to work with build jobs and release pipelines, but not with deployment jobs (from Yaml).

**Comment by WilliamAntonRohm** [comment]
@MBiekem Thanks for your feedback; we appreciate it. To make sure we have all the information needed to triage your issue, please let us know which topic you’re referencing.

**Comment by MBiekem** [comment]
> @MBiekem Thanks for your feedback; we appreciate it. To make sure we have all the information needed to triage your issue, please let us know which topic you’re referencing.

This page:
https://docs.microsoft.com/en-us/azure/devops/extend/develop/add-pipeline-decorator?view=azure-devops#author-a-pipeline-decorator

**Comment by MBiekem** [comment]
Created the issue again from the docs page itself.
