### ISSUE TITLE
Non existing links to pages in organizations/projects/toc.yml

### ISSUE THREAD

**Issue by MitchelVreman** [MicrosoftDocs/vsts-docs#7125]
Hi,
Sorry if the format of the issue isn't as it should be. I couldn't find the rules of it.

I found an issue while navigating through the docs. I received an 404 on "Set project visibility" and on "Change service visibility". By further diving in to it, I found the file and the issue:
[organizations/projects/toc.yml](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/projects/toc.yml)
line: 22 and 24.
The paths are non-existing in the repo (maybe deleted).

**Comment by WilliamAntonRohm** [comment]
@MitchelVreman -- Mitchel, thanks for your feedback; we appreciate it. To make sure we have all the information needed to triage your issue, please let us know which topic you’re referencing, or provide more context around the general task.

**Comment by MitchelVreman** [comment]
@WilliamAntonRohm -- You can see the issue when navigating to https://docs.microsoft.com/en-us/azure/devops/organizations/projects/restore-project?view=azure-devops (for example). 
Then using the menu to go to "Set project visibility" or "Change service visibility":
![image](https://user-images.githubusercontent.com/7677974/73637264-318ba580-4668-11ea-9172-713a332006e4.png)

I hope you can do something with this information.

**Comment by WilliamAntonRohm** [comment]
@MitchelVreman -- Mitchel, thank you for your feedback.

@chcomley -- please let me know the new target paths, or whether these links should be deleted, and I will update toc.yml appropriately.

**Comment by chcomley** [comment]
Hi @MitchelVreman, I've published an update fixing the TOC issue, which should be live momentarily. Thanks very much for letting us know about this!
