### ISSUE TITLE
Azure Artifacts Too Permissive

### ISSUE THREAD

**Issue by cmeyertons** [MicrosoftDocs/vsts-docs#7126]
For on-prem agents where security is a concern, requiring opening *.blob.core.windows.net in a corporate firewall opens up an attack vector for malicious code to be downloaded from anywhere hosted on blob storage. 

Is there a more granular DNS / IPs that are wholly owned by Microsoft we can open up to in our firewall?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc5a4cfa-aa84-9f0f-55f4-71ec4861c070
* Version Independent ID: d621620a-c924-03b1-8b43-f99c33e58bb8
* Content: [Add IP addresses and URLs to allow list - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/security/allow-list-ip-url?view=azure-devops#feedback)
* Content Source: [docs/organizations/security/allow-list-ip-url.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/security/allow-list-ip-url.md)
* Product: **devops**
* Technology: **devops-security**
* GitHub Login: @chcomley
* Microsoft Alias: **ChComley**

**Comment by msebolt** [comment]
@cmeyertons Thank you for the question.

This issue is currently active in https://github.com/MicrosoftDocs/vsts-docs/issues/6242.

Please refer there if you have any additional comments and/or would like to check the status.
