### ISSUE TITLE
Take App Offline flag - Which app_offline.htm file will be used? 

### ISSUE THREAD

**Issue by pijemcolu** [MicrosoftDocs/vsts-docs#7127]
The documentation doesn't specify what file is used when the app is taken offline using the flag.

Is it a default file? Is the file sourced from a specific path? Can we customise the file?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be413593-c38c-d3bf-8450-627f3c4928b1
* Version Independent ID: 4d4e3115-5146-b715-7940-39a68186c871
* Content: [IIS Web App Deploy task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/iis-web-app-deployment-on-machine-group?view=azure-devops#)
* Content Source: [docs/pipelines/tasks/deploy/iis-web-app-deployment-on-machine-group.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/deploy/iis-web-app-deployment-on-machine-group.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by RoopeshNair** [comment]
This is based on webdeploy (MSDeploy) tool. It drops a blank app_offline.htm to the root of application folder. It is not customizable. More [here](https://docs.microsoft.com/en-us/iis/publish/deploying-application-packages/taking-an-application-offline-before-publishing)

**Comment by glautrou** [comment]
It should be customizable: -dest:iisApp=destApp,appOfflineTemplate="offlineTemplate.htm"

Unfortunately there is no way to specify this in the Azure DevOps task, meaning the "Take App Offline" option is useless, who want to see a blank page on a website?
The only solution is to manually add an app_offline.html file in artifacts and then copy it to the root before deployment before the WebDeploy task, and after the MsDeploy task deleting it.

IIS blog:  https://blogs.iis.net/msdeploy/webdeploy-3-5-rtw

Please reopen.
