### ISSUE TITLE
Please clarify version of AzCopy used

### ISSUE THREAD

**Issue by p1johnson** [MicrosoftDocs/vsts-docs#7128]
Can the page clarify what version of AzCopy is used by this task? The currently supported version is AzCopy v10 but it looks like this task is using AzCopy v8.1 - as the parameters have changed quite a bit between versions, it might cause a bit of confusion. This page links to https://docs.microsoft.com/en-gb/azure/storage/common/storage-use-azcopy-v10 which is the v10 documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 622daa35-c6a1-dac3-17ee-3f9308fc60cd
* Version Independent ID: 2c28a59b-8ef5-d7ab-46a6-58748ec552f5
* Content: [Azure File Copy task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-file-copy?view=azure-devops#feedback)
* Content Source: [docs/pipelines/tasks/deploy/azure-file-copy.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/deploy/azure-file-copy.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by msebolt** [comment]
@p1johnson Thank you for the feedback.

Assigning this to the author for further review.

**Comment by RoopeshNair** [comment]
@ninallam

**Comment by ninallam** [comment]
Added AzCopy Version details
