### ISSUE TITLE
The names in the first diagram are not visible in dark theme

### ISSUE THREAD

**Issue by slavizh** [MicrosoftDocs/vsts-docs#713]
The names in the first diagram are not visible in dark theme

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 92be2bb1-d071-8531-4dea-75fbffdbe764
* Version Independent ID: 82b71f3e-48ee-6616-30eb-f939941807ea
* Content: [What is Scrum? - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/agile/what-is-scrum)
* Content Source: [https://mseng.visualstudio.com/DefaultCollection/TechnicalContent/_git/devops-learn-pr?path=%2fdocs%2fagile%2fwhat-is-scrum.md&version=GBlive&_a=contents](https://mseng.visualstudio.com/DefaultCollection/TechnicalContent/_git/devops-learn-pr?path=%2fdocs%2fagile%2fwhat-is-scrum.md&version=GBlive&_a=contents)
* Service: **unspecified**
* GitHub Login: @samgu
* Microsoft Alias: **gregboe**

**Comment by steved0x** [comment]
@slavizh Here is what it looks like for me on chrome, can you share a screenshot and more details about your browser and I can see what we need to fix. Is this the right image?

![image](https://user-images.githubusercontent.com/1580889/39642557-1af82728-4fa0-11e8-8bed-305bdf9d7e1a.png)

**Comment by steved0x** [comment]
@slavizh I'm going to close all of these except for https://github.com/MicrosoftDocs/vsts-docs/issues/716 which I'll keep open until we have a fix. Thanks for reporting these.

**Comment by steved0x** [comment]
This is fixed and should be live in a day or two, thank you.
