### ISSUE TITLE
Demand any or specific machine

### ISSUE THREAD

**Issue by RichardMeadowsTC** [MicrosoftDocs/vsts-docs#7134]
I often need to test a build on a specific machine.  We are using yaml definitions so my options (That I am aware of are)
1. Create special yaml which include demand for Agent.ComputerName -eq 'specificMachine'
2. Move the machine in question to a pool that has only that machine.

Is it possible to have a demand in yaml like
3.  demand Agent.ComputerName -like '*'

Example we specify a default pool or a specific one at queue time using following yaml.
parameters:
  buildPool: $[coalesce(variables.PoolName, 'OnPremAgents')]
  pool:
    name: ${{ parameters.buildPool }}

I would like to add something similar for the agent.computername demand.  But have not found anything that will work.  Not sure it I have tried using -like.  Many things have failed to work :)

parameters:
  buildPool: $[coalesce(variables.PoolName, 'OnPremAgents')]
  agentName: $[coalesce(variables.MName, '*')]
  pool:
    name: ${{ parameters.buildPool }}
    demands:
    - agent.computername -like ${{ parameters.agentName }}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e7541ee6-d2bb-84c0-fead-1aa8ee7d2372
* Version Independent ID: 5cf7c51e-37e1-6c67-e6c6-80262c4eb662
* Content: [Demands - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/demands?view=azure-devops&tabs=yaml#feedback)
* Content Source: [docs/pipelines/process/demands.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/demands.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by msebolt** [comment]
@RichardMeadowsTC Thank you for the feedback.

You are correct in that current functionality is limited to `equals` or the existence of a custom capability.  

For your scenario you would need to create a custom capability such as `ComputerNameAgent' and then to use its existence as a `like` substitute:

```
name: ${{ parameters.buildPool }}
demands:
- agent.computername -like ${{ parameters.agentName }}
```
becomes,
```
name: ${{ parameters.buildPool }}
demands:
- ComputerNameAgent
```
Then, to use an actual computer name:
```
name: ${{ parameters.buildPool }}
demands:
- ComputerNameAgent -eq ${{ parameters.agentName }}
```

Definitely a good suggestion for the product team, please consider starting this issue [here](https://developercommunity.visualstudio.com/topics/Azure+DevOps.html) and/or voting with [this similar request](https://developercommunity.visualstudio.com/idea/617997/allow-or-condition-for-agent-demands-in-task-defin.html).

**Comment by msebolt** [comment]
Closing is now, please comment below if there are further issues.
