### ISSUE TITLE
Relative trigger paths

### ISSUE THREAD

**Issue by cadull** [MicrosoftDocs/vsts-docs#7138]
Are trigger paths relative to the yml file (when in a subdirectory) or relative to the repository root?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5673ec1-c7d1-e0ac-043a-8fc3d5b226a9
* Version Independent ID: b4872831-51c0-6cf8-1c56-de20beb38a80
* Content: [Build pipeline triggers - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/triggers?tabs=yaml&view=azure-devops#feedback)
* Content Source: [docs/pipelines/build/triggers.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/build/triggers.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by msebolt** [comment]
@cadull  Thank you for the question.

Trigger paths are relative the repository root.

Assigning this to the author for review.

**Comment by vijayma** [comment]
Thanks for calling this out. We are making an update to the doc to clarify this.
