### ISSUE TITLE
Two of the diagrams have black text which is not visible in dark theme

### ISSUE THREAD

**Issue by slavizh** [MicrosoftDocs/vsts-docs#714]
Two of the diagrams have black text which is not visible in dark theme

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f4bc244f-e07c-f8a4-0f00-04c8e015821f
* Version Independent ID: 2a37fdcf-eac8-3738-af46-7d70826ec660
* Content: [Scale Agile to Large Teams - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/agile/scale-agile-large-teams)
* Content Source: [https://mseng.visualstudio.com/DefaultCollection/TechnicalContent/_git/devops-learn-pr?path=%2fdocs%2fagile%2fscale-agile-large-teams.md&version=GBlive&_a=contents](https://mseng.visualstudio.com/DefaultCollection/TechnicalContent/_git/devops-learn-pr?path=%2fdocs%2fagile%2fscale-agile-large-teams.md&version=GBlive&_a=contents)
* Service: **unspecified**
* GitHub Login: @samgu
* Microsoft Alias: **gregboe**

**Comment by steved0x** [comment]
@slavizh I'm going to close all of these except for https://github.com/MicrosoftDocs/vsts-docs/issues/716 which I'll keep open until we have a fix. Thanks for reporting these.

**Comment by steved0x** [comment]
This is fixed and should be live in a day or two, thank you.
