### ISSUE TITLE
Kubernetes service connection not working

### ISSUE THREAD

**Issue by techsaau** [MicrosoftDocs/vsts-docs#7142]
I'm working on AKS and Azure Devops for CI\CD pipeline. It seems this morning Microsoft updated "**Kubernetes service connection**" in Azure DevOps. I'm trying update current AKS connection with new KubeConfig and getting **serviceEndpointDetails.Authorization: null** error:

![image](https://user-images.githubusercontent.com/46290126/73647617-2a6e9280-467c-11ea-9cd2-eb841d278d20.png)

I got this issue today morning. Before this incident, connection update operation was working perfectly fine.

When I try to create a new connection, I didn't receive any error

**Comment by andreitoupinets** [comment]
I have same problem, but it can be solved when you update/create service connection using "Azure Subscription" option, save it and than edit it again using "KubeConfig" option.

**Comment by msebolt** [comment]
@techsaau Thank you for the feedback, we apologize for any issues you're having.

Please see if @andreitoupinets post fixes the issue, otherwise start a support ticket [here](https://developercommunity.visualstudio.com/content/problem/post.html?space=22) with the product team on how to best proceed.

**Comment by techsaau** [comment]
This workaround worked after 15-20 attempts. I have logged a ticket [](https://developercommunity.visualstudio.com/content/problem/911805/kubernetes-service-connection-not-working-as-expec.html)

**Comment by techsaau** [comment]
I was using preview feature of service connections. after reverting to old one, it is working as expected

**Comment by ashokirla** [comment]
Are you still facing the issue in new UI. Can you enable untrusted certificates check box and try again
