### ISSUE TITLE
Java pipeline template referred instead of Python

### ISSUE THREAD

**Issue by ivangeorgiev** [MicrosoftDocs/vsts-docs#7148]
Step 6 from Create a Python-specific pipeline to deploy to App Service refers to selecting "Maven package Java project Web App to Linux on Azure" on "Configure your pipeline". The correct one should be "Python to Linux Web App on Azure"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eefdcb17-b1e5-141c-aef8-36795c9983af
* Version Independent ID: 007ebfcf-12bf-755c-858b-540d0fc59f96
* Content: [Build and deploy Python web apps - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/ecosystems/python-webapp?view=azure-devops#feedback)
* Content Source: [docs/pipelines/ecosystems/python-webapp.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/ecosystems/python-webapp.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @kraigb
* Microsoft Alias: **kraigb**

**Comment by kraigb** [comment]
@N-Usha Looks like you're maintaining this article now, and likely introduced this error. Can you correct, and also mark yourself as the author?

**Comment by iamsrivatsa** [comment]
The document has been updated and I'll be closing the issue. Thank you for the feedback and feel free to open a new issue if you have any more feedback.
