### ISSUE TITLE
Are these client libraries supported in UWP?

### ISSUE THREAD

**Issue by dpaulino** [MicrosoftDocs/vsts-docs#7150]
UWP can use any .NET Standard 2.0 libraries, so theoretically, these should work. However, I would like confirmation from someone. Can anyone confirm? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 413163f0-28c3-a2a7-d626-fcb81bcb2257
* Version Independent ID: 57c127da-2b1e-d29e-9abb-a3c258762ccf
* Content: [.NET Client Libraries - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/integrate/concepts/dotnet-client-libraries?view=azure-devops)
* Content Source: [docs/integrate/concepts/dotnet-client-libraries.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/integrate/concepts/dotnet-client-libraries.md)
* Product: **devops**
* Technology: **devops-ecosystem**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by dpaulino** [comment]
I performed some testing. The nuget packages can be added to a UWP project, but when you attempt to create a Store Upload Package, the Windows App Certification Kit will fail the package. The error is related to sni.dll not being in the app container.

Did some digging, and sni.dll is use by some Sql client package that the ADO nuget package is dependent on. 

Thus, one cannot publish a UWP app to the store while having these ADO packages as dependencies. 

Is this a bug? Where can I file a bug for the nuget packages themselves?

**Comment by WilliamAntonRohm** [comment]
@dpaulino -- Daniel, thank you for your feedback and research.  It looks like you've encountered an issue with the product itself, rather than an issue with the documentation. To make sure it gets in front of the right people, please [submit your bug]( https://developercommunity.visualstudio.com/content/problem/post.html?space=21) here.
