### ISSUE TITLE
Move a work item to another project resets all states

### ISSUE THREAD

**Issue by thomasvehus** [MicrosoftDocs/vsts-docs#7152]
Under the section https://docs.microsoft.com/en-us/azure/devops/boards/backlogs/remove-delete-work-items?view=azure-devops&tabs=browser#move-a-work-item-to-another-project

It says: "Also, the system automatically resets the State and Reason fields to the default initial values for the work item type that you move"

This behavior should be made optional (at least for State) to be able to preserve state of work items when moving them to another project.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e9f02cb-f094-d6bc-ca7b-973db9de0082
* Version Independent ID: 1af6a7f5-9e99-ec99-081d-c0bf9e7ac5f5
* Content: [Move, change, and delete work items - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/backlogs/remove-delete-work-items?view=azure-devops&tabs=browser#move-a-work-item-to-another-project)
* Content Source: [docs/boards/backlogs/remove-delete-work-items.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/boards/backlogs/remove-delete-work-items.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@thomasvehus - Thank you for your feedback. Since this is a proposed change to a feature, please make your suggestion at our [Developer Community page](https://developercommunity.visualstudio.com/spaces/21/index.html).
