### ISSUE TITLE
Document contains a typo with single brackets instead of double brackets around TOC

### ISSUE THREAD

**Issue by samvanbrussel** [MicrosoftDocs/vsts-docs#7153]
'To create a table of contents, add a [_TOC_].' should be 'To create a table of contents, add a [[_TOC_]].'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 29f1e43f-a069-dd88-7fc7-9cc497fb94f0
* Version Independent ID: c261afa7-6eb7-b3f0-9f92-6d2f3c5ac336
* Content: [Markdown syntax for wikis in Azure DevOps - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/project/wiki/wiki-markdown-guidance?view=azure-devops#feedback)
* Content Source: [docs/project/wiki/wiki-markdown-guidance.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/project/wiki/wiki-markdown-guidance.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by JohnKeippel** [comment]
Thanks for opening this! Just completed a pull request and wondered why [TOC] didn't work even though I copy/pasted from this very page.
