### ISSUE TITLE
Add Note Regarding Package Demotion

### ISSUE THREAD

**Issue by qJake** [MicrosoftDocs/vsts-docs#7156]
There is no mention in this article regarding package demotion.

A user coming to this page should be able to view information on how to demote a package, and what platform(s) this operation is supported on.

For example, if there is no UI to demote a package or remove it from a view, a note should be added to this article. However, if it is possible to demote a package via an API request, then a code sample should be providede, or a link to the API reference article should be included.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b254809-bcfe-5859-42e1-05df82aa730b
* Version Independent ID: cd8e1d01-c11b-4173-8f36-95d4237bc6a5
* Content: [Communicate package quality with release views - Azure Artifacts](https://docs.microsoft.com/en-us/azure/devops/artifacts/feeds/views?view=azure-devops#feedback)
* Content Source: [docs/artifacts/feeds/views.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/artifacts/feeds/views.md)
* Product: **devops**
* Technology: **devops-artifacts**
* GitHub Login: @chasewilson
* Microsoft Alias: **phwilson**

**Comment by ramiMSFT** [comment]
@qJake Thank you for the feedback. I'm adding a note to address your comment and will be reaching out to the product team to see if we can get this feature added to a future release
