### ISSUE TITLE
The informaiton on many of the picture is not completely visible in dark theme

### ISSUE THREAD

**Issue by slavizh** [MicrosoftDocs/vsts-docs#716]
The informaiton on many of the picture is not completely visible in dark theme

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0cf98c4b-9185-00d5-a980-e2adb3e291fd
* Version Independent ID: f6005931-c9b5-48d9-e6c3-f835bb9b01b1
* Content: [What is DevOps? - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/what-is-devops)
* Content Source: [https://mseng.visualstudio.com/DefaultCollection/TechnicalContent/_git/devops-learn-pr?path=%2fdocs%2fwhat-is-devops.md&version=GBlive&_a=contents](https://mseng.visualstudio.com/DefaultCollection/TechnicalContent/_git/devops-learn-pr?path=%2fdocs%2fwhat-is-devops.md&version=GBlive&_a=contents)
* Service: **unspecified**
* GitHub Login: @samgu
* Microsoft Alias: **samgu**

**Comment by steved0x** [comment]
@slavizh I'll do a sweep and get these fixed up.

**Comment by steved0x** [comment]
This is fixed and should be live in a day or two, thank you.
