### ISSUE TITLE
Variables does not display in UI

### ISSUE THREAD

**Issue by nithinvenugopal** [MicrosoftDocs/vsts-docs#7160]
Only if variables group is defined will appear in the Variables field in UI. If we define a global variable as below, it will not display in the UI before running the pipeline.
variables:
  configuration: debug
  platform: x64

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd7e0bd3-1f7d-d7b6-cc72-5ef63c31b46a
* Version Independent ID: dae87abd-b73d-9120-bcdb-6097d4b40f2a
* Content: [Variables - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch#feedback)
* Content Source: [docs/pipelines/process/variables.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/variables.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by juliakm** [comment]
@nithinvenugopal and @msebolt  I'm confused about whether this is a documentation issue or if it is a problem with the product. Did you expect the product to work one way and it did not?

**Comment by msebolt** [comment]
@juliakm  If this is a valid issue, I thought a note should be added to the documentation.

**Comment by nithinvenugopal** [comment]
I am sorry that I wasn't clear earlier. I feel this is a documentation concern + feature request. 
When I define a variable in yaml file, pipeline should automatically consider that to be a user input and display it under the variables option.
Currently variables has to be configured additionally for the pipeline using UI in order to take input from the user. This is not clear from the documentation.

**Comment by juliakm** [comment]
@nithinvenugopal I've updated the docs for clarification. If you'd like to also submit a feature request, please reach out to the [Azure DevOps Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html). That site is monitored by the product team.
