### ISSUE TITLE
The picture is not fully visible in dark theme

### ISSUE THREAD

**Issue by slavizh** [MicrosoftDocs/vsts-docs#717]
The picture is not fully visible in dark theme

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1bc48620-03dc-7d0e-5e30-2e70fd114028
* Version Independent ID: 6142280a-a27b-aaf6-43ef-b91f7ae44084
* Content: [What is Continuous Integration? - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/what-is-continuous-integration)
* Content Source: [https://mseng.visualstudio.com/DefaultCollection/TechnicalContent/_git/devops-learn-pr?path=%2fdocs%2fwhat-is-continuous-integration.md&version=GBlive&_a=contents](https://mseng.visualstudio.com/DefaultCollection/TechnicalContent/_git/devops-learn-pr?path=%2fdocs%2fwhat-is-continuous-integration.md&version=GBlive&_a=contents)
* Service: **unspecified**
* GitHub Login: @samgu
* Microsoft Alias: **samgu**

**Comment by steved0x** [comment]
@slavizh I'm going to close all of these except for https://github.com/MicrosoftDocs/vsts-docs/issues/716 which I'll keep open until we have a fix. Thanks for reporting these.

**Comment by steved0x** [comment]
This is fixed and should be live in a day or two, thank you.
