### ISSUE TITLE
What are the full list of demands supported?

### ISSUE THREAD

**Issue by yosephlodamo** [MicrosoftDocs/vsts-docs#7170]
What are the full list of demands supported?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e7541ee6-d2bb-84c0-fead-1aa8ee7d2372
* Version Independent ID: 5cf7c51e-37e1-6c67-e6c6-80262c4eb662
* Content: [Demands - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/demands?view=azure-devops&tabs=yaml#feedback)
* Content Source: [docs/pipelines/process/demands.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/demands.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by WilliamAntonRohm** [comment]
@yosephlodamo -- Yoseph, the `demands` keyword is also documented [here](https://docs.microsoft.com/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema#demands).  The syntax allows for any custom demand, so a complete list is not possible.

@steved0x -- Steve, please look into further clarifying this topic and the one linked above.

**Comment by reynoldsbd** [comment]
@WilliamAntonRohm appreciate the pointer to the `demands` schema! However, that link only tells me that `demands` accepts an array of strings. In particular, it does not tell me the supported syntax for those strings.

Based on the examples on this page, I know that there is some kind of `-equals` operator available. Are there any other operators available? What kinds of expressions can I use as operands to this operator?

(It would be nice if `demands` supported the same expression language as the rest of Azure Pipelines)

**Comment by CodeSwimBikeRunner** [comment]
@reynoldsbd I had the exact same question, but posted it on their github. They shirked me off and closed the question , saying it was an implementation detail.

**Comment by MarkIannucci** [comment]
@reynoldsbd @CodeSwimBikeRunner @yosephlodamo , based on the statement 'You can check for the existence of a capability or a specific string' in the [yaml-schema demands specification](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/yaml-schema.md#demands) , I did not attempt to use an expression that would evaluate to a boolean.  Instead, I populated a parameter on my template and got the agent's capability key value to equal my parameter value.  Syntax follows:

    demands:
      - ClarityBranchAffinity -equals ${{ parameters.BranchMoniker }}

In my use case, `ClarityBranchAffinity` is a user specified demand on our agents, and parameters.BranchMoniker is set by the yaml file that consumes the template, which in my scenario is a variable (whose value is determined using [conditional insertion](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/templates?view=azure-devops#conditional-insertion) template syntax).

Linking @CodeSwimBikeRunner 's similar question #5279

**Comment by MarkIannucci** [comment]
My workaround has an unfortunate limitation.  Because the [template expressions](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/templates?view=azure-devops#template-expressions) are evaluated early on in the pipeline, you are limited in what variables you can use.  Quoting the documentation:

`you have access to the variables context that contains all the variables specified in the YAML file plus the system variables. Importantly, it doesn't have runtime variables such as those stored on the pipeline or given when you start a run.`

**Comment by vtbassmatt** [comment]
Demands are documented [here](https://docs.microsoft.com/azure/devops/pipelines/process/demands). Existence and equality are the only supported operators. If you want to make a feature request, [Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html) is the best place for that.

**Comment by mark-at-tusksoft** [comment]
@vtbassmatt I think some confusion comes from the phrasing and ordering of information in the docs.

>Some tasks won't run unless one or more demands are met by the agent. For example, the Visual Studio Build task demands that msbuild and visualstudio are installed on the agent.

It doesn't explicitly say 'tasks provide their own demands' and the demands keyword is intended for demands that are not defined by said tasks. That is at least where I was getting confused.

**Comment by ChristoWolf** [comment]
> Demands are documented [here](https://docs.microsoft.com/azure/devops/pipelines/process/demands). Existence and equality are the only supported operators. If you want to make a feature request, [Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html) is the best place for that.

Is this still the case though?
Azure DevOps Server 2020 seems to at least also support `gtVersion`.
