### ISSUE TITLE
az login devops for multi-tenant

### ISSUE THREAD

**Issue by avbhaskar** [MicrosoftDocs/vsts-docs#7176]
**Issue: Azure devops signin issue for dual tenant operations (commercial + government tenants)**

Our azure-devops organization  authenticates using commercial tenant logins. We have azure devops projects that target Azure US Government tenant for deployment.  
Most of the time my azure cli environment is pointing to azure US government. [az cloud set --name AzureUSGovernment].   
**_I cannot sign in to azure devops [az devops login ] while my Azure CLI environment is pointing at government cloud._** 
switching to commercial cloud environment to run az devops commands in commercial and then switch back to government cloud environment  to verify resources is tedious. 
Solution requested : 
**Add optional parameter cloudname** on az devops login, like so:
$az cloud set --name AzureUSGovernment; $az login - u mygovuserid@contoso.us
$az devops login --organization https://dev.azure.com/contoso --Cloudname AzureCloud -u (mycommercialuserid@contoso.com)

**Comment by WilliamAntonRohm** [comment]
Thanks for the suggestion! The product teams aren’t always watching this repository, so to make sure it gets in front of them for triage, please [submit your idea]( https://developercommunity.visualstudio.com/content/idea/post.html?space=21) here.
