### ISSUE TITLE
Is there an easy way to find Azure DevOps organizations connected to my directory?

### ISSUE THREAD

**Issue by vladik-hbinov** [MicrosoftDocs/vsts-docs#7177]
The only way I found to find these organizations including orphaned organizations is to create an organization by myself is to create a new organization in Azure DevOps and go to Setting -&gt; Azure Active Directory and download the csv file of Azure DevOps organizations connected to my directory.
Also, why do I need to be assign the Azure DevOps Administrator role if I'm already have the Global administrator role? I think every Global administrator of a specific Azure Active Directory needs to have full control permissions inside every Azure DevOps organization that is connected to that directory.
If not, maybe give an option to enable it without being assign the Azure DevOps Administrator role like you do for Azure subscriptions with the Access management for Azure resources in the Azure Active Directory properties where you set you can manage access to all Azure subscriptions and management groups in this directory.
Azure DevOps is a resource under the Azure Active Directory...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 378ad220-599b-e802-f084-851277cc208d
* Version Independent ID: 8b041bf4-ec98-78bd-99e1-93e9f11225df
* Content: [Resolve inactive organization owner and project collection administrators - Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/resolve-orphaned-organization?toc=%2Fazure%2Fdevops%2Fsecurity-access-billing%2Ftoc.json&bc=%2Fazure%2Fdevops%2Fsecurity-access-billing%2Fbreadcrumb%2Ftoc.json&view=azure-devops)
* Content Source: [docs/organizations/accounts/resolve-orphaned-organization.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/accounts/resolve-orphaned-organization.md)
* Product: **devops**
* Technology: **devops-accounts**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by vladik-hbinov** [comment]
As I said, I think this config https://docs.microsoft.com/en-us/azure/role-based-access-control/elevate-access-global-admin needs to give me the DevOps Administrator role much like it gives me the User Access Administrator role.

**Comment by WilliamAntonRohm** [comment]
Thanks for the suggestion! The product teams aren’t always watching this repository, so to make sure it gets in front of them for triage, please [submit your idea]( https://developercommunity.visualstudio.com/content/idea/post.html?space=21) here.

**Comment by ztrhgf** [comment]
I am also looking for a programmatic solution to this. Is it possible to get such data without manual download of such csv file?
