### ISSUE TITLE
Your documentation is horribly outdated, please update it

### ISSUE THREAD

**Issue by karelkral** [MicrosoftDocs/vsts-docs#7179]
This documentation is related to 4 years old version of TFS. Documentation of [new UI](https://developer.microsoft.com/en-us/azure-devops/components) is only reference documentation and is completely missing these how-to examples and tutorials.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 91ce0f6c-251b-7a4f-4cd5-7a19410d5a57
* Version Independent ID: f4b2d83d-976e-afcf-69ff-c0c4e6d012cb
* Content: [Samples Overview - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/extend/develop/samples-overview?view=azure-devops#feedback)
* Content Source: [docs/extend/develop/samples-overview.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/extend/develop/samples-overview.md)
* Product: **devops**
* Technology: **devops-ecosystem**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @karelkral, You're so right about that! We'll be assigning a content developer to work with a PM to address these stale articles within the next few months. If you don't see anything soon, feel free to comment on this issue, even if it's closed. Thank you!

**Comment by djeec** [comment]
I'd love to see at least one example of a dashboard widget using showing how `azure-devops-extension-sdk`, `azure-devops-extension-api` and `azure-devops-ui` work together
