### ISSUE TITLE
Email bounce from alias when sending feedback email

### ISSUE THREAD

**Issue by stijnherreman** [MicrosoftDocs/vsts-docs#7183]
When sending email to devops_tools@microsoft.com, it fails to deliver to the sadadirs alias.
This was previously reported in #5825 and (I assume) fixed.

The email is delivered fine, except to the alias. But when sending feedback email for the first time it is confusing and unclear whether the email was delivered at all.

**Comment by steved0x** [comment]
@stijnherreman I have reported that to the team, and have added more detail to the note at the bottom of the page right after the feedback email to try and clarify that even with the bounce message, the email is getting through. I am not sure why it is taking so long for the issue to be resolved, but I can assure you that the feedback is getting through, and I apologize for the confusion (I agree it is very confusing). Thank you.
