### ISSUE TITLE
There is no "Set as default branch" option.

### ISSUE THREAD

**Issue by samrueby** [MicrosoftDocs/vsts-docs#7184]
We are unable to set the default branch. It is currently set to another branch. Even after deleting the default branch, a new branch cannot be specified as default. There is no option in the "..." menu.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c8630b8-08ea-d706-e51c-03863b33d49e
* Version Independent ID: ad8a3b91-7b41-a6af-0d5c-b26355a49c7b
* Content: [Manage branches in your Git repo - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/manage-your-branches?view=azure-devops#change-your-default-branch)
* Content Source: [docs/repos/git/manage-your-branches.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/repos/git/manage-your-branches.md)
* Product: **devops**
* Technology: **devops-code-git**
* GitHub Login: @apawast
* Microsoft Alias: **sdanie**

**Comment by apawast** [comment]
Hi @samrueby, normally the option does not show up if you don't have permission to do this. I believe you need the "Edit Policies" permission to be able to set default branch. Hope that helps, if not we can explore other possible issues.

**Comment by d-vs** [comment]
Leaving this guide here as I've had the same issue and the solution is not only to do with permissions. I cannot find the option to set the default branch in the ellipsis as decribed in the MS documentation, on a repo's branches page. To do this, one has to instead go into:

Project Settings -> Repos -> Repositories

Then, in the Repositories column, expand the repository in question, then expand branches and select the branch you want as the default. Once selected, an ellipsis will appear, and clicking this will give the 'Set as default branch' option.

**Comment by WilliamAntonRohm** [comment]
@d-vs -- thank you for your follow-up and solution.

**Comment by daviburg** [comment]
UX is confusing. It should show the option as gray with a hover-hint why it isn't enabled. I created the repo, I have "Edit Policies" permissions, and yet the option is not showing up. I went to the project settings and don't see an ellipsis there on the branches at all.

**Comment by WilliamAntonRohm** [comment]
@daviburg -- David, thank you for your follow-up.  This seems to be product-related; [please add it here](https://developercommunity.visualstudio.com/search?space=21).

**Comment by daviburg** [comment]
Added here: https://developercommunity.visualstudio.com/t/Do-not-hide-Set-as-default-branch-and/10024185?space=21&q=Set+as+default+branch&entry=suggestion
