### ISSUE TITLE
Restrict modification of work items based on a user or group not implemented

### ISSUE THREAD

**Issue by mekr** [MicrosoftDocs/vsts-docs#7185]
Hi,
Picture related to this topic is the same as the Azure DevOps Services, however, on Azure DevOps Server you can't set up a rule based on user or group as a conditional filter. In this way, this picture is misleading. Rule composition reference shows the correct information. See https://docs.microsoft.com/en-us/azure/devops/organizations/settings/work/custom-rules?view=azure-devops-2019#rule-composition.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b9a3085-d952-f4ba-e7c5-88e8ea7b3b29
* Version Independent ID: fb29b46c-3b07-ec11-f731-78c1371eef33
* Content: [Grant or restrict access to select features - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/security/restrict-access?view=azure-devops-2019#feedback)
* Content Source: [docs/organizations/security/restrict-access.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/security/restrict-access.md)
* Product: **devops**
* Technology: **devops-security**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@mekr - Thank you for the feedback. I am correcting the article as you have noted.
