### ISSUE TITLE
Send ADO Content to separate channels

### ISSUE THREAD

**Issue by KehindeOwens** [MicrosoftDocs/vsts-docs#7186]
Hello,

We'd like to create separate channels for certain ADO actions to go to (Pull Requests would be in one channel and Deployment failures in another for example). However the app only allowed me to choose one channel. Is this capability i'm asking about available? Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 99a6f5aa-7e92-a028-d13e-e1e4b7fede86
* Version Independent ID: be7e5d7c-0033-6b72-4bd1-809f7d1894aa
* Content: [Azure Pipelines with Slack - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/integrations/slack?view=azure-devops)
* Content Source: [docs/pipelines/integrations/slack.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/integrations/slack.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @atinb
* Microsoft Alias: **atinb**

**Comment by RGKarthik** [comment]
Kehin,
Yes, your use case is supported. To get notifications on pull requests, please use Azure Repos App for Slack (https://aka.ms/AzureReposSlackIntegration). Once you install the app in a work space, you can sign in and set up subscriptions to receive notifications about PRs in any channel of your choice. 

Azure Pipelines app for Slack posts notifications related to pipelines and can be used (to know about deployment failures) in any channel of your choice. For both the apps, subscriptions are channel specific. Hence, subscriptions set up in one channel does not affect the subscriptions in another channel.

**Comment by KehindeOwens** [comment]
Thank you very much, I will test this and confirm that it works.
