### ISSUE TITLE
What is --cov=com

### ISSUE THREAD

**Issue by sawatsky** [MicrosoftDocs/vsts-docs#7189]
When I'm running the unit tests, on the step
```
pytest tests --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html
```
I get 
```
Coverage.py warning: Module com was never imported. (module-not-imported)
```

What is `--cov=com`? From research, I believe it's supposed to be a project name, but for me, that's just the root of my repo. If it's the module I'm testing, again that's the root of my repo.

Is this warning the reason no code coverage files are generated?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2ca42420-9324-1988-16bd-501be69e278d
* Version Independent ID: 400c0122-a0cc-bb52-b6cc-8aa93ff2c47a
* Content: [Build and test Python apps - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/ecosystems/python?view=azure-devops)
* Content Source: [docs/pipelines/ecosystems/python.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/ecosystems/python.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @vtbassmatt
* Microsoft Alias: **macoope**

**Comment by vtbassmatt** [comment]
I think [you're right](https://github.com/pytest-dev/pytest-cov/blob/87a11732e76658244ed23d7f38e93adb19c4a795/src/pytest_cov/plugin.py#L71) (I'm a Python expert but not a Pytest guru :grin:). I think you can just leave that out to have it run against everything in your repo.

Would you let me know whether that works? If yes, I'll update the docs.

**Comment by sawatsky** [comment]
@vtbassmatt 
When I just do `--cov=`, it says: `Coverage.py warning: Module  was never imported. (module-not-imported)` (there's a double-space between 'Module' and 'was' as if it's printing out the blank name that I gave it), so that didn't work.

When I get rid of the `--cov=` completely, it doesn't even try to generate the coverage report.

So that parameter is required, but I don't know what to set it to.

**Comment by vtbassmatt** [comment]
Maybe try `--cov=.`? After that, we'll have exhausted my understanding of the area. The pytest-cov docs are also woefully lacking. I know a few people in the Python community to whom we might be able to reach out for help.

**Comment by sawatsky** [comment]
Yes! `--cov=.` worked... code coverage report generated!

Thanks!
