### ISSUE TITLE
Permissions for creating work items?

### ISSUE THREAD

**Issue by dancoupar** [MicrosoftDocs/vsts-docs#7192]
This page talks a lot about "the ability to view, modify, or edit work items" but nowhere does it mention creating work items. I'm  confused by this! I guess this is configured differently, but a link to another page giving more info would have been helpful.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 022fb627-3fc3-e748-8431-a4597bb27ad5
* Version Independent ID: 0b56992a-b121-6095-5a60-65548fdd5a3b
* Content: [Set permissions and access for work tracking - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/security/set-permissions-access-work-tracking?view=azure-devops#feedback)
* Content Source: [docs/organizations/security/set-permissions-access-work-tracking.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/security/set-permissions-access-work-tracking.md)
* Product: **devops**
* Technology: **devops-security**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@dancoupar - Thank you for the feedback.  Most permissions that support editing or modifying work items apply to creating them. However, to avoid further confusion, I'll update the content to be more explicit. There are some places where users don't have full permissions to create a work item based on the page they are on and the access they've been granted.
