### ISSUE TITLE
SECRET_KEY as a variable name

### ISSUE THREAD

**Issue by MasaSip** [MicrosoftDocs/vsts-docs#7194]
I defined a variable "SECRET_KEY" in pipelines -> variables UI and imported it in YML-file:

```
env:
    SECRET_KEY: $(SECRET_KEY)
```
however, when accessing it within Django settings.py, I was not able to refer to it. However, if the variable was renamed to DJANGO_SECRET_KEY, it worked. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd7e0bd3-1f7d-d7b6-cc72-5ef63c31b46a
* Version Independent ID: dae87abd-b73d-9120-bcdb-6097d4b40f2a
* Content: [Variables - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch)
* Content Source: [docs/pipelines/process/variables.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/variables.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by WilliamAntonRohm** [comment]
It looks like you've encountered an issue with the product itself, rather than an issue with the documentation. To make sure it gets in front of the right people, please [submit your bug]( https://developercommunity.visualstudio.com/content/problem/post.html?space=21) here.
