### ISSUE TITLE
Slight inaccuracy in the Project-level groups section

### ISSUE THREAD

**Issue by dancoupar** [MicrosoftDocs/vsts-docs#7196]
Under the section for "Project-level groups", the description for the Project Valid Users group includes the following:

"If you set the View collection-level information permission to Deny or Not set for this group, no users will be able to access the project."

I think this should read: "If you set the View project-level information..." Also, this is not true of Project Collection Admins, who can do anything regardless of permissions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 68686c2b-c69a-d9e4-3e21-a46d231b649c
* Version Independent ID: 049659da-1772-3166-f909-4feeb8a97730
* Content: [What are all the default permissions and groups? - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/security/permissions?view=azure-devops&tabs=preview-page)
* Content Source: [docs/organizations/security/permissions.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/security/permissions.md)
* Product: **devops**
* Technology: **devops-security**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@dancoupar - Thank you for the feedback. I will update the topic.
