### ISSUE TITLE
This is written as if its a live feature and not a preview

### ISSUE THREAD

**Issue by StingyJack** [MicrosoftDocs/vsts-docs#7208]
yet there is still a toggle to enable this. Which is it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e013ceb-c5eb-6fc8-9842-708e669bd4ce
* Version Independent ID: b9bc3c0e-85e5-1318-374b-fe1cd3354152
* Content: [Multi-stage pipelines user experience - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/get-started/multi-stage-pipelines-experience?view=azure-devops)
* Content Source: [docs/pipelines/get-started/multi-stage-pipelines-experience.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/get-started/multi-stage-pipelines-experience.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
@StingyJack Let me find out,  when I check my various organizations I see this on some:
![image](https://user-images.githubusercontent.com/1580889/74743812-122b7580-522f-11ea-8ca3-278686f05be4.png)

and I see this in others:
![image](https://user-images.githubusercontent.com/1580889/74743839-1eafce00-522f-11ea-9b1d-61ae76ade436.png)

I will report back with more info shortly.

**Comment by steved0x** [comment]
@StingyJack It is live and should be fully rolled out soon, and that toggle will go away shortly.

**Comment by StingyJack** [comment]
Great...  [hopefully the product team got it together and didnt forget to fix these things](https://developercommunity.visualstudio.com/content/problem/724885/i-cant-turn-off-the-new-build-results-page.html).
