### ISSUE TITLE
Clicking the .Net Core CLI build task gives me a 404

### ISSUE THREAD

**Issue by tristanbarcelon** [MicrosoftDocs/vsts-docs#721]
The link to .Net Core CLI build task points to a link https://github.com/Microsoft/vsts-tasks/tree/master/Tasks/DotNetCoreCLI which does not exist. Should it be https://github.com/Microsoft/vsts-tasks/tree/master/Tasks/DotNetCoreCLIV2 instead?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e7ba5cf3-d229-03d0-ad6a-a30a0379afc0
* Version Independent ID: ccffed3b-ea44-517f-f7a8-a1c4c4147495
* Content: [Catalog of the built-in tasks for build-release and VSTS & TFS](https://docs.microsoft.com/en-us/vsts/build-release/tasks/?view=vsts#feedback)
* Content Source: [docs/build-release/tasks/index.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/build-release/tasks/index.md)
* Service: **unspecified**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by alexhomer1** [comment]
Thank you for your feedback. I just checked and the links now go to https://docs.microsoft.com/en-us/vsts/build-release/tasks/build/dotnetcorecliv2.2 which describes the task. I assume the page was recently updated.
