### ISSUE TITLE
Function skipped()

### ISSUE THREAD

**Issue by M0ns1gn0r** [MicrosoftDocs/vsts-docs#7212]
The section "Job status check functions" doesn't list the function `skipped()`, although the corresponding state does exist. Is this a documentation or an implementation gap?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77c58a78-a567-e99a-9eb7-62dddd1b90b6
* Version Independent ID: 680a79bc-11de-39fc-43e3-e07dc762db18
* Content: [Expressions - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/expressions?view=azure-devops#dependencies)
* Content Source: [docs/pipelines/process/expressions.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/expressions.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by juliakm** [comment]
Thanks for your question. I checked with the product team and we do not have an implementation available for `skipped()`. The status exists but not as a job status check function.
