### ISSUE TITLE
SQL is incorrect in ISVError:300005 

### ISSUE THREAD

**Issue by SamGrantham** [MicrosoftDocs/vsts-docs#7216]
https://docs.microsoft.com/en-us/azure/devops/migrate/migration-troubleshooting?view=azure-devops#isverror-300005

The SQL that is given to update the group memberships is:

>DECLARE @p6 dbo.typ_GroupMembershipTable
>INSERT into @p6 values('S-1-9-1551374245-3746625149-2333054533-2458719197-2313548623-0-0-0-0-3','Microsoft.TeamFoundation.Identity','76050ddf-4fd8-48c4-a1ff-859e44364519',0)
>EXEC prc_UpdateGroupMembership @partitionId=1,@scopeId='7df650df-0f8b-4596-928d-13dd89e5f34f',@idempotent=1,@incremental=1,@insertInactiveUpdates=0,@updates=@p6,@eventAuthor='9EE20697-5343-43FC-8FC5-3D5D455D21C5',@updateGroupAudit=0

but the definition of the stored Proc in the current version is:
>CREATE PROCEDURE [dbo].[prc_UpdateGroupMembership]
>    @partitionId                    INT,
>    @scopeId                        UNIQUEIDENTIFIER,
>    @idempotent                     BIT,
>    @incremental                    BIT,
>    @insertInactiveUpdates          BIT,
>    @updates                        typ_GroupMembershipTable READONLY,
>    @eventAuthor                    UNIQUEIDENTIFIER

It appears that we need to remove the final Parameter from the guidance to be comparable with the versions in play at this time:

>DECLARE @p6 dbo.typ_GroupMembershipTable
>INSERT into @p6 values('S-1-9-1551374245-3746625149-2333054533-2458719197-2313548623-0-0-0-0-3','Microsoft.TeamFoundation.Identity','76050ddf-4fd8-48c4-a1ff-859e44364519',0)
>EXEC prc_UpdateGroupMembership @partitionId=1,@scopeId='7df650df-0f8b-4596-928d-13dd89e5f34f',@idempotent=1,@incremental=1,@insertInactiveUpdates=0,@updates=@p6,@eventAuthor='9EE20697-5343-43FC-8FC5-3D5D455D21C5'

(as well as in the generic version of the script)

Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bff3fd07-3d7b-1244-88e4-c2cfbb3fa204
* Version Independent ID: 63f4392f-2dc6-4620-a24f-c02070dd7115
* Content: [Troubleshoot migration import to Azure DevOps Services - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/migrate/migration-troubleshooting?view=azure-devops#isverror-300005)
* Content Source: [docs/migrate/migration-troubleshooting.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/migrate/migration-troubleshooting.md)
* Product: **devops**
* Technology: **devops-migrate**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by WilliamAntonRohm** [comment]
@KathrynEE -- please review the above-mentioned PR 951.
