### ISSUE TITLE
Can I link to other work item in hyperlink template

### ISSUE THREAD

**Issue by Nhattd97** [MicrosoftDocs/vsts-docs#7223]
I'm using this `https://dev.azure.com/{OrganizationName}/{ProjectName}/_workItems/create/Task?
[System.Title]=TaskTitle&
[System.AssignedTo]=Jamal+Hartnett` to create a work item template. How I can link to other work item (parent) in that hyperlink.
Thank you!

**Comment by WilliamAntonRohm** [comment]
@Nhattd97 -- Nhat, thanks for your feedback; we appreciate it. To make sure we have all the information needed to triage your issue, please let us know which topic you’re referencing, or provide more context around the general task.

**Comment by Nhattd97** [comment]
I'm following **Define an ad hoc work item template using a hyperlink** (https://docs.microsoft.com/en-us/azure/devops/boards/backlogs/work-item-template?view=azure-devops&tabs=browser#define-an-ad-hoc-work-item-template-using-a-hyperlink). I'm looking forward to linking a parent work item in the hyperlink.

**Comment by Nhattd97** [comment]
Are you need any further pieces of information? @WilliamAntonRohm

**Comment by KathrynEE** [comment]
@@Nhattd97 - Thank you for your inquiry. The ability to create an adhoc URL that creates a work item linked to another work item isn't a supported feature. Please review the following Q&A for more information: https://review.docs.microsoft.com/en-us/azure/devops/boards/faqs?view=azure-devops&branch=pr-en-us-1060#q-can-i-create-a-work-item-template-that-creates-links-to-other-work-items.
