### ISSUE TITLE
Feature availability - triggers

### ISSUE THREAD

**Issue by ciufudean** [MicrosoftDocs/vsts-docs#7224]
Re feature availability, only YAML pipelines allow triggers defined in cron syntax

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f94a6e7d-3cb5-790c-2b8b-c09abd1de3f6
* Version Independent ID: a0d381e1-07ad-9191-4697-6faf600a7bd8
* Content: [Use Azure Pipelines - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/get-started/pipelines-get-started?view=azure-devops&tabs=classic)
* Content Source: [docs/pipelines/get-started/pipelines-get-started.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/get-started/pipelines-get-started.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by WilliamAntonRohm** [comment]
@ciufudean -- thank you for your feedback.  Please clarify the nature of your question or issue.
