### ISSUE TITLE
Vsts name is deprecated

### ISSUE THREAD

**Issue by estensen** [MicrosoftDocs/vsts-docs#7229]
Replace Vsts with Azure Devops

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0fa37a3f-6551-16ad-e164-a4ac522cdaab
* Version Independent ID: a3fd6935-2b99-92ef-4eb3-3249fca01f8a
* Content: [NuGet restore, pack, and publish task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/package/nuget?view=azure-devops)
* Content Source: [docs/pipelines/tasks/package/nuget.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/package/nuget.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @chasewilson
* Microsoft Alias: **phwilson**

**Comment by WilliamAntonRohm** [comment]
@estensen -- Håvard, do you mean these two instances?

vstsFeed
Use packages from this Azure Artifacts/TFS feed.
- Include the selected feed in the generated NuGet.config. You must have Azure Artifacts installed and licensed to select a feed here.


publishVstsFeed
Target feed
- Select a feed hosted in this account.  You must have Azure Artifacts installed and licensed to select a feed here.

**Comment by estensen** [comment]
I think the vsts name should be avoided as it confuses user's who started using the product after it was renamed to Azure DevOps

**Comment by WilliamAntonRohm** [comment]
@estensen -- Håvard, thanks for the suggestion! The product teams aren’t always watching this repository, so to make sure it gets in front of them for triage, please [submit your idea]( https://developercommunity.visualstudio.com/content/idea/post.html?space=21) here.

**Comment by estensen** [comment]
I don't understand why this is closed. Why is it linked in the docs that you can submit feedback in this Github repo if you later have to create an issue in another system? I like the feedback section of the docs because it's easy to see problems others are having.
