### ISSUE TITLE
Next Iteration

### ISSUE THREAD

**Issue by EldarAliev** [MicrosoftDocs/vsts-docs#7233]
Is it possible to plan for product development to be able to add @NextIteration ?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5430ccc7-e8ea-d02d-b2e9-33b8138338da
* Version Independent ID: 0c0b7f9a-69fe-3edf-6216-a4784d4cb94b
* Content: [View and configure sprint burndown - Azure DevOps](https://docs.microsoft.com/en-gb/azure/devops/report/dashboards/configure-sprint-burndown?view=azure-devops&tabs=remaining-work%2Cmay&source=docs#feedback)
* Content Source: [docs/report/dashboards/configure-sprint-burndown.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/report/dashboards/configure-sprint-burndown.md)
* Product: **devops**
* Technology: **devops-analytics**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by WilliamAntonRohm** [comment]
Thanks for the suggestion! The product teams aren’t always watching this repository, so to make sure it gets in front of them for triage, please [submit your idea]( https://developercommunity.visualstudio.com/content/idea/post.html?space=21) here.
