### ISSUE TITLE
Latest available version of PowerShell Modules

### ISSUE THREAD

**Issue by BrandonWhite-Altius** [MicrosoftDocs/vsts-docs#7237]
There is a noticeable misalignment between the latest version of a PowerShell module (e.g Az 3.4.0) and the latest supported version by the release pipeline task, 4.* and 5.* (preview) both only support up to Az 3.1.0.

Please can the pipeline task be updated to support the latest module versions, as in this case it is currently 3 releases behind?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fb215324-b1a0-93b5-5022-4bcc7da93bb7
* Version Independent ID: 9eb2977b-ac34-9d53-670e-04fa027bc8e4
* Content: [Azure PowerShell task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-powershell?view=azure-devops#feedback)
* Content Source: [docs/pipelines/tasks/deploy/azure-powershell.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/deploy/azure-powershell.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by RoopeshNair** [comment]
We don't automatically update the agent images with latest versions in case of Azure PowerShell module. It takes several weeks for us to ensure that there are no compatibility issues and rollout the updated images. If you need latest, as a workaround, you can use self-hosted agents. 

Current ETA is ~2 months for the revision.
