### ISSUE TITLE
Special character are ignored

### ISSUE THREAD

**Issue by daviburg** [MicrosoftDocs/vsts-docs#724]
I needed to do a count of 

package id="Newtonsoft.Json" version="6 

vs 

package id="Newtonsoft.Json" version="10

Which can be done by removing the original double quotes and wrapping the result in double quote as "special" character are ignored, which i think is anything not alphanumerical.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 071837d4-ee58-9e91-3037-4e83608ee376
* Version Independent ID: bf4f3524-4b1d-e4b4-a0b8-ff703d2da0ab
* Content: [Advanced search options in Microsoft Code Search in VS VSTS and TFS](https://docs.microsoft.com/en-us/vsts/search/code/advanced-search?view=vsts#syntaxdetails)
* Content Source: [docs/search/code/advanced-search.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/search/code/advanced-search.md)
* Service: **unspecified**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment]
Thank you for your feedback. I have passed this on to the product team for their advice.

**Comment by alexhomer1** [comment]
I have updated the topic to include the new syntax and search capabilities for special characters and phrases:
https://docs.microsoft.com/en-us/vsts/search/code/advanced-search?view=vsts#syntax-for-simple-and-compound-searches
https://docs.microsoft.com/en-us/vsts/search/code/advanced-search?view=vsts#search-for-phrases
This should help to answer your question.
