### ISSUE TITLE
Directions not correct

### ISSUE THREAD

**Issue by FISHMANPET** [MicrosoftDocs/vsts-docs#7240]
Either these instructions were vauge and wrong to begin with, or the process has changed since this document was created, but it appears the process for this has now changed.

After granting an account Azure DevOps Administrator, they will need to navigate to the URL of the orphaned organization (it won't show up in the list of organizations as the screenshot implies).  You'll get what looks like a normal "permission denied" error screen, but instead of a button to request access from the owner, the button will say Claim Ownership, at which point you can claim ownership of the project.

These directions and screenshots imply that the orphaned org will be visible along with all your other organizations and you can view it from there, but that's not the case/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 378ad220-599b-e802-f084-851277cc208d
* Version Independent ID: 8b041bf4-ec98-78bd-99e1-93e9f11225df
* Content: [Resolve inactive organization owner and project collection administrators - Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/resolve-orphaned-organization?toc=%2Fazure%2Fdevops%2Forganizations%2Ftoc.json&bc=%2Fazure%2Fdevops%2Forganizations%2Fbreadcrumb%2Ftoc.json&view=azure-devops)
* Content Source: [docs/organizations/accounts/resolve-orphaned-organization.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/accounts/resolve-orphaned-organization.md)
* Product: **devops**
* Technology: **devops-accounts**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @FISHMANPET, Thanks for your feedback. I've created a user story for updating this doc and am currently researching. I'll let you know once it has been published. Thanks again!

**Comment by chcomley** [comment]
I've just published the article, which should be live within an hour (it's 8:21am PST). Please @ mention me if you continue to experience difficulties. Thanks so much.
