### ISSUE TITLE
How do Azure Resource Manager service connections work with automatic secret rotation?

### ISSUE THREAD

**Issue by ynambiar** [MicrosoftDocs/vsts-docs#7241]
Our team is trying to automate secret rotation for our service principals. Is there a way to create a Service Connection that automatically updates/rotates the secret when we rotate the service principal secret from our end?

Thanks!
Yamini

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5093b8d4-43df-12c3-591d-43e174e630cd
* Version Independent ID: 4a9bf702-1b28-33ef-9a26-fcf9dadaa7c2
* Content: [Troubleshoot Azure Resource Manager service connections - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/azure-rm-endpoint?view=azure-devops#feedback)
* Content Source: [docs/pipelines/release/azure-rm-endpoint.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/release/azure-rm-endpoint.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by RoopeshNair** [comment]
No, it is not supported. You'll have manually update the service connection or use REST APIs to automate updating service connection with the new keys

**Comment by iamthemoon-git** [comment]
Hi Yamni

We are trying to do the smae thing, did you manage to com up with a solutuon?

**Comment by ynambiar** [comment]
@iamthemoon-git no, we ended up manually updating our service connections.
