### ISSUE TITLE
Unable to view more than 125 test cases in a single suite.

### ISSUE THREAD

**Issue by sulu99** [MicrosoftDocs/vsts-docs#7243]
Despite adding more than 125 test cases in a suite, the Web Portal will only display 125 and no more, no matter how many times you try to add the case(s).

**Comment by WilliamAntonRohm** [comment]
@sulu99 -- thanks for your feedback; we appreciate it. To make sure we have all the information needed to triage your issue, please let us know which topic you’re referencing, or provide more context around the general task.
