### ISSUE TITLE
Not able to configure package resources

### ISSUE THREAD

**Issue by Adamsimsy** [MicrosoftDocs/vsts-docs#7247]
Although mentioned in the schema at the top of this page, there is no section that desribes how to configure packages.

I followed other documentation available here:
https://github.com/microsoft/azure-pipelines-yaml/blob/master/design/pipeline-resources.md

However when i try this, i get the following error:
'Unexpected property packages'

Is this not supported yet in production? 

I'm trying to trigger a CD pipeline in Azure DevOps Services that runs when a new version of a Universial Package is created in an Azure DevOps Artifact Feed.

We can get this to work with a Pipeline Artfact produced by a CI Pipeline resource. However would like to keep the Artifact off of the pipeline build in a Feed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee4ec9d0-e0d5-4fb4-7c3e-b84abfa290c2
* Version Independent ID: 3e2b80d9-30e5-0c48-49f0-4fcdfedf5eee
* Content: [Resources - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/resources?view=azure-devops&tabs=schema#feedback)
* Content Source: [docs/pipelines/process/resources.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/resources.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by Adamsimsy** [comment]
Hi there. I can see this is tagged as a documentation bug. Does this mean it is or isn't possible? Just wondering as my team will use Pipeline Builds as triggers and their artifacts instead of a Package trigger if this isn't available at this time. Thanks.

**Comment by juliakm** [comment]
@Adamsimsy It sounds like you are running into a possible issue with the product and not necessarily the docs. Please reach out to the [Azure DevOps Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html). That site is monitored by the product team and should be a good resource for getting to the bottom of this.  If it turns out that this is a documentation issues, please let us know!

**Comment by Adamsimsy** [comment]
Hi @juliakm i posted there and confirm it doesn't work and the team will look at getting this work. Not sure if it is worth updating the documentation to avoid any confusion for others trying to use this feature now before it is ready.
