### ISSUE TITLE
Restricting System.State doesn't work for non-custom work item types

### ISSUE THREAD

**Issue by MatthewDiPietroTR** [MicrosoftDocs/vsts-docs#7256]
The documentation indicates that restrictions can be placed on who can create specific work item types such as Epics and Features, but this does not seem to work for built-in types. The system errors when doing this for a built-in WIT indicating that the ReadOnly rule conflicts with the Required rule and won't allow the custom rule to be saved.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4107b23a-ba0a-5a1b-b689-072717cfe8ec
* Version Independent ID: 1ed09ce9-be9b-6146-9cb8-a2a50e12a3c2
* Content: [Add a custom rule to a work item type - Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/organizations/settings/work/custom-rules?view=azure-devops#feedback)
* Content Source: [docs/organizations/settings/work/custom-rules.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/settings/work/custom-rules.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by MatthewDiPietroTR** [comment]
The specific error is "VS1640115: The action ReadOnly cannot be used with the action Required when applied to the same field under the same conditions."

There doesn't seem to be any way to make System.State not Required for built-in WIT, so making it ReadOnly wouldn't be an option.

**Comment by KathrynEE** [comment]
@MatthewDiPietroTR - Thank you for the feedback. You are correct. I will update the article to reflect that the rule only works on custom work item types.
