### ISSUE TITLE
Are variable groups supported in builds?

### ISSUE THREAD

**Issue by iosgitr** [MicrosoftDocs/vsts-docs#726]
The top of the document states "available across multiple build and release definitions" but this document only describes how to use a variable group within a release definition.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4827aa99-ae62-bd63-6f2f-a87a4065ed27
* Version Independent ID: c9e461ee-7f42-3503-9460-18fa3a807bbb
* Content: [Variable groups for VSTS and TFS](https://docs.microsoft.com/en-us/vsts/build-release/concepts/library/variable-groups?view=vsts)
* Content Source: [docs/build-release/concepts/library/variable-groups.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/build-release/concepts/library/variable-groups.md)
* Service: **unspecified**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment]
Thank you for your feedback. I will ask the product team for advice and update the topic accordingly.
