### ISSUE TITLE
404 page link

### ISSUE THREAD

**Issue by michaelpimentel** [MicrosoftDocs/vsts-docs#727]
The link in "Read more about the Continuous Delivery capabilities of Visual Studio Team Services." show 404 page not found.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 895ed016-6ddc-3458-db9e-ebbedf218982
* Version Independent ID: 36e017f5-b012-fcec-6906-1966f3a97cb4
* Content: [What is Continuous Delivery? - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/what-is-continuous-delivery)
* Content Source: [https://mseng.visualstudio.com/DefaultCollection/TechnicalContent/_git/devops-learn-pr?path=%2fdocs%2fwhat-is-continuous-delivery.md&version=GBlive&_a=contents](https://mseng.visualstudio.com/DefaultCollection/TechnicalContent/_git/devops-learn-pr?path=%2fdocs%2fwhat-is-continuous-delivery.md&version=GBlive&_a=contents)
* Service: **unspecified**
* GitHub Login: @samgu
* Microsoft Alias: **samgu**

**Comment by thomps23** [comment]
Confirmed that link was fixed. Closing out.
