### ISSUE TITLE
Wrong defaults for workingFolder

### ISSUE THREAD

**Issue by FixRM** [MicrosoftDocs/vsts-docs#7273]
It's said that workingFolder parameter defaults to the folder where the script is located but it not so. I have script that use related paths. It is not working as expected if workingFolder parameter is not set this way:

- task: BatchScript@1
  displayName: 'Run spkl pack'
  inputs:
    filename: 'Solutions/spkl/pack.bat'
    workingFolder: 'Solutions/spkl'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 96dafbb6-b4ba-d4ab-7468-55e6df71b5e1
* Version Independent ID: 634b0719-9641-59fd-9f6f-f3a2082f9b39
* Content: [Batch Script task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/batch-script?view=azure-devops#arguments)
* Content Source: [docs/pipelines/tasks/utility/batch-script.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/utility/batch-script.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @vtbassmatt
* Microsoft Alias: **macoope**

**Comment by FixRM** [comment]
What?

**Comment by vtbassmatt** [comment]
We have a separate internal repo where we make docs changes. Here's what I see in this thread:
<img width="692" alt="image" src="https://user-images.githubusercontent.com/714283/74753298-ed8aca00-523d-11ea-99f1-7893539deb76.png">
