### ISSUE TITLE
Task description in doc doesn't match description in code

### ISSUE THREAD

**Issue by dylandragon93** [MicrosoftDocs/vsts-docs#7279]
In this doc the task is listed as:

> Use this task in a build or release pipeline to run a program from the command prompt.

But in the task [code](https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/CmdLineV2/Strings/resources.resjson/en-US/resources.resjson#L4) the description is:

> Run a command line script using Bash on Linux and macOS and cmd.exe on Windows

These should be synced to whichever description is more accurate.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a79d17fd-6e65-d8f0-ea05-f62d68456474
* Version Independent ID: 3f7338a7-aae7-b6b6-3291-5c985c6fa6f3
* Content: [Command Line task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/command-line?view=azure-devops&tabs=yaml#feedback)
* Content Source: [docs/pipelines/tasks/utility/command-line.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/utility/command-line.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @vtbassmatt
* Microsoft Alias: **macoope**

**Comment by vtbassmatt** [comment]
Low priority, they're both accurate.

**Comment by dylandragon93** [comment]
I would argue that the doc description is not accurate since it doesn't mention anything about Bash and makes it sound like you can only use cmd.
