### ISSUE TITLE
Visual Studio for Mac setup

### ISSUE THREAD

**Issue by albilaga** [MicrosoftDocs/vsts-docs#729]
It will be good if there is also setup for Visual Studio for mac  like solution configurations because it is different with Visual Studio On Windows

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c45a95ce-73c8-861e-f92d-a26f1667aa60
* Version Independent ID: ecb82128-cdf4-3834-62c1-2cf61989ab5e
* Content: [Build your Xamarin app](https://docs.microsoft.com/en-us/vsts/build-release/apps/mobile/xamarin?view=vsts&tabs=vsts)
* Content Source: [docs/build-release/apps/mobile/xamarin.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/build-release/apps/mobile/xamarin.md)
* Service: **unspecified**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by DavidStaheli** [comment]
Hi @albilaga.  Apologies that it took so long to reply to you, but the work has been done.  Thank you for this suggestion!
