### ISSUE TITLE
Azure DevOps Server 2019 needs a note for IE compatibility.

### ISSUE THREAD

**Issue by SamGrantham** [MicrosoftDocs/vsts-docs#7290]
The ability to use Themes is NOT compatible with Internet Explorer (and never has been), if you are using IE you will not see the themes option in the menu, this should be in a note or an FAQ to avoid confusion.

Please see Chrome VS IE behavior:

![chromeVSIE](https://user-images.githubusercontent.com/36972300/74547451-bfda1400-4f11-11ea-9265-4dfe65a45339.gif)
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d28a6661-50d4-527e-9727-ab5974da951d
* Version Independent ID: fdac329a-b9b4-77d0-916a-dee6d2576379
* Content: [View, change user preferences - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/settings/set-your-preferences?view=azure-devops-2019&tabs=preview-page#change-profile-settings)
* Content Source: [docs/organizations/settings/set-your-preferences.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/settings/set-your-preferences.md)
* Product: **devops**
* Technology: **devops-settings**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
@SamGrantham, Thanks so much for making us aware of this. I've just published an update that includes the note that you spoke of, which should be live momentarily. Thanks again!

**Comment by chcomley** [comment]
Actually, @SamGrantham, I don't believe that this is true. What version of IE are you using? We were able to change the theme in Azure DevOps Server 2019 while on IE 11...please let me know
