### ISSUE TITLE
Agent.BuildDirectory and Pipeline.Workspace seem synonymous but not sure

### ISSUE THREAD

**Issue by niander** [MicrosoftDocs/vsts-docs#7298]
The example for both Agent.BuildDirectory and Pipeline.Workspace is the same. However, there is no indication if these variables are synonymous or not. Please be more clear here. Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ffebdc8-521c-44b5-cde4-4abdc1bd6f18
* Version Independent ID: dc0effda-6d93-62aa-64c5-4e6f283b0826
* Content: [Predefined variables - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml#feedback)
* Content Source: [docs/pipelines/build/variables.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/build/variables.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by juliakm** [comment]
@niander These two variables will have the same value. I will update the doc to make this clear.
