### ISSUE TITLE
Projects with spaces in their name

### ISSUE THREAD

**Issue by mbrancato** [MicrosoftDocs/vsts-docs#7301]
In addition to the naming issue from #6729, the other problem is many projects have mixed-case naming and spaces.

`go get` does not support spaces, the percent sign, or capital letters. The paths for Azure DevOps seem to be case-insensitive, as a workaround. Is there some plan to translate these repos in a reliable manner?

As a work around: the following must be done currently:

- set GOPRIVATE to dev.azure.com/organization or similar
- Alias the url base with spaces to the same URL, lower-cased, with spaces replaced by `_` - use the `insteadOf` config for this
- perform `go get` with the new, valid alias.

e.g.
```
go get -v dev.azure.com/{{org}}/{{project}}/_git/{{repo}}.git/{{optional folder}}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 069d650f-9948-2492-86d2-a5423ce043fb
* Version Independent ID: 9c95f2fb-44be-5dbb-be51-0c498ed692d2
* Content: [Go get support - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/go-get?view=azure-devops)
* Content Source: [docs/repos/git/go-get.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/repos/git/go-get.md)
* Product: **devops**
* Technology: **devops-code-git**
* GitHub Login: @apawast
* Microsoft Alias: **sdanie**

**Comment by WilliamAntonRohm** [comment]
It looks like you've encountered an issue with the product itself, rather than an issue with the documentation. To make sure it gets in front of the right people, please [submit your bug]( https://developercommunity.visualstudio.com/content/problem/post.html?space=21) here.
