### ISSUE TITLE
iOS automatic code signing

### ISSUE THREAD

**Issue by sam-moshenko** [MicrosoftDocs/vsts-docs#7302]
Automatic signing works good on my computer, but it does not on azure pipelines. 
The error is:
`error: No profiles for *** were found: Xcode couldn't find any iOS App Development provisioning profiles matching ***. Automatic signing is disabled and unable to generate a profile. To enable automatic signing, pass -allowProvisioningUpdates to xcodebuild. (in target *** from project ***)`

Enabling -allowProvisioningUpdates says that it needs apple id profile. But as I know there is no way to specify it.

There is also an option in the xcode task for signing automatically, what is the point of it?

So is it possible to automatically sign ios app in azure? If not it should be specified in the document, and the automatic signing option should be removed from the task.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3e66a70d-e359-9d0a-0143-a9e43b263795
* Version Independent ID: 7b320a02-0a63-947a-3017-4826ab461112
* Content: [Sign Your Mobile App During CI - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/apps/mobile/app-signing?view=azure-devops&tabs=apple-install-during-build)
* Content Source: [docs/pipelines/apps/mobile/app-signing.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/apps/mobile/app-signing.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by juliakm** [comment]
It sounds like you are running into a possible issue with the product and not necessarily the docs. Please reach out to the [Azure DevOps Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html). That site is monitored by the product team and should be a good resource for getting to the bottom of this.

**Comment by evanjd** [comment]
I struggled with this too! What I was able to work out was this: you _can_ use automatic signing in a DevOps pipeline, but it requires you to extract the automatically generated provisioning profiles from your local Xcode, upload them to secure files (or wherever else you prefer), and then use the Install Provisioning Profile task to install them. You'll also need to install the signing certificate that those profiles are using.

This only works for development builds. AFAIK, you cannot use auto signing in a DevOps pipeline for distribution (ad hoc, app store, etc).

In my case, I was able to use auto signing to build the app for XCUI tests on the App Center. I still use manual signing for adhoc + app store distribution pipelines.

I definitely think the docs could be updated to make this clearer.

**Comment by nadafsak** [comment]
> In my case, I was able to use auto signing to build the app for XCUI testing on App Center. I still use manual signing for adhoc + app store distribution pipelines.

This was exactly the solution for me. The documentation doesn't really talk about this as I suppose it assumes familiarity with how signing works at a lower level.

Next challenge for me is stopping it to try sign my Cocoapod frameworks and then failing the build!

**Comment by vassily-fr** [comment]
well that's desapointing to be limited to developpement signin. 
The main porpose of doing CI is to facilitate the app distribution...

@nadafsak  for your cocoapods you have to add this in your pod file : 

`post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      # Inherit the deployment target defined in this Podfile instead, e.g. platform :ios, '11.0' at the top of this file
      config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
      config.build_settings['CODE_SIGNING_REQUIRED'] = "NO" # for Azure Pipeline
      config.build_settings['CODE_SIGNING_ALLOWED'] = "NO" # for Azure Pipeline
     end
  end
end`
