### ISSUE TITLE
Values Need to Be In Quotes

### ISSUE THREAD

**Issue by wgriffin13** [MicrosoftDocs/vsts-docs#7303]
Using app settings and pipeline variables, the values need to be in quotes.  For example, "value": "$(key)"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f4a09e1d-5fe6-cac3-47c9-cb2f4422a473
* Version Independent ID: 4cf6d896-5421-d32f-5fca-90134ddcdfa1
* Content: [Azure App Service Settings task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-app-service-settings?view=azure-devops)
* Content Source: [docs/pipelines/tasks/deploy/azure-app-service-settings.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/deploy/azure-app-service-settings.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @N-Usha
* Microsoft Alias: **ushan**

**Comment by WilliamAntonRohm** [comment]
@wgriffin13 -- thank you for your feedback.

@N-Usha -- please review the above-mentioned PR 990.

**Comment by WilliamAntonRohm** [comment]
@mijacobs -- please review [PR 990](https://github.com/MicrosoftDocs/azure-devops-docs-pr/pull/990).
