### ISSUE TITLE
Does the CONTAINS operator for Identity field types work like an INCLUDE list for SQL?

### ISSUE THREAD

**Issue by StingyJack** [MicrosoftDocs/vsts-docs#7307]
So using the WorkItemLinks query above, if I wanted to constrain the results to only report when the [child workitem ids](https://docs.microsoft.com/en-us/azure/devops/boards/queries/wiql-syntax?view=azure-devops#operators) are either 22, 33, or 44, would the query look like this?

```
SELECT [System.Id]
FROM WorkItemLinks
WHERE ([Source].[System.WorkItemType] = 'User Story')
  AND ([System.Links.LinkType] = 'Child')
  AND ([Target].[System.State] = 'Active')
  AND ([Target].[System.Id] CONTAINS 22 ,33, 44)
MODE (MustContain)
```

Because I get this error 
```
'Operator CONTAINS can be used with string type fields only. The error is caused by «Target.[System.Id] contains 22».'
```

After linking that operators section above I realized that the IN operator was part of the list of allowed operators for the Identity type fields.  Using that does work like a SQL include and works for what I needed, but I'm still curios about the syntax for using CONTAINS with an Identity field.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 710af5f2-8a31-e0d3-4f20-00c79dc54713
* Version Independent ID: 1d4d9580-984c-9fee-861a-a02ce828d3db
* Content: [WIQL reference syntax - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/queries/wiql-syntax?view=azure-devops#linked-work-items)
* Content Source: [docs/boards/queries/wiql-syntax.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/boards/queries/wiql-syntax.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by kunalranglani** [comment]
You need to use IN operator. Contains is used for matching strings only

You query would look like this

```
SELECT
    [System.Id]
FROM workitemLinks
WHERE
    (
        [Source].[System.WorkItemType] = 'User Story'
    )
    AND (
        [System.Links.LinkType] = 'Child'
    )
    AND (
        [Target].[System.State] = 'Active'
    )
    AND (
        [Target].[System.Id] IN (22, 33, 44)
    )
```

**Comment by StingyJack** [comment]
@kunalranglani - yes, I did figure that out. Thank you for offering the help.

**Comment by StingyJack** [comment]
@KathrynEE - there is still a problem or something missing from the docs in regards to the CONTAINS operator being used for `identity` types
