### ISSUE TITLE
How can i get build definition guid for badge url?

### ISSUE THREAD

**Issue by Soarc** [MicrosoftDocs/vsts-docs#731]
Build status url requires {guid} parameter. Where is it located?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 75a10513-2af9-8e16-61a4-25d4b09f6d32
* Version Independent ID: 788acaa2-d5a1-1d0d-18f4-e94a4e2fe2c9
* Content: [Define a CI build process for your GitHub repository](https://docs.microsoft.com/en-us/vsts/build-release/actions/ci-build-github?view=vsts#create-a-vsts-build-status-with-a-github-readme-file)
* Content Source: [docs/build-release/actions/ci-build-github.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/build-release/actions/ci-build-github.md)
* Service: **vsts**
* GitHub Login: @mlearned
* Microsoft Alias: **mlearned**

**Comment by mlearned** [comment]
@Soarc its from step 13 (per the article) when you enable the option, you get the guid as part of the URL.  Does the below make sense?

![image](https://user-images.githubusercontent.com/17324782/41661631-c2b9bc40-7464-11e8-938d-f4acbf981291.png)


![image](https://user-images.githubusercontent.com/17324782/41661503-89c33cae-7464-11e8-990a-bb4ae3a2788e.png)

**Comment by Soarc** [comment]
I'm using [YAML builds](https://docs.microsoft.com/en-us/vsts/pipelines/build/yaml?view=vsts) , so that steps does not apply to me. For yaml builds there is no options menu, as described in step 13.

![image](https://user-images.githubusercontent.com/3385495/41700535-ae408ac0-7539-11e8-9e0e-d55c106e31c1.png)
 Is there any other way to get build definition Id?

**Comment by thomps23** [comment]
This topic was recently refreshed and now focuses on defining a yml file.
