### ISSUE TITLE
Working directory doesn't affect the build, no ability to set path to gradlew file in UI

### ISSUE THREAD

**Issue by RomanMazanka** [MicrosoftDocs/vsts-docs#7312]
there is a param "Working directory", but it doesn't work. The working directory is root even if another specified. That is why there is no ability to build the project using UI in Azure DevOps - the "Gradle wrapper" option is disabled. Thus, the only option - is to use YAML build and specify the full path to gradlew file through the gradleWrapperFile option.

**Comment by WilliamAntonRohm** [comment]
@RomanMazanka -- Roman, thanks for your feedback; we appreciate it. To make sure we have all the information needed to triage your issue, please let us know which topic you’re referencing.
