### ISSUE TITLE
Linked WorkItems not Shown

### ISSUE THREAD

**Issue by sawhneyapurva** [MicrosoftDocs/vsts-docs#732]
Hi,

The linked work items are not displayed on TFS work item if the linking is done using following ways:

1. If we try linking work items using Visual Studio Team Explorer for GIT code development then those commits are not linked with TFS work item
2. If we use git-commit command and include work item id in the comment like "Changes for #xxxx" even then the commits are not linked with TFS work item.

Please suggest why the commits are not getting linked with TFS work item for GIT using above mentioned ways.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3167d770-e6d3-dde7-2a9f-89967fb49c58
* Version Independent ID: 66c7f3b8-6de6-47ad-c1fa-94fb98bdac69
* Content: [Link work items to support traceability - VSTS & TFS](https://docs.microsoft.com/en-us/vsts/work/track/link-work-items-support-traceability?view=vsts&tabs=new-web-form#feedback)
* Content Source: [docs/work/track/link-work-items-support-traceability.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/work/track/link-work-items-support-traceability.md)
* Service: **unspecified**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by steved0x** [comment]
@KathrynEE Please loop me in on this one if you need - have you seen this before?

@sawhneyapurva When linking a work item to a commit, the link isn't added until the commit is pushed, just as a quick check, is the link to the work items not showing up after you push the commit?

**Comment by sawhneyapurva** [comment]
Yes, I have pushed my commits and still they are not linking.

**Comment by andre-f-paggi** [comment]
Having the same issue here. 

Addin #ID to the commit message or linking the work item on the Team Explorer does not reflect on linked items section of the VSTS's backlog item.

**Comment by Allendorf231** [comment]
We're also having this issue...

**Comment by Allendorf231** [comment]
Found it!

Navigate to:

Project Settings > Code > Repositories > %Your repository% > Options

Now enable Work item management

![image](https://user-images.githubusercontent.com/41143773/45356506-b386b480-b5c3-11e8-9221-219743a82636.png)

**Comment by andre-f-paggi** [comment]
@Allendorf231 This worked for me too! 

Thank you very much for sharing the solution.
