### ISSUE TITLE
Column sort & Tree view

### ISSUE THREAD

**Issue by FF2bricker** [MicrosoftDocs/vsts-docs#7329]
Why don't we have multiple column sort? Why don't we have Tree view in this list also?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cac6c862-47be-a0ec-80c1-02762c3a5134
* Version Independent ID: da9616b3-0fca-dfba-658a-ad218205190a
* Content: [View and filter work items - Azure DevOps Services Public Project](https://docs.microsoft.com/en-us/azure/devops/organizations/public/view-filter-work-items-public?view=azure-devops)
* Content Source: [docs/organizations/public/view-filter-work-items-public.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/public/view-filter-work-items-public.md)
* Product: **devops**
* Technology: **devops-public-projects**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by WilliamAntonRohm** [comment]
Thanks for the suggestions! The product teams aren’t always watching this repository, so to make sure it gets in front of them for triage, please [submit your ideas]( https://developercommunity.visualstudio.com/content/idea/post.html?space=21) here.
