### ISSUE TITLE
Is it ok, if even possible, to assign multiple deployment groups to a single server?

### ISSUE THREAD

**Issue by gojanpaolo** [MicrosoftDocs/vsts-docs#7337]
Hello, we currently have one server for both Dev and UAT environments. Is it ok to assign multiple deployment groups to that server?

Thanks!
Jan 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3b38c265-be4c-b038-e3a9-783a5e5ce659
* Version Independent ID: 67da69da-3651-a8f4-f06a-c35aa3aa98fc
* Content: [Use deployment groups in a release pipeline - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/deployment-groups/?view=azure-devops)
* Content Source: [docs/pipelines/release/deployment-groups/index.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/release/deployment-groups/index.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by RoopeshNair** [comment]
While in theory you can with multiple agents on the same server and registering them with multiple deployment groups.  It is not recommended as  now the deployment / traceability information is split across deployment groups. Ideally, you can have a single deployment groups and use it with multiple pipelines be it dev  or UAT
