### ISSUE TITLE
Work item type Feature (or others) cannot be changed.

### ISSUE THREAD

**Issue by ricardoserradas** [MicrosoftDocs/vsts-docs#734]
According to the documentation, it should be possible to change the type of User Stories, Features, etc. But, in my scenario here, I'm unable to do it. I receive this exact message:

"Work item type Feature cannot be changed."
"Work item type User Story cannot be changed."

How did I get to this step?

- I created this Team Project using Agile;
- Then created a new inherited process based on Agile;
  - Here, I created some new work item types and added some backlog levels;
- I applied the new process to the existing Team Project;
- When I go to the Team Project and try to change the WIT of some work items, I receive this message.

![image](https://user-images.githubusercontent.com/874409/39704891-310d28e8-51e3-11e8-968f-70848d0eee00.png)

**Comment by KathrynEE** [comment]
@ricardoserradas - Thank you for your inquiry. Is it possible that the User Story work item type is currently disabled in the inherited process? If so, you need to enable the “User Story” work item type, convert them to the new type of “Proactive” or whatever other enabled WIT, and then once you've converted all that you want, you can then disable the “User Story” work item type.

**Comment by ricardoserradas** [comment]
Hi Kathryn.

It’s possible to be true. I’m going to check and I’ll let you know.

Best,
Ricardo Serradas

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by mmatiaschek** [comment]
Enabling the Work Item type for migrating items to the new type, then disabling it again worked for me. Thank you!

**Comment by priyarani477** [comment]
> Enabling the Work Item type for migrating items to the new type, then disabling it again worked for me. Thank you!

Hey mmatiaschek,

Can you please share the steps how can I disable the change type permission for work items. thanks you in advance!
