### ISSUE TITLE
Header vs Page Title Mismatch

### ISSUE THREAD

**Issue by KanishkT123** [MicrosoftDocs/vsts-docs#7344]
The page title currently says "Publish Packages to PyPi"
The article itself is about publish to any artifact repository. This is arguably more generic and more applicable. I would request that the page title be changed to "Publish Packages to Artifact Repositories"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 638243e7-cdd6-7573-aa6a-87c39da1bb3d
* Version Independent ID: d0046f56-ed26-7af2-3b8f-3dd5ab6ab892
* Content: [Publish packages to PyPI - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/pypi?view=azure-devops&tabs=yaml#feedback)
* Content Source: [docs/pipelines/artifacts/pypi.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/artifacts/pypi.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @chasewilson
* Microsoft Alias: **phwilson**

**Comment by WilliamAntonRohm** [comment]
@chasewilson -- please review the above-mentioned PR 992.
