### ISSUE TITLE
Install SQL Server Link under How-To guides returns http 404 error

### ISSUE THREAD

**Issue by nyannios** [MicrosoftDocs/vsts-docs#735]
Install SQL Server Link under How-To guides returns http 404 error

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7ea9258d-d528-4f5d-1d67-fc3c33a8cd81
* Version Independent ID: f3103b09-8f5f-3718-161f-51976cbe5ef6
* Content: [Install and configure TFS on a single server](https://docs.microsoft.com/en-us/vsts/tfs-server/install/single-server?view=tfs-2018)
* Content Source: [docs/tfs-server/install/single-server.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/tfs-server/install/single-server.md)
* Service: **unspecified**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by elbatk** [comment]
Ah @nyannios sorry about that - the link should go here:
https://docs.microsoft.com/en-us/vsts/report/sql-reports/reporting-services-reports?toc=/vsts/tfs-server/toc.json&bc=/vsts/tfs-server/breadcrumb/toc.json&view=tfs-2017

Fixing the link in the TOC now.
