### ISSUE TITLE
Pre-reqs need some clarification.

### ISSUE THREAD

**Issue by MarkAtAgilliance** [MicrosoftDocs/vsts-docs#7350]
In this section https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/change-azure-ad-connection?view=azure-devops#prerequisites I think it could be clearer that you need to be a member in the source AD and that AD account needs to be a guest in the destination AD.   

As it currently reads, 
   "You're in the source Azure AD and destination Azure AD as a member"
it sounds like you need an account mark@sourceAD.com and mark@DestAD.com.  This is true for transferring users but not enough to enable the Switch Directory feature.  For this you need a guest account in DestAD.com for mark@SourceAD.com.

Also I would add an FYI that says "If you do not see the Switch Directories control, make sure the same account you signed into in Devops is a member of the source AD and also a *guest* member of the destination AD.

Something like this might work :  (BTW - I am not a writer and I don't play one on TV :-) )

*Prerequisites*
- You're in the Project Collection Administrator group (in Organization settings) for the organization
- You're in the source Azure AD and that account is a guest in the destination Azure AD. 
note: Users that you would like to map/transfer should have a member account (not guest) in the destination AD.  For more information, see how you can convert an Azure AD guest into a member.
Tip:  If you do not see the "Switch Directory" control, then ensure that your account is a guest in the destination AD and you will have to logout and login again to see this control.

Hope this helps.
Mark.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 98f0caaf-2697-c506-339b-2dea64233e48
* Version Independent ID: 7cd2ea02-2079-85d0-09e0-a90af59937d9
* Content: [Switch to another Azure Active Directory - Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/change-azure-ad-connection?view=azure-devops#prerequisites)
* Content Source: [docs/organizations/accounts/change-azure-ad-connection.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/accounts/change-azure-ad-connection.md)
* Product: **devops**
* Technology: **devops-accounts**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @MarkAtAgilliance, Thanks for your feedback! I'm following up on this and will be in touch soon. Thanks!

**Comment by chcomley** [comment]
Hi @MarkAtAgilliance, I've published an update to the prerequisites, based on your feedback. I didn't add the note or tip, however, as the users who want to map just need to exist in the target tenant (either as guests or members) and the **Switch directory** button should always appear and should always be enabled for PCAs. This should be live momentarily!
Please @mention me if you need any further clarification. Thanks!
