### ISSUE TITLE
Unable to add ssh-ed25519 key

### ISSUE THREAD

**Issue by LiohMoeller** [MicrosoftDocs/vsts-docs#7352]
When I try to add a ssh-ed25519 SSH key to Azure I got an error like:

Invalid key: Valid keys will start with "ssh-rsa".

Could you please allow ed25519 as well?

**Comment by WilliamAntonRohm** [comment]
@LiohMoeller -- Lioh, thank you for your feedback; we appreciate it. To make sure we have all the information needed to triage your issue, please let us know which topic you’re referencing, or provide more context around your general task.

**Comment by fuero** [comment]
@WilliamAntonRohm

@LiohMoeller is talking about this screen:

![image](https://user-images.githubusercontent.com/108815/190929442-c30c5dec-3110-4908-8605-f5f41d811c93.png)

Here you can add SSH keys to your user account using the 'Add' button. The dialogue that follows refuses to accept anything but `ssh-rsa` type keys. As a user, I expect all key types to be supported that `ssh-keygen` is able to generate and are deemed secure by the OpenSSH docs. See [ssh-keygen's man page](https://man.openbsd.org/ssh-keygen.1).

**Comment by WilliamAntonRohm** [comment]
@fuero -- thank you for clarifying.  This seems to be a product issue, rather than a documentation issue.  Please add it here:
- [Developer Community](https://developercommunity.visualstudio.com/search?space=21)

**Comment by fuero** [comment]
It's already there... Has only been a few years:
https://developercommunity.visualstudio.com/t/Support-non-RSA-keys-for-SSH-authenticat/365980

**Comment by WilliamAntonRohm** [comment]
@fuero -- thank you for your follow-up.  I upvoted that issue.
