### ISSUE TITLE
Innacurate documentation for "Select the default access level for new users"

### ISSUE THREAD

**Issue by ewekansige** [MicrosoftDocs/vsts-docs#7354]
Selecting the default access level for new users is no longer available on the billing page, the section "Change Default access level for new users to Basic." is missing.
The billing page only contains a section for pipelines, a section for boards, repos and test plans and a section for Resources.

Please update the document so we can see how to set the default access level, I'm starting to suspect that now it is always pre-set to stakeholder (is that how it works now?).

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: 608a8c53-51a9-0878-da16-bfb7f977e01b
* Version Independent ID: 52155a9a-b7bf-607c-a90d-547395f059d6
* Content: [Manage paid access for users in Azure DevOps - Azure DevOps](https://docs.microsoft.com/es-es/azure/devops/organizations/billing/buy-basic-access-add-users?view=azure-devops)
* Content Source: [docs/organizations/billing/buy-basic-access-add-users.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/billing/buy-basic-access-add-users.md)
* Product: **devops**
* Technology: **devops-billing**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @ewekansige, Thanks for reaching out. One question: Is billing already set up? "Change Default access level for new users to Basic" only shows up after you've set up billing. Please let me know. Thank you!

**Comment by ewekansige** [comment]
Maybe we're seeing a different version of the interface?
Our billing has been properly set up for a while. This is how the Billing section shows up in our organization:

![image](https://user-images.githubusercontent.com/39995110/74967126-62006d00-53e6-11ea-9f3c-3713bdf25dd5.png)

**Comment by drewbren** [comment]
@ewekansige it seems like there is an issue with your org, can you send me an email at Andrew dot Brenner at Microsoft dot com? I'd like to get a few more details from you and we can get this resolved. Thanks!
