### ISSUE TITLE
Is there any way to limit the amounts of copying files for Copy Files task in release pipeline?

### ISSUE THREAD

**Issue by BaoYiQunSSMR** [MicrosoftDocs/vsts-docs#7361]
**Copy files task:**
https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/copy-files?view=azure-devops&tabs=yaml

**The pattern in contents, but there is no way about how to control the amount of copying:**
https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/file-matching-patterns?view=azure-devops

**Comment by vtbassmatt** [comment]
I don't understand the request. The task will copy the files which match your pattern.

**Comment by BaoYiQunSSMR** [comment]
@vtbassmatt 
For example, folder A has 4 *.zip files(In the future there may be 100 files), I  want to only copy the newest 2 *.zip files to folder B. How to set the contents?
![image](https://user-images.githubusercontent.com/61310176/75302978-60b5c100-587a-11ea-8d87-d9f71c5243cd.png)

![image](https://user-images.githubusercontent.com/61310176/75302524-036d4000-5879-11ea-8ab0-59cd8a653837.png)

**Comment by vtbassmatt** [comment]
Copy Files can only be limited by filename, not by age. I think you could say `?.zip` in this case to only get files with a one-character name.

**Comment by BaoYiQunSSMR** [comment]
OK, since the one-character name is just an example, I have used powershell with robocopy commands to implement, and realized the function of controlling file amounts and maxage.
Also thanks for your suggestion.
