### ISSUE TITLE
Billing page design encourages confusion between minutes and jobs 

### ISSUE THREAD

**Issue by NeilMacMullen** [MicrosoftDocs/vsts-docs#7363]
A minor point but in step 4 "Enter the amount of Microsoft-hosted CI/CD or Self-hosted CI/CD, and then select Save." the design of the billing page is confusing. It shows the current free tier as "1800 minutes" so my first instinct was to enter a number of minutes into the "Paid" box until I realised it was meant to be the number of jobs. I'm not quite sure what would have happened if I'd really tried to book 3000 parallel jobs but but I'm hoping it wouldn't have been a call from the credit card company! ;-)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7734edca-173b-ba47-bf1b-3c19f9bd93e1
* Version Independent ID: d6ea8680-546e-f102-fd55-b35af33a6aa5
* Content: [Buy CI/CD Azure Pipelines - Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/organizations/billing/buy-more-build-vs?view=azure-devops#microsoft-hosted-cicd)
* Content Source: [docs/organizations/billing/buy-more-build-vs.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/billing/buy-more-build-vs.md)
* Product: **devops**
* Technology: **devops-billing**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by Sarrgas** [comment]
Totally agree on this. My team were just doing this, and we were *this* close to buying 1800 agents, instead of the 2 or 3 that we actually needed.... Very unclear instructions!

**Comment by drewbren** [comment]
Thanks for the feedback! We will make this more clear ASAP. Quick question. If we update the text to say "Paid parallel jobs" and the size of the text box - is that clear enough? See below

![image](https://user-images.githubusercontent.com/3791931/75181245-ac3d6300-56f2-11ea-9a47-0b7dc3e47f88.png)

**Comment by Sarrgas** [comment]
That would be better! A step in the right direction, although I still miss some clarity in the fact that "paid jobs" also means "unlimited minutes" (if that even is the case? Kinda confused over here....)
For instance, my teams needs were not related to needing more parallel jobs, but rather "more minutes", as we reached the maximum of the free agents. We simply wanted to "buy more minutes", so the parallel jobs-feature was really just a happy bonus :)

**Comment by NeilMacMullen** [comment]
Agree with @Sarrgas  - in fact I'm still a little confused over whether 1 "paid" job means "1800 free minutes on the shared pool + unlimited minutes on 1 dedicated job" or just "unlimited minute on 1 dedicated job" ?  Nevertheless - the new wording is definitely an improvement so thanks for that! :-)
