### ISSUE TITLE
Update "Q: Which versions of Visual Studio can I use with Azure DevOps?"

### ISSUE THREAD

**Issue by KellyMcMeekin-Blackbaud** [MicrosoftDocs/vsts-docs#7369]
The current answer implies you can't use VS 2019 with ADO, which I don't believe is correct based on https://docs.microsoft.com/en-us/azure/devops/organizations/projects/connect-to-projects?view=azure-devops&tabs=visual-studio-2019

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b267c3a8-85d9-0ab6-12f9-2cb5c0af0735
* Version Independent ID: 7eec9937-897e-e67a-87c9-b80122917dc8
* Content: [Troubleshoot setting up Visual Studio - Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/faq-set-up-vs?view=azure-devops#feedback)
* Content Source: [docs/organizations/accounts/faq-set-up-vs.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/accounts/faq-set-up-vs.md)
* Product: **devops**
* Technology: **devops-accounts**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @KellyMcMeekin-Blackbaud, Thanks so much for bringing this to our attention. I've just published a fix, which should be live momentarily. Thanks again!
