### ISSUE TITLE
Can assign outside of project

### ISSUE THREAD

**Issue by cmw2** [MicrosoftDocs/vsts-docs#7370]
The doc says:
   You can assign a work item only to users that have been added to a project or team

However in testing this doesn't seem to be the case.  It allows assignment to anyone in the AD, not just members of the project/team.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a197bf55-89c7-682d-bb1c-e82bec732349
* Version Independent ID: 5aa2afac-cb82-3f72-643c-25a0173cce98
* Content: [Using work items to track user stories, & more - Azure Boards and TFS](https://docs.microsoft.com/en-us/azure/devops/boards/work-items/about-work-items?view=azure-devops&tabs=agile-process#feedback)
* Content Source: [docs/boards/work-items/about-work-items.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/boards/work-items/about-work-items.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@cmw2 - Thank you for your inquiry. I believe the documentation is correct as written. If the way permissions are working for your instance are causing a problem, please file your problem here: https://developercommunity.visualstudio.com/spaces/21/index.html.

**Comment by cmw2** [comment]
@KathrynEE  - I checked over on developer community and found other posts of the same issue.  [This post](https://developercommunity.visualstudio.com/solutions/532894/view.html) has an answer that says "There is currently no such feature that can limit the users in the assign to only the project team."  So there seems to be a disconnect.  The software doesn't behave as this doc says, and the answer from developer community also states that it doesn't behave that way.  Shouldn't the doc be changed then?
