### ISSUE TITLE
Unsupported HTML (iframe)

### ISSUE THREAD

**Issue by squalrus** [MicrosoftDocs/vsts-docs#7371]
Are there certain HTML elements that are not supported? I am trying to embed a PowerPoint presentation which is embedded using an &lt;iframe&gt;. Assuming this is intentional, could the article include a list of non-supported HTML elements?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 29f1e43f-a069-dd88-7fc7-9cc497fb94f0
* Version Independent ID: c261afa7-6eb7-b3f0-9f92-6d2f3c5ac336
* Content: [Markdown syntax for wikis in Azure DevOps - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/project/wiki/wiki-markdown-guidance?view=azure-devops#feedback)
* Content Source: [docs/project/wiki/wiki-markdown-guidance.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/project/wiki/wiki-markdown-guidance.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by WilliamAntonRohm** [comment]
@squalrus -- Chad, thank you for your question.  There are many HTML tags, and it would be more complete to specify those that are supported than those that are not.

@chcomley -- Chrystal, please look into this issue.

**Comment by chcomley** [comment]
Hi @squalrus, I have to agree with William that listing the HTML tags that are supported is our goal. I invite you to submit a feature request for supporting this, however. Please go here to do so: https://developercommunity.visualstudio.com/spaces/21/index.html, and then select **Suggest a feature**. Thank you for your feedback!

**Comment by laurawalker** [comment]
Vote here for iframe: https://developercommunity.visualstudio.com/content/idea/608314/allow-iframe-elements-to-be-embedded-in-wiki-pages.html
