### ISSUE TITLE
Does changing owner make any impacts?

### ISSUE THREAD

**Issue by nguyenlamlll** [MicrosoftDocs/vsts-docs#7379]
Reading this document, I understand the scenario when we need to change the owner, which fits my organization's situation. 

However, are there any underlying changes? This document didn't mention it. Or am I changing the surface look only?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: df27392f-aec0-41d9-726c-88abc12468e0
* Version Independent ID: f21e6a50-99f5-819b-4e09-99a84253bf9d
* Content: [Change the owner of an organization - Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/change-organization-ownership?view=azure-devops)
* Content Source: [docs/organizations/accounts/change-organization-ownership.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/accounts/change-organization-ownership.md)
* Product: **devops**
* Technology: **devops-accounts**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @nguyenlamlll, Changing the owner doesn't cause any underlying changes. Thanks so much for reaching out!
