### ISSUE TITLE
This article is out of date

### ISSUE THREAD

**Issue by pheonixblade9** [MicrosoftDocs/vsts-docs#738]
With the newest version of VSTS

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c0449868-e233-3ada-067b-fc8de52ecc9a
* Version Independent ID: df871375-c579-12c1-6aec-394046c42746
* Content: [Delete or recover VSTS account](https://docs.microsoft.com/en-us/vsts/accounts/delete-your-vsts-account?view=vsts#feedback)
* Content Source: [docs/accounts/delete-your-vsts-account.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/accounts/delete-your-vsts-account.md)
* Service: **unspecified**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Thanks for the heads up, @pheonixblade9 ! I've updated the topic with fresh screenshots and updated content. These changes should go live sometime this afternoon. Thanks again.
