### ISSUE TITLE
Project Managers, or Product Owners?

### ISSUE THREAD

**Issue by ajtgh** [MicrosoftDocs/vsts-docs#7383]
"Project managers
Project managers (PMs) typically plan the feature set to deliver, set priorities, and track the status of work, code defects, and customer issues."

Not in an Agile context - just a thought.

Thanks guys, great resource.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a5389de-ae53-e46b-45b7-2edde0d794a7
* Version Independent ID: dbffc6f2-5386-d398-3f9b-32ef5750fb23
* Content: [Supported roles for software development - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/user-guide/roles?view=azure-devops)
* Content Source: [docs/user-guide/roles.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/user-guide/roles.md)
* Product: **devops**
* Technology: **devops-new-user**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
@ajtgh Thanks for the feedback!
