### ISSUE TITLE
Precedence of multiple variables with the same name from linked variable groups.

### ISSUE THREAD

**Issue by theyetiman** [MicrosoftDocs/vsts-docs#7384]
E.g. I have two variable groups containing a variable with the same name

```
Group    Var     Value
VG1      MyVar   Foo
VG2      MyVar   Bar
```

If I include VG1 and VG2 in my pipeline as linked variable groups, which value am I going to get for "MyVar"? 

Does the order in which I add the variable group matter? Is it random/unpredictable? Does it error or give empty/null value?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd7e0bd3-1f7d-d7b6-cc72-5ef63c31b46a
* Version Independent ID: dae87abd-b73d-9120-bcdb-6097d4b40f2a
* Content: [Define variables - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=classic%2Cbatch#feedback)
* Content Source: [docs/pipelines/process/variables.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/variables.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by juliakm** [comment]
The order of the variable groups does matter. The last included variable group in the YAML file will set the value if both groups define the same variable. 

In this example, I have two variable groups (`group-one` and `group-two`) and both have the variable c. 

```yaml
trigger: none
variables: 
  - group: group-two # var c is beta
  - group: group-one # var c is alpha

steps: 
  - script: echo $(c) # outputs alpha
```

**Comment by juliakm** [comment]
#sign-off

**Comment by ericchansen** [comment]
This is a bad solution. It should be possible to access the variables that were "overwritten" in the earlier variable group using some syntax.

**Comment by lachlann562** [comment]
I created a feature request to allow you to be able to visualize which variable groups are linked to a given stage instead of the other way around (what is currently supported) 

https://github.com/microsoft/azure-pipelines-tasks/issues/14696

**Comment by george-ly** [comment]
> This is a bad solution. It should be possible to access the variables that were "overwritten" in the earlier variable group using some syntax.

yes upvote for this please. I want to use the same variable stored in two different groups in the same stage.
