### ISSUE TITLE
Deployment Job

### ISSUE THREAD

**Issue by mslot** [MicrosoftDocs/vsts-docs#7392]
Why do you "we recommend that you put your deployment steps in a deployment job."? Is it because you then can rerelease a release? Or? We need more clarification on this, i think.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7458d5b2-1bb7-7d87-7ce6-2b0c430b0155
* Version Independent ID: edf5bbd3-a3f0-5426-e985-31290f8afd05
* Content: [YAML schema - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema#deployment-job)
* Content Source: [docs/pipelines/yaml-schema.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/yaml-schema.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by ramiMSFT** [comment]
@mslot Thank you for your feedback. A deployment job is a special type of job that's a collection of steps, which are run sequentially against the environment.

Deployment jobs provide the following benefits:

- Deployment history: You get end-to-end deployment history across pipelines, down to a specific resource and status of the deployments for auditing.

- Apply deployment strategy: You define how your application is rolled out. 

You can find more details about deployment jobs [here](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/deployment-jobs?view=azure-devops)

**Comment by mslot** [comment]
> @mslot Thank you for your feedback. A deployment job is a special type of job that's a collection of steps, which are run sequentially against the environment.
> 
> Deployment jobs provide the following benefits:
> 
> * Deployment history: You get end-to-end deployment history across pipelines, down to a specific resource and status of the deployments for auditing.
> * Apply deployment strategy: You define how your application is rolled out.
> 
> You can find more details about deployment jobs [here](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/deployment-jobs?view=azure-devops)

The "rerun" stage is very well hidden in the UI. That was why I couldn't find it:
![image](https://user-images.githubusercontent.com/544655/76958033-3904c680-6917-11ea-972a-7d96a2d17b29.png)

you need to describe in docs that you have to hover over the right top corner and push this icon
![image](https://user-images.githubusercontent.com/544655/76958093-5b96df80-6917-11ea-95f1-8353cec4df3c.png)
