### ISSUE TITLE
Re-title the last question

### ISSUE THREAD

**Issue by shaisundar** [MicrosoftDocs/vsts-docs#7398]
The last question - 
"If I change the organization name, can I switch back? Is the toggle two way?" - is pretty confusing. 

Changing the "name of the organisation" and  "Use the new URL"  are two different things, and the answer responds to the latter rather than the former. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 129e3d78-3ac8-8d07-d573-5530cd018656
* Version Independent ID: 1fbe6f52-2967-114e-1d2b-af4771080ac7
* Content: [Rename your organization - Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/rename-organization?view=azure-devops)
* Content Source: [docs/organizations/accounts/rename-organization.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/accounts/rename-organization.md)
* Product: **devops**
* Technology: **devops-accounts**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @shaisundar, Thanks so much for pointing this out. I've published an update, which should be live momentarily. Thanks again!
