### ISSUE TITLE
Chinese version of this document missing?

### ISSUE THREAD

**Issue by moyanming** [MicrosoftDocs/vsts-docs#740]
There used to be a Chinese version of [this document](https://docs.microsoft.com/zh-cn/azure/devops/git/what-is-version-control). But it is missing recently. How to find or get the Chinese version of this document?
https://docs.microsoft.com/zh-cn/azure/devops/git/what-is-version-control
[在此处输入反馈]

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 64f1b21d-ba58-7b3f-126f-d62c0ff931b3
* Version Independent ID: c82e367a-1080-8a43-0386-b9e1eecc42c7
* Content: [What is version control? - Azure DevOps](https://docs.microsoft.com/zh-cn/azure/devops/git/what-is-version-control)
* Content Source: [https://mseng.visualstudio.com/DefaultCollection/TechnicalContent/_git/devops-learn-pr?path=%2fdocs%2fgit%2fwhat-is-version-control.md&version=GBlive&_a=contents](https://mseng.visualstudio.com/DefaultCollection/TechnicalContent/_git/devops-learn-pr?path=%2fdocs%2fgit%2fwhat-is-version-control.md&version=GBlive&_a=contents)
* Service: **devops**
* GitHub Login: @samgu
* Microsoft Alias: **routlaw**

**Comment by steved0x** [comment]
@moyanming These documents were just migrated over to docs.microsoft.com and I think the translated versions are coming shortly. I'll see if I can get an update on the timeline.

**Comment by ltm0203** [comment]
@steved0x 
Hello, do you have a repository in Chinese?
Or build one?
I translated several articles, but found that he did not have a Chinese repository ?
How do I deal with and cooperate?

**Comment by thomps23** [comment]
Azure DevOps documentation is not currently localized.
