### ISSUE TITLE
Document missing information

### ISSUE THREAD

**Issue by doramalita** [MicrosoftDocs/vsts-docs#7403]
It is worth to mention that Deploy: Azure PowerShell task will only run successfully if the VMSS was created with unmanaged OS disk created from generalized VHD. Only in this case can image.uri be changed to a new path of VHD. If the VMSS was created from an image in your resource group (or shared image gallery), imageReference exists under storageProfile, and it expects fully qualified 
resource Id that start with '/subscriptions/{subscriptionId}' or '/providers/{resourceProviderNamespace}/'. In this case another set commands are needed to create an image from the VHD.

**Comment by WilliamAntonRohm** [comment]
@doramalita -- Thanks for your feedback; we appreciate it. To make sure we have all the information needed to triage your issue, please let us know which topic you’re referencing, or provide more context around the general task.
