### ISSUE TITLE
Stage vs jobs

### ISSUE THREAD

**Issue by trajano** [MicrosoftDocs/vsts-docs#7405]
We need a table that illustrates the differences between Stage and Jobs.

Some things that can come up.

| factor | Stages | Jobs |
|-|-|-|
| UX  | appears as separate icons on the pipeline view | --- |
| Steps | --- | contains steps |

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7f8c8539-89a7-a426-868b-96e961c39e29
* Version Independent ID: de260a68-aab7-7c6b-6727-90c92c65b225
* Content: [Azure Pipelines New User Guide - Key concepts - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/get-started/key-pipelines-concepts?view=azure-devops)
* Content Source: [docs/pipelines/get-started/key-pipelines-concepts.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/get-started/key-pipelines-concepts.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by juliakm** [comment]
Thanks for the suggestion. I've added it to our backlog.
