### ISSUE TITLE
We got a error message like ”Can't find netstandard2.0.0“. Could you give me a hand?

### ISSUE THREAD

**Issue by tjlcast** [MicrosoftDocs/vsts-docs#7418]
When we use `Visual Studio Test task` it doesn't work and shows a error message: 

##[error]Unhandled exception ocurred: System.IO.FileNotFoundException: Could not load file or assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of 
its dependencies. The system cannot find the file specified.

It seems there isn't netstandard2.0.0 in our test machine  when we run the Visual Studio Test task.  Is there some suggestions about how to solve the error?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 16bd8dd1-7650-8c18-2553-38a8bc54e892
* Version Independent ID: f9fa517a-7adc-e327-d12e-256295a1ed52
* Content: [Visual Studio Test task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/test/vstest?view=azure-devops#feedback)
* Content Source: [docs/pipelines/tasks/test/vstest.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/test/vstest.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @PBoraMSFT
* Microsoft Alias: **pbora**

**Comment by ronniemacapobre** [comment]
May be this could help.

https://developercommunity.visualstudio.com/content/problem/929883/visual-studio-test-task-cannot-find-dotnetstandard.html

**Comment by WilliamAntonRohm** [comment]
@tjlcast -- thank you for your question.

@ronniemacapobre -- thank you for your answer.  That link indicates this error has been fixed.

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.

**Comment by tjlcast** [comment]
We have observed that this task problem has been solved and it works normanlly. If similar problems appear next time, as a customer, how can we know the latest updates of these problems and their impacts in time. For example, when to fix it.
