### ISSUE TITLE
Broken permalink https://aka.ms/yamlauthz

### ISSUE THREAD

**Issue by algattik** [MicrosoftDocs/vsts-docs#7419]
When using a non-authorized pool in a YAML pipeline, the error "##[error]Pipeline does not have permissions to use the referenced pool(s) starterpool. For authorization details, refer to https://aka.ms/yamlauthz." is displayed. The link points to "https://docs.microsoft.com/en-gb/azure/devops/pipelines/process/resources?view=azure-devops&tabs=schema#troubleshooting-authorization-for-a-yaml-pipeline", which is a broken link.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee4ec9d0-e0d5-4fb4-7c3e-b84abfa290c2
* Version Independent ID: 3e2b80d9-30e5-0c48-49f0-4fcdfedf5eee
* Content: [Resources - Azure Pipelines](https://docs.microsoft.com/en-gb/azure/devops/pipelines/process/resources?view=azure-devops&tabs=schema#troubleshooting-authorization-for-a-yaml-pipeline)
* Content Source: [docs/pipelines/process/resources.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/resources.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by juliakm** [comment]
@vtbassmatt It looks like you are the owner of the name yamlauthz. I think the link should be https://docs.microsoft.com/azure/devops/pipelines/troubleshooting instead of https://docs.microsoft.com/en-gb/azure/devops/pipelines/process/resources?view=azure-devops&tabs=schema#troubleshooting-authorization-for-a-yaml-pipeline but I am not sure.

**Comment by vtbassmatt** [comment]
It looks like we lost the troubleshooting paragraph (and heading) in one of the content refreshes, so I'll need to reintroduce that before I can update the link. Sorry about that.

**Comment by juliakm** [comment]
Looks like [this commit](https://github.com/MicrosoftDocs/azure-devops-docs-pr/commit/4a93925443b818b7690baa0bdc338989b9f7c4ad#diff-663bc0b275794deeae17d13bbbd82216). Working on restoring.
