### ISSUE TITLE
Connect to AZ repo from Azure hosted agents

### ISSUE THREAD

**Issue by SidGrundfos** [MicrosoftDocs/vsts-docs#7423]
Thank you for your feedback!

The issues in this repo are for documentation feedback.

If you are submitting your documentation feedback issue directly through GitHub, please provide the URL of the article so we can route the feedback to the correct author.

Please report Azure DevOps or TFS software bugs, feedback, or questions in the [Azure DevOps Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html).

**Comment by SidGrundfos** [comment]
Hello Team,
I have the following requirement - 
Terraform scripts which refers other repositories as modules. I have a multistage pipeline which starts the chain with planning a terrafrom main file which in turn refers other repositories in chain. When I use ubuntu latest as agent it tries to download the referred repos but fails with permission denied. Is there a way or any parameters which can be configured in the yaml to solve this?

**Comment by WilliamAntonRohm** [comment]
@SidGrundfos -- thank you for your feedback; we appreciate it. To make sure we have all the information needed to assess your issue, please let us know which topic you’re referencing, and provide more context around your general task.
