### ISSUE TITLE
Status of a code review comment

### ISSUE THREAD

**Issue by DrGriff** [MicrosoftDocs/vsts-docs#7429]
When performing a code review, I add suggested changes.  These go in with the status of ACTIVE.

When the Developer makes his change, then they change it to "RESOLVED". 

The possible statuses are: Active, Pending, Resolved, Won't Fix and Closed.  

I think it would be great to add some documentation giving examples of when you'd use each status.  Personally, I'm not clear on when to use "Closed".  

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eea32d3a-53e9-3e21-d419-6e8c8c055ef0
* Version Independent ID: 4942fd13-34c2-a2ef-5e2d-fff913a397ed
* Content: [Create a pull request - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/pullrequest?view=azure-devops)
* Content Source: [docs/repos/git/pullrequest.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/repos/git/pullrequest.md)
* Product: **devops**
* Technology: **devops-code-git**
* GitHub Login: @apawast
* Microsoft Alias: **sdanie**

**Comment by WilliamAntonRohm** [comment]
Related to #7430.
