### ISSUE TITLE
Consider adding `Limitations` section

### ISSUE THREAD

**Issue by iyerusad** [MicrosoftDocs/vsts-docs#743]
Noticing that certain tasks don't support Powershell core, which is what Hosted Linux Agents run, powershell wise. 

It might make some sense to add a limitation section for tasks to outline known limitations (I don't believe full AzureRM, which this task is, runs on powershell core). Without it, it can be confusing as there is [an AzureRM (abliet, a limited one) that works on powershell core](https://docs.microsoft.com/en-us/powershell/azure/install-azurermps-maclinux?view=azurermps-6.0.0), but this task runs full AzureRM, which appears to require full powershell, which requires Windows agent (hosted or private).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fb215324-b1a0-93b5-5022-4bcc7da93bb7
* Version Independent ID: 9eb2977b-ac34-9d53-670e-04fa027bc8e4
* Content: [Azure PowerShell](https://docs.microsoft.com/en-us/vsts/build-release/tasks/deploy/azurepowershellv3.3?view=vsts)
* Content Source: [docs/build-release/tasks/deploy/AzurePowerShellV3.3.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/build-release/tasks/deploy/AzurePowerShellV3.3.md)
* Service: **devops**
* GitHub Login: @erickson-doug
* Microsoft Alias: **dastahel**

**Comment by steved0x** [comment]
@DavidStaheli Can you take a look at this one? Thank you!

**Comment by shashban** [comment]
The Azure powershell step has a built in demand for AzurePS. The job would execute on a compatible agent only. If an agent has powershell core only, then it would not be picked up for execution of the job.
