### ISSUE TITLE
Is .order file case sensitive?

### ISSUE THREAD

**Issue by styfle** [MicrosoftDocs/vsts-docs#744]
I see two references to the `.order` file.
In this document it is lowercase.
However, in this document, it is uppercase: https://blogs.msdn.microsoft.com/devops/2018/03/25/announcement-publish-markdown-files-from-your-git-repository-to-vsts-wiki/

Is the file case sensitive?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dfd8b86a-48ce-08ea-5b24-529c220cc682
* Version Independent ID: 142d1339-6613-29a7-b160-e5ed9a37979b
* Content: [Clone and update wiki content offline - VSTS & TFS](https://docs.microsoft.com/en-us/vsts/collaborate/wiki-update-offline?view=vsts#add-pages-to-the-git-repository)
* Content Source: [docs/collaborate/wiki-update-offline.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/collaborate/wiki-update-offline.md)
* Service: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@styfle - Thank you for your inquiry. The file is case sensititive and should be labeled as **.order**.

**Comment by styfle** [comment]
@KathrynEE I see. Are you going to fix the blog post?
