### ISSUE TITLE
available in Azure DevOps Server, timeline?

### ISSUE THREAD

**Issue by Dauit** [MicrosoftDocs/vsts-docs#7442]
according to your feature timeline this will be available during 2020, this is highly requested by our developers, do you have a more specific release timeline for this feature?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5aeeaace-1c5b-a51b-e41f-f25b806155b8
* Version Independent ID: fd7ff690-b2e4-41c7-a342-e528b911c6e1
* Content: [Deployment jobs - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/deployment-jobs?view=azure-devops&viewFallbackFrom=azure-devops-2019#feedback)
* Content Source: [docs/pipelines/process/deployment-jobs.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/deployment-jobs.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by WilliamAntonRohm** [comment]
@Dauit -- thank you for your question.  It may be answered [here](https://docs.microsoft.com/en-us/azure/devops/release-notes/features-timeline).

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
