### ISSUE TITLE
Usage of Variables

### ISSUE THREAD

**Issue by Emrahdi** [MicrosoftDocs/vsts-docs#7444]
Hi,
I execute a plenty of powershell scripts for backup website,copy files, execute IIS operations etc.
In every definition I have to write the script path staticly. Is variable usage possible with script path and Script Arguments?

**Comment by WilliamAntonRohm** [comment]
@Emrahdi -- EmrahDi, thanks for your feedback; we appreciate it. To make sure we have all the information needed to triage your issue, please let us know which topic you’re referencing, or provide more context around your general task.

**Comment by Emrahdi** [comment]
Hi,
Thank you for quick reply @WilliamAntonRohm,
I keep the powershell scripts in the repository and deploy these scripts too. I execute these scripts and don't use inline scripts to avoid dependency on the Platform.
The pipeline stages are as in the following and in these powershell tasks, I have to define the script location seperately for each powershell task.

Script File Path : **C:\azagent\A2\_work\r1\a\ApplicationName\drop\CHP\DevOpsPowerShellScripts**\BackUpWebSite.ps1

Script File Path : **C:\azagent\A2\_work\r1\a\ApplicationName\drop\CHP\DevOpsPowerShellScripts**\RestAPICall.ps1

Instead of this, I think it will be much better to define a variable in the Azure Devops portal and use as in the following. 

Script File Path : 
($PowerShellScriptsPath)\BackUpWebSite.ps1

If the path changes, I don't have to change the "Script File Path" of power shell tasks separately. It will be enough to change the variable only. Also, I have to use define the repetitive configuration within the PowerShell scripts parameter like passing the name of the **website name**. But this will maybe cause conflict if ($ParamaterName) is really wanted to be taken as parameter.

The pipeline has the following stages.

Build the application,
Deploy the application using the Azure Agent as a new WebSite (Staging),
Back-up website using msdeploy.exe using **powershell scripts** (PowerShell on Targets Machine Task),
Call REST API for testing Staging Web Site using **powershell scripts** (PowerShell on Targets Machine Task),
Stop IIS app pool of staging and current website using **powershell scripts** (PowerShell on Targets Machine Task),
Swap website phsical path using **powershell scripts** (PowerShell on Targets Machine Task),
Start the website application pool  using **powershell scripts** (PowerShell on Targets Machine Task),
Delete staging website and app pool  **powershell scripts** (PowerShell on Targets Machine Task),
Delete pysical path of previous web site **powershell scripts** (PowerShell on Targets Machine Task),


Thanks

**Comment by WilliamAntonRohm** [comment]
@Emrahdi -- EmrahDi, thank you for clarifying.  Do you have a particular docs.microsoft.com article in mind?
