### ISSUE TITLE
Why call it is parallel job, when you can run only one build or release job at a time ?

### ISSUE THREAD

**Issue by nbandi413** [MicrosoftDocs/vsts-docs#7447]
Could you please clarify. Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c6a488b-88f6-dff6-e2ee-402167e17ad4
* Version Independent ID: 9a4dedda-e82c-2833-f28c-5ab346fb1b38
* Content: [Parallel jobs - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/pipelines/licensing/concurrent-jobs?view=azure-devops#feedback)
* Content Source: [docs/pipelines/licensing/concurrent-jobs.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/licensing/concurrent-jobs.md)
* Product: **devops**
* Technology: **devops-cicd-licensing**
* GitHub Login: @steved0x
* Microsoft Alias: **jukullam**

**Comment by steved0x** [comment]
@nbandi413 A parallel job in this context is a license to run a job. If you have 1 parallel job in your organization, then you can run 1 job at a time. If your pipeline specifies parallel jobs, or if you try to run multiple pipelines at the same time, the jobs will queue up and run 1 at a time. If you have 10 parallel jobs licensed, you can have 10 jobs running concurrently, spread across multiple pipelines, or a single pipeline that runs jobs concurrently using the parallel strategy.

I can see how it could be confusing with multiple uses for "job" and "parallel" - does this info help?
