### ISSUE TITLE
Read only permissions for wiki docs

### ISSUE THREAD

**Issue by g6andrew** [MicrosoftDocs/vsts-docs#745]
I have several users, both Stakeholder and Basic, in the Readers group of my project.  But they get the message "you do not have sufficient permissions to read wiki" when trying to read a wiki doc.  They are not in Contributors, and shouldn't be, since they don't change code.  How do I grant them read permission?  Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 58d291c7-b242-57ae-e4ae-2a75eaf3c91d
* Version Independent ID: 4d491730-d433-05a5-e685-9cbaa16141cb
* Content: [Manage permissions for READMEs and wiki pages - VSTS & TFS](https://docs.microsoft.com/en-us/vsts/collaborate/manage-readme-wiki-permissions?view=vsts)
* Content Source: [docs/collaborate/manage-readme-wiki-permissions.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/collaborate/manage-readme-wiki-permissions.md)
* Service: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@g6andrew - Thank you for your inquiry. Stakeholders and Contributors should be able to read a Wiki. Could you check the Readers group permissions for the Wiki Security dialog - https://docs.microsoft.com/en-us/vsts/collaborate/manage-readme-wiki-permissions?view=vsts - and make sure that it is set to Allow. If that isn't the problem, I suggest you report any problems on the Developer Community, https://developercommunity.visualstudio.com/spaces/21/index.html. You can also get support via our [Support](https://www.visualstudio.com/team-services/support/) page.
