### ISSUE TITLE
Importing work items with direct link via .csv/ .xlsx file

### ISSUE THREAD

**Issue by SandeepDhamale19** [MicrosoftDocs/vsts-docs#7452]
How to import work items with direct link? E.g. import a bug with linked test case ( by id/ name)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4296d1cc-f211-9d17-d97f-2b0858fdea7d
* Version Independent ID: cc66dfee-adde-cdfb-b3f5-5d58d89d3c81
* Content: [Import or update work items from a CSV file - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/queries/import-work-items-from-csv?view=azure-devops#feedback)
* Content Source: [docs/boards/queries/import-work-items-from-csv.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/boards/queries/import-work-items-from-csv.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by SandeepDhamale19** [comment]
The microsoft docs (https://docs.microsoft.com/en-us/azure/devops/boards/queries/import-work-items-from-csv?view=azure-devops) mention about importing work itmes with parent - child relationship. I need to import bug and associate it with test case id/ name (direct link relationship). E.g. In .csv file I can mention bug title in one column and associated test case id/ name in other. Then I should be able to upload csv file, and test case should be automatically linked to bug after upload.

**Comment by SandeepDhamale19** [comment]
Also would be great if we can import screenshots from CSV to bug

**Comment by KathrynEE** [comment]
@SandeepDhamale19 - Similar to importing work items with Excel, only parent-child relationships are supported. No direct link relationships are supported for import or update.  Please see this Q&A for info on import or update of work and test items: https://docs.microsoft.com/en-us/azure/devops/boards/backlogs/office/faqs?view=azure-devops#work-with-test-work-items. 

Also, you might consider suggesting this feature or upvoting a feature for import of direct link relationships. See https://developercommunity.visualstudio.com/content/idea/post.html?space=21.
