### ISSUE TITLE
Exact search, no "stemming"?

### ISSUE THREAD

**Issue by ScottWelker** [MicrosoftDocs/vsts-docs#7453]
Is there no way to search for an exact match? If exact match is supported it would be useful if the "Related articles" section linked to the appropriate documentation. If it is not supported it would be helpful to say so.

For example the quoted string "C++". A search for this in our Wiki results in 100s of unwanted results, e.g. all pages containing text like "Part C", "C#," "C:", "-c", "c.", "L.L.C.", "C programming", "TPC-C", "U.S.C." etc. It's like sipping from a fire hydrant.

As a work-around, I clone the repository and run grep against the .md files. Not optimal.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 219de2f0-b98c-3fcf-dc0c-7518e913c944
* Version Independent ID: a7e93e0a-fece-4848-9f58-42aeac9700b4
* Content: [Search the Wiki in Azure DevOps - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/project/wiki/search-wiki?view=azure-devops#feedback)
* Content Source: [docs/project/wiki/search-wiki.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/project/wiki/search-wiki.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @ScottWelker, Thanks for reaching out. I'm following up with a PM and will be in touch soon.

**Comment by chcomley** [comment]
Hi @ScottWelker,
Unfortunately there is no way to trigger an exact match in wiki search. Please go [here](https://developercommunity.visualstudio.com/spaces/21/index.html), and then select **Suggest a feature**. This space is monitored and included in our planning. Thanks very much!

**Comment by ScottWelker** [comment]
Done. Thank you.
https://developercommunity.visualstudio.com/idea/944714/exact-search-no-stemming-wiki.html
