### ISSUE TITLE
Needs to reference API information

### ISSUE THREAD

**Issue by MaxGuernseyIII** [MicrosoftDocs/vsts-docs#7455]
There should be a way to find the corresponding API for the entities created through this UI.

Alternatively, if there is no publicly-available API, that should be made very clear, in an easy-to-find way.

Either way, someone shouldn't have to scour this documentation for hours to obtain 90% confidence that there is no publicly-available API.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77d95db6-9983-7346-d0eb-4b7443e4e252
* Version Independent ID: 0a22cccc-318d-592f-d1ab-09ec01d88087
* Content: [Environment - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/environments?view=azure-devops#deployment-history)
* Content Source: [docs/pipelines/process/environments.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/environments.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by juliakm** [comment]
You can find our REST API here - https://docs.microsoft.com/en-us/rest/api/azure/devops/?view=azure-devops-rest-5.1. 

I'm adding an issue to our backlog to enhance the integration in the docs with the API docs.

**Comment by MaxGuernseyIII** [comment]
Yes. It is trivially easy to find the generic API documentation. Every search engine tells you that.

What nothing can tell you is whether or not there is a corresponding portion of the API for the UI elements documented on the referenced page. (Environment - Azure Pipelines)

If there is such an API that is publicly available, it should be easy to locate - probably with a link from the page.

If there is no such publicly-available API (which I strongly suspect to be the case). There should be a note to that effect. Something like "there is currently no API you can use to read or manipulate these data)" would have saved me hours of searching and will probably save the next person about as much time.

This should not be closed as it was not resolved.

**Comment by MaxGuernseyIII** [comment]
I guess if this is being transmuted to another backlog item, then it should be made clear in that item what the real problem is. It's not the absence of a link to https://docs.microsoft.com/en-us/rest/api/azure/devops/?view=azure-devops-rest-5.1. It is the absence of a definitive declaration that there is no publicly-available API for environments at this moment.
