### ISSUE TITLE
Incorrect statement VS 2019 has no load/web test project

### ISSUE THREAD

**Issue by RoyKimYYZ** [MicrosoftDocs/vsts-docs#7456]
I believe this statement is incorrect from my observation " Visual Studio 2019 will be the last version of Visual Studio containing web performance and load test features"
I could not find this in VS 2019. Online forums say the same thing. I only see it in VS 2017. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cde00a22-c654-f6e9-5bad-c4deb0852899
* Version Independent ID: 88ff6f31-199d-e3f6-bc68-be91dc695b0e
* Content: [Load test overview - Azure Test Plans](https://docs.microsoft.com/en-us/azure/devops/test/load-test/overview?view=azure-devops#feedback)
* Content Source: [docs/test/load-test/overview.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/test/load-test/overview.md)
* Product: **devops**
* Technology: **devops-test**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by cmw2** [comment]
I see it in my VS 2019.  You need Enterprise and you may need to Modify and specifically install that functionality.

**Comment by RoyKimYYZ** [comment]
I have enterprise and I tried to install that specific feature but could not find. But if you see it in your VS 2019, then I can’t debate.

Roy Kim
Microsoft Azure & Office 365 Consultant
Microsoft Azure MVP

**Comment by steved0x** [comment]
@RoyKimYYZ I'll see if I can find out the right combo to allow you to find it in VS 2019

**Comment by RoyKimYYZ** [comment]
I was able to find perf test project in VS 2019 enterprise.

So this is no longer a technical issue. But I think the documentation should be very clear and explicit that to install the perf tools you need to have Enterprise license.

In contrast, to VS 2017, with standard license, I am able to install and create a web/load test project but with a max virtual user of 250.

Therefore, this causes confusion.

As product feedback, I think this feature is still well used and I tried JMeter as the doc suggests and it is not very user friendly at all.


Roy Kim
Microsoft Azure & Office 365 Consultant
Microsoft Azure MVP

**Comment by PBoraMSFT** [comment]
@RoyKimYYZ - the need to install the web and load test components are documented in the load test creation doc in Visual Studio. https://docs.microsoft.com/en-us/visualstudio/test/quickstart-create-a-load-test-project?view=vs-2019

**Comment by RoyKimYYZ** [comment]
But my feedback is specific to this article: https://docs.microsoft.com/en-us/azure/devops/test/load-test/overview?view=azure-devops

Should be clear that enterprise edition is required in that article as well. Also, isn't it the case that you have to have license to see the perf test functionality as well? This is where I got confused.
