### ISSUE TITLE
Information invalid for Azure DevOps Server

### ISSUE THREAD

**Issue by nickwigton** [MicrosoftDocs/vsts-docs#7466]
This page lists the Import Work Items feature as being available for Azure DevOps Server, with the following text:

This feature is available with Azure DevOps Services, Azure DevOps Server 2019 Update 1, and later versions.

However this statement is not true. It is not available in Azure DevOps Server 2019 Update 1. A user opened an issue in Github stating that it was not available, and the response mentioned that they need to NOT be using Azure DevOps Server 2019 Update 1. If it is not an available feature, please remove the text from this page stating that it is available.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4296d1cc-f211-9d17-d97f-2b0858fdea7d
* Version Independent ID: cc66dfee-adde-cdfb-b3f5-5d58d89d3c81
* Content: [Import or update work items from a CSV file - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/queries/import-work-items-from-csv?view=azure-devops-2019#feedback)
* Content Source: [docs/boards/queries/import-work-items-from-csv.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/boards/queries/import-work-items-from-csv.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by nickwigton** [comment]
https://github.com/MicrosoftDocs/vsts-docs/issues/6949 is the closed issue from two months ago.

**Comment by KathrynEE** [comment]
@nickwigton - Thank you for the feedback. You are correct, the import feature isn't yet available for Azure DevOps Server 2019. I'm updating the article to reflect this change.
