### ISSUE TITLE
"Give teams and builds access to feeds"...

### ISSUE THREAD

**Issue by JamesMiera** [MicrosoftDocs/vsts-docs#747]
I somewhat looks like somebody might have been just about ready to include some useful information, and forgot what they were doing, or suffered a medical emergency. The lack of detailed information under the headers in that sub-section, as well as the suspiciously incomplete "how to" (EOD), might lead one to believe that this is a work in progress. Is there any chance that one might complete this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e77774e-012a-45cc-d566-7170d86003cd
* Version Independent ID: 778dafea-bf98-3292-f451-d82ce8db5bbc
* Content: [Secure and share packages using feed permissions](https://docs.microsoft.com/en-us/vsts/package/feeds/feed-permissions?view=vsts#give-teams-and-builds-access-to-feeds)
* Content Source: [docs/package/feeds/feed-permissions.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/package/feeds/feed-permissions.md)
* Service: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by elbatk** [comment]
Ah, yes this isn't quite what this page is supposed to look like @JamesMiera , I'll throw this on the backlog and get it fixed asap. @alexmullans for awareness

**Comment by bergmeister** [comment]
@elbatk Yes, please. We are in the situation where authentication on build servers does not seem to work across different VSTS accounts (when using NuGet to be specific) and have to figure out whether this is due to a malconfiguration on our side or not supported by VSTS (at the moment it seems to be due to the build server failing due to the AD login, which creates a popup)

**Comment by mason-mcglothlin** [comment]
@elbatk It's been over a month. And this still isn't fixed. Surely this wouldn't take more than an hour of someone's time to finish?

**Comment by bergmeister** [comment]
cc @xenalite

**Comment by alexmullans** [comment]
Sorry for the delay. Working across VSTS accounts with NuGet is a bit of a pain, frankly. We've got some features queued up that will make it better but they're still a ways out. We have an internal to Microsoft guide of how to use NuGet packages from one VSTS account in another VSTS account's build. I'll chat with @elbatk this week to see if we can get it cleaned up and published as public documentation.

**Comment by bergmeister** [comment]
cc @xenalite

**Comment by bergmeister** [comment]
@alexmullans We have also seen issues where it does not work if the VSTS accounts are hosted in different Azure regions (US and Europe to be specific)

**Comment by bogdanbanciu** [comment]
@alexmullans We also have issues where we can not restore private packages on our build server, please help

**Comment by alexmullans** [comment]
@bogdanbanciu can you post the issue on https://developercommunity.visualstudio.com/spaces/21/index.html?

**Comment by alexmullans** [comment]
@elbatk can you close this issue? The [permissions page](https://docs.microsoft.com/en-us/vsts/package/feeds/feed-permissions?view=vsts) has been fixed, and I've added a guide of doing [NuGet package restore across VSTS accounts here](https://docs.microsoft.com/en-us/vsts/pipelines/packages/nuget-restore?view=vsts#restoring-packages-from-feeds-in-a-different-account).

**Comment by elbatk** [comment]
Closing this issue :)
