### ISSUE TITLE
Leading with wildcard in pipeline trigger

### ISSUE THREAD

**Issue by AlexDenton** [MicrosoftDocs/vsts-docs#7474]
The docs show that you can do things like `release/*` but what if you wanted to do something like `*-release`?

From my experimentation it doesn't seem to be possible but can this be confirmed? And, if so, is there any intention to add this in the future?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5673ec1-c7d1-e0ac-043a-8fc3d5b226a9
* Version Independent ID: b4872831-51c0-6cf8-1c56-de20beb38a80
* Content: [Build pipeline triggers - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/triggers?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/build/triggers.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/build/triggers.md)
* Product: **devops**
* Technology: **devops-cicd-build**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
@AlexDenton The schema doesn't support it, if you try it in the editor you get the below, which is the supported pattern (ok now that I look at it, I don't see the `*` excluded... but I am not an expert on regex).

Please feel this as a bug/feature request [here](https://developercommunity.visualstudio.com/spaces/21/index.html) and I am giving a heads up to the team to be on the lookout for it, and to let me know if I need to update the docs for this page.


![image](https://user-images.githubusercontent.com/1580889/76230097-9606cb00-61f9-11ea-839d-b846b0c6da16.png)

**Comment by steved0x** [comment]
@AlexDenton I found out it is supported, but if leading with a wildcard it must be wrapped in quotes like this:

![image](https://user-images.githubusercontent.com/1580889/76241363-36b1b680-620b-11ea-96fd-edcd60f55bc2.png)

I'll make a note in the documentation. Thank you for reporting this and sorry that you ran into trouble.

**Comment by AlexDenton** [comment]
@steved0x Well, sorry I missed the response on this but hopefully my delayed appreciation is better than none. Thanks for looking into this! Glad to hear it's supported.
