### ISSUE TITLE
Documentation for "Required Template" approval missing

### ISSUE THREAD

**Issue by imphil** [MicrosoftDocs/vsts-docs#7476]
There is a approval type "Required template", which seems to allow one to require a specific template for an agent. Unfortunately, it's not documented, and it doesn't work as I'd expect it to work. How is this feature supposed to be used?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b067a175-f640-7503-9c1e-f0130c6dbeda
* Version Independent ID: ff743c7b-a103-eae6-4478-62ba995a4b36
* Content: [Pipeline deployment approvals - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/approvals?view=azure-devops&tabs=check-pass)
* Content Source: [docs/pipelines/process/approvals.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/approvals.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @azooinmyluggage
* Microsoft Alias: **shashban**

**Comment by adriantorrie** [comment]
It doesn't even looks like it works properly either.

[Comment on #7235](https://github.com/MicrosoftDocs/vsts-docs/issues/7235#issuecomment-594372221)
