### ISSUE TITLE
Porting to TFS 2018?

### ISSUE THREAD

**Issue by nikolaiblackie** [MicrosoftDocs/vsts-docs#748]
Is it possible to manually install this tool task on TFS 2018 or does it have to be shipped by MS in an update?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6cdab61-a70b-e725-cd74-f258620447b7
* Version Independent ID: ee1753a6-2b6c-8304-5cba-73b86606ebb3
* Content: [Visual Studio Test Platform Installer](https://docs.microsoft.com/en-us/vsts/build-release/tasks/tool/vstestplatformtoolinstaller.1?view=vsts)
* Content Source: [docs/build-release/tasks/tool/VsTestPlatformToolInstaller.1.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/build-release/tasks/tool/VsTestPlatformToolInstaller.1.md)
* Service: **devops**
* GitHub Login: @erickson-doug
* Microsoft Alias: **dastahel**

**Comment by steved0x** [comment]
@DavidStaheli Can you take a look at this one? Thank you!

**Comment by PBoraMSFT** [comment]
@nikolaiblackie - sorry this took a while to get routed to me. The platform installer task cannot be used on TFS 2018 by installing manually. There are other changes in the system necessary to have it work correctly. It has shipped in TFS 2018 updates.
