### ISSUE TITLE
DEBIAN_FRONTEND=noninteractive ARG instead of ENV?

### ISSUE THREAD

**Issue by zoekdestep** [MicrosoftDocs/vsts-docs#7483]
Regarding this doc: [https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/docker?view=azure-devops](url)

Recently have been reading some discussions on ENV DEBIAN_FRONTEND=noninteractive, as in [https://github.com/moby/moby/issues/4032](url) and [https://github.com/grafana/grafana/pull/20196/commits/2b7487579b5f79a74d68e5cbd6f](url). 

In:
`FROM ubuntu:16.04`
`ENV DEBIAN_FRONTEND=noninteractive`
`RUN echo "APT::Get::Assume-Yes \"true\";" > /etc/apt/apt.conf.d/90assumeyes`

Shouldn't ENV be replaced by ARG? As ENV makes the variable persist in the final image, while ARG makes sure it's only set during build?

**Comment by steved0x** [comment]
@zoekdestep I will find out and if so we will update the docs. Thank you for your feedback.

**Comment by vtbassmatt** [comment]
The idea was that some pipelines run `apt` or `apt-get` as part of their normal flow. By setting this variable and having it persist into the final image, that works more smoothly.
