### ISSUE TITLE
Should include info about using for and each to build proper build matrices

### ISSUE THREAD

**Issue by JustinGrote** [MicrosoftDocs/vsts-docs#7486]
In absense of the AzDevops Matrix keyword not doing job scaleout like the Github Actions version does, this document should include information about using the each keyword as a workaround. Example:
https://github.com/microsoft/azure-pipelines-yaml/issues/20#issuecomment-594415636

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7458d5b2-1bb7-7d87-7ce6-2b0c430b0155
* Version Independent ID: edf5bbd3-a3f0-5426-e985-31290f8afd05
* Content: [YAML schema - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema%2Cparameter-schema#feedback)
* Content Source: [docs/pipelines/yaml-schema.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/yaml-schema.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
@JustinGrote Thank you for the feedback, I am reaching out to the product team to see if we can get something added.
