### ISSUE TITLE
Users?

### ISSUE THREAD

**Issue by JohnStraumann66** [MicrosoftDocs/vsts-docs#7487]
Do DevOps users have to have a MSFT or Github account? Can a corporate Office 365 email be used?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c985016-9453-7c7f-bbbd-39252037b807
* Version Independent ID: ea8f7d65-dc88-d11d-4358-ac7b31a20827
* Content: [Start using Azure Boards - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/get-started/sign-up-invite-teammates?view=azure-devops)
* Content Source: [docs/boards/get-started/sign-up-invite-teammates.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/boards/get-started/sign-up-invite-teammates.md)
* Product: **devops**
* Technology: **devops-new-user**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by WilliamAntonRohm** [comment]
@JohnStraumann66 -- my understanding is that only Microsoft or GitHub accounts can be used.

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
