### ISSUE TITLE
Please be more specific about lifetimes of VssConnection

### ISSUE THREAD

**Issue by leotsarev** [MicrosoftDocs/vsts-docs#7489]
From documentation and decompiled code of VssConnection it seems that VssConnection SHOULD be created once per application and freely reused between threads. If so, could you please document it? I.e. in the comment 
`// Create a connection object, which we will use to get httpclient objects.  This is more robust`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aa8505e8-cef0-fee8-866a-e000058ac233
* Version Independent ID: d6858ee2-4282-b4e1-fb3b-e8b531b950b7
* Content: [.NET Client Library Samples for Azure DevOps Services - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/integrate/get-started/client-libraries/samples?view=azure-devops)
* Content Source: [docs/integrate/get-started/client-libraries/samples.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/integrate/get-started/client-libraries/samples.md)
* Product: **devops**
* Technology: **devops-ecosystem**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by leotsarev** [comment]
If I'm right, I could send PR to documentation if you want, I just need someone to confirm/reject my conclusion

**Comment by chcomley** [comment]
Hi @leotsarev, Thanks for reaching out. I'm looking into this and will get back to you soon.

**Comment by chcomley** [comment]
Hi @leotsarev, You're right that the VssConnection should be created once per application. Feel free to submit an update, or I can do it. Whichever you prefer. Thanks very much!
