### ISSUE TITLE
Example connect database local server 

### ISSUE THREAD

**Issue by franciszcko** [MicrosoftDocs/vsts-docs#7491]
Hi 

I try run unit test on Microservice build in node, but the Microservice don't  have connectivity  with database in local server (private net).
What I Need for like azure devops has connectivity   with database in local server (private net)

**Comment by WilliamAntonRohm** [comment]
@franciszcko -- Thanks for your feedback; we appreciate it. To make sure we have all the information needed to triage your issue, please let us know which topic you’re referencing, or provide more context around your general task.
