### ISSUE TITLE
Unclear documentation for powershell shortcuts

### ISSUE THREAD

**Issue by robertlarkins** [MicrosoftDocs/vsts-docs#7493]
There is unclear information about what agents Powershell can run on. In the Yaml snippet for `PowerShell@2` it says `# Run a PowerShell script on Linux, macOS, or Windows` which implies it will work on all agents. Then further down in has for the two shortcuts (`powershell` and `pwsh`):

> Both of these resolve to the PowerShell@2 task. `powershell` runs Windows PowerShell and will only work on a Windows agent. `pwsh` runs PowerShell Core, which must be available on the agent or container.
> This task will select the version of PowerShell or PowerShell Core that's available on the agent.

Do the two shortcuts resolve to `PowerShell@2` which should work on all Microsoft-Hosted agents, or does it choose a powershell type based on what is available on the agent, or do they individually target different powershell types (powershell and powershell core)?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a0e444c2-69c6-4d71-6fd0-94d0f4097d3a
* Version Independent ID: 3a727833-1cc3-c2fb-c5b3-22605eee2721
* Content: [PowerShell task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/powershell?view=azure-devops#feedback)
* Content Source: [docs/pipelines/tasks/utility/powershell.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/utility/powershell.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @vtbassmatt
* Microsoft Alias: **macoope**

**Comment by vtbassmatt** [comment]
They both resolve to the `PowerShell@2` task with appropriate task inputs set to choose PowerShell or PowerShell Core. It doesn't bind to a particular version number of those, which is what the line about "chooses a version available" refers to. Either form will work on hosted agents. I'll see if we can make this clearer in the docs.
