### ISSUE TITLE
Is this contradictory advice?

### ISSUE THREAD

**Issue by jeremydeal** [MicrosoftDocs/vsts-docs#7498]
The example for Node.js/npm cache uses npm ci, then a tip underneath says "Because npm ci deletes the node_modules folder to ensure that a consistent, repeatable set of modules is used, you should avoid caching node_modules when calling npm ci." I may be misunderstanding, but if this is a contradiction, perhaps the code should reflect the best practice.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77c20289-dab2-7a6e-4f63-4b30eaff2c71
* Version Independent ID: d75cc196-90c1-8291-9907-ff405bde4edf
* Content: [Pipeline caching - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/caching?view=azure-devops#feedback)
* Content Source: [docs/pipelines/release/caching.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/release/caching.md)
* Product: **devops**
* Technology: **devops-cicd-release**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**

**Comment by EvtK** [comment]
Hi Jeremy, this has been answered already:
https://github.com/MicrosoftDocs/vsts-docs/issues/5572

but I have to say I was lost there also :)

**Comment by ramiMSFT** [comment]
@EvtK Thank you for your answer

@jeremydeal Thank you for your feedback. Here is a very good explanation from one of our program managers:
> 
> * The example shows best practice: cache the global NPM cache folder -- `$(npm_config_cache)` -- and use `npm ci` to install packages. `npm ci` will create and populate `node_modules` based on packages found in the global cache (i.e. the folder possibly restored from the cache) and/or packages downloaded from npmjs.
> * The "tip" points out that because `npm ci` deletes `node_modules`, it wouldn't make sense to cache `node_modules` and also use `npm ci` since any cache restored into `node_modules` will be immediately deleted when `npm ci` runs.
>
