### ISSUE TITLE
There is no Multi-configuration under Options

### ISSUE THREAD

**Issue by TerryChan** [MicrosoftDocs/vsts-docs#750]
I didn‘t find Multi-configuration under Options tab, but I found it under Tasks in Phase1->Execution plan. And after I set it under Tasks, the build works well.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0fa5a83c-70fd-6925-a8c8-256b21c21a2e
* Version Independent ID: 75f4a136-7245-7878-2953-6b68272fe4ec
* Content: [Build definition options](https://docs.microsoft.com/en-us/vsts/build-release/concepts/definitions/build/options?view=vsts#multi-configuration)
* Content Source: [docs/build-release/concepts/definitions/build/options.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/build-release/concepts/definitions/build/options.md)
* Service: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by andyjlewis** [comment]
Thanks for the feedback. We've got an update on the way.

**Comment by steved0x** [comment]
Content refactored, info is here: https://docs.microsoft.com/en-us/azure/devops/pipelines/process/phases?view=azure-devops&tabs=yaml#multi-configuration
