### ISSUE TITLE
Cannot move a shared query between folders

### ISSUE THREAD

**Issue by GaTechThomas** [MicrosoftDocs/vsts-docs#7502]
When trying to move a query between folders underneath the Shared Queries folder, we get error "TF401256: You do not have Write permissions for query MyQueryName". Queries have no "Write" permission option.

After a bit of trial and error, we found that moving between folders requires the Delete permission on the query to be moved. I gather that "move" is implemented as "copy/delete". Something should be cleaned up here: either rework the error message, document the permissions needed, or rework the behavior. 

Please and thank you. :-)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 54179351-62b2-c41b-949b-0652a0f1d354
* Version Independent ID: 1ffcd0b3-e67b-6cfe-caa6-814a699627db
* Content: [Set query permissions - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/queries/set-query-permissions?view=azure-devops)
* Content Source: [docs/boards/queries/set-query-permissions.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/boards/queries/set-query-permissions.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@GaTechThomas - Thank you for the feedback. I'll update the article to clarify and pass the feedback on the error message to the product team.
