### ISSUE TITLE
Repository Limits

### ISSUE THREAD

**Issue by jeffpatton1971** [MicrosoftDocs/vsts-docs#7506]
Team, looking for clarification on upper limits if any on number repositories per project.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8327ce3e-a6f7-74ba-7cc0-95885c247a75
* Version Independent ID: ae36a4ea-20cb-4f29-e760-8f6c362c5a47
* Content: [About projects and scaling your organization - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/projects/about-projects?view=azure-devops#feedback)
* Content Source: [docs/organizations/projects/about-projects.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/projects/about-projects.md)
* Product: **devops**
* Technology: **devops-new-user**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @jeffpatton1971, Thanks for reaching out. I'm looking into this and will be in touch soon.

**Comment by jeffpatton1971** [comment]
@chcomley thanks for reaching out, look forward to see if there is a limit or not

**Comment by scottmwyant** [comment]
Also interested in this answer.

**Comment by chcomley** [comment]
Hi @jeffpatton1971 and @scottmwyant, 
There's a registry setting that can be used to limit repositories, but if that's not set, it defaults to Int32.MaxValue or over 2 billion. But, for several orders of magnitude approaching the technical limit, developers may not love the user experience. Please exercise good judgement. Thanks! Please @mention me if you have any follow up questions. Thank you!

**Comment by jeffpatton1971** [comment]
@chcomley This was in Azure DevOps, to my knowledge there is no registry setting that is accessible there. Perhaps you were thinking Devops Server? TFS?

**Comment by chcomley** [comment]
There's a registry setting for Azure DevOps, configurable by our engineers, but defaults to int max (over 2 billion). Even thousands of repos would become difficult to deal with, so please consider how many you choose to add. Thanks very much!
