### ISSUE TITLE
No prerequisite information provided for blob data copy

### ISSUE THREAD

**Issue by Tarvinder91** [MicrosoftDocs/vsts-docs#7507]
There is no information on what are the prerequisites for authentication for copying the data to blob storage. The copy doesn't work when this job is run on vsts2016 agent. No option to use SAS token either. Could you cover some scenarios with some examples?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 622daa35-c6a1-dac3-17ee-3f9308fc60cd
* Version Independent ID: 2c28a59b-8ef5-d7ab-46a6-58748ec552f5
* Content: [Azure File Copy task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-file-copy?view=azure-devops)
* Content Source: [docs/pipelines/tasks/deploy/azure-file-copy.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/deploy/azure-file-copy.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by ninallam** [comment]
The task supports authentication based on Azure Active Directory. Authentication using a service principal and managed identity are available. For managed identities, only system-wide managed identity is supported.

For authorization you will have to provide access to the Security Principal. The level of authorization required can be referred [here](https://docs.microsoft.com/azure/storage/common/storage-use-azcopy-v10#option-1-use-azure-active-directory)
