### ISSUE TITLE
Please show an example of how `=[Field]` works. 

### ISSUE THREAD

**Issue by StingyJack** [MicrosoftDocs/vsts-docs#7509]
If i wanted to find where `Original Estimate` was equal to `Remaining Work` what does the actual query look like. 

`Original Estimate =[Field]  Remaining Work`?
`Original Estimate = [Remaining Work]`?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a718268-1105-4def-5f9e-20ea21afc0d7
* Version Independent ID: 0f08fa18-3075-4275-22c7-d5d1c1e260b0
* Content: [Query fields, operators, and macros/variables - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/queries/query-operators-variables?view=azure-devops)
* Content Source: [docs/boards/queries/query-operators-variables.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/boards/queries/query-operators-variables.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@StingyJack - The following query can be used. The last clause eliminates those fields that are blank or set to 0.

![image](https://user-images.githubusercontent.com/10856840/76117993-cc4a0d80-5fa1-11ea-9550-7fa2d014dd4b.png)

**Comment by StingyJack** [comment]
Sorry, I thought I was on the Wiql page
