### ISSUE TITLE
Mean Times

### ISSUE THREAD

**Issue by CyberJMC66** [MicrosoftDocs/vsts-docs#751]
Sam, I like your comments around MTTM and MTTR - I speak to Mean Time to Detect (MTTD) and Mean Time to Identify. Obviously both MTTD and MTTI if reduced to near zero, result in quick action because automation has detected and identified failures and either attempted automated recovery, or has notified appropriate owners of defect.  Thoughts? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 389d9a0a-8068-d3b3-9386-ee2be9e2d04b
* Version Independent ID: 443ad32b-8d5d-5ed6-ca54-37765d6f3a50
* Content: [What is DevOps Culture? - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/what-is-devops-culture)
* Content Source: [https://mseng.visualstudio.com/DefaultCollection/TechnicalContent/_git/devops-learn-pr?path=%2fdocs%2fwhat-is-devops-culture.md&version=GBlive&_a=contents](https://mseng.visualstudio.com/DefaultCollection/TechnicalContent/_git/devops-learn-pr?path=%2fdocs%2fwhat-is-devops-culture.md&version=GBlive&_a=contents)
* Service: **devops**
* GitHub Login: @samgu
* Microsoft Alias: **samgu**

**Comment by steved0x** [comment]
@samgu can you take a look at this one?

**Comment by steved0x** [comment]
@CyberJMC66 I have forwarded your feedback to Sam and if I get a reply I'll add it here. Thank you for your feedback.
