### ISSUE TITLE
run $project=xxxx failed

### ISSUE THREAD

**Issue by risingwen** [MicrosoftDocs/vsts-docs#7513]
[Enter feedback here]
+ ... view.3" -UseDefaultCredentials).value | where > name -eq $projectName
+                                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Where-Object]，PSArgumentException
    + FullyQualifiedErrorId : ValueNotSpecifiedForWhereObject,Microsoft.PowerShell.Commands.WhereObjectCommand
![image](https://user-images.githubusercontent.com/6387840/76050515-98231c80-5fa2-11ea-890d-db3314770731.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 93b1cf79-de4e-500b-388a-64665e3af89b
* Version Independent ID: 2cdda8ac-9e42-eed7-8d0c-9ab8dfc2c5f8
* Content: [Restore a project - Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/organizations/projects/restore-project?view=azure-devops-2019#feedback)
* Content Source: [docs/organizations/projects/restore-project.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/projects/restore-project.md)
* Product: **devops**
* Technology: **devops-accounts**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by WilliamAntonRohm** [comment]
@risingwen -- Thanks for your feedback; we appreciate it. To make sure we have all the information needed to triage your issue, please provide more context around your general task.
