### ISSUE TITLE
Runtime parameters not working as described

### ISSUE THREAD

**Issue by jason-ha** [MicrosoftDocs/vsts-docs#7514]
Please see #6588. This issue added so readers my find that issue from this page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 790318bb-8220-3241-4ca7-73351074492f
* Version Independent ID: db1da9db-3694-779b-17aa-1ed67fcecf86
* Content: [Use runtime and type-safe parameters - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/runtime-parameters?view=azure-devops#feedback)
* Content Source: [docs/pipelines/process/runtime-parameters.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/runtime-parameters.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by WilliamAntonRohm** [comment]
@jason-ha -- Jason, thank you for your feedback.

@juliakm -- Julia, please look into the referenced issue #6588.

**Comment by vbrinza** [comment]
same here

**Comment by wsmckenz** [comment]
I am having the same issue. Is there a feature flag that enables this, maybe?

**Comment by juliakm** [comment]
Sorry for the confusion. This is not rolled out to all customers yet. I've added a warning at the top of the article to make that clear.

**Comment by chenghuang-mdsol** [comment]
@juliakm What do you mean? I didn't see anything changed in the doc. Do you mean runtime parameter in pipeline is not yet shipped? If not, how do I enable it?

**Comment by wsmckenz** [comment]
I think this means it is deployed to some "rings" but not all.

**Comment by juliakm** [comment]
@wsmckenz is correct. It is not shipped yet but should be soon.

**Comment by sderungs** [comment]
@juliakm is there an ETA for this? would really come in handy now (at least as preview feature that could be enabled on the org)

**Comment by philipktlin** [comment]
how I know this feature already deployed for my organization?

**Comment by chenghuang-mdsol** [comment]
@philipktlin try it, if it's not shipped to your org, you get an error "Pipeline parameters not enabled" when you run.

**Comment by aodugga** [comment]
Hi @juliakm , just wanted to check if we have an ETA on this please?
