### ISSUE TITLE
Extensibility point on release page

### ISSUE THREAD

**Issue by tovVAar** [MicrosoftDocs/vsts-docs#7515]
![image](https://user-images.githubusercontent.com/4789492/76055846-9cf7ba00-5f29-11ea-824e-391c97471988.png)
Hello, I am part of VS performance team, I need to create a new tab for the Release result page, previously it was possible with the target _ms.vss-releaseManagement-web.release-details-view_ but that no longer works on the new experience, do you know how the contribution configuration should look?, this is what I have so far:
```

           "id": "pit-tab",
            "type": "ms.vss-releaseManagement-web.release-summary-tab",
            "targets": [
                "ms.vss-releaseManagement-web.release-details-view"
            ],
            "properties": {
                "name": "Performance",
                "uri": "dist/index.html",
                "order": "99",
                "icon": "asset://static/sample-icon.png",
                "supportsMobile": true
            }
```

**Comment by WilliamAntonRohm** [comment]
@tovVAar -- Erick, thank you for your feedback; we appreciate it. To make sure we have all the information needed to triage your issue, please let us know which topic you’re referencing, or provide more context around your general task.
