### ISSUE TITLE
Typo in the script output

### ISSUE THREAD

**Issue by Madsteph** [MicrosoftDocs/vsts-docs#7522]
In the section 'Repository declared using a repository resource' the script output should be 'CurrentRepo MyAzureReposGitRepository MyBitBucketRepo MyGitHubRepo'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a0499c0-bd1c-47a0-b472-54a5d6c159b4
* Version Independent ID: ec3feae0-4f23-68ab-6307-75fde645468a
* Content: [Check out multiple repositories in your pipeline - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/multi-repo-checkout?view=azure-devops)
* Content Source: [docs/pipelines/repos/multi-repo-checkout.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/repos/multi-repo-checkout.md)
* Product: **devops**
* Technology: **devops-cicd-repos**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by WilliamAntonRohm** [comment]
@steved0x -- please review the above-mentioned PR 1082.

**Comment by steved0x** [comment]
@Madsteph The output in the sample is correct, the `repository` attribute in the YAML is used only for referring to the repo from the pipeline, the actual name of the repo is used for the folder name. I'll add a note to clarify that.
