### ISSUE TITLE
Documentation is wrong about batch being true by default

### ISSUE THREAD

**Issue by Slooz** [MicrosoftDocs/vsts-docs#7525]
The documentation says the following:

>     batch: boolean # batch changes if true (the default); start a new build for every push if false

This is wrong. `batch` is `false` by default.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7458d5b2-1bb7-7d87-7ce6-2b0c430b0155
* Version Independent ID: edf5bbd3-a3f0-5426-e985-31290f8afd05
* Content: [YAML schema - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema%2Cparameter-schema#stage)
* Content Source: [docs/pipelines/yaml-schema.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/yaml-schema.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by msebolt** [comment]
@Slooz  Thank you for the feedback, the documentation has been updated and is now pending review.

Make your contributions count and consider [becoming a contributor](https://docs.microsoft.com/contribute).

@steved0x
