### ISSUE TITLE
MultiConfiguration no longer on the Options tab

### ISSUE THREAD

**Issue by shaynemarriage** [MicrosoftDocs/vsts-docs#7526]
The MultiConfiguration setting has been moved to the Execution Plan section of the agent job (previously agent phase).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bf775750-39ed-42b1-db31-7c7bc1eece00
* Version Independent ID: a02d6d49-37f9-27d4-c4af-efb735f18966
* Content: [Visual Studio Build build and release task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/visual-studio-build?view=azure-devops#feedback)
* Content Source: [docs/pipelines/tasks/build/visual-studio-build.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/build/visual-studio-build.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @vijayma
* Microsoft Alias: **vijayma**

**Comment by msebolt** [comment]
@shaynemarriage  Thank you for the feedback, the documentation has been revised and is currently pending review.

Please consider [becoming a contributor](https://docs.microsoft.com/contribute).

@vijayma
