### ISSUE TITLE
Please consider adding standard Markdown language tags

### ISSUE THREAD

**Issue by frankshearar** [MicrosoftDocs/vsts-docs#7530]
It's great that I can embed Mermaid diagrams in wiki pages, except that the rest of the world uses ````mermaid to do so. Please also consider making this change in the Preview pane of a file. Right now I have to choose whether to have decent Mermaid support in VS Code, OR in ADO.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 29f1e43f-a069-dd88-7fc7-9cc497fb94f0
* Version Independent ID: c261afa7-6eb7-b3f0-9f92-6d2f3c5ac336
* Content: [Markdown syntax for wikis in Azure DevOps - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/project/wiki/wiki-markdown-guidance?view=azure-devops#feedback)
* Content Source: [docs/project/wiki/wiki-markdown-guidance.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/project/wiki/wiki-markdown-guidance.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by msebolt** [comment]
@frankshearar Thank you for the feedback.

The product team currently has an open issue on this [here](https://developercommunity.visualstudio.com/idea/826044/mermaid-use-the-code-blog-identifier-istead-of-a-c.html).

Please refer there for current status and updates, or to vote and add additional comments.

**Comment by WilliamAntonRohm** [comment]
I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
