### ISSUE TITLE
System.PullRequest.PullRequestId is not populated when manually run a pipeline

### ISSUE THREAD

**Issue by haroldrandom** [MicrosoftDocs/vsts-docs#7532]
System.PullRequest.PullRequestId is populated with correct value only when Pull Request is created or "/azp run"

I would like to get the System.PullRequest.PullRequestId variable with the correct value set no matter what measures I trigger to run a pipeline.

Is it possible?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 11d3469c-83c2-c2f6-41d0-08f82c330bbc
* Version Independent ID: a373c48d-6395-3002-d2d8-bbc1fea2e48e
* Content: [Predefined variables - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/build/variables.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/build/variables.md)
* Product: **devops**
* Technology: **devops-cicd-build**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by msebolt** [comment]
@haroldrandom Thank you for the question.

Unfortunately our support options are limited in this forum to documentation examples only.

Please use **Report a problem** or **Suggest a feature** in the [Azure DevOps community](https://developercommunity.visualstudio.com/spaces/21/index.html) where the product team can better address this issue.

Or, for additional support options, refer to:

- [Azure DevOps Support](https://azure.microsoft.com/support/devops/)
- [Azure DevOps on StackOverflow](https://stackoverflow.com/questions/tagged/azure-devops)

@juliakm

**Comment by WilliamAntonRohm** [comment]
I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
