### ISSUE TITLE
Placeholders not working for all event data

### ISSUE THREAD

**Issue by be-studio** [MicrosoftDocs/vsts-docs#7533]
When I use the Trello service hook to create a card on Git push although I can use the `message` and `detailedMessage` properties of the event JSON in placeholders, I cannot access any other properties such as `resource` and importantly the nested `commits` array.

As an example if I try `{{message.text}}` I get a message text, but if I try `{{createdDate}}` as per the event JSON I get nothing.

 Is this an intentional break or a bug? Can this be investigated and resolved?

**Reference:** https://docs.microsoft.com/en-us/azure/devops/service-hooks/events?view=azure-devops#code

**Comment by msebolt** [comment]
@be-studio  Thank you for the question.

Unfortunately our support options are limited to specific examples, such as the [Trello service hooks example](https://docs.microsoft.com/azure/devops/service-hooks/services/trello), where we can directly assign the author for review.

For product issues, please use **Report a problem** in the [Azure DevOps community](https://developercommunity.visualstudio.com/spaces/21/index.html) to solicit feedback direclty from the product team.  

You can also refer [here](https://developercommunity.visualstudio.com/search.html?f=&type=question+OR+problem+OR+idea&type=question+OR+problem+OR+idea&c=&redirect=search%2Fsearch&sort=relevance&q=trello) for the list of current Trello issues, or try:

- [Azure DevOps Support](https://azure.microsoft.com/support/devops/)
- [Azure DevOps on StackOverflow](https://stackoverflow.com/questions/tagged/azure-devops)

**Comment by WilliamAntonRohm** [comment]
I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
