### ISSUE TITLE
Code search does not work as described here

### ISSUE THREAD

**Issue by PalleDue** [MicrosoftDocs/vsts-docs#7538]
Code search disregards escaped double quotes. For instance this search term:

"\"name\""

finds all occurences of name, whether they are quotet or not.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 12512a47-a85e-736e-9045-3004b4459d95
* Version Independent ID: c7a4b27e-5b68-1e07-527c-cb357eb53b3b
* Content: [Use advanced code search options - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/project/search/advanced-code-search-syntax?view=azure-devops#feedback)
* Content Source: [docs/project/search/advanced-code-search-syntax.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/project/search/advanced-code-search-syntax.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by WilliamAntonRohm** [comment]
@PalleDue -- thank you for your feedback.  That article goes on to say:

- Search for a literal occurrence of the double-quote character " by preceding it with the escape character \ and enclosing the search string in double-quotes. For example, "\"react-redux\"" will find the literal string "react-redux".

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.

**Comment by PalleDue** [comment]
@WilliamAntonRohm : I see that the backslashes disappeared both in my original comment and in your reply.
"(backslash)"name(backslash)"" finds all occurences of name, not just the quoted ones.
