### ISSUE TITLE
Getting storage account not found error during deployment.

### ISSUE THREAD

**Issue by gdprtcl** [MicrosoftDocs/vsts-docs#7539]
I am getting the following issue when I do a Function App Deployment.
<img width="816" alt="Screenshot 2020-03-09 at 6 41 12 PM" src="https://user-images.githubusercontent.com/19777169/76215843-9329cb80-6235-11ea-852d-9e8adb6c2139.png">
Is there any argument/parameter I need to add for the storage account in the azure-pipelines.yml file?

**Comment by WilliamAntonRohm** [comment]
@gdprtcl -- Partha, thank you for your feedback; we appreciate it. To make sure we have all the information needed to triage your issue, please let us know which docs.microsoft.com topic you’re referencing, or provide more context around your general task.
