### ISSUE TITLE
Spot on, but not for novice

### ISSUE THREAD

**Issue by GregTrevellick** [MicrosoftDocs/vsts-docs#754]
Ok for me to follow, experienced with VS, vsix, node etc but perhaps need a beginner version and experienced version of this doc

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 14955ee9-29f2-46fe-3a8d-a42666f53ffc
* Version Independent ID: 5d417cd0-a671-ee30-8fca-5f8b0addd328
* Content: [Write your first extension for VSTS](https://docs.microsoft.com/en-us/vsts/extend/get-started/node?view=vsts)
* Content Source: [docs/extend/get-started/node.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/extend/get-started/node.md)
* Service: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by GregTrevellick** [comment]
Closing as this isn't an issue, just a comment

**Comment by elbatk** [comment]
@GregTrevellick I appreciate the feedback, I agree completely so I'lll round up the product team and see if we can't make this content a little more accessible to beginners.
