### ISSUE TITLE
Documentation for 'Edit instance-level information' wrong?

### ISSUE THREAD

**Issue by SebastianSchuetze** [MicrosoftDocs/vsts-docs#7542]
This permission (Edit instance-level information) lists permission like create and modify areas & iterations.
But when I give this permission on organization level to a specific user. The only difference I can see is, that this user can edit permissions on other users and security groups.

Is the documentation wrong or the business logic of Azure DevOps

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c399d3d3-3442-91a7-eb72-f0451b735cd1
* Version Independent ID: 5c4f77ec-5ef8-afe7-8e96-f1b4238f8f44
* Content: [Permissions and role lookup guide - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/security/permissions-lookup-guide?view=azure-devops#feedback)
* Content Source: [docs/organizations/security/permissions-lookup-guide.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/security/permissions-lookup-guide.md)
* Product: **devops**
* Technology: **devops-security**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@SebastianSchuetze - Thank you for your inquiry. I will check with the product team and update the relevant documentation soon.

**Comment by KathrynEE** [comment]
@@SebastianSchuetze - just a follow up, you are correct. The Edit instance-level information was wrong. It primarily supports allowing a user to add/remove security groups and permissions.

**Comment by SebastianSchuetze** [comment]
Cool. Has the documentation been updated or should I PR this myself?
