### ISSUE TITLE
Slight Clarification to the important note at the start of the page

### ISSUE THREAD

**Issue by SamGrantham** [MicrosoftDocs/vsts-docs#7544]
Hi team,
The meaning of the first Note is a bit ambiguous, we switch between integration is not supported and support is deprecated, and though they mean the same thing it causes it to be less clear as to what is and isn't supported, would it be possible to change this so that it reads more easily?

Maybe a format like:

> Important
> Microsoft Project Integration is deprecated as of:
>
>- Visual Studio 2019 and Azure DevOps Office® Integration 2019.  
>- Azure DevOps Services and Azure DevOps Server 2019. 
>
>However, full support for Microsoft Excel integration is maintained and is the recommended alternative.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4f6edd47-46d7-ab0d-db47-d73bc45d6b43
* Version Independent ID: 6ac2ae49-0bd0-2c28-fc87-7f034dd96443
* Content: [Create your backlog and tasks using Microsoft Project - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/backlogs/office/create-your-backlog-tasks-using-project?view=tfs-2018&tabs=office-365&viewFallbackFrom=azure-devops)
* Content Source: [docs/boards/backlogs/office/create-your-backlog-tasks-using-project.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/boards/backlogs/office/create-your-backlog-tasks-using-project.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by SamGrantham** [comment]
It's worth noting, though maybe beyond the scope of this documentation that _Deprecated_ does not mean that it doesn't work in this scenario.  There are (at least currently) ways to still get this to work, but it's not _Supported_ so if it breaks there isn't anything we can do if you call support ffor help.

**Comment by KathrynEE** [comment]
@SamGrantham - Thank you for the feedback. I'm updating the article per your recommendation.
