### ISSUE TITLE
Betta Azure 101 

### ISSUE THREAD

**Issue by lukeenterprise** [MicrosoftDocs/vsts-docs#7546]
Thank you for your feedback!

The issues in this repo are for documentation feedback.

If you are submitting your documentation feedback issue directly through GitHub, please provide the URL of the article so we can route the feedback to the correct author.

Please report Azure DevOps or TFS software bugs, feedback, or questions in the [Azure DevOps Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html).

**Comment by WilliamAntonRohm** [comment]
@lukeenterprise, thank you for your feedback; we appreciate it. To make sure we have all the information needed to triage your issue, please let us know which docs.microsoft.com topic you’re referencing, or provide more context around your general task.
