### ISSUE TITLE
Incomplete sentence

### ISSUE THREAD

**Issue by dharmababa** [MicrosoftDocs/vsts-docs#7565]
Under #5 below, it says: "If the Forecasting bar doesn't appear." Seems like an incomplete sentence.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9e47f8c5-7b66-ec49-a03c-1240ad9fe4f0
* Version Independent ID: 21551259-e300-329a-3ce1-95dbb4730bc5
* Content: [Forecasting - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/sprints/forecast?view=azure-devops&tabs=vertical&viewFallbackFrom=vsts#feedback)
* Content Source: [docs/boards/sprints/forecast.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/boards/sprints/forecast.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@dharmababa - Thank you for the feedback. I'm updating the article to remove the incomplete sentence.
