### ISSUE TITLE
Fix 'only leaf nodes showing' for bug-task hierarchies. 

### ISSUE THREAD

**Issue by WaterSibilantFalling** [MicrosoftDocs/vsts-docs#7566]
There is no reason for only leaf nodes to show. It is a bug and Microsoft or their programming contractor company should fix it straight away. 

> Is there a workaround to display intermediate nodes within a hierarchy? Not at this time. You can always check the entire list of items assigned to a sprint by using the Create Query link.

The is also no reason for Azure's repeated requests that their customers avoid same-level (task-task, bug-bug . . .) dependencies. Such dependencies are a common,  everyday occurrence and their lack of support is a bug that should have been fixed years ago. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 12c0f3ea-b59f-1f67-b0be-dfb773aafab0
* Version Independent ID: d5c25240-899d-e9b7-c4f5-1f157bcaa515
* Content: [Fix backlog reorder and nesting issues - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/backlogs/resolve-backlog-reorder-issues?view=azure-devops)
* Content Source: [docs/boards/backlogs/resolve-backlog-reorder-issues.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/boards/backlogs/resolve-backlog-reorder-issues.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by WilliamAntonRohm** [comment]
@WaterSibilantFalling -- Stephen, it looks like you've encountered an issue with the product itself, rather than an issue with the documentation. To make sure it gets in front of the right people, please [submit your bug]( https://developercommunity.visualstudio.com/content/problem/post.html?space=21) here.
