### ISSUE TITLE
Credential Usage and Expiration

### ISSUE THREAD

**Issue by shaselsc** [MicrosoftDocs/vsts-docs#757]
Hello,

I think it would be helpful to know what actually happens when you run NuGet CLI commands after the CredentialProvider.vss.exe is put in its proper place. If you are logged into Windows Active Directory that's linked to Azure Active Directory, then it seems to use that as your user for the commands. If you are logged in with a user without that, then a browser window appears asking you to log into a Microsoft account. It then stores those credentials somewhere. It would be nice to know where those credentials are stored since we first feared that they might be stored within the exe itself, which we thought would be too insecure for our purposes. It would be nice to know where they are in case we need to remove/reset them for any reason. Also, it would be nice to know if the username/password credentials stored expire at some point and how long that might be.

_EDIT 2018-05-10 10:58 AM_: ~~It would also be nice to know if when you first run a command using AD credentials, then does it store those credentials as well?~~ Never mind. It looks like it doesn't from our testing.

Thanks for your time,
Steve

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab0a3735-a9b0-2ed7-f08f-5321f55f8c90
* Version Independent ID: 2153f6c0-def7-eed1-286d-5e61c9fcbec4
* Content: [Use NuGet with VSTS feeds](https://docs.microsoft.com/en-us/vsts/package/nuget/nuget-exe?view=vsts)
* Content Source: [docs/package/nuget/nuget-exe.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/package/nuget/nuget-exe.md)
* Service: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by kgreed** [comment]
In my case it asked for credentials once. I was able to push then but now I get access denied and I don't know where to go to fix the credentials.

**Comment by elbatk** [comment]
Adding @alexmullans to knock out some of these questions, looks like it has gotten quite some momentum from the community. Alex, maybe we should think about adding an "Authentication" concepts doc or something?

**Comment by kgreed** [comment]
I solved my issue, but it is strange behaviour  https://stackoverflow.com/questions/52798199/access-is-denied-error-pushing-package-into-my-azure-devops-artifacts-nuget-feed

**Comment by thomps23** [comment]
Closing per Issue creators latest update.
