### ISSUE TITLE
Transition from Git to TFS has been good

### ISSUE THREAD

**Issue by cmiller734** [MicrosoftDocs/vsts-docs#758]
In part due to docs like this. I appreciate this documentation, and even the fact that you can toggle from light to dark mode.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cfd36c9f-c60e-6191-f344-0cd8c0829bb6
* Version Independent ID: 25868222-c846-1e31-9373-a741df436cb6
* Content: [Suspend your work and manage your shelvesets](https://docs.microsoft.com/en-us/vsts/tfvc/suspend-your-work-manage-your-shelvesets?view=vsts)
* Content Source: [docs/tfvc/suspend-your-work-manage-your-shelvesets.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/tfvc/suspend-your-work-manage-your-shelvesets.md)
* Service: **devops**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
@cmiller734 Thank you for your feedback!
