### ISSUE TITLE
Release pipeline in yaml

### ISSUE THREAD

**Issue by stankolubomir** [MicrosoftDocs/vsts-docs#7580]
Hello, is it possible to setup the whole release pipeline in the yaml configuration of the chosen repository?
I see that there is a possibility to configure build pipeline in the azure-pipelines.yaml file (or similar), but I'd like to configure also separated release pipelines in the yaml files. The only option I've seen is export to json and import from json. But this is not what I'm looking for.
Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 63234ade-28cc-02fc-a319-42e3491da601
* Version Independent ID: 7ccbfe96-d61e-8bf2-de22-61150d648abd
* Content: [Release pipelines - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/?view=azure-devops#feedback)
* Content Source: [docs/pipelines/release/index.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/release/index.md)
* Product: **devops**
* Technology: **devops-cicd-release**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by RoopeshNair** [comment]
Yaml syntax is same for build and release pipelines. Here is the link to [schema](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema%2Cparameter-schema). Let us know if you still queries around configuring the YAML pipelines for release/deployments

**Comment by NathanielRose** [comment]
I do not see an option to use YAML for a release pipeline. I only see the option to import JSON. Release pipelines have unique features such as condition gates which I am unsure how to incorporate into a YAML with the correct syntax.
