### ISSUE TITLE
Please update the page for Azure DevOps Server

### ISSUE THREAD

**Issue by gojanpaolo** [MicrosoftDocs/vsts-docs#7592]
https://developercommunity.visualstudio.com/content/problem/941173/facing-a-sequence-was-not-expected-when-applying-y.html

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6724abea-bbdc-bf66-ed5e-3214fa6c3e66
* Version Independent ID: 4f8dab21-3f0e-da32-cc0e-1d85c13c0065
* Content: [Templates - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/templates?view=azure-devops-2019)
* Content Source: [docs/pipelines/process/templates.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/templates.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by juliakm** [comment]
I'm running into the same error as you and will let you know what the product team says.
