### ISSUE TITLE
Duplicate steps

### ISSUE THREAD

**Issue by Sathelka** [MicrosoftDocs/vsts-docs#7594]
Step 3 and 4 in the "Set capacity for the team and team members" section repeat twice.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de93c4e5-f491-af61-6df5-e7253d727dc9
* Version Independent ID: 417246fa-90ed-38a0-cc68-1de7895e96ce
* Content: [Set sprint capacity - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/sprints/set-capacity?view=azure-devops#set-capacity-for-the-team-and-team-members)
* Content Source: [docs/boards/sprints/set-capacity.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/boards/sprints/set-capacity.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by WilliamAntonRohm** [comment]
@Sathelka -- thank you for your observations.

@KathrynEE -- the numbering in that section is 1,2,3,4,3,4 -- it appears to be a versioning (moniker) overlap.

**Comment by KathrynEE** [comment]
@@Sathelka, @WilliamAntonRohm - Thanks for the correction. I'll get the article updated soon.
