### ISSUE TITLE
Stakeholder's cannot see Analytics View*

### ISSUE THREAD

**Issue by Ahetejaz** [MicrosoftDocs/vsts-docs#7608]
This page says all project valid users who are project contributor will be able to see the analytics page however that's not the case with Stakeholders. I have verified both the requirements and even the permissions mentioned in the page. I have made those permission allowed too still stakeholders cannot see the analytics page unless basic users.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1f04bf6a-1455-8770-0a2e-da22f644bced
* Version Independent ID: d63dea23-3678-60c4-c028-c4b618fc3613
* Content: [Analytics permissions and security - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/report/powerbi/analytics-security?view=azure-devops#feedback)
* Content Source: [docs/report/powerbi/analytics-security.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/report/powerbi/analytics-security.md)
* Product: **devops**
* Technology: **devops-analytics**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@Ahetejaz  - Thank you for your feedback. I will update the article to reflect that Stakeholders have no access to Analytics views.
