### ISSUE TITLE
Clarify which bash is used on Windows

### ISSUE THREAD

**Issue by letmaik** [MicrosoftDocs/vsts-docs#7613]
Git Bash? WSL? Something else?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 450ac349-5c33-6cdf-1ecd-6eb989a00334
* Version Independent ID: a7119c1a-59b2-3081-a241-e93aa0d6b4b9
* Content: [Bash task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/bash?view=azure-devops)
* Content Source: [docs/pipelines/tasks/utility/bash.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/utility/bash.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @vtbassmatt
* Microsoft Alias: **macoope**

**Comment by letmaik** [comment]
Eh...?

**Comment by vtbassmatt** [comment]
We have an insane dual-repo system, with one private and one public. PRMerger closes the issue here once the PR completes in the private repo.

**Comment by letmaik** [comment]
I see. Maybe this could be changed so that the issue is tagged "fixed-pending-release" (or similar) and only once it's becoming public the issue is closed. It's still a bit unfortunate as then I'm not able to comment on the changes made before they are released to everyone.

**Comment by arcotek-ltd** [comment]
It looks like this was closed without resolution, siting your complex repo system. Could you answer it please, as a fresh Windows install of the agent does not seem to come with any version of bash. As your documentation suggests this task works on Windows, it would be good to highlight any prerequisites.

Thanks
