### ISSUE TITLE
Require both tag and branch as trigger

### ISSUE THREAD

**Issue by matthias-herrmann** [MicrosoftDocs/vsts-docs#7620]
A build should only be triggered if a tag is specified an the branch matches a filter.

**Comment by WilliamAntonRohm** [comment]
@matthias-herrmann -- Matthias, thank you for your suggestion.  Please add it [here](https://developercommunity.visualstudio.com/content/idea/post.html?space=21).

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
