### ISSUE TITLE
Is this not supported in Azure DevOps Server at all?

### ISSUE THREAD

**Issue by gojanpaolo** [MicrosoftDocs/vsts-docs#7622]
Is this not supported in Azure DevOps Server at all?

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 365bff0e-8532-ae8a-f1c9-37ea7017e5b1
* Version Independent ID: a324129d-0edb-00ce-1217-819be9fda4f6
* Content: [Change process from Basic to Agile - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/organizations/settings/work/change-process-basic-to-agile?view=azure-devops)
* Content Source: [docs/organizations/settings/work/change-process-basic-to-agile.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/settings/work/change-process-basic-to-agile.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @kaelli
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@gojanpaolo - Thank you for your inquiry. Yes, currently the Change process for a project is only supported on Azure DevOps Services. It is scheduled to be available with Azure DevOps Server 2020 (according to the [Feature timeline](https://docs.microsoft.com/en-us/azure/devops/release-notes/features-timeline)) slated to be released sometime this summer.
