### ISSUE TITLE
Example value for websiteName

### ISSUE THREAD

**Issue by fassetar** [MicrosoftDocs/vsts-docs#7627]
A little confused on what value should I provide for the field: websiteName.

Thanks 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 244121ae-5de4-14cd-a9c3-d9cda5ad0a3b
* Version Independent ID: 313238b7-d67b-bc60-1188-cbe305179600
* Content: [IIS Web App Manage task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/iis-web-app-management-on-machine-group?view=azure-devops#feedback)
* Content Source: [docs/pipelines/tasks/deploy/iis-web-app-management-on-machine-group.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/deploy/iis-web-app-management-on-machine-group.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by RoopeshNair** [comment]
name of the website that you are trying to update - IIS website name. The default is "Default website"
