### ISSUE TITLE
Pipeline triggers: not clearly documented

### ISSUE THREAD

**Issue by kwaazaar** [MicrosoftDocs/vsts-docs#7629]
I want to use pipeline triggers, but this documentation is very vague about it. Whatever I try, nothing seems to work. Others asked for the same info, but that issue (https://github.com/MicrosoftDocs/vsts-docs/issues/6913) has simply been closed without explanation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5673ec1-c7d1-e0ac-043a-8fc3d5b226a9
* Version Independent ID: b4872831-51c0-6cf8-1c56-de20beb38a80
* Content: [Build pipeline triggers - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/triggers?view=azure-devops&tabs=yaml#pipeline-triggers)
* Content Source: [docs/pipelines/build/triggers.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/build/triggers.md)
* Product: **devops**
* Technology: **devops-cicd-build**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
@kwaazaar Let me see if I can get some more detail added to that section and maybe some more examples.

**Comment by steved0x** [comment]
@kwaazaar I am publishing an update to this article that answers the questions in #6913 and includes more details.
