### ISSUE TITLE
please fix workingDirectory in YAML snippet at the top

### ISSUE THREAD

**Issue by pb6** [MicrosoftDocs/vsts-docs#7630]
workingDirectory should be cwd, as per "best" standard.
See https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/GradleV2/gradletask.ts#L188

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 00499395-fdc3-b150-3469-aee2f9fb7cbc
* Version Independent ID: 44e630e1-1689-2d2e-212b-3ce2baf8771f
* Content: [Gradle build and release task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/gradle?view=azure-devops#feedback)
* Content Source: [docs/pipelines/tasks/build/gradle.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/build/gradle.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @vijayma
* Microsoft Alias: **vijayma**

**Comment by steved0x** [comment]
This issue is fixed and here is the commit, please ignore the Merge pull request auto-generated link above. https://github.com/MicrosoftDocs/vsts-docs/commit/cc9a07224ddd484dc60c06a88c84cafd4027085c#diff-b00bb7ea397bca65fd63cd546b2d88eb
