### ISSUE TITLE
Hockeyapp link incorrect

### ISSUE THREAD

**Issue by githubvick** [MicrosoftDocs/vsts-docs#7631]
When I click on the Hockeyapp link, it simply redirects to app insights overview page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 878f028a-4418-1f6c-bf27-d469b249b621
* Version Independent ID: 7209b942-b6ab-e9f6-6cfd-bd5d89ea9aa8
* Content: [Tools and clients that connect - Azure DevOps - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/user-guide/tools?view=azure-devops#feedback)
* Content Source: [docs/user-guide/tools.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/user-guide/tools.md)
* Product: **devops**
* Technology: **devops-new-user**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @githubvick, Thanks for alerting us. I'll get this taken care of shortly. Thanks again!
