### ISSUE TITLE
Deploy service / files

### ISSUE THREAD

**Issue by curtiswatson** [MicrosoftDocs/vsts-docs#7632]
How do we achieve non-IIS deployments to deployment groups? For example, copy files to deployment group (i.e. define a target path for artifacts to be copied to on deployment group servers). Other options such as executing PowerShell against deployment group?

This is important - other tasks such as Powershell on Target, Windows File Copy, Azure File Copy, etc. do not suffice as it breaks the abstraction provided by deployment groups. If we use these tasks, we'll have deployment groups defining where IIS goes; and other configurations within the CD pipeline defining where these service files go. We would not be able to update the deployment group and have our CD pipeline follow - it would cause the CD pipeline needing to be updated if an environment changed rather than the deployment groups simply being updated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca1c5394-611b-b119-dbf3-b88404e351d5
* Version Independent ID: fcc23259-21ec-f9fa-4e25-f587e1e0f41b
* Content: [Deploy to IIS on a Windows VM - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/apps/cd/deploy-webdeploy-iis-deploygroups?view=azure-devops)
* Content Source: [docs/pipelines/apps/cd/deploy-webdeploy-iis-deploygroups.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/apps/cd/deploy-webdeploy-iis-deploygroups.md)
* Product: **devops**
* Technology: **devops-cicd-apps**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by RoopeshNair** [comment]
You can run any tasks on deployment group targets that can run locally. For example, instead of running PowerShell on Target which targets a remote machine, you can run PowerShell that can run locally. You can use copy files on it as well. Basically instead of relying on WinRM or SSH you run locally using PowerShell or Bash. In Lieu of Azure File Copy you can use az cli or AzCopy.exe in the deployment group phase

**Comment by curtiswatson** [comment]
How do you configure these tasks in a way that they execute against deployment group and not on the build agent (Azure PIpelines)? Copy files, Powershell, etc. are all used for operations on the local build agent - not a "deployment group".

**Comment by curtiswatson** [comment]
Cancel that - ohhh man was I missing a HUGE part of DevOps.

You have to click the [,,,] to the right of the stage and add a "deployment group job" - the default is an agent job.
