### ISSUE TITLE
Importing only accepts work items in NEW state

### ISSUE THREAD

**Issue by salipour105** [MicrosoftDocs/vsts-docs#7641]
Please confirm that when importing items from Excel, only work items with a State of NEW are accepted. The system requires a Title and ID to be saved for any other states.

You can only change the state of a work item when modifying an existing ticket via import.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4296d1cc-f211-9d17-d97f-2b0858fdea7d
* Version Independent ID: cc66dfee-adde-cdfb-b3f5-5d58d89d3c81
* Content: [Import or update work items from a CSV file - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/queries/import-work-items-from-csv?view=azure-devops#feedback)
* Content Source: [docs/boards/queries/import-work-items-from-csv.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/boards/queries/import-work-items-from-csv.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@salipour105 - Hello. Yes, Confirming that when importing items from Excel, only work items with a State of NEW are accepted. The system requires a Title and ID to save work items in any other states.
You can only change the state of a work item when modifying an existing work item via import.
