### ISSUE TITLE
Missing supported scenario: Materialising user accounts

### ISSUE THREAD

**Issue by rodolfograve** [MicrosoftDocs/vsts-docs#7644]
I have recently gone through a Support request with Microsoft because one of our service accounts was being prevented from accessing ADO's REST API.

The error message mentioned Conditional Access Policies, which turned out to be a red herring:

> VS403463: The conditional access policy defined by your Azure Active Directory administrator has failed.

The real reason was the service account had not been "materialised". The "normal" way to materialise a user account is to log in, but since this is not possible with a service account without interactive login permissions, the work-around contained in this official repository is required: 

https://github.com/microsoft/azure-devops-dotnet-samples/blob/master/ClientLibrary/Quickstarts/dotnet/MaterializeUserQuickStarts/Program.cs

If the above information had been available in this page, it would save us (and Microsoft's support) 2 months of investigation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 294772ce-58a0-bb83-8927-3e69beca39df
* Version Independent ID: d9c4a4b3-3abf-d738-369e-fff8532e9dd9
* Content: [Guidance for authentication - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/integrate/get-started/authentication/authentication-guidance?view=azure-devops#feedback)
* Content Source: [docs/integrate/get-started/authentication/authentication-guidance.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/integrate/get-started/authentication/authentication-guidance.md)
* Product: **devops**
* Technology: **devops-ecosystem**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @rodolfograve, Thanks so much for alerting us. I'll review and get this article updated shortly. Thanks again.

**Comment by chcomley** [comment]
I've added an FAQ to the article. Thank you for your feedback, we appreciate it.
