### ISSUE TITLE
Being able to add Reasons to system or custom states?

### ISSUE THREAD

**Issue by cdudley-oncore** [MicrosoftDocs/vsts-docs#7649]
When adding a custom state, we also need to be able to add a list of custom reasons. I searched the community and found this thread indicating that we can't do it in Azure DevOps Services: https://developercommunity.visualstudio.com/content/idea/365937/ability-to-customize-wit-state-reas-in-inheritan.html. I've added a comment to the thread. Can you please add this capability? Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 715eca62-8a31-4163-c27b-f5e71d781982
* Version Independent ID: 06dc711f-1946-29e9-aece-75af903da09b
* Content: [Customize the workflow of an inherited process - Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/organizations/settings/work/customize-process-workflow?view=azure-devops#feedback)
* Content Source: [docs/organizations/settings/work/customize-process-workflow.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/settings/work/customize-process-workflow.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by WilliamAntonRohm** [comment]
@cdudley-oncore -- please [submit your product idea here](https://azure.microsoft.com/en-us/support/devops/).  This repo is solely for documentation issues, with limited support options.

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.

**Comment by cdudley-oncore** [comment]
It's being looked into. Thank you!

**Comment by WilliamAntonRohm** [comment]
@cdudley-oncore -- you're welcome!
