### ISSUE TITLE
Trigger Pipeline on PR Merge

### ISSUE THREAD

**Issue by hdiass** [MicrosoftDocs/vsts-docs#7654]
Hello,

How can we trigger a pipeline when a PR is merged (to clean up an environment)?

Thanks in advance,

**Comment by WilliamAntonRohm** [comment]
@hdiass -- Helder, thank you for your feedback; we appreciate it. To make sure we have all the information needed to triage your issue, please let us know which topic you’re referencing, or provide more context around your general task.
