### ISSUE TITLE
Project Administrators need Basic access level to Share Queries

### ISSUE THREAD

**Issue by salipour105** [MicrosoftDocs/vsts-docs#7659]
Please clarify that a project administrator needs to have a Basic access level to create a query and save it to the Shared folder. Being just a project administrator is not sufficient.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 54179351-62b2-c41b-949b-0652a0f1d354
* Version Independent ID: 1ffcd0b3-e67b-6cfe-caa6-814a699627db
* Content: [Set query permissions - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/queries/set-query-permissions?view=azure-devops)
* Content Source: [docs/boards/queries/set-query-permissions.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/boards/queries/set-query-permissions.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@salipour105 - Thank you for the feedback. I'm updating the article per your suggestion. Users with Stakeholder access cannot create and save queries in a Shared folder.  You need Basic access or higher.
