### ISSUE TITLE
Why does the .npmrc change across each build, causing Dockerfile cache busting?

### ISSUE THREAD

**Issue by patroza** [MicrosoftDocs/vsts-docs#7661]
Why does the .npmrc change across each build, causing Dockerfile cache busting and reinstalling all packages?
This makes this unusable.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 59f58da2-31f3-2daa-09ff-a12d31e45638
* Version Independent ID: 3bee56ad-9f54-fe0c-cf44-c7b9561e4e43
* Content: [npm Authenticate task (for task runners) - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/package/npm-authenticate?view=azure-devops#feedback)
* Content Source: [docs/pipelines/tasks/package/npm-authenticate.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/package/npm-authenticate.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @vijayma
* Microsoft Alias: **vijayma**

**Comment by WilliamAntonRohm** [comment]
It looks like you've encountered an issue with the product itself, rather than an issue with the documentation. To make sure it gets in front of the right people, please [submit your bug]( https://developercommunity.visualstudio.com/content/problem/post.html?space=21) here.
