### ISSUE TITLE
Participating in scale set agents

### ISSUE THREAD

**Issue by SebastianSchuetze** [MicrosoftDocs/vsts-docs#7665]
Hello. Who do I need to contact to participate in the scale set agent private preview?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b2476ab-d8db-bd41-689c-8d3b7c4a16d8
* Version Independent ID: 6d2e5dd0-8678-d850-a1f3-f664a653bac3
* Content: [Virtual machine scale set agents - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/vmss?view=azure-devops#use-scale-set-agent-pool)
* Content Source: [docs/pipelines/agents/vmss.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/agents/vmss.md)
* Product: **devops**
* Technology: **devops-cicd-agents**
* GitHub Login: @vijayma
* Microsoft Alias: **vijayma**

**Comment by vijayma** [comment]
Please send an email to vijayma_at_microsoft_dot_com with your Azure DevOps organization name.

**Comment by annajanicka** [comment]
Hi all,
I was able to add a scale set agent around 2 weeks ago, but this option is not available for me anymore. I would like to add another one, but just can't. Is sending an email to this contact still an option?
Thanks in advance for any advice.
