### ISSUE TITLE
Unnecessary link at the end of page

### ISSUE THREAD

**Issue by IAmHopp** [MicrosoftDocs/vsts-docs#767]
At the very last line, there's a link with a call to "get started" with release views that just links to the same page that it's located at. I think maybe this was supposed to be at the end of the "Feeds" page to continue navigation through the concepts? In any event, I don't see any use for it here. Again, it just links to the exact same page and if someone it's at the end of the document, they already "got started" with the very thing they were reading.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1a891e9b-bf26-ea09-1da3-ebe3e57b7e26
* Version Independent ID: bf53c51c-c1c1-1931-44ef-81433746e5ec
* Content: [Views on VSTS feeds](https://docs.microsoft.com/en-us/vsts/package/concepts/views?view=vsts)
* Content Source: [docs/package/concepts/views.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/package/concepts/views.md)
* Service: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by IAmHopp** [comment]
[By the way, I can edit the file to either remove that line or link to upstream sources with a call to "get started with upstream sources" if you guys want. Just let me know.]

**Comment by elbatk** [comment]
Hey @IAmHopp , I'll just get rid of the link as the concepts don't really need to be followed sequentially, (unless you wanted to).

**Comment by elbatk** [comment]
Thanks for the heads up :)

**Comment by IAmHopp** [comment]
No problem! (:
