### ISSUE TITLE
crossAccountconfigs configuration documentation

### ISSUE THREAD

**Issue by Friedduc** [MicrosoftDocs/vsts-docs#7677]
The provided code to disable cross account dependency is the same as the default code.

`{
"crossAccountDependencyEnabled": true,  
"crossAccountDependencyToggleDefaultState": false
}`

To disable the cross account dependency it should read
`{
"crossAccountDependencyEnabled": false,  
"crossAccountDependencyToggleDefaultState": false
}`
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a1714e91-58b6-9911-0da6-7555d09eccb3
* Version Independent ID: 2a317fb7-67cb-a355-8fe2-8cd0e147acdc
* Content: [Plan and track dependencies across teams and organizations using the Dependency Tracker extension - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/boards/extensions/dependency-tracker?view=azure-devops)
* Content Source: [docs/boards/extensions/dependency-tracker.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/boards/extensions/dependency-tracker.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by WilliamAntonRohm** [comment]
@Frueddyc -- Duc, thank you for catching this.

@KathrynEE -- Kathryn, please review the above-mentioned PR 1129.
