### ISSUE TITLE
SWE?

### ISSUE THREAD

**Issue by Good-man** [MicrosoftDocs/vsts-docs#7687]
I don't know what SWE stands for.  Should I?  It would be helpful to know.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 53c7e8d4-9092-e85f-2310-89065740dd00
* Version Independent ID: d13c25f4-5902-da63-85c3-28e99b318c5c
* Content: [Pipeline Automation Case Study for World Wide Time Keeping - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/migrate/build-deployment-best-practices?toc=%2Fazure%2Fdevops%2Fpipelines%2Ftoc.json&bc=%2Fazure%2Fdevops%2Fpipelines%2Fbreadcrumb%2Ftoc.json&view=azure-devops)
* Content Source: [docs/migrate/build-deployment-best-practices.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/migrate/build-deployment-best-practices.md)
* Product: **devops**
* Technology: **devops-migrate**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by WilliamAntonRohm** [comment]
"Software Engineering"  :^)
