### ISSUE TITLE
"No authentication" 's configuration is wrong

### ISSUE THREAD

**Issue by VAllens** [MicrosoftDocs/vsts-docs#7693]
```json
{
	"id": "endpoint-auth-scheme-none",
	"description": "i18n:Creates an endpoint authentication scheme with no authentication.",
	"type": "ms.vss-endpoint.endpoint-auth-scheme-none",
	"targets": [
		"ms.vss-endpoint.endpoint-auth-schemes"
	],
	"properties": {
		"name": "None",
		"displayName": "i18n:No Authentication"
	}
}
```

It's `ms.vss-endpoint.endpoint-auth-scheme-none`, not `ms.vss-endpoint.endpoint-auth-scheme`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad945cf7-cd73-49da-90f5-21eb88f485e1
* Version Independent ID: d3032766-fb21-d299-e34f-05fe1010132c
* Content: [Authentication Schemas for Service Endpoints - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/extend/develop/auth-schemes?view=azure-devops)
* Content Source: [docs/extend/develop/auth-schemes.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/extend/develop/auth-schemes.md)
* Product: **devops**
* Technology: **devops-ecosystem**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by WilliamAntonRohm** [comment]
Thank you for your feedback.  We have updated the documentation and it should be live by tomorrow.
