### ISSUE TITLE
Tasks in a group task do not have this option

### ISSUE THREAD

**Issue by bootrider** [MicrosoftDocs/vsts-docs#771]
if you setup a task group, with conditions, the will affect the execution of the release, but if you require to modify the condition in the task group, the option does not appear.

As well, if you are defining a group task from scratch, and require to define conditions for the execution, you are not going to find the option

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f151218-9a11-0078-e038-f96198a76143
* Version Independent ID: 09c4d032-62f3-d97c-79d7-6fbfd89910e9
* Content: [Conditional task expressions](https://docs.microsoft.com/en-us/vsts/build-release/concepts/process/conditions?view=vsts)
* Content Source: [docs/build-release/concepts/process/conditions.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/build-release/concepts/process/conditions.md)
* Service: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by thiagocrepaldi** [comment]
It could be possible to chose whether skipped tasks/phases are marked as successes or failures. Currently, "succeeded()" evaluates to false if previous tasks/phases is skipped, but many times skipped tasks/phases are skipped because no additional work is necessary and it is a legitimate success scenario

**Comment by alexhomer1** [comment]
Open the task group in the Build & Release | Task Groups page, select the task and open the Tasks tab. Select the task itself, expand the Control Options section, and select Custom condition in the Run this task option.
