### ISSUE TITLE
Source Control Explorer is not something that Local Workspaces support

### ISSUE THREAD

**Issue by jefflaing** [MicrosoftDocs/vsts-docs#7710]
According to Veronica Giaudrone [MSFT] , https://developercommunity.visualstudio.com/content/problem/958731/source-control-explorer-doesnt-work-with-a-local-w.html,

"Local Workspaces makes a small number of operations work locally. The most important two are compare and undo so you can code and fall back to the workspace version of the file without needing the server.
Source Control Explorer is a feature for browsing the server, so it does not work when offline. Thanks!"

This makes them almost useless when one considers the poor substitute that the Solution Explorer is for the Source Control Explorer.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9b16d189-fa47-b490-5186-76bc9acdcacc
* Version Independent ID: f8e87439-67ec-b342-7e2c-8bc162f53574
* Content: [Decide between using a local or a server workspace - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/tfvc/decide-between-using-local-server-workspace?view=azure-devops#feedback)
* Content Source: [docs/repos/tfvc/decide-between-using-local-server-workspace.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/repos/tfvc/decide-between-using-local-server-workspace.md)
* Product: **devops**
* Technology: **devops-code-tfvc**
* GitHub Login: @apawast
* Microsoft Alias: **sdanie**

**Comment by WilliamAntonRohm** [comment]
It looks like you've encountered an issue with the product itself, rather than an issue with the documentation. To make sure it gets in front of the right people, please [submit your bug]( https://developercommunity.visualstudio.com/content/problem/post.html?space=21) here.

**Comment by jefflaing** [comment]
No, the issue I have encountered is that you describe features that the software does not implement, not will it according to the product people
