### ISSUE TITLE
Would it kill you to provide the name of the Azure DevOps agent IP object in the weekly file?

### ISSUE THREAD

**Issue by yobyot** [MicrosoftDocs/vsts-docs#7718]
First, it is annoying that one has to whitelist IPs for hosted ADO agents. ADO should be a trusted service. Full stop. Second, it's insane that one has to download a large file and then MANUALLY search for the IPs that apply to the hosted agents. Is it "AzureDevOps"? No. Is it "VSTS"? No. Is it "*agent*"? No. 

Who's thinking there? Apparently, not the author of this document. Whoever decided that "download the weekly file" is enough should be embarrassed. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 99af681d-41ad-da15-0b72-08b5cd5a11ac
* Version Independent ID: 2fa0df36-a437-8cbb-b019-b49b31b1e116
* Content: [Microsoft-hosted agents for Azure Pipelines - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops#agent-ip-ranges)
* Content Source: [docs/pipelines/agents/hosted.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/agents/hosted.md)
* Product: **devops**
* Technology: **devops-cicd-agents**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by WilliamAntonRohm** [comment]
It looks like you've encountered an issue with the product itself, rather than an issue with the documentation. To make sure it gets in front of the right people, please [submit your bug]( https://developercommunity.visualstudio.com/content/problem/post.html?space=21) here. 

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.

**Comment by steved0x** [comment]
@yobyot I agree, but right now this is what we have. Please do submit a feature request here:

https://developercommunity.visualstudio.com/spaces/21/index.html

The more folks that do, the more weight it carries with the Azure DevOps team.

I am filing a work item on myself for the documentation - if the process improves, I will get the docs updated ASAP.

Thank you

**Comment by yobyot** [comment]
“Process improves?”

You mean to say that nobody in doc knows the name of the weekly IP file object containing the IP addresses for hosted ADO IPs?

IOW, users just have to whitelist them all?

**Comment by steved0x** [comment]
@yobyot I am publishing an update to this article today with more detail on the process. `Whoever decided that "download the weekly file" is enough should be embarrassed.` - definitely agree that this article needs more info and hopefully today's update will provide better guidance.
