### ISSUE TITLE
What if I don't know the project? Why is it required?

### ISSUE THREAD

**Issue by FredConklin** [MicrosoftDocs/vsts-docs#772]
Why is the project required - it appears to me that the workitem id values are unique for a collection.  Is there a way to create a link for VSTS that uses the workitem id but does not require the project?  We may have a hundred projects and all I have is the workitem id and not the project name. Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2a2fa2c-bdbd-3357-1f4f-ff6504367404
* Version Independent ID: aba4b3e9-7572-e1f1-e618-291fbd5b704f
* Content: [Define the hyperlink for a work item - VSTS & TFS](https://docs.microsoft.com/en-us/vsts/work/work-items/work-item-url-hyperlink?view=vsts)
* Content Source: [docs/work/work-items/work-item-url-hyperlink.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/work/work-items/work-item-url-hyperlink.md)
* Service: **devops**
* GitHub Login: @erickson-doug
* Microsoft Alias: **kaelli**

**Comment by Baisakhc** [comment]
The projectId is an optional parameter to provide to the REST api. So, yes if you can provide the link even without providing the projectId , that will work too.

**Comment by KathrynEE** [comment]
@FredConklin - Thank you for your inquiry. You can use the [Get Work Items](https://docs.microsoft.com/en-us/rest/api/vsts/wit/work%20items/get%20work%20item?view=vsts-rest-4.1) REST API to get a work item solely by account name and ID.  
**For example:** 
`https://mseng.visualstudio.com/_apis/wit/workitems/1263163?api-version=4.1` 
{
•	id: 1263163,
•	rev: 27,
•	fields: 
{
o	System.AreaPath: "VSOnline\VSTS\Agile\WIT Z",
o	System.TeamProject: "VSOnline",
o	System.IterationPath: "VSOnline\OneVS\Sprint 136",
o	System.WorkItemType: "User Story",
o	System.State: "In Progress",
o	System.Reason: "Started",
o	System.AssignedTo: "Baisakhi Chaudhuri <baisakhc@microsoft.com>",
o	System.CreatedDate: "2018-05-16T21:40:09.993Z",
o	System.CreatedBy: "Amit Gupta (VSCS) <amitgup@microsoft.com>",
o	System.ChangedDate: "2018-05-30T23:02:19.26Z",
o	System.ChangedBy: "Baisakhi Chaudhuri <baisakhc@microsoft.com>",
o	System.Title: "Replace stakeholder license check with (hidden) permission for "agile Ux"",
o	System.BoardColumn: "Active Work",
o	System.BoardColumnDone: false,
o	System.BoardLane: "Improvements (B, MG, An)",
o	Microsoft.VSTS.Common.StateChangeDate: "2018-05-23T21:53:34.18Z",
o	Microsoft.VSTS.Common.StackRank: 36506,
o	WEF_1E1D911227064C8FB0E3C087E28E67DB_Kanban.Column: "Active Work",
o	WEF_1E1D911227064C8FB0E3C087E28E67DB_Kanban.Column.Done: false,
o	WEF_1E1D911227064C8FB0E3C087E28E67DB_Kanban.Lane: "Improvements (B, MG, An)",
o	System.History: "Ok, so this is what we have decided on so far :<div><br></div><div>a. We will introduce a system (what Amit calls hidden, basically user will not be able to see this permission) permission on PROJECT namespace :&nbsp;<span style="color:rgb(0, 0, 255);font-family:Consolas;font-size:12.6667px;">52d39943-cb85-4d7f-8fa8-c6baac873819. We can call it &quot;Move WorkItems On Board&quot; or something like that.&nbsp;</span></div><div><span style="color:rgb(0, 0, 255);font-family:Consolas;font-size:12.6667px;">b. All project valid users will have this permission granted to them by default.&nbsp;</span></div><div><span style="color:rgb(0, 0, 255);font-family:Consolas;font-size:12.6667px;">c. Stakeholder users will have this permission granted to him ONLY on public project. On private project, they will not have this permission granted on them. We can achieve this with code similar to below. (below work item move permission has been used as an example, to be replaced with the new permission&nbsp;</span></div><div><br></div><div><p class=MsoNormal style="text-autospace:none;"><span style="font-size:9.5pt;font-family:Consolas;color:blue;">&lt;!--</span><span style="font-size:9.5pt;font-family:Consolas;color:green;"> Grant stakeholders WORK_ITEM_MOVE = 16384 permission only on public projects to stakeholders </span><span style="font-size:9.5pt;font-family:Consolas;color:blue;">--&gt;</span><span style="font-size:9.5pt;font-family:Consolas;color:black;"></span></p> <p class=MsoNormal style="text-autospace:none;"><span style="font-size:9.5pt;font-family:Consolas;color:blue;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &lt;</span><span style="font-size:9.5pt;font-family:Consolas;color:#A31515;">SecurityTemplateEntryStepData</span><span style="font-size:9.5pt;font-family:Consolas;color:blue;"> </span><span style="font-size:9.5pt;font-family:Consolas;color:red;">id</span><span style="font-size:9.5pt;font-family:Consolas;color:blue;">=</span><span style="font-size:9.5pt;font-family:Consolas;color:black;">&quot;</span><span style="font-size:9.5pt;font-family:Consolas;color:blue;">AF5CB753-9343-45AF-ABEA-F6611813909D</span><span style="font-size:9.5pt;font-family:Consolas;color:black;">&quot;</span><span style="font-size:9.5pt;font-family:Consolas;color:blue;"> </span><span style="font-size:9.5pt;font-family:Consolas;color:red;">hostType</span><span style="font-size:9.5pt;font-family:Consolas;color:blue;">=</span><span style="font-size:9.5pt;font-family:Consolas;color:black;">&quot;</span><span style="font-size:9.5pt;font-family:Consolas;color:blue;">4</span><span style="font-size:9.5pt;font-family:Consolas;color:black;">&quot;</span><span style="font-size:9.5pt;font-family:Consolas;color:blue;"> </span><span style="font-size:9.5pt;font-family:Consolas;color:red;">namespaceId</span><span style="font-size:9.5pt;font-family:Consolas;color:blue;">=</span><span style="font-size:9.5pt;font-family:Consolas;color:black;">&quot;</span><span style="font-size:9.5pt;font-family:Consolas;color:blue;">52d39943-cb85-4d7f-8fa8-c6baac873819</span><span style="font-size:9.5pt;font-family:Consolas;color:black;">&quot;</span><span style="font-size:9.5pt;font-family:Consolas;color:blue;"> </span><span style="font-size:9.5pt;font-family:Consolas;color:red;">allow</span><span style="font-size:9.5pt;font-family:Consolas;color:blue;">=</span><span style="font-size:9.5pt;font-family:Consolas;color:black;">&quot;</span><span style="font-size:9.5pt;font-family:Consolas;color:blue;">16384</span><span style="font-size:9.5pt;font-family:Consolas;color:black;">&quot;</span><span style="font-size:9.5pt;font-family:Consolas;color:blue;">&gt;</span><span style="font-size:9.5pt;font-family:Consolas;color:black;"></span></p> <p class=MsoNormal style="text-autospace:none;"><span style="font-size:9.5pt;font-family:Consolas;color:blue;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &lt;</span><span style="font-size:9.5pt;font-family:Consolas;color:#A31515;">TokenTemplate</span><span style="font-size:9.5pt;font-family:Consolas;color:blue;">&gt;</span><span style="font-size:9.5pt;font-family:Consolas;color:black;">{ &quot;type&quot;: &quot;perteamprojectliteral&quot;, &quot;value&quot;: { token: &quot;$PROJECT:vstfs:///Classification/TeamProject/{0}:&quot;, &quot;visibilityFilter&quot;: &quot;Public&quot; } }</span><span style="font-size:9.5pt;font-family:Consolas;color:blue;">&lt;/</span><span style="font-size:9.5pt;font-family:Consolas;color:#A31515;">TokenTemplate</span><span style="font-size:9.5pt;font-family:Consolas;color:blue;">&gt;</span><span style="font-size:9.5pt;font-family:Consolas;color:black;"></span></p> <p class=MsoNormal style="text-autospace:none;"><span style="font-size:9.5pt;font-family:Consolas;color:blue;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &lt;</span><span style="font-size:9.5pt;font-family:Consolas;color:#A31515;">SubjectTemplate</span><span style="font-size:9.5pt;font-family:Consolas;color:blue;">&gt;</span><span style="font-size:9.5pt;font-family:Consolas;color:black;">{&quot;type&quot;:&quot;License&quot;,&quot;value&quot;:&quot;stakeholder&quot;}</span><span style="font-size:9.5pt;font-family:Consolas;color:blue;">&lt;/</span><span style="font-size:9.5pt;font-family:Consolas;color:#A31515;">SubjectTemplate</span><span style="font-size:9.5pt;font-family:Consolas;color:blue;">&gt;</span><span style="font-size:9.5pt;font-family:Consolas;color:black;"></span></p> <p class=MsoNormal><span style="font-size:9.5pt;font-family:Consolas;color:blue;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &lt;/</span><span style="font-size:9.5pt;font-family:Consolas;color:#A31515;">SecurityTemplateEntryStepData</span><span style="font-size:9.5pt;font-family:Consolas;color:blue;">&gt;</span></p><p class=MsoNormal><span style="font-size:9.5pt;font-family:Consolas;color:blue;"><br></span></p><p class=MsoNormal><span style="font-size:9.5pt;font-family:Consolas;color:blue;">d. In UI, wherever we are doing license check to disallow drag drop for stake holder license holders, we will do this permission check instead. Look for&nbsp;</span><span style="background-color:rgb(255, 255, 254);color:rgb(0, 0, 0);font-family:Consolas, &quot;Courier New&quot;, monospace;font-size:12px;white-space:pre;">AdvancedBacklogManagement on UI, below is an example of the check we are doing on UI. Also need to ask Smitha's team if there is anything else they are checking on.</span></p><p class=MsoNormal><a href="https://mseng.visualstudio.com/VSOnline/VSOnline%20Team/_search?text=AdvancedBacklogManagement&amp;type=code&amp;lp=code-Team&amp;filters=ProjectFilters%7bVSOnline%7dRepositoryFilters%7bVSO%7d&amp;result=DefaultCollection/VSOnline/VSO/GBmaster//Tfs/Service/WebAccess/Agile/Scripts/IterationBacklog/IterationBacklog.ts&amp;_a=contents">https://mseng.visualstudio.com/VSOnline/VSOnline%20Team/_search?text=AdvancedBacklogManagement&amp;type=code&amp;lp=code-Team&amp;filters=ProjectFilters%7BVSOnline%7DRepositoryFilters%7BVSO%7D&amp;result=DefaultCollection%2FVSOnline%2FVSO%2FGBmaster%2F%2FTfs%2FService%2FWebAccess%2FAgile%2FScripts%2FIterationBacklog%2FIterationBacklog.ts&amp;_a=contents</a></p><br></div>"
},
•	_links: 
{
o	self: 
{
	href: "https://mseng.visualstudio.com/_apis/wit/workItems/1263163"
},
o	workItemUpdates: 
{
	href: "https://mseng.visualstudio.com/_apis/wit/workItems/1263163/updates"
},
o	workItemRevisions: 
{
	href: "https://mseng.visualstudio.com/_apis/wit/workItems/1263163/revisions"
},
o	workItemHistory: 
{
	href: "https://mseng.visualstudio.com/_apis/wit/workItems/1263163/history"
},
o	html: 
{
	href: "https://mseng.visualstudio.com/web/wi.aspx?pcguid=0efb4611-d565-4cd1-9a64-7d6cb6d7d5f0&id=1263163"
},
o	workItemType: 
{
	href: "https://mseng.visualstudio.com/b924d696-3eae-4116-8443-9a18392d8544/_apis/wit/workItemTypes/User%20Story"
},
o	fields: 
{
	href: "https://mseng.visualstudio.com/_apis/wit/fields"
}
},
•	url: "https://mseng.visualstudio.com/_apis/wit/workItems/1263163"
}

**Comment by FredConklin** [comment]
Apologies - I should have been more explicit.  I am looking for a way to have an "edit" hyperlink on an internal webpage that will open the workitem in the VSTS editor.  The workitem could be in one of several different projects and the only information I have available to me is the workitem Id.  I have tried the hyperlink mentioned in the Document Details page at https://docs.microsoft.com/en-us/vsts/work/work-items/work-item-url-hyperlink?view=vsts)  I have tried the hyperlink mentioned on that page but it appears to work only if the project is specified.  https://AccountName.visualstudio.com/ProjectName/_workitems?id=WorkItemNumber&_a=edit

When I don't specify the project, I get ERR_TOO_MANY_REDIRECTS.

**Comment by FredConklin** [comment]
After digging around some more, I was able to get this to work, and so I'll just add this comment in case others have the same issue. 
This hyperlink worked for me:   https://AccountName.visualstudio.com/_workitems/edit/{id}  where {id} is the workitem id. 
e.g. https://acme.visualstudio.com/_workitems/edit/7
