### ISSUE TITLE
Parameters inheritance?

### ISSUE THREAD

**Issue by JCPuerto** [MicrosoftDocs/vsts-docs#7723]
I love the runtime parameters.

However I'm wondering if I can define the runtime parameters in the template so those parameters are  "shown" in the pipeline using that template.

For instance, the example to choose the pool image is nice. I just don't want to set the 20 lines in each pipeline. I'd like to have those 20 lines just in the template.

![image](https://user-images.githubusercontent.com/10167695/77709440-67cb0e80-6fa1-11ea-86f5-81ca90977da0.png)

Is this possible?

Thank you!

**Comment by WilliamAntonRohm** [comment]
@JCPuerto -- Juan, thank you for your feedback; we appreciate it. To make sure we have all the information needed to triage your issue, please let us know which topic you’re referencing.

**Comment by JCPuerto** [comment]
Hi @WilliamAntonRohm,

This is in reference to this functionality:

https://docs.microsoft.com/en-us/azure/devops/pipelines/process/runtime-parameters?view=azure-devops

Thank you!

**Comment by WilliamAntonRohm** [comment]
@JCPuerto -- Juan, thank you for clarifying.  [This article](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/templates?view=azure-devops) may help.

Beyond that, please see my previous links.
