### ISSUE TITLE
Description for Contents argument does not explain that patterns are evaluated separately

### ISSUE THREAD

**Issue by ian-craig** [MicrosoftDocs/vsts-docs#7732]
The only real description here is "Supports multiple lines of minimatch patterns."

I interpreted this as being simmilar to a `.gitignore` so did a pattern like

```
foo
!foo/bar
```

But in this case it will delete `foo/` then delete everything not in `foo/bar`. So, basically it deletes everything.

Please add into the description that patterns are evaluated independently, and provide an example for negating a subdir like "`foo/!({bar,baz})" deletes all sub-directories of `foo` except `bar` and `baz`"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4cd0e110-4b14-2d96-f28e-d2d2ef53b966
* Version Independent ID: 76cb1df7-c2c5-2de0-fd14-93175838934f
* Content: [Delete Files task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/delete-files?view=azure-devops#feedback)
* Content Source: [docs/pipelines/tasks/utility/delete-files.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/utility/delete-files.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @vtbassmatt
* Microsoft Alias: **macoope**

**Comment by vtbassmatt** [comment]
fixed pending publish
