### ISSUE TITLE
Why cant this thing just let me pick @CurrentSprint and not have to specify the dates, etc. 

### ISSUE THREAD

**Issue by StingyJack** [MicrosoftDocs/vsts-docs#7733]
Its really looking unfinished. What else would i need to use this for if not a sprint burndown on the dashboard?  I could do this for TFS 2015.4

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a9d627b9-9aa8-c52c-3178-cffbefe9727a
* Version Independent ID: 31967bb3-2635-da97-782c-641f432750f7
* Content: [Configure Burndown & Burnup widgets - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/report/dashboards/configure-burndown-burnup-widgets?view=azure-devops#example-configuring-the-burndown-widget-to-act-as-a-sprint-burndown)
* Content Source: [docs/report/dashboards/configure-burndown-burnup-widgets.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/report/dashboards/configure-burndown-burnup-widgets.md)
* Product: **devops**
* Technology: **devops-analytics**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by WilliamAntonRohm** [comment]
It looks like you've encountered an issue with the product itself, rather than an issue with the documentation. To make sure it gets in front of the right people, please [submit your bug]( https://developercommunity.visualstudio.com/content/problem/post.html?space=21) here.
