### ISSUE TITLE
For the "Set up authentication in a build task", it would not work until I set permissions

### ISSUE THREAD

**Issue by jcace** [MicrosoftDocs/vsts-docs#7737]
See StackOverflow with the problem & solution here

https://stackoverflow.com/questions/60907290/azure-pipeline-npm-install-error-403-with-azure-feed/60908185#60908185

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cb7c2ab6-4ba1-51d5-96bb-38a9ab6b50c3
* Version Independent ID: 415de875-ba1b-476b-f08b-1a61dc7a2747
* Content: [Set up your client's npmrc - Azure Artifacts](https://docs.microsoft.com/en-us/azure/devops/artifacts/npm/npmrc?view=azure-devops&tabs=windows#feedback)
* Content Source: [docs/artifacts/npm/npmrc.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/artifacts/npm/npmrc.md)
* Product: **devops**
* Technology: **devops-artifacts**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**

**Comment by WilliamAntonRohm** [comment]
@jcace -- Jason, thank you for your feedback and researches.

@ramiMSFT -- Rami, here is the gist of that stackoverflow post:
> I've also tried changing the npm install task to use Registry I select here, and linking it to my "design-system" feed directly, but it results in the same error. I've followed all the steps here https://docs.microsoft.com/en-us/azure/devops/artifacts/npm/npmrc?view=azure-devops&tabs=windows, but it just doesn't work. Thanks

>Problem solved. What I had to do was go under into the feed -> settings -> permissions, and add the ...Build Service... as a Contributor.

**Comment by ramiMSFT** [comment]
@jcace  Thank you for your feedback. The updated version of the article will go live soon.
