### ISSUE TITLE
Force Approvers on shared service connection

### ISSUE THREAD

**Issue by allanmoller** [MicrosoftDocs/vsts-docs#7745]
Hey, 

So just joined preview feature on shared service connections, already love it. But have one issue, seems like project admins in the project that is allowed to use a shared service connection can remove my approval settings :-( is this intentional?

Was hopping to use this feature to allow more project selfcontrol, by locking down service connections that deploy to prod.

**Comment by WilliamAntonRohm** [comment]
It looks like you've encountered an issue with the product itself, rather than an issue with the documentation. To make sure it gets in front of the right people, please [submit your bug]( https://developercommunity.visualstudio.com/content/problem/post.html?space=21) here.
