### ISSUE TITLE
"You can customize some options for inherited fields" --- is there documentation on what you can do to those fields and how?

### ISSUE THREAD

**Issue by MarkIannucci** [MicrosoftDocs/vsts-docs#7747]
In the [Add or Modify field section](https://docs.microsoft.com/en-us/azure/devops/organizations/settings/work/customize-process?view=azure-devops#add-or-modify-a-field), the document mentions that it is possible to customize some options for inherited fields.  I haven't been able to find documentation on what we can do with those fields.  

In our specific scenario, we have a process which was inherited from the `Basic` process.  I'd like to hide or move the `Deployments` field to another tab.  It appears I am unable to do either one of those, but I don't know if that is by design or not, and I can't determine that from the UI, hence my request for some documentation on what we can and cannot do with inherited fields.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bbd11642-1af2-c211-68bc-7e324131a6cb
* Version Independent ID: 81d3f210-59e5-8487-0347-3db574242a97
* Content: [Customize a project - Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/organizations/settings/work/customize-process?view=azure-devops#add-or-modify-a-field)
* Content Source: [docs/organizations/settings/work/customize-process.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/settings/work/customize-process.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by WilliamAntonRohm** [comment]
@MarkIannucci -- Mark, thank you for your question.  As I understand your question, the available options are listed under that section's step 3: "To modify an existing field...".

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
