### ISSUE TITLE
The DevOps Rangers link under Resources is migrated

### ISSUE THREAD

**Issue by PHBeagle** [MicrosoftDocs/vsts-docs#775]
The page does provide the new link as  https://aka.ms/vsarsolutions

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a922f18-55a1-cf8d-732e-8420b5466187
* Version Independent ID: f70e2d11-4920-b88b-92b2-f3124f4ac8d5
* Content: [Continuous Testing in VSTS and TFS](https://docs.microsoft.com/en-us/vsts/build-release/test/?view=vsts)
* Content Source: [docs/build-release/test/index.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/build-release/test/index.md)
* Service: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment]
Thank you for your feedback. The guide is now discontinued, and so I will update the topic to reflect the change.
