### ISSUE TITLE
Is there maximum stakeholder limit for free license?

### ISSUE THREAD

**Issue by rpskumar** [MicrosoftDocs/vsts-docs#7752]
We understood the limitation of stakeholder license.Each DevOps organization has 5 Free basic license. We would like to add about 800-1200 free stakeholders.   I would like to know is there maximum free stakeholder count. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17e7fef2-40df-4923-e62e-74ac556cbc6a
* Version Independent ID: af9269b4-1db4-df1f-2520-78ad20baf17b
* Content: [Get started with Stakeholder access - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/security/get-started-stakeholder?view=azure-devops&tabs=agile-process#feedback)
* Content Source: [docs/organizations/security/get-started-stakeholder.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/security/get-started-stakeholder.md)
* Product: **devops**
* Technology: **devops-new-user**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by WilliamAntonRohm** [comment]
[This article](https://docs.microsoft.com/azure/devops/organizations/security/access-levels?view=azure-devops#supported-access-levels) states:

> Stakeholder: Provides partial access, can be assigned to unlimited users for free. Assign to users with no license or subscriptions who need access to a limited set of features.

**Comment by rpskumar** [comment]
Thank you!
