### ISSUE TITLE
Localization to Hebrew

### ISSUE THREAD

**Issue by itaihay** [MicrosoftDocs/vsts-docs#7756]
Hi. I did a translation of this page for my organization. Would love to contribute

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7f3770d0-5b22-f550-d7fa-fe7e851eb617
* Version Independent ID: 484ee77c-14dd-f2f4-f0cb-dc5d106f306b
* Content: [Set up billing for your organization - Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/organizations/billing/set-up-billing-for-your-organization-vs?view=azure-devops)
* Content Source: [docs/organizations/billing/set-up-billing-for-your-organization-vs.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/billing/set-up-billing-for-your-organization-vs.md)
* Product: **devops**
* Technology: **devops-billing**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by WilliamAntonRohm** [comment]
@itaihay -- Itai, thank you for your offer.  

@chcomley -- Chrystal, please consider this document enhancement.

**Comment by chcomley** [comment]
Hi @itaihay, Thanks so much for reaching out on this. Unfortunately, the software/UI isn't localized, and I don't believe there are any plans to do so. We thank you for your offer and would love to have you contribute by submitting a PR if you find something that needs to be updated, removed, and so on.

**Comment by yanivush** [comment]
it's very awful that it's not supports righ to left languges. So I can understand people who are searching for another alternative to azure devops board..

**Comment by WilliamAntonRohm** [comment]
@yanivush -- thank you for your feedback.  [Please add it here](https://developercommunity.visualstudio.com/search?space=21).
