### ISSUE TITLE
Docs could be clearer that these *products* / *offerings* are deprecated

### ISSUE THREAD

**Issue by brandonh-msft** [MicrosoftDocs/vsts-docs#7760]
"entrypoints" didn't speak clearly to me that what we killed were actual product offerings. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cde00a22-c654-f6e9-5bad-c4deb0852899
* Version Independent ID: 88ff6f31-199d-e3f6-bc68-be91dc695b0e
* Content: [Load test overview - Azure Test Plans](https://docs.microsoft.com/en-us/azure/devops/test/load-test/overview?view=azure-devops)
* Content Source: [docs/test/load-test/overview.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/test/load-test/overview.md)
* Product: **devops**
* Technology: **devops-test**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by brandonh-msft** [comment]
I misunderstood the docs as listing alternatives. I think the verbiage here could be improved instead of speaking to these offerings as "entrypoints"... just mention that "it affects the following products ..."

**Comment by WilliamAntonRohm** [comment]
@brandonh-msft -- Brandon, thank you for your feedback.  I have updated the document.

@steved0x -- Steve, please review [private PR 1168](https://github.com/MicrosoftDocs/azure-devops-docs-pr/pull/1168).
