### ISSUE TITLE
In DevOps, RG parameter only available for "SPN (Automatic)"

### ISSUE THREAD

**Issue by bajumar** [MicrosoftDocs/vsts-docs#7766]
Existing SPN Step 4 screenshot from TFS shows Resource Group parameter, but this parameter does not appear if configuring Existing SPN via DevOps - please indicate this or add screenshot to clarify. Also, would be nice to have additional instructions for restricting Existing SPN or Managed ID to Resource Groups scopes if required.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 26477658-d1ad-a4c9-0d9e-59aeead8a71e
* Version Independent ID: 45dfbd24-b9f4-fdf2-48a2-5648220204fe
* Content: [Connect to Microsoft Azure - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/library/connect-to-azure?view=azure-devops#create-an-azure-resource-manager-service-connection-using-automated-security)
* Content Source: [docs/pipelines/library/connect-to-azure.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/library/connect-to-azure.md)
* Product: **devops**
* Technology: **devops-cicd-library**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by RoopeshNair** [comment]
Existing SPNs are granted roles outside of Azure DevOps as they are not created by the system.  For role assignments to service principal, please refer to [links](https://docs.microsoft.com/en-us/azure/devops/pipelines/library/connect-to-azure?view=azure-devops#create-an-azure-resource-manager-service-connection-with-an-existing-service-principal) in the doc
