### ISSUE TITLE
Does this task run powershell on Linux?

### ISSUE THREAD

**Issue by kummerer94** [MicrosoftDocs/vsts-docs#7768]
It is not clear from the documentation whether this task will actually run Powershell on Linux or just on Windows.

In the first example, it states that you can run powershell with task task:

```yml
# Run a PowerShell script on Linux, macOS, or Windows
```

Then, later:

&gt;&gt; Both of these resolve to the PowerShell@2 task. powershell runs Windows PowerShell and will **only work on a Windows agent**.

Is this task now working on a Linux agent or not?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a0e444c2-69c6-4d71-6fd0-94d0f4097d3a
* Version Independent ID: 3a727833-1cc3-c2fb-c5b3-22605eee2721
* Content: [PowerShell task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/powershell?view=azure-devops)
* Content Source: [docs/pipelines/tasks/utility/powershell.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/utility/powershell.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @vtbassmatt
* Microsoft Alias: **macoope**

**Comment by vtbassmatt** [comment]
The task will run anywhere. Different settings work/don't work on different platforms: namely, Windows PowerShell only works on Windows. You have to tell the task to use PowerShell Core if you want it to work on Windows.

You elided a lot of words, including the "this task has some shortcuts in YAML". If you use the `- powershell` shortcut in YAML, you'll get Windows PowerShell, which is obviously Windows-only. If you use the `- pwsh` shortcut, you'll get PowerShell Core, which runs anywhere.
