### ISSUE TITLE
New .Net Core 2 MVC project gives 502.5 - Sample project works.

### ISSUE THREAD

**Issue by DanJ210** [MicrosoftDocs/vsts-docs#777]
I followed this documentation and deployed to Azure, app works. I created a new .Net Core 2 web app from a VS 2017 template, no code changes at all, followed this documentation to deploy to Azure and I get a 502.5 error, process or app cannot start.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f9e617bc-bf8d-0348-5fd4-7b040e4d2ff3
* Version Independent ID: ded5c7ec-feee-b573-ffbf-c972d25135bb
* Content: [Deploy your app to an Azure web app](https://docs.microsoft.com/en-us/vsts/build-release/apps/cd/azure/aspnet-core-to-azure-webapp?view=vsts&tabs=vsts)
* Content Source: [docs/build-release/apps/cd/azure/aspnet-core-to-azure-webapp.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/build-release/apps/cd/azure/aspnet-core-to-azure-webapp.md)
* Service: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment]
Thank you for your feedback. I have passed this on to the product team for advice.

**Comment by imalokagrawal** [comment]
I am not able to reproduce this issue at my end. Are you deploying to Azure WebApp on Windows or Linux?

**Comment by DanJ210** [comment]
Windows. I've found what the issue is. The latest templates from VS 2017 has the package `Microsoft.AspNetCore.All` which contains the latest packages for a lot of packages. I had to bring the version down and then the application started working. So it looks like Azure isn't keeping up quite as quick with the templates on VS 2017. This could throw people off quite a bit when they upgrade packages only for it not to work on Azure yet. Not sure when the latest will be available on Azure yet but until then I'll have to use a lower version.

**Comment by DanJ210** [comment]
@imalokagrawal From Windows. Not sure how you can't reproduce, all you should have to do is create a brand new .Net Core MVC from the latest VS 2017 with the latest `Microsoft.AspNetCore.All` package and then deploy to Azure. Happens every time.
