### ISSUE TITLE
Table under "Auto Detect Logic" has mis-aligned rows

### ISSUE THREAD

**Issue by dpolivy** [MicrosoftDocs/vsts-docs#7770]
The formatting of the Auto Detect Logic table is off and is confusing on first glance. Specifically, under the 3rd row (WebApp on Windows...), the Package Type and Deployment Method columns don't match up for the last two package types, due to wrapping.

It would be nice to add proper alignment to the table so the behavior for each package type is more clearly understandable.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 29c94df7-9de9-ea1a-8b77-d1e6023694dc
* Version Independent ID: a525989e-2e0a-0399-556e-9011ee95da4e
* Content: [Azure App Service Deploy task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-rm-web-app-deployment?view=azure-devops)
* Content Source: [docs/pipelines/tasks/deploy/azure-rm-web-app-deployment.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/deploy/azure-rm-web-app-deployment.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by dpolivy** [comment]
![image](https://user-images.githubusercontent.com/3200655/78058994-01961100-733e-11ea-9b6a-2d7472db63ff.png)

**Comment by WilliamAntonRohm** [comment]
@dpolivy -- Dan, thank you for your feedback.

@N-Usha -- Usha, thank you for correcting this.
