### ISSUE TITLE
North and West - incorrect axis..?

### ISSUE THREAD

**Issue by SetTrend** [MicrosoftDocs/vsts-docs#7772]
The text distinguishes "between North and West Europe". Are you sure this is by intention? Shouldn't it correctly read "between **East** and West Europe" or "between North and **South** Europe"?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 52eb9f91-b952-afb6-6d17-d7092f46440d
* Version Independent ID: bb9113a5-8b8b-b20b-9c6f-09a57f53ba7c
* Content: [Azure DevOps - Data Protection - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/security/data-protection?view=azure-devops&source=docs#feedback)
* Content Source: [docs/organizations/security/data-protection.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/security/data-protection.md)
* Product: **devops**
* Technology: **devops-security**
* GitHub Login: @mlearned
* Microsoft Alias: **mlearned**

**Comment by WilliamAntonRohm** [comment]
@SetTrend -- Axel, thank you for your question.  I believe the text is correct as-is.

**Comment by SetTrend** [comment]
@WilliamAntonRohm:

Thanks for replying. I'm wondering, because many countries, like Sweden, Denmark, Germany, The Netherlands, Belgium, Luxemburg, Ireland etc. are all **north western** European countrys (in contrast to Italy, Greece, Hungary, Czechoslovakia etc.). I don't see a true distinction between north and west as it's the same attribute for many countries.
