### ISSUE TITLE
true default value of `failOnStderr`

### ISSUE THREAD

**Issue by nerijusk** [MicrosoftDocs/vsts-docs#7778]
What is the true default value of `failOnStderr`? Seems it has changed recently as my pipelines with bash tasks continue in a strange way. Once the first bash task fails the pipeline continues to run all other tasks except the rest bash tasks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 07e70665-a794-82fd-287b-65a747488efa
* Version Independent ID: 0c34f5c3-bc80-061d-cf7a-f30c224ce3b1
* Content: [Bash task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/bash?view=azure-devops)
* Content Source: [docs/pipelines/tasks/utility/bash.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/utility/bash.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @vtbassmatt
* Microsoft Alias: **macoope**

**Comment by vtbassmatt** [comment]
[The relevant line](https://github.com/microsoft/azure-pipelines-tasks/blame/master/Tasks/BashV3/task.json#L91) hasn't changed in 3 years according to `git blame`. The default is "false".

It sounds like you need product support, so please file a ticket on [Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html).
