### ISSUE TITLE
Possible for project owners to delete other user's wiki comments?

### ISSUE THREAD

**Issue by montebhoover** [MicrosoftDocs/vsts-docs#7781]
You mention it is possible to delete your own comments, but is there a way to delete other user's comments?  Is there some permission level that allows this?  Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c85ebb83-c49f-e784-70b5-30c0ac01682b
* Version Independent ID: dc859870-0b8f-bee5-0b2f-e6b2aa3260c6
* Content: [Add comments to wiki pages - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/project/wiki/add-comments-wiki?view=azure-devops#feedback)
* Content Source: [docs/project/wiki/add-comments-wiki.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/project/wiki/add-comments-wiki.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @montebhoover, Thanks for your question. It is not possible to delete other users' comments. I'd suggest that you submit a feature request [here](https://developercommunity.visualstudio.com/spaces/21/index.html).
Thanks!
