### ISSUE TITLE
MSBuild argument task incorrect parameter

### ISSUE THREAD

**Issue by kunduso** [MicrosoftDocs/vsts-docs#7788]
https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/msbuild?view=azure-devops

In the below yaml snippet, it is mentioned as msbuildArguments while using Azure Pipelines for vscode I found that the right parameter is msbuildArgs.

# MSBuild
# Build with MSBuild
- task: MSBuild@1
  inputs:
    #solution: '**/*.sln' 
    #msbuildLocationMethod: 'version' # Optional. Options: version, location
    #msbuildVersion: 'latest' # Optional. Options: latest, 16.0, 15.0, 14.0, 12.0, 4.0
    #msbuildArchitecture: 'x86' # Optional. Options: x86, x64
    #msbuildLocation: # Optional
    #platform: # Optional
    #configuration: # Optional
    #msbuildArguments: # Optional
    #clean: false # Optional
    #maximumCpuCount: false # Optional
    #restoreNugetPackages: false # Optional
    #logProjectEvents: false # Optional
    #createLogFile: false # Optional
    #logFileVerbosity: 'normal' # Optional. Options: quiet, minimal, normal, detailed, diagnostic

**Comment by WilliamAntonRohm** [comment]
@kunduso -- Sourav, thank you for catching this.

@vijayma -- Vijay, please review [private PR 1191](https://github.com/MicrosoftDocs/azure-devops-docs-pr/pull/1191).

**Comment by steved0x** [comment]
@kunduso You can see the source for the tasks, and the task.json for MSBuildV1 for this parameter is here:

https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/MSBuildV1/task.json#L103

![image](https://user-images.githubusercontent.com/1580889/78911778-c9d14c80-7a54-11ea-8628-b23f1d03b7dd.png)

There is another tasks, VSBuildV1that does have an `msBuildArgs` parameter, is that possibly the one?

I'm closing this issue but please reopen a new one with additional details if this doesn't help you resolve your issue. Thank you,
