### ISSUE TITLE
Invitation Email Example

### ISSUE THREAD

**Issue by cashewshideout** [MicrosoftDocs/vsts-docs#7790]
Could an example of the email invitation be added to the documentation as well as details on what the subject will be and what will show as the 'From' address?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b6db4fba-7322-16bc-3431-6b8f933a84bf
* Version Independent ID: a20bd1b0-06d7-8f49-30d2-25c5e188b674
* Content: [Add, invite guest users to your organization - Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/add-external-user?view=azure-devops&tabs=preview-page#feedback)
* Content Source: [docs/organizations/accounts/add-external-user.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/accounts/add-external-user.md)
* Product: **devops**
* Technology: **devops-accounts**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @cashewshideout, Thanks for reaching out. This is a great suggestion. I'll publish an update shortly. Until then, the email comes from AzureDevOps at Microsoft.com and the subject says, "You have been invited to an Azure DevOps project." Please let me know if you have any further questions or suggestions. Thanks!
