### ISSUE TITLE
Azure Devops Release Pipeline Override Template Parameters with an External Config File

### ISSUE THREAD

**Issue by tucane** [MicrosoftDocs/vsts-docs#7793]
Not sure if this is the correct place to ask this but I was redirected here by the arm templates team.

Is there is a way for us override the parameters in this step with an external config file instead of directly editing in the box? Our team would prefer to edit this part with a config file instead of directly doing it in the pipeline to prevent accidental edits.

![image](https://user-images.githubusercontent.com/14172078/78185755-6aee5080-7420-11ea-93de-f803268eefc6.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3aa4bb5b-30b2-bb87-5a4d-d1fd4f8b9860
* Version Independent ID: aba4f40c-5b1d-404e-7594-aa8887ad5ce5
* Content: [Azure Resource Group Deployment task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-resource-group-deployment?view=azure-devops#arguments)
* Content Source: [docs/pipelines/tasks/deploy/azure-resource-group-deployment.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/deploy/azure-resource-group-deployment.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by RoopeshNair** [comment]
No. you can either use template parameters json or override template option. External config file as an input is not supported. 

You may [suggest a feature](https://developercommunity.visualstudio.com/content/idea/post.html?space=21) on developer community
