### ISSUE TITLE
Is the note on managed identity support current?

### ISSUE THREAD

**Issue by migolfi** [MicrosoftDocs/vsts-docs#7794]
I have a service connection to allow webhook triggers for ACR. Those are working with MI. I'm wondering if Managed Identities are still not supported on Microsoft Hosted Agents.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5093b8d4-43df-12c3-591d-43e174e630cd
* Version Independent ID: 4a9bf702-1b28-33ef-9a26-fcf9dadaa7c2
* Content: [Troubleshoot Azure Resource Manager service connections - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/azure-rm-endpoint?view=azure-devops#feedback)
* Content Source: [docs/pipelines/release/azure-rm-endpoint.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/release/azure-rm-endpoint.md)
* Product: **devops**
* Technology: **devops-cicd-release**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by RoopeshNair** [comment]
No hosted agents can't be used with managed identities. AFAIK, you can't grant IAM user role on your resources to hosted agents which are in Microsoft tenant.
