### ISSUE TITLE
only two jobs defined but comment says 3 jobs

### ISSUE THREAD

**Issue by kknight-valorem** [MicrosoftDocs/vsts-docs#7795]
Change text for the Build using multiple versions section 
from 
•Select Save and then confirm the changes to see your build run three jobs on three different platforms and SDKs.
to
•Select Save and then confirm the changes to see your build run two jobs on three different platforms and SDKs.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 521b594c-dbb9-54d5-f56f-00e2f5fa1d92
* Version Independent ID: 509d3e4e-23db-8493-e1a6-acb67ec47e81
* Content: [Customize your pipeline - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/customize-pipeline?view=azure-devops)
* Content Source: [docs/pipelines/customize-pipeline.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/customize-pipeline.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @vijayma
* Microsoft Alias: **vijayma**

**Comment by WilliamAntonRohm** [comment]
@kknight-valorem -- Ken, thank you for spotting this.

@vijayma -- Vijay, please review [private PR 1192](https://github.com/MicrosoftDocs/azure-devops-docs-pr/pull/1192).
