### ISSUE TITLE
Formula Design System link broken

### ISSUE THREAD

**Issue by debben** [MicrosoftDocs/vsts-docs#7798]
When clicking the link to the [formula design system](https://developer.microsoft.com/en-us/azure-devops/), the page seems to be down. The main js and css assets return 404. The link worked a few days ago. Who at Microsoft do I need to reach out to in order to get this documentation back up? Is there any particular reason these formula design system docs are on a separate site from the rest of the vsts-docs? If the docs were part of vsts-docs I'd be able to access them here regardless of if docs.microsoft.com was down.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d966f184-5f28-f746-ed60-6afedc044d47
* Version Independent ID: 274ed471-e63f-47db-c9df-595e0173ea1a
* Content: [Use the Combo Control - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/extend/develop/ui-controls/comboo?view=azure-devops#feedback)
* Content Source: [docs/extend/develop/ui-controls/comboo.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/extend/develop/ui-controls/comboo.md)
* Product: **devops**
* Technology: **devops-ecosystem**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by WilliamAntonRohm** [comment]
@debben -- Don, thank you for your feedback.  The page appears to be working now.  If you have further issues, please [file a bug]( https://developercommunity.visualstudio.com/content/problem/post.html?space=21).
