### ISSUE TITLE
how to debug  in VS code

### ISSUE THREAD

**Issue by guywou** [MicrosoftDocs/vsts-docs#780]
Can somebody tell me how I can debug the TypeScript of my web extension directly in VS Code ?

**Comment by gregvanl** [comment]
Moved to https://github.com/Microsoft/vscode-docs/issues/1617

**Comment by gregvanl** [comment]
@steved0x I can't close the issue but moved to the vscode-docs repo. Feel free to close.

**Comment by thomps23** [comment]
Closing per @gregvanl comment.
