### ISSUE TITLE
Need to understand what to do with "Package or Folder" field that is mandatory in the "Deploy Azure App Service"

### ISSUE THREAD

**Issue by jholovacs** [MicrosoftDocs/vsts-docs#781]
It seems to be looking for a package, but I want to use the artifact I published to VSTS.  There's no information on how to do this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 86417335-e55d-02b0-bdcb-3f2640611887
* Version Independent ID: 9cc086b1-8add-751e-1625-d10a4f9b8a40
* Content: [Deploy a web app from VSTS or TFS to Azure App Services](https://docs.microsoft.com/en-us/vsts/build-release/apps/cd/deploy-webdeploy-webapps?view=vsts)
* Content Source: [docs/build-release/apps/cd/deploy-webdeploy-webapps.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/build-release/apps/cd/deploy-webdeploy-webapps.md)
* Service: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment]
Did you follow Step 3 instruction to select the artifact to deploy, and choose your VSTS project and build name? This sets the Package or folder property to $(System.DefaultWorkingDirectory)/**/*.zip, which is where the build definition should have created the zip file package as the artifact to deploy. If this does not exist, you may want to work through https://docs.microsoft.com/en-us/vsts/build-release/apps/aspnet/build-aspnet-4?view=vsts&tabs=vsts first. I hope this helps.
