### ISSUE TITLE
problem in Microsoft docs

### ISSUE THREAD

**Issue by hpcustomersupport2** [MicrosoftDocs/vsts-docs#782]

**Comment by hpcustomersupport2** [comment]
thanku

**Comment by brollySSJ** [comment]
If i have known issues i want to track, i can do so by defining an impediment (Scrum) or issue (Agile or CMMI). ... Using the impediment work item type helps to track and manage these issues until i can resolve and close them??
[google support ](https://supportwala.wordpress.com/)

**Comment by steved0x** [comment]
@hpcustomersupport2 Thank you for your feedback. I am closing this issue, but if you have additional feedback on our docs, you can select the **Content feedback** button in the **Feedback** section at the bottom of topics on docs.microsoft.com and leave feedback for that topic. Thank you.

![image](https://user-images.githubusercontent.com/1580889/40060241-28be72ae-5824-11e8-89b7-b2ff2aff37e0.png)
