### ISSUE TITLE
Images are broken

### ISSUE THREAD

**Issue by zhankezk** [MicrosoftDocs/vsts-docs#7824]
All images are showing 404. Can we fix please. Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4b2914b5-105a-32f7-c7be-5f1604775f61
* Version Independent ID: 0070cd88-c1f7-6a69-ef9c-fb5b4f3b8544
* Content: [Publishing and Packaging an Extension from the Command Line - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/extend/publish/command-line?view=azure-devops#feedback)
* Content Source: [docs/extend/publish/command-line.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/extend/publish/command-line.md)
* Product: **devops**
* Technology: **devops-ecosystem**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @zhankezk,
Thanks so much for letting us know. I'll be publishing an update today, which should be live shortly afterward. Thanks again!
