### ISSUE TITLE
while running pipeline parameters are coming on UI only for branch where it is defined in yml

### ISSUE THREAD

**Issue by abisekwins29** [MicrosoftDocs/vsts-docs#7828]
https://docs.microsoft.com/en-us/azure/devops/pipelines/process/runtime-parameters?view=azure-

parameters are coming on ui only for branch where it is defined in yml.
Example:
I created the pipeline for yml in devlopment branch with below parameters defined 
parameters:
- name: version
  type: string
  default: SNAPSHOT

For running pipeline while selecting branch development, version parameter is coming on UI but while selecting master it is not coming.

**Comment by abisekwins29** [comment]
After reeding on multiple forums this seems expected behaviour, i did not find any microsoft official document where its is explained.
Could you please share the documentaion link explaining this.

**Comment by WilliamAntonRohm** [comment]
@abisekwins29 -- thank you for your feedback.  You may find further information [here](https://github.com/microsoft/azure-pipelines-yaml/blob/master/design/runtime-parameters.md).

l

**Comment by abisekwins29** [comment]
Thanks William, these documents have already gone through.
I am looking for documentation where i can get details how a pipeline is created and it runs for different branches.
Like created a pileline for say master/azure-pipeline.yml, now for running same pipeline for development branch and other branches i need to have azure-pipeline.yml in all branches.
I want to have more understanding how pipeline has been created and referring azure-pipeline.yml in each branch to run for that specific branch.

**Comment by WilliamAntonRohm** [comment]
@abisekwins29 -- perhaps [this article](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/ci-build-git?view=azure-devops&tabs=yaml) will help.
