### ISSUE TITLE
TOC for this page contains unrelated entries like Data protection overview

### ISSUE THREAD

**Issue by NenoLoje** [MicrosoftDocs/vsts-docs#7835]
When navigating to this page, the TOC in the left shows "Data protection overview" which seems unrelated.

When I navigate to "Data protection overview", it changes to TOC entirely (and is not under the "Wikis" root).

![grafik](https://user-images.githubusercontent.com/13981145/78471876-c1b39d00-7734-11ea-942e-7c55e1f487a6.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 29f1e43f-a069-dd88-7fc7-9cc497fb94f0
* Version Independent ID: c261afa7-6eb7-b3f0-9f92-6d2f3c5ac336
* Content: [Markdown syntax for wikis in Azure DevOps - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/project/wiki/wiki-markdown-guidance?view=azure-devops#feedback)
* Content Source: [docs/project/wiki/wiki-markdown-guidance.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/project/wiki/wiki-markdown-guidance.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @NenoLoje, Thanks for the heads up on this. I'll publish an update today, which will be live shortly afterward. The Data protection overview is related to Azure DevOps, but I do understand that it can be frustrating to be taken to a completely different TOC! Thanks again.
