### ISSUE TITLE
Some info out of date

### ISSUE THREAD

**Issue by densto88** [MicrosoftDocs/vsts-docs#784]
Whether the Hosted Agents run as a service depends on the Queue (Image) you're using now. Hosted VS 2017 Agents run interactively in a user context with Admin permissions. On that image you can install additional software since you're running as Admin, you're only limited by time and disk space.

For Disk Space we provide *at least* 10 GB, it's typically much more though between the actual temp drive size (14GB for the DS2_v2's) and another ~30GB or so free on the operating system disk.

It would be good to add consideration for Docker in the section on which Hosted Agents you should pick (answer is VS 2017 or Linux if you're building containers). Calling out Hosted Linux as a potentially better option than the windows based images for dotnet core builds, etc. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 99af681d-41ad-da15-0b72-08b5cd5a11ac
* Version Independent ID: 2fa0df36-a437-8cbb-b019-b49b31b1e116
* Content: [Hosted agents for VSTS](https://docs.microsoft.com/en-us/vsts/build-release/concepts/agents/hosted?view=vsts)
* Content Source: [docs/build-release/concepts/agents/hosted.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/build-release/concepts/agents/hosted.md)
* Service: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by vtbassmatt** [comment]
@andyjlewis I think we addressed this but I don't have permission to close the bug
