### ISSUE TITLE
Scale-down behavior in VMSS agent pools

### ISSUE THREAD

**Issue by vlad-m-r** [MicrosoftDocs/vsts-docs#7840]
I am curious how Azure pipeline's VMSS agent pools scale-down logic works. As far as I understand, Azure pipeline's managed VMSS agent pool autoscaler will adjust the scale of the VMSS. If so, then how does the autoscaler ensures that the process of scaling down will not tear down a virtual machine running a build or release pipeline? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b2476ab-d8db-bd41-689c-8d3b7c4a16d8
* Version Independent ID: 6d2e5dd0-8678-d850-a1f3-f664a653bac3
* Content: [Virtual machine scale set agents - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/vmss?view=azure-devops)
* Content Source: [docs/pipelines/agents/vmss.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/agents/vmss.md)
* Product: **devops**
* Technology: **devops-cicd-agents**
* GitHub Login: @vijayma
* Microsoft Alias: **vijayma**

**Comment by WillLennon** [comment]
Hi Vlad-m-r,
We monitor the build agents and look for agents that have been idle longer than 1 hour.  We then compare that number to the number of desired agents on standby.  Based on those numbers, we select agents that are currently idle and delete those specific VMs.  We do not let Azure Scalesets decide which VMs to delete.

**Comment by vlad-m-r** [comment]
Hi Will, 
Appricate the quick response. I was under the impression it uses VMSS autoscaling, but if not, then it all makes sense now. 
Gonna close this issue.

**Comment by WillLennon** [comment]
Correct.  VMSS autoscaling must be disabled because Azure doesn't know which VMs to delete.

**Comment by carct** [comment]
@WillLennon, why should that agent be idle for longer than 1h in order to be validate for tear down on Scale down action?
Wouldn't it be better that the first stand-by agent be destroyed and if multiple are in stand-by take down the one with the highest age ?

**Comment by sean-redmond** [comment]
I think it would also be useful to understand the scale-up rules, I see often I have 2 agents running (standby number), I kick off 8 jobs that run for ~20 mins each, I will see 6 jobs in the queue behind the 2 running jobs but the scale action only adds 2 instances when the limit is set to 8. I would like to understand how it decides how many instances to add, and if there is any way to change this behaviour.
