### ISSUE TITLE
How to fetch variables in decorator tasks from pipeline

### ISSUE THREAD

**Issue by jashan05** [MicrosoftDocs/vsts-docs#7842]
Team,

I am using decorator to read variables from pipeline. After reading them i want to use these variables in my decorator tasks. e.g in 'Bash' task if I refer to these variables like variables['varName'], it doesnt get populated. COuld you please help me with the syntax which i can use.

Best Regards
Jashan

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e2f7712f-f527-4326-21d5-34f1c300bdd7
* Version Independent ID: d3e588cc-8552-ddae-1f82-0856cc84f2d9
* Content: [Pipeline decorator context - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/extend/develop/pipeline-decorator-context?view=azure-devops)
* Content Source: [docs/extend/develop/pipeline-decorator-context.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/extend/develop/pipeline-decorator-context.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @vtbassmatt
* Microsoft Alias: **macoope**

**Comment by vtbassmatt** [comment]
Decorators inject tasks and scripts, but those tasks and scripts are executed along with the rest of the job. If you try to refer to variables using `${{ variables['foo'] }}`, the variable is likely to be empty at the time the decorator runs. You should instead use the `$(foo)` macro syntax or possibly a `$[ variables['foo'] ]` runtime expression. Relevant docs are [here](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/expressions?view=azure-devops).
