### ISSUE TITLE
23 Marsh 2020 Warning Banner

### ISSUE THREAD

**Issue by rickyno** [MicrosoftDocs/vsts-docs#7847]
Hi, the change is supposed to have taken effect on March 23rd. We are now April 6th. When do you plan to stop showing "On March 23, 2020, Azure Pipelines will remove Windows Server 2012 R2 with Visual Studio 2015(`vs2015-win2012r2`), macOS High Sierra 10.13 (`macOS-10.13`), and Windows Server Core 1803 (`win1803`) from our hosted pools. This includes builds using the `Hosted` agent pool. A series of brownouts to highlight builds and releases using these soon-to-be-removed images will be conducted over the next couple of weeks. During these brownouts, any builds and releases using the vs2015-win2012r2, macOS-10.13, or win1803 images will fail." since the date is past already?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 61db3371-6395-88a2-fb78-09f98790ab1b
* Version Independent ID: ef6f1bf7-02b8-9093-b84e-c9bde7d98e57
* Content: [Microsoft-hosted agents for Azure Pipelines - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops)
* Content Source: [docs/pipelines/agents/hosted.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/agents/hosted.md)
* Product: **devops**
* Technology: **devops-cicd-agents**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by WilliamAntonRohm** [comment]
@rickyno -- Richard, thank you for your feedback.  That notice should stay in place for a while longer, for new readers.
