### ISSUE TITLE
Permission needed is missing

### ISSUE THREAD

**Issue by get-itips** [MicrosoftDocs/vsts-docs#785]
The Confirm User has Permission does not specify what is the needed permission level to set for the user that will register the agent, 3 choices are available, reader, service account and administrator.
Please correct the documentation, thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 344fb6c7-8770-a366-ed19-0626966be202
* Version Independent ID: 22ac2ad8-186a-3530-9a0e-fdbc860eb470
* Content: [Prepare permissions](https://docs.microsoft.com/en-us/vsts/build-release/actions/agents/prepare-permissions?view=vsts)
* Content Source: [docs/build-release/actions/agents/prepare-permissions.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/build-release/actions/agents/prepare-permissions.md)
* Service: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by mlearned** [comment]
@get-itips i've created a backlog item for our docs for this one.
