### ISSUE TITLE
yaml example typo?

### ISSUE THREAD

**Issue by er1c** [MicrosoftDocs/vsts-docs#7853]
I'm assuming the first YAML snippet here isn't suppose to have 

```
    #script: 'echo Write your commands here.' 
    #workingDirectory: # Optional
    #failOnStderr: false # Optional
```

commented out?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 26225103-344e-6ce2-e4bc-b400c07beff8
* Version Independent ID: 36784662-72a3-543f-9daa-9bad51b19843
* Content: [Command Line task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/command-line?view=azure-devops&tabs=yaml#feedback)
* Content Source: [docs/pipelines/tasks/utility/command-line.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/utility/command-line.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @vtbassmatt
* Microsoft Alias: **macoope**

**Comment by vtbassmatt** [comment]
Good catch.
