### ISSUE TITLE
Preview fully parsed YAML document without committing or running the pipeline

### ISSUE THREAD

**Issue by MisinformedDNA** [MicrosoftDocs/vsts-docs#7857]
I can't get the API to return YAML. Is there further documentation on the use of this feature?

https://docs.microsoft.com/en-us/azure/devops/release-notes/2020/sprint-165-update#preview-fully-parsed-yaml-document-without-committing-or-running-the-pipeline

**Comment by vtbassmatt** [comment]
This is a product support question. Please file a ticket at [Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html). When you do, please incude details about what you tried and what results you got.

**Comment by MisinformedDNA** [comment]
Sorry, I should have worded this differently:

There is no documentation on how to use "Preview fully parsed YAML". Documentation should be added.

**Comment by steved0x** [comment]
@MisinformedDNA That is a valid question, there is an internal PR going to get some REST PI documentation going for this feature and we'll add links when that is ready. In the meantime if you post what you tried over at [Developer communities](https://developercommunity.visualstudio.com/spaces/21/index.html) we'll take a look and see if we can help you get it going.
