### ISSUE TITLE
Android App Bundles

### ISSUE THREAD

**Issue by 200even** [MicrosoftDocs/vsts-docs#7859]
Can you please include in the documentation how to sign .aab with this tool?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c7b5eec0-df86-eb96-93da-af9d16e45e78
* Version Independent ID: 437d8e35-b143-91ef-47d5-7adea2f7f188
* Content: [Android signing build and release task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/android-signing?view=azure-devops)
* Content Source: [docs/pipelines/tasks/build/android-signing.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/build/android-signing.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @vijayma
* Microsoft Alias: **vijayma**

**Comment by WilliamAntonRohm** [comment]
Thanks for the suggestion! The product teams aren’t always watching this repository, so to make sure it gets in front of them for triage, please [submit your idea]( https://developercommunity.visualstudio.com/content/idea/post.html?space=21) here. 

cc @vijayma for awareness
