### ISSUE TITLE
Missing image

### ISSUE THREAD

**Issue by helgedv** [MicrosoftDocs/vsts-docs#7863]
Image for claiming ownership is missing in section "When your Azure DevOps Administrator isn't a member of the target organization"
![Azure AD Administrator not member of organization](media/change-organization-ownership/error-message-administrator-not-member-of-organization.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 378ad220-599b-e802-f084-851277cc208d
* Version Independent ID: 8b041bf4-ec98-78bd-99e1-93e9f11225df
* Content: [Resolve inactive organization owner and project collection administrators - Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/resolve-orphaned-organization?view=azure-devops)
* Content Source: [docs/organizations/accounts/resolve-orphaned-organization.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/accounts/resolve-orphaned-organization.md)
* Product: **devops**
* Technology: **devops-accounts**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @helgedv, Thank you for alerting us! I've just published a fix, which should be live momentarily. Thanks again and have a lovely day.
