### ISSUE TITLE
Currently specifying the latest major version (3.x) is failing to download with the error: Certificate error

### ISSUE THREAD

**Issue by EntityAdam** [MicrosoftDocs/vsts-docs#7867]
Currently specifying the latest major version (3.x) is failing to download with the error: Certificate error.

```
steps:
- task: UseDotNet@2
  displayName: 'Use .Net Core sdk 3.x'
  inputs:
    version: 3.x
```

Build Error
```
Tool to install: .NET Core sdk version 3.x.
Found version 3.1.201 in channel 3.1 for user specified version spec: 3.x
Version 3.1.201 was not found in cache.
Getting URL to download .NET Core sdk version: 3.1.201.
Detecting OS platform to find correct download package for the OS.
C:\windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoLogo -Sta -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command "& 'd:\a\_tasks\UseDotNet_b0ce7256-7898-45d3-9cb5-176b752bfea6\2.165.2\externals\get-os-platform.ps1'"
Primary:win-x64
Detected platform (Primary): win-x64
Downloading: https://download.visualstudio.microsoft.com/download/pr/adeab8b1-1c44-41b2-b12a-156442f307e9/65ebf805366410c63edeb06e53959383/dotnet-sdk-3.1.201-win-x64.zip
##[error]Failed while installing version: 3.1.201 at path: C:/hostedtoolcache/windows/dotnet with error: Could not download installation package from this URL: https://download.visualstudio.microsoft.com/download/pr/adeab8b1-1c44-41b2-b12a-156442f307e9/65ebf805366410c63edeb06e53959383/dotnet-sdk-3.1.201-win-x64.zip Error: Error: certificate has expired
Finishing: Use .Net Core sdk 3.x
```
If I explicitly specify the previous version 3.1.103 the step succeeds with no error.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 99300227-44ca-2348-43f6-a9206077db9f
* Version Independent ID: 2ce43283-e362-fab0-dcae-4a4f1a85c8e9
* Content: [Use .NET Core task - Azure Pipelines](https://docs.microsoft.com/en-gb/azure/devops/pipelines/tasks/tool/dotnet-core-tool-installer?view=azure-devops#feedback)
* Content Source: [docs/pipelines/tasks/tool/dotnet-core-tool-installer.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/tool/dotnet-core-tool-installer.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @pulkitaggarwl
* Microsoft Alias: **puagarw**

**Comment by WilliamAntonRohm** [comment]
It looks like you've encountered an issue with the product itself, rather than an issue with the documentation. To make sure it gets in front of the right people, please [submit your bug]( https://developercommunity.visualstudio.com/content/problem/post.html?space=21) here.

**Comment by EntityAdam** [comment]
thank you
