### ISSUE TITLE
Overwriting a secure file

### ISSUE THREAD

**Issue by padmick** [MicrosoftDocs/vsts-docs#791]
I wish to overwrite a secure file with an updated version.. how can i do this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a5f8376-3654-0ed4-d9f8-d15f28350783
* Version Independent ID: f393daba-6515-6c26-71ac-b557e8c8dad1
* Content: [Download Secure File](https://docs.microsoft.com/en-us/vsts/build-release/tasks/utility/download-secure-file?view=vsts)
* Content Source: [docs/build-release/tasks/utility/download-secure-file.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/build-release/tasks/utility/download-secure-file.md)
* Service: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by padmick** [comment]
Can i get an update on this?

**Comment by DavidStaheli** [comment]
Hi @padmick, I apologize for not seeing this until now.  Currently, VSTS doesn't support updating a secure file.  Instead, the existing secure file must be deleted and another uploaded in its place.  We plan to support direct updates as soon as we can get to them.

**Comment by padmick** [comment]
Thanks

How can one delete the file? A delete option isn't advailable

⁣Sent from BlueMail ​

**Comment by DavidStaheli** [comment]
My latest UI may look a bit different than yours, but does yours show a delete option on this context menu?  It's a little hidden.

![image](https://user-images.githubusercontent.com/1767415/40312300-7f90c490-5ce0-11e8-8c4e-fe186aea273b.png)

**Comment by padmick** [comment]
Ah got it thanks. I'll check now if I can delete the file and replace it with a file with the same name

⁣Sent from BlueMail ​

**Comment by padmick** [comment]
works! thanks ill close this

**Comment by mitschman** [comment]
Hello @DavidStaheli 
I see that the DownloadSecureFile task should be also updated manually everywhere in each Build/Release with a new secure file, in case if the used secure file deleted and uploaded again, even if the file name is the same.

Is the support of direct updates you prognoses soon will have the same behavior?..
I mean when the secure file update will be supported - will it be necessary to update the Build/Release DownloadSecureFile tasks manually?..

**Comment by TripleEmcoder** [comment]
Is there an issue or User Voice item that tracks the actual feature of updating secure files in place?

**Comment by Axemasta** [comment]
It would be really handy if we could update these files. Especially for iOS developers the provisioning profiles & certificates need updating from time to time and its a bit of a pain to delete everything and have to re-enabled all the permissions in our pipelines 🥺

Any ETA on the feature being implemented?

**Comment by WilliamAntonRohm** [comment]
@All -- thank you for your follow-up.  This repo is solely for documentation issues, and this issue seems product-related. To make sure it gets in front of the right people, [please add it here](https://developercommunity.visualstudio.com/search?space=21).

**Comment by dannyvv** [comment]
A proper link to the issue still ther from 2019:
[Unable-to-edit-a-secure-file](https://developercommunity.visualstudio.com/t/Unable-to-edit-a-secure-file/376314?space=21&q=replace+secure+file)
