### ISSUE TITLE
Are files downloaded to $env:TEMP?

### ISSUE THREAD

**Issue by dtamai** [MicrosoftDocs/vsts-docs#792]
I have a release definition that uses a Copy Files task to copy the downloaded secure file to the application folder.
When Source Folder is configured to `$(TEMP)` the task doesn't copy any file, but when I change it to `$(Agent.TempDirectory)` the file is copied.

From the source code I would say the Download Secure File task downloads the file to the _Agent.TempDirectory_ folder (https://github.com/Microsoft/vsts-tasks/blob/master/Tasks/Common/securefiles-common/securefiles-common.ts#L58).

Am I missing something?

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: 2a5f8376-3654-0ed4-d9f8-d15f28350783
* Version Independent ID: f393daba-6515-6c26-71ac-b557e8c8dad1
* Content: [Download Secure File](https://docs.microsoft.com/pt-br/vsts/build-release/tasks/utility/download-secure-file?view=vsts)
* Content Source: [docs/build-release/tasks/utility/download-secure-file.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/build-release/tasks/utility/download-secure-file.md)
* Service: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by arnoldpistorius** [comment]
I can confirm this behavior on my machine too. I think the documentation should be altered to use the $(Agent.TempDirectory) instead of $env:TEMP variable

**Comment by DavidStaheli** [comment]
Thanks a lot, @dtamai and @arnoldpistorius!  This documentation is fixed and should be [available](https://docs.microsoft.com/en-us/vsts/pipelines/tasks/utility/download-secure-file?view=vsts) in production later today.

**Comment by DavidStaheli** [comment]
Verified complete.  Thanks!
