### ISSUE TITLE
Microsoft Test Manager Updates

### ISSUE THREAD

**Issue by bethannfrankum** [MicrosoftDocs/vsts-docs#794]
I was wondering when you plan on supporting automated Nunit tests within the Test Manager? I am trying to figure out a way to run my automated tests that are associated with our test cases here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7d8a7e40-73d6-795f-7b8c-77104ef606e8
* Version Independent ID: 8f15995b-bd94-8d9f-1e8b-82f1f364d221
* Content: [Associate an automated test with a test case](https://docs.microsoft.com/en-us/vsts/build-release/test/associate-automated-test-with-test-case?view=vsts#feedback)
* Content Source: [docs/build-release/test/associate-automated-test-with-test-case.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/build-release/test/associate-automated-test-with-test-case.md)
* Service: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment]
Thank you for your feedback. I have passed this on to the product team for advice.

**Comment by alexhomer1** [comment]
The product team tell me that they expect to ship the final version of this feature with the next update to Visual Studio. At present the feature is partly implemented and may not work for all customers.
