### ISSUE TITLE
Build Your C++ App article implies that I can automatically deploy

### ISSUE THREAD

**Issue by gprosch** [MicrosoftDocs/vsts-docs#795]
This "Build Your C++ App" article implies that I can automatically deploy my app but it appears that only web apps can be configured for Continuous Deployment.  Can you please clarify?  Is there a built-in way to do CD on a C++ application or does this page need to be corrected?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 02b0c082-81b3-79af-8841-8b3033dedf4a
* Version Independent ID: de8aab33-f9ef-0d8d-dbbc-49e23930f1c6
* Content: [Build your Visual C++ app](https://docs.microsoft.com/en-us/vsts/build-release/apps/windows/cpp?view=vsts&tabs=vsts)
* Content Source: [docs/build-release/apps/windows/cpp.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/build-release/apps/windows/cpp.md)
* Service: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by andyjlewis** [comment]
Thank you for the heads up. I've removed the Next Steps section that doesn't apply here. Change should be published in about a day.
