### ISSUE TITLE
Set variables in variable group in a script

### ISSUE THREAD

**Issue by teamtam** [MicrosoftDocs/vsts-docs#796]
Hi VSTS team,

I can see that your documentation states: "Note that the updated variable value is scoped to the phase being executed and does not flow across phases."

Just wondering if it is possible to set a variable in a variable group in a script to work around this?

Cheers,
Ben

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c2e7e7aa-775c-075a-a302-c9628fc9ed9a
* Version Independent ID: a64120fa-cd9c-f237-81f2-a06655a7a55d
* Content: [Define and modify your variables in a script](https://docs.microsoft.com/en-us/vsts/build-release/concepts/definitions/_shared/set-variables-in-scripts?view=vsts&tabs=shell)
* Content Source: [docs/build-release/concepts/definitions/_shared/set-variables-in-scripts.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/build-release/concepts/definitions/_shared/set-variables-in-scripts.md)
* Service: **devops**
* GitHub Login: @erickson-doug
* Microsoft Alias: **douge**

**Comment by vijayma** [comment]
Even with variable groups, you won't be able to set the value of a variable in one phase and read the value in a different phase. That is something we are working on. Thanks.
