### ISSUE TITLE
typo in title

### ISSUE THREAD

**Issue by MrSucik** [MicrosoftDocs/vsts-docs#799]
https://docs.microsoft.com/en-us/vsts/work/customize/process/manage-process?view=vsts you have typo in title 'Create and mange an...'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d547b364-45cc-35d2-bb13-ca93e5043259
* Version Independent ID: ccb4a4ec-cabc-5ace-f42e-b5520e6d443e
* Content: [Create and mange an inherited process - VSTS](https://docs.microsoft.com/en-us/vsts/work/customize/process/manage-process?view=vsts)
* Content Source: [docs/work/customize/process/manage-process.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/work/customize/process/manage-process.md)
* Service: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by steved0x** [comment]
@MrSucik Thanks for letting us know, this has been fixed in https://github.com/MicrosoftDocs/vsts-docs/pull/808 and should be live soon. Thank you.
