### ISSUE TITLE
'Copy' button in the Markdown

### ISSUE THREAD

**Issue by garfbradaz** [MicrosoftDocs/vsts-docs#804]
Hey guys,

Is the copy button meant to appear in my markdown renders on VSTS, when using ``` some code ``` or is that a docs thing here?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 63e81f8a-e33c-afb7-493b-f51f40fafd49
* Version Independent ID: c9495a96-c3e8-00f1-1e53-da6ce584412b
* Content: [Syntax usage for Markdown files, widgets, wikis, and pull requests - VSTS & TFS](https://docs.microsoft.com/en-us/vsts/collaborate/markdown-guidance?view=vsts#links)
* Content Source: [docs/collaborate/markdown-guidance.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/collaborate/markdown-guidance.md)
* Service: **unspecified**
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by steved0x** [comment]
@garfbradaz Can you paste in a screenshot? Thank you.

**Comment by garfbradaz** [comment]
Get @steved0x  - thanks for the reply.

Should I get the following "Copy" button in VSTS when using " ``` ":

![image](https://user-images.githubusercontent.com/959766/40186732-bcc94116-59ed-11e8-875f-79ae687d0357.png)

**Comment by SudoCerb** [comment]
Any idea why this functionality isn't being considered? I think it would be incredibly useful.

**Comment by KathrynEE** [comment]
@SudoCerb - You are welcome to propose it as a feature to consider on the [Developer Community Page](https://developercommunity.visualstudio.com/search?space=21). That is the right place to get visibility.
