### ISSUE TITLE
some Keyboard shortcuts are not working

### ISSUE THREAD

**Issue by damongaylor** [MicrosoftDocs/vsts-docs#806]
j and k do not move me to the next item in backog or board views.  Tried Chrome and ie

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 324d7bd1-0094-2857-9c29-eb55285d0cb1
* Version Independent ID: 6881938e-d065-b3ef-d2d4-bf04951dc686
* Content: [Web portal& Team Explorer keyboard shortcuts - VSTS & TFS](https://docs.microsoft.com/en-us/vsts/collaborate/keyboard-shortcuts?view=vsts)
* Content Source: [docs/collaborate/keyboard-shortcuts.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/collaborate/keyboard-shortcuts.md)
* Service: **unspecified**
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@damongaylor   - Thank you for the correction. I've updated the topic and the changes should be live later today.
