### ISSUE TITLE
Missing options for build-results-section extension type

### ISSUE THREAD

**Issue by brownbl1** [MicrosoftDocs/vsts-docs#809]
I am looking into developing an extension of type `ms.vss-build-web.build-results-section`, and while it exists in the sample, it looks like info is missing on that here. Is there more documentation on developing this type of extension?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 56437af3-75da-d219-5364-9b7927298ece
* Version Independent ID: ca01655a-9195-cf92-14b4-77ef66053dcf
* Content: [Extension Points](https://docs.microsoft.com/en-us/vsts/extend/reference/targets/overview?view=vsts)
* Content Source: [docs/extend/reference/targets/overview.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/extend/reference/targets/overview.md)
* Service: **unspecified**
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by elbatk** [comment]
Hey @brownbl1 , I'll reach out to the product team and see if I can't snag someone who can give you info on that type of extension.

**Comment by yaananth** [comment]
https://github.com/Microsoft/vsts-extension-samples/tree/master/build-results-enhancer

**Comment by elbatk** [comment]
Let me know if that link helps @brownbl1 ! I'll close this out if it does :)

**Comment by brownbl1** [comment]
Thanks! Yes, that helps.
