### ISSUE TITLE
Wrong token_type in OAuth2.0

### ISSUE THREAD

**Issue by jmprovencher** [MicrosoftDocs/vsts-docs#810]
When authenticating with OAuth2.0 for visual studio team service, I receive a response containing the access token like this : 
`{
	"access_token": "ACCESS_TOKEN",
	"token_type": "jwt-bearer",
	"expires_in": "3599",
	"refresh_token": "REFRESH_TOKEN",
	"scope": "vso.work"
}`

The specified token type is "jwt-bearer". However, when performing a request with a header like:
`Authorization: jwt-bearer {access_token}` , I receive a HTTP 203 from the service. According to [RFC](https://tools.ietf.org/html/rfc6749#section-4.2.2) and all your other OAuth2.0 services at microsoft, the returned token_type in the response should be "Bearer" if the server expects an header like `Authorization: Bearer {access_token}`. I think it should be important to respect the RFC standard for the token_type issued.

**Comment by steved0x** [comment]
@jmprovencher Thank you for providing this feedback. This particular repo (vsts-docs) and its associated issues are primarily for providing doc feedback. If the above is something we can add to a document, we can do that (let us know which one), but it sounds like you are reporting a product bug. If so, please report it here: [Product feedback](https://developercommunity.visualstudio.com/spaces/21/index.html). Thank you again for the feedback.

**Comment by jmprovencher** [comment]
Thanks, I reported it to the product feedback page !
