### ISSUE TITLE
Custom endpoint without Url validation

### ISSUE THREAD

**Issue by ProH4Ck** [MicrosoftDocs/vsts-docs#811]
I'm building an extension with a custom endpoint that's not an http url.
Now I solved the problem with `tcp://` at the beginning of the url and then I replace this string in my extension code.
I think a good improvement could be add an option to disable url validation in extension manifest file.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad945cf7-cd73-49da-90f5-21eb88f485e1
* Version Independent ID: d3032766-fb21-d299-e34f-05fe1010132c
* Content: [Authentication Schemas for Service Endpoints](https://docs.microsoft.com/en-us/vsts/extend/develop/auth-schemes?view=vsts)
* Content Source: [docs/extend/develop/auth-schemes.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/extend/develop/auth-schemes.md)
* Service: **unspecified**
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by stephaneey** [comment]
It'd be interesting to have an HTTP header based authentication. In the scenario where VSTS should talk to an API made available by Azure API Management, it'd be nice to use the subscription key as a way to connect from VSTS to the target API.

**Comment by elbatk** [comment]
Hello @ProH4Ck ! You can post suggestions/ideas to the VSTS (now Azure DevOps) UserVoice: https://visualstudio.uservoice.com/forums/330519-visual-studio-team-services
