### ISSUE TITLE
These steps are not very discoverable.

### ISSUE THREAD

**Issue by rfalanga** [MicrosoftDocs/vsts-docs#816]
I'm someone who doesn't use Git often. (My employer has decided to use TFVC instead.) Consequently, when I cloned a repo to my laptop I spent a long time trying to find a way of opening it in VS 2017, without opening the repo folder. I'm glad that you have the instructions under the heading, "Open a solution in Visual Studio from a cloned repo". But those steps are not easily discoverable. I'm glad I found this article, but I wish there was a way, through a menu in VS 2017 to do the same thing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8b8a5b68-909f-126d-5f83-4659e0f55b85
* Version Independent ID: f71ca2b9-c00d-0b2b-34bc-63d11b3576db
* Content: [Clone an existing Git repo](https://docs.microsoft.com/en-us/vsts/git/tutorial/clone?view=vsts&tabs=visual-studio#feedback)
* Content Source: [docs/git/tutorial/clone.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/git/tutorial/clone.md)
* Service: **unspecified**
* Product: **devops**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
@rfalanga Thank you for the feedback and I'm glad you were able to find the section that would help you. I'll see if I can make this more discoverable in the documentation (I may be able to add something [here](https://docs.microsoft.com/en-us/vsts/git/share-your-code-in-git-vs-2017?view=vsts), and if you want. you could file a [feature request](https://developercommunity.visualstudio.com/spaces/21/index.html) with the product team to see if they can add this: `I wish there was a way, through a menu in VS 2017 to do the same thing.`

**Comment by rfalanga** [comment]
Thank you very much, Steve! I'll go to the feature request and add that now.
