### ISSUE TITLE
TFS 2018 Differences

### ISSUE THREAD

**Issue by Sacrilege** [MicrosoftDocs/vsts-docs#817]
I just installed TFS 2018 Update 2 and the configure features link is nowhere to be found. The admin screen doesn't look anything like the screenshot anymore. I'd like to see the documentation updated definitely but I'm also struggling presently because I need to run the configure features wizard and can't find it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97ee4f3d-94b4-c278-de53-ca8a75f4e08f
* Version Independent ID: 2b4e4012-a14b-87ed-4bcc-4b3e504e33be
* Content: [Configure features after an upgrade](https://docs.microsoft.com/en-us/vsts/work/customize/configure-features-after-upgrade?view=tfs-2018)
* Content Source: [docs/work/customize/configure-features-after-upgrade.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/work/customize/configure-features-after-upgrade.md)
* Service: **unspecified**
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@Sacrilege - What version of TFS are you updating from? If the link isn't there, then it's possible that there are no features that need updating.
