### ISSUE TITLE
Agent.OS documentation missing

### ISSUE THREAD

**Issue by jessehouwing** [MicrosoftDocs/vsts-docs#819]
The agent does log it:

[AGENT_OS] --> [Linux]
[AGENT_OS] --> [Windows_NT]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ffebdc8-521c-44b5-cde4-4abdc1bd6f18
* Version Independent ID: dc0effda-6d93-62aa-64c5-4e6f283b0826
* Content: [Build variables](https://docs.microsoft.com/en-us/vsts/build-release/concepts/definitions/build/variables?view=vsts&tabs=batch)
* Content Source: [docs/build-release/concepts/definitions/build/variables.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/build-release/concepts/definitions/build/variables.md)
* Service: **unspecified**
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by andyjlewis** [comment]
Thanks for the heads up. We've got a work item on the backlog.
