### ISSUE TITLE
Dead link https://www.visualstudio.com/pricing/visual-studio-online-feature-matrix-vs

### ISSUE THREAD

**Issue by nschonni** [MicrosoftDocs/vsts-docs#824]
Found in docs/security/export-users-audit-log.md
docs/security/change-access-levels.md
docs/feedback/get-feedback.md
docs/accounts/faq-azure-access.md

**Comment by steved0x** [comment]
@nschonni I have reported this one to the Visual Studio team to get it fixed. Thanks for letting us know. The Visual studio team is fixing these up, and we're fixing the links in our topics as well. Thanks for letting us know!
