### ISSUE TITLE
Lacking documentation

### ISSUE THREAD

**Issue by gvdm90** [MicrosoftDocs/vsts-docs#825]
Hi,

I'm using the .NET client libs for TFS but I did not find a complete documentation on the classes and methods provided by this library. Please provide a link to a developer documentation on all the components (e.g. the different HttpClients).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 413163f0-28c3-a2a7-d626-fcb81bcb2257
* Version Independent ID: 57c127da-2b1e-d29e-9abb-a3c258762ccf
* Content: [.NET Client Libraries for VSTS (and TFS)](https://docs.microsoft.com/en-us/vsts/integrate/concepts/dotnet-client-libraries?view=vsts)
* Content Source: [docs/integrate/concepts/dotnet-client-libraries.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/integrate/concepts/dotnet-client-libraries.md)
* Service: **unspecified**
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by elbatk** [comment]
Hi @gvdm90 , we have it on our backlog to get developer doc reference for the .NET client libraries, it's a work in progress but we do not have it available currently.
