### ISSUE TITLE
why testcase doesn't support 'delete' , only support permanent delection'? 

### ISSUE THREAD

**Issue by JunQianZ** [MicrosoftDocs/vsts-docs#827]
I found the below statements in TFS2018 links: 

_We only support permanent deletion of test artifacts such as test plans, test suites, test cases, shared steps and shared parameters. Deleted test artifacts won't appear in the recycle bin and cannot be restored. Deletion of test artifacts not only deletes the selected test artifact but also all its associated child items such as child test suites, test points across all configurations, testers (the underlying test case work item doesn't get deleted), test results history, and other associated history._

and our customer are some confused, why testcase can't be deleted and restored, why they only support 'permanent delection'? and the bug/task can support both?

**Comment by steved0x** [comment]
@JunQianZ I apologize for the great delay in addressing your feedback. I have forwarded it to the testing product team people. If you think that we should have a feature added that supports delete/recovery of test artifacts, please file a feature request [here](https://developercommunity.visualstudio.com/spaces/21/index.html
).
