### ISSUE TITLE
Add note on SAM-Account-Name limitation

### ISSUE THREAD

**Issue by ChristopherMank** [MicrosoftDocs/vsts-docs#832]
Should add a note when configuring the agent as a Windows Service, that the username (SAM-Account-Name) still has a 20-character limit when setting the runas user account.
https://msdn.microsoft.com/en-us/library/ms679635(v=vs.85).aspx

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43799c5d-2f13-cc76-a1c0-a3f850e16d4e
* Version Independent ID: 97a5b73f-faf7-f9c0-9269-fc79984616d6
* Content: [Deploy a build and release agent on Windows](https://docs.microsoft.com/en-us/vsts/build-release/actions/agents/v2-windows?view=vsts)
* Content Source: [docs/build-release/actions/agents/v2-windows.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/build-release/actions/agents/v2-windows.md)
* Service: **unspecified**
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by ChristopherMank** [comment]
I noticed the "Edit" button no longer appears on the VSTS docs on the right-side nav. Can we no longer directly edit in GitHub and create a PR?

**Comment by ChristopherMank** [comment]
This content source still says 404. Any plans to update with an Edit button so I can PR this update?

**Comment by vtbassmatt** [comment]
addressed in a pending doc update
