### ISSUE TITLE
Expanding on the concept of defining a single sprint cadence for all teams

### ISSUE THREAD

**Issue by erptechnician** [MicrosoftDocs/vsts-docs#835]
I'm a new VSTS administrator, and I have questions and comments pertaining to the section of this post entitled: "Define a single sprint cadence for all teams." I'd very much like to use a shared cadence for all teams with the intention of simplifying the maintenance of my Iteration structure in VSTS. But I'm running into some problems. In the post above, all sprints are added to the root Iteration node (Fabrikam) without a hierarchy as shown below:

Fabrikam
        Sprint 1
        Sprint 2
        Sprint 3

In some cases, a flat Iteration structure works really well, and some cases it might not. Many VSTS/TFS articles suggest configuring Iterations in a hierarchical structure with Releases as shown below:

Fabrikam
    Release A
        Sprint 1
        Sprint 2
        Sprint 3
    Release B
        Sprint 1
        Sprint 2

If I end up using a shared cadence, I'd have to go with the flat model without Releases (as shown in the first example) because Releases would not be universally compatible across all of our teams and the various products that they deliver.

So here are my questions:

1. If I adopt a shared cadence across teams and forego the usage of Releases in my Iteration structure, what practical functionality would I be sacrificing? For example, would I lose the ability to view reports and dashboards which are helpful in managing Releases? Also, would this prevent me from mapping Features to Releases?
2. Could you suggest a work-around solution for shared cadences (flat Iteration structure) that could support the concept of tracking work items belonging to multiple Iterations (e.g. Releases)? In other words, is there another way to track works items belonging to a multiple Iterations other than including a Release node in the Iteration hierarchy itself?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5164b0b1-c11f-67f1-b1ac-f7380147c98f
* Version Independent ID: 34f6260f-e02b-2db6-1ebf-6ab5935543a5
* Content: [Portfolio management - VSTS & TFS](https://docs.microsoft.com/en-us/vsts/work/scale/portfolio-management?view=vsts)
* Content Source: [docs/work/scale/portfolio-management.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/work/scale/portfolio-management.md)
* Service: **unspecified**
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@erptechnician - Thank you for your inquiry.  I don't believe that you lose any practical functionality by foregoing the use of Releases. Here are a few additional notes: 
- The system doesn't accept Iteration Paths which have overlapping dates, which could happen if you define Releases that span several sprints. However, if you set the iteration dates for a Release for a single day, then you may be able to use them effectively (this is an idea, I haven't seen it work in action). 
- Regarding a work-around solution that could support the concept of tracking work items belonging to multiple Iterations, here are a few things you could try: 
	- You can tag work items that are slated for a specific Release with the name of that release 
	- You can add a Milestone or Release field to your work items and set that field based on the target or known release date. 
	- You can create parent Features or Epics which are designed to support a release and then link the User Stories (Features/User Stories) or Features (Epics/Features) to show which items are planned for a release. 
- As for dashboards or reports, you shouldn't lose any functionality. Several of the new [Analytics widgets](https://docs.microsoft.com/en-us/vsts/report/analytics/analytics-widgets-vsts?view=vsts) provide greater flexibility in terms of configuring the data to show. Specifically, I suggest you look at the [Configure a Burndown or Burnup widget](https://docs.microsoft.com/en-us/vsts/report/dashboards/configure-burndown-burnup-widgets), which can support a view of burndown or burnup over several sprints.
- Another tool to review is the [Delivery Plans](https://docs.microsoft.com/en-us/vsts/work/scale/review-team-plans?view=vsts), which can show work items defined across several teams against a calendar view. Make sure all teams that show up in the view have their work items assigned to iteration paths with dates set. 
- Another tool available from the Marketplace is the [Feature timeline](https://marketplace.visualstudio.com/items?itemName=ms-devlabs.workitem-feature-timeline-extension).

I hope the above helps. Please feel free to reach out again if you have more questions.

**Comment by erptechnician** [comment]
Kathryn,

Thanks for your response.  It was very detailed and packed with helpful ideas. 

I'll try mapping User Stories (aka PBIs) to Features.  If I recall correctly, Features in VSTS already have a "Target Date" field, so I can probably use that to track collections of work items that span multiple Iterations. 

I might also try using Tags as you suggest, but I need to do some more research about VSTS Best Practices related the usage of tags.
