### ISSUE TITLE
Incorrect documentation for removing Elasticsearch service

### ISSUE THREAD

**Issue by bittusarkar** [MicrosoftDocs/vsts-docs#836]
Documentation [here](https://docs.microsoft.com/en-us/vsts/search/code/administration?view=tfs-2018#unconfigure-search-on-the-machine-configured-as-your-tfs-server) is stale and does not apply for TFS 2018 U2.

---
 I am proposing to change the documentation as under:

3. Remove the Elasticsearch service:
    a. Open **Command Prompt** as an administrator
    b. Remove the service: `sc delete elasticsearch-service-x64`

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 707d403c-b68d-4c8d-56da-0f37d3117dd2
* Version Independent ID: 9b043f37-0dd2-3aba-c201-8160cdbfac86
* Content: [Code and Work Item Search set up](https://docs.microsoft.com/en-us/vsts/search/code/administration?view=tfs-2018#trouble-tfs)
* Content Source: [docs/search/code/administration.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/search/code/administration.md)
* Service: **unspecified**
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment]
Thank you for your feedback. While we are migrating the documentation to a new site, we are unable to publish changes immediately. However, I have applied the changes to the source topics and they will be published when the migration is complete.
