### ISSUE TITLE
Broken Url 'symbols have been published'

### ISSUE THREAD

**Issue by mishal153** [MicrosoftDocs/vsts-docs#838]
'symbols have been published' URL is broken

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a10a409-5468-9532-f0dc-5a28cdd566d8
* Version Independent ID: 2ef20266-bc45-448b-27f5-e5c3bffed2ef
* Content: [Get Started with NuGet Package Management in VSTS and TFS](https://docs.microsoft.com/en-us/vsts/package/get-started-nuget?view=vsts#feedback)
* Content Source: [docs/package/get-started-nuget.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/package/get-started-nuget.md)
* Service: **unspecified**
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by elbatk** [comment]
Hi @mishal153 ! Thanks for pointing this out - we're doing some work in our repo and this one must have slipped by. The correct link is: https://docs.microsoft.com/en-us/vsts/pipelines/symbols/index?view=vsts and I'm fixing the link ASAP :)
