### ISSUE TITLE
"Automatic package versioning" is misleading

### ISSUE THREAD

**Issue by redwyre** [MicrosoftDocs/vsts-docs#844]
If you select "Use the build number" the task will actually extract a dotted version (x.x.x.x) and use only that, dropping any label.
To use the build number as-is, change it to "Use environment variable" and set the environment variable to BUILD_BUILDNUMBER.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0fa37a3f-6551-16ad-e164-a4ac522cdaab
* Version Independent ID: a3fd6935-2b99-92ef-4eb3-3249fca01f8a
* Content: [NuGet restore, pack, and publish](https://docs.microsoft.com/en-us/vsts/build-release/tasks/package/nuget?view=vsts)
* Content Source: [docs/build-release/tasks/package/nuget.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/build-release/tasks/package/nuget.md)
* Service: **unspecified**
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by elbatk** [comment]
Hi @redwyre , I know it's been forever for this one, but I'm adding a note that details what you've described because I think it's an important thing to clarify, thank you!
