### ISSUE TITLE
Dark Theme issues

### ISSUE THREAD

**Issue by KevinCust** [MicrosoftDocs/vsts-docs#859]
Black text on branch diagrams hard to make out when using dark theme.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4e18eead-7795-0752-93b0-e07f6d088089
* Version Independent ID: f637de69-b13c-eed8-ab05-3515106c9270
* Content: [What is Git? - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/git/what-is-git?wt.mc_id=AID627586_QSG_SCL_251563)
* Content Source: [https://mseng.visualstudio.com/DefaultCollection/TechnicalContent/_git/devops-learn-pr?path=%2fdocs%2fgit%2fwhat-is-git.md&version=GBlive&_a=contents](https://mseng.visualstudio.com/DefaultCollection/TechnicalContent/_git/devops-learn-pr?path=%2fdocs%2fgit%2fwhat-is-git.md&version=GBlive&_a=contents)
* Service: **unspecified**
* Product: **devops**
* GitHub Login: @samgu
* Microsoft Alias: **kangan**

**Comment by steved0x** [comment]
@KevinCust I am working on getting these fixed up - it looks like it is widespread across several documents in that section.

**Comment by steved0x** [comment]
This is fixed and should be live in a day or two, thank you.

**Comment by KevinCust** [comment]
@steved0x FYI - still doesn't seem to be fixed.
