### ISSUE TITLE
Add "in"

### ISSUE THREAD

**Issue by andresnava** [MicrosoftDocs/vsts-docs#861]
"There aren't any changes included this merge commit since I didn't have conflicts" -> "There aren't any changes included in this merge commit since I didn't have conflicts"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7bf7740e-8439-e580-ec7f-c4c185a08048
* Version Independent ID: 2b326db7-b811-b99f-966c-1e603e4f836f
* Content: [History in Git](https://docs.microsoft.com/en-us/vsts/git/concepts/history?view=vsts)
* Content Source: [docs/git/concepts/history.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/git/concepts/history.md)
* Service: **unspecified**
* Product: **devops**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
@andresnava Thanks for letting us know, I will get this fixed and it should be live soon.

**Comment by pascalberger** [comment]
There's a PR for fixing this available here #5054
