### ISSUE TITLE
Link Items across VSTS domains?

### ISSUE THREAD

**Issue by CaptainZippy** [MicrosoftDocs/vsts-docs#864]
Is it possible to e.g. add depencencies on items in other domains?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3167d770-e6d3-dde7-2a9f-89967fb49c58
* Version Independent ID: 66c7f3b8-6de6-47ad-c1fa-94fb98bdac69
* Content: [Link work items to support traceability - VSTS & TFS](https://docs.microsoft.com/en-us/vsts/work/track/link-work-items-support-traceability?view=vsts&tabs=new-web-form)
* Content Source: [docs/work/track/link-work-items-support-traceability.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/work/track/link-work-items-support-traceability.md)
* Service: **unspecified**
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@CaptainZippy - The only way to add this type of link is by using the Hyperlink link type. There is ongoing work planned for later this year to provide cross account linking which would support adding links to work items defined in a project in another account associated with the same organization.
