### ISSUE TITLE
Acronym BDT is used but never defined

### ISSUE THREAD

**Issue by nschonni** [MicrosoftDocs/vsts-docs#865]
Maybe "Build, Deploy, Test", but it's unclear what "BDT task" is talking about.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 81948835-e705-b849-c72e-76c871bccea1
* Version Independent ID: 8b27ddc4-9131-2868-330f-3b1d3e8e1116
* Content: [VSTS and TFS Build and Test - Run Functional Tests step](https://docs.microsoft.com/en-us/vsts/build-release/tasks/test/run-functional-tests?view=vsts)
* Content Source: [docs/build-release/tasks/test/run-functional-tests.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/build-release/tasks/test/run-functional-tests.md)
* Service: **unspecified**
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment]
Thank you for your feedback. I will update the topic to include your recommendations.
