### ISSUE TITLE
Dead Hyper-V fwlinks on docs/tfs-server/admin/config-lab-scvmm-envs.md

### ISSUE THREAD

**Issue by nschonni** [MicrosoftDocs/vsts-docs#875]
These all redirect to dead pages
http://go.microsoft.com/fwlink/?LinkId=181875
http://go.microsoft.com/fwlink/?LinkId=181894
http://go.microsoft.com/fwlink/?LinkID=181875
http://go.microsoft.com/fwlink/?LinkID=181896

**Comment by steved0x** [comment]
@elbatk Sorry to have held onto this issue for so long, I did a bulk update of these broken links but unfortunately I don't know enough about this area to find the right links to replace the broken ones.

**Comment by elbatk** [comment]
Thanks again @nschonni, fixing most of these to point to the [Hyper-V documentation](https://docs.microsoft.com/en-us/windows-server/virtualization/hyper-v/hyper-v-server-2016), couldn't find a link to the Hyper-V Server 2008 R2 oddities though.
