### ISSUE TITLE
Dead links in release-notes/2012/aug-13-team-services.md

### ISSUE THREAD

**Issue by nschonni** [MicrosoftDocs/vsts-docs#889]
http://go.microsoft.com/fwlink/?LinkId=266498
https://www.visualstudio.com/en-us/get-started/hosted-build-controller-vs
https://www.visualstudio.com/en-us/get-started/build-your-eclipse-projects-vs
https://www.visualstudio.com/en-us/get-started/build-your-apps-vs

**Comment by steved0x** [comment]
Fixed
