### ISSUE TITLE
Dead links in release-notes/index.md

### ISSUE THREAD

**Issue by nschonni** [MicrosoftDocs/vsts-docs#896]
http://go.microsoft.com/fwlink/?LinkId=533008
https://www.microsoft.com/en-us/download/details.aspx?id=39305

**Comment by steved0x** [comment]
@nschonni I am hopeful that these will be all fixed this week - I have got a big PR that is going through hopefully by tomorrow. I'm keeping these issues open until they are live.

**Comment by steved0x** [comment]
Just getting back to this, this is the download link for TFS 2015.1, I have reported it to the owner of that product area. Thanks for letting us know.
