### ISSUE TITLE
@CurrentIteration macro

### ISSUE THREAD

**Issue by Richspeirs** [MicrosoftDocs/vsts-docs#897]
Morning, 
I must have missed the change notes, but can't understand why queries using the @CurrentIteration macro are now mandatorily linked to 'Search Teams'.  Forcing this value means it can no longer be used for Shared Queries when listing impediments etc. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f98abc5c-97e7-e8c9-4f3e-d9c82065c574
* Version Independent ID: 77606a2d-92fd-cecd-6b0c-5d86cabb61b2
* Content: [Query by date or current iteration - VSTS & TFS](https://docs.microsoft.com/en-us/vsts/work/track/query-by-date-or-current-iteration?view=vsts)
* Content Source: [docs/work/track/query-by-date-or-current-iteration.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/work/track/query-by-date-or-current-iteration.md)
* Service: **unspecified**
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@Richspeirs - Thank you for your inquiry. More information for this change is provided in the blog post, [@CurrentIteration, Team Parameter, Offset](https://blogs.msdn.microsoft.com/devops/2018/03/01/currentiteration-team-parameter-offset/).  The change was also noted in the Mar 5 release notes, [Work Items hub and VM-based Azure DevOps Project – VSTS Sprint 131 Update](https://docs.microsoft.com/en-us/vsts/release-notes/2018/mar-05-vsts#clarify-query-iteration-schedules-with-the-currentiteration-team-parameter). For a number of reasons, the Team Name is being moved out of the URL, and this requires the Team Parameters to be included in the query.
