### ISSUE TITLE
Build Compatbility

### ISSUE THREAD

**Issue by xdaDaveShaw** [MicrosoftDocs/vsts-docs#899]
XAML Builds have been re-enabled in 2018 Update 2, see here: https://docs.microsoft.com/en-us/visualstudio/releasenotes/tfs2018-update2#build-and-release

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e6b0a421-bc31-fec9-fab1-aea1a7d6cebf
* Version Independent ID: 584d306a-6f5c-d197-ed32-c246463bdb14
* Content: [Changes to required for TFS 2018 - TFS 2018](https://docs.microsoft.com/en-us/vsts/tfs-server/requirement-changes-tfs16?view=tfs-2018)
* Content Source: [docs/tfs-server/requirement-changes-tfs16.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/tfs-server/requirement-changes-tfs16.md)
* Service: **unspecified**
* Product: **devops-server**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by elbatk** [comment]
Ah, yes, you're right @xdaDaveShaw , I'll make this apparent in the docs, thank you!
