### ISSUE TITLE
The JS snippet to discover group identifiers no longer works

### ISSUE THREAD

**Issue by jkeech** [MicrosoftDocs/vsts-docs#900]
After pasting the JS snippet into the F12 console, it doesn't seem to have any effect on the rendered context menus. I tried a couple different menus on VSTS. Is this code outdated due to VSTS changes? What is the current way to discover context menu group identifiers?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b46557dc-2e49-b914-105e-9235c7dbf860
* Version Independent ID: 42901bac-88ea-acb6-cf5e-6086b3223a9a
* Content: [Discover menu group identifiers](https://docs.microsoft.com/en-us/vsts/extend/test/discover-menu-group-ids?view=vsts#feedback)
* Content Source: [docs/extend/test/discover-menu-group-ids.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/extend/test/discover-menu-group-ids.md)
* Service: **unspecified**
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by elbatk** [comment]
Hi @jkeech , I've reached out to the product team to try to get this thing figured out for you. Hopefully we can get you an answer and update the article soon if needed!

**Comment by chcomley** [comment]
Hi there, this issue has been stale for close to one year. I'll be closing this issue, however please @mention me if you'd like me to reopen or create a new issue, if problems remain. Thank you!
