### ISSUE TITLE
"Build job timeout in minutes (VSTS, TFS 2017.3 and newer)" should be "Build job cancel timeout in minutes (VSTS, TFS 2017.3 and newer)"

### ISSUE THREAD

**Issue by mydiemho** [MicrosoftDocs/vsts-docs#901]
There's already a "Build job timeout in minutes".  The second section should be "Build job cancel timeout in minutes"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0fa5a83c-70fd-6925-a8c8-256b21c21a2e
* Version Independent ID: 75f4a136-7245-7878-2953-6b68272fe4ec
* Content: [Build definition options](https://docs.microsoft.com/en-us/vsts/build-release/concepts/definitions/build/options?view=vsts#job-cancel-timeout)
* Content Source: [docs/build-release/concepts/definitions/build/options.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/build-release/concepts/definitions/build/options.md)
* Service: **unspecified**
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by steved0x** [comment]
Content refactored and the updated content no longer has the mistake:
https://docs.microsoft.com/en-us/azure/devops/pipelines/process/phases?view=azure-devops&tabs=yaml
