### ISSUE TITLE
The link doesn't work (Deploy: Azure SQL Database Deployment)

### ISSUE THREAD

**Issue by trumhemcut** [MicrosoftDocs/vsts-docs#907]
Hi,

I tried to open this link https://docs.microsoft.com/en-us/vsts/build-release/tasks/deploy/azure-sql-database-deployment?view=vsts but it doesn't work

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 39fe3a05-aeb1-5a05-1bba-34aa733c9bb3
* Version Independent ID: ff3b8383-6df0-60f6-a898-c1ae5792efe0
* Content: [Deploy your database to Azure SQL Database using DACPACs](https://docs.microsoft.com/en-us/vsts/build-release/apps/cd/deploy-dacpac-sqlpackage?view=vsts)
* Content Source: [docs/build-release/apps/cd/deploy-dacpac-sqlpackage.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/build-release/apps/cd/deploy-dacpac-sqlpackage.md)
* Service: **unspecified**
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by nschonni** [comment]
Should be fixed with #841

**Comment by thomps23** [comment]
Confirmed as fixed. Closing.
