### ISSUE TITLE
Full source code

### ISSUE THREAD

**Issue by vietkuong** [MicrosoftDocs/vsts-docs#908]
Hi,
Can you provide full source code for this example? I've tried but my extension doesn't work, not sure what's wrong, I need your source code to compare. Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6e6cb0ed-c129-901c-10a2-909354aa562f
* Version Independent ID: ceb10d41-b306-0d3f-ccb2-124a3ba69332
* Content: [Add a custom control to the work item form](https://docs.microsoft.com/en-us/vsts/extend/develop/custom-control?view=vsts)
* Content Source: [docs/extend/develop/custom-control.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/extend/develop/custom-control.md)
* Service: **unspecified**
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by nschonni** [comment]
A bunch are over here https://github.com/Microsoft/vsts-extension-samples, but I don't see that particular one

**Comment by elbatk** [comment]
Hi @vietkuong , all of our full samples are in the github repo that @nschonni has pointed out, if it's not there then we likely don't have it. What problem(s) are you seeing?

**Comment by JanZiese** [comment]
I think the full code for this sample is available here: https://github.com/Microsoft/vsts-extension-color-control

**Comment by elbatk** [comment]
Going to close this issue for now - creating new samples and better ramp-up documentation is on the backlog for writing extensions so hopefully that will address some documentation gaps found here.
