### ISSUE TITLE
Format code as XML

### ISSUE THREAD

**Issue by Styxxy** [MicrosoftDocs/vsts-docs#91]
Take page https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/work/customize/reference/all-witd-xml-elements-reference.md

In the table the code blocks should be formatted as XML for readability.

Normally I would submit a PR, however the table is written in HTML, so I am not sure how to change the code to include XML code formatting.

**Comment by steved0x** [comment]
@Styxxy Thank you for letting us know, I am filing a work item with the author of this topic to take a look (and it looks like there are a couple of similar topics that are similar as well). Thanks again!
