### ISSUE TITLE
Link to Keyvault setting is missing

### ISSUE THREAD

**Issue by artisticcheese** [MicrosoftDocs/vsts-docs#911]
For my variable group I can not see "link to keyvault" option in VSTS.

![vmconnect_2018-05-29_10-30-11](https://user-images.githubusercontent.com/13176884/40669046-a10d755e-632b-11e8-8a08-d8f93833537c.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4827aa99-ae62-bd63-6f2f-a87a4065ed27
* Version Independent ID: c9e461ee-7f42-3503-9460-18fa3a807bbb
* Content: [Variable groups for VSTS and TFS](https://docs.microsoft.com/en-us/vsts/pipelines/library/variable-groups?view=vsts#link-secrets-from-an-azure-key-vault-as-variables)
* Content Source: [docs/pipelines/library/variable-groups.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/pipelines/library/variable-groups.md)
* Service: **unspecified**
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment]
Thank you for your feedback. I have passed this on to the product team for advice.

**Comment by artisticcheese** [comment]
Can not send to that email, it replied with 

```

Your message to vsse@microsoft.com couldn't be delivered.
--
The group vsse only accepts messages from people in its organization or on its allowed senders list, and your email address isn't on the list.


```

**Comment by artisticcheese** [comment]
FYI if anybody else find the same issue. This feature is not GA and have to be enabled manually by Microsoft on your account.

**Comment by imalokagrawal** [comment]
@artisticcheese - This feature is actually GA. Due to a bug, this feature is not getting enabled by default for our new accounts. We are working on fixing this bug.

Thanks for your support.
