### ISSUE TITLE
Search across "collections"

### ISSUE THREAD

**Issue by 2Dews** [MicrosoftDocs/vsts-docs#912]
It appears as though  the search functionality does not search across all collections. Our organization has many collections and it would be nice to search all of them at once. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1619be8b-c51b-b8f8-a590-d14fa524714b
* Version Independent ID: 5e0b06c3-0fad-105c-1ade-4d448844c7ef
* Content: [Search across all your code and work items](https://docs.microsoft.com/en-us/vsts/search/overview?view=vsts)
* Content Source: [docs/search/overview.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/search/overview.md)
* Service: **unspecified**
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment]
Please file a request at https://visualstudio.uservoice.com/forums/330519-team-services. If there are sufficient votes it may be implemented in the product. Thank you!
