### ISSUE TITLE
Custom build task with multi-version upload error 

### ISSUE THREAD

**Issue by sameer-kumar** [MicrosoftDocs/vsts-docs#913]
I get this error when uploading vsix to TFS 2017.1 - "**The task.json file was not found in contribution xxx**"

When I create a vsix of my custom build task with flat structure it works like a charm. But when I introduce new folder scheme which allows multiple version of a task then it poops out during upload of the vsix extension in TFS.
I guess my Contributions are messed up:
```
"contributions": [
        {
            "id": "TfsExtension-Build-Task-JsonTokenizer",
            "type": "ms.vss-distributed-task.task",
            "description": "Tokenizes a json file.",
            "targets": [
				"ms.vss-distributed-task.tasks"
            ],
            "properties": {
				"name": "JsonTokenizer"
			}
        }
    ]
```
I think it is looking for task.json inside JsonTokenizer folder but NOT enumerating deeper in this folder. My folder structure is like this:

E:\\
|-- Org-Extensions
|--- icon.png
|--- vss-extension.json
|--- JsonTokenizer
|---- JsonTokenizerV1
|------ task.json
|------ script.ps1
|------ readme.md
|------ ps_modules
|--------***
|---- JsonTokenizerV2
|------ task.json
|------ script.ps1
|------ readme.md
|------ ps_modules
|--------***

Any documentation or sample with multiple version support is appreciated.

Thanks,
Sam

**Comment by elbatk** [comment]
Ah, this should be working according to this document: https://github.com/MicrosoftDocs/vsts-docs/issues/913#event-1654134332

Adding @willsmythe to take a look!

**Comment by willsmythe** [comment]
@chrisrpatterson - can you help on this?

**Comment by chrisrpatterson** [comment]
Get ride of the JasonTokenizer in the hierarchy and explicitly list each version.  Also I am not sure off the top of my head if multi-version is supported in 2017.1

**Comment by elbatk** [comment]
Hi everyone, doing some Spring cleaning of our backlog here, this issue seems to be resolved so I'm going to go ahead and close it!
