### ISSUE TITLE
Variable substitution is not working for cases where configSource attribute is used to point to external file

### ISSUE THREAD

**Issue by artisticcheese** [MicrosoftDocs/vsts-docs#915]
Hello,

If web.config specifies configSource to external file then variable substitution in XML file is not working. Code shall parse configsource and perform replacement there. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 315ff823-9992-9f9b-62a1-42ce622ed41c
* Version Independent ID: 72ec3ffc-1dc9-b2dc-e3d4-4f14deae3720
* Content: [File transforms and variable substitution](https://docs.microsoft.com/en-us/vsts/pipelines/tasks/transforms-variable-substitution?view=vsts)
* Content Source: [docs/pipelines/tasks/transforms-variable-substitution.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/pipelines/tasks/transforms-variable-substitution.md)
* Service: **unspecified**
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment]
Thank you for your feedback. I have passed this on to the product team for advice.

**Comment by RoopeshNair** [comment]
@artisticcheese  - can you please elaborate? are you referring to SetParameters.xml file here?

**Comment by RoopeshNair** [comment]
Got it, marking this as an enhancement, will add it to our backlog
