### ISSUE TITLE
Syntax bug in "Code Highlighting" example

### ISSUE THREAD

**Issue by aapalm** [MicrosoftDocs/vsts-docs#916]
In Edge, the "To install the Microsoft VSTS Cross Platform Build & Release Agent..." code highlighting example is somehow rendering the example with plus (+) signs:

+Example: + +
+To install the Microsoft VSTS Cross Platform Build & Release Agent, run the following: `$ sudo npm install vsoagent-installer -g`.
+

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 63e81f8a-e33c-afb7-493b-f51f40fafd49
* Version Independent ID: c9495a96-c3e8-00f1-1e53-da6ce584412b
* Content: [Syntax usage for Markdown files, widgets, wikis, and pull requests - VSTS & TFS](https://docs.microsoft.com/en-us/vsts/collaborate/markdown-guidance?view=vsts)
* Content Source: [docs/collaborate/markdown-guidance.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/collaborate/markdown-guidance.md)
* Service: **unspecified**
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@aapalm - Thank you for your correction. I'm updating the topic and the changes should be live later today.

**Comment by paiw** [comment]
Yes

รับ Outlook for iOS<https://aka.ms/o0ukef>
________________________________
