### ISSUE TITLE
Possible typo: missing "to"

### ISSUE THREAD

**Issue by jwatkin** [MicrosoftDocs/vsts-docs#917]
In the sentence fragment: "... the pipeline stages each successive environment the next upon successful completion of tests.", should it have been this instead: "... the pipeline stages each successive environment to the next upon successful completion of tests."?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 895ed016-6ddc-3458-db9e-ebbedf218982
* Version Independent ID: 36e017f5-b012-fcec-6906-1966f3a97cb4
* Content: [What is Continuous Delivery? - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/what-is-continuous-delivery#feedback)
* Content Source: [https://mseng.visualstudio.com/DefaultCollection/TechnicalContent/_git/devops-learn-pr?path=%2fdocs%2fwhat-is-continuous-delivery.md&version=GBlive&_a=contents](https://mseng.visualstudio.com/DefaultCollection/TechnicalContent/_git/devops-learn-pr?path=%2fdocs%2fwhat-is-continuous-delivery.md&version=GBlive&_a=contents)
* Service: **unspecified**
* Product: **devops**
* GitHub Login: @samgu
* Microsoft Alias: **samgu**

**Comment by steved0x** [comment]
Fixed and should be live very soon, thank you for letting us know and apologies for the great delay.
