### ISSUE TITLE
Migrate wikis to another account

### ISSUE THREAD

**Issue by ronnieghosh** [MicrosoftDocs/vsts-docs#918]
On line 13, we are pushing back the changes to the same project in the same account. What should I do if I want to push the wiki to a another project in another account?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 89127967-cf31-edd5-53f3-bad14d30e651
* Version Independent ID: 576a9e5b-8a3b-ff49-e6e1-d193c26f6093
* Content: [Migrate wiki extension pages - VSTS & TFS](https://docs.microsoft.com/en-us/vsts/collaborate/migrate-extension-wiki-pages?view=vsts)
* Content Source: [docs/collaborate/migrate-extension-wiki-pages.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/collaborate/migrate-extension-wiki-pages.md)
* Service: **unspecified**
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@ronnieghosh - Thank you for your inquiry. If you are on VSTS, I believe you can migrate the wiki content to whatever project you want. I suggest reviewing these two topics:
- [Clone and update wiki content offline](https://docs.microsoft.com/en-us/vsts/collaborate/wiki-update-offline?view=vsts)
- [Publish a Git repository to a wiki](https://docs.microsoft.com/en-us/vsts/collaborate/publish-repo-to-wiki?view=vsts).
