### ISSUE TITLE
Which version and update of Team Foundation Server do you need in order to use YAML builds?

### ISSUE THREAD

**Issue by Advanium** [MicrosoftDocs/vsts-docs#922]
This article doesn't tell you which version of Team Foundation Server supports the use of YAML builds. I noticed TFS 2018 Update 1 doesn't have that feature yet, so it's propably supported from TFS 2018 Update 2 onwards, right?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 87686bea-7c46-cd47-d1a9-128e16b63a23
* Version Independent ID: ace78317-e562-e35d-781d-23cd7d2dfff2
* Content: [CI Build in code using YAML](https://docs.microsoft.com/en-us/vsts/pipelines/get-started-yaml?view=vsts)
* Content Source: [docs/pipelines/get-started-yaml.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/pipelines/get-started-yaml.md)
* Service: **unspecified**
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by andyjlewis** [comment]
It's not yet in TFS.

**Comment by Advanium** [comment]
Hi @andyjlewis,

would you then please update the documentation to not speak of TFS as of yet? That's kind of confusing.

Thank you.

**Comment by andyjlewis** [comment]
agree, good catch, thanks, will do

**Comment by fullerth** [comment]
Is there a roadmap for TFS getting support for YAML builds?

**Comment by andyjlewis** [comment]
Yes, the roadmap is here: https://docs.microsoft.com/en-us/vsts/release-notes/

**Comment by andyjlewis** [comment]
Thanks for raising this issue. The topic no longer speaks of TFS.
