### ISSUE TITLE
WARNING: The DOCKER_REGISTRY variable is not set

### ISSUE THREAD

**Issue by alvipeo** [MicrosoftDocs/vsts-docs#923]
I have this warning when I try to build a container locally and then that same warning becomes an error in VSTS build. I just created a standard ASP.NET MVC solutions with Docker support (NOT Core).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0fc9593a-77be-75c1-8d20-86a995d925f6
* Version Independent ID: 63c81326-3b7a-8452-bc04-95ff06e517a7
* Content: [Build and push a Docker image](https://docs.microsoft.com/en-us/vsts/pipelines/apps/containers/build?view=vsts&tabs=web)
* Content Source: [docs/pipelines/apps/containers/build.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/pipelines/apps/containers/build.md)
* Service: **unspecified**
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by MarkusAnthony** [comment]
Same here, any update?

**Comment by andyjlewis** [comment]
Hi @alvipeo and @MarkusAnthony. We recently published some major updates, including https://docs.microsoft.com/en-us/azure/devops/pipelines/languages/docker. Please give it a try.
