### ISSUE TITLE
Section on TFS 2017 agent versions is incomplete and incorrect

### ISSUE THREAD

**Issue by TASlavens** [MicrosoftDocs/vsts-docs#924]
TFS 2017u2 provided agent version 2.117.2 and TFS 2017u3.1 (and presumably also 2017u3) provided agent version 2.122.1, so it seems very unlikely that the listed agent version 2.112.0 is correct - maybe that's the correct agent version for TFS 2017u1, but surely not for 2017u3.  Currently the list doesn't include TFS 2017u1 and 2017u2; I suppose we can assume that 2017u3.1 (also not listed) provides the same agent version as 2017u3, but I believe it would be better to have that explicitly listed as well, or at least include a note that it is the same.  Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43799c5d-2f13-cc76-a1c0-a3f850e16d4e
* Version Independent ID: 97a5b73f-faf7-f9c0-9269-fc79984616d6
* Content: [Deploy a build and release agent on Windows](https://docs.microsoft.com/en-us/vsts/pipelines/agents/v2-windows?view=tfs-2017)
* Content Source: [docs/pipelines/agents/v2-windows.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/pipelines/agents/v2-windows.md)
* Service: **unspecified**
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by vtbassmatt** [comment]
Addressed in a pending docs change
