### ISSUE TITLE
Warning : Option 2 is very hard for migration from non-English TFS to VSTS

### ISSUE THREAD

**Issue by nakamacchi** [MicrosoftDocs/vsts-docs#926]
If you use non-English TFS, it is very difficult to use Option 2, because VSTS WIT requires the WIT data is English-based. The migration scenario from non-English TFS to VSTS, you have to modify the TFS WIT manually before migration. In many cases it is very tough and difficult task.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 848d1786-556b-cd92-7a84-a4bd0b16facd
* Version Independent ID: ebf6bd4c-9e27-2faf-2b86-d3b3332ac189
* Content: [Migration options for migrating from TFS to VSTS](https://docs.microsoft.com/en-us/vsts/articles/migrate-to-vsts-from-tfs?view=vsts)
* Content Source: [docs/articles/migrate-to-vsts-from-tfs.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/articles/migrate-to-vsts-from-tfs.md)
* Service: **unspecified**
* Product: **devops**
* GitHub Login: @aaronhallberg
* Microsoft Alias: **aaronha**

**Comment by nakamacchi** [comment]
Also created a product feedback.
https://developercommunity.visualstudio.com/content/problem/263991/please-provide-the-option-to-ignore-the-wit-data-m.html

**Comment by nakamacchi** [comment]
Also created a product feedback. (which is the correct location?)
https://visualstudio.uservoice.com/forums/330519-visual-studio-team-services/suggestions/34404625-please-provide-the-option-to-ignore-the-wit-data-m

**Comment by steved0x** [comment]
@nakamacchi The first one is correct, [https://developercommunity.visualstudio.com/spaces/21/index.html](https://developercommunity.visualstudio.com/spaces/21/index.html) is where to report product issues. I will see if we can get this article updated to provide more information and sorry that you ran into trouble. Thank you for letting us know.
