### ISSUE TITLE
mseng link used in release-notes/2017/jun-22-team-services.md

### ISSUE THREAD

**Issue by nschonni** [MicrosoftDocs/vsts-docs#941]
https://github.com/MicrosoftDocs/vsts-docs/blob/master/release-notes/2017/jun-22-team-services.md
The link is to https://mseng.visualstudio.com/docs/collaborate/preview-features but that isn't available to users outside of Microsoft Engineering.

**Comment by steved0x** [comment]
@nschonni Whoops :) I'll get that fixed, once I figure out where it should point... I think to [https://docs.microsoft.com/en-us/vsts/collaborate/preview-features?view=vsts](https://docs.microsoft.com/en-us/vsts/collaborate/preview-features?view=vsts)

**Comment by steved0x** [comment]
`but that isn't available to users outside of Microsoft Engineering.` or to inside either, that is a bad link :)

**Comment by nschonni** [comment]
This looks fixed
