### ISSUE TITLE
Markdown not parsed on 'Add and manage dashboards'

### ISSUE THREAD

**Issue by simondel** [MicrosoftDocs/vsts-docs#942]
On the [Add and manage dashboards page](https://docs.microsoft.com/en-us/vsts/report/dashboards/dashboards?view=vsts&tabs=new-query-exp#manage-dashboards) the markdown is not properly parsed at the start of the article:
![image](https://user-images.githubusercontent.com/4221997/40764735-6e85919a-64aa-11e8-9050-bc89a6ee672f.png)

It seems to be [this md file](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/report/_shared/dashboard-prerequisites-vsts.md), which does render correctly on GitHub. The rest of the page does render properly.

Tested in IE, Edge and Chrome

**Comment by KathrynEE** [comment]
@simondel - Thank you for the correction. I've updated the topic and the changes should appear later today.
