### ISSUE TITLE
Available event types

### ISSUE THREAD

**Issue by HaydnFidler** [MicrosoftDocs/vsts-docs#946]
Can we extend the list of available event types? In particular, I want to know when the wiki is updated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6033d681-9093-547c-20fd-b31183c2bb33
* Version Independent ID: 0d92e3f0-7fb4-57e5-d913-f305a055a819
* Content: [Service hooks event reference](https://docs.microsoft.com/en-us/vsts/service-hooks/events?toc=/vsts/integrate/toc.json&bc=/vsts/integrate/breadcrumb/toc.json&view=vsts)
* Content Source: [docs/service-hooks/events.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/service-hooks/events.md)
* Service: **unspecified**
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by steved0x** [comment]
@HaydnFidler You can submit a feature request to have more events added to the Wiki, by to the product team [here](https://developercommunity.visualstudio.com/spaces/21/index.html). I don't see any Wiki events on this doc page (and I'm not familiar with Wikis) so I am assigning this to the author of that Service hooks events topic for their feedback - they may have more up to date information to share.

**Comment by elbatk** [comment]
Hi @HaydnFidler , reaching out to the owner of Service Hooks implementation to see if I can't get an answer for ya!

**Comment by sandeepchads** [comment]
Hi,

We have this on our backlog but I dont have an ETA on this yet. You can upvote the user voice so that you can get updates on when we implement this feature:
https://visualstudio.uservoice.com/forums/330519-visual-studio-team-services/suggestions/20285818-service-hooks-to-support-new-wiki

Thanks
Sandeep Chadda

**Comment by elbatk** [comment]
Hi everyone! Doing some cleaning of the backlog here. I don't believe we use UserVoice anymore, but you can post your questions/requests to the [Azure DevOps Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html) which is monitored by the product team. Best of luck!
