### ISSUE TITLE
XML Transformation fails with :  System.NullReferenceException: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by rahulvmarathe** [MicrosoftDocs/vsts-docs#948]
The error occurs as attributes referenced in the transformation files (web.release.config) are missing from the web.config. This may happen if the transformation is applied during the build stage. The documentation does call this out. However to disable the XML transformation during the build phase build phase I had to use /p:TransformWebConfigEnabled=false msbuild argument. Contrary to the Notes removing DependentUpon from the project file does not disable XML transformation during the build phase.

I was able to successfully build, transform and deploy after using  /p:TransformWebConfigEnabled=false msbuild argument.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 315ff823-9992-9f9b-62a1-42ce622ed41c
* Version Independent ID: 72ec3ffc-1dc9-b2dc-e3d4-4f14deae3720
* Content: [File transforms and variable substitution](https://docs.microsoft.com/en-us/vsts/pipelines/tasks/transforms-variable-substitution?view=vsts#xml-transformation)
* Content Source: [docs/pipelines/tasks/transforms-variable-substitution.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/pipelines/tasks/transforms-variable-substitution.md)
* Service: **unspecified**
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment]
Thank you for your feedback. I will pass this on to the product team and update the topic based on their response.
