### ISSUE TITLE
Alternative to using the Checkout submodules option - PAT must be Base64 string

### ISSUE THREAD

**Issue by kdubau** [MicrosoftDocs/vsts-docs#951]
`git -c http.https://<url of submodule repository>.extraheader="AUTHORIZATION: basic ********" submodule update --init --recursive`

>Use a secret variable in your project or build definition to store the personal access token (PAT) that you generate in VSTS or GitHub with access to your submodules. Use that variable to populate the secret in the above Git command.

The docs here fail to mention that you must first encode your PAT as a Base64 string which is explained here: https://docs.microsoft.com/en-us/vsts/integrate/get-started/authentication/pats?view=vsts#create-personal-access-tokens-to-authenticate-access

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 41d4fcf8-3fd9-27b5-89e5-a026cc4a2b6a
* Version Independent ID: 76481ffb-aec5-50cd-6cdd-9e53c59e2933
* Content: [Build definition source repositories](https://docs.microsoft.com/en-us/vsts/pipelines/build/repository?view=vsts#alternative-to-using-the-checkout-submodules-option)
* Content Source: [docs/pipelines/build/repository.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/pipelines/build/repository.md)
* Service: **unspecified**
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by kdubau** [comment]
Good bot but I don't think it's fixed yet! 😄

**Comment by andyjlewis** [comment]
@steved0x to confirm if this issue has been resolved in some of the changes we've made recently.

**Comment by steved0x** [comment]
Those documents have been refactored and the new content has this information:

https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/azure-repos-git?view=azure-devops&tabs=yaml#authorize-access-to-your-repositories
