### ISSUE TITLE
Some issue populate getting marked with MSeng internal repo

### ISSUE THREAD

**Issue by nschonni** [MicrosoftDocs/vsts-docs#952]
Noticed on a few issue templates that it seems to get the `Content Source` set as urls pointing to `https://mseng.visualstudio.com/DefaultCollection/TechnicalContent`
This doesn't appear to be specific to MS employees that would be visiting inside, so maybe it's something related to the live/private cut over.

EX: https://github.com/search?p=2&q=org%3AMicrosoftDocs+https%3A%2F%2Fmseng.visualstudio.com%2FDefaultCollection%2FTechnicalContent&type=Issues

**Comment by steved0x** [comment]
@nschonni Let me see if I can figure out why this is happening and get them fixed.

**Comment by steved0x** [comment]
This happens when there is no public repo for the feedback control to point to, it should be fixed now for our various doc sets.
