### ISSUE TITLE
Several images are not showing on this page

### ISSUE THREAD

**Issue by neraath** [MicrosoftDocs/vsts-docs#962]
There appear to be several images that fail to render on this page. I can see the references to them:
![Schematic showing tasks](_img/2017-user-experience/Process parameters view 1.png)
![Schematic showing tasks](_img/2017-user-experience/Tasks linking.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8b96fad0-7bfb-8c02-701a-5960da7fb313
* Version Independent ID: 74847500-c617-31f4-999c-a344e7b4299e
* Content: [New Build Editor](https://docs.microsoft.com/en-us/vsts/pipelines/archive/preview/2017-user-experience?view=vsts#feedback)
* Content Source: [docs/pipelines/archive/preview/2017-user-experience.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/pipelines/archive/preview/2017-user-experience.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by steved0x** [comment]
@neraath This is fixed now and should be live later today. Thanks for letting us know and sorry for the delay.
