### ISSUE TITLE
Incorrect title for typescript sections

### ISSUE THREAD

**Issue by Liran-Dobrish** [MicrosoftDocs/vsts-docs#965]
Title for typescript shows javascript

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d966f184-5f28-f746-ed60-6afedc044d47
* Version Independent ID: 274ed471-e63f-47db-c9df-595e0173ea1a
* Content: [Use the Combo Control](https://docs.microsoft.com/en-us/vsts/extend/develop/ui-controls/comboo?view=vsts#typescript_list)
* Content Source: [docs/extend/develop/ui-controls/comboo.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/extend/develop/ui-controls/comboo.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by elbatk** [comment]
Ah, yes they do. They must have gotten switched over somehow when we moved docs locations! I'll get this sorted out, thanks @Liran-Dobrish !

**Comment by froens** [comment]
@elbatk
The titles are still wrong
