### ISSUE TITLE
workitem custom extensions

### ISSUE THREAD

**Issue by Liran-Dobrish** [MicrosoftDocs/vsts-docs#966]
The examples here don't work when used in work item custom controls.
the popup section is limited by the control's iframe.
i have tried using the combobox with tree and a simple one., both had there popup section limited by the iframe (visibly cut)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d966f184-5f28-f746-ed60-6afedc044d47
* Version Independent ID: 274ed471-e63f-47db-c9df-595e0173ea1a
* Content: [Use the Combo Control](https://docs.microsoft.com/en-us/vsts/extend/develop/ui-controls/comboo?view=vsts#typescript_list)
* Content Source: [docs/extend/develop/ui-controls/comboo.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/extend/develop/ui-controls/comboo.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by Liran-Dobrish** [comment]
the problem is that the body where the control is hosted does not show the correct size when the control is clicked, it shows 20px. (i had to find the drop down div to get the correct size)
it's missing a way to better control the resize from the control.
it's missing a means to know when it has been clicked (i need to register multiple elements, the button , input , blur,...)

**Comment by elbatk** [comment]
Hi @Liran-Dobrish , I'm doing some cleaning of our backlog. Sorry we never got to you on this one, please forgive us (me, mostly!). If you're having an issue with the product, please post to the [Azure DevOps Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html), it is actively monitored by the product teams and you'll get better answers there. If there are docs consequences, please feel free to reach back out, thank you!
