### ISSUE TITLE
incorrect API used

### ISSUE THREAD

**Issue by Liran-Dobrish** [MicrosoftDocs/vsts-docs#967]
Some of the properties used in the examples are not valid / don't exists when using typescript
example: 
* width
* sepChar

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d966f184-5f28-f746-ed60-6afedc044d47
* Version Independent ID: 274ed471-e63f-47db-c9df-595e0173ea1a
* Content: [Use the Combo Control](https://docs.microsoft.com/en-us/vsts/extend/develop/ui-controls/comboo?view=vsts#typescript_list)
* Content Source: [docs/extend/develop/ui-controls/comboo.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/extend/develop/ui-controls/comboo.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by elbatk** [comment]
Ah, that's misleading. I'll sort this one out too @Liran-Dobrish thanks again!

**Comment by Liran-Dobrish** [comment]
any progress?

**Comment by elbatk** [comment]
Hi @Liran-Dobrish , I've reached out to the product team but our backlogs have been pretty busy lately, I'll update here as soon as I hear something! I just re-sent the question :)

**Comment by Liran-Dobrish** [comment]
still in the backlog....?

**Comment by chcomley** [comment]
Closing this issue, as it's stale. Please @mention me if you'd like me to reopen this issue or we can create a new one. Thank you!
