### ISSUE TITLE
Linking of process parameters to release definitions

### ISSUE THREAD

**Issue by jrottmann** [MicrosoftDocs/vsts-docs#968]
The Links to 'Link' and 'Unlink' process parameters in a release definition are missing in TFS2018 Update 2. In Build definitions everything is okay.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8b96fad0-7bfb-8c02-701a-5960da7fb313
* Version Independent ID: 74847500-c617-31f4-999c-a344e7b4299e
* Content: [New Build Editor](https://docs.microsoft.com/en-us/vsts/pipelines/archive/preview/2017-user-experience?view=vsts#what-are-process-parameters)
* Content Source: [docs/pipelines/archive/preview/2017-user-experience.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/pipelines/archive/preview/2017-user-experience.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by alexhomer1** [comment]
Thank you for your feedback. I have passed this on to the product team for advice.

**Comment by imalokagrawal** [comment]
This feature is only available for Build and not yet for Release Management.
