### ISSUE TITLE
Broken hyperlinks

### ISSUE THREAD

**Issue by mahony** [MicrosoftDocs/vsts-docs#969]
In the Project Server section, the first two table rows contain "Synchronize TFS with Project Server" hyperlinks which result in a 404 error.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 641b37fc-f117-aca0-32f4-8ea9b73e9d71
* Version Independent ID: 211130c6-43b8-f47f-3589-cb4d2a330231
* Content: [Requirements and compatibility](https://docs.microsoft.com/en-us/tfs/server/requirements?view=vsts#project-server)
* Content Source: [docs/server/requirements.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/server/requirements.md)
* Product: **devops-server**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by elbatk** [comment]
Ah, you've actually shed some light on a lot of broken links in that docset.. thank you! Shipping the fix right now! @mahony

**Comment by elbatk** [comment]
Oh, and the issue was that it was adding ".md" to the end, so the correct link is:
https://docs.microsoft.com/en-us/vsts/work/tfs-ps-sync/sync-ps-tfs?view=tfs-2015
