### ISSUE TITLE
This doesn't seem to work with command-line .NET Core?

### ISSUE THREAD

**Issue by jholovacs** [MicrosoftDocs/vsts-docs#972]
I try something like `dotnet publish --configuration Release --self-contained true --runtime win-x64 MySolution.Application` and I get `C:\Program Files\dotnet\sdk\2.1.201\NuGet.targets(114,5): error :   Response status code does not indicate success: 401 (Unauthorized). [C:\Repos\MySolution\MySolution.Application\MySolution.Application.csproj]`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab0a3735-a9b0-2ed7-f08f-5321f55f8c90
* Version Independent ID: 2153f6c0-def7-eed1-286d-5e61c9fcbec4
* Content: [Use NuGet with VSTS feeds](https://docs.microsoft.com/en-us/vsts/package/nuget/nuget-exe?view=vsts)
* Content Source: [docs/package/nuget/nuget-exe.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/package/nuget/nuget-exe.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by elbatk** [comment]
Ah, looks like an auth issue. Adding @alexmullans to take a look for ya!

**Comment by alexmullans** [comment]
dotnet's auth story is a bit tricky. This page can help: https://docs.microsoft.com/en-us/vsts/package/nuget/dotnet-exe?view=vsts

**Comment by jholovacs** [comment]
That doesn't seem to work.  I created a PAT, ran the nuget command line
with the url set to v2 as the vsts documentation says to do.  `nuget
sources list` shows my repository.   When I try to run dotnet from the
command line, I get a 404 instead of a 401.  Progress?  In the wrong
direction?  Not sure how to tell.

**Comment by jholovacs** [comment]
NM, it looks like I was led astray by the VSTS documentation, I still
needed to keep it v3.

**Comment by elbatk** [comment]
hi @jholovacs , I know this is a while ago, but what part told you to use anything but v3? I could change that if it's incorrect :)

**Comment by jholovacs** [comment]
There's an "instructions" modal when setting up the package repo for how to
connect, basically suggested (at least the way I read it) that I needed to
use PAT and v2 to access this externally.

**Comment by androidand** [comment]
This doesn't seem to work on Visual Studio for Mac... It's possible to add a private NuGet repository from say VSTS and log in to that account in Visual Studio for Mac. However, the credentials don't seem to work for the NuGet Repository and VS for Mac nags about credentials. The same credentials work fine in Visual Studio (For PC). Please add instructions for VS for Mac. Why don't you release an IDE that works on all platforms.

**Comment by elbatk** [comment]
Adding @alexmullans to address some of the platform/credential questions here.

**Comment by alexmullans** [comment]
As of today, the new cross-platform [Credential Provider](https://github.com/Microsoft/artifacts-credprovider) is the way to go if you're using dotnet on the command line (regardless of platform). For VS for Mac, instructions are available here: https://docs.microsoft.com/en-us/azure/devops/artifacts/nuget/consume?view=vsts&tabs=new-nav#macos-add-the-feed-to-your-nuget-configuration

**Comment by alexmullans** [comment]
That should work. @keithrob any ideas?

**Comment by keithrob** [comment]
@andreesteve,
Are you using TFS or Visualstudio.com?

**Comment by andreesteve** [comment]
@keithrob I am using visualstudio.com (that's where the feed is). Here's dotnet --info if it helps:

```
.NET Core SDK (reflecting any global.json):
 Version:   2.1.401
 Commit:    91b1c13032

Runtime Environment:
 OS Name:     arch
 OS Version:  
 OS Platform: Linux
 RID:         arch-x64
 Base Path:   /opt/dotnet/sdk/2.1.401/

Host (useful for support):
  Version: 2.1.3
  Commit:  124038c13e

.NET Core SDKs installed:
  2.1.401 [/opt/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.3 [/opt/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.3 [/opt/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.3 [/opt/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by keithrob** [comment]
@andreesteve ,
dotnet version looks fine.  Can you send the output of `tree $HOME\.nuget\plugins`?

**Comment by keithrob** [comment]
@andreesteve ,
Also, make sure that you do not have credentials anywhere in your nuget.config(s).

**Comment by andreesteve** [comment]
Contents of ~/.nuget:

```
/home/andre/.nuget/
/home/andre/.nuget/plugins
/home/andre/.nuget/plugins/netcore
/home/andre/.nuget/plugins/netcore/CredentialProvider.Microsoft
/home/andre/.nuget/plugins/netcore/CredentialProvider.Microsoft/Newtonsoft.Json.dll
/home/andre/.nuget/plugins/netcore/CredentialProvider.Microsoft/NuGet.Common.dll
/home/andre/.nuget/plugins/netcore/CredentialProvider.Microsoft/runtimes
/home/andre/.nuget/plugins/netcore/CredentialProvider.Microsoft/runtimes/unix
/home/andre/.nuget/plugins/netcore/CredentialProvider.Microsoft/runtimes/unix/lib
/home/andre/.nuget/plugins/netcore/CredentialProvider.Microsoft/runtimes/unix/lib/netstandard1.3
/home/andre/.nuget/plugins/netcore/CredentialProvider.Microsoft/runtimes/unix/lib/netstandard1.3/System.Security.Cryptography.ProtectedData.dll
/home/andre/.nuget/plugins/netcore/CredentialProvider.Microsoft/runtimes/win
/home/andre/.nuget/plugins/netcore/CredentialProvider.Microsoft/runtimes/win/lib
/home/andre/.nuget/plugins/netcore/CredentialProvider.Microsoft/runtimes/win/lib/netstandard1.3
/home/andre/.nuget/plugins/netcore/CredentialProvider.Microsoft/runtimes/win/lib/netstandard1.3/System.Security.Cryptography.ProtectedData.dll
/home/andre/.nuget/plugins/netcore/CredentialProvider.Microsoft/NuGet.Packaging.Core.dll
/home/andre/.nuget/plugins/netcore/CredentialProvider.Microsoft/CredentialProvider.Microsoft.pdb
/home/andre/.nuget/plugins/netcore/CredentialProvider.Microsoft/CredentialProvider.Microsoft.runtimeconfig.json
/home/andre/.nuget/plugins/netcore/CredentialProvider.Microsoft/PowerArgs.dll
/home/andre/.nuget/plugins/netcore/CredentialProvider.Microsoft/NuGet.Configuration.dll
/home/andre/.nuget/plugins/netcore/CredentialProvider.Microsoft/Microsoft.IdentityModel.Clients.ActiveDirectory.Platform.dll
/home/andre/.nuget/plugins/netcore/CredentialProvider.Microsoft/CredentialProvider.Microsoft.dll
/home/andre/.nuget/plugins/netcore/CredentialProvider.Microsoft/Microsoft.IdentityModel.Clients.ActiveDirectory.dll
/home/andre/.nuget/plugins/netcore/CredentialProvider.Microsoft/NuGet.Packaging.dll
/home/andre/.nuget/plugins/netcore/CredentialProvider.Microsoft/NuGet.Versioning.dll
/home/andre/.nuget/plugins/netcore/CredentialProvider.Microsoft/NuGet.Frameworks.dll
/home/andre/.nuget/plugins/netcore/CredentialProvider.Microsoft/CredentialProvider.Microsoft.deps.json
/home/andre/.nuget/plugins/netcore/CredentialProvider.Microsoft/NuGet.Protocol.dll
/home/andre/.nuget/NuGet
/home/andre/.nuget/NuGet/NuGet.Config
```

@keithrob I have no credentials anywhere in nuget.config(s) - when I actually add PAT there, it works, but I assume it is not using the new plugin.

Running ```dotnet restore``` on my project fails with:

```
/opt/dotnet/sdk/2.1.402/NuGet.targets(114,5): error : Unable to load the service index for source https://sample.pkgs.visualstudio.com/_packaging/Official/nuget/v3/index.json. [/home/andre/projects/d365/deployment/src/DeploymentServices/DeployServices.sln]
/opt/dotnet/sdk/2.1.402/NuGet.targets(114,5): error :   Response status code does not indicate success: 401 (Unauthorized). [/home/andre/projects/d365/deployment/src/DeploymentServices/DeployServices.sln]
```

Then I manually run the plugin and it retrieves the token with manual authentication when calling directly:

```
dotnet /home/andre/.nuget/plugins/netcore/CredentialProvider.Microsoft/CredentialProvider.Microsoft.dll -C -U https://sample.pkgs.visualstudio.com/_packaging/Official/nuget/v3/index.json -R
[Information] [CredentialProvider]Username: VssSessionToken
[Information] [CredentialProvider]Password: [REDACTED]
```

From verbose dotnet restore logs it shows the plugin is being loaded:

```
$ dotnet restore --interactive --verbosity diag

... (omitted some urls / paths)

Using /home/andre/.nuget/plugins/netcore/CredentialProvider.Microsoft/CredentialProvider.Microsoft.dll as a credential provider plugin. (TaskId:38)
17:10:08.562     1>/opt/dotnet/sdk/2.1.401/NuGet.targets(114,5): error : Unable to load the service index for source ...
/opt/dotnet/sdk/2.1.401/NuGet.targets(114,5): error :   Response status code does not indicate success: 401 (Unauthorized).  ...
                     NuGet.Protocol.Core.Types.FatalProtocolException: Unable to load the service index for source https://.....pkgs.visualstudio.com/_packaging/Official/nuget/v3/index.json. ---> System.Net.Http.HttpRequestException: Response status code does not indicate success: 401 (Unauthorized).
```

So looks like the plugin works by itself, is being loaded by dotnet restore but for some reason does to provide the auth token to dotnet restore, even if I call it manally beforehand to cache the auth token.

Any other logs I could look into?

**Comment by jinhong-** [comment]
By any chance are you on a Mac? I have a similar issue, plus i also spotted some error complaining about culture parameter is required. I got mine working by setting the LANG=en_US for my environment variable
