### ISSUE TITLE
Needs updated for newer Office versions

### ISSUE THREAD

**Issue by MSGriz** [MicrosoftDocs/vsts-docs#973]
Visual Studio 2015 has an FW Link to this doc, but Office 365 current release has different dialogs that do not match these instructions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e823a432-9aab-43ea-52e2-07512c0b5c55
* Version Independent ID: 93d6e60f-8c46-8ec1-68c8-ab8afc7f2359
* Content: [TF237002-Cannot open the document because Microsoft Excel 2007 or later, or one of its components is not installed - VSTS & TFS](https://docs.microsoft.com/en-us/vsts/work/customize/reference/error/tf237002-cannot-open-document-excel-not-installed?view=vsts#feedback)
* Content Source: [docs/work/customize/reference/error/tf237002-cannot-open-document-excel-not-installed.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/work/customize/reference/error/tf237002-cannot-open-document-excel-not-installed.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@MSGriz - Thank you for your comment. I've added a backlog item to update this topic and other Office articles to be more up-to-date.
