### ISSUE TITLE
Code Coverage

### ISSUE THREAD

**Issue by aboo** [MicrosoftDocs/vsts-docs#976]
When enabling TIA the code coverage result is generated just for the tests that are run therefore we cannot maintain our 100% code coverage. Any solution on how to keep the code coverage maintained while having TIA on?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6529216f-fe59-01f0-ae0e-3268dcfaeca2
* Version Independent ID: ef485353-2613-03f1-1dd0-da34d4e4dcda
* Content: [Speed up testing with Test Impact Analysis (TIA)](https://docs.microsoft.com/en-us/vsts/pipelines/test/test-impact-analysis?view=vsts)
* Content Source: [docs/pipelines/test/test-impact-analysis.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/pipelines/test/test-impact-analysis.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment]
Thank you for your feedback. I have passed this on to the product team for advice.

**Comment by aboo** [comment]
Any update on this?

**Comment by PBoraMSFT** [comment]
@aboo - no, there isn't a way around it. Coverage can only be collected for tests that are run.
