### ISSUE TITLE
TFS 2018 please

### ISSUE THREAD

**Issue by nk111** [MicrosoftDocs/vsts-docs#977]
I'd also really like to use this on TFS 2018 (without the update). Is this possible?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6cdab61-a70b-e725-cd74-f258620447b7
* Version Independent ID: ee1753a6-2b6c-8304-5cba-73b86606ebb3
* Content: [Visual Studio Test Platform Installer](https://docs.microsoft.com/en-us/vsts/pipelines/tasks/tool/vstest-platform-tool-installer?view=vsts)
* Content Source: [docs/pipelines/tasks/tool/vstest-platform-tool-installer.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/pipelines/tasks/tool/vstest-platform-tool-installer.md)
* Product: **devops**
* GitHub Login: @erickson-doug
* Microsoft Alias: **dastahel**

**Comment by DavidStaheli** [comment]
Hi @PBoraMSFT, do you know if the VS Test Platform installer task is compatible with TFS 2018 if we build it and upload it into TFS with the tfx-cli tool?

**Comment by PBoraMSFT** [comment]
@DavidStaheli - the installer task will install the platform, but the option to use that platform has to be chosen in the VSTest task, so the update to VSTest task is also needed for the scenario to work. So, using the tfx-cli for this isn't recommended.

**Comment by DavidStaheli** [comment]
Thanks a lot, @PBoraMSFT.  @nk111 I'm sorry this doesn't yet meet your needs.  😞

**Comment by nk111** [comment]
Thank you very much @PBoraMSFT & @DavidStaheli ! In the meantime i had to install SSDT to complete another task and this also installed a visual studio 17 instance. I then added a "user function" VSTest" with the path pointing to this instance. The build completes. I wonder if i could somehow update my agent so the vstest capability is recognized automatically? A simple restart of the agent service doesn't seem to be enough for that...

**Comment by PBoraMSFT** [comment]
@nk111 - agent restart should recognize the VS install and gain the vstest capability automatically with that. Which version of VS do you have - details from Help->About would help..

**Comment by nk111** [comment]
unfortunately i still get the message that no agent could be found with "msbuild, visualstudio, vstest".

this is the output from vs on the build machine:

Microsoft SQL Server Data Tools for Visual Studio 2017  (SSDT)
Version 15.7.3
VisualStudio.15.Release/15.7.3+27703.2026
Microsoft .NET Framework
Version 4.7.02558

Installed Version: IDE Standard

C# Tools   2.8.3-beta6-62923-07. Commit Hash: 7aafab561e449da50712e16c9e81742b8e7a2969
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

NuGet Package Manager   4.6.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

ResourcePackage Extension   1.0
ResourcePackage Visual Studio Extension Detailed Info

SQL Server Data Tools   15.1.61804.210
Microsoft SQL Server Data Tools

Visual Basic Tools   2.8.3-beta6-62923-07. Commit Hash: 7aafab561e449da50712e16c9e81742b8e7a2969
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

**Comment by ShreyasRmsft** [comment]
Does the SSDT installation install vstest.console.exe on the machine? Can you check under the installation path whether this file exists and share the path if it does?

Also are you installing SSDT via the standalone installer or as a workflow in the VS installer?

**Comment by nk111** [comment]
@ShreyasRmsft i did install SSDT via standalone installer. One possible reason could be that i had to install SSDT into a new subfolder under the existing "Visual Studio \ 2017" path. When i tried using the existing path (C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools) created by the agent the installation exited with an error. So SSDT was installed to "C:\Program Files (x86)\Microsoft Visual Studio\2017\SQL". And yes.  "C:\Program Files (x86)\Microsoft Visual Studio\2017\SQL\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe" exists.

**Comment by kaadhina** [comment]
@nk111 The VSTest task does not support running tests via an SSDT installation. You can instead use the Visual Studio Test Platform Installer task to get the requirements onto the agent and use it to run tests using VSTest task. 
https://docs.microsoft.com/en-us/vsts/release-notes/2017/nov-28-vsts has instructions about how to use this.

**Comment by nk111** [comment]
@kaadhina unfortunately this task is not available for TFS2018 only for TFS2018.2 (which is not installed on our production system yet).

**Comment by PBoraMSFT** [comment]
Closing this issue as the questions have already been addressed, but the issue remained open for some reason.
