### ISSUE TITLE
The Prerequisites title is displayed as markdown instead of HTML.

### ISSUE THREAD

**Issue by jawn** [MicrosoftDocs/vsts-docs#978]
The Prerequisites title is displayed in markdown instead of HTML.

![image](https://user-images.githubusercontent.com/1705112/40961987-84b04336-68a4-11e8-8dc6-0988f6612c91.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7dff2777-0bde-c6ae-c421-b6c1a3f536a8
* Version Independent ID: 1943469d-b7c3-5d41-5715-da86961a83f5
* Content: [Manage issues or impediments - VSTS & TFS](https://docs.microsoft.com/en-us/vsts/work/backlogs/manage-issues-impediments?toc=/vsts/work/work-items/toc.json&bc=/vsts/work/work-items/breadcrumb/toc.json&view=vsts)
* Content Source: [docs/work/backlogs/manage-issues-impediments.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/work/backlogs/manage-issues-impediments.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by jawn** [comment]
This sounds like product feedback instead of a documentation issue. There's a different link to give feedback.

**Comment by steved0x** [comment]
@jawn This is good documentation feedback, I am assigning to the author and we'll get that formatting fixed. Thank you for letting us know.

**Comment by KathrynEE** [comment]
@jawn - Thank you for the feedback. I'm correcting the affected topics and they'll be live later today.
