### ISSUE TITLE
'run' script can't handle spaces in path

### ISSUE THREAD

**Issue by richardgroves** [MicrosoftDocs/vsts-docs#980]
The run.sh script referenced will fail if the path it is in has a space in it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c9cb3bd5-5c72-4ad6-8566-3bc4527112ce
* Version Independent ID: 4c0f61d9-0d61-83e6-ece5-4d96ca91e9d1
* Content: [Deploy a build and release agent on macOS](https://docs.microsoft.com/en-us/vsts/pipelines/agents/v2-osx?view=vsts#service_files)
* Content Source: [docs/pipelines/agents/v2-osx.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/pipelines/agents/v2-osx.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by andyjlewis** [comment]
How is this issue different than what happens for any other script?

**Comment by richardgroves** [comment]
The script doesn't take arguments, so I can't wrap them in "s manually and scripts that want to work widely take care of making sure that they wrap up paths in "s internally when they capture and pass them around.

**Comment by richardgroves** [comment]
```
Last login: Tue Jun  5 14:36:39 on ttys007
Richards-MacBook-Pro:Folder With Spaces In The Name richard$ cd vsts-agent-osx-x64-2.134.2
Richards-MacBook-Pro:vsts-agent-osx-x64-2.134.2 richard$ ls
bin		config.sh	env.sh		externals	run.sh
Richards-MacBook-Pro:vsts-agent-osx-x64-2.134.2 richard$ pwd
/Users/richard/Folder With Spaces In The Name/vsts-agent-osx-x64-2.134.2
Richards-MacBook-Pro:vsts-agent-osx-x64-2.134.2 richard$ ./run.sh
./run.sh: line 27: /Users/richard/Folder: No such file or directory
Richards-MacBook-Pro:vsts-agent-osx-x64-2.134.2 richard$
```

**Comment by chrisrpatterson** [comment]
ok that run script.  I would suggest you not do this as your users running builds or releases could end up with failures if they don't quote everything.

**Comment by richardgroves** [comment]
You might want to update the documentation to not suggest using it then.

<img width="771" alt="screen shot 2018-06-05 at 15 21 10" src="https://user-images.githubusercontent.com/715058/40981970-213dc8d4-68d4-11e8-9aec-f16c83a28a9c.png">

**Comment by vtbassmatt** [comment]
Doc fix in progress.
