### ISSUE TITLE
Need Scope for TFS/DistributedTask/TaskAgentRestClient

### ISSUE THREAD

**Issue by kmunusam** [MicrosoftDocs/vsts-docs#981]
Trying to Retrieve Variablegroups details using Rest Client, code below:
VSS.require(["VSS/Controls", "VSS/Service", "ReleaseManagement/Core/RestClient","TFS/DistributedTask/TaskAgentRestClient"],
            function (Controls, VSS_Service, RM_WebApi,DTClient) {
            
			var DTClients = VSS_Service.getCollectionClient(DTClient.TaskAgentHttpClient);
	DTClients.getVariableGroupsById(Project_name,variablegroupID).then(function(DTData){
		console.log(DTData);
		
	});

Facing TFS.WebApi.Exception: TF400813: The user 'xxxxx' is not authorized to access this resource.  Defined below scopes in my manifest: 
"vso.build_execute",
        "vso.release_execute",
		"vso.agentpools_manage",
		"vso.agentpools",
		"vso.project_manage"

Please help me with the right scope

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d8b703fe-8982-4284-6db0-ef33abac08a4
* Version Independent ID: 0fc84d11-1c32-0a49-04ec-641b68f44886
* Content: [Extension Manifest Reference](https://docs.microsoft.com/en-us/vsts/extend/develop/manifest?view=vsts#scopes)
* Content Source: [docs/extend/develop/manifest.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/extend/develop/manifest.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by elbatk** [comment]
Hi @kmunusam , I've reached out to the product team and I'll let you know what they say!

**Comment by kmunusam** [comment]
Hi Steve, 

Do I have any update on this?

Thanks,
Kamesh

**Comment by kmunusam** [comment]
Waiting for the reply?

**Comment by kmunusam** [comment]
Any update..?

**Comment by elbatk** [comment]
Hi @kmunusam , sorry I've been out of the office. This question is more suitable for the product team, you can post it here in the [VSTS Developer Community page](https://developercommunity.visualstudio.com/spaces/21/index.html). Sorry I can't help more, but they should be able to answer it there!
