### ISSUE TITLE
Deploy or upgrade

### ISSUE THREAD

**Issue by AlexanderViken** [MicrosoftDocs/vsts-docs#982]
Is it possible to have this task  do a check to see if an service fabric application already is deployed? If it is not - deploy a fresh new copy, if it is, upgrade it. It's a small pain when you for instance add a new environment to your pipeline and It would remove a few manual steps needed from how it is working now.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7068e469-201e-c820-4d27-b798ea799b70
* Version Independent ID: d6bb717a-1c44-43a1-c7a5-9616b257c0e0
* Content: [Service Fabric Application Deployment task for use in the phases of all of your build and release definitions in Microsoft VSTS and TFS](https://docs.microsoft.com/en-us/vsts/pipelines/tasks/deploy/service-fabric-deploy?view=vsts)
* Content Source: [docs/pipelines/tasks/deploy/service-fabric-deploy.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/pipelines/tasks/deploy/service-fabric-deploy.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment]
Thank you for your feedback. I have passed this on to the product team for advice.

**Comment by RoopeshNair** [comment]
@AlexanderViken - we do deploy fresh if the application is not found and upgrade if already existing. Make sure you check upgrade checkbox available after enabling "Override all publish profile upgrade setttings"

**Comment by artisticcheese** [comment]
Per Service Fabric documentation upgrades based on compose file are not supported in Service Fabric 
(https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-docker-compose) 


> Because this support is in preview, only a subset of Compose directives is supported. For example, application upgrades are not supported. However, you can always remove and deploy applications instead of upgrading them.

Is application documentation is outdated?

**Comment by RoopeshNair** [comment]
@artisticcheese  - thanks, it needs update :)

**Comment by artisticcheese** [comment]
@RoopeshNair  
1. What "upgrade" under Advanced setting checkbox is for if per your statement service is always upgraded if it already exits.
2. How do you specify registry username/password in this task? Powershell module has this option to be specified as parameter but I don't see any option in this task
