### ISSUE TITLE
Broken link https://visualstudio/extend/ide/overview.md

### ISSUE THREAD

**Issue by xjlim** [MicrosoftDocs/vsts-docs#983]
Found in [extend](https://docs.microsoft.com/en-us/vsts/extend/index?view=vsts) docs [TOC](https://github.com/MicrosoftDocs/vsts-docs/blob/d46d2a1372ab71c64032c0014a0575850d31884a/docs/extend/toc.yml#L187)

**Comment by elbatk** [comment]
Thanks @xjlim ! This should be fixed within 5-10 minutes with the latest push and it should go here: https://docs.microsoft.com/en-us/vsts/integrate/ide/extensions/overview?view=vsts
