### ISSUE TITLE
SourceLink page is out of date

### ISSUE THREAD

**Issue by CoolDadTx** [MicrosoftDocs/vsts-docs#984]
The page content seem out of date. It mentions publishing the symbols via VSTS but that isn't really source linking from what I understand. The page is specifically about GitHub but there is a version available for VSTS Git as well from Microsoft (pre release). It would be nice if the docs were updated to reference it instead. The steps have changed quite a bit as you don't need the listed package anymore and there are some project settings you have to add. It would be nice if the docs were updated to refer to the MS packages (when available) and the steps clarified to get this working. Finding that documentation right now is difficult and requires some trial and error.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 728b7c25-2ef7-3807-b898-b9024ba297e2
* Version Independent ID: 4b2eda64-1f32-fdf8-ee09-420dbb8b9f4d
* Content: [Setting up GitHub Source Linking with VSTS Build & VSTS Symbol Server](https://docs.microsoft.com/en-us/vsts/package/symbols/setting-up-github-sourcelinking?view=vsts)
* Content Source: [docs/package/symbols/setting-up-github-sourcelinking.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/package/symbols/setting-up-github-sourcelinking.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by elbatk** [comment]
Hi @CoolDadTx , thanks for the input here! I've added a work item on our backlog to get this updated and will discuss it with the product team at our meeting (which happens to be tomorrow)
