### ISSUE TITLE
Documentation not finished

### ISSUE THREAD

**Issue by glatzert** [MicrosoftDocs/vsts-docs#987]
The documentation seems unfinished and it should be added how to use give Teams and buidls Access to Feeds ans how the packages can be shared with everyone (which might be important)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e77774e-012a-45cc-d566-7170d86003cd
* Version Independent ID: 778dafea-bf98-3292-f451-d82ce8db5bbc
* Content: [Secure and share packages using feed permissions](https://docs.microsoft.com/en-us/vsts/package/feeds/feed-permissions?view=vsts)
* Content Source: [docs/package/feeds/feed-permissions.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/package/feeds/feed-permissions.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by elbatk** [comment]
Hi @glatzert , thanks for the input here! I've added a work item on our backlog to get this updated and will discuss it with the product team at our meeting (which happens to be tomorrow)

**Comment by glatzert** [comment]
Thank you.
I'd volunteer as "does this really work"-tester ;)

**Comment by elbatk** [comment]
Hi @glatzert , we gave it a small update, check it out and let us know what you think. Closing this issue if you think it's good!

**Comment by glatzert** [comment]
Hi @elbatk  i think it's more useful than before, but for [TFS-2018](https://docs.microsoft.com/en-us/vsts/package/feeds/feed-permissions?view=tfs-2018) there's a small Problem:

> If you want to make the packages in a feed available to all users in your VSTS account, create or select a view that contains the packages you want to share and ensure its visibility is set to People in my account.

Does not apply - at least not to my Version - to TFS2018.

**Comment by elbatk** [comment]
Adding @alexmullans so he can comment on availability/versions for us!
