### ISSUE TITLE
Missing inline option

### ISSUE THREAD

**Issue by jabteles** [MicrosoftDocs/vsts-docs#988]
Hi,

I notice on the "YAML snippet" part of this documentation that it has the input argument "inlineScript", but on the "PowerShell on Target Machines" task version 1.* I have available on my TFS 2018 Update 1 I don't see any possibility to add an inline script or either the scriptpath, only the possibility to fill "PowerShell Script" editbox which says "Location of the PowerShell script on the target machines or on a UNC path like C:\BudgetIT\Web\Deploy\Website.ps1".

Apreciate your help since I would like to run an inline script on a target computer, instead of having a local or UNC .ps1 script.

Regards,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2cf2fff2-d778-760c-d1a0-428a07d3590e
* Version Independent ID: f00e3009-1c3b-dd16-e9fc-50d1e58c83a8
* Content: [PowerShell on Target Machines task for use in the phases of all of your build and release definitions in Microsoft VSTS and TFS](https://docs.microsoft.com/en-us/vsts/pipelines/tasks/deploy/powershell-on-target-machines?view=vsts)
* Content Source: [docs/pipelines/tasks/deploy/powershell-on-target-machines.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/pipelines/tasks/deploy/powershell-on-target-machines.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment]
Thank you for your feedback. I will pass this on to the product team and update the topic based on their response.

**Comment by RoopeshNair** [comment]
Inline script option is enabled only since 3.* version of the PowerShell on Target task, which is by the way still in preview. Unfortunately, you will not able to run inlinescript with 1.* version of the task.

**Comment by jabteles** [comment]
Yes, for now, copy the file on the remote machine is my workaround but it creates some unnecessary files.

How can I upgrade my 1.* version to 3*?

**Comment by RoopeshNair** [comment]
There are significant changes since 2.* version of the task. I'm not sure if you can update the version in your TFS with 3.* version of the task.  Let me check and get back.

**Comment by RoopeshNair** [comment]
@jabteles  - the newer version of the tasks are just rolling out as a preview in VSTS. And they aren't tested with TFS 2018. My recommendation would be to use Windows File Copy task first followed by PowerShell on target task as mentioned earlier.
