### ISSUE TITLE
Resource link "Build Visual Studio extensions" broken

### ISSUE THREAD

**Issue by jbreadner** [MicrosoftDocs/vsts-docs#991]
The server name is 'visualstudio', which is not a FQDN.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f699a190-5e7e-1103-8d9d-c3d58e698e3a
* Version Independent ID: 1e54fe20-7e4d-d5ff-1682-8659f7a8fba8
* Content: [Core Client SDK](https://docs.microsoft.com/en-us/vsts/extend/reference/client/core-sdk?view=vsts)
* Content Source: [docs/extend/reference/client/core-sdk.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/extend/reference/client/core-sdk.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by elbatk** [comment]
Hey @jbreadner , I've updated the link to go to this page: https://docs.microsoft.com/en-us/visualstudio/extensibility/starting-to-develop-visual-studio-extensions

Thanks!
