### ISSUE TITLE
Custom conditions in Release tasks for TFS 2017 update 3.1

### ISSUE THREAD

**Issue by Nirosha927** [MicrosoftDocs/vsts-docs#992]
Microsoft documentation says custom conditions are available in release tasks for TFS 2017.3. So I have upgraded to TFS 2017.3 from TFS2017.2. But didn't find that feature in release tasks. Is this feature available for TFS2017 update3?
Please find the documentation in the below link.
https://docs.microsoft.com/en-us/vsts/pipelines/process/conditions?view=vsts#enable-a-custom-condition

**Comment by alexhomer1** [comment]
Thank you for your feedback. I have passed this on to the product team for advice.

**Comment by matthiasverhelst** [comment]
I have exactly the same problem in TFS 2017.3. I was looking for the custom conditions option in the Control Options, but it's not there. The only options are 'Enabled', 'Continue on error', 'Always run' and the Timeout variable. Is it something that needs to be enabled explicitly in TFS 2017.3 or is it a mistake in the documentation?

**Comment by alexhomer1** [comment]
The product team report that custom conditions were added in TFS 2018. I will update the topic to reflect this.
