### ISSUE TITLE
Broken link for Code Search hardware requirements

### ISSUE THREAD

**Issue by jallman112** [MicrosoftDocs/vsts-docs#993]
In section Hardware Requirements for Multi Server Deployments, the link to "For more details, see hardware requirements for Code Search." results in a 404 error.

https://docs.microsoft.com/en-us/tfs/server/requirements#multi-server-deployments

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 641b37fc-f117-aca0-32f4-8ea9b73e9d71
* Version Independent ID: 211130c6-43b8-f47f-3589-cb4d2a330231
* Content: [Requirements and compatibility](https://docs.microsoft.com/en-us/tfs/server/requirements#multi-server-deployments)
* Content Source: [docs/server/requirements.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/server/requirements.md)
* Product: **devops-server**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by jallman112** [comment]
Looks like the ".md" strikes again.

It would appear the link should be this: https://docs.microsoft.com/en-us/vsts/project/search/administration?view=vsts#hardware-recommendations

**Comment by elbatk** [comment]
@jallman112 whew, you scared me because I thought I fixed all of these. These were fixed in our master branch but just not pushed to live site - these should all be fixed (hopefully) in the next 5-10 minutes. If you find another one after today then you really will scare me :P
