### ISSUE TITLE
Maven Artifact fails to publish

### ISSUE THREAD

**Issue by shanelile** [MicrosoftDocs/vsts-docs#994]
Using the sample config above, I'm running into issues getting the artifact to actually publish to maven. It seems like gradle doesn't like something about how the artifact is configured and results in an error like:

Invalid publication 'myPublication': multiple artifacts with the identical extension and classifier ('aar', 'null')

What version of gradle was the sample written for? I'm seeing this on version 2.8 in the version that ships with .androidproj file templates in Visual Studio.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 52da1009-6733-d555-3c00-1a1bd77f1759
* Version Independent ID: 72b916de-2836-460b-2889-67981ffea5a4
* Content: [Publish a Maven artifact using Gradle and VSTS](https://docs.microsoft.com/en-us/vsts/package/gradle/publish-package-gradle?view=vsts)
* Content Source: [docs/package/gradle/publish-package-gradle.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/package/gradle/publish-package-gradle.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by shanelile** [comment]
Looks like this was a problem on my side. I tried to integrate the publishing changes into an existing build.gradle file for my project. It works if I only have what's in the sample in a build.gradle file higher up in my repository.

**Comment by elbatk** [comment]
Ah, glad you figured it out @shanelile :)
