### ISSUE TITLE
GitHub link is either wrong or private

### ISSUE THREAD

**Issue by yashints** [MicrosoftDocs/vsts-docs#995]
When I click on https://github.com/Microsoft/vsts-tasks/tree/master/Tasks/CopyFiles to see the details, I get 404 from GitHub

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 87686bea-7c46-cd47-d1a9-128e16b63a23
* Version Independent ID: ace78317-e562-e35d-781d-23cd7d2dfff2
* Content: [CI Build in code using YAML](https://docs.microsoft.com/en-us/vsts/pipelines/build/yaml?view=vsts)
* Content Source: [docs/pipelines/build/yaml.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/pipelines/build/yaml.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by steved0x** [comment]
@yashints I think that that section moved and the new link is: https://github.com/Microsoft/vsts-tasks/tree/master/Tasks/CopyFilesV2

I have assigned this issue to the author of the article and they can confirm.

**Comment by yashints** [comment]
Thanks Steve
