### ISSUE TITLE
adding .vsts-ci.yml file and pushing changes is not creating a build definition :(

### ISSUE THREAD

**Issue by has-taiar** [MicrosoftDocs/vsts-docs#996]
I am following the documentation here and doing all the steps as described but no build defintion is created from my .vsts-ci.yml 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6cfd9f66-a0f8-8369-f19e-c3446c301bcd
* Version Independent ID: 4f666589-3917-3424-bd3b-83b658e3a56d
* Content: [Build a repo with YAML file](https://docs.microsoft.com/en-us/vsts/pipelines/get-started-yaml?view=vsts&tabs=gitvsts)
* Content Source: [docs/pipelines/get-started-yaml.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/pipelines/get-started-yaml.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by vijayma** [comment]
A few things to check:
- YAML is still in preview. You need to turn the preview toggle on. Your profile -> Preview features -> Account level.
- Is the file at the root of your repo and in the default branch of the repo?

**Comment by has-taiar** [comment]
Thanks the issue was that I could not see the feature in my Preview Features because it only shows up in when you select Account form the drop down list. Closing this issue

**Comment by andyjlewis** [comment]
re-opening the issue until we add mention about preview feature needing to be turned on

**Comment by vlef** [comment]
There is now a mention of the preview feature at the top of the page: this issue should be closed.
