### ISSUE TITLE
This extension is not installable on any currently installed products

### ISSUE THREAD

**Issue by Grandizer** [MicrosoftDocs/vsts-docs#997]
I went through the steps and it all seemed straight forward until I went to install the extension in our VSTS.  Here is the log:

6/7/2018 8:40:40 AM - Microsoft VSIX Installer
6/7/2018 8:40:40 AM - -------------------------------------------
6/7/2018 8:40:40 AM - vsixinstaller.exe version:
6/7/2018 8:40:40 AM - 15.7.105+ga2c5d563c6
6/7/2018 8:40:40 AM - -------------------------------------------
6/7/2018 8:40:40 AM - Command line parameters:
6/7/2018 8:40:40 AM - C:\program files (x86)\microsoft visual studio\installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\VSIXInstaller.exe,C:\Users\kevin\AppData\Local\Packages\Microsoft.MicrosoftEdge_8wekyb3d8bbwe\TempState\Downloads\KevinLGrigsby.my-first-extension-1.0.0 (1).vsix
6/7/2018 8:40:40 AM - -------------------------------------------
6/7/2018 8:40:40 AM - Microsoft VSIX Installer
6/7/2018 8:40:40 AM - -------------------------------------------
6/7/2018 8:40:42 AM - Initializing Install...
6/7/2018 8:40:43 AM - Extension Details...
6/7/2018 8:40:43 AM - 	Identifier         : my-first-extension
6/7/2018 8:40:43 AM - 	Name               : My First Extension
6/7/2018 8:40:43 AM - 	Author             : KevinLGrigsby
6/7/2018 8:40:43 AM - 	Version            : 1.0.0
6/7/2018 8:40:43 AM - 	Description        : A sample Visual Studio Services extension
6/7/2018 8:40:43 AM - 	Locale             : en-US
6/7/2018 8:40:43 AM - 	MoreInfoURL        : 
6/7/2018 8:40:43 AM - 	InstalledByMSI     : False
6/7/2018 8:40:43 AM - 	SupportedFrameworkVersionRange : [0.0,2147483647.2147483647]
6/7/2018 8:40:43 AM - 
6/7/2018 8:40:43 AM - 	SignatureState     : Unsigned
6/7/2018 8:40:43 AM - 	Supported Products : 
6/7/2018 8:40:43 AM - 		Microsoft.VisualStudio.Services
6/7/2018 8:40:43 AM - 			Version : 
6/7/2018 8:40:43 AM - 
6/7/2018 8:40:43 AM - 	References         : 
6/7/2018 8:40:43 AM - Signature Details...
6/7/2018 8:40:43 AM - 	Extension is not signed.
6/7/2018 8:40:43 AM - 
6/7/2018 8:40:43 AM - Searching for applicable products...
6/7/2018 8:40:43 AM - Found installed product - Microsoft Visual Studio Professional 2015
6/7/2018 8:40:43 AM - Found installed product - Microsoft Visual Studio Community 2015
6/7/2018 8:40:43 AM - Found installed product - Microsoft Visual Studio 2015 Shell (Integrated)
6/7/2018 8:40:43 AM - Found installed product - Global Location
6/7/2018 8:40:43 AM - Found installed product - ssms
6/7/2018 8:40:43 AM - Found installed product - Visual Studio Professional 2017
6/7/2018 8:40:43 AM - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.App.GetInstallableData(String vsixPath, Boolean isRepairSupported, IEnumerable`1& skuData)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 14955ee9-29f2-46fe-3a8d-a42666f53ffc
* Version Independent ID: 5d417cd0-a671-ee30-8fca-5f8b0addd328
* Content: [Develop a web extension for VSTS](https://docs.microsoft.com/en-us/vsts/extend/get-started/node?view=vsts)
* Content Source: [docs/extend/get-started/node.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/extend/get-started/node.md)
* Product: **devops**
* GitHub Login: @wismythe
* Microsoft Alias: **wismythe**

**Comment by elbatk** [comment]
@Grandizer It looks like VSIXInstaller is used to install extensions for Visual Studio, not VSTS. Are you installing the extension from the Marketplace?

**Comment by Grandizer** [comment]
Actually take from here: https://docs.microsoft.com/en-us/vsts/extend/get-started/node?view=vsts and is a VSTS extension.

**Comment by willsmythe** [comment]
It looks like @Grandizer is somehow downloading the .vsix and then running it, which won't work since the VSIX installer is not used to install VSTS extensions. @Grandizer - after you click "Get it free", you should be presented with a list of VSTS accounts that you can install your extension into. Is this not happening for you?

**Comment by Grandizer** [comment]
After some attempts at getting it to work I wound up going the REST route for what I needed to do.  So no Extension needed at all.  Thank you for the response.

**Comment by infact** [comment]
How can I migrate my TFS extension to Azure DevOps. Is that even supported ?Our TFS 2015 extension has almost 100 plus text boxes,  and 3 to 5 custom buttons that will post data to our API.I am exploring the possibilities of quickly migrating to VSO online azureDevops. Any comments, pointers, examples to get me towards the right direction ?

**Comment by willsmythe** [comment]
Are you referring to the legacy TFS extension model? By this, I mean the model that doesn’t rely on a vss-extension.json manifest file and is not packaged as a .vsix file?

Will

**Comment by elbatk** [comment]
Going to go ahead and close this one as I don't think there's a bug/defect with the docs! Thanks everyone!
