### ISSUE TITLE
Test Publish docs do not address dotnet CLI test output

### ISSUE THREAD

**Issue by timheuer** [MicrosoftDocs/vsts-docs#999]
In following this documentation it is focused on MSBuild but does not address the ```dotnet``` CLI user that uses ```dotnet test``` commands - like me :-).

You have to tell the output to produce TRX files for publishing or else this doesn't work.  I could not find appropriate documentation on using ```dotnet test``` with VSTS.  I had to find the information on a blog: https://medium.com/@bridgesquared/dotnet-core-c37e96a11bff and would love to have this officially in this same documentation point.  

Thanks to @abelsquidhead for helping me track down the right execution, but this should be in the docs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba91e46a-de53-c0c1-f7f7-c02e797d527c
* Version Independent ID: 6f478148-461f-694a-ed82-deb4d731854e
* Content: [VSTS and TFS Build and Test - Publish Test Results task](https://docs.microsoft.com/en-us/vsts/pipelines/tasks/test/publish-test-results?view=vsts)
* Content Source: [docs/pipelines/tasks/test/publish-test-results.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/pipelines/tasks/test/publish-test-results.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment]
Thank you for your feedback. I will pass this on to the product team and update the topic based on their response.

**Comment by alexhomer1** [comment]
The product team tell me they are planning to update these topics and will incorporate your suggestion. Thank you.

**Comment by trajano** [comment]
Actually it doesn't do it for JUnit either.  I was checking the coverage files and it does contain the output, but it does not appear on the published reports.
